### ISSUE TITLE
x/build/internal/task: provide a release archive with all the syso files, or release the files separately

### ISSUE THREAD

**Issue by blorente** [golang/go#54174]
### What version of Go are you using (`go version`)?

1.17 SDK, via Bazel's `rules_go`: https://github.com/bazelbuild/rules_go.

### Does this issue reproduce with the latest release?

Yes, the latest release (1.18.4  from go.dev/dl) has that issue.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/blorente/Library/Caches/go-build"
GOENV="/Users/blorente/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/blorente/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/blorente/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.18.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.18.4/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.18.4"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0b/d4kmqgkx0w5bs1qb8cktwfpw0000gn/T/go-build1763548739=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I tried to build a binary for linux using the musl C toolchain.

rules_go tries to build the standard library by downloading a copy of the sdk in the host architecture (e.g., it would be https://go.dev/dl/go1.18.4.darwin-amd64.tar.gz for my architecture), and then doing roughly:

- Create a new dir, let's call it `foo`.
- Copy `src` and `pkg` there.
- Set `foo` as the new `GOROOT`, and set `GOOS` and `GOARCH` to the target platform (in this case, `GOOS=linux, GOARCH=x86_64`
- Build the standard library by calling `go install`.

This builds correctly with musl.

### What did you expect to see?

However, if I try to link a binary that uses the race detector to this standard library, it will fail to find libc-specific symbols from the thread sanitiser. This issue has been solved in the precompiled `syso` files for race, in `src/runtime/race`. 

And, in fact, if reproduce the process but manually place `race_{GOOS}_{GOARCH}.syso` in `src/runtime/race`, the `syso` is packed into the `race.a` archive, and the binary links successfully.
Since the go sdk is supposed to cross-compile, I would have expected this operation to succeed.

### What did you see instead?

Since [this tool](https://github.com/golang/build/blob/0a9b2ecb0faa38b74e988adf7e43685411647789/internal/task/buildrelease.go#L163-L174) strips the syso for platforms other than the host, the syso can't end up in the `.a` archive for the package.

### Further info

I'm preparing to contribute a fix to `rules_go`, which involves getting a hold of the `syso`s somehow. My question is:

**What would be the recommended way to get those syso files?**

Should I download the `src` sdk (e.g. https://go.dev/dl/go1.18.4.src.tar.gz) and incur the bandwidth penalty? Should I download the binaries directly from the GitHub mirror, or should I do something else?

**Comment by dmitshur** [comment]
CC @golang/release.

**Comment by blorente** [comment]
Sorry not answering before. There is indeed no more to do, thanks for the investigation.
