### ISSUE TITLE
cmd/compile: enable Duff's device on darwin/arm64

### ISSUE THREAD

**Issue by erifan** [golang/go#54189]
This is disabled because Darwin linker does not support BR26 relocation with non-zero addend, see https://github.com/golang/go/issues/16724. I wonder if we can find a way to work around this issue, since the performance impact of Duff's device is pretty obvious.

**Comment by dmitshur** [comment]
CC @golang/compiler.

**Comment by cherrymui** [comment]
There have been several changes to the Go linker. I'm not sure the BR26 issue is still relevant. We can try to enable it.

If it still matters, we can use the label symbol mechanism, which is what we do on Windows ARM64.

I can give it a try.
