### ISSUE TITLE
runtime: cpu suboption for GODEBUG is not documented with the others for GODEBUG

### ISSUE THREAD

**Issue by laboger** [golang/go#54183]
I've seen mention of using GODEBUG=cpu to disable certain cpu capabilities in various issues. I expected to find it described in runtime/extern.go where the other GODEBUG suboptions are documented, but it is not.

**Comment by mknyszek** [comment]
Where do you suggest the documentation should go? (I agree it should be documented.)

**Comment by ianlancetaylor** [comment]
I think it pretty much has to go in the runtime package.  Which is what @laboger suggests.  It's a reasonable location, and where else could it go?
