### ISSUE TITLE
x/build: silent TryBot failure on linux-arm*-aws with err=unknown EC2 vm type

### ISSUE THREAD

**Issue by findleyr** [golang/go#54204]
Investigating why I didn't get a TryBot result for https://go-review.googlesource.com/c/tools/+/419954, I see that there was actually a new failure mode on `linux-arm*-aws` builders: `err=unknown EC2 vm type: m6g.xlarge-standard-16`

https://farmer.golang.org/try?commit=4bbeb083)

```
linux-arm-aws | FAIL | linux-arm-aws rev 1b7e71e8 (sub-repo tools rev 4bbeb083) (trybot set for Ide3972a); failed, 5s ago ...   2022-08-02T17:50:40Z finish_checking_for_snapshot after 25ms   2022-08-02T17:50:40Z get_buildlet    2022-08-02T17:50:41Z finish_get_buildlet after 97.7ms; err=unknown EC2 vm type: m6g.xlarge-standard-16
-- | -- | --


linux-arm-aws	FAIL	
[linux-arm-aws](https://github.com/golang/go/wiki/DashboardBuilders) rev [1b7e71e8](https://go-review.googlesource.com/#/q/1b7e71e8ae824c2ac661dd793bca29cf60378936) (sub-repo tools rev [4bbeb083](https://go-review.googlesource.com/#/q/4bbeb083f935716a822e24d45f8becc25d180a9d)) ([trybot set](https://farmer.golang.org/try?commit=4bbeb083) for [Ide3972a](https://go-review.googlesource.com/#/q/tools~master~Ide3972a94c129bcce554c10dd167df01c3040d31)); [failed](https://farmer.golang.org/temporarylogs?name=linux-arm-aws&rev=1b7e71e8ae824c2ac661dd793bca29cf60378936&st=0xc031534540&subName=tools&subRev=4bbeb083f935716a822e24d45f8becc25d180a9d), 5s ago
...
  2022-08-02T17:50:40Z finish_checking_for_snapshot after 25ms
  2022-08-02T17:50:40Z get_buildlet 
  2022-08-02T17:50:41Z finish_get_buildlet after 97.7ms; err=unknown EC2 vm type: m6g.xlarge-standard-16
  ```
  
  Questions:
  - what is this failure?
  - why didn't I get a TryBot result? Is this failure mode prevent normal processing of the results?
  
  I'll see if I can re-run trybots, but wanted to capture the failure mode.
  
  CC @golang/release

**Comment by findleyr** [comment]
Err, TryBots just restarted, so maybe coordinator is being deployed... (perhaps I should have waited a bit before filing...)

**Comment by dmitshur** [comment]
This is being fixed by [CL 420755](https://go.dev/cl/420755) right now.

**Comment by findleyr** [comment]
Great, will leave this open for visibility and close after TryBots pass.

**Comment by findleyr** [comment]
Seems like this is fixed now. At least, my TryBots passed. @dmitshur do you want to leave this up a bit longer? It seems some of the backlog is still being processed?

**Comment by dmitshur** [comment]
I agree the AWS builder issue is resolved (e.g., trybots passed on CL 420816), so let's mark this as closed to reflect current status. (We can unpin it a bit later.)
