### ISSUE TITLE
affected/package: Coverity Scan [Security] - Risky cryptographic hashing function

### ISSUE THREAD

**Issue by raghvendra-dixit** [golang/go#54207]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.17
Image source for golang:
us-docker.pkg.dev/google.com/api-project-999119582588/go-boringcrypto/golang:1.17.11b7
</pre>

### What operating system and processor architecture are you using (`go env`)?
Linux
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you see instead?
It's a coverity scan issue highlighted, related to security:
Details: A use of a weak hashing algorithm was detected. There exist well known ways to produce collisions on the hashes.
In golang.​org/x/crypto/ssh.​FingerprintLegacyMD5(golang.​org/x/crypto/ssh.​PublicKey, string): A risky hashing function was used. This may allow an attacker to produce collisions on the hash or execute length extension attacks.
<img width="1678" alt="image" src="https://user-images.githubusercontent.com/93790023/182454116-83e7f9a4-111d-490c-ba0f-c2cf20617615.png">

**Comment by seankhliao** [comment]
please don't waste our time with these

**Comment by seankhliao** [comment]
Duplicate of #54205
