### ISSUE TITLE
affected/package: SAST coverity scan [security] - Crypto - Risky cryptographic function

### ISSUE THREAD

**Issue by raghvendra-dixit** [golang/go#54206]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.17

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you expect to see?
A use of a weak cryptographic method was detected. There exist known ways to compromise the security of the encrypted data.
In golang.​org/x/crypto/ssh.​newTripleDESCBCCipher([]byte, []byte, []byte, golang.​org/x/crypto/ssh.​directionAlgorithms): A risky cryptographic function was used. This may allow an attacker to decrypt encrypted data as the quality of the cryptographic protection is suspect.
<img width="1677" alt="image" src="https://user-images.githubusercontent.com/93790023/182446731-db81d03f-fb16-4001-9117-03dc2ffd3300.png">

**Comment by seankhliao** [comment]
Duplicate of #54205
