### ISSUE TITLE
affected/package: SAST coverity scan [security] - Crypto -  Risky cryptographic function

### ISSUE THREAD

**Issue by raghvendra-dixit** [golang/go#54205]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.17
</pre>

### What operating system and processor architecture are you using (`go env`)?
Linux
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you see instead?

A use of a weak cryptographic method was detected. There exist known ways to compromise the security of the encrypted data.
In golang.​org/x/crypto/ssh.​newRC4([]byte, []byte): A risky cryptographic function was used. This may allow an attacker to decrypt encrypted data as the quality of the cryptographic protection is suspect.
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/93790023/182446063-98a2706a-a73a-4a03-b629-edebeb49a1cb.png">

**Comment by seankhliao** [comment]
> 	// Ciphers from RFC4345, which introduces security-improved arcfour ciphers.
	// They are defined in the order specified in the RFC.
	"arcfour128": {16, 0, streamCipherMode(1536, newRC4)},
	"arcfour256": {32, 0, streamCipherMode(1536, newRC4)},

	// Cipher defined in RFC 4253, which describes SSH Transport Layer Protocol.
	// Note that this cipher is not safe, as stated in RFC 4253: "Arcfour (and
	// RC4) has problems with weak keys, and should be used with caution."
	// RFC4345 introduces improved versions of Arcfour.
	"arcfour": {16, 0, streamCipherMode(0, newRC4)},


Working as intended.
