### ISSUE TITLE
affected/package: `bufio.Reader` add comment note about concurrent read

### ISSUE THREAD

**Issue by Trim21** [golang/go#54210]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.19

</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

doesn't matter

### What did you do?

I read new 1.19 release note and try to wrap `crypto/rand.Reader` with `bufio.NewReader`.

In the old code, I just call `rand.Read([]byte)` in multi goroutine and everything works fine. But to buffer it, now I need to create a global variable with `var reader = bufio.NewReader(rand.Reader)` and call `io.ReadFull(reader, []byte)`.

And obverious, `bufio.Reader` is not thread safe and may panic when reading bytes

https://github.com/golang/go/blob/29b9a328d268d53833d2cc063d1d8b4bf6852675/src/bufio/bufio.go#L247-L250

The comment only note about broken underlying reader, not concurrent read.

So I suggess add some note about this.

**Comment by seankhliao** [comment]
Unless otherwise documented, by default the standard library functions are not safe for concurrent use.
