### ISSUE TITLE
cmd/go: internal/mmap/mmap.go:30:9: undefined: mmapFile on js-wasm

### ISSUE THREAD

**Issue by p-kraszewski** [golang/go#54219]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.4 freebsd/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, on 2 different operating systems

- FreeBSD 13.1 with Go 1.18.4 from packages
- Arch Linux with Go 1.19 from packages - the error messages are exactly the same, didn't copy output twice.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="freebsd"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="freebsd"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go118"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go118/pkg/tool/freebsd_amd64"
GOVCS=""
GOVERSION="go1.18.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="cc"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3287959224=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```bash
> git describe --tags --long --all
tags/go1.19-0-g43456202a1

> ./buildall.bash '(freebsd|linux|js)-(amd64|arm64|wasm)'
```

### What did you expect to see?

```
Building Go cmd/dist using /usr/local/go118. (go1.18.4 freebsd/amd64)
Building Go toolchain1 using /usr/local/go118.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for freebsd/amd64.
---
Installed Go for freebsd/amd64 in /home/pawel/.go
Installed commands in /home/pawel/.go/bin

### Building linux-amd64

### Building linux-arm64

### Building freebsd-amd64

### Building freebsd-arm64

### Building js-wasm

```

### What did you see instead?

```
Building Go cmd/dist using /usr/local/go118. (go1.18.4 freebsd/amd64)
Building Go toolchain1 using /usr/local/go118.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for freebsd/amd64.
---
Installed Go for freebsd/amd64 in /home/pawel/.go
Installed commands in /home/pawel/.go/bin

### Building linux-amd64

### Building linux-arm64

### Building freebsd-amd64

### Building freebsd-arm64

### Building js-wasm
# cmd/go/internal/mmap
cmd/go/internal/mmap/mmap.go:30:9: undefined: mmapFile

Build(s) failed.
```

**Comment by seankhliao** [comment]
please try this with the upstream source tree.

**Comment by p-kraszewski** [comment]
Checked. All the details are in my [other bug report](https://github.com/golang/go/issues/54221). 

I resolved the other problem by un-hiding `goroot` directory (from `.goroot`). It has no influence on the issue reported here.

**Comment by seankhliao** [comment]
cc @bcmills @matloob not sure if js is a supported target for cmd/go?

**Comment by bcmills** [comment]
> not sure if js is a supported target for cmd/go?

It looks like the `js/wasm` builder has been configured to skip `cmd/go` since [CL 121938](https://go.dev/cl/121938), although it's not clear to me why that's useful. (Shouldn't the `js/wasm` builder be trivial to shard more widely?)

However, there isn't much point in building `cmd/go` for `js/wasm`, given that it relies on executing subprocesses.

As long as the fixes are small, I think it would be fine to tweak the `cmd/go` source to once again build and pass (or skip) tests on `js/wasm`, and then re-enable its tests on the builder.
