### ISSUE TITLE
builtin/error: return value mismatch between "error interface" and custom error struct

### ISSUE THREAD

**Issue by pomeh** [golang/go#54229]
### What version of Go are you using (`go version`)?

<pre>
1.19 (from online Go playground: https://go.dev/play/)
</pre>

### Does this issue reproduce with the latest release?
Yes (using "Go dev branch" from Go playground)

### What operating system and processor architecture are you using (`go env`)?
Unknown (Go Playground handle this for me)

### What did you do?

I have a `CustomError` struct with an error:

```go
type CustomError struct {
	error
	errcode string
}
```

I have 2 functions, one returning a builtin error (if any), and one other returning a `CustomError` (if any).

```go
func A() error {
	return nil
}
func B() *CustomError {
	return nil
}
```

I call both function in a row, and store both error into the same variable of type `error`.

```go
        // new variable "err"
	err := A()

        // reuse previous variable "err"
	err = B()
```

After each call, log `err` value, and log a custom message if any error is returned:

```go
	err := A()
	fmt.Printf("a value is '%v'\n", err)
	if err == nil {
		fmt.Println("a is nil")
	} else {
		fmt.Println("a is not nil")
	}

	err = B()
	fmt.Printf("b value is '%v'\n", err)
	if err == nil {
		fmt.Println("b is nil")
	} else {
		fmt.Println("b is not nil")
	}
```

### What did you expect to see?

Both function return `nil`, so we should have the following:

```bash
a value is '<nil>'
a is nil
b value is '<nil>'
b is nil
```

### What did you see instead?

```bash
a value is '<nil>'
a is nil
b value is '<nil>'
b is not nil
```

It says `b value is '<nil>'`, but the condition `if err == nil` is still evaluated to `true`.

Whole code to reproduce the issue is available below and in [this Go playground example](https://go.dev/play/p/1ZrXHPZ1IL5) too:

```go
package main

import "fmt"

type CustomError struct {
	error
	errcode string
}

func A() error {
	return nil
}
func B() *CustomError {
	return nil
}

func main() {
	err := A()
	fmt.Printf("a value is '%v'\n", err)
	if err == nil {
		fmt.Println("a is nil")
	} else {
		fmt.Println("a is not nil")
	}

	err = B()
	fmt.Printf("b value is '%v'\n", err)
	if err == nil {
		fmt.Println("b is nil")
	} else {
		fmt.Println("b is not nil")
	}
}
```

----

One interesting thing is when I change A function to return `*CustomError` too, instead of builtin `error`:

```diff
-func A() error {
+func A() *CustomError {
        return nil
 }
```

In this case, I get the expected behavior (everything is nil):

```bash
a value is '<nil>'
a is nil
b value is '<nil>'
b is nil
```

Here is the updated code for this working case, as long with [the new Go Playground example](https://go.dev/play/p/dQex9SuT-if):

```go
package main

import "fmt"

type CustomError struct {
	error
	errcode string
}

func A() *CustomError {
	return nil
}
func B() *CustomError {
	return nil
}

func main() {
	err := A()
	fmt.Printf("a value is '%v'\n", err)
	if err == nil {
		fmt.Println("a is nil")
	} else {
		fmt.Println("a is not nil")
	}

	err = B()
	fmt.Printf("b value is '%v'\n", err)
	if err == nil {
		fmt.Println("b is nil")
	} else {
		fmt.Println("b is not nil")
	}
}
```

**Comment by seankhliao** [comment]
See https://go.dev/doc/faq#nil_error

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by pomeh** [comment]
Thanks for your quick and detailed answer.

I considered this a bug from an user/developer point of view, as this is an unexpected behavior, that's why I did not ask a question on other tools. I search on Github issue list but did not find anything either.

With your explanations, I now understand what's going on under the hood.
