### ISSUE TITLE
internal compiler error: assertion failed

### ISSUE THREAD

**Issue by RSRGEN** [golang/go#54228]
### What version of Go are you using (`go version`)?

go version go1.18.4 linux/amd64

<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?

yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

bash-4.4$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/users/xxx/.cache/go-build"
GOENV="/users/xxx/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/ws/xxx-bgl/go_118/go_path/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/ws/xxx-bgl/go_118/go_path/"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/ws/xxx-bgl/go_118/go_root/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/ws/xxx-bgl/go_118/go_root/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/nobackup/xxx/opensource/consul/consul/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1472410546=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
Build consul open source.

1. git clone https://github.com/hashicorp/consul.git
2. make bootstrap
3. make

bash-4.4$ make
mkdir -p bin
CGO_ENABLED=0 go install -ldflags "-X github.com/hashicorp/consul/version.GitCommit=58eed6b04 -X github.com/hashicorp/consul/version.BuildDate=2022-08-02T21:58:41Z " -tags ""
# github.com/hashicorp/consul/agent/consul/state
agent/consul/state/catalog_schema.go:271:28: internal compiler error: assertion failed

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new
make: *** [GNUmakefile:147: dev-build] Error 2
bash-4.4$

**Comment by seankhliao** [comment]
fixed in 1.18.5+
