### ISSUE TITLE
cmd/compile: internal compiler error of atomic type and offsetof

### ISSUE THREAD

**Issue by shawndx** [golang/go#54220]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOOS="linux"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3916657495=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
Try to cross-build a simple case having atomic type and unsafe.Offsetof.

https://go.dev/play/p/BwewXT6hUo9

GOARCH=386 go build <simple.go>

### What did you expect to see?
no error.

### What did you see instead?

# command-line-arguments
./simple.go:17:44: internal compiler error: got 4 from types2, but want 8

**Comment by cuonglm** [comment]
Seems we need to backport this to go1.19, since when there's no workaround.

cc @randall77 @mdempsky

**Comment by randall77** [comment]
@gopherbot please open a backport to 1.19.
