### ISSUE TITLE
x/build/cmd/relui: workflow parameters of slice types aren't visibly shown

### ISSUE THREAD

**Issue by dmitshur** [golang/go#54240]
relui currently renders a recent "announce-and-tweet-minor" workflow from the Go 1.18.5 and 1.17.13 minor release:

![image](https://user-images.githubusercontent.com/1924134/182671788-9886ab98-dd4b-4585-ae1e-d3d40ca34295.png)

The values for the string parameters "Version", "Security Summary", etc., are displayed, but not for the "Release Coordinator Names" and "Security Fixes" parameters, likely because their type is []string.

(The parameter values are there in the database and were correctly used by the tasks; this is only a presentation issue.)

CC @golang/release, @cherrymui.

**Comment by dmitshur** [comment]
Looked at this briefly. As expected, it was only a problem for non-string parameters, and it's because the current parameter display code assumes all parameters are strings, which isn't always the case as of #51191.

Long term, we could extend the nice type-specific presentation that @toothrot did for results and outputs in #53382 to parameters too, but for now I'll mail a small CL that shows their JSON encoding, which is much better than invisible.

**Comment by toothrot** [comment]
This change breaks the layout a bit for some workflows. I am happy to fix it, though, and give it a little nicer visual treatment.

https://build.golang.org/releases/workflows/14dad363-ab84-41b7-af65-1928299f3390

![9tAbAsV6PWWGQdD](https://user-images.githubusercontent.com/9885/184006298-7baefbef-8790-47fb-a945-a0580c44d834.png)

**Comment by dmitshur** [comment]
Sure, thanks for helping!

**Comment by toothrot** [comment]
![image](https://user-images.githubusercontent.com/9885/184034607-386c8348-6a62-45f0-a45d-404010d2205e.png)

I'll send a CL that implements this screenshot. It's not perfect, but it's closer to something nice.
