### ISSUE TITLE
x/build: update Go bootstrap on Corellium builders

### ISSUE THREAD

**Issue by rsc** [golang/go#54246]
We are going to require Go 1.17 for building Go 1.20 (see #44505).
On most builders we will have the buildlet download the right toolchain automatically.
The Corellium builders do not seem to be able to download from storage.googleapis.com: I get 403 Forbidden.

The ios builder has a toolchain at d6c4583ad4, between Go 1.17 and Go 1.18, which is fine.
The android builder has Go 1.15.3 and will stop building soon.
Can you please update the android builder to Go 1.17 or later?
If you update it to Go 1.19 it might be a good idea to update the ios builder to match
and to get it onto a tagged release, even though it doesn't strictly need an update.

/cc @steeve and @changkun who are listed as the owners of these builders in x/build/dashboard/builders.go.

**Comment by dmitshur** [comment]
CC @golang/release.

**Comment by thanm** [comment]
Friendly ping  @steeve and @changkun , it would be nice to get these builders back on line (they have been red for a week or so).

**Comment by changkun** [comment]
I am investigating this.

**Comment by dmitshur** [comment]
It looks like these builders are now using a Go 1.18.3 bootstrap (up from Go 1.15.3), and passing:

- [android-arm-corellium at 2f6783c098696790223eae6986700868e9da0472](https://build.golang.org/log/96da138610e90ba12c8f676e9f01dd7408b754d4)
- [android-arm64-corellium at 2f6783c098696790223eae6986700868e9da0472](https://build.golang.org/log/7587f464b6e797e3bb85a01c0d68c423c97c2d6d)

Thanks very much for resolving this.

**Comment by changkun** [comment]
The Android builder is now using Go 1.18.3, as @dmitshur noted above. I reconfigured one iOS builder to use Go 1.19 because this builder was removed by Corellium due to their VM reallocation.

Let me know if it is necessary to have all Android and iOS builders use the same 1.19 version as bootstrap.

**Comment by dmitshur** [comment]
> Let me know if it is necessary to have all Android and iOS builders use the same 1.19 version as bootstrap.

I think it's fine for the Android and iOS builders to use slightly different bootstrap versions, given they're all meeting the hard requirement of being at minimum 1.17+. I wouldn't worry about redoing them to be exactly the same versions. In the future after #54265, it's also fine to stay closer to version specified in the [`dashboard.GoBootstrap`](https://pkg.go.dev/golang.org/x/build/dashboard#GoBootstrap) constant.
