### ISSUE TITLE
math/bits: different results when using a pure Go copy of Add64

### ISSUE THREAD

**Issue by mertcandav** [golang/go#54255]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/mertcandav/.cache/go-build"
GOENV="/home/mertcandav/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/mertcandav/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/mertcandav/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.18"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.18/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="/usr/bin/gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/mertcandav/Desktop/xxc/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4177709774=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

The result of the `Add64` function in the `math.bits` package is not the same as the result of the copy of the function.
https://go.dev/play/p/K16VoyuwfvK

### What did you expect to see?
Terminal output:
```
313 0
````

### What did you see instead?
Terminal output:
```
304 0
````

**Comment by mvdan** [comment]
I think your program runs into documented undefined behavior:

> Add64 returns the sum with carry of x, y and carry: sum = x + y + carry. The carry input must be 0 or 1; otherwise the behavior is undefined. The carryOut output is guaranteed to be 0 or 1. 

As to _why_ your results are different, note that Add64 is an intrinsic on amd64, meaning that it compiles down to efficient code: https://cs.opensource.google/go/go/+/refs/tags/go1.19:src/cmd/compile/internal/ssagen/ssa.go;l=4685

I would guess that the efficient intrinsic takes advantage of the undefined inputs to be faster.

**Comment by mvdan** [comment]
cc @randall77 in case I got the above wrong.

**Comment by mertcandav** [comment]
> I think your program runs into documented undefined behavior:
> 
> > Add64 returns the sum with carry of x, y and carry: sum = x + y + carry. The carry input must be 0 or 1; otherwise the behavior is undefined. The carryOut output is guaranteed to be 0 or 1.
> 
> As to _why_ your results are different, note that Add64 is an intrinsic on amd64, meaning that it compiles down to efficient code: https://cs.opensource.google/go/go/+/refs/tags/go1.19:src/cmd/compile/internal/ssagen/ssa.go;l=4685
> 
> I would guess that the efficient intrinsic takes advantage of the undefined inputs to be faster.

If ``Add64`` has a different assembly output, I think that's the likely reason why the results are different.

**Comment by rsc** [comment]
@mvdan's explanation is correct. Carry is a single bit. Calling Add with carry>1 is not defined and will not give consistent results.
