### ISSUE TITLE
x/build/env/linux-ppc64le/osuosl: update builder to a newer Linux distribution

### ISSUE THREAD

**Issue by cagedmantis** [golang/go#54257]
This builder should be running on the latest version of Debian. #52091 #54070

@golang/release

**Comment by pmur** [comment]
These are running Ubuntu 18.04.6 today. I'll ping OSU to investigate moving these to a newer LTS.

Would it be ok to move to the latest LTS? That seems to be 22.04. I think Bullseye corresponds to the 20.04 LTS.

**Comment by ramereth** [comment]
FYI, I subscribed to this issue if you want to discuss this directly with me. I'm here representing OSU.

**Comment by pmur** [comment]
Hi @ramereth, let's try to update these to Ubuntu 20.04. Looking at the linked issues, it seems like the preferred solution. Could you start the initial update? If so, I think you can reboot/update whenever works best for you. I can help once ssh access is restored. Thanks!

**Comment by dmitshur** [comment]
> Would it be ok to move to the latest LTS?

I think that should be okay.

**Comment by pmur** [comment]
I am going to update the P9 builder now to 20.04 now. Once it is back online, I'll update the P8 builder.

**Comment by pmur** [comment]
I am updating the P8 builder now since the upgrade on P9 VM has gone well.

**Comment by pmur** [comment]
And the P8 builder is updated. This task is complete.
