### ISSUE TITLE
affected/package: method:growsSlice  from runtime/slice.go  

### ISSUE THREAD

**Issue by JBossBC** [golang/go#54252]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.17.6
</pre>

### Does this issue reproduce with the latest release?

when i use the keyword of append,according to the slice capacity expansion policy,i choose a slice with the capacity and length of 2 and use the append method to expanse its data capacity,but the result dont match with theory.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
the programming code
![图片](https://user-images.githubusercontent.com/90125263/182818051-9af618f3-a25f-4293-abe0-c352c243fae7.png)

### What did you expect to see?

the theory result

the 3 line data should be "arr1: 9" but the running result is "arr1:10"

### What did you see instead?

the running result
![图片](https://user-images.githubusercontent.com/90125263/182818293-f23ed50f-7d2d-4919-af2b-5a264e4d5279.png)

**Comment by perbu** [comment]
This is expected behavior. The capacity of the array doesn't always match the length of the slice. Since expanding an array (allocate + copy the content) is expensive the array will be somewhat bigger than the slice.

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.
