### ISSUE TITLE
x/build/env/linux-ppc64le/osuosl: OOM running api test during all.bash

### ISSUE THREAD

**Issue by pmur** [golang/go#54267]
This seems to have started after 76065a2ab1b195a790c803d11e713491cfcb3ba5.

Is the new bootstrap toolchain download counting against the memory limits of the container? If so, should we increase memory accordingly? Should the limit be removed?

**Comment by laboger** [comment]
It should be noted that we have been trying to reproduce this error on other systems and have not been able to. It only seems to happen when running in one of the buildlets.

**Comment by laboger** [comment]
This is a problem with this line in x/build/env/linux-ppc64le/osusl/rundockerbuildlet.service

ExecStart=/usr/local/bin/rundockerbuildlet -basename=power_ -image=golang/builder -n=5 -cpu=2 -memory=4.9g --env=XXX

Note that the corresponding file for linux-ppc64 does not have a memory limit and does not fail in this way. Also as I mention above it does not fail on other ppc64le systems, so is totally related to running in these containers. Actually if I look at all other rundockerbuildlet.service files, only the linux-ppc64le file has a limit. I don't know why it was set up this way.
