### ISSUE TITLE
go 1.18: access to exported fields of unexported types from other packages

### ISSUE THREAD

**Issue by dzqv** [golang/go#54266]
### What version of Go are you using (`go version`)?

go 1.18.3

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

darwin, macos

### What did you do?

`foo.go`
```
package foo

// struct s is unexported
type s struct {
    U int
}

// func F returns a pointer to an unexported type
func F() *s {
  return &s{1}  
}
```

`foo_test.go`
```
package foo_test

import (
   "testing"
   "foo"
)

func TestF(t *testing.T) {
    // this test is able to access field `U` of unexported struct `s`
    if u := foo.F().U; u != 1 {
       t.Fail()
    }
}
```

### What did you expect to see?

I expected the code to fail to compile because the test is referencing a named field from an unexported type.

### What did you see instead?

The test passes. Is this documented behavior or something new?

**Comment by ianlancetaylor** [comment]
That is how the language works.  `U` is an exported identifier.  There is no special rule saying "exported fields of unexported types are not really exported after all."

**Comment by dzqv** [comment]
Thanks Ian!
