### ISSUE TITLE
cmd/api: API check failing with "go tool api: signal: killed", "exit status 1" on linux-ppc64le-buildlet, linux-ppc64le-power9osu

### ISSUE THREAD

**Issue by dmitshur** [golang/go#54269]
As of [CL 420902](https://go.dev/cl/420902) ("cmd/dist: require Go 1.17 for building Go" for #44505), API check fails on these two builders with:

```
##### API check
Error running API checker: exit status 1
go tool api: signal: killed
exit status 1
2022/08/04 21:17:55 Failed: exit status 1
go tool dist: FAILED
```

CC @rsc, @golang/ppc64.

**Comment by pmur** [comment]
I suspect this is related to the change to download the bootstrap compiler inside the container. I also opened #54267.

If so, the containers likely need the memory limit bumped to compensate, or maybe the limit can be removed?
