### ISSUE TITLE
cmd/compile: internal compiler error: panic: runtime error: slice bounds out of range [712097:26324]

### ISSUE THREAD

**Issue by Pxingtian** [golang/go#54282]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.1 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre>set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\LENOVO‘\AppData\Local\go-build
set GOENV=C:\Users\LENOVO‘\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=E:\lenovo\Desktop\SupervisorySystem\supermet\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=E:\lenovo\Desktop\SupervisorySystem\supermet
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=F:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=F:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.18.1
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=E:\lenovo\Desktop\SupervisorySystem\supermet\src\supermet\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\LENOVO‘\AppData\Local\Temp\go-build3606341032=/tmp/go-build -gno-record-gcc-switches</details>

### What did you do?
Vscode restart

### What did you expect to see?

I expect vscode golang debug to work properly

### What did you see instead?
<pre>
Starting: E:\lenovo\Desktop\SupervisorySystem\supermet\bin\dlv.exe dap --check-go-version=false --log=true --log-output=debugger --listen=127.0.0.1:56773 from e:\lenovo\Desktop\SupervisorySystem\supermet\src\supermet
DAP server listening at: 127.0.0.1:56773
Build Error: go build -o e:\lenovo\Desktop\SupervisorySystem\supermet\src\supermet\__debug_bin.exe -gcflags all=-N -l .
# supermet/models/vehicles
<unknown line number>: internal compiler error: panic: runtime error: slice bounds out of range [712097:26324]

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new (exit status 2)
</pre>

**Comment by mvdan** [comment]
Please see if the problem reproduces with the latest stable version of Go: either 1.18.5 or 1.19.

**Comment by mdempsky** [comment]
We'll need the relevant source files to reproduce the issue.

**Comment by Pxingtian** [comment]
There is no source file. This debug tool is installed from vscode。

**Comment by Pxingtian** [comment]
There is no source file. This debug tool is installed from vscode




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "golang/go"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月11日(星期四) 凌晨4:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [golang/go] cmd/compile: internal compiler error: panic: runtime error: slice bounds out of range [712097:26324] (Issue #54282)





 
We'll need the relevant source files to reproduce the issue.

**Comment by mdempsky** [comment]
The error you posted is from the Go compiler trying to compile the package "supermet/models/vehicles":

```
Build Error: go build -o e:\lenovo\Desktop\SupervisorySystem\supermet\src\supermet\__debug_bin.exe -gcflags all=-N -l .
# supermet/models/vehicles
: internal compiler error: panic: runtime error: slice bounds out of range [712097:26324]
```

That's your source package, right?
