### ISSUE TITLE
cmd/trace: goroutine analysis grouped by PC and reported `N=?`, but PC is zero and Name is empty

### ISSUE THREAD

**Issue by hitzhangjie** [golang/go#54284]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.18.3
</pre>

### Does this issue reproduce with the latest release?
I only tried go1.18.3

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="arm64"
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOOS="darwin"
GOVERSION="go1.18.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
...
</pre></details>

### What did you do?

go tool trace trace.out, then view the `goroutine analysis`, at last there's a N=4, what does it mean?

![image](https://user-images.githubusercontent.com/3725760/183026137-4e1b25e4-1fea-4374-abfe-bad4d5d79141.png)

I check the code src/cmd/trace, it is caused by the GDesc.PC / GDesc.Name is zero value. 
When does this occasion happend?

### What did you expect to see?
I want to know what does it mean, if detailed description is shown, it may be better understood.

### What did you see instead?

I see `N=4` at last, it is not clear.

**Comment by hitzhangjie** [comment]
And, the template cannot render the goroutine func entry (name is empty).

Then, we cannot query by `/goroutine?id=0` by click the hyperlink.

**Comment by hitzhangjie** [comment]
Is it caused by goroutine func() and inline?

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by hitzhangjie** [comment]
@seankhliao Yes, I think `go tool trace` should give a clearer description about which goroutines `N=4` is associated.

**Comment by hitzhangjie** [comment]
This is a bug, why just closed it? The final N=4 isn't associated with any goroutine information.
