### ISSUE TITLE
cmd/compile: internal compiler error: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jmacd** [golang/go#54302]
### What version of Go are you using (`go version`)?
Installed the binary from https://go.dev/doc/install today:
<pre>
$ go version
go version go1.19 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes. Here is a play link:
https://go.dev/play/p/R_wq9G9RIFV
That pulls in https://github.com/lightstep/otel-launcher-go/tree/main/lightstep/sdk/metric/aggregator/minmaxsumcount, which compiles in 1.18 but not in 1.19

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/josh.macdonald/Library/Caches/go-build"
GOENV="/Users/josh.macdonald/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/josh.macdonald/src/lightstep/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/josh.macdonald/src/lightstep/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/josh.macdonald/src/opentelemetry/otel-launcher-go/lightstep/sdk/metric/go.mod"
GOWORK="/Users/josh.macdonald/src/opentelemetry/otel-launcher-go/go.work"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hp/8_6w4qns7g79tww_56kst5nh0000gp/T/go-build4007331615=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

This may be a duplicate of #54243

### What did you expect to see?

In 1.18 [this package](https://github.com/lightstep/otel-launcher-go/tree/main/lightstep/sdk/metric/aggregator/minmaxsumcount) compiles.

### What did you see instead?

In 1.19, the error message:
```
# github.com/lightstep/otel-launcher-go/lightstep/sdk/metric/aggregator/minmaxsumcount
<autogenerated>:1: internal compiler error: panic: runtime error: invalid memory address or nil pointer dereference

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new
```

**Comment by seankhliao** [comment]
cc @golang/compiler

**Comment by mdempsky** [comment]
Minimized repro:

```
package p

func A() {
	B[int](nil)
}

func B[T any](iface interface{ M() }) {
	_ = iface.(*G[T])
}

type G[_ any] struct{}

func (*G[_]) M() {}
```

**Comment by mdempsky** [comment]
@gopherbot Please backport to Go 1.19. This is a regression from Go 1.18.
