### ISSUE TITLE
affected/package: Go1.19 `go fmt` breaks package's code generation

### ISSUE THREAD

**Issue by zzjin** [golang/go#54349]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.19 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Upgrade to go 1.19 causes this issue.

### What operating system and processor architecture are you using (`go env`)?

I think this affect all support plaforms.

### What did you do?

I have one repo inited by `kubebuilder`, witch is using `code generation`, all works fine, but upgrade to go1.19 the `//+` will be formatted to `// +` then code generation breaks. 

### What did you expect to see?

Nothing to change as code file already `go fmt`ed.

### What did you see instead?

```diff
@@ -15,8 +15,8 @@ limitations under the License.
 */
 
 // Package v1 contains API Schema definitions for the app v1 API group
-//+kubebuilder:object:generate=true
-//+groupName=test.com
+// +kubebuilder:object:generate=true
+// +groupName=test.com
-//nolint
+// nolint
 package v1
 
 import (
```

**Comment by seankhliao** [comment]
This is working as intended, see https://github.com/golang/go/issues/37974#issuecomment-611088006 for relevant discussions.

kubebuilder should use the more standard format for its directives.
