### ISSUE TITLE
cmd/compile: ICE when a promoted method on an instantiated type implements a type parameter constraint

### ISSUE THREAD

**Issue by mdempsky** [golang/go#54348]
This program should run successfully: https://go.dev/play/p/bqSPtEGm82w?v=gotip

It worked with Go 1.18 through Go 1.18.3. In Go 1.18.4, it started ICE'ing due to nil pointer dereference in getDictionarySym. It still ICEs in Go 1.18.5 and Go 1.19.

Bisect identifies 93aab1813930fd3e936d13cb2d0729a8b60aa541.

Minimized from test case reported by @borzovplus on #54308.

/cc @golang/compiler @cuonglm

**Comment by cuonglm** [comment]
@mdempsky @randall77 Though we agree that there's no backport for generic to go1.18, I think this can be an exception?

At least, I think it's ok to backport this to 1.19, for 1.18, we can revert 93aab1813930fd3e936d13cb2d0729a8b60aa541 instead.
