### ISSUE TITLE
affected/package: 

### ISSUE THREAD

**Issue by mneverov** [golang/go#54340]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19 linux/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/mneverov/.cache/go-build"
GOENV="/home/mneverov/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/mneverov/go/pkg/mod"
GOOS="linux"
GOPATH="/home/mneverov/go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1219124964=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

https://go.dev/play/p/vsNE85PCqsQ

```go
package main

import (
	"fmt"
	"time"
)

func main() {
	i := 1
	t := time.NewTicker(100 * time.Millisecond)
	for {
		select {
		case <-time.After(1 * time.Second):
			fmt.Println("done")
			return
		case <-t.C:
			fmt.Println(i)
			i++
		}
	}
}

```

### What did you expect to see?
After one second (+ some time to pick the first case) the program terminates.

### What did you see instead?
The program continues to run.

As per [spec](https://go.dev/ref/spec#Select_statements): `If one or more of the communications can proceed, a single one that can proceed is chosen via a uniform pseudo-random selection.` 

I also added a couple of more cases with `time.After` and the ticker case is picked up almost always.

**Comment by ianlancetaylor** [comment]
This is working as expected.  Every time you enter the `select` statement, it runs `time.After(1 * time.Second)` to get a new channel that will receive a value after 1 second.  Then it waits for a channel to be ready.  The ticker will always be ready in less than 1 second, and that is what you see.

You may have meant to write this program:

```Go
package main

import (
	"fmt"
	"time"
)

func main() {
	i := 1
	t := time.NewTicker(100 * time.Millisecond)
	c := time.After(1 * time.Second)
	for {
		select {
		case <-c:
			fmt.Println("done")
			return
		case <-t.C:
			fmt.Println(i)
			i++
		}
	}
}
```

**Comment by mneverov** [comment]
maybe worth updating the [example](https://pkg.go.dev/time#After)?

**Comment by seankhliao** [comment]
The example represents a different use case that is different from yours (not in a loop)
