### ISSUE TITLE
x/tools/gopls: TryBot flake in TestDeleteFiles/delete_then_close/default

### ISSUE THREAD

**Issue by findleyr** [golang/go#54342]
```
#!watchflakes
post <- pkg == "golang.org/x/tools/gopls/internal/regtest/watch" && test == "TestDeleteFiles"
```

The following flake occured on https://go.dev/cl/422135:

https://storage.googleapis.com/go-build-log/a34a97d8/freebsd-amd64-12_3_7f502470.log

`greplogs` does not turn up any recent flakes on the builders, but this one flake suggests that there may be a race to logging (which makes sense, as logs might be asynchronous).

**Comment by findleyr** [comment]
Without a reoccurrence, this is unlikely to get prioritized. Closing for now as unreproducible.

**Comment by adonovan** [comment]
More go command stuckness.
