### ISSUE TITLE
x/pkgsite: "Report a Vulnerability" link sends a confusing message

### ISSUE THREAD

**Issue by AlekSi** [golang/go#54358]
### What is the URL of the page with the issue?

Any third-party package documentation page; for example, https://pkg.go.dev/github.com/pkg/errors.

### Screenshots

---

![image](https://user-images.githubusercontent.com/11512/183704275-538a9a01-980e-4cb9-b963-e40e3e781738.png)

---

![image](https://user-images.githubusercontent.com/11512/183704030-8db621c9-6b6c-4860-b269-f45eda9309ba.png)

---

### What did you do?

1. Clicked "[Report a Vulnerability](https://github.com/golang/vulndb/issues/new?assignees=&labels=Needs+Triage%2CDirect+External+Report&template=new_third_party_vuln.yml&title=x%2Fvulndb%3A+potential+Go+vuln+in+github.com%2fpkg%2ferrors)" link.
2. Clicked "[golang/vulndb](https://github.com/golang/vulndb)" link on top to learn more about vulndb.
3. Got confused about [that part of the README](https://github.com/golang/vulndb#reporting-a-vulnerability).

### What did you expect to see?

Non-contradictory statements.

### What did you see instead?

Contradictory statements: pkg.go.dev prompts me to report security vulnerabilities in a repository that (according to README) does not accept them.

**Comment by findleyr** [comment]
CC @jamalc as well.

**Comment by jamalc** [comment]
The README is out of date. The Report Vulnerability template is live in the golang/vulndb issue tracker. @julieqiu, do you have plans to update it already?

**Comment by julieqiu** [comment]
This has been updated. Please contribute away! :)
