### ISSUE TITLE
x/image: bmp decode of attached image will result in all alpha values to be 0

### ISSUE THREAD

**Issue by maaft** [golang/go#54368]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.19 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home//.cache/go-build"
GOENV="/home//.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home//go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home//go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build115352423=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

download this BMP [image](https://github.com/golang/go/files/9377474/30Sep23-84.BMP.zip)

execute this bmp-to-png conversion "script":
```golang
package main

import (
	"bytes"
	"image/png"
	"os"

	"golang.org/x/image/bmp"
)

func must(err error) {
	if err != nil {
		panic(err)
	}
}

func main() {

	f, err := os.Open("<path to bmp file>")

	must(err)

	bmp_decode, err := bmp.Decode(f)

	must(err)

	buffer := &bytes.Buffer{}
	err = png.Encode(buffer, bmp_decode)

	must(err)

	err = os.WriteFile("test.png", buffer.Bytes(), 0644)

	must(err)

}

```

### What did you expect to see?

I expect to see the original image in png format or an error while opening the bmp file if its corrupt.

### What did you see instead?

I saw no errors and the resulting png image is completely transparent. All alpha values of `bmp_decode` are 0.

**Comment by thanm** [comment]
I am getting a 404 on the link cited (https://file.io/3QG9p08hAz71)

**Comment by maaft** [comment]
@thanm  Oh, sorry about that. That provider seems to delete the file after first download. Since I can't upload BMP files here directly, any idea what to use for a hosting service?

**Comment by seankhliao** [comment]
zip the file and upload here

**Comment by maaft** [comment]
lol, yes. how could I not think about zipping it -.- thanks
[30Sep23-84.BMP.zip](https://github.com/golang/go/files/9377474/30Sep23-84.BMP.zip)

**Comment by ZekeLu** [comment]
Here is the information of the image:

<table>
  <tbody>
    <tr>
      <th>Offset</th>
      <th>Size</th>
      <th>Hex value</th>
      <th>Value</th>
      <th>Description</th>
    </tr>
    <tr>
      <th colspan="5">BMP Header</th>
    </tr>
    <tr>
      <td>00</td>
      <td>2</td>
      <td>42 4D</td>
      <td>"BM"</td>
      <td>ID field</td>
    </tr>
    <tr>
      <td>02</td>
      <td>4</td>
      <td>96 38 01 00</td>
      <td>80022 bytes (0x013896)</td>
      <td>Size of the BMP file (54 bytes header + 79968 bytes data)</td>
    </tr>
    <tr>
      <td>06</td>
      <td>2</td>
      <td>00 00</td>
      <td>Unused</td>
      <td>Application specific</td>
    </tr>
    <tr>
      <td>08</td>
      <td>2</td>
      <td>00 00</td>
      <td>Unused</td>
      <td>Application specific</td>
    </tr>
    <tr>
      <td>0A</td>
      <td>4</td>
      <td>36 00 00 00</td>
      <td>54 bytes (14+40)</td>
      <td>Offset where the pixel array (bitmap data) can be found</td>
    </tr>
    <tr>
      <th colspan="5">DIB Header (BITMAPINFOHEADER)</th>
    </tr>
    <tr>
      <td>0E</td>
      <td>4</td>
      <td>28 00 00 00</td>
      <td>🔴 40 bytes</td>
      <td>Number of bytes in the DIB header (from this point)</td>
    </tr>
    <tr>
      <td>12</td>
      <td>4</td>
      <td>88 00 00 00</td>
      <td>136 pixels</td>
      <td>Width of the bitmap in pixels</td>
    </tr>
    <tr>
      <td>16</td>
      <td>4</td>
      <td>93 00 00 00</td>
      <td>147 pixels</td>
      <td>Height of the bitmap in pixels</td>
    </tr>
    <tr>
      <td>1A</td>
      <td>2</td>
      <td>01 00</td>
      <td>🔴 1 plane</td>
      <td>Number of color planes being used</td>
    </tr>
    <tr>
      <td>1C</td>
      <td>2</td>
      <td>20 00</td>
      <td>🔴 32 bits</td>
      <td>Number of bits per pixel</td>
    </tr>
    <tr>
      <td>1E</td>
      <td>4</td>
      <td>00 00 00 00</td>
      <td>🔴 0</td>
      <td>BI_RGB, no pixel array compression used</td>
    </tr>
    <tr>
      <td>22</td>
      <td>4</td>
      <td>60 38 01 00</td>
      <td>79968 bytes (0x013860)</td>
      <td>Size of the raw bitmap data</td>
    </tr>
    <tr>
      <td>26</td>
      <td>4</td>
      <td>00 00 00 00</td>
      <td>horizontal resolution</td>
      <td rowspan="2">Not provided</td>
    </tr>
    <tr>
      <td>2A</td>
      <td>4</td>
      <td>00 00 00 00</td>
      <td>vertical resolution</td>
    </tr>
    <tr>
      <td>2E</td>
      <td>4</td>
      <td>00 00 00 00</td>
      <td>0 colors</td>
      <td>Number of colors in the palette</td>
    </tr>
    <tr>
      <td>32</td>
      <td>4</td>
      <td>00 00 00 00</td>
      <td>0 important colors</td>
      <td>0 means all colors are important</td>
    </tr>
    <tr>
      <th colspan="5">Start of pixel array (bitmap data)</th>
    </tr>
    <tr>
      <td>36</td>
      <td>4</td>
      <td>7A 7A 7A 00</td>
      <td></td>
      <td rowspan="3">
        🔴 The last byte (00) in the pixel<br />
        is incorrectly treated as the alpha value
      </td>
    </tr>
    <tr>
      <td>3A</td>
      <td>4</td>
      <td>7A 7A 7A 00</td>
      <td></td>
    </tr>
    <tr>
      <td>3E</td>
      <td>4</td>
      <td>78 78 78 00</td>
      <td></td>
    </tr>
    <tr>
      <th colspan="5">pixel array truncated...</th>
    </tr>
  </tbody>
</table>

We are interested in these attributes:

- The size of the DIB header is 40, which means it's a `BITMAPINFOHEADER`
- The bits per pixel (bpp) is 32
- The type of compression is `BI_RGB` (no pixel array compression used)

For `BITMAPINFOHEADER` with compression set to `BI_RGB`, the alpha channel is not supported (see the references in the end of this comment). So the alpha component in the decoded image data should be `0xFF`.

I think this is a bug in the `x/image/bmp` package. I will send a CL to fix it.

It's interesting that the `x/image` repository already contains two test images which looks different but decoded to the same image data (covered by a test):

- `testdata/yellow_rose-small.bmp`:
    <img width="100px" src="https://raw.githubusercontent.com/golang/image/7e034cad644213bc79b336b52fce73624259aeca/testdata/yellow_rose-small.bmp" />

- `testdata/yellow_rose-small.png`:
    <img width="100px" src="https://raw.githubusercontent.com/golang/image/7e034cad644213bc79b336b52fce73624259aeca/testdata/yellow_rose-small.png" />

My fix will make this test fail. Obviously, the two images look different and in my opinion, the failure is expected. I will modify `testdata/yellow_rose-small.png` to make it pass again.

BTW, [GraphicsMagick 1.3.38](http://www.graphicsmagick.org/) has the same issue. Running the following command will generate a transparent image:

```
gm convert 30Sep23-84.BMP 30Sep23-84.png
```

References:

- https://docs.microsoft.com/previous-versions/dd183376(v=vs.85)
- https://en.wikipedia.org/wiki/BMP_file_format#Pixel_format

**Comment by thanm** [comment]
@ZekeLu thanks for sending that CL, looks good to me (although I have very little familiarity with image/bmp).
