### ISSUE TITLE
misc/cgo/testsanitizers: ASAN test skipped due to old compiler version even though gcc is quite recent 

### ISSUE THREAD

**Issue by archanaravindar** [golang/go#54370]
### What version of Go are you using (`go version`)?

<pre>
go version devel go1.20-5531838c04 Wed Aug 10 02:14:09 2022 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes 

### What operating system and processor architecture are you using (`go env`)?
<details><summary><code>go env</code> Output</summary><br><pre>

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/archana/.cache/go-build"
GOENV="/home/archana/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/archana/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/archana/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/archana/Go_master/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/archana/Go_master/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel go1.20-c81dfdd47a Wed Aug 10 08:57:33 2022 +0000"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3708586492=/tmp/go-build -gno-record-gcc-switches"
```
</pre></details>
### What did you do?

Build Go, 
misc/cgo/testsanitizers/> go test -c 
./testsanitizers.test -test.v 

### What did you expect to see?

--- PASS: TestASAN (1.22s)
    --- PASS: TestASAN/asan3_fail (1.75s)
    --- PASS: TestASAN/asan_useAfterReturn (2.15s)
    --- PASS: TestASAN/asan_global3_fail (2.16s)
    --- PASS: TestASAN/asan_global5 (2.18s)
    --- PASS: TestASAN/asan4_fail (2.25s)
    --- PASS: TestASAN/asan_global2_fail (2.33s)
    --- PASS: TestASAN/asan2_fail (2.34s)
    --- PASS: TestASAN/asan_unsafe_fail2 (2.35s)
    --- PASS: TestASAN/asan1_fail (2.40s)
    --- PASS: TestASAN/asan5_fail (2.41s)
    --- PASS: TestASAN/asan_global4_fail (2.42s)
    --- PASS: TestASAN/asan_unsafe_fail1 (2.44s)
    --- PASS: TestASAN/asan_unsafe_fail3 (2.50s)
    --- PASS: TestASAN/asan_global1_fail (2.52s)
--- PASS: TestTSAN (1.16s)
    --- PASS: TestTSAN/tsan8 (1.61s)
    --- PASS: TestTSAN/tsan (1.86s)
    --- PASS: TestTSAN/tsan6 (2.09s)
    --- PASS: TestTSAN/tsan4 (2.13s)
    --- PASS: TestTSAN/tsan3 (2.16s)
    --- PASS: TestTSAN/tsan2 (2.19s)
    --- PASS: TestTSAN/tsan10 (2.21s)
    --- PASS: TestTSAN/tsan11 (2.22s)
    --- PASS: TestTSAN/tsan12 (2.26s)
    --- PASS: TestTSAN/tsan5 (2.32s)
    --- PASS: TestTSAN/tsan7 (2.33s)
    --- PASS: TestTSAN/tsan9 (2.59s)
--- PASS: TestShared (0.00s)
    --- SKIP: TestShared/msan_shared (0.01s)
    --- PASS: TestShared/tsan_shared (4.99s)
PASS

### What did you see instead?

./testsanitizers.test -test.v 
=== RUN   TestASAN
    asan_test.go:31: skipping: too old version of compiler

even though the gcc version on the machine is 
gcc version 11.2.0 (Ubuntu 11.2.0-19ubuntu1)

**Comment by archanaravindar** [comment]
It appears that the file cc_test.go was originally having -dumpversion which was changed to -v
and gcc -v gives the output in stderr which seems to be causing this issue 
When I make the following changes to the code in cc_test.go it works 

Acc to documentation dumpversion prints the full version in older gcc and dumpfullversion prints the full version in newer gcc but dumpversion prints only the major version using both together could be an alternate solution  
diff cc_test.go ~/Go_master/go/misc/cgo//testsanitizers/
205c205
< 				cmd, err := cc("-dumpfullversion","-dumpversion")
---
> 				cmd, err := cc("-v")
209c209
< 				out, err := cmd.Output()
---
> 				out, err := cmd.CombinedOutput()
214c214
< 				gccRE := regexp.MustCompile(`(\d+)\.(\d+)`)
---
> 				gccRE := regexp.MustCompile(`gcc version (\d+)\.(\d+)`)

**Comment by thanm** [comment]
Thank you for reporting this problem.

Would you be interested in sending a patch with a fix?

**Comment by archanaravindar** [comment]
Yes I am interested

**Comment by archanaravindar** [comment]
Hi @bcmills Similar code exists in go/src/cmd/go/internal/work/init.go though it does not seem to create any issue like it does for ASAN tests being skipped. Should similar changes be made in here too?
