### ISSUE TITLE
x/vuln/vulncheck: TestCommand, TestBinary, TestExtractPackagesAndSymbols, TestLineFromAline failing after compiler generated symbol change

### ISSUE THREAD

**Issue by dmitshur** [golang/go#54381]
https://build.golang.org/?repo=golang.org%2fx%2fvuln shows test failures on Go tip as of [CL 317917](https://go.dev/cl/317917) ("all: use ":" for compiler generated symbols").

CC @golang/vulndb, @cuonglm.

**Comment by zpavlinovic** [comment]
@jba @julieqiu
