### ISSUE TITLE
cmd/compile: internal compiler error: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dmholtz** [golang/go#54399]
### Input

```go
package main

import "fmt"

type WeightType interface {
	float64 | int
}

type IEdge interface {
	To() int
}

type Edge struct {
	to int
}

func (e Edge) To() int {
	return e.to
}

type WeightedEdge[W WeightType] struct {
	Edge
	weight W
}

func (e WeightedEdge[W]) Weight() W {
	return e.weight
}

type Graph[N any, E IEdge] struct {
	nodes []N
	edges []E
}

func Accept[N any, E IEdge](gr Graph[N, E]) {
	for _, e := range gr.edges {
		to := e.To()
		fmt.Printf("To: %d\n", to)
	}
}

func main() {
	g := Graph[struct{}, WeightedEdge[int]]{}
	Accept(g)
}
```

### Output:

When attempting to build this program using go1.19 or go1.18.5, an internal compiler error is triggered:

```bash
david@w520:~/repos/gobug$ go build main.go
# command-line-arguments
./main.go:38:13: internal compiler error: panic: runtime error: invalid memory address or nil pointer dereference

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new
```

In a previous version of go, namely go.1.18.2, this error does NOT occur, i.e. there a no build errors.

```bash
david@MacBook golang-compiler-error % go build main.go
david@MacBook golang-compiler-error %
```

### Other Observations:

* The bug is triggered by a combination of
  * generics
  * nested structs
  * interfaces
* Exhaustive bug description and other observations in this [GitHub Repository](https://github.com/dmholtz/golang-compiler-error)

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What did you do?

After realizing that the template asks for a playground link, I c/p the code to playground: https://go.dev/play/p/toMBvIw6jmU

### Interesting short-term fix for others who observe this bug

* avoid generics
* avoid nested structs

Please refer to my [bug report repository](https://github.com/dmholtz/golang-compiler-error) for details.

**Comment by cuonglm** [comment]
Confirm that it's duplicated and fixed by CL https://go-review.googlesource.com/c/go/+/422274
