### ISSUE TITLE
x/sys/windows: `windows/svc/example` is detected as malware

### ISSUE THREAD

**Issue by t00ts** [golang/go#54394]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Akila\AppData\Local\go-build
set GOENV=C:\Users\Akila\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Akila\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Akila\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.19
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\Akila\Desktop\service tests\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\Akila\AppData\Local\Temp\go-build4169214643=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

1. Download the [example service](https://pkg.go.dev/golang.org/x/sys/windows/svc/example).
2. Build the example: `go build .`
3. Run the example: Install and start the service
```
> win_svc.exe install
> win_svc.exe start
```

### What did you expect to see?
The service running normally

### What did you see instead?
![Capture1](https://user-images.githubusercontent.com/2751266/184128217-de3f9fd6-0f93-46fd-9a5b-95c6663c8301.PNG)
![win_sec_detection](https://user-images.githubusercontent.com/2751266/184128224-a8955559-2ea8-421f-9e10-3d7fb153e6ca.png)
![Capture3](https://user-images.githubusercontent.com/2751266/184128223-2ff1a716-31c4-4c58-aec1-f0cbf2fbdfce.PNG)

Windows has stopped the service from running and uninstalled it from the registry. It cannot be run or re-installed:

```
> win_svc.exe start
failed to start myservice: could not access service: The specified service does not exist as an installed service.

> win_svc.exe install
failed to install myservice: SetupEventLogSource() failed: SYSTEM\CurrentControlSet\Services\EventLog\Application\myservice registry key already exists
```

**Comment by t00ts** [comment]
Hi @seankhliao, given you've closed the issue, I'd like to know what's the solution to build and ship software for Windows users using Go, if any. Thanks!

**Comment by seankhliao** [comment]
this is an issue for your antivirus vendor, not the go project

**Comment by t00ts** [comment]
Example provided is a clean Windows install, not any commercial anti-virus software

**Comment by seankhliao** [comment]
Microsoft / Windows is also an antivirus vendor.

**Comment by t00ts** [comment]
It's also (maybe unfortunately) the most widely used Desktop operating system, by far.

I'm surprised on how quickly this was disregarded as a non-issue when it's in fact quite a blocker in shipping a Go-based product to Windows users.

**Comment by alexbrainman** [comment]
> I'm surprised on how quickly this was disregarded as a non-issue when it's in fact quite a blocker in shipping a Go-based product to Windows users.

What do you suggest Go project should do instead of pointing affected users to the antivirus vendor?

Alex

**Comment by t00ts** [comment]
Hi Alex, I don't know what the Go project should do. I truly wish I did, but I don't.

All I know is there's no way of justifying further development efforts using Go if the moment our product reaches the (paying) customer's computer there's a high chance of it getting flagged as malware.

Customers are not engineers nor Go developers. You can't "point them" to their antivirus vendor (Microsoft).

Have you ever downloaded a desktop application and have the installer come up with a message like: _"Hey, please whitelist our software before Windows flags it as a virus"_?

I don't think so.

**Comment by alexbrainman** [comment]
> All I know is there's no way of justifying further development efforts using Go if the moment our product reaches the (paying) customer's computer there's a high chance of it getting flagged as malware.

I have never done this myself, but I suspect you can use some tools to sign your Go executable. This will make you executable not marked as malware. I just googled for it, and I can find

https://docs.microsoft.com/en-us/windows/win32/appxpkg/how-to-sign-a-package-using-signtool

https://stackoverflow.com/questions/252226/signing-a-windows-exe-file

Perhaps there are better solutions, if you are willing to look.

> Have you ever downloaded a desktop application and have the installer come up with a message like: _"Hey, please whitelist our software before Windows flags it as a virus"_?

I don't download random software from the Internet and run it on my computer.

@qmuntal is there a way for Microsoft antivirus team to include Go built executable in their testing when they develop their product? Sorry for pinging you here, if you are the wrong person to ask that question. Thank you.

Alex

**Comment by qmuntal** [comment]
> @qmuntal is there a way for Microsoft antivirus team to include Go built executable in their testing when they develop their product? Sorry for pinging you here, if you are the wrong person to ask that question. Thank you.

I can't reproduce this issue, but I like the idea. I'll try to move this forward.

**Comment by alexbrainman** [comment]
> I like the idea. I'll try to move this forward.

Thank you for doing that.

Alex
