### ISSUE TITLE
go mod download: failure inside docker only with "x509: certificate signed by unknown authority" error

### ISSUE THREAD

**Issue by smithbk** [golang/go#54400]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY="*.<My Corporate Domain>"
GONOSUMDB="*.<My Corporate Domain>"
GOOS="linux"
GOPATH="/go"
GOPRIVATE="*.<My Corporate Domain>"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/usr/src/app/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2433054485=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I am trying to build a docker image from inside a financial institution with strict security, including a corporate proxy.

Here is my Dockerfile:

```
FROM <My Corporate Artifactory Host>/golang:1.18

ARG UID
ARG PWD

ENV http_proxy=http://${UID}:${PWD}@<My Corporate Proxy Host>:8080
ENV https_proxy=http://${UID}:${PWD}@<My Corporate Proxy Host>:8080
ENV no_proxy="localhost,127.0.0.1,<My Corporate Domain>"

RUN apt-get update && apt-get install -y ca-certificates openssl
ARG certDir=/usr/local/share/ca-certificates
# Get certificate from "github.com"
RUN openssl s_client -showcerts -connect github.com:443 -proxy <My Corporate Proxy Host>:8080 </dev/null 2>/dev/null|openssl x509 -outform PEM > ${certDir}/github.crt
# Get certificate from "proxy.golang.org"
RUN openssl s_client -showcerts -connect proxy.golang.org:443 -proxy <My Corporate Proxy Host>:8080 </dev/null 2>/dev/null|openssl x509 -outform PEM > ${certDir}/proxy.golang.crt
# Update certificates
RUN update-ca-certificates

WORKDIR /usr/src/app

COPY . .

RUN go mod download
RUN go mod verify

RUN go build -v -o /usr/local/bin/app ./...

CMD ["app"]
```

My docker build fails as follows:

```
# docker build --build-arg UID=$(whoami) --build-arg PWD=<My Password> .
[+] Building 1.4s (12/14)                                                                                                                                               
 => [internal] load build definition from Dockerfile                                                                                                               0.0s
 => => transferring dockerfile: 1.07kB                                                                                                                             0.0s
 => [internal] load .dockerignore                                                                                                                                  0.0s
 => => transferring context: 2B                                                                                                                                    0.0s
 => [internal] load metadata for <My Corporate Artifactory>/golang:1.18                                                            0.0s
 => [ 1/10] FROM <My Corporate Artifactory>/golang:1.18                                                                            0.0s
 => [internal] load build context                                                                                                                                  0.0s
 => => transferring context: 12.09kB                                                                                                                               0.0s
 => CACHED [ 2/10] RUN apt-get update && apt-get install -y ca-certificates openssl                                                                                0.0s
 => CACHED [ 3/10] RUN openssl s_client -showcerts -connect github.com:443 -proxy <My Corporate Proxy Host>:8080 </dev/null 2>/dev/null|openssl x509 -outfo  0.0s
 => CACHED [ 4/10] RUN openssl s_client -showcerts -connect proxy.golang.org:443 -proxy<My Corporate Proxy Host>:8080 </dev/null 2>/dev/null|openssl x509   0.0s
 => CACHED [ 5/10] RUN update-ca-certificates                                                                                                                      0.0s
 => CACHED [ 6/10] WORKDIR /usr/src/app                                                                                                                            0.0s
 => [ 7/10] COPY . .                                                                                                                                               0.0s
 => ERROR [ 8/10] RUN go mod download                                                                                                                              1.3s
------
 > [ 8/10] RUN go mod download:
#12 1.257 go: github.com/gdamore/encoding@v1.0.0: Get "https://proxy.golang.org/github.com/gdamore/encoding/@v/v1.0.0.mod": x509: certificate signed by unknown authority
------
executor failed running [/bin/sh -c go mod download]: exit code: 1
```

Note that `go mod download` works fine on my host (macos), so it is something different inside docker.  

### What did you expect to see?

I expect the docker build to succeed 

### What did you see instead?

The following failure:

```
go: github.com/gdamore/encoding@v1.0.0: Get "https://proxy.golang.org/github.com/gdamore/encoding/@v/v1.0.0.mod": x509: certificate signed by unknown authority
```

**Comment by seankhliao** [comment]
have you confirmed that your `update-ca-certificates` actually updates the CA store?

**Comment by smithbk** [comment]
Yes, I looked in the /etc/ssl/certs directory and saw the `github.pem` and `proxy.golang.pem` files and the contents looked correct.

**Comment by seankhliao** [comment]
does curl work

**Comment by seankhliao** [comment]
and does setting the SSL_CERT_DIR env work?

**Comment by seankhliao** [comment]
and does setting the SSL_CERT_DIR env work?

**Comment by smithbk** [comment]
@seankhliao Adding the following to my Dockerfile fixed it.   Thanks much!

```
ENV SSL_CERT_DIR=/etc/ssl/certs
```

**Comment by smithbk** [comment]
@seankhliao Well, it looks like I prematurely closed it.  It worked once but then started failing again in the same way.  Could you please reopen?

WRT to curl, see below.

```
root@4a0548c58e5d:/usr/src/app# curl https://proxy.golang.org/github.com/gdamore/encoding/@v/v1.0.0.mod
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
root@4a0548c58e5d:/usr/src/app# curl -k https://proxy.golang.org/github.com/gdamore/encoding/@v/v1.0.0.mod
module github.com/gdamore/encoding

go 1.9

require golang.org/x/text v0.3.0
```

WRT the self-signed part, when I print the cert using `openssl s_client -showcerts -connect proxy.golang.org:443 -proxy proxy-app.discoverfinancial.com:8080 </dev/null 2>/dev/null|openssl x509 -text`, the CN and issuer are different so I don't see where the self-signed cert is coming from.

```
Subject: CN = misc-sni.google.com
Issuer: C = US, ST = Illinois, L = Riverwoods, O = DFS Services LLC, OU = BT ISS, CN = DFS SECURITY PROXY CA G2, emailAddress = firewalleng@discover.com
```

**Comment by seankhliao** [comment]
self signed would mean the signing CA not part of the trusted ca roots, so your `update-ca-certificates` invocation was ineffective.

I would talk to your IT / Infosec people on getting the actual internal CA certificates and figure out how to add it to the system trust store.

In any case, it doesn't seem to be a Go problem.

**Comment by smithbk** [comment]
@seankhliao If the internal CA certs weren't part of my system trust store, then it wouldn't work outside of docker either, right?   But that works fine for me.  Is there a way to get golang to print the unknown signing CA?  It is very difficult to debug without knowing that.

**Comment by Devil-Eloper** [comment]
How was the issue resolved?
