### ISSUE TITLE
http/request: maxBytesReader.Read int64 overflow

### ISSUE THREAD

**Issue by zhixun-cxy** [golang/go#54408]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/chenxiangyu/Library/Caches/go-build"
GOENV="/Users/chenxiangyu/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/chenxiangyu/go/pkg/mod"
GONOPROXY="gitlab.alibaba-inc.com"
GONOSUMDB="gitlab.alibaba-inc.com"
GOOS="darwin"
GOPATH="/Users/chenxiangyu/go"
GOPRIVATE="gitlab.alibaba-inc.com"
GOPROXY="http://gomodule-repository.aone.alibaba-inc.com"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/mv/q0m312c13h71lt7km7xxfk740000gn/T/go-build2968071884=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I wrote the following code in main.go:

```go
package main

import (
	"bytes"
	"io"
	"net/http"
)

func main() {
	buffer := bytes.NewBufferString("foo")
	reader := http.MaxBytesReader(nil, io.NopCloser(buffer), int64(1<<63-1))
	res := make([]byte, 3)
	if _, err := reader.Read(res); err != nil {
		println(err.Error())
	}
	println(string(res))
}

```

Then run the command `go run main.go`

### What did you expect to see?

Starting: /Users/chenxiangyu/go/bin/dlv dap --check-go-version=false --listen=127.0.0.1:56670 --log-dest=3 from /Users/chenxiangyu/arrow-cli/example/
DAP server listening at: 127.0.0.1:56670
Type 'dlv help' for list of commands.
foo
Process 35830 has exited with status 0
Detaching
dlv dap (35802) exited with code: 0

### What did you see instead?

Exception has occurred: panic
"runtime error: slice bounds out of range [:-9223372036854775808]"
Stack:
	3  0x00000000012ebb2a in net/http.(*maxBytesReader).Read
	    at /usr/local/go/src/net/http/request.go:1152
	4  0x00000000013e2d0a in main.main
	    at /Users/chenxiangyu/arrow-cli/example/main.go:13

**Comment by zhixun-cxy** [comment]
### before
```go
func (l *maxBytesReader) Read(p []byte) (n int, err error) {
	if l.err != nil {
		return 0, l.err
	}
	if len(p) == 0 {
		return 0, nil
	}
	// If they asked for a 32KB byte read but only 5 bytes are
	// remaining, no need to read 32KB. 6 bytes will answer the
	// question of the whether we hit the limit or go past it.
	if int64(len(p)) > l.n+1 {
		p = p[:l.n+1]
	}
	n, err = l.r.Read(p)

	if int64(n) <= l.n {
		l.n -= int64(n)
		l.err = err
		return n, err
	}

	n = int(l.n)
	l.n = 0

	// The server code and client code both use
	// maxBytesReader. This "requestTooLarge" check is
	// only used by the server code. To prevent binaries
	// which only using the HTTP Client code (such as
	// cmd/go) from also linking in the HTTP server, don't
	// use a static type assertion to the server
	// "*response" type. Check this interface instead:
	type requestTooLarger interface {
		requestTooLarge()
	}
	if res, ok := l.w.(requestTooLarger); ok {
		res.requestTooLarge()
	}
	l.err = errors.New("http: request body too large")
	return n, l.err
}
```
### after 
```go
func (l *maxBytesReader) Read(p []byte) (n int, err error) {
	if l.err != nil {
		return 0, l.err
	}
	if len(p) == 0 {
		return 0, nil
	}
        
        // 0 < len(p) < 2^63
	if int64(len(p)) - 1 > l.n {
		p = p[:l.n+1]
	}
	n, err = l.r.Read(p)

	if int64(n) <= l.n {
		l.n -= int64(n)
		l.err = err
		return n, err
	}

	n = int(l.n)
	l.n = 0

	type requestTooLarger interface {
		requestTooLarge()
	}
	if res, ok := l.w.(requestTooLarger); ok {
		res.requestTooLarge()
	}
	l.err = errors.New("http: request body too large")
	return n, l.err
}
```

**Comment by seankhliao** [comment]
cc @neild
