### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by renxm** [golang/go#54409]
### What is the URL of the page with the issue?
 
 https://go.dev/doc/tutorial/workspaces
 
### Screenshot
 

 
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/1243886/184313401-6918962e-dadd-4d46-9ca9-88a028acfb1f.png">

 
 
### What did you do?
 

 
 just look
 
### What did you expect to see?
 
 go run .
 
### What did you see instead?

go run example.com/hello

**Comment by seankhliao** [comment]
The invocation is a correct one.
