### ISSUE TITLE
whats the different between request.ParseMultipartForm(maxMemory) and request.MultipartReader()

### ISSUE THREAD

**Issue by mnasruul** [golang/go#54410]
Hy, I'm Muhammad Nasrul, whats the different between request.ParseMultipartForm(maxMemory) and request.MultipartReader(), i mean method request.ParseMultipartForm(maxMemory) work flow, if file size from client more than maxMemory, than the file will save at temp file, what's about request.MultipartReader()?

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by mnasruul** [comment]
yes im using question before, please https://github.com/golang/go/wiki/whats-the-different-between-request.ParseMultipartForm(maxMemory)-and-request.MultipartReader() @seankhliao

**Comment by ianlancetaylor** [comment]
@mnasruul Please read https://go.dev/wiki/Questions for places to ask a question.  Please do not ask a question by creating a page on the wiki.  Thanks.
