### ISSUE TITLE
time: optimise time.GoString

### ISSUE THREAD

**Issue by amarjeetanandsingh** [golang/go#54436]
Currently `Time.GoString` uses methods like `Year(), Month(), Day()` to generate the string. These methods call `absDate()` internally. We can improve the performance by avoiding multiple calls to `absDate()`.

**Comment by amarjeetanandsingh** [comment]
cc @ianlancetaylor @dsnet

**Comment by AAlvarez90** [comment]
@amarjeetanandsingh Thanks for your contribution and observations. Although this issue was addressed somewhere else, we appreciate the time you took to look into a potential improvement here. Well done, mate.
