### ISSUE TITLE
x/pkgsite: package removal request for github.com/dinoschristou/goff

### ISSUE THREAD

**Issue by dinoschristou** [golang/go#54431]
### What is the path of the package that you would like to have removed?

[github.com/dinoschristou/goff)](https://pkg.go.dev/github.com/dinoschristou/goff)
 
 
### Are you the owner of this package?

Yes

### What is the reason that you could not retract this package instead?

I published this be accident, the code should be sent as a PR to upstream: https://github.com/Forestmb/goff. Then a new version created from there.

**Comment by jamalc** [comment]
Please retract this module if it was published in error. Steps are available at https://go.dev/ref/mod#go-mod-file-retract.

**Comment by dinoschristou** [comment]
I would like to remove the package itself, not a specific version. Is that not possible?

i.e. remove the entry from: https://pkg.go.dev/github.com/dinoschristou/goff
