### ISSUE TITLE
x/tools/gopls: 

### ISSUE THREAD

**Issue by zvisavvy** [golang/go#54442]
### gopls version

golang.org/x/tools/gopls v0.9.3
    golang.org/x/tools/gopls@v0.9.3 h1:wfh4cfJAKwOG49sCE4ldafYeD5rlejE/gJQ7JAR5yX0=

### What did you do?

I tries to invoke a go language specific function is vscode such as "Go To Definition" for a function.77

Ever since version 0.9.2 was released (and 0.9.3 as well).  I am not able to use any go language specific functions in vscode.  If I try to "Go To Definition" in a go file, I see the following error in the Developer tools Window:

### What did you expect to see?

I expected VSCODE to position itself on source code for the function.

### What did you see instead?

VSCODE displays an endless progress bar and display the following error message in developer tools window:

workbench.desktop.main.js:2279 Error: Header must provide a Content-Length property.
	at StreamMessageReader.onData

### Editor and settings

I have seen this behaviour it the two latest version 0.9.2 and 0.9.3 when I go back to version 0.9.1 everything returns to normal function.

**Comment by findleyr** [comment]
Thank you for the issue.

This is golang/vscode-go#2406: a new vet analyzer contains a print statement that breaks jsonrpc2 communication in gopls.

It will be fixed on Monday. We only discovered this midday on Friday, and do not release over the weekend.

Sorry for the breakage.

**Comment by zvisavvy** [comment]
"Sorry for the breakage"

Thanks for everything that does work - It's great.

**Comment by findleyr** [comment]
:heart: thanks.

BTW, if you hit this bug, your project contains a time format string containing "2006-02-01" instead of "2006-01-02", which is probably incorrect (c.f. #48801)
