### ISSUE TITLE
x/tools/gopls: unsupported version 0 of Verneed record

### ISSUE THREAD

**Issue by Mr1X** [golang/go#54453]
### gopls version

v0.9.3

### go env

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/linux/.cache/go-build"
GOENV="/home/linux/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOMODCACHE="/home/linux/.go/pkg/mod"
GOOS="linux"
GOPATH="/home/linux/.go"
GOPROXY="https://mirrors.aliyun.com/goproxy/,direct"
GOROOT="/home/linux/sdk/go1.19"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/linux/sdk/go1.19/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOWORK=""
CGO_CFLAGS="-I/home/linux/rocksdb/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L/home/linux/rocksdb -lrocksdb -lstdc++ -lm -lz -lbz2 -lsnappy -llz4 -lzstd"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2598684643=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

gopls version or vscode code tips

### What did you expect to see?

gopls version or code tips

### What did you see instead?

unsupported version 0 of Verneed record

### Editor and settings

* vscode 

* "go.useLanguageServer": true,

**Comment by findleyr** [comment]
Hi, this looks like some corruption of your gopls binary (compare #46680).

How did you install and update gopls? Did you use go get, or something else? If you installed from the command line, which command exactly did you execute?

**Comment by Mr1X** [comment]
> Hi, this looks like some corruption of your gopls binary (compare #46680).
> 
> How did you install and update gopls? Did you use go get, or something else? If you installed from the command line, which command exactly did you execute?

I tried three methods
1. go install golang.org/x/tools/gopls@latest
2. go install golang.org/x/tools/gopls@v0.9.3
3. vscode Go Install/Update tools

The three results are the same

**Comment by findleyr** [comment]
I don't think this is related to gopls. It looks like this is some form of corruption of your shared libraries. For example:
https://bugzilla.redhat.com/show_bug.cgi?id=203311

Sorry, I don't think we'll be able to help you debug this. Please reopen if you think there is something gopls or go specific that is leading to this error.
