### ISSUE TITLE
gollvm: C.cpp:186:6: error: ‘class llvm::MCStreamer’ has no member named ‘SwitchSection’

### ISSUE THREAD

**Issue by advancedwebdeveloper** [golang/go#54457]
Navigate via [this](https://github.com/advancedwebdeveloper/gollvm_build_process/runs/7821213562?check_suite_focus=true#step:8:3081) link.

> /usr/bin/c++ -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/home/runner/work/gollvm_build_process/gollvm_build_process/gollvm_build_process/build_release/tools/gollvm/passes -I/home/runner/work/gollvm_build_process/gollvm_build_process/gollvm_build_process/llvm-project/llvm/tools/gollvm/passes -I/home/runner/work/gollvm_build_process/gollvm_build_process/gollvm_build_process/build_release/include -I/home/runner/work/gollvm_build_process/gollvm_build_process/gollvm_build_process/llvm-project/llvm/include -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wmisleading-indentation -fdiagnostics-color -ffunction-sections -fdata-sections -O3 -DNDEBUG  -fno-exceptions -fno-rtti -fcf-protection=none -std=c++17 -MD -MT tools/gollvm/passes/CMakeFiles/LLVMCppGoPasses.dir/GC.cpp.o -MF tools/gollvm/passes/CMakeFiles/LLVMCppGoPasses.dir/GC.cpp.o.d -o tools/gollvm/passes/CMakeFiles/LLVMCppGoPasses.dir/GC.cpp.o -c /home/runner/work/gollvm_build_process/gollvm_build_process/gollvm_build_process/llvm-project/llvm/tools/gollvm/passes/GC.cpp
> /home/runner/work/gollvm_build_process/gollvm_build_process/gollvm_build_process/llvm-project/llvm/tools/gollvm/passes/GC.cpp: In member function ‘virtual bool {anonymous}::GoGCPrinter::emitStackMaps(llvm::StackMaps&, llvm::AsmPrinter&)’:
> /home/runner/work/gollvm_build_process/gollvm_build_process/gollvm_build_process/llvm-project/llvm/tools/gollvm/passes/GC.cpp:186:6: error: ‘class llvm::MCStreamer’ has no member named ‘SwitchSection’; did you mean ‘switchSection’?
>   186 |   OS.SwitchSection(StackMapSection);
>       |      ^~~~~~~~~~~~~
>       |      switchSection

It also raises when you would try to build via Clang compiler.

CC @thanm @cherrymui @ianlancetaylor 
CC @Stetsyk

**Comment by advancedwebdeveloper** [comment]
CC @ChunyuLiao @realqhc

**Comment by realqhc** [comment]
gollvm has not yet synced with llvm trunk, you should consider using older commit like https://github.com/llvm/llvm-project/commit/bfb4c0c37078aa5ce251752d99310ccb05e1296a or use plct's branch (intended to port gollvm to RISC-V) https://github.com/plctlab/llvm-project/tree/llvm-for-gollvm.

**Comment by advancedwebdeveloper** [comment]
@thanm , I got another problem

> GC.cpp:20:10: fatal error: llvm/IR/GCStrategy.h: No such file or directory

[The link](https://github.com/advancedwebdeveloper/gollvm_build_process/runs/7907071242?check_suite_focus=true#step:8:2208)

**Comment by advancedwebdeveloper** [comment]
CC @realqhc

**Comment by realqhc** [comment]
> gollvm has not yet synced with llvm trunk, you should consider using older commit like [llvm/llvm-project@bfb4c0c](https://github.com/llvm/llvm-project/commit/bfb4c0c37078aa5ce251752d99310ccb05e1296a) or use plct's branch (intended to port gollvm to RISC-V) https://github.com/plctlab/llvm-project/tree/llvm-for-gollvm .

You are still using the wrong branch, the link provided is to branch llvm-for-gollvm

**Comment by advancedwebdeveloper** [comment]
> fatal: repository 'https://github.com/plctlab/llvm-project/tree/llvm-for-gollvm/' not found

**Comment by realqhc** [comment]
> 

Use git clone -b

**Comment by advancedwebdeveloper** [comment]
> $ git clone -b llvm-for-gollvm https://github.com/plctlab/llvm-project/tree/llvm-for-gollvm/
> Cloning into 'llvm-for-gollvm'...
> fatal: repository 'https://github.com/plctlab/llvm-project/tree/llvm-for-gollvm/' not found
>

**Comment by realqhc** [comment]
You should consider use a link that ends with .git, to obtain it, press the clone button. https://github.com/plctlab/llvm-project.git

**Comment by advancedwebdeveloper** [comment]
[done](https://github.com/advancedwebdeveloper/gollvm_build_process/runs/7916155562?check_suite_focus=true)
