### ISSUE TITLE
golang.org/x/sys/windows: Can't compile windows app 

### ISSUE THREAD

**Issue by stranger-inthenight** [golang/go#54462]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.10.8 windows/amd64
</pre>

### Does this issue reproduce with the latest release? 
Yes, since 1.13.0

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
</pre></details>

### What did you expect to see?
No errors and warnings. Backward compatibility exists

### What did you see instead?

```
../../../go/src/golang.org/x/sys/windows/syscall_windows.go:1791:11: invalid operation: 1 << pos (shift count type int, must be unsigned integer)
../../../go/src/golang.org/x/sys/windows/syscall_windows.go:1795:23: invalid operation: masked >> start (shift count type int, must be unsigned integer)

```

**Comment by ianlancetaylor** [comment]
Sorry, Go 1.10 is no longer supported.  You'll need to use at least Go 1.13.  And you may need to set `go 1.13` or later in your go.mod file.

**Comment by stranger-inthenight** [comment]
[ianlancetaylor](https://github.com/ianlancetaylor) But what happened with golang.org/x/sys? 
A couple of months ago it worked

**Comment by seankhliao** [comment]
Backwards compatibility means old code will run with newer language versions. Here you're trying to run new code with older language versions. This isn't covered by any compatibility promises.

**Comment by ianlancetaylor** [comment]
@stranger-inthenight To put it another way, what happened is that somebody committed a change to x/sys/windows that uses a language feature that was added in Go 1.13.  This is permitted as the current version of x/sys/windows is only expected to be used with currently supported versions of Go.

**Comment by stranger-inthenight** [comment]
Got it! Thank you for the comments
