### ISSUE TITLE
cmd/go: `go test -race` does not set implicit `race` build tag

### ISSUE THREAD

**Issue by 578559967** [golang/go#54468]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19 darwin/arm64

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/r/Library/Caches/go-build"
GOENV="/Users/r/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/r/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/r/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/r/workspace/testcode/testrace/tmp/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/lr/5ttkwx8x6s9fm23m80546v180000gn/T/go-build4125567734=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

run_test.go:
```
//go:build race

package tmp

import (
        "testing"

        _ "github.com/gogo/protobuf/proto"
)

func TestRun(t *testing.T) {
}
```

go.mod:
```
module testrace/tmp

go 1.19

require github.com/gogo/protobuf v1.3.2
```
go.sum:
```
github.com/gogo/protobuf v1.3.2 h1:Ov1cvc58UF3b5XjBnZv7+opcTcQFZebYjWzi34vdm4Q=
github.com/gogo/protobuf v1.3.2/go.mod h1:P1XiOD3dCwIKUDQYPy72D8LYyHL2YPYrpS2s69NZV8Q=
github.com/kisielk/errcheck v1.5.0/go.mod h1:pFxgyoBC7bSaBwPgfKdkLd5X25qrDl4LWUI2bnpBCr8=
github.com/kisielk/gotool v1.0.0/go.mod h1:XhKaO+MFFWcvkIS/tQcRk01m1F5IRFswLeQ+oQHNcck=
github.com/yuin/goldmark v1.1.27/go.mod h1:3hX8gzYuyVAZsxl0MRgGTJEmQBFcNTphYh9decYSb74=
github.com/yuin/goldmark v1.2.1/go.mod h1:3hX8gzYuyVAZsxl0MRgGTJEmQBFcNTphYh9decYSb74=
golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2/go.mod h1:djNgcEr1/C05ACkg1iLfiJU5Ep61QUkGW8qpdssI0+w=
golang.org/x/crypto v0.0.0-20191011191535-87dc89f01550/go.mod h1:yigFU9vqHzYiE8UmvKecakEJjdnWj3jj499lnFckfCI=
golang.org/x/crypto v0.0.0-20200622213623-75b288015ac9/go.mod h1:LzIPMQfyMNhhGPhUkYOs5KpL4U8rLKemX1yGLhDgUto=
golang.org/x/mod v0.2.0/go.mod h1:s0Qsj1ACt9ePp/hMypM3fl4fZqREWJwdYDEqhRiZZUA=
golang.org/x/mod v0.3.0/go.mod h1:s0Qsj1ACt9ePp/hMypM3fl4fZqREWJwdYDEqhRiZZUA=
golang.org/x/net v0.0.0-20190404232315-eb5bcb51f2a3/go.mod h1:t9HGtf8HONx5eT2rtn7q6eTqICYqUVnKs3thJo3Qplg=
golang.org/x/net v0.0.0-20190620200207-3b0461eec859/go.mod h1:z5CRVTTTmAJ677TzLLGU+0bjPO0LkuOLi4/5GtJWs/s=
golang.org/x/net v0.0.0-20200226121028-0de0cce0169b/go.mod h1:z5CRVTTTmAJ677TzLLGU+0bjPO0LkuOLi4/5GtJWs/s=
golang.org/x/net v0.0.0-20201021035429-f5854403a974/go.mod h1:sp8m0HH+o8qH0wwXwYZr8TS3Oi6o0r6Gce1SSxlDquU=
golang.org/x/sync v0.0.0-20190423024810-112230192c58/go.mod h1:RxMgew5VJxzue5/jJTE5uejpjVlOe/izrB70Jof72aM=
golang.org/x/sync v0.0.0-20190911185100-cd5d95a43a6e/go.mod h1:RxMgew5VJxzue5/jJTE5uejpjVlOe/izrB70Jof72aM=
golang.org/x/sync v0.0.0-20201020160332-67f06af15bc9/go.mod h1:RxMgew5VJxzue5/jJTE5uejpjVlOe/izrB70Jof72aM=
golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a/go.mod h1:STP8DvDyc/dI5b8T5hshtkjS+E42TnysNCUPdjciGhY=
golang.org/x/sys v0.0.0-20190412213103-97732733099d/go.mod h1:h1NjWce9XRLGQEsW7wpKNCjG9DtNlClVuFLEZdDNbEs=
golang.org/x/sys v0.0.0-20200930185726-fdedc70b468f/go.mod h1:h1NjWce9XRLGQEsW7wpKNCjG9DtNlClVuFLEZdDNbEs=
golang.org/x/text v0.3.0/go.mod h1:NqM8EUOU14njkJ3fqMW+pc6Ldnwhi/IjpwHt7yyuwOQ=
golang.org/x/text v0.3.3/go.mod h1:5Zoc/QRtKVWzQhOtBMvqHzDpF6irO9z98xDceosuGiQ=
golang.org/x/tools v0.0.0-20180917221912-90fa682c2a6e/go.mod h1:n7NCudcB/nEzxVGmLbDWY5pfWTLqBcC2KZ6jyYvM4mQ=
golang.org/x/tools v0.0.0-20191119224855-298f0cb1881e/go.mod h1:b+2E5dAYhXwXZwtnZ6UAqBI28+e2cm9otk0dWdXHAEo=
golang.org/x/tools v0.0.0-20200619180055-7c47624df98f/go.mod h1:EkVYQZoAsY45+roYkvgYkIh4xh/qjgUK9TdY2XT94GE=
golang.org/x/tools v0.0.0-20210106214847-113979e3529a/go.mod h1:emZCQorbCU4vsT4fOWvOPXz4eW1wZW4PmDk9uLelYpA=
golang.org/x/xerrors v0.0.0-20190717185122-a985d3407aa7/go.mod h1:I/5z698sn9Ka8TeJc9MKroUUfqBBauWjQqLJ2OPfmY0=
golang.org/x/xerrors v0.0.0-20191011141410-1b5146add898/go.mod h1:I/5z698sn9Ka8TeJc9MKroUUfqBBauWjQqLJ2OPfmY0=
golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543/go.mod h1:I/5z698sn9Ka8TeJc9MKroUUfqBBauWjQqLJ2OPfmY0=
golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1/go.mod h1:I/5z698sn9Ka8TeJc9MKroUUfqBBauWjQqLJ2OPfmY0=
```

compile and run the test:
```
$ go test -race ./...
```

### What did you expect to see?
expect to see:
```
ok      testrace/tmp    0.425s
```

### What did you see instead?
```
# testrace/tmp
run_test.go:8:2: cannot find package
FAIL    testrace/tmp [setup failed]
FAIL
```

but the go1.17.10 can compile successfully and output the expected result.

**Comment by mengzhuo** [comment]
This is WAI, as your code shows
```
//go:build race
```
You are using build constraints https://pkg.go.dev/go/build#hdr-Build_Constraints

In the meantime `go test -race` is passing a race argument into compiler (note it's not a build tag)

**Comment by 578559967** [comment]
> This is WAI, as your code shows
> 
> ```
> //go:build race
> ```
> 
> You are using build constraints https://pkg.go.dev/go/build#hdr-Build_Constraints
> 
> In the meantime `go test -race` is passing a race argument into compiler (note it's not a build tag)

Won't go add build tag "race" when race enabled?
Why go1.17 works fine?
Why it works fine if not import thirdparty package?
And when I add "-x -a" flags, I see it compiles go/src/runtime/race.go which also has build constraints "go:build race" in its head.

**Comment by mengzhuo** [comment]
Go1.17 isn't works fine, it's a bug.
The `race` argument should be command line only, and this is droped at https://github.com/golang/go/commit/931d80ec17374e52dbc5f9f63120f8deb80b355d (cmd/go/internal/work/init.go), which @rsc stats 
> - Change the tags list to match the -tags command-line argument.
> - Add msan and race, echoing the -msan and -race arguments
  (always 'true' when present, omitted when false).

If you insist this is a bug, I can reopen it.

**Comment by ianlancetaylor** [comment]
I think there is a bug here.  We may be enabling the "race" build constraint for some purposes but not others.  Changing `race` to, say, `race1` in the test case produces a completely different result (`go: warning: "./..." matched no packages`).

**Comment by 578559967** [comment]
I think this is a bug.
If "-race" does not add tag "race", it should not compile the test file "run_test.go" and will output `go: warning: "./..." matched no packages` instead. But actually it compiles the file and report the import error.

And I find that if we build with the single file instead of "./...", it will pass:
```
$ go test -race ./run_test.go
ok      command-line-arguments  0.362s

$ go test -race ./...
# testrace/tmp
run_test.go:8:2: cannot find package
FAIL    testrace/tmp [setup failed]
FAIL
```

**Comment by bcmills** [comment]
The implicit `race` build tag is documented in https://go.dev/doc/articles/race_detector#Excluding_Tests, so I agree that this looks like a `cmd/go` bug.

**Comment by bcmills** [comment]
@578559967, can you identify a Go version at which the test worked as expected (perhaps using `// +build` instead of `//go:build`, if it was prior to #41184)? If this is a regression, we can probably bisect it.

**Comment by 578559967** [comment]
> @578559967, can you identify a Go version at which the test worked as expected (perhaps using `// +build` instead of `//go:build`, if it was prior to #41184)? If this is a regression, we can probably bisect it.

go1.17.5、go1.17.10、go1.17.13 all worked as expected.
go1.18~go1.18.5、go1.19 all failed.

**Comment by ZekeLu** [comment]
`git bisect` shows that 931d80ec17374e52dbc5f9f63120f8deb80b355d is the commit that changed the behavior.

```diff
diff --git a/src/cmd/go/internal/work/init.go b/src/cmd/go/internal/work/init.go
index dc368de1c1..26192ecaed 100644
--- a/src/cmd/go/internal/work/init.go
+++ b/src/cmd/go/internal/work/init.go
@@ -138,7 +138,7 @@ func instrumentInit() {
        cfg.BuildContext.InstallSuffix += "_"
    }
    cfg.BuildContext.InstallSuffix += mode
-   cfg.BuildContext.BuildTags = append(cfg.BuildContext.BuildTags, mode)
+   cfg.BuildContext.ToolTags = append(cfg.BuildContext.ToolTags, mode)
 }
```

`BuildContext.ToolTags` is introduced by dba89283ad05e600defc41dbf94df91ce9027566. `cmd/go/internal/imports.loadTags()` should be updated to merge tags from `BuildContext.ToolTags`. I have sent a CL to fix that.

**Comment by bcmills** [comment]
@gopherbot, please backport to Go 1.19 and 1.18. This is a regression from prior releases that can cause build failures.
