### ISSUE TITLE
go/types, types2: Syntax (interface vs nil struct) This example breaks the concept of passing nil values to interface

### ISSUE THREAD

**Issue by vorishirne** [golang/go#54470]
### What version of Go are you using (`go version`)? 

<pre>
$ go version
go version 1.18.2
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/vorishirne/.cache/go-build"
GOENV="/home/vorishirne/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/vorishirne/go/pkg/mod"
GONOPROXY="gitlab.private.aws.cradlepointecm.com"
GONOSUMDB="gitlab.private.aws.cradlepointecm.com"
GOOS="linux"
GOPATH="/home/vorishirne/go"
GOPRIVATE="gitlab.private.aws.cradlepointecm.com"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/vo/wo/repository/aaorg/ncx-auth/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""                                                                                                                               
CGO_CXXFLAGS="-g -O2"                                                                                                                         
CGO_FFLAGS="-g -O2"                                                                                                                           
CGO_LDFLAGS="-g -O2"                                                                                                                          
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2039916513=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

```go
package main

import (
	"fmt"
)


type IO interface {
	Foo()
}

type IOImplementation struct {
}

func (e IOImplementation) Foo() {
}

func returnNilIO() *IOImplementation {
	return nil
}


func main() {
	var io IO
	io = returnNilIO()
	if io != nil {
		fmt.Printf("io is %v", io)
	}
}

```

### What did you expect to see?
<No output>

### What did you see instead?
io is nil

Is this phenomena documented somewhere? How to pass nil to an interface in this case.

**Comment by mvdan** [comment]
https://go.dev/doc/faq#nil_error

The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.
