### ISSUE TITLE
access: may-start-trybots and approvers

### ISSUE THREAD

**Issue by panjf2000** [golang/go#54499]
Hi, I'm applying for "may-start-trybots" and "approvers" access, membership of https://github.com/golang as well, thanks!

Email: panjf2000@gmail.com
Contributions: [via gerrit](https://go-review.googlesource.com/q/author:panjf2000%2540gmail.com) and [via github](https://github.com/golang/go/commits?author=panjf2000)
Group: https://go-review.googlesource.com/#/admin/groups/1030,members, https://go-review.googlesource.com/#/admin/groups/1005,members, https://github.com/golang

/cc @golang/release

See https://go.dev/wiki/GerritAccess

**Comment by seankhliao** [comment]
cc @golang/release

**Comment by panjf2000** [comment]
Hi, I've been working on several CLs recently, it would be a great help if this process could be expedited, thanks~

**Comment by heschi** [comment]
Hi Andy,

Thank you for your contributions! After some discussion, we decided that it's too early for Approvers access -- we appreciate all the cleanup work, but it doesn't form a large enough history for us to evaluate. However, we're very happy to give you TryBot access. I've added you to the may-start-trybots group, so you should be able to do that now. 

As you've likely read at https://golang.org/wiki/GerritAccess#trybot-access-may-start-trybots, please be sure to at least skim CLs before starting a Trybot run.

Let us know if you have any questions or issues with it, and thanks again!

**Comment by panjf2000** [comment]
Hi @heschi , sorry to hear that, I believe I used to do more than just trivial cleanup work, but also some feature development, performance optimization and bug fixing, so could you please tell me what specific prerequisites are needed before I can officially apply for go-approver access? Thanks~

Besides, I was also requesting to be in https://github.com/orgs/golang/teams/go-approvers for https://go.dev/wiki/Gardening and https://github.com/golang/go/wiki/HandlingIssues, as a member of https://github.com/orgs/golang, helping handle some github issues, please also take a look at this request, thank you!

**Comment by ianlancetaylor** [comment]
@panjf2000 An approvers grant is normally reserved for people whose CLs are routinely approved with no comments.  I don't think your CLs are at that point yet.  Sorry.

Issue gardening doesn't require approvers access, as the issues are managed in GitHub, not Gerrit.  It's a bit confusing, as the GitHub name is "go-approvers" (not "approvers") for some reason..  I sent you an invitation to the GitHub group.

**Comment by panjf2000** [comment]
Hi all,
I'd like to reapply for the  `Code-Review+2` permission at this point.

I've had a few [pending submissions](https://go-review.googlesource.com/q/author:panjf2000%2540gmail.com) lately, along with a series of pending CLs locally (haven't uploaded yet). It would really help me expedite my work onGerritt if I have permission to submit CLsthath have gained sufficient votes. Thanks!

**Comment by panjf2000** [comment]
cc @golang/release

**Comment by panjf2000** [comment]
Ping @golang/release

**Comment by panjf2000** [comment]
Hi @golang/release, I have a few new [ready-to-submit CLs](https://go-review.googlesource.com/q/owner:panjf2000@gmail.com) recently and my request for `+2` permission has been around for quite a while, I wonder what its current status is?

**Comment by dmitshur** [comment]
Hi @panjf2000, thanks for contributing to the Go project and asking for approvers access again.

We considered this request. As documented at https://go.dev/wiki/GerritAccess, Gerrit "approvers" access permits reviewing and submitting CLs across the entire Go project, and I know you've expressed in helping with `net` and `net/http` package maintenance in particular. It's a high bar to clear to get access to leave +2 reviews, and your contribution history is not currently at a point where we can confidently grant it. We'll decline this request for now, but please feel free to reapply after some time.

For CLs that you've authored that have a +2 Code-Review vote and are ready to be submitted from your side, please don't hesitate to ask the person who left the +2 vote to submit your CL (or leave an Auto-Submit+1 vote if you don't anticipate needing to push additional patch sets, e.g., if it's just waiting for the last trybot run). Thanks again.

**Comment by panjf2000** [comment]
> or to leave an Auto-Submit+1 vote if you don't anticipate needing to push additional patch sets, e.g., if it's just waiting for the last trybot run

I didn't know I had the `Auto-Submit+1` permission already? Where can I find this vote? I don't see any on Gerrit.

**Comment by dmitshur** [comment]
@panjf2000 The Auto-Submit+1 vote is documented at https://go.dev/wiki/GerritAccess#auto-submit. I meant you can ask the person who left the +2 vote to either submit or leave Auto-Submit+1 vote—but it needs to be done by someone who is an approver.

**Comment by panjf2000** [comment]
> It's a high bar to clear to get access to leave +2 reviews, and your contribution history is not currently at a point where we can confidently grant it.

To be frank, I can understand setting the "high bar" for `+2` permission, it's just that the criteria for that threshold have always seemed unclear to me. Furthermore, I'm not trying to seek permission to submit any CLs in "the entire Go project", I only want to be able to submit those CLs that were created by myself and have already gained sufficient votes from Google staff. It's fine for me to have the permission that only allows me to submit my own "ready-to-submit" CLs, if that kind of permission exists. I've been constantly contributing over 120 commits to the Go project for almost five years. If that still can't suffice to qualify me, I believe I must haven't been doing things right. Please show me what I have done wrong and point me in the right direction so that I can be on the track of earning a `+2` permission afterward.

**Comment by panjf2000** [comment]
> It's a high bar to clear to get access to leave +2 reviews, and your contribution history is not currently at a point where we can confidently grant it.

To be frank, I can understand setting the "high bar" for `+2` permission, it's just that the criteria for that threshold have always seemed unclear to me. I've been constantly contributing over 120 commits to the Go project across `net`, `net/http`, `runtime`, `os`, `internal/poll`, `log/slog`, `encoding`, etc. and participating in resolving GitHub issues for almost five years. If that still can't suffice to qualify me, I believe I must haven't been doing things right. Please show me what I have done wrong and point me in the right direction so that I can be on the track of earning a `+2` permission afterward.

**Comment by panjf2000** [comment]
I guess what I'm trying to figure out is how far I am to the `+2` permission, because at this moment I really can't tell what more I have to do before I should reapply again, or when to do it.
