### ISSUE TITLE
cmd/6g: free ephemeral maps

### ISSUE THREAD

**Issue by bradfitz** [golang/go#5449]
<pre>In a function like,

func foo() {
    m := make(map[int]int)
    m[1] = 2
}

The compiler could know the map doesn't escape foo and insert an explicit map delete
call in the generated code.

(Inspired from actual code reviews where I see maps used with short lifetimes.)</pre>

**Comment by dvyukov** [comment]
We don't have free function in runtime anymore.
But we could detect that map does not escape and allocate map descriptor and one bucket on stack in this case.
