### ISSUE TITLE
access: may-start-trybots

### ISSUE THREAD

**Issue by doujiang24** [golang/go#54494]
See https://go.dev/wiki/GerritAccess

Hi! I'm working on [CL 424374](https://go-review.googlesource.com/c/go/+/424374) for #54458 , it would be very helpful if I can start trybots to check the changes.
I know the trybots are relatively sensitive infrastructure, and I will take good care of it. Thanks.

Group: https://go-review.googlesource.com/#/admin/groups/1030,members
Email: doujiang24@gmail.com

cc @golang/release @prattmic @ianlancetaylor

**Comment by seankhliao** [comment]
cc @golang/release

**Comment by heschi** [comment]
Hi @doujiang24 , thanks for your contributions to the Go project so far! I have a personal interest in viewcore so it's great to see someone working on it.

We generally prefer that contributors have an established track record before granting trybot access. It looks like you're off to a strong start, but it's still early. I'm going to decline this for now, but please keep up the good work and feel free to reapply in a while.

Thanks again!
