### ISSUE TITLE
cmd/compile: missed optimization: binary alignment is unnecessarily complex

### ISSUE THREAD

**Issue by piotr-sneller** [golang/go#54496]
### What version of Go are you using (`go version`)?

<pre>
1.19
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
amd64/windows

<details><summary> If binary alignment like in the function below is encountered, the compiler correctly strength reduces the division/multiplication to shifts, but then fails to combine them into a single `and`. In general `(x >> N) << N` should be further folded to `x & -(1 << N)` for constant N during strength reduction</summary><br><pre>

</pre></details>

### What did you do?

```
package testcase

func foo(x uint) uint {
    return x / 64 * 64
}
```
Compile:
`go tool compile -S t1.go`

Output:
```
<unlinkable>.foo STEXT nosplit size=9 args=0x8 locals=0x0 funcid=0x0 align=0x0                  
        0x0000 00000 (t1.go:4)  TEXT    <unlinkable>.foo(SB), NOSPLIT|ABIInternal, $0-8         
        0x0000 00000 (t1.go:4)  FUNCDATA        $0, gclocals·g2BeySu+wFnoycgXfElmcg==(SB)       
        0x0000 00000 (t1.go:4)  FUNCDATA        $1, gclocals·g2BeySu+wFnoycgXfElmcg==(SB)       
        0x0000 00000 (t1.go:4)  FUNCDATA        $5, <unlinkable>.foo.arginfo1(SB)               
        0x0000 00000 (t1.go:4)  FUNCDATA        $6, <unlinkable>.foo.argliveinfo(SB)            
        0x0000 00000 (t1.go:4)  PCDATA  $3, $1                                                  
        0x0000 00000 (t1.go:5)  SHRQ    $6, AX <= here                                              
        0x0004 00004 (t1.go:5)  SHLQ    $6, AX <= here                                                   
        0x0008 00008 (t1.go:5)  RET   
```                                                          

### What did you expect to see?
`ANDQ $FFFFFFFFFFFFFFC0, AX`

### What did you see instead?
```
SHRQ    $6, AX
SHLQ    $6, AX
```

**Comment by randall77** [comment]
We used to do the optimization in the other direction (and => 2 shifts) because it uses one less register in the case where the constant needs to be materialized (e.g. >>48<<48).
That was removed in https://go-review.googlesource.com/c/go/+/196810/ , but we didn't add the (2 shifts => and) rule. We probably should.

We do handle >>1<<1 with BTR.

@martisch
