### ISSUE TITLE
access: may-start-trybots

### ISSUE THREAD

**Issue by kolyshkin** [golang/go#54508]
I'd like to request "may-start-trybots" access for myself.

Group: https://go-review.googlesource.com/#/admin/groups/1030
Gerrit email: kolyshkin@gmail.com
Ref: https://go-review.googlesource.com/c/go/+/417694/comments/498bf05c_b9d353ef

Thanks.

**Comment by seankhliao** [comment]
cc @golang/release

**Comment by kolyshkin** [comment]
cc @cagedmantis PTAL 🙏🏻

**Comment by heschi** [comment]
Hi Kir,

Thank you for your contributions and for requesting Trybots access! I've added you to the may-start-trybots group, so you should be able to do so now.

As you've likely read at https://golang.org/wiki/GerritAccess#trybot-access-may-start-trybots, please be sure to at least skim CLs before starting a Trybot run.

Let us know if you have any questions or issues with it, and thanks again!
