### ISSUE TITLE
x/pkgsite: package removal request for https://pkg.go.dev/github.com/instill-ai/protogen-go

### ISSUE THREAD

**Issue by pinglin** [golang/go#54507]
### What is the path of the package that you would like to have removed?

https://pkg.go.dev/github.com/instill-ai/protogen-go@v0.3.0-alpha
 
### Are you the owner of this package?

yes
 
### What is the reason that you could not retract this package instead?

I can retract `v0.3.0-alpha` but it seems the package page is no longer updated correctly after I published a `v0.3.1-alpha`. I suspect the publishing chain has been broken due to the delete of `v0.3.0-alpha` tag in the original GitHub repo.

Can you help remove `v0.3.0-alpha` and put `v0.3.1-alpha` in place? Also wondering what's the best practice here. Thanks.

**Comment by seankhliao** [comment]
it looks correct
