### ISSUE TITLE
x/tools: better isolate lsp code under gopls submodule

### ISSUE THREAD

**Issue by rsc** [golang/go#54509]
Today there is a module reference cycle between x/tools and x/text,
which we'd ideally like to remove to make it easier to tag modules.

x/text depends on x/tools for x/tools/go/loader.
That should probably be updated to use go/packages, but so be it.
It's a fairly reasonable use of x/tools either way.

x/tools depends on x/text only for x/tools/internal/lsp/source,
which uses golang.org/x/text/unicode/runenames in Hover.

The reference cycle would “naturally” go away if we move some of the internals around
so that internal/lsp can move to gopls/internal/lsp.
There are very few uses of internal/lsp outside gopls, and what's there is fairly generic
and would make sense outside of internal/lsp.

So it looks like this would work:

	internal/lsp/diff -> internal/diff (used in go/analysis/analysistest)
	internal/lsp/fuzzy -> internal/fuzzy (used in internal/analysisinternal)
	internal/lsp/debug/tag -> internal/event/tag (used in internal/jsonrpc2)
	internal/lsp -> gopls/internal/lsp

At that point the x/text reference would be entirely under gopls.

That feels cleaner anyway, and also a step toward making it possible to move gopls to x/gopls at some point.

It's a pretty straightforward change, especially since package boundaries and package names are not changing.
I'm happy to send the CLs.

Is there any gotcha here that I'm missing?

/cc @hyangah @adonovan @findleyr @ianthehat @heschi

**Comment by findleyr** [comment]
No gotcha. We are planning to move everything under the gopls module eventually. We can do this now if there is need.

Let me send a CL.

**Comment by findleyr** [comment]
Discussing with the team and thinking about this a bit more, there are some potential sources of churn with this change.
 - In progress CLs will be disrupted
 - Potentially more (or maybe fewer) test flakes due to test colocation.

I think it makes sense to set a date for this change, perhaps at the end of the month (I'm out next week).

**Comment by findleyr** [comment]
We're planning to do this on August 30th.

**Comment by findleyr** [comment]
Has been a couple weeks with no issues, so I'll close this.
