### ISSUE TITLE
cmd/compile: <autogenerated>:1: internal compiler error

### ISSUE THREAD

**Issue by DmitriyMV** [golang/go#54504]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.19
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

It reproduces even on playground.

### What did you do?

https://go.dev/play/p/ofUDuB6gNud

### What did you expect to see?

Build runs successfully. 

### What did you see instead?

```
<autogenerated>:1: internal compiler error: panic: runtime error: invalid memory address or nil pointer dereference

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new

Go build failed.
```

**Comment by DmitriyMV** [comment]
Probably related to #54326

**Comment by cuonglm** [comment]
Duplicated of https://github.com/golang/go/issues/53982

**Comment by DmitriyMV** [comment]
@cuonglm minor nit - this is not duplicate of #53982 but of #54302 🙂
