### ISSUE TITLE
affected/package:  when I create a module named reflect, it cannot get  the compiled binary file

### ISSUE THREAD

**Issue by liuzq2015** [golang/go#54519]
### What version of Go are you using (`go version`)?
1.3-1.8
<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

![企业微信截图_16608040699814](https://user-images.githubusercontent.com/12743855/185309412-cd4954a3-fbb0-4de3-b05e-d883e438c9ff.png)

### What did you expect to see?

I expect to see a binary file reflect is generated

### What did you see instead?
But is nothing...
And when I change the module name to anyother, like reflect1/test/xxx and so on, it worked, when I go build, it generate a binary file named  reflect1/test/xxx and so on
![企业微信截图_16608042951396](https://user-images.githubusercontent.com/12743855/185309999-532a1575-5ba8-40e0-9892-d14953ae4b89.png)

**Comment by liuzq2015** [comment]
as a supplement， any folder name in the go project will cause this problem too...
![企业微信截图_16608072562577](https://user-images.githubusercontent.com/12743855/185334643-92f2a194-7a8a-4d1f-966c-409eacd44ed5.png)

**Comment by seankhliao** [comment]
Working as intended, see #32819
