### ISSUE TITLE
x/website: documentation no longer suggests to add $GOPATH/bin to the user's PATH

### ISSUE THREAD

**Issue by leaanthony** [golang/go#54510]
### Does this issue reproduce with the latest release?

Yes

### 

</pre></details>

### What did you do?

I went to the installation page.

### What did you expect to see?

That adding `$HOME/go/bin` to your path was necessary to make `go install` function as expected.

### What did you see instead?

A lot of bug reports on my project that they can't run the project binary after installing.

**Comment by ALTree** [comment]
The suggestion has always been there, must have been lost after the recent website reshuffling.

**Comment by SrijanSriv** [comment]
i believe this has been [updated](https://go.dev/doc/install#:~:text=Add%20/usr/local/go/bin%20to%20the%20PATH%20environment%20variable).

**Comment by leaanthony** [comment]
Thanks all 🙏

**Comment by leaanthony** [comment]
The windows docs do not state this so I can only assume it's set up as part of the installation?
