### ISSUE TITLE
access: may-start-trybots

### ISSUE THREAD

**Issue by qmuntal** [golang/go#54521]
Hi,

I'd like to request "may-start-trybots" access https://go-review.googlesource.com/#/admin/groups/1030,members for [quimmuntal@gmail.com](https://go-review.googlesource.com/q/owner:quimmuntal).

See https://go.dev/wiki/GerritAccess

cc @seankhliao

**Comment by seankhliao** [comment]
cc @golang/release

**Comment by heschi** [comment]
Hi Quim,

Thank you for your contributions and for requesting Trybots access! I've added you to the may-start-trybots group, so you should be able to do so now.

As you've likely read at https://golang.org/wiki/GerritAccess#trybot-access-may-start-trybots, please be sure to at least skim CLs before starting a Trybot run.

Let us know if you have any questions or issues with it, and thanks again!
