### ISSUE TITLE
x/pkgsite: package cosmossdk.io/depinject@v1.0.0-alpha.2 not showing up

### ISSUE THREAD

**Issue by facundomedica** [golang/go#54522]
### What is the URL of the page with the issue?
 
[ cosmossdk.io/depinject@v1.0.0-alpha.2](https://pkg.go.dev/cosmossdk.io/depinject@v1.0.0-alpha.2)
 
### What did you do?
 
Tagged a version (which once was previously tagged but contained a wrong module name: "github.com/cosmos/cosmos-sdk/depinject", instead of "cosmossdk.io/depinject").
 
### What did you expect to see?
 
 I expect this URL to show our module: https://pkg.go.dev/cosmossdk.io/depinject@v1.0.0-alpha.2
 
### What did you see instead?

I can access https://pkg.go.dev/cosmossdk.io/depinject but it shows an untagged version.

**Comment by seankhliao** [comment]
it shows up now
