### ISSUE TITLE
access: may-start-trybots and GitHub memberships

### ISSUE THREAD

**Issue by Abirdcfly** [golang/go#54523]
Hi team,

I am a go user and have also committed some CLs [My Gerrit Dashboard](https://go-review.googlesource.com/dashboard/56538) So I’d like to request "may-start-trybots" access to speed up the merging process of some CLs.

I am also a [member of kubernetes Github Org](https://github.com/orgs/kubernetes/people?query=abirdcfly) and have [contributed some CLs to kubernetes](https://github.com/search?o=desc&q=is%3Apr+author%3AAbirdcfly+sort%3Aupdated-desc+org%3Akubernetes&s=updated&type=Issues), So I'm familiar with Github issue and the testbot process ( kubernetes-bot is very similar to Gopher Robot ).

**I want get https://github.com/orgs/golang/teams/go-assignees for @Abirdcfly**

**And https://go-review.googlesource.com/#/admin/groups/1030,members for fp544037857@gmail.com**

Thank you !

cc @golang/release

**Comment by seankhliao** [comment]
cc @golang/release

**Comment by heschi** [comment]
Hi @Abirdcfly, thanks for your contributions to the Go project so far!

We generally prefer that contributors have an established track record before granting these permissions. It looks like you're off to a strong start, but it's still early. I'm going to decline this for now, but please keep up the good work and feel free to reapply in a while.

Thanks again!
