### ISSUE TITLE
cmd/compile: failed to compile some recursive generic type

### ISSUE THREAD

**Issue by johejo** [golang/go#54535]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.20-a719a78c1b Fri Aug 19 00:29:18 2022 +0000 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

tip only

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/mitsuoheijo/Library/Caches/go-build"
GOENV="/Users/mitsuoheijo/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/mitsuoheijo/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/mitsuoheijo/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/mitsuoheijo/ghq/github.com/golang/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/mitsuoheijo/ghq/github.com/golang/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="devel go1.20-a719a78c1b Fri Aug 19 00:29:18 2022 +0000"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/mitsuoheijo/ghq/github.com/johejo/sandbox/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bq/s3vkkxm17jq79lx5qy3856zh0000gn/T/go-build3085638013=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```go
package main

type node[T any] struct {
	items    items[T]
	children items[*node[T]]
}

func (n *node[T]) f(i int, j int) bool {
	if len(n.children[i].items) < j {
		return false
	}
	return true
}

type items[T any] []T

func main() {
	_ = node[int]{}
	println("hello")
}
```

### What did you expect to see?

```
$ go run .
hello
```

### What did you see instead?

```
$ gotip run .
# github.com/johejo/sandbox
./main.go:9:22: n.children[i].items undefined (type go.shape.*uint8 has no field or method items)
```

This might be some regression.
I found this problem while using google/btree.
https://github.com/google/btree

**Comment by cuonglm** [comment]
@hopehook Oh right, I messed up my operation.

It runs ok in `nounified`:

```
GOEXPERIMENT=nounified go run r.go
```

cc @mdempsky

**Comment by mdempsky** [comment]
Thanks for the report!

Further minimized test case:

```
package main

type s[T any] struct{ f T }

func f[T any]() {
	var x s[*struct{ g T }]
	_ = x.f.g
}

func main() {
	_ = f[int]
}
```

This is an issue with pointer shaping. The type `items[*struct{g T}]` gets pointer shaped to `items[*byte]`, which means `x.f` has shape type `*byte`. We need to insert an implicit conversion back to `*struct{g T}` so that we can select the `g` field.

**Comment by hopehook** [comment]
FYI: bisect shows bad at this CL: https://go-review.googlesource.com/c/go/+/422235.

**Comment by mdempsky** [comment]
@hopehook Thanks, that's not surprising.

FWIW, more useful would be if you can force `GOEXPERIMENT=unified` while bisecting. But I'm pretty sure that will bisect to CL 424734.

**Comment by hopehook** [comment]
@mdempsky Yes, you are right.
