### ISSUE TITLE
x/pkgsite: bsd-4-clause link is broken

### ISSUE THREAD

**Issue by willfaught** [golang/go#54540]
### What is the URL of the page with the issue?

https://pkg.go.dev/license-policy

### What is your user agent?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6 Safari/605.1.15

### Screenshot

<img width="848" alt="Screen Shot 2022-08-18 at 8 27 50 PM" src="https://user-images.githubusercontent.com/63830/185536589-e2bfeb4f-7ac5-47c4-925b-f2fca3880127.png">

### What did you do?

- Went to https://pkg.go.dev/license-policy
- Clicked on the "BSD-4-Clause" and "BSD-4-Clause-UC" links.

### What did you expect to see?

Links work

### What did you see instead?

404

---

The links are https://opensource.org/licenses/BSD-4-Clause and https://opensource.org/licenses/BSD-4-Clause-UC.

What were probably intended were https://spdx.org/licenses/BSD-4-Clause.html and https://spdx.org/licenses/BSD-4-Clause-UC.html.

**Comment by willfaught** [comment]
OMG, more:

-https://opensource.org/licenses/AGPL-3.0-only
- https://opensource.org/licenses/BSD-3-Clause-Open-MPI
- https://opensource.org/licenses/BSD-3-Clause-Clear
- https://opensource.org/licenses/BSD-3-Clause-LBNL
- https://opensource.org/licenses/BSD-3-Clause-Open-MPI

I guess just test them all.

**Comment by Kucukaslan** [comment]
It seems those licenses are not OSI approved licences[^osi] but the pkgsite generates the URLs as if they're OSI approved. I think adding them to [nonOSILicenses](https://github.com/golang/pkgsite/blob/master/internal/licenses/licenses.go#L226-L238) map in the website source code would fix it. I'll give it a try and open a PR to fix.

[^osi]: https://opensource.org/licenses/alphabetical
