### ISSUE TITLE
runtime: cgoCheckUnknownPointer triggering incorrectly

### ISSUE THREAD

**Issue by rolandshoemaker** [golang/go#54558]
A flakey test in x/crypto seems to be surfacing an issue with `runtime.cgoCheckUnknownPointer`, e.g. https://build.golang.org/log/d95a3c5e412f55ba2574530a147983e1546cf6eb.

The call to `_goboringcrypto_HMAC_Init` is triggering the `runtime.cgoCheckUnknownPointer` check on `unsafe.Pointer(base(h.key))`. This reproduces inconsistently, it seems like in the failure cases the span element size does not match the array size, but beyond that this is deeper in the runtime than I can particularly understand 🤷.

Git bisect suggests https://go.dev/cl/422634 introduced this issue.

cc @rsc @randall77

**Comment by ianlancetaylor** [comment]
See the approach used by https://go.dev/cl/404295.  The approach used there might fix the problem here.
