### ISSUE TITLE
nm

### ISSUE THREAD

**Issue by duaneking** [golang/go#54565]
We made a mistake because AWS docs are terrible. nm

**Comment by rhysh** [comment]
Go’s name for x86_64 is “GOARCH=amd64”.

Go’s name for AArch64, for 64-bit ARM processors, is “GOARCH=arm64”.

It looks like the environment variables in your report are asking for the wrong arch, though maybe I misread. They look very similar. Try “arm64”.

**Comment by duaneking** [comment]
Nope, amd64 is correct per https://github.com/aws/aws-lambda-go

**Comment by duaneking** [comment]
Its important to state that amd64 works as expected and generates the output given that we expect when used on a linux box.

**Comment by rhysh** [comment]
Setting GOARCH=arm64 should result in a program for 64-bit ARM / AArch64.

The Graviton-specific instructions at https://aws.amazon.com/blogs/compute/migrating-aws-lambda-functions-to-arm-based-aws-graviton2-processors/ suggest `GOOS=linux GOARCH=arm64 go build`.

**Comment by duaneking** [comment]
AWS docs suck.  NM
