### ISSUE TITLE
x/pkgsite: package removal request for [https://github.com/yunacatw/bitgin]

### ISSUE THREAD

**Issue by ghost** [golang/go#54560]
### What is the path of the package that you would like to have removed?

github.com/yunacatw/bitgin
 
### Are you the owner of this package?

YES
 
### What is the reason that you could not retract this package instead?

Already set module retraction, but it still exists in https://pkg.go.dev/github.com/yunacatw/bitgin

Please help me to remove this package, thanks.

**Comment by seankhliao** [comment]
retraction requires tagging a new higher version
