### ISSUE TITLE
time: Parse of RFC3339 is incorrect for hour field

### ISSUE THREAD

**Issue by dsnet** [golang/go#54568]
RFC 3339, section 5.6 specifies that the `time-hour` field must be two digits wide.

However, [`Parse` permits that field having only a single digit](https://go.dev/play/p/Qo4_YDlHt6w):
```go
Parse(time.RFC3339, "0000-01-01T0:00:00+00:00")
```
reports nil rather than an error.

**Comment by seankhliao** [comment]
same as #29911 ?

**Comment by dsnet** [comment]
It's related. If we're unwilling to change the meaning of "15", we could detect that the format is RFC3339 and perform a stricter check.

**Comment by dsnet** [comment]
Closing as dupe of #29911. The `Unmarshal` methods have been modified to perform strict checking. That change is more justifiable since they're explicitly documented as using RFC 3339 and the `Marshal` methods already have some checks for strict RFC 3339 compliance.
