### ISSUE TITLE
time: Parse of RFC3339 is incorrect for fractional second seperator

### ISSUE THREAD

**Issue by dsnet** [golang/go#54571]
RFC 3339, section 5.6 specifies that the `time-secfrac` field must use a period.

However, [Parse permits the use of commas](https://go.dev/play/p/Yxw7tMABIkB):
```go
Parse(time.RFC3339, "0000-01-01T00:00:00,0Z")
```
reports nil rather than an error.

**Comment by dsnet** [comment]
Unfortunately, this behavior is specified in the docs:
> A **comma or decimal point** followed by one or more zeros represents a fractional second,
> printed to the given number of decimal places.
> A **comma or decimal point** followed by one or more nines represents a fractional second,
> printed to the given number of decimal places, with trailing zeros removed.
> For example "15:04:05,000" or "15:04:05.000" formats or parses with millisecond precision.

**Comment by seankhliao** [comment]
That is a relatively recent addition #6189, at some point in the past, we didn't support it #24860
Maybe it would be ok to roll it back for RFC3339

**Comment by dsnet** [comment]
Yuck. In my opinion #6189 was a mistake. We probably should instead have allowed the format string to have a `,` where it means either `,` or `.`, while keeping the presence of `.` to only mean `.`.

**Comment by dsnet** [comment]
Closing as the allowance of commas was a deliberate decision in #6189. 

The `Unmarshal` methods have been modified to perform strict checking. That change is more justifiable since the methods are explicitly documented as using RFC 3339 and the `Marshal` methods already have some checks for strict RFC 3339 compliance.
