### ISSUE TITLE
cmd/compile: ppc64 port is broken

### ISSUE THREAD

**Issue by yejibro** [golang/go#54572]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

The Host:
<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/yeji/Library/Caches/go-build"
GOENV="/Users/yeji/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/yeji/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/yeji/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/local/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/local/lib/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="/usr/bin/clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/yeji/git/go/src/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/c4/jp_cc5kj1cbc344rjv8rjngh0000gn/T/go-build2107651393=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>
The target is PowerMac G5 ppc64be running Linux

### What did you do?
<pre>
$ GOOS=linux GOARCH=ppc64 ./bootstrap.bash

</pre>

### What did you expect to see?
Go working on PowerPC 64 big endian

### What did you see instead?
<pre>
$ bin/go
Illegal instruction

$ strace bin/go
execve("bin/go", ["bin/go"], 0x3fffd0deead0 /* 25 vars */) = 0
--- SIGILL {si_signo=SIGILL, si_code=ILL_ILLOPC, si_addr=0x58924} ---
+++ killed by SIGILL +++
Illegal instruction

</pre>

**Comment by seankhliao** [comment]
See https://github.com/golang/go/wiki/MinimumRequirements#ppc64-big-endian
