### ISSUE TITLE
compiler: panics on un-implemented generic polymorphism

### ISSUE THREAD

**Issue by lucasavila00** [golang/go#54581]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/vscode/.cache/go-build"
GOENV="/home/vscode/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/workspaces/comp_to_go/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1895177786=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

https://go.dev/play/p/dSa7iLyypqq

### What did you expect to see?
A compile error.

### What did you see instead?
The compiler crashed.

**Comment by cuonglm** [comment]
I think it works correctly.

Your `Cat[A any]` implements the `Animal[A any]` interface, because it embeds `Animal[A]`. When you call `animal.is_cat()`, the `Animal[string]` field of your `Cat[string]` is nil, thus it raises an nil dereference.

**Comment by nojus297** [comment]
The compiler panics (fails to build) on 1.19, but compiles successfully on both 1.18 and tip.

**Comment by seankhliao** [comment]
Closing as fixed on tip

**Comment by cuonglm** [comment]
@nojus297 I think this dues to CL https://go-review.googlesource.com/c/go/+/414836/ and fix in https://go-review.googlesource.com/c/go/+/422274
