### ISSUE TITLE
runtime,cmd/compile: apparent memory corruption in compress/flate

### ISSUE THREAD

**Issue by bcmills** [golang/go#54596]
```
#!watchflakes
post <- pkg == "compress/flate" && `fatal error: found bad pointer in Go heap`
```

`greplogs -l -e \(\?ms\)runtime\\.throw.\*FAIL\\s+compress/flate --since=2021-10-09`
[2022-08-17T20:19:28-9c2b481/freebsd-amd64-12_3](https://build.golang.org/log/99d1bf55153f39e42741f60063cb2732398cf5e1)
[2022-08-17T03:15:44-e1b62ef/netbsd-arm64-bsiegert](https://build.golang.org/log/8e08296b3138a563d4ec56bda5a9dfa363d6d537)

A very similar failure mode was reported in #48846 and thought to have been fixed by @cherrymui.

(attn @golang/runtime)

**Comment by heschi** [comment]
[2022-08-26T17:48:20-296c40d/darwin-amd64-10_14](https://build.golang.org/log/4c7618e90e934e0158912f4fb949875d171bd521)

**Comment by cherrymui** [comment]
All three failures seem to have in common:
- the GC complains about a bad pointer pointing to an unallocated span, but the object hex dump shows the memory content is 0. In face, the entire object seems 0. I think this looks like there is something zeroing the object in concurrent with the GC.
- the object is in a span of size 663552 (0xa2000), which may be a `flate.Writer` which has size 656648 (0xa0508)

One possibility for the concurrent write of 0 is allocation. It may be that the GC scans the object when (or before) `mallocgc` zeroes it. For an object with that size, it is a large object and goes on this code path https://cs.opensource.google/go/go/+/master:src/runtime/malloc.go;l=1036

Why the GC sees the object before `mallocgc` returns? I don't really know. A conservative scan that happens to see a value coincide with the newly allocated pointer? That seems possible. `mallocgc` sets `span.freeindex` to 1 before zeroing the object or setting the heap bitmap. `scanConservative` (and `greyobject`) checks for `span.IsFree`, which in turn checks for `freeindex` https://cs.opensource.google/go/go/+/master:src/runtime/mgcmark.go;l=1431 . So it seems possible for `scanConservative` to pick up that object.

The span is from `mcache.allocLarge`, which calls `initHeapBits` https://cs.opensource.google/go/go/+/master:src/runtime/mcache.go;l=255
which, however, seems to set the heap bits only in certain cases -- noscan, or all pointers https://cs.opensource.google/go/go/+/master:src/runtime/mbitmap.go;l=735
For the case of a `flate.Writer`, it would be unset. I guess then the GC is possible to use an old heap bitmap to scan an object that isn't (fully) initialized? That seems bad.

In the third failure https://build.golang.org/log/4c7618e90e934e0158912f4fb949875d171bd521 it is complaining about the first word of the object. If the object is really a `flate.Writer`, the first word is not a pointer. This may indicate it is not using the right pointer bitmap, which the theory above would lead to.

In Go 1.19, where `heapBits.initSpan` always set the span's heap bits (to either all 0s or all pointers, never leave it unset), which seems to prevent this problem.

Maybe we should increment `span.freeindex` later, after zeroing the object and maybe setting the heap bits, so the GC won't see it, even for a conservative scan? This seems easy to do for large objects, but may be harder to do for small objects (without refactoring `nextFree` etc.).

I haven't reproduced the failure myself (didn't try very hard either). This is just a hypothesis. I may have missed something...

cc @mknyszek @randall77 @aclements

**Comment by mknyszek** [comment]
> A conservative scan that happens to see a value coincide with the newly allocated pointer?

One issue with this is while we're still in some runtime frame a conservative scan shouldn't happen. Asynchronous preemption backs out, I think.

But I agree with the rest of your thinking, i.e. the fact that it's a large object and that it seems like a pointer might somehow be getting published early (while freeindex is still unset). Either that, or there's a pointer into that space that was for some old object before the span was freed, and then materialized after the space for it had died (and it's just likely to land on the large object because it's large).

I think you're also onto something with the fact that the bitmap isn't cleared. Maybe there's yet-another place somewhere that we might hold onto a stale pointer that's otherwise safe because we _assume_ the bitmap is going to get cleared (this was the case with noscan objects and cgo not long ago)?

We can try always zeroing the bitmap (unfortunate...) and see if the problem still shows up. That's data, but it would take a while to be sure given how rare this is.

**Comment by cherrymui** [comment]
> One issue with this is while we're still in some runtime frame a conservative scan shouldn't happen. Asynchronous preemption backs out, I think.

Oh, I didn't mean conservatively scanning the runtime frame (sorry for being unclear). I think it is possible that a conservative scan of a (completely separate) user frame, on a different thread, happens to see a value (possibly a dead pointer) that is within the range of the newly allocated span.

That said, I don't really know that it was conservative scan. There might be other possibilities for a GC to see such pointer that I couldn't think of.

> We can try always zeroing the bitmap (unfortunate...) and see if the problem still shows up. That's data, but it would take a while to be sure given how rare this is.

I can try that. Last night I ran `stress flate.test -test.short` overnight on a gomote and saw 15 failures over 300000 runs. I can make the change and let it run for a day.

Among the failures the object hex dump are not always all 0. It could be that it is not (always) allocation. Or it may still be allocation, just that when it throws the allocating goroutine has already moved on, returned from mallocgc and started filling in the content.

> I think you're also onto something with the fact that the bitmap isn't cleared. Maybe there's yet-another place somewhere that we might hold onto a stale pointer that's otherwise safe because we assume the bitmap is going to get cleared (this was the case with noscan objects and cgo not long ago)?

Yeah, this is unfortunate. But I'm also not really sure how safe it is for the "all pointer" case. If the above is possible, I guess it is still possible for the GC to see the newly allocated but not yet zeroed pointer word? Just much harder as it is just one word?

**Comment by mknyszek** [comment]
> Oh, I didn't mean conservatively scanning the runtime frame

Ohhhhhhh, I see. That's a really good point. It didn't occur to me that pointers *could* in effect get "published" this way. We probably do need to be defensive about it, as you suggest.

**Comment by cherrymui** [comment]
With the CL above, before the gomote was killed by coordinator restart, I got
```
3h36m5s: 101279 runs so far, 0 failures
```
compared to previously
```
14h0m0s: 310600 runs so far, 15 failures (0.00%)
```
It seems positive that zeroing heap bitmap helps.

Independently I'm going to try if delaying incrementing `span.freeindex` makes any difference.

**Comment by cherrymui** [comment]
With CL 427619 (without CL 426834), it also doesn't fail running overnight. So delaying incrementing freeindex also seems to help.

As another data point, disabling async preemption (without either CL above) also seems to stop the failure.

I think these all support the hypothesis above, i.e. conservative scan, GC seeing the newly allocated object before zeroing, and heap bitmap not set.

**Comment by bcmills** [comment]
`greplogs -l -e \(\?ms\)runtime\\.throw.\*FAIL\\s+compress/flate --since=2022-08-18`
[2022-09-07T06:18:48-6375f50/freebsd-amd64-13_0](https://build.golang.org/log/6826f5d4e3c604a6435cef07dac76eb735f30a4a)
[2022-09-02T02:15:21-157aae6/windows-amd64-2008-newcc](https://build.golang.org/log/66f717095952b486739fec8191b5a86effa903ae)
[2022-08-29T20:21:48-2113fef/plan9-386-0intro](https://build.golang.org/log/f343e089d7c4e5fe726a2fe14ce7a72e509be74e)
[2022-08-26T17:48:20-296c40d/darwin-amd64-10_14](https://build.golang.org/log/4c7618e90e934e0158912f4fb949875d171bd521)
[2022-08-25T16:35:38-1df2a03/windows-amd64-2008-newcc](https://build.golang.org/log/8c1b176e338ae783ab1ee44f7fc37b30d5d75349)

**Comment by aclements** [comment]
Just hit on a trybot: https://storage.googleapis.com/go-build-log/65e11c86/windows-amd64-2016_3020f2c6.log

Marking release-blocker, since this can cause random crashes on any platform. It sounds like we have a pretty good hypothesis as to the cause. We should finish the fix and land it.

**Comment by cherrymui** [comment]
Yeah, I'm working on the fix. Hope to land soon-ish.

**Comment by cherrymui** [comment]
@aclements @mknyszek  CL 427619 and CL 449017 are two possible fixes. I stress-tested on gomotes and both runs 11+ hours, 300000+ runs with no failure, so both seem to fix the issue. Let me know which one do you think is better. Thanks.

(Probably still need some benchmarks to make sure the fast path performance doesn't regress. Will do.)

**Comment by mknyszek** [comment]
I accidentally clicked submit in the wrong Gerrit tab. I sent a revert: https://go-review.git.corp.google.com/c/go/+/449501.

**Comment by cherrymui** [comment]
@gopherbot please backport this to previous releases. This may cause (rare) GC crashes or memory corruptions. The large object case is new for Go 1.20, but it could still happen with small objects in previous releases. Thanks.

**Comment by cherrymui** [comment]
Well, gopherbot picks the "Go 1.20" from my previous comment and opens 1.20 backport, which is not what we want... I'll open 1.18 and 1.19 ones manually...

**Comment by cherrymui** [comment]
Failure is before the fix.
