### ISSUE TITLE
cmd/compile: k8s scalability load test failure (latency regression) with unified IR

### ISSUE THREAD

**Issue by mknyszek** [golang/go#54593]
Kubernetes runs a nightly load test built with Go tip. Recently there was a [regression in latency that caused various thresholds to be exceeded](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-golang-tip-k8s-1-23/1560444460821647360). 

(See the "gathering measurements step," though that on its own isn't very descriptive.)

The team has narrowed the culprit down to

```
833367e98a internal/buildcfg: enable unified IR by default
```

It's unclear at this time what the issue is. We're currently waiting on more metrics to investigate this more thoroughly.

CC @mdempsky

**Comment by mknyszek** [comment]
Assigning to myself for now to gather more information.

**Comment by mdempsky** [comment]
Just to confirm, this is an issue with run-time code being slower? Like it's not a problem with the compiler having slowed down too much?

One thing that comes to mind is inlining is somewhat (inlining cost analysis, because IR has changed; which function bodies are available to inline, because export data format has changed).

**Comment by mknyszek** [comment]
Nope, it's about code at runtime. Now that I'm looking at some of the graphs, it actually looks more like occasional stalls than a uniform slowdown, though I think there is some smaller uniform impact on tail latencies as well in between those stalls as well (unclear if they're related yet).

Here's what the API call latency looks like over time (note the threshold for the first graph is 1 second):

![image](https://user-images.githubusercontent.com/1248668/185990612-d6a69ab3-53e5-4fb1-9098-db1276eaa5e4.png)

And here's some GC-related statistics (note the breaks in the graphs that line up with the spikes):

![image](https://user-images.githubusercontent.com/1248668/185990808-b559f4b6-4e26-4aed-b2ef-ecd3388e42a0.png)

**Comment by mdempsky** [comment]
Kubernetes reports this is fixed since [6a801d3](https://github.com/golang/go/commit/6a801d3082c6ab28372c115d13ef0c238e3535ae).
