### ISSUE TITLE
crypto/internal/boring: found pointer to free object/found bad pointer in Go heap

### ISSUE THREAD

**Issue by rolandshoemaker** [golang/go#54604]
While running the Wycheproof test suite to debug #54558, I managed to trigger a `fatal error: found pointer to free object` and a `fatal error: found bad pointer in Go heap` panic. In particular this seemed to occur frequently when using `rsa.DecryptOAEP` (and the internal `boring.DecryptOAEP`), but I was able to trigger it elsewhere as well (i.e. `rsa.SignPKCS1v15` etc). Unfortunately after debugging this for a while the issue managed to magically disappear, and I have been unable to trigger it again.

Opening this issue in case a cause is obvious to anyone. I'll post traces if I'm able to trigger it again.

cc @rsc

**Comment by mknyszek** [comment]
@randall77 and I believe that this is probably fixed by https://go.dev/425194, so I'm just going to leave this in WaitingForInfo to see if it shows up again.

**Comment by mknyszek** [comment]
Since it's been a week and we're pretty sure this is fixed, I'm going to close it optimistically.
