### ISSUE TITLE
http/net/sniff gzip and fontobject type conflict

### ISSUE THREAD

**Issue by readerx** [golang/go#54614]
# The contents of my file are as follows:

![图片](https://user-images.githubusercontent.com/1893630/186103269-ea5013e2-43c4-4fbe-8568-dda1c2fd768c.png)

# The code of the problem is as follows:

code file: net/http/sniff.go

```go
	// Font types
	&maskedSig{
		// 34 NULL bytes followed by the string "LP"
		pat: []byte("\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00LP"),
		// 34 NULL bytes followed by \xF\xF
		mask: []byte("\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xFF\xFF"),
		ct:   "application/vnd.ms-fontobject",
	},
	&exactSig{[]byte("\x00\x01\x00\x00"), "font/ttf"},
	&exactSig{[]byte("OTTO"), "font/otf"},
	&exactSig{[]byte("ttcf"), "font/collection"},
	&exactSig{[]byte("wOFF"), "font/woff"},
	&exactSig{[]byte("wOF2"), "font/woff2"},

	// Archive types
	&exactSig{[]byte("\x1F\x8B\x08"), "application/x-gzip"},
```

# Test code is as follows:

![code](https://user-images.githubusercontent.com/1893630/186107065-0714c9ab-650a-4905-8d96-c129cda7f997.png)

# Operation results

![out](https://user-images.githubusercontent.com/1893630/186107011-f5f98eef-59bb-405e-ae6e-a0587660dc3c.png)

My file is `application/x-gzip` format, but it is parsed into `application/vnd.ms-fontobject` format.

**Comment by seankhliao** [comment]
net/http uses the sniffing algorithm defined here: https://mimesniff.spec.whatwg.org

It is unfortunate that it sometimes guesses wrong, but if you already know the content type, then you should set it directly.

**Comment by readerx** [comment]
So we accept this problem?

**Comment by readerx** [comment]
> net/http uses the sniffing algorithm defined here: https://mimesniff.spec.whatwg.org
> 
> It is unfortunate that it sometimes guesses wrong, but if you already know the content type, then you should set it directly.

So we accept this problem?

**Comment by seankhliao** [comment]
Unfortunate, but sniffing is best effort, and this is working as intended
