### ISSUE TITLE
proposal: Go 2: 

### ISSUE THREAD

**Issue by rahuldhirendersingh** [golang/go#54627]
### Author background

- **I'm a novice go programmer**
- **Html, CSS, Javascript, Java, Python**

### Related proposals

Code needs better **spacing** and **indentation** for better **readability**

**Comment by mvdan** [comment]
Please note that you should fill https://github.com/golang/proposal/blob/master/go2-language-changes.md when proposing a language change. I'm going to close this for now, as there's very little information here.
