### ISSUE TITLE
x/net: missing 'net' import breaks z/OS build

### ISSUE THREAD

**Issue by MacMalainey** [golang/go#54676]
A change was introduced in [this commit](https://github.com/golang/net/commit/46097bf591d3ad9985e32e2cac8857dc523f89e1) that breaks the build of `x/net/ipv6` (and any packages that end up depending on `golang.org/x/net/internal/socket`) on IBM z/OS.

The build error that occurs is when trying to build `x/net/ipv6`:
```
# golang.org/x/net/internal/socket
/home/macmala/go/pkg/mod/golang.org/x/net@v0.0.0-20220822230855-b0a4917ee28c/internal/socket/sys_zos_s390x.go:30:116: undefined: net
/home/macmala/go/pkg/mod/golang.org/x/net@v0.0.0-20220822230855-b0a4917ee28c/internal/socket/sys_zos_s390x.go:53:58: undefined: net
```

**Cause:**
The `net` package is used but not imported in the file `internal/socket/sys_zos_s390x.go`.

**Verification:**
When the `net` package is added as an import the package `golang.org/x/net/internal/socket` builds and all tests pass on IBM z/OS.

**Requested action:**
Add the `net` package as an import in the file `internal/socket/sys_zos_s390x.go`

**Comment by ianlancetaylor** [comment]
Sorry about that.  Sent https://go.dev/cl/425534.
