### ISSUE TITLE
x/pkgsite@latest doesn't install

### ISSUE THREAD

**Issue by Yan3y** [golang/go#54672]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.4 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
I am not clear about that,because my golang version must be consistent with the team.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/yaney/Library/Caches/go-build"
GOENV="/Users/yaney/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/yaney/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/yaney/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.18.4"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/t0/5dc5xbgs6qg__wghsr84hrym0000gn/T/go-build698603497=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
- install pkgsite
<details><summary><code>go install golang.org/x/pkgsite/cmd/pkgsite@latest</code> Output</summary><br><pre>
go: downloading golang.org/x/pkgsite v0.0.0-20220824165620-386289514eef
go: downloading golang.org/x/sync v0.0.0-20220722155255-886fb9371eb4
go: downloading golang.org/x/vuln v0.0.0-20220823182523-5ae4b706aeb8
../pkg/mod/golang.org/x/pkgsite@v0.0.0-20220824165620-386289514eef/internal/godoc/dochtml/internal/render/linkify.go:13:2: package go/doc/comment is not in GOROOT (/usr/local/go/src/go/doc/comment)
</pre></details>

- I check the issue ,https://github.com/golang/go/issues/51185#issue-1137062751 said the version of golang requires Go 1.18 ,but the version of mine is 1.18.4

- I checked the error found that may be some files are missing,And then  ls the directory,found the comment is missing
<details><summary><code>ls /usr/local/go/src/go/doc/</code> Output</summary><br><pre>
Makefile         comment_test.go  doc_test.go      example_test.go  filter.go        reader.go        synopsis_test.go
comment.go       doc.go           example.go       exports.go       headscan.go      synopsis.go      testdata
</pre></details>

- last,I download the source of code ——go1.18.5.darwin-arm64.tar.gz from [https://go.dev/dl/](https://go.dev/dl/)，There is no the same file here.
Is there any other way?

Yaney
Thanks！

### What did you expect to see?
Install pkgsite successfully

**Comment by seankhliao** [comment]
https://github.com/golang/pkgsite#requirements
