### ISSUE TITLE
x/pkgsite: multiple licenses not showing documentation

### ISSUE THREAD

**Issue by wxolp** [golang/go#54683]
### What is the URL of the page with the issue?

- https://pkg.go.dev/github.com/89z/hello@v1.0.3
- https://pkg.go.dev/github.com/89z/hello@v1.0.2

### What is your user agent?

Mozilla Firefox

### Screenshot

https://pkg.go.dev

### What did you do?

Visit the pages

### What did you expect to see?

Documentation

### What did you see instead?

> Documentation not displayed due to license restrictions

"X" next to "Redistributable license". Both licenses are redistributable:

- https://creativecommons.org/licenses/by-nc/4.0/legalcode#s2a1
- https://polyformproject.org/licenses/noncommercial/1.0.0#distribution-license

**Comment by wxolp** [comment]
here are some large repos:

stars  | URL
-------|----
14,083 | https://github.com/inancgumus/learngo/blob/master/LICENSE
7,111  | https://github.com/teh-cmc/go-internals/blob/master/LICENSE
2,693  | https://github.com/ashleymcnamara/gophers/blob/master/LICENSE
2,591  | https://github.com/mikespook/Learning-Go-zh-cn/blob/master/LICENSE
1,793  | https://github.com/sensepost/ruler/blob/master/LICENSE

**Comment by seankhliao** [comment]
Non-commercial places significant restrictions on what you can do

https://creativecommons.org/faq/#does-my-use-violate-the-noncommercial-clause-of-the-licenses

> Please note that CC’s definition does not turn on the type of user: if you are a nonprofit or charitable organization, your use of an NC-licensed work could still run afoul of the NC restriction, and if you are a for-profit entity, your use of an NC-licensed work does not necessarily mean you have violated the term. Whether a use is commercial will depend on the specifics of the situation and the intentions of the user.

**Comment by wxolp** [comment]
@seankhliao I don't understand. Why does the fact that you personally dislike the license, mean that any module using that license is blocked from using https://pkg.go.dev?

**Comment by seankhliao** [comment]
In the context of pkg.go.dev, the requirement is (from the tooltip):

> Redistributable licenses place minimal restrictions on how software can be used, modified, and redistributed.

**Comment by wxolp** [comment]
@seankhliao both licenses are redistributable. I mentioned that in the original issue text, but here it is again:

- https://creativecommons.org/licenses/by-nc/4.0/legalcode#s2a1
- https://polyformproject.org/licenses/noncommercial/1.0.0#distribution-license

**Comment by seankhliao** [comment]
> for NonCommercial purposes only

conflicts with

> place minimal restrictions

**Comment by wxolp** [comment]
https://github.com/github/choosealicense.com/issues/1015
