### ISSUE TITLE
x/net: incorrect sync.Pool usage leads to EINVAL errors on WriteBatch (sendmmsg)

### ISSUE THREAD

**Issue by marten-seemann** [golang/go#54693]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19 linux/arm64
</pre>

with a current version of `x/net`:
```
require golang.org/x/net v0.0.0-20220822230855-b0a4917ee28c
```

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/home/parallels/.cache/go-build"
GOENV="/home/parallels/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/parallels/src/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/parallels/src/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/parallels/bin/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/parallels/bin/go/pkg/tool/linux_arm64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/parallels/src/go/src/github.com/lucas-clemente/quic-go/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1105120780=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I'm adding support for `WriteBatch` to [quic-go](https://github.com/lucas-clemente/quic-go). Batching writes of QUIC (UDP) packets leads to a significant speedup of QUIC throughput, due to the reduced number of syscalls. Some connections set OOB, others don't, therefore the `OOB` field in the [`ipv{4,6}.Message`](https://pkg.go.dev/golang.org/x/net/ipv4#Message) will sometimes be set, other times it won't.

### What did you expect to see?

I expect calls to `WriteBatch` to succeed. 

### What did you see instead?

Calls to `WriteBatch` occasionally return a `sendmmsg: invalid argument` error. I wrote a minimal example that reproduces the bug (even in the Go Playground): https://go.dev/play/p/lALtpTKEgw5

### Why does this happen?

A `sync.Pool` is used to avoid allocations of the `msghdr` struct: https://cs.opensource.google/go/x/net/+/b0a4917e:internal/socket/rawconn_mmsg.go;l=39-40.
When the pool returns a `msghdr` where the `Control` and `Controllen` is set (this happens if the previous user of the struct set OOB), it is not properly cleared if no OOB is set: https://cs.opensource.google/go/x/net/+/b0a4917e:internal/socket/msghdr_linux.go;l=14-16.

This leads to `Control` pointing to a memory location that might have already been reused between the two invocations. The kernel will thus see an invalid `mmsghdr` passed to the `sendmmsg`, and (rightfully) return an `EINVAL` error.

Update: Here's a fix: https://go-review.googlesource.com/c/net/+/425914.

**Comment by heschi** [comment]
cc @neild @ianlancetaylor
