### ISSUE TITLE
affected/package: reflect and unsafe together occur random errors

### ISSUE THREAD

**Issue by hzmsrv** [golang/go#54702]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.183
</pre>

### What operating system and processor architecture are you using (`go env`)?
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz

### What did you do?

```
func UnsafeOutputAnyParameter() any {
	type eface struct {
		typ, val unsafe.Pointer
	}

	fn := func(arg any) {
		var val any = 123

                //*********************** delete those codes will both run perfect
		t := reflect.TypeOf(arg)
		tt := reflect.TypeOf(val)
		
		if t.Elem().String() != tt.String() {
			panic("could not convert differnt type!")
		}
                //***********************

		dst := (*eface)(unsafe.Pointer(&arg))
		src := (*eface)(unsafe.Pointer(&val))

                // NOTE: delete Println will occur more random errors
		fmt.Println(*(*eface)(dst.val), *(*eface)(src.val)) //<===== output show arg not nil
		*(*eface)(dst.val) = *(*eface)(src.val)
	}

	var i int

	fn(&i)
	return i
}

func BenchmarkUnsafeOutputAnyParameter(b *testing.B) {
	for n := 0; n < b.N; n++ {
		fmt.Println("Output:", UnsafeOutputAnyParameter())
	}
}
func TestUnsafeOutputAnyParameter(t *testing.T) {
	for n := 0; n < 100; n++ {
		fmt.Println("Output:", UnsafeOutputAnyParameter())
	}
}
```

### What did you expect to see?
**Benchmark & Test run ok**

### What did you see instead?
**Benchmark  run with errors
Test run ok**

**Comment by randall77** [comment]
Modifying interfaces by overwriting parts of their internal fields is not supported.
You're likely tripping up on some escape analysis, or perhaps differences in how `*int` and `int` are represented in interfaces.

In short, don't do that. Or barring that, using `unsafe` in this way means it's on you to figure out what is going wrong.

**Comment by hzmsrv** [comment]
that is why I sent it here because I can not locate its problems!  just like changed which i only add the one line code to call Println

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
