### ISSUE TITLE
context: should panic at WithValue but not

### ISSUE THREAD

**Issue by cuiweixie** [golang/go#54708]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version devel go1.20-18e01e9436 Sat Aug 27 15:34:47 2022 +0800 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
darwin/arm64
</pre></details>

### What did you do?
```
package main

import (
	"context"
	"reflect"
)

func main() {
	ctx := context.Background()
	var key interface{} = [1]interface{}{[]int{1}}
	e := reflect.ValueOf(&key).Elem()
	key = e.Interface()
	ctx = context.WithValue(ctx, key, 1)
	val := ctx.Value(key)
	println(val)
}

```

### What did you expect to see?

panic at line 13 when call WithValue

### What did you see instead?

panic at line 14 when call ctx.Value(key)

**Comment by cuonglm** [comment]
I'm not sure we should, this change will break user program that set context value with comparable key type, but non-comparable key value (like your example), but never call `ctx.Value` to get the value.

Also, the `context.WithValue` doc is also not so clear, it said:

> The provided key must be comparable and should not be of type string or any other built-in type to avoid collisions between packages using context.

Not specify `key type` or `key value`.

PS: next time, you should wait for discussing in the issue before sending a CL.

**Comment by cuiweixie** [comment]
i think checking value is comparable is better

**Comment by Mgrdich** [comment]
why the inside the `WithValue`
we are checking it like this , instead of making this with generics ?

```
 if !reflectlite.TypeOf(key).Comparable() {
		panic("key is not comparable")
}
```

if we can make type value as `comparable`  in the function params ?

`func WithValue[T comparable](parent context.Context, key T, val any) context.Context {`

**Comment by ianlancetaylor** [comment]
The `WithValue` function was added to the API before generics were added to the language.  Changing the signature of `WithValue` now would break the Go 1 compatibility guarantee.
