### ISSUE TITLE
x/pkgsite:  Error in metadata informations about an package

### ISSUE THREAD

**Issue by victorfernandesraton** [golang/go#54704]
### What is the URL of the page with the issue?
https://pkg.go.dev/github.com/victorfernandesraton/cepgo@v0.0.0-20220824053107-8c8c6f237032

### What is your user agent?
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36

### Screenshot

[<image src="https://drive.google.com/file/d/1kXhoLkyODeycxd8goOGsvw0BanMpe5FJ/view?usp=sharing"/>](https://drive.google.com/file/d/1kXhoLkyODeycxd8goOGsvw0BanMpe5FJ/view?usp=sharing)

### What did you do?
I recently update my lib in github, but go. pkg metadata has not been info about version and other things after I update

### What did you expect to see?
I should be seen the info about the package and I need use semantic versioning

### What did you see instead?
I see my package with v0.0.0 and not been change

**Comment by seankhliao** [comment]
patience, it's there
