### ISSUE TITLE
x/crypto/ssh: invalid packet length, packet too large

### ISSUE THREAD

**Issue by marklaptenok** [golang/go#54719]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.5 freebsd/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="freebsd"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="freebsd"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go118"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go118/pkg/tool/freebsd_amd64"
GOVCS=""
GOVERSION="go1.18.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="cc"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/root/deployer/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2722818596=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

```
func send(private_key_path string, ftp_server_address_port string, ftp_user string) {
        key, error := os.ReadFile(private_key_path)
	if error != nil {
		logger.Fatalf("Can't open the private key to connect to runtime environment: %s", error.Error())
	}

	signer, error := ssh.ParsePrivateKeyWithPassphrase(key, []byte(ftp_user))
	if error != nil {
		logger.Fatalf("Can't parse the private key to connect to runtime environment: %s", error.Error())
	}

	ssh_configuration := &ssh.ClientConfig{
		User: ftp_user,
		Auth: []ssh.AuthMethod{
			ssh.PublicKeys(signer),
		},
		HostKeyCallback: ssh.InsecureIgnoreHostKey(),
		Timeout:         0,
		ClientVersion:   "Deployer",
	}

	ssh_connection, error := ssh.Dial("tcp", ftp_server_address_port, ssh_configuration)
	if error != nil {
		logger.Fatalf("Can't connect to %s as %s: %s", ftp_server_address_port, ftp_user, error.Error())
	}
	defer ssh_connection.Close()

	logger.Printf("Connected to %s as %s", ftp_server_address_port, ftp_user)

         // ...
}
```

### What did you expect to see?

"Connected to 10.0.3.15:22 as test_env"

### What did you see instead?

"Can't connect to 10.0.3.15:22 as test_env: ssh: handshake failed: ssh: invalid packet length, packet too large"

**Comment by seankhliao** [comment]
golang.org/x/crypto/ssh version?
sshd version?
sshd config?

without information on how to reproduce this report isn't very actionable

**Comment by marklaptenok** [comment]
Hi @seankhliao, when the research will start? When could I estimate to have some results on the incident?

**Comment by 5hir0kur0** [comment]
Hi @marklaptenok 

I had the same problem and found this issue through a Google search. In my case, I could fix it by setting the `ClientVersion` (in the `ssh.ClientConfig` struct) to a string starting with `SSH-2.0-`.
Maybe you could try that as well. You can also just omit the `ClientVersion` in which case the default value of `"SSH-2.0-Go"` will be used.
Hope this helps.

**Comment by marklaptenok** [comment]
Hi @5hir0kur0 ,

thank you for a workaround. It works for me.

**Comment by akmistry** [comment]
It's not a workaround, it's a requirement of the SSH protocol. The server config has this comment:
```
// Note that [RFC 4253 section 4.2](https://rfc-editor.org/rfc/rfc4253.html#section-4.2) requires that this string start with
// "SSH-2.0-".
```

This comment should probably be added to ClientConfig.ClientVersion too.

**Comment by marklaptenok** [comment]
> It's not a workaround, it's a requirement of the SSH protocol. The server config has this comment:
> 
> ```
> // Note that [RFC 4253 section 4.2](https://rfc-editor.org/rfc/rfc4253.html#section-4.2) requires that this string start with
> // "SSH-2.0-".
> ```
> 
> This comment should probably be added to ClientConfig.ClientVersion too.

Thank you for your remark. I have not known this.
