### ISSUE TITLE
cmd/go: `cannot find package` when importing dependencies with the `unix` build constraint

### ISSUE THREAD

**Issue by WIZARDISHUNGRY** [golang/go#54712]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
I don't know if this reproduces in gotip.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/tmp/go-build-jon"
GOENV="/home/jon/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/jon/.asdf/installs/golang/1.19/packages/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jon/.asdf/installs/golang/1.19/packages"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/jon/.asdf/installs/golang/1.19/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/jon/.asdf/installs/golang/1.19/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/jon/src/tmp/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2789217673=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
https://go.dev/play/p/vhnTI8FhFJE
Doesn't reproduce in the playground.
### What did you expect to see?
My program runs. 

### What did you see instead?
main.go:6:2: cannot find package

If I change `unix` to `linux`, it works.
If I remove the build constraint, it works.
If I remove the references to `golang.org/x/sync/singleflight`, it works.

Per `go help buildconstraint`:
> During a particular build, the following build tags are satisfied:
>
>        - the target operating system, as spelled by runtime.GOOS, set with the
>          GOOS environment variable.
>        - the target architecture, as spelled by runtime.GOARCH, set with the
>          GOARCH environment variable.
>        - "unix", if GOOS is a Unix or Unix-like system.

**Comment by ZekeLu** [comment]
It seems that https://go.dev/cl/389934 forgot to change `src/cmd/go/internal/imports/build.go`, which is copied from `src/go/build/build.go`, `src/go/build/syslist.go`. I have sent https://go.dev/cl/426296 to change that file and add a regression test.

**Comment by bcmills** [comment]
> Doesn't reproduce in the playground.

It does if you add a `go.mod` file with an explicit dependency and a recent `go` version! 🙂

https://go.dev/play/p/A9PbFemDPD-?v=gotip

**Comment by bcmills** [comment]
@gopherbot, please backport to Go 1.19. This is a subtle bug in a feature introduced in Go 1.19, and the fix in Go 1.20 will mask spurious build failures that users on Go 1.19 will run into.
