### ISSUE TITLE
x/playground: commands fail when a multi-file playground program uses workspace mode

### ISSUE THREAD

**Issue by bcmills** [golang/go#54741]
### What did you do?

https://go.dev/play/p/gJxLs807WTz

### What did you expect to see?

Go commands executed in workspace mode.
(In this case, I was trying to reproduce #54680.)

### What did you see instead?

```
go: -mod may only be set to readonly when in workspace mode, but it is set to "mod"
	Remove the -mod flag to use the default readonly value,
	or set GOWORK=off to disable workspace mode.

Go build failed.
```

**Comment by bcmills** [comment]
(attn @toothrot per https://dev.golang.org/owners)

**Comment by nikola-jokic** [comment]
Can I take this one?

**Comment by bcmills** [comment]
@toothrot, the Gerrit login for your `golang.org` account seems to no longer be working. Do you plan to continue reviewing https://go.dev/cl/458895, or should I complete the review or reassign it?
