### ISSUE TITLE
cmd/compile: internal compiler error: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by kralicky** [golang/go#54746]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/joe/.cache/go-build"
GOENV="/home/joe/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/joe/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/joe/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/joe/sdk/go1.19"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/joe/sdk/go1.19/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/joe/tmp/go-ice/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1648616691=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

The following program will trigger the ICE:

https://go.dev/play/p/1MeZY9-tOtp
```
package main

type Interface interface {
	Method() Interface
}
type Struct struct{}

func (x *Struct) Method() Interface {
	return nil
}
func clone(m Interface) Interface {
	return nil
}
func Clone[T Interface](msg T) T {
	return clone(msg).(T)
}
func (in *Struct) Foo() *Struct {
	return Clone(in)
}
func main() {
}
```

### What did you expect to see?

No error

### What did you see instead?

```
<autogenerated>:1: internal compiler error: panic: runtime error: invalid memory address or nil pointer dereference

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new
```

**Comment by cuonglm** [comment]
Seems duplicated of https://github.com/golang/go/issues/54302

**Comment by cuonglm** [comment]
Confirm that 0c4db1e347dc51589e5289388305b02108ca0aa1 fixed this, so it's duplicated of https://github.com/golang/go/issues/54302
