### ISSUE TITLE
cmd/compile: missing BCE in range expression

### ISSUE THREAD

**Issue by tamird** [golang/go#54753]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.19
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
Linux amd64
</pre></details>

### What did you do?

```
package main

type foo struct {
    number int
}

var foos []foo

func main() {
    foos = make([]foo, 5)
    for i := range foos {
        _ = &foos[i] // No IsInBounds
    }
    for i := range foos {
        f := &foos[i] // IsInBounds
        f.number = i
    }
    for i := 0; i < len(foos); i++ {
        f := &foos[i] // No IsInBounds
        f.number = i
    }
    foos2 := make([]foo, 5)
    for i := range foos2 {
        f := &foos2[i] // No IsInBounds
        f.number = i
    }
}
```
[compiler output visible on godbolt](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DBUpJfWQE8Ayo3QBhVLQCuLBnrsAZPA0wA5VwAjTGIQACYADlIAB1QFQmsGRxc3PVj4qwFvXwCWYNDIs0wLTIYhAiZiAmTXdy4iksTyyoJs/yCQvQUKqprU%2Bu6Wttz8iQBKM1RnYmR2DmimZABrJmBMAGoWJh8AUg0AQT39ggBPaI3%2BVHXu4mdLdZ2AdgAhI/X39YYO4nWfAiOngARAEHABulXWlwUDwArK8YYDLiD9lRnAxkJttgwIGMHi83h8oQ8AMyAzFLTAQHZw6mI1CmdYwsYE978H54dYgHak9bEQxrSH06FPV4HD7i9YAfRJZJ2YQAbFDqc88LT1gB6dXrPxXACSCl1DGeUwY6AULLxwLFhJIv053LJfKMFyFeNF%2BwlhPtPLliqFytVCI1Wv1huNaLNFvFVAAdF88iEZb8LUCLWy7VyeRpuc87dz7Ot6NioczibnVWFXpW3VGvZnZQqlXDA2TNdq9QajSbI9bPbH4/kk6re5a00Kwt6yVsKVSaQjLqRGcyR%2BmOfXefyXXEJyLa6zJw9G%2BOA2q2zr1qGuxHzSPo3HvkOU48rYdn0cOBNaJwYbx3BwtKQqCcAA4lcChTDMGxysSPCkAQmgfhMSwgMSEQxgqACcEQaFwqEwhEjyRBh%2BicJIv4IYBnC8AoIAaHBCETHAsAwIgKCoCw0R0CE5CUGgHFcaEwC0FwXAYXRNC0AQIQ0RAgQUYEPiVCcnCwXxbCCAA8gwtDKf%2BvBYFsRjiHppD4MQmCWHgoKYDRJmYKoFnOFJKm8H8xQUbQeCBHyxAnI4WAUQQxB4CwLkTFQBjAAoABqeCYAA7hp5x/rB/CCCIYjsFIMiCIoKjqCZuj1AYRggCY%2BheTRkATKg0SlLZAC06AOgoChMOqyAIBZSySoEszqlggTOMADqweYFmlLYpp9HUpBeD47QJqE9TpAkAgzWkcRrQwwzfF0xQTU0PTVE4tT7Y0AjNFUu1LV0x0bQMx03aMXATOB0yzHoQWYHMPCft%2B5EmUBHCsOg8qSOswAYlwMaiesECgYuuCELa0H1Osjj8fQPxo2MvDwXpYwTF1TBYKEOKkMhxIwjGMEwo8jzyhoGGRJIXA4SRHBkaQoUwnRf4AcD1G0fRhOkExrFTAQ0ROTxECYPgRDBegehpcIojiOzOXyEoagUUVpDxXy0RhZzP6kALvDAxpTkywQ6yoFQ6yg%2BDkPQ7DGHw5jnHY4eMF46LWhE6QJNk5Q/1c7wvP8xRQtmCLBNB0hKFhLDEQwhh8qoVwEQRBhkhhMSnPEoDgtUYHH7iyxEsQEgfE%2B9xFAQPXAllcJoniXQUnEDJckmQpzC%2BS5pBqYwBBaTpFEGfyxkAWZh3WbZAH2Y5zncK5gjuevFXeUp/m/fjwWhWLEWrDFcWJclw9qxlmvSGreV64V4T6PyZWmJ5gRVRTtX1eX42WRsPLaap1%2BhzVNM9ToK0tqlAejEGBiRIHLQaIdS691QGzQAaUK6rQFojCgWYdBKRMFPTwXtV6kwPpZTguZA%2BEdzaW0oiDFgYMIZQ3WDDOGCMGTIyVn7dG3sBJ%2BzCAHROiFKYpxjBEeUMIC7ylzlIGE8p5Sc25tHGM%2BENCPAiFIKQGF86EQtrHf%2BCcGJV3gLXEAUs7ZywVijZWqtZC3yyuJWQj8CoAV0GEQ2xtTZfg4Aw4xHAbbSycg7J2Ls2Huy4YI320ERH4wYhHNRIBJAYRjGzFmOd8J8w0DCMIjwjFAxMXRMRwdkJhHSbIguxJJCPAwvk4kRFvH%2BJLkUsuHBEmEwjmEUuVty5lImNZHuiRUlAA%3D%3D)

### What did you expect to see?

No bounds checks.

### What did you see instead?

Bounds check when ranging over a variable declared and initialized separately.

**Comment by heschi** [comment]
cc @golang/runtime

**Comment by randall77** [comment]
I'm going to close this, as I don't think there's anything to do here. We could improve the compiler to change its CSE rule  from "any write might be synchronization" to something more complicated, but that's a really big lift for an issue that's pretty easy to work around.
