### ISSUE TITLE
cmd/compile: missing BCE when index is modulo len

### ISSUE THREAD

**Issue by tamird** [golang/go#54755]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.19
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
Linux amd64
</pre></details>

### What did you do?

```
package main

type foo struct {
	number int
}

var foos []foo

func init() {
	foos = make([]foo, 3)
}

func getFoo(n int) *foo {
	foos[len(foos)-1] = foo{} // IsInBounds
	if len(foos) != 0 {
		foos[len(foos)-1] = foo{} // No IsInBounds
		return &foos[n%len(foos)] // IsInBounds
	}
	return nil
}

func main() {

}
```

[compiler output visible on godbolt](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DBUpJfWQE8Ayo3QBhVLQCuLBiADMpOwBk8DTAA5VwAjTGIJAA5SAAdUBUJrBkcXN09Y%2BMSBPwDgljCIrmjzTEskoQImYgIU13cvErKBCqqCHKDQ8KizSuratIbetv8O/K6igEozVGdiZHYOGKZkAGsmYEwAahYmfwBSDQBBA8OCAE8Yrf5UTYUCYmdLTb2AdgAhE4OATgZO4k3/ARPi8ACKfI4ANyqm2uCmeAFYPvCQddwYcqM4GMgAQxCBAJs93uCvrDnh4QdsmCtMBA9oi6SjUKZNh4JsCwUcThisZsNgQAGJMiAMHEEAkAKmuhI%2BnI0JKZCjpb3oDGoComAFouAyyRTUUTQZsAPRGzYASQUZoYbxmDHQitlXzwVE2KrV8QJYDAe3Jmw00uJ31hSrdsM12uRuphTNeH0NJs2gRuFqtNsx9sDcuImAIsxFewATAA2YOIhiF%2BGh9U6hMp622jOO14c45ZnN5za42jstHc7E7fz4gOy46gk4cKa0Tjw3juDhaUioTgAcRuChmcy2hY8PFIBE0E6mK08kQAdMWvpENFwPJF4ZEXgXIl99JxJLOD4vOLwFCANHuDymOBYBgRAUFQFgYjocJyEoNBIOgiJgFoLguC%2Bf8aFoAhwl/CAQk/EJ/CqM5OF3eC2EEAB5BhaBI%2BdeCwHYjHEejSHwbMyghTBf1YzBVFKZxsNI3hAUwKdWNoPAQmIYjHCwT97jwFhhKmKgDGABQADU8EwAB3SjLjnXd%2BEEEQxHYKQZEERQVHUVjdC4fRDGMUxJJCX9ICmVAYisAQeI1dAfRBBQFCYI1kAQUoVgAfRCeYjSwEJnGAILd0aXz3AgOx%2BncRzfBGPICj0OIEgynLisyDL2kK8YzDE0oMpaPonDqPR0vKIZqr%2BNqhnKxy7laLqxkKKZ11meY9HuTAFh4Sdpw/Vilw4Vh0CLSReWxLhTzQzYIFXUhNlwQgSGeAsdwOxwEPof5ty4CZeH3eiJimSKmCwCJ8VIY8PHhU8d3hF4XiLOUn0kLhr1fDh31IZT4X/OcFyWn8/wAp7SGAsCZgIGJBNgrL8CIYg8HQPQTOEURxHBqz5CUNRPwc0hdJkmIVMhmdSAR3glsowScYITZUBdFa1o2zYtp2iBLqg67Tp3e7Ua0Z7SFe97KDmqHeFh%2BHPyRswUcexWj08AttrvL4i1vIpn0kM7IY8BbEe/BWJ3R0CMYgJB4OlmCKAgL3EJAZDUPQvg6Gw4hcPw1jCOYYg6LIiCKIIajaM/RjnJYhd2IavAuJ4hc%2BIEoTuBEwQxOE/QpJkuO5Jmh6ieUtG1PWLSdP0wyK7JszKekMmbLp%2ByQALJyjED1ypI8z7vIynif3qppMuylq0jyu0hqKxySqyZJl9yjJSqSdfava5pet3tr58azqCu6/qz9SPeBuqI%2BRumcaLL3bM6/V9nOa/ZaWCrXWsATa20vi7X2odAmJ1boXQgt7G6Z0CzywNoeL6xtTyRCLPCG2RZIiRCkPCIsRZIbQy1qee8GgXgELBpIL4XxJCPg5jrJ2v5/yoKAm7JAWM%2BZ40wNAomJNHJdwphZDCsh%2B52QXLoYeTMmAsxLj/B2XNOA82xoJAWQtAEixAWLMBu0paIVlsgh6gF1ZkJAHQ08YMvgFiKPeOGGh4QFheMwxarD9ZmPQQWL4FDJA2w8Iwr4ziPBPlsXbZR/9TFPXVgWSJusOFTC4hHJIligA%3D%3D)

### What did you expect to see?

No bounds checks.

### What did you see instead?

Bounds check.

**Comment by heschi** [comment]
cc @golang/runtime

**Comment by randall77** [comment]
`i%len(a)` is not necessarily in bounds of `a` if `i` is negative.

**Comment by tamird** [comment]
Good point; casting to uint removes the bounds check.
