### ISSUE TITLE
cmd/go: TestScript/build_overlay broken when `gccgo` is present as of CL 421879

### ISSUE THREAD

**Issue by bcmills** [golang/go#54761]
https://go.dev/cl/421879 caused `go build --compiler=gccgo` to fail when the installed `gccgo` predates the `runtime/cgo` changes in that CL.

I'm not sure what exactly, if anything, we should do about that, since we can't in general make assumptions about which `gccgo` the user may have installed.

@ianlancetaylor, @cuonglm: any suggestions? (For now I'm going to disable that part of the test.)

**Comment by ianlancetaylor** [comment]
For the record, while I haven't looked at this specific issue yet, the general goal is for cmd/go to test what gccgo features are supported, and use those.

**Comment by bcmills** [comment]
That makes sense. Perhaps at some point after https://go.dev/cl/420054 lands we should add a script condition for `gccgo` features in script tests?
