### ISSUE TITLE
wrong key, iv pbkdf2 package 

### ISSUE THREAD

**Issue by m-abdalrahman** [golang/go#54769]
### What version of Go are you using (`go version`)?

<pre>
go version go1.19 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2899816848=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
I have file encoded by aes-256-cfb, when I use openssl command
`openssl enc -d -aes-256-cfb -salt -pbkdf2 -pass file:pass_clear -in pkg_digest -out file.txz
`
this file is decrypted without any problem,but when I try to decrypt this file by golang, I always get incorrect file.
code:

```
package main

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/sha256"
	"fmt"
	"log"
	"os"

	"golang.org/x/crypto/pbkdf2"
)

func main() {
	fiencpkg, err := os.ReadFile("pkg_digest")
	if err != nil {
		log.Println(err)
		os.Exit(1)
	}

	salt := fiencpkg[8:16]
	fmt.Printf("salt:%x\n", salt)
	ciphertext := fiencpkg[16:]

	fiencpass, err := os.ReadFile("pass_clear")
	if err != nil {
		log.Println(err)
		os.Exit(1)
	}

	keyIv := pbkdf2.Key(fiencpass, salt, 10000, 48, sha256.New)
	key := keyIv[:32]
	iv := keyIv[32:48]
	fmt.Printf("keyIv:%x\n", keyIv)
	fmt.Printf("key:%x\n", key)
	fmt.Printf("iv:%x\n", iv)

	block, err := aes.NewCipher(key)
	if err != nil {
		panic(err)
	}

	stream := cipher.NewCFBDecrypter(block, iv)
	stream.XORKeyStream(ciphertext, ciphertext)
	os.WriteFile("go.txz", ciphertext, 0777)
}
```

**Note:** when I use  `openssl enc -d -aes-256-cfb -salt -pbkdf2 -pass file:pass_clear -in pkg_digest -out x.txz -P
` to get key and iv, it's different from pbkdf2.Key keyIv

**Comment by ZekeLu** [comment]
It's most likely that `pass_clear` contains new lines. Try to trim the white spaces.

This works for me:

```go
package main

import (
	"bytes"
	"crypto/aes"
	"crypto/cipher"
	"crypto/sha256"
	"log"
	"os"

	"golang.org/x/crypto/pbkdf2"
)

func main() {
	fiencpkg, err := os.ReadFile("pkg_digest")
	if err != nil {
		log.Fatalln(err)
	}

	salt := fiencpkg[8:16]
	log.Printf("salt:%X\n", salt)
	ciphertext := fiencpkg[16:]

	fiencpass, err := os.ReadFile("pass_clear")
	if err != nil {
		log.Fatalln(err)
	}
	fiencpass = bytes.TrimSpace(fiencpass)
	log.Printf("pass: %q", fiencpass)

	keyIv := pbkdf2.Key(fiencpass, salt, 10000, 48, sha256.New)
	key := keyIv[:32]
	iv := keyIv[32:48]
	log.Printf("key:%X\n", key)
	log.Printf("iv:%X\n", iv)

	block, err := aes.NewCipher(key)
	if err != nil {
		panic(err)
	}

	stream := cipher.NewCFBDecrypter(block, iv)
	stream.XORKeyStream(ciphertext, ciphertext)
	log.Printf("%q", ciphertext)
}
```

Test:

```shell
$ echo 'pa$$w0rd' > pass_clear
$ echo 'hello world!' > plain.txt
$ openssl enc -e -aes-256-cfb -salt -p -pbkdf2 -pass file:pass_clear -in plain.txt -out pkg_digest
salt=1B7CA9092FF2138B
key=0784DFB7D8596C17A82CB7548021B6053FE57EF6683F91F7EFAD6D2381DCDD3B
iv =8B12AD0CC0D44D9D1A91744BFAFCA89C
$ go run main.go
2022/08/30 21:50:13 salt:1B7CA9092FF2138B
2022/08/30 21:50:13 pass: "pa$$w0rd"
2022/08/30 21:50:13 key:0784DFB7D8596C17A82CB7548021B6053FE57EF6683F91F7EFAD6D2381DCDD3B
2022/08/30 21:50:13 iv:8B12AD0CC0D44D9D1A91744BFAFCA89C
2022/08/30 21:50:13 "hello world!\n"
```

**Comment by m-abdalrahman** [comment]
@ZekeLu same problem output pass:

`pass: "\xbd\xaeU\xb8\\P\x02~a\xfa\x14o7g\xbbԑ/\xfd-WF:\xec\x10)\a\xb4\x17;\xb2hC\x94S\xaf'\xe5^\x04,\xb8\xd8\xe3\xa3HZ}\xb5\xb6\xc4\xf7&\x96^\r\x91S\xbe\xe3\xc0\x1dT\x9f\xb09\xf0\xb9\x8c\xd5\xf5\xaei\x86\x8cFSU$\x14U\xfd\x130W\xbe&[\x1e\xd2\xe8\x06.\xe4\xe5Tw\n\x8ao\xe18ygs\x91\xb3X\x86\xedPyn\xc45\xbf\xf6\x86\x95Ǹ\xa1bm\xf0\x97\v\xee"`

**Comment by ZekeLu** [comment]
Can you provide the original `pass_clear` file that can be used to reproduce the issue?

**Comment by m-abdalrahman** [comment]
@ZekeLu https://drive.google.com/file/d/1mSEdXX2fFt6EimqnIf67PLyuH9LdxJaI/view?usp=sharing

**Comment by ZekeLu** [comment]
It turns out that openssl just reads the first line as the password.

This updated demo mimic this behavior of openssl.

```go
package main

import (
	"bufio"
	"crypto/aes"
	"crypto/cipher"
	"crypto/sha256"
	"log"
	"os"

	"golang.org/x/crypto/pbkdf2"
)

func main() {
	fiencpkg, err := os.ReadFile("pkg_digest")
	if err != nil {
		log.Fatalln(err)
	}

	salt := fiencpkg[8:16]
	log.Printf("salt:%X\n", salt)
	ciphertext := fiencpkg[16:]

	fiencpass, err := os.Open("pass_clear")
	if err != nil {
		log.Fatalln(err)
	}
	r := bufio.NewReader(fiencpass)
	p, _, err := r.ReadLine()
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("pass: %q", p)

	keyIv := pbkdf2.Key(p, salt, 10000, 48, sha256.New)
	key := keyIv[:32]
	iv := keyIv[32:48]
	log.Printf("key:%X\n", key)
	log.Printf("iv:%X\n", iv)

	block, err := aes.NewCipher(key)
	if err != nil {
		panic(err)
	}

	stream := cipher.NewCFBDecrypter(block, iv)
	stream.XORKeyStream(ciphertext, ciphertext)
	log.Printf("%q", ciphertext)
}
```

**Comment by seankhliao** [comment]
sounds like it's not a bug in the standard library

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
