### ISSUE TITLE
cmd/compile: disallow not-in-heap types to be used as type arguments

### ISSUE THREAD

**Issue by mdempsky** [golang/go#54765]
I think we shouldn't allow not-in-heap types to be used as type arguments.

```
func f[T any]() { println(new(T)) }
```

is a valid generic function declaration, but instantiating it as `f[nih]` will (or should) fail. (We're inconsistent about whether we catch this today: https://go.dev/play/p/bRMtJouiaR5)

In theory, we could still allow instantiating `f[nih]` if `f` doesn't contain `new(T)`, or allocate `T` on the stack, or any of the other problematic use cases; but this violates the generics principle that the type parameter constraints fully constrain what type arguments are valid.

I think the most likely case where this could come up today is with cgo and incomplete types; a user might want to write `atomic.Pointer[C.some_incomplete_type]`, which would now fail to compile if we reject not-in-heap types as type arguments. However, internally atomic.Pointer is using an unsafe.Pointer to store the pointer, which may not be appropriate for a `*C.some_incomplete_type` value, so arguably this is already potentially broken.

/cc @ianlancetaylor @randall77

**Comment by randall77** [comment]
I agree, we should probably disallow this.  I don't see how it would be terribly useful, and I don't see how we could implement it safely for almost any uses of T.

We should allow instantiating with a pointer-to-nih type, though. We need to be at least a bit careful there, as a pointer-to-nih must be treated as a uintptr, not a pointer. Which means when shapifying we can't unify pointer-to-nih types with *byte (like we do for most pointer types). I *think* we already have that special case?

**Comment by mdempsky** [comment]
> We should allow instantiating with a pointer-to-nih type, though.

Ack, agreed. Pointer-to-nih types are not themselves nih, so they're not subject to the proposed restriction here.

> I think we already have that special case?

Yeah, both nounified and unified have code to exempt pointer-to-nih from the current pointer shaping. I haven't spent too much time on it yet, but I'm pretty sure it's right.

**Comment by mknyszek** [comment]
@mdempsky assigning to you for now, but feel free to unassign it if you don't plan to work on it. Sounds like we should probably have some thing here for 1.20 (does this need a backport?), but I'm not sure.

**Comment by janpfeifer** [comment]
Just for future record, this created a nuanced incompatibility (code that worked in go 1.19 no longer works in 1.20), when using a C forward declared type as a type parameter, that is never instantiated (only pointers to it are used).

See example of breaking code in [go-nuts tread](https://groups.google.com/g/golang-nuts/c/h75BwBsz4YA/m/FLBIjgFBBQAJ)

@ianlancetaylor suggests it's too subtle (hard?) to ensure that the type is only used in acceptable ways -- that is, as pointers I'm assuming. But there is also no way to impose that a type parameter to be of pointer type (which would be a way around).

Maybe in the future someone will think of something.
