### ISSUE TITLE
x/mobile: gomobile bind slow compilation

### ISSUE THREAD

**Issue by NightBlaze** [golang/go#54770]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.19 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/user/Library/Caches/go-build"
GOENV="/Users/user/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/user/go/pkg/mod"
GONOPROXY="gitlab.mycompany.com"
GONOSUMDB="gitlab.mycompany.com"
GOOS="darwin"
GOPATH="/Users/user/go"
GOPRIVATE="gitlab.mycompany.com"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/7v/1f7g4jw1337ggmqlxxgq74g00000gn/T/go-build1457147379=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
time gomobile bind -target=ios golang.org/x/mobile/example/bind/hello
30,61s user 16,19s system 118% cpu 39,495 total

### What did you expect to see?
Faster compilation

### What did you see instead?
30 s compilation time on default empty project. Working project compiles 2,5 minutes

**Comment by heschi** [comment]
cc @hyangah

**Comment by NightBlaze** [comment]
@changkun The time is the same for every compilation. It seems that cgo doesn't use any cache and rebuild everything every time.

The same issue (long time compilation of `gomobile bind`) have all my team members.

**Comment by changkun** [comment]
I think https://go-review.googlesource.com/c/mobile/+/426274 is currently speeding up the compilation process. Can this patch mitigate this issue?

**Comment by hajimehoshi** [comment]
I'll work on the same thing for iOS in another CL.
