### ISSUE TITLE
x/build: upgrade netbsd-386 and netbsd-amd64 builders to pick up recent `libpthread` fixes

### ISSUE THREAD

**Issue by bsiegert** [golang/go#54773]
There are a few ongoing issues that are potentially related to kernel bugs in NetBSD (possibly related to #50496).

There was a new NetBSD stable release, 9.3, that fixes a large number of such bugs. Perhaps some of the hard-to-diagnose bugs that keep cropping up have been actually fixed upstream. (I certainly hope so!)

I can send a CL to bump the versions in /x/build. However, as I remember, at some point, a member of @golang/release needs to actually create the image, or I can do that on a corp workstation and provide a link to an image.

/cc @golang/netbsd

**Comment by cagedmantis** [comment]
I think sending a CL to bump the version in x/build would be the desired path.

**Comment by bcmills** [comment]
Per https://github.com/golang/go/issues/50138#issuecomment-1276782139, we should upgrade the NetBSD builders to a post-9.3 build that includes the `libpthread` fix (CC @riastradh).

**Comment by bcmills** [comment]
@bsiegert, is there anything remaining to be done for this? (Do the older builders still need to be turned down, or configured to only run on release branches?)

**Comment by bsiegert** [comment]
Yes, the *-9_0 builders should be turned down. Should I send a CL removing them from the dashboard?

**Comment by cagedmantis** [comment]
@bsiegert It would be great if you did. Thank you.
