### ISSUE TITLE
x/pkgsite: add package and symbol search options for vulnerabilities

### ISSUE THREAD

**Issue by jba** [golang/go#54802]
We should support the following searches for pkg.go.dev/vuln pages:

 - Search by module path / package path prefix
 - Search by symbol name

**Comment by julieqiu** [comment]
Related feedback:

A module author may want to know if any vulnerabilities are reported against any of the
modules they maintain, either current or past versions? This search UI could provide an easy way to figure
this out.

Ideally, support would include searching by a module path
prefix, for example, mvdan.cc/ or github.com/mvdan/, so I can then find all
known vulnerabilities for mvdan.cc/foo, github.com/mvdan/bar, etc."

**Comment by jamalc** [comment]
Done.
