### ISSUE TITLE
affected/package: stdlib math

### ISSUE THREAD

**Issue by thomshutt** [golang/go#54817]
### What version of Go are you using (`go version`)?

v1.19

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

darwin / arm64

Also reproduces in the Go Playground

### What did you do?

Did some simple floating point multiplication: https://go.dev/play/p/utCY6W7Sk9h

### What did you expect to see?

(0.5 * 0.8) + 0.2 = 0.6
(0.5 * 0.8) + 0.3 = 0.7
(0.5 * 0.8) + 0.4 = 0.8

### What did you see instead?

(0.5 * 0.8) + 0.2 = 0.6000000000000001
(0.5 * 0.8) + 0.3 = 0.7
(0.5 * 0.8) + 0.4 = 0.8

**Comment by alexballas** [comment]
Hello @thomshutt,
This is working as expected. Please refer to this site https://floating-point-gui.de/ for more details on Floating-Point Arithmetic. There are some libraries like shopspring/decimal that you could use instead.

**Comment by thomshutt** [comment]
Thanks @alexballas, will close the issue
