### ISSUE TITLE
x/tools/gopls/internal/regtest/diagnostics: failing test hangs instead of reporting failure

### ISSUE THREAD

**Issue by griesemer** [golang/go#54825]
From the [test log](https://storage.googleapis.com/go-build-log/cac0bfb6/linux-amd64_7c54045f.log) associated with CL 426477:
```
#### End Gopls Test Logs for "TestEditGoDirectiveWorkspace/default"
--- FAIL: TestEditGoDirectiveWorkspace (27.63s)
    --- FAIL: TestEditGoDirectiveWorkspace/default (27.63s)
        diagnostics_test.go:2144: waiting on:
            Unmet: once "main.go: diagnostic at {line:2, column:7} (location of \"T any\") with message \"type parameters require\"" is met, must have:
            read diagnostics for "main.go"
            
            err:context deadline exceeded
            
            state:
            #### log messages (see RPC logs for full text):
            	Info: "2022/09/01 22:23:27 go env for /workdir/tmp/gopls-...
            	Info: "2022/09/01 22:23:27 go/packages.Load #202\n\tsnaps...
            	Info: "2022/09/01 22:23:27 go/packages.Load #202: updatin...
            
            #### diagnostics:
            	main.go (version 0):
            		(2, 7): type parameter requires go1.18 or later
            		(2, 9): predeclared any requires go1.18 or later
            
            #### outstanding work:
            #### completed work:
            	Load: 1
            	Setting up workspace: 1
            	diagnosing initial workspace load: 1
            
FAIL
FAIL	golang.org/x/tools/gopls/internal/regtest/diagnostics	599.048s
```
The test is supposed to fail with an error message (fix is CL 427736), but instead it times out. Running locally, the test appears to never finish.

**Comment by griesemer** [comment]
To reproduce, simply change the expected error in gopls/internal/regtest/diagnostics/diagnostics_test.go:2112 to an incorrect message.

**Comment by findleyr** [comment]
Much of the LSP is communicated via bidirection notifications, and doesn't lend itself to operate-and-assert style testing, so our test framework must support the notion of something happening "eventually". Initially, this was the best we could do, but we've added additional instrumentation that allows us to express things like "once gopls is done processing this change, we should have a diagnostic in the editor", and most if not all tests can be written to fail eagerly. This is done in [CL 427543](https://go.dev/cl/427543).
