### ISSUE TITLE
x/tools/internal/lsp: re-enable/fix disabled tests (tracking issue)

### ISSUE THREAD

**Issue by griesemer** [golang/go#54822]
Because of changes to the go/parser and go/types, some lsp tests were disabled. This issue tracks the respective CL so we can re-enable and/or fix the tests.

Tentatively set for Go 1.20 but may be moved if necessary.

**Comment by griesemer** [comment]
@findleyr Is there anything left to do here for 1.20? Should this be moved over to 1.21, or can it be closed?

**Comment by findleyr** [comment]
Yes there is, though it needn't be associated with the 1.20 milestone.

I'd prefer to leave it in the milestone for this week, in case there are any fixes required to re-enable the test. I plan to get to it this week.

**Comment by findleyr** [comment]
Moved this to a gopls milestone, as it need not be in a Go milestone: we will endeavor to re-enable these tests before gopls@v0.11.0, which is the version of gopls corresponding to Go 1.20.
