### ISSUE TITLE
x/vuln/cmd/govulncheck: document the default cache location

### ISSUE THREAD

**Issue by hyangah** [golang/go#54829]
Currently, `govulncheck` creates a local cache under `$GOPATH/pkg/mod/cache/download/vulndb`.
Document this - I had old data in this cache (before the spec change) which prevented the newly built govulncheck from working correctly.

Related questions:
* Is there any way to set a different location than a subdirectory?
* Is deleting the directory the recommended best practice when users want to fix corrupted/outdated cache problems? Or should we use a variation of `go clean`?

**Comment by heschi** [comment]
cc @golang/vulndb

**Comment by zpavlinovic** [comment]
Although we expect spec to converge at some point, we should have a story for updating this. Would ideally this be done automatically, e.g., refetch if the spec has changed? Or you'd like more control via, say, `GOVULNDBCACHE` flag?

**Comment by zpavlinovic** [comment]
The new design of the db does not use cache, so this is obsolete now.
