### ISSUE TITLE
unsafe: unsafe.Alignof atomic.Int64 error 

### ISSUE THREAD

**Issue by richzw** [golang/go#54832]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.19 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/me/Library/Caches/go-build"
GOENV="/Users/me/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/me/go/pkg/mod"
GONOPROXY="github.com/com"
GONOSUMDB="github.com/com"
GOOS="darwin"
GOPATH="/Users/me/go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/me/go119/go1.19"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/me/go119/go1.19/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/me/go/src/test/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/c9/4szs5fc14m74qknb351618k00000gn/T/go-build2731140220=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

For codes

```go
func main() {
	var a64 atomic.Int64
	fmt.Println(unsafe.Alignof(a64))
}
```

With compile `GOOS=linux GOARCH=386 go build tt.go`

Got the output error

```
# command-line-arguments
./test.go:8:28: internal compiler error: got 4 from types2, but want 8

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new
```

Is there anything am I misunderstanding or missing?

**Comment by cuonglm** [comment]
Duplicated of  https://github.com/golang/go/issues/54220.
