### ISSUE TITLE
Potential issue with type conversions for generic functions that have function pointer parameters

### ISSUE THREAD

**Issue by vishvananda** [golang/go#54831]
### What version of Go are you using (`go version`)?
go 1.19 (go playground)

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

playground

### What did you do?

https://play.golang.com/p/hkijxIysB-f

### What did you expect to see?

I expected to be able to pass print2 to the generic2 function

### What did you see instead?

    ./prog.go:39:17: cannot use print2 (value of type func(vals Foo)) as type func([]int) in argument to generic2

Foo is typedef to []int and i can use them interchangeably for function calls and for generic parameters, but when I use a function pointer parameter containing the generic type it cannot be converted to the other. It seems like this conversion should be legal since two types are equivalent, but it is not allowed.

**Comment by vishvananda** [comment]
Looks like it is possible to work around this with some constraints:

    func generic2[U ~[]T, T any](vals []T, f func(U)) {
        f(vals)
    }
    
 https://play.golang.com/p/BZnhPMbLsoY
 
 I'll leave this open for now because it seems odd that the type in the first parameter is converted automatically but the second requires the special underlying type syntax.

**Comment by seankhliao** [comment]
The need for `~` is working as intended.
