### ISSUE TITLE
x/tools/gopls: struct filling breaks with generic items

### ISSUE THREAD

**Issue by not-rusty** [golang/go#54836]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19 linux/amd64
$ gopls version
golang.org/x/tools/gopls v0.9.4
    golang.org/x/tools/gopls@v0.9.4 h1:YhHOxVi++ILnY+QnH9FGtRKZZrunSaR7OW8/dCp7bBk=
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

GOHOSTARCH="amd64"
GOHOSTOS="linux"

### What did you do?

Open a main.go file and try autofilling these structs:

```go
package main

type GenericUser[T any] struct {
	Name  string
	Age   int
	Value T
}

type StructUsingAGeneric struct {
	User GenericUser[string]
	Age  int
}

func main() {
	// Fill anonymous struct breaks here.
	_ = GenericUser[string]{
	}

	// Here it isn't even an option.
	_ = StructUsingAGeneric{
		
	}
}


```

### What did you expect to see?

I did expect `gopls` to autofill these structs without problem when the generic type is provided.

```go
package main

type GenericUser[T any] struct {
	Name  string
	Age   int
	Value T
}

type StructUsingAGeneric struct {
	User GenericUser[string]
	Age  int
}

func main() {
	// Fill anonymous struct breaks here.
	_ = GenericUser[string]{
		Age: 0,
		Value: "",
	}

	// Here it isn't even an option.
	_ = StructUsingAGeneric{
		User: GenericUser[string]{},
		Age: 0,
	}
}
```

### What did you see instead?

Error on the first case in my lsp client, no action suggested in the other case.

**Comment by adonovan** [comment]
The GenericUser example works for me (when I add a test case for it). But the lack of support for fields that contain type parameters appears to be a known limitation of the current information:

https://cs.opensource.google/go/x/tools/+/master:gopls/internal/lsp/analysis/fillstruct/fillstruct.go;l=100-101?q=ignore.*for.now%20&ss=go%2Fx%2Ftools

**Comment by findleyr** [comment]
There's still action to take here: either make it work, or don't suggest struct filling if it is known to not work.
