### ISSUE TITLE
cmd/link,runtime: unused fields in `inlinedCall`

### ISSUE THREAD

**Issue by prattmic** [golang/go#54849]
[`runtime.inlinedCall`](https://cs.opensource.google/go/go/+/master:src/runtime/symtab.go;l=1175;drc=b5b2cf519fe332891c165077f3723ee74932a647) fields `parent` (`parentPc` is used instead), `file` (`pcfile` in the parent is used), and `line` (`pcln` in the parent is used) seem to be completely unused. They are a reflection of fields in [`goobj.InlTreeNode`](https://cs.opensource.google/go/go/+/master:src/cmd/internal/goobj/funcinfo.go;l=106;drc=ef8414101fba959c8df220ca0e544781029ce111), which are used within the toolchain, but the runtime itself doesn't need them.

If I did the math right, cmd/go contains 431KB of `inlineTree` objects (2.8% of the binary size). With those fields gone it would drop to 258KB.

**Comment by aclements** [comment]
Neat. Originally these were important because we didn't have parentPc or the marker NOPs to attach file/line to, so the only source of that metadata was the inline tree. I believe you're right that they are no longer necessary.
