### ISSUE TITLE
cmd/vet: false positive of self-assignment

### ISSUE THREAD

**Issue by afriza** [golang/go#54840]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/username/Library/Caches/go-build"
GOENV="/Users/username/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/username/go/pkg/mod"
GONOPROXY="gitlab.com/orgname"
GONOSUMDB="gitlab.com/orgname"
GOOS="darwin"
GOPATH="/Users/username/go"
GOPRIVATE="gitlab.com/orgname"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/username/Code/project/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/r3/9d9f8ggn5t1_vd8ht7425w9c0000gn/T/go-build3919061805=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

https://go.dev/play/p/TBs0FGA9Ry8
```go
package main

func main() {
	m := make(map[string][]string)
	m["s"] = m["s"]
}
```
```console
$ go vet
# test
./main.go:5:2: self-assignment of m["s"] to m["s"]
```

### What did you expect to see?

nothing

### What did you see instead?
./main.go:5:2: self-assignment of m["s"] to m["s"]

I thought this is supposed to be fixed. Looks similar to https://github.com/golang/go/issues/22174

**Comment by seankhliao** [comment]
This is a true positive.

**Comment by randall77** [comment]
No, this is a false positive. The thing that looks like a self-assignment modifies `m` to have length 1 (maps "s" to nil).

**Comment by heschi** [comment]
cc @matloob @timothy-king

**Comment by timothy-king** [comment]
I do not find the example given in the issue all that compelling.  `m["s"] = nil` is obviously better. Here is a slightly contrived, but more compelling example:
```
// AddKeys adds keys as keys in the map m. Returns true if any keys were added.
func AddKeys(m map[string]interface{}, keys []string) bool {
  l := len(m)
  for _, k := range keys {
    m[k] = m[k]
  }
  return l >= len(m)
}
```

The root cause is that analysisutils.HasSideEffect is applied the lhs and rhs independenly by the `assign` pass and does not take into account the side effect of an assign statement to an index on a map.

I think we do not want vet warning in this case.

**Comment by afriza** [comment]
The example was minimum reproducible code..
My actual use case was: if map content exists keep it, if the key doesn't exist, use nil.

Alternative implementation for my case would be 
```go
if _, ok := m["s"]; !ok {
        m["s"] = nil
}
```

**Comment by timothy-king** [comment]
Right. I just wanted an example where "if map content exists keep it, if the key doesn't exist, use [zero value]" is clearly the desired operation. This made being a "false positive" more obvious (at least to me).
