### ISSUE TITLE
unsafe: no documentation for unsafe.SliceData, StringData, or String

### ISSUE THREAD

**Issue by robpike** [golang/go#54858]
Recent changes added these data types to the unsafe package, but due to the peculiarities of how unsafe is implemented, special work needs to be done to have

```
go doc unsafe.String
```

work. It does not:

```
% go doc unsafe.String
doc: no symbol String in package unsafe
exit status 1
% 
```

Please fix.

**Comment by hopehook** [comment]
Final work is in progress, there are still some comments on the revisions to the documentation that have not been resolved, so they have not been merged.

FYI: https://go-review.googlesource.com/c/go/+/427095

**Comment by hopehook** [comment]
CC @mdempsky

**Comment by griesemer** [comment]
Not sure why this was closed. As far as I can tell, this is not done yet.

**Comment by robpike** [comment]
Closed because it overlapped with other issues about this, and because of https://go-review.googlesource.com/c/go/+/427095

**Comment by griesemer** [comment]
https://go-review.googlesource.com/c/go/+/427095 is now submitted. The spec changes have also been submitted (https://go-review.googlesource.com/c/go/+/449537).
