### ISSUE TITLE
Document link always quoted 500

### ISSUE THREAD

**Issue by Oliverwqcwrw** [golang/go#54867]
In [https://go-zh.org/doc/](https://go-zh.org/doc/)

when i click `Go 语言之旅`

it always report 500

<img width="863" alt="image" src="https://user-images.githubusercontent.com/31796988/188339719-b15542db-2dae-4165-943d-b1fc613bcb04.png">

**Comment by mengzhuo** [comment]
`go-zh.org` is not a part of Golang project.
Please contact their site admin for help.
