### ISSUE TITLE
x/pkgsite: net/http/cookiejar directory entry weird

### ISSUE THREAD

**Issue by danp** [golang/go#54872]
### What is the URL of the page with the issue?

https://pkg.go.dev/net/http#section-directories

### What is your user agent?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

### Screenshot

<img width="1115" alt="Screen Shot 2022-09-05 at 8 45 21 AM" src="https://user-images.githubusercontent.com/2182/188441548-5441080c-4398-493f-9423-5e24d0d807e6.png">

### What did you expect to see?

The cookiejar directory/package linked similar to others.

### What did you see instead?

The cookiejar entry missing the directory/package name, with the package doc where the name should be.

**Comment by seankhliao** [comment]
Not seeing this either.
