### ISSUE TITLE
access: gomote

### ISSUE THREAD

**Issue by tklauser** [golang/go#54873]
I'm re-requesting access to gomote per the instructions at https://github.com/golang/go/wiki/Gomote#access

I previously already had gomote access and occasionally used to test and debug patches around `syscall` and `golang.org/x/sys` on different platforms before sending CLs. I'd like to be able to make use of gomote for that purpose in the future.

account: tobias.klauser -at- gmail -dot- com

/cc @golang/release

**Comment by mknyszek** [comment]
Approved! You should now have access. Give it some time if it doesn't work immediately, but please post here again if you have any issues.
