### ISSUE TITLE
go/doc/comment: markdown multi-level lists don't work if the comment ends directly before a thing

### ISSUE THREAD

**Issue by Jorropo** [golang/go#54894]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/hugo/.cache/go-build"
GOENV="/home/hugo/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/hugo/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/hugo/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/home/hugo/Documents/Scripts/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/hugo/Documents/Scripts/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v3"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4005220034=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Load https://go.dev/play/p/au_BiSmy6DK then press `format`.

### What did you expect to see?

```go
// Example
//   - 1
//     - 1.1
package a

// b test stuff
//   - 1
//     - 1.1
type b struct{}

// However this works
//   - 1
//     - 1.1

type farAway struct{}
```

### What did you see instead?

```go
// Example
//   - 1
//   - 1.1
package a

// b test stuff
//   - 1
//   - 1.1
type b struct{}

// However this works
//   - 1
//     - 1.1

type farAway struct{}
```

**Comment by seankhliao** [comment]
This is working as intended: from https://pkg.go.dev/go/doc/comment#pkg-overview , doc comments are only:

> Package comment implements parsing and reformatting of Go doc comments, (documentation comments), which are comments that immediately precede a top-level declaration of a package, const, func, type, or var.

**Comment by Jorropo** [comment]
@seankhliao thx I didn't knew how this was called, however this isn't solving my issue.
Now I find that the `Go Doc Comments` spec doesn't support nested lists.

If I want to add support for that, how can I do this ? Should I open a proposal ?

**Comment by seankhliao** [comment]
This is an explicit design choice: [link to design doc](https://github.com/golang/proposal/blob/master/design/51082-godocfmt.md#:~:text=Note%20also%20that%20there%20are%20no%20code%20blocks%20inside%20list%20items%E2%80%94any%20indented%20paragraph%20following%20a%20list%20item%20continues%20the%20list%20item%2C%20and%20the%20list%20ends%20at%20the%20next%20unindented%20line%E2%80%94nor%20are%20there%20nested%20lists.%20This%20avoids%20any%20the%20space%2Dcounting%20subtlety%20like%20in%20Markdown)

> Note also that there are no code blocks inside list items—any indented paragraph following a list item continues the list item, and the list ends at the next unindented line—nor are there nested lists. This avoids any the space-counting subtlety like in Markdown.
