### ISSUE TITLE
net/http: ProxyFromEnvironment documentation is wrong

### ISSUE THREAD

**Issue by dfawley** [golang/go#54890]
After the change in #40909 (referenced via #45227), the [documentation for `ProxyFromEnvironment`](https://pkg.go.dev/net/http@go1.19#ProxyFromEnvironment) still incorrectly claims:

> HTTPS_PROXY takes precedence over HTTP_PROXY for https requests.

It seems `HTTP_PROXY` is no longer used at all for `https` requests.  The documentation here should have been fixed when the breaking change was made in Go 1.16.

**Comment by mknyszek** [comment]
CC @neild
