### ISSUE TITLE
x/vuln: fails to run in monorepo with non-go programming language files

### ISSUE THREAD

**Issue by lbhdc** [golang/go#54895]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.5 linux/amd64
</pre>

### Does this issue reproduce at the latest version of golang.org/x/vuln?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/<user>/.cache/go-build"
GOENV="/home/<user>/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/<user>/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/<user>/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/lib/golang"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/<user>/<code>/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3715058208=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

```shell
cd <repo root>
ovulncheck ./...
govulncheck is an experimental tool. Share feedback at https://go.dev/s/govulncheck-feedback.

Scanning for dependencies with known vulnerabilities...
govulncheck: Packages contain errors:
-: C++ source files not allowed when not using cgo or SWIG: 
```

### What did you expect to see?

```shell
govulncheck ./...
govulncheck is an experimental tool. Share feedback at https://go.dev/s/govulncheck-feedback.

Scanning for dependencies with known vulnerabilities...
No vulnerabilities found.
```

### What did you see instead?

```shell
cd <repo root>
ovulncheck ./...
govulncheck is an experimental tool. Share feedback at https://go.dev/s/govulncheck-feedback.

Scanning for dependencies with known vulnerabilities...
govulncheck: Packages contain errors:
-: C++ source files not allowed when not using cgo or SWIG: <cpp files>
```

In my monorepo most of the code is separated by language, but some of it isn't (code generated from protobufs live next to the protos used to generate them). When I attempt to run with a more limited scope to only hit my go code dir, I still run into the same issue. go vuln check walks the directory to where those generated sources are, but chokes on the c++ files there. Those c++ files aren't used by any of the go programs. 
```shell
govulncheck ./<gocode>/...
govulncheck is an experimental tool. Share feedback at https://go.dev/s/govulncheck-feedback.

Scanning for dependencies with known vulnerabilities...
govulncheck: Packages contain errors:
-: C++ source files not allowed when not using cgo or SWIG: ...
```

**Comment by mknyszek** [comment]
CC @golang/vulndb

**Comment by zpavlinovic** [comment]
Thanks for bringing this up. Do you have a reproducible example we can work with?

**Comment by zpavlinovic** [comment]
I can confirm that the message appears for the reproduction module. But I get the same message when running `go test ./...` or `go build .`  What happens when you run these two go commands for the original repo?

**Comment by zpavlinovic** [comment]
> Still not sure why cgo cares about c++ files when it can't use them.

Go does recognize C++ files in the sense that it will try to [compile them](https://pkg.go.dev/cmd/cgo)

```
When the Go tool sees that one or more Go files use the special import "C", it will look for other non-Go files in the directory and compile them as part of the Go package. ...  Any .cc, .cpp, or .cxx files will be compiled with the C++ compiler. 
```
