### ISSUE TITLE
runtime: scavengeOne ignores searchIdx optimization

### ISSUE THREAD

**Issue by mvdan** [golang/go#54892]
```
// [...]
// searchIdx is the page index to start searching from in ci.
// [...]
func (p *pageAlloc) scavengeOne(ci chunkIdx, searchIdx uint, max uintptr) uintptr {
```

Yet searchIdx has never been used in the func body, as far as I can see. Is the parameter truly unnecessary and can be removed, or is it a bug that the parameter isn't being used? I found this one via unparam, but it's not a clear one without understanding the context of the function.

cc @mknyszek @prattmic per `git blame` :)

**Comment by mvdan** [comment]
Another one nearby: `gcmarknewobject` does not use its `scanSize` parameter, but at least that one isn't documented.

**Comment by mknyszek** [comment]
Ah, that's a mistake, albeit a minor one. It's not a bug, just slightly less efficient. It should be passed to `findScavengeCandidate` instead of `pallocChunkPages-1`.

**Comment by mknyszek** [comment]
The extra argument `gcmarknewobject` is likely a leftover from the Go 1.18 pacer updates. I believe it was used by the Go 1.17 pacer and when I deleted the branches in Go 1.19 I neglected to delete the parameter.

**Comment by mknyszek** [comment]
No need to file an issue about `gcmarknewobject`, I'll just clean that up sometime this cycle.

**Comment by mvdan** [comment]
Ack, I'll leave both here for you then :)
