### ISSUE TITLE
x/pkgsite: package removal request for github.com/marcelohmariano/timescaledb-benchmark

### ISSUE THREAD

**Issue by marcelohmariano** [golang/go#54897]
### What is the path of the package that you would like to have removed?
github.com/marcelohmariano/timescaledb-benchmark 
 
### Are you the owner of this package?
Yes.
 
### What is the reason that you could not retract this package instead?
Published accidentally.

**Comment by seankhliao** [comment]
Please retract this module if it was published in error. Steps are available at https://go.dev/ref/mod#go-mod-file-retract.

**Comment by marcelohmariano** [comment]
This repo will be deleted soon because it's just a project for a coding assessment. That's why I requested the deletion.
