### ISSUE TITLE
net/http: flake in TestCancelRequestWhenSharingConnection

### ISSUE THREAD

**Issue by mknyszek** [golang/go#54909]
[2022-09-03T18:21:45-a0f0582/windows-arm64-10](https://build.golang.org/log/dafdc74185dddb68c672771658eecf09c79233a7)

CC @neild

**Comment by bcmills** [comment]
Given that it's on `windows/arm64`, I suspect a platform bug — there seem to be a lot of issues remaining in the `windows/arm64` network stack (CC @qmuntal).

See also #53584, #51147, #51080; hopefully many of these will be addressed by #53541.

**Comment by bcmills** [comment]
Duplicate of #55226

**Comment by bcmills** [comment]
(Dup'd to that one even though it is newer because it already has a `watchflakes` pattern.)
