### ISSUE TITLE
cmd/compile: internal compiler error: method ToNumber on struct {} not found

### ISSUE THREAD

**Issue by jmacd** [golang/go#54910]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.1 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/josh.macdonald/Library/Caches/go-build"
GOENV="/Users/josh.macdonald/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/josh.macdonald/src/lightstep/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/josh.macdonald/src/lightstep/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/josh.macdonald/src/opentelemetry/otel-launcher-go/lightstep/sdk/metric/go.mod"
GOWORK="/Users/josh.macdonald/src/opentelemetry/otel-launcher-go/go.work"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hp/8_6w4qns7g79tww_56kst5nh0000gp/T/go-build743137128=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Tried to build the code linked here: https://go.dev/play/p/OAZa7iraqsH
The code rooted here: https://github.com/lightstep/otel-launcher-go/tree/main/lightstep/sdk/metric

### What did you expect to see?

This compiles with 1.18.6.
Incidentally, this code produced https://github.com/golang/go/issues/54302 in the 1.19 release.

### What did you see instead?

```
../gopath861173676/pkg/mod/github.com/lightstep/otel-launcher-go/lightstep/sdk/metric@v1.10.1/internal/viewstate/collectors.go:108:16: internal compiler error: method ToNumber on struct {} not found
```

**Comment by jmacd** [comment]
Having trouble isolating this with a small example.

**Comment by cuonglm** [comment]
This is duplicated of #54225, will be fixed by https://go-review.googlesource.com/c/go/+/428356
