### ISSUE TITLE
crypto/x509: Reallow duplicate attributes in CSRs.

### ISSUE THREAD

**Issue by robstradling** [golang/go#54936]
Tracking https://go-review.googlesource.com/c/go/+/428636

If accepted, I'd like this to be considered for backport to the next 1.19 minor release.

**Comment by mknyszek** [comment]
CC @golang/security

**Comment by rolandshoemaker** [comment]
Fixed by http://go.dev/cl/428636.

**Comment by FiloSottile** [comment]
This was a fix for a regression introduced by #50988, and #57556 is the Go 1.19 backport request.
