### ISSUE TITLE
x/vuln: enhancing community involvement for GHSA

### ISSUE THREAD

**Issue by bnevis-i** [golang/go#54937]
### What version of Go are you using (`go version`)?

n/a

### Does this issue reproduce at the latest version of golang.org/x/vuln?

n/a

### What operating system and processor architecture are you using (`go env`)?

n/a

### What did you do?

n/a

### What did you expect to see?

n/a

### What did you see instead?

n/a

### Suggestion

Given that this new tool has the ability to import GHSA's, and GHAS's have Contributor and Credits fields (who have valid github ids), it might increase community participation when importing GHSA's to cc the reporters of the original issue.

**Comment by mknyszek** [comment]
CC @golang/vulndb

**Comment by julieqiu** [comment]
Thanks for the suggestion!

@bnevis-i - would you mind pointing me to where you see the "Contributor and Credits" field?

**Comment by seankhliao** [comment]
The ones with a profile icon in their row have an extra credits section in their sidebar
https://github.com/advisories?query=type%3Areviewed
Example: https://github.com/advisories/GHSA-rvgm-35jw-q628

**Comment by julieqiu** [comment]
Thanks @seankhliao!

Do you know of an easy way to get this information from the API? I don't see it a field here: https://docs.github.com/en/graphql/reference/objects#securityadvisory, or at https://github.com/github/advisory-database/blob/2cd22bd9a7fea97dd2f2378c28f0b9615332a3c5/advisories/github-reviewed/2022/08/GHSA-rvgm-35jw-q628/GHSA-rvgm-35jw-q628.json.

**Comment by seankhliao** [comment]
Not that I'm aware of

**Comment by bnevis-i** [comment]
I can't find it either.  I withdraw the suggestion. :-(
