### ISSUE TITLE
x/pkgsite: package removal request for https://pkg.go.dev/github.com/lavafroth/debloatplusplus

### ISSUE THREAD

**Issue by lavafroth** [golang/go#54953]
### What is the path of the package that you would like to have removed?

 

https://pkg.go.dev/github.com/lavafroth/debloatplusplus
 
### Are you the owner of this package?

Yes
 
### What is the reason that you could not retract this package instead?

I had renamed my repository (now at github.com/lavafroth/droidrunco) which is a version ahead of the conflicting package at pkg.go.dev

**Comment by bcmills** [comment]
> What is the reason that you could not retract this package instead?

The `retract` directive is intended to work even if the module path no longer matches. (It applies to a version range, but that version range applies to all module paths that resolve to the same repository.)
