### ISSUE TITLE
cmd/go: go get cannot handle custom repository URLs specified using ".hg" importpath suffix

### ISSUE THREAD

**Issue by gopherbot** [golang/go#5495]
by **czapkofan**:

<pre>What steps will reproduce the problem?
1. hg init foobar
2. cd foobar
3. hg serve --daemon --port 80 --prefix foobar --pid-file ../foobar.pid
4. cd ..
5. hg clone -U <a href="http://127.0.0.1/foobar">http://127.0.0.1/foobar</a> foobar2
6. go get 127.0.0.1/foobar.hg

What is the expected output?
(no errors during download)

What do you see instead?
# cd .; hg clone -U 127.0.0.1/foobar c:\gopath\src\127.0.0.1\foobar.hg
abort: repository 127.0.0.1/foobar not found!
package 127.0.0.1/foobar.hg: exit status 255

Which compiler are you using (5g, 6g, 8g, gccgo)?

Which operating system are you using?
Windows 7

Which version are you using?  (run 'go version')
go version go1.1 windows/amd64

Please provide any additional information below.
AFAIK, Mercurial requires a schema (http://) in the cloned URL, otherwise it assumes
this is a local filesystem path.</pre>

**Comment by ianlancetaylor** [comment]
Closing based on previous comment.  Please reopen if not fixed.
