### ISSUE TITLE
x/website: Fuzzing documentation image has transparent background, works poorly with dark mode

### ISSUE THREAD

**Issue by carlpett** [golang/go#54954]
The fuzzing page, https://tip.golang.org/security/fuzz/, has an image describing different components involved. It however has a transparent background, and with the page supporting dark mode, the image gets very tricky to read:
![image](https://user-images.githubusercontent.com/214867/189207556-9c10f2e7-894a-4b8c-be87-678fb45a21a9.png)

I'm not sure if having a opaque white background would be problematic, but that seems to be the easiest solution.

**Comment by mvdan** [comment]
An alternative might be a white background with 50% opacity, then at least you don't get a block of solid white light on dark mode.

**Comment by mknyszek** [comment]
CC @dmitshur

**Comment by cameronldroberts** [comment]
Hey would like to pick this up if possible :)

**Comment by Deleplace** [comment]
Cameron's fix is one fine way to solve this. It makes the code readable again, at the cost of having block with white background inside a dark page.

I can think of 2 other approaches that would "save" the ambiant dark background:
- edit the original picture to apply a shadow (bright or half-bright) to all the text
- server a different picture when in dark mode, as illustrated here https://chrisruppel.com/blog/picture-prefers-color-scheme-dark/

**Comment by Deleplace** [comment]
I experimented 2 ways of adding a light-tone shadow:

- With the CSS style `filter: drop-shadow(0.5px 0.5px 0.3px #CCC);`
<img width="707" alt="image" src="https://user-images.githubusercontent.com/13508141/198298109-a8d89d5e-cbca-4ac9-b84d-3cb17ebd84b9.png">


- By editing the original image 
<img width="679" alt="image" src="https://user-images.githubusercontent.com/13508141/198298339-20334986-90f7-4951-a068-d010f3e6d634.png">

While these have the advantage of having a single transparent PNG that works in both light them and dark theme, I'm still not satisfied with the readability of the dark version.

See my next comment instead.

**Comment by Deleplace** [comment]
We can achieve much better results by serving a different image for light theme (default) and dark theme.

Something like 
```
<picture>
	<source srcset="/security/fuzz/example_dark.png" media="(prefers-color-scheme: dark)" type="image/svg+xml">
	<img alt="Example code showing [...]" src="/security/fuzz/example.png" style="display: block; width: 600px; height:
auto;">
</picture>
```

<img width="640" alt="image" src="https://user-images.githubusercontent.com/13508141/198300391-23d5c739-04f5-4550-8d20-d125e49f9c3e.png">

<img width="642" alt="image" src="https://user-images.githubusercontent.com/13508141/198301741-7d5dd06d-96a2-4331-b8f1-8f0463a8a094.png">

I could make a CL for this.
