### ISSUE TITLE
how to config go web app in nginx

### ISSUE THREAD

**Issue by Yudas21** [golang/go#54950]

**Comment by Yudas21** [comment]
access http://localhost:8080/api/v1/menus in nginx, 502 bad gateway. how to solve it. Please help me

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
