### ISSUE TITLE
Somehow allowed to mix named and unnamed return types.

### ISSUE THREAD

**Issue by assyrianic** [golang/go#54960]
### What version of Go are you using (`go version`)?

<pre>
go1.12.7
reproducible on go1.19.0
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env linux amd64

</pre></details>

### What did you do?
wrote test code for an AST transpiler and noticed discrepancy.

https://go.dev/play/p/6UqzL03ltk_I

### What did you expect to see?
Consistent type requirements.

### What did you see instead?
That a return type of two ints (one named, one unnamed) and one bool somehow allows me to return an int and two bools.

**Comment by assyrianic** [comment]
![image](https://user-images.githubusercontent.com/12402418/189232485-74150dc2-d726-49a5-a5e3-6d4a769cc041.png)

**Comment by assyrianic** [comment]
![image](https://user-images.githubusercontent.com/12402418/189232621-a9d370f1-32b3-4db9-ba8d-6644bf78d49b.png)

**Comment by assyrianic** [comment]
![image](https://user-images.githubusercontent.com/12402418/189232701-1e884003-4aa7-4f17-a07b-adfb7ccf1ba1.png)

**Comment by seankhliao** [comment]
Confusing but working as intended, the second `int` is a named return of type `bool`.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by assyrianic** [comment]
> Confusing but working as intended, the second `int` is a named return of type `bool`.
@seankhliao  How is it a named return type of bool when it's separated by a comma? The comma is ignored?

**Comment by griesemer** [comment]
The meaning of `int` depends on the scope. Here you have a (return) parameter list of the form
```Go
(X int, Y, Z bool)
```
The scope of `X`, `Y`, and `Z` is the function body (https://golang.org/ref/spec#Declarations_and_scope), so your actual  name for `Y` which is `int` is simply a variable (a result parameter) that happens to have the name `int` and is visible in the function body (and inside it shadows the predeclared `int`). Go ahead and assign to it!

**Comment by go101** [comment]
@assyrianic 
You may use `_` as var names:

```Go
func test() (i1 int, _ int, b1 bool) {
...
}
```

**Comment by assyrianic** [comment]
> @assyrianic 
> You may use `_` as var names:
> 
> ```Go
> func test() (i1 int, _ int, b1 bool) {
> ...
> }
> ```
> 
> or another equivalence 
> 
> ```Go
> func test() (i1, _ int, b1 bool) {
> ...
> }
> ```

This one I already knew and pretty interesting but it was just how the type name also being used as a variable name threw me off. I would've thought the type checker would make that an error somehow but I was wrong.
