### ISSUE TITLE
spec: typo in a type parameter example

### ISSUE THREAD

**Issue by dolzenko** [golang/go#54973]
In https://golang.org/ref/spec 
```
func apply[S ~[]E, E any](s S, f(E) E) S { … }
```

should be something like

```
func apply[S ~[]E, E any](s S, f func(E) E) S { … }
```

**Comment by mvdan** [comment]
The spec is in the main repo, not the website, so I've retitled this.

I think you're right about the typo. Want to send a PR or CL? See https://go.dev/doc/contribute.

**Comment by mknyszek** [comment]
CC @griesemer @ianlancetaylor
