### ISSUE TITLE
x/vuln: 500 error for excluded reports

### ISSUE THREAD

**Issue by willfaught** [golang/go#54981]
### What did you do?

Navigated to https://pkg.go.dev/vuln/GO-2022-0964.

### What did you expect to see?

On https://pkg.go.dev/vuln/, I saw GO-2022-0965, GO-2022-0963, and GO-2022-0962 listed. I wondered what the numbering scheme was, and why there wasn't a *0964. So I navigated to that page, expecting either info or a 404.

### What did you see instead?

>500 Internal Server Error

**Comment by seankhliao** [comment]
cc @golang/vulndb

**Comment by hyangah** [comment]
This is fixed.
