### ISSUE TITLE
proposal: Generics apply to struct methods

### ISSUE THREAD

**Issue by michaelhenry** [golang/go#55006]
Something like this:

```go
type Store struct {}

func (s *Store) Get[model any](key string) (*model, error) {
  ...
}

```
Currently, having a generic inside a struct function can throw a syntax error like:
```bash
syntax error: method must have no type parameters
```

Though my current workaround with this is by creating a generic function that accepts a pointer of the struct, but it would better if generics can be accepted inside struct functions and not only on `struct[T]`. and I think with this, a lot of APIs can be totally simplified.

```go

func Get[model any](store *Store, key string)(*model, error) {
   ...
}
```
Any particular reason, why we can't allow this? or any plan in the future? 

Thanks

**Comment by seankhliao** [comment]
Duplicate of #49085
