### ISSUE TITLE
Hello friends, (if Err! = nil) Is there an alternative now?

### ISSUE THREAD

**Issue by xiaokentrl** [golang/go#55003]
Hello friends, (if Err! = nil) Is there an alternative now?

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by D1CED** [comment]
If you are looking for updates on error handling I recommend you subscribe to #40432.
