### ISSUE TITLE
x/crypto/ssh: EOF on password expired 

### ISSUE THREAD

**Issue by fdefilippo** [golang/go#55011]
connecting to an sftp server using username and password and the password has expired I get EOF as an error message instead of the output of the server asking to change the password because it has expired.

```
package main
import (
"fmt"
    "golang.org/x/crypto/ssh"
)

func main() {

    config := &ssh.ClientConfig{
      User: "testuser",
      Auth: []ssh.AuthMethod{
        ssh.Password("password"),
      },
      HostKeyCallback: ssh.InsecureIgnoreHostKey(),
    }

    conn, err := ssh.Dial("tcp", "127.0.0.1:22", config)
    if err != nil {
      fmt.Println("ssh dial", err)
      return
    }

    _ = conn
    fmt.Println("ok")
}

```

go run expire.go
```
ssh dial ssh: handshake failed: EOF
```

how can i get the correct server message?

**Comment by seankhliao** [comment]
See BannerCallback

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
