### ISSUE TITLE
cmd/go: Generate type has no method on type redefine

### ISSUE THREAD

**Issue by RelicOfTesla** [golang/go#55010]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.3 windows/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

```golang


type TestT[T any] struct {
	V T
}

func (TestT[T]) Hello1() {
	fmt.Println("hello")
}

type TestInt1 TestT[int]
type TestInt2 TestT[int]
type TestInt3 = TestT[int]

func TestGoType(t *testing.T) {
	var (
		v1 TestInt1
		v2 TestInt2
		v3 TestInt3
		v4 TestT[int]
	)
	v1.Hello1() // v1.Hello1 undefined (type TestInt1 has no field or method Hello1)
	v2.Hello1() // v2.Hello1 undefined (type TestInt2 has no field or method Hello1)
	v3.Hello1()
	v4.Hello1()
	v3 = v4
	//v1 != v2
}



```

### What did you expect to see?

Support call method.

### What did you see instead?
undefined (type TestInt1 has no field or method Hello1)

**Comment by seankhliao** [comment]
Like all `type` declarations, methods are cleared out.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
