### ISSUE TITLE
affected/package: bug in io pipe not closing/ending

### ISSUE THREAD

**Issue by da-tai** [golang/go#55029]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

```
uname -a
Linux ubuntu 4.4.0-210-generic #242-Ubuntu SMP Fri Apr 16 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ram/.cache/go-build"
GOENV="/home/ram/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/ram/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ram/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/snap/go/9951"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/snap/go/9951/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1310836824=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

I created a TCP Proxy using io.copy (which creates a splice). Here is the code.

Proxy TCP Server - https://pastebin.com/iAcFjmV1
Regular TCP Server - https://pastebin.com/V6AN7atV

When using telent to port 8080, the proxy starts and everything typed in the telnet will be returned. After 10 seconds, the connection drop to the proxy but you can see there is one message/packet lost.

Proxy Logs - https://prnt.sc/u76C3KyeXAI3
Telnet Logs - https://prnt.sc/VK9vbmishxi2

### What did you expect to see?

I expected to see `s` in the logs in the proxy.go

### What did you see instead?

You can see that the proxy ends at the end of when 0 is used in Telnet. 's' is then sent from the Telnet but it's not seen in the proxy.go as shown in the screenshot. 'd' 'f' etc are then seen in the proxy.go.

**Comment by seankhliao** [comment]
Working as intended, the write for `s` fails, which triggers the error and the end of `io.Copy`.
You need some sort of buffering if you want to ensure writes are successful.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
