### ISSUE TITLE
Lost local library folder (/usr/local/go/src/MyGoLibrary)

### ISSUE THREAD

**Issue by cvq** [golang/go#55034]
After upgrade Golang from 1.19 to 1.19.1 my local library lost ( /usr/local/go/src/MyGoLibrary).
Please help to fix. Thank you.
### What version of Go are you using (`go version`)?

<pre>
$ go version 
1.19.1
</pre>

### Does this issue reproduce with the latest release?

Error loading workspace: You are outside of a module and outside of $GOPATH/src. If you are using modules, please open your editor to a directory in your module. If you believe this warning is incorrect, please file an issue: https://github.com/golang/go/issues/new.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
MacOS/amd64
</pre></details>

### What did you do?
upgrade from 1.19 to 1.19.1

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
