### ISSUE TITLE
x/tools/gopls: ignore line directives

### ISSUE THREAD

**Issue by findleyr** [golang/go#55043]
From a  discussion with @pjweinb and @adonovan:

The existence of line directives causes gopls all sorts of problems, because it means that there are two potentially valid source positions for a token.Pos, and it's not always clear which is correct in context. It also means that we need to access multiple files from operations that would otherwise be local to a single file. This has been a source of historical (and in all likelihood ongoing) bugs.

This issue records an outcome from that discussion: we should ignore line directives internally to gopls (in particular, being careful to call `token.File.PositionFor` instead of `token.File.Position`). If this causes usability issues in e.g. CGo programs, we should address those issues individually. For example, we could perform a post-processing pass on diagnostics that duplicates them to their mapped positions.

CC @golang/tools-team

**Comment by adonovan** [comment]
We could even offer an operation that jumps the cursor to the image of the current position through any applicable //line mapping.

**Comment by kortschak** [comment]
https://go.dev/cl/439115 is marked as having addressed this (with a digit transpose). Should this be closed?

**Comment by pjweinb** [comment]
not quite yet. 457656 is still open

**Comment by adonovan** [comment]
It's fine to close this issue since @pjweinb your CL addressed it. My CL 457656 is now just the some follow-up simplifications to location processing (with more to follow).
