### ISSUE TITLE
macOS Monterey 12.6 go build ld: warning: -no_pie is deprecated when targeting new OS versions

### ISSUE THREAD

**Issue by ghj1976** [golang/go#55058]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.1 darwin/amd64go 
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/guohongjun/Library/Caches/go-build"
GOENV="/Users/guohongjun/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/guohongjun/Documents/MyCodes/mygocodes/pkg/mod"
GONOPROXY="dianpingoa.com"
GONOSUMDB="dianpingoa.com"
GOOS="darwin"
GOPATH="/Users/guohongjun/Documents/MyCodes/mygocodes"
GOPRIVATE="dianpingoa.com"
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.19.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/guohongjun/Documents/MyCodes/sankuaigocodes/src/sankuai/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hp/_v5x9cvd5fvf_0k3q00t9_7h0000gp/T/go-build3638380680=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
macOS Monterey 12.6
<img width="586" alt="image" src="https://user-images.githubusercontent.com/3283196/190029273-50596549-e81b-4261-a93d-f040ef1ee714.png">
Xcode Version 14.0 (14A309)
<img width="802" alt="image" src="https://user-images.githubusercontent.com/3283196/190029414-62cc8ea2-44d9-44fb-8ef1-6fcc33b513e3.png">

<pre>
% go build  
# sankuai/zcm/daily
ld: warning: -no_pie is deprecated when targeting new OS versions
</pre>
<img width="482" alt="image" src="https://user-images.githubusercontent.com/3283196/190029564-12ee0f8e-8b9a-4b63-86e1-9dd39741981c.png">

**Comment by ghj1976** [comment]
这是 github.com/mattn/go-sqlite3 的bug

**Comment by mikesmitharoo** [comment]
Happening to me too

**Comment by lindianfeng** [comment]
happening to me too

**Comment by lggomezsf** [comment]
I haven't updated yet to run into this but cannot get a clear output on the `ld -v` to get the exact version:

```shell
@(#)PROGRAM:ld  PROJECT:ld64-764
BUILD 11:22:55 Apr 28 2022
configured to support archs: armv6 armv7 armv7s arm64 arm64e arm64_32 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em
LTO support using: LLVM version 13.1.6, (clang-1316.0.21.2.5) (static support for 28, runtime is 28)
TAPI support using: Apple TAPI version 13.1.6 (tapi-1316.0.7.3)
```

As of [2.39](https://sourceware.org/binutils/docs-2.39/ld.html#index-position-dependent-executables) the -no-pie field isn't deprecated but this is GNU ld so I guess it's a misomer.

I haven't done a manual link to verify but my guess is that the warning is getting propagated from [the ld call](https://github.com/golang/go/blob/d3660e8ef8adf91462d0be382a1ed8e696f0ee37/src/cmd/link/internal/ld/lib.go#L1492-L1496). The relevant darwin/arm64 logic for the params is [here](https://github.com/golang/go/commit/d3660e8ef8adf91462d0be382a1ed8e696f0ee37#diff-12cc6da4d4e7e3c99b7cd3fc668861b7448180c2b96523e80058db138cfd13f2) although I don't know how should the linker frontend proceed with this

**Comment by Emixam23** [comment]
Sam over here :(

**Comment by cherrymui** [comment]
See also #54482 . Although it has some discussion about another issue, but there are already some discussion about this. Closing as a dup. Thanks.

Also note that this is a _warning_, not an _error_. The build should still succeed and the generated program should work. (Although it affects some tests that checks build output.)

**Comment by duvis-alejandro** [comment]
I don't know if this can help, however, after upgrading to MacOs Monterrey 12.6 I started getting the warning message
`ld: warning: -no_pie is deprecated when targeting new OS versions`

In itself this shouldn't be a problem, when I run a test for a single file it shows the warning but runs the tests normally, just as I would expect.
![image](https://user-images.githubusercontent.com/92595398/190252135-0382a3a1-ee62-46db-a6f6-36069ed0535f.png)


However, when I try to run all the tests of the application, the warning message is taken as an error, the command used is the following:
`/usr/local/go/bin/go test -json -race ./...`

And the result obtained is:
![Failed test](https://user-images.githubusercontent.com/92595398/190251039-2112c626-d2ae-40e0-8b17-ffd74c9fc7f5.png)

**Comment by ollolollollooloo** [comment]
its only a warning but its annoying, how do we disable it?

**Comment by ZekeLu** [comment]
@ollolollollooloo See https://github.com/golang/go/issues/54482#issuecomment-1251124908

**Comment by nicoarguello** [comment]
Pudieron resolver este inconveniente ```ld: warning: -no_pie is deprecated when targeting new OS versions```?

**Comment by fujie-xiyou** [comment]
golang版本升级到1.18.8 或者1.19.3 即可解决
Upgrade the version of golang to 1.18.8 or 1.19.3 to solve the problem
