### ISSUE TITLE
I can't install goleng on my computer, i5, media master m.2 1tb, OS win 10 interprise LTSC - Message: Installation directory must be on a local hard drive - I don't know what to do, please help!!!! !!!!x/website:

### ISSUE THREAD

**Issue by edsonjplima** [golang/go#55053]

**Comment by edsonjplima** [comment]
I can't install goleng on my computer, i5, media master m.2 1tb, OS win 10 interprise LTSC - Message: Installation directory must be on a local hard drive - I don't know what to do, please help!!!! !!!!

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
