### ISSUE TITLE
cmd/objdump: does not decode `VPUNPCK*` AVX2 instructions

### ISSUE THREAD

**Issue by Jorropo** [golang/go#55061]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.20-a813be86df Tue Sep 13 17:43:40 2022 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/hugo/.cache/go-build"
GOENV="/home/hugo/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/hugo/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/hugo/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/home/hugo/Documents/Scripts/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/hugo/Documents/Scripts/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel go1.20-a813be86df Tue Sep 13 17:43:40 2022 +0000"
GCCGO="gccgo"
GOAMD64="v3"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2806241209=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```console
go/src$ go tool asm cmd/asm/internal/asm/testdata/amd64enc.s
go/src$ go tool objdump amd64enc.o | grep amd64enc.s:9975
```

### What did you expect to see?

```
  amd64enc.s:9975	0x12088			c4e1316813		VPUNPCKHBW (BX), X9, X2
```

### What did you see instead?

```
  amd64enc.s:9975	0x12088			b168			MOVL $0x68, CL				
  amd64enc.s:9975	0x1208a			13c4			ADCL SP, AX
```

**Comment by randall77** [comment]
This is definitely a duplicate, at least in spirit, of #48584. The x86 disassembler needs some modernization. I'll close this issue in favor of that other one, but anyone fixing the disassembler should consider the examples in both issues.
