### ISSUE TITLE
affected/package: math/big incompatible change in Rat.SetString()

### ISSUE THREAD

**Issue by halmai** [golang/go#55060]
There seems to be an incompatible change between go `v1.19` and `v1.18`

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.6 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOVERSION="go1.18.6"
GOAMD64="v1"
</pre></details>

### What did you do?

I ran this program (https://go.dev/play/p/NbxEgJJ0Vl_B):

```
package main

import (
	"fmt"
	"math/big"
)

func main() {
	x := big.Rat{}
	y, _ := x.SetString("0")
	fmt.Printf("%+v %+v\n", x, y)
}
```

### What did you expect to see?

I wanted to see the same result in v1.19 as in v 1.18.

### What did you see instead?

In v1.18: `{a:{neg:false abs:[]} b:{neg:false abs:[]}} 0/1`
In v1.19: `{a:{neg:false abs:[]} b:{neg:false abs:[1]}} 0/1`

**Comment by ianlancetaylor** [comment]
Dup of #50944?

**Comment by halmai** [comment]
Yes, it seems to be. Thanks, I close this one.
