### ISSUE TITLE
encoding/csv: fails to parse "a"b,c as two fields (with or w/o LazyQuotes)

### ISSUE THREAD

**Issue by sebnyberg** [golang/go#55069]
### Go version

go1.19 linux/amd64

### What did you do?

```go
r := csv.NewReader(strings.NewReader(`"a"b,c`))
r.LazyQuotes = true
fields, _ := r.Read()
```

### What did you expect to see?
Two parsed fields: `"a"b` and `c`

### What did you see instead?

A single field: `a"b,c`

**Comment by sebnyberg** [comment]
Actually, on second thought, this makes sense. Closing the issue.

**Comment by seankhliao** [comment]
Duplicate of #24422
