### ISSUE TITLE
x/pkgsite: package removal request for FKLC/WhatsAppToDiscord and fklc/whatsapptodiscord

### ISSUE THREAD

**Issue by FKLC** [golang/go#55087]
### What is the path of the package that you would like to have removed?
github.com/FKLC/WhatsAppToDiscord
github.com/fklc/whatsapptodiscord
 
 
 
### Are you the owner of this package?
Yes

 
### What is the reason that you could not retract this package instead?
I don't know what might have caused the second package to exist in the first place, and don't know how to remove it. For the first package, I tried retracting but I believe it failed because it was under another branch. So, now I can't retract it without changing the main branch, which I don't want to as I moved the whole codebase to JS.

**Comment by jamalc** [comment]
Done.
