### ISSUE TITLE
x/vuln: GetByModule for a local source client breaks standard library pages on pkgsite

### ISSUE THREAD

**Issue by jamalc** [golang/go#55088]
### What did you do?

Ran golang.org/x/pkgsite/cmd/pkgsite with `GO_DISCOVERY_VULN_DB="file://<vulndb_mock>"

### What did you expect to see?

No errors on standard library pages.

### What did you see instead?

<img width="1314" alt="Screen Shot 2022-09-15 at 11 08 19 AM" src="https://user-images.githubusercontent.com/18269441/190459927-06bf8a0a-d724-4ef5-b405-1cb8c910452a.png">

**Comment by zpavlinovic** [comment]
I believe `GetByModule` is obsolete now. Is this issue still present?

**Comment by zpavlinovic** [comment]
The issue seems to be gone. The pkgsite has its own vuln db client that handles this well now.
