### ISSUE TITLE
flag: Error wrapping is missing from the flag package

### ISSUE THREAD

**Issue by VoyTechnology** [golang/go#55097]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/voy/.go/bin"
GOCACHE="/Users/voy/Library/Caches/go-build"
GOENV="/Users/voy/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/voy/.go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/voy/.go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.19.1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.19.1/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.19.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/voy/.go/src/REDACTED/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/var/folders/sj/5vkqw5217xn221ywb9d95bzc0000gn/T/go-build832936302=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

https://go.dev/play/p/SVo8u-vFr3T

### What did you expect to see?

No output as the underlying error is the same.

### What did you see instead?

The errors do not match as the error returned from `Value.Set` is not wrapped using `%w` in `(*FlagSet).parseOne`

https://github.com/golang/go/blob/36760ca9fd3eaf2c79efef48e533b66da6c542bd/src/flag/flag.go#L1088

**Comment by ianlancetaylor** [comment]
That's not how `errors.Is` works.  `errors.Is` doesn't report whether an error prints the same.  It reports whether the error is the same.  `errors.Is` will never report true when called with an error returned from the flag package and an error that you've defined yourself.  See the docs for `errors.New`: "Each call to New returns a distinct error value even if the text is identical."

**Comment by VoyTechnology** [comment]
Hi ianlancetaylor, thank you for your response. I am aware that the `errors.Is` does not compare the error string representation. The problem is that the error returned by `Set` is not wrapped in the error chain by the `flag` package. As shown in

https://github.com/golang/go/blob/36760ca9fd3eaf2c79efef48e533b66da6c542bd/src/flag/flag.go#L1088

I would expect that the error was wrapped by using `%w` rather than converted into a string using `%v`.

**Comment by D1CED** [comment]
Consider opening a new issue requesting that the flag package shall return a new kind of error in case a `flag.Value.Set` returns an error so that one is able to inspect it.

**Comment by ianlancetaylor** [comment]
Today I can't see any reason for the flag package to use `%w`, because the wrapped error is not exported.

**Comment by seankhliao** [comment]
There are cases like [`flag.Func`](https://pkg.go.dev/flag#FlagSet.Func) where the user can return an error that's later surfaced through `flag.Parse`.
Wrapping those errors would allow users to test for their own validation errors.

**Comment by tsuna** [comment]
Isn't the code sample posted by OP on the Go Playground another example of a user-controller error type returned eventually through `flag.Parse()`?
