### ISSUE TITLE
x/crypto/chacha20: not compatible with OpenSSL

### ISSUE THREAD

**Issue by pedroalbanese** [golang/go#55095]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.3 windows/386
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=386
set GOBIN=
set GOCACHE=C:\Users\0wner\AppData\Local\go-build
set GOENV=C:\Users\0wner\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\0wner\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\0wner\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_386
set GCCGO=gccgo
set GO386=sse2
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=H:\PGMM\RSASigner\RSASigner\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\cygwin\tmp\go-build582847026=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
```go
	var iv []byte
	iv = make([]byte, 24)
	var nonce [24]byte
	if *vector != "" {
		iv, _ = hex.DecodeString(*vector)
		copy(nonce[:], iv)
	} else {
		fmt.Fprintf(os.Stderr, "IV= %x\n", nonce)
	}
	cypher, _ := chacha20.NewUnauthenticatedCipher(key1, nonce[:])
	cypher.XORKeyStream(buf[:n], buf[:n])

	if _, err := os.Stdout.Write(buf[:n]); err != nil {
		log.Fatal(err)
	}
```

### What did you expect to see?

I expect it work like OpenSSL compatible.

### What did you see instead?

Incompatibility, I cannot decrypt message encrypted with OpenSSL

Thanks in advance.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by pedroalbanese** [comment]
I'm reporting a bug. CHACHA20 is not working properly. Look at https://github.com/pedroalbanese/rsasigner, it's almost full compatible with OpenSSL, except Chacha20.

**Comment by ianlancetaylor** [comment]
Please show us a complete standalone test case that demonstrates the problem.  Thanks.

**Comment by pedroalbanese** [comment]
Thanks for consideration.

```go
package main
import (
	"crypto/rand"
	"encoding/hex"
	"flag"
	"fmt"
	"crypto/sha256"
	"golang.org/x/crypto/pbkdf2"
	"golang.org/x/crypto/chacha20"
	"io"
	"log"
	"os"
)

	var iter = flag.Int("i", 1024, "Iterations. (for PBKDF2)")
	var key = flag.String("k", "", "128-bit key to Encrypt/Decrypt.")
	var pbkdf = flag.String("p", "", "PBKDF2.")
	var salt = flag.String("s", "", "Salt. (for PBKDF2)")
	var vector = flag.String("iv", "", "Initialization vector. (for symmetric encryption)")

func main() {
    flag.Parse()

        if (len(os.Args) < 2) {
	fmt.Println("Usage of",os.Args[0]+":")
        flag.PrintDefaults()
        os.Exit(1)
        }

	var keyHex string
	var prvRaw []byte
	if *pbkdf != "" {
	prvRaw = pbkdf2.Key([]byte(*pbkdf), []byte(*salt), *iter, 32, sha256.New)
	keyHex = hex.EncodeToString(prvRaw)
	} else {
	keyHex = *key
	}
	var key []byte
	var err error
	if keyHex == "" {
		key = make([]byte, 32)
		_, err = io.ReadFull(rand.Reader, key)
		if err != nil {
                        log.Fatal(err)
		}
		fmt.Fprintln(os.Stderr, "Key=", hex.EncodeToString(key))
	} else {
		key, err = hex.DecodeString(keyHex)
		if err != nil {
                        log.Fatal(err)
		}
		if len(key) != 32 {
                        log.Fatal(err)
		}
	}
	var nonce []byte
	nonce = make([]byte, 24)
	var iv []byte
	iv = make([]byte, 24)
	if *vector != "" {
		iv, _ = hex.DecodeString(*vector)
		copy(nonce[:], iv)
	} else {
		fmt.Fprintf(os.Stderr, "IV= %x\n", nonce[:])
	}
	ciph, _ := chacha20.NewUnauthenticatedCipher(key, nonce)
	buf := make([]byte, 64*1<<10)
	var n int
	for {
		n, err = os.Stdin.Read(buf)
		if err != nil && err != io.EOF {
                        log.Fatal(err)
		}
		ciph.XORKeyStream(buf[:n], buf[:n])
		if _, err := os.Stdout.Write(buf[:n]); err != nil {
                        log.Fatal(err)
		}
		if err == io.EOF {
			break
		}
	}
        os.Exit(0)
}
```
I expected the commands to be compatible (except for some workaround done in OpenSSL itself)
```sh
./thistool -key $256bitkey < Plaintext.ext > Ciphertext.ext
openssl enc -d -chacha20 -iv 00 -in Ciphertext.ext -out Plaintext.ext
```

But I don't understand how the nonce is composed in OpenSSL:
https://www.openssl.org/docs/man1.1.1/man3/EVP_chacha20_poly1305.html

**Comment by seankhliao** [comment]
Your nonce size is incorrect. Please refer to the documentation for [chacha20](https://pkg.go.dev/golang.org/x/crypto/chacha20)

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by pedroalbanese** [comment]
Not. It doesn't work if I try to shorten the length. What's the correct nonce?

**Comment by pedroalbanese** [comment]
Oh, I get it. Thanx very much.

**Comment by pedroalbanese** [comment]
Hi again. Would you reopen this please? It's not compatible with OpenSSL-PHP.

```php
<?php
$plaintext = 'SECRET MESSAGE';
$key = '820qufp5820qufp5820qufp5820qufp5';
$nonce = '000000000000';
$r = openssl_encrypt(
    $plaintext,
    'chacha20-poly1305',
    $key, 
    $options=1,
    $nonce
);

echo base64_encode($r);

echo "<br>";

$t = openssl_decrypt(
    $r,
    'chacha20-poly1305',
    $key, 
    $options=1,
    $nonce
);
echo $t;
?>
```

Result:
6N/wRtwz/VhHOfyepNk=
SECRET MESSAGE

Equivalent to:
```go
	out := aead.Seal(nil, nonce, msg, nil)
	fmt.Printf("%s", out[:len(msg)])
```

If I don't trunk the output, the result is:
6N/wRtwz/VhHOfyepNnnYKagDMd4Gk9HPSv2y1EWros=

But there is no way to decrypt it in Go as the ciphertext has no tag:
```go
	out, err := aead.Open(nil, nonce, msg, nil)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%s", out)
```

Result:
`chacha20poly1305: message authentication failed`

Help please!
