### ISSUE TITLE
affected/package: 

### ISSUE THREAD

**Issue by 467892746** [golang/go#55102]
### What version of Go are you using (`go version`)?

<pre>
$ go version 
go1.18.1 darwin/arm64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN="/Users/biwentao/Desktop/go/bin"
GOCACHE="/Users/biwentao/Library/Caches/go-build"
GOENV="/Users/biwentao/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/biwentao/Desktop/go/pkg/mod"
GONOPROXY=""
GONOSUMDB="gitlab.ustock.cc/*"
GOOS="darwin"
GOPATH="/Users/biwentao/Desktop/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="0"
GOMOD="/Users/biwentao/Desktop/go/src/demo/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/k5/l5y3fv9n27zfjrd9jwmp4p8c0000gn/T/go-build1830639654=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
func main() {
	a := "222"
	fmt.Println(json.Valid([]byte(a)))
}

### What did you expect to see?
false

### What did you see instead?
true

**Comment by mengzhuo** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

------------
FYI: JSON spec https://www.json.org/json-en.html

**Comment by 467892746** [comment]
Thank you for your answer
