### ISSUE TITLE
x/vuln: respect GOPRIVATE env variable

### ISSUE THREAD

**Issue by ArtAndreev** [golang/go#55105]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.1 darwin/arm64
</pre>

### Does this issue reproduce at the latest version of golang.org/x/vuln?
Yes, reproduced on latest `govulncheck` from `go install golang.org/x/vuln/cmd/govulncheck@latest`.
Actually, not from tool, but codebase.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/ar.s.andreev/Library/Caches/go-build"
GOENV="/Users/ar.s.andreev/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/ar.s.andreev/go/pkg/mod"
GONOPROXY="" # removed because it's sensitive information.
GONOSUMDB="" # removed because it's sensitive information.
GOOS="darwin"
GOPATH="/Users/ar.s.andreev/go"
GOPRIVATE="" # removed because it's sensitive information.
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/f5/tvc95lsd2tgfjkb489878h_40000gq/T/go-build534434502=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
Walked through code in `https://github.com/golang/vuln/blob/master/cmd/govulncheck/main.go`, searched for usage of `GOPRIVATE` env variable and found nothing.

### What did you expect to see?
Expected this tool to respect `GOPRIVATE` env variable and not run checks of dependencies with domains in this variable, like checksum checks. Don't want to exposure domains and URL-structure of deps.

From `go help environment`:

```
GOPRIVATE, GONOPROXY, GONOSUMDB
        Comma-separated list of glob patterns (in the syntax of Go's path.Match)
        of module path prefixes that should always be fetched directly
        or that should not be compared against the checksum database.
        See https://golang.org/ref/mod#private-modules.
```

### What did you see instead?
Nothing, but it's interesting to listen for opinion on this situation. Should the tool scan all deps or not? Will be there a way to exclude some dependencies?

**Comment by cherrymui** [comment]
cc @golang/vulndb

**Comment by zpavlinovic** [comment]
Currently, the only information about user code that is transmitted over the network are user module paths for which there *exist known vulnerabilities* in the (specified) vulnerability database: we do not query the db with a module path for which the db does not have any vulnerability info.

We haven't added support for `GOPRIVATE` at this moment as it is unlikely that a private package would have vulnerability info in a database. (Even if it did, such information would be already public if the database is public, or if the database is private then this information would hence stay private.)

Do you see scenarios where `GOPRIVATE` would be useful here? Would supporting it increase your confidence or should we perhaps document this explicitly?

@rsc @julieqiu

**Comment by ArtAndreev** [comment]
Thanks for the answer, sorry, I thought my package names are sent to compare with entries in db. I'll close the issue.
