### ISSUE TITLE
x/pkgsite: package removal request for `ktbs.dev/teler`

### ISSUE THREAD

**Issue by dwisiswant0** [golang/go#55118]
### What is the path of the package that you would like to have removed?

`ktbs.dev/teler`
 
 
### Are you the owner of this package?

Yes.
 
### What is the reason that you could not retract this package instead?

I want to delete all the versions listed instead of retracting them one by one. For several reasons:

1. Custom domain is not configured (and maintained) anymore, and
2. Replace it with a new custom domain.

Having trouble doing reason(2), because https://pkg.go.dev/teler.app is redirected to an old custom domain.

```console
$ go list -m -json -v teler.app@latest
{
	"Path": "teler.app",
	"Version": "v1.2.2",
	"Query": "latest",
	"Time": "2021-04-01T23:06:52Z",
	"Dir": "/home/dw1/.go/pkg/mod/teler.app@v1.2.2",
	"GoMod": "/home/dw1/.go/pkg/mod/cache/download/teler.app/@v/v1.2.2.mod",
	"GoVersion": "1.14"
}
```

But [deps.dev listing it](https://deps.dev/go/teler.app) correctly.

On a special note, I don't want to change the codebase directory structure like moving files under the new `/v2` path.

**Comment by seankhliao** [comment]
note teler.app needs a major version suffix in its module path (but not necessarily directory structure) as its tags are v2+

**Comment by dwisiswant0** [comment]
> note teler.app needs a major version suffix in its module path (but not necessarily directory structure) as its tags are v2+

Can you please elaborate? So that means I have to change the module path (to `teler.app/v2`) in `go.mod`?

**Comment by seankhliao** [comment]
No.
Removing it from pkgsite only hides the generated documentation.
If `go install` doesn't work now, it still won't work if we hide the documentation. It's a configuration issue on your site and/or module.

**Comment by dwisiswant0** [comment]
Currently not working because I think the version is not listed on `pkg.go.dev`. Correct me if I'm wrong.

**Comment by seankhliao** [comment]
pkg.go.dev does not affect the `go` tool

**Comment by dwisiswant0** [comment]
Given such evidence, I will close this issue until I can resolve the current situation. Thanks, @seankhliao & @findleyr.
