### ISSUE TITLE
testing: T.Setenv can be called after T.Parallel

### ISSUE THREAD

**Issue by noi** [golang/go#55128]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="$HOME/.cache/go-build"
GOENV="$HOME/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="$HOME/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="$HOME/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="$HOME/dev/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1463438795=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

`T.Setenv` will panic if it be called after `T.Parallel` but it can be called in `T.Run`.

Sample code:
https://go.dev/play/p/54VhJKYpb_q

### What did you expect to see?

I think it should panic even in `T.Run`.

### What did you see instead?

Those tests become flaky without panic.

# Others

I'm trying to fix this issue now.

**Comment by ianlancetaylor** [comment]
I'm not sure what is wrong with calling `t.Setenv` in a function passed to `t.Run`.  It would be wrong if the function calls `t.Parallel`, but if it doesn't, it should work reliably.  It may not do what you want, but it shouldn't be flaky.  Do I misunderstand?

**Comment by ZekeLu** [comment]
I think noi@ means that a sub test is flaky when it calls `t.Setenv` while its parent has called `t.Parallel`. This looks plausible.

**Comment by ianlancetaylor** [comment]
Ah, yes, I see.  We need to walk the `parent` list or something.

**Comment by noi** [comment]
Thank you for your replying!
I'm sorry for confusing you by my bad English. ZekeLu is right, I wanted to say like that.

I'm trying to fix this issue by passing `isAncestorParalell` to sub test in `t.Run`.

**Comment by noi** [comment]
I sent my changes, so I would appreciate it if you could review it when you have time🙇‍♂️
