### ISSUE TITLE
affected/package: flag

### ISSUE THREAD

**Issue by jagottsicher** [golang/go#55135]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GOHOSTARCH="amd64"
GOHOSTOS="linux"

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jens/.cache/go-build"
GOENV="/home/jens/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/jens/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jens/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.19"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.19/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build450993853=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
If am using the follwing flag type to create a flag

```
flag.StringVar(&outputTypes, "o", "", "Outputs desired output formats.")
flag.StringVar(&outputTypes, "output", "", "Outputs desired output formats.")
flag.Parse()
fmt.Println(outputTypes)
```
to create a string to check different output conditons for.

One of my possible output conditions shall be indicated by a "#" character, but if I handle over something like 
```myapp -o #abc``` outputTypes does not contain "#" after parsing. What you can do though is ```myapp -o "#abc"``` or ```myapp -o \#abc```or ```myapp -o abc\#abc``` which gives me ```"#abc"```, respectively ```"abc#abc"``` like intended. 

It seems that I cannot use a "#" character as an argument. That a pity. I hoped that in an UTF-8 based language I could use even some runes in strings, but ```flag.Parse()``` strips it out if it the first (unescaped) character in the String followed to my flag.

see above.

### What did you expect to see?
That the "#" character is usable as an argument

### What did you see instead?
it is removed from my argument after calling ```flag.Parse()```

**Comment by seankhliao** [comment]
that would appear to be an issue with your shell rather than flag: https://go.dev/play/p/5jTx1rOVsyK

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
