### ISSUE TITLE
go_bootstrap install -i cmd/asm cmd/cgo cmd/compile cmd/link: signal: segmentation fault (core dumped)

### ISSUE THREAD

**Issue by austgl** [golang/go#55130]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.15.6 linux/loong64   from yum 

go1.18.6 linux/loong64  download from http://ftp.loongnix.cn/toolchain/golang/go-1.18/

</pre>

### Does this issue reproduce with the latest release?

[root@localhost go]# cat VERSION
go1.19.1

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="loong64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="loong64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="http://goproxy.loongnix.cn:3000"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_loong64"
GOVCS=""
GOVERSION="go1.18.6"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/code/go/src/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -mabi=lp64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3486517463=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

build from source

```
[root@localhost go]# cat /etc/os-release
NAME="Kylin Linux Advanced Server"
VERSION="V10 (Tercel)"
ID="kylin"
VERSION_ID="V10"
PRETTY_NAME="Kylin Linux Advanced Server V10 (Tercel)"
ANSI_COLOR="0;31"

[root@localhost go]# uname -r
4.19.90-23.19.v2101.a.ky10.loongarch64
```

[root@localhost src]# GOOS=linux GOARCH=loong64 ./bootstrap.bash
#### Building ../../go-linux-loong64-bootstrap

Building Go cmd/dist using /usr/local/go. (go1.18.6 linux/loong64)
Building Go toolchain1 using /usr/local/go.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
go tool dist: FAILED: /home/code/go-linux-loong64-bootstrap/pkg/tool/linux_loong64/go_bootstrap install -i cmd/asm cmd/cgo cmd/compile cmd/link: signal: segmentation fault (core dumped)

**Comment by austgl** [comment]
build on x86_64, copy targets to loongArch64

[root@localhost home]# file go-linux-loong64-bootstrap/bin/go
go-linux-loong64-bootstrap/bin/go: ELF 64-bit LSB executable, *unknown arch 0x102* version 1 (SYSV), statically linked, Go BuildID=uVYcJluYFcI01dyI-PA6/YCwsg_kAJAugQRIvByC8/St44trjPdhKO640fppum/0ba-V4lmHdRxf6iSOW_3, with debug_info, not stripped
[root@localhost home]# ./go-linux-loong64-bootstrap/bin/go version
segmentation fault (core dumped)

**Comment by cherrymui** [comment]
See https://go.dev/doc/go1.19#loong64
> Minimum kernel version supported is 5.19.

> Note that most existing commercial Linux distributions for LoongArch come with older kernels, with a historical incompatible system call ABI. Compiled binaries will not work on these systems, even if statically linked. Users on such unsupported systems are limited to the distribution-provided Go package.


You'll need to update the kernel, or use distribution-provided Go package.
