### ISSUE TITLE
access: may-forge-author

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#55132]
I'd like my Gerrit account (filippo@) to be added to the may-forge-author group.

I mostly need it for:

1. uploading code mostly authored by others and provided to me to be submitted under the terms of the CLA, or under a source-only notice license like BSD-1 (for example, I am trying to upload Thomas Pornin's crypto/rsa backend without claiming credit in the Author line)
2. fixing commit messages of other people's CLs before submitting them
3. mailing cherry-picks 

I'm well aware of the CLA requirements and implications of mailing other people's code :)

**Comment by ianlancetaylor** [comment]
CC @golang/release

**Comment by FiloSottile** [comment]
Friendly ping :) I am blocked on this also to upload a revision of https://go.dev/cl/326012 (which then I'd ask the original author to +1).

**Comment by cherrymui** [comment]
Hi Filippo,

The permission is granted. Thanks.

See also #55841 . We are also considering give may-forge-author permission to approves, and update the git-codereview tool to prevent misuse. Thanks.
