### ISSUE TITLE
x/tools/go/analysis/unitchecker: export output JSON schema and include SuggestedFixes

### ISSUE THREAD

**Issue by lfolger** [golang/go#55138]
Currently the [unitchecker](https://pkg.go.dev/golang.org/x/tools/go/analysis/unitchecker) offers a JSON (via the `-json` flag).

The schema of the JSON output is not documented and the output does not contain `SuggestedFixes`. I propose to document the schema and include `SuggestedFixes` in the output. I think it is reasonable to export the position information as filename and byte offsets for start and end into the file. The end is exclusive (similar to the AST representation).

The implementation for the JSON output is [here](https://cs.opensource.google/go/x/tools/+/refs/tags/v0.1.12:go/analysis/internal/analysisflags/flags.go;l=355-359). Exporting and extending it should solve this issue.

I have not yet checked in detail if this is used by other code as well.
It might make sense to flag protect the new output to not break existing tools that rely on the output without `SuggestedFixes`.

**Comment by cherrymui** [comment]
cc @timothy-king @zpavlinovic

**Comment by timothy-king** [comment]
Including SuggestedFixes in json output seems like a good idea to me.

If possible it would be preferable to not add another flag, but we should do at least a preliminary investigations of tools that use `-json` to confirm whether these are backwards compatible. Based on what the investigation finds, we can choose whether we can safely add a flag or not.
