### ISSUE TITLE
gccgo: can not handle multiple return values

### ISSUE THREAD

**Issue by melonedo** [golang/go#55141]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, tested on GCC 12.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/melonedo/.cache/go-build"
GOENV="/home/melonedo/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/melonedo/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/melonedo/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.2"
GCCGO="/usr/bin/gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/melonedo/fuzzTest/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build557955963=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

Run `gccgo issue.go` on code:

```go
// MWE from signature fuzzer
package Checker0

type StructF3S0 struct {
}

func Test3() (r0 complex64, r1 *float32, r2 StructF3S0) {
  // consume some stack space, so as to trigger morestack
  rc0 := complex(float32(-6.1751327e+37),float32(6.408295e+37))
  rc1 := New_0(float32(-3.2629494e+37))
  rc2 := StructF3S0{}
  return rc0, rc1, rc2
  // 0 addr-taken params, 0 addr-taken returns
}

func New_0(i float32)  *float32 {
  x := new( float32)
   *x = i
  return x
}
```

### What did you expect to see?

The code should be compiled.

### What did you see instead?

gccgo crashes:

```
go1: internal compiler error: in convert_tree, at go/go-gcc.cc:2693
Please submit a full bug report, with preprocessed source.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
```

**Comment by cherrymui** [comment]
cc @ianlancetaylor @thanm

**Comment by ianlancetaylor** [comment]
This is a dup of https://gcc.gnu.org/PR101994.  This is fixed on tip and on the GCC 12 branch.  Thanks for reporting it.
