### ISSUE TITLE
affected/package: Go build failed to compile in go1.19.1 but working 1.18 and dev branch

### ISSUE THREAD

**Issue by subokuma** [golang/go#55240]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.1 linux/amd64
go version go1.19.1 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes, I am using Go1.19.1 and it is reproducible. But it is working in Go 1.18 of The Go Playground.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
As it is failed in  Go Playground. I hope that go env should be required.
</pre></details>

### What did you do?

I was working on design using generic feature where I faced this issue. So I wrote dummy and small code to depict  it. 
https://go.dev/play/p/b8U8IoeQGWw

### What did you expect to see?
It should run and print output=2

### What did you see instead?
./prog.go:48:24: internal compiler error: method M1 on struct {} not found

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new

Go build failed.

**Comment by cuonglm** [comment]
Duplicated of https://github.com/golang/go/issues/54225
