### ISSUE TITLE
cmd/compile: internal compiler errors in test flakes

### ISSUE THREAD

**Issue by rsc** [golang/go#55257]
```
#!watchflakes
default <- `: internal compiler error:` && date < "2023-07-25"
```

This issue collects build dashboard flakes due to internal compiler errors.

**Comment by bcmills** [comment]
> [2022-08-31 21:10 linux-ppc64-sid-buildlet go@52d9e7f5](https://build.golang.org/log/f329080009702b9158c2f520dc2da09679df665b)

That particular crash bears a strong resemblance to #54906.

**Comment by prattmic** [comment]
https://github.com/golang/go/issues/55257#issuecomment-1252358190 is #54906, closing.

Watchflakes will reopen with new default matching crashes.

**Comment by bcmills** [comment]
This issue seems needlessly broad — it went from what seems to be an issue specific to `linux/ppc64xx` (possibly #60368?) to some new ICE (#61570).

I don't see evidence in the issue comments that this umbrella issue is being actively triaged, so I'm going to add a date cap and close it as stale.
