### ISSUE TITLE
cmd/compile: internal compiler error building k8s

### ISSUE THREAD

**Issue by mknyszek** [golang/go#55269]
Build error: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-build-and-push-k8s-at-golang-tip/1572196947165450240

Summary:
```
# k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/core/v1
vendor/k8s.io/client-go/kubernetes/typed/core/v1/event_expansion.go:116:2: internal compiler error: bad live variable at entry of (*events).Search: stringRefUID (type string)
```

Looks like something in the compiler broke between 7db923fe5 and 1eeb257b8, which suggests to me that cf53990	or 4c414c7 are the issue.

CC @golang/compiler

**Comment by mknyszek** [comment]
More specifically: CC @erifan @cherrymui @randall77

**Comment by cuonglm** [comment]
Duplicated of https://github.com/golang/go/issues/55254

**Comment by mknyszek** [comment]
Oh, great, thanks.
