### ISSUE TITLE
go1.16.12: Source release hash doesn't match to the package.

### ISSUE THREAD

**Issue by blorente** [golang/go#55298]
### What version of Go are you using (`go version`)?

This is relevant to go1.16.12

### Does this issue reproduce with the latest release?

No.

### What did you do?

I want to download and hash the available source releases. I queried the public repository:
```
$ curl "https://go.dev/dl/?mode=json&include=all" | jq '.[] | select(.version | contains("go1.16.12")) | .files[] | select(.kind | contains("source"))'
{
  "filename": "go1.16.12.src.tar.gz",
  "os": "",
  "arch": "",
  "version": "go1.16.12",
  "sha256": "2afd839dcb76d2bb082c502c01a0a5cdbfc09fd630757835363c4fde8e2fbfe8",
  "size": 20918701,
  "kind": "source"
}
```

However, if we download the archive and hash it, we get a different sha:
```
$ curl  https://go.dev/dl/go/go1.16.12.src.tar.gz | shasum -a 256
b16e15764b8bc06c5c3f9f19bc8b99fa48e7894aa5a6ccdad65da49bbf564793
```

### What did you expect to see?

I would have expected these has to be the same.

### What did you see instead?

They weren't.

**Comment by seankhliao** [comment]
Your url is incorrect, that's a 404 response.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
