### ISSUE TITLE
x/vuln/cmd/govulncheck: avoid mutating go/build.Default context

### ISSUE THREAD

**Issue by hyangah** [golang/go#55305]
In https://github.com/golang/vuln/blob/d9be10b6cc846585ded9197e3a20ea2661da49f7/cmd/govulncheck/main.go#L34
`-tags` flag mutates `go/build.Default.BuildTags`.
In old days, adjusting the `go/build` default context was necessary to minimize confusions stem from differences in local/external build contexts. However, with `golang.org/x/tools/go/packages` this is no longer necessary in most cases.

Don't mutate `go/build.Default` context, but pass the info to `go/packages` load configuration.

cc @zpavlinovic

**Comment by zpavlinovic** [comment]
Fixed [here](https://go-review.git.corp.google.com/c/vuln/+/432915).
