### ISSUE TITLE
cmd/link: source paths in binary distribution assume installation to specific directory

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#5533]
<pre>Here to demonstrate:

$ mkdir ~/tmp
$ cd ~/tmp
$ zcat /tmp/go1.1.linux-386.tar.gz | tar x
$ export GOROOT=~/tmp/go
$ export PATH=$PATH:$GOROOT/bin/
$ mkdir a
$ cd a
$ cat &gt;a.go
package main

import (
	&quot;fmt&quot;
)

func main() {
	fmt.Printf(&quot;Hello\n&quot;)
}
$ go build a.go
$ gdb a                                                                  
GNU gdb (Gentoo 7.3.1 p2) 7.3.1                                                         
     
Copyright (C) 2011 Free Software Foundation, Inc.                                       
     
License GPLv3+: GNU GPL version 3 or later &lt;<a href="http://gnu.org/licenses/gpl.html&gt">http://gnu.org/licenses/gpl.html&gt</a>;     
           
This is free software: you are free to change and redistribute it.                      
     
There is NO WARRANTY, to the extent permitted by law.  Type &quot;show copying&quot;    
               
and &quot;show warranty&quot; for details.                                              
               
This GDB was configured as &quot;i686-pc-linux-gnu&quot;.                               
               
For bug reporting instructions, please see:                                             
     
&lt;<a href="http://bugs.gentoo.org/&gt">http://bugs.gentoo.org/&gt</a>;...                                                      
           
Reading symbols from /home/brainman/tmp/a/a...done.                                     
     
warning: /usr/local/go/src/pkg/runtime/runtime-gdb.py (referenced in
.debug_gdb_scripts): No such file or directory                                          
                              
(gdb) br main.main                                                                      
     
Breakpoint 1 at 0x8048c00: file /home/brainman/tmp/a/a.go, line 5.                      
     
(gdb) r                                                                                 
     
Starting program: /home/brainman/tmp/a/a                                                
     
                                                                                              
Breakpoint 1, main.main () at /home/brainman/tmp/a/a.go:5                               
     
5       func main() {                                                                   
     
(gdb) s                                                                                 
     
6               fmt.Printf(&quot;Hello\n&quot;)                                         
               
(gdb)                                                                                   
     
fmt.Printf (format=..., a=..., n=405032960, err=...)                                    
     
    at /usr/local/go/src/pkg/fmt/print.go:222                                                 
222     /usr/local/go/src/pkg/fmt/print.go: No such file or directory.                  
     
        in /usr/local/go/src/pkg/fmt/print.go                                                 
(gdb) q                                                                                 
     
A debugging session is active.                                                          
     
                                                                                              
        Inferior 1 [process 17239] will be killed.                                            
                                                                                              
Quit anyway? (y or n) y                                                                 
     
$                                                                        

We could stress that only /usr/local/go destination is supported. But this does not work
on windows, because our windows installer allows other path (then c:\go) to be specified.

Perhaps we could change our linker, so it rewrites these paths correctly.

Alex</pre>

**Comment by kormat** [comment]
I have (presumably) the same problem on linux: i installed go in `~/opt/go`, set `$GOROOT` to that dir, but `go build` still hardcodes the wrong `.debug_gdb_scripts` path into binaries (`/usr/local/go/src/runtime/runtime-gdb.py`).

**Comment by davecheney** [comment]
@kormat if you are building Go from source, it is recommended to build Go in it's final destination. If that is not possible you should set `GOROOT_FINAL` to the destination, then after building Go move it to that location taking care to not touch any timestamps.

**Comment by kormat** [comment]
@davecheney - i'm just using the tarball directly from https://golang.org/dl/

**Comment by davecheney** [comment]
@kormat in that case I appolgise, I have no workaround for the gdb issue.

**Comment by rsc** [comment]
I prepared a CL to use $GOROOT for the location of the gdb script. That will help with finding the gdb script. The source line information for the standard library will still point at /usr/local/go but maybe that's not as big a deal.
