### ISSUE TITLE
panic: runtime error: racy use of timers

### ISSUE THREAD

**Issue by SNGxx** [golang/go#55340]
### What version of Go are you using (`go version`)?

<pre>
$ go version
v1.14.7
</pre>

### Does this issue reproduce with the latest release?
not sure

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY="******"
GONOSUMDB="******"
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/usr/local/go/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build206275195=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
```golang

```

### What did you expect to see?
no panic

### What did you see instead?
```
panic: runtime error: racy use of timers

goroutine 3014322 [running]:
time.stopTimer(0xc00f1a80f8, 0x2e45a20)
	/usr/local/go/src/runtime/time.go:224 +0x2b
time.(*Timer).Stop(...)
	/usr/local/go/src/time/sleep.go:78
net/http.(*http2clientConnReadLoop).cleanup(0xc010682fa8)
	/usr/local/go/src/net/http/h2_bundle.go:8210 +0x10d
net/http.(*http2ClientConn).readLoop(0xc004fb1380)
	/usr/local/go/src/net/http/h2_bundle.go:8180 +0x122
created by net/http.(*http2Transport).newClientConn
```

**Comment by seankhliao** [comment]
go1.14 is no longer supported.
