### ISSUE TITLE
x/pkgsite: package removal request for [https://pkg.go.dev/github.com/haseeb-apimatic/go-core-lib]

### ISSUE THREAD

**Issue by haseeb-apimatic** [golang/go#55342]
### What is the path of the package that you would like to have removed?
https://pkg.go.dev/github.com/haseeb-apimatic/go-core-lib
 
 
 
### Are you the owner of this package?
Yes.

 
### What is the reason that you could not retract this package instead?
I have published it with version 1 but the current version is pre-release one.

**Comment by mvdan** [comment]
Did you try retracting the version, like the docs say?

**Comment by haseeb-apimatic** [comment]
> Did you try retracting the version, like the docs say?

As the Docs says that we can retracting the version with the latest version but I don't want to publish a new version as my current package is published with the stable version v1.0.0 but currently the package is unstable.

**Comment by seankhliao** [comment]
removing it will only permanently hide the docs for all versions, it won't change anything else about the versioning

**Comment by haseeb-apimatic** [comment]
> removing it will only permanently hide the docs for all versions, it won't change anything else about the versioning

So how can I Hide the current published version. As I don't want to publish a version of v1.0.1. I Only want to change the current version to v0.0.1. Is there is any possible way to hide the Current version(v1.0.0) and make live package of (v0.0.1). So that when any one want to use this package it would get v0.0.1 instead of v1.0.0

**Comment by mvdan** [comment]
You can't do that. Once you have released a v1, that ship has sailed. You could release a v1.0.1 that retracts both v1.0.0 and v1.0.1, and then you cannot use those version names again in the future. The latest version would then go back to whatever v0 tag exists.

**Comment by haseeb-apimatic** [comment]
> You can't do that. Once you have released a v1, that ship has sailed. You could release a v1.0.1 that retracts both v1.0.0 and v1.0.1, and then you cannot use those version names again in the future. The latest version would then go back to whatever v0 tag exists.

Hello @mvdan @seankhliao i have studied and tested about retracting versioning. That's a great support but my problem cannot be resolved. So I want to permanently remove the package that I have published.

**Comment by haseeb-apimatic** [comment]
@mvdan @seankhliao @gopherbot is anyone is working on my query. As I want to remove the documentation of this package, if it is permanently hidden or removed then I am ok with that. I request you all to resolve my query as soon as possible.
