### ISSUE TITLE
spec: document interface satisfaction more explicitly

### ISSUE THREAD

**Issue by dsymonds** [golang/go#5570]
<pre><a href="http://golang.org/ref/spec#Interface_types">http://golang.org/ref/spec#Interface_types</a> does not clearly spell out the requirements
for a type to implement an interface. It should.</pre>

**Comment by griesemer** [comment]
The Go 1.18 spec has now a section on what it means to implement an interface (see the end of the section on [Interface types](https://go.dev/ref/spec#Interface_types)). Closing.
