### ISSUE TITLE
x/crypto/ssh: data race if session.Stdout and Stderr are the same writer

### ISSUE THREAD

**Issue by davecheney** [golang/go#5582]
<pre><a href="https://golang.org/cl/9711043/">https://golang.org/cl/9711043/</a> identified that the ssh package does not handle
the case where the Stdout and Stderr point to the same writer, as in the case of the
CombinedOutput() helper function.

This was worker around by introducing a blocking wrapper, however the proper solution is
to handle this common case the way os/exec handles it.</pre>

**Comment by odeke-em** [comment]
@hanwen @davecheney @rsc any thoughts on this bug?

**Comment by hanwen** [comment]
I'm pretty this is obsolete, but if you can repro a race, I can look into fixing it.
