### ISSUE TITLE
net/http: ReadRequest can leak pool entry

### ISSUE THREAD

**Issue by ruz** [golang/go#55835]
https://github.com/golang/go/blob/2551324cd01b295915c10c6d3d06625676401610/src/net/http/request.go#L1041

Line mentioned above should be a few lines earlier before first return.

**Comment by bradfitz** [comment]
Want to send a change moving it to its own defer a few lines up? (keeping the existing one where it's at)

**Comment by cherrymui** [comment]
cc  @neild
