### ISSUE TITLE
manifest not word yet

### ISSUE THREAD

**Issue by BlackSinny** [golang/go#55847]
## 1. Question
when i run exe, i want it has uac right ,i run last comment as this blog but not use. After go build ,the exe app do have Administrator authority yet
** https://github.com/mozey/run-as-admin **
## 2. Execute the following operation
1. go get github.com/akavel/rsrc
2. edit manifest file 
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
<assemblyIdentity
    version="9.0.0.0"
    processorArchitecture="x86"
    name="app.exe"
    type="win32"
/>
<description>Golang example of using a manifest file to prompt "Run as administrator"</description>
<trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
        <requestedPrivileges>
            <requestedExecutionLevel level="requireAdministrator" uiAccess="false"/>
        </requestedPrivileges>
    </security>
</trustInfo>
</assembly>
```
3. rsrc -manifest app.exe.manifest -o app.syso
4. go build -o app.exe

## 3. My Env
> goversion : go version go1.15.13 windows/amd64
  equipment version : windows10 Professional version

**Comment by seankhliao** [comment]
Sounds like a question about windows rather than Go.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by ChugunovRoman** [comment]
@BlackSinny Did you find solution on your issue?
