### ISSUE TITLE
syscall: unix Sendto panic if nil Sockaddr provided

### ISSUE THREAD

**Issue by nathanaelle** [golang/go#55845]
### What version of Go are you using (`go version`)?

1.19.1

### Does this issue reproduce with the latest release?

yes.

### What operating system and processor architecture are you using (`go env`)?

ubuntu linux 22.04 on amd64 

### What did you do?

syscall.Sendto(socket, buffer, flag, nil)

### What did you expect to see?

as specified in https://linux.die.net/man/2/sendto 

```
send(sockfd, buf, len, flags);

is equivalent to

sendto(sockfd, buf, len, flags, NULL, 0); 
```

### What did you see instead?

we can see in https://cs.opensource.google/go/go/+/refs/tags/go1.19.1:src/syscall/syscall_unix.go;l=445

```
func Sendto(fd int, p []byte, flags int, to Sockaddr) (err error) {
	ptr, n, err := to.sockaddr()
	if err != nil {
		return err
	}
	return sendto(fd, p, flags, ptr, n)
}
```

the `nil` situation for `to` is not tested, thus a panic() occurs.

### Suggestion

is it possible to add a test to avoid a panic() when `to` is set to `nil` like in SendmsgN() ( see: https://cs.opensource.google/go/go/+/refs/tags/go1.19.1:src/syscall/syscall_unix.go;l=400 ) ?

this issue may also impact :
– SendtoInet4
– SendtoInet6
– SendmsgNInet4
– SendmsgNInet6

**Comment by tklauser** [comment]
I think it would make sense to add the check for `syscall.Sendto`. The other functions (`SendtoInet4`, `SendtoInet6`, `SendmsgNInet4`, `SendmsgNInet6`) are defined in `internal/syscall/unix` and are only used internally by Go. As far as I can see all call sites pass a non-nil `Sockaddr`, so I'm not sure we'd need the check there.

/cc @ianlancetaylor
