### ISSUE TITLE
build: the struct embeds the inteface 

### ISSUE THREAD

**Issue by SimFG** [golang/go#55850]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.6 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
the detail code
```
type A interface {
	A()
	//OtherA()
}

type a struct {
}

func (a *a) A() {
	fmt.Println("a")
}

func (a *a) OtherA() {
	fmt.Println("otherA")
}

type B interface {
	A
	Other()
}

type b struct {
	A
}

func (b *b) Other() {
	fmt.Println("other")
}

func PrintAB(b B) {
	b.A()
	//b.OtherA()
	b.Other()
}

func main() {
	PrintAB(&b{A: &a{}})
}
```
 build the code, output:
``` 
./main.go:44:10: cannot use &b{…} (value of type *b) as type B in argument to PrintAB:
        *b does not implement B (missing A method)

```
The editor does not prompt syntax errors, but this code doesn't compile. If I change the `A` method to the `OtherA` in  the `A` interface, it can compile successfully.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by ianlancetaylor** [comment]
The type `*b` has a field named `A`.  That is, `(*b).A` refers to the field `A`.  It's true that that that field has a method `A` that could be promoted to the type `*b`, but the field `A` shadows the method `A`.

In general we do not use the issue tracker for questions about the language.  If you want to discuss this further, please use a forum; see https://go.dev/wiki/Questions.  Thanks.

**Comment by SimFG** [comment]
@ianlancetaylor thanks your answer >v<
