### ISSUE TITLE
affected/package: compress/lzw

### ISSUE THREAD

**Issue by zergon321** [golang/go#55852]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/zergon321/.cache/go-build"
GOENV="/home/zergon321/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE="gitlab.com/zergon321/*"
GOMODCACHE="/home/zergon321/go/pkg/mod"
GONOPROXY="gitlab.com/zergon321/*"
GONOSUMDB="gitlab.com/zergon321/*"
GOOS="linux"
GOPATH="/home/zergon321/go"
GOPRIVATE="gitlab.com/zergon321/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2387926288=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I wanted to build functionality to compress and decompress an **RGBA** image. The [play example](https://go.dev/play/p/V0__0htvSI4) contains random bytes instead.

### What did you expect to see?

Equal hashes for the source data and the decompressed data.

### What did you see instead?

The hashes are always not equal.

```plaintext
Source hash: d99d9bfb59cf1bda57898fe86073795c5a0337dff9a676f5804c533397a0dc86
Decompressed hash: 800c6574b79bd1b6404b9745285d826e5ca38ce030ea714264271b343e35881e
```

**Comment by ZekeLu** [comment]
> It is the caller's responsibility to call Close on the WriteCloser when finished writing.

Applying the following change to your example will make it work.

```diff
diff --git a/main.go b/main.go
index 1f237c8..8b56e4b 100644
--- a/main.go
+++ b/main.go
@@ -29,6 +29,7 @@ func CompressLZWOrderLSBLitWidth8(in []byte) ([]byte, error) {
        return nil, err
    }
 
+   writer.Close()
    return buffer.Bytes(), nil
 }
```

**Comment by mdlayher** [comment]
See above, closing.
