### ISSUE TITLE
 xml.Marshal Changed  string "\f/" to "�/"

### ISSUE THREAD

**Issue by yangzong18** [golang/go#55869]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by mengzhuo** [comment]
Could you submit an example in https://go.dev/play?

**Comment by ZekeLu** [comment]
Duplicate of #46048
