### ISSUE TITLE
affected/package: Go test reflect.DeepEqual causes the slice memory to change

### ISSUE THREAD

**Issue by bygo** [golang/go#55862]
### What version of Go are you using (`go version`)?

<pre>
$ go 1.19
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
</pre></details>

### What did you do?

go test https://github.com/bygo/x/blob/6b0da02b427b24be47cab8d63f428130bac6a1ad/collection_test.go#L347

want := [[1 2 3] [4 5]]
The `want` slice directly becomes [[824634181024 2] [4 5]]

But sometimes, it's sometimes normal
My guess is a memory error

You can also check the results of the Github Action
https://github.com/bygo/x/actions/runs/3121123189/jobs/5062222442

### What did you expect to see?

collection_test.go:396: Collect().Chunk() = [[1 2 3] [4 5]], want [[1 2 3] [4 5]]

### What did you see instead?
```sh
=== RUN   TestCollection_Chunk/Int_1
=== RUN   TestCollection_Chunk/Int_2
=== RUN   TestCollection_Chunk/Int_3
Error:     collection_test.go:396: Collect().Chunk() = [[1 2 3] [4 5]], want [[824634181024 2] [4 5]]
=== RUN   TestCollection_Chunk/Int_4
=== RUN   TestCollection_Chunk/Int_5
=== RUN   TestCollection_Chunk/Int_6
```

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.

**Comment by ZekeLu** [comment]
It seems that this is a valid issue. I have attached the reduced demo to the end of this comment.

My environment: `go version go1.19 linux/amd64`.

```shell
$ go test x_test.go -count 10000 -run TestFoo
--- FAIL: TestFoo (0.00s)
    --- FAIL: TestFoo/1 (0.00s)
        x_test.go:24: tt.want has been changed to: 0
--- FAIL: TestFoo (0.00s)
    --- FAIL: TestFoo/1 (0.00s)
        x_test.go:24: tt.want has been changed to: 0
FAIL
FAIL	command-line-arguments	0.138s
FAIL

```
It can be reproduced on tip (`go1.20-a0441c7ae3 linux/amd64`) only when `GOEXPERIMENT=nounified` is set.

```go
// x_test.go
package x

import (
	"testing"
)

func TestFoo(t *testing.T) {
	type Args[T comparable] struct {
		name  string
		items []int
		want  int
	}

	tt := Args[int]{
		name:  "1",
		items: []int{1},
		want:  1,
	}
	t.Run(tt.name, func(t *testing.T) {
		items := make([]int, len(tt.items))
		copy(items, tt.items)
		if tt.want != 1 {
			t.Errorf("tt.want has been changed to: %v", tt.want)
		}
	})
}

func TestBar(t *testing.T) {
	type Args[T comparable] struct {
		name string
	}

	tt := Args[int]{
		name: "2",
	}
	t.Errorf("%v", tt)
}
```

**Comment by bygo** [comment]
T.run is an asynchronous method

So I redefined the closure , redefined it to fix the problem

But 824634181024 is the address where "want" is "want" memory

It's weird. I've never changed it

**Comment by bygo** [comment]
@ZekeLu 
Your memory seems to have also changed

**Comment by ZekeLu** [comment]
Yes. It's weird. If I changed `Args` in `TestBar` to another name (for example, `Arg`), then the issue can not be reproduced.

**Comment by ZekeLu** [comment]
I believe this is a duplicate of #54456.
