### ISSUE TITLE
x/mobile: wiki page commands don't work

### ISSUE THREAD

**Issue by TheBicPen** [golang/go#55867]
https://github.com/golang/go/wiki/Mobile
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Probably.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/alex/.cache/go-build"
GOENV="/home/alex/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/alex/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/alex/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.18"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.18/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1987326445=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Went through the guide on the wiki page: https://github.com/golang/go/wiki/Mobile
```
$ gomobile init
gomobile: command not found
```
had to do `echo 'export PATH=$PATH:~/go/bin' >> ~/.bashrc && . ~/.bashrc` (from https://github.com/golang/go/issues/21818 comments). Didn't see this documented anywhere.

```
$ go get -d golang.org/x/mobile/example/bind/...
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```

Tried a whole bunch of things:
```
$ go install golang.org/x/mobile/example/bind/...
go: warning: "golang.org/x/mobile/example/bind/..." matched no packages
$ go install golang.org/x/mobile/example/bind/
go: 'go install' requires a version when current directory is not in a module
        Try 'go install golang.org/x/mobile/example/bind/@latest' to install the latest version
$ go install golang.org/x/mobile/example/bind/@latest
go: golang.org/x/mobile/example/bind/@latest: argument must be a clean package path
```
Still not sure what to do at this point.

### What did you expect to see?

I expected the commands in the wiki page to work correctly out of the box.

### What did you see instead?

They did not work out of the box, and no documentation is provided for how to solve the issues encountered. Just a poor experience for new users overall.

**Comment by changkun** [comment]
According to the provided messages, it seems that gomobile is not yet installed on your environment, try:

```
go install golang.org/x/mobile/cmd/gomobile@latest
```

This is described in https://github.com/golang/go/wiki/Mobile#tools
