### ISSUE TITLE
`os.Chdir` returns to the first working directory path even if different symlink path is specified

### ISSUE THREAD

**Issue by knaka** [golang/go#55866]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

macOS Catalina 10.15.7

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/knaka/Library/Caches/go-build"
GOENV="/Users/knaka/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/knaka/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/knaka/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/knaka/sdk/go1.19"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/knaka/sdk/go1.19/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8k/rhxxw8ds12x1p6z6nxjgn5y40000gn/T/go-build2319953163=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

If the target directory of `os.Chdir` is the first working directory of the program, while the paths differ because of symlink, the program returns the the first path (first working directory).

```console:
$ ls -ld /tmp/foo_dir /tmp/bar_dir
lrwxr-xr-x  1 knaka  wheel   7  9 26 02:20 /tmp/bar_dir -> foo_dir
drwxr-xr-x  3 knaka  wheel  96  9 26 02:21 /tmp/foo_dir
$ pwd
/tmp/foo_dir
$ cat chdir.go
package main

import (
  "fmt"
  "os"
)

func main() {
  s, _ := os.Getwd()
  fmt.Println(s)
  if err := os.Chdir("/tmp/bar_dir"); err != nil {
    panic(err)
  }
  s, _ = os.Getwd()
  fmt.Println(s)
}
$ go run chdir.go
/tmp/foo_dir
/tmp/foo_dir
```

### What did you expect to see?

It chdir-s to the path the argument specifies.

### What did you see instead?

It returns to the first working directory path in which the process started.

**Comment by ZekeLu** [comment]
Maybe that's how `os.Getwd` is designed.

> If the current directory can be reached via multiple paths (due to symbolic links), Getwd may return any one of them.

See https://pkg.go.dev/os@go1.19.1#Getwd.

**Comment by robpike** [comment]
This is how chdir works in Unix, sorry. Working as intended, and the only way it can on Unix. But if you're interested in what can be done about it, at least in theory, see https://9p.io/sys/doc/lexnames.html

**Comment by knaka** [comment]
Oh, it is not the problem of `os.Chdir` but of `os.Getwd`. I got it.

If `os.Getwd` always returns symlink evaluated path, it is OK. But the implementation returns symlink path if current working directory is `$PWD` , the directory in which the program started, and it is symlink path.

```console:
$ ls -ld /tmp/foo_dir /tmp/bar_dir
lrwxr-xr-x  1 knaka  wheel   7  9 26 02:20 /tmp/bar_dir -> foo_dir
drwxr-xr-x  3 knaka  wheel  96  9 26 02:21 /tmp/foo_dir
$ pwd
/tmp/bar_dir
$ cat chdir.go
$ cat chdir.go
package main

import (
  "fmt"
  "os"
)

func main() {
  s, _ := os.Getwd()
  fmt.Println(s)
  if err := os.Chdir("/tmp/foo_dir"); err != nil { panic(err) }
  s, _ = os.Getwd()
  fmt.Println(s)
}
$ go run chdir.go
/tmp/bar_dir
/tmp/bar_dir
```

Unsetting `$PWD` solved my problem.

```
$ cat chdir.go
package main

import (
  "fmt"
  "os"
)

func main() {
  if err := os.Unsetenv("PWD"); err  != nil { panic(err) }
  s, _ := os.Getwd()
  fmt.Println(s)
  if err := os.Chdir("/tmp/foo_dir"); err != nil { panic(err) }
  s, _ = os.Getwd()
  fmt.Println(s)
}
$ go run chdir.go
/private/tmp/foo_dir
/private/tmp/foo_dir
```

**Comment by robpike** [comment]
I remember complaining about it using $PWD, and losing the argument.
