### ISSUE TITLE
proposal: Go 2: Do-While Extension to For-Loops

### ISSUE THREAD

**Issue by assyrianic** [golang/go#55868]
### Author background

- **Would you consider yourself a novice, intermediate, or experienced Go programmer?** --Intermediate.
- **What other languages do you have experience with?** --C, C++, and Python.

### Related proposals

- **Has this idea, or one like it, been proposed before?** --Not that I've seen.
- **Does this affect error handling?** --Possibly but shouldn't have too much of an effect.
- **Is this about generics?** --No.

### Proposal

- **What is the proposed change?** --Extending the for-loop in Go to also be able to function as a do-while loop.

```go
// traditional for-loop.
for i := 0; i < n; i++ {
    
}

// do-while-style for-loop.
for {
    
} if i < n /// <-- newline/semicolon inserted to end it.
```

- **Who does this proposal help, and why?** --Provide a simpler mechanism for writing a do-while loop.
- **Please describe as precisely as possible the change to the language.** --This would change the syntax grammar for the for-statement construct.
- **What would change in the language spec?** --The `ForStmt` syntax.
- **Please also describe the change informally, as in a class teaching Go.**

At the end of a for-loop statement, an optional `if` and a conditional expression following the `if` would allow the for-loop to act similar to a do-while loop. The conditional would work as an "after-check" when the code block of the for-loop finished an iteration.

- **Is this change backward compatible?** --Yes.
- **Orthogonality: how does this change interact or overlap with existing features?** --It does not.
- **Is the goal of this change a performance improvement?** --No.

### Costs

- **Would this change make Go easier or harder to learn, and why?** --Debatebly Easier as the Go For-loop would be the all encompassing loop.
- **What is the cost of this proposal? (Every language change has a cost).** --Needing to work on any parsing such as the go/ast library.
- **How many tools (such as vet, gopls, gofmt, goimports, etc.) would be affected?** --Any tool that has to analyze/manipulate the source code.
- **What is the compile time cost?** --Insignificant.
- **What is the run time cost?** --None.

**Comment by rittneje** [comment]
You can already essentially do this today:
```go
for {
    // ...
    if i < n {
        break
    }
}
```
