### ISSUE TITLE
x/pkgsite: package removal request for github.com/pedroalbanese/edgetk

### ISSUE THREAD

**Issue by pedroalbanese** [golang/go#55882]
### What is the path of the package that you would like to have removed?
https://pkg.go.dev/github.com/pedroalbanese/edgetk
 
 
 
### Are you the owner of this package?
Yes!

 
### What is the reason that you could not retract this package instead?
This folders do not exist anymore and I need the name
Please remove my old package:
https://pkg.go.dev/github.com/pedroalbanese/edgetk?utm_source=godoc

Thanks in advance!

**Comment by hyangah** [comment]
> This folders do not exist anymore and I need the name

Can you elaborate this further? 
Package removal is only to hide the package from pkg.go.dev. The package will still be available from proxy.golang.org, sum.golang.org and other module proxies, so you won't be able to publish already published versions again.

**Comment by pedroalbanese** [comment]
Will it work if I start from the latest version? I mean, releasing version 1.2.4, will the directories present in pkg.go.dev/github.com/pedroalbanese/edgetk and previous versions disappear?

**Comment by pedroalbanese** [comment]
hi?

**Comment by hyangah** [comment]
> Will it work if I start from the latest version? I mean, releasing version 1.2.4, will the directories present in pkg.go.dev/github.com/pedroalbanese/edgetk and previous versions disappear?

You will need to publish a new version (v1.2.4+) with a go.mod that specifies retraction. 
See https://go.dev/ref/mod#go-mod-file-retract
Once done, they will disappear from the pkgsite at least.

**Comment by pedroalbanese** [comment]
But this way I would have to specifie retraction in all go.mod of all versions from this one?

**Comment by pedroalbanese** [comment]
Listen, there is documentation referring to the pkg.go.dev website at https://pkg.go.dev/about#adding-a-package. On this page there is a section called "Removing a package" which says:

"If you would like to hide versions of a module on pkg.go.dev, as well as from the go command, you should retract them. Retracting a module version involves adding a retract directive to your go.mod file and publishing a new version.See the Go blog post New module changes in Go 1.16 and the modules reference for details.

If you cannot retract your module, you can file a request for the pkgsite team to remove your package." As I did three days ago.

Well, I need to remove the previous versions of my application and add the latest one. I can't do either one. Note that I fulfill all the requirements for "file a request" here, as the documentation says, ie: I need my module removed and I can't do it by my own means. I don't speak English and I didn't expect to have to explain myself when removing a module that belongs to me, I hope I don't have to beg or wait a week for this.

I humbly request that versions prior to 1.2.3 be removed from the server, and version 1.2.4 added.

**Comment by pedroalbanese** [comment]
Here it exists:
https://goreportcard.com/report/github.com/pedroalbanese/edgetk

**Comment by hyangah** [comment]
Sorry for all the trouble. 

I see v1.2.5 was published so it should be the latest. Proxy also agrees.  https://proxy.golang.org/github.com/pedroalbanese/edgetk/@latest

But for some reason, pkgsite fails to process it.

@golang/tools-team @jamalc can you help fogure out why pkgsite doesn't recognize these new versions?

**Comment by jamalc** [comment]
An issue with usage of the exclude directive in your go.mod file is preventing processing. The [exclude directive](https://go.dev/ref/mod#go-mod-file-exclude) requires a module path and module version.

**Comment by pedroalbanese** [comment]
@jamalc What if it don't have a version? Like v0.0.0-something? I don't know what the versions are..

**Comment by pedroalbanese** [comment]
Now I managed to update in godoc, but the directories are still there even excluding in go.mod.

**Comment by jamalc** [comment]
The submodules only relationship to github.com/pedroalbanese/edgetk is that they share a prefix. The exclude directive has no effect on the pkgsite UI for displaying submodules. 

If your goal is to keep the module [github.com/pedroalbanese/edgetk](https://pkg.go.dev/github.com/pedroalbanese/edgetk) visible and hide the submodules at github.com/pedroalbanese/edgetk/*  we can exclude the paths below from ever being visible on pkg.go.dev. Hiding these modules no affect on what's available via the module proxy. In the future if you decide to use these paths for new packages in the github.com/pedroalbanese/edgetk module, we'll have to un-exclude them. Documentation for these modules will become unavailable on the site. Should I proceed with hiding these paths? 

github.com/pedroalbanese/edgetk/c509
github.com/pedroalbanese/edgetk/ccm
github.com/pedroalbanese/edgetk/cfb8
github.com/pedroalbanese/edgetk/eax
github.com/pedroalbanese/edgetk/ecb
github.com/pedroalbanese/edgetk/groestl
github.com/pedroalbanese/edgetk/jh
github.com/pedroalbanese/edgetk/ocb
github.com/pedroalbanese/edgetk/pragma
github.com/pedroalbanese/edgetk/pragma128
github.com/pedroalbanese/edgetk/scrypt
github.com/pedroalbanese/edgetk/scrypt2
github.com/pedroalbanese/edgetk/sha128
github.com/pedroalbanese/edgetk/threefish

**Comment by pedroalbanese** [comment]
Yes, please hide them. Leave only the cmd directory. Thanks

**Comment by jamalc** [comment]
Done.

**Comment by pedroalbanese** [comment]
Thank you very much!
