### ISSUE TITLE
x/website: Documentation supports code highlighting

### ISSUE THREAD

**Issue by SherlockGy** [golang/go#55886]
### What is the URL of the page with the issue?

https://go.dev/doc/tutorial/database-access
https://go.dev/doc/effective_go
etc.
 
### What did you expect to see?
 
 code highlighting for Docs and Tutorials

**Comment by mvdan** [comment]
Also https://github.com/golang/go/issues/40952 and https://github.com/golang/go/issues/52198. I think we should have a single umbrella issue for all of these.

**Comment by SherlockGy** [comment]
The Go Playground and the website front page are also need code highlighting
<img width="1298" alt="image" src="https://user-images.githubusercontent.com/29522658/193034150-9a586db3-6227-4197-b4fb-860a262a7b03.png">
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/29522658/193034208-c632814e-c40f-4a64-bd3e-e2d93b53e874.png">

**Comment by hyangah** [comment]
Closing. Let's centralize the discussion in the umbrella issue.
