### ISSUE TITLE
affected/package: exec, why output nothing?

### ISSUE THREAD

**Issue by billcoding** [golang/go#55887]
### What version of Go are you using (`go version`)?

<pre>
go version go1.18.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Administrator\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Administrator\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.18.5
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\Administrator\AppData\Local\Temp\go-build107211989=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
```go
package main

import (
	"bufio"
	"fmt"
	"os/exec"
)

func main() {
	cmd := exec.Command("mtr", "-p", "-c", "10", "www.qq.com")
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		fmt.Println(err)
	}
	if err := cmd.Start(); err != nil {
		fmt.Println(err)
	}
	go func() {
		scr := bufio.NewScanner(stdout)
		for {
			if scr.Scan() {
				fmt.Println(scr.Text())
			}
			if scr.Err() != nil {
				return
			}
		}
	}()
	if err := cmd.Wait(); err != nil {
		fmt.Println(err)
	}
}

```
Output: nothing!!!
But, executed in shell on linux host.
![image](https://user-images.githubusercontent.com/21271780/192467340-a42ca6a4-0b83-442c-918b-364861d7fe22.png)

```go
package main

import (
	"bufio"
	"fmt"
	"os/exec"
)

func main() {
	cmd := exec.Command("ping", "-c", "10", "www.qq.com")
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		fmt.Println(err)
	}
	if err := cmd.Start(); err != nil {
		fmt.Println(err)
	}
	go func() {
		scr := bufio.NewScanner(stdout)
		for {
			if scr.Scan() {
				fmt.Println(scr.Text())
			}
			if scr.Err() != nil {
				return
			}
		}
	}()
	if err := cmd.Wait(); err != nil {
		fmt.Println(err)
	}
}
```
I tried `ping www.qq.com`, seems outputs.

### What did you expect to see?
Data output

### What did you see instead?
Nothing

**Comment by gucio321** [comment]
consider, that there are two outputs of cmd:
- Stdout
- Stderr
some commands otuputs to stderr instead stdout

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by billcoding** [comment]
@gucio321
I tried using Stderr, but the result is the same as Stdout, still no result output.
Strangely, I write similar code in Java to get the result through the stream.
The difference is that Go provides 2 ways to start child processes: Fork/Exec?
But Exec I don't know how to get the result? Can you help me see?

**Comment by christophberger** [comment]
The question has been taken to the [Go Forum](https://forum.golangbridge.org/t/exec-why-output-nothing/28939).

**Comment by zplzpl** [comment]
```

		sp.logBuffer = newLogBuffer(10000000)

		// create a pipe for the output of the command
		stdout, err := sp.cmd.StdoutPipe()
		if err != nil {
			logrus.Infof("Error StdoutPipe: %s", err.Error())
		}
		defer func() {
			_ = stdout.Close()
		}()

		stderr, err := sp.cmd.StderrPipe()
		if err != nil {
			logrus.Infof("Error StderrPipe: %s", err.Error())
		}
		defer func() {
			_ = stderr.Close()
		}()

		var wg sync.WaitGroup

		wg.Add(1)
		go func() {
			defer wg.Done()

			// define a buffer for the output
			buf := make([]byte, 81960)

			// copy the output from the command to the console
			for {

				n, err := stdout.Read(buf)
				if err != nil {
					if err == io.EOF {
						logrus.Infof("Break StdoutPipe")
						break
					} else {
						logrus.Errorf("Error reading from stdout pipe: %s", err)
						continue
					}
				}

				if _, err := sp.logBuffer.Write(buf[:n]); err != nil {
					logrus.Errorf("logBuffer.Write stdout error: %s", err.Error())
				}

			}
		}()

		wg.Add(1)
		go func() {
			defer wg.Done()

			// define a buffer for the output
			buf := make([]byte, 81960)

			// copy the output from the command to the console
			for {

				n, err := stderr.Read(buf)
				if err != nil {
					if err == io.EOF {
						logrus.Infof("Break StderrPipe")
						break
					} else {
						logrus.Errorf("Error reading from stderr pipe: %s", err)
						continue
					}
				}

				if _, err := sp.logBuffer.Write(buf[:n]); err != nil {
					logrus.Errorf("logBuffer.Write stderr error: %s", err.Error())
				}

			}

		}()

		wg.Wait()

		// wait for the command to finish
		err = sp.cmd.Wait()
		sp.run <- err

```

* If the command is executed manually directly, the full output.
* Using golang exec.Command will result in incomplete reading
