### ISSUE TITLE
proposal: Go 2: String interpolation

### ISSUE THREAD

**Issue by xbt573** [golang/go#55894]
### Author background

- **Would you consider yourself a novice, intermediate, or experienced Go programmer?**
Something between novice and intermediate
- **What other languages do you have experience with?**
C#, Python, JS/TS

### Related proposals

- **Has this idea, or one like it, been proposed before?**
#50554
#34174
  - **If so, how does this proposal differ?**
This proposal defines different syntax
- **Does this affect error handling?**
No
- **Is this about generics?**
No

### Proposal

- **What is the proposed change?**
This proposal adds way to interpolate values to string other than `fmt.Printf`, concatenation, or others
- **Who does this proposal help, and why?**
This proposal helps to make interpolation simple and don't remember all %something in `fmt.Printf`
- **Please describe as precisely as possible the change to the language.**
This interpolation use strings, prefixed by hash (`#`) symbol, they converted to normal strings at runtime, because expressions can vary
- **What would change in the language spec?**
Specification will include information about syntax of this string interpolation
- **Is this change backward compatible?**
Yes
- **Show example code before and after the change.**
- **Before**
```go
a := 5
hash := "#"

// Simple output
fmt.Printf("%v\n", a)

// Pad char
fmt.Printf("%-3v\n", hash)
```
- **After**
```go
a := 5
hash := "#"

// You can even not import fmt!
// Simple output
println(#"{a}")

// Pad char (shows optional formatting)
println(#"{[%-3v] hash}")
```
- **Orthogonality: how does this change interact or overlap with existing features?**
This is new feature
- **Is the goal of this change a performance improvement?**
No
### Costs

- **Would this change make Go easier or harder to learn, and why?**
It's makes interpolation in Go easier to learn because of simple syntax
- **What is the cost of this proposal? (Every language change has a cost).**
Implementation of this interpolation
- **How many tools (such as vet, gopls, gofmt, goimports, etc.) would be affected?**
gopls, vet
- **What is the compile time cost?**
Zero
- **What is the run time cost?**
Additional interpolation
- **Can you describe a possible implementation?**
No
- **Do you have a prototype? (This is not required.)**
No

**Comment by ianlancetaylor** [comment]
Thanks.  Closing as dup of #34174 and #50554.
