### ISSUE TITLE
x/pkgsite: Version manager program

### ISSUE THREAD

**Issue by tonycody** [golang/go#55906]
rust
```shell
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```
Can it be like Rust? 
Version Manager can be downloaded directly through one line of shell script, and different versions of go can be managed later through version Manager.
java
```shell
curl -s "https://get.sdkman.io" | bash
```
The Go language also has to download packages and care about which directory it exists in Linux, which is too troublesome. 
Can you make it easier through the Shell script?

**Comment by hyangah** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and [proposals](https://go.dev/s/proposal-process) only.. For questions, see https://github.com/golang/go/wiki/Questions

---

Not exactly like `rustup`, but here is another way to use different versions of go https://go.dev/doc/manage-install.
There are community contributed go version managers like `gvm`, `asdf`, ...
Some IDEs and editor plugins (vscode-go) also provide installation/use of different go versions.

You also may be interested in a currently active discussion topic (https://github.com/golang/go/discussions/55092) that talks about a very different approach for go version management.
