### ISSUE TITLE
affected/package: golang.org/x/tools

### ISSUE THREAD

**Issue by marcelloh** [golang/go#55912]
### What version of Go are you using (`go version`)?

<pre>
go version go1.19.1 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/marcelloh/Library/Caches/go-build"
GOENV="/Users/marcelloh/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/marcelloh/go/pkg/mod"
GONOPROXY="github.com/***secret***"
GONOSUMDB="github.com/***secret***"
GOOS="darwin"
GOPATH="/Users/marcelloh/go"
GOPRIVATE="github.com/***secret***"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/marcelloh/data/go-private/MyProject/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/2j/sl_kv1311vggqj0m8jy3_w7w0000gn/T/go-build1888163313=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

go install golang.org/x/tools@latest

### What did you expect to see?

No error (or a message that looks like an error)

### What did you see instead?
go: golang.org/x/tools@latest: module golang.org/x/tools@latest found (v0.1.12), but does not contain package golang.org/x/tools

**Comment by seankhliao** [comment]
there is no package to install there

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
