### ISSUE TITLE
sync/atomic: Generic type self-reference via atomic.Pointer causes internal compiler error

### ISSUE THREAD

**Issue by dmgard** [golang/go#55938]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes, in go1.19.1, but not in the latest development branch on go.dev/play.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\dmgard\AppData\Local\go-build
set GOENV=C:\Users\dmgard\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\dmgard\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\dmgard\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.19
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\dmgard\GolandProjects\ppool\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\dmgard\AppData\Local\Temp\go-build3267611165=/tmp/go-build -gno-record-gcc-switches
GOROOT/bin/go version: go version go1.19 windows/amd64
GOROOT/bin/go tool compile -V: compile version go1.19
gdb --version: GNU gdb (GDB) 12.1
</pre></details>

### What did you do?
```
package main

import "sync/atomic"

func main() {
	var m Map[StrHasher]
	_ = m
}

type Map[H Hasher] struct {
	ptr atomic.Pointer[Map[H]]
}

func (m *Map[H]) Prehash() {
	var h H
	h.Hash()
}

func (m *Map[H]) Access() {
	m.ptr.Load()
}

type Hasher interface {
	Hash()
}

type StrHasher struct{}

func (st StrHasher) Hash() {}
```

https://go.dev/play/p/-VhHZqDR8Pz

### What did you expect to see?

Nothing, but it should compile.

### What did you see instead?

`$GOROOT/src/sync/atomic/type.go:55:30: internal compiler error: method Hash on struct {} not found`

**Comment by cuonglm** [comment]
Duplicated of #54225.
