### ISSUE TITLE
x/pkgsite: package removal request for - https://pkg.go.dev/github.com/haseeb-apimatic/core-lib-go

### ISSUE THREAD

**Issue by haseeb-apimatic** [golang/go#55933]
### What is the path of the package that you would like to have removed?

https://pkg.go.dev/github.com/haseeb-apimatic/core-lib-go

### Are you the owner of this package?
Yes.

### What is the reason that you could not retract this package instead?

I have published the wrong code with correct version. I don't want to retract it. You can remove it so that I can publish a new package with new name.

**Comment by suzmue** [comment]
Package removal is only to hide the named package from pkg.go.dev (forever). This will just hide the documentation for this package. The package will still be available from proxy.golang.org, sum.golang.org and other module proxies, so you won't be able to publish already published versions again.

To fully [remove your package](https://go.dev/about#removing-a-package) please use the `retract` feature.

If you just want to remove the documentation for this package, please let me know and I can do that for you, but it sounds like what you need is a [retraction](https://go.dev/about#removing-a-package).

**Comment by haseeb-apimatic** [comment]
> Package removal is only to hide the named package from pkg.go.dev (forever). This will just hide the documentation for this package. The package will still be available from proxy.golang.org, sum.golang.org and other module proxies, so you won't be able to publish already published versions again.
> 
> To fully [remove your package](https://go.dev/about#removing-a-package) please use the `retract` feature.
> 
> If you just want to remove the documentation for this package, please let me know and I can do that for you, but it sounds like what you need is a [retraction](https://go.dev/about#removing-a-package).

I want to remove the documentation for this package. There is no issue if it is permanently hidden or removed.

**Comment by suzmue** [comment]
The documentation for [github.com/haseeb-apimatic/core-lib-go](https://pkg.go.dev/github.com/haseeb-apimatic/core-lib-go) has been removed from pkg.go.dev
