### ISSUE TITLE
x/sys/unix: Add `Dup3` on FreeBSD

### ISSUE THREAD

**Issue by dveeden** [golang/go#55935]
### What version of Go are you using (`go version`)?

<pre>
% go version
go version go1.19.1 freebsd/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
% go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/dveeden/.cache/go-build"
GOENV="/home/dveeden/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="freebsd"
GOINSECURE=""
GOMODCACHE="/home/dveeden/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="freebsd"
GOPATH="/home/dveeden/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go119"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go119/pkg/tool/freebsd_amd64"
GOVCS=""
GOVERSION="go1.19.1"
GCCGO="gccgo"
GOAMD64="v2"
AR="ar"
CC="cc"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4147625229=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

`syscall.Dup3()` is available on Linux, but not on FreeBSD. However the syscall seems to be present as indicated on [the `dup3(3)` manpage](https://www.freebsd.org/cgi/man.cgi?query=dup3&sektion=3).

A patch like this might work:
```patch
diff --git a/src/syscall/syscall_freebsd.go b/src/syscall/syscall_freebsd.go
index 0f3912644b..83d338554b 100644
--- a/src/syscall/syscall_freebsd.go
+++ b/src/syscall/syscall_freebsd.go
@@ -179,6 +179,7 @@ func Mknod(path string, mode uint32, dev uint64) (err error) {
 //sys  Close(fd int) (err error)
 //sys  Dup(fd int) (nfd int, err error)
 //sys  Dup2(from int, to int) (err error)
+//sys  Dup3(oldfd int, newfd int, flags int) (err error)
 //sys  Fchdir(fd int) (err error)
 //sys  Fchflags(fd int, flags int) (err error)
 //sys  Fchmod(fd int, mode uint32) (err error)
```

**Comment by dveeden** [comment]
Looks like `dup3()` is a Linux compatibility. See https://docs.freebsd.org/en/books/developers-handbook/x86/#x86-call-numbers
I assume that this means that it should not be included in `syscall`?

```
% grep 'SYS_dup' /usr/include/sys/syscall.h
#define	SYS_dup	41
#define	SYS_dup2	90
% find /usr/src/sys -name syscalls.master -print -exec grep -B1 -A5 'dup3(' {} \;
/usr/src/sys/compat/freebsd32/syscalls.master
/usr/src/sys/kern/syscalls.master
/usr/src/sys/amd64/linux32/syscalls.master
330	AUE_NULL	STD {
		int linux_dup3(
		    l_int oldfd,
		    l_int newfd,
		    l_int flags
		);
	}
/usr/src/sys/amd64/linux/syscalls.master
292	AUE_NULL	STD {
		int linux_dup3(
		    l_uint oldfd,
		    l_uint newfd,
		    l_int flags
		);
	}
/usr/src/sys/arm/linux/syscalls.master
358	AUE_NULL	STD	{
		int linux_dup3(
		    l_int oldfd,
		    l_int newfd,
		    l_int flags
		);
	}
/usr/src/sys/arm64/linux/syscalls.master
24	AUE_NULL	STD	{
		int linux_dup3(
		    l_int oldfd,
		    l_int newfd,
		    l_int flags
		);
	}
/usr/src/sys/i386/linux/syscalls.master
330	AUE_NULL	STD {
		int linux_dup3(
		    l_int oldfd,
		    l_int newfd,
		    l_int flags
		);
	}
```

**Comment by tklauser** [comment]
The `dup3` is Linux-specific and e.g. [NetBSD](https://man.netbsd.org/dup3.2) and [OpenBSD](https://man.openbsd.org/OpenBSD-5.9/dup.2) decided to add it as a syscall too. On FreeBSD it's available as a libc function using `fcntl` with `F_DUP2FD_CLOEXEC`: https://github.com/freebsd/freebsd-src/blob/373ffc62c158e52cde86a5b934ab4a51307f9f2e/lib/libc/gen/dup3.c#L42-L60

We could add a similar `Dup3` implementation for FreeBSD. Though not to the `syscall` package - which is frozen, see its [package level godoc](https://pkg.go.dev/syscall) - but to `golang.org/x/sys/unix` which should be used instead.
