### ISSUE TITLE
os/exec: TestPipeLookPathLeak fails randomly on OS X

### ISSUE THREAD

**Issue by davecheney** [golang/go#5593]
<pre>Darwin builders have started to occasionally fail this test

--- FAIL: TestPipeLookPathLeak (0.02 seconds)
	exec_test.go:169: leaked 4 fds; want ~0
FAIL
FAIL	os/exec	1.083s

Recent failures:
<a href="http://build.golang.org/log/5b9a4be800936ee52a6c00b1b64337ae9d4e1906">http://build.golang.org/log/5b9a4be800936ee52a6c00b1b64337ae9d4e1906</a>
<a href="http://build.golang.org/log/5fa2f5674bc6293bf068689b4df3e3baf96810e1">http://build.golang.org/log/5fa2f5674bc6293bf068689b4df3e3baf96810e1</a></pre>

**Comment by rsc** [comment]
Per #9511, we will not be making any further bug fixes specific to 10.6.
