### ISSUE TITLE
x/vuln: add credit field to OSV reports

### ISSUE THREAD

**Issue by julieqiu** [golang/go#55956]
We currently store the credit field in our YAML reports, but they are not surfaced in the OSV reports.

For example, see https://github.com/golang/vulndb/blob/master/data/reports/GO-2021-0172.yaml#L19 vs https://vuln.go.dev/ID/GO-2021-0172.json.

**Comment by aaqaishtyaq** [comment]
Hey @julieqiu, If no one is assigned on this issue, Can I pick this up?

From the first look, It seems I need to add `Credit` [here](https://github.com/golang/vuln/blob/21a3e98a940a14fb04a1510b073f1f79b321152f/osv/json.go#L191) in  `osv.Entry` and pass `Credit` during `GenerateOSVEntry` [here](https://github.com/golang/vulndb/blob/e38f8c08b387fc77b8a24bcdd03cb3d885bda8e3/internal/database/generate.go#L220).

Anything I missed?

**Comment by aaqaishtyaq** [comment]
Added the CL for the change, Let me know if I missed something. 

Thank you!

**Comment by tatianab** [comment]
Thanks for your contribution, Aaqa!

**Comment by aaqaishtyaq** [comment]
Thank you @tatianab  for helping me throughout the review process.

**Comment by productofgrace1** [comment]
** Yeah attack it was never able to make it in**
