### ISSUE TITLE
x/pkgsite: Proxy protocol `@v/list` endpoint version data structures as json?

### ISSUE THREAD

**Issue by ein-tier** [golang/go#55969]
### What is the URL of the page with the issue?
https://proxy.golang.org
https://go.dev/ref/mod#goproxy-protocol

### What is your user agent?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

### Screenshot

<img width="1379" alt="Screen Shot 2022-09-30 at 2 46 38 PM" src="https://user-images.githubusercontent.com/107634772/193272928-b8b90cbf-deed-4a8f-8864-019fb87f919a.png">

### What did you do?

Make an HTTP GET request to https://proxy.golang.org/github.com/aws/aws-sdk-go-v2/service/lexruntimev2/@v/list

```
curl --location --request GET 'https://proxy.golang.org/github.com/aws/aws-sdk-go-v2/service/lexruntimev2/@v/list'
```

### What did you expect to see?
In the GOPROXY Protocol documentation there are two paragraphs next to the `.../@v/list` endpoint: https://go.dev/ref/mod#goproxy-protocol

The first says

```
Returns a list of known versions of the given module in plain text, one per line. This list should not include pseudo-versions.
```

The second says

```
Returns JSON-formatted metadata about a specific version of a module. The response must be a JSON object that corresponds to the Go data structure below:

type Info struct {
    Version string    // version string
    Time    time.Time // commit time
}
```

I would love to have the behavior described in the second paragraph, but I cannot figure out how to get it. I have tried some of the obvious things like setting `Accept` and `Content-type` headers to `application/json`, but I note that above the documentation says that no query parameters or headers are required and, indeed, they don't seem to do anything.

### What did you see instead?

A list of newline separated version strings is returned, but no additional information (`Time` timestamps).

**Comment by seankhliao** [comment]
That paragraph is part of the next row in the table about .info endpoints

**Comment by andersthomson** [comment]
The table really could do with borders. More than once I've had to manually piece together the sections as each cell is vertically centered (which is not a common practice in formal specifications.)

**Comment by nieomylnieja** [comment]
Got caught up by this one too :D The invisible borders explain ti :) thanks
