### ISSUE TITLE
x/pkgsite: package removal request for [github.com/cosmiqal/cosmiqal-apis*]

### ISSUE THREAD

**Issue by stevencedro** [golang/go#55960]
### What is the path of the package that you would like to have removed?

github.com/cosmiqal/cosmiqal-apis
github.com/cosmiqal/cosmiqal-apis-go
 
### Are you the owner of this package?

Organization is [cosmiqal](https://github.com/cosmiqal) and I am the owner.
 
### What is the reason that you could not retract this package instead?

The repositories no longer exist.

**Comment by suzmue** [comment]
These packages have been removed.
