### ISSUE TITLE
x/build: remove linux-ppc64-osu builder 

### ISSUE THREAD

**Issue by pmur** [golang/go#55975]
The new VM linux-ppc64-sid (also at OSU) seems to be working OK over the last month.

I think it is time to decommission this builder in favor of linux-ppc64-sid.

Is it OK to continue using the name "linux-ppc64-sid"?

@golang/ppc64

**Comment by dmitshur** [comment]
Thanks. When you're ready, please feel free to send a CL to update x/build/dashboard accordingly and someone from @golang/release will review it.

I think it's okay to keep using "linux-ppc64-sid" if that's what you'd like to do. It's also okay to change if another name is better, but that means past results will not be connected to the new builder name. (Also, if changing the builder's host type name, the builder key needs to match.)
