### ISSUE TITLE
encoding/asn1: remove allocation from init

### ISSUE THREAD

**Issue by Thorleon** [golang/go#55973]
asn1 allocates due to `reflect.TypeOf(new(big.Int))` in init time. We could replace it with `reflect.TypeOf((*big.Int)(nil))`.

Before:
init encoding/asn1 @1.0 ms, 0.009 ms clock, 224 bytes, 7 allocs

After:
init encoding/asn1 @0.70 ms, 0.002 ms clock, 192 bytes, 6 allocs

**Comment by Thorleon** [comment]
Sure, I will skip Github issue part in minor tasks, thanks.

**Comment by andig** [comment]
The standard library has a few more occurences of this pattern `reflect.TypeOf(new(foo))`. Should they all be replaced?

**Comment by ianlancetaylor** [comment]
Probably.

Note that files in $GOROOT/test should not be changed unnecessarily.

Note that files under vendor are copied from upstream sources, and must be changed upstream and then vendored into to the standard library.

**Comment by hopehook** [comment]
I checked all the code, the memory is allocated on initialization, nowhere else.

@ianlancetaylor @andig 
To clarify, do we need to deal with the allocation of memory during the program running phase?

**Comment by Thorleon** [comment]
I didn't take care of other cases, as I was mainly focused on reducing init time of common binary. 

But for the sake of consistency and based on the Ian's comment I will adjust cases below in separate CLs:
```
go • src/cmd/compile/internal/base/flag.go:
277: 		ptrBoolType   = reflect.TypeOf(new(bool))
278: 		ptrIntType    = reflect.TypeOf(new(int))
279: 		ptrStringType = reflect.TypeOf(new(string))

go • src/cmd/vendor/golang.org/x/tools/go/analysis/passes/ctrlflow/ctrlflow.go:
28: 	ResultType: reflect.TypeOf(new(CFGs)),

go • src/cmd/vendor/golang.org/x/tools/go/analysis/passes/inspect/inspect.go:
43: 	ResultType:       reflect.TypeOf(new(inspector.Inspector)),

go • src/database/sql/sql.go:
3188: 			ci.scanType = reflect.TypeOf(new(any)).Elem()
```

**Comment by dolmen** [comment]
FYI I'm working on patching the `reflect.TypeOf(new(foo))` instances in `github.com/pelletier/go-toml/v2` which is vendored.

**Comment by mvdan** [comment]
I'm confused; where do you see go-toml being vendored into the standard library?

**Comment by dolmen** [comment]
I've sent a patch ([go-jose/go-jose#15]) for `github.com/go-jose/go-jose/v3` which is the successor of `gopkg.in/square/go-jose.v2` which is also marked as vendored in @andig's [report](https://github.com/golang/go/issues/55973#issuecomment-1264600417).

**Comment by dolmen** [comment]
@mvdan 
> I'm confused; where do you see go-toml being vendored into the standard library?

I did use @andig's [report above](https://github.com/golang/go/issues/55973#issuecomment-1264600417).

Whether it is still vendored or not, my patches will benefit to anybody.

**Comment by andig** [comment]
I'm sorry. Since I've included invalid results as I had my local folder open, too. Go-toml is not vendored into the standard library.
