### ISSUE TITLE
x/build: MacStadium macOS builders at reduced capacity

### ISSUE THREAD

**Issue by dmitshur** [golang/go#55979]
After some mandatory maintenance, a portion of the MacStadium builders did not come back after their host was rebooted, and as a result their capacity is reduced right now. This is the tracking issue to get them all online again.

Status is visible at https://farmer.golang.org/status/macs.

CC @golang/release.

**Comment by cagedmantis** [comment]
A hardware failure occurred while maintenance was being performed. The MacStadium amd64 macOS builders will not be available until the hardware is replaced and reconfigured.

**Comment by dmitshur** [comment]
This is resolved now, and https://farmer.golang.org/status/macs reports "ok". Closing.

(Thanks Carlos who did most of the work here.)
