### ISSUE TITLE
 lint error while implementing generics

### ISSUE THREAD

**Issue by codesnail21** [golang/go#55970]
### Issue

- I tried to learn and implement goGenerics in the local system, 
In local, i observed that the syntax is not working, although the program run (in both go playground as well as the local system) 

but only the syntax error is showing

![image](https://user-images.githubusercontent.com/87218847/193278142-85a53dd6-37a5-40c3-b33e-f11b8b49349e.png)

**Comment by dmitshur** [comment]
Can you add more information on how to reproduce the problem? What editor, editor version are you using? What tool or plugin is providing linting in your editor, and what version is it?

Please note the Go issue tracker is for tracking bugs and proposals for Go only. For asking questions, see https://go.dev/wiki/Questions.

**Comment by findleyr** [comment]
Also: what is the error message corresponding to the red underline?

(If I had to guess, absent context, I would suspect that you may be using an editor backed by gopls, and may need to recompile gopls using a version of Go that supports generics).

**Comment by codesnail21** [comment]
> Can you add more information on how to reproduce the problem? What editor, editor version are you using? What tool or plugin is providing linting in your editor, and what version is it?
> 
> Please note the Go issue tracker is for tracking bugs and proposals for Go only. For asking questions, see https://go.dev/wiki/Questions.

- Using the latest VS code on the Linux platform
- go version 18beta series'
- go-lint-cli version latest

**Comment by codesnail21** [comment]
> Also: what is the error message corresponding to the red underline?
> 
> (If I had to guess, absent context, I would suspect that you may be using an editor backed by gopls, and may need to recompile gopls using a version of Go that supports generics).

Error msg corresponding to underline: Cannot define func like this
In place of `[` you have to use `(` 

But, luckily when I compiled the program it runs regardless of error and print results

**Comment by seankhliao** [comment]
what is "go-lint-cli version latest"

**Comment by codesnail21** [comment]
> `go install golang.org/x/tools/gopls@latest`?

That's also the latest,
Might be because of vs Code, it's showing red underline

**Comment by codesnail21** [comment]
> what is "go-lint-cli version latest"

CLI lint for Golang

**Comment by seankhliao** [comment]
1.18 has been properly released, you shouldn't be using beta releases.
1.19 is also available.
Reinstall a proper version of go, then reinstall the tools.
Note golangci-lint is not part of the Go project.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
