### ISSUE TITLE
Error loading workspace - Incorrect warning

### ISSUE THREAD

**Issue by Suutuk** [golang/go#55988]
Hello guys!

When I open the Visual Studio Code in my go folder, where I use to develop, I receive the following message:

Error loading workspace: You are outside of a module and outside of $GOPATH/src. If you are using modules, please open your editor to a directory in your module. If you believe this warning is incorrect, please file an issue: https://github.com/golang/go/issues/new.

My GOPATH is setted:
GOPATH="/home/rafaelsonhador/go"

The project is in folder:
/home/rafaelsonhador/go/src/github.com/DreamBridgeNetwork/Go-GoogleOauth/

This project have the following structure:
-Go-GoogleOauth
--cmd
--internal
--config
-go.mod
-go.sum

I open the Visual Studio Code directly in the folder "/home/rafaelsonhador/go"

So this warning is incorrect.
Is there anything I can do to fix it?
Dos it cause any known problem during the development?

Kind Regards!
Suutuk

**Comment by seankhliao** [comment]
The warning is correct, open VS Code in the directory with the go.mod file.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by Suutuk** [comment]
ok. Thank you for the guidance.
And sorry by the mess.

Kind Regards,
Suutuk
