### ISSUE TITLE
x/vuln: govulncheck command not available after adding the package

### ISSUE THREAD

**Issue by aleybovich** [golang/go#55981]
### What version of Go are you using (`go version`)? 1.19.1

<pre>
$ go version

</pre>

### Does this issue reproduce at the latest version of golang.org/x/vuln?
Yes

### What operating system and processor architecture are you using (`go env`)?
Mac OSx 12.6  darwin-amd64

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

I try to install govulncheck: `go install golang.org/x/vuln/cmd/govulncheck@latest`
Th command completes with no errors 

### What did you expect to see?
I expect govulncheck command to become available in bash shell

### What did you see instead?
govulncheck command doesn't exists in my bash shell

**Comment by ZekeLu** [comment]
https://go.dev/ref/mod#go-install

> Executables (main packages) are installed to the directory named by the `GOBIN` environment variable, which defaults to `$GOPATH/bin` or `$HOME/go/bin` if the `GOPATH` environment variable is not set.

In order to make the command become available in bash shell, you should add that directory to the `PATH` environment variable.

**Comment by aleybovich** [comment]
@ZekeLu Thank you! I am using asdf for golang version control, so GOPATH is not exposed to the shell and I had to add the following to my `.zshrc` after the line that initializes asdf
```
# This line is already in the file if you have asdf installed
. /usr/local/opt/asdf/libexec/asdf.sh 

# This is the line adds $GOPATH/bin to $PATH
PATH=$(go env GOPATH)/bin:$PATH 
```

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
