### ISSUE TITLE
all: openbsd port maintainers

### ISSUE THREAD

**Issue by 4a6f656c** [golang/go#55998]
In light of #53383, Aaron Bieber (@qbit) has agreed to be an additional maintainer for the OpenBSD Go ports - could we please get him set up accordingly?

/cc @bcmills @qbit

**Comment by qbit** [comment]
Is anything needed from me for this (with regard to getting things setup)?

**Comment by dmitshur** [comment]
Thanks Joel and Aaron. Aaron, you should have an invite to join the https://github.com/orgs/golang/teams/openbsd team.

**Comment by qbit** [comment]
Indeed I do! Joined!
