### ISSUE TITLE
Slices:  inconsistent behavior when slicing > length

### ISSUE THREAD

**Issue by MaerF0x0** [golang/go#55991]
Go playground link below

### What version of Go are you using (`go version`)?
go playground (go.dev/play)
1.19 

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
go playground

### What did you do?

see: https://go.dev/play/p/06pE_6NxQvm

resliced a slice with capacity, and got back a slice with many ZeroValue elements

### What did you expect to see?

either `panic: runtime error: slice bounds out of range [:25] with capacity 3`
or a best effort slice that results in items up to the length of the slice

```go
[]int{1, 2, 3}
```

### What did you see instead?
```
[]int{1, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
```

Is this by design, and I'm wondering why? It means it's generally not safe to use make w/ cap to prealloc space , particularly with interfaces which will result in nil pointer panics once we range over the resliced item... 

I'm curious if it's described in the docs anywhere?

**Comment by randall77** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and [proposals](https://go.dev/s/proposal-process) only.. For questions, see https://github.com/golang/go/wiki/Questions

For understanding slices, you should probably start with https://go.dev/blog/slices-intro
