### ISSUE TITLE
os/exec 

### ISSUE THREAD

**Issue by JBossBC** [golang/go#56008]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.17
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
operation system:windows
</pre></details>

### What did you do?
i want to execute `docker container ls -a --format  "{{json  .}}"` command throught exec.command

###  guess question

i think this is because the  Double quotation marks cant be used in   `docker container ls -a --format  "{{json  .}}"` ,but i hasnt enough revidence to  prove

### What did you expect to see?

![image](https://user-images.githubusercontent.com/90125263/193540442-dfcda822-b593-434d-b1ce-9f493aeb4385.png)

### What did you see instead?
![image](https://user-images.githubusercontent.com/90125263/193540526-6277fc90-031b-41cb-9b3a-647ca96dfc9e.png)

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.
