### ISSUE TITLE
reflect: Method() on a type races

### ISSUE THREAD

**Issue by mstoykov** [golang/go#56011]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.20-5451ba3 Mon Oct 3 13:05:50 2022 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Not from my experience

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/mstoykov/.cache/go-build"
GOENV="/home/mstoykov/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/mstoykov/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/mstoykov/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/mstoykov/sdk/gotip"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/mstoykov/sdk/gotip/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel go1.20-5451ba3 Mon Oct 3 13:05:50 2022 +0000"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2972316461=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
Run

`gotip test -trimpath  -race  -count 1 .`

with the following file as `main_test.go`

```go
package main_test

import (
	"net"
	"reflect"
	"testing"
)

func Test1(t *testing.T) {
	test(t)
}

func Test2(t *testing.T) {
	test(t)
}

func Test3(t *testing.T) {
	test(t)
}

func Test4(t *testing.T) {
	test(t)
}

func Test5(t *testing.T) {
	test(t)
}

func Test6(t *testing.T) {
	test(t)
}

func Test7(t *testing.T) {
	test(t)
}

func test(t *testing.T) {
	t.Parallel()
	ipT := reflect.TypeOf(net.IP{})
	for i := 0; i < ipT.NumMethod(); i++ {
		_ = ipT.Method(i)
	}
}
```

### What did you expect to see?

No races

### What did you see instead?

A race was detected.
<details><summary>race trace stack</summary><br><pre>

==================
WARNING: DATA RACE
Write at 0x000001cf0480 by goroutine 17:
  reflect.initFuncTypes()
      reflect/type.go:2015 +0x1a7
  reflect.FuncOf()
      reflect/type.go:2050 +0x15e
  reflect.(*rtype).Method()
      reflect/type.go:876 +0xb46
  go.k6.io/k6_test.test()
      go.k6.io/k6/main_test.go:41 +0xc1
  go.k6.io/k6_test.Test2()
      go.k6.io/k6/main_test.go:14 +0x2e
  testing.tRunner()
      testing/testing.go:1501 +0x216
  testing.(*T).Run.func1()
      testing/testing.go:1548 +0x47

Previous read at 0x000001cf0480 by goroutine 16:
  reflect.FuncOf()
      reflect/type.go:2051 +0x16a
  reflect.(*rtype).Method()
      reflect/type.go:876 +0xb46
  go.k6.io/k6_test.test()
      go.k6.io/k6/main_test.go:41 +0xc1
  go.k6.io/k6_test.Test1()
      go.k6.io/k6/main_test.go:10 +0x2e
  testing.tRunner()
      testing/testing.go:1501 +0x216
  testing.(*T).Run.func1()
      testing/testing.go:1548 +0x47

Goroutine 17 (running) created at:
  testing.(*T).Run()
      testing/testing.go:1548 +0x75d
  testing.runTests.func1()
      testing/testing.go:1913 +0x72
  testing.tRunner()
      testing/testing.go:1501 +0x216
  testing.runTests()
      testing/testing.go:1911 +0x884
  testing.(*M).Run()
      testing/testing.go:1783 +0xaa4
  main.main()
      _testmain.go:61 +0x2e9

Goroutine 16 (running) created at:
  testing.(*T).Run()
      testing/testing.go:1548 +0x75d
  testing.runTests.func1()
      testing/testing.go:1913 +0x72
  testing.tRunner()
      testing/testing.go:1501 +0x216
  testing.runTests()
      testing/testing.go:1911 +0x884
  testing.(*M).Run()
      testing/testing.go:1783 +0xaa4
  main.main()
      _testmain.go:61 +0x2e9
==================
--- FAIL: Test2 (0.00s)
    testing.go:1374: race detected during execution of test
--- FAIL: Test4 (0.00s)
    testing.go:1374: race detected during execution of test
--- FAIL: Test5 (0.00s)
    testing.go:1374: race detected during execution of test
--- FAIL: Test1 (0.00s)
    testing.go:1374: race detected during execution of test
--- FAIL: Test7 (0.00s)
    testing.go:1374: race detected during execution of test
--- FAIL: Test3 (0.00s)
    testing.go:1374: race detected during execution of test
--- FAIL: Test6 (0.00s)
    testing.go:1374: race detected during execution of test
</pre></details>

From my experiments it happens 1/3 times on gotip, but I haven't' seen a single case on go 1.19.1 out of probably a hundred runs.

It seems to me like https://github.com/golang/go/commit/63668a5155c808f474d5adab676ef3f3aa50c1d3 changed something? But haven't bisected it yet. So it might be unrelated.

We started seeing it in CI *today*, but it is not 100% reproducible there as well, so it might be older :shrug:

**Comment by randall77** [comment]
That's a race all right. @cuiweixie

**Comment by mstoykov** [comment]
I have now ran with https://github.com/golang/go/commit/63668a5155c808f474d5adab676ef3f3aa50c1d3 and the previous commit.

Got race on the first run with https://github.com/golang/go/commit/63668a5155c808f474d5adab676ef3f3aa50c1d3 and not a single one over ... 20-30+ runs on the previous one.
