### ISSUE TITLE
cmd/compile: confusing message for syntax error

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#56022]
Bug mentioned by @apparentlymart in #55863.

With tip, compiling

```Go
package main

type Foo struct{}

func (f *Foo) (
	Blah() {}
)
```

produces the error messages

```
foo.go:5:15: syntax error: unexpected (, expected name or (
foo.go:6:9: syntax error: unexpected { after top level declaration
```

The first error makes no sense: it is saying that it found an unexpected left parenthesis when it expected a left parenthesis.

I think the error is in `(*parser).funcDeclOrNil`: it should not say that it expects a left parenthesis if it already found a receiver.

CC @griesemer

**Comment by rittneje** [comment]
Strangely, gofmt yields the correct error message:
> prog.go:5:15: expected 'IDENT', found '(' (and 1 more errors)

**Comment by ianlancetaylor** [comment]
gofmt and the compiler do not use the same parser, so they can have different error messages.
