### ISSUE TITLE
x/pkgsite: Custom license file review based on MICROSOFT REFERENCE SOURCE LICENSE (MS-RSL)

### ISSUE THREAD

**Issue by bismapervaiz** [golang/go#56074]
### Request to review custom license based on [MICROSOFT REFERENCE SOURCE LICENSE (MS-RSL)](https://referencesource.microsoft.com/license.html)
I cannot see our custom license at [https://pkg.go.dev/github.com/apimatic/core-lib-go](https://pkg.go.dev/github.com/apimatic/core-lib-go) due to which our package's documentation is being blocked.

With this request I would like to bring to your attention that our custom license is because of our business need which grants the right to review and study the code which includes the right to document it as well.
 
I would highly appreciate the consideration.

**Comment by hyangah** [comment]
Thanks for filing the issue @bismapervaiz 
The MS-RSL explicitly excludes the right to distribute. Unless there is clear evidence that some other permissive license (https://pkg.go.dev/license-policy) allowing distribution applies to package documentation, pkgsite does not redistibute the documentation.

**Comment by bismapervaiz** [comment]
Thanks @hyangah
