### ISSUE TITLE
x/pkgsite: Add support for MICROSOFT REFERENCE SOURCE LICENSE (MS-RSL)

### ISSUE THREAD

**Issue by bismapervaiz** [golang/go#56078]
### What is the URL of the page with the issue?
MICROSOFT REFERENCE SOURCE LICENSE (MS-RSL) not supported yet at [pkg.go.dev](https://pkg.go.dev/license-policy) page.

### What did you expect to see?
Support for the MICROSOFT REFERENCE SOURCE LICENSE [(MS-RSL).](https://referencesource.microsoft.com/license.html) 

Kindly consider adding this LICENSE to the list of recognized licenses on the https://pkg.go.dev/ website.

**Comment by seankhliao** [comment]
Duplicate of #56074
