### ISSUE TITLE
x/pkgsite: clarify what kinds of licenses are acceptable

### ISSUE THREAD

**Issue by mvdan** [golang/go#56075]
https://pkg.go.dev/license-policy has quite a bit of helpful wording, including:

> If you use a package whose license is not detected, please inform the package author. If you are a package author who believes a license for one of your packages should have been detected and was not, please check for discrepancies between your license and the official text. If you still believe there is an error, please [file an issue](https://golang.org/s/pkgsite-feedback).

I would like to see a bit more information about what _kinds of licenses_ are acceptable for pkgsite. For example, I can think of two cases where it is unlikely that pkgsite would add a particular license:

* If the license does not allow redistribution of the code, as this could cause problems with e.g. rendering examples
* If the license is entirely bespoke for one or few Go modules which aren't popular - I imagine that lawyers reviewing new licenses is expensive, and that doesn't scale if thousands of Go users write their own licenses from scratch

Moreover, it seems like a license being recognized by the Open Source Initiative [is a significant factor](https://github.com/golang/go/issues/52923#issuecomment-1144705151), but this is not documented either.

It's also unclear to me if a license being recognized by OSI is a requirement or not. If it's not a requirement, do we still require licenses to include some OSS freedoms such as read/study/redistribute? If so, that should be documented as well.

cc @jba @hyangah

**Comment by mvdan** [comment]
I should clarify that the added guidance would likely not be in the form of "meet these criteria and the license will be added", because making such a promise can lead to sticky situations down the line. But the guidance should make it pretty clear to the reader that, for example:

* A fully bespoke and rare license is very unlikely to be added
* An OSI license is very likely to be added

**Comment by seankhliao** [comment]
I believe this is done in [CL 491775](https://go.dev/cl/491775)
