### ISSUE TITLE
x/build: update plan9-arm builder to a current buildlet binary

### ISSUE THREAD

**Issue by bcmills** [golang/go#56079]
### What did you do?

```
~/go/src$ gomote run -dir=/boot/workdir/go/src bcmills-plan9-arm-0 ./make.rc
```

### What did you expect to see?

Successful `make.rc` run.

### What did you see instead?

```
~/go/src$ gomote run -dir=/boot/workdir/go/src bcmills-plan9-arm-0 ./make.rc
Error running run: Error trying to execute ./make.rc: unable to execute command: buildlet: HTTP status 400 Bad Request: bogus 'dir' parameter
```

The “`bogus 'dir parameter'`” error message was removed in https://go.dev/cl/367896, so this seems to imply that the `plan9-arm` builder is not using an up-to-date `cmd/buildlet` binary. (I had through that `cmd/buildlet` automatically updated itself, but I guess not?)

(attn @0intro @millerresearch)

**Comment by 0intro** [comment]
I've just rebuilt the buildlet binaries:

- http://9legacy.org/download/go/buildlet/386/buildlet
- http://9legacy.org/download/go/buildlet/amd64/buildlet
- http://9legacy.org/download/go/buildlet/arm/buildlet

I've updated the buildlet binary on the `plan9-386` and `plan9-amd64` builders.

@millerresearch Could you please update the buildlet binaries on the `plan9-arm` builders?

Thanks.

**Comment by millerresearch** [comment]
Done.
