### ISSUE TITLE
cmd/gofmt: indenting removed from multi-line bullet-lists inside numbered lists

### ISSUE THREAD

**Issue by thaJeztah** [golang/go#56072]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.2 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

(probably not relevant)
</pre></details>

### What did you do?

Given the following file;

```go
/*
Package main is an example.

 1. Item 1.
 2. Item 2.
    - SubItem 1.
    - SubItem 2.
    - SubItem 3 spans two lines. Lorem ipsum dolor sit amet, consectetur
      adipiscing elit. Morbi porta eros nunc, in viverra ex porttitor vitae.
    - Subitem 3 spans three lines. Lorem ipsum dolor sit amet, consectetur
      adipiscing elit. Morbi porta eros nunc, in viverra ex porttitor vitae.
      Mauris nisi magna, faucibus quis velit vitae, euismod convallis magna.
*/
package main
```

Running `gofmt` reformat the bullet-list, removing the indentation for bullets spanning multiple lines;

```bash
gofmt -d .
diff main.go.orig main.go
--- main.go.orig
+++ main.go
@@ -6,9 +6,9 @@
     - SubItem 1.
     - SubItem 2.
     - SubItem 3 spans two lines. Lorem ipsum dolor sit amet, consectetur
-      adipiscing elit. Morbi porta eros nunc, in viverra ex porttitor vitae.
+    adipiscing elit. Morbi porta eros nunc, in viverra ex porttitor vitae.
     - Subitem 3 spans three lines. Lorem ipsum dolor sit amet, consectetur
-      adipiscing elit. Morbi porta eros nunc, in viverra ex porttitor vitae.
-      Mauris nisi magna, faucibus quis velit vitae, euismod convallis magna.
+    adipiscing elit. Morbi porta eros nunc, in viverra ex porttitor vitae.
+    Mauris nisi magna, faucibus quis velit vitae, euismod convallis magna.
 */
 package main
```

I also tried adding whitespace after the bullet-list (following the example at https://go.dev/doc/comment#mistakes):

```go
/*
Package main is an example.

 1. Item 1.

 2. Item 2.

    - SubItem 1.
    - SubItem 2.
    - SubItem 3 spans two lines. Lorem ipsum dolor sit amet, consectetur
      adipiscing elit. Morbi porta eros nunc, in viverra ex porttitor vitae.
    - Subitem 3 spans three lines. Lorem ipsum dolor sit amet, consectetur
      adipiscing elit. Morbi porta eros nunc, in viverra ex porttitor vitae.
      Mauris nisi magna, faucibus quis velit vitae, euismod convallis magna.
*/
package main
```

But this gave the same result;

```bash
gofmt -d .
diff main.go.orig main.go
--- main.go.orig
+++ main.go
@@ -8,10 +8,9 @@
     - SubItem 1.
     - SubItem 2.
     - SubItem 3 spans two lines. Lorem ipsum dolor sit amet, consectetur
-      adipiscing elit. Morbi porta eros nunc, in viverra ex porttitor vitae.
+    adipiscing elit. Morbi porta eros nunc, in viverra ex porttitor vitae.
     - Subitem 3 spans three lines. Lorem ipsum dolor sit amet, consectetur
-      adipiscing elit. Morbi porta eros nunc, in viverra ex porttitor vitae.
-      Mauris nisi magna, faucibus quis velit vitae, euismod convallis magna.
+    adipiscing elit. Morbi porta eros nunc, in viverra ex porttitor vitae.
+    Mauris nisi magna, faucibus quis velit vitae, euismod convallis magna.
 */
 package main
```

### What did you expect to see?

The indentation preserved.

### What did you see instead?

The indentation removed.

**Comment by mvdan** [comment]
You're right, that issue was about nested lists, I forgot that.

**Comment by tenkoh** [comment]
Interesting issue 😄 

I think the workaround to avoid reformatting refered in https://go.dev/doc/comment#mistakes is a little confusing. The workaround could avoid reformatting but the output does not match to users' expectations.

For example, add a second line to the workaround's example.

```go
// Here is a list:
//
//  1. Item 1.
//
//     - Subitem 1.
//       This is a second line. (added)
//
//     - Subitem 2.
//
//  2. Item 2.
//
//  3. Item 3.
```

`go doc` command outputs as below.

```
 1. Item 1.

    - Subitem 1. This is a second line. (added)

    - Subitem 2.

 2. Item 2.

 3. Item 3.
``` 

So, in the workaround, the bullet list is not regarded as a list but regarded as a part of paragraph in the number list. That's because the second line is indented to the outer indent level.

For reference, `gofmt` output is here.
```go
// Here is a list:
//
//  1. Item 1.
//
//     - Subitem 1.
//     This is a second line. (added)
//
//     - Subitem 2.
//
//  2. Item 2.
//
//  3. Item 3.
```

How about removing the workaround from the documentation? Otherwise, how about clarifying the workaround's limitation as described above?

**Comment by HeCorr** [comment]
Hello, I've recently updated Go from 1.18 to 1.20 and noticed most multi-line comments have lost their original formatting:

![image](https://github.com/golang/go/assets/75134774/0f8c3eaf-2c7a-4056-aa46-706b5fae74c4)

It was previously spaced like that to be more readable:

![image](https://github.com/golang/go/assets/75134774/adad17ff-7d6f-4fed-a96f-778d27303863)

in comparison to:

![image](https://github.com/golang/go/assets/75134774/956565fb-b81d-4b4b-8907-2a68515b2a5f)

What is the reason of the change? And could it be reverted to allow such formatting again? Thanks!

**Comment by ianlancetaylor** [comment]
@HeCorr Please paste plain text as plain text, not images.  Images are much harder to read.  Thanks.

The change you are describing is documented at https://go.dev/doc/go1.19#go-doc.  The links there explain how you can get doc comments that format correctly in both text and HTML.

**Comment by ianlancetaylor** [comment]
I'm closing this issue because the comment is working according to the current doc comment formatting rules.

**Comment by HeCorr** [comment]
well, that's a shame because I'm not even using godoc and yet this change affected me negatively.
