### ISSUE TITLE
x/exp/slog: unexpected behavior when using NewJSONHandler

### ISSUE THREAD

**Issue by AndrewHarrisSPU** [golang/go#56087]
### What version of Go are you using (`go version`)?

<pre>
go version go1.19rc2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOOS="darwin"

</pre></details>

### What did you do?

Using the `slog` package, ran the following program, as well as one with `NewTextHandler`

```
func main() {
	log := slog.New( slog.NewJSONHandler(os.Stdout)).With("job", "Eulerian Gophers" )
	log = log.With( "id", 1 )
	log.Log( slog.InfoLevel, "", "total", 5050 )
}

func main() {
	scully := slog.New( slog.NewTextHandler(os.Stdout))
	scully.Error( "👩‍🦰", errors.New("🛸"))
}
```

### What did you expect to see?

For the first program, JSON parseable by `gojq`

For the second program, a log message showing some error associating Agent Scully and a UFO

(I don't have the expectation that slog is anything but /x/exp, but just noticed these things)

### What did you see instead?

For the first program:
```
"level":"INFO","msg":"","job":"Eulerian Gophers""id":1,"total":5050}
```
this isn't parsed because there should be a [edit] a comma here: `"Eulerian Gophers","id"`. There is a similar glitch with TextHandler output, and I guess it's the preformatting. `With("job", "Eulerian Gophers", "id", 1 )` eliminates the glitch.

For the second program, using 
```
level=ERROR msg="👩\u200d🦰" err=🛸
```
Using JSON seems to avoid escaping the zero width joiner.

[edit: fixed a few details in description that were backwards]

**Comment by seankhliao** [comment]
cc @jba

**Comment by jba** [comment]
The first problem is fixed at master.

The second is WAI. TextHandler uses strconv.Quote to quote strings with non-printing characters, like the zero-width joiner. You can get back the original with strconv.Unquote. JSONHandler uses the same escaping as json.Marshal, which does not escape non-printing characters. We wanted to make parsing of the text format straightforward; we don't want it to depend on anything in the encoding/json package.
