### ISSUE TITLE
gollvm: error: ‘class llvm::MCStreamer’ has no member named ‘SwitchSection’

### ISSUE THREAD

**Issue by iMacker2020** [golang/go#56089]
### What version of Go are you using (`go version`)?

<pre>
$ go version
Go 1.19 
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
Operating system:  Windowsfx (Linux)
Processor: x86-64

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1286324867=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

I followed the directions from this web page: 
https://go.googlesource.com/gollvm

### What did you expect to see?
A gollvm binary.

### What did you see instead?
This error message:
/home/user/workarea/llvm-project/llvm/tools/gollvm/passes/GC.cpp:186:6: error: ‘class llvm::MCStreamer’ has no member named ‘SwitchSection’; did you mean ‘switchSection’?
  186 |   OS.SwitchSection(StackMapSection);
      |      ^~~~~~~~~~~~~
      |      switchSection

**Comment by ianlancetaylor** [comment]
CC @thanm @cherrymui

**Comment by thanm** [comment]
Dup of #56092.

**Comment by iMacker2020** [comment]
Why is this considered a duplicate of #56092? 56092 is about a missing member named ‘getElementType’. This ticket is about the switchSection function.

**Comment by thanm** [comment]
It falls into the general category of fixing up the bridge code to bring it into sync with LLVM trunk. I don't think it makes sense to have separate bugs for each specific item.
