### ISSUE TITLE
x/vuln/cmd/govulncheck: communicate current Go version to user when analyzing source

### ISSUE THREAD

**Issue by zpavlinovic** [golang/go#56097]
When analyzing source code, results of govulncheck should be interpreted w.r.t. to the current Go version. For instance, if the user is having go1.18 at PATH, we will report reachable standard library vulnerabilities for that version only. Users need to be aware of this.

Although documentation [mentions](https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck) this, perhaps we can do better. Ideally, we should further help avoiding the scenario where users run govulncheck only for, say, a single Go version where a standard library vulnerability is not exercised and then have an expectation that their programs are safe from std vulnerabilities for all Go versions.

### Approach 1

One approach is to make explicit to the user in the govulncheck output for which Go/std version govulncheck analysis was conducted: [CL](https://go-review.git.corp.google.com/c/vuln/+/436909).

### Approach 2

An alternative approach is to pretend that the user is having all Go versions at PATH simultaneously and then just list at which Go versions are the reachable std vulnerabilities exercised. This is similar to #54841. There are few issues with this approach:

1) The std code we load is still the std code for the Go version at PATH. In theory, if the current version is, say, go1.18 but a vulnerable symbol is introduced in, say, go1.19, we would miss reporting that symbol. This might not be a problem in practice because if the code for go1.18 compiles, then it clearly cannot use the symbol introduced later. However, it could be importing it though. I could also be missing something obvious.

2) We should not bake this logic into vulncheck library, which means we need to come up with a module version that vulncheck should interpret as "all" and document it. We would also need to change a lot of tests, but that is less of a problem.

@jba @julieqiu @hyangah  @fflewddur

**Comment by timothy-king** [comment]
Can we be clearer about what the "user journey" we are worried about is?

Here is my understanding a local dev of package P is at go1.19. The CI building system is at go1.18.0. There is a hypothetical vulnerable std library function Vuln which is vulnerable in go.18.0. P reaches Vuln.  This vuln was fixed by 1.19. The user checks locally with govulncheck and P has no vulns against 1.19. A binary built by CI using 1.18.0 containing the vuln is then deployed.

Is this the concern? Or is there a motivating case I am missing?

**Comment by zpavlinovic** [comment]
Yes, that would be the concern.
