### ISSUE TITLE
affected/package: image/gif EncodeAll have black dots

### ISSUE THREAD

**Issue by jishi92** [golang/go#56095]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.17

</pre>

### Does this issue reproduce with the latest release?
no

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
`GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="xxx"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"`
</pre></details>

### What did you do?

I have many png images and want encode them to a gif animation. These png images dont have any black dots ,but the gif result have many dots.

![2](https://user-images.githubusercontent.com/22196414/194555997-fd6da838-2795-4127-b7a6-4b341003a222.png)

![response-dots](https://user-images.githubusercontent.com/22196414/194554704-c1585e87-83c8-46f8-9f52-281e1e5ca54a.gif)

### What did you expect to see?

I hope these dots can be deleted 

### What did you see instead?

make these dots much less

**Comment by thediveo** [comment]
gif is 8bit color palette with 256 out of 24bit RGB, png supports different color depths, such as 8bits RGBA and different color spaces, with sRGB being default IIRC. This looks like your source pngs color space cannot be converted to the gif RGB color space without dithering.

**Comment by jishi92** [comment]
Hi @thediveo , thanks for your reply. So how should I convert the pngs color depths or color model, to compatible with the gif color palette. I have very little knowledge about image color.

**Comment by thediveo** [comment]
Unfortunately, I don't have much experience with Go handling color spaces. Did you notice this Stackoveflow question https://stackoverflow.com/questions/70327401/golang-create-gif-animation-from-png-images about creating GIF animations from PNG using Go? Also, I would suggest maybe asking in the go-nuts group for help instead of on the Go issue tracker itself unless it really is a stdlibs bug, as I would expect a better chance of the right people with more colorspace knowledge than I do to find your question and answer it.

**Comment by thediveo** [comment]
Oh, and please provide minimal concrete code and the other input files, as without code there's often no chance to help in such situations; and without at least a single input file no-one can probably help.

**Comment by thediveo** [comment]
Another tangent to tackle this might be to use the animated PNG (apng) format instead of GIF, for instance: https://github.com/kettek/apng

**Comment by jishi92** [comment]
Hi @thediveo, I saw this Stackoveflow question (https://stackoverflow.com/questions/70327401/golang-create-gif-animation-from-png-images) the other day and create my question (https://stackoverflow.com/questions/73987493/golang-image-gif-encodeall-have-many-black-dots).

**Comment by thediveo** [comment]
You'll need to use a custom palette, please see this answer https://stackoverflow.com/a/73998156.

Could you please close this issue, ws it is no go bug?

**Comment by jishi92** [comment]
ok,I close it
