### ISSUE TITLE
gollvm: error: ‘class llvm::DomTreeUpdater’ has no member named ‘insertEdge’

### ISSUE THREAD

**Issue by iMacker2020** [golang/go#56090]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.19
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Operating System: linux
Process Architecture: amd64

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build237170764=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you expect to see?
I expected to see a completed gollvm compiler made.

### What did you see instead?
I saw this error message:
/home/user/workarea/llvm-project/llvm/tools/gollvm/passes/GoStatepoints.cpp:2182:11: error: ‘class llvm::DomTreeUpdater’ has no member named ‘insertEdge’
 2182 |       DTU.insertEdge(Old, PadBB);

I looked up this class and found its documentation page here: https://docs.hdoc.io/hdoc/llvm-project/r11162AC129BF1CE7.html.
There is no insertEdge() function.

I did find this page: https://reviews.llvm.org/D58443. It states that the insertEdge() function was depreciated and replaced with applyUpdates().

**Comment by iMacker2020** [comment]
Found out that llvm patch b9898e7ed1cea0fc429674e655f91d28b9964814 removed the insertEdge(), insertEdgeRelaxed(),  deleteEdge(), deleteEdgeRelaxed methods. This was applied today (10.6.2022).

**Comment by ianlancetaylor** [comment]
CC @thanm @cherrymui

**Comment by thanm** [comment]
See notes on #56092.

**Comment by thanm** [comment]
Dup of #56092.
