### ISSUE TITLE
encoding/xml: decoder fails to locate correct closing tag

### ISSUE THREAD

**Issue by christopherhwood** [golang/go#56091]
### What version of Go are you using (`go version`)? 

1.19, also reproducible on dev branch

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

Linux amd64

### What did you do?

Link to go playground with problematic code example: https://go.dev/play/p/sW7Wgl67OFi

xml decoder fails to find correct closing tag.

### What did you expect to see?

xml decoder should locate the correct closing tag.

**Comment by christopherhwood** [comment]
Seems the problem is that the cdata section does not include a space before the `]]>` closure. After adding a space it is properly handled by the xml decoder.

**Comment by cagedmantis** [comment]
cc @rsc

**Comment by tenkoh** [comment]
I assume that there are no issues on Go code, but the reproduction code on playground might have an encoding bug.

- As we know, Go's source code is supposed to be encoded by UTF-8. 
- The original reproduction code contains Chinese sentences. Though they are encoded by UTF-8, the xml tag says it is encoded by GBK. So xml decoder fails to decode properly.
- In the reproduction code, the decoding failure caused a lack of the CDATA's closing tag (see below). As a result, xml decoder skipped it and failed to parse xml behind the CDATA.

```go
s := "润]]>"
r, _ := charset.NewReaderLabel("gbk", strings.NewReader(s))
b, _ := io.ReadAll(r)
fmt.Println(string(b))
// Output: 娑�]>
```
https://go.dev/play/p/TXhWsqyaSPY



How was the original problem? If the xml body is properly encoded by GBK, the xml decoder with gbk reader works well like below.

https://go.dev/play/p/JkyF8rOfWFU
