### ISSUE TITLE
x/vuln: Show which packages are being scanned

### ISSUE THREAD

**Issue by fflewddur** [golang/go#56101]
To help developers establish trust that govulncheck is behaving as they expect, we should include an option to show what it is scanning and how recent the vulnerability information it's checking against is. This could be part of verbose mode, though there might be a short summary that would also make sense for the default output.

As an example, we could print a list of all packages that were scanned and the timestamp of the vulndb that was used to scan them.

**Comment by zpavlinovic** [comment]
Also tracked in #56501. (keeping that one open due to an active discussion)
