### ISSUE TITLE
x/pkgsite: package removal request for [github.com/christowolf/go-middleware

### ISSUE THREAD

**Issue by ChristoWolf** [golang/go#56108]
### What is the path of the package that you would like to have removed?

All versions of github.com/christowolf/go-middleware.

### Are you the owner of this package?

Yes.
 
### What is the reason that you could not retract this package instead?

I wanted to start again from a clean slate due to my previous versioning scheme leading to hard to maintain versions.
The module was still in an experimental state but I did not mark it as such.
Would be great if you could remove them so that I can newly request my current one in experimental state.

Thanks!

**Comment by seankhliao** [comment]
pkgsite removal only hides documentation, it doesn't affect cached versions and checksums, there's no way to reuse those.

**Comment by ChristoWolf** [comment]
Thanks @seankhliao!
Is there anything I can do to make it still work?
I would really like to re-use that module name.
