### ISSUE TITLE
x/pkgsite: package removal request for ask.systems/daemon/spawn

### ISSUE THREAD

**Issue by fsmv** [golang/go#56114]
### What is the path of the package that you would like to have removed?

ask.systems/daemon/spawn

Please leave the base module ask.systems/daemon untouched.
 
### Are you the owner of this package?

Yes, I own ask.systems.

### What is the reason that you could not retract this package instead?

I accidentally published this package as a module and got it cached that way and now it selects an old version unlike all the other packages in my project. I tried to publish a retraction go.mod file for all versions but it didn't seem to work and having the go.mod file messes up my build setup (`ask.systems/daemon/spawn: ambiguous import: found package ask.systems/daemon/spawn in multiple modules`) so I deleted it again from the HEAD commit in the repo.

I want ask.systems/daemon/spawn to just be a package of the ask.systems/daemon module but the proxy.golang.org etc sites have cached it as a module and now it seems impossible to delete the existence of the module, you can only retract versions of a module that still exists.

**Comment by seankhliao** [comment]
pkgsite removal only hides documentation, it doesn't affect the `go` tool's version selection.
