### ISSUE TITLE
x/pkgsite: package removal request for github.com/Azure/azure-sdk-for-go/sdk/*/arm*

### ISSUE THREAD

**Issue by tadelesh** [golang/go#56121]
### What is the path of the package that you would like to have removed?

 

github.com/Azure/azure-sdk-for-go/sdk/agfood/armagfood
github.com/Azure/azure-sdk-for-go/sdk/agrifood/armagrifood
github.com/Azure/azure-sdk-for-go/sdk/apimanagement/armapimanagement
github.com/Azure/azure-sdk-for-go/sdk/authorization/armauthorization
github.com/Azure/azure-sdk-for-go/sdk/compute/armcompute
github.com/Azure/azure-sdk-for-go/sdk/containerregistry/armcontainerregistry
github.com/Azure/azure-sdk-for-go/sdk/containerservice/armcontainerservice
github.com/Azure/azure-sdk-for-go/sdk/cosmos/armcosmos
github.com/Azure/azure-sdk-for-go/sdk/eventgrid/armeventgrid
github.com/Azure/azure-sdk-for-go/sdk/eventhub/armeventhub
github.com/Azure/azure-sdk-for-go/sdk/keyvault/armkeyvault
github.com/Azure/azure-sdk-for-go/sdk/monitor/armmonitor
github.com/Azure/azure-sdk-for-go/sdk/network/armnetwork
github.com/Azure/azure-sdk-for-go/sdk/operationalinsights/armoperationalinsights
github.com/Azure/azure-sdk-for-go/sdk/postgresql/armpostgresql
github.com/Azure/azure-sdk-for-go/sdk/postgresql/armpostgresqlflexibleservers
github.com/Azure/azure-sdk-for-go/sdk/privatedns/armprivatedns
github.com/Azure/azure-sdk-for-go/sdk/redis/armredis
github.com/Azure/azure-sdk-for-go/sdk/resources/armresources
github.com/Azure/azure-sdk-for-go/sdk/servicebus/armservicebus
github.com/Azure/azure-sdk-for-go/sdk/sql/armsql
github.com/Azure/azure-sdk-for-go/sdk/storage/armstorage
github.com/Azure/azure-sdk-for-go/sdk/web/armweb
github.com/Azure/azure-sdk-for-go/sdk/arm/compute/2020-09-30/armcompute
github.com/Azure/azure-sdk-for-go/sdk/arm/keyvault
github.com/Azure/azure-sdk-for-go/sdk/arm/keyvault/2019-09-01/armkeyvault
github.com/Azure/azure-sdk-for-go/sdk/arm/network/2020-07-01/armnetwork
github.com/Azure/azure-sdk-for-go/sdk/arm/resources/2020-06-01/armresources
github.com/Azure/azure-sdk-for-go/sdk/arm/storage/2019-06-01/armstorage
 
### Are you the owner of this package?

Yes.

### What is the reason that you could not retract this package instead?

We have already retracted all versions of all these modules. However, it still be displayed under `https://pkg.go.dev/github.com/Azure/azure-sdk-for-go#section-directories`. These modules are our previous preview versions and we need to hide them from `pkg.go.dev` to prevent any misleading usage. cc @xboxeer @jhendrixMSFT

**Comment by jamalc** [comment]
Done.
