### ISSUE TITLE
x/vuln: 

### ISSUE THREAD

**Issue by RyanCode** [golang/go#56122]
### what i do?
compile a go program for c.
### go env
GO111MODULE=""
GOARCH="mips64le"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="mips64le"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/root/workspace/go-linux-mips64le-bootstrap"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/root/workspace/go-linux-mips64le-bootstrap/pkg/tool/linux_mips64le"
GOVCS=""
GOVERSION="go1.18.7"
GCCGO="gccgo"
GOMIPS64="hardfloat"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/ryan/proxy-protector/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -mabi=64 -mhard-float -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build816227691=/tmp/go-build -gno-record-gcc-switches"
### go version
go1.18.7 linux/mips64le
### static library
```shell
[root@host proxy-protector]# go build -tags "cxterm_parser" -o libs/xterm-linux-mips64le/libxterm.so -buildmode=c-archive xterm/cxterm/cxterm.go
# internal/goos
compile: linux/mips64le does not support -shared
# internal/itoa
compile: linux/mips64le does not support -shared
# internal/unsafeheader
compile: linux/mips64le does not support -shared
# internal/goarch
compile: linux/mips64le does not support -shared
# internal/goexperiment
compile: linux/mips64le does not support -shared
# unicode/utf8
compile: linux/mips64le does not support -shared
# math/bits
compile: linux/mips64le does not support -shared
# internal/race
compile: linux/mips64le does not support -shared
# internal/cpu
compile: linux/mips64le does not support -shared
# unicode
compile: linux/mips64le does not support -shared
# sync/atomic
compile: linux/mips64le does not support -shared
# runtime/internal/atomic
compile: linux/mips64le does not support -shared
# runtime/internal/syscall
compile: linux/mips64le does not support -shared
```
### dylib
```shell
go build -tags "cxterm_parser" -o libs/xterm-linux-mips64le/libxterm.so -buildmode=c-shared xterm/cxterm/cxterm.go
-buildmode=c-shared not supported on linux/mips64le
```

**Comment by zpavlinovic** [comment]
Also, it is not currently clear how this issue is related to x/vuln and vulncheck/vulndb.

**Comment by seankhliao** [comment]
Duplicate of #43264
