### ISSUE TITLE
x/exp/jsonrpc2: data race

### ISSUE THREAD

**Issue by maxatome** [golang/go#56130]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.1 freebsd/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/xxx/.cache/go-build"
GOENV="/home/xxx/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="freebsd"
GOINSECURE=""
GOMODCACHE="/home/xxx/go/pkg/mod"
GOOS="freebsd"
GOPATH="/home/xxx/go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go119"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go119/pkg/tool/freebsd_amd64"
GOVCS=""
GOVERSION="go1.19.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="cc"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1731022611=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

`go test -race` on complex unit tests using `golang.org/x/exp/jsonrpc2` as an external dependency.

### What did you expect to see?

No data race.

### What did you see instead?

A data race in jsonrpc2/conn.go line 312.

https://go-review.googlesource.com/c/exp/+/412334 fixes the problem.

**Comment by bcmills** [comment]
Fixed by [CL 412334](https://go.dev/cl/412334).
