### ISSUE TITLE
cmd/compile: libFuzzer instrumentation fakePC overflow on 386 arch

### ISSUE THREAD

**Issue by cuonglm** [golang/go#56141]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.20-4274ffd4b8 Tue Oct 11 04:04:13 2022 +0000 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

Compile following program with `-d=libfuzzer`:

```
package p

func f(x, y int) {
	_ = x > y
	_ = y > x
}
```

### What did you expect to see?

Compile ok.

### What did you see instead?

```
$ GOOS=linux GOARCH=386 go tool compile -d=libfuzzer p.go
p.go:5:8: constant 3550266861 overflows int
```

**Comment by cuonglm** [comment]
@randall77 @mdempsky seems we need to backport this, it affect `go test -fuzz` on 386 arch.

**Comment by cuonglm** [comment]
Re-open for backport consideration.

cc @randall77 @mdempsky

**Comment by randall77** [comment]
@gopherbot please open a backport to 1.19. This bug causes libfuzzer mode to fail to compile. There is no easy workaround.
(I don't think this applies to 1.18.)

**Comment by cuonglm** [comment]
> @gopherbot please open a backport to 1.19. This bug causes libfuzzer mode to fail to compile. There is no easy workaround.
> 
> (I don't think this applies to 1.18.)
> 
> 

Yes, this does not happen in go1.18 release. The libfuzzerTrace* and friends are added in 1.19
