### ISSUE TITLE
x/text: internal compiler error from unicode/norm/tables13.0.0.go:21:5 

### ISSUE THREAD

**Issue by tmccombs** [golang/go#56143]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Unknown

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

I tried to build [hcl2json](https://github.com/tmccombs/hcl2json) using it's [Dockerfile](https://github.com/tmccombs/hcl2json/blob/main/Dockerfile), with the command:

```
podman build .
```
 

### What did you expect to see?

A successful compilation

### What did you see instead?

An internal compiler error:
 
 ```
 [1/2] STEP 9/10: RUN go get .
go: downloading github.com/zclconf/go-cty v1.11.0
go: downloading github.com/hashicorp/hcl/v2 v2.13.0
go: downloading github.com/apparentlymart/go-textseg/v13 v13.0.0
go: downloading golang.org/x/text v0.3.7
go: downloading github.com/apparentlymart/go-textseg v1.0.0
go: downloading github.com/agext/levenshtein v1.2.3
go: downloading github.com/mitchellh/go-wordwrap v1.0.1
--> 89d64a9c5dc
[1/2] STEP 10/10: RUN go build -a -ldflags '-s' -o /hcl2json .
# golang.org/x/text/unicode/norm
/root/go/pkg/mod/golang.org/x/text@v0.3.7/unicode/norm/tables13.0.0.go:21:5: internal compiler error: panic: runtime error: invalid memory address or nil pointer dereference
```

When I ran it again, it succeeded.

**Comment by seankhliao** [comment]
I can't reproduce this with the given dockerfile or with just the repo

**Comment by tmccombs** [comment]
After seeing some other random crashes, I checked my RAM, and it turns out I was having memory faults. That is probably what caused this. I'll close.
