### ISSUE TITLE
affected/package: os

### ISSUE THREAD

**Issue by BhanuKiranChaluvadi** [golang/go#56148]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.19
</pre>

### Does this issue reproduce with the latest release?
I am not sure, If this is the case with previous versions of go

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/bkch/go/bin"
GOCACHE="/home/bkch/.cache/go-build"
GOENV="/home/bkch/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/bkch/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/bkch/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3828613201=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

 I am trying to create a directory with 0766(drwxrw-rw-) permissions in root directory. 

Here is the code

```
package main

import (
	"fmt"
	"os"
	"path/filepath"
)

const (
	base_path         string = "/applications/bin/contributions"
	installation_path string = "robot/gripper"
)

func main() {
	fmt.Println("Creating folder structure")
	err := os.MkdirAll(filepath.Join(base_path, installation_path), 0766)
	// err := os.MkdirAll(filepath.Join(base_path, installation_path), 0755)
	if err != nil {
		fmt.Println(err.Error())
	}
}
```

### What did you expect to see?
Output folder has same permissions as metioned in program else through an error.

### What did you see instead?
output folder is of 0744 (drwxr--r--) permission and do not through an error.

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.
