### ISSUE TITLE
net: "127.0.0.1:" should be an invalid tcp4 address for ResolveTCPAddr

### ISSUE THREAD

**Issue by 7a6bb3ef3** [golang/go#56144]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.1 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/zhoudaxing/Library/Caches/go-build"
GOENV="/Users/zhoudaxing/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/zhoudaxing/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/*/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io,direct"
GOROOT="/Users/*/go1.19.1"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/Users/*/go1.19.1/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="0"
GOMOD="*"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/d0/4_y_gtss2wsfct5v6f6k0zcw0000gn/T/go-build3948008299=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

https://go.dev/play/p/KWM001uZ1aA
```
func main() {
	a, e := net.ResolveTCPAddr("tcp4", "127.0.0.1:")
	if e != nil {
		panic(e)
	}
	print(a.String())
}
```

### What did you expect to see?
error is not nil and program panic.

### What did you see instead?
127.0.0.1:0
Program exited.

**Comment by 7a6bb3ef3** [comment]
Hi ,i just found that "127.0.0.1:" is a valid tcp4 address for `net. ResolveTCPAddr `.
and i don't konw if that is correct or not ,if there is any specification about tcp4 addr i'm glad to konw.

I investigated this issue:
`net.SplitHostPort("127.0.0.1:")` return a nil error and zero-value port, `SplitHostPort` do not validate port and it is ok ,but an empty port string should be treated as error.

**Comment by thediveo** [comment]
why should ":" constitute a valid IPv4 address, with it not being defined in any textual IPv4 address representation.

**Comment by 7a6bb3ef3** [comment]
> why should ":" constitute a valid IPv4 address, with it not being defined in any textual IPv4 address representation.

yes ,it should be invalid ,but in my case it is a valid tcp4 addr. Maybe i should change the title.

**Comment by Jack-Kingdom** [comment]
<img width="661" alt="Screen Shot 2022-10-12 at 3 31 40 AM" src="https://user-images.githubusercontent.com/10584772/195181959-b0e73cf0-8b1c-4081-99fc-c4e562b9f005.png">

this func assume port is zero if not provide

**Comment by seankhliao** [comment]
Working as intended, see #13610

**Comment by 7a6bb3ef3** [comment]
maybe i misunderstood something ,but it is nothing about `parsePort` and the problem is `SplitHostPort` treats empty port string(xxx.xxx.xxx.xxx:) as 0. I don't think that's what we expected.
