### ISSUE TITLE
net: go resolver on Windows takes disabled interfaces' DNS nameservers 

### ISSUE THREAD

**Issue by zhzy0077** [golang/go#56160]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.2 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\xxx\AppData\Local\go-build
set GOENV=C:\Users\xxx\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\xxx\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\xxx\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.19.2
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\xxx\Code\gosample\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\xxx\AppData\Local\Temp\go-build106667779=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
1. Create a network interface like VPN or so, but do not connect to it, i.e. disable the interface.
2. Run code below:
```golang
package main

import (
	"context"
	"fmt"
	"net"
)

func main() {
	c := context.TODO()

	r := &net.Resolver{
		PreferGo: true,
	}

	fmt.Println(r.LookupNetIP(c, "ip", "www.google.com"))
}
```

### What did you expect to see?
Go uses the go resolver and picks the active interfaces nameserver.

### What did you see instead?
Go starts with the nameserver configured at disabled network interface.

It is because the code [here](https://github.com/golang/go/edit/master/src/net/dnsconfig_windows.go#L33) doesn't filter network interfaces by its operating status as per the [docs](https://learn.microsoft.com/en-us/windows/win32/api/iptypes/ns-iptypes-ip_adapter_addresses_lh)

**Comment by seankhliao** [comment]
cc @ianlancetaylor @neild
