### ISSUE TITLE
net/http/client.go

### ISSUE THREAD

**Issue by laihanhua** [golang/go#56170]
### What version of Go are you using (`go version`)?

<pre>
go1.14

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/lhh/Library/Caches/go-build"
GOENV="/Users/lhh/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/lhh/.gvm/pkgsets/go1.14.12/global"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/lhh/.gvm/gos/go1.14.12"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/lhh/.gvm/gos/go1.14.12/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"

</pre></details>

### What did you do?

I set client:=http.Client{Timeout: time.Duration(10 * time.Second)}，but when concurrent requests(1000qps) tls connection，
some requests time out for a long time, and the timeout seems to be out of control

**Comment by laihanhua** [comment]
code:
```
   c:=timeouthttp.New(time.Duration(1 * time.Second))
    comment := ctx.Value("lhh")
    req, err := http.NewRequest("GET", url, nil)
    if err != nil {
        return nil, err
    }
   trace := &httptrace.ClientTrace{
        DNSStart: func(dnsInfo httptrace.DNSStartInfo) {
            fmt.Printf("%v dns start: %v\n", comment, time.Now())
        },
        DNSDone: func(dnsDoneInfo httptrace.DNSDoneInfo) {
            fmt.Printf("%v dns end: %v\n", comment, time.Now())
        },

        ConnectStart: func(network, addr string) {
            fmt.Printf("%v ConnectStart: %v\n", comment, time.Now())
        },

        ConnectDone: func(network, addr string, err error) {
            fmt.Printf("%v ConnectDone: %v\n", comment, time.Now())
        },

        TLSHandshakeStart: func() {
            fmt.Printf("%v TLSHandshakeStart: %v\n", comment, time.Now())
        },

        TLSHandshakeDone: func(state tls.ConnectionState, err error) {
            fmt.Printf("%v TLSHandshakeDone: %v\n", comment, time.Now())
        },

        GetConn: func(hostPort string) {
            fmt.Printf("%v GetConn: %v\n", comment, time.Now())
        },

        GotConn: func(httptrace.GotConnInfo) {
            fmt.Printf("%v GotConn: %v\n", comment, time.Now())
        },
    }
    ctx = httptrace.WithClientTrace(ctx, trace)
    c.ContextDo(ctx, req)
```

85149_1665546458_6479  GetConn: 2022-10-12 11:47:39.337179 +0800 CST m=+15.558445406
85149_1665546458_6479  GotConn: 2022-10-12 11:47:39.340332 +0800 CST m=+15.561599015
85149_1665546458_6479  dns start: 2022-10-12 11:47:39.337246 +0800 CST m=+15.558512764
85149_1665546458_6479  dns end: 2022-10-12 11:47:39.361864 +0800 CST m=+15.583130468
85149_1665546458_6479  ConnectStart: 2022-10-12 11:47:39.361915 +0800 CST m=+15.583181071
85149_1665546458_6479  ConnectDone: 2022-10-12 11:47:42.163672 +0800 CST m=+18.384853577
85149_1665546458_6479  TLSHandshakeStart: 2022-10-12 11:47:42.197607 +0800 CST m=+18.418787900

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.

**Comment by laihanhua** [comment]
您好，我是赖汉华，我已收到你的邮件，辛苦了！
