### ISSUE TITLE
os: document that WriteFile is not atomic

### ISSUE THREAD

**Issue by mvdan** [golang/go#56173]
As I was replying to https://github.com/golang/go/issues/56172, I was looking at the docs for https://pkg.go.dev/os#WriteFile, which say:

```
// WriteFile writes data to the named file, creating it if necessary.
// If the file does not exist, WriteFile creates it with permissions perm (before umask);
// otherwise WriteFile truncates it before writing, without changing permissions.
func WriteFile(name string, data []byte, perm FileMode) error {
```

I know that this operation isn't atomic: for example, if a write to the file fails half-way through, we may be left with a partial file. That is why alternatives like https://pkg.go.dev/github.com/google/renameio#WriteFile exist.

However, by just reading the docs as a new user, it could be an easy misconception. A lot of the other `os` APIs like `Create`, `Mkdir`, or `Chmod` are atomic at the system level - they only perform a single system call which modifies the filesystem, so we can't be left with partial changes.

Perhaps we should add a godoc note that the API is not atomic. That is, that if an error occurs, the file might be left behind. I imagine this won't matter for many cases, but the warning would be very useful for any Go program which cares about invalid or incomplete states.

cc @ianlancetaylor @stapelberg

**Comment by mvdan** [comment]
Trying to think about what other `os` operations modify the filesystem in multiple steps. `MkdirAll` and `RemoveAll` come to mind, but I don't think we need to worry about `RemoveAll` because it is already a destructive operation by design.

**Comment by jacobishao** [comment]
as far as I know, open the file in append mode, then call `WriteFile` to write data is atomic.

**Comment by mvdan** [comment]
@jacobishao that doesn't make sense to me. `WriteFile` takes a path to a file, not an `*os.File`, so you can't choose to open the file in append mode. I also don't think opening the file in any one mode would result in atomic writes - the first write could fail, for example, leaving the file behind.

**Comment by yujiri8** [comment]
Tbf I don't think this really needs to be documented. If you know how syscalls work it should be obvious that it can't be atomic because it needs an open syscall.

**Comment by mvdan** [comment]
@yujiri8 the API doesn't require the operation to not be atomic; see https://pkg.go.dev/github.com/google/renameio#WriteFile. A Go user can read the code behind `os.WriteFile` and figure out that it's not atomic, but most users will just read the documentation.

I don't think there's a need to document whether every OS or I/O API is atomic or not, just like we don't document whether every API is safe for concurrent use, but I think in this case the current documentation is somewhat prone to being misunderstood.

**Comment by ianlancetaylor** [comment]
Updating the docs sounds good to me.

**Comment by SrijanSriv** [comment]
i would imagine that the docs require a clear heads up just to draw attention, which will be enough to connect the dots. should it discuss/link the alternatives?

**Comment by jacobishao** [comment]
> @jacobishao that doesn't make sense to me. `WriteFile` takes a path to a file, not an `*os.File`, so you can't choose to open the file in append mode. I also don't think opening the file in any one mode would result in atomic writes - the first write could fail, for example, leaving the file behind.

sorry. it's `Write` method of `*os.File`, not `os.WriteFile`. but if you do `man open`, you will see
![image](https://user-images.githubusercontent.com/8140244/195573445-a1baeba1-4542-4006-83a3-53b05c96e520.png)
but it has nothing to do with `os.WriteFile` we discussed here.

**Comment by KaithyRookie** [comment]
How about adding a comment like this:
`// Note that WriteFile does not guarantee atomicity, if file writing fails halfway through, the file content will be incomplete`

**Comment by ianlancetaylor** [comment]
@SrijanSriv The docs for `os.WriteFile` should not discuss alternatives.  That's not the place for that.  Docs should be accurate but short.
