### ISSUE TITLE
x/tools/gopls: improvements to package renaming

### ISSUE THREAD

**Issue by findleyr** [golang/go#56184]
This issue tracks improvements to package renaming that we are aiming to land in gopls@v0.11.0, namely:

- [x] Add a test for the case when the renaming package's path contains "internal" as a segment.
- [x] Don't rename subpackages that don't belong to the same module with the renaming package (e.g. if we're renaming lib->lib1 and lib/submod is a sub module, then we should not rename packages in lib/submod -- this may actually work already but needs verification)
- [x] Check the go.mod files in the workspace to see if any replace directives need to be fixed if the renaming affects the locations of any go.mod files (e.g. in the previous step, any replace directives pointing at lib/submod need to be updated).

**Comment by bcmills** [comment]
>  Reject renaming if the renamed subpackages don't belong to the same module with the renaming package

Hmm. I think it should be fine to rename across modules as long as both modules are in the workspace..?

**Comment by uh-zz** [comment]
I was looking forward to this feature!

I tried package rename in the following environment and it seems that the renamed file is newly created and the original file is deleted.
Is this expected behavior?

Visual Studio Code v1.72.2
golang.org/x/tools/gopls v0.10.0

**Comment by findleyr** [comment]
@uh-zz yes, this is how VS Code handles the RenameFile operation. Unfortunately, I believe this is out of our control.

**Comment by findleyr** [comment]
I've updated the tasks here to separate the feature request of supporting arbitrary renaming of package paths into #57171.

**Comment by findleyr** [comment]
@dle8 anything more to do here?

**Comment by dle8** [comment]
No I think we can close this issue!
