### ISSUE TITLE
x/vuln/cmd/govulncheck: surface a "fixed" version when the fix is in a subsequent major version

### ISSUE THREAD

**Issue by julieqiu** [golang/go#56206]
There are reports with no fixed version in a module, but a fix exists in the next major version. We should find a way to surface this info in govulncheck

Example (https://vuln.go.dev/ID/GO-2022-0386.json):

```
  - module: github.com/nats-io/jwt
    versions:
      - fixed: 1.2.3-0.20210314221642-a826c77dc9d2
    vulnerable_at: 1.2.2
    packages:
      - package: github.com/nats-io/jwt
        ...
  - module: github.com/nats-io/jwt/v2
    versions:
      - fixed: 2.0.1
    vulnerable_at: 2.0.0
    packages:
      - package: github.com/nats-io/jwt/v2
      ...
```

**Comment by zpavlinovic** [comment]
Based on offline discussion, we decided to not add this. Suggesting subsequent major version might introduce a breaking change. Folks should really do their investigation on pkg.go.dev.
