### ISSUE TITLE
unsafe: Allocated object address changed

### ISSUE THREAD

**Issue by cocotyty** [golang/go#56209]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOOS="linux"
</pre></details>

### What did you do?

https://go.dev/play/p/XvMkBVE5b7Y
```go
package main

import (
	"log"
	"unsafe"
)

func main() {
	h := new(Array)
	ptr := uintptr(unsafe.Pointer(h))
	show(h)
	ptr2 := uintptr(unsafe.Pointer(h))
	show(h)
	ptr3 := uintptr(unsafe.Pointer(h))
	log.Println(ptr, ptr2, ptr3)
}

func show(t *Array) {
	log.Println((*t)[1])
}

type Array [399]int

```

### What did you expect to see?
These three pointer value are the same.

### What did you see instead?

The first value is not the same as the second and the third one.

**Comment by mateusz834** [comment]
```
./main.go:9:10: new(Array) does not escape
./main.go:11:6: ... argument does not escape
./main.go:11:6: (*t)[1] escapes to heap
./main.go:13:6: ... argument does not escape
```
Looks like h is on the stack. And probably log.Println() causes the stack to grow.

**Comment by cocotyty** [comment]
> ```
> ./main.go:9:10: new(Array) does not escape
> ./main.go:11:6: ... argument does not escape
> ./main.go:11:6: (*t)[1] escapes to heap
> ./main.go:13:6: ... argument does not escape
> ```
> 
> Looks like `h` is on the stack. And probably `log.Println()` causes the stack to grow (so the pointers change).

Thank you for your help 👍
