### ISSUE TITLE
access: add new members to port-maintainers/s390x team

### ISSUE THREAD

**Issue by jonathan-albrecht-ibm** [golang/go#56216]
We have two new developers that will be helping to maintain the s390x port. Please add:

@Vishwanatha-HD
@srinivas-pokala

to https://github.com/orgs/golang/teams/s390x

I'm not sure if this is done automatically but they are not yet members of the Go org or the go-assignees team; please also add them to those memberships if possible.

**Comment by bcmills** [comment]
Done. They should have both received invitations from GitHub — please let me know if those don't work.

**Comment by Vishwanatha-HD** [comment]
Thanks Jonathan and Bryan.. We are now added to "Go" team "go-assignees"...
