### ISSUE TITLE
httputil.NewSingleHostReverseProxy panic with http.ErrAbortHandler on cancel request

### ISSUE THREAD

**Issue by paullaffitte** [golang/go#56228]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/paul/go/bin"
GOCACHE="/home/paul/.cache/go-build"
GOENV="/home/paul/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/paul/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/paul/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3895889062=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I have a reverse proxy, if I curl it and `ctrl+c` before receiving the response, I got weird errors as follow :

```
2022/10/14 16:40:28 [Recovery] 2022/10/14 - 16:40:28 panic recovered:
GET /v2/xxxxxxx
HTTP/1.1
Host: localhost:8082
Accept: */*
Authorization: *
User-Agent: curl/7.81.0
X-Forwarded-For: 127.0.0.1


net/http: abort Handler
/usr/local/go/src/net/http/httputil/reverseproxy.go:349 (0x71d468)
	(*ReverseProxy).ServeHTTP: panic(http.ErrAbortHandler)
/home/paul/dev/internal/docker-cache-registry/internal/proxy/server.go:179 (0x11cc52e)
	(*Proxy).proxyRegistry: proxy.ServeHTTP(c.Writer, c.Request)
/home/paul/dev/internal/docker-cache-registry/internal/proxy/server.go:96 (0x11cbf24)
	(*Proxy).routeProxy: p.proxyRegistry(c, "https://"+originRegistry, true, basicAuth)
/home/paul/go/pkg/mod/github.com/gin-gonic/gin@v1.7.3/context.go:165 (0x9008a1)
	(*Context).Next: c.handlers[c.index](c)
/home/paul/go/pkg/mod/github.com/gin-gonic/gin@v1.7.3/recovery.go:99 (0x90088c)
	CustomRecoveryWithWriter.func1: c.Next()
/home/paul/go/pkg/mod/github.com/gin-gonic/gin@v1.7.3/context.go:165 (0x8ff9c6)
	(*Context).Next: c.handlers[c.index](c)
/home/paul/go/pkg/mod/github.com/gin-gonic/gin@v1.7.3/logger.go:241 (0x8ff9a9)
	LoggerWithConfig.func1: c.Next()
/home/paul/go/pkg/mod/github.com/gin-gonic/gin@v1.7.3/context.go:165 (0x8fea7d)
	(*Context).Next: c.handlers[c.index](c)
/home/paul/go/pkg/mod/github.com/gin-gonic/gin@v1.7.3/gin.go:489 (0x8fe705)
	(*Engine).handleHTTPRequest: c.Next()
/home/paul/go/pkg/mod/github.com/gin-gonic/gin@v1.7.3/gin.go:445 (0x8fe264)
	(*Engine).ServeHTTP: engine.handleHTTPRequest(c)
/usr/local/go/src/net/http/server.go:2916 (0x6d815a)
	serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
/usr/local/go/src/net/http/server.go:1966 (0x6d3156)
	(*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
/usr/local/go/src/runtime/asm_amd64.s:1571 (0x4653e0)
	goexit: BYTE	$0x90	// NOP

[GIN-debug] [WARNING] Headers were already written. Wanted to override status code 200 with 500
```

### What did you expect to see?

I don't want my server to panic and print those awful errors if everything is fine (I just didn't wait for the response, it should not break anything, imagine someone close his browser before the page is fully loaded...)

### What did you see instead?

The above error message.

**Comment by chrisguiney** [comment]
As far as I'm aware, this is actually expected behavior.  Because headers are already sent and the streaming copy of the body has already started, there's not really anything else that the handler can do to alert of an error.

I've dealt with it by having a recovery middleware to detect it, something along the lines of

```
func (next http.Handler) http.HandlerFunc {
	return func(w http.RresponseWriter, r http.Request) {
		defer func() {
			if p := recover(); p != nil {
				if err, ok := p.(error); ok {
					if errors.Is(err, http.ErrAbortHandler) {
						return
					}
				}
				panic(p)
			}
		}()
		next.ServeHTTP(w, r)
	}
}
```

**Comment by paullaffitte** [comment]
It indeed works. From what I understand this error arise when the client left so I guess we don't have to bother about the status being the wrong one (200 when it should be 500). `http.Server` already [handle this case](https://github.com/golang/go/issues/28239#issuecomment-430381086) but `gin` looks to not handle this correctly so it's fine to handle it manually.

Thanks! I consider the issue resolved for me so I will close this issue.

**Comment by pboiseau** [comment]
I got into the same problem with reverse proxy for SSE and usage of gin gonic as http server. 

If you use the gin gonic recovery middleware you will get the panic / recover stack trace.

I deal with it by removing the gin recovery middleware and do a custom one like this : 

```go
func customRecoveryMiddleware() gin.HandlerFunc {
	return func(c *gin.Context) {
		defer func() {
			if p := recover(); p != nil {
				if err, ok := p.(error); ok {
					// ignore panic abort handler for text/event-stream SSE
					if errors.Is(err, http.ErrAbortHandler) {
						return
					}
				}
				c.AbortWithStatus(http.StatusInternalServerError)
			}
		}()
		c.Next()
	}
}
```
