### ISSUE TITLE
builtin: recover returns nil in an anonymous function from an variable

### ISSUE THREAD

**Issue by maranqz** [golang/go#56254]
### What version of Go are you using (`go version`)?

<pre>
1.19, 1.18

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/maranqz/Library/Caches/go-build"
GOENV="/Users/maranqz/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/maranqz/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/iasergunin/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/iasergunin/go/go1.19"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/maranqz/go/go1.19/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/g_/t4zy6gcj5hj6g9_hrykqswwr0000gn/T/go-build3751429232=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

I creates  and puts an anonymous function in a variable. Then, I uses the variable in defer function to recover panic. 

https://go.dev/play/p/w5yIvY-q5BL

### What did you expect to see?

Recovery returns a message from the panic.

### What did you see instead?

Recovery returns nil and program shutdown with the panic.

**Comment by maranqz** [comment]
Use the code to fix it.
https://go.dev/play/p/ZLHAxy4yMoF

**Comment by domenicomastrangelo** [comment]
This fixes your isse without modifying the code too much

`package main

import "fmt"

func printRecoverer() func() {
	return func() {
		fmt.Println("print", recover())
	}
}

func main() {
	d := printRecoverer()

	defer d()

	panic("panic")
}
`

**Comment by maranqz** [comment]
I needs to commit or rollback of a transaction and return err if it happens.

That is why I needs to func(){}() in defer.

https://go.dev/play/p/pGFLbrRWe58

**Comment by maranqz** [comment]
I think I misunderstands recover because my case differs from docs explanation, isn't it?

Docs says: `recover was not called directly by a deferred function.`

https://go.dev/ref/spec#Handling_panics

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
