### ISSUE TITLE
x/tools: depends on non-go-team library

### ISSUE THREAD

**Issue by aldas** [golang/go#56266]
`x/tools` depends on `github.com/yuin/goldmark` library which is unlike all other dependencies owned by non-go team.  Is not this potentially problematic or even unsafe for the community?

I see this because `golang.org/x/net` depends on `golang.org/x/text` it depends on `golang.org/x/tools` and now `goldmark` end up in your `go.sum`

https://github.com/golang/tools/blob/9b5e55b1a7e215a54c9784492d801104a8381a91/go.mod#L6

**Comment by rsc** [comment]
The use of goldmark is limited to the 'present' package and tool (as well as x/website for go.dev itself), so there is no safety problem for the vast majority of uses. In particular, if you are only using x/net or x/text, then you are not importing goldmark in any way. The long term plan is to remove the use of goldmark, which is only an implementation detail of those packages.

That said, if you are seeing goldmark in your go.sum file, I think that means your go.mod file says "go 1.16" or earlier and is not using [pruned module graphs](https://go.dev/doc/go1.17#go-command). If so, then as documented in the release notes I linked, you can run 'go mod tidy -go=1.17' (or 1.18 or 1.19) to update your go.mod file without affecting selected dependency versions.

If your go.mod already says 'go 1.17' or later, then you may just need to run 'go mod tidy' to clean up go.sum.

**Comment by seankhliao** [comment]
Closing as this is known and intentional.
