### ISSUE TITLE
x/exp/mmap: mapping 0 length file is already closed

### ISSUE THREAD

**Issue by robaho** [golang/go#56261]
<pre>
go version go1.19.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
amd64, intel i7
</pre></details>

If you use mmap to map  a file of 0 length, any future usage of the mapped file results in an error `mmap: closed`

The offending code is:

```
	size := fi.Size()
	if size == 0 {
		return &ReaderAt{}, nil
	}
```

in mmap_unix.go, in `func Open(filename string) (*ReaderAt, error)` - lines 92-95.

I don't think this is correct or expected behavior. You should be able to mmap a zero length file and use it.

**Comment by dr2chase** [comment]
Simple as this is, a reproducer would still be nice.

**Comment by robaho** [comment]
I will add one this evening.

**Comment by robaho** [comment]
Attaching test case. Notice that 0 length file returns 'closed', while a non-zero file returns the expected EOF.

**Comment by ianlancetaylor** [comment]
CC @nigeltao who originally wrote x/exp/mmap.
