### ISSUE TITLE
go: why "initialization loop for componentHandlers" 

### ISSUE THREAD

**Issue by mei-rune** [golang/go#56262]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.19.2
</pre>

### Does this issue reproduce with the latest release?

https://go.dev/play/p/Fsutyphj3a-

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

compile the code.

### What did you expect to see?

compile success

### What did you see instead?

compile fail

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.

**Comment by mei-rune** [comment]
https://github.com/golang/go/issues/1817
