### ISSUE TITLE
fmt: unexpected fault address 0x0

### ISSUE THREAD

**Issue by arch3754** [golang/go#56265]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.2 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/lib/golang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build275872546=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

<img width="961" alt="image" src="https://user-images.githubusercontent.com/16916249/196117011-e4a08e2a-fa69-4348-9687-6b95ff18c795.png">

Is there a known repair or workaround

**Comment by arch3754** [comment]
I have not been able to find a consistent repro for this, It happens about 1/100000 of the time when running the program over a large service.

**Comment by dr2chase** [comment]
This needs more information, please.  What program?  What service?  Is cgo or unsafe code involved?  Have you tried the race detector?

**Comment by arch3754** [comment]
For a service requested by a batch of rpc clients, a log is printed after each request is completed. The error is reported when the network request reports an error, not involving cgo and unsafe code

**Comment by ZekeLu** [comment]
Is it possible to run your code with the race detector enabled, as suggested by dr2chase@ ?. See https://go.dev/blog/race-detector.

**Comment by arch3754** [comment]
> Is it possible to run your code with the race detector enabled, as suggested by dr2chase@ ?. See https://go.dev/blog/race-detector.

There should be no race. Each request is an independent goroutine. The log is also independent in goroutine. The error "err" is also declared independently

**Comment by arch3754** [comment]
The project returns an error in the production environment for a few days, which cannot be reproduced in the test environment at present

**Comment by ZekeLu** [comment]
Maybe the access to `e.Source` (line `482`) is racy?

https://github.com/golang/go/blob/819087624072fe8ca5914668e837d18eb231f04e/src/net/net.go#L473-L494

**Comment by arch3754** [comment]
This error is returned by the "conn. Write" or "DialTimeout" method of the "net" package. I'm not sure which one it is

**Comment by arch3754** [comment]
This error is returned by the "conn. Write" or "DialTimeout" method of the "net" package. I'm not sure which one it is
