### ISSUE TITLE
access: add new member to GitHub approvers and windows groups

### ISSUE THREAD

**Issue by qmuntal** [golang/go#56288]
Hi,

I'd like to request access for the following GitHub groups:

- [go-assignees](https://github.com/orgs/golang/teams/go-assignees)
- [go-approvers](https://github.com/orgs/golang/teams/go-approvers)
- @golang/windows

@alexbrainman @bcmills 

See https://go.dev/wiki/GithubAccess

**Comment by bcmills** [comment]
I've added you to `@golang/go-assignees` and `@golang/windows`. (The `go-approvers` access has a slightly different approval flow, so I can't just go ahead and do that one.)

**Comment by dr2chase** [comment]
I took the first step on that approval flow.

**Comment by heschi** [comment]
Approved for go-approvers.

As a reminder, please be sure to review https://go.dev/wiki/Gardening and https://go.dev/wiki/HandlingIssues as part of helping garden issues. If uncertain about something, don't hesitate to ask.

Thanks for your contributions!
