### ISSUE TITLE
x/time/rate: alternating AllowN before last and after last can create new tokens

### ISSUE THREAD

**Issue by tentree** [golang/go#56287]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
PS D:\code\src\yangr\rate> go env
set GO111MODULE=auto
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\yangr\AppData\Local\go-build
set GOENV=C:\Users\yangr\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\yangr\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\yangr\go
set GOPRIVATE=
set GOPROXY=https://goproxy.io
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.18
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\code\src\yangr\rate\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\yangr\AppData\Local\Temp\go-build38909240=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

```go
package main

import (
	"fmt"
	"golang.org/x/time/rate"

	"time"
)

func main() {
	limiter := rate.NewLimiter(rate.Every(time.Second/1), 10)

	t0 := time.Now()
	t1 := time.Now().Add(-time.Second * 2)

	t := t0
	for limiter.AllowN(t, 1) {
		if t == t0 {
			t = t1
		} else {
			t = t0
		}
	}

	fmt.Println("exit")
}
```
### What did you expect to see?
Exit loop

### What did you see instead?
Always loop.

mark:
i also use the fixed(https://github.com/ZekeLu/time/commit/127e7a41be4d57aa3254fa7faa3673dec5ce8a6d) of https://github.com/golang/go/issues/52584, but it did not work.

**Comment by dr2chase** [comment]
@bcmill, @ianlancetaylor can you give this a look?

**Comment by bcmills** [comment]
`x/time/rate` is more @Sajmani...

**Comment by ZekeLu** [comment]
I think this is work as designed. It's covered by the test ` TestLimiterJumpBackwards` (https://github.com/golang/time/blob/f3bd1da661afd6357b957af27c50ccdb248b7dd3/rate/rate_test.go#L124-L138). On line 127, it jumps backward from **t1** to **t0**. And then on line 131, it jumps forward from **t0** to **t1**, and it **got a new token**.

In your demo, every time it jumps from t1 to t0, it gets two new tokens. That's why the available tokens never reduce to 0.

By the way, @tentree please change your comment to put your code into a [fenced code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks):

<pre>
```go
package main

import (
	"fmt"
	"time"

	"golang.org/x/time/rate"
)

func main() {
	limiter := rate.NewLimiter(1, 10)

	t0 := time.Now()
	t1 := time.Now().Add(-time.Second * 2)

	t := t0
	for limiter.AllowN(t, 1) {
		if t == t0 {
			t = t1
		} else {
			t = t0
		}
	}

	fmt.Println("exit")
}
```
</pre>

**Comment by tentree** [comment]
> 
since `t1` to `t0` could got new tokens, i think `t0` back to `t1` also could reduce tokens.  This is what I'm confused about.

**Comment by tentree** [comment]
> I think this is work as designed. It's covered by the test ` TestLimiterJumpBackwards` (https://github.com/golang/time/blob/f3bd1da661afd6357b957af27c50ccdb248b7dd3/rate/rate_test.go#L124-L138). On line 127, it jumps backward from **t1** to **t0**. And then on line 131, it jumps forward from **t0** to **t1**, and it **got a new token**.
> 
> In your demo, every time it jumps from t1 to t0, it gets two new tokens. That's why the available tokens never reduce to 0.
> 
> By the way, @tentree please change your comment to put your code into a [fenced code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks):
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> 	"time"
> 
> 	"golang.org/x/time/rate"
> )
> 
> func main() {
> 	limiter := rate.NewLimiter(1, 10)
> 
> 	t0 := time.Now()
> 	t1 := time.Now().Add(-time.Second * 2)
> 
> 	t := t0
> 	for limiter.AllowN(t, 1) {
> 		if t == t0 {
> 			t = t1
> 		} else {
> 			t = t0
> 		}
> 	}
> 
> 	fmt.Println("exit")
> }
> ```

since t1 to t0 could got new tokens, i think t0 back to t1 also could reduce tokens. This is what I'm confused about.

**Comment by ZekeLu** [comment]
@tentree Please don't quote an entire comment unnecessarily. Jumping backward won't reduce the tokens. It's also covered by that same test (line 127, `jump back to t0, two tokens remain`).

**Comment by tentree** [comment]
@ZekeLu thanks , i may understand the designe of limiter.  back in the past just like fixed clock. the func with `N`（like AllowN） is just for testing easily, Is my understanding biased？

**Comment by ZekeLu** [comment]
In my opinion, the `time.Time` parameter in the `*N` funcs is just for testing. Regarding whether the tokens should be dropped when it jumps backwards, there is some interesting comments here: https://go-review.googlesource.com/c/time/+/16672/2..6/rate/rate.go#b65

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. Please close this issue if there is not bug. See https://github.com/golang/go/wiki/Questions.
