### ISSUE TITLE
err: strconv.ParseFloat: parsing "1234\n": invalid syntax

### ISSUE THREAD

**Issue by kaushikdharamshi** [golang/go#56290]
What version of Go are you using (go version)?
$ go version 1.18.4

Does this issue reproduce with the latest release?
What operating system and processor architecture are you using (go env)?
go env Output

What did you do?
we tried to read a file which contains a value using ioutil.Readfile /os.Readfile and parse the value using strconv.ParseFloat(string(value), 64)

What did you expect to see?
it should convert to float

What did you see instead?
err: strconv.ParseFloat: parsing "1234\n": invalid syntax

code snippet :
`package main

import (
	"fmt"
	"os"
	"strconv"
)

func main() {
	file := "test.txt" //. contains 1234
	dat, _ := os.ReadFile(file)
	data, err := strconv.ParseFloat(string(dat), 64)
}

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
