### ISSUE TITLE
cmd/compile: did not infer implementation[actual] passed to interface[generic]

### ISSUE THREAD

**Issue by vahid-sohrabloo** [golang/go#56294]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes. it does

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/vahid/.cache/go-build"
GOENV="/home/vahid/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/vahid/go/pkg/mod"
GONOPROXY="github.com/dolphinfms/*"
GONOSUMDB="github.com/dolphinfms/*"
GOOS="linux"
GOPATH="/home/vahid/go/"
GOPRIVATE="github.com/dolphinfms/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4148583324=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
https://go.dev/play/p/iTbFKExhVeZ

### What did you expect to see?
`B(&Imp[int64]{})` doesn't work and show `cannot infer T` error but `B[int64](&Imp[int64]{})`  works. But it can auto infer. in this example, the `T` of `B` is always `int64`

**Comment by dr2chase** [comment]
I think this is working-as-intended -- not everything that could be inferred, is inferred.

@griesemer or @mdempsky would know better.

**Comment by dr2chase** [comment]
My understanding of The Plan is that we want to let the current rules soak for a while, and see how things work as they are.  Once we extend an inference rule, we can't retract it, and there might be impacts on other parts of type inference, analysis time, other tools, error message quality, and perhaps readability (which is more important than write-ability).  We're still dealing with some of the long-tail problems of the generics addition (build speed, IR changes, export data changes, deciding how we feel about cyclic interfaces, and "comparable").

Anyhow, I'll close with working-as-intended-for-now.  We ought to revisit this in a year or so.

**Comment by griesemer** [comment]
Update: This works now on the dev branch (eventual Go 1.21).
