### ISSUE TITLE
x/pkgsite: package removal request for jotaen/kong-completion (@v1.0.0 and @v1.0.1)

### ISSUE THREAD

**Issue by jotaen** [golang/go#56306]
### What is the path of the package that you would like to have removed?

The path is [`jotaen/kong-completion`](https://pkg.go.dev/github.com/jotaen/kong-completion), and I’d like to have the versions [v1.0.0](https://pkg.go.dev/github.com/jotaen/kong-completion@v1.0.0) and [v1.0.1](https://pkg.go.dev/github.com/jotaen/kong-completion@v1.0.1) retracted. (So only these two specific versions, not the entire package!)

 
 
 
### Are you the owner of this package?

[Yes](https://github.com/jotaen/kong-completion).

 
### What is the reason that you could not retract this package instead?

Both v1 releases were by accident. I’m apparently not able to retract via a v0 release, [which I’ve tried (via @v0.0.4)](https://github.com/jotaen/kong-completion/blob/00881ad0daa2fd23cdd375c8ae581743596854f3/go.mod#L21-L24). Retracting via a `v1.0.2` release wouldn’t help me, because as I mentioned the v1 release shouldn’t have happened in the first place.

**Comment by seankhliao** [comment]
We can't retract versions for you.
And we can only hide the documentation for the entire module.
A v1.0.2 can retract itself.
