### ISSUE TITLE
Website :- Web Service Gin tutorial broken.

### ISSUE THREAD

**Issue by parkeradam** [golang/go#56304]
I am following this tutorial on the golang website
https://go.dev/doc/tutorial/web-service-gin

Upon getting to the point where it is adding an album, the call to BindJson is failing when i am making a call using the insomnia.rest client.

I am able to get it to deserialize to json when using the standard library json deserialization stuff (by googling) however as a newcomer to go it is strange this doesnt work.

Any help would be appreciated. Also if the issue is figure out could you please let me know.

Golang Version : 1.19
Gin Version: 1.8.1 (installed using go get)
Operating System: Windows 11 Home 22H2

I have also reported this on the gin repo [here](https://github.com/gin-gonic/gin/issues/3364) however reporting here also as it is a bad new developer experience. 

Many thanks.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by parkeradam** [comment]
I think this has been closed early, there as it is a bug/error on the golang website that prevents new developers from learning. While yes this also contains a queston from myself, it is as a new developer trying to get in to the ecosystem. @seankhliao , what do you think about this? Would it help if i removed my personal question and left it as an issue for the tutorial not functioning/working.
