### ISSUE TITLE
x/pkgsite: package removal request for https://pkg.go.dev/github.com/TheFern2/goplctag

### ISSUE THREAD

**Issue by TheFern2** [golang/go#56313]
### What is the path of the package that you would like to have removed?

https://pkg.go.dev/github.com/TheFern2/goplctag

 
 
 
### Are you the owner of this package?
Yes

 
### What is the reason that you could not retract this package instead?

TheFern2/goplctag repo was made private because it was colliding with the official repo. (I am also the repo mantainer) https://pkg.go.dev/github.com/libplctag/goplctag

**Comment by hyangah** [comment]
This is already removed.
