### ISSUE TITLE
x/vuln/client: revisit `Client` interface

### ISSUE THREAD

**Issue by hyangah** [golang/go#56312]
Currently `Client` is defined as:

```
type Client interface {
	GetByModule(context.Context, string) ([]*osv.Entry, error)
	GetByID(context.Context, string) (*osv.Entry, error)
	GetByAlias(context.Context, string) ([]*osv.Entry, error)
	ListIDs(context.Context) ([]string, error)
	LastModifiedTime(context.Context) (time.Time, error)
}
```

* Placing `Get` in getters is not common in Go code, how about renaming `Get*` methods to `EntriesByModule`?
* As the database grows, `ListIDs` response size will keep growing. Current size of this response from vuln.go.dev is ~3KB, so that may not be too concerning. However, the response itself does not contain sufficient info so I guess most clients will have to call `GetByID` for each id every time after `ListIDs`. (See [the example usage in x/pkgsite](https://github.com/golang/pkgsite/blob/873fb37c24799199f4b1e129bc425fa0490b1f8d/internal/frontend/vulns.go#L245-L257)) However, most entries will remain unchanged even when the database is updated (indicated by the `LastModifiedTime` change). Why don't we make `ListIDs` return the last modified timestamp for each osv.Entry too? (Similar to  vulnerability database `$base/index.json` endpoint provides (i.e. `(module path, timestamp)`-pairs).

**Comment by hyangah** [comment]
Another feature request from @alandonovan is the ability to batch lookups (e.g. GetByModule**s** that takes a batch of module names).

**Comment by zpavlinovic** [comment]
Duplicate of an internal issue.
