### ISSUE TITLE
x/pkgsite: https://pkg.go.dev/github.com/libplctag/goplctag Issue with licenses

### ISSUE THREAD

**Issue by TheFern2** [golang/go#56322]
I have an issue with the package in the title is go bindinds to a c library, the core libplctag library uses a dual license so not entirely sure if this is causing the issue or maybe because one license version is not on the list, the MPL-2.0.TXT license is on the list, but LGPL-2.0.TXT is not. Can someone point me in the right direction? I'd like for the package to show the documentation but won't show without registering the license.

@kyle-github

### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/libplctag/goplctag 
 
### What is your user agent?

[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36](https://developers.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)
 

 
 
 
### Screenshot
 

 
 
![image](https://user-images.githubusercontent.com/10265682/196732639-5fb57d85-649c-45db-810b-305a428affa7.png)

 
### What did you do?
 

 
 Added licenses to root directory.
 
### What did you expect to see?
 
 Documentation on the package webpage.
 
### What did you see instead?

Error on screenshot.

**Comment by seankhliao** [comment]
Please see the license policy link for the files pkgsite checks for licenses.

**Comment by TheFern2** [comment]
> Please see the license policy link for the files pkgsite checks for licenses.

I did checked the link, and I have licenses in the repo, hence why I opened this issue.

**Comment by TheFern2** [comment]
Nvm r/golang answered my question.

**Comment by TheFern2** [comment]
I've renamed as per license policy and still not working. Can someone look in the repo and tell me what's wrong?

Would be nice if there was an actual error in the package page other than just pointing to a license page.
