### ISSUE TITLE
access: Approving CLs ("approvers")

### ISSUE THREAD

**Issue by wdvxdr1123** [golang/go#56321]
I would like to request submit access on gerrit. I recently work on linux/riscv64.

Gerrit e-mail: wdvxdr@golangcn.org
Ref: https://go-review.googlesource.com/#/admin/groups/1005,members

See https://golang.org/wiki/GerritAccess

**Comment by dr2chase** [comment]
To clarify, you wish to be able to "approve"?  I see plenty of CLs submitted already.

**Comment by dr2chase** [comment]
In progress, for "approvers".

**Comment by heschi** [comment]
Hi @wdvxdr1123,

Thank you for contributing to the Go project! I've discussed this request with the team, and we agreed to grant you access. I've added you to the approvers groups now.

Please be familiar with the rules for voting and submitting changes as described at https://golang.org/wiki/GerritAccess#approver-access-approvers. If you're unsure or have any questions, please don't hesitate to ask us.

Thank you again for contributing, your help is greatly appreciated!
