### ISSUE TITLE
net/http: bad handling of HEAD requests with a body [1.18 backport]

### ISSUE THREAD

**Issue by dr2chase** [golang/go#56323]
This is a by-hand backport request to 1.18 for #53960.
We approved the #56154 (1.19 backport today) and by default backports target the last two releases, so this backport is also approved.

**Comment by neild** [comment]
The backport for the HTTP/1 fix was never merged, thanks to none of us noticing that Gopherbot had prematurely closed this issue (#29599). Since there won't be another 1.18 minor release, this is unfortunate but there's not much to be done about that at this point.
