### ISSUE TITLE
x/vuln/client: implement sanity check on the return value of `httpReadJSON`

### ISSUE THREAD

**Issue by hyangah** [golang/go#56333]
From "TODO" in https://github.com/golang/vuln/blob/41df7bda74f30fac0cab688927dab16df2f938eb/client/client.go#L314-L315:

The basic check is desirable since `json.Unmarshal` is too generous and types like `osv.Entry` allows `omitempty` for many fields. Assume that the client is built with an old version of golang.org/x/vuln/client, and vuln.go.dev decided to serve a slightly different `osv.Entry` (e.g. https://go-review.googlesource.com/c/vuln/+/424375) for some unforeseen reasons. The cache may be polluted with incomplete data.

**Comment by tatianab** [comment]
Obsolete with re-design of client
