### ISSUE TITLE
proposal: make interfaces holding nil pointers evaluate to NaN (Not a Nil)

### ISSUE THREAD

**Issue by robpike** [golang/go#56364]
There are two major problems writing Go programs that cause frequent confusion: The so called "nil error" problem (https://go.dev/doc/faq#nil_error), wherein a nil pointer stored in an interface is not equal to nil, even though it seems like it should be; and NaNs going into maps, which complicate matters because they never compare true to one another, violating a number of invariants around map behavior.

I suggest we make both these problems the same, by making an interface holding a nil pointer evaluate to NaN, thus never comparing true and reducing the confusion to a single problem rather than two. To make this easy to understand, we rename the NaN that results be a "not a nil" value, thereby both clarifying and confounding the NaN problem that plagues our world.

**Comment by hajimehoshi** [comment]
I'm not sure I understand this suggestion, but an interface with a `nil` pointer is comparable, while NaN (not a number) is not, right?

https://go.dev/play/p/mldzOxNjqpu

```go
package main

import (
	"fmt"
	"math"
)

func main() {
	var a any = (*int)(nil)
	var b any = (*int)(nil)
	fmt.Println(a == b)

	c := math.NaN()
	d := math.NaN()
	fmt.Println(c == d)
}
```
