### ISSUE TITLE
x/pkgsite: package removal request for gitlab.com/roger-codina/go-query-builder

### ISSUE THREAD

**Issue by roger-codina** [golang/go#56369]
### What is the path of the package that you would like to have removed?
gitlab.com/roger-codina/go-query-builder
 
 
 
### Are you the owner of this package?
YES

 
### What is the reason that you could not retract this package instead?
It was a test, and the repository was deleted after that. We were testing about GOPRIVATE modules usage.

**Comment by findleyr** [comment]
Sorry for the delay. This is done.
