### ISSUE TITLE
x/pkgsite: package removal request for [gopkg.inshopline.com/commons/snowflake]

### ISSUE THREAD

**Issue by JasonMing** [golang/go#56366]
### What is the path of the package that you would like to have removed?
`gopkg.inshopline.com/commons/snowflake`

 
 
 
### Are you the owner of this package?

YES!

 
### What is the reason that you could not retract this package instead?

This is a private repo, accidentally leak when testing, please remove it from public index and cache.

**Comment by jamalc** [comment]
Done.
