### ISSUE TITLE
x/pkgsite: package removal request for github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/elasticsans/armelasticsans

### ISSUE THREAD

**Issue by tadelesh** [golang/go#56367]
### What is the path of the package that you would like to have removed?

github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/elasticsans/armelasticsans

 
 
 
### Are you the owner of this package?

Yes

 
### What is the reason that you could not retract this package instead?

Module has been retracted and replaced with github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/elasticsan/armelasticsan.

**Comment by jamalc** [comment]
Done.
