### ISSUE TITLE
x/tools/cmd/godoc: Possible improvements

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#5637]
<pre>Some improvement we could make to godoc.  Split these up into separate issues if it's
easier.

* Add the ability for godoc-specific comments.  This would not be markup as such, but
would be ways to organize the presented docs.  For example, a way to indicate which
names in a package are important and which are not.  The important names would appear
first.  The unimportant ones would be hidden by default.

* When the text has a capitalized word that is the same as an exported name in the
package, link the text to the docs for that name.

* Provide some way to automatically know which types implement which interfaces, ideally
across packages.</pre>

**Comment by bradfitz** [comment]
Item 2 seems to be happening in #18342

**Comment by mvdan** [comment]
Item 3 (a restricted version of it) is at https://github.com/golang/go/issues/20131, accepted as a proposal.
