### ISSUE TITLE
proposal: net/rpc: add DialWithCodec, DialHTTPWithCodec, DialHTTPPathWithCodec 

### ISSUE THREAD

**Issue by xbt573** [golang/go#56376]
Now, i can't create RPC client with custom codec and path (if i didn't miss anything)
Adding this functions will make this possible
Possible implementations:

DialWithCodec:
```go
// DialWithCodec connects to an RPC server at the specified network address, using given codec.
func DialWithCodec(codec ClientCodec) *Client {
    return NewClientWithCodec(codec)
}
```

**Comment by robpike** [comment]
As it says in the package comment, "The net/rpc package is frozen and is not accepting new features."
