### ISSUE TITLE
go/format: unable to write '' in a comment as it's unconditionally transformed to a ” "smart quote"

### ISSUE THREAD

**Issue by arp242** [golang/go#56380]
Since Go 1.19 (commit ae3d890202) `''` is unconditionally transformed to `“` or `”`. This means my comment:

    // lexMultilineRawString consumes a raw string. Nothing can be escaped in such
    // a string. It assumes that the beginning ''' has already been consumed and
    // ignored.

Now becomes:

    // lexMultilineRawString consumes a raw string. Nothing can be escaped in such
    // a string. It assumes that the beginning ”' has already been consumed and
    // ignored.

There are some other cases, especially when parsing things, where one might reasonably want to type `''` inside a regular (non-codeblock) comment.

Looking at go/doc/comment/parse.go, there is no way to escape this behaviour, and I don't really see an obvious non-ugly way to write that comment.

**Comment by ALTree** [comment]
I believe this is already tracked at  #54312. I suggest we keep all the discussion about the '' replacement issue in that thread. Closing here.

**Comment by arp242** [comment]
Cheers, I tried searching for an existing issue but I couldn't find it.
