### ISSUE TITLE
net: nss myhostname incorrectly handles gateway and outbound hostnames

### ISSUE THREAD

**Issue by mateusz834** [golang/go#56387]
[nss-myhostname(8)](https://manpages.debian.org/testing/libnss-myhostname/nss-myhostname.8.en.html):
>
>•The hostname "_gateway" is resolved to all current default routing gateway addresses, ordered by their metric. (...)
>•The hostname "_outbound" is resolved to the local IPv4 and IPv6 addresses that are most likely used for communication with other hosts. (...)

But it only checks for the "gateway" hostname which is incorrect, it should check for "_gateway" (as defined in man page), and _outbound.

https://github.com/golang/go/blob/7e72d384d66f48a78289edc6a7d1dc6ab878f990/src/net/conf.go#L249-L251

https://github.com/golang/go/blob/7e72d384d66f48a78289edc6a7d1dc6ab878f990/src/net/conf.go#L348-L352
```go
package main

import (
	"fmt"
	"net"
)

func main() {
	fmt.Println(net.LookupHost("localhost"))
	fmt.Println(net.LookupHost("_gateway"))
	fmt.Println(net.LookupHost("_outbound"))
}
```
```
[mateusz@arch testtt]$  GODEBUG=netdns=2 go run main.go
go package net: confVal.netCgo = false  netGo = false
go package net: dynamic selection of DNS resolver
go package net: hostLookupOrder(localhost) = cgo
[::1 127.0.0.1] <nil>
go package net: hostLookupOrder(_gateway) = files,dns
[] lookup _gateway on 81.26.0.10:53: no such host
go package net: hostLookupOrder(_outbound) = files,dns
[] lookup _outbound on 81.26.0.10:53: no such host
```

**Comment by mateusz834** [comment]
With this linked CL it should work fine.

```
[mateusz@arch testtt]$ GODEBUG=netdns=2 go run main.go
go package net: confVal.netCgo = false  netGo = false
go package net: dynamic selection of DNS resolver
go package net: hostLookupOrder(localhost) = cgo
[::1 127.0.0.1] <nil>
go package net: hostLookupOrder(_gateway) = cgo
[10.100.0.1] <nil>
go package net: hostLookupOrder(_outbound) = cgo
[10.100.5.228] <nil>
```

**Comment by seankhliao** [comment]
cc @ianlancetaylor @neild
