### ISSUE TITLE
runtime.semrelease:  fatal error: fault [signal 0xc0000005 code=0x0 addr=0x60140eea3f0 pc=0x14004bde2]

### ISSUE THREAD

**Issue by kmlebedev** [golang/go#56393]
### What version of Go are you using (`go version`)?

<pre>
$ root@orangepi-rk3399:/usr/local/src/txmlconnector# go version
go version go1.19.2 linux/arm64

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

on arm64

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm64"
GOVCS=""
GOVERSION="go1.19.2"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/usr/local/src/txmlconnector/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build552478422=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

<pre>
git clone https://github.com/kmlebedev/txmlconnector.git
cd txmlconnector
CGO_ENABLED=1 CC="x86_64-w64-mingw32-gcc" CXX="x86_64-w64-mingw32-g++" GOOS=windows GOARCH=amd64 go build -ldflags "-extldflags -static -s -w" -o bin/server.exe main.go
box64 /usr/local/wine/bin/wine64 bin/server.exe
</pre>

### What did you expect to see?

on intel MacOSX
<pre>
make server
CGO_ENABLED=1 CC="x86_64-w64-mingw32-gcc" CXX="x86_64-w64-mingw32-g++" GOOS=windows GOARCH=amd64 go build -ldflags "-extldflags -static -s -w" -o bin/server.exe main.go
mkdir -p logs
wine64 bin/server.exe
002c:err:winediag:getaddrinfo Failed to resolve your host name IP
0024:fixme:process:SetProcessPriorityBoost (FFFFFFFFFFFFFFFF,1): stub
0024:fixme:powrprof:PowerRegisterSuspendResumeNotification (0x00000002,000000000021FBC0,000000000021FBA8) stub!
time="2022-10-24T14:40:44+05:00" level=info msg="Initialize module: txmlconnector64-6.19.2.21.21.dll"
InitCrashHandler: Z:\Users\kmlebedev\go\src\txmlconnector\bin\server-221024-144047.mdmp
time="2022-10-24T14:40:47+05:00" level=info msg="Server running ..."
0110:fixme:ver:GetCurrentPackageId (00000000274EFE10 0000000000000000): stub
time="2022-10-24T14:40:47+05:00" level=info msg="Press CRTL+C to stop the server..."
^C^Ctime="2022-10-24T14:44:24+05:00" level=info msg="\r Ctrl+C pressed in Terminal"
</pre>

### What did you see instead?

<pre>
box64 /usr/local/wine/bin/wine64 bin/server.exe
0024:fixme:process:SetProcessPriorityBoost (FFFFFFFFFFFFFFFF,1): stub
unexpected fault address 0x60140eea3f0
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0x60140eea3f0 pc=0x14004bde2]

goroutine 1 [running, locked to thread]:
runtime.throw({0x1405360fe?, 0x0?})
        /usr/local/go/src/runtime/panic.go:1047 +0x65 fp=0xc0000c7240 sp=0xc0000c7210 pc=0x140039ce5
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_windows.go:261 +0x125 fp=0xc0000c7288 sp=0xc0000c7240 pc=0x14004d185
runtime.semrelease1(0x10c?, 0xc?, 0xc00008a6c0?)
        /usr/local/go/src/runtime/sema.go:172 +0x62 fp=0xc0000c72d8 sp=0xc0000c7288 pc=0x14004bde2
runtime.semrelease(...)
        /usr/local/go/src/runtime/sema.go:162
internal/poll.runtime_Semrelease(0x0?)
        /usr/local/go/src/runtime/sema.go:82 +0x1d fp=0xc0000c7300 sp=0xc0000c72d8 pc=0x140062d5d
internal/poll.(*FD).destroy(0xc0000cc780)
        /usr/local/go/src/internal/poll/fd_windows.go:380 +0xc5 fp=0xc0000c7328 sp=0xc0000c7300 pc=0x1400d3525
internal/poll.(*FD).decref(0xc0000c72d0?)
        /usr/local/go/src/internal/poll/fd_mutex.go:213 +0x53 fp=0xc0000c7348 sp=0xc0000c7328 pc=0x1400d1133
internal/poll.(*FD).Close(0xc0000cc780)
        /usr/local/go/src/internal/poll/fd_windows.go:395 +0x69 fp=0xc0000c7378 sp=0xc0000c7348 pc=0x1400d35e9
os.(*file).close(0xc0000cc780)
        /usr/local/go/src/os/file_windows.go:197 +0x56 fp=0xc0000c73c8 sp=0xc0000c7378 pc=0x1400e03f6
os.(*File).Close(0x1?)
        /usr/local/go/src/os/file_posix.go:25 +0x25 fp=0xc0000c73e0 sp=0xc0000c73c8 pc=0x1400defc5
google.golang.org/protobuf/internal/detrand.binaryHash.func1()
        /root/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/detrand/rand.go:50 +0x26 fp=0xc0000c73f8 sp=0xc0000c73e0 pc=0x140117626
google.golang.org/protobuf/internal/detrand.binaryHash()
        /root/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/detrand/rand.go:68 +0x25c fp=0xc0000c74c0 sp=0xc0000c73f8 pc=0x1401175bc
google.golang.org/protobuf/internal/detrand.init()
        /root/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/detrand/rand.go:38 +0x17 fp=0xc0000c74d0 sp=0xc0000c74c0 pc=0x140117677
runtime.doInit(0x14040bc80)
        /usr/local/go/src/runtime/proc.go:6321 +0x12d fp=0xc0000c7600 sp=0xc0000c74d0 pc=0x140048f8d
runtime.doInit(0x14040bd00)
        /usr/local/go/src/runtime/proc.go:6298 +0x71 fp=0xc0000c7730 sp=0xc0000c7600 pc=0x140048ed1
runtime.doInit(0x14040bc40)
        /usr/local/go/src/runtime/proc.go:6298 +0x71 fp=0xc0000c7860 sp=0xc0000c7730 pc=0x140048ed1
runtime.doInit(0x14040bcc0)
        /usr/local/go/src/runtime/proc.go:6298 +0x71 fp=0xc0000c7990 sp=0xc0000c7860 pc=0x140048ed1
runtime.doInit(0x14040ff80)
        /usr/local/go/src/runtime/proc.go:6298 +0x71 fp=0xc0000c7ac0 sp=0xc0000c7990 pc=0x140048ed1
runtime.doInit(0x140411bc0)
        /usr/local/go/src/runtime/proc.go:6298 +0x71 fp=0xc0000c7bf0 sp=0xc0000c7ac0 pc=0x140048ed1
runtime.doInit(0x14040f580)
        /usr/local/go/src/runtime/proc.go:6298 +0x71 fp=0xc0000c7d20 sp=0xc0000c7bf0 pc=0x140048ed1
runtime.doInit(0x140410420)
        /usr/local/go/src/runtime/proc.go:6298 +0x71 fp=0xc0000c7e50 sp=0xc0000c7d20 pc=0x140048ed1
runtime.doInit(0x140409b40)
        /usr/local/go/src/runtime/proc.go:6298 +0x71 fp=0xc0000c7f80 sp=0xc0000c7e50 pc=0x140048ed1
runtime.main()
        /usr/local/go/src/runtime/proc.go:233 +0x1bf fp=0xc0000c7fe0 sp=0xc0000c7f80 pc=0x14003c3df
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000c7fe8 sp=0xc0000c7fe0 pc=0x140067521

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00003ffb0 sp=0xc00003ff90 pc=0x14003c7b6
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:369
runtime.forcegchelper()
        /usr/local/go/src/runtime/proc.go:302 +0xb1 fp=0xc00003ffe0 sp=0xc00003ffb0 pc=0x14003c651
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00003ffe8 sp=0xc00003ffe0 pc=0x140067521
created by runtime.init.6
        /usr/local/go/src/runtime/proc.go:290 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000041f90 sp=0xc000041f70 pc=0x14003c7b6
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:369
runtime.bgsweep(0x0?)
        /usr/local/go/src/runtime/mgcsweep.go:278 +0x8e fp=0xc000041fc8 sp=0xc000041f90 pc=0x1400269ee
runtime.gcenable.func1()
        /usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc000041fe0 sp=0xc000041fc8 pc=0x14001b586
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000041fe8 sp=0xc000041fe0 pc=0x140067521
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000028070?, 0x1405f9f50?, 0x1?, 0x0?, 0x140025056?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000051f70 sp=0xc000051f50 pc=0x14003c7b6
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:369
runtime.(*scavengerState).park(0x140895bc0)
        /usr/local/go/src/runtime/mgcscavenge.go:389 +0x53 fp=0xc000051fa0 sp=0xc000051f70 pc=0x140024a73
runtime.bgscavenge(0x0?)
        /usr/local/go/src/runtime/mgcscavenge.go:617 +0x45 fp=0xc000051fc8 sp=0xc000051fa0 pc=0x140025065
runtime.gcenable.func2()
        /usr/local/go/src/runtime/mgc.go:179 +0x26 fp=0xc000051fe0 sp=0xc000051fc8 pc=0x14001b526
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000051fe8 sp=0xc000051fe0 pc=0x140067521
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:179 +0xaa

goroutine 18 [finalizer wait]:
runtime.gopark(0x1408962e0?, 0xc0000841a0?, 0x0?, 0x0?, 0xc000043f70?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000043e28 sp=0xc000043e08 pc=0x14003c7b6
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:369
runtime.runfinq()
        /usr/local/go/src/runtime/mfinal.go:180 +0x10f fp=0xc000043fe0 sp=0xc000043e28 pc=0x14001a68f
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000043fe8 sp=0xc000043fe0 pc=0x140067521
created by runtime.createfing
        /usr/local/go/src/runtime/mfinal.go:157 +0x45
</pre>

https://github.com/kmlebedev/txmlconnector/issues/9

**Comment by kmlebedev** [comment]
Hello code works
```
package main
import "fmt"
func main() {
        fmt.Println("Hello, world")
}
```
do
<pre>
CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build main.go
box64 /usr/local/wine/bin/wine64 /tmp/main.exe
0024:fixme:process:SetProcessPriorityBoost (FFFFFFFFFFFFFFFF,1): stub
Hello, world

**Comment by antong** [comment]
So this is not really running the compiled binary on linux/arm64, but actually windows/amd64 on top of Windows emulation (wine) on top of amd64 emulation (box64) ?

**Comment by kmlebedev** [comment]
> So this is not really running the compiled binary on linux/arm64, but actually windows/amd64 on top of Windows emulation (wine) on top of amd64 emulation (box64) ?

yes

**Comment by bcmills** [comment]
Does the problem reproduce when running the Windows binary on an actual AMD64 Windows installation? That would help to narrow down whether the bug is in Go or in one of the emulation layers.

**Comment by kmlebedev** [comment]
> Does the problem reproduce when running the Windows binary on an actual AMD64 Windows installation? That would help to narrow down whether the bug is in Go or in one of the emulation layers.

@bcmills I gave an example above, on real windows AMD64 and Windows emulation (wine) no errors occur.
The problem is in box64 + wine emulation, but somewhere inside go runtime.

**Comment by bcmills** [comment]
The Go project does not provide specific support for running under `box64`. If you believe that this is a bug in the Go project, you will need to either identify the specific code change needed to fix it or reproduce the bug on a supported platform.
