### ISSUE TITLE
proxy.golang.org:  letme

### ISSUE THREAD

**Issue by lockedinspace** [golang/go#56399]
Hi all, thanks for your amazing contribution to open source!

I am having a little issue where it seems like for this repository (https://github.com/lockedinspace/letme) tags are not being correctly updated on their respective mirror https://pkg.go.dev/github.com/lockedinspace/letme?tab=versions I can see the tag v0 but on the repo mentioned above its the v0.1.

It is also causing some errors while installing:
```
$ go install [github.com/lockedinspace/letme@latest](http://github.com/lockedinspace/letme@latest)

go: downloading [github.com/lockedinspace/letme](http://github.com/lockedinspace/letme) v0.1.1-rc2
go: [github.com/lockedinspace/letme@latest](http://github.com/lockedinspace/letme@latest): module [github.com/lockedinspace/letme@latest](http://github.com/lockedinspace/letme@latest) found (v0.1.1-rc2), but does not contain package [github.com/lockedinspace/letme](http://github.com/lockedinspace/letme)
```
If you clone the repo and execute ``go build`` this  error does not appear.

Seems like it is not successfully updated, could you please verify from your end if everything's correct?

**Comment by D1CED** [comment]
`v0.1` is not a valid version. A version must contain at least three segments, so `v0.1.0` would be valid. For more see this https://go.dev/doc/modules/version-numbers.

**Comment by seankhliao** [comment]
see above.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by lockedinspace** [comment]
Hi @seankhliao , sorry to bother you but please if this is not the place, update your docs accordingly:
https://proxy.golang.org/ 
FAQ -> _I committed a new change (or released a new version) to a repository, why isn't it showing up when I run go get -u or go list -m --versions?_ 
**file an issue** link. Currently pointing at: https://github.com/golang/go/issues/new?title=proxy.golang.org%3A+
