### ISSUE TITLE
test: -args invalid

### ISSUE THREAD

**Issue by bladehan1** [golang/go#56407]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/blade/Library/Caches/go-build"
GOENV="/Users/blade/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/blade/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/blade/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.17.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.17.5/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xq/tbl6y4sx6bl2d2x0vqz0zmjm0000gn/T/go-build1318505985=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
go test pass parameters

flag.go 
```
package flag

import (
	"flag"
	"fmt"
	"os"
)

var flagvar int
var user int

//-flagename 2345
func CaseBase() {
	
	args := os.Args
	fmt.Printf("args%+v\n", args)
	value := 3
	flag.IntVar(&flagvar, "flagname", 1234, "help message for flagname")
	flag.IntVar(&user, "user", value, "help message for user")
	flag.Parse()
	fmt.Println("flagvar:", flagvar)
	fmt.Println("user:", user)
	fmt.Println(flag.Lookup("user"))
}

```
flag_test.go
```
package flag

import "testing"

func TestCaseBase(t *testing.T) {
	CaseBase()
}
```
<pre>
$ go test github.com/hzj/tool/stdLib/flag -test.v -args -flagname 111

...
</pre>

### What did you expect to see?

flagvar: 111
user: 3

### What did you see instead?

flag provided but not defined: -flagname
Usage of /var/folders/xq/tbl6y4sx6bl2d2x0vqz0zmjm0000gn/T/go-build793913372/b001/flag.test:
  -test.bench regexp

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
