### ISSUE TITLE
x/pkgsite: latest version gets confused by old conflicting subdirectory / submodule

### ISSUE THREAD

**Issue by guregu** [golang/go#56408]
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/trealla-prolog/go@v0.11.1/trealla

### What is your user agent?

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

### Screenshot

![2022-10-25](https://user-images.githubusercontent.com/131059/197714151-7a88eb27-aa56-4ed4-b8a6-80f97431428e.png)

### What did you do?

Accessed the "trealla" subpackage from this URL: https://pkg.go.dev/github.com/trealla-prolog/go#section-directories

### What did you expect to see?

No "latest version" warning (as of writing v0.11.1 is the latest version).

### What did you see instead?

Red "latest version" button linking to a very outdated version.

## Cause?

While trying to figure out the best way to publish a package in a subdirectory, I tried a bunch of configurations of "root go.mod module in a subdirectory", "go.mod in root and child directory", etc. 
Eventually I settled on a single go.mod in the parent directory.
pkg.go.dev remembers one of these old attempts as the newest version for [this subdirectory package](https://pkg.go.dev/github.com/trealla-prolog/go/trealla) which is confusing to users and means I can't link to it to point to the latest version (currently the latest version is [here](https://pkg.go.dev/github.com/trealla-prolog/go@v0.11.1/trealla)).
I tried to retract the old version but it's a git hash pseudoversion and I wasn't able to get it to 'forget' the old package.

Is there any way to get the site to prefer my newer parent package instead?

**Comment by seankhliao** [comment]
you could make a branch with:

trealla/go.mod:
```
module github.com/tralla-prolog/go/trealla

retract [v0.0.0-0, v0.0.1]
```

and tag it `v0.0.1`

see https://go.dev/ref/mod#go-mod-file-retract

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
