### ISSUE TITLE
x/vulndb: populate "summary" OSV field

### ISSUE THREAD

**Issue by tatianab** [golang/go#56443]
This would require adding a corresponding notion in YAML (or perhaps pulling the first sentence from the description for the "summary"). Also need to think about how (if) these would be translated to CVE fields

**Comment by hyangah** [comment]
Lack of "summary" makes the Go vulnerabilities coming from vuln.go.dev look less helpful in osv.dev and also, when using in IDEs or tools that seek for compact presentation. 

For example, this is the current osv.dev Go vulnerability screenshot. Compare the advisory coming from GHSA and x/vulndb.
![Screenshot 2023-03-09 at 12 21 48 PM](https://user-images.githubusercontent.com/4999471/224105926-3ac96443-4061-49fd-99ce-f696945affef.png)
