### ISSUE TITLE
cmd/trace: split traces include all stack traces, which can consume all space

### ISSUE THREAD

**Issue by prattmic** [golang/go#56444]
cmd/trace splits events into ~100MB chunks of JSON. When creating chunks, each chunk [includes the full stackFrames map](https://cs.opensource.google/go/go/+/master:src/cmd/trace/trace.go;l=346;drc=5d59fa143ae1d0d8fdcc677297ce58bbfc592111) for the entire trace, rather than limiting to just the stack frames relevant to the events in the chunk.

In the most extreme case, the stackFrames map is >100MB of JSON, leaving no space for events. In this case, cmd/trace will include only 1 event in each split, resulting in thousands of ~useless splits.

It should be possible to mitigate this by including only relevant stack frames.

**Comment by adonovan** [comment]
Many thanks for tracking this down so quickly.
