### ISSUE TITLE
internal/bytealg: strings test fails on ppc64le/p9 on certain random strings

### ISSUE THREAD

**Issue by archanaravindar** [golang/go#56457]
```
#!watchflakes
post <- pkg == "strings" && test == "TestIndexRandom"
```

### What version of Go are you using (`go version`)?

<pre>
master go1.20-50557edf10
</pre>

### Does this issue reproduce with the latest release?

Yes 

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="ppc64le"
GOBIN=""
GOCACHE="/home/archana/.cache/go-build"
GOENV="/home/archana/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="ppc64le"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/archana/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/archana/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/archana/Go_master/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/archana/Go_master/go/pkg/tool/linux_ppc64le"
GOVCS=""
GOVERSION="devel go1.20-50557edf10 Thu Oct 27 10:37:01 2022 +0000"
GCCGO="gccgo"
GOPPC64="power9"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/archana/Go_master/go/src/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3329760993=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

There is a random failure seen recently in the Go build dashboard under ppc64le/power9. The timing of this error seems to be related to the CL 443058 as it does not occur with setting GODEBUG=randautoseed=0.

--- FAIL: TestIndexRandom (0.01s)
    strings_test.go:268: Index(999f2xmimunbuyew5vrkla9cpwhmxan8o98ec,98ec) = -1; want 33
FAIL
FAIL	strings	1.575s

Upon running the strings test multiple times with random inputs, it appears that the test fails for some number of cases.  

### What did you expect to see?

The strings test should pass 

### What did you see instead?

The strings test fails for a subset of the random inputs tested 

@bcmills

**Comment by ianlancetaylor** [comment]
CC @golang/ppc64

**Comment by pmur** [comment]
I think gopherbot reopened this against failure @archanaravindar already observed and committed a fix for yesterday.

@archanaravindar does this fix need [backported](https://github.com/golang/go/wiki/MinorReleases) to go1.19?
