### ISSUE TITLE
x/mobile: bug: cannot use variable (untyped int constant) as int value in argument to fmt.Printf (overflows)

### ISSUE THREAD

**Issue by benma** [golang/go#56453]
Hi

Thanks for gomobile, we use it successfully since years for our Android app!

I recently had to workaround this compiler error, which seems to be a bug:

```
package foo

import "fmt"

func Foo() {
	const foo = 0xff000000
	fmt.Printf("%v", foo)
}
```

```
$ gomobile bind -target android .
foo.go:7:19: cannot use foo (untyped int constant 4278190080) as int value in argument to fmt.Printf (overflows)
```

Running the same code with `go run ...` prints the constant as expected.

I worked around it by typing the constant explicitly: 

`const foo uint32 = 0xff000000`.

Anyone knows why this is happening?

**Comment by changkun** [comment]
@benma Could you also report what is your current environment by answering the following questions?

```
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?



### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>
```

**Comment by robpike** [comment]
I believe this program will work on a 64-bit platform but fail to compile on a 32-bit platform, as 0xff000000 overflows the range of positive signed 32-bit integers.

**Comment by benma** [comment]
Actually that makes a lot of sense, thanks! Sorry for the noise.
