### ISSUE TITLE
crypto/tls extreamly slow!

### ISSUE THREAD

**Issue by clarkk** [golang/go#56468]
```
# go version
go version go1.19.2 linux/amd64
```

I have a simple HTTP server running TLS. When it's exposed directly to the internet it can only handle ~17 req/sec.

If I switch to HTTP and put it behind nginx and let nginx handle TLS, ciphers etc it handles ~100 req/sec

```
ab -n 100 -c 1
```

Why have you removed the option to select ciphers when using TLS1.3??

When I test the SSL certs, ciphers etc on the nginx everything is 100% without any vulnerabilities

https://www.ssllabs.com/ssltest/analyze.html

![tls1](https://user-images.githubusercontent.com/1913916/198547224-ae0cac04-007e-46ef-b867-81aad8b0f8f4.png)

![tls2](https://user-images.githubusercontent.com/1913916/198547673-8342f9b0-0c3f-4324-9a25-828376ece8d0.png)

![tls3](https://user-images.githubusercontent.com/1913916/198547858-037a6cc9-3d57-4e0c-9a35-c10b3cc4f076.png)

**Comment by mateusz834** [comment]
I probably happens because of slow RSA in golang, #20058, try using ECDSA, or switching to BoringSSL

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by clarkk** [comment]
@mateusz834 How is it possible to select a preferred list of ciphers in golang with TLS 1.3?

**Comment by clarkk** [comment]
The options are removed from TLS 1.3

**Comment by mateusz834** [comment]
It is not possible by design (all TLS 1.3 cipher suites are really secure).
