### ISSUE TITLE
testing: silly typo in documentation

### ISSUE THREAD

**Issue by seebs** [golang/go#56479]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.19.2
</pre>

### Does this issue reproduce with the latest release?

y

### What operating system and processor architecture are you using (`go env`)?

N/A

### What did you do?

Read the docs.

### What did you expect to see?

Fewer typos.

### What did you see instead?

In the FuzzJSONMarshaling example:
```
t.Error("Marshal: %v", err)
```
Either this shouldn't have the "%v", or it should be `t.Errorf`.

**Comment by ianlancetaylor** [comment]
Thanks, sending a CL.
