### ISSUE TITLE
fmt: Printf flag '0' is not ignored for strings

### ISSUE THREAD

**Issue by yejianfengblue** [golang/go#56486]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/k/.cache/go-build"
GOENV="/home/k/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/k/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/k/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build536070510=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

https://go.dev/play/p/thI6FNjWrY_G

```go
package main

import "fmt"

func main() {
    fmt.Printf("%05s", "abc")
    // print 00abc
}
```

### What did you expect to see?
abc

According to the [doc](https://pkg.go.dev/fmt#pkg-overview), the flag '0' is ignored for strings.
> '0' pad with leading zeros rather than spaces; for numbers, this moves the padding after the sign; ignored for strings, byte slices and byte arrays

### What did you see instead?
00abc

### Background
I originally asked this question in [Stackoverflow](https://stackoverflow.com/q/74246342/10009424). [Pak Uula](https://stackoverflow.com/a/74246921/10009424) helps check the source code and this issue seems to be a bug.
> [The source code](https://cs.opensource.google/go/go/+/refs/tags/go1.19.2:src/fmt/print.go;l=1037) resets the zero flag only for - (minus) flag. It is not modified neither for strings nor for any other type.
And the [function that outputs a string](https://cs.opensource.google/go/go/+/refs/tags/go1.19.2:src/fmt/format.go;l=108) doesn't reset the zero flag either.

**Comment by seankhliao** [comment]
seems to have been this way for a long time

cc @robpike

**Comment by robpike** [comment]
It's sometimes ignored. See https://go.dev/play/p/_-73vYP6W4p

It's a bug that it's not always ignored.

**Comment by robpike** [comment]
This is not complete yet. Another change to come: must also protect quoted strings and characters, all of which are lovely demonstrated in the golden test as badly broken. Good work, guy.

**Comment by dmitshur** [comment]
@robpike Note that the release-blocker label applies to the milestone an issue is in, and this issue is in Unplanned, so it had no effect. I've moved it to the Go1.23 milestone since that seems to be the intention.

**Comment by rsc** [comment]
CL 555776 broke a bunch of code. Documenting the long-time behavior instead seems like it makes more sense than causing breakage, so I sent CL 559196 (revert) and CL 559197 (document).
