### ISSUE TITLE
x/pkgsite:Missing type string on the first parameter of Split function.

### ISSUE THREAD

**Issue by Lucas-Melo0** [golang/go#56488]
### What is the URL of the page with the issue?
 https://pkg.go.dev/strings#Split
 
 

 
### Screenshot
 
![image](https://user-images.githubusercontent.com/106865843/198876376-75674b24-3369-4501-af8b-6de2dd192b37.png)
 
 
 
### What did you do?
 
Access the docs page.
 
 
 
### What did you expect to see?

The type of the s parameter in the split function. 
 
 
### What did you see instead?

No type for the s parameter.

**Comment by seankhliao** [comment]
That's how the language works.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
