### ISSUE TITLE
cmd/compile: performance regression compiling crypto/internal/edwards25519/field.feMulGeneric on PPC64

### ISSUE THREAD

**Issue by pmur** [golang/go#56497]
The change to support carry flag optimization on ARM64 (go.dev/cl/432275) caused a large regression in the crypto/ed25519 benchmarks. I missed this regression when reviewing the patch.

The optimization created by using the CarryChainTail priority fails when schedulable memory ops get intertwined with schedulable CarryChainTail ops like ADDZ on PPC64. This leads to many avoidable CA bit clobbers.

### What did you expect to see?

No difference in benchmark tests.

### What did you see instead?

```
name              old time/op  new time/op  delta
KeyGeneration-2   27.2µs ± 0%  29.6µs ± 0%   +9.05%  (p=1.000 n=1+1)
NewKeyFromSeed-2  23.9µs ± 0%  29.4µs ± 0%  +23.13%  (p=1.000 n=1+1)
Signing-2         33.7µs ± 0%  37.2µs ± 0%  +10.36%  (p=1.000 n=1+1)
Verification-2    68.3µs ± 0%  88.8µs ± 0%  +30.06%  (p=1.000 n=1+1)
```

**Comment by mknyszek** [comment]
In triage, context from @cherrymui, @pmur is already looking into it so assigning it to you.
