### ISSUE TITLE
cmd/compile: `Maximum call stack size exceeded` testing go/parser with Node.js v18.7.0

### ISSUE THREAD

**Issue by bcmills** [golang/go#56498]
### What version of Go are you using (`go version`)?

<pre>
$ gotip version
go version devel go1.20-e09bbaec69 Sat Oct 29 04:48:07 2022 +0000 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes: reproduces with go1.19.2.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ gotip env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/usr/local/google/home/bcmills/.cache/go-build"
GOENV="/usr/local/google/home/bcmills/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/tmp/tmp.BkSnRHYFHZ/.gopath/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/tmp/tmp.BkSnRHYFHZ/.gopath"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/google/home/bcmills/sdk/gotip"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/google/home/bcmills/sdk/gotip/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel go1.20-e09bbaec69 Sat Oct 29 04:48:07 2022 +0000"
GCCGO="/usr/local/google/home/bcmills/bin/gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="c++"
CGO_ENABLED="1"
GOMOD="/tmp/tmp.BkSnRHYFHZ/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2991106879=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

```
$ GOOS=js GOARCH=wasm go test go/parser
```

### What did you expect to see?

Tests passing.

### What did you see instead?

It appears that some function being executed by the test is compiled in a way that runs afoul of Node's default limits on stack depth.

```
$ GOOS=js GOARCH=wasm go test go/parser
wasm://wasm/01129cfe:1


RangeError: Maximum call stack size exceeded
    at wasm://wasm/01129cfe:wasm-function[2020]:0x1e73d9
    at wasm://wasm/01129cfe:wasm-function[2333]:0x23f11a
    at wasm://wasm/01129cfe:wasm-function[2336]:0x23fd71
    at wasm://wasm/01129cfe:wasm-function[2406]:0x254b40
    at wasm://wasm/01129cfe:wasm-function[2425]:0x25a280
    at wasm://wasm/01129cfe:wasm-function[2428]:0x25bdf9
    at wasm://wasm/01129cfe:wasm-function[2431]:0x25cb53
    at wasm://wasm/01129cfe:wasm-function[2434]:0x25d618
    at wasm://wasm/01129cfe:wasm-function[2436]:0x25d8ac
    at wasm://wasm/01129cfe:wasm-function[2360]:0x244ad8

Node.js v18.7.0
FAIL    go/parser       0.461s
FAIL
```

(attn @golang/js; CC @golang/compiler)

**Comment by rsc** [comment]
Reproducing on https://go-review.git.corp.google.com/c/go/+/446178 now too. Not sure what the workaround is.

**Comment by rsc** [comment]
Ran go test -v encoding/xml on a js-wasm builder and it is dying in one of the very deep unmarshal tests. Cutting the depth limit in half fixes the problem, which as far as I am concerned is good enough.

**Comment by johanbrandhorst** [comment]
This is now blocking https://github.com/golang/go/issues/57614 so I'll be looking at this too.
