### ISSUE TITLE
sync/atomic: document hint in the old APIs to point out that the new named types exist

### ISSUE THREAD

**Issue by uji** [golang/go#56495]
I posted the proposal of deprecated old APIs of sync/atomic.
ref: https://github.com/golang/go/issues/55302

Finally, this proposal was declined, but I think it's better to have a hint to the old APIs to point out and recommend that the new named types exist.

**Comment by randall77** [comment]
Not sure how to actually word this. Suggestions welcome.
```
// SwapInt32 atomically stores new into *addr and returns the previous *addr value.
// Consider using (*Int32).Swap instead.
func SwapInt32(addr *int32, new int32) (old int32)
```
Seems kinda lame and not really explanatory. But I don't want to clutter each function doc with lots of exposition either.
