### ISSUE TITLE
x/vuln/cmd/govulncheck: add some progress output

### ISSUE THREAD

**Issue by zpavlinovic** [golang/go#56501]
Make govulncheck a bit more transparent by printing some progress output. Initially, we can write something like

"Analyzing X specified packages and Y of their transitive dependencies..."

**Comment by hyangah** [comment]
Is it also possible to add some logging in x/vuln/vulncheck too?

**Comment by zpavlinovic** [comment]
We could do that. For instance, we can have a, say, Verbose flag in vulncheck.Config that logs major vulncheck steps.

**Comment by seankhliao** [comment]
same as #56101 ?

**Comment by zpavlinovic** [comment]
Yes, will close the former one to keep the current discussion flowing.
