### ISSUE TITLE
x/website: wrong checksum for go1.18.8.windows-amd64.msi

### ISSUE THREAD

**Issue by wkhere** [golang/go#56513]
### What is the URL of the page with the issue?
 
https://go.dev/dl/go1.18.8.windows-amd64.msi
 
### What is your user agent?
 
wget
 
### What did you do?
 
I downloaded [go1.18.8.windows-amd64.msi](https://go.dev/dl/go1.18.8.windows-amd64.msi)
then ran the check via
```
echo 'caeb81bf04d72b1a39c01df9f7702c59250798f6365ec15d67849782b3f0662e go1.18.8.windows-amd64.msi' | sha256sum -c
```
 
### What did you expect to see?
 
I expected sha256 checksum published on the website to match the file.
 
### What did you see instead?

```
go1.18.8.windows-amd64.msi: FAILED
````

**Comment by seankhliao** [comment]
command to download?
checksum of what you downloaded?
file size?

**Comment by atc0005** [comment]
I experienced this also. 

Tried from Google Chrome on Windows, Firefox on Ubuntu and Firefox Focus on Android. Same checksum on all of them.

The go.dev/dl site now lists the expected checksum as `6d38668862bf9772c0c1c1e0f26aa5dedea9825b33f763b81ccc4aa63df2cef9` which matches what I see on my end.

**Comment by seankhliao** [comment]
Closing as fixed

**Comment by heschi** [comment]
See https://groups.google.com/g/golang-nuts/c/_LWRvyo8-Ak. Error on our side.
