### ISSUE TITLE
A problem about debug in vscode, can't watch a expression `call str.String()` ,the str is a var :strings.Builder.

### ISSUE THREAD

**Issue by OrdinaryYZH** [golang/go#56511]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.2 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\yao\AppData\Local\go-build
set GOENV=C:\Users\yao\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=F:\Code\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=F:\Code\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.19.2
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\yao\AppData\Local\Temp\go-build34721351=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

I want to check a expression in my program, the expression is `call str.String()`, the str is a var :strings.Builder.

It tips me "Unable to evaluate expression: cannot use str.String as argument b in function strings.(*Builder).String: stack object passed to escaping pointer: b"

The detail pls look at the screenshot

I asked somebody, they said it is ok in Goland, so I don't konw is it a bug or not surpport in vscode

![image](https://user-images.githubusercontent.com/10287222/199228649-a4739381-0ffa-4f0b-898c-4b0c4f01a345.png)

### What did you expect to see?

show the result of expression

### What did you see instead?

a error: "Unable to evaluate expression: cannot use str.String as argument b in function strings.(*Builder).String: stack object passed to escaping pointer: b"

**Comment by seankhliao** [comment]
doesn't sound like a Go problem.

**Comment by OrdinaryYZH** [comment]
> doesn't sound like a Go problem.

But I posted the issue in vscode project, they said it is not vscode can solve,https://github.com/golang/vscode-go/issues/2522#issuecomment-1298488639

and I can search a relevant issue in go:https://github.com/golang/go/issues/21678#issuecomment-1077876231

so is it a windows system problem?

**Comment by OrdinaryYZH** [comment]
fine, i found an issue in go-delve project :-( https://github.com/go-delve/delve/issues/3174
