### ISSUE TITLE
x/vuln: missing --version

### ISSUE THREAD

**Issue by ldemailly** [golang/go#56514]
Please use the wonderful `debug.ReadBuildInfo()` to provide some version information so when installing

```
go install golang.org/x/vuln/cmd/govulncheck@latest
```

we can then run `govulncheck --version` and get some details

do consider also outputting the version of the remote db as that would help track differences of output for runs at different times

**Comment by zpavlinovic** [comment]
Thanks for reporting this. We are actively looking into how to best surface this information to the user.

**Comment by ldemailly** [comment]
yes that would be good, maybe also some stats about how many cve etc

**Comment by ldemailly** [comment]
- Versions is just in general when comparing different CI output or creating update build images to know what we're running
- DB version could be fancy json dump of  as much meta data as possible but just something like when it was last updated and number of entries - same need but run time instead of build/install time: what is it we're testing with

later when it does find or stops finding a vulnerability getting a url that could show the history of a given detected entry would be ideal (for investigating)

**Comment by ldemailly** [comment]
> For info available in debug.ReadBuildInfo(), go version -m <path_to_govulncheck> and there is https://github.com/golang/go/issues/53867

I missed that there was already an issue open but yes +1 to adding a proper version output (and tagging of the releases) in the binary itself

> DB version is interesting 

thx!

**Comment by zpavlinovic** [comment]
Default govulncheck output now contains govulncheck version info (in its current format) and vuln db info. We'll use #53867 for tracking potential addition of `--version` flag.

**Comment by ldemailly** [comment]
thx, though the output isn't exactly helpful in absence of tags:

```
$ go install golang.org/x/vuln/cmd/govulncheck@latest
go: downloading golang.org/x/vuln v0.0.0-20230130175424-dd534eeddf33
go: downloading golang.org/x/tools v0.5.1-0.20230117180257-8aba49bb5ea2
go: downloading golang.org/x/mod v0.7.0
$ govulncheck ./...
Using go1.19.5 and govulncheck@v0.0.0 with
vulnerability data from https://vuln.go.dev (last modified 30 Jan 23 19:23 UTC).
```

**Comment by zpavlinovic** [comment]
We are working on adding tags. When that happens, we will integrate it into the message.
