### ISSUE TITLE
x/pkgsite: duplicate drop down button


### ISSUE THREAD

**Issue by sslime336** [golang/go#56521]
### What is the URL of the page with the issue?

It is https://pkg.go.dev/std, but actually all of the pages like the former (from pkg.go.dev/xxx) represent the same.

### What is your user agent?

Mozilla/5.0 (Android 10; Mobile; rv:106.0) Gecko/106.0 Firefox/106.0

btw, my cellphone's screen resolution is	360 X 800

### Screenshot

![Screenshot_20221102_135454.jpg](https://user-images.githubusercontent.com/97684920/199409401-a1e80a7f-0461-4aa7-9d0c-f9ab1d74c05a.jpg)

### What did you do?

I just visit the website using firefox browser on my phone

![Screenshot_20221102_135740_com.huawei.android.launcher_edit_796253096295167.jpg](https://user-images.githubusercontent.com/97684920/199409858-796d17f9-5ee4-45c3-838d-de7e076bfe49.jpg)

### What did you expect to see?

Like 

![Screenshot_20221102_140010_com.huawei.browser.jpg](https://user-images.githubusercontent.com/97684920/199410196-ad14d542-847f-4086-b646-7af4bed8b418.jpg)

without duplicate drop down btns.

### What did you see instead?

already showed above

**Comment by ZekeLu** [comment]
I can not reproduce the issue. This is my browser:

```
Mozilla/5.0 (Android 12; Mobile; rv:106.0) Gecko/106.0 Firefox/106.0
```

**Comment by sslime336** [comment]
@ZekeLu result's below

![Screenshot_20221102_194346_org.mozilla.firefox.jpg](https://user-images.githubusercontent.com/97684920/199483608-bfcb4a58-8967-46ce-a7e9-82ede3b165de.jpg)

the same.

But I noticed your Android is 12, 2 version above mine(Android 10), so I guess is there anything relatived to this?

Just guess, I have no idea about that.

**Comment by findleyr** [comment]
CC @jamalc 

I also cannot reproduce, either on my mobile device or in an emulator with the same resoluition.

**Comment by sslime336** [comment]
Well.. My browser is to blame... I've just re-install the firefox and nothing went wrong 🙂 

![图片](https://user-images.githubusercontent.com/97684920/199763024-4c245e83-4966-414b-ab59-06dc0485b1d1.png)

Thx 4 ur quickly reply :)

**Comment by sslime336** [comment]
It is weird... This had relapsed after I re-installed my browser after several days... well, never mind. It seems it's all about my bowser 😳
