### ISSUE TITLE
cmd/go: TestScripts/svn fails if TZ database not installed

### ISSUE THREAD

**Issue by qmuntal** [golang/go#56527]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.20-3ba3b4893f Wed Nov 2 14:43:52 2022 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Only in tip

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/src/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/src/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel go1.20-3ba3b4893f Wed Nov 2 14:43:52 2022 +0000"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/usr/local/src/go/src/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3269867307=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

`go test -run TestScripts/svn/hello -count 1 ./cmd/go/internal/vcweb/vcstest`

### What did you expect to see?

`ok      cmd/go/internal/vcweb/vcstest   0.155s`

### What did you see instead?

```cmd
  vcstest_test.go:136: 2022/11/02 07:32:23 hello.txt:
        > handle svn
        > env TZ='America/New_York'
        > mkdir db/transactions
        > mkdir db/txn-protorevs
        > chmod 0755 hooks/pre-revprop-change
        > env ROOT=$PWD
        > cd .checkout
        > svn checkout file://$ROOT .
        [stdout]
        Checked out revision 0.
        > svn add hello.go
        [stdout]
        A         hello.go
        > svn commit --file MSG
        [stdout]
        Adding         hello.go
        Transmitting file data .done
        Committing transaction...
        Committed revision 1.
        > svn propset svn:author 'rsc' --revprop -r1
        [stdout]
        property 'svn:author' set on repository revision 1
        > svn propset svn:date '2017-09-22T01:12:45.861368Z' --revprop -r1
        [stdout]
        property 'svn:date' set on repository revision 1
        > svn update
        [stdout]
        Updating '.':
        At revision 1.
        > svn log
        [stdout]
        ------------------------------------------------------------------------
        r1 | rsc | 2017-09-22 01:12:45 +0000 (Fri, 22 Sep 2017) | 3 lines
        
        hello world
        
        
        ------------------------------------------------------------------------
        > cmp stdout .svn-log
        diff stdout .svn-log
        --- stdout
        +++ .svn-log
        @@ -1,5 +1,5 @@
         ------------------------------------------------------------------------
        -r1 | rsc | 2017-09-22 01:12:45 +0000 (Fri, 22 Sep 2017) | 3 lines
        +r1 | rsc | 2017-09-21 21:12:45 -0400 (Thu, 21 Sep 2017) | 3 lines
         
         hello world
```

### Additional info

- Same failure happens in `test1-svn-git.txt` and `test2-svn-git.txt`.
- These tests were added in [CL 427914](https://go-review.googlesource.com/c/go/+/427914), but they have been expanded in as part of #27494.
- I'm running these tests on a Linux distro with `svn` but without `tzdata`.

**Comment by qmuntal** [comment]
The `TestScripts/svn` tests are not hermetic, they set `TZ='America/New_York'` at the beginning and expect `svn` to honor that time zone when formatting date strings. Unfortunately, `svn` can only format dates using UTC if the TZ database is not installed.

These are the offending lines:

```cmd
        > cmp stdout .svn-log
        diff stdout .svn-log
        --- stdout
        +++ .svn-log
        @@ -1,5 +1,5 @@
         ------------------------------------------------------------------------
        -r1 | rsc | 2017-09-22 01:12:45 +0000 (Fri, 22 Sep 2017) | 3 lines
        +r1 | rsc | 2017-09-21 21:12:45 -0400 (Thu, 21 Sep 2017) | 3 lines
```

The first date timezone is UTC and has been formatted by `svn`.
The second date timezone is UTC-4 and is hardcoded in the test case ([here](https://github.com/golang/go/blob/3ba3b4893f3630b2bd78ec6f4f366d60e16bd636/src/cmd/go/testdata/vcstest/svn/hello.txt#L33)).

@bcmills

**Comment by qmuntal** [comment]
I believe that we can fix this issue by changing `env TZ='America/New_York'` to `env TZ=''` and updating the hardcoded date to be formatted as UTC. This way we wouldn't need the TZ database, and the test coverage would remain the same (IMO).

**Comment by bcmills** [comment]
That seems like a fine solution as long as the tests that use that repo don't depend on that timezone information.
