### ISSUE TITLE
cmd/compile: Dgeev/Circulant100-8 sec/op 1.1% regression, 1.1%point change between 3d92205 and da6042e

### ISSUE THREAD

**Issue by mknyszek** [golang/go#56532]
Regression range: https://go.googlesource.com/go/+log/3d92205ef5ed42147376d929e0f59c765974e345..da6042e82eb7fe5ba40a5c17959a31e19a44c3e8

Next step is to bisect.

**Comment by randall77** [comment]
I take that back about the addressingmodes issue, we don't generate the `X` versions in the regular rules any more, but we *do* generate the `Xload` versions, which is what addressingmodes cares about.

**Comment by randall77** [comment]
Closing, as I don't think there's anything actionable here.
