### ISSUE TITLE
text/template: new keywords (e.g. break, continue) breaks older working programs

### ISSUE THREAD

**Issue by bep** [golang/go#56538]
E.g. 

```go
package main

import (
	"os"
	"text/template"
)

func main() {

	t := `{{ break 32 }}`

	echo := func(in any) any {
		return in
	}

	funcs := template.FuncMap{
		"break": echo,
	}

	tmpl, err := template.New("test").Funcs(funcs).Parse(t)
	if err != nil {
		panic(err)
	}

	err = tmpl.Execute(os.Stdout, nil)
	if err != nil {
		panic(err)
	}
}
```

Note that the above program is a little constructed; I, personally, am not concerned about break/continue. But I notice that the upcoming new `return` keyword (#53015) uses the same approach. And an app I'm maintaining (Hugo) does have a `return` template func.

## Go 1.18:

```bash
go1.18 run main.go                                                              
32
````

## Go 1.19.3:

```
go version && go run main.go                                                       
go version go1.19.3 darwin/arm64
panic: template: test:1: unexpected "32" in {{break}}
goroutine 1 [running]:
main.main()
	/Users/bep/dev/go/bep/temp/main.go:24 +0x258
exit status 2
```

**Comment by seankhliao** [comment]
cc @robpike

**Comment by bcmills** [comment]
FWIW, the change could be made non-breaking by only giving the new behavior to new keywords if they do not have a corresponding entry in the `FuncMap`.

**Comment by bep** [comment]
>FWIW, the change could be made non-breaking by only giving the new behavior to new keywords if they do not have a corresponding entry in the FuncMap.

Yes, and that was also the original implementation (note that `break` and `continue` was introduced in Go 1.18, this is a Go 1.19 regression).

**Comment by bcmills** [comment]
> this is a Go 1.19 regression

Any idea when specifically it regressed?

https://go.dev/cl/410414 looks like a likely culprit to me (attn @eliben; CC @mvdan)

**Comment by eliben** [comment]
Just a note that I can reproduce this with tip as well (`go version devel go1.20-2af48cbb7d`).

@robpike significantly refactored the template lexer for 1.20 (https://go-review.googlesource.com/c/go/+/421883) but this doesn't affect the issue (it works in 1.18 but not 1.19 or 1.20)

**Comment by eliben** [comment]
Indeed, https://go-review.googlesource.com/c/go/+/410414 is the culprit as @bcmills suspected.

I'll work on a fix.
