### ISSUE TITLE
modules: go mod vendor does not vendor command packages expectedly

### ISSUE THREAD

**Issue by wizardishungry** [golang/go#56531]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.1 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
[Yes](https://go.dev/play/p/weGT-2NVgzQ?v=gotip)

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/jon/Library/Caches/go-build"
GOENV="/Users/jon/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/jon/.asdf/installs/golang/1.19.1/packages/pkg/mod"
GONOPROXY="bitbucket.org/redacted"
GONOSUMDB="bitbucket.org/redacted"
GOOS="darwin"
GOPATH="/Users/jon/.asdf/installs/golang/1.19.1/packages"
GOPRIVATE="bitbucket.org/redacted"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/jon/.asdf/installs/golang/1.19.1/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/jon/.asdf/installs/golang/1.19.1/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/jon/src/project/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/lj/jt8w0fb11rg9sncmt5t77z4c0000gn/T/go-build493077638=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
I'm trying to import `github.com/actgardner/gogen-avro/v10` to vendor the command at `github.com/actgardner/gogen-avro/v10/cmd/...`.

[If I try a tools.go style import of the v10 package](https://go.dev/play/p/weGT-2NVgzQ), I get errors when running `go mod vendor` (and in the playground).  Note there are no Go files in the top level directory.

[If I import a subpackage of the module, I don't get errors.](https://go.dev/play/p/-8IKoTdF4Zt) 
But, `vendor/github.com/actgardner/gogen-avro/v10` does not contain a `cmd` directory. This leaves me unable to `go run` commands from vendored modules.

### What did you expect to see?
I should be able to import the root of a go module and `go run` stuff under it, regardless if I have run `go mod vendor` or not. (I'm attempting to run code generation inside a Docker container.)

As a workaround, you may import a main package directly in tools.go, but it took a lot of trial an error to figure this out:
```go
import(
    _ "github.com/actgardner/gogen-avro/v10/cmd/gogen-avro"
)
```

### What did you see instead?

```
bitbucket.org/redacted/project imports
	github.com/actgardner/gogen-avro/v10: no required module provides package github.com/actgardner/gogen-avro/v10; to add it:
	go get github.com/actgardner/gogen-avro/v10
```
or `vendor/github.com/actgardner/gogen-avro/v10/cmd` does not exist.

**Comment by seankhliao** [comment]
Working as intended, vendor will only contain inputs necessary for a build

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
