### ISSUE TITLE
os/exec: Plan 9 build has been broken by a Windows security fix (also breaks 1.19.3 and 1.18.8)

### ISSUE THREAD

**Issue by millerresearch** [golang/go#56544]
[CL 446915](https://go.dev/cl/446915) fixes a security vulnerability on Windows (#56284), by rejecting environment variables containing NUL in `os/exec.Cmd`. In Plan 9, NULs in environment variables are not only permitted but required: the `path` variable uses NUL as the `os.PathListSeparator` character. Since the environment almost always contains `path`, this effectively breaks `os/exec`, on which `go build` depends.

The change has already been back-ported to 1.19.3 and 1.18.8, so those releases also won't build for Plan 9.

Plan 9 does not exhibit the vulnerability to NULs because it implements environment variables in a completely different way.

Therefore we could safely correct this issue by making the rejection of NUL conditional on `runtime.GOOS != "plan9"` or on `os.PathListSeparator != '\000'`.

**Comment by mdempsky** [comment]
@gopherbot Backport to 1.18 and 1.19. The Windows security fix inadvertently broke Plan 9.

**Comment by mdempsky** [comment]
@gopherbot Please backport to 1.18 and 1.19. The Windows security fix inadvertently broke Plan 9.

**Comment by rsc** [comment]
If we can get a Plan 9 builder (either 386 or amd64) running on GCP VMs again, that would help with being able to run the Plan 9 tests in advance of security releases. That's #29801.

**Comment by millerresearch** [comment]
> If we can get a Plan 9 builder (either 386 or amd64) running on GCP VMs again, that would help with being able to run the Plan 9 tests in advance of security releases. That's #29801.

Suppose the plan9-arm builder could run on AWS arm bare-metal, would that be an acceptable alternative?

**Comment by millerresearch** [comment]
> Suppose the plan9-arm builder could run on AWS arm bare-metal, would that be an acceptable alternative?

As an alternative alternative, one (physical) raspberry pi in the reverse-dial plan9-arm cluster (in my house) could be kept in reserve for explicitly requested slowbot runs, so those wouldn't have to be queued up behind the normal trybot runs from every new CL. Is there a way to configure that in the coordinator? I guess using a separate builder name would work.
