### ISSUE TITLE
security: include CVE IDs in pre-announcements

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#56547]
In the lead-up to the (then downgraded) CRITICAL OpenSSL vulnerability, [there was some discussion](https://twitter.com/FiloSottile/status/1587376656594993154) of how it would be useful to have the CVE IDs included in security pre-announcements, to pre-fill triage issues and docs without using made up names.

A valid objection is that things sometimes change between the pre-announcement and publication, or sometimes the pre-announcement is sent before the CVE ID is assigned. I think that's fine, because this can be a best-effort policy without causing collateral damage. If the CVE changes, it can be called out in the release announcement. If one is not available, it can be stated as so in the pre-announcement.

I propose that pre-announcements per the Security Policy start including the CVE IDs when available.

/cc @golang/security @golang/release

**Comment by rolandshoemaker** [comment]
No objection here. It seems inevitable that we'll eventually need to add/remove a CVE between the pre-announcement and the release, but that is no worse than what we do now where we just share nothing.

**Comment by rolandshoemaker** [comment]
👍 nothing else to do here.
