### ISSUE TITLE
x/website: github icon in nav is not visible in dark-mode 

### ISSUE THREAD

**Issue by hyangah** [golang/go#56559]
In "Get Connected" section

![Screen Shot 2022-11-03 at 4 33 18 PM](https://user-images.githubusercontent.com/4999471/199828480-95f2a955-6ec4-43b0-97bf-401aa1184a76.png)

**Comment by mrwormhole** [comment]
how do you activate the dark mode? I can't see it on the go.dev?

**Comment by eutampieri** [comment]
There should be an option in your browser's web dev tools
