### ISSUE TITLE
x/mobile: multiple libraries in android

### ISSUE THREAD

**Issue by DAT4** [golang/go#56567]
[This question I made originally on stackoverflow - but I never got any reply.
](https://stackoverflow.com/questions/70908381/duplicate-class-go-seq-found-in-modules-jetified-packageone-runtime-packageone)

---

I am trying to use two different go packages in my android app project

I am using gomobile and each package is compiled with

```
gomobile bind --target=android
```

They are imported like this

```gradle
implementation files("libs/packageone.aar")
implementation files("libs/packagetwo.aar")
```

and they work separateley, but they conflict when i try to run the app.

and I get the following error

```
Duplicate class go.Seq found in modules jetified-packageone-runtime (packageone.aar) and jetified-packagetwo-runtime (packagetwo.aar)
```

**Comment by zhcandroid** [comment]
@DAT4  请问题这个问题解决了吗 我也遇到了同样的问题！

**Comment by DAT4** [comment]
@zhcandroid 你必须将你的模块组合成一个 - 问题还没有解决 ！

english: You need to combine your modules to one. The problem is not resolved.

**Comment by MrKrisYu** [comment]
About using multiple aar in as, i offer a solution, more details see my fork: https://github.com/MrKrisYu/mobile

**Comment by phxism** [comment]
keep an eye on it

**Comment by khayyamov** [comment]
The basic method is to be able to create different packages with one parameter so that we can have several aar made with gomobile in one project.

The combine solution is not economical at all for the situation I have with the amount of code that has compatibility problems

**Comment by musqdp** [comment]
error: package go does not exist import go.Seq;
