### ISSUE TITLE
affected/package: strconv

### ISSUE THREAD

**Issue by zsr228** [golang/go#56566]
func TestNumFormatString(t *testing.T) {    
		digit := 14.10    
		fmt.Println(strconv.FormatFloat(digit, 'f', -1, 64)) // 14.1
		fmt.Println(fmt.Sprintf("%f", digit))                // 14.100000
		fmt.Println(strconv.FormatFloat(digit, 'f', 2, 64))  // 14.10  It's what I want
	}
	/* Need Help
	I want the digit  format string to keep zero after the decimal point，but the length end with zeros is dynamic。
	After I read the strconv package，it looks like there is no way to handle it
	*/

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
