### ISSUE TITLE
x/vuln: add flag to provide actionable govulncheck fixes

### ISSUE THREAD

**Issue by el10savio** [golang/go#56569]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.2 darwin/amd64
</pre>

### Does this issue reproduce at the latest version of golang.org/x/vuln?
Feature Request:

Provide a flag '--fixes/-f' that would parse the output of `govulncheck` and suggest actionable steps to fix them.

For example., 

```
  Found in: github.com/gin-gonic/gin@v1.6.3
  Fixed in: github.com/gin-gonic/gin@v1.7.7
  More info: https://pkg.go.dev/vuln/GO-2021-0052
```

Would output 
```
Please run `go get -u github.com/gin-gonic/gin@v1.7.7`
```

Also given the fact that this output would be shown for both direct and indirect dependencies and suggests a `go get` generic message to update the calling dependency (package-function).

```
<call-stack> --- <package-function> --- <affected-function>
```

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/e.savio/Library/Caches/go-build"
GOENV="/Users/e.savio/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/e.savio/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/e.savio/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.19.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.19.2/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.19.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/44/79ttc6d962x84fw3_2g0wd2sdh29lk/T/go-build2982873195=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
N/A

### What did you expect to see?
N/A

### What did you see instead?
N/A

**Comment by zpavlinovic** [comment]
Would 

```
Please run `go get -u github.com/gin-gonic/gin@v1.7.7`
```

replace 

```
Found in: github.com/gin-gonic/gin@v1.6.3
Fixed in: github.com/gin-gonic/gin@v1.7.7
More info: https://pkg.go.dev/vuln/GO-2021-0052
```

or just be an additional row in the latter message?

It seems that `Fixed in` effectively contains all the needed info. Would the benefit for the user be the ease of copy/paste?

**Comment by el10savio** [comment]
Hi @zpavlinovic, 

Yep, I was thinking that when setting the `--fixes` flag it would only print

```
go get -u github.com/gin-gonic/gin@v1.7.7
```

Which I was hoping one could use to pipe into bash to automatically fix vulnerability issues reported that could be fixed by just running `go get -u` for the appropriate vulnerabilities.

But, to be honest, you are right about the fact that 

```
Found in: github.com/gin-gonic/gin@v1.6.3
Fixed in: github.com/gin-gonic/gin@v1.7.7
More info: https://pkg.go.dev/vuln/GO-2021-0052
```

Is enough in and of itself. I guess one could just pipe the output to `grep "Fixed in"` and use that to form the appropriate fixes. 

I would be closing the issue since it looks like its not needed. Thanks a lot for checking out the feature request.

**Comment by zpavlinovic** [comment]
We will definitely investigate the option for providing a -fix flag, but we currently don't know what the outcome of that will be or when it will be determined.

Feel free to close the issue if the grep approach works for you.

**Comment by el10savio** [comment]
Sure yep Thank you @zpavlinovic
