### ISSUE TITLE
affected/package: net/http

### ISSUE THREAD

**Issue by CravateRouge** [golang/go#56589]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.3
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Windows 10 x64

### What did you do?
`http.Get("https://some.website.intranet")`

### What did you expect to see?
HTTP Response or HTTP error

### What did you see instead?
`Get "https://some.website.intranet": dial tcp 172.X.X.X:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions.`

If i do the same for external website (e.g google.com) I don't have this issue. I suspect it's because it has to go through my VPN (I use Win 10 VPN client) but I don't know why I have this error because http get shouldn't try to bind to a port of my Windows right?

Could you please enlighten me on this issue?

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
