### ISSUE TITLE
x/tools/gopls: Warn UnusedVar for unused assign

### ISSUE THREAD

**Issue by igoracmelo** [golang/go#56598]
### gopls version
```
Build info
----------
golang.org/x/tools/gopls v0.10.1
    golang.org/x/tools/gopls@v0.10.1 h1:JoHe17pdZ8Vsa24/GUO8iTVTKPh0EOBiWpPop7XJybI=
    github.com/BurntSushi/toml@v1.2.0 h1:Rt8g24XnyGTyglgET/PRUNlrUeu9F5L+7FilkXfZgs0=
    github.com/google/go-cmp@v0.5.8 h1:e6P7q2lk1O+qJJb4BtCQXlK8vWEO8V1ZeuEdJNOqZyg=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/exp@v0.0.0-20220722155223-a9213eeb770e h1:+WEEuIdZHnUeJJmEUjyYC2gfUMj69yZXw17EnHg/otA=
    golang.org/x/exp/typeparams@v0.0.0-20220722155223-a9213eeb770e h1:7Xs2YCOpMlNqSQSmrrnhlzBXIE/bpMecZplbLePTJvE=
    golang.org/x/mod@v0.6.0 h1:b9gGHsz9/HhJ3HF5DHQytPpuwocVTChQJK3AvoLRD5I=
    golang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4 h1:uVc8UZUe6tr40fFVnUP5Oj+veunVezqYl9z7DYw9xzw=
    golang.org/x/sys@v0.1.0 h1:kunALQeHf1/185U1i0GOB/fy1IPRDDpuoOOqRReG57U=
    golang.org/x/text@v0.4.0 h1:BrVqGRd7+k1DiOgtnFvAkoQEWQvBc25ouMJM6429SFg=
    golang.org/x/tools@v0.2.1-0.20221101170700-b5bc717366b2 h1:KBm+UwBaO/tdQ35tfGvxH1FUCiXRg4MoTzkznsdeab8=
    golang.org/x/vuln@v0.0.0-20221010193109-563322be2ea9 h1:KaYZQUtEEaV8aVADIHAuYBTjo77aUcCvC7KTGKM3J1I=
    honnef.co/go/tools@v0.3.3 h1:oDx7VAwstgpYpb3wv0oxiZlxY+foCpRAwY7Vk6XpAgA=
    mvdan.cc/gofumpt@v0.3.1 h1:avhhrOmv0IuvQVK7fvwV91oFSGAk5/6Po8GXTzICeu8=
    mvdan.cc/xurls/v2@v2.4.0 h1:tzxjVAj+wSBmDcF6zBB7/myTy3gX9xvi8Tyr28AuQgc=
go: go1.18.1
```

### go env

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/igor/.cache/go-build"
GOENV="/home/igor/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/igor/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/igor/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3498574676=/tmp/go-build -gno-record-gcc-switches"
```

#### Changing the value of a variable won't warn me that the new value is not being used.
```go
_, err := os.Stat("somefile")

// can't forget to handle error, because compiler forces me to use the variable
if err != nil {
	// ...
}	

_, err = os.Stat("anotherfile")
// forgets to handle error, because compiler doesn't force me nor warn that the new value is not used

doOtherStuff()
```

#### Workaround 1: declaring `err` inside an if scope:
```go
if _, err := os.Stat("somefile"); err != nil {
	// ...
}

if _, err := os.Stat("somefile"); false {
	// err declared but not used
}
```

This solution can get very messy. Example:
```go
if a, err := funcThatReturnsTwoThings("arg1", "arg2"); err != nil {
	if b, err := funcThatUsesA(a); err != nil {
		if c, err := funcThatUsesA(b); err != nil {
			fmt.Println(c)
		}	
	}
}
```

#### Workaround 2: different error variables:
```go
a, err1 := funcThatReturnsTwoThings("arg1", "arg2")
if err1 != nil {
}

b, err2 := funcThatUsesA(a)
if err2 != nil {
}

c, err3 := funcThatUsesA(b)
if err3 != nil {
}

fmt.Println(c)
```

It is cleaner, and may be the best workaround, but makes me creates more variables.

And it is not just for error handling. Warning variables that are reassigned and not used can help catching many bugs in existing code.

### What did you expect to see?
Could be a warn or an error:
```
value assigned to err is not used (UnusedVar)
```

Example in Rust:
![image](https://user-images.githubusercontent.com/85039990/200134205-d972771d-4ee5-48c5-ad3e-65d05a2405e3.png)

### What did you see instead?
Nothing.

### Editor and settings

I don't believe its necessary for this issue.

### Logs

I don't believe its necessary for this issue.

**Comment by igoracmelo** [comment]
I just found out that the golangci-lint has this warning.
It fixes my problem, but I still think it is a valid request for gopls.

![image](https://user-images.githubusercontent.com/85039990/200150907-08a4df16-7422-4313-a11f-a1c68fd7e8f5.png)

**Comment by hyangah** [comment]
Related: https://github.com/golang/go/issues/23142 (supporting from `vet`, not `gopls` though).

This feature is already available in VSCode through `staticcheck`, the default linter used by vscode go extension also detects it. If it didn't detect it, please make sure the staticcheck is installed and run.
 
![Screen Shot 2022-11-07 at 2 12 45 PM](https://user-images.githubusercontent.com/4999471/200394727-8565ea1e-39cf-472e-9d85-27d1d9b288fa.png)

If the proposal #23142 is accepted and implemented in `vet`, gopls will get it for free.
If the proposal #23142 is not accepted, gopls still can get it through its staticcheck integration already
(see [setting](https://github.com/golang/tools/blob/master/gopls/doc/settings.md#staticcheck-bool); in vscode-go `"gopls": {  "ui.diagnostic.staticcheck": true }`)  
![Screen Shot 2022-11-07 at 2 14 57 PM](https://user-images.githubusercontent.com/4999471/200395164-ca95de3d-54b9-4bd1-bd38-3b7056381c82.png)
