### ISSUE TITLE
cmd/doc: inconsistent removal of directive comments 

### ISSUE THREAD

**Issue by thockin** [golang/go#56592]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/thockin/.cache/go-build"
GOENV="/home/thockin/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/thockin/src/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/thockin/src/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/thockin/src/go/src/k8s.io/kubernetes/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3419971970=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Given this file:

```
package p

type T struct {
	// Field is a field.
	//magic:true
	Field int
}
```

Run `go doc`.

```
$ go doc --all .
package p // import "."


TYPES

type T struct {
	// Field is a field.
	//magic:true
	Field int
}
```

Note the "magic" directive is present.

```
$ go doc --all T
package p // import "."

type T struct {
	// Field is a field.
	//magic:true
	Field int
}
```

Still has magic directive.

```
$ go doc --all T.Field
package p // import "."

type T struct {
    // Field is a field.
    Field int
}
```

This time, the magic is detected as a directive and removed.  Shouldn't that happen in all cases? 

### What did you expect to see?

Consistent stripping of "directives".

### What did you see instead?

Inconsistent stripping of "directives".

**Comment by thockin** [comment]
cmd/doc/pkg.go :: `func Package.emit` calls `format.Node(&pkg.buf, pkg.fs, arg)` but the field-centric invocation calls into each dtruct-field's `field.Doc.Text()` which calls go/ast/ast.go `CommentGroup.Text()` which checks `isDirective()`.

**Comment by seankhliao** [comment]
cc @robpike

**Comment by robpike** [comment]
This is surely an issue with the go/doc package, not the cmd/doc command, which just formats what the package provides.

@griesemer

**Comment by thockin** [comment]
Hi all, this popped up again - is there any way I can help get traction on it?

**Comment by thockin** [comment]
Thanks!  I tried it at gotip and I see something unexpected:

given this file:
```
// Package p is a package.
//
//magic:true
package p

// T is a type
//
//magic:true
type T struct {
	// Field is a field
	//magic:true
	Field int
}
```

go doc shows:

```
$ go doc --all .
package p // import "hockin.org/p"

Package p is a package.

TYPES

type T struct {
	// Field is a field
	//magic:true
	Field int
}
    T is a type
```

Note the directive is still present.  gotip says:

```
$ gotip doc --all .
package p // import "hockin.org/p"

Package p is a package.

TYPES

type T struct {
	// Field is a field

	Field int
}
    T is a type
```

The directive is gone (yay) but there's now a blank like.  Is that expected?  @ianlancetaylor

**Comment by ianlancetaylor** [comment]
@thockin It turns out to be rather painful to avoid.  Or to put it more fairly, I was sufficiently exhausted by the effort tracking through all the code that I didn't feel like trying to fix that too.

It's because go/ast records positions for all comments and tokens, and go/format honors those positions to try to recreate the same format as the original file.  That means that without extra work, when a comment line disappears, go/format inserts an extra line to get back to the expected position.  Just disregarding the positions doesn't work, as that would mean that we lose track of which comments come before a field and which comments appear on the same line as a field.  So removing the blank line is non-trivial, or, at least, I haven't seen a simple solution.

I do think that the gotip output is better.  But as you say it's perhaps not ideal.  By all means open a new issue.
