### ISSUE TITLE
affected/package: net

### ISSUE THREAD

**Issue by CravateRouge** [golang/go#56597]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.19.3
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\JohnDoe\AppData\Local\go-build
set GOENV=C:\Users\JohnDoe\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\JohnDoe\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\JohnDoe\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Users\JohnDoe\AppData\Local\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Users\JohnDoe\AppData\Local\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.19.3
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\JohnDoe\AppData\Local\Temp\go-build1397425744=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
I tried to establish a TCP connection with an intranet address using the following go snippet:
```go
s, err := syscall.Socket(syscall.AF_NET, syscall.SOCK_STREAM, 6)
if err != nil {
    log.Fatal(err)
}
addr := &syscall.SockaddrInet4{
    Port:443,
    Addr: [4]byte{10,X,X,X}
}
if err := syscall.Connect(s, addr); err != nil {
    log.Fatal(err)
}
syscall.Closesocket(s)
```

### What did you expect to see?
I expect to see the code running without error as the equivalent C code did:
```c
#include <winsock2.h>
#pragma comment(lib, "ws2_32.lib")
#pragma warning(disable:4996)
int main(){
    SOCKET sock;
    SOCKADDR_IN sin;
    sock = socket(AF_INET, SOCK_STREAM, 0);
    sin.sin_addr.s_addr = inet_addr("10.X.X.X");
    sin.sin_family = AF_INET;
    sin.sin_port = htons(443);
    connect(sock, (SOCKADDR*)&sin, sizeof(sin));
    closesocket(sock);
    return 0;
}
```
The same WinAPI functions are used but the go snippet fail to execute.

### What did you see instead?
I saw the following error code: `An attempt was made to access a socket in a way forbidden by its access permissions`

### Environment details
```
route PRINT -4
===========================================================================
Liste d'Interfaces
  7...04 0e 3c c9 d1 d8 ......Intel(R) Ethernet Connection (6) I219-LM
 16...24 ee 9a 7e 43 94 ......Microsoft Wi-Fi Direct Virtual Adapter
 19...26 ee 9a 7e 43 93 ......Microsoft Wi-Fi Direct Virtual Adapter #2
  4...24 ee 9a 7e 43 93 ......Intel(R) Wireless-AC 9560 160MHz
 53........................... VPN
  1...........................Software Loopback Interface 1
===========================================================================

IPv4 Table de routage
===========================================================================
Itinéraires actifs :
Destination réseau    Masque réseau  Adr. passerelle   Adr. interface Métrique
          0.0.0.0          0.0.0.0      192.168.1.1     192.168.1.18     35
         10.0.0.0        255.0.0.0         On-link    10.Y.Y.Y    311
===========================================================================
Itinéraires persistants :
  Aucun
```

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by CravateRouge** [comment]
@seankhliao Unless I miss something, the behavior of go `syscall.Connect` should be the same as C `connect` because it's the same WinAPI function. Hence it's a bug in the internal code of Go

**Comment by seankhliao** [comment]
no, you're being blocked by something, eg antivirus.

**Comment by CravateRouge** [comment]
You're right, the C code snippet has the same issue actually, I forgot I had to retrieve the error code from each function instead of them popping by themselves. I tried using connect in C# and it didn't work as an executable but worked when called as powershell objects. So it's more a matter of trusted vs untrusted software.
