### ISSUE TITLE
darwin_amd64/link: combining dwarf failed: Unknown load command 0x80000033 (2147483699)

### ISSUE THREAD

**Issue by weirubo** [golang/go#56605]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.15 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Because the framework is go-micro v1.18, so I must use go v1.13, and i use go v1.13.15, it's the latest release of go v.1.13

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/frank/Library/Caches/go-build"
GOENV="/Users/frank/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=" -mod="
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/frank/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/Users/frank/go/go1.13.15"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/frank/go/go1.13.15/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/frank/opensource/go-micro-v1/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/w7/18c05pys5zjb25d2t6qr7s7m0000gn/T/go-build367507295=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

I just execute the command of go build.

main.go
<pre>
package main

import "github.com/micro/go-micro"

func main() {
	service := micro.NewService()
	service.Init()
	service.Run()
}
</pre>

### What did you expect to see?

build success

### What did you see instead?

\# github.com/weirubo/go-micro-v1
ld: warning: -no_pie is deprecated when targeting new OS versions
ld: warning: non-standard -pagezero_size is deprecated when targeting macOS 13.0 or later
/Users/frank/go/go1.13.15/pkg/tool/darwin_amd64/link: /Users/frank/go/go1.13.15/pkg/tool/darwin_amd64/link: combining dwarf failed: Unknown load command 0x80000033 (2147483699)

**Comment by seankhliao** [comment]
Sorry, we don't support 1.13 anymore.

**Comment by weirubo** [comment]
> 

Thank you for your answer, and i change the go version to go v1.14.15, go v1.15.15, go v1.16.15, the result of go v1.14.15 and go v.15.15 the same with go v1.13.15

But, go v1.16.15 happend the new error:

<pre>
# github.com/weirubo/go-micro-v1
ld: warning: -no_pie is deprecated when targeting new OS versions
ld: warning: non-standard -pagezero_size is deprecated when targeting macOS 13.0 or later
/private/var/folders/w7/18c05pys5zjb25d2t6qr7s7m0000gn/T/GoLand/___go_build_github_com_weirubo_go_micro_v1
panic: qtls.ConnectionState not compatible with tls.ConnectionState

goroutine 1 [running]:
github.com/lucas-clemente/quic-go/internal/handshake.init.1()
        /Users/frank/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.13.1/internal/handshake/unsafe.go:17 +0x12e
</pre>

**Comment by ianlancetaylor** [comment]
The currently supported versions of Go are 1.18 and 1.19.

**Comment by BeautifulMaker** [comment]
I also have this problem when update macos 13.0

**Comment by weirubo** [comment]
> 

Because i must use go-micro v1.18, so i read many article, last  i find this blog, if you need , could read it too.

https://imlht.com/archives/239/

Thanks  a lot to the author of this blog.

**Comment by danwelcome** [comment]
Does anyone know if there is a workaround to get past this error without upgrading Go versions?

**Comment by fonoisrev** [comment]
I have solve this problem by installing the XCode v13.4.1 manual.
Then use command `xcode-select -p' to change the xcode command line tools version.
I works!!
@BeautifulMaker

**Comment by rizkifadilah12** [comment]
> I have solve this problem by installing the XCode v13.4.1 manual. Then use command `xcode-select -p' to change the xcode command line tools version. It works!! @BeautifulMaker
> 
> > I also have this problem when update macos 13.0

I try to install Xcode v13.4.1 but got this message
The version of Xcode installed on this Mac is not compatible with macOS Ventura. Download the latest version for free from the App Store.
How you solved that?

**Comment by avinashmidathada** [comment]
You can manually download an older version [here](https://developer.apple.com/download/all/?q=xcode). This worked for me until I upgraded to MacOS Ventura 13.3, and now even using Xcode 13.4.1 or older versions doesn't solve the problem!

@fonoisrev I wonder how you identified you had to downgrade xcode version? How do you even debug this error?

**Comment by Cameron-Wang** [comment]
May be this config can solve your problem.
add environment config `CGO_ENABLED=0`

**Comment by billgalin** [comment]
when i update go version, it works, but i dont know why...
