### ISSUE TITLE
x/pkgsite: package removal request for [https://github.com/aliml92/ocpp]

### ISSUE THREAD

**Issue by aliml92** [golang/go#56602]
### What is the path of the package that you would like to have removed?
https://github.com/aliml92/ocpp
 
 
 
### Are you the owner of this package?
yes

 
### What is the reason that you could not retract this package instead?
I accidentally gave to my package the version 1.0.0, which was to early to make the package stable.

**Comment by seankhliao** [comment]
Please use `rettract`, pkgsite package removal will not allow you to reuse v1.0.0
