### ISSUE TITLE
cmd/compile: ICE instantiating a generic type `B` in `type A[T] struct{}; type B[T] A[[]T]` with `error`

### ISSUE THREAD

**Issue by twz123** [golang/go#56626]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/user/.local/share/go/bin"
GOCACHE="/home/user/.cache/go/cache"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user/.cache/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/.local/share/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/nix/store/mpbwhnfs6ciqrnckyn33z2yljsgpg416-go-1.19.3/share/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/nix/store/mpbwhnfs6ciqrnckyn33z2yljsgpg416-go-1.19.3/share/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/user/boom/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3668342732=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I've put together the following program: https://go.dev/play/p/J8PRzNRJoUi

### What did you expect to see?

As far as my Go knowledge goes, I think the above program is valid. I expected to see the program compile and run with no output. If I am wrong and the program is not okay, I would have expected a proper compiler error to be displayed that indicates the problem(s).

### What did you see instead?

An internal compiler error. Running this on the Go Playground gives me:

```text
# play.ground/foo
<autogenerated>:1: internal compiler error: missing pkg

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new

Go build failed.
```

### My observations

* Using any other type than `error` in `x := SlicedInner[error]{}` on line 27 makes it compile. I tried other interfaces (including `any`), primitives, struct pointers, ...
* Actually using the return value of `CallSomeFuncOnInner` (i.e. by uncommenting the `fmt.Println`) fixes it, too.

**Comment by mknyszek** [comment]
CC @golang/compiler

**Comment by cuonglm** [comment]
Duplicated of https://github.com/golang/go/issues/55101
