### ISSUE TITLE
misc/cgo/test: static test fails

### ISSUE THREAD

**Issue by aclements** [golang/go#56623]
### What version of Go are you using (`go version`)?

581a822a9ed8fcae4afbc93daa6a74db7d9ea9a2 in the Go 1.20 development tree

### What operating system and processor architecture are you using (`go env`)?

linux/loong64, observed on the trybots for [CL 448016 PS 1](https://go-review.git.corp.google.com/c/go/+/448016/1)

### What did you do?

I've been enabling dist tests for cgo on more architectures where it's not clear why they're disabled. One of the misc/cgo/test static build configurations crashes on linux/loong64. It's unfortunately not easy to extract tests from dist (something I'm hoping to improve), but I believe this is what the test is doing:

```sh
cd $GOROOT/misc/cgo/test
CGO_LDFLAGS="-static -pthread" go test -short=true -count=1 -run= -tags=static .
```

### What did you expect to see?

Test passes.

### What did you see instead?

Test crashes with "signal: bus error" ([trybot log](https://storage.googleapis.com/go-build-log/cdf348c8/linux-loong64-3a5000_d8029088.log))

/cc @golang/loong64

**Comment by abner-chenc** [comment]
Thank you very much，  I will try to solve this problem

**Comment by xen0n** [comment]
Another instance: https://build.golang.org/log/40befeb1926223b8194ffd6ff76777e20f81a434

CL 416154 is supposed to have this fixed though.
