### ISSUE TITLE
affected/package: x.net and x.sys is failing with error "note: module requires Go 1.17" where as go version installed is 1.19

### ISSUE THREAD

**Issue by shanmydell** [golang/go#56646]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.19.3
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

[root@csipowermax ~]# go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY="github.com/dell/gopowermax-juniper"
GONOSUMDB="github.com/dell/gopowermax-juniper"
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE="github.com/dell/gopowermax-juniper"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1917351821=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you expect to see?

go package is built into the container image

### What did you see instead?

# golang.org/x/sys/unix
/go/pkg/mod/golang.org/x/sys@v0.1.0/unix/syscall.go:83:16: undefined: unsafe.Slice
/go/pkg/mod/golang.org/x/sys@v0.1.0/unix/syscall_linux.go:2255:9: undefined: unsafe.Slice
/go/pkg/mod/golang.org/x/sys@v0.1.0/unix/syscall_unix.go:118:7: undefined: unsafe.Slice
/go/pkg/mod/golang.org/x/sys@v0.1.0/unix/sysvshm_unix.go:33:7: undefined: unsafe.Slice
note: module requires Go 1.17

/go/pkg/mod/golang.org/x/net@v0.1.0/http2/transport.go:437:45: undefined: os.ErrDeadlineExceeded
**note: module requires Go 1.17**

After updating to latest x.net, unable to build the image
Refer:
https://github.com/dell/csi-powermax/blob/main/go.mod

**Comment by shanmydell** [comment]
@matloob  @adonovan : Could you please look into this issue?

**Comment by shanmydell** [comment]
@findleyr  @mdempsky : Could you please look into this issue?

**Comment by seankhliao** [comment]
sounds like you have an out of date docker image.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by shanmydell** [comment]
@seankhliao : We have our package upto date with 1.19 where as x.net is failing stating module requires 1.17 which is a bug

**Comment by seankhliao** [comment]
please include a full reproducer

**Comment by shanmydell** [comment]
@seankhliao : I am unable to reopen the issue, will update the full reproducer now

**Comment by shanmydell** [comment]
@seankhliao : 
Full reproducer: While building the image it is failing 
Building the image from the repo here: https://github.com/dell/csi-powermax
+ bash ./build.sh -i ubim -pyoer 501
/usr/bin/podman
Using podman for building image
SOURCE_IMAGE_REPO is set to: registry.access.redhat.com
SOURCE_IMAGE_REPO_NAMESPACE is set to: ubi8/ubi-minimal
Source Image will be pulled from: registry.access.redhat.com/ubi8/ubi-minimal
BUILD_NUMBER specified via environment and set to: 000
BUILD_TYPE specified via environment and set to: R
Directory already exists
###################### BUILDING IMAGE ########################
podman inspect --type=image csi-powermax:v2.5.0.000R-501
podman build -t csi-powermax:v2.5.0.000R-501 -t csi-powermax:latest -t csi-powermax:v2.5.0 -f csi-powermax/Dockerfile.build . --build-arg BUILD_NUMBER=000 --build-arg BUILD_TYPE=R --build-arg GO_VERSION=1.19 --build-arg SOURCE_IMAGE_TAG=c8c1c0f893a7ba679fd65863f2d1389179a92957c31e95521b3290c6b6fc4a76 --build-arg SOURCE_REPO=registry.access.redhat.com/ubi8/ubi-minimal@sha256 --build-arg IMAGE_TYPE=ubim --format=docker
STEP 1: FROM golang:1.19 AS builder
Resolved "golang" as an alias (/var/cache/containers/short-name-aliases.conf)
Trying to pull docker.io/library/golang:1.19...
Getting image source signatures
Copying blob sha256:31f01728a4e155a49cc26989c315d6e9168832adbab874a83d3527b7127316f0
Copying blob sha256:17c9e6141fdb3387e5a1c07d4f9b6a05ac1498e96029fa3ea55470d4504f7770
Copying blob sha256:efa7548a174d51c2cadd24f9e629f436fbf1f501daba3e757d78c32f31c7fe83
Copying blob sha256:de4a4c6caea8801bb0b7377e10220a914da403bc93fa79663cbf2dcf1800b6f1
Copying blob sha256:a7969cffbf46e6a91291fd76b19ecbe93c03ea4ded0d14042aecb4c0c4211a43
Copying blob sha256:4edced8587e6c18412817019074f5e04a8ede4e2fc89d06af13df3f80d78a70d
Copying blob sha256:e7094519954655e5688d14bd7d0645392f5fe39090f01db37931752e8bf5fa6b
Copying config sha256:f7d4f5578ce3878c9d365e9cf30a97ebf77960c0dcdb52da6e8fe2808a4b64e7
Writing manifest to image destination
Storing signatures
STEP 2: ARG BUILD_NUMBER=0
--> 15ff207fcef
STEP 3: ARG BUILD_TYPE=R
--> 250f7b4a882
STEP 4: ENV BUILD_NUMBER=$BUILD_NUMBER
--> 654087f22b3
STEP 5: ENV BUILD_TYPE=$BUILD_TYPE
--> 7e13fb1b1e6
STEP 6: RUN mkdir -p /go/src
--> dd2dcd569b8
STEP 7: COPY csi-powermax/go.mod /go/src/csi-powermax/go.mod
--> 1b4388366e5
STEP 8: COPY csi-powermax/ /go/src/csi-powermax
--> b0ec44e05a9
STEP 9: COPY goiscsi/ /go/src/goiscsi
--> 018de129e53
STEP 10: COPY gofsutil/ /go/src/gofsutil
--> fda41d9ffc6
STEP 11: COPY gopowermax /go/src/gopowermax
--> 09db5d75751
STEP 12: COPY gobrick /go/src/gobrick
--> 793de66c02d
STEP 13: COPY gocsi /go/src/gocsi
--> 4479c96310c
STEP 14: COPY dell-csi-extensions /go/src/dell-csi-extensions
--> 2613368ffe6
STEP 15: WORKDIR /go/src/csi-powermax
--> f5f4586fc63
STEP 16: RUN go mod download
--> cbc0a4342bf
STEP 17: RUN ./check.sh
=== Checking format...
=== Finished
=== Vetting csi-powermax
=== Finished
=== Linting...
go: downloading golang.org/x/lint v0.0.0-20210508222113-6edffad5e616
go: downloading golang.org/x/tools v0.0.0-20200130002326-2f3ba24bd6e7
=== Finished
--> f97edb78abf
STEP 18: RUN go generate
--> a6b3362f93e
STEP 19: RUN CGO_ENABLED=0 go build
--> 0101bb11baa
STEP 20: RUN go run core/semver/semver.go -f mk
GOOS ?= linux
GOARCH ?= amd64
OS ?= Linux
ARCH ?= x86_64
MAJOR ?= 2
MINOR ?= 4
PATCH ?= 0
BUILD ?= 000
NOTES ?= 
TYPE ?= R
DIRTY ?= true
SHA7 ?= 759fc1b
SHA32 ?= 759fc1b7ea0273592984c99c7656ae3fbfd3a656
EPOCH ?= 1667564148
SEMVER ?= 2.4.0+dirty
SEMVER_RPM ?= 2.4.0+dirty
BUILD_DATE ?= Fri, 04 Nov 2022 12:15:48 UTC
RELEASE_DATE ?= 22-11-04
--> 64401aec0c5
STEP 21: FROM registry.access.redhat.com/ubi8/ubi-minimal@sha256:c8c1c0f893a7ba679fd65863f2d1389179a92957c31e95521b3290c6b6fc4a76 AS driver-others
Trying to pull registry.access.redhat.com/ubi8/ubi-minimal@sha256:c8c1c0f893a7ba679fd65863f2d1389179a92957c31e95521b3290c6b6fc4a76...
Getting image source signatures
Copying blob sha256:d6e3788a121c267b721a23e030dd339c41f70721e09bdf4b21051cfb22421025
Copying blob sha256:b336a633f9e2c8ec18c45427d7e957df6d20ec09e71eee92c2f3247bb63c2d66
Copying config sha256:017b05e1359182e10f9360b771a740a2ea44d11dd1ed0fb3ad4021fb4c342460
Writing manifest to image destination
Storing signatures
STEP 22: ONBUILD RUN yum install -y e2fsprogs which xfsprogs device-mapper-multipath     &&     yum clean all     &&     rm -rf /var/cache/run
--> a54492b282c
STEP 23: FROM registry.access.redhat.com/ubi8/ubi-minimal@sha256:c8c1c0f893a7ba679fd65863f2d1389179a92957c31e95521b3290c6b6fc4a76 AS driver-ubim
STEP 24: ONBUILD RUN microdnf update -y     &&     microdnf install -y e2fsprogs which xfsprogs device-mapper-multipath     &&     microdnf clean all
--> 486c411018c
STEP 25: FROM 486c411018c468fc1ee3a695b2e89e415621e4c651fe3bc75531b0ca331be522 AS driver
STEP 26: RUN microdnf update -y     &&     microdnf install -y e2fsprogs which xfsprogs device-mapper-multipath     &&     microdnf clean all
Downloading metadata...
Downloading metadata...
Downloading metadata...
Downloading metadata...
Downloading metadata...
Package                                                 Repository                        Size
Installing:                                                                                   
 acl-2.2.53-1.el8.x86_64                                ubi-8-baseos                   83.0 kB
 cracklib-2.9.6-15.el8.x86_64                           ubi-8-baseos                   95.5 kB
 cracklib-dicts-2.9.6-15.el8.x86_64                     ubi-8-baseos                    4.1 MB
 cryptsetup-libs-2.3.7-2.el8.x86_64                     ubi-8-baseos                  499.4 kB
 dbus-1:1.12.8-18.el8_6.1.x86_64                        ubi-8-baseos                   42.5 kB
 dbus-common-1:1.12.8-18.el8_6.1.noarch                 ubi-8-baseos                   47.3 kB
 dbus-daemon-1:1.12.8-18.el8_6.1.x86_64                 ubi-8-baseos                  246.3 kB
 dbus-libs-1:1.12.8-18.el8_6.1.x86_64                   ubi-8-baseos                  188.6 kB
 dbus-tools-1:1.12.8-18.el8_6.1.x86_64                  ubi-8-baseos                   87.8 kB
 device-mapper-8:1.02.181-3.el8_6.2.x86_64              ubi-8-baseos                  386.5 kB
 device-mapper-libs-8:1.02.181-3.el8_6.2.x86_64         ubi-8-baseos                  419.6 kB
 diffutils-3.6-6.el8.x86_64                             ubi-8-baseos                  367.4 kB
 elfutils-debuginfod-client-0.186-1.el8.x86_64          rhel-8-for-x86_64-baseos-rpms  72.8 kB
 elfutils-default-yama-scope-0.186-1.el8.noarch         ubi-8-baseos                   51.7 kB
 elfutils-libs-0.186-1.el8.x86_64                       ubi-8-baseos                  302.2 kB
 expat-2.2.5-8.el8_6.3.x86_64                           ubi-8-baseos                  116.2 kB
 gnupg2-smime-2.2.20-3.el8_6.x86_64                     ubi-8-baseos                  289.9 kB
 gzip-1.9-13.el8_5.x86_64                               ubi-8-baseos                  170.8 kB
 kmod-libs-25-19.el8.x86_64                             ubi-8-baseos                   70.1 kB
 libfdisk-2.32.1-35.el8.x86_64                          ubi-8-baseos                  258.1 kB
 libnsl2-1.2.0-2.20180605git4a062cf.el8.x86_64          ubi-8-baseos                   59.1 kB
 libpwquality-1.4.4-3.el8.x86_64                        ubi-8-baseos                  109.5 kB
 libseccomp-2.5.2-1.el8.x86_64                          ubi-8-baseos                   72.9 kB
 libsecret-0.18.6-1.el8.x86_64                          ubi-8-baseos                  166.9 kB
 libsemanage-2.9-9.el8_6.x86_64                         ubi-8-baseos                  172.1 kB
 libtirpc-1.1.4-6.el8.x86_64                            ubi-8-baseos                  115.3 kB
 libutempter-1.1.6-14.el8.x86_64                        ubi-8-baseos                   32.6 kB
 libxkbcommon-0.9.1-1.el8.x86_64                        ubi-8-appstream               118.5 kB
 pam-1.3.1-16.el8_6.1.x86_64                            ubi-8-baseos                  757.5 kB
 pinentry-1.1.0-2.el8.x86_64                            ubi-8-appstream               102.3 kB
 shadow-utils-2:4.6-16.el8.x86_64                       ubi-8-baseos                    1.3 MB
 shared-mime-info-1.9-3.el8.x86_64                      ubi-8-baseos                  336.4 kB
 systemd-239-58.el8_6.8.x86_64                          ubi-8-baseos                    3.8 MB
 systemd-pam-239-58.el8_6.8.x86_64                      ubi-8-baseos                  498.3 kB
 trousers-0.3.15-1.el8.x86_64                           ubi-8-baseos                  156.3 kB
 trousers-lib-0.3.15-1.el8.x86_64                       ubi-8-baseos                  171.6 kB
 util-linux-2.32.1-35.el8.x86_64                        ubi-8-baseos                    2.6 MB
 xkeyboard-config-2.28-1.el8.noarch                     ubi-8-appstream               801.0 kB
Upgrading:                                                                                    
 ca-certificates-2022.2.54-80.2.el8_6.noarch            ubi-8-baseos                  942.8 kB
  replacing ca-certificates-2021.2.50-80.0.el8_4.noarch                                       
 glib2-2.56.4-158.el8_6.1.x86_64                        ubi-8-baseos                    2.6 MB
  replacing glib2-2.56.4-158.el8.x86_64                                                       
 gnupg2-2.2.20-3.el8_6.x86_64                           ubi-8-baseos                    2.5 MB
  replacing gnupg2-2.2.20-2.el8.x86_64                                                        
 gnutls-3.6.16-5.el8_6.x86_64                           ubi-8-baseos                    1.0 MB
  replacing gnutls-3.6.16-4.el8.x86_64                                                        
 libdnf-0.63.0-8.2.el8_6.x86_64                         ubi-8-baseos                  723.4 kB
  replacing libdnf-0.63.0-8.1.el8_6.x86_64                                                    
 libksba-1.3.5-8.el8_6.x86_64                           ubi-8-baseos                  137.4 kB
  replacing libksba-1.3.5-7.el8.x86_64                                                        
 rpm-4.14.3-24.el8_6.x86_64                             ubi-8-baseos                  556.5 kB
  replacing rpm-4.14.3-23.el8.x86_64                                                          
 rpm-libs-4.14.3-24.el8_6.x86_64                        ubi-8-baseos                  353.8 kB
  replacing rpm-libs-4.14.3-23.el8.x86_64                                                     
 sqlite-libs-3.26.0-16.el8_6.x86_64                     ubi-8-baseos                  594.8 kB
  replacing sqlite-libs-3.26.0-15.el8.x86_64                                                  
 systemd-libs-239-58.el8_6.8.x86_64                     ubi-8-baseos                    1.2 MB
  replacing systemd-libs-239-58.el8_6.4.x86_64                                                
 tzdata-2022f-1.el8.noarch                              ubi-8-baseos                  480.6 kB
  replacing tzdata-2022c-1.el8.noarch                                                         
 zlib-1.2.11-19.el8_6.x86_64                            ubi-8-baseos                  105.1 kB
   replacing zlib-1.2.11-18.el8_5.x86_64                                                      
Transaction Summary:
 Installing:       38 packages
 Reinstalling:      0 packages
 Upgrading:        12 packages
 Obsoleting:        0 packages
 Removing:          0 packages
 Downgrading:       0 packages
Downloading packages...
Running transaction test...
Updating: zlib;1.2.11-19.el8_6;x86_64;ubi-8-baseos
Updating: systemd-libs;239-58.el8_6.8;x86_64;ubi-8-baseos
Updating: sqlite-libs;3.26.0-16.el8_6;x86_64;ubi-8-baseos
Installing: dbus-libs;1:1.12.8-18.el8_6.1;x86_64;ubi-8-baseos
Updating: libksba;1.3.5-8.el8_6;x86_64;ubi-8-baseos
Installing: libtirpc;1.1.4-6.el8;x86_64;ubi-8-baseos
Installing: libnsl2;1.2.0-2.20180605git4a062cf.el8;x86_64;ubi-8-baseos
Installing: dbus-tools;1:1.12.8-18.el8_6.1;x86_64;ubi-8-baseos
Updating: rpm-libs;4.14.3-24.el8_6;x86_64;ubi-8-baseos
Updating: rpm;4.14.3-24.el8_6;x86_64;ubi-8-baseos
Installing: kmod-libs;25-19.el8;x86_64;ubi-8-baseos
Installing: xkeyboard-config;2.28-1.el8;noarch;ubi-8-appstream
Installing: libxkbcommon;0.9.1-1.el8;x86_64;ubi-8-appstream
Installing: acl;2.2.53-1.el8;x86_64;ubi-8-baseos
Installing: libsemanage;2.9-9.el8_6;x86_64;ubi-8-baseos
Installing: shadow-utils;2:4.6-16.el8;x86_64;ubi-8-baseos
Installing: libutempter;1.1.6-14.el8;x86_64;ubi-8-baseos
Installing: libfdisk;2.32.1-35.el8;x86_64;ubi-8-baseos
Installing: libseccomp;2.5.2-1.el8;x86_64;ubi-8-baseos
Installing: diffutils;3.6-6.el8;x86_64;ubi-8-baseos
Installing: trousers-lib;0.3.15-1.el8;x86_64;ubi-8-baseos
Installing: gzip;1.9-13.el8_5;x86_64;ubi-8-baseos
Installing: cracklib;2.9.6-15.el8;x86_64;ubi-8-baseos
Installing: cracklib-dicts;2.9.6-15.el8;x86_64;ubi-8-baseos
Installing: libpwquality;1.4.4-3.el8;x86_64;ubi-8-baseos
Installing: pam;1.3.1-16.el8_6.1;x86_64;ubi-8-baseos
Installing: util-linux;2.32.1-35.el8;x86_64;ubi-8-baseos
Installing: expat;2.2.5-8.el8_6.3;x86_64;ubi-8-baseos
Installing: device-mapper;8:1.02.181-3.el8_6.2;x86_64;ubi-8-baseos
Installing: device-mapper-libs;8:1.02.181-3.el8_6.2;x86_64;ubi-8-baseos
Installing: cryptsetup-libs;2.3.7-2.el8;x86_64;ubi-8-baseos
Installing: elfutils-debuginfod-client;0.186-1.el8;x86_64;rhel-8-for-x86_64-baseos-rpms
Installing: elfutils-default-yama-scope;0.186-1.el8;noarch;ubi-8-baseos
Installing: elfutils-libs;0.186-1.el8;x86_64;ubi-8-baseos
Updating: gnutls;3.6.16-5.el8_6;x86_64;ubi-8-baseos
Installing: dbus-common;1:1.12.8-18.el8_6.1;noarch;ubi-8-baseos
Installing: dbus-daemon;1:1.12.8-18.el8_6.1;x86_64;ubi-8-baseos
Installing: systemd-pam;239-58.el8_6.8;x86_64;ubi-8-baseos
Installing: systemd;239-58.el8_6.8;x86_64;ubi-8-baseos
Installing: trousers;0.3.15-1.el8;x86_64;ubi-8-baseos
Installing: dbus;1:1.12.8-18.el8_6.1;x86_64;ubi-8-baseos
Updating: glib2;2.56.4-158.el8_6.1;x86_64;ubi-8-baseos
Installing: shared-mime-info;1.9-3.el8;x86_64;ubi-8-baseos
Installing: libsecret;0.18.6-1.el8;x86_64;ubi-8-baseos
Installing: pinentry;1.1.0-2.el8;x86_64;ubi-8-appstream
Installing: gnupg2-smime;2.2.20-3.el8_6;x86_64;ubi-8-baseos
Updating: gnupg2;2.2.20-3.el8_6;x86_64;ubi-8-baseos
Updating: libdnf;0.63.0-8.2.el8_6;x86_64;ubi-8-baseos
Updating: ca-certificates;2022.2.54-80.2.el8_6;noarch;ubi-8-baseos
Updating: tzdata;2022f-1.el8;noarch;ubi-8-baseos
Cleanup: libdnf;0.63.0-8.1.el8_6;x86_64;installed
Cleanup: gnupg2;2.2.20-2.el8;x86_64;installed
Cleanup: glib2;2.56.4-158.el8;x86_64;installed
Cleanup: rpm;4.14.3-23.el8;x86_64;installed
Cleanup: ca-certificates;2021.2.50-80.0.el8_4;noarch;installed
Cleanup: tzdata;2022c-1.el8;noarch;installed
Cleanup: rpm-libs;4.14.3-23.el8;x86_64;installed
Cleanup: sqlite-libs;3.26.0-15.el8;x86_64;installed
Cleanup: zlib;1.2.11-18.el8_5;x86_64;installed
Cleanup: gnutls;3.6.16-4.el8;x86_64;installed
Cleanup: libksba;1.3.5-7.el8;x86_64;installed
Cleanup: systemd-libs;239-58.el8_6.4;x86_64;installed
Complete.
Downloading metadata...
Downloading metadata...
Package                                           Repository                        Size
Installing:                                                                             
 device-mapper-multipath-0.8.4-22.el8.x86_64      rhel-8-for-x86_64-baseos-rpms 204.4 kB
 device-mapper-multipath-libs-0.8.4-22.el8.x86_64 rhel-8-for-x86_64-baseos-rpms 333.3 kB
 e2fsprogs-1.45.6-4.el8.x86_64                    rhel-8-for-x86_64-baseos-rpms   1.1 MB
 e2fsprogs-libs-1.45.6-4.el8.x86_64               rhel-8-for-x86_64-baseos-rpms 238.7 kB
 fuse-libs-2.9.7-15.el8.x86_64                    ubi-8-baseos                  104.6 kB
 kpartx-0.8.4-22.el8.x86_64                       rhel-8-for-x86_64-baseos-rpms 117.1 kB
 libaio-0.3.112-1.el8.x86_64                      ubi-8-baseos                   33.4 kB
 libss-1.45.6-4.el8.x86_64                        ubi-8-baseos                   55.0 kB
 userspace-rcu-0.10.1-4.el8.x86_64                ubi-8-baseos                  103.2 kB
 which-2.21-17.el8.x86_64                         ubi-8-baseos                   50.6 kB
 xfsprogs-5.0.0-10.el8.x86_64                     rhel-8-for-x86_64-baseos-rpms   1.1 MB
Transaction Summary:
 Installing:       11 packages
 Reinstalling:      0 packages
 Upgrading:         0 packages
 Obsoleting:        0 packages
 Removing:          0 packages
 Downgrading:       0 packages
Downloading packages...
Running transaction test...
Installing: userspace-rcu;0.10.1-4.el8;x86_64;ubi-8-baseos
Installing: kpartx;0.8.4-22.el8;x86_64;rhel-8-for-x86_64-baseos-rpms
Installing: e2fsprogs-libs;1.45.6-4.el8;x86_64;rhel-8-for-x86_64-baseos-rpms
Installing: libss;1.45.6-4.el8;x86_64;ubi-8-baseos
Installing: libaio;0.3.112-1.el8;x86_64;ubi-8-baseos
Installing: device-mapper-multipath-libs;0.8.4-22.el8;x86_64;rhel-8-for-x86_64-baseos-rpms
Installing: fuse-libs;2.9.7-15.el8;x86_64;ubi-8-baseos
Installing: e2fsprogs;1.45.6-4.el8;x86_64;rhel-8-for-x86_64-baseos-rpms
Installing: device-mapper-multipath;0.8.4-22.el8;x86_64;rhel-8-for-x86_64-baseos-rpms
Installing: xfsprogs;5.0.0-10.el8;x86_64;rhel-8-for-x86_64-baseos-rpms
Installing: which;2.21-17.el8;x86_64;ubi-8-baseos
Complete.
Complete.
--> db07c7cfefb
STEP 27: COPY --from=builder /go/src/csi-powermax/csi-powermax .
--> fd838fe3e27
STEP 28: COPY "csi-powermax/csi-powermax.sh" .
--> bb2c12f48a0
STEP 29: ENTRYPOINT ["/csi-powermax.sh"]
--> 431d735f6b8
STEP 30: FROM 486c411018c468fc1ee3a695b2e89e415621e4c651fe3bc75531b0ca331be522 AS verify
STEP 31: RUN microdnf update -y     &&     microdnf install -y e2fsprogs which xfsprogs device-mapper-multipath     &&     microdnf clean all
--> Using cache db07c7cfefbd78e47b1c06f9c64933be4aff388e718427a78a0f1e25e868bfc8
--> db07c7cfefb
STEP 32: RUN which mkfs.ext4
/usr/sbin/mkfs.ext4
--> cfa366b850c
STEP 33: RUN which mkfs.xfs
/usr/sbin/mkfs.xfs
--> f72dbdd35aa
STEP 34: FROM 431d735f6b8c1cf89bccf7af467d9d6674a2f1e5f5d63dd23747c312e62f8f41 AS trivy-others
STEP 35: ONBUILD RUN echo "Not a UBI minimal image"
--> a9a6359c86d
STEP 36: FROM 431d735f6b8c1cf89bccf7af467d9d6674a2f1e5f5d63dd23747c312e62f8f41 AS final
STEP 37: LABEL vendor="Dell Inc."       name="csi-powermax"       summary="CSI Driver for Dell PowerMax"       description="CSI Driver for provisioning persistent storage from Dell PowerMax"       version="2.5.0"       license="Apache-2.0"
--> 3b14049a9ee
STEP 38: COPY csi-powermax/licenses /licenses
STEP 39: COMMIT csi-powermax:v2.5.0.000R-501
--> 0db537a5c7d
STEP 40: FROM 431d735f6b8c1cf89bccf7af467d9d6674a2f1e5f5d63dd23747c312e62f8f41 AS trivy-ubim
STEP 41: ONBUILD RUN microdnf install -y tar
--> 7bde39016ad
0db537a5c7d839241a5b32bee907cdc3a7e377084cc0856a0219acb48317d176
STEP 1: FROM golang@sha256:244a736db4a1d2611d257e7403c729663ce2eb08d4628868f9d9ef2735496659 AS builder
Resolved "golang" as an alias (/var/cache/containers/short-name-aliases.conf)
Trying to pull docker.io/library/golang@sha256:244a736db4a1d2611d257e7403c729663ce2eb08d4628868f9d9ef2735496659...
Getting image source signatures
Copying blob sha256:c732a2540651eb09faab95b03b3b5928ab23e096fae0006bdc2abf9e0cb5bfb4
Copying blob sha256:08684ee472f39cbba2db3b665d1e96eb3ba2e634302461e4bf13aada1d7f6a7e
Copying blob sha256:aad63a9339440e7c3e1fff2b988991b9bfb81280042fa7f39a5e327023056819
Copying blob sha256:7b2225181d6bcfb7877529a7257ff207cb14e52831420f770cbc2187031b6228
Copying blob sha256:c8dae7ec6990c7bc4c11880ff4c8ad988fbb8e33b575d0c4bcb89e34e68e0624
Copying config sha256:760fdda71c8fffbf9c6cb1a6d4a461fafd72eb507a62dc61f6354bb1c98f7ec2
Writing manifest to image destination
Storing signatures
STEP 2: RUN apk update && apk add --no-cache tzdata && update-ca-certificates
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
v3.11.13-12-g2cfa91a2b4 [http://dl-cdn.alpinelinux.org/alpine/v3.11/main]
v3.11.11-124-gf2729ece5a [http://dl-cdn.alpinelinux.org/alpine/v3.11/community]
OK: 11285 distinct packages available
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
(1/1) Installing tzdata (2021e-r0)
Executing busybox-1.31.1-r9.trigger
OK: 10 MiB in 16 packages
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
--> f3dbb6458aa
STEP 3: ENV USER=revproxy
--> 1f3af191081
STEP 4: ENV UID=10001
--> 3bd9f43547e
STEP 5: RUN adduser     --disabled-password     --gecos ""     --home "/nonexistent"     --shell "/sbin/nologin"     --no-create-home     --uid "${UID}"     "${USER}"
--> e7a91beedd8
STEP 6: RUN mkdir -p /go/src/csireverseproxy
--> 3d99b3d927c
STEP 7: COPY . /go/src/csireverseproxy
--> b0b38f18118
STEP 8: WORKDIR /go/src/csireverseproxy
--> aae9ed231b7
STEP 9: RUN CGO_ENABLED=0 go build
go: downloading github.com/spf13/viper v1.7.0
go: downloading github.com/kubernetes-csi/csi-lib-utils v0.9.1
go: downloading k8s.io/client-go v0.19.0
go: downloading github.com/fsnotify/fsnotify v1.4.9
go: downloading github.com/gorilla/mux v1.7.3
go: downloading github.com/sirupsen/logrus v1.6.0
go: downloading github.com/spf13/afero v1.2.2
go: downloading github.com/spf13/cast v1.3.0
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/dell/gopowermax/v2 v2.0.0
go: downloading k8s.io/api v0.19.0
go: downloading github.com/subosito/gotenv v1.2.0
go: downloading gopkg.in/yaml.v2 v2.3.0
go: downloading github.com/magiconair/properties v1.8.1
go: downloading k8s.io/klog/v2 v2.2.0
go: downloading github.com/spf13/jwalterweatherman v1.0.0
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading golang.org/x/sys v0.1.0
go: downloading github.com/pelletier/go-toml v1.2.0
go: downloading golang.org/x/text v0.4.0
go: downloading k8s.io/apimachinery v0.19.0
go: downloading github.com/mitchellh/mapstructure v1.1.2
go: downloading golang.org/x/crypto v0.0.0-20210921155107-089bfa567519
go: downloading k8s.io/utils v0.0.0-20200729134348-d5654de09c73
go: downloading golang.org/x/oauth2 v0.0.0-20200107190931-bf48bf16ab8d
go: downloading github.com/golang/groupcache v0.0.0-20191227052852-215e87163ea7
go: downloading k8s.io/kube-openapi v0.0.0-20200805222855-6aeccd4b50c6
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading gopkg.in/ini.v1 v1.51.0
go: downloading golang.org/x/term v0.1.0
go: downloading github.com/hashicorp/golang-lru v0.5.4
go: downloading github.com/gogo/protobuf v1.3.2
go: downloading github.com/googleapis/gnostic v0.4.1
go: downloading golang.org/x/net v0.1.0
go: downloading github.com/go-logr/logr v0.2.0
go: downloading sigs.k8s.io/yaml v1.2.0
go: downloading gopkg.in/inf.v0 v0.9.1
go: downloading github.com/google/go-cmp v0.4.0
go: downloading golang.org/x/time v0.0.0-20200630173020-3af7569d3a1e
go: downloading github.com/google/gofuzz v1.1.0
go: downloading sigs.k8s.io/structured-merge-diff/v4 v4.0.1
go: downloading github.com/json-iterator/go v1.1.10
go: downloading github.com/imdario/mergo v0.3.5
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/golang/protobuf v1.4.2
go: downloading github.com/modern-go/reflect2 v1.0.1
go: downloading google.golang.org/protobuf v1.24.0
# golang.org/x/sys/unix
/go/pkg/mod/golang.org/x/sys@v0.1.0/unix/syscall.go:83:16: undefined: unsafe.Slice
/go/pkg/mod/golang.org/x/sys@v0.1.0/unix/syscall_linux.go:2255:9: undefined: unsafe.Slice
/go/pkg/mod/golang.org/x/sys@v0.1.0/unix/syscall_unix.go:118:7: undefined: unsafe.Slice
/go/pkg/mod/golang.org/x/sys@v0.1.0/unix/sysvshm_unix.go:33:7: undefined: unsafe.Slice
note: module requires Go 1.17
# golang.org/x/net/http2
/go/pkg/mod/golang.org/x/net@v0.1.0/http2/transport.go:437:45: undefined: os.ErrDeadlineExceeded
note: module requires Go 1.17
STEP 10: FROM scratch
STEP 11: LABEL vendor="Dell Inc."       name="csipowermax-reverseproxy"       summary="CSI PowerMax Reverse Proxy"       description="CSI PowerMax Reverse Proxy which helps manage connections with Unisphere for PowerMax"       version="2.4.0"       license="Apache-2.0"
Error: error building at STEP "RUN CGO_ENABLED=0 go build": error while running runtime: exit status 2

**Comment by shanmydell** [comment]
@seankhliao : Attached the full reproducer, please reopen this issue
