### ISSUE TITLE
sync: occasional panic "inconsistent mutex state" on sync.allPoolsMu

### ISSUE THREAD

**Issue by supergao222** [golang/go#56648]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.3 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
</pre></details>

### What did you expect to see?

no panic

### What did you see instead?

I encounter occasional panic "inconsistent mutex state" when server try to run sync.allPoolsMu.Lock() in pinSlow(). The panic always happens on sync.allPoolsMu, all other mutex works OK.

I collected 6 panic's coredump file, print the allPoolsMu's value using delve. And found some incredible values:
<pre>
1. sync.allPoolsMu = sync.Mutex {state: -1159398752, sema: 192}
2. sync.allPoolsMu = sync.Mutex {state: -679418736, sema: 192}
3. sync.allPoolsMu = sync.Mutex {state: -1955878282, sema: 192}
4. sync.allPoolsMu = sync.Mutex {state: 1481213382, sema: 192}
5. sync.allPoolsMu = sync.Mutex {state: -1298326986, sema: 192}
6. sync.allPoolsMu = sync.Mutex {state: -565380458, sema: 192}
</pre>

**Comment by mknyszek** [comment]
That looks like memory corruption. Do you have a way to reproduce? What happens if you run your application with the race detector?

CC @golang/runtime

**Comment by bingzhuo2008** [comment]
I have this problem too. It happens in production environment by chance, it's hard to reproduce it by pressure tests. Besides unsafe.Pointer, what other  operations may lead to memory corruption?

**Comment by satyrswang** [comment]
> That looks like memory corruption. Do you have a way to reproduce? What happens if you run your application with the race detector?
> 
> CC @golang/runtime

@mknyszek why other variables' memory corruption caused by data race can lead to the state in mutex unpredictable？

**Comment by satyrswang** [comment]
if integer overflow, or something like that, BUT there has no memory protection?

**Comment by CAFxX** [comment]
@satyrswang if your program imports unsafe, or imports packages that transitively import unsafe, or IIRC also if you use cgo, yes it is possible for memory corruption to occur even elsewhere (e.g. the mutex state). Similar effects may manifest also in presence of data races.

**Comment by mknyszek** [comment]
I think we need a way to reproduce this to move forward, otherwise we'll just be guessing. I can't think of a recent change off the top of my head that might involve mutexes in the last couple releases and memory corruption is too broad a category to try to pinpoint on any particular change in recent memory.
