### ISSUE TITLE
net: `could not determine kind of name for C.res_nclose` on linux-amd64-alpine

### ISSUE THREAD

**Issue by mknyszek** [golang/go#56657]
[Persistently failing](https://build.golang.org/log/6565acb0b3bd39e948f694e646025f179ee243e0) since https://go.dev/cl/446179.

CC @rsc @ianlancetaylor

**Comment by mknyszek** [comment]
Actually, I'm not sure if linux-amd64-alpine is first class...

**Comment by mknyszek** [comment]
There appear to be similar, related errors on [dragonfly](https://build.golang.org/log/ce16b8caf265f67c87ef2ff7ff4bf7d6a831a6ea) and [android](https://build.golang.org/log/75e489d82698a2349a33478e24a5f815c08db636) but with a different symptom (`-lresolv` related).

**Comment by rsc** [comment]
#56660 for the -lresolv issue.
