### ISSUE TITLE
net/netip: documentation: p.IP() should say p.Addr()

### ISSUE THREAD

**Issue by candlerb** [golang/go#56664]
### What version of Go are you using (`go version`)?

Any 1.18+

### Does this issue reproduce with the latest release?

N/A

### What operating system and processor architecture are you using (`go env`)?

N/A

### What did you do?

Read the documentation for net/netip package online.

https://pkg.go.dev/net/netip#AddrPort.IsValid
> "IsValid reports whether p.IP() is valid."

https://pkg.go.dev/net/netip#Prefix.IsValid
> "IsValid reports whether p.Bits() has a valid range for p.IP()"

However, neither AddrPort nor Prefix has an `IP()` method.

### What did you expect to see?

I think p.IP() should say p.Addr() in both cases

### What did you see instead?

See above

**Comment by mknyszek** [comment]
CC @neild

**Comment by AlexanderYastrebov** [comment]
This has been fixed by https://go-review.googlesource.com/c/go/+/421995
