### ISSUE TITLE
Goboring check in aws lambda function

### ISSUE THREAD

**Issue by Sanjeev3008** [golang/go#56670]
How do i verify if the goboringcrypto binary im using in the lambda function uses the goboring and boringssl function and not the standard functions??

I'm using go version - go version go1.19.3 linux/amd64 I've build a basic go application using boringcyrpto option - GOEXPERIMENT=boringcrypto

Command used to build the application - GOOS=linux GOARCH=amd64 GOEXPERIMENT=boringcrypto CGO_ENABLED=1 go build -o bootstrap hello.go

EXAMPLES:
go tool nm bootstrap > tags.txt  - gives the **_Cfunc__goboringcrypto_** , ican verify the binary uses the goboring function in local.
  4019a0 T _cgo_d3bdb93f8e25_Cfunc__goboringcrypto_AES_cbc_encrypt
  4019c0 T _cgo_d3bdb93f8e25_Cfunc__goboringcrypto_AES_ctr128_encrypt
  4019f0 T _cgo_d3bdb93f8e25_Cfunc__goboringcrypto_AES_decrypt
  401a00 T _cgo_d3bdb93f8e25_Cfunc__goboringcrypto_AES_encrypt
  401a10 T _cgo_d3bdb93f8e25_Cfunc__goboringcrypto_AES_set_decrypt_key
  401a50 T _cgo_d3bdb93f8e25_Cfunc__goboringcrypto_AES_set_encrypt_key
  401c00 T _cgo_d3bdb93f8e25_Cfunc__goboringcrypto_BN_bn2le_padded
  401c40 T _cgo_d3bdb93f8e25_Cfunc__goboringcrypto_BN_free
  
Also i checked "cat tags.txt | grep FIPS" gives FIPS functions too:
  454b90 t BORINGSSL_FIPS_abort
  403010 t FIPS_mode_set
  401cd0 T _cgo_d3bdb93f8e25_Cfunc__goboringcrypto_FIPS_mode
  403000 t _goboringcrypto_FIPS_mode
  6def00 T crypto/internal/boring._Cfunc__goboringcrypto_FIPS_mode.abi0
  bcc298 D crypto/internal/boring._cgo_d3bdb93f8e25_Cfunc__goboringcrypto_FIPS_mode
  6dccc0 T crypto/internal/boring/sig.FIPSOnly.abi0
  bcd140 D crypto/tls.defaultCipherSuitesFIPS
  bcd1c0 D crypto/tls.defaultFIPSCurvePreferences

Is there a way to check the binary im uploading to lambda uses the boring functions. I checked MD5, which usually isnt supported in FIPS mode, but go supports md5 in boring version too.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
