### ISSUE TITLE
cmd/link: link time regression for kubelet at `fix transitive inlining of generic functions`

### ISSUE THREAD

**Issue by mknyszek** [golang/go#56678]
~2% performance regression that seems to point at 9944ba757b0f8005cfb7715d41592c7e13c0a2b8.

CC @mdempsky 

The benchmark builds cmd/kubelet in the kubernetes main repo at v1.22.1: https://cs.opensource.google/go/x/benchmarks/+/master:sweet/harnesses/go-build.go;l=26

**Comment by cherrymui** [comment]
Tried to run the benchmark locally
```
name \ time/op                  go1.19      a7538d7      9944ba7           tip
GoBuildKubeletLink          10.4s ± 9%   10.1s ±10%   10.3s ± 3%    10.5s ±14%
```
(a7538d7 is the commit before 9944ba7)

There is some noise, so it hard to tell.

From the dashboard it seems it no longer regress much at tip now. https://perf.golang.org/dashboard/?benchmark=GoBuildKubeletLink&repository=go&branch=master&days=100&end=2023-01-17T00%3A03
I think we can close this for now.
