### ISSUE TITLE
cmd/link: crash on custom scenario

### ISSUE THREAD

**Issue by aviramha** [golang/go#56685]
### What version of Go are you using (`go version`)?
go version go1.19.2 linux/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/azureuser/.cache/go-build"
GOENV="/home/azureuser/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/azureuser/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/azureuser/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/azureuser/aviram/going/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/azureuser/aviram/going/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.3"
GCCGO="/usr/bin/gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/azureuser/aviram/going/go-detour/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3760260815=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I tried to create a c-archive that links to Go symbols used by it in runtime, instead of including the whole runtime/go stdlib.
This happens even on the simple program:
```go
package main
func main() {
}
```
Then compile steps:
`go tool compile -shared -dynlink main.go`
^^ This creates a file that seems correct.
`go tool link -buildmode=c-archive -extld clang -extldflags='-undefined dynamic_lookup' -w -installsuffix /tmp -o main.a main.o`

### What did you expect to see?
Output fail `main.a` includes only wanted functions, which I can further link later on to a binary.

### What did you see instead?
```
warning: unable to find runtime.a
warning: unable to find runtime/cgo.a
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
cmd/link/internal/ld.(*Link).findfunctab(0xc0000fc000?, 0x67ec63?, {0xc0000183b0?, 0x14?, 0xc0000e0095?})
 /usr/local/go/src/cmd/link/internal/ld/pcln.go:827 +0x28f
cmd/link/internal/ld.Main(_, {0x20, 0x20, 0x1, 0x7, 0x10, 0x0, {0x0, 0x0}, {0x6886d9, ...}, ...})
 /usr/local/go/src/cmd/link/internal/ld/main.go:330 +0x133e
main.main()
 /usr/local/go/src/cmd/link/main.go:72 +0x1145
```

**Comment by ianlancetaylor** [comment]
Well, it shouldn't crash, but you will still get errors.  Using `go tool compile` and `go tool link` directly is unlikely to ever work.  You need to use things like `go build -ldflags`.

In general what you are trying to do is not supported and I would be surprised if it works at all.  But sometimes I am surprised.

**Comment by cherrymui** [comment]
> go tool compile -shared -dynlink main.go

If you want to create a c-archive, I think you don't want to pass the -dynlink flag.

> Output fail main.a includes only wanted functions, which I can further link later on to a binary.

I'm not sure I understand this. Are you expecting the linker to fail?
