### ISSUE TITLE
spec: `append` doesn't specify zero values when growing underlying array

### ISSUE THREAD

**Issue by griesemer** [golang/go#56684]
When `append` is called on a slice and the underlying array is not large enough, a new underlying array is allocated, possibly increasing the slice's capacity significantly (typically doubling it). The spec doesn't specify the value of any slice elements past the slice length and up to the capacity.

**Comment by zephyrtronium** [comment]
I noticed also that the spec doesn't actually say `append` *will* allocate an underlying array larger than strictly necessary. All it says is "a new, sufficiently large underlying array that fits both the existing slice elements and the additional values." It doesn't specify the values of extra elements because it doesn't specify that there may be extra elements.

**Comment by griesemer** [comment]
Yes, that part is on purpose - we don't want to be too specific and constrain an implementation. But we should probably say that the array may possibly larger.

**Comment by dsnet** [comment]
Related to #56086?

**Comment by dsnet** [comment]
When I was thinking about #56086, I came across this issue, and I think the Go spec does guarantee it.

[Appending to and copying slices](https://go.dev/ref/spec#Appending_and_copying_slices) says:
> If the capacity of s is not large enough to fit the additional values, **append allocates** a new, sufficiently large underlying array

[The zero value](https://go.dev/ref/spec#The_zero_value) says:
> When storage is allocated for a [variable](https://go.dev/ref/spec#Variables), either through a declaration or a call of new, or when a new value is created, either through a composite literal or a call of make, and no explicit initialization is provided, the variable or value is given a default value. Each element of such a variable or value is set to the zero value for its type.

I interpreted the list in "the zero value" section as non-exhaustive and that allocations from `append` fell under this category.

**Comment by griesemer** [comment]
@dsnet I agree. The thought occurred to me as well, afterwards. Perhaps all that's needed to make this more explicit is making "allocates" link to the appropriate section.
