### ISSUE TITLE
encoding/gob: unable to encode constant.Value with default encoder

### ISSUE THREAD

**Issue by JamesRTaylor** [golang/go#56696]
### What version of Go are you using (`go version`)?
go1.18.3

### Does this issue reproduce with the latest release?
Unknown

### What operating system and processor architecture are you using (`go env`)?
darwin/arm64

### What did you do?

type ConstantValue struct {
	Value constant.Value
}

func EnocdeDecodeRoundtrip(value ConstantValue) {
	var b bytes.Buffer
	e := gob.NewEncoder(&b)
	if err := e.Encode(&value); err != nil {
		panic(err)
	}
	var decodedValue ConstantValue
	d := gob.NewDecoder(&b)
	if err := d.Decode(&decodedValue); err != nil {
		panic(err)
	}
	if value.Value.ExactString() != decodedValue.Value.ExactString() {
		err := fmt.Errorf("Decoded value not the same as original. Expected %s, but got %s",
			value.Value.ExactString(), decodedValue.Value.ExactString())
		panic(err)
	}
}

func TestConstantValueGobEncoding(t *testing.T) {
	field := ConstantValue{constant.Make(int64(1))}
	EnocdeDecodeRoundtrip(field)
}

### What did you expect to see?
Expected to be able to encode and decode constant.Value

### What did you see instead?
panic: gob: type not registered for interface: constant.int64Val

### Workaround
I'm able to workaround the issue by creating a custom encoder, but it's a bit painful

**Comment by robpike** [comment]
Your snippet is not complete. For example, there is no definition for ConstantValue.
Please provide a self-contained executable example to demonstrate the problem.

**Comment by JamesRTaylor** [comment]
Sorry about that, @robpike. I've added the struct definition.

**Comment by seankhliao** [comment]
See https://pkg.go.dev/encoding/gob#Register

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by seankhliao** [comment]
https://go.dev/play/p/bJP9C7YhEV_9

**Comment by JamesRTaylor** [comment]
https://go.dev/play/p/_13x4HBB6nZ

**Comment by JamesRTaylor** [comment]
@seankhliao - did you see my example? Just curious if you've closed this issue as "gob encode/decode of `constant.Value` isn't supported" or if you're theorizing that it works? Without writing custom encoding/decoding methods for anything that contains a `constant.Value`, I'm not able to get it to work.
