### ISSUE TITLE
net: reenable TestLookupDotsWithRemoteSource and TestLookupGoogleSRV with a different target

### ISSUE THREAD

**Issue by mknyszek** [golang/go#56708]
Due to #56707 these tests were disabled. This issue tracks reenabling them with a different DNS target that works.

CC @neild

**Comment by mateusz834** [comment]
We might use now email SRVs like: `_submission._tcp.gmail.com`

**Comment by mknyszek** [comment]
@gopherbot Please open backport a backport issue for Go 1.18 and Go 1.19 since the same workaround and test skips were applied there.

**Comment by cherrymui** [comment]
It is not a release blocker, but would be good to be done soon-ish. Thanks.
