### ISSUE TITLE
affected/package: fmt

### ISSUE THREAD

**Issue by sandeepkalra** [golang/go#56713]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.19.3
</pre>

### Does this issue reproduce with the latest release?
I have checked with only official go1.19.3

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
O111MODULE=""
GOARCH="amd64"
GOBIN="/home/bpadmin/go/bin"
GOCACHE="/home/bpadmin/.cache/go-build"
GOENV="/home/bpadmin/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/bpadmin/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/bpadmin/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/bpadmin/repos/sankalra/chetak.git/src/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build419792306=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

included multiple build tags in code so that build compilation can happen for multiple platforms
I build code for more than 1 OS - say linux and darwin. I have code that is sometimes debug only, and they can be different based on tag set "production, linux" , "production,darwin", "production", "linux", etc

in go code, I have 
// +build tag1, tag2

also tried
// +build tag1, tag2
and 
// +build tag1
// +build tag2

the build works. But when automating, I run "go fmt" and "golint" etc, and found that "go fmt" removes tag2 and onwards.

### What did you expect to see?

go fmt must work with multiple tags

### What did you see instead?

go fmt is breaking my automation build

**Comment by seankhliao** [comment]
This isn't reproducible.

**Comment by sandeepkalra** [comment]
sorry, it is sorted out. Not a bug!
