### ISSUE TITLE
affected/package: encoding/json + type error between Floats & Int.

### ISSUE THREAD

**Issue by Tang8330** [golang/go#56719]
### What version of Go are you using (`go version`)?

<pre>
$ go version
# go1.19

</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

Floats and Integers are not properly marshalled via `encoding/json`. There is no distinction between `7` vs. `7.00` this is causing issues with `encoding/json` since the output is just `7` and when checking the type via `val.(type)`, it all defaults to a `Float`.

I have it repro'ed here: https://go.dev/play/p/lwxgCWH-ReP

### What did you expect to see?

I expect `encoding/json` and `types` understands the difference between Int and Float.

### What did you see instead?

Both just get casted as `7` and when checking the type, it's a `Float`.

**Comment by ZekeLu** [comment]
[RFC 8259](https://www.rfc-editor.org/rfc/rfc8259#section-3):

> A JSON value MUST be an object, array, number, or string, or one of  the following three literal names:
> - false
> - null
> - true

There is only **number**, but not **int** or **float** in JSON.

If you run the following javascript snippet:

```js
var v = {
  a: 7,
  b: 7.0,
};

JSON.stringify(v);
```

You will get

```json
{
  "a": 7,
  "b": 7
}
```

Instead of

```
{
  "a": 7,
  "b": 7.0
}
```

**Comment by Tang8330** [comment]
Ah, I see! Thanks for the context. Is there not an amendment? Or frameworks that allow us to work through this constraint?

**Comment by seankhliao** [comment]
nope. this is json working as intended.
