### ISSUE TITLE
proposal: patch-level for releases & go.mod

### ISSUE THREAD

**Issue by jfrog-tamirb** [golang/go#56723]
We recently ran `govulncheck` and saw that our package was vulnerable to a CVE. 
Since the CVE was in Go's standard library, we needed to upgrade our installation of Go, which we did.
But, unlike with other packages - we could not update our `go.mod` file to ensure the code is not vulnerable.
The `go` directive in `go.mod` only allows requiring release versions of Go (so `1.18` or `1.19`),
but not minor revisions containing critical bugfixes.
This means that the only way to communicate this requirement to users of our package is via documentation, which is hardly sufficient, as they might not even know our package is a dependency.

We propose adding another data field to both Go releases and `go.mod` - a **patch level**.
The **patch level** would be shared across release versions of Go, indicating the bugfixes applied to each version.
A possible way to indicate it could be the release data of a patch, so that in case of existing revisions:

| Go Version | Patch Level |
| ---------- | ----------- |
| 1.18       | 2022-03-15  |
| 1.18.5     | 2022-08-01  |
| 1.18.6     | 2022-09-06  |
| 1.19       | 2022-08-02  |
| 1.19.1     | 2022-09-06  |

So by indicating `patch 2022-09-06` in the `go.mod` file,
a package indicates that it requires `1.18.6` or `1.19.1` or any later release.
This goes hand-in-hand with a `go 1.18` directive indicating that the minimal version of Go required to compile the code is `1.18`.

Additionally, this will also allow automated tooling to check against Go CVEs from source-code alone, 
without requiring a Go installation.

**Comment by seankhliao** [comment]
Duplicate of #55092

Note that right now, `go` directive in `go.mod` is not a hard requirement of any version of the toolchain.
