### ISSUE TITLE
affected/package:  strings

### ISSUE THREAD

**Issue by huiqqq** [golang/go#56739]
### What version of Go are you using (`go version`)?     
GO1.19

<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
set GOVERSION=go1.19
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

link:   https://go.dev/play/p/f9aHqt7Ryh0

fileName := "14-010-Zirk10000-1116675.A53"
fmt.Println(strings.Trim(fileName, filepath.Ext(fileName)))      //14-010-Zirk10000-111667？
fmt.Println(strings.TrimRight(fileName, filepath.Ext(fileName))) //14-010-Zirk10000-111667？

### What did you expect to see?
14-010-Zirk10000-1116675

### What did you see instead?
14-010-Zirk10000-111667

**Comment by mvdan** [comment]
You want TrimSuffix, not TrimRight.

The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.
