### ISSUE TITLE
hook for routine life cycle:  is there any way to hook before create routine and after its dead

### ISSUE THREAD

**Issue by fengyeall111** [golang/go#56738]
we create routine like this: 
```
go func(){
}
```
after routine has done its work, goexit1() will be called and its status bencome runtime_dead.
is there any way to insert some code fragment before run "goexit1()"
If go language have some hooks In go routine lifecycle, thread local sotrage for go becomes easy,“async await” features that many other lanuages have  may be achieved 
```
// javascript
async func test0(){
}
async fun test1(){
   var res = await test0()
}
```

**Comment by ianlancetaylor** [comment]
No, there are no such hooks, and there are no plans for any such hooks.

In general we don't use the issue tracker for questions.  See https://go.dev/wiki/Questions.  Thanks.
