### ISSUE TITLE
cmd/6c: incorrect code for large immediate address

### ISSUE THREAD

**Issue by dvyukov** [golang/go#5673]
<pre>parent: 17021:8257d3f823ee tip, linux/amd64
6c generated incorrect code for the following function -- the constant silently
disappears:

int32 foobar(int32 i)
{
        return ((int32*)0xc000000000ull)[i];
  418f50:       8b 44 24 08             mov    0x8(%rsp),%eax
  418f54:       48 63 c0                movslq %eax,%rax
  418f57:       48 c1 e0 02             shl    $0x2,%rax
  418f5b:       8b 00                   mov    (%rax),%eax
  418f5d:       c3                      retq   
}

Such code may be useful in GC, since arena_start/arena_end/spans are usually known large
addresses.</pre>

**Comment by rsc** [comment]
6c is gone!
