### ISSUE TITLE
x/pkgsite: Invalid content of an example that contains a block comment

### ISSUE THREAD

**Issue by pellared** [golang/go#56762]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/goyek/goyek/v2#example-package
 
### What is your user agent?
 
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
 
### Screenshot
 
<img width="250" alt="image" src="https://user-images.githubusercontent.com/5067549/202200340-8d1cfa6e-80ff-4203-b8e2-27a53a4e5890.png">
 
<img width="154" alt="image" src="https://user-images.githubusercontent.com/5067549/202201210-e169c42a-341f-494e-84a8-027f19f20f96.png">

### What did you do?
 
I have an example test like this: 
 
https://github.com/goyek/goyek/blob/v2.0.0-rc.11/example_test.go 

### What did you expect to see?
 
Proper content taken from the example.

### What did you see instead?

The example has a strange ending. The `*/` is duplicated together with some other symbols.

**Comment by enstenr** [comment]
I can also see that extra 
closing comment symbol at tail end.
