### ISSUE TITLE
x/net/http2: spec violation 6.5.3

### ISSUE THREAD

**Issue by Duslia** [golang/go#56760]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.19
</pre>

### Does this issue reproduce with the latest release?
No

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

I run HTTP2 spec test and there are four tests that cannot be passed.
spec test repo: https://github.com/summerwind/h2spec
command: ./h2spec -p 8888 -k -t -v http2

### What did you expect to see?
all the tests passed

### What did you see instead?
<img width="821" alt="image" src="https://user-images.githubusercontent.com/37136584/202179949-65ca9ca9-e69a-4416-8708-8b2d132bef25.png">

test code:
```

func main() {
	server := &http.Server{
		Addr:         ":8888",
		ReadTimeout:  5 * time.Second,
		WriteTimeout: 10 * time.Second,
	}

	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte(fmt.Sprintf("Protocol: %s", r.Proto)))
	})

	if err := server.ListenAndServeTLS("./examples/tls/server.crt", "./examples/tls/server.key"); err != nil {
		log.Fatal(err)
	}
}

```

**Comment by Duslia** [comment]
> 4.2 was deemed incorrect: [#25023 (comment)](https://github.com/golang/go/issues/25023#issuecomment-404017052) 8.1.2.2 is #26321
> 
> 6.5.3 seems to be a new failure?
> 
> cc @neild @tombergan

@seankhliao These pr cause 6.5.3 failure: https://go-review.googlesource.com/c/net/+/124735. It seems that it's expected.

**Comment by seankhliao** [comment]
In that case there seems to be nothing new here not tracked in other issues.
