### ISSUE TITLE
x/vuln: skip one line of code

### ISSUE THREAD

**Issue by sten4eg** [golang/go#56767]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.3 linux/amd64
</pre>

How Can I skip one line of code, In my project I use `go:embed` file but on CI/CD stage this file is doesn’t exist in my project and Vuln reports me about an error `middleware/checkJWT.go:28:12: pattern public.pem: no matching files found.` Many linters have a function to read comments
like `//linter:skip`  to skip next line.
Is it possible to add the same functionality to Vuln?

**Comment by seankhliao** [comment]
isn't it a build error to not have a listed file for `//go:embed` ?

**Comment by sten4eg** [comment]
@seankhliao Yes. Sorry my bad
