### ISSUE TITLE
Implement godoc version command. affected/package: golang.org/x/tools

### ISSUE THREAD

**Issue by haraldrudell** [golang/go#56772]
* in macOS brew there are sometimes troublemas with ugrading godoc
* godoc does not have **godoc version** command
* the godoc version may be from some stale package lacking generics parsing abaility

How can version be found presently?
* In the footer of every generated go documentation page: “Build version go1.19.3.”
* `strings ~/go/bin/godoc | egrep ^go1`: “go1.19.3”
* `go version -m ~/go/bin/godoc`: “~/go/bin/godoc: go1.19.3…”

How can godoc be rebuilt?
`go install golang.org/x/tools/cmd/godoc@latest`

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.3 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""                                                                                                            
GOARCH="arm64"                                                                                                            
GOBIN=""                                                                                                                  
GOCACHE="/var/root/Library/Caches/go-build"                                                                               
GOENV="/var/root/Library/Application Support/go/env"                                                                      
GOEXE=""                                                                                                                  
GOEXPERIMENT=""                                                                                                           
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/var/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/var/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.19.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.19.3/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4204179306=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

<pre>
git clone https://github.com/haraldrudell/parl.git
cd parl
godoc -http=localhost:6063
2022/11/16 12:22:18 /src/github.com/haraldrudell/parl/closable-chan.go:25:21: expected ']', found any (and 1 more errors)
</pre>

### What did you expect to see?

No errors and an available Go documentation page generated

### What did you see instead?

Corrupt Go documentation page: /src/github.com/haraldrudell/parl/closable-chan.go:25:21: expected ']', found any (and 1 more errors)

**Comment by seankhliao** [comment]
godoc has been deprecated as of #49212
