### ISSUE TITLE
affected/package: crypto/x509, crypto/x509/pkix, encoding/asn1

### ISSUE THREAD

**Issue by Atul-Mundlik** [golang/go#56779]
### What version of Go are you using (`go version`)?

<pre>
$ go version  go1.18.4 

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
darwin/arm64

### What did you do?

I am creating x509 certificate.
below is the play url
https://go.dev/play/p/hRSlYhoh-Rx

when i parse the generated certificate using asn1parse -in <PathToPemFile>

I can see the common name as PRINTABLESTRING instead if UTF8STRING.

as I understand, in golang the string is default utf8 then why PRINTABLESTRING instead if UTF8STRING?

Also,
when I put some characters like é um then I can see UTF8STRING

### What did you expect to see?
   31:d=4  hl=2 l=  13 cons: SEQUENCE          
   33:d=5  hl=2 l=   3 prim: OBJECT            :commonName
   38:d=5  hl=2 l=   6 prim: UTF8STRING   :golang

### What did you see instead?
   31:d=4  hl=2 l=  13 cons: SEQUENCE          
   33:d=5  hl=2 l=   3 prim: OBJECT            :commonName
   38:d=5  hl=2 l=   6 prim: PRINTABLESTRING   :golang

**Comment by seankhliao** [comment]
see [CL 6348074](https://go.dev/cl/6348074)

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by Atul-Mundlik** [comment]
Well it is not sort of a question of how to do that but more like the values are getting stored with incorrect type in the certificate. 
Its moreover a contradiction to what golang claims about strings vs how it is getting stored/treated
