### ISSUE TITLE
x/tools/cmd/cover: isolate, tag, and delete package

### ISSUE THREAD

**Issue by bcmills** [golang/go#56783]
The [documentation](https://cs.opensource.google/go/x/tools/+/refs/tags/v0.3.0:cmd/cover/doc.go;l=9-10;drc=5fef6fdaed6f1d9428caf7126087ec67105ab1df) for `x/tools/cmd/cover` says:
> Deprecated: For Go releases 1.5 and later, this tool lives in the standard repository. The code here is not maintained.

I count 11 CLs updating the package since that notice was first added in [CL 9539](https://go.dev/cl/9539).
Keeping the code around clearly isn't doing anyone any good — at the very least, it adds noise in `git grep` results (which is how I came to notice it in the first place).

I propose that we give it the same treatment as `x/exp/winfsnotify`: carve it out into a nested module, tag that module `cmd/cover/v0.1.0-deprecated`, and then delete it from the `x/tools` repo at HEAD.

**Comment by rsc** [comment]
No change in consensus, so **[accepted](https://go.dev/s/proposal-status#accepted)**. 🎉
This issue now tracks the work of implementing the proposal.
— rsc for the proposal review group
