### ISSUE TITLE
pprof: strange pprof heap flamegraph 

### ISSUE THREAD

**Issue by Cluas** [golang/go#56782]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.3 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN="/Users/cluas/go/bin"
GOCACHE="/Users/cluas/Library/Caches/go-build"
GOENV="/Users/cluas/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE="git.5th.im/*"
GOMODCACHE="/Users/cluas/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/cluas/go"
GOPRIVATE=""
GOPROXY=""
GOROOT="/opt/homebrew/Cellar/go/1.19.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.19.3/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/gq/88dv0f_d45x_90p9s6_471g00000gn/T/go-build2351336244=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

What this service does is basically grab its own pprof info and write it to clickhouse. The heap memory flamegraph data that I download either manually or from the service itself doesn't feel very accurate. emm.. a lot of `untime.doInit`?

### What did you expect to see?

Hierarchical heap pprof flamegraph

### What did you see instead?
<img width="1795" alt="image" src="https://user-images.githubusercontent.com/10056928/202477255-0f3afbb4-2ec2-4904-8f4b-96a5968bd4a7.png">

This is the pprof heap file.
[heap.gz](https://github.com/golang/go/files/10032639/heap.gz)

**Comment by seankhliao** [comment]
Without knowing what your program does or how it's written, it's hard to tell what an in use heap profile should look like.
Here it looks pretty normal, maybe taken near startup without a lot of application code using memory, with the space eventually attributed to user code.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
