### ISSUE TITLE
encoding/json: set key converter on en/decoder

### ISSUE THREAD

**Issue by eaigner** [golang/go#5680]
<pre>Instead of having to specify `json:&quot;lowercase_field&quot;` or similar on every
struct field, the JSON en/decoder could have a

    SetKeyConverter(c KeyConverter)

method. The KeyConverter would be responsible for converting struct/map keys to JSON
keys and vice versa.

    type KeyConverter interface {
        EncodeKey(key string) string
        DecodeKey(key string) string
    }

This would be much less intrusive into type declarations, and generating a different
JSON output would simply be a matter of using another KeyConverter instead of a whole
new struct.</pre>

**Comment by bradfitz** [comment]
Sorry, the json package is pretty frozen at this point. We need to stop accreting features and options.

Everything will be up for reconsideration if/when we do Go 2, though.
