### ISSUE TITLE
x/pkgsite: package removal request for panther

### ISSUE THREAD

**Issue by fgeronimo-panther** [golang/go#56824]
### What is the path of the package that you would like to have removed?

https://pkg.go.dev/github.com/panther-labs/panther#section-readme
 
### Are you the owner of this package?

I am not. How do I find this out?

### What is the reason that you could not retract this package instead?

Panther is no longer open source and this documentation is outdated.

**Comment by seankhliao** [comment]
the old versions are still available as open source software, if people want to use that, documentation should still be available.
if the module owner wants to hide the documentation, it'd be up to them to request it.
