### ISSUE TITLE
proposal: affected/package: 

### ISSUE THREAD

**Issue by WhipMe** [golang/go#56832]
Dear Golang Management and Developers,
I am a legacy programmer (C, Pascal, Visual Basic, FoxPro, Delphi), and this is a first time that I have reached out to consider other programming languages. Golang seems to be the right fit for me at the moment. I did find learning this language irksome in some respects, because many of the typical programming conventions which we take for granted seemed to be broken.

As I have started my journey in mastering Golang, I have been working with Command Line functions. I have noticed that
Golang seems incapable of clearing a Command Line. 

For example: If one writes fmt.Print(">\r") to the Command Line, instead of the line being cleared, so that the character ">" can be put at the beginning of the line, it is usually "appended" to whatever is written, unless the ">" character is already existent at the beginning of the line. 

However, if a different character is printed to the same line, such as, "<". This different character will only be appended, so that what we will see will be - hypothetically: "><".

I am hoping and proposing that Golang will resolve this problem, issue or lack of functionality.

**Comment by seankhliao** [comment]
`\r` is an escape sequence that needs to be interpreted by your terminal. This is not something handled by Go.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
