### ISSUE TITLE
x/pkgsite: package removal request for github.com/SherlockGy/my_go_utils_test

### ISSUE THREAD

**Issue by SherlockGy** [golang/go#56847]
### What is the path of the package that you would like to have removed?
https://pkg.go.dev/github.com/SherlockGy/my_go_utils_test@v0.1.1

 
 
 
### Are you the owner of this package?

yes
 
### What is the reason that you could not retract this package instead?

github repo was deleted

**Comment by jamalc** [comment]
Done.
