### ISSUE TITLE
bytes/buffer: Strange condition

### ISSUE THREAD

**Issue by benjish** [golang/go#56846]
This condition seems strange to me
https://github.com/golang/go/blob/e84ce0802dac6d5a780acc2f54113b55f49f4b07/src/bytes/buffer.go#L138-L139
I think it should be
`c > maxInt-n`

**Comment by seankhliao** [comment]
It makes sense if you look at what growSlice does, or look at the change that introduced it.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by benjish** [comment]
Knowing that:
**c** represents the current capacity of the slice
**maxInt** the maximum size of a slice
**n** is the growth increment

the condition should be either `c > maxInt-n` or `maxInt-c-n < 0`

but `c > maxInt-c-n` means that the actual max size of the slice is `maxInt / 2`

It has no practical consequences on a 64bit system, but it's still a mistake, or an unnecessary complexity if the effective max size of a slice is `maxInt / 2`.
