### ISSUE TITLE
spec: the identity of instantiated types is not well defined

### ISSUE THREAD

**Issue by go101** [golang/go#56850]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```Go
package main

type G[T any] struct {}

func main() {
	var x, y, z any = G[int]{}, G[int]{}, G[bool]{}
	println(x == y) // true
	println(x == z) // false
}
```

The result might be not unexpected (some unexpected for me, as I think `x == z` should also result in `true`), but the current spec is not very clear on this:

> Instantiating a type results in a new non-generic named type;

People may think the types of `x` and `y` are different by this description.

**Comment by blackgreen100** [comment]
There's also [Type identity](https://go.dev/ref/spec#Type_identity)

> Two [instantiated](https://go.dev/ref/spec#Instantiations) types are identical if their defined types and all type arguments are identical.

**Comment by go101** [comment]
Didn't notice that line.

Thanks. Closed.
