### ISSUE TITLE
cmd/compile: further failures relating to CL 450136 (inlined static initializer optimization)

### ISSUE THREAD

**Issue by mdempsky** [golang/go#56894]
Google-internal toolchain testing is hitting further failures relating to [CL 450136](https://go.dev/cl/450136) (internal tracking reference: b/260007024).

I think we should at least move the static-init optimization behind a compiler flag and disable it for now while we minimize the failure cases.

**Comment by cuonglm** [comment]
Could you share the stack trace with confidential information stripped?

**Comment by mdempsky** [comment]
> Could you share the stack trace with confidential information stripped?

At least the first case I looked at was a runtime test failure, not an ICE, so there's nothing useful to report yet without minimizing the failure.

**Comment by mdempsky** [comment]
After further testing, the failures in question appear unrelated to this. At least some of the failures were probably actually fixed by CL 452616, and misattributed due to build failures interfering with bisection. See Russ's commit message in go.dev/cl/452817 for further explanation.
