### ISSUE TITLE
plugin: document that the package is not recommended

### ISSUE THREAD

**Issue by marwan-at-work** [golang/go#56893]
Hi there,

Almost every informal conversation I have with a member of the Go team about the `plugin` package, they tell me to stay away from it for various reasons. 

However, the package docs don't mention anything about that: https://pkg.go.dev/plugin

There are  projects in the open source that use plugins as a measure of extensibility such as [tyk](https://github.com/TykTechnologies/tyk). 

Therefore, we should really document that the package should just not be used in any serious/production environments if what I've heard in the past about the plugin package still applies. 

Furthermore, it would be great to document what are the reasons/concerns to making the plugin package not production-ready and maybe eventually resolve that as it certainly can be helpful. 

cc: @bcmills @alandonovan and @ianthehat from a few conversations in the past :)

**Comment by adonovan** [comment]
Hi Marwan! I agree it would be a good idea to write down the technical problems it creates (as well as those it solves) so that users can make an informed decision.
