### ISSUE TITLE
x/pkgsite: Are you considering providing the ability to manage your own package versions and subscription packages

### ISSUE THREAD

**Issue by SherlockGy** [golang/go#56898]
### What is the URL of the page with the issue?
https://pkg.go.dev/

### What is your user agent?

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36

### What did you do?

Are you considering providing the ability to manage your own package  versions (For example to remove the package) 
and subscription packages

**Comment by seankhliao** [comment]
what do you mean by "subscription packages"?

**Comment by SherlockGy** [comment]
similar to this :
https://crates.io/crates/anyhow/reverse_dependencies
https://crates.io/dashboard

![image](https://user-images.githubusercontent.com/29522658/203262828-2ee53d58-49b1-4845-851b-614f50b18a06.png)

![image](https://user-images.githubusercontent.com/29522658/203262960-cc2f9e38-dba2-4dae-a5a0-486875a86cca.png)

**Comment by seankhliao** [comment]
Package removal should be done via retractions.
We do show a list of your consumer packages, but we have no plans on having download counts (which are not done via pkgsite and heavily skewed by caching). See also #41805
