### ISSUE TITLE
cmd: vendor x/tools to 3b9d20c52192 [freeze exception]

### ISSUE THREAD

**Issue by timothy-king** [golang/go#56890]
https://github.com/orgs/golang/teams/release, may we have a freeze exception to land [CL 452615](http://go.dev/cl/c/go/+/452615). This fixed https://go.dev/issue/16520. It is going to miss the freeze by about an hour. This lands [CL 452155](http://go.dev/cl/c/tools/+/452155) which was reviewed and made it to x/tools before the freeze. We are trying to prevent 452155 from being vendored with x/tools later in the middle of the freeze cycle.

**Comment by heschi** [comment]
Doesn't need an exception, or really doesn't need to be done at all: we're going to vendor in dependencies soon as part of #36905 anyway. But since you've already got the CL ready feel free to submit it.

**Comment by timothy-king** [comment]
Thank you.
