### ISSUE TITLE
encoding/csv: field split fails when a field ends with two double quotes (... ,"field"", ...) and won't recognize next delimiter

### ISSUE THREAD

**Issue by fvha** [golang/go#56903]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.3 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=auto
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\name\AppData\Local\go-build
set GOENV=C:\Users\name\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\name\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\name\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.19.3
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\name\AppData\Local\Temp\go-build4287909446=/tmp/go-build -gno-record-gcc-switches    

</pre></details>

### What did you do?
  csvReader := csv.NewReader(f)
  csvReader.LazyQuotes = true
  records, err := csvReader.ReadAll()

Input row: "field1","field2"","field3"

### What did you expect to see?
[field1 field2" field3]

### What did you see instead?
[field1 field2","field3]

**Comment by seankhliao** [comment]
Working as intended, see also #56329
