### ISSUE TITLE
x/build: shard `linux-amd64-longtest-race` and `windows-amd64-longtest-newcc` SlowBots

### ISSUE THREAD

**Issue by bcmills** [golang/go#56907]
In #37439 we set `numTryTestHelpers` for the `-longtest` builders in order to speed them up when run as SlowBots.

Since that time, we have added two new `-longtest` builders: `windows-amd64-longtest-newcc` and `linux-amd64-longtest-race`. Those should also be sharded, for the same reason.

**Comment by heschi** [comment]
cc @thanm @mknyszek since they added the two builders. @cherrymui, can you take a look as on duty?
