### ISSUE TITLE
x/tools/go/pointer: sound models of `sync/atomic` `Pointer[T]` and `Value`

### ISSUE THREAD

**Issue by BarrensZeppelin** [golang/go#56918]
It would be nice to have sound pointer analysis models of the atomic primitives that contain pointers.
Currently the pointer analysis unsoundly ignores their use.

A failing test pointer analysis test `go/pointer/testdata/atomic_value.go` could be:

```go
//go:build ignore
// +build ignore

package main

import "sync/atomic"

var g1 int

func main() {
	var v atomic.Value
	print(v.Load()) // @types
	v.Store(&g1)
	x := v.Load().(*int)
        // Fails because the points-to set of x is empty.
	print(x) // @pointsto command-line-arguments.g1
}
```

**Comment by cherrymui** [comment]
cc @timothy-king @zpavlinovic @golang/tools-team

**Comment by timothy-king** [comment]
`sync.atomic.{Pointer[T],Value}` are implemented using `unsafe.Pointer` internally ([Pointer](https://cs.opensource.google/go/go/+/refs/tags/go1.19.3:src/sync/atomic/type.go;l=41) and [Value.Store](https://cs.opensource.google/go/go/+/refs/tags/go1.19.3:src/sync/atomic/value.go;l=51-52) code). This is a documented soundness limitation of the `pointer` package ([doc](https://cs.opensource.google/go/x/tools/+/master:go/pointer/doc.go;l=55-60;drc=36a5c6a8a6d3dc45fbccd63e2fb38ef6911f33ce)). This is consistent with the points to set of x being empty.

This can be resolved by modeling the both as intrinsics in go/pointer/intrinsics.go. Work on this is  currently unplanned by the Go team. This is a good opportunity for a community contribution.

**Comment by BarrensZeppelin** [comment]
Yeah, I think the correct thing to do is to model the behaviour with intrinsics.

The semantics are conceptually simple to model, for example in `(av *atomic.Value).Store(x any)` the value of the argument flows to the struct field `av.v`. However, implementing this seems to require strong knowledge of the internals of the pointer analysis, which I currently lack. Otherwise I would've been glad to contribute the models myself. :slightly_smiling_face:

**Comment by danvolchek** [comment]
I'd like to work on this - I'll give it a shot!

**Comment by adonovan** [comment]
x/tools/go/pointer was deleted; see #59676.
