### ISSUE TITLE
runtime/msan: go test -msan sporadically produces segmentation fault error

### ISSUE THREAD

**Issue by alimertkoc** [golang/go#56915]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.18.5
</pre>

### gcc version
`gcc (Debian 8.3.0-6) 8.3.0`

### clang version
```clang version 7.0.1-8+deb10u2 (tags/RELEASE_701/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

### Does this issue reproduce with the latest release?
Sorry, I can not reproduce locally myself. But it occurs frequently on product environment.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4002285683=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
When I execute `go test -msan` as a stage of my pipeline, it sporadically produces "segmentation fault" error and make stage failed. When I spam retry like 3-5 times, then it produces no error and stage can pass in my Gitlab pipeline. 

### What did you expect to see?
See memory sanitizer test successful.

### What did you see instead?
```
Running memory sanitizer...
go: downloading github.com/stretchr/testify v1.6.1
go: downloading gopkg.in/yaml.v3 v3.0.0-20200313102051-9f266ea9e77c
go: downloading github.com/davecgh/go-spew v1.1.0
go: downloading github.com/pmezard/go-difflib v1.0.0
?   	ali-mert/ali/ali [no test files]
signal: segmentation fault (core dumped)
FAIL	ali-mert/ali-client	0.160s
ok  	ali-mert/ali-mert-code 0.043s
FAIL
make: *** [Makefile:52: msan] Error 1
```

**Comment by alimertkoc** [comment]
@seankhliao which informations I need to provide?

**Comment by seankhliao** [comment]
code / environment to reproduce this, pointing to issues within the go runtime rather than user code, otherwise there's little we can do here
