### ISSUE TITLE
About Go 1.18 new feature: GeniericType

### ISSUE THREAD

**Issue by enddeadroyal** [golang/go#56928]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.4 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
below the code, compile is failed
error message is:
`*Foo does not implement []any|*any`

I guest that *Foo need not implement []any|*any`. this is only type constraints.
why happened,please help me!!!

```go
type Foo struct {}

type Optional[T []any | *any] interface {
	IsNil() bool
	Value() T
	Unwrap() T
}

type emptyValue[T []any | *any] struct {
	t T
}

func (ev *emptyValue[T]) IsNil() bool {
	return ev.t == nil
}

func (ev *emptyValue[T]) Value() T {
	return ev.t
}

func (ev *emptyValue[T]) Unwrap() T {
	return ev.t
}

func NonNullWrap[T []any | *any](t T) Optional[T] {
	return &emptyValue[T]{t: t}
}

func NullWrap[T []any | *any](t T) Optional[T] {
	return &emptyValue[T]{t: t}
}

func Flat[T []any | *any, V []any | *any](t Optional[T], f func(t T) V) Optional[V] {

	if t.IsNil() {
		return &emptyValue[V]{}
	}

	return NullWrap(f(t.Value()))
}

func main() {

	foo := &Foo{}
	ops := NullWrap(foo)

	v := Flat(ops, func(v *Foo) *Foo {
		return &Foo{}
	})

	Flat(v, func(l *Foo) *Foo {
		return &Foo{}
	})
}
```

### What did you expect to see?
I guest that *Foo need not implement []any|*any`. this is only type constraints.
why happened,please help me!!!

**Comment by mdlayher** [comment]
Please see https://github.com/golang/go/wiki/Questions.
