### ISSUE TITLE
proposal: src/bufio: consider add one function for handle multi delimeter one by one

### ISSUE THREAD

**Issue by crazy-cpu** [golang/go#56927]
example: 4040010000000000080101e2000000000000000000000000030004510100462323

0x23 0x23 is end of protocol example from network flow,is necessary new add function to handle multi delimeter

for examle . 
```
func reader.ReadBytes(delim byte,count int) 
```
instead of 

```
 func reader.ReadBytes(delim byte) 
```

or other way?

**Comment by seankhliao** [comment]
See Scanner.Split, it covers a wider range of usecases than just repeated byte delimiters

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
