### ISSUE TITLE
os/user: TestCredentialNoSetGroups failed

### ISSUE THREAD

**Issue by YoshikiShibata** [golang/go#56942]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.20-d5de62df15 Thu Nov 24 06:48:07 2022 +0000 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

N/A

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/yoshikishibata/Library/Caches/go-build"
GOENV="/Users/yoshikishibata/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/yoshikishibata/gocode/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/yoshikishibata/gocode"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/yoshikishibata/tools/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/yoshikishibata/tools/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="devel go1.20-d5de62df15 Thu Nov 24 06:48:07 2022 +0000"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/fs/3c1rlryd2v3_z5m04g3lnd580000gn/T/go-build3727885018=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version devel go1.20-d5de62df15 Thu Nov 24 06:48:07 2022 +0000 darwin/arm64
GOROOT/bin/go tool compile -V: compile version devel go1.20-d5de62df15 Thu Nov 24 06:48:07 2022 +0000
uname -v: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103
ProductName:		macOS
ProductVersion:		13.0.1
BuildVersion:		22A400
lldb --version: lldb-1400.0.38.13
Apple Swift version 5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51)
</pre></details>

### What did you do?

Rebuild from the source (run all.bash)

### What did you expect to see?

No error

### What did you see instead?

```
ok  	os	1.111s
--- FAIL: TestCredentialNoSetGroups (0.00s)
    exec_posix_test.go:47: error getting current user: user: unknown userid 501
FAIL
FAIL	os/exec	0.555s
ok  	os/exec/internal/fdtest	0.222s
ok  	os/signal	3.320s
--- FAIL: TestCurrent (0.00s)
    user_test.go:21: Current: user: unknown userid 501 (got (*user.User)(nil))
--- FAIL: TestLookup (0.00s)
    user_test.go:60: Current: user: unknown userid 501
--- FAIL: TestLookupId (0.00s)
    user_test.go:77: Current: user: unknown userid 501
--- FAIL: TestLookupGroup (0.00s)
    user_test.go:97: Current(): user: unknown userid 501
--- FAIL: TestGroupIds (0.00s)
    user_test.go:132: Current(): user: unknown userid 501
FAIL
FAIL	os/user	0.290s
ok  	path	0.221s
```

**Comment by seankhliao** [comment]
are you uid 501?
does it also fail without cgo?

**Comment by YoshikiShibata** [comment]
Yes, my UserID is 501 which is the first user account after setting up macOS.

**Comment by YoshikiShibata** [comment]
Without cgo:

```
--- FAIL: TestCredentialNoSetGroups (0.00s)
    exec_posix_test.go:47: error getting current user: user: unknown userid 501
FAIL
FAIL	os/exec	0.544s
ok  	os/exec/internal/fdtest	0.214s
ok  	os/signal	2.776s
--- FAIL: TestCurrent (0.00s)
    user_test.go:21: Current: user: unknown userid 501 (got (*user.User)(nil))
--- FAIL: TestLookup (0.00s)
    user_test.go:60: Current: user: unknown userid 501
--- FAIL: TestLookupId (0.00s)
    user_test.go:77: Current: user: unknown userid 501
--- FAIL: TestLookupGroup (0.00s)
    user_test.go:97: Current(): user: unknown userid 501
--- FAIL: TestGroupIds (0.00s)
    user_test.go:132: Current(): user: unknown userid 501
FAIL
FAIL	os/user	0.269s
ok  	path	0.225s
```

**Comment by andlabs** [comment]
501 is the standard UID for the first user on macOS. The non-cgo path looks at /etc/passwd, which explicitly says is only used in single-user mode and does not contain any actual users.

**Comment by rsc** [comment]
The non-cgo path does not run on macOS anymore. That file says

    //go:build ((unix && !android) || (js && wasm)) && ((!cgo && !darwin) || osusergo)

The cgo_lookup_unix.go code, despite the file name, runs always on macOS, since it doesn't actually use cgo (it uses direct libc calls instead):

    //go:build (cgo || darwin) && !osusergo && unix && !android

So there shouldn't be any problem with cgo vs non-cgo. And nothing should be reading /etc/passwd.

Clearly something about the cgo path is not right anymore.

**Comment by rsc** [comment]
I can't seem to reproduce this on either of my Macs. It would help if you could check which of these two CLs introduces the breakage:

2022-11-10 c3d444d0985 os/user: allocate buffers in Go memory, not C memory
2022-11-10 185766de0ff os/user: use libc (not cgo) on macOS

My guess is the first one is OK and the second one is what breaks. But knowing for sure would help narrow the search. Thanks.

**Comment by rsc** [comment]
Found the problem, CL sent.
