### ISSUE TITLE
affected/package: html/template

### ISSUE THREAD

**Issue by ahfuzhang** [golang/go#56952]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.13 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
I didn't test yet.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/ahfuzhang/Library/Caches/go-build"
GOENV="/Users/ahfuzhang/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/ahfuzhang/go/pkg/mod"
GONOPROXY="git.garena.com"
GONOSUMDB="git.garena.com"
GOOS="darwin"
GOPATH="/Users/ahfuzhang/go"
GOPRIVATE="git.garena.com"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.17.13"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xl/1x9hw92n2f7dz9n93j0txzmm0000gp/T/go-build3326179315=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

those code will make index page error:
```go
//go:embed index.html
var indexFileTemplate string
var indexTempate = template.New("index")

//go:embed mysql_data_source.html
var mysqlDataSourceFileTemplate string

var mysqlDataSourceTempate = template.New("mysql_data_source")

// var mysqlDataSourceTempate = template.Must(template.New("mysql_data_source").Parse(mysqlDataSourceFileTemplate))

func init() {
	indexTempate = template.Must(indexTempate.Parse(indexFileTemplate))
	mysqlDataSourceTempate = template.Must(indexTempate.Parse(mysqlDataSourceFileTemplate))
}
```
error info is : `template: index:9:49: executing "index" at <.Name>: can't evaluate field Name in type *page.templateParam`

and those code is fine:
```go
//go:embed index.html
var indexFileTemplate string
var indexTempate = template.New("index")

//go:embed mysql_data_source.html
var mysqlDataSourceFileTemplate string

var mysqlDataSourceTempate = template.New("mysql_data_source")

var mysqlDataSourceTempate = template.Must(template.New("mysql_data_source").Parse(mysqlDataSourceFileTemplate))

func init() {
	indexTempate = template.Must(indexTempate.Parse(indexFileTemplate))
	// mysqlDataSourceTempate = template.Must(indexTempate.Parse(mysqlDataSourceFileTemplate))
}
```

I don't known why. 
Thanks.

**Comment by D1CED** [comment]
You override the `indexTempate` in the first case by calling `Parse` on it a second time. `indexTempate` and `mysqlDataSourceTempate` will then be the same.

In the second case you create a new one with the same name. This way they are not associated to each other.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by ahfuzhang** [comment]
> You override the `indexTempate` in the first case by calling `Parse` on it a second time. `indexTempate` and `mysqlDataSourceTempate` will then be the same.
> 
> In the second case you create a new one with the same name. This way they are not associated to each other.

thanks.
