### ISSUE TITLE
crypto: boringcrypto memory leak patch from rhel8

### ISSUE THREAD

**Issue by ha-lam** [golang/go#56963]
### What version of Go are you using (`go version`)?

<pre>
1.20

</pre>

### Does this issue reproduce with the latest release?

Yes

The following patch for a memory leak is from rhel8, I'm wondering why Go doesn't have this patch:

https://git.rockylinux.org/staging/rpms/golang/-/blob/r8-stream-rhel8/SOURCES/fix-crypto-memory-leaks.patch#L203

Note that the patch is for an older code base that uses `C.malloc` instead of the [current](https://github.com/golang/go/blob/master/src/crypto/internal/boring/rsa.go#L161) `C._goboringcrypto_OPENSSL_malloc`.

To update the patch so that it uses the corresponding `C._goboringcrypto_OPENSSL_free` is a bit of work because `_goboringcrypto_OPENSSL_free` is not in [the current goboringcrypto.h file](https://github.com/golang/go/blob/master/src/crypto/internal/boring/goboringcrypto.h). This means that to use this patch, I have to rebuild the syso file for the updated header file.

It would be good to either have the patch merged or to understand why it is unnecessary.

**Comment by seankhliao** [comment]
The upstream for that is https://github.com/golang-fips/go
which uses openssl rather than boringcrypto.

Closing as out of scope for the Go project.
