### ISSUE TITLE
x/build/cmd/coordinator: apply GO_TEST_TIMEOUT_SCALE to scale go test timeout for x-repo tests

### ISSUE THREAD

**Issue by bcmills** [golang/go#56968]
Many of the slower Go builders (especially reverse builders) set `GO_TEST_TIMEOUT_SCALE` to some positive factor to compensate for a slow host.

For the main `go` repo, that scale factor is currently applied in `cmd/dist`:
https://cs.opensource.google/go/go/+/master:src/cmd/dist/test.go;l=207-212;drc=0a8055ef3f84673dc3a70ce5143bdf9817986dea

However, I don't see any place where we apply it for the `x`-repo tests:
https://cs.opensource.google/search?q=GO_TEST_TIMEOUT_SCALE&sq=&ss=go%2Fx%2Fbuild

And, empirically it does not seem to be applied for `x` repos at all. In https://build.golang.org/log/a2a8de1767171071d4551d937474538b0ad961c6, we see `GO_TEST_TIMEOUT_SCALE=10` in the environment, but a `test timed out after 10m0s` — which is exactly equal to the default timeout for `go test`!

Perhaps we should update [`(*cmd/coordinator.buildStatus).runSubrepoTests`](https://cs.opensource.google/go/x/build/+/master:cmd/coordinator/buildstatus.go;l=1080-1086;drc=46a4cc89025a035aab2df0f9fb5036bb95dd42c3) to also apply the scale factor? It seems unduly optimistic to assume that `x` tests will run quickly even when `std` tests do not.

**Comment by bcmills** [comment]
In combination with #47257 (which has the side-effect of causing tests that need export data for `std` to become much more expensive), this is causing frequent test timeouts on at least one of the reverse builders (#56967).

(CC @aclements @golang/release)

**Comment by aclements** [comment]
I don't suppose we'd be willing to apply `GO_TEST_TIMEOUT_SCALE` in `go test` itself?

**Comment by bcmills** [comment]
At the very least, I think that would require a proposal (and perhaps a freeze exception). 😅

**Comment by aclements** [comment]
Fair enough.

I'll note that *in addition to* processing `GO_TEST_TIMEOUT_SCALE`, dist also has a [default timeout scale](https://cs.opensource.google/go/go/+/master:src/cmd/dist/test.go;l=201?q=GO_TEST_TIMEOUT_SCALE&ss=go) for a few architectures. I'm not sure that's something we'd want to duplicate in `go test`, but that logic in dist could instead set `GO_TEST_TIMEOUT_SCALE` and let `go test` apply it. That would keep all.bash working for users on those architectures.

(The whole thing is weird, maybe we should be running a quick benchmark at the beginning of dist test and setting a timeout scale based on that!)

**Comment by Santanathegreat** [comment]
Perhaps we should update [(*cmd/coordinator.buildStatus).runSubrepoTests](https://cs.opensource.google/go/x/build/+/master:cmd/coordinator/buildstatus.go;l=1080-1086;drc=46a4cc89025a035aab2df0f9fb5036bb95dd42c3) to also apply the scale factor? It seems unduly optimistic to assume that x tests will run quickly even when std tests do not.

**Comment by bcmills** [comment]
> dist also has a [default timeout scale](https://cs.opensource.google/go/go/+/master:src/cmd/dist/test.go;l=201?q=GO_TEST_TIMEOUT_SCALE&ss=go) for a few architectures.

Could we just get rid of that default and set `GO_TEST_TIMEOUT_SCALE` explicitly on the builders? I don't think we should be in the business of assuming the performance characteristics of architectures, especially given the performance overlap between modern ARM and x86 (and between ARM and ARM64).

> (The whole thing is weird, maybe we should be running a quick benchmark at the beginning of dist test and setting a timeout scale based on that!)

Long-term (once we implement #48157), I wonder if the per-test-binary timeouts are even all that useful. But I guess even with per-test timeouts we'd still need a way to scale them.

I'm not sure that running a benchmark would be all that helpful: some builders are slow because of CPU performance, while others are slow because of disk performance (which disproportionately affects toolchain tests, since they tend to be more I/O intensive), and yet others are slow because of low memory (resulting in contention for file buffer cache and/or swap space). To get a reliable benchmark, we would probably need to measure all three — and we'd still need to figure out a way to incorporate that into `go test` in general.

**Comment by bcmills** [comment]
> In combination with https://github.com/golang/go/issues/47257 (which has the side-effect of causing tests that need export data for std to become much more expensive), this is causing frequent test timeouts on at least one of the reverse builders (https://github.com/golang/go/issues/56967).

I've resolved #56967 in a different way (via [CL 454497](https://go.dev/cl/454497) and [CL 454499](https://go.dev/cl/454499)), so I believe this is no longer contributing to ongoing test timeouts.

However, I do still think we should fix it at some point: I suspect that honoring `GO_TEST_TIMEOUT_SCALE` would help us reduce the technical debt embodied in [`golang.org/x/tools/internal/testenv.ExitifSmallMachine`](https://pkg.go.dev/golang.org/x/tools/internal/testenv#ExitIfSmallMachine).
