### ISSUE TITLE
path/filepath: filepath.Join() not respecting \ in backticks on Windows

### ISSUE THREAD

**Issue by bagarber** [golang/go#56988]
### What version of Go are you using (`go version`)?

I'm compiling this binary on Linux.

<pre>
$ go version
go version go1.20-pre3 cl/474093167 +a813be86df linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

I'm running this compiled binary on Windows, x64.

### What did you do?

I wrote the following code and ran it on Windows.

```
// Package main assembles a filepath.
package main

import (
	"fmt"
	"os"
	"path/filepath"
)

func main() {
	fmt.Println("Printing the filepath!")
	fmt.Printf(filepath.Join(os.Getenv("SystemDrive"), `\Program Files\test`))
}
```

### What did you expect to see?
```
Printing the filepath!
C:\Program Files\test
```
Please note the slash between the colon and the "P" in "Program Files".

### What did you see instead?
```
Printing the filepath!
C:Program Files\test
```
The first slash seems to have been discarded.

**Comment by bcmills** [comment]
This may be related to the changes for #56336 (attn @neild).

@bagarber, does Go 1.19.3 also exhibit this problem, or is it a regression in 1.20?

**Comment by ianlancetaylor** [comment]
CC @golang/windows

**Comment by bagarber** [comment]
I tested the code here using `version go1.19.3 windows/amd64` and the issue does **not** reproduce there.

**Comment by neild** [comment]
This looks to be an inadvertent effect of https://go.dev/cl/444280.
