### ISSUE TITLE
cmd/compile: CMOV optimization allows GC to see invalid pointer

### ISSUE THREAD

**Issue by randall77** [golang/go#56990]
[This program](https://go.dev/play/p/u1lunyS8Hdm) when run on the playground, go1.18, go1.19, or tip, crashes when the Go runtime finds an invalid pointer on the stack.

@cherrymui determined that this has to do with a conditional move optimization. We have code like:

```
if q != nil {
    p = &q.f
}
```
Which gets rewritten to a conditional move:
```
tmp := &q.f
p = Select q!=nil, tmp, p
```
Unfortunately, we can't compute `&q.f` before we've checked if `q` is nil, because if it is nil, `&q.f` is an invalid pointer (if `f`'s offset is nonzero but small).

Normally this is not a problem because the `tmp` variable above immediately dies, and is thus not live across any safepoint. However, if later there is another `&q.f` computation, those two computations are CSEd, causing `tmp` to be used at both use points. That will extend `tmp`'s lifetime, possibly across a call.

**Comment by cherrymui** [comment]
Simpler reproducer
```
package main

type ConfigSpec int

// Config is the Schema for the configs API.
type Config struct {
	x, y int
	Spec ConfigSpec
}

//go:noinline
func f1(cs *ConfigSpec) {
	grow(100000)
}

func grow(n int) { if n > 0 { grow(n-1) } }


//go:noinline
func f2(cs *ConfigSpec) {}

//go:noinline
func Foo(config *Config) {
	var cs *ConfigSpec
	if config != nil {
		cs = &config.Spec
	}
	f1(cs)
	if config != nil {
		cs = &config.Spec
		f1(cs)
	}
	f2(cs)

}

func main() {
	Foo(nil)
}
```

This fails since at least Go 1.11 (possibly even earlier).

**Comment by toothrot** [comment]
Removing the release-blocker label as this is not a new regression.
