### ISSUE TITLE
cmd/compile: incosistent behaviour when assigning slices from a base slice with append

### ISSUE THREAD

**Issue by sipwarriper** [golang/go#56999]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.2 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env 
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="~/Library/Caches/go-build"
GOENV="~/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="~/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="~/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sq/szsnndwj6qz7ynp902xhg9rr0000gn/T/go-build4130374379=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
I have a base slice with some elements. And I need 2 slices with the same base elements, and some different elements at the end of them, so I used append to add those elements to the base array 2 times, assigning each of them to a new different variable. Something like this: 
```
a := append(base, elem1)
b := append(base, elem2)
```
The content of `a` and `b` after assigning `b` is the same in both slices. This changes depending on the number .

Here's an example reproducing the error (with a link to the playground with the same code). 

```
package main

import "fmt"

func main() {
	lim := 3
	a := []int{}
	for i := 0; i < lim; i++ {
		a = append(a, i)
	}

	b := append(a, 20)
	fmt.Println(b)
	c := append(a, 30)
	fmt.Println(b)
	fmt.Println(c)
}

```
https://go.dev/play/p/5IeuvhEOM13

when changing `lim` value to 2, the behavior is different, `a` and `b` have the values I would expect:

### What did you expect to see?

the same behavior when assigning the new variables, regardless of the number of elements in the base slice. 

with `lim:= 2`
``` 
[0 1 20]
[0 1 20]
[0 1 30]
```

with `lim:=3`
``` 
[0 1 2 20]
[0 1 2 20]
[0 1 2 30]
```

### What did you see instead?
with `lim:= 2`
``` 
[0 1 20]
[0 1 20]
[0 1 30]
```

with `lim:=3`
``` 
[0 1 2 20]
[0 1 2 30]
[0 1 2 30]
```

depending on the number of elements, the first variable I assign takes the value I appended first or second. This is confusing to me. Is this behaviour expected?

**Comment by fzipp** [comment]
This is normal slice behavior. They initially share the same backing array in memory and thus affect each other, but if the data exceeds the capacity, `append` allocates a new backing array with twice the capacity and copies the data. Now the slices have different backing arrays in different memory locations and do no longer affect each other.

You can see this by logging the memory addresses and capacities of the slices:
- https://go.dev/play/p/jUQFxuEuayj
- https://go.dev/play/p/2EdUzilZJXs

**Comment by ianlancetaylor** [comment]
Please see https://go.dev/blog/slices.
