### ISSUE TITLE
x/vuln: Package files not found for modules containing capital letters

### ISSUE THREAD

**Issue by peterebden** [golang/go#56996]
### What version of Go are you using (`go version`)?
N/A

### Does this issue reproduce at the latest version of golang.org/x/vuln?
Yes

### What operating system and processor architecture are you using (`go env`)?
N/A

### What did you do?
Part of our internal vulnerability process occasionally downloads vulnerabilities from the Go vuln DB. At present it fetches the entire set (since it's relatively small and we rarely need to re-download it this hasn't been a problem).

### What did you expect to see?
All modules referred to in [the index](https://vuln.go.dev/index.json) have corresponding module files that are retrievable from the API.

### What did you see instead?
The following URLs return 404s:
[https://vuln.go.dev/github.com/AndrewBurian/powermux.json](https://vuln.go.dev/github.com/AndrewBurian/powermux.json)
[https://vuln.go.dev/github.com/Masterminds/goutils.json](https://vuln.go.dev/github.com/Masterminds/goutils.json)
[https://vuln.go.dev/github.com/Masterminds/vcs.json](https://vuln.go.dev/github.com/Masterminds/vcs.json)
[https://vuln.go.dev/github.com/RobotsAndPencils/go-saml.json](https://vuln.go.dev/github.com/RobotsAndPencils/go-saml.json)

It seems to be only those four which are failing (e.g. [github.com/antchfx/xmlquery](https://vuln.go.dev/github.com/antchfx/xmlquery.json) downloads fine). 
I surmise there may be a problem involving the module path containing capital letters since these four are the only modules in the index with them.

**Comment by seankhliao** [comment]
It uses exclamation encoding for caps in the same way as the GOPROXY protocol, see https://go.dev/ref/mod#goproxy-protocol

Ex: https://vuln.go.dev/github.com/!andrew!burian/powermux.json

**Comment by peterebden** [comment]
Great, thanks for explaining that!

Would it be possible to update the documentation on https://go.dev/security/vuln/database to mention this? I am happy to send a PR although would appreciate a pointer on where that lives.

**Comment by seankhliao** [comment]
That's should be this line

> To avoid various character set issues, the $module element is encoded using [module.EncodePath](https://pkg.go.dev/golang.org/x/mod/module/#EncodePath).
