### ISSUE TITLE
proposal: crypto/tls: contributor Manual for testdata.

### ISSUE THREAD

**Issue by jclab-joseph** [golang/go#57019]
https://github.com/golang/go/tree/master/src/crypto/tls/testdata

How is the above testdata created?
It would be nice to have a manual on how to create data for contributors.

**Comment by seankhliao** [comment]
there is a comment in handshake_test.go

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
