### ISSUE TITLE
math/big: regression in BitLen

### ISSUE THREAD

**Issue by rsc** [golang/go#57014]
CL 450055 replaced big.Int.BitLen with a portable constant-time operation for fear of bits.LeadingZeros using a lookup table on some architectures (notably not on x86, which uses a hardware instruction). @drchase's benchmarks found https://perf.golang.org/search?q=upload%3A20221130.13+pkg%3Agithub.com%2Fericlagergren%2Fdecimal%2Fbenchmarks, non-crypto code with a significant performance hit for a property (constant-time) it didn't need.

Talked to @filosottile, and he is going to send a CL removing use of big.Int.BitLen from crypto code and restoring the old implementation.

Filing issue so we remember to submit the CL before the release.

**Comment by ericlagergren** [comment]
Sorry :)

**Comment by prattmic** [comment]
Fix confirmed on https://perf.golang.org/dashboard/?benchmark=Pi%2Ffoo%3Dericlagergren_%28Go%29%2Fprec%3D100-8&days=60&end=2022-12-21T16%3A46

![image](https://user-images.githubusercontent.com/1293187/208959515-adfbd983-5f14-4da7-9918-8bddc4dcdf5f.png)
