### ISSUE TITLE
x/tools/gopls: signal version differences in go.mod when using go.work

### ISSUE THREAD

**Issue by hyangah** [golang/go#57026]
go.mod is not a lock file and go's module version selection may pick versions different from what are written in go.mod require statement. But most of time, we expect the versions appearing in go.mod are the versions actually in use. Especially, when using `go.work` or `replace` or `exclude` come into play, the difference can be sometimes confusing.

How about surfacing this when the versions chosen by Go and written in the main module's go.mod are different?
Either using  1) inlay hints next to the require statement or 2) informational diagnostics on the require statement.

cc ideas from @ianthehat

**Comment by findleyr** [comment]
Makes sense to me.

CC @bcmills, who may have insight.

**Comment by findleyr** [comment]
Peter and I just discussed this, and realized it would be useful to compute this information whenever we build the metadata graph (`cache.metadataGraph.build`). Then adding an inlay hint becomes a very cheap operation.
