### ISSUE TITLE
x/playground: playground does not run fuzz tests

### ISSUE THREAD

**Issue by bcmills** [golang/go#57029]
### What did you do?

Write a Fuzz test in the Playground: https://go.dev/play/p/YWPNCv-_iS7

### What did you expect to see?

The same output as running `go test -v` locally on the file:
```
$ go test -v
=== RUN   FuzzNorm
=== RUN   FuzzNorm/seed#0
    main_test.go:67: oldNorm(-9223372036854775808, -9223372036854775808, 1) = 0, 0
    main_test.go:70: norm(-9223372036854775808, -9223372036854775808, 1) = 0, 0, false
=== RUN   FuzzNorm/seed#1
    main_test.go:67: oldNorm(-9223372036854775808, 9223372036854775807, 1) = -1, 0
    main_test.go:70: norm(-9223372036854775808, 9223372036854775807, 1) = -1, 0, true
=== RUN   FuzzNorm/seed#2
    main_test.go:67: oldNorm(9223372036854775807, -9223372036854775808, 1) = -1, 0
    main_test.go:70: norm(9223372036854775807, -9223372036854775808, 1) = -1, 0, true
=== RUN   FuzzNorm/seed#3
    main_test.go:67: oldNorm(9223372036854775807, 9223372036854775807, 1) = -2, 0
    main_test.go:70: norm(9223372036854775807, 9223372036854775807, 1) = 0, 0, false
=== RUN   FuzzNorm/c8836bb80adad37a
    main_test.go:67: oldNorm(-9223372036854775783, -9223372036854775799, 111) = 9140278595081309384, 40
    main_test.go:70: norm(-9223372036854775783, -9223372036854775799, 111) = 0, 0, false
--- PASS: FuzzNorm (0.00s)
    --- PASS: FuzzNorm/seed#0 (0.00s)
    --- PASS: FuzzNorm/seed#1 (0.00s)
    --- PASS: FuzzNorm/seed#2 (0.00s)
    --- PASS: FuzzNorm/seed#3 (0.00s)
    --- PASS: FuzzNorm/c8836bb80adad37a (0.00s)
PASS
ok      example 0.011s
```

### What did you see instead?

A build error:
```
runtime.main_main·f: function main is undeclared in the main package

Go build failed.
```

Adding a dummy `Test` function (https://go.dev/play/p/OoIPkmP05-K) causes only that test to be run, not the seed values for the `Fuzz` function:
```
=== RUN   TestDummy
--- PASS: TestDummy (0.00s)
PASS

Program exited.
```

(CC @golang/fuzzing for `Fuzz`, @toothrot for `x/playground`)

**Comment by bcmills** [comment]
It looks like the problem is that `getTestProg` currently only checks for `Test` functions:
https://cs.opensource.google/go/x/playground/+/master:sandbox.go;l=254-256;drc=5931d39a14321611dd3d7a9061d66e2f0d9b95c1

**Comment by nikola-jokic** [comment]
Hey, may I give it a shot?  :smile:

**Comment by bcmills** [comment]
Sure! (See https://go.dev/doc/contribute for documentation on the code review process.)

**Comment by nikola-jokic** [comment]
Just a quick update, I am finishing up changes. I tested by hand and it works.
I want to add unit tests as well, just in case.
Everything should be ready by tomorrow :relaxed:
