### ISSUE TITLE
docs: go fuzzing docs in go.dev blog

### ISSUE THREAD

**Issue by sshaplygin** [golang/go#57027]
Hey, everyone! 

I read the [article](https://go.dev/security/fuzz/) in DARK mode about go fuzzing. I guess, source code by black font on grey background look awful.

Please, fix it

**Comment by sshaplygin** [comment]
light mode
<img width="1243" alt="Снимок экрана 2022-12-01 в 19 51 34" src="https://user-images.githubusercontent.com/14343349/205084349-13f93faf-0ae2-4c41-897d-2e510237ec6a.png">

dark mode <img width="1262" alt="Снимок экрана 2022-12-01 в 19 50 10" src="https://user-images.githubusercontent.com/14343349/205084389-c242c8e0-034c-40d6-9e68-c17c86676261.png">

**Comment by ALTree** [comment]
Indeed, but also dup of #54954. Closing here in favour of the older thread.
