### ISSUE TITLE
cmd/go: TestScript/version_buildvcs_git_gpg (if enabled) fails on linux longtest builders

### ISSUE THREAD

**Issue by cherrymui** [golang/go#57034]
Split from #49649 . Filing a new issue to investigate/decide.

After setting up the linux-arm64-longtest builder, we saw cmd/go's TestScript/version_buildvcs_git_gpg fails.
https://build.golang.org/log/7b3bdfcc706b20aeb4deb0a6b7fb6c73d75670d9

On 386 and amd64,  linux-386-longtest and linux-amd64-longtest builders didn't actually have `gpg` command installed, so the test was actually skipped. @cagedmantis 's CL installs the command. And after that, the test fails on those builders, too. https://build.golang.org/log/30e41a5b422d7ca512aa244816e1ee578dfa9285
So we currently rolled back the builder update.

Interestingly, the test passes under SSH, but fails in the post-submit run and under `gomote run`. From https://github.com/golang/go/issues/49649#issuecomment-1334261636, it seems `TMPDIR` or some other environment variable settings may cause the difference.

cc @bcmills

**Comment by bcmills** [comment]
@gopherbot, please backport to Go 1.19 and 1.18: this test may fail spuriously due to problems with a fragile third-party tool.

**Comment by cagedmantis** [comment]
I will update the `linux-amd64-longtest` and `linux-386-longtest` builder images to include `gpg-agent` and `gpg` next week.

**Comment by bcmills** [comment]
@cagedmantis, I don't think you need to bother. I don't plan to try to restore the test — the complexity of the workarounds for the fragile socket behavior does not seem worth it for the incremental value of the test.
