### ISSUE TITLE
BSD Zero Clause License not being detected

### ISSUE THREAD

**Issue by nikitavoloboev** [golang/go#57075]
### What is the URL of the page with the issue?

The package: https://github.com/nikitavoloboev/go-safari 

License file: https://github.com/nikitavoloboev/go-safari/blob/main/license

GoDoc says it can't recognise it and said to open an issue here. 

https://pkg.go.dev/github.com/nikitavoloboev/go-safari
 
### What is your user agent?
 

 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15
 
### What did you expect to see?
 
I expect GoDoc to recognize the license file and show Go developers my documentation for the package.
 
 
### What did you see instead?

Saw: `Documentation not displayed due to license restrictions. See our license policy.`

**Comment by nikitavoloboev** [comment]
One thing to note is that GitHub recognises this license file.

<img width="160" alt="image" src="https://user-images.githubusercontent.com/6391776/205494683-1aab2056-f130-42e4-8459-7eb0890e7d9a.png">

So something wrong with `licensecheck` perhaps.

**Comment by seankhliao** [comment]
Looks like it's working now.
