### ISSUE TITLE
x/tools/bundle: explain bundle semantics

### ISSUE THREAD

**Issue by switchupcb** [golang/go#57087]
### What version of Go are you using (`go version`)?

<pre>
$ go 1.18
</pre>

### Does this issue reproduce with the latest release?

No idea.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\rsc\AppData\Local\go-build
set GOENV=C:\Users\rsc\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\rsc\go\pkg\mod
set GOOS=windows
set GOPATH=C:\Users\rsc\go
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.18.1
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\rsc\Documents\Github\disgo\_gen\go.mod
set GOWORK=off
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\rsc\AppData\Local\Temp\go-build1032919154=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

```go
// works in terminal, not with exec from no shell
// run from ./disgo after using chdir code
bundle := exec.Command("bundle",
    "-dst", ".",
    "-pkg", "disgo",
    "-prefix", "\"\"",
    "./wrapper",
)

var f bytes.Buffer
bundle.Stdout = &f // also tried with CombinedOutput
err := bundle.Run()
// time.Sleep(time.Second * 5) changes nothing

fmt.Println(f.String()) // nothing
fmt.Println(err) // exit code 1
// bundle.Stderr = Format error
```

### What did you expect to see?

The output (even with a format error).

Same with `-o` specified (no file output). When I use in terminal it works with a format error. Every other executable in [`_gen`](https://github.com/switchupcb/disgo/tree/v10/_gen) works, except this one. I had to use a go generate trick. Plus, I can't even call `bundle` from the Go language. So maybe it's an issue.

### What did you see instead?

Just the format error: Output is empty.

**Comment by seankhliao** [comment]
your issue is with how your passing the empty string.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by switchupcb** [comment]
@seankhliao Can you explain? The error I get is from the `bundle` tool because it resolves imports wrong. Not because the prefix is incorrect.

**Comment by switchupcb** [comment]
@andydotxyz The prefix must empty or it will precede with `wrapper`. There is no error there.

**Comment by andydotxyz** [comment]
`"\"\""` is not the empty string, `""` is.
