### ISSUE TITLE
net/http: apparent deadlock in TestServerWriteTimeout on plan9-amd64-0intro

### ISSUE THREAD

**Issue by bcmills** [golang/go#57114]
```
#!watchflakes
post <- builder ~ `^plan9` && pkg == "net/http" && test == "TestServerWriteTimeout"
```

As of [CL 449935](https://go.dev/cl/449935), the `plan9-amd64-0intro` builder went from failing something like 25% of the time to failing nearly 100% of the time.

The vast majority of the current failures are test timeouts running `net/http`, and they all seem to involve goroutines parked in `net/http.(*http2ClientConn).RoundTrip` via `net/http_test.testServerWriteTimeout`.

I think this is probably because the plan9 netpoll implementation does not support (or does not fully support?) `SetDeadline`.

(attn @golang/plan9; CC @neild)

**Comment by 0intro** [comment]
Deadlines should be supported. What is not supported is half closing of TCP connections (`closeWrite`, `closeRead`, see issue #17906), but I don't believe it's related here.

I'm not sure why this issue is happening on the amd64 builder only and not on the 386 and arm builders. I'll investigate.

**Comment by bcmills** [comment]
> I'm not sure why this issue is happening on the amd64 builder only and not on the 386 and arm builders. I'll investigate.

Turns out that it does occasionally happen on the `plan9-arm` builder too:
https://build.golang.org/log/c3901bbe3d4681c4026a08664447fe2629aeebbd

**Comment by bcmills** [comment]
> Strictly speaking this is not specifically a Plan 9 issue, since the deadlock could occur on any platform given the right timing. I've simulated this on linux by hacking a deadline in the past after the server reads the client's request. That results in the same deadlock.
…
> should I submit the `ResponseHeaderTimeout` workaround for this test, or just rely on the `poll.FD` fix to prevent it from happening?

Could you file a separate issue for the cross-platform bug? I don't think that setting a client-side `ResponseHeaderTimeout` should be necessary.

If a write timeout occurs before (or while) writing headers, I would expect the server to close the connection immediately instead of waiting for the client to close it.

**Comment by millerresearch** [comment]
> If a write timeout occurs before (or while) writing headers, I would expect the server to close the connection immediately instead of waiting for the client to close it.

Is that the right thing to do with respect to http2 persistent connections? Or should the client be able to time out and send another request on the same connection? I don't know what the http spec says.

**Comment by bcmills** [comment]
I'm not sure! That's part of why I think it merits a separate issue for discussion. 😅

**Comment by millerresearch** [comment]
> Could you file a separate issue for the cross-platform bug? I don't think that setting a client-side `ResponseHeaderTimeout` should be necessary.
> 
> If a write timeout occurs before (or while) writing headers, I would expect the server to close the connection immediately instead of waiting for the client to close it.

Sorry, I was mistaken: my simulation wasn't realistic. In http2 deadlines (after the TLS handshake) are set by an explicit `time.AfterFunc`, not by setting a deadline on the underlying connection. So this is just a Plan 9 issue.
