### ISSUE TITLE
x/pkgsite: package removal request for github.com/haseeb-apimatic/go-core-lib

### ISSUE THREAD

**Issue by haseeb-apimatic** [golang/go#57133]
### What is the path of the package that you would like to have removed?

https://pkg.go.dev/github.com/haseeb-apimatic/go-core-lib

### Are you the owner of this package?
Yes.

### What is the reason that you could not retract this package instead?
I have published the wrong code with correct version. I don't want to retract it. You can remove it so that I can publish a new package with new name.

**Comment by seankhliao** [comment]
we can only hide documentation, it won't affect any available versions.

**Comment by haseeb-apimatic** [comment]
> we can only hide documentation, it won't affect any available versions.

Yes its version don't get affected but its documentation is still visible.@seankhliao

**Comment by seankhliao** [comment]
sorry, i read that wrong.

**Comment by haseeb-apimatic** [comment]
> sorry, i read that wrong.

Its ok. I only want to hide its documentation. Can you hide its documentation Or assign someone else who can do that.

**Comment by findleyr** [comment]
Looks like this was done!
