### ISSUE TITLE
cmd/compile: insert new nil checks

### ISSUE THREAD

**Issue by dvyukov** [golang/go#5713]
<pre>parent: 17086:2879112bff3d tip, linux/amd64

The program is:

package main

type Foo struct {
	len int
	buf [1&lt;&lt;20]interface{}
}

var foo = new(Foo)

func main() {
	println(bar(0))
}

func bar(x int) *interface{} {
	if x &gt;= foo.len {
		return nil
	}
	return &amp;foo.buf[x]
}

The generated code is:

        return &amp;foo.buf[x]
  400c75:       48 89 cb                mov    %rcx,%rbx
  400c78:       f6 03 00                testb  $0x0,(%rbx)
  400c7b:       48 8d 6b 08             lea    0x8(%rbx),%rbp
  400c7f:       48 89 c3                mov    %rax,%rbx
  400c82:       f6 45 00 00             testb  $0x0,0x0(%rbp)
  400c86:       48 81 fb 00 00 10 00    cmp    $0x100000,%rbx
  400c8d:       73 0d                   jae    400c9c &lt;main.bar+0x5c&gt;
  400c8f:       48 6b db 10             imul   $0x10,%rbx,%rbx
  400c93:       48 01 dd                add    %rbx,%rbp
  400c96:       48 89 6c 24 10          mov    %rbp,0x10(%rsp)
  400c9b:       c3                      retq   

There are two 'testb $0x0, addr' checks. The second one is unnecessary, because it is
the same object. It basically checks:
testb  $0x0,(%rbx)
and:
testb  $0x0,8(%rbx)

The second check causes 5.8x slowdown for my program, because it causes false sharing --
each element of the array is accessed by a single goroutine, and the testb check
accesses the data owned by a different goroutine.</pre>

**Comment by josharian** [comment]
Fixed by SSA. There are now no nil checks. :)

```
"".bar t=1 size=96 args=0x10 locals=0x0
	0x0000 00000 (d.go:14)	TEXT	"".bar(SB), $0-16
	0x0000 00000 (d.go:14)	MOVQ	(TLS), CX
	0x0009 00009 (d.go:14)	CMPQ	SP, 16(CX)
	0x000d 00013 (d.go:14)	JLS	76
	0x000f 00015 (d.go:14)	FUNCDATA	$0, gclocals·23e8278e2b69a3a75fa59b23c49ed6ad(SB)
	0x000f 00015 (d.go:14)	FUNCDATA	$1, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x000f 00015 (d.go:15)	MOVQ	"".foo(SB), AX
	0x0016 00022 (d.go:15)	MOVQ	(AX), CX
	0x0019 00025 (d.go:15)	MOVQ	"".x+8(FP), DX
	0x001e 00030 (d.go:15)	CMPQ	DX, CX
	0x0021 00033 (d.go:15)	JGE	$0, 66
	0x0023 00035 (d.go:18)	CMPQ	DX, $1048576
	0x002a 00042 (d.go:18)	JCC	$0, 59
	0x002c 00044 (d.go:18)	SHLQ	$4, DX
	0x0030 00048 (d.go:18)	LEAQ	8(AX)(DX*1), AX
	0x0035 00053 (d.go:18)	MOVQ	AX, "".~r1+16(FP)
	0x003a 00058 (d.go:18)	RET
	0x003b 00059 (d.go:18)	PCDATA	$0, $0
	0x003b 00059 (d.go:18)	CALL	runtime.panicindex(SB)
	0x0040 00064 (d.go:18)	UNDEF
	0x0042 00066 (d.go:16)	MOVQ	$0, "".~r1+16(FP)
	0x004b 00075 (d.go:16)	RET
	0x004c 00076 (d.go:14)	CALL	runtime.morestack_noctxt(SB)
	0x0051 00081 (d.go:14)	JMP	0
```
