### ISSUE TITLE
affected/package: 

### ISSUE THREAD

**Issue by goranp13** [golang/go#57137]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.19.3

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
C:\Users\goran>go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=D:\goworkspace\bin
set GOCACHE=C:\Users\goran\AppData\Local\go-build
set GOENV=C:\Users\goran\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\goworkspace\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\goworkspace
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.19.3
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\goran\AppData\Local\Temp\go-build3586402992=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

package main

import "fmt"

func main() {
	fmt.Println("Hello from GO")
}

### What did you expect to see?

Hello from GO
after 1-2s of compiling
### What did you see instead?

Hello from GO
after 19 s of compiling

**Comment by mengzhuo** [comment]
The build time related to your PC's performance.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by goranp13** [comment]
I have hp elitebook g 840 with 32gb of memory. I have tried to compile
under wsl2 Ubuntu on the same machine and compilation is 1.5 sec.

**Comment by seankhliao** [comment]
Then it's your antivirus.
