### ISSUE TITLE
Compilation fails in OpenBSD 7.1

### ISSUE THREAD

**Issue by khezerberg** [golang/go#57148]
hello!
I apologize for the newbie question but I don't know why golang is not compiling from source on my OpenBSD system.
CPU: Intel(R) Core(TM)2 duo

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.7 openbsd/amd64
</pre>

### Does this issue reproduce with the latest release?

No, it does not reproduce with the latest release. 
I get a goroutine error related to test: os/signal with the latest release.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/somestring/.cache/go-build"
GOENV="/home/somestring/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="openbsd"
GOINSECURE=""
GOMODCACHE="/home/somestring/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="openbsd"
GOPATH="/home/somestring/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/openbsd_amd64"
GOVCS=""
GOVERSION="go1.17.7"
GCCGO="gccgo"
AR="ar"
CC="cc"
CXX="c++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostigs -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3405912898=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

$ git clone https://go.googlesource.com/go goroot
$ cd goroot/
$ git checkout go1.19.1
$ cd src/
$ ./all.bash

### What did you expect to see?

I expected the program to compile and pass all tests just fine.

### What did you see instead?

....
```shell
ok            cmd/internal/obj/s390x    0.022s
ok            cmd/internal/obj/x86        14.082s
ok            cmd/internal/objabi          0.220s
ok            cmd/internal/pkgpath      0.107s
ok            cmd/internal/quoted        0.020s
ok            cmd/internal/src                0.105s
ok            cmd/internal/sys               0.028s
ok            cmd/internal/test2json    0.308s
--- FAIL:  TestCGOLTO  (0.00s)
     ---  FAIL: TestCGOLTO/gcc-0  (2.36s)
           cgo_test.go:116:   go build
           cgo_test.go:118:  #  runtime/cgo
                   /tmp//ccwNcpT7.s:  Assembler messages:
                   /tmp//ccwNcpT7.s:2: Fatal error:  Bad .section directive:  want a,l,w,x,M,S,G,T in string
           cgo_test.go:121:   go build failed:  exit status 2
           cgo_test.go:139:  failed
    ---   FAIL:  TestCGOLTO/gcc-1  (1.30s)
           cgo_test.go:116:  go build
           cgo_test.go:118:  #  runtime/cgo
                   /tmp//cc4P37fD.s: Assembler messages:
                   /tmp//cc4P37fD.s:2:  Fatal error:  Bad .section directive:  want a,l,w,x,M,S,G,T in string
           cgo_test.go:121:  go build failed:  exit status 2
           cgo_test.go:139: failed
FAIL
FAIL    cmd/link            33.468s
ok        cmd/link/internal/benchmark       0.066s
ok        cmd/link/internal/ld            21.161s
ok        cmd/link/internal/loader                0.180s
ok        cmd/nm        7.045s
ok        cmd/objdump        10.098s
ok        cmd/pack                4.866s
ok        cmd/pprof              5.856s
ok        cmd/trace               4.317s
ok        cmd/vet   24.764s
FAIL
go  tool  dist:  Failed:  exit  status  1
```

**Comment by ianlancetaylor** [comment]
Unless I'm missing something, this looks like a problem with your C compiler.  The file for which the error is being reported is being generated by the C compiler.  The `.section` directive is coming from the C compiler, not from Go.

**Comment by khezerberg** [comment]
but I don't know what is wrong with my compiler?
I have egcc (version 11.2.0), which is an OpenBSD port of gcc and I also have cc version 13.0.0. 

How do I get or edit this ```shell .section``` directive?
Thank you so much for your time.

**Comment by ianlancetaylor** [comment]
I think that what is interesting here is that the test uses the `-flto` option.  Try running `egcc -flto hello.go` and see if you get the same error.  If you do, there is a problem with the C compiler.  We can't help you with that.

**Comment by bcmills** [comment]
(CC @golang/openbsd)

**Comment by qbit** [comment]
@khezerberg `go env` is showing `CC="cc"` which defaults to clang 13.0.0. What is the output of `cc -v` in the shell you are doing the build from?

**Comment by khezerberg** [comment]
> I think that what is interesting here is that the test uses the `-flto` option. Try running `egcc -flto hello.go` and see if you get the same error. If you do, there is a problem with the C compiler. We can't help you with that.

When I do that it prints this to stdout:
```shell
egcc: error: hello.go: Go compiler not installed on this system
```
But when I type ``` $ go version``` : 
```shell
go version go1.17.7 openbsd/amd64
```
but I don't understand, where did you get the '-flto' option from?

**Comment by khezerberg** [comment]
> @khezerberg `go env` is showing `CC="cc"` which defaults to clang 13.0.0. What is the output of `cc -v` in the shell you are doing the build from?

when I type in ```$ cc -v ``` I get the following output:
```shell
OpenBSD clang version 13.0.0
Target: amd64-unknown-openbsd7.1
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by khezerberg** [comment]
wait I just thought of something. 
Could it perhaps be looking for 'gcc' or 'g++' but it instead only finds egcc and eg++ and does not recognize them as being practically the same thing? sorry I don't know. I'm such a noob.

**Comment by ianlancetaylor** [comment]
My apologies, I mean to write `egcc -flto hello.c`, where the file `hello.c` comtains a simple hello, world program written in C.

**Comment by khezerberg** [comment]
wait so if I cannot fix the compiler (because I'm noob), can I still compile go with clang (which is already installed in my system) or llvm (which I would need to install in my system)?

How would I go about doing this? Do I need to edit a file on my local copy of golang? 
for example to make it look for clang or llvm instead of gcc (egcc in my case).

**Comment by ianlancetaylor** [comment]
@khezerberg I'm sorry, I don't know what egcc is and I don't know who maintains it.

Yes, you can use Go with clang, by setting `CC=clang` in the environment.
