### ISSUE TITLE
Using function-local generic types of the same name produces a SIGSEGV

### ISSUE THREAD

**Issue by amahiwa-jp** [golang/go#57158]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/amahiwa/.cache/go-build"
GOENV="/home/amahiwa/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/amahiwa/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/amahiwa/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.19"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.19/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/amahiwa/dev/projects/tmp/bug1/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3279347530=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

After defining two function-local generic structure of the same name, the code accessing the structures produces a SIGSEGV.
If types have different names or if they are not generic, then the error goes away.
Link to the example: https://go.dev/play/p/IwVJFu13i2x

(Note that it doesn't blow up on Go Playground, just displays a wrong output. However it does reproduce on my local machine and [Compiler Explorer:](url) 

<details><summary>Code MWE</summary>

```go

package main

import (
	"fmt"
	"sync"
)

func f1(wg *sync.WaitGroup) {
	type caze[U any] struct {
		data         []U
		defaultValue U
		expected     []U
	}
	tcase := caze[int]{
		data:         []int{1, 2, 3},
		defaultValue: 0,
	}

	fmt.Println(tcase)
	wg.Done()
}

func f2(wg *sync.WaitGroup) {
	type caze[U any] struct {
		data     []U
		expected []U
	}
	tcase := caze[int]{
		data:     []int{1, 2, 3},
		expected: []int{2, 4, 6},
	}

	fmt.Println(tcase)
	wg.Done()
}

func main() {
	var wg sync.WaitGroup
	wg.Add(2)
	go f1(&wg)
	go f2(&wg)
	wg.Wait()
}
```
</details>

### What did you expect to see?
No error and correct `fmt.Println` output

### What did you see instead?
Either a SIGSEGV or an incorrect output

**Comment by seankhliao** [comment]
fixed on tip
