### ISSUE TITLE
encoding/json: Error when use with append

### ISSUE THREAD

**Issue by mcat1997** [golang/go#57163]
both happend in go1.14 and go1.19

func main() {

	var onlyPlatformIDS []int
	jsonStr := "[16,803]"
	_ = json.Unmarshal([]byte(jsonStr), &onlyPlatformIDS)

	platformIDS := append(onlyPlatformIDS, 3)
	platformIDS[1] = 804

	fmt.Println(onlyPlatformIDS)
	fmt.Println(platformIDS)
}

Code like this. It print 

[16 804]
[16 804 3]

func main() {

	var onlyPlatformIDS []int
	//jsonStr := "[16,803]"
	//_ = json.Unmarshal([]byte(jsonStr), &onlyPlatformIDS)
	onlyPlatformIDS = []int{16, 803}

	platformIDS := append(onlyPlatformIDS, 3)
	platformIDS[1] = 804

	fmt.Println(onlyPlatformIDS)
	fmt.Println(platformIDS)
}

Code like this. It print

[16 803]
[16 804 3]

Why?

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
