### ISSUE TITLE
affected/package: cgo

### ISSUE THREAD

**Issue by rakesh-mahapatra** [golang/go#57167]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.18.4
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\mahapr1\AppData\Local\go-build
set GOENV=C:\Users\mahapr1\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\mahapr1\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\mahapr1\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.18.4
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\mahapr1\AppData\Local\Temp\go-build1568680846=/tmp/go-build -gno-record-gcc-switches

### What did you do?
Call to C.free(unsafe.Pointer()) is crashing.
I'm calling C APIs defined in another C library. The C API returns a ApiResponse pointer which populates error code and message.
After using this, when I call C.free to free the allocated memory, it crashes

main.c
======

ApiResponsePtr create_instance(char * property, char ** instanceID)
{

	ApiResponsePtr ptr = NULL;
	ptr = (ApiResponse *) calloc(1, sizeof(ApiResponse));
	
	// Internally it allocates memory for instanceID and fill ID
	GetInstaceID(instanceID)
	
	// Do other stuff
	
	// Fill ptr
	ptr->status = 0;
	ptr->msg = //populate status message by allocating memory
	
	return prt
}

main.go
=======

package main

/*
#cgo pkg-config: --with-path=./pc_files libmain
#cgo CFLAGS: -g -Wall
#cgo CFLAGS: -I./include/include
#cgo LDFLAGS: -L./lib
#include <stdlib.h>
#include "main.h"
*/
import "C"
import (
	"log"
	"os"
	"unsafe"
)

func main() {

	var apiResponse *C.ApiResponse
	var instanceID *C.char
	
	property := C.CString(".\\properties")
	
	apiResponse = C.create_instance(property, &instanceID)
	
	// I'm able to access data from apiResponse
	status := int32(apiResponse.status)
	
	// When I call free of the allocated memory, its crashing
	C.free(unsafe.Pointer(apiResponse))
}	
	

### What did you expect to see?
I expect it to free the allocated memory

### What did you see instead?
exit status 0xc0000374
PS C:\Users\mahapr1\cgo-integration> GOVERSION
PS C:\Users\mahapr1\clp-cgo-integration> go run "c:\Users\mahapr1\clp-cgo-integration\main.go"
main.go:84: created instance ID :  9e3a2818-cff9-4511-b25a
main.go:86:
Exception 0xc0000005 0x0 0xffffffffffffffff 0x7ff85bcd6fbb
PC=0x7ff85bcd6fbb
signal arrived during external code execution

runtime.cgocall(0x159110, 0xc000107e48)
        C:/Program Files/Go/src/runtime/cgocall.go:157 +0x4a fp=0xc000107e20 sp=0xc000107de8 pc=0xc392a
main._Cfunc_free(0x25edb1d5e50)
        _cgo_gotypes.go:452 +0x4e fp=0xc000107e48 sp=0xc000107e20 pc=0x1562ae
main.main.func5(0x0?)
        c:/Users/mahapr1/clp-cgo-integration/main.go:88 +0x3a fp=0xc000107e80 sp=0xc000107e48 pc=0x15745a
main.main()
        c:/Users/mahapr1/clp-cgo-integration/main.go:88 +0x4a5 fp=0xc000107f80 sp=0xc000107e80 pc=0x156845
runtime.main()
        C:/Program Files/Go/src/runtime/proc.go:250 +0x1fe fp=0xc000107fe0 sp=0xc000107f80 pc=0xf6ade
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000107fe8 sp=0xc000107fe0 pc=0x11d501
rax     0x25edb1d3300
rbx     0x6172676f72505c3a
rcx     0x2b40
rdi     0x0
rsi     0x25ed9870000
rbp     0x0
rsp     0xf338bff4a0
r8      0x60da8c55
r9      0x0
r10     0xc000092001
r11     0x53
r12     0x0
r13     0x25edb1d5e50
r14     0x25edb1d5e40
r15     0x1
rip     0x7ff85bcd6fbb
rflags  0x10206
cs      0x33
fs      0x53
gs      0x2b
exit status 2

**Comment by rakesh-mahapatra** [comment]
[cgo-to-c-load-dll.zip](https://github.com/golang/go/files/10194663/cgo-to-c-load-dll.zip)
I've attached a working code which can be run as it is. Please note, I've also packaged main.dll which I created a DLL for my C code. With my go code, I'm trying to invoke function exposed from C library.

**Comment by rakesh-mahapatra** [comment]
@seankhliao I've attached the required self contained code and library. Can you please check this

**Comment by seankhliao** [comment]
It's hard to tell if you're violating pointer passing rules, eg with instanceID.

I think this looks more like a question of how to use CGo rather than a concrete bug.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
