### ISSUE TITLE
access: may-start-trybots

### ISSUE THREAD

**Issue by felixge** [golang/go#57164]
See https://go.dev/wiki/GerritAccess

I'm requesting `may-start-trybots` permissions to test CLs before submitting them and save back and forth with the Go maintainers.

Group URL: https://go-review.googlesource.com/#/admin/groups/1030,members
Gerrit Email: felix.geisendoerfer@datadoghq.com

**Comment by seankhliao** [comment]
cc @golang/release

**Comment by prattmic** [comment]
Hi Felix,

Thank you for your contributions and for requesting Trybots access! I've added you to the `may-start-trybots` group, so you should be able to do so now.

As you've likely read at https://golang.org/wiki/GerritAccess#trybot-access-may-start-trybots, please be sure to at least skim CLs before starting a Trybot run.

Let us know if you have any questions or issues with it, and thanks again!
