### ISSUE TITLE
syscall: fork blocks the process

### ISSUE THREAD

**Issue by pierrre** [golang/go#5717]
<pre>What steps will reproduce the problem?
<a href="http://play.golang.org/p/cbQIfyHasD">http://play.golang.org/p/cbQIfyHasD</a>

What is the expected output?
Low value for http request duration

What do you see instead?

High value (200-300ms) with GOMAXPROCS=1
Low value (1ms) with GOMAXPROCS=2, but os/exec.Command.Run() takes 300ms

If the command is not executed, the code is fast.

Which compiler are you using (5g, 6g, 8g, gccgo)?
6g? (Linux, 64 bits)

Which operating system are you using?
Ubuntu 13.04 64 bits

Which version are you using?  (run 'go version')
go version go1.1.1 linux/amd64

Please provide any additional information below.
Google Groups:
<a href="https://groups.google.com/forum/?fromgroups=#">https://groups.google.com/forum/?fromgroups=#</a>!topic/golang-nuts/58_jSKTeSzE</pre>

**Comment by bradfitz** [comment]
I'm going to close this in favor of the more active #5838 currently targeting Go 1.9.
