### ISSUE TITLE
go/types: Cannot return `T` from method receiving `Generic[T]`

### ISSUE THREAD

**Issue by fschuetz04** [golang/go#57182]
### What version of Go are you using (`go version`)?

Go Playground with Go 1.18, 1.19, and dev branch.

### Does this issue reproduce with the latest release?

Yes.

### What did you do?

See <https://go.dev/play/p/fCO1GDA_oZj?v=gotip> for an example.

I defined a generic type, e. g.:

```go
type Generic[T any] struct{}
```

Then I wanted to add a method receiving an instantiation of this generic type and returning `T`, e. g.:

```go
func (_ Generic[uint8]) Value() uint8 {
	return 0
}
```

### What did you expect to see?

I would expect the program to build without errors.

### What did you see instead?

Adding the method leads to an error when building the program:

```
cannot use 0 (untyped int constant) as uint8 value in return statement
```

The program only builds if the return type of the method is different from `T`.

**Comment by seankhliao** [comment]
this doesn't do what you think it does.
methods can't be on specific instantiations.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by timothy-king** [comment]
`func (_ Generic[uint8]) Value() uint8 { return 0 }` does not mean what you think it means. This is the same as `func (_ Generic[T]) Value() T { return 0 }`. You are overloading the name `uint8` with a type parameter named "uint8" that is constrained to be an `any`. This is the meaning of the "uint8" return value. Hence the very confusing error message.

**Comment by timothy-king** [comment]
I vaguely recall there was a suggested vet check for this.

**Comment by seankhliao** [comment]
the check was deemed premature at the time #48123

**Comment by ianlancetaylor** [comment]
https://go.dev/doc/faq#types_in_method_declaration
