### ISSUE TITLE
affected/package: go1.19.4

### ISSUE THREAD

**Issue by jonnysu** [golang/go#57183]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.19.4

</pre>

### Does this issue reproduce with the latest release?

not sure

### What operating system and processor architecture are you using (`go env`)? 

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env  ubuntu

</pre></details>

### What did you do?
i want to use spacevim to develop golang software. when i use gd function to open the definiation page. the ssh will going down for half an hour when i broswer the page for a while.

the old version have no such problem such as go 1.15.*

**Comment by seankhliao** [comment]
doesn't sound like a go issue

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
