### ISSUE TITLE
x/vuln: Cannot install govulncheck anymore since yesterday

### ISSUE THREAD

**Issue by nphmuller** [golang/go#57189]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.19.4 darwin/arm64

</pre>

### Does this issue reproduce at the latest version of golang.org/x/vuln?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/nphmuller/Library/Caches/go-build"
GOENV="/Users/nphmuller/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/nphmuller/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/nphmuller/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.4"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/l5/4r4nnb4j1_79bc7w3swx85980000gn/T/go-build549177952=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

> go install golang.org/x/vuln/cmd/govulncheck@latest

### What did you expect to see?

Succesfull install (it worked before yesterday)

### What did you see instead?

After a while it times out with this error:

> go: golang.org/x/vuln/cmd/govulncheck@latest: no matching versions for query "latest"

I also tried the other 2 version on this page: https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck?tab=versions
> v0.0.0-20221208170415-d970d6cd0f6e
> 
v0.0.0-20221208180742-f2dca5ff4cc3

**Comment by seankhliao** [comment]
Duplicate of #57185
