### ISSUE TITLE
net/http: transferWriter.doBodyCopy() calls io.Copy() resulting in many buffer allocations 

### ISSUE THREAD

**Issue by mmatczuk** [golang/go#57202]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.19.4 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/michal/Library/Caches/go-build"
GOENV="/Users/michal/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/michal/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/michal/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/michal/sdk/go1.19.4"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/michal/sdk/go1.19.4/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.4"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/7q/nyynjpwj5p19npby48ykjpx00000gn/T/go-build3980036370=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I have HTTP proxy server proxying plain HTTP 1.1 requests based on [google/martian](https://github.com/google/martian). When I profile the memory allocations I see that `transferWriter.doBodyCopy()` calls `io.Copy()` resulting in many buffer allocations. The profile graph is attached below.

<img width="735" alt="Screenshot 2022-12-09 at 13 40 11" src="https://user-images.githubusercontent.com/1617930/206704740-881bfe68-9e81-4196-8ae5-27150bb35d95.png">

I think `doBodyCopy()` could use `copyBufPool` we have in [response.ReadFrom()](https://github.com/golang/go/blob/e76c87b1915cfbd0d4f22c6401987948af18e8c5/src/net/http/server.go#L570) to avoid the allocations.

**Comment by neild** [comment]
I wonder if io.Copy should use a pool to allocate buffers.
