### ISSUE TITLE
There is a mistake. Please help me see. What is the reason? How to solve it?

### ISSUE THREAD

**Issue by xiaokentrl** [golang/go#57219]
### I want to download the specified file in an infinite loop without interruption
Error content

down/2022-12-10_05-53-55-268395800-5d9c0c0b5c6af6e7.pdf
down/2022-12-10_05-53-55-315459500-ea819f170238afb2.pdf
down/2022-12-10_05-53-55-350170800-4bb778310261f11c.pdf
down/2022-12-10_05-53-55-455923600-b65483e33ebf934d.pdf
down/2022-12-10_05-53-55-471081900-af3a3d86895f5a4f.pdf
down/2022-12-10_05-53-55-578222800-826d1ca9b7b15f9c.pdf
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0xa41f15]

goroutine 701 [running]:
main.testDown()
        E:/GoProject/src/main.go:30 +0x55
created by main.getData
        E:/GoProject/src/main.go:50 +0x29
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0xa41f15]

goroutine 693 [running]:
main.testDown()
        E:/GoProject/src/main.go:30 +0x55
created by main.getData
        E:/GoProject/src/main.go:50 +0x29
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0xa41f15]

goroutine 748 [running]:
main.testDown()
        E:/GoProject/src/main.go:30 +0x55
created by main.getData
        E:/GoProject/src/main.go:50 +0x29

My Code

```golang

package main

import (
	"crypto/rand"
	"fmt"
	"io"
	"net/http"
	"os"
	"strconv"
	"time"
)

func random_filename() (s string, err error) {
	b := make([]byte, 8)
	_, err = rand.Read(b)
	if err != nil {
		return
	}
	s = fmt.Sprintf("%x", b)
	return
}

func testDown() {
	pdfUrl := "http://www.xxxxxx.cn/xeec/cdrr/ccrr7899.pdf"
	// Get the data
	resp, err := http.Get(pdfUrl)
	if err != nil {

	}
	defer resp.Body.Close()
	name, err := random_filename()
	if err != nil {

	}
	fileName := "down/" + time.Now().Format("2006-01-02_15-04-05-") + strconv.Itoa(time.Now().Nanosecond()) + "-" + name + ".pdf"
	println(fileName)
	out, err := os.Create(fileName)
	if err != nil {

	}
	defer out.Close()	
	_, err = io.Copy(out, resp.Body)
	if err != nil {
		panic(err)
	}
}

func getData() {
	for i := 0; i < 500; i++ {
		go testDown()
	}
}

func main() {
	for {
		getData()
		time.Sleep(1000 * time.Second)
	}

}


```

**Comment by xiaokentrl** [comment]
I hope to download a PDF file wirelessly all the time. How can I write code so that the code will not stop running?

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
