### ISSUE TITLE
x/net/websocket: remove Gorilla recommendation in docs

### ISSUE THREAD

**Issue by percybolmer** [golang/go#57228]
### What version of Go are you using (`go version`)?
1.18

### Does this issue reproduce with the latest release?
No Issue

### What did you do?
Read the docs

### What did you expect to see?
How to use the x/net/websocket library

### What did you see instead?
https://github.com/golang/net/blob/e1ec361d0b39748d321472b2be7298211e05a3b6/websocket/websocket.go#L11
Gorilla recommendation which is now archived

**Comment by seankhliao** [comment]
archived: https://github.com/gorilla/websocket

cc @neild @ianlancetaylor
