### ISSUE TITLE
x/pkgsite: package removal request for github.com/MIN-Group/minlib 

### ISSUE THREAD

**Issue by linlih** [golang/go#57227]
### What is the path of the package that you would like to have removed?
https://pkg.go.dev/github.com/MIN-Group/minlib

### Are you the owner of this package?
Yes

### What is the reason that you could not retract this package instead?
The package is made private, please delete the web page about the package, thx.

**Comment by linlih** [comment]
Does anyone help to resolve this issue ?

**Comment by findleyr** [comment]
This was done in #57024. Thanks for your patience.
