### ISSUE TITLE
x/tools/gopls: install failed, error obtaining buildID for go tool compile: signal: killed

### ISSUE THREAD

**Issue by hongliang5316** [golang/go#57239]
### gopls version

go: downloading golang.org/x/tools/gopls v0.10.1

### go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/hl/Library/Caches/go-build"
GOENV="/Users/hl/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/hl/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/hl/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io,direct"
GOROOT="/Users/hl/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/hl/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.19.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/m_/fq5fc7yn6pv5vv3yhkpx8hzh0000gn/T/go-build1979055502=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?

go install -v golang.org/x/tools/gopls@latest                      
go: downloading golang.org/x/tools/gopls v0.10.1
go: downloading golang.org/x/tools v0.4.0
go: downloading golang.org/x/tools v0.2.1-0.20221101170700-b5bc717366b2
go: downloading github.com/sergi/go-diff v1.1.0
go: downloading honnef.co/go/tools v0.3.3
go: downloading mvdan.cc/gofumpt v0.3.1
go: downloading mvdan.cc/xurls/v2 v2.4.0
go: downloading golang.org/x/mod v0.6.0
go: downloading golang.org/x/text v0.4.0
go: downloading golang.org/x/exp/typeparams v0.0.0-20220722155223-a9213eeb770e
go: downloading github.com/google/go-cmp v0.5.8
go: downloading golang.org/x/exp v0.0.0-20220722155223-a9213eeb770e
go: downloading golang.org/x/sys v0.1.0
go: downloading golang.org/x/sync v0.0.0-20220722155255-886fb9371eb4
go: downloading golang.org/x/vuln v0.0.0-20221010193109-563322be2ea9
go: downloading github.com/BurntSushi/toml v1.2.0
go: error obtaining buildID for go tool compile: signal: killed
go: error obtaining buildID for go tool compile: signal: killed
go: error obtaining buildID for go tool compile: signal: killed
go: error obtaining buildID for go tool compile: signal: killed
go: error obtaining buildID for go tool compile: signal: killed
go: error obtaining buildID for go tool compile: signal: killed

**Comment by bcmills** [comment]
`signal: killed` is usually what we see if a process is killed due to the system running out of memory.

@hongliang5316, is this failure consistently reproducible for you? If so, can you confirm how much free RAM you have while `go install` is running?

**Comment by hongliang5316** [comment]
Thank you for your answer, it is a must now, the memory can be confirmed to be sufficient, now v0.10.1 can be installed successfully, but the operation will fail 100%

**Comment by hyangah** [comment]
@hongliang5316 does it have sufficient memory to load and run gopls?

**Comment by hongliang5316** [comment]
@hyangah 
Yes, the computer has at least 3GB of free memory when running, I will spend time debugging this later, and I will give feedback in time if there are any problems, thank you.
