### ISSUE TITLE
x/crypto: requires old version of x/net

### ISSUE THREAD

**Issue by duncanharris** [golang/go#57245]
Latest `golang.org/x/crypto` requires `v0.3.0` of `golang.org/x/net` but the latest of the latter is `v0.4.0`

https://cs.opensource.google/go/x/crypto/+/master:go.mod :
```
module golang.org/x/crypto

go 1.17

require (
	golang.org/x/net v0.3.0
	golang.org/x/sys v0.3.0
	golang.org/x/term v0.3.0
)

require golang.org/x/text v0.5.0 // indirect
```

Highlighted because seems to cause my vulnerability checker to report an issue.

**Comment by heschi** [comment]
Nothing in crypto uses the vulnerable package in net, so I would consider this a false positive from the vulnerability checker. The dependency will be updated in a few weeks when the next versions are tagged, and in the meantime you can upgrade yourself if you want.
