### ISSUE TITLE
 go test: ld: library not found for -lpthread

### ISSUE THREAD

**Issue by tiger-guo** [golang/go#57242]
### What version of Go are you using (`go version`)?

<pre>
go version: go1.18.9 darwin/amd64
macOS: 13.0.1 (22A400) 
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/Users/xxxxx/Code/go/bin"
GOCACHE="/Users/xxxx/Library/Caches/go-build"
GOENV="/Users/xxxxx/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/xxxx/Code/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/xxx/Code/go"
GOPRIVATE=""
GOPROXY="xxxx"
GOROOT="/usr/local/Cellar/go@1.18/1.18.9/libexec"
GOSUMDB="xxxx"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go@1.18/1.18.9/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18.9"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="xxxx"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_g/pkqs0xhs7l7b0kb0zspg8z3c0000gn/T/go-build1190468193=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

```json
go test
```

### What did you see instead?

```json
> go test
# runtime/cgo
ld: library not found for -lpthread
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
FAIL    hcm/pkg/dal/dao [build failed]
```

**Comment by tiger-guo** [comment]
After upgrading the Mac version, it is found that the go test execution error is as follows, is there any solution?

Thank you!

**Comment by seankhliao** [comment]
this is an issue with your system / c linker
presumably you need to upgrade xcode / command-line-tools after an os upgrade

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
