### ISSUE TITLE
gofmt: Increase readability by adding spacing

### ISSUE THREAD

**Issue by raisoftware** [golang/go#57249]
Hello,

Increase readability by adding spacing. Spacing makes easy to visually tokenize symbols, especially for those of use with imperfect vision. Even with syntax highlighting it is a lot easier to read code when spaces are added.

1. For ease of reading, function calls should have spaces between the parentheses and the arguments.
Example:
Nice: `SayHi( HelloFunc, and, world )`
Ugly: `SayHi(HelloFunc,and,world)`
Explanation: SayHi and HelloFunc are two completely different symbols, why should they mingled together?
Consistency: Most other formatting rules use spaces, for the better. Examples: commas add a space after them, but parentheses do not, even if the comma glyph has more empty space in it, so it is easier to tell apart, and it is less likely to be confounded with a I. Same for binary operators, they have spaces around them.

So please add a space after the opening parenthesis and a space before the closing parenthesis.

2. Add a breaking space before and after function definitions:
Nice:
```
func Hello() string {
    return "Hello"
}

var aFunc = " " 

func World() string {
    return "World"
}
```

Ugly:
```
func Hello() string {
    return "Hello"
}
var aFunc = " " 
func World() string {
    return "World"
}
```

**Comment by seankhliao** [comment]
1. This will churn nearly every line of code for very little gain as this is standard style in Go and almost every other language. It is safe to say this won't happen.
2. already happens

**Comment by raisoftware** [comment]
Thanks for the fast answer.
1. So please consider it for Go 2. The formatting rule change makes sense by itself, for the many people who are visually impaired, which most programmers are, after a certain age. The fact that it would impact so much code actually makes our discussion worthwhile.
2. It does for var followed by func, but not for func followed by func:
`package Test

var sa = []string{"", "b", "c"}

func HelloFunc() string {
        hello := "Hello"
        return hello
} // will not be followed by a breaking space
func SayHi(prefix func() string, b string, c string) string {
        return prefix() + " World"
}`

**Comment by seankhliao** [comment]
see #22337
