### ISSUE TITLE
cmd/compile: No BCE for x&(len(p)-1)

### ISSUE THREAD

**Issue by greatroar** [golang/go#57243]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19 linux/amd64
$ gotip version
go version devel go1.20-9b8750f53e Sat Dec 10 00:35:24 2022 +0000 linux/amd64
</pre>

### What did you do?

Distilled from a custom hash table:

```go
package ht

func get(p []string, h uint) string {
	if len(p) == 0 {
		return ""
	}
	i := h & uint(len(p)-1)
	return p[i]
}
```

### What did you expect to see?

BCE for the expression p[i]. From the if statement, the compiler knows that len(p) > 0, so len(p)-1 is non-negative and in bounds, and so is h&(len(p)-1).

### What did you see instead?

./bce.go:8:10: Found IsInBounds

It doesn't seem to matter if I put the cast on h or change the length check to <=0.

**Comment by RuinanSun** [comment]
I would like to have a try on this. Maybe need a little bit changes on [CL 419555](https://go-review.googlesource.com/c/go/+/419555)

**Comment by Jorropo** [comment]
Just so you know, this is harder than it looks currently the facts table is filled in by OpCode specific knowlege first, then CFG is explored.

`prove` currently know how to handle everything in this example except the `OpSub64` value.
It is rarely true that the result of a subtraction is always smaller or equal than the first input (it only happen if you prove that the second operand is always smaller or equal than the first one in the first place, such as in this case).

There are many ways you could solve this, I'm just saying this isn't a trivial thing like it might look like.
