### ISSUE TITLE
x/pkgsite: package removal request for github.com/immutable/imx-core-sdk-golang/examples/workflows

### ISSUE THREAD

**Issue by suluvai** [golang/go#57256]
### What is the path of the package that you would like to have removed?

github.com/immutable/imx-core-sdk-golang/examples/workflows?tab=versions

### Are you the owner of this package?

yes

### What is the reason that you could not retract this package instead?

The released package should not exist and we do not want users to use any version of it. The whole structure is changed and the old go.mod file is not accessible.

**Comment by findleyr** [comment]
For technical reasons it appears this exclusion did not work. We're investigating.

CC @jamalc

**Comment by findleyr** [comment]
Duh, forgot that cache invalidation is one of the two hard problems! (page was still cached).

This is done now :)
