### ISSUE TITLE
cmd/compile: internal compiler error: 'weak': unhandled stmt ASOP

### ISSUE THREAD

**Issue by maoxiaojie1** [golang/go#57255]
### What version of Go are you using (`go version`)?
go version go1.19 linux/amd64
<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
linux  amd64
$ go env

</pre></details>

### What did you do?
i run this cmd `go test -fuzztime 10s -fuzz ./impl`

### What did you see instead?
# github.com/jcmturner/gokrb5/v8/crypto/rfc3961
../../go/pkg/mod/github.com/jcmturner/gokrb5/v8@v8.4.2/crypto/rfc3961/keyDerivation.go:144:15: internal compiler error: 'weak': unhandled stmt ASOP

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new

**Comment by thanm** [comment]
Thanks for the report.

Would you please post detailed instructions on how to reproduce this? You have this as the command you ran:

```
go test -fuzztime 10s -fuzz ./impl
```

but I don't know where to find "./impl" (it doesn't seem to be part of the github.com/jcmturner/gokrb5 repo).

Thanks.

**Comment by cuonglm** [comment]
Duplicated of https://github.com/golang/go/issues/56105
