### ISSUE TITLE
x/pkgsite: package removal request for cloud.2linfo.fr/gitea/2linfo/golibarr

### ISSUE THREAD

**Issue by adlmr** [golang/go#57260]
### What is the path of the package that you would like to have removed?

cloud.2linfo.fr/gitea/2linfo/golibarr
 
### Are you the owner of this package?

I am the Owner of 2LINFO, the company which owns cloud.2linfo.fr/gitea/ and subsequent projects
 
### What is the reason that you could not retract this package instead?

This project is internal and our board didn't ruled on the open-source nature of the project at this time.
This package was published by a former employee who used an open-source licence without the consent of the management team.
Please remove it from your package list.

**Comment by findleyr** [comment]
Hi, to make our investigation easier is there any information you can point us to to verify that you own this package / host?

(I don't doubt it, but we generally verify ownership)
