### ISSUE TITLE
compiler

### ISSUE THREAD

**Issue by lmau2** [golang/go#57267]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Problem can also be reproduced on https://go.dev/play using 1.19

### What did you do?
Try out example in language Spec on "Conversions from slice to array or array pointer"

s := make([]byte, 2, 4)

a0 := [0]byte(s)
a1 := [1]byte(s[1:])     // a1[0] == s[1]
a2 := [2]byte(s)         // a2[0] == s[0]

https://go.dev/play/p/Cf6xkGTGbK0

### What did you expect to see?

Program with fragment to compile

### What did you see instead?

./prog.go:12:16: cannot convert s (variable of type []byte) to type [2]byte

Go build failed.

**Comment by timothy-king** [comment]
Support for conversions from slice to array is coming in 1.20. Release notes draft: https://github.com/golang/go/blob/master/doc/go1.20.html#L32
