### ISSUE TITLE
proposal: generics: support direct type-casting

### ISSUE THREAD

**Issue by gucio321** [golang/go#57266]
Lets imageine the following code:

```go
package main

import (
	"fmt"
)

func cast[T1, T2 any](in T1) T2 {
	return T2(in)
}

func main() {
	var x int16 = 80
	result := cast[int16, int8](x)
	fmt.Println(result)
}
```

in fact, casting `int16` directly into `int8` should be allowed, shouldn't it?

Well, the perfect solution here should be to check if T1 could be directly converted into T2 by
```go
v, ok := T2(in)
```

**Comment by seankhliao** [comment]
Given the constraint `T1, T2 any`, any code you write has to be applicable to any possible type parameter passed in.
If you're actually working with more constrained types, they should be encoded in constraints.
For the `ok` check, sounds like you actually want interfaces.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
