### ISSUE TITLE
x/website: typo in covdata invocation

### ISSUE THREAD

**Issue by seankhliao** [golang/go#57268]
On the coverage page: https://go.dev/testing/coverage/
Under [Reporting percent statements covered
](https://go.dev/testing/coverage/#reporting-percent-statements-covered)

There's 

> go tool covdata -i=<directory> percent

Which should be 

> go tool covdata percent -i=<directory>

cc @thanm

**Comment by thanm** [comment]
Thanks for the report. I will send a CL.
