### ISSUE TITLE
cmd/compile: the loong64  intrinsic for CompareAndSwapUint32 function needs to sign extend its "old" argument.

### ISSUE THREAD

**Issue by abner-chenc** [golang/go#57282]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.20-b16e94d13d Mon Dec 12 23:10:52 2022 +0000 linux/loong64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

```
package main

import (
	"fmt"
	. "sync/atomic"
)

const (
	_magic = 0xfbcdefaf
)

func main() {
	var x struct {
		before uint32
		i      uint32
		after  uint32

		o uint32
		n uint32
	}

	x.before = _magic
	x.after = _magic

	for t := uint32(0x7FFFFFF0); t < 0x80000003; t += 1 {
		x.i = t + 0
		x.o = t + 0
		x.n = t + 1

		if !CompareAndSwapUint32(&x.i, x.o, x.n) {
			panic(fmt.Sprintf("should have swapped %#x %#x", x.o, x.n))
		}

		if x.i != x.n {
			panic(fmt.Sprintf("wrong x.i after swap: x.i=%#x x.n=%#x", x.i, x.n))
		}

		if x.before != _magic || x.after != _magic {
			panic(fmt.Sprintf("wrong magic: %#x _ %#x != %#x _ %#x", x.before, x.after, _magic, _magic))
		}
	}
}
```

### What did you expect to see?
<pre>
</pre>
(i.e. no output)

### What did you see instead?
```
panic: should have swapped 0x80000000 0x80000001

goroutine 1 [running]:
main.main()
	/home/chenguoqi/atomic.go:31 +0x31c
```

**Comment by abner-chenc** [comment]
@golang/loong64

**Comment by wdvxdr1123** [comment]
I reproduced this issue on linux/riscv64.

**Comment by dr2chase** [comment]
Checked that it does NOT repro on ppc64le (seemed unlikely, however trust-but-verify).

**Comment by dr2chase** [comment]
@gopherbot please open backport issues.
