### ISSUE TITLE
x/pkgsite: package removal request for https://pkg.go.dev/github.com/zebon43/tempProto

### ISSUE THREAD

**Issue by zebon43** [golang/go#57283]
### What is the path of the package that you would like to have removed?

https://pkg.go.dev/github.com/zebon43/tempProto
 
### Are you the owner of this package?

Yes. And I have deleted the repo from gitHub.
 
### What is the reason that you could not retract this package instead?

I forgot to do the retract before deleting the repo.

**Comment by findleyr** [comment]
Done.
