### ISSUE TITLE
x/pkgsite: package removal request for github.com/jmandel1027/perspex

### ISSUE THREAD

**Issue by jmandel1027** [golang/go#57295]
### What is the path of the package that you would like to have removed?

https://pkg.go.dev/github.com/jmandel1027/perspex

 
 
 
### Are you the owner of this package?

Yes

 
### What is the reason that you could not retract this package instead?

unfortunately i made an error when changing my github username from `jay-manday` to `jmandel1027` I missed a spot updating my go.mod files. I tried retracting them but would like this project dropped permanently.

**Comment by findleyr** [comment]
Done.
