### ISSUE TITLE
cmd/compile: compute booleans without jumps

### ISSUE THREAD

**Issue by gopherbot** [golang/go#5729]
by **martisch@uos.de**:

<pre>What steps will reproduce the problem?

take:
<a href="http://play.golang.org/p/y2nj-Icl-j">http://play.golang.org/p/y2nj-Icl-j</a>

bench and notice the difference between an int that gets xor with 1 and a bool that gets
flipped

go test bench=&quot;.*&quot;
BenchmarkBoolFlip	2000000000	         1.93 ns/op
BenchmarkBoolFlipManual	2000000000	         1.92 ns/op
BenchmarkBoolXor	2000000000	         0.85 ns/op

This might be only a very minor performance improvement as such but it also has the side
effect to not require and use resources of the branch predictor.

What is the expected output?

would think flag=!flag gets compiled to (gcc for C does this too):
0013 (boolxor.go:8) XORQ    $1,AX

What do you see instead?

0013 (boolxor.go:8) JMP     ,16
0014 (boolxor.go:8) MOVQ    $1,AX
0015 (boolxor.go:8) JMP     ,9
0016 (boolxor.go:8) CMPB    AX,$0
0017 (boolxor.go:8) JEQ     ,14
0018 (boolxor.go:8) MOVQ    $0,AX

if jumps need to be done: reordering and eliminating the first jump just makes a nearly
unnoticeable improvement of 1ns in the bench on average (see FlipManual). 
0034 (boolxor.go:15) CMPB    AX,$0
0035 (boolxor.go:15) JEQ     ,38
0036 (boolxor.go:16) MOVQ    $0,AX
0037 (boolxor.go:15) JMP     ,30
0038 (boolxor.go:18) MOVQ    $1,AX

Which compiler are you using (5g, 6g, 8g, gccgo)?
6g

Which operating system are you using?
Mac OS X 10.8.4
Darwin 12.4.0 Darwin Kernel Version 12.4.0: Wed May  1 17:57:12 PDT 2013;
root:xnu-2050.24.15~1/RELEASE_X86_64 x86_64

Which version are you using?  (run 'go version')
go version devel +27baf5978be6 Tue Jun 18 15:26:15 2013 +1000 darwin/amd64

Notes:
If you think such minor code generation issues (few jumps to much here and there,
boolean expression simplifications) are better left to be done faster by gccgo and not
be special cased by normal go compiler please let me know.</pre>

**Comment by alexey-s-sidorov** [comment]
Bug author's results:

bench and notice the difference between an int that gets xor with 1 and a bool that gets
 flipped.

go test bench=".*"
 BenchmarkBoolFlip 2000000000 1.93 ns/op
 BenchmarkBoolFlipManual 2000000000 1.92 ns/op
 BenchmarkBoolXor 2000000000 0.85 ns/op

=======================================

My results:

 go test bench=".*"
 BenchmarkBoolFlip 2000000000 0.70 ns/op
 BenchmarkBoolFlipManual 2000000000 1.01 ns/op
 BenchmarkBoolXor 2000000000 0.71 ns/op"

there is no difference between an int that gets xor with 1 and a bool that gets
 flipped.

Looks like dev.ssa recognizes bool flip.

**Comment by randall77** [comment]
Note that your test code doesn't demonstrate what you think it does.  What you're measuring is the fact that SSA notices that your bool is dead and removes the code for flag=!flag altogether.

But put in a use of the resulting bool, and you'll see that SSA does use ^1 for bool flip.
