### ISSUE TITLE
x/sys/unix: Pwritev and Preadv always allocate

### ISSUE THREAD

**Issue by elagergren-spideroak** [golang/go#57296]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.3 darwin/amd64
</pre>

But for sys/unix:

```
golang.org/x/sys v0.3.0 h1:w8ZOecv6NaNa/zC8944JTU3vz4u6Lagfk4RPQxv92NQ=
golang.org/x/sys v0.3.0/go.mod h1:oPkhp1MJrh7nUepCBck5+mAzfO9JrbApNNgaTdGDITg=
```

### Does this issue reproduce with the latest release?

n/a

### What operating system and processor architecture are you using (`go env`)?

n/a

### What did you do?

Wrote a program that regularly calls `unix.Pwritev` with a similar number of discontinuous buffers.

### What did you expect to see?

A way to call `Pwritev` [without allocating](https://github.com/golang/sys/blame/cffae8ece41663c5af9960b8e9a735ef226ca64a/unix/syscall_linux.go#L2050) a slice of `Iovecs` each time.

### What did you see instead?

No way to do that.

I agree that [using `[][]byte` is nicer](https://github.com/golang/go/issues/36201#issuecomment-567278822), but unless the `Preadv`, `Pwritev`, etc. maintain a cache of `Iovec`s, each call necessarily allocates.

**Comment by randall77** [comment]
It is possible to stack-allocate a reasonably-sized iovec that would cover a lot of cases.
```
func Pwritev(fd int, iovs [][]byte, offset int64) (n int, err error) {
	iovecs := make([]Iovec, 0, 8)
	iovecs = appendBytes(iovecs, iovs)
```
Where `appendBytes` appends an `Iovec` for each `[]byte` argument. As long as there are at most 8 entries in `iovs`, it would not allocate.

(This is assuming `pwritev` doesn't escape its argument. I'm not sure if that is encoded somewhere or not?)

**Comment by ericlagergren** [comment]
@randall77  that seems to work, sending a CL
