### ISSUE TITLE
x/tools/gopls: support markdown in completion items

### ISSUE THREAD

**Issue by rodrigocfd** [golang/go#57300]
### What version of Go, VS Code & VS Code Go extension are you using?

* Go 1.19.4
* VSCode 1.74.0
* Go extension 0.36.0

### Describe the bug

Go 1.19 introduced a lot of new additions to [doc comments](https://tip.golang.org/doc/go1.19#go-doc), in particular, a syntax to add hyperlinks to the text. The hyperlinks render correctly when hovering the entity with the cursor, but not in autocomplete.

```go
package foo

// Just says [hello].
//
// [hello]: https://en.wikipedia.org/wiki/Hello
func Hello() string {
    return "hello"
}
```

### Screenshots or recordings

The VSCode extension correctly renders the hyperlinks when hovering the function declaration:

![1 hover func](https://user-images.githubusercontent.com/1283868/206884983-b2b1a2ea-b34c-49f8-827f-ef7ae4aad9d1.png)

And it also correctly renders the hyperlinks when hovering the function calls:

![2 hover func](https://user-images.githubusercontent.com/1283868/206884995-039800f0-75f8-4a87-9daa-09232713a42e.png)

However, in autocompletion, the new hyperlink syntax disappears, and we read instead the raw syntax formatting:

![3 autocomp](https://user-images.githubusercontent.com/1283868/206885020-f3d1b7ca-b221-4afc-a028-2ab3aae1e43e.png)

The autocomplete box should also render the hyperlinks.

**Comment by pjweinb** [comment]
It is possible to change gopls to provide this new behavior:
1. CompletionItem.Documentation is presently a string, but should be a MarkupItem (or at least accept MarkupItem)
2. Gopls has to look at the client's optional SignatureHelpClientCapabilities.SignatureInformation.DocumentationFormat list to see if the client prefers markdown to plaintext. (as vscode does)
3. And if so, convert the documentation to markdown (as is already done for Hover).
4. (it's probably not quite this simple...)

Getting this done is dependent on some existing CLs getting approved first. (and prioritization, of course, but it looks worth doing)
