### ISSUE TITLE
affected/package: 

### ISSUE THREAD

**Issue by dreamerzjy** [golang/go#57306]
follow the step below:
"""""
goctl api new greet
cd greet
go mod init
go mod tidy
go run greet.go -f etc/greet-api.yaml
""""""
error occurs:

D:\WorkSpace\goproject\greet>go run greet.go -f etc/greet-api.yaml
# greet/internal/handler
internal\handler\greethandler.go:16:10: undefined: httpx.ErrorCtx
internal\handler\greethandler.go:23:10: undefined: httpx.ErrorCtx
internal\handler\greethandler.go:25:10: undefined: httpx.OkJsonCtx

**Comment by seankhliao** [comment]
This doesn't look like an issue for the Go project.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
