### ISSUE TITLE
runtime: with -test.blockprofile program run even faster.

### ISSUE THREAD

**Issue by zdyj3170101136** [golang/go#57319]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes
### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/usr/local/go/pkg/mod/"
GONOPROXY=""
GONOSUMDB="gopkg.mihoyo.com"
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/root/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/root/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/profilerbench/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build799047141=/tmp/go-build -gno-record-gcc-switches"GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/usr/local/go/pkg/mod/"
GONOPROXY=""
GONOSUMDB="gopkg.mihoyo.com"
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/root/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/root/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/profilerbench/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build799047141=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
run benchmark test of src/runtime/chan_test.go.
one with blockprofile, another not.
```
/root/go/bin/go test -run=^$ -bench=BenchmarkChanProdConsWork0$ -benchtime=10000000x
goos: linux
goarch: amd64
pkg: github.com/zdyj3170101136/profilerbench/sync
cpu: Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz
BenchmarkChanProdConsWork0-8    10000000               839.0 ns/op
PASS
ok      github.com/zdyj3170101136/profilerbench/sync    8.490s

/root/go/bin/go test -run=^$ -bench=BenchmarkChanProdConsWork0$ -benchtime=10000000x -blockprofile=b
goos: linux
goarch: amd64
pkg: github.com/zdyj3170101136/profilerbench/sync
cpu: Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz
BenchmarkChanProdConsWork0-8    10000000               793.7 ns/op
PASS
ok      github.com/zdyj3170101136/profilerbench/sync    8.059s
```

### What did you expect to see?
with blockprofile, the program should run slower!

### What did you see instead?
with blockprofile, the program run faster !

### helpful information
here is the cpu profile diff:
<img width="1145" alt="截屏2022-12-15 下午3 23 00" src="https://user-images.githubusercontent.com/52686065/207798058-14ecd7d6-f5d9-44f5-8992-81d5d81e3cf6.png">

- saveblockevent cost lots of cpu.
- runtime.lock save lots of cpu, which means contention is less.

**Comment by thanm** [comment]
@golang/runtime

**Comment by mknyszek** [comment]
Since that benchmark is a microbenchmark, it's possible there's a scalability failure as it hammers on a particular lock. The CPU profile seems to suggest this. By adding in time between lock calls via the block profile operations, it actually eases up barging behaviors causing better performance.

I'm not sure there's anything to do here. In general, scalability failures aren't a good thing to have, but unless they're affecting real-world Go programs, I'm not too worried. They usually require a non-trivial amount of work to resolve, though this may be related to just general channel performance.

Please see #8899 for one possible solution/mitigation. Closing for now.

**Comment by mknyszek** [comment]
(To be clear, I don't think we _shouldn't_ make channels scale better in general. :) It's just going to be a non-trivial effort, potentially with a long bug tail, and we have to weigh that against everything else.)
