### ISSUE TITLE
affected/package: Time

### ISSUE THREAD

**Issue by acekingke** [golang/go#57316]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.18~1.19
</pre>

### Does this issue reproduce with the latest release?

yes 
### What operating system and processor architecture are you using (`go env`)?
linux
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
import (
	"fmt"
	"time"
)

func main() {
	now := time.Now()
	fmt.Println(now.Format("2022-12-15 09:07:41"))
}

 it return error times:
101010-1110-23 09:07:011

Program exited.

It run play ground occus error

### What did you expect to see?

the result should be  2022-12-15 09:07:011

**Comment by robpike** [comment]
Please read the documentation for time.Format carefully: https://pkg.go.dev/time#Time.Format

Look at the examples, which explain the mistake you're making regarding how to format a time value.
