### ISSUE TITLE
affected/package: strings

### ISSUE THREAD

**Issue by fruboy-qisst** [golang/go#57320]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.19.3

</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>
go env
</code>
</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mac/Library/Caches/go-build"
GOENV="/Users/mac/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/mac/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/mac/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.19.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/kf/jm3xjpxx179g8tlvsrtftm5h0000gn/T/go-build3777675844=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

When I'm using the strings.ReplaceAll function to strip slashes it doesn't work.
`
removalString := "{\"id\": 39894369894423, \"quantity\": 1, \"src\": \"\", \"title\": \"171 Keys DOUBLE SHOT Mechanical Gaming Keyboard\", \"variant_id\": 39894369894423, \"attribute\": [\"Merlin Keycap\"], \"price\": 99.99}"
`
`
result := strings.ReplaceAll(removalString, "\\", "")
`
This code should remove all the backslashes from the string but id doesn't.

I've tried using strings.Replace as well but that's not working either.

### What did you expect to see?

I expected that all the backslashes will be removed from the string.

### What did you see instead?

The backslashes were not removed from the string.

**Comment by seankhliao** [comment]
there are no slashes in the original string

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
