### ISSUE TITLE
syscall, internal/poll: accept4-to-accept fallback removal broke Go code on Synology DSM 6.2 ARM devices

### ISSUE THREAD

**Issue by bradfitz** [golang/go#57333]
We've started getting bug reports that our application is broken on older ARM-based Synology devices. SyncThing is also hitting it in https://github.com/syncthing/syncthing/issues/8325.

In https://github.com/golang/go/issues/45964 it was decided to require Linux 2.6.32 at minimum because that seemed like a popular cut-off as seen in the wild (due to Synology DSM 6.2) as seen by data I'd earlier collected.

Then some Go patches landed to simplify things based on that new minimum:

* https://go-review.googlesource.com/c/go/+/346849 (6705191e02d7e5e849a7877928003b797e0bc4f6) for Go 1.18
* ... _(something else? still digging)_ ....
*https://github.com/golang/go/commit/b8b9e83ec7a92498c2c69a1a963c31983d303e21 for Go 1.20rc1

Because packages in the Synology Package Center don't update often (it's like quarters to a year, not days like in the iOS/Google app stores), people are just hitting this now.

As @sfanous says in https://github.com/syncthing/syncthing/issues/8325#issuecomment-1119011120:

> Did some more digging, it seems accept4 for ARM was added in 2.6.36.
> ....

So it seems like maybe we should revert that 6705191e02d7e5e849a7877928003b797e0bc4f6 accept4->accept fallback if we truly want to say that 2.6.32 is our Linux minimum?

Oh, but I see at https://github.com/golang/go/wiki/MinimumRequirements that it says:

> Kernel version 2.6.32 or later. [This depends on architecture though, we need to have specific builder for this.] Linux/ARMv5 requires much newer kernels, at least v3.1 (for __kuser_cmpxchg64).

... and sure enough, some of these older Synology boxes experiencing problems are ARMv5 (e.g. `Linux ds212j 2.6.32.12 #25556 Thu Jul 1 14:25:48 CST 2021 armv5tel GNU/Linux synology_88f6281_212j`) so maybe `accept4` would just be the first of many problems they'd hit. I suppose I could try to run the Go std tests on one of these old boxes, but it's a bespoke userspace so would require some machinery running elsewhere.

/cc @tklauser @ianlancetaylor @knyar (who dig much of this digging)

**Comment by ianlancetaylor** [comment]
Looks like https://go.dev/cl/93637 (from 2018) removed the use of `__kuser_cmpxchg64`, saying "On linux/arm, 64-bit CAS kernel helper is dropped, as we're trying to move away from kernel helpers."

**Comment by ianlancetaylor** [comment]
The Linux man page says that `accept4` was added in kernel version 2.6.28.  However, I do see https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=21d93e2e29722d7832f61cc56d73fb953ee6578e which says "sys_accept4() was added in kernel 2.6.28, but ARM was not updated to include it."  So, yeah.  I think we need to revert CL 346849.  CC @tklauser .

**Comment by ianlancetaylor** [comment]
@gopherbot Please open backport issues.

We thought that we could require support for `accept4` on Linux when we updated the minimum kernel version to 2.6.32, but it turns out that on 32-bit ARM `accept4` was only added in kernel version 2.6.36.

**Comment by tklauser** [comment]
> The Linux man page says that `accept4` was added in kernel version 2.6.28. However, I do see https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=21d93e2e29722d7832f61cc56d73fb953ee6578e which says "sys_accept4() was added in kernel 2.6.28, but ARM was not updated to include it." So, yeah. I think we need to revert CL 346849. CC @tklauser .

I agree and I think we'd need to revert https://go.dev/cl/422375 (dropping the `accept` fallback from `internal/poll`), https://go.dev/cl/410737 (removing `syscall.accept` for `linux/loong64`), https://go.dev/cl/386415 (removing `syscall.accept` for all Linux platforms except `loong64`) in addition.

**Comment by ianlancetaylor** [comment]
I'm working on a patch, rather than a set of reverts.
