### ISSUE TITLE
x/net/nettest: SupportsIPv6 reports false even IPv6 is enabled

### ISSUE THREAD

**Issue by cuonglm** [golang/go#57386]
[SupportsIPv6](https://pkg.go.dev/golang.org/x/net@v0.4.0/nettest#SupportsIPv6) probe the stack by attempting to listen on `[::1]:0` to detect if IPv6 was enabled. However, servers may disabled IPv6 on loopback interface (for policies, security reason ...), but  still enable for the others.

~For IPv6, maybe it's better to use `[::]:0` instead.~

A better approach is looking for any "UP" interface that we can route ipv4/ipv6 traffic.

**Comment by wizardishungry** [comment]
Don't some operating systems (depending on security policy) throw a confirmation dialog when attempting to listen on any interface other than the loopback?

**Comment by cuonglm** [comment]
> Don't some operating systems (depending on security policy) throw a confirmation dialog when attempting to listen on any interface other than the loopback?

I don't know about this, I can only tested it on some of my Linux boxes.

The linux-arm* builders also reveal this thing, they support IPv6 but was disabled for loopback (See https://go-review.googlesource.com/c/net/+/458096 for details).

**Comment by wizardishungry** [comment]
https://apple.stackexchange.com/questions/393715/do-you-want-the-application-main-to-accept-incoming-network-connections-pop

**Comment by bradfitz** [comment]
> Don't some operating systems (depending on security policy) throw a confirmation dialog when attempting to listen on any interface other than the loopback?

Yes, the loopback listen (for both IPv4 and IPv6) was explicitly done to avoid OS firewall dialog boxes during tests.

**Comment by cuonglm** [comment]
> > Don't some operating systems (depending on security policy) throw a confirmation dialog when attempting to listen on any interface other than the loopback?
> 
> 
> 
> Yes, the loopback listen (for both IPv4 and IPv6) was explicitly done to avoid OS firewall dialog boxes during tests.
> 
> 
> 
> 

Then I think test should just use the `RoutedInterface` to test if we can do ipv6 on loopback?

**Comment by bradfitz** [comment]
I think the real problem is that `SupportsIPv6` isn't defined well enough.

It says:

> SupportsIPv6 reports whether the platform supports IPv6 networking functionality.

Does that mean?

* has a global unicast IPv6 address that works?
* can do IPv6 in theory, but might be disabled by a sysctl/OS knob? (so many people turn off their IPv6 for paranoia or while debugging something or from some misguided instructions they read somewhere and then forget they'd turned it off)
* can do IPv6 but only on certain interfaces ("for security reasons" !?)
* can do IPv6 on all interfaces

Seems like we'd want to figure out what this function is supposed to be reporting first.

**Comment by cuonglm** [comment]
> I think the real problem is that `SupportsIPv6` isn't defined well enough.
> 
> 
> 
> It says:
> 
> 
> 
> > SupportsIPv6 reports whether the platform supports IPv6 networking functionality.
> 
> 
> 
> Does that mean?
> 
> 
> 
> * has a global unicast IPv6 address that works?
> 
> * can do IPv6 in theory, but might be disabled by a sysctl/OS knob? (so many people turn off their IPv6 for paranoia or while debugging something or from some misguided instructions they read somewhere and then forget they'd turned it off)
> 
> * can do IPv6 but only on certain interfaces ("for security reasons" !?)
> 
> * can do IPv6 on all interfaces
> 
> 
> 
> Seems like we'd want to figure out what this function is supposed to be reporting first.
> 
> 

Totally agree!

For me, I'm leaning to report that we can do IPv6 at least on one of all interfaces. That also help us implementing more easily using `RoutedInterface`.

**Comment by cuonglm** [comment]
> For me, I'm leaning to report that we can do IPv6 at least on one of all interfaces. That also help us implementing more easily using RoutedInterface.

Something like this:

```
diff --git a/nettest/nettest.go b/nettest/nettest.go
index 8cb26a9..9ba5c99 100644
--- a/nettest/nettest.go
+++ b/nettest/nettest.go
@@ -38,10 +38,10 @@ func probeStack() {
                ln.Close()
                ipv4Enabled = true
        }
-       if ln, err := net.Listen("tcp6", "[::]:0"); err == nil {
-               ln.Close()
+       if _, err := RoutedInterface("ip6", net.FlagUp); err == nil {
                ipv6Enabled = true
        }
+
        rawSocketSess = supportsRawSocket()
        switch runtime.GOOS {
        case "aix":
```

**Comment by bcmills** [comment]
I've reopened this issue because I've mailed a revert for the fix CL (in https://go.dev/cl/460715) — it caused test failures for `dragonfly` and `js/wasm` (#57623).

We can either resolve the problem by implementing `RoutedInterface` on those platforms, or taking some alternate approach, or applying build constraints to use `RoutedInterface` only where supported.

**Comment by cuonglm** [comment]
I mailed https://go-review.googlesource.com/c/net/+/460735 for fixing the tests. The problem is not about `RoutedInterface`, but the code path that rely on old (wrong) behavior needs to be updated.
