### ISSUE TITLE
affected/package: FuncForPC not work like 1.8 before

### ISSUE THREAD

**Issue by z1293271436** [golang/go#57382]
### What version of Go are you using (`go version`)?

<pre>
$ go version  1.9.4
</pre>

### Does this issue reproduce with the latest release?

no

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env  this bug not cast by system

</pre></details>

### What did you do?

func (ctrl *BaseController) setFunc(f func(), father *BaseController) {
	ctrl.rpcFunc = f
	ctrl.http = &httpBase{Data: map[string]any{}}
	ptr := reflect.ValueOf(f).Pointer()
	functionInfo := runtime.FuncForPC(ptr)
	file, line := functionInfo.FileLine(ptr)
	file = file[strings.LastIndex(file, "/")+1:] //strings.ReplaceAll(file, utils.GetRuntimePath()+"/", "")
	name := functionInfo.Name()
	file = name[:strings.LastIndex(name, ".")]
	file = file[:strings.LastIndex(file, ".")]
	name = name[strings.LastIndex(name, ".")+1:]
	ctrl.funcName = utils.CombineString(name[strings.LastIndex(name, ".")+1:], "(", file, ":", utils.AllToString(line), ")")
	ctrl.father = father
}

### What did you expect to see?
if use 1.7 this file and line return the value I want  but now it work not well
it not return the function in witch file and line number

**Comment by mdlayher** [comment]
You're using a version of Go that is several years out of support. Apologies, but upgrading is the only path forward.

**Comment by z1293271436** [comment]
sorry,I edit version by misstake,I use the newest version and this funtion not work properly

**Comment by z1293271436** [comment]
please reopen my issue,and I had change content version
