### ISSUE TITLE
runtime:  FuncForPc on reflect.Pointer() result does not work properly

### ISSUE THREAD

**Issue by z1293271436** [golang/go#57383]
### What version of Go are you using (`go version`)?

<pre>
$ go version  1.19.4
</pre>

### Does this issue reproduce with the latest release?

no

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env  this bug not cast by system

</pre></details>

### What did you do?

func (ctrl *BaseController) setFunc(f func(), father *BaseController) {
	ctrl.rpcFunc = f
	ctrl.http = &httpBase{Data: map[string]any{}}
	ptr := reflect.ValueOf(f).Pointer()
	functionInfo := runtime.FuncForPC(ptr)
	file, line := functionInfo.FileLine(ptr)
	file = file[strings.LastIndex(file, "/")+1:] //strings.ReplaceAll(file, utils.GetRuntimePath()+"/", "")
	name := functionInfo.Name()
	file = name[:strings.LastIndex(name, ".")]
	file = file[:strings.LastIndex(file, ".")]
	name = name[strings.LastIndex(name, ".")+1:]
	ctrl.funcName = utils.CombineString(name[strings.LastIndex(name, ".")+1:], "(", file, ":", utils.AllToString(line), ")")
	ctrl.father = father
}

### What did you expect to see?
if use 1.17 this file and line return the value I want  but now it work not well
it not return the function in witch file and line number

**Comment by seankhliao** [comment]
This is insufficient info to reproduce or diagnose the issue.

**Comment by randall77** [comment]
A self-contained reproducer would be nice, thanks.

That said, I think this has to do with wrappers, similar (maybe dup?) of #51774 or #52809.

I would be interested in knowing if the CL for #51774 (CL 416455) helps in your situation.

More generally, `runtime.FuncForPC(reflect.Pointer(..some func..))` is not guaranteed to be stable. The docs for `reflect.Pointer()` only guarantee nil vs. non-nil result.

**Comment by z1293271436** [comment]
> A self-contained reproducer would be nice, thanks.
> 
> That said, I think this has to do with wrappers, similar (maybe dup?) of #51774 or #52809.
> 
> I would be interested in knowing if the CL for #51774 (CL 416455) helps in your situation.
> 
> More generally, `runtime.FuncForPC(reflect.Pointer(..some func..))` is not guaranteed to be stable. The docs for `reflect.Pointer()` only guarantee nil vs. non-nil result.

I cc,my question is same as other person has been set ,I'll close my issue
