### ISSUE TITLE
x/goproxy: access-control-allow-origin wildcard in response

### ISSUE THREAD

**Issue by x1unix** [golang/go#57387]
### What is the URL of the page with the issue?

* https://proxy.golang.org/go.uber.org/zap/@latest
* https://proxy.golang.org/go.uber.org/zap/@v/v1.24.0.zip

### What did you do?

Hello, I found that [proxy.golang.org](https://proxy.golang.org) returns `access-control-allow-origin: *` header in every response. That means that any web page (origin) from a web browser can do XHR requests to the module proxy.

```bash
$  curl -I -X GET https://proxy.golang.org/go.uber.org/zap/@v/v1.24.0.zip                                                                                                                                                   
HTTP/2 200
accept-ranges: bytes
access-control-allow-origin: *
...

$ curl -I -X GET https://proxy.golang.org/go.uber.org/zap/@latest                                                                                                                                                           
HTTP/2 200
accept-ranges: bytes
access-control-allow-origin: *
cache-control: public, max-age=60
content-length: 189
content-type: application/json
...
```

Usually wildcard value is served on local environments for development and it's very unusual to see it on production environment.

Can you tell me please if this is an intentional behaviour and can clients rely on it?

Thank you.

### What did you expect to see?

```
access-control-allow-origin: proxy.golang.org
```

### What did you see instead?

```
access-control-allow-origin: *
```

**Comment by seankhliao** [comment]
#36870

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
