### ISSUE TITLE
log/slog: slog.SetDefault side effects log.Print is not respecting level

### ISSUE THREAD

**Issue by mkungla** [golang/go#57396]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20rc1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

`-`

### What did you do?

```go
// Handle handles the Record.
// It will only be called if Enabled returns true.
// Handle methods that produce output should observe the following rules:
//   - If r.Time is the zero time, ignore the time.
//   - If an Attr's key is the empty string, ignore the Attr.
Handle(r Record) error
```
> It will only be called if Enabled returns true.

That is misleading, there is no checks for `Enabled` on available handlers which call directly `commonHandler.handle`. commonHandler.handler does not have enabled check. This check is performed by Logger call chain using `Logger.logDepth` where enabled is checked. 

That can lead some undesired side effects; e.g.

```go
slog.SetDefault(slog.New(slog.HandlerOptions{
  Level: slog.LevelWarn,
}.NewTextHandler(os.Stdout)))

slog.Info("slog.Info: that is ignored as it should")
slog.Warn("slog.Warn: that is logged as it should", "info.enabled", slog.Default().Enabled(slog.LevelInfo))
log.Print("log.Print: did not expect to see that in logs")

slog.Default().Handler().Handle(
  slog.NewRecord(
    time.Now(),
    slog.LevelInfo,
    "call.Handle: I guess thats ok if that is printed always",
    0, 
    nil,
))
```

### What did you expect to see?

No info logs.

### What did you see instead?

```out
time=2022-12-19T22:13:49.033+02:00 level=WARN msg="slog.Warn: that is logged as it should" info.enabled=false
time=2022-12-19T22:13:49.033+02:00 level=INFO msg="log.Print: did not expect to see that in logs"
time=2022-12-19T22:13:49.033+02:00 level=INFO msg="call.Handle: I guess thats ok if that is printed always"
```

Primarly it conserns  `log.Output` set by `func SetDefault(l *Logger)` 

```go
// It is used to link the default log.Logger to the default slog.Logger.
func (w *handlerWriter) Write(buf []byte) (int, error) {
  ...
  r := NewRecord(time.Now(), LevelInfo, string(buf), depth, nil)
  return origLen, w.h.Handle(r)
}
```

**So shouldn't this `handlerWriter` call have something like**

```go
func (w *handlerWriter) Write(buf []byte) (int, error) {
  if !w.h.Enabled(LevelInfo) {
    return 0, nil
  }
  ...
}
```

**or should Handle implementation do this check?**

_Originally posted by @mkungla in https://github.com/golang/go/issues/56345#issuecomment-1358281902_

**Comment by seankhliao** [comment]
please use the original thread
