### ISSUE TITLE
x/build/env/windows/arm64: windows/arm64 builders are down

### ISSUE THREAD

**Issue by qmuntal** [golang/go#57408]
`windows\arm64` builders have been unresponsive since December 12. First failing CL was https://go-review.googlesource.com/c/go/+/456835, which doesn't seem related.

Is this a planed-long downtime? Is there an ETA for having them up an running again? I have a couple of CLs stuck due to this issue.

@cagedmantis @heschi @dmitshur

**Comment by heschi** [comment]
Yeah, unfortunately we've lost our builders and not yet replaced them. @thanm may know more about progress here.

**Comment by jaredpar** [comment]
Is the expectation that these will be brought back when the builders are available?

**Comment by thanm** [comment]
@jaredpar yes

**Comment by thanm** [comment]
Builders are back up.  I'm going to keep the issue open for a bit longer in case other problems arise, but for now it looks like things are working.

**Comment by qmuntal** [comment]
> Builders are back up. I'm going to keep the issue open for a bit longer in case other problems arise, but for now it looks like things are working.

Good news!

@thanm I'm still not able to trigger the windows-arm64 builders from a CL (by posting `TRY=windows-arm64`), see for example https://go-review.googlesource.com/c/go/+/454675. Is there something missing?

**Comment by thanm** [comment]
@qmuntal as far as I know there aren't any remaining issues/problems. We had to do a test fix backport for the release branches, but other than that I think things are working.  I'll go ahead and close out the bug, we can reopen later if need be. Thanks.

**Comment by heschi** [comment]
@qmuntal I don't see the `TRY=` comment on that CL? The alias does exist: https://cs.opensource.google/go/x/build/+/master:dashboard/builders.go;l=103;drc=faea4fa6b0c3ed3cd8232c6eb6742d3bcb3f867d.

**Comment by qmuntal** [comment]
> @qmuntal I don't see the `TRY=` comment on that CL? The alias does exist: https://cs.opensource.google/go/x/build/+/master:dashboard/builders.go;l=103;drc=faea4fa6b0c3ed3cd8232c6eb6742d3bcb3f867d.

Here it is: https://go-review.googlesource.com/c/go/+/452995/comments/ba8287b7_ae1d5bac

**Comment by heschi** [comment]
Oh, it was too old to see. I believe you need to repeat it every time you trigger trybots. https://github.com/golang/go/wiki/SlowBots#pitfalls
