### ISSUE TITLE
cmd/link: dead importcycle code

### ISSUE THREAD

**Issue by jquirke** [golang/go#57400]
Remove dead code importcycles() function.

This was originally introduced in 2011 in CL https://codereview.appspot.com/4812053 for Issue 2052.

All consumers of this code were removed in a cleanup in 2016 https://go-review.googlesource.com/c/go/+/21782 and it performs no function whatsoever.

Furthermore:

- The compiler itself provides some protection against import cycles
- The linker already has import cycle detection in postorder (https://github.com/golang/go/blob/fe67a21625ee811897077b32d4e75566ef74c6c4/src/cmd/link/internal/ld/lib.go#L2558)

**Comment by cherrymui** [comment]
Thanks for spotting this. For things like this, you can just send a CL without filing an issue. Thanks.
