### ISSUE TITLE
cmd/compile: remove GOEXPERIMENT=nounified

### ISSUE THREAD

**Issue by mdempsky** [golang/go#57410]
Tracking issue for removing GOEXPERIMENT=nounified for Go 1.21.

**Comment by liggitt** [comment]
FYI, we're seeing regressions on ARM builds in go1.20 that bisected to https://github.com/golang/go/commit/833367e98af838a2511ee7e4e19dc8f1da7b8ed7 where the unified experiment was enabled by default (https://github.com/golang/go/issues/58425#issuecomment-1426359497)

Should the experiment remain until we're confident regressions in the unified build on go1.20 are resolved?

**Comment by mdempsky** [comment]
The nounified frontend used in the 1.18 and 1.19 releases was the first to support generics, but we've experienced a lot of subtle correctness issues with it, which became untenable to fix. E.g., for 1.18, we decided to stop backporting generics fixes, because every time we attempted to fix one issue, we introduced at least one new one.

The unified frontend has been in use internally within Google for months. The compiler team decided as a whole to commit to the unified frontend for 1.20 and forward. We talked about whether it made sense to keep the code around longer, but we have a lot of other work planned for 1.21 (e.g., overhauling how inlining works, for better PGO support), which was hindered by the technical burden of maintaining two frontends.

We did expect hiccups in the transition though, which is why GOEXPERIMENT=nounified is still available and supported in the 1.20 release branch. And admittedly #58339 is a bit embarrassing, but that will be fixed in 1.20.1. In 1.20, it can be worked around with `-gcflags=all=-d=inlstaticinit=0`.

Thanks for your patience while we address the reported regressions.

**Comment by mdempsky** [comment]
Closing this issue because the nounified frontend has been removed at tip. There's still more cleanup work to do, but that can happen without a tracking issue.

**Comment by randall77** [comment]
@liggitt I don't think the "relocation truncated" error is particularly related to the unified frontend. That's just the change that happened to reorder functions such that the branch distance was exceeded.

When I compile your repro from #58425 successfully with 1.20, it generates a binary whose text size is 66MB, when the branch (call) distance on arm32 is +/- 32 MB. I'm kind of surprised it ever worked before - you probably just got lucky using the old frontend.

Not that there couldn't be reasons why the unified frontend exacerbates the situation, but once your program is >32MB of text it's just a matter of time before some benign change causes relocation errors. (Until #58425 is fixed, probably by adding trampolines or something.)
