### ISSUE TITLE
dangling and unhelpful links in generics blog post https://go.dev/blog/why-generics

### ISSUE THREAD

**Issue by glycerine** [golang/go#57421]
https://go.dev/blog/why-generics

says

~~~
Note added January 2022: This blog post was written in 2019 and 
does not describe the version of generics that was finally adopted. 
For updated information please see [the language spec](https://go.dev/ref/spec) and
 [the generics design document] (https://go.dev/design/43651-type-parameters).
~~~

The design document link is broken, giving the following error

~~~
NOT_FOUND: Requested entity was not found

You may not have access to this page. You can retry after signing in.
[Sign in](https://accounts.google.com/AccountChooser?service=gerritcodereview&continue=https://go.googlesource.com/login/proposal/%2B/master/design/43651-type-parameters%29.md)

[type.googleapis.com/google.rpc.LocalizedMessage]
locale: "en-US"
message: "Object is not found"

[type.googleapis.com/google.rpc.RequestInfo]
request_id: "133005606361471fa2e31ecb656293dc"
~~~

The language spec link is not helpful regarding generics. It has only one instance of the word generics, and this does not describe the implementation at all, only to point to old docs of the pre-generics Go:

"This is the reference manual for the Go programming language. The pre-Go1.18 version, without generics, can be found [here](https://go.dev/doc/go1.17_spec.html)."

These links should be updated to point to useful information about the present form of the generics implementation.

**Comment by fzipp** [comment]
The URL itself is correct, but the markdown contains a misplaced space between description and URL, which breaks the rendering of the link.

> The language spec link is not helpful regarding generics. It has only one instance of the word generics

The feature is called "type parameters" in the spec.

**Comment by dr2chase** [comment]
The CL looks plausible to me, I pinged @ianlancetaylor as a reviewer.
