### ISSUE TITLE
crypto/x509: Verify on macOS does not return typed errors [1.19 backport]

### ISSUE THREAD

**Issue by rolandshoemaker** [golang/go#57427]
@rolandshoemaker requested issue https://github.com/golang/go/issues/56891 to be considered for backport to the next 1.19 minor release.

> @gopherbot please open backport issues. This issue makes macOS behave differently from every other platform, which otherwise return consistent types for verification errors. This was an inadvertent breaking API change introduced in 1.18, and is likely causing silent issues in code that expects consistent behavior across platforms when verifying certificates. Currently working around this requires adding macOS specific code in order to catch specific verification failures.

**Comment by heschi** [comment]
cc @golang/security
