### ISSUE TITLE
x/website: images not displaying properly

### ISSUE THREAD

**Issue by climbTheStairs** [golang/go#57456]
Page: <https://go.dev/blog/survey2022-q2-results>

### What did you expect to see?

Images

### What did you see instead?

The HTML `<img src=... />` tag displayed as text.

**Comment by seankhliao** [comment]
sounds more likely to be a problem with your browser?

**Comment by seankhliao** [comment]
seems to be only 2 images

![Screenshot_20221225-103418](https://user-images.githubusercontent.com/11343221/209461749-5d77c69b-e06e-46ba-89a5-1734caf4a05e.png)

**Comment by climbTheStairs** [comment]
Yes, it's just those images not displaying properly (though the files do exist)
