### ISSUE TITLE
runtime/cgo: the handle pointer is freed during C asynchronous callback

### ISSUE THREAD

**Issue by huskar-t** [golang/go#57463]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1056322479=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

https://go.dev/play/p/k68Hr3YCWdP
when the C asynchronous callback, the runtime/cgo handle pointer has been freed by the gc, causing the wrong memory to be used during the callback

### What did you expect to see?
keep the handle pointer until `handle.Delete()` is called

### What did you see instead?
handle pointer has been freed by the gc

**Comment by doujiang24** [comment]
I think it's just a wrong usage.

`handle` could be GC freed, after `C.callback_wrapper` returning, it's by design.

according to your code:
```
func DoAsync() {
	handle := cgo.NewHandle("test")
	pointer := unsafe.Pointer(&handle)
	fmt.Printf("handle:%d,pointer: %v\n", handle, pointer)
	C.callback_wrapper(pointer)
}
```

**Comment by huskar-t** [comment]
@doujiang24 I temporarily use sync.map to save the pointer, I'm not sure if cgo handle should provide this feature.This example is just to show the problem I'm having

**Comment by seankhliao** [comment]
I believe this violates cgo pointer rules https://pkg.go.dev/cmd/cgo#hdr-Passing_pointers 
specifically: 
> C code may not keep a copy of a Go pointer after the call returns.
