### ISSUE TITLE
Hey, expand of go1.19.4.linux-amd64.tar.gz DOES NOT create bin directory!

### ISSUE THREAD

**Issue by Jibun-no-Kage** [golang/go#57468]
Hey, expand of go1.19.4.linux-amd64.tar.gz DOES NOT create bin directory!  Your installation instructions cannot be followed! 
Per https://go.dev/doc/install Linux installation steps...

The following command is broken on Debian 11...
\# cd /usr/local
\# wget https://go.dev/dl/go1.19.4.src.tar.gz
\# rm -rf /usr/local/go && tar -C /usr/local -xzf go1.19.4.linux-amd64.tar.gz
tar (child): go1.19.4.linux-amd64.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

So I tried the following...

\# cd /usr/local
\# wget https://go.dev/dl/go1.19.4.src.tar.gz
\# tar -xvf go1.19.4.src.tar.gz
\# cd /usr/local/go
\# pwd
/usr/local/go

\# ls -l /usr/local/go
total 60
drwxr-xr-x  2 root root  4096 Dec  1 10:12 api
-rw-r--r--  1 root root    52 Dec  1 10:12 codereview.cfg
-rw-r--r--  1 root root  1339 Dec  1 10:12 CONTRIBUTING.md
drwxr-xr-x  2 root root  4096 Dec  1 10:12 doc
drwxr-xr-x  3 root root  4096 Dec  1 10:12 lib
-rw-r--r--  1 root root  1479 Dec  1 10:12 LICENSE
drwxr-xr-x 11 root root  4096 Dec  1 10:12 misc
-rw-r--r--  1 root root  1303 Dec  1 10:12 PATENTS
-rw-r--r--  1 root root  1455 Dec  1 10:12 README.md
-rw-r--r--  1 root root   419 Dec  1 10:12 SECURITY.md
drwxr-xr-x 48 root root  4096 Dec  1 10:12 src
drwxr-xr-x 26 root root 12288 Dec  1 10:13 test
-rw-r--r--  1 root root     8 Dec  1 10:12 VERSION

So like where is the bin directory?  Guess I can't use go language as I hoped.

**Comment by seankhliao** [comment]
you've downloaded a copy of the source code and not the binary distribution. Note the difference between the file name in your title and download commands.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by Jibun-no-Kage** [comment]
Ah... well that explains a lot!  I guess since I spend some much time in GitHub... I took a wrong turn.  Time lay off the egg-nog!  Thanks for the clarification.
