### ISSUE TITLE
affected/package: build error | service/service_layer.go:38:34: internal compiler error: assertion failed

### ISSUE THREAD

**Issue by princeparmar** [golang/go#57464]
```
this part i can execute
	switch d := h.helper.(type) {
	case Debugger:
		if d.Debug() {
			cmd, err := http2curl.GetCurlCommand(request)
			fmt.Println("curl_request", cmd.String(), "err", err)
		}
	}

	// if debugger, found := h.helper.(Debugger); found && debugger.Debug() {
	// 	cmd, err := http2curl.GetCurlCommand(request)
	// 	fmt.Println("curl_request", cmd.String(), "err", err)
	// }

this i can't
```

### What version of Go are you using (`go version`)?

<pre>
$ go version 1.18.4

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by seankhliao** [comment]
please include a full reproduction case (eg playground)

**Comment by mvdan** [comment]
Also, 1.18.4 is not the latest release.
