### ISSUE TITLE
x/net: net/internal/timeseries/timeseries.go - Division by zero

### ISSUE THREAD

**Issue by stasos24** [golang/go#57466]
### What do you expect to see

https://github.com/golang/net/blob/2aa82152a53e7aa6b28c6390d9369ee5a5b63584/internal/timeseries/timeseries.go#L360

```if num <=0```
### What did you see instead?
When  ```ComputeRange(start, finish time.Time, num int) ``` function 
https://github.com/golang/net/blob/2aa82152a53e7aa6b28c6390d9369ee5a5b63584/internal/timeseries/timeseries.go#L354
is called with num=0 you'll get Division by zero at
https://github.com/golang/net/blob/2aa82152a53e7aa6b28c6390d9369ee5a5b63584/internal/timeseries/timeseries.go#L398

**Comment by seankhliao** [comment]
does this actually come up in real code?

**Comment by stasos24** [comment]
No, but if someone is calling this function where num is dynamically assigned, there's possible division by zero

**Comment by seankhliao** [comment]
given this is internal code with no direct path for misuse, i don't think this is an issue.
