### ISSUE TITLE
reflect: MakeStruct

### ISSUE THREAD

**Issue by sbinet** [golang/go#5748]
<pre>Feature request for MakeStruct, to go along with the newly-arrived MakeFunc ( <a href="https://golang.org/issue/1765">issue #1765</a>
).

It would be greatly useful for interacting with libraries expecting a certain binary
layout, and also to have a programmatic interface to code against.</pre>

**Comment by randall77** [comment]
ArrayOf just landed, https://go-review.googlesource.com/#/c/4111/

Getting equals and hash correct is one of the hard parts of StructOf.  The ArrayOf change makes the equal and hash functions from closures.  The same technique could be used here.

(Closures for equal/hash became available as of https://go-review.googlesource.com/#/c/2392/)

**Comment by sbinet** [comment]
I'll give it a try tomorrow.

**Comment by ben-clayton** [comment]
Is this now done?

**Comment by bradfitz** [comment]
Seems like it.

**Comment by mdempsky** [comment]
@ben-clayton Not completely. See 633ab74

**Comment by bradfitz** [comment]
Or apparently recursive structs: #20013

**Comment by bradfitz** [comment]
@mdempsky, I think embedding types with non-exported methods should probably be a new bug rather than reusing this one for four years.

**Comment by mdempsky** [comment]
@bradfitz Okay by me. Tracking in #20015.
