### ISSUE TITLE
x/tools/gopls: incorrect edit when completing test function name

### ISSUE THREAD

**Issue by findleyr** [golang/go#57480]
Split off from #56852. When completing at `_` in `func Te_(t *testing.T) {} (i.e. modifying the test func name), the completion duplicates the test body`:

```
func TestXxx(t *testing.T) {

}(t *testing.T) {

}
```

CC @pjweinb

**Comment by pjweinb** [comment]
This is definitely undesirable behavior but I'm not sure what to do about it. (In gopls' defence, Git Copilot also offers some completions that duplicate existing stuff, but that's undesirable too.)

Here's one possible way of handling this (where $ indicates either the end of the current line or the end of the editor buffer, _ is where the cursor is before and after the completion, Xx stands for any non-empty prefix of 'Test', Yy stands for any non-empty prefix of '(t *testing.T)')
'func Xx_$' completes to 'func Test_(t *testing.T) {$'   (or maybe 'func Test_(t *testing.T) {}$')
'func Xx_Yy$' completes to 'func Test_Yy$'
and any other 'func Xx_<stuff>' completes to 'func Test_<stuff>'

I'm not sure this is all the cases, and I'm not sure how practical it is to implement. Thoughts welcome.

**Comment by muirdm** [comment]
[completion/definition.go](https://github.com/golang/tools/blob/85e6ad773c681df9702c85baf7808ed1324de4e3/gopls/internal/lsp/source/completion/definition.go#L55) unconditionally adds the `(t *testing.T) {}` part. One fix would be to get the parent FuncDecl out of `path` and check if the recorded parens/curlies actually exist in the source code. For example, check if FuncDecl.Type.Params.Opening is valid and is actually a "(" in the source code.

If they don't exist, assume you have "func Te<>". If they do exist, assume you have "func Te<>(t *testing.T) {}" and don't add the boilerplate.
