### ISSUE TITLE
x/build/dashboard: add OpenBSD 7.1 and 7.2 builders (for 386, amd64)

### ISSUE THREAD

**Issue by dmitshur** [golang/go#57496]
OpenBSD 7.2 [has been released](https://www.openbsd.org/72.html). 
This is a tracking issue for adding OpenBSD 7.1 and 7.2 builders for amd64 and 386 architectures.
This is in progress, see https://go.dev/cl/456295.

CC @golang/release, @golang/openbsd.

**Comment by dmitshur** [comment]
I've deployed these builder last night and they had a chance to produce results. It looks to be working well to me. It's passing on all golang.org/x repos, and mostly passing on the main repo. There are some failures on OpenBSD 7.1 that might be related to #55161.

As far as I can tell, it seems fine to remove the known issue and switch trybots from 7.0 to 7.2. And, we should remove the <= 7.0 builders after that too (fine to do in a separate CL or all at once).

@qbit Would you like to send CLs to take those next steps here and I can review?

**Comment by qbit** [comment]
Sure, I'll get that sent off here in a sec.

**Comment by 4a6f656c** [comment]
@dmitshur @qbit 

I'm a bit late to this party, however as things stand we will not be able to run OpenBSD 7.1 builders - there is a kernel kqueue bug that got fixed upstream, however there is currently no errata for it:

http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/sys/kern/kern_event.c.diff?r1=1.188&r2=1.189

This means we would either a custom kernel with this diff, or we would need to get this released as OpenBSD errata.

**Comment by qbit** [comment]
Oh bummer. Well, should we disable the 7.1 builders? Not sure a 7.1 errata would fly.. but I don't have much insight into that side of things :D .

**Comment by dmitshur** [comment]
Thanks Joel. To me, disabling (or removing, really) 7.1 builders seems fine, and that would resolve #57585. I'll let OpenBSD port owners follow up as you prefer. Please file a new issue for anything that needs to happen.
