### ISSUE TITLE
cmd/go: import path "demo/测试" is reported as malformed

### ISSUE THREAD

**Issue by sxin0** [golang/go#57503]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.2 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jsx/.cache/go-build"
GOENV="/home/jsx/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/jsx/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jsx/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/data/www/jsx/tanxiao_hesuan/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build45875529=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Use Chinese as the directory

 

### What did you expect to see?
All utf8 characters are supported
```go
// demo/测试/示例.go
package 测试

func A测试() string {
	return "示例"
}
```

```go
// main.go

fmt.Println(测试.A测试())

// main.go:9:2: malformed import path "demo/测试": invalid char '测'
```
 

### What did you see instead?
main.go:9:2: malformed import path "demo/测试": invalid char '测'

**Comment by dmitshur** [comment]
Thanks for the report. Also see a similar previous report in #45507.

I think the tracking issue for revisiting this is #45549 (and maybe also #44970). Please comment if you think this is a different issue.

CC @bcmills, @matloob.
