### ISSUE TITLE
proposal: Go 2: Just a suggestion，About Single Line Comments

### ISSUE THREAD

**Issue by Mr-Zhang-Cn** [golang/go#57504]
###Author Background
Chinese people with poor English
A programmer who has just started writing code for less than 2 months

### Proposal
I want the single line comment to be # instead of//
Because the # on the keyboard is easier to operate, just shift+3, but//the input method always needs to be switched. There is always a problem with the full width and half width.
The main reason is that I am used to using # as annotation when developing PHP.

### Costs

I think it's a small cost

**Comment by seankhliao** [comment]
I don't think we'd want to introduce more inconsistency in the way people write comments, only for tools like gofmt to reformat them back to a single canonical form.

It's also quite a high cost change across the entire ecosystem.
