### ISSUE TITLE
x/build: linux-amd64-wsl builder failing

### ISSUE THREAD

**Issue by dmitshur** [golang/go#57517]
The linux-amd64-wsl builder (owned by @mengzhuo) flipped abruptly from almost always passing to almost always failing on December 13, 2022:

<img width="36" alt="image" src="https://user-images.githubusercontent.com/1924134/210019397-02532958-d3d2-480f-9a2e-a8a291859c8a.png">

On the main branch, it happened first on [CL 457055](https://go.dev/cl/457055) on Dec 13. But it also started happening on 1.19 and 1.18 release branches on a completely unrelated change ([CL 456560](https://go.dev/cl/456560) and [456561](https://go.dev/cl/456561)) on Dec 14. This suggests that the failure is more likely to be caused by something that happened on that week rather than a particular code change.

The most common error is:

```
fatal error: trace: ReadTrace got invalid frequency
```

Here are the 3 most recent build logs:

- https://build.golang.org/log/fbc66b6fd21efece15fba6a5793ab39a5534a4dc
- https://build.golang.org/log/f11b716d9f72e7322f25bda7b946041b90370df5
- https://build.golang.org/log/4b224c4fdd65698d08c0e5a00a42bb952310f86f

@mengzhuo Do you know if there were changes to the builder or its environment around Dec 13?

CC @golang/runtime, @golang/release.

**Comment by mengzhuo** [comment]
The WSL builders were based on ESXi 6.7 before Dec 13th, however my license are expired on that day. So I changed to PVE instead now.

Maybe I can change to ESXi 7.0 for free usage.

**Comment by mengzhuo** [comment]
Updates: I've transfered all wsl builder to new esxi based server, but there is no new commit so I think we need to wait for it to close this issue.

**Comment by heschi** [comment]
Still looks busted? https://build.golang.org/log/2d1e14595ca6ef409f849aa8eab0afced9c43623

**Comment by heschi** [comment]
Note also that quite a few x/ repo tests are failing; debug, sys, net look real to me.

**Comment by mengzhuo** [comment]
@heschi One major difference is builders running on Ubuntu 22.04 LTS from Microsoft store, instead of 20.04 LTS.
I'll take a look at strace log in WSL builder

**Comment by mengzhuo** [comment]
Updates:
The builder is based on WSL2/Ubuntu 20.04 now and it's working as expected.
https://build.golang.org/log/24a4cef69560bdde23d3eda23925bc0cf569b901

I will look into why Ubuntu 22.04 LTS still failed builds.

**Comment by cagedmantis** [comment]
@mengzhuo Should we close this issue since the builder is green again? Then maybe add an issue to explore why the Ubuntu 22.04 based builder was failing?
