### ISSUE TITLE
x/build/dashboard: add js-wasm-node18 builder

### ISSUE THREAD

**Issue by dmitshur** [golang/go#57513]
The current "js-wasm" builder tests using Node.js 14 (as of August 2021; see [CL 338730](https://go.dev/cl/338730)). From looking at https://nodejs.org/en/about/releases, there are newer Node.js releases available by now, and Node.js 14 will reach EOL on 2023-04-30.

This is the tracking issue for adding a js/wasm builder with a newer Node.js release.

It seems Node.js 18 will have longer LTS support than Node.js 19 and the https://nodejs.org page describes it as "Recommended For Most Users", so it looks like a good choice for the next version. I've titled this issue accordingly.

CC @golang/js, @golang/wasm, @golang/release.

**Comment by agnivade** [comment]
Duplicate of https://github.com/golang/go/issues/57017?

**Comment by dmitshur** [comment]
@agnivade Thanks, I missed that unfortunately (it didn't have `CC @golang/release` nor a new-builder label). I'll update my CL to use that issue.
