### ISSUE TITLE
x/pkgsite: packages with an excluded prefix show up in search

### ISSUE THREAD

**Issue by suzmue** [golang/go#57528]
Follow up from #57510
### What is the URL of the page with the issue?
https://pkg.go.dev/search?q=pixelyte

### Screenshot
<img width="609" alt="Screenshot 2022-12-30 at 11 26 56 AM" src="https://user-images.githubusercontent.com/6634754/210091792-f6081f6f-68b6-44a2-a026-3fa5bae86b8d.png">

### What did you do?
Searched for the name of a package that has been excluded from the pkgsite results from the main pkg.go.dev page. 

### What did you expect to see?
No results matching codeberg.org/pixelyte

### What did you see instead?
The pages for the documentation are correctly not available, but the excluded packages still appear in the results.

Interestingly, if I search from the results page, there are correctly no results (https://pkg.go.dev/search?q=pixelyte&m=package)

<img width="602" alt="Screenshot 2022-12-30 at 11 30 29 AM" src="https://user-images.githubusercontent.com/6634754/210092101-031a4344-6401-4838-bac8-e41f6824b8ba.png">

**Comment by niceatoms** [comment]
This issue seems to have resolved itself. I think it was probably just still in the cache. Somebody should close this. @suzmue
