### ISSUE TITLE
net: LookupAddr does not set IsNotFound with cgo resolver

### ISSUE THREAD

**Issue by rudis** [golang/go#57548]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="$HOME/.cache/go-build"
GOENV="$HOME/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="$HOME/dev/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/go/go1.19.4"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/go/go1.19.4/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/run/user/$UID/go-build1957738364=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

    $ cat > x.go <<EOF
    package main
    import (
            "fmt"
            "net"
    )
    func main() {
            _, err := net.LookupAddr("1.2.3.4")
            fmt.Printf("%v\n", err.(*net.DNSError).IsNotFound)
    }
    EOF

    $ GODEBUG=netdns=go go run x.go
    true

    $ GODEBUG=netdns=cgo go run x.go
    false

### What did you expect to see?

Both go and cgo resolver correctly report `IsNotFound`.

### What did you see instead?

Only go resolver does so.

There's already a pull request for this but it wasn't merged: https://github.com/golang/go/pull/45959

**Comment by mateusz834** [comment]
I should be fixed when [CL 459955](https://go-review.googlesource.com/c/go/+/459955) gets merged

**Comment by rudis** [comment]
I think this CL is unrelated because it changes cgoLookupIPCNAME and not cgoLookupAddrPTR which is used by LookupAddr.

**Comment by mateusz834** [comment]
@rudis  you are right, my mistake, deleted that comment. I will make a new CL for this.

**Comment by heschi** [comment]
cc @neild @ianlancetaylor

**Comment by rudis** [comment]
> @rudis you are right, my mistake, deleted that comment. I will make a new CL for this.

Thanks for the quick response. CL looks good to me.
