### ISSUE TITLE
x/website: Effective go docs say there are 3 forms of for but with for .. range there are 4

### ISSUE THREAD

**Issue by damonfeldman** [golang/go#57545]
### What is the URL of the page with the issue?
 https://go.dev/doc/effective_go
 
### What is your user agent?
[Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:108.0) Gecko/20100101 Firefox/108.0](https://developers.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)
 
### Screenshot
 

 
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/700633/210248198-ea8d2a6d-2c52-4181-83db-9b7a7213aef9.png">

 
### What did you expect to see?
I expected the 
    for key, value := range <rangeexp>
form of a for loop to conform to one of the three for loop forms listed above, since the doc says there are only three forms. 
 
### What did you see instead?
Three forms listed, then immediate use of the fourth (for..range) form.

**Comment by seankhliao** [comment]
`key, value :=  range oldMap` is a single `condition` in the second form.
