### ISSUE TITLE
cmd/compile: race is not supported on windows/386

### ISSUE THREAD

**Issue by VaibhavArora19** [golang/go#57543]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.4 windows/386
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=386
set GOBIN=
set GOCACHE=C:\Users\arora\AppData\Local\go-build
set GOENV=C:\Users\arora\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\arora\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\arora\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files (x86)\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files (x86)\Go\pkg\tool\windows_386
set GOVCS=
set GOVERSION=go1.19.4
set GCCGO=gccgo
set GO386=sse2
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\arora\Desktop\learnGo\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m32 -mthreads -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\arora\AppData\Local\Temp\go-build1124495080=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
I tried testing the race condition using command `go run -race main.go` 

### What did you expect to see?
By running this command I should have been able to test the race condition in my go code.

### What did you see instead?
I am getting the following in my terminal `-race is not supported on windows/386`

**Comment by ALTree** [comment]
The Go race detector is based on ThreadSanitizer, which does not work on any 32-bit platform since AFAIK it assumes it can reserve huge continuous part of address space for various things, well beyond what's 32-bits-addressable. 

> Support for 32-bit platforms is problematic and is not planned.

from https://clang.llvm.org/docs/ThreadSanitizer.html. So it's unlikely that the Go race detector will ever work on any 32-bit platform.

**Comment by VaibhavArora19** [comment]
But I am running go on a 64-bit platform.

**Comment by ALTree** [comment]
`go version` printing `windows/386` means you're using the 32-bit windows toolchain. You'll need to download the 64-bit one.
