### ISSUE TITLE
x/tools/gopls: TestRenamePackage_InternalPackage failing on linux-amd64-wsl builder

### ISSUE THREAD

**Issue by findleyr** [golang/go#57555]
It looks like the linux-amd64-wsl builder is generally unhappy. It seems to have encountered "hanging go commands" very frequently, but that is a separate issue (#54461).

Recent failures appear deterministic, failing with "permission denied", starting with https://go.dev/cl/459416. This may be because the go command is still holding onto a file, but the failure mode does seem related to that change.
https://build.golang.org/log/5053369eca96766a09d70f36ed4ac8926fc182a1
```
rename_test.go:940: renaming sandbox file: rename /tmp/workdir-host-linux-amd64-wsl/tmp/gopls-regtest-4043663239/TestRenamePackage_InternalPackage/default/work/lib /tmp/workdir-host-linux-amd64-wsl/tmp/gopls-regtest-4043663239/TestRenamePackage_InternalPackage/default/work/lib1: permission denied
```

CC @dle8

**Comment by heschi** [comment]
The WSL builder has been sick, see https://go.dev/issue/57517.

**Comment by findleyr** [comment]
Closing as dupe of #57517
