### ISSUE TITLE
cmd/gofmt: inconsistent variable names in rewrite.go

### ISSUE THREAD

**Issue by rillig** [golang/go#57567]
### What did you do?
Read through `cmd/gofmt/rewrite.go` in order to find out how to deal with comments when instrumenting Go code.

### What did you expect to see?
The _Values/types for special cases_ use a consistent naming scheme.

### What did you see instead?
* Some of the variable names include `Ptr`, others omit it. Either all or none should include the word `Ptr`.
* `positionType` should rather be `posType`, as it is about `token.Pos`, not `token.Position`.

**Comment by heschi** [comment]
Do you intend to fix this? If so, cleanup CLs don't generally need an issue associated. If not, I'm not sure this is worth tracking as an issue.

cc @griesemer

**Comment by griesemer** [comment]
There is no issue here. These naming choices have been made many years ago, and there's no reason to make changes in this code.
