### ISSUE TITLE
cmd/compile: constraint satisfaction errors use "implements" instead of "satisfies"

### ISSUE THREAD

**Issue by griesemer** [golang/go#57564]
Per the latest spec, we now distinguish between interface _implementation_ and constraint _satisfaction_.

However, currently the compiler reports constraint satisfaction errors with the phrase "cannot implement" or "does not implement" instead of "cannot satisfy" or "does not satisfy".

Not necessarily a release blocker but would be good to fix ASAP.

**Comment by griesemer** [comment]
cc: @findleyr

**Comment by griesemer** [comment]
cc: @golang/release to decide if the CL above acceptable to submit for 1.20. The change only affects error messages, but of those it affects virtually every error message about constraint satisfaction. It would be good to use the same language in those messages as is now used in the spec.

**Comment by heschi** [comment]
Fine by us; seems like a straightforward bug fix even if it's not so critical.
