### ISSUE TITLE
net: add examples

### ISSUE THREAD

**Issue by adg** [golang/go#5757]
<pre>The net package is somewhat overwhelming. Good examples would help.</pre>

**Comment by marcellanz** [comment]
what is the intention and scope of examples in the documentation? is it defined how examples complement the documentation?

**Comment by parkr** [comment]
> The net package is somewhat overwhelming. Good examples would help.

@adg Have a moment to answer @marcellanz's question? Thank you!

**Comment by bradfitz** [comment]
@marcellanz, examples **are** documentation. Some people prefer to learn by reading code instead of reading words.

**Comment by kavirajk** [comment]
net package have just one example https://golang.org/pkg/net/#example_Listener And even that fails with following error.

`
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_notifyListWait(0x1054e080, 0x0)
	/usr/local/go/src/runtime/sema.go:267 +0x1e0
sync.(*Cond).Wait(0x1054e078, 0x1054e070)
	/usr/local/go/src/sync/cond.go:57 +0xe0
syscall.(*queue).waitRead(0x1054e070, 0x1, 0x0, 0x0, 0x105000f0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/net_nacl.go:263 +0x180
syscall.(*msgq).read(0x1054e070, 0x1050e090, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/net_nacl.go:377 +0xc0
syscall.(*netFile).accept(0x10534100, 0x1c8da0, 0x10534100, 0x0, 0x0, 0x0, 0x0, 0x1050e0f8)
	/usr/local/go/src/syscall/net_nacl.go:539 +0x60
syscall.Accept(0x3, 0x77d5, 0x10534140, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/net_nacl.go:759 +0xa0
net.accept(0x3, 0x170144, 0x10534140, 0x0, 0x0, 0x0, 0x0, 0x77d5)
	/usr/local/go/src/net/sys_cloexec.go:45 +0x60
net.(*netFD).accept(0x10534140, 0x1, 0x0, 0x0, 0x0, 0x2)
	/usr/local/go/src/net/fd_unix.go:411 +0x220
net.(*TCPListener).accept(0x1050a188, 0x1c02a0, 0x10529f28, 0x0, 0x0, 0x10529f28)
	/usr/local/go/src/net/tcpsock_posix.go:132 +0x40
net.(*TCPListener).Accept(0x1050a188, 0x1c053c, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock.go:222 +0xc0
main.main()
	/tmp/sandbox839529466/main.go:18 +0x1a0
`

I'm thinking covering some examples for net package. Can we use any ports in the examples? just wondering how it will work
//cc @adg

**Comment by kennygrant** [comment]
The package now has 8 examples, so perhaps this could be closed as fixed?

https://tip.golang.org/pkg/net/#pkg-examples
