### ISSUE TITLE
runtime: test timeouts on openbsd-.*-71 builders

### ISSUE THREAD

**Issue by cherrymui** [golang/go#57585]
```
#!watchflakes
post <- builder ~ `openbsd-.*-71` && (`SIGQUIT` || `test timed out` || `failed to start: context deadline exceeded` || `panic: finalizer started .* ago .*, but did not return`)
```

**Comment by bcmills** [comment]
In all of the failures with `SIGQUIT` dumps, it appears that every goroutine but one is blocken in `runtime.gopark`, and the remaining goroutine is blocked in `runtime.thrsleep` via `runtime.findRunnable`.

Smells like a platform bug to me, but maybe @golang/runtime will have some debugging tips for the port owners?

**Comment by bcmills** [comment]
@golang/openbsd, any progress on this?

I feel like we're not getting any useful signal from the `openbsd-.*-71` builders because of this. Given that the `-72` series are passing, should we just turn off the `-71` series?

**Comment by qbit** [comment]
I'll make a PR to remove the 7.1 builders here pretty quick.

**Comment by cherrymui** [comment]
The last failure is openbsd-72, tracked in #55161.
