### ISSUE TITLE
all: update js/wasm port for Node.js 18

### ISSUE THREAD

**Issue by dmitshur** [golang/go#57614]
The recently-added [js/wasm builder with Node.js 18](https://github.com/golang/go/issues/57017) reports that all.bash doesn't pass out of the box.
This is the umbrella issue to track everything needed to migrate the js/wasm port from Node.js 14 to 18.
(It can't happen now because we're in the freeze for 1.20, so placing in 1.21 milestone.)

- #56860
- #57516
- #57613
- #58145
- #56498

CC @golang/js, @golang/wasm, @johanbrandhorst.

**Comment by johanbrandhorst** [comment]
I've created https://go.dev/cl/463234, https://go.dev/cl/463975 and https://go.dev/cl/463976 to deal with https://github.com/golang/go/issues/57516, https://github.com/golang/go/issues/56860 and https://github.com/golang/go/issues/57613 respectively. I think once all 3 are merged, we should be able to build successfully for Node 18.

**Comment by johanbrandhorst** [comment]
New issue found by trybots: https://github.com/golang/go/issues/58145

**Comment by johanbrandhorst** [comment]
I expect the next issue we'll be hitting is https://github.com/golang/go/issues/56498.
