### ISSUE TITLE
x/tools/gopls/internal/lsp/fake: file edits in regression tests cause diffs with invalid edits

### ISSUE THREAD

**Issue by findleyr** [golang/go#57627]
Just encountered in a regtest: formatting a particular go.work file (that isn't newline terminated) results in out of bounds edits:

```
env.OpenFile("go.work")
env.SetBufferContent("go.work", "go 1.18\nuse moda/a")
env.Save("go.work")
```

```
        metadata_test.go:175: formatting before save: editing "go.work": diff has out-of-bounds edits; edits:
            [{1:0 1:0
            } {2:0 2:0
            }]
```

CC @adonovan @pjweinb

**Comment by adonovan** [comment]
The bug is in the fake editor's applyEedits function. Fix pending. (Sorry for casting aspersions on the diff package, which hasn't had any bugs yet.)
