### ISSUE TITLE
os: UserCacheDir and UserConfigDir have no tests

### ISSUE THREAD

**Issue by bcmills** [golang/go#57638]
`os.UserCacheDir` was added in https://go.dev/cl/78835 for #22536.

In examining #57630, it seems that this function is not covered by any tests at all. There were none added in https://go.dev/cl/78835, nor in https://go.dev/cl/120757.

It seems like we should at least have some test that verifies that `UserCacheDir` reports either an error or a directory in which the user is allowed to create files. 😅

(CC @rsc @robpike @ianlancetaylor @bradfitz @griesemer for `os`)

**Comment by Ja7ad** [comment]
https://github.com/golang/go/pull/57809

**Comment by bcmills** [comment]
It appears that `UserConfigDir` (https://go.dev/cl/160877 / #29960) is [similarly untested](https://cs.opensource.google/search?q=UserConfigDir%20filepath:_test.go&sq=&ss=go%2Fgo).
