### ISSUE TITLE
x/exp: wrong go.mod go version

### ISSUE THREAD

**Issue by Shubhaankar-Sharma** [golang/go#57639]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.4 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/shubhaankar/Library/Caches/go-build"
GOENV="/Users/shubhaankar/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/shubhaankar/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/shubhaankar/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.4"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/j2/gmd4pj9j35q4w1t01mb1ng480000gn/T/go-build2203409633=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

If i use golang.org/x/exp/slog in a project with go 1.18 it errors because
https://github.com/golang/exp/blob/master/slog/level.go#L95 Here, the type atomic.Int64 is being used
which was introduced in go 1.19 but golang.org/x/exp requires go version of 1.18 as its minimum version which didn't support this type

**Comment by ianlancetaylor** [comment]
CC @jba

**Comment by jba** [comment]
We're only going to support slog for 1.19 and above.
It's OK that the go.mod `go` line says 1.18. That has to do with language features; it need not reflect the needed standard library version (although I agree it would be less confusing if it did).

**Comment by heschi** [comment]
Seems like this is WAI, closing as such.
