### ISSUE TITLE
cmd/gc: clang 3.3 complains about undefined behavior

### ISSUE THREAD

**Issue by davecheney** [golang/go#5764]
<pre>What steps will reproduce the problem?

1. Download clang 3.3 or later, <a href="http://llvm.org/releases/download.html#3.3">http://llvm.org/releases/download.html#3.3</a>
2. export CC=clang
3. apply CL <a href="https://golang.org/cl/10488044">https://golang.org/cl/10488044</a>
4. ./make.bash

What is the expected output? What do you see instead?

Expected, clean build

Actual, quite a few warnings, some trivial, others not.
<a href="https://gist.github.com/davecheney/5847237">https://gist.github.com/davecheney/5847237</a>

Please use labels and text to provide additional information.

See also the discussion here
<a href="https://groups.google.com/forum/#">https://groups.google.com/forum/#</a>!topic/golang-dev/SlTKGOfHjtU</pre>

**Comment by ianlancetaylor** [comment]
We're planning to remove the C code, so the issue, which is about avoiding warnings in C code, is irrelevant.
