### ISSUE TITLE
basic operation: Basic unsigned int type

### ISSUE THREAD

**Issue by fenghaojiang** [golang/go#57652]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go 1.19.2
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
darwin

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN="/Users/fenghaojiang/Go/bin/"
GOCACHE="/Users/fenghaojiang/Library/Caches/go-build"
GOENV="/Users/fenghaojiang/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/fenghaojiang/go/pkg/mod"
GONOPROXY="gitlab.blockvision.org/*"
GONOSUMDB="gitlab.blockvision.org/*"
GOOS="darwin"
GOPATH="/Users/fenghaojiang/go"
GOPRIVATE="gitlab.blockvision.org/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/fenghaojiang/Solidity/eth-note/blockvision/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/tb/ky45y6z11kx53hmjgnp120br0000gn/T/go-build2064063778=/tmp/go-build -gno-record-gcc-switches -fno-common"
fenghaojiang@fenghaojiangdeMacBook-Pro blockvision % go env
GO111MODULE=""
GOARCH="arm64"
GOBIN="/Users/fenghaojiang/Go/bin/"
GOCACHE="/Users/fenghaojiang/Library/Caches/go-build"
GOENV="/Users/fenghaojiang/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/fenghaojiang/go/pkg/mod"
GONOPROXY="gitlab.blockvision.org/*"
GONOSUMDB="gitlab.blockvision.org/*"
GOOS="darwin"
GOPATH="/Users/fenghaojiang/go"
GOPRIVATE="gitlab.blockvision.org/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/fenghaojiang/Solidity/eth-note/blockvision/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/tb/ky45y6z11kx53hmjgnp120br0000gn/T/go-build1463808580=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

```go
package main

import (
	"fmt"
)

func main() {
	var num1 uint64 = 1
	if num1-10000 >= 0 {
		num1 = num1 - 10000
	}
	fmt.Printf("%v", num1)
}

```

```shell
go run main.go
```

### What did you expect to see?
shell output should be like:
```shell
0
```

### What did you see instead?
```shell
18446744073709541617%
```

**Comment by randall77** [comment]
That is how `uint64` works.
From the spec:
```
uint64      the set of all unsigned 64-bit integers (0 to 18446744073709551615)
```
```
For [unsigned integer](https://go.dev/ref/spec#Numeric_types) values, the operations +, -, *, and << are computed modulo 2n, where n is the bit width of the unsigned integer's type. Loosely speaking, these unsigned integer operations discard high bits upon overflow, and programs may rely on "wrap around".
```
