### ISSUE TITLE
cmd/go: error while fetching dependency

### ISSUE THREAD

**Issue by rajender** [golang/go#57656]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.4 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\rreddy\AppData\Local\go-build
set GOENV=C:\Users\rreddy\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\rreddy\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\rreddy\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.19.4
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\rreddy\AppData\Local\Temp\go-build168345287=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

$ go get  github.com/xuri/excelize/v2
go: downloading github.com/xuri/excelize/v2 v2.6.1
go: downloading github.com/xuri/excelize v1.4.1
go: github.com/xuri/excelize/v2@v2.6.1: read "https:/proxy.golang.org/@v/v2.6.1.zip": unexpected EOF

### What did you expect to see?

fetching the package without errors.

### What did you see instead?

go: github.com/xuri/excelize/v2@v2.6.1: read "https:/proxy.golang.org/@v/v2.6.1.zip": unexpected EOF

**Comment by seankhliao** [comment]
is that unmodified output?
can you download any code without issue?
is there a proxy/mitm on your network?
are you able to get `https://proxy.golang.org/github.com/xuri/excelize/v2/@v/v2.6.1.zip` with other tools?
can you give the full log of `go get -x -v github.com/xuri/excelize/v2`?

**Comment by rajender** [comment]
@bcmills No. HTTP_PROXY and/or HTTPS_PROXY environment variables not set.

**Comment by rajender** [comment]
<pre>
$ curl -vLO https://proxy.golang.org/github.com/xuri/excelize/v2/@v/v2.6.1.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 146.112.47.14:443...
* Connected to proxy.golang.org (146.112.47.14) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
*  CApath: none
} [5 bytes data]
* [CONN-0-0][CF-SSL] TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [10 bytes data]
* [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [3172 bytes data]
* [CONN-0-0][CF-SSL] TLSv1.3 (OUT), TLS alert, unknown CA (560):
} [2 bytes data]
* SSL certificate problem: unable to get local issuer certificate
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
</pre>

**Comment by seankhliao** [comment]
That is a Cisco IP address it's connecting to, not an upstream proxy address.
It would suggest that there is some network middleware which is modifying the request/response, causing the errors.
This is outside the control of Go, and you should probably contact your network operator for help.
