### ISSUE TITLE
access: go-approvers 

### ISSUE THREAD

**Issue by hickford** [golang/go#57654]
Hi. Please consider me for go-approvers. See https://go.dev/wiki/GithubAccess.

> The poorly named "go-approvers" group is the set of people who can edit metadata on issues.

I hope to tidy https://github.com/golang/oauth2/ a little

**Comment by seankhliao** [comment]
cc @golang/release

**Comment by heschi** [comment]
Hi Matt,

I've added you to go-approvers. Thanks for your contributions!

**Comment by hickford** [comment]
Thanks very much
