### ISSUE TITLE
cmd/compile: large, simple array 75x slower to compile with -race

### ISSUE THREAD

**Issue by josharian** [golang/go#57657]
Compile this file with and without `-race`:

https://gist.githubusercontent.com/josharian/7e19da2d4c68d004ffebf510aeb8ef69/raw/5c475f906ce7a515d45d8bb5ae5c701469682b8a/x.go

On my laptop, it compiles without -race in 1.5s. With -race, it takes over 100s.

This is extracted and simplified from real code that was causing repeated CI build timeouts, meaning it was taking upwards of 10 minutes to build on a slow CI machine.

Reproduced with both 1.19.4 and 1.20rc2.

I haven't investigated at all.

**Comment by cuonglm** [comment]
It seems to me that `-race` forces `new(T)` to be copied, causing quadratic behavior of `cmd/compile/internal/ssa.Func.computeZeroMap`. Disable writebarrier brings the speed back:

```
time go tool compile -race -wb=false p.go
=====
JOB go tool compile -race -wb=false p.go
128%    cpu
1.80s real
2.18s user
0.12s sys
```

`Func.computeZeroMap` was introduced in [CL 156363](https://go-review.googlesource.com/c/go/+/156363) cc @randall77

**Comment by cuonglm** [comment]
Ops @gopherbot, why did you post two comments :smiley:
