### ISSUE TITLE
cmd/internal/obj/arm64: ARM assembly rotational right shift of a register with @> syntax causes compile error

### ISSUE THREAD

**Issue by dadrian** [golang/go#57662]
### What version of Go are you using (`go version`)?

<pre>
$ go version 
go1.19.4 darwin/arm64

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/dadrian/Library/Caches/go-build"
GOENV="/Users/dadrian/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/dadrian/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/dadrian/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.19.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.19.4/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.4"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/dadrian/src/github.com/dadrian/go-bugs/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/7_/yc9s7tp94lq83r7fmlncg58c0000gn/T/go-build2852821403=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

Compiled Go assembly for arm that uses a rotation right shift with the [@> syntax](https://pkg.go.dev/cmd/internal/obj/arm64#hdr-Argument_mapping_rules).

`ADD R0@>16, ZR, R0`

I pushed a minimal test case here: https://github.com/dadrian/go-bugs/tree/main/arm-ror

### What did you expect to see?

Successful compilation

### What did you see instead?

```
asm: unsupported shift operator: 00016 (/Users/dadrian/src/github.com/dadrian/go-bugs/arm-ror/function_arm64.s:3)       ADDR0@>16, ZR, R0
```

**Comment by cespare** [comment]
@dadrian is ROR a valid shift type for ADD?

If I look at the [ADD docs](https://developer.arm.com/documentation/dui0802/b/A64-General-Instructions/ADD--shifted-register-) I see

> Is the optional shift type to be applied to the second source operand, defaulting to LSL, and can be one of LSL, LSR, or ASR.

whereas if I look at, for example, [EOR](https://developer.arm.com/documentation/dui0802/b/A64-General-Instructions/EOR--shifted-register-) I see

> Is the optional shift to be applied to the final source, defaulting to LSL, and can be one of LSL, LSR, ASR, or ROR.

(I'm an arm64 newbie so maybe I'm mistaken.)

**Comment by dadrian** [comment]
I actually first ran into this on an `EOR` and dumbed it down to `ADD` for the repro. You're absolutely correct.

That being said, it does work on EOR but only on the first argument, not the second. Not sure if that's intentional (I'm also an ARM newbie).

**Comment by greatroar** [comment]
This is a feature/limitation of the architecture.
