### ISSUE TITLE
x/mobile: Multiple independent lib using gomobile in the same app

### ISSUE THREAD

**Issue by hpcarlos** [golang/go#57661]
### What version of Go are you using (`go version`)?
<pre>
1.19
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE="on"
GOARCH="arm64"
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOOS="darwin"
GOVERSION="go1.19.3"
</pre></details>

### What did you do?

I have a problem which is as follows.
I have a legacy android app that already has a lib.so made using gomobile, this lib is necessary for the app, and I don't have its code, much less is it simple to reproduce what this lib does, and I need to include it another lib made by me in the same project, but as soon as I load the lib made by me, in several versions of android I have the following crash:
<pre>
17:33:40.619 system_process W  channel 'f020b3a mypackage.android/org.dep.ClassDep (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
17:33:40.619 system_process E  channel 'f020b3a mypackage.android/org.dep.ClassDep (server)' ~ Channel is unrecoverably broken and will be disposed!
</pre>

### What did you expect to see?
I need both libs to work in the same app.
If there is a way where I can free up the communication channel and let the other use it, and then manage to keep alternating between the libs where each one does what it needs and free this channel, it would be interesting.

Or maybe a way to load the two separately inside the android where each one is inside a sandbox or something along those lines.

### What did you see instead?
The error mentioned above.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
