### ISSUE TITLE
proposal: slice: support converting [2]T to []T. 

### ISSUE THREAD

**Issue by goldwind-ting** [golang/go#57678]
```golang
arr := [2]int{1, 2}
slice := []int(arr)
fmt.Println(slice)
```
Want to convert array to slice but getting: `cannot convert arr (variable of type [2]int) to type []int`.
So, could support converting?

**Comment by seankhliao** [comment]
`arr[:]`

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
