### ISSUE TITLE
x/pkgsite: module version in pkg.go.dev still hasn't updated almost a year after github version update

### ISSUE THREAD

**Issue by natemcintosh** [golang/go#57677]
### What is the URL of the page with the issue?
 https://pkg.go.dev/github.com/natemcintosh/gocombinatorics
 
 
### What is your user agent?
[Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:108.0) Gecko/20100101 Firefox/108.0](https://developers.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)
 
 
### Screenshot
![pkg site](https://user-images.githubusercontent.com/40805156/211179499-1be6d794-63b5-4ca5-ba6c-b4a70f6d3d07.jpg)

 
![github](https://user-images.githubusercontent.com/40805156/211179507-58f8379e-eb1d-450d-aca1-a05d23760055.jpg)

 
 
### What did you do?
On January 11, 2022, I released version 0.3.1 of a module on github. I then tried all three methods listed under [adding a package](https://pkg.go.dev/about#adding-a-package) to get it to update on the [pkg site](https://pkg.go.dev/github.com/natemcintosh/gocombinatorics), but to no avail.
 
 
 
### What did you expect to see?
That the version number and updated information for v0.3.1 on the [pkg site](https://pkg.go.dev/github.com/natemcintosh/gocombinatorics)
 
 
### What did you see instead?
Still on v0.2.0 after almost a year.

**Comment by jamalc** [comment]
My theory is pkgsite attempted to process this module while running go1.18beta2 and it failed. From the logs we know that parsing the packages failed but we can't see why, unfortunately it just says the module contained no packages. Submitted those versions for reprocessing and now they're live on the site. I haven't seen any similar reports but we could consider reprocessing additional packages if it comes up again.

**Comment by natemcintosh** [comment]
Thank you so much! I really appreciate your help
