### ISSUE TITLE
net: make sure Dial returns random UDP port

### ISSUE THREAD

**Issue by gopherbot** [golang/go#5767]
by **fish@soundcloud.com**:

<pre>Hello everyone,

I was digging around in the net package (to see how hard it would be to fix #5686) when
I realized that it's using math/rand for id randomization. math/rand is a pseudo-random
generator and, without being an crypto expert, this seems like it's predictable.

Since DNS security (without dnssec) depends solely on the randomness of dns ID and
source port, it's important for both to be random. This yield true especially since Dan
Kaminski's dns vulnerability discovery.

For the source port, net seems to depend on the kernel's source port randomization where
I'm not sure if they are unpredictable or whether go should explicitly generate a
random, unpredictable port as well.

Attached is a naive fix, replacing math/rand by crypto/rand. I'm happy for suggestions
in case there is a better way to fix it.</pre>

Attachments:

1. <a href="https://storage.googleapis.com/go-attachment/5767/0/replace-math-rand-by-crypto-rand-for-dns-id.patch">replace-math-rand-by-crypto-rand-for-dns-id.patch</a> (1312 bytes)

**Comment by dpiddy** [comment]
Can this be closed?

**Comment by ianlancetaylor** [comment]
Thanks, as far as I can tell it looks OK.  Closing.
