### ISSUE TITLE
math/big:Float.Add returns incorrect Accuracy

### ISSUE THREAD

**Issue by qiulaidongfeng** [golang/go#57670]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=auto
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=E:\gofile\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=E:\gofile
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,https://proxy.golang.org,direct
set GOROOT=D:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.19
set GCCGO=gccgo
set GOAMD64=v2
set AR=ar
set CC=clang
set CXX=clang++
set CGO_ENABLED=1
set GOMOD=
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=D:\TEMP\go-build2837617554=/tmp/go-build -gno-record-gcc-switches
GOROOT/bin/go version: go version go1.19 windows/amd64
GOROOT/bin/go tool compile -V: compile version go1.19
</pre></details>

### What did you do?
```go
package main

import (
	"fmt"
	"math/big"
	"strconv"
)

func main() {
	src1str := "9.1"
	src1f, err := strconv.ParseFloat(src1str, 64)
	if err != nil {
		panic(err)
	}
	src1 := big.NewFloat(src1f)
	src2str := "1.8"
	src2f, err := strconv.ParseFloat(src2str, 64)
	if err != nil {
		panic(err)
	}
	src2 := big.NewFloat(src2f)
	var result big.Float
	result.SetPrec(64)
	result.Add(src1, src2)
	fmt.Println(result.Float64())
}
```

### What did you expect to see?
10.9 Exact

### What did you see instead?
10.9 Above

**Comment by seankhliao** [comment]
Your input is lower precision (53) than your result (64).
This appears to be working as expected.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
