### ISSUE TITLE
compile/internal/pgo: show informative error message for missing Function.start_line

### ISSUE THREAD

**Issue by lizthegrey** [golang/go#57674]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20rc2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What did you do?
Pass a `default.pgo` merged profile that contained some pprof data from 1.19 rather than 1.20rcX.

### What did you expect to see?
An informative error message telling me that the profile passed in needed to be entirely from 1.20rcX or newer, specifically containing [the patch that enabled start_line passing](https://github.com/golang/go/commit/a401468b0092446d537edc2000c23e8015ce6b58)

### What did you see instead?

```
# vendor/golang.org/x/crypto/cryptobyte/asn1
compile: PGO profile missing Function.start_line data
# sync/atomic
compile: PGO profile missing Function.start_line data
...
```

**Comment by prattmic** [comment]
Thanks, this should indeed be more informative.
