### ISSUE TITLE
compile: version "go1.x.x" does not match go tool version "go1.x.x"

### ISSUE THREAD

**Issue by marcelo321** [golang/go#57685]
### What version of Go are you using (`go version`)?

<pre>
# go version
go version go1.19.1 linux/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
# go version
go version go1.19.1 linux/amd64
root@localhost:/usr/local/go/bin# go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/root/.go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/root/.go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2264740211=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

Apparently I was using `go1.17.3` and updated it to last version `go1.19.1`, but now when I want to download something I get the following errors:

```
# go install github.com/projectdiscovery/katana/cmd/katana@latest
# internal/unsafeheader
compile: version "go1.17.3" does not match go tool version "go1.19.1"
# internal/abi
compile: version "go1.17.3" does not match go tool version "go1.19.1"
# internal/cpu
compile: version "go1.17.3" does not match go tool version "go1.19.1"
# internal/goexperiment
compile: version "go1.17.3" does not match go tool version "go1.19.1"
# runtime/internal/atomic
compile: version "go1.17.3" does not match go tool version "go1.19.1"
..... etc.
```

**Comment by seankhliao** [comment]
this happens when you don't do a clean install.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
