### ISSUE TITLE
HTTPS server crashes because of alertCertificateUnknown

### ISSUE THREAD

**Issue by bharat42** [golang/go#57681]
HTTPS server crashes at the following line because of [alertCertificateUnknown](https://github.com/golang/go/blob/2ebe77a2fda1ee9ff6fd9a3e08933ad1ebaea039/src/crypto/tls/alert.go#L65
) error.

https://github.com/golang/go/blob/f721fa3be9bb52524f97b409606f9423437535e8/src/net/http/server.go#L1855

**Comment by seankhliao** [comment]
This is only a log line for an unrecoverable error, not a hard crash.

**Comment by bharat42** [comment]
Sorry for the wrong reporting. I found the actual bug that caused it to a hard crash.
