### ISSUE TITLE
affected/package:  Will linux kernel 5 or above affect the memory release of go1.15?

### ISSUE THREAD

**Issue by ruby1ring** [golang/go#57686]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.15

</pre>

### Does this issue reproduce with the latest release?
No

### What operating system and processor architecture are you using (`go env`)?
Linux  5.4.54-1.0.0.std7c.el7.2.x86_64 #1 SMP Mon Nov 16 10:02:20 CST 2020 x86_64 x86_64 x86_64 GNU/Linux
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
The memory usage is too high, but there is no memory leak by analyzing the heap file of pprof.
The reason for this conclusion is:
1. My service is deployed on k8s, and there are other same services. The pprof file analysis results are similar to this problematic one (linux kernel version is 4.9.2-3.0.0.std7b.el7.5.x86_64 #1 SMP Thu Apr 26 17:33:02 CST 2018 x86_64 x86_64 x86_64 GNU/Linux).
2. I refer to the MADV_FREE problem in the link below. By analyzing the LazyFree of the /proc/1/smaps file, I found that it is all 0, and all machines are linux kernel 4.5 or above. Logically, the same problem will occur, but it does not No. https://github.com/golang/go/issues/42330
3. gotrace records are normal

### What did you expect to see?
Why is the memory usage of this service high? What impact does Linux kernel version 5 and above have on golang memory management?

### What did you see instead?
Below is a screenshot of the abnormal machine
![image](https://user-images.githubusercontent.com/27205174/211217530-e3d179f3-b2d4-4096-81fe-7152e27370bd.png)
![image](https://user-images.githubusercontent.com/27205174/211217552-098e7752-32fe-48fb-8e26-b9199a37b9a1.png)
![image](https://user-images.githubusercontent.com/27205174/211217598-07c8299a-7e49-4a54-ad54-2e01fde538e1.png)

**Comment by seankhliao** [comment]
We no longer support 1.15, only the 2 latest releases.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
