### ISSUE TITLE
fork/exec /var/folders/ty/q11880gn5797hjv_tnk2m_k80000gn/T/go-build3935763930/b001/exe/main: exec format error

### ISSUE THREAD

**Issue by bcdon** [golang/go#57693]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.19.4 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
MacOs，M2

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/biandong/Library/Caches/go-build"
GOENV="/Users/biandong/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/biandong/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/Users/biandong/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="0"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ty/q11880gn5797hjv_tnk2m_k80000gn/T/go-build3632438957=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.19.4 darwin/arm64
GOROOT/bin/go tool compile -V: compile version go1.19.4
uname -v: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:52 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8112
ProductName:		macOS
ProductVersion:		13.0.1
BuildVersion:		22A400
lldb --version: lldb-1400.0.30.3
Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)
</pre></details>

### What did you do?
```
 go run hello.go 

error:
fork/exec /var/folders/ty/q11880gn5797hjv_tnk2m_k80000gn/T/go-build1075750828/b001/exe/hello: exec format error
```

```
% sudo go run hello.go        

error:
fork/exec /tmp/go-build2358697227/b001/exe/hello: exec format error
```

**Comment by mengzhuo** [comment]
You are forcing Go use `amd64` instead of `arm64` by enviorment variable `GOARCH="amd64"`.
--------
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
