### ISSUE TITLE
cmd/compile: internal compiler error: Value live at entry. It shouldn't be.

### ISSUE THREAD

**Issue by SladeThe** [golang/go#57702]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.4 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\SLADE\AppData\Local\go-build
set GOENV=C:\Users\SLADE\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\SLADE\.gopath\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\SLADE\.gopath
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=D:\Programs\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Programs\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.19.4
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\Projects\Go\issue\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\SLADE\AppData\Local\Temp\go-build583418767=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
[This single-package version](https://go.dev/play/p/dHwis_tpjda) works just fine.

But if I move all the code except `main`-func to a package, e.g. `foo`, the code stops working.

<details><summary><code>main.go</code></summary><br><pre>
package main

import (
	"issue/foo"
)

func main() {
	println(foo.Chain(foo.Foo()))
}
</pre></details>

<details><summary><code>foo/foo.go</code></summary><br><pre>
package foo

type Func func() error

func Chain(funcs ...Func) error {
	for _, f := range funcs {
		if err := f(); err != nil {
			return err
		}
	}

	return nil
}

func Foo() Func {
	return bar[string]{}.Validate
}

type bar[T any] struct{}

func (v bar[T]) Validate() error {
	return nil
}
</pre></details>

<details><summary><code>go.mod</code></summary><br>
<pre>
module issue

go 1.19
</pre>
</details>

### What did you expect to see?

Is compiles successfully

### What did you see instead?

```
.\main.go:8:27: internal compiler error: 'main': Value live at entry. It shouldn't be. func main, node foo..rcvr1, value nil

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new
```

**Comment by SladeThe** [comment]
If I remove generic parameter from `bar` struct, the code also works fine, no matter the package.

**Comment by cuonglm** [comment]
Duplicated of https://github.com/golang/go/issues/54911
