### ISSUE TITLE
cmd/go/internal/vcs: wrong comment, repoRootForImportPathStatic func no longer exists

### ISSUE THREAD

**Issue by bekcpear** [golang/go#57718]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### Details

check this line: https://github.com/golang/go/blob/0202ad0b3a2bfddf9f3eafb94e19d5a0fa3d1f31/src/cmd/go/internal/vcs/vcs.go#L1273

the `repoRootForImportPathStatic` func has been replaced by `repoRootFromVCSPaths` func in this commit: https://github.com/golang/go/commit/669f5be2ac6f761f8c917baa2ba899ed7f64bc14, but the comment here is not updated.

**Comment by bcmills** [comment]
This doesn't really need to be filed as an issue — if a comment is wrong please just send a PR or CL. 😅

https://go.dev/doc/contribute

**Comment by bekcpear** [comment]
> This doesn't really need to be filed as an issue — if a comment is wrong please just send a PR or CL. sweat_smile

Thanks for your reply, however I just found this wrong comment and not sure whether there are something others related contents/comments should be fixed either, and I don't want to ignore the question, so I opened this issue.
