### ISSUE TITLE
affected/package: x/time/rate

### ISSUE THREAD

**Issue by jfweioefjweeoifjwjfoiawfwefwefweqfwe** [golang/go#57712]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.19.4
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you expect to see?
How do I get the queue size?

### What did you see instead?
Can't get the queue size. If I have 3 items waiting in the queue then I'd like a way to get "3". Thanks!

**Comment by seankhliao** [comment]
rate isn't a queue

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
