### ISSUE TITLE
x/perf: allow callers to specify precision of benchmark report

### ISSUE THREAD

**Issue by nealeckard** [golang/go#57711]
### What version of Go are you using (`go version`)?
go1.20-20221229-RC00
<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?
I think so (I'm on an RC, so I'd assume so).

### What operating system and processor architecture are you using (`go env`)?

Debian Linux, x86_64

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

We're running three sets of benchmarks (using the Google benchmark library): "original", "user", and "solution" (see screenshot). We then pipe the benchmarks through benchstat for display to the user.

### What did you expect to see?
The "original" is usually much slower than the solution, so when benchstat processes the results, it displays all three benchmarks with the precision of the slowest benchmark, resulting in displayed rounded-down zero values for the solution. It would be better if these zero values weren't rounded down, but instead displayed, for example, 0.234 microseconds (instead of just 0 microseconds).

### What did you see instead?

![5T9BeqzE9XF3gJv](https://user-images.githubusercontent.com/62125412/211418467-6bdfff99-ca02-4feb-8cad-5b33803f6cb5.png)

**Comment by thepudds** [comment]
Hi @nealeckard, thanks for filing this.

FWIW, there is a complete rewrite of benchstat that is in progress, including this CL:
https://go-review.googlesource.com/c/perf/+/309969

It could be interesting to try that on your example to see if you get better or different behavior:

```
git clone https://go.googlesource.com/perf xperf-benchstat-new
cd xperf-benchstat-new
git fetch https://go.googlesource.com/perf refs/changes/69/309969/11 && git checkout -b change-309969 FETCH_HEAD
cd cmd/benchstat/
go build -o benchstat-new
```

**Comment by nealeckard** [comment]
Thanks for the tip! The new version does indeed seem to solve the problem of precision for widely disparate benchmarks.

![Screenshot 2023-01-09 6 17 06 PM](https://user-images.githubusercontent.com/62125412/211447280-dd7693fe-55ca-43e2-9df6-b011ff324745.png)

**Comment by thepudds** [comment]
Hi @aclements, enthusiasm for your new version of `benchstat` continues to build... 😅

**Comment by prattmic** [comment]
Closing now that https://go-review.googlesource.com/c/perf/+/309969 is in
