### ISSUE TITLE
Wrong digit precision when subtraction 2 float64

### ISSUE THREAD

**Issue by bestbug456** [golang/go#57732]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.19.4
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

Go darwin on arm64 but I was able to reproduce the problem even on playground.

### What did you do?

I was make some subtraction of float64 in a slice which need to have the exact result expected but I found out even with constant number in the array the difference is not exactly correct with an error result of e-12. I was able to reproduce the problem on playground as well: https://go.dev/play/p/RSU8PpQaZzJ

am I doing something wrong? Thanks in advance for the support.

### What did you expect to see?
A difference between 2 constant value with an error equal to 0

### What did you see instead?
A difference between 2 constant value with an error not equal to 0

**Comment by seankhliao** [comment]
see https://0.30000000000000004.com/

working as intended.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by bestbug456** [comment]
I'm definitly missing something but then why 
`22.36-math.Abs(9096.62-9118.98) > 1e-12`
Result in a correct result but
`22.36-math.Abs(info[0]-info[1]) > 1e-12`
does not? I was expecting the same result since info[0] and info[1] contain the exact same value (9096.62 and 9118.98)

**Comment by seankhliao** [comment]
https://go.dev/ref/spec#Constant_expressions

> Constant expressions are always evaluated exactly; intermediate values and the constants themselves may require precision significantly larger than supported by any predeclared type in the language.
