### ISSUE TITLE
x/pkgsite: k8s.io/api/core/v1#PersistentVolumeSpec information is wrong

### ISSUE THREAD

**Issue by zioproto** [golang/go#57758]
### What is the URL of the page with the issue?
https://pkg.go.dev/k8s.io/api/core/v1#PersistentVolumeSpec

### What is your user agent?
Not relevant

### Screenshot

![Screenshot 2023-01-12 at 14 11 29](https://user-images.githubusercontent.com/789701/212087359-61841cfb-4f98-450e-af1a-5aa0daee4eb2.png)

### What did you do?

The information is wrong:
https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/types.go#L303-L306

From the upstream source code you can see the `PersistentVolumeSpec.Capacity` is **not** optional

### What did you expect to see?

I expected to see the same `struct` for `PersistentVolumeSpec` as in the Kubernetes repository.

### What did you see instead?

I see a different version where `capacity` is marked as optional, but this is wrong.

**Comment by seankhliao** [comment]
please report this to kubernetes

**Comment by zioproto** [comment]
Thanks, I figured out now the bug is actually here:
https://github.com/kubernetes/api/blob/release-1.26/core/v1/types.go#L302-L321

I will report to Kubernetes. Thanks
