### ISSUE TITLE
net: Windows build with netgo doesn't repsect `hosts` file, can not resolve `localhost`

### ISSUE THREAD

**Issue by wxiaoguang** [golang/go#57757]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.5 windows/amd64
go version go1.20rc2 windows/amd64
</pre>

### What did you do?

Set Windows system DNS to a standard server which doesn't resolve `localhost`, then use Go net package to resolve a domain defined in local `hosts` file (`C:\Windows\System32\Drivers\etc\hosts`).

```go
package main

import (
	"fmt"
	"net"
)

func main() {
	addr, err := net.ResolveTCPAddr("tcp", "localhost:12345")
	fmt.Printf("addr=%v, err=%v\n", addr, err)
}
```

### What did you expect to see?

Go should respect `C:\Windows\System32\Drivers\etc\hosts` file and resolve `localhost` correctly with `-tags=netgo`.

### What did you see instead?

Go can not resolve localhost with `-tags=netgo`

```
C:\work> go run resolvtest.go
addr=127.0.0.1:12345, err=<nil>

C:\work> go run -tags=netgo resolvtest.go
addr=<nil>, err=lookup localhost on 8.8.8.8:53: no such host
```

**Comment by bcmills** [comment]
That seems like this `TODO` in the code, added in [CL 409234](https://go.dev/cl/409234) (attn @bradfitz @ianlancetaylor)
https://cs.opensource.google/go/go/+/master:src/net/conf.go;l=137-141;drc=d52883f443e1d564b0300acdd382af1769bf0477

(CC @neild @golang/windows)

**Comment by qmuntal** [comment]
I naively changed `etc/hosts` to `C:/Windows/System32/Drivers/etc/hosts` in https://cs.opensource.google/go/go/+/master:src/net/hook.go;l=16 and exercised the `ResolveTCPAddr` function with some addresses only known to my local hosts file, and all of them could be successfully resolved.

Everything seems to be wired up on the Windows side, only the hosts file path needs to be changed, and probably add some tests.

**Comment by zeripath** [comment]
The underlying problem is likely in:

https://github.com/golang/go/blob/d52883f443e1d564b0300acdd382af1769bf0477/src/net/conf.go#L134-L145

The result of L141 is that DNS lookups cannot check the `/etc/hosts` file (or equivalent) and thus I bet the lookups for localhost are going out to an external server and we're getting the external name for the host.
