### ISSUE TITLE
runtime: fatal: systemstack called from unexpected goroutine

### ISSUE THREAD

**Issue by derekparker** [golang/go#57763]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.19.2
</pre>

### Does this issue reproduce with the latest release?

Has not been tested.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
linux/amd64
</pre></details>

### What did you do?

Run `tmt run -arv provision -h container plan -n /remote`

See https://github.com/teemtee/tmt/issues/1735 for more information.

### What did you expect to see?

No fatal error.

### What did you see instead?

`fatal: systemstack called from unexpected goroutine`

**Comment by seankhliao** [comment]
if it's podman that's crashing it should be reported to them
it's not clear that this is an issue with go itself

**Comment by derekparker** [comment]
> if it's podman that's crashing it should be reported to them it's not clear that this is an issue with go itself

I'm happy to open an issue there as well, however this is a fatal error from the Go runtime, not user code.
