### ISSUE TITLE
net/http: NewRequest cannot handle %2F in path

### ISSUE THREAD

**Issue by gopherbot** [golang/go#5777]
by **rjohnson.id.au**:

<pre>What steps will reproduce the problem?

    urlStr := &quot;<a href="http://myhost.com/test%2Fasdf/&quot">http://myhost.com/test%2Fasdf/&quot</a>;
    req, _ = http.NewRequest(&quot;GET&quot;, urlStr, nil)
    client := new(http.Client)
    resp, err := client.Do(req)

What is the expected output?

    A request to &quot;<a href="http://myhost.com/test%2Fasdf/&quot">http://myhost.com/test%2Fasdf/&quot</a>;

What do you see instead?

    A request to &quot;<a href="http://myhost.com/test/asdf/&quot">http://myhost.com/test/asdf/&quot</a>;

Which compiler are you using (5g, 6g, 8g, gccgo)?

    N/A, but 6g

Please provide any additional information below.

Unfortunately it appears that http.NewRequest uses url.Parse, which suffers from this
issue: <a href="https://golang.org/issue/3659">https://golang.org/issue/3659</a>

I would not have added an additional bug, however the original bug seems to have been
closed with the status &quot;Fixed&quot; due to the documentation being updated to
reflect this.  Clearly this is not the correct fix for the issue.</pre>

**Comment by rsc** [comment]
I see more and more REST services that use %2F in path elements that correspond to variables, and therefore more and more reports like this one. I am reopening this for a possible fix in the Go 1.5 cycle. I have a fix in mind.
