### ISSUE TITLE
x/net: module golang.org/x/net@latest found (v0.5.0), but does not contain package golang.org/x/net 

### ISSUE THREAD

**Issue by ToyBlackHat** [golang/go#57779]
### What version of Go are you using (`go version`)?

go version go1.19.5 darwin/amd64

### Does this issue reproduce with the latest release?
 yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mike/Library/Caches/go-build"
GOENV="/Users/mike/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/mike/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/mike/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.19.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.19.5/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.19.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/80/hvrr1sbs3h5118dc82nrfb_m0000gn/T/go-build3374878071=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

When I run install,c ommand to install a library/module by go install golang.org/x/net@latest
it produces error
go: golang.org/x/net@latest: module golang.org/x/net@latest found (v0.5.0), but does not contain package golang.org/x/net

### What did you expect to see?

i expect to install this package

### What did you see instead?

this message:
go: golang.org/x/net@latest: module golang.org/x/net@latest found (v0.5.0), but does not contain package golang.org/x/net

**Comment by seankhliao** [comment]
working as intended, there's nothing for you to install at x/net
