### ISSUE TITLE
affected/package: io/fs

### ISSUE THREAD

**Issue by exyzzy** [golang/go#57772]
### What version of Go are you using (`go version`)?
1.19.5
<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?
Online, but local is:
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
Go Example fails
Go to: https://pkg.go.dev/io/fs#example-WalkDir
Click run
Output:
2009/11/10 23:00:00 stat /usr/local/go/bin/.: no such file or directory

Example fails in the exact same way my code is failing, so not helpful. Bug?

### What did you expect to see?
A working example

### What did you see instead?
A failing example

**Comment by robpike** [comment]
The error seems clear. Do your environment have a /usr/local/go/bin? If not, change the example to point to a different, extant directory and run it in an environment that can access it.

-rob

**Comment by exyzzy** [comment]
yes, it does :
% ls /usr/local/go/bin
go	gofmt

does the example work for you?

**Comment by jrathert** [comment]
Locally works for me, with 1.19.4 and 1.19.5 - are you sure you are working in the right environment? (I guess the "online example" which is probably build on Go Playground cannot work as access to local file system is forbidden)

**Comment by exyzzy** [comment]
Yes, it is my issue. Locally for this example works for me too. My failing example is a bit more complex and other parts of code are affecting the traverse with a similar stat error. Apologies. 
Still though, the example in playground as it stands could be more helpful. Probably should be commented that it needs to be run locally, or else provide a playground environment that works for the example. Thanks for looking into it.
