### ISSUE TITLE
cmd/compile: internal compiler error: 'init': value .dict (nil) incorrectly live at entry

### ISSUE THREAD

**Issue by dveeden** [golang/go#57778]
### What version of Go are you using (`go version`)?

<pre>
$ go1.20rc3 version
go version go1.20rc3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Happens with 1.20rc3 and not with 1.19.4

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go1.20rc3 env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/dvaneeden/.cache/go-build"
GOENV="/home/dvaneeden/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/dvaneeden/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/dvaneeden/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/dvaneeden/sdk/go1.20rc3"
GOSUMDB="sum.golang.org"
GOTMPDIR="/home/dvaneeden/go/tmp"
GOTOOLDIR="/home/dvaneeden/sdk/go1.20rc3/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20rc3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/tmp/foo/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/home/dvaneeden/go/tmp/go-build3602575493=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

This happens for https://pkg.go.dev/github.com/google/btree  that's used in https://github.com/pingcap/tiflow

To reproduce:
```go
package main

type FreeListG[T any] struct {
	freelist []*node[T]
}

type node[T any] struct {
}

func NewFreeListG[T any](size int) *FreeListG[T] {
	return &FreeListG[T]{freelist: make([]*node[T], 0, size)}
}

var (
	bf = NewFreeListG[*int](1024)
)

func main() {

}
```

Or with external dependencies:
```
package main

import "github.com/google/btree"

var (
	bf = btree.NewFreeListG[*int](1024)
)

func main() {

}
```
### What did you expect to see?

```
$ go version 
go version go1.19.4 linux/amd64
$ go build foo.go
$
```

### What did you see instead?

```
$ go1.20rc3 build foo.go 
# command-line-arguments
./foo.go:15:2: internal compiler error: 'init': value .dict (nil) incorrectly live at entry

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new
```

**Comment by wdvxdr1123** [comment]
compile ok with `go build -gcflags=-d=inlstaticinit=1` or ` GOEXPERIMENT=nounified go build`.

**Comment by seankhliao** [comment]
cc @golang/compiler

**Comment by wdvxdr1123** [comment]
another repro:
```
package main

type M[T comparable] struct {
	m map[T]int
}

func NewM[T comparable](x T) *M[T] {
	return &M[T]{m: map[T]int{x: 1}}
}

var foo = NewM[int](1)

func main() {

}
```

**Comment by thepudds** [comment]
Another example, in case useful, using tip as of this morning. (Seen while testing #57173 on many public modules).

```
git clone -b v1.5.14 https://github.com/mpetavy/common
cd common
go build ./...
```
Error:
```
# github.com/mpetavy/common
./app.go:92:2: internal compiler error: 'init': value .dict (nil) incorrectly live at entry
```

```
go version devel go1.20-66689c7 Tue Jan 17 15:26:07 2023 +0000 linux/amd64
```

**Comment by randall77** [comment]
@mdempsky
