### ISSUE TITLE
affected/package: go list all fails to resolve dependencies that are locally replaced in an upstream go.mod

### ISSUE THREAD

**Issue by aallawala** [golang/go#57793]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.5 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/abdurrahman_allawala/Library/Caches/go-build"
GOENV="/Users/abdurrahman_allawala/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/abdurrahman_allawala/go/pkg/mod"
GONOPROXY=""
GOOS="darwin"
GOPATH="/Users/abdurrahman_allawala/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/abdurrahman_allawala/developer/awesomeProject/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xn/vz65wjnn4q1bw0q7c8drf9kh0000gn/T/go-build390077078=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
For a given project:

go.mod
```
module awesomeProject

go 1.18

require github.com/earthly/earthly v0.0.0-20221220163335-877ec53f97a8
```

and sample test.go:
```go
package awesomeProject

import _ "github.com/earthly/earthly"
```

The following command fails:
```
go list -m -json -mod=mod all
```

### What did you expect to see?
The dependencies pulled from `github.com/earthly/earthly v0.0.0-20221220163335-877ec53f97a8`'s go.mod should resolve.

### What did you see instead?
I see the following:
```
go: github.com/earthly/earthly/ast@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
go: github.com/earthly/earthly/util/deltautil@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

This occurs for any Go module where a sub-dependency is defined with version`v0.0.0-00010101000000-000000000000` and a `replace` is used to replace that project with a local path.

This also occurs when attempting to use `https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/testbed/go.mod` where the dependency, `github.com/open-telemetry/opentelemetry-collector-contrib/receiver/signalfxreceiver v0.0.0-00010101000000-000000000000` causes a similar error:
```
go: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/signalfxreceiver@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

**Comment by bcmills** [comment]
This is by design. Per https://go.dev/ref/mod#go-mod-file-replace:
> `replace` directives only apply in the main module’s `go.mod` file and are ignored in other modules. See [Minimal version selection](https://go.dev/ref/mod#minimal-version-selection) for details.
