### ISSUE TITLE
cmd/compile: internal compiler error: assertion failed 

### ISSUE THREAD

**Issue by stephenafamo** [golang/go#57796]
### What version of Go are you using (`go version`)?

<pre>
go1.18.10 version
go version go1.18.10 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Happens with 1.18 (I have tried with 1.18.9 and 1.18.10) but does not happen with 1.19 (tried with 1.19.3 and 1.19.5)

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/stephen/Library/Caches/go-build"
GOENV="/Users/stephen/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/stephen/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/stephen/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/stephen/sdk/go1.18.10"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/stephen/sdk/go1.18.10/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.18.10"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/stephen/code/minimal/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9d/1smj789x4r5bdjccy3tqss0c0000gn/T/go-build758039394=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Ran tests for <https://github.com/stephenafamo/bob>. 

I have been able to provide a minimal example [on the playground](https://go.dev/play/p/LeGidZ2IA9C?v=goprev).

```go
package main

func main() {
	_ = Table[*SelectQuery]{}
}

type SelectQuery struct{}

type Table[T any] struct{}

func (t *Table[T]) Query() *TableQuery[T] {
	return &TableQuery[T]{}
}

func (t *Table[T]) Insert() error {
	t.Query().Apply()
	return nil
}

type TableQuery[T any] struct {
	BaseQuery[*SelectQuery]
}

type BaseQuery[E any] struct {
	Expression E
}

func (b BaseQuery[E]) Apply(mods ...Mod[E]) {
	for _, mod := range mods {
		mod.Apply(b.Expression)
	}
}

type Mod[T any] interface {
	Apply(T)
}
```

### What did you expect to see?

Compile and run the program successfully

### What did you see instead?

```sh
./prog.go:16:17: internal compiler error: assertion failed

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new

Go build failed.
```

**Comment by seankhliao** [comment]
closing as it's fixed in the latest release (1.19)
