### ISSUE TITLE
affected/package: all go src, expecially simple demo code

### ISSUE THREAD

**Issue by cocktail828** [golang/go#57804]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yep!

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/xbli10/.cache/go-build"
GOENV="/home/xbli10/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/xbli10/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/xbli10/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1852617249=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
The following is demo code.
```go
package main

import (
	"fmt"
	"time"
)

type person struct {
	Name string `json:"Name,omitempty"`
	Age  int    `json:"Age,omitempty"`
}

type testStruct struct {
	student *person
}

func (ts *testStruct) testCronFunc() {
	for {
		fmt.Println(ts.student)
		time.Sleep(1 * time.Second)
	}
}

func main() {
	tempStruct := &testStruct{
		student: &person{
			Name: "xiaobai",
			Age:  90,
		},
	}
	go tempStruct.testCronFunc()
	time.Sleep(3 * time.Second)
	tempStruct.student = &person{
		Name: "xiaoming",
		Age:  18,
	}

	// the folowing line can be 'fmt.Println', 'select', 'sycn.Mutex' ...
	// please run with or without the following line, you will get different result.
	// why? This is unreasonable! Only tell be this is about 'date race', is not convincing
	// fmt.Println("")
	for {
	}
}
```
 And you can compile with '-S' to get the assembly code.
```
go tool compile -S demo.go > x.S

...
	0x00aa 00170 (demo.go:32)	MOVL	$3000000000, AX
	0x00af 00175 (demo.go:32)	CALL	time.Sleep(SB)
	0x00b4 00180 (demo.go:33)	LEAQ	type.main.person(SB), AX
	0x00bb 00187 (demo.go:33)	NOP
	0x00c0 00192 (demo.go:33)	CALL	runtime.newobject(SB)          --- here,  the new object is create, but no place to init. let alone assign it to `tempStruct.student`
	0x00c5 00197 (demo.go:42)	PCDATA	$1, $-1
	0x00c5 00197 (demo.go:42)	XCHGL	AX, AX
	0x00c6 00198 (demo.go:1)	JMP	197
	0x00c8 00200 (demo.go:1)	NOP
	0x00c8 00200 (demo.go:24)	PCDATA	$1, $-1
	0x00c8 00200 (demo.go:24)	PCDATA	$0, $-2
	0x00c8 00200 (demo.go:24)	CALL	runtime.morestack_noctxt(SB)
	0x00cd 00205 (demo.go:24)	PCDATA	$0, $-1
	0x00cd 00205 (demo.go:24)	JMP	0
```

### What did you expect to see?
```
&{xiaobai 90}
&{xiaobai 90}
&{xiaobai 90}
&{xiaobai 90}
&{xiaoming 18}
&{xiaoming 18}
&{xiaoming 18}
...
```

### What did you see instead?
```
&{xiaobai 90}
&{xiaobai 90}
&{xiaobai 90}
&{xiaobai 90}
&{xiaobai 90}
...
```

**Comment by randall77** [comment]
There's no synchronization in this code. There's no guarantee that the second write done to `tempStruct.student` by the main goroutine is visible to any other thread. In that situation. You need some sort of synchronization (channel, mutex, etc.) to make that write visible.
The compiler is dead-code eliminating that write, as no goroutine is required to see it.
