### ISSUE TITLE
x/pkgsite: package removal request for github.com/fastbpmn/go-study

### ISSUE THREAD

**Issue by fastbpmn** [golang/go#57805]
### What is the path of the package that you would like to have removed?

 
 https://pkg.go.dev/github.com/fastbpmn/go-study
 
### Are you the owner of this package?

yes
 
### What is the reason that you could not retract this package instead?

I am new to publishing packages & made way too many mistakes & now have way too many versions of the package out there. I should've done it in pre-release first but was arrogant & thought the package was simple enough to push out there without pre-releases.

**Comment by seankhliao** [comment]
please use retract directives for this.

**Comment by bcmills** [comment]
@fastbpmn, the `retract` directive must be included in the latest release of the module.

Try changing the directive to `retract [v1.0.0, v1.0.3]` and tagging it `v1.0.3` (which would then retract itself).

**Comment by fastbpmn** [comment]
> @fastbpmn, the `retract` directive must be included in the latest release of the module.
> 
> Try changing the directive to `retract [v1.0.0, v1.0.3]` and tagging it `v1.0.3` (which would then retract itself).

Thank you for your help，I will try it tomorrow.

**Comment by fastbpmn** [comment]
I didn't have time to reply yesterday, this issue has been solved, thank you for your help.
