### ISSUE TITLE
go get -u ./... does not handle branches as expected

### ISSUE THREAD

**Issue by LeeBrotherston** [golang/go#57817]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.5 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

I believe that this is the latest release yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/lee/Library/Caches/go-build"
GOENV="/Users/lee/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/lee/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/lee/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/opt/homebrew/Cellar/go/1.19.5/libexec"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.19.5/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/lee/opshelm/event-processor/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/j3/qv7s4b3j6jdd5h58n8jncnz80000gp/T/go-build235891349=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

- Create a github repo with a module that you wish to import to your project
- Create a branch to develop a new version of that module and commit new code to that branch
- Use the new branch in your project using `go get github.com/thing/something@my-new-branch`
- Do some work / time passes ....
- Update dependencies in your project using `go get -u ./...`

### What did you expect to see?

That the module in `github.com/thing/something` would be updated to the latest commit in `my-new-branch`

### What did you see instead?

That the module in `github.com/thing/something` was updated to the latest commit in `main`

**Comment by seankhliao** [comment]
working as expected.
dependencies are recorded as commits, with no reference back to the original branch.
`go get -u` points to `@latest`, which is `main`
