### ISSUE TITLE
cmd/compile: internal compiler error: NewBulk too big: nbit=60759 count=506114 nword=1899 size=961110486

### ISSUE THREAD

**Issue by vsin12** [golang/go#57832]
### What version of Go are you using (`go version`)?

<pre>
$ go version 
1.18.8
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/userName/Library/Caches/go-build"
GOENV="/Users/userName/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS="-mod=vendor"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/userName/projects/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/userName/projects/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18.8"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/userName/projects/go/src/github.com/terraform-providers/terraform-provider-oci/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/t3/1vyzd0fj2msgmtt_8bmch3sr0000gn/T/go-build1510721642=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
Tried to run a gotest in Intellij and vscode.

Regular builds run just fine, but running or debugging gotest gives us this issue. One of the tests that I tried to run - https://github.com/oracle/terraform-provider-oci/blob/master/internal/integrationtest/core_vcn_test.go#L62

All tests give the same issue.

### What did you expect to see?

successful compilation

### What did you see instead?

# github.com/oracle/terraform-provider-oci/internal/integrationtest [github.com/oracle/terraform-provider-oci/internal/integrationtest.test]
<autogenerated>:1: internal compiler error: NewBulk too big: nbit=60759 count=506114 nword=1899 size=961110486

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new

**Comment by randall77** [comment]
Closing as dup of #26560 and #33437 . The input code is just too big for the compiler to handle.
