### ISSUE TITLE
all: update release-branch.go1.20 with changes for Go 1.20 final

### ISSUE THREAD

**Issue by cherrymui** [golang/go#57854]
The release-branch.go1.20 branch has updated to commit 9088c69 at the master branch. The master branch is then soft reopen for 1.21 development. At this point, any changes targeting Go 1.20 release need to be explicitly cherry-picked to the release-branch.go1.20 branch.

This is the tracking umbrella issue to collect the remaining CLs that need to land on the release branch, and sort them all.

**Comment by mdempsky** [comment]
https://go.dev/cl/461686 should go into 1.20. It's just been reviewed. I think it's ready to merge and backport, pending confirmation on the approval process for that.

**Comment by cuonglm** [comment]
CL https://go-review.googlesource.com/c/go/+/461759 should go into 1.20, it's reviewed and waiting for trybot.

**Comment by bcmills** [comment]
#57903 too. (Probably https://go.dev/cl/462555?)

**Comment by anitgandhi** [comment]
Hello!

Hopefully I'm not asking out of line - can CL https://go-review.googlesource.com/c/go/+/410496 be included in 1.20? 
It was reviewed and approved a while ago but just got merged today. I'm not sure if it constitutes too much of a behavior change to me included this late in the cycle. 
If it can be included, that would be awesome; it would be a huge help for our organization.

Thanks in advance!

**Comment by cherrymui** [comment]
That CL addresses #52113, which is not in Go1.20 milestone and it seems the issues has existed for a long time. So it seems not critical to be included this late in the cycle. At this point we weigh more on stability than feature improvements. If you think it is critical, feel free to comment. Thanks for understanding.

**Comment by bcmills** [comment]
https://go.dev/cl/459715 should be backported to the release branch.

(I had thought it would be submitted before the branch was even cut, but apparently it's been sitting in the `needs-review` queue for ~10 days?)

**Comment by cherrymui** [comment]
Hmmm, I was doing +1s for the `needs-review` queue this week and I never saw that CL. Not sure what made it not included in the queue...

**Comment by thanm** [comment]
I'd like to request that https://go.dev/cl/462955 be cherry-picked onto the 1.20 release branch. It is a very low-risk change, and it fixes problems with incorrect coverage data reports (no easy workaround).

**Comment by randall77** [comment]
Please also backport https://go-review.googlesource.com/c/go/+/463295

**Comment by mdempsky** [comment]
@thanm I see https://go.dev/cl/462756 is in that CL stack. Does it need to be cherry picked to 1.20 too, or just 462955?

@randall77 SGTM.

**Comment by heschi** [comment]
cc @golang/release

**Comment by thanm** [comment]
@mdempsky you asked about https://go.dev/cl/462756 , ideally it would be nice to have that as well.  It is less serious but is also very low risk. Thanks.

**Comment by mknyszek** [comment]
We're approaching the release and all the above CLs seem to be in. I'm going to close this issue assuming nothing else is going in. Please comment and reopen if that's not the case. Thanks!
