### ISSUE TITLE
`go get` doesn't work over proxy

### ISSUE THREAD

**Issue by sagittaracc** [golang/go#57895]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.4 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\arutyunyan\AppData\Local\go-build
set GOENV=C:\Users\arutyunyan\AppData\Roaming\go\env  
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\arutyunyan\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\arutyunyan\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.19.4
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\xampp\htdocs\sandbox\go\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\ARUTYU~1\AppData\Local\Temp\go-build519211700=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

```
set http_proxy=http://user:pass@proxy.server.com:port
git config --global http.proxy http://user:pass@proxy.server.com:port
go get -u github.com/go-sql-driver/mysql
```

### What did you expect to see?
Successful installation of the package

### What did you see instead?
```
go: github.com/go-sql-driver/mysql@v1.7.0: verifying module: github.com/go-sql-driver/mysql@v1.7.0: Get "https://proxy.golang.org/sumdb/sum.golang.org/supported": dial tcp 74.125.131.141:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

**Comment by seankhliao** [comment]
see the `GOPRIVATE` env var.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
