### ISSUE TITLE
x/website: high-res favicon for system integration

### ISSUE THREAD

**Issue by Deleplace** [golang/go#57899]
## What did you do?

The use case is "Open the online playground as if it was a standalone app".

In Google Chrome (desktop), there is a very nice feature "Create Shortcut". Its creates an shortcut for the OS window manager, that opens the website in its own window, as if it were an app.

- Open Google Chrome
- Navigate to https://go.dev/play/
- Top Right `⋮` (kebab button) > More Tools > Create Shortcut...
- Check the box "Open as window"
- Click Create

It is very well integrated with OSX. Not so much with Ubuntu. YMMV.

![image](https://user-images.githubusercontent.com/13508141/213183573-544f18ff-118f-4fa4-b1b7-cea8ff561477.png)

![image](https://user-images.githubusercontent.com/13508141/213183599-b5ef2129-3431-4155-b17b-c58eda6ad9ee.png)

## What did you expect to see?

A new Gopher icon shows up in my dock  (I'm on OSX)

## What did you see instead?

A new Gopher icon shows up in my dock, but it is blurry.

![image](https://user-images.githubusercontent.com/13508141/213183758-6bb2c253-0297-4bd0-9683-ff5ec41a619f.png)

In my screenshot,
- the 4 icons on the left are actual desktop apps
- the 3 icons on the right are shortcuts to the webapps Google Meet, Youtube and Youtube Music, which have high-res favicon
- I think the Gopher icon is https://go.dev/favicon.ico , which is not high-res.

I suggest we fix this with either a high-res raster favicon, or a vector favicon.

**Comment by seankhliao** [comment]
cc @golang/tools-team

**Comment by Deleplace** [comment]
Here is my suggestion, I can turn it into a PR after discussion.

I looked at a few guides [1](https://css-tricks.com/svg-favicons-and-all-the-fun-things-we-can-do-with-them/), [2](https://dev.to/masakudamatsu/favicon-nightmare-how-to-maintain-sanity-3al7), [3](https://caniuse.com/link-icon-svg), [4](https://developer.mozilla.org/en-US/docs/Web/Manifest/icons), [5](https://developers.google.com/search/docs/appearance/favicon-in-search?visit_id=637612551778130156-3112088115&rd=1#guidelines)

I propose to add 3 image files and 3 lines of HTML, to fit for most popular OS and browsers.

- Keep the existing [`favicon.ico`](https://go.dev/favicon.ico) at root path. It contains 2 layers: one 16x16 and one 32x32
<img width="202" alt="image" src="https://user-images.githubusercontent.com/13508141/214067970-9797a6f2-a987-460f-bd2f-0f44ccfaaf2f.png">

- Create and add a larger image `/images/gopher.png` with dimensions 144x144  (it [must](https://developers.google.com/search/docs/appearance/favicon-in-search?visit_id=637612551778130156-3112088115&rd=1#guidelines) be a multiple of 48x48)
- Create and add a larger image `/images/gopher-plain.png` with a white background (no transparency)
- Add an image `/images/gopher.svg`  (an equivalent of [this one](https://commons.wikimedia.org/wiki/File:Go_gopher_favicon.svg) is already approved for use)
- Add these lines in the HTML `<head>`:
```
    <link rel="icon" href="/images/gopher.png" sizes="any">
    <link rel="apple-touch-icon" href="/images/gopher-plain.png"/>
    <link rel="icon" href="/images/gopher.svg" type="image/svg+xml">
```

To test what the change would look like, I created color variations for each resources and uploaded 5 static sites to an 5 HTTPS servers.

- **A)** the original favicon file, but with the 2 low-res layers colored in pink and brown
<img width="203" alt="image" src="https://user-images.githubusercontent.com/13508141/214071012-e94e9c7c-70ff-4d5b-92b0-9404e31e1c5e.png">

- **B)** a high-res transparent PNG `gopher.png` colored in green
<img width="517" alt="image" src="https://user-images.githubusercontent.com/13508141/214071417-beb2855e-e3fe-4724-98de-6c7176ab8a24.png">

- **C)** a vector file `gopher.svg` colored in purple
<img width="527" alt="image" src="https://user-images.githubusercontent.com/13508141/214071913-43548be5-b6e1-48f3-bd91-d6d2383e32a8.png">

The goal is to verify that all modern system correctly take into account either the SVG (best) or the high-res PNG (second best).

The static websites are name [a](https://gopher-favicon-a.web.app), [ab](https://gopher-favicon-ab.web.app), [ac](https://gopher-favicon-ac.web.app), [bc](https://gopher-favicon-bc.web.app), [abc](https://gopher-favicon-abc.web.app), reflecting which resources they contain out of A, B, C.

## Results

### Chrome (OSX)

#### Tabs

<img width="1229" alt="OSX_Chrome" src="https://user-images.githubusercontent.com/13508141/214073389-33853c75-8933-4296-8b87-8d2821d3d5b9.png">

Chromes "sees" all of the favicon resource types. It correctly prefers SVG when available, then PNG, then ICO.

#### Dock

_a, ab, ac, bc, abc_

<img width="295" alt="OSX_macbook_dock" src="https://user-images.githubusercontent.com/13508141/214073703-d717a656-3fcf-4953-b184-3e58037767ee.png">

The Dock shortcut correctly displays the SVG.  It does not properly handles the high-res PNG, though.

## Firefox (OSX)

### Tabs

<img width="1261" alt="OSX_Firefox" src="https://user-images.githubusercontent.com/13508141/214074318-a1c220b9-fd72-4915-bcb2-748dc85445a3.png">

Firefox "sees" all of the favicon resource types. It correctly prefers SVG when available, then PNG, then ICO.

## Safari (OSX)

### Tabs

<img width="1199" alt="OSX_Safari" src="https://user-images.githubusercontent.com/13508141/214074571-19abdb81-aaeb-48ec-a1f6-d17bea7232de.png">

Safari [does not support](https://caniuse.com/link-icon-svg) SVG favicons. It [does support](https://caniuse.com/link-icon-png) the high-res PNG.

## iPhone 7 (iOS 15.7)

### Home screen

![iphone_7_home_screen](https://user-images.githubusercontent.com/13508141/214076214-1513a7d0-4c31-4f30-91d3-2bca0e01937c.png)

ICO and SVG not supported as home screen shortcut icons.

The transparent PNG background turned black, so instead we'll need a distinct file `<link rel="apple-touch-icon" href="/images/gopher-plain.png"/>` with a plain white background.

## iPad Pro (iOS 17.7)

### Safari tabs

<img width="1066" alt="ipad_pro_safari" src="https://user-images.githubusercontent.com/13508141/214076278-47109066-deca-4abd-afc8-b055015b579e.png">

SVG not supported.

### Home screen

![ipad_pro_home_screen](https://user-images.githubusercontent.com/13508141/214076311-91c2f385-0c3a-4c38-a185-21ec8bb1f124.png)

ICO and SVG not supported as home screen shortcut icons.

The transparent PNG background turned black, so instead we'll need a distinct file `<link rel="apple-touch-icon" href="/images/gopher-plain.png"/>` with a plain white background.

## Android 12 (Samsung Galaxy S10)

### Home screen

![samsung_galaxy_S10_home_screen](https://user-images.githubusercontent.com/13508141/214076366-f4e7e323-8325-46ba-93a5-9ced0b07f16c.jpg)

ICO not supported.

PNG takes precedence over SVG, for some reason.

## Android 13 (Pixel 5)

### Home screen

![pixel_5_home_screen](https://user-images.githubusercontent.com/13508141/214076410-36bc4129-bff0-4ce6-b91f-01bbcd6a9e04.png)

ICO not supported.

PNG takes precedence over SVG, for some reason.

**Comment by Deleplace** [comment]
Thank you all, it looks great now in my Mac's dock!

<img width="308" alt="image" src="https://user-images.githubusercontent.com/13508141/225695580-3bcf1dc5-b2df-4667-bd16-21fc81c60207.png">
