### ISSUE TITLE
x/tools/gopls: tests leave behind a lot of data in `.cache/gopls`

### ISSUE THREAD

**Issue by findleyr** [golang/go#57900]
```
#!watchflakes
post <- repo == "tools" && builder == "aix-ppc64"
```

Starting last night, the aix-ppc64 builder started failing frequently on both the main repo and x/tools. (I noticed because watchflakes filed ~30 flakes for x/tools tests related to aix-ppc64).

CC @golang/release

**Comment by findleyr** [comment]
Ah, this appears to be the problem:
/.cache/gopls/7f4281e2/analysis/13: no space left on device

CC @adonovan, in case this is related to gopls file caching.

**Comment by cherrymui** [comment]
cc @golang/aix

**Comment by bcmills** [comment]
I think this is a defect in the `gopls` test suite: it appears to me that the tests are leaving behind a _lot_ of data in `~/.cache/gopls`.

I ran `rm -r /.cache/gopls` on a `gomote` session and it appears to have (slowly!) reclaimed around 7GB (of a 10GB) root partition.

**Comment by bcmills** [comment]
Independently, we should double-check the `gopls` cache invalidation logic to make sure we don't end up consuming too much space in end users' `.cache` directories. 😅

**Comment by findleyr** [comment]
If this is fixed in the builder, we can repurpose this issue for following up on cache usage.

@bcmills thank you for investigating.

**Comment by adonovan** [comment]
> I think this is a defect in the gopls test suite: it appears to me that the tests are leaving behind a lot of data in ~/.cache/gopls.

I think you're right. I suspect that because it takes so long (over a minute) just to walk the directory tree at full speed, at least on some machines, none of the test processes ever even starts sweeping garbage before it is terminated.

**Comment by findleyr** [comment]
That flake is #59475, which I'm looking at.

**Comment by bcmills** [comment]
I just cleared off many GiB of `.cache/gopls` from the `freebsd-arm64-dmgk` builder (https://build.golang.org/log/40dc9e3bd385f3f68c8a12032377c97a91245741).
