### ISSUE TITLE
net/rpc: data race on non-net transport

### ISSUE THREAD

**Issue by dvyukov** [golang/go#5792]
<pre>Here is the reproducer:
<a href="https://golang.org/cl/10613043/diff/3001/src/pkg/net/rpc/server_test.go">https://golang.org/cl/10613043/diff/3001/src/pkg/net/rpc/server_test.go</a>

Report is below.

The gist: it's impossible to use net/rpc client/server with any non-thread-safe
transport as pipe or socketpair. It's inevitably produces races between read/write and
close. Such races corrupt arbitrary files and write data to random network connections.

=== RUN TestUnixPipe
==================
WARNING: DATA RACE
Read by goroutine 59:
  os.(*File).read()
      src/pkg/os/file_unix.go:175 +0x5b
  os.(*File).Read()
      src/pkg/os/file.go:95 +0xb9
  bufio.(*Reader).fill()
      src/pkg/bufio/bufio.go:119 +0x272
  bufio.(*Reader).Read()
      src/pkg/bufio/bufio.go:187 +0x3b1
  io.ReadAtLeast()
      src/pkg/io/io.go:284 +0x11a
  io.ReadFull()
      src/pkg/io/io.go:302 +0x7c
  encoding/gob.decodeUintReader()
      src/pkg/encoding/gob/decode.go:65 +0xba
  encoding/gob.(*Decoder).recvMessage()
      src/pkg/encoding/gob/decoder.go:73 +0x81
  encoding/gob.(*Decoder).decodeTypeSequence()
      src/pkg/encoding/gob/decoder.go:159 +0x92
  encoding/gob.(*Decoder).DecodeValue()
      src/pkg/encoding/gob/decoder.go:223 +0x124
  encoding/gob.(*Decoder).Decode()
      src/pkg/encoding/gob/decoder.go:202 +0x227
  net/rpc.(*gobClientCodec).ReadResponseHeader()
      src/pkg/net/rpc/client.go:218 +0x5d
  net/rpc.(*Client).input()
      src/pkg/net/rpc/client.go:106 +0x118

Previous write by goroutine 57:
  os.(*file).close()
      src/pkg/os/file_unix.go:110 +0x164
  os.(*File).Close()
      src/pkg/os/file_unix.go:99 +0x43
  net/rpc.(*gobClientCodec).Close()
      src/pkg/net/rpc/client.go:226 +0x48
  net/rpc.(*Client).Close()
      src/pkg/net/rpc/client.go:280 +0xc6
  net/rpc.TestUnixPipe()
      src/pkg/net/rpc/server_test.go:567 +0x3d5
  testing.tRunner()
      src/pkg/testing/testing.go:361 +0x10c

Goroutine 59 (running) created at:
  net/rpc.NewClientWithCodec()
      src/pkg/net/rpc/client.go:196 +0xd5
  net/rpc.NewClient()
      src/pkg/net/rpc/client.go:186 +0x18d
  net/rpc.TestUnixPipe()
      src/pkg/net/rpc/server_test.go:566 +0x3c7
  testing.tRunner()
      src/pkg/testing/testing.go:361 +0x10c

Goroutine 57 (running) created at:
  testing.RunTests()
      src/pkg/testing/testing.go:441 +0xaef
  testing.Main()
      src/pkg/testing/testing.go:373 +0xab
  main.main()
      net/rpc/_test/_testmain.go:74 +0xda
==================</pre>

**Comment by rsc** [comment]
We fixed #7970, so now there is no longer a race for pipes and socketpairs. I think everything is OK now.
