### ISSUE TITLE
x/pkgsite: not picking up latest module version name

### ISSUE THREAD

**Issue by djthorpe** [golang/go#57929]
### What is the URL of the page with the issue?
https://pkg.go.dev/github.com/ggerganov/whisper.cpp/bindings/go

### What is your user agent?
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

### Screenshot
![image](https://user-images.githubusercontent.com/2916361/213553987-8b5d43f4-a7e2-4e97-879f-0caa552b5cfe.png)

### What did you do?
Attempted to fetch the latest module version v1.1.0 but says "not found"

### What did you expect to see?
Expected to see the module version v1.1.0 (a published tag in the repository 

https://github.com/ggerganov/whisper.cpp/releases/tag/v1.1.0

### What did you see instead?
Want pkg.go.dev to reflect latest module version, v1.1.0

**Comment by seankhliao** [comment]
working as intended, 
the module is in a subdirectory `bindings/go`, it needs special tags
see https://go.dev/ref/mod#vcs-version
