### ISSUE TITLE
access: gerrit approvers

### ISSUE THREAD

**Issue by qmuntal** [golang/go#57936]
Hi,

I'd like to request "approvers" access https://go-review.googlesource.com/#/admin/groups/1005,members for [quimmuntal@gmail.com](https://go-review.googlesource.com/q/owner:quimmuntal).

See https://go.dev/wiki/GerritAccess

**Comment by seankhliao** [comment]
cc @golang/release

**Comment by cherrymui** [comment]
Hi Quim,

Thank you for contributing to the Go project! I've added you to the approvers group now.

Please be familiar with the rules for voting and submitting changes as described at https://golang.org/wiki/GerritAccess#approver-access-approvers. If you're unsure or have any questions, please don't hesitate to ask us.

Thank you again for contributing, your help is greatly appreciated!
