### ISSUE TITLE
x/pkgsite: package removal request for github.com/erdaltsksn/go-response

### ISSUE THREAD

**Issue by erdaltsksn** [golang/go#57933]
### What is the path of the package that you would like to have removed?

[github.com/erdaltsksn/go-response](github.com/erdaltsksn/go-response)

### Are you the owner of this package?

Yes

### What is the reason that you could not retract this package instead?

I removed the repository and moved the package inside the another go project's `pkg` folder. There aren't any dependents for this package.

**Comment by findleyr** [comment]
Done.
