### ISSUE TITLE
affected/package: src/encoding/json/encode.go

### ISSUE THREAD

**Issue by skyterra** [golang/go#57935]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.15 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="arm64"
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
</pre></details>

### What did you do?

When I marshal a nil slice, the json output 'null'; but in json language, empty array should output '[]' not 'null'

func main() {
	var a []int
	v, _ := json.Marshal(a)
	fmt.Println("json:", string(v))
}

// output
json: null

### What did you expect to see?
//ouput
json: []

### My question?
The following code show the logic, if the slice variable's value is nil, then write 'null', i want to know the reason.

``` go
func (se sliceEncoder) encode(e *encodeState, v reflect.Value, opts encOpts) {
	if v.IsNil() {
		e.WriteString("null")
		return
	}
        ...
}
```

**Comment by seankhliao** [comment]
working as intended.
