### ISSUE TITLE
x/pkgsite: double magnifying glass icons in search input element on iOS

### ISSUE THREAD

**Issue by willfaught** [golang/go#57948]
### What is the URL of the page with the issue?

pkg.go.dev

### What is your user agent?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15

### Screenshot

![IMG_0212](https://user-images.githubusercontent.com/63830/213887349-96e54be2-5a92-4469-8f19-3946886ebade.png)

### What did you do?

Navigate there in iOS 16.2 Safari.

### What did you expect to see?

One magnifying glass icon by the input element.

Moving the cursor to the far left, the input element retains focus and you can still type.

### What did you see instead?

Two magnifying glass icons by the input element.

When I typed "pow", then moved the cursor back to the beginning of the input, and then past it to the left, the cursor is lost, and you have to tap the input element again for it to have focus. I assume these two issues are related.

**Comment by carlmjohnson** [comment]
This has bothered me forever but I’m always immediately distracted and forget to file a bug. Thank you.

**Comment by hyangah** [comment]
Either make it `type="text"` or
skip pkgsite's own icon for Safari or
disable the browser styling with css magic.

**Comment by jamalc** [comment]
No, gopherbot closes related issues after a fix is merged.
