### ISSUE TITLE
cmd/asm: wrong AVX512 instructions are miscompiled

### ISSUE THREAD

**Issue by WojciechMula** [golang/go#57952]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

I compile this simple assembly procedure:

```go
TEXT ·procedure(SB), NOSPLIT|NOFRAME, $0-8
    VMOVDQA32.Z Z0, Z1
    RET
```

Because I used ``.Z`` suffix, it means the instruction needs a mask register. That is missing in this case -- it should be something like ``VMOVDQA32.Z Z0, K1, Z1``.

### What did you expect to see?

Assembler message pointing out a syntax error.

### What did you see instead?

The procedure is compiled into the following instructions (the output from GNU objdump):

```
0000000000457c80 <main.procedure.abi0>:
  457c80:	62 f1 7d c8 7f c1    	vmovdqa32 %zmm0,%zmm1{z}
  457c86:	c3                   	retq   
  457c87:	cc                   	int3   
  457c88:	cc                   	int3   
  457c89:	cc                   	int3   
  457c8a:	cc                   	int3   
  457c8b:	cc                   	int3   
  457c8c:	cc                   	int3   
  457c8d:	cc                   	int3   
  457c8e:	cc                   	int3   
  457c8f:	cc                   	int3   
```

When the program is run, we get a CPU exception:

```
SIGILL: illegal instruction
PC=0x457c80 m=0 sigcode=2
instruction bytes: 0x62 0xf1 0x7d 0xc8 0x7f 0xc1 0xc3 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc
```

**Comment by randall77** [comment]
So should we produce an error in this case then? i.e., if there is a `.Z` suffix but no mask register specified?

**Comment by WojciechMula** [comment]
> So should we produce an error in this case then? i.e., if there is a `.Z` suffix but no mask register specified?

Yes, it's an error. An instruction **without** `.Z` suffix is valid in two forms, for instance:

```
VMOVDQA32 Z0, Z1 // a regular move without masking
VMOVDQA32 Z0, K1, Z1 // merge-move using mask K1
```

But in the case of zeroing variant `VMOVDQA32.Z` a mask register is mandatory - this particular instruction means: copy elements for which the bit in the mask is 1, write zeros when the bit is 0. Without a mask reg the instruction has no sense.

**Comment by randall77** [comment]
@quasilyte

**Comment by wojciech-sneller** [comment]
Thank you for such a quick fix! Great.
