### ISSUE TITLE
cmd/vet: stdmethods should not complain about `Unwrap() []error` on go 1.19

### ISSUE THREAD

**Issue by fishy** [golang/go#57978]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/fishy/.cache/go-build"
GOENV="/home/fishy/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/fishy/.gopath/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/fishy/.gopath"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.19"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.19/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3642394640=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Implement `Unwrap() []error` for error type for _library code_, so that even though the library itself has `go 1.19` in its `go.mod`, it will play nicely when the _user_ of the library is using go 1.20+.

### What did you expect to see?
`go vet` does not complain about it.

### What did you see instead?
`go vet` complains:
```
# github.com/reddit/baseplate.go/errorsbp
errorsbp/batch.go:12:2: method Unwrap() []error should have signature Unwrap() error
errorsbp/batch.go:202:17: method Unwrap() []error should have signature Unwrap() error
# github.com/reddit/baseplate.go/errorsbp_test
errorsbp/batch_test.go:272:23: method Unwrap() []error should have signature Unwrap() error
```

(the library code in this example is https://github.com/reddit/baseplate.go/blob/7c2e214c9d12ad278fdc87585bf68144feb2a585/errorsbp/batch.go#L199-L204)

**Comment by neild** [comment]
Are you sure you're using a recent version of `vet`? It should accept `Unwrap() []error`:

https://go.googlesource.com/tools/+/refs/tags/v0.5.0/go/analysis/passes/stdmethods/testdata/src/a/a.go#74

**Comment by fishy** [comment]
@neild `go vet` comes from the `go` itself, so I believe someone needs to backport that to 1.19 tree?

**Comment by seankhliao** [comment]
If you're writing code for 1.20, shouldn't you be using the 1.20 toolchain for vet?

**Comment by fishy** [comment]
> If you're writing code for 1.20, shouldn't you be using the 1.20 toolchain for vet?

This is _library code_, we want to make sure that it still works on go 1.19, so we still use go 1.19 toolchain (in addition to 1. 20 toolchain) on ci.

Basically tl;dr is that this is library code that should work in both 1.19 and 1.20. `Unwrap() []error` itself doesn't really break any 1.19 code, it's just ignored by 1.19 `errors` APIs (we provided another api for 1.19 users).

**Comment by fishy** [comment]
Now 1.19 is no longer supported I guess this issue is moot.
