### ISSUE TITLE
x/website: Fix link to Security Policy

### ISSUE THREAD

**Issue by Deleplace** [golang/go#57971]
At https://go.dev/project , the "security policy" link goes to https://go.dev/security/ but it would be more accurate to link to https://go.dev/security/policy

**Comment by findleyr** [comment]
SGTM -- I see that @ianlancetaylor has already reviewed.

**Comment by IanoNjuguna** [comment]
Hey @findleyr can I tackle this issue?

**Comment by findleyr** [comment]
@IanoNjuguna it looks like there is a pending CL already.

**Comment by IanoNjuguna** [comment]
> @IanoNjuguna it looks like there is a pending CL already.

Alright then.
