### ISSUE TITLE
x/tools/gopls: incremental gopls scaling

### ISSUE THREAD

**Issue by findleyr** [golang/go#57987]
# Incremental gopls

This is an umbrella issue to track the work we've been doing to change the way gopls scales (and significantly reduce memory usage and CPU on large codebases). We've been working off an internal design, but I wanted to share some of that here and have a public issue to track the work.

The main goal of this project is to use on-disk export data and indexing to allow gopls to persist data across sessions, reloading on-demand, thereby reducing its overall memory footprint and startup time.

As a result of this change, gopls memory usage (at least related to package information) will be O(open packages), rather than O(workspace). Furthermore, we will break global relationships between elements of gopls' cache, simplifying gopls' execution model and eliminating multiple categories of bugs.

## Background

Gopls, as it very recently existed, was a monolithic build system. Certain algorithms relied on a global package graph containing the full set of workspace packages. For example, to find references to a given identifier, gopls simply walked all packages in the reverse transitive cone of the declaring package(s) and checked `types.Info.Uses` for references to the declared object. In order for this algorithm to be correct and sufficiently fast, gopls must hold all type-checked packages in memory (including many redundant intermediate test variants!).

We can't solve gopls' scaling problems until we rewrite these algorithms and fix all the places where gopls makes assumptions of global identity. This is what we've been working on.

## High level plan

1. [x] Design a shallow export data format that does not bundle its transitive closure.
2. [x] Add a mechanism for on-disk caching.
3. [x] Implement package analysis using export data.
4. [x] Rewrite workspace-wide queries to use indexes that are independent of `types.Package` or `types.Object` identity.
   - [x] workspace symbols
   - [x] references
   - [x] call hierarchy
   - [x] implementations
   - [x] rename (may require re-implementing `types.Identical` and `types.AssignableTo` with a new notion of object identity, c.f. #57497)
   - [x] Unimported completion
5. [x] Separate the concept of a "syntax package" (something containing AST and types.Info) from an "export package" (a `types.Package` with type information for exported symbols). Syntax packages are used to fully understand the syntax a user is working on.  Export packages are used for type checking. Currently, gopls has a concept of "exported parse mode", which produces a syntax package on a truncated AST. This exists to reduce memory, but means that syntax packages may be partial, a source of many historical and current bugs.  All current uses of partial packages in the package graph can (and must) be eliminated or replaced with a judicious use of parsing or type-checking on-demand.
6. [x] Create a control plane to manage package information that must be preserved in memory vs re-computed on demand or transiently cached.
7. [x] When importing during type-checking, use export packages for packages outside the workspace. For now, continue to produce syntax packages for all packages inside the workspace.
8. [x] Persist and load export packages from disk.
9. [x] Load xrefs and methodset indexes from disk, rather than hanging them off of syntax packages.
10. [x] Drop all syntax packages, except those with open files.
11. [x] Implement precise pruning
12. [x] Investigate holding on to packages imported by open packages, to reduce re-type-checking latency.
13. [ ] Revisit diagnostic storage and retrieval: diagnostics are re-accessed in multiple places, assuming they will be free to retrieve: fix TestBadlyVersionedModule
14. [x] ~Improve the UX around indexing (better progress notifications, partial results, etc).~

**Comment by ShoshinNikita** [comment]
Using `gopls@master` I noticed that diagnostics are updated with a significant delay in comparison with `gopls@v0.11.0`. And this delay is the same for both small and large projects.

I managed to find a CL that introduced this behavior. Is is https://go.dev/cl/477979 (`gopls/internal/lsp: reorder the way we compute diagnostics`):

| `gopls@83c1ba19d` (before the CL) | `gopls@d52bc5689` (after the CL) |
| --------------------------------- | -------------------------------- |
|  <video src="https://user-images.githubusercontent.com/30220965/230233836-afa8b6ed-742d-477b-94b1-9a1f2977f1f0.mp4">                            | <video src="https://user-images.githubusercontent.com/30220965/230233943-231886d3-880c-4499-8fd5-84f21875a5fa.mp4"> |

I would like to ask, is it an intended behavior? For me this delay looks like a performance issue.

**Comment by findleyr** [comment]
@ShoshinNikita this is unintended.

We set the diagnostics delay to a higher number, and I think that made it more apparent that certain type-checking errors are not getting published immediately for the recently changed file.

The intended behavior is that you get diagnostics immediately for the file you are editing.

I can reproduce.
