### ISSUE TITLE
access: plan9: add 9front developers to the plan 9 group

### ISSUE THREAD

**Issue by oridb** [golang/go#58011]
Right now, the only plan 9 maintainers are associated with 9legacy, which means that if the builders break, the 9front developers have no visibility into the breakage, which makes keeping up with fixes.

When talking about this at the runtime office hours, I was told that to get notifications, we should get the 9front developers into the 'plan9' group.

I think the people included should be myself (@oridb), moody (@majiru), and if they want, @psilva261.

I believe the groups should be https://github.com/orgs/golang/teams/port-maintainers, https://github.com/orgs/golang/teams/plan9 -- but both of those are 404s for me, so it's hard to say.

(I'm not sure if this is a proposal, but I didn't see a more appropriate option in the list)

**Comment by seankhliao** [comment]
cc @golang/release
