### ISSUE TITLE
go tool objdump can't decode VSQRTSS

### ISSUE THREAD

**Issue by BullSprite** [golang/go#58017]
### What version of Go are you using (`go version`)?

<pre>
$go version
go version devel go1.20-6001c043dc Fri Aug 19 03:32:27 2022+0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOOS="linux"
</pre></details>

### What did you do?

<details><summary><code>test.s</code></summary><br><pre>
TEXT main·test(SB), $0
    VSQRTSS    (BX),X9,X11

</pre></details>
Commands that I run:
<pre>
$ go tool asm test.s
$ go tool objdump test.o
</pre>

### What did you expect to see?
<pre>
test.s:2 0x35f c532511b VSQRTSS (BX),X9,X11
</pre>

### What did you see instead?
<pre>
test.s:2 0x35f c53251 PUSHQ CX
test.s:2 0x362 1b     ?
</pre>

Bits of instructions are the same, but objdump tool decodes it incorrectly. Also, there is a failure '?' to decode last byte.

And it only one example of many such decode issues.

**Comment by randall77** [comment]
I believe this is a dup of #25617. Please reopen if you disagree.
