### ISSUE TITLE
cmd/asm: constant MOVQ transformed to MOVL, but MOVL upper bit zeroing not guaranteed

### ISSUE THREAD

**Issue by BullSprite** [golang/go#58016]
### What version of Go are you using (`go version`)?
<pre>
$go version
go version devel go1.20-6001c043dc Fri Aug 19 03:32:27 2022+0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOOS="linux"
</pre></details>

### What did you do?
When 64bit immediate that can be fit into 32bit immediate is used as argument of MOVQ instruction, the compiler assembler transforms it to MOVL. On X86_64 platform the test shows that upper that upper 32bits of RAX are zeroed after MOVL of 32bit constant (tested on Xeon 6230N CPU). But there is no such statement in SDM so this behavior should be classified as 'non-documented' and can be easily changed by the platform owner without any announcement.

<details><summary><code>test.s</code>File</summary><br><pre>
TEXT main·test(SB), 4, $0
    MOVQ    $0xFFFFFFFE, AX
    MOVQ    AX, ret+8(FP)
    RET
</pre></details>

Commands that I run:
<pre>
$ go tool asm test.s
$ go tool objdimp -gnu test.o
</pre>

### What did you expect to see?
<pre>
test.s:4 0x332 48b8feffffff00000000 MOVQ $0xfffffffe, AX // mov $0xfffffffe,%rax
test.s:7 0x33c 4889442410 MOVQ AX, 0x10(SP) // mov %rax,0x10(%rsp)
test.s:8 0x341 c3 RET // retq
</pre>

### What did you see instead?
<pre>
test.s:4 0x332 b8feffffff MOVL $-0x2, AX // mov $-0x2,%eax
test.s:7 0x337 4889442410 MOVQ AX, 0x10(SP) // mov %rax,0x10(%rsp)
test.s:8 0x341 c3 RET // retq
</pre>

**Comment by mknyszek** [comment]
CC @golang/compiler

**Comment by randall77** [comment]
This is specified in the SDM, vol 1 section 3.4.1.1.

> 32-bit operands generate a 32-bit result, zero-extended to a 64-bit result in the destination general-purpose register.

In addition, other compilers assume this, e.g. gcc.
