### ISSUE TITLE
race: Thread Sanitizer breaks sequential consistency semantics

### ISSUE THREAD

**Issue by vmg** [golang/go#58020]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, it reproduces on the tip of `master` too.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/vmg/.cache/go-build"
GOENV="/home/vmg/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/vmg/src/go/pkg/mod"
GOOS="linux"
GOPATH="/home/vmg/src/go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/vmg/.local/opt/go1.19.4"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/vmg/.local/opt/go1.19.4/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
</pre></details>

### What did you do?

I was working on some lock-free algorithms in Go and found something interesting. Here's a break down:

1. The Go memory model ensures sequential consistency for atomic operations in the `sync/atomic` package. This is explicitly declared in [the documentation](https://go.dev/ref/mem) that @rsc carefully crafted!

> The APIs in the [sync/atomic](https://go.dev/pkg/sync/atomic/) package are collectively “atomic operations” that can be used to synchronize the execution of different goroutines. If the effect of an atomic operation A is observed by atomic operation B, then A is synchronized before B. All the atomic operations executed in a program behave as though executed in some sequentially consistent order.

> The preceding definition has the same semantics as C++’s sequentially consistent atomics and Java’s volatile variables.

2. To accomplish sequential consistency between stores and loads, in `AMD64`, the Go compiler always emits `XCHG` instructions for both `atomic.StoreXX` and `atomic.SwapXX`. In fact, these two atomic functions are interchangeable in the codegen if you don't care about the output.

https://github.com/golang/go/blob/4df10fba1687a6d4f51d7238a403f8f2298f6a16/src/cmd/compile/internal/ssa/_gen/AMD64.rules#L526-L535

3. However, when you compile a Go program with the race detector enabled (`-race`), the Go codegen for x64 no longer applies, as the atomic operations are delegated to the TSAN runtime library so they can be checked for races:

https://github.com/golang/go/blob/4df10fba1687a6d4f51d7238a403f8f2298f6a16/src/runtime/race_amd64.s#L234-L238

https://github.com/golang/go/blob/4df10fba1687a6d4f51d7238a403f8f2298f6a16/src/runtime/race_amd64.s#L259-L263

4. The TSAN runtime library actually implements two different helpers for `Store` and `Swap`, unlike the Go codegen which would emit identical code for both.

https://github.com/llvm/llvm-project/blob/79649eacbc113a287d380fd7a0dab60302078eb4/compiler-rt/lib/tsan/rtl/tsan_interface_atomic.cpp

```c++
SANITIZER_INTERFACE_ATTRIBUTE
void __tsan_go_atomic64_store(ThreadState *thr, uptr cpc, uptr pc, u8 *a) {
  ATOMIC(Store, *(a64**)a, *(a64*)(a+8), mo_release);
}

SANITIZER_INTERFACE_ATTRIBUTE
void __tsan_go_atomic64_exchange(ThreadState *thr, uptr cpc, uptr pc, u8 *a) {
  ATOMIC_RET(Exchange, *(a64*)(a+16), *(a64**)a, *(a64*)(a+8), mo_acq_rel);
}
```

6. **The code in TSAN does not match Go's semantics!** Besides doing the race checking, TSAN must actually perform the atomic operation that the user requested. These atomic operations have been modeled using the C++ memory model **and they have an explicit ordering argument that does not match Go's semantics**. More particularly, `atomic64_exchange` is emitted with C++'s `std::memory_order_acq_rel`, which coincidentally in x64 is equivalent to `std::memory_order_seq_cst` (it emits a `LOCK XCHG` like Go would). However, `atomic64_store` is emitted with `std::memory_order_release` **which is not sequentially consistent**! In fact, it only emits a `MOV` because writes in x64 imply release semantics.
7. Hence, when running under `-race`, calls to `atomic.Store64` in Go code are actually not sequentially consistent!

It took me and @dbussink a good while to figure this one out. We were porting a lock-free algorithm that required sequentially consistent semantics and we were extremely puzzled when the algorithm worked correctly when ran normally and yet **it broke down and started emitting wrong results without any race errors** when ran under `-race`. It got even more confusing when replacing an `atomic.StoreInt64` with an `atomic.SwapInt64` fixed the algorithm.

We think this explains the issue we were seeing quite well!

### What did you expect to see?

I would expect the sequentially consistent semantics of Go atomics to be maintained when running under the race detector. I would expect the actual assembly instructions for the atomic operations to be identical when running under the race detector (modulo _all the helper code that TSAN adds around them to actually track races_).

### What did you see instead?

The race detector actually introduced a race in my code that didn't exist before! I want my money back!

**Comment by ianlancetaylor** [comment]
CC @dvyukov

**Comment by randall77** [comment]
Looks like we started promising sequential consistent behavior in https://go-review.googlesource.com/c/go/+/381316 (~ 1 year ago, released first in 1.19), but we didn't verify that we actually provided that, as far as I can tell. @rsc 

Probably the right fix is to fix the tsan library to use `mo_acq_rel` for the `__tsan_go_atomic64_store` versions.

But an easier, quicker fix is just to use the `_exchange` tsan operations to implement the Go `Store` operations. Especially for backport to 1.19 and the soon-to-be-released 1.20, that's an easier, safer fix.

**Comment by randall77** [comment]
I have a CL out to fix this immediate problem. I'm not sure we're really covered completely, though. For instance atomic loads are marked acquire, not acquire+release. Will that lead to problems? The compare-and-swap ops are also dual-marked and one of the marks is acquire-only. Maybe that's for when the comparison fails?

What about other architectures? They may in fact be worse, as they tend to have looser default semantics.

How do we test this?

The good news is that this only matters to race mode, where performance doesn't matter much. We can drop big memory barrier hammers if we need to.

**Comment by dvyukov** [comment]
There are tests for sequential consistency, they run under race detector and don't fail, right?
https://github.com/golang/go/blob/master/src/sync/atomic/atomic_test.go#L2221-L2303
Besides mo_release there are at least 2 other Mutex lock/unlock operations. They also participate in synchronization. Have you accounted for these?

**Comment by randall77** [comment]
Yes, those tests pass.

That said, they also pass if I change the non-race code to use MOVQ instead of XCHGQ. So either we're currently using XCHGQ unnecessarily or our tests aren't very thorough. (Or maybe my processor provides more than minimal guarantees, hard to tell.)

I think we're going to need a test case from the OP. Without that, it is hard to be sure there is something wrong, and certainly hard to tell whether we've actually fixed it.

**Comment by dvyukov** [comment]
It should fail pretty reliably on a typical x86 CPU.
Here is what I did:
```
atomic$ go test -run=TestStoreLoadSeqCst64 -count=1000 
PASS
ok  	sync/atomic	0.273s

atomic$ go test -run=TestStoreLoadSeqCst64 -count=1000 -race
PASS
ok  	sync/atomic	1.507s
```

Then (which should practically lead to MOVQ):
```
--- a/src/sync/atomic/atomic_test.go
+++ b/src/sync/atomic/atomic_test.go
@@ -2276,7 +2276,8 @@ func TestStoreLoadSeqCst64(t *testing.T) {
                        for i := int64(1); i < N; i++ {
-                               StoreInt64(&X[me], i)
+                               X[me] = i
                                my := LoadInt64(&X[he])
```
```
atomic$ go test -run=TestStoreLoadSeqCst64 -count=10
--- FAIL: TestStoreLoadSeqCst64 (0.00s)
    atomic_test.go:2294: store/load are not sequentially consistent: 27/27 (28)
    atomic_test.go:2294: store/load are not sequentially consistent: 27/27 (28)
--- FAIL: TestStoreLoadSeqCst64 (0.00s)
    atomic_test.go:2294: store/load are not sequentially consistent: 20/20 (21)
    atomic_test.go:2294: store/load are not sequentially consistent: 20/20 (21)
--- FAIL: TestStoreLoadSeqCst64 (0.00s)
    atomic_test.go:2294: store/load are not sequentially consistent: 11/11 (12)
    atomic_test.go:2294: store/load are not sequentially consistent: 11/11 (12)
--- FAIL: TestStoreLoadSeqCst64 (0.00s)
    atomic_test.go:2294: store/load are not sequentially consistent: 3/3 (4)
    atomic_test.go:2294: store/load are not sequentially consistent: 3/3 (4)
--- FAIL: TestStoreLoadSeqCst64 (0.00s)
    atomic_test.go:2294: store/load are not sequentially consistent: 45/45 (46)
    atomic_test.go:2294: store/load are not sequentially consistent: 45/45 (46)
--- FAIL: TestStoreLoadSeqCst64 (0.00s)
    atomic_test.go:2294: store/load are not sequentially consistent: 491/491 (492)
    atomic_test.go:2294: store/load are not sequentially consistent: 491/491 (492)
--- FAIL: TestStoreLoadSeqCst64 (0.00s)
    atomic_test.go:2294: store/load are not sequentially consistent: 2/2 (3)
    atomic_test.go:2294: store/load are not sequentially consistent: 2/2 (3)
FAIL
```

**Comment by randall77** [comment]
Hmm, I did this:
```
--- a/src/runtime/internal/atomic/atomic_amd64.s
+++ b/src/runtime/internal/atomic/atomic_amd64.s
@@ -171,7 +171,8 @@ TEXT ·Store8(SB), NOSPLIT, $0-9
 TEXT ·Store64(SB), NOSPLIT, $0-16
        MOVQ    ptr+0(FP), BX
        MOVQ    val+8(FP), AX
-       XCHGQ   AX, 0(BX)
+       MOVQ    AX, 0(BX)
+       //XCHGQ AX, 0(BX)
        RET
```
Maybe that code doesn't get used somehow? Semantic inlining somewhere, I suspect.

**Comment by randall77** [comment]
Yes, that'll be the reason. Need this patch:
```
--- a/src/cmd/compile/internal/ssagen/ssa.go
+++ b/src/cmd/compile/internal/ssagen/ssa.go
@@ -4085,7 +4085,7 @@ func InitTables() {
                sys.AMD64, sys.ARM64, sys.Loong64, sys.MIPS, sys.MIPS64, sys.PPC64, sys.RISCV64, sys.S390X)
        addF("runtime/internal/atomic", "Store64",
                func(s *state, n *ir.CallExpr, args []*ssa.Value) *ssa.Value {
-                       s.vars[memVar] = s.newValue3(ssa.OpAtomicStore64, types.TypeMem, args[0], args[1], s.mem())
+                       s.vars[memVar] = s.newValue3A(ssa.OpStore, types.TypeMem, types.Types[types.TINT64], args[0], args[1], s.mem())
                        return nil
                },
```
Then the sequential consistency tests in sync/atomic fail.

**Comment by mknyszek** [comment]
CC @golang/compiler @golang/runtime

**Comment by mknyszek** [comment]
CC @golang/compiler @golang/runtime

**Comment by vmg** [comment]
This is still not fixed in Go 1.20.3 or gotip, and it appears that @randall77 and @dvyukov managed to verify the issue. Is there any further info you need me to provide?

**Comment by randall77** [comment]
We're going to need a test case. I do think the code looks not quite right, but @dvyukov disagrees. We have tests for sequential consistency under `-race` which are currently passing. So if there is something wrong here, it is subtle.

I'll reopen for now.

**Comment by vmg** [comment]
@dvyukov: Here's a reproduction recipe. It's based on _"Left-Right - A Concurrency Control Technique with Wait-Free Population Oblivious Reads"_, an algorithm that requires sequential consistency.

When run under `-race`, `TestLeftRightRace` consistently fails because either the `left` or `right` maps are being accessed concurrently by the writer and one of the readers. When run _without_ `-race`, the algorithm never fails. Note that if the implementation was incorrect, it would fail without `-race` too, because concurrent writes and reads to builtin Go maps are _always_ checked.

Furthermore, to demonstrate what we believe to be the reported issue, you can change the `Store` calls in `readerArrive` and `readerDepart` with `Swap` calls, and the algorithm now always works even when run under `-race`. If the semantics described by the language were being applied, the behavior of `Store` and `Swap` whilst ignoring the returned value should be identical. 

```go
package view

import (
	"runtime"
	"sync"
	"sync/atomic"
	"testing"
	_ "unsafe"
)

//go:linkname sync_runtime_procPin sync.runtime_procPin
//go:nosplit
func sync_runtime_procPin() int

//go:linkname sync_runtime_procUnpin sync.runtime_procUnpin
//go:nosplit
func sync_runtime_procUnpin()

const Reading = 1
const NotReading = 0
const Left = -1

type atomicInt64 struct {
	atomic.Int64
	pad [120]byte
}

type leftright struct {
	active        atomic.Int64
	writerVersion atomic.Uint64
	readerVersion [2][]atomicInt64

	left, right map[uintptr]uintptr
}

func (lr *leftright) init(maxprocs int) {
	lr.left = make(map[uintptr]uintptr)
	lr.right = make(map[uintptr]uintptr)
	lr.readerVersion = [2][]atomicInt64{
		make([]atomicInt64, maxprocs),
		make([]atomicInt64, maxprocs),
	}
	lr.active.Store(Left)
}

func (lr *leftright) readerArrive(version uint64, tid int) {
	v := lr.readerVersion[version&0x1]
	// BUG: this breaks sequential consistency when run under -race
	// Because Swap uses a LOCK XCHG in x64, you can fix the sequential consistency issue with:
	// v[tid].Swap(Reading)
	v[tid].Store(Reading)
}

func (lr *leftright) readerDepart(version uint64, tid int) {
	v := lr.readerVersion[version&0x1]
	// BUG: this breaks sequential consistency when run under -race
	// Because Swap uses a LOCK XCHG in x64, you can fix the sequential consistency issue with:
	// v[tid].Swap(NotReading)
	v[tid].Store(NotReading)
}

func (lr *leftright) readerIsEmpty(version uint64) bool {
	v := lr.readerVersion[version&0x1]
	for t := range v {
		if v[t].Load() == Reading {
			return false
		}
	}
	return true
}

func (lr *leftright) Read(callback func(tbl map[uintptr]uintptr, version uint64)) {
	tid := sync_runtime_procPin()
	vi := lr.writerVersion.Load()

	lr.readerArrive(vi, tid)

	if lr.active.Load() == Left {
		callback(lr.left, vi)
	} else {
		callback(lr.right, vi)
	}

	lr.readerDepart(vi, tid)
	sync_runtime_procUnpin()
}

func (lr *leftright) publish(active int64, callback func(tbl map[uintptr]uintptr)) {
	lr.active.Store(-active)

	prevVersion := lr.writerVersion.Load()
	nextVersion := prevVersion + 1

	for !lr.readerIsEmpty(nextVersion) {
		runtime.Gosched()
	}
	lr.writerVersion.Store(nextVersion)

	for !lr.readerIsEmpty(prevVersion) {
		runtime.Gosched()
	}

	if -active == Left {
		callback(lr.right)
	} else {
		callback(lr.left)
	}
}

func (lr *leftright) Write(callback func(tbl map[uintptr]uintptr)) {
	active := lr.active.Load()
	if active == Left {
		callback(lr.right)
	} else {
		callback(lr.left)
	}
	lr.publish(active, callback)
}

func TestLeftRightRace(t *testing.T) {
	runtime.GOMAXPROCS(8)

	const Procs = 8
	const Iter = 1000000

	var lr leftright
	lr.init(Procs)

	var wg sync.WaitGroup
	wg.Add(Procs + 1)

	for proc := 0; proc < Procs; proc++ {
		go func() {
			defer wg.Done()
			for i := 0; i < Iter; i++ {
				lr.Read(func(tbl map[uintptr]uintptr, _ uint64) {
					_ = tbl[0]
				})
			}
		}()
	}

	go func() {
		defer wg.Done()
		for i := 0; i < Iter; i++ {
			lr.Write(func(tbl map[uintptr]uintptr) {
				tbl[0] = uintptr(i)
			})
		}
	}()

	wg.Wait()
}
```

**Comment by dvyukov** [comment]
It's quite hard to understand what it's doing and ensure the code itself is correct. A simpler example that just captures the pattern where race detector fails would help.

The race detector also reports a race on this code. Is it a false race report?

**Comment by vmg** [comment]
> It's quite hard to understand what it's doing and ensure the code itself is correct. A simpler example that just captures the pattern where race detector fails would help.

I know, but reducing the test case further is proving to be very complicated and I currently don't have more cycles to spend on this this week. Can we agree that the reproduction recipe is valid, for now?

> The race detector also reports a race on this code. Is it a false race report?

Do you mean the data race on `runtime.mapassign_fast64()`? No, the report is legitimate. The map is being written and read to concurrently, even though the purpose of the algorithm is providing exclusionary access to it.

Have you attempted running the same code but replacing the two calls to `Store` in `readerDepart` and `readerArrive` with `Swap`? In my experience, this fixes the race and makes the code run successfully, both in `-race` and without. 

Can we agree that replacing an atomic `Store` with a `Swap` should not change the behavior of a Go program? Can you reproduce that the provided example shows a data race when using `Store` but shows no data race when using `Swap`?

If you agree with the underlying issue and can reproduce the bug with the provided example, I'll gladly spend some more time (probably next week) trying to minimize this test case so it can be incorporated in the standard library's test suite.

Thanks for taking the time to look into this. I know the issue is hairy!

**Comment by vmg** [comment]
> A simpler example that just captures the pattern where race detector fails would help.

Just to clarify, this bug report is not about the race detector failing. It's about the race detector weakening the sequential consistency of Go programs, so that algorithms like Left/Right, which require sequential consistency, stop behaving properly when they're being run under the race detector.

**Comment by vmg** [comment]
Thanks for the review! Let me see if I understand the situation: you're saying that by pinning the reader goroutines to specific `P`s, the happens-before relation between the readers and the writer is hidden from TSAN. This is because the two stores must necessarily happen sequentially, as the G where they run is pinned, but TSAN is not aware of this fact. Explicitly perform a read (with a `Load` or `Swap`) forces TSAN to see the HB relation. If so, this is a bug that could never reproduce in safe Go code, but would apply to internal runtime code. Does this seem accurate?

**Comment by dvyukov** [comment]
Yes. Looks accurate.
And this is where difference between Store and Swap kicks in -- Swap's done by reads synchronize with each other, while Store's don't.
In you actual code Readers effectively synchronize as well by means of pin/unpin, but the race detector is not aware of that.
If this is your real production code, I would suggest adding some "annotations" in race build. The Load as I added in the previous comment is probably the simplest and cheapest way.

**Comment by vmg** [comment]
Thanks again for the review, @dvyukov. I don't know if making TSAN aware of Go scheduler pinning is in scope, since this would only apply when race testing internal runtime code. I'll leave that up to you!

**Comment by dvyukov** [comment]
The race detector intentionally ignores all synchronization in the runtime and does not test it. It's intended for end users for testing of their code.
If we want to test the runtime itself, we need a different tool, or at least a radically different operation mode.
