### ISSUE TITLE
cmd/go: support multiple main packages with -pgo=auto

### ISSUE THREAD

**Issue by prattmic** [golang/go#58099]
In Go 1.20, `go build -pgo=auto` can only be used with a single main package. Specifying multiple main packages (e.g., `go build -pgo=auto cmd/compile cmd/link`) is an error.

To support this, cmd/go needs to learn to build the transitive dependencies N times, once for each different profile used by each main package.

Follow up to #55022.

cc @cherrymui @aclements

**Comment by nemo-cpt** [comment]
I hope everone here understand that this N-fold complete rebuild doesn't scale.

Having 100s of services and 1000s of packages you end up in extremely large caches (100x than normal) or basically dong every build without cache, or mix of both.

**Comment by aclements** [comment]
Just tracking: this doesn't actually make `-pgo=auto` the default, but it does remove the blocker to doing so.
