### ISSUE TITLE
generics: method-on-generic-type shadowing an existing type can lead to surprising method sets

### ISSUE THREAD

**Issue by mcy** [golang/go#58100]
```
$ go version
go version go1.19.4 linux/amd64
```

Consider the following, valid program which is not flagged by `go vet`:

```go
package bad 

type X interface { F(); }
type Y[T any] float32
func (Y[int]) F() {}  // (1)
var _ X = Y[string](0.0)  // (2)

type X2 interface { F() int; }
type Y2[T any] struct { x T; }
func (y Y2[int]) F() int { return y.x; }  // (3)
// var _ X2 = Y2[string]{""}  // (4)
```

This program exhibits a pair of situations in which declaring a method on a generic type can lead to unexpected results. Because identifiers between the [] of the receiver introduce new type variables, in both definitions of `F` above, `int` is not `builtin.int` but rather a type variable named `int`.

Thus, up to line (2), the program compiles, because (1) is equivalent to `func (Y[_]) F() {}`, which fuilfills the method for every specialization of `Y`.

On the other hand, (3) is equivalent to `func (y Y2[T]) F() T { return y.x; }`. This means that (4) does *not* compile, but not for the reason the user expects: it is not because there is no `Y2[string].F`, but because that method exists and returns a `string`, not an `int`.

Although this is working as intended per spec, I spoke to @dr2chase and we concurred that this is:
1. A UX bug: a programmer not completely versed in the details of methods-on-generic-types might expect this to only define `Y[int].F`, not `Y[T].F` for all types `T any`. `go vet`, at a minimum, should complain about programs where the type variables declared in a method-on-generic-type do not shadow types currently in scope.
2. A misuse of syntax real-estate. If, in the future, Go allows [1] to compile, it may be too late to re-purpose this syntax as a shorthand for it. Given that generics is relatively new, making this an error at the language level now rather than later seems prudent. Arguably, no *reasonable* programmer should be shadowing existing types this way, as described in (1).

Ideally I would like it if Go rejected (1) and (3) above on the basis of type variables in a receiver not being allowed to shadow existing names. If that breaking change seems to be impossible at this point, a `go vet` check seems worthwhile to inform users that attempting to define a method on a specialization of a generic type is not permitted.

[1] This program currently does not compile, as expected per spec.
```go
type Spec = Y[int]
func (Spec) F() {}
// ^ cannot define new methods on instantiated type Y[int]
```

**Comment by ianlancetaylor** [comment]
https://go.dev/doc/faq#types_in_method_declaration

**Comment by mcy** [comment]
That's not very discoverable. Seems like a bad UX outcome to me.

**Comment by ianlancetaylor** [comment]
It's not ideal, but it's a mistake that people will make once and then never again.  I think the focus here should be on better compiler error messages and better documentation, rather than a vet check.
