### ISSUE TITLE
affected/package:  Pass by reference, func not print text

### ISSUE THREAD

**Issue by qiaoliangXgamemode** [golang/go#58115]
### What version of Go are you using (`go version`)?

<pre>
C:\Users\Bridge grain>go version
go version go1.19.5 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
PS D:\Mydesok\Code_project\Xooline\server> go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Bridge grain\AppData\Local\go-build
set GOENV=C:\Users\Bridge grain\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Bridge grain\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Bridge grain\go
set GOPRIVATE=
set GOPROXY=https://goproxy.io,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.19.5
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\Mydesok\Code_project\Xooline\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 '-fdebug-prefix-map=C:\Users\Bridge grain\AppData\Local\Temp\go-build2377547279=/tmp/go-build' -gno-record-gcc-switches 

</pre></details>

### What did you do?
Using UDP Doing C/S
![image](https://user-images.githubusercontent.com/46279874/215158990-8f8542b0-6aa7-4824-84d1-cccea7ba4977.png)
## Code
<pre>
package main

import (
	"xoline/module/keys"
	"log"
	"net"
)

func main(){
	Server_Addrs, _ := net.ResolveUDPAddr("udp", "localhost:5248")
	listen,err := net.ListenUDP("udp",Server_Addrs)
	if err != nil {
		log.Println(err)
	}
	// buffer size stting -> 1024
	log.Println("[Server] buffer size: 1024")
	for {
		buf := make([]byte, 1024)
		n,addr, err := listen.ReadFromUDP(buf)
		if err != nil {
			log.Println(err)
		}
		log.Println("[Server] Connent IP -> ", addr)
		Configure := keys.InfoMap(string(buf[:n]))
		// log.Println("--> ",Configure)
		log.Println("[Server] IP: ", addr)
		log.Println(Configure["keys"])
		go reInfoPeertoPerr(listen,
			addr,
			Configure["Keys"],
			Configure["method"])
		}
}

func reInfoPeertoPerr(conn net.Conn,addrs *net.UDPAddr,key string,method string) {
	// defer conn.Close()
	log.Println("[Server] Keys -> ",key)
	log.Println("[Server] Peer to Peer -> ",addrs.IP,addrs.Port)
}

</pre>

i use fmt.Println replace log.Println,but not resolve.i don't doing?

## log.Println Logs
this run log.Println logs
[2023-01-28-01-36-45.log](https://github.com/golang/go/files/10521702/2023-01-28-01-36-45.log)

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by qiaoliangXgamemode** [comment]
OK，this only language question



---- Replied Message ----
| From | Sean ***@***.***> |
| Date | 01/28/2023 02:17 |
| To | ***@***.***> |
| Cc | Bridge ***@***.***>***@***.***> |
| Subject | Re: [golang/go] affected/package: Pass by reference, func not print text (Issue #58115) |

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
