### ISSUE TITLE
cmd/compile: gcflags="-d=ssa/check_bce" doesn't work or doesn't work well for generic functions

### ISSUE THREAD

**Issue by go101** [golang/go#58139]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20rc3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```Go
package main

type ByteSeq interface{ ~string | ~[]byte }

//go:noinline
func CommonPrefixes[X, Y ByteSeq](x X, y Y) (X, Y) {
	min := len(x)
	if min > len(y) {
		min = len(y)
	}
	x2 := x[:min]
	y2 := y[:len(x2)]
	for i := 0; i < len(x2); i++ {
		if x2[i] != y2[i] {
			return x2[:i], y2[:i]
		}
	}
	return x2, y2
}

var _, _ = CommonPrefixes("", []byte{})
var _, _ = CommonPrefixes("", "")
var _, _ = CommonPrefixes([]byte{}, "")
var _, _ = CommonPrefixes([]byte{}, []byte{})

func main() {}
```

```
go run -gcflags="-d=ssa/check_bce"  main.go
```

### What did you expect to see?

```
./main.go:11:9: Found IsSliceInBounds
./main.go:12:9: Found IsSliceInBounds
```

### What did you see instead?

```
./main.go:11:9: Found IsSliceInBounds
./main.go:12:9: Found IsSliceInBounds
./main.go:14:17: Found IsInBounds
```

If the all variable declaration lines are removed, then there is no bound check found messages.
If the latter 3 variable declaration lines are removed, then there will be only two  bound check found messages

This makes library maintainers mistake there is no or less bound checks, except that the maintainers list all possible function instances (like the variable declaration lines).

**Comment by greatroar** [comment]
Not all inlining decisions can be made prior to instantiation. Consider:

```go
func f[T byte | int](a *[256]int, i T) int { return a[i] }
```

T=byte triggers BCE, but T=int can't.

**Comment by mknyszek** [comment]
CC @golang/compiler

**Comment by randall77** [comment]
I'm not sure what the right thing to do here is. Optimization decisions might be different for different instantiations. Right now we basically report the union of all the optimizations across instantiations. That's inaccurate, but I don't see an obvious accurate way to report them that isn't very verbose.

That said, this is a pretty rare situation. Usually optimizations will be the same.

The fact that we get no reports at all if you don't instantiate something is also unfortunate, but I'm not sure what the solution to that is either. We could instantiate with some default types but how would we do that? If the bound has method `Foo` how do we find a type that has `Foo` to instantiate with? Maybe there aren't any in the package being compiled?

**Comment by go101** [comment]
It certainly has some improvement room there.
Some bound checks are type arguments independent,
For example, no bound checks for the following function if it is never instantiated,
but all instantiations of the functions will do bound checks.

```Go
func foo[T any](s []T) {
	_ = s[0]
	_ = s[1]
	_ = s[2]
}
```

On the other hand, I do understand that custom generics are not free meat.
Thanks for the explanation.

Please close this issue if nothing needs to be done.
