### ISSUE TITLE
x/pkgsite: why i can't search my published module only by github account name or module name?

### ISSUE THREAD

**Issue by mumingv** [golang/go#58136]
### What is the URL of the page with the issue?

https://pkg.go.dev

### What is your user agent?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

### Screenshot

see below.

### What did you do?

Searching by account name "mumingv", i can't get the expected result.

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/12959446/215335273-c579a340-4dcb-41af-a16f-498367a3142a.png">

Searching by module name "golib", i can't get the expected result too. (I look through all items, but "mumingv/golib" doesn't exist.)

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/12959446/215335582-2fec4198-1c70-4ab0-8c13-60a44e719fe1.png">

But i search by "mumingv/golib", i get it.

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/12959446/215335632-28cfdb21-f2d3-4bc7-8e08-558c9454c8b8.png">

Then i try to search another user's account name, it can list all modules belonging to him.

<img width="992" alt="image" src="https://user-images.githubusercontent.com/12959446/215335825-73813e79-d0c7-4791-b8d2-01f22fa2b463.png">

I don't know why?

### What did you expect to see?

I want to search my published modules only by "mumingv" or "golib" rather than "mumingv/golib".

### What did you see instead?

I must use account name plus module name, i.e. "mumingv/golib", to search my published module.

**Comment by mumingv** [comment]
So does anybody know this problem?

**Comment by hyangah** [comment]
Strange. I see the search work as expected now but still see the problem when searching with `golib`.

![Screenshot 2023-02-01 at 10 49 14 PM](https://user-images.githubusercontent.com/4999471/216227125-1929ec7c-7651-46eb-8d05-493fb287ef0a.png)

cc @golang/tools-team

**Comment by jamalc** [comment]
It looks like the initial version of your module contained no license making it un-redistributable. Projects without a redistributable license do not show up in our search results. We cache the result of a search query for 24 hours. Now that your module has a redistributable license it should appear in search results for queries where it ranks high enough. We do not show all relevant results for a search term.

**Comment by mumingv** [comment]
> It looks like the initial version of your module contained no license making it un-redistributable. Projects without a redistributable license do not show up in our search results. We cache the result of a search query for 24 hours. Now that your module has a redistributable license it should appear in search results for queries where it ranks high enough. We do not show all relevant results for a search term.

Yes, I add a license file after publishing according the tips of my package's main page(https://pkg.go.dev/github.com/mumingv/golib). So, if I publish a new package with a license file, I will search it immediately, right? Or, I also wait it ranking high enough?
