### ISSUE TITLE
net/http perform curl request with args -T and -L

### ISSUE THREAD

**Issue by freesinger** [golang/go#58135]
### What did you do?

I'm using http.Client to perform a curl command line, but it seems there's no support for `-T` and `-L` args in curl.
I've tried `-d` and pass the content of file, which returns 405.
How can I solve it?

Here's raw curl
```curl
curl -u bob:123456 -H "filename: 2022-10-20/1.csv" -T data/2022-10-20/1.csv -L '172.21.21.12:8035/copy/copyUpload'
```

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
