### ISSUE TITLE
crypto/ecdh: ECDH method doesn't check curve

### ISSUE THREAD

**Issue by tmthrgd** [golang/go#58131]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20rc3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes with go1.20rc3.

### What did you do?

https://go.dev/play/p/ehaJDunhTUG?v=gotip

```go
package main

import (
	"crypto/ecdh"
	"crypto/rand"
	"fmt"
)

func main() {
	p256, _ := ecdh.P256().GenerateKey(rand.Reader)
	p384, _ := ecdh.P384().GenerateKey(rand.Reader)
	x25519, _ := ecdh.X25519().GenerateKey(rand.Reader)

	secret, err := p256.ECDH(p384.PublicKey())
	fmt.Println(secret, err)

	secret, err = p256.ECDH(x25519.PublicKey())
	fmt.Println(secret, err)

	secret, err = p384.ECDH(p256.PublicKey())
	fmt.Println(secret, err)

	secret, err = p384.ECDH(x25519.PublicKey())
	fmt.Println(secret, err)

	secret, err = x25519.ECDH(p256.PublicKey())
	fmt.Println(secret, err)

	secret, err = x25519.ECDH(p384.PublicKey())
	fmt.Println(secret, err)
}
```

### What did you expect to see?

Some kind of invalid curve error.

### What did you see instead?

```
[] invalid P256 point encoding
[] invalid P256 point encoding
[] invalid P384 point encoding
[] invalid P384 point encoding
[] crypto/ecdh: bad X25519 remote ECDH input: low order point
[] crypto/ecdh: bad X25519 remote ECDH input: low order point
```

When run with `GOEXPERIMENT=boringcrypto`:
```
[] boringcrypto: EC_POINT_mul failed
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x5f20cd]

goroutine 1 [running]:
crypto/internal/boring.ECDH(0xc000014048, 0x0)
	/home/tom/sdk/go1.20rc3/src/crypto/internal/boring/ecdh.go:150 +0x12d
crypto/ecdh.(*nistCurve[...]).ecdh(...)
	/home/tom/sdk/go1.20rc3/src/crypto/ecdh/nist.go:200
crypto/ecdh.(*PrivateKey).ECDH(...)
	/home/tom/sdk/go1.20rc3/src/crypto/ecdh/ecdh.go:121
main.main()
	/home/tom/ecdh.go:17 +0x155
```

**Comment by seankhliao** [comment]
cc @golang/security

**Comment by FiloSottile** [comment]
The non-BoringCrypto behavior is working as intended: there is nothing in the input that identifies the curve, so we can’t reject them as the wrong curve, but we correctly reject them as invalid encodings or points. We could make the error message better for inputs of the wrong length.

The BoringCrypto panic is a security issue, I’ll look into it ASAP. (Please send suspected security issues to ***@***.*** when you can.)

**Comment by tmthrgd** [comment]
@FiloSottile Apologies for submitting this publicly. It didn't at all occur to me that an (somewhat unlikely) panic in an experiment in a pre-release version of Go could be a security issue. But now that you've mentioned it I can definitely see how that could be. I'll keep that in mind in future.

As for the non-BoringCrypto behaviour, while I know there's no curve identifier in the byte representation of the public keys and private keys, the `ECDH` method does take a typed `*ecdh.PublicKey` which does have a specific curve it's associated with. `privateKeyToPublicKey` even includes the same sanity check panic for curve mismatch (`if key.curve != c {`).

**Comment by FiloSottile** [comment]
Oh, sorry, I misread the code. Yeah we should definitely do the check since we have the information.

**Comment by FiloSottile** [comment]
@gopherbot please backport to Go 1.20. This is a crasher in Go+BoringCrypto that we don't consider a security vulnerability (since Go+BoringCrypto is unsupported) but would be better not to leave laying around, and the patch is tiny and safe.
