### ISSUE TITLE
Cannot redefine existing variables inside an if statement when ":=" is required

### ISSUE THREAD

**Issue by MarkGaskinRR** [golang/go#58147]
### What version of Go are you using (`go version`)?
Reproducible in go.dev/play with Go 1.19
<pre>
$ go version
1.19
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Just using go.dev/play here

### What did you do?

https://go.dev/play/p/VF4NlYvP7ce

```
func generateNumberAndError() (int, error) {
	return 1, errors.New("Test")
}

func main() {
	var err error
	if true {
		i, err := generateNumberAndError()
		fmt.Println(i)
		fmt.Println(err)
	}

	fmt.Println(err) // Expecting "Test", but receiving nil
}
```

### What did you expect to see?
"Test"

### What did you see instead?
nil

### Workarounds
```
func generateNumberAndError() (int, error) {
	return 1, errors.New("Test")
}

func main() {
	var err error
	var i int
	if true {
		i, err = generateNumberAndError()
		fmt.Println(i)
		fmt.Println(err)
	}

	fmt.Println(err) // Works
}
```

But this is not feasible for situations where multiple return values are needed. It would unnecessarily bloat the code.

**Comment by seankhliao** [comment]
Working as intended for the spec.

**Comment by MarkGaskinRR** [comment]
Can you link the spec: @seankhliao ?

**Comment by randall77** [comment]
https://go.dev/ref/spec#Declarations_and_scope and https://go.dev/ref/spec#Short_variable_declarations

**Comment by MarkGaskinRR** [comment]
Thanks @randall77 and @seankhliao.

I'll just note for me, this is unintuitive behaviour worth reconsidering.
