### ISSUE TITLE
x/crypto/bcrypt: new prefix

### ISSUE THREAD

**Issue by gopherbot** [golang/go#5814]
by **raul.san@sent.com**:

<pre>In 2011, was discovered a bug related to the sign extension bug, so nex versions of
OpenBSD's bcrypt added support for the &quot;$2y$&quot; prefix (which guarantees correct
handling of both 7- and 8-bit characters as in OpenBSD's &quot;$2a$&quot;) and a
countermeasure to avoid one-correct to many-buggy hash collisions with the
&quot;$2a$&quot; prefix.

<a href="http://www.openwall.com/lists/announce/2011/07/17/1">http://www.openwall.com/lists/announce/2011/07/17/1</a>

I don't know whether the Go code also has this issue. But in whatever case it should
also support the &quot;$2ay$&quot; prefix.</pre>

**Comment by mdp** [comment]
Golang's bcrypt doesn't distinguish between minor versions ("a","b","y", or any other single letter), just the major version (https://github.com/golang/crypto/blob/master/bcrypt/bcrypt.go#L260)

It happily treats all of them the same. It's probably safe to close this ticket.
