### ISSUE TITLE
proposal: math: use generics.

### ISSUE THREAD

**Issue by gucio321** [golang/go#58148]
While going through math code, I see many functions that's usage could be simplified by using generics.
this will simplify code like this:
```golang
var a, b int = 5, 10
var max int
max = int(math.Max(float64(a), float64(b)))
```
to be just
```golang
var a, b int = 5, 10
var max int
max = math.Max(a, b)
```
because `Max` declaration could become
```golang
func Max[T number](x, y T) T {...}
```

what the `number` should be needs to be discussed. My proposal is to make it
```go
type number interface {
   ~int | ~uint | ~float32 | ~float64
}
```

**Comment by seankhliao** [comment]
That would be a backwards incompatible change.
In general, see https://github.com/golang/go/discussions/48287
