### ISSUE TITLE
proxy.golang.org: forked project showing parent project module history & source

### ISSUE THREAD

**Issue by tebruno99** [golang/go#58167]
I forked gorilla/websocket a few weeks ago. I removed all releases and started from a v1.0.0 to signal that this project will be moving forward independently from the parent.

The package proxy page has all the incorrect documentation, versions, and non-updated history. https://pkg.go.dev/github.com/elasticperch/websocket  for instance v1.4.0 no longer exists (and it only existed for about 60 seconds during the forking process).  Please remove this cached version where ever it came from and proxy the correct package github.com/elasticperch/websocket

**Comment by seankhliao** [comment]
Once seen by the proxy, versions and their contents are immutable.
https://proxy.golang.org/github.com/elasticperch/websocket/@v/list

Your only option is to use retract directives and not reuse these version numbers.

**Comment by tebruno99** [comment]
Wow, ok. well thats pretty crappy. Guess it'll just stay broken and wrong until v1.0.5 is ready in a few months.
