### ISSUE TITLE
cmd/link: `TestBuildForTvOS` failing on `darwin-amd64-11_0`

### ISSUE THREAD

**Issue by bcmills** [golang/go#58221]
https://build.golang.org/log/91e8c2d60784a2c561e285e0d3ac9b204be6e8c2:
```
--- FAIL: TestBuildForTvOS (11.69s)
    link_test.go:312: [/tmp/buildlet/go/bin/go build -buildmode=c-archive -o /tmp/buildlet/tmp/TestBuildForTvOS1814397663/001/lib.a testdata/testBuildFortvOS/lib.go]: exit status 1:
        -buildmode=c-archive not supported on ios/arm64
FAIL
FAIL	cmd/link	24.797s
```

(attn @golang/ios)

**Comment by bcmills** [comment]
This started failing as of [CL 464339](https://go.dev/cl/464339) (CC @ianlancetaylor), which marked `-buildmode=c-archive` as unsupported on `ios` due to the integration tests for that feature failing when run by `cmd/dist`.

**Comment by bcmills** [comment]
I do not understand why the test is failing on _only_ `darwin-amd64-11_0` and not the other `darwin/amd64` builders. @golang/release, is there an intentional difference in this builder as compared with the others?

The test skips itself if `xcrun` is not found in `$PATH` — perhaps our setup instructions for the builders are missing some step to include that tool?

**Comment by dmitshur** [comment]
From a quick look at https://farmer.golang.org/builders and the `BuildConfig` entries in [x/build/dashboard](https://cs.opensource.google/go/x/build/+/master:dashboard/builders.go), the only intentional and documented difference between `darwin-amd64-11_0` and other darwin/amd64 builders is its macOS version. All other differences are incidental.

xcrun seems to be present on darwin-amd64-11_0 and darwin-amd64-12_0 that I quickly tried, but it's likely the problem is along those lines.

**Comment by bcmills** [comment]
This test was originally added in [CL 168321](https://go.dev/cl/168321) for #22395.

It appears that `ios` support was explicitly maintained in `carchive_test.go` at some point, because skips were added for #13701, #19320, #31722, and #33384. So I think the intent is for the buildmode to be supported on this platform; it's a shame that the integration test failures were masked by the `cmd/dist` bug for so long. 😞

**Comment by bcmills** [comment]
> xcrun seems to be present

There is a subsequent check for an `appletvos` SDK specifically — maybe that's the difference?
(https://cs.opensource.google/go/go/+/master:src/cmd/link/link_test.go;l=285-288;drc=4f467f10820e78add23bf5ddeb1de521aa6f8864)

**Comment by bcmills** [comment]
The test is once again passing on `darwin-amd64-11_0`. I've filed #58231 to follow up on the builder configuration issue separately.
