### ISSUE TITLE
x/build/cmd/relui: "Go 1.20 final" workflow ended too early

### ISSUE THREAD

**Issue by dmitshur** [golang/go#58228]
A recent "Go 1.20 final" relui workflow reached almost the end of its execution. One of the last tasks failed, which should've left the option to retry that task and keep going, but instead the entire workflow ended early with a `no workflow named "Go 1.20 final"` error.

This is the tracking issue to investigate and fix that.

CC @golang/release, @mknyszek, @mdempsky.

**Comment by dmitshur** [comment]
The failing task (#58227) didn't just fail with an error, but panicked, and that caused all of relui to restart. If relui restarting causes a workflow to get marked as completed, maybe that's unavoidable, or maybe we can do better.

A particular task can avoid taking down the entire workflow by adding a defer recover that converts panics into internal errors.

**Comment by dmitshur** [comment]
I see what happened—the sequence of events here was unfortunate:

- a "Go 1.20 final" workflow was running and almost finished
- relui restarted and tried to resume all pending workflows
- during workflow registration, since a go1.20 tag was already published, a workflow named "Go 1.21 final" was registered, but a workflow named "Go 1.20 final" was not

I guess we should take this possible sequence of events into account in our logic for dynamic workflow registration.

**Comment by heschi** [comment]
Oops. A bit janky, but perhaps we should GetTagInfo on the latest tag and drop back to the previous one if it's less than, say, 3 days old?
