### ISSUE TITLE
cmd/go: exec: WaitDelay expired before I/O complete

### ISSUE THREAD

**Issue by prattmic** [golang/go#58230]
```
#!watchflakes
post <- `^exec: WaitDelay expired before I/O complete`
```

I only see one prior failure (posted to #56785):

[2023-01-24T19:47:54-ffbd194/freebsd-arm-paulzhol](https://build.golang.org/log/5dc4ebe4b9783af7fa12f44d20dea614fff27d97)

This seems to be a case of the test passing, but slow scheduling preventing Wait in the parent from returning quickly enough.

**Comment by bcmills** [comment]
Looks like we need to adjust the `WaitDelay` heuristic following [CL 456116](https://go.dev/cl/456116) (#24050).
