### ISSUE TITLE
x/tools/gopls: emacs crash when using gopls with Go 1.20

### ISSUE THREAD

**Issue by jackgris** [golang/go#58236]
### gopls version
```bash
golang.org/x/tools/gopls v0.11.0
    golang.org/x/tools/gopls@v0.11.0 h1:/nvKHdTtePQmrv9XN3gIUN9MOdUrKzO/dcqgbG6x8EY=
    github.com/BurntSushi/toml@v1.2.1 h1:9F2/+DoOYIOksmaJFPw1tGFy1eDnIJXg+UHjuD8lTak=
    github.com/google/go-cmp@v0.5.9 h1:O2Tfq5qg4qc4AmwVlvv0oLiVAGB7enBSJ2x2DqQFi38=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/exp@v0.0.0-20221031165847-c99f073a8326 h1:QfTh0HpN6hlw6D3vu8DAwC8pBIwikq0AI1evdm+FksE=
    golang.org/x/exp/typeparams@v0.0.0-20221031165847-c99f073a8326 h1:fl8k2zg28yA23264d82M4dp+YlJ3ngDcpuB1bewkQi4=
    golang.org/x/mod@v0.7.0 h1:LapD9S96VoQRhi/GrNTqeBJFrUjs5UHCAtTlgwA5oZA=
    golang.org/x/sync@v0.1.0 h1:wsuoTGHzEhffawBOhz5CYhcrV4IdKZbEyZjBMuTp12o=
    golang.org/x/sys@v0.2.0 h1:ljd4t30dBnAvMZaQCevtY0xLLD0A+bRZXbgLMLU1F/A=
    golang.org/x/text@v0.4.0 h1:BrVqGRd7+k1DiOgtnFvAkoQEWQvBc25ouMJM6429SFg=
    golang.org/x/tools@v0.3.1-0.20221213193459-ca17b2c27ca8 h1:7/HkGkN/2ktghBCSRRgp31wAww4syfsW52tj7yirjWk=
    golang.org/x/vuln@v0.0.0-20221109205719-3af8368ee4fe h1:qptQiQwEpETwDiz85LKtChqif9xhVkAm8Nhxs0xnTww=
    honnef.co/go/tools@v0.3.3 h1:oDx7VAwstgpYpb3wv0oxiZlxY+foCpRAwY7Vk6XpAgA=
    mvdan.cc/gofumpt@v0.4.0 h1:JVf4NN1mIpHogBj7ABpgOyZc65/UUOkKQFkoURsz4MM=
    mvdan.cc/xurls/v2@v2.4.0 h1:tzxjVAj+wSBmDcF6zBB7/myTy3gX9xvi8Tyr28AuQgc=
go: go1.20
```

### go env
```bash
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jackgris/.cache/go-build"
GOENV="/home/jackgris/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/jackgris/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jackgris/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build44411116=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

Every time I open a go file my editor crash, no matter the size of the file, or the project where is the file. This started happening when I update go from 1.95 release to 1.20. The only way I found to fix that is still using the 1.95 release of go.

### What did you expect to see?

I'm using emacs, with lsp-mode. I expect to see lsp server start and connected to gopls

### What did you see instead?

Instead of that, emacs crash and don't say anything even I use debug flag when running my editor

### Editor and settings

I using the flavor spacemacs with the go layer

```lisp
     (go :variables go-backend 'lsp
         go-format-before-save t
         go-use-golangci-lint t)
```

### Logs

Is almost impossible to see what happen in ```*lsp-log*``` buffer, emacs crash really fast

**Comment by findleyr** [comment]
Gopls should never cause emacs to crash. When you downgrade to 1.19, do you reinstall gopls as well?

Can you run gopls as a daemon to try to see if there is a gopls crash?

In a terminal:
```
gopls -listen=localhost:8091
```

And then configure your editor to start gopls with `-remote=localhost:8091`.

This will allow you to see if the gopls daemon crashes.

**Comment by findleyr** [comment]
Also: you can pass `-logfile=/tmp/gopls.log` to have gopls write logs to a file.

**Comment by jackgris** [comment]
Well this's pretty weird to me, but when I run gopls like daemon and see the log a receive only this:
```bash
lsprpc.go:104: Session 15: connected
lsprpc.go:482: Session 15: got handshake. Logfile: "", Debug addr: ""
```
But also that makes emacs don't crash when I use go 1.20

To connect spacemacs to gopls daemon I had to put this on my spacemacs layer config:
```lisp
     (go :variables go-backend 'lsp :custom (lsp-gopls-server-args)
         go-format-before-save t
         go-use-golangci-lint t)
```
And edit that variable in the file lsp-go.el to this:
```lisp
(defcustom lsp-go-gopls-server-args '("-remote=localhost:8091")
```
So at the end with the flag ```lsp-gopls-server-args``` and restoring his value to:
```lisp
(defcustom lsp-go-gopls-server-args '("-remote=auto")
```
I can run emacs without any problem, I am not sure if is that right, but at least I can work with that.

Thanks for your time.

**Comment by jackgris** [comment]
Well, I discovered my problem was with golangci-lint, sorry for this issue.

**Comment by findleyr** [comment]
Thank you for following up, that is good to know!
