### ISSUE TITLE
cmd/asm: `type.xx` error in go1.20

### ISSUE THREAD

**Issue by timandy** [golang/go#58244]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.20

</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
` MOVQ    $type·int32(SB), AX`
asm build error, but it works fine in go1.19

relocation target type.int32 not defined

**Comment by tmthrgd** [comment]
It’s in the release notes: https://go.dev/doc/go1.20#linker.

**Comment by timandy** [comment]
MOVQ    $type:int32(SB), AX
build error also
 illegal or missing addressing mode for symbol type

**Comment by mknyszek** [comment]
CC @golang/compiler

**Comment by cherrymui** [comment]
I don't think we support reference type symbols in assembly code. And the name of type symbols is not guaranteed to be stable, and it can change at any time (as you noticed.) So this would not be expected to work. Thanks.

**Comment by timandy** [comment]
@cherrymui This answer is unacceptable, it worked fine until 1.20.

**Comment by timandy** [comment]
@cuonglm

**Comment by cuonglm** [comment]
@timandy I'm not sure what else to do here.

**Comment by ianlancetaylor** [comment]
@timandy I'm sorry this change broke your code, but internal symbol names are always subject to change.  We do not provide any guarantee for stability of assembler code.  We do our best, of course, but we make no promises.  These symbol names were changed for good reasons.

**Comment by timandy** [comment]
I'm not opposed to internal symbol modification, and golang is developing very well.
I modified my code to accommodate the 1.20 changes, but the compiler reported other errors. This change appears to be contradictory.

**Comment by timandy** [comment]
> @timandy I'm not sure what else to do here.

@cuonglm  Does the commit change the symbol, but the compilation does not recognize the new symbol

link: https://github.com/golang/go/commit/0f8dffd0aa71ed996d32e77701ac5ec0bc7cde01

**Comment by cuonglm** [comment]
> > @timandy I'm not sure what else to do here.
> 
> 
> 
> @cuonglm  Does the commit change the symbol, but the compilation does not recognize the new symbol
> 
> 
> 
> link: https://github.com/golang/go/commit/0f8dffd0aa71ed996d32e77701ac5ec0bc7cde01

See Cherry's explanation above. This is not supported feature, and also not guaranteed to be stable. The asm is also outside of Go1 promise.

**Comment by timandy** [comment]
#37762
