### ISSUE TITLE
x/crypto/ssh: too many private members

### ISSUE THREAD

**Issue by gopherbot** [golang/go#5826]
by **jeremy.f.stephens**:

<pre>I'm experimenting with crypto/ssh in order to implement X11 forwarding for a project. To
enable x11 forwarding, the server initiates a channel open message. However, most of the
internal functions used to open channels and to send messages are private. This makes
crypto/ssh unusable for this purpose.

Is it reasonable to export more functions so that users can create custom channels (not
just x11 channels)?</pre>

**Comment by hanwen** [comment]
@ianlancetaylor this bug is obsolete.
