### ISSUE TITLE
affected/package: wrong version in terminal go v1.20

### ISSUE THREAD

**Issue by Moranilt** [golang/go#58289]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.5 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/morani/Library/Caches/go-build"
GOENV="/Users/morani/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/morani/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/morani/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.19.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.19.5/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vm/7t7qkj_s5h9dlzrg9gkm2m7w0000gn/T/go-build1449309482=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

MacOS 13.2

1. Download https://go.dev/dl/go1.20.darwin-arm64.pkg installer of go v1.20
2. Run installer
3. Go to Terminal
4. Run `go version`

### What did you expect to see?
go version go1.20.0 darwin/arm64

### What did you see instead?
go version go1.19.5 darwin/arm64

`/usr/local/go/VERSION`: go1.20

**Comment by seankhliao** [comment]
you're using go installed by homebrew, not the installer.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by Moranilt** [comment]
@seankhliao, you are wrong. I'm **always** installing Go with installers from https://go.dev. But 1.20 is not installing correctly. Looks like it's bug in your installer for this version.

**Comment by Moranilt** [comment]
Exactly what helped: `brew uninstall go`
I have no clue how `go1.19.5` have been instaled on my PC after running `go1.20.0` installer. Anyway you helped me. Thank you.

P.S. Maybe it's a bug.

**Comment by seankhliao** [comment]
Homebrew may have installed go as a dependency of something else you installed.
The Go installer does not interact with homebrew.
