### ISSUE TITLE
x/website: go.dev/learn dark mode text contrast

### ISSUE THREAD

**Issue by talohana** [golang/go#58295]
### What is the URL of the page with the issue?

https://go.dev/learn

 
 
### What is your user agent?
 

 
[Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36](https://developers.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)
 
 
### Screenshot
 

 
![image](https://user-images.githubusercontent.com/24203431/216656418-23dadaec-4258-4a1e-ac6b-bad06cb14f5e.png)

**Comment by mknyszek** [comment]
CC @golang/tools-team

**Comment by talohana** [comment]
The issue seems to only happen on my external DELL U2722DE display, on my MBP monitor it seems to work: 
<img width="1706" alt="image" src="https://user-images.githubusercontent.com/24203431/216705651-2ff75a70-8b40-4559-9634-55d765d22785.png">

**Comment by thediveo** [comment]
That looks like a layout problem to me, as in a narrow window (regardless of monitor width) the text will flow into the graphic and that will never work well for dark themes.

**Comment by MarcusXavierr** [comment]
Maybe giving the circle a darker color would solve the problem
<img width="1296" alt="image" src="https://user-images.githubusercontent.com/59923581/217698559-eb87e703-257a-441c-b10f-4ec88ef73fa9.png">

<img width="1282" alt="image" src="https://user-images.githubusercontent.com/59923581/217698579-484aa6bd-f9af-42cc-a525-93766f48132d.png">

**Comment by suzmue** [comment]
Closing as fixed since this was addressed in the learn page redesign in http://go.dev/cl/445579.
