### ISSUE TITLE
x/build: failure to build on linux/riscv64

### ISSUE THREAD

**Issue by mknyszek** [golang/go#58307]
https://build.golang.org/log/441fa832fa6ef64f5d9f6bc6e6d04d232a5e1f12

**Comment by mknyszek** [comment]
(Just noting this down for a comment in some x/build code. I don't mean to imply this necessarily should work. Feel free to close.)

**Comment by dmitshur** [comment]
x/build is exempt from Go 1 compat and even the release policy as documented at the top of README; if the failing platform isn't something we want to go out our way to support (e.g. we only support coordinator on linux/amd64 where it runs, and darwin for convenience of development), we can just leave them out.

But this one is probably easier to fix than to ignore, i.e., just need to update to a newer version of that dependency.

```
build $ GOOS=linux GOARCH=riscv64 go build ./...
# github.com/prometheus/procfs
../../../../pkg/mod/github.com/prometheus/procfs@v0.2.0/cpuinfo.go:71:9: undefined: parseCPUInfo
build $ go get github.com/prometheus/procfs
go: upgraded github.com/prometheus/procfs v0.2.0 => v0.9.0
go: upgraded golang.org/x/sync v0.0.0-20220722155255-886fb9371eb4 => v0.1.0
go: upgraded golang.org/x/sys v0.1.0 => v0.3.0
build $ go mod tidy
build $ GOOS=linux GOARCH=riscv64 go build ./...
build $ echo $?
0
```
