### ISSUE TITLE
x/build/cmd/coordinator: enable misc-compile trybots for release branches

### ISSUE THREAD

**Issue by mknyszek** [golang/go#58311]
These are currently disabled because we don't have data on what breaks.

**Comment by dmitshur** [comment]
This issue tracks turning this on in the coordinator codebase (see [here](https://cs.opensource.google/go/x/build/+/master:dashboard/builders.go;l=1484-1486;drc=4ee487b137da815f5e68acb20a18dc0e6f9693be)), but that's going away soon ([CL 586776](https://go.dev/cl/586776)) and so there's no need to do this anymore.

In LUCI, the misc-compile trybots are already turned on both for release branches in the main Go repo, and for internal (e.g., vendor) branches in x/ repos.
