### ISSUE TITLE
runtime: problems running Windows binary under WINE

### ISSUE THREAD

**Issue by hanwen** [golang/go#5831]
<pre>Hi there,

I'm seeing something that looks like a race condition.

Symptoms:

* on Linux, run GOOS=windows go run standalone.go 

=&gt;

...
fatal error: malloc/free - deadlock
[signal 0xc0000005 code=0x0 addr=0x30 pc=0x41f570]

goroutine 1 [chan receive]:
net/rpc.(*Client).Call(0x8de7300, 0x686860, 0x3, 0x5bf0a0, 0x8de0508, ...)
    /home/hanwen/vc/go/src/pkg/net/rpc/client.go:310 +0xa9
main.main()
    /home/hanwen/go/src/barf/standalone.go:47 +0x312
 

* This is on Ubuntu 12.04 on amd64, with the .exe running on Wine 1.4-0ubuntu4.1.

* When applying works.patch, it goes back to working.  I've also bisected this problem
to <a href="https://code.google.com/p/go/source/detail?r=f800157ce425">https://code.google.com/p/go/source/detail?r=f800157ce425</a>

* It's possible that this a Wine problem, but anecdotally, we've seen frequent runtime
crashes on Windows 7 on VMWare with the original program too (dialog box with &quot;your
program has stopped.&quot;).

* If this is a Wine problem, what kind of bugreport should I file with the Wine folks?

* I'm on 

parent: 17191:a1fe2e3fadb0 tip
 misc/vim: Add compiler plugin for Go
branch: default
commit: 3 modified, 5 unknown
update: (current)</pre>

Attachments:
1. <a href="https://storage.googleapis.com/go-attachment/5831/0/standalone.go">standalone.go</a> (6484 bytes)
2. <a href="https://storage.googleapis.com/go-attachment/5831/0/works.patch">works.patch</a> (2326 bytes)

**Comment by AlekSi** [comment]
Linked issue #5873 is fixed.
