### ISSUE TITLE
runtime: cpu sample has wrong descripting comment in the code

### ISSUE THREAD

**Issue by subtle-byte** [golang/go#58327]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, I got the same result with go 1.20.

### What did you do?

I have program:
```go
package main

import (
	"os"
	"runtime"
	"runtime/trace"
)

func main() {
	runtime.SetCPUProfileRate(100)
	err := trace.Start(os.Stdout)
	if err != nil {
		panic(err)
	}
	for i := 0; i < 10000; i++ {
		for j := 0; j < 10000; j++ {
			_ = i + j
		}
	}
	defer trace.Stop()
}
```

The program provides a trace file as output.

### What did you expect to see?

I expect Cpu samples in the trace file will be in the format (as in [the source code of trace tool](https://github.com/golang/go/blob/2da8a55584aa65ce1b67431bb8ecebf66229d462/src/internal/trace/parser.go#L1081)):

```go
EvCPUSample         = 49 // CPU profiling sample [timestamp, stack, real timestamp, real P id (-1 when absent), goroutine id]
```

I.e. stack is second, real timestamp is third.

### What did you see instead?

Instead, I see the following events in the trace file:

```
event type: 49, args: [11 1755437435756 0 1 15]
event type: 49, args: [10 1755437928681 0 1 15]
event type: 49, args: [4 1755438251486 0 1 15]
```

So seems like real timestamp is on the second position, but more essential there is no stack id!

**Comment by subtle-byte** [comment]
Hi @rhysh, seems like [you added cpu samples to traces](https://github.com/golang/go/commit/2c0a9884e0dc930c1a3596bc1decf183c8fdcf77), could you take a look at this issue?

**Comment by subtle-byte** [comment]
After some investigation, looks like we have the stack id in the cpu sample, but the comment to the mentioned line is invalid - actually stack id is last, so the comment should look like:

```go
EvCPUSample         = 49 // CPU profiling sample [timestamp, real timestamp, real P id (-1 when absent), goroutine id, stack]
```

**Comment by mknyszek** [comment]
Thanks for sending a patch. In the future you don't need to file an issue about internal code comments, feel free to just send the PR. If you want to double-check your understanding, we'll hash it out in the review. If you have questions about the implementation in general, a good place to send a message https://groups.google.com/g/golang-dev.

(There's nothing inherently wrong with filing an issue, but I think it ends up being more work for you in the end and doesn't really serve the Go maintainers either.)
