### ISSUE TITLE
x/pkgsite: Beego package page contains a link to a GAMBLING advertisement

### ISSUE THREAD

**Issue by informatik01** [golang/go#58328]
On the Beego package page (a fork of the [Beego framework](https://github.com/beego/beego)), the link in the "More info at" section leads to some Indonesian online **gambling** advertisement page. 

Here is this Go package page:
https://pkg.go.dev/github.com/astaxie/beego

And here is the related "project" page (it **redirects** to a gambling advertisement page):
http://beego.me/

Please address this issue accordingly.

**Comment by ianlancetaylor** [comment]
CC @golang/pkgsite 

I think the real site is https://pkg.go.dev/github.com/beego/beego, but it has the same problem.  The README displayed at pkgsite is not the README on GitHub: the pkgsite one has the bad link to beego dot me.

**Comment by informatik01** [comment]
@ianlancetaylor 

> I think the real site is https://pkg.go.dev/github.com/beego/beego

Seems so. I mentioned that the reported project is a _fork_ of the original Beego etc.

What is interesting that on the GitHub page of the original Beego project, there is a link to the supposedly official home page (`https://beego.vip`) which is currently["unavailable" / down](https://www.isitdownrightnow.com/beego.vip.html). Didn't expect such situation for this quite a big project.

**Comment by ianlancetaylor** [comment]
OK, the reason that bogus link shows up on the astaxie/beego page is that the last tag in that repo is https://github.com/astaxie/beego/tree/v1.12.3, and in that tag the README has the bogus link.

In other words, pkg.go.dev is correctly reflecting the source of the package.  This should be fixed by the package.  I'm going to close this as I don't think there is anything to change on pkg.go.dev.  Thanks.

**Comment by informatik01** [comment]
I understand that on the "Go package" side everything is correct. Just sad that there is a way for placing unexpected advertisements or any unrelated and potentially harmful information without any consequences. 

Next time it could be some scam / phishing site and no penalties for that. 

But anyways...
