### ISSUE TITLE
runtime/cgo: Compilation Error

### ISSUE THREAD

**Issue by peterramaldes** [golang/go#58320]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes (latest release = 1.20)

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/peterramaldes/.local/go/bin"
GOCACHE="/home/peterramaldes/.cache/go-build"
GOENV="/home/peterramaldes/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/peterramaldes/.local/go/pkg/mod"
GONOPROXY="github.com/peterramaldes/*,gitlab.com/peterramaldes/*"
GONOSUMDB="github.com/peterramaldes/*,gitlab.com/peterramaldes/*"
GOOS="linux"
GOPATH="/home/peterramaldes/.local/go"
GOPRIVATE="github.com/peterramaldes/*,gitlab.com/peterramaldes/*"
GOPROXY="direct"
GOROOT="/home/peterramaldes/.asdf/installs/golang/1.20/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/peterramaldes/.asdf/installs/golang/1.20/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1632069434=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Try to build (`go build fetch.go`) this [program](https://go.dev/play/p/1EhUaVQ57X1) on Go 1.20 linux/amd64

### What did you expect to see?

The compilation did not failed on 1.20 (on 1.19.5 linux/amd64 did not failed)

### What did you see instead?

![image](https://user-images.githubusercontent.com/3129159/216769516-34709628-1179-4fa2-ac87-1b6cdf2d743e.png)

**Comment by seankhliao** [comment]
working as intended, with CGO_ENABLED=1, you need an appropriate C toolchain setup now that we no longer ship precompiled artifacts.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by peterramaldes** [comment]
I get it. Thank you @seankhliao .
