### ISSUE TITLE
x/pkgsite: package removal request for github.com/kobaxidze256/go-null

### ISSUE THREAD

**Issue by Kobaxidze256** [golang/go#58329]
### What is the path of the package that you would like to have removed?
github.com/kobaxidze256/go-null

 
 
 
### Are you the owner of this package?
Yes.

 
### What is the reason that you could not retract this package instead?
There's a new module where its URL points.

**Comment by suzmue** [comment]
Hi @Kobaxidze256, I see that at pkg.go.dev the information for [github.com/kobaxidze256/go-null](https://pkg.go.dev/github.com/kobaxidze256/go-null@v1.0.3) is from 3 days ago. Is this a different module than is there now?

There appear to be a couple of new tagged versions in the github repo, to get those into the module proxy (and onto pkg.go.dev) you need to make a request for the module version through the module proxy. There are a number of ways to do this and instructions on pkg.go.dev (https://pkg.go.dev/about#adding-a-package).

Visiting the following should add the version to pkgsite, and you can do the same for earlier versions if you want those to appear as well:
- https://proxy.golang.org/github.com/kobaxidze256/go-null/@v/v1.0.7.info



Removing this package from pkg.go.dev means that pkg.go.dev will no longer serve documentation for that package path at all, including the new module that is at that URL.  I see the latest version on pkg.go.dev was 1.0.3, so if you request any of the newer versions through the proxy (as described above), the latest information for the documentation will show this newer version.

**Comment by Kobaxidze256** [comment]
The new package is https://pkg.go.dev/github.com/Kobaxidze256/go-null .
I wrote an incorrect path in go.mod which resulted in the old path showing up on pkg.go.dev. I will remove the versions containing the old go.mod.

**Comment by suzmue** [comment]
Thanks for the clarification! I missed the change of case.

You should be able to retract the previous versions of the module using retract as follows:

1. Commit the following (with the old module path):

go.mod:
```
module github.com/kobaxidze256/go-null

go 1.19

retract (
  v1.0.8
  [v1.0.0, v1.0.3]
)
```

2. Tag v1.0.8
3. Revert go.mod to use the new module path.
go.mod:
```
module github.com/Kobaxidze256/go-null

go 1.18

... rest of go.mod file
```

**Comment by Kobaxidze256** [comment]
Did 1 and 2. I will do the third later. I'm expecting the old go doc page to change.

**Comment by Kobaxidze256** [comment]
It worked. Close the issue if you want.

**Comment by ianlancetaylor** [comment]
Thanks for following up.
