### ISSUE TITLE
cmd/compile: internal compiler error: panic: interface conversion: ir.Node is *ir.BasicLit, not *ir.ConstExpr

### ISSUE THREAD

**Issue by 578559967** [golang/go#58339]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/r/Library/Caches/go-build"
GOENV="/Users/r/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/r/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/r/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/Users/r/sdk/go1.20"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/r/sdk/go1.20/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/r/workspace/testcode/testinline/bug2.1/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/j_/rq9ph2cd3h50w468sgv34lwh0000gn/T/go-build2923148267=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version go1.20 darwin/arm64
GOROOT/bin/go tool compile -V: compile version go1.20
uname -v: Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000
ProductName:		macOS
ProductVersion:		13.1
BuildVersion:		22C65
lldb --version: lldb-1400.0.38.17
Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
</pre></details>

### What did you do?

`go.mod`:
```
module foo

go 1.20
```
`pkg/a.go`:
```go
package pkg

func Assert(msgAndArgs ...any) {
}

func Run() int {
        Assert("%v")
        return 0
}

func Run2() int {
        return Run()
}
```
`b.go`:
```go
package main

import "foo/pkg"

var A = pkg.Run2()

func main() {
}
```
`GOEXPERIMENT=nounified go1.20 build ./b.go`

### What did you expect to see?
Build successfully.

### What did you see instead?
```
# command-line-arguments
./b.go:5:5: internal compiler error: panic: interface conversion: ir.Node is *ir.BasicLit, not *ir.ConstExpr

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new
```

**Comment by cuonglm** [comment]
Sounds like the non-unified frontend importer import `"%v"` as an untyped constant: https://github.com/golang/go/blob/release-branch.go1.20/src/cmd/compile/internal/typecheck/iimport.go#L1283, while the unified IR frontend represents `"%v"` as a constant-fold - constant expression - node. That's why there's an ICE with `GOEXPERIMENT=nounified`.

The non-unified frontend is gone at tip, so I think there's nothing to do here.

cc @mdempsky

**Comment by randall77** [comment]
We should check 1.19. If it fails there we should arrange a backport for that.

**Comment by cuonglm** [comment]
> We should check 1.19. If it fails there we should arrange a backport for that.
> 
> 

Inline static init is only added in 1.20, 1.19 have no effect.

**Comment by sywhang** [comment]
Can confirm this issue is only happening on Go 1.20 and is currently blocking Uber's upgrade to Go 1.20.

**Comment by cuonglm** [comment]
> Can confirm this issue is only happening on Go 1.20 and is currently blocking Uber's upgrade to Go 1.20.

This only affects old unified IR IIRC, do you set `GOEXPERIMENT=nounified` in your go build?

**Comment by sywhang** [comment]
> do you set GOEXPERIMENT=nounified in your go build?

Unfortunately yes, we have some codegen based tooling that's seeing huge build time regression due to almost 10x regression in calling [gcexportdata.Read](https://pkg.go.dev/golang.org/x/tools/go/gcexportdata#Read) when we do not set that.

**Comment by cuonglm** [comment]
> > do you set GOEXPERIMENT=nounified in your go build?
> 
> Unfortunately yes, we have some codegen based tooling that's seeing huge build time regression due to almost 10x regression in calling [gcexportdata.Read](https://pkg.go.dev/golang.org/x/tools/go/gcexportdata#Read) when we do not set that.

Thanks for confirmation, I just worry there's another regression in Unified IR.

Note that `GOEXPERIMENT=nounified` will be gone in go1.21, so you may want to file new issue about that regression so we could take a look.

**Comment by sywhang** [comment]
An even simpler repro:
```
package main

import (
	"go.uber.org/zap"
)

var nopLogger = zap.NewNop()

func main() {
	nopLogger.Info("Hi")
}

```

**Comment by sywhang** [comment]
@mdempsky @cuonglm  Thanks for the reviews. Can this be backported to Go 1.20 branch?

**Comment by cuonglm** [comment]
> @mdempsky @cuonglm Thanks for the reviews. Can this be backported to Go 1.20 branch?

Let wait for the decision in https://github.com/golang/go/issues/58439. The fix there will also fix this issue if backported.

**Comment by cuonglm** [comment]
CL https://go-review.googlesource.com/c/go/+/467035 is going to be backported, so I don't think we need to backport this one.
