### ISSUE TITLE
cmd/compile: <autogenerated>:1: internal compiler error: dictionary for anyArr[go.shape.*uint8_0].Len should only use concrete types: go.shape.*uint8_0

### ISSUE THREAD

**Issue by fthvgb1** [golang/go#58332]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.10 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

it happend only 1.18.  
1.19,1.20 are normal.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.10"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/code/wp-go/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3258465993=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

building exec binary with my code github.com/fthvgb1/wp-go

<pre>go build --race -o wgo -gcflags "all=-N -l" internal/cmd/main.go
</pre>

### What did you expect to see?

builded runnable binray

### What did you see instead?

<pre>
# github.com/fthvgb1/wp-go/internal/plugins
<autogenerated>:1: internal compiler error: dictionary for anyArr[go.shape.*uint8_0].Len should only use concrete types: go.shape.*uint8_0

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new
</pre>

**Comment by cuonglm** [comment]
go1.18 is end of support, and there is policy to not backport generic fixes.

**Comment by fthvgb1** [comment]
ok, I get it.
