### ISSUE TITLE
x/pkgsite: package removal request for github.com/danielthomas/iomux / go-iomux

### ISSUE THREAD

**Issue by DanielThomas** [golang/go#58344]
### What is the path of the package that you would like to have removed?

https://pkg.go.dev/github.com/danielthomas/iomux
https://pkg.go.dev/github.com/danielthomas/go-iomux

These forks are now deleted.
 
### Are you the owner of this package?

Yes.
 
### What is the reason that you could not retract this package instead?

These were temporary repositories prior to the official repository going public (https://github.com/Netflix/go-iomux).

**Comment by suzmue** [comment]
Both packages have been removed. Closing as done!

**Comment by DanielThomas** [comment]
Thank you!
