### ISSUE TITLE
x/website: Invalid icon font

### ISSUE THREAD

**Issue by cidosx** [golang/go#58343]
### What is the URL of the page with the issue?
 
https://go.dev/
 
### What is your user agent?
 

 
 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
 
### Screenshot
 

 
 
<img width="1621" alt="image" src="https://user-images.githubusercontent.com/15716336/216861730-9ae60a3f-ca72-4ec2-9e00-092a0b7446cf.png">

 
### What did you do?
 

 
 Just visit the website

**Comment by gophun** [comment]
Do you use a JavaScript blocker?

**Comment by cidosx** [comment]
> Do you use a JavaScript blocker?

@gophun It's closed.
