### ISSUE TITLE
cmd/compile: internal compiler error: '(*Tree[go.shape.int]).RemoveParent.func1': value .dict (nil) incorrectly live at entry

### ISSUE THREAD

**Issue by anupcshan** [golang/go#58341]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Reproduces with Go 1.20, but not with 1.19.4

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/codespace/.cache/go-build"
GOENV="/home/codespace/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/codespace/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/codespace/go:/home/codespace/src/server/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/workspaces/goissue/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1991160894=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

`main.go`:
```
package main

func main() {
        _ = Tree[int]{}
}

type Tree[T comparable] struct {
        parent map[T]T
}

func (g *Tree[T]) RemoveParent(node T) {
        defer delete(g.parent, node)
        // To fix, remove "defer" from the above line, like below.
        // delete(g.parent, node)
}
```

### What did you expect to see?
```
$ go build
```

### What did you see instead?
```
$ go build
# goissue
./main.go:12:2: internal compiler error: '(*Tree[go.shape.int]).RemoveParent.func1': value .dict (nil) incorrectly live at entry

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new
```

```
$ GOEXPERIMENT=nounified go build
```

https://github.com/golang/go/issues/57778 shows the same error

**Comment by cuonglm** [comment]
It seems to me that `GOEXPERIMENT=nounified` build ok, but unified IR crashes.

**Comment by cuonglm** [comment]
Seems we need to backport this? @mdempsky @randall77

**Comment by mdempsky** [comment]
@cuonglm Yes, I think so.

@gopherbot Please backport to Go 1.20.

**Comment by mdempsky** [comment]
FWIW, as a workaround until a fix is included in a point release, if you change `defer delete(m, k)` into `defer func() { delete(m, k) }()`, it should work. The same applies to any other go/defer calls to builtin functions within a generic function/method.
