### ISSUE TITLE
x/pkgsite: package removal request for github.com/0xWaleed/pomod

### ISSUE THREAD

**Issue by 0xWaleed** [golang/go#58357]
### What is the path of the package that you would like to have removed?

 
 github.com/0xWaleed/pomod
 
### Are you the owner of this package?

Yes I am the owner 
 
### What is the reason that you could not retract this package instead? 
I publish this accidentally and not yet even ready. it's already has multiple versions
1.x.x and is not ready yet. Also I want to start the versioning from v1.x.x rather than starting
with v2

**Comment by seankhliao** [comment]
Sorry, there's no way to change what the contents of already published tags point to. You can hide them with retract, but not reuse them.
