### ISSUE TITLE
x/playground/cmd/latestgo: use gerrit for resolving go versions

### ISSUE THREAD

**Issue by findleyr** [golang/go#58350]
In #58305, we observed that there is a race in the x/playground deployment: the deployment is triggered by git tagging, but uses maintner for repo information, and maintner state changes are triggered by pub/sub. As a result, the playground deployment found the wrong go versions.

We should update cmd/latestgo to use the same information as the trigger. @dmitshur pointed to the following reference where x/build determines Go versions: https://cs.opensource.google/go/x/build/+/master:internal/task/version.go;l=24-47;drc=dd73d1bda781b30f2e6d723897aa0113c72f2534.

Low priority, but it would be nice if this were done at least before Go 1.21, else we may find that the playground serves stale versions again.

This is a self-contained project that is easy to test, and therefore would be a good opportunity for external contribution.

CC @golang/release @toothrot

**Comment by petergeorgas** [comment]
Does this still need fixed? I would love to do this.

**Comment by findleyr** [comment]
@petergeorgas yes this still needs fixing. Please feel free to take it on.
