### ISSUE TITLE
gobootstrap: Doesn't respect `GOARCH=amd64`, `CC='arch -x86_64 clang'`, or `CC='clang -arch x86_64'` on Apple silicon

### ISSUE THREAD

**Issue by steakknife** [golang/go#58368]
### Environment

- Go 1.19.5 (latest stable) amd64
- macOS 13.2 Apple silicon

### Tried

- `arch -x86_64 ./make.bash`
- `env CC='clang -arch x86_64' ./make.bash`
- `env GOARCH=amd64 ./make.bash`

### What did you expect to see?

Build for amd64

### What did you see instead?

Built for arm64 or build failure

`~/homebrew.x86_64/Cellar/go/1.19.5/bin/go: Mach-O 64-bit executable arm64`

### Resolution

`env GOHOSTARCH=amd64 ./make.bash`

`~/homebrew.x86_64/Cellar/go/1.19.5/bin/go: Mach-O 64-bit executable x86_64`

Not resolved by #43476

**Comment by seankhliao** [comment]
make.bash uses a different set of env vars as documented in its preamble, eg CC_FOR_TARGET.
you probably should be using the arm build on apple silicon.

if you want to file a bug report, please fill out the template we've asked for, as well as proper documentation of what you did, and what happened.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
