### ISSUE TITLE
x/playground: errors running locally

### ISSUE THREAD

**Issue by comdiv** [golang/go#58372]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.19.5

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
</pre></details>

### What did you do?

Try to launch golang/playground locally, with instruction from `https://github.com/golang/playground`

### What did you expect to see?

Working playground 

### What did you see instead?

When Run button pressed - it's web interface writes  
```
Error communicating with remote server.
Program exited.
```

In terminal log where is following problem:

```
Listening on :8080 ...
2023/02/07 05:30:40 http: panic serving 172.17.0.1:50798: no SANDBOX_BACKEND_URL environment and no default defined for project ""
goroutine 41 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1850 +0xbf
panic({0xcfbfc0, 0xc0001be2d0})
	/usr/local/go/src/runtime/panic.go:890 +0x262
main.sandboxBackendURL()
	/go/src/playground/sandbox.go:569 +0xbe
main.sandboxRun({0x11b1a00, 0xc000114660}, {0xc00004ac80, 0x1c}, {0x0, 0x0})
	/go/src/playground/sandbox.go:497 +0x19c

```

when try `make runlocal` it's not working too, but with another message

```
Listening on :8080 ...
cmdFunc error: POST "http://sandbox_dev.sandnet/run": Post "http://sandbox_dev.sandnet/run": dial tcp: lookup sandbox_dev.sandnet: no such host


```

No idea how to launch it locally....

**Comment by bcmills** [comment]
> What did you do?

What were the commands that you ran?

**Comment by essodjolo** [comment]
Hi @bcmills,
I'm having the same issue, and here's the command I ran:
```shell
docker run --name=goplay -p 8181:8080 golang/playground
```

**Comment by essodjolo** [comment]
Finally used https://github.com/x1unix/go-playground which ran smoothly.
