### ISSUE TITLE
access: gerrit approvers

### ISSUE THREAD

**Issue by aeitzman** [golang/go#58390]
Hi,

I'd like to request "approvers" access https://go-review.googlesource.com/#/admin/groups/1005,members for eitzman@google.com

See https://go.dev/wiki/GerritAccess

**Comment by seankhliao** [comment]
cc @golang/release

**Comment by dmitshur** [comment]
Hello,

Thanks for your contributions and making this access request. The "approvers" access permits reviewing and submitting CLs across the entire Go project as documented https://go.dev/wiki/GerritAccess#approving-cls-approvers, so it needs a longer history of contributions and demonstrated familiarity with the Go project before granting access can be considered.

Please feel free to make this request again at a later time. Thank you.
