### ISSUE TITLE
x/pkgsite-metrics/internal/pkgsitedb: build failures on `plan9` since CL 464901

### ISSUE THREAD

**Issue by bcmills** [golang/go#58414]
[CL 464901](https://go.dev/cl/464901) (attn @julieqiu, @jba) added a dependency on `github.com/lib/pq`, which assumes the existence of a `syscall.Stat_t`:
https://github.com/lib/pq/blob/922c00e176fb3960d912dc2c7f67ea2cf18d27b0/ssl_permissions.go#L77
The file is build-constrained to `!windows`, but `syscall.Stat_t` is not defined on `plan9` either.
(This looks like an upstream bug in the `github.com/lib/pq` module.)

This can be addressed by fixing the build for `plan9` (by either fixing the upstream dependency or build-constraining away its uses on `plan9`), or if `x/pkgsite-metrics` intentionally does not support that `GOOS`, by configuring x/build/cmd/coordinator not to test that repo on its builders.

(CC @golang/plan9)

**Comment by jba** [comment]
Fixed by http://go.dev/cl/466415.
