### ISSUE TITLE
cmd/covdata: `short read on string table` when merging coverage counters

### ISSUE THREAD

**Issue by yihuang** [golang/go#58411]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/yihuang/Library/Caches/go-build"
GOENV="/Users/yihuang/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/yihuang/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/yihuang/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/nix/store/0m3v5yn7s5ipvzp7p462pvjknfcn8c6s-go-1.20/share/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/nix/store/0m3v5yn7s5ipvzp7p462pvjknfcn8c6s-go-1.20/share/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.20"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/yihuang/src/cronos/go.mod"
GOWORK=""
CGO_CFLAGS="-I/nix/store/qg6n4gdcccfd93lnih1yh8a894ya6akr-rocksdb-7.9.2/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-L/nix/store/qg6n4gdcccfd93lnih1yh8a894ya6akr-rocksdb-7.9.2/lib -lrocksdb"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3_/dt3cb8952_12y960nh8fhqx40000gn/T/go-build3007670481=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Use `-cover` to collect coverage report in integration tests.

### What did you expect to see?

`go tool covdata` should be able to process generated file succesfully.

### What did you see instead?

```
$ go tool covdata merge -i integration_tests/coverage -o profile.txt
error: error: reading counter data file integration_tests/coverage/covcounters.627546bfc793cab3f06764545dba1bd1.91113.1675846217322297000: error: short read on string table
```

The tarball of generated coverage directory are attached, it can reproduced stably, both in CI(linux) and laptop(macOS).

[coverage.tar.gz](https://github.com/golang/go/files/10686484/coverage.tar.gz)

**Comment by bcmills** [comment]
(attn @thanm; CC @golang/compiler)

**Comment by thanm** [comment]
Thanks, I will take a look.

**Comment by thanm** [comment]
Thank you for sending this report, it is an interesting bug in the coverage profile reader, specifically the portion that reads counter data files.  It appears that the bug is only tickled when you have a small counter data file (large ones will be mmap'd) that has a string table larged than the bufio.Reader 4k buffer size (which might explain why I didn't hit it previously in my testing). 

Sending a CL with a fix shortly.  I will also ask the release team if the fix can be back-ported to Go 1.20.1

**Comment by thanm** [comment]
@gopherbot please backport to 1.20

**Comment by thanm** [comment]
I have started the process to get this approved for backport to 1.20, however I think it will have to wait until the March minor release (too late for the Feb cycle), just FYI.
