### ISSUE TITLE
runtime: copystack doesn't adjust frame pointers on arm64

### ISSUE THREAD

**Issue by felixge** [golang/go#58432]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using

any/arm64

### What did you do?

Try to implement frame pointer unwinding for the tracer ([gh 16638](https://github.com/golang/go/issues/16638), [wip patch](https://go-review.googlesource.com/c/go/+/463835)).

### What did you expect to see?

copystack should adjust frame pointers on the stack when growing the stack.

### What did you see instead?

[TODO what about arm64 frame pointer adjustment?](https://github.com/golang/go/blob/46e3d9d12a51e6783ac8a244f13a9a96abfef85e/src/runtime/stack.go#L678) 😅.

Seems like this issue was missed when the [CL 61511](https://go-review.googlesource.com/c/go/+/61511) for this landed in 2018.

This is causing lots of crashes when trying to frame pointer unwind stacks that have grown.

**Comment by felixge** [comment]
@mknyszek @prattmic @aclements FYI. Took me a while to debug the fp unwinding crashes I saw, but this seems to be easy to fix (see CL above). However, the fix reveals (or causes?) more issues with frame pointers on arm64, details are in the CL.

I'm putting this on hold for now and will focus on making fp unwinding work on amd64 first. But if anybody has a good idea, please let me know :).

**Comment by bcmills** [comment]
(CC @golang/arm)

**Comment by erifan** [comment]
There's a lot of work to be done here, can you try if this CL works for you first?

**Comment by felixge** [comment]
Thanks @erifan - I hadn't seen this CL. Will definitely try it out.

**Comment by felixge** [comment]
> There's a lot of work to be done here, can you try if this CL https://go-review.googlesource.com/c/go/+/241158 works for you first?

My colleague @nsrip-dd and I are currently looking at this. Could you elaborate what you mean by "a lot of work to be done here"? We can't really figure out why the patch had stalled and what other things might need to be done here. cc @cherrymui

**Comment by cherrymui** [comment]
I'm not sure there are a lot. But I'm also not sure if that CL is not enough to ensure frame pointer working everywhere. (It is probably enough for this particular issue.) There are probably a few places we smashed the frame pointer. CL https://golang.org/cl/241080 was one I found. There may be others. Syscall wrappers might be some. I'm happy to update that CL.
