### ISSUE TITLE
proposal: Functional Go(built in support for lambda, foreach ,map , filter , map )

### ISSUE THREAD

**Issue by gitsupi** [golang/go#58443]
proposal: Functional Go(built in support for lambda, foreach ,map , filter , map )

**Comment by seankhliao** [comment]
Duplicate of #21498

**Comment by gitsupi** [comment]
why not planned

**Comment by loveyandex** [comment]
@seankhliao

**Comment by 4cq2** [comment]
https://github.com/golang/go/issues/58014
