### ISSUE TITLE
affected/package: 

### ISSUE THREAD

**Issue by duckbrain** [golang/go#58453]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jonathan/.cache/go-build"
GOENV="/home/jonathan/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/jonathan/.go/pkg/mod"
GONOPROXY="bitbucket.org/abacastinc"
GONOSUMDB="bitbucket.org/abacastinc"
GOOS="linux"
GOPATH="/home/jonathan/.go"
GOPRIVATE="bitbucket.org/abacastinc"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="<censored>"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2592279368=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Run an existing test utilizing `http.NewFileTransport` that does a `POST`.

### What did you expect to see?

In previous releases, my test passes.

### What did you see instead?

The `RoundTripper` returned by `http.NewFileTransport` now errors on a `POST` request

```json
{"error": "status 405: \"Method Not Allowed\" read-only"}
```

This appears to be a side-effect of changing the behavior for `http.FileServer`  https://go-review.googlesource.com/c/go/+/413554

From https://pkg.go.dev/net/http#NewFileTransport

> The returned RoundTripper ignores the URL host in its incoming requests, as well as most other properties of the request.

It's not clear to me that the old behavior was correct, but "most other properties" leaves a lot of room for interpretation there. It does make sense to me that a file system handler would need to be strict, but a `RoundTripper` that pulls from disk seems mostly useful for mocking out the responses of an `http.Client`.

**Comment by seankhliao** [comment]
I believe this is the intended behavior (not just a side effect) for the change that you've found.

POST probably only makes sense if you were allowed to update the file.
There are other, more appropriate ways of mocking out responses.
