### ISSUE TITLE
runtime: access faults to memory mapped files on windows can't be caught by using SetPanicOnFault

### ISSUE THREAD

**Issue by secDre4mer** [golang/go#58457]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go 1.19
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

windows/amd64

### What did you do?

Memory map a file on an external disk (using CreateFileMapping / MapViewOfFile)
Call debug.SetPanicOnFault(true)
Eject the external disk
Try to read from the memory map

### What did you expect to see?
The read should cause a panic since the access fails.

### What did you see instead?
The runtime faults (`Exception 0xc0000006 0x0 ...`) instead of panicing, thus preventing the user from recovering from this error.

**Comment by qmuntal** [comment]
@golang/windows

**Comment by qmuntal** [comment]
Windows docs seems to back @secDre4mer proposed solution (implemented in CL 467195): https://learn.microsoft.com/en-us/windows/win32/memory/reading-and-writing-from-a-file-view

> Reading from or writing to a file view of a file other than the page file can cause an EXCEPTION_IN_PAGE_ERROR exception. For example, accessing a mapped file that resides on a remote server can generate an exception if the connection to the server is lost. Exceptions can also occur because of a full disk, an underlying device failure, or a memory allocation failure.
