### ISSUE TITLE
syscall: implement Sendfile for NetBSD and OpenBSD

### ISSUE THREAD

**Issue by minux** [golang/go#5847]
<pre><a href="https://groups.google.com/d/topic/golang-nuts/8Dx-na22PkU/discussion">https://groups.google.com/d/topic/golang-nuts/8Dx-na22PkU/discussion</a></pre>

**Comment by coypoop** [comment]
netbsd doesn't have sendfile. I don't think openbsd does either.

**Comment by 4ad** [comment]
That's right.
