### ISSUE TITLE
proposal: for iterator: add syntax for iterating with reference

### ISSUE THREAD

**Issue by sonalys** [golang/go#58486]
Hello everyone, I think it would be really nice if we could iterate through slices without copying data. I know it's possible to use slice of pointers, or declaring the reference in a new line, but it would be really practical.

I think something like the following example would be really great:
```go
for index, &ref := range slice {
  ...
}
```
It would solve the following scenario:
```go
for index := range slice {
  ref := &slice[index]
  ...
}
```

Thanks for your work and attention.
I searched for this feature request previously and didn't find anything, if this is a duplicate, sorry.

**Comment by seankhliao** [comment]
I think this goes counter to our approach of further isolating loop variables, which would make the slice of pointers safer to use, see #56010
