### ISSUE TITLE
x/website: short links should work on tip.golang.org

### ISSUE THREAD

**Issue by rittneje** [golang/go#58484]
### What is the URL of the page with the issue?

https://tip.golang.org/doc/go1.20#compiler

### What did you do?

If you look at the release notes on https://go.dev/doc/go1.20#compiler, the text "rejects anonymous interface cycles" links to `https://go.dev/issue/56103`, which results in a 302 redirect to `https://github.com/golang/go/issues/56103`.

However, if you look at the release notes on https://tip.golang.org/doc/go1.20#compiler, the link is for `https://tip.golang.org/issue/56103`, which results in a 404 and thus renders the `to, err := human()` page.

### What did you expect to see?

Either `https://tip.golang.org/issue/56103` should redirect to `https://github.com/golang/go/issues/56103`, or the release notes should just directly link to GitHub in the first place.

### What did you see instead?

![image](https://user-images.githubusercontent.com/28784688/218372641-e60657eb-b627-4646-8238-56f22222723b.png)

**Comment by aryanvarma7272** [comment]
Hey @rittneje , I would like to work on this issue ...

**Comment by aryanvarma7272** [comment]
I am very new to open source , I tried to search alot for the text "rejects anonymous interface cycles" but couldn't find , @rittneje please help me solve this issue and make me move one step forward in my open source contribution journey
Thank you.

**Comment by ianlancetaylor** [comment]
The text is at https://go.googlesource.com/website/+/refs/heads/master/_content/doc/go1.20.html#339.

But the fix for this is not to change that file.  This fix for this is to change tip.golang.org so that /issue links redirect as they do for go.dev.  See references to tip.golang.org and gotip in the Go files in go.googlesource.com/website.

**Comment by aryanvarma7272** [comment]
@ianlancetaylor Thanks for replying , But I suspect that the file go1.20.html is not present on my localhost but can be seen when inspecting or viewing the source code.  In this type of situation , what can i do more ?

**Comment by ianlancetaylor** [comment]
I'm sorry, I don't understand the question.  To be clear, I suspect that fixing this issue is going to require checking out the source code from go.googlesource.com/website and changing it so that the /issue (and /cl) shortlinks from tip.golang.org redirect correctly.

**Comment by aryanvarma7272** [comment]
@ianlancetaylor 

![issue](https://user-images.githubusercontent.com/89654334/218671301-00b50dd0-d9fb-494c-9328-78a98138803e.png)



I can find the above code for the site https://go.dev/issue/56103 which redirects to https://github.com/golang/go/issues/56103.

*********************************

First line specifies that its for site https://go.dev/doc/go1.20#compiler  
but the changes have to be done in [https://tip.golang.org/doc/go1.20#compiler](https://tip.golang.org/doc/go1.20#compiler)

I understood what changes are to be made ..
But I can't find the text "rejects anonymous interface cycles" which is linked with the url value  [https://tip.golang.org/doc/go1.20#compiler]


***********************************

If I would get the text " rejects anonymous interface cycles" which is linked with https://tip.golang.org/issue/56103 then I will make the appropriate changes which will then be redirected to https://github.com/golang/go/issues/56103

Hope you understand
Thanks for helping : )

**Comment by rittneje** [comment]
@aryanvarma7272 I think you have misunderstood what is to be done. The link I mentioned in the original issue is just one example of the problem. The fix is NOT to fix the link itself. Rather, it is add/fix the redirection logic in the tip.golang.org server.

Here is where the redirection logic is set up:
https://github.com/golang/website/blob/a69753836928bab0cc4c3a2e6fc127572c1787bf/internal/redirect/redirect.go#L31-L34

For some reason, it seems that code is not running on tip.golang.org (or it isn't working correctly).

**Comment by David-Mao** [comment]
Any progress on this issue? The problem exists for newer release notes too. For example, in https://tip.golang.org/doc/go1.22 and https://tip.golang.org/doc/go1.23 , the links of issues and go playground pages don't work.
