### ISSUE TITLE
x/pkgsite: package removal request for github.com/Avanis-GmbH/GoSUCK

### ISSUE THREAD

**Issue by Valentin-Kaiser** [golang/go#58507]
### What is the path of the package that you would like to have removed?

> pkg.go.dev/github.com/Avanis-GmbH/GoSUCK

 
 
### Are you the owner of this package?

> Organization Owner and Code Author

 
### What is the reason that you could not retract this package instead?

We renamed the package to github.com/Avanis-GmbH/shopware-kit and we dont want to support the old package path.

**Comment by jamalc** [comment]
Done.
