### ISSUE TITLE
affected/package: time

### ISSUE THREAD

**Issue by Tang8330** [golang/go#58510]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go 1.20
</pre>

### Does this issue reproduce with the latest release?

YES

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
</pre></details>

### What did you do?

Go's native `time.Time.String()` and `time.Parse()` have incompatible formats.

### What did you expect to see?

I expect to be able to use the same `format` from `time.Now().String()` to be able to parse it.

### What did you see instead?
`error: parsing time "2009-11-10 23:00:00 +0000 UTC m=+0.000000001": extra text: " m=+0.000000001"`
## Repro

https://go.dev/play/p/kDo5BVr1xU0

**Comment by imkos** [comment]
time.Parse("2006-01-02 15:04:05.999999999 -0700 MST m=+0.000000001", now.String())  ?

**Comment by Tang8330** [comment]
Yeah, if you append `m=+0.000000001` to the layout, it'll work. But we shouldn't have to.

**Comment by ianlancetaylor** [comment]
That is how the time package works.  We aren't going to change it now.

**Comment by Tang8330** [comment]
> That is how the time package works. 

Why?

**Comment by ianlancetaylor** [comment]
It seemed important to include the monotonic time in `Time.String` so that people could more clearly understand how it was behaving.  It's easy to remove the monotonic time by using `t.Round(0)` as explained in the package documentation at https://pkg.go.dev/time.
