### ISSUE TITLE
x/pkgsite: package removal request for github.com/askripalev/go2go

### ISSUE THREAD

**Issue by askripalev** [golang/go#58516]
### What is the path of the package that you would like to have removed?
github.com/askripalev/go2go 
 
### Are you the owner of this package?
Yes

### What is the reason that you could not retract this package instead?
Package was published accidentally 'cause I forgot to set GOPRIVATE environment variable.
Anyway I need it no any longer, so I've removed the repo as well.
If there are any leftovers of github.com/askripalev, please remove them as well - I will add this prefix to GOPRIVATE.

**Comment by jamalc** [comment]
Done.
