### ISSUE TITLE
affected/package: encoding/json

### ISSUE THREAD

**Issue by orestonce** [golang/go#58511]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3904791243=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

````go
package main

import (
	"encoding/json"
	"fmt"
	"strconv"
)

func main() {
	var s1 = string([]byte{0xff})
	b1, err := json.Marshal(s1)
	if err != nil {
		panic(err)
	}
	var s2 string
	err = json.Unmarshal(b1, &s2)
	if err != nil {
		panic(err)
	}
	fmt.Println(s1 == s2)
	fmt.Println(strconv.Quote(s1), strconv.Quote(s2))
}
````

### What did you expect to see?

true
"\xff" "\xff"

### What did you see instead?

false
"\xff" "�"

**Comment by ianlancetaylor** [comment]
The documentation says "String values encode as JSON strings coerced to valid UTF-8, replacing invalid bytes with the Unicode replacement rune."  That is what you are seeing here.  The string `"\xff"` is not valid UTF-8.
