### ISSUE TITLE
x/pkgsite: package reset request for github.com/supabase/gotrue

### ISSUE THREAD

**Issue by hf** [golang/go#58544]
The package mentioned was a fork of `github.com/netlify/gotrue` but the repo is now unforked. We need to reset the pkg.go.dev index so it picks up the correct package instead.

### What is the path of the package that you would like to have removed?

`github.com/supabase/gotrue`

### Are you the owner of this package?

One of the owners, yes.

### What is the reason that you could not retract this package instead?

As mentioned above, the package is an unfork of a forked repo.

**Comment by seankhliao** [comment]
we can't "reset" anything, only hide documentation
note your versioning is incompatible, v2+ requires the `/vN` suffix in module paths

**Comment by hf** [comment]
> we can't "reset" anything, only hide documentation

How is the unfork case handled then? Do we have to do an explicit rename?

**Comment by jamalc** [comment]
I'm not sure what the "unfork" case means. `github.com/supabase/gotrue` and `github.com/netlify/gotrue` are distinct modules. Is your intention to have `github.com/supabase/gotrue` redirect to `github.com/netlify/gotrue`? That would require an explicit rename.

Would you like to hide the documentation for `github.com/supabase/gotrue`?
