### ISSUE TITLE
affected/package: go 1.15 and go 1.20 bug

### ISSUE THREAD

**Issue by xwb1993** [golang/go#58540]
### What version of Go are you using (`go version`)?

<pre>
$ go version go 1.15 and go 1.20

</pre>

### Does this issue reproduce with the latest release?
no

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\asus\AppData\Local\go-build
set GOENV=C:\Users\asus\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\asus\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\asus\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.20
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\asus\AppData\Local\Temp\go-build624360970=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

![e80db1923c200cf2d468c4d408629e7](https://user-images.githubusercontent.com/18282502/218990716-fa557faa-992c-479b-a151-e3eaf7559b89.png)

### When i use go 1.15,get this result,"ApplicationVndSecurityVulnerabilityReportVersion11" is Capital

![047bc689da074a8c19eb689a382c73d](https://user-images.githubusercontent.com/18282502/218990830-ccdd93a1-92c0-42e9-8513-c6f7132ff7e7.png)

### But when i use go 1.20,"ApplicationVndSecurityVulnerabilityReportVersion11" is in lowcase

![08a4e3d453ab1c80f1acdef8195c050](https://user-images.githubusercontent.com/18282502/218991028-7a628555-cc7c-4eda-b7dd-2e8f75ea945f.png)

**Comment by seankhliao** [comment]
We only support the 2 most recent releases (1.20, 1.19), soory.

**Comment by xwb1993** [comment]
> We only support the 2 most recent releases (1.20, 1.19), soory.

So there is any other methods if i want use go 1.15 to Unmarshal "ApplicationVndSecurityVulnerabilityReportVersion11" in lowcase?
