### ISSUE TITLE
Non-obvious interpretation of an empty switch

### ISSUE THREAD

**Issue by fpawel** [golang/go#58558]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/pafilimo10/Library/Caches/go-build"
GOENV="/Users/pafilimo10/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/pafilimo10/GOPATH/pkg/mod"
GONOPROXY="gitlab.services.mts.ru"
GONOSUMDB="gitlab.services.mts.ru"
GOOS="darwin"
GOPATH="/Users/pafilimo10/GOPATH"
GOPRIVATE="gitlab.services.mts.ru"
GOPROXY="https://nexus.services.mts.ru/repository/go-proxy/"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/pafilimo10/GolandProjects/awesomeProject1/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ty/469mkn2n2rz1jy631_ydldhxbrhs6k/T/go-build1661517278=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

- run this code with go run ./... f.e.
```
package main

func main() {
	f := func() bool {
		return false
	}
	switch f()
	{
	case true:
		println(1)
	case false:
		println(0)
	}
}
```

### What did you expect to see?
0

### What did you see instead?
1

# Explanation 

In fact we have here a switch with an empty condition, which is switch(true)

https://go.dev/play/p/OnkQDMKawZG ==  https://go.dev/play/p/hDndn2tXzbU == https://go.dev/play/p/b7tnWKQJS4H

the compiler takes and converts this 
```
switch f() 
{
```
to this 
```
switch f() ; { // switch(true) 
```
for good this code should not compile at all
```
switch f() 
{
```
otherwise we can get non-obvious and bug-prone behavior

**Comment by seankhliao** [comment]
this is due to semicolon insertion rules.
running `go fmt` over the third example will turn it into the second, making it obvious what's happening.

unfortunate, but working as intended.
