### ISSUE TITLE
x/playground: not showing vet warnings

### ISSUE THREAD

**Issue by Deleplace** [golang/go#58560]
### What version of Go are you using (`go version`)?

<pre>
go1.20.1
</pre>
([in the playground](https://go.dev/play/p/Rk28OKHjNHc) actually, not my computer)

### Does this issue reproduce with the latest release?

Yes

### What did you do?

In the Go playground:
- executed [program 1](https://go.dev/play/p/g3iO751-3NW) which has a loop variable capture problem
- executed [program 2](https://go.dev/play/p/8OWt-5ZqRPp) which passes a Mutex by value

### What did you expect to see?

Program 1:
```
./prog.go:11:16: loop variable i captured by func literal
5
5
5
5
5
```

Program 2:
```
./prog.go:8:16: call of work copies lock value: sync.Mutex
./prog.go:11:23: work passes lock by value: sync.Mutex
Done
```

### What did you see instead?

Program 1:
```
5
5
5
5
5
```

Program 2:
```
Done
```

This is not expected because the playground's About explicitly says "The service receives a Go program, [**vets**](https://go.dev/cmd/vet/), compiles, links, and runs the program inside a sandbox, then returns the output". If the service does vet, then I'm expecting to see the vet warnings.

**Comment by bcmills** [comment]
(attn @toothrot @findleyr)

**Comment by Deleplace** [comment]
The vet error message is not reaching the browser anymore, as the JSON key `"VetErrors"` is missing from the "compile" HTTP response:

<img width="940" alt="image" src="https://user-images.githubusercontent.com/13508141/223136536-714861e2-b8ce-4d12-9fa6-e9dcaaa8d563.png">

The old JSON on the left is the response of a POST request to https://gotipplay.golang.org/compile 

The new JSON on the right is the response of a POST request to https://go.dev/_/compile?backend=

**Comment by Deleplace** [comment]
In both cases (old and new), the request to the endpoint `compile` has in its payload `withVet: true`.  This seems to point at the server behaving differently.

**Comment by findleyr** [comment]
It also looks like there were styles in the stylesheet that were not being applied, due to selectors changing in the new playground. I fixed that as well (assuming that was unintentional):

![image](https://user-images.githubusercontent.com/57144380/226999290-be8fc212-a9d9-4268-a397-4b1b81e3de38.png)

**Comment by Deleplace** [comment]
\o/ fantastic, thank you Robert

**Comment by findleyr** [comment]
Thank you @Deleplace for reporting this, helping to root cause, and for providing feedback on the colors!
