### ISSUE TITLE
x/pkgsite: https://pkg.go.dev/github.com/alparslanahmed/weightedrandom

### ISSUE THREAD

**Issue by alparslanahmed** [golang/go#58562]
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/alparslanahmed/weightedrandom

### What is your user agent?
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

### Screenshot
![image](https://user-images.githubusercontent.com/5161926/219399746-1cd3b66f-a53e-4ecc-bdf2-f68572343f84.png)

### What did you do?

I just enter to url and clicked Request button many times. Also i changed module name from go.mod file because it was different from the github url.

### What did you expect to see?
Module page

### What did you see instead?
Error page

**Comment by findleyr** [comment]
Looks like this package is there now. Please let me know if there's still a problem.
