### ISSUE TITLE
cmd/compile: ICE: "must have bodyReader for type..hash.[type]"

### ISSUE THREAD

**Issue by mdempsky** [golang/go#58572]
We have a Google-internal package that's failing to build since 25f5d9d4a253cb880bff909ebbdc05c8941c4a48 (https://go.googlesource.com/go/+/25f5d9d, /cc @cuonglm).

Mostly minified test case here: https://go.dev/play/p/jddWxVs4sf0?v=gotip

**Comment by mdempsky** [comment]
Further minimized: https://go.dev/play/p/fkRXZrXwIfe?v=gotip

**Comment by mdempsky** [comment]
Since CL [436961](https://go-review.googlesource.com/c/go/+/436961) isn't essential, I'm leaning towards reverting it for now and adding the regress test case; and then we can try that CL again but without breaking the test case.

**Comment by cuonglm** [comment]
@mdempsky seems that we should relax the check in bodyReaderFor to assert only in case of local functions?

Previously, the type hash functions is generated during local package compilation, but they are from pseudo package `type`, not local package. Before https://github.com/golang/go/commit/25f5d9d4a253cb880bff909ebbdc05c8941c4a48, we create these ONAME nodes with nil func, so they couldn't reach `unifiedHaveInlineBody` check. Now they do, which causes the ICE.

**Comment by mdempsky** [comment]
> @mdempsky seems that we should relax the check in bodyReaderFor to assert only in case of local functions?

I think it would be a reasonable short-term solution to exempt the synthetic hash and eq functions, but I wouldn't want to more broadly relax that assert. The inliner is able to gracefully fallback when an inline body is missing, but that's not really intended operation, and it degrades the quality of the inliner's cost heuristics.

I think a better solution would be to change inline.CanInline to recognize these functions, and mark them as non-inlineable.

Longer term, if there's a reason we *do* want to be able to inline these eq/hash functions, then maybe we need to integrate the code generation into the unified frontend's "synthetic" function mechanism.
