### ISSUE TITLE
x/pkgsite: internal folders/packages handled differently on top-level versus inside packages?

### ISSUE THREAD

**Issue by thediveo** [golang/go#58577]
Example project where I notice this (inconsistent?) behavior: https://pkg.go.dev/github.com/thediveo/lxkns#section-directories
- there is a top-level `internal` directories node rendered at the end of the directories list.
- there is no `cmd/internal` directory rendered for the package in the repository:  https://github.com/thediveo/lxkns/tree/master/cmd/internal

### What is your user agent?

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

### Screenshot

![image](https://user-images.githubusercontent.com/6920158/219663677-3102200f-e30d-4213-bff5-3fa8ccec6b93.png)

### What did you do?

Navigate to https://pkg.go.dev/github.com/thediveo/lxkns#section-directories

### What did you expect to see?

The `cmd` directory node to contain a sub node named `internal`.

### What did you see instead?

No such sub node named `internal` inside `cmd`, while there correctly is a top-level `internal` node.

**Comment by findleyr** [comment]
This appears to be only a property of the nav. The directory is there:
https://pkg.go.dev/github.com/thediveo/lxkns@v0.26.1/cmd/internal

**Comment by jamalc** [comment]
This is working as intended ([CL 297109](http://go.dev/cl/297109)), but I agree it does seem inconsistent. Given https://github.com/golang/go/issues/44356#issuecomment-786280831, maybe what we really want is to hide internal packages in the standard library but not third party modules.

**Comment by jamalc** [comment]
Any thoughts on a toggle for internal directory visibility?
![Screen Recording 2023-03-14 at 1 39 00 PM](https://user-images.githubusercontent.com/18269441/225092310-19891299-4062-4dc5-909e-8ebaa6047d2a.gif)

**Comment by findleyr** [comment]
I like the toggle idea.

If I'm browsing my own code, I want to see internal. If I'm browsing other people's code, I don't want to see internal. Based on this heuristic, perhaps we should make it the default to show internal packages for cmd/pkgsite.

**Comment by thediveo** [comment]
Thank you very much!
