### ISSUE TITLE
encoding/xml: unmarshal fails for numeric types if field empty

### ISSUE THREAD

**Issue by eaigner** [golang/go#5857]
<pre>When a XML tag contains an empty string, unmarshalling fails with

    strconv.ParseInt: parsing &quot;&quot;: invalid syntax

A more sensible default would be to just omit this field if the value cannot be parsed
(is the zero value).</pre>

**Comment by ivashyst** [comment]
This has been fixed by [CL 38386](https://go-review.googlesource.com/#/c/go/+/38386/).

**Comment by bradfitz** [comment]
@ivashyst, thanks.
