### ISSUE TITLE
x/build/cmd/release: Go installer failing on macos ventura 

### ISSUE THREAD

**Issue by Fomoukev** [golang/go#58585]
Version :  go1.20.1 , 

impossible for me to install Go on my computer, each time this message appears.

<img width="638" alt="Capture d’écran 2023-02-18 à 02 25 23" src="https://user-images.githubusercontent.com/106202608/219825398-4e7567b7-1b46-4bc6-af4c-4847d9be28ef.png">

**Comment by thanm** [comment]
Thanks for the report. 

Without more detail on what's happening here, I am not sure there is much that we can do to help.  If you could please post more details on your system (specific version of Ventura) and the exact link that you used to download the go installer, that would be helpful.

@golang/release

**Comment by nikoloza** [comment]
same issue on `MacOS Ventura 13.3.1 (a) (22E772610a)`

instralling
```
Apple macOS (x86-64)
macOS 10.13 or later, Intel 64-bit processor
```

**Comment by nikoloza** [comment]
works with brew

`brew install golang`
