### ISSUE TITLE
cmd/compile: bits.Len of constant not constant-folded

### ISSUE THREAD

**Issue by greatroar** [golang/go#58588]
### What version of Go are you using (`go version`)?

<pre>
$ gotip version
go version devel go1.21-169203f3ee Sat Feb 18 05:22:26 2023 +0000 linux/amd64
</pre>

### What did you do?

```
b >>= 8 - bits.Len(100)
```

### What did you expect to see?

A single shift instruction after constant folding.

### What did you see instead?

With GOARCH=amd64, GOAMD64=v2:

```
MOVL    $100, DX
BSRQ    DX, CX
MOVQ    $-1, DX
CMOVQEQ DX, CX
ADDQ    $-7, CX
NEGQ    CX
NOP
TESTQ   CX, CX
JLT     49
SHRB    CL, AL
CMPQ    CX, $8
SBBL    DX, DX
ANDL    DX, AX
// ...
CALL    runtime.panicshift(SB)
XCHGL   AX, AX
```

Adding a uint cast gets rid of the panicshift call, but still produces more than a dozen instructions.

GOAMD64=v3 produces shorter, but still suboptimal code.

Interestingly, GOARCH=386 does trigger constant folding, but still gets a useless check for 1 < 0:

```
MOVL    $1, AX
TESTL   AX, AX
JLT     40
MOVBLZX command-line-arguments.b+4(SP), AX
SHRB    $1, AX
// ...
CALL    runtime.panicshift(SB)
```

**Comment by renthraysk** [comment]
Pretty sure this has come up before? 

#28172

**Comment by greatroar** [comment]
Oh, I thought that bits.Len was supposed to be constant-folded based on the 386 behavior and amd64 was just broken. Closing as duplicate.
