### ISSUE TITLE
x/tools/gopls/internal/lsp/protocol: use AnnotatedTextEdit for TextDocumentEdit.Edits

### ISSUE THREAD

**Issue by hyangah** [golang/go#58583]
In 3.16, LSP introduced support for [`AnnotatedTextEdit`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocumentEdit) that allows annotations to a text edit and
supports UX that optionally asks user for confirmation before applying the change.

`TextDocumentEdit.Edits` is defined an array of `TextEdit | AnnotatedTextEdit` according to the spec,
but Gopls is currently accepting only `TextEdit` type.  It would be nice if gopls uses AnnotatedTextEdit instead of TextEdit
so we can experiment and start developing features with the AnnotatedTextEdit.

Given that `AnnotatedTextEdit` is a simple extension of `TextEdit` with one extra field (`annotationId`),
I think we can consider to replace all references of TextEdit in gopls with [AnnotatedTextEdit](https://cs.opensource.google/go/x/tools/+/gopls/v0.11.0:gopls/internal/lsp/protocol/tsprotocol.go;l=18)  while marking the annotatedId field omitempty.

Alternatively, I saw some internal non-TS/JS LSP implementations work around this OR type issue by a type corresponding to TextEdit

 ```
 type TextEdit struct {
   Range Range `json:"range"`
   NewText string `json:"newText"`
   AnnotationID ChangeAnnotationIdentifier `json:"annotationId,omitempty"`
 }
 ```  
 
 cc @pjweinb

**Comment by pjweinb** [comment]
The general replacement idea doesn't work, alas. Several of the RPCs use
TextEdits, not AnnotatedTextEdits. But conforming with the specification
ought to be possible. What features would that enable?

**Comment by hyangah** [comment]
You are right that the general replacement doesn't work. 
As the LSP maintainer pointed out (https://github.com/microsoft/language-server-protocol/issues/998#issuecomment-728765631) `AnnotatedTextEdit` is applicable only in a certain context (i.e. workspace edit)
and for completion items or formatting this may not make much sense.
 
This unlocks more advanced workspace edits shown in 
https://github.com/microsoft/vscode/issues/77728#issuecomment-573559307

  - users can see the diffs when involving many file changes, 
  - users can select individual changes per file
  - editor can group text edits based on the concise annotation
  
I think this will help us enhance gopls's workspace edit feature - various renaming that results in multiple file changes/moves.

**Comment by findleyr** [comment]
Per chat -- this was done in https://go.dev/cl/547295
