### ISSUE TITLE
cmd/go:  go install fails with malformed file path ("*" in png file path)

### ISSUE THREAD

**Issue by InfoLibre** [golang/go#58595]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

?

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/david/.cache/go-build"
GOENV="/home/david/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/david/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/david/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.18"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.18/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2800159434=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

$ go install framagit.org/InfoLibre/rapido@latest

It should download all the module package.

### What did you see instead?

Nothing is downloaded and there's an error message because one of the file in the package contains * character: https://framagit.org/InfoLibre/rapido/-/blob/master/docs/diaspora*.png

![Capture d’écran du 2023-02-19 12-13-05](https://user-images.githubusercontent.com/3955499/219944715-8de95a7f-71b3-4c28-9a86-f041835e2d56.png)

**Comment by AlexanderYastrebov** [comment]
Looks similar to https://github.com/golang/go/issues/44776

**Comment by thanm** [comment]
@golang/tools-team 

I can reproduce this on tip.

**Comment by bcmills** [comment]
The error is intentional, and the error message seems to be accurate.

You can't create a Go module containing a file with that name because it would be impossible to extract that module on Windows (https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions), and Go modules are intended to be downloadable on all platforms that Go supports.

**Comment by InfoLibre** [comment]
F* Windows!

**Comment by adonovan** [comment]
> F* Windows!
Perhaps you are looking for https://fsharp.org/use/windows/.

**Comment by InfoLibre** [comment]
:rofl:
