### ISSUE TITLE
doc: provide docs in some downloadable format

### ISSUE THREAD

**Issue by gopherbot** [golang/go#5859]
by **feedback.test.account**:

<pre><a href="https://feedback.corp.google.com/#/Report/990904700">https://feedback.corp.google.com/#/Report/990904700</a>

Description:
No problem. Just wondering if the documentation could be posted in PDF format so I could
download it and read it on my eReader.

UI language: en
Detected language: en</pre>

**Comment by ALTree** [comment]
Pretty much a dup of #2381 (x/tools/cmd/godoc: generate static docs), closing.
