### ISSUE TITLE
affected/package: 

### ISSUE THREAD

**Issue by TDnorthgarden** [golang/go#58593]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.3 linux/arm64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/golang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_arm64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build821360819=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Do nothing, just run dockerd 18.09.0

### What did you expect to see?

Keep dockerd running

### What did you see instead?

dockerd[4603]: runtime: bad span s.state=3 s.sweepgen=1115595 sweepgen=1115596
 dockerd[4603]: fatal error: non in-use span in unswept list
 dockerd[4603]: goroutine 3 [running]:
 dockerd[4603]: runtime.throw(0xaaae76402f2e, 0x1f)
 dockerd[4603]: #011/usr/lib/golang/src/runtime/panic.go:774 +0x54 fp=0x4000105730 sp=0x4000105700 pc=0xaaae7503c404
 dockerd[4603]: runtime.sweepone(0xaaae7711ad20)
 dockerd[4603]: #011/usr/lib/golang/src/runtime/mgcsweep.go:123 +0x49c fp=0x40001057a0 sp=0x4000105730 pc=0xaaae7502fddc
 dockerd[4603]: runtime.bgsweep(0x400006e000)
 dockerd[4603]: #011/usr/lib/golang/src/runtime/mgcsweep.go:73 +0xd8 fp=0x40001057d0 sp=0x40001057a0 pc=0xaaae7502f868
 dockerd[4603]: runtime.goexit()
 dockerd[4603]: #011/usr/lib/golang/src/runtime/asm_arm64.s:1128 +0x4 fp=0x40001057d0 sp=0x40001057d0 pc=0xaaae7506b074
 dockerd[4603]: created by runtime.gcenable
 dockerd[4603]: #011/usr/lib/golang/src/runtime/mgc.go:210 +0x54
 dockerd[4603]: goroutine 1 [chan receive, 52422 minutes]:
 dockerd[4603]: runtime.gopark(0xaaae7711ae28, 0x4000f0c958, 0x4000e7170e, 0x3)
 dockerd[4603]: #011/usr/lib/golang/src/runtime/proc.go:304 +0xd0 fp=0x4000ef98a0 sp=0x4000ef9880 pc=0xaaae7503e0b0
 dockerd[4603]: runtime.goparkunlock(...)
 dockerd[4603]: #011/usr/lib/golang/src/runtime/proc.go:310
 dockerd[4603]: runtime.chanrecv(0x4000f0c900, 0x4000e75bc8, 0x4000000101, 0xaaae763bdaec)
 dockerd[4603]: #011/usr/lib/golang/src/runtime/chan.go:524 +0x25c fp=0x4000ef9930 sp=0x4000ef98a0 pc=0xaaae75013bfc
 dockerd[4603]: runtime.chanrecv1(0x4000f0c900, 0x4000e75bc8)
 dockerd[4603]: #011/usr/lib/golang/src/runtime/chan.go:406 +0x28 fp=0x4000ef9960 sp=0x4000ef9930 pc=0xaaae75013948
 dockerd[4603]: main.(*DaemonCli).start(0x4000857890, 0x40008555c0, 0x0, 0x0)
 dockerd[4603]: #011/builddir/build/BUILD/docker-engine/components/engine/.gopath/src/github.com/docker/docker/cmd/dockerd/daemon.go:290 +0xa8c fp=0x4000ef9cd0 sp=0x4000ef9960 pc=0xaaae763bdb0c
 dockerd[4603]: main.runDaemon(...)
 dockerd[4603]: #011/builddir/build/BUILD/docker-engine/components/engine/.gopath/src/github.com/docker/docker/cmd/dockerd/docker_unix.go:7
 dockerd[4603]: main.newDaemonCommand.func1(0x4000815b80, 0x40007ee2d0, 0x0, 0xf, 0x0, 0x0)
 dockerd[4603]: #011/builddir/build/BUILD/docker-engine/components/engine/.gopath/src/github.com/docker/docker/cmd/dockerd/docker.go:29 +0x78 fp=0x4000ef9d10 sp=0x4000ef9cd0 pc=0xaaae763c3308
 dockerd[4603]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0x4000815b80, 0x4000162010, 0xf, 0xf, 0x4000815b80, 0x4000162010)
 dockerd[4603]: #011/builddir/build/BUILD/docker-engine/components/engine/.gopath/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:762 +0x314 fp=0x4000ef9df0 sp=0x4000ef9d10 pc=0xaaae763b2a24
 dockerd[4603]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x4000815b80, 0xaaae77159540, 0x400015e010, 0x10)
 dockerd[4603]: #011/builddir/build/BUILD/docker-engine/components/engine/.gopath/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:852 +0x214 fp=0x4000ef9ec0 sp=0x4000ef9df0 pc=0xaaae763b31b4
 dockerd[4603]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(...)
 dockerd[4603]: #011/builddir/build/BUILD/docker-engine/components/engine/.gopath/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:800
 dockerd[4603]: main.main()
 dockerd[4603]: #011/builddir/build/BUILD/docker-engine/components/engine/.gopath/src/github.com/docker/docker/cmd/dockerd/docker.go:70 +0xfc fp=0x4000ef9f50 sp=0x4000ef9ec0 pc=0xaaae763c223c
 dockerd[4603]: runtime.main()
 dockerd[4603]: #011/usr/lib/golang/src/runtime/proc.go:203 +0x22c fp=0x4000ef9fd0 sp=0x4000ef9f50 pc=0xaaae7503dcac
 dockerd[4603]: runtime.goexit()
 dockerd[4603]: #011/usr/lib/golang/src/runtime/asm_arm64.s:1128 +0x4 fp=0x4000ef9fd0 sp=0x4000ef9fd0 pc=0xaaae7506b074
 dockerd[4603]: goroutine 2 [force gc (idle), 52422 minutes]:
 dockerd[4603]: runtime.gopark(0xaaae7711ae28, 0xaaae7821e7f0, 0x1411, 0x1)
 dockerd[4603]: #011/usr/lib/golang/src/runtime/proc.go:304 +0xd0 fp=0x4000104fa0 sp=0x4000104f80 pc=0xaaae7503e0b0
 dockerd[4603]: runtime.goparkunlock(...)
 dockerd[4603]: #011/usr/lib/golang/src/runtime/proc.go:310
 dockerd[4603]: runtime.forcegchelper()
 dockerd[4603]: #011/usr/lib/golang/src/runtime/proc.go:253 +0xb8 fp=0x4000104fd0 sp=0x4000104fa0 pc=0xaaae7503df68
 dockerd[4603]: runtime.goexit()
 dockerd[4603]: #011/usr/lib/golang/src/runtime/asm_arm64.s:1128 +0x4 fp=0x4000104fd0 sp=0x4000104fd0 pc=0xaaae7506b074
 dockerd[4603]: created by runtime.init.4
 dockerd[4603]: #011/usr/lib/golang/src/runtime/proc.go:242 +0x30
 dockerd[4603]: goroutine 4 [runnable]:
 dockerd[4603]: runtime.gopark(0xaaae7711ae28, 0xaaae7821fe00, 0x140d, 0x1)
 dockerd[4603]: #011/usr/lib/golang/src/runtime/proc.go:304 +0xd0 fp=0x4000105f30 sp=0x4000105f10 pc=0xaaae7503e0b0
 dockerd[4603]: runtime.goparkunlock(...)
 dockerd[4603]: #011/usr/lib/golang/src/runtime/proc.go:310
 dockerd[4603]: runtime.bgscavenge(0x400006e000)
 dockerd[4603]: #011/usr/lib/golang/src/runtime/mgcscavenge.go:374 +0x3b0 fp=0x4000105fd0 sp=0x4000105f30 pc=0xaaae7502f220
 dockerd[4603]: runtime.goexit()
 dockerd[4603]: #011/usr/lib/golang/src/runtime/asm_arm64.s:1128 +0x4 fp=0x4000105fd0 sp=0x4000105fd0 pc=0xaaae7506b074
 dockerd[4603]: created by runtime.gcenable
 dockerd[4603]: #011/usr/lib/golang/src/runtime/mgc.go:211 +0x74

**Comment by TDnorthgarden** [comment]
same problem  occur in https://github.com/golang/go/issues/50727

**Comment by mdlayher** [comment]
Go 1.13 is several years out of support. Closing.
