### ISSUE TITLE
go build: internal compiler error

### ISSUE THREAD

**Issue by catenacyber** [golang/go#58607]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/root/.go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/root/.go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/src/ngolo-fuzzing/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2481516251=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Build ngolo-fuzzing on oss-fuzz cf https://oss-fuzz-build-logs.storage.googleapis.com/log-4dc63c26-831e-4307-ba2b-de60a1fc0a35.txt

### What did you expect to see?

Some success and failures due to my code

### What did you see instead?

`<unknown line number>: internal compiler error: have package "main" (0xc0000c6320), want package "github.com/catenacyber/ngolo-fuzzing" (0xc00049d3b0)`

```
goroutine 1 [running]:
runtime/debug.Stack()
	/src/goroot/src/runtime/debug/stack.go:24 +0x5e
cmd/compile/internal/base.FatalfAt({0x1685a1?, 0xc0?}, {0xd52d63, 0x2a}, {0xc00014e3e0, 0x4, 0x4})
	/src/goroot/src/cmd/compile/internal/base/print.go:227 +0x1d7
cmd/compile/internal/base.Fatalf(...)
	/src/goroot/src/cmd/compile/internal/base/print.go:196
cmd/compile/internal/base.Assertf(...)
	/src/goroot/src/cmd/compile/internal/base/print.go:246
cmd/compile/internal/noder.readPackage(0xc0000e6380, 0xc00009df90, 0x0)
	/src/goroot/src/cmd/compile/internal/noder/unified.go:296 +0x225
cmd/compile/internal/noder.readImportFile({0xc0001685a1?, 0xcbe420?}, 0xc00036e0c0, 0xc000022201?, 0xc00009e510)
	/src/goroot/src/cmd/compile/internal/noder/import.go:240 +0x5a7
cmd/compile/internal/noder.(*gcimports).ImportFrom(0xcb5440?, {0xc0001685a1?, 0xc0000401b0?}, {0x10?, 0xc0001685a1?}, 0x0?)
	/src/goroot/src/cmd/compile/internal/noder/import.go:45 +0x34
cmd/compile/internal/types2.(*Checker).importPackage(0xc0000ae000, {0xc000121d70, 0xe, 0x9}, {0xc0001685a1, 0x24}, {0xc000168577, 0x12})
	/src/goroot/src/cmd/compile/internal/types2/resolver.go:146 +0x195
cmd/compile/internal/types2.(*Checker).collectObjects(0xc0000ae000)
	/src/goroot/src/cmd/compile/internal/types2/resolver.go:254 +0x1025
cmd/compile/internal/types2.(*Checker).checkFiles(0xc0000ae000, {0xc0000100a8, 0x3, 0x3})
	/src/goroot/src/cmd/compile/internal/types2/check.go:323 +0x127
cmd/compile/internal/types2.(*Checker).Files(...)
	/src/goroot/src/cmd/compile/internal/types2/check.go:301
cmd/compile/internal/types2.(*Config).Check(0xd3851d?, {0x7ffcf69cd136?, 0x134c9a0?}, {0xc0000100a8, 0x3, 0x3}, 0x9?)
	/src/goroot/src/cmd/compile/internal/types2/api.go:429 +0x66
cmd/compile/internal/noder.checkFiles({0x0, {0x0, 0x0}}, {0xc0003f59f8, 0x3, 0x9?})
	/src/goroot/src/cmd/compile/internal/noder/irgen.go:66 +0x477
cmd/compile/internal/noder.writePkgStub({0x0?, {0x0?, 0x0?}}, {0xc0003f59f8, 0x3, 0x3})
	/src/goroot/src/cmd/compile/internal/noder/unified.go:206 +0x6a
cmd/compile/internal/noder.unified({0x0?, {0x0?, 0x0?}}, {0xc0003f59f8?, 0xc854e0?, 0x13da420?})
	/src/goroot/src/cmd/compile/internal/noder/unified.go:75 +0x96
cmd/compile/internal/noder.LoadPackage({0xc000134120, 0x3, 0x4})
	/src/goroot/src/cmd/compile/internal/noder/noder.go:76 +0x45c
cmd/compile/internal/gc.Main(0xd65738)
	/src/goroot/src/cmd/compile/internal/gc/main.go:197 +0xc4c
main.main()
	/src/goroot/src/cmd/compile/main.go:57 +0xf9
```

**Comment by cuonglm** [comment]
Duplicated of https://github.com/golang/go/issues/54542
