### ISSUE TITLE
cmd/link: linker fails on linux/amd64 when gcc's lto options are used

### ISSUE THREAD

**Issue by jcajka** [golang/go#58619]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.21-7f59bea53c Tue Feb 21 05:09:21 2023 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes, seems to be reproducible at least as far back as go1.18

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel go1.21-7f59bea53c Tue Feb 21 05:09:21 2023 +0000"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/loki/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3131861800=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

This is with gcc-13.0.1, binutils-2.40 and glibc-2.37

### What did you do?

git clone https://github.com/grafana/loki
cd loki
export CGO_CFLAGS='-O2 -flto=auto -ffat-lto-objects'
go build -o logcli ./cmd/logcli

### What did you expect to see?
Build finishing successfully or more clear error message being displayed.

### What did you see instead?
<pre>
go build -o logcli ./cmd/logcli
# github.com/grafana/loki/cmd/logcli
net(.text): relocation target malloc not defined
net(.text): relocation target __errno_location not defined
net(.text): relocation target getnameinfo not defined
net(.text): relocation target __errno_location not defined
net(.text): relocation target getaddrinfo not defined
net(.text): relocation target free not defined
net(.text): relocation target freeaddrinfo not defined
net(.text): relocation target gai_strerror not defined
net(.text): relocation target __errno_location not defined
net(.text): relocation target res_search not defined
runtime/cgo(.text): relocation target stderr not defined
runtime/cgo(.text): relocation target fwrite not defined
runtime/cgo(.text): relocation target vfprintf not defined
runtime/cgo(.text): relocation target fputc not defined
runtime/cgo(.text): relocation target abort not defined
runtime/cgo(.text): relocation target pthread_mutex_lock not defined
runtime/cgo(.text): relocation target pthread_cond_wait not defined
runtime/cgo(.text): relocation target pthread_mutex_unlock not defined
runtime/cgo(.text): relocation target pthread_cond_broadcast not defined
runtime/cgo(.text): relocation target pthread_create not defined
runtime/cgo(.text): relocation target nanosleep not defined
/go/pkg/tool/linux_amd64/link: too many errors
</pre>

**Comment by thanm** [comment]
Similar to #58620, we're doing CGO internal linking (due to use of CGO in "net" and related packages), and the linker's host object loader is getting confused by the non-standard objects.

**Comment by thanm** [comment]
@gopherbot please open backport issues
