### ISSUE TITLE
Can't install gomobile inside Docker image

### ISSUE THREAD

**Issue by GTP95** [golang/go#58617]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>
go version go1.10.4 linux/amd64
### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/lib/go-1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build556453211=/tmp/go-build -gno-record-gcc-switches"
### What did you do?
Here's my Dockerfile that you can use to reproduce the issue:
```
FROM androidsdk/android-31
WORKDIR /root
RUN sdkmanager --update
RUN sdkmanager --install "build-tools;33.0.2" "cmdline-tools;latest" "ndk;21.4.7075529" "platform-tools" "cmake;3.6.4111459"
RUN apt-get update && apt-get -y install zip libglu1-mesa chromium-browser clang cmake ninja-build pkg-config libgtk-3-dev golang-go
RUN wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.7.3-stable.tar.xz
RUN tar xf flutter_linux_3.7.3-stable.tar.xz
RUN echo 'export CHROME_EXECUTABLE="/usr/bin/chromium-browser"' >> .bashrc
RUN echo 'export PATH="$PATH:`pwd`/flutter/bin"' >> .bashrc
RUN go install golang.org/x/mobile/cmd/gomobile@latest
RUN git clone --recursive https://github.com/privacybydesign/irmamobile.git
CMD bash
```

### What did you expect to see?
The Docker instruction `RUN go install golang.org/x/mobile/cmd/gomobile@latest` installs gomobile.

### What did you see instead?
gomobile fails installation with the following error:
```
can't load package: package golang.org/x/mobile/cmd/gomobile@latest: cannot find package "golang.org/x/mobile/cmd/gomobile@latest" in any of:
	/usr/lib/go-1.10/src/golang.org/x/mobile/cmd/gomobile@latest (from $GOROOT)
	/root/go/src/golang.org/x/mobile/cmd/gomobile@latest (from $GOPATH)
```
Similar to issue #34676.

**Comment by seankhliao** [comment]
1.10 isn't a supported version
