### ISSUE TITLE
link: link failed runtime.test in race mode

### ISSUE THREAD

**Issue by peter-xiao** [golang/go#58616]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
<pre>
diff --git a/src/runtime/rand_test.go b/src/runtime/rand_test.go
index 92d07ebada..ca6ab0ba2c 100644
--- a/src/runtime/rand_test.go
+++ b/src/runtime/rand_test.go
@@ -10,6 +10,10 @@ import (
        "testing"
 )
 
+func CallFastrand() {
+       Fastrand()
+}
+
 func BenchmarkFastrand(b *testing.B) {
        b.RunParallel(func(pb *testing.PB) {
                for pb.Next() {
</pre> 
```
export GOEXPERIMENT=nounified && go test -race runtime -v  
```

### What did you expect to see?
```
ok  	runtime	148.753s
```

### What did you see instead?
```
# runtime.test
panic: runtime error: index out of range [1696] with length 244

goroutine 1 [running]:
cmd/link/internal/loader.(*Loader).resolve(0xc?, 0xc00014cc80?, {0x4300?, 0xc0?})
	/Users/bytedance/go_google/src/cmd/link/internal/loader/loader.go:654 +0x1c5
cmd/link/internal/loader.Reloc.Sym({0x2a92f348?, 0xc00014cc80?, 0xc000004300?})
	/Users/bytedance/go_google/src/cmd/link/internal/loader/loader.go:60 +0x35
cmd/link/internal/loader.(*Loader).UndefinedRelocTargets(0xc000004300, 0x1)
	/Users/bytedance/go_google/src/cmd/link/internal/loader/loader.go:2408 +0x1f9
cmd/link/internal/ld.(*Link).loadlib(0xc000152000)
	/Users/bytedance/go_google/src/cmd/link/internal/ld/lib.go:618 +0x5fc
cmd/link/internal/ld.Main(_, {0x20, 0x20, 0x1, 0x7, 0x10, 0x0, {0x0, 0x0}, {0x12922ba, ...}, ...})
	/Users/bytedance/go_google/src/cmd/link/internal/ld/main.go:268 +0xecb
main.main()
	/Users/bytedance/go_google/src/cmd/link/main.go:72 +0xedb
FAIL	runtime [build failed]
FAIL
```

**Comment by thanm** [comment]
@thanm @cherrymui

**Comment by peter-xiao** [comment]
I found code of exporter had been deleted in mr https://go-review.googlesource.com/c/go/+/458620, and this issue doesn't reproduce again after this commit. Maybe there is no need to bugfix this issue.

**Comment by cherrymui** [comment]
Yeah, if this only fails with `GOEXPERIMENT=nounified`, we will not fix it as that mode is gone. Feel free to reopen if you can reproduce without the GOEXPERIMENT. Thanks.
