### ISSUE TITLE
affected/package:  gomobile. Can't init gomobile

### ISSUE THREAD

**Issue by GTP95** [golang/go#58618]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.1 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/giacomo/.cache/go-build"
GOENV="/home/giacomo/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/giacomo/Sviluppo/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/giacomo/Sviluppo/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2344969156=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I installed gomobile with `go install golang.org/x/mobile/cmd/gomobile@latest` and then tried to initialize it with `gomobile init`

### What did you expect to see?

gomobile gets initialized.

### What did you see instead?
Bash doesn't find the `gomobile` command:

```
$ gomobile init
bash: gomobile: comando non trovato
```
The executable `gomobile` seems to be in `/home/giacomo/Sviluppo/go/pkg/mod/golang.org/x/mobile@v0.0.0-20221110043201-43a038452099/cmd/gomobile`, which is not in my path. Am I supposed to add this manually to my path? If yes, which exact directory should I add? Here's what my path looks like now:

```
$ echo $PATH
/home/giacomo/Android/Sdk/platform-tools:/home/giacomo/.local/bin:/home/giacomo/Sviluppo/android_home/Tools/android-sdk/cmdline-tools/tools/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/giacomo/flutter/bin
```

**Comment by GTP95** [comment]
I just checked to see if I could run gomobile by specifying the full path, and `/home/giacomo/Sviluppo/go/pkg/mod/golang.org/x/mobile@v0.0.0-20221110043201-43a038452099/cmd/gomobile` is actually a directory, so it seems that after installing gomobile, I don't have the `gomobile` executable on my system. This is what I have inside that directory:

```
$ ls /home/giacomo/Sviluppo/go/pkg/mod/golang.org/x/mobile@v0.0.0-20221110043201-43a038452099/cmd/gomobile
bind_androidapp.go  bind_iosapp.go  build_androidapp.go  build_darwin_test.go  build_test.go  cert_test.go  dex.go  env.go       gendex.go  init_test.go  main.go      strings_flag.go  version.go  writer_test.go
bind.go             bind_test.go    build_apple.go       build.go              cert.go        clean.go      doc.go  env_test.go  init.go    install.go    manifest.go  tools.go         writer.go
```

**Comment by seankhliao** [comment]
you're expected to add GOBIN / GOPATH/bin to your PATH.
