### ISSUE TITLE
define IOV_MAX

### ISSUE THREAD

**Issue by pascaldekloe** [golang/go#58623]
Use of iovec(2) in the core library is left with a TODO.

> // TODO: read from sysconf(_SC_IOV_MAX)? The Linux default is
> // 1024 and this seems conservative enough for now. Darwin's
> // UIO_MAXIOV also seems to be 1024.
> — https://github.com/golang/go/blob/master/src/internal/poll/writev.go#L29

POSIX seems clear on `IOV_MAX` in <limits.h>.

> Maximum number of iovec structures that one process has available for use with [readv()](https://pubs.opengroup.org/onlinepubs/009695399/functions/readv.html) or [writev()](https://pubs.opengroup.org/onlinepubs/009695399/functions/writev.html).
> Minimum Acceptable Value: `_XOPEN_IOV_MAX`
> — The Open Group Base Specifications Issue 6, IEEE Std 1003.1, 2004 Edition

The gains of writev(2) on regular files are also significant. I found myself better of with writev(2) than with `bufio.Writer` in many perfomance-intense applications.

**Comment by pascaldekloe** [comment]
Solaris seems to comply.

> The iovcnt buffer is valid if greater than 0 and less than or equal to {IOV_MAX}.
> — write(2), SunOS 5.11, 2008

**Comment by pascaldekloe** [comment]
AIX seems to comply.

> iovcnt is valid if greater than 0 and less than or equal to {IOV_MAX}
> — https://www.ibm.com/docs/en/aix/7.3?topic=w-write-writex-write64x-writev-writevx-ewrite-ewritev-pwrite-pwritev-subroutine

The documentation of z/OS [mentions](https://www.ibm.com/docs/en/zos/2.5.0?topic=functions-writev-write-data-file-socket-from-array) “An incorrect value for iocvnt”, yet it leaves out what the correct value is. 😏

**Comment by ianlancetaylor** [comment]
The fix for this is not to define `IOV_MAX` in syscall, but to use `sysconf` to retrieve the actual value.

That said, are you using Solaris or AIX?  If not, do you have real code that uses more than 1024 iovecs?

**Comment by pascaldekloe** [comment]
No @ianlancetaylor, This issue is about exposing IOV_MAX. Using in internal/poll is just a bonus cleanup.

I used writev(2) with more than 1024 vectors [today](https://github.com/pascaldekloe/seeq/blob/132c386984a931871f60cd3cd099e1fd0ca0f64f/stream/simple.go#L57). No idea which operating systems this code will run on.

**Comment by pascaldekloe** [comment]
Doing a zero-copy write of records consisting of a [4]byte, a string and a []byte is neat. 😍 The net.Buffers only works on network devices. Requests for something similar on regular files stranded on vague reasons. Ideally we'd have the following. Until then a simple `IOV_MAX` will do.

```go
type Bytes interface {
        ~[]byte|~string
}

func WriteAll(*os.File, []Bytes) (int64, error)
```

**Comment by pascaldekloe** [comment]
Darwin [complies](https://opensource.apple.com/source/Libc/Libc-1353.60.8/include/limits.h.auto.html) too.

Not sure what to make of the "help wanted" label @mknyszek. Do you mean you'd welcome a patch which includes IOV_MAX in `syscall/mkerrors.sh` somehow?

**Comment by mknyszek** [comment]
I think I originally left the "help wanted" tag based on your original post, which was about resolving a TODO in `internal/poll`, which during triage no one in the Go team planned to pick up for now. (I think that `internal/poll` might need its own call to `sysconf` to grab the value anyway; I don't remember off the top of my head if the Go standard library vendors x/sys.)

However rereading this issue, I think I'm not clear on what this issue is about.

If you're suggesting adding `IOV_MAX` as a constant or something to the `syscall`, that's not possible today since the `syscall` package is basically frozen (as @ianlancetaylor alluded to). New support for platform-specific interfaces should go into `golang.org/x/sys`. But then it also sounds like defining a constant is not the right approach either, based on the TODO and Ian's last comment? (Disclaimer: I'm not very familiar with the specifics here.)

**Comment by ianlancetaylor** [comment]
If the goal is just to expose `IOV_MAX`, that should be done somewhere in the golang.org/x/sys/unix package.  It should not be done in internal/poll, and doing it there wouldn't help anyhow.

So this issue title and description are confusing.  Can you be more precise as to what change you want?  Thanks.

**Comment by pascaldekloe** [comment]
Yes, all what is needed is IOV_MAX exposure. I just thought of syscall to be the right place. If that is frozen, then what would be the right place? No internal please, as that limits use to the core library.

**Comment by ianlancetaylor** [comment]
The right place is the golang.org/x/sys/unix package.
