### ISSUE TITLE
x/mobile: gomobile cannot add extra so library

### ISSUE THREAD

**Issue by ImagineYao** [golang/go#58621]
My go project use a so library, such as _example.so_. After I using gomobile to make an aar and build it in android apk, I get the error that couldn't find the library _example.so_. There is only _ibgojin.so_ in the aar, _example.so_ is missing.
<img width="773" alt="截屏2023-02-21 23 17 36" src="https://user-images.githubusercontent.com/38421751/220385133-3d35e50b-c8ef-4c81-8fa5-59aee96b7ecc.png">
<img width="348" alt="截屏2023-02-21 23 26 29" src="https://user-images.githubusercontent.com/38421751/220386995-c2482c5c-1c6b-40a6-8630-38d4393e96d3.png">

Following is my build command.
`CGO_LDFLAGS="-L$(libs_dir)/android_arm64" CC="$(android_ndk_bin)/aarch64-linux-android30-clang" gomobile bind -ldflags "-s -w" -v -target=android/arm64`

**Comment by bcmills** [comment]
(CC @golang/android @hyangah)
