### ISSUE TITLE
cmd/cgo: "initializer element is not constant" for #define structs

### ISSUE THREAD

**Issue by mori-nobuteru** [golang/go#58638]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ubuntu/.cache/go-build"
GOENV="/home/ubuntu/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/ubuntu/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ubuntu/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/ubuntu/ctest/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build85441351=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I'm trying to link against the quickjs library. The library builds successfully on my machine, but my Go code fails to compile once the header file for this library is included. I've created a minimal reproduction here that requires only a header file to illustrate the issue:

```
// ctest.h
#include <stdint.h>

enum {
    JS_TAG_UNDEFINED   = 3,
};

typedef union JSValueUnion {
    int32_t int32;
    double float64;
    void *ptr;
} JSValueUnion;

typedef struct JSValue {
    JSValueUnion u;
    int64_t tag;
} JSValue;

#define JS_MKVAL(tag, val) (JSValue){ (JSValueUnion){ .int32 = val }, tag }
#define JS_UNDEFINED JS_MKVAL(JS_TAG_UNDEFINED, 0)
```

```
// ctest.go
package ctest

/*
#include "ctest.h"
*/
import "C"
import "fmt"

func MyTest() {
	var s C.JSValue = C.JS_UNDEFINED
	fmt.Println(s)
}
```

The code above comes from the quick js library. The goal is to use a macro to define that initializes a struct.

### What did you expect to see?
I expected this code to compile on Linux, like it does on MacOS.

### What did you see instead?
```
In file included from ./ctest.go:4:
./ctest.h:18:37: error: initializer element is not constant
   18 | #define JS_MKVAL(tag, val) (JSValue){ (JSValueUnion){ .int32 = val }, tag }
      |                                     ^
./ctest.h:19:22: note: in expansion of macro 'JS_MKVAL'
   19 | #define JS_UNDEFINED JS_MKVAL(JS_TAG_UNDEFINED, 0)
      |                      ^~~~~~~~
cgo-dwarf-inference:2:12: note: in expansion of macro 'JS_UNDEFINED'
```

**Comment by mori-nobuteru** [comment]
I was able to get this to compile by using Clang (`go env -w CC="clang`), but it'd be nice for it to work out-of-the-box as well.

**Comment by thanm** [comment]
@golang/compiler

**Comment by ianlancetaylor** [comment]
This doesn't have anything to do with cgo or Go.  A pure C file

```C
#include "ctest.h"
JSValue x = JS_UNDEFINED;
```

will report the same error when using GCC.

**Comment by mori-nobuteru** [comment]
@ianlancetaylor The error you get when compiling your code is slightly different:

```
ctest.h:19:37: error: initializer element is not constant
   19 | #define JS_MKVAL(tag, val) (JSValue){ (JSValueUnion){ .int32 = val }, tag }
      |                                     ^
ctest.h:20:22: note: in expansion of macro ‘JS_MKVAL’
   20 | #define JS_UNDEFINED JS_MKVAL(JS_TAG_UNDEFINED, 0)
      |                      ^~~~~~~~
ctest.c:3:13: note: in expansion of macro ‘JS_UNDEFINED’
    3 | JSValue x = JS_UNDEFINED;
```

You'll notice your const assignment is actually part of the error. No where in my C example do I create a const assignment, so it's unclear where the error is coming from.

**Comment by ianlancetaylor** [comment]
The error string is coming from the cgo tool.  It's because the cgo tool itself needs to determine the type of the value.  It does by writing out

```C
__typeof__(JS_UNDEFINED) *__cgo__1;
```

It compiles that as C code, and looks at the DWARF debug info to determine type.  Unfortunately, that code doesn't compile when using GCC.

I think that to make this work with GCC you are going to write something like

```Go
/*
#include "ctest.h"

static JSValue undef() { return JS_UNDEFINED; }
*/
import "C"
import "fmt"

func MyTest() {
	var s C.JSValue = C.undef()
	fmt.Println(s)
}
```
