### ISSUE TITLE
cgo: regression: go command does not recompile changed packages

### ISSUE THREAD

**Issue by gucio321** [golang/go#58640]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes (just tested with 1.20.1)

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/me/.cache/go-build"
GOENV="/home/me/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/me/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/me/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build106840752=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Hi!
I've started working on a go project using CGO.
I've realised that changing C code does not trigger it re-building so that faulty code still seems to be compilable (but isn't in fact). Using `-a` compiler flag "fixes" the issue.
It is a regression from the previous version (go 1.19.*) sinc it worked fine there.

### What did you expect to see?

code should re-compile automatically if something within cgo code has changed

### What did you see instead?

it does not re-compile.

### how to reproduce

consider the following two files:
`main.go`:
```go
package main

/*
#include "./file.h"
*/
import "C"

func main() {
	C.foo()
}
```
and `file.h`
```h
#include <stdio.h>

void foo() {
        printf("hi!\n")
}
```
there is an intentionally-made mistake in `h` file - missing `;` at the end of `printf` line. Now take the following actions:
- try to compile main.go - it will fail
- add the missing `;` and try again - it will compile fine
- now remove `;` again and try to compile - it will work although it should fail now

**Comment by thanm** [comment]
@gucio321  you have this down as a regression, however when I try this with Go 1.19 I see the same behavior you are citing.   This is expected, since the Go tools don't do any sort of deep inspection of header files to see what they pull in (for this to happen, the Go tools would have to implement a complete C preprocessor).

**Comment by gucio321** [comment]
oh, very strange, let me downgrade go and test again

**Comment by gucio321** [comment]
oh, ok I see. So I'm closing this.

>  (for this to happen, the Go tools would have to implement a complete C preprocessor).
@thanm btw is there any discussion on such a feature?

**Comment by thanm** [comment]
>any discussion on such a feature?
Not that I am aware of.
