### ISSUE TITLE
crypto/elliptic: specific unreduced P-256 scalars produce incorrect results

### ISSUE THREAD

**Issue by rolandshoemaker** [golang/go#58647]
In particular (in psuedocode)

```
x = 48439561293906451759052585252797914202762949526041747995844080717082404635286
y = 36134250956749795798585127919587881956611106672985015071877198253568414405109

P256().ScalarMult(x, y, N) != P256().ScalarMult(x, y, N + 30)
```

Thanks to Guido Vranken for repoting this issue via the Ethereum Foundation bug
bounty program.

**Comment by FiloSottile** [comment]
We agreed with @rolandshoemaker that this can be fixed as PUBLIC since it only affects niche configurations, namely very specific direct uses of crypto/elliptic. We found no real world protocol that could be attacked due to this.

**Comment by FiloSottile** [comment]
@gopherbot please backport. CL 471255 is a security fix.

/cc @golang/security and @golang/release
