### ISSUE TITLE
x/pkgsite: package removal request for github.com/lobliveoaklabs/readme-api-go-client

### ISSUE THREAD

**Issue by joshbeard** [golang/go#58643]
### What is the path of the package that you would like to have removed?

 

/github.com/lobliveoaklabs/readme-api-go-client
 
### Are you the owner of this package?

Yes

 
### What is the reason that you could not retract this package instead?

We moved the module from the GitHub organization "lobliveoaklabs" to "liveoaklabs".

A new version was published under the new namespace and works as expected. The former organization/path is not valid.

**Comment by jamalc** [comment]
Done.
