### ISSUE TITLE
x/exp/slog: TextHandler panics on nil arg

### ISSUE THREAD

**Issue by suiriass** [golang/go#58652]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/shimingjun/Library/Caches/go-build"
GOENV="/Users/shimingjun/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE="xxxxxx"
GOMODCACHE="/Users/shimingjun/go/pkg/mod"
GONOPROXY="xxxxxx"
GONOSUMDB="xxxx"
GOOS="darwin"
GOPATH="/Users/shimingjun/go"
GOPRIVATE="xxxxxxx"
GOPROXY="xxxxxxx"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.19.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/5z/6g3r5wdj70d88pljjvlhk0f80000gn/T/go-build81508862=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

<pre>
import (
	"golang.org/x/exp/slog"
	"os"
	"testing"
)

func TestTextHandler(t *testing.T) {
	handler := slog.New(slog.NewJSONHandler(os.Stderr))
	var err error // err is nil
	handler.Info("json msg1", "key", "str", "err", err)
	handler.Info("json msg2", "key", "str", slog.Any("err", err))

	handler = slog.New(slog.NewTextHandler(os.Stderr))
	handler.Info("text msg1", "key", "str", "err", err)
	handler.Info("text msg2", "key", "str", slog.Any("err", err))
}

</pre>

### What did you expect to see?
When using attr to output nil, the text handler gets panic, while the json handler does not, expecting the correct null output

### What did you see instead?

=== RUN   TestTextHandler
{"time":"2023-02-23T10:51:38.906392+08:00","level":"INFO","msg":"json msg1","key":"str","err":null}
{"time":"2023-02-23T10:51:38.906612+08:00","level":"INFO","msg":"json msg2","key":"str","err":null}
--- FAIL: TestTextHandler (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x11539a0]

goroutine 4 [running]:
testing.tRunner.func1.2({0x11725e0, 0x12c28e0})
	/usr/local/go/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1399 +0x39f
panic({0x11725e0, 0x12c28e0})
	/usr/local/go/src/runtime/panic.go:884 +0x212
golang.org/x/exp/slog.byteSlice({0x0?, 0x0})
	/Users/gowork/gx/vendor/golang.org/x/exp/slog/text_handler.go:130 +0x80
golang.org/x/exp/slog.appendTextValue(0xc000135708, {0x5?, {0x0?, 0x0?}})
	/Users/gowork/gx/vendor/golang.org/x/exp/slog/text_handler.go:109 +0x305
golang.org/x/exp/slog.(*handleState).appendValue(0xc000135708, {0x1196f12?, {0x0?, 0x0?}})
	/Users/gowork/gx/vendor/golang.org/x/exp/slog/handler.go:532 +0x37
golang.org/x/exp/slog.(*handleState).appendAttr(0xc000135708, {{0x1196f12, 0x3}, {0x0, {0x0, 0x0}}})
	/Users/gowork/gx/vendor/golang.org/x/exp/slog/handler.go:468 +0x725
golang.org/x/exp/slog.(*handleState).appendNonBuiltIns.func1({{0x1196f12, 0x3}, {0x0, {0x0, 0x0}}})
	/Users/gowork/gx/vendor/golang.org/x/exp/slog/handler.go:327 +0x4f
golang.org/x/exp/slog.Record.Attrs({{0xc0f5d1d36f9de160, 0xf6a35, 0x12cc380}, {0x1197c45, 0x8}, 0x0, {0x0, 0x0}, 0x1158807, {{{0x1196f2d, ...}, ...}, ...}, ...}, ...)
	/Users/gowork/gx/vendor/golang.org/x/exp/slog/record.go:100 +0x9e
golang.org/x/exp/slog.(*handleState).appendNonBuiltIns(_, {{0xc0f5d1d36f9de160, 0xf6a35, 0x12cc380}, {0x1197c45, 0x8}, 0x0, {0x0, 0x0}, 0x1158807, ...})
	/Users/gowork/gx/vendor/golang.org/x/exp/slog/handler.go:326 +0x465
golang.org/x/exp/slog.(*commonHandler).handle(_, {{0xc0f5d1d36f9de160, 0xf6a35, 0x12cc380}, {0x1197c45, 0x8}, 0x0, {0x0, 0x0}, 0x1158807, ...})
	/Users/gowork/gx/vendor/golang.org/x/exp/slog/handler.go:304 +0x8c8
golang.org/x/exp/slog.(*TextHandler).Handle(_, {{0xc0f5d1d36f9de160, 0xf6a35, 0x12cc380}, {0x1197c45, 0x8}, 0x0, {0x0, 0x0}, 0x1158807, ...})
	/Users/gowork/gx/vendor/golang.org/x/exp/slog/text_handler.go:90 +0x58
golang.org/x/exp/slog.(*Logger).logPC(0xc000135dc8, {0x0, 0x0}, 0x1158807, 0x0, {0x1197c45, 0x8}, {0xc000135ee0, 0x4, 0x4})
	/Users/gowork/gx/vendor/golang.org/x/exp/slog/logger.go:178 +0x255
golang.org/x/exp/slog.(*Logger).LogDepth(0xc000135dc8, 0x1, 0x100d9ff?, {0x1197c45, 0x8}, {0xc000135ee0, 0x4, 0x4})
	/Users/gowork/gx/vendor/golang.org/x/exp/slog/pc.go:26 +0xe8
golang.org/x/exp/slog.(*Logger).Info(...)
	/Users/gowork/gx/vendor/golang.org/x/exp/slog/logger.go:193
git.woa.com/sase/gx/glibs/slogx.TestTextHandler(0x0?)
	/Users/gowork/gx/glibs/slogx/slog_core_test.go:47 +0x42d
testing.tRunner(0xc0001501a0, 0x11ba030)
	/usr/local/go/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1493 +0x35f
Process finished with the exit code 1

**Comment by seankhliao** [comment]
cc @jba

**Comment by jba** [comment]
Fix: https://go-review.googlesource.com/c/exp/+/470635.
