### ISSUE TITLE
encoding/json: optimizing memory allocation of json.RawMessage

### ISSUE THREAD

**Issue by hafus** [golang/go#58657]
### What version of Go are you using (`go version`)?

<pre>
$ go version
All versions
</pre>

### Does this issue reproduce with the latest release?

Yes, It does

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
All OS/CPU arch
</pre></details>

### What did you do?

This is the first time I open an issue in Golang repo and I don't know if it's under the right category. I would like to propose an optimization to json.RawMessage  struct to get rid of an extract memory allocation on call of UnmarshalJSON func of json.RawMessage struct as stated below:

Current
```golang
func (m *RawMessage) UnmarshalJSON(data []byte) error {
	if m == nil {
		return errors.New("json.RawMessage: UnmarshalJSON on nil pointer")
	}
	*m = append((*m)[0:0], data...)
	return nil
}
```

Proposal
```golang
func (m *RawMessage) UnmarshalJSON(data []byte) error {
	if m == nil {
		return errors.New("json.RawMessage: UnmarshalJSON on nil pointer")
	}

	*m = data
	return nil
}
```
To verify the above optimization,  I run below benchmark.
```golang
type msg struct {
	RawData json.RawMessage
}

var raw = []byte(`{"RawData":{"name":"test", "age":22}}`)

func BenchmarkRawMsg(b *testing.B) {

	for i := 0; i < b.N; i++ {
		var m msg
		json.Unmarshal(raw, &m)
	}

}
```

### What did you expect to see?
<code>BenchmarkRawMsg-16    	 1476358	       797.3 ns/op	     256 B/op	       6 allocs/op</code>

### What did you see instead?
<code>BenchmarkRawMsg-16    	 1467776	       842.1 ns/op	     288 B/op	       7 allocs/op</code>

**Comment by mateusz834** [comment]
https://pkg.go.dev/encoding/json#Unmarshaler
> UnmarshalJSON must copy the JSON data if it wishes to retain the data after returning.

**Comment by seankhliao** [comment]
see above, working as intended
