### ISSUE TITLE
Program freezes a moment on Windows + virus security (often) + > redirection not working

### ISSUE THREAD

**Issue by fredOnGitHub** [golang/go#58664]
Program to test : [On Github](https://github.com/fredOnGitHub/TriRapide/tree/main/GoTriRapide)

go version go1.20.1 windows/amd64

Hello,

I have 3 problems:

1. Often Windows tells me there is a virus detected, so I have to click too often on defender...

2. Using `Measure-Command { go run main.go } > temps.txt` the program freeze and i get [0,6457994 sec](https://github.com/fredOnGitHub/TriRapide/blob/main/GoTriRapide/temps.txt) but really it is [0.004178 sec](https://github.com/fredOnGitHub/TriRapide/blob/main/GoTriRapide/out.txt) (`t0 := time.Now()`)

3. `go run .\main.go > out.txt `redirection not working and the file is empty. It's like i only do that `go run .\main.go` 

Thanks for your help

**Comment by seankhliao** [comment]
there's nothing we can do about antivirus or shell issues.

closing as not an issue with the Go project
