### ISSUE TITLE
compiler: internal compiler error: assertion failed with when calling a function returned from the profile package

### ISSUE THREAD

**Issue by florisch** [golang/go#58673]
### What version of Go are you using (`go version`)?

<pre>
$ 1.20.1
</pre>

### Does this issue reproduce with the latest release?

This issue started with Go 1.20, the same code compiles and run fine under Go 1.19

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Florian\AppData\Local\go-build
set GOENV=C:\Users\Florian\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Florian\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Florian\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Users\Florian\sdk\go1.20.1
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Users\Florian\sdk\go1.20.1\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.20.1
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=W:\projects\software\go\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\Florian\AppData\Local\Temp\go-build1056532871=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

Updating my company's codebase to Go 1.20, our code doesn't build anymore. The build results in the error shown below.

Investigating this I found that it comes from a function returning a function, when the function returned is the ``Stop`` function of the github.com/pkg/profile package.

The most simplified version that could reproduce the issue can be found here: https://go.dev/play/p/qjfpA3p_M25

The same code executed with Go 1.19 works, it fails with Go 1.20. This other example (https://go.dev/play/p/jsa1eJJcGkc) show that calling this function directly works. It only fail when this function is returned and then called from an other function.

### What did you expect to see?
The code should compile and work fine, the result should be similar to the output below (with Go 1.19):

<pre>
2009/11/10 23:00:00 profile: cpu profiling enabled, /tmp/profile4007450419/cpu.pprof
2009/11/10 23:00:00 profile: caught interrupt, stopping profiles
timeout running program

Program exited.
</pre>

### What did you see instead?
<pre>
/tmp/gopath1895340349/pkg/mod/github.com/pkg/profile@v1.7.0/profile.go:72:6: internal compiler error: assertion failed

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new

Go build failed.
</pre>

**Comment by cuonglm** [comment]
Duplicated of https://github.com/golang/go/issues/58563
