### ISSUE TITLE
bufio: Scanner.Err() checks for io.EOF directly

### ISSUE THREAD

**Issue by stevenh** [golang/go#58670]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/data/go/bin"
GOCACHE="/home/steveh/.cache/go-build"
GOENV="/home/steveh/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOOS="linux"
GOPATH="/home/steveh/code"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2926415486=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Scanned from a reader which returned a wrapped io.EOF.
https://go.dev/play/p/HClzqB8deSR

### What did you expect to see?
No errors.

### What did you see instead?
The wrapped io.EOF was returned from scanner.Err().

I would expect the check to use `errors.Is(s.err, io.EOF)`:
```go
// Err returns the first non-EOF error that was encountered by the Scanner.
func (s *Scanner) Err() error {
	if errors.Is(s.err, io.EOF) {
		return nil
	}
	return s.err
}
```
And not the [direct check](https://github.com/golang/go/blob/master/src/bufio/scan.go#L96):
```go
// Err returns the first non-EOF error that was encountered by the Scanner.
func (s *Scanner) Err() error {
	if s.err == io.EOF {
		return nil
	}
	return s.err
}
```

**Comment by ianlancetaylor** [comment]
Thanks, but as is documented at https://pkg.go.dev/io#Reader, a `Read` method should return `io.EOF` at end-of-file.  It should not return an error that wraps `io.EOF`.

**Comment by stevenh** [comment]
Ahh you learn something every day, not sure how well known that is but now I do :)
