### ISSUE TITLE
x/tools/gopls/internal/lsp/protocol: CodeAction.Edit is always serialized

### ISSUE THREAD

**Issue by briandealwis** [golang/go#58687]
`protocol.CodeAction` can't be used to lazily compute workspace edits with [`codeAction/resolve`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#codeAction_resolve) as  [`protocol.CodeAction.Edit`](https://cs.opensource.google/go/x/tools/+/master:gopls/internal/lsp/protocol/tsprotocol.go;drc=e85b5336ed5c729c983d08d5f581b5034e8f1a9b;l=303) is a struct value, and not a pointer to a struct, and is thus always serialized even when a zero value:
```golang
// The workspace edit this code action performs.
Edit WorkspaceEdit `json:"edit,omitempty"`
```

I see in serialized output:
```
I0224 09:15:34.328959      63 conn_opt.go:96] jsonrpc2: <-- result #3: textDocument/codeAction: [{"title":"...","kind":"quickfix","diagnostics":[...],"edit":{},"data":{...}},...]
```

`omitempty` is not applied by [`json.Marshal`](https://pkg.go.dev/encoding/json) for zero-value structs (see #11939):
> The "omitempty" option specifies that the field should be omitted from the encoding if the field has an empty value, defined as false, 0, a nil pointer, a nil interface value, and any empty array, slice, map, or string.

I think the solution is for [`{"CodeAction", "edit"}`](https://cs.opensource.google/go/x/tools/+/master:gopls/internal/lsp/protocol/generate/tables.go;drc=e85b5336ed5c729c983d08d5f581b5034e8f1a9b;l=25) to be marked as `wantOptStar`:
```golang
	{"CodeAction", "edit"}:                                       wantOpt,
```
cc: @hyangah

**Comment by pjweinb** [comment]
Yes, this is a bug. (It was this way for backwards compatibility, but it
can now be fixed. There are a lot of these.)

I'll try to fix it fairly soon.

**Comment by pjweinb** [comment]
This was fixed by https://go-review.git.corp.google.com/c/tools/+/472656 .
