### ISSUE TITLE
affected/package: time

### ISSUE THREAD

**Issue by afiefh** [golang/go#58688]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.20
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
amd64, Linux
</pre></details>

### What did you do?

```
const FormatISO8601Short = "2006-01-02"
t := time.Date(0, 0, 0, 0, 0, 0, 0, time.UTC)
fmt.Printf("Date was constructed as %s\n", t.String())
ts := t.Format(FormatISO8601Short)
fmt.Printf("Date was formatted as %s\n", t.String())
if tt, err := time.Parse(FormatISO8601Short, ts); err != nil {
	fmt.Printf("Parsing returned an error: %s\n", err)
} else {
	fmt.Printf("Parsing succeeded: %s\n", tt.Format(FormatISO8601Short))
}
```

### What did you expect to see?

`Parsing succeeded` with the same Time string representation as on the line `Date was formatted as`.

### What did you see instead?

```
Date was constructed as -0001-11-30 00:00:00 +0000 UTC
Date was formatted as -0001-11-30 00:00:00 +0000 UTC
Parsing returned an error: parsing time "-0001-11-30" as "2006-01-02": cannot parse "-0001-11-30" as "2006"
```

### Expected solution

The functions `Parse` and `Format` should be the inverse of one another.

**Comment by seankhliao** [comment]
I believe this is working as intended for Parse:

> Years must be in the range 0000..9999.
