### ISSUE TITLE
x/tools/cmd/godoc: make path elements hyperlinks

### ISSUE THREAD

**Issue by gopherbot** [golang/go#5869]
by **feedback.test.account**:

<pre><a href="https://feedback.corp.google.com/#/Report/1007590596">https://feedback.corp.google.com/#/Report/1007590596</a>

Description:
These should be hyperlinks so can browse the code.

UI language: en
Detected language: en</pre>

**Comment by agnivade** [comment]
Seems fixed now. Closing.
