### ISSUE TITLE
syscall: `Environ` uses an invalid `unsafe.Pointer` conversion on Windows

### ISSUE THREAD

**Issue by bcmills** [golang/go#58714]
```
#!watchflakes
post <- goos == "windows" && log ~ `fatal error: checkptr: converted pointer straddles multiple allocations` && log ~ `syscall\.Environ`
```

The pointer conversion on [this line](https://cs.opensource.google/go/go/+/master:src/syscall/env_windows.go;l=83;drc=8dc08394f0d5f83523080e4dd99fded26b7c1ceb) is invalid: it refers to a null-terminated string by a hard-coded array size.
```
	for from, i, p := 0, 0, (*[1 << 24]uint16)(unsafe.Pointer(s)); true; i++ {
```

**Comment by bcmills** [comment]
(CC @golang/windows)

**Comment by bcmills** [comment]
(Pulled out from https://github.com/golang/go/issues/55167#issuecomment-1443976333.)

**Comment by bcmills** [comment]
@gopherbot, please backport to Go 1.19 and 1.20. These failures also occur on at least `release-branch.go1.20`.

**Comment by bcmills** [comment]
aef8a8cd is also `release-branch.go1.20`.

**Comment by mknyszek** [comment]
In triage: @bcmills Is this effectively done? Should this issue be closed?

**Comment by bcmills** [comment]
Yes, this is done; `watchflakes` erroneously reopened it again (see #57632).

**Comment by alexbrainman** [comment]
> x/tools/gopls/internal/regtest/misc.TestRunGovulncheckStd

Looks like x/tools/... uses old version of x/sys/windows package that contains this bug.

Reopening this issue so we remember to update x/tools to the later version.

Alex
