### ISSUE TITLE
runtime/pprof,cmd/compile: simplified symbol names for generics break PGO matching

### ISSUE THREAD

**Issue by prattmic** [golang/go#58712]
For functab, and thus stack traces and symbol names in pprof profile outputs, the compiler simplifies symbol names like `foo[go.shape.int64]` to just `foo[...]`.

When reading a profile for PGO, the compiler will attempt to match symbols and fail because the profile symbol name does not match the actual symbol name.

This could be addressed from either end:

* The profile could contain the full symbol name (`Function.name = "foo[...]"`, `Function.system_name = "foo[go.shape.int64]"` perhaps?).
* Or, the compiler could match `foo[...]` to any instantiation of `foo`.

cc @cherrymui @aclements

**Comment by cherrymui** [comment]
I'd prefer the first option.  For the same generic function, some instantiation may be hot and some other may be cold. So it would be good to distinguish them. Especially if we want to do PGO-based specification/stenciling later.

**Comment by cherrymui** [comment]
I'll look into it.
