### ISSUE TITLE
runtime: SIGSEGV in `allocNeedsZero` on darwin

### ISSUE THREAD

**Issue by bcmills** [golang/go#58715]
```
#!watchflakes
post <- goos == "darwin" && log ~ `runtime\.\(\*mheap\)\.allocNeedsZero` && log ~ `SIGSEGV`
```

(Pulled out from https://github.com/golang/go/issues/55167#issuecomment-1443976333.)

**Comment by mknyszek** [comment]
The stack trace implies loading a nil `heapArena` struct. I'm not sure how this could happen (for instance due to a race). I'll look into it.

**Comment by mknyszek** [comment]
I want to look into whether this is actually only happening on Darwin.

**Comment by prattmic** [comment]
I see it once on freebsd in 2021:

[2021-10-13T18:15:48-40f82f8/freebsd-386-12_2](https://build.golang.org/log/4e841ce2ad732e873499f87e37920d6b0dc983ea)

**Comment by bcmills** [comment]
@golang/runtime, is this another symptom of #60449 or do we think it has a separate root cause?

**Comment by mknyszek** [comment]
I believe it's another symptom. I recall investigating this and concluding that it's memory corruption. I double-checked just now and yeah, the failing line doesn't really make sense (that index is write-once, but if it was just allocated and the wrong index was being set up, then we'd be seeing these crashes in a *lot* more places).

**Comment by mknyszek** [comment]
I added this as a condition to https://github.com/golang/go/issues/60449, closing now as a duplicate.
