### ISSUE TITLE
proposal: crypto/tls: Support AEGIS (for TLS 1.3)

### ISSUE THREAD

**Issue by rugk** [golang/go#58724]
> Two AEGIS algorithms have been added to the [IANA registry](https://www.iana.org/assignments/aead-parameters/aead-parameters.xhtml#:~:text=32-,AEAD_AEGIS128L,-%5Bdraft%2Dirtf) and will be supported in TLS 1.3. [AEGIS](https://datatracker.ietf.org/doc/draft-irtf-cfrg-aegis-aead/00/) is a new authenticated encryption algorithm that provides better performance and better practical security.

from the [Bulletproof TLS Newsletter](https://www.feistyduck.com/bulletproof-tls-newsletter/) 2022-12-29

---

So given caddy e.g. has a history of adapting new TLS changes, maybe that should be a thing to adopt. (`AEAD_AEGIS128L` and `AEAD_AEGIS256` as ciphers)

---

copied from https://github.com/caddyserver/caddy/issues/5345

**Comment by seankhliao** [comment]
This should wait until it is stabilized as a published RFC before we consider it.
