### ISSUE TITLE
cmd/compile: race is not supported on linux/riscv64

### ISSUE THREAD

**Issue by ArchFeh** [golang/go#58739]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.1 linux/riscv64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="riscv64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="riscv64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_riscv64"
GOVCS=""
GOVERSION="go1.20.1"
GCCGO="gccgo"
AR="ar"
CC="riscv64-unknown-linux-gnu-gcc"
CXX="riscv64-unknown-linux-gnu-g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2295547135=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I just run <pre>go test -race</pre>

### What did you expect to see?
It run.

### What did you see instead?
<pre>-race is not supported on linux/riscv64</pre>

Is there any plan to let race support riscv64?

**Comment by wdvxdr1123** [comment]
According to https://github.com/llvm/llvm-project/blob/aa56e66bf7520512fd1209cbb7d099604a5f6277/compiler-rt/cmake/Modules/AllSupportedArchDefs.cmake#L63-L64, ThreadSanitizer is not supported in LLVM. We need to wait for upstream support for this feature.

**Comment by ianlancetaylor** [comment]
Closing because this isn't something that the Go project can fix.
