### ISSUE TITLE
x/vuln: possible missed x/crypto vulnerability in govulncheck?

### ISSUE THREAD

**Issue by taisph** [golang/go#58752]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.1 linux/amd64
</pre>

### Does this issue reproduce at the latest version of golang.org/x/vuln?

Yes.

### What did you do?

GitHub dependabot reports a project is affected by GHSA-8c26-wmh5-6g9v. I can see it is in the vulnerability database at https://pkg.go.dev/vuln/GO-2021-0356, yet the govulncheck tool does not report it when running `govulncheck ./...`. Not even as an informational entry. Unsure if GitHub dependabot could wrong about this though as the report seems to concern <go1.18.

```
govulncheck is an experimental tool. Share feedback at https://go.dev/s/govulncheck-feedback.

Using go1.20.1 and govulncheck@v0.0.0 with
vulnerability data from https://vuln.go.dev (last modified 22 Feb 23 20:16 UTC).

Scanning your code and 463 packages across 64 dependent modules for known vulnerabilities...
No vulnerabilities found.
```

go.mod seems to contain the vulnerable indirect dependency:
```
go 1.18
//...
require (
//...
	golang.org/x/crypto v0.0.0-20220214200702-86341886e292 // indirect
//...
)
```

### What did you expect to see?

```
Scanning your code and 463 packages across 64 dependent modules for known vulnerabilities...

... information about the vulnerability, affected or informational.
```

### What did you see instead?

```
Scanning your code and 463 packages across 64 dependent modules for known vulnerabilities...
No vulnerabilities found.
```

**Comment by seankhliao** [comment]
dependabot only looks at dependency versions
govulncheck will look at code that's imported and used to determine if a vulnerability is reachable / affects the code.

without further information, this is likely working as intended

**Comment by taisph** [comment]
> dependabot only looks at dependency versions govulncheck will look at code that's imported and used to determine if a vulnerability is reachable / affects the code.

govulncheck usually reports the vulnerabilities that are not reachable under "informational" such as the example below. In this specific case, it doesn't report anything which makes me a little worried if it might sometimes miss things given that it is an experimental tool.

```
=== Informational ===

Found 3 vulnerabilities in packages that you import, but there are no call
stacks leading to the use of these vulnerabilities. You may not need to
take any action. See https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck
for details.

Vulnerability #1: GO-2022-0956
  Parsing malicious or large YAML documents can consume excessive
  amounts of CPU or memory.
  More info: https://pkg.go.dev/vuln/GO-2022-0956
  Found in: gopkg.in/yaml.v2@v2.2.2
  Fixed in: gopkg.in/yaml.v2@v2.2.4

[...]
```

> without further information, this is likely working as intended

What would be needed to help? It is sadly from a private client repo so I am unable to share much.

**Comment by gophun** [comment]
> govulncheck usually reports the vulnerabilities that are not reachable under "informational" 

Only if the vulnerable subpackage is imported.

This one does not report anything:

```
module demo

go 1.20

require golang.org/x/crypto v0.0.0-20220214200702-86341886e292
```

```
package main

import "golang.org/x/crypto/blowfish"

func main() {
	_ = blowfish.BlockSize
}
```

However, this one does report the vulnerability in the "Informational" section:

```
package main

import "golang.org/x/crypto/ssh"

func main() {
	_ = ssh.UserCert
}
```

```
=== Informational ===

Found 1 vulnerability in packages that you import, but there are no call
stacks leading to the use of this vulnerability. You may not need to
take any action. See https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck
for details.

Vulnerability #1: GO-2021-0356
  Attackers can cause a crash in SSH servers when the server has
  been configured by passing a Signer to ServerConfig.AddHostKey
  such that 1) the Signer passed to AddHostKey does not implement
  AlgorithmSigner, and 2) the Signer passed to AddHostKey returns
  a key of type “ssh-rsa” from its PublicKey method. Servers
  that only use Signer implementations provided by the ssh package
  are unaffected.
  More info: https://pkg.go.dev/vuln/GO-2021-0356
  Found in: golang.org/x/crypto@v0.0.0-20220214200702-86341886e292
  Fixed in: golang.org/x/crypto@v0.0.0-20220314234659-1baeb1ce4c0b
```

**Comment by seankhliao** [comment]
see above

**Comment by taisph** [comment]
> > govulncheck usually reports the vulnerabilities that are not reachable under "informational" 
> 
> Only if the vulnerable subpackage is imported.

Thank you for the explanation.
