### ISSUE TITLE
bug with string changing in goroutine: 

### ISSUE THREAD

**Issue by niciki** [golang/go#58762]
### What version of Go are you using (`go version`)?
go1.20.1 darwin/amd64

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

### What did you do?

Link to the repository with the service: https://github.com/niciki/go-bug. When starting the service, call the handle /printstring with an id of some kind, for example, http://localhost:8080/v1/printstring/2adf08ce-5c8d-49c9-acbc-99c08b908d91, and then pull the handle http://localhost:8080/v1/get/string many times. In the running goroutine, the value of id passed changes, as if some kind of shift of the pointer in memory occurs, as can be seen in the output. If the handle / get is not called, everything works correctly. At the same time, on Go 1.18, and the AMD processor, everything works correctly.

### What did you expect to see?
![image](https://user-images.githubusercontent.com/71276784/221584628-f34e4c53-eef7-414d-b215-34983eb7b617.png)

### What did you see instead?

![image](https://user-images.githubusercontent.com/71276784/221584428-a8842fa8-b1cb-410c-bbd1-3837e58753df.png)

**Comment by wdvxdr1123** [comment]
Looks like a data race. Have you run your program under race mode?

**Comment by niciki** [comment]
> race mode

yes, you're right, there are problems with DATA RACE. But how can it arise, the string does not change in the gorutin, the gorutin is one, what can cause this string to change?

**Comment by ianlancetaylor** [comment]
A data race can cause a string to change because the same memory can be accessed from two different goroutines.  Fix the data race first, then see if you still have a problem.

**Comment by wdvxdr1123** [comment]
I notice you use fiber in your code. See https://docs.gofiber.io/#zero-allocation. Fiber will reuse fiber.Ctx that may cause a data race.
