### ISSUE TITLE
cmd/go: TestDocsUpToDate is incompatible with android emu builder environment

### ISSUE THREAD

**Issue by dmitshur** [golang/go#58775]
[CL 468636](https://go.dev/cl/468636) (CC @bcmills) recently improved TestDocsUpToDate to invoke `go help documentation` directly, without the mkalldocs.sh script, but it's not able to run at least in the emu android builders, failing with:

```
--- FAIL: TestDocsUpToDate (0.00s)
    help_test.go:34:  help documentation: exec: no command
FAIL
exitcode=1
FAIL	cmd/go	0.550s
```

(https://build.golang.org/log/3cee601aeb5302bcf6b0304d14ef713c9f3bff76)

CC @golang/android.

**Comment by dmitshur** [comment]
The problem seems to be that `testGo` is only set when `testenv.HasGoBuild()` reports positively, but when GOOS=android it returns false. The test currently doesn't check `testenv.HasGoBuild()` nor `testGo` being non-empty.

**Comment by bcmills** [comment]
Agreed — I just noticed that too. Probably we should set `testGo` if `testenv.HasExec` is true, since not every Go command is `go build`.

Independently, I think there are some pretty deep problems with the way the `go_android_exec` wrapper is setting up the build environment. 😕
