### ISSUE TITLE
cmd/go: too many open files in system 

### ISSUE THREAD

**Issue by maxgiraldo** [golang/go#58788]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.1 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/maxgiraldo/Library/Caches/go-build"
GOENV="/Users/maxgiraldo/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/maxgiraldo/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/maxgiraldo/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/maxgiraldo/go/src/github.com/maxgiraldo/test_server/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/lf/r3_cvxl10n502833_y2v3rr80000gn/T/go-build2784566378=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Trying to run basic server:

```go
package main

import (
    "fmt"
    "net/http"
)

func hello(w http.ResponseWriter, req *http.Request) {

    fmt.Fprintf(w, "hello\n")
}

func headers(w http.ResponseWriter, req *http.Request) {

    for name, headers := range req.Header {
        for _, h := range headers {
            fmt.Fprintf(w, "%v: %v\n", name, h)
        }
    }
}

func main() {

    http.HandleFunc("/hello", hello)
    http.HandleFunc("/headers", headers)

    http.ListenAndServe(":8090", nil)
}
```

I am not able to run or install the program.

### What did you expect to see?
The server running.

### What did you see instead?
`/usr/local/go/src/vendor/golang.org/x/text/unicode/bidi/core.go:9:2: open /usr/local/go/src/log/example_test.go: too many open files in system`

Why is `go` trying to open these files?

**Comment by ianlancetaylor** [comment]
What is the exact command that you run that prints that error message?

**Comment by maxgiraldo** [comment]
go run .

**Comment by maxgiraldo** [comment]
I ran go mod tidy earlier and it completely messed up everything and failed because it tried to search my entire filesystem. Not sure if causal relationship is there, but that context might help.

**Comment by ianlancetaylor** [comment]
What does `go run -x` print?

**Comment by maxgiraldo** [comment]
```
WORK=/var/folders/lf/r3_cvxl10n502833_y2v3rr80000gn/T/go-build2569235747
/usr/local/go/src/vendor/golang.org/x/text/unicode/bidi/core.go:9:2: open /usr/local/go/src/log/example_test.go: too many open files in system
```

**Comment by bcmills** [comment]
> `/usr/local/go/src/vendor/golang.org/x/text/unicode/bidi/core.go:9:2: open /usr/local/go/src/log/example_test.go: too many open files in system`
>
> Why is go trying to open these files?

`golang.org/x/text/unicode/bidi` imports the `log` package.

Compiling the `log` package itself shouldn`t require opening `example_test.go`, but as of Go 1.19 the `go` command indexes package information and uses that instead of reopening files for each build. That is supposed to happen only once per build, but of course if that fails the  index won't be written to the cache.

But, that seems like something of a red herring — if the error is `too many open files in system`, what else on your system is holding files open? (If it were just the `go` command, the error would presumably be `too many open files` instead.)

A good starting point for that investigation might be to run `lsof` and see if you spot a pattern.

**Comment by maxgiraldo** [comment]
Closing as it doesn't seem to be an issue with go, but rather my system.

**Comment by maxgiraldo** [comment]
I have about 8007 open files in my system on fresh reboot and closing my applications. I set a soft limit for 10240, but there's a hard limit of unlimited. I'm not sure why go would still complain.

```
ulimit -aS
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8176
-c: core file size (blocks)         0
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       1333
-n: file descriptors                10240
```

**Comment by bcmills** [comment]
FWIW, based on https://superuser.com/questions/433746/is-there-a-fix-for-the-too-many-open-files-in-system-error-on-os-x-10-7-1 I checked a couple of the builders operated by the Go project and found:

`darwin-amd64-13-0`:
```
$ lsof | wc -l
    3311
$ sysctl kern.maxfiles
kern.maxfiles: 30720
$ sysctl kern.maxfilesperproc
kern.maxfilesperproc: 10240
```

`darwin-arm64-12`:
```
$ lsof | wc -l
    3643
$ sysctl kern.maxfiles
kern.maxfiles: 122880
$ sysctl kern.maxfilesperproc
kern.maxfilesperproc: 61440
```

Even on the `amd64` builder with a `maxfilesperproc` limit of only 10240, that seems like plenty of headroom. I would be surprised if any of those limits were adjusted when the builder images were created. (There aren't any such steps listed in https://cs.opensource.google/go/x/build/+/master:env/darwin/setup-notes.md.)

Perhaps you have some kind of third-party service installed that is holding a lot of files open?

**Comment by maxgiraldo** [comment]
Yeah, i’m going to do a clean install and see if I can reproduce.

**Comment by carlmjohnson** [comment]
I was running out of file descriptors on Mac OS every few days a few months ago. It started around the time I installed Tailscale's Golink program, and it seemed to be related to that because, it seemed to stop when I stopped running it, and since I upgraded Golink a few weeks ago, the problem hasn't recurred. I'm still unsure what the root cause was though, maybe that's a coincidence. I've also had instability with my Time Machine backups.

**Comment by maxgiraldo** [comment]
I erased all contents and settings on my Mac and re-installed go and was able to run it. There's still about ~6265 open files by default when you do a fresh install of Ventura 13.1, but `go` no longer complains. I guess I'll be careful about what I install next time.
