### ISSUE TITLE
cmd/link: new c-shared relocations of the ELF ABI on LoongArch

### ISSUE THREAD

**Issue by limeidan** [golang/go#58784]
Hi everyone,

This Issue is opened to discuss relocation-related issues in the LoongArch ELF ABI.

Here's the section on relocations from the LoongArch ELF ABI documentation:

https://loongson.github.io/LoongArch-Documentation/LoongArch-ELF-ABI-EN.html#_relocations

Initially, in order to easily understand the relocation process when linking binary files (the linker reads the relocation table linearly, which can be naturally associated with stack operations), LoongArch adopts a relocation mechanism based on a data stack, also, considering the reusability, the granularity of these relocations is small.

However, in subsequent practice, it was found that this approach will lead to a large increase in the number of relocations in the binary file.

Therefore, LoongArch has added relocation types from No. 64 to No. 100 on the original basis. These relocations have a large operation granularity, and they can directly implement a single function without stack operations, which solves the problem of excessive relocations.

## Regarding compatibility:

Binutils supported LoongArch when version 2.38 was released. Since v2.40, it supports the new relocation of LoongArch. The original relocation has not been deleted, so v2.40 and later versions can also support early relocation. Released v2.38 and v2.39 do not support the new relocations.

## User machine:

The upcoming debian12 already uses binutils-2.40, and LoongArch is currently being submitted on the debian development branch. It is foreseeable that in the future debian version that supports LoongArch (maybe debian13), the binutils used in it must support the newly added relocation .

The latest Gentoo system that has been released uses binutils-2.40.

The loong64 builders we are using also support the new relocations.

**Comment by limeidan** [comment]
@golang/loong64 @cherrymui

**Comment by limeidan** [comment]
We recommend removing support for stack-based relocation. The work of the LoongArch community is still in its initial stage. And, there are still very few users based on stack-style relocations, the impact of deletion is not very great. If we continue to use the old relocation, it may be more difficult to deal with this part in the future, finally, it will become a historical burden.

**Comment by cherrymui** [comment]
Sounds fine to me. Thanks.

So you estimate that it will affect very small amount of users? And updating the C toolchain is relatively straightforward? Do you think Go 1.21 release (Aug 2023) is a good time for this, or do it in a later release so the new C toolchain is more widely available? Thanks.

**Comment by limeidan** [comment]
Yes, currently there are very few LoongArch users using the community source code. The users of the community code are basically upstream developers or based on experimental nature, not a production environment, so timely changes have little impact.

For golang, the update of the C toolchain only involves the upgrade of binutils, which is relatively simple.

I think it's a good time to support new relocations in Go 1.21:
1. Currently, there are very few users, and new users will basically use the new C toolchain.
2. The latest binutils version (v2.40) is the first version that supports LoongArch relatively well. It contains important bug fixes for linker support for dynamic shared libraries (if users want to use c-shared, they must use version 2.40 or later).

Thanks.

**Comment by xen0n** [comment]
> Sounds fine to me. Thanks.
> 
> So you estimate that it will affect very small amount of users?

AFAIK yes, we've always been discouraging casual end-users from trying the new-world for the last 2 years.

> And updating the C toolchain is relatively straightforward?

Yes. All new-world distros stick to latest toolchains in general (sometimes even chasing weekly snapshots, as been the case with Gentoo/LoongArch's GCC 13). All are already switched to psABI v2.

> Do you think Go 1.21 release (Aug 2023) is a good time for this, or do it in a later release so the new C toolchain is more widely available? Thanks.

Given the current development pace of new-world distros, Aug 2023 most certainly works, since both binutils 2.40 and gcc 13 would be officially released for a while then, and distros are expected to pick up the versions real quick. Many are *already done* after all...

**Comment by abner-chenc** [comment]
CL [#480875](https://go.dev/cl/480875)  also uses a new relocation implementation in accessing GOT, which makes the code look more concise.

**Comment by abner-chenc** [comment]
In CL [483455](https://go-review.googlesource.com/c/sys/+/483455), I updated the loong64 platform cross toolchain that generates the zerog64 platform in sys, which also uses the new relocation type. 

Thanks.
