### ISSUE TITLE
debug/buildinfo: recognize macOS fat binaries

### ISSUE THREAD

**Issue by jamesez** [golang/go#58796]
### What version of Go are you using (`go version`)?
`go version go1.19.6 darwin/arm64`

### Does this issue reproduce with the latest release?
Yes, with 1.20.1.

### What did you do?
1. Built a dual-architecture fat binary with
``` 
GOOS=darwin GOARCH=arm64 go build -o arm64 .
GOOS=darwin GOARCH=amd64 go build -o amd64 .
lipo -create -output fatBinary arm64 amd64
```
2. Try to inspect version of built product with `go version fatBinary`
3. Get error `unrecognized file format` instead of version data.

### What did you expect to see?
Two listings, one per architecture. Something like:
```
fatBinary (arm64): go1.19.6
fatBinary (amd64): go1.19.6
```

**Comment by nikola-jokic** [comment]
Can I give it a try :relaxed: ?

**Comment by ianlancetaylor** [comment]
Sure.  Thanks.
