### ISSUE TITLE
syscall: effect of Chdir in Plan 9 may not be simultaneous to all goroutines

### ISSUE THREAD

**Issue by millerresearch** [golang/go#58802]
CL [6350](https://go-review.googlesource.com/c/go/+/6350) added a `syscall.Fixwd` routine to ensure that a Chdir in one goroutine is propagated to other goroutines before the working directory is referenced in a subsequent syscall. This is needed because each M in Plan 9 runs as a separate OS process with its own working directory.

This mechanism turns out to be not quite sufficient to guarantee that Chdir is effectively program wide. It may be frustrated by preemption of a goroutine and rescheduling onto a different M at an inopportune moment.

Circumstantial evidence includes test failures like [this](https://build.golang.org/log/5c92640ec6907f3afb756b2fa45a48559d068d53) with messages like './testdata' file does not exist', and the observation by @psilva261 in the discussion of #57540 that inserting some `runtime.LockOSThread` calls around `Fixwd` makes "fs related tests ... much more stable".

I've also found that if the `os.TestProgWideChdir` test is made slightly more aggressive, it will
sometimes report errors.

**Comment by psilva261** [comment]
I could create a patch for this, so far I've tried adding additional locking in `Fixwd()`, `fixwd()`, `Getwd()` and `Chdir()` although it's probably not needed everywhere.

**Comment by millerresearch** [comment]
I think your patch mentioned in #57540 might be too much and too little. For example `fixwd()` doesn't need to lock to the OS thread because it only makes one call to `Fixwd()`, which already does the locking.

On the other hand, consider this sequence (with your patch):

1. syscall.Open is called with a relative pathname
2. Open calls fixwd, which calls runtime.LockOSThread
3. fixwd calles Fixwd which calls fixwdLocked which calls chdir, changing the directory for the current M
4. Before returning, fixwd calls runtime.UnlockOSThread
5. syscall.Open calls open which opens the file in the correct (we hope) directory

But what if the goroutine gets preempted between 4. and 5. and is rescheduled on a different M where Fixwd hasn't yet been called since the most recent Chdir?

I think for safety the goroutine needs to be locked to the OS thread from the start of fixwd until after the syscall which the fixwd protects. This only needs to be done if the syscall uses a relative pathname, so maybe fixwd could return a bool to indicate if (deferred) UnlockOSThread is required.

**Comment by millerresearch** [comment]
> I think for safety the goroutine needs to be locked to the OS thread from the start of fixwd until after the syscall which the fixwd protects. This only needs to be done if the syscall uses a relative pathname, so maybe fixwd could return a bool to indicate if (deferred) UnlockOSThread is required.

@psilva261 I've tried something along these lines and it seems to work. Shall I submit it, or would you like to develop your patch (it was your idea first)?

**Comment by psilva261** [comment]
> @psilva261 I've tried something along these lines and it seems to work. Shall I submit it, or would you like to develop your patch (it was your idea first)?

@millerresearch Yes, it would be great if you would submit your patch. This takes more corner-cases into account. Also thanks a lot for the explanation.
