### ISSUE TITLE
cmd/compile: change the max allowed number of methods on a type

### ISSUE THREAD

**Issue by go101** [golang/go#58805]
Someone encountered a `too many methods on ***` compiler error: https://twitter.com/magiconair/status/1630589195856097280

It looks now the limit is 65535. Maybe the limit should be enlarged.

**Comment by ianlancetaylor** [comment]
This doesn't have to be a proposal.

This would require changing the `mcount` and `xcount` fields in `reflect.uncommonType`.  I don't think it's worth it.  64K should be enough for everyone.
