### ISSUE TITLE
cmd-*: go test -fuzz=<regexp> not run the relevant fuzz test

### ISSUE THREAD

**Issue by hitzhangjie** [golang/go#58825]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/xxxxxxx/Library/Caches/go-build"
GOENV="/Users/xxxxxx/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/xxxxx/go/pkg/mod"
GOOS="darwin"
GOPATH="/Users/xxxxxx/go"
GOPROXY="direct"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.6"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/xxxxx/Github/codemaster/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/4m/2_pn1sln1fzcg2zg_4mh95z80000gn/T/go-build1425731567=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I write 2 fuzz testcase in my code, and run the 1st testcase and it failed.
Then I want to run the 2nd testcase by `go test -fuzz=<SecondTestcase>` , but it ignores `-fuzz=<regexp>` and `-count=1` flag and keep reporting the failed testcase in the testdata/<failing_testcase_log>.

I delete the testdata/... and re-run it by `go test -fuzz=<SecondTestcase>` and it works as expected.

### What did you expect to see?

I want `go test -fuzz` could run specified testcase rather than keep reporting other testcase failing.

### What did you see instead?

It keeps reporting previous testcase failing, and not run specified testcase.

Actually, I am new to the go fuzztest :) But how it works make me a little confused.

**Comment by seankhliao** [comment]
This is working as intended, see https://go.dev/security/fuzz/#running-fuzz-tests
