### ISSUE TITLE
x/text: building as a plugin failure on darwin/arm64

### ISSUE THREAD

**Issue by zoncoen** [golang/go#58826]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.1 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/zoncoen/Library/Caches/go-build"
GOENV="/Users/zoncoen/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/zoncoen/dev/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/zoncoen/dev"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/zoncoen/dev/src/github.com/zoncoen-sample/go1.20-plugin-issue/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/7b/75304vxx7szc4b0lph6y311c0000gp/T/go-build328686675=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

`go build` fails with `-buildmode=plugin` flag on darwin/arm64 if the code imports `golang.org/x/text`.

<pre>
$ go build -buildmode=plugin -o plugin.so .
</pre>

<pre>
$ cat main.go
package main

import "golang.org/x/text/date"

func EtcUTC() int {
        return date.EtcUTC
}
</pre>

The complete reproducing code is [here](https://github.com/zoncoen-sample/go1.20-plugin-issue).

### What did you expect to see?

`go build` succeeds without error.

### What did you see instead?

<pre>
$ go build -buildmode=plugin -o plugin.so .
# golang.org/x/text/internal/language
<autogenerated>:1: REGTMP used in large offset load: 00204 (/Users/zoncoen/dev/pkg/mod/golang.org/x/text@v0.7.0/internal/language/coverage.go:18)       MOVD    2189(R27), R5
</pre>

I have confirmed that it builds correctly on linux/amd64.

**Comment by dmitshur** [comment]
CC @mpvl, @golang/runtime.

**Comment by cherrymui** [comment]
This looks like some issue in the assembler. I can look into that.

**Comment by dtrudg** [comment]
We are seeing the same issue on linux/arm64 (RHEL8, RHEL9, SLES15) when building a plugin with go 1.20.1

```
# golang.org/x/text/internal/language
    <autogenerated>:1: REGTMP used in large offset load: 00204 (golang.org/x/text@v0.7.0/internal/language/coverage.go:18)  MOVD    2189(R27), R5
    FATAL:   Plugin compile failed with error: while building plugin .so: exit status 1
    error: Bad exit status from /var/tmp/rpm-tmp.CfiMwQ (%build)
        Bad exit status from /var/tmp/rpm-tmp.CfiMwQ (%build)
``` 

The build has completes without errors on linux/amd64, and on arm64 with go 1.19.5

**Comment by cherrymui** [comment]
I think this is due to CL https://golang.org/cl/445535 . The CL description says
```
If off is very large, it becomes:
  MOVD sym@GOT, REGTMP
  MOVD $off, Rt
  ADD  Rt, REGTMP
  MOVx (REGTMP), Ry
```
The question is what is Rt? It cannot use REGTMP. Maybe it can use Ry but currently it doesn't do so. Also, Ry only works for load, not store.

cc @golang/arm @erifan

**Comment by cherrymui** [comment]
@gopherbot please backport this to Go 1.20. This can cause code failing to build. Thanks.

**Comment by cherrymui** [comment]
The culprit CL is reverted. I sent CL 473999 to re-enable the optimization but not in `-dynlink` mode, which is `-buildmode=plugin` uses and where the problem actually is.

**Comment by zoncoen** [comment]
I confirmed `gotip` (`devel go1.21-fc45eb3 Thu Mar 9 00:51:36 2023 +0000 darwin/arm64`) could build actual code. Thank you.
