### ISSUE TITLE
Useless comparison of nr, nw in io.copyBuffer

### ISSUE THREAD

**Issue by hophacker** [golang/go#58841]
https://github.com/golang/go/blob/14015be5bb4ef69c710ac5a4fad5a5d2a548e3fb/src/io/io.go#L430

In the definition of `Writer.Write`, it is specified that written bytes should `<= len(p)`. So, how could code in above line happen that `nr < nw`
```golang
// Writer is the interface that wraps the basic Write method.
//
// Write writes len(p) bytes from p to the underlying data stream.
// It returns the number of bytes written from p (0 <= n <= len(p))
// and any error encountered that caused the write to stop early.
// Write must return a non-nil error if it returns n < len(p).
// Write must not modify the slice data, even temporarily.
//
// Implementations must not retain p.
type Writer interface {
	Write(p []byte) (n int, err error)
}

```

**Comment by ianlancetaylor** [comment]
Sometimes a type that implements `io.Writer` has a bug.  This code makes it easier to catch such a bug, and compared to the overall cost of `io.Copy` it is cheap.  See #39978.
