### ISSUE TITLE
io/bufio/http : io.ReadAll costs a long time to read http request payload 

### ISSUE THREAD

**Issue by saoDiSengTank** [golang/go#58842]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.19.3 1.20.1

</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
macOS linux 
</pre></details>

### What did you do?

When i send a request  and use io.ReadAll to read the json request payload , it cost almost 2-3s on k8s env, that's unacceptable for us ,so i tried to reproduce it on my mac , but it only cost 5ms , i think that's just the exact result.

So i tried to found out  the root cause.

Here are my steps:

1.  copy the io.ReadAll code to my project , and add logs to record the time every line costs.
<img width="920" alt="Screenshot 2023-03-03 at 09 56 29" src="https://user-images.githubusercontent.com/102742059/222611972-4e4ecbbe-4a5a-4dfd-a519-89a57744cbea.png">
as the screenshot shows , i logged the expansion length / how long the read operation costs / how many times the slice b expanded.

2. Run the method on vsCode on my mac and get the logs.

content length is 604355
b length is 0 , cap is 512 
read to b from b(0) to c(512) , length is 512 
read cost 0 ms  ,len is 0 , n is 512 ,cap is 512 
b[:len(b)+n] cost 0ms  ,len is 512 , cap is 512 

b length is 512 , cap is 512 
append len=(512) cap=(896) add length 384 
read to b from b(512) to c(896) , length is 38
read cost 0 ms  ,len is 512 , n is 384 ,cap is 896 
b[:len(b)+n] cost 0ms  ,len is 896 , cap is 896 

b length is 896 , cap is 896 
append len=(896) cap=(1408) add length 512 
read to b from b(896) to c(1408) , length is 512 
read cost 0 ms  ,len is 896 , n is 512 ,cap is 1408 
b[:len(b)+n] cost 0ms  ,len is 1408 , cap is 1408 

b length is 1408 , cap is 1408 
append len=(1408) cap=(2048) add length 640 
read to b from b(1408) to c(2048) , length is 640 
read cost 0 ms  ,len is 1408 , n is 640 ,cap is 2048 
b[:len(b)+n] cost 0ms  ,len is 2048 , cap is 2048 

b length is 2048 , cap is 2048 
append len=(2048) cap=(3072) add length 1024 
read to b from b(2048) to c(3072) , length is 1024 
read cost 0 ms  ,len is 2048 , n is 1024 ,cap is 3072 
b[:len(b)+n] cost 0ms  ,len is 3072 , cap is 3072 

b length is 3072 , cap is 3072 
append len=(3072) cap=(4096) add length 1024 
read to b from b(3072) to c(4096) , length is 1024 
read cost 0 ms  ,len is 3072 , n is 764 ,cap is 4096 
b[:len(b)+n] cost 0ms  ,len is 3836 , cap is 4096 

b length is 3836 , cap is 4096 
read to b from b(3836) to c(4096) , length is 260 
read cost 0 ms  ,len is 3836 , n is 260 ,cap is 4096 
b[:len(b)+n] cost 0ms  ,len is 4096 , cap is 4096 

b length is 4096 , cap is 4096 
append len=(4096) cap=(5376) add length 1280 
read to b from b(4096) to c(5376) , length is 1280 
read cost 0 ms  ,len is 4096 , n is 1280 ,cap is 5376 
b[:len(b)+n] cost 0ms  ,len is 5376 , cap is 5376 

b length is 5376 , cap is 5376 
append len=(5376) cap=(6912) add length 1536 
read to b from b(5376) to c(6912) , length is 1536 
read cost 0 ms  ,len is 5376 , n is 1536 ,cap is 6912 
b[:len(b)+n] cost 0ms  ,len is 6912 , cap is 6912 

b length is 6912 , cap is 6912 
append len=(6912) cap=(9472) add length 2560 
read to b from b(6912) to c(9472) , length is 2560 
read cost 0 ms  ,len is 6912 , n is 1020 ,cap is 9472 
b[:len(b)+n] cost 0ms  ,len is 7932 , cap is 9472 

b length is 7932 , cap is 9472 
read to b from b(7932) to c(9472) , length is 1540 
read cost 0 ms  ,len is 7932 , n is 1540 ,cap is 9472 
b[:len(b)+n] cost 0ms  ,len is 9472 , cap is 9472 

b length is 9472 , cap is 9472 
append len=(9472) cap=(12288) add length 2816 
read to b from b(9472) to c(12288) , length is 2816 
read cost 0 ms  ,len is 9472 , n is 2556 ,cap is 12288 
b[:len(b)+n] cost 0ms  ,len is 12028 , cap is 12288 

b length is 12028 , cap is 12288 
read to b from b(12028) to c(12288) , length is 260 
read cost 0 ms  ,len is 12028 , n is 260 ,cap is 12288 
b[:len(b)+n] cost 0ms  ,len is 12288 , cap is 12288 

b length is 12288 , cap is 12288 
append len=(12288) cap=(16384) add length 4096 
read to b from b(12288) to c(16384) , length is 4096 
read cost 0 ms  ,len is 12288 , n is 3836 ,cap is 16384 
b[:len(b)+n] cost 0ms  ,len is 16124 , cap is 16384 

b length is 16124 , cap is 16384 
read to b from b(16124) to c(16384) , length is 260 
read cost 0 ms  ,len is 16124 , n is 260 ,cap is 16384 
b[:len(b)+n] cost 0ms  ,len is 16384 , cap is 16384 

b length is 16384 , cap is 16384 
append len=(16384) cap=(21760) add length 5376 
read to b from b(16384) to c(21760) , length is 5376 
read cost 0 ms  ,len is 16384 , n is 3836 ,cap is 21760 
b[:len(b)+n] cost 0ms  ,len is 20220 , cap is 21760 

b length is 20220 , cap is 21760 
read to b from b(20220) to c(21760) , length is 1540 
read cost 0 ms  ,len is 20220 , n is 1540 ,cap is 21760 
b[:len(b)+n] cost 0ms  ,len is 21760 , cap is 21760 

b length is 21760 , cap is 21760 
append len=(21760) cap=(28672) add length 6912 
read to b from b(21760) to c(28672) , length is 6912 
read cost 0 ms  ,len is 21760 , n is 2556 ,cap is 28672 
b[:len(b)+n] cost 0ms  ,len is 24316 , cap is 28672 

b length is 24316 , cap is 28672 
read to b from b(24316) to c(28672) , length is 4356 
read cost 0 ms  ,len is 24316 , n is 4356 ,cap is 28672 
b[:len(b)+n] cost 0ms  ,len is 28672 , cap is 28672 

b length is 28672 , cap is 28672 
append len=(28672) cap=(40960) add length 12288 
read to b from b(28672) to c(40960) , length is 12288 
read cost 0 ms  ,len is 28672 , n is 12288 ,cap is 40960 
b[:len(b)+n] cost 0ms  ,len is 40960 , cap is 40960 

b length is 40960 , cap is 40960 
append len=(40960) cap=(57344) add length 16384 
read to b from b(40960) to c(57344) , length is 16384 
read cost 0 ms  ,len is 40960 , n is 16384 ,cap is 57344 
b[:len(b)+n] cost 0ms  ,len is 57344 , cap is 57344 

b length is 57344 , cap is 57344 
append len=(57344) cap=(73728) add length 16384 
read to b from b(57344) to c(73728) , length is 16384 
read cost 0 ms  ,len is 57344 , n is 16384 ,cap is 73728 
b[:len(b)+n] cost 0ms  ,len is 73728 , cap is 73728 

b length is 73728 , cap is 73728 
append len=(73728) cap=(98304) add length 24576 
read to b from b(73728) to c(98304) , length is 24576 
read cost 1 ms  ,len is 73728 , n is 24576 ,cap is 98304 
b[:len(b)+n] cost 1ms  ,len is 98304 , cap is 98304 

b length is 98304 , cap is 98304 
append len=(98304) cap=(131072) add length 32768 
read to b from b(98304) to c(131072) , length is 32768 
read cost 1 ms  ,len is 98304 , n is 32768 ,cap is 131072 
b[:len(b)+n] cost 1ms  ,len is 131072 , cap is 131072 

b length is 131072 , cap is 131072 
append len=(131072) cap=(172032) add length 40960 
read to b from b(131072) to c(172032) , length is 40960 
read cost 1 ms  ,len is 131072 , n is 40960 ,cap is 172032 
b[:len(b)+n] cost 1ms  ,len is 172032 , cap is 172032 

b length is 172032 , cap is 172032 
append len=(172032) cap=(221184) add length 49152 
read to b from b(172032) to c(221184) , length is 49152 
read cost 1 ms  ,len is 172032 , n is 49152 ,cap is 221184 
b[:len(b)+n] cost 1ms  ,len is 221184 , cap is 221184 

b length is 221184 , cap is 221184 
append len=(221184) cap=(278528) add length 57344 
read to b from b(221184) to c(278528) , length is 57344 
read cost 1 ms  ,len is 221184 , n is 57344 ,cap is 278528 
b[:len(b)+n] cost 1ms  ,len is 278528 , cap is 278528 

b length is 278528 , cap is 278528 
append len=(278528) cap=(352256) add length 73728 
read to b from b(278528) to c(352256) , length is 73728 
read cost 1 ms  ,len is 278528 , n is 73728 ,cap is 352256 
b[:len(b)+n] cost 1ms  ,len is 352256 , cap is 352256 

b length is 352256 , cap is 352256 
append len=(352256) cap=(442368) add length 90112 
read to b from b(352256) to c(442368) , length is 90112 
read cost 1 ms  ,len is 352256 , n is 90112 ,cap is 442368 
b[:len(b)+n] cost 1ms  ,len is 442368 , cap is 442368 

b length is 442368 , cap is 442368 
append len=(442368) cap=(557056) add length 114688 
read to b from b(442368) to c(557056) , length is 114688 
read cost 2 ms  ,len is 442368 , n is 114688 ,cap is 557056 
b[:len(b)+n] cost 2ms  ,len is 557056 , cap is 557056 

b length is 557056 , cap is 557056 
append len=(557056) cap=(704512) add length 147456 
read to b from b(557056) to c(704512) , length is 147456 
read cost 3 ms  ,len is 557056 , n is 47299 ,cap is 704512 
b[:len(b)+n] cost 3ms  ,len is 604355 , cap is 704512 
index is 31

As the logs show  , the slice b expanded 31 times but only cost 3ms to read 604355 bytes payload.

4.  build a docker image and run on k8s .

content length is 604355
b length is 0 , cap is 512 
read to b from b(0) to c(512) , length is 512 
read cost 0 ms  ,len is 0 , n is 512 ,cap is 512 
b[:len(b)+n] cost 0ms  ,len is 512 , cap is 512 

b length is 512 , cap is 512 
append len=(512) cap=(896) add length 384 
read to b from b(512) to c(896) , length is 384 
read cost 0 ms  ,len is 512 , n is 384 ,cap is 896 
b[:len(b)+n] cost 0ms  ,len is 896 , cap is 896 

b length is 896 , cap is 896 
append len=(896) cap=(1408) add length 512 
read to b from b(896) to c(1408) , length is 512 
read cost 0 ms  ,len is 896 , n is 288 ,cap is 1408 
b[:len(b)+n] cost 0ms  ,len is 1184 , cap is 1408 

b length is 1184 , cap is 1408 
read to b from b(1184) to c(1408) , length is 224 
read cost 0 ms  ,len is 1184 , n is 224 ,cap is 1408 
b[:len(b)+n] cost 0ms  ,len is 1408 , cap is 1408 

b length is 1408 , cap is 1408 
append len=(1408) cap=(2048) add length 640 
read to b from b(1408) to c(2048) , length is 640 
read cost 0 ms  ,len is 1408 , n is 640 ,cap is 2048 
b[:len(b)+n] cost 0ms  ,len is 2048 , cap is 2048 

b length is 2048 , cap is 2048 
append len=(2048) cap=(3072) add length 1024 
read to b from b(2048) to c(3072) , length is 1024 
read cost 0 ms  ,len is 2048 , n is 1024 ,cap is 3072 
b[:len(b)+n] cost 0ms  ,len is 3072 , cap is 3072 

b length is 3072 , cap is 3072 
append len=(3072) cap=(4096) add length 1024 
read to b from b(3072) to c(4096) , length is 1024 
read cost 0 ms  ,len is 3072 , n is 1024 ,cap is 4096 
b[:len(b)+n] cost 0ms  ,len is 4096 , cap is 4096 

b length is 4096 , cap is 4096 
append len=(4096) cap=(5376) add length 1280 
read to b from b(4096) to c(5376) , length is 1280 
read cost 0 ms  ,len is 4096 , n is 1184 ,cap is 5376 
b[:len(b)+n] cost 0ms  ,len is 5280 , cap is 5376 

b length is 5280 , cap is 5376 
read to b from b(5280) to c(5376) , length is 96 
read cost 0 ms  ,len is 5280 , n is 96 ,cap is 5376 
b[:len(b)+n] cost 0ms  ,len is 5376 , cap is 5376 

b length is 5376 , cap is 5376 
append len=(5376) cap=(6912) add length 1536 
read to b from b(5376) to c(6912) , length is 1536 
read cost 0 ms  ,len is 5376 , n is 1536 ,cap is 6912 
b[:len(b)+n] cost 0ms  ,len is 6912 , cap is 6912 

b length is 6912 , cap is 6912 
append len=(6912) cap=(9472) add length 2560 
read to b from b(6912) to c(9472) , length is 2560 
read cost 0 ms  ,len is 6912 , n is 2464 ,cap is 9472 
b[:len(b)+n] cost 0ms  ,len is 9376 , cap is 9472 

b length is 9376 , cap is 9472 
read to b from b(9376) to c(9472) , length is 96 
read cost 0 ms  ,len is 9376 , n is 96 ,cap is 9472 
b[:len(b)+n] cost 0ms  ,len is 9472 , cap is 9472 

b length is 9472 , cap is 9472 
append len=(9472) cap=(12288) add length 2816 
read to b from b(9472) to c(12288) , length is 2816 
read cost 0 ms  ,len is 9472 , n is 1076 ,cap is 12288 
b[:len(b)+n] cost 0ms  ,len is 10548 , cap is 12288 

b length is 10548 , cap is 12288 
read to b from b(10548) to c(12288) , length is 1740 
read cost 2 ms  ,len is 10548 , n is 1740 ,cap is 12288 
b[:len(b)+n] cost 2ms  ,len is 12288 , cap is 12288 

b length is 12288 , cap is 12288 
append len=(12288) cap=(16384) add length 4096 
read to b from b(12288) to c(16384) , length is 4096 
read cost 2 ms  ,len is 12288 , n is 2356 ,cap is 16384 
b[:len(b)+n] cost 2ms  ,len is 14644 , cap is 16384 

b length is 14644 , cap is 16384 
read to b from b(14644) to c(16384) , length is 1740 
read cost 2 ms  ,len is 14644 , n is 1740 ,cap is 16384 
b[:len(b)+n] cost 2ms  ,len is 16384 , cap is 16384 

b length is 16384 , cap is 16384 
append len=(16384) cap=(21760) add length 5376 
read to b from b(16384) to c(21760) , length is 5376 
read cost 2 ms  ,len is 16384 , n is 2356 ,cap is 21760 
b[:len(b)+n] cost 2ms  ,len is 18740 , cap is 21760 

b length is 18740 , cap is 21760 
read to b from b(18740) to c(21760) , length is 3020 
read cost 2 ms  ,len is 18740 , n is 3020 ,cap is 21760 
b[:len(b)+n] cost 2ms  ,len is 21760 , cap is 21760 

b length is 21760 , cap is 21760 
append len=(21760) cap=(28672) add length 6912 
read to b from b(21760) to c(28672) , length is 6912 
read cost 2 ms  ,len is 21760 , n is 1076 ,cap is 28672 
b[:len(b)+n] cost 2ms  ,len is 22836 , cap is 28672 

b length is 22836 , cap is 28672 
read to b from b(22836) to c(28672) , length is 5836 
read cost 2 ms  ,len is 22836 , n is 5836 ,cap is 28672 
b[:len(b)+n] cost 2ms  ,len is 28672 , cap is 28672 

b length is 28672 , cap is 28672 
append len=(28672) cap=(40960) add length 12288 
read to b from b(28672) to c(40960) , length is 12288 
read cost 2 ms  ,len is 28672 , n is 3806 ,cap is 40960 
b[:len(b)+n] cost 2ms  ,len is 32478 , cap is 40960 

b length is 32478 , cap is 40960 
read to b from b(32478) to c(40960) , length is 8482 
read cost 191 ms  ,len is 32478 , n is 8482 ,cap is 40960 
b[:len(b)+n] cost 191ms  ,len is 40960 , cap is 40960 

b length is 40960 , cap is 40960 
append len=(40960) cap=(57344) add length 16384 
read to b from b(40960) to c(57344) , length is 16384 
read cost 191 ms  ,len is 40960 , n is 7902 ,cap is 57344 
b[:len(b)+n] cost 191ms  ,len is 48862 , cap is 57344 

b length is 48862 , cap is 57344 
read to b from b(48862) to c(57344) , length is 8482 
read cost 192 ms  ,len is 48862 , n is 8482 ,cap is 57344 
b[:len(b)+n] cost 192ms  ,len is 57344 , cap is 57344 

b length is 57344 , cap is 57344 
append len=(57344) cap=(73728) add length 16384 
read to b from b(57344) to c(73728) , length is 16384 
read cost 192 ms  ,len is 57344 , n is 7902 ,cap is 73728 
b[:len(b)+n] cost 192ms  ,len is 65246 , cap is 73728 

b length is 65246 , cap is 73728 
read to b from b(65246) to c(73728) , length is 8482 
read cost 192 ms  ,len is 65246 , n is 8482 ,cap is 73728 
b[:len(b)+n] cost 192ms  ,len is 73728 , cap is 73728 

b length is 73728 , cap is 73728 
append len=(73728) cap=(98304) add length 24576 
read to b from b(73728) to c(98304) , length is 24576 
read cost 192 ms  ,len is 73728 , n is 7902 ,cap is 98304 
b[:len(b)+n] cost 192ms  ,len is 81630 , cap is 98304 

b length is 81630 , cap is 98304 
read to b from b(81630) to c(98304) , length is 16674 
read cost 381 ms  ,len is 81630 , n is 16384 ,cap is 98304 
b[:len(b)+n] cost 381ms  ,len is 98014 , cap is 98304 

b length is 98014 , cap is 98304 
read to b from b(98014) to c(98304) , length is 290 
read cost 383 ms  ,len is 98014 , n is 290 ,cap is 98304 
b[:len(b)+n] cost 383ms  ,len is 98304 , cap is 98304 

b length is 98304 , cap is 98304 
append len=(98304) cap=(131072) add length 32768 
read to b from b(98304) to c(131072) , length is 32768 
read cost 383 ms  ,len is 98304 , n is 3806 ,cap is 131072 
b[:len(b)+n] cost 383ms  ,len is 102110 , cap is 131072 

b length is 102110 , cap is 131072 
read to b from b(102110) to c(131072) , length is 28962 
read cost 383 ms  ,len is 102110 , n is 28672 ,cap is 131072 
b[:len(b)+n] cost 383ms  ,len is 130782 , cap is 131072 

b length is 130782 , cap is 131072 
read to b from b(130782) to c(131072) , length is 290 
read cost 383 ms  ,len is 130782 , n is 290 ,cap is 131072 
b[:len(b)+n] cost 383ms  ,len is 131072 , cap is 131072 

b length is 131072 , cap is 131072 
append len=(131072) cap=(172032) add length 40960 
read to b from b(131072) to c(172032) , length is 40960 
read cost 383 ms  ,len is 131072 , n is 3806 ,cap is 172032 
b[:len(b)+n] cost 383ms  ,len is 134878 , cap is 172032 

b length is 134878 , cap is 172032 
read to b from b(134878) to c(172032) , length is 37154 
read cost 383 ms  ,len is 134878 , n is 12288 ,cap is 172032 
b[:len(b)+n] cost 383ms  ,len is 147166 , cap is 172032 

b length is 147166 , cap is 172032 
read to b from b(147166) to c(172032) , length is 24866 
read cost 384 ms  ,len is 147166 , n is 16384 ,cap is 172032 
b[:len(b)+n] cost 384ms  ,len is 163550 , cap is 172032 

b length is 163550 , cap is 172032 
read to b from b(163550) to c(172032) , length is 8482 
read cost 384 ms  ,len is 163550 , n is 8482 ,cap is 172032 
b[:len(b)+n] cost 384ms  ,len is 172032 , cap is 172032 

b length is 172032 , cap is 172032 
append len=(172032) cap=(221184) add length 49152 
read to b from b(172032) to c(221184) , length is 49152 
read cost 384 ms  ,len is 172032 , n is 24286 ,cap is 221184 
b[:len(b)+n] cost 384ms  ,len is 196318 , cap is 221184 

b length is 196318 , cap is 221184 
read to b from b(196318) to c(221184) , length is 24866 
read cost 576 ms  ,len is 196318 , n is 16384 ,cap is 221184 
b[:len(b)+n] cost 576ms  ,len is 212702 , cap is 221184 

b length is 212702 , cap is 221184 
read to b from b(212702) to c(221184) , length is 8482 
read cost 577 ms  ,len is 212702 , n is 8482 ,cap is 221184 
b[:len(b)+n] cost 577ms  ,len is 221184 , cap is 221184 

b length is 221184 , cap is 221184 
append len=(221184) cap=(278528) add length 57344 
read to b from b(221184) to c(278528) , length is 57344 
read cost 578 ms  ,len is 221184 , n is 7902 ,cap is 278528 
b[:len(b)+n] cost 578ms  ,len is 229086 , cap is 278528 

b length is 229086 , cap is 278528 
read to b from b(229086) to c(278528) , length is 49442 
read cost 579 ms  ,len is 229086 , n is 16384 ,cap is 278528 
b[:len(b)+n] cost 579ms  ,len is 245470 , cap is 278528 

b length is 245470 , cap is 278528 
read to b from b(245470) to c(278528) , length is 33058 
read cost 583 ms  ,len is 245470 , n is 33058 ,cap is 278528 
b[:len(b)+n] cost 583ms  ,len is 278528 , cap is 278528 

b length is 278528 , cap is 278528 
append len=(278528) cap=(352256) add length 73728 
read to b from b(278528) to c(352256) , length is 73728 
read cost 584 ms  ,len is 278528 , n is 73728 ,cap is 352256 
b[:len(b)+n] cost 584ms  ,len is 352256 , cap is 352256 

b length is 352256 , cap is 352256 
append len=(352256) cap=(442368) add length 90112 
read to b from b(352256) to c(442368) , length is 90112 
read cost 584 ms  ,len is 352256 , n is 17324 ,cap is 442368 
b[:len(b)+n] cost 584ms  ,len is 369580 , cap is 442368 

b length is 369580 , cap is 442368 
read to b from b(369580) to c(442368) , length is 72788 
read cost 584 ms  ,len is 369580 , n is 39730 ,cap is 442368 
b[:len(b)+n] cost 584ms  ,len is 409310 , cap is 442368 

b length is 409310 , cap is 442368 
read to b from b(409310) to c(442368) , length is 33058 
read cost 764 ms  ,len is 409310 , n is 16384 ,cap is 442368 
b[:len(b)+n] cost 764ms  ,len is 425694 , cap is 442368 

b length is 425694 , cap is 442368 
read to b from b(425694) to c(442368) , length is 16674 
read cost 769 ms  ,len is 425694 , n is 16384 ,cap is 442368 
b[:len(b)+n] cost 769ms  ,len is 442078 , cap is 442368 

b length is 442078 , cap is 442368 
read to b from b(442078) to c(442368) , length is 290 
read cost 770 ms  ,len is 442078 , n is 290 ,cap is 442368 
b[:len(b)+n] cost 770ms  ,len is 442368 , cap is 442368 

b length is 442368 , cap is 442368 
append len=(442368) cap=(557056) add length 114688 
read to b from b(442368) to c(557056) , length is 114688 
read cost 770 ms  ,len is 442368 , n is 3806 ,cap is 557056 
b[:len(b)+n] cost 770ms  ,len is 446174 , cap is 557056 

b length is 446174 , cap is 557056 
read to b from b(446174) to c(557056) , length is 110882 
read cost 770 ms  ,len is 446174 , n is 12288 ,cap is 557056 
b[:len(b)+n] cost 770ms  ,len is 458462 , cap is 557056 

b length is 458462 , cap is 557056 
read to b from b(458462) to c(557056) , length is 98594 
read cost 770 ms  ,len is 458462 , n is 16384 ,cap is 557056 
b[:len(b)+n] cost 770ms  ,len is 474846 , cap is 557056 

b length is 474846 , cap is 557056 
read to b from b(474846) to c(557056) , length is 82210 
read cost 771 ms  ,len is 474846 , n is 16384 ,cap is 557056 
b[:len(b)+n] cost 771ms  ,len is 491230 , cap is 557056 

b length is 491230 , cap is 557056 
read to b from b(491230) to c(557056) , length is 65826 
read cost 772 ms  ,len is 491230 , n is 16384 ,cap is 557056 
b[:len(b)+n] cost 772ms  ,len is 507614 , cap is 557056 

b length is 507614 , cap is 557056 
read to b from b(507614) to c(557056) , length is 49442 
read cost 777 ms  ,len is 507614 , n is 32768 ,cap is 557056 
b[:len(b)+n] cost 777ms  ,len is 540382 , cap is 557056 

b length is 540382 , cap is 557056 
read to b from b(540382) to c(557056) , length is 16674 
read cost 777 ms  ,len is 540382 , n is 16674 ,cap is 557056 
b[:len(b)+n] cost 777ms  ,len is 557056 , cap is 557056 

b length is 557056 , cap is 557056 
append len=(557056) cap=(704512) add length 147456 
read to b from b(557056) to c(704512) , length is 147456 
read cost 778 ms  ,len is 557056 , n is 32478 ,cap is 704512 
b[:len(b)+n] cost 778ms  ,len is 589534 , cap is 704512 

b length is 589534 , cap is 704512 
read to b from b(589534) to c(704512) , length is 114978 
read cost 778 ms  ,len is 589534 , n is 14821 ,cap is 704512 
b[:len(b)+n] cost 778ms  ,len is 604355 , cap is 704512 
index is 57

the index value here is 57 which means the slice b expanded 57 times during read payload.

As we know , the more times slice expansion , the more time process spend on read payload to slice b , because  the read operation can only read limit bytes contents one time, and with the length of b increases , read operation costs more time.

Another difference between them is , even to read the same length contents , the method on k8s also much slower than local.

I also tried to use io.Copy to replace io.ReadAll , it's true that the io.Copy faster than  io.ReadAll , but it doesn't helps us much. 

### What did you expect to see?
io.ReadAll shouldn't cost such a long time 

### Question
1. Is there any go env configs that may affect the io.ReadAll efficiency ？
2. Does the  io.ReadAll efficiency are different on different OS ?
3.  io.ReadAll sometimes fast but sometimes slow on the k8s env , what may caused that ?

**Comment by seankhliao** [comment]
1. no
2. no
3. There are many things that can affect performance on k8s (network, sender, cpu limits, etc), all outside the control of Go. io.ReadAll has to make a tradeoff between allocating too large slices and efficiency. If you care about allocations, you could use something like bytes.Buffer with a preallocated slice.

I don't see anything wrong with Go in this report.
