### ISSUE TITLE
x/pkgsite: package removal request for github.com/NeuraLegion/sectester-go@v1.0.0

### ISSUE THREAD

**Issue by derevnjuk** [golang/go#58852]
### What is the path of the package that you would like to have removed?

 

The package version is v1.0.0 under the following module path: [github.com/NeuraLegion/sectester-go](http://github.com/NeuraLegion/sectester-go)
 
 
### Are you the owner of this package?

Author, Owner, and actual Publisher
 
### What is the reason that you could not retract this package instead?

Due to the workflow misconfiguration, the initial development release has been tagged by v1.0.0 instead of the expected v0.1.0. We would like to remove this package version from the [pkg.go.dev](http://pkg.go.dev/) website, to avoid any confusion. Retracting the particular stable version, we will have to bump it up to v2.x.x. later on.

**Comment by seankhliao** [comment]
we can't remove singular versions for you.
you can publish v1.0.1 and retract both v1.0.0 and v1.0.1 at the same time

**Comment by derevnjuk** [comment]
@seankhliao, I am unable to release any version of the package without the reason, as the version number is automatically determined based on the changes made, following the semantic versioning (semver) guidelines. Is it possible to remove the whole package then?

**Comment by derevnjuk** [comment]
Should I open a new issue then?

**Comment by seankhliao** [comment]
the repo still exists, please use retract

**Comment by derevnjuk** [comment]
@seankhliao The package was published for the first time yesterday and is currently in the early stages of development. As such, the initial version should be labeled as v0.0.1 instead of v1.0.0. Since the package has yet to be utilized and is not expected to be used for the next few months, there doesn't seem to be any compelling reason why you couldn't remove the specific version or even the entire package from the registry.
