### ISSUE TITLE
runtime: crash when receiving multiple signals on C threads on NetBSD

### ISSUE THREAD

**Issue by minux** [golang/go#5885]
<pre>run the following program on netbsd/386:
package main

/*
#include &lt;signal.h&gt;
#include &lt;pthread.h&gt;

static void *thread(void *p) {
    (void)p;
    const int N = 100;
    int i;
    for (i = 0; i &lt; N; i++)
        pthread_kill(pthread_self(), SIGCHLD);
    return NULL;
}
void testSendSIG() {
    const int M = 10;
    pthread_t tid[M];
    int i;
    for (i = 0; i &lt; M; i++)
        pthread_create(&amp;tid[i], 0, thread, NULL);
    for (i = 0; i &lt; M; i++)
        pthread_join(tid[i], 0);
}
*/
import &quot;C&quot;

import (
    &quot;fmt&quot;
    &quot;os&quot;
    &quot;os/signal&quot;
    &quot;syscall&quot;
)

func main() {
    ch, wait := make(chan os.Signal), make(chan bool)
    signal.Notify(ch, syscall.SIGCHLD)
    go func() {
        wait2 := wait
        for {
            select {
            case v := &lt;-ch:
                fmt.Println(&quot;got&quot;, v)
                wait &lt;- false
            case &lt;-wait2:
                wait2 = nil
            }
        }
    }()
    wait &lt;- true
    C.testSendSIG()
    &lt;-wait
}

it will crash as follows:
SIGSEGV: segmentation violation
PC=0x3e8

goroutine 1 [syscall]:
main._Cfunc_testSendSIG(0x80b0ca0)
    command-line-arguments/_obj/_cgo_defun.c:43 +0x31
main.main()
    command-line-arguments/_obj/signal.cgo1.go:34 +0x14c

goroutine 3 [syscall]:
os/signal.loop()
    /home/builder/go.hg/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
    /home/builder/go.hg/src/pkg/os/signal/signal_unix.go:27 +0x31

goroutine 4 [select]:
main.func·001()
    command-line-arguments/_obj/signal.cgo1.go:23 +0x15c
created by main.main
    command-line-arguments/_obj/signal.cgo1.go:31 +0x12a

goroutine 5 [runnable]:
runtime.exitsyscall()
    /home/builder/go.hg/src/pkg/runtime/proc.c:1466 +0x109
runtime.cgocallbackg(0x18438c2c, 0x18438c3c, 0x4)
    /home/builder/go.hg/src/pkg/runtime/cgocall.c:244 +0x76
runtime.cgocallback_gofunc(0x0, 0x0)
    /home/builder/go.hg/src/pkg/runtime/asm_386.s:583 +0x5a
runtime.goexit()
    /home/builder/go.hg/src/pkg/runtime/proc.c:1289

eax     0x0
ebx     0x18439250
ecx     0x1
edx     0x0
edi     0x805c540
esi     0x18401780
ebp     0x813b160
esp     0x18438bd8
eip     0x3e8
eflags  0x10216
cs      0x1b
fs      0xab
gs      0xb3</pre>

**Comment by mikioh** [comment]
Note that this still crashes on NetBSD w/ go1.6beta1 + the fix for #14067.

**Comment by bradfitz** [comment]
All NetBSD bugs are on hold until there's a release later than NetBSD 7.1, which still had known issues fixed in NetBSD-current after 7.1.

**Comment by bradfitz** [comment]
Fixed by requiring NetBSD 8+ for Go 1.10.

Documentation bug is #22911
