### ISSUE TITLE
proposal: Go 2:  try-catch

### ISSUE THREAD

**Issue by yingshaoxo** [golang/go#58876]
I can't believe the whole go-lang community doesn't have any idea about try-catch

In the end, this useful module was written by someone else. And got so little stars...

https://github.com/fmorenovr/gotry

___

Think about this, if the go program accidentally have a small function that generates an unknown error, what would happen? the whole program will break!

But with try-catch in hand, no errors will cause a big problem.

```go
func simple_error_function() error {
	sum := 3
	for i := 1; i < 5; i++ {
		sum -= 1
		s := 2 / sum
		println(s)
	}
	return nil
}

func Test_error_handling(t *testing.T) {
	gotry.Try(func() {
		simple_error_function()
	}).Catch(func(e gotry.Exception) {
		// Print crash
		fmt.Println("Catch ---> exception catched:", e)
	}).Finally(func() {
		fmt.Println("Finally ---> This always print after all try block #1")
	})

	println("great")
}
```

**Comment by fzipp** [comment]
https://go.dev/doc/faq#exceptions
