### ISSUE TITLE
affected/package: fmt, math/big

### ISSUE THREAD

**Issue by yingshaoxo** [golang/go#58879]
Expect 3.145, but got 3.146

```golang
package main

import (
	"fmt"
	"log"
)

func main() {
	number := 3.14556
	expect_3_dot_145 := fmt.Sprintf("%.3f", number)

	log.Println(expect_3_dot_145)
}
```

<img width="1410" alt="image" src="https://user-images.githubusercontent.com/17190829/222959800-a7e6eb2a-07c7-4889-aa4c-6a45e2c174cf.png">

**Comment by seankhliao** [comment]
working as intended

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by yingshaoxo** [comment]
But as I tested

If I use 0.045 and 2 as the input

The result would be 0.04, which is wrong according to the last demo I give
to you

So, golang has bug.

For 0.045 and 2, it returns 0.04 (not round

For 3.14556 and 3, it returns 3.146 (round

**Comment by seankhliao** [comment]
floats are round to even

**Comment by yingshaoxo** [comment]
Is there any method could do the same thing in golang without round?

Kindly ask
