### ISSUE TITLE
cmd/compile: constant propagation on amd64

### ISSUE THREAD

**Issue by dvyukov** [golang/go#5887]
<pre>parent: 16892:ac183442f328 tip

The following program:

package main
func main() {
        println(foo(true))
}
func foo(f bool) int {
        if f {
                return 42
        }
        return -42
}

Generates the following code:

        println(foo(true))
  400c17:       48 c7 c0 01 00 00 00    mov    $0x1,%rax
  400c1e:       80 f8 00                cmp    $0x0,%al
  400c21:       74 1a                   je     400c3d &lt;main.main+0x3d&gt;
  400c23:       48 c7 c0 2a 00 00 00    mov    $0x2a,%rax
  400c2a:       48 89 04 24             mov    %rax,(%rsp)
  400c2e:       e8 7d ce 00 00          callq  40dab0 &lt;runtime.printint&gt;

The compiler can do constant propagation and generate just:
  400c2a:       48 89 04 24             mov    $0x2a,(%rsp)
  400c2e:       e8 7d ce 00 00          callq  40dab0 &lt;runtime.printint&gt;</pre>

**Comment by brtzsnr** [comment]
Here is another missed constant propagation which I believe is more common:

```go
package test
func S() int {
        a := 1
        a += 5
        if a > 1 {
                return 0
        }
        return 9
}      
```

Generated code is
```asm
        0x0000 00000 (a.go:2)   TEXT    "".S(SB), $0-8
        0x0000 00000 (a.go:2)   NOP
        0x0000 00000 (a.go:2)   NOP
        0x0000 00000 (a.go:2)   FUNCDATA        $0, gclocals·5184031d3a32a42d85027f073f873668(SB)
        0x0000 00000 (a.go:2)   FUNCDATA        $1, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
        0x0000 00000 (a.go:3)   MOVQ    $1, BX
        0x0007 00007 (a.go:4)   ADDQ    $5, BX
        0x000b 00011 (a.go:4)   NOP
        0x000b 00011 (a.go:5)   CMPQ    BX, $1
        0x000f 00015 (a.go:5)   JLE     27
        0x0011 00017 (a.go:6)   MOVQ    $0, "".~r0+8(FP)
        0x001a 00026 (a.go:6)   RET
        0x001b 00027 (a.go:8)   MOVQ    $9, "".~r0+8(FP)
        0x0024 00036 (a.go:8)   RET
```

There are two missed propagation: `a += 5` and `a > 1`. The whole function's body can be replaced with `return 9`.

Another example involving nil check:
```go
package test
func S() int {
        a := 0
        if &a == nil {
                return 0
        }
        return 9
}      
```

```asm
        0x0000 00000 (a.go:2)   TEXT    "".S(SB), $8-8
        0x0000 00000 (a.go:2)   SUBQ    $8, SP
        0x0004 00004 (a.go:2)   FUNCDATA        $0, gclocals·5184031d3a32a42d85027f073f873668(SB)
        0x0004 00004 (a.go:2)   FUNCDATA        $1, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
        0x0004 00004 (a.go:3)   MOVQ    $0, "".a(SP)
        0x000c 00012 (a.go:4)   LEAQ    "".a(SP), BX
        0x0010 00016 (a.go:4)   MOVQ    $0, BP
        0x0012 00018 (a.go:4)   CMPQ    BX, BP
        0x0015 00021 (a.go:4)   JNE     37
        0x0017 00023 (a.go:5)   MOVQ    $0, "".~r0+16(FP)
        0x0020 00032 (a.go:5)   ADDQ    $8, SP
        0x0024 00036 (a.go:5)   RET
        0x0025 00037 (a.go:7)   MOVQ    $9, "".~r0+16(FP)
        0x002e 00046 (a.go:7)   ADDQ    $8, SP
        0x0032 00050 (a.go:7)   RET
```

Again `&a == nil` is always false, so `a` is unused (dead store) so the whole function's body can be replaced with `return 9`.

**Comment by bradfitz** [comment]
@brtzsnr, which compiler version is that?

**Comment by brtzsnr** [comment]
I updated the comment.

**Comment by rsc** [comment]
SSA may help here.

**Comment by randall77** [comment]
These are all fixed on tip SSA.
(Except for the last example, where `a` is still initialized despite not being used.)
