### ISSUE TITLE
affected/package: gofmt

### ISSUE THREAD

**Issue by codpe** [golang/go#58878]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.19.4

</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?
Cant disable formating comments that ar parsed and used for code generation

**Comment by gophun** [comment]
Whatever you're trying to do (you didn't give an example) can probably be achieved in a different way without modifying gofmt.

**Comment by seankhliao** [comment]
working as intended
