### ISSUE TITLE
proposal: nfnt/resize: Pixel-perfect resizing

### ISSUE THREAD

**Issue by donmor** [golang/go#58880]
I'm looking for ways to resize an image pixel-perfectly, i.e. resize with no interpolation. If I resize a pixel art with `resize.Resize()`, I'll get a blurred image that wrecked by `NearestNeighbor`.

Can anyone tell me a way to do that? Or if possible, make a PR and put a dummy interpolating program in `nfnt/resize`, something like `resize.None`.

**Comment by mdlayher** [comment]
See https://github.com/golang/go/wiki/Questions.
