### ISSUE TITLE
x/sys/unix: syscall_unix.go - Recvmsg reports empty/wrong error value

### ISSUE THREAD

**Issue by rinor** [golang/go#58898]
### Does this issue reproduce with the latest release?
- yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOVERSION="go1.20.1"

</pre></details>

### What did you do?
```go
import (
	"golang.org/x/sys/unix"
)
...
retn, _, _, _, err = unix.Recvmsg(tunfd, msg[:], nil, 0)
```

### What did you expect to see?
```go
retn == -1
err != nil
```

### What did you see instead?
```go
retn == -1
err == nil
```
---
https://github.com/golang/sys/blob/494aa493ccb0c797af52f75ff7839a241bb26cdd/unix/syscall_unix.go#L356 is lacking error check 
```go
	n, oobn, recvflags, err = recvmsgRaw(fd, iov[:], oob, flags, &rsa)
	if rsa.Addr.Family != AF_UNSPEC {
		from, err = anyToSockaddr(fd, &rsa)
	}
```
vs
```go
	n, oobn, recvflags, err = recvmsgRaw(fd, iov[:], oob, flags, &rsa)
	if err == nil && rsa.Addr.Family != AF_UNSPEC {
		from, err = anyToSockaddr(fd, &rsa)
	}
```

**Comment by ianlancetaylor** [comment]
Can you show us a complete program that recreates the problem?  Thanks.

**Comment by rinor** [comment]
I'll try and figure out how to recreate that from the environment it happens since it depends on the socket state that affects `rsa.Addr.Family` , but from tests the behavior changes in this commit https://github.com/golang/sys/commit/51cd9980dadf015f085fdaa735da31d7242adc6d. Before that `rsa.Addr.Family != AF_UNSPEC` was no cheked in case of an error returned from `recvmsg` and probably with the code reorg that check was lost. FWIW the other functions "similar" to `Recvmsg` there have the correct check in place
- `Recvfrom` - https://github.com/golang/sys/blob/494aa493ccb0c797af52f75ff7839a241bb26cdd/unix/syscall_unix.go#L325
- `RecvmsgBuffers` - https://github.com/golang/sys/blob/494aa493ccb0c797af52f75ff7839a241bb26cdd/unix/syscall_unix.go#L377

**Comment by rinor** [comment]
This case was triggered by a "kernel" implementation bug that was wrongly changing the socket address family also in case of errors.
While I still think would be better to add that error check and unify the handling, for the time being I'm unable to provide correct code example that can trigger that branch.

Thank you.
