### ISSUE TITLE
x/build/cmd/coordinator: invalid SlowBots in `TRY=` comments are silently ignored

### ISSUE THREAD

**Issue by bcmills** [golang/go#58902]
In https://go-review.git.corp.google.com/c/go/+/465805/6#message-b69a437c43e08f518fc3ffb4de60cc525f9ee9ef, I typo'd a `TRY=` line, listing a valid builder name (`longtest`) along with an invalid one (`windows-awd64-longtest`).

The Gopher Robot ran only the `longtest` builder, and happily added a `TryBot-Result` along with a list of slowbots that included only the valid one.

Especially given that the `TryBot+1` now feeds into submitting auto-submit CLs, it should not ignore invalid builders. Instead, it should reply on the CL with an explicit error if the `TRY=` line contains an invalid name.

This is related to #41831, but perhaps easier to resolve.

(attn @golang/release)

**Comment by mauri870** [comment]
@gopherbot, assign @mauri870

**Comment by mauri870** [comment]
Looks like this is already deployed, a quick test shows that it is working as intended:

![image](https://github.com/golang/go/assets/10168637/2cf4d6c1-e4b5-4cdd-984d-7f29af0a5cfc)
