### ISSUE TITLE
x/pkgsite: package removal request for `gitlab.com/pygolo/pygolo`

### ISSUE THREAD

**Issue by cavokz** [golang/go#58916]
### What is the path of the package that you would like to have removed?

gitlab.com/pygolo/pygolo
 
### Are you the owner of this package?

Yes.
 
### What is the reason that you could not retract this package instead?

I learned about retracting only after I removed the git repository.

**Comment by hyangah** [comment]
@cavokz Sorry it's not convenient, but can you create a git repository again and publish a module for retraction?
And, leaving it as it is an option too. Removing from pkgsite is simply just hiding the package. The package is still available from proxy.golang.org.

**Comment by cavokz** [comment]
@hyangah, I resurrected the original pygolo repository (https://gitlab.com/pygolo/pygolo) and retracted all the published versions (v0.1.0-alpha and v0.1.0-alpha.2, the latter containing only the retraction of the first). This change is not reflected in https://pkg.go.dev/gitlab.com/pygolo/pygolo yet, don't know how to force the refresh.

Can we now get pygolo removed also from https://pkg.go.dev?

**Comment by findleyr** [comment]
Thank you for trying, @cavokz. It looks like all published versions have been successfully retracted, but pkg.go.dev now shows a pseudoversion as latest.

I will go ahead remove the module.

**Comment by findleyr** [comment]
This is done.

**Comment by cavokz** [comment]
Thanks!
