### ISSUE TITLE
cmd/go/mod - "go mod tidy" error `file name too long`

### ISSUE THREAD

**Issue by krasi-georgiev** [golang/go#58915]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/krasi/.cache/go-build"
GOENV="/home/krasi/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/krasi/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/krasi"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/krasi/src/github.com/Defi-Cartel/builder-geth/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build663349659=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

clone https://github.com/ethereum/go-ethereum
go mod tidy

results in:
```
github.com/ethereum/go-ethereum/tests/fuzzers/bn256 imports
        github.com/consensys/gnark-crypto/ecc/bn254: unzip /home/krasi/pkg/mod/cache/download/github.com/consensys/gnark-crypto/@v/v0.9.1-0.20230105202408-1a7a29904a7c.zip: open /home/krasi/pkg/mod/github.com/consensys/gnark-crypto@v0.9.1-0.20230105202408-1a7a29904a7c/internal/generator/addchain/1eed5b76b77315c55824fc3c6ad19eb92f19a5f5859d13f7e464428aa2c74d998d5ce788548db3d6059025d409f55414fd63967a0dcc8dc5259a2bdb6c8d4a860554784b1bcfbda16d0bd0d0a49d80678fcc7f0d0: file name too long
```

**Comment by bcmills** [comment]
That is a really impressively long filename. 😅
The `file name too long` message is probably a syscall error (`ENAMETOOLONG`).

That said, the last component of the filename seems to be only 170 characters, whereas `_POSIX_PATH_MAX` is 256 bytes (and even the Windows `MAX_PATH` is 260). So on systems that support `openat(2)`, it should succeed (compare https://go.dev/play/p/Ge7rAMxT_rw).

So I wonder: is something in the Go standard library failing to use `openat` where it is needed, or is your filesystem restricted to paths shorter than `_POSIX_PATH_MAX`?

**Comment by bcmills** [comment]
Indeed, I'm not able to reproduce this failure locally (on a Debian machine with `GOMODCACHE` on an `ext4` partition).

What does `df -Th $(go env GOMODCACHE)` report for your filesystem type?

**Comment by krasi-georgiev** [comment]
you are right the script executes fine under the root dir, but not under the home dir
```
df -Th $(go env GOMODCACHE)
Filesystem           Type      Size  Used Avail Use% Mounted on
/home/krasi/.Private ecryptfs  469G  322G  123G  73% /home/krasi
```

when I run the script on the root folder it does succeed

```
cd /
/ $ sudo su^C
/ $ sudo /usr/local/go/bin/go run main.go 
2023/03/07 19:10:51 Mkdir($PWD/a/b/c/d/e): <nil>
2023/03/07 19:10:51 Mkdir(a): <nil>
2023/03/07 19:10:51 Chdir(a)
2023/03/07 19:10:51 Mkdir(b): <nil>
2023/03/07 19:10:51 Chdir(b)
2023/03/07 19:10:51 Mkdir(c): <nil>
2023/03/07 19:10:51 Chdir(c)
2023/03/07 19:10:51 Mkdir(d): <nil>
2023/03/07 19:10:51 Chdir(d)
2023/03/07 19:10:51 Mkdir(e): <nil>
2023/03/07 19:10:51 Chdir(e)
/ $ ls
...// removed the other folders
drwxr-xr-x   3 root  4.0K Mar  7 19:10 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
drwxr-xr-x  22 root  4.0K Mar  7 19:10 ..
drwxr-xr-x  22 root  4.0K Mar  7 19:10 .
```

when running it on the home dir it doesn't, 

```
sudo /usr/local/go/bin/go run main.go 
2023/03/07 19:13:50 Mkdir($PWD/a/b/c/d/e): mkdir /home/krasi/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa: file name too long
2023/03/07 19:13:50 Mkdir(a): mkdir aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa: file name too long
2023/03/07 19:13:50 chdir aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa: file name too long

**Comment by krasi-georgiev** [comment]
look at this on encrypted drives the max length is 143 chars

https://unix.stackexchange.com/questions/32795/what-is-the-maximum-allowed-filename-and-folder-size-with-ecryptfs/32834#32834

**Comment by krasi-georgiev** [comment]
as a workaround, I used a symlink to another partition

Feel free to close if you don't think anything should be done in the mod command to compensate for that.

**Comment by bcmills** [comment]
A simpler workaround might be to explicitly set `GOMODCACHE` to point to a partition with a different filesystem.

(FWIW, https://bugs.launchpad.net/ecryptfs/+bug/344878/comments/126 seems to recommend ext4 native encryption as a preferred alternative.)

Since we seem to be in line with `_POSIX_PATH_MAX` I don't intend to pursue a workaround on the `cmd/go` side. Thanks for following up!
