### ISSUE TITLE
freebsd regression in 1.20.1- `os.Stat` shows `function not implemented`

### ISSUE THREAD

**Issue by JalonSolov** [golang/go#58914]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.6 linux/amd64

and

$ go version
go version go1.20.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
linux/amd64

### What did you do?

Test file `foo.go`:
```go
package main

import (
        "fmt"
        "os"
)

func main() {
        s, err := os.Stat("foo.go")
        if err != nil {
                fmt.Println(err)
        }
        fmt.Printf("%#v\n", s)
}
```

On system with Go 1.19.6:
```
$ GOOS=freebsd go build foo.go
$ scp foo <freebsd machine>:foo.19
```

On system with Go 1.20.1:
```
$ GOOS=freebsd go build foo.go
$ scp foo <freebsd machine>:foo.20
```

From either system:
```
$ scp foo.go <freebsd machine>:
```
On FreeBSD system:
```
$ ./foo.19
...
$ ./foo.20
```
### What did you expect to see?

Same (or at least very similar) output

### What did you see instead?

```
$ ./foo.19
&os.fileStat{name:"foo.go", size:175, mode:0x1a4, modTime:time.Time{wall:0x7d8ca00, ext:63813798690, loc:(*time.Location)(0x53d360)}, sys:syscall.Stat_t{Dev:0x3a00ff6c, Ino:0x4aebd51, Nlink:0x1, Mode:0x81a4, Padding0:0, Uid:0x257, Gid:0x7e, Padding1:0, Rdev:0x0, Atimespec:syscall.Timespec{Sec:1678201603, Nsec:752772000}, Mtimespec:syscall.Timespec{Sec:1678201890, Nsec:131648000}, Ctimespec:syscall.Timespec{Sec:1678201890, Nsec:131648000}, Birthtimespec:syscall.Timespec{Sec:-1, Nsec:0}, Size:175, Blocks:8, Blksize:4096, Flags:0x0, Gen:0x0, Spare:[10]uint64{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}}}
$ ./foo.20
stat foo.go: function not implemented
<nil>
$
```

**Comment by bcmills** [comment]
(attn @golang/freebsd)

**Comment by bcmills** [comment]
What version of FreeBSD are you running?
Per https://go.dev/wiki/MinimumRequirements#freebsd, current Go releases require FreeBSD 10 or higher.

**Comment by JalonSolov** [comment]
FreeBSD <server name> 11.1-RELEASE FreeBSD 11.1-RELEASE #0

**Comment by JalonSolov** [comment]
So Go 1.19 was supposed to be the last version of Go to support FreeBSD 11?

**Comment by paulzhol** [comment]
FreeBSD 11 support was dropped in Go 1.20, like mentioned in the ticket. 1.19 still has the compatibility shims for switching the syscall versions at runtime.
Go 1.18 was supposed to be the last, but we missed the merge window. So 1.19 is the last version with that code.

**Comment by paulzhol** [comment]
I've updated the [wiki](https://go.dev/wiki/MinimumRequirements#freebsd) to point to https://github.com/golang/go/wiki/FreeBSD#go-on-freebsd instead.
