### ISSUE TITLE
flag: Unexpected print result from flag.PrintDefaults() with grave accent mark (`).

### ISSUE THREAD

**Issue by dimandzhi** [golang/go#58921]
Using grave accent mark (`) in descriptions to flags produces unexpected flag.PrintDefaults() results. In case of two grave accent marks used all between them are moved next to flag name to the previous row. The desired result is achieved using three grave accent marks in a row. Tested on 1.19 and 1.20.  
Example:
~~~.go
desc := fmt.Sprintf("Place `foo` option, or maybe `bar`")
flag.StringVar(new(string), "missing", "something", desc)
desc = fmt.Sprintf("Place ```foo` option, or maybe `bar`")
flag.StringVar(new(string), "workaround", "something", desc)
flag.Parse()
flag.PrintDefaults()
// Result:
// -missing foo
//	Place foo option, or maybe `bar` (default "something")
// -workaround
//	Place `foo` option, or maybe `bar` (default "something")
~~~
AFAIK, this behavior is not documented.

**Comment by bcmills** [comment]
> AFAIK, this behavior is not documented.

https://pkg.go.dev/flag#PrintDefaults says:
>  The listed type … can be changed by placing a back-quoted name in the flag's usage string; the first such item in the message is taken to be a parameter name to show in the message and the back quotes are stripped from the message when displayed.

**Comment by dimandzhi** [comment]
Ah, I didn't quite understood what back-quoted name was, but example makes it clair. I should have been more attentive. Thank you for your time and sorry! Closing issue.
