### ISSUE TITLE
access: running TryBots

### ISSUE THREAD

**Issue by cuishuang** [golang/go#58946]
Hi,

Could I maybe have Gerrit access for running the TryBots ?

My Gerrit user ID there is 51518, email address is [imcusg@gmail.com](mailto:imcusg@gmail.com).

I'm trying to fix some bugs such as  https://go.dev/cl/474375 , https://go.dev/cl/473895, having this permission will save Reviewers time

Reference: https://go-review.googlesource.com/#/admin/groups/1030,members

See https://go.dev/wiki/GerritAccess

Thanks!

@dmitshur

**Comment by seankhliao** [comment]
cc @golang/release

**Comment by cagedmantis** [comment]
Hi Shuang,

Thank you for your contributions and for requesting Trybots access! I've added you to the `may-start-trybots` group, so you should be able to do so now.

As you've likely read at https://golang.org/wiki/GerritAccess#trybot-access-may-start-trybots, please be sure to at least skim CLs before starting a Trybot run.

Let us know if you have any questions or issues with it, and thanks again!

**Comment by cuishuang** [comment]
> Hi Shuang,
> 
> Thank you for your contributions and for requesting Trybots access! I've added you to the `may-start-trybots` group, so you should be able to do so now.
> 
> As you've likely read at https://golang.org/wiki/GerritAccess#trybot-access-may-start-trybots, please be sure to at least skim CLs before starting a Trybot run.
> 
> Let us know if you have any questions or issues with it, and thanks again!

Thank you so much!
