### ISSUE TITLE
encoding/json: marshall dont work on any lowercased field in struct

### ISSUE THREAD

**Issue by ErwanMAS** [golang/go#58956]
the field `name`  is excluded from the result because start with a lower case .

```
type ColorGroup struct {
		ID     int
		name   string
		Colors []string
	}
```

### Does this issue reproduce with the latest release?

yes

### What did you do?

a example , 99% inspired by the example from your documentation

https://go.dev/play/p/ZaxfyRsRg_g

### What did you expect to see?

`{"ID":1,"name":"Reds","Colors":["Crimson","Red","Ruby","Maroon"]}
`

### What did you see instead?

json result has only 2 fields 

`{"ID":1,"Colors":["Crimson","Red","Ruby","Maroon"]}
`

this issue is so obvious , that i think i miss a word in this documentation https://pkg.go.dev/encoding/json#Marshal 
but i read twice , and i did not anything

**Comment by ErwanMAS** [comment]
I just found this rule https://go.dev/ref/spec#Exported_identifiers , so it seem to apply to json marshalling .

Can you modify the documentation of marshall to add small few words about this  ?

**Comment by rittneje** [comment]
It already mentions this.

> Struct values encode as JSON objects. Each exported struct field becomes a member of the object, using the field name as the object key, unless the field is omitted for one of the reasons given below.

**Comment by erwan-mas-okcupid** [comment]
but with a link to   https://go.dev/ref/spec#Exported_identifiers , that will be better
