### ISSUE TITLE
x/tools/go/analysis: pkgsite documentation for golang.org/x/tools/go/analysis/passes/* often lacks details

### ISSUE THREAD

**Issue by hyangah** [golang/go#58950]
I am not sure if this is a feature request for pkgsite, or it's just because the go analysis analyzer code was structured in a way not friendly with go documentation. Analyzers often place the helpful details in Doc constant, but this long doc is hidden from documentation

https://pkg.go.dev/golang.org/x/tools/go/analysis/passes/nilness

![Screenshot 2023-03-09 at 9 10 51 AM](https://user-images.githubusercontent.com/4999471/224050682-c293e809-ffd5-4726-95c7-98f68e79b49d.png)

```
$ go doc
package nilness // import "golang.org/x/tools/go/analysis/passes/nilness"

Package nilness inspects the control-flow graph of an SSA function and reports
errors such as nil pointer dereferences and degenerate nil pointer comparisons.

const Doc = ...
var Analyzer = &analysis.Analyzer{ ... }

$ go doc Doc
```

Would be nice if the documentation page of analyzers presents sufficient details. 
The pattern I saw in similar situation was to generate the package doc (doc.go) from the types but not sure if that's the best way.

cc @adonovan @golang/tools-team

**Comment by adonovan** [comment]
I agree that doc.go makes sense. See https://go-review.googlesource.com/c/tools/+/474935 for a sketch of a starting point.

**Comment by seankhliao** [comment]
I wonder if that ExtractDoc function is something that could go in maybe the standard library `go/doc`?
It's something I've wanted a few times

**Comment by hyangah** [comment]
Thanks @adonovan 

https://go.dev/cl/474935's approach is

  * place the doc for an analyzer in the package document
  * extract the relevant section from the package document and wire it to `analysis.Analyzer.Doc`.
  * provide a helper function `ExtractDoc` to extract the section

  (+) One copy and place where the document is
  (-) To support multiple analyzers in one package, we may end up with some convention in the package documentation organization.
  (-) Some features available in comment doc (cross-reference, etc) may leak to the analyzer doc which.
     
I was originally thinking a different approach

  * have a tool to extract `analysis.Analyzer.Doc` contents
  * populate `doc.go` using the tool which can be automated with `go:generate`
  * may have a test that ensures consistency of doc.go.
  
  (+) No magic keyword or convention in the package documentation.
  (-) Two copies of the same contents.
  (-) Consistency between two copies is not automatically enforced.

**Comment by adonovan** [comment]
I think the benefit of having a single copy (that is automatically readable in pkgsite) probably offsets the risk of markup (e.g. cross-refs) being accidentally included in the plain text version. Perhaps we can apply the go/doc/comment parser and format such things, so we get the best of both worlds: HTML in the browser and plain text in the terminal?

I agree we need to support multiple analyzers. Perhaps we should require a section called `# Analyzer foo`, and make ExtractDoc(doc, "foo") fail if if doesn't find a section of that name.

**Comment by findleyr** [comment]
Looks good at master: https://pkg.go.dev/golang.org/x/tools/go/analysis/passes/nilness@master

Closing this as the work is done, and x/tools will automatically be released at some point.
