### ISSUE TITLE
x/website: blog post contains a typo

### ISSUE THREAD

**Issue by mkraft** [golang/go#58951]
Typo in blog post.

URL: https://go.dev/blog/integration-test-coverage

Sentence:
 
> This merge capability is also useful to combine results from different types of test runs, including runs from generated by other test harnesses.

Recommendation:

This merge capability is also useful to combine results from different types of test runs, including runs ~~from~~ generated by other test harnesses.

Alternatively:

This merge capability is also useful to combine results from different types of test runs, including runs from ~~generated by~~ other test harnesses.

**Comment by cagedmantis** [comment]
Thanks for reporting this @mkraft.
