### ISSUE TITLE
x/website: use of deprecated `math/rand.Seed` in the tutorial docs

### ISSUE THREAD

**Issue by RemoteSalad** [golang/go#58958]
### What is the URL of the page with the issue?
[https://go.dev/doc/tutorial/random-greeting](https://go.dev/doc/tutorial/random-greeting)
 
 
### What is your user agent?
 
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0
 
### Screenshot
 
![image](https://user-images.githubusercontent.com/98570330/224206834-cc55db77-3307-440c-90ee-4da71dde0555.png)

### What did you do?
 
Followed the introductory tutorials
 
### What did you expect to see?
 
n/a
 
### What did you see instead?

Code examples that produced warnings from the go-staticcheck linter based on #56319 or #54880

> rand.Seed has been deprecated since Go 1.20 and an alternative has been available since Go 1.0: Programs that call Seed and then expect a specific sequence of results from the global random source (using functions such as Int) can be broken when a dependency changes how much it consumes from the global random source. To avoid such breakages, programs that need a specific result sequence should use NewRand(NewSource(seed)) to obtain a random generator that other packages cannot access.  (SA1019)go-staticcheck

The math/rand module's [documentation](https://pkg.go.dev/math/rand#Seed)

**Comment by adityakode** [comment]
Can I work on this?
