### ISSUE TITLE
affected/package: "net/http" http.Error(w, "test", http.StatusMethodNotAllowed) newline at the end of the response message.

### ISSUE THREAD

**Issue by freexmonster** [golang/go#58961]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.20.2 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?
ubuntu 22.04 x64

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
I created a web server, I decided to describe the errors in requests. And got a newline after getting a request error.
`http.Error(w, "test", http.StatusMethodNotAllowed)`

`405    test /n <--- newline`

### What did you expect to see?
After the request, I expected to receive a response without a new line.

### What did you see instead?

I saw a newline at the end of the response.

**Comment by seankhliao** [comment]
working as expected
