### ISSUE TITLE
x/pkgsite: package removal request for `github.com/lca1/lattigo`

### ISSUE THREAD

**Issue by ChristianMct** [golang/go#58963]
### What is the path of the package that you would like to have removed?

`github.com/lca1/lattigo`
 
### Are you the owner of this package?

Yes.
 
### What is the reason that you could not retract this package instead?

The GitHub organization name has changed and the repository URL is not under our control anymore.

**Comment by bcmills** [comment]
https://github.com/lca1/lattigo currently redirects to `https://github.com/tuneinsight/lattigo`, and I believe that redirect will be followed by the module proxy.

You should be able to `retract` the versions for the prior path by publishing them in the `go.mod` file in the `github.com/tuneinsight/lattigo` repo.
