### ISSUE TITLE
cgo not picking up cpp or cc file for compilation

### ISSUE THREAD

**Issue by siara-cc** [golang/go#58962]
### What version of Go are you using (`go version`)?

<pre>
go version go1.20.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

I just installed `go` yesterday so I guess it should be the latest.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/arun/Library/Caches/go-build"
GOENV="/Users/arun/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/arun/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/arun/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.20.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/arun/git/Text_frequency_research/wip/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/h2/tw_svvd12hq7h3jspndldntr0000gn/T/go-build949305981=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I want to call a function defined in C++ so I am using cgo.  It works if my code is plain C, but not CPP.  It says in the doc `Any .cc, .cpp, or .cxx files will be compiled with the C++ compiler.`, but it does not pick up my .cpp file for compilation.  If I rename it to .c file it attempts to compile it.

I searched through www, the solution given is to #include the .cpp file above import "C", but if I do that it apparently uses the C compiler to compile the code included.

### What did you expect to see?

I expect any .cpp file in the same folder to be compiled and linked during build using the CXXFLAGS as mentioned in the doc.

### What did you see instead?

I am getting symbols not found because the .cpp file is not compiled and linked:

```
% go build
# siara.cc/main
/usr/local/go/pkg/tool/darwin_amd64/link: running clang++ failed: exit status 1
ld: warning: -no_pie is deprecated when targeting new OS versions
Undefined symbols for architecture x86_64:
  "_load_model", referenced from:
      __cgo_a9ef5f2dc645_Cfunc_load_model in 000001.o
     (maybe you meant: __cgo_a9ef5f2dc645_Cfunc_load_model)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by seankhliao** [comment]
please include example code of what you're doing.

**Comment by siara-cc** [comment]
This is not all the code, but the issue can be reproduced with this.  Before using this, fasttext lib to be installed using `brew install fasttext`.

main.go:

```go
package main

/*
#cgo CXXFLAGS: -std=c++11
#cgo LDFLAGS: -L/usr/local/lib -lstdc++ -lfasttext
#include <stdlib.h>
#include "go_fasttext.h"
//#include "go_fasttext.cpp"
*/
import "C"
import "unsafe"

func main() {
        model_name := C.CString("lid.176.bin")
        C.load_model(model_name)
        defer C.free(unsafe.Pointer(model_name))
}
```

go_fasttext.h:
```
void load_model(const char *model_name);
```

go_fasttext.cpp:
```
#include <stdio.h>     // fprintf
#include <stdlib.h>    // free
#include <fasttext/fasttext.h>
#include <string.h>
#include <string>
#include <sstream>

using namespace std;

fasttext::FastText ftext;

void load_model(const char *filename) {
    ftext.loadModel(string(filename));
}
```

If I do `go run main.go` I am getting `Undefined symbols` as shown in my previous comment.
If I uncomment `#include "go_fasttext.cpp`, it compiles it without -std=c++11 so the c++ code throws lot of errors.
If I use CPPFLAGS instead of CXXFLAGS, I get `error: invalid argument '-std=c++11' not allowed with 'C'`

I was able to make it work with a [shared lib here](https://github.com/siara-cc/FastText_Lang_bindings/tree/main/Golang), but I am trying to avoid the trouble of compiling shared lib separately etc.  I am unable to integrate the C++ library [fasttext](https://github.com/facebookresearch/fasttext) with my go program with the code shown above.

**Comment by nsrip-dd** [comment]
This is because cgo is going to build the stuff above `import "C"` in the Go file as **C** code. You're declaring a `void load_model(const char *)` function in the header, and when compiled as C the linker is going to look for a `load_model` symbol. But the actual function definition is in a **C++** file. It'll get compiled into a symbol like `_Z10load_modelPc` because C++ does [name mangling](https://en.wikipedia.org/wiki/Name_mangling). So the linker won't find the `load_model` symbol it's looking for. Hence the "undefined symbol" error. You'll need to add `extern "C"` to the `load_model` definition in your C++ file, so that when it's compiled the symbol will get a name that C understands. You'll need to do this whenever you want C++ code to be usable from C. See here for more on this: https://en.cppreference.com/w/cpp/language/language_linkage

**Comment by siara-cc** [comment]
Thank you, that worked !!  I appreciate the time taken to provide a detailed explanation.

I had tried `extern "C"` earlier as suggested by others out there, but was using `go run main.go` instead of running the executable created by `go build`.  I guess only `go build` includes the cpp file in build.

`go run main.go` still gives `Undefined symbols`.

**Comment by cherrymui** [comment]
`go run .` includes C code in the current directory. `go run main.go` only includes `main.go`.
