### ISSUE TITLE
x/build: `illumos-amd64` builder consistently failing

### ISSUE THREAD

**Issue by bcmills** [golang/go#58967]
The `illumos-amd64` builder has timed out testing `cmd/go` in every run since [CL 473697](https://go.dev/cl/473697).

Since the code involved in that change has literally no effect on `illumos-amd64`, I suspect that something has changed in either the builder itself or its configuration in `cmd/coordinator` to cause the test to become much slower.

**Comment by bcmills** [comment]
Looking at a few of the failures, it's not just `cmd/go` — there have also been timeouts in at least `runtime` and `testing`.

**Comment by jclulow** [comment]
As an initial note on this: nothing about the builder has changed to the best of my knowledge, unless AWS have moved it onto a defective or noisy host somehow.

**Comment by jclulow** [comment]
I will investigate!

**Comment by jclulow** [comment]
I believe disk space exhaustion was caused by the build-up of files in `$HOME/.cache/gopls`...

```
ncdu 1.15.1 ~ Use the arrow keys to navigate, press ? for help
--- /home/gobuild/.cache -------------------------------------------------------
                         /..
   18.1 GiB [##########] /gopls
  133.7 MiB [          ] /staticcheck
   40.8 MiB [          ] /go-build
   17.0 KiB [          ] /screentest

 Total disk usage:  18.3 GiB  Apparent size:   6.0 GiB  Items: 1406542
```

Should these files be deleted automatically after the job completes?  Can I delete them now?

**Comment by jclulow** [comment]
NB: in the interim I have activated the warm standby VM here which obviously doesn't (yet!) have a full disk, and appears to be processing jobs OK.

**Comment by bcmills** [comment]
@jclulow, it appears that the `illumos-amd64` builder is completely disconnected from the coordinator at the moment.

**Comment by jclulow** [comment]
> @jclulow, it appears that the `illumos-amd64` builder is completely disconnected from the coordinator at the moment.

Oh no!

I'm looking at it now, and the issue appears to be that the buildlet user has consumed all 10G of its quota.  (I set the quota to less than the VM disk size on this one, after the last builder filled the _entire_ disk in the machine making it harder to manage.)

I'm running `ncdu` at the moment, which is taking a while because there are a _lot_ of tiny files.  They are once again concentrated in `/home/gobuild/.cache/gopls` like last time.

@bcmills What is responsible for managing the contents of `$HOME/.cache/gopls`?  Should these files be deleted automatically after the job completes?  Can I delete them now?

**Comment by findleyr** [comment]
@heschi I thought we already did this in https://go.dev/cl/494297? Does that miss something?

**Comment by heschi** [comment]
Hm. Forgot about that. @jclulow, does this machine auto-update the buildlet?

**Comment by jclulow** [comment]
> Hm. Forgot about that. @jclulow, does this machine auto-update the buildlet?

We run the `stage0` binary under our service manager, so, if that auto-updates the buildlet then it should do that yes.  Indeed it was, when I looked at it, _trying_ to do that but the disk was full so it was unable.  It's also been offline for a while, it seems, so maybe that fix happened after the outage started?

I'm currently clearing out `.cache/gopls` to make room and I'll kick it off after that and we'll see!

**Comment by jclulow** [comment]
I have re-enabled the thing and it obtained a new buildlet and is ostensibly doing work now.
