### ISSUE TITLE
x/pkgsite: package removal request for pkg.berachain.dev/polaris

### ISSUE THREAD

**Issue by itsdevbear** [golang/go#58974]
pkg.berachain.dev/polaris

 

Just the one above.
 
 
### Are you the owner of this package?

Yes: github.com/berachain/polaris
 
### What is the reason that you could not retract this package instead?

We are getting a dependency conflict since pkg.berachain.dev/polaris shares a prefix with other packages we need to utilize.

i.e pkg.berachain.dev/polaris/build,eth etc.

pkg.go.dev won't update to see the new packages that are being pushed up https://pkg.berachain.dev/ since it thinks those packages are folders in the root package.

**Comment by seankhliao** [comment]
Your go-import meta directives look wrong:
from https://go.dev/ref/mod#vcs-find

> ```
> <meta name="go-import" content="root-path vcs repo-url">
> ```
> root-path is the repository root path, the portion of the module path that corresponds to the repository’s root directory. It must be a prefix or an exact match of the requested module path. If it’s not an exact match, another request is made for the prefix to verify the <meta> tags match.

While your response contains:

> ```
> <meta name="go-import" content="pkg.berachain.dev/polaris/build git https://github.com/berachain/polaris">
> ```

**Comment by itsdevbear** [comment]
@seankhliao resolved. Do I need to wait for pkg.go.dev to update?

**Comment by itsdevbear** [comment]
Updated tags  @seankhliao 

```
<title>pkg.berachain.dev/polaris/playground</title>
<meta name="go-import" content="pkg.berachain.dev/polaris git https://github.com/berachain/polaris">
<meta name="go-source" content="pkg.berachain.dev/polaris https://github.com/berachain/polaris https://github.com/berachain/polaris/tree/main{/dir} https://github.com/berachain/polaris/blob/main{/dir}/{file}#L{line}">
<style>
```

**Comment by seankhliao** [comment]
getting the module should just work, eg https://pkg.go.dev/pkg.berachain.dev/polaris/eth
