### ISSUE TITLE
os: Truncate() on a non-existent file will create a file on Windows

### ISSUE THREAD

**Issue by jfantinhardesty** [golang/go#58977]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.2 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\jfan\AppData\Local\go-build
set GOENV=C:\Users\jfan\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\jfan\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\jfan\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.20.2
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=C:\Users\jfan\code\lyvecloudfuse\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\jfan\AppData\Local\Temp\go-build1326796536=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

If you truncate a non-existent file with os.Truncate on Linux a no such file or directory error is given. On Windows, however, a file will be created and the error will be nil.

Here is a link to an application https://go.dev/play/p/SoUjXmpP0Ii that behaves as expected on Linux. It correctly gives a no such file or directory error. However, if you run it on Windows, you will not see any errors and a file will be created. Here is the test code to run.

<pre>
package main

import (
	"fmt"
	"os"
)

func main() {
	err := os.Truncate("./testfile", 1)
	fmt.Println("Expect error to be no such file or directory and error is :", err)

	_, err = os.ReadFile("./testfile")
	fmt.Println("Expect error to be no such file or directory and error is :", err)
}
</pre>

### What did you expect to see?

The behavior on Windows should be the same as it is on Linux. Since no file exists, it should give a no such file or directory error.

### What did you see instead?

On Windows, no error is given and a file is created.

**Comment by bcmills** [comment]
(CC @golang/windows)

**Comment by alexbrainman** [comment]
> The behavior on Windows should be the same as it is on Linux.

Why should Windows program behave the same as Linux?

Alex

**Comment by icholy** [comment]
@alexbrainman that's kind of the point of the os package.

**Comment by alexbrainman** [comment]
> @alexbrainman that's kind of the point of the os package.

@icholy

If you read `os.Truncate` documentation, it does not say that the function will fail, if the file does not exists.

I suspect that authors of the `os.Truncate` code decided that this behaviour is not important enough to implement / document.

Alex

**Comment by icholy** [comment]
@alexbrainman luckily, we're not bound by the unspecified documentation.

**Comment by qmuntal** [comment]
> The behavior should be consistent across platforms unless there is a well-defined platform-specific behavior that would lead a Go user to expect otherwise.

AFAIK, the only well-defined Windows api that truncate files referenced by file name and not by handler is `fsutil file seteof <filename> <length>` ([docs](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/fsutil-file)). It returns an error when the file name is not found:

```cmd
$ fsutil file seteof foo.txt 2
Error:  The system cannot find the file specified.
```
