### ISSUE TITLE
x/website: integration coverage blog post format issue

### ISSUE THREAD

**Issue by crisman** [golang/go#58981]
### What did you do?

View the new blog post at 
https://go.dev/blog/integration-test-coverage

### What did you expect to see?

A two line code block listing for "these two additional lines".

### What did you see instead?

```
<p>./mdtool.exe +ty testdata/README.md  &gt; /dev/null
./mdtool.exe +ta &lt; testdata/README.md  &gt; /dev/null</p>
```

which renders as one line without a code block on the web page.

**Comment by crisman** [comment]
Well, that's what I get for not looking first.  Seems to be a fix already in Gerrit:
https://go-review.googlesource.com/c/website/+/474876

**Comment by cagedmantis** [comment]
Thanks for the report. It's been fixed in the CL you mentioned.
