### ISSUE TITLE
proposal: Flags/args passing in `exec.Command` affected/package: os/exec

### ISSUE THREAD

**Issue by thejanasatan** [golang/go#58985]
Problem:
1. When executing Go programs from other Go programs, the flags need to be passed before arguments. This can cause developer errors.
2. There are examples of Go code creating slices of strings or functions that return arguments for a given command based on some config. This could be as easy as creating and configuring an `exec.Cmd` with the right flags and arguments.

I haven't thought about this API too much - just leaving this here for everyone's thoughts and suggestions.

Possible solution:

```golang

cmd := exec.Command("path/to/program")
cmd.SetFlag("flag", "value")
cmd.SetBoolFlag("boolflag")

if someconfig {
    cmd.SetFlag("optional", "value")
}

cmd.Args("arg1", "arg2")

err := cmd.Run()
```

**Comment by seankhliao** [comment]
we're not going to social case some go programs with a particular convention of flag/argument passing in os/exec
