### ISSUE TITLE
affected/package: 

### ISSUE THREAD

**Issue by jorgeupx** [golang/go#59009]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.19.5

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Jorge\AppData\Local\go-build
set GOENV=C:\Users\Jorge\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Jorge\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Jorge\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.19.5
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\Jorge\Documents\GitHub\Zalabox\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\Jorge\AppData\Local\Temp\go-build3365244248=/tmp/go-build -gno-record-gcc-switches 

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

For some reasons, 90% of the time I'm trying to build with golang I get the following error:

open C:\Users\Jorge\AppData\Local\Temp\go-build156064299\b001\exe\a.out.exe: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso

### What did you expect to see?

A successful build

### What did you see instead?

This error, which haunts me in every golang project I do, it's not caused by my computer since it happens in my new PC and older laptop, also tried adding a VS extension which seemed to solve the issue for others, but didnt work for my case.

**Comment by jorgeupx** [comment]
> Could you share the command(s) you run for building the program, and the full error message? Also, would it be possible to try Go 1.20.2? Thanks.

I just do go build, and it won't work with the latest update either

**Comment by cherrymui** [comment]
What program do you build? Could you share the complete error message?
Also, if you have antivirus software installed, could you try turning it off? Thanks.

**Comment by jorgeupx** [comment]
> What program do you build? Could you share the complete error message?
> 
> Also, if you have antivirus software installed, could you try turning it off? Thanks.

Sorry for delayed response, I'm using VSCODE, but no matter the program I will still get this error, tried goland as well, and I don't have any antivirus enabled as of now
