### ISSUE TITLE
"if" have very weird semantic 

### ISSUE THREAD

**Issue by LLyaudet** [golang/go#59006]
### What version of Go are you using (`go version`)?

<pre>
$ go version
I'm doing the tour here https://go.dev/
I assume it is 1.20.2
</pre>

### Does this issue reproduce with the latest release?
I think so.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
must be Linux as it was the output of some previous snippet of the tour
</pre></details>

### What did you do?

I'm doing this exercise :
https://go.dev/tour/methods/23

I first coded this (plus debug code since it did not work) :

```go
package main

import (
	//"fmt"
	"io"
	"os"
	"strings"
)

type rot13Reader struct {
	r io.Reader
	mybuffer []byte
}

func (rot13 rot13Reader) Read(b []byte) (int, error) {
	if rot13.mybuffer == nil {
		rot13.mybuffer = make([]byte, 1)
	}
	_, err := rot13.r.Read(rot13.mybuffer)
	if err == io.EOF {
		return 0, err
	}
	result := rot13.mybuffer[0]
	// fmt.Printf("Before : %v\n", result)
	if (result >= 'a' && result <= 'm') || (result >= 'A' && result <= 'M') {
		// fmt.Println("Increase")
		result = result + 13
	}
	if (result >= 'n' && result <= 'z') || (result >= 'N' && result <= 'Z') {
		//fmt.Println("Decrease")
		result = result - 13
	}
	// fmt.Printf("After : %v\n", result)
	b[0] = result
	return 1, nil
}

func main() {
	s := strings.NewReader("Lbh penpxrq gur pbqr!")
	r := rot13Reader{r:s}
	io.Copy(os.Stdout, &r)
}

```
but it failed.

Then I coded that code that works fine :
```go
package main

import (
	//"fmt"
	"io"
	"os"
	"strings"
)

type rot13Reader struct {
	r io.Reader
	mybuffer []byte
}

func (rot13 rot13Reader) Read(b []byte) (int, error) {
	if rot13.mybuffer == nil {
		rot13.mybuffer = make([]byte, 1)
	}
	_, err := rot13.r.Read(rot13.mybuffer)
	if err == io.EOF {
		return 0, err
	}
	result := rot13.mybuffer[0]
	// fmt.Printf("Before : %v\n", result)
	switch {
	case (result >= 'a' && result <= 'm') || (result >= 'A' && result <= 'M'):
		// fmt.Println("Increase")
		result = result + 13
	case (result >= 'n' && result <= 'z') || (result >= 'N' && result <= 'Z'):
		//fmt.Println("Decrease")
		result = result - 13
	default:
	}
	// fmt.Printf("After : %v\n", result)
	b[0] = result
	return 1, nil
}

func main() {
	s := strings.NewReader("Lbh penpxrq gur pbqr!")
	r := rot13Reader{r:s}
	io.Copy(os.Stdout, &r)
}

```

### What did you expect to see?

Both code should work.

### What did you see instead?

Only the code with switch works and returns "You cracked the code!"
The code with if returns "Lbh ceacked ghe cbde!".
For some values, it goes through both if (Increase then decrease).
It makes no sense

**Comment by LLyaudet** [comment]
In case someone pretends it is hard to read, the bug is just on those lines :
How is it possible that this :
```go
	if (result >= 'a' && result <= 'm') || (result >= 'A' && result <= 'M') {
		// fmt.Println("Increase")
		result = result + 13
	}
	if (result >= 'n' && result <= 'z') || (result >= 'N' && result <= 'Z') {
		//fmt.Println("Decrease")
		result = result - 13
	}
```
is not equivalent to this :
```go
	switch {
	case (result >= 'a' && result <= 'm') || (result >= 'A' && result <= 'M'):
		// fmt.Println("Increase")
		result = result + 13
	case (result >= 'n' && result <= 'z') || (result >= 'N' && result <= 'Z'):
		//fmt.Println("Decrease")
		result = result - 13
	default:
	}
```
The two conditions of the "if" are mutually exclusive.

**Comment by randall77** [comment]
This is not a bug. The modification of `result` makes the two not equivalent. Or maybe you want to use `else if`?
Please see https://go.dev/wiki/Questions for a good list of places to get help.

**Comment by LLyaudet** [comment]
Thanks XD It was right under my eyes :D 
I did try with else if but like this on a separate line :
```go
	else if (result >= 'n' && result <= 'z') || (result >= 'N' && result <= 'Z') {
		//fmt.Println("Decrease")
		result = result - 13
	}
```
(and also elseif and elif)
Since I had a syntax error, I tried something else and made a stupid error.
