### ISSUE TITLE
Float64 casting issue

### ISSUE THREAD

**Issue by Tang8330** [golang/go#59011]
### What version of Go are you using (`go version`)?
1.20

<pre>
$ go version
</pre>

### Does this issue reproduce with the latest release?
Seems like it has been here for a while.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

I'm testing large numbers (in the range of 2^63) and whenever we are casting it into Float, it seems to be losing precision. Please see the Go playground example.

https://go.dev/play/p/jor5bW97ZyV

### What did you see instead?

Large number got incremented by 2, from `9223372036854775806` to `9223372036854775808`. It's weird because float64 should be able to handle larger numbers. As you can see from [math/const.go](https://go.dev/src/math/const.go)

```golang
MaxFloat64             = 0x1p1023 * (1 + (1 - 0x1p-52)) // 1.79769313486231570814527423731704356798070e+308
```

**Comment by randall77** [comment]
That's how floating point works. Above `1<<53`, the delta between representations is more than one.
Play with `math.NextAfter` in that range.

**Comment by Tang8330** [comment]
Are there any reference documentation around the `1<<53`? Also, any documentation around `math.NextAfter`?

**Comment by randall77** [comment]
https://en.wikipedia.org/wiki/IEEE_754

`math.Nextafter` is documented in its godoc:
```
Nextafter returns the next representable float64 value after x towards y.
```
Seems pretty straightforward once you know what a "representable float64 value" is.

**Comment by ianlancetaylor** [comment]
https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html
