### ISSUE TITLE
x/mobile: gomobie bind go1.18 package, the api is suspend ...

### ISSUE THREAD

**Issue by izouxv** [golang/go#59020]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.2 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
yes 

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Volumes/Vault/DEV/xvm/golang/default/gopath/pkg/mod"
GOOS="darwin"
GOPATH="/Volumes/Vault/DEV/xvm/golang/default/gopath"
GOPROXY="https://goproxy.cn,direct"
GOROOT="/Volumes/Vault/DEV/xvm/golang/default"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Volumes/Vault/DEV/xvm/golang/default/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.18.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/lw/cfz6lhfn1zv6mld4_6zs5s680000gn/T/go-build3898754961=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

gomobile latest version, git hash: e0f5769 
xcode: 14.1
macOS: 13.1

gomobile bind -ldflags="-w -s" -work -target=macos 

it can build a framework, but if it is bind a go package with go.mod version 1.17, the framework no problem,
if it build a go package with go.mod version 1.18, and then all apis will suspend in a xcode project 

go 1.17,  no problem
go 1.18 and above, all api is suspend

**Comment by izouxv** [comment]
xcode: 14.1

**Comment by cherrymui** [comment]
Could you clarify what you mean by "all apis will suspend in a xcode project"? Does it fail to build? Fail to run? How do you build or run it in an Xcode project? Thanks.

**Comment by izouxv** [comment]
> 
i can build a macos xcframework with the latest gomobile, and import to a macos project.
if the go package' version is 1.17, every is ok
if the go package' version is 1.18, i debug the macos project, Call the go api and the program will get stuck

gomobile bind -ldflags="-w -s" -work -target=macos

1.18，call go api，program will get stuck
1.17，every is fine

**Comment by izouxv** [comment]
@cherrymui

**Comment by seankhliao** [comment]
note we no longer support 1.17 or 1.18

**Comment by izouxv** [comment]
go 1.20, the error still exist

**Comment by cherrymui** [comment]
Thanks. How do you run the program? On an iOS device? On a simulator? Device connected to Xcode?

**Comment by izouxv** [comment]
no, i run a macos program, not a ios program. 
i use the follow cmd to build xcframework 

gomobile bind -ldflags="-w -s" -work -target=macos

and, the gomobile is also support macos target

```
gomobile bind  --help
usage: gomobile bind [-target android|ios|iossimulator|macos|maccatalyst] [-bootclasspath <path>] [-classpath <path>] [-o output] [build flags] [package]
```

**Comment by izouxv** [comment]
-_-
