### ISSUE TITLE
x/pkgsite: 

### ISSUE THREAD

**Issue by ghostsquad** [golang/go#59036]
### What is the URL of the page with the issue?
https://pkg.go.dev/sort

### What is your user agent?

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0

### Screenshot

![image](https://user-images.githubusercontent.com/903488/225091574-f6e23482-f244-4de5-b8f3-9230511ece41.png)

![image](https://user-images.githubusercontent.com/903488/225091490-bfb9a7ac-2335-453e-8744-bf1fdcc20237.png)

### What did you do?

Viewed the page, looking for the package-level `Reverse` function.

### What did you expect to see?

`sort.Reverse` is a package-level function that should be listed on this page, in the index and in the `functions` section.

### What did you see instead?

It's not listed in the index, nor in the functions section. Instead I found the definition of it under `types` (which it is not a `type`).

https://pkg.go.dev/sort#Reverse

![image](https://user-images.githubusercontent.com/903488/225092397-921e0b80-418e-4ba1-af49-de08a7bcdeae.png)

**Comment by rsc** [comment]
Constructors are listed under their types. Reverse is a constructor for an Interface.

**Comment by ghostsquad** [comment]
> Constructors are listed under their types. Reverse is a constructor for an Interface.
> 

It can't be a constructor, as it also has a parameter of the same type it produces.
