### ISSUE TITLE
reflect: reflect.StructOf fields with Anonymous=true has not got Their func

### ISSUE THREAD

**Issue by ssbeatty** [golang/go#59046]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.5 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\wang\AppData\Local\go-build
set GOENV=C:\Users\wang\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\wang\go\pkg\mod
set GONOPROXY=*.gitlab.com,*.gitee.com
set GONOSUMDB=*.gitlab.com,*.gitee.com
set GOOS=windows
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\PROJECTS\GO\gateway_test\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\wang\AppData\Local\Temp\go-build881389354=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

I have a piece of code that has unexpected execution results
refer to the example in https://github.com/golang/go/blob/9ae97f8b8b07c63d354ac41cd37771d87c679df7/src/reflect/all_test.go#L5920

```go
package main

import (
	"bytes"
	"reflect"
	"time"
)

func main() {
	tt := reflect.StructOf([]reflect.StructField{
		{Name: "Time", Type: reflect.TypeOf(time.Time{}), Anonymous: true},
	})

	if _, present := tt.MethodByName("After"); present {
		println("tt has After func")
	} else {
		println("tt has not After func")
	}

	bt := reflect.StructOf([]reflect.StructField{
		{Name: "Buffer", Type: reflect.TypeOf(bytes.Buffer{}), Anonymous: true},
	})

	if _, present := bt.MethodByName("Write"); present {
		println("bt has Write func")
	} else {
		println("bt has not Write func")
	}
}

```

### What did you expect to see?
```go
// output
// tt has After func
// bt has Write func
```

### What did you see instead?
```go
// output
// tt has After func
// bt has not Write func
```

**Comment by ShawnHXH** [comment]
Here's the methods signature of Time.After and Buffer.Write:

https://github.com/golang/go/blob/71f82df19a7595b422d9dbc7d05530bd824a9114/src/bytes/buffer.go#L175

https://github.com/golang/go/blob/71f82df19a7595b422d9dbc7d05530bd824a9114/src/time/time.go#L250

You can see their receivers are not the same type,  if you expect to see `"bt has Write func"`, change type of `Buffer` to `*Buffer`:

```go
bt := reflect.StructOf([]reflect.StructField{
	{Name: "Buffer", Type: reflect.PtrTo(reflect.TypeOf(bytes.Buffer{})), Anonymous: true},  // <=
})
```

**Comment by ssbeatty** [comment]
Thanks
