### ISSUE TITLE
sum.golang.org: 404 on pseudo-version for a specific commit

### ISSUE THREAD

**Issue by zephyrtronium** [golang/go#59042]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

n/a

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/branden/.cache/go-build"
GOENV="/home/branden/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/branden/go/pkg/mod"
GONOPROXY="*.mycompany.net"
GONOSUMDB="*.mycompany.net"
GOOS="linux"
GOPATH="/home/branden/go"
GOPRIVATE="*.mycompany.net"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/branden/work/snip/pdtets/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build738594437=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

`curl https://sum.golang.org/lookup/github.com/pdfcpu/pdfcpu@v0.4.1-0.20230312101853-a410fdc32533`

Or, run https://go.dev/play/p/VbPSk4VnykD, or `go get github.com/pdfcpu/pdfcpu@master`, or `go mod download` or `go run .` with the go.mod in the playground link.

### What did you expect to see?

Successfully get the dependency's info from sum.golang.org. `GOSUMDB=off GOPROXY=direct go mod download` does complete after some seconds.

### What did you see instead?

Usually `not found: `. Sometimes `not found: fetch timed out`.

#57185 is possibly related. The commit we are trying to use was pushed two days ago, and we have been unable to fetch it for over an hour, so it does not appear to be #42809. The target repo is not unusually large, so it does not appear to be #56174.

Also, `curl https://sum.golang.org/lookup/github.com/pdfcpu/pdfcpu@v0.4.0` completes with no issue.

**Comment by cherrymui** [comment]
cc @golang/tools-team

**Comment by zephyrtronium** [comment]
Looking into it more, it seems the repo is unusually large after all, at about 461 MB under .git. This probably is #56174 after all. Closing as a dup.
