### ISSUE TITLE
runtime.asyncPreempt use much time

### ISSUE THREAD

**Issue by LeGamerDc** [golang/go#59045]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

i dont know

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/dongcheng/.cache/go-build"
GOENV="/home/dongcheng/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go1.18"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go1.18/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3091739208=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

our code do a logic in every second, sometimes it run very slow. we found that from profile when it run slow, most of time is doing runtime.asyncPreempt (preempt_amd64.s:7  PUSHQ BP )

### What did you expect to see?

process run smooth in every run.

### What did you see instead?

somtimes, i run very slow

here is the flamegraph

![profile315](https://user-images.githubusercontent.com/86505352/225191924-79d9f330-2ca9-4584-9a7b-9b665a22b7c1.jpg)

**Comment by seankhliao** [comment]
sorry, we no longer support 1.18
