### ISSUE TITLE
x/pkgsite: Support pseudoversion semver-timestamp-commit_hash on about pages

### ISSUE THREAD

**Issue by juspence** [golang/go#59054]
### What is the URL of the page with the issue?
https://pkg.go.dev/about#adding-a-package (if a doc bug)
https://pkg.go.dev/cloud.google.com/go@v0.102.2-0.20220627142403-5be6d33a57cc (if a code bug)

### What is your user agent?
Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0

### Screenshot
![Screenshot from 2023-03-15 16-08-27](https://user-images.githubusercontent.com/87657842/225370906-022b959d-d58d-47b7-9002-6e9d76d1d096.png)

### What did you do?
I visited the below pages, which have version info and a downloadable artifact like I expect:
https://proxy.golang.org/cloud.google.com/go/@v/v0.102.2-0.20220627142403-5be6d33a57cc.info
https://proxy.golang.org/cloud.google.com/go/@v/v0.102.2-0.20220627142403-5be6d33a57cc.zip

I also visited https://pkg.go.dev/cloud.google.com/go@v0.102.2-0.20220627142403-5be6d33a57cc, which does not have any information about this package version.

Note that ```v0.102.2-0.20220627142403-5be6d33a57cc``` is still a valid semver, and everything after the first dash is part of the semver "pre-release identifier": https://semver.org/#spec-item-9

### What did you expect to see?
Package version info / other metadata should be displayed on https://pkg.go.dev/cloud.google.com/go@v0.102.2-0.20220627142403-5be6d33a57cc

The behavior should be the same as this page for the same package but a different version: https://pkg.go.dev/cloud.google.com/go@v0.102.1

### What did you see instead?
Oops! We couldn't find “cloud.google.com/go@v0.102.2-0.20220627142403-5be6d33a57cc”.

Check that you entered the URL correctly, try fetching it following the [instructions here](https://pkg.go.dev/about#adding-a-package), or request to add “cloud.google.com/go@v0.102.2-0.20220627142403-5be6d33a57cc” to pkg.go.dev.

There is also a button labeled ```Request “cloud.google.com/go@v0.102.2-0.20220627142403-5be6d33a57cc”```, but clicking this does not solve the issue. The package is still not available on pkg.go.dev even after waiting.

Maybe this is expected and these pseudoversions are not supported on the pkg.go.dev about pages, even though they are present on the proxy.golang.org and the index.golang.org pages. In that case, I think that https://pkg.go.dev/about#adding-a-package should be updated with a note that explains this:
Adding a package

Data for the site is downloaded from [proxy.golang.org](https://proxy.golang.org/). We monitor the [Go Module Index](https://index.golang.org/index) regularly for new packages to add to pkg.go.dev. If you don’t see a package on pkg.go.dev, you can add it by doing one of the following **(note)**:

    Visiting that page on pkg.go.dev, and clicking the “Request” button. For example:
    https://pkg.go.dev/example.com/my/module

    Making a request to proxy.golang.org for the module version, to any endpoint specified by the [Module proxy protocol](https://pkg.go.dev/cmd/go/#hdr-Module_proxy_protocol). For example:
    https://proxy.golang.org/example.com/my/module/@v/v1.0.0.info

**(note): Note that pseudoversions of packages, like v0.0.0-20220315123456-abcdeffedcba, are not supported.**

**Comment by seankhliao** [comment]
I see the pages are there now
