### ISSUE TITLE
cmd/go: `go clean --fuzzcache` failure in TestScript/test_fuzz_limit_dup_entry

### ISSUE THREAD

**Issue by bcmills** [golang/go#59062]
```
#!watchflakes
post <- pkg == "cmd/go" && `go clean --fuzzcache: exit status`
```

Pulled out from https://github.com/golang/go/issues/55311#issuecomment-1469087280.

I think the fix is to set `env GOCACHE=$WORK/cache` or similar explicitly in script tests that need a clean fuzzcache.

**Comment by bcmills** [comment]
@rolandshoemaker, was this fixed by CL [59062](https://go.dev/issue/59062)?

**Comment by rolandshoemaker** [comment]
It seems so 🎉.
