### ISSUE TITLE
x/image/tiff: decoding of metadata is not available

### ISSUE THREAD

**Issue by vault-thirteen** [golang/go#59079]
Current implementation of TIFF decoder is unable to decode following metadata from TIFF image:
* TIFF tags
* EXIF tags
* GPS tags

### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.20.2 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Microsoft Windows 10
Intel x86-64 (a.k.a. AMD64)

### What did you expect to see?
Usable metadata for TIFF images.

**Comment by cherrymui** [comment]
It looks like it needs a new API to decode the metadata? Would you like to file a proposal (see https://golang.org/s/proposal-process)? Thanks.

**Comment by vault-thirteen** [comment]
If someone needs TIFF metadata decoded, this functionality is available in the "TIFFer" library – https://github.com/vault-thirteen/TIFFer
