### ISSUE TITLE
x/tools/gopls: panic in mod.hoverOnModuleStatement

### ISSUE THREAD

**Issue by heliostatic** [golang/go#59077]
gopls version: v0.11.0 (go1.20.2)
gopls flags: 
update flags: proxy
extension version: 0.38.0
go version: 1.20.2
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Wed, 15 Mar 2023 17:20:29 GMT
restart history:
Wed, 15 Mar 2023 17:11:59 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x30 pc=0x100b8976c]

goroutine 160 [running]:
golang.org/x/tools/gopls/internal/lsp/mod.hoverOnModuleStatement({0x1010b5308%3F, 0x14000980bd0%3F}, 0x14000980bd0%3F, 0x1010b5570%3F, {0x1010c1470%3F, 0x1400043a2c0%3F}, {0x1010b5570%3F, 0x1400033c620%3F})
	  hover.go:128  0x3c
golang.org/x/tools/gopls/internal/lsp/mod.Hover({0x1010b5260, 0x140005e2050}, {0x1010c1470, 0x1400043a2c0}, {0x1010b5570, 0x1400033c620}, {0x980a50%3F, 0x140%3F})
	  hover.go:50  0x22c
golang.org/x/tools/gopls/internal/lsp.(*Server).hover(0x14000980a50%3F, {0x1010b5260, 0x140005e2050}, 0x14000980a50)
	  hover.go:25  0x100
golang.org/x/tools/gopls/internal/lsp.(*Server).Hover(0x1400003d180%3F, {0x1010b5260%3F, 0x140005e2050%3F}, 0x100f4f840%3F)
	  server_gen.go:140  0x24
golang.org/x/tools/gopls/internal/lsp/protocol.serverDispatch({0x1010b5260, 0x140005e2050}, {0x1010c4720, 0x140000e2000}, 0x14000980a20, {0x1010b5650, 0x140005543c0})
	  tsserver.go:397  0xa58
golang.org/x/tools/gopls/internal/lsp/protocol.ServerHandler.func1({0x1010b5260, 0x140005e2050}, 0x14000980a20, {0x1010b5650, 0x140005543c0})
	  protocol.go:157  0x6c
golang.org/x/tools/gopls/internal/lsp/lsprpc.handshaker.func1({0x1010b5260, 0x140005e2050}, 0x14000980a20, {0x1010b5650%3F, 0x140005543c0%3F})
	  lsprpc.go:519  0x740
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1({0x1010b5260, 0x140005e2050}, 0x140004ddb78, {0x1010b5650%3F, 0x140005543c0%3F})
	  handler.go:35  0xf0
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2()
	  handler.go:103  0x90
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x1d8
[Error - 1:20:25 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by adonovan** [comment]
Dup of #57625 (fixed)?

**Comment by findleyr** [comment]
Yes, this is a dupe. Our current release is a big one, and probably won't be out until April. Unfortunately, this panic seemed rare enough to not put out a patch release.
