### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by caogenfu** [golang/go#59071]
### What is the URL of the page with the issue?
 the filename mismatch with arch
 
 
### Screenshot
 
![image](https://user-images.githubusercontent.com/43062234/225542886-27fd4990-a2b3-466b-a97c-4619bf31ef6c.png)

**Comment by ShawnHXH** [comment]
X86_64 and AMD64 are different names for the same thing - they're both 64-bit extensions to the x86 architecture.
