### ISSUE TITLE
https://go.dev/ref/spec#Constant_declarations

### ISSUE THREAD

**Issue by dxinli** [golang/go#59083]
### What is the URL of the page with the issue?
 https://go.dev/ref/spec#Constant_declarations
 
 
### Screenshot
 

 
![1679016215909](https://user-images.githubusercontent.com/44126836/225788291-d3b13e39-eb4c-4cb3-8edb-b71895b98722.jpg)
![1679016226106](https://user-images.githubusercontent.com/44126836/225788310-cfcd8692-adfa-4932-b626-1c1c8b9179da.jpg)

 
 
### What did you do?
i think the grammer is error

 why this ConstSpec can omit the ExpressionList

**Comment by randall77** [comment]
Read to the end of that section you referenced. ExpressionLists can be omitted. It is particularly helpful with `iota`.

**Comment by dxinli** [comment]
thank you , but const declaration list the expression list may be omitted from any but the first ConstSpec.The grammer is not reflected.Does it mean that the compiler promise correctness in constant declarations instead of grammar?

> Read to the end of that section you referenced. ExpressionLists can be omitted. It is particularly helpful with `iota`.

thank you , but const declaration list the expression list may be omitted from any but the first ConstSpec.The grammer is not reflected.Does it mean that the compiler promise correctness in constant declarations instead of grammar?

**Comment by randall77** [comment]
Not everything that can be parsed by the grammar is correct Go code. So yes, the compiler implements additional restrictions.
So something like
```
const (
    X
    Y
)
```
Will generate a compile-time error even though it parses just fine.

**Comment by dxinli** [comment]
Thank you for your help, I will study further
