### ISSUE TITLE
x/website/tour: top-left link not working

### ISSUE THREAD

**Issue by Deleplace** [golang/go#59094]
### What did you do?

- Visited https://go.dev/tour
- Clicked the top-left "Go" logo

<img width="382" alt="image" src="https://user-images.githubusercontent.com/13508141/225892174-db68894d-b9ce-4e66-b6e5-49a898ae8b12.png">

### What did you expect to see?

https://go.dev/

### What did you see instead?

Stays on current page https://go.dev/tour/welcome/1

**Comment by Deleplace** [comment]
Observed in Chrome and in Firefox

**Comment by cherrymui** [comment]
It seems that link always goes back to the first page of the tour https://go.dev/tour/welcome/1 , even if the current package is at a later part of the tour (e.g. on https://go.dev/tour/basics/5).

cc @golang/tools-team
