### ISSUE TITLE
proposal: Go 2: functional interface like implementation

### ISSUE THREAD

**Issue by mstrYoda** [golang/go#59095]
Currently Go has first class functions and duck type interfaces.

It would be handy to have functional interfaces for easily passing a function as a parameter to another function that expects an interface with has only one function definition.

Example:

```go

type Some interface {
  SomeFunc(param int) int
}

func Test(s Some) {
...
}

f := func(a int) int {
...
}

Test(f)
```

WDYT about it?

**Comment by fzipp** [comment]
This is a duplicate of #21670

**Comment by mstrYoda** [comment]
> This is a duplicate of #21670

Thank you, closed.
