### ISSUE TITLE
x/tools/gopls: internal error: non-deterministic parsing result

### ISSUE THREAD

**Issue by findleyr** [golang/go#59097]
In https://go.dev/cl/473165, I adjusted the parse cache logic for reparsing syntax that had to be fixed.

This logic includes an assumption that parsing is deterministic (which one would hope is true!). However, that assumption is clearly violated, or I have a bug in my implementation of that assumption, as I've hit the included panic twice already.

CC @adonovan

**Comment by adonovan** [comment]
> I've hit the included panic twice already.

Which panic? (Did you mean to include it in this issue?)

**Comment by findleyr** [comment]
Oh, it's in the title, but I should have linked.

This one:
https://cs.opensource.google/go/x/tools/+/master:gopls/internal/lsp/cache/parse_cache.go;l=181;drc=b222520ff002290a694dda6a6dfe858cf8d8dfe6
