### ISSUE TITLE
x/website/tour: Dark mode

### ISSUE THREAD

**Issue by Deleplace** [golang/go#59093]
The current UI of https://go.dev/tour only has a light theme

<img width="300" alt="image" src="https://user-images.githubusercontent.com/13508141/225889957-6102a892-1173-440f-80b4-eb843f114515.png">

An additional dark theme would be very nice to have, like already implemented in the other parts of https://go.dev/

**Comment by Deleplace** [comment]
I may help with the implementation, while also taking other accessibility concerns into consideration.
@alicemerrick @jamalc @fflewddur

**Comment by lucasres** [comment]
That would be really cool. If you need help, I'm also willing to help.

**Comment by cherrymui** [comment]
cc @golang/tools-team

**Comment by Deleplace** [comment]
TIL this has been [asked ~10 times](https://github.com/golang/tour/issues?q=is%3Aissue+dark) in the golang/tour issue tracker (using the "Share feedback" button, top-right in the Tour)

**Comment by hyangah** [comment]
Fix verified. Thanks!
