### ISSUE TITLE
cmd/go: "go clean -cache" is an unknown command on fresh installs

### ISSUE THREAD

**Issue by percivalalb** [golang/go#59109]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.2 linux/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/home/bob/.cache/go-build"
GOENV="/home/bob/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/bob/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/bob/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm64"
GOVCS=""
GOVERSION="go1.20.2"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4151970831=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.20.2 linux/arm64
GOROOT/bin/go tool compile -V: compile version go1.20.2
uname -sr: Linux 5.15.80-v8.1.el9.altarch
</pre></details>

### What did you do?

Installed golang on a Raspiberry PI and ran `go clean -cache` but got an "unknown command" error.

After running `go install` (I installed Hugo from it's source). `go clean -cache` is now a recongised command and doesn't error.

### What did you expect to see?

I would expect the command to not say it is an unknown command on a fresh install and if there is nothing to clean, either exit with such a message or no message at all. Saying it is an "unknown command" is misleading.
```
$ go clean -cache
$ echo $?
0
```

### What did you see instead?

```console
$ go ​clean -cache
go ​clean: unknown command
Run 'go help' for usage.
```

**Comment by seankhliao** [comment]
how did you install go?
I don't see how it's possible for clean to be an unknown command.

**Comment by percivalalb** [comment]
I was installing on my Raspberry PI 4 running Rocky9 - I have the commands at hand:
```
curl https://go.dev/dl/go1.20.2.linux-arm64.tar.gz --output /tmp/go.tar.gz --location
tar -zxvf /tmp/go.tar.gz -C /usr/local
echo 'export GOROOT=/usr/local/go' | tee -a /etc/profile.d/golang.sh
echo 'export PATH=$PATH:/usr/local/go/bin' | tee -a /etc/profile.d/golang.sh
source /etc/profile.d/golang.sh
```

Then immediately ran `go clean -cache`

**Comment by seankhliao** [comment]
is this a reproducible error?

**Comment by ALTree** [comment]
You've got a zero width space character before cache (it's also in the command you pasted above):

![image](https://user-images.githubusercontent.com/3586803/226112665-48ea6860-3889-4b55-99b9-a1a04382b568.png)

**Comment by percivalalb** [comment]
Oh ahaha! Nice spot. No idea how that got there. Okey, no issue here. Closing...

**Comment by MarioVilas** [comment]
Just wanted to comment I was hit by the exact same error. Surprisingly when copying and pasting from Google! Apparently Google inserts that character there for some reason.
