### ISSUE TITLE
x/website: add linux/riscv64 downloads

### ISSUE THREAD

**Issue by ernado** [golang/go#59113]
Add `linux/riscv64` to [go.dev/dl](https://go.dev/dl/) to downloads table under "Other Ports" (i.e. like go1.20.2.linux-ppc64le.tar.gz).

Here:
![image](https://user-images.githubusercontent.com/866677/226139179-e85c1a00-fdb9-4abf-a592-51e64b82f80e.png)

This is required to add riscv64 to [Docker Official Image packaging for golang](https://github.com/docker-library/golang).

I've tried to search for repo to apply CL's, but failed (golang/build?).

**Comment by seankhliao** [comment]
As per our https://github.com/golang/go/wiki/PortingPolicy
linux/risc64 is a secondary port, the core team won't be publishing binary builds for this architecture.

See also #53383

**Comment by ernado** [comment]
@seankhliao `linux/s390x` is a secondary port to, same as all under "Other Ports" section, so port should not be first class to have binaries.

**Comment by ernado** [comment]
Oh, I see the porting policy now.

Removing secondary ports will break some docker official images, which is unfortunate.

It looks like there should be another process to publish binaries, I'll investigate.

**Comment by ernado** [comment]
Ref: #53862

**Comment by ernado** [comment]
I've created [go-riscv/go](https://github.com/go-riscv/go) that cross-compiles compiler for `riscv64` in CI/CD.

There is a [pre-compiled](https://github.com/go-riscv/go/releases/latest) go distrubiton `go1.20.2.linux-riscv64.tar.gz` in [latest release](https://github.com/go-riscv/go/releases/latest) and also scripts for building it locally.

**Comment by ernado** [comment]
This was done as part of #53862.
