### ISSUE TITLE
runtime: fatal error: missing stack in shrinkstack

### ISSUE THREAD

**Issue by mrhb6006** [golang/go#59125]
### What version of Go are you using (`go version`)?

<pre>
$ 1.20.2

</pre>

### What operating system and processor architecture are you using (`go env`)? debian - amd64

<details><summary><code>go env</code> Output</summary><br><pre>
$ 
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOOS="linux"
GOPATH="/home/mohammadreza/go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3308778073=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
I have written a rest api service that panics every few minutes. 
This panic is related to the golang libraries themselves
load of this service is high, but it provided enough resources to the service (100 GIG RAM , 40 CPU CORE , ... )

**fatal error: missing stack in shrinkstack**

   runtime stack:
   runtime.throw({0x1a8bd5f?, 0x0?})
        	/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7fbbf9ffaaa8 sp=0x7fbbf9ffaa78 pc=0x43a9bd
   runtime.shrinkstack(0x0?)
        	/usr/local/go/src/runtime/stack.go:1164 +0x198 fp=0x7fbbf9ffaac8 sp=0x7fbbf9ffaaa8 pc=0x454978
   runtime.scanstack(0xc000d0a000, 0xc0000c2638)
        	/usr/local/go/src/runtime/mgcmark.go:775 +0xf2 fp=0x7fbbf9ffacd0 sp=0x7fbbf9ffaac8 pc=0x421b92
   runtime.markroot.func1()
         	/usr/local/go/src/runtime/mgcmark.go:239 +0xb5 fp=0x7fbbf9ffad20 sp=0x7fbbf9ffacd0 pc=0x420a95
   runtime.markroot(0xc0000c2638, 0xc74, 0x1)
   	       /usr/local/go/src/runtime/mgcmark.go:213 +0x1a5 fp=0x7fbbf9ffadc0 sp=0x7fbbf9ffad20 pc=0x420745
   runtime.gcDrain(0xc0000c2638, 0x7)
        	/usr/local/go/src/runtime/mgcmark.go:1069 +0x39f fp=0x7fbbf9ffae20 sp=0x7fbbf9ffadc0 pc=0x42283f
   runtime.gcBgMarkWorker.func2()
   	        /usr/local/go/src/runtime/mgc.go:1367 +0x7a fp=0x7fbbf9ffae70 sp=0x7fbbf9ffae20 pc=0x41ed1a
   runtime.systemstack()
   	       /usr/local/go/src/runtime/asm_amd64.s:496 +0x49 fp=0x7fbbf9ffae78 sp=0x7fbbf9ffae70 pc=0x46c189`

**There are many _more same panics occurring_ related to the golang libraries themselves, which I will send.**

**Comment by seankhliao** [comment]
please fill out the bug report template

**Comment by mrhb6006** [comment]
> please fill out the bug report template

edited

**Comment by mrhb6006** [comment]
@seankhliao plz help me

**Comment by mrhb6006** [comment]
no solution ???

**Comment by ianlancetaylor** [comment]
Is there a way that we can reproduce the problem ourselves?  Right now this looks like a form of memory corruption.  Do you call C functions using cgo?  Have you tried running your program using the race detector?

**Comment by mrhb6006** [comment]
> Is there a way that we can reproduce the problem ourselves? Right now this looks like a form of memory corruption. Do you call C functions using cgo? Have you tried running your program using the race detector?

no , i dont call cgo function .
yes i run with race  detector and it is ok
