### ISSUE TITLE
x/tools/gopls: OrganizeImports truncates file with line directives

### ISSUE THREAD

**Issue by pjweinb** [golang/go#59124]
with gopls at tip, here are before and after OrganizeImports

"//line foo.y:103\npackage main\n\nimport \"fmt\"\n\n// this comment is necessary for failure\nfunc a() { fmt.Println()}\n"
 "//line foo.y:103\npackage main\n\nimport \"fmt\"\n\n// this comment is necessary for failure\n"

**Comment by findleyr** [comment]
This was fixed in https://go.dev/cl/480515 (the issue formatting was broken in that commit message).
