### ISSUE TITLE
pkg.go.dev: no IPv6 address/hosting

### ISSUE THREAD

**Issue by 06kellyjac** [golang/go#59148]
### What is the URL of the page with the issue?
 
All of go.dev

 
### What did you do?
 

Check if go.dev had an IPv6 address
 
 
### What did you expect to see?

See it did
 
 
### What did you see instead?

See it didn't

---

https://repology.org/link/https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/tools/security/govulncheck/default.nix

https://ready.chair6.net/?url=https%3A%2F%2Fpkg.go.dev

**Comment by heschi** [comment]
go.dev does:

```
$ host go.dev
[...]
go.dev has IPv6 address 2001:4860:4802:36::15
```

but it seems true that pkg.go.dev doesn't. cc @golang/tools-team

**Comment by 06kellyjac** [comment]
Thanks for the correction

**Comment by jamalc** [comment]
Done.
```
$ host pkg.go.dev
pkg.go.dev has address 34.149.140.181
pkg.go.dev has IPv6 address 2600:1901:0:f535::
```
