### ISSUE TITLE
Unmarshaling failed when json string contains "\u0000", and it reports "invalid character '\x00' in string literal"

### ISSUE THREAD

**Issue by xiaobai-tx** [golang/go#59140]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.19.1
</pre>

### Does this issue reproduce with the latest release?
YES

### What operating system and processor architecture are you using (`go env`)?
Linux

### What did you do?
```
package main

import (
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
)

func UnescapeUnicode(uContent string) (string, error) {
	content := strings.Replace(strconv.Quote(uContent), `\\u`, `\u`, -1)
	text, err := strconv.Unquote(content)
	if err != nil {
		return "", err
	}
	return text, nil
}

func main() {
	v := "{\"aa\":\"some\\u0000\"}"
	v2, _ := UnescapeUnicode(v)
	var m = make(map[string]interface{})
	err := json.Unmarshal([]byte(v2), &m)
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(m)
}

```

### What did you expect to see?
```
map[aa:some]
```

### What did you see instead?
```
invalid character '\x00' in string literal
```

**Comment by seankhliao** [comment]
it is invalid.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
