### ISSUE TITLE
x/website: Compatibility information for GCC 12 gccgo

### ISSUE THREAD

**Issue by jefferyto** [golang/go#59143]
On https://go.dev/doc/install/gccgo#Releases it lists the implementation compatibility of gccgo for each GCC release, but it only goes up to GCC 11.

What is the implementation compatibility for GCC 12, and can this information be added to the page?

**Comment by ianlancetaylor** [comment]
Thanks for the note.  I sent CL 477875 to update the page.

GCC is currently stuck on the Go 1.18 standard library until generics support is added to the Go frontend.
