### ISSUE TITLE
cmd/go: improve go list parallelism

### ISSUE THREAD

**Issue by findleyr** [golang/go#59157]
While staring at gopls execution patterns, I noticed surprisingly low CPU utilization while awaiting `go list` results. This got me excited that perhaps there was still some room for optimization.

I hooked up runtime/trace to cmd/go, and observed the following result while loading kubernetes using go/packages:
![image](https://user-images.githubusercontent.com/57144380/226457925-785b662e-cf6e-4d9d-8a1d-2a0674f44ad4.png)

The circled regions appear to be pre- and post- processing packages in a single thread, the bulk of which amounts to sorting of dependencies. This should be possible to parallelize.

The middle region looks like recursive loading of imports, involving a mixture of I/O, and therefore does not achieve high CPU utilization. It's possible that this could also be optimized.

Overall, if we could reduce this 4.6s load time, it could have significant impact on gopls startup. (background: we're working to heavily optimize gopls via on-disk caching, and while historically `go list` has been a small fraction of load time, it has become the majority of load time). Eyeballing the trace, I would not be surprised if it would be easy to shave off 1s, and possible (but hard) to shave off 2s. :)

CC @matloob

**Comment by heschi** [comment]
cc @bcmills
