### ISSUE TITLE
x/website: outdated description of A Tour Of Go

### ISSUE THREAD

**Issue by Deleplace** [golang/go#59167]
The pages at https://go.dev/learn/#selected-tutorials and https://go.dev/doc/#go_tour say the Tour has 3 sections, however it now has a 4th section "Generics"

![image](https://user-images.githubusercontent.com/13508141/226572002-1fc2428d-91e1-4e4d-8d61-867e010b4024.png)

![image](https://user-images.githubusercontent.com/13508141/226572214-ec1514a4-bcf5-4284-a6b7-58020aec6a9b.png)

**Comment by Deleplace** [comment]
I will make a CL to fix this.

**Comment by heschi** [comment]
cc @golang/tools-team
