### ISSUE TITLE
encoding/gob: cannot decode large []string

### ISSUE THREAD

**Issue by RandomSort** [golang/go#59172]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>
1.20.2
### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOOS="linux"
</pre></details>

### What did you do?

If you try to decode a `[]string` larger than `655360` using `encoding/gob`, you get a panic as the slice helpers introduced in 1.20 did not extend the stringslice helper.

https://go.dev/play/p/Xe0ajfykrSm?v=goprev (thanks to Jacob Oaks)

### What did you expect to see?
Successful decoding (https://go.dev/play/p/Xe0ajfykrSm?v=goprev ) <- 1.19

### What did you see instead?
Panic (https://go.dev/play/p/Xe0ajfykrSm) <- 1.20

**Comment by ianlancetaylor** [comment]
FYI this was a mistake on my part, in CL 443777, and there is already an approved CL to fix it.
