### ISSUE TITLE
x/pkgsite: Requesting BSL inclusion

### ISSUE THREAD

**Issue by jsimnz** [golang/go#59183]
### What did you do?

Tried to access documentation for a Business Source License 1.1 (BSL 1.1) repo.

### What did you expect to see?
Generated documentation.

### What did you see instead?
Unsupported due to licensing restrictions

--

I'm seeking to have my (and potentially all) repo(s) included in pkg.go.dev that uses the BSL 1.1 license. https://mariadb.com/bsl11/

The BSL 1.1 license is becoming *very* popular for open source projects that are also balancing commercialization priorities. Although it is not an official OSI license, it does have the endorsement from Bruce Perens[0] who is the founder of the OSI Foundation. Additionally, it automatically converts to an "official" OSI license after a period of no more than 4 years from release. Finally, it's designed around an "Additional Use Grant" which my self (and Im sure other repo authors) would be happy to make inclusions to accomodate pkgsite.

These repos are fundamentally open-source / source available, so it's unfortunate that the current structure of pkg.go.dev doesn't support them.

[0] - https://perens.com/2017/02/14/bsl-1-1/#:~:text=So%2C%20there%20can,works%20Open%20Source.

**Comment by jamalc** [comment]
We have forwarded this request and are waiting to hear back from our legal team.

**Comment by jsimnz** [comment]
Appreciate the update, looking forward.

**Comment by jsimnz** [comment]
@jamalc any update on this? Thanks.

**Comment by willfaught** [comment]
@hyangah Then shouldn't BlueOak-1.0.0 and the CC licenses be removed from that list? They aren't OSI-approved.

**Comment by cespare** [comment]
@willfaught the policy doesn't say that the list can only contain OSI-approved licenses. It says that being OSI-approved is a requirement for adding new licenses to the list.

**Comment by jsimnz** [comment]
@hyangah was there specific items about the BSL that is preventing it from being approved that you can share, other than not being OSI-approved?
