### ISSUE TITLE
cmd/go: does not vendor some directories 

### ISSUE THREAD

**Issue by mcandre** [golang/go#59182]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/andrew/Library/Caches/go-build"
GOENV="/Users/andrew/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/andrew/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/andrew/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/andrew/.asdf/installs/golang/1.19/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/andrew/.asdf/installs/golang/1.19/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xc/s20l07yj76x8m3h20lmy5jlc0000gn/T/go-build3387780020=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Attempting to `go mod vendor` the package gitlab.com/gomidi/midi results in a critical `cpp/` cgo directory being deleted in its entirety.

### What did you expect to see?

Complete vendoring and successful cgo compilation.

### What did you see instead?

I tried several recommended tricks to force `go mod vendor` to persist the directory, to no avail. I tried:

* Adding a `dummy.go` file to the `cpp/` directory (the most commonly recommended tip from the Go community).
* Moving `cpp/*` to a parent directory with existing `*.go` files, and updating `#include` directives to account for the new locations.
* Removing `#include` directives from `*.go` files (another Go community recommended tip).
* Enclosing the C/C++ files with `#pragma once` or `#ifndef`... directives.

The only states I am have been able to achieve are:

* `go mod vendor` deletes the `cpp/` directory entirely
* `go install ./...` complains of missing C/C++ declarations
* `go install ./...` complains of *duplicate* C/C++ declarations

Can someone please explain what the gomidi/midi author should do to correct their `go mod vendor` integration in their CGO code?

As a workaround, I am currently using modvendor, but if at all possible, I would prefer to use only built-in go tools.

https://github.com/goware/modvendor

Frankly, the whole go vendoring system behaves awkwardly with cgo (above), with `go install <dev tools>` (no dev dependency tracking in `go.mod`), and with reflection (e.g. enum comparison). I am at a loss to explain why the different built-in Go components often fail to cooperate with each other.

**Comment by mvdan** [comment]
> Adding a `dummy.go` file to the `cpp/` directory (the most commonly recommended tip from the Go community).

Can you show an example of that not working? If you add a Go file to that directory to make it a Go package, and you either directly or indirectly import it from your main module, it should be included by `go mod vendor`. My guess is that you added the Go file, but did not add any import, so it got discarded as an unused import by `go mod vendor`, since it only includes the packages in the package import graph.

**Comment by ccll** [comment]
> My guess is that you added the Go file, but did not add any import, so it got discarded as an unused import by `go mod vendor`

What if I want to add a `cmd` type package as dependency?
I think this is a valid use case that cmd/go currently ignoring.

When we do 'vendoring', we are assuming that in the future some of the 'dependencies' may disappear from the Internet so we keep those source codes together with our application code, IMHO not only the `import`-ed libraries are dependencies, but also the external commands/programs that run along side with our application should be considered as 'dependencies'. Currently there are no way to vendor those packages with `go mod vendor`.

I hope there is a way to allow the user explicitly set a package as vendorable dependency, even those packages are not `import`-ed directly or indirectly by our main package.
