### ISSUE TITLE
cmd/go: If strip the windows binary with binutils it won't run.

### ISSUE THREAD

**Issue by jclab-joseph** [golang/go#59193]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOHOSTARCH="amd64"
GOOS="windows"
GOVERSION="go1.20.2"
GCCGO="gccgo"
</pre></details>

### What did you do?

See https://github.com/jclab-joseph/issue-go-windows-strip-not-working

The file built with the `go build` were stripped through binutils.
The stripped file runs on linux, but not on windows.
I'd like to keep the debug files separate to reduce the size.

### What did you expect to see?

It should work on Windows PC.

### What did you see instead?

![image](https://user-images.githubusercontent.com/88625531/227155708-663d040f-f200-4c68-a438-ec389b76b5b6.png)

**Comment by bcmills** [comment]
This doesn't seem like a `cmd/go` bug at all. If you're using binutils to modify a binary that runs, and it produces a binary that doesn't run, you should open an issue against binutils.

If you build a binary using the Go toolchain, and then you break that binary using a third-party tool, that's not the fault of the Go toolchain. 🙃

**Comment by jclab-joseph** [comment]
I don't think so... It works fine except for go-lang .

![image](https://user-images.githubusercontent.com/88625531/227391047-2bd9fc72-6467-4352-bd0a-8100c9b1849b.png)
