### ISSUE TITLE
go/types, types2: internal compiler error: panic: Config.Sizes.Sizeof returned a size < 0

### ISSUE THREAD

**Issue by Sundal4** [golang/go#59190]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.20

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

https://go.dev/play/p/bF8KMRTERIW

### What did you expect to see?

Errors are reported.

### What did you see instead?

```
<unknown line number>: internal compiler error: panic: Config.Sizes.Sizeof returned a size < 0
```

**Comment by cuonglm** [comment]
cc @mdempsky @griesemer

**Comment by griesemer** [comment]
Thanks for reporting. The case that doesn't produce a crash is a different issue. Filed #59207 for that.

**Comment by griesemer** [comment]
I filed #59209 for the case that produces a bad error message (`(untyped int constant 9223372036854775808) must be integer`).
