### ISSUE TITLE
debug/elf: Incorrectly double-decompressing ELF section

### ISSUE THREAD

**Issue by brancz** [golang/go#59208]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.1 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN="/Users/brancz/bin"
GOCACHE="/Users/brancz/Library/Caches/go-build"
GOENV="/Users/brancz/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/brancz/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/brancz"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.20.1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.20.1/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/brancz/src/github.com/polarsignals/polarsignals/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/var/folders/rl/8sh8jb5s1c1fl77ztzy4zw6m0000gn/T/go-build2747742421=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Downloaded the debuginfo for liblzma5:

```
curl https://debuginfod.ubuntu.com/buildid/0e13b0f27b3bc79a2828c11199ce4336a348af37/debuginfo > liblzma5.debuginfo
```

Tried to look at the DWARF entries:

```go
package main

import (
	"bytes"
	"debug/elf"
	"fmt"
	"io"
	"net/http"
)

func main() {
	resp, err := http.Get("https://debuginfod.ubuntu.com/buildid/0e13b0f27b3bc79a2828c11199ce4336a348af37/debuginfo")
	if err != nil {
		panic(err)
	}

	if resp.StatusCode != 200 {
		panic("unexpected status code")
	}

	content, err := io.ReadAll(resp.Body)
	if err != nil {
		panic(err)
	}

	f, err := elf.NewFile(bytes.NewReader(content))
	if err != nil {
		panic(err)
	}

	_, err = f.DWARF()
	fmt.Println("DWARF ERROR:", err)
}
```

And running that returns an error:

```
$ go run main.go
DWARF ERROR: zlib: invalid header
```

### What did you expect to see?

No error.

### What did you see instead?

An error, and I suspect I know why: `debug/elf` in extremely rare cases attempts to double-decompress an ELF section.

First the call to `.Data()` returns the decompressed section:

https://github.com/golang/go/blob/0aa14fca8c639c9ceba264dbf0d82bd53306aeaa/src/debug/elf/file.go#L1308

And if by pure chance the first 4 bytes of the decompressed bytes also happen to be what trigger a decompression, then the `.DWARF()` function will attempt to decompress the section a second time:

https://github.com/golang/go/blob/0aa14fca8c639c9ceba264dbf0d82bd53306aeaa/src/debug/elf/file.go#L1317-L1319

cc @mengzhuo since you recently added this case

**Comment by brancz** [comment]
A suggestion of how to fix this: I think all the decompression code should live in the `(*section).Open` function. Then there is no risk of double-decompressing.

**Comment by mengzhuo** [comment]
I'll send a CL for this issue, thanks.

**Comment by ianlancetaylor** [comment]
@brancz Just to be sure, can you confirm that the problem you originally reported is fixed on HEAD?  Thanks.

**Comment by brancz** [comment]
Sorry for the very late reply, but I can confirm that this has been fixed since the linked change landed.

**Comment by lucab** [comment]
For future reference, this was the amd64 debuginfo for Ubuntu xz-utils `5.2.4-1ubuntu1.1` ([launchpad entry](https://launchpad.net/ubuntu/+source/xz-utils/5.2.4-1ubuntu1.1)).
Auto-built as part of `liblzma5-dbgsym_5.2.4-1ubuntu1.1_amd64.ddeb` in https://launchpad.net/~ubuntu-security-proposed/+archive/ubuntu/ppa/+build/23531947.
