### ISSUE TITLE
cmd/internal/obj/arm: add TST, TEQ instruction

### ISSUE THREAD

**Issue by ncw** [golang/go#5921]
<pre>5l seems to explode on the TST instruction

        TST $3, R0

5a is quite happy to assemble this, but 5l then produces

main.tst: illegal combination TST C_RCON C_REG C_NONE, 8 1
(3) TST $3,R0,
main.tst: illegal combination TST C_RCON C_REG C_NONE, 8 1
(3) TST $3,R0,

I conjecture this might be easy to fix since the very similar TEQ instruction works fine.

-------------------

What steps will reproduce the problem?

Save the attached files into a temporary directory

Run

GOARCH=&quot;arm&quot; GOOS=&quot;linux&quot; go build

What is the expected output?

Nothing (it compiles)

What do you see instead?

# _/tmp/tst
main.tst: illegal combination TST C_RCON C_REG C_NONE, 8 1
(3) TST $3,R0,
main.tst: illegal combination TST C_RCON C_REG C_NONE, 8 1
(3) TST $3,R0,

Which compiler are you using (5g, 6g, 8g, gccgo)?

5a &amp; 5l

Which operating system are you using?

Cross compiling for arm linux on amd64 linux

$ go-linux-arm env
GOARCH=&quot;arm&quot;
GOBIN=&quot;&quot;
GOCHAR=&quot;5&quot;
GOEXE=&quot;&quot;
GOHOSTARCH=&quot;amd64&quot;
GOHOSTOS=&quot;linux&quot;
GOOS=&quot;linux&quot;
GOPATH=&quot;/home/ncw/Code/Go&quot;
GORACE=&quot;&quot;
GOROOT=&quot;/home/ncw/Code/go&quot;
GOTOOLDIR=&quot;/home/ncw/Code/go/pkg/tool/linux_amd64&quot;
CC=&quot;gcc&quot;
GOGCCFLAGS=&quot;-g -O2 -fPIC -marm&quot;
CGO_ENABLED=&quot;0&quot;

Which version are you using?  (run 'go version')

go version devel +77be25034f84 Fri Jul 19 01:22:26 2013 +0400 linux/amd64</pre>

Attachments:
1. <a href="https://storage.googleapis.com/go-attachment/5921/0/tst.s">tst.s</a> (74 bytes)
2. <a href="https://storage.googleapis.com/go-attachment/5921/0/tst.go">tst.go</a> (49 bytes)

**Comment by rsc** [comment]
Note that there is a TST that means something else.

**Comment by jolan** [comment]
I believe this can be closed now since this is a duplicate of #21583 which was just closed via:

https://go-review.googlesource.com/c/go/+/67490

**Comment by tklauser** [comment]
Fixed by https://golang.org/cl/67490
