### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by Teuton-Roy** [golang/go#59223]
gopls version: v0.11.0 (go1.20.2)
gopls flags: 
update flags: proxy
extension version: 0.38.0
go version: 1.20.2
environment: Visual Studio Code win32
initialization error: undefined
issue timestamp: Fri, 24 Mar 2023 09:44:48 GMT
restart history:
Fri, 24 Mar 2023 08:14:05 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x30 pc=0x16f829d]

goroutine 242 [running]:
golang.org/x/tools/gopls/internal/lsp/mod.hoverOnModuleStatement({0x1c411b8%3F, 0xc000458f60%3F}, 0xc000458f60%3F, 0x1c41420%3F, {0x1c4dd30%3F, 0xc00017cdc0%3F}, {0x1c41420%3F, 0xc0001be8c0%3F})
	  hover.go:128  0x5d
golang.org/x/tools/gopls/internal/lsp/mod.Hover({0x1c41110, 0xc0000a8e10}, {0x1c4dd30, 0xc00017cdc0}, {0x1c41420, 0xc0001be8c0}, {0x458ea0%3F, 0xc0%3F})
	  hover.go:50  0x31f
golang.org/x/tools/gopls/internal/lsp.(*Server).hover(0x1869640%3F, {0x1c41110, 0xc0000a8e10}, 0xc000458ea0)
	  hover.go:25  0x152
golang.org/x/tools/gopls/internal/lsp.(*Server).Hover(0xc0005b6240%3F, {0x1c41110%3F, 0xc0000a8e10%3F}, 0x1869640%3F)
	  server_gen.go:140  0x25
golang.org/x/tools/gopls/internal/lsp/protocol.serverDispatch({0x1c41110, 0xc0000a8e10}, {0x1c51c00, 0xc000222100}, 0xc000458e70, {0x1c41500, 0xc0000d5880})
	  tsserver.go:397  0xca6
golang.org/x/tools/gopls/internal/lsp/protocol.ServerHandler.func1({0x1c41110, 0xc0000a8e10}, 0xc000458e70, {0x1c41500, 0xc0000d5880})
	  protocol.go:157  0x90
golang.org/x/tools/gopls/internal/lsp/lsprpc.handshaker.func1({0x1c41110, 0xc0000a8e10}, 0xc000458e70, {0x1c41500%3F, 0xc0000d5880%3F})
	  lsprpc.go:519  0x9f9
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1({0x1c41110, 0xc0000a8e10}, 0xc00028d530, {0x1c41500%3F, 0xc0000d5880%3F})
	  handler.go:35  0xf6
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2()
	  handler.go:103  0xa3
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x20a
[Error - 3:14:42 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by adonovan** [comment]
This is (another) duplicate report of https://github.com/golang/go/issues/59077, which is already fixed at head, but unfortunately we haven't released gopls as often as usual because of recent major redesign work. However we plan to make another release in April which will include the fix.

Thanks for reporting the crash.

**Comment by Teuton-Roy** [comment]
Thanks for your review 🙂
