### ISSUE TITLE
x/tools/gopls: 'implementations' doesn't work with generics

### ISSUE THREAD

**Issue by adonovan** [golang/go#59224]
Even some of the most basic scenarios of 'implementations' are not working at all with generics, for example when the concrete and interface types are both generalized over `[T any]` and are defined within the same file:
```
xtools$ cat d/d.go 
package d

type Collection[T any] interface {
	Push(T) error
	Pop() (*T, bool)
}

type C[T any] struct{}

func (C[T]) Push(t T) error { return nil }

func (C[T]) Pop() (*T, bool) {
	var t T
	return &t, true
}

var _ Collection[int] = C[int]{}

xtools$ go run ./gopls implementation ./d/d.go:#120  # within "Push" concrete method identifier
xtools$
```
This is not a recent regression:
```
xtools$ ./gopls-v0.11.0 implementation ./d/d.go:#120  
xtools$
```
A similar lack of results is obtained by querying the `Push` abstract method, or the Collection interface, or the C concrete type.

(This test case was a further reduction of the one described in https://youtrack.jetbrains.com/issue/GO-12702/Go-to-Declaration-Implementation-not-available-for-generics-interfaces, referenced by https://github.com/golang/vscode-go/issues/2711.)

**Comment by linjunhao1997** [comment]
I think this is urgently needed

**Comment by fangjh13** [comment]
I would like to know how the progress is going, it's really needed.

**Comment by adonovan** [comment]
> I would like to know how the progress is going, it's really needed.

No progress, sorry. Haven't even designed the algorithm yet. But let's make it a priority for 0.13.

**Comment by ajsqr** [comment]
Hello, is a fix for this planned in the upcoming release ?

**Comment by Solverj** [comment]
I'm also currently googling / gpting / searching, atm I have to make tests on a struct to verify that I've created structs according to generic interface in neovim.

**Comment by adonovan** [comment]
> Hello, is a fix for this planned in the upcoming release ?

Unfortunately no, but likely the following one.

**Comment by HarishHary** [comment]
Hello any progress on this one?

**Comment by adonovan** [comment]
Still no progress yet, sorry.

The problem is a little trickier than it may appear because of the design of the index (database) used to radically optimize gopls v0.15. The indexed designed means that the problem of testing implements(T, I), where I is an interface, cannot be done by making queries on the type-checker data structures for T and I since we no longer have them. Instead, the problem is mapped onto the domain of sets of strings, each representing a single method, so that the query becomes a string subset test. This works well for non-generic methods, which can each be mapped to a special string called a fingerprint; but we have not yet had time to develop a theory for fingerprinting generic methods, so they would need to fall back to using the type-checker, undoing the benefits of the gopls v0.15 redesign. Of course there are various short-cuts we could apply for common and simple cases, but our current focus is on better support for refactoring, so unfortunately this is not going to happen in the next several months.

**Comment by DingYuan0118** [comment]
Hello, half year passed. Any progress on this one?

**Comment by adonovan** [comment]
Yes! Run `go install golang.org/x/tools/gopls@master` and let us know how this feature works for you.

**Comment by DingYuan0118** [comment]
Thanks for the quick response.

And I have got a question. I found that the Goland IDE already have a similar func like 

<img width="1023" alt="Image" src="https://github.com/user-attachments/assets/0b4d3b6b-010c-4f62-b34d-a8091248cefb" />

Is there any difference between it and gopls?

**Comment by DingYuan0118** [comment]
reports 
```
/Users/.../go/go1.23.4/bin/go install golang.org/x/tools/gopls@master
go: golang.org/x/tools/gopls@master (in golang.org/x/tools/gopls@v0.0.0-20250124010602-45227b6df520):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```

**Comment by adonovan** [comment]
> Is there any difference between it and gopls?

I don't use goland, so I can't answer that question. I am sure the feature is similar in the broad strokes (connecting interfaces with implementations), but it may differ in the details. For example, gopls only reports package-level types from other packages, so a type such as `type T struct { io.Reader }` appearing with in a function will not be found be a query for implementations of `io.Reader`. Also, gopls' matching algorithm for generic types and instantiations is not perfectly accurate.


> /Users/.../go/go1.23.4/bin/go install golang.org/x/tools/gopls@master ... [errors]

Ah, sorry about that, our go.mod file uses a replace directive so you can't install direct from master except for tagged releases.

You'll need to `git clone https://go.googlesource.com/tools` and then `cd gopls` and `go install`.

**Comment by DingYuan0118** [comment]
It works good for this demo. 

But our project can not upgrade go version so quickly and still use go1.19. So it is a little painful that I can not use this feature...

**Comment by adonovan** [comment]
> But our project can not upgrade go version so quickly and still use go1.19. So it is a little painful that I can not use this feature...

go1.19? That's very old: gopls v0.15 dropped support for go1.29 last April. You should find a way to upgrade your project.
