### ISSUE TITLE
crypto: Change to how errors are returned across multiple packages.

### ISSUE THREAD

**Issue by geofffranks** [golang/go#59226]
### What version of Go are you using (`go version`)?

1.20.2

### Does this issue reproduce with the latest release?

Yes

### Summary

The `crypto/tls` and `crypto/x509` packages (and maybe others?) return error messages differently in 1.20 than in 1.19. Errors are now wrapped down the calling chain. This does not appear to be mentioned in the 1.20 release notes, but is a breaking change for anyone looking at the types of these errors.

### Example

When making a failed HTTPS connection, in 1.19, the following error was returned:

```
x509.UnknownAuthorityError{Cert:(*x509.Certificate)(0xc0001f6000), hintErr:error(nil), hintCert:(*x509.Certificate)(nil)}
```

In 1.20, this is what is returned:
```
&tls.CertificateVerificationError{UnverifiedCertificates:[]*x509.Certificate{(*x509.Certificate)(0xc000198b00)}, Err:x509.UnknownAuthorityError{Cert:(*x509.Certificate)(0xc000198b00), hintErr:error(nil), hintCert:(*x509.Certificate)(nil)}}
```

### What did you expect to see?

Either the error types returned should have been the same, or this should have been called out in 1.20 release notes.

### What did you see instead?

I could not find it mentioned on https://go.dev/doc/go1.20#errors

**Comment by mateusz834** [comment]
It only breaks when using direct type assertions, but with `errors.As` is should still work (it unwraps, `*tls.CertificateVerificationError` has an Unwrap method).
