### ISSUE TITLE
cmd/go: install pkg@version: print deprecation messages 

### ISSUE THREAD

**Issue by seankhliao** [golang/go#59230]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.21-2ef70d9d0f9 Tue Mar 21 06:53:28 2023 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/arccy/.cache/go-build"
GOENV="/home/arccy/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS="-trimpath "-ldflags=-s -w""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/arccy/.data/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/arccy/.data/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/arccy/sdk/gotip"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/arccy/sdk/gotip/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel go1.21-2ef70d9d0f9 Tue Mar 21 06:53:28 2023 +0000"
GCCGO="gccgo"
GOAMD64="v3"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
GOMOD="/home/arccy/tmp/testrepo0151/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build287293194=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```sh
$ go install go.seankhliao.com/testrepo0150@latest
go: downloading go.seankhliao.com/testrepo0150 v0.0.0-20230324184925-aa9dc37d2fb8
```

### What did you expect to see?

deprecation message printed like with `go get`

```sh
$ go get go.seankhliao.com/testrepo0150@latest
go: module go.seankhliao.com/testrepo0150 is deprecated: use v2
go: added go.seankhliao.com/testrepo0150 v0.0.0-20230324184925-aa9dc37d2fb8
```

### What did you see instead?

no deprecation message

cc @bcmills @matloob

**Comment by bcmills** [comment]
For reference, the code in `go get` that prints these messages is here:
https://cs.opensource.google/go/go/+/master:src/cmd/go/internal/modget/get.go;l=1604-1629;drc=2f2c5e41e7728cae99abd14e8bd5ffcfebf9df8e

And the code in `go install` that implements `go install pkg@version` is here:
https://cs.opensource.google/go/go/+/master:src/cmd/go/internal/work/build.go;l=843-874;drc=0aa14fca8c639c9ceba264dbf0d82bd53306aeaa

**Comment by ronaudinho** [comment]
perhaps adding `CheckDeprecation` right after [this line](https://cs.opensource.google/go/go/+/master:src/cmd/go/internal/load/pkg.go;l=3282) will fix this?

> Should go run also print deprecations and retractions?

- deprecations: the proposed change should affect `go install` or `go run` when it uses `pkg@version`, but not when only `pkg` is supplied. 

- retractions: I believe it is already handled [here](https://cs.opensource.google/go/go/+/master:src/cmd/go/internal/load/pkg.go;l=3273)
