### ISSUE TITLE
go1.20.2 Not able to compile with cgo

### ISSUE THREAD

**Issue by tejaskumark** [golang/go#59237]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/tejaskumar/.cache/go-build"
GOENV="/home/tejaskumar/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/tejaskumar/repo/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/tejaskumar/repo/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/tejaskumar/work/code/go/example/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build728345486=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
```
Directory structure --
example --> main.go
        -->lib
            lib.c
            lib.h
```
cat main.go
```
package main

// #include "lib/lib.h"
// #include <stdio.h>
// #include <stdlib.h>
import "C"
import (
	"fmt"
	"unsafe"
)

func main() {
	cstrin := C.CString("welcome")
	s1 := C.struct_s1{b: cstrin, a: 100}

	C.f32_123(&s1)
	cs := C.GoString(s1.b)
	fmt.Println(cs)
	fmt.Println(s1)
	C.free(unsafe.Pointer(cstrin))
}
```

cat lib/lib.c
```#include "lib.h"

#include <stdlib.h>
#include <stdio.h>

void printc(char *str, int *t)
{
     str = "Test";
     printf("%d\n", *t);
     *t = 30;
     printf("%s\n", str);
}

void f32_123(struct s1 *s)
{
     printf("%s\n", s->b);
     s->a = 10;
     s->b = "Hello123";
     printf("%d\n", s->a);
     printf("%s\n", s->b);
}
```

cat lib/lib.h
```struct s1
{
    int a;
    char *b;
};

void printc(char *str, int *t);
void f32_123(struct s1 *s);
```

### What did you expect to see?
Expecting that code should compile successfully, but somehow it is not. If documentation I have read correctly then I have to keep lib.c and lib.h into same directory with main.go file. But I am not sure if this can be achieved or I am doing something wrong.

- If I keep all the files into same directory example then compile is successful.
- If I keep lib.c and lib.h into subdir then compile fails

- If I remove one function f32_123 from main.go then also compile is successful and that is pretty strange and that is the reason opening this bug to get more understanding why compile has not issue with printc function when lib.h and lib.c is in subdir. 

### What did you see instead?

# example
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: /tmp/go-link-3024881602/000001.o: in function `_cgo_cf24297edd23_Cfunc_f32_123':
/tmp/go-build/cgo-gcc-prolog:49: undefined reference to `f32_123'
collect2: error: ld returned 1 exit status

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
