### ISSUE TITLE
net: panic on LookupHost when running in a libOS

### ISSUE THREAD

**Issue by thomasten** [golang/go#59242]
I'm not sure whether this can be considered a bug in Go, but let me explain. In my environment, rlim_max for RLIMIT_NOFILE is RLIM_INFINITY. This causes an overflow here:
https://github.com/golang/go/blob/aee9a19c559da6fd258a8609556d89f6fad2a6d8/src/net/lookup_unix.go#L148-L151

(rlim_cur has been set to rlimt_max here: https://github.com/golang/go/blob/aee9a19c559da6fd258a8609556d89f6fad2a6d8/src/os/rlimit.go#L27-L30)

As far as I could find out, on Linux it's not possible to set RLIMIT_NOFILE to anything greater than 0x7FFF_FFFF. So the overflow can't happen. I couldn't find out whether this is true for all Unix/POSIX systems supported by Go.

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/tho/.cache/go-build"
GOENV="/home/tho/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/tho/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/tho/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4248147521=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Run this on a system/libOS where rlim_max for RLIMIT_NOFILE is RLIM_INFINITY and force cgo lookup (e.g., with env var `RES_OPTIONS=rotate`):

```go
func main() {
	fmt.Println(net.LookupHost("localhost"))
}
```

### What did you expect to see?

```
[127.0.0.1] <nil>
```

### What did you see instead?

```
panic: makechan: size out of range

goroutine 1 [running]:
net.acquireThread.func1()
        net/net.go:690 +0x28
sync.(*Once).doSlow(0x680?, 0x4e3280?)
        sync/once.go:74 +0xc2
sync.(*Once).Do(...)
        sync/once.go:65
net.acquireThread()
        net/net.go:689 +0x31
net.cgoLookupIPCNAME({0x4f0a1e, 0x2}, {0x4f170d, 0x9})
        net/cgo_unix.go:136 +0x85
net.cgoLookupIP({0x516ff0, 0xc00001c098}, {0x4f0a1e, 0x2}, {0x4f170d, 0x9})
        net/cgo_unix.go:216 +0x2fa
net.cgoLookupHost({0x516ff0?, 0xc00001c098?}, {0x4f170d?, 0x9?})
        net/cgo_unix.go:49 +0x55
net.(*Resolver).lookupHost(0x5b44c0, {0x516ff0, 0xc00001c098}, {0x4f170d, 0x9})
        net/lookup_unix.go:59 +0xad
net.(*Resolver).LookupHost(0xc0000061a0?, {0x516ff0, 0xc00001c098}, {0x4f170d, 0x9})
        net/lookup.go:191 +0x15c
net.LookupHost(...)
        net/lookup.go:177
main.main()
        ./main.go:9 +0x3e
```

**Comment by ianlancetaylor** [comment]
Thanks.  Does https://go.dev/cl/479436 fix the problem?

**Comment by thomasten** [comment]
Thanks for your quick response. Yes, just tested it and your CL fixes the problem.
