### ISSUE TITLE
telemetry in the Go toolchain [PROPOSE: release it separately]

### ISSUE THREAD

**Issue by thealio** [golang/go#59244]
### Discussed in https://github.com/golang/go/discussions/58409

<div type='discussions-op-text'>

<sup>Originally posted by **rsc** February  8, 2023</sup>
**Feb 10 5pm US Eastern**: Thanks for the lively discussion everyone. It has given me plenty to think about. We are starting to go in circles, and actually new comments are increasingly rare, so I've locked this to give everyone their weekend back. Thanks again.

If anyone feels like there's something important that wasn't said in these 506 comments, please feel free to email me at rsc@golang.org.

**Feb 26** The current plan is to use [some form of opt-in](https://research.swtch.com/telemetry-opt-in) to collect telemetry.

- - -

How do software developers understand which parts of their software are being used and whether they are performing as expected? The modern answer is _telemetry_, which means software sending data to answer those questions back to a collection server.

I believe that open-source software projects need to explore new telemetry designs that help developers get the information they need to work efficiently and effectively, without collecting invasive traces of detailed user activity.

I have written a short series of blog posts about one such design, which I call _transparent telemetry_, because it collects as little as possible (kilobytes per year from each installation) and then publishes every bit that it collects, for public inspection and analysis.

I’d like to explore using transparent telemetry, or a system like it, in the Go toolchain, which I hope will help Go project developers and users alike. To be clear, I am only suggesting that the instrumentation be added to the Go command-line tools written and distributed by the Go team, such as the `go` command, the Go compiler, `gopls`, and `govulncheck`. I am _not_ suggesting that instrumentation be added by the Go compiler to all Go programs in the world: that’s clearly inappropriate.

Transparent telemetry has the following key properties:

 - The decisions about what metrics to collect are made in an open, public process.

 - The collection configuration is automatically generated from the actively tracked metrics: no data is collected that isn’t needed for the metrics.

 - The collection configuration is served using a tamper-evident transparent log, making it very difficult to serve different collection configurations to different systems.

 - The collection configuration is a cacheable, proxied Go module, so any privacy-enhancing local Go proxy already in use for ordinary modules will automatically be used for collection configuration. To further ameliorate concerns about tracking systems by the downloading of the collection configuration, each installation only bothers downloading the configuration each week with probability 10%, so that each installation only asks for the configuration about five times per year.

 - Uploaded reports only include total event counts over a full week, not any kind of time-ordered event trace.

 - Uploaded reports do not include user IDs, machine IDs, or any other kind of ID.

 - Uploaded reports only contain strings that are already known to the collection server: counter names, program names, and version strings repeated from the collection configuration, along with the names of functions in specific, unmodified Go toolchain programs for stack traces. The only types of non-string data in the reports are event counts, dates, and line numbers.

 - IP addresses exposed by the HTTP session that uploads the report are not recorded with the reports.

 - Thanks to [sampling](https://research.swtch.com/sample), only a constant number of uploaded reports are needed to achieve a specific accuracy target, no matter how many installations exist. Specifically, only about 16,000 reports are needed for 1% accuracy at a 99% confidence level. This means that _as new systems are added to the system, each system reports less often_. With a conservative estimate of two million Go installations, about 16,000 reporting each week corresponds to an overall reporting rate of well under 2% per week, meaning each installation would upload a report on average less than once per year.

 - The aggregate computed metrics are made public in graphical and tabular form.

 - The full raw data as collected is made public, so that project maintainers have no proprietary advantage or insights in their role as the direct data collector.

 - The system is on by default, but opting out is easy, effective, and persistent.

**Please read the [introductory blog post](https://research.swtch.com/telemetry-intro) for more background before commenting here.** You may also want to check out the [detailed design](https://research.swtch.com/telemetry-design) and [list of use cases](https://research.swtch.com/telemetry-uses).

</div>
----------------------------------------------------------------------------------------------------------------------------
Hi,
About the implementation of OpenTelemetry in Go language

I think that this feature should be released separately from the main Go code, and implemented with a separate package.

So users could have the power to choose to include telemetry or not into their OSs.
It should be released with a separate package   

I think that this solution should make everyone happy.

Because Devs surely can implement telemetry , but users shouldn't be forced to use it if they don't want to.

Thanks for your attention

**Comment by seankhliao** [comment]
this is clearly not understanding what is being proposed
