### ISSUE TITLE
 sigs.k8s.io/apiserver-runtime is not compatible with k8s.io/apiserver@0.25.0 or later

### ISSUE THREAD

**Issue by shanehooker** [golang/go#59246]
A compile error occurs when using these versions in go.mod:
	k8s.io/apiserver v0.25.0
	k8s.io/client-go v0.25.0
	k8s.io/klog v1.0.0
	sigs.k8s.io/apiserver-runtime v1.1.1

# sigs.k8s.io/apiserver-runtime/pkg/builder/rest
vendor/sigs.k8s.io/apiserver-runtime/pkg/builder/rest/provider.go:60:10: cannot use parentPlumbedStorageGetterUpdaterProvider{ } (value of type parentPlumbedStorageGetterUpdaterProvider) as type "k8s.io/apiserver/pkg/registry/rest".Storage in return statement:
	parentPlumbedStorageGetterUpdaterProvider does not implement "k8s.io/apiserver/pkg/registry/rest".Storage (missing Destroy method)

The Storage interface defined in k8s.io/apiserver v0.25.0
type Storage interface {
	// New returns an empty object that can be used with Create and Update after request data has been put into it.
	// This object must be a pointer type for use with Codec.DecodeInto([]byte, runtime.Object)
	New() [runtime](https://pkg.go.dev/k8s.io/apimachinery/pkg/runtime).[Object](https://pkg.go.dev/k8s.io/apimachinery/pkg/runtime#Object)

	// Destroy cleans up its resources on shutdown.
	// Destroy has to be implemented in thread-safe way and be prepared
	// for being called more than once.
	Destroy()
}

**Comment by ianlancetaylor** [comment]
This sounds like a bug in k8s.io, not a bug in the Go toolchain or libraries.  It should be reported in the k8s.io bug tracker.  Please comment if you disagree.
