### ISSUE TITLE
sync/map: misleading documentation about the map.LoadOrStore functions

### ISSUE THREAD

**Issue by ShayNehmad-RecoLabs** [golang/go#59251]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.20.1
</pre>

### Does this issue reproduce with the latest release?

Yep

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

Not super relevant, this is an issue with the documentation

### What did you expect to see?

The documentation for LoadOrStore says the following:

> LoadOrStore returns the existing value for the key if present. Otherwise, it stores and returns the given value.
> The loaded result is true if the value was loaded, false if stored.

However, this is very misleading: while TECHNICALLY this is correct, it's very easy to understand it backwards. look at this test:

```
func Test(t *testing.T) {
   exampleMap := new(sync.Map)
   val, x := policyEnablement.LoadOrStore("key1", true)
   fmt.Println(val, x)
   val, x = policyEnablement.LoadOrStore("key1", false)
   fmt.Println(val, x)
}
```

The output is:

```
=== RUN   Test
true false // <--------- "false if stored" 
true true  // <--------- "true if the value was loaded" 
```

I think that clarifying the documentation with slightly more verbose explanation would help.

**Comment by seankhliao** [comment]
It looks correct, "loaded" refers to the return value named "loaded".
The backwards interpretation doesn't really make any sense.
