### ISSUE TITLE
golang/website: erratum in checksum database documentation

### ISSUE THREAD

**Issue by bwsd0** [golang/go#59258]
There appears to be an error in the [checksum database documentation:

> The checksum database allows for global consistency and reliability for all publicly available module versions. _It makes untrusted proxies possible_ since they can’t serve the wrong code without it going unnoticed. (emphasis added)

The text should read: "It makes untrusted proxies impossible" or "It deters
untrusted proxies".

### What is the URL of the page with the issue?

https://go.dev/ref/mod#checksum-database

**Comment by seankhliao** [comment]
The website is correct, you no longer have to trust the proxy as you can verify the contents yourself.
