### ISSUE TITLE
affected/package: [go install] go install ignore $HOME/.gitconfig ssh settings

### ISSUE THREAD

**Issue by o0flame** [golang/go#59261]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.18
</pre>

### Does this issue reproduce with the latest release?
our code base cannot use other go version, so no.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>

I am using mac 13.0.1 with m1 chip.
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18.10"
GCCGO="gccgo"
GOAMD64="v1"

</pre></details>

### What did you do?

There are url redirecting under ~/.gitconfig, like [url "git@code.xxxx.org:"] insteadOf = https://code.xxxx.org/, 
I tried to `go install`, but it still fetched from https links in https://code.xxxx.org/. 

### What did you expect to see?
`go install` installs packages through ssh instead of https. 

### What did you see instead?
`go install` installs packages still through https, but our org limits the access to ssh only.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
