### ISSUE TITLE
debug/elf: ElfFile.SectionByType() should return a list of matched sections. 

### ISSUE THREAD

**Issue by BrytonLee** [golang/go#59287]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.19.5

</pre>

### Does this issue reproduce with the latest release?
Yes, there is no change between go 1.19.5 to the latest. The affected file and line number is here: https://github.com/golang/go/blob/master/src/debug/elf/file.go#L246

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/lichengdong/Library/Caches/go-build"
GOENV="/Users/lichengdong/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/lichengdong/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/lichengdong/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.19.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.19.5/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/g4/4_y2t8q179s1n1h40218_3rm0000gn/T/go-build2820814962=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

Just send a ELF file for debug/elf to parse it. Then call SectionByType(elf.SHT_PROGBITS), it will return first section with type equals to elf.SHT_PROGBITS. But in a normal ELF file on Linux, there is more than on elf.SHT_PROGBITS section in fact. 

### What did you expect to see?

returns a list of matched sections. 

### What did you see instead?

None

**Comment by ianlancetaylor** [comment]
Unfortunately we can't change the current method, as that would break existing programs.  `SectionByType` is only useful for section types that normally only occur once, such as `SHT_DYNAMIC`.

**Comment by ianlancetaylor** [comment]
That kind of new API should go through the proposal process: see https://go.dev/s/proposal.  But I'm not sure it's really helpful; why not just loop through the sections yourself?  Would anybody really call `SectionAllByType`?

**Comment by BrytonLee** [comment]
Yeah, sure I can iterate all sections and find out what I need.  But, I am a live sample that I was confused by SectionByType(), literally,  it implies that user just need to specify section type and get what they need.  I am not sure this will continue to confuse other developers as well.  :-)

**Comment by ianlancetaylor** [comment]
I agree that `SectionByType` is not all that useful, and it may have been a mistake to add it.  But now that it exists we aren't going to change it.
