### ISSUE TITLE
x/pkgsite: package removal request for github.com/senzing/initdatabase

### ISSUE THREAD

**Issue by docktermj** [golang/go#59299]
### What is the path of the package that you would like to have removed?

github.com/senzing/initdatabase
 
### Are you the owner of this package?

Yes.  You'll see me as a contributor on https://github.com/Senzing/init-database
 
### What is the reason that you could not retract this package instead?

We moved the package to `github.com/senzing/init-database`

and now we're seeing errors like this:

```console
$ go get github.com/senzing/init-database
go: github.com/senzing/init-database@v0.1.8: parsing go.mod:
	module declares its path as: github.com/senzing/initdatabase
	        but was required as: github.com/senzing/init-database
```

**Comment by seankhliao** [comment]
The module line on v0.1.8 does have the old name.
Note that you won't be able to change this.
You most likely want to retract the old versions, retractions work across redirects even with mismatched module names.

Closing as there's nothing to do.

**Comment by seankhliao** [comment]
use the retract directive, it works across renames.
