### ISSUE TITLE
x/playground: 1.19 is missing

### ISSUE THREAD

**Issue by rittneje** [golang/go#59303]
Currently the playground lists "Go 1.20", "Go 1.21", and "Go dev branch". 1.19 is missing, and 1.21 was not released yet.

![image](https://user-images.githubusercontent.com/28784688/228405972-e29d753b-d846-4942-98f8-02dfd740e87a.png)

**Comment by dmitshur** [comment]
Thanks for reporting.

It might be because [CL 467955](https://go.dev/cl/467955) (CC @petergeorgas) removed the `-prev` flag, which is still used, and https://goprevplay.golang.org/version ends up deploying tip rather than 1.19.7.

CC @findleyr.

**Comment by findleyr** [comment]
Fix has been deployed.
