### ISSUE TITLE
Using errors.As in goroutines leads to abnormal memory consumption

### ISSUE THREAD

**Issue by andvary** [golang/go#59308]
### What version of Go are you using (`go version`)?

<pre>
$ go version
Go version: go1.20.2

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
Ubuntu 20.04.6 LTS, amd64
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
Running the following snippet then obtaining a memory profile (net/http/pprof endpoint) once I see the "goroutines done"  message.

```
package main

import (
	"errors"
	"fmt"
	"sync"
	"time"
)

var myErr = errors.New("my test error")

func main() {
	var wg sync.WaitGroup
	for i := 0; i < 1_000_000; i++ {
		go foo(&wg)
	}
	wg.Wait()
	fmt.Println("goroutines done")

	time.Sleep(5 * time.Minute)
}

func foo(wg *sync.WaitGroup) {
	wg.Add(1)
	err := fmt.Errorf("test err: %w", myErr)
	if errors.As(err, &myErr) {
		time.Sleep(10 * time.Millisecond)
	}
	wg.Done()
}
```

### What did you expect to see?
I expected memory used by the goroutines to be garbage-collected once they have returned, so that my program uses a very small amount of memory after wg.Wait() unblocks.

### What did you see instead?
The obtained memory profile shows a huge amount of memory allocated by fmt.Errorf (memory profile for ppfof: [test.zip](https://github.com/golang/go/files/11099638/test.zip)) The fact, that the program consumes an abnormal amount of memory can be also verified using the "top" utility.

**Comment by seankhliao** [comment]
This is a bug in your code: you're reusing the argument to As with the same types, constructing a very long chain. of errors from each invocation of fmt.Errorf

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by andvary** [comment]
Ok, sorry for the trouble and thanks for taking your time to explain the issue to me.
