### ISSUE TITLE
cmd/compile: 3.14% regression in AppendMsgResyncTargetsInfo-8 sec/op at 61bc17f

### ISSUE THREAD

**Issue by mknyszek** [golang/go#59319]
Discovered a regression in sec/op of 3.14% for benchmark AppendMsgResyncTargetsInfo-8 at 61bc17f.

CC @randall77 

Note: This might not matter. This benchmark has a weird history.

**Comment by randall77** [comment]
I don't see any differences in assembly for any of the of the functions that appear in a cpu profile of this benchmark.
Closing, probably just code alignment issues.
