### ISSUE TITLE
cmd/compile: linkname symbol redeclared, unknown line number

### ISSUE THREAD

**Issue by ii64** [golang/go#59313]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.20
</pre>

### Does this issue reproduce with the latest release?
Yes, go1.20, go1.21, tip

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
[go playground]
</pre></details>

### What did you do?

```go
package main

import (
	"fmt"
	"unsafe"
)

type M struct {
	p string
}

var k = []*M{
	{"a"}, {"b"}, {"c"},
}

//go:linkname x main.k
var x unsafe.Pointer

func main() {
	fmt.Println(k)
	fmt.Println(x)
}
```
Go playground link: https://go.dev/play/p/TzmdH78MJj-

### What did you expect to see?

Address of `k`

### What did you see instead?

`./prog.go:14:5: <unknown line number>: symbol main.k redeclared`

**Comment by mknyszek** [comment]
There should be a better error message, but to clarify `go:linkname` does actually define a new symbol, hence the message. The error overall is expected.

Since `go:linkname` is meant for internal low-level use-cases, we're inclined to close this issue.
