### ISSUE TITLE
net: do not wait on EAGAIN from lossy packet conn

### ISSUE THREAD

**Issue by gopherbot** [golang/go#5932]
by **swhite@fitstar.com**:

<pre>When writing to a connection created by net.Dial(&quot;unixgram&quot;,
&quot;/dev/log&quot;) I will occasionally get an EAGAIN returned.  When that happens the
internal WaitWrite call will block forever if no deadline is set.  I can break by
setting a deadline.  Writing to the connection after the timeout error works so it looks
like the WaitWrite is not working properly for this type of socket.  It happens for both
the Write and the WriteToUnix calls.

I don't know how to create an EAGAIN from a unixgram type socket so I don't have a test
case.  It was very difficult to reproduce this against rsyslog.  I'm hoping a socket
expert can figure it out an easy way to reproduce this.

This bug started on go1.1 and is reproducible on go1.1.1 (never saw it on 1.0.x). 
amd64/linux (ubuntu 12.04)</pre>

**Comment by driskell** [comment]
Hello. A user of mine is seeing a similar issue as in Comment 12. Is there any useful information we can provide to help with this? Thanks

**Comment by chendo** [comment]
I've also seen this happen with our setup where we mount in `/dev/log` into our Docker containers to write to

**Comment by a13xb** [comment]
This *may* have been fixed somewhere between 1.3 and 1.3.1. [The sample from comment 17](https://play.golang.org/p/vu12qIyPil) fails 100% of the time on 1.3 and succeeds 100% of the time on 1.3.1 for me.

**Comment by ianlancetaylor** [comment]
@driskell @chendo which version of Go are you using when you see the problem?  Which kernel version?  Thanks.

**Comment by bradfitz** [comment]
Closing due to timeout.
