### ISSUE TITLE
x/vuln: govulncheck has broken output for only stdlib vulns

### ISSUE THREAD

**Issue by bitcynth** [golang/go#59323]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.1 linux/amd64
</pre>

### Does this issue reproduce at the latest version of golang.org/x/vuln?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

I ran `govulncheck` on a package that only returned a vulnerability in a Go standard library. (Specifically [GO-2023-1621](https://pkg.go.dev/vuln/GO-2023-1621))

### What did you expect to see?

I expected something like the following summary line in the output:
```
Your code is affected by 1 vulnerability from the Go standard library.
```

### What did you see instead?

I saw the following summary line in the output:
```
Your code is affected by 1 vulnerability from 0 modulesthe Go standard library.
```

I could immediately see that this is because the case of only having stdlib vulns is simply not handled in the template: [internal/scan/output.tmpl#17](https://github.com/golang/vuln/blob/9550759f8614ff679d9415f29f0a83a5abd6d439/internal/scan/output.tmpl#L17)

**Comment by mknyszek** [comment]
CC @golang/vulndb
