### ISSUE TITLE
goproxy env doesn't work when set file://xxxxxx on windows, show "invalid file:// proxy URL with non-path elements"

### ISSUE THREAD

**Issue by tooyangtoonaive** [golang/go#59342]
### What version of Go are you using (`go version`)?
go1.20.2

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

windows 10

PS D:\workspace\go_test> go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\myname\AppData\Local\go-build
set GOENV=C:\Users\myname\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\Programs\go\gopath\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\Programs\go\gopath
set GOPRIVATE=
set GOPROXY=file://D:/Programs/go/gopath/pkg/mod/cache/download
set GOROOT=D:\Programs\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Programs\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.20.2
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=D:\workspace\go_test\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\myname\AppData\Local\Temp\go-build1958736271=/tmp/go-build -gno-record-gcc-switches

### What did you do?
set GOPROXY=file://D:/Programs/go/gopath/pkg/mod/cache/download
go mod tidy

### What did you expect to see?
It should read cache from local file system

### What did you see instead?

PS D:\workspace\go_test> go mod tidy
go: finding module for package go.bug.st/serial
example/hello imports
        **go.bug.st/serial: invalid file:// proxy URL with non-path elements: file://D:/Programs/go/gopath/pkg/mod/cache/download**

PS D:\workspace\go_test> ls

    dir: D:\workspace\go_test

Mode                 LastWriteTime         Length Name

-a----         2023/3/31     13:04             44 go.mod
-a----         2023/3/29     20:22            324 zc.go

**Comment by seankhliao** [comment]
try GOPROXY=file:///D:/Programs/go/gopath/pkg/mod/cache/download

**Comment by tooyangtoonaive** [comment]
> try GOPROXY=file:///D:/Programs/go/gopath/pkg/mod/cache/download
Doesn't work too:




```
PS D:\workspace\go_test> go mod tidy
go: finding module for package go.bug.st/serial
go.bug.st/serial@v1.5.0: verifying module: go.bug.st/serial@v1.5.0: Get "https://sum.golang.org/lookup/go.bug.st/serial@v1.5.0": dial tcp 172.217.24.241:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

```

**Comment by seankhliao** [comment]
you'll also need to disable sumdb for those modules

otherwise it looks like it works with file: schemes

closing as there is no bug
