### ISSUE TITLE
affected/package: runtime  relocation target runtime.getg not defined

### ISSUE THREAD

**Issue by introspection3** [golang/go#59344]
### What version of Go are you using (`go version`)?
all
<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?
relocation target runtime.getg not defined

package main

import "unsafe"

func main() {
	println(getg())
}

//go:linkname getg runtime.getg
func getg() unsafe.Pointer

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by randall77** [comment]
`//go:linkname` is intended for internal low-level use. It will not work for magic runtime functions like `getg`.
