### ISSUE TITLE
net/http: solaris 11.3  protocol wrong type for socket

### ISSUE THREAD

**Issue by karlik8899** [golang/go#59359]
### What version of Go are you using (`go version`)?

<pre>
go version go1.20.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOOS="linux"
GOPATH="/home/x/go"
GOPROXY="https://proxy.golang.org"
GOROOT="/opt/go1.20.2"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/go1.20.2/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build713374419=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
       c := http.Client{Timeout: time.Duration(3) * time.Second}
        req, err := http.NewRequest(http.MethodGet, "http://jenkins.x.x:8080/job/"+app+"/lastStableBuild/artifact/", nil)
        panicOnError(err)
        req.SetBasicAuth(user, pwd)
        resp, err := c.Do(req)
        panicOnError(err)

env GOOS=solaris GOARCH=amd64 go build .

### What did you expect to see?
no error
This doesn't work for me since version 1.19, the last working version was 1.18.
Is it a bug or is solaris 11.3 no longer supported?

### What did you see instead?
Get "http://jenkins.x.x:8080/job/celllocker/lastStableBuild/artifact/": dial tcp: lookup jenkins.nms.ip on x.x.x.x:53: dial udp x.x.x.x:53: socket: protocol wrong type for socket

**Comment by ianlancetaylor** [comment]
CC @golang/solaris 

The error is that the `socket` system call is returning `EPROTOTYPE`, which is documented as "The socket type is not supported by the protocol."  I don't understand how that could be; as far as I can tell we always pass `0` for the protocol.  What are the contents of the file `/etc/netconfig` on your system?

**Comment by karlik8899** [comment]
<details><summary><code>/etc/netconfig</code> Output</summary><br><pre>
#
# Copyright 1999 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident "%Z%%M% %I%     %E% SMI"
#
# The "Network Configuration" File.
#
# Each entry is of the form:
#
#       <network_id> <semantics> <flags> <protofamily> <protoname> \
#               <device> <nametoaddr_libs>
#
# The "-" in <nametoaddr_libs> for inet family transports indicates
# redirection to the name service switch policies for "hosts" and
# "services". The "-" may be replaced by nametoaddr libraries that
# comply with the SVr4 specs, in which case the name service switch
# will not be used for netdir_getbyname, netdir_getbyaddr,
# gethostbyname, gethostbyaddr, getservbyname, and getservbyport.
# There are no nametoaddr_libs for the inet family in Solaris anymore.
#
udp6       tpi_clts      v     inet6   udp    /dev/udp6       -
tcp6       tpi_cots_ord  v     inet6   tcp    /dev/tcp6       -
udp        tpi_clts      v     inet    udp    /dev/udp        -
tcp        tpi_cots_ord  v     inet    tcp    /dev/tcp        -
rawip      tpi_raw       -     inet    -      /dev/rawip      -
ticlts     tpi_clts      v    loopback -      /dev/ticlts     straddr.so
ticotsord  tpi_cots_ord  v    loopback -      /dev/ticotsord  straddr.so
ticots     tpi_cots      v    loopback -      /dev/ticots     straddr.so
</pre></details>

**Comment by karlik8899** [comment]
if it helps here is the output from sotruss
[sotruss-out-go1.18.txt](https://github.com/golang/go/files/11145137/sotruss-out-go1.18.txt)
[sotruss-out-go1.20.txt](https://github.com/golang/go/files/11145139/sotruss-out-go1.20.txt)

**Comment by ianlancetaylor** [comment]
Thanks for the data.  Unfortunately I have no idea what is going on.

**Comment by xmikus01** [comment]
This [CL 403394](https://go-review.googlesource.com/c/go/+/403394) and [commit](https://github.com/golang/go/commit/3e00bd0ae4482064aa9eac0695078b1096ee913a) introduced support for the accept4 syscall on Solaris (commit message refers to Solaris 11.4), but unfortunately also [introduced passing of SOCK_* flags](https://github.com/golang/go/blob/3e00bd0ae4482064aa9eac0695078b1096ee913a/src/net/sock_cloexec.go#L20) to the socket syscall unconditionally for all versions of Solaris  by introducing `solaris` to build flags of `src/net/sock_cloexec.go`.

However, these [SOCK_* flags are only available only in Solaris 11.4](https://docs.oracle.com/cd/E88353_01/html/E37843/socket-3c.html) and later:

> Support for SOCK_* flags as part of the type parameter was added to Oracle Solaris in the 11.4 release.

@tklauser @ianlancetaylor The question is, which Solaris version is officially supported by the Go team? If it is also 11.3, then of course this is a regression...

**Comment by ianlancetaylor** [comment]
On https://go.dev/wiki/MinimumRequirements we claim to support Solaris 11+, which presumably includes 11.3.

So I think we may need to revert https://go.dev/cl/403634.

**Comment by ianlancetaylor** [comment]
@xmikus01 Thanks for digging through this.

**Comment by tklauser** [comment]
I think this can be closed now that https://go.dev/cl/403634 and https://go.dev/cl/422375 were reverted.
