### ISSUE TITLE
runtime/trace: TestTraceSymbolize broken on solaris/amd64 as of CL 463835

### ISSUE THREAD

**Issue by bcmills** [golang/go#59350]
https://build.golang.org/log/ec79810c83e1ddca4758df05fd4b8f0351fe462a:
```
solaris-amd64-oraclerel at ba71817390f78bf8c479dc65d1bc51db98d667a7
…
--- FAIL: TestTraceSymbolize (0.24s)
    trace_stack_test.go:285: Did not match event GoSysCall with stack
          syscall.read					 :0
          syscall.Read					 :0
          internal/poll.ignoringEINTRIO			 :0
          internal/poll.(*FD).Read			 :0
          os.(*File).read				 :0
          os.(*File).Read				 :0
          runtime/trace_test.TestTraceSymbolize.func11	 :0

        Seen 43 events of the type
…
        Offset 855
          syscall.Read					/go/src/syscall/syscall_unix.go:181
          internal/poll.ignoringEINTRIO			/go/src/internal/poll/fd_unix.go:793
          internal/poll.(*FD).Read			/go/src/internal/poll/fd_unix.go:163
          os.(*File).read				/go/src/os/file_posix.go:31
          os.(*File).Read				/go/src/os/file.go:118
          runtime/trace_test.TestTraceSymbolize.func11	/go/src/runtime/trace/trace_stack_test.go:105
…
        Offset 2672
          syscall.Read					/go/src/syscall/syscall_unix.go:181
          internal/poll.ignoringEINTRIO			/go/src/internal/poll/fd_unix.go:793
          internal/poll.(*FD).Read			/go/src/internal/poll/fd_unix.go:163
          os.(*File).read				/go/src/os/file_posix.go:31
          os.(*File).Read				/go/src/os/file.go:118
          runtime/trace_test.TestTraceSymbolize.func11	/go/src/runtime/trace/trace_stack_test.go:105
```

This failure mode seems to have been introduced by [CL 463835](https://go.dev/cl/463835). It isn't clear to me whether it affects `illumos` because the test results are blocked by #58967.

(attn @golang/solaris @felixge @prattmic)

**Comment by prattmic** [comment]
[`syscall.read`](https://cs.opensource.google/go/go/+/master:src/syscall/zsyscall_solaris_amd64.go;l=808) calls [`syscall.sysvicall6`](https://cs.opensource.google/go/go/+/master:src/syscall/asm_solaris_amd64.s;l=11), which is a simple jump to [`runtime.syscall_sysvicall6`](https://cs.opensource.google/go/go/+/master:src/runtime/syscall_solaris.go;l=35).

I'd guess that one of those latter frames doesn't have proper framepointer handling.

**Comment by bcmills** [comment]
Looks like that call sequence does also apply to `illumos` (attn @golang/illumos), so adding that tag.

**Comment by felixge** [comment]
> [`syscall.read`](https://cs.opensource.google/go/go/+/master:src/syscall/zsyscall_solaris_amd64.go;l=808) calls [`syscall.sysvicall6`](https://cs.opensource.google/go/go/+/master:src/syscall/asm_solaris_amd64.s;l=11), which is a simple jump to [`runtime.syscall_sysvicall6`](https://cs.opensource.google/go/go/+/master:src/runtime/syscall_solaris.go;l=35).
> 
> I'd guess that one of those latter frames doesn't have proper framepointer handling.

Sounds plausible. It would probably nice to fix that. But for now we could also try to special-case the syscall test expectations for solaris and illumos? I could probably send a patch for the latter quickly, the former might take more time.

**Comment by felixge** [comment]
> Change https://go.dev/cl/481336 mentions this issue: `runtime/trace: Fix TestTraceSymbolize on solaris and illumos`

This should fix the problem for now.
