### ISSUE TITLE
proxy.golang.org: problems requesting ssh based git site to pkg.go.dev

### ISSUE THREAD

**Issue by supertxtnet** [golang/go#59354]
### What is the URL of the page with the issue?

https://pkg.go.dev/supertxt.net/cats

### What is your user agent?

Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0

### Screenshot

![Uploading Screenshot from 2023-03-31 16-44-55.png…]()

### What did you do?

I published a Go-based git repository to a server that uses the git ssh protocol. The site implements the module proxy protocol. https://pkg.go.dev/cmd/go#hdr-Module_proxy_protocol and provides the ssh url of the git repo. The following is the meta tag that is given when accessing this url: https://supertxt.net/git/cats?go-get=1

```
<meta name="go-import" content="supertxt.net/git/cats git ssh://nobody@supertxt.net/git/cats">
```

### What did you expect to see?

It is expected that the new Go packages can be added to the pkg.go.dev site.

### What did you see instead?

Instead, the screenshot stays as it is. It's clear from the site's logs that the service accesses the https URL, but it never clones using ssh using the url given in the meta tag.

**Comment by hyangah** [comment]
pkg.go.dev finds modules from proxy.golang.org and
proxy.golang.org supports only https:// git protocol (not `git+ssh://`). 

Even with `git+ssh://` enabled, it doesn't look like proxy can fetch data from the repo. 
Can you please arrange to serve using the https protocol? Thank you!

```
$ GOMODCACHE=/tmp/cache GOPRIVATE=* go mod download -x supertxt.net/git/cats@v0.1.0
# get https://supertxt.net/git/cats?go-get=1
# get https://supertxt.net/git/cats?go-get=1: 200 OK (0.162s)
mkdir -p /tmp/cache/cache/vcs # git3 ssh://nobody@supertxt.net/git/cats
# lock /tmp/cache/cache/vcs/5036be04affce43ea67c463aac9d1c179b6e55c9f8d713eadbb0f442f8bbb14f.lock
# /tmp/cache/cache/vcs/5036be04affce43ea67c463aac9d1c179b6e55c9f8d713eadbb0f442f8bbb14f for git3 ssh://nobody@supertxt.net/git/cats
cd /tmp/cache/cache/vcs/5036be04affce43ea67c463aac9d1c179b6e55c9f8d713eadbb0f442f8bbb14f; git tag -l
0.005s # cd /tmp/cache/cache/vcs/5036be04affce43ea67c463aac9d1c179b6e55c9f8d713eadbb0f442f8bbb14f; git tag -l
cd /tmp/cache/cache/vcs/5036be04affce43ea67c463aac9d1c179b6e55c9f8d713eadbb0f442f8bbb14f; git ls-remote -q origin
0.095s # cd /tmp/cache/cache/vcs/5036be04affce43ea67c463aac9d1c179b6e55c9f8d713eadbb0f442f8bbb14f; git ls-remote -q origin
go: supertxt.net/git/cats@v0.1.0: invalid version: git ls-remote -q origin in /tmp/cache/cache/vcs/5036be04affce43ea67c463aac9d1c179b6e55c9f8d713eadbb0f442f8bbb14f: exit status 128:
	Host key verification failed.
	fatal: Could not read from remote repository.
	
	Please make sure you have the correct access rights
	and the repository exists.
```

**Comment by supertxtnet** [comment]
This error occurs because the host key isn't yet known by the ssh client. To automatically add it as a known host on first connection, but complain if that host key ever changes you can run the above command like this. Also, generate a new ssh client key for identification purposes.

```
ssh-keygen -q -t rsa -N '' -f ~/.ssh/id_rsa
GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=accept-new" GOMODCACHE=/tmp/cache GOPRIVATE=* go mod download -x supertxt.net/git/cats@v0.1.0
```
This works fine with the site:

```
# get https://supertxt.net/git/cats?go-get=1
# get https://supertxt.net/git/cats?go-get=1: 200 OK (0.170s)
mkdir -p /tmp/cache/cache/vcs # git3 ssh://nobody@supertxt.net/git/cats
# lock /tmp/cache/cache/vcs/5036be04affce43ea67c463aac9d1c179b6e55c9f8d713eadbb0f442f8bbb14f.lock
mkdir -p /tmp/cache/cache/vcs/5036be04affce43ea67c463aac9d1c179b6e55c9f8d713eadbb0f442f8bbb14f # git3 ssh://nobody@supertxt.net/git/cats
cd /tmp/cache/cache/vcs/5036be04affce43ea67c463aac9d1c179b6e55c9f8d713eadbb0f442f8bbb14f; git init --bare
0.006s # cd /tmp/cache/cache/vcs/5036be04affce43ea67c463aac9d1c179b6e55c9f8d713eadbb0f442f8bbb14f; git init --bare
cd /tmp/cache/cache/vcs/5036be04affce43ea67c463aac9d1c179b6e55c9f8d713eadbb0f442f8bbb14f; git remote add origin -- ssh://nobody@supertxt.net/git/cats
0.003s # cd /tmp/cache/cache/vcs/5036be04affce43ea67c463aac9d1c179b6e55c9f8d713eadbb0f442f8bbb14f; git remote add origin -- ssh://nobody@supertxt.net/git/cats
cd /tmp/cache/cache/vcs/5036be04affce43ea67c463aac9d1c179b6e55c9f8d713eadbb0f442f8bbb14f; git tag -l
0.002s # cd /tmp/cache/cache/vcs/5036be04affce43ea67c463aac9d1c179b6e55c9f8d713eadbb0f442f8bbb14f; git tag -l
cd /tmp/cache/cache/vcs/5036be04affce43ea67c463aac9d1c179b6e55c9f8d713eadbb0f442f8bbb14f; git ls-remote -q origin
0.520s # cd /tmp/cache/cache/vcs/5036be04affce43ea67c463aac9d1c179b6e55c9f8d713eadbb0f442f8bbb14f; git ls-remote -q origin
cd /tmp/cache/cache/vcs/5036be04affce43ea67c463aac9d1c179b6e55c9f8d713eadbb0f442f8bbb14f; git -c log.showsignature=false log --no-decorate -n1 '--format=format:%H %ct %D' ebd998e49e96e35ad6b12a71cda3f0f49bcd9fe7 --
0.003s # cd /tmp/cache/cache/vcs/5036be04affce43ea67c463aac9d1c179b6e55c9f8d713eadbb0f442f8bbb14f; git -c log.showsignature=false log --no-decorate -n1 '--format=format:%H %ct %D' ebd998e49e96e35ad6b12a71cda3f0f49bcd9fe7 --
cd /tmp/cache/cache/vcs/5036be04affce43ea67c463aac9d1c179b6e55c9f8d713eadbb0f442f8bbb14f; git fetch -f --depth=1 origin refs/tags/v0.1.0:refs/tags/v0.1.0
0.733s # cd /tmp/cache/cache/vcs/5036be04affce43ea67c463aac9d1c179b6e55c9f8d713eadbb0f442f8bbb14f; git fetch -f --depth=1 origin refs/tags/v0.1.0:refs/tags/v0.1.0
cd /tmp/cache/cache/vcs/5036be04affce43ea67c463aac9d1c179b6e55c9f8d713eadbb0f442f8bbb14f; git -c log.showsignature=false log --no-decorate -n1 '--format=format:%H %ct %D' refs/tags/v0.1.0 --
0.002s # cd /tmp/cache/cache/vcs/5036be04affce43ea67c463aac9d1c179b6e55c9f8d713eadbb0f442f8bbb14f; git -c log.showsignature=false log --no-decorate -n1 '--format=format:%H %ct %D' refs/tags/v0.1.0 --
cd /tmp/cache/cache/vcs/5036be04affce43ea67c463aac9d1c179b6e55c9f8d713eadbb0f442f8bbb14f; git cat-file blob ebd998e49e96e35ad6b12a71cda3f0f49bcd9fe7:go.mod
0.002s # cd /tmp/cache/cache/vcs/5036be04affce43ea67c463aac9d1c179b6e55c9f8d713eadbb0f442f8bbb14f; git cat-file blob ebd998e49e96e35ad6b12a71cda3f0f49bcd9fe7:go.mod
cd /tmp/cache/cache/vcs/5036be04affce43ea67c463aac9d1c179b6e55c9f8d713eadbb0f442f8bbb14f; git cat-file blob ebd998e49e96e35ad6b12a71cda3f0f49bcd9fe7:go.mod
0.002s # cd /tmp/cache/cache/vcs/5036be04affce43ea67c463aac9d1c179b6e55c9f8d713eadbb0f442f8bbb14f; git cat-file blob ebd998e49e96e35ad6b12a71cda3f0f49bcd9fe7:go.mod
cd /tmp/cache/cache/vcs/5036be04affce43ea67c463aac9d1c179b6e55c9f8d713eadbb0f442f8bbb14f; git cat-file blob ebd998e49e96e35ad6b12a71cda3f0f49bcd9fe7:go.mod
0.002s # cd /tmp/cache/cache/vcs/5036be04affce43ea67c463aac9d1c179b6e55c9f8d713eadbb0f442f8bbb14f; git cat-file blob ebd998e49e96e35ad6b12a71cda3f0f49bcd9fe7:go.mod
cd /tmp/cache/cache/vcs/5036be04affce43ea67c463aac9d1c179b6e55c9f8d713eadbb0f442f8bbb14f; git cat-file blob ebd998e49e96e35ad6b12a71cda3f0f49bcd9fe7:go.mod
0.001s # cd /tmp/cache/cache/vcs/5036be04affce43ea67c463aac9d1c179b6e55c9f8d713eadbb0f442f8bbb14f; git cat-file blob ebd998e49e96e35ad6b12a71cda3f0f49bcd9fe7:go.mod
cd /tmp/cache/cache/vcs/5036be04affce43ea67c463aac9d1c179b6e55c9f8d713eadbb0f442f8bbb14f; git -c core.autocrlf=input -c core.eol=lf archive --format=zip --prefix=prefix/ ebd998e49e96e35ad6b12a71cda3f0f49bcd9fe7
0.078s # cd /tmp/cache/cache/vcs/5036be04affce43ea67c463aac9d1c179b6e55c9f8d713eadbb0f442f8bbb14f; git -c core.autocrlf=input -c core.eol=lf archive --format=zip --prefix=prefix/ ebd998e49e96e35ad6b12a71cda3f0f49bcd9fe7
```

**Comment by hyangah** [comment]
@supertxtnet the module proxy fetches from a fresh new container every time and doesn't keep the host keys around. One may propose to skip the host key check but that is insecure. Before disabling git+ssh protocol, we analyzed the existing module versions and we found git+ssh usage for public Go modules is rare. Is there a reason that your modules need to be hosted on git+ssh? If it is meant to be used by only a small number of users who trust and accept new host keys, couldn't they use GOPRIVATE option?

**Comment by supertxtnet** [comment]
The supertxt ecosystem is about trying to encourage the use of simple text, SSH, and [command-specific hosting environments](https://supertxt.net/intro-to-ssc.html) that are flexible enough for hosting in small intranets, and also the internet. This is demonstrated with the [supertxt.net](https://supertxt.net) internet site itself. The website portion is available, but only via simple static hosting for better discoverability. Adding support for git's https protocol would be non-trivial just so that the site can be more like github, and it takes away from the message that SSH is secure, and usable with a unix philosophy.

In terms of security, SSH itself provides an encrypted channel to help prevent third party sniffing of data. The hostkey approach provides some protection against MITM based on a time of first use (tofu) approach. It's not perfect, but neither is the root CA approach of the web. Project Gemini uses a similar tofu with its non-web browsing technology. As an added measure of security all of the git commits are signed on the supertxt site.

This is not necessarily meant to be used by a small number of users, nor is it private, so GOPRIVATE doesn't seem like a good option. It would have a funny smell. Also, this still won't allow the Go packages to be seen on the pgksite, which I feel is an important path to discoverability and usability of the supertxt tech that we've made available.

Since you're using containers for the fetching and indexing of the Go packages. Could there be a volume mount for the ~/.ssh/known_hosts so that new hosts can be added and compared in future fetches? I think it would be really great if the known_hosts could be shared by the pkgsite, or maybe the sumsite so that ssh sites can compare the keys they have for each other and put up flags in case of mismatches. The supertxt site shares its known_hosts of other sites via both [https](https://supertxt.net/.ssh/known_hosts) and through ssh:

``` .sh
ssh supertxt.net cat .ssh/known_hosts
```

**Comment by hyangah** [comment]
> In terms of security, SSH itself provides an encrypted channel to help prevent third party sniffing of data. The hostkey approach provides some protection against MITM based on a time of first use (tofu) approach. It's not perfect, but neither is the root CA approach of the web. Project Gemini uses a similar tofu with its non-web browsing technology. As an added measure of security all of the git commits are signed on the supertxt site. 

The module proxy is handling multiple millions of module versions and fetching in highly distributed system. Implementing volume mount in the current architecture designed for scale is, I am afraid, non trivial. We can carry ~/.ssh/known_hosts but how should it handle if the key rotates? This is fully automated and there is no human involved. Is the extra measure supertxt site implements (e.g. publishing ssh/known_hosts list) a common practice other ssh+git based source repositories also implement? Or are you proposing the proxy to special case supertxt.net domain when fetching data?

**Comment by supertxtnet** [comment]
The established approach for key rotation among SSH sites is to provide multiple host keys, and replace one on an interval. OpenSSH compatible clients since around 2015 will add + remove the keys transparently if one of the presented host keys is in known_hosts. If the host isn't known at all then the option I posted above will automatically add all of the keys to the known_hosts.

In the case where none of the keys for the host in the known_hosts match the presented host keys then there will be an error. I imagine that this error encountered in the context of the pkgsite/sumsite that it could be handled in the same way as it handles a website's that has an expired TLS certificate, the domain doesn't match the certificate, or the trust chain doesn't lead to a trusted root CA.

Btw, what's the crawl interval look like for the pkgsite/sumsite so that I can align the key rotation with that?

The sharing of known_hosts is something that we're trying with the supertxt site as a way to share public fingerprints. I'm not suggesting that supertxt be treated specially here; it's just an idea. If someone trusted supertxt then they might compare their known_hosts with the supertxt site to see if there's any discrepancy as another form of verification on tofu. Maybe someday there will be tooling around the comparing of known_hosts. A prestigious site like the pkgsite might be trusted by more users and crawls many sites regularly checking their state.

Thanks, I'll check out the module proxy documentation.

**Comment by hyangah** [comment]
> I imagine that this error encountered in the context of the pkgsite/sumsite that it could be handled in the same way as it handles a website's that has an expired TLS certificate, the domain doesn't match the certificate, or the trust chain doesn't lead to a trusted root CA.

Until the hosting site fixes the certificate issue, proxy and pkgsite won't be able to fetch data. Unlike the ssh known_host, there is a scalable way to recover without manual intervention on proxy side.

> Btw, what's the crawl interval look like for the pkgsite/sumsite so that I can align the key rotation with that?

It depends on how frequently users request modules from the sites and how many module versions or packages are hosted in the sites. Sites that host actively used modules will be contacted at least a couple of times every 30 minutes. Hosts with many popular module versions would be contacted more frequently. 

> The sharing of known_hosts is something that we're trying with the supertxt site as a way to share public fingerprints. 

It sounds like this is not yet an established convention proxy/pkgsite can rely on to automate known_host discovery and validation. 

Closing since we don't have a plan to rearchitect to support this yet and there are workarounds e.g., module server that speaks module proxy protocol.

**Comment by supertxtnet** [comment]
Alright, I understand that this isn't going to be supported. Can the documentation make this explicit since "go get" can't work with an ssh site because that site must be indexed by the sumsite or use GOPRIVATE, with the smell? This is where I first encountered this problem independent of pkgsite.

I find it unfortunate that ssh is second class here and things must use the github approach (or adapt to it) moving forward or remain obscure.

> Until the hosting site fixes the certificate issue, proxy and pkgsite won't be able to fetch data. Unlike the ssh known_host, there is a scalable way to recover without manual intervention on proxy side.

I'm not quite sure what you mean about manual intervention. Host key rotations are fully automated as mentioned above.

> It sounds like this is not yet an established convention proxy/pkgsite can rely on to automate known_host discovery and validation.

There is though. The established convention is to use multiple hostkeys at a time, and rotate one out. This has been supported for nearly 10 years in OpenSSH. The client will update the known_hosts automatically as long as one remains in common.

**Comment by supertxtnet** [comment]
Alright, I understand that this isn't going to be supported. Can the documentation make this explicit since "go get" can't work with an ssh site because that site must be indexed by the sumsite or use GOPRIVATE, with the smell? This is where I first encountered this problem independent of pkgsite.

I find it unfortunate that ssh is second class here and things must use the github approach (or adapt to it) moving forward or remain obscure.

> Until the hosting site fixes the certificate issue, proxy and pkgsite won't be able to fetch data. Unlike the ssh known_host, there is a scalable way to recover without manual intervention on proxy side.

I'm not quite sure what you mean about manual intervention. Host key rotations are fully automated as mentioned above.

> It sounds like this is not yet an established convention proxy/pkgsite can rely on to automate known_host discovery and validation.

There is though. The established convention is to use multiple hostkeys at a time, and rotate one out. This has been supported for nearly 10 years in OpenSSH. The client will update the known_hosts automatically as long as one remains in common.
