### ISSUE TITLE
x/pkgsite: package removal request for github.com/5GCoreNet/openapi

### ISSUE THREAD

**Issue by Joffref** [golang/go#59380]
### What is the path of the package that you would like to have removed?

github.com/5GCoreNet/openapi

### Are you the owner of this package?

Yes

### What is the reason that you could not retract this package instead?

I've recreated the repository since the first import in pkg.go.dev thus it is not able to sync and update versioning. That is why I'm requesting a removal.

**Comment by seankhliao** [comment]
removing will only hide the entire module, it won't do anything else, like let you reset versioning.

**Comment by Joffref** [comment]
@seankhliao Do you have any idea on how to sync pkg.go.dev with the new github repository ? Any workaround ?

**Comment by Joffref** [comment]
or maybe this an issue with the proxy. TBH I'm quite confused with this issue.
