### ISSUE TITLE
x/pkgsite: bad rendering for generics code

### ISSUE THREAD

**Issue by egonelbre** [golang/go#59398]
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/zyedidia/generic/list#section-readme

### What is your user agent?

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

### Screenshot

![example](https://user-images.githubusercontent.com/192964/229510646-84df50f5-18e6-49f8-a5e0-77d07743e6ca.png)

### What did you do?

Just reading the documentation of the package.

### What did you expect to see?

Properly formatted link.

### What did you see instead?

Weird link in the index.

**Comment by findleyr** [comment]
That index is from the README itself, not generated by pkgsite.

Github doesn't render it properly either:
https://github.com/zyedidia/generic/blob/master/list/README.md

I think this is simply incorrectly formatted markdown in the module itself. Closing as unactionable on our end.
