### ISSUE TITLE
net: "semaphore timeout period has expired" on Windows

### ISSUE THREAD

**Issue by taruti** [golang/go#5940]
<pre>Long-standing http.Client connections appear to suffer from

WSARecv: tcp &lt;some-ipaddress-and-port&gt;: The semaphore timeout period has expired

with go1.1.1 on windows/386.

This is quite hard to reproduce, but is probably the same problem as <a href="https://golang.org/issue/2057">issue #2057</a> was.</pre>

**Comment by mikioh** [comment]
Closing. I think runtime-integrated network poller with IOCP fixed this issue.
