### ISSUE TITLE
Gofmt doesn't format new operator ":=" correctly.  affected/package: gofmt

### ISSUE THREAD

**Issue by jcbritobr** [golang/go#59405]
<pre>
go1.20.2 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jcbritobr/.cache/go-build"
GOENV="/home/jcbritobr/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/jcbritobr/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jcbritobr/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/jcbritobr/Bin/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/jcbritobr/Bin/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/jcbritobr/Workspace/go/lotest/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1467521579=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

Using go format formats assignments symbols in wrong way

![image](https://user-images.githubusercontent.com/6579862/229614265-a4d99a6b-68da-44ff-a318-a3dfc60803a7.png)

### What did you expect to see?

![image](https://user-images.githubusercontent.com/6579862/229614637-a45e2e4a-7684-4ce5-a001-15e35a4d03d8.png)

### What did you see instead?

![image](https://user-images.githubusercontent.com/6579862/229614758-310c55a9-ed99-4c50-be74-f2c8fe7a4111.png)

**Comment by seankhliao** [comment]
This is working as intended.
Alignment only happens for groups, eg:

```go
	var (
		a  = "abc"
		bb = "def"
	)

```


see also https://github.com/golang/go/issues/7819#issuecomment-66093841
