### ISSUE TITLE
runtime: clear() on map doesn't correctly clear existing iterators

### ISSUE THREAD

**Issue by randall77** [golang/go#59411]
This program shouldn't print anything:
```
package main

import "math"

func main() {
	for i := 0; i < 100; i++ {
		f()
	}
}
func f() {
	// Allocate map.
	m := map[float64]int{}
	// Fill to just before a growth trigger.
	const N = 13 << 4 // 6.5 * 2 * 2^k
	for i := 0; i < N; i++ {
		m[math.NaN()] = i
	}
	// Trigger growth.
	m[math.NaN()] = N

	// Iterate through map.
	i := 0
	for _, v := range m {
		if i == 6 {
			// Partway through iteration, clear the map.
			clear(m)
		} else if i > 6 {
			// If we advance to the next iteration, that's a bug.
			println("BAD", i, v)
		}
		i++
	}
}
```

It does (at tip).

For maps whose keys have NaNs in them, iterators that are in progress can't tell that some entries have been deleted by the `clear` builtin. This is because where those NaNs should move to in the larger bucket array isn't computable.  Pre `clear` bultin, this didn't matter because the NaN entries couldn't be deleted.

@cuonglm 

Update #55002, #56351

**Comment by cuonglm** [comment]
@randall77 Could we mark all bucket slot as `emptyOne`?
