### ISSUE TITLE
LockOSThread + SchedSetaffinity unexpected behaviour

### ISSUE THREAD

**Issue by kaber2** [golang/go#59410]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/user/sdk/go1.20.2"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/user/sdk/go1.20.2/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.2"
GCCGO="gccgo"
GOAMD64="v3"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2690853676=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I'm using isolated CPU cores and runtime.LockOSThread() + unix.SchedSetaffinity() to move specific tasks to these cores. The code first locks to the current OS thread, then changes its CPU affinity.

This works well, but I randomly see the main thread changing its CPU affinity immediately after spawning the locked goroutines. The locked goroutines arent't doing anything at this point, just idling, and they have not spawned any other goroutines. They just go into a select loop and sleep there. GOMAXPROCS is set to a value to accomodate both locked and regular threads.

### What did you expect to see?

The combination LockOSThread + SchedSetaffinity only affecting the affinity of the specific goroutines it is invoked in, as long as they don't spawn any other goroutines.

### What did you see instead?

Main thread changes affinity.

As an additional note, when adding a time.Sleep(10*time.Second) after spawning the locked goroutines, the problem disappears. The program is long running (days, weeks) and if the problem doesn't show up on startup, it never does. It "feels" like LockOSThread is not taking effect immediately and the SchedSetAffinity is executed in the wrong thread.

**Comment by kaber2** [comment]
Thanks for your response.

Actually I believe I had incorrect assumptions. Basically I'm seeing the changed affinity using taskset on the main program PID. But I suppose there's actually nothing wrong with scheduling my new locked goroutines to this PID as its probably just a thread like any other, except that its also the first one that was created and from the OS point of view is the "main thread".

Is my (revised) assumption correct, that the main thread is just a thread like any other? If so, there's no bug and I appologize for wasting your time.

**Comment by ianlancetaylor** [comment]
Yes, the main thread is a thread like any other.
