### ISSUE TITLE
x/tools/go/ssa: ssa.EnclosingFunction panic

### ISSUE THREAD

**Issue by nabice** [golang/go#59428]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/nabice/.cache/go-build"
GOENV="/home/nabice/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/nabice/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/nabice/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/nabice/source/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/nabice/source/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2666103133=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

Source Code: 
parser.go:            https://go.dev/play/p/P-kZ6j7Eq7R
async_pool.go:    https://go.dev/play/p/hVneLr-mMLI

Build parser.go and run, program will read async_pool.go, and crashes occasionally.
I think the problem is here:
https://github.com/golang/tools/blob/d5076cc64d484da83963b1ae098aef830c21c448/go/ssa/source.go#L112-L128
Here, the iteration order of the map may be inconsistent. If the outer struct(`AsyncPoolProcessor`) is iterated first, a new *types.Func will be generated, and its address is different.

### What did you expect to see?

No panic.

### What did you see instead?

Panic
```
command-line-arguments.NewAsyncPool
panic: interface conversion: ssa.Member is nil, not *ssa.Function

goroutine 1 [running]:
golang.org/x/tools/go/ssa.findNamedFunc(0xc00011a280, 0x8f)
        /home/nabice/go/pkg/mod/golang.org/x/tools@v0.7.0/go/ssa/source.go:124 +0x1fe
golang.org/x/tools/go/ssa.findEnclosingPackageLevelFunction(0x5f5800?, {0xc0000693a0?, 0xc0000fbb40?, 0xc0000fbb48?})
        /home/nabice/go/pkg/mod/golang.org/x/tools@v0.7.0/go/ssa/source.go:101 +0xb8
golang.org/x/tools/go/ssa.EnclosingFunction(0x6230e0?, {0xc0000693a0?, 0x2, 0x6b18b8?})
        /home/nabice/go/pkg/mod/golang.org/x/tools@v0.7.0/go/ssa/source.go:34 +0x2c
main.main.func2({0x6b1b88?, 0xc000076990})
```

**Comment by mknyszek** [comment]
CC @golang/tools-team

**Comment by nabice** [comment]
Workaround:
                if obj.Pos() == pos {
                    for _, o := range pkg.objects {
                        if f, ok := o.(*Function); ok {
                            if f.Pos() == pos && f.Name() == obj.Name() {
                                return f
                            }
                        }
                    }
                }
