### ISSUE TITLE
run go generate Error: no compiler specified

### ISSUE THREAD

**Issue by MrSsunlight** [golang/go#59420]
```bash
# go version
go version go1.19.7 darwin/amd64
```

clone  ebpf v0.10.0
```bash
git clone --depth 1 git@github.com:cilium/ebpf.git
cd ebpf/examples/kprobe
rm -rf  *.o
rm -rf bpf_*

go generate .
Error: no compiler specified
exit status 1
main.go:16: running "go": exit status 1
```

How can I troubleshoot

**Comment by seankhliao** [comment]
this is not an error from Go 

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
