### ISSUE TITLE
cmd/compile: miscompilation in star-tex.org/x/cmd/star-tex

### ISSUE THREAD

**Issue by sbinet** [golang/go#59432]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.21-f62c9701b4 Tue Apr 4 07:17:19 2023 +0000 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/binet/.cache/go-build"
GOENV="/home/binet/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/binet/dev/go/gocode/pkg/mod"
GONOPROXY="gitlab.cern.ch/tile-in-one/tio-go,gitlab.cern.ch/tile-in-one/tio-0021/*"
GONOSUMDB="gitlab.cern.ch/tile-in-one/tio-go,gitlab.cern.ch/tile-in-one/tio-0021/*"
GOOS="linux"
GOPATH="/home/binet/dev/go/gocode"
GOPRIVATE="gitlab.cern.ch/tile-in-one/tio-go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/binet/sdk/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/binet/sdk/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel go1.21-f62c9701b4 Tue Apr 4 07:17:19 2023 +0000"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2001148705=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

since 1c783f7c68aae4effd6dcc9692a6574418556ebb, [star-tex test](https://git.sr.ht/~sbinet/star-tex/tree/v0.4.0/item/cmd/star-tex/main_test.go) is failing:
```
$> cd star-tex.org/x/tex/cmd/star-tex
$> go test
--- FAIL: TestProcess (0.00s)
    --- FAIL: TestProcess/hello.tex (0.00s)
        main_test.go:43: could not process TeX document: xtex.pasError(-2)
FAIL
exit status 1
```

ie: it was working with Go-1.18.x, but not anymore starting with Go-1.19.x.

### What did you expect to see?

a sucessfully working test.

### What did you see instead?

a failing test.

bisecting Go, I've found out the first revision of `go test` that triggered the failing test.

star-tex is relying on [web2go](https://gitlab.com/cznic/web2go) to automatically transpile Donald Knuth's WEB `tex.web` file to Go.
the result is under `x/tex/internal/xtex`.
it's machine generated so, not super easy on the eye:
- https://git.sr.ht/~sbinet/star-tex/tree/v0.4.0/item/internal/xtex/xtex.go

the failure is actually coming from:
- https://git.sr.ht/~sbinet/star-tex/tree/v0.4.0/item/internal/xtex/xtex.go#L1674
which, of course, shouldn't happen by just recompiling the same piece of code but with different `go build` versions.

looking at 1c783f7c68aae4effd6dcc9692a6574418556ebb CL, a possible hint at the root cause generating this issue *might* be in how some of the C-trickeries performed in `tex.web` are translated into Go, meaning `"unsafe"`:
- https://git.sr.ht/~sbinet/star-tex/tree/v0.4.0/item/internal/xtex/xtex.go#L136
- https://git.sr.ht/~sbinet/star-tex/tree/v0.4.0/item/internal/xtex/xtex.go#L145
- https://git.sr.ht/~sbinet/star-tex/tree/v0.4.0/item/internal/xtex/xtex.go#L149
- https://git.sr.ht/~sbinet/star-tex/tree/v0.4.0/item/internal/xtex/xtex.go#L163

(perhaps the interplay of `unsafe.Pointer` and `uintptr` at `L145` and `L149` ?)

**Comment by mknyszek** [comment]
CC @golang/compiler

**Comment by cherrymui** [comment]
Does the test pass with an older version of Go (which is known to work) with `go test -race` or `go test -gcflags=all=-d=checkptr=1` ? So we can see if the unsafe conversions are okay? Thanks.

**Comment by sbinet** [comment]
yes, with 581603cb7d (Go1.18.10) and 7ffc1e47b4 (one revision before 1c783f7c68aae4effd6dcc9692a6574418556ebb), I get:

```
$> cd x/tex/cmd/star-tex
$> go version; go test -gcflags=all=-d=checkptr=1; go test -race
go version devel go1.20-7ffc1e47b4 Mon Oct 17 14:53:58 2022 +0000 linux/amd64
PASS
ok  	star-tex.org/x/tex/cmd/star-tex	0.010s
PASS
ok  	star-tex.org/x/tex/cmd/star-tex	0.080s
```

**Comment by sbinet** [comment]
interestingly, with today's `tip` (ecc5ba4611), I get:

```
$> go version; go test -gcflags=all=-d=checkptr=1; go test -race
go version devel go1.21-ecc5ba4611 Tue Apr 4 17:04:36 2023 +0000 linux/amd64
--- FAIL: TestProcess (0.00s)
    --- FAIL: TestProcess/hello.tex (0.00s)
        main_test.go:43: could not process TeX document: xtex.pasError(-2)
FAIL
exit status 1
FAIL	star-tex.org/x/tex/cmd/star-tex	0.003s
PASS
ok  	star-tex.org/x/tex/cmd/star-tex	0.080s
```

(_ie:_ `go test -race` succeeds)

**Comment by dr2chase** [comment]
Can confirm that undoing that single CL "fixes" the bug.  As they say, hmmmmmmm.

**Comment by dr2chase** [comment]
I wasn't able to write a test case, so shall include the debugging debris here:
This line (1666 in github.com/go-latex/star-tex/internal/xtex/xtex.go)
```
a = (10 * a) + int32(tex.xord[n]) - 48
```
compiles to (just before late lower)
```
b109: ← b107
  v1495 (+1667) = CMPBconst <flags> [9] v2107
  v1895 (+1666) = LEAL4 <int32> v2103 v2103
  v878 (+1666) = LEAL2 <int32> v675 v1895
  v879 (1666) = LEAL2 <int32> [-48] v675 v1895 (a[int32])
EQ v1495 → b137 b144 (1667)
```
late lower transforms this to
```
b109: ← b107-
  v1495 (+1667) = CMPBconst <flags> [9] v2107
  v1895 (+1666) = LEAL4 <int32> v2103 v2103
  v1953 (1666) = LEAL2 <byte> v675 v1895
  v878 (+1666) = LEAL2 <int32> v675 v1895
  v879 (1666) = ADDLconst <int32> [-48] v1953 (a[int32])
EQ v1495 → b137 b144 (1667)
```
After additional optimization, v879 is moved to another block, and its input (v1953) is spilled *as a byte*:
```
b109: ← b107-
  v1895 (+1666) = LEAL4 <int32> v2103 v2103 : SI
  v878 (+1666) = LEAL2 <int32> v675 v1895 : R8
  v1953 (1666) = LEAL2 <byte> v675 v1895 : SI
  v1495 (+1667) = CMPBconst <flags> [9] v2107
EQ v1495 → b137 b144 (unlikely) (1667)
b144: ← b109-
  v1810 (1666) = StoreReg <byte> v1953 : .autotmp_185[byte]
...
b105: ← b230-
...
  v1684 (1666) = LoadReg <byte> v1810 : SI
  v879 (1666) = ADDLconst <int32> [-48] v1684 : SI (a[int32])

```
and the root cause of this is the wrong type used to create the optimized LEA instructions.

**Comment by dr2chase** [comment]
@gopherbot please open the backport tracking issues. This is a severe compiler bug.

**Comment by dr2chase** [comment]
Fix CL had a problem, going to just remove the offending rewrite rules instead.
