### ISSUE TITLE
go/scanner: scanNumber() method produces inconsistent error message

### ISSUE THREAD

**Issue by hafus** [golang/go#59441]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20 windows/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes, it's

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=auto
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOVCS=
set GOVERSION=go1.20
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=

</pre></details>

### What did you do?
I ran the code snippets listed below to check the error message printed by the number parser. The test targets octal numbers, but it is valid for other number systems as well.  As you can see the error message is varies depending on the invalid value being in the decimal range or not.

1- In decimal range.
```go
func main() {
	fmt.Println(0o19)
}
```

2- In the hex range.
```go
func main() {
	fmt.Println(0o1A)
}
```

### What did you expect to see?
1- Output:
```go
./prog.go:8:17: invalid digit '9' in octal literal
```

2- Output:
```go
./prog.go:8:17: invalid digit 'A' in octal literal
```

### What did you see instead?
1- Output:
```go
./prog.go:8:17: invalid digit '9' in octal literal
````

2- Output:
```go
./prog.go:8:17: syntax error: unexpected A in argument list; possibly missing comma or )
```

**Comment by hafus** [comment]
I think the root cause is on the func below. It should be extended to handle invalid values for other number systems.

```go
func (s *Scanner) digits(base int, invalid *int) (digsep int) {
	if base <= 10 {
		max := rune('0' + base)
		for isDecimal(s.ch) || s.ch == '_' {
			ds := 1
			if s.ch == '_' {
				ds = 2
			} else if s.ch >= max && *invalid < 0 {
				*invalid = s.offset // record invalid rune offset
			}
			digsep |= ds
			s.next()
		}
	} else {
		for isHex(s.ch) || s.ch == '_' {
			ds := 1
			if s.ch == '_' {
				ds = 2
			}
			digsep |= ds
			s.next()
		}
	}
	return
}
```

**Comment by mknyszek** [comment]
CC @griesemer via https://dev.golang.org/owners
