### ISSUE TITLE
net/http/pprof: missing documentation of the "seconds" parameter

### ISSUE THREAD

**Issue by aktau** [golang/go#59452]
cc @aalexand

```
$ go version
Go 1.21-dev
```

### What did you do?

Navigate to https://pkg.go.dev/net/http/pprof and read.

### What did you expect to see?

I expected to see a mention of the "seconds" parameter for all profiles types that implement delta profiling:

https://github.com/golang/go/blob/508f445a28b08ed8c881572652c47139e669c19d/src/net/http/pprof/pprof.go#L341-L348

### What did you see instead?

No mention. This feature was first worked on in https://github.com/golang/go/issues/23401 AFAICT. It's been in Go for a while.

**Comment by mknyszek** [comment]
CC @golang/runtime 

The current owners are Cherry and Russ, but should probably just be a compiler/runtime team-owned package, since it has much more to do with `runtime/pprof` than `net/http`.

**Comment by mknyszek** [comment]
Actually, the "seconds" parameter is mentioned in a few places, e.g. https://pkg.go.dev/net/http/pprof#Trace. It's also mentioned in examples. What else should change? Is it just that it's missing on some of them? `Profile` also mentions it.

Maybe what you're suggesting is better clarity? Like a full list of endpoints (not examples) and their parameters?

**Comment by aalexand** [comment]
It would be good to have a way for a reader to know what profiles accept what parameters. For example, the "seconds" parameter was not respected by the mutex handler in the past, and then it was added. It would be good to have this reflected in the docs.
