### ISSUE TITLE
runtime/cgo: The x_cgo_sigaction function uses the unsafe function memset.

### ISSUE THREAD

**Issue by chenweihao9** [golang/go#59498]
### What version of Go are you using (`go version`)?

<pre>
$ go version
all
</pre>

### Does this issue reproduce at the latest version of golang.org/x/vuln?
yes

### What operating system and processor architecture are you using (`go env`)?
linux

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

View Code

### What did you expect to see?

Whether the memset function can be modified to a secure function

**Comment by bcmills** [comment]
What is unsafe about `memset`?

**Comment by ianlancetaylor** [comment]
These uses of `memset` are safe.
