### ISSUE TITLE
proposal log/slog: Structured values cause allocations

### ISSUE THREAD

**Issue by CannibalVox** [golang/go#59509]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.2 windows/amd64
</pre>

I also tested this on the "go dev branch" setting in the playground: https://go.dev/play/p/gXHvWmaCLB5?v=gotip.go?download=true

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Stephen\AppData\Local\go-build
set GOENV=C:\Users\Stephen\AppData\Roaming\go\env  
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\msys64\mingw64\pkg\mod
set GONOPROXY=github.com/vkngwrapper/arsenal       
set GONOSUMDB=github.com/vkngwrapper/arsenal       
set GOOS=windows
set GOPATH=C:/msys64/mingw64                       
set GOPRIVATE=github.com/vkngwrapper/arsenal       
set GOPROXY=https://proxy.golang.org,direct        
set GOROOT=C:\Users\Stephen\go\go1.20.2            
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Users\Stephen\go\go1.20.2\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.20.2
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=C:\Users\Stephen\projects\vkngwrapper\go.work
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\msys64\tmp\go-build2749040163=/tmp/go-build -gno-record-gcc-switches   
</pre></details>

### What did you do?

Ran simple code to output a log message with a value in slog: https://go.dev/play/p/gXHvWmaCLB5?v=gotip.go?download=true

### What did you expect to see?
Zero allocations, since that is how other structured logging solutions (i.e. zap) works and avoiding the allocations of fmt.Sprintf is one of the benefits of structured logging. Additionally, merely calling slog.Int() doesn't cause an allocation. 

### What did you see instead?
The code performs one allocation per Attr passed into slog.Logger.Debug. Here's an example with more allocations: https://go.dev/play/p/gXHvWmaCLB5?v=gotip.go?download=true

**Comment by fzipp** [comment]
[LogAttrs](https://pkg.go.dev/log/slog@master#Logger.LogAttrs) is what you're looking for: https://go.dev/play/p/6aAtjXqrntn?v=gotip

From the [design document](https://go.googlesource.com/proposal/+/master/design/56345-structured-logging.md):
> For the most efficient log output, use Logger.LogAttrs. It is similar to Logger.Log but accepts only Attrs, not alternating keys and values; this allows it, too, to avoid allocation.

**Comment by CannibalVox** [comment]
Ah! Sorry about that, and thank you.
