### ISSUE TITLE
x/tools/godoc: static files links old tour mod/url

### ISSUE THREAD

**Issue by crisman** [golang/go#59505]
### What did you do?

View the main page of a godoc server under Sub-repositories

http://127.0.0.1:6060/pkg/#subrepo

### What did you expect to see?

Links to the current tour (under x/website) and and tour URL go.dev/tour

### What did you see instead?

Old (x/tour) mod link and tour.golang.org.

**Comment by dr2chase** [comment]
@golang/tools-team

**Comment by seankhliao** [comment]
The godoc command was deprecated
