### ISSUE TITLE
Cannot use make.bash to build go pkg

### ISSUE THREAD

**Issue by waruqi** [golang/go#59515]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.20.3
</pre>

### Does this issue reproduce with the latest release?

I tried to cross-compile pkg sdk using a recent version of go, but it failed. The previous version is working, but I'm not sure from which version it breaks.

```
$ cd ~/Downloads/go/src
$ GOOS=darwin GOARCH=amd64 GOROOT_BOOTSTRAP=~/Downloads/go/ ./make.bash --no-clean
Building Go cmd/dist using /Users/ruki/Downloads/go/. (go1.20.3 darwin/amd64)
go: no such tool "compile"
go: no such tool "compile"
go: no such tool "compile"
go: no such tool "compile"
go: no such tool "compile"
go: no such tool "compile"
```

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/ruki/Library/Caches/go-build"
GOENV="/Users/ruki/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/ruki/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/ruki/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/ruki/Downloads/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/ruki/Downloads/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.20.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/ruki/Downloads/go/src/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug
-prefix-map=/var/folders/32/w9cz0y_14hs19lkbs6v6_fm80000gn/T/go-build3475982979=/tmp/go-build -gno-record-gcc-swi
tches -fno-common"
</pre></details>

### What did you expect to see?

it works

**Comment by seankhliao** [comment]
you need to use an existing installation (bootstrap) to build the entire tree, you're trying to build the tree from itself.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
