### ISSUE TITLE
x/tools/gopls:  generic base type like pointer or any struct

### ISSUE THREAD

**Issue by fengyeall111** [golang/go#59518]
### gopls version
1.20.3
### go env
win11
### What did you do?
In other language like c#, the type constraints can be "class",but in go there is no "struct"
I have some situation need generic link this:
type gen[T anystruct]strcut{}
type gen[T *anystruct]{}
sync.pool[T any] 

### What did you expect to see?
[T anystruct] but not [T interface] 
sync.pool[T any] but not sync.pool which return interface

**Comment by seankhliao** [comment]
no, this isn't something we will do

**Comment by fengyeall111** [comment]
> no, this isn't something we will do

why？Is there some harmful?
