### ISSUE TITLE
net/http: "Test appears to have leaked a Transport" on darwin-amd64-longtest

### ISSUE THREAD

**Issue by prattmic** [golang/go#59526]
The new `darwin-amd64-longtest` builders (#35678) are failing continuously with "Test appears to have leaked a Transport" errors, either in `TestTransportPrefersResponseOverWriteError/h1` (5/6 failures) or `TestMaxBytesHandler/max_size_100_request_size_1000000/h1` (1/6 failures):

[2023-04-10T18:52:58-65ea4c5/darwin-amd64-longtest](https://build.golang.org/log/ac1e6d40e15d127bb5245a3ab91ee8d35bf90048)
[2023-04-10T17:30:27-5e93a2c/darwin-amd64-longtest](https://build.golang.org/log/119518ca382a37685fa27cb4822c9ac1209b2168)
[2023-04-10T17:13:41-63a08e6/darwin-amd64-longtest](https://build.golang.org/log/669e914bb8b72ca134536e39b39a8e31f8baec46)
[2023-04-10T17:07:24-a3f3868/darwin-amd64-longtest](https://build.golang.org/log/f82068fd5dd298926d1ffcdaad6275f997085c4e)
[2023-04-10T17:06:55-60140a8/darwin-amd64-longtest](https://build.golang.org/log/103a2b0e0ea708c66913925265b2558a8a539222)
[2023-04-10T15:57:38-9efca84/darwin-amd64-longtest](https://build.golang.org/log/fb5d86d3ec50a236359b79149b9b101954cc5b1e)

The only other failures I see like this in fetchlogs are from 2020, so too old to be obviously related.

cc @neild @bcmills

**Comment by prattmic** [comment]
For reference, the bug for the 2020 failures was #42943

**Comment by prattmic** [comment]
This bug easily reproduces on a `darwin-amd64-13` gomote, simply by running `go test net/http`. It also reproduces with filtering (`-run TestTransportPrefersResponseOverWriteError/h1`).

The full set of failures I get in net/http:

```
--- FAIL: TestTransportPrefersResponseOverWriteError (6.94s)
    --- FAIL: TestTransportPrefersResponseOverWriteError/h1 (3.85s)
    --- FAIL: TestTransportPrefersResponseOverWriteError/h2 (3.09s)
--- FAIL: TestTransportReuseConnEmptyResponseBody (6.04s)
    --- FAIL: TestTransportReuseConnEmptyResponseBody/h1 (3.04s)
    --- FAIL: TestTransportReuseConnEmptyResponseBody/h2 (3.00s)
```

(`TestMaxBytesHandler` suspiciously missing)

**Comment by bcmills** [comment]
`TestTransportPrefersResponseOverWriteError` does seem to be leaky: it fires off a bunch of requests for which the server writes an error response without reading the request body to completion.

For those requests, `c.Do(req)` will return as soon as the server response arrives, even though the request processing hasn't finished yet.

Perhaps the solution is to wrap the `strings.Reader` with a `Close` method that calls `wg.Done()` on a `sync.WaitGroup`? Then the test could wait for all of the request bodies to be closed before returning. (That's probably close enough timing-wise to not trigger the leak check.)

**Comment by bcmills** [comment]
I'm not sure what's going on with `TestTransportReuseConnEmptyResponseBody`, since that request doesn't seem to involve writing a request body. 🤔

**Comment by bcmills** [comment]
`TestMaxBytesHandler` has the same issue as `TestTransportPrefersResponseOverWriteError`: it creates a request that will be rejected by the server before the body has been read, which on the client side leaks the `Write` goroutine.

It can be fixed in the same way: by adding a `Close` method to the body that synchronizes with the return from the test function.

**Comment by carlmjohnson** [comment]
I think I wrote TestMaxBytesHandler. As I recall I just copypasta’d another test. Sorry if it’s buggy! 😓

**Comment by bcmills** [comment]
FWIW, `watchflakes` found `TestMaxBytesHandler` in #57612.

**Comment by bcmills** [comment]
I think failures reported in `TestTransportReuseConnEmptyResponseBody` are a red herring. As far as I can tell, the goroutines reported as “leaked” there are the ones from `TestTransportPrefersResponseOverWriteError`.

Probably the leak check should just be disabled after the first report.

**Comment by bcmills** [comment]
Fixed in [CL 483895](https://go.dev/cl/483895).
