### ISSUE TITLE
x/website: go 1.20 doc html format problem

### ISSUE THREAD

**Issue by yuanyao07** [golang/go#59534]
### What is the URL of the page with the issue?
 https://go.dev/doc/go1.20
 
 
### What is your user agent?
 

 [Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36](https://explore.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)
 
 
### Screenshot
 

 
<img width="1217" alt="Screenshot 2023-04-11 at 1 55 38 AM" src="https://user-images.githubusercontent.com/2541681/231069042-e16828db-f455-4175-a65f-a09990b67c0d.png">

 
 
### What did you do?
 

Visit https://go.dev/doc/go1.20 and scroll down to "mime/multipart". All fonts after the paragraph are formatted as code as the below mentioned html tag wasn't closed properly.
 
 
### What did you expect to see?
 
```<code>Reader.ReadForm</code>```
 
### What did you see instead?

```<code>Reader.ReadForm</code<>```

**Comment by dr2chase** [comment]
@golang/tools-team
