### ISSUE TITLE
x/pkgsite: 

### ISSUE THREAD

**Issue by Aman-1407** [golang/go#59535]
### What is the URL of the page with the issue?
package insatallation error.

### What is your user agent?

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

### Screenshot

go install -v github.com/go-delve/delve/cmd/dlv@latest
go\pkg\mod\github.com\go-delve\delve@v1.20.2\service\debugger\debugger.go:32:2: found packages native (followexec_other.go) and your_windows_architecture_is_not_supported_by_delve (support_sentinel_windows.go) in C:\Users\xxxx\go\pkg\mod\github.com\go-delve\delve@v1.20.2\pkg\proc\native

### What did you do?
run this command
go install -v github.com/go-delve/delve/cmd/dlv@latest
but not able to install this delve any version. 

### What did you expect to see?

installation succesfull

### What did you see instead?

go\pkg\mod\github.com\go-delve\delve@v1.20.2\service\debugger\debugger.go:32:2: found packages native (followexec_other.go) and your_windows_architecture_is_not_supported_by_delve (support_sentinel_windows.go) in C:\Users\xxxx\go\pkg\mod\github.com\go-delve\delve@v1.20.2\pkg\proc\native

**Comment by seankhliao** [comment]
this is an issue for the delve project, not go
