### ISSUE TITLE
cmd/compile: 4% kubelet compile time regression from CL 482356 "cmd/compile: allow more inlining of functions that construct closures"

### ISSUE THREAD

**Issue by prattmic** [golang/go#59547]
https://go.dev/cl/482356 seems to have caused a regression of ~4% for the kubernetes kubelet:

https://perf.golang.org/dashboard/?benchmark=GoBuildKubelet&unit=sec/op#commit39986d28e435d23e1d1dc41b8f16c0cf30181208

The immediate parent of this commit was also tested (f1caf1a), so it does seem to be caused by https://go.dev/cl/482356.

Strangely, our other two build benchmarks (Istio and pkgsite) regressed <1%:

https://perf.golang.org/dashboard/?benchmark=GoBuildIstioctl&unit=sec/op#commit39986d28e435d23e1d1dc41b8f16c0cf30181208
https://perf.golang.org/dashboard/?benchmark=GoBuildFrontend&unit=sec/op#commit39986d28e435d23e1d1dc41b8f16c0cf30181208

cc @thanm to see if this is expected
cc @mdempsky

**Comment by thanm** [comment]
I've reworked the code that marks unreferenced hidden closures as dead (to fix another bug). The new patch marks a lot more stuff dead, so I am hoping that it will help speed up the compiler a bit as well.  Will send CL shortly.

**Comment by thanm** [comment]
Kubelet build is now back on track with https://go.dev/cl/492016. Marking this closed.
