### ISSUE TITLE
Wrong return value when implicit return variable gets assigned inside defer block

### ISSUE THREAD

**Issue by krishna-birla** [golang/go#59543]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.3 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/krishna.birla/Library/Caches/go-build"
GOENV="/Users/krishna.birla/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/krishna.birla/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/krishna.birla/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/krishna.birla/go/go1.20.3"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/krishna.birla/go/go1.20.3/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/krishna.birla/GolandProjects/testProjGo/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3z/yk_jktzn7kn2f73cgf3rq97w0000gq/T/go-build1179941713=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I ran the following code snippet:
```go
package main

import (
	"fmt"
)

func myFunc1() (err error) {
	err = fmt.Errorf("func error")
	newErr := fmt.Errorf("new error")
	defer func() {
		// nothing here
	}()
	return newErr
}

func myFunc2() (err error) {
	err = fmt.Errorf("func error")
	newErr := fmt.Errorf("new error")
	defer func() {
		err = fmt.Errorf("defer error")
	}()
	return newErr
}

func main() {
	err1 := myFunc1()
	fmt.Printf("Case where implicit return variable is untouched in defer: %s\n", err1)

	err2 := myFunc2()
	fmt.Printf("Case where implicit return variable is overwritten in defer: %s\n", err2)
}

```
Link to playground: https://go.dev/play/p/-dSxEenEDA1

### What did you expect to see?

I expected the following output:
```
Case where implicit return variable is untouched in defer: new error
Case where implicit return variable is overwritten in defer: new error
```

Even though a different new error (`newErr`) gets returned in the function, the caller receives the implicit error (`err`) which was modified inside the `defer`. When the implicit error (`err`) is NOT modified inside the `defer`, then the caller receives the different new error (`newErr`) as expected.

### What did you see instead?

Instead, I saw the following output:
```
Case where implicit return variable is untouched in defer: new error
Case where implicit return variable is overwritten in defer: defer error
```

The caller should receive the different new error (`newErr`) in both cases, irrespective of whether the implicit error (`err`) gets modified inside the `defer` or not.

**Comment by thediveo** [comment]
Your expectation about how return values and defer interact doesn't seem to match the specification. A `return newErr` isn't bypassing the explicitly defined `err` return value; instead, it assigns the value of `newErr` to `err` and returns, triggering the defer handler(s). You proposed change would break a lot of existing code (not least several instances of my own code), because it would completely alter the behavior of setting or changing named function return values from defer handlers.

**Comment by krishna-birla** [comment]
@thediveo I agree, this changes the defer handler behaviour in other scenarios.

@thediveo Is this: "The returned new error is assigned to the named variable" documented anywhere? Can you point me to some documentation.

**Comment by krishna-birla** [comment]
@thediveo Thanks for the clarification. Please point me to the documented behaviour of "local variable getting assigned to named variable". Closing this for now.

**Comment by thediveo** [comment]
StackOverflow's your parent: [answer to How does defer and named return value work](https://stackoverflow.com/a/37252098), with links to the specification on return statements and defer statements.

> A "return" statement in a function F terminates the execution of F, and optionally provides one or more result values. Any functions [deferred](https://go.dev/ref/spec#Defer_statements) by F are executed before F returns to its caller.

> For instance, if the deferred function is a [function literal](https://go.dev/ref/spec#Function_literals) and the surrounding function has [named result parameters](https://go.dev/ref/spec#Function_types) that are in scope within the literal, the deferred function may access and modify the result parameters before they are returned. If the deferred function has any return values, they are discarded when the function completes. (See also the section on [handling panics](https://go.dev/ref/spec#Handling_panics).)

**Comment by krishna-birla** [comment]
Thanks!

**Comment by krishna-birla** [comment]
For anyone who comes across this later, to make it absolutely clear:

```go
package main

import (
	"fmt"
)

func myFunc1() (err error) {
	err = fmt.Errorf("func error")
	newErr := fmt.Errorf("new error")
	defer func() {
		fmt.Println(err)
		// nothing here
	}()
	return newErr
}

func myFunc2() (err error) {
	err = fmt.Errorf("func error")
	newErr := fmt.Errorf("new error")
	defer func() {
		fmt.Println(err)
		err = fmt.Errorf("defer error")
	}()
	return newErr
}

func main() {
	err1 := myFunc1()
	fmt.Printf("Case where implicit return variable is untouched in defer: %s\n", err1)

	err2 := myFunc2()
	fmt.Printf("Case where implicit return variable is overwritten in defer: %s\n", err2)
}

```

has the output:

```
new error
Case where implicit return variable is untouched in defer: new error
new error
Case where implicit return variable is overwritten in defer: defer error
```

The `newErr` gets assigned to `err`, and then the `defer` modifies and returns it. In both cases, the object `err` is the one to be returned.

**Comment by thediveo** [comment]
Personally, I'm taking likewise questions first to the [go-nuts](https://groups.google.com/g/golang-nuts) google group, with usually helpful results.
