### ISSUE TITLE
cmd/cover: Some code are missed by Go coverage profile

### ISSUE THREAD

**Issue by rumtid** [golang/go#59563]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes. Also, go1.19.8 works fine.

### What operating system and processor architecture are you using (`go env`)?

darwin, amd64

### What did you do?

Run: 

```
$ git clone https://github.com/rumtid/parser.git
$ cd parser

$ /usr/local/go/bin/go test -timeout 30s -coverprofile=/var/folders/ry/vp2b73b17vq3_w50fsqt1xp80000gn/T/vscode-goaU9l71/go-code-cover -run ^TestMe$ github.com/rumtid/parser -coverpkg=all
```

### What did you expect to see?

The coverage profile marks some covered lines in `yyParse()`.

### What did you see instead?

Despite `yyParse()` is invoked, it is not covered according to the profile.

**Comment by thanm** [comment]
Thanks for the report. I will take a look.

**Comment by thanm** [comment]
OK, I think I see what's going on here. I will send a fix shortly.

What's happening here is a side effect of `-coverpkg=all`, in which we gather coverage data from **everything**, including the Go runtime and a lot of other low-level packages. This in turn means that the underlying coverage counters can be changing even as the data is being written out, which is the source of this particular bug.

As a workaround, I recommend picking out just the packages that you are actually interested in and passing those to -coverpkg; doing that won't expose you to this particular problem.

**Comment by rumtid** [comment]
I see, thanks a lot.
