### ISSUE TITLE
net/http: bufio.Writer aren't garbage collected after Hijack

### ISSUE THREAD

**Issue by lxzan** [golang/go#59567]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.3 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/caster/Library/Caches/go-build"
GOENV="/Users/caster/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/caster/go/pkg/mod"
GONOPROXY=""
GONOSUMDB="gitlab.ustock.cc/*"
GOOS="darwin"
GOPATH="/Users/caster/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="0"
GOMOD="/Users/caster/go/src/github.com/lxzan/go-websocket-testing/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/q0/5vn9xlns1cd70d3mzcdg3jv00000gn/T/go-build966805946=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

upgrade http to websocket

### What did you expect to see?

After hijacking the http connection, the bufio.Writer in the connection is garbage collected

### What did you see instead?

They have never been released

**Comment by seankhliao** [comment]
which bufio Reader / Writer are you referring to?
Do you have code to demonstrate the issue?

**Comment by das7pad** [comment]
Hi @seankhliao, the returning of a write buffer you likely pointed at, `http.response.w`, is for the buffer used in chunked-encoding. It is one of two write buffers that are used as part of the request/response life cycle.

https://github.com/golang/go/blob/35222eeb78ddb84f5787729c5f149cfd73d63ef8/src/net/http/server.go#L2118


The other write buffer is attached to the connection, `http.conn.bufw`, and it remains unused after hijacking.

https://github.com/golang/go/blob/35222eeb78ddb84f5787729c5f149cfd73d63ef8/src/net/http/server.go#L288-L289

As part of the hijack process, the connection read buffer, `http.conn.bufr`, will be re-used and returned to the hijack caller. A new write buffer will be allocated and returned to the caller.

https://github.com/golang/go/blob/35222eeb78ddb84f5787729c5f149cfd73d63ef8/src/net/http/server.go#L325

I do not see a need for allocating a new write buffer as part of the hijack process. After hijacking a connection, no further writes can be made via the `http.response` methods.
So we might as well re-use the connection write buffer and return it to the hijack caller. WDYT @seankhliao?

The net/http unit tests are happy with the following patch and `BenchmarkServerHijack` records a reduction of two allocations worth 4172 bytes per operation (the 4096B buffer slice and a struct for the buffer).

Patch: 25b0691cf41bcf5a8d9a0446e93f5eb6ab3f90b8
```diff
diff --git a/src/net/http/server.go b/src/net/http/server.go
index 9245778590..0ba55e8ee5 100644
--- a/src/net/http/server.go
+++ b/src/net/http/server.go
@@ -322,7 +322,7 @@ func (c *conn) hijackLocked() (rwc net.Conn, buf *bufio.ReadWriter, err error) {
        rwc = c.rwc
        rwc.SetDeadline(time.Time{})
 
-       buf = bufio.NewReadWriter(c.bufr, bufio.NewWriter(rwc))
+       buf = bufio.NewReadWriter(c.bufr, c.bufw)
        if c.r.hasByte {
                if _, err := c.bufr.Peek(c.bufr.Buffered() + 1); err != nil {
                        return nil, nil, fmt.Errorf("unexpected Peek failure reading buffered byte: %v", err)
```

<details>
<summary> BenchmarkServerHijack stats </summary>

```
goos: linux
goarch: amd64
pkg: net/http
cpu: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
               │   old.txt   │               new.txt               │
               │   sec/op    │   sec/op     vs base                │
ServerHijack-8   13.28µ ± 2%   10.84µ ± 3%  -18.36% (p=0.000 n=10)

               │   old.txt    │               new.txt                │
               │     B/op     │     B/op      vs base                │
ServerHijack-8   15.84Ki ± 0%   11.77Ki ± 0%  -25.70% (p=0.000 n=10)

               │  old.txt   │              new.txt              │
               │ allocs/op  │ allocs/op   vs base               │
ServerHijack-8   50.00 ± 0%   48.00 ± 0%  -4.00% (p=0.000 n=10)
```
</details>

I can open a PR with the patch in case you are happy with the approach, @seankhliao.
