### ISSUE TITLE
cmd/compile: incorrect inline function variable

### ISSUE THREAD

**Issue by wdvxdr1123** [golang/go#59572]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?
```go
package main

func foo() {
	println("foo")
}

func main() {
	fn := foo
	for _, fn = range list {
		fn()
	}
}

var list = []func(){
	func() {
		println("1")
	},
	func() {
		println("2")
	},
	func() {
		println("3")
	},
}
```
https://go.dev/play/p/gJSSO8xRwyl

### What did you expect to see?
output
```
1
2
3
```
### What did you see instead?
output
```
foo
foo
foo
```

```
go run -gcflags='-m=1' a.go
# command-line-arguments
./a.go:3:6: can inline foo
./a.go:7:6: can inline main
./a.go:10:5: inlining call to foo
./a.go:15:2: can inline glob..func1
./a.go:18:2: can inline glob..func2
./a.go:21:2: can inline glob..func3
```

I'll send a CL to fix soon.

**Comment by randall77** [comment]
@gopherbot please open backport issues. This is a bad miscompilation.

**Comment by ianlancetaylor** [comment]
Works in Go 1.15, broken since then.  Works in gccgo.
