### ISSUE TITLE
x/pkgsite: package removal request for fauna/faunadb-go/v5

### ISSUE THREAD

**Issue by adambollen** [golang/go#59577]
### What is the path of the package that you would like to have removed?

 

https://pkg.go.dev/github.com/fauna/faunadb-go/v5 (only deprecating v5; other versions remain untouched)
 
### Are you the owner of this package?

Yes, I'm an engineer with Fauna, Inc.; I've been tasked with deprecating the v5 version of our drivers.
 
### What is the reason that you could not retract this package instead?

We have deleted the branch that hosted the v5 version of our drivers and we don't intend to push a new version in the v5 path, so retracting isn't feasible.

**Comment by bcmills** [comment]
> We have deleted the branch that hosted the v5 version of our drivers and we don't intend to push a new version in the v5 path, so retracting isn't feasible.

Why not push a new version in order to publish the `retract` directive and deprecation notice?

**Comment by adambollen** [comment]
Thanks for the quick reply, @bcmills .  As mentioned, the branch from which we released this v5 version doesn't exist anymore and we aren't planning on releasing any more versions in the v5 path.

Here's the go.mod for our v4 path: https://github.com/fauna/faunadb-go/blob/v4/go.mod - my understanding is that if I updated the file temporarily to point to the v5 path and published a retraction of `5.0.0-beta`, that would necessarily push a _new_ v5 version, correct?  And my guess is that I can't simply add the `retract` directive to the current go.mod (that points at `v4`) to retract a v5 version.

Appreciate any help you can provide; if I've made a wrong assumption (I'm not a golang expert), let me know.  Thanks!

**Comment by bcmills** [comment]
> As mentioned, the branch from which we released this v5 version doesn't exist anymore and we aren't planning on releasing any more versions in the v5 path.

You don't need to recreate the whole branch to publish a `v5` version. (All it takes is a single commit with a version tag, and if it has an explicit tag it doesn't even need to be reachable from any branch that remains.)

**Comment by bcmills** [comment]
> my understanding is that if I updated the file temporarily to point to the v5 path and published a retraction of 5.0.0-beta, that would necessarily push a new v5 version, correct?

Yes, you would need to publish a new `v5` version (like `v5.0.0-deprecated`) and have its `retract` directive include that version as well (so that `v5.0.0-deprecated` retracts itself along with all previous versions of its path).

**Comment by adambollen** [comment]
> > my understanding is that if I updated the file temporarily to point to the v5 path and published a retraction of 5.0.0-beta, that would necessarily push a new v5 version, correct?
> 
> Yes, you would need to publish a new `v5` version (like `v5.0.0-deprecated`) and have its `retract` directive include that version as well (so that `v5.0.0-deprecated` retracts itself along with all previous versions of its path).

Ah, I think this was my misunderstanding; I presumed that I couldn't retract the version I was also publishing.  I'll go that route.  Thanks!
