### ISSUE TITLE
affected/package: time

### ISSUE THREAD

**Issue by engineering-this** [golang/go#59582]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, I can reproduce it in go playgorund with 1.20

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOHOSTARCH="amd64"
GOHOSTOS="linux"
</pre></details>

### What did you do?

Golang uses wrong timezone for Marocco. 
According to https://www.timeanddate.com/time/zone/morocco/casablanca
Casablanca has UTC+1 for day of 27.04.2023
According to wikipedia Marocco has always DST except for month of Ramandan: https://en.wikipedia.org/wiki/Daylight_saving_time_in_Morocco

```go
// You can edit this code!
// Click here and start typing.
package main

import (
	"fmt"
	"time"
)

func main() {
	location := "Africa/Casablanca"
	loc, err := time.LoadLocation(location)
	if err != nil {
		panic(err)
	}
	dateTime := "2023-04-27 21:45"
	format := "2006-01-02 15:04"
	t, err := time.ParseInLocation(format, dateTime, loc)
	if err != nil {
		panic(err)
	}
	fmt.Println(t) //Expected 2023-04-27 21:45:00 +0100 +00
}

```
https://go.dev/play/p/tukVIJjI-_n

### What did you expect to see?

In code above expected print:  `2023-04-27 21:45:00 +0100 +00`

### What did you see instead?

`2023-04-27 21:45:00 +0000 +00`

**Comment by ianlancetaylor** [comment]
Go programs get timezone information from the system on which they are run.  On a Linux system this usually comes from the files under /usr/share/zoneinfo.  To get correct timezone information you need to update those files.

Closing because there isn't anything to change in Go.

**Comment by engineering-this** [comment]
In this case it should be fixed in https://go.dev/play

**Comment by ianlancetaylor** [comment]
I'm sorry, I didn't realize that you are speaking specifically about the playground.  The playground gets updated from time to time.  We aren't going to commit to keeping the playground timezone information up to date at all time.

**Comment by fzipp** [comment]
As I understand the updates to the time zone information [lib/time/zoneinfo.zip](https://github.com/golang/go/blob/master/lib/time/zoneinfo.zip) bundled with Go that is used by the playground are tracked in #22487 and it is updated before each release if there is a new version. The version bundled with Go is 2022g, the time zone information for Morocco was fixed in 2023a: http://mm.icann.org/pipermail/tz-announce/2023-March/000077.html
