### ISSUE TITLE
x/net/websocket: server should ping on an interval

### ISSUE THREAD

**Issue by lukescott** [golang/go#5958]
<pre>RFC6455 has a ping/pong function that allows the server to discover if the client isn't
responding. The go.net/websocket library will respond to pings, but cannot send them or
do anything with pongs.

What I'd like to see is some sort of PingInterval / PongTimeout value that causes pings
to be sent on a timer, and then timeout the connection if a pong hasn't been received.

Perhaps this can be done in the Read function, or done in a go routine. It would likely
have to use SetReadDeadline, but I'm not sure how that would work with the existing
exported function.</pre>

**Comment by klausenbusk** [comment]
3 year later, and nothing had happened yet.

**Comment by bradfitz** [comment]
@klausenbusk, see https://golang.org/wiki/NoMeToo

Perhaps you can elaborate on why this is a problem for you in practice? Can you describe your environment? Do underlying TCP keep-alive mechanisms not adequately cull dead connections?

**Comment by herkyl** [comment]
Haproxy removed connections that have not pinged for X minutes. So golang websocket connections are cut of every 2 minutes in my case.

**Comment by GeorgeLyon** [comment]
TCP keep alive != websocket keepalive because in the case there is a proxy between the client and server, tcp keepalives will go between the proxy and each endpoint, whereas websocket ping pong works and to end.

**Comment by danmux** [comment]
You can 'manually' send a ping frame - what is worse tho is that whether the remote side sends a pong in response or not, makes no difference - it is discarded, with no api to allow the client code to respond to a dead client.

I suspect the intention of `x/net/websocket` would be to defer to the underlying net timeout mechanism, but provides no mechanism to extend the read deadline on a good frame read.

**Comment by cpq** [comment]
@danmux any hint on how pings could be sent manually? The marshalling function looks like this:

```go
func marshal(v interface{}) (msg []byte, payloadType byte, err error) {
	switch data := v.(type) {
	case string:
		return []byte(data), TextFrame, nil
	case []byte:
		return data, BinaryFrame, nil
	}
	return nil, UnknownFrame, ErrNotSupported
}
```

It is either text or binary, with no way to set the type to PingFrame.

**Comment by klausenbusk** [comment]
> @danmux any hint on how pings could be sent manually? The marshalling function looks like this:

```
codec := websocket.Codec{Marshal: func(v interface{}) (data []byte, payloadType byte, err error) {
	return nil, websocket.PingFrame, nil
}}
if err := codec.Send(ws, nil); err != nil {
	conn.Close()
}
```

**Comment by mkungla** [comment]
why is it still open issue?

**Comment by bradfitz** [comment]
@mkungla, because it's not yet implemented. Or are you asking why people haven't prioritized fixing this?

**Comment by odeke-em** [comment]
Thanks everyone for the engagement on this issue, and for the patience.

We no longer maintain x/net/websocket and instead recommend these libraries:
* https://godoc.org/github.com/gorilla/websocket
* https://godoc.org/nhooyr.io/websocket

But at least a work around of manual pings was suggested by @danmux in https://github.com/golang/go/issues/5958#issuecomment-364878073, and code was provided by @klausenbusk in https://github.com/golang/go/issues/5958#issuecomment-425639709.

Thus, I shall close this issue. Thank you again.
