### ISSUE TITLE
testing: Coverage() function doesnt work for go 1.20+

### ISSUE THREAD

**Issue by jehowell** [golang/go#59590]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.3 linux/arm64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN="/go/bin"
GOCACHE="/home/vscode/.cache/go-build"
GOENV="/home/vscode/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm64"
GOVCS=""
GOVERSION="go1.20.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/workspaces/work/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2929308236=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Calling testing.Coverage() always returns 0.0. Looking at the source, this function has not been updated to the new coverage2 system.

### What did you expect to see?

testing.Coverage() should return the percent of code coverage for the current unit test.

### What did you see instead?

Always returns 0

**Comment by ianlancetaylor** [comment]
CC @thanm

**Comment by thanm** [comment]
Thanks for the report.  `testing.Coverage()` is definitely something that slipped through the cracks (it currently has no unit tests); I'll add this to my other cleanup items for code coverage this release.

**Comment by jehowell** [comment]
Awesome thanks! In addition, it would be great if that value Coverage() returns is the game as the one that gets sent to the console report after the test. The previous implementation did not calculate this value the same way so the value returned differed from the coverage report (% of blocks vs % of statements). 

We use this value as a pseudo way to enforce test coverage. Would love to see this more integrated into the tools in the future to do this in a more official way.

**Comment by simonkotwicz** [comment]
@thanm may not be related but Go 1.20 broke overall code coverage for a lot of people as per https://github.com/golang/go/issues/24570#issuecomment-1415144330

**Comment by thanm** [comment]
Thanks. I'll put that issue on my list.

Cheers, Than

**Comment by thanm** [comment]
From https://github.com/golang/go/wiki/MinorReleases:

_Our default decision should always be to not backport, but fixes for security issues, serious problems with no workaround, and documentation fixes are backported to the most recent two release branches, if applicable to that branch_

Generally speaking "serious problem" means your program is crashing or computing incorrect results, that sort of thing.   I would be surprised in this case if the release team were to approve a backport given the nature of the bug. Sorry about that.
