### ISSUE TITLE
x/net/websocket: No way to manage connection outside of handler

### ISSUE THREAD

**Issue by lukescott** [golang/go#5959]
<pre>Currently there is no way to get a websocket.Conn object without leaving the handler, or
without having a handler at all. I need to wrap the websocket.Conn object for another
library, but not without maintaing a blocked go routine.

I suggest adding this method:

func (s Server) Upgrade(w http.ResponseWriter, req *http.Request) (conn *Conn, err
error) {
    var rwc net.Conn
    var buf *bufio.ReadWriter
    if rwc, buf, err = w.(http.Hijacker).Hijack(); err != nil {
        return nil, err
    }
    conn, err = newServerConn(rwc, buf, req, &amp;s.Config, s.Handshake);
    return
}</pre>

**Comment by odeke-em** [comment]
Thank you @lukescott for having filed this issue, for the patience, and for using Go. Unfortunately we no longer maintain x/net/websocket and instead recommend using libraries
* https://godoc.org/github.com/gorilla/websocket
* https://godoc.org/nhooyr.io/websocket

I shall close this issue.
