### ISSUE TITLE
http.client io.CopyN(io.Discard, resp.Body, maxBodySlurpSize) out of memory

### ISSUE THREAD

**Issue by liubaochuan** [golang/go#59592]
<pre>
$ go version
go version go1.20.3 linux/amd64
</pre>

Total: 7.64GB
ROUTINE ======================== io.ReadAll in /usr/local/go/src/io/io.go
    4.83GB     6.26GB (flat, cum) 81.95% of Total
         .          .    638:}
         .          .    639:
         .          .    640:var blackHolePool = sync.Pool{
         .          .    641:   New: func() any {
         .          .    642:           b := make([]byte, 8192)
    4.83GB     4.83GB    643:           return &b
         .          .    644:   },
         .     1.43GB    645:}
         .          .    646:
         .          .    647:func (discard) ReadFrom(r Reader) (n int64, err error) {
         .          .    648:   bufp := blackHolePool.Get().(*[]byte)
         .          .    649:   readSize := 0
         .          .    650:   for {

**Comment by seankhliao** [comment]
I think this is working as expected, the temporary read buffers have to come from somewhere, in this case it's from discard due to the upgrade to ReadFrom.

you'll just need more resources to handle the higher number of concurrent requests

**Comment by liubaochuan** [comment]
> I think this is working as expected, the temporary read buffers have to come from somewhere, in this case it's from discard due to the upgrade to ReadFrom.
> 
> you'll just need more resources to handle the higher number of concurrent requests

How to limit unlimited memory growth and adaptively handle processing speed in high-concurrency scenarios
