### ISSUE TITLE
cgo: cannot use C reference variable created by one package in another

### ISSUE THREAD

**Issue by gucio321** [golang/go#59606]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.2 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/gucio/.cache/go-build"
GOENV="/home/gucio/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/gucio/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/gucio/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1985314571=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

hi
cgo is an awesome tool.
sometimes however it is really confusing :confused: 
I'm trying to make a generic package used to convert GO types into C types.
The problem is that package, where I'm using converted type complains about them not being of the same type...

wrapper reference: https://github.com/gucio321/cimgui-go/blob/wrapper-extract/internal/wrapper/type_wrapper.go
project ref: gttps://github.com/gucio321/cimgui-go/tree-wrapper-extract

### What did you expect to see?

as C is treated as pseudo-package (`import "C"`) `C.char`/`C.int` _should_ (in my opinion) be equal, shouldn't they?

### What did you see instead?

```console
cannot use text_beginArg (variable of type *wrapper._Ctype_char) as *_Ctype_char value in variable declaration
```

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by gucio321** [comment]
> Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.
> 
> For questions please refer to https://github.com/golang/go/wiki/Questions

@seankhliao I know it may be a bit subjective, but I consider this a bug anyway.

**Comment by ianlancetaylor** [comment]
Dup of #13467.
