### ISSUE TITLE
proposal: math/rand: add InsecureRand 

### ISSUE THREAD

**Issue by BobDu** [golang/go#59629]
https://github.com/golang/go/issues/20661
now, we only deprecate math/rand.Read , in initial proposal suggest add a  math/rand.InsecureRand 

in many cases (like only create a random string in internal system for idempotent), we need math/rand.
So, we should give developers a choice.

**Comment by seankhliao** [comment]
Only the global function is deprecated, we're not going to add back a new global, whatever the name is.
You can create your own package level one if you need.
