### ISSUE TITLE
x/tools/gopls: "pattern too long" error with gopls@master + k8s + coc.nvim

### ISSUE THREAD

**Issue by findleyr** [golang/go#59635]
Noticed that when using gopls@master in kubernetes, I am starting to get a new exception in coc.nvim:

![image](https://user-images.githubusercontent.com/57144380/232099327-c09e5594-fe2c-4189-bb0e-c167afe0c8d5.png)

I believe this is related to the (enormous) file watching pattern we serve for Kubernetes directories. But it is surprising that I don't get this error with gopls@v0.11.0. Needs investigation.

More generally, I really hope we can switch to simply requesting all file watching notifications, and avoid the enormous pattern entirely. But this must be carefully tested in various LSP clients.

**Comment by hyangah** [comment]
can we have an experimental flag to use a simplified file watching patterns instead and let people test (in particular those involved in the issue that resulted in the current way of file watch registration)?

**Comment by findleyr** [comment]
So, it turns out that we *do* get this error with gopls@v0.11.0, so I have moved this to 'okay-after-beta1'.

Here is the upstream discussion about file watching: https://github.com/microsoft/vscode/issues/109754

In that discussion, it is suggested that we could simply watch `**`. I think we should test this in various LSP clients to confirm it works.

If we do so, I don't think we need to guard it behind a flag. Or if we do, the default should be to use the simplified watching logic and we can can have a temporary flag to revert to the old behavior.

**Comment by findleyr** [comment]
Unfortunately I don't think this is going to get prioritized for v0.12.0, as much as I'd like to fix it.
