### ISSUE TITLE
go.work: go.work and main.go is same path question

### ISSUE THREAD

**Issue by deatil** [golang/go#59648]
go.work and main.go is same path, but now it not use this. why? 
sometime use work, go.work and main.go is at same path and it must use replace to other pkg at the work.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
