### ISSUE TITLE
runtime: `TestCollisions` failure on `linux-arm64-longtest` TryBot

### ISSUE THREAD

**Issue by bcmills** [golang/go#59643]
```
#!watchflakes
post <- pkg == "runtime" && test == "TestCollisions"
```

https://storage.googleapis.com/go-build-log/eb2e13b8/linux-arm64-longtest_dc236d4a.log:
```
--- FAIL: TestCollisions (0.68s)
    hash_test.go:779: too many collisions i=3 j=13 outputs=32768 out of 65536
    hash_test.go:779: too many collisions i=13 j=3 outputs=32768 out of 65536
FAIL
FAIL	runtime	154.178s
```

**Comment by bcmills** [comment]
That was on `release-branch.go1.20` at [CL 484758](https://go.dev/cl/484758).

**Comment by randall77** [comment]
Weird. Probability says that the number of outputs should be close to 41427 (N balls in N bins, how many bins have a ball? N=65536). And the variance should be quite low, stddev is ~123. That means 32768 is 70 standard deviations away.

amd64 runs seem entirely consistent with that, both with amd64 assembly and with the fallback Go version. I see deviations at most in the small hundreds, not the tens of thousands.

arm64 looks different. The fallback is still ok, but the arm64 assembly has some weird behavior. For some cases it hits every bin exactly once! As a hash function that's great, but there's definitely something nonrandom about it. I have not been able to reproduce the described failure, but given the weird nonrandom behavior I'm less surprised.

Sounds like the arm64 assembly hash function needs some more mixing.
