### ISSUE TITLE
syscall.SyscallN returns golang.org/x/sys/windows.ERROR_NO_TOKEN (1008) error

### ISSUE THREAD

**Issue by vault-thirteen** [golang/go#59645]
### What version of Go are you using (`go version`)?
1.20.3.

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
Windows 10,
Intel x86-64.

### What did you do?
I am trying to call a procedure from a DLL file in Golang.
Here is the simpliest code to demostrate the effect.

```lang-go
package main

import (
	"fmt"
	"syscall"

	"golang.org/x/sys/windows"
)

const (
	INIT_TIMER          uint32 = 0x00000001
	INIT_AUDIO          uint32 = 0x00000010
	INIT_VIDEO          uint32 = 0x00000020
	INIT_JOYSTICK       uint32 = 0x00000200
	INIT_HAPTIC         uint32 = 0x00001000
	INIT_GAMECONTROLLER uint32 = 0x00002000
	INIT_EVENTS         uint32 = 0x00004000
	INIT_SENSOR         uint32 = 0x00008000
	INIT_NOPARACHUTE    uint32 = 0x00100000
	INIT_EVERYTHING     uint32 = INIT_TIMER | INIT_AUDIO | INIT_VIDEO | INIT_EVENTS |
		INIT_JOYSTICK | INIT_HAPTIC | INIT_GAMECONTROLLER | INIT_SENSOR
)

var sdlDll windows.Handle
var fnInit uintptr

func xInit(flags uint32) {
	ret, _, callErr := syscall.SyscallN(fnInit, uintptr(flags))
	fmt.Println(ret, callErr)
}

func mustBeNoError(err error) {
	if err != nil {
		panic(err)
	}
}

func main() {
	var err error
	sdlDll, err = windows.LoadLibrary("SDL2.dll")
	mustBeNoError(err)
	fnInit, err = windows.GetProcAddress(sdlDll, "SDL_Init")
	mustBeNoError(err)
	xInit(INIT_EVERYTHING) // -> golang.org/x/sys/windows.ERROR_NO_TOKEN (1008)
}
```

A DLL file can be obtained here: 
https://github.com/libsdl-org/SDL/releases/tag/release-2.26.5
https://github.com/libsdl-org/SDL/releases/download/release-2.26.5/SDL2-2.26.5-win32-x64.zip

### What did you expect to see?
I expect to see a successfull cal to a procedure in a DLL file.

### What did you see instead?
I saw an error.
Debugger shows it as: `golang.org/x/sys/windows.ERROR_NO_TOKEN (1008)`.
Program's output is: `0 An attempt was made to reference a token that does not exist.`

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by vault-thirteen** [comment]
Then why does this DLL work in other languages ?

**Comment by vault-thirteen** [comment]
Are you sure that Golang fully supports the `SetLastError` behaviour on Windows O.S. ?

**Comment by vault-thirteen** [comment]
It turns out that Golang is reading errors from WinAPI when the errors were not requested.
Looks like a feature of this language.
