### ISSUE TITLE
cmd/compile: Unnecessary copies of local variables in equality checks

### ISSUE THREAD

**Issue by merykitty** [golang/go#59655]
### Does this issue reproduce with the latest release?
Yes

### What did you do?

https://godbolt.org/z/snnP3KWv7

### What did you expect to see?

The 2 functions should do the same and just take the addresses of the local variables to invoke `type..eq."".Bar`.

### What did you see instead?

The naive one creates 2 temporaries, then takes the addresses of those to invoke `type..eq."".Bar`, while the `*&` version does the expected operations.

**Comment by cuonglm** [comment]
CL https://go-review.googlesource.com/c/go/+/419234 fixed this, could not reproduce with go1.20 and tip.

**Comment by merykitty** [comment]
Thanks, in that case, should I close the issue now?

**Comment by cuonglm** [comment]
> Thanks, in that case, should I close the issue now?

Sure.
