### ISSUE TITLE
os/signal: `warning: syscall() may go away, please rewrite code to use direct calls` on openbsd

### ISSUE THREAD

**Issue by bcmills** [golang/go#59667]
```
#!watchflakes
post <- goos == "openbsd" && `warning: syscall\(\) may go away, please rewrite code to use direct calls`
```

(attn @golang/openbsd @4a6f656c; see also #36435)

**Comment by mknyszek** [comment]
CC @4a6f656c 

This warning pops up in the last failure, but that's actually also a timeout. Maybe needs a new issue?

**Comment by aclements** [comment]
@cherrymui points out this is because os/signal/signal_cgo_test.go:TestTerminalSignal uses `syscall.Syscall`, which kind of unavoidably uses `syscall`. That suggests we either need to rewrite that test to not use `syscall.Syscall` (I'm not sure that's possible) or stop building it on openbsd.

**Comment by bcmills** [comment]
`syscall.Wait4` is already defined. I guess that just leaves `SYS_IOCTL`, for which a wrapper could presumably be added in `internal/syscall/unix`?

**Comment by 4a6f656c** [comment]
I'm going to close this as the `warning: syscall() may go away, please rewrite code to use direct calls on openbsd` message is just a warning. All of the failures logged come from a range of different sources, including timeouts and breakage in other parts of Go (that have since been fixed).
