### ISSUE TITLE
x/tools/gopls: restrict references to workspace packages

### ISSUE THREAD

**Issue by findleyr** [golang/go#59674]
After the rewrite of references/rename, these operations became agnostic to the set of workspace packages. As such, finding references on e.g. `fmt.Println` will find references throughout the module graph, not just in workspace modules.

This is a change in behavior, may produce noisy references, and can lead to slow initial performance of queries, as we only pre-compute reference indexes for workspace packages.

We should filter these queries to workspace packages.

**Comment by adonovan** [comment]
I don't think a rename operation should ever proceed with less than the complete scope of the identifier, as this would leave things in a bad state. If you really want to rename fmt.Println, it should touch every module in the module graph (and hopefully a good client will notice that you're attempting to modify readonly modules in the cache and abort before corrupting the cache or editing any other files). So I propose to leave out rename for now (as we discussed offline).
