### ISSUE TITLE
runtime: CL 481061 "runtime/cgo: store M for C-created thread in pthread key" causes C TSAN failures

### ISSUE THREAD

**Issue by prattmic** [golang/go#59678]
When built with C TSAN, x_cgo_getstackbound triggers race detection on `g->stacklo` because the synchronization is in Go, which isn't instrumented.

Hopefully simple repro coming soon.

cc @cherrymui @doujiang24

**Comment by prattmic** [comment]
The "race" occurs on the write to `g->stacklo` in https://go-review.git.corp.google.com/c/go/+/481061/2/src/runtime/cgo/gcc_stack_unix.c.

My understanding of what happens is:

1. T1 calls into Go, calls `needm`.
2. `needm` gets M1, and calls `cgo_getstackbound`, writing `M1.g0.stack.lo`.
3. T1 exits, calls `dropm` via thread destructor, which puts M1 back on the extra list.
4. T2 calls into Go, calls `needm`.
5. `needm` gets M2 since it is back on the extra list, and calls `cgo_getstackbound`, writing `M1.g0.stack.lo`.

I believe that TSAN sees this as a racing write because it is unaware of synchronization in the runtime preventing two threads from using the same M (`lockextra`). 

I tried to resolve this by adding a dummy barrier just prior to the crosscall in [`pthread_thread_destructor`](https://go-review.git.corp.google.com/c/go/+/481061/2/src/runtime/cgo/gcc_libinit.c), in an attempt to annotate the barrier that `dropm` provides, but it did not work.

```
diff --git a/src/runtime/cgo/gcc_libinit.c b/src/runtime/cgo/gcc_libinit.c
index 9676593211..ec95f90a18 100644
--- a/src/runtime/cgo/gcc_libinit.c
+++ b/src/runtime/cgo/gcc_libinit.c
@@ -142,6 +142,8 @@ pthread_key_destructor(void* g) {
                // We restore g by using the stored g, before dropm in runtime.cgocallback,
                // since the g stored in the TLS by Go might be cleared in some platforms,
                // before this destructor invoked.
+                _cgo_tsan_acquire();
+                _cgo_tsan_release();
                x_crosscall2_ptr(NULL, g, 0, 0);
        }
 }
```

cc @ianlancetaylor @cherrymui do either of you know if I am misunderstanding the semantics of `_cgo_tsan_acquire`/`_cgo_tsan_release`? Or perhaps I missed a case and there really is a race here.

**Comment by prattmic** [comment]
At the moment, https://go.dev/cl/485500 contains the original CL merged with the extra reverted followup CLs, plus a new failing test (based on the snippet aove).

**Comment by prattmic** [comment]
My initial temptation is to change `cgo_getstackbound` to take a `uintptr_t*` argument to place the stack bound, which is just a local variable in the caller, and let the caller write to `gp.stack.lo`. This avoids having C write to the g at all.

I'm just held back by worry at the back of my head that if I've missed something and there really is a race here then that will just mask it.

**Comment by ianlancetaylor** [comment]
There's a lot I don't know here, but why can't `cgo_getstackbound` return a value rather than setting `g->stacklo`?

I don't think passing a `uintptr_t*` will help, because TSAN will still cleverly see the memory write.

If `cgo_getstackbound` does need to set the value, then I think the fix is going to be to call `_cgo_tsan_acquire` before the memory write and call `_cgo_tsan_release` after the memory write.

**Comment by ianlancetaylor** [comment]
I see.  Sure, if you prefer passing a pointer to a local stack variable, that seems like it should work.

**Comment by cherrymui** [comment]
Passing a stack local variable would work. I have a plan to use `cgo_getstackbound` to set the stack bound for the initial C stack in e.g. https://cs.opensource.google/go/go/+/master:src/runtime/cgo/gcc_linux_arm64.c;l=84 . In both places passing a `*G` seems natural, but passing a stack local works as well.

Agreed that an alternative would be putting `_cgo_tsan_acquire` and `_cgo_tsan_release` before and after the write.
