### ISSUE TITLE
cmd/compile: optimize away redundant assignments

### ISSUE THREAD

**Issue by edsrzf** [golang/go#597]
<pre>I have the following program:

func main() {
    var a float

    a = 6.7

    ...
}

Here is the assembly generated with 6g:

0000 (test.go:12) TEXT    main+0(SB),$72-0
0001 (test.go:6) MOVSS   $(0.00000000000000000e+00),X0
0002 (test.go:8) MOVSS   $(6.70000000000000000e+00),X0
...

I would expect the first MOVSS to be optimized away. Subsequent assignments
generate more instructions still. 5g and 8g also generate similar instructions.

Which revision are you using?  (hg identify)
c20b85c872e5+ tip</pre>

**Comment by josharian** [comment]
Fixed by the new SSA backend.
