### ISSUE TITLE
io: refactor ReadAll to not check for realloc before first read

### ISSUE THREAD

**Issue by dolmen** [golang/go#59702]
The current implementation of [`io.ReadAll`](https://pkg.go.dev/io#ReadAll) checks for realloc *before* each read.

I propose instead to check for realloc *after* each successful read. This will avoid a check before the first read as we know the buffer is already allocated and empty.

[Current implementation](https://cs.opensource.google/go/go/+/refs/tags/go1.20.3:src/io/io.go;l=694):
```go
func ReadAll(r Reader) ([]byte, error) {
	b := make([]byte, 0, 512)
	for {
		if len(b) == cap(b) {
			// Add more capacity (let append pick how much).
			b = append(b, 0)[:len(b)]
		}
		n, err := r.Read(b[len(b):cap(b)])
		b = b[:len(b)+n]
		if err != nil {
			if err == EOF {
				err = nil
			}
			return b, err
		}
	}
}
```

My proposal:
```go
func ReadAll(r Reader) ([]byte, error) {
	b := make([]byte, 0, 512)
	for {
		n, err := r.Read(b[len(b):cap(b)])
		b = b[:len(b)+n]
		if err != nil {
			if err == EOF {
				err = nil
			}
			return b, err
		}

		if len(b) == cap(b) {
			// Add more capacity (let append pick how much).
			b = append(b, 0)[:len(b)]
		}
	}
}
```

**Comment by dolmen** [comment]
CL: https://go-review.googlesource.com/c/go/+/486236

**Comment by ianlancetaylor** [comment]
Thanks, but no need to open an issue if you are going to send in a patch anyhow.
