### ISSUE TITLE
net: `Listen("tcp", "localhost:0")` fails on `js/wasm` and `wasip1/wasm`

### ISSUE THREAD

**Issue by bcmills** [golang/go#59718]
### What version of Go are you using (`go version`)?

<pre>
$ gotip version
go version devel go1.21-0853f8ca Fri Apr 14 20:24:18 2023 +0000 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ gotip env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/usr/local/google/home/bcmills/.cache/go-build"
GOENV="/usr/local/google/home/bcmills/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/tmp/tmp.GW5wdtYKZr/.gopath/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/tmp/tmp.GW5wdtYKZr/.gopath"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/google/home/bcmills/sdk/gotip"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/google/home/bcmills/sdk/gotip/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel go1.21-0853f8ca Fri Apr 14 20:24:18 2023 +0000"
GCCGO="/usr/bin/gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="c++"
CGO_ENABLED="1"
GOMOD="/tmp/tmp.GW5wdtYKZr/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3341472864=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

Run the following program with `GOOS=js GOARCH=wasm`:

```go
package main

import (
	"fmt"
	"net"
	"os"

	"golang.org/x/net/nettest"
)

func main() {
	if !nettest.TestableNetwork("tcp") {
		fmt.Println("tcp is not testable")
		os.Exit(1)
	}
	if !nettest.TestableAddress("tcp", "localhost") {
		fmt.Println("localhost is not testable on tcp")
		os.Exit(1)
	}
	l, err := net.Listen("tcp", "localhost:0")
	if err != nil {
		panic(err)
	}
	fmt.Printf("listening on %s\n", l.Addr())
	l.Close()
}
```

### What did you expect to see?

One of the “… `is not testable`“ messages, or a Listener address.

### What did you see instead?

```
$ GOOS=js GOARCH=wasm go run .
panic: listen tcp: lookup localhost: Protocol not available

goroutine 1 [running]:
main.main()
        /tmp/tmp.GW5wdtYKZr/main.go:22 +0x2a
exit status 2
```

----

Perhaps tellingly, [`net/conn_test.go`](https://cs.opensource.google/go/go/+/master:src/net/conn_test.go;l=5-8;drc=ee591c841439292a8ecdefcb66d518381928d9f3) claims:
```
// This file implements API tests across platforms and will never have a build
// tag.
```
but then:
```
//go:build !js && !wasip1
```
(introduced in [CL 109995](https://go.dev/cl/109995))

(attn @golang/wasm)

**Comment by bcmills** [comment]
@golang/wasm, is this something that can reasonably be fixed? Dealing with this idiosyncrasy adds significant friction in writing tests.

**Comment by johanbrandhorst** [comment]
I'm looking at https://cs.opensource.google/go/x/net/+/refs/tags/v0.14.0:nettest/nettest.go;l=111 and it looks to me like both `js` and `wasip1` should return false for `nettest.TestableNetwork`, no? Maybe I'm misunderstanding the question?

**Comment by bcmills** [comment]
@johanbrandhorst , that's for `ip`. This behavior is for `tcp` and `tcp4`.

**Comment by johanbrandhorst** [comment]
Ah so the problem is in `probeStack`. I would have to do some digging, not sure why that identifies tcp as available 🤔. CC @achille-roussel.
