### ISSUE TITLE
syscall: add prlimit

### ISSUE THREAD

**Issue by YallaPayInc** [golang/go#59712]
i have this issues when go run my project package 

/usr/bin/ld: /root/.cache/go-build/b5/b57f729b94d703ef771f9fbc8d67eb3ffd7f44d5567a271fccd55d54c1a2cecf-d(_go_.o): in function `golang_0org_1x_1sys_1unix.Prlimit':

/root/go/pkg/mod/golang.org/x/sys@v0.7.0/unix/syscall_linux.go:1895: undefined reference to `syscall.prlimit'
collect2: error: ld returned 1 exit status

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by YallaPayInc** [comment]
how please ?

**Comment by ianlancetaylor** [comment]
@YallaPayInc You'll have to patch and rebuild gccgo's libgo library.  The fix is https://go.dev/cl/486576.

**Comment by YallaPayInc** [comment]
i uploaded patch file on project directory but still error exist

**Comment by ianlancetaylor** [comment]
@YallaPayInc To be clear, you are using gccgo, which is not the usual Go compiler.  In order to use the patch, you will have to build and install a new version of gccgo.  If you have not done that before, that is a difficult job.  But if you have done that before, are you sure that you want to be using gccgo?  Perhaps you should be using the default Go compiler, which is known as gc.

**Comment by YallaPayInc** [comment]
i'm using it already 

g++ (Ubuntu 12.2.0-3ubuntu1) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by YallaPayInc** [comment]
i have path for gcc under usr/lib  so is this correct path to add patch file for fix issue ?

**Comment by ianlancetaylor** [comment]
In order to apply the patch you must download the GCC sources, you must apply the patch to the GCC sources, and you must rebuild and reinstall GCC.

If you have not done this before I do not recommend doing it today.  It is difficult.

**Comment by YallaPayInc** [comment]
regarding to this error message when compile Go project 
/usr/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/bin/ld: /root/.cache/go-build/b5/b57f729b94d703ef771f9fbc8d67eb3ffd7f44d5567a271fccd55d54c1a2cecf-d(_go_.o): in function `golang_0org_1x_1sys_1unix.Prlimit':
/root/go/pkg/mod/golang.org/x/sys@v0.7.0/unix/syscall_linux.go:1895: undefined reference to `syscall.prlimit'
collect2: error: ld returned 1 exit status

so i upload this files if you can help 

https://we.tl/t-2gzlx5cz5I

**Comment by mknyszek** [comment]
@ianlancetaylor I assigned this to you in triage, assuming that your CL is the fix and will close out the issue.
