### ISSUE TITLE
x/tools/gopls: error importing package with go 1.20. The error does not appear with GO 1.19

### ISSUE THREAD

**Issue by Luizfpereira** [golang/go#59756]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.20.3

</pre>

### Does this issue reproduce with the latest release?
No.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\luizp\AppData\Local\go-build
set GOENV=C:\Users\luizp\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\luizp\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\luizp\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.20
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=C:\Users\luizp\go\src\chatservice\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config

</pre></details>

### What did you do?

I tried to import the package "github.com/j178/tiktoken-go" with GO version 1.20. However, even after go mod tidy, it appears in the terminal that GO could find and download the package. As I am using VSCode to test, it still indicates an error saying that it could not import the package and so, I was not able to visualize the methods that I could call from the package.

When I changed GO version to 1.19, the package was imported without problems and VSCode stopped indicating me about the error.

### What did you expect to see?

A correct package import.

### What did you see instead?

After downloading the package, my editor still indicated an error saying that the package could not be imported. The error was solved only after changing GO versions.

**Comment by findleyr** [comment]
Thank you for the report. I will investigate.

**Comment by findleyr** [comment]
Hi, I could not reproduce this in a new module. Here is my go.mod:

```
module mod.test

go 1.21

require github.com/j178/tiktoken-go v0.2.1

require github.com/sashabaranov/go-openai v1.5.8 // indirect
```

And here is my main.go:

```
package main

import tiktoken_go "github.com/j178/tiktoken-go"

func main() {
	_ = tiktoken_go.CountMessagesTokens
}
```

Can you share a minimal reproducer?
