### ISSUE TITLE
x/website: better documentation for writing v2+ go modules

### ISSUE THREAD

**Issue by mcandre** [golang/go#59772]
I still don't understand how we're expected to write post-v1.x series go modules. The current `go install` behavior is confusing and the current documentation is quite sparse.

Ideally, v0 and v2 would behave identically in the `go mod` system. But I'd settle at least for clearer documentation.

**Comment by gophun** [comment]
It would probably help if you pointed out at which point in the text of the existing documentation you got stuck.

https://go.dev/doc/modules/release-workflow#breaking
https://go.dev/doc/modules/major-version

**Comment by thediveo** [comment]
one thing that is intuitive only after some trial and error is that `@latest` doesn't go for v2 unless you specify `/v2`. Maybe the OP thinks of this?

**Comment by mvdan** [comment]
Two weeks without a clarifying reply, and [it's not the first time](https://github.com/golang/go/issues/41739#issuecomment-703303783), so I'm closing this for now.
