### ISSUE TITLE
cmd/go/internal/modindex: index_format.txt is out of date

### ISSUE THREAD

**Issue by bradfitz** [golang/go#59770]
As of Apr 2023 (87272bd1a18666ec38ac44c63e11c739f3054056), [`cmd/go/internal/modindex/index_format.go`](https://github.com/golang/go/blob/87272bd1a18666ec38ac44c63e11c739f3054056/src/cmd/go/internal/modindex/index_format.txt) describes `"go index v0"`.

But the index format was updated to `"go index v1"` in 7510e597def68cee77e8ba280fc0f04d3cfd2a22 and `"go index v2"` in bd8ec78b08ead1fb34ec8dc7bc4bf2ff7a9e8b82

**Comment by akarshit49** [comment]
Hi @bradfitz I am new to open source contribution and I am interested in resolving this issue. Can you guide me where and what needs to be resolved?

**Comment by ianlancetaylor** [comment]
@akarshit49 Thanks, but this kind of change to the internal documentation is usually best left to the code maintainers.

**Comment by ianlancetaylor** [comment]
CC @matloob @bcmills
