### ISSUE TITLE
access: go-approvers

### ISSUE THREAD

**Issue by hickford** [golang/go#59771]
Hi. Please consider me for go-approvers. See https://go.dev/wiki/GithubAccess.

> The poorly named "go-approvers" group is the set of people who can edit metadata on issues.

I hope to continue to tidy https://github.com/golang/oauth2/

**Comment by seankhliao** [comment]
cc @golang/release

**Comment by cagedmantis** [comment]
You've been granted go-approvers access. Thank you for helping keep oauth2 tidy.
