### ISSUE TITLE
x/pkgsite: trouble with Apache 2 LICENSE file at repository root

### ISSUE THREAD

**Issue by tschaub** [golang/go#59782]
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/planetlabs/go-ogc@v0.8.0

### What is your user agent?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36

### Screenshot

![image](https://user-images.githubusercontent.com/41094/233805786-dc9e0389-4925-4dbe-9615-cb57812fbd16.png)

### What did you do?

I visited https://pkg.go.dev/github.com/planetlabs/go-ogc.

### What did you expect to see?

I expected to see [the readme](https://github.com/planetlabs/go-ogc/blob/main/readme.md) rendered and to be able to browse reference docs for the [`filter`](https://pkg.go.dev/github.com/planetlabs/go-ogc@v0.8.0/filter) and [`api`](https://pkg.go.dev/github.com/planetlabs/go-ogc@v0.8.0/api) packages.

### What did you see instead?

Instead, it looks the license information cannot be determined, so no additional information is shown.

Here is the license file for the v0.8.0 version referenced above: https://github.com/planetlabs/go-ogc/blob/v0.8.0/LICENSE

When I run `go-licenses report github.com/planetlabs/go-ogc` (in a project where this is a dependency), I see that it correctly detects the Apache 2 license.

Is there a way to run [`licensecheck`](https://github.com/google/licensecheck) in the same way that the pkg.go.dev site does so I can diagnose why the license is not getting identified?

**Comment by jamalc** [comment]
Alterations to the text of the original license will cause your license to fall below our confidence threshold for detection. Can you revert the changes you have made?

s/LICENSE/NOTICE

<img width="1157" alt="Screenshot 2023-04-28 at 12 18 29 PM" src="https://user-images.githubusercontent.com/18269441/235200908-f130bb91-4971-4973-9450-f2959c1dcacf.png">

**Comment by tschaub** [comment]
Thank you for pointing this out, @jamalc.  I have corrected the license text and the docs are rendering now.
