### ISSUE TITLE
cmd/build: 'GOOS=ios go build' will also include darwin code

### ISSUE THREAD

**Issue by awsong** [golang/go#59789]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.3 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/wsong/Library/Caches/go-build"
GOENV="/Users/wsong/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/wsong/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/wsong/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/opt/homebrew/Cellar/go/1.20.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.20.3/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.3"
GCCGO="gccgo"
AR="ar"
CC="cc"
CXX="c++"
CGO_ENABLED="1"
GOMOD="/tmp/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/lr/s8_5072s6cs602ksv8tv5myh0000gn/T/go-build3771226631=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I intend to compile some code that include only ios implementation, and excluding darwin implementation. 
But I found when I give GOOS=ios my darwin code is also compiled in.

I created a minimal demo folder like this
<pre>
$ ls
test.go         test_darwin.go  test_ios.go
</pre>
If I run go list with GOOS=dardwin, I get
<pre>
$GOOS=darwin go list -f '{{.GoFiles}}' 
[test.go test_darwin.go]
</pre>
If I run go list with GOOS=ios, I get
<pre>
$ GOOS=ios go list -f '{{.GoFiles}}' 
[test.go test_darwin.go test_ios.go]
</pre>
### What did you expect to see?

<pre>
$ GOOS=ios go list -f '{{.GoFiles}}' 
[test.go test_ios.go]
</pre>

### What did you see instead?
<pre>
$ GOOS=ios go list -f '{{.GoFiles}}' 
[test.go test_darwin.go test_ios.go]
</pre>

**Comment by rittneje** [comment]
This is mentioned in the docs. https://pkg.go.dev/cmd/go

> Using GOOS=ios matches build tags and files as for GOOS=darwin in addition to ios tags and files.

You'll need to add a `//go:build !ios` directive at the top of these files if you want to exclude them.

**Comment by awsong** [comment]
I see. I thought all OS types are mutually exclusive. 

Thanks for the info.
