### ISSUE TITLE
sort: add unit tests for slice.go

### ISSUE THREAD

**Issue by khareyash05** [golang/go#59791]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.19.2 windows/amd64

</pre>

I would like to add tests for [slice.go](https://github.com/golang/go/blob/master/src/sort/slice.go)

**Comment by dmitshur** [comment]
CC @golang/vulndb.

**Comment by timothy-king** [comment]
What kind of tests are you hoping to add? Unit tests? Integration tests? Are these tests for the `sort` package? Are these tests of how x/vuln integrates with the `sort` package? What properties are you hoping to test?

**Comment by khareyash05** [comment]
@timothy-king These are the unit tests for the functions in slice.go

**Comment by timothy-king** [comment]
I don't think this is related to vulncheck or vulndb then.

**Comment by khareyash05** [comment]
I am sorry i labeled it wrong! @timothy-king Do we need these tests?

**Comment by timothy-king** [comment]
It would probably depend on the tests. I am no sure what you intend on testing. There are tests of these functions in sort_test.go. Example https://cs.opensource.google/go/go/+/master:src/sort/sort_test.go;l=79 . If you have suggestions for tests that are not already covered, it could make sense.

**Comment by ianlancetaylor** [comment]
There are also tests of `sort.Slice` in the file sort/example_test.go.
