### ISSUE TITLE
x/pkgsite: Footer is not fixed at bottom

### ISSUE THREAD

**Issue by 0xJungleMonkey** [golang/go#59820]
### What is the URL of the page with the issue?
 https://pkg.go.dev/search?q=golang.org%2fx%20%23error
 
 
### What is your user agent?
 [Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36](https://explore.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)
 
 
### Screenshot
<img width="1512" alt="Screenshot 2023-04-24 at 10 48 51 PM" src="https://user-images.githubusercontent.com/86534234/234163178-59cf39ce-7b29-4153-95e6-b38c681aa7c7.png">

 
 
### What did you do?
1.  https://pkg.go.dev/
2. search for any pkg and enter the documentation page. 
3. scroll down, the footer is in the middle of the screen.
 
 
 
### What did you expect to see?
 Footer fixed at the bottom of the screen
 
 
### What did you see instead?
Footer hang in the middle of the screen

**Comment by fzipp** [comment]
I have the exact same user agent string and I can't reproduce it with the given link. Maybe one of your browser extensions is interfering? Can you check if the problem still occurs when you disable them?

**Comment by 0xJungleMonkey** [comment]
Not sure what happened, but it works fine right now. Thanks!
