### ISSUE TITLE
go/types: improve the error message `does not implement interface` by adding a hint if a method is unexported in a different package

### ISSUE THREAD

**Issue by sauterp** [golang/go#59831]
### What version of Go are you using (`go version`)?

go1.20 linux/amd64

### Does this issue reproduce with the latest release?

yes, I reproduced it with 1.20.3

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/sauterp/.cache/go-build"
GOENV="/home/sauterp/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/sauterp/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/sauterp/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build424782179=/tmp/go-build -gno-record-gcc-switches"
</pre>
</details>

### What did you do?

I was refactoring some code that included an unexported type implementing the unexported methods of an unexported interface like this: 
https://go.dev/play/p/LVz8GjGiyuw

I moved the interface to a separate package and exported it there, but I forgot to export its method:
https://go.dev/play/p/fCCisc3I6Y0

### The error message

`./prog.go:12:22: cannot use &pkg.MyImplementation{} (value of type *pkg.MyImplementation) as myInterface value in variable declaration: *pkg.MyImplementation does not implement myInterface (missing method privateMethod)`

This error message could be improved. IMO the statement `*pkg.MyImplementation does not implement myInterface` is not correct and confusing, since the code compiles if both implementation and interface are in the same package. The hint `(missing method privateMethod)` adds to this confusion since my implementation does have `privateMethod`.

I think it's correct that the code fails, since an unexported method from another package should not be available in the importing package. But we could change the error message to something like `*pkg.MyImplementation cannot implement unexported method privateMethod from myInterface since they are in different packages.`

**Comment by dmitshur** [comment]
CC @griesemer, @findleyr.
