### ISSUE TITLE
generics: define 'exclude' semantics in constraints

### ISSUE THREAD

**Issue by Neightly** [golang/go#59857]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.21-22d94dfdc8 Tue Apr 25 01:14:08 2023 +0000 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=D:\DEVPATH\GOBIN
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\DEVPATH\GOMOD
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Administrator\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=E:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=E:\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=devel go1.21-22d94dfdc8 Tue Apr 25 01:14:08 2023 +0000
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=E:\go\src\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build3861961594=/tmp/go-build -gno-record-gcc-switches
GOROOT/bin/go version: go version devel go1.21-22d94dfdc8 Tue Apr 25 01:14:08 2023 +0000 windows/amd64
GOROOT/bin/go tool compile -V: compile version devel go1.21-22d94dfdc8 Tue Apr 25 01:14:08 2023 +0000
gdb --version: GNU gdb (GDB) 7.8.1
</pre></details>

### What did you do?

https://go.dev/play/p/1AQJGcq_YhO

```go
// Get read memory at current position, move pointer for next read.
func Get[T any](p Pointer) (next Pointer, data T) {
	if p.kind&0b_1000_0000 != 0 { // NilPtr
		panic("nilness!")
	}
	data = *(*T)(p.ptr) // FIXME: unsafe.Pointer not work
	next = p.WithOffset(unsafe.Sizeof(data))
	return
}
```

bool, int[N], uint[N], structs, arrays... all work here, even Go pointer, except unsafe.Pointer. 
unsafe.Pointer dereferences pointer.

### What did you expect to see?

There is someway to define a constraint which denote everything except  one (or small number) type.

### What did you see instead?

Currently one can use approximations and unions, both of them are 'include' not 'exclude' .

**Comment by Neightly** [comment]
admit that this scenario is rare and can be addressed by switch any(data). switch is a little ugly.

**Comment by ianlancetaylor** [comment]
This is not something that we are likely to do, as it complicates the type system even more.  We barely understand what we have today.
