### ISSUE TITLE
proposal: math: integer square root

### ISSUE THREAD

**Issue by chiyoi** [golang/go#59861]
Add a function like `math.Isqrt(n int) int`.

Currently I implement this by
```go
sort.Search(n, func(x int) bool { return x * x + 2 * x + 1 > n })
```
but maybe this feature could be added to the standard library like `math.Ilogb`

**Comment by seankhliao** [comment]
our bar for what might be added to math was clarified here https://github.com/golang/go/issues/58146#issuecomment-1497871784

c math.h doesn't have this.
