### ISSUE TITLE
affected/package: strings

### ISSUE THREAD

**Issue by zsr228** [golang/go#59878]
go version: 1.18.3

my test code
```
package string

import (
	"fmt"
	"strings"
	"testing"
)

func TestEmptySp(t *testing.T) {
	fmt.Println(len(strings.Split("", ",")))  //result is 1
}

```

### What did you expect to see?
In my case , I think the result is 0

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.
