### ISSUE TITLE
crypto/tls: do not require extended key usage extension

### ISSUE THREAD

**Issue by gopherbot** [golang/go#5987]
by **jtolds**:

<pre>Currently, Go's server TLS implementation requires clientAuth extendedKeyUsage on any
client certificate when client verification is enabled, with no way to turn it off and
still have client certificate verification. (handshake_server.go, processCertsFromClient)

However, from RFC5280:

&quot;Certificate using applications MAY require that the extended key usage extension
be present and that a particular purpose be indicated in order for the certificate to be
acceptable to that application.&quot;

This says to me that a specific application should be able to choose this behavior, not
have it be forced on them by the TLS library.

Specifically, OpenSSL does *not* require this.

Can we make this optional, or perhaps only require the clientAuth extendedKeyUsage iff
the extendedKeyUsage field is actually used and not the default empty? Or even better,
support verify callbacks like OpenSSL or GnuTLS?</pre>

**Comment by FiloSottile** [comment]
Go likes to be strict wherever possible, and this is not causing widespread issues. It can also now be overridden by `VerifyPeerCertificate`. Closing.
