### ISSUE TITLE
x/tools/go/packages: `TestCgoOption` broken on Windows as of CL 487196

### ISSUE THREAD

**Issue by bcmills** [golang/go#59876]
https://build.golang.org/log/0fe24153d95b32025a7a17173fb145e2b460fbd4:
```
--- FAIL: TestCgoOption (2.04s)
    stdlib_test.go:110: no object net.addrinfoErrno
FAIL
FAIL	golang.org/x/tools/go/packages	47.889s
```

The underlying problem is that the test is making assumptions about the internal implementation details of the `net` package, and those implementation details changed in [CL 487196](https://go.dev/cl/487196).

The test should be fixed to not rely on the implementation details of a package outside of its own module.

(attn @matloob @adonovan)

**Comment by adonovan** [comment]
It's not clear to me how that test actually exercises the two states of the Cgo option: it used to loop over them, but that was removed in CL https://go.dev/cl/125535 (see stdlib_test.go:97). I was in the middle of writing a hermetic replacement for this test that creates a tiny module in $TMP, but then I realized there are a bunch of existing tests that seem to cover that (e.g. TestTypecheckCgo, TestCgoNoCcompiler, TestCgoMissingFile, TestLoadImportsC, TestCgoNoSyntax, testCgoBadPkgConfig).

So perhaps the right thing do is just delete this test?
