### ISSUE TITLE
x/tools/go/analysis/passes/printf: say what the right type is in the analyzer

### ISSUE THREAD

**Issue by b0ri5** [golang/go#59875]
The analyzer output at https://github.com/golang/tools/blob/master/go/analysis/passes/printf/printf.go#L889 knows that you're using the wrong type, but does not specify what the right type should be and it seems like it could.

### What did you expect to see?
The correct format string to use. Something like

```
format %s has arg <redacted code> of wrong type bool, should be %t. See also https://pkg.go.dev/fmt#hdr-Printing
```

### What did you see instead?

```
format %s has arg <redacted code> of wrong type bool see also https://pkg.go.dev/fmt#hdr-Printing
```

Would it be feasible to include the correct type in the output?

**Comment by dmitshur** [comment]
CC @timothy-king.

**Comment by timothy-king** [comment]
1. There is always some tension between more informative and being pithy and precise in vet warnings.  IMO the current message is already a bit long, but no part of it is redundant. The end is directing users to a helpful place to self service `format %s has arg <redacted code> of wrong type bool see also https://pkg.go.dev/fmt#hdr-Printing`. We have URLs fields coming soon so perhaps this verbosity will soon no longer required as we can redirect to a landing page that then has the equivalent of `see also https://pkg.go.dev/fmt#hdr-Printing`. So vet may have more space to play with soon.

1. So the message is already pretty helpful. We are mostly discussing whether the message could be *more* helpful.

1. I am somewhat hesitant to think we know user intent here. The checker does know something is wrong so the current message is fine from that regard. Adding a recommendation ("should") kinda requires having an opinion about user intent. And there are also multiple choices valid. Why not recommend `%v`? We can soften the language do be `(Did you mean %t?)`.

1.  I am not sure we want to add a recommendation just for bool. What do we think about other cases? Is it all of the types that have a default format for `%v`? Do we really want to recommend %d over %x or %v for int?

Thoughts from others?

**Comment by AndrewHarrisSPU** [comment]
> Thoughts from others?

At a glance, is `incompatible type` any better than `wrong type`?

Occasionally it's relevant if some `wrong type` implements `fmt.Formatter`, or has a `GoString`, `String`, or `Error` methods, if there's an inclination to provide a guess about what verbs are compatible.

**Comment by adonovan** [comment]
I agree with @timothy-king. The message tells you the offending expression, type, and format verb. Usually there are multiple possible fixes among which the tool has no basis to choose---was the problem with the format or the argument?---yet the appropriate fix is obvious to the user.

**Comment by b0ri5** [comment]
Great, thank you for taking a look at this!
