### ISSUE TITLE
cmd/dist: make.bash -distpack fails

### ISSUE THREAD

**Issue by heschi** [golang/go#59889]
At 265d19ed526b6d6a01a20150918b362c1e6befba, distpack builds are failing:

`distpack: unexpected source archive file: go/src/internal/platform/zosarch.go (generated by dist)`

cc @bcmills, since someone mentioned http://go.dev/cl/483695 might be related.

**Comment by ianlancetaylor** [comment]
I think that CL 490655 will fix this.
