### ISSUE TITLE
x/pkgsite: net/http.Cookie type decl missing

### ISSUE THREAD

**Issue by willfaught** [golang/go#59901]
### What did you do?

Go to https://pkg.go.dev/net/http#Cookie.

### What did you expect to see?

The page load and scroll to the Cookie type.

### What did you see instead?

The page loaded, but it didn't scroll. I scrolled down to where the Cookie type should be, and saw this:

<img width="1080" alt="Screenshot 2023-04-29 at 4 16 11 PM" src="https://user-images.githubusercontent.com/63830/235327883-1e93ad30-a3cb-49e4-89f5-2495e36bc083.png">

There's no `type Cookie struct [...]` content!

**Comment by seankhliao** [comment]
user agent, etc info please, that's not what I see

**Comment by willfaught** [comment]
Woops, sorry.

OS: macOS 13.3.1 (22E261)
Browser: Safari 16.4 (18615.1.26.11.23)

**Comment by jamalc** [comment]
Do you have an extension that hides html elements where id=Cookie?
