### ISSUE TITLE
x/pkgsite:

### ISSUE THREAD

**Issue by CodingDog-CD** [golang/go#59903]
### What is the URL of the page with the issue?
 https://github.com/CodingDog-CD/sorting
 
 
### What is your user agent?
 
[Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36](https://explore.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)
 
 
 
### What did you do?
 
1. added MIT license to my project.
2. tag the current commit: `git tag v0.1.1-beta.1 `
3. push the version into github `git push origin v0.1.1-beta.1`
4. published my golang module `GOPROXY=proxy.golang.org go list -m github.com/CodingDog-CD/sorting@v0.1.1-beta.1`

 
 
### What did you expect to see?
 Documentation shown in [module page](https://pkg.go.dev/github.com/CodingDog-CD/sorting/pkg/quick_sort) instead of the message "Documentation not displayed due to license restrictions."
 
 
### What did you see instead?
Documentation not displayed due to license restrictions.

See our [license policy](https://pkg.go.dev/license-policy).

**Comment by seankhliao** [comment]
patience, plus caching on mutable references like latest https://pkg.go.dev/github.com/CodingDog-CD/sorting@v0.1.1-beta.1/pkg/quick_sort

**Comment by CodingDog-CD** [comment]
Okay... Sorry for my impatience. Thanks a lot.
