### ISSUE TITLE
go/map

### ISSUE THREAD

**Issue by chaoshikong** [golang/go#59917]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
It is already the latest version

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\xxsww\AppData\Local\go-build
set GOENV=C:\Users\xxsww\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=d:\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=d:\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.20
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\go\bug\mapbug\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\xxsww\AppData\Local\Temp\go-build4200823100=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
`package main

import (
	"sync"
	"time"

	"github.com/gofiber/fiber/v2"
)

const DefTime = "2006-01-02 15:04:05"

type cip struct {
	Ip   string
	Time string
}

type sip struct {
	sync.RWMutex
	User map[string]cip
}

func main() {
	app := fiber.New()
	users := sip{User: make(map[string]cip)}

	//查看所有用户的IP信息
	app.Get("/list", func(c *fiber.Ctx) error {
		return c.JSON(fiber.Map{"data": users.User})
	})

	//提交用户的IP
	app.Get("/dns/:name", func(c *fiber.Ctx) error {
		name := c.Params("name")
		if name != "" {
			users.Lock()
			users.User[name] = cip{Ip: c.IP(), Time: time.Now().Format(DefTime)}
			users.Unlock()
		}
		return c.SendString("OK")
	})

	//监听端口2178
	go app.Listen(":2178") //这里不在协程中运行，错误不会出现

	for {
		time.Sleep(time.Second)
	}
}
`

The code is backed up at github.com/chaoshikong/mapbug

### What did you expect to see?
Input in browser http://127.0.0.1:2178/dns/xxx, xxx is a string of different lengths
After entering multiple times, use http://127.0.0.1:2178/list Viewing Data

### What did you see instead?
The result I see is not the string I entered, for example, when I input "abcde" and "fgh", it becomes "fghde" and "fgh" when viewing
A few more inputs will reproduce the error

**Comment by seankhliao** [comment]
I believe this is from fiber being unsafe rather an issue with go itself.
