### ISSUE TITLE
proposal: time/tick.go: Ticker provide api to allow shared C among runtimeTimer objects

### ISSUE THREAD

**Issue by agility323** [golang/go#59920]
If I need N tickers, different period time.
I have to create N goroutines as follows.
`t1 := time.NewTicker(3)`
`t2 := time.NewTicker(7)`
`...`
`go func() { for range t1.C { f1() } }`
`go func() { for range t2.C { f2() } }`
`...`

If there's a api like:
`func NewTickerWithArgs(d Duration, c chan any, arg any) *Tciker {`
`...`
`}`
I can handle this with one goroutine.
`c := make(chan any, 1)`
`t1 := time.NewTickerWithArgs(3, c, f1)`
`t2 := time.NewTickerWithArgs(7, c, f2)`
`...`
`go func() { for itf := range c { itf.(func())() } }`

**Comment by seankhliao** [comment]
you can use select

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
