### ISSUE TITLE
cmd/compile: TestEmptyDwarfRanges and TestScopeRanges fail on ios-arm64-corellium

### ISSUE THREAD

**Issue by bcmills** [golang/go#59939]
https://storage.googleapis.com/go-build-log/d11befbe/ios-arm64-corellium_f53b1ad2.log (a TryBot on [CL 491660](https://go.dev/cl/491660)):
```
--- FAIL: TestEmptyDwarfRanges (0.98s)
    scope_test.go:498: decoding dwarf section info at offset 0x0: too short
--- FAIL: TestScopeRanges (1.01s)
    scope_test.go:234: decoding dwarf section info at offset 0x0: too short
FAIL
FAIL	cmd/compile/internal/dwarfgen	1.038s
```

**Comment by cherrymui** [comment]
On iOS we don't combine the DWARF info into the binary, as the kernel doesn't like such a binary (https://cs.opensource.google/go/go/+/master:src/cmd/link/internal/ld/lib.go;l=1389). So we cannot find the DWARF section from the binary. I think it is okay to skip the test on iOS.

**Comment by bcmills** [comment]
@cherrymui, the code you linked seems to apply to all `darwin` platforms — would this also apply to GOOS=darwin if external linking is forced on?
