### ISSUE TITLE
Incorrect documentation for builtin 'func cap'

### ISSUE THREAD

**Issue by edmundadjei** [golang/go#59937]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes, I can still see this here
https://pkg.go.dev/builtin@go1.20.4

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/eadjei/.cache/go-build"
GOENV="/home/eadjei/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/eadjei/go/pkg/mod"
GONOPROXY=""
GONOSUMDB="bitbucket.org/resumelibrary/*"
GOOS="linux"
GOPATH="/home/eadjei/go"
GOPRIVATE=""
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3458291872=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.19.1 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.19.1
uname -sr: Linux 5.19.0-41-generic
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
gdb --version: GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
</pre></details>

### What did you do?

Trying out some code to check if "cap" returns the same value is "len"

https://go.dev/play/p/u1598FhNDhD

### What did you expect to see?

for the same array, a, cap(a) equals len(a)
as per the documentation here - https://pkg.go.dev/builtin@go1.20.4

-----
func cap(v Type) int
The cap built-in function returns the capacity of v, according to its type:

Array: the number of elements in v (same as len(v)).
-----

### What did you see instead?

for the same array, a, cap(a) does not equal len(a)

**Comment by randall77** [comment]
This is intended. This has nothing to do with `cap` per se, it has to do with the behavior of casting a `string` to a `[]byte`. That allocation can allocate more capacity than the length of the string.

**Comment by edmundadjei** [comment]
I know it is to do with how the malloc works, but shoiuld it not say that in the docs as opposed to suggesting len = cap?

**Comment by randall77** [comment]
`len`==`cap` for arrays. That is absolutely true, not just a suggestion.
The code you showed is not about arrays, it is about slices.
