### ISSUE TITLE
x/website: package names are confusing when considering the included diagram.

### ISSUE THREAD

**Issue by LightBubblegum** [golang/go#59948]
### What is the URL of the page with the issue?
 https://go.dev/doc/modules/major-version
 
 
### What is your user agent?
 

 [Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36](https://explore.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)
 
 
### Screenshot
 

 
<img width="1313" alt="image" src="https://user-images.githubusercontent.com/1853752/235962093-570d433f-321e-4e31-928f-66794f7add27.png">

 
 
### What did you do?
 

 Just open the web-page
 
 
### What did you expect to see?
`example.com/mymodule/v2/package3` 
 
 
### What did you see instead?
`example.com/mymodule/v2/package1`

**Comment by cagedmantis** [comment]
cc @golang/tools-team

**Comment by findleyr** [comment]
The typo is definitely in the image. Unfortunately, the image is harder to fix.
