### ISSUE TITLE
syscall: various gopls tests hang in filesystem operations on illumos

### ISSUE THREAD

**Issue by findleyr** [golang/go#59950]
I've noticed that now that gopls makes heavy use of the filesystem, various gopls tests have started flaking due to hanging in the Lstat syscall on illumos.

For example:
https://github.com/golang/go/issues/57373#issuecomment-1518111315

Creating this issue to aggregate these failures.

CC @golang/illumos @adonovan @bcmills

**Comment by bcmills** [comment]
See also #58967, #59379.

**Comment by findleyr** [comment]
As @bcmills points out, the Lstat goroutine may be a red herring: that is just the filecache.GC. Rather, it looks like the failures are due slowness / hanging in various filesystem operations. Bryan suggests filesystem contention.

**Comment by findleyr** [comment]
Thanks, I'll close as a dupe of #59379.
