### ISSUE TITLE
x/tools/cmd/godoc: public fields of a private embedded struct do not appear in GoDoc

### ISSUE THREAD

**Issue by ijrsvt** [golang/go#59951]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOOS="darwin"
</pre></details>

### What did you do?

I created two structs, one private, one public. I attached a public method to the private struct and then embedded the private struct in the public struct. I can access that public method from elsewhere, but cannot view it in Godoc. Code below:

```
type min interface {
	Var()
}

type Other interface {
	Something()
}

type Max struct {
	Other
	min
}
```

### What did you expect to see?

* I expect to see that this in an available method on the public struct.

### What did you see instead?

<img width="1840" alt="Screenshot 2023-05-03 at 10 33 05 AM" src="https://user-images.githubusercontent.com/21353794/235997913-0b0b0408-017e-462e-8f4f-833508bf7185.png">

**Comment by go101** [comment]
related: https://github.com/golang/go/issues/6600
