### ISSUE TITLE
x/vuln: crash on large repos

### ISSUE THREAD

**Issue by Dafaque** [golang/go#59966]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.3 linux/amd64
go version go1.19.8 linux/amd64 # nix-shell
</pre>

### Does this issue reproduce at the latest version of golang.org/x/vuln?
I've install `@latest` and `@v0.1.0` version, but output shows: 
`Using go1.20.3 and govulncheck@v0.0.0 with`
I guess, yes?

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/me/.cache/go-build"
GOENV="/home/me/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/me/go/pkg/mod"
GONOPROXY="<hidden>"
GONOSUMDB="<hidden>"
GOOS="linux"
GOPATH="/home/me/go"
GOPRIVATE="<hidden>"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="..../go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4038305880=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
Run under vscode intergrated terminal `govulncheck -v ./...` on project that meets condition:
<pre>
$ tree .
......
843 directories, 3746 files
</pre>
In my case it's a very large vendor dir

### What did you expect to see?
My laptop is working and i actually get vuln report

### What did you see instead?
Even cursor is dead for a ~2 min;
htop for a second afrer vscode crash shows all 8 cores and 8gb RAM are full

**Comment by Dafaque** [comment]
UPD
After first success run from outside vscode, witch runs very fast and without  any issues, runs under vscode terminal now out of trouble too

**Comment by Dafaque** [comment]
UPD2
Outside vscode under `nix-shell -p go_1_19`:
```
govulncheck -v ...
govulncheck is an experimental tool. Share feedback at https://go.dev/s/govulncheck-feedback.

Using go1.19.8 and govulncheck@v0.0.0 with
vulnerability data from https://vuln.go.dev (last modified 2023-04-18 21:32:26 +0000 UTC).

Scanning your code and 95 packages across 0 dependent modules for known vulnerabilities...
Killed
```
With total PC freeze

**Comment by Dafaque** [comment]
pure zsh run with go1.20 detects more packages and deps:
```
govulncheck -v ./...                                                                                                                   127 ✘  9s  
govulncheck is an experimental tool. Share feedback at https://go.dev/s/govulncheck-feedback.

Using go1.20.3 and govulncheck@v0.0.0 with
vulnerability data from https://vuln.go.dev (last modified 2023-04-18 21:32:26 +0000 UTC).

Scanning your code and 570 packages across 110 dependent modules for known vulnerabilities...
```

**Comment by Dafaque** [comment]
Just figured out, maybe trouble depends on `go version`
go.mod contains line `go 1.19`, but under go_1_19 always failed to run, but go_1_20 runs perfectly

**Comment by cagedmantis** [comment]
cc @golang/vulndb

**Comment by zpavlinovic** [comment]
Does this issue still reproduce?
