### ISSUE TITLE
cmd/go: "import cycle not allowed in test" message shows wrong stack

### ISSUE THREAD

**Issue by rsc** [golang/go#59970]
```
% cd go/src/internal/godebug
% echo 'package godebug; import _ "testing"' >g_test.go
% go test
# internal/godebug
package internal/godebug
	imports math/rand
	imports testing: import cycle not allowed in test
FAIL	internal/godebug [setup failed]
% 
```

The error is incorrect (the imports it reports are reversed from reality) and incomplete (it doesn't complete the cycle). It should say something like:

```
package internal/godebug
	imports testing
	imports math/rand
	imports internal/godebug: import cycle not allowed in test
FAIL	internal/godebug [setup failed]
```

**Comment by giridharan-7** [comment]
Hey, can i work on this issue? if you don't mind :)

**Comment by giridharan-7** [comment]
ouch!.. I'll try my best but, I am new to opensource and have really some good understanding of the Golang.. for the past 20 days i finding the some good issue to getting start my contribution journey but i didn't find that yet.. If there is any some good beginner friendly issues.. Please suggest me :) have a nice day!!!

**Comment by bcmills** [comment]
@matloob has a fix.
