### ISSUE TITLE
x/build: `git http-backend` on `linux-loong64-3a5000` fails with `GIT_PROJECT_ROOT is set but PATH_INFO is not`

### ISSUE THREAD

**Issue by bcmills** [golang/go#59984]
The `linux-loong64-3a5000` builder started failing as of https://go.dev/cl/491659.
https://build.golang.org/log/2c3437d386796f3252381ab1d3ed9051681bf513:
```
# get http://127.0.0.1:34721/git/gitrepo1
fatal: GIT_PROJECT_ROOT is set but PATH_INFO is not
# get http://127.0.0.1:34721/git/gitrepo1: 500 Internal Server Error (0.052s)
```

The HTTP handler is run using a `net/http/cgi.Handler` via `cmd/go/internal/vcweb`:
https://cs.opensource.google/go/go/+/master:src/cmd/go/internal/vcweb/git.go;l=40-49;drc=57f9ed5f12ba395fa55880305bc11e1db840f36c

The `cgi.Handler` unconditionally sets `PATH_INFO`:
https://cs.opensource.google/go/go/+/master:src/net/http/cgi/host.go;l=118-147;drc=ffa663c9b3c942cbde590bb792179dcca52224b7

So this looks like a bug on `loong64` where either that environment variable is not being passed to the `git` command correctly, or the `git` command is not reading it correctly.

(attn @golang/loong64)

**Comment by abner-chenc** [comment]
Sorry, this error is because the environment variable is set on the builder of loong64 _“http_proxy”_  caused it, I'll deal with it right away.

**Comment by bcmills** [comment]
Looks like this is now fixed?

**Comment by abner-chenc** [comment]
> Looks like this is now fixed?

Yes, I think the problem has been fixed now.

**Comment by npadhya** [comment]
Can someone please attach the PR that fixed it?

**Comment by xen0n** [comment]
> Can someone please attach the PR that fixed it?

Hi; I believe this is solely a builder configuration problem, so there was no code change. @abner-chenc can confirm that as the maintainer of the builder.
