### ISSUE TITLE
x/pkgsite: please add ODbL license to list of approved licenses

### ISSUE THREAD

**Issue by ydnar** [golang/go#59992]
Hi, I’m the author of the [ZoneDB](https://zonedb.org) package (https://pkg.go.dev/github.com/zonedb/zonedb). I visited the GoDoc page for the package today and discovered that the documentation was suppressed because the license we specify in [LICENSE.md](https://github.com/zonedb/zonedb/blob/main/LICENSE.md) is not accepted.

This is a request to add the [Open Data Commons Open Database License (ODbL)](https://opendatacommons.org/licenses/odbl/) to the list of approved licenses.

We could split the license into a separate license for the code and one for the underlying data (zones.txt and metadata JSON files), but it seems inconsistent as the Go package is derived from the base data.

Thanks!
 
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/zonedb/zonedb

No documentation due to policy: https://pkg.go.dev/license-policy
 
### What is your user agent?
 

 
 Safari
 
### Screenshot
 

 
 
<img width="490" alt="Screenshot 2023-05-04 at 3 13 46 PM" src="https://user-images.githubusercontent.com/34146/236340973-c035d125-2f26-4ee1-bd0b-11b8aec179c9.png">

 
### What did you do?
 

 
 Visit the GoDoc page for the zonedb package at: https://pkg.go.dev/github.com/zonedb/zonedb
 
### What did you expect to see?
 
 GoDoc documentation for ZoneDB.
 
### What did you see instead?

<img width="490" alt="Screenshot 2023-05-04 at 3 13 46 PM" src="https://user-images.githubusercontent.com/34146/236340973-c035d125-2f26-4ee1-bd0b-11b8aec179c9.png">

**Comment by seankhliao** [comment]
Our [license policy](https://pkg.go.dev/license-policy) was recently clarified: we can only accept OSI approved licenses. As the Open Data Commons Open Database License (ODbL) is not on the list, this won't be possible.

**Comment by ydnar** [comment]
Looks like the last time OSI contemplated this was 12 years ago:

https://lists.opensource.org/pipermail/license-review_lists.opensource.org/2011-June/001280.html

```
Mike,

> I have some questions about the ODBL
> http://www.opendatacommons.org/licenses/odbl/

To date, OSI has not reviewed or certified any oben content licenses,  
which are necessarily different in structure from open source  
licenses.  This has been discussed, but currently is not a practice of  
OSI.

I've been thinking of setting up a new working group on open content,  
but that would put us at least a year away from certifying anyone.

--Josh Berkus
```

I went ahead and dual-licensed it (code under MIT, database under ODbL). Not ideal, but I’d prefer to not have to split the repo.
