### ISSUE TITLE
encoding/csv: Read returns partial record on error

### ISSUE THREAD

**Issue by IvoGoman** [golang/go#59991]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.20.1 darwin/arm64

</pre>

### Does this issue reproduce with the latest release?
Yes it does

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/<user>/Library/Caches/go-build"
GOENV="/Users/<user>/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/<user>/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/<user>/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.20.1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.20.1/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/<user>/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/29/tcsmnyzs7px55jxt3grz88c80000gn/T/go-build3619271105=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

I have read an invalid csv with csv.Reader 
```golang
invalidCSV := "one,\"two\"\"" # extra quote which leads to parse error
csvReader := csv.NewReader(strings.NewReader(invalidCSV))
res, err := csvReader.Read()
```
See:  https://go.dev/play/p/p66Sy_Z4494

### What did you expect to see?

I have expected to receive a nil record and a non-nil error indicating the problem with this line of csv.

### What did you see instead?
The method returns a partially parsed record and the appropriate error `ErrQuote`. 
The method's documentation states this should never happen: https://github.com/golang/go/blob/fc106b016cc4ba5dc5a1a44eda7524fdce4463bb/src/encoding/csv/reader.go#L188-L191

From what I can tell the behavior has changed 6 years ago with this change: https://github.com/golang/go/commit/2181653be637cdcc7a6efee8ec0a719df1d83c00

**Comment by seankhliao** [comment]
cc @dsnet @bradfitz @rsc as secondary owners

**Comment by dsnet** [comment]
While the convention is that a non-nil error implies a nil return value, this is not required. Callers that care about errors should be checking the error before using the value.

I don't see how we can change this without breaking existing usages that are depending on this semantic.

**Comment by ianlancetaylor** [comment]
We shouldn't change the behavior but we should certainly update the docs.
