### ISSUE TITLE
runtime: crash when >10k C threads call Go after CL 485500

### ISSUE THREAD

**Issue by prattmic** [golang/go#60004]
[`debug.SetMaxThreads`](https://pkg.go.dev/runtime/debug#SetMaxThreads) has a default limit of 10k threads, which is enforced by [`runtime.checkmcount`](https://cs.opensource.google/go/go/+/master:src/runtime/proc.go;l=779;drc=72c33a5ef0eea8663328375d9d339ed150310ebb) when the M is created.

https://go.dev/cl/485500 creates an M for every C thread that calls into Go, freeing the M only when the thread exits. Thus, 10k unique C threads calling into Go at least once will trigger the thread exhaustion throw (assuming the threads don't exit). Prior to CL 485500, the 10k threads would all need to call into Go concurrently to trigger the throw.

I don't think we strictly need to do anything. A program with 10k C threads is exceptional and I think it is reasonable to say that such programs should adjust `debug.SetMaxThreads`.

On the other hand, the primary purpose of this limit is to prevent Go programs from accidentally fork-bombing the system. e.g., by creating 1 million goroutines which all block on a system call, thus requiring 1 million threads. This concern doesn't really apply to threads created by C, since by definition we aren't automatically creating threads. Thus, I think it would reasonable to exclude extra Ms from the `SetMaxThreads` limit.

cc @cherrymui @doujiang24

**Comment by cherrymui** [comment]
>  I think it would reasonable to exclude extra Ms from the SetMaxThreads limit.

That sounds reasonable to me. If C code wants to create a lot of threads, the Go runtime probably should not stop it from doing so.
