### ISSUE TITLE
net: panic dialing udp address on node/wasm

### ISSUE THREAD

**Issue by seankhliao** [golang/go#60012]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.21-10ad6c91de1 Fri May 5 19:53:39 2023 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

no (1.20.4)

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/arccy/.cache/go-build'
GOENV='/home/arccy/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS='-trimpath "-ldflags=-s -w"'
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/arccy/.data/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/arccy/.data/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/home/arccy/sdk/gotip'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLDIR='/home/arccy/sdk/gotip/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='devel go1.21-10ad6c91de1 Fri May 5 19:53:39 2023 +0000'
GCCGO='gccgo'
GOAMD64='v3'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='0'
GOMOD='/home/arccy/tmp/testrepo0180/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build162874202=/tmp/go-build -gno-record-gcc-switches'
21:16:55 ~/tmp/test
</pre></details>

### What did you do?

```go
package main

import (
	"log"
	"net"
)

func main() {
	_, err := net.Dial("udp", "127.0.0.1:1234")
	if err != nil {
		log.Fatalln(err)
	}
}
```

```sh
main » node --version
v19.9.0

21:18:03 ~/tmp/testrepo0180 0:00:00
main » GOOS=js GOARCH=wasm go build -o main.wasm main.go     

21:18:07 ~/tmp/testrepo0180 0:00:00
main » node ~/sdk/gotip/misc/wasm/wasm_exec_node.js main.wasm
panic: interface conversion: net.Addr is *net.UDPAddr, not *net.TCPAddr

goroutine 1 [running]:
net.socket({0x50110, 0x16ef60}, {0x2f2da, 0x3}, 0x2, 0x2, 0x0, 0x0, {0x50398, 0x0}, ...)
	net/net_fake.go:92 +0x59
net.internetSocket({0x50110, 0x16ef60}, {0x2f2da, 0x3}, {0x50398, 0x0}, {0x50398, 0x143a420}, 0x2, 0x0, ...)
	net/ipsock_posix.go:142 +0x3
net.(*sysDialer).dialUDP(0x14561e0, {0x50110, 0x16ef60}, 0x0, 0x143a420)
	net/udpsock_posix.go:212 +0x7
net.(*sysDialer).dialSingle(0x14561e0, {0x50110, 0x16ef60}, {0x4ff80, 0x143a420})
	net/dial.go:643 +0x2c
net.(*sysDialer).dialSerial(0x14561e0, {0x50110, 0x16ef60}, {0x140e0c0, 0x1, 0x1})
	net/dial.go:604 +0x1c
net.(*sysDialer).dialParallel(0x14561e0, {0x50110, 0x16ef60}, {0x140e0c0, 0x1, 0x1}, {0x0, 0x0, 0x0})
	net/dial.go:505 +0x28
net.(*Dialer).DialContext(0x144ae78, {0x50110, 0x16ef60}, {0x2f2da, 0x3}, {0x30a9e, 0xe})
	net/dial.go:496 +0x64
net.(*Dialer).Dial(...)
	net/dial.go:423
net.Dial({0x2f2da, 0x3}, {0x30a9e, 0xe})
	net/dial.go:390 +0x8
main.main()
	./main.go:9 +0x2
```

### What did you expect to see?

an error like "Protocol not available"

### What did you see instead?

panic asserting a TCP address

cc @golang/wasm

**Comment by bcmills** [comment]
I wonder — does that also apply to `GOOS=wasip1`? I think they use the same net stack.

Also in the category of “`net` on `wasm` is weird and buggy”:
- #59718 
- #50216

**Comment by seankhliao** [comment]
I think so

https://github.com/golang/go/blob/4576184b438125966dc761e2384a728f07fb8da8/src/net/net_fake.go#L7
