### ISSUE TITLE
PureGo Plugins?

### ISSUE THREAD

**Issue by zarkones** [golang/go#60020]
I was playing around with the plugins package of the standard library. 
The idea of plugins itself is great.
However, I did not appreciate the fact that I was forced to switch compiler. (plugins are enabled by C language & toolchain)
Searching online I have failed to find a mention of why was it implemented in such a way.

Also, it is my desire to contribute code to the plugins package.
Please refer me to any resources of programming Go.
(apart from the Go source-code, that I'm already reading)

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
