### ISSUE TITLE
x/tools/gopls: exclude "golang.org/toolchain/*" from import completion suggestions

### ISSUE THREAD

**Issue by hyangah** [golang/go#60062]
`golang.org/toolchain/*` added for the extended forward compat work are special modules and not suitable for import candidates.
We probably need to exclude them from goimports computation too.

![Screenshot 2023-05-08 at 9 22 22 PM](https://user-images.githubusercontent.com/4999471/236970628-e189347d-481b-4698-9a0e-2bbac244a156.png)

**Comment by findleyr** [comment]
Thanks for catching this so quickly!

I'm working on goimports, so may do this now, but slotting for v0.13.0 as this is tied to the forward compat work.
