### ISSUE TITLE
go/ast: add func Unparen(Expr) Expr

### ISSUE THREAD

**Issue by adonovan** [golang/go#60061]
Almost every application that uses go/ast needs a function to strip parens. There are 4 copies of `unparen` in the standard library. golang.org/x/tools has [astutil.Unparen](https://pkg.go.dev/golang.org/x/tools/go/ast/astutil#Unparen). I propose we add this function to `go/ast`.

```
package ast // import "go/ast"

// Unparen returns e with any enclosing parentheses stripped.
func Unparen(e Expr) Expr
```

See https://go.dev/cl/495315 for the implementation.

**Comment by rsc** [comment]
No change in consensus, so **[accepted](https://go.dev/s/proposal-status#accepted)**. 🎉
This issue now tracks the work of implementing the proposal.
— rsc for the proposal review group
