### ISSUE TITLE
Reopen #15656: encoding/base64: wrongly decodes bad base64 as valid

### ISSUE THREAD

**Issue by zamicol** [golang/go#60090]
The previous issue is currently frozen due to age:

https://github.com/golang/go/issues/15656

I'll comment on that if it is unfrozen (So this issue I'm opening right now can be deleted), but more details on why this is significant:

I believe RFC 4648 is perhaps misleading here.  The problem is not related to padding as the padded string `hOk=` and `hOl=` have the same encoding issue as unpadded strings.  Neither string when decoded throws an error in Go.  

See this issue for why this problem is significant: https://github.com/Cyphrme/Coze/issues/18

**Comment by ianlancetaylor** [comment]
We believe that issue #15656 was fixed a long time ago.  We aren't going to reopen it.  Please explain here what the problem is, ideally with a test case that misbehaves.  Thanks.
