### ISSUE TITLE
x/pkgsite: package removal request for github.com/fuyu-lang/fuyu

### ISSUE THREAD

**Issue by adamchristiansen** [golang/go#60098]
### What is the path of the package that you would like to have removed?

 

[github.com/fuyu-lang/fuyu](https://github.com/fuyu-lang/fuyu)
 
### Are you the owner of this package?

Yes, I own this package. See the repository at [github.com/fuyu-lang/fuyu](https://github.com/fuyu-lang/fuyu) where the [most recent commit](https://github.com/fuyu-lang/fuyu/commit/9b99130e4f9c1bec45b6a1a45724c7c21e5bf5e5) is authored by me.
 
### What is the reason that you could not retract this package instead?

I have retracted all versions of this package. I would like to have the module removed from pkg.go.dev because the project has moved to a different organization ([github.com/fuyulang/fuyu](https://github.com/fuyulang/fuyu)). I don't want confusion between the new and old documentation since the names differ by only a hyphen `-`.

**Comment by jamalc** [comment]
The retraction you published only retracted tagged versions. This returns your module to an unversioned state.
```
retract (
	v0.0.0 // Project relocated.
	v0.0.1 // Contains retractions only.
	v0.0.2 // Contains retractions only.
)
```

To wipe out all versions, include psuedoversions with v0.0.0-0 as part of a range. For example:

```
retract [v0.0.0-0, v0.0.3]  // assuming v0.0.3 contains this retraction.
```

See the [retract directive](https://go.dev/ref/mod#go-mod-file-retract) for more information. Additionally, you may want to [deprecate your module](https://go.dev/ref/mod#go-mod-file-module-deprecation) and add a deprecation message that points users to the new module.

**Comment by adamchristiansen** [comment]
Thank you for this information, @jamalc. I have made both these suggested changes and verified that the deprecation message shows when I try to add the module with `go get`. If that is all, please proceed with the removal.

**Comment by findleyr** [comment]
@jamalc this looks correct to me: https://github.com/fuyu-lang/fuyu/blob/v0.0.3/go.mod

And yet the module is still available on pkgsite. Do you have an idea of how long this process should take?

**Comment by jamalc** [comment]
The job that cleans modules from the db runs once per week. I manually ran the cleanup process on this module to ensure it worked as expected.
