### ISSUE TITLE
x/tools/gopls: fmt.Sprintf format % is missing verb at end of string

### ISSUE THREAD

**Issue by wanqin88** [golang/go#60103]
### gopls version

Build info
----------
golang.org/x/tools/gopls v0.11.0
    golang.org/x/tools/gopls@v0.11.0 h1:/nvKHdTtePQmrv9XN3gIUN9MOdUrKzO/dcqgbG6x8EY=
    github.com/BurntSushi/toml@v1.2.1 h1:9F2/+DoOYIOksmaJFPw1tGFy1eDnIJXg+UHjuD8lTak=
    github.com/google/go-cmp@v0.5.9 h1:O2Tfq5qg4qc4AmwVlvv0oLiVAGB7enBSJ2x2DqQFi38=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/exp@v0.0.0-20221031165847-c99f073a8326 h1:QfTh0HpN6hlw6D3vu8DAwC8pBIwikq0AI1evdm+FksE=
    golang.org/x/exp/typeparams@v0.0.0-20221031165847-c99f073a8326 h1:fl8k2zg28yA23264d82M4dp+YlJ3ngDcpuB1bewkQi4=
    golang.org/x/mod@v0.7.0 h1:LapD9S96VoQRhi/GrNTqeBJFrUjs5UHCAtTlgwA5oZA=
    golang.org/x/sync@v0.1.0 h1:wsuoTGHzEhffawBOhz5CYhcrV4IdKZbEyZjBMuTp12o=
    golang.org/x/sys@v0.2.0 h1:ljd4t30dBnAvMZaQCevtY0xLLD0A+bRZXbgLMLU1F/A=
    golang.org/x/text@v0.4.0 h1:BrVqGRd7+k1DiOgtnFvAkoQEWQvBc25ouMJM6429SFg=
    golang.org/x/tools@v0.3.1-0.20221213193459-ca17b2c27ca8 h1:7/HkGkN/2ktghBCSRRgp31wAww4syfsW52tj7yirjWk=
    golang.org/x/vuln@v0.0.0-20221109205719-3af8368ee4fe h1:qptQiQwEpETwDiz85LKtChqif9xhVkAm8Nhxs0xnTww=
    honnef.co/go/tools@v0.3.3 h1:oDx7VAwstgpYpb3wv0oxiZlxY+foCpRAwY7Vk6XpAgA=
    mvdan.cc/gofumpt@v0.4.0 h1:JVf4NN1mIpHogBj7ABpgOyZc65/UUOkKQFkoURsz4MM=
    mvdan.cc/xurls/v2@v2.4.0 h1:tzxjVAj+wSBmDcF6zBB7/myTy3gX9xvi8Tyr28AuQgc=
go: go1.20.1

### What did you do?

	var a, b []int
	msg := fmt.Sprintf("size argv:%d ret:%d success < 50%", len(a), len(b))
	fmt.Println(msg)

### What did you see instead?

![image](https://github.com/golang/go/assets/8621512/89f305cb-a609-4720-904b-18b72a0611a6)

### Editor and settings
vscode 1.78.1 (user setup)

  "gopls": {
    // Add parameter placeholders when completing a function.
    "ui.completion.usePlaceholders":true,
    "ui.diagnostic.staticcheck": true,
    "ui.diagnostic.analyses": {
      "shadow":true,
      "useany":true,
      "unusedwrite":true,
      "unusedparams":true,
      "unusedvariable":true
    },
    "formatting.gofumpt": true,
    "ui.semanticTokens": true
  },

**Comment by mustan989** [comment]
Try to replace `"size argv:%d ret:%d success < 50%"` with `"size argv:%d ret:%d success < 50%%"`. Since you put % sign it is expected to get format argument after or escape it with double %
