### ISSUE TITLE
x/tools/goyacc: why token must be a char? 

### ISSUE THREAD

**Issue by lysShub** [golang/go#60101]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

go install golang.org/x/tools/cmd/goyacc@v0.9.1 

![image](https://github.com/golang/go/assets/55095917/7171b02b-d367-4929-9a31-e0c7852f2852)

goyacc -l -o parser.go parser.y

### What did you expect to see?
no error, token should be spupport a string 

### What did you see instead?
character token too long: "!=": parser.y:25

**Comment by cherrymui** [comment]
We don't really use our issue tracker for questions. You will get better answers, if you ask on a forum rather than on the issue tracker. See https://golang.org/wiki/Questions. Thanks.
