### ISSUE TITLE
runtime/pprof: test timed out in `StartCPUProfile`

### ISSUE THREAD

**Issue by bcmills** [golang/go#60108]
```
#!watchflakes
post <- pkg == "runtime/pprof" && log ~ `Test killed with quit` && log ~ `^runtime/pprof\.StartCPUProfile`
```

https://build.golang.org/log/e7671b5aac25301376187c735141b1a0dd33bbe0 (from https://github.com/golang/go/issues/57995#issuecomment-1535416660):
```
SIGQUIT: quit
PC=0x7ff81b7a62be m=1 sigcode=0
…
goroutine 2 [running]:
	goroutine running on other thread; stack unavailable
created by runtime.init.6 in goroutine 1
	/tmp/buildlet/go/src/runtime/proc.go:310 +0x1a
…
goroutine 55 [running]:
	goroutine running on other thread; stack unavailable
created by testing.(*T).Run in goroutine 1
	/tmp/buildlet/go/src/testing/testing.go:1648 +0x836
…
goroutine 57 [syscall]:
runtime.notetsleepg(0x10bce3a?, 0xc000050ec8?)
	/tmp/buildlet/go/src/runtime/lock_sema.go:294 +0x31 fp=0xc000050e90 sp=0xc000050e48 pc=0x105c711
runtime.(*profBuf).read(0xc000138090, 0x0)
	/tmp/buildlet/go/src/runtime/profbuf.go:500 +0xa8 fp=0xc000050ee8 sp=0xc000050e90 pc=0x10978a8
runtime/pprof.readProfile()
	/tmp/buildlet/go/src/runtime/cpuprof.go:230 +0x4b fp=0xc000050f48 sp=0xc000050ee8 pc=0x10b6f4b
runtime/pprof.profileWriter({0x12eea60, 0xc000414000})
	/tmp/buildlet/go/src/runtime/pprof/pprof.go:810 +0x65 fp=0xc000050fb0 sp=0xc000050f48 pc=0x121d105
runtime/pprof.StartCPUProfile.func2()
	/tmp/buildlet/go/src/runtime/pprof/pprof.go:794 +0x45 fp=0xc000050fe0 sp=0xc000050fb0 pc=0x121d005
runtime.goexit()
	/tmp/buildlet/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000050fe8 sp=0xc000050fe0 pc=0x10bd041
created by runtime/pprof.StartCPUProfile in goroutine 55
	/tmp/buildlet/go/src/runtime/pprof/pprof.go:794 +0x1af
…
*** Test killed with quit: ran too long (4m0s).
FAIL	runtime/pprof	240.037s
```

**Comment by mknyszek** [comment]
Related to #59995?

**Comment by bcmills** [comment]
I wonder if this is related to #18717. Do we know if `cgo_yield` is non-nil on `darwin` when the race detector is enabled?

**Comment by bcmills** [comment]
The answer as of https://go.dev/cl/451055 seems to be no.

So, that's my theory: the TSAN runtime is deferring signals as described in #18717, but the workaround added to the `runtime` package for #18717 is no longer in effect because `runtime/race/race.go` is no longer used on `darwin`, which causes `runtime/cgo` not to be linked in, which causes `_cgo_yield` to be nil.

**Comment by bcmills** [comment]
One possible fix, in the spirit of https://go.dev/cl/451055, would be to have `runtime/race` provide a libc-but-not-cgo definition of `_cgo_yield`.

**Comment by bcmills** [comment]
@cherrymui notes:
> I think C TSAN intercepts signals but the Go race detector doesn't (when it bundles TSAN it doesn't include the signal interceptor code). So for non-cgo build it shouldn't matter?

But I wonder: since we're linking against `libc` on macOS, do we use our bundled TSAN implementation, or the one provided by the system C toolchain? 🤔

**Comment by cherrymui** [comment]
I think we use the bundled TSAN implementation from the race syso files. I don't think the libc we use contains TSAN.

**Comment by mknyszek** [comment]
As of the resolution of #61768, I think this is also fixed. gopherbot will reopen it if not true, but we haven't seen any issues in a couple weeks.

**Comment by mknyszek** [comment]
Closing in favor of https://github.com/golang/go/issues/67023.
