### ISSUE TITLE
x/pkgsite: stdlib path package missing from top results

### ISSUE THREAD

**Issue by dsnet** [golang/go#60119]
Search for the package "path" on the pkgsite:
https://pkg.go.dev/search?limit=25&m=package&q=path

The top 5 results are:
* path/filepath
* golang.org/x/sys/execabs
* github.com/Masterminds/glide/path
* github.com/ipfs/go-path
* gopkg.in/src-d/go-git.v4/utils/merkletrie/noder

What happened to the `path` package itself?
https://pkg.go.dev/path

**Comment by seankhliao** [comment]
dup of #41369 ?

**Comment by dsnet** [comment]
Yes, duplicate, thank you.
