### ISSUE TITLE
compile, reflect: Type wrappers get methods from fields embedded in underlying type

### ISSUE THREAD

**Issue by abhinav** [golang/go#60135]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.4 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/abg/Library/Caches/go-build"
GOENV="/Users/abg/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/abg/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/abg/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.20.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.20.4/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.4"
GCCGO="gccgo"
AR="ar"
CC="cc"
CXX="c++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/12/gsh1s5sj4ds4mgmdyg4b5h400000gn/T/go-build34061159=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

The [language spec](https://go.dev/ref/spec#Type_definitions) states that a new type wrapper like the following gets an empty method set.

```go
type NewMutex Mutex
```

This appears to be true, except for methods in Mutex that were received by embedding.

A thorough demonstration is at https://go.dev/play/p/VOHGCORGmJw, but in short:

```go
package main

type mutex struct{}

func (*mutex) Lock() {}

type Mutex struct{ mutex }

// Should work and does:
func init() {
	var m Mutex
	m.Lock()
}

type NewMutex Mutex

// Should not work, but it does:
func init() {
	var m NewMutex
	m.Lock()
}

func main() {}
```

### What did you expect to see?

The second example should not compile.
`Lock` should not be part of `NewMutex`'s method set.

### What did you see instead?

`Lock` is part of `NewMutex`'s method set.
It can be accessed directly, as in the example above, and via reflection.

https://go.dev/play/p/VOHGCORGmJw has a more thorough demonstration.

**Comment by cherrymui** [comment]
The compiler and the reflect package work as intended. The spec says

> A defined type may have [methods](https://go.dev/ref/spec#Method_declarations) associated with it. It does not inherit any methods bound to the given type, but the [method set](https://go.dev/ref/spec#Method_sets) of an interface type or of elements of a composite type remains unchanged

specifically, "the method set ... of elements of a composite type remains unchanged". It doesn't say a new type definition "gets an empty method set".

Thanks.

**Comment by abhinav** [comment]
@cherrymui are we talking about the same thing here? I'm referring to the new type.

From the spec:

```go
// NewMutex has the same composition as Mutex but its method set is empty.
type NewMutex Mutex
```

"[NewMutex's] method set is empty". That's true if Mutex is defined as:

```go
type Mutex struct{}
func (Mutex) Lock()
```

But not if it's defined as:

```go
type inner struct{}
func (inner) Lock()

type Mutex struct{ inner }
```

Whether Mutex embeds a field or not invalidates the following example:

```go
// NewMutex has the same composition as Mutex but its method set is empty.
type NewMutex Mutex
```

**Comment by cherrymui** [comment]
In that example, `Mutex` is defined as

```
// A Mutex is a data type with two methods, Lock and Unlock.
type Mutex struct         { /* Mutex fields */ }
func (m *Mutex) Lock()    { /* Lock implementation */ }
func (m *Mutex) Unlock()  { /* Unlock implementation */ }
```

The claim of "method set is empty" is specifically to the definition in the example above. It does not apply to other cases. Please read the example as a whole. Thanks.

**Comment by abhinav** [comment]
Apologies, I may be misunderstanding the spec, so I would appreciate some clarification here.
Even outside of the NewMutex example, the spec says a defined type "does not inherit any methods bound to the given type".
This may be wrong, but I'm reading that as saying that in all cases, `type NewMutex Mutex` should not have any methods on it.
And my Ctrl-F-ing through the spec for the string "embedded" so far hasn't suggested that a field embedded in `Mutex` changes the statement above.

As a messier example of this: https://go.dev/play/p/954dQE5nncn
The embedded `mutex` implements `Lock() int`.
The real `Mutex` implements `Lock() string`.
The wrapper `NewMutex` gets `Lock() int`.

**Comment by ianlancetaylor** [comment]
The behavior you are seeing is how the language is intended to work.

`type T1 T2` does not give `T1` any methods that are specifically defined for `T2`.  It does give `T1` any methods that are embedded in `T2`.

For further discussion please use a forum rather than the issue tracker.  See https://go.dev/wiki/Questions.  Thanks.
