### ISSUE TITLE
cmd/compile: build failures with `signal: killed` on ppc64x

### ISSUE THREAD

**Issue by bcmills** [golang/go#60151]
```
#!watchflakes
post <- goarch ~ `ppc64` && (`compile(.exe)?: signal: killed` || log ~ `compile(.exe)?: signal: killed`)
```

(Filed from https://github.com/golang/go/issues/57995#issuecomment-1545660220.)

**Comment by mknyszek** [comment]
This seems related to #60148, it just happens to be the compiler that OOMs. I'll leave this in our queue for now, but CC @pmur.

**Comment by pmur** [comment]
The spur of power10/ppc64 failures in early may is almost certainly an OOM for the reason I noted in #60148.

**Comment by pmur** [comment]
I think we can ignore these for now. I've been fine tuning the LUCI builders. They should all be 4 cores / 10G RAM now. The old buildlets are limited to 8G RAM and seem to be near their limits.

**Comment by pmur** [comment]
This flake stills falls under my previous comment. The failure can be ignored.
