### ISSUE TITLE
all: unrecognized test failures on `linux/loong64`

### ISSUE THREAD

**Issue by bcmills** [golang/go#60168]
```
#!watchflakes
default <- goarch == "loong64"
```

(CC @golang/loong64)

**Comment by XiaodongLoong** [comment]
We will have a look. Thanks!

**Comment by xen0n** [comment]
The failures seemed spurious and can't be reproduced right now: https://go.dev/cl/481937 and https://go.dev/cl/492620 for example both passed on the loong64 builder.

If no new instances of this flake occur in the next few days, I think we can close this issue then.

**Comment by abner-chenc** [comment]
> Now this seems very likely caused by faulty memory, @abner-chenc should be working to replace the physical host underneath the `loong64` builder. He may have more to share later.

I have replaced the physical machines and updated the latest stable firmware (previously these physical machines were beta versions of the firmware).

**Comment by bcmills** [comment]
It looks like the failures being posted here are not specific to `loong64`. I'm going to close this issue and add a `date` constraint so that new failures get new issues.
