### ISSUE TITLE
x/pkgsite: package removal request for https://pkg.go.dev/github.com/square/gonomalo

### ISSUE THREAD

**Issue by squareJake** [golang/go#60169]
### What is the path of the package that you would like to have removed?

 

https://pkg.go.dev/github.com/square/gonomalo
 
 
### Are you the owner of this package?

Yes
 
### What is the reason that you could not retract this package instead?

The package was added to the repository before I realized it should have a different name. The repo no longer exists.

**Comment by hyangah** [comment]
Fixed.
