### ISSUE TITLE
x/vuln: release version v0.2.0

### ISSUE THREAD

**Issue by julieqiu** [golang/go#60165]
This issue tracks progress toward releasing x/vuln@v0.2.0

- [ ] complete tasks on Github milestone: https://github.com/golang/go/milestone/308
- [ ] verify tests are passing: https://build.golang.org/?repo=golang.org%2fx%2fvuln
- [ ] verify integration tests are passing: https://fusion2.corp.google.com/ci/kokoro/prod:golang%2Fvuln%2Fgovulncheck%2Fgcp_ubuntu%2Fintegration/activity/8bc895c0-5963-43c1-809f-6baad9aa193f/summary
- [ ] write release notes
- [ ] update https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck
- [ ] add documentation for JSON output
- [ ] update any other documentation
- [ ] tag x/vuln@v0.2.0

**Comment by hansgylling** [comment]
@julieqiu, @bkessler-go. Shouldn't milestone vuln/v0.2.0 have been closed in June when govulncheck v0.2.0 was released?

**Comment by bkessler-go** [comment]
Yes it should have. I closed it out now. Thanks for letting us know
