### ISSUE TITLE
proposal: more idempotence for go mod {download, tidy, vendor}

### ISSUE THREAD

**Issue by mcandre** [golang/go#60177]
I regularly run the commands `go mod {download, tidy, vendor}` when adjusting my dependencies. However, one of these commands often fails, whining that the other has not run yet. Quite frustrating, in fact.

I could study the commands in further detail to learn, and memorize the expected order to run them in. But as a workaround, I usually just repeat all three in a cycle a few times, until they calm down.

One solution would be to move more of these subcommands into a CLI flag of the other subcommand. Then, the flag could trigger the desired action as a side effect after it automatically satisfies its own precondition.

**Comment by seankhliao** [comment]
We've explicitly decided to move to `-mod=readonly` to have less side effects. I don't think we're going to do this.
