### ISSUE TITLE
[feature request]: hope go fmt tools can limit the length of a single line of go code 

### ISSUE THREAD

**Issue by fansehep** [golang/go#60172]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you expect to see?

Now go fmt tools doesn't limit the length of a single line of go code. Some code line are so long. I hope the tools can limit the length. like 80 or 90 or provide a gofmt config file.

**Comment by ALTree** [comment]
#11915 is about comments but I think https://github.com/golang/go/issues/11915#issuecomment-125792373 is still relevant. Making gofmt configurable is not on the table because would default its purpose, and forcing an hardcoded column would be too restrictive.
