### ISSUE TITLE
why I can't run in Google VPS? 

### ISSUE THREAD

**Issue by abusabiha** [golang/go#60184]
I have installed Go but can't run in VPS. Solution please.
![43](https://github.com/golang/go/assets/86252592/d4c7b9bf-00a6-490a-8e6f-5fd3ae6a7bfe)

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
