### ISSUE TITLE
net/mail: ParseAddress doesn't support using a domain-literal in the domain of an email address

### ISSUE THREAD

**Issue by robplee** [golang/go#60206]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes, confirmed against 1.20 and "Go dev branch" using The Go Playground

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/robertlee/Library/Caches/go-build"
GOENV="/Users/robertlee/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/robertlee/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/robertlee/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.19.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.19.5/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.19.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/robertlee/go/src/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/g9/kjpfy6dn3f3gr60k0j5f5j9r0000gn/T/go-build2238133857=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I used mail.ParseAddress to try to parse an email address containing an IP address.

```
package main

import (
	"fmt"
	"net/mail"
)

func main() {
	_, err := mail.ParseAddress("me@[192.168.0.1]")
	if err != nil {
		fmt.Println("mail is complaining incorrectly")
	}
}
```

Go playground: https://go.dev/play/p/rZW6QPqVZC6

### What did you expect to see?
mail.ParseAddress shouldn't have returned an error and the program should not have printed any output

This format, `me@[192.168.0.1]`, is how email addresses are supposed to be formatted according to [Section 3.4.1 of RFC 5322](https://datatracker.ietf.org/doc/html/rfc5322#section-3.4.1), so this email address should have been parsed correctly without any error being returned.

### What did you see instead?
mail.Parse address _did_ return an error so the message "mail is complaining incorrectly" was printed

**Comment by heschi** [comment]
cc @bradfitz

**Comment by seankhliao** [comment]
It's a valid (according to RFC) formatting of an address, but it would also be valid to format it as `me@192.168.0.1`.

The RFC also notes

> Note: A liberal syntax for the domain portion of addr-spec is
      given here.  However, the domain portion contains addressing
      information specified by and used in other protocols (e.g.,
      [[RFC1034](https://datatracker.ietf.org/doc/html/rfc1034)], [[RFC1035](https://datatracker.ietf.org/doc/html/rfc1035)], [[RFC1123](https://datatracker.ietf.org/doc/html/rfc1123)], [[RFC5321](https://datatracker.ietf.org/doc/html/rfc5321)]).  It is therefore
      incumbent upon implementations to conform to the syntax of
      addresses for the context in which they are used.

Which sounds like we'd have to decide on address formats to support.

**Comment by nunogoncalves03** [comment]
I have reproduced the issue and investigated both the RFC specification and the code itself. Upon inspecting the code, I found a relevant TODO:

https://github.com/golang/go/blob/ef84d62cfc358ff62c60da9ceec754e7a389b5d5/src/net/mail/message.go#L550-L562

Based on this, it seems like there's a need to implement handling for domain literals in the email parsing logic. I'll be working on a fix.

**Comment by puellanivis** [comment]
> Which sounds like we'd have to decide on address formats to support.

Good news, without and address literal tag, the address is to be an IPv4 address. And the only address literal tag registered by the IANA is IPv6, and adding that support is pretty minimal with the work already done.

https://www.iana.org/assignments/address-literal-tags/address-literal-tags.xhtml
