### ISSUE TITLE
Golang on Microsoft VS IDE

### ISSUE THREAD

**Issue by AGoh2019** [golang/go#60200]
I wonder if it is possible for Google to ask Microsoft to built a Golang extension into VS IDE?

Other languages which can be included are - Kotlin, Rust, Clojure, Prolog, and for some other folks Haskell and Scala.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
