### ISSUE TITLE
x/build: new luci choose tryjobs is not accessible even tho I have permissions for the gerrit one

### ISSUE THREAD

**Issue by Jorropo** [golang/go#60219]
In gerrit trying to use the new `CHOOSE TRYJOBS` tab for luci:
![Capture d’écran du 2023-05-16 10-19-56](https://github.com/golang/go/assets/24391983/7d01ac82-9af4-47b7-b6a7-110274e07c6b)

I get this error in the console:

> ```
> Failed to schedule builds: Error: "user:jorropo.pgm@gmail.com" does not have permission "buildbucket.builds.add" in bucket "golang/try"
> ```

Even tho I was able to do it through the voting system: https://go-review.googlesource.com/c/go/+/495115/comments/e46ce1cd_fd4e7fe9

**Comment by heschi** [comment]
Thanks. We should probably grant that permission to everyone with may-start-trybots, but we haven't fully understood the implications yet.

cc @golang/release

**Comment by heschi** [comment]
This should've been fixed in http://go.dev/cl/518895.
