### ISSUE TITLE
cmd/5c: handle 64bit operations internally

### ISSUE THREAD

**Issue by davecheney** [golang/go#6021]
<pre>What steps will reproduce the problem?

The virt_asm.c helpers tend to show up in the hot path of the runtime, the garbage
collector, the netpoll code, etc. 

5c currently defers to runtime functions to handle any operations involving 64 bit
quantities. 5g can handle them internally, but the code in cgen64.c is not easily
converted to run on 5c.

While not a trivial job, is it possible to include a scaffold for handling 64bit
operations inside 5c, the operations could be added as needed once the scaffold is in
place.</pre>

**Comment by rsc** [comment]
5c is gone!
