### ISSUE TITLE
x/tools/cmd/stringer to accept string input

### ISSUE THREAD

**Issue by suntong** [golang/go#60228]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.3 linux/amd64

</pre>

### What did you want?

> Given the name of a (signed or unsigned) integer type T that has constants
defined, stringer will create a new self-contained Go source file implementing
> 
> 	func (t T) String() string
> 
> That method will translate the value of a Pill constant to the string representation
 of the respective constant name, so that the call fmt.Print(painkiller.Aspirin) will
 print the string "Aspirin".

I need to pass the _string_ representation from command line and get the corresponding _integer_ value of type T.   
EG, giving an input string "Aspirin", I need a method to get the corresponding value of `Aspirin` (`1`).

It is not possible at the moment right? Hope it'll be some day.
And meanwhile, while waiting, what shall I do? Can I still make use of the automatic created methods / code, or I should be looking for something entirely different? 

Thanks

**Comment by suntong** [comment]
The challenge is when using the `-linecomment=true`. IE the value are different than the name. 

See https://go.dev/play/p/t8n91_GF0Od

Given a string "`Or`", I need to get its value of "`|`". thx.

**Comment by randall77** [comment]
Dup of #23535.
