### ISSUE TITLE
affected/package: go/exec

### ISSUE THREAD

**Issue by Robertzzel** [golang/go#60239]
### What version of Go are you using (`go version`)?

go1.19.9 linux/amd64

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>

amd64
Linux Mint 20.3 Cinnamon

</pre></details>

### What did you do?

I need to combine an compress 2 files (audio and video). I am using the next code and script to do so:

```
func (avp *AudioVideoPair) CombineAndCompress(compressFactor int, output string, buffer *bytes.Buffer) error {
    cmd := exec.Command("./CombineAndCompress", avp.Video, avp.Audio, fmt.Sprint(compressFactor), output)
    cmd.Stdout = buffer
    err := cmd.Run()
    if err != nil {
        return err
    }
    return nil
}
```

```
#!/bin/sh

ffmpeg -y -i "$1" -i "$2" -map 0:v -map 1:a -c:v libx264 -tune zerolatency -preset ultrafast -shortest -movflags frag_keyframe -pass 1 -f mp4 -crf "$3" "$4"
```

The "output" parameter will be "pipe:1".
Using this method I get a memory leak from Start method of cmd. (I do reset my buffer after each call)

I tried the following:

    manually using Start() and Wait();
    using cmd.Output() and returning the resulting byte slice.
    saving the result in a separate file and then reading it.

**Comment by ianlancetaylor** [comment]
> Using this method I get a memory leak from Start method of cmd.

What precisely does this mean?  How are you determining that there is a memory leak?

Can you show us a complete standalone example that demonstrates the problem?

**Comment by Robertzzel** [comment]
I apologize for not being clear. My memory keeps filling when I call "CombineAndCompress" multiple times.
```
for {
	select {
	case filesPair := <-filesChannel:
		err := CompressAndSendFiles(producer, filesPair, &combineOutput)
		if err != nil {
			return err
		}

		combineOutput.Reset()
	case <-ctx.Done():
		return nil
	}
} 
```
I know its from the Start method of exec.Command because of 2 reasons:
1. When I stop calling the method, the memory leak stops.
2.  I get that from "pprof"
