### ISSUE TITLE
proposal: golang.org/x/crypto/ssh, configure a proxy to etablish ssh connexion

### ISSUE THREAD

**Issue by Sachavent** [golang/go#60270]
Hello,

I need to etablish a ssh connexion over a HTTP proxy, and I don't find anyway to do it with the current package

In pseudo code, it might be something like this : 
`
import (
    "net"
    "golang.org/x/crypto/ssh"
)

proxyConn, _: = net.Dial("tcp", proxyURL)
conn, _: = proxyConn.Dial("tcp", serverURL)
c, chans, reqs, err: = ssh.NewClientConn(conn, serverURL, & sshConfig)
client: = ssh.NewClient(c, chans, reqs)
`

Steps:
- 1. Connect to the http proxy
- 2. Using the "proxy connection" to etablish the SSH connection

Maybe we can achieve that with the currect package but I don't find anyway to do it

Thanks a lot for your help

**Comment by seankhliao** [comment]
this is what NewClientConn is for.
establishing an http proxy connection is out of scope for x/crypto/ssh

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
