### ISSUE TITLE
x/tools/gopls: code action for implementing interface

### ISSUE THREAD

**Issue by marcelbeumer** [golang/go#60290]
It would be great if `gopls` could implement an interface for the struct under cursor, like https://github.com/josharian/impl does, but then updating existing implementation as well, erroring if it can't because of incompatibilities. Because of LSP,`gopls` could also be accurate about using existing imports/aliases of packages. 

GoLand can already do this, would be great to bring it to other editors this way too!

**Comment by suzmue** [comment]
impl is available from VS Code through the`>Go: Generate Interface Stubs` command: https://github.com/golang/vscode-go/wiki/features#generate-interface-implementation.

gopls also has support for generating interface implementations as code actions (see #37537).

Please let us know if there are ways that these features could be improved for your use case!

**Comment by marcelbeumer** [comment]
Hi @suzmue, I knew about vscode & impl (not using vscode though), but I'd like gopls to do this out of the box. Also impl doesn't analyze existing code / existing methods, it just generates stubs from scratch.  

I struggle to find how to do use the code actions of gpls you mentioned through https://github.com/golang/go/issues/37537. I'm using neovim but I'm able to trigger code action requests through code: where should my cursor be and can I just ask gopls for available actions or should I explicitly trigger a specific action?

Please note the gopls documentation doesn't mention this special code action either.

Thanks in advance!

**Comment by marcelbeumer** [comment]
@suzmue I may overlook something, but checking the source of gopls, I don't see any implement interface command of sorts.

**Comment by adonovan** [comment]
It's admittedly tricky to find. First you must create a statement that will not compile because the concrete type does not satisfy the interface. For example: var r io.Reader = new(myReader). Gopls will report a diagnostic at the right-hand side of the assignment, and associated with that diagnostic is a code action to fix the type error by defining the missing methods.

**Comment by marcelbeumer** [comment]
@adonovan, yes that works! Hehe, it's actually a nice way to avoid the need for UI to pick which interface to implement :D Thanks!
