### ISSUE TITLE
x/pkgsite: tag removal request flashbots/mev-boost-relay v1.*

### ISSUE THREAD

**Issue by metachris** [golang/go#60300]
Links: 
- https://github.com/flashbots/mev-boost-relay
- https://github.com/flashbots/mev-boost-relay/tags
- https://pkg.go.dev/github.com/flashbots/mev-boost-relay?tab=versions

Tags `v1*` were created accidentally and have since been removed. Could you please reindex the tags for this repository?

The latest actual tag is v0.23, and all tags v1.0.0-alpha1 and after were removed, but are still indexed in pkg.go.dev, which prevents the actual tags of showing up as latest, or at all: https://pkg.go.dev/github.com/flashbots/mev-boost-relay?tab=versions

**Comment by seankhliao** [comment]
We cannot remove individual tags, only entire module prefixes.
Please use `retract`, you can publish a retraction version that also retracts itself.
