### ISSUE TITLE
database/sql: sql.RawBytes is not compatible with contexts

### ISSUE THREAD

**Issue by bradfitz** [golang/go#60304]
[`sql.RawBytes` says:
](https://pkg.go.dev/database/sql#RawBytes)

> RawBytes is a byte slice that holds a reference to memory owned by the database itself. After a Scan into a RawBytes, the slice is only valid until the next call to Next, Scan, or Close.

That was true when `RawBytes` was added (in the first Go release, Go 1(.0)), but Go 1.8 added `context.Context` support to the `database/sql` package.

Since that time, `RawBytes` has been unsafe to use with any `BeginTx`/`QueryContext` with a context that might be done, as internally the `database/sql` package starts a goroutine (`awaitDone`) waiting for the context(s) to be done and then calls `Close` on the `database/sql/driver.Conn`, concurrently with the caller working with RawBytes.

Consider this series of events:

```go
      ctx, cancel := context.WithCancel(context.Background())
      rows, ... := QueryRowContext(ctx)
      for rows.Next() {
           var raw sql.RawBytes
           rows.Scan(&raw)
           cancel()   // imagine this a timeout or cancellation
           json.Unmarshal(raw, ....)  // working with memory that's not ours
     }
```

Options:

* document that `RawBytes` can't be used with a context that might be Done
* make `convertAssignRows` clone the driver's `[]byte` memory when a vulnerable context is in use
* change the goroutine that does the concurrent driver.Close to instead set an atomic bool that the context is done, and do the Close+error on the next call to `Rows.Next`/`Rows.Close`/`Rows.Err`/etc.... something that the user did explicitly, rather than doing something concurrently with the user code working with the `RawBytes`.

### What version of Go are you using (`go version`)?

Go 1.20, but happens starting with Go 1.8 probably (not verified)

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

macOS, Linux, etc. Not platform-specific.

**Comment by rsc** [comment]
Looks like this is a duplicate of #53970, although we didn't realize the severity of that one when it came in.

**Comment by rsc** [comment]
Of the three options, the atomic bool and delayed driver close seems like the right fix. /cc @kardianos

**Comment by rsc** [comment]
@gopherbot please backport Go 1.20 and Go 1.19

**Comment by renthraysk** [comment]
The MySQL driver solution was to use switch buffers if an error/cancellation happened.

https://github.com/go-sql-driver/mysql/pull/943

**Comment by heschi** [comment]
@rsc can you explain why this is a release blocker for 1.21? #53970 was filed nearly a year ago, and the problem has supposedly existed since 1.8. This seems like a bug worth fixing, but do we really need to hold 1.21 for it?

**Comment by rsc** [comment]
Even though it's old, it causes data corruption in code that looks perfectly innocent (and arguably _is_ innocent). 
I believe @bradfitz is working on a fix. If at all possible we really should put the fix in the release and backport it.

**Comment by heschi** [comment]
@bradfitz seems like the CL above fixed this? Should we close?

**Comment by ianlancetaylor** [comment]
Is there anything else left to do for this issue?

**Comment by rsc** [comment]
All set.
