### ISSUE TITLE
affected/package: json.json.Marshal(interface{&resp}) has panic, main content:ptrEncoder.encode: e.ptrLevel--,runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by StarCsu** [golang/go#60327]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.19.5 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
i don't try it;

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="/usr/local/gcc-5.4.0/bin/gcc"
CXX="/usr/local/gcc-5.4.0/bin/g++"
CGO_ENABLED="1"
GOMOD="/go/src/packPlayer/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build27185314=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

main code:
<pre>
// MarshalPPTP 序列化pptp传输数据，后续下发给前端使用
func MarshalPPTP(td PackTransferContent) []byte {
	if len(td.Topics) != len(td.TopicMetas) {
		logrus.Infof("MarshalPPTP len(td.Topics) != len(td.TopicMetas)")
		return nil
	}
	cmdDetailData, err := json.Marshal(td.CMDDetail)
	if err != nil {
		logrus.Infof("MarshalPPTP json.Marshal err:%v", err)
		//当前返回错误时，兼容该情况的数据返回
		cmdDetailData = make([]byte, 0)
	}
}
</pre>

<pre>
func writeError(wsClient websocket.WSClient, code int32, msg string) {
	logrus.Errorf("write err,code:%d,msg:%s", code, msg)
	data := pptp.MarshalPPTP(
		pptp.PackTransferContent{
			CMDCode: constant.ErrorCMDCode,
			CMDDetail: &pack_play.CommonCMDRsp{
				Code: code,
				Msg:  msg},
		})
	err := wsClient.WriteBinaryMsg(data)
	if err != nil {
		logrus.Errorf("write binary msg:%s", err)
	}
}
</pre>

<pre>
// PackTransferContent,PackTransferContent CMDDetail type:
type PackTransferContent struct {
	// have detail、topic_data、close three cmd
	CMDCode uint8
	// cmd resp content
	CMDDetail interface{}
}
</pre>

### What did you expect to see?
i think this is not appear panic ,because i  passed the cmddetail instance variable；
i think it should exec success;

### What did you see instead?
I currently suspect that GC garbage collected the data pointed to by cmddetail， but I am unable to replicate it in the testing environment，and i find  other panic from gc;
panic info:
<pre>
runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/encoding/json/encode.go:327 (0x5112cd)
 (*encodeState).marshal.func1: panic(r)
/usr/local/go/src/runtime/panic.go:884 (0x4385b1)
 gopanic: done = runOpenDeferFrame(gp, d)
/usr/local/go/src/runtime/panic.go:260 (0x44e575)
 panicmem: panic(memoryError)
/usr/local/go/src/runtime/signal_unix.go:835 (0x44e545)
 sigpanic: panicmem()
/usr/local/go/src/encoding/json/encode.go:945 (0x515a7e)
 ptrEncoder.encode: e.ptrLevel--
/usr/local/go/src/encoding/json/encode.go:359 (0x511657)
 (*encodeState).reflectValue: valueEncoder(v)(e, v, opts)
/usr/local/go/src/encoding/json/encode.go:331 (0x5111d9)
 (*encodeState).marshal: e.reflectValue(reflect.ValueOf(v), opts)
/usr/local/go/src/encoding/json/encode.go:160 (0x510864)
 Marshal: err := e.marshal(v, encOpts{escapeHTML: true})
xxx/pkg/util/pptp/pack_play_transfer_protocol.go:55 (0x9cec50)
xxx/pkg/controller/pack_play_ws.go:105 (0xa30bf4)
xxx/pkg/controller/pack_play_ws.go:34 (0xa302a4)
</pre>

gc panic:
<pre>
runtime: marked free object in span 0x7feea298ede8, elemsize=24 freeindex=0 (bad use of unsafe.Pointer? try -d=checkptr)
0xc000000000 free  marked   zombie

fatal error: found pointer to free object

goroutine 3 [running]:
runtime.throw({0xb8d6f9?, 0xc000000018?})
 /usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0xc00009b5e8 sp=0xc00009b5b8 pc=0x438b9d
runtime.(*mspan).reportZombies(0x7feea298ede8)
 /usr/local/go/src/runtime/mgcsweep.go:788 +0x2e5 fp=0xc00009b668 sp=0xc00009b5e8 pc=0x4291e5
runtime.(*sweepLocked).sweep(0x12e7740?, 0x0)
 /usr/local/go/src/runtime/mgcsweep.go:606 +0x335 fp=0xc00009b740 sp=0xc00009b668 pc=0x428655
runtime.sweepone()
 /usr/local/go/src/runtime/mgcsweep.go:369 +0xf4 fp=0xc00009b790 sp=0xc00009b740 pc=0x428054
runtime.bgsweep(0x0?)
 /usr/local/go/src/runtime/mgcsweep.go:281 +0x105 fp=0xc00009b7c8 sp=0xc00009b790 pc=0x427e05
runtime.gcenable.func1()
 /usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc00009b7e0 sp=0xc00009b7c8 pc=0x41ca26
runtime.goexit()
 /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00009b7e8 sp=0xc00009b7e0 pc=0x4691a1
created by runtime.gcenable
 /usr/local/go/src/runtime/mgc.go:178 +0x6b
</pre>

**Comment by seankhliao** [comment]
given that gc panic, seems more likely that you're using unsafe or C incorrectly

**Comment by StarCsu** [comment]
> given that gc panic, seems more likely that you're using unsafe or C incorrectly

I did use cgo and unsafe ptr，but unsafe ptr or c code will affect JSON Does Marshall have an impact ？after all, the Marshall object does not involve unsafe ptr operations
