### ISSUE TITLE
https://pkg.go.dev/gitlab.com/fruitygo/pnutmux/v2

### ISSUE THREAD

**Issue by fruitygo** [golang/go#60323]
### What is the URL of the page with the issue?
 https://pkg.go.dev/gitlab.com/fruitygo/pnutmux/v2
 
 
### What is your user agent?
 mozilla firefox

 
 
 
### What did you do?
 I published a package by error. I tagged a major version but I deleted the tag to a non-major version. Now, my major version package is still on pkg.go.dev.

 
 
 
### What did you expect to see?
 Delete the package please.
 
 
### What did you see instead?
Nothing.

**Comment by seankhliao** [comment]
Sorry we cannot remove versions for you, you'll have to use retract.
