### ISSUE TITLE
hexadecimal mantissa requires a 'p' exponent

### ISSUE THREAD

**Issue by kstenerud** [golang/go#60326]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.20

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

https://go.dev/play/p/DbPDqLY5mc2

### What did you do?

```golang
package main

import "fmt"

func main() {
	fmt.Printf("%v", 1)
	fmt.Printf("%v", 0x1)
	fmt.Printf("%v", 1.1)
	fmt.Printf("%v", 0x1.1)
}
```

### What did you expect to see?

I expected it to compile.

### What did you see instead?

```
./prog.go:9:24: hexadecimal mantissa requires a 'p' exponent
```

It's jarring and weird that the pattern of (number, 0Xnumber) suddenly breaks down when it comes to floating point literals. I'm having trouble thinking of any reason why insisting on an exponent of `p+0` is useful (especially since it's not required for decimal float literals).

**Comment by robpike** [comment]
This format was introduced in C, I believe, as a way to guarantee exact values for constants, which is not in general possible when converting base 10 constants to floating point. In C, the exponent is mandatory, and there is no reason for Go to differ.

It's a special-purpose format that might as well be rigid.

In short, the 'p' is mandatory and it's not up to Go to change that.

**Comment by kstenerud** [comment]
:+1:
