### ISSUE TITLE
fmt: error in the documentation for fmt.Formatter?

### ISSUE THREAD

**Issue by myitcv** [golang/go#60358]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.21-40bdc56180 Tue May 23 13:22:25 2023 +0000 linux/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOENV="/home/myitcv/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/myitcv/gostuff/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/myitcv/dev/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/dev/go/pkg/tool/linux_arm64"
GOVCS=""
GOVERSION="go1.20.4"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build697360160=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```
$ go doc fmt Formatter
```

### What did you expect to see?

Documentation that is consistent with the intended use of `fmt.Formatter`

### What did you see instead?

```
package fmt // import "fmt"

type Formatter interface {
        Format(f State, verb rune)
}
    Formatter is implemented by any value that has a Format method. The
    implementation controls how State and rune are interpreted, and may call
    Sprint(f) or Fprint(f) etc. to generate its output.
```

It's unclear to me how a call to `Sprint(f)` can possibly work with with a `fmt.State` value.

A call to `Fprint(f)` yes, but not `Sprint(f)`.

Am I missing something obvious, or is this a mistake in the docs?

**Comment by contrast-jproberts** [comment]
Could "`may call Sprint(f)`" mean "`may call Sprint or Sprintf`" instead of "`may call Sprint with f`"? I can't remember where I've seen the syntax before but I associate `ab(c)` with matching `ab` and `abc`.

Even if that match is the intent of the comment, I agree that it's confusing in this context where `Sprint` and `Fprint` are functions and `f` is a defined parameter.

**Comment by robpike** [comment]
Yes, it's an error. It should read "Sprint() or Fprint(f)".

**Comment by dolmen** [comment]
So is a call to `Sprintf` dangerous? Is it because `Sprintf` is not reentrant?

If this was allowed before by the documentation, but not anymore, this not just a bug fix but a breaking change.

**Comment by myitcv** [comment]
> So is a call to `Sprintf` dangerous? Is it because `Sprintf` is not reentrant?

@dolmen - what does the call `Sprint(f)` actually do to your understanding?

**Comment by ianlancetaylor** [comment]
@dolmen To be clear, calling `fmt.Sprintf` is fine.  The comment was confusing.
