### ISSUE TITLE
cmd/go: `go env GOTOOLCHAIN` prints superfluous trailing newline

### ISSUE THREAD

**Issue by zephyr** [golang/go#60361]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.21-e4e8f9b8ff 2023-05-23 04:38:43 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
No, because `GOTOOLCHAIN` is new in go1.21.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='amd64'
GOBIN='/home/dennis/bin/binaries-golang'
GOCACHE='/home/dennis/.cache/go-build'
GOENV='/home/dennis/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/dennis/.local/share/gopath/pkg/mod'
GONOPROXY='bitbucket.org/zephyr'
GONOSUMDB='bitbucket.org/zephyr'
GOOS='linux'
GOPATH='/home/dennis/.local/share/gopath'
GOPRIVATE='bitbucket.org/zephyr'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/opt/golang/master'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLDIR='/opt/golang/master/pkg/tool/linux_amd64'
GOVCS='*:git'
GOVERSION='devel go1.21-e4e8f9b8ff 2023-05-23 04:38:43 +0000'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3637338098=/tmp/go-build -gno-record-gcc-switches'
GOROOT/bin/go version: go version devel go1.21-e4e8f9b8ff 2023-05-23 04:38:43 +0000 linux/amd64
GOROOT/bin/go tool compile -V: compile version devel go1.21-e4e8f9b8ff 2023-05-23 04:38:43 +0000
uname -sr: Linux 5.10.0-22-amd64
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
/lib/x86_64-linux-gnu/libc.so.6: GNU C Library (Debian GLIBC 2.31-13+deb11u6) stable release version 2.31.
</pre></details>

### What did you do?

After reading #57001:
```
$ go env -w GOTOOLCHAIN=local
$ go env GOTOOLCHAIN
$ go env --json GOTOOLCHAIN
```

### What did you expect to see?

```
local
{
	"GOTOOLCHAIN": "local"
}
```

### What did you see instead?

```
local

{
	"GOTOOLCHAIN": "local\n"
}
```

**Comment by ianlancetaylor** [comment]
CC @bcmills @rsc
