### ISSUE TITLE
cmd/compile: compiler built with PGO crashes occasionally on ppc64{le}

### ISSUE THREAD

**Issue by prattmic** [golang/go#60368]
```
#!watchflakes
default <- goarch ~ `ppc64` && date != "" && date > "2023-05-22"
```

https://go.dev/cl/495596 added a `default.pgo` profile for `cmd/compile`, enabling a PGO build of the compiler (as long as `-pgo=none` is not set explicitly).

This caused a variety of crashes in the compiler on ppc64{le} builders:

[2023-05-18T16:55:07-88f89d8/linux-ppc64le-power9osu](https://build.golang.org/log/e555ebedadffd416d94823969c8c1a34329802c2)
[2023-05-18T13:41:27-33a601b/aix-ppc64](https://build.golang.org/log/7db526c84a30501f190c81a219a7bebabab3e61f)
[2023-05-18T12:52:14-7b0835d/aix-ppc64](https://build.golang.org/log/163bbdc75cb1c0c4c77523c4d22fc11e3440b8cc)
[2023-05-18T10:23:17-75add1c/aix-ppc64](https://build.golang.org/log/79a9fa4404b38cb36673ac260e41f915ff86a905)
[2023-05-18T09:16:07-774f602/linux-ppc64-sid-power10](https://build.golang.org/log/bec1c3b8f9e65978e427d3fae6fb00d35c2a028d)
[2023-05-18T09:16:07-774f602/linux-ppc64le-buildlet](https://build.golang.org/log/2a53364380c79e635de0fd4fd1b70708daf155d9)
[2023-05-18T09:15:25-27906bb/aix-ppc64](https://build.golang.org/log/de44da3c501b391f8f3efb26c861fd372b41103e)
[2023-05-18T09:15:25-27906bb/linux-ppc64-sid-power10](https://build.golang.org/log/126aed9b0f3a4774981f20117b1269941a9091d8)
[2023-05-18T01:40:37-6ed8474/linux-ppc64-sid-buildlet](https://build.golang.org/log/94ed70099290e4844515918d15b26a9770e77bc1)
[2023-05-18T01:40:37-6ed8474/linux-ppc64-sid-power10](https://build.golang.org/log/c51e3a356db068656781e652ad22544683e9021e)
[2023-05-18T00:35:53-956d31e/linux-ppc64le-buildlet](https://build.golang.org/log/000137ddd145138ca99fa2cece56fc534a146c3d)
[2023-05-17T22:11:31-0b86a04/linux-ppc64le-buildlet](https://build.golang.org/log/6e18a8c6eff8a4e9ca7d4b6126e80151afcadb8f)
[2023-05-17T21:53:11-c426c87/linux-ppc64-sid-buildlet](https://build.golang.org/log/994fc2be3a517bb112777b3283007d125864c637)
[2023-05-17T21:53:11-c426c87/linux-ppc64le-power10osu](https://build.golang.org/log/f2b6c925ba5a0657cceb795e9c176d580f1d04af)
[2023-05-17T21:44:30-2693ade/linux-ppc64-sid-power10](https://build.golang.org/log/83a4bf815826ffe62d99aedcb3771902eb718b98)

That CL also caused #60263. Since it caused several issues, the CL was reverted in https://go.dev/cl/496185. #60263 has since been fixed.

Given these failures are all on ppc64{le}, @dr2chase and I suspect that they are due to a bad ppc64-specific optimization (SSA rule, e.g.) that is tickled by the additional inlining caused by PGO.

I have had some success reproducing these crashes. Running all.bash in a loop on three `linux-ppc64-sid-power10` builders concurrently with `GOGC=5` usually gets me a failure in <30 minutes. Not stellar, but I think workable.

We should then be able to bisect down to a bad function with GOSSAHASH applied in [inlineCostOK](https://cs.opensource.google/go/go/+/master:src/cmd/compile/internal/inline/inl.go;l=1000) to enable/disable PGO-based inlining. (Also set `-d=pgodevirtualize=0` to disable PGO-based devirtualization, which was submitted in https://go.dev/cl/492436, after the bad CL above was reverted).

Given that there is a path forward to debugging ppc64, and we'd like more soak time on the primary ports, I intend to resubmit https://go.dev/cl/495596, which will make ppc64 flaky until this issue is resolved. (GOARCH=ppc64{le} could also temporarily change the default of -pgo from auto to none if necessary). 

cc @golang/ppc64 @dr2chase @aclements @cherrymui

**Comment by laboger** [comment]
We have done some experimenting with this. I found that if we build the default.pgo file natively instead of using the one built on amd64 we are not able to get the problem to occur. When using the default pgo file built on amd64 more inlining happens within cmd/compile/internal/ssagen.(*state).stmt and according to the stacktraces that seems like where many of the problems occur.

I was going to attempt to force more aggressive inlining and see if that forces the problem.

**Comment by dr2chase** [comment]
@laboger 
PROGRESS!

I ran a binary search on the flake, and isolated it to a single PGO inline.

you can compare two versions of ssa.html with (full recipe):

First checkout experiment CL, build a known-good (no PGO-inlining) compiler, and save it:
```
cd whatever/go/src
git fetch https://go.googlesource.com/go refs/changes/57/497557/1 && git checkout -b change-497557 FETCH_HEAD
GOCOMPILEDEBUG=gossahash=10101010101010110101001011 ./make.bash
go install golang.org/x/tools/cmd/toolstash@latest
toolstash save
```

Then you can build a bad compiler, or a good compiler, with output to a nearby directory (../bad or ../good):
```
GOSSADIR=`pwd`/../bad  GOSSAFUNC='cmd/compile/internal/ssa.(*expandState).rewriteSelect' GOCOMPILEDEBUG=gossahash=v1100101001011 toolstash go install cmd/compile

GOSSADIR=`pwd`/../good  GOSSAFUNC='cmd/compile/internal/ssa.(*expandState).rewriteSelect' GOCOMPILEDEBUG=gossahash=10101010101010110101001011 toolstash go install cmd/compile
```

Note that `gossahash=10101010101010110101001011` matches nothing, but is quieter than `n` which logs a lot about what it isn't doing.  When you build the bad compiler with the command line above, it should print:
```
# cmd/compile/internal/ssa
cmd/compile/internal/ssa/expand_calls.go:550:22 [bisect-match 0xa6214988bb18594b]
gossahash triggered cmd/compile/internal/ssa/expand_calls.go:550:22 000110000101100101001011
dumped SSA to ../bad/cmd/compile/internal/ssa.(*expandState).rewriteSelect.html
```

I have not had a chance to dig into this yet, it seems likely that you might be able to make faster progress than me, unless something obvious leaps out at me.

**Comment by dr2chase** [comment]
@mknyszek suggest turning off async preemption, and so far we are almost an hour in with no failure.

**Comment by dr2chase** [comment]
It's at 100 minutes, still running, I will leave it running.

**Comment by dr2chase** [comment]
6 hours, no failures.  Looks like there's an instruction sequence in that code that should not be preempted.

**Comment by laboger** [comment]
I can get it to fail pretty consistently a few times while running index0.go this way: 
```
cd cmd/internal/testdir
GOMAXPROCS=4 go test -test.run=Test/index0.go -test.count=100
...

FAIL: Test (0.04s)
    --- FAIL: Test/index0.go (0.71s)
        testdir_test.go:132: exit status 1
            # command-line-arguments
            panic: runtime error: index out of range [8484704] with length 4028
            
            goroutine 472 [running]:
            cmd/internal/src.(*PosTable).Pos(...)
            	/home/boger/golang/base/go/src/cmd/internal/src/xpos.go:153
            cmd/internal/obj.(*Link).InnermostPos(...)
            	/home/boger/golang/base/go/src/cmd/internal/obj/inl.go:124
            cmd/internal/obj.(*Link).OutermostPos(0x10?, {0x56800?, 0xc0?})
            	/home/boger/golang/base/go/src/cmd/internal/obj/inl.go:105 +0x140
            cmd/compile/internal/base.FmtPos({0x11?, 0x0?})
            	/home/boger/golang/base/go/src/cmd/compile/internal/base/print.go:66 +0x50
            cmd/compile/internal/base.FatalfAt({0x9ad2e0?, 0xc0?}, {0xc0009ad2b8, 0x17}, {0xc0010c5260, 0x2, 0x2})
            	/home/boger/golang/base/go/src/cmd/compile/internal/base/print.go:218 +0xa8
            cmd/compile/internal/base.Fatalf(...)
            	/home/boger/golang/base/go/src/cmd/compile/internal/base/print.go:199
            cmd/compile/internal/ssagen.(*ssafn).Fatalf(0x665ad4?, {0x6?, 0x7f01?}, {0x96cbde, 0x11}, {0xc00116f5b0, 0x1, 0xc000817701?})
            	/home/boger/golang/base/go/src/cmd/compile/internal/ssagen/ssa.go:7986 +0x1a0
            cmd/compile/internal/ssagen.(*state).Fatalf(0xc000c1eb00?, {0x96cbde?, 0x104cb48?}, {0xc00116f5b0?, 0x42604?, 0x0?})
            	/home/boger/golang/base/go/src/cmd/compile/internal/ssagen/ssa.go:932 +0xb8
            cmd/compile/internal/ssagen.(*state).stmt(0xc000c1eb00, {0xacf3a8, 0xc000be1c98?})
            	/home/boger/golang/base/go/src/cmd/compile/internal/ssagen/ssa.go:2002 +0x2998
            cmd/compile/internal/ssagen.(*state).stmtList(...)
            	/home/boger/golang/base/go/src/cmd/compile/internal/ssagen/ssa.go:1418
            cmd/compile/internal/ssagen.buildssa(0xc002ee8840, 0x1)
            	/home/boger/golang/base/go/src/cmd/compile/internal/ssagen/ssa.go:548 +0x24d0
            cmd/compile/internal/ssagen.Compile(0xc002ee8840, 0x0?)
            	/home/boger/golang/base/go/src/cmd/compile/internal/ssagen/pgen.go:187 +0x48
            cmd/compile/internal/gc.compileFunctions.func5.1(0x0?)
            	/home/boger/golang/base/go/src/cmd/compile/internal/gc/compile.go:184 +0x4c
            cmd/compile/internal/gc.compileFunctions.func3.1()
            	/home/boger/golang/base/go/src/cmd/compile/internal/gc/compile.go:166 +0x48
            created by cmd/compile/internal/gc.compileFunctions.func3 in goroutine 10
            	/home/boger/golang/base/go/src/cmd/compile/internal/gc/compile.go:165 +0x20c
            
FAIL
exit status 1
```
It only fails if I set GOMAXPROCS=4, which is the number of processors available on the OSU builders.
I also suspected preemption because of the intermittent nature of the failure and the fact that some of the registers have to be bad some of the time, but this also fails if I turn off async preemption.
My other suspicion is inlining, and in particular in this case there is some recursion in the stmt, stmtList functions (since they appear in stacks in so many of the failures) along with being inlined. I don't know how to just force more aggressive inlining, I was thinking it was the -l option but I don't see many additional inlined functions when I set this. Maybe there is another way, or PGO just does more inlining than normally and that hasn't been tested very well on Power. I did try setting some //go:noinline directives before some suspicious functions inlined by stmt or stmtList but that caused the failures to appear in different places.
Because of the random nature of the failures, my next theory is data corruption and in a way where it doesn't matter very often, probably on the stack. That's as far as I got.

**Comment by dr2chase** [comment]
For better reproducibility in the future, use -trimpath with gossahash:
```
GOCOMPILEDEBUG=gossahash=v100010110000011001010011 GOARCH=ppc64le GOOS=linux go build -trimpath -o ./compile.ppc64le cmd/compile
# cmd/compile/internal/ssa
cmd/compile/internal/ssa/expand_calls.go:550:22 [bisect-match 0xe94438dd7b8b0653]
gossahash triggered cmd/compile/internal/ssa/expand_calls.go:550:22 100010110000011001010011
```
I'll try to find some way to make this the default for gossahash; this was explicitly NOT chosen for the other flags.

**Comment by prattmic** [comment]
We've realized that the gossahash is using the full absolute path in the hash input, so it probably only works on @dr2chase's machine.

I wrote https://go.dev/cl/499217 to hard-code the bad position check. Enable with `-gcflags=all=-d=ppc64bad=1` to get a bad binary.

**Comment by mknyszek** [comment]
I'm setting release blocker on this issue only to indicate that we should at least disable PGO on ppc64 before the RC, if we can't figure out the issue and/or solve it before then.

I think it would be worthwhile doing this ASAP, just because we're not explicitly relying on the builders to gather additional data anymore.

**Comment by aclements** [comment]
Neither 4406e8ef nor d59926ec include the fix commit, so those flakes are okay.

**Comment by cherrymui** [comment]
The new failure is unrelated.

**Comment by cherrymui** [comment]
Removed from the "Teat Flakes" project so watchflakes will not look at this. It's been long enough so I think we're confident that the original issue is fixed.

**Comment by cherrymui** [comment]
Bummer. Sorry about that. Thanks for the fix.
