### ISSUE TITLE
cmd/compile: invalidly inferred type for interface that doesn't use type parameter

### ISSUE THREAD

**Issue by griesemer** [golang/go#60377]
In the [following code](https://go.dev/play/p/Skc4IEzymQ1):
```Go
type T[P any] interface {
	m()
}

func g[P any](T[P]) {}

func _() {
	var x T[int]
	g(x)         // here we infer P == int, but in fact any type of P would be ok
	g[string](x) // here we set P == string
}
```
we infer the type `int` for `P` of `g`. But in fact any type would make this code work. Type inference should not succeed in this case.

**Comment by griesemer** [comment]
Consider [this case](https://go.dev/play/p/FgN4BHMc2LX):
```Go
type T1[P any] interface {
	m()
}

type T2[P any] interface {
	m()
}

func g[P any](T1[P]) {}

func _() {
	var x T2[int]
	g(x)         // here we infer P == int, but in fact any type of P would be ok
	g[string](x) // here we set P == string
}
```
Now we get an error for `g(x)` but `g[string](x)` is ok. That seems inconsistent. We should not be able to infer a type for `P` in the first case.

**Comment by jimmyfrasche** [comment]
I see what you are saying. The interfaces-as-constraints are identical to each other and `interface { m() }` so `P` does not matter for the constraint.

However, it seems like the parameterization of the interface-as-type should still be part of its identity.

**Comment by jimmyfrasche** [comment]
I expect it to behave like this, since the interface(s) aren't used as constraints and are just ordinary types:
```go
type T[P any] struct{}

func g[P any](T[P]) {}

func _() {
	var x T[int]
	g(x)         // here we infer P == int
	g[string](x) // here we fail to set P == string as P = int
}
```
https://go.dev/play/p/0Wj38UCOijw

**Comment by griesemer** [comment]
@jimmyfrasche But the rules for interface assignment are quite different from non-interface assignment. But here is a [counter-example](https://go.dev/play/p/OQXSiXzpKBw):
```Go
type T[P any] interface{ m() }

func g[P any](func(T[P])) {}

func _() {
	var f func(T[int])
	g(f)
	g[int](f)
	g[string](f) // ERROR cannot use f (variable of type func(T[int])) as func(T[string]) value in argument to g[string]
}
```
Because the interface is a component type, now it must match exactly.

**Comment by jimmyfrasche** [comment]
Ah, I was so fixated on the type inference I wasn't thinking about assignability. `g[string](x)` makes total sense.

I still do not see why that implies that `int` should not be inferred, though. Even if other choices are valid, it seems reasonable to go with what's provided.

**Comment by griesemer** [comment]
I believe type inference should only infer a type if it is the only one possible, if a valid type argument exists in the first place (ignoring the fact that in many cases `any` is also a valid type argument).

This may mean that in some cases (like this one) we cannot infer a type argument. That's ok.

**Comment by jimmyfrasche** [comment]
I agree that type inference should not invent a type but I disagree that it should discard the provided type. I don't think this would matter much given how niche the edge case is, though.

Would `g(T[int](x))` also fail? This case is identical but it feels more wrong written like this.

**Comment by griesemer** [comment]
`g(T[int](x))` is the same as `g(x)` if `x` is of type `T[int]`. So `g(T[string](nil))` currently works but would fail if we consider this issue a bug. Consider `g[int](T[string](nil))` which works either way.

**Comment by griesemer** [comment]
cc: @mdempsky @findleyr for input, especially considering also #8082.

**Comment by griesemer** [comment]
> We know that a type parameter can only have one instantiation at a time. So the solution is unique.

A type parameter can have only one instantiation at a time but that doesn't mean the solution to inference is unique: in the original example in this issue type inference infers `int` but in fact any type would solve the equation. So the solution is not unique at all.

**Comment by findleyr** [comment]
I think the framing provided by @griesemer and @atdiar is useful: if the solution is not unique, inference should fail. Otherwise, we run the risk of inferring a different type in the future (and that's exactly why we need the special case currently).

I'll note that there are other cases where there *is* one unique solution, and inference fails because of the current implementation:

```
type S[P any] interface{}

func F[P any](S[P], P) {}

func _() {
	var s S[int]
	F(s, "")
}
```

**Comment by griesemer** [comment]
@findleyr 's example is very convincing. Fix forthcoming.

**Comment by findleyr** [comment]
Here's an example where inference will continue to succeed, but infer a different type:

```
type S[P any] interface{}

func F[P any](S[P], P) P { var x P; return x }

func main() {
	var s S[float64]
	y := F(s, 1)
	_ = y
}
```

IMO this is an example of the current algorithm inferring the "wrong" type. The type of y is inferred to be float64, but should be int (and will be after this issue is fixed).

**Comment by griesemer** [comment]
@atdiar Your 2nd example will work with the fix.

**Comment by hajimehoshi** [comment]
This should be too late, and I am sorry if this was already discussed, but wouldn't it be possible to forbide unused type parameters by the Go compiler? In other words, couldn't Go compiler forbid the following code?

```go
type T[P any] interface {
	m()
}
```

I realized that unused type parameters tend to cause counterintuitive implicit conversions (https://go.dev/play/p/VLb031yF1z6). Also, unused parameters are unused then these should be useless. (If we really want to have a unused type parameter, we can add a member like `[0]T` somewhere).

What do you think?

**Comment by hajimehoshi** [comment]
OK so my question is when phatom types are useful.

**Comment by hajimehoshi** [comment]
> Edit: now that I think of it, since you only want to disable it for interface types, I think it will depend on how the question of interface identity is solved.

Good point. Probably what I want to solve is counterintuitve assignment to a interface type. For non-interface types, such a counterintuitive assignment should not happen as far as I understand. So, forbidding an unused parameter for an interface type might be enough, beside the consistency.
