### ISSUE TITLE
go: module gomsgque appears multiple times in workspace

### ISSUE THREAD

**Issue by aotto1968** [golang/go#60396]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
only with current release

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/dev/shm/dev1usr/Main/x86_64-suse-linux-gnu/debug/.gocache"
GOENV="/home/dev1usr/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/dev1usr/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/dev1usr/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/dev1usr/ext/x86_64-suse-linux-gnu/go1.20.3"
GOSUMDB="sum.golang.org"
GOTMPDIR="/dev/shm/dev1usr/Main/x86_64-suse-linux-gnu/debug/.gotemp"
GOTOOLDIR="/home/dev1usr/ext/x86_64-suse-linux-gnu/go1.20.3/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/dev/shm/dev1usr/Main/x86_64-suse-linux-gnu/debug/.gotemp/go-build760766763=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I want to compile my application that is called `gomsgque` and this should also be the toplevel modulename
I have multiple _sub-modules_ like `mkkernel` `mqmsgque` and `lcconfig`

now the 3 submodules are located in different directories

~~~~
dir1/gomsgque/mkkernel
dir1/gomsgque/mqmsgque
dir2/gomsgque/lcconfig
~~~~

the `lcconfig` also include `mkkernel` and the `go.work` file looks like
~~~~
go 1.20

use (
    DIR1/gomsgque
    DIR2/gomsgque
)
~~~~

but the build __fails__ with 

~~~~
theConfig/gomsgque> make
  make:  /home/dev1usr/ext/x86_64-suse-linux-gnu/go/bin/go build  -v -buildmode=default  gomsgque/mqmsgque
go: module gomsgque appears multiple times in workspace
make: *** [Makefile:674: lcconfig.a] Fehler 1
~~~~

at first all _submodules_ were in the __same__ directory and this was fine , but now I split the directories and this error arrive.

→ Q:  what can I do to still use the same TOPLEVEL package `gomsgque` with multiple submodules in different `gomsgque` directories?

### work-around

I can skip the `go.work` setup and __softlink__ the missing `mkkenrel` _submodule_ into the working-directory:

~~~~
drwxr-xr-x  4 dev1usr users   4096 24. Mai 10:14 .
drwxr-xr-x 14 dev1usr users   4096 24. Mai 09:19 ..
-rw-r--r--  1 dev1usr users   2040 24. Apr 10:17 .golcconfig.index
-rw-r--r--  1 dev1usr users  75219 19. Mai 10:57 .golcconfig.meta
-rw-r--r--  1 dev1usr users     25 15. Apr 09:43 go.mod
-rw-r--r--  1 dev1usr users    292 24. Mai 08:33 .index.mk
-rw-r--r--  1 dev1usr users   1751 18. Apr 20:19 .label.go
-rw-r--r--  1 dev1usr users      0 12. Apr 16:10 .labelignore
-rw-r--r--  1 dev1usr users    363 12. Apr 11:16 .label_inc.tcl
drwxr-xr-x  2 dev1usr users    136 22. Apr 22:02 lcconfig
-rw-r--r--  1 dev1usr users  15515 22. Mai 11:58 LcConfigC.go
-rw-r--r--  1 dev1usr users    854  8. Mai 19:59 LcImport.go
-rw-r--r--  1 dev1usr users  19794 22. Mai 11:58 LcSettingC.go
-rw-r--r--  1 dev1usr users   6929 22. Mai 11:58 LibLcConfig.go
-rw-r--r--  1 dev1usr users   3082  8. Mai 19:59 LibLcConfig_go.c
-rw-r--r--  1 dev1usr users    879  8. Mai 19:59 LibLcConfig_go.h
-rw-r--r--  1 dev1usr users    235 16. Mai 23:01 .make_clean.bash
-rw-r--r--  1 dev1usr users   3152 24. Mai 10:14 Makefile.am
-rw-r--r--  1 dev1usr users  20764 24. Mai 10:14 Makefile.in
-rwxr--r--  1 dev1usr users    533 24. Mai 08:32 .makefile_index.bash
-rwxr--r--  1 dev1usr users    611  8. Mai 19:59 .makeLink.bash
lrwxrwxrwx  1 dev1usr users     31 24. Mai 10:14 mkkernel -> ../../theLink/gomsgque/mkkernel
-rw-r--r--  1 dev1usr users 331713 25. Apr 20:32 tags
-rw-r--r--  1 dev1usr users  23834  2. Mai 14:46 .vimrc
~~~~

**Comment by seankhliao** [comment]
The modules listed in your go.work must be unique, if mkkernel, mqmsgque, and lcconfig are modules, they should be listed in go.work, and only one instance of gomsgque should be in there.

I believe this is working as intended, workspaces resolve to a single consistent set of module versions, having the same module listed twice won't work.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
