### ISSUE TITLE
cmd/go: go build either looks for go.mod in the directory specified by -C or doesn't depending on where -C appears relative to -gcflags

### ISSUE THREAD

**Issue by aarzilli** [golang/go#60392]
```
$ go version
go version devel go1.21-40bdc56180 Tue May 23 13:22:25 2023 +0000 linux/amd64
```

but also reproduces with 1.20. Reproducer:

```
$ mkdir example
$ cd example
$ go mod init example
$ cat - > main.go
package main
func main() { println("hello world") }
^D
$ cd ..
$ go build -C example -gcflags=""
(succeeds)
$ go build -gcflags="" -C example
go: go.mod file not found in current directory or any parent directory; see 'go help modules'
```

Originally reported at https://github.com/go-delve/delve/pull/3380#issuecomment-1560400825

**Comment by aarzilli** [comment]
cc @bcmills

**Comment by seankhliao** [comment]
both -C and the build flags are processed as they are set, doesn't seem like an easy fix

https://github.com/golang/go/blob/7ad92e95b56019083824492fbec5bb07926d8ebd/src/cmd/go/internal/base/flag.go#L65
https://github.com/golang/go/blob/7ad92e95b56019083824492fbec5bb07926d8ebd/src/cmd/go/internal/work/build.go#L313
https://github.com/golang/go/blob/7ad92e95b56019083824492fbec5bb07926d8ebd/src/cmd/go/internal/load/flag.go#L38

**Comment by bcmills** [comment]
The documentation for `go build` currently states:
> If used, [the `-C`] flag must be the first one in the command line.

That restriction was added in https://go.dev/cl/500915 for #57001.

Closing as probably fixed, but please let us know if you can still reproduce similar problems using Go 1.21 or higher.
