### ISSUE TITLE
cmd/go: `go test -race -coverpkg=all` AST-parser is broken 

### ISSUE THREAD

**Issue by xaionaro** [golang/go#60403]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/xaionaro/.cache/go-build"
GOENV="/home/xaionaro/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/xaionaro/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/xaionaro/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/xaionaro/.gimme/versions/go1.20.4.linux.amd64"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/xaionaro/.gimme/versions/go1.20.4.linux.amd64/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/xaionaro/go/src/github.com/linuxboot/contest/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build143176400=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Just run:
```sh
cd /tmp
git clone https://github.com/leodido/go-urn
cd go-urn
go test -race -coverpkg=all ./
```

### What did you expect to see?

```
ok  	github.com/leodido/go-urn	0.049s	coverage: 7.8% of statements in all
```

### What did you see instead?

```
../../../../pkg/mod/github.com/leodido/go-urn@v1.2.4/urn.go:86:2: syntax error: unexpected var after top level declaration
```

**Comment by xaionaro** [comment]
The problem is not reproducible in Go1.18.

**Comment by seankhliao** [comment]
fixed on tip.
