### ISSUE TITLE
cmd/go: GOEXPERIMENT=gocacheprog [freeze exception]

### ISSUE THREAD

**Issue by rsc** [golang/go#60419]
Requesting a freeze exception for [CL 486715](https://go-review.googlesource.com/c/go/+/486715) for Brad's GOEXPERIMENT=cacheprog work. It's clean and well isolated and doesn't affect anything unless you explicitly set GOEXPERIMENT=cacheprog. We want to make it available in Go 1.21 as an experiment in order to get feedback for promoting it to a real feature. Thanks.

**Comment by dmitshur** [comment]
That CL has some comments that need to be resolved. It also says "Updates #59719"—is there more that needs to happen for that proposal or is that CL fine to submit now and leave further changes for 1.22?

**Comment by bradfitz** [comment]
It's all addressed. I didn't say "Fixes" until it lands without an experiment, hopefully next cycle.

**Comment by bradfitz** [comment]
(but I can also say "Fixes" here and file a new bug later... no preference.)
