### ISSUE TITLE
cmd/go: GOCACHEPROG approval [freeze exception]

### ISSUE THREAD

**Issue by bradfitz** [golang/go#60420]
Hey @golang/release,

I forgot to submit https://go-review.googlesource.com/c/go/+/486715 this morning after getting @bcmills's approval. I was going to spend the evening stress testing it more and then submit. I didn't know about this cycle's new freeze rules now including in-progress changes. 😬

**Comment by dmitshur** [comment]
I'll dedup this into #60419 and copy the rationale there. Thanks.
