### ISSUE TITLE
cmd/go: forward compatibility work [freeze exception]

### ISSUE THREAD

**Issue by rsc** [golang/go#60421]
The work for #57001 is not yet complete. [Pending CLs are here](https://go-review.git.corp.google.com/q/o:rsc+is:open+message:57001), modulo Gerrit's search problems, plus there will be one more important bug fix as well as probably some additional commentary and documentation. The non-doc, non-test CLs (other than bug fixes) will be ready to submit by end of week. This is an important feature for Go 1.21 that unlocks important work planned for Go 1.22. (If it doesn't get into Go 1.21 then the loopvar changes we hope to get into Go 1.22 slip to Go 1.23.)

I apologize profusely for needing the exception.

**Comment by dmitshur** [comment]
CC @golang/release.

**Comment by rsc** [comment]
It took a week longer than I expected to tie up various loose ends that @bcmills and I identified, but I've just submitted the last non-doc CL for #57001 (modulo bug fixes of course). Docs CLs to come in the next few days.
