### ISSUE TITLE
crypto/internal/bigmod: fix panic [freeze exception]

### ISSUE THREAD

**Issue by rolandshoemaker** [golang/go#60422]
[#60411](https://go.dev/issue/60411) was only filed today, as it was blocked by an internal security investigation. The CL (http://go.dev/cl/498035) was sent & reviewed, but just slipped the deadline for the freeze. The change is small, tested, and reviewed, so I don't think it poses a significant risk.

cc @golang/release

**Comment by ianlancetaylor** [comment]
My understanding is that actual bug fixes (and doc changes) are OK at the moment.  Freeze exceptions are required for new features.

(Please correct me if I am wrong.)

**Comment by rolandshoemaker** [comment]
Oh I completely misread the change in the freeze policy, and this makes complete sense 🤦, ignore me!
