### ISSUE TITLE
golink:  support link or relocation unexported method of generics type in golang

### ISSUE THREAD

**Issue by kom0055** [golang/go#60425]
### What did you do?

for example, I have file "pkg/A/internal/A.go" that has code like shown below
```golang
package internal

type AS[T any] struct {
}

func (s *AS[T]) helloLink() string {
    return "hello"
}
```

And I have another one file "pkg/B/B.go"

```golang
package B

import (
    _ "unsafe"

    _ "pkg/A/internel"
)

type BS[T any] struct {
}


//go:linkname pkgHello pkg/A/internel.(*AS[T]).helloLink
func pkgHello[T any](s *BS[T]) string
```

### What did you expect to see?

method `helloLink` of `AS[T]` should be linked

### What did you see instead?

when I try to run this code, it tells that " parameterized function is missing function body"

1. I have set asm.s file in package B
2. It works without generics declaration
3. Ignore import path shown in code, it should be right

**Comment by randall77** [comment]
`//go:linkname` is not supported outside the standard library.
Even if it was, `//go:linkname` is not supported for generic code. There's no reasonable way to make this work given how generics is implemented. ([gory details](https://go.googlesource.com/proposal/+/refs/heads/master/design/generics-implementation-gcshape.md).)
