### ISSUE TITLE
x/build: create LUCI EC2 builders

### ISSUE THREAD

**Issue by cagedmantis** [golang/go#60441]
As part of a migration to a new CI/CD system, there is a need to create images for the machines hosted on the Go EC2 project. This is a list of the builders which are currently hosted on the project. This list will be used to seed which images must be built in order to support all of these builders.

## Builders
 - linux-arm-aws (Container image) - #65241

Note: The Darwin builders have been included in the reverse builder issue #60440

@golang/release

**Comment by dmitshur** [comment]
There's only one builder in this category in the end. I'll close this umbrella issue in favor of #65241.
