### ISSUE TITLE
cmd/go: go list cmd/compile takes 40x longer than go list cmd/...

### ISSUE THREAD

**Issue by findleyr** [golang/go#60455]
As in the title:

```
> time go list cmd/compile
cmd/compile

real	0m8.523s
user	0m8.610s
sys	0m0.068s
```

vs
```
> time go list cmd/...
...output, including cmd/compile

real	0m0.200s
user	0m0.492s
sys	0m0.185s
```

Here is my go version:
```
> go version
go version devel go1.21-e51b5f8384 Thu May 25 10:06:01 2023 -0700 linux/amd64
```

CC @bcmills @matloob @adonovan

**Comment by bcmills** [comment]
This is likely another PGO issue, or another symptom of the same PGO issue. Probably closely related to #60428.
(attn @cherrymui @prattmic)

**Comment by prattmic** [comment]
![image](https://github.com/golang/go/assets/1293187/6b45cb8e-cf9b-435b-b3fa-d246ea13d711)

😬
