### ISSUE TITLE
runtime: find uses of int32 that should be uintptr

### ISSUE THREAD

**Issue by bradfitz** [golang/go#6046]
<pre>In src/pkg/runtime/strings.goc, findnull uses an int32:

int32
runtime·findnull(byte *s)
{
        int32 l;

        if(s == nil)
                return 0;
        for(l=0; s[l]!=0; l++)
                ;
        return l;
}

And that is called by:

String
runtime·gostring(byte *str)
{
        intgo l;
        String s;

        l = runtime·findnull(str);
	s = gostringsize(l);
        runtime·memmove(s.str, str, l);
        return s;
}

Which means:

package main

/*
*/
import &quot;C&quot;
import &quot;unsafe&quot;

func main() {
	println(&quot;pre-make&quot;)
	buf := make([]byte, 1&lt;&lt;31 + 2)
	println(&quot;pre-set&quot;)
	for i := range buf {
		buf[i] = 'a'
	}
	buf[len(buf)-1] = 0
	println(&quot;pre-gostring&quot;)
	println(len(C.GoString((*C.char)(unsafe.Pointer(&amp;buf[0])))))
}

$ go run x.go
pre-make
pre-set
pre-gostring
unexpected fault address 0xc190022000
fatal error: fault
[signal 0xa code=0x2 addr=0xc190022000 pc=0x401b7de]

goroutine 1 [running]:
runtime.throw(0x405e0dc)
	/Users/bradfitz/go/src/pkg/runtime/panic.c:498 +0x69 fp=0x4210e80
runtime.sigpanic()
	/Users/bradfitz/go/src/pkg/runtime/os_darwin.c:446 +0x1ed fp=0x4210e98
runtime.findnull(0xc210022000)
	/Users/bradfitz/go/src/pkg/runtime/string.goc:21 +0x1e fp=0x4210ea8
runtime.gostring(0x4210f00, 0xc210022000)
	/Users/bradfitz/go/src/pkg/runtime/string.goc:66 +0x27 fp=0x4210ee0
main._Cfunc_GoString(0xc210022000, 0xc, 0x80000002)
	command-line-arguments/_obj/_cgo_defun.c:10 +0x31 fp=0x4210ef8
main.main()
	/Users/bradfitz/x.go:19 +0x115 fp=0x4210f48
runtime.main()
	/Users/bradfitz/go/src/pkg/runtime/proc.c:201 +0x113 fp=0x4210fa0
runtime.goexit()
	/Users/bradfitz/go/src/pkg/runtime/proc.c:1333 fp=0x4210fa8
exit status 2</pre>

**Comment by robpike** [comment]
I suspect this is obsolete..

**Comment by bradfitz** [comment]
Yes, I just verified they've been fixed.
