### ISSUE TITLE
x/vuln: define format returned by -json flag

### ISSUE THREAD

**Issue by VirrageS** [golang/go#60496]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.20.4
</pre>

### Feature request

I would like to request a definition of the format that is returned by `-json`. It is listed in https://github.com/golang/go/issues/60165 but just wanted to make it explicit. The idea behind this request is that using `govulncheck -json` could be streamed to other tools to act on the vulnerabilities. It would be especially important to add descriptions to all the fields to know when to use which.

**Comment by mknyszek** [comment]
CC @golang/vulndb

**Comment by ianthehat** [comment]
Does https://pkg.go.dev/golang.org/x/vuln@v0.1.0/internal/govulncheck have all the information you need?
The intent of that package it that it is also easy to copy those files if you are writing a tool that wants to consume the output, as well as documenting that output.

**Comment by VirrageS** [comment]
Oh, I totally missed that. That's definitely sufficient. Maybe some mention of it in the README would be appreciated :)) Thanks!
