### ISSUE TITLE
can not get asm code?

### ISSUE THREAD

**Issue by cuiweixie** [golang/go#60498]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.21-7d6aeafeee Fri May 19 11:17:16 2023 +0800 darwin/arm64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE='on'
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/xiecui/Library/Caches/go-build'
GOENV='/Users/xiecui/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE='weixiecui.net'
GOMODCACHE='/Users/xiecui/code/go/gopath/pkg/mod'
GONOPROXY='kscm.kasikornbank.com,weixiecui.net'
GONOSUMDB='kscm.kasikornbank.com,weixiecui.net'
GOOS='darwin'
GOPATH='/Users/xiecui/code/go/gopath'
GOPRIVATE='kscm.kasikornbank.com,weixiecui.net'
GOPROXY='https://goproxy.cn,direct'
GOROOT='/Users/xiecui/code/go/src/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLDIR='/Users/xiecui/code/go/src/go/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='devel go1.21-7d6aeafeee Fri May 19 11:17:16 2023 +0800'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/xiecui/code/go/go-test/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/j2/s6k2rxl14kn__6tngwr5hdgw0000gn/T/go-build3034602010=/tmp/go-build -gno-record-gcc-switches -fno-common'
GOROOT/bin/go version: go version devel go1.21-7d6aeafeee Fri May 19 11:17:16 2023 +0800 darwin/arm64
GOROOT/bin/go tool compile -V: compile version devel go1.21-7d6aeafeee Fri May 19 11:17:16 2023 +0800
uname -v: Darwin Kernel Version 21.6.0: Mon Dec 19 20:46:01 PST 2022; root:xnu-8020.240.18~2/RELEASE_ARM64_T8101
ProductName:	macOS
ProductVersion:	12.6.3
BuildVersion:	21G419
lldb --version: lldb-1400.0.38.17
Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
</pre></details>

### What did you do?

file: clone.go
```
package clone

// Clone returns a copy of the slice.
// The elements are copied using assignment, so this is a shallow clone.
func Clone[S ~[]E, E any](s S) S {
	// Preserve nil in case it matters.
	if s == nil {
		return nil
	}
	return append(S([]E{}), s...)
}

```

```
go tool compile -S clone.go
```
### What did you expect to see?
asm code of func Clone.

### What did you see instead?

```
go:cuinfo.producer.<unlinkable> SDWARFCUINFO dupok size=0
        0x0000 72 65 67 61 62 69                                regabi
go:cuinfo.packagename.<unlinkable> SDWARFCUINFO dupok size=0
        0x0000 63 6c 6f 6e 65                                   clone

```

**Comment by seankhliao** [comment]
generic functions do not exist until they are instantiated with concrete types
