### ISSUE TITLE
go/types: error diagnostics reported by go/types contain  %!v(MISSING)

### ISSUE THREAD

**Issue by myitcv** [golang/go#60500]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.4 linux/arm64
$ go list -m golang.org/x/tools
golang.org/x/tools v0.9.2-0.20230526183654-5974258e689a
$ go list -m golang.org/x/tools/gopls
golang.org/x/tools/gopls v0.0.0-20230526183654-5974258e689a
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOENV="/home/myitcv/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/myitcv/gostuff/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/myitcv/gos"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_arm64"
GOVCS=""
GOVERSION="go1.20.4"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/myitcv/gostuff/src/github.com/myitcv/playground/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1568132059=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Load the following file with a `gopls`-enabled editor:

```
package main

func main() {
	log("This is a test %v", 5)
}

func log(enabled bool, format string, args ...any) {
	log.Printf(format, args...)
}
```

### What did you expect to see?

The following diagnostics (showing the vim-rendered version):

```
main.go|4 col 6| cannot use "This is a test %v" (untyped string constant) as bool value in argument to log
main.go|4 col 27| cannot use 5 (untyped int constant) as string value in argument to log
main.go|8 col 6| log.Printf undefined (type func(enabled bool, format string, args ...any) has no field or method Printf)
```

### What did you see instead?

```
main.go|4 col 6| cannot use "This is a test %!v(MISSING)" (untyped string constant) as bool value in argument to log
main.go|4 col 27| cannot use 5 (untyped int constant) as string value in argument to log
main.go|8 col 6| log.Printf undefined (type func(enabled bool, format string, args ...any) has no field or method Printf)
```

Note the presence of `%!v(MISSING)` in the first line.

Log files:

* [gopls.log](https://github.com/golang/go/files/11597630/gopls.log)
* [govim.log](https://github.com/golang/go/files/11597631/govim.log)

---

cc @findleyr

**Comment by findleyr** [comment]
Thank you for the report.

This is reproducible with go/types alone (simply copy the example above into `src/go/types/testdata/manual.go`.

We should not be passing user content as format strings, therefore this is a release blocker.

CC @griesemer

**Comment by adonovan** [comment]
Perhaps the printf vet checker should be able to catch problems like this: a variable format string is passed to a printf wrapper, followed by no other arguments. I can't see how that would ever be useful.

**Comment by griesemer** [comment]
We have a type checker local printf test that perhaps can be adjusted.
- gri
