### ISSUE TITLE
x/tools/gopls: can't see assembly implementation of functions w/o body

### ISSUE THREAD

**Issue by inliquid** [golang/go#60531]
#### What did you do?
I'm using VS Code. Until some moment it was possible to see the assembly implementation of a function without body by `Ctrl-Click` or `F12`, etc. I just found that it's not possible anymore.

For instance when I try to see implementation of `atomic.AddInt32` I'm just switching between its signature and a method where it's used.
![изображение](https://github.com/golang/go/assets/6797881/292bd4dc-1469-45a4-8fe2-fd7dcd1cfb29)

#### What did you expect to see?
See the assembly code of a function.

#### What did you see instead?
Switching between function signature and it's only reference in a package.

#### Build info

```
golang.org/x/tools/gopls master
    golang.org/x/tools/gopls@(devel)
    github.com/BurntSushi/toml@v1.2.1 h1:9F2/+DoOYIOksmaJFPw1tGFy1eDnIJXg+UHjuD8lTak=
    github.com/google/go-cmp@v0.5.9 h1:O2Tfq5qg4qc4AmwVlvv0oLiVAGB7enBSJ2x2DqQFi38=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/exp@v0.0.0-20220722155223-a9213eeb770e h1:+WEEuIdZHnUeJJmEUjyYC2gfUMj69yZXw17EnHg/otA=
    golang.org/x/exp/typeparams@v0.0.0-20221212164502-fae10dda9338 h1:2O2DON6y3XMJiQRAS1UWU+54aec2uopH3x7MAiqGW6Y=
    golang.org/x/mod@v0.10.0 h1:lFO9qtOdlre5W1jxS3r/4szv2/6iXxScdzjoBMXNhYk=
    golang.org/x/sync@v0.2.0 h1:PUR+T4wwASmuSTYdKjYHI5TD22Wy5ogLU5qZCOLxBrI=
    golang.org/x/sys@v0.8.0 h1:EBmGv8NaZBZTWvrbjNoL6HVt+IVy3QDQpJs7VRIw3tU=
    golang.org/x/text@v0.9.0 h1:2sjJmO8cDvYveuX97RDLsxlyUxLl+GHoLxBiRdHllBE=
    golang.org/x/tools@v0.6.0 => ../
    golang.org/x/vuln@v0.0.0-20230110180137-6ad3e3d07815 h1:A9kONVi4+AnuOr1dopsibH6hLi1Huy54cbeJxnq4vmU=
    honnef.co/go/tools@v0.4.2 h1:6qXr+R5w+ktL5UkwEbPp+fEvfyoMPche6GkOpGHZcLc=
    mvdan.cc/gofumpt@v0.4.0 h1:JVf4NN1mIpHogBj7ABpgOyZc65/UUOkKQFkoURsz4MM=
    mvdan.cc/xurls/v2@v2.4.0 h1:tzxjVAj+wSBmDcF6zBB7/myTy3gX9xvi8Tyr28AuQgc=
go: go1.20.4
```

**Comment by Nasfame** [comment]
@inliquid I assuming u r stuck at the function declarations in atomic/doc.go.

To see the function implementation go to atomic/asm.s

<img width="365" alt="image" src="https://github.com/golang/go/assets/24226219/e2c2ce8d-58f7-4d41-b9b0-ee5ba6898b32">

**Comment by inliquid** [comment]
@Nasfame thanks! Yea, I know it's possible to view `*.s` files but as I remember previously it was possible to navigate from function declarations.

**Comment by Nasfame** [comment]
ok which version do u remember when it was working ?

**Comment by Nasfame** [comment]
when did u last use this functionality?

**Comment by jamalc** [comment]
We don't recall having this feature. Is it possible this was implemented by some other extension?

**Comment by inliquid** [comment]
I didn't use this feature on a regular basis, so can't say when exactly it last worked, but I'm pretty sure that it worked. I don't think it was any side extension. I do use Go Asm extension, however, but AFAIK it only provides syntax highlighting.

**Comment by findleyr** [comment]
We're pretty sure that we never did this, so I'm going to switch this to a feature request :)

**Comment by adonovan** [comment]
>  I just found that it's not possible anymore.

This feature should be working again.
