### ISSUE TITLE
runtime: add debugger hook for fatal signals [freeze exception]

### ISSUE THREAD

**Issue by hyangah** [golang/go#60538]
@aarzilli 's https://go.dev/cl/495736 refactors `sighandler` and moves fatal signal handling code to a separate `fatalsignal` function.
This allows debuggers like Delve to continue to check and intercept fatal signals when necessary. It would be nice if this change is merged to go1.21.

cc @golang/release

**Comment by dmitshur** [comment]
[CL 495736](https://go.dev/cl/495736) is submitted, closing. Please comment if something more is needed for this freeze exception.
