### ISSUE TITLE
x/pkgsite: package removal request for https://pkg.go.dev/github.com/emar-kar/region

### ISSUE THREAD

**Issue by emar-kar** [golang/go#60530]
### What is the path of the package that you would like to have removed?

https://pkg.go.dev/github.com/emar-kar/region/v2
https://pkg.go.dev/github.com/emar-kar/region

 
 
 
### Are you the owner of this package?

Yes

 
### What is the reason that you could not retract this package instead?

Repository is already deleted. I didn't even know this test util was published on `pkgsite`

**Comment by bcmills** [comment]
Can you recreate the repo, publish new versions with `retract` directives, and then delete it again?

**Comment by emar-kar** [comment]
@bcmills Can I create just a blank project or should search sources for the original one?

**Comment by emar-kar** [comment]
Done

**Comment by bcmills** [comment]
The project can be empty except for the `go.mod` file containing the `retract` directive.

You'll need to tag the commit containing the `retract` directive with a release higher than the previous releases (`v1.0.1` and `v2.5.1`?) and have the `retract` directive cover every version up to and including the new tags, then fetch those versions through the proxy to get it to pick up the retractions.

**Comment by bcmills** [comment]
I see the retraction notice for `v1`. Note that there is a typo in the tag for `v2.5.4` — the tag is `v.2.5.4` (with an extra leading `.`.

**Comment by emar-kar** [comment]
Oh yeah, sorry. Just fixed the tag name

**Comment by emar-kar** [comment]
Okay, now the only version I can get is v0.0.0

**Comment by findleyr** [comment]
Is this WAI now? I see the retract notifications for those modules.

**Comment by findleyr** [comment]
Ok, closing. Please comment if I am closing erroneously.
