### ISSUE TITLE
bool values are not merged properly

### ISSUE THREAD

**Issue by lakhgupt** [golang/go#60559]
// You can edit this code!
// Click here and start typing.
package main

import (
	"fmt"

	"github.com/imdario/mergo"
)

type Foo struct {
	A string
	B int64
	C bool
	D int64
}

func main() {
	src := Foo{
		A: "five",
		B: 5,
		C: true,
		D: 10,
	}
	dest := Foo{
		C: false,
		B: 3,
		//A: "three",
		D: 11,
	}
	mergo.Merge(&dest, src)
	fmt.Println(src)
	fmt.Println(dest)
}

Output:
{five 5 true 10}
{five 3 true 11}

Expected Output:
{five 5 true 10}
{five 3 false 11}

**Comment by randall77** [comment]
You should open this issue on the [issue tracker of mergo](https://github.com/imdario/mergo/issues), not here. This is the issue tracker for the Go language itself.

**Comment by lakhgupt** [comment]
Thanks a lot, will open at above link
