### ISSUE TITLE
net/http ListenAndServe 

### ISSUE THREAD

**Issue by zengjiangbin** [golang/go#60568]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
not

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\35033\AppData\Local\go-build
set GOENV=C:\Users\35033\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\35033\Desktop\web\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Users\35033\sdk\go1.20
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Users\35033\sdk\go1.20\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.20
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=C:\Users\35033\Desktop\web\go.work
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\35033\AppData\Local\Temp\go-build812796149=/tmp/go-build -gno-record-gcc-switches
GOROOT/bin/go version: go version go1.20 windows/amd64
GOROOT/bin/go tool compile -V: compile version go1.20
gdb --version: GNU gdb (GDB) 8.1
</pre></details>

### What did you do?
<img width="446" alt="4fa459dcd16ddaa4f8b62109f456997" src="https://github.com/golang/go/assets/26378099/92d0a22f-ee4b-4290-875e-14ead8f67feb">
<img width="364" alt="69c0a3c527afba14ad6393880c5d211" src="https://github.com/golang/go/assets/26378099/f85c6669-66b1-4b45-ac4f-ed0f2e7b21c5">

### What did you expect to see?

ListenAndServe method should add  `defer ln.Close()`  ??

### What did you see instead?

**Comment by ianlancetaylor** [comment]
Please add plain text as plain text.  The images are very difficult to read.

The `ListenAndServe` method calls `Serve` which closes the listener.  The `ListenAndServeTLS` method calls `ServeTLS`, which does not close the listener.  So everything should normally work, and we aren't going to change this behavior now.
