### ISSUE TITLE
x/tools/gopls: release version v0.12.1 = v0.12.2

### ISSUE THREAD

**Issue by findleyr** [golang/go#60563]
This issue tracks progress toward releasing gopls@v0.12.1.

- [x] merge master into gopls-release-branch.0.12
- [x] update hard-coded version
- [x] update go.mod/go.sum (remove x/tools replace, update x/tools version)
- [x] tag gopls/v0.12.1-pre.1
- [x] update Github milestone
- [x] write release notes
- [x] smoke test features
- [x] tag gopls/v0.12.1 https://github.com/golang/tools/releases/tag/gopls%2Fv0.12.1
- [ ] update dependencies in master for the next release

NOTE: As a defensive measure for an incident during the release, we also released v0.12.2 as an alias for v0.12.1. The tools are identical and report their version as v0.12.1. (We are investigating.)

**Comment by justfalter** [comment]
> NOTE: As a defensive measure for an incident during the release, we also released v0.12.2 as an alias for v0.12.1. The tools are identical and report their version as v0.12.1. (We are investigating.)

Any update on this investigation, or the nature of the incident?  Is this security-related?

**Comment by justfalter** [comment]
> NOTE: As a defensive measure for an incident during the release, we also released v0.12.2 as an alias for v0.12.1. The tools are identical and report their version as v0.12.1. (We are investigating.)

@findleyr @adonovan  Any update on this investigation, or the nature of the incident?  Is this security-related?

**Comment by adonovan** [comment]
> Any update on this investigation or the nature of the incident? Is this security-related?

Not security related. The sumdb was briefly serving a cached 404 for the v0.12.1 release, preventing download of that module.
