### ISSUE TITLE
x/sys/windows: get Windows services status without all access permissions

### ISSUE THREAD

**Issue by tguenneguez** [golang/go#60573]
Next exchange with #48777 

Why not change the fonction like this :
`func (m *Mgr) OpenService(name string, right int) (*Service, error) {
	if right == nil {
		right =windows.SERVICE_ALL_ACCESS
	}
	h, err := windows.OpenService(m.Handle, syscall.StringToUTF16Ptr(name), right)
	if err != nil {
		return nil, err
	}
	return &Service{Name: name, Handle: h}, nil
}
`

**Comment by mknyszek** [comment]
That would unfortunately be compatibility-breaking. If you'd like to suggest a new API, that's fine, but we'd need someone more familiar with Windows to chime in.

Also, generally speaking we don't generally do continuations of frozen issues like this. Please update your original post with relevant context and details from https://github.com/golang/go/issues/48777 as if this were a new issue. Sorry for the inconvenience. Thanks!

**Comment by mknyszek** [comment]
We could add a new function that takes "right," but seeing as how the implementation of OpenService is using exported APIs already, I don't really see a need to do anything here. As @alexbrainman said in the last issue, copying out that code is totally reasonable here. Closing.
