### ISSUE TITLE
spec: imprecise language around min and max when considering NaN

### ISSUE THREAD

**Issue by btracey** [golang/go#60570]
The go spec at tip has the following language about min and max

```
For numeric arguments, min and max are commutative and associative:

min(x, y)    == min(y, x)
min(x, y, z) == min(min(x, y), z) == min(x, min(y, z))
```

In my reading, this is insufficiently precise.  In particular, `min(math.NaN()) == min(math.NaN())` is false, so currently the spec is impossible to satisfy (cannot both propogate NaN and have those expressions be true). There should be a clarification around the interaction of `NaN` and `==`.

**Comment by mknyszek** [comment]
CC @griesemer who wrote the spec update for this.

**Comment by griesemer** [comment]
NaN which stands for "Not a Number" is not a number, and thus arguably not a numeric argument...

**Comment by btracey** [comment]
NaN is why we can't have nice things (and arguably floating point numbers
more generally)

**Comment by crisman** [comment]
This is already covered in the text given, "For numeric arguments" which means NaN is not covered in that section.

The next line after the original quoted text gives the chart:

> For floating-point arguments negative zero, NaN, and infinity the following rules apply:

Also `min(math.NaN()) == min(math.NaN())` is correct as `math.NaN() == math.NaN()` is false and the spec says "Two floating-point values are compared as defined by the IEEE-754 standard." and that is how 754 works.  We can't import 754 like that and then say using it in another section is broken.

**Comment by crisman** [comment]
Meh, my brain is clearly not up to speed as float64 is numeric and NaN is float64 so my last comment does not make sense.  Sorry about the added confusion.

**Comment by crisman** [comment]
Related oddity for `NaN` in #60616.
