### ISSUE TITLE
net/http: doc of FormValue does not mention PATCH

### ISSUE THREAD

**Issue by gazerro** [golang/go#60585]
The documentation of the `(*Request).FormValue` method does not mention the `PATCH` method:

> // POST and PUT body parameters take precedence over URL query string values.

It should be:

> // POST, PATCH, and PUT body parameters take precedence over URL query string values.

Similarly, commit 0979767 fixed `PostFormValue`.

**Comment by shani34** [comment]
Hi everyone , can someone /assing this issue to me

**Comment by eduardbme** [comment]
Both `Request.PostFormValue` and `Request.FormValue` referring to `Request.ParseForm`, so it's seems like a valid improvement.
