### ISSUE TITLE
x/pkgsite: package removal request for github.com/Azure/azure-sdk-for-go/sdk/keyvault/*

### ISSUE THREAD

**Issue by gracewilcox** [golang/go#60583]
### What is the path of the package that you would like to have removed?

All packages under github.com/Azure/azure-sdk-for-go/sdk/keyvault

* github.com/Azure/azure-sdk-for-go/sdk/keyvault/azcertificates
* github.com/Azure/azure-sdk-for-go/sdk/keyvault/azkeys
* github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets

 
 
 
### Are you the owner of this package?

Yes, I am a Microsoft employee on the Azure SDK for Go team acting with the approval of my organization.

 
### What is the reason that you could not retract this package instead?

Our team is [moving our Key Vault modules](https://github.com/Azure/azure-sdk-for-go/issues/17906) from the `sdk/keyvault` location to `sdk/security/keyvault`. We have marked the modules in the old location as deprecated and now want them removed from pkg.go.dev.

**Comment by findleyr** [comment]
Sorry for the delay. I have enqueued these for exclusion.

**Comment by findleyr** [comment]
This is now done.
