### ISSUE TITLE
x/pkgsite: package removal request for git.agecem.com/agecem/bottin/v4

### ISSUE THREAD

**Issue by vlbeaudoin** [golang/go#60581]
### What is the path of the package that you would like to have removed?

`git.agecem.com/agecem/bottin/v4`

 
 
 
### Are you the owner of this package?

Yes
 
### What is the reason that you could not retract this package instead?

Versions 1 -> 3 AND 5 are in `agecem/bottin`, but version 4 is in `agecem/bottin/v4`. I cannot seem to update pkg.go.dev to reflect the fact that `agecem/bottin` is newer than `agecem/bottin/v4`, or how to use the retract directive to accomplish this goal.

**Comment by findleyr** [comment]
Hi, sorry for the delay.

Can you share pkgsite links relating to the versions you're describing? I do not see a version 1-3: I only a v0 version for https://pkg.go.dev/git.agecem.com/agecem/bottin, and I see that this package also exists in the /v4 and /v5 module.

Do you want to retract /v4 entirely? If so, see the [retract documentation](https://go.dev/ref/mod#go-mod-file-retract) for instruction on how to retract an entire module.
