### ISSUE TITLE
cmd/go: unnecessary parens in error message

### ISSUE THREAD

**Issue by rsc** [golang/go#60599]
```
$ go build
toolchain.go:131:24: syntax error: cannot use assignment (gotoolchain) = ("path") as value
```

The code only says `if gotoolchain = "path" {`, a typo of `=` for `==`.

I am not sure what the parens mean in this error message.
Every time I see them (apparently I do this with some frequency)
it is a bit jarring, almost like they are single-element tuples,
but then I remember Go has no tuples, at least not parenthesized ones like Python.
It would be better not to show them:

```
toolchain.go:131:24: syntax error: cannot use assignment gotoolchain = "path" as value
```

Or maybe:

```
toolchain.go:131:24: syntax error: cannot use assignment as value: gotoolchain = "path"
```

/cc @griesemer

**Comment by griesemer** [comment]
Trivial repro: https://go.dev/play/p/nFjETHH2pFk?v=gotip

**Comment by griesemer** [comment]
There's explicit code in the parser to emphasize the LHS and RHS for this kind of error:
```Go
// A common syntax error is to write '=' instead of '==',
// which turns an expression into an assignment. Provide
// a more explicit error message in that case to prevent
// further confusion.
var str string
if as, ok := s.(*AssignStmt); ok && as.Op == 0 {
	// Emphasize Lhs and Rhs of assignment with parentheses to highlight '='.
	// Do it always - it's not worth going through the trouble of doing it
	// only for "complex" left and right sides.
	str = "assignment (" + String(as.Lhs) + ") = (" + String(as.Rhs) + ")"
} else {
	str = String(s)
}
```
I added this in response to #23385.

This is trivially changed (or even removed), but we should be conscious of the issue. Without the special casing, the error for 
```Go
package p

func _(x, y int) {
	if x = y {}
}
```
will be:
```
syntax error: cannot use x = y as value
```
Maybe change it to:
```
syntax error: cannot use assignment x = y as value
```
?
