### ISSUE TITLE
cmd/compile: write internals documents

### ISSUE THREAD

**Issue by rsc** [golang/go#6059]
<pre>Write internals doc.</pre>

**Comment by agnivade** [comment]
After @mvdan's awesome READMEs on the [compiler](https://github.com/golang/go/blob/master/src/cmd/compile/README.md) and [SSA](https://github.com/golang/go/blob/master/src/cmd/compile/internal/ssa/README.md), I think an overview of the compiler and SSA is covered.

If we need further documentation on some particular portion of the compiler, we can open specific issues about that. I think we can close this one.

If anybody has any objections, feel free to reopen.
