### ISSUE TITLE
x/mobile: use less Java

### ISSUE THREAD

**Issue by MatejMagat305** [golang/go#60603]
this is mainly for discussion

### Author background
I  consider myself a  intermediate
I have experience with C, C++, Java, Kotlin, Pascal, Haskell, Assembly, Vlang, Rust and Prolog 

### Related proposals

- **Has this idea, or one like it, been proposed before?**
- I got this Idea sometime ago when I have read about https://github.com/cnlohr/rawdrawandroid

### Proposal

- **What is the proposed change?**
- based gomobile
- **which aspect of golang proposal solve?**
- it has potencial reduce binary size of apk (binary of android) it also can reduce call java, but it is not mainly goal (benefit)  and in practical maybe unmeasured, although it seems like avoid dalvik and it's GC, it couldn't have effect to go bind , it can brings more control and better debug ... 
- **how make it?**
- use cgo to bind https://github.com/cnlohr/rawdrawandroid

**Comment by ianlancetaylor** [comment]
Thanks.  This doesn't sound like it has to be a proposal, so taking it out of the proposal process.

**Comment by MatejMagat305** [comment]
ok, sorry for bad mark ...

**Comment by MatejMagat305** [comment]
No sence
