### ISSUE TITLE
proposal: Go 2: Enhance the competitiveness of the Golang

### ISSUE THREAD

**Issue by Bmixo** [golang/go#60612]
### Author background

- **Would you consider yourself a novice, intermediate, or experienced Go programmer?**
experienced Go programmer
- **What other languages do you have experience with?**
golang、c++

### Related proposals

- **Has this idea, or one like it, been proposed before?**
no
- **Does this affect error handling?**
  no
- **Is this about generics?**
no
### Proposal

- **What is the proposed change?**

**Why do I feel that these few versions of Go in 2023 hardly bring any substantial benefits or changes, except for the addition of a generics feature? The other minor versions seem to be just small bug fixes in the standard library. Does the Go team understand that the world's economy is undergoing a transformation, and that backend development for the internet economy is becoming a severely affected area in terms of unemployment? After diving deep into learning Go, I found that my job prospects are almost limited to Kubernetes and website backend development due to the limitations of your toolchain.**

![image](https://github.com/golang/go/assets/25509024/862563ef-5eef-45b6-b1be-57148787230e)
![image](https://github.com/golang/go/assets/25509024/74b4c00b-86b7-4fb3-bd11-277d54bea27a)

- Why does Go language have to include the runtime by default?Do you dislike developers who want to use Go to develop operating systems?

- Why does the Go language enforce the use of garbage collection (GC)? Dlang's garbage collection (GC) is optional. Why can't Go implement that?Why can't the Go language incorporate the ownership-based implementation used in Rust?

- Why can't you consider adding operator overloading functionality for developers working on numerical computation, deep learning, machine learning, and image processing matrix libraries?  eg: matrixA.Add(matrixB) => matrixA+matrixB

- Why does call C code inside a for loop will cost such  significant performance loss?Are you considering doing some actual work to fix this performance  issure or are you just ignoring it and doing nothing about it?

![image](https://github.com/golang/go/assets/25509024/930a6749-8e48-46fb-81d2-12fabc5ac986)

- Why doesn't Golang support plugins on Windows? This functionality has been abandoned for so many years. What have you been doing all this time? Windows is the most widely used operating system worldwide, and nearly all industrial programs run on Windows.

- Why does Go will generate C header files when exporting static libraries? Why can't Go allow Go calling its own static libraries without using C header files, considering that static and dynamic libraries are such importent things for system programming?

- Why do such useless improvement and fancy  stuff  like change compiler "go tool compile -importcfg" ? Most other languages have two step compile and linking,and they can manual run the step.just like this:
```
g++ -c file1.cpp
g++ -c file2.cpp
g++ -o myprog.exe file1.o file2.o
```
so what is the innovative aspect of using importcfg in recent versions? Why complicate simple things? Does this improvement bring any benefits for Go market promotion? Will it make Go programmers have capability to work in more domains and easy finding jobs? Is this improvement really made have any benefit for Go programmers? Can it help Go programmers earn higher income? Can it make Go programmers become more competitive among all programmers? Have you considered interests beyond those of Google backend since Go claim to be an organization rather than just a Google company?

- Why don't you focus on developing the LLVM frontend properly? Do you realize how many benefits LLVM IR can bring? Do you have any plans like Carbon Language and Dlang's that integrating C++ source code? Considering the poor performance of cgo, do you have any ideas about change this? Is the lack of C++ integration a complete abandonment of systems programming? Do we all have to use SWIG  to generate  cgo bindings for libraries like PhysX and ImGui one by one? After all, cgo performs so poorly!

 **Who does this proposal help, and why?**
My suggestion is, can you make some practical contributions? Instead of fixing minor bugs in every release, have you even considered the job market for Go programmers? Kubernetes (k8s) and CNCF have already full and i dont think it going to have any great extent. Go has become the number one language of choice for cloud computing. Can you consider the development of Go in other areas, such as systems programming and machine learning?

In recent years, Python has been the preferred language for machine learning, and Rust is rising rapidly in systems programming. C++ is about to release version 23, which will include the "import std" feature. Carbon Language aims to optimize C++ and achieve seamless integration with it at the source code level.

Every language is progressing rapidly, but what does the Go official team doing every day? What competitive advantages will Go have in a few years? Do you realize how many excellent Go libraries have been buried due to the flaws in your toolchain, wasting people's time and causing many GitHub projects to fail?

cgo performance issure such as:
https://github.com/g3n/engine
https://github.com/hajimehoshi/ebiten

AI programming Language syntactic sugar(operator overloading), marketing:
https://github.com/gorgonia/gorgonia

Static or dynamic library：
https://github.com/pkujhd/goloader

llvm:
https://tinygo.org/

### Costs

- **Would this change make Go easier or harder to learn, and why?**
no

**Comment by ianlancetaylor** [comment]
Thanks, but there isn't any useful action we can take here, so closing.

If you want to discuss Go's shortcomings, please do not use the issue tracker.  Please use a forum.  See https://go.dev/wiki/Questions.  Thanks.
