### ISSUE TITLE
affected/package: x86 assembly `REP MOVSB` instruction not works

### ISSUE THREAD

**Issue by cocotyty** [golang/go#60620]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.4 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/tangyang/.cache/go-build"
GOENV="/home/tangyang/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/tangyang/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/tangyang/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2407807130=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
Write a asm file , contains:
 REP  MOVSB 

### What did you expect to see?
Compile successfully

### What did you see instead?

/xxx.s:406: illegal or missing addressing mode for symbol MOVSB

**Comment by randall77** [comment]
See, e..g, `runtime/asm_amd64.s` for a correct use of `REP`.
In particular, you should write it as
```
    REP; MOVSB
```
With the semicolon.

Please reopen this issue if that fix doesn't work for you. When you reopen, please include an entire `.s` file that isn't compiling, so we can reproduce on our end.

**Comment by cocotyty** [comment]
> See, e..g, `runtime/asm_amd64.s` for a correct use of `REP`. In particular, you should write it as
> 
> ```
>     REP; MOVSB
> ```
> 
> With the semicolon.
> 
> Please reopen this issue if that fix doesn't work for you. When you reopen, please include an entire `.s` file that isn't compiling, so we can reproduce on our end.

Thank you for your help! It works!
