### ISSUE TITLE
x/tools/gopls: missing references to methods on generic types

### ISSUE THREAD

**Issue by findleyr** [golang/go#60622]
Repro:

- clone https://github.com/hashicorp/terraform-provider-aws
- open `./internal/types/option.go`
- find references on methods, e.g. `(Option[T]).MustUnwrap`; gopls@v0.12.0 finds no references, but v0.11.0 does

CC @adonovan

**Comment by adonovan** [comment]
The root cause is failure of `objectpath.For` for the `MustUnwrap` method object during index construction (`xrefs.Index`).
