### ISSUE TITLE
go/cmd go race checker: runtime.(*mspan).setUserArenaChunkToFault relocation target not defined

### ISSUE THREAD

**Issue by abhinavDhulipala** [golang/go#60624]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

I believe 20.04 is the latest release

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="~/.cache/go-build"
GOENV="~.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="~/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="~/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="$WORKDIR/new-prometheus-slurm-exporter/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4119921415=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

I ran the following
```bash
$ go test -race
$ go build -o $BUILD_DIR -race
```
I tried to expose some that is _similiar_ to the code I employ in my package. Here is the play link: https://go.dev/play/p/QRrfjx9e_90
I don't know whether it matters but I'm using the latest Prometheus library and Mutex lock

### What did you expect to see?
I expected it to evaluate whether my code had race conditions. I use both channels and locks

### What did you see instead?
I see this error trace
```bash
 % go build -race -o build 
# slurm_exporter
runtime.(*mspan).setUserArenaChunkToFault: relocation target __tsan_free not defined
runtime.mallocgc: relocation target __tsan_malloc not defined
runtime.runfinq: relocation target __tsan_finalizer_goroutine not defined
runtime.(*sweepLocked).sweep: relocation target __tsan_free not defined
runtime.goexit1: relocation target __tsan_go_end not defined
runtime.gfget: relocation target __tsan_malloc not defined
runtime.(*p).init: relocation target __tsan_proc_create not defined
runtime.(*p).destroy: relocation target __tsan_go_end not defined
runtime.(*p).destroy: relocation target __tsan_proc_destroy not defined
runtime.RaceDisable: relocation target __tsan_go_ignore_sync_begin not defined
runtime.RaceEnable: relocation target __tsan_go_ignore_sync_end not defined
runtime.raceinit: relocation target __tsan_init not defined
runtime.raceinit: relocation target __tsan_map_shadow not defined
runtime.racefini: relocation target __tsan_fini not defined
runtime.racemapshadow: relocation target __tsan_map_shadow not defined
runtime.racegostart: relocation target __tsan_go_start not defined
runtime.raceacquireg: relocation target __tsan_acquire not defined
runtime.raceacquirectx: relocation target __tsan_acquire not defined
runtime.racereleaseg: relocation target __tsan_release not defined
runtime.racereleaseacquireg: relocation target __tsan_release_acquire not defined
runtime.racereleasemergeg: relocation target __tsan_release_merge not defined
/usr/lib/go/pkg/tool/linux_amd64/link: too many errors
```

**Comment by dr2chase** [comment]
I think there is something wrong (missing) from your environment.  What version of C are you using (gcc, clang, etc)?  It works okay for me, if the race detector were broken various tests would fail.

**Comment by abhinavDhulipala** [comment]
Thanks for responding. According to my `go env`. Cgo is using `gcc` and `g++`. Here are their versions:

```bash
g++ --version
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```bash
gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by seankhliao** [comment]
How was Go installed?
It's home in /usr/lib suggests an installation by a distro package manager, but ubuntu 20.04 doesn't have 1.20, nor would it install go1.20 in /usr/lib/go if it did.

**Comment by abhinavDhulipala** [comment]
That's just a soft-link. Looks like a manual installation. 
```bash
% ll /usr/bin/go
lrwxrwxrwx 1 root root 18 Jun  6 11:43 /usr/bin/go -> /usr/lib/go/bin/go
/usr/lib/go % ls
api  codereview.cfg   doc  LICENSE  PATENTS  README.md	  src	VERSION
bin  CONTRIBUTING.md  lib  misc     pkg      SECURITY.md  test
```
