### ISSUE TITLE
go/types: inconsistency between LookupFieldOrMethod and NewMethodSet

### ISSUE THREAD

**Issue by adonovan** [golang/go#60634]
```
package p

type T *int

func (r *T) f() {} // error: "invalid receiver type T[A] (pointer or interface type)"
```

It is an error to declare a method on *T when T's underlying type is a pointer. Nonetheless, after reporting the error, the type checker must represent this situation. However, its representation is inconsistent: LookupFieldOrMethod fails to find the method, but NewMethodSet does report it. I think it should be an invariant that these two operations are consistent. (This bug was the cause of a crash in gopls.)

https://go.dev/play/p/uWoUFewDCj4:
```
	// Look up func T.f (with addressable T): it doesn't exist.
	T := pkg.Scope().Lookup("T").Type()
	obj, _, _ := types.LookupFieldOrMethod(T, true, pkg, "f")
	if obj != nil {
		log.Fatalf("LookupFieldOrMethod(T.f) = %v", obj)
	}

	// But ask for the method set of *T: it contains f!
	mset := types.NewMethodSet(types.NewPointer(T))
	if mset.Len() > 0 {
		log.Fatalf("NewMethodSet(*T) is non empty: %v", mset)
	}
```
Output:
```
 NewMethodSet(*T) is non empty: MethodSet {
	method (*p.T) f()
}
```

@findleyr @mdempsky

**Comment by findleyr** [comment]
Thanks for digging into this crash!

Yep, sounds like a bug in NewMethodSet. Since it has existed for a while, it's probably OK to defer the fix until 1.22 (but fixing it in 1.21 means that we can delete our workaround 6 months sooner...).
