### ISSUE TITLE
proposal: go/parser: extending go compiler for custom compile-time checks

### ISSUE THREAD

**Issue by nicchongwb** [golang/go#60660]
Currently, we use the `go` binary to compile and build our projects. Will introducing extensible APIs to perform customised checks on compile-time data structures (eg. AST, IR) be inline with what Go is design to be?

In Java/Kotlin, we are able to develop custom compiler plugins that can be autoserviced during compile time by `javac` or `kotlinc`. One use case of such a capability is to manipulate the IR (intermediate representation) before bytecode/machine code generation. Another use case is to perform custom checks on the program context during compile time (as compared to static code analysis).

Maybe another challenge for this, is the consideration of how such compiler plugins will function with Go's native binary and build tool process.

**Comment by ianlancetaylor** [comment]
I'm sorry, this is not a direction that we are going to follow.  The compiler IR is unstable and we aren't going to commit to stability for the benefit of compiler plugins.

For static analysis purposes, we already have extensive tooling that is not part of the compiler.  See https://pkg.go.dev/golang.org/x/tools/go/analysis .
