### ISSUE TITLE
go.exp/fsnotify: possible shadowing bug

### ISSUE THREAD

**Issue by robpike** [golang/go#6067]
<pre>This looks like a real shadowing bug but I can't make the tests pass with or without a
fix. Expert needed?

go.exp/fsnotify/fsnotify_bsd.go:161: declaration of path shadows declaration at
/Users/r/src/code.google.com/p/go.exp/fsnotify/fsnotify_bsd.go:130</pre>

**Comment by rsc** [comment]
fsnotify has been removed from exp
