### ISSUE TITLE
syscall: PtraceGetRegs return value error on Linux/{arm64,loong64}

### ISSUE THREAD

**Issue by abner-chenc** [golang/go#60679]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.4 linux/loong64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

```
package main

/*
#include <stdio.h>
#include <unistd.h>
#include <signal.h>
#include <sys/types.h>

int create_progress()
{
	pid_t pid;

	pid = fork();
	if (pid == 0) {
		while(1) {
			usleep(200);
		}
	}

	return (int)pid;
}

void send_signal_kill(pid_t pid)
{
	kill(pid, SIGKILL);
}
*/
import "C"

import (
	"fmt"
	"syscall"
)

func main() {
	var pid int
	var regs syscall.PtraceRegs

	pid = int(C.create_progress())
	if pid > 0 {
		fmt.Printf("pid: %d\n", pid)
		err := syscall.PtraceAttach(pid)
		if err != nil {
			fmt.Printf("attach err: %v\n", err)
		}

		defer C.send_signal_kill(C.int(pid))
		defer syscall.PtraceDetach(pid)

		var status syscall.WaitStatus
		for {
			wpid, err := syscall.Wait4(pid, &status, syscall.WALL, nil)
			if err != nil {
				panic(err)
			}
			fmt.Printf("wpid: %d\n", wpid)
			if wpid == pid {
				break
			}
		}

		err = syscall.PtraceGetRegs(pid, &regs)
		if err != nil {
			fmt.Printf("getregs err: %v\n", err)
		}

		fmt.Printf("regs: %v\n", regs)
	}
}
```

### What did you expect to see?
<pre>
pid: 17023
wpid: 17023
regs: {[102 1099359059400 1099360532336 1099441289504 18446744073709551100 0 0 1099360530736 0 2 824633721392 101 0 1099359226540 12 0 1 1 9187201950435737471 56 0 0 4833107456 0 1099441289544 4832428080 49 392 4935863200 4832564256 1099360532336 4935972416] 1099359059420 1099359226540 0 [0 0 0 0 0 0 0 0 0 0]}
</pre>

### What did you see instead?
<pre>
pid: 21359
wpid: 21359
getregs err: input/output error
regs: {[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 0 0 0 [0 0 0 0 0 0 0 0 0 0]}
</pre>

**Comment by dr2chase** [comment]
@golang/runtime @ianlancetaylor
