### ISSUE TITLE
cmd/go: TestScript expects go.env to contain GOTOOLCHAIN=auto

### ISSUE THREAD

**Issue by qmuntal** [golang/go#60685]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.21-b9baf4452f Thu Jun 8 01:52:35 2023 +0000 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

Only with tip.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\***\AppData\Local\go-build
set GOENV=C:\Users\***\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\***\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\***\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Users\***\code\golang-go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=local
set GOTOOLDIR=C:\Users\***\code\golang-go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=devel go1.21-b9baf4452f Thu Jun 8 01:52:35 2023 +0000
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\***\AppData\Local\Temp\go-build4262901046=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

1. Update `GOROOT/go.env`, replacing `GOTOOLCHAIN=auto` with `GOTOOLCHAIN=local`.
2. Run `go tool dist test -run cmd/go`

### What did you expect to see?

All tests passed.

### What did you see instead?

Some tests failed.

```cmd
=== Failed
=== FAIL: cmd/go TestScript/work_goline_order (0.15s)
=== FAIL: cmd/go TestScript/mod_go_version (0.04s)
=== FAIL: cmd/go TestScript/mod_get_future (0.08s)
=== FAIL: cmd/go TestScript/gotoolchain_modcmds (0.13s)
=== FAIL: cmd/go TestScript/gotoolchain_local (0.05s)
=== FAIL: cmd/go TestScript/goline_order (0.10s)
=== FAIL: cmd/go TestScript (0.33s)
```

As per [CL 462198](go.dev/cl/462198), the original intent of having `go.env` was this:

> Various Linux distributions edit cmd/go/internal/cfg/cfg.go to change
the default settings of GOPROXY and GOSUMDB. Make it possible for
them to do this without editing the go command source code by
introducing GOROOT/go.env and moving those defaults there.

I'm trying to exercise this use case, changing the `GOTOOLCHAIN` default value instead (see #57001), and I can't get all tests to pass without patching a bunch of script tests.

@rsc I might be missing something, as this feature is quite new, but I'll tentatively label this as release-blocker because it is a potential blocker for Linux distros, at least it is for the one I support at Microsoft.

**Comment by dr2chase** [comment]
@bcmills @rsc

**Comment by bcmills** [comment]
@qmuntal, does setting `GOTOOLCHAIN=auto` in the default script environment help?

(If not, perhaps we need a test hook to override the default `GOROOT/go.env`.)

**Comment by qmuntal** [comment]
> @qmuntal, does setting `GOTOOLCHAIN=auto` in the default script environment help?
> 
> (If not, perhaps we need a test hook to override the default `GOROOT/go.env`.)

Almost, the only remaining failure is `TestScript/gotoolchain_local`:

```cmd
script_test.go:158: FAIL: testdata/script/gotoolchain_local.txt:11: stdout auto: no match for `(?m)auto` in stdout
```

**Comment by bcmills** [comment]
That one seems like just an erroneous expectation in the test. Want to send a CL to clean it up?

**Comment by qmuntal** [comment]
> That one seems like just an erroneous expectation in the test. Want to send a CL to clean it up?

Suro + done!
