### ISSUE TITLE
x/pkgsite: go.googlesource.com does not offer ZIP download

### ISSUE THREAD

**Issue by 4cq2** [golang/go#60700]
### What is the URL of the page with the issue?

https://pkg.go.dev/golang.org/x/tools
 
### What is your user agent?
 
Mozilla Firefox
 
### What did you do?

if you visit the page, you are presented with this URL:

https://cs.opensource.google/go/x/tools

### What did you expect to see?
 
A link to download ZIP or TAR.GZ
 
### What did you see instead?

I cannot see a method to download the source code from `opensource.google`. another user pointed me here:

https://go.googlesource.com/tools

but that doesn't have a link to download a ZIP or TAR.GZ either.

**Comment by seankhliao** [comment]
it's there as tgz links

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by 4cq2** [comment]
> it's there as tgz links

no, its not.

**Comment by 4cq2** [comment]
> it's there as tgz links

no, its not:

~~~
> curl https://go.googlesource.com/tools | rg tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11479    0 11479    0     0  25825      0 --:--:-- --:--:-- --:--:-- 25911
~~~

**Comment by seankhliao** [comment]
that page doesn't represent any ref

**Comment by 4cq2** [comment]
neither does this:

https://github.com/golang/tools

but it does include a link to download:

https://github.com/golang/tools/archive/refs/heads/master.zip
