### ISSUE TITLE
govulncheck-action: Add support for check-latest when using setup-go

### ISSUE THREAD

**Issue by gaby** [golang/go#60704]
The new govulncheck-action doesnt now allow to specify "check-latest" for the "setup-go" action. This causes the CI to use cache versions and fail when there's a security release like `1.20.5`

Add a field for "check-latest" that gets passed setup-go here: https://github.com/golang/govulncheck-action/blob/master/action.yml

Related to: https://github.com/actions/setup-go/issues/384

**Comment by gaby** [comment]
Ping @julieqiu @cagedmantis @bkessler-go

**Comment by gaby** [comment]
I was going to do a PR but for some reason this repo is not hosted on Github, instead its a mirror 😁

**Comment by dr2chase** [comment]
@golang/vulndb

**Comment by gaby** [comment]
The `cache` key also needs to be configurable. Ideally set to false by default. 

https://github.com/actions/setup-go/blob/main/action.yml#LL15C5-L15C5

**Comment by gaby** [comment]
Any news on this?
