### ISSUE TITLE
x/vuln: govulncheck hangs when collecting stacks of all `runtime` usages

### ISSUE THREAD

**Issue by karelbilek** [golang/go#60708]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.9 darwin/arm64
</pre>

### Does this issue reproduce at the latest version of golang.org/x/vuln?
Yes

### What operating system and processor architecture are you using (`go env`)?

Darwin

### What did you do?

I have a rather big project.

I was using go 1.19.9. Then, this vulnerability was published

https://pkg.go.dev/vuln/GO-2023-1840

When I run `govulncheck ./...`, it eats 8 cores for 5 minutes.

That is not normal. Go vulncheck should not take that much longer than code build. When before this vuln, it took seconds.

I know that I am using an old go version, which I did not notice. But then govulncheck should warn me, not hang.

Below is the actual issue in the govulncheck code.

When doing pprof, I figured out it's collecting _all_ the traces where any function from `runtime` was used, and spending all the time on sorting slices.

The issue is at `func CallStacks(res *Result) map[*Vuln][]CallStack {`

It seems that the `for _, vuln := range res.Vulns {` is run 2052 times, and for each one, there is about 50000 of them for each.

When I made a small adjustment to the code, it fixed it instantly. That is, in witness.go - https://go.googlesource.com/vuln/+/refs/heads/master/internal/vulncheck/witness.go , instead of 

```
		for _, cs := range callsites(f.CallSites, seen) {
			nStack := &callChain{f: cs.Parent, call: cs, child: c}
			if entries[cs.Parent] {
				stacks = append(stacks, nStack.CallStack())
			}
			queue.PushBack(nStack)
		}
```

I added (very dumb)

```
		for _, cs := range callsites(f.CallSites, seen) {
			nStack := &callChain{f: cs.Parent, call: cs, child: c}
			if entries[cs.Parent] {
				stacks = append(stacks, nStack.CallStack())
                                 if len(stacks)>10 {return stacks}
			}
			queue.PushBack(nStack)
		}
```

it worked well.

I think govulncheck is trying to get _all_ the usages of all `runtime` functions, which then tries to somehow sort thousands of call stacks over and over. (2000 times getting and sorting 50.000 call stacks, I guess)

The simple fix is to just limit how many stacks will this collect. As the user still sees just 27 stacks....

### What did you expect to see?

See above

### What did you see instead?

See above

**Comment by timothy-king** [comment]
cc @zpavlinovic  
There was also some relevant discussion here https://gophers.slack.com/archives/C0VPK4Z5E/p1686300492622229

**Comment by karelbilek** [comment]
I _don't_ think I'm the only one with this problem, I think it will also be present with old go 1.20 (but I cannot test now)

**Comment by dr2chase** [comment]
@golang/vulndb

**Comment by zpavlinovic** [comment]
Thanks for reporting this.

Indeed, govulncheck tries to find the "best" call stack for each reachable vulnerable symbol for better user experience. It does so by choosing from all "representative" call stacks. If there are a lot of vulnerable symbols, computing all representative call stacks for each such symbol might take time.

We should probably introduce some heuristic, in the lines of what you described, to counter examples such as [GO-2023-1840](https://pkg.go.dev/vuln/GO-2023-1840)  where all symbols of a package are deemed vulnerable.

@ianthehat @julieqiu

**Comment by zpavlinovic** [comment]
Feel free to re-open the issue if the problem persists. We couldn't verify if it solves the problem on your code, but it did for another large project we considered.
