### ISSUE TITLE
net/url: fix typo in method Redacted() 

### ISSUE THREAD

**Issue by starius** [golang/go#60716]
### What version of Go are you using (`go version`)?

<pre>
$ go version

1.20.5

</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

Open https://pkg.go.dev/net/url#URL.Redacted
It says "Only the password in u.URL is redacted."
Should be "Only the password in u.User is redacted."

**Comment by ianlancetaylor** [comment]
Thanks.
