### ISSUE TITLE
cmd/compile: gopls install failed on centos stream 9

### ISSUE THREAD

**Issue by bucketsize** [golang/go#60727]
### gopls version
0.12.2

### go env
GO111MODULE="" 
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jb1/.cache/go-build"
GOENV="/home/jb1/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/jb1/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jb1/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/mnt/data/jb/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/mnt/data/jb/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/jb1/repo/github.sec.samsung.net/sfploy/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3533021216=/tmp/go-build -gno-record-gcc-switches"

### What did you do?
go install golang.org/x/tools/gopls@latest  

### What did you expect to see?
success

### Editor and settings
# html/template                                                                     
/mnt/data/jb/local/go/src/sync/atomic/type.go:43:6: internal compiler error: panic: assertion failed                                                                    

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new
# golang.org/x/tools/gopls/internal/lsp/protocol
../../../go/pkg/mod/golang.org/x/tools/gopls@v0.12.2/internal/lsp/protocol/tsserver.go:95:6: internal compiler error: panic: assertion failed

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new

### Logs
not installed

**Comment by findleyr** [comment]
Hi, thanks for the report. If I'm understanding correctly this error message is coming from the compiler itself, not gopls.

CC @golang/compiler

**Comment by thanm** [comment]
I can't seem to reproduce this with go 1.20.5 on my linux machine.

Could you please try to the same install command passing "-h" to the compiler, e.g. 

```
go install -gcflags=-h golang.org/x/tools/gopls@latest
```

That should produce panic from the error with a stack trace.
