### ISSUE TITLE
proposal: Go 2: Go Should Introduce Ternary Operators at least for templating.

### ISSUE THREAD

**Issue by Necoo33** [golang/go#60726]
Hello. I'm a node.js developer which built real world apps with it. I know typescript, php and c++. I'm started to learn go new but also i write a liblary for it, so im played a bit with that language. And i want to make real world apps also with go but there is a problem for me: there is no ternary operator in this language.

Most of the time ternary operators aren't really needed but in some cases, they are so useful. One of them is adding attributes and classes to the html elements depending on your data.

If your app requires quite big forms for adding and also updating data, your customers could want from you to make current values selected by default on form inputs. When you deal with such that scenario ternary operator makes your life so much simpler, especially on select boxes.

Select Boxes includes option tags as many as you want and if you want to make one of that options selected by default, you have to add "selected" keyword as attribute to it. In this case if you can't use ternary you have to make it with horrible looking and writing front-end javascript codes.

According to my experiences, when you want to give specific classes to your html tags that's very useful.

I think there is no breaking changes needed for that, it can be designed as a synthactic sugar of if/else if/else statements, it can be design for only templating datas.

That change will make go more capable for full-stack development for sure.

**Comment by randall77** [comment]
This was previously proposed, and declined, in #33171 and others.
You might also be interested in #60204.

I'm not sure what "at least for templating" means. Do you want a general Go language operator, or would maybe a new template operator be sufficient? The `pipeline` operator seems at least adjacent to what you need.
