### ISSUE TITLE
pkg/tool/darwin_arm64/compile: scans non invalid build files

### ISSUE THREAD

**Issue by Nasfame** [golang/go#60724]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.5 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN="/Users/hiro/go/bin"
GOCACHE="/Users/hiro/go/cache"
GOENV="/Users/hiro/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/hiro/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/hiro/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/hiro/goferHiro/gcvis/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/44/nbbyll_10jd0z8rj_qxm43740000gn/T/go-build4213734283=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

```bash
git clone https://github.com/golangFame/gcvis
git checkout 8ce8b3d4708c73afe99a05ba3bd3cc9a7e10eb19
go build .
```

### What did you expect to see?
``` bash

```

### What did you see instead?
```bash
$ go build .
go: downloading github.com/pkg/browser v0.0.0-20210911075715-681adbf594b8
go: downloading golang.org/x/crypto v0.9.0
go: downloading golang.org/x/term v0.8.0
go: downloading golang.org/x/sys v0.8.0
# github.com/golangFame/gcvis
./template.go:8:3: go:embed requires go1.16 or later (-lang was set to go1.14; check go.mod)
```

**Comment by seankhliao** [comment]
empty

**Comment by Nasfame** [comment]
> empty

@seankhliao its not empty i missed the some content while copy pasting from external markdown editor. My Bad!

**Comment by seankhliao** [comment]
see #43980

**Comment by Nasfame** [comment]
Seems like "A module needs to declare the higher version to be able to make use of the new features, however, it can still choose to support older versions through the use of build tags".
