### ISSUE TITLE
xml:how to check point to nil when xml Unmarshal 

### ISSUE THREAD

**Issue by ChuLiqiang** [golang/go#60736]
when some value is <tt:PTZPosition /> how can I check the value is nil when xml Unmarshal. I try use pointer.but the value is not nil(Zoom attributes is 0 I can not confirm 0 value is pass by xml value).

Example code:https://go.dev/play/p/BrgD4S--Rmf

code:
package main

import (
	"encoding/xml"
	"fmt"
)

type Vector1D struct {
	X float64 `xml:"x,attr"`
}

type PTZVector struct {
	Zoom Vector1D `xml:"Zoom"`
}

type PTZPresetTourPresetDetailUnmarshal struct {
	PTZPosition *PTZVector `xml:"PTZPosition"`
}

func main() {
	str := `
          <tt:PresetDetail>
            <tt:PTZPosition />
          </tt:PresetDetail>
`
	var ans PTZPresetTourPresetDetailUnmarshal
	err := xml.Unmarshal([]byte(str), &ans)
	if err != nil {
		panic(err)
	}
	fmt.Printf(`%#v`, ans.PTZPosition)
}

result:
&main.PTZVector{Zoom:main.Vector1D{X:0}}

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
