### ISSUE TITLE
cmd/6c: crash on g->writebuf == nil

### ISSUE THREAD

**Issue by dvyukov** [golang/go#6073]
<pre>parent: 17599:d91993212194 tip, darwin/amd64

Apply the following patch:

+++ b/src/pkg/runtime/panic.c	Wed Aug 07 23:55:11 2013 +0400
@@ -415,6 +415,7 @@
 		runtime·exit(3);
 	}
 	m-&gt;dying = 1;
+	g-&gt;writebuf == nil;
 	runtime·xadd(&amp;runtime·panicking, 1);
 	runtime·lock(&amp;paniclk);

run make.bash

pkg/runtime
go tool dist: FAILED: pkg/tool/darwin_amd64/6c -F -V -w -I $WORK -I pkg/darwin_amd64 -D
GOOS_darwin -D GOARCH_amd64 -o $WORK/panic.o src/pkg/runtime/panic.c

The code is 'invalid', but the crash was still surprising.</pre>

**Comment by rsc** [comment]
6c is gone!
