### ISSUE TITLE
x/tools/gopls: rename of receiver var gives spurious shadowing error

### ISSUE THREAD

**Issue by adonovan** [golang/go#60752]
There's a bug in the shadowing logic of rename w.r.t. receivers:

```
type foo int

func (f foo) f() {} // rename f to foo:

error: renaming this var "f" to "foo" [the receiver variable name]
would shadow this reference [the receiver type name]
to the type declared here [above]
```

The renaming is actually safe, since the receiver is resolved in the package scope.

**Comment by findleyr** [comment]
This seems like something that can wait for v0.13.0, so moving to that milestone.

**Comment by adonovan** [comment]
While working on CL 509875 I temporarily deluded myself that these were two aspects of the same bug. They were not, but I had to do most of the work of fixing this one to figure it out. Bumping this back to v0.12. ;-)

**Comment by adonovan** [comment]
Fixed again.
