### ISSUE TITLE
math/big: about bigint add 

### ISSUE THREAD

**Issue by tedmax100** [golang/go#60762]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.1 darwin/arm64
</pre>

### What did you do?
```go
// You can edit this code!
// Click here and start typing.
package main

import (
	"fmt"
	"math/big"
)

type Test struct {
	target big.Int
}

func OO(input Test) {
	input.target.Add(&input.target, big.NewInt(2))
}

func main() {
	var yy Test
	yy.target.SetUint64(0)
	for i := 0; i < 4; i++ {
		OO(yy)
		fmt.Println(yy.target.String())
		yy.target.Add(&yy.target, big.NewInt(10))
	}
	fmt.Println(yy.target.String())
}
I 
```

### What did you expect to see?
I thought the answer was.
0
10
20
30
40

But i got 
0
10
22
34
44

**Comment by emilhotkowski** [comment]
I believe it is not a problem with bigint but rather misunderstanding. When you pass a struct as an argument to a function you create a _copy_ of it. So no wonders you don't see any addition done. More info [here.](https://stackoverflow.com/a/44872811)

**Comment by seankhliao** [comment]
https://pkg.go.dev/math/big#Int
> shallow copies of Ints are not supported and may lead to errors.
