### ISSUE TITLE
x/tools/gopls: misleading error message when having multiple workspace folders and using build tag

### ISSUE THREAD

**Issue by hyangah** [golang/go#60776]
### gopls version

v0.12.2 (or v0.12.1)

### go env

<details><summary>go env</summary>
<pre>
 go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/hakim/Library/Caches/go-build"
GOENV="/Users/hakim/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/hakim/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/hakim/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.20.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/hakim/projects/tmp-misleading/mod1/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/5p/zn7ykc111kn3lm09h_47mz2w001py5/T/go-build89764978=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre>
</details>

<details><summary>gopls stats</summary>
<pre>
gopls stats 
Initializing workspace...     done (281.462653ms)
Gathering bug reports...      done (368.227003ms)
Querying memstats...          done (4.590305ms)
Querying workspace stats...   done (716.432µs)
Collecting directory info...  done (186.099µs)
{
  "BugReports": [],
  "CacheDir": "/Users/hakim/Library/Caches/gopls/309eafdc",
  "DirStats": {
    "Files": 4,
    "TestdataFiles": 0,
    "GoFiles": 2,
    "ModFiles": 1,
    "Dirs": 1
  },
  "GOARCH": "amd64",
  "GOOS": "darwin",
  "GOPLSCACHE": "",
  "GoVersion": "go1.20.3",
  "GoplsVersion": "v0.12.1",
  "InitialWorkspaceLoadDuration": "281.462653ms",
  "MemStats": {
    "HeapAlloc": 9656168,
    "HeapInUse": 15237120,
    "TotalAlloc": 36597232
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 447,
      "Largest": 201909,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.20.3",
        "AllPackages": {
          "Packages": 48,
          "LargestPackage": 132,
          "CompiledGoFiles": 444,
          "Modules": 2
        },
        "WorkspacePackages": {
          "Packages": 1,
          "LargestPackage": 1,
          "CompiledGoFiles": 1,
          "Modules": 1
        },
        "Diagnostics": 0
      }
    ]
  }
}
</pre>
</details>

### What did you do?

```
git clone https://github.com/hyangah/tmp-misleading
cd tmp-misleading/mod1
code .
```

Then, from the VS Code window open with the setting, open `buildtag.go` which has `//go:build` tag.

### What did you expect to see?

Usual build-tag related error message on the `package` line

### What did you see instead?

"This file is within module ".", which is not included in your workspace.
To fix this problem, you can add a go.work file that uses this directory.
See the documentation for more information on setting up your workspace:
https://github.com/golang/tools/blob/master/gopls/doc/workspace.md.go list"

![Screenshot 2023-06-13 at 9 30 43 PM](https://github.com/golang/go/assets/4999471/093be285-4de1-47c4-8070-6f410c6e1260)

**Comment by findleyr** [comment]
Thanks. We should improve this heuristic.

Milestoning for v0.12.4.
