### ISSUE TITLE
My Erorr

### ISSUE THREAD

**Issue by sayyidpane9** [golang/go#60780]
Help me for this

could not import praktikum/configs (current file is not included in a workspace module)compiler[BrokenImport](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#BrokenImport)

![image](https://github.com/golang/go/assets/52853596/4e60fdce-5a12-4733-86a4-ba26fccae941)

**Comment by Nasfame** [comment]
@sayyidpane9 this won't be enough. Can u zip and share ur workspace?

**Comment by sayyidpane9** [comment]
[23_Unit Testing.zip](https://github.com/golang/go/files/11742810/23_Unit.Testing.zip)
[24_Clean and Hexagonal Architecture.zip](https://github.com/golang/go/files/11742812/24_Clean.and.Hexagonal.Architecture.zip)

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.
