### ISSUE TITLE
cmd/go: test -coverprofile "path too long" error on Windows

### ISSUE THREAD

**Issue by chrisdutz** [golang/go#60785]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.20.5 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

I am on the latest release

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\cdutz\AppData\Local\go-build
set GOENV=C:\Users\cdutz\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\cdutz\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\cdutz\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Users\cdutz\.mvnGoLang\go1.20.5.windows-amd64
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Users\cdutz\.mvnGoLang\go1.20.5.windows-amd64\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.20.5
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\cdutz\AppData\Local\Temp\go-build1515085630=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

We are using go in the Apache PLC4X project in the plc4go sub-project.
When running our build in our CI/CD servers, the Windows builds are failing when running the tests with coverage:

`[WARNING] ---------Exec.Err---------
[WARNING] github.com/apache/plc4x/plc4go/protocols/cbus/readwrite/model: C:\Users\cdutz\.mvnGoLang\go1.20.5.windows-amd64\pkg\tool\windows_amd64\cover.exe: fork/exec C:\Users\cdutz\.mvnGoLang\go1.20.5.windows-amd64\pkg\tool\windows_amd64\cover.exe: Der Dateiname oder die Erweiterung ist zu lang.`

Path length is too long (Got a German Windows)

So even when executing the command: 

` go test -v -coverprofile=target/coverage.out ./...`

I'm getting the same error, so it's not related to the maven plugin, that we are using.
I even tried moving Go to "C:\Go" but this too didn't help.

For now we're just disabling go coverage on all windows machines, but we'd like to enable it again.

### What did you expect to see?

I would expect the build to not fail on windows

### What did you see instead?

`[WARNING] ---------Exec.Err---------
[WARNING] github.com/apache/plc4x/plc4go/protocols/cbus/readwrite/model: C:\Users\cdutz\.mvnGoLang\go1.20.5.windows-amd64\pkg\tool\windows_amd64\cover.exe: fork/exec C:\Users\cdutz\.mvnGoLang\go1.20.5.windows-amd64\pkg\tool\windows_amd64\cover.exe: Der Dateiname oder die Erweiterung ist zu lang.`

**Comment by thanm** [comment]
A request: if you could please run one of the failing commands with "-x -work" flags in addition and post the output, that would be helpful for me so as to determine which path it is that is over the limit. E.g. output of

```
go test -x -work -v -coverprofile=target/coverage.out ./...
```

Thanks.

**Comment by thanm** [comment]
Thanks, yes, that is helpful. It looks as though the issue is with total command line length, not with the length of any specific file being passed to the cover tool. I'll see about crafting a fix.

**Comment by chrisdutz** [comment]
I have seen something similar with other tools ... there the length of the command being executed was too long ... they resolved the issue with dynamically creating some sort of batch script, that then is simply called (Not pretty, but it worked)

**Comment by chrisdutz** [comment]
Oh wow ... great :-) Thank you so much :-)
