### ISSUE TITLE
net: no way to lower listen backlog on a TCP listen socket

### ISSUE THREAD

**Issue by gopherbot** [golang/go#6079]
by **vinay.ys**:

<pre>While writing a tcp server one may need to set the tcp listen backlog to a lower value
than the system default. There don't seem to be any API available in net package to
accomplish this.

Which version are you using?  (run 'go version')
go version devel +d3f99f091748 Tue Jun 25 17:04:18 2013 -0700 linux/amd64</pre>

**Comment by mikioh** [comment]
Merged into #9661.
