### ISSUE TITLE
encoding/binary: panic when Write a nil.

### ISSUE THREAD

**Issue by laushunyu** [golang/go#60814]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/macoo/.cache/go-build"
GOENV="/home/macoo/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/macoo/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/macoo/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/home/macoo/go/go1.20.5"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/macoo/go/go1.20.5/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/macoo/GolandProjects/binbug/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3159415642=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```
package main

import (
	"bytes"
	"crypto/md5"
	"encoding/binary"
	"fmt"
)

type MyStruct struct {
	Name string
}

func main() {
	var a *MyStruct
	hash := md5.New()
	binary.Write(bytes.NewBuffer(nil), binary.LittleEndian, a)
	fmt.Printf("%x", hash.Sum(nil))
}

```
then:
```
$ go run .
```

### What did you expect to see?

nothing will be write to `bytes.NewBuffer(nil)`

### What did you see instead?

```

panic: reflect: call of reflect.Value.Type on zero Value

goroutine 1 [running]:
reflect.Value.typeSlow({0x0?, 0x0?, 0x524400?})
        /home/macoo/go/go1.20.5/src/reflect/value.go:2610 +0x12e
reflect.Value.Type(...)
        /home/macoo/go/go1.20.5/src/reflect/value.go:2605
encoding/binary.dataSize({0x0?, 0x0?, 0xc00004a5c0?})
        /home/macoo/go/go1.20.5/src/encoding/binary/binary.go:490 +0x17f
encoding/binary.Write({0x4c06a8, 0xc00007e150}, {0x4c0ae8, 0x567230}, {0x48dd80?, 0x0})
        /home/macoo/go/go1.20.5/src/encoding/binary/binary.go:448 +0xea5
main.main()
        /home/macoo/GolandProjects/binbug/main.go:17 +0xb5
```

**Comment by bcmills** [comment]
The documentation at https://pkg.go.dev/encoding/binary#Write says:
> Data must be a fixed-size value or a slice of fixed-size values, or a pointer to such data.

The nil interface value is not any of those things, so this is a user error that should have been caught during testing and/or code review; a panic is appropriate in that case.

**Comment by bcmills** [comment]
> but since this pointer does not point to any data, no data should be written to it and no error should be returned(maybe?).

The nil interface value is not a pointer.

**Comment by Nasfame** [comment]
@bcmills why can't we add additional check for the `data` ? Panics are the scary. 

Even the panic makes less sense for someone not accustomed to `reflect` - `panic: reflect: call of reflect.Value.Type on zero Value` .

I think its the responsibility of the developer to ensure the function exits blissfully as soon as he uses/accepts `any` type to escape static type check

**Comment by ianlancetaylor** [comment]
The standard library does not do explicit checks for all possible incorrect values.  Panicking on an invalid value is acceptable behavior.
