### ISSUE TITLE
cmd/compile: confusing error message when using an indexing expression as an array size

### ISSUE THREAD

**Issue by go101** [golang/go#60812]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```Go
package main

const S = "Go"

type T [S[0]]int // syntax error: type parameters must be named

func main() {}
```

### What did you expect to see?

syntax error: array length must be a constant

or

syntax error: type constraint is incomplete

or

syntax error: either type constraint is incomplete or array length is not a constant

### What did you see instead?

syntax error: type parameters must be named

**Comment by ianlancetaylor** [comment]
CC @griesemer
