### ISSUE TITLE
Virus total detects simple hello world program as a trojan on windows

### ISSUE THREAD

**Issue by jmwielandt** [golang/go#60828]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.5 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes. Also tried with 1.20.4.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=C:\Users\josew\go\bin
set GOCACHE=C:\Users\josew\AppData\Local\go-build
set GOENV=C:\Users\josew\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\josew\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\josew\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.20.5
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\josew\go\src\example.com\hola\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\josew\AppData\Local\Temp\go-build888617517=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

<details>
<summary>`go.mod` file:</summary>

```
module example.com/hola

go 1.20

``` 
</details>

<details>
<summary>`main.go` file</summary>

```go
package main

import "fmt"

func main() {
	fmt.Println("hola mundo")
}

```
</details>

Compile with `go build`.

Upload your `.exe` to https://www.virustotal.com/gui

My exe: [hola.zip](https://github.com/golang/go/files/11762302/hola.zip) (google chrome blocks the download).

### What did you expect to see?

No virus nor trojan detection.

### What did you see instead?

![imagen](https://github.com/golang/go/assets/37153467/7697d2ee-81d9-48d7-8486-3f7543a38fab)

Idk if the url will be available for you but: https://www.virustotal.com/gui/file/2eb68957ba42d0aafcedcef515b0485b22e0dd9e2179081bae83328ff637ba71?nocache=1

**Comment by seankhliao** [comment]
https://golang.org/doc/faq#virus
