### ISSUE TITLE
go list -m doesn't support the "replace" tag recursively

### ISSUE THREAD

**Issue by dploeger** [golang/go#60839]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.5 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/dennis.ploeger/Library/Caches/go-build"
GOENV="/Users/dennis.ploeger/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/dennis.ploeger/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/dennis.ploeger/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.20.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.20.5/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.5"
GCCGO="gccgo"
AR="ar"
CC="cc"
CXX="c++"
CGO_ENABLED="1"
GOMOD="/Users/dennis.ploeger/work/goreplacetest/c/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8j/h44wpsp14kdff86yx8gkl0t40000gn/T/go-build1833179998=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Check out the [example demo program](https://github.com/golang/go/files/11768152/goreplacetest.zip). The module c depends on module b depends on module a. Module c uses a require from a public package and then replaces that require with the local path to module b. Same thing in module b with module a.

Now, run the following in the path of module c:

    go list -modfile go.mod -m -json -mod=mod all

### What did you expect to see?

The list of required modules in json format.

### What did you see instead?

go: unrecognized import path "example.com/a": reading https://example.com/a?go-get=1: 404 Not Found

=> apparently, go list resolves the replaced dependency to module b, but doesn't resolve the replaced dependency in module b to module a and uses the unreplaced dependency instead.

**Comment by mvdan** [comment]
From https://go.dev/ref/mod#go-mod-file-replace:

> replace directives only apply in the main module’s go.mod file and are ignored in other modules. See [Minimal version selection](https://go.dev/ref/mod#minimal-version-selection) for details.

This is working as intended. See the docs above for more details.

**Comment by dploeger** [comment]
Ah okay. Thanks for the clarification.
