### ISSUE TITLE
affected/package: bufio.Scanner

### ISSUE THREAD

**Issue by Fly-Playgroud** [golang/go#60855]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go 1.19
</pre>

### Does this issue reproduce with the latest release?
No, I don't try

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\12528\AppData\Local\go-build
set GOENV=C:\Users\12528\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\Coding\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\Coding\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=E:\Program Files\GoVersionTools\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=E:\Program Files\GoVersionTools\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.19.10
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\12528\AppData\Local\Temp\go-build2405066100=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
In a for loop use bufio.scanner. When in second loop the `firstFileScanner.Scan()`  retrun `false` directly!
```go
	secondFileScanner := bufio.NewScanner(secondFile)
	defer close(b.loginCredentialsChan)
	for secondFileScanner.Scan() {
		select {
		case <-b.ctx.Done():
			return
		case <-b.boomDoneSignal:
			return

		default:
			if b.boomStatus.Load() {
				return
			}
			secondText := secondFileScanner.Text()
			firstFileScanner := bufio.NewScanner(firstFile)
			for firstFileScanner.Scan() {
				select {
				case <-b.ctx.Done():
					return
				case <-b.boomDoneSignal:
					return
				default:
					if b.boomStatus.Load() {
						return
					}
					credits := make(map[string]string, 2)
					credits["first"] = firstFileScanner.Text()
					credits["second"] = secondText
					select {
					case b.loginCredentialsChan <- credits:
					case <-b.boomDoneSignal:
						return
					}
				}
			}
		}
	}
```

### What did you expect to see?

No matter how many times the `firstFileScanner` is looped, it can always scan until all data of `firstFile` is scanned in the current loop.

### What did you see instead?

it return false and I have debugged it found that in second loop this line return an `EOF` error https://github.com/golang/go/blob/dbf9bf2c39116f1330002ebba8f8870b96645d87/src/bufio/scan.go#L214

**Comment by seankhliao** [comment]
looks like a bug in your program.
the reader passed to bufio.NewScanner is never reset.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by Fly-Playgroud** [comment]
> looks like a bug in your program. the reader passed to bufio.NewScanner is never reset.
> 
> Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.
> 
> For questions please refer to https://github.com/golang/go/wiki/Questions

I give it a os.File not a io.Reader

**Comment by ianlancetaylor** [comment]
@Fly-Playgroud The statement is still true: whatever is passed to bufio.NewScanner is not reset.  Since bufio.NewScanner takes an io.Reader argument, it's correct to describe that as a reader.

**Comment by WeidiDeng** [comment]
The problem is `*bufio.Scanner` has to be created from scratch even if the file is readable after seeking, here is where it [returns false](https://cs.opensource.google/go/go/+/refs/tags/go1.20.5:src/bufio/scan.go;l=135).

**Comment by Fly-Playgroud** [comment]
I think *bufio.Scanner should provide a method `Reset()` to reset scanner , in this way it's understanded easily

**Comment by ianlancetaylor** [comment]
@Fly-Playgroud Note that by itself that wouldn't help.  You would also need to use the `Seek` method to move the file position back to the start of the file.  The `bufio.Scanner` can't do that for you.
