### ISSUE TITLE
os: Getenv() don't work when it has more than 1 env inside

### ISSUE THREAD

**Issue by Necoo33** [golang/go#60867]
Hello, i'm using go v1.20.4 and os.Getenv function don't work when it has more than 1 variable inside it.

.env file looks like this:

```env

LOCALADDR="http://localhost:2000"
WEBSITEADDR="http://www.postgres-with-go.com"
ENVIRONMENT="dev"

```

When i find that bug, i make some tests like this:

```go

	_, exist := os.LookupEnv("LOCALADDR")
	_, exist1 := os.LookupEnv("WEBSITEADDR")
	_, exist2 := os.LookupEnv("ENVIRONMENT")

	fmt.Printf("localAddr: %v \nwebsiteAddr: %v \nenvironment: %v \n", exist, exist1, exist2)

```

And i take this Promt in the terminal:

localAddr: false
websiteAddr: false
environment: false

Normally, i should use environment variables but i don't know why i cant if they are more than 1. This also happened when i try to write the values without quotes. I'm using Windows 11 and Visual Studio Code.

### **Update: It's Solved**

First, I'm solved it with giving env variables to empty string on .env file:

```env

LOCALADDR=""
WEBSITEADDR=""
ENVIRONMENT=""

```

Later than that i use `os.Setenv()` functions for each variable:

```go

	os.Setenv("LOCALADDR", "http://localhost:2000")
	os.Setenv("WEBSITEADDR", "http://postgres-with-go.com")
	os.Setenv("ENVIRONMENT", "dev")

	_, exist := os.LookupEnv("LOCALADDR")
	_, exist1 := os.LookupEnv("WEBSITEADDR")
	_, exist2 := os.LookupEnv("ENVIRONMENT")

	fmt.Printf("localAddr: %v \nwebsiteAddr: %v \nenvironment: %v \n", exist, exist1, exist2)

```

And i take this prompt on terminal:

localAddr: true
websiteAddr: true
environment: true

So, why this weird thing happened from beginning? Why i have to set this variables manually?

**Comment by ianlancetaylor** [comment]
CC @golang/windows

**Comment by seankhliao** [comment]
have you checked that your shell has set the environment variables correctly?

**Comment by Necoo33** [comment]
> have you checked that your shell has actually set the environment variables correctly?

I don't have any idea about what you said.  If you mean in .env file there is no empty space left of the lines i checked it.

**Comment by seankhliao** [comment]
how does a line in your .env file get into your shell? Go doesn't read .env files. Did your shell pick up the your config? Which shell/platform combination is this running on? how is your program executed?

**Comment by Necoo33** [comment]
> how does a line in your .env file get into your shell? Go doesn't read .env files. Did your shell pick up the your config? Which shell/platform combination is this running on? how is your program executed? 

I'm executed program with "go run main.go" command. I'm using Visual Studio Core Insiders, and i don't know anything about "shell".

**Comment by seankhliao** [comment]
closing as I don't think this is a bug in Go, rather it is in whatever thing that sources the lines from your file into the environment.
