### ISSUE TITLE
x/pkgsite: enable LocalMode 

### ISSUE THREAD

**Issue by amine7536** [golang/go#60872]
### What is the URL of the page with the issue?
 
 Self-Hosted
 
### What is your user agent?

Any

### What did you do?
 
Launch `cmd/frontend/main.go`, navigate to `localhost:8080`. 

The site shows the same frontend as the public site pkg.go.dev with links to `go.dev`, blogs ...
 
### What did you expect to see?
 
Run the `frontend` in "LocalMode" (same as `pkgsite`). 

<img width="1080" alt="Screenshot 2023-06-19 at 20 10 00" src="https://github.com/golang/go/assets/781894/4149fdb9-3ad8-4386-8c3b-3a6d9d1ad2e2">
 
### Proposal
 
When running `pkgsite` locally, it runs by default in `LocalMode`, which hides items in the header and removes the footer completely. Running the `frontend` in `LocalMode` is particularly beneficial for those who wish to run the `frontend` locally or self-host documentation for their internal packages.

**Comment by amine7536** [comment]
https://github.com/golang/pkgsite/pull/66

**Comment by findleyr** [comment]
Thanks! Makes sense to me. We'll review.
