### ISSUE TITLE
x/exp/slog: Fix HandlersOptions.ReplaceAttr documentation when attribute is discarded

### ISSUE THREAD

**Issue by powerman** [golang/go#60870]
Documentation for latest (v0.0.0-20230522175609-2e198f4a06a1) version of HandlersOptions.ReplaceAttr says:

> If ReplaceAttr returns an Attr with Key == "", the attribute is discarded.

This is counter-intuitive (because Handler.Handle docs discard zero attribute instead), prevent returning group attrs with empty key to embed group, and didn't match actual behaviour of current implementation (which is correct: it discards zero Attr and handles Attr with empty Key but non-zero Value).

Looks like docs should be fixed to match current implementation.
(Maybe log/slog docs needs similar fix.)

**Comment by ianlancetaylor** [comment]
CC @jba
