### ISSUE TITLE
runtime,cmd/compile: `unexpected fault address` in cmd/compile on Windows

### ISSUE THREAD

**Issue by bcmills** [golang/go#60889]
```
#!watchflakes
post <- goos == "windows" && log ~ `unexpected fault address` && log ~ `fatal error: fault`
```

(extracted from https://github.com/golang/go/issues/55167#issuecomment-1585900931)

(attn @golang/runtime; CC @golang/windows)

**Comment by mknyszek** [comment]
Looking at the context (one build failing twice with what looks like memory corruption), I think we agree this *could* be a one-off. Leaving in WaitingForInfo for now, but untriaged so it'll end up back in our queue.

**Comment by qmuntal** [comment]
All these new failures are related to https://github.com/golang/go/issues/65447. Closing.
