### ISSUE TITLE
cmd/compile: fails for recursive types

### ISSUE THREAD

**Issue by Nasfame** [golang/go#60880]
### What version of Go are you using (`go version`)?

<pre>
$ go version
tip
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
goplayground
</pre></details>

### What did you do?

https://go.dev/play/p/Xt9crVV0gUW?v=gotip

```shell
go tool compile  recursive_types.go
recursive_types.go:5:6: invalid recursive type T1
        recursive_types.go:5:6: T1 refers to
        recursive_types.go:13:6: innerT refers to
        recursive_types.go:5:6: T1

```

### What did you expect to see?

```shell 
didnt panic
```

### What did you see instead?

```
./prog.go:5:6: invalid recursive type T1
	./prog.go:5:6: T1 refers to
	./prog.go:8:6: innerT refers to
	./prog.go:5:6: T1
```

### Relates to :  
- https://go.googlesource.com/proposal/+/refs/heads/master/design/43651-type-parameters.md
- https://github.com/golang/go/pull/60856
- https://github.com/golang/go/issues/60817

### Additional Info
- <s>go tool compile is able to compile the src code to object code</s>
- Passing case - https://go.dev/play/p/ptsobyBVSl4?v=gotip

**Comment by Nasfame** [comment]
Applies to go1.18, go1.19, go1.20. Backport required if this is a bug!

**Comment by ianlancetaylor** [comment]
Recursive generic types are not permitted.  Quoting https://go.dev/ref/spec#Type_parameter_declarations

> Within a type parameter list of a generic type T, a type constraint may not (directly, or indirectly through the type parameter list of another generic type) refer to T.

**Comment by Nasfame** [comment]
> Within a type parameter list of a generic type T, a type constraint may not (directly, or indirectly through the type parameter list of another generic type) refer to T.

So I presume -

`type T2[P interface{ T2[int] }] `covers the cases  `type T2[P *T2[int]] `  & `type T2[P *T2[P]] `  

But then this is not enforced in tool/compile. There are several potential test cases escaping it.

**Comment by ianlancetaylor** [comment]
CC @griesemer

**Comment by findleyr** [comment]
Per https://github.com/golang/go/issues/51244#issuecomment-1507255710, I think we could probably allow cycles through constraints, and that would fix the inconsistent handling of these checks in the typechecker.

**Comment by Nasfame** [comment]
@findleyr right cycles through constraints does no harm

**Comment by Nasfame** [comment]
> Per [#51244 (comment)](https://github.com/golang/go/issues/51244#issuecomment-1507255710), I think we could probably allow cycles through constraints, and that would fix the inconsistent handling of these checks in the typechecker.

Opening new issue #61169, #61171
