### ISSUE TITLE
encoding/binary: Size panics when passed a nil pointer to a slice

### ISSUE THREAD

**Issue by lmb** [golang/go#60892]
### What version of Go are you using (`go version`)?

1.20

### Does this issue reproduce with the latest release?

Yes.

### What did you do?

Pass `(*[]byte)(nil)` to `binary.Size`.

https://go.dev/play/p/eKvs4FJHkxy

### What did you expect to see?

The function should return `-1`.

### What did you see instead?

The function panicked instead:

```
panic: reflect: call of reflect.Value.Type on zero Value

goroutine 1 [running]:
reflect.Value.typeSlow({0x0?, 0x0?, 0xc0000406c8?})
	/usr/local/go-faketime/src/reflect/value.go:2610 +0x12e
reflect.Value.Type(...)
	/usr/local/go-faketime/src/reflect/value.go:2605
encoding/binary.dataSize({0x0?, 0x0?, 0x60?})
	/usr/local/go-faketime/src/encoding/binary/binary.go:490 +0x17f
encoding/binary.Size({0x4873c0?, 0x0?})
	/usr/local/go-faketime/src/encoding/binary/binary.go:463 +0xb9
main.main()
	/tmp/sandbox3549274882/prog.go:11 +0x25
```

**Comment by lmb** [comment]
Could this get a backport to v1.20?

**Comment by ianlancetaylor** [comment]
We normally only backport serious bugs that have no workaround.  This bug has a simple workaround, so it's not eligible for backporting.
