### ISSUE TITLE
Go Syntax Analyzer Fails to Detect Invalid Argument Types in Variadic Function Call

### ISSUE THREAD

**Issue by hsequeda** [golang/go#60893]
### What version of Go are you using (`go version`)?

<pre>
$ go version: go1.20.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/hsequeda/.cache/go-build"
GOENV="/home/hsequeda/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/hsequeda/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/hsequeda/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/hsequeda_i3/Programing/Godev/example/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1440199062=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

I tried to pass arguments of different types (an int64, an []int64, and a string) to a variadic function that is declared to accept ...int64. Here is the sample code:

```go

package main

import (
	"fmt"
)

func main() {
	fmt.Println(sum(1, []int64{2, 3, 4, 5}, "ss"))
}

func sum(values ...int64) int64 {
	resp := int64(0)
	for _, v := range values {
		resp += v
	}

	return resp
}
```

### What did you expect to see?

I expected the Go compiler to throw a compile-time error indicating that I was passing incorrect argument types to the sum function. Specifically, it should tell me that []int64 and string arguments cannot be passed to a function that expects ...int64.

### What did you see instead?

The Go compiler does not catch this mismatch of argument types. This could potentially lead to undetected bugs in the code. I suggest that the Go compiler's type checking for variadic function parameters should be enhanced to handle such scenarios.

**Comment by seankhliao** [comment]
does not reproduce https://go.dev/play/p/M3g-2Wt6_cw

**Comment by hsequeda** [comment]
The error is detected when u run the code, but it's not detected by the syntax analyzer

**Comment by hsequeda** [comment]
I mean, when u run `gopls check` that error isn't detected.

**Comment by hsequeda** [comment]
ok, solved, was a local error.
