### ISSUE TITLE
x/exp/apidiff: incorrect behaviour with user defined type constraints

### ISSUE THREAD

**Issue by MadhavJivrajani** [golang/go#60911]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.
Also reproducible with `master`.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mjivrajani/Library/Caches/go-build"
GOENV="/Users/mjivrajani/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/mjivrajani/gocode/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/mjivrajani/gocode"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.20.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/r7/f6kyp7vs0sv90105pjh1t8340000gp/T/go-build3338208334=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

We run `apidiff` as part of our CI in [kubernetes/utils](https://github.com/kubernetes/utils).
Recently https://github.com/kubernetes/utils/pull/243 was merged which introduced a type constraint called `ordered`.
(`comparable` is what was hoped to be used but since we weren't able to bump to go1.20 back then, we couldn't use it just yet)

`apidiff` ran successfully in the CI for that PR since it was a new and compatible addition, and hence deemed to be compatible.
However, it now fails to run against itself.
Reproducer:
```
git clone git@github.com:kubernetes/utils.git && cd utils
make verify-apidiff
```

### What did you expect to see?
`apidiff` runs successfully when run against no new changes.

### What did you see instead?

```
FAIL: k8s.io/utils/set contains incompatible changes:
- KeySet: changed from func(map[E]A) Set[E] to func(map[E]A) Set[E]
- New: changed from func(...E) Set[E] to func(...E) Set[E]
- Set: changed from Set[E ordered] to Set[E ordered]
```

### Potential Reason

I see that `apidiff` was recently updated to support generics: https://go-review.googlesource.com/c/exp/+/411076
However, as part of this change, we check that 2 named types have an identical type parameter list:
https://github.com/golang/exp/blob/2e198f4a06a1643ba6d13f4823bebb46216bcb41/apidiff/correspondence.go#L209-L211

The issue that arises here is that since constraints are considered named types, and we are using `types.Identical` for comparison here, they are defined to be identical if they are part of the same type declaration, and since we now essentially end up with the same type but in two different packages (`old` and `new`), and hence are not identical. 
See here: https://go.dev/play/p/z4AHbUXWA3D

However, on the other hand, if we used something like `comparable` as the type constraint instead of defining our own, things work fine since we no longer end up in the 2 package situation. 
See here: https://go.dev/play/p/4X2t3TOx-UR

**Comment by ianlancetaylor** [comment]
CC @jba

**Comment by jba** [comment]
Thank you for the clear reproduction.

**Comment by MadhavJivrajani** [comment]
Thank you @jba!
Verified that this fixes the issue:
```
❯ make verify-apidiff
GO111MODULE=on ./hack/verify-apidiff.sh -r master
Inspecting API of master...
Comparing with master...
Ignoring internal package k8s.io/utils/internal/third_party/forked/golang/golang-lru
Ignoring internal package k8s.io/utils/internal/third_party/forked/golang/net
❯ echo $?
0
```
