### ISSUE TITLE
affected/package: Compiler issue

### ISSUE THREAD

**Issue by harshit-gupta-glean** [golang/go#60910]
### What version of Go are you using (`go version`)? 

<pre>
$ go version
go version go1.17.13 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes 

https://go.dev/play/p/lnqhhj-qO0G

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="arm64"
GOBIN="/Users/harshitgupta/go/bin"
GOCACHE="/Users/harshitgupta/Library/Caches/go-build"
GOENV="/Users/harshitgupta/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/harshitgupta/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/harshitgupta/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go@1.17/1.17.13/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go@1.17/1.17.13/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.17.13"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/my/sdgzm_ps1_l6ww479nzwwblm0000gn/T/go-build1954872321=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
Playground link : https://go.dev/play/p/lnqhhj-qO0G 

The var value of one of the var `cShouldNotChange` is changing whereas it should not change

### What did you expect to see?
in https://go.dev/play/p/lnqhhj-qO0G , var `cShouldNotChange` is changing whereas it should not change

### What did you see instead?
Var `cShouldNotChange` got mutated.

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.
