### ISSUE TITLE
cmd/go/internal/modfetch/codehost: tests failing on Plan 9 because "git" is a minimal shell script

### ISSUE THREAD

**Issue by millerresearch** [golang/go#60923]
The plan9-386 builder has been failing since CL [491659](https://go-review.googlesource.com/c/go/+/491659), which introduced or re-enabled tests which depend on `git`. The `git` command on Plan 9  is not the real thing but a minimal shell script, originally written to provide just enough functionality for `go get` to work. (See issue #29640.)

The new tests in this package are skipped if there's no `git` executable, but they should also be skipped on Plan 9, where the `git` executable doesn't support the subcommands needed in the tests.

Alternatively, maybe the pseudo `git` should now be removed from the plan9-386 and plan9-amd64 builders, since it's not needed by the current version of `go get`. I removed the pseudo `git` on the plan9-arm builders some years ago, with apparently no ill effect. @0intro, what do you think?

**Comment by bcmills** [comment]
One way or another, it would certainly simplify a lot of tests if we could rely on the property that a `git` found via `exec.LookPath` supports all of the same commands as the mainline `git` tool.

**Comment by millerresearch** [comment]
> One way or another, it would certainly simplify a lot of tests if we could rely on the property that a `git` found via `exec.LookPath` supports all of the same commands as the mainline `git` tool.

I think that property is only likely to be satisfied vacuously on Plan 9, _ie_ by deleting or renaming the pseudo `git`.

Apart from its use in `go get` (now obsolete), there appear to be some other places the pseudo `git` is helpful, for example in finding `go version` for a development version of go in a git repository.

**Comment by 0intro** [comment]
I've just renamed the `git` tool on the `plan9-386` and `plan9-amd64` builder.

**Comment by millerresearch** [comment]
> I've just renamed the `git` tool on the `plan9-386` and `plan9-amd64` builder.

Thanks - "All tests passed" on plan9-386.
