### ISSUE TITLE
x/tools/gopls: reduce CPU while typing (better cancellation)

### ISSUE THREAD

**Issue by findleyr** [golang/go#60926]
While profiling in large repos recently, I think there is more we can do to reduce CPU during typing:

- Build import maps as part of the metadata graph, and persist them: for large repos the cost of rebuilding maps for importing can be very high (as expensive as type-checking!)
- Improve cancellation while building package handles
- Optimize rebuilding typerefs, by moving the "quickparse" algorithm behind a cache.

There may be more. Experimentally, this seemed to reduce cpu while mashing on the keyboard by 50%.

We should also come up with a good benchmark: something like "press a key every N milliseconds for a duration of M seconds, and then measure total CPU used by the gopls process".

CC @adonovan

**Comment by adonovan** [comment]
> for large repos the cost of rebuilding maps for importing can be very high (as expensive as type-checking!)

This wasn't confirmed by our little experiments just now (a 30s CPU profile of interactively mashing the keyboard in a kubernetes source file). I did notice gob decoding in analysis (cache.mustDecode) at 8%, and string formatting in analysisNode.cacheKey at 3%.

The total CPU was 7s, which over 30s means a load average of 25%, which seems pretty reasonable while mashing the keyboard.

**Comment by findleyr** [comment]
I think we've made some good progress on this, and the gains are getting smaller, so I'll close. If we have specific ideas for future optimization, we can open a separate issue.
