### ISSUE TITLE
x/website: Random greeting tutorial docs outdated

### ISSUE THREAD

**Issue by mattcen** [golang/go#60930]
This commit: https://github.com/golang/website/commit/f734127 removes some code from the tutorial, but  fails to remove the explanation for that code: https://github.com/golang/website/blob/cf517d8748f3d07b8a57fbee59d056c25b447bef/_content/doc/tutorial/random-greeting.html#L94-L100

**Comment by seankhliao** [comment]
Duplicate of #60627
