### ISSUE TITLE
cmd/dist,cmd/go: no such tool "dist" running `go tool dist list`

### ISSUE THREAD

**Issue by marten-seemann** [golang/go#60939]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21rc2 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/marten/Library/Caches/go-build'
GOENV='/Users/marten/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/marten/src/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/marten/src/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/Users/marten/bin/go1.21ex'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/Users/marten/bin/go1.21ex/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.21rc2'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/q0/b5ynf00142l7bl9sp8y098zr0000gn/T/go-build2814318498=/tmp/go-build -gno-record-gcc-switches -fno-common'
</pre></details>

### What did you do?

I use `go tool dist list` to get the architectures available for cross-compilation ([CI workflow](https://github.com/quic-go/quic-go/blob/master/.github/workflows/cross-compile.yml)).

### What did you expect to see?

The list of architectures available for cross-compilation. This worked fine in Go 1.20.x.

### What did you see instead?

```
❯ go tool dist list
go: no such tool "dist"
```

**Comment by prattmic** [comment]
cc @rsc

**Comment by bcmills** [comment]
Our current thinking is that shipping `go tool dist` is excessive, but breaking scripts that rely on `go tool dist list` is also unfortunate. Perhaps we can allow `cmd/go` to impersonate `dist` when the command is `go tool dist list` and the `dist` tool isn't present.

**Comment by dmitshur** [comment]
Mentioning that there is a workaround that can be used with go1.21rc2:

```
~ $ go version
go version go1.21rc2 darwin/arm64
~ $ go tool dist list
go: no such tool "dist"
~ $ GOROOT=$(go env GOROOT) go run cmd/dist list          
aix/ppc64
android/386
android/amd64
android/arm
[...]
```

It is more verbose than just `go tool dist list`, and slightly slower since go builds the dist command on the fly. But that wouldn't be noticeable in the context of a CI job.
