### ISSUE TITLE
x/website: doc/install: add download instructions into numbered steps 

### ISSUE THREAD

**Issue by varshneydevansh** [golang/go#60941]
### What is the URL of the page with the issue?

[https://go.dev/doc/install#](https://go.dev/doc/install#)

### What is your user agent?

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

### Screenshot

![image](https://github.com/golang/go/assets/20411128/9b66a3ff-a06e-41ce-bde4-8c5f04258b6f)

![image](https://github.com/golang/go/assets/20411128/9cae029f-dd47-47fb-917f-6b51b495d5de)

### What did you do?

It's not an error but felt like a little inconsistent for someone if they are coming for the first time to download and install Golang.

If you are coming from the go.dev homepage, and you press the Download button, then it's landing you to the [https://go.dev/dl/]( https://go.dev/dl/) which seems fine. Then, if you go to the installation instructions from that page, that also seems fine (Refer to the first Screenshot)

But, if you are coming from the [https://go.dev/doc/](https://go.dev/doc/) or directly hitting the link [https://go.dev/doc/install#](https://go.dev/doc/install#) from the search engine page, then these instructions going to look a little confusing.

As, it's assuming we have already downloaded the Go binary release, as the first instruction starts with that.(Refer to the second Screenshot)

### What did you expect to see?
My suggestion is that we modify the first line on the [https://go.dev/dl/] (https://go.dev/dl/) page to obtain the binary release suitable for your system, and then follow the installation instructions.

And for the users who are coming from the [https://go.dev/doc/](https://go.dev/doc/) or directly hitting the link [https://go.dev/doc/install#](https://go.dev/doc/install#) from the search engine page, we can add the first instruction in the **Go Installation** as-

1.  Download the suitable binary release from the above button.(If you have already downloaded it, kindly move ahead with the following instructions)

Rest steps could remain the same.

It was the first time that I missed the very first thing, which was a download, as my focus went straight to the **Go Installation**. Although, I am doing installing binaries and programming for years, but I just felt it a little inconsistent from the perspective of a new user. As, I landed to https://go.dev/doc/install from an open-source contributing page. Particularly, the steps for installing on Linux.

**Comment by varshneydevansh** [comment]
Hi @seankhliao,

Thank you for correcting the title and tag, as it is my first issue. If this seems like a valid inconsistency with the instructions, I would love to contribute to this issue.

Regards.

**Comment by varshneydevansh** [comment]
Hi,

Is this the right place [https://github.com/golang/website/tree/master/_content/doc/install](https://github.com/golang/website/tree/master/_content/doc/install) to edit the **doc/install** page to add the required number step?

Do I have to edit the **source.html** file only?

**Comment by varshneydevansh** [comment]
Hi @seankhliao I have opened a PR https://github.com/golang/website/pull/229 for the numbered step instructions to eliminate the inconsistency.

**Comment by jamalc** [comment]
Thanks for highlighting this but we're currently redesigning the download and install flow internally.

**Comment by varshneydevansh** [comment]
Hi @jamalc, So should I close the PR and this issue?
