### ISSUE TITLE
x/telemetry/internal/counter: TestNewFile persistently failing on linux-amd64-wsl using Go 1.20 and Go tip

### ISSUE THREAD

**Issue by dmitshur** [golang/go#60966]
```
#!watchflakes
post <- pkg == "golang.org/x/telemetry/internal/counter" && test == "TestNewFile" && builder == "linux-amd64-wsl" && `days = 7`
```

The linux-amd64-wsl builder is persistently failing on TestNewFile in this package on Go 1.20 release branch and Go tip. Example failure:

```
--- FAIL: TestNewFile (0.00s)
    counter_test.go:164: GOOS linux GARCH amd64
    counter_test.go:220: 5: days = 7, want 7 < days <= 14
2023/06/23 21:08:22 closing /tmp/workdir-host-linux-amd64-wsl/tmp/TestRotate813491770/001/local/counter.test-devel-linux-amd64-2023-06-23.v1.count
FAIL
FAIL	golang.org/x/telemetry/internal/counter	0.128s
```

See https://build.golang.org/log/b96749f3606ddcbb735661cd819ea69e2dc17fb4 for an example log. More are visible at https://build.golang.org/?repo=golang.org%2fx%2ftelemetry.

Very similar to #60970.

CC @mengzhuo.

**Comment by bcmills** [comment]
It is worth noting that this builder is passing reliably on `release-branch.go1.19`. 🤔

**Comment by hyangah** [comment]
> It is worth noting that this builder is passing reliably on `release-branch.go1.19`. 🤔

The test has build tag go1.20 :-P Sent https://go-review.googlesource.com/c/telemetry/+/505722  to remove the build tag.
