### ISSUE TITLE
runtime/cgo: parallel calls from C to Go causes high mutex lock contention on system with large CPUs

### ISSUE THREAD

**Issue by cuonglm** [golang/go#60961]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.21-25e46693a1 Thu Jun 22 19:52:13 2023 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

See https://groups.google.com/g/golang-nuts/c/rgKT2ptyeGQ/m/7i6tnfuuBAAJ.

### What did you expect to see?

Program do not spend much time on lock/unlock.

### What did you see instead?

Half of the time on lock contention.

---

Here's slightly version of original program:

```
package main

/*
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

extern void c_call_go_get_value(uint8_t* key32, uint8_t *value32);

static inline void get_value(uint8_t* key32, uint8_t *value32) {
    uint8_t value[32];
    c_call_go_get_value(key32, value);
    memcpy(value32, value, 32);
}
*/
import "C"
import (
	"fmt"
	"runtime"
	"sync"
	"time"
	"unsafe"
)

func main() {
	numWorkers := runtime.NumCPU()
	fmt.Printf("numWorkers = %v\n", numWorkers)
	numTasks := 10_000_000
	tasks := make(chan struct{}, numTasks)
	for i := 0; i < numTasks; i++ {
		tasks <- struct{}{}
	}
	close(tasks)
	start := time.Now()
	var wg sync.WaitGroup
	wg.Add(numWorkers)
	for i := 0; i < numWorkers; i++ {
		go func() {
			defer wg.Done()
			for range tasks {
				_ = getValue([32]byte{})
			}
		}()
	}
	wg.Wait()
	fmt.Printf("took %vms\n", time.Since(start).Milliseconds())
}

func getValue(key [32]byte) []byte {
	key32 := (*C.uint8_t)(C.CBytes(key[:]))
	value32 := (*C.uint8_t)(C.malloc(32))
	C.get_value(key32, value32)
	ret := C.GoBytes(unsafe.Pointer(value32), 32)
	C.free(unsafe.Pointer(key32))
	C.free(unsafe.Pointer(value32))
	return ret
}

//export c_call_go_get_value
func c_call_go_get_value(key32 *C.uint8_t, value32 *C.uint8_t) {
	key := C.GoBytes(unsafe.Pointer(key32), 32)
	_ = key
	value := make([]byte, 32)
	for i := 0; i < len(value); i++ {
		*(*C.uint8_t)(unsafe.Pointer(uintptr(unsafe.Pointer(value32)) + uintptr(i))) = (C.uint8_t)(value[i])
	}
}
```

**Comment by dmitshur** [comment]
Thanks for reporting this and sending a CL.

Do you know if it's a performance regression was caused by changes in 1.21, or a pre-existing performance opportunity? That'll help determine if the fix can be considered for this release or should wait for 1.22 after the release freeze. Thanks.

**Comment by cuonglm** [comment]
> Thanks for reporting this and sending a CL.
> 
> 
> 
> Do you know if it's a performance regression was caused by changes in 1.21, or a pre-existing performance opportunity? That'll help determine if the fix can be considered for this release or should wait for 1.22 after the release freeze. Thanks.

This is not a regression, so should be for 1.22 cycle.
