### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by manuelcarriernunes** [golang/go#60987]
### What is the URL of the page with the issue?
 https://go.dev/doc/tutorial/getting-started
 
 
### What is your user agent?
 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

 
 
 
### Screenshot
 
![image](https://github.com/golang/go/assets/3910632/674166f3-f8cc-4a98-97d8-f628bddcd87d)

 
 
 
### What did you do?
 Ran `cd %HOMEPATH%` on Windows

 
 
 
### What did you expect to see?
 I expected not to get an error.
 
 
### What did you see instead?
![image](https://github.com/golang/go/assets/3910632/baa40c25-b775-48c8-ab0e-ff8267c0559a)

**Comment by rittneje** [comment]
Those instructions are written assuming you are using the regular Windows command shell (i.e., cmd.exe), where environment variables are surrounded by percent signs. If you want to use PowerShell, you will need to use its syntax instead (e.g., `$env:HOMEPATH`).
