### ISSUE TITLE
affected/package: runtime/internal/sys, len8tab redeclaration errors

### ISSUE THREAD

**Issue by pjmlp** [golang/go#60983]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21rc2 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/username/.cache/go-build'
GOENV='/home/username/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/username/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/username/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/opt/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/opt/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21rc2'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/username/projects/ppm2png/go/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build4081609926=/tmp/go-build -gno-record-gcc-switches'

</pre></details>

### What did you do?

Tried to compile one of my Go applications,

https://github.com/pjmlp/ppm2png/tree/main/go

### What did you expect to see?

To compile without errors.

### What did you see instead?

<pre>
# runtime/internal/sys
/opt/go/src/runtime/internal/sys/intrinsics_common.go:9:7: len8tab redeclared in this block
	/opt/go/src/runtime/internal/sys/intrinsics.go:76:7: other declaration of len8tab
/opt/go/src/runtime/internal/sys/intrinsics_common.go:32:6: Len64 redeclared in this block
	/opt/go/src/runtime/internal/sys/intrinsics.go:99:6: other declaration of Len64
/opt/go/src/runtime/internal/sys/intrinsics_common.go:50:7: m0 redeclared in this block
	/opt/go/src/runtime/internal/sys/intrinsics.go:117:7: other declaration of m0
/opt/go/src/runtime/internal/sys/intrinsics_common.go:51:7: m1 redeclared in this block
	/opt/go/src/runtime/internal/sys/intrinsics.go:118:7: other declaration of m1
/opt/go/src/runtime/internal/sys/intrinsics_common.go:52:7: m2 redeclared in this block
	/opt/go/src/runtime/internal/sys/intrinsics.go:119:7: other declaration of m2
/opt/go/src/runtime/internal/sys/intrinsics_common.go:55:6: OnesCount64 redeclared in this block
	/opt/go/src/runtime/internal/sys/intrinsics.go:122:6: other declaration of OnesCount64
/opt/go/src/runtime/internal/sys/intrinsics_common.go:86:6: LeadingZeros64 redeclared in this block
	/opt/go/src/runtime/internal/sys/intrinsics.go:153:6: other declaration of LeadingZeros64
/opt/go/src/runtime/internal/sys/intrinsics_common.go:89:6: LeadingZeros8 redeclared in this block
	/opt/go/src/runtime/internal/sys/intrinsics.go:156:6: other declaration of LeadingZeros8
/opt/go/src/runtime/internal/sys/intrinsics_common.go:92:6: Len8 redeclared in this block
	/opt/go/src/runtime/internal/sys/intrinsics.go:159:6: other declaration of Len8
/opt/go/src/runtime/internal/sys/intrinsics_common.go:101:6: Prefetch redeclared in this block
	/opt/go/src/runtime/internal/sys/intrinsics.go:200:6: other declaration of Prefetch
/opt/go/src/runtime/internal/sys/intrinsics_common.go:101:6: too many errors
</pre>

**Comment by seankhliao** [comment]
did you completely remove the previous installation before installing the current version?

**Comment by pjmlp** [comment]
You're right, it was my mistake when installing the RC, not everything was cleaned out.

It works as expected.

Closing the issue.

**Comment by craftizmv** [comment]
@pjmlp How did you completely clean the old installation

**Comment by proxfly** [comment]
> @pjmlp How did you completely clean the old installation

I just ran `rm -rf /usr/local/go`

**Comment by jq460494839** [comment]
> > @pjmlp How did you completely clean the old installation
> 
> I just ran `rm -rf /usr/local/go` on Linux

this fix my problem
