### ISSUE TITLE
syscall: EBADFD not defined for the wasip1 target

### ISSUE THREAD

**Issue by flavio** [golang/go#60998]
### What version of Go are you using (`go version`)?

```
go version go1.21rc2 linux/amd64
```

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

I tried to compile some code using the `spf13/afero` library to the wasip1 target

A simple reproducer can be found here:

https://go.dev/play/p/3KyfMD2DTUd

### What did you expect to see?

I expected the compilation to be successful

### What did you see instead?

The compilation failed with this error:

```
GOOS=wasip1 GOARCH=wasm go build -o main.wasm
# github.com/spf13/afero
../go/pkg/mod/github.com/spf13/afero@v1.9.5/const_win_unix.go:22:23: undefined: syscall.EBADFD
```

**Comment by flavio** [comment]
CC @johanbrandhorst: sorry about the direct mention. I'm pinging you since you are in charge of the WASI port, and I think this might be relevant for you

**Comment by ianlancetaylor** [comment]
There are lots of systems that don't define `EBADFD`.  Currently it seems to be defined only on Linux, Solaris, and Windows.  Is it needed for wasip1?  The package github.com/spf13/afero is already set up to use build tags for portability; perhaps we should instead adjust those build tags.

**Comment by flavio** [comment]
I can totally patch `github.com/spf13/afero` to make it work with wasip1.

I noticed `EBADFD` is defined inside of [wasi-libc](https://github.com/WebAssembly/wasi-libc), which is then used by [wasi-sdk](https://github.com/WebAssembly/wasi-sdk). However I don't know if this is a strong enough motivation to have Go define this error :woman_shrugging:

**Comment by ianlancetaylor** [comment]
I don't know much about wasi, but if the wasi C library does define and use `EBADFD`, then I'm OK with defining it in Go's syscall package.  Thanks.

**Comment by mknyszek** [comment]
It sounds like we just need a patch here, so I applied the "help wanted" label and moved it to NeedsFix. Thanks.
