### ISSUE TITLE
affected/package: go mod 

### ISSUE THREAD

**Issue by alistair-segment** [golang/go#61008]
### What version of Go are you using (`go version`)?
go version go1.20.4 darwin/amd64
<pre>

</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GOHOSTARCH="amd64"
GOHOSTOS="darwin"

</pre></details>

### What did you do?

go mod tidy/vendor/ etc. returns the following error when there is trailing whitespace in the path to main.go

github.com/.... : malformed import path "github.com/.... ": invalid char ' '

### What did you expect to see?
successful go tidy

### What did you see instead?

github.com/.... : malformed import path "github.com/.... ": invalid char ' '

**Comment by seankhliao** [comment]
working as intended.
as the error indicates, spaces aren't allowed.
