### ISSUE TITLE
mock: update repository documentation to reflect the current support status

### ISSUE THREAD

**Issue by willfaught** [golang/go#61017]
See https://github.com/golang/mock/pull/627#issuecomment-1605169998

We should either archive the repo, or update the readme to say PRs aren't being accepted.

We don't want contributors to have a bad experience contributing to Go like that.

**Comment by rsc** [comment]
We have been working with Uber to establish continuity for this tool. They are going to take over development at https://github.com/uber/mock, which only became official recently. I will update the README.

**Comment by willfaught** [comment]
CC @FlorianLoch. Perhaps Uber will accept your PR?

**Comment by FlorianLoch** [comment]
Thanks @willfaught, appreciate your effort!

**Comment by mbamber** [comment]
@rsc - out of interest, are there any reasons as to why this is no longer maintained by the Go team?
