### ISSUE TITLE
affected/package: net/http

### ISSUE THREAD

**Issue by Nu1i** [golang/go#61019]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.5 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

I user net/http wrote a test program.

client := &http.Client{}
request, err := http.NewRequest("POST", "http://...", strings.NewReader(data))
request.Header.Add("ReqTType", "something")
response, err := client.Do(request)

as up,server response me 400.
then i use wireshark capture the request
![image](https://github.com/golang/go/assets/38694534/8c11b9e4-a5d7-4e43-b6d0-c4306ceedcca)
the header i add "ReqTType" uppercase "T" became lowercase "t".

**Comment by seankhliao** [comment]
working as intended.
go uses a single canonical capitalization, http should be case insensitive
