### ISSUE TITLE
bytealg/equal_riscv64.s: memory unaligned access at `memequal` assembly

### ISSUE THREAD

**Issue by hero78119** [golang/go#61018]
### What version of Go are you using (`go version`)?

<pre>
1.21rc1
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
riscv64 arch 

</pre></details>

### What did you do?
a simple go program can reproduce this memory alignment problem on riscv64 platform

```golang
import (
	"bytes"
	"reflect"
	"unsafe"
)

func main() {
	var bytesa []byte
	bha := (*reflect.SliceHeader)(unsafe.Pointer(&bytesa))
	bha.Data = uintptr(0xd0000deadbfa2)
	bha.Len = 40
	bha.Cap = 40

	var bytesb []byte
	bhb := (*reflect.SliceHeader)(unsafe.Pointer(&bytesb))
	bhb.Data = uintptr(0xd0000deadbfb2)
	bhb.Len = 40
	bhb.Cap = 40

	bytes.Equal(bytesa, bytesb)
}
```

Build command
```
GOGC=off GOARCH=riscv64 go1.21rc1 build -tags=faketime -buildvcs=false -o demo -gcflags="-N -l" -ldflags '-memprofilerate 0'  demo.go
```

Memory unaligned starting at these lines https://github.com/golang/go/blob/13529cc5f443ef4e242da3716daa0032aa8d34f2/src/internal/bytealg/equal_riscv64.s#L54-L57
At these moment, X10, X11 register values as below 
```
...
X10: d0000deadbfa4
X11: d0000deadbfb4
...
```

It might be related to commit https://github.com/golang/go/commit/9552a1122f3334f6fa47c0cf718766af27255b84 the memory alignment in riscv64 which also fixed optimisation code. 

Only tested on GOARCH `riscv64`, not sure other arch platforms

### What did you expect to see?
memory address unaligned access should be avoided. 

### What did you see instead?
memory address unaligned happend at `memequal` `MOV` assembly code

**Comment by hero78119** [comment]
Below try to point out the logic error, please kindly help to check, thanks

https://github.com/golang/go/blob/go1.21rc2/src/internal/bytealg/equal_riscv64.s#L39-L40

```diff
- // Check one byte at a time until we reach 8 byte alignment.
- SUB	X9, X12, X12
+ // Check one byte at a time until we reach 32 byte alignment.
+ SUB	X9, X23, X9
+ SUB	X9, X12, X12
```

**Comment by randall77** [comment]
There is a fix in https://go-review.googlesource.com/c/go/+/500855 . Is that CL sufficient?

**Comment by mengzhuo** [comment]
Fixed on tip.
