### ISSUE TITLE
x/tools/gopls: collect editor kind information with telemetry

### ISSUE THREAD

**Issue by hyangah** [golang/go#61038]
* Counter: gopls/client:{vscode,vscodium,code-server,eglot,govim,neovim,coc.nvim,sublimetext,other}
* Title: Editor Distribution
* Description: measure editor distribution for gopls users.
* Type: partition
* Issue: go.dev/issues/61038
* Program: golang.org/x/tools/gopls

### Why?

We want to utilize this information when prioritizing editor-specific specialization and features.

### Does it carry sensitive user information?

No.

### How?

Some LSP clients send the name of editor in the initialization message's ClientInfo field.
Increment the counter corresponding to the field's value.

note: The default is 'local' which does not send any data to the telemetry server. Users must opt-in explicitly.

cc @golang/tools-team

**Comment by hyangah** [comment]
Updated to "gopls/client:..." cc @jamalc

**Comment by pjweinb** [comment]
add gopls/clietn:vscode-insiders perhaps?

**Comment by hyangah** [comment]
@pjweinb https://github.com/golang/go/issues/62214 proposes it.
