### ISSUE TITLE
affected/package: using textproto.Cmd(line) shows line with NOVERB or MISSING on the networkside

### ISSUE THREAD

**Issue by go-dev-joint** [golang/go#61044]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.20.5

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
debian 11 amd64

### What did you do?
sending this formated string https://github.com/go-dev-joint/test_textproto_client_server/blob/main/test_textproto_client.go#L41
from the client to the server with "func response_cm2" https://github.com/go-dev-joint/test_textproto_client_server/blob/main/test_textproto_client.go#L188 , uses 'textproto.Cmd(line)' fails. 

the string in tcpdump shows as 'TEST=cm2 <_anyB3.4976$2%!(NOVERB)' and server receives gibberish..
sending string with this '.Cmd("%s", line)' "func response_cm1" https://github.com/go-dev-joint/test_textproto_client_server/blob/main/test_textproto_client.go#L188182 works..  

[raw client.log](https://raw.githubusercontent.com/go-dev-joint/test_textproto_client_server/main/client.log)
[raw server.log](https://raw.githubusercontent.com/go-dev-joint/test_textproto_client_server/main/server.log)
[raw tcpdump.log](https://raw.githubusercontent.com/go-dev-joint/test_textproto_client_server/main/tcpdump.log)

this my fault or bug in go? 
more strings to test are in 
[client.go](https://github.com/go-dev-joint/test_textproto_client_server/blob/main/test_textproto_client.go#L42):L42 

Thank you all

**Comment by seankhliao** [comment]
working as intended, the Cmd takes a format string, and your string has an unescaped percent sign.
