### ISSUE TITLE
cmd/go/internal/vcs: ignores selected branch when getting most recent commit

### ISSUE THREAD

**Issue by nreilly** [golang/go#61045]
The [current go source](https://cs.opensource.google/go/go/+/refs/heads/master:src/cmd/go/internal/vcs/vcs.go;drc=8008c0840ff09c492434e67de443ee478957fb8f;l=341
) for getting the most recent commit hash doesn't appear to consider the currently active branch.

### What version of Go are you using (`go version`)?

<pre>
go version go1.20.5 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOOS="darwin"

</pre></details>

### What did you do?

Compiled code from a branch, the code uses debug.ReadBuildInfo() to get information about the branch/commit being used for the build. This hash was not the most recent in the branch being used, it was the most recent commit in the repository.

### What did you expect to see?
The most recent commit in the currently used branch

### What did you see instead?
The most recent commit in the repository

**Comment by seankhliao** [comment]
can you please include a test program and instructions to reproduce the issue

**Comment by bcmills** [comment]
Or are you talking about `go get` in GOPATH mode in particular? If so, please see #60915, which proposes to maintain support for `go build` but not `go get` in that mode.
