### ISSUE TITLE
proposal: affected/package: syscall  How to transfer syscall to libc on Linux?

### ISSUE THREAD

**Issue by yangboyd** [golang/go#61057]
Looks like begin with this step: "mksyscall.pl -libc -tags linux,amd64   syscall_linux.go  syscall_linux_amd64.go > zsyscall_linux_amd64.go"
What else need to do?

**Comment by mengzhuo** [comment]
Not an issue, closed.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
