### ISSUE TITLE
cmd/dist,x/build/cmd/coordinator: test logs missing errors or final status

### ISSUE THREAD

**Issue by bcmills** [golang/go#61069]
```
#!watchflakes
post <- repo == "go" && !(log ~ `^(All tests passed|FAIL|build failed|fatal error:|panic:|WARNING: DATA RACE|go tool dist: |(Test .* ran over .* limit)|([^ ]*make.bash: .*(error|fault)))`)
```

(pulled out from https://github.com/golang/go/issues/57995#issuecomment-1612281933)

**Comment by kolyshkin** [comment]
I _think_ that @gopherbot adds new comments to the wrong issues.

**Comment by cherrymui** [comment]
As we now switched to LUCI, which print things differently, we should close this and stop many unrelated bugs being matched here.
