### ISSUE TITLE
encoding/json: json.Marshal()  doesn't produce right result

### ISSUE THREAD

**Issue by DiJester** [golang/go#61062]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Not test yet

### What operating system and processor architecture are you using (`go env`)?
MacOS
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

I run the code below
```go
func main() {
	data := []byte{110, 117, 108, 108}

	list := []string{}

	err := json.Unmarshal(data, &list)
	if err != nil {
		fmt.Println(err)
	}

	if len(list) == 0 {

		fmt.Printf("list is: %+v \n\r", list)
		listData, err := json.Marshal(list)
		if err != nil {
			fmt.Println(err)
		}
		fmt.Printf("list marshalled bytes are: %+v \n\r", listData)

	}

}

Why the unmarshalled listData is 
[110 117 108 108] , but not [91, 93]

```

### What did you expect to see?
The marshlled bytes for list should be [91, 93]

### What did you see instead?
The marshlled bytes for list is  [110 117 108 108]

**Comment by Jorropo** [comment]
`110 117 108 108` is literally the string `null`.
You are parsing `null` into a `[]string` which gives you `[]string(nil)`, you are then serializing the `[]string(nil)` you have to the json object: `null`.

Everything in your example works like expected.

**Comment by DiJester** [comment]
> This seems to be working as documented (https://pkg.go.dev/encoding/json#Marshal):
> 
> > Array and slice values encode as JSON arrays, except that … a nil slice encodes as the null JSON value.

Thank you for your answers.
