### ISSUE TITLE
cmd/go: GOTOOLCHAIN=<name>+[auto|path] is incorrectly rejected as "invalid minimum toolchain"

### ISSUE THREAD

**Issue by dmitshur** [golang/go#61068]
The [Go toolchain selection](https://go.dev/doc/toolchain#select) section in https://go.dev/doc/toolchain documents that GOTOOLCHAIN may have "\<name\>+auto" or "\<name\>+path" form. These are currently rejected in go1.21rc2 and at tip:

```bash
$ go version
go version devel go1.21-da5d8fdd0c Thu Jun 29 15:35:27 2023 +0000 darwin/arm64
$ GOTOOLCHAIN=go1.21rc2+auto go version 
go: invalid GOTOOLCHAIN "go1.21rc2+auto": invalid minimum toolchain "go1.21rc2"
```

A quick look at the code suggests at least part of the problem is that `gover.FromToolchain` is being called with the wrong argument:

https://github.com/golang/go/blob/03cd8a7b0e47f2141a1dbdad9fdce175942d5515/src/cmd/go/internal/toolchain/select.go#L132-L134

Instead of the intended `gover.FromToolchain(min)`. I haven't looked if there's more to it or not.

CC @rsc, @bcmills, @matloob.

**Comment by iwdgo** [comment]
The reported behavior is explicitly described in the code documentation. With something like "go1.21rc2",  `x` contains "rc2" and an empty version is returned. An empty version triggers the error message. One could argue that go1.21 does not exist before go1.21rc2 restricting this case to somebody using the patch (rc) rather then the release.

https://github.com/golang/go/blob/03cd8a7b0e47f2141a1dbdad9fdce175942d5515/src/cmd/go/internal/gover/gover.go#L168-L175

Good to know, as go1.21 is not released, a dev version is returned.
```
$ GOTOOLCHAIN=go1.21+auto goissue version
go version devel go1.21-5b72f45dd1 Fri Jun 30 22:02:00 2023 +0000 windows/amd64
```

**Comment by dmitshur** [comment]
@iwdgo That snippet talks about "prereleases (alpha, beta, rc) for patch releases", which isn't relevant here. It's true that `GOTOOLCHAIN=go1.20.5rc3+auto` shouldn't work, but this bug is about `GOTOOLCHAIN=go1.20.5+auto` not working even though it should.

<details><br>

```sh
# Works as expected without +auto suffix.
$ GOTOOLCHAIN=go1.20.5 go version
go version go1.20.5 darwin/arm64
$ GOTOOLCHAIN=go1.20rc3 go version 
go version go1.20rc3 darwin/arm64

# Fails to work with +auto suffix.
$ GOTOOLCHAIN=go1.20.5+auto go version
go: invalid GOTOOLCHAIN "go1.20.5+auto": invalid minimum toolchain "go1.20.5"
$ GOTOOLCHAIN=go1.20rc3+auto go version
go: invalid GOTOOLCHAIN "go1.20rc3+auto": invalid minimum toolchain "go1.20rc3"
```

</details>
