### ISSUE TITLE
supporting generic Type for "Type alias"

### ISSUE THREAD

**Issue by fengyeall111** [golang/go#61083]
### go env
go version go1.20.5 linux/amd64
### What operating system and processor architecture are you using (`go env`)?
openEuler
### What did you do?
write code like this:
```
type MidFunc[T any] func(T, MidFunc[T])
type Handler[T any] func(T)

type Processor[T any] interface {
	Use(midFunc MidFunc[T])
	Handler[T]
}

type msgProcessor[T any] struct {
	mid []MidFunc[T]
	Handler[T]
}
func NewMsgProcessor[T any](handler Handler[T]) Processor[T] {
	res := &msgProcessor[T]{
		Handler: handler,
	}
	return res
}

// Use not concurrent safely method
func (m *msgProcessor[T]) Use(midFunc MidFunc[T]) {
	m.mid = append(m.mid, midFunc)
}
```
### What did you expect to see?
the  code is correct and can be compiled

### What did you see instead?
can not build the code:
`cannot use type Processor[T] outside a type constraint: interface contains type constraints`
·```
// MisplacedConstraintIface occurs when a constraint-type interface is used
// outside of constraint position.
```
I'm confused about the lack of support for generic alias recognition. Is there some conideration?

**Comment by seankhliao** [comment]
This is not an alias issue, it's the same reason you can't have `var x Processor[T]`.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
