### ISSUE TITLE
runtime: NumCPU returns 0 on Solaris (gccgo)

### ISSUE THREAD

**Issue by calmh** [golang/go#6109]
<pre>What steps will reproduce the problem?

Getting the value of runtime.NumCPU().

<a href="http://play.golang.org/p/cuaf2ZHLIx">http://play.golang.org/p/cuaf2ZHLIx</a>

What is the expected output?

The number of processor cores installed in the machine, including hyperthreading if
enabled (eight, in my specific case).

What do you see instead?

Zero.

Which compiler are you using (5g, 6g, 8g, gccgo)?

Gccgo.

Which operating system are you using?

SunOS zlogin2.nym.se 5.11 joyent_20130808T195337Z i86pc i386 i86pc Solaris

(i.e. latest Illumos)

Which version are you using?  (run 'go version')

Gccgo in gcc 4.7.2.</pre>

**Comment by ianlancetaylor** [comment]
No reply, so closing.
