### ISSUE TITLE
affected/package: 

### ISSUE THREAD

**Issue by Kazzyman** [golang/go#61133]
### What version of Go are you using (`go version`)?
version go1.20.5 windows/amd64
<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
failingString := "µs" // micro seconds 
fmt.Fprintf(filehandle, "Micro Seconds should look like this: µs and this: %s", failingString)

### What did you expect to see?
Micro Seconds should look like this: µs and this: µs 

### What did you see instead?
Micro Seconds should look like this: ┬╡s and this: ┬╡s

**Comment by ianlancetaylor** [comment]
You need to configure your terminal to display UTF-8 characters.  Exactly how to do this will depend on what terminal you are using.

Closing because there is nothing we can change in Go to fix this.  For questions please use a forum; see https://go.dev/wiki/Questions.
