### ISSUE TITLE
Go extension not working

### ISSUE THREAD

**Issue by Fishyva** [golang/go#61134]
I recently got a new MacBook and my go extension is not working its not auto importing packages after save nor is it suggesting intellisense.
<img width="1707" alt="Screenshot 2023-06-30 at 10 41 41 PM" src="https://github.com/golang/go/assets/97076661/a82ff88d-ad99-466b-8054-92d836afb4c7">

**Comment by shani34** [comment]
I think you need to install some plugins for that....Or you can manually import the packages and then you can do **go mod tidy**  to sync dependencies.

**Comment by Fishyva** [comment]
> I think you need to install some plugins for that....Or you can manually import the packages and then you can do **go mod tidy** to sync dependencies.

The thing on my old MacBook all the basic package would auto suggest while I'm typing it also what about the error at the bottom right corner

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
