### ISSUE TITLE
x/crypto/ssh: MAC orders

### ISSUE THREAD

**Issue by drakkan** [golang/go#61138]
This [commit](https://github.com/golang/crypto/commit/16222386f4de802a3c27c1714b0bcc28c0fd5397) added support for `hmac-sha2-512-etm@openssh.com` which is a good addition. But the mac order is relevant, now `hmac-sha2-512-etm@openssh.com` is the preferred MAC.

Since sha256 is more optimized than sha512 in Go and is secure enough, I think we should prefer sha256 based MAC algorithms.

**Comment by seankhliao** [comment]
cc @golang/security
