### ISSUE TITLE
x/vuln: -v flag is not recognized in v0.2.0

### ISSUE THREAD

**Issue by chorin1** [golang/go#61144]
### What version of Go are you using (`go version`)?
go1.20.5

### Does this issue reproduce at the latest version of golang.org/x/vuln?
Yes

### What operating system and processor architecture are you using (`go env`)?
arm64 / darwin
does also reproduce on ubuntu

### What did you do?
```
go install golang.org/x/vuln/cmd/govulncheck@latest
${GOPATH}/bin/govulncheck -v ./...
```
Gives the error
`flag provided but not defined: -v`

```
go install golang.org/x/vuln/cmd/govulncheck@v0.1.0
${GOPATH}/bin/govulncheck -v ./...
```

works as expected

### What did you expect to see?
Retain the same behavior as before, if this is intended the change does not appear in the changelog nor in the [official page](https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck#hdr-Flags)

**Comment by ianthehat** [comment]
This was replaced by the more flexible `-show=traces`
