### ISSUE TITLE
runtime: callback memory error 

### ISSUE THREAD

**Issue by mainjzb** [golang/go#61147]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.5 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\mainj\AppData\Local\go-build
set GOENV=C:\Users\mainj\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\mainj\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\mainj\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.20.5
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\mainj\AppData\Local\Temp\go-build1190511740=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

I want call C++ dll that has C API , the one API has callback function  as parameter. 
when I alloc memory in callback funtion , my go program will exit. 

```
func MyCallBack() uintptr {
	b := make([]byte, 1024*1024)
	_ = b

	printMemUsage()
	return 0
}

func printMemUsage() {
	var m runtime.MemStats
	runtime.ReadMemStats(&m)
	fmt.Printf("Alloc = %v MiB\n", m.Alloc/1024/1024)
}
func main(){
    dll := MustLoadDLL("xx.dll")
    t := syscall.NewCallback(MyCallBack)
    cFunc = nfapi.MustFindProc("cFunc")

    type EH struct {
        callback uintptr
    }
    eh := EH{t}

    cFunc.Call(uintptr(unsafe.Pointer(&_eh)))
}
```

### What did you expect to see?

The program should not exit. 

### What did you see instead?
the output : 
```
Alloc = 1 MiB
Alloc = 2 MiB
Alloc = 3 MiB
Alloc = 4 MiB
Alloc = 1 MiB
Alloc = 2 MiB
Alloc = 3 MiB
Alloc = 4 MiB
Alloc = 1 MiB
Alloc = 2 MiB
Alloc = 3 MiB
Alloc = 4 MiB

exit status 0xc0000005
```

I see the Task Manager the process memroy increate to 8MB , process will exit in any way .

**Comment by mainjzb** [comment]
I try use go version `1.19.10` , It's work fine. 
maybe only `1.20` version bug

**Comment by ianlancetaylor** [comment]
Can you show us a complete standalone program that demonstrates the problem?

**Comment by mainjzb** [comment]
https://github.com/mainjzb/go1.20.5_error 
I upload my mini case.

**Comment by mainjzb** [comment]
#59724 Perhaps it's a related issue
I try  these go version all will exit with 0xc0000005
1.18.10
1.19.10
 1.20.5
It's seem about GC break stack and heap
