### ISSUE TITLE
plugin: plugin was built with a different version of package internal/goarch

### ISSUE THREAD

**Issue by pohly** [golang/go#61150]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21rc2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes. It still worked with Go 1.20.4.

### What operating system and processor architecture are you using (`go env`)?

Debian GNU/Linux 10 (buster), amd64

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/pohly/.cache/go-build'
GOENV='/home/pohly/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/nvme/gopath/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/nvme/gopath'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/nvme/gopath/go-1.21rc2'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/nvme/gopath/go-1.21rc2/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21rc2'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/nvme/gopath/src/github.com/pohly/go-plugin/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2784042289=/tmp/go-build -gno-record-gcc-switches'
</pre></details>

### What did you do?

In Kubernetes, we build golangci-lint and a plugin for it inside the [same Go environment](https://github.com/kubernetes/kubernetes/blob/0a82bdbfdb1b8dd644d242b39a257d14fa5bf6b0/hack/verify-golangci-lint.sh#L142-L145). That worked with Go 1.20. When [trying to upgrade to 1.21rc2](https://github.com/kubernetes/kubernetes/pull/118996), plugin loading fails with `Unable to load custom analyzer logcheck:../_output/local/bin/logcheck.so, plugin.Open(\"/nvme/gopath/src/k8s.io/kubernetes/_output/local/bin/logcheck\"): plugin was built with a different version of package encoding"`.

This only fails on my desktop. It fails differently ([for other reasons](https://gophers.slack.com/archives/CS0TBRKPC/p1688365821502669?thread_ts=1686144370.506279&cid=CS0TBRKPC)) in the Kubernetes CI. 

Here is a simple reproducer: https://github.com/pohly/go-plugin/tree/master

```console
go-plugin$ go version
go version go1.21rc2 linux/amd64
go-plugin$ make  clean all
rm -f main plugin.so
go build -o main .
go build -buildmode=plugin -o plugin.so ./plugin
go-plugin$ ./main 
loading plugin: plugin.Open("./plugin"): plugin was built with a different version of package internal/goarch
```

### What did you expect to see?

Plugin should load.

### What did you see instead?

`plugin was built with a different version of package` (which specific package depends on the plugin)

**Comment by MadhavJivrajani** [comment]
Hmm
I can't seem to reproduce this on `darwin/amd64`
```
❯ go version
go version go1.21rc2 darwin/amd64
❯ make clean all
rm -f main plugin.so
go build -o main .
go build -buildmode=plugin -o plugin.so ./plugin
❯ rm -f main plugin.so
❯ go build -o main .
❯ go build -buildmode=plugin -o plugin.so ./plugin
❯ ./main
❯ echo $?
0
```

**Comment by pohly** [comment]
It's also okay on my Debian 11 (bullseye) installation.

**Comment by seankhliao** [comment]
it also works in a debian buster container

**Comment by pohly** [comment]
What information can I provide to narrow down why it fails now? The exact same environment worked before I switched to Go 1.21rc2.

**Comment by pohly** [comment]
I can go back and forth between the two Go installations and one works while the other doesn't.

**Comment by seankhliao** [comment]
some way for someone else to actually reproduce it.
`go version -m <file>` on both?
build logs with `-a -x` for both?
zip up the files and upload them?

**Comment by pohly** [comment]
It seems to depend on the content of my $HOME. A test account on the desktop works, and so does my normal user when (temporarily) replacing $HOME with an empty directory. Let's see...

It turned out to be the content of `$HOME/.cache/go-build`. After removing that, it started to work.

Now that I have wiped it, I can no longer reproduce the issue. Feel free to close the issue. I still think that this shouldn't have happened, but I understand that it's close to impossible to root cause now.
