### ISSUE TITLE
net: "cgoAvailable redeclared in this block" when using "-tags:netgo", Windows and go 1.21rc2

### ISSUE THREAD

**Issue by neclepsio** [golang/go#61153]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21rc2 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\---\AppData\Local\go-build
set GOENV=C:\Users\---\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=c:\---\Go-Modules\pkg\mod
set GONOPROXY=neclepsio.example/*
set GONOSUMDB=neclepsio.example/*
set GOOS=windows
set GOPATH=c:\Ignazio\Personale\Go-Modules
set GOPRIVATE=neclepsio.example/*
set GOPROXY=direct
set GOROOT=c:\Ignazio\Lavoro\IgnPack\Go\go1.21rc2
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=c:\---\go1.21rc2\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.21rc2
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=---
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=-Wno-stringop-overflow
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\---\AppData\Local\Temp\go-build2402352097=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

    package main

    import (
    	"fmt"
    	"net"
    )
    
    func main() {
    	fmt.Println(net.FlagUp)
    }

Compiled with:

    go build -tags netgo

### What did you expect to see?

No error.

### What did you see instead?

    c:\---\go1.21rc2\src\net\lookup_windows.go:20:7: cgoAvailable redeclared in this block
            c:\---\go1.21rc2\src\net\cgo_stub.go:19:7: other declaration of cgoAvailable

**Comment by mateusz834** [comment]
Thanks for the report, there is a issue with build tags after [CL 487196](https://go.dev./cl/487196)

**Comment by mateusz834** [comment]
This issue also applies to plan9:
```
[mateusz@arch src (net-restrict-cgo-stub-to-unix)]$ GOOS=plan9 go test net -tags netgo
# net [net.test]
net/lookup_plan9.go:19:7: cgoAvailable redeclared in this block
        net/cgo_stub.go:20:7: other declaration of cgoAvailable
FAIL    net [build failed]
FAIL
```

**Comment by shenwei356** [comment]
I just  also met  this  issue on Linux, doing cross-compile  with 

    CGO_ENABLED=0 gox -os="windows darwin linux" -arch="386 amd64 arm64" -tags netgo -ldflags '-w -s' -asmflags '-trimpath'

Error:

```
--> windows/386 error: exit status 1
Stderr: # net
/usr/local/go/src/net/lookup_windows.go:20:7: cgoAvailable redeclared in this block
        /usr/local/go/src/net/cgo_stub.go:19:7: other declaration of cgoAvailable

--> windows/amd64 error: exit status 1
Stderr: # net
/usr/local/go/src/net/lookup_windows.go:20:7: cgoAvailable redeclared in this block
        /usr/local/go/src/net/cgo_stub.go:19:7: other declaration of cgoAvailable

```

**Comment by mateusz834** [comment]
@shenwei356 it is already fixed on gotip
