### ISSUE TITLE
x/vuln: outdated govulncheck documentation

### ISSUE THREAD

**Issue by dB2510** [golang/go#61152]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.5 darwin/arm64
</pre>

### Does this issue reproduce at the latest version of golang.org/x/vuln?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
Executed the following commands based on the latest documentation: https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck
```
go install golang.org/x/vuln/cmd/govulncheck@v0.2.0
govulncheck -v -test ./...
```

### What did you expect to see?

```
govulncheck is an experimental tool. Share feedback at https://go.dev/s/govulncheck-feedback.

Using go1.20.5 and govulncheck@v0.2.0 with
vulnerability data from https://vuln.go.dev (last modified 2023-06-26 16:56:57 +0000 UTC).

Scanning your code and 638 packages across 140 dependent modules for known vulnerabilities...
No vulnerabilities found.
```

### What did you see instead?

```
flag provided but not defined: -v
Govulncheck reports known vulnerabilities in dependencies.

Usage:

	govulncheck [flags] [patterns]
	govulncheck -mode=binary [flags] [binary]

  -C dir
    	change to dir before running govulncheck
  -db url
    	vulnerability database url (default "https://vuln.go.dev/")
  -json
    	output JSON
  -mode string
    	supports source or binary (default "source")
  -scan-level string
    	set the scanning level desired, one of module, package or symbol (default "symbol")
  -show list
    	enable display of additional information specified by list
  -tags list
    	comma-separated list of build tags
  -test
    	analyze test files (only valid for source mode)

For details, see https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck.
flag provided but not defined: -v
```

**Comment by dB2510** [comment]
Hi @julieqiu @ianthehat 👋 

Looks like govulncheck [documentation](https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck#hdr-Flags) still mentions about `-v` flag while it was replaced with `-show` in this [issue](https://github.com/golang/go/issues/59833).

**Comment by julieqiu** [comment]
Thank you @dB2510 for letting us know!

**Comment by julieqiu** [comment]
This is fixed at master.
