### ISSUE TITLE
x/pkgsite: package removal request for https://pkg.go.dev/github.com/panda8z/eeyoo

### ISSUE THREAD

**Issue by panda8z** [golang/go#61167]
### What is the path of the package that you would like to have removed?

 
 https://pkg.go.dev/github.com/panda8z/eeyoo
 
### Are you the owner of this package?

 yes 

### What is the reason that you could not retract this package instead?

I delete this github repo `github.com/panda8z/eeyoo`

**Comment by seankhliao** [comment]
please try following the instructions here https://github.com/golang/go/issues/60985#issuecomment-1607712161
