### ISSUE TITLE
cmd/internal/obj/s390x:  Adding Crypto mnemonics to the assembler

### ISSUE THREAD

**Issue by srinivas-pokala** [golang/go#61163]
Currently a few  crypto intsructions in the s390x Architecture's are hardcoded using BYTE and WORD.  Need to add KDSA, KM,KMC,KMCTR,KIMD,KMA, KLMD instructions to go assembler.

@golang/s390x

**Comment by srinivas-pokala** [comment]
Added CL for adding KM,KMC,KIMD,KLMD instructions to the assembler.

**Comment by Vishwanatha-HD** [comment]
Raised a CL to add the assembly instruction mnemonics for KMA and KMCTR instructions. CL link is:
https://go-review.googlesource.com/c/go/+/515195
