### ISSUE TITLE
gofmt: misaligned map values when key contains an emoji

### ISSUE THREAD

**Issue by EduardGomezEscandell** [golang/go#61168]
### What version of Go are you using (`go version`)?

Linux:
<pre>
$ go version
go version go1.20 linux/amd64
</pre>

Windows:
<pre>
> go version
go version go1.20 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes, with 1.20.5

### What operating system and processor architecture are you using (`go env`)?

Linux:
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/edu/.cache/go-build"
GOENV="/home/edu/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/edu/go/pkg/mod"
GONOPROXY="github.com/canonical/[hidden]"
GONOSUMDB="github.com/canonical/[hidden]"
GOOS="linux"
GOPATH="/home/edu/go"
GOPRIVATE="github.com/canonical/[hidden]"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2008844192=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

Windows:
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\edu19\AppData\Local\go-build
set GOENV=C:\Users\edu19\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\edu19\go\pkg\mod
set GONOPROXY=github.com/canonical/[hidden]
set GONOSUMDB=github.com/canonical/[hidden]
set GOOS=windows
set GOPATH=C:\Users\edu19\go
set GOPRIVATE=github.com/canonical/[hidden]
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.20
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=cl.exe
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\edu19\AppData\Local\Temp\go-build1095880433=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

https://go.dev/play/p/RqgxlB3sskB

Use `gofmt`on the following file:
```go
package foo

var bar = map[string]int{
	"💩":     23,
	"hello": 54,
	"bye":   67,
}
```

### What did you expect to see?

I expected the map values to be aligned.

### What did you see instead?

The map values are misaligned when the key contains an emoji.

**Comment by ALTree** [comment]
This is more or less unavoidable, see the discussion in #16170 for an explanation.

Closing here as not actionable.
