### ISSUE TITLE
x/tools/gopls: high memory consumption in certain workspaces when staticcheck is enabled

### ISSUE THREAD

**Issue by findleyr** [golang/go#61178]
Forked from https://github.com/golang/go/issues/45457#issuecomment-1620486267, where @folago is reporting that they still encounter high memory consumption in their workspace. In fact, this memory consumption is even higher than gopls@v0.11.0.

I suspect analysis facts, the import graph for open packages, or perhaps a memory leak.  Unfortunately this reproducer is not open source, but with some help we should be able to narrow down the cause.

CC @adonovan

**Comment by findleyr** [comment]
Per ongoing discussion in #45457, we have narrowed this down to SSA/SSI analyzers that are enabled (nilness and staticcheck).

Looking at the profile posted there, it appears that encoding/decoding staticcheck's IR is causing quite a bit of allocation:

```
(pprof) top
Showing nodes accounting for 13800.10MB, 88.23% of 15640.41MB total
Dropped 449 nodes (cum <= 78.20MB)
Showing top 10 nodes out of 105
      flat  flat%   sum%        cum   cum%
 9905.08MB 63.33% 63.33% 10184.11MB 65.11%  honnef.co/go/tools/go/ir.memberFromObject
 1119.06MB  7.15% 70.48%  1392.08MB  8.90%  golang.org/x/tools/go/types/objectpath.namedMethods
  541.59MB  3.46% 73.95%  2420.59MB 15.48%  golang.org/x/tools/internal/facts.(*Decoder).Decode
  522.31MB  3.34% 77.29%   522.31MB  3.34%  os.ReadFile
  351.41MB  2.25% 79.53%   351.41MB  2.25%  reflect.unsafe_NewArray
  325.03MB  2.08% 81.61%   325.03MB  2.08%  honnef.co/go/tools/go/ir.NewConst (inline)
  310.03MB  1.98% 83.59%   310.03MB  1.98%  go/types.NewParam (inline)
  268.52MB  1.72% 85.31%   268.52MB  1.72%  go/types.Id
  241.51MB  1.54% 86.86%   241.51MB  1.54%  encoding/gob.decString
  215.56MB  1.38% 88.23%   719.62MB  4.60%  honnef.co/go/tools/go/ir.makeWrapper
```

As reported by @folago, with staticcheck/nilness enabled they are observing up to 12GB of disk reads, vs ~300MB of reads without. This indicates that SSA structures may be consuming more than the fixed 1GB of cache, which could result in a lot of churn.

Next step: try to reproduce this in an open source repository that we know to have expensive analysis, such as hashicorp/terraform-provider-aws.

(I'll note that I am intentionally not CCing Dominik yet, as I suspect our driver lacks some sophistication, and don't want to bother him :) )

**Comment by dominikh** [comment]
`staticcheck` using 10 GB seems quite high to me. I'll try and do some analysis tomorrow.

**Comment by findleyr** [comment]
Thanks @dominikh. I'll just note that this repository was chosen because it is known to be very expensive to analyze. It has some large low-level packages. 10GB does not seem entirely unreasonable.  But it may be worthwhile to understand the cost a bit better: e.g. is there some common edge through a method that causes buildir to be effectively quadratic?

**Comment by adonovan** [comment]
The problem is very easy to reproduce without staticcheck or buildir, and without gopls.

Simply add a dummy fact to nilness.Analyzer.FactTypes and run the nilness command:
```
terraform-provider-aws$ (cd ~/w/xtools && go build -o nilness ) && time ~/w/xtools/nilness -cpuprofile=prof ./internal/provider/
... time passes, memory fades ...
```
