### ISSUE TITLE
runtime, x/mobile: runtime.raise_trampoline.abi0 crash

### ISSUE THREAD

**Issue by NightBlaze** [golang/go#61173]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/user/Library/Caches/go-build"
GOENV="/Users/user/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/user/go/pkg/mod"
GONOPROXY="*"
GONOSUMDB="*"
GOOS="darwin"
GOPATH="/Users/user/go"
GOPRIVATE="*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.20.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/user/Work/gomobile-experiments/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/7v/1f7g4jw1337ggmqlxxgq74g00000gn/T/go-build1425140998=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
I have an app in production which uses library created with gomobile bind. Sometimes iOS crashes with `runtime.raise_trampoline.abi0`. There is no dependence on the user's device type and iOS version.

### What did you expect to see?
No crash.

### What did you see instead?
Crash.

![stacktrace](https://github.com/golang/go/assets/1081461/b40f72d9-27a4-4a06-bff9-44de220d0124)

**Comment by cherrymui** [comment]
This function is only called when the program is already about to crash or terminate, usually when it receives a signal that it doesn't want to handle. Does this program or other program send it signals that it doesn't want to handle?

**Comment by NightBlaze** [comment]
@cherrymui I don't send any signals and don't wait for them. The crash is pretty rare and nobody from our team had it but according to reports it's about 80% of all crashes in the application. Users said that the crash can occur at any time: on the app start or even when user is doing nothing.

Full crash report is here. `FIRCLSMatchException*` is from Firebase library and it's the only suspect.
![stacktrace1](https://github.com/golang/go/assets/1081461/ff64d73e-a610-4620-9b2e-6a0cd63da77d)
![stacktrace2](https://github.com/golang/go/assets/1081461/34b1a9c3-f5dd-4f11-9d84-2bed91e023a1)
![stacktrace3](https://github.com/golang/go/assets/1081461/7a485e0a-a8e4-4dc7-9898-1f871ed8a89f)
![stacktrace4](https://github.com/golang/go/assets/1081461/fb4a431d-13c8-4152-a025-f9cc6f3e2a3a)

**Comment by cherrymui** [comment]
> FIRCLSMatchException* is from Firebase library and it's the only suspect.

That is possible.

Unfortunately the stack traces for Go threads are stopped at runtime.asmcgocall. Could you try Go 1.21rc2 and see if that makes any difference? Thanks.

**Comment by NightBlaze** [comment]
> Could you try Go 1.21rc2 and see if that makes any difference?

I will try 1.21 after it will be released and notify on results.

**Comment by jiangzhiguo1992** [comment]
@NightBlaze  I also encountered the same problem, any follow-up?

**Comment by NightBlaze** [comment]
@jiangzhiguo1992 Nope. Will make next release with go 1.21 and check if the issue still present.

**Comment by brave723** [comment]
go version go1.21.1 darwin/arm64
I get this crash all the time，how to slove it？
help me

**Comment by tex0l** [comment]
I have the same issue with a library built with the latest gomobile ([v0.0.0-20231127183840-76ac6878050a](https://pkg.go.dev/golang.org/x/mobile@v0.0.0-20231127183840-76ac6878050a/cmd/gomobile)) and go version (1.21.5).

I am not able to find a root cause that triggers the crash.
