### ISSUE TITLE
net: FileConn can yield blocking descriptors, leading to livelock 

### ISSUE THREAD

**Issue by philhofer** [golang/go#61205]
### What version of Go are you using (`go version`)?

go1.20.5

<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

Linux/amd64

### What did you do?

We use `net.FileConn` to construct a `net.Conn` from a file descriptor passed in from another process via a unix socket.

`net.FileConn` calls `internal/poll.FD.Init(net, true)`, which then makes the descriptor pollable **conditional on poll configuration succeeding**:
```go
        err := fd.pd.init(fd)
        if err != nil {
                // If we could not initialize the runtime poller,
                // assume we are using blocking mode.
                fd.isBlocking = 1
        }
```

The trouble here is that `fd.pd.init(fd)` can produce an error when the number of poll watches exceeds `/proc/sys/fs/epoll/max_user_watches`, and thus the **non-blocking** file descriptor is incorrectly labelled as blocking.
The consequence of this is that calls to `write(2)`, `read(2)`, etc. that return `EAGAIN` do not invoke the netpoller and instead loop forever (or as long as the operation would block), which consumes 100% of the CPU time. Here's a flame graph I captured from a profile:
![Screenshot 2023-07-06 9 06 37 AM](https://github.com/golang/go/assets/2940902/1a68e7ef-71e9-4281-a0f8-e71377bdbab8)

I think the correct fix here is to have `poll.FD.Init` produce a real error when netpoller registration fails.

**Comment by ianlancetaylor** [comment]
What is the value of `/proc/sys/fs/epoll/max_user_watches` on your systems?

**Comment by philhofer** [comment]
```
# cat /proc/sys/fs/epoll/max_user_watches 
1766110
```

I'm not 100% certain this is the error that causes `isBlocking` to be set to `1`. I am certain, though, that a file descriptor leak in our process led to this livelock, so exceeding `max_user_watches` was my best guess as to the error that is being returned from `fd.pd.init`.

**Comment by philhofer** [comment]
I've uploaded a (large) execution trace to a public S3 bucket:
```
aws s3 cp s3://sneller-samples/pub/go-61205.trace . --no-sign-request
```

**Comment by ramondeklein** [comment]
Trace file can be downloaded using https://sneller-samples.s3.amazonaws.com/pub/go-61205.trace.

**Comment by ianlancetaylor** [comment]
As far as I can tell, if `epoll_ctl` fails because `max_user_watches` is exceeded, then the error is returned back up the stack and should be returned from `net.FileConn`.  So I don't think I understand the problem.  Can you show a test case?  Thanks.
