### ISSUE TITLE
cmd/compile/internal/base, cmd/compile/internal/noder: "importmap" verb of -importcfg file has no effect

### ISSUE THREAD

**Issue by podtserkovskiy** [golang/go#61206]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/michaelpo/Library/Caches/go-build"
GOENV="/Users/michaelpo/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/michaelpo/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/michaelpo/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.20.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.20.5/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.20.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="cc"
CXX="c++"
CGO_ENABLED="1"
GOMOD="/Users/michaelpo/code/gotest/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/pc/tv8rh9c925g6dx1wpcc3bpjh0000gn/T/go-build284202503=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I was trying to use ["importmap" verb of `-importcfg` file](https://github.com/golang/go/blob/go1.20.5/src/cmd/compile/internal/base/flag.go#L442C7-L442C7) when run the compiler, but it had no effect. 
Looking into the code, I found out that the compiler never use "importmap" from importcfg.
It happens because of [this condition](https://github.com/golang/go/blob/go1.20.5/src/cmd/compile/internal/noder/import.go#L90) which is always `true` when `-importcfg` provided. 
Because of base.Flag.Cfg.PackageFile never equal to `nil` due to [this line](https://github.com/golang/go/blob/go1.20.5/src/cmd/compile/internal/base/flag.go#L416)

### What did you expect to see?

Actually I don't expect this to be fixed as I've started to use "packagefile" verb instead. 
This functionality is dead at the moment (after removing `-importmap` flag) and `-I` flag is dead too (unless no `-importmap` flag provided).
Probably "importmap" verb and `-I` flag should be just removed to simplify the compiler interface and avoid further confusion.

**Comment by seankhliao** [comment]
cc @golang/compiler

**Comment by mdempsky** [comment]
ImportMap is used here: https://github.com/golang/go/blob/e827d41c0a2ea392c117a790cdfed0022e419424/src/cmd/compile/internal/noder/import.go#L140

**Comment by podtserkovskiy** [comment]
Sorry I meant it doesn't work as `-importmap` flag, so [these lines](https://github.com/golang/go/blob/go1.20.5/src/cmd/compile/internal/noder/import.go#L94-L101C3) (which searching mapped imports in directories provided by `-I`) are never executed when `-importcfg` provided.

**Comment by mdempsky** [comment]
That's by design. If you use -importcfg, you need to provide a packagefile entry for each imported package. There's no fallback behavior.

**Comment by podtserkovskiy** [comment]
Thanks, I got the idea. The only thing confusing me is that`-I` flag makes sense only when `-importcfg` is unset, because the compiler [doesn't use `base.Flag.Cfg.ImportDirs`](https://github.com/golang/go/blob/go1.20.5/src/cmd/compile/internal/noder/import.go#L94C40-L94C40) if [`base.Flag.Cfg.PackageFile` is not `nil`](https://github.com/golang/go/blob/go1.20.5/src/cmd/compile/internal/noder/import.go#L90C26-L90C26).
Probably the compiler should return an error if both `-I` and `-importcfg` were provided.
