### ISSUE TITLE
websocket: chrome wss doesn't work with go-lang https/tls server

### ISSUE THREAD

**Issue by xoba** [golang/go#6121]
<pre>What steps will reproduce the problem?
If possible, include a link to a program on play.golang.org.

0. see <a href="http://play.golang.org/p/FM79CQOQT1">http://play.golang.org/p/FM79CQOQT1</a> for my test code &quot;ws.go&quot;, which
runs fine on a real machine but not in play environment because of websockets
1. &quot;go run ws.go&quot;
2. in a browser, visit unsecure url &quot;<a href="http://localhost:8080&quot">http://localhost:8080&quot</a>; ---
this is insecure version, you should see echo messages once per second
3. in a browser, visit secure url &quot;<a href="https://localhost:8090&quot">https://localhost:8090&quot</a>; ---
	this is secure version, depending on browser type, you should see same output as insecure version, or error; note
      that you will have to accept the untrusted certificate below and/or security exception manually when prompted.

What is the expected output?
list of log events in browser: &quot;open&quot;, then multiple &quot;message&quot;
events once per second

What do you see instead?
for wss in chrome (my version is 28.0.1500.95), we see error and premature close events
(i.e., wss fails), whereas firefox and opera work fine. note that wss in chrome seems to
work fine with other non-golang https/tls servers. for insecure websockets (ws), all
three work fine: chrome, firefox, &amp; opera.

Which compiler are you using (5g, 6g, 8g, gccgo)?
i run the test code as &quot;go run ws.go&quot;

Which operating system are you using?
<a href="http://linuxmint.com/">http://linuxmint.com/</a> 64-bit v15

Which version are you using?  (run 'go version')
go version devel +d7db8c804ffa Mon Aug 12 13:03:50 2013 +1000 linux/amd64

Please provide any additional information below.
code at <a href="http://play.golang.org/p/FM79CQOQT1">http://play.golang.org/p/FM79CQOQT1</a> is attached</pre>

Attachments:

1. <a href="https://storage.googleapis.com/go-attachment/6121/0/ws.go">ws.go</a> (5559 bytes)

**Comment by mikioh** [comment]
Nowadays looks like it's okay. I just tried with Chrome Version 39.0.2171.99 (64-bit), Go 1.4 and current x/net subrepo, and didn't see any failures.

**Comment by integrii** [comment]
I don't think its completely fixed, or it is broken again in the same way.  This is still happening for me on go version 1.4.2 x64.  Safari (version 9.0) works, but Firefox (version 39.0) and Chrome do not (version 43 on OSX).  It also appears that javax.websocket also gets a 403.

I get this error in Chrome:
```
WebSocket connection to 'wss://my.domain.com:8000/copyTest' failed: Error during WebSocket handshake: Unexpected response code: 403
```
Nothing is produced at the go terminal, unless i hit it with javax.websocket - which produces this:
```
http: TLS handshake error from 127.0.0.1:44249: tls: first record does not look like a TLS handshake
```

In Safari I get the expected result in the javascript console:
```
[Log] sent data:test (testClient.html, line 31)
[Log] got data:test (testClient.html, line 19)
```

in Firefox I get a 403 similar to Chrome and the console shows this:
```
GET 
https://my.domain.com:8000/rideTracking [HTTP/1.1 403 Forbidden 3ms]
"got error:" error { target: WebSocket, isTrusted: true, currentTarget: WebSocket, eventPhase: 2, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1435967773819792, originalTarget: WebSocket, explicitOriginalTarget: WebSocket, NONE: 0 } testClient.html:22:5
"got close:" close { target: WebSocket, isTrusted: true, wasClean: false, code: 1006, reason: "", currentTarget: WebSocket, eventPhase: 2, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1435967773821310 } testClient.html:25:5
```



Here is some go code to serve TLS websockets.  sub in your own cert.key and cert.pem files.

```golang
package main

import (
	"golang.org/x/net/websocket"
	"io"
	"log"
	"net/http"
)

func copyTest(ws *websocket.Conn) {
	io.Copy(ws, ws)
}

func main() {

	// setup http handler
	http.Handle("/copyTest", websocket.Handler(copyTest))

	// start secure websocket server
	log.Println("Listening for secure websocket connections on localhost port 8000...")
	if err := http.ListenAndServeTLS(":8000", "cert.pem", "cert.key", nil); err != nil {
		panic("ListenAndServeTLS Error: " + err.Error())
	}
}
```

Here is a javascript client.  Sub in the proper domain name for your cert instead of localhost and connect using it.  Results will be written to the javascript console.
```javascript
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8" />
		<title>Websocket connector</title>
		<script src="http://code.jquery.com/jquery-compat-git.js">
		</script>
	</head>
	<body>
			<input id="name" type="text" />
			<button id="sendBtn">send</a>

		<script>
			var ws = new WebSocket("wss://localhost:8000/copyTest");

			ws.onmessage = function(e) {
				console.log("got data:" + e.data);
			};
			ws.onerror = function(e) {
				console.log("got error:", e);
			};
			ws.onclose = function(e) {
				console.log("got close:", e);
			};

			$('#sendBtn').click(function(){
				var data = $('#name').val();
				ws.send(data);
				console.log("sent data:" + data);
			});
		</script>
	</body>
</html>
```

**Comment by mikioh** [comment]
@integrii,

Please open a new issue.
