### ISSUE TITLE
log/slog: don't write nil contexts [freeze exception] 

### ISSUE THREAD

**Issue by jba** [golang/go#61226]
As #61219 points out, we should not pass nil where a context.Context is expected. 
https://go.dev/cl/508437 contains the fix, which includes code as well as documentation.

/cc @golang/release

**Comment by heschi** [comment]
No need for a freeze exemption for documentation and test updates. The production change is tiny and seems obviously safe, but maybe I'd have left it out just to keep the risk to zero. Anyway, approved.
