### ISSUE TITLE
affected/package: sort

### ISSUE THREAD

**Issue by LargeOrange** [golang/go#61222]
### What version of Go are you using (`go version`)?

<pre>
$ go version
$ go version go1.17.13 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
I dont know

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/sundacheng/Library/Caches/go-build"
GOENV="/Users/sundacheng/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/sundacheng/go/pkg/mod"
GONOPROXY="git.ddxq.mobi"
GONOSUMDB="git.ddxq.mobi"
GOOS="darwin"
GOPATH="/Users/sundacheng/go"
GOPRIVATE="git.ddxq.mobi"
GOPROXY="https://goproxy.cn"
GOROOT="/Users/sundacheng/sdk/go1.17.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/sundacheng/sdk/go1.17.13/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.17.13"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/sundacheng/GolandProjects/study/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/87/y0yp0xd51tx38ddkg7vrxx8x0zr3tr/T/go-build2063815648=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
This is my code:
<pre>
func main() {
	s1 := []byte("tan")
	s2 := []byte("nat")
	sort.Slice(s1, func(i, j int) bool {
		return s1[i] > s1[j]
	})
	sort.Slice(s2, func(i, j int) bool {
		return s1[i] > s1[j]
	})
	fmt.Println(s1, s2)
}
</pre>
This is my code output: 
<pre>
[116 110 97] [110 97 116]
</pre>

### What did you expect to see?

I think s1 and s2 should get the same result after sort. But the results are different and not in order

### What did you see instead?
<pre>
[116 110 97] [110 97 116]
</pre>

**Comment by Nasfame** [comment]
Code fixed  - typo in L15

```go 
package main

import (
	"fmt"
	"sort"
)

func main() {
	s1 := []rune("tan")
	s2 := []rune("nat")
	sort.Slice(s1, func(i, j int) bool {
		return s1[i] > s1[j]
	})
	sort.Slice(s2, func(i, j int) bool {
		return s2[i] > s2[j]
	})
	fmt.Println(s1, s2)
}

```

**Comment by Nasfame** [comment]
Not a bug

**Comment by LargeOrange** [comment]
<pre>
func main() {
	s1 := strings.Split("tan", "")
	s2 := strings.Split("nat", "")
	sort.Slice(s1, func(i, j int) bool {
		return s1[i] > s1[j]
	})
	sort.Slice(s2, func(i, j int) bool {
		return s1[i] > s1[j]
	})
	fmt.Println(s1, s2)
}
</pre>
output
<pre>
[t n a] [n a t]
</pre>
Why is it not sorted correctly here

**Comment by LargeOrange** [comment]
> Not a bug

why？

**Comment by Nasfame** [comment]
sort.Slice(s2, func(i, j int) bool {
		return **s1**[i] > **s1**[j]
	})

**Comment by LargeOrange** [comment]
<pre>
func main() {
	s1 := []rune("eat")
	s2 := []rune("tea")
	sort.Slice(s1, func(i, j int) bool {
		return s1[i] > s1[j]
	})
	sort.Slice(s2, func(i, j int) bool {
		return s2[i] > s2[j]
	})
	fmt.Println(s1, s2)
}
</pre>
This case can be sorted correctly. But fisrt case can not

**Comment by rittneje** [comment]
@LargeOrange As @Nasfame has pointed out, you wrote the callback function for the second call to `sort.Sort` incorrectly.

You wrote this:
```go
sort.Slice(s2, func(i, j int) bool {
    return s1[i] > s1[j]
})
```

You meant to write this:
```go
sort.Slice(s2, func(i, j int) bool {
    return s2[i] > s2[j]
})
```

And indeed, the corrected code works as expected. https://go.dev/play/p/XOAfmwboMiH

Hence not a bug.
