### ISSUE TITLE
testing/slogtest: add check for empty group [freeze exception]

### ISSUE THREAD

**Issue by jba** [golang/go#61227]
https://go.dev/issue/61067 identifies a bug in log/slog. CL https://go.dev/cl/508436 fixes it and so does not require a freeze exception.

However, any user-written handler could exhibit the same bug. The testing/slogtest package is designed to catch errors like this in Handlers. It should be updated to check for the problem. https://go.dev/cl/508438 does that.

Since this isn't technically a bug fix, I'm applying for an exception.

/cc @golang/release

**Comment by heschi** [comment]
Approved.
