### ISSUE TITLE
cmd/go: panic with empty import

### ISSUE THREAD

**Issue by thierry-f-78** [golang/go#61224]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/thierry/Library/Caches/go-build"
GOENV="/Users/thierry/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/thierry/go/pkg/mod"
GONOPROXY="xxx"
GONOSUMDB="xxx"
GOOS="darwin"
GOPATH="/Users/thierry/go"
GOPRIVATE="xxx"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.20.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/thierry/git/tools/gofuse/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_d/zs7l5ldx1r94fn_qh1zvn1rw0000gn/T/go-build2033600722=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

```go
package main
import ""
```

`go build`

```
panic: loadPackageData called with empty package path

goroutine 35 [running]:
cmd/go/internal/load.loadPackageData({0x1747538, 0xc000112010}, {0xc00009c5d6, 0x0}, {0xc000112ec8, 0x8}, {0xc0000a2840, 0x21}, {0xc00002e0c4, 0x1f}, ...)
	/usr/local/go/src/cmd/go/internal/load/pkg.go:815 +0x65d
cmd/go/internal/load.(*preload).preloadImports.func1({0xc00009c5d6?, 0x0?})
	/usr/local/go/src/cmd/go/internal/load/pkg.go:1076 +0xa5
created by cmd/go/internal/load.(*preload).preloadImports
	/usr/local/go/src/cmd/go/internal/load/pkg.go:1075 +0x2aa
```

Note: I tried to fix the issue myself, but I can't find the right to work in the debug mode on the go compiler.

### What did you expect to see?

single line with error message

### What did you see instead?

the backtrace below

**Comment by Nasfame** [comment]
I am not getting a panic

```scratch_44.go
package main

import ""

func main() {

}
```

```go
 go run scratch_44.go
warning: GOPATH set to GOROOT (/Users/hiro/goferHiro/go) has no effect
/Users/hiro/Library/Application Support/JetBrains/GoLand2023.1/scratches/scratch_44.go:3:8: invalid import path: 
```

go env

```shell
GO111MODULE='on'
GOARCH='arm64'
GOBIN='/Users/hiro/go/bin'
GOCACHE='/Users/hiro/go/cache'
GOENV='/Users/hiro/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/hiro/goferHiro/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/hiro/goferHiro/go'
GOPRIVATE=''
GOPROXY=''
GOROOT='/Users/hiro/goferHiro/go'
GOSUMDB=''
GOTMPDIR=''
GOTOOLCHAIN=''
GOTOOLDIR='/Users/hiro/goferHiro/go/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='devel go1.21-39c5070712 Thu Jul 6 23:23:41 2023 +0000'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/44/nbbyll_10jd0z8rj_qxm43740000gn/T/go-build1883771837=/tmp/go-build -gno-record-gcc-switches -fno-common'

```

**Comment by Nasfame** [comment]
`goimports` is throwing the error as expected in go1.20.5

```
invalid import path: ""
```

**Comment by randall77** [comment]
If this is fixed at tip I think we can just close this. The error is reported, albeit verbosely, in previous versions and is easily worked around.

**Comment by thierry-f-78** [comment]
👍
