### ISSUE TITLE
x/pkgsite: package removal request for https://pkg.go.dev/github.com/twmb/franz-go/pkg/kmsg/v2@v2.0.1

### ISSUE THREAD

**Issue by nyetwurk** [golang/go#61238]
### What is the path of the package that you would like to have removed?

https://pkg.go.dev/github.com/twmb/franz-go/pkg/kmsg/v2@v2.0.0
https://pkg.go.dev/github.com/twmb/franz-go/pkg/kmsg/v2@v2.0.1
 
### Are you the owner of this package?

No
 
### What is the reason that you could not retract this package instead?

The owner cannot
https://github.com/twmb/franz-go/issues/494

Its causing problems with renovate and go get -u

**Comment by seankhliao** [comment]
removing from pkgsite won't affect module proxy, which are what go and renovate look at. we can't modify those by hand.
try v2.0.0-0, v2.x.y
