### ISSUE TITLE
x/website: add log/slog handler guide (https://golang.org/s/slog-handler-guide)

### ISSUE THREAD

**Issue by bbkane** [golang/go#61239]
### What is the URL of the page with the issue?

https://pkg.go.dev/log/slog#hdr-Writing_a_handler

Linking to https://golang.org/s/slog-handler-guide (broken link)

### What is your user agent?

Mozilla/5.0 (Android 13; Mobile; rv:109.0) Gecko/115.0 Firefox/115.0

### Screenshot

n/a

### What did you do?

Head to https://pkg.go.dev/log/slog#hdr-Writing_a_handler

Click on the https://golang.org/s/slog-handler-guide link

### What did you expect to see?

A guide about slog handlers

### What did you see instead?

"not found"

**Comment by ianlancetaylor** [comment]
CC @jba 

There is indeed no such short link, and I'm not sure what it should link to.

**Comment by jba** [comment]
This is https://go.dev/cl/494576, which is in progress.
I would rather roll forward by finishing that doc. 
I will aim to do so by early next week.

**Comment by cherrymui** [comment]
As this is not  in the main repo we will remove the release blocker label. @jba already has a CL out and hopefully we can get it in soon. Thanks.

**Comment by jba** [comment]
The link now points to a valid page.

The actual document is just a stub at the moment, but we won't track its progress here.
