### ISSUE TITLE
Determining Deprecation annotation in runtime:  better reflection.

### ISSUE THREAD

**Issue by subusc** [golang/go#61231]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.19 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
% go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/subramanian.sankarasubramanian/Library/Caches/go-build"
GOENV="/Users/subramanian.sankarasubramanian/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOWORK=""
CGO_CFLAGS="-Wno-undef-prefix"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/kn/1jfzpgk91m9fdpvl9c6hdsbr0000gn/T/go-build329976916=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

https://stackoverflow.com/questions/45328818/how-to-determine-at-runtime-if-a-variable-is-annotated-as-deprecated

How to do the same in Go? AFAIC - Today we just mark a comment that can be accessed by staticcheck only.

I need this internally for some tests to ensure some deprecated proto enum fields aren't getting used in yaml configs.

**Comment by seankhliao** [comment]
That would be a question for the protobuf community, not go.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by subusc** [comment]
@seankhliao This is not a question about how Protobuf generates it: More about how to get an annotation like //Deprecated: from code. once we have a mechanic, I can raise it with the proto community.

**Comment by seankhliao** [comment]
they do not exist in compiled code.

**Comment by subusc** [comment]
I understand that. So where would I lodge a request for annotation support?

**Comment by seankhliao** [comment]
you should really be looking at protoreflect.
