### ISSUE TITLE
gopls not downloading on my Mac 

### ISSUE THREAD

**Issue by Fishyva** [golang/go#61243]
<img width="702" alt="Screenshot 2023-07-09 at 4 26 21 AM" src="https://github.com/golang/go/assets/97076661/1fe48c4b-20b6-4321-b16c-9454bd04e6d0">

<img width="456" alt="Screenshot 2023-07-09 at 4 27 12 AM" src="https://github.com/golang/go/assets/97076661/acf790f4-38c2-4663-9632-251d62ee17fc">

I'm trying to download gopls for vscode go extension and it will not work at all. So now my IntelliSense won't work at all.

**Comment by seankhliao** [comment]
I believe the error message go install printed is relevant

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
