### ISSUE TITLE
affected/flag: my  program crash at M:\work\tool\go1.12.16.windows-amd64\src\flag\flag.go

### ISSUE THREAD

**Issue by epowsal** [golang/go#61255]
here is the source panic position:
func (f *FlagSet) Var(value Value, name string, usage string) {
	// Remember the default value as a string; it won't change.
	flag := &Flag{name, usage, value, value.String()}
	_, alreadythere := f.formal[name]
	if alreadythere {
		var msg string
		if f.name == "" {
			msg = fmt.Sprintf("flag redefined: %s", name)
		} else {
			msg = fmt.Sprintf("%s flag redefined: %s", f.name, name)
		}
		fmt.Fprintln(f.Output(), msg)
		panic(msg) // Happens only if flags are declared with identical names
	}

I commented the panic(msg) line,  everything is OK.
this is a bug. It should be fixed.

**Comment by seankhliao** [comment]
We no longer support 1.12
