### ISSUE TITLE
In func http.HandleFunc if first use PostFormValue or r.URL.Query().Get.  next to use r.MultipartRead will get error

### ISSUE THREAD

**Issue by epowsal** [golang/go#61260]
go:1.20.5
error:
http: multipart handled by ParseMultipartForm

I just want get url parameter. It got error not right.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
