### ISSUE TITLE
x/build: add linux-ppc64le-power8 builder

### ISSUE THREAD

**Issue by pmur** [golang/go#61274]
This will test `GOPPC64=power8 GOARCH=ppc64le GOOS=linux` configuration.

The hostname  should be `linux-ppc64le-power8`. This VM will also be hosted by OSU.

Related to #60440

**Comment by pmur** [comment]
Github prevents uploading files with a `csr` extension. It's plaintext anyhow, so I appended `.txt` to workaround.
[linux-ppc64le-power8.csr.txt](https://github.com/golang/go/files/12032869/linux-ppc64le-power8.csr.txt)

**Comment by cagedmantis** [comment]
The certificate is attached: [linux-ppc64le-power8-1689691894.cert.txt](https://github.com/golang/go/files/12081840/linux-ppc64le-power8-1689691894.cert.txt)

I've also appended the `.txt` extension as a workaround to the upload limitation.

**Comment by dmitshur** [comment]
Great, thanks very much.
