### ISSUE TITLE
cmd/compile: failed to make Go on riscv64 CPU with numa

### ISSUE THREAD

**Issue by mengzhuo** [golang/go#61295]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go 1.21rc2
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='riscv64'
GOBIN=''
GOCACHE='/home/perfxlab04/.cache/go-build'
GOENV='/home/perfxlab04/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='riscv64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/perfxlab04/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/perfxlab04/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/home/perfxlab04/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/home/perfxlab04/go/pkg/tool/linux_riscv64'
GOVCS=''
GOVERSION='go1.21rc2'
GCCGO='gccgo'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3214241602=/tmp/go-build -gno-record-gcc-switches'
</pre></details>

### What did you do?

cd src && ./make.bash

### What did you expect to see?

build complete

### What did you see instead?
```
Building packages and commands for linux/riscv64.
runtime: checkdead: find g 2581 in status 1
fatal error: checkdead: runnable g

runtime stack:
runtime.throw({0x618a92?, 0x53f00?})
        /home/perfxlab04/godev/src/runtime/panic.go:1077 +0x44 fp=0x3f74633d80 sp=0x3f74633d58 pc=0x49db4
runtime.checkdead.func1(0x3f740fbd40)
        /home/perfxlab04/godev/src/runtime/proc.go:5451 +0x118 fp=0x3f74633db0 sp=0x3f74633d80 pc=0x582b8
runtime.forEachG(0x3f74633e20)
        /home/perfxlab04/godev/src/runtime/proc.go:608 +0x70 fp=0x3f74633dd8 sp=0x3f74633db0 pc=0x4d530
runtime.checkdead()
        /home/perfxlab04/godev/src/runtime/proc.go:5437 +0x10c fp=0x3f74633e30 sp=0x3f74633dd8 pc=0x57f14
runtime.mput(0x5227c?)
        /home/perfxlab04/godev/src/runtime/proc.go:5933 +0x58 fp=0x3f74633e38 sp=0x3f74633e30 pc=0x59540
runtime.stopm()
        /home/perfxlab04/godev/src/runtime/proc.go:2534 +0x60 fp=0x3f74633e60 sp=0x3f74633e38 pc=0x50c10
runtime.findRunnable()
        /home/perfxlab04/godev/src/runtime/proc.go:3229 +0xc20 fp=0x3f74633f58 sp=0x3f74633e60 pc=0x52798
runtime.schedule()
        /home/perfxlab04/godev/src/runtime/proc.go:3582 +0xa4 fp=0x3f74633f88 sp=0x3f74633f58 pc=0x538bc
runtime.park_m(0x3f740001a0?)
        /home/perfxlab04/godev/src/runtime/proc.go:3745 +0x124 fp=0x3f74633fc8 sp=0x3f74633f88 pc=0x53e6c
runtime.mcall()
        /home/perfxlab04/godev/src/runtime/asm_riscv64.s:291 +0x40 fp=0x3f74633fd8 sp=0x3f74633fc8 pc=0x7c
af0
```

**Comment by mengzhuo** [comment]
@bcmills hi, can I add this issue to release-blocker?

**Comment by bcmills** [comment]
@mengzhuo, since `riscv64` is not a [first-class port](https://go.dev/wiki/PortingPolicy#first-class-ports) it pretty much by definition can't be a release-blocker.

That said, I would expect that the fix can make the final `go1.21.0` release anyway.
