### ISSUE TITLE
x/tools/gopls: rename reports spurious conflict between parameter and package-level decl ("unexpected var object")

### ISSUE THREAD

**Issue by jan-xyz** [golang/go#61294]
### What version of Go are you using (`go version`)?

<pre>
❯ go version
go version go1.20.5 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
❯ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/jan.steinke/Library/Caches/go-build"
GOENV="/Users/jan.steinke/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/jan.steinke/Go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/jan.steinke/Go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.20.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.20.5/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.5"
GCCGO="gccgo"
AR="ar"
CC="cc"
CXX="c++"
CGO_ENABLED="1"
GOMOD="/Users/jan.steinke/code/github.com/<private module>/go.mod"
GOWORK="/Users/jan.steinke/code/github.com/<private module>/go.work"
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/gc/v8gpyn8x0vgfqjzzqcw1g5w40000gp/T/go-build2228193324=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

Trying to run `rename` command on the `Decode` parameter with gopls:

```go
package main

import (
	"context"
	"encoding/base64"
	"fmt"

	"github.com/aws/aws-lambda-go/events"
	"google.golang.org/protobuf/proto"
)

// APIGatewayEventHandler is a function type that expresses how a APIGatewayEvent is handled.
// This can be used for convenience to build Middlewares for this handler.
type APIGatewayEventHandler func(ctx context.Context, e events.APIGatewayProxyRequest) (*events.APIGatewayProxyResponse, error)

// New returns a new DynamoDBEvent handler.
func New[TIn any](
	Decode func(events.APIGatewayProxyRequest) (TIn, error),
	endpoint func(context.Context, TIn) (proto.Message, error),
) APIGatewayEventHandler {
	return func(ctx context.Context, apiGatewayEvent events.APIGatewayProxyRequest) (*events.APIGatewayProxyResponse, error) {
		tripID, err := Decode(apiGatewayEvent)
		if err != nil {
			return nil, err
		}
		dto, err := endpoint(ctx, tripID)
		if err != nil {
			return nil, err
		}

		// this might work better in an encode function
		protoMessage, err := proto.Marshal(dto)
		if err != nil {
			return nil, err
		}

		body := base64.StdEncoding.EncodeToString(protoMessage)

		return &events.APIGatewayProxyResponse{
			StatusCode:        200,
			Headers:           map[string]string{},
			MultiValueHeaders: map[string][]string{},
			Body:              body,
			IsBase64Encoded:   true,
		}, nil
	}
}
```

I cannot reproduce it when I isolate that code so it seems it has something to do with the module in general. I cannot share it because it's a private code base.

### What did you expect to see?

Being able to rename the parameter

### What did you see instead?

An error by `gopls`:
```
gopls: 0: handler/handler.go:18:2: unexpected var object "var Decode func(github.com/aws/aws-lambda-go/events.APIGatewayProxyRequest) (TIn, error)" (please report a bug)
```

**Comment by adonovan** [comment]
Based on the logic of renamer.check:
```go
// check performs safety checks of the renaming of the 'from' object to r.to.
func (r *renamer) check(from types.Object) {
	if r.objsToUpdate[from] {
		return
	}
	r.objsToUpdate[from] = true

	// NB: order of conditions is important.
	if from_, ok := from.(*types.PkgName); ok {
		r.checkInFileBlock(from_)
	} else if from_, ok := from.(*types.Label); ok {
		r.checkLabel(from_)
	} else if isPackageLevel(from) {
		r.checkInPackageBlock(from)
	} else if v, ok := from.(*types.Var); ok && v.IsField() {
		r.checkStructField(v)
	} else if f, ok := from.(*types.Func); ok && recv(f) != nil {
		r.checkMethod(f)
	} else if isLocal(from) {
		r.checkInLexicalScope(from)
	} else {
		r.errorf(from.Pos(), "unexpected %s object %q (please report a bug)\n",
			objectKind(from), from)
	}
}
``` 
and the fact that Decode is not a package name, label, package-level decl, field, or method, it must be that the isLocal function is spuriously returning false for this parameter var, likely somehow related to generics. But so far I have not been able to reproduce it in golang.org/x/tools/go/types/internal/play modified to report isLocal, trying minimizations such as:
```go
package main

import "fmt"

func New[T any](g func() (T, error)) {
	g()
}

```

**Comment by jan-xyz** [comment]
I had the same problem. As soon as I take it out of context it stops being broken. I feel kind of stupid reporting by it 🙈

**Comment by jan-xyz** [comment]
Ha! I now have a minimal reproduction of it

```go
package cmd

import "errors"

var Foo = errors.New("oops")

func Bar() {
}

const Baz = 42

func New(Foo int, Bar string, Baz float64) string {
	return ""
}

```

The problem seems to happen when the parameter is shadowing an exported token. Non of the parameters to `New` can be renamed and fail with `gopls: 0: ...: unexpected var object "var  ...)" (please report a bug)`

**Comment by adonovan** [comment]
Well done for isolating this test case: I can reproduce it locally and will prepare a fix presently.

**Comment by adonovan** [comment]
> That's also why it stoped to break once I took it out of its context, because it stopped shadowing the exported token called Decode.

The reason it was tricky is that the package must be imported for the bug to appear, even though the object is local to the function. (The reason is that, from the type-checker's perspective, function parameter vars are exported, as that may affect error messages emitted by the compiler in other packages, and this property of being exported causes rename to use a different algorithm.)

**Comment by jan-xyz** [comment]
I guess it doesn't happen that much because it's very unusual for function parameter vars to be uppercase. That's also how I encountered it, I saw the code and wanted to lowercase it. The Decode function was though quite far away from this in a completely different file.
