### ISSUE TITLE
x/pkgsite: requested package could not be found

### ISSUE THREAD

**Issue by munichbughunter** [golang/go#61313]
I recently created a new public github repo (https://github.com/munichbughunter/flow) but pkg.go.dev seems to be unable to access/parse it.

### What is the URL of the page with the issue?
If I go to https://pkg.go.dev/github.com/munichbughunter/flow
Once I click on "request", I get almost immediately, "github.com/munichbughunter/flow" could not be found.:

### What is your user agent?
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/115.0

### Screenshot

<img width="1720" alt="Bildschirmfoto 2023-07-12 um 15 16 37" src="https://github.com/golang/go/assets/56535110/45c81887-ecea-462a-a2bd-371ff2a4fd09">

### What did you do?

Once I click on "request", I get almost immediately, "github.com/munichbughunter/flow" could not be found.:

### What did you expect to see?

Success or Found 

### What did you see instead?

could not be found

Personal notes: 
If I use go get it works:

❯ mkdir test

❯ cd test

❯ go mod init test
go: creating new go.mod: module test

❯ go get github.com/munichbughunter/flow
go get: added github.com/munichbughunter/flow v0.0.0-20230707062840-d3da69e273fe

**Comment by seankhliao** [comment]
your module declaration `flow` doesn't match.
