### ISSUE TITLE
x/website: doc/install: the download button is unclear

### ISSUE THREAD

**Issue by RheingoldRiver** [golang/go#61311]
### What did you do?

On the [documentation page](https://go.dev/doc/install), I read "Download (1.20.6)" and then "Don't see your operating system here? Try one of the other downloads."

![image](https://github.com/golang/go/assets/18037011/1e64ae28-9909-400f-909b-6cd3b595864c)

Then I got really confused because this looks like a file-download button, and no operating system is listed. I asked my friend if this was the official docs because I thought I was in the wrong place, and then went to file a ticket.

### What did you expect to see?

A list of operating systems with download links. But then my friend explained the download button is actually a link to all of the OS versions. So, I would expect the text to be "View Download Links"

And then the line below it should say, "Don't see your operating system listed?" with "listed" instead of "here."

### What did you see instead?

Described above.

**Comment by Oguidan** [comment]
"Download (1.20.6)" and "Don't see your operating system here? Try one of the other downloads." lead to the same page of download. But don't worry or be confuse because to install Go Lang you need to download a file and then execute. Download the file corresponding to your system and then execute the file.

**Comment by Oguidan** [comment]
Hello 👋 @seankhliao please do you know where to fixe this. I can't find the place.

**Comment by gophun** [comment]
@Oguidan The file is `_content/doc/install.html` in the `website` repository: https://go.googlesource.com/website/+/master/_content/doc/install.html

**Comment by cherrymui** [comment]
cc @golang/tools-team

**Comment by Oguidan** [comment]
@cherrymui what do you mean

**Comment by cherrymui** [comment]
@Oguidan I just cc'd the owner of the page so they're aware of this issue. Thanks.

**Comment by Oguidan** [comment]
@cherrymui ah ok 👌 thank you for letting me know. I didn't know
