### ISSUE TITLE
x/build/cmd/gerritbot: make first GitHub PR comment more useful to a new contributor

### ISSUE THREAD

**Issue by thepudds** [golang/go#61317]
Currently, the first message posted by GerritBot to a GitHub PR is similar to:
```
This PR (HEAD: 09c8d87) has been imported to Gerrit for code review.

Please visit https://go-review.googlesource.com/c/build/+/508475 to see it.

Tip: You can toggle comments from me using the comments slash command (e.g. /comments off)
See the Wiki page for more info
```

In general, the timing of putting information in front of people has a material influence on how they read and retain that information, and that message arrives at an excellent moment in a new contributor's journey.

It seems we could provide more tips & context to inform or remind a PR author of key information as well as provide more links to details.

A draft CL with some possible modifications is at https://go.dev/cl/508475.

A related issue is #61316, which attempts to tackle a slightly different set of problems around whether an author has a Gerrit account, whether they will ever reply in Gerrit, and so on. (#61316 suggests a new comment on the Gerrit CL, whereas this issue suggests changing the wording of a comment on the GitHub PR).

CC @heschi, @cagedmantis

**Comment by carlmjohnson** [comment]
It's not super-clear as written where to put the slash commands. It could be more explicit like "(e.g. **by replying to this comment on GitHub with** /comments off)".

**Comment by thepudds** [comment]
Hi @carlmjohnson 

> It's not super-clear as written where to put the slash commands. 

FWIW, I did initially attempt to improve the wording, but I didn't want to take the time to test it, so I instead just kept the wording exactly as it was.

Also, my personal take was that it was more important to try to improve the likelihood of success for a new contributor while also attempting to reduce some friction for the maintainers... and "I'd like to mute GerritBot on my PR" seems to be less of a problem for a new contributor.

In any event, with this CL, that text is now moved to the Wiki, and the wording can be improved there if someone is interested in doing so:

https://github.com/golang/go/wiki/GerritBot/#frequently-asked-questions
