### ISSUE TITLE
Runtime error is seen with GC in go 1.18.1 

### ISSUE THREAD

**Issue by AVESH-RAI** [golang/go#61332]
### What version of Go are you using (`go version`)?

$ go version 1.18.1 

### What operating system and processor architecture are you using (`go env`)?
Centos 7.8

### What did you expect to see?
No Panic and restart. This is deployed in customer premises.

### What did you see instead?
Below panic is observed.

runtime stack:
runtime.throw({0x8525e1?, 0x42041f?})
	/usr/local/go/src/runtime/panic.go:992 +0x71
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:802 +0x3a9
runtime.(*gQueue).pushBack(...)
	/usr/local/go/src/runtime/proc.go:5956
runtime.runqdrain(0xc00004dc38?)
	/usr/local/go/src/runtime/proc.go:5847 +0x110
runtime.gcBgMarkWorker.func2()
	/usr/local/go/src/runtime/mgc.go:1283 +0xc5
runtime.systemstack()
	/usr/local/go/src/runtime/asm_amd64.s:469 +0x49

goroutine 138 [GC worker (idle)]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:436 fp=0xc0005aa758 sp=0xc0005aa750 pc=0x462e80
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1263 +0x1b1 fp=0xc0005aa7e0 sp=0xc0005aa758 pc=0x41cf71
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0005aa7e8 sp=0xc0005aa7e0 pc=0x4650a1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1131 +0x25

**Comment by cherrymui** [comment]
Go 1.18.1 is no longer supported. Could you try the latest Go 1.19.11 or Go 1.20.6 release, or Go 1.21 RC? Also, could you provide more information about your program? Thanks.

**Comment by AVESH-RAI** [comment]
Prometheus version-2.31.1 is compiled with GO-1.18.1. It is deployed on Field. Customer is not willing to upgrade the version. Following is the logs of the application.
[Prometheus Error logs](https://drive.google.com/drive/u/0/folders/13yuaDNTGqEM1U3h-eXMeIPnNPxciZjOZ)

**Comment by AVESH-RAI** [comment]
After adding this environment variable in prometheus container. The error is not seen in last 13 days after this change. Prior to this change it used to restart once in a day or two.
        - name: GODEBUG
          value: "gctrace=2"
