### ISSUE TITLE
x/tools/gopls: slow diagnostics after adding/removing an import

### ISSUE THREAD

**Issue by findleyr** [golang/go#61344]
I just noticed that in certain packages, diagnostics are very slow after adding or removing an import (or making any other metadata-affecting change).

It looks like I introduced an `awaitLoaded(...)` call into the critical path re-typechecking a package (via `resolveImportGraph`). When the package being edited is low level, this results in reloading its entire reverse-transitive closure.

As an invariant, we should always be able to operate on the current package without reloading everything.

- [ ] add a benchmark for this operation, which is common thanks to goimports on save
- [ ] fix the logic of `resolveImportGraph`

**Comment by carlmjohnson** [comment]
I sometime see saving a file in VSCode take an extremely long time, and I've never been able to figure out why, but this sounds like a likely culprit. Good luck fixing it!

**Comment by findleyr** [comment]
Thanks @carlmjohnson. It should not actually be that difficult to fix. I'll be sure to ask you to test once it is done :)
