### ISSUE TITLE
govulncheck-action:  be able to specify the working directory when running govulncheck

### ISSUE THREAD

**Issue by Hyuga-Tsukui** [golang/go#61354]
I'm developing a Go application in a monorepo environment. The split actions do not refer to the working-directory specified in the jobs. Therefore, in a monorepo environment, I need to do something similar to what is defined in these actions. If possible, I would like to use this.

**Comment by cherrymui** [comment]
cc @golang/vulndb

**Comment by zpavlinovic** [comment]
Sorry, could you provide more information or ideally an example? It is currently unclear if the problem you are having cannot be solved using [`working-directory`](https://github.com/orgs/community/discussions/25742) directive.

**Comment by zpavlinovic** [comment]
I think the problem might be that `working-directory` does not apply to `uses` steps?

**Comment by Hyuga-Tsukui** [comment]
Yes

**Comment by Hyuga-Tsukui** [comment]
Therefore, I would be happy if you could make it possible to use `working-directory` as a parameter, if possible.

```yml
working-directory:
    description: Where to start the process
    required: false
````

**Comment by zpavlinovic** [comment]
`govulncheck` command accepts the `-C` flag specifying the working directory. We can have an input to `govulncheck-action` that would then be propagated to the command. So you would use `with` instead with the action.
