### ISSUE TITLE
access: go-assignees and security for @drakkan

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#61355]
@drakkan is working with me on x/crypto/ssh and towards taking over maintenance of it.

Can we get him into https://github.com/orgs/golang/teams/go-assignees and https://github.com/orgs/golang/teams/security? IIRC, the latter doesn't grant any access, it's just so he gets notified on x/crypto/ssh issues.

See https://go.dev/wiki/GithubAccess

/cc @golang/release

**Comment by heschi** [comment]
Done.

**Comment by drakkan** [comment]
Thank you!
