### ISSUE TITLE
x/website: go.dev/cl redirector does not work for CL 80780043

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#61363]
According to https://github.com/golang/go/commit/881d693c8603510bee3b88205a90ca97942ee0b9 that change was reviewed on https://golang.org/cl/80780043.  However, neither that link nor https://go.dev/cl/80780043 resolves to the actual change.  I'm unable to find the change on codereview.appspot.com, although other changes around that one do still exist.

The conversation remains at https://groups.google.com/g/golang-codereviews/c/6waUN-WcrRM/m/rn7OsN-pShEJ .

Not sure what happened here.

**Comment by heschi** [comment]
cc @golang/tools-team

**Comment by jamalc** [comment]
The redirector is working as expected, it appears the target is missing the change.

**Comment by hyangah** [comment]
From internal discussion 

> Looking at the Datastore viewer that record seems to just be gone. It is possible that the CL author used Edit Issue > Delete.

@rsc started a process to copy the remaining data to prevent this type of loss in the future. Thanks!
