### ISSUE TITLE
go/doc/comment: failure to recognize initial code block

### ISSUE THREAD

**Issue by 1268** [golang/go#61373]
### What version of Go are you using (`go version`)?

<pre>
go version go1.20 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Steven\AppData\Local\go-build
set GOENV=C:\Users\Steven\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Steven\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Steven\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=D:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.20
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Windows\TEMP\go-build2119281587=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

if I run this code:

~~~go
package main

import (
   "go/doc/comment"
   "os"
)

const pass = `one
 two
 three`

const fail = ` two
 three`

func main() {
   {
      d := new(comment.Parser).Parse(pass)
      b := new(comment.Printer).HTML(d)
      os.Stdout.Write(b)
   }
   os.Stdout.WriteString("\n")
   {
      d := new(comment.Parser).Parse(fail)
      b := new(comment.Printer).HTML(d)
      os.Stdout.Write(b)
   }
}
~~~

### What did you expect to see?

~~~
<p>one
<pre>two
three
</pre>

<pre>two
three
</pre>
~~~

### What did you see instead?

~~~
<p>one
<pre>two
three
</pre>

<p>two
three
~~~

it seems the first input gives expected output, but the second does not. from what I can tell, both inputs match the definition of a code block:

> A code block is a span of indented or blank lines not starting with a bullet list marker or numbered list marker.

https://go.dev/doc/comment#code

**Comment by AndrewHarrisSPU** [comment]
Interesting - subtly, I think the implementation has a [notion of common indentation](https://cs.opensource.google/go/go/+/refs/tags/go1.20.6:src/go/doc/comment/parse.go;drc=7aa4905bb4fd70a5b32552fd8db23a3550d3df83;l=520). By tweaking the relative amount of whitespace it's possible to get different parses (https://go.dev/play/p/-MM0d5hDbYk).

Is this a documentation thing? I couldn't pick out this behavior from the documentation directly or infer it from subtle details it does cover. The package doc for [Parser.Parse](https://pkg.go.dev/go/doc/comment@go1.20.6#Parser.Parse) says:

> Parse parses the doc comment text and returns the \*Doc form. Comment markers (/\* // and \*/) in the text must have already been removed.

Would "Comment markers _and indentation common to all lines in `text`_" be enough of a tweak?

**Comment by 1268** [comment]
> Is this a documentation thing?

I would prefer if the current behavior was an error, because I would like the freedom to start a comment with a code block, which seems is not currently possible. but if I had to guess, I would say the current behavior is correct, and that the documentation needs to be improved.

> Would "Comment markers _and indentation common to all lines in `text`_" be enough of a tweak?

I dont think so. I think this behavior is unexpected enough that it should be special cased in the documentation, assuming the current behavior is correct. so something like:

> it is not possible to start a comment with a code block.

**Comment by AndrewHarrisSPU** [comment]
> I would like the freedom to start a comment with a code block

I think this is possible? In https://go.dev/play/p/-MM0d5hDbYk just having the opening line have more spaces in front seemed to set it into a `<pre>` block

**Comment by 1268** [comment]
yes, I just noticed that as well. it seems the current restriction would more accurately be:

> it is not possible to have only a code block as a comment. a code block must be accompanied by at least one leading or trailing line

**Comment by 1268** [comment]
closing for lack of interest. if anyone wants to pick this up I can reopen

**Comment by ianlancetaylor** [comment]
This is happening because the go/doc/comment parser first strips any indentation that appears consistently in every line.  If you change your example to

```Go
const fail = ` two
 three
four`
```

then the initial code block is recognized.

Stripping consistent indentation is a heuristic that seems to work reasonably well in practice.

**Comment by 1268** [comment]
ideally I would like to be able to have a code block only comment, which is not currently possible. however failing that, I think it would be helpful to at least document that its a known shortcoming that you cannot do that.
