### ISSUE TITLE
affected/package: fmt

### ISSUE THREAD

**Issue by fireflycons** [golang/go#61379]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

No

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/.go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/.go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.4"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2351729845=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```go
	var query int
	var radius float64

	fmt.Print("Enter the radius of the circle: ")
	fmt.Scanf("%f", &radius)
	fmt.Printf("Enter \n 1 - area \n 2 - perimeter \n 3 - diameter: ")
	fmt.Scanf("%d", &query)
```

### What did you expect to see?

As per the documentation for `Scanf` regarding newlines, the first `Scanf` will read a float, and the second `Scanf` will immediately consume the `ENTER` keypress from the fist one, resulting in `query` being set to zero and the user not getting a chance to enter an integer. This behavior was observed on three separate systems running variously 1.19.5, 1.20.2 and 1.20.5

### What did you see instead?

The second `Scanf` paused the program to take input.

**Comment by Jorropo** [comment]
@fireflycons what about checking for error ?
```go
	fmt.Print("Enter the radius of the circle: ")
	if err := fmt.Scanf("%f", &radius); err != nil { panic(err) }
	fmt.Printf("Enter \n 1 - area \n 2 - perimeter \n 3 - diameter: ")
	if err := fmt.Scanf("%d", &query); err != nil { panic(err) }
```

**Comment by fireflycons** [comment]
@Jorropo This isn't about checking for the error. More that the behavior is inconsistent with respect to the documentation. According to what that says, I would expect to have to code the following for the value in `query` to be prompted for and set - and assuming that values of the correct types are entered at the prompts

```go
	fmt.Print("Enter the radius of the circle: ")
	fmt.Scanf("%f\n", &radius)
	fmt.Printf("Enter \n 1 - area \n 2 - perimeter \n 3 - diameter: ")
	fmt.Scanf("%d\n", &query)
```

Without the `\n` 's the behaviour should be (and is observed to be on the later versions), that the float is scanned, but the integer is not because the second Scanf consumes the carriage return from entering the first value, therefore `query` is not set and retains the zero value.

**Comment by Jorropo** [comment]
@fireflycons I don't get what you mean:
> I would expect to have to code the following for the value in query to be prompted for and set

It is what I see:
```go
package main

import "fmt"

func main() {
	var query int
	var radius float64

	fmt.Print("Enter the radius of the circle: ")
	if _, err := fmt.Scanf("%f", &radius); err != nil { panic(err) }
	fmt.Printf("Enter \n 1 - area \n 2 - perimeter \n 3 - diameter: ")
	if _, err := fmt.Scanf("%d", &query); err != nil { panic(err) }
	fmt.Println("done", query, radius)
}
```
```
Enter the radius of the circle: 42
Enter 
 1 - area 
 2 - perimeter 
 3 - diameter: 1337
done 1337 42
```

> This isn't about checking for the error.

This is a commun trap, 0 is the default value, so if `.Scanf` return an error you can see it set to 0 because it has not been touched. Even if I am wrong it would be nice for you to test with error to eliminate potential issues.

**Comment by fireflycons** [comment]
For the record, I'm not trying to learn go here I already understand it pretty well - well enough to create a kubernetes operator. I'm just trying to get a handle on this behavior. Perhaps it's operating system based. 

Using your code above:

```

**Comment by randall77** [comment]
@golang/windows

**Comment by fireflycons** [comment]
Did a bit more investigation. 
```
go version go1.19.5 windows/amd64
```
At line 142 in `scan.go`, if  I change the value of the argument `nlIsSpace` from `false` to `true`, then the scan performs as it does for Linux. The test it line 430 in `SkipSpace` is true  and line 433 where the error string is set is not executed.

The variables pointed to by both scans are correctly set and the program completes without error.

**Comment by seankhliao** [comment]
I don't see anything to do here, we no longer support 1.17.

**Comment by fireflycons** [comment]
@seankhliao The windows issue above is present in the 1.20 stream too

**Comment by fireflycons** [comment]
This is down to whether or not it is *required* to terminate a Scanf format string with `\n` or not for a scan to work correctly - and the behavior should be consistent on both windows and linux

**Comment by seankhliao** [comment]
Given this:

> Input processed by verbs is implicitly space-delimited: the implementation of every verb except %c starts by discarding leading spaces from the remaining input, and the %s verb (and %v reading into a string) stops consuming input at the first space or newline character.

I still don't see an issue

**Comment by fireflycons** [comment]
The issue is that if you are using windows, the enter key puts `\r\n` into `stdin`. Linux puts only `\r`

Because the two cases are not handled in that both these characters should be consumed as one, the behavior of Scanf is inconsistent across platforms resulting in non-portable code.

Try the code posted by @Jorropo above on both platforms. Windows will hit the panic, and Linux won't.

Expected behavior: Either both panic, or neither.

**Comment by Jorropo** [comment]
I don't really know if I would call it not portable, even if I am running on linux, if I configure my shell to emit `\r\n` it will panic just the same.

I agree it's weird that different OSes are handled differently, but there are cost to emulating a consistent behaviour in Go when the OSes don't agree with each other.

It sounds reasonable to me that `\r\n` should be processed like `\n`, even on linux.

**Comment by fireflycons** [comment]
Think is, this will confuse beginners - people who most likely wouldn't know what a shell option is. But I agree that Microsoft and the rest of the world not agreeing on what an end of line is, is more than frustrating!
