### ISSUE TITLE
spec: clarify scope of imports in package with colliding declaration

### ISSUE THREAD

**Issue by smasher164** [golang/go#61380]
Under **Declarations and scope**, the scope of imports is defined as follows:
> 3. The scope of the package name of an imported package is the file block of the file containing the import declaration.

This seems to suggest that the scope of an import only exists for the current file. And while this is true from the perspective of *using* the import, it's not necessarily true from the perspective of shadowing of an outer scope. Specifically, your import can't collide with any package variable, even if it's defined in another file. See the following example:
```Go
package main

import "play.ground/foo"

func main() {
    foo.Bar()
}
-- anotherfile.go --
package main

var foo int
-- go.mod --
module play.ground
-- foo/foo.go --
package foo

func Bar() {}
```
Although the import only appears in `prog.go`, the declaration of `foo` in `anotherfile.go` still collides with it. This results in the following error message:
```
./anotherfile.go:3:5: foo already declared through import of package foo ("play.ground/foo")
    ./prog.go:3:8: other declaration of foo
```
This might lead one to think "oh okay, imports can collide with other names introduced at package scope". However, this isn't entirely true either. For example:
```Go
package main

import "play.ground/foo"

func main() {
    foo.Bar()
}
-- anotherfile.go --
package main

import "play.ground/foo/foo"

var _ = foo.Tar()
-- go.mod --
module play.ground
-- foo/foo.go --
package foo

func Bar() {}
-- foo/foo/foo.go --
package foo

func Tar() {}
```
Each file has its own *distinct* import for `foo` (`"play.ground/foo"` and `"play.ground/foo/foo"`). They correspond to different identifiers brought into scope, but they do not collide. The compiler is perfectly happy to accept this.

Can this behavior be clarified in the spec? Specifically, that the package name of an import can collide with other package variables.

**Comment by go101** [comment]
see https://github.com/golang/go/issues/7429

**Comment by smasher164** [comment]
Ah yeah, this is a dupe of #7429. I didn't think it was being considered to change the current behavior.
I'll close this issue.
