### ISSUE TITLE
affected/package: defer called too early

### ISSUE THREAD

**Issue by DefinitlyEvil** [golang/go#61382]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.2 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
YES

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/..../Library/Caches/go-build"
GOENV="/Users/..../Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/..../.gopath/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/..../.gopath"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="...."
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xx/vtkf1phx0_g8nxxrknzx99fh0000gn/T/go-build2203903721=/tmp/go-build -gno-record-gcc-switches -fno-common"
(base) kevin@Kevins-MacBook-Pro Victimizer % GOOS=windows GOARCH=amd64 go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/..../Library/Caches/go-build"
GOENV="...."
GOEXE=".exe"
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="...."
GONOPROXY=""
GONOSUMDB=""
GOOS="windows"
GOPATH="...."
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="0"
GOMOD="...."
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xx/vtkf1phx0_g8nxxrknzx99fh0000gn/T/go-build2733700552=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I am compiling for `Windows amd64` and using go's Windows Service package `mgr`. 
```go
// s, err = m.OpenService("SomeService")
defer s.Close()
```

### What did you expect to see?
`s.Close()` should be called after the function exits. 

### What did you see instead?
It seemed to be called too early and further calls are invalid thus returned "The handle is invalid". 

----------

```go
	func() {
		m := my_project.Must(mgr.Connect())
		defer func() {
			my_project.Must1(m.Disconnect()) // <<--- MUST put it into a function or it will be closed early!? 
		}()
		func() {
			s, err := m.OpenService(m, my_project.ServiceConfig.Name)
			if err == nil {
				// service exists
				defer func() { my_project.Must1(s.Close()) }() // <<--- THIS WORKS
				defer my_project.Must1(s.Close()) // <<--- THIS DOES NOT WORK
```

**Comment by DefinitlyEvil** [comment]
I don't know how many people experienced what I encountered but this problem is very confusing, it seemed that deferring a function can be more reliable than deferring a call.

**Comment by go101** [comment]
In Go, all arguments of a deferred function call are evaluated at the time when the deferred call is pushed into the defer call stack. This is different from zig.

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.

**Comment by DefinitlyEvil** [comment]
@go101 AH!!! That's why it does not work properly, thanks so much for clearing up my confusion. 
@mvdan Sorry mate for bring up this mess, I thought it was a bug.
