### ISSUE TITLE
net/http, golang.org/x/net/http2

### ISSUE THREAD

**Issue by rakeshkumbi** [golang/go#61391]
### What version of Go are you using (`go version`)?

<pre>
go version go1.20.3 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/rakeshkumbi/.cache/go-build"
GOENV="/home/rakeshkumbi/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/rakeshkumbi/learning/go/golib/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/rakeshkumbi/learning/go/golib:/home/rakeshkumbi/learning/go/workspace"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/rakeshkumbi/learning/go/workspace/test_h2/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build708873615=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

I am trying to send HTTP/2 proxy request without TLS to my HTTP2 Proxy server (nginx & vertex). But the requests and responses which are being sent and received are of HTTP1.1.

Here is my code:
https://go.dev/play/p/Ln1KiQ2200s

### What did you expect to see?
I am expecting the HTTP/2 request/responses

### What did you see instead?

The requests/responses made are HTTP1.1

**Comment by seankhliao** [comment]
see h2c

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
