### ISSUE TITLE
time: since or time.Now().Sub(t) returns wrong when t is start date of the calender

### ISSUE THREAD

**Issue by ErfanMomeniii** [golang/go#61396]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.20.3

</pre>

### What did you expect to see?

I wanted to calculate the number of seconds that have passed since the start of the calendar.
```go
fmt.Println(time.Now().UTC().Sub(time.Date(1, 1, 1, 0, 0, 0, 0, time.UTC)))
```
it returned the wrong answer.
```
2562047h47m16.854775807s
```
from the number of hours, we can calculate 292 years but we are in 2023 now.

**Comment by seankhliao** [comment]
it's unfortunate but int64 can only represent so much time at nanosecond resolution.
