### ISSUE TITLE
x/pkgsite: package removal request for go.dkinom.dev/baseconv/characters

### ISSUE THREAD

**Issue by dkin-om** [golang/go#61400]
### What is the path of the package that you would like to have removed?
go.dkinom.dev/baseconv/characters

 
 
 
### Are you the owner of this package?
Yes

 
### What is the reason that you could not retract this package instead?
Removed the module from GitHub repo

**Comment by seankhliao** [comment]
please try following the instructions at https://github.com/golang/go/issues/60985#issuecomment-1607712161

**Comment by dkin-om** [comment]
@seankhliao I did as advised in the comment. It's been over an hour. Module is not retracted from pkgsite yet.

**Comment by bcmills** [comment]
According to https://proxy.golang.org/cached-only/go.dkinom.dev/baseconv/characters/@latest, the most recent version of `go.dkinom.dev/baseconv/characters` fetched through `proxy.golang.org` is godsfood/baseconv@357f22fe, which is two commits behind the one containing the `retract` directives.

(Did you forget step 3 of the instructions in that comment? Perhaps you accidentally fetched the root module instead of the nested one?)

**Comment by bcmills** [comment]
That error message is correct: the `v0.2.3` tag applies to only the root module, not the nested one.
`go mod download go.dkinom.dev/basecon/characters@master` does the right thing, though:
```
~$ go mod download -json go.dkinom.dev/baseconv/characters@master
{
        "Path": "go.dkinom.dev/baseconv/characters",
        "Version": "v0.0.0-20230718102946-3bd85f839063",
        "Query": "master",
        "Info": "/usr/local/google/home/bcmills/pkg/mod/cache/download/go.dkinom.dev/baseconv/characters/@v/v0.0.0-20230718102946-3bd85f839063.info",
        "GoMod": "/usr/local/google/home/bcmills/pkg/mod/cache/download/go.dkinom.dev/baseconv/characters/@v/v0.0.0-20230718102946-3bd85f839063.mod",
        "Zip": "/usr/local/google/home/bcmills/pkg/mod/cache/download/go.dkinom.dev/baseconv/characters/@v/v0.0.0-20230718102946-3bd85f839063.zip",
        "Dir": "/usr/local/google/home/bcmills/pkg/mod/go.dkinom.dev/baseconv/characters@v0.0.0-20230718102946-3bd85f839063",
        "Sum": "h1:1bcDVdiIr4VDthkjR7WiBOAHej2Ujg/5dVn32663KEY=",
        "GoModSum": "h1:gRR8MVtSp14lHHB/Zeo6V3QCrY6iwzAphxPrY0dDVyo=",
        "Origin": {
                "VCS": "git",
                "URL": "https://github.com/godsfood/baseconv",
                "Subdir": "characters",
                "Hash": "3bd85f839063b2b23ccab1be6cd4c87940d2cda1"
        }
}
```

**Comment by bcmills** [comment]
It should have updated by now. I'm escalating to the `proxy.golang.org` maintainers to figure out what's going on.

**Comment by bcmills** [comment]
This turns out to be a bug in `go list`, filed as #61415.

**Comment by bcmills** [comment]
In the meantime you may be able to work around it by adding a tag for the nested module on the latest commit, like `characters/v0.0.0-retracted`.

**Comment by dkin-om** [comment]
> This turns out to be a bug in `go list`, filed as #61415.

Thank you.

> In the meantime you may be able to work around it by adding a tag for the nested module on the latest commit, like `characters/v0.0.0-retracted`.

Let me try this.

**Comment by dkin-om** [comment]
> > In the meantime you may be able to work around it by adding a tag for the nested module on the latest commit, like `characters/v0.0.0-retracted`.
> 
> Let me try this.

This worked. Now, https://pkg.go.dev/go.dkinom.dev/baseconv/characters is retracted.

But, In the go.dkinom.dev/baseconv module's [directories section](https://pkg.go.dev/go.dkinom.dev/baseconv#section-directories) on the pkgsite I still see reference to go.dkinom.dev/baseconv/characters module. Is this an expected behaviour? Can't the references/links to characters module be removed?
