### ISSUE TITLE
x/sys/unix: Possible breaking change with Pselect on linux

### ISSUE THREAD

**Issue by mauri870** [golang/go#61402]
Follow up to https://go-review.googlesource.com/c/sys/+/510195
Relates to https://github.com/golang/go/issues/61251

Jesse Rittner words:
```
The Go Pselect wrapper never followed this requirement, which means this is a breaking change. 
I agree it was technically a bug, but it can break existing programs in hard-to-detect ways, 
particularly where EINTR is involved.
```

**Comment by ianlancetaylor** [comment]
Thanks, but I think that changing this is fine.  We are not as strict about backward compatibility in the x/sys repo as we are in the standard library.
