### ISSUE TITLE
proposal: affected/package: Add first class GUI support into Golang stdlib.

### ISSUE THREAD

**Issue by laoshaw** [golang/go#61419]
Flutter's Skia and new Impeller render engine made them a great cross platform GUI,  however Dart is still not very popular for some reason. The new Impeller is in C++ and cross platform, both Golang and Impeller are Google's projects.

How feasible is it to add Impeller support to Go stdlib? That will open such a wide 'market' for Golang and is the best way to become truely mainstream IMHO.

Current cross-platform GUI is still either bloated electron.js or who-knows-which-license-is-required Qt. Even Rust has a few OK GUIs(though not in its stdlib).

**Comment by seankhliao** [comment]
see https://go.dev/doc/faq#x_in_std
