### ISSUE TITLE
x/tools/go/packages: document that different package loads lead to different type identities

### ISSUE THREAD

**Issue by griesemer** [golang/go#61418]
When loading the same set of packages twice, user-defined types are not guaranteed to have the same type identity.
This should be explicitly documented.

See #61412 for an example where not understanding this property causes problems.

cc: @findleyr @alandonovan

**Comment by adonovan** [comment]
Yes, we should document that. But see also #57497, which argues that we might be able to finesse the issue (at least for package-level types) by allowing two distinct Named to be identical if their (PkgPaths, Name) pairs are equal.
