### ISSUE TITLE
net: TestInterfaceArrivalAndDepartureZoneCache is broken on linux-arm64

### ISSUE THREAD

**Issue by heschi** [golang/go#61414]
I recently rebuilt our linux-arm64 image to include the `iproute2` package, which caused the skip at https://cs.opensource.google/go/go/+/master:src/net/interface_unix_test.go;l=193;drc=f229e7031a6efb2f23241b5da000c3b3203081d6 to stop happening. Unfortunately the test is failing:

```
--- FAIL: TestInterfaceArrivalAndDepartureZoneCache (0.00s)
    interface_unix_test.go:196: args=[ip address add fe80::1 dev gotest0] out="RTNETLINK answers: Permission denied\n" err=exit status 2
```

cc @ianlancetaylor @neild @stapelberg

**Comment by ianlancetaylor** [comment]
That's weird, because the test is skipped unless the program is running as root.  So it sounds like the test is running as root but it still gets permission denied.  Why would that happen?

In any case I suppose we can look for "Permission denied" in the output string and skip the test in that case.  Unless @stapelberg knows any better.

**Comment by heschi** [comment]
I'll do that for now.

**Comment by stapelberg** [comment]
Is IPv6 disabled on the test runner for some reason? That would explain a “permission denied” from “ip address add”: https://github.com/torvalds/linux/blob/ccff6d117d8dc8d8d86e8695a75e5f8b01e573bf/net/ipv6/addrconf.c#L2502

Which Linux kernel version is the test runner using?

**Comment by bcmills** [comment]
> it sounds like the test is running as root but it still gets permission denied. Why would that happen?

My guess would be a container environment.

We have seen several tests in the past that assumed root has permission to do anything supported by the kernel, but in practice many containers enforce syscall restrictions even for the container's root user.

**Comment by heschi** [comment]
@gopherbot please backport
