### ISSUE TITLE
runtime: Random crash from Windows Server 2019

### ISSUE THREAD

**Issue by BVoychev** [golang/go#61411]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.16.15
</pre>

### Does this issue reproduce with the latest release?
Issue was reproduced with go version 1.19.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
OS: Windows Svr 2019 version 1809
</pre></details>

### What did you do?
I have started a go application on Windows Server 2019. After a few months the application started to randomly crash.

### What did you expect to see?
No crash. 

### What did you see instead?

A go application running on Windows Server randomly crashes with the following error:

```
runtime stack:
runtime: unexpected return pc for sigtramp called from 0xf77e3fef80
...

runtime.throw(0xdf5d63, 0x2a)
    C:/Program Files/Go/src/runtime/panic.go:1117 +0x79
runtime.sigpanic()
    C:/Program Files/Go/src/runtime/signal_windows.go:233 +0x317
runtime.gentraceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc000c9f800, 0x0, 0x0, 0x64, 0x0, 0x0, 0x0, ...)
    C:/Program Files/Go/src/runtime/traceback.go:249 +0x13c9
runtime.traceback1(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc000c9f800, 0x0)
    C:/Program Files/Go/src/runtime/traceback.go:732 +0x105
runtime.traceback(...)
    C:/Program Files/Go/src/runtime/traceback.go:686
runtime.tracebackothers(0xc00040f500)
    C:/Program Files/Go/src/runtime/traceback.go:951 +0x173
runtime.lastcontinuehandler(0xf77e3ff470, 0xf77e3fef80, 0xc00040f500, 0x0)
    C:/Program Files/Go/src/runtime/signal_windows.go:218 +0x265
```

**Comment by qmuntal** [comment]
@bcmills @cherrymui the failure mode seems to be the same as in #50144.

**Comment by mknyszek** [comment]
It's really hard to tell from just the information provided. That stack (`tracebackothers`) happens whenever there's any kind of throw. Do you have a way to reproduce the issue?

I also want to point out that 1.19 isn't going to be supported anymore in just a few weeks when Go 1.21 comes out. Can you reproduce with even newer Go versions?

Thanks.
