### ISSUE TITLE
x/vuln/internal/vulncheck: various tests fail with "binary built using unsupported Go version" when using go1.21rc3 (but not tip nor go1.20.6)

### ISSUE THREAD

**Issue by dmitshur** [golang/go#61424]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21rc3 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

No. It doesn't happen when using Go 1.20.6 nor gotip, only Go 1.21 pre-release versions.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/gopher/Library/Caches/go-build'
GOENV='/Users/gopher/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/gopher/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/gopher/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.21rc3'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/s_/5sjqzr0j6xggz_xtzmq_8r4m00jwcj/T/go-build821381150=/tmp/go-build -gno-record-gcc-switches -fno-common'
</pre></details>

### What did you do?

I ran tests in x/vuln.

### What did you expect to see?

Passing tests.

```
$ go test golang.org/x/vuln/...
[...]
ok  	golang.org/x/vuln/internal/vulncheck/internal/buildinfo	19.467s
ok  	golang.org/x/vuln/internal/vulncheck/internal/gosym	0.764s
ok  	golang.org/x/vuln/internal/web	0.500s
```

### What did you see instead?

Failing tests with "could not parse provided binary: binary built using unsupported Go version" error message.

```
$ go test -count=1 golang.org/x/vuln/internal/vulncheck -run=TestBinary
--- FAIL: TestBinary (0.34s)
    binary_test.go:124: could not parse provided binary: binary built using unsupported Go version: "go1.21rc3"
FAIL
FAIL	golang.org/x/vuln/internal/vulncheck	0.602s
FAIL
```

If this is working as intended and Go 1.21 pre-release versions are intentionally unsupported, the tests that cannot run can be skipped instead of failing.

CC @golang/vulndb.

**Comment by maceonthompson** [comment]
CL: go.dev/cl/513515
