### ISSUE TITLE
net/http/httptest: failed to listen on a port: listen tcp6 [::1]:0: socket

### ISSUE THREAD

**Issue by haroon-sheikh** [golang/go#61452]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.20.5 / 1.20.6
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
windows_amd64 on github actions
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
  set GOARCH=amd64
  set GOBIN=
  set GOCACHE=C:\Users\runneradmin\AppData\Local\go-build
  set GOENV=C:\Users\runneradmin\AppData\Roaming\go\env
  set GOEXE=.exe
  set GOEXPERIMENT=
  set GOFLAGS=
  set GOHOSTARCH=amd64
  set GOHOSTOS=windows
  set GOINSECURE=
  set GOMODCACHE=C:\Users\runneradmin\go\pkg\mod
  set GONOPROXY=
  set GONOSUMDB=
  set GOOS=windows
  set GOPATH=C:\Users\runneradmin\go
  set GOPRIVATE=
  set GOPROXY=https://proxy.golang.org,direct
  set GOROOT=C:\hostedtoolcache\windows\go\1.[20](https://github.com/getgauge/gauge/actions/runs/5603337007/jobs/10249808290#step:3:21).5\x64
  set GOSUMDB=sum.golang.org
  set GOTMPDIR=
  set GOTOOLDIR=C:\hostedtoolcache\windows\go\1.20.5\x64\pkg\tool\windows_amd64
  set GOVCS=
  set GOVERSION=go1.20.5
  set GCCGO=gccgo
  set GOAMD64=v1
  set AR=ar
  set CC=gcc
  set CXX=g++
  set CGO_ENABLED=1
  set GOMOD=D:\a\gauge\gauge\go.mod
  set GOWORK=
  set CGO_CFLAGS=-O2 -g
  set CGO_CPPFLAGS=
  set CGO_CXXFLAGS=-O2 -g
  set CGO_FFLAGS=-O2 -g
  set CGO_LDFLAGS=-O2 -g
  set PKG_CONFIG=pkg-config
  set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\RUNNER~1\AppData\Local\Temp\go-build15[27](https://github.com/getgauge/gauge/actions/runs/5603337007/jobs/10249808290#step:3:28)5[38](https://github.com/getgauge/gauge/actions/runs/5603337007/jobs/10249808290#step:3:39)[40](https://github.com/getgauge/gauge/actions/runs/5603337007/jobs/10249808290#step:3:41)7=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

No changes to the following, but tests on github actions is now failing on windows only.

```golang
handler := func(w http.ResponseWriter, r *http.Request) {
	http.NotFound(w, r)
}

server := httptest.NewServer(http.HandlerFunc(handler))
defer server.Close()
```

### What did you expect to see?

Tests are passing as before.

### What did you see instead?

```sh
... Panic: httptest: failed to listen on a port: listen tcp6 [::1]:0: socket: The requested service provider could not be loaded or initialized. (PC=0xC0A1F2)

C:/hostedtoolcache/windows/go/1.20.5/x64/src/runtime/panic.go:884
  in gopanic
C:/hostedtoolcache/windows/go/1.20.5/x64/src/net/http/httptest/server.go:71
  in newLocalListener
C:/hostedtoolcache/windows/go/1.20.5/x64/src/net/http/httptest/server.go:119
  in NewUnstartedServer
C:/hostedtoolcache/windows/go/1.20.5/x64/src/net/http/httptest/server.go:106
  in NewServer
httpUtils_test.go:52
  in MySuite.TestDownloadFailureIfSomeHTTPError
C:/hostedtoolcache/windows/go/1.20.5/x64/src/reflect/value.go:586
  in Value.call
C:/hostedtoolcache/windows/go/1.20.5/x64/src/reflect/value.go:370
  in Value.Call
C:/hostedtoolcache/windows/go/1.20.5/x64/src/runtime/asm_amd64.s:1598
  in goexit
```

**Comment by heschi** [comment]
cc @ianlancetaylor @neild

**Comment by bcmills** [comment]
(CC @golang/windows)

**Comment by alexbrainman** [comment]
@haroon-sheikh 

> ```shell
> The requested service provider could not be loaded or initialized.
> ```

This is WSAEPROVIDERFAILEDINIT Windows error message.

I googled for `The requested service provider could not be loaded or initialized.`, and I find https://travis-ci.community/t/socket-the-requested-service-provider-could-not-be-loaded-or-initialized/1127 which points me to https://github.com/golang/go/issues/25210 .

I suspect you are doing something similar to what happens in https://github.com/golang/go/issues/25210 .

Alex

**Comment by haroon-sheikh** [comment]
Thanks @alexbrainman for getting back. A couple of our unittests are calling `os.Clearenv()`. I wonder if it's clearing out `SYSTEMROOT` variable as well.

**Comment by alexbrainman** [comment]
> A couple of our unittests are calling `os.Clearenv()`. I wonder if it's clearing out `SYSTEMROOT` variable as well.

I would avoid calling `os.Clearenv()` on Windows. Different computers have different software / drivers installed on them. So environment variables used on each system will be different too.

Alex

**Comment by haroon-sheikh** [comment]
I have removed a couple of Clearenv() calls that was causing the failures. Thanks for your help.
