### ISSUE TITLE
x/website dev.go/dl uses Legacy ssl renegotation

### ISSUE THREAD

**Issue by Cybergenik** [golang/go#61479]
### System
MacOS 
wget: GNU Wget 1.21.4 built on darwin22.4.0.
openssl: LibreSSL 3.3.6

### Repro
```sh
❯ wget https://go.dev/dl/go1.20.6.src.tar.gz                                                                                                                                  ─╯
--2023-07-20 11:07:13--  https://go.dev/dl/go1.20.6.src.tar.gz
Resolving go.dev (go.dev)... 216.239.38.21, 216.239.32.21, 216.239.34.21, ...
Connecting to go.dev (go.dev)|216.239.38.21|:443... connected.
OpenSSL: error:0A000152:SSL routines::unsafe legacy renegotiation disabled
Unable to establish SSL connection.
```

### What did you expect to see?
File download

### What did you see instead?
`OpenSSL: error:0A000152:SSL routines::unsafe legacy renegotiation disabled`

### Fix

Probably just need to upgrade openssl for dev.go's web server

**Comment by heschi** [comment]
I can't reproduce, and https://www.ssllabs.com/ssltest/analyze.html?d=go.dev&s=216.239.34.21 says insecure renegotiation isn't supported. Please check that you aren't behind some kind of proxy or gateway that's intercepting the connection.

**Comment by heschi** [comment]
cc @golang/tools-team just in case

**Comment by Cybergenik** [comment]
I just verified, it was a proxy handling it with an outdated openssl. Closing
