### ISSUE TITLE
cmd/go: Remove support for relative import paths.

### ISSUE THREAD

**Issue by mewmew** [golang/go#6147]
<pre>Ref the discussion at golang-nuts &quot;Proposal: ban relative import paths&quot;.

<a href="https://groups.google.com/d/msg/golang-nuts/n9d8RzVnadk/07f9RDlwLsYJ">https://groups.google.com/d/msg/golang-nuts/n9d8RzVnadk/07f9RDlwLsYJ</a>

Posted by Andrew Gerrand on Apr 3:
&gt; See my earlier post in this thread about why relative imports are a bad idea.
&gt; 
&gt; The only reason the go tool supports relative imports is to run the compiler tests,
which predate the go tool and the concept of GOPATH. I would prefer to refactor the
compiler tests so that relative imports are not used, and remove support for relative
imports from the go tool entirely.
&gt; 
&gt; Andrew</pre>

**Comment by rsc** [comment]
I believe we should keep the limited support that exists today.
