### ISSUE TITLE
testing: skip flag not applied to examples

### ISSUE THREAD

**Issue by pascaldekloe** [golang/go#61482]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.21-9cf97cbbdd Fri Jul 14 16:37:04 2023 +0200 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

Run `go test -v strings -skip Trim`.

### What did you expect to see?

Regular expression "Trim" should skip `ExampleTrim`.

	-skip regexp
	    Run only those tests, examples, fuzz tests, and benchmarks that
	    do not match the regular expression.

### What did you see instead?

Go runs `ExampleTrim` anyway.

```
=== RUN   ExampleTrim
--- PASS: ExampleTrim (0.00s)
```

It does skip `TestTrim` though.

**Comment by heschi** [comment]
cc @bcmills

**Comment by bcmills** [comment]
@pascaldekloe, want to send a fix?

**Comment by mauri870** [comment]
@pascaldekloe I can try working on this if you don't mind ;)

**Comment by bcmills** [comment]
> There's too many bugs open in the Go command and they start to bother me now.

You're not wrong about the Go command (it bothers me too!), but technically this bug is in the `testing` package. 🙃
