### ISSUE TITLE
x/net/http/httpproxy: document proxy authentication support

### ISSUE THREAD

**Issue by gberche-orange** [golang/go#61505]
Many tools built with golang rely on the environment variables documented in https://pkg.go.dev/golang.org/x/net/http/httpproxy#Config to let their users specify the http proxy to use (e.g. HTTPS_PROXY and NO_PROXY), and don't offer other configuration mechanism to configure http proxies used by outgoing http requests they make.

Besides, many CLIs such as curl have adopted the [convention](https://superuser.com/a/1166790) of extracting proxy authentication basic auth username and password from the http proxy url such as HTTPS_PROXY=https://user:pwd@fqdn , see https://curl.se/docs/manpage.html#-x 
> Using an environment variable to set the proxy has the same effect as using the [-x, --proxy](https://curl.se/docs/manpage.html#-x) option. [...]
> User and password that might be provided in the proxy string are URL decoded by curl. This allows you to pass in special characters such as @ by using %40 or pass in a colon with %3a. 

Currently, the x/net/http/httpproxy#Config does not document the explicit support for username and password that would translate in http request made to comply with http proxy client authentication specified in https://datatracker.ietf.org/doc/html/rfc9110#section-11.7

This proposal suggests to document and implement as required such client proxy authentication support in proxy environment variables so that the golang binaries ecosystem relying on environment variables can leverage proxy authentication.

Note that the [Deprecation of userinfo in http(s) URIs in RFC9110](https://datatracker.ietf.org/doc/html/rfc9110#name-deprecation-of-userinfo-in-)  (as I understand it), does not preclude using user info in URIs for configuration such as environment variables, but rather aims at preventing propagating Uris with user info from untrusted sources (e.g. in emails messages in the context of  phishing attacks).

**Comment by seankhliao** [comment]
Moving out of proposals because there's nothing to change.
httpproxy already supports user:pass in urls, sending them in `Proxy-Authorization`.
Given that we document support for a complete URL, I'm not sure there's anything to do.
