### ISSUE TITLE
x/text/cmd/gotext: dir flag has no effect

### ISSUE THREAD

**Issue by miilord** [golang/go#61507]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.5 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/$USER/Library/Caches/go-build"
GOENV="/Users/$USER/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/$USER/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/$USER/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/opt/homebrew/Cellar/go/1.20.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.20.5/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.5"
GCCGO="gccgo"
AR="ar"
CC="cc"
CXX="c++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ql/c6vc6chx01z6269q2wwdhq3m0000gn/T/go-build4216456255=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I want to store the generated translation files in a specific directory,
so I used the following command
```bash
gotext -srclang=en -dir=./Foo update -out=./catalog.go -lang=en,zh
```

### What did you expect to see?
The following directories should be generated
```bash
.
├── Foo
│   ├── en
│   │   └── out.gotext.json
│   └── zh
│       └── out.gotext.json
├── catalog.go
└── translations.go
```

### What did you see instead?
```bash
.
├── catalog.go
├── locales
│   ├── en
│   │   └── out.gotext.json
│   └── zh
│       └── out.gotext.json
└── translations.go
```

**Comment by heschi** [comment]
cc @mpvl
