### ISSUE TITLE
govulncheck-action: apply for the Verified Creator tag

### ISSUE THREAD

**Issue by bplessis-swi** [golang/go#61503]
Hi,

Thanks for the publication of https://github.com/golang/govulncheck-action
It is however currently lacking the "verified creator" tag, is it something 

It would be great for re-usability.

**Comment by heschi** [comment]
cc @golang/security

**Comment by zpavlinovic** [comment]
Thanks for the suggestion, we are looking into this.

**Comment by zpavlinovic** [comment]
Thanks for the suggestion, we are looking into this.

**Comment by bplessis-swi** [comment]
I am so sorry i just saw i submitted the ticket while not having finished my sentences ...
Great news however, thanks !
