### ISSUE TITLE
select method bug

### ISSUE THREAD

**Issue by epowsal** [golang/go#61518]
if the select metod like this:
```
func thread(){
	for true {
		select {
		case <-stf.quitc:
			break tk5
		case <-ticker5sec.C:
			stf.heapmu.Lock()
			...
			stf.heapmu.Unlock()
		}
	}
}
some time run code:
func Close(){
	stf.quitc <- true
	stf.Flush()
	stf.dataf.Close()
	stf.bkheap.Clear()
}
after run line stf.quitc <- true.some time it will run to case <-ticker5sec.C:
it should be impossible.

this is the error code:
panic: runtime error: index out of range [6] with length 6

goroutine 11 [running]:
shortablefile.(*blockheap).Less(0x38?, 0xc0cd8b36c0?, 0xc000093ea0?)
	M:/work/code/go/src/shortablefile/blockheap.go:45 +0x55
container/heap.up({0x23d0fc0, 0xc000719a80}, 0x6?)
	M:/work/tool/go1.20.5.windows-amd64/src/container/heap/heap.go:92 +0x7e
container/heap.Fix({0x23d0fc0, 0xc000719a80}, 0xc000000003?)
	M:/work/tool/go1.20.5.windows-amd64/src/container/heap/heap.go:85 +0x5d
shortablefile.(*blockheap).Update(0xc000719a80, 0x93f08?, 0x1b)
	M:/work/code/go/src/shortablefile/blockheap.go:83 +0xb0
shortablefile.updateBlockSpeed(0xc0016ad0e0)
	M:/work/code/go/src/shortablefile/shorttablefile.go:118 +0x28f
created by shortablefile.Open
	M:/work/code/go/src/shortablefile/shorttablefile.go:103 +0x31b
```

windows go version 1.20.5.

this is the source code:

[shortablefile.zip](https://github.com/golang/go/files/12135631/shortablefile.zip)

run code very long time will cause this error.

**Comment by randall77** [comment]
We're going to need a complete runnable example if we're going to have any hope of finding a bug.

Please run with the race detector `-race` to see if it reports anything.

**Comment by epowsal** [comment]
the program are running very lang time almost some months.this is the full code. It is package full code. all method is safe. so this is the only one problem.

**Comment by randall77** [comment]
> this is the full code.

There's no `main` function, so I don't know how this could be all the code.
We're going to need some way to reproduce your problem in order to debug it. The listed stack trace is not helpful, at least not if the bug is indeed in the Go project and not yours. Without detailed repro instructions, we would at best be guessing what the problem is.

> all method is safe.

Does this mean you ran your program with the race detector, and it reported no races?

**Comment by thediveo** [comment]
Oh, what does the `...` instruction and in which Go version it was introduced? It looks very interesting, please tell me more!

**Comment by Nasfame** [comment]
@thediveo ... implies private code

**Comment by Nasfame** [comment]
@epowsal 
`panic: runtime error: index out of range [6] with length 6`

this is an error that occurs when u try to modify the structure of slice and try to access it simultaneously i.e concurrently. You can fix this by implementing mutex locks. 

To check the race condition as previously suggests you can pass in -race flag.

**Comment by epowsal** [comment]
I have use go build -race to build my program. the program are running some hours and it didn't have error generated. I checked this package's every parent package. every invoke is right. the shortablefile package Open parameter: Datl+Dabi=64; blocksize=262144; binmem=false;Maxblockind increase by time from 0; so bbh.deq length should not be 6. I have no ideal for the error.

**Comment by thediveo** [comment]
Doesn't this belong to the go-nuts forum, then with a fully self-contained example?

It could even be flaky hardware, but without sufficient details who'll know?

**Comment by epowsal** [comment]
I reimplement the package use right weight. the old package I will never investigate the reason.
