### ISSUE TITLE
x/vuln/internal/vulncheck/internal/buildinfo: broken at tip

### ISSUE THREAD

**Issue by heschi** [golang/go#61511]
```
#!watchflakes
post <- pkg == "golang.org/x/vuln/internal/vulncheck/internal/buildinfo" && test == "TestStrippedDarwin"
```

```
--- FAIL: TestStrippedDarwin (0.20s)
    --- FAIL: TestStrippedDarwin/darwin/amd64 (0.09s)
        additions_scan_test.go:109: reading go:func.*: no symbol "go:func.*"
```

across essentially all builders starting at http://go.dev/cl/506758.

cc @golang/vulndb @cherrymui

**Comment by cherrymui** [comment]
The test seems to be checking for old (buggy) behavior, maybe so it can be adjusted when needed (i.e. now). Related to #61051.

cc @zpavlinovic

**Comment by zpavlinovic** [comment]
This looks it is fixed now, but will keep it open for a bit longer.

**Comment by zpavlinovic** [comment]
The issue seems to be resolved. Closing.

**Comment by zpavlinovic** [comment]
For some reason still not known to me, this is testing the vuln repo from Jul 18th. This particular test should not be failing now.

**Comment by cherrymui** [comment]
The date is the commit date of the vuln repo commit, not the date where the test ran, nor the main repo commit date. This is probably newer Go commit run with an older vuln commit. I think it is probably safe to call it fixed. Thanks.
