### ISSUE TITLE
affected/package: syscall

### ISSUE THREAD

**Issue by ThankyouEverybody** [golang/go#61528]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.4 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

1.20.6 still appear

### What operating system and processor architecture are you using (`go env`)?
os: macOS Monterey 
version: 12.6.6  
chip: Apple M1 Pro
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOOS="darwin"
</pre></details>

### What did you do?

Hello:
Use `syscall.Mmap` to map the file to memory, append content to the file in memory, and find that the parameter `offset` can only be zero, if it is not zero, it will return error, `syscall.Errno`: EINVAL 22, message: invalid argument, why is there such a situation?
I don't want to map the entire content of the file into memory, I only need a part of the buffer, here is the code in question:

[https://go.dev/play/p/pDyfSxnki2f](https://go.dev/play/p/pDyfSxnki2f)
operation result
![image](https://github.com/golang/go/assets/38928746/f7dc36b8-050f-4b35-ae26-a3af8ef3f1ef)

after modification
[https://go.dev/play/p/onlb5U6csh2](https://go.dev/play/p/onlb5U6csh2)
![image](https://github.com/golang/go/assets/38928746/87f2dcf2-425a-49ef-8bd3-ce7622df53ef)

### What did you expect to see?
I hope the above code, the parameter `offset` can run normally when it is not 0.

I once suspected that the problem was caused by my `length` parameter, but I just changed `offset` to 0 and it can run normally. The `main` method is just a sample. In fact, I have to start multiple goroutine to process the function of writing files. Each goroutine has to write a lot of data in the file created by itself. If `offset` is equal to 0, the cost is that all the data in the file is mapped to the memory, which is a waste of system resources. If this is the case, it may not be as good as `file.Write() `The way to write data is efficient. Please fix it, thanks

### What did you see instead?
<img width="846" alt="image" src="https://github.com/golang/go/assets/38928746/3ab8f521-1b80-4811-b84b-8e0ef12314b4">

**Comment by randall77** [comment]
From `man mmap`, one of the causes for `EINVAL` is:

>     [EINVAL]           The offset argument was not page-aligned based on the page size as returned by getpagesize(3).

Are you passing page-aligned offsets?

**Comment by ThankyouEverybody** [comment]
It is my fate to meet you, thanks for the reminder, it is the problem of page-aligned offsets, which has been resolved.
