### ISSUE TITLE
x/tools/gopls: crash with modules named "command-line-arguments"

### ISSUE THREAD

**Issue by Martin-Jia** [golang/go#61543]
gopls version: v0.12.4 (go1.20.6)
gopls flags: 
update flags: proxy
extension version: 0.39.1
go version: 1.20.6
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Wed, 19 Jul 2023 16:26:40 GMT
restart history:
Wed, 19 Jul 2023 16:26:31 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

Failed to open any go file. It showed up that the gopls server crashed. Reopen window did not help.

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb8 pc=0xbfb1f8]

goroutine 3867 [running]:
golang.org/x/tools/gopls/internal/lsp/cache.(*snapshot).getPackageHandles.func1({0xc000e66080, 0x1a})
	  check.go:787  0x178
golang.org/x/tools/gopls/internal/lsp/cache.(*snapshot).getPackageHandles.func1({0xc001034e40, 0x52})
	  check.go:788  0x1d7
golang.org/x/tools/gopls/internal/lsp/cache.(*snapshot).getPackageHandles(0xc00440c000, {0x115b1f8, 0xc004359170}, {0xc0043579c0, 0x1, 0x0%3F})
	  check.go:792  0x246
golang.org/x/tools/gopls/internal/lsp/cache.(*snapshot).forEachPackage(0x115b1f8%3F, {0x115b1f8, 0xc004358ff0}, {0xc0043579c0, 0x1, 0x1}, 0xc0043579c0%3F, 0x0%3F)
	  check.go:341  0x1d9
golang.org/x/tools/gopls/internal/lsp/cache.(*snapshot).PackageDiagnostics(0xc003e04f68%3F, {0x115b1f8%3F, 0xc003aff380%3F}, {0xc0043579c0, 0x1, 0x1})
	  snapshot.go:666  0x1fc
golang.org/x/tools/gopls/internal/lsp.(*Server).diagnosePkgs.func1()
	  diagnostics.go:441  0x1dc
created by golang.org/x/tools/gopls/internal/lsp.(*Server).diagnosePkgs
	  diagnostics.go:434  0x205
[Error - 4:26:38 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by adonovan** [comment]
> We later found that the issue may potentially relate with the project module name. The module name used to be "command-line-arguments". After we changed it to another one, for example, github.com/x/y/z, the issue just disappeared.

I'm curious what motivated this choice of module name. Does the package actually concern command-line argument processing? Was the name chosen in a confused attempt to match the name of an ad-hoc package printed by go list? Or was this a case of naming your child [little bobby tables](https://xkcd.com/327/)? ;-)
