### ISSUE TITLE
go install `go.o' has malformed LC_DYSYMTAB, expected 130 undefined symbols to start at index 25593`

### ISSUE THREAD

**Issue by TerminalFi** [golang/go#61558]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.6 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/terminal/Library/Caches/go-build"
GOENV="/Users/terminal/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/terminal/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/terminal/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.20.6/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.20.6/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.6"
GCCGO="gccgo"
AR="ar"
CC="cc"
CXX="c++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_m/w_k_jtfx1v9grbk7mb11p50c0000gn/T/go-build1236678511=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

`go install -x "golang.org/x/tools/gopls@latest"`

### What did you expect to see?

Gopls updated / installed

### What did you see instead?

<pre>
# get https://proxy.golang.org/golang.org/@v/list
# get https://proxy.golang.org/golang.org/x/@v/list
# get https://proxy.golang.org/golang.org/x/tools/@v/list
# get https://proxy.golang.org/golang.org/x/tools/gopls/@v/list
# get https://proxy.golang.org/golang.org/x/tools/gopls/@v/list: 200 OK (0.301s)
# get https://proxy.golang.org/golang.org/@v/list: 404 Not Found (0.338s)
# get https://proxy.golang.org/golang.org/x/@v/list: 404 Not Found (0.338s)
# get https://proxy.golang.org/golang.org/x/tools/@v/list: 200 OK (0.362s)
WORK=/var/folders/_m/w_k_jtfx1v9grbk7mb11p50c0000gn/T/go-build2658121465
cat /Users/terminal/Library/Caches/go-build/b3/b3417aa71b46521aeb15441951d0ab93a3c7205b01469028bbbe99e6cb293aa3-d  # internal
# golang.org/x/tools/gopls
ld: warning: '/private/var/folders/_m/w_k_jtfx1v9grbk7mb11p50c0000gn/T/go-link-3541256822/go.o' has malformed LC_DYSYMTAB, expected 130 undefined symbols to start at index 25593, found 139 undefined symbols starting at index 77
</pre>

**Comment by cherrymui** [comment]
See #61229 (especially the NOTE at the top) and #61190. Closing as duplicate. Thanks.
