### ISSUE TITLE
x/tools/gopls: remove convenience analyzers (cleanup)

### ISSUE THREAD

**Issue by findleyr** [golang/go#61559]
Reminder issue: CL 511995 left now-pointless shells for "convenience analyzers", which were refactored to be computed outside of the analysis framework.

We should clean up, though doing so will mean that these analyzers are no longer configurable via the [`"analyses"`](https://github.com/golang/tools/blob/master/gopls/doc/settings.md#analyses-mapstringbool) setting. That's probably fine; if necessary we can introduce a new way to configure refactorings, but I'd rather not do that if unnecessary.

**Comment by adonovan** [comment]
Didn't you do this already?

**Comment by findleyr** [comment]
As you noted in your CL, we need to decide what to do with configuration.

I think we can honor the old configuration for a release or two, and then remove it. I don't think there's a strong reason to make code actions configurable, since they are much less intrusive than diagnostics.
