### ISSUE TITLE
Go Installer doesn't address Windows incompatibility

### ISSUE THREAD

**Issue by sivan-koren** [golang/go#61562]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.6 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
n/a
</pre></details>

### What did you do?
Installed Go.

### What did you expect to see?
The Go installer or documentation should warn users of incompatibility with default Windows components/configuration.

See #61560: https://github.com/golang/go/issues/61560

### What did you see instead?
It doesn't.

**Comment by seankhliao** [comment]
this does not appear to be default configuration, we don't get many reports of it.

see also https://groups.google.com/g/golang-nuts/c/IR8v3B1pPCI/m/-yrCL_j0HAAJ
and https://golang.org/doc/faq#virus

**Comment by sivan-koren** [comment]
I don't see how locking recent Go groups and closing issues with no
resolution is any indication that this is not a common issue.

Obviously if people can't report it, then it will wrongfully be assumed to
be uncommon.

**Comment by sivan-koren** [comment]
Just confirming. Windows complains investing when these features are turned
off, so we can absolutely conclude that they are indeed default
configuration. They are also newly released, and I don't see that they are
documented anywhere in relation to Go.

I've tested on 3 machines at this point and in all cases disabling them
resolved the issue.

For others experiencing this issue as these updates roll out, please post.

**Comment by sivan-koren** [comment]
Microsoft is unlikely to update Go installation files and documentation. That's what this GitHub is for. Or at least, what it purports to be.
