### ISSUE TITLE
Go Build is Slow w/ Latest Windows Updates

### ISSUE THREAD

**Issue by sivan-koren** [golang/go#61560]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.6 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?
Windows 11 amd64
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

Open a terminal
Navigate to directory with the package main
Execute "go build"

### What did you expect to see?
A fast build time.

### What did you see instead?
A very, very, very long build time.

<p>
**Issue:**
With recent Windows 11 updates, and likely other Windows versions, it appears that the build process is hanging for long periods of time. The issue is not manifest when disabling the following new Windows components:

- Cloud-delivered protection
- Automatic Sample Submission

While I'm aware that this is not explicitly a Go issue, it is nonetheless common place for applications built for Windows to play nice with the Windows ecosystem by doing things upon installation like disabling or warning about incompatible Windows settings and features.

It might also be a good idea to offer to add temporary build directories to the Windows Defender exclusion list, or advise users about how to do that somewhere in some documentation. I didn't find any, and no one on the Go forum appears to know where to find these. Or at least no one so far.

**Comment by seankhliao** [comment]
sounds like a windows defender specific issue, not go.

**Comment by sivan-koren** [comment]
That's surprising and disappointing. Is Go abandoning Windows compatibility altogether?

**Comment by ianlancetaylor** [comment]
Go is an open source project.  If you want to send in a documentation patch, that would be fine.  Thanks.

**Comment by sivan-koren** [comment]
Yes I tried to submit a docs issue and it was closed immediately without investigation.
I'd rather discuss and investigate with experts before submitting my own personal research on the topic.
Is there somewhere that experts can discuss issues and share potential solutions besides the issues board on GitHub where they are apparently closed indiscriminately?

**Comment by ianlancetaylor** [comment]
We don't use the issue tracker for discussion.  For good places to discuss Go issues see https://go.dev/wiki/Questions.

**Comment by sivan-koren** [comment]
Thanks, @ianlancetaylor. That makes sense. I should have checked the bottom of the readme.
