### ISSUE TITLE
proxy.golang.org: github.com/chargehound/chargehound-go@v8.6.2

### ISSUE THREAD

**Issue by aggarwalvinay** [golang/go#61569]
Release a new version v8.6.2 of chargehound but the new version is still not visible on the go pkg.
Link to the new tag: https://github.com/chargehound/chargehound-go/releases/tag/v8.6.2

**Comment by seankhliao** [comment]
wrong module line declaration in go.mod, it should only include the major version.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
