### ISSUE TITLE
x/website: go.dev/dl "Other Ports" link does not work

### ISSUE THREAD

**Issue by rsc** [golang/go#61587]
When I visit https://go.dev/dl in Chrome, under the list of file downloads for first-class ports for each version, there is text that says "Other Ports ^". Clicking on it does nothing at all.

I assume that is supposed to open a toggle that shows the non-first-class ports, but it's not.

The toggle under "Unstable version" to open the go1.21rc3 list works, so it's not like JavaScript is completely broken. That version lists all the ports in one big list instead of splitting by "Other Ports". The split is better for the stable versions; we just need the toggle to work.

/cc @jamalc

**Comment by mauri870** [comment]
CL https://go-review.googlesource.com/c/website/+/513315

**Comment by rsc** [comment]
Thank you @mauri870!
