### ISSUE TITLE
x/pkgsite: package removal request for github.com/odin-cyble/odin-sdk-go

### ISSUE THREAD

**Issue by cyble-dev** [golang/go#61592]
### What is the path of the package that you would like to have removed?
https://pkg.go.dev/github.com/odin-cyble/odin-sdk-go
 
 
 
### Are you the owner of this package?
yes

 
### What is the reason that you could not retract this package instead?
Github url is changed for this package

**Comment by bcmills** [comment]
Please fill out the complete issue template. What is the reason you could not retract this package instead?

**Comment by cyble-dev** [comment]
updated the issue

**Comment by bcmills** [comment]
`retract` directives intentionally allow mismatched module paths. You should be able to publish a `retract` directive in the `go.mod` file for https://github.com/cybledev/odin-sdk-go that retracts all of the versions predating the change in module path.

**Comment by cyble-dev** [comment]
Hey,
https://github.com/cybledev/odin-sdk-go this sdk is a different package that we are publishing along with the licence,
so we surely want to remove the  https://github.com/odin-cyble/odin-sdk-go pkg without any retract or versioning.

Can you please remove this https://github.com/odin-cyble/odin-sdk-go package ?

**Comment by bcmills** [comment]
Given that both URLs redirect to the same repository, you should be able to just `retract` the pseudo-versions up to the commit where the module path was changed. Something like:

```go.mod
retract [v0.0.0-0, v0.0.0-20230725131200-b3179dd121e0]  // Old module path; no license present.
```
