### ISSUE TITLE
cmd/go: missing name of failed command in error

### ISSUE THREAD

**Issue by rsc** [golang/go#61604]
Looks like I broke an error path when I refactored this code to enable toolchain updates:

```
% go1.20 asdf
go asdf: unknown command
Run 'go help' for usage.
% go asdf
go : unknown command
Run 'go help' for usage.
% 
```

Note the missing asdf in the second error message.

**Comment by dmitshur** [comment]
Reopening to track CL submission to release-branch.go1.21.

**Comment by dmitshur** [comment]
Closed by merging [CL 515278](https://go.dev/cl/515278) (commit 07c72a0915093feb9837dbcbc963810a3efcb6b6) to release-branch.go1.21.
