### ISSUE TITLE
x/pkgsite: cs.opensource.google does not offer Raw links

### ISSUE THREAD

**Issue by 1268** [golang/go#61603]
### What is the URL of the page with the issue?
 
If I go here:

https://pkg.go.dev/fmt#Println
 
### What did you do?

I followed the link above to the linked source:

https://cs.opensource.google/go/go/+/go1.20.6:src/fmt/print.go
 
### What did you expect to see?
 
if I visit the same file on GitHub:

https://github.com/golang/go/blob/go1.20.6/src/fmt/print.go

a Raw link is available:

https://raw.githubusercontent.com/golang/go/go1.20.6/src/fmt/print.go
 
### What did you see instead?

I do not see any any such Raw link on `cs.opensource.google`.

**Comment by seankhliao** [comment]
please use the feedback form for cs.opensource.google.
this is out of scope for the go issue tracker.

**Comment by 1268** [comment]
> please use the feedback form for cs.opensource.google.

I dont know where that is.

**Comment by 1268** [comment]
thanks @fzipp. as usual @seankhliao assistance is "unique".

**Comment by seankhliao** [comment]
the issue tracker is scoped to bugs and proposals for the go project specifically, discouraging everything else to prevent it becoming a (support) forum.

**Comment by 1268** [comment]
it seems it would be in scope to propose to move the pkgsite links to GitHub instead of cs.opensource.google.

if you agree, then please reopen and I can rename the issue, or post a new issue.

**Comment by seankhliao** [comment]
#47202
