### ISSUE TITLE
x/pkgsite: package removal request for github.com/Azure/azure-sdk-for-go/sdk/cognitiveservices/azopenai

### ISSUE THREAD

**Issue by richardpark-msft** [golang/go#61616]
### What is the path of the package that you would like to have removed?

github.com/Azure/azure-sdk-for-go/sdk/cognitiveservices/azopenai
 
### Are you the owner of this package?

Yes - primary code contributor and owner within the Azure SDK.
 
### What is the reason that you could not retract this package instead?

We're moving this package to a new location (new: github.com/Azure/azure-sdk-for-go/sdk/ai/azopenai). We've marked the the previous package as deprecated and now just want to ensure nobody else picks it up.

**Comment by seankhliao** [comment]
you should be able to do this yourself with `retract`.

**Comment by richardpark-msft** [comment]
@seankhliao , just to check - if we retract this version (and all other versions of this package) will that completely eliminate it from showing up on pkg.go.dev? We're worried people will see the old and new packages and just want the older package to disappear entirely.

**Comment by suzmue** [comment]
If all versions of the package are retracted, that should completely eliminate it from pkg.go.dev. 

From https://go.dev/ref/mod#go-mod-file-retract

> Wiping out a module including all pseudo-versions and tagged versions:
> ```
> retract [v0.0.0-0, v0.1.2]  // assuming v0.1.2 contains this retraction.
> ```

**Comment by richardpark-msft** [comment]
Thank you @suzmue and @seankhliao, I'll do that. Closing this because you two have taught me a valuable lesson - the true power was in my hands the entire time. ;)

**Comment by richardpark-msft** [comment]
Hey all, sorry to reopen this. 

I published a 'retract' for our `github.com/Azure/azure-sdk-for-go/sdk/cognitiveservices/azopenai` (the old package) but it hasn't removed the old entry from pkg.go.dev.

The version I published (v0.1.2) isn't showing up in the versions list for the package:
https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/cognitiveservices/azopenai?tab=versions

Here's our go.mod, which shows the `retract`:
https://github.com/Azure/azure-sdk-for-go/blob/4b91f97771d98ea60da9fb1139e03d40c10245b7/sdk/cognitiveservices/azopenai/go.mod#L6

I believe I've got the proper metadata because, when I try to pull the old package version, it gives me the `retract` message:

```
go get github.com/Azure/azure-sdk-for-go/sdk/cognitiveservices/azopenai@v0.1.2
go: module github.com/Azure/azure-sdk-for-go/sdk/cognitiveservices/azopenai is deprecated: use github.com/Azure/azure-sdk-for-go/sdk/ai/azopenai instead
go: warning: github.com/Azure/azure-sdk-for-go/sdk/cognitiveservices/azopenai@v0.1.2: retracted by module author: use github.com/Azure/azure-sdk-for-go/sdk/ai/azopenai instead.
go: to switch to the latest unretracted version, run:
        go get github.com/Azure/azure-sdk-for-go/sdk/cognitiveservices/azopenai@latest
```

**Comment by findleyr** [comment]
Hi, sorry for the slow response -- this popped up on our radar again thanks to @seankhliao removing the label.

It appears that those versions *are* retracted (as labeled in pkg.go.dev), and don't show up in search results, but are still viewable.

I'll exclude the path entirely.

**Comment by richardpark-msft** [comment]
@findleyr, thank you for the help, really appreciate it. :)

**Comment by findleyr** [comment]
Looks like this is done now.
