### ISSUE TITLE
x/website: https://go.dev/security/vuln/editor#editor-specific-instructions

### ISSUE THREAD

**Issue by falco467** [golang/go#61633]
### What is the URL of the page with the issue?
 https://go.dev/security/vuln/editor#editor-specific-instructions
 
 
### What did you expect to see?
 
 The settings for VS-Code should be `"ui.codelenses"`
 
### What did you see instead?

```
"go.diagnostic.vulncheck": "Imports", // enable the imports-based analysis by default.
"gopls": {
  "codelenses": {
    "run_govulncheck": true  // "Run govulncheck" code lens on go.mod file.
  }
}
```

**Comment by dr2chase** [comment]
@golang/tools-team
(added NeedsFix because it needs a fix and otherwise it clutters the untriaged bugs list)

**Comment by suzmue** [comment]
These settings are passed through directly to gopls, which accepts either `"ui.codelenses"`, or `"codelenses"` (but not both at the same time).

Since this section references the VS Code settings explicitly, this should be updated to match the VS Code style of `"ui.codelenses"'
