### ISSUE TITLE
x/mobile: Is it possible to import multiple gomobile package into iOS project?

### ISSUE THREAD

**Issue by asdfsx** [golang/go#61631]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.6 darwin/amd64

</pre>

### What did you do?

I create 2 simple package `sdk2` & `sdk3` with the following code

```
import (
	"fmt"
)
type Support struct {
}
func NewSupport() *Support {
	return &Support{}
}
func (s *Support) Echo() *Support {
	fmt.Println("Init Support Library")
	return s
}
```

then I create 2 package 
```
gomobile bind --ldflags -target ios -o ios/sdk2.xcframework -v -x ./sdk2
gomobile bind --ldflags -target ios -o ios/sdk3.xcframework -v -x ./sdk3
```

And import them into a simple XCode Project, with only one button and invocae the package like below

```
import Sdk2
import Sdk3

...
            Button(action: {
                print("keygen")
                let platformAddress = "172.18.1.16:50055"
                let token = "token4test"
                let su2 = Sdk2.Sdk2NewSupport()
                su2!.echo()
                let su3 = Sdk3.Sdk3NewSupport()
                su3!.echo()
            }){
                Text("Keygen")
                    .font(.system(size: 14))
                    .frame(minWidth: 0, maxWidth:.infinity)
                    .padding()
                    .foregroundColor(.white)
                    .background(Color(red: 88 / 255, green: 224 / 255, blue: 133 / 255))
                    .cornerRadius(5)
                    .padding(.horizontal, 20)
            }
...
```

### What did you see ?

I build the project and execute the project in the simulator, and the simulator crashed very quick, with the error `Thread 1: EXC_BAD_ACCESS (code=1, address=0x10)`

If I remove one of the invocation the simulator won't crash.

I know this is not a normal use case, I  just wanna know whether it is possible to import multiple `gomobile` packages in one project

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by asdfsx** [comment]
> Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.
> 
> For questions please refer to https://github.com/golang/go/wiki/Questions

But it looks like a bug to me , may be I should change the name of the issue
