### ISSUE TITLE
x/sys/unix: fchmodat2 will handle flags in Linux 6.6

### ISSUE THREAD

**Issue by mauri870** [golang/go#61636]
The current go implementation of Fchmodat has some workarounds since the flags argument on Linux is ignored:

flags can be `0` or `AT_SYMLINK_NOFOLLOW` for POSIX

```go
func Fchmodat(dirfd int, path string, mode uint32, flags int) (err error) {
	// Linux fchmodat doesn't support the flags parameter. Mimick glibc's behavior
	// and check the flags. Otherwise the mode would be applied to the symlink
	// destination which is not what the user expects.
	if flags&^AT_SYMLINK_NOFOLLOW != 0 {
		return EINVAL
	} else if flags&AT_SYMLINK_NOFOLLOW != 0 {
		return EOPNOTSUPP
	}
	return fchmodat(dirfd, path, mode)
}
```

There is a [proposed patch](https://lwn.net/ml/linux-kernel/cover.1689092120.git.legion@kernel.org/) that creates a new version of this syscall (fchmodat2) that handles the posix flag `AT_SYMLINK_NOFOLLOW` properly at the kernel level.

When made accessible in the release kernel, library implementations will be able to utilize it for their fchmodat() implementation, circumventing the need for existing workarounds.

**Comment by mauri870** [comment]
Related to #20130

**Comment by bcmills** [comment]
(CC @tklauser)

**Comment by anton-kuklin** [comment]
@tklauser Would be happy to work on it, if you don't mind

**Comment by ianlancetaylor** [comment]
I don't see how to do this safely.  Usually we can try the system call and do something else if it fails, but that doesn't seem to work here.  Do we have to look at the kernel version to see whether the flags argument is supported?

**Comment by mauri870** [comment]
I'm not aware of another way to handle this as well. There is not much detail on this yet but I imagine we could somehow check if fchmodat2 is available and then use it or rely on the kernel version.

**Comment by bcmills** [comment]
Presumably we could call `fchmodat2`, and if it returns `EINVAL` or `ENOSYS` we could fall back to `fchmodat`.

(Although we would probably also have to deal with bad container implementations that return some bogus error like `EPERM` for new or unrecognized syscalls. 😩)

**Comment by ianlancetaylor** [comment]
Sorry, I missed that it was an entirely new system call.  We can handle that.

**Comment by tklauser** [comment]
> Presumably we could call `fchmodat2`, and if it returns `EINVAL` or `ENOSYS` we could fall back to `fchmodat`.

Another option would be to only call `fchmodat2` if `flags != 0`, or even better if there are only valid flags, i.e. `flags&(AT_SYMLINK_NOFOLLOW|AT_EMPTY_PATH) != 0` and continue using `fchmodat` for `flags==0`, something like:

```go
func Fchmodat(dirfd int, path string, mode uint32, flags int) error {
        // Linux fchmodat doesn't support the flags parameter, but fchmodat2 does. Try fchmodat2
        // first, but only if flags are specified. If fchmodat2 is not available, mimick glibc's
        // behavior and check the flags. Otherwise the mode would be applied to the symlink
        // destination which is not what the user expects.
        if flags&^(AT_SYMLINK_NOFOLLOW|AT_EMPTY_PATH) != 0 {
                return EINVAL
        } else if flags&(AT_SYMLINK_NOFOLLOW|AT_EMPTY_PATH) != 0 {
                return fchmodat2(dirfd, path, mode, flags)
        }
        return fchmodat(dirfd, path, mode)
}
```

> (Although we would probably also have to deal with bad container implementations that return some bogus error like `EPERM` for new or unrecognized syscalls. 😩)

That way the caller would have to deal with the bogus errors. Or we could just keep returning `EOPNOTSUPP` for any `fchmodat2` error :thinking:

**Comment by mauri870** [comment]
@tklauser Thanks for sending a CL, I forgot to update here but after [CL538378](https://go-review.googlesource.com/c/sys/+/538378) was merged we now have access to SYS_FCHMODAT2 in x/sys.

Regarding the implementation, I agree with your solution, seems to handle the corner cases properly.

I also found this [patch for glibc to use fchmodat2](https://patchwork.sourceware.org/project/glibc/patch/20231030213245.2626895-7-adhemerval.zanella@linaro.org/), maybe we can reason about it for the implementation details.

I was also unable to find any man pages for fchmodat2, not sure if it was deliberately ommited, or there is just no man pages for it in the [man-pages project](https://git.kernel.org/pub/scm/docs/man-pages/man-pages.git/tree/man2).

**Comment by dmitshur** [comment]
Adding a note for reference.

> (Although we would probably also have to deal with bad container implementations that return some bogus error like `EPERM` for new or unrecognized syscalls. 😩)
>
> That way the caller would have to deal with the bogus errors.

I happened to run into exactly this during earlier WIP iterations of the upcoming linux/arm LUCI builder, and the problem was that the caller was `TestFchmodat` in the tree, which was [failing](https://ci.chromium.org/ui/p/golang/builders/ci/x_sys-gotip-linux-arm/b8756803781222073521/test-results) due to `EPERM` being returned instead of `EOPNOTSUPP`:

```
=== RUN   TestFchmodat
    syscall_unix_test.go:780: Fchmodat: unexpected error: operation not permitted
--- FAIL: TestFchmodat (0.00s)
```

Fortunately, it's viable for the container on that builder to run with `--security-opt=seccomp=unconfined`, the same approach we've used in #35547, and that is enough to get it to return the expected `EOPNOTSUPP` and have the test pass without introducing other problems.
