### ISSUE TITLE
x/pkgsite: package removal request for [type path here]

### ISSUE THREAD

**Issue by anukul-001182** [golang/go#61630]
### What is the path of the package that you would like to have removed?
https://pkg.go.dev/github.com/anukul-001182/odin-sdk-Go/api/certificate
 
 
 
### Are you the owner of this package?
yes

 
### What is the reason that you could not retract this package instead?
Now i don't need this, I have deleted this package from my github too

**Comment by seankhliao** [comment]
please try following the instructions at https://github.com/golang/go/issues/60985#issuecomment-1607712161
