### ISSUE TITLE
x/website: tutorial index has wrong links for govulncheck pages

### ISSUE THREAD

**Issue by seedpower** [golang/go#61663]
### What is the URL of the page with the issue?
 https://go.dev/doc/tutorial/
 
 
### What is your user agent?
 

 [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36](https://explore.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)
 
 
### Screenshot
 

 
![image](https://github.com/golang/go/assets/11022830/3c9fecc0-f92b-4fe5-afcf-e34b9349052a)

 
 
### What did you do?
 

 Click links.
 
 
### What did you expect to see?
 Show the right web page.
 
 
### What did you see instead?
404, page not found.
https://go.dev/doc/tutorial/doc/tutorial/govulncheck -> https://go.dev/doc/tutorial/govulncheck
https://go.dev/doc/tutorial/doc/tutorial/govulncheck-ide -> https://go.dev/doc/tutorial/govulncheck-ide

**Comment by seankhliao** [comment]
cc @golang/vulndb
