### ISSUE TITLE
x/tools/gopls: remove double space in "func" snippets

### ISSUE THREAD

**Issue by mochamadhaikal** [golang/go#61660]
I don't feel comfortable with this "func" snippet. it has 2 spaces before the opening curly brace
<img width="109" alt="Screen Shot 2023-07-31 at 10 59 18" src="https://github.com/golang/go/assets/63646491/cb027f52-6ba1-4339-898b-3603ba3ab94a">
Maybe the "go" creators can change this🙏🏿🙏🏿

**Comment by findleyr** [comment]
Thanks, this is a bug. We'll fix in the next patch release.

**Comment by findleyr** [comment]
Sorry, looking at your screenshot again, I'm not sure this is a bug. It looks like there's a tabstop to write the result type.

Also, I don't think this is a gopls snippet. Looks like it may be a VS Code snippet?

**Comment by findleyr** [comment]
Closing this as WAI, since this isn't actionable for gopls.

**Comment by mochamadhaikal** [comment]
yes, it's in vscode. sorry, looks like it's a go extension error in vscode
