### ISSUE TITLE
proxy.golang.org: github.com/confidential-containers/cloud-api-adaptor@v0.7.0 uses wrong hash

### ISSUE THREAD

**Issue by snir911** [golang/go#61668]
It seems like proxy.golang.org points [github.com/confidential-containers/cloud-api-adaptor@v0.7.0](https://github.com/confidential-containers/cloud-api-adaptor/commits/v0.7.0) to [6d7d2a3fe8243809b3c3a710792c8498292e2fc3](https://github.com/confidential-containers/cloud-api-adaptor/commit/6d7d2a3fe8243809b3c3a710792c8498292e2fc3) rather than [aac894721b23c07b83dd2d36abba9f94b9b36a2c](https://github.com/confidential-containers/cloud-api-adaptor/commit/aac894721b23c07b83dd2d36abba9f94b9b36a2c) which is the correct commit which is tagged by [v0.7.0](https://github.com/confidential-containers/cloud-api-adaptor/commits/v0.7.0)

**Comment by seankhliao** [comment]
looks like they moved a tag, by design the proxy doesn't allow it.
