### ISSUE TITLE
x/tools/gopls: improve error message when user needs newer go version

### ISSUE THREAD

**Issue by hyangah** [golang/go#61673]
### go version

go 1.21rc3
gopls v0.13.0

### How to reproduce the issue

```
-- go.mod --
module example.com

go 1.23
```

And start gopls from this directory.

![Screenshot 2023-07-31 at 12 42 10 PM](https://github.com/golang/go/assets/4999471/98ad68a8-1e40-43d7-b7c2-392ac8dcb16e)

go1.23 is not available so this error is expected. (Users who have `GOTOOLCHAIN=local` env would experience similar issues). But the error message that references a temporary go.mod file can be potentially confusing for users. Either rewrite the error message or at least, replace the temporary go.mod file with the original go.mod file in the message.

And this diagnostic is attached to the "module" line. But for this specific error, I think the "go" line may be more suitable if feasible.

![Screenshot 2023-07-31 at 12 45 43 PM](https://github.com/golang/go/assets/4999471/47fb7122-8e66-4873-9747-5daef683abe2)

**Comment by findleyr** [comment]
I think we should no longer use a temp mod file in this case, since the go command should no longer mutate the mod file.

**Comment by findleyr** [comment]
As of https://go.dev/cl/579439 we no longer use a temp mod file for loads, so this error message should be improved.
