### ISSUE TITLE
x/tools/gopls: broken import error with v0.13.0

### ISSUE THREAD

**Issue by TJDev** [golang/go#61687]
### gopls version

Build info
----------
golang.org/x/tools/gopls v0.13.0
    golang.org/x/tools/gopls@v0.13.0 h1:ZUvkm53dJpJ9sUXWtgH39rD53JyQ9/vwB1cpI7swnGo=
    github.com/BurntSushi/toml@v1.2.1 h1:9F2/+DoOYIOksmaJFPw1tGFy1eDnIJXg+UHjuD8lTak=
    github.com/google/go-cmp@v0.5.9 h1:O2Tfq5qg4qc4AmwVlvv0oLiVAGB7enBSJ2x2DqQFi38=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/exp@v0.0.0-20220722155223-a9213eeb770e h1:+WEEuIdZHnUeJJmEUjyYC2gfUMj69yZXw17EnHg/otA=
    golang.org/x/exp/typeparams@v0.0.0-20221212164502-fae10dda9338 h1:2O2DON6y3XMJiQRAS1UWU+54aec2uopH3x7MAiqGW6Y=
    golang.org/x/mod@v0.12.0 h1:rmsUpXtvNzj340zd98LZ4KntptpfRHwpFOHG188oHXc=
    golang.org/x/sync@v0.3.0 h1:ftCYgMx6zT/asHUrPw8BLLscYtGznsLAnjq5RH9P66E=
    golang.org/x/sys@v0.10.0 h1:SqMFp9UcQJZa+pmYuAKjd9xq1f0j5rLcDIk0mj4qAsA=
    golang.org/x/text@v0.11.0 h1:LAntKIrcmeSKERyiOh0XMV39LXS8IE9UL2yP7+f5ij4=
    golang.org/x/tools@v0.11.1-0.20230727183555-65b14ec44dc9 h1:KyJgiheQsNju4tb8D6MzAlWqI0YS5LbPyDgitUfKCZg=
    golang.org/x/vuln@v0.0.0-20230110180137-6ad3e3d07815 h1:A9kONVi4+AnuOr1dopsibH6hLi1Huy54cbeJxnq4vmU=
    honnef.co/go/tools@v0.4.2 h1:6qXr+R5w+ktL5UkwEbPp+fEvfyoMPche6GkOpGHZcLc=
    mvdan.cc/gofumpt@v0.4.0 h1:JVf4NN1mIpHogBj7ABpgOyZc65/UUOkKQFkoURsz4MM=
    mvdan.cc/xurls/v2@v2.4.0 h1:tzxjVAj+wSBmDcF6zBB7/myTy3gX9xvi8Tyr28AuQgc=
go: go1.20.5

### go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/me/Library/Caches/go-build"
GOENV="/Users/me/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/me/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/me/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.20.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.20.5/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.20.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="cc"
CXX="c++"
CGO_ENABLED="1"
GOMOD="/Users/me/workspace/development-docker/services/go-data-sync-service/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/l_/rs2k5yxs53v2fr45pf28q_080000gn/T/go-build2487342215=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?

I upgraded from version 0.12.4 to 0.13.0.

### What did you expect to see?

No errors

### What did you see instead?

After upgrading from version 0.12.4 to 0.13.0, I am getting in multiple files the following or similar broken import error:
```
runtime error: index out of range [36] with length 5
```
The error is shown with some but not all internal packages. Most of them seem to result to one package but no file in this package shows any error and the code there is untouched since some months.

**Comment by kuna** [comment]
Suffering from same issue on v0.13. I dropped an logfile to see is there anything to debug but it didn't helped.

**Comment by findleyr** [comment]
Thanks for the report. This is fixed in v0.13.1-pre.1 (please `go install golang.org/x/tools/gopls@v0.13.1-pre.1` to confirm). We'll release v0.13.1 today.

**Comment by findleyr** [comment]
Thanks for confirming, and sorry for the breakage.

**Comment by findleyr** [comment]
Actually, I'll leave this open for visibility, until v0.13.1 is released.
