### ISSUE TITLE
x/pkgsite:

### ISSUE THREAD

**Issue by BOTbkcd** [golang/go#61680]
### What is the URL of the page with the issue?
 https://pkg.go.dev/github.com/BOTbkcd/mayhem
 
 
### What is your user agent?
[Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36](https://explore.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)
 

 
 
 
### Screenshot
 

 
![image](https://github.com/golang/go/assets/83156045/1f437c6b-4155-4a7d-a94c-20b29dc408b8)

 
 
### What did you do?
 So far I have released v1.0.0 & v1.1.0 for my go package on github: https://github.com/BOTbkcd/mayhem/releases

 
 
 
### What did you expect to see?
 I was expecting to see only those releases (v1.0.0 & v1.1.0) to be shown on the go pkg site
 
 
### What did you see instead?
I am seeing v1.0.1 & v1.0.2 listed on go pkg site. They might reflect the old state of my project which has since been scrapped. But the go pkg site is not showing the updated state.

**Comment by seankhliao** [comment]
pkgsite doesn't actively scrape modules, did you pull your updates releases through the proxy?

**Comment by rsc** [comment]
It looks like you tagged v1.1.0 at 6:02pm and then filed this issue at 6:17pm. The proxy does not notice new things on GitHub automatically. It would notice eventually, or you can run 'go mod download pkg@version' (with the default GOPROXY setting) or visit https://pkg.go.dev/pkg@version to trigger a load. Even then it may take up to 30 minutes for various caches to expire. See https://proxy.golang.org/ for details, especially the FAQ.

It looks like pkg.go.dev is showing the latest version now.
