### ISSUE TITLE
x/pkgsite:[feature request] Interface with fields

### ISSUE THREAD

**Issue by mahesh-riddles** [golang/go#61683]
Everything is wonderful.

Whenever I am defining a contract in the application, without fields, I have to manually check the contracts.
If the interface can support fields, it will be a great help for programmer like me.

Is that possible to force interface to check if the implementing type has certain fields?
Is there any hack right now for this kind of work?

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by mahesh-riddles** [comment]
Thank you so much. My motto is not about asking question. I just wanted to have a **feature** in which i**nterfaces** can have **fields**. May be, I am good with English.

**Comment by mahesh-riddles** [comment]
Yes you are right. This is what I asked. When I discuss this in the go forum, I understood that it is not needed actually.
When started to use go from another language, brain expects go to be same. (which is not.. :-) )
