### ISSUE TITLE
x/crypto/ssh: unexpected packet

### ISSUE THREAD

**Issue by gopherbot** [golang/go#6169]
by **maciek@heroku.com**:

<pre>What steps will reproduce the problem?
If possible, include a link to a program on play.golang.org.
1. Run this test in sshpool: <a href="https://github.com/kr/sshpool/blob/master/pool_test.go#L108">https://github.com/kr/sshpool/blob/master/pool_test.go#L108</a>

What is the expected output?

The session should fail (due to the timeout) with a well-understood error

What do you see instead?

This will hit this unexpected code path in ssh/channel.go:
code.google.com/p/go/source/browse/ssh/channel.go?repo=crypto#489

Which compiler are you using (5g, 6g, 8g, gccgo)?

6g

Which operating system are you using?

Ubuntu 13.04 / Linux 3.8.0-27 x86_64

Which version are you using?  (run 'go version')

go version devel +01810e5c68e9 Mon Jun 03 13:20:17 2013 +0400 linux/amd64</pre>

**Comment by hanwen** [comment]
this is from before the big rewrite. This can be closed.

@ianlancetaylor
