### ISSUE TITLE
crypto: Add crypto/dh to the stdlib

### ISSUE THREAD

**Issue by gopherbot** [golang/go#6170]
by **deleted.evan.phoenix@hungrymachine.com**:

<pre>Please consider adding crypto/dh, found here: <a href="https://github.com/evanphx/go-crypto-dh">https://github.com/evanphx/go-crypto-dh</a> to
the stdlib. RSA and EC are already present and using diffie hellman for custom crypto
protocols is very useful.

Thanks for your consideration!</pre>

**Comment by FiloSottile** [comment]
Finite field Diffie-Hellman has mostly run its course.
