### ISSUE TITLE
cmd/go: test -coverpkg: compilation error when file only contains interface definitions

### ISSUE THREAD

**Issue by pchmieli** [golang/go#61709]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.6 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\username\AppData\Local\go-build
set GOENV=C:\Users\username\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\username\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\username\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.20.6
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\USERNAME\AppData\Local\Temp\go-build2060490568=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

I try to run unit tests with coverage
```
GOROOT=C:\Program Files\Go #gosetup
GOPATH=C:\Users\username\go #gosetup
"C:\Program Files\Go\bin\go.exe" test -c -coverpkg=../../../../../repo-name/... -covermode=atomic -o C:\Users\username\AppData\Local\JetBrains\IntelliJIdea2023.1\tmp\GoLand\___binary-name.exe package-name/project-name/pkg/feature_tests #gosetup
```
I've got multiple packages with executable code in my project. Additionally, there is one package with single file and single interface inside and this very file causes the issue:
```
package api

type Foo interface {
	Bar(x, y string) ([]string, error)
}
```

### What did you expect to see?

Test coverage report

### What did you see instead?

Compilation error
```
(...) api.go:1:21: "sync/atomic" imported as _cover_atomic_ and not used

Compilation finished with exit code 1
```

### Workaround

Error is gone once I add some executable code to api.go. It might be whatever function, even empty and unused:
```
package api

type Foo interface {
	Bar(x, y string) ([]string, error)
}

func xyz() {
}
```

### Possibly related issues:
https://github.com/golang/go/issues/17817 cmd/cover: Avoid importing atomic package if not used
https://github.com/golang/go/issues/18486 cmd/go: go test -coverpkg=./... -race does not rebuild sync/atomic

**Comment by thediveo** [comment]
Can you please specify how exactly you're invoking the go command? I have several modules with type-only packages, but creating coverage hasn't been a problem, thus wondering.

**Comment by seankhliao** [comment]
Can you provide a self contained reproducer please.

**Comment by pchmieli** [comment]
I've just tried to prepare smallest possible example and bug does not appear there :(

Cannot disclose my real example as it is proprietary. Will come back to you once I have self contained reproducer.
