### ISSUE TITLE
encoding/json: Error in Marshalling Slice of Struct type -> affected/package: json

### ISSUE THREAD

**Issue by Prakhar-FF13** [golang/go#61710]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.5 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
I am on the latest version

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/prakharkumar/Library/Caches/go-build"
GOENV="/Users/prakharkumar/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/prakharkumar/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/prakharkumar/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.20.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.20.5/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.5"
GCCGO="gccgo"
AR="ar"
CC="cc"
CXX="c++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/s6/97rzy6yd76d5rd9fldl8x4dc0000gn/T/go-build4001747071=/tmp/go-build -gno-record-gcc-switches -fno-common"</summary><br><pre>
$ go env

</pre></details>

### What did you do?
Tried to Marshal a struct type array
type CM struct 
{
kind string,
payload []byte,
}

x is an array of CM i.e []CM. 

json.Marshal(x) ---> this gives wrong output, but no error is returned.

### What did you expect to see?
Marshalled output - example:
[{abc:"some"}, {abc:"thing"}]

### What did you see instead?
[{}]

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
