### ISSUE TITLE
runtime: "fatal error: s.allocCount != s.nelems && freeIndex == s.nelems" ADM Ryzen 9 6900HX, 32Gb

### ISSUE THREAD

**Issue by ajstarks** [golang/go#61726]
### What version of Go are you using (`go version`)?

<pre>
go version go1.20.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Unable to reproduce with 1.20.7, or any other version

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ajstarks/.cache/go-build"
GOENV="/home/ajstarks/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/ajstarks/gowork/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ajstarks/gowork"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/ajstarks/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/ajstarks/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.6"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1452667981=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

Other OS details: 

* Fedora 38 (6.4.6-200.fc38.x86_64 )
* AMD Ryzen 9 6900HX with Radeon Graphics (16) @ 4.935GHz 
* 32 Gb RAM

### What did you do?

using the update script from the giocanvas package: https://github.com/ajstarks/giocanvas/blob/master/update

the clients run, but a fatal runtime error occurs (see below)

### What did you expect to see?

no message, building and running giocanvas clients

### What did you see instead?

<pre>

$ ./update
go: downloading gioui.org v0.1.1-0.20230801070910-edbf872b44af
go: upgraded gioui.org v0.1.1-0.20230731100737-c7c49c3258f8 => v0.1.1-0.20230801070910-edbf872b44af
alpha arc apisheet cchue concentric compchart confetti dots elections eclipse flowers gcdeck grid hello images lego lines mondrian pie polar rgb scim shapesketch showimage spiral sunearth tile transform twrap play 
alpha arc apisheet cchue concentric compchart confetti dots elections eclipse flowers gcdeck grid hello images lego lines mondrian pie polar rgb scim shapesketch showimage spiral sunearth tile transform twrap play 
$ runtime: s.allocCount= 93 s.nelems= 102
fatal error: s.allocCount != s.nelems && freeIndex == s.nelems

goroutine 6 [running]:
runtime.throw({0x7e13c7?, 0xc000fc9728?})
	/home/ajstarks/go/src/runtime/panic.go:1047 +0x5d fp=0xc000fc9300 sp=0xc000fc92d0 pc=0x441b1d
runtime.(*mcache).nextFree(0x7fc5102d55b8, 0xe)
	/home/ajstarks/go/src/runtime/malloc.go:853 +0x1e5 fp=0xc000fc9348 sp=0xc000fc9300 pc=0x41a405
runtime.mallocgc(0x48, 0x79f660, 0x1)
	/home/ajstarks/go/src/runtime/malloc.go:1042 +0x455 fp=0xc000fc93b0 sp=0xc000fc9348 pc=0x41a895
runtime.convT(0x79f660, 0xc000fc9458?)
	/home/ajstarks/go/src/runtime/iface.go:331 +0x34 fp=0xc000fc93e8 sp=0xc000fc93b0 pc=0x418434
github.com/go-text/typesetting/fontscan.fontSet.selectByFamily({0xc000cf02a0, 0x1, 0x1}, {0xc000165248?, 0x748a60?}, 0x0, 0xc000218340, 0xc000cf2e70)
	/home/ajstarks/gowork/pkg/mod/github.com/go-text/typesetting@v0.0.0-20230720191532-efc36025df80/fontscan/match.go:142 +0x42d fp=0xc000fc95d0 sp=0xc000fc93e8 pc=0x6596cd
github.com/go-text/typesetting/fontscan.(*FontMap).buildCandidates.func1(0x0)
	/home/ajstarks/gowork/pkg/mod/github.com/go-text/typesetting@v0.0.0-20230720191532-efc36025df80/fontscan/fontmap.go:364 +0xaa fp=0xc000fc9668 sp=0xc000fc95d0 pc=0x65672a
github.com/go-text/typesetting/fontscan.(*FontMap).buildCandidates(0xc000218280)
	/home/ajstarks/gowork/pkg/mod/github.com/go-text/typesetting@v0.0.0-20230720191532-efc36025df80/fontscan/fontmap.go:390 +0x1ca fp=0xc000fc9758 sp=0xc000fc9668 pc=0x65648a
github.com/go-text/typesetting/fontscan.(*FontMap).ResolveFace(0xc000218280, 0x73)
	/home/ajstarks/gowork/pkg/mod/github.com/go-text/typesetting@v0.0.0-20230720191532-efc36025df80/fontscan/fontmap.go:440 +0x237 fp=0xc000fc99b0 sp=0xc000fc9758 pc=0x656d97
gioui.org/text.(*shaperImpl).ResolveFace(0xc000b60c28, 0xfc9c88?)
	/home/ajstarks/gowork/pkg/mod/gioui.org@v0.1.1-0.20230801070910-edbf872b44af/text/gotext.go:327 +0x39 fp=0xc000fc9a68 sp=0xc000fc99b0 pc=0x6720f9
github.com/go-text/typesetting/shaping.SplitByFace({{0xc000020948, 0x5, 0x6}, 0x0, 0x5, 0x0, 0x0, {0x0, 0x0, 0x0}, ...}, ...)
	/home/ajstarks/gowork/pkg/mod/github.com/go-text/typesetting@v0.0.0-20230720191532-efc36025df80/shaping/input.go:116 +0x126 fp=0xc000fc9b68 sp=0xc000fc9a68 pc=0x663ce6
gioui.org/text.(*shaperImpl).splitByFaces(0xc000020948?, {0xc000cf0380?, 0x1, 0x5?}, {0x0?, 0x0?, 0x0?})
	/home/ajstarks/gowork/pkg/mod/gioui.org@v0.1.1-0.20230801070910-edbf872b44af/text/gotext.go:350 +0x1b1 fp=0xc000fc9c98 sp=0xc000fc9b68 pc=0x672631
gioui.org/text.(*shaperImpl).shapeText(0xc000b60c28, 0x600, {{0x0?, 0x5e85cd?}, 0x10?}, {0xc000020948, 0x5, 0x6})
	/home/ajstarks/gowork/pkg/mod/gioui.org@v0.1.1-0.20230801070910-edbf872b44af/text/gotext.go:372 +0x385 fp=0xc000fc9fc0 sp=0xc000fc9c98 pc=0x672aa5
gioui.org/text.(*shaperImpl).shapeAndWrapText(0xc000b60c28, {{{0x0, 0x0}, 0x0, 0x0}, 0x2, 0x600, 0x0, {0x0, 0x0}, ...}, ...)
	/home/ajstarks/gowork/pkg/mod/gioui.org@v0.1.1-0.20230801070910-edbf872b44af/text/gotext.go:466 +0x5ae fp=0xc000fca150 sp=0xc000fc9fc0 pc=0x6736ae
gioui.org/text.(*shaperImpl).LayoutRunes(0xc000b60c28, {{{0x0, 0x0}, 0x0, 0x0}, 0x2, 0x600, 0x0, {0x0, 0x0}, ...}, ...)
	/home/ajstarks/gowork/pkg/mod/gioui.org@v0.1.1-0.20230801070910-edbf872b44af/text/gotext.go:535 +0x17e fp=0xc000fca378 sp=0xc000fca150 pc=0x67397e
gioui.org/text.(*Shaper).layoutParagraph(0xc000b60c00, {{{0x0, 0x0}, 0x0, 0x0}, 0x2, 0x600, 0x0, {0x0, 0x0}, ...}, ...)
	/home/ajstarks/gowork/pkg/mod/gioui.org@v0.1.1-0.20230801070910-edbf872b44af/text/shaper.go:395 +0x458 fp=0xc000fca608 sp=0xc000fca378 pc=0x677cf8
gioui.org/text.(*Shaper).layoutText(0xc000b60c00, {{{0x0, 0x0}, 0x0, 0x0}, 0x2, 0x600, 0x0, {0x0, 0x0}, ...}, ...)
	/home/ajstarks/gowork/pkg/mod/gioui.org@v0.1.1-0.20230801070910-edbf872b44af/text/shaper.go:332 +0x4d4 fp=0xc000fca808 sp=0xc000fca608 pc=0x677434
gioui.org/text.(*Shaper).LayoutString(0x34f0000012a?, {{{0x0, 0x0}, 0x0, 0x0}, 0x2, 0x600, 0x0, {0x0, 0x0}, ...}, ...)
	/home/ajstarks/gowork/pkg/mod/gioui.org@v0.1.1-0.20230801070910-edbf872b44af/text/shaper.go:278 +0x94 fp=0xc000fca8c8 sp=0xc000fca808 pc=0x676ef4
gioui.org/widget.Label.LayoutDetailed({0x2, 0x0, {0x0, 0x0}, 0x0, 0x0, 0x0}, {{{0x640, 0x3e8}, {0x640, ...}}, ...}, ...)
	/home/ajstarks/gowork/pkg/mod/gioui.org@v0.1.1-0.20230801070910-edbf872b44af/widget/label.go:59 +0x2b0 fp=0xc000fcb738 sp=0xc000fca8c8 pc=0x685dd0
gioui.org/widget.Label.Layout(...)
	/home/ajstarks/gowork/pkg/mod/gioui.org@v0.1.1-0.20230801070910-edbf872b44af/widget/label.go:43
gioui.org/widget/material.LabelStyle.Layout({{{0x0, 0x0}, 0x0, 0x0}, {0x0, 0x0, 0x0, 0xff}, {0x3f, 0x51, ...}, ...}, ...)
	/home/ajstarks/gowork/pkg/mod/gioui.org@v0.1.1-0.20230801070910-edbf872b44af/widget/material/label.go:153 +0x8b6 fp=0xc000fcbab8 sp=0xc000fcb738 pc=0x692b96
github.com/ajstarks/giocanvas.(*Canvas).textops(0xc000030100, 0x6cba45?, 0x0?, 0x41c00000, 0x2, {0x7ce476, 0x5}, {0x9a?, 0x99?, 0x99?, ...})
	/home/ajstarks/gocode/giocanvas/abs.go:39 +0x4bb fp=0xc000fcbe00 sp=0xc000fcbab8 pc=0x6c5b7b
github.com/ajstarks/giocanvas.(*Canvas).TextMid(0x447a000096b48246?, 0x30100?, 0xc0?, 0xfcbee4?, {0x7ce476?, 0x0?}, {0xd8?, 0xbe?, 0xfc?, 0x0?})
	/home/ajstarks/gocode/giocanvas/pct.go:167 +0x69 fp=0xc000fcbe40 sp=0xc000fcbe00 pc=0x6cb649
main.ref(0xc000118600, 0x2?, 0x0?, 0x0)
	/home/ajstarks/gocode/giocanvas/apisheet/main.go:153 +0x119a fp=0xc000fcbf90 sp=0xc000fcbe40 pc=0x6cd25a
main.main.func1()
	/home/ajstarks/gocode/giocanvas/apisheet/main.go:208 +0xeb fp=0xc000fcbfe0 sp=0xc000fcbf90 pc=0x6cdb0b
runtime.goexit()
	/home/ajstarks/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000fcbfe8 sp=0xc000fcbfe0 pc=0x4725e1
created by main.main
	/home/ajstarks/gocode/giocanvas/apisheet/main.go:206 +0x1b0

goroutine 1 [select (no cases)]:
runtime.gopark(0x44ce20?, 0xc0000121e0?, 0xa0?, 0x61?, 0x6cd9f0?)
	/home/ajstarks/go/src/runtime/proc.go:381 +0xd6 fp=0xc000071ee0 sp=0xc000071ec0 pc=0x444876
runtime.block()
	/home/ajstarks/go/src/runtime/select.go:103 +0x2c fp=0xc000071f10 sp=0xc000071ee0 pc=0x453d4c
gioui.org/app.osMain(...)
	/home/ajstarks/gowork/pkg/mod/gioui.org@v0.1.1-0.20230801070910-edbf872b44af/app/os_unix.go:43
gioui.org/app.Main(...)
	/home/ajstarks/gowork/pkg/mod/gioui.org@v0.1.1-0.20230801070910-edbf872b44af/app/app.go:64
main.main()
	/home/ajstarks/gocode/giocanvas/apisheet/main.go:214 +0x1b7 fp=0xc000071f80 sp=0xc000071f10 pc=0x6cd9f7
runtime.main()
	/home/ajstarks/go/src/runtime/proc.go:250 +0x207 fp=0xc000071fe0 sp=0xc000071f80 pc=0x444447
runtime.goexit()
	/home/ajstarks/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000071fe8 sp=0xc000071fe0 pc=0x4725e1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/home/ajstarks/go/src/runtime/proc.go:381 +0xd6 fp=0xc000060fb0 sp=0xc000060f90 pc=0x444876
runtime.goparkunlock(...)
	/home/ajstarks/go/src/runtime/proc.go:387
runtime.forcegchelper()
	/home/ajstarks/go/src/runtime/proc.go:305 +0xb0 fp=0xc000060fe0 sp=0xc000060fb0 pc=0x4446b0
runtime.goexit()
	/home/ajstarks/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000060fe8 sp=0xc000060fe0 pc=0x4725e1
created by runtime.init.6
	/home/ajstarks/go/src/runtime/proc.go:293 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	/home/ajstarks/go/src/runtime/proc.go:381 +0xd6 fp=0xc000061780 sp=0xc000061760 pc=0x444876
runtime.goparkunlock(...)
	/home/ajstarks/go/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
	/home/ajstarks/go/src/runtime/mgcsweep.go:319 +0xde fp=0xc0000617c8 sp=0xc000061780 pc=0x43117e
runtime.gcenable.func1()
	/home/ajstarks/go/src/runtime/mgc.go:178 +0x26 fp=0xc0000617e0 sp=0xc0000617c8 pc=0x4265e6
runtime.goexit()
	/home/ajstarks/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000617e8 sp=0xc0000617e0 pc=0x4725e1
created by runtime.gcenable
	/home/ajstarks/go/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xe2dd12dd7867?, 0xd3e84?, 0x0?, 0x0?, 0x0?)
	/home/ajstarks/go/src/runtime/proc.go:381 +0xd6 fp=0xc000061f70 sp=0xc000061f50 pc=0x444876
runtime.goparkunlock(...)
	/home/ajstarks/go/src/runtime/proc.go:387
runtime.(*scavengerState).park(0xaae8a0)
	/home/ajstarks/go/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc000061fa0 sp=0xc000061f70 pc=0x42f053
runtime.bgscavenge(0x0?)
	/home/ajstarks/go/src/runtime/mgcscavenge.go:633 +0x65 fp=0xc000061fc8 sp=0xc000061fa0 pc=0x42f645
runtime.gcenable.func2()
	/home/ajstarks/go/src/runtime/mgc.go:179 +0x26 fp=0xc000061fe0 sp=0xc000061fc8 pc=0x426586
runtime.goexit()
	/home/ajstarks/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000061fe8 sp=0xc000061fe0 pc=0x4725e1
created by runtime.gcenable
	/home/ajstarks/go/src/runtime/mgc.go:179 +0xaa

goroutine 5 [finalizer wait]:
runtime.gopark(0x0?, 0x812b98?, 0x0?, 0xa0?, 0x2000000020?)
	/home/ajstarks/go/src/runtime/proc.go:381 +0xd6 fp=0xc000060628 sp=0xc000060608 pc=0x444876
runtime.runfinq()
	/home/ajstarks/go/src/runtime/mfinal.go:193 +0x107 fp=0xc0000607e0 sp=0xc000060628 pc=0x425627
runtime.goexit()
	/home/ajstarks/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000607e8 sp=0xc0000607e0 pc=0x4725e1
created by runtime.createfing
	/home/ajstarks/go/src/runtime/mfinal.go:163 +0x45

goroutine 7 [select]:
runtime.gopark(0xc00006cf50?, 0x5?, 0x1?, 0x0?, 0xc00006ceee?)
	/home/ajstarks/go/src/runtime/proc.go:381 +0xd6 fp=0xc00006cd60 sp=0xc00006cd40 pc=0x444876
runtime.selectgo(0xc00006cf50, 0xc00006cee4, 0x6?, 0x0, 0x0?, 0x1)
	/home/ajstarks/go/src/runtime/select.go:327 +0x7be fp=0xc00006cea0 sp=0xc00006cd60 pc=0x45451e
gioui.org/app.(*Window).run(0xc000118600, {0xc0000883c0?, 0xc0000121f8?, 0xc000105528?})
	/home/ajstarks/gowork/pkg/mod/gioui.org@v0.1.1-0.20230801070910-edbf872b44af/app/window.go:961 +0x1d9 fp=0xc00006cfb0 sp=0xc00006cea0 pc=0x6a3519
gioui.org/app.NewWindow.func6()
	/home/ajstarks/gowork/pkg/mod/gioui.org@v0.1.1-0.20230801070910-edbf872b44af/app/window.go:188 +0x32 fp=0xc00006cfe0 sp=0xc00006cfb0 pc=0x69f592
runtime.goexit()
	/home/ajstarks/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00006cfe8 sp=0xc00006cfe0 pc=0x4725e1
created by gioui.org/app.NewWindow
	/home/ajstarks/gowork/pkg/mod/gioui.org@v0.1.1-0.20230801070910-edbf872b44af/app/window.go:188 +0x834

goroutine 18 [select, locked to thread]:
runtime.gopark(0xc0005db8c8?, 0x4?, 0xc0?, 0x10?, 0xc0005db8a0?)
	/home/ajstarks/go/src/runtime/proc.go:381 +0xd6 fp=0xc0005db728 sp=0xc0005db708 pc=0x444876
runtime.selectgo(0xc0005db8c8, 0xc0005db898, 0xc0005db8c8?, 0x1, 0x58?, 0x1)
	/home/ajstarks/go/src/runtime/select.go:327 +0x7be fp=0xc0005db868 sp=0xc0005db728 pc=0x45451e
gioui.org/app.(*Window).waitFrame(0xc000118600, {0x862c68, 0xc000218000})
	/home/ajstarks/gowork/pkg/mod/gioui.org@v0.1.1-0.20230801070910-edbf872b44af/app/window.go:744 +0xea fp=0xc0005db918 sp=0xc0005db868 pc=0x6a1b6a
gioui.org/app.(*Window).processEvent(0xc000118600, {0x862c68, 0xc000218000}, {0x85f028, 0xc001efc840})
	/home/ajstarks/gowork/pkg/mod/gioui.org@v0.1.1-0.20230801070910-edbf872b44af/app/window.go:872 +0x8e7 fp=0xc0005dbcf0 sp=0xc0005db918 pc=0x6a2707
gioui.org/app.(*callbacks).Event(0xc000118ad0, {0x85f028?, 0xc001efc840?})
	/home/ajstarks/gowork/pkg/mod/gioui.org@v0.1.1-0.20230801070910-edbf872b44af/app/window.go:476 +0x145 fp=0xc0005dbdb0 sp=0xc0005dbcf0 pc=0x6a0ac5
gioui.org/app.(*x11Window).loop(0xc000218000)
	/home/ajstarks/gowork/pkg/mod/gioui.org@v0.1.1-0.20230801070910-edbf872b44af/app/os_x11.go:460 +0x3b9 fp=0xc0005dbf50 sp=0xc0005dbdb0 pc=0x6bbc19
gioui.org/app.newX11Window.func12()
	/home/ajstarks/gowork/pkg/mod/gioui.org@v0.1.1-0.20230801070910-edbf872b44af/app/os_x11.go:834 +0x1a5 fp=0xc0005dbfe0 sp=0xc0005dbf50 pc=0x6bdf25
runtime.goexit()
	/home/ajstarks/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0005dbfe8 sp=0xc0005dbfe0 pc=0x4725e1
created by gioui.org/app.newX11Window
	/home/ajstarks/gowork/pkg/mod/gioui.org@v0.1.1-0.20230801070910-edbf872b44af/app/os_x11.go:826 +0x8f5

goroutine 19 [GC worker (idle)]:
runtime.gopark(0xc000218000?, 0xc0000883c0?, 0x6?, 0x0?, 0x10?)
	/home/ajstarks/go/src/runtime/proc.go:381 +0xd6 fp=0xc000062750 sp=0xc000062730 pc=0x444876
runtime.gcBgMarkWorker()
	/home/ajstarks/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0000627e0 sp=0xc000062750 pc=0x428151
runtime.goexit()
	/home/ajstarks/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000627e8 sp=0xc0000627e0 pc=0x4725e1
created by runtime.gcBgMarkStartWorkers
	/home/ajstarks/go/src/runtime/mgc.go:1199 +0x25

goroutine 20 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/home/ajstarks/go/src/runtime/proc.go:381 +0xd6 fp=0xc00005c750 sp=0xc00005c730 pc=0x444876
runtime.gcBgMarkWorker()
	/home/ajstarks/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc00005c7e0 sp=0xc00005c750 pc=0x428151
runtime.goexit()
	/home/ajstarks/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00005c7e8 sp=0xc00005c7e0 pc=0x4725e1
created by runtime.gcBgMarkStartWorkers
	/home/ajstarks/go/src/runtime/mgc.go:1199 +0x25

goroutine 8 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/home/ajstarks/go/src/runtime/proc.go:381 +0xd6 fp=0xc000062f50 sp=0xc000062f30 pc=0x444876
runtime.gcBgMarkWorker()
	/home/ajstarks/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc000062fe0 sp=0xc000062f50 pc=0x428151
runtime.goexit()
	/home/ajstarks/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000062fe8 sp=0xc000062fe0 pc=0x4725e1
created by runtime.gcBgMarkStartWorkers
	/home/ajstarks/go/src/runtime/mgc.go:1199 +0x25

goroutine 9 [GC worker (idle)]:
runtime.gopark(0xe2deb0b8a74d?, 0x3?, 0x1d?, 0x2?, 0x0?)
	/home/ajstarks/go/src/runtime/proc.go:381 +0xd6 fp=0xc000063750 sp=0xc000063730 pc=0x444876
runtime.gcBgMarkWorker()
	/home/ajstarks/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0000637e0 sp=0xc000063750 pc=0x428151
runtime.goexit()
	/home/ajstarks/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000637e8 sp=0xc0000637e0 pc=0x4725e1
created by runtime.gcBgMarkStartWorkers
	/home/ajstarks/go/src/runtime/mgc.go:1199 +0x25

goroutine 10 [GC worker (idle)]:
runtime.gopark(0xe2deacb56050?, 0x3?, 0x2d?, 0x15?, 0x0?)
	/home/ajstarks/go/src/runtime/proc.go:381 +0xd6 fp=0xc000063f50 sp=0xc000063f30 pc=0x444876
runtime.gcBgMarkWorker()
	/home/ajstarks/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc000063fe0 sp=0xc000063f50 pc=0x428151
runtime.goexit()
	/home/ajstarks/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000063fe8 sp=0xc000063fe0 pc=0x4725e1
created by runtime.gcBgMarkStartWorkers
	/home/ajstarks/go/src/runtime/mgc.go:1199 +0x25

goroutine 11 [GC worker (idle)]:
runtime.gopark(0xe2deb0b8b3bf?, 0x1?, 0x86?, 0x48?, 0x0?)
	/home/ajstarks/go/src/runtime/proc.go:381 +0xd6 fp=0xc0001ec750 sp=0xc0001ec730 pc=0x444876
runtime.gcBgMarkWorker()
	/home/ajstarks/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0001ec7e0 sp=0xc0001ec750 pc=0x428151
runtime.goexit()
	/home/ajstarks/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0001ec7e8 sp=0xc0001ec7e0 pc=0x4725e1
created by runtime.gcBgMarkStartWorkers
	/home/ajstarks/go/src/runtime/mgc.go:1199 +0x25

goroutine 12 [GC worker (idle)]:
runtime.gopark(0xe2deb0b8b49b?, 0x1?, 0x56?, 0x1c?, 0x0?)
	/home/ajstarks/go/src/runtime/proc.go:381 +0xd6 fp=0xc0001ecf50 sp=0xc0001ecf30 pc=0x444876
runtime.gcBgMarkWorker()
	/home/ajstarks/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0001ecfe0 sp=0xc0001ecf50 pc=0x428151
runtime.goexit()
	/home/ajstarks/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0001ecfe8 sp=0xc0001ecfe0 pc=0x4725e1
created by runtime.gcBgMarkStartWorkers
	/home/ajstarks/go/src/runtime/mgc.go:1199 +0x25

goroutine 13 [GC worker (idle)]:
runtime.gopark(0xe2deb0b8bd6a?, 0x1?, 0x23?, 0xe4?, 0x0?)
	/home/ajstarks/go/src/runtime/proc.go:381 +0xd6 fp=0xc0001ed750 sp=0xc0001ed730 pc=0x444876
runtime.gcBgMarkWorker()
	/home/ajstarks/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0001ed7e0 sp=0xc0001ed750 pc=0x428151
runtime.goexit()
	/home/ajstarks/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0001ed7e8 sp=0xc0001ed7e0 pc=0x4725e1
created by runtime.gcBgMarkStartWorkers
	/home/ajstarks/go/src/runtime/mgc.go:1199 +0x25

goroutine 14 [GC worker (idle)]:
runtime.gopark(0xaddd20?, 0x3?, 0xcc?, 0xc?, 0x0?)
	/home/ajstarks/go/src/runtime/proc.go:381 +0xd6 fp=0xc0001edf50 sp=0xc0001edf30 pc=0x444876
runtime.gcBgMarkWorker()
	/home/ajstarks/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0001edfe0 sp=0xc0001edf50 pc=0x428151
runtime.goexit()
	/home/ajstarks/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0001edfe8 sp=0xc0001edfe0 pc=0x4725e1
created by runtime.gcBgMarkStartWorkers
	/home/ajstarks/go/src/runtime/mgc.go:1199 +0x25

goroutine 34 [GC worker (idle)]:
runtime.gopark(0xe2deae1640a8?, 0x3?, 0xdd?, 0x3a?, 0x0?)
	/home/ajstarks/go/src/runtime/proc.go:381 +0xd6 fp=0xc0001e8750 sp=0xc0001e8730 pc=0x444876
runtime.gcBgMarkWorker()
	/home/ajstarks/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0001e87e0 sp=0xc0001e8750 pc=0x428151
runtime.goexit()
	/home/ajstarks/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0001e87e8 sp=0xc0001e87e0 pc=0x4725e1
created by runtime.gcBgMarkStartWorkers
	/home/ajstarks/go/src/runtime/mgc.go:1199 +0x25

goroutine 15 [GC worker (idle)]:
runtime.gopark(0xe2deb0b8c5de?, 0x1?, 0x51?, 0x43?, 0x0?)
	/home/ajstarks/go/src/runtime/proc.go:381 +0xd6 fp=0xc0001ee750 sp=0xc0001ee730 pc=0x444876
runtime.gcBgMarkWorker()
	/home/ajstarks/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0001ee7e0 sp=0xc0001ee750 pc=0x428151
runtime.goexit()
	/home/ajstarks/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0001ee7e8 sp=0xc0001ee7e0 pc=0x4725e1
created by runtime.gcBgMarkStartWorkers
	/home/ajstarks/go/src/runtime/mgc.go:1199 +0x25

goroutine 16 [GC worker (idle)]:
runtime.gopark(0xe2deacb561cd?, 0x1?, 0xba?, 0x30?, 0x0?)
	/home/ajstarks/go/src/runtime/proc.go:381 +0xd6 fp=0xc0001eef50 sp=0xc0001eef30 pc=0x444876
runtime.gcBgMarkWorker()
	/home/ajstarks/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0001eefe0 sp=0xc0001eef50 pc=0x428151
runtime.goexit()
	/home/ajstarks/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0001eefe8 sp=0xc0001eefe0 pc=0x4725e1
created by runtime.gcBgMarkStartWorkers
	/home/ajstarks/go/src/runtime/mgc.go:1199 +0x25

goroutine 50 [GC worker (idle)]:
runtime.gopark(0xe2deb0b8b640?, 0x3?, 0xa6?, 0x30?, 0x0?)
	/home/ajstarks/go/src/runtime/proc.go:381 +0xd6 fp=0xc0001ef750 sp=0xc0001ef730 pc=0x444876
runtime.gcBgMarkWorker()
	/home/ajstarks/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0001ef7e0 sp=0xc0001ef750 pc=0x428151
runtime.goexit()
	/home/ajstarks/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0001ef7e8 sp=0xc0001ef7e0 pc=0x4725e1
created by runtime.gcBgMarkStartWorkers
	/home/ajstarks/go/src/runtime/mgc.go:1199 +0x25

goroutine 51 [GC worker (idle)]:
runtime.gopark(0xe2deacb55fc4?, 0x1?, 0xde?, 0x1b?, 0x0?)
	/home/ajstarks/go/src/runtime/proc.go:381 +0xd6 fp=0xc0001eff50 sp=0xc0001eff30 pc=0x444876
runtime.gcBgMarkWorker()
	/home/ajstarks/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0001effe0 sp=0xc0001eff50 pc=0x428151
runtime.goexit()
	/home/ajstarks/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0001effe8 sp=0xc0001effe0 pc=0x4725e1
created by runtime.gcBgMarkStartWorkers
	/home/ajstarks/go/src/runtime/mgc.go:1199 +0x25

goroutine 52 [GC worker (idle)]:
runtime.gopark(0xaddd20?, 0x3?, 0x36?, 0x5c?, 0x0?)
	/home/ajstarks/go/src/runtime/proc.go:381 +0xd6 fp=0xc0001f4750 sp=0xc0001f4730 pc=0x444876
runtime.gcBgMarkWorker()
	/home/ajstarks/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0001f47e0 sp=0xc0001f4750 pc=0x428151
runtime.goexit()
	/home/ajstarks/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0001f47e8 sp=0xc0001f47e0 pc=0x4725e1
created by runtime.gcBgMarkStartWorkers
	/home/ajstarks/go/src/runtime/mgc.go:1199 +0x25

goroutine 53 [GC worker (idle)]:
runtime.gopark(0xe2de66a0c88e?, 0x3?, 0xb3?, 0x47?, 0x0?)
	/home/ajstarks/go/src/runtime/proc.go:381 +0xd6 fp=0xc0001f4f50 sp=0xc0001f4f30 pc=0x444876
runtime.gcBgMarkWorker()
	/home/ajstarks/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0001f4fe0 sp=0xc0001f4f50 pc=0x428151
runtime.goexit()
	/home/ajstarks/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0001f4fe8 sp=0xc0001f4fe0 pc=0x4725e1
created by runtime.gcBgMarkStartWorkers
	/home/ajstarks/go/src/runtime/mgc.go:1199 +0x25
</pre>

**Comment by dr2chase** [comment]
@golang/runtime

**Comment by mknyszek** [comment]
Is this repeatable with Go 1.20.6?

**Comment by ajstarks** [comment]
I have **not** been able to make this re-occur on 1.20.6, 1.20.7, nor 1.21.0

**Comment by mknyszek** [comment]
Thanks. Unfortunately, this isn't a lot to go off of. It's almost certainly some kind of memory corruption, since this crash indicates an inconsistency in the memory allocator fast path which hasn't changed recently and is executed quite often (so crashes due to bad logic like this tend to flush out very fast).
