### ISSUE TITLE
x/vuln: Treat fixes in unstable releases as warnings

### ISSUE THREAD

**Issue by adapptor-kurt** [golang/go#61729]
### What version of Go are you using (`go version`)?

go version go1.20.6 darwin/arm64

### Does this issue reproduce at the latest version of golang.org/x/vuln?

Yes

### What did you do?

I am running `govulncheck ./...` as part of my CI process

### What did you expect to see?

govulncheck should tell me whether there is a security vulnerability that I can take an action to fix.

### What did you see instead?

govulncheck is causing a failure due to a fix in the unstable release crypto/tls@go1.21rc4.  While this is useful to know about, it should be possible to ignore vulnerabilities that are not yet fixed in a stable release.

**Comment by dr2chase** [comment]
@golang/vulndb

**Comment by adapptor-kurt** [comment]
@zpavlinovic I'm happy to close this issue if it has been resolved, as I won't be able to reproduce the original issue.  Thanks!
