### ISSUE TITLE
fuzzing process terminated without fuzzing: EOF

### ISSUE THREAD

**Issue by Dmytro-yakymuk** [golang/go#61742]
Hi, help me with the error it comes when I want to test the api server.

First I start this server and later in the f.Fuzz section I try to send requests to the server, but even with the missing code in the section I get an error.
go test -v -fuzz=FuzzHistory -parallel=1

![image](https://github.com/golang/go/assets/38706023/0fbc09b2-d0b7-47a0-b9be-84d4a74233c4)

What can this error indicate? This test passes if I run it from vs code IDE, but once using the data that I recorded in f.Add,
also similar, non-fuzz tests are performed without problems.

I tried the recommendations from https://github.com/golang/go/issues/52569 and https://github.com/golang/go/issues/52133, but nothing helped((

go version go1.20.4 linux/amd64

GOHOSTARCH="amd64"
GOHOSTOS="linux"

**Comment by ianlancetaylor** [comment]
This means that the program crashed unexpectedly.

In general we don't use the issue tracker for questions.  Please use a forum for further discussions.  See https://go.dev/wiki/Questions.  Thanks.
