### ISSUE TITLE
cmd/go: provide support for VCS branches in go get / import

### ISSUE THREAD

**Issue by gopherbot** [golang/go#6174]
by **tv@duh.org**:

<pre>Running go1.1.2 -- but as far as I can tell, this hasn't been filed as an actual issue
yet.

Basically, the vcs-based checkouts are now pretty flexible (even when not from a
well-known hosting service), but there is no syntax for checking out a branch other than
the vcs's &quot;default&quot; branch. Something as simple as
&quot;example.org/foo/projname.vcs::branchname/bar/baz&quot; as the URL syntax might be
good enough. How this is stored on disk to prevent conflicts would likely be more
complicated, perhaps as separate parallel directories of some fashion.

Note that this is not the same goal as in <a href="https://golang.org/issue/5779">issue #5779</a>. Here, I'm talking about giving a
third-party library creator the ability to supply generationally stable APIs for that
library (irrespective of Go language version, for which build constraints are probably
sufficient for now).

For instance, the main development branch of example.org/mylibrary.git may contain a
refactor/rethink of how fundamental logic works, but this requires an API-call rework by
all downstream applications. The author could provide a &quot;1.x-stable&quot; branch,
or other indicative name, to keep changes as compatible as possible without impeding new
development.</pre>

**Comment by bcmills** [comment]
> I'm talking about giving a
third-party library creator the ability to supply generationally stable APIs for that
library (irrespective of Go language version, for which build constraints are probably
sufficient for now).

I believe that modules address exactly that use-case. Give them a try! 🙂
