### ISSUE TITLE
runtime: execution halts with goroutines stuck in `runtime.gopark` (`protocol error E08 during memory read for packet`)

### ISSUE THREAD

**Issue by patrick-ogrady** [golang/go#61768]
### What version of Go are you using (`go version`)?

```
go version go1.20.7 darwin/arm64
```

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="arm64"
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
```

### What did you do?

When running continuous profiling on my binary, the entire program halted with all goroutines stuck in `runtime.gopark`. When disabling profiling, this problem went away.

I posted a similar issue a few months ago ("halt when profiling") but don't believe it to be related (https://github.com/golang/go/issues/58798).

```
  Goroutine 1 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [semacquire 258316338387791]
  Goroutine 2 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4)
  Goroutine 4 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [debug call]
  Goroutine 5 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [debug call 258796780404375]
  Goroutine 6 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [debug call 258856782846166]
  Goroutine 7 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [debug call 258856782846166]
  Goroutine 8 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [debug call]
  Goroutine 9 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [debug call]
  Goroutine 10 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [chan receive]
  Goroutine 18 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [GC sweep wait]
  Goroutine 19 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [GC scavenge wait]
  Goroutine 20 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [debug call]
  Goroutine 21 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [debug call]
  Goroutine 22 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [debug call]
  Goroutine 23 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [debug call]
  Goroutine 26 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [chan receive 258316338387791]
  Goroutine 33 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [select 258856782846166]
  Goroutine 34 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [finalizer wait]
  Goroutine 36 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [debug call 258316186592916]
  Goroutine 37 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [debug call]
  Goroutine 44 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [select 258316338387791]
  Goroutine 52 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [chan receive 258316338387791]
  Goroutine 54 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [select 258316338387791]
  Goroutine 58 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [IO wait 258316338387791]
  Goroutine 59 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [IO wait 258316338387791]
  Goroutine 61 - Runtime: :0 ??? (0x1ab4ccacc) (thread 7681484)
  Goroutine 62 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [chan receive 258316338387791]
  Goroutine 66 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [select 258316338387791]
  Goroutine 67 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [select]
  Goroutine 68 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [select 258316338387791]
  Goroutine 69 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [select 258316338387791]
  Goroutine 88 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [select]
  Goroutine 340 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [chan receive]
  Goroutine 347 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [select 258362045239291]
  Goroutine 607 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [select 258376783287916]
  Goroutine 619 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [select]
  Goroutine 620 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [select]
  Goroutine 621 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [select]
  Goroutine 622 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [semacquire]
  Goroutine 632 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [select]
  Goroutine 633 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [IO wait]
  Goroutine 634 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [select]
  Goroutine 635 - Runtime: /usr/local/go/src/runtime/proc.go:382 runtime.gopark (0x102255ab4) [chan receive 258316810183875]
```

### What did you expect to see?
I expected profiling to allow the binary to run without issue.

### What did you see instead?
Profiling put the binary in a "deadlocked"/"unrecoverable" state.

**Comment by patrick-ogrady** [comment]
Here are some interesting backtraces I captured (when running using go1.20.7): 

```
thread 8303355

 0  0x00000001ab4cebc8 in ???
    at ?:-1
 1  0x00000001028682b8 in runtime.systemstack_switch
    at /usr/local/go/src/runtime/asm_arm64.s:200
 2  0x0000000102853dbc in runtime.libcCall
    at /usr/local/go/src/runtime/sys_libc.go:49
 3  0x0000000102853a80 in runtime.pthread_cond_wait
    at /usr/local/go/src/runtime/sys_darwin.go:507
 4  0x000000010282fc28 in runtime.semasleep
    at /usr/local/go/src/runtime/os_darwin.go:66
 5  0x0000000102806878 in runtime.notetsleep_internal
    at /usr/local/go/src/runtime/lock_sema.go:213
 6  0x0000000102806b80 in runtime.notetsleepg
    at /usr/local/go/src/runtime/lock_sema.go:295
 7  0x00000001028446e0 in runtime.(*profBuf).read
    at /usr/local/go/src/runtime/profbuf.go:500
 8  0x0000000102862818 in runtime/pprof.readProfile
    at /usr/local/go/src/runtime/cpuprof.go:230
 9  0x00000001030fc794 in runtime/pprof.profileWriter
    at /usr/local/go/src/runtime/pprof/pprof.go:810
10  0x00000001030fc6ac in runtime/pprof.StartCPUProfile.func2
    at /usr/local/go/src/runtime/pprof/pprof.go:794
11  0x000000010286a8b4 in runtime.goexit
    at /usr/local/go/src/runtime/asm_arm64.s:1172
```

```
thread 8303391

0  0x00000001ab4cf50c in ???
   at ?:-1
1  0x77288001ab3b01e8 in ???
   at ?:-1
2  0x683600010286b9f4 in ???
   at ?:-1
3  0x000000010286a728 in runtime.asmcgocall
   at /usr/local/go/src/runtime/asm_arm64.s:1005
4  0x000000016de0ae28 in ???
   at ?:-1
   error: protocol error E08 during memory read for packet $m683600010286b9fc,8
```

```
thread 8303392

0  0x00000001ab4cf710 in ???
   at ?:-1
1  0x1f4100010286bd78 in ???
   at ?:-1
2  0x000000010286a728 in runtime.asmcgocall
   at /usr/local/go/src/runtime/asm_arm64.s:1005
3  0x00000000043a4800 in ???
   at ?:-1
   error: protocol error E08 during memory read for packet $m1f4100010286bd80,8
```

**Comment by dr2chase** [comment]
@mknyszek @cherrymui @bcmills 
Unclear if this is a Darwin flake (if so, perhaps a recipe for making it happen more often) or a profiling bug.

**Comment by patrick-ogrady** [comment]
I can reliably reproduce this within a few minutes on my machine if you want me to grab anything else 👍 .

**Comment by dr2chase** [comment]
Is this https://github.com/ava-labs/avalanchego ?  Can the test run on just a laptop, or does it need additional setup?

**Comment by patrick-ogrady** [comment]
> Is this https://github.com/ava-labs/avalanchego ? Can the test run on just a laptop, or does it need additional setup?

There is some additional setup. I've been reproducing on my Mac M2 Max with:
```
git clone https://github.com/ava-labs/hypersdk.git;
cd hypersdk/examples/morepheusvm;
./scripts/run.sh;
```

Within a few minutes, different processes spawned will start to halt (continuous profiling is enabled by default).

**Comment by dr2chase** [comment]
Can confirm that ./scripts/run.sh does run and spew messages.  Is there anything else I should be doing after that?  I see messages about "disconnecting peer".  One avalanchego process is chewing up 300% of CPU, is that expected?  (Laptop is also an M2 Max, all the cores, a truckload of memory too.)

I.e., what am I looking for?  (And is there a better way than killall to get rid of the processes?)
Specific instructions are better, no way of knowing for sure if "disconnecting peer" is another way of saying "start to halt" though I have my suspicions.

Now there's two avalanchego processes, each consuming well over 300% of CPU.

**Comment by patrick-ogrady** [comment]
> One avalanchego process is chewing up 300% of CPU, is that expected?

This is what happens when the process halts. Run `dlv attach <pid>` then `grs -r` and you should see everything stuck.

**Comment by dr2chase** [comment]
A-ha.  Any way to prevent the other ones from getting further stuck and eating all the CPU?  Maybe just keep attaching them to shut them down?  Or do I debug one, kill the rest?

**Comment by patrick-ogrady** [comment]
> A-ha. Any way to prevent the other ones from getting further stuck and eating all the CPU? Maybe just keep attaching them to shut them down? Or do I debug one, kill the rest?

I'd suggest killing the rest after attaching to one that is stuck. Otherwise the runaway CPU will happen as more get stuck (no way to prevent that bc of this bug ^).

**Comment by patrick-ogrady** [comment]
Any update on this?

**Comment by patrick-ogrady** [comment]
I'm going to test if this occurs on go1.19 to see if I can bisect the regression.

**Comment by dr2chase** [comment]
Thank you, and good luck.

**Comment by patrick-ogrady** [comment]
I ran a few tests. I have not been able to reproduce it in v1.19.12 but was able to reproduce it immediately in v1.21.0.

I'm going to keep trying on v1.19.12.

**Comment by patrick-ogrady** [comment]
> I ran a few tests. I have not been able to reproduce it in v1.19.12 but was able to reproduce it immediately in v1.21.0.
> 
> I'm going to keep trying on v1.19.12.

I've been running v1.19.12 for the last 20 minutes and still no issue. I'm fairly confident that this is not an issue in v1.19.x.

**Comment by patrick-ogrady** [comment]
I just reproduced the issue on v1.19.12 😢 . It took longer but it eventually hit (same exact symptoms as shared above).

**Comment by dr2chase** [comment]
I know "what" but not "why".  The profiling signal lock is stuck on for at least 100,000 consecutive osyield, i.e., 1 second.

**Comment by bcmills** [comment]
Given `darwin`, I wonder if this is related to #60108 and/or #59995.

Hmm. Given that the Go runtime on `darwin` uses `libc`, is it possible that the Go signal handler is ending up in a `libc` call and deadlocking on acquiring a mutex already held by another `libc` call on the running thread?

**Comment by dr2chase** [comment]
I can look for that, but I don't think I've seen it.  I'm also seeing behavior that makes me think this might perhaps be a symptom, not a cause -- after adding checks, two processes jammed at 99.9% (but not more, which was what I previously saw) and not having "Idle Wake Ups" counting up at a wicked rate.  And not crashing out on the checks I added.

**Comment by dr2chase** [comment]
Note, so far, of the 3 failures that I have seen, they've been at
```
func (p *cpuProfile) add(tagPtr *unsafe.Pointer, stk []uintptr) {
```
in runtime/cpuprof, in particular the failure was detected there, and the stuck lock was also created there.
That's what I've got so far, I'm going to collect a few more.

**Comment by dr2chase** [comment]
definitely have a fix, maybe it's not the right fix.

**Comment by dr2chase** [comment]
@gopherbot please open the backport tracking issues. This is an annoying bug, possible cause of flakes, with a targeted fix.

**Comment by patrick-ogrady** [comment]
Thanks @dr2chase!!
