### ISSUE TITLE
install go tools failed 

### ISSUE THREAD

**Issue by zhiyunliu** [golang/go#61775]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.20.7 windows/amd64

</pre>

### Does this issue reproduce with the latest release?
yes , 
go install golang.org/x/tools/gopls@latest

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>
![image](https://github.com/golang/go/assets/29598760/0ea0f44a-2ac2-43bd-b6fc-04293bd1f8c9)

### What did you do?

![image](https://github.com/golang/go/assets/29598760/a73ddd7a-fcb8-4f0c-a783-4933d543184a)

### What did you expect to see?

Installing successfully.

### What did you see instead?

D:\Go\src\crypto\elliptic\internal\fiat\p521_invert.go:12:10: undefined: P521Element
D:\Go\src\crypto\elliptic\internal\fiat\p521_invert.go:35:14: undefined: P521Element
D:\Go\src\crypto\elliptic\internal\fiat\p521_invert.go:36:15: undefined: P521Element

**Comment by seankhliao** [comment]
looks like you have a corrupt installation

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
