### ISSUE TITLE
x/build/cmd/gomote: enable gomote for LUCI bots

### ISSUE THREAD

**Issue by cagedmantis** [golang/go#61772]
The migration to LUCI requires us enable gomote functionality for LUCI. This issue tracks that work.

- [ ] #61773
- [ ] #61843
- [ ] #61842
- [ ] #61844
- [ ] #63354
- [ ] #62733
- [ ] #64430
- [ ] #62734
- [ ] #61912
- [ ] #62118
- [ ] #63710
- [ ] #63778
- [ ] #64212
- [ ] #63781
- [ ] #63774
- [ ] #63776
- [ ] #63779
- [ ] #63780
- [ ] #63775
- [ ] #63786
- [ ] #63788
- [ ] #63789
- [ ] #63790
- [ ] #63791
- [ ] #63792
- [ ] #63793
- [ ] #63819
- [ ] #63991
- [ ] #63992
- [ ] #64064
- [ ] #64213
- [x] #64743
- [x] #64744
- [x] #64745
- [x] #64746
- [x] #64747
- [x] #64951
@golang/release

**Comment by Oguidan** [comment]
@cagedmantis what is LUCI

**Comment by cagedmantis** [comment]
@Oguidan Hi! The Go team is migrating the build infrastructure to the infra developed by the Chrome team. That infra is called [LUCI](https://chrome-internal.googlesource.com/infra/infra_internal/+/HEAD/doc/index.md). I don't think this would be the best task to learn from. But I can certainly point you in the right direction if you are interested.

**Comment by Oguidan** [comment]
Yes @cagedmantis I will love that. If you can also mentor me to be a better contributor like you I would be happy.

**Comment by cagedmantis** [comment]
The work required for this issue has been completed.
