### ISSUE TITLE
x/website:  not able to copy commands on Install page

### ISSUE THREAD

**Issue by harshakp06** [golang/go#61789]
### What is the URL of the page with the issue?
 https://go.dev/doc/install
 
 
### What is your user agent?
Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0
 

 
 
 
###

 

![Screenshot from 2023-08-06 13-35-15](https://github.com/golang/go/assets/48921568/c07270e4-24cc-4993-9e2f-9ece7255e7a0)
 Screenshot

 
 
 
### What did you do?
 
add the copy command shortcut

 
 
 
### What did you expect to see?

Copy the command
 
 
 
### What did you see instead?
seen a zoom in arrow

**Comment by mauri870** [comment]
Thanks for reporting, but that appears to be correct.

The cursor is of type `copy` which should have this icon, see https://developer.mozilla.org/en-US/docs/Web/CSS/cursor

The copy-to-clipboard functionality is also working properly.
