### ISSUE TITLE
x/tour: some characters disappear after typing

### ISSUE THREAD

**Issue by red-co** [golang/go#61787]
### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

Android 13, chrome 
keyboard is gboard

https://github.com/golang/go/assets/75922982/f335e8d1-d394-4fc8-b37d-5a1f776bba9d

**Comment by sergeizv** [comment]
I've encountered the issue on Android in Chrome and Firefox browsers, and I'm wondering if this should be reopened.
