### ISSUE TITLE
net/http: internal error: connCount underflow

### ISSUE THREAD

**Issue by SABERYJS** [golang/go#61794]
when i  send too many http request (more than one hundred thousand)  by http.transport, application exit, by check  log,
```
2023/08/06 17:14:27.188633 [ants]: worker exits from panic: net/http: internal error: connCount underflow
goroutine 414 [running]:
runtime/debug.Stack()
        /usr/lib/golang/src/runtime/debug/stack.go:24 +0x65
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
        /root/go/pkg/mod/github.com/panjf2000/ants/v2@v2.8.1/worker.go:56 +0x89
panic({0xf2e2a0, 0x1217930})
        /usr/lib/golang/src/runtime/panic.go:884 +0x212
net/http.(*Transport).decConnsPerHost(0xc000002f00, {{0xc003eb83c0, 0x34}, {0x10d58e0, 0x5}, {0xc0010cc3a8, 0x13}, 0x0})
        /usr/lib/golang/src/net/http/transport.go:1476 +0x592
net/http.(*Transport).roundTrip(0xc000002f00, 0xc005bb4e00)
        /usr/lib/golang/src/net/http/transport.go:605 +0x88b
net/http.(*Transport).RoundTrip(0xc005bb4e00?, 0x121a860?)
        /usr/lib/golang/src/net/http/roundtrip.go:17 +0x19
net/http.send(0xc005bb4b00, {0x121a860, 0xc000002f00}, {0x105c1a0?, 0x4d4601?, 0x1ba1180?})
        /usr/lib/golang/src/net/http/client.go:251 +0x5f7
net/http.(*Client).send(0xc0004988a0, 0xc005bb4b00, {0xc003f21760?, 0xc00501e630?, 0x1ba1180?})
        /usr/lib/golang/src/net/http/client.go:175 +0x9b
net/http.(*Client).do(0xc0004988a0, 0xc005bb4b00)
        /usr/lib/golang/src/net/http/client.go:715 +0x8fc
net/http.(*Client).Do(...)
        /usr/lib/golang/src/net/http/client.go:581

```

go version `go version go1.19.10 linux/amd64`

following is my http transport
```
func getTransport() *http.Transport {
	transport := http.DefaultTransport.(*http.Transport).Clone()
	transport.MaxIdleConns = config.SieveConfig.Transport.MaxIdleConnCount
	transport.MaxConnsPerHost = config.SieveConfig.Transport.MaxConnCount
	transport.MaxIdleConnsPerHost = config.SieveConfig.Transport.MaxIdleConnCount
	transport.DisableKeepAlives = false
	//transport.IdleConnTimeout = 90 * time.Second
	transport.TLSHandshakeTimeout = 20 * time.Second
	transport.ExpectContinueTimeout = 8 * time.Second

	header := http.Header{}
	//header.Add("Connection", "close")
	transport.ProxyConnectHeader = header

	timeout := 8 * time.Second
	transport.DialContext = (&net.Dialer{
		Timeout: timeout,
	}).DialContext
	transport.TLSClientConfig = &tls.Config{InsecureSkipVerify: true}
	proxyurl, err := url.Parse(ProxyServiceIpProviderImpl.GetProxy())
	if err != nil {
		panic(err)
	}
	transport.Proxy = http.ProxyURL(proxyurl)
	return transport
}
```

`transport.MaxIdleConns`  set to  500
`transport.MaxConnsPerHost` set to 500
`transport.MaxIdleConnsPerHost` set to 500

**Comment by mknyszek** [comment]
CC @neild

**Comment by mknyszek** [comment]
Does this reproduce with newer versions of Go? Note that Go 1.19 is slated to become unsupported this week.

**Comment by bcmills** [comment]
See also:
- #61474 (reported against Go 1.18.3, status on supported versions unknown)
- #38172 (a similar symptom due to a data race in user code)

@SABERYJS, have you tried building your program with the `-race` flag? If so, does it report any races?

**Comment by mauri870** [comment]
@zzkcode posted some updates at #61474

Issue still reproducible with `-race` and `go 1.20.6`

/CC @mknyszek @bcmills

**Comment by ppanphper** [comment]
![image](https://github.com/golang/go/assets/6057923/b4d6902f-f09b-40a5-a39c-f296bbfa1ef8)

![image](https://github.com/golang/go/assets/6057923/e01a125e-81b5-4488-af77-7deea8d0c075)
![image](https://github.com/golang/go/assets/6057923/79fe4262-1500-41ed-9cdd-8413b30f0c0c)

### too many call close, will there be any mistakes?
![image](https://github.com/golang/go/assets/6057923/d07062d2-43cd-4bb2-9f59-31e7ffd59a7a)
### Will it be a fault of goroutine concurrency?
![image](https://github.com/golang/go/assets/6057923/3acf0508-9b3c-4469-a456-86305b94178e)

**Comment by kajtzu** [comment]
We stumbled on this in an earlier version of golang and it seems to happen on 1.21.0, too, and after very many requests have been made by the client. We will see if the race detector reports something.
