### ISSUE TITLE
Build: Can't import static  lib on window 10

### ISSUE THREAD

**Issue by PhanSon95** [golang/go#61803]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.5 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Hey guys, I have problem with import static lib c++ on window 10
I use Visual Code to build static lib
When  import static lib, I got error 
```
PS C:\Users\Administrator\Desktop\static_lib\window> go run .\main.go
# command-line-arguments
C:\Program Files\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ADMINI~1\AppData\Local\Temp\2\go-link-1866661389\000001.o: in function `_cgo_4edeb0dd26e3_Cfunc_hello_world':
/tmp/go-build/main.cgo2.c:49: undefined reference to `__imp_hello_world'
collect2.exe: error: ld returned 1 exit status
```

But when I build code c++ with dynamic  library, it working fine
I want to use static lib for this lib
This is my c++ code:

```
// file pch.h
#ifndef PCH_H
#define PCH_H

#ifdef MY_WINDOW_EXPORTS
#define MY_API __declspec(dllexport)
#else
#define MY_API __declspec(dllimport)
#endif

// add headers that you want to pre-compile here
#include "framework.h"


#ifdef __cplusplus
extern "C" {
#endif
	// Your prototype or Definition 
	MY_API const char* hello_world();
#ifdef __cplusplus
}
#endif


#endif //PCH_H
```

``` pch.cpp
// pch.cpp: source file corresponding to the pre-compiled header

#include "pch.h"

// When you are using pre-compiled headers, this source file is necessary for compilation to succeed.


const char* hello_world()
{
    const char *message = "hello world";
    return message;
}
```

Golang function
```
package main

/*
#cgo CFLAGS: -I.
#cgo LDFLAGS: -L./x64/Release -lmywindow
#include "pch.h"
*/
import "C"
import "fmt"

func main() {
	msg := C.hello_world()
	fmt.Println("Message from static lib : ", msg)
}

```

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Administrator\go\pkg\mod
set GOOS=windows
set GOPATH=C:\Users\Administrator\go
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.20.5
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\Administrator\Desktop\static_lib\window\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\2\go-build2277286378=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
I try many ways to use my custom static lib  and it not work

### What did you expect to see?
 - Use my custom library with golang

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
