### ISSUE TITLE
go is not recognizing a bool variable being used after initializing

### ISSUE THREAD

**Issue by rishavs** [golang/go#61814]
### What version of Go are you using (`go version`)?
1.20
The bug is also in dev

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

PS C:\Users\risharan\Documents\GitHub\freya> go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\risharan\AppData\Local\go-build
set GOENV=C:\Users\risharan\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\risharan\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\risharan\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Users\risharan\scoop\apps\go\current
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Users\risharan\scoop\apps\go\current\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.20.7
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\risharan\Documents\GitHub\freya\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\risharan\AppData\Local\Temp\go-build3815782178=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

I ran this program
```
package main

func main() {
	var fre bool
	fre = true
}
```
Here's the link for the playground https://go.dev/play/p/Qq3shMPahYz?v=gotip

### What did you expect to see?
The program should compile. 

### What did you see instead?

Instead it is erroring out and saying `./prog.go:6:6: fre declared and not used`, which makes no sense

**Comment by seankhliao** [comment]
working as intended, `fre` is never read.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
