### ISSUE TITLE
x/sys/windows: Add SetFileValidData and SetFilePointerEx support 

### ISSUE THREAD

**Issue by kanak-clumio** [golang/go#61834]
Currently, this package does not support `SetFileValidData` and `SetFilePointerEx` syscalls. Is there any specific reason not to have this?

Adding this support should be very straightforward.

**Comment by bcmills** [comment]
(CC @golang/windows)

**Comment by bcmills** [comment]
`SetFilePointerEx` seems like an obvious addition: we already have `SetFilePointer` and AFAICT the only difference is the operand size.

I also see no reason not to add `SetFileValidData`. Want to send a CL?

**Comment by kanak-clumio** [comment]
Sure! I've not contributed to golang yet and am used to github and not gerrit. Let me look into setting up the repo and will create a PR with this change

**Comment by dtangster** [comment]
@mknyszek Do you know why this ticket issue is marked as closed? Looking at the changes, it looks like only `SetFileValidData` was added and not `SetFilePointerEx`.
