### ISSUE TITLE
net/http: After HTTP write StatusSwitchingProtocols, calling Hijack doesn't clean up req.Body data

### ISSUE THREAD

**Issue by lujinda** [golang/go#61841]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

The issue with the latest code of master still exists

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

When Containerd processes exec requests, it will upgrade the HTTP protocol to SPDY through HTTP Upgrade.
```Golang
// UpgradeResponse upgrades an HTTP response to one that supports multiplexed
// streams. newStreamHandler will be called synchronously whenever the
// other end of the upgraded connection creates a new stream.
func (u responseUpgrader) UpgradeResponse(w http.ResponseWriter, req *http.Request, newStreamHandler httpstream.NewStreamHandler) httpstream.Connection {
	connectionHeader := strings.ToLower(req.Header.Get(httpstream.HeaderConnection))
	upgradeHeader := strings.ToLower(req.Header.Get(httpstream.HeaderUpgrade))
	if !strings.Contains(connectionHeader, strings.ToLower(httpstream.HeaderUpgrade)) || !strings.Contains(upgradeHeader, strings.ToLower(HeaderSpdy31)) {
		errorMsg := fmt.Sprintf("unable to upgrade: missing upgrade headers in request: %#v", req.Header)
		http.Error(w, errorMsg, http.StatusBadRequest)
		return nil
	}

	hijacker, ok := w.(http.Hijacker)
	if !ok {
		errorMsg := fmt.Sprintf("unable to upgrade: unable to hijack response")
		http.Error(w, errorMsg, http.StatusInternalServerError)
		return nil
	}

	w.Header().Add(httpstream.HeaderConnection, httpstream.HeaderUpgrade)
	w.Header().Add(httpstream.HeaderUpgrade, HeaderSpdy31)
	w.WriteHeader(http.StatusSwitchingProtocols)

	conn, bufrw, err := hijacker.Hijack()
	if err != nil {
		runtime.HandleError(fmt.Errorf("unable to upgrade: error hijacking response: %v", err))
		return nil
	}

```

In the `Hijack` function, if `writeHeader==true` , `w.cw.flush()` will be called
https://github.com/golang/go/blob/24f83ed4e29495d5b8b6375aeaa2d34d14629c7d/src/net/http/server.go#L2075-L2077

and the `writeHeader` in the `flush` function will eventually clear the content of req.Body:

https://github.com/golang/go/blob/2c95fa4f31aec5c903947920e9e555f435869359/src/net/http/server.go#L397-L402

https://github.com/golang/go/blob/2c95fa4f31aec5c903947920e9e555f435869359/src/net/http/server.go#L1401-L1422

So if you want to clear req.Body, `writeHeader` must be true. writeHeader is set in the `(w *response) WriteHeader` function. But if the code is 101, it will not be set. So in our scene, `writeHeader` is always false.
https://github.com/golang/go/blob/24f83ed4e29495d5b8b6375aeaa2d34d14629c7d/src/net/http/server.go#L1143-L1181

If there is data in the HTTP Body (such as Transfer-Encoding: chunked time, Body is 0\r\n\r\n), the raw conn obtained by Hijack will always have dirty data, resulting in the upgraded protocol (such as SPDY, WebSocket) have problems.

Can we modify `Hijack` like this?
```Golang
// Hijack implements the Hijacker.Hijack method. Our response is both a ResponseWriter
// and a Hijacker.
func (w *response) Hijack() (rwc net.Conn, buf *bufio.ReadWriter, err error) {
	if w.handlerDone.isSet() {
		panic("net/http: Hijack called after ServeHTTP finished")
	}
	// if w.wroteHeader {
	w.cw.flush() // Always call flush
	// }
```

**Comment by bcmills** [comment]
The documentation for [`net/http.Hijacker`](https://pkg.go.dev/net/http#Hijacker) explicitly says:
>	```go
> 	// The returned bufio.Reader may contain unprocessed buffered
>	// data from the client.
>	```

Does that not cover exactly this situation?

(CC @neild)

**Comment by lujinda** [comment]
> 

Thank you for your reply.
Also as described in the documentation:
> 
	// After a call to Hijack, the original Request.Body must not
	// be used.

So I think that after adjusting Hijack, the original content of req.Body is no longer meaningful?

thx

**Comment by lujinda** [comment]
> The documentation for [`net/http.Hijacker`](https://pkg.go.dev/net/http#Hijacker) explicitly says:
> 
> > ```go
> >  // The returned bufio.Reader may contain unprocessed buffered
> >  // data from the client.
> > ```
> 
> Does that not cover exactly this situation?
> 
> (CC @neild)

Thank you for your reply.
Also as described in the documentation:
> 
	// After a call to Hijack, the original Request.Body must not
	// be used.

So I think that after called Hijack, the original content of req.Body is no longer meaningful?

thx

**Comment by neild** [comment]
If you want to remove the original request body from the connection before hijacking it, you can drain it yourself by reading `Request.Body` to completion before calling Hijack. (For example, `io.Copy(io.Discard, req.Body)`.)

Hijacking a connection takes over ownership of the socket from `net/http`. Reading from `Request.Body` can read from the socket, so you must not read from the body after hijacking.

**Comment by seankhliao** [comment]
looks like it's working as intended
