### ISSUE TITLE
cmd/go: `go mod init' from 1.21 incompatible with older versions

### ISSUE THREAD

**Issue by howardjohn** [golang/go#61851]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.0 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?

Using 1.21's `go mod init`:
```
$ cd `mktemp -d`
$ go1.21.0 mod init test
$ go1.21.0 build
no Go files in ...
$ go1.20 build
go: errors parsing go.mod:
/tmp/tmp.eoz8RDYcBC/go.mod:3: invalid go version '1.21.0': must match format 1.23
```

We can see the result is not compatible with older versions

If we manually set the go.mod up with the same semantics, it works fine:
```
$ cd `mktemp -d`
$ cat <<EOF > go.mod
module test

go 1.21
EOF
$ go1.21.0 build
no Go files in ...
$ go1.20 build
no Go files in ...
```

### What did you expect to see?

`go mod init` created by 1.21 can be built by older Go versions

### What did you see instead?

Somewhat obscure error

**Comment by bcmills** [comment]
In general a `go.mod` file (or Go source file) created for a higher Go version cannot be expected to successfully build with an older go version.

Starting with Go 1.21, you can use `go get go@1.20` or similar to explicitly downgrade for compatibility with an older release.

(You can also use the older `go mod tidy` flag for that, like `go mod tidy -go=1.20`, which works with older Go releases back to 1.17, although `go get` is preferred going forward.)
