### ISSUE TITLE
x/website/_content/doc/go1.21: dead link to Buffer.AvailableBuffer

### ISSUE THREAD

**Issue by gazerro** [golang/go#61861]
In https://go.dev/doc/go1.21 the link to `Buffer.AvailableBuffer` is `/pkg/bytes/#AvailableBuffer` instead of `/pkg/bytes/#Buffer.AvailableBuffer`.

**Comment by ianlancetaylor** [comment]
Thanks, sent https://go.dev/cl/517375.
