### ISSUE TITLE
cmd/go, x/mod: "invalid go version" message mentions old version format

### ISSUE THREAD

**Issue by dominikh** [golang/go#61888]
When parsing an invalid `go` line in a go.mod, the error message says

```
go: errors parsing go.mod:
go.mod:3: invalid go version '1.22foo': must match format 1.23
```

but that's not strictly true, it doesn't have to match the `1.23` format anymore.

**Comment by seankhliao** [comment]
cc @bcmills

**Comment by jamietanna** [comment]
What version of the `go` CLI was this with? I've hit this this morning when using `gopls` that's been compiled with a pre-1.21 `go`

**Comment by vincenthsh** [comment]
just came across this, to update vscode go tooling:

1. Press Ctrl+Shift+P
1. Select Go: Install/Update tools

or just to update golang language server:

```sh
go install golang.org/x/tools/gopls@latest
```

and you may Ctrl+Shift+P to `restart language server`

**Comment by amrojjeh** [comment]
I just got this error message recently after I updated go. I updated gopls as well and that did not fix it. For now I've manually edited the version number to be `1.21` rather than `1.21.1`

**Comment by optik-aper** [comment]
I am also noticing this occurring in newly `go mod init`'d projects on fresh pull of `gopls@latest`.  Manually edition the go version allows the language server to restart without error.  I'm using `vim-go` which utilizes `YouCompleteMe` for the LSP communication to `gopls`.

```sh
go version                                                                                             
go version go1.21.0 linux/amd64

gopls version                                                                                         
golang.org/x/tools/gopls v0.13.2
    golang.org/x/tools/gopls@v0.13.2 h1:Pyvx6MKvatbX3zzZmdGiFRfQZl0ohPlt2sFxO/5j6Ro=
```

**Comment by Seefooo** [comment]
I am also running into this. Similar setup to @optik-aper:
```
go version go1.21.1 linux/amd64
golang.org/x/tools/gopls v0.13.2
    golang.org/x/tools/gopls@v0.13.2 h1:Pyvx6MKvatbX3zzZmdGiFRfQZl0ohPlt2sFxO/5j6Ro=
```

**Comment by andydotxyz** [comment]
Possibly related to [#63370](https://github.com/golang/go/issues/63370)? 
There seems to be confusion to what version numbers the tools should support. Part of the challenge of introducing a new format and requiring it in the same release I think?

**Comment by let4be** [comment]
For me fixing version in go.mod and go.work to 1.21 didn't resolve the issue :(
What am I missing?

**Comment by let4be** [comment]
Hrm... should do this for all other modules in a workspace as well
Okay, changing all stuff to 1.21 resolved the issue

Is there currenlt no way to specify the version exactly, like 1.21.3?

**Comment by Rican7** [comment]
Is this related to #62584?

**Comment by kampaidev** [comment]
Still an issue please fix

**Comment by bcmills** [comment]
@kampaidev https://go.dev/wiki/NoPlusOne

**Comment by luisdavim** [comment]
I'm also getting this error, using:

```
go version    
go version go1.21.5 darwin/arm64

gopls version
golang.org/x/tools/gopls v0.11.0
    golang.org/x/tools/gopls@v0.11.0 h1:/nvKHdTtePQmrv9XN3gIUN9MOdUrKzO/dcqgbG6x8EY=
````

Previously I'd get around it by editing the `go.mod` file and removing the patch version, for example by changing `go 1.21.4` to `go 1.21` and that still works if the the mod file doesn't use `replace` if it does, then I get:

```
updates to go.mod needed, disabled by -mod=readonly; to update it: ^Igo mod tidy
```

To get it working I have to:

* edit the `go.mod` file to remove the patch version, for example by changing `go 1.21.4` to `go 1.21`
* run `go work init . .`
* edit the `go.work` file to remove the patch version, for example by changing `go 1.21.5` to `go 1.21`

but why? why is all this needed? why are the patch versions being added to the mod files?

**Comment by permalik** [comment]
> I'm also getting this error, using:
> 
> ```
> go version    
> go version go1.21.5 darwin/arm64
> 
> gopls version
> golang.org/x/tools/gopls v0.11.0
>     golang.org/x/tools/gopls@v0.11.0 h1:/nvKHdTtePQmrv9XN3gIUN9MOdUrKzO/dcqgbG6x8EY=
> ```
> 
> Previously I'd get around it by editing the `go.mod` file and removing the patch version, for example by changing `go 1.21.4` to `go 1.21` and that still works if the the mod file doesn't use `replace` if it does, then I get:
> 
> ```
> updates to go.mod needed, disabled by -mod=readonly; to update it: ^Igo mod tidy
> ```
> 
> To get it working I have to:
> 
>     * edit the `go.mod` file to remove the patch version, for example by changing `go 1.21.4` to `go 1.21`
> 
>     * run `go work init . .`
> 
>     * edit the `go.work` file to remove the patch version, for example by changing `go 1.21.5` to `go 1.21`
> 
> 
> but why? why is all this needed? why are the patch versions being added to the mod files?

Also getting this at 1.21.5.
Had to move to 1.21

**Comment by bcmills** [comment]
Looks like this was partially fixed in `x/mod` in https://go.dev/cl/527897, but we missed the ones in `WorkFile.add`:
https://cs.opensource.google/go/x/mod/+/master:modfile/rule.go;l=633-649;drc=6e58e47c7bd6672665dc35cce7b1f325d2addd67

🤦‍♂️

**Comment by mapkon** [comment]
Happy to merge if you can raise a PR

**Comment by bcmills** [comment]
I think this is fixed as of https://go.dev/cl/560855.

**Comment by maxmeng-oss** [comment]
@bcmills can we backport this CL to 1.21 and 1.22?

https://github.com/hashicorp/terraform using `go1.21.5`

**Comment by bcmills** [comment]
@maxmeng-hw, the only change for this issue was to an error message. That does not seem worth backporting.

**Comment by UponTheSky** [comment]
If anyone has the same issue when building a docker image, consider making the go version on your machine the same as the one in the `Dockerfile`

```sh
Step 4/8 : RUN go mod download
 ---> Running in 23ecb7792e18
go: errors parsing go.mod:
/app/go.mod:3: invalid go version '1.22.0': must match format 1.23
```

In my case, I was using Go 1.22 on my machine whereas the `Dockerfile` was using the base image of `golang:1.18.0-alpine`.

**Comment by oussamaAbdelwahed** [comment]
> just came across this, to update vscode go tooling:
> 
> 1. Press Ctrl+Shift+P
> 2. Select Go: Install/Update tools
> 
> or just to update golang language server:
> 
> ```shell
> go install golang.org/x/tools/gopls@latest
> ```
> 
> and you may Ctrl+Shift+P to `restart language server`

After doing the steps above , you sometimes have to manually close and reopen vscode (even Ctrl+Shift+P then 'Reload Window' doesnt worked for me )

**Comment by MeanManMachineMan** [comment]
Sorry to bump and old thread but there's another way to go around it since in my case even a language server restart didn't fix the issue. Instead of forcing gopls version updates, i saw that my vscode itself was using an older go binary (which could very well be why the solution wasn't working for me). I personally use and recommend `gvm` for managing multiple go versions so i thought of using the path that is specified by gvm for `go1.21.5` and forcing vscode to use that. Step by step:

1. Run `gvm use go1.21.5` or whichever version you want, then `echo $GOROOT`:
 ```shell
  [-> echo $GOROOT
  /Users/your_username/.gvm/gos/go1.21.5
 ``` 
 2. From the bottom right of the vscode window, select the go version -> `Choose Go Environment` -> `Choose from file browser`. Hit `Cmd+Shift+.` to be able to view hidden folders in the file explorer and then locate the path above. Navigate to `bin`->`go` and select that file.
 3. Follow the vscode prompt to recompile gopls and other modules with this version and it will automatically restart the language server after that.
