### ISSUE TITLE
doc: mention language downgrading via `//go:build`

### ISSUE THREAD

**Issue by dominikh** [golang/go#61894]
Reading https://go.dev/doc/toolchain, only upgrading the language version on a per-file basis is shown, not downgrading.

It does say that

> The language version can be changed on a per-file basis by using a [build constraint](https://go.dev/cmd/go#hdr-Build_constraints)

but that's a bit implicit, considering this is a major change from how module versions and build constraints used to interact.

https://pkg.go.dev/cmd/go#hdr-Build_constraints doesn't mention the semantics of version build constraints, either.

**Comment by mknyszek** [comment]
CC @rsc

**Comment by oliverpool** [comment]
I got bitten by this in #64308 where implementing a polyfill for a previous version of the compiler would not work:
```go
//go:build !go1.21

package main

// min is a pseudo-polyfill for go1.21 min function
func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
```

Currently the [doc](https://go.dev/doc/toolchain#config) states:

> For example, a module containing code that uses the Go 1.21 language version should have a <code>go.mod</code> file with a <code>go</code> line such as <code>go 1.21</code> or <code>go 1.21.3</code>. If a specific source file should be compiled only when using a newer Go toolchain, adding <code>//go:build go1.22</code> to that source file both ensures that only Go 1.22 and newer toolchains will compile the file and also changes the language version in that
file to Go 1.22.

It would be helpful to add something like:

> For a module to use builtin functions introduced in a later version of Go, use a proxy function with two files implementing it. One with the <code>//go:build go1.22</code> build constraint which directly calls the builtin, the other with <code>//go:build go1.21</code>, with a polyfill of the (not-yet available) builtin.

**Comment by oliverpool** [comment]
the **language version** declared by the `go` directive of the `go.mod` **is not used to satisfy build constraints**  (which are checked against the currently running Go toolchain).
