### ISSUE TITLE
strings: TrimLeft fails in certain cases

### ISSUE THREAD

**Issue by sanketsudake** [golang/go#61919]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.7 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

https://go.dev/play/p/Abefs5j3At0

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

```
func main() {
	fmt.Println(strings.TrimLeft("user_support", "user_"))
	// Expected: support Actual: pport
	fmt.Println(strings.TrimLeft("user_conversation", "user_"))
	// Expected: conversation Actual: conversation
	fmt.Println(strings.TrimLeft("user_suconversation", "user_"))
	// Expected: suconversation Actual: conversation
}
```
https://go.dev/play/p/Abefs5j3At0

### What did you expect to see?

`TrimLeft` output not expected in above cases. Output seems bit different when string contains `su` substring.

### What did you see instead?

Please see above snippet.

**Comment by merykitty** [comment]
> // TrimLeft returns a slice of the string s with all leading
// Unicode code points contained in cutset removed.
//
// To remove a prefix, use TrimPrefix instead.

In other word, `cutset` is interpreted as a character set, and the longest prefix of `s` whose characters are all in `cutset` is chosen and trimmed.
