### ISSUE TITLE
valgrind fails #60600

### ISSUE THREAD

**Issue by erezgeva** [golang/go#61929]
As #60600 was closed with not explanation.
And as I can not reopen it.
I open a new ticket.

**Comment by seankhliao** [comment]
I believe closing was the correct call, it seems more to be an error on valgrind rather than go

**Comment by erezgeva** [comment]
You are like a politician.
Always blame others.
Yet, other projects make sure valgrind works.
Sometimes with a helping flags, like python.
Seems you do not want to really solve problems.
My conclusion is not to use you. And advice others to skip you.
