### ISSUE TITLE
x/build/cmd/coordinator: compile error in `os/os_test.go` not detected by `misc-compile` TryBots

### ISSUE THREAD

**Issue by bcmills** [golang/go#61923]
https://go.dev/cl/517755 caused a compilation error on the `plan9` builders (https://build.golang.org/log/2613479c07e3aaf02e75f15f00b8d1c01c9ec217):
```
# os_test [os.test]
os/os_test.go:3297:70: too many arguments in call to syscall.Open
	have (string, number, number)
	want (string, int)
os/os_test.go:3302:55: too many arguments in call to syscall.Open
	have (string, number, number)
	want (string, int)
FAIL	os [build failed]
```

I didn't catch that during code review because the CL had a passing TryBot run, and based on #20119 I assumed that the `misc-compile` TryBots would have caught any compile error in the test.

It appears that either the fix for #20119 was incomplete, or something has regressed since then to cause the `misc-compile` TryBots to no longer catch compile errors in tests.

(CC @dmitshur @aclements @golang/release)

**Comment by bcmills** [comment]
I suspect this regressed in https://go.dev/cl/464955 (for #58163; attn @mknyszek).

**Comment by mknyszek** [comment]
Thanks for flagging this, on it.

**Comment by mknyszek** [comment]
OK yeah, got it. I suspect this should be an easy fix.

**Comment by dmitshur** [comment]
For the record, this is is being caught in LUCI as intended, see the misccompile column at https://ci.chromium.org/p/golang/g/go-gotip-ci/console. So this issue only affects x/build/cmd/coordinator.

<img width="669" alt="image" src="https://github.com/golang/go/assets/1924134/cf364b3f-d297-4336-afe6-08a556fbb8fd">
