### ISSUE TITLE
v1.21 compile.exe reported as a Thread by WindowsDefender

### ISSUE THREAD

**Issue by vaind** [golang/go#61937]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.0 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\dlugo\AppData\Local\go-build
set GOENV=C:\Users\dlugo\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\dlugo\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\dlugo\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Users\dlugo\scoop\apps\go\current
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Users\dlugo\scoop\apps\go\current\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.21.0
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\dlugo\AppData\Local\Temp\go-build1330945210=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

Installed latest `go` through scoop (but also tried downloading from https://go.dev/dl/go1.21.0.windows-amd64.zip) and when running tests in VS Code, Windows Defender started reporting `compile.exe` as a threat and the compilation stopped working.

> "Details: This program is dangerous and executes commands from an attacker."
> ... C:\Users\dlugo\scoop\apps\go\1.21.0\pkg\tool\windows_amd64\compile.exe

### What did you see instead?

<img width="629" alt="image" src="https://github.com/golang/go/assets/6349682/7a50aa41-a30d-4807-aad5-17a9837b23af">

**Comment by seankhliao** [comment]
https://golang.org/doc/faq#virus
