### ISSUE TITLE
net/http: HTTP/1.x transport connection broken: http: ContentLength=3253 with Body length 0

### ISSUE THREAD

**Issue by Jayesh-Cldscle** [golang/go#61946]
I am trying to upload objects in s3 using presigned url, however, I am facing above error whenever I run the script

I am using net/http module and already added Transfer-Encoding=Identity and Content-Length headers.

But stuck on this error,

Can someone help me here?

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
