### ISSUE TITLE
x/pkgsite:https://pkg.go.dev/github.com/raydcode/easy-json

### ISSUE THREAD

**Issue by raydcode** [golang/go#61947]
### What is the URL of the page with the issue?
 https://pkg.go.dev/github.com/raydcode/easy-json
 
 
### What is your user agent?
 [Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36](https://explore.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)

 
 
 
### Screenshot
![image](https://github.com/golang/go/assets/83969563/821bd5f4-8154-462f-b718-b52d7c0aeb44)

 

 
 
 
### What did you do?

I publish a package but i can't able to see my documentation in https://pkg.go.dev/github.com/raydcode/easy-json
 

 
 
 
### What did you expect to see?
 
I need to see the documentation 
 
 
### What did you see instead?

Documentation is not displayed due to license restrictions.

See our [license policy](https://pkg.go.dev/license-policy).

**Comment by seankhliao** [comment]
I believe your license text deviates too much from the standard form of an MIT license. GitHub doesn't recognize it either.
Please adjust it to match.
