### ISSUE TITLE
crypto/tls: add GODEBUG to control max RSA key size

### ISSUE THREAD

**Issue by rolandshoemaker** [golang/go#61965]
`tlsmaxrsasize`, See http://go.dev/cl/517495.

**Comment by rolandshoemaker** [comment]
@gopherbot please open backport issues.

**Comment by dmitshur** [comment]
[CL 517495](https://go.dev/cl/517495) is submitted. Is there more to do for Go1.22?

**Comment by rolandshoemaker** [comment]
I don't believe so, I opened this after the fact in order to create backport issues, so it didn't get closed when the CL was submitted (because it was submitted before the issue existed 😅). Can probably be closed.

**Comment by dmitshur** [comment]
Let's close it to help keep issues that are open actionable, then. Thanks.
