### ISSUE TITLE
runtime: "unexpected fault address 0x0" during GC

### ISSUE THREAD

**Issue by gopherbot** [golang/go#6196]
by **mitchell.hashimoto**:

<pre>Go version:
go version go1.1.2 linux/amd64

While I haven't been able to reproduce this, a handful of users of my software have been
seeing this regularly:

<a href="https://gist.github.com/mitchellh/6283509">https://gist.github.com/mitchellh/6283509</a>

It appears to be a SIGSEGV during hashmap access during GC. I'm sorry I can't provide
much more information. If you need to point the stack traces back at my own code, here
is the code in question (tagged so it won't change):
<a href="https://github.com/mitchellh/packer/tree/v0.3.3">https://github.com/mitchellh/packer/tree/v0.3.3</a></pre>

**Comment by randall77** [comment]
Closing for now, reopen if you're still having problems with go1.4+.
