### ISSUE TITLE
x/pkgsite: package removal request for https://pkg.go.dev/github.com/lucavallin/mawu

### ISSUE THREAD

**Issue by lucavallin** [golang/go#61988]
### What is the path of the package that you would like to have removed?

https://pkg.go.dev/github.com/lucavallin/mawu

### Are you the owner of this package?

Yes

### What is the reason that you could not retract this package instead?

Repository changed name.

**Comment by seankhliao** [comment]
retract directives work even across repository renames, please try them

**Comment by lucavallin** [comment]
Thanks @seankhliao! I tested it but it didn't work: https://github.com/lucavallin/brosa/releases. Does it take some extra time to happen?

**Comment by seankhliao** [comment]
Did you pull the version with the retraction through the proxy?
eg `go get github.com/lucavallin/mawu@v0.0.1`

**Comment by lucavallin** [comment]
Thanks again @seankhliao. I did that and got the message that the version has been retracted, however, the link at https://pkg.go.dev/github.com/lucavallin/mawu is still visible.

**Comment by bcmills** [comment]
The link is still visible, but it should be suppressed in search results per #47590.

@lucavallin, are you finding that not to be the case?

**Comment by lucavallin** [comment]
Hey @bcmills, thanks! That is the case, however, I thought retracting the version would also delete the old one from the website.
