### ISSUE TITLE
x/pkgsite: OpenSearch not recognized by Firefox 116.0

### ISSUE THREAD

**Issue by Merovius** [golang/go#61986]
### What is the URL of the page with the issue?

https://pkg.go.dev/

### What is your user agent?

Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0

### Screenshot

![2023-08-13-095902_1920x1080_scrot](https://github.com/golang/go/assets/720787/455c3a31-1f6d-4739-88f0-215b238e1aef)

### What did you do?

Right-click on the address bar in Firefox

### What did you expect to see?

[An Option to add pkg.go.dev as a search engine to Firefox](https://support.mozilla.org/en-US/kb/add-or-remove-search-engine-firefox#w_add-a-search-engine-from-the-address-bar).

This works with other pages (like Wikipedia or YouTube) but not with `pkg.go.dev`. I'm not entirely sure, but I *think* I actually did that not very long ago, when first setting up Firefox, but I had to reset my profile and now it doesn't. I can't imagine how it would've done that, but if my memory is correct, the timing would implicate [this commit](https://github.com/golang/pkgsite/commit/17236d30855a86d83b4d373b702844f39c29c9b0).

### What did you see instead?

No such option.

**Comment by philippgille** [comment]
>  I'm not entirely sure, but I think I actually did that not very long ago, when first setting up Firefox

Was that maybe via the search form, i.e. 
![image](https://github.com/golang/go/assets/170670/09266b6d-4059-4611-8c2f-0038d3800e42)

**Comment by Merovius** [comment]
The "Add a Keyword for this Search" behaves somewhat differently - it creates a bookmark with a search query, instead of registering a search engine. That means a) you have to put that bookmark somewhere and b) it doesn't have the same interactivity as a search engine.

So, *maybe* that was? Though I don't really think so. But even if - I'd prefer `pkgsite` to support the actual OpenSearch integration.

**Comment by findleyr** [comment]
Thanks for pointing this out. I agree this would be good to support.  Added `Help Wanted`, as this looks small but not entirely trivial, and we may not get to it soon.
