### ISSUE TITLE
cmd/link: OSX internal linker generates invalid App store executable

### ISSUE THREAD

**Issue by gopherbot** [golang/go#6198]
by **rustf3**:

<pre>What steps will reproduce the problem?
   &gt; go build hello  (hello world will do)
   &gt; otool -l hello | grep LC_  (compare this output with valid output below)
      cmd LC_SEGMENT_64
      cmd LC_SEGMENT_64
      cmd LC_SEGMENT_64
      cmd LC_SEGMENT_64
      cmd LC_SEGMENT_64
      cmd LC_UNIXTHREAD
      cmd LC_SYMTAB
      cmd LC_DYSYMTAB
      cmd LC_LOAD_DYLINKER

The OSX executable produced is fine except that it will be rejected if submitted to the
Mac App Store.  The error that comes back after submitting the app is:

    &quot;Missing DWARF data - Your app does not include DWARF data with architecture information in
     Contents/MacOS/Bampf . In your Xcode build settings, ensure that the debug information is set
     to &quot;DWARF with dSYM&quot; and that the list of valid architectures does not include PPC.&quot; 

What is the expected output?
    A workaround is to use the external linker as follows:
   &gt; go build -ldflags &quot;-linkmode=external&quot; hello.go 
   &gt; otool -l hello | grep LC_
      cmd LC_SEGMENT_64
      cmd LC_SEGMENT_64
      cmd LC_SEGMENT_64
      cmd LC_SEGMENT_64
      cmd LC_DYLD_INFO_ONLY
      cmd LC_SYMTAB
      cmd LC_DYSYMTAB
      cmd LC_LOAD_DYLINKER
      cmd LC_UUID                               &lt;-- needed for Mac App Store?
      cmd LC_VERSION_MIN_MACOSX
      cmd LC_SOURCE_VERSION
      cmd LC_MAIN
      cmd LC_LOAD_DYLIB
      cmd LC_FUNCTION_STARTS
      cmd LC_DATA_IN_CODE
      cmd LC_DYLIB_CODE_SIGN_DRS

What do you see instead?
   The golang internal linker produces OSX executables that can be packaged signed, and self distributed.  Ideally it would also produce OSX executables that could be submitted to the App store by creating output similar to the native OSX gcc/ld.

Which compiler are you using (5g, 6g, 8g, gccgo)?
  6g

Which operating system are you using?
  OS X 10.8.4 (12E55)

Which version are you using?  (run 'go version')
   go version go1.1.2 darwin/amd64 (also happens with go1.1.1)

Please provide any additional information below.
   This problem appears similar in nature to <a href="https://golang.org/issue/5238">https://golang.org/issue/5238</a> where the external linker was used to produce system specific fields in the binary.</pre>

**Comment by odeke-em** [comment]
It has been a couple of years (~7 years) since this issue was filed and lots of progress has been made in that time. Lots of Apple binaries have been built using Go, but also this issue hasn't had much activity. I am therefore going to close it. Thank you though for reporting it rustf3 (even though I can't easily find your Github name) and also @james4k.
