### ISSUE TITLE
x/pkgsite: package removal request for github.com/feynmaz/cypherhunterscrapper

### ISSUE THREAD

**Issue by feynmaz** [golang/go#61990]
### What is the path of the package that you would like to have removed?
https://pkg.go.dev/github.com/feynmaz/cypherhunterscrapper

### Are you the owner of this package?
Yes, my page is https://github.com/feynmaz

### What is the reason that you could not retract this package instead?
The features in this package no longer work because they depended on a site that changed its privacy policy. This package is the copy of https://github.com/golang/go/issues/61989

**Comment by seankhliao** [comment]
please try following the instructions at https://github.com/golang/go/issues/60985#issuecomment-1607712161
