### ISSUE TITLE
x/pkgsite: package removal request for [github.com/jefferyjob/go-redis-lock]

### ISSUE THREAD

**Issue by jefferyjob** [golang/go#62029]
### What is the path of the package that you would like to have removed?

github.com/jefferyjob/go-redis-lock

### Are you the owner of this package?

Yes

### What is the reason that you could not retract this package instead?

Because I want to delete this package and republish it

**Comment by seankhliao** [comment]
removing won't let you reuse versions

**Comment by jefferyjob** [comment]
But because I have already deleted the GitHub warehouse, can the go. dev package be synchronously deleted?

https://pkg.go.dev/github.com/jefferyjob/go-redis-lock
