### ISSUE TITLE
cmd/compile: ICE 'F': func F, startMem[b4] has different values, old v1, new v50

### ISSUE THREAD

**Issue by Nasfame** [golang/go#62027]
### What version of Go are you using (`go version`)?

<pre>
$ go version
gotip
</pre>

### Does this issue reproduce with the latest release?
Yes, go1.21+

Platform affected: faketime/playground; linux/amd64

**_Working on: darwin/arm_**

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
playground
</pre></details>

### What did you do?
https://go.dev/play/p/Lnq1zWYrYwY?v=gotip

### What did you expect to see?
No ICE

### What did you see instead?
ICE

Relates to #61992

**Comment by randall77** [comment]
This is likely just a dup of #61992.

**Comment by Nasfame** [comment]
@randall77 a dup but essentially a valid testcase
