### ISSUE TITLE
x/vuln: 

### ISSUE THREAD

**Issue by Youahui** [golang/go#62058]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.0 windows/amd64
</pre>

### Does this issue reproduce at the latest version of golang.org/x/vuln?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=auto
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Administrator\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Administrator\go
set GOPRIVATE=
set GOPROXY=https://goproxy.io,direct
set GOROOT=D:\go
set GOSUMDB=off
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=D:\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.21.0
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=
</pre></details>

### What did you do?
updated update my go  version

### What did you expect to see?
fix it

### What did you see instead?
GOROOT=D:\go #gosetup
GOPATH=C:\Users\Administrator\go #gosetup
D:\go\bin\go.exe build -o C:\Users\Administrator\AppData\Local\JetBrains\GoLand2023.1\tmp\GoLand\___go_build_merchant_cmd_admin.exe merchant/cmd/admin #gosetup
# runtime/internal/sys
D:\go\src\runtime\internal\sys\intrinsics_common.go:9:7: len8tab redeclared in this block
	D:\go\src\runtime\internal\sys\intrinsics.go:76:7: other declaration of len8tab
D:\go\src\runtime\internal\sys\intrinsics_common.go:32:6: Len64 redeclared in this block
	D:\go\src\runtime\internal\sys\intrinsics.go:99:6: other declaration of Len64
D:\go\src\runtime\internal\sys\intrinsics_common.go:50:7: m0 redeclared in this block
	D:\go\src\runtime\internal\sys\intrinsics.go:117:7: other declaration of m0
D:\go\src\runtime\internal\sys\intrinsics_common.go:51:7: m1 redeclared in this block
	D:\go\src\runtime\internal\sys\intrinsics.go:118:7: other declaration of m1
D:\go\src\runtime\internal\sys\intrinsics_common.go:52:7: m2 redeclared in this block
	D:\go\src\runtime\internal\sys\intrinsics.go:119:7: other declaration of m2
D:\go\src\runtime\internal\sys\intrinsics_common.go:55:6: OnesCount64 redeclared in this block
	D:\go\src\runtime\internal\sys\intrinsics.go:122:6: other declaration of OnesCount64
D:\go\src\runtime\internal\sys\intrinsics_common.go:86:6: LeadingZeros64 redeclared in this block
	D:\go\src\runtime\internal\sys\intrinsics.go:153:6: other declaration of LeadingZeros64
D:\go\src\runtime\internal\sys\intrinsics_common.go:89:6: LeadingZeros8 redeclared in this block
	D:\go\src\runtime\internal\sys\intrinsics.go:156:6: other declaration of LeadingZeros8
D:\go\src\runtime\internal\sys\intrinsics_common.go:92:6: Len8 redeclared in this block
	D:\go\src\runtime\internal\sys\intrinsics.go:159:6: other declaration of Len8
D:\go\src\runtime\internal\sys\intrinsics_common.go:101:6: Prefetch redeclared in this block
	D:\go\src\runtime\internal\sys\intrinsics.go:200:6: other declaration of Prefetch
D:\go\src\runtime\internal\sys\intrinsics_common.go:101:6: too many errors

Compilation finished with exit code 1

**Comment by seankhliao** [comment]
looks like you have a corrupt go installation.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
