### ISSUE TITLE
cmd/link: Setting rounding quantum to a value higher than the default page size breaks

### ISSUE THREAD

**Issue by Mihnea27** [golang/go#62064]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.0 linux/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><pre>$ go env
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/data00/home/mihnea/.cache/go-build'
GOENV='/data00/home/mihnea/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/data00/home/mihnea/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/data00/home/mihnea/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/data00/home/mihnea/test_go/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/data00/home/mihnea/test_go/go/pkg/tool/linux_arm64'
GOVCS=''
GOVERSION='go1.21.0'
GCCGO='gccgo'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/data00/home/mihnea/test_go/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build706829959=/tmp/go-build -gno-record-gcc-switches'

</pre></details>

### What did you do?

Simple hello world program, code: https://go.dev/play/p/lLJK7euS0R6
Build it with with:
`$ go build -ldflags "-R 0x200000" -o hello_world_2mb main.go`
Run with:
`$ ./hello_world_2mb`

### What did you expect to see?

`$ Hello world!`

### What did you see instead?

`$ Segmentation fault`

### Additional details

Looking at the binary with readelf -l:
<pre>$  readelf -l hello_world_2mb

Elf file type is EXEC (Executable file)
Entry point 0x6e7f0
There are 6 program headers, starting at offset 64

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  PHDR           0x0000000000000040 0x0000000000010040 0x0000000000010040
                 0x0000000000000150 0x0000000000000150  R      0x200000
readelf: Error: the PHDR segment is not covered by a LOAD segment
  NOTE           0x0000000000000f9c 0x0000000000010f9c 0x0000000000010f9c
                 0x0000000000000064 0x0000000000000064  R      0x4
  LOAD           0xffffffffffff0000 0x0000000000000000 0x0000000000000000
                 0x000000000008b1c4 0x000000000008b1c4  R E    0x200000
  LOAD           0x0000000000200000 0x0000000000200000 0x0000000000200000
                 0x00000000000968b8 0x00000000000968b8  R      0x200000
  LOAD           0x0000000000400000 0x0000000000400000 0x0000000000400000
                 0x0000000000009580 0x00000000000414f0  RW     0x200000
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x8

 Section to Segment mapping:
  Segment Sections...
   00
   01
   02
   03        P
   04        =7
   05
</pre>
Compared to the output of compiling the same program on an x86_64 machine:

<pre>$ readelf -l hello_world_2mb

Elf file type is EXEC (Executable file)
Entry point 0x45e500
There are 7 program headers, starting at offset 64

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  PHDR           0x0000000000000040 0x0000000000400040 0x0000000000400040
                 0x0000000000000188 0x0000000000000188  R      0x200000
  NOTE           0x0000000000000f9c 0x0000000000400f9c 0x0000000000400f9c
                 0x0000000000000064 0x0000000000000064  R      0x4
  LOAD           0x0000000000000000 0x0000000000400000 0x0000000000400000
                 0x0000000000081027 0x0000000000081027  R E    0x200000
  LOAD           0x0000000000200000 0x0000000000600000 0x0000000000600000
                 0x000000000008e818 0x000000000008e818  R      0x200000
  LOAD           0x0000000000400000 0x0000000000800000 0x0000000000800000
                 0x0000000000017fa0 0x000000000004bb68  RW     0x200000
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x8
  LOOS+0x5041580 0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000         0x8

 Section to Segment mapping:
  Segment Sections...
   00
   01     .note.go.buildid
   02     .text .note.go.buildid
   03     .rodata .typelink .itablink .gosymtab .gopclntab
   04     .go.buildinfo .noptrdata .data .bss .noptrbss
   05
   06
</pre>
Trying different values for the -R flag i notice that the issue appears only if the value passed is larger than 64KB which is the default page size on the ARM machine. Passing 4KB for example works just fine.

**Comment by dmitshur** [comment]
CC @golang/compiler.

**Comment by erifan** [comment]
One more point, on linux/arm64 and linux/amd64, it also fails when -R is less than 4k. When using external link mode, it always succeed no matter what value is set to -R. So I'm guessing this might not be just an arm64 specific issue.

**Comment by zhangfannie** [comment]
From the log output of ’readelf -l hello_world_2mb`, we can see that the **VirtAddr and PhysAddr of one PT_LOAD is 0**, which should be the cause of the segment fault.
```
  LOAD      0xffffffffffff0000 0x0000000000000000 0x0000000000000000
                 0x000000000008b1c4 0x000000000008b1c4  R E    0x200000
```
Why setting ‘-R ’ to ‘0x20000’ will cause the Vaddr and Paddr of the program header to be 0?  I looked at the linker code and it is the [fixElfPhdr ](https://github.com/golang/go/blob/master/src/cmd/link/internal/ld/elf.go#L304)function.
```
func fixElfPhdr(e *ElfPhdr) {
	frag := int(e.Vaddr & (e.Align - 1))

	e.Off -= uint64(frag)
	e.Vaddr -= uint64(frag)
	e.Paddr -= uint64(frag)
	e.Filesz += uint64(frag)
	e.Memsz += uint64(frag)
}
```
When `-R` is set to `0x20000`, `e.Align` is `0x20000`.  If `e.Addr` is not set by `-T`, the default value is `0x11000`, and 'e.Paddr` is equal to `e.Addr`, its value is also equal to 0x11000. 
Through the above calculation formula, the value of 'frag' is 0x11000, the values of 'e.Addr' and 'e.Paddr' are both 0, which is the adjusted the Vaddr and Paddr of the program header.

The same issue will also appear on x86 if set `-R` is greater than 4MB.

I'm not particularly familiar with linker. I'm thinking maybe we need to limit the value of `-R` based on the value of `-T` to avoid such issues? Thank you.

**Comment by zhangfannie** [comment]
This function does an **alignment** operation. Maybe there should be **rounding up** here? Because I lack an understanding of the correct behavior of `-R`, I don't know if setting the address of `PT_LOAD` to `0` when the value of `-R` is greater than the value of `-T` is valid behavior.
@cherrymui Do you have any ideas? Thank you.

**Comment by cherrymui** [comment]
Rounding up the `-T` value seems reasonable to me.

An alternative would be erroring out. We could require that if one sets `-R`, one also needs to set a corresponding `-T`.

**Comment by cherrymui** [comment]
I don't think this is ARM64 specific.

**Comment by d-bytebase** [comment]
Hi @cherrymui, could it be related to https://github.com/golang/go/issues/66993? It only occurs in Go 1.22 but not 1.21. It happens consistently only when the source imports large dependencies or probably when the object goes over certain size. The build failure happens on my MacOS/Darwin arm64, while there isn't build failure on ubuntu amd64. Thanks!

repo: https://github.com/bytebase/bytebase
build command: go build -p=8 -o ./.air/bytebase ./backend/bin/server/main.go
