### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by MrLinusMeow** [golang/go#62072]
### What is the URL of the page with the issue?
 https://go.dev/doc/tutorial/random-greeting
 
### What is your user agent?
[Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0]
 
### Screenshot
![image](https://github.com/golang/go/assets/66890270/9930ca99-1a48-4346-995e-77e0dd3e5460)
 
### What did you do?
Nothing much Just following the tutorial and then I found out that I need to add function to calculate seed
 
### What did you expect to see?
Working code
 
### What did you see instead?
Not working code

**Comment by seankhliao** [comment]
I don't see anything wrong with this, math/rand uses random seeds on the latest versions of Go.
