### ISSUE TITLE
x/pkgsite: package removal request for [github.com/jefferyjob/GoRedisLock]

### ISSUE THREAD

**Issue by jefferyjob** [golang/go#62082]
### What is the path of the package that you would like to have removed?

github.com/jefferyjob/GoRedisLock

### Are you the owner of this package?

yes

### What is the reason that you could not retract this package instead?

The original github warehouse has been deleted

**Comment by bcmills** [comment]
Presumably you still control the GitHub account. Can you recreate the repo to publish a retraction, as described in https://github.com/golang/go/issues/60985#issuecomment-1607712161?
