### ISSUE TITLE
cmd/internal/buildid: buildid invalid read when program alignment is zero

### ISSUE THREAD

**Issue by stevemk14ebr** [golang/go#62097]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.20.2
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?
Using binary 2a2513e8687993ed71cc48b09676abf18bb0e739f15473d36c50627b05036686 (on VT) running the buildid code over the sample fails to correctly read the notes section. This is not a Go binary, however this does excersize a failure case in the build id code here:
```
//note.go readELF

off += notesz
align := p.Align
alignedOff := (off + align - 1) &^ (align - 1)
notesz += alignedOff - off
off = alignedOff
filesz -= notesz
note = note[notesz:]
```

![image](https://github.com/golang/go/assets/6619205/24fe1b62-822e-4ff5-81ca-6e09afcd891a)

The  alignedOff is aligned to zero while the offset is positive leading to an underflow when the notesz is calculated. This later leads to an invalid array access at `note = note[notesz:]`

To fix, the code should ignore alignment when it's zero:
```
off += notesz
align := p.Align
if align != 0 {
    alignedOff := (off + align - 1) &^ (align - 1)
    notesz += alignedOff - off
    off = alignedOff
}
filesz -= notesz
note = note[notesz:]
```

**Comment by dmitshur** [comment]
Can you provide more context and/or links on what you mean by "binary 2a2513e8687993ed71cc48b09676abf18bb0e739f15473d36c50627b05036686" and "the buildid code"? Is this related to https://pkg.go.dev/cmd/internal/buildid or something else?

**Comment by stevemk14ebr** [comment]
This code here https://cs.opensource.google/go/go/+/master:src/cmd/internal/buildid/buildid.go;drc=615c7c18a70e0d6638accdb0fcc5f60c57a2118b;l=289 there is a bug in readELF as I commented above.

https://www.virustotal.com/gui/file/2a2513e8687993ed71cc48b09676abf18bb0e739f15473d36c50627b05036686 sha256 hashes are commonly used to refer to files on VT.

**Comment by dmitshur** [comment]
CC @bcmills, @rsc.

**Comment by ianlancetaylor** [comment]
It's pretty strange to have a PT_NOTE segment with a p_align field of 0, but I guess we should handle it.  I'll send a CL.

**Comment by stevemk14ebr** [comment]
I agree, I had to lookup if alignment of 0 was even valid. Apparently it is.
