### ISSUE TITLE
affected/package: os Receiving RTP media packets using UDP, resulting in disorder

### ISSUE THREAD

**Issue by jobo-zt** [golang/go#62092]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.7 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

###hat operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\GOPATH\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\GOPATH
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=D:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.20.7
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Windows\TEMP\go-build1979553829=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

Listen to a port through UDP to receive data, use ReadFromUDPto read data, and decode seq. Sending RTP data on the other end.
Confirm through packet capture that it did not occur during network transmission.

### What did you expect to see?

the RTP packet I receive has a sequence

### What did you see instead?
A small portion of the data packets obtained by calling ReadFromUDP are out of order

**Comment by seankhliao** [comment]
that's udp, you have no guarantee of ordering.
