### ISSUE TITLE
affected/package: 

### ISSUE THREAD

**Issue by noel-yap** [golang/go#62107]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.4 darwin/arm64

But bazel is using 1.18.9
</pre>

### Does this issue reproduce with the latest release?

I don't know — haven't tried.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/nyap/Library/Caches/go-build"
GOENV="/Users/nyap/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/nyap/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/nyap/go"
GOPRIVATE=""
GOPROXY="https://artifactory.ti-apps.aws.grail.com/artifactory/api/go/go,https://proxy.golang.org"
GOROOT="/Users/nyap/.gimme/versions/go1.18.4.darwin.arm64"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/nyap/.gimme/versions/go1.18.4.darwin.arm64/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.18.4"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="0"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/w7/l4dcw2ss1l98wqcxsx1pq03h0000gs/T/go-build547156787=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

Code:
```
package main

import (
	"fmt"

	"github.com/samber/lo"
	"github.com/volatiletech/null"
)

type Color int32

const (
	GRAY Color = 0
)

func main() {
	colors := NullJSONFromSlice([]Color{GRAY})

	fmt.Printf("%v\n", colors)
}

func NullJSONFromSlice[T any](ts []T) null.JSON {
	if ts == nil {
		return null.JSON{}
	}

	return NullJSONFrom(ts)
}

func NullJSONFrom[T any](arg T) null.JSON {
	var result null.JSON

	lo.Must0(result.Marshal(arg)) // can never error

	return result
}
```

When using `go build .`, code builds fine and executable runs as expected.

When using `bazel build .`, build errors with `internal compiler error: assigning ts (type []Color) to parameter arg (type go.shape.[]int32_0)`.

If the call to `lo.Must0` is changed to `_ =`, the error goes away.

`bazel build --sandbox_debug .` shows that it's running:
```
( cd /private/var/tmp/_bazel_nyap/29cd39e755dc2150ecde970986aff8d0/sandbox/darwin-sandbox/43/execroot/grail &&   exec env -     CGO_ENABLED=1     GOARCH=arm64     GOOS=darwin     GOPATH=''     GOROOT=external/go_sdk     GOROOT_FINAL=GOROOT     PATH=/usr/bin:external/llvm_toolchain/bin:/bin     TMPDIR=/var/folders/w7/l4dcw2ss1l98wqcxsx1pq03h0000gs/T/   /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_nyap/29cd39e755dc2150ecde970986aff8d0/sandbox/darwin-sandbox/43/sandbox.sb /var/tmp/_bazel_nyap/install/3c4a7a3c33b4c067b191587b066e5f1b/process-wrapper '--timeout=0' '--kill_delay=15' bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix darwin_arm64 -tags bazel,bazel -src go/src/grail.com/order-manager/tools/aoeu/aoeu.go -embedroot '' -embedroot bazel-out/darwin_arm64-opt/bin -embedlookupdir go/src/grail.com/order-manager/tools/aoeu -arc 'github.com/samber/lo=github.com/samber/lo=bazel-out/darwin_arm64-opt/bin/external/com_github_samber_lo/lo.x' -arc 'github.com/volatiletech/null=github.com/volatiletech/null=bazel-out/darwin_arm64-opt/bin/external/com_github_volatiletech_null/null.x' -importpath grail.com/order-manager/tools/aoeu -p main -package_list bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/go_sdk/packages.txt -o bazel-out/darwin_arm64-opt/bin/go/src/grail.com/order-manager/tools/aoeu/aoeu.a -x bazel-out/darwin_arm64-opt/bin/go/src/grail.com/order-manager/tools/aoeu/aoeu.x -nogo bazel-out/darwin_arm64-opt-exec-2B5CBBC6-ST-eda1e837b650/bin/bazel/go/nogo_actual_/nogo_actual -gcflags '' -asmflags '' )
```

### What did you expect to see?

Build succeeds with both `go build .` and `bazel build .`

### What did you see instead?

Build succeeds with `go build .` and fails with `bazel build .`

**Comment by randall77** [comment]
We no longer support 1.18. There were several issues with the generics implementation in 1.18 that have since been fixed. Please try a later release and see if your issue persists. If so, you can reopen.
