### ISSUE TITLE
runtime: fatal error: m changed unexpectedly in cgocallbackg on 386

### ISSUE THREAD

**Issue by mknyszek** [golang/go#62102]
```
#!watchflakes
post <- log ~ `fatal error: m changed unexpectedly in cgocallbackg`
```

2023-08-02 15:24 linux-386 go@0f1491de cmd/cgo/internal/test.TestCallbackStack ([log](https://build.golang.org/log/72df2a24cd0081cf42fdb311db45914fcb7ce687))
2023-08-07 06:58 linux-386 go@088f953f cmd/cgo/internal/test.TestCallbackStack ([log](https://build.golang.org/log/cdf8196402a79e8b2f6992b5931b8ec596d2af4b))
2023-08-14 19:23 linux-386 go@02b548e5 cmd/cgo/internal/test.TestCallbackStack ([log](https://build.golang.org/log/3b3da6c90e31eff119912c7f2b7c528881238477))

**Comment by prattmic** [comment]
@cherrymui this is happening quite consistently on linux-386. I fear that this is another issue with https://go.dev/cl/495855.

**Comment by cherrymui** [comment]
Yeah, probably related. I'll take a look.

**Comment by cherrymui** [comment]
Interestingly, this seems to happen more frequently with `-buildmode=pie`, which is the 5th run of `cmd/cgo/internal/test`, although not all of the failures above are from this. Running stress test on gomote it is also more likely to fail with `-buildmode=pie`.

**Comment by cherrymui** [comment]
`cgocallbackg1` calls `unlockOSThread` as seemingly the very last step, in a deferred call https://cs.opensource.google/go/go/+/master:src/runtime/cgocall.go;l=349 . Then in the caller `cgocallbackg` it immediately set `m.incgo` to true to prevent the scheduler moving it to another M. There is seemingly no preemption point before the two operations. However, on 386, in PIE buildmode, it does not use open coded defers https://cs.opensource.google/go/go/+/master:src/cmd/compile/internal/ssagen/ssa.go;l=403 , therefore `unlockOSThread` is called via `deferreturn`, and there is actually preemption point, e.g. `p.nextDefer` in `deferreturn` https://cs.opensource.google/go/go/+/master:src/runtime/panic.go;l=591 (on the next iteration after `unlockOSThread` is called), which is not nosplit. Therefore the G can be preempted and rescheduled to a different M.

**Comment by ianlancetaylor** [comment]
Ouch, nice catch.  I think I wrote that code (https://go.dev/cl/64070) before we had asynchronous preemption, and I assumed that no preemption was possible.

**Comment by cherrymui** [comment]
I think this is synchronous preemption (e.g. in function prologues). We don't yet preempt runtime code asynchronously (for now).

I'm working on a fix.

**Comment by ianlancetaylor** [comment]
Thanks.
