### ISSUE TITLE
time: now.Before(time.Unix(math.MaxInt64, 0)) should return true

### ISSUE THREAD

**Issue by gopherbot** [golang/go#6210]
by **tim.olsen@10gen.com**:

<pre>Before filing a bug, please check whether it has been fixed since the
latest release. Search the issue tracker and check that you're running the
latest version of Go:

Run &quot;go version&quot; and compare against
<a href="http://golang.org/doc/devel/release.html">http://golang.org/doc/devel/release.html</a>  If a newer version of Go exists,
install it and retry what you did to reproduce the problem.

Thanks.

What steps will reproduce the problem?
If possible, include a link to a program on play.golang.org.
1. run program at <a href="http://play.golang.org/p/cvez19tXfE">http://play.golang.org/p/cvez19tXfE</a>

What is the expected output?
&quot;Cool, not the end of the world yet&quot;

What do you see instead?
&quot;uh oh&quot;

Which compiler are you using (5g, 6g, 8g, gccgo)?
6g

Which operating system are you using?
darwin (Mac OS X 10.8.4

Which version are you using?  (run 'go version')
go version go1.1.2 darwin/amd64

Please provide any additional information below.
Subtracting 1 or 1000 from MaxInt64 does not change the behavior.  Dividing by 2 does
however suggesting time.Time cannot accommodate the last bit (before the sign) of int64
when converting from unix epoch time.</pre>

**Comment by bradfitz** [comment]
Fixed by documentation in f3fc8b02 and 526b5017 for #10906
