### ISSUE TITLE
第一财经【杏福娱乐的招商注册】MBA智库百科affected/package: 

### ISSUE THREAD

**Issue by h402201** [golang/go#62111]
【杏福娱乐代理注册网址yz3699.com 悦总QQ5566745】🔥I stuffed a shirt or two into my old carpet-bag, tucked it under my arm, and started for Cape Horn and the Pacific. Quitting the good city of old Manhatto, I duly arrived in New Bedford. It was a Saturday night in December. Much was I disappointed upon learning that the little packet for Nantucket had already sailed, and that no way of reaching that place would offer, till the following Monday

### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by dmitshur** [comment]
This doesn't seem to be a valid Go issue.
