### ISSUE TITLE
encoding/gob: panic decoding into local type, received remote type 

### ISSUE THREAD

**Issue by vkjon** [golang/go#62117]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.0 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/vscode/.cache/go-build'
GOENV='/home/vscode/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.0'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build318203347=/tmp/go-build -gno-record-gcc-switches'
</pre></details>

### What did you do?
Decode downstream gob into a local type.
- Gob encode: https://go.dev/play/p/-Br5PjBZTSF
- Gob decode: https://go.dev/play/p/BMmDBvThMJo

### What did you expect to see?
<pre>
gob: decoding into local type *[]*struct {}, received remote type 
</pre>

### What did you see instead?
<pre>
panic: runtime error: index out of range [64] with length 64 [recovered]
	panic: runtime error: index out of range [64] with length 64 [recovered]
	panic: runtime error: index out of range [64] with length 64

goroutine 1 [running]:
encoding/gob.catchError(0xc000108070)
	/usr/local/go-faketime/src/encoding/gob/error.go:38 +0x6d
panic({0x4b5c20?, 0xc00001a030?})
	/usr/local/go-faketime/src/runtime/panic.go:914 +0x21f
encoding/gob.catchError(0xc0001198c8)
	/usr/local/go-faketime/src/encoding/gob/error.go:38 +0x6d
panic({0x4b5c20?, 0xc00001a030?})
	/usr/local/go-faketime/src/runtime/panic.go:914 +0x21f
encoding/gob.(*Decoder).typeString(0xc000108000?, 0x4e4480?)
	/usr/local/go-faketime/src/encoding/gob/decode.go:1085 +0x1e9
encoding/gob.(*Decoder).compileSingle(0x1800000700?, 0x40, 0xc00001cdc0)
	/usr/local/go-faketime/src/encoding/gob/decode.go:1100 +0x365
encoding/gob.(*Decoder).compileDec(0xc000108000, 0x40, 0xc00001cdc0)
	/usr/local/go-faketime/src/encoding/gob/decode.go:1132 +0x257
encoding/gob.(*Decoder).getDecEnginePtr(0xc000108000, 0x4a48a0?, 0xc00001cdc0)
	/usr/local/go-faketime/src/encoding/gob/decode.go:1189 +0x12a
encoding/gob.(*Decoder).decodeValue(0xc000108000, 0x446e00?, {0x4a48a0?, 0xc000010258?, 0xc000016601?})
	/usr/local/go-faketime/src/encoding/gob/decode.go:1234 +0xfd
encoding/gob.(*Decoder).DecodeValue(0xc000108000, {0x4a48a0?, 0xc000010258?, 0x0?})
	/usr/local/go-faketime/src/encoding/gob/decoder.go:229 +0x196
encoding/gob.(*Decoder).Decode(0xc000108000, {0x4a48a0?, 0xc000010258?})
	/usr/local/go-faketime/src/encoding/gob/decoder.go:204 +0x125
main.main()
	/tmp/sandbox717720055/prog.go:14 +0xbb
</pre>

**Comment by panjf2000** [comment]
@gopherbot please consider this for backport to 1.21, this issue may have a wide impact.
