### ISSUE TITLE
math/big: Float is not big

### ISSUE THREAD

**Issue by willfaught** [golang/go#62127]
### What did you do?

https://pkg.go.dev/math/big#Float

### What did you expect to see?

>[Arbitrary-precision fixed-point decimal numbers](https://github.com/shopspring/decimal)

### What did you see instead?

>A nonzero finite Float represents a multi-precision floating point number

I almost shot myself in the foot with this one.

Please add a huge disclaimer in the Float doc that says it's not big:

>BEWARE! THIS IS NOT ARBITRARY PRECISION  LIKE INT AND RAT! A nonzero finite Float represents a multi-precision floating point number

**Comment by seankhliao** [comment]
the following paragraphs describe the levels of precision that Float provides,  screaming notice is not in the standard style and should not be necessary.
