### ISSUE TITLE
affected/package: strings

### ISSUE THREAD

**Issue by cybercent** [golang/go#62139]
### What version of Go are you using (`go version`)?

1.21

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

```
strings.Trim("0x0abcd", "0x")
```

### What did you expect to see?

```
"0abcd"
```

### What did you see instead?

```
abcd
```

**Comment by dmitshur** [comment]
[`strings.Trim`](https://pkg.go.dev/strings#Trim) is documented as:

> Trim returns a slice of the string s with all leading and trailing Unicode code points contained in cutset removed.

Trimming leading and trailing "0" and "x" from the string "0x0abcd" should result in "abcd", and it does so correctly. So this is working correctly.

`strings.TrimPrefix` results in "0abcd" so perhaps you were thinking of that.
