### ISSUE TITLE
encoding/csv: conflicting comments regarding column indexing

### ISSUE THREAD

**Issue by krmpotic** [golang/go#62147]
https://github.com/golang/go/blob/ce16086345435d85906de31ea4af486b69bae895/src/encoding/csv/reader.go#L64-L71

comments of `ParseError` struct and of its element `Column` are in conflict with each-other, regarding
columns being 1-indexed or 0-indexed

**Comment by seankhliao** [comment]
looks like it should be 1 indexed.

**Comment by ianlancetaylor** [comment]
Thanks.  Looks like we improved it in https://go.dev/cl/291290 for #44221 but didn't fully update the docs.  CC @rogpeppe
