### ISSUE TITLE
cmd/link: index out of range at cmd/link/internal/ld.decodetypeKind

### ISSUE THREAD

**Issue by johejo** [golang/go#62156]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.22-a9859a7df7 Fri Aug 18 23:45:44 2023 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

no, tip only

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/mitsuoheijo/.cache/go-build'
GOENV='/home/mitsuoheijo/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/mitsuoheijo/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/mitsuoheijo/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/home/mitsuoheijo/repos/github.com/golang/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/home/mitsuoheijo/repos/github.com/golang/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='devel go1.22-a9859a7df7 Fri Aug 18 23:45:44 2023 +0000'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/mitsuoheijo/repos/github.com/osrg/gobgp/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build811026688=/tmp/go-build -gno-record-gcc-switches'
</pre></details>

### What did you do?

```
git clone https://github.com/osrg/gobgp.git
cd gobgp/
git checkout v3.17.0
go build ./cmd/gobgpd
```

### What did you expect to see?

build succeeds

### What did you see instead?

```
# github.com/osrg/gobgp/v3/cmd/gobgpd
type:func([]github.com/osrg/gobgp/v3/pkg/packet/bgp.ExtendedCommunityInterface) []github.com/osrg/gobgp/v3/pkg/packet/bgp.ExtendedCommunityInterface: missing type
panic: runtime error: index out of range [23] with length 0

goroutine 1 [running]:
cmd/link/internal/ld.decodetypeKind(...)
        /home/mitsuoheijo/repos/github.com/golang/go/src/cmd/link/internal/ld/decodesym.go:42
cmd/link/internal/ld.(*dwctxt).newtype(0xc001ef6948, 0x7a245)
        /home/mitsuoheijo/repos/github.com/golang/go/src/cmd/link/internal/ld/dwarf.go:546 +0x228a
cmd/link/internal/ld.(*dwctxt).defgotype(0xc001ef6948, 0x7a245)
        /home/mitsuoheijo/repos/github.com/golang/go/src/cmd/link/internal/ld/dwarf.go:534 +0x119
cmd/link/internal/ld.(*dwctxt).importInfoSymbol(0xc001ef6948, 0x4a00e)
        /home/mitsuoheijo/repos/github.com/golang/go/src/cmd/link/internal/ld/dwarf.go:1143 +0x345
cmd/link/internal/ld.(*dwctxt).dwarfVisitFunction(0xc001ef6948, 0x6?, 0xc0000b7040)
        /home/mitsuoheijo/repos/github.com/golang/go/src/cmd/link/internal/ld/dwarf.go:1723 +0x41f
cmd/link/internal/ld.dwarfGenerateDebugInfo(0xc00011e200)
        /home/mitsuoheijo/repos/github.com/golang/go/src/cmd/link/internal/ld/dwarf.go:1882 +0x148e
cmd/link/internal/ld.Main(_, {0x20, 0x20, 0x1, 0x7, 0x10, 0x0, {0xc000012469, 0x1, 0x1}, ...})
        /home/mitsuoheijo/repos/github.com/golang/go/src/cmd/link/internal/ld/main.go:356 +0x1332
main.main()
        /home/mitsuoheijo/repos/github.com/golang/go/src/cmd/link/main.go:72 +0xdfb
```

If disabling DWARF with -ldflags='-w' the link succeeds.

**Comment by dmitshur** [comment]
Thanks for reporting.

CC @mdempsky.

**Comment by mdempsky** [comment]
Bisect identifies ca858a43f4e63275381e657a13ef7431cbe8c823.

**Comment by mdempsky** [comment]
Confirmed that reverting that CL fixes the gobgpd build.

I'm fine with reverting and then rolling forward once the failure case is understood.

**Comment by mdempsky** [comment]
The issue here is that DWARF generation can also produce references to runtime type descriptors, which need to be written out too. So that also needs to go into the work queue. Whee.

**Comment by mdempsky** [comment]
Minimal repro:

```
package a

type iface interface{ m() }

func F() {
	f := func(rt []iface) []iface {
		return append([]iface{}, rt...)
	}
	f(nil)
}
```

```
package main

import "test/a"

func main() {
	a.F()
}
```

**Comment by johejo** [comment]
Fixed in https://go-review.googlesource.com/c/go/+/522339
