### ISSUE TITLE
x/tools/gopls: gopls was broken with the latest tip version

### ISSUE THREAD

**Issue by YoshikiShibata** [golang/go#62163]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.0 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

go1.21.0 doesn't reproduce the problem, but the lastest tip version reproduces it

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/yoshikishibata/Library/Caches/go-build'
GOENV='/Users/yoshikishibata/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/yoshikishibata/gocode/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/yoshikishibata/gocode'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/Users/yoshikishibata/tools/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/Users/yoshikishibata/tools/go/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.21.0'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/fs/3c1rlryd2v3_z5m04g3lnd580000gn/T/go-build2516750516=/tmp/go-build -gno-record-gcc-switches -fno-common'
GOROOT/bin/go version: go version go1.21.0 darwin/arm64
GOROOT/bin/go tool compile -V: compile version go1.21.0
uname -v: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8103
ProductName:		macOS
ProductVersion:		13.4.1
ProductVersionExtra:	(c)
BuildVersion:		22F770820d
lldb --version: lldb-1403.0.17.67
Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
</pre></details>

### What did you do?

When I recompiled the latest tip version from the source code with src/all.bash and rebuilt gopls with the tip version, vim-go doesn't work with the gopls (for example, `:GoDef` command)

### What did you expect to see?

vim-go works with gopls

### What did you see instead?

vim-go deosn't work with gopls.

Using git bisect command, I found that the following commit produces the problem.

```
% git bisect bad                            
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[5fa4aac0cec637fd9415fb260e3fbc2975377e00] go/types, types2: add Sizes computation to match gc behavior
```

**Comment by dmitshur** [comment]
Can you elaborate on what you mean by "vim-go deosn't work with gopls."? In what way does it not work? If there's an error printed, what is its text? Or is there no error, just no functionality?

CC @cuonglm, @findleyr.

**Comment by cuonglm** [comment]
Also, do you build gopls latest version or master?

**Comment by YoshikiShibata** [comment]
I built it by go install command:

```
go install golang.org/x/tools/gopls@latest
```

**Comment by YoshikiShibata** [comment]
with :GoDef , the following messages were shown, but didn't jump to the definition.

```
vim-go: initializing gopls
vim-go: initialized gopls
vim-go: Finished loading packages.
```

**Comment by cuonglm** [comment]
> I built it by go install command:
> 
> 
> 
> ```
> 
> go install golang.org/x/tools/gopls@latest
> 
> ```

Then you probably need to use @master, to pull in the fix in gopls.

**Comment by YoshikiShibata** [comment]
I rebuilt gopls from it source and the problem didn't appear. Thanks!
