### ISSUE TITLE
affected/package: 

### ISSUE THREAD

**Issue by ShamimEnamul** [golang/go#62166]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.20.4

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/shamim/.cache/go-build"
GOENV="/home/shamim/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/shamim/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/shamim/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/shamim/go/go1.20.4"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/shamim/go/go1.20.4/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3407556493=/tmp/go-build -gno-record-gcc-switches"
</code> Output</summary><br><pre>

</pre></details>

### What did you do?

package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
	"os"
	"sync"
)

var wg sync.WaitGroup

func main() {
	wg.Add(2)
	ch := make(chan int) // bidirectional channel
	send(ch)
	receive(ch)
	wg.Wait()
}

// write only
func send(ch chan<- int) {
	wg.Done()
	val := ch // expecting compile time error here
	fmt.Println(val)
}

// read only
func receive(ch <-chan int) {
	wg.Done()
	//ch <- 10 //i am getting compile time error here which is expected
	val := ch
	fmt.Println(val)
}

### What did you expect to see?

I am expecting a compile time error as I want to restrict the channels based on read/write (unidirectional)

### What did you see instead?
Not getting any compile time error while trying to reading from write only channel.

**Comment by seankhliao** [comment]
that's not receiving from a channel.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by ShamimEnamul** [comment]
well, thanks for your response. 
val := <-ch // if ch is write only getting the expected compile time error
val := ch // not getting the compile time error what I am expecting. There should be a reason need to deep dive. Ignore for now.
