### ISSUE TITLE
proposal: `golang.org/x/exp/slices`: add `make` equivalent with pragmatic capacity selection

### ISSUE THREAD

**Issue by extemporalgenome** [golang/go#62168]
The `make` builtin provides exactly as much capacity as requested, but no more.

If I understand correctly, this will often be a wasted opportunity.
Consider: `make([]byte, 0, 1793)` or `make([]byte, 1793)`.

These are using one byte larger than fits in the 1792 byte [size class](https://go.dev/src/runtime/sizeclasses.go), or at least it uses the majority of a typical OS memory page while leaving the remainder of that page unusable.

Since slice capacity does not typically have semantic meaning, it would be helpful to allow a function with better awareness of runtime internals to fill wasted/unusable tail space.

I propose we add a `Make` function within `golang.org/x/exp/slices` to experiment with this concept. It's stated purpose would be to have the same behavior as `make`, except that it makes available as capacity the full size class that it is allocated within.

```
func Make[S ~[]E, E any](length, capacity int) S
```

Behavioral requirements:
1. `Make` will never allocate less capacity than `make` with equivalent arguments.
2. `Make` will never leave unused capacity within its size class.

**Comment by seankhliao** [comment]
This is already possible through `slices.Grow`.

**Comment by extemporalgenome** [comment]
Ah, that is true. Thanks!
