### ISSUE TITLE
x/tools/go/analysis/passes/nilness: wrong internal code comment // "x is nil, y is unknown"

### ISSUE THREAD

**Issue by CptGit** [golang/go#62160]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.21.0 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

"x is nil, y is unknown" -> "y is nil, x is unknown"at <https://cs.opensource.google/go/x/tools/+/refs/tags/v0.12.0:go/analysis/passes/nilness/nilness.go;l=164>

**Comment by siddharth-sable** [comment]
Hello @dmitshur , I was working on this change.

Do I need to change the comment on line [160](https://cs.opensource.google/go/x/tools/+/refs/tags/v0.12.0:go/analysis/passes/nilness/nilness.go;l=160) as well? Just changing on line [164](https://cs.opensource.google/go/x/tools/+/refs/tags/v0.12.0:go/analysis/passes/nilness/nilness.go;l=164) will contradict the conditions, please check.

Thank you

**Comment by dmitshur** [comment]
Thanks Siddharth, please feel free to mail a code change. See https://go.dev/doc/contribute for more information on the process.

**Comment by siddharth-sable** [comment]
Hello, @dmitshur, I mailed a code change. Please check. Thank you.

**Comment by snprajwal** [comment]
This seems to be fixed on the current master branch. Should this issue be closed?

**Comment by dmitshur** [comment]
Thanks for pointing that out.

Fixed by [CL 595895](https://go.dev/cl/595895).
