### ISSUE TITLE
proposal: affected/package: context add DetachValue(ctx Context, key any)Contex

### ISSUE THREAD

**Issue by bigobject** [golang/go#62178]
sence:
ctx = context.WithValue(ctx, key1, value1)
ctx =context.WithValue(ctx, key2, value2)
while the value2 is cached by sync.Pool, value1 will hold the memory meanwhile.
can we got a context.DetachValue API to delete key1 value1 from context.

**Comment by seankhliao** [comment]
given how contexts are trees, there's no feasible implementation for this
