### ISSUE TITLE
x/build: ios-arm64-corellium builders appear to be stuck

### ISSUE THREAD

**Issue by bcmills** [golang/go#62187]
https://farmer.golang.org/try?commit=c7a100e5 has been waiting on an `ios-arm64-corellium` SlowBot for ~66 hours so far.

From looking at https://farmer.golang.org/, it appears that all three builders got stuck after `make.bash` on or around 2023-08-1-6:
- [ios-arm64-corellium](https://github.com/golang/go/wiki/DashboardBuilders) rev [94d36fbc](https://go-review.googlesource.com/#/q/94d36fbc4acdbcff5d4d7ad3869f285294c4181c); [running](https://farmer.golang.org/temporarylogs?name=ios-arm64-corellium&rev=94d36fbc4acdbcff5d4d7ad3869f285294c4181c&st=0xc00181fc00); http://iPhone reverse peer iPhone/18.220.71.121:55403 for host type host-ios-arm64-corellium-ios, 141h9m1s ago
```
...
  2023-08-15T21:16:47Z finish_write_go_src_tar after 10.6s
  2023-08-15T21:16:47Z make_and_test 
  2023-08-15T21:16:47Z make src/make.bash
 +499936.5s (now)
```
- [ios-arm64-corellium](https://github.com/golang/go/wiki/DashboardBuilders) rev [60506f4d](https://go-review.googlesource.com/#/q/60506f4d7f912bff9af886ea1befb8aa9583d535); [running](https://farmer.golang.org/temporarylogs?name=ios-arm64-corellium&rev=60506f4d7f912bff9af886ea1befb8aa9583d535&st=0xc0018221c0); http://iPhone reverse peer iPhone/18.220.71.121:51147 for host type host-ios-arm64-corellium-ios, 141h9m1s ago
```
...
  2023-08-15T23:31:55Z finish_write_go_src_tar after 9.35s
  2023-08-15T23:31:55Z make_and_test 
  2023-08-15T23:31:55Z make src/make.bash
 +491828.3s (now)
```
- [ios-arm64-corellium](https://github.com/golang/go/wiki/DashboardBuilders) rev [850b6ce3](https://go-review.googlesource.com/#/q/850b6ce33ced3d20d036cb41317f783469f3ea86); [running](https://farmer.golang.org/temporarylogs?name=ios-arm64-corellium&rev=850b6ce33ced3d20d036cb41317f783469f3ea86&st=0xc005179a40); http://iPhone reverse peer iPhone/3.12.63.38:53729 for host type host-ios-arm64-corellium-ios, 134h1m6s ago
```
...
  2023-08-16T03:19:47Z finish_write_go_src_tar after 10.6s
  2023-08-16T03:19:47Z make_and_test 
  2023-08-16T03:19:47Z make src/make.bash
 +478156.2s (now)
```

(attn @changkun @cagedmantis)

**Comment by changkun** [comment]
rebooted all builders, looks like an old issue is reoccurring

**Comment by bcmills** [comment]
Looks like they're stuck again: https://farmer.golang.org/ shows them “working for” longer than 24h each.

**Comment by changkun** [comment]
Rebooted.

**Comment by cherrymui** [comment]
Seems it is stuck again.
```
ios-arm64-corellium rev b4c889b5; running; http://iPhone reverse peer iPhone/18.220.71.121:65358 for host type host-ios-arm64-corellium-ios, 126h57m50s ago
...
  2023-09-01T15:15:15Z finish_write_go_src_tar after 8.99s
  2023-09-01T15:15:15Z make_and_test 
  2023-09-01T15:15:15Z make src/make.bash
 +456962.4s (now)
```

@changkun is it possible to log into the builder and see which process is stuck? If we know the stuck process, maybe send a SIGQUIT signal so it can dump a stack trace.
Thanks.

**Comment by heschi** [comment]
Seem to be unstuck at the moment. Closing until next time.
