### ISSUE TITLE
runtime: `fatal error: found bad pointer in Go heap` on `darwin-amd64-nocgo`

### ISSUE THREAD

**Issue by bcmills** [golang/go#62186]
```
#!watchflakes
post <- goos == "darwin" && goarch == "amd64" && log ~ `fatal error: found bad pointer in Go heap`
```

Pulled out from https://github.com/golang/go/issues/55167#issuecomment-1684924675.

Note that the failure in that log is on `release-branch.go1.20` (see also #59483).

**Comment by mknyszek** [comment]
Turns out this is already captured by https://github.com/golang/go/issues/60449. I'm starting to think all of these corruption issues boil down to the same problem, and now we're building a class of failures. Closing this for now as a duplicate.
