### ISSUE TITLE
x/pkgsite: Github username (in Capital Case variant) causes package not found on pkg.go.dev

### ISSUE THREAD

**Issue by Sven-Seyfert** [golang/go#62188]
### What is the URL of the page with the issue?
- https://pkg.go.dev/github.com/sven-seyfert/gomisc
- https://pkg.go.dev/github.com/Sven-Seyfert/gomisc (Capital Case username)
- https://pkg.go.dev/github.com/sven-seyfert/gomisc/singleinstance
- https://pkg.go.dev/github.com/Sven-Seyfert/gomisc/singleinstance (Capital Case username)

### What is your user agent?
- Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0
- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36

### Screenshot

![grafik](https://github.com/golang/go/assets/29656921/4e3688f1-23de-469e-800d-04bc986da9d8)

![grafik](https://github.com/golang/go/assets/29656921/4a668d93-d26a-407d-b12c-fde4cb6fb90f)

### What did you do?
- I created my own (first tryout) go package and published it on GitHub.
  - https://github.com/Sven-Seyfert/gomisc
- I added git tags (v0.4.0) and used `git push origin --tags` (which shows up on my GitHub page too).
- I have a license (MIT) in the repository.
- I used the proxy command `GOPROXY=proxy.golang.org go list -m github.com/sven-seyfert/gomisc@v0.4.0` to address my package for pkg.go.dev.
- I wait more then a day for my package to be visible on pkg.go.dev.

### What did you expect to see?
My package `singleinstance` of `github.com/sven-seyfert/gomisc` should be available on pkg.go.dev.

### What did you see instead?
Like in the screenshot: *"... could not be found."*

### What did I recognized?
My GitHub username is `Sven-Seyfert` as Capital Case. When I tried the different URLs in pkg.go.dev and on proxy.golang.org (https://proxy.golang.org/github.com/sven-seyfert/gomisc/@v/v0.4.0.info) I see no issue when I use the lower case variant of `sven-seyfert`. But when I use the Capital Case variant for the same request I get *"bad request: invalid escaped module path "github.com/Sven-Seyfert/gomisc""*.

Can this be the reason for my problem?

---

Thanks for your help and support, I really appreciate it 🤝 .

**Comment by bcmills** [comment]
> when I use the Capital Case variant for the same request I get "bad request: invalid escaped module path "github.com/Sven-Seyfert/gomisc"".

No, you just have to use an escaped URL:
- https://proxy.golang.org/github.com/!sven-!seyfert/gomisc/@latest
- https://proxy.golang.org/github.com/!sven-!seyfert/gomisc/@v/list 

The proxy definitely has data for the lower-case version as well:
- https://proxy.golang.org/github.com/sven-seyfert/gomisc/@latest
- https://proxy.golang.org/github.com/sven-seyfert/gomisc/@v/list

**Comment by findleyr** [comment]
I'm pretty sure this is https://go.dev/issue/62031. I'll confirm after the fix is deployed.

**Comment by findleyr** [comment]
Ok, I've figured it all out...

- #62031 was originally preventing any fetching from working, but even after fixing that I was having trouble fetching this module manually, because...
- v0.1.0 lacks any go files
- v0.2.0 was named github.com/Sven-Seyfert/gomisc in the go.mod file (and so must be fetched as such, with the exact casing)
- v0.3.0 was _also_ named github.com/Sven-Seyfert/gomisc, according to the proxy, but the tag in github says github.com/sven-seyfert/gomisc in the go.mod file -- did you change the tag?
- v0.4.0 is named github.com/sven-seyfert/gomisc

So I've fetch the three valid versions (v0.2.0-v0.4.0). v0.2.0 and v0.3.0 are available with capital 'S': https://pkg.go.dev/github.com/Sven-Seyfert/gomisc?tab=versions. v0.4.0 is available with lower-case 's': https://pkg.go.dev/github.com/sven-seyfert/gomisc?tab=versions

**Comment by Sven-Seyfert** [comment]
Thank you very much @findleyr for your investigation and your effort, I appreciate it 🤝 .
You're right with all your findings. I changed the tag v0.3.0. I really just need v0.4.0 and the future upcoming versions.
Since it's my first step into own packages and working with GO, it's not a big deal. Anyway, I really grateful.

One question @findleyr : How can I get rid of the versions v0.2.0 and v0.3.0? I really don't need them.

Best regards
Sven
