### ISSUE TITLE
x/telemetry: `TestCounter` fails if the current date does not match the UTC date

### ISSUE THREAD

**Issue by bcmills** [golang/go#62192]
```
#!watchflakes
post <- pkg == "golang.org/x/telemetry/internal/counter" && test == "TestRotate" && `us = .*, want .*`
```

https://build.golang.org/log/f9adf22ae18f3c790952f2f3efe33e81cdaf4329:
```
--- FAIL: TestRotate (0.00s)
    counter_test.go:383: GOOS linux GOARCH amd64
    counter_test.go:410: us = 2023-08-27 00:00:00 +0000 UTC, want 2023-08-28 00:00:00 +0000 UTC
    counter_test.go:410: us = 2023-08-27 00:00:00 +0000 UTC, want 2023-08-28 00:00:00 +0000 UTC
FAIL
FAIL	golang.org/x/telemetry/internal/counter	0.106s
```

The test was added in https://go.dev/cl/499920, with the comment:
```go
		// we expect today's date?
		if us != now {
			t.Errorf("us = %v, want %v", us, now)
		}
```

I think there are two problems in the test:
1. It calls `time.Date(year, month, day, 0, 0, 0, 0, time.UTC)` with arguments derived from `time.Now().Date()` (without an explicit time zone). It should either convert `time.Now()` to `time.UTC` before extracting the date, or construct `now` in the local time zone instead of UTC.
2. If the test run happens to cross midnight (as may be the case on CI builders), I suspect that the date could have changed after the call to `time.Now()`.

This test was added in https://go.dev/cl/499920 (attn @pjweinb, @hyangah, @jamalc).

**Comment by findleyr** [comment]
I believe @hyangah's in-flight refactoring of the tests is close to fixing this (we need to close over a fixed date).
