### ISSUE TITLE
x/tools/gopls: crashes when built with Go at tip due to go/types.Sizes change

### ISSUE THREAD

**Issue by babinin** [golang/go#62191]
gopls version: v0.13.2 (devel go1.22-d63652b7c6 Thu Aug 17 16:48:35 2023  0000)
gopls flags: 
update flags: proxy
extension version: 2023.8.1617
go version: devel 1.22-d63652b7c6
environment: Visual Studio Code - Insiders darwin
initialization error: undefined
issue timestamp: Sat, 19 Aug 2023 11:37:36 GMT
restart history:
Sat, 19 Aug 2023 11:37:20 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x102c32ee8]

goroutine 1490 [running]:
golang.org/x/tools/gopls/internal/lsp/cache.localPackageKey({{0x14000508cba, 0x6}, {0x14000508cba, 0x6}, {0x14000509270, 0x6}, {0x14000c86540, 0x1, 0x1}, {0x1037719a0, ...}, ...})
	  check.go:1402  0x528
golang.org/x/tools/gopls/internal/lsp/cache.(*packageHandleBuilder).buildPackageHandle(0x14001b1e810, {0x10319a900, 0x14001b32d70}, 0x140003a3360)
	  check.go:1090  0x234
golang.org/x/tools/gopls/internal/lsp/cache.(*snapshot).getPackageHandles.func2.1()
	  check.go:891  0xb0
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:75  0x5c
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1456
	  errgroup.go:72  0x98
[Error - 14:37:21] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
This is fixed in gopls@tip.
