### ISSUE TITLE
x/pkgsite: Service Unavailable

### ISSUE THREAD

**Issue by sinux-l5d** [golang/go#62210]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev
 
### What is your user agent?
 
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
 
### Screenshot
 
![image](https://github.com/golang/go/assets/22861912/3c4bcc57-41df-4ce6-a9d9-42ae7e7c5852)
and
![image](https://github.com/golang/go/assets/22861912/ce4be68a-8c21-4c5b-976f-a822eccdf462)
 
### What did you do?
 
Just access the documentation
 
### What did you expect to see?
 
 The documentation website
 
### What did you see instead?

Service Unavailable, title 500 Server Error

**Comment by sinux-l5d** [comment]
Closing as it's back, after 5 min downtime.

**Comment by findleyr** [comment]
Yes, this was a bad rollout. We were paged, and rolled back. Should be fixed now.

Thanks very much for the prompt issue!
