### ISSUE TITLE
x/build: darwin-amd64-longtest builds are slow

### ISSUE THREAD

**Issue by cagedmantis** [golang/go#62215]
According to https://farmer.golang.org there are three longtest runs that are running. They've been running for the lifetime of the coordinator. The builds are progressing very slowly.

[darwin-amd64-longtest](https://github.com/golang/go/wiki/DashboardBuilders) rev [01cad815](https://go-review.googlesource.com/#/q/01cad815a1c3c48d54b3cbbfc9f599f5f91918fe); [running](https://farmer.golang.org/temporarylogs?name=darwin-amd64-longtest&rev=01cad815a1c3c48d54b3cbbfc9f599f5f91918fe&st=0xc00127d340); http://Gophers-iMac-Pro-2.local reverse peer Gophers-iMac-Pro-2.local/18.217.145.210:34880 for host type host-darwin-amd64-13-aws, 20h27m35s ago
```
...
  2023-08-22T16:48:07Z still_waiting_on_test runtime:mayMoreStackPreempt
  2023-08-22T16:48:37Z still_waiting_on_test runtime:mayMoreStackPreempt
  2023-08-22T16:49:07Z still_waiting_on_test runtime:mayMoreStackPreempt
  +14.6s (now)
```

[darwin-amd64-longtest](https://github.com/golang/go/wiki/DashboardBuilders) rev [1081f8c0](https://go-review.googlesource.com/#/q/1081f8c05807728738e1e6bf9097a41796fe5a05); [running](https://farmer.golang.org/temporarylogs?name=darwin-amd64-longtest&rev=1081f8c05807728738e1e6bf9097a41796fe5a05&st=0xc0394c7500); http://Gophers-iMac-Pro.local reverse peer Gophers-iMac-Pro.local/18.217.145.210:36186 for host type host-darwin-amd64-13-aws, 20h24m20s ago
```
...
  2023-08-22T16:49:17Z still_waiting_on_test test:1_10
  2023-08-22T16:49:21Z finish_run_test:test:1_10 after 33.3s; Gophers-iMac-Pro.local
  2023-08-22T16:49:21Z run_test:test:2_10 Gophers-iMac-Pro.local
   +0.6s (now)
```

[darwin-amd64-longtest](https://github.com/golang/go/wiki/DashboardBuilders) rev [9e9556d3](https://go-review.googlesource.com/#/q/9e9556d328c53ed0a4d8b36feee949885d648ba8); [running](https://farmer.golang.org/temporarylogs?name=darwin-amd64-longtest&rev=9e9556d328c53ed0a4d8b36feee949885d648ba8&st=0xc009729340); http://Gophers-iMac-Pro-2.local reverse peer Gophers-iMac-Pro-2.local/18.217.218.177:35877 for host type host-darwin-amd64-13-aws, 20h24m20s ago
```
...
  2023-08-22T16:48:15Z still_waiting_on_test runtime:mayMoreStackPreempt
  2023-08-22T16:48:45Z still_waiting_on_test runtime:mayMoreStackPreempt
  2023-08-22T16:49:15Z still_waiting_on_test runtime:mayMoreStackPreempt
   +6.5s (now)
```
cc @golang/release @golang/darwin

**Comment by dmitshur** [comment]
Revision 1081f8c0 has completed by now: https://build.golang.org/log/b6794b36aae821c21ac4dd69b38f795c412fabe0.

The other two are still running, but spent most of the 20 hours waiting for a builder to free up so they could be scheduled:

```
Events:
  2023-08-21T20:21:46Z get_buildlet 
  2023-08-22T15:00:57Z finish_get_buildlet after 18h39m10.7s
```

```
Events:
  2023-08-21T20:25:01Z get_buildlet 
  2023-08-22T14:59:31Z finish_get_buildlet after 18h34m29.7s
```

**Comment by bcmills** [comment]
See previously:
- #59634
- #60919

**Comment by bcmills** [comment]
> The other two are still running, but spent most of the 20 hours waiting for a builder to free up so they could be scheduled

Could those have been blocked behind SlowBot runs, maybe?

**Comment by cagedmantis** [comment]
As @dmitshur pointed out, these were a product of a large backlog of builds. The builds themselves completed in an acceptable amount to time. Closing as working as intended.
