### ISSUE TITLE
x/build: os.TestUserConfigDir failing on freebsd-arm-paulzhol

### ISSUE THREAD

**Issue by bcmills** [golang/go#62223]
For https://github.com/golang/go/issues/57638, https://go.dev/cl/520262 added tests for a couple of previously-untested functions in the os package.

`TestUserConfigDir` is currently failing on the `freebsd-arm-paulzhol` builder with `EROFS`:
https://build.golang.org/log/b036bd49870c10c9b4ec9806283065b48eb5e04d

I see from the log that that builder has an explicit entry in its environment for `XDG_CACHE_HOME`. I think the builder could be fixed by also setting `XDG_CONFIG_HOME` in the builder's environment.

(attn @paulzhol)

**Comment by paulzhol** [comment]
I've set `XDG_DATA_HOME=/tmp/home_data XDG_CONFIG_HOME=/tmp/home_config` in addition to `XDG_CACHE_HOME=/tmp/cache`. Lets see how it goes.

**Comment by bcmills** [comment]
The most recent test run is still in progress, but so far it has made it past the `os` package, so this appears to be fixed. Thanks!
