### ISSUE TITLE
x/website: replace incorrect links to pkg.dev.go with pkg.go.dev

### ISSUE THREAD

**Issue by alurm** [golang/go#62225]
Hi.

I was reading a blog post about structured logging (https://go.dev/blog/slog) and found a typo: pkg.dev.go is written instead of pkg.go.dev.

Sentence: `The best place to learn about all of slog is the [package documentation](https://pkg.dev.go/log/slog).`

Notice `pkg.dev.go`. I think it should be `pkg.go.dev`.

After git grepping for `'dev\.go'` in the repository I found one more post where this exact problem happens: https://go.dev/doc/articles/go_command.

Sentence part: `and thus the import path of the [glog](https://pkg.dev.go/github.com/golang/glog) package is "github.com/golang/glog".`

Likewise, pkg.dev.go should be replaced with pkg.go.dev, which is correct.

Patch generated with `git diff`:

```
diff --git a/_content/blog/slog.md b/_content/blog/slog.md
index b0d8bbfc..ea491c6c 100644
--- a/_content/blog/slog.md
+++ b/_content/blog/slog.md
@@ -150,7 +150,7 @@ There is a lot more to `slog`:
   among other things.
 
 The best place to learn about all of `slog` is the [package
-documentation](https://pkg.dev.go/log/slog).
+documentation](https://pkg.go.dev/log/slog).
 
 
 ## Performance
diff --git a/_content/doc/articles/go_command.html b/_content/doc/articles/go_command.html
index df689537..3a19377d 100644
--- a/_content/doc/articles/go_command.html
+++ b/_content/doc/articles/go_command.html
@@ -87,7 +87,7 @@ git clone https://github.com/golang/glog
 </pre>
 
 and thus the import path of the
-<a href="https://pkg.dev.go/github.com/golang/glog">glog</a>
+<a href="https://pkg.go.dev/github.com/golang/glog">glog</a>
 package is "<code>github.com/golang/glog</code>".</p>
 
 <p>These paths are on the long side, but in exchange we get an
```

**Comment by ianlancetaylor** [comment]
Thanks, sent https://go.dev/cl/522075 to fix this.

**Comment by alurm** [comment]
@ianlancetaylor awesome, thanks!

Although I don't see change to _content/doc/articles/go_command.html mentioned in the change list (it needs the same one line fix, as I said in the comment above).

Perhaps, it should be changed as well, seems very much of the same mistake to me. Or should I create a new issue?
