### ISSUE TITLE
runtime: poller should be used for file system operations

### ISSUE THREAD

**Issue by lexprfuncall** [golang/go#6222]
<pre>Presently, the runtime blocks an operating system thread when performing a file system
operation such as a file read or write.  However, the same interfaces used by the poller
to poll socket file descriptors can be used for file system file descriptors.

In addition to limiting the number of threads in the runtime, there are other potential
resource usage and running time benefits.  An experiement should be conducted across the
various supported platforms to understand whether there is an opportunity for a
performance improvement.  The answer might depend on the quality of the underlying
asynchronous I/O implementation and its interaction with the kernel event notification
system.</pre>

**Comment by jaracil** [comment]
There is a nice implementation of Poller:
https://github.com/npat-efault/poller

It gives safe Close() in one goroutine while read/write operations are blocked in other goroutines and all read/write operations are released after close().
It also gives useful methods like  SetDeadline, SetReadDeadline, SetWriteDeadline.

This package only implements linux epoll syscall. I think it could use golang runtime poller to make it multi platform.

Thanks.

**Comment by ianlancetaylor** [comment]
I think that on tip this one is now done as much as it can be.  Closing.

**Comment by t3rm1n4l** [comment]
Is there any possibility for future runtime poller support for file I/O ?

**Comment by davecheney** [comment]
@t3rm1n4l 

Please don't comment on closed issues. Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.

> Is there any possibility for future runtime poller support for file I/O ?

The limitation is the operating systems Go supports do not have good APIs for async file i/o. This isn't a complete answer, I know there is some kind of async i/o on linux, windows probably has something related to overlapping file operations or i/o completion ports (or something)--i've no idea what it would take for osx, freebsd, et al. 

The take away is it might be possible to support async file io for a subset of platforms, but it's nowhere near as straight forward as the support for async network io, and it would/will take an expert in each platform to implement it.
