### ISSUE TITLE
cmd/go: 'go test -o' may fail with `ETXTBSY` when running the compiled test

### ISSUE THREAD

**Issue by bcmills** [golang/go#62221]
```
#!watchflakes
post <- pkg ~ `^cmd/go` && `text file busy` && `go test .* -o\b`
```
(Pulled out from https://github.com/golang/go/issues/58019#issuecomment-1665963517.)

When `go test` is run with the `-o` flag but not the `-c` flag, it writes out the requested binary and then `exec`s that binary.
Occasionally that races with calling `exec` on another test in the same run, which can cause the file descriptor to be (briefly) held open by a child process, leading to the failure mode described in #22315.

This can occur any time `go test -o` is used to build and run multiple tests.

I can think of three possible fixes:
1. Acquire a read lock on `syscall.ForkLock` when copying test binaries, blocking an `exec` anywhere else in the command from proceeding concurrently.
2. Start a subprocess (probably another instance of `cmd/go` with some secret handshake?) to copy the file, preventing other subprocesses from ever seeing the file descriptor.
3. Retry `ETXTBSY` errors when running the test binary.

**Comment by bcmills** [comment]
Reproduced using:
```
$ OUT=$(mktemp -d)
$ while go test -o $OUT -run='^$' -count=1 archive/... compress/... crypto/... encoding/... hash/... image/... testing/... text/... unicode/...; do rm $OUT/*.test ; done
```

It failed after a couple dozen iterations.

**Comment by ianlancetaylor** [comment]
My vote is to retry `ETXTBSY` errors.  Copying a file is not an instantaneous operation, so holding `syscall.ForkLock` seems too heavyweight.  And retrying `ETXTBSY` seems simpler than starting a new process just to copy a file.

**Comment by bcmills** [comment]
I agree with that assessment.

**Comment by bcmills** [comment]
@gopherbot, please backport to Go 1.21. This Go command bug causes occasional test failures in `TestScript/test_compile_multi_pkg`, which was added in Go 1.21, and the fix is small and straightforward.
