### ISSUE TITLE
У меня проблема с импортом fine.io

### ISSUE THREAD

**Issue by MartinIden3353** [golang/go#62237]
загрузил fine так - C:\Users\Admin\Documents\GoProject> go install fyne.io/fyne/v2@latest
дождался окончание загрузки, перезапустил Visual Studio, однако импорт не работает! показывает - could not import fyne.io/fyne/v2/app (cannot find package "fyne.io/fyne/v2/app" in GOROOT or GOPATH)compiler[BrokenImport](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#BrokenImport)

помогите пожалуйста!

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
