### ISSUE TITLE
net/http: RFC 6874 cleanup not done on NewRequest* methods 

### ISSUE THREAD

**Issue by RemiBou** [golang/go#62235]
### What version of Go are you using (`go version`)?

go 1.21

### Does this issue reproduce with the latest release?

yes

### What did you do?

```golang
func main() {
	_, err := http.NewRequest("GET", "http://[::1%lo0]:8080", nil)
	if err != nil {
		fmt.Printf("Error: %v", err)
	} else {
		fmt.Printf("OK")
	}
}
```

https://go.dev/play/p/oVgxggDoViJ

### What did you expect to see?
"OK" displayed and request created with hostname "[::1]"  like it would have been with
This was implemented in https://github.com/golang/go/issues/9544 by @mikioh 

### What did you see instead?

```
Error: parse "http://[::1%lo0]:8080": invalid URL escape "%lo"
```

**Comment by bcmills** [comment]
(CC @neild)

@RemiBou, do you want to send a CL to implement this?
(I recommend the Gerrit-based workflow from https://go.dev/doc/contribute.)

**Comment by neild** [comment]
The `%` needs to be percent-encoded, so the URL should be `http://[::1%25lo0]:8080`.

RFC 6874:

> According to URI syntax [[RFC3986](https://www.rfc-editor.org/rfc/rfc3986)], "%" is always treated as
   an escape character in a URI, so, according to the established URI
   syntax [[RFC3986](https://www.rfc-editor.org/rfc/rfc3986)] any occurrences of literal "%" symbols in a URI MUST
   be percent-encoded and represented in the form "%25".  Thus, the
   scoped address fe80::a%en1 would appear in a URI as
   http://[fe80::a%25en1].
