### ISSUE TITLE
proposal: x/sys: add riscv vector extension detection

### ISSUE THREAD

**Issue by mengzhuo** [golang/go#62238]
Since Linux 6.5 will be released with riscv vector support, I proposal adding a vector feature detection for it.
Linux source code: https://github.com/torvalds/linux/blob/v6.5-rc7/arch/riscv/include/uapi/asm/hwcap.h

```
#define COMPAT_HWCAP_ISA_V	(1 << ('V' - 'A'))
```

The API change in x/sys is simple by adding:

```
var RISCV64 struct {
	HasV bool // Vector extension
}
```
Other Linux architecture had already supported aux reading, nothing changed in `*_linux`.

FreeBSD has not support riscv as Tier 1 platform, nothing changed in freebsd/riscv64.

p.s. In [CL 508676](https://go-review.googlesource.com/c/sys/+/508676), Mills wants a proposal for riscv64 vector extension detection.

Related #61416

**Comment by bcmills** [comment]
(attn @golang/riscv64)

**Comment by mengzhuo** [comment]
Closed, as HasV had been abondon.
