### ISSUE TITLE
x/crypto/ssh: does not support ssh-agent forwarding

### ISSUE THREAD

**Issue by gopherbot** [golang/go#6223]
by **jamwt@dropbox.com**:

<pre>crypto/ssh does not have support for ssh-agent forwarding.

This is useful for building out things like deployment systems where you're tunneling
through some bastion server into production.  The packer project could benefit from this
(in fact, that's why we @ dropbox tackled this issue).</pre>

**Comment by hanwen** [comment]
agent forwarding is described here: 

  https://www.vandyke.com/technology/draft-ietf-secsh-agent.txt

basically, you do channel.SendRequest("auth-agent-req", true) before starting the session, and then route incoming NewChannel requests of type "auth-agent" to a connection to the SSH_AUTH_SOCK unix domain socket.

Most of the legwork has been done here for you:

 https://godoc.org/golang.org/x/crypto/ssh/agent#RequestAgentForwarding
 https://godoc.org/golang.org/x/crypto/ssh/agent#ForwardToAgent
 https://godoc.org/golang.org/x/crypto/ssh/agent#ForwardToRemote
