### ISSUE TITLE
cmd/compile: special-case MethodByName(string literal) to keep the DCE enabled.

### ISSUE THREAD

**Issue by dominiquelefevre** [golang/go#62257]
Normally, a call to `MethodByName()` disables the DCE because the linker assumes that any method can be accessed this way. This pessimises the code generation for `k8s.io/apimachinery` which needs `MethodByName()` to verify whether or not a struct implements `DeepCopyInto()`. It cannot cast a struct to `interface { DeepCopyInto() Foo }` because the return type may vary. Instead, it does the following:
```
      if m := reflect.ValueOf(obj).MethodByName("DeepCopyInto"); ... {
```
In this case there is no need to disable the DCE altogether. It suffices to add a relocation to keep methods named `DeepCopyInto()`.

**Comment by thanm** [comment]
Thanks for sending this.  I touched up the reviewer set for your CLs and ran the trybots.
