### ISSUE TITLE
x/pkgsite: package removal request for https://pkg.go.dev/github.com/ovotech/terraform-testing@v1.1.0

### ISSUE THREAD

**Issue by richardday-ovo** [golang/go#62262]
### What is the path of the package that you would like to have removed?
https://pkg.go.dev/github.com/ovotech/terraform-testing@v0.3.0
https://pkg.go.dev/github.com/ovotech/terraform-testing@v1.0.0

### Are you the owner of this package?
Yes

### What is the reason that you could not retract this package instead?
I have retracted v0.3.0 and 1.0.0 however i need the documentation hidden for these particular versions as well. Is that something you can do for me please?

**Comment by seankhliao** [comment]
we cannot hide specific versions, only entire modules.
