### ISSUE TITLE
log/slog: Package doc mistakes / inconsistencies

### ISSUE THREAD

**Issue by icza** [golang/go#62286]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.0 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?

Visited the package doc of `log/slog` package: https://pkg.go.dev/log/slog

### What did you expect to see?

I found 3 possible mistakes in the package doc:

1. In [Attrs and Values](https://pkg.go.dev/log/slog#hdr-Attrs_and_Values) section:

> The call
> 
>     logger.LogAttrs(ctx, slog.LevelInfo, "hello", slog.Int("count", 3))
> is the most efficient way to achieve the same output as
> 
>     slog.Info("hello", "count", 3)

The last line should be:

    logger.InfoContext(ctx, "hello", "count", 3)

2. In the [Wrapping output methods](https://pkg.go.dev/log/slog#hdr-Wrapping_output_methods) section:

> For instance, if you define this function in file mylog.go:
> 
>     func Infof(format string, args ...any) {
>         slog.Default().Info(fmt.Sprintf(format, args...))
>     }
> and you call it like this in main.go:
> 
>     Infof(slog.Default(), "hello, %s", "world")

If the call to `Infof()` passes a logger, the signature should contain it and the body should use it, e.g.:

     func Infof(logger *slog.Logger, format string, args ...any) {
         logger.Info(fmt.Sprintf(format, args...))
     }

3. I would also like to note that the rendered package doc contains the text `[HandlerOptions.Level]` at multiple places, without being rendered as link. There are other examples too, e.g. `[HandlerOptions.ReplaceAttr]`.

**Comment by bcmills** [comment]
(attn @jba)

**Comment by seankhliao** [comment]
3 would be this issue: #61394
