### ISSUE TITLE
x/pkgsite: trouble finding latest version for github.com/apache/arrow/go

### ISSUE THREAD

**Issue by tschaub** [golang/go#62287]
### What is the URL of the page with the issue?
 
 * https://pkg.go.dev/github.com/apache/arrow/go
 * https://pkg.go.dev/github.com/apache/arrow/go/v12
 * https://pkg.go.dev/github.com/apache/arrow/go/v13
 
### What is your user agent?
 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
 
### Screenshot

![image](https://github.com/golang/go/assets/41094/3e2f1347-fb08-4de8-8f66-ffec080325d5) 
 
### What did you do?
 
I searched for "apache/arrow" (https://pkg.go.dev/search?q=apache%2Farrow) and found links to [an unstable version](https://pkg.go.dev/github.com/apache/arrow/go/arrow/array) of the package and [a version of the package](https://pkg.go.dev/github.com/apache/arrow/go/v12/arrow) that is shown to be the latest but appears not to be.
 
### What did you expect to see?
 
I was hoping to find a link to the latest tagged version (https://pkg.go.dev/github.com/apache/arrow/go/v13).  It looks like [go/v13.0.0](https://github.com/apache/arrow/releases/tag/go%2Fv13.0.0) was tagged Aug 17, 2023.
 
### What did you see instead?

On [the unstable version](https://pkg.go.dev/github.com/apache/arrow/go) of the module, I saw the "latest" badge and misinterpreted that to mean this was the latest stable version (but perhaps it means the latest unstable).

I found the [v12 module](https://pkg.go.dev/github.com/apache/arrow/go/v12) marked as "latest" and "stable" and was surprised to see the [v13 module](https://pkg.go.dev/github.com/apache/arrow/go/v13) say "The highest tagged major version is v12."

I imagine this could be an issue with the release process for [the Apache Arrow project](https://github.com/apache/arrow/tree/main/go).  Or maybe it is has to do with the way they name their tags or the way the module is named.

My hope in opening this ticket is that I could get enough information on how the pkg.go.dev site works to submit a pull request or open an issue suggesting a change to the Arrow project.  In cases like this where the module name changes with every major tagged release, is there a pkg.go.dev URL that could be used (e.g. in a readme.md) that would lead people to the most recent tagged release?

The [`readme.md`](https://github.com/apache/arrow/blob/go/v13.0.0/go/README.md?plain=1#L23) for the Arrow project links to `https://godoc.org/github.com/apache/arrow/go/arrow`.  If possible, I would like to submit a pull request to that project that would link to docs for the latest tagged version on the pkg.go.dev site instead.

**Comment by bcmills** [comment]
It looks like `v13.0.0` is present in the proxy, at least:
https://proxy.golang.org/cached-only/github.com/apache/arrow/go/v13/@v/list

**Comment by tschaub** [comment]
Maybe I just wasn’t patient enough.  The [v13 page](https://pkg.go.dev/github.com/apache/arrow/go/v13) now shows stable and tagged.  And the [v12 page](https://pkg.go.dev/github.com/apache/arrow/go/v12) notes that v13 is the highest tagged version.

So maybe my only remaining question is whether there is a URL that redirects to the highest tagged version?

**Comment by findleyr** [comment]
There was a bug that caused new version processing to be backlogged; we've since caught up.

> So maybe my only remaining question is whether there is a URL that redirects to the highest tagged version?

`pkg.go.dev/<path>` by default resolves to the highest tagged version, but only for the *same exact path*. Since different major versions have different paths, there is no URL that always resolves to the highest major version (but there is the hint that you noticed).

Closing since the processing problem is fixed.
