### ISSUE TITLE
Garbage collection frees memory while cgo function uses it

### ISSUE THREAD

**Issue by baskarangappan** [golang/go#62284]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/usr/local/go/bin"
GOCACHE="/Users/bangappa/Library/Caches/go-build"
GOENV="/Users/bangappa/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/bangappa/go/pkg/mod"
GONOPROXY="*.cisco.com"
GONOSUMDB="*.cisco.com"
GOOS="darwin"
GOPATH="/Users/bangappa/go"
GOPRIVATE="*.cisco.com"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/bangappa/AAA/Engines/Repos/platform-engines/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/nn/rmx8m1hn0638jchpty577x600000gn/T/go-build2883907392=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
My use goes like this:
```
func ProcessBuffer(buf []byte) {
	if len(buf) <= 0 {
		return
	}

	C.Foo(unsafe.Pointer(&buf[0]))
	....
	// fmt.Println(len(buf))
	return
}
```

### What did you expect to see?
I expected to see the memory of the buf is not freed until this ProcessBuffer function returns

### What did you see instead?
But I see that while the C.Foo is still executing the memory of buf being garbage collected. It doesn't happen always, but if I call this method in a loop, then within a few seconds the scenario happens.
At the same time, if I uncomment the commented line `fmt.Println(len(buf))`, then the issue isn't happening. This kind of gives the logic that, using the buf towards the end of the function makes the variable unmarked for deletion, but if I don't do that, Golang's garbage collection doesn't understand the fact that the buf is being still referenced inside C.Foo()

**Comment by seankhliao** [comment]
see https://pkg.go.dev/cmd/cgo#hdr-Passing_pointers

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by r0l1** [comment]
Use `runtime.KeepAlive(buf)`
