### ISSUE TITLE
gccgo: traceback should suppress frames with no debug info

### ISSUE THREAD

**Issue by gopherbot** [golang/go#6229]
by **capnm9**:

<pre>gccgo built from gcc tip:

commit f248394b138d19d68661563d4b6b5a22e3b12b18
Author: ian &lt;ian@138bc75d-0d04-0410-961f-82ee72b054a4&gt;
Date:   Fri Aug 23 01:08:25 2013 +0000

    libgo: Update libtool.m4 from upstream to recognize powerpcle.

    git-svn-id: svn+ssh://gcc.gnu.org/svn/gcc/trunk@201933 138bc75d-0d04-0410-961f-82ee72b054a4

E.g. divide by zero panic:

export GOTRACEBACK=2
./a.out
panic: runtime error: integer divide by zero

goroutine 1 [running]:
runtime_dopanic
    /data4/soft/go/gccgo-git/libgo/runtime/panic.c:71
__go_panic
    /data4/soft/go/gccgo-git/libgo/runtime/go-panic.c:113
runtime_panicstring
    /data4/soft/go/gccgo-git/libgo/runtime/panic.c:121
__go_runtime_error
    /data4/soft/go/gccgo-git/libgo/runtime/go-runtime-error.c:85

    :0
runtime_main
    /data4/soft/go/gccgo-git/libgo/runtime/proc.c:529
kickoff
    /data4/soft/go/gccgo-git/libgo/runtime/proc.c:229

    :0

goroutine 3 [runnable]:
kickoff
    /data4/soft/go/gccgo-git/libgo/runtime/proc.c:226

    :0
created by runtime_main
    /data4/soft/go/gccgo-git/libgo/runtime/proc.c:520

goroutine 4 [runnable]:
kickoff
    /data4/soft/go/gccgo-git/libgo/runtime/proc.c:226

    :0

goroutine 5 [runnable]:
kickoff
    /data4/soft/go/gccgo-git/libgo/runtime/proc.c:226

    :0</pre>

**Comment by ianlancetaylor** [comment]
I don't think there is anything to be done here.
