### ISSUE TITLE
log/slog: Documented value type for slog.SourceKey is wrong

### ISSUE THREAD

**Issue by lostluck** [golang/go#62294]
### What version of Go are you using (`go version`)?
1.21.0

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?
N/A

### What did you do?

Follow the documentation of slog.SourceKey and use it with a string value.

The [constant `slog.SourceKey`](https://pkg.go.dev/log/slog#SourceKey) is documented to have string values.

However, the [wrapping example](https://pkg.go.dev/log/slog#example-package-Wrapping) demonstrates that is has a [*slog.Source](https://pkg.go.dev/log/slog#Source) value.

A different package used the example code to remove the directory from log lines. https://github.com/proullon/ramsql/blob/master/engine/log/log.go#L22, which my code indirectly depended on, triggering a type assertion error the error on log.

This problem exists in the [exp/slog package as well](https://pkg.go.dev/golang.org/x/exp/slog#SourceKey

### What did you expect to see?

Document the type for SourceKey values as [*slog.Source](https://pkg.go.dev/log/slog#Source), which is the correct expected value.

Alternatively, the example needs to change.

### What did you see instead?

SourceKey values are documented as strings. https://pkg.go.dev/log/slog#SourceKey)

**Comment by ianlancetaylor** [comment]
CC @jba
