### ISSUE TITLE
wasm:wasip1 --- fatal error: all goroutines are asleep - deadlock!

### ISSUE THREAD

**Issue by it512** [golang/go#62304]
mikewang@VM-24-16-ubuntu:~/go_w/dd/cmd$ GOOS=wasip1 GOARCH=wasm ~/b/go/bin/go build server.go  
mikewang@VM-24-16-ubuntu:~/go_w/dd/cmd$ wazero run server
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
net.(*fakeNetFD).accept(...)
	/home/mikewang/b/go/src/net/net_fake.go:229
net.(*netFD).accept(0x14562c0)
	/home/mikewang/b/go/src/net/fd_wasip1.go:88 +0x3c
net.(*TCPListener).accept(0x142a0c0)
	/home/mikewang/b/go/src/net/tcpsock_posix.go:152 +0x4
net.(*TCPListener).Accept(0x142a0c0)
	/home/mikewang/b/go/src/net/tcpsock.go:315 +0x8
net/http.(*Server).Serve(0x1478000, {0xcb6e0, 0x142a0c0})
	/home/mikewang/b/go/src/net/http/server.go:3053 +0x2e
net/http.(*Server).ListenAndServe(0x1478000)
	/home/mikewang/b/go/src/net/http/server.go:2982 +0x10
net/http.ListenAndServe(...)
	/home/mikewang/b/go/src/net/http/server.go:3236
main.main()
	/home/mikewang/go_w/dd/cmd/server.go:15 +0xb

-------------------------
server.go
```golang

func main(){
    http.Handle("/foo", fooHandler)
    http.HandleFunc("/bar", func(w http.ResponseWriter, r *http.Request) {
        fmt.Fprintf(w, "Hello, %q", html.EscapeString(r.URL.Path))
    })
   log.Fatal(http.ListenAndServe(":8080", nil))
}
```
------------------------
**Environment (please complete the relevant information):**
- Go version: [e.g. 1.21.0]
- wazero Version: 1.5
- Host architecture: linux amd64

### What version of Go are you using (`go version`)?

<pre>
golang 1.21.0

</pre>

**Comment by seankhliao** [comment]
I believe this is expected, wasi have not stabilized sockets, so the current implementation is only here to pass tests https://github.com/WebAssembly/wasi-sockets/
