### ISSUE TITLE
x/pkgsite: my package doesn't show on the website but can be downloaded

### ISSUE THREAD

**Issue by ayonli** [golang/go#62303]
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/ayonli/goext

### What is your user agent?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

### Screenshot

![FireShot Capture 002 - github com_ayonli_goext - Go Packages - pkg go dev](https://github.com/golang/go/assets/58472737/8b0f67cb-8c67-4e34-8df1-1263808fb54f)

### What did you do?

I went to the pkg.go.dev and searched for my package, but it did not show on the website.

### What did you expect to see?

The package should be shown on the website.

### What did you see instead?

package could not be found.

The package is fully viable with the `go get` or `go mod tidy` command, this URL [https://proxy.golang.org/github.com/ayonli/goext/@v/v0.2.1.info](https://proxy.golang.org/github.com/ayonli/goext/@v/v0.2.1.info) also shows correct information about the package. And the package is actually being used by my other package [github.com/ayonli/gorpc](https://pkg.go.dev/github.com/ayonli/gorpc), but the website won't show it.

I've hit the **Request** button, but responded with **package could not be found**. How is that possible?

**Comment by seankhliao** [comment]
maybe #62031 
cc @findleyr

**Comment by ayonli** [comment]
@findleyr Thanks, man, much obliged.
