### ISSUE TITLE
affected/package: https://github.com/qax-os/excelize, https://github.com/tealeg/xlsx

### ISSUE THREAD

**Issue by devin7788** [golang/go#62312]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.21
</pre>

### Does this issue reproduce with the latest release?
After writing strings to Excel, the file content is all empty.

### What operating system and processor architecture are you using (`go env`)?
windows, amd64
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\18627\AppData\Local\go-build
set GOENV=C:\Users\18627\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\18627\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\18627\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.21.0
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\18627\AppData\Local\Temp\go-build3040523275=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?
After downgrading the Go version to 1.20.7, it worked correctly.

### What did you expect to see?
Hope this issue gets resolved in Go 1.21.

**Comment by seankhliao** [comment]
not a go project issue

**Comment by myNameIsVary** [comment]
Yeah, I saw that problem, too
m1 pro
go version go1.21.0 darwin/arm64
