### ISSUE TITLE
x/crypto/ssh/agent: Bad constraint extension id

### ISSUE THREAD

**Issue by 35niavlys** [golang/go#62311]
SSH agent has been implemented on [first version of the protocol definition (00)](https://datatracker.ietf.org/doc/html/draft-miller-ssh-agent-00#section-5.2) but at least a blocking change exists according [last version (11)](https://datatracker.ietf.org/doc/html/draft-miller-ssh-agent-11#section-5.2)
Constraint extension identifier is set to 3 but should be 255 here: https://github.com/golang/crypto/blob/master/ssh/agent/client.go#L146
Openssh implementation is ok: https://github.com/openssh/openssh-portable/blob/master/authfd.h#L109

**Comment by 35niavlys** [comment]
And of course this line must be updated too: https://github.com/golang/crypto/blob/master/ssh/agent/client.go#L208

**Comment by drakkan** [comment]
@35niavlys can you please confirm that the linked CL fixes the issue? Can you also share a small reproducer? I would like to add a small test case before merging the CL. Thank you

**Comment by 35niavlys** [comment]
I confirm it fixes the issue, I do not know how to create a golang test because I use openssh to do the test...

Run my test code: ```SSH_AUTH_SOCK=/tmp/test go run main.go```
Adding a key with a constraint```SSH_AUTH_SOCK=/tmp/test ssh-add -v -h myhost ~/.ssh/id_rsa```

My test code:
```golang
package main

import (
	"fmt"
	"log"
	"net"
	"os"

	"golang.org/x/crypto/ssh"
	"golang.org/x/crypto/ssh/agent"
)

type WrappedAgent struct {
	agent agent.Agent
}

func NewWrappedAgent(ag agent.Agent) *WrappedAgent {
	return &WrappedAgent{
		agent: ag,
	}
}

func (a *WrappedAgent) Add(key agent.AddedKey) error {
	fmt.Println(key.ConstraintExtensions)
	return a.agent.Add(key)
}

func (a *WrappedAgent) List() ([]*agent.Key, error) { return a.agent.List() }
func (a *WrappedAgent) Sign(key ssh.PublicKey, data []byte) (*ssh.Signature, error) { return a.agent.Sign(key, data) }
func (a *WrappedAgent) Remove(key ssh.PublicKey) error { return a.agent.Remove(key) }
func (a *WrappedAgent) RemoveAll() error { return a.agent.RemoveAll() }
func (a *WrappedAgent) Lock(passphrase []byte) error { return a.agent.Lock(passphrase) }
func (a *WrappedAgent) Unlock(passphrase []byte) error { return a.agent.Unlock(passphrase) }
func (a *WrappedAgent) Signers() ([]ssh.Signer, error) { return a.agent.Signers() }

func main() {
	socket := os.Getenv("SSH_AUTH_SOCK")
	os.Remove(socket)
	conn, err := net.Listen("unix", socket)
	if err != nil {
		log.Fatalf("Failed to open SSH_AUTH_SOCK: %v", err)
	}
	defer conn.Close()
	ag := NewWrappedAgent(agent.NewKeyring())
	for {
		l, err := conn.Accept()
		if err != nil {
			fmt.Printf("Failed to accept connection: %s\n", err)
			continue
		}
		go agent.ServeAgent(ag, l)
	}
}
```

Result without patch on server side:
```2023/09/03 20:30:30 agent 25: unknown constraint type: 255```

Result with patch on server side:
```[{restrict-destination-v00@openssh.com...```

**Comment by drakkan** [comment]
@35niavlys thank you for the reproducer. Even though the patch work and we can ignore the id 3 (SSH_AGENT_CONSTRAIN_MAXSIGN), we don't support [SSH agent restriction](https://www.openssh.com/agent-restrict.html) so the agent will not refuse signing for not allowed destination

**Comment by 35niavlys** [comment]
Yes I know its not implemented in the default keyring implementation

**Comment by drakkan** [comment]
> Yes I know its not implemented in the default keyring implementation

ok, if you have an implementation supporting `restrict-destination-v00@openssh.com` considering sharing it. I'll try to help merge in the main repo. Thank you.

@FiloSottile  do you think we have to try to add some compatibility layer to the linked CL to also parse requests using the previous constraint identifier? Do you know implementation other than OpenSSH using constraints?

**Comment by noonien** [comment]
I'm trying to work on an implementation supporting `restrict-destination-v00@openssh.com` but I'm blocked due to this issue.

**Comment by drakkan** [comment]
> I'm trying to work on an implementation supporting `restrict-destination-v00@openssh.com` but I'm blocked due to this issue.

@noonien please try the linked CL and confirm that it fixes the issue. The latest revision is also backward compatible. More confirmations it works as expected could speedup the upstream merge. Thank you

**Comment by noonien** [comment]
I've tested the CL with @35niavlys's reproducer and the server behaves correctly.

I'm not sure what the benefit is for keeping agentConstrainExtensionV00 for backward compatibility since this is clearly not up to spec. I'm guessing this is for use by an ssh agent client written in go connecting to an ssh agent server written in go, but if just the client is updated and connects to a server using the older version of x/crypto/ssh/agent, the same error will occur.

Otherwise, the CL fixes the initial issue.

**Comment by 35niavlys** [comment]
You can keep backward compatibility until SSH_AGENT_CONSTRAIN_MAXSIGN is not implemented but I agree with @noonien it's not really usefull.
And no I didn't start to work on ```restrict-destination-v00@openssh.com``` and I will probably don't have the time shortly

**Comment by 35niavlys** [comment]
I have at least a quick `restrict-destination-v00@openssh.com` parser if somebody needs it

**Comment by drakkan** [comment]
Thanks for your feedback, much appreciated. I've added compatibility bits to avoid breaking existing implementations even if  I'm not aware of any. We can live with it until we implement `SSH_AGENT_CONSTRAIN_MAXSIGN`.

The long term plan is to support `restrict-destination-v00@openssh.com` within `x/crypto/ssh/agent`, in the meantime if you have even a partial implementation it might be useful to share it. It can be used by others or as a basis for future upstream implementation.

Thank you!

**Comment by 35niavlys** [comment]
https://github.com/golang/crypto/compare/master...35niavlys:golang_crypto:add_constraints
