### ISSUE TITLE
testing/cover: 

### ISSUE THREAD

**Issue by bedisco** [golang/go#62321]
### What version of Go are you using (`go version`)?

<pre>
1.20

</pre>

### Does this issue reproduce with the latest release?

not sure

### What operating system and processor architecture are you using (`go env`)?

<details><summary>
GOHOSTOS='darwin'/'linux'
</summary><br><pre>
</pre></details>

### What did you do?

i used to add a func in /testing:
func GetCover(){
     return cover
}
to get runtime coverage which defined in testing/cover:
var cover Cover

but in go1.20, it seems like broken, i cannot get the cover.
meanwhile, the go test -coverfile=xxx.out also present the correct content.

### What did you expect to see?

i want to see the correct content in go1.20, so the go1.19 has.

### What did you see instead?

no content

**Comment by seankhliao** [comment]
This is not a supported, exported API.

**Comment by bedisco** [comment]
> 

yes but it works before 1.20， i want to know the difference
