### ISSUE TITLE
reflect: MakeSlice doesn't take an int64 for length

### ISSUE THREAD

**Issue by purpleidea** [golang/go#62331]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.21
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
Linux/amd64
</pre></details>

### What did you do?

Compiled, got error:

> cannot use i (value of type int64) as type int in argument to reflect.MakeSlice

### What did you expect to see?

MakeSlice takes an int as the size, but we would like to make slices of int64 size. I propose either changing the signature or perhaps more appropriately adding a MakeSlice64 which uses int64 as it's input instead.

https://pkg.go.dev/reflect#MakeSlice

Cheers!

**Comment by dsnet** [comment]
Hi, thanks for the issue report.

Why does this need to take in an `int64`? The `int` type (identical in size to `uintptr`) is sized appropriately to address the memory space that a Go program can use regardless of 32-bit vs 64-bit architectures. A Go map cannot possible be larger than the physically addressable memory space.

What's wrong with manually converting a `int64` into an `int` before calling `MakeSlice`?

**Comment by purpleidea** [comment]
I seem to have not remembered that `int` would be sized as an int64 on 64 bit systems. Sorry for the noise and thanks. That idea is workable. Cheers!
