### ISSUE TITLE
x/build: may-start-trybots only applies to one's own CLs

### ISSUE THREAD

**Issue by heschi** [golang/go#62332]
In LUCI, may-start-trybots only grants permission to trigger a presubmit run on a CL you authored yourself. (Approvers can still trigger presubmits on any CL.)

This makes community members less able to shepherd CLs and therefore slows down the Go project as a whole. We want to fix this in LUCI (see https://crbug.com/1443582), but if it's causing enough trouble in the meantime we can look into workarounds. If that's important to you, please comment on or react to this issue.

cc @golang/release

**Comment by prattmic** [comment]
This should be fixed now. Felix graciously tested triggering tests on https://go.dev/cl/554615.
