### ISSUE TITLE
x/vuln/cmd/govulncheck: output a final result in json mode

### ISSUE THREAD

**Issue by andy-github-info** [golang/go#62340]
### What version of Go are you using (`go version`)?

<pre>
# govulncheck  --version
Go: go1.21.0
Scanner: govulncheck@v1.0.1
DB: https://vuln.go.dev
DB updated: 2023-08-23 14:38:50 +0000 UTC

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
# go env
GO111MODULE='on'
GOARCH='amd64'
GOBIN=''
GOCACHE='/root/.cache/go-build'
GOENV='/root/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/root/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/root/go'
GOPRIVATE=''
GOPROXY='https://goproxy.cn,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.0'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='0'
GOMOD='/root/tmp/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build351832300=/tmp/go-build -gno-record-gcc-switches'

</pre></details>

### What did you do?

执行了以下命令检查漏洞
`# govulncheck -json ./...`

### What did you expect to see?

{
  "config": {
    "protocol_version": "v1.0.0",
    "scanner_name": "govulncheck",
    "scanner_version": "v1.0.1",
    "db": "https://vuln.go.dev",
    "db_last_modified": "2023-08-23T14:38:50Z",
    "go_version": "go1.21.0",
    "scan_level": "symbol"
  }
}
{
  "progress": {
    "message": "Scanning your code and 48 packages across 1 dependent module for known vulnerabilities..."
  }
}
{
  "result": {
    "status":  true
  }
}

### What did you see instead?
{
  "config": {
    "protocol_version": "v1.0.0",
    "scanner_name": "govulncheck",
    "scanner_version": "v1.0.1",
    "db": "https://vuln.go.dev",
    "db_last_modified": "2023-08-23T14:38:50Z",
    "go_version": "go1.21.0",
    "scan_level": "symbol"
  }
}
{
  "progress": {
    "message": "Scanning your code and 48 packages across 1 dependent module for known vulnerabilities..."
  }
}

**Comment by zpavlinovic** [comment]
What would be the easiest way for us to reproduce this?

**Comment by zpavlinovic** [comment]
It is also not clear what is being suggested here. The govulncheck command provides streaming json containing the result section. Could it just be that govulncheck did not find anything for your project?

**Comment by andy-github-info** [comment]
Use the command 'govulncheck-json. /... 'Reproduce.

**Comment by andy-github-info** [comment]
It is hoped that a key value in the json result of govulncheck can clearly indicate whether there is any vulnerability in the detection result. The current version does not have this key/value, so it cannot be integrated into CI for automation.

**Comment by zpavlinovic** [comment]
`govulncheck` supports streaming json where typically one will see a `config` section followed by a `progress` section, followed by `finding`s. (More info also [here](https://github.com/golang/vuln/blob/master/internal/govulncheck/govulncheck.go)). If there are no findings, that means nothing has been found. It is specifically designed for CI automation where the results are communicated as soon as they are computed (hence streaming).

Closing.

**Comment by andy-github-info** [comment]
Like the following? If the finding property is in, there is a vulnerability; otherwise, there is no vulnerability

`root@Ubuntu ~/tmp# govulncheck  -json ./... |jq ".finding"
null
null
null
{
  "osv": "GO-2021-0113",
  "fixed_version": "v0.3.7",
  "trace": [
    {
      "module": "golang.org/x/text",
      "version": "v0.3.5",
      "package": "golang.org/x/text/language",
      "function": "Parse"
    },
    {
      "module": "tmp",
      "package": "tmp",
      "function": "main",
      "position": {
        "filename": "/root/tmp/g1.go",
        "offset": 189,
        "line": 12,
        "column": 43
      }
    }
  ]
}
null
{
  "osv": "GO-2022-1059",
  "fixed_version": "v0.3.8",
  "trace": [
    {
      "module": "golang.org/x/text",
      "version": "v0.3.5",
      "package": "golang.org/x/text/language"
    }
  ]
}`

**Comment by zpavlinovic** [comment]
Yes, and you can have multiple findings.

Each finding will give you the information needed to interpret it. Above, you can see that you have a trace of multiple `frames` showing you the call stack. That means that the vulnerability was called and the `function` in the first frame is the vulnerable symbol.

If the trace has only one entry whose `function` is empty, that means that the vulnerability is only imported.

We plan to write up more detailed documentation about json output.

**Comment by andy-github-info** [comment]
ok, thanks
