### ISSUE TITLE
strings.TrimLeft("xxx "), In case of loss of a

### ISSUE THREAD

**Issue by icowan** [golang/go#62344]
```
        var authorization = "Bearer app-xxx"
	fmt.Println(strings.TrimLeft(authorization, "Bearer "))
	fmt.Println(strings.TrimLeft(authorization, "Bearer"))
	fmt.Println(strings.TrimSpace(strings.TrimLeft(authorization, "Bearer")))
	fmt.Println("-------")
	authorization = "Bearer sk-xxx"
	fmt.Println(strings.TrimLeft(authorization, "Bearer "))
	fmt.Println(strings.TrimLeft(authorization, "Bearer"))
	fmt.Println(strings.TrimSpace(strings.TrimLeft(authorization, "Bearer")))
```

<img width="235" alt="image" src="https://github.com/golang/go/assets/6229526/b8161274-dc07-4a04-9322-13aed8eee2f4">

### What version of Go are you using (`go version`)?

<pre>
go version go1.20.1 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/dudulu/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/go"
GOPRIVATE=""
GOPROXY=""
GOROOT="/go/go1.20.1"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/go/go1.20.1/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.20.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="0"
GOMOD="go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/qd/h_6jw84502g0r1q7b61w3wsc0000gn/T/go-build257210823=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
nothing

### What did you expect to see?

// pp-

### What did you see instead?

// app-

**Comment by gazerro** [comment]
This is the correct behavior, use the `TrimPrefix` and `TrimSuffix` functions instead.

**Comment by realpg** [comment]
please read the manual before post an issue

**Comment by go101** [comment]
https://github.com/golang/go/issues?q=is%3Aissue+TrimLeft+is%3Aclosed

**Comment by wxl2578** [comment]
丢人现眼的玩意儿

**Comment by icowan** [comment]
> 丢人现眼的玩意儿

不懂就问，为什么？

**Comment by icowan** [comment]
> This is the correct behavior, use the `TrimPrefix` function instead.

thank you！
