### ISSUE TITLE
affected/package: 

### ISSUE THREAD

**Issue by eyes-of-ice** [golang/go#62343]
build golang.org/x/sys/windows: cannot load golang.org/x/sys/windows: no Go source files

what should i do?
im using ubuntu20

**Comment by mengzhuo** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

----------
p.s. You should check your network and proxy setting to download proper go module.
