### ISSUE TITLE
affected/package: package web/tool is not in std (C:\Program Files\Go\src\web\tool) ??

### ISSUE THREAD

**Issue by pwango** [golang/go#62348]
The module web have another module file (tool includes hw.go, package name is hw, just for printing hello world )

When I used the test.go to import "web/tool", the computer still return error "package web/tool is not in std (C:\Program Files\Go\src\web\tool)" even after using go mod and go work command.

Could you tell me the way to address the error for using local module? I just a rookie in golang, thanks.

<details><summary><code>go env</code> Output</summary><br><pre>
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\agntw\AppData\Local\go-build
set GOENV=C:\Users\agntw\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=F:\goProject\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=F:\goProject
set GOPRIVATE=
set GOPROXY=https://mirrors.aliyun.com/goproxy/,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.21.0
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=F:\goProject\src\web\go.mod
set GOWORK=F:\goProject\src\web\go.work
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\agntw\AppData\Local\Temp\go-build3461556476=/tmp/go-build -gno-record-gcc-switches

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by pwango** [comment]
answer it please!

**Comment by pwango** [comment]
> 

Sorry, I have searched most pagers in web. but I did not obtain any usful answer for this problem.

**Comment by ianlancetaylor** [comment]
The page https://go.dev/wiki/Questions tell you where to ask your questions.  It doesn't answer your questions, it tells you where to ask them.  This is not the place to ask them.
