### ISSUE TITLE
x/pkgsite: package removal request for [type path here]

### ISSUE THREAD

**Issue by sidneycao** [golang/go#62341]
### What is the path of the package that you would like to have removed?
github.com/SidneyCao/gofile
github.com/SidneyCao/tcping

### Are you the owner of this package?
Yes

### What is the reason that you could not retract this package instead?
Today i have changed my github accout name from SidneyCao  to sidneycao,
and also the pkg path should changed from github.com/SidneyCao/gofile to github.com/sidneycao/gofile or
from github.com/SidneyCao/tcping to github.com/sidneycao/tcping

but now https://pkg.go.dev/ only shows  github.com/SidneyCao/*  and github.com/sidneycao/* will redirect to github.com/SidneyCao/*, which confused me a lot.

**Comment by sidneycao** [comment]
Now github.com/sidneycao/* will not redirect to github.com/SidneyCao/*, but https://pkg.go.dev/  still not show github.com/sidneycao/*.

**Comment by seankhliao** [comment]
i see both https://pkg.go.dev/github.com/sidneycao/tcping and https://pkg.go.dev/github.com/sidneycao/gofile

**Comment by sidneycao** [comment]
Now i can see both， but the search result can only show  github.com/SidneyCao/*

**Comment by sidneycao** [comment]
It worked！ Thanks  a lot!
