### ISSUE TITLE
affected/package: package xxx  is not in std???

### ISSUE THREAD

**Issue by pwango** [golang/go#62364]
Recently, I met a problem regarding import local package even after using go mod and go work comand acording to the tutoral of official website. 

I think may this problem is a bug because go work is useless!!

 And I did not got any usful result from internet. So come here.

![屏幕截图 2023-08-30 103642](https://github.com/golang/go/assets/143368172/655b3a55-ecae-433a-926d-58e83794601a)

![屏幕截图 2023-08-30 104813](https://github.com/golang/go/assets/143368172/5a398672-c224-4951-bf5b-ac1e57896427)

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
