### ISSUE TITLE
affected/package: 

### ISSUE THREAD

**Issue by bytss** [golang/go#62371]
Hello, is there a possible solution for this without merging them in a single aar?

Error:
Duplicate class go.Seq found in modules

![image](https://github.com/golang/go/assets/97946487/d6f7d60a-defc-4207-a60b-570545c5a570)

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
