### ISSUE TITLE
x/tools/gopls/internal/lsp: slice bounds out of range error during typerefs.Decode

### ISSUE THREAD

**Issue by siamkiw** [golang/go#62383]
gopls version: v0.13.2 (go1.19.4)
gopls flags: 
update flags: proxy
extension version: 2023.8.1617
go version: 1.19.4
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Wed, 30 Aug 2023 09:56:11 GMT
restart history:
Wed, 30 Aug 2023 09:55:46 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: slice bounds out of range [:1728708865] with capacity 504

goroutine 3780 [running]:
golang.org/x/tools/gopls/internal/lsp/frob.(*reader).bytes(...)
	  frob.go:404
golang.org/x/tools/gopls/internal/lsp/frob.(*frob).decode(0x1400007fad0, 0x140040c5840, {0x1038d2300%3F, 0x14004306000%3F, 0x14000a441c8%3F})
	  frob.go:362  0xfc8
golang.org/x/tools/gopls/internal/lsp/frob.(*frob).decode(0x1400007faa0, 0x140e4b9f840, {0x1038c5fc0%3F, 0x14002605d10%3F, 0x104208108%3F})
	  frob.go:324  0x101c
golang.org/x/tools/gopls/internal/lsp/frob.(*frob).decode(0x1400027b470, 0x140e4b9f840, {0x10395fba0%3F, 0x14002605d10%3F, 0xe380%3F})
	  frob.go:367  0xf80
golang.org/x/tools/gopls/internal/lsp/frob.(*frob).Decode(0x1400027b470, {0x140021c3e00, 0xb3, 0x200}, {0x1038b06e0%3F, 0x14002605d10%3F})
	  frob.go:258  0x1a8
golang.org/x/tools/gopls/internal/lsp/source/typerefs.decode(0x140002b86e0%3F, {0x103a246d8%3F, 0x140042632c0%3F}, {0x140021c3e00, 0xb3, 0x200})
	  refs.go:806  0x6c
golang.org/x/tools/gopls/internal/lsp/source/typerefs.Decode(...)
	  refs.go:42
golang.org/x/tools/gopls/internal/lsp/cache.(*snapshot).typerefs(0x140002b86e0, {0x103a246d8, 0x140042632c0}, 0x14000341200, {0x103fc4098, 0x0, 0x0})
	  check.go:1224  0x188
golang.org/x/tools/gopls/internal/lsp/cache.(*packageHandleBuilder).buildPackageHandle(0x1400290d380, {0x103a246d8, 0x140042632c0}, 0x140003fba40)
	  check.go:1082  0x1c8
golang.org/x/tools/gopls/internal/lsp/cache.(*snapshot).getPackageHandles.func2.1()
	  check.go:891  0xb0
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:75  0x5c
created by golang.org/x/sync/errgroup.(*Group).Go
	  errgroup.go:72  0xa4
[Error - 4:55:53 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by adonovan** [comment]
Thanks for reporting this; it's very mysterious? How often have you observed it? I added an assertion that may help diagnose the cause. If you are able to reproduce this crash readily, please try cloning and building gopls from master and let us know what you observe.

**Comment by findleyr** [comment]
Has this reoccurred? If not, we don't have much to go on, and are unlikely to be able to root cause the issue here.

Bumping to v0.15 to keep on our radar.
