### ISSUE TITLE
affected/package: errors

### ISSUE THREAD

**Issue by FocusHuang** [golang/go#62386]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
<pre>
type bizError struct {
	Code    int32
	Message string
}

func NewBizError(code int32, message string) error {
	return &bizError{
		Code:    code,
		Message: message,
	}
}

func IsBizError(err error) bool {
	return errors.As(err, &bizError{})
}

func (err bizError) Error() string {
	return fmt.Sprintf("Code=%d, Message=%s\n", err.Code, err.Message)
}

func TestBizError(t *testing.T) {
	tests := []struct {
		err      error
		expected bool
	}{
		{
			err:      e.NewBizError(1, "bizerror"),
			expected: true,
		},
		{
			err:      errors.New("normal"),
			expected: false,
		},
	}

	for _, test := range tests {
		if ok := IsBizError(test.err); ok != test.expected {
			t.Fatal("not correct")
		}
	}
}
</pre>

### What did you expect to see?
these testcase wiil be pass

### What did you see instead?
not passed because returned a ptr when NewBizError(code int32, message string)

**Comment by Jorropo** [comment]
```diff
 func NewBizError(code int32, message string) error {
-	return &bizError{
+	return bizError{
 		Code:    code,
 		Message: message,
 	}
 }
```
Don't return a pointer then, no where in your code a pointer is used.
