### ISSUE TITLE
x/crypto/ssh: investigate support for ping@openssh.com protocol extension

### ISSUE THREAD

**Issue by drakkan** [golang/go#62390]
Maybe we can just advertise server side support for this extension and reply to ping requests

see section 1.9

https://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.bin/ssh/PROTOCOL?rev=HEAD

This extension will be added to OpenSSH 9.5

**Comment by dmitshur** [comment]
CC @FiloSottile.

**Comment by djmdjm** [comment]
FYI I've started an I-D to get this extension standardised but that would be art least a year away.

https://github.com/djmdjm/drafts/blob/master/draft-miller-ssh-ping.txt

**Comment by hanwen** [comment]
Is this RFC final already? 

A single byte keystroke looks like 10 bytes (uint8 packet type, uint32 channel ID, uint32 data length, data), but in response the other side will  send a 9 byte window adjust message (uint8 packet type, uint32 channel ID, uint32 byte count.)

wouldn't it be better if the pong message contained the number of bytes to send in return?
