### ISSUE TITLE
affected/package: toolchain test/fixedbugs/10607

### ISSUE THREAD

**Issue by cflewis** [golang/go#62399]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.21

</pre>

### Does this issue reproduce with the latest release?
Yes, also repro'd 1.20.6, which is the only other one I tried.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/cflewis/.cache/go-build'
GOENV='/home/cflewis/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/cflewis/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/cflewis/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/home/cflewis/downloads/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/home/cflewis/downloads/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.0'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='0'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3443187397=/tmp/go-build -gno-record-gcc-switches'

</pre></details>

### What did you do?

```shell
# Go wild and delete gcc on a fresh Debian VM
sudo apt remove libgcc-10-dev

# Get toolchain source before hand and go into the directory
export CGO_ENABLED=0
git checkout go1.21.0
cd src/
./make.bash
./run.bash --no-rebuild
```

### What did you expect to see?
A happy completion.

### What did you see instead?

```shell
# Other output snipped.
##### ../test
--- FAIL: Test (0.05s)
    --- FAIL: Test/fixedbugs/issue10607.go (1.32s)
        testdir_test.go:141: exit status 1
            BUG: linkmode=external exit status 1
            # command-line-arguments
            loadinternal: cannot find runtime/cgo
            /home/cflewis/downloads/go/pkg/tool/linux_amd64/link: running gcc failed: exec: "gcc": executable file not found in $PATH



FAIL
FAIL	cmd/internal/testdir	40.625s
FAIL
2023/08/31 17:27:08 Failed: exit status 1

##### API check
ok  	cmd/api	39.590s
go tool dist: FAILED
```

https://tip.golang.org/test/fixedbugs/issue10607.go wants `cgo` in the build tags:

```
//go:build linux && !ppc64 && gc && cgo
// +build linux,!ppc64,gc,cgo
```

However, even with `CGO_ENABLED=0`, something happens during the test harness where I guess the `cgo` bit is lost.

**Comment by ianlancetaylor** [comment]
Thanks.  This has already been fixed on HEAD by https://go.dev/cl/522495 and https://go.dev/cl/522635.
