### ISSUE TITLE
x/pkgsite: 

### ISSUE THREAD

**Issue by cva-source** [golang/go#62401]
### What is the URL of the page with the issue?
https://pkg.go.dev/github.com/jfrog/jfrog-cli@2.3.0

What's the process on adding jfrog-cli v2.3.0 to pkg.go.dev? Needing for a project and wondering what steps to take in order to get this onto pkg.go.dev.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
