### ISSUE TITLE
x/website: dead link

### ISSUE THREAD

**Issue by josephmarkus** [golang/go#62416]
### What is the URL of the page with the issue?

https://go.dev/solutions/cloud
 
### What is your user agent?
 
Chrome 116
 
### Screenshot
 
<img width="1229" alt="Screenshot 2023-09-01 at 17 58 45" src="https://github.com/golang/go/assets/9258365/95d72815-be5d-44eb-9178-b9f470e728a6"> 
 
### What did you do?
 
Clicked on 'Mastering Go Web Services'
 
### What did you expect to see?

Link with the above book
 
### What did you see instead?

404

**Comment by ianlancetaylor** [comment]
Thanks for reporting this.
