### ISSUE TITLE
Map keys are being all updated

### ISSUE THREAD

**Issue by mhclaudiu** [golang/go#62428]
### What version of Go are you using (`go version`)?

<pre>
go1.21.0 darwin/arm64

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOHOSTARCH='arm64'
GOHOSTOS='darwin'

</pre></details>

### What did you do?

https://go.dev/play/p/qs7_ZpI8l0o

### What did you expect to see?

`map[bridge:map[rx:0 tx:0] ether:map[rx:1 tx:1] wg:map[rx:0 tx:0] wlan:map[rx:0 tx:0]]`

### What did you see instead?

`map[bridge:map[rx:1 tx:1] ether:map[rx:1 tx:1] wg:map[rx:1 tx:1] wlan:map[rx:1 tx:1]]`

Hello team, is there something wrong in what I'm doing? I don't understand why the all the map keys are being updated, it should be only the 'ether' key.

**Comment by randall77** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
