### ISSUE TITLE
Updated struct `value` in `map`

### ISSUE THREAD

**Issue by Almazatun** [golang/go#62435]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.20.6

</pre>

### Does this issue reproduce with the latest release?
 Sorry, I don't know

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOMODCACHE="/Users/pc/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/pc/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.6"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/pc/dev/test/backend/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cr/10sy8pl574s35c7v0njtxpxm0000gn/T/go-build3112415207=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
Backend service with some endpoints without database. Three endpoints with working with http `protocol` and one with `websoket`.

Structs in service
```go
type Clients struct {
	Clients map[string]*Client
	Rooms   map[string]ClientRoom
}
type ClientRoom struct {
	RoomID   string `json:"roomId"`
	Name     string `json:"name"`
	ClientID string `json:"clientId"`
}
type Room struct {
	ID   string
	Name string
	JoinClients map[string]string
}
type Client struct {
	ID             string
	Rooms          map[string]*Room
	Username       string
}

func NewClients() *Clients {
	cls := &Clients{
		Clients: make(map[string]*Client),
		Rooms:   make(map[string]ClientRoom),
	}

	return cls
}

func main(){
        app := fiber.New()
	cls := NewClients()

//Register route just for create client 
app.Post("/register", func(c *fiber.Ctx) error {
               id := "test"
               username := "some_username"
               c := NewClient(username, id)

	       cls.Clients[id] = c
               
		return c.Status(200).JSON(&fiber.Map{
			"success":    true,
			"clientUUID": client.ID,
			"username":   registerClient.Username,
		})
	})
	
//Just for create room
app.Post("/rooms/:user_uuid", func(c *fiber.Ctx) error {
		uuid := c.Params("user_uuid")

		cl := cls.Clients[uuid]
		id := "test"
		r := &Room{
		   ID:          id,
		   Name:        name,
		   JoinClients: make(map[string]string),
	        }

	        cl.Rooms[id] = r
                
		cls.Rooms[roomId] = ClientRoom{ClientID: uuid, RoomID: roomId, Name: name}

		fmt.Println("CREATE_ROOM", cls.Clients)
		fmt.Println("CREATE_ROOM", cls.Rooms)

		return c.Status(200).JSON(&fiber.Map{
			"success":  true,
			"roomUUID": r.ID,
			"roomName": r.Name,
		})
	})
	
//For get all rooms
app.Get("/rooms/:user_uuid", func(c *fiber.Ctx) error {
		uuid := c.Params("user_uuid")

		fmt.Println("GET_ROOMS", cls.Clients)
		fmt.Println("GET_ROOMS", cls.Rooms)

		return c.Status(200).JSON(&fiber.Map{
			"success": true,
			"rooms":   []
		})
	})
	
//Websocket endpoint
app.Get("/ws/:roomId", websocket.New(func(c *websocket.Conn) {
		defer func() {
			c.Close()
		}()

		fmt.Println("WS", cls.Clients)
		fmt.Println("WS", cls.Rooms)
	}))
}
```
![image](https://github.com/golang/go/assets/50825098/713f594b-6bcb-4d96-a2b0-a7a5ac45dc60)
If look at scheen in the end of the terminal `cls.Rooms` changed `client id` from `test` to `YFUF`. I can't understand this behavior, because  in all of the `endpoints` I don't have any domain logic that can change in `cls.Rooms` `ClientID in Room struct`. After some of time I realized that `YFUF` is peace of `RoomID`. I don't have any idea how peace of `RoomID` replaced `client id` in `map`.

### What did you expect to see?
WS map[VGJYFUFDYAUC:{VGJYFUFDYAUC asdf `test`}]

### What did you see instead?
WS map[VGJYFUFDYAUC:{VGJYFUFDYAUC asdf `YFUF`}]

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by Almazatun** [comment]
@seankhliao sorry for that. But I didn't ask a question, just represent the `bug` case with data structure `map`.

**Comment by seankhliao** [comment]
that sounds like a problem from the poor choice of http framework doing unsafe things, not a go problem

**Comment by Almazatun** [comment]
@seankhliao Thanks.
