### ISSUE TITLE
cmd/internal/obj: stack bounds check prologue can be preemptible and resume at entry

### ISSUE THREAD

**Issue by zhouguangyuan0718** [golang/go#62433]
The stack bounds check prologue is nonpreemptible now. But actually, if we mark the unsafepoint of it as "RestartAtEntry", it can be async preempted safely. After async preempted, we just need resume it at the entry of the function.

And according to the comment in [CL 208126](https://go-review.googlesource.com/c/go/+/208126):

> TODO: the split-stack function prologue is currently not async
preemptible. We could use this mechanism, preempt it and restart
at the function entry.

It will be reasonable to do this.

**Comment by cherrymui** [comment]
This doesn't really need an issue. You can just send a CL (as you already did) and we can go from there (and have the discussion in one place). Thanks.
