### ISSUE TITLE
plugin: variable not initialized properly

### ISSUE THREAD

**Issue by oszika** [golang/go#62430]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.0 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
❯ go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/oszika/.cache/go-build'
GOENV='/home/oszika/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/oszika/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/oszika/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/lib/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/lib/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.0'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/oszika/example/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1329397681=/tmp/go-build -gno-record-gcc-switches'
</pre></details>

### What did you do?

I tried to use regexp on a plugin and it fails. After a little investigation, I saw unicode.Categories is not properly initialized.

Plugin: p1/main.go
```
package main

import (
	"unicode"
)

func F(s string) *unicode.RangeTable {
	return unicode.Categories[s]
}

func main() {}
```

main.go:
```
package main

import (
	"fmt"
	"plugin"
	"unicode"
)

func main() {
	p, err := plugin.Open("p1.so")
	if err != nil {
		panic(err)
	}
	s, err := p.Lookup("F")
	if err != nil {
		panic(err)
	}

	f := s.(func(string) *unicode.RangeTable)
	if f("C") == nil {
		fmt.Println("unicode.Categories not properly initialized")
	} else {
		fmt.Println("unicode.Categories properly initialized")
	}
}
```

Execution:
`$ go build -buildmode=plugin ./p1 && go run main.go
unicode.Categories not properly initialized`

If I add a use of unicode.Categories in the ./main.go, it is properly initialized. For example:
`_ = unicode.Categories["C"]`.

Note: when unicode.Categories is not properly initialized, It is not nil but an empty map.

### What did you expect to see?
The unicode.Categories properly initialized.

### What did you see instead?
An empty map.

**Comment by candlerb** [comment]
I observe that if you add this line anywhere inside your top-level main() function, it works:

```
fmt.Println(len(unicode.Categories))
```

Or even just add this outside the main function:

```
var z = unicode.Categories
```

Hence it appears to be something to do with the triggering (or suppression) of package initialization.  The [documentation](https://pkg.go.dev/plugin) says:

> When a plugin is first opened, the init functions of all packages not already part of the program are called.

You have already imported "unicode" to access the type `unicode.RangeTable`, but possibly because you're not accessing any *values* this has suppressed initialization?

**Comment by oszika** [comment]
Hum, I have not been able to reproduce this behavior with another variable.

If I add  a init function using unicode.Categories in the plugin, there is no reason to remove its initialization.
```
func init() {
	fmt.Println(len(unicode.Categories))
}
```
But it prints 0.
```
$ go build -buildmode=plugin ./p1 && go run main.go
0
unicode.Categories not properly initialized
```

**Comment by candlerb** [comment]
Yes, what matters is whether the main program initializes unicode (which you can do using "var z = unicode.Categories" in the top-level main.go)

As a complete guess:
* Main program thinks: "I'm not using any variables from unicode, I don't need to initialize it"
* Plugin thinks: "main program already links with unicode, I don't need to initialize it"

**Comment by candlerb** [comment]
I modified your reproducer to demonstrate a similar issue with the regexp library as reported on [golang-nuts](https://groups.google.com/g/golang-nuts/c/jKRHGGkU4pw):

```
==> go.mod <==
module example.com

go 1.20

==> main.go <==
package main

import (
	"plugin"
	"regexp/syntax"
)

func main() {
	if syntax.Perl != 212 {
		panic("Unexpected flags")
	}

	p, err := plugin.Open("p1.so")
	if err != nil {
		panic(err)
	}
	s, err := p.Lookup("F")
	if err != nil {
		panic(err)
	}

	f := s.(func())
	f()
}

==> p1/plugin.go <==
package main

import (
	"regexp"
)

func F() {
	_ = regexp.MustCompile(`\w+`)
}

func main() {}
```

```
$ go version
go version go1.21.0 darwin/amd64
$ go build -buildmode=plugin ./p1 && go run main.go
panic: regexp: Compile(`\w+`): error parsing regexp: invalid escape sequence: `\w`

goroutine 1 [running]:
regexp.MustCompile({0x107aa6eea, 0x3})
	/usr/local/go/src/regexp/regexp.go:319 +0xb4
example.com/p1.F()
	/Users/brian/tmp/go/62430/p1/plugin.go:8 +0x1f
main.main()
	/Users/brian/tmp/go/62430/main.go:23 +0x103
exit status 2
```

**Comment by cherrymui** [comment]
cc @thanm 

I haven't looked into this carefully, but I guess this is related to the map initialization change. My guess (without looking into details) is that as the main program imports the unicode package but not explicitly use the map, it initialize the unicode package but not the map. When the plugin is loaded, it sees the unicode package is already initialized by the main program, it doesn't initialize it again, leaving the map uninitialized. Maybe we need to initialize maps for programs that can use plugins.

**Comment by tarm** [comment]
Supporting what @cherrymui said, I bisected to e2ca417ee797e1e80d8d395e0f4760416b8346d9

https://go.dev/cl/463395

**Comment by thanm** [comment]
Thanks for the report. I will take a look.

**Comment by candlerb** [comment]
The regexp case is almost certainly also due to an uninitialized map, in `regexp/syntax/perl_groups.go`

```
var perlGroup = map[string]charGroup{
        `\d`: {+1, code1},
        `\D`: {-1, code1},
        `\s`: {+1, code2},
        `\S`: {-1, code2},
        `\w`: {+1, code3},
        `\W`: {-1, code3},
}
```
