### ISSUE TITLE
x/mobile/cmd/gomobile: gomobile bind fails for ambiguous paths

### ISSUE THREAD

**Issue by hajimehoshi** [golang/go#62458]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/hajimehoshi/Library/Caches/go-build"
GOENV="/Users/hajimehoshi/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/hajimehoshi/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/hajimehoshi/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.20.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/hajimehoshi/test/mobiletest/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/60/khbk2xqn1c5bml1byjn89dwc0000gn/T/go-build2688873579=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

Prepare this project

```
module mobiletest

go 1.20

require golang.org/x/mobile v0.0.0-20230905140555-fbe1c053b6a9

require (
        golang.org/x/exp v0.0.0-20190731235908-ec7cb31e5a56 // indirect
        golang.org/x/image v0.11.0 // indirect
        golang.org/x/sys v0.11.0 // indirect
)
```

```go
package foo

import (
        _ "golang.org/x/mobile/app"
)

func Dummy() {}
```

and run

```go
gomobile bind .
```

The gomoible version is fbe1c053b6a9fb82bd32271219fa206af328fa80
The go.mod is created by `go mod tidy` and modified to depend on `golang.org/x/exp`

### What did you expect to see?

No error

### What did you see instead?

```
gomobile: go mod tidy failed: exit status 1
go: found mobiletest in mobiletest v0.0.0-00010101000000-000000000000
gobind/gobind imports
        mobiletest imports
        golang.org/x/mobile/app imports
        golang.org/x/exp/shiny/driver/gldriver: ambiguous import: found package golang.org/x/exp/shiny/driver/gldriver in multiple modules:
        golang.org/x/exp v0.0.0-20190731235908-ec7cb31e5a56 (/Users/hajimehoshi/go/pkg/mod/golang.org/x/exp@v0.0.0-20190731235908-ec7cb31e5a56/shiny/driver/gldriver)
        golang.org/x/exp/shiny v0.0.0-20230817173708-d852ddb80c63 (/Users/hajimehoshi/go/pkg/mod/golang.org/x/exp/shiny@v0.0.0-20230817173708-d852ddb80c63/driver/gldriver)
gobind/gobind imports
        mobiletest imports
        golang.org/x/mobile/app imports
        golang.org/x/exp/shiny/screen: ambiguous import: found package golang.org/x/exp/shiny/screen in multiple modules:
        golang.org/x/exp v0.0.0-20190731235908-ec7cb31e5a56 (/Users/hajimehoshi/go/pkg/mod/golang.org/x/exp@v0.0.0-20190731235908-ec7cb31e5a56/shiny/screen)
        golang.org/x/exp/shiny v0.0.0-20230817173708-d852ddb80c63 (/Users/hajimehoshi/go/pkg/mod/golang.org/x/exp/shiny@v0.0.0-20230817173708-d852ddb80c63/screen)
```

https://go-review.googlesource.com/c/mobile/+/525695 is the fix.

**Comment by hajimehoshi** [comment]
Unfortunately, it seems impossible to resolve this go.mod, even though the Go version is specified.

```go
module gobind

go 1.20

replace mobiletest => /Users/hajimehoshi/test/mobiletest

require (
	github.com/BurntSushi/xgb v0.0.0-20160522181843-27f122750802
	github.com/yuin/goldmark v1.4.13
	golang.org/x/crypto v0.0.0-20210921155107-089bfa567519
	golang.org/x/exp v0.0.0-20190731235908-ec7cb31e5a56
	golang.org/x/exp/shiny v0.0.0-20230817173708-d852ddb80c63
	golang.org/x/image v0.11.0
	golang.org/x/mobile v0.0.0-20230905140555-fbe1c053b6a9
	golang.org/x/mod v0.12.0
	golang.org/x/net v0.6.0
	golang.org/x/sync v0.3.0
	golang.org/x/sys v0.11.0
	golang.org/x/term v0.5.0
	golang.org/x/text v0.12.0
	golang.org/x/tools v0.12.1-0.20230818130535-1517d1a3ba60
	golang.org/x/xerrors v0.0.0-20190717185122-a985d3407aa7
)
```

**Comment by hajimehoshi** [comment]
I've confirmed that the 'regular' go.mod (requiring golang.org/x/exp/shiny, not golang.org/x/exp)

```
module mobiletest

go 1.20

require golang.org/x/mobile v0.0.0-20230905140555-fbe1c053b6a9

require (
	golang.org/x/exp/shiny v0.0.0-20230817173708-d852ddb80c63 // indirect
	golang.org/x/image v0.11.0 // indirect
	golang.org/x/sys v0.11.0 // indirect
)
```

also fails to be compiled with the same error. Instead, this can now be compiled with my fix https://go-review.googlesource.com/c/mobile/+/525695. So my fix cannot fix the original issue, but can fix the above issue.

**Comment by cherrymui** [comment]
cc @hyangah
