### ISSUE TITLE
cmd/compile: internal compiler error: InvertFlags should never make it to codegen v100 = InvertFlags v123

### ISSUE THREAD

**Issue by TheRook** [golang/go#62469]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.0 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH='arm64'
</pre></details>

### What did you do?
go get github.com/azr/phash
go build

### What did you expect to see?

clean build, worked on 1.20.0

### What did you see instead?

# github.com/azr/phash/geometry/triangle
/Users/mike/go/pkg/mod/github.com/azr/phash@v0.2.0/geometry/triangle/triangle.go:38:12: internal compiler error: '(*Triangle).HasPoint': InvertFlags should never make it to codegen v100 = InvertFlags <flags> v123

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new

**Comment by randall77** [comment]
Smaller reproducer:
```
package main

func sign(p1, p2, p3 Point) bool {
	return (p1.X-p3.X)*(p2.Y-p3.Y)-(p2.X-p3.X)*(p1.Y-p3.Y) < 0
}

type Point struct {
	X, Y int
}
```

**Comment by randall77** [comment]
@gopherbot please open a backport issue for 1.21.
