### ISSUE TITLE
proposal: log/slog: implement a method to change logger level

### ISSUE THREAD

**Issue by tiaguinho** [golang/go#62473]
Today, the only way to change the logger level is creating a new logger.
But there are at least two scenarios where having a method to change the logger level will be nice.

1. Let's say I have an environment variable to enable DEBUG mode. Instead of create a new logger with the debug level configured, will be easiest just call a method.
```go
logger.SetLevel(slog.LevelDebug)
``` 

2. If I'm using a default logger on my application, and want to enable debug level on a single package.
```go
logger = slog.Default().WithLevel(slog.LevelDebug)
```

To solve the problem of create a new logger every time the logger level needs to be changed, I'm proposing the implementation of two methods `SetLevel` and `WithLevel`.

**Comment by seankhliao** [comment]
log level filtering/output is a property of the handler, not the logger
