### ISSUE TITLE
x/build: longtest extra slowbot runs should count against prequal

### ISSUE THREAD

**Issue by thanm** [golang/go#62476]
For a recent [CL](https://go-review.git.corp.google.com/c/go/+/526115), I kicked off the LUCI trybots and requested an additional slowbot run for the linux-amd64-longtest builder.

I noticed that I got an "all checks passed" email from LUCI before the longtest slowbot run had completed-- it seems that the additional slowbot runs are decoupled from conditions used to decide whether the CL passes prequal, which is a little different from the way things worked pre-LUCI. 

It would be nice to have a way to tell LUCI something to the effect of "don't add prequal +1 to this CL unless a specific set of slowbots also pass" (this is especially important for things like cmd/go CLs or linker CLs that touch arch-specific code).

Thanks.

cc @golang/release

**Comment by heschi** [comment]
Looks like the way to do this is to specify `Cq-Include-Trybots:` in the CL description. You can go through the "Choose Tryjobs" interface, then copy the line at the bottom of the dialog box into the description. Does that work for you? The advantage is that you don't have to remember to do it at each patchset.

**Comment by thanm** [comment]
Thanks that recipe SGTM, thanks (don't think I would have discovered that on my own).

I see from the docs for `Cq-Include-Trybots:`

```
The format for specifying the list of builders is
project/bucket:builder1,builder2;another_proj/bucket: builder3.
```

So for our case, what should I fill in for project and bucket? Builder I assume should be "linux-amd64-longtest"? Or should it be "gotip-linux-amd64-longtest"?

**Comment by thanm** [comment]
Ah never mind, I see what you mean now, with the business of using the dialog box. yeah, that seems like it should work.

**Comment by heschi** [comment]
This seems like a reasonable result; if there's more to do feel free to reopen.
