### ISSUE TITLE
flag/flag: There is a BUG in flag when analyzing the bool pointer value

### ISSUE THREAD

**Issue by 20yyq** [golang/go#62491]
There is a BUG in flag when analyzing the bool pointer value. The space format parameter is not fully supported

**Comment by 20yyq** [comment]
flag.BoolVar(&ext, "ext1", false, "ext usage bool")
	flag.BoolVar(&ext1, "ext2", false, "ext usage bool")
	flag.UintVar(&id, "id", 0, "id usage uint")
	flag.StringVar(&data1, "data", "", "data usage string")
	flag.Parse()
	fmt.Println("flag arg ", ext, ext1, flag.Args())
	fmt.Println("os.Args ", os.Args)

Output：
root@Eacher:/system/test/vcan# go run test.go -ext1 false -ext2 true -id 123124 -data string
flag arg  true false [false -ext2 true -id 123124 -data string]
os.Args  [/tmp/go-build11580025/b001/exe/test -ext1 false -ext2 true -id 123124 -data string]

**Comment by seankhliao** [comment]
Boolean flags are intentionally designed to only allow `-f`, `-f=true`, `-f=false` to avoid any parsing ambiguity
