### ISSUE TITLE
x/crypto/ssh: EOF is received before all data is read

### ISSUE THREAD

**Issue by gopherbot** [golang/go#6250]
by **JeanSebTr**:

<pre>That happen reading the server side of a channel.

If EOF is received before all the data have been read, Channel.Read will only return EOF
without the rest of the data.

See
<a href="https://code.google.com/r/jeansebtr-crypto-ssh/source/diff?spec=svn877906a89475f2f09694e4ccc1f70d970cd58590&amp">https://code.google.com/r/jeansebtr-crypto-ssh/source/diff?spec=svn877906a89475f2f09694e4ccc1f70d970cd58590&amp</a>;old=07e1b9edd3f09884b4c1139494960cdfd42dad42&amp;r=877906a89475f2f09694e4ccc1f70d970cd58590&amp;format=unidiff&amp;path=%2Fssh%2Fchannel.go
for a naive fix.</pre>

**Comment by hanwen** [comment]
this is from before the big rewrite. I think this can be closed.

@ianlancetaylor

**Comment by ianlancetaylor** [comment]
@hanwen I just gave you the ability to close issues yourself.  Let me know if it doesn't work.
