### ISSUE TITLE
x/tools/go/analysis/passes/shadow: unexpected type compatibility failure

### ISSUE THREAD

**Issue by shawndx** [golang/go#62519]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.13 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
No, the latest go1.20/21/tip works fine, go1.18/19 is broken (didn't check older releases). 

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOVCS=""
GOVERSION="go1.19.13"
GCCGO="/usr/bin/gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
</pre></details>

### What did you do?

 
go binary set to the latest go1.19.13
% go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow@v0.13.0
% cd <go1.19 root>/src/crypto
% go vet -vettool=[path to shadow] $(go list ./...)

### What did you expect to see?
No error, or just shadow warnings.

### What did you see instead?

A couple of type-checking errors, bitsecting points to the following CL that introduced the behavior change.

```
commit 7e1bfe8bc98ca8e94b7853eca0993bc9ee369101
Author: Alan Donovan <adonovan@google.com>
Date:   Sun Jul 16 13:14:42 2023 -0400

    go/analysis/unitchecker: Example of separate analysis
```

type-checking errors:

```
# crypto/ecdsa
shadow: ecdsa/ecdsa.go:127:12: cannot use asn1.SEQUENCE (constant 48 of type "golang.org/x/crypto/cryptobyte/asn1".Tag) as "vendor/golang.org/x/crypto/cryptobyte/asn1".Tag value in argument to b.AddASN1
# crypto/ecdsa
shadow: ecdsa/ecdsa.go:127:12: cannot use asn1.SEQUENCE (constant 48 of type "golang.org/x/crypto/cryptobyte/asn1".Tag) as "vendor/golang.org/x/crypto/cryptobyte/asn1".Tag value in argument to b.AddASN1
# crypto/rsa
```

**Comment by cherrymui** [comment]
cc @adonovan @timothy-king @matloob @zpavlinovic

**Comment by timothy-king** [comment]
Something suspicious is:
> "golang.org/x/crypto/cryptobyte/asn1".Tag

vs 

> "vendor/golang.org/x/crypto/cryptobyte/asn1".Tag

**Comment by adonovan** [comment]
Thanks for the very helpful bug report; I can reproduce the problem locally with go1.19.5. The code change looks like a no-op, but it's clear that it has changed the vendoring behavior (the subtle difference between "import path" and "package path"). Still investigating...
