### ISSUE TITLE
vscode: multi module support vs single project root setup

### ISSUE THREAD

**Issue by krinklesaurus** [golang/go#62538]
Hi,
my vscode's project root is my home folder `/Users/krinklesaurus` right now and my GOPATH is set to `/Users/krinklesaurus/go`

my workspace file just has `.` as the project's root

	"folders": [
		{
			"path": "."			
		}
	],

Unfortunately, none of the workspace setups described here https://github.com/golang/tools/blob/master/gopls/doc/workspace.md is working for me.

It looks like `go.work` always needs to be at the project's root and that messes up my setup completely.

* opening a single module as a new vscode project is working, but this keeps me from browsing between multiple modules. I want to browse between all modules I have, even unrelated modules, even folders that are not even go related, for code snippet lookup etc.)
* adding a `go.work` file to my home folder pointing to a module like `/Users/krinklesaurus/go/src/github.com/krinklesaurus/my-project` works, but if I add all of my modules there, they all need to be build together
* adding multiple root folders to my workspace also forces me to use a nav tree in my workspace panel I don't want

I'm just confused by how gopls and `go.work` files enforce how I have to use vscode at that point. why can I not just have a `go.work` file in my module's root (`/Users/krinklesaurus/go/src/github.com/krinklesaurus/my-project`) and that's it? Or, have a `go.work` file in my home directory (which I use as project root) and define muiple workspaces in there. I feel like I have the most simplistic workspace setup you can have but it's just not supported and I don't understand why 🤷

**Comment by seankhliao** [comment]
go.work defines the root of a collection of modules (a workspace), affecting how packages are processed both for go tooling itself and gopls. it doesn't make sense for any go tooling to cross workspace boundaries.
