### ISSUE TITLE
net/http:RemoteAddr returned a value error when running locally

### ISSUE THREAD

**Issue by Tiper-In-Github** [golang/go#62548]
### What version of Go are you using (`go version`)?

<pre>
>go version
go version go1.20 windows/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<pre>
set GO111MODULE=on
set GOARCH=amd64
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows

</pre>

### What did you do?

<pre>
request.RemoteAddr
</pre>
I found this issue during local testing, and when I tried to obtain RemoteAddr locally, its results were very uncertain. There is a probability of the problem occurring when I rerun the program or make file changes to restart the program.
When executed locally, its return value should be fixed and unchanging, but in fact, it has a probability of unexpected results

### What did you expect to see?
127.0.0.1:port

### What did you see instead?
[::1]:port  OR  127.0.01:port

**Comment by seankhliao** [comment]
working as expected, both are addresses for localhost

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by Tiper-In-Github** [comment]
> working as expected, both are addresses for localhost
> 
> Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.
> 
> For questions please refer to https://github.com/golang/go/wiki/Questions

Okay, thank you for your reply. Additionally, your personal website is really cool
