### ISSUE TITLE
access: may-start-trybots

### ISSUE THREAD

**Issue by mauri870** [golang/go#62550]
See https://go.dev/wiki/GerritAccess

I'd like to request `may-start-trybots` permission in order to trigger builds for my CLs. This will enable me to test changes before submission, reducing the need for Go maintainers' involvement and the back-and-forth process, especially when builds encounter issues that require subsequent review after my fixes.

Thanks in advance!

Gerrit user: https://go-review.googlesource.com/q/author:mauri870@gmail.com

**Comment by mauri870** [comment]
cc @golang/release

**Comment by mauri870** [comment]
@gopherbot add NeedsDecision

**Comment by heschi** [comment]
Hi @mauri870,

Thank you for your contributions and for requesting Trybots access! I've added you to the may-start-trybots group, so you should be able to do so now.

As you've likely read at https://golang.org/wiki/GerritAccess#trybot-access-may-start-trybots, please be sure to at least skim CLs before starting a Trybot run.

Let us know if you have any questions or issues with it, and thanks again!
