### ISSUE TITLE
affected/package: flag

### ISSUE THREAD

**Issue by Rui-Gan** [golang/go#62561]
### What version of Go are you using (`go version`)?

<pre>
$ go version 
go version go1.21.1 linux/arm64
</pre>

### Does this issue reproduce with the latest release?
yes, it does.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/root/.cache/go-build'
GOENV='/root/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_arm64'
GOVCS=''
GOVERSION='go1.21.1'
GCCGO='gccgo'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='0'
GOMOD='/go/cli/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2511941237=/tmp/go-build -gno-record-gcc-switches'

</pre></details>

### What did you do?

```
package main

import (
	"flag"
	"fmt"
)

func main() {
	rule := flag.String("ruleJson", "", "rule JSON representation")
	flag.Parse()
	fmt.Printf("rule json：%s\n", *rule)

}

```

### What did you expect to see?
<pre>
$ go run main.go -ruleJson='{"sql": "SELECT *, lower('abc') FROM demo"}'
rule json: {"sql": "SELECT *, lower('abc') FROM demo"}
</pre>

### What did you see instead?
<pre>
$ go run main.go -ruleJson='{"sql": "SELECT *, lower('abc') FROM demo"}'
rule json: {"sql": "SELECT *, lower(abc) FROM demo"}
</pre>

I would like to know if this result is in line with community expectations. Personally, I feel that the generated string is counterintuitive and seems like a bug.

**Comment by gophun** [comment]
This is how quoting in the shell works, and it's not related to Go:

```
$ echo '{"sql": "SELECT *, lower('abc') FROM demo"}'
{"sql": "SELECT *, lower(abc) FROM demo"}
```

**Comment by Rui-Gan** [comment]
ok, thank you😁
