### ISSUE TITLE
go get -u is wrong when in go.work

### ISSUE THREAD

**Issue by yangyile1990** [golang/go#62567]
project A
project B
go.work

when in project A, go get -u ./...  OK.
when in project B, go get -u ./...  wrong. because in B import A. while A is not in github. it is just a project, not in any lab.

**Comment by seankhliao** [comment]
working as intended, get is there to retrieve remote dependencies.

**Comment by yangyile1990** [comment]
while I still need upgrade the deps.

because there are some other deps.

my solution is to update the direct modules one by one.

but I think you can skip it with some flag.

thank you.

**Comment by ddkwork** [comment]
I think go work need add a command as "update all" for all module

**Comment by wolverian** [comment]
This is confusing me too. How do I update the dependencies of a workspace module when `go get -u` gives me errors for all the dependencies to the other workspace modules? (`package <dep> is not in std`)
