### ISSUE TITLE
proxy.golang.org: github.com/eclipse-kanto/suite-connector@v0.1.0-M3

### ISSUE THREAD

**Issue by ozblumen** [golang/go#62566]
Hi guys,

Thanks a lot,  for your dedication & support, it is really appreciated 🙏 

I'm using the golang proxy in order to get some metadata of OSS packages.
For example, I've tried to find the following package using the proxy info API:
https://proxy.golang.org/github.com/eclipse-kanto/suite-connector/@v/v0.1.0-m3.info

I'm getting the following error:
not found: github.com/eclipse-kanto/suite-connector@v0.1.0-m3: invalid version: unknown revision v0.1.0-m3

When I get to GH repo of this package I can see the following tag exists:
https://github.com/eclipse-kanto/suite-connector/releases/tag/v0.1.0-M3

Can you guide me what I am missing please ?

Thanks again.

**Comment by seankhliao** [comment]
https://go.dev/ref/mod#module-cache

> Capital letters in module paths and versions are escaped using exclamation points (Azure is escaped as !azure) to avoid conflicts on case-insensitive file systems.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
