### ISSUE TITLE
context: Cause does not return Err for a custom context

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#62582]
The documentation for [`context.Cause`](https://pkg.go.dev/context#Cause) says that if a context was canceled other than via a call to `CancelCauseFunc`, then "`Cause(c)` returns the same value as `c.Err()`".  However, that is not true today for a custom context.  CC @Sajmani 

Here is a test:

```Go
// customCauseContext is a custom Context used to test context.Cause.
type customCauseContext struct {
	mu   sync.Mutex
	done chan struct{}
	err  error
}

func (ccc *customCauseContext) Deadline() (deadline time.Time, ok bool) {
	return
}

func (ccc *customCauseContext) Done() <-chan struct{} {
	ccc.mu.Lock()
	defer ccc.mu.Unlock()
	return ccc.done
}

func (ccc *customCauseContext) Err() error {
	ccc.mu.Lock()
	defer ccc.mu.Unlock()
	return ccc.err
}

func (ccc *customCauseContext) Value(key any) any {
	return nil
}

func (ccc *customCauseContext) cancel() {
	ccc.mu.Lock()
	defer ccc.mu.Unlock()
	ccc.err = context.Canceled
	close(ccc.done)
}

func TestCustomContextCause(t *testing.T) {
	ccc := customCauseContext{
		done: make(chan struct{}),
	}
	ccc.cancel()
	if got := ccc.Err(); got != context.Canceled {
		t.Errorf("ccc.Err() = %v, want %v", got, context.Canceled)
	}
	if got := context.Cause(&ccc); got != context.Canceled {
		t.Errorf("Cause(ccc) = %v, want %v", got, context.Canceled)
	}
}
```

This fails with

```
--- FAIL: TestCustomContextCause (0.00s)
    foo_test.go:53: Cause(ccc) = <nil>, want context canceled
```

**Comment by nightlyone** [comment]
Should that be backported to Go 1.20 where this behaviour has been introduced or is there a possible workaround for that issue that I am missing to see?

**Comment by ianlancetaylor** [comment]
It's kind of an edge case: code that has a custom `Context` type and calls `context.Cause` on that type.  There isn't a lot of reason to call `context.Cause` on a `Context` that wasn't created by `context.WithCancelCause`, and by definition that does not return a custom context.  So this issue doesn't seem to meet the requirements outlined at https://go.dev/wiki/MinorReleases.  Happy to hear counter-arguments.

**Comment by colega** [comment]
> It's kind of an edge case: code that has a custom Context type and calls context.Cause on that type.

I don't think it's such an edge case. I hit this while working on a library that does some intensive work and regularly checks for the context cancellation with `if err := context.Cause(ctx); err != nil {`.

The library doesn't know the type of the context that it has been provided, so in the case of a custom context it won't detect its cancellation and will keep executing.
