### ISSUE TITLE
encoding/csv: LazyQuotes option breaks if the fields are quoted and the lazy quotes appear at the end of the field

### ISSUE THREAD

**Issue by gopherbot** [golang/go#6258]
by **alex@zylman.com**:

<pre>What steps will reproduce the problem?
Try to read a CSV file where the fields are quoted and one of them ends in something
that would need lazy quotes, e.g.
&quot;Field1&quot;,&quot;Field2
&quot;LazyQuotes&quot;&quot;,&quot;Field3&quot;,&quot;Field4&quot;

What is the expected output?
[&quot;Field1&quot;, &quot;Field2 \&quot;Lazy Quotes\&quot;&quot;, &quot;Field3&quot;,
&quot;Field4&quot;]
Basically, an array of length 4, one for each field, with the lazy quotes in place.

What do you see instead?
[&quot;Field1&quot;, &quot;Field2 \&quot;LazyQuotes\&quot;,\&quot;Field3&quot;,
&quot;Field4&quot;]
An array of length 3, where it smashed Field2 and Field3 together.

Which compiler are you using (5g, 6g, 8g, gccgo)?
Whatever the default is from <a href="https://code.google.com/p/go/downloads/list">https://code.google.com/p/go/downloads/list</a>

Which operating system are you using?
Mac OS X 10.8

Which version are you using?  (run 'go version')
go version go1.1 darwin/amd64

Please provide any additional information below.
I've attached a .tar.gz that contains four .csv files and a Go program that reads them
and prints them.
Two of them files have quoted fields show lazy quotes in the middle of a field
(inp_quoted_end.csv) and at the end of a field (inp_quoted.csv), and two are the same
thing but unquoted fields (inp_unquoted_end.csv, inp_unquoted.csv, respectively). Only
the quoted fields with lazy quotes at the end break (inp_quoted.csv).</pre>

Attachments:
1. <a href="https://storage.googleapis.com/go-attachment/6258/0/broken_lazy_quotes.tar.gz">broken_lazy_quotes.tar.gz</a> (487754 bytes)

**Comment by nussjustin** [comment]
This could be fixed for the simple case by peeking ahead for the next rune after a lazy quote, but I don't think this is really possible to fix in a simple and consistent way for all cases. I don't think this is really worth fixing.

The issue author originally wrote that 

> if this is a feature request and not a bug, then there's a bug in the
documentation since it says this works. :/

But I can't find anything about this case in the documentation. There is a case with a double-quoted word in a non-lazy quoted field, but nothing about a lazy quoted case.

**Comment by dsnet** [comment]
I agree that this can't really be fixed. There is an infinite number of edge cases where `LazyQuotes` will fail. The current rules it follows in simple. Anything that starts to require peeking from the incoming stream is probably heading down the wrong direction. Secondly, subtle changes to `LazyQuotes` has massive effects on how files are parsed and would break compatibility. So probably not worth "fixing".
