### ISSUE TITLE
x/tools/go/types: New needs to be able to use imports

### ISSUE THREAD

**Issue by robpike** [golang/go#6259]
<pre>types.New lets you write:

types.New(&quot;interface{ Error() string }&quot;)

but not

types.New(&quot;interface{Format(f fmt.State, c rune)}&quot;)

because fmt is not defined in the universe scope.

New would be much more useful if one could provide it (or some companion function) a
list of imports.</pre>

**Comment by griesemer** [comment]
- types.New is problematic for various reason and we are planning to remove it.
- cmd/vet is not relying on types.New anymore but does the actual import and lookup needed.

Will not fix.
