### ISSUE TITLE
go called a wrong interface method implementation in a class hierarchy

### ISSUE THREAD

**Issue by xujintao** [golang/go#62608]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/pi/.cache/go-build"
GOENV="/home/pi/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/pi/go/pkg/mod"
GONOPROXY="git.mycompany.com,github.com/my/private"
GONOSUMDB="git.mycompany.com,github.com/my/private"
GOOS="linux"
GOPATH="/home/pi/go"
GOPRIVATE="git.mycompany.com,github.com/my/private"
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2635587169=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```
type barer interface {
	bar()
}

type base struct {
	barer
}

func (b *base) foo() {
	print("foo call: ")
	b.bar()
}

func (b *base) bar() {
	println("base bar")
}

type derive1 struct {
	base
}

func (d *derive1) bar() {
	println("derive1 bar")
}

type derive2 struct {
	base
}

func (d *derive2) bar() {
	println("derive2 bar")
}

func main() {
	var d1 derive1
	d1.barer = &d1
	var d2 derive2
	d2.barer = &d2

	bases := []*base{&d1.base, &d2.base}
	for _, b := range bases {
		b.foo()
	}
}
```

### What did you expect to see?
foo call: derive1 bar
foo call: derive2 bar

### What did you see instead?
foo call: base bar
foo call: base bar

**Comment by seankhliao** [comment]
working as intended.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
