### ISSUE TITLE
x/pkgsite: package removal request for github.com/mend-toolkit/mend-log-parser/*

### ISSUE THREAD

**Issue by kyallanum-MND** [golang/go#62602]
### What is the path of the package that you would like to have removed?
github.com/mend-toolkit/mend-log-parser/bll
github.com/mend-toolkit/mend-log-parser/models
github.com/mend-toolkit/mend-log-parser/utils

### Are you the owner of this package?
Yes

### What is the reason that you could not retract this package instead?
All three of these were sub-modules I had on the original package. I removed the submodules as they are only intended to work with this package. Therefore I would like them removed so they don't show on pkg.go.dev. 

I haven't retracted them as they are sub-modules that no longer exist in my go.mod file.

**Comment by seankhliao** [comment]
please use the retract directive, a retraction doesn't need to be published on the main branch, you can recreate the go.mod files on a temporary branch with the appropriate tags.

**Comment by kyallanum-MND** [comment]
@seankhliao I did as you suggested, but I get an error:
```
.\go.mod:14:2: retract github.com/mend-toolkit/mend-log-parser/v23: version "bll/v0.1.0" invalid: version "bll/v0.1.0" invalid: disallowed version string       
.\go.mod:15:2: retract github.com/mend-toolkit/mend-log-parser/v23: version "models/v0.1.0" invalid: version "models/v0.1.0" invalid: disallowed version string 
.\go.mod:16:2: retract github.com/mend-toolkit/mend-log-parser/v23: version "utils/v0.1.0" invalid: version "utils/v0.1.0" invalid: disallowed version string
```

When checking on pkg.go.dev I see [this](https://pkg.go.dev/search?q=mend-log-parser&m=) still.

I'm not supposed to be using the full sub-module name like:
``github.com/mend-toolkit/mend-log-parser/bll``
am I?

**Comment by seankhliao** [comment]
retractions have to be published in the module being retracted, ie:
create `models/go.mod` with:
```
module github.com/mend-toolkit/mend-log-parser/models
retract [v0.0.0-0, v0.2.0]
```
tag the commit with `models/v0.2.0`, and fetch `github.com/mend-toolkit/mend-log-parser/models@v0.2.0`.

Go modules have no concept of nesting.

**Comment by kyallanum-MND** [comment]
@seankhliao looks like this worked. I get retract messages when attempting to fetch them. Thank you.

I do still see them on pkg.go.dev. Is this expected? Or will they be hidden/removed eventually.

**Comment by kyallanum-MND** [comment]
shows as retracted now on pkg.go.dev.
