### ISSUE TITLE
x/vuln: how to troubleshoot HTTP 403

### ISSUE THREAD

**Issue by udhos** [golang/go#62603]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.1 linux/amd64
</pre>

### Does this issue reproduce at the latest version of golang.org/x/vuln?
Yes.

<pre>
govulncheck -version
Go: go1.21.1
Scanner: govulncheck@v1.0.1
DB: https://vuln.go.dev
DB updated: 2023-09-12 17:31:22 +0000 UTC

No vulnerabilities found.

Share feedback at https://go.dev/s/govulncheck-feedback.
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/everton/.cache/go-build'
GOENV='/home/everton/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/everton/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/everton/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go1.21.1.linux-amd64'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go1.21.1.linux-amd64/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.1'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/everton/dev/gateboard/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1705569373=/tmp/go-build -gno-record-gcc-switches'
</pre></details>

### What did you do?

I am running govulncheck behind a corporate proxy and it is hitting HTTP 403.
Unfortunately govulncheck does not show exactly which request was blocked with HTTP 403.
If I had that information I could easily ask my proxy team to whitelist its request.

<pre>
$ mkdir /tmp/test
$ cd /tmp/test
$ go mod init test
go: creating new go.mod: module test
$ cat > main.go
package main
func main() {
}
$ go install ./...
$ go install golang.org/x/vuln/cmd/govulncheck@latest
$ govulncheck ./...
Scanning your code and 0 packages across 0 dependent modules for known vulnerabilities...

unexpected HTTP status code: 403
</pre>

### What did you expect to see?

The exact HTTP request that was denied with HTTP 403.

### What did you see instead?

Only the HTTP 403 status.

<pre>
Scanning your code and 0 packages across 0 dependent modules for known vulnerabilities...

unexpected HTTP status code: 403
</pre>

**Comment by heschi** [comment]
cc @golang/vulndb

**Comment by zpavlinovic** [comment]
There is a CL for providing more info, but my hunch is that the request is to `https://vuln.go.dev`.

**Comment by udhos** [comment]
It worked like a charm for me!

```
go install golang.org/x/vuln/cmd/govulncheck@master

govulncheck ./...
Scanning your code and 42 packages across 0 dependent modules for known vulnerabilities...

HTTP GET https://vuln.go.dev/index/modules.json.gz returned unexpected status: 403 MediaTypeBlockedDlownload
```

Thanks!
