### ISSUE TITLE
runtime/race: update syso files with tsan atomics for And/Or

### ISSUE THREAD

**Issue by mauri870** [golang/go#62624]
In order to implement the race variants for the new sync/atomic And/Or operators proposed in #61395 we need to build new syso files as well as implementing these atomic operations for the llvm thread sanitizer.

I already have a patch under review https://github.com/llvm/llvm-project/pull/65695 that adds support for the new functions, but that is still hanging, awaiting to be merged. I would appreciate it if someone with closer ties to llvm could draw the maintainers attention to it.

Once the patch is merged we need to use [x/build/cmd/racebuild](https://pkg.go.dev/golang.org/x/build/cmd/racebuild) with llvm HEAD to build the new syso files in runtime/race and commit them.

**Comment by mauri870** [comment]
@gopherbot add NeedsFix, RaceDetector

**Comment by mauri870** [comment]
It's worth noting that previous updates to the syso files have caused issues, for example https://github.com/golang/go/issues/37485. Since the race runtimes haven't been recompiled for almost a year we need to be careful when doing so.

**Comment by mauri870** [comment]
The upstream llvm support for the and/or tsan operators was cherry picked as https://github.com/llvm/llvm-project/commit/51bfeff0e4b0757ff773da6882f4d538996c9b04, I'll try to move forward with this as soon as I get gomote access.

**Comment by mauri870** [comment]
cc @cherrymui

**Comment by cherrymui** [comment]
Working on it. Apparently there are a few things needed to be changed in `racebuild`, as the builders and environments changed. Hopefully I'll get this done soon (in a couple of days).

**Comment by mauri870** [comment]
Thanks @cherrymui. Additionally, I remember reading somewhere (I can't seem to find the source now) that some platforms still rely on tsan v2 that don't have these new operators. Can you confirm that? And if so how to proceed? Thanks

Here is what I have on my notes (no source sorry!)

> On 1.19, the race detector has been upgraded to use thread sanitizer version v3 on all supported platforms except `windows/amd64` and `openbsd/amd64`, which remain on v2. Race detector support for `openbsd/amd64` has been removed from thread sanitizer upstream, so it is unlikely to ever be updated from v2.

**Comment by cherrymui** [comment]
@mauri870 good point! windows/amd64 is already updated to v3 (https://go.dev/cl/420197). It is probably true that openbsd will remain v2. On openbsd, is it possible to write the new operations as a CAS loop and just use the CAS operation from TSAN? Thanks

**Comment by mauri870** [comment]
Well it seems like we will have some additional work on openbsd, but it should be possible to have a race_openbsd_amd64.s that uses a tsan CAS, afaik race only works on openbsd/amd64.
