### ISSUE TITLE
affected/package: 

### ISSUE THREAD

**Issue by meklit1311** [golang/go#62634]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.21.1

</pre>

### Does this issue reproduce with the latest release?

no
### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
linux amd64
</pre></details>

### What did you expect to see?

result of go tests

### What did you see instead?
# net/http
/snap/go/10339/src/net/http/server.go:3190:26: internal compiler error: panic: runtime error: index out of range [29] with length 10

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new
FAIL    command-line-arguments [build failed]
FAIL

**Comment by bcmills** [comment]
Please fill out the complete issue template. What is the complete output of the `go env` command? What was the exact command you invoked to run the test?

**Comment by thediveo** [comment]
#62639

**Comment by thediveo** [comment]
might be a snap package error

**Comment by thediveo** [comment]
snap package is working.
