### ISSUE TITLE
misc/pprof: problem with pdf or svg generation

### ISSUE THREAD

**Issue by gopherbot** [golang/go#6263]
by **ma.adameit**:

<pre>What steps will reproduce the problem?
If possible, include a link to a program on play.golang.org.
1. Create .prof file as described in <a href="http://blog.golang.org/profiling-go-programs">http://blog.golang.org/profiling-go-programs</a>
2. go tool pprof test.exe test.prof
3. top10

What is the expected output?
No errors after step 2 and proper output after step 3.

What do you see instead?
After 2. multiple &quot;The system cannot find the file specified&quot;
After 3. no function names, but memory addresses

Which compiler are you using (5g, 6g, 8g, gccgo)?
The default one. &quot;go build&quot;

Which operating system are you using?
Windows 8 64bit

Which version are you using?  (run 'go version')
go version go1.1.2 windows/amd64

Please provide any additional information below.

Compare with <a href="https://code.google.com/p/gperftools/issues/detail?id=317&amp">https://code.google.com/p/gperftools/issues/detail?id=317&amp</a>;redir=1</pre>

**Comment by ALTree** [comment]
It appears the last remaining issue was a bad error on a missing `dot`, but I've just tried and now it says:

> Failed to execute dot. Is Graphviz installed? Error: exec: "dot": executable file not found in %PATH%

which seems clear. Closing here as fixed.
