### ISSUE TITLE
go does not run at all

### ISSUE THREAD

**Issue by meklit1311** [golang/go#62639]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.1 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/meklit/.cache/go-build'
GOENV='/home/meklit/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/meklit/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/meklit/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/snap/go/10339'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/snap/go/10339/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.1'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/meklit/Desktop/mereb/game_backend/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1907575489=/tmp/go-build -gno-record-gcc-switches'
uname -sr: Linux 6.2.0-31-generic
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
gdb --version: GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
</pre></details>

**Comment by bcmills** [comment]
Please fill out the complete issue template. What did you do? What did you expect to see? What did you see instead?

**Comment by thediveo** [comment]
can you please deinstall the go snap package completely and reinstall it again, does the problem persist?

**Comment by thediveo** [comment]
I've upgraded on of my dev systems to the Go snap rev 10339 as the issuer and successfully build and coverage tested one of my projects that pull in some Docker, containerd, and kubernetes stuff. No problems.

The only difference is that I'm on 23.04 and not 22.04.x LTS. However, I don't have any 22.04.x as they turned sour in the past several times before their shell life and getting cloud-related packages for LTS is contrary to common misbelief an adventure that typically doesn't end well in terms of security patches and required function upgrades.
