### ISSUE TITLE
go/ast, go/parser: parse doc/comment for `stmt`

### ISSUE THREAD

**Issue by dugenkui03** [golang/go#62646]
# background
I'd like to analysis the go source code by go parse and get important info represented by File.

But I find that the info of doc/comment will not assign to Stmt.

# proposal
I propose change `Stmt` from
```go
type Stmt interface {
	Node
	stmtNode()
}
```
to 
```go
type Stmt interface {
	Node
	stmtNode()
	SetDoc(*CommentGroup)
	SetComment(*CommentGroup)
}
```

# demo
Code like below:
```go
...

func testFunc() {
	// first lead doc
	sprintf := fmt.Sprintf("%s", 222) // first line comment
	// second lead doc
	print(sprintf) // second line comment
}
...
```
will parse and get `FuncDecl` like that
<img width="628" alt="image" src="https://github.com/golang/go/assets/18216266/5b81be6c-0f0d-4205-a08b-12f4bbdf6fc3">

**Comment by qiulaidongfeng** [comment]
Changing the export API violates the go1 compatibility commitment.

**Comment by qiulaidongfeng** [comment]
Changing the export API violates the go1 compatibility commitment.

**Comment by mvdan** [comment]
This problem has been known for a long time; for example, see https://github.com/golang/go/issues/20744.

@adonovan has a work in progress solution at https://go-review.googlesource.com/c/go/+/429639, although I don't think it has a tracking issue.

Personally, I don't think this proposal is the right approach, and it's not nearly detailed enough to really tell how it would work beyond adding a bit of API.

**Comment by adonovan** [comment]
The previous two comments are correct: we can't change the interface, and we have a different solution for comments (that has been moving slowly but is not forgotten). So I think we must reject this proposal.

**Comment by dugenkui03** [comment]
@qiulaidongfeng Thanks for you remind "go1 compatibility commitment"

@mvdan @adonovan thanks, I will close this issue, and  this proposal should  be continue in t https://go-review.googlesource.com/c/go/+/429639
