### ISSUE TITLE
cmd/go: "missing ziphash" error with go.work

### ISSUE THREAD

**Issue by gbrlsnchs** [golang/go#62663]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/gbrlsnchs/.cache/go-build'
GOENV='/home/gbrlsnchs/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/gbrlsnchs/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/gbrlsnchs/go'
GOPRIVATE=''
GOPROXY='direct'
GOROOT='/usr/lib/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='local'
GOTOOLDIR='/usr/lib/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.1'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='x86_64-pc-linux-gnu-gcc'
CXX='x86_64-pc-linux-gnu-g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build430421167=/tmp/go-build -gno-record-gcc-switches'
</pre></details>

### What did you do?

1. Clone https://github.com/siderolabs/talos/tree/v1.5.2
2. In the project root, run `go mod verify`

### What did you expect to see?

```console
$ go mod verify
all modules verified
```

### What did you see instead?

```console
$ go mod verify
module-sig-verify : missing ziphash: open hash: no such file or directory
```

---

This is a follow up to https://github.com/golang/go/issues/54372#issuecomment-1721444989. Note that the project used for testing contains a `go.work` file.

**Comment by heschi** [comment]
cc @bcmills @matloob @rsc

**Comment by matloob** [comment]
@gopherbot please open backport issues

**Comment by matloob** [comment]
We want to create backports for this because there was a regression in the behavior of go mod verify in workspaces in go 1.21.
