### ISSUE TITLE
affected/package: strings

### ISSUE THREAD

**Issue by VarusHsu** [golang/go#62677]
Is there a wrong comment about strings.TrimSpace ?

### What version of Go are you using (`go version`)?
go 1.21
<pre>
$ go version
go 1.21
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
MacOS 
<details><summary><code>go env</code> Output</summary><br><pre>

</pre></details>

It's not a bug but maybe it will misslead golang newer.
```
// TrimSpace returns a slice of the string s, with all leading
// and trailing white space removed, as defined by Unicode.
func TrimSpace(s string) string {
```

**Comment by seankhliao** [comment]
it's a necessary detail as it means both strings will reference the same backing array (important in deciding if it can be gc'ed)

**Comment by VarusHsu** [comment]
@seankhliao Oh Thanks, after your answer. I suddenly understand what author want to explain.
