### ISSUE TITLE
runtime: bsdthread_register error on macOS 12.6.9

### ISSUE THREAD

**Issue by taojiaenx** [golang/go#62686]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.21.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes. I have tried updating go to the latest version, as well as updating to the latest of xcode and command tools. Also ran brew upgrade to make sure everything is updated. Also tried diffrent shells to see if that makes any difference.
I am also running the latest version of docker.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
```bash
GO111MODULE='on'
GOARCH='amd64'
GOBIN=''
GOCACHE='/Users/xietangtao/Library/Caches/go-build'
GOENV='/Users/xietangtao/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/usr/local/go/bin/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/usr/local/go/bin'
GOPRIVATE=''
GOPROXY='https://goproxy.cn'
GOROOT='/usr/local/Cellar/go/1.21.1/libexec'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/Cellar/go/1.21.1/libexec/pkg/tool/darwin_amd64'
GOVCS=''
GOVERSION='go1.21.1'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/ds/40g_rxwj4lb2mvw2bqcrm2hh0000gn/T/go-build3912756394=/tmp/go-build -gno-record-gcc-switches -fno-common'
```
</pre></details>

### What did you do?

When running the following command to connect to a server running docker it produces the error. It does not matter if the server is hosted on AWS EC2 or Digital Ocean droplets.

It seems this issue is not related just to Docker, as I am also getting this error when running a command in the terminal inside of Mac OS.
```
eval "$(docker-machine env machinegoeshere)"
```

### What did you expect to see?

Usually nothing displays which indicates its connected to the server

### What did you see instead?

```
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x205dfa5, 0x21)
	/usr/local/go/src/runtime/panic.go:619 +0x81 fp=0x7ff7bfeff468 sp=0x7ff7bfeff448 pc=0x1029751
runtime.goenvs()
	/usr/local/go/src/runtime/os_darwin.go:129 +0x83 fp=0x7ff7bfeff498 sp=0x7ff7bfeff468 pc=0x10272d3
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:496 +0xa4 fp=0x7ff7bfeff4f0 sp=0x7ff7bfeff498 pc=0x102c014
runtime.rt0_go(0x7ff7bfeff528, 0x3, 0x7ff7bfeff528, 0x0, 0x1000000, 0x3, 0x7ff7bfeff6e8, 0x7ff7bfeff6f7, 0x7ff7bfeff6fb, 0x0, ...)
	/usr/local/go/src/runtime/asm_amd64.s:252 +0x1f4 fp=0x7ff7bfeff4f8 sp=0x7ff7bfeff4f0 pc=0x1052c64
```

**Comment by seankhliao** [comment]
is your docker-machine command built locally?

**Comment by taojiaenx** [comment]
Yes I executed eval on macOS terminal.

**Comment by seankhliao** [comment]
that's not what I asking, how did you get the docker-machine binary built?

**Comment by cherrymui** [comment]
See https://github.com/golang/go/wiki/MacOS12BSDThreadRegisterIssue . Your docker or a program it invokes must be built with an old version of Go. See also #49425, where a few candidate of old programs were mentioned. Thanks.

**Comment by cherrymui** [comment]
@taojiaenx you ran into this because some binary that your command invokes is built with a very old version of Go. You need to find what binary that is, and rebuild it. Does docker have a verbose/debug mode that prints all the commands it invokes? If so, that could be helpful.

This is not a bug in Go, and unfortunately we couldn't help resolve your problem.
