### ISSUE TITLE
os: TestMkdirStickyUmask failed in github code space

### ISSUE THREAD

**Issue by qiulaidongfeng** [golang/go#62684]
### What version of Go are you using (`go version`)?

<pre>
$ go version
tip
</pre>

### Does this issue reproduce with the latest release?
yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/codespace/.cache/go-build"
GOENV="/home/codespace/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/workspaces/go/src/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build17331257=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

cd src
./all.bash

### What did you expect to see?

Test passed.

### What did you see instead?
--- FAIL: TestMkdirStickyUmask (0.00s)
    os_unix_test.go:271: unexpected mode dtrwxr-xr--
FAIL    os      0.691s

**Comment by bcmills** [comment]
I suspect that this is an ACL problem.

Per https://man7.org/linux/man-pages/man2/umask.2.html:
> if the parent directory has a default ACL (see [acl(5)](https://man7.org/linux/man-pages/man5/acl.5.html)), the umask is ignored, the default ACL is inherited, the permission bits are set based on the inherited ACL, and permission bits absent in the mode argument are turned off.

**Comment by qiulaidongfeng** [comment]
The test has been fixed.
