### ISSUE TITLE
x/telemetry: telemetry fails if certain config directories do not exist 

### ISSUE THREAD

**Issue by findleyr** [golang/go#62706]
Just observed when working with telemetry on a new computer: with a fresh environment, local telemetry collection doesn't work. From experimentation, it appears not to work until I manually create the `~/.config/go/telemetry/local` directory.

This looks like a bug: the necessary directories should be created as necessary. It looks like this isn't caught in testing because the requisite directories are created during setup:
https://github.com/golang/telemetry/blob/46be8a514e945b237ab6f8c82bef65a4dbbf6ebd/internal/counter/counter_test.go#L554

CC @pjweinb @hyangah

**Comment by pjweinb** [comment]
more information would help. All of the calls to Mkdir in the telemetry
module are os.MkdirAll or os.MkdirTmp
