### ISSUE TITLE
cmd/go: go clean can make go unusable

### ISSUE THREAD

**Issue by fasmat** [golang/go#62718]
### What version of Go are you using (`go version`)?

I was using 1.21.0 with toolchain 1.21.1

<pre>
$ go version
bash: /go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.1.linux-arm64/bin/go: No such file or directory
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
bash: /go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.1.linux-arm64/bin/go: No such file or directory
</pre></details>

### What did you do?

I was using go 1.21.0 and updated to 1.21.1 using the new `go get go@1.21.1` option to do so. Afterwards I ran `go clean -cache -modcache`. Now any `go` command returns the error above complaining about the missing toolcain.

### What did you expect to see?

Not sure, probably `go` using 1.21.0 if the installed toolchain was removed.

### What did you see instead?

The `go` command broke.

**Comment by fasmat** [comment]
Closing my shell and opening a new one seems to have fixed the issue:

```
$ go version
go: downloading go1.21.1 (linux/arm64)
go version go1.21.1 linux/arm64
```

**Comment by seankhliao** [comment]
sounds like your shell is caching something it shouldn't be

**Comment by dolmen** [comment]
This issue lacks information:
* is `go env` launched from a tree with a go.mod? What is the content of that `go.mod`?
* output of `which go`
