### ISSUE TITLE
os/user: TestGroupIds fails in Windows Server Core container

### ISSUE THREAD

**Issue by corhere** [golang/go#62712]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.1 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\ContainerAdministrator\AppData\Local\go-build
set GOENV=C:\Users\ContainerAdministrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.21.1
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\ContainerAdministrator\AppData\Local\Temp\go-build269861932=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

```
docker run --rm -it golang:1.21.1-windowsservercore-ltsc2022 go test os/user
```

### What did you expect to see?
```
ok  	os/user	1.005s
```

### What did you see instead?
```
--- FAIL: TestGroupIds (0.13s)
    user_test.go:178: &{Uid:S-1-5-93-2-1 Gid:S-1-5-93-2-1 Username:User Manager\ContainerAdministrator Name:ContainerAdministrator HomeDir:C:\Users\ContainerAdministrator}.GroupIds(): The user name could not be found.
FAIL
FAIL    os/user 2.044s
FAIL
```

Through a liberal sprinkling of `println()` I have confirmed that the error is returned from the `NetUserGetLocalGroups()` call, same as #26041. I also tried forcing use of the fully-qualified user name `User Manager\ContainerAdministrator` as the query despite `isDomainJoined() = (false, nil)` with the same result.

The os/user tests do pass inside a container if a local user is created inside the container and the `go test` command run under that user. The issue only manifests with the `ContainerAdministrator` and `ContainerUser` [default user accounts](https://learn.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-security#when-to-use-containeradmin-and-containeruser-user-accounts).

**Comment by bcmills** [comment]
(attn @golang/windows)
