### ISSUE TITLE
syscall: TestDeathSignal failed in github code space.

### ISSUE THREAD

**Issue by qiulaidongfeng** [golang/go#62719]
### What version of Go are you using (`go version`)?

<pre>
$ go version
tip
</pre>

### Does this issue reproduce with the latest release?

yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/root/.cache/go-build'
GOENV='/root/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/workspaces/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/workspaces/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='devel go1.22-ee788dba Sat Sep 9 01:48:44 2023 +0000'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/workspaces/go/src/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2757108754=/tmp/go-build -gno-record-gcc-switches'
</pre></details>

### What did you do?
Fork golang/go in github, see https://docs.github.com/en/codespaces/developing-in-codespaces/creating-a-codespace-for-a-repository Create a code space.
See also https://docs.github.com/en/codespaces/developing-in-codespaces/opening-an-existing-codespace Open the code space.
cd src
./all.bash

### What did you expect to see?

Test passed.

### What did you see instead?

death signal parent error: fork/exec /tmp/TestDeathSignal3458263251/syscall.test: permission denied
--- FAIL: TestDeathSignal (0.00s)
    exec_pdeathsig_test.go:97: did not receive start from child, received "", EOF
FAIL
FAIL    syscall 1.447s

**Comment by bcmills** [comment]
This is one of the tests that was also failing on the LUCI builders and was skipped in https://go.dev/cl/513779 (CC @dmitshur @heschi).

As I commented on that CL:
> I suspect that the real problem in this case is that the `deathSignalParent` function hard-codes a specific UID and GID that probably don't apply in a chroot:
> https://cs.opensource.google/go/go/+/master:src/syscall/exec_pdeathsig_test.go;l=111-113;drc=2ad666dea0490305bb7fd2dd6e7beb767acfd2c3
>
> Probably the test should be changed to look up the actual UID and GID for `nobody`, and should skip the test if that lookup fails.

@qiulaidongfeng, want to send a CL implementing that approach?

**Comment by qiulaidongfeng** [comment]
Yes, I will send the CL after repairing the test failure according to your method.

---Original---
From: "Bryan C. ***@***.***&gt;
Date: Tue, Sep 19, 2023 22:09 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [golang/go] syscall: TestDeathSignal failed in github code space.(Issue #62719)




 
This is one of the tests that was also failing on the LUCI builders and was skipped in https://go.dev/cl/513779 (CC @dmitshur @heschi).
 
As I commented on that CL:
  
I suspect that the real problem in this case is that the deathSignalParent function hard-codes a specific UID and GID that probably don't apply in a chroot:
 https://cs.opensource.google/go/go/+/master:src/syscall/exec_pdeathsig_test.go;l=111-113;drc=2ad666dea0490305bb7fd2dd6e7beb767acfd2c3
 
Probably the test should be changed to look up the actual UID and GID for nobody, and should skip the test if that lookup fails.
  
@qiulaidongfeng, want to send a CL implementing that approach?
