### ISSUE TITLE
x/pkgsite: github.com/JetBrains/qodana-cli is not the latest version

### ISSUE THREAD

**Issue by tiulpin** [golang/go#62720]
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/JetBrains/qodana-cli

### What is your user agent?

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15
```

### What did you do?

I checked the page with my browser, and also, tried installing the package with `go install ...`

### What did you expect to see?

Expected to see the latest version of the package. And be able to install it with `go install ...`

### What did you see instead?

v1.1.1, while the latest version published is https://github.com/JetBrains/qodana-cli/releases/tag/v2023.2.6

**Comment by seankhliao** [comment]
working as intended, repo doesn't follow go's major version suffix for semver

**Comment by tiulpin** [comment]
@seankhliao thanks for mentioning and a quick reply. Fixed the module definition.

For anyone else reading this issue in the future and figuring out how to fix that: https://go.dev/doc/modules/release-workflow#breaking
