### ISSUE TITLE
x/pkgsite: package removal request for codeberg.org/lhinderberger/* and github.com/lhinderberger/*

### ISSUE THREAD

**Issue by lhinderberger** [golang/go#62739]
### What is the path of the package that you would like to have removed?
All packages with the prefixes codeberg.org/lhinderberger and github.com/lhinderberger

### Are you the owner of this package?
Yes.

### What is the reason that you could not retract this package instead?
I did retract my packages, but they still show up when searching on pkg.go.dev (with a "Retracted" banner).

Please remove my packages from search, and from the site entirely. Thank you!

**Comment by findleyr** [comment]
I believe this is done.
