### ISSUE TITLE
x/pkgsite: package removal request for open.boneffect.de/libs/vcsaccess

### ISSUE THREAD

**Issue by lhinderberger** [golang/go#62738]
### What is the path of the package that you would like to have removed?
open.boneffect.de/libs/vcsaccess

### Are you the owner of this package?
Yes.

### What is the reason that you could not retract this package instead?
I have retracted the package, but it still shows up when searching for it on pkg.go.dev (with a "Retracted" banner).

Please remove the package from search as well, and from the site entirely. Thank you!

**Comment by findleyr** [comment]
This is done, and should take effect within an hour or so.
