### ISSUE TITLE
interfaces: Can't cast if method name matches struct name on embedded struct

### ISSUE THREAD

**Issue by Naatan** [golang/go#62735]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.3 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes (reproduced on go playground)

### What operating system and processor architecture are you using (`go env`)?

Irrelevant, reproduced on go playground.

### What did you do?

```
package main

import (
	"errors"
	"fmt"
)

type errorReporter interface {
	error
	report() string
}

type reportWrapped struct {
	*report
}

type report struct {
	error
}

func (c *report) report() string { return "" }

type customErrorWrapped struct {
	*customError
}

type customError struct {
	error
}

func (c *customError) report() string { return "" }

func main() {
	{
		var err error = &customError{errors.New("foo")}
		_, ok := err.(errorReporter)
		fmt.Printf("Custom: %v\n", ok)
	}

	{
		var err error = &customErrorWrapped{&customError{errors.New("foo")}}
		_, ok := err.(errorReporter)
		fmt.Printf("Wrapped Custom: %v\n", ok)
	}

	{
		var err error = &report{errors.New("foo")}
		_, ok := err.(errorReporter)
		fmt.Printf("Report: %v\n", ok)
	}

	{
		var err error = &reportWrapped{&report{errors.New("foo")}}
		_, ok := err.(errorReporter)
		fmt.Printf("Wrapped Report: %v\n", ok)
	}
}
```

See: https://go.dev/play/p/NGI2vPyYymd

### What did you expect to see?

All of the prints should print a `true`.

### What did you see instead?

The last one is false. The only difference between this one and the second one is that the struct name and the method name are identical.

**Comment by Jorropo** [comment]
Trying to assign it to an `errorReporter` gives:
```
./prog.go:53:27: cannot use &reportWrapped{…} (value of type *reportWrapped) as errorReporter value in variable declaration: *reportWrapped does not implement errorReporter (*reportWrapped.report is a field, not a method)
```
The `*report` embed field overrides the promoted method.

I was not able to find a description of promotion precedence in the spec. 
I guess this is implicit from:
> A field or [method](https://go.dev/ref/spec#Method_declarations) f of an embedded field in a struct x is called promoted if x.f is a legal [selector](https://go.dev/ref/spec#Selectors) that denotes that field or method f.

Because `reportWrapped.report` already exists it wouldn't be legal to promote the method, however this line of thinking does not explain why if multiple embeded fields have conflicting selector neither is promoted.
But I'm not sure, this could be red multiple ways.

**Comment by bcmills** [comment]
See https://go.dev/ref/spec#Selectors:
> For a value `x` of type `T` or `*T` where `T` is not a pointer or interface type, `x.f` denotes the field or method at the shallowest depth in `T` where there is such an `f`. If there is not exactly [one `f`](https://go.dev/ref/spec#Uniqueness_of_identifiers) with shallowest depth, the selector expression is illegal.

**Comment by Naatan** [comment]
> See [go.dev/ref/spec#Selectors](https://go.dev/ref/spec#Selectors):
> 
> > For a value `x` of type `T` or `*T` where `T` is not a pointer or interface type, `x.f` denotes the field or method at the shallowest depth in `T` where there is such an `f`. If there is not exactly [one `f`](https://go.dev/ref/spec#Uniqueness_of_identifiers) with shallowest depth, the selector expression is illegal.

Wouldn't that mean that both wrapped errors should've failed to match the interface? The code I shared only fails to cast if the method name matches the struct name.

**Comment by bcmills** [comment]
The name of the embedded field is what clobbers the method. (`reportWrapped.report` is a field name, so it can't also be a method name: the two kinds of names share a single “selector” namespace.)

**Comment by quki3** [comment]
I think that inside of you interface you have something like this :
```bash
interface [ 
        error
   ->	report() string                 //have the same name so go find this like a nil type func() value
        reportWrapped struct
    -> report struct                   //have the same name unknow for go
        customErrorWrapped struct
        .....
```

**Comment by Naatan** [comment]
Ahhh of course! Obvious in retrospect, not so much when I was running into it. Thanks guys!
