### ISSUE TITLE
log/slog: ReplaceAttr called with Group attribute, contradicting the docs

### ISSUE THREAD

**Issue by pschultz** [golang/go#62731]
The Documention for slog.HandlerOptions.ReplaceAttr reads:

> ReplaceAttr is never called for Group attributes, only their contents.

However, ReplaceAttr is indeed called with a Group attribute if -- and only if -- the Value is the result of resolving a LogValuer.

Either the call should not happen, or the documentation should mention this exception.

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/pschultz/.cache/go-build'
GOENV='/home/pschultz/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/pschultz/go/pkg/mod'
GONOPROXY='<redacted>'
GONOSUMDB='<redacted>'
GOOS='linux'
GOPATH='/home/pschultz/go'
GOPRIVATE='<redacted>'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go1.21.1'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go1.21.1/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.1'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/tmp/tmp.QjZvF8MPOj/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build480343776=/tmp/go-build -gno-record-gcc-switches'
</pre></details>

### What did you do?

https://go.dev/play/p/uCI04fkKVIq

```
package main

import (
        "fmt"
        "io"
        "log/slog"
)

type Name struct {
        First, Last string
}

// LogValue implements slog.LogValuer.
// It returns a group containing the fields of
// the Name, so that they appear together in the log output.
func (n Name) LogValue() slog.Value {
        return slog.GroupValue(
                slog.String("first", n.First),
                slog.String("last", n.Last))
}

func main() {

        l := slog.New(slog.NewTextHandler(io.Discard, &slog.HandlerOptions{
                ReplaceAttr: func(groups []string, a slog.Attr) slog.Attr {
                        fmt.Println(a.Key, a.Value.Kind())
                        return a
                },
        }))

        n := Name{"Perry", "Platypus"}
        l.Info("mission accomplished", "agent", n)
}
```

### What did you expect to see?

```
time Time
level Any
msg String
first String
last String
```

### What did you see instead?

```
time Time
level Any
msg String
agent Group // <-- this call should not happen
first String
last String
```

**Comment by quki3** [comment]
I think this call yes must happen because you are defining a type attr so
the print of slog.attr interface search all types and print... look this
https://cs.opensource.google/go/go/+/master:src/log/slog/attr.go
