### ISSUE TITLE
encoding/csv: LazyQuotes option breaks if the fields are unquoted and the lazy quotes appear at the beginnng of the field

### ISSUE THREAD

**Issue by gopherbot** [golang/go#6287]
by **alex@zylman.com**:

<pre>Similar to issue #6258, but not the same.

What steps will reproduce the problem?
Try to read a CSV file where the fields are unquoted and one of them begins in something
that would need lazy quotes, e.g.
Field1,Field2,&quot;LazyQuotes&quot; Field3,Field4,Field5

What is the expected output?
[&quot;Field1&quot;, &quot;Field2&quot;, &quot;\&quot;LazyQuotes\&quot; Field3&quot;,
&quot;Field4&quot;, &quot;Field5&quot;]
Length 5

What do you see instead?
[&quot;Field1&quot;, &quot;Field2&quot;, &quot;LazyQuotes\&quot;
Field3,Field4,Field5&quot;]
Length 3

Which compiler are you using (5g, 6g, 8g, gccgo)?
Whatever the default is from <a href="https://code.google.com/p/go/downloads/list">https://code.google.com/p/go/downloads/list</a>

Which operating system are you using?
Mac OS X 10.8

Which version are you using?  (run 'go version')
go version go1.1.2 darwin/amd64</pre>

**Comment by dsnet** [comment]
I believe this is working as intended. A quote at the beginning signifies that this is a quoted string, and the parser continues to follow the appropriate lazy rules for quoted strings.
