### ISSUE TITLE
text/template: (and html/template) execution option for given errors for missing map keys

### ISSUE THREAD

**Issue by gopherbot** [golang/go#6288]
by **bjruth**:

<pre>What steps will reproduce the problem?
If possible, include a link to a program on play.golang.org.

<a href="http://play.golang.org/p/zVTrueV2dd">http://play.golang.org/p/zVTrueV2dd</a>

Note the '&lt;no value&gt;' value for lastName.

What is the expected output?

I expect fields used in the template that are missing in the map should return an error
(missing key) rather than render '&lt;no value&gt;'

Please provide any additional information below.

Discussion on golang-nuts:
<a href="https://groups.google.com/forum/#">https://groups.google.com/forum/#</a>!topic/golang-nuts/VPhthY-ocsg

An ideal solution would be a Template.ExecuteStrict method that returns an error rather
than replacing missing keys/fields with '&lt;no value&gt;' in the output (as it does
now). This ensures nothing breaks with programs using Template.Execute in Go 1.x</pre>

**Comment by j7b** [comment]
You can implement pretty decent fail and default value behaviors with functions:

https://play.golang.org/p/AC_JYvE2CK

**Comment by alytvynov** [comment]
@robpike What's the rationale of this string-based approach as opposed to Options field in template.Template?
If new options are added you will have to update text/template and html/template anyway.
Struct-based implementation would add compile-time safety and feels cleaner.

**Comment by robpike** [comment]
It's a simpler API this way and html/template will not need to echo every type and constant.
