### ISSUE TITLE
cmd/compile: tables of interface data generate too much code.

### ISSUE THREAD

**Issue by robpike** [golang/go#6289]
<pre>The initialization of the pre-defined color palettes in package image/color/palette
generate an init function with more than 45KB of instructions. In principle, it could be
done entirely in data.

The tables are 512 interface values: type image.Color holding an image.RGBA. The RGBA
value could fit in a word, and the interface's type pointer is known, so in principle
the tables could be laid out at compile time. As it stands, it's about 90 bytes of init
code to generate each table entry.</pre>

**Comment by josharian** [comment]
I have a fix for this waiting for 1.8
