### ISSUE TITLE
net: connecting to 0.0.0.0 fails on windows

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#6290]
<pre>What steps will reproduce the problem?

run this program on windows

package main

import (
    &quot;log&quot;
    &quot;net&quot;
)

func dial() error {
    l, err := net.Listen(&quot;tcp&quot;, &quot;:0&quot;)
    if err != nil {
        return err
    }

    go func() {
        c, err := l.Accept()
        if err != nil {
            return
        }
        c.Close()
    }()

    c, err := net.Dial(&quot;tcp&quot;, l.Addr().String())
    if err != nil {
        return err
    }
    c.Close()
    return nil
}

func main() {
    err := dial()
    if err != nil {
        log.Fatal(err)
    }
}

What is the expected output?

Should output noting.

What do you see instead?

2013/08/30 16:43:22 dial tcp 0.0.0.0:1406: ConnectEx tcp: The format of the specified
network name is invalid.

Please use labels and text to provide additional information.

The problem seems to be that l.Addr().String() returns '0.0.0.0', but connecting to that
address is not allowed on windows. From
<a href="http://msdn.microsoft.com/en-us/library/aa923167.aspx">http://msdn.microsoft.com/en-us/library/aa923167.aspx</a>

&quot; ... If the address member of the structure specified by the name parameter is
all zeroes, connect will return the error WSAEADDRNOTAVAIL. ...&quot;</pre>

**Comment by bradfitz** [comment]
Let's at least remove that example from the docs on the `Dial` func. It's weird to connect to 0.0.0.0.

**Comment by taylorchu** [comment]
The doc says: `If the host is empty, as in ":80", the local system is assumed`. I interpret that `local system` as `localhost` (127.0.0.1) instead of `0.0.0.0`. It will be nice if this is clarified.

**Comment by mikioh** [comment]
#10624 will update the documentation; It will probably have a section about "Network and host/address arguments."

**Comment by rsc** [comment]
I think we should fix this. We advertise that Dial(":80") connects to the local system's port 80. It should do that on Windows too. I'll send a CL with a test and a fix; criticisms welcome.
