### ISSUE TITLE
syscall: reading os.Stdin does not treat ^Z as EOF on Windows

### ISSUE THREAD

**Issue by mattn** [golang/go#6303]
<pre>1. call io.Copy(os.Stdout, os.Stdin)
2. Type CTRL-Z on console

What is the expected output?

  Interrupt stdin

What do you see instead?

  Seeing ^Z character

Which compiler are you using (5g, 6g, 8g, gccgo)?

  8g

Which operating system are you using?

  Windows 7

Which version are you using?  (run 'go version')

  go version devel +2f13cc5d7043 Tue Aug 27 14:53:57 2013 +1000 windows/386

Please provide any additional information below.

  <a href="https://groups.google.com/forum/#">https://groups.google.com/forum/#</a>!topic/golang-dev/xnjP0VlL2nw</pre>

**Comment by mattn** [comment]
https://go-review.googlesource.com/#/c/4310/

**Comment by techtonik** [comment]
+1 for fixing this. Looks like the only way to terminate input from `stdin` in Go 1.4.2 is to be prepared for it.

**Comment by techtonik** [comment]
Maybe make that optional - ability to choose what combination can be used to terminate the stream.
