### ISSUE TITLE
x/website: broken Markdown link in loopvar-preview blog post

### ISSUE THREAD

**Issue by alurm** [golang/go#63042]
Hi, Go team.

I was reading a blog post about fixing for loops (https://go.dev/blog/loopvar-preview) and found what seems to me to be a typo: in Markdown link, square bracket was never opened.

Relevant part:

`code written depending on the new semantics will never be compiled with the old semantics, unless people are using very old, unsupported Go versions](/doc/devel/release#policy).`

Notice how opening square bracket is missing.

I think it should be something like this:

`code written depending on the new semantics will never be compiled with the old semantics, unless people are using [very old, unsupported Go versions](/doc/devel/release#policy).`

Please fix this.

Thanks!

**Comment by ianlancetaylor** [comment]
Thanks.  Already fixed by https://go.dev/cl/529257.
