### ISSUE TITLE
proposal: otel: Add OpenTelemetry (OTEL) Support to the Go Standard Library

### ISSUE THREAD

**Issue by bkielbasa** [golang/go#63119]
# Introduction
As the demand for observability increases in modern software, there is a growing need for standardized tools that allow developers to monitor, trace, and log their applications effectively. OpenTelemetry (OTEL) is a merged project of OpenTracing and OpenCensus, and it has become the de facto standard for observability.

This proposal aims to integrate OTEL support directly into the Go standard library. Such an inclusion would simplify and standardize the instrumentation of Go applications, further driving Go's reputation as a first-class language for modern cloud-native development.

From my experience, integrating infrastructure-related topics is very common and very often repeated in may projects.

# Goals
* **Seamless Integration**: Allow Go developers to effortlessly instrument their code without the need for third-party libraries.
* **Standardized Observability**: Promote the usage of a unified observability tool in Go, reducing fragmentation in the ecosystem.
* **Improved Performance**: By integrating OTEL natively, we can fine-tune performance bottlenecks, ensuring minimal overhead.
* **Flexibility**: While OTel would be part of the standard library, it should be entirely optional, ensuring that developers are not forced to adopt it if they have other preferences.

# Proposed Changes
New `otel` Package: Introduce a new package in the standard library, tentatively named otel. This package will contain the necessary APIs for tracing, metrics collection, and context propagation.

* **Integration with Existing Packages**: Enhance some of the existing packages, such as `http`, `database/sql`, and `net`, to include built-in OTEL instrumentation. This would ensure that common operations are automatically traced without requiring manual intervention.

* **Configuration & Extension Points**: While the standard library will offer a default implementation, it's vital that developers can configure and extend OTel as per their needs. This would include setting up exporters, span processors, and more.

* **Documentation & Tutorials**: Add comprehensive documentation for the OTEL package and its integrations. Furthermore, develop tutorials to guide Go developers on best practices for instrumenting their applications.

* **Backward Compatibility**: Ensure that adding OTEL support does not break any existing functionality or introduce unexpected behaviors in the standard library.

I was thinking about having otel support disabled by default but adding a simple import like:

```go
 import _ `net/http/otel`
```

Would register the most basic metrics/functionalities. I imagine it to work similarly to how `net/http/pprof` does right now.

# Potential Challenges & Solutions
 * **Size & Bloat:** One of the major concerns is adding a substantial amount of code to the standard library. We must ensure that the integration is as lightweight as possible. The `otel` package can be designed in such a way that only the core functionalities are included, while extensions or plugins can be fetched separately if needed.

 * **Performance Overhead**: Introducing tracing and metrics might add overhead to applications. We need to benchmark the implementation rigorously and ensure that any performance degradation is minimal and acceptable.

* **Maintenance**: The OTEL specification evolves over time. The Go team would need to keep up with changes, ensuring that the standard library's implementation remains compliant.

**Comment by seankhliao** [comment]
please discuss this in the active discussion at #61638
this is currently too broad to be considered for a proposal.
