### ISSUE TITLE
cmd/go: go list does not scale with GOMAXPROCS

### ISSUE THREAD

**Issue by goto1134** [golang/go#63136]
### What version of Go are you using (`go version`)?

master ace1494d9235be94f1325ab6e45105a446b3224c

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH='arm64'
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOOS='darwin'
</pre></details>

### What did you do?

1. Clone Kubernetes
2. Run `GOMAXPROCS=10 go list -json -m -u -mod=readonly -debug-trace=trace-default.txt all`
3. Run `GOMAXPROCS=20 go list -json -m -u -mod=readonly -debug-trace=trace-maxproc.txt all`

The second command takes the same amount of time as the first one.
Here are the collected traces:

### What did you expect to see?
The second command runs faster and scales, depending on the GOMAXPROCS value.

### What did you see instead?
The second comment took the same amount of time as the first one.

Here are the collected traces:
[trace-default.txt](https://github.com/golang/go/files/12681714/trace-default.txt)
[trace-maxproc20.txt](https://github.com/golang/go/files/12681715/trace-maxproc20.txt)

From the traces, it's evident that the bottleneck is in getting the modules in a loop here:
https://github.com/golang/go/blob/ace1494d9235be94f1325ab6e45105a446b3224c/src/cmd/go/internal/modload/list.go#L277C1-L286C4

**Comment by goto1134** [comment]
@dany74q , the next step is to provide benchmarks. I want to do it sometime later. Probably in November.

I hope this change will be accepted for the February release of Go.

**Comment by AdallomRoy** [comment]
@goto1134 any updates on this?

**Comment by goto1134** [comment]
@AdallomRoy, the PR is still being reviewed and waiting for me to revisit the performance tests after the [latest review comments](https://go.dev/cl/530037). It's my next task on the list 🙂

**Comment by AdallomRoy** [comment]
@goto1134 any updates on this? it's been another month and performance is still abysmal.

**Comment by goto1134** [comment]
> @goto1134 any updates on this? it's been another month and performance is still abysmal.

Hey! As you might see, I provided all the changes requested by reviewers. Could you clarify how I can help you?
