### ISSUE TITLE
ld: warning: ignoring duplicate libraries: '-lproc'

### ISSUE THREAD

**Issue by yangyile1990** [golang/go#63135]
I don't know where the error come.

when I `go run main.go` the message come `ld: warning: ignoring duplicate libraries: '-lproc'`,just a warning.

**Comment by eaardal** [comment]
For those who find this page when searching for ways to silence this obnoxious warning, I was able to get rid of it by setting this env:
```shell
export CGO_LDFLAGS="-Wl,-no_warn_duplicate_libraries"
```

**Comment by dolbyzerr** [comment]
@eaardal thank you so much!

**Comment by missinglink** [comment]
For `go build` use `-ldflags="-extldflags=-Wl,-no_warn_duplicate_libraries"`
