### ISSUE TITLE
affected/package: crypto

### ISSUE THREAD

**Issue by pedroalbanese** [golang/go#63130]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.20
</pre>

### Does this issue reproduce with the latest release?

Yep

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=386
set GOBIN=
set GOCACHE=C:\Users\0wner\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\0wner\go
set GOPROXY=
set GORACE=
set GOROOT=c:\go
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_386
set GCCGO=gccgo
set GO386=sse2
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\cygwin\tmp\go-build295106434=/tmp/go-build -gno-record-gcc-switches

but the error also occurs at Windows 10
</pre></details>

### What did you do?

I'm trying to integrate my tool [EDGETk](https://github.com/pedroalbanese/edgetk) with TCL/TK:

tiny_script3.tcl
```tcl
#!/usr/bin/tclsh

package require base64
package require sha256

set a "this is the plain text"
set key [sha2::sha256 $a]
set iv [string range [sha2::sha256 $key] 0 31]

# Encrypt the text
set enc_output [exec edgetk -crypt enc -key $key -iv $iv -mode ctr << $a]

# Encode the ciphertext in base64
set encoded_enc_output [base64::encode $enc_output]

puts "\nCiphertext: $encoded_enc_output\n\n"

# Decode the ciphertext from base64
set decoded_enc_output [base64::decode $encoded_enc_output]

# Decrypt the ciphertext
set dec_output [exec edgetk -crypt dec -key $key -iv $iv -mode ctr << $decoded_enc_output]

puts "Plaintext: $dec_output\n"
```

### What did you expect to see?

"this is the plain text"

### What did you see instead?

"this is the Ölain text"

![TCL](https://github.com/golang/go/assets/68971450/ceed9f70-693c-4854-a82e-efcab40bf20c)

Note that the ciphertext has the same length and the same hexdump in both cases.
![openssl](https://github.com/golang/go/assets/68971450/7ff59608-130a-485b-b888-94e36b58c5f8)

As you can see, encrypted text differs for some reason and, in some cases, is misinterpreted by the OS.

How to proceed?

Thanks in advace.

**Comment by ianlancetaylor** [comment]
You will get better and faster answers if you use a forum.  See https://go.dev/wiki/Questions.  Thanks.

**Comment by pedroalbanese** [comment]
@ianlancetaylor 

This is a bug and not a question. I'm demonstrating that the Go language works differently than it should. Using the same resources to perform the same operation, there is incompatibility.

**Comment by pedroalbanese** [comment]
What a shit?

**Comment by ianlancetaylor** [comment]
@pedroalbanese Give us a small, standalone example and we can take a look.  That said, please be open to the possibility that you are not using the Go packages correctly, and that asking on a forum will give you a quick answer.  Thanks.

**Comment by pedroalbanese** [comment]
This code encrypts like the image a diferent output than openssl, bot at same time, is compliant:

```go
package main
import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"encoding/hex"
	"flag"
	"fmt"
	"crypto/sha256"
	"golang.org/x/crypto/pbkdf2"
	"io"
	"log"
	"os"
)

	var derive = flag.Bool("d", false, "Derive password-based key.")
	var iter = flag.Int("i", 1024, "Iterations. (for PBKDF2)")
	var key = flag.String("k", "", "128-bit key to Encrypt/Decrypt.")
	var pbkdf = flag.String("p", "", "PBKDF2.")
	var random = flag.Bool("r", false, "Generate random 128-bit cryptographic key.")
	var salt = flag.String("s", "", "Salt. (for PBKDF2)")

func main() {
    flag.Parse()

        if (len(os.Args) < 2) {
	fmt.Println("AES Encryption Tool - ALBANESE Lab (c) 2020-2021\n")
	fmt.Println("Usage of",os.Args[0]+":")
        flag.PrintDefaults()
        os.Exit(1)
        }

        if *derive == true {
	prvRaw := pbkdf2.Key([]byte(*pbkdf), []byte(*salt), *iter, 32, sha256.New)
	fmt.Println(hex.EncodeToString(prvRaw))
        os.Exit(1)
	}
	
	if *random == true {
	var key []byte
	var err error
		key = make([]byte, 32)
		_, err = io.ReadFull(rand.Reader, key)
		if err != nil {
                        log.Fatal(err)
		}
		fmt.Println(hex.EncodeToString(key))
        	os.Exit(0)
	}

	var keyHex string
	var prvRaw []byte
	if *pbkdf != "" {
	prvRaw = pbkdf2.Key([]byte(*pbkdf), []byte(*salt), *iter, 32, sha256.New)
	keyHex = hex.EncodeToString(prvRaw)
	} else {
	keyHex = *key
	}
	var key []byte
	var err error
	if keyHex == "" {
		key = make([]byte, 32)
		_, err = io.ReadFull(rand.Reader, key)
		if err != nil {
                        log.Fatal(err)
		}
		fmt.Fprintln(os.Stderr, "Key=", hex.EncodeToString(key))
	} else {
		key, err = hex.DecodeString(keyHex)
		if err != nil {
                        log.Fatal(err)
		}
		if len(key) != 32 {
                        log.Fatal(err)
		}
	}
	ciph, err := aes.NewCipher(key)
	if err != nil {
		log.Fatal(err)
	}
	iv := make([]byte, 16)
	stream := cipher.NewCTR(ciph, iv)
	buf := make([]byte, 64*1<<10)
	var n int
	for {
		n, err = os.Stdin.Read(buf)
		if err != nil && err != io.EOF {
                        log.Fatal(err)
		}
		stream.XORKeyStream(buf[:n], buf[:n])
		if _, err := os.Stdout.Write(buf[:n]); err != nil {
                        log.Fatal(err)
		}
		if err == io.EOF {
			break
		}
	}
        os.Exit(0)
}
```

So 

`echo secret message | thiscode -p 123 -i 2`

Must be equal:

`echo secret message|openssl enc -aes-256-ctr -md sha256 -pbkdf2 -k 123 -iter 2 -nosalt -iv 00000000000000000000000000000000`

In other words, this code is compatible with openssl and is capable of undoing the operation without bugs

`echo secret message|openssl enc -aes-256-ctr -md sha256 -pbkdf2 -k 123 -iter 2 -nosalt -iv 00000000000000000000000000000000 | | thiscode -p 123 -i 2`

However, there is a coding problem that occurs in Windows 7 and Windows 10 that I noticed, as the commands individually generate different outputs despite having the same hexdump.

![openssl2](https://github.com/golang/go/assets/68971450/24116431-87f3-4fa4-a033-98661b4fb592)

**Comment by pedroalbanese** [comment]
Can You reopen it please

**Comment by seankhliao** [comment]
you've shown that it works, but not that it's wrong

**Comment by pedroalbanese** [comment]
Have you noticed the difference between the outputs when operations are performed individually?

**Comment by pedroalbanese** [comment]
This 

```tcl
#!/usr/bin/tclsh

package require base64
package require sha256

set a "this is the plain text"
set key [sha2::sha256 $a]
set iv [string range [sha2::sha256 $key] 0 31]

# Encrypt the text
set enc_output [exec edgetk -crypt enc -key $key -iv $iv -mode ctr << $a]

# Encode the ciphertext in base64
set encoded_enc_output [base64::encode $enc_output]

puts "\nCiphertext: $encoded_enc_output\n\n"

# Decode the ciphertext from base64
set decoded_enc_output [base64::decode $encoded_enc_output]

# Decrypt the ciphertext
set dec_output [exec edgetk -crypt dec -key $key -iv $iv -mode ctr << $decoded_enc_output]

puts "Plaintext: $dec_output\n"
```

should work as openssl, but results:


![TCL](https://github.com/golang/go/assets/68971450/b6edd733-5c2b-4054-91ab-69a3363af257)

**Comment by seankhliao** [comment]
that doesn't look like a go problem, if the output bytes are the same, then it points to it being a problem with your shell/terminal

**Comment by pedroalbanese** [comment]
This don't work:

tiny_script.tcl
```tcl 
#!/usr/bin/tclsh

package require base64
package require sha256

set a "this is the plain text"
set key [sha2::sha256 $a]
set iv [string range [sha2::sha256 $a] 0 31]

set enc_output [base64::encode [exec edgetk -crypt enc -key $key -iv $iv -cipher aria -mode ctr << $a]]
puts "\n$enc_output\n\n"

set dec_output [exec edgetk -crypt dec -key $key -iv $iv -cipher aria -mode ctr << [base64::decode $enc_output]]
puts "$dec_output\n"
```

And this work:

```tcl
#!/usr/bin/tclsh

package require base64
package require sha256

set a "this is the plain text"
set key [sha2::sha256 $a]
set iv [string range [sha2::sha256 $key] 0 31]

set enc_output [base64::encode [exec openssl enc -aes-256-ctr -pbkdf2 -md sha256 -k $key -iv $iv -aes-256-ctr -nosalt << $a]]
puts "\n$enc_output\n\n"

set dec_output [exec openssl enc -d -aes-256-ctr -pbkdf2 -md sha256 -k $key -iv $iv -aes-256-ctr -nosalt << [base64::decode $enc_output]]
puts "$dec_output\n"
```
where the only difference is that I'm using openssl in one, and edgetk in the other.
![tiny_script](https://github.com/golang/go/assets/68971450/98b61fc9-d0c8-4a92-88d1-a955794af54e)

**Comment by pedroalbanese** [comment]
Any terminal in Windows

![AnyTerminal](https://github.com/golang/go/assets/68971450/3fba0a13-1b9b-4648-8c82-47d8a0667271)

**Comment by ianlancetaylor** [comment]
If I understand correctly, you are saying that the program behavior is different on Windows.  It certainly sounds like a terminal issue.  What happens if you write the output to a file?

Again, you will receive better and faster answers if you use a forum as described at http://go.dev/wiki/Questions.

**Comment by pedroalbanese** [comment]
This problem was reported to me about 25 days ago by an EDGETk user, Mr. Dana Booth, who was trying to implement a graphical interface using it as a backend as it has a graphical interface for OpenSSL. Since then, I have carried out dozens of tests until I was convinced that the error was not with the implementation of TCL for Windows.

If I thought this wasn't interesting for you to know, I wouldn't have created the first issue.

I imagined that, a priori, you would have no explanation for this either, and it refers to a characteristic of Go on Windows, not my code.

**Comment by pedroalbanese** [comment]
If I save the result in a file this works correctly, contrary to the initial assumption of attributing the inability to my code and not to the language itself, which is still under construction.

There is no point in saving the result in a file, as Go is INCOMPATIBLE with TCL and I will make a point of saying this as many times as necessary.

**Comment by ianlancetaylor** [comment]
On Windows, Go assumes that console output uses valid UTF-8, which it converts to UTF-16 and passes to `WriteConsole`.  In this case the output is likely not valid UTF-8, so this conversion process is lossy.  Presumably TCL does something else, though I don't know what.

**Comment by pedroalbanese** [comment]
It makes sense. Tomorrow I will study this calmly. Thx
