### ISSUE TITLE
net/http:  content-encoding=gzip has not been deleted on wasmjs

### ISSUE THREAD

**Issue by 0x5457** [golang/go#63139]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.0 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH='arm64'
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOARCH='arm64'
GOVERSION='go1.21.1'
GCCGO='gccgo'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='0'
</pre></details>

### What did you do?

Introduction: When HTTP requests a gzip API in wasm-js, the response body has been decompressed, but content-encoding=gzip has not been deleted. This is inconsistent with the native behavior.

I created a [github repository](https://github.com/0x5457/go-wasm-http-client-gzip-issue-reproduce) containing complete reproduction steps

### What did you expect to see?
Expect the response of the HTTP client to be automatically decoded into gzip and remove the header with content encoding=gzip

Content-Encoding: 
Content-Length: 
ContentLength: -1
 body: [104 101 108 108 111 44 32 119 111 114 108 100] # decompressed body

### What did you see instead?
Content-Encoding: gzip
Content-Length: 36
ContentLength: 36
body: [104 101 108 108 111 44 32 119 111 114 108 100] # decompressed body

**Comment by dmitshur** [comment]
CC @golang/js, @golang/wasm.
