### ISSUE TITLE
x/pkgsite: os/exec

### ISSUE THREAD

**Issue by sslime336** [golang/go#63134]
### What is the URL of the page with the issue?

https://pkg.go.dev/os/exec@go1.21.1#Cmd.StdoutPipe

### What is your user agent?

Mozilla/5.0 (Android 12; Mobile; rv:109.0) Gecko/114.0 Firefox/114.0

### Screenshot

![Screenshot_20230921_094925_org.mozilla.firefox.jpg](https://github.com/golang/go/assets/97684920/64fe0fc5-47b9-42d7-b021-755a41d29e7c)

### What did you do?

Run the given example of exec.StdoutPipe

https://play.golang.org/p/ek7-_Xa_bN3

### What did you expect to see?

Output:

"Bob is 32 years old\n"

### What did you see instead?

 Deadloock.

**Comment by seankhliao** [comment]
unfortunately the playground is limited in what it can run.
