### ISSUE TITLE
x/mobile/cmd/gomobile: gomobile bind fails with Xcode 15

### ISSUE THREAD

**Issue by hajimehoshi** [golang/go#63141]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/Users/hajimehoshi/Library/Caches/go-build'
GOENV='/Users/hajimehoshi/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/hajimehoshi/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/hajimehoshi/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/darwin_amd64'
GOVCS=''
GOVERSION='go1.21.1'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/hajimehoshi/go-x-mobile/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/60/khbk2xqn1c5bml1byjn89dwc0000gn/T/go-build2181238540=/tmp/go-build -gno-record-gcc-switches -fno-common'
</pre></details>

### What did you do?

Install Xcode 15.0.

In gomobile directory, run

```sh
gomobile bind -target=ios ./example/bind/hello/
```

### What did you expect to see?

This command succeeds

### What did you see instead?

This command fails:

```
gomobile: xcodebuild -create-xcframework -framework /var/folders/60/khbk2xqn1c5bml1byjn89dwc0000gn/T/gomobile-work-3454804453/ios/iphoneos/Hello.framework -framework /var/folders/60/khbk2xqn1c5bml1byjn89dwc0000gn/T/gomobile-work-3454804453/iossimulator/iphonesimulator/Hello.framework -framework /var/folders/60/khbk2xqn1c5bml1byjn89dwc0000gn/T/gomobile-work-3454804453/iossimulator/iphonesimulator/Hello.framework -output Hello.xcframework failed: exit status 70
error: cannot compute path of binary 'Path(str: "/private/var/folders/60/khbk2xqn1c5bml1byjn89dwc0000gn/T/gomobile-work-3454804453/ios/iphoneos/Hello.framework/Versions/A/Hello")' relative to that of '/var/folders/60/khbk2xqn1c5bml1byjn89dwc0000gn/T/gomobile-work-3454804453/ios/iphoneos/Hello.framework'
```

/CC @hyangah @dmitshur

**Comment by hajimehoshi** [comment]
I'm sending a CL soon.

**Comment by brave723** [comment]
so，how to slove it？

**Comment by brave723** [comment]
> I'm sending a CL soon.

please send your cl

**Comment by hajimehoshi** [comment]
> please send your cl

https://github.com/golang/go/issues/63141#issuecomment-1729760259

**Comment by brave723** [comment]
> > please send your cl
> 
> [#63141 (comment)](https://github.com/golang/go/issues/63141#issuecomment-1729760259)

How do I operate on the computer? I'm an ios developer

**Comment by brave723** [comment]
> > please send your cl
> 
> [#63141 (comment)](https://github.com/golang/go/issues/63141#issuecomment-1729760259)

thanks , I have slove, rebuild gomobile

**Comment by cherrymui** [comment]
@hajimehoshi on the CL you mentioned that this is likely a bug in xcodebuild in Xcode 15. Have you reported it to Apple? Thanks.

**Comment by hajimehoshi** [comment]
No, I have not.

**Comment by cherrymui** [comment]
Thanks.

**Comment by losh11** [comment]
Is there a temp fix for this bug?

**Comment by cherrymui** [comment]
This is already fixed in the latest version of gomobile. Please update gomobile. Thanks.
