### ISSUE TITLE
Why go does not panic when trying to visit nil map?

### ISSUE THREAD

**Issue by sleagon** [golang/go#63140]
### What version of Go are you using (`go version`)?
1.19

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
noneed

### What did you do?

```
		var mp map[string]string = nil
		log.Println(mp["12"], "12")
		if mp == nil {
			panic("wtf")
		}
```

### What did you expect to see?

Panic should hanppend in the line of `log.Pirntln` instead of `panic("wtf")`.

### What did you see instead?
Just panic in the line `panic("wtf")`

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
