### ISSUE TITLE
affected/package: go install fail

### ISSUE THREAD

**Issue by summer-boythink** [golang/go#63156]
## `go install` cannot install the package when `go.mod` contains the `replace` statement

<pre>
$ go version
go version go1.21.1 linux/amd64
</pre>

When I try to use `go install github.com/bcicen/ctop@v0.7.7`,I'll get an error

![Snipaste_2023-09-22_13-56-17](https://github.com/golang/go/assets/57977288/e18aedbb-7204-4a89-b6a8-174e10d42573)

I guess what he meant was that go.mod contains one or more replace directives
I confirmed my guess in this  [link](https://github.com/bcicen/ctop/blob/v0.7.7/go.mod)

**So, my question is: When `go.mod` is designed, if `go.mod` contains one or more `replace directives`, does it prohibit the `go install` for this package**
 
**If `go.mod` is designed according to what I said above, I think this design is not very reasonable. Because `go.mod` contains `replace directives` is a can be found in (https://pkg.go.dev/github.com/bcicen/termui )  package**

He shouldn't have denied me access `to go install`

**Comment by seankhliao** [comment]
working as intended

**Comment by mvdan** [comment]
Also see https://github.com/golang/go/issues/40276 for the history of the design.
