### ISSUE TITLE
flag: print default value when false for boolean flags

### ISSUE THREAD

**Issue by Rajan-226** [golang/go#63150]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.21.0 darwin/arm64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

I defined a boolean flag with default value as false.

`flag.Bool("boolVar", false, "Trying bool variable")`

I'm running go run main.go -h

### What did you expect to see?

I expect to get default value of boolVar like I get when it's true.
<img width="1496" alt="image" src="https://github.com/golang/go/assets/56467449/17ea1849-f058-4741-b975-7697e2f46297">

### What did you see instead?

I'm not getting default value when it's false.
<img width="1497" alt="image" src="https://github.com/golang/go/assets/56467449/0fb31ce6-38ef-4c0a-957b-baf809a6f077">

**Comment by Rajan-226** [comment]
I would like to pick dev for this if you consider it as a good first issue.

**Comment by seankhliao** [comment]
sure, send a CL / PR

**Comment by ianlancetaylor** [comment]
Please always post ordinary text output as plain text, not as an image.  Plain text is much easier to read.  Thanks.

**Comment by ianlancetaylor** [comment]
This is intentional behavior.  The flag package only displays the default flag when that value is not the zero value of the type.  The code is at https://go.googlesource.com/go/+/refs/heads/master/src/flag/flag.go#628.  Thanks for reporting this but we don't plan to change it.
