### ISSUE TITLE
affected/package: regexp

### ISSUE THREAD

**Issue by akashjain971** [golang/go#63157]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.21

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)? 

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
</pre></details>
mac/linux/playground

### What did you do?
```
package main

import (
	"fmt"
	"regexp"
)

const pattern = `^.*world|hello.*$`
const text = `hi hello world bye`

func main() {
	r := regexp.MustCompile(pattern)
	fmt.Println(r.MatchString(text)) // returns true expected false
}
```
### What did you expect to see?
The program should return `false`

### What did you see instead?
The program returns `true`

The way to interpret the pattern is 
1. The text must end with the string `world`
2. The text must start with the string `hello`

This works as expected with java.util.regex.
Is this a bug with golang implementation or is it as per the [RE2](https://github.com/google/re2/wiki/Syntax) spec?

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.
