### ISSUE TITLE
affected/package: cgo

### ISSUE THREAD

**Issue by ImagineYao** [golang/go#63158]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/user/Library/Caches/go-build"
GOENV="/Users/user/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/user/go/pkg/mod"
GONOPROXY="*.okg.com"
GONOSUMDB="*.okg.com"
GOOS="darwin"
GOPATH="/Users/user/go"
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go/bin"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/bin/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vy/p9bfvrgj7vq7lsgpmzkswf440000gn/T/go-build665163270=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

run the go test file

### What did you expect to see?
a result without error

### What did you see instead?
got error
<pre>
 cgo: malformed DWARF TagVariable entry
</pre>

**Comment by seankhliao** [comment]
sorry we don't support 1.18
