### ISSUE TITLE
net/http: unexpected malformed MIME header error

### ISSUE THREAD

**Issue by hy950921** [golang/go#63168]
### What version of Go are you using (`go version`)?

<pre>
$ go version
just upgraded to 1.20.8 from 1.17
</pre>

### Does this issue reproduce with the latest release?
we are having it in 1.20.8 but not in 1.17

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
macos locally
</pre></details>

### What did you do?
running the url test locally

### What did you expect to see?

a status code 200 is returned

### What did you see instead?

500 is returned and error message=net/http: HTTP/1.x transport connection broken: malformed MIME header line: (.*)A:B

FYI: (.*)A is defined as a queryparameter and B is the value here. idk why it is identified as MIME header here.

**Comment by ianlancetaylor** [comment]
Can you show us a standalone program that reproduces the problem?  I don't understand the problem from your description.  Thanks.

**Comment by hy950921** [comment]
It is an enterprise config driven routing application, I can only share more details in words here. I am upgrading the golang version from 1.17 to 1.20.8, and I am getting some errors after running our URL tests in CI/locally. The error message from the log says "net/http: HTTP/1.x transport connection broken: malformed MIME header line: (.*)foo:bar". However, in our config definition, " (.*)foo" is defined as the name of queryparameter and "bar" is defined as the value of queryparameter. I am wondering that what changed to have this issue.

**Comment by seankhliao** [comment]
we'd need to see the request it's making to determine if it's valid

**Comment by ianlancetaylor** [comment]
CC @neild

**Comment by ianlancetaylor** [comment]
This may be due to https://go.dev/cl/410714, which restricts the bytes permitted in MIME headers to those listed in RFC 7230.

**Comment by hy950921** [comment]
@ianlancetaylor Thanks, I can confirm this is the root cause for me, is there any easy fix for experiencing such issue, we used to have some characters "parentheses" that are not allowed in 1.20 but we are hoping to keep them.

**Comment by ianlancetaylor** [comment]
Unfortunately, there is no easy fix, as the change was made for security reasons.  Sorry.
