### ISSUE TITLE
the new go is installed but none environment variable loaded

### ISSUE THREAD

**Issue by Azaretdodo** [golang/go#63189]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.21.1

</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env windows 64 byte

</pre></details>

### What did you do?

i try to install gotv-plus-go-master

### What did you expect to see?

i can install fully with both go.sum and go.mod from the fork gotv-plus-go-master

### What did you see instead?

```
PS C:\Windows\System32\go\src\gotv-plus-go-master> go build go.mod
go: cannot find GOROOT directory: C:\Windows\System32\go\bin\go.exe
```

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
