### ISSUE TITLE
cmd/go: rare corruption of elf binary

### ISSUE THREAD

**Issue by pwaller** [golang/go#63191]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.8 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

I have been unable to reproduce this at all. So it is obviously a rare failure of some component somewhere.

I believe this may have nothing to do with the Go toolchain but that an error report may be appreciated anyway. Please feel free to close this if that seems the appropriate course of action.

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOOS="linux"
```

go version: 1.20.8, linux/amd64. Linux 6.4.16; Small binary built on NixOS (nixos/nixpkgs@d64aec9ffb49ef3aaa38924224c069945caad362 using nixpkgs `buildGoModule` [0]). 

### What did you do?

Build a fairly simple Go binary which uses HTTP and run it.

### What did you expect to see?

A well formed binary.

### What did you see instead?

Upon running the program, junk binary data printed to terminal, segfault. Corrupted binary. Rebuild [via nixpkgs, so no caches involved] produced the expected result.

# Details

Reproduction attempts so far failed across thousands of builds. I can't rule out filesystem or hardware corruption though was unable to detect those with memcheck and further testing either. Could also be a nixpkgs or other toolchain bug. A friend and I worked out the corruption function (`bork`, below). Which from the offsets doesn't feel likely to be filesystem corruption either.

```
def bork(g): return 
    g[:4880*512] + 
    g[4880*512+2672:6255*512] + 
    g[6249*512+400:7608*512] + 
    g[7608*512+336:8733*512+256] + 
    g[8732*512+432:]

bork(good binary bytes) == bad binary bytes

len(both binaries) == 5067832
```

[0] Build env repro below, supply your own sources, if you have nix installed, put source code in `.` and fix `vendorHash` when it complains. Note that NixOS also does [other binary mangling](https://trofi.github.io/posts/293-mysterious-patchelf-linkage-bug.html), those things may also be implicated. 

```
NIX_PATH=nixpkgs=flake:nixpkgs/d64aec9ffb49ef3aaa38924224c069945caad362 nix-build --expr '(import <nixpkgs> {}).buildGoModule { name = "hello-world"; src = ./.; vendorHash = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="; }'
```

**Comment by seankhliao** [comment]
maybe related? #53804

**Comment by pwaller** [comment]
> maybe related? #53804

I think this issue is likely distinct, though that issue inspired me to file this one. The reasons I think it is likely distinct are because 1) my kernel version is newer than the one which is thought to fix it and 2) that one involved zero pages.

This bug does not have zero pages. All of the bytes in the corrupt binary are accounted for in the good binary. It is as if the binary has been scrambled a bit.
