### ISSUE TITLE
x/website: Go keywords syntax is not readable with Dark mode and Syntax Highlighting turned on

### ISSUE THREAD

**Issue by Manish-Giri** [golang/go#63229]
### What is the URL of the page with the issue?

https://go.dev/tour/moretypes/9

### What is your user agent?

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.36

### Screenshot

![image](https://github.com/golang/go/assets/11348778/85537883-e430-44c5-b8dc-f2bb96e29f97)

None of the bool values are readable.

### What did you do?

1. Visit the Tour of Go website.
2. Turn on dark mode on the page (top right).
3. Turn on syntax highlighting for the editor (top right).

### What did you expect to see?

Code should be readable.

### What did you see instead?

Code is not readable.

**Comment by thanm** [comment]
@golang/tools-team

**Comment by suzmue** [comment]
go.dev shoots for a color contrast of 4.5:1 or greater for all text.

The booleans on this page have a ratio of 1.02:1
<img width="435" alt="Screenshot 2023-09-26 at 10 09 21 AM" src="https://github.com/golang/go/assets/6634754/ef5646b2-0381-4283-acac-52d1b68b415f">

Comments also have a low contrast ratio of 2.42 in dark mode, https://go.dev/tour/moretypes/5:
<img width="372" alt="Screenshot 2023-09-26 at 10 09 52 AM" src="https://github.com/golang/go/assets/6634754/a68210e8-d626-41ef-bf5b-e64cd1d8bc12">
