### ISSUE TITLE
proposal: strings/bytes: Accept named types

### ISSUE THREAD

**Issue by Inuart** [golang/go#63234]
Currently the definition of `bytes.Split` is `func Split(s, sep []byte) [][]byte` and I think it could be backwards-compatibly updated to `func Split[T ~[]byte](s, sep T) []T`. 

Other functions in the `bytes` package as well as their counterparts in the `strings` package could be changed to accept named types.

I was not able to find any previous issue about this, nor any reference to `bytes` nor `strings` in https://github.com/golang/go/discussions/48287. Maybe because that thread is focused on backwards-incompatible changes.

**Comment by mateusz834** [comment]
It is not backwards compatible:
```go
package main

import "bytes"

func Split[T ~[]byte](s, sep T) []T {
	return nil
}

func main() {
	_ = Split // cannot use generic function Split without instantiation
	_ = bytes.Split // fine
}

```
