### ISSUE TITLE
x/pkgsite: package removal request for github.com/steelshot/go-nullable < v0.2.0

### ISSUE THREAD

**Issue by steelshot** [golang/go#63261]
### What is the path of the package that you would like to have removed?

I would like to remove all versions below v0.2.0 under [github.com/steelshot/go-nullable](https://pkg.go.dev/github.com/steelshot/go-nullable)

### Are you the owner of this package?

Yes

### What is the reason that you could not retract this package instead?

I was not aware that modules are indexed by default when using **go get**. I've did few force commit and tag amends also was as well not aware that go module paths are case sensitive, tried retracting everything prior to v0.1.0, did not work. Decided to just move on and renamed my username to be lowercase to be friendlier for various reasons. Tried retracting the old and the new paths and start a fresh with v0.2.0, was unaware retractions worked on case insensitive... The retractions seemed to have worked after a 2nd attempt in v0.1.99, everything prior to 0.2.0 was retracted until I have commited v0.2.0 and everything again shows up as before.

I must be confused on how retractions works? Submit a bad version (persay 0.5.0, after 0.4.9), commit a 0.5.1 that retracts 0.5.0-0.5.1, 0.4.9 is now latest, submit 0.6.0 after some time and keep going until a new retraction is needed. 
Does the retract statement needs to be included for the whole lifetime of a module, each time a new version is released and also for every single new retraction? Making the retract statement growing indefinitely? My assumption or miss understanding, when a bad version(s) is present, submit a new version that retracts what is necessary, hiding but not removing the packages from pkg.go.dev and then continue as normal in future versions without the retract statement until a new retration is needed and then rinse and repeat?

Thank You

**Comment by seankhliao** [comment]
We cannot remove specific versions, only entire modules.
And yes, the retractions that apply depend on what's in the current "latest".
