### ISSUE TITLE
x/pkgsite: package removal request for https://pkg.go.dev/github.com/fuyulang/fuyu

### ISSUE THREAD

**Issue by adamchristiansen** [golang/go#63273]
### What is the path of the package that you would like to have removed?

https://pkg.go.dev/github.com/fuyulang/fuyu

### Are you the owner of this package?

Yes.

### What is the reason that you could not retract this package instead?

I believe I have retracted this package correctly but it has not been removed. The generated documentation at https://pkg.go.dev/github.com/fuyulang/fuyu says that it is retracted. I have retracted it three times and waited for variable periods (>1 week to ~2 months) between each for the package to be removed. The source repository can be viewed at https://github.com/fuyulang/fuyu. The `v0.0.1`, `v0.0.2`, and `v0.0.3` tags all issue retractions, but the package was never removed.

**Comment by bcmills** [comment]
Retraction is not the same as removal. (Retracting a module adds a notice that the module is retracted, removes in from search results, and prevents `go get` from adding a new dependency on it.)

Can you explain why retraction is not sufficient in this case?

**Comment by adamchristiansen** [comment]
For some reason I thought that retraction with the pseudo-version `v0.0.0-0` queued the package for removal.

I was trying to remove it because (1) I have changed the direction of the project and Go is no longer the best choice for it and (2) the package itself is empty except for a placeholder "hello world" style executable.

**Comment by adonovan** [comment]
https://pkg.go.dev/github.com/fuyulang/fuyu is serving 404, so I assume this happened already.
