### ISSUE TITLE
encoding/base64: Decode shouldn't panic when destination buffer is insufficient

### ISSUE THREAD

**Issue by RodionGork** [golang/go#63278]
### What version of Go are you using (`go version`)?

<pre>
1.21
</pre>

### What operating system and processor architecture are you using (`go env`)?

ubuntu 22.04 on amd64

### What did you do?

`base64.StdEncoding.Decode` is called with the destination buffer of insufficient size

https://go.dev/play/p/8mGzeMnqg5e

### What did you expect to see?

either of two seems acceptable:

- destination buffer is filled up to its capacity, remaining decoded data are discarded
- specific error is returned (as the method signature has second value for error)

### What did you see instead?

`panic: runtime error: index out of range [2] with length 1`

which is not only harmful but also misleading as the size of destination buffer is larger than 1

### Note

This seemingly existed at least since 1.18 and was already reported but failed to gain attention and was closed after confused discussion: #54532

**Comment by seankhliao** [comment]
see #58391

**Comment by RodionGork** [comment]
thanks but no idea "see what", sorry

library methods shouldn't panic and referred issue doesn't explain why they should

**Comment by ianlancetaylor** [comment]
We have decided that in the Go standard library functions are permitted to panic if the input arguments fail their preconditions.  For example, functions in the Go standard library do not routinely check whether they have been passed a `nil` pointer.
