### ISSUE TITLE
net/url: func parse(rawURL string, viaRequest bool) (*URL, error) 

### ISSUE THREAD

**Issue by tibetsam** [golang/go#63280]
### What version of Go are you using (`go version`)?

<pre>
go 1.21

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
[$ go env](https://go.dev/play/)

</pre></details>

### What did you do?

https://go.dev/play/p/njAfwJZKrXZ

### What did you expect to see?
https://www.rfc-editor.org/rfc/rfc1738.html
user           = *[ uchar | ";" | "?" | "&" | "=" ]
password       = *[ uchar | ";" | "?" | "&" | "=" ]

### What did you see instead?

invalid port ":p" after host

**Comment by bcmills** [comment]
RFC 1738 defines:
> ```
> uchar          = unreserved | escape
> ```

But `:` is in the `reserved` class — the opposite of `unreserved`. As far as I cal tell, the behavior of `url.Parse` in this case matches the RFC.

**Comment by bcmills** [comment]
The character `:` is not in that list.

**Comment by tibetsam** [comment]
I think the problem comes along with character ?, not : please check code
between line 531-536
https://github.com/golang/go/blob/master/src/net/url/url.go

**Comment by seankhliao** [comment]
we use RFC 3986, not 1738
https://www.rfc-editor.org/rfc/rfc3986.html#section-3.2.1

**Comment by tibetsam** [comment]
thanks!
