### ISSUE TITLE
x/tools/gopls: less syntax highlighting in v0.14.0-pre.1

### ISSUE THREAD

**Issue by erdauletbatalov** [golang/go#63291]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.18

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GOARCH="amd64"
</pre></details>

### What did you do?

Just installed gopls v0.14.0-pre.1 and got this issue

### What did you expect to see?

I expect code colorization to work as it was working in go nightly before

### What did you see instead?

code colorization feature disapeared

before and after:
![photo_2023-09-29_12-56-38](https://github.com/golang/go/assets/54989150/f271aeb9-735e-41e3-b513-2f1cc83ea922)
![photo_2023-09-29_12-56-31](https://github.com/golang/go/assets/54989150/511706ee-f4e0-436e-a96a-738a7cf91219)

**Comment by erdauletbatalov** [comment]
Also forgot to mention that I checked everything and ended up with concluding that gopls v0.14 is the actual problem causer.

**Comment by erdauletbatalov** [comment]
I installed prev version of gopls and code colorization got back

**Comment by findleyr** [comment]
Thanks very much for the report. We'll look into this and ensure it's fixed before the release.

**Comment by hyangah** [comment]
the `initialize` response omits all the necessary legend info. 

```
"semanticTokensProvider":{"legend":{"tokenTypes":[],"tokenModifiers":[]},"range":true,"full":true},
```

I am guessing this bug is related to the Option management.

**Comment by findleyr** [comment]
Thanks for investigating, @hyangah, that must be right. I'll investigate.
