### ISSUE TITLE
cmd/compile: allow interface pointers to be used as pointers to subset interface types in calls, rather than being unable to obtain addresses

### ISSUE THREAD

**Issue by qiulaidongfeng** [golang/go#63304]
### What version of Go are you using (`go version`)?

<pre>
$ go version
tip
</pre>

### Does this issue reproduce with the latest release?

yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

https://go.dev/play/p/tdRYybgfMzt?v=gotip

### What did you expect to see?
I hope to see the compilation pass.

I think local variables should be able to obtain addresses.

### What did you see instead?
./prog.go:23:7: invalid operation: cannot take address of I1(j) (value of type I1)

**Comment by go101** [comment]
Now, intermediate values can't be taken addresses in Go: https://go101.org/article/unofficial-faq.html#unaddressable-values

**Comment by thanm** [comment]
Hi @qiulaidongfeng this seems more like a language question as opposed to a compiler bug -- the compiler is being consistent with the way the language is defined.  If you have questions about addressability in Go, probably best to consult a forum like golang-nuts mailing list.
