### ISSUE TITLE
affected/package: crypto Bug in ed25519

### ISSUE THREAD

**Issue by master255** [golang/go#63301]
Why is there a 32 byte limit here? A full hash is 64 bytes
https://github.com/golang/go/blob/1e690409206ff97330b5a91517d453fc5129bab2/src/crypto/ed25519/ed25519.go#L172C43-L172C43

And then an empty array is used instead of this full hash https://github.com/golang/go/blob/1e690409206ff97330b5a91517d453fc5129bab2/src/crypto/internal/edwards25519/scalar.go#L216

And then do the calculation operations with the empty bytes?
https://github.com/golang/go/blob/1e690409206ff97330b5a91517d453fc5129bab2/src/crypto/internal/edwards25519/scalar.go#L126C21-L126C21

So we only use 32 bytes of ed25519 instead of 64? Like everyone else in the world.

My ed25519 keys generated in go don't work on other systems.

**Comment by AlexanderYastrebov** [comment]
Hello. Please read the code, comments and https://datatracker.ietf.org/doc/html/rfc8032#section-5.1.5 in particular.

**Comment by master255** [comment]
@AlexanderYastrebov This doesn't answer my questions. It is not written anywhere to cut off 32 bytes from the hash. 
And do calculations with empty bytes.
https://github.com/golang/go/blob/1e690409206ff97330b5a91517d453fc5129bab2/src/crypto/internal/edwards25519/scalar.go#L128

**Comment by ericlagergren** [comment]
@master255 yes, it does answer your questions.

> Why is there a 32 byte limit here? A full hash is 64 bytes

From RFC 8032 section 5.1.5:

> 1.  Hash the 32-byte private key using SHA-512, storing the digest in a 64-octet large buffer, denoted h.  **Only the lower 32 bytes are used for generating the public key.**

**Comment by ericlagergren** [comment]
> My ed25519 keys generated in go don't work on other systems.

Perhaps you should demonstrate how Go differs from other systems.

**Comment by master255** [comment]
OK. I checked the keys with Java bouncycastle and they match. Apparently everything is correct.
[This code](https://github.com/arvidn/libtorrent/blob/RC_2_0/src/ed25519/keypair.cpp) confused me. Apparently they use their own version ed25519

**Comment by master255** [comment]
@AlexanderYastrebov @ericlagergren But I'm right. I got zeros from the bytes in [that string](https://github.com/golang/go/blob/1e690409206ff97330b5a91517d453fc5129bab2/src/crypto/internal/edwards25519/scalar.go#L128):
```
        s.setShortBytes(x[:21])
	t := new(Scalar).setShortBytes(x[21:42])
	s.Add(s, t.Multiply(t, scalarTwo168))
	**fmt.Println("public: ", x[42:])   = [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]**
	t.setShortBytes(x[42:])
	s.Add(s, t.Multiply(t, scalarTwo336))
```
Is this an error in the standard? Why do we perform operations with zeros?

**Comment by AlexanderYastrebov** [comment]
@master255 I think it may help if you provide a runnable code snippet (e.g. via https://go.dev/play/) to demonstrate the problem you observe.

**Comment by master255** [comment]
@AlexanderYastrebov This can't help. Since it is necessary to edit the crypto package files to show the problem.

**Comment by AlexanderYastrebov** [comment]
@master255 Do not worry, there are a lot of people here who can edit crypto package. I am proposing that you show _your_ code that generates ed25519 keys that don't work on other systems.

**Comment by master255** [comment]
@AlexanderYastrebov No. There's no problem with the calculations (although they're very strange, too). It is necessary refactoring to speed up the calculation.
