### ISSUE TITLE
x/website: Cursor color on the Tour of Go editor in dark mode is not readable 

### ISSUE THREAD

**Issue by Manish-Giri** [golang/go#63313]
### What is the URL of the page with the issue?
https://go.dev/tour/welcome/1

### What is your user agent?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36

### Screenshot

<img width="438" alt="Screenshot 2023-09-30 at 9 59 17 AM" src="https://github.com/golang/go/assets/11348778/26937473-c4d6-42fb-a5dc-d53fef8316a4">

Notice the **barely-visible** black cursor at the end of the `fmt.Println()` statement. It looks like the color was selected for the light mode and never adjusted for dark mode. Below is the same cursor in light mode.

<img width="408" alt="Screenshot 2023-09-30 at 10 02 40 AM" src="https://github.com/golang/go/assets/11348778/0ff70737-48a6-4de4-be39-34d59018a29b">

### What did you do?

1. Visit tour of go.
2. Turn on dark mode.

### What did you expect to see?
A clearly visible cursor.

### What did you see instead?
See screenshot above.

**Comment by AlexanderYastrebov** [comment]
Created https://github.com/golang/website/pull/253 to fix cursor and selection colors.

![Screenshot from 2023-10-01 00-27-07](https://github.com/golang/go/assets/697976/a1788eec-b664-49d0-9d34-2e34f478367f)
![Screenshot from 2023-10-01 00-25-56](https://github.com/golang/go/assets/697976/06ec1a59-54a9-4988-859a-95fc17f08a80)
![Screenshot from 2023-10-01 00-26-00](https://github.com/golang/go/assets/697976/76be74e3-0ef0-4147-bd65-093dead3c692)
