### ISSUE TITLE
cmd/gc: escape analysis should free objects that could not be stack allocated

### ISSUE THREAD

**Issue by lexprfuncall** [golang/go#6331]
<pre>A recent change set a threshold of 16MiB for stack allocating objects.  Objects larger
than 16MiB will be heap allocated even when their scope is known to be limited.

Instead of treating these objects as having indefinite scope, the compiler could
automatically insert a call to free when their containing scope is exited.

Looking toward the future, this is probably not profitable for small objects as better
garbage collection mechanisms are known to outperform individual frees.  This is usually
not the case for large objects as garbage collectors  make a lifetime assumption based
on the size of an object.  In the large object case an explicit reclamation is likely to
be a win into the future.</pre>

**Comment by dvyukov** [comment]
Runtime now does not have a free function. Closing this for now as non-actionable.
If/when we have some idea of what to do with these allocations, we can reopen this issue.
