### ISSUE TITLE
debug/buildinfo,internal/xcoff: oom (infinite loop ?)

### ISSUE THREAD

**Issue by catenacyber** [golang/go#63337]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

It happens only on gotip, not on go 1.21

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/root/.go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/root/.go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.21"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/src/ngolo-fuzzing/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2481516251=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Run https://go.dev/play/p/9MShhrc8jgK?v=gotip

### What did you expect to see?

The program finishing and printing Hello, without allocating too much
(as happens with go 1.21)

Regression range is given as 5fe3f0a265c90a9c0346403742c6cafeb154503b:856cf23a8acfa14756a6e9b82ace76f5604262c9

### What did you see instead?

Nothing : Program exited

Found by https://github.com/catenacyber/ngolo-fuzzing with oss-fuzz : 
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=62574

**Comment by mauri870** [comment]
I was able to reproduce this in linux as well as macos. I believe it is related to [CL514075](https://go-review.googlesource.com/c/go/+/514075), issue #61644.

The initial magic bytes matches conditions for xcoff, the routine that is causing the high memory usage is xcoffExe.ReadData, particulary the line with [saferio.ReadDataAt](https://github.com/golang/go/blob/17d67ed0c904871bb2738ec7d1ed7831924c9aaf/src/debug/buildinfo/buildinfo.go#L399)

**Comment by mauri870** [comment]
@gopherbot add NeedsFix

**Comment by mauri870** [comment]
Same issue as https://github.com/golang/go/issues/59817, but there it was fixed for PE.

**Comment by AlexanderYastrebov** [comment]
I think the logic is disconnected here: https://github.com/golang/go/blob/340a4f55c4afac5b74c8df8365decb0c0237d710/src/debug/buildinfo/buildinfo.go#L151-L163

It tries to locate data section address by section type (x.DataStart()):
https://github.com/golang/go/blob/340a4f55c4afac5b74c8df8365decb0c0237d710/src/debug/buildinfo/buildinfo.go#L405-L410

but then finds a wrong section based on the virtual address (x.ReadData()):
https://github.com/golang/go/blob/340a4f55c4afac5b74c8df8365decb0c0237d710/src/debug/buildinfo/buildinfo.go#L392-L403

The wrong section happens to be a .bss section that uses zeroReaderAt that reads infinite amount of zeroes:
https://github.com/golang/go/blob/340a4f55c4afac5b74c8df8365decb0c0237d710/src/internal/xcoff/file.go#L263-L265

Its not clear whether sections virtual addresses could actually overlap, if not then this should be validated during parsing.
Also using a never-ending reader does not seem like a safe choice.

**Comment by AlexanderYastrebov** [comment]
Maybe using eofReaderAt that always returns 0, io.EOF for .bss instead of zeroReaderAt would be enough to fix this.

**Comment by mauri870** [comment]
@AlexanderYastrebov Would you be willing to send in a fix? Thanks
