### ISSUE TITLE
cmd/compile: //go:nointerface error misreported as ICE

### ISSUE THREAD

**Issue by mdempsky** [golang/go#63333]
Compiling this package with `GOEXPERIMENT=fieldtrack` causes an ICE, when it should just report a compiler error:

```
package p

func f(interface{ m() }) {}
func g() { f(new(T)) }

type T struct {}

//go:nointerface
func (*T) m() {}
```

**Comment by cuonglm** [comment]
This seems to be present since `-G=3` added.

The old typechecker problem exposed by https://go-review.googlesource.com/c/go/+/394575.

I'm not sure what's the best place to address this, types2 does not know about `go:nointerface` pragma.

**Comment by cuonglm** [comment]
> I'm not sure what's the best place to address this, types2 does not know about go:nointerface pragma.

Probably we should just error out during `tcConv` instead of fatal. That would catch invalid conversion due to go pragma.
