### ISSUE TITLE
code cannot run on macOS Sonoma if ".app" is in the module name

### ISSUE THREAD

**Issue by andydotxyz** [golang/go#63368]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.1 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes, with any go version

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOOS='darwin'
GOARCH='arm64'
</pre></details>

### What did you do?

* Set the `module` of go.mod to `myco.app`
* run `go run` for any `main.go` content
* Notice that darwin will kill the app

### What did you expect to see?

The application would run

### What did you see instead?

```
[main] ><> go run .
# myco.app
ld: warning: ignoring duplicate libraries: '-lobjc'
signal: killed
```

There is strange info in the console - but it is probably a red herring as simply changing ".app" to "_app" fixes the issue.
It would seem that in macOS Sonoma (not earlier) it gets confused, thinking this is a .app bundle when compiled using the Go toolchain.

Notably if you build and then change the filename ('myco.app' -> 'myco_app') the execution will succeed.

**Comment by andydotxyz** [comment]
This seems to be the cause of https://github.com/fyne-io/fyne/issues/4296

**Comment by seankhliao** [comment]
If that's the case, I'm not sure there's anything go can do about it?

**Comment by andydotxyz** [comment]
Why not? There is no requirement that the output binary has the same name as the module...
If your statement holds then the Go project would basically be asserting that "top level .app domain names cannot be used for Go modules".

Why not update so output file names cannot match certain known problematic patterns?

**Comment by seankhliao** [comment]
The current rule is simple and consistent, we've consistently chosen not to mangle executable names, even when you may have multiple that clash in a module and build with `./...`.
If you need a different default name for your application, use a (sub)directory: https://go.dev/doc/modules/layout#multiple-commands

**Comment by andydotxyz** [comment]
The name of my app is fine, and has worked for a while. I don't want to change it.

Is the go team seriously happy to be building executables that are non-functional?
