### ISSUE TITLE
x/tools/gopls/internal/span: TestURIFromPath fail in windows 

### ISSUE THREAD

**Issue by qiulaidongfeng** [golang/go#63366]
### What version of Go are you using (`go version`)?

<pre>
$ go version
tip
</pre>

### Does this issue reproduce with the latest release?

yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

git clone https://github.com/golang/tools
cd tools
cd gopls
go test ./...

### What did you expect to see?
Test Passed.

### What did you see instead?
```
--- FAIL: TestURIFromPath (0.00s)
    uri_windows_test.go:63: URIFromPath("\\path\\to\\dir"): got "file:///E:/path/to/dir", expected "file:///C:/path/to/dir"
    uri_windows_test.go:67: Filename("file:///E:/path/to/dir"): got "E:\\path\\to\\dir", expected "C:\\path\\to\\dir"
    uri_windows_test.go:63: URIFromPath("\\a\\b\\c\\src\\bob.go"): got "file:///E:/a/b/c/src/bob.go", expected "file:///C:/a/b/c/src/bob.go"
    uri_windows_test.go:67: Filename("file:///E:/a/b/c/src/bob.go"): got "E:\\a\\b\\c\\src\\bob.go", expected "C:\\a\\b\\c\\src\\bob.go"
FAIL
exit status 1
FAIL    golang.org/x/tools/gopls/internal/span  1.701s
```

**Comment by findleyr** [comment]
This test is build tagged !windows, so failure is expected. Our CI regularly runs tests on windows.

Are you overriding GOOS?

**Comment by qiulaidongfeng** [comment]
I am running go test on gopls ./...

**Comment by qiulaidongfeng** [comment]
see https://github.com/golang/tools/blob/master/gopls/internal/span/uri_windows_test.go#L5-L20 ,The build label is Windows.

**Comment by hyangah** [comment]
Similar issue like https://github.com/golang/go/issues/63363. Need to avoid the hard-coded drive name (C:)

**Comment by findleyr** [comment]
@qiulaidongfeng my apologies, I blame gopls's lack of build tag support :)
(which we're working on!)

**Comment by adonovan** [comment]
The problem (as @hyangah points out) is that filepath.Abs will prepend a drive letter based on where the x/tools repo was cloned. The test should not assume `C:`, but should normalize the path to replace `^[A-Z]:` by `C:` before the assertion.
