### ISSUE TITLE
x/tools/gopls/internal/lsp/cache: TestFileMap fail in windows

### ISSUE THREAD

**Issue by qiulaidongfeng** [golang/go#63363]
### What version of Go are you using (`go version`)?

<pre>
$ go version
tip
</pre>

### Does this issue reproduce with the latest release?
yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

git clone https://github.com/golang/tools
cd tools
cd gopls
go test ./...

### What did you expect to see?
Test passed.

### What did you see instead?

--- FAIL: TestFileMap (0.00s)
    --- FAIL: TestFileMap/singleton (0.00s)
        filemap_test.go:87: Files mismatch (-want +got):
              []string{
            -   "/a/b",
            +   "E:/a/b",
              }
        filemap_test.go:104: Dirs mismatch (-want +got):
              []string{
            -   "/",
            +   "E:/",
            -   "/a",
            +   "E:/a",
              }
    --- FAIL: TestFileMap/overlay (0.00s)
        filemap_test.go:87: Files mismatch (-want +got):
              []string{
            -   "/a/b",
            +   "E:/a/b",
              }
        filemap_test.go:95: Overlays mismatch (-want +got):
              []string{
            -   "/a/b",
            +   "E:/a/b",
              }
        filemap_test.go:104: Dirs mismatch (-want +got):
              []string{
            -   "/",
            +   "E:/",
            -   "/a",
            +   "E:/a",
              }
    --- FAIL: TestFileMap/replace_overlay (0.00s)
        filemap_test.go:87: Files mismatch (-want +got):
              []string{
            -   "/a/b",
            +   "E:/a/b",
              }
        filemap_test.go:104: Dirs mismatch (-want +got):
              []string{
            -   "/",
            +   "E:/",
            -   "/a",
            +   "E:/a",
              }
    --- FAIL: TestFileMap/multi_dir (0.00s)
        filemap_test.go:87: Files mismatch (-want +got):
              []string{
            -   "/a/b",
            +   "E:/a/b",
            -   "/c/d",
            +   "E:/c/d",
              }
        filemap_test.go:104: Dirs mismatch (-want +got):
              []string{
            -   "/",
            +   "E:/",
            -   "/a",
            +   "E:/a",
            -   "/c",
            +   "E:/c",
              }
    --- FAIL: TestFileMap/empty_dir (0.00s)
        filemap_test.go:87: Files mismatch (-want +got):
              []string{
            -   "/c/d",
            +   "E:/c/d",
              }
        filemap_test.go:104: Dirs mismatch (-want +got):
              []string{
            -   "/",
            +   "E:/",
            -   "/c",
            +   "E:/c",
              }
FAIL
exit status 1
FAIL    golang.org/x/tools/gopls/internal/lsp/cache     0.232s

**Comment by hyangah** [comment]
@findleyr Looks like the `normalize` uses a hard-coded "C:" drive name, which can be problematic for some users.
