### ISSUE TITLE
x/tools/go/ssa: add support for range-over-int

### ISSUE THREAD

**Issue by findleyr** [golang/go#63373]
Per https://github.com/golang/go/issues/61405#issuecomment-1727898328, it is likely that range-over-int will land for 1.22.

This issue tracks supporting this new range form in x/tools/go/ssa. Marking as a release blocker because we endeavor to keep our tools in sync with language changes.

**Comment by adonovan** [comment]
I think the change to the builder is actually very small: https://go.dev/cl/532580
The hard part is plumbing the version through.
