### ISSUE TITLE
bad error

### ISSUE THREAD

**Issue by iamhassanfaraji** [golang/go#63388]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.21.1 linux/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/hassanfaraji/.cache/go-build'
GOENV='/home/hassanfaraji/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/usr/local/go/bin/src/cmd/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/usr/local/go/bin/src/cmd'
GOPRIVATE=''
GOPROXY=''
GOROOT='/usr/local/go/bin'
GOSUMDB=''
GOTMPDIR=''
GOTOOLCHAIN=''
GOTOOLDIR='/usr/local/go/bin/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.1'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3843205642=/tmp/go-build -gno-record-gcc-switches'
</pre></details>

### What did you do?

my code is 
<pre>
package main

import("fmt") 

func main(){
	name = "hassan faraji"

	fmt.Printf("%v \n", name)
}
</pre>

and return this error:

<pre>
# example.com/hello
./hello.go:6:2: undefined: name
./hello.go:8:22: undefined: name
</pre>

### What did you expect to see?

i have syntax error in declaring variable name
and get "undefined variable name" error
 
### What did you see instead?

report syntax error when declaring variable

**Comment by Jorropo** [comment]
```
name = "hassan faraji"
```
is valid syntax.
This is the syntax you use to reasign variables:
```go
name := "example"
name = "hassan faraji"
fmt.Println(name)
```
So everything is working as intended here.
I guess this could be improved by having the compiler try to guess what you are trying to do, but this would be a pretty big error philosophy change.

---

Golang do not use the issue tracker for questions and discussions. I encourage you to take a look at https://go.dev/wiki/Questions.

**Comment by ianlancetaylor** [comment]
This is not a syntax error.  The variable can be declared elsewhere.  For example, this is valid Go code:

```Go
package main

import("fmt") 

var name string

func main(){
	name = "hassan faraji"

	fmt.Printf("%v \n", name)
}
```
