### ISSUE TITLE
proposal: Go 2: errors handling

### ISSUE THREAD

**Issue by sultan-mo** [golang/go#63380]
### Author background

- An expert Go developer using it on daily basis 
- Excellent in C and good in Rust 

### Proposal

I think Go can add some syntax sugar that make the error handling easier. Developer can mark an error with a marker/operator and if this marked error is not 'nil' it's value will be returned. 

Example 

'''go
 err! := example.ShouldRetErr()
'''

The '!' operator will simulates checking the err value and returning it if it's not 'nil' (maybe replace it with if statement behind-the-scenes) and we don't need to rewrite the if statement every time we get an error as a return. 

The if statement errors handling still doable which guarantees backward compatibility.

**Comment by seankhliao** [comment]
see #14066 #36390 #60779 #62253
