### ISSUE TITLE
x/tools/cmd/compilebench: loadinternal: cannot find runtime/cgo

### ISSUE THREAD

**Issue by qiulaidongfeng** [golang/go#63383]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.21.1
</pre>

### Does this issue reproduce with the latest release?

yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

go install golang.org/x/tools/cmd/compilebench@latest
compilebench -alloc

### What did you expect to see?

Normal benchmark.

### What did you see instead?

loadinternal: cannot find runtime/cgo

**Comment by prattmic** [comment]
cc @golang/compiler

**Comment by cherrymui** [comment]
Could you show the complete output? What platform do you run on?

`loadinternal: cannot find runtime/cgo` this line is just a print, not an error. Do you still get the benchmark results?

**Comment by qiulaidongfeng** [comment]
Run on Linux/amd64
output:
```
BenchmarkTemplate 1 266844474 ns/op 358912000 user-ns/op
BenchmarkUnicode 1 125062571 ns/op 139210000 user-ns/op
BenchmarkGoTypes 1 1731786734 ns/op 2655056000 user-ns/op
BenchmarkCompiler 1 97326266 ns/op 107688000 user-ns/op
BenchmarkSSA 1 11858574099 ns/op 18812607000 user-ns/op
BenchmarkFlate 1 129268703 ns/op 180482000 user-ns/op
BenchmarkGoParser 1 252441849 ns/op 389266000 user-ns/op
BenchmarkReflect 1 623183863 ns/op 978348000 user-ns/op
BenchmarkTar 1 230124921 ns/op 321653000 user-ns/op
BenchmarkXML 1 251384006 ns/op 382333000 user-ns/op
BenchmarkLinkCompiler 1 501002715 ns/op 730779000 user-ns/op
loadinternal: cannot find runtime/cgo
BenchmarkExternalLinkCompiler 1 1502519909 ns/op 1492371000 user-ns/op
BenchmarkLinkWithoutDebugCompiler 1 242237716 ns/op 257949000 user-ns/op
BenchmarkStdCmd 1 122730287736 ns/op
BenchmarkHelloSize 1 804035 text-bytes 14624 data-bytes 203368 bss-bytes 1284840 exe-bytes
BenchmarkCmdGoSize 1 11216349 text-bytes 305074 data-bytes 235440 bss-bytes 16734189 exe-bytes
```

see https://github.com/golang/go/blob/master/src/cmd/link/internal/ld/lib.go#L450,It seems that it was printed by the link. Is this an error in the link or is it the debugging information for the link?

**Comment by cherrymui** [comment]
It is just a diagnostic message the linker prints. It is not an error. It should still generate the correct program.

That said, since #31544 is fixed, we probably could arrange compilebench to pass a more correct configuration to avoid this.
