### ISSUE TITLE
affected/package: syscall/js, build constraints exclude all Go files

### ISSUE THREAD

**Issue by dimkauzh** [golang/go#63396]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.1 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### Issue

Hi everyone reading this. So I recently got into syscall/js package and I wanted to build a package using it. It was gonna be a web-only game engine. I'm currently running all my tests with wasmserve, but i sometimes also compile to web-assembly. But this is the issue: I get this error: `imports syscall/js: build constraints exclude all Go files in /usr/local/Cellar/go/1.21.1/libexec/src/syscall/js`. Normally to avoid this error when running i just use wasmserve or compile it with these flags: `GOOS=js GOARCH=wasm`, but gopls gives me a error when i use that code:
<img width="1579" alt="Screenshot 2023-10-05 at 18 09 18" src="https://github.com/golang/go/assets/106883655/927e5c52-53e4-4846-9098-2c65422ac4ba">
As you see in the picture im trying to interact with the package I build but its telling me theres a error and it really annoys me. Is there any way of fixing this?

The link to the package I'm building with syscall/js: https://github.com/dimkauzh/webzen

**Comment by seankhliao** [comment]
gopls has options for setting the build tags

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by dimkauzh** [comment]
> gopls has options for setting the build tags
> 
> Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.
> 
> For questions please refer to https://github.com/golang/go/wiki/Questions

Okay thanks!
