### ISSUE TITLE
golang pointer sometimes work, sometimes fail, quite confuse when using it

### ISSUE THREAD

**Issue by babashark** [golang/go#63409]
### What version of Go are you using (`go version`)?
go 1.21

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
it can be reproduced using golang playground
https://go.dev/play/p/xaoxoY_M9Ao

### What did you do?
please refer to the link above or the picture below:
https://go.dev/play/p/xaoxoY_M9Ao

<img width="858" alt="image" src="https://github.com/golang/go/assets/127459243/2b2eeaf8-c058-4f18-8d32-8da32f867b97">

### What did you expect to see?
I expect variable m1 can be assigned a time value successfully

### What did you see instead?
variable m1 failed to assign a value, but it works if I am using a struct with a time field

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
