### ISSUE TITLE
[BUG] Golang run on Windows without deal with the Firewall

### ISSUE THREAD

**Issue by swarajkumarsingh** [golang/go#63410]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.6 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
<pre>
Yes
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Swaraj Singh\AppData\Local\go-build
set GOENV=C:\Users\Swaraj Singh\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Swaraj Singh\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Swaraj Singh\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=D:\Software\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Software\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.20.6
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\SWARAJ~1\AppData\Local\Temp\go-build3512185934=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### How to reproduce

```
func main() {
	r := gin.Default()

	r.GET("/", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{
			"message": "health ok",
		})
	})

	log.Printf("Server Started, version: %s", version)
	r.Run(":8080")
}
```

### What did you do?
<pre>
I'm working on a Rest API with Go, but every time I try to run my application with **go run main.go**

the Windows Firewall tells me that has blocked some features of my app. I would like to know if there's some way to make my executions without having to Accept every time.
</pre>

### What did you expect to see?
<pre>
I see a Windows firewall appearing every time, I run main.go, it becomes very irritating at times
</pre>

### What did you see instead?
<pre>
Just run the program without the Windows firewall pop
</pre>
![image](https://github.com/golang/go/assets/89764448/d994e0bc-d04a-44a3-82c3-0fb5fa0cd32c)

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by swarajkumarsingh** [comment]
Sure

**Comment by swarajkumarsingh** [comment]
# The perfect solution 💕

**Issue:** Windows blocks applications that try to use localhost by default, for some security reasons.

**Solution:** We will add a localhost add before the PORT, to specify Golang & Windows to run the program in localhost and not access other systems

**Solution in code:**

```
func main() {
	r := gin.Default()

	r.GET("/", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{
			"message": "health ok",
		})
	})
        // Add localhost tag
	r.Run("localhost:8080")
}

```

**Comment by iamSuva** [comment]
Yes ,to avoid the pop we can run

func main(){
       router := gin.Default()

	router.GET("/api",func(ctx *gin.Context) {
		ctx.JSON(http.StatusOK,gin.H{
			"message":"Hello welcome to golang gin webframework",
			"status":http.StatusOK,
		})
	 })
       router.Run("localhost:8080")
}
