### ISSUE TITLE
x/telemetry: present the list of approved counters in telemetry.go.dev

### ISSUE THREAD

**Issue by hyangah** [golang/go#63418]
The list of approved counters is in the golang.org/x/telemetry/config module.
https://go.googlesource.com/telemetry/+/refs/heads/master/config/config.json
(this is linked from a section in https://telemetry.go.dev/privacy, but I don't think the `privacy` page is the first page users would think of when looking up such info).

Present it in a human-friendly way and make it more discoverable from the telemetry.go.dev main page.

**Comment by findleyr** [comment]
Pragmatically blocked by #63504
