### ISSUE TITLE
affected/package: 

### ISSUE THREAD

**Issue by 863377977** [golang/go#63443]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.21.2
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

use https://pkg.go.dev/crypto/rsa#SignPSS

In rsa/pss.go 
func emsaPSSEncode
// 3.  If emLen < hLen + sLen + 2, output "encoding error" and stop.

	if emLen < hLen+sLen+2 {
		return nil, ErrMessageTooLong
	}

My saltlen is too big

### What did you expect to see?

Error should prompt me about saltlen

### What did you see instead?

But error is "crypto/rsa: message too long for RSA key size"
message is irrelevant

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.
