### ISSUE TITLE
testing/fstest: set perm 0555 for synthetized directories in MapFS

### ISSUE THREAD

**Issue by dolmen** [golang/go#63468]
`testing/fstest.MapFS` should set a [FileMode](https://pkg.go.dev/io/fs#FileMode) compatible with its behaviour: as reading and traversing directories just ignores filemodes (it doesn't check filemode before giving access to file content or directory content), it would be more consistent to synthetise directories with mode `fs.ModeDir | 0555` instead of `fs.ModeDir | 0000`.

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What did you do?

https://go.dev/play/p/3_nH4WnurYA

```go
func Test(t *testing.T) {
	m := fstest.MapFS{
		"subdir/a.txt": &fstest.MapFile{
			Mode: 0444,
		},
		"subdir/subdir2/a.txt": &fstest.MapFile{
			Mode: 0444,
		},
	}

	info, err := fs.Stat(m, "subdir")
	if err != nil {
		t.Fatal(err)
	}
	t.Logf("%o %[1]s %s", info.Mode(), info.Name())

	info, err = fs.Stat(m, "subdir/subdir2")
	if err != nil {
		t.Fatal(err)
	}
	t.Logf("%o %[1]s %s", info.Mode(), info.Name())

	// t.Logf("%o %[1]s", info.Mode() | 0555)
}
```

### What did you expect to see?

```
=== RUN   Test
    prog_test.go:23: 20000000555 dr-xr-xr-x subdir
    prog_test.go:29: 20000000555 dr-xr-xr-x subdir2
--- PASS: Test (0.00s)
PASS
```

### What did you see instead?

```
=== RUN   Test
    prog_test.go:23: 20000000000 d--------- subdir
    prog_test.go:29: 20000000000 d--------- subdir2
--- PASS: Test (0.00s)
PASS
```

**Comment by dolmen** [comment]
Fix:
```patch
diff --git a/src/testing/fstest/mapfs.go b/src/testing/fstest/mapfs.go
index a0b1f65668..b3fc0c8ad7 100644
--- a/src/testing/fstest/mapfs.go
+++ b/src/testing/fstest/mapfs.go
@@ -98,14 +98,14 @@ func (fsys MapFS) Open(name string) (fs.File, error) {
                delete(need, fi.name)
        }
        for name := range need {
-               list = append(list, mapFileInfo{name, &MapFile{Mode: fs.ModeDir}})
+               list = append(list, mapFileInfo{name, &MapFile{Mode: fs.ModeDir | 0555}})
        }
        sort.Slice(list, func(i, j int) bool {
                return list[i].name < list[j].name
        })
 
        if file == nil {
-               file = &MapFile{Mode: fs.ModeDir}
+               file = &MapFile{Mode: fs.ModeDir | 0555}
        }
        return &mapDir{name, mapFileInfo{elem, file}, list, 0}, nil
 }
```

**Comment by dmitshur** [comment]
CC @bcmills, @ianlancetaylor.

**Comment by ianlancetaylor** [comment]
Want to send a patch?  https://go.dev/doc/contribute.

**Comment by dolmen** [comment]
🎉

**Comment by jsageryd** [comment]
While I do agree that it makes sense for directories to have `0555` set, this change actually broke my tests that relied on `fstest.MapFS` synthesizing directories with only mode `fs.ModeDir`. The exact behaviour of `fstest.MapFS` wasn't documented and I suppose one might even be able to call the previous behaviour a bug, so I don't _think_ it breaks the Go 1 compatibility promise, and I have no issue with that part.

However, the documentation does still suggest that a directory can be created by setting the file mode to `fs.ModeDir`. This is true, but following this recommendation now results in a directory that differs from what `fs.MapFS` would synthesize by default. Would it make sense to update the documentation to recommend setting the mode to `fs.ModeDir | 0555` (or perhaps `fs.ModeDir | 0o555`)?

> The map need not include parent directories for files contained in the map; those will be synthesized if needed. But a directory can still be included by setting the [MapFile.Mode]'s [fs.ModeDir](https://pkg.go.dev/io/fs#ModeDir) bit; this may be necessary for detailed control over the directory's [fs.FileInfo](https://pkg.go.dev/io/fs#FileInfo) or to create an empty directory.

https://pkg.go.dev/testing/fstest
