### ISSUE TITLE
x/telemetry/cmd/gotelemetry: add option to quiet output

### ISSUE THREAD

**Issue by timothy-king** [golang/go#63476]
I tried to add gotelemetry to my startup. However, I really to do not want to see this in every terminal I create:
```
Telemetry uploading is now enabled and data will be periodically sent to https://telemetry.go.dev/. Uploaded data is used to help improve the Go toolchain and related tools, and it will be published as part of a public dataset.

For more details, see https://telemetry.go.dev/privacy.
This data is collected in accordance with the Google Privacy Policy (https://policies.google.com/privacy).

To disable telemetry uploading, run “gotelemetry off”.
taking:~%
```
If possible I would like to ack this once or periodically as long as nothing has changed. Otherwise I would like it to not see this message on startup.

I am also okay with a `-q` flag.

**Comment by dmitshur** [comment]
CC @pjweinb, @hyangah, @findleyr.

**Comment by findleyr** [comment]
> If possible I would like to ack this once or periodically as long as nothing has changed

Hmm, currently we reset the ack date every time this command is invoked, which would mean we won't subsequently upload anything from *before* that time. If users are going to occasionally re-acknowledge, I should probably change this logic to preserve the original ack date.

 Adding `-q` seems OK to me, since it is explicitly added by the user. CC @rsc as I think this communication was a key part of the opt-in design.

**Comment by hyangah** [comment]
I want to understand the use case. @timothy-king 
 Why do you want to run this command every time? Is it for collecting container telemetry?

**Comment by timothy-king** [comment]
@hyangah I wanted to add this to .vshrc to set this up once and then not worry about it. I know this is probably not the best file, but it was easy for me. Hence every terminal. It ended up being a bit noisy.

**Comment by hyangah** [comment]
@timothy-king Once you run `gotelemetry on`, that's persisted on your user configuration, so you wouldn't need to rerun the command until you switch machines or format the disk strictly speaking.

cl/534195 makes gotelemetry read the configuration before making the change and skip modification if the old/new values are same. This won't help if you run the command again for a new machine or in a container, but I hope it's ok for your use case.

**Comment by timothy-king** [comment]
Looks like I had the wrong mental model of what `gotelemetry` was doing. Looks like a `-q` mode is not needed for my use case.
