### ISSUE TITLE
compiler error logger

### ISSUE THREAD

**Issue by iamhassanfaraji** [golang/go#63475]
### What version of Go are you using (`go version`)?

<pre>
$ go version  go1.21.1 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/hassanfaraji/.cache/go-build'
GOENV='/home/hassanfaraji/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/hassanfaraji/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/hassanfaraji/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.1'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2079238861=/tmp/go-build -gno-record-gcc-switches'
</pre></details>

### What did you do?

its my code:
<pre>
package main

import (
	"fmt"
)

func sum(args ...int){
	var total int = 0
	for _, arg := range args {
		total += arg
	}
	return total
}

func main() {
	x := sum(1, 2, 3)
	fmt.Println(x)
}

</pre>

and compiler show these report:
<pre>
  # command-line-arguments
./func.go:12:9: too many return values
        have (int)
        want ()
./func.go:16:7: add(1, 2, 3) (no value) used as value
</pre>

### What did you expect to see?
in sum function, total var after computing (sum)  is simple int ( not []int ) and seems everything should be ok 
and app should be run 

### What did you see instead?
"wrongResultCount" and "tooManyValues" errors occur  

and when set specify return type of sum function, error fixed
<pre>
package main

import (
	"fmt"
)

func sum(args ...int)  int  {
	var total int = 0
	for _, arg := range args {
		total += arg
	}
	return total
}

func main() {
	x := sum(1, 2, 3)
	fmt.Println(x)
}
</pre>

its better not need to add " int " type for returned value of sum funcation

**Comment by seankhliao** [comment]
This is just how the language works.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
