### ISSUE TITLE
cmd/go: `mod vendor` tries to evaluate go:embed pattern inside _test.go files

### ISSUE THREAD

**Issue by wizardishungry** [golang/go#63473]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.1 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

I don't know.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/jon/Library/Caches/go-build'
GOENV='/Users/jon/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/jon/.asdf/installs/golang/1.21.1/packages/pkg/mod'
GONOPROXY='bitbucket.org/thetalake'
GONOSUMDB='bitbucket.org/thetalake'
GOOS='darwin'
GOPATH='/Users/jon/.asdf/installs/golang/1.21.1/packages'
GOPRIVATE='bitbucket.org/thetalake'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/Users/jon/.asdf/installs/golang/1.21.1/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/Users/jon/.asdf/installs/golang/1.21.1/go/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.21.1'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/jon/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/4y/nhc3l04n53x2125plghk78bw0000gp/T/go-build3701474416=/tmp/go-build -gno-record-gcc-switches -fno-common'
</pre></details>

### What did you do?

1. Import a package containing `go:embed` directives inside a `_test.go` file. 
```go
import _ "github.com/emiago/sipgo"
```
For example, https://github.com/emiago/sipgo/blob/main/server_integration_test.go#L26 contains `go:embed` directives that will not satisfied.

2. Run `go mod vendor`:

### What did you expect to see?
`go mod vendor` completes normally

### What did you see instead?
```
go: pattern testdata/certs/client.crt: no matching files found
```

**Comment by seankhliao** [comment]
working as intended. vendor aims to make it possible to both build and run tests for your dependencies (`go test all`)

**Comment by wizardishungry** [comment]
@seankhliao The `go:embed` I mentioned is included in the vendored package's test code. The go mod vendor documentation says: 

> Vendor resets the main module's vendor directory to include all packages
> needed to build and test all the main module's packages.
> **It does not include test code for vendored packages.**
(*Emphasis mine*)

It's fine if this isn't going to get fixed, but `go mod vendor` absolutely does not include `_test` files.

**Comment by seankhliao** [comment]
Sorry, I misremembered.

cc @bcmills

**Comment by quantonganh** [comment]
So, according to the `go help mod vendor`:

```
$ go help mod vendor
usage: go mod vendor [-e] [-v] [-o outdir]

Vendor resets the main module's vendor directory to include all packages
needed to build and test all the main module's packages.
It does not include test code for vendored packages.
```

We [should not include embed patterns in test files](https://github.com/golang/go/blob/33cdafed5213a17d23baa92568ede4bb16e7af0c/src/cmd/go/internal/modcmd/vendor.go?plain=1#L316) when vendoring?
