### ISSUE TITLE
kubernetes: deepcopy.go:887 Hit an unsupported type invalid type for invalid type

### ISSUE THREAD

**Issue by KorolevSD** [golang/go#63493]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 gccgo (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes (I also get an error using gccgo-13. This is the last gccgo in ubuntu.)

### What operating system and processor architecture are you using (`go env`)?
<pre>
$ uname -a
VB-U22 6.2.0-33-generic #33~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 10:33:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
</pre>

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT="fieldtrack,regabiwrappers"
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/gcc/x86_64-linux-gnu/12"
GOVCS=""
GOVERSION="go1.18 gccgo (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0"
GCCGO="/usr/bin/x86_64-linux-gnu-gccgo-12"
GOAMD64="v1"
AR="ar"
CC="x86_64-linux-gnu-gcc-12"
CXX="x86_64-linux-gnu-g++-12"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3362027528=/tmp/go-build -gno-record-gcc-switches -funwind-tables"

</pre></details>

### What did you do?

<pre>
git clone https://github.com/kubernetes/kubernetes.git
cd kubernetes/
git checkout v1.23.17
apt install gccgo-12
ln -s /usr/bin/go-12 /usr/bin/go
make
</pre>
### What did you expect to see?

I expected to see a successful build

### What did you see instead?

<pre>
make
+++ [1010 19:58:02] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/prerelease-lifecycle-gen
> non-static build: k8s.io/kubernetes/./vendor/k8s.io/code-generator/cmd/prerelease-lifecycle-gen
Generating prerelease lifecycle code for 28 targets
+++ [1010 19:58:18] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/deepcopy-gen
> non-static build: k8s.io/kubernetes/./vendor/k8s.io/code-generator/cmd/deepcopy-gen
Generating deepcopy code for 238 targets
F1010 19:58:34.604514  107695 deepcopy.go:887] Hit an unsupported type invalid type for invalid type, from k8s.io/component-base/config/v1alpha1.LoggingConfiguration

goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks
	/root/errors/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1038
k8s_0io_1kubernetes_1vendor_1k8s_0io_1klog_1v2.loggingT.output
	/root/errors/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:987
k8s_0io_1kubernetes_1vendor_1k8s_0io_1klog_1v2.loggingT.printf
	/root/errors/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:753
k8s_0io_1kubernetes_1vendor_1k8s_0io_1klog_1v2.Fatalf
	/root/errors/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1532
k8s_0io_1kubernetes_1vendor_1k8s_0io_1gengo_1examples_1deepcopy_x2dgen_1generators.genDeepCopy.doStruct
	/root/errors/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/gengo/examples/deepcopy-gen/generators/deepcopy.go:887
k8s_0io_1kubernetes_1vendor_1k8s_0io_1gengo_1examples_1deepcopy_x2dgen_1generators.genDeepCopy.generateFor
	/root/errors/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/gengo/examples/deepcopy-gen/generators/deepcopy.go:695
k8s_0io_1kubernetes_1vendor_1k8s_0io_1gengo_1examples_1deepcopy_x2dgen_1generators.genDeepCopy.GenerateType
	/root/errors/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/gengo/examples/deepcopy-gen/generators/deepcopy.go:608
k8s_0io_1kubernetes_1vendor_1k8s_0io_1gengo_1generator.Context.executeBody
	/root/errors/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/gengo/generator/execute.go:306
k8s_0io_1kubernetes_1vendor_1k8s_0io_1gengo_1generator.Context.ExecutePackage
	/root/errors/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/gengo/generator/execute.go:267
k8s_0io_1kubernetes_1vendor_1k8s_0io_1gengo_1generator.Context.ExecutePackages
	/root/errors/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/gengo/generator/execute.go:51
k8s_0io_1kubernetes_1vendor_1k8s_0io_1gengo_1args.GeneratorArgs.Execute
	/root/errors/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/gengo/args/args.go:207
main.main
	/root/errors/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/deepcopy-gen/main.go:78

goroutine 18 [chan receive]:
k8s_0io_1kubernetes_1vendor_1k8s_0io_1klog_1v2.loggingT.flushDaemon
	/root/errors/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1181
created by k8s_0io_1kubernetes_1vendor_1k8s_0io_1klog_1v2.k8s_0io_1kubernetes_1vendor_1k8s_0io_1klog_1v2..init0
	/root/errors/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:420 +0xdb

goroutine 32227 [runnable]:
text_1template_1parse.lexer.emit
	../../../src/libgo/go/text/template/parse/lex.go:163
text/template/parse.lexText
	../../../src/libgo/go/text/template/parse/lex.go:275
text_1template_1parse.lexer.run
	../../../src/libgo/go/text/template/parse/lex.go:236
created by text_1template_1parse.Tree.Parse
	../../../src/libgo/go/text/template/parse/parse.go:247 +0x28e

</pre>

### Additionally

I know I can assemble the program by installing golang-1.20-go
But first I wanted to compile k8s for e2k architecture
For e2k I have only gccgo and I get the same error as in ubuntu with gccgo

I will be glad for any help in solving or working around this error.

**Comment by seankhliao** [comment]
This looks like an error from deepcopy-gen, not go or gccgo

**Comment by ianlancetaylor** [comment]
gccgo does not support generics.  I'm actively working on it but there is no ETA.
