### ISSUE TITLE
import init: now import init sort is a-z, but old is use import order

### ISSUE THREAD

**Issue by deatil** [golang/go#63500]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go1.21
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

init run e:
~~~go
import (
    _ "gotest/a"
    _ "gotest/c"
    _ "gotest/bb/a"
    _ "gotest/b"
)
~~~

now show:
~~~
a
b
bb-a
c
~~~

old show:
~~~
a
c
bb-a
b
~~~

this is a bug.

**Comment by mateusz834** [comment]
> This may change the behavior of some programs that rely on a specific initialization ordering that was not expressed by explicit imports. The behavior of such programs was not well defined by the spec in past releases. The new rule provides an unambiguous definition. 

https://go.dev/doc/go1.21#language

**Comment by deatil** [comment]
> > This may change the behavior of some programs that rely on a specific initialization ordering that was not expressed by explicit imports. The behavior of such programs was not well defined by the spec in past releases. The new rule provides an unambiguous definition.
> 
> https://go.dev/doc/go1.21#language

so, go will use the sort type for init? that, some used init for sort will change use type.

**Comment by seankhliao** [comment]
this is working as intended and documented, see #57411
