### ISSUE TITLE
affected/package: 

### ISSUE THREAD

**Issue by majiyue** [golang/go#63512]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.20.6
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/autel/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/autel/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3086384846=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

When I was using the latest gomobile, I occasionally reported an error

### What did you see instead?
uid: 10243
tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
pac_enabled_keys: 000000000000000f (PR_PAC_APIAKEY, PR_PAC_APIBKEY, PR_PAC_APDAKEY, PR_PAC_APDBKEY)
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: 'Unknown reference: 42'
    x0  0000000000000000  x1  0000000000003975  x2  0000000000000006  x3  0000006f1eac0a30
    x4  0000000000000010  x5  0000000000000010  x6  0000000000000010  x7  7f7f7f7f7f7f7f7f
    x8  00000000000000f0  x9  0000007125834cb0  x10 0000000000000001  x11 00000071258a97c8
    x12 0000006f1eabf340  x13 0000000000000016  x14 0000006f1eac0688  x15 000000065776ec77
    x16 0000007125914a80  x17 00000071258ed450  x18 0000006f1e0fc000  x19 00000000000024fa
    x20 0000000000003975  x21 00000000ffffffff  x22 0000006f4f743000  x23 b400006fa59d9a00
    x24 0000006f4da79be0  x25 000000000000000a  x26 0000006f4ed2d9c8  x27 0000000000000010
    x28 00000040001949c0  x29 0000006f1eac0ab0
    lr  000000712589a748  sp  0000006f1eac0a10  pc  000000712589a774  pst 0000000000001000

backtrace:
      #00 pc 000000000008d774  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168) (BuildId: 449f781894033dce6346794a1ee593e0)
      #01 pc 00000000012acc1c  /data/app/~~sFUES2dzrQ-HpCm8lqu79w==/com.test-S0i9Chd0bjesDkXIEF30Hg==/base.apk (go_seq_from_refnum+236)

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
