### ISSUE TITLE
net/http, x/net/http2: page fails to load with http2 server push due to underflow

### ISSUE THREAD

**Issue by MagicalTux** [golang/go#63511]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/magicaltux/.cache/go-build'
GOENV='/home/magicaltux/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/magicaltux/go/pkg/mod'
GONOPROXY='git.atonline.com'
GONOSUMDB='git.atonline.com'
GOOS='linux'
GOPATH='/home/magicaltux/go'
GOPRIVATE='git.atonline.com'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/pkg/main/dev-lang.go.dev.1.21.3.linux.amd64'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/pkg/main/dev-lang.go.dev.1.21.3.linux.amd64/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.3'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/magicaltux/projects/platform-fe/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1840746337=/tmp/go-build -gno-record-gcc-switches'
</pre></details>

### What did you do?

Running a http server using `http.Pusher` to push a specific resource to the brower.

We updated in emergency to `go1.21.3` following the http2 fast reset issue, this caused all the sites we use to fail to load on firefox and safari until we commented the use of `http.Pusher`.

I think this looks suspiciously a lot similar to https://github.com/golang/go/issues/17777

### What did you expect to see?

Page should work fine.

### What did you see instead?

Only the initial page loads, and somehow firefox refuses to load the rest, either remaining blank or erroring with `NS_BINDING_ABORTED`. Firefox didn't provide any useful information to debug this issue, but not using `http.Pusher` fixed it.

**Comment by MagicalTux** [comment]
I've looked at the code and in case the stream has been reset before `runHandler` was called the whole thing is simply ignored. I'm guessing this is the same issue as in https://github.com/golang/go/issues/17777 where firefox/safari don't like HTTP servers that do not respond to the RST, causing a similar result I guess.

**Comment by seankhliao** [comment]
cc @neild

**Comment by mauri870** [comment]
Looks like there is an underflow in `sc.curHandlers`. It should always be incremented before calling `runHandler` otherwise when we decrement it in `handlerDone` we end up with an underflow. Seems like we missed one of these cases where we should increment it.

**Comment by mauri870** [comment]
@gopherbot, please backport to Go 1.21.4

**Comment by mauri870** [comment]
@gopherbot, please backport to Go 1.20.11

**Comment by mauri870** [comment]
@MagicalTux Could you please update the issue title to include x/net/http2 alongside net/http? Thanks

**Comment by mauri870** [comment]
@gopherbot add NeedsFix, release-blocker

**Comment by mauri870** [comment]
@seankhliao could you please update the issue title to smth akin to `net/http, x/net/http2: page fails to load with http2 server push due to underflow`. Thanks

**Comment by neild** [comment]
@gopherbot please open backport issues. This is a regression with no workaround.
