### ISSUE TITLE
Go toolchain should not force upgrade

### ISSUE THREAD

**Issue by joestringer** [golang/go#63522]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go: cannot find "go1.21.3" in PATH
$ snap info go | grep installed
installed:             1.21.1                  (10339)  62MB classic
</pre>

### Does this issue reproduce with the latest release?

Not exactly. The issue presents as soon as any individual project switches the default go.mod go version to a new patch release. For instance when facing the problem I have this in one of my Go repositories:

```
$ grep '^go' go.mod
go 1.21.3
```

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
go: cannot find "go1.21.3" in PATH
</pre></details>

### What did you do?

I don't want my toolchain to randomly swap and break underneath me. I would rather decide exactly I have time to maintain my local system and defer updates until a suitable time. Therefore I disabled autoupdates:
```
export GOTOOLCHAIN='path'
```

Now, whenever any individual project I work on changes its declared go version inside go.mod, I cannot even run `go version` because Go refuses to run. This breaks builds even if there's only a patch version change.

### What did you expect to see?

I can use Go tooling even if there is a patch version difference vs. a particular repository I am working on.

### What did you see instead?

Go refuses to run because the toolchain has a patch version mismatch vs the repository.

**Comment by hyangah** [comment]
If the project can be built with go 1.21 or newer, why did the project specify the minimum version to `go 1.21.3` instead of `go 1.21` or `go 1.21.0`?

**Comment by seankhliao** [comment]
This is working as intended, the go version is treated like any other dependency where the highest required version is the one to use.

**Comment by hyangah** [comment]
@SuperSandro2000 

> I don't want go to decide what go version to use. If I have a go version locally installed, then that one should be used and if it can't go should complain about it and let me find a solution and not trying to be a smart and unexpectedly trying to swap itself under my foot.

Use `GOTOOLCHAIN=local` in that case. You can also use `go env -w` or mess with $GOROOT/go.env.

More details are in https://go.dev/doc/toolchain and https://go.dev/blog/toolchain.

> Sometimes go 1.21 is swapped for my current go version when running go mod tidy. 

Please open an issue if you find a repro case (i.e. dependencies' go version requirements are unchanged but go mod tidy updates the go line, which shouldn't happen)

**Comment by joestringer** [comment]
For what it's worth, here's my experience of the way this worked:
- In Go 1.20 or earlier, `go.mod` accepted versions in the form `1.20` which declared that in order to build the project, you as a builder must install a Go 1.20.x release.
- Go 1.21 rejected the format that was previously allowed and forced projects to express the version in the `go.mod` in the form `1.21.0`. This broke my workflow, which is unfortunate, but I can deal with that.
- Now that there's a patch release version in the `go.mod`, either maintainers or automated tools start to notice this and innocently update the version to match the latest patch release. 
  - There's some good reasoning here: If you are releasing binaries, they should build against the latest libraries to ensure that security fixes etc. are picked up.
  - The side effect is that it forces the local dev environment to match.
- When these tools bump the version in `go.mod` to `1.26.6`, by default Go will automatically install the latest Go release unless you override the behaviour.
- Like others in the thread, I don't want to deal with this admin or have Go overriding my local environment when I'm in the middle of trying to contribute to a project. It's not just Go updating, but all the other local tooling I have that builds on Go, so even if I relied on Go to update, I still need to manually do additional recompilations & administration of my local system. IDE tools like `gopls` are an example. Failing to update these can cause complaints and breakages due to version mismatches.
- To mitigate the above, I export `GOTOOLCHAIN='path'`. However, if the `go.mod` is bumped to a newer version then the tooling will still complain, even though it should be clear from the environment that I don't intend on updating at this time.
- I _can_ work around this by overriding the version in `go.mod`, but if I have to do this each time I create a branch, but this is just one more little hoop I have to jump through during my regular workflow because the tooling doesn't recognize the way I'd like to work.
- My solution for now is to advocate for the `go.mod` version to always be set to `X.Y.0` to avoid imposing additional upgrades on developers.
  - This seems equivalent to the original behaviour in Go 1.20 or earlier with the form `X.Y` in the `go.mod`: If the project relies on newer language features, they bump the minimum, and then obviously I as a developer need to bump my toolchain to match.
- Additionally, for release binaries I advocate that the Go version is tracked somewhere separately from `go.mod` so that release builds do *not* rely on the `go.mod` Go version to decide which Go toolchain to build with. Those should instead pull the latest toolchain patch release.

It's a small usability issue, but every small hassle you deal with during development adds cognitive load to being able to achieve what you want to do. I'd like the toolchain to do what I want and get out of my way, not to get in my way when I'm trying to do something else.

**Comment by szmcdull** [comment]
It's like a virus, polluting everywhere.

**Comment by dolmen** [comment]
> Additionally, for release binaries I advocate that the Go version is tracked somewhere separately from go.mod so that release builds do not rely on the go.mod Go version to decide which Go toolchain to build with. Those should instead pull the latest toolchain patch release.

For reproducibility the default is to respect the _minimum_ toolchain specified in go.mod. However you can override this with the `GOTOOLCHAIN` environment variable (and this is recorded in the binary). 

Personally I think that tools like dependabot that blindly upgrade the `go` and `toolchain` directives are a pain and have (hopefully had?) a bad behavior.
