### ISSUE TITLE
affected/package: 

### ISSUE THREAD

**Issue by liren-sun** [golang/go#63526]
### What version of Go are you using (`go version`)?

<pre>
$ go version
</pre>
go1.18

### Does this issue reproduce with the latest release?
I am not sure.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>
MacOS arm64

### What did you do?

Using the websockets code from this tutorial, after building and running, when I try to access 127.0.0.1:8080, the terminal shows an error.    [websockets.go](https://gowebexamples.com/websockets/)

### What did you expect to see?

Expecting no errors after accessing 127.0.0.1:8080

### What did you see instead?

```bash
request origin not allowed by Upgrader.CheckOrigin
```

### Code that needs to be modified.
```go
var upgrader = websocket.Upgrader{
	ReadBufferSize:  1024,
	WriteBufferSize: 1024,
	CheckOrigin: func(r *http.Request) bool {
		return true
	},
}
```

**Comment by seankhliao** [comment]
The Go project does not run that website.
