### ISSUE TITLE
spec: confusing final code block in operator section

### ISSUE THREAD

**Issue by randall77** [golang/go#63525]
The last code block in the [operators section](https://go.dev/ref/spec#Operators) confuses me.
There are some examples in that code block, but no explanation as to what they are for. I was expecting some description of the order of evaluation for the various examples, but there is none.
The code block in question:
```
+x
23 + 3*x[i]
x <= f()
^a >> b
f() || g()
x == y+1 && <-chanInt > 0
```
@griesemer

**Comment by griesemer** [comment]
I think these are just examples for binary operators.
But we could explain the evaluation order in comments.
Will do.
