### ISSUE TITLE
x/pkgsite: package removal request for [https://pkg.go.dev/github.com/huweihuang/golib/logger]

### ISSUE THREAD

**Issue by huweihuang** [golang/go#63546]
### What is the path of the package that you would like to have removed?

help to remove the three pkg on pkg.go.dev site, because they are discard.

- https://pkg.go.dev/github.com/huweihuang/golib/logger
- https://pkg.go.dev/github.com/huweihuang/golib/db
- https://pkg.go.dev/github.com/huweihuang/golib/gin

### Are you the owner of this package?

yes ,I am the owner of the packages.

### What is the reason that you could not retract this package instead?

because they are discard.

**Comment by huweihuang** [comment]
@bcmills @findleyr help to review the package removal request, thanks!

**Comment by findleyr** [comment]
This is done, though it might take an hour or so to propagate.

**Comment by huweihuang** [comment]
thanks so much
