### ISSUE TITLE
affected/package: go_asm.h:1: expected identifier, found "%"

### ISSUE THREAD

**Issue by ChenYuStart** [golang/go#63564]
go install github.com/rogpeppe/godef@latest
# internal/bytealg
go_asm.h:1: expected identifier, found "%"
asm: assembly of C:\Program Files\Go\src\internal\bytealg\compare_amd64.s failed

**Comment by ChenYuStart** [comment]
What happened?Why does installing a plug-in involve this?

**Comment by seankhliao** [comment]
what are the contents of that file?

**Comment by ChenYuStart** [comment]
There seems to be some mathematical processing functions using assembly language stored in C:\Program Files\Go\src\internal\bytealg,in the installation directory of go language.
I cloned a go project in another disk space and tried to install a plugin. I cloned the tool.git on github locally, and this problem was prompted when using go install command. I haven't even written any code and the presence of this go_asm.h confuses me.Here I need some help.
![image](https://github.com/golang/go/assets/39488509/4c2b1047-bd40-4c1d-b422-f38afc18afed)

**Comment by seankhliao** [comment]
Sounds like you have a corrupted installation of Go.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by yudhiopik** [comment]
still cant resolve, reinstall is the same .... our compute used encryto tool, system level, dont know where this go.asm.h locate

**Comment by Leycee** [comment]
Brother  how did you solve this problem?
