### ISSUE TITLE
cmd/compile: unsafe.Pointer not treated as a pointer for embedding

### ISSUE THREAD

**Issue by griesemer** [golang/go#6357]
<pre><a href="http://play.golang.org/p/YhdG1ZoVzp">http://play.golang.org/p/YhdG1ZoVzp</a>

Per the spec: &quot;An embedded type must be specified as a type name T or as a pointer
to a non-interface type name *T, and T itself may not be a pointer type.&quot;  (
<a href="http://tip.golang.org/ref/spec#Struct_types">http://tip.golang.org/ref/spec#Struct_types</a> )

gc issues an error for line 9 (as expected), but not for line 10. Arguably, an
unsafe.Pointer is a pointer and thus line 10 should not be legal.

The spec is not very clear about whether an unsafe.Pointer should act like a pointer in
these situations, but:

1. The documentation (by pseudo code) defines unsafe.Pointer as *ArbitraryType (
<a href="http://tip.golang.org/ref/spec#Package_unsafe">http://tip.golang.org/ref/spec#Package_unsafe</a> )

2. For the purposes of method receivers, they are treated as pointers (see <a href="https://golang.org/issue/6116">issue #6116</a>)

3. It's ok to assign nil to it (see line 15 of the above code).

4. It's called a &quot;Pointer&quot;.</pre>

**Comment by odeke-em** [comment]
Good news @griesemer, this issue has been fixed since at least Go1.7 (I couldn't get Go1.6 and earlier to build on my Macbook Pro) and it rightly matches gccgo's behavior producing
### Go1.7
```shell
$ go version && go run main.go 
go version go1.7.6 darwin/amd64
# command-line-arguments
./main.go:9: embedded type cannot be a pointer
./main.go:10: embedded type cannot be a pointer
```

### Go1.8
```shell
 go version && go run main.go 
go version go1.8.7 darwin/amd64
# command-line-arguments
./main.go:9: embedded type cannot be a pointer
./main.go:10: embedded type cannot be a pointer
```

### Go1.9
```shell
$ go version && go run main.go 
go version go1.9.7 darwin/amd64
# command-line-arguments
./main.go:9:2: embedded type cannot be a pointer
./main.go:10:2: embedded type cannot be a pointer
```

### Go1.10
```shell
$ go version && go run main.go 
go version go1.10.8 darwin/amd64
# command-line-arguments
./main.go:9:2: embedded type cannot be a pointer
./main.go:10:2: embedded type cannot be a pointer
```

### Go1.11
```shell
$ go version && go run main.go 
go version go1.11.13 darwin/amd64
# command-line-arguments
./main.go:9:2: embedded type cannot be a pointer
./main.go:10:2: embedded type cannot be a pointer
```

### Go1.12
```shell
$ go version && go run main.go 
go version go1.12.16 darwin/amd64
# command-line-arguments
./main.go:9:2: embedded type cannot be a pointer
./main.go:10:2: embedded type cannot be a pointer
```

### Go1.13
```shell
$ go version && go run main.go 
go version go1.13.11 darwin/amd64
# command-line-arguments
./main.go:9:2: embedded type cannot be a pointer
./main.go:10:2: embedded type cannot be a pointer
```

### Go1.14
```shell
$ go version && go run main.go 
go version go1.14.3 darwin/amd64
# command-line-arguments
./main.go:9:2: embedded type cannot be a pointer
./main.go:10:2: embedded type cannot be a pointer
```

I shall let you close this issue as you please. Thank you.

**Comment by griesemer** [comment]
Appears fixed per the above comment. Verified in latest playground. Closing.
