### ISSUE TITLE
pprof: Focus expression matched no samples

### ISSUE THREAD

**Issue by nagayev** [golang/go#63572]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/marat/.cache/go-build"
GOENV="/home/marat/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/marat/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/marat/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/lib/golang"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/marat/Desktop/Alina/linal/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4214657806=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I want to use `pprof` for `gonum` benchmarking.
Note I don't use `gccgo` but I have GOGCCFLAGS. I have to delete it because I coudn't use pprof
My test file:
```go

package main

import (
	"fmt"
	"time"
	"gonum.org/v1/gonum/mat"
)

func getDet(m mat.Matrix)float64{
	time.Sleep(1*time.Second)
	return mat.Det(m)
}

func main() {
	// This example copies the second column of a matrix into col, allocating a new slice of float64.
	/*m := mat.NewDense(3, 3, []float64{
		2.0, 9.0, 3.0,
		4.5, 6.7, 8.0,
		1.2, 3.0, 6.0,
	})*/

	m := mat.NewDense(2, 2, []float64{
		3.0, 10.0,
		1.0, 3.0,
	})

	d:=getDet(m)
	fmt.Printf("det(m) = %#v\n", d)
}

```
My steps:
1. `go test -bench=getDet -cpuprofile cpu.prof`
PASS
ok      linal   0.204s
Note 0.2s but `time.Sleep` for second
2. `go tool pprof -tree -edgefraction 0 -nodefraction 0 -nodecount 100000 -focus linal.test cpu.prof`
go tool pprof -tree -edgefraction 0 -nodefraction 0 -nodecount 100000 -focus linal.test cpu.prof
Focus expression matched no samples
File: linal.test
Type: cpu
Time: Oct 16, 2023 at 6:43pm (MSK)
Duration: 200.69ms, Total samples = 0 
Active filters:
   focus=linal.test
Showing nodes accounting for 0, 0% of 0 total
----------------------------------------------------------+-------------
      flat  flat%   sum%        cum   cum%   calls calls% + context              
3. I also try to run it using `go tool pprof -svg ./linal.test ./cpu.out > linal.svg`
But in linal.svg there aren't functions' calls

### What did you expect to see?

Functions call stack.

### What did you see instead?

Nothing interesting
go tool pprof -tree -edgefraction 0 -nodefraction 0 -nodecount 100000 -focus linal.test cpu.prof
Focus expression matched no samples
File: linal.test
Type: cpu
Time: Oct 16, 2023 at 6:43pm (MSK)
Duration: 200.69ms, Total samples = 0 
Active filters:
   focus=linal.test
Showing nodes accounting for 0, 0% of 0 total
----------------------------------------------------------+-------------
      flat  flat%   sum%        cum   cum%   calls calls% + context

**Comment by nagayev** [comment]
@seankhliao please check out updated version with  details in what did you see

**Comment by seankhliao** [comment]
your code is still a program, not a test

**Comment by nagayev** [comment]
Problem on my side, no go bug
