### ISSUE TITLE
affected/package: 

### ISSUE THREAD

**Issue by smwltr** [golang/go#63589]
### What version of Go are you using (`go version`)?
This is N/A, but here it is:
<pre>
$ go version
go version go1.19.13 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
This is N/A, but here it is:
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/-/.cache/go-build"
GOENV="/home/-/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/-/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/-/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/lib/golang"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.13"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1477792466=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
Used httptest
https://cs.opensource.google/go/go/+/refs/tags/go1.21.3:src/net/http/httptest/httptest.go;drc=1b09d430678d4a6f73b2443463d11f75851aba8a;l=5

### What did you expect to see?
"Package httptest provides utilities for testing the http package."

### What did you see instead?
"Package httptest provides utilities for HTTP testing."

This is a report about wording. So maybe it is appropriate for the package author. I see bradfitz@golang.org around those lines.

It has been explained to me the reasons behind some choices such as setting the HTTP status code of ResponseRecorder to 200 and changing 0 to 200.
https://cs.opensource.google/go/go/+/refs/tags/go1.21.3:src/net/http/httptest/recorder.go;drc=ff14e844d26090e09aa335d836f737c09a7a0402;l=55
https://cs.opensource.google/go/go/+/refs/tags/go1.21.3:src/net/http/httptest/recorder.go;drc=ff14e844d26090e09aa335d836f737c09a7a0402;l=196

The explanation was that it is coupled to the http package. If this is true, the description is misleading.

Background: for areas of safety, it is recommended to test with foreign langs/tools/libs - avoiding a homogeneous environment.

The change is only a suggestion to help the random QA person avoid httptest.

**Comment by karelbilek** [comment]
I don't understand this issue.

I use httptest in my test code all the time. (I am not testing http package.) I am testing my own code, `httptest.NewServer` lets me quickly create a new test server.

I don't understand how are the links about status code related to your documentation issue.

**Comment by candlerb** [comment]
If you write server code to run under `net/http`, then you will likely have written a [HandlerFunc](https://pkg.go.dev/net/http#HandlerFunc) such as

```
func MyHandler(w http.ResponseWriter, r *http.Request)
```

or you've implemented the similar [Handler](https://pkg.go.dev/net/http#Handler) interface.

`net/http/httptest` provides helpers for unit testing such functions.

A ResponseRecorder is a mock implementation of the [http.ResponseWriter](https://pkg.go.dev/net/http#ResponseWriter) interface. As such, its semantics match the documented semantics of the ResponseWriter interface, including an assumed 200 status code if WriteHeader is not called before the first call to Write. This is so that you can test what your handler would have sent, were it called within a real HTTP exchange.

As such, the design of ResponseRecorder in `net/http/httptest` makes perfect sense IMO. It's not meant for testing arbitrary HTTP implementations - since it doesn't actually make or receive any real HTTP requests - but to log the calls made by a handler function under test.

**Comment by Merovius** [comment]
Correction: `http.ResponseRecorder` is a fake, not a mock. In a way, that's the entire contention. The point of a mock would be to verify that the system under test calls the right methods - so a mock would be useful to verify that a `http.Handler` actually calls `WriteHeader`. A fake, on the other hand, is an implementation for a test that tries to mimic the production behavior as closely as possible.

`ResponseRecorder` is a fake of `ResponseWriter`. As such, it does not simply record the calls that where made, it simulates the behavior of the `net/http` server. Note, for example, that it also doesn't record each individual call to `Write`, but instead just appends all of them to a buffer.

A lot of ink has been spilled on fakes vs. mocks and ultimately which one you prefer comes down to opinion (assertions to the contrary by @smwltr notwithstanding). But it's certainly reasonable for the stdandard library to provide a fake.

**Comment by Merovius** [comment]
As for this issue, FWIW: As I said on the golang-nuts thread, the facts that this package is in the standard library - even nested under `net/http` - and that it references types from `net/http` in its documentation and signatures is, to me, already a sufficiently clear indication of what it does and what it's for. Trying to construct a difference between "an HTTP testing package" and "a testing package for `net/http`" is, at best, academic nit-picking in this context.

I would just close this issue, personally.

**Comment by candlerb** [comment]
It's already closed, so that's fine :-)

**Comment by Merovius** [comment]
Oh, didn't notice.

**Comment by smwltr** [comment]
> Trying to construct a difference between "an HTTP testing package" and "a testing package for net/http" is, at best, academic nit-picking in this context.

...construct a difference? That is the realm of politicians.

They look similar, but if you place each letter side by side, the difference between 'HTTP' and 'http' should be noticeable. No construction should be necessary. In this context upper case and lower case also has a different meaning.

Lame humor aside, it sounds like you are saying that I am nitpicking, and, considering the context of software testing, I'll take that as a compliment.
