### ISSUE TITLE
proposal: Go 2:  Allow non-generic interface   contains generic method

### ISSUE THREAD

**Issue by someview** [golang/go#63582]
### Proposal
- **What is the proposed change?**
Now non-generic interface can not define generic method in go 1.21.
- **Who does this proposal help, and why?**
This feature is needed in some cases  like factory desigin pattern: create a list of generic objects of a specific define type.
### Costs
- **Do you have a prototype? (This is not required.)**
-just  like c#， a interface does not need contains Type parameter.
```
 public class GrpcServiceProxyFactory : IServiceProxyFactory
 {
     /// <summary>
     ///    
     /// </summary>
     public ICollection<Type> ServiceTypes { get; private set; } = Array.Empty<Type>();

     private static readonly object Lock = new();
}
```

**Comment by ianlancetaylor** [comment]
Dup of #49085.
