### ISSUE TITLE
fmt: inconsistent output with escape strings in playground, shell

### ISSUE THREAD

**Issue by Nasfame** [golang/go#63585]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.0 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE='on'
GOARCH='arm64'
GOBIN='/Users/hiro/go/bin'
GOCACHE='/Users/hiro/go/cache'
GOENV='/Users/hiro/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/hiro/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/hiro/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.21.0'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/44/nbbyll_10jd0z8rj_qxm43740000gn/T/go-build2816362605=/tmp/go-build -gno-record-gcc-switches -fno-common'

</pre></details>

### What did you do?

```
package main

import (
	"fmt"
)

func main() {
	name := "\bhiro"
	fmt.Printf("%v\n", name)
}

```

```
 go run scratch_55.go                                                                                                                            
```

### What did you expect to see?

\bhiro

### What did you see instead?
<img width="508" alt="image" src="https://github.com/golang/go/assets/24226219/b4ed6472-22bf-4ec6-81d2-893fd45080b8">

<img width="438" alt="image" src="https://github.com/golang/go/assets/24226219/956aee1a-94e1-4858-b655-d127459f55e2">

<img width="534" alt="image" src="https://github.com/golang/go/assets/24226219/ae57a5f4-c0f6-4c52-8111-9f69cf49d8bd">

https://go.dev/play/p/XBh3lJgYzWc
[<img width="145" alt="image" src="https://github.com/golang/go/assets/24226219/b2898fb1-35d6-4021-9e70-4c960cfa913a">](https://go.dev/play/p/XBh3lJgYzWc)

```
 go run scratch_55.go
hiro
```

**Comment by bcmills** [comment]
`\b` is the ASCII Backspace character (see https://go.dev/ref/spec#String_literals). It doesn't surprise me that different environments might render that character differently.

This doesn't look like a Go bug to me: the behavior of the Go program itself is consistent, it is the surrounding environment that differs.

**Comment by Nasfame** [comment]
> This doesn't look like a Go bug to me: the behavior of the Go program itself is consistent, it is the surrounding environment that differs.

Within the same surrounding environment, the output is quite different.

https://github.com/golang/go/assets/24226219/c972a08a-65eb-4728-9a13-f64efd76f76e


If I am not wrong: \b behaviour:
`Hello,\b,World`-> Hellworld
 `\bhiro`-> \bhiro (behaves like normal string)

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
