### ISSUE TITLE
affected/package: VS Code Go extension

### ISSUE THREAD

**Issue by buchs** [golang/go#63620]
I don't know what is going on with this extension. I don't even know what this means. I opened a repo-folder that includes subdirectories with go source included. Your notification asks me to file and issue if I believe this warning is incorrect. 

> Error loading workspace: You are outside of a module and outside of $GOPATH/src. If you are using modules, please open your editor to a directory in your module. If you believe this warning is incorrect, please file an issue: https://github.com/golang/go/issues/new.

**Comment by buchs** [comment]
It just sits and spins.

**Comment by Jorropo** [comment]
@buchs did you initialised a module with `go mod init` ?

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
