### ISSUE TITLE
affected/package: os/exec

### ISSUE THREAD

**Issue by anuphalarnkar** [golang/go#63625]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.21.3 linux/arm64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/home/user/.cache/go-build'
GOENV='/home/user/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/user/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/user/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_arm64'
GOVCS=''
GOVERSION='go1.21.3'
GCCGO='gccgo'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2963907658=/tmp/go-build -gno-record-gcc-switches'
</pre></details>

### What did you do?
I want to execute a shell command "timeout 1 perf stat -I 500" which is giving an error "exit status 124"
But, I got correct results with the command "timeout 1 perf list". As soon as I add more parameters, I get the error of exit status

Here is my code:

package main
import (
        "fmt"
        "os/exec"
)
func main() {
        cmd := exec.Command("timeout", "1", "perf", "stat", "-I", "500")
        stdout,err := cmd.Output()
        if err != nil {
            fmt.Println(err.Error())
        }
        fmt.Println(string(stdout))
}

### What did you expect to see?
When I run this command directly on shell:
timeout 1 perf stat -I 500
#           time             counts           unit      events
     0.500533417          48,801.67    msec  cpu-clock                     #   97.603 CPUs utilized
     0.500533417              4,192                 context-switches          #   85.899 /sec
     0.500533417                 98                   cpu-migrations            #    2.008 /sec
     0.500533417                  2                    page-faults                  #    0.041 /sec
     0.500533417        3,63,75,695              cycles                           #    0.001 GHz
     0.500533417        3,98,75,909              instructions                  #    1.10  insn per cycle
     0.500533417    <not supported>        branches
     0.500533417           1,25,349                branch-misses             #    0.00% of all branches

### What did you see instead?
exit status 124

### This works correctly
package main
import (
        "fmt"
        "os/exec"
)
func main() {
        //The parameters have been changed. Instead of "perf stat", I am using "perf list" below
        cmd := exec.Command("timeout", "1", "perf", "list")
        stdout,err := cmd.Output()
        if err != nil {
            fmt.Println(err.Error())
        }
        fmt.Println(string(stdout))
}

### Output
  branch-misses                                      [Hardware event]
  bus-cycles                                         [Hardware event]
  cache-misses                                       [Hardware event]
  cache-references                                   [Hardware event]
  cpu-cycles OR cycles                               [Hardware event]
  instructions                                       [Hardware event]
  stalled-cycles-backend OR idle-cycles-backend      [Hardware event]
  stalled-cycles-frontend OR idle-cycles-frontend    [Hardware event]
  alignment-faults                                   [Software event]
.....
.....
.....

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
