### ISSUE TITLE
dl: failed to install Go 1.15 on darwin/arm64

### ISSUE THREAD

**Issue by alexandear** [golang/go#63626]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.3 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/Oleksandr_Redko/Library/Caches/go-build'
GOENV='/Users/Oleksandr_Redko/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/Oleksandr_Redko/go/pkg/mod'
GONOPROXY='dev.azure.com/slb-swt,dev.azure.com/slb-digital,slb-swt.visualstudio.com,slb-digital.visualstudio.com'
GONOSUMDB='dev.azure.com/slb-swt,dev.azure.com/slb-digital,slb-swt.visualstudio.com,slb-digital.visualstudio.com'
GOOS='darwin'
GOPATH='/Users/Oleksandr_Redko/go'
GOPRIVATE='dev.azure.com/slb-swt,dev.azure.com/slb-digital,slb-swt.visualstudio.com,slb-digital.visualstudio.com'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.21.3'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/Oleksandr_Redko/src/github.com/golang/dl/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/pk/5dzf3qsj6l18s2b3zfw194840000gn/T/go-build447310872=/tmp/go-build -gno-record-gcc-switches -fno-common'
</pre></details>

### What did you do?

Run commands to install `go1.15`:

```
$ go install golang.org/dl/go1.15@latest
```
and
```
$ go1.15 download
```

### What did you expect to see?

```
$ go1.15 download
...
Success. You may now run 'go1.15'
```

### What did you see instead?

The error appeared:
```
$ go1.15 download
go1.15: download failed: no binary release of go1.15 for darwin/arm64 at https://dl.google.com/go/go1.15.darwin-arm64.tar.gz
```

### Other notes

The problem exists for Go version 1.15 and below.

A possible solution is to install `go` for `darwin/amd64` when OS is `darwin/arm64` for Go 1.15-.

**Comment by ianlancetaylor** [comment]
We didn't promote darwin/arm64 to be a primary port until Go 1.16.  Since Go 1.15 and Go 1.16 are no longer supported, we don't plan to backfill older binary releases.
