### ISSUE TITLE
testing/require: (*Assertion) PanicsWithErrorIs & PanicsWithErrorContains

### ISSUE THREAD

**Issue by mail2nnv** [golang/go#63627]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.3 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What did you do?

https://go.dev/play/p/-ePsCuCxyW1

```go
import (
	"errors"
	"fmt"
	"testing"

	"github.com/stretchr/testify/require"
)

var ErrGoCrazy = errors.New("go crazy")
var GoCrazy = func() { panic(fmt.Errorf("🔫: %w", ErrGoCrazy)) }

func Test_SomePanicWithError(t *testing.T) {
	require := require.New(t)

	t.Run("must be ok to test panics wrapped errors", func(t *testing.T) {
		require.PanicsWithErrorIs( // <— error here ⛔
			func() { GoCrazy() },
			ErrGoCrazy,
		)
	})

	t.Run("must be ok to test panics error contains string", func(t *testing.T) {
		require.PanicsWithErrorContains( // <— error here ⛔
			func() { GoCrazy() },
			"crazy",
		)
	})
}
```

### What did you expect to see?

I see compile errors:
```
- require.PanicsWithErrorIs undefined
- require.PanicsWithErrorContains undefined
```

### What did you see instead?

I expected:
- This `require.Assertions` methods (`PanicsWithErrorIs()` & `PanicsWithErrorContains()`) will be implemented in feature Go versions 😊

**Comment by seankhliao** [comment]
testify is not part of the Go project, please file an issue with them
