### ISSUE TITLE
Building bootstrap takes forever

### ISSUE THREAD

**Issue by Ponewor** [golang/go#63628]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.12.3 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE='on'
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/mamazur/.cache/go-build'
GOENV='/home/mamazur/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/mamazur/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/mamazur/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/snap/go/10389'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/snap/go/10389/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.3'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2469723538=/tmp/go-build -gno-record-gcc-switches'

</pre></details>

### What did you do?

I've replicated [this](https://go-review.googlesource.com/c/go/+/507415) change and run `all.bash`.

### What did you expect to see?
Result of build process in reasonable time - either success or some kind of a failure. For comparison: the version from master builds in just a couple of minutes.

### What did you see instead?

The build is stuck for over 20 hours on building bootstrap:
<details><summary><code>go env</code> Output</summary><br><pre>
mamazur@pc:~/go-source/src$ ./all.bash
Building Go cmd/dist using /snap/go/10389. (go1.21.3 linux/amd64)
Building Go toolchain1 using /snap/go/10389.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
</pre></details>

**Comment by seankhliao** [comment]
this looks specific to that unmerged CL, please comment there with any issues it may have.
