### ISSUE TITLE
net: tests fail if /etc/hosts lists localhost 127.0.0.1 twice

### ISSUE THREAD

**Issue by gopherbot** [golang/go#6363]
by **jaq@spacepants.org**:

<pre>I just downloaded the source code release branch from code.google.com per the
instructions, then ran all.bash:

hg clone ...
hg update release
cd go/src
./all.bash
...
--- FAIL: TestLookupHost (0.00 seconds)
	hosts_test.go:65: LookupHost(&quot;localhost&quot;) = [127.0.0.1 127.0.0.1], has duplicate addresses
FAIL
FAIL	net	2.379s
...

My /etc/hosts is managed by a config management tool and just happens to have put two
localhost entries in there (I didn't know this until now ;-)

cat /etc/hosts
...
127.0.0.1	gunstar	localhost
...
127.0.0.1	localhost	

The test seems a bit fragile because it relies on config outside the control of the Go
source code.</pre>

**Comment by mikioh** [comment]
Closing. TestLookupHost was removed by 047f07a285edbc60f64018973be7ce6b341fe22d.
