### ISSUE TITLE
Comments with code give error

### ISSUE THREAD

**Issue by pandasoli** [golang/go#63634]
### What version of Go are you using (`go version`)?
```
$ go version

go version go1.21.3 linux/amd64
```

### Does this issue reproduce with the latest release?
Yes, on `go1.22-eabf3bf688`!

### What operating system and processor architecture are you using (`go env`)?

<details>
  <summary><code>go env</code> Output</summary>
  <br>
  
```
$ go env

GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/panda/.cache/go-build'
GOENV='/home/panda/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/panda/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/panda/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/lib/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='local'
GOTOOLDIR='/usr/lib/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.3'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='x86_64-pc-linux-gnu-gcc'
CXX='x86_64-pc-linux-gnu-g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1989142553=/tmp/go-build -gno-record-gcc-switches'
```
</details>

### What did you do?

I commented a piece of my code, like this:
```go
  /*line := self.Lines[self.CursorY] // current line
  line_len := uint(len(line))

  // CursorX cannot be bigger than the line length
  cursor_x := self.CursorX

  if cursor_x > line_len {
    cursor_x = line_len
  }

  // get: ScrollX < x < CursorX
  line = line[self.ScrollX:cursor_x]

  tabs_count := uint(strings.Count(string(line), "\t"))*/
```

I didn't manage to discover what exactly gives me the error.  
But if I give a space between `/*` and `line :=`, it stops.

The same doesn't happen with `/*test*/` so the problem is not exactly about the spacing.

### What did you expect to see?
The program runs as it should without that piece of code.

### What did you see instead?
```
# command-line-arguments
./test.go:4: invalid line number: = uint(strings.Count(string(line), "\t"))
```

**Comment by ianlancetaylor** [comment]
Please show us a complete self-contained example file that we can pass to `go build` to recreate the problem.  Thanks.

**Comment by rittneje** [comment]
@pandasoli This is because your comment is being misinterpreted as a compiler `line` directive. https://pkg.go.dev/cmd/compile#hdr-Compiler_Directives

**Comment by pandasoli** [comment]
@ianlancetaylor Just put the comment inside a main function and it happens.  
@rittneje mmm, bug solved hahah. Another thing to learn about Go <img width='20' src='https://github.com/egonelbre/gophers/blob/master/icon/emoji/gopher-victorious.png?raw=true'/>
