### ISSUE TITLE
affected/package: Build is consuming the whole CPU resources 1.21.3

### ISSUE THREAD

**Issue by leomirandadev** [golang/go#63631]
Build is consuming the whole CPU resources on MACBOOK intel.

### What version of Go are you using (`go version`)?
1.21.3 
<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?
Yes. Only happening on the last version.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

I've updated the go from 1.21.1 to 1.21.3 and ran the ``go build``.

### What did you expect to see?

Fast build

### What did you see instead?

Infinite build

**Comment by seankhliao** [comment]
please fill out the issue template.

**Comment by leomirandadev** [comment]
Yes, I downgrade and everything is working again @andig

**Comment by mauri870** [comment]
From what I understood the build is stuck consuming cpu indefinitely, but is there any errors reported? Do you have a reproducible example to share? Thanks

**Comment by chadgrant** [comment]
having this issue also, only seems to be happening when doing a go build in docker with 1.21.4 and 1.21.5 so far, hangs forever on builds that only thing that changed was go version. When I move back to 1.20.0, it works
