### ISSUE TITLE
access: add new member to GitHub assignees and editors

### ISSUE THREAD

**Issue by mauri870** [golang/go#63635]
Hi,

Per https://github.com/golang/go/wiki/GithubAccess I'd like to request access for the following GitHub groups:

- [go-assignees](https://github.com/orgs/golang/teams/go-assignees) So I can assign myself to issues without having to ask others
- [go-editors](https://github.com/orgs/golang/teams/go-editors) So I can update metadata on issues while [Gardening](https://github.com/golang/go/wiki/Gardening)
- if possible to also join https://github.com/orgs/golang/people

I'm currently working with new apis in the internal/atomic and sync/atomic and also contribute to x/sys/unix, but it is probably not applicable to @golang/runtime (per https://dev.golang.org/owners).

I already have access to trybots and +1 approval

gerrit account: [mauri870@gmail.com](https://go-review.googlesource.com/q/author:mauri870@gmail.com)
github account: [mauri870](https://github.com/mauri870)

Thank you!

**Comment by mauri870** [comment]
@gopherbot add NeedsDecision

**Comment by mauri870** [comment]
cc @golang/release

**Comment by cagedmantis** [comment]
Granted. Thank you for your work on the project.
