### ISSUE TITLE
affected/package: go command Permission error prevents `go mod tidy` from executing

### ISSUE THREAD

**Issue by leath-dub** [golang/go#63632]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

go version go1.21.3 linux/amd64

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

```
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/cathal/.cache/go-build'
GOENV='/home/cathal/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/cathal/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/cathal/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/lib/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/lib/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.3'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/tmp/mod/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build4100770186=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

This is easily reproducible, just create a fresh go module

```
$ mkdir mod && cd mod
$ go mod init
```

Make a directory and change the permissions to be not readable by the current user

```
$ mkdir data
$ chmod 000 data
```

Add a main.go with the following example, you can add any external module

```go
package main

import "github.com/redis/go-redis/v9"

func main() {}
```

Now run `go mod tidy` and see as it fails with permission denied on the directory we created

```
go: mod/data: open /tmp/mod/data: permission denied
go: pattern all: open /tmp/mod/data: permission denied
```

### What did you expect to see?

I was using a mount onto a container so the permissions were not correct. I did not expect this to prevent me fetching dependencies.

### What did you see instead?

Permission errors

**Comment by seankhliao** [comment]
working as intended, go needs to know which dependencies are in the module, which includes all subdirectories
