### ISSUE TITLE
fmt: %q with byte value

### ISSUE THREAD

**Issue by 3052** [golang/go#63646]
If I run this code:

~~~go
package main

import "fmt"

func main() {
   fmt.Printf("%s\n", "\xA1") 
   fmt.Printf("%q\n", "\xA1") 
   fmt.Printf("%c\n", rune(0xA1)) 
   fmt.Printf("%q\n", rune(0xA1)) 
   fmt.Printf("%c\n", byte(0xA1)) 
   fmt.Printf("%q\n", byte(0xA1)) 
}
~~~

I get this result:

~~~
�
"\xa1"
¡
'¡'
¡
'¡'
~~~

everything seems OK except for the last two items. INVERTED EXCLAMATION MARK (U+00A1) is actually 0xC2 0xA1 in UTF-8, not just 0xA1. with `%c`, this is explained in the documentation:

https://github.com/golang/go/blob/693def151adff1af707d82d28f55dba81ceb08e1/src/fmt/doc.go#L26-L33

but `%q` doesn't seem to be clear enough about what its doing. it seems with both `%c` and `%q`, a byte value is first converted to a rune before printing, but only `%c` draws attention to that fact. I think the current behavior is correct, but the `%q` value documentation should be more explicit about the conversion to a rune/Unicode code point.

**Comment by 3052** [comment]
looks like this is related to 5 here:

https://go.dev/ref/spec#Conversions_to_and_from_a_string_type

**Comment by 3052** [comment]
looks like this is related to 5 here:

<https://go.dev/ref/spec#Conversions_to_and_from_a_string_type>

as a workaround, you can use a byte slice instead:

~~~go
package main

import "fmt"

func main() {
   fmt.Printf("%s\n", []byte{0xA1}) // �
   fmt.Printf("%q\n", []byte{0xA1}) // "\xa1"
}
~~~

**Comment by raghvenders** [comment]
Inverted exclamation is within a byte and hope below helps

`package main

import "fmt"

func main() {
	fmt.Printf("%s\n", "\xC2\xA1")
	fmt.Printf("%q\n", "\xC2\xA1")
	fmt.Printf("%+q\n", "\xC2\xA1")
	fmt.Printf("%#U\n", rune(0xA1))

}`

**Comment by 3052** [comment]
no one was asking for help, its a documentation issue
