### ISSUE TITLE
x/pkgsite: package removal request for [github.com/Abu-Zakaria/termui-kit]

### ISSUE THREAD

**Issue by Abu-Zakaria** [golang/go#63643]
### What is the path of the package that you would like to have removed?

My package is at – github.com/Abu-Zakaria/termui-kit

I have already deleted the package from github.

### Are you the owner of this package?

Yes

### What is the reason that you could not retract this package instead?

I have already deleted the package project files from my local computer and GitHub. The reason I deleted the repo is that I wanted to rename the package name, so I created a new repo with a new name for the package and deleted the old package.

**Comment by ansaba** [comment]
Package removed.
