### ISSUE TITLE
x/pkgsite: package removal request for github.com/credo4me/moysklad

### ISSUE THREAD

**Issue by arcsub** [golang/go#63652]
### What is the path of the package that you would like to have removed?

github.com/credo4me/moysklad

### Are you the owner of this package?

Yes

### What is the reason that you could not retract this package instead?

The github repository was created and archived by mistake. Now it is no longer accessible from the original URL.

**Comment by ansaba** [comment]
@arcsub, we cannot verify that you are the author of the package github.com/credo4me/moysklad. Userid @credo4me is the right author to create removal request for this package.
