### ISSUE TITLE
toolchain/compiler: compatibiltiy breakage and version build tag mis-selection

### ISSUE THREAD

**Issue by extemporalgenome** [golang/go#63662]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.21.3
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?
Observed on playground, as well as darwin/amd64.

### What did you do?

Two variations on the same issue (but with two separate impacts)

#### Build tag mis-selection
Go 1.21.3 build:  https://go.dev/play/p/fWOoY4Pl4zy
Go 1.20.10 build: https://go.dev/play/p/fWOoY4Pl4zy?v=goprev

#### Backwards-compatibility breakage
Go 1.20.10 build: https://go.dev/play/p/DD7-mCI3k5r?v=goprev
Go 1.21.3 build: https://go.dev/play/p/DD7-mCI3k5r

### What did you expect to see?

I expected Go 1.21 to maintain Go 1.20 compatibility mode when the `go.mod` file declares 1.20.

More specifically: I expected Go to match go-version build tags based on the stated `go.mod` version directive, _not_ based on the toolchain/compiler version.

#### Build tag mis-selection

I expected to see this output:

```
build version: go1.21.3
using 1.20 clear variant
```

#### Backwards-compatibility breakage
I expected to see the code compile in Go 1.21 just as it had in Go 1.20.

#### Build tag mis-selection
I saw the output:

```
build version: go1.21.3
using 1.21 clear variant
```

#### Backwards-compatibility breakage
Backwards compatibility breakage in the presence of a negated version build tag: 

```
./main.go:10:2: clear requires go1.21 or later (-lang was set to go1.20; check go.mod)
```

When no build tag is used, the compiler recognizes that the `clear` builtin is shadowed, following normal shadowing rules. In the presence of a build tag (`!go1.21`), the compiler complains about use of a builtin from a version that is later than what is declared in `go.mod`.

Since this code would have worked in versions Go 1.18 through Go 1.20, it should have continued working in Go 1.21 without modification.

**Comment by seankhliao** [comment]
Working as intended. The toolchain version is the one that is used. Build tags are explicitly designed to allow skew away from the main version declared in go.mod.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by extemporalgenome** [comment]
Hi @seankhliao! I opened a question in `#golang-nuts` as you suggested (https://groups.google.com/g/golang-nuts/c/Oh_F5wDhAjU), particularly as I was unable to find any documentation (explicit or otherwise) regarding this aspect of the design.

I'm hoping/appreciate you being able to follow-up with a link to docs/doc comments regarding this behavior, or more detail.

Regards,
Kevin
