### ISSUE TITLE
builtin: documentation for recover does not match that of panic

### ISSUE THREAD

**Issue by mitar** [golang/go#63669]
Recently `panic` has been change to better support panicking with `nil` (aa51c40b1cc62d53603d7b7aea3232969aa40afe) and its documentation in `src/builtin/builtin.go` has been updated by adding:

```
// Starting in Go 1.21, calling panic with a nil interface value or an
// untyped nil causes a run-time error (a different panic).
// The GODEBUG setting panicnil=1 disables the run-time error.
```

Sadly, `recover` documentation was not updated and it currently reads:

```
// ... In this case, or when the goroutine is not
// panicking, or if the argument supplied to panic was nil, recover returns
// nil. Thus the return value from recover reports whether the goroutine is
// panicking.
```

See "or if the argument supplied to panic was nil" part. That is not true anymore by my understanding.

cc @rsc

**Comment by go101** [comment]
The spec says:

> calling panic with a nil interface value (or an untyped nil) **causes** a run-time panic.

So, maybe no needs to do for the `panic` API docs?

**Comment by randall77** [comment]
This doc has been changed to update that text. (As of CL 544975.)
