### ISSUE TITLE
access: add dagood to windows group

### ISSUE THREAD

**Issue by dagood** [golang/go#63697]
Hi, I'd like to request being added to these GitHub groups:

* https://github.com/orgs/golang/teams/windows
* https://github.com/orgs/golang/teams/go-assignees

I work with @qmuntal at Microsoft and plan to help with Windows issues, in particular when Quim isn't available.

@golang/windows

See https://go.dev/wiki/GithubAccess

(I noticed the issue creation link in the wiki isn't working--GitHub forces me back to the template selection screen. This URL could be used as a workaround: https://github.com/golang/go/issues/new?template=00-bug.md&title=access:+&body=See+https://go.dev/wiki/GithubAccess. Picked that template because it doesn't add any labels, maybe there's a better way?)

**Comment by dr2chase** [comment]
Does "request to Join" on the windows team page not "work"? (Not clear to me what "work" would mean, exactly.)

**Comment by dagood** [comment]
Both of the team pages show up as 404's for me. They seem to be set up as "secret" teams, and I don't have a way to know they exist from my account. Even the `@golang/windows` looks like plain old text from my perspective, everywhere I see it. (In theory, the teams might not exist, it just seems more reasonable that they do. 😄)

**Comment by dr2chase** [comment]
Ugh.  I will see if I can figure this out tomorrow.

**Comment by dagood** [comment]
I noticed a pending invite to the golang org from @bcmills, and after accepting I can see the windows team (and I'm already a member). The team mention in my post also now shows up as a mention. 👍 

https://github.com/orgs/golang/teams/go-assignees is still a 404, but I don't know if getting in is all that necessary, given the note in https://github.com/golang/go/wiki/GithubAccess#assignees. (I started this based on @qmuntal's request issue, https://github.com/golang/go/issues/56288, and https://go.dev/wiki/GithubAccess.)

**Comment by dagood** [comment]
I checked again and I'm in go-assignees now too. All set, thanks!
