### ISSUE TITLE
access: gomote

### ISSUE THREAD

**Issue by mauri870** [golang/go#63695]
Per https://github.com/golang/go/wiki/Gomote#access, I'd like to request access to the gomote service. 

Main usecase I have at the moment is to build new syso files for the race detector with [racebuild](https://pkg.go.dev/golang.org/x/build/cmd/racebuild), which require gomote. Additionally, being able to debug other architectures that I normally don't have access to sounds very useful as well.

- [gerrit user](https://go-review.googlesource.com/q/author:mauri870@gmail.com)
- [mauri870@gmail.com](mailto:mauri870@gmail.com)

/cc @golang/release

Thanks in advance!

**Comment by heschi** [comment]
Apologies for the rather extreme delay. We don't have a lot of practice with these requests.

Unfortunately I don't think gomote access will give you what you want. For security reasons we're not able to grant access to all machine types to non-Googlers, including some you'd need to build the race detector syso's. @cherrymui has offered to help out if you need them rebuilt. Hopefully that'll be sufficient :(

If the debugging case is important to you we can definitely reconsider. For now I'm closing the request.

**Comment by mauri870** [comment]
@heschi I understand the security constraints regarding gomote access.

Upon reviewing my contributions, it's clear that the majority of them pertain to architectures and operating systems that I do not have direct access to.  I have to rely on qemu static to test most of my work, which in most cases do suffice but it is not the same as a real machine. From memory, I remember encountering test failures on qemu-s390x-static, which have led to additional debugging efforts on my part. This issue was later confirmed to be a qemu limitation, after successfully running slow bots on the CL.

The debugging case at hand is crucial, and gomote access would greatly facilitate my contributions. I appreciate @cherrymui's offer for assistance in rebuilding the necessary syso files, I already reached out to her in the related issue.

If possible, could you reconsider gomote access? I'm willing to adhere to any security measures and guidelines.

If the answer remains no, I would like to express my sincere gratitude for your time and attention to this matter. I will seek alternative ways to test my work.

Thank you for taking the time to consider my request.

Sincerely,

Mauri

**Comment by heschi** [comment]
Fair enough, and sorry for making you jump through hoops. I've granted gomote access. Thanks for all of your contributions!
