### ISSUE TITLE
x/tools/internal/refactor/inline,x/tools/gopls: undo variadic elimination when it is safe to do so

### ISSUE THREAD

**Issue by findleyr** [golang/go#63717]
Follow up on this comment on a semi-automated CL: https://go-review.googlesource.com/c/tools/+/537475/1/gopls/internal/lsp/source/rename.go#973

The inliner should undo variadic elimination (packing variadic arguments as `[]T{...}`) when it is safe to do so. As a result of the current logic, the inliner may introduce this redundancy at the callsite.

CC @adonovan

**Comment by adonovan** [comment]
FWIW, "Safe to do so" means there is exactly one use in the callee body and it is the final argument of an ellipsis call f(param...).

**Comment by adonovan** [comment]
> I don't think that's right. `[]T{a,b,c}...` is safe to replace with `a, b, c` wherever it occurs.

Good point. Though I suspect that if there were multiple uses of the parameter, it would not have been substituted, so you would not see `f([]T{a, b, c}...)`, only `f(args...)` after a binding decl `var args = []T{a, b, c}`.
