### ISSUE TITLE
"go test -fuzz FuzzReverse -timeout 10s" can not limit time

### ISSUE THREAD

**Issue by yangyile1990** [golang/go#63721]
my cpu is burning but the fuzz is not done.
so how to limit the fuzz timeout?

**Comment by zhenfeng1028** [comment]
You should use -fuzztime option rather than -timeout. The proper form of this command is "go test -run=FuzzReverse -fuzz=Fuzz -fuzztime 10s". Refer to this [https://go.dev/doc/tutorial/fuzz](tutorial)

**Comment by bcmills** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

See https://go.dev/wiki/Questions.
