### ISSUE TITLE
access: may-start-trybots

### ISSUE THREAD

**Issue by callthingsoff** [golang/go#63724]
See https://go.dev/wiki/GerritAccess

I want to request the may-start-trybots permission in order to trigger the build of my CLs.

Thanks in advance!

Gerrit user: https://go-review.googlesource.com/q/author:xigua67damn@gmail.com

**Comment by seankhliao** [comment]
cc @golang/release

**Comment by cherrymui** [comment]
Hi @callthingsoff,

Thank you for your contributions and for requesting Trybots access! I've added you to the may-start-trybots group, so you should be able to do so now.

As you've likely read at https://github.com/golang/go/wiki/GerritAccess#running-trybots-may-start-trybots, please be sure to at least skim CLs before starting a Trybot run.

Let us know if you have any questions or issues with it, and thanks again!
