### ISSUE TITLE
”go build -race ./...“ Causing the program to not run correctly

### ISSUE THREAD

**Issue by buguang01** [golang/go#63720]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.21.3

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\xiachongshang\AppData\Local\go-build
set GOENV=C:\Users\xiachongshang\AppData\Roaming\go\env  
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=E:\gopath\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=E:\gopath
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.21.3
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=E:\goworks\gobige-demo\go.work
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\xiachongshang\AppData\Local\Temp\go-build912284024=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

package main

import "fmt"

func main() {
	fmt.Println("abc")
}

directory structure
-gatetest
-- Lobby
---main.go
--go.mod

cmd:
go build -race ./...
.\Lobby.exe

### What did you expect to see?

See output：
abc

### What did you see instead?

nothing in the world.

**Comment by seankhliao** [comment]
did you not get a executable or not get any output from the executable (and did it exit)?

**Comment by dr2chase** [comment]
Could not reproduce on Darwin.
Could not reproduce on a teetering stack of virtualization with windows-amd64 Go and gcc perched on top.
I think we need more information.

**Comment by buguang01** [comment]
[gatewtest.zip](https://github.com/golang/go/files/13185821/gatewtest.zip)

**Comment by buguang01** [comment]
![微信截图_20231027145542](https://github.com/golang/go/assets/48193468/bbfb47d2-3fa6-4ee0-9df3-38d65f4a3cbe)

**Comment by buguang01** [comment]
![微信截图_20231027145542](https://github.com/golang/go/assets/48193468/7c4e9922-c3ce-490f-ac21-126427c68cf8)

**Comment by buguang01** [comment]
@dr2chase

**Comment by buguang01** [comment]
@bcmills @dr2chase @seankhliao @evanphx

**Comment by buguang01** [comment]
@seankhliao What information is missing?
