### ISSUE TITLE
cmd/link: need to handle new-style loong64 relocs

### ISSUE THREAD

**Issue by abner-chenc** [golang/go#63725]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.3 linux/loong64
</pre>

### Does this issue reproduce with the latest release?

Yes (found during packaging testing)

### What operating system and processor architecture are you using (`go env`)?
Debian Linux sid, Loongson 3A5000.
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
cd $GOROOT/src/cmd/link && go test ./...

### What did you expect to see?
all tests pass

### What did you see instead?
```
ok  	cmd/internal/src	0.013s
ok  	cmd/internal/test2json	0.779s
--- FAIL: TestMinusRSymsWithSameName (0.76s)
    elf_test.go:164: gcc [-fPIC -mabi=lp64d -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build4287643683=/tmp/go-build -gno-record-gcc-switches] -c -o /tmp/TestMinusRSymsWithSameName5512364/001/x0.o /tmp/TestMinusRSymsWithSameName5512364/001/x0.c
    elf_test.go:164: gcc [-fPIC -mabi=lp64d -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build4287643683=/tmp/go-build -gno-record-gcc-switches] -c -o /tmp/TestMinusRSymsWithSameName5512364/001/x1.o /tmp/TestMinusRSymsWithSameName5512364/001/x1.c
    elf_test.go:172: gcc [-fPIC -mabi=lp64d -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build4287643683=/tmp/go-build -gno-record-gcc-switches] -nostdlib -r -o /tmp/TestMinusRSymsWithSameName5512364/001/ldr.syso [/tmp/TestMinusRSymsWithSameName5512364/001/x0.o /tmp/TestMinusRSymsWithSameName5512364/001/x1.o]
    elf_test.go:192: /root/debian-upstream/golang-1.21-1.21.3/bin/go build
    elf_test.go:197: # elf_test
        /tmp/go-build2943499130/b001/_pkg_.a(ldr.syso): unknown relocation type 66; compiled without -fpic?
    elf_test.go:198: exit status 1
FAIL
FAIL	cmd/link	13.001s
ok  	cmd/link/internal/benchmark	0.023s
```

**Comment by dr2chase** [comment]
@golang/compiler does this want a backport, perhaps?  The change is small, and this looks like regression (though I am not sure).

**Comment by cherrymui** [comment]
Looks fine with me. Up to the Loong64 maintainers for whether this needs backport.

I think this is not a regression, just the Go 1.21 doesn't support newer C toolchains. To be clear, what version of the C toolchain do you use?

**Comment by abner-chenc** [comment]
> @golang/compiler does this want a backport, perhaps? The change is small, and this looks like regression (though I am not sure).

This test failure has always existed on [Go1.21.](https://logs.chromium.org/logs/golang/buildbucket/cr-buildbucket/8747819804746988721/+/u/step/9/log/2) Can we backport this CL to the Go1.21 release-branch.
Thanks.

**Comment by cherrymui** [comment]
@gopherbot please backport this to Go 1.21. This causes test failures on the 1.21 release branch. Thanks.
