### ISSUE TITLE
bufio: optimize bufio.Reader.WriteTo() and bufio.Writer.ReadFrom()

### ISSUE THREAD

**Issue by gopherbot** [golang/go#6373]
by **valyala**:

<pre>Current implementations of bufio.Reader.WriteTo() and bufio.Writer.ReadFrom() can be
optimized further for common cases such as copying big files to / from network
connections.

See the following topic for details -
<a href="https://groups.google.com/d/msg/golang-nuts/oYYggbLntVE/DMsqEyIU-yIJ">https://groups.google.com/d/msg/golang-nuts/oYYggbLntVE/DMsqEyIU-yIJ</a></pre>

**Comment by odeke-em** [comment]
@vancluever perhaps you might be interested in this issue, if you get time and are bored :)

**Comment by odeke-em** [comment]
This issue got implemented with CLs https://golang.org/cl/69220046 aka commit https://github.com/golang/go/commit/b00e4770d962289ef1a542f153408d55e3307167 for .WriteTo which falls back to using the target's .ReadFrom method and then https://golang.org/cl/6548047 aka commit https://github.com/golang/go/commit/e289a2b913d476cf8592728e6d50767d0e29afde for the target's .WriteTo method thus we can close this legacy issue. Please reopen if necessary.
