### ISSUE TITLE
When i use go embed add my vue static file in my go file

### ISSUE THREAD

**Issue by nicelizhi** [golang/go#63747]
Dear all

When i use go embed add my Vue file  and then tell me don't match any file

![image](https://github.com/golang/go/assets/34465153/c1b69caa-fd41-4075-a490-f66533a464ca)

![image](https://github.com/golang/go/assets/34465153/9ff4daff-c196-4f77-b70c-9d43429ffc53)

### What version of Go are you using (`go version`)?

1.21

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by mauri870** [comment]
The Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
