### ISSUE TITLE
https://pkg.go.dev/database/sql#Conn.ExecContext

### ISSUE THREAD

**Issue by rolfostvik** [golang/go#63749]
### What version of Go are you using (`go version`)?

<pre>
Example on https://pkg.go.dev/database/sql#Conn.ExecContext
Example on https://pkg.go.dev/database/sql#DB.QueryRowContext
</pre>

### Does this issue reproduce with the latest release?

na

### What operating system and processor architecture are you using (`go env`)?

na

### What did you do?

Press the Run button for the example

### What did you expect to see?
A relevant example which can be used as is , but maybe with options for changes so that i can test it against may own database.
Or a relevant response from running the example.

### What did you see instead?

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x49fb34]

goroutine 1 [running]:
database/sql.(*DB).conn(0x0, {0x0, 0x0}, 0x1)
	/usr/local/go-faketime/src/database/sql/sql.go:1282 +0x54
database/sql.(*DB).query(0x413388?, {0x0, 0x0}, {0x4d0a46, 0x31}, {0xc000104e88, 0x1, 0x1}, 0xd0?)
	/usr/local/go-faketime/src/database/sql/sql.go:1721 +0x57
database/sql.(*DB).QueryContext.func1(0x10?)
	/usr/local/go-faketime/src/database/sql/sql.go:1704 +0x4f
database/sql.(*DB).retry(0xc000010018?, 0xc000104d98)
	/usr/local/go-faketime/src/database/sql/sql.go:1538 +0x42
database/sql.(*DB).QueryContext(0xc00003e730?, {0x0?, 0x0?}, {0x4d0a46?, 0x40b63e?}, {0xc00003e688?, 0x20003e670?, 0x0?})
	/usr/local/go-faketime/src/database/sql/sql.go:1703 +0xc5
database/sql.(*DB).QueryRowContext(...)
	/usr/local/go-faketime/src/database/sql/sql.go:1804
main.main()
	/tmp/sandbox2040142950/prog.go:19 +0xcd

**Comment by seankhliao** [comment]
it should be obvious that you need a database connection setup first
to not clutter an already long example, it just shows the parts relevant to calling the function and processing its response

**Comment by rolfostvik** [comment]
You forgot to mention that initializing the context (ctx) may be the next obvious step if a database connection already has been set up.
