### ISSUE TITLE
x/tools/gopls: (recovered) panic in canRemoveParameter

### ISSUE THREAD

**Issue by findleyr** [golang/go#63755]
Found via telemetry: https://storage.googleapis.com/prod-telemetry-merged/2023-10-25.json

There's a panic in lsp.canRemoveParameter: inspecting nil function bodies (as is the case for external functions) leads to a panic.

Fix incoming.

**Comment by adonovan** [comment]
This stack `9eOAKA` was [reported by telemetry](https://storage.googleapis.com/prod-telemetry-merged/2024-06-06.json):

```
gopls/bug
golang.org/x/tools/gopls/internal/bug.report:35
golang.org/x/tools/gopls/internal/bug.Errorf:2
golang.org/x/tools/gopls/internal/lsp.refactorRewrite.func1:2
runtime.gopanic:50
runtime.panicmem:?261
runtime.sigpanic:19
go/ast.Walk:184
go/ast.Inspect:?397
golang.org/x/tools/gopls/internal/lsp.canRemoveParameter:22
golang.org/x/tools/gopls/internal/lsp.refactorRewrite:14
golang.org/x/tools/gopls/internal/lsp.(*Server).codeAction:220
golang.org/x/tools/gopls/internal/lsp.(*Server).CodeAction:1
golang.org/x/tools/gopls/internal/lsp/protocol.serverDispatch:142
golang.org/x/tools/gopls/internal/lsp/lsprpc.(*StreamServer).ServeStream.ServerHandler.func3:5
golang.org/x/tools/gopls/internal/lsp/lsprpc.(*StreamServer).ServeStream.handshaker.func4:52
golang.org/x/tools/gopls/internal/lsp/protocol.Handlers.MustReplyHandler.func1:2
```
```
golang.org/x/tools/gopls@v0.14.0 go1.22.3 darwin/amd64 vscode (1)
```

Issue created by golang.org/x/tools/gopls/internal/telemetry/cmd/stacks.

**Comment by adonovan** [comment]
This stack `BTt5nw` was [reported by telemetry](https://telemetry.go.dev/data/2025-07-05):

- `gopls/bug`
- [`golang.org/x/tools/gopls/internal/bug.report:35`](https://cs.opensource.google/go/x/tools/+/gopls/v0.14.0:gopls/internal/bug/bug.go;l=106)
- [`golang.org/x/tools/gopls/internal/bug.Errorf:2`](https://cs.opensource.google/go/x/tools/+/gopls/v0.14.0:gopls/internal/bug/bug.go;l=58)
- [`golang.org/x/tools/gopls/internal/lsp.refactorRewrite.func1:2`](https://cs.opensource.google/go/x/tools/+/gopls/v0.14.0:gopls/internal/lsp/code_action.go;l=430)
- [`runtime.gopanic:80`](https://cs.opensource.google/go/go/+/go1.20.14:src/runtime/panic.go;l=884)
- `runtime.panicmem:?260`
- [`runtime.sigpanic:19`](https://cs.opensource.google/go/go/+/go1.20.14:src/runtime/signal_unix.go;l=841)
- [`go/ast.Walk:184`](https://cs.opensource.google/go/go/+/go1.20.14:src/go/ast/walk.go;l=234)
- `go/ast.Inspect:?397`
- [`golang.org/x/tools/gopls/internal/lsp.canRemoveParameter:22`](https://cs.opensource.google/go/x/tools/+/gopls/v0.14.0:gopls/internal/lsp/code_action.go;l=560)
- [`golang.org/x/tools/gopls/internal/lsp.refactorRewrite:14`](https://cs.opensource.google/go/x/tools/+/gopls/v0.14.0:gopls/internal/lsp/code_action.go;l=436)
- [`golang.org/x/tools/gopls/internal/lsp.(*Server).codeAction:220`](https://cs.opensource.google/go/x/tools/+/gopls/v0.14.0:gopls/internal/lsp/code_action.go;l=249)
- [`golang.org/x/tools/gopls/internal/lsp.(*Server).CodeAction:1`](https://cs.opensource.google/go/x/tools/+/gopls/v0.14.0:gopls/internal/lsp/server_gen.go;l=16)
- [`golang.org/x/tools/gopls/internal/lsp/protocol.serverDispatch:142`](https://cs.opensource.google/go/x/tools/+/gopls/v0.14.0:gopls/internal/lsp/protocol/tsserver.go;l=239)
- [`golang.org/x/tools/gopls/internal/lsp/protocol.ServerHandler.func1:5`](https://cs.opensource.google/go/x/tools/+/gopls/v0.14.0:gopls/internal/lsp/protocol/protocol.go;l=157)
- [`golang.org/x/tools/gopls/internal/lsp/lsprpc.handshaker.func1:52`](https://cs.opensource.google/go/x/tools/+/gopls/v0.14.0:gopls/internal/lsp/lsprpc/lsprpc.go;l=521)
- [`golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1:2`](https://cs.opensource.google/go/x/tools/+/gopls/v0.14.0:internal/jsonrpc2/handler.go;l=35)
```
golang.org/x/tools/gopls@v0.14.0 go1.20.14 darwin/amd64 vscode (1)
```

**Comment by adonovan** [comment]
This stack `3W4qPQ` was [reported by telemetry](https://telemetry.go.dev/data/2025-10-18):

- `gopls/bug`
- [`golang.org/x/tools/gopls/internal/bug.report:35`](https://cs.opensource.google/go/x/tools/+/gopls/v0.14.0:gopls/internal/bug/bug.go;l=106)
- [`golang.org/x/tools/gopls/internal/bug.Errorf:2`](https://cs.opensource.google/go/x/tools/+/gopls/v0.14.0:gopls/internal/bug/bug.go;l=58)
- [`golang.org/x/tools/gopls/internal/lsp.refactorRewrite.func1:2`](https://cs.opensource.google/go/x/tools/+/gopls/v0.14.0:gopls/internal/lsp/code_action.go;l=430)
- [`runtime.gopanic:50`](https://cs.opensource.google/go/go/+/go1.24.5:src/runtime/panic.go;l=792)
- `runtime.panicmem:?262`
- [`runtime.sigpanic:19`](https://cs.opensource.google/go/go/+/go1.24.5:src/runtime/signal_unix.go;l=925)
- [`go/ast.Walk:178`](https://cs.opensource.google/go/go/+/go1.24.5:src/go/ast/walk.go;l=211)
- `go/ast.Inspect:?372`
- [`golang.org/x/tools/gopls/internal/lsp.canRemoveParameter:22`](https://cs.opensource.google/go/x/tools/+/gopls/v0.14.0:gopls/internal/lsp/code_action.go;l=560)
- [`golang.org/x/tools/gopls/internal/lsp.refactorRewrite:14`](https://cs.opensource.google/go/x/tools/+/gopls/v0.14.0:gopls/internal/lsp/code_action.go;l=436)
- [`golang.org/x/tools/gopls/internal/lsp.(*Server).codeAction:220`](https://cs.opensource.google/go/x/tools/+/gopls/v0.14.0:gopls/internal/lsp/code_action.go;l=249)
- [`golang.org/x/tools/gopls/internal/lsp.(*Server).CodeAction:1`](https://cs.opensource.google/go/x/tools/+/gopls/v0.14.0:gopls/internal/lsp/server_gen.go;l=16)
- [`golang.org/x/tools/gopls/internal/lsp/protocol.serverDispatch:142`](https://cs.opensource.google/go/x/tools/+/gopls/v0.14.0:gopls/internal/lsp/protocol/tsserver.go;l=239)
- [`golang.org/x/tools/gopls/internal/lsp/lsprpc.(*StreamServer).ServeStream.ServerHandler.func3:5`](https://cs.opensource.google/go/x/tools/+/gopls/v0.14.0:gopls/internal/lsp/protocol/protocol.go;l=157)
- [`golang.org/x/tools/gopls/internal/lsp/lsprpc.(*StreamServer).ServeStream.handshaker.func4:52`](https://cs.opensource.google/go/x/tools/+/gopls/v0.14.0:gopls/internal/lsp/lsprpc/lsprpc.go;l=521)
- [`golang.org/x/tools/gopls/internal/lsp/protocol.Handlers.MustReplyHandler.func1:2`](https://cs.opensource.google/go/x/tools/+/gopls/v0.14.0:internal/jsonrpc2/handler.go;l=35)
```
golang.org/x/tools/gopls@v0.14.0 go1.24.5 linux/amd64 vscode (1)
```
