### ISSUE TITLE
cmd/go,cmd/link: "go build" doesn't rebuild the binary after build flags changed

### ISSUE THREAD

**Issue by sandy-lcq** [golang/go#63760]
I am doing cross compile with go,  version 1.20.6. 

Reproduce steps:
1.  go build -p 48 -v -ldflags="-r /usr/lib/go/pkg/linux_arm64_dynlink  -I /lib64/ld-linux-aarch64.so.1  ..."   ...
      this command will generate an binary under builds/plugins/bin/brigde
2. Don't delete builds/plugins/bin/brigde,   Don't change any code or others, only change dynamic link path in ldflags,  dynamic linker changed from " /lib64/ld-linux-aarch64.so.1" to " /usr/lib/ld-linux-aarch64.so.1". 
    Run  go build -p 48 -v -ldflags="-r /usr/lib/go/pkg/linux_arm64_dynlink  -I /usr/lib/ld-linux-aarch64.so.1  ..."   ...
3.  readelf -a builds/plugins/bin/brigde | grep interpre
     we can see the binary brigde still have the old dynamic linker, this will make bridge cannot run on target.

It seems like that "go build" only checks if the cached packagefile is changed,  since we don't change any code in step 2,  cached packagefile not changed, and bridge is still there,  so it did not  relink with the new dynamic linker.   I think it should relink.

**Comment by bcmills** [comment]
Please fill out the complete issue template, including the requested output from `go version` and `go env` and the complete command lines used to build the binaries.

**Comment by bcmills** [comment]
The linker flags are supposed to be recorded in the cache key here:
https://cs.opensource.google/go/go/+/master:src/cmd/go/internal/work/exec.go;l=1393-1396;drc=b3acaa8230e95c232a6f5c30eb7619a0c859ab16

@sandy-lcq, can you set `GODEBUG=gocachehash=1` in your environment during both builds and check the `link ` and `linkflags ` lines in the resulting output?

**Comment by sandy-lcq** [comment]
Hi,  Here is reproduce steps and corresponding log:
1.  `$aarch64-wrs-linux-go env `
[env.log](https://github.com/golang/go/files/14079339/env.log)
2.  `$env | grep GO`
[goenv.log](https://github.com/golang/go/files/14079342/goenv.log)
3.
 ```
$rm /build/tmp-glibc/work/cortexa72-wrs-linux/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0/build/plugins/bin/bridge
$aarch64-wrs-linux-go build -p 48 -v -ldflags="-r /usr/lib64/go/pkg/linux_arm64_dynlink  -I /lib64/ld-linux-aarch64.so.1 -extldflags ' -mcpu=cortex-a72 -march=armv8-a+crc -mbranch-protection=standard -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/build/tmp-glibc/work/cortexa72-wrs-linux/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0/recipe-sysroot -Wl,-rpath-link=/build/tmp-glibc/work/cortexa72-wrs-linux/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0/recipe-sysroot/usr/lib64/go/pkg/linux_arm64_dynlink -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -fmacro-prefix-map=/build/tmp-glibc/work/cortexa72-wrs-linux/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0/cni-v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb=/usr/src/debug/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0  -fdebug-prefix-map=/build/tmp-glibc/work/cortexa72-wrs-linux/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0/cni-v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb=/usr/src/debug/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0  -fmacro-prefix-map=/build/tmp-glibc/work/cortexa72-wrs-linux/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0/build=/usr/src/debug/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0  -fdebug-prefix-map=/build/tmp-glibc/work/cortexa72-wrs-linux/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0/build=/usr/src/debug/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0  -fdebug-prefix-map=/build/tmp-glibc/work/cortexa72-wrs-linux/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0/recipe-sysroot=  -fmacro-prefix-map=/build/tmp-glibc/work/cortexa72-wrs-linux/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0/recipe-sysroot=  -fdebug-prefix-map=/build/tmp-glibc/work/cortexa72-wrs-linux/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0/recipe-sysroot-native=  -Wl,-z,relro,-z,now'" -trimpath -buildmode=pie -o /build/tmp-glibc/work/cortexa72-wrs-linux/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0/build/plugins/bin/bridge github.com/containernetworking/plugins/plugins/main/bridge
$ readelf -a bridge | grep interpre
 [Requesting program interpreter: /lib64/ld-linux-aarch64.so.1]
```
[first_build.log](https://github.com/golang/go/files/14079359/first_build.log)

4.
```
 $aarch64-wrs-linux-go build -p 48 -v -ldflags="-r /usr/lib64/go/pkg/linux_arm64_dynlink  -I /usr/lib64/ld-linux-aarch64.so.1 -extldflags ' -mcpu=cortex-a72 -march=armv8-a+crc -mbranch-protection=standard -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/build/tmp-glibc/work/cortexa72-wrs-linux/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0/recipe-sysroot -Wl,-rpath-link=/build/tmp-glibc/work/cortexa72-wrs-linux/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0/recipe-sysroot/usr/lib64/go/pkg/linux_arm64_dynlink -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -fmacro-prefix-map=/build/tmp-glibc/work/cortexa72-wrs-linux/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0/cni-v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb=/usr/src/debug/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0  -fdebug-prefix-map=/build/tmp-glibc/work/cortexa72-wrs-linux/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0/cni-v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb=/usr/src/debug/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0  -fmacro-prefix-map=/build/tmp-glibc/work/cortexa72-wrs-linux/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0/build=/usr/src/debug/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0  -fdebug-prefix-map=/build/tmp-glibc/work/cortexa72-wrs-linux/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0/build=/usr/src/debug/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0  -fdebug-prefix-map=/build/tmp-glibc/work/cortexa72-wrs-linux/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0/recipe-sysroot=  -fmacro-prefix-map=/build/tmp-glibc/work/cortexa72-wrs-linux/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0/recipe-sysroot=  -fdebug-prefix-map=/build/tmp-glibc/work/cortexa72-wrs-linux/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0/recipe-sysroot-native=  -Wl,-z,relro,-z,now'" -trimpath -buildmode=pie -o /build/tmp-glibc/work/cortexa72-wrs-linux/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0/build/plugins/bin/bridge github.com/containernetworking/plugins/plugins/main/bridge
$ readelf -a bridge | grep interpre
 [Requesting program interpreter: /lib64/ld-linux-aarch64.so.1]
```
[second_build.log](https://github.com/golang/go/files/14079365/second_build.log)

5. 
```
$rm /build/tmp-glibc/work/cortexa72-wrs-linux/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0/build/plugins/bin/bridge
$aarch64-wrs-linux-go build -p 48 -v -ldflags="-r /usr/lib64/go/pkg/linux_arm64_dynlink  -I /usr/lib64/ld-linux-aarch64.so.1  -extldflags ' -mcpu=cortex-a72 -march=armv8-a+crc -mbranch-protection=standard -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/build/tmp-glibc/work/cortexa72-wrs-linux/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0/recipe-sysroot -Wl,-rpath-link=/build/tmp-glibc/work/cortexa72-wrs-linux/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0/recipe-sysroot/usr/lib64/go/pkg/linux_arm64_dynlink -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -fmacro-prefix-map=/build/tmp-glibc/work/cortexa72-wrs-linux/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0/cni-v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb=/usr/src/debug/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0  -fdebug-prefix-map=/build/tmp-glibc/work/cortexa72-wrs-linux/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0/cni-v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb=/usr/src/debug/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0  -fmacro-prefix-map=/build/tmp-glibc/work/cortexa72-wrs-linux/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0/build=/usr/src/debug/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0  -fdebug-prefix-map=/build/tmp-glibc/work/cortexa72-wrs-linux/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0/build=/usr/src/debug/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0  -fdebug-prefix-map=/build/tmp-glibc/work/cortexa72-wrs-linux/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0/recipe-sysroot=  -fmacro-prefix-map=/build/tmp-glibc/work/cortexa72-wrs-linux/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0/recipe-sysroot=  -fdebug-prefix-map=/build/tmp-glibc/work/cortexa72-wrs-linux/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0/recipe-sysroot-native=  -Wl,-z,relro,-z,now'" -trimpath -buildmode=pie -o /build/tmp-glibc/work/cortexa72-wrs-linux/cni/v1.1.2+gitf024754da8d49bdac31d99d04355ddfe0340f8eb-r0/build/plugins/bin/bridge github.com/containernetworking/plugins/plugins/main/bridge
$ readelf -a bridge | grep interpre
[Requesting program interpreter: /usr/lib64/ld-linux-aarch64.so.1]
```
[third_build.log](https://github.com/golang/go/files/14079371/third_build.log)


NOTE:
1. The only change in command "aarch64-wrs-linux-go build xxx" in step3/4/5 is bold part thesame as previous discussion.
2.  I don't find linkflags in the output,  maybe becasue my toolchainName matched gccgo in below line:
https://cs.opensource.google/go/go/+/master:src/cmd/go/internal/work/exec.go;drc=b3acaa8230e95c232a6f5c30eb7619a0c859ab16;l=1420
 and in second_build.log,  There is no output like below,  but other 2 logs have it.
HASH subkey 5914338cba0fbdac08ce1ac733694989411fa0d387485b4d0369503a6cbb036a "link-stdout" = 04ebc72aa9e5cbcf71c575d9225139a74c12bde9f96f7d97e57123036b739af

**Comment by bcmills** [comment]
Huh. I see the `link\n` lines from [here](https://cs.opensource.google/go/go/+/refs/tags/go1.20.6:src/cmd/go/internal/work/exec.go;l=1293;drc=c0ed873cd8259f16d0da67eee783fda49f45ef61) in the build logs.

The output from `b.printLinkerConfig` should be in between the `trimpath` link and the first `packagefile` line in the logs, but it is missing.

`b.printLinkerConfig` unconditionally writes a `link` line with additional linker details:
- [for `"gc"`](https://cs.opensource.google/go/go/+/refs/tags/go1.20.6:src/cmd/go/internal/work/exec.go;l=1337;drc=c0ed873cd8259f16d0da67eee783fda49f45ef61)
- [for `"gccgo"`](https://cs.opensource.google/go/go/+/refs/tags/go1.20.6:src/cmd/go/internal/work/exec.go;l=1369;drc=c0ed873cd8259f16d0da67eee783fda49f45ef61)

And in the `default` case, it calls `base.Fatalf`.

So the only possibilities I can see are:
1. Your build of the `go` toolchain has been modified with a third case that does not print anything, or
2. the compiler is somehow miscompiling `printLinkerConfig` so that it is not taking any of the defined branches in the `switch`.

@sandy-lcq, can you confirm that the source code used to build your `go` command exactly matches the contents tagged at `go1.20.6` in https://go.googlesource.com/go?

**Comment by sandy-lcq** [comment]
@bcmills Thanks.  I find that my go command have an local patch,  uncomments https://cs.opensource.google/go/go/+/refs/tags/go1.20.6:src/cmd/go/internal/work/exec.go;drc=c0ed873cd8259f16d0da67eee783fda49f45ef61;l=1302 and https://cs.opensource.google/go/go/+/refs/tags/go1.20.6:src/cmd/go/internal/work/exec.go;drc=c0ed873cd8259f16d0da67eee783fda49f45ef61;l=1597.

After revert it, above issue cannot reproduce. So I will close this.
