### ISSUE TITLE
mime: wrong content-type return when use svg as css background-image

### ISSUE THREAD

**Issue by gopherbot** [golang/go#6378]
by **ipv6.elata**:

<pre>the right return content-type is image/svg+xml

Which operating system are you using?
windows 7 64bit

Which version are you using?  (run 'go version')
go1.1.2 windows/386

Please provide any additional information below.
the related source file is
<a href="http://golang.org/src/pkg/mime/type.go">http://golang.org/src/pkg/mime/type.go</a>
but modify the registry to edit mimetypes is very trouble on winodws
I think  the easy way is add a mime type 
&quot;.svg&quot;:  &quot;image/svg+xml&quot;, in mimeTypes</pre>

**Comment by odeke-em** [comment]
This issue seems to have already been fixed by commit https://github.com/golang/go/commit/21e47d831bafb59f22b1ea8098f709677ec8ce33 through CL https://go-review.googlesource.com/#/c/7942. The CL just hadn't mentioned it.
Proof that it works here http://play.golang.org/p/gN51TN-BzZ.
