### ISSUE TITLE
affected/package: for k,v range map

### ISSUE THREAD

**Issue by wxmeng04** [golang/go#63797]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.3 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
I removed PROXY settings below only.
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=D:\Tools\go\bin
set GOCACHE=C:\Users\SQC_WXM\AppData\Local\go-build
set GOENV=C:\Users\SQC_WXM\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\SQC_WXM\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\SQC_WXM\go
set GOPRIVATE=xace.top/*
set GOPROXY=
set GOROOT=D:\Tools\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=D:\Tools\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.21.3
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=E:\Project\wxm\utils\resp3\go.mod
set GOWORK=E:\Project\wxm\utils\go.work
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\SQC_WXM\AppData\Local\Temp\go-build270273932=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
The functionality of below code is to subscribe a `topic` in a new goroutine and publish `payload` on the same `topic` without new goroutine created. In order to perform a test, a map is predefined with key as `topic` and value as `payload`. 
case 1 may fail with different result and may pass as well while the case 2 always pass. Is there any concurrency criteria for the `k, v` pair derived from `a for loop` based on a map? As far as I know, there is a problem when you use map as a whole in concurrent go routines. But for the k, v, do I have to make a copy if it's intended to use them in a new go routine? I don't change k or v at all in the subroutine and just read.

**case 1: below code may fail but not always**
```
// global map
var pairs = map[string]string{
	"abc": "def",
	"aef": "kkk",
	"888": "6666",
	"bbb": "777",
}
// piece of code in a test function
	for k, v := range pairs {
		client.Subscribe(context.Background(), k,
			func(s string) {
				if s != payload {
					t.Errorf("Topic: %s, Expecting: %s, Get: %s", k, v, s)
				}
			},
		)

		for i := 0; i < 50; i++ {
			client.Publish(k, v)
		}
	}
```
result of one trial fails
=== RUN   Test_PubSub
    resp3_test.go:127: Topic: aef, Expecting: kkk, Get: def
    resp3_test.go:127: Topic: 888, Expecting: 6666, Get: kkk
    resp3_test.go:127: Topic: bbb, Expecting: 777, Get: 6666
--- FAIL: Test_PubSub (4.67s)

**case 2: below code never fail**
```
// global map
var pairs = map[string]string{
	"abc": "def",
	"aef": "kkk",
	"888": "6666",
	"bbb": "777",
}
// piece of code in a test function
	for k, v := range pairs {
		topic, payload := k, v // If I remove this line and use `k` and `v` directly, the test may fail but not always.
		client.Subscribe(context.Background(), topic,
			func(s string) {
				if s != payload {
					t.Errorf("Topic: %s, Expecting: %s, Get: %s", topic, payload, s)
				}
			},
		)

		for i := 0; i < 50; i++ {
			client.Publish(topic, payload)
		}
	}
```
### What did you expect to see?
I'm expecting to get the same result for the two cases.

### What did you see instead?
I got different results for the two cases.

**Comment by rittneje** [comment]
https://go.dev/doc/faq#closures_and_goroutines

**Comment by wxmeng04** [comment]
> https://go.dev/doc/faq#closures_and_goroutines

Noted. If a copy of the value is a must in the current version of go, what about the key? do I have to copy as well?

**Comment by rittneje** [comment]
The issue applies to both loop variables. So yes, you need to copy both.

Note that with the upcoming loopvar change, this will no longer be necessary. https://github.com/golang/go/wiki/LoopvarExperiment

**Comment by wxmeng04** [comment]
> The issue applies to both loop variables. So yes, you need to copy both.
> 
> Note that with the upcoming loopvar change, this will no longer be necessary. https://github.com/golang/go/wiki/LoopvarExperiment

Expect to use a new released version with the problem solved. I struggle with myself to check the logic of my program. I will read the page you shared completedly to check if there are other cautions. Thank you so much!
