### ISSUE TITLE
net/http/cgi: TestDirWindows fails on Windows when `perl` is installed

### ISSUE THREAD

**Issue by qiulaidongfeng** [golang/go#63800]
### What version of Go are you using (`go version`)?

<pre>
$ go version
tip
</pre>

### Does this issue reproduce with the latest release?

yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=D:\tmp\go-build
set GOENV=C:\Users\26454\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\file\gofile\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\file\gofile
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=D:\file\gofile\gogit\go1
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=local
set GOTOOLDIR=D:\file\gofile\gogit\go1\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=devel go1.22-2968f56 Fri Oct 20 03:00:06 2023 +0000
set GCCGO=gccgo
set GOAMD64=v3
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\file\gofile\gogit\go1\src\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\26454\AppData\Local\Temp\go-build532945110=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
Install Git-2.42.0.2-64-bit.exe,There's perl in here.
go test net/http/cgi

### What did you expect to see?
test passed.

### What did you see instead?

```
--- FAIL: TestDirWindows (0.16s)
    host_test.go:67: Unexpected response from invalid line number 25: "(c) Microsoft Corporation\xa1\xa3\xb1\xa3\xc1\xf4\xcb\xf9\xd3\xd0Ȩ\xc0\xfb\xa1\xa3\r\n"; existing map=map[_body:test=Hello CGI
        env-COMSPEC=C:\Windows\system32\cmd.exe
        env-GATEWAY_INTERFACE=CGI/1.1
        env-HOME=/c/Users/26454
        env-HTTP_HOST=example.com
        env-PATH=/d/file/gofile/gogit/go1/bin:/tmp/system32:/tmp:/tmp/System32/Wbem:/tmp/System32/WindowsPowerShell/v1.0:/tmp/System32/OpenSSH:/d/file/gofile/bin:/c/Users/26454/.go/current/bin:/d/cloc:/bin:/usr/bin:/d/goup:/d/Graphviz/bin:/d/pandoc:/d/mingw64/bin:/c/Users/26454/AppData/Local/Microsoft/WindowsApps:/c/Users/26454/AppData/Local/GitHubDesktop/bin
        env-PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
        env-PATH_INFO=
        env-QUERY_STRING=
        env-REMOTE_ADDR=1.2.3.4
        env-REMOTE_HOST=1.2.3.4
        env-REMOTE_PORT=1234
        env-REQUEST_METHOD=GET
        env-REQUEST_URI=/test.cgi
        env-SCRIPT_FILENAME=D:\file\gofile\gogit\go1\src\net\http\cgi\testdata\test.cgi
        env-SCRIPT_NAME=/test.cgi
        env-SERVER_NAME=example.com
        env-SERVER_PORT=80
        env-SERVER_PROTOCOL=HTTP/1.1
        env-SERVER_SOFTWARE=go
        env-SYSTEMROOT=C:\Windows
        env-TERM=xterm-256color
        env-WINDIR=C:\Windows
        cwd=Microsoft Windows [�汾 10.0.22621.2428]
        (c) Microsoft Corporation����������Ȩ����

        D:\file\gofile\gogit\go1\src\net\http\cgi>
         cwd:Microsoft Windows [�汾 10.0.22621.2428] env-COMSPEC:C:\Windows\system32\cmd.exe env-GATEWAY_INTERFACE:CGI/1.1 env-HOME:/c/Users/26454 env-HTTP_HOST:example.com env-PATH:/d/file/gofile/gogit/go1/bin:/tmp/system32:/tmp:/tmp/System32/Wbem:/tmp/System32/WindowsPowerShell/v1.0:/tmp/System32/OpenSSH:/d/file/gofile/bin:/c/Users/26454/.go/current/bin:/d/cloc:/bin:/usr/bin:/d/goup:/d/Graphviz/bin:/d/pandoc:/d/mingw64/bin:/c/Users/26454/AppData/Local/Microsoft/WindowsApps:/c/Users/26454/AppData/Local/GitHubDesktop/bin env-PATHEXT:.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL env-PATH_INFO: env-QUERY_STRING: env-REMOTE_ADDR:1.2.3.4 env-REMOTE_HOST:1.2.3.4 env-REMOTE_PORT:1234 env-REQUEST_METHOD:GET env-REQUEST_URI:/test.cgi env-SCRIPT_FILENAME:D:\file\gofile\gogit\go1\src\net\http\cgi\testdata\test.cgi env-SCRIPT_NAME:/test.cgi env-SERVER_NAME:example.com env-SERVER_PORT:80 env-SERVER_PROTOCOL:HTTP/1.1 env-SERVER_SOFTWARE:go env-SYSTEMROOT:C:\Windows env-TERM:xterm-256color env-WINDIR:C:\Windows test:Hello CGI]
2023/10/28 19:33:32 cgi: copy error: past write limit
2023/10/28 19:33:32 cgi: no headers
2023/10/28 19:33:32 cgi: missing required Content-Type in headers
2023/10/28 19:33:32 cgi: no headers
FAIL
exit status 1
FAIL    net/http/cgi    2.277s
```

**Comment by bcmills** [comment]
It looks like this comes from a bad Perl script here:
https://cs.opensource.google/go/go/+/master:src/net/http/cgi/testdata/test.cgi;l=50-62;drc=45d334ecf1b2bcbf0f8667d4c772ef3db0e03587

**Comment by bcmills** [comment]
Perhaps the test's Perl script could be fixed, but I think it would be better still to rewrite the test CGI handler in Go, for which I have filed #63828.
