### ISSUE TITLE
net:  Windows not support Bind for a raw/tcp socket

### ISSUE THREAD

**Issue by lysShub** [golang/go#63807]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.3 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\lys\AppData\Local\go-build
set GOENV=C:\Users\lys\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\gopath\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\gopath
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.21.3
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
</pre></details>

### What did you do?

```go
package main

import "net"

func main(){
        conn, err := net.ListenIP("ip4:tcp", &net.IPAddr{IP: net.IPv4(0, 0, 0, 0)})
        if err != nil {
	        panic(err)
        }
        defer conn.Close()
}
```

### What did you expect to see?

no error

### What did you see instead?

```txt
panic: listen ip4:tcp 0.0.0.0: bind: An invalid argument was supplied.

goroutine 1 [running]:
main.main()
        D:/OneDrive/code/go/atest/main.go:27 +0x155
exit status 2
```

**Comment by lysShub** [comment]
Windows not support Bind for a raw/tcp socket, [ref](https://learn.microsoft.com/en-us/windows/win32/winsock/tcp-ip-raw-sockets-2#:~:text=A%20call%20to%20the%20bind%20function%20with%20a%20raw%20socket%20for%20the%20IPPROTO_TCP%20protocol%20is%20not%20allowed.)

**Comment by seankhliao** [comment]
Given that windows doesn't support it, I don't think there's anything for Go to do.
