### ISSUE TITLE
x/exp/slog: Customising log source value

### ISSUE THREAD

**Issue by bentcoder** [golang/go#63811]
Hi,

RE: https://github.com/golang/go/issues/59280#issuecomment-1487344160

> `func (s *Source) String() string { return fmt.Sprintf("%s:%d", s.File, s.Line) }`

What @rsc suggested above is what all our app's are doing for many years. I am wondering if I can **somehow** accomplish the same behaviour using Slog?

If there is still possibility for a simple string value, I will then get rid of working directory from it (`file`) and have a final value as shown below.

```
"source": "/Users/myself/dev/tetris/cmd/api/main.go:15" <--- FROM
"source": "/cmd/api/main.go:15"                         <--- TO
```

**Note**: I am coming from Zerolog and Logrus background and both have this possibility but I am not sure if Slog has it. If id does, I prefer migrating to Slog.

Thank you

CC: @jba

**Comment by seankhliao** [comment]
see slog.SouceKey and slog.Record.PC

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
