### ISSUE TITLE
net/http/cgi: eliminate use of Perl in tests

### ISSUE THREAD

**Issue by bcmills** [golang/go#63828]
`net/http/cgi` currently uses a Perl script (`testdata/test.cgi`) for some of its tests:
https://cs.opensource.google/search?q=perl%20file:go%20file:net%2Fhttp%2Fcgi&sq=&ss=go%2Fgo

Unfortunately, that can cause spurious failures due to bugs in the Perl script, such as:
- #63800
- #27790

Those failures are easily masked, because the tests are skipped on builders that do not have Perl installed (as appears to be the case for our Windows builders). The use of Perl also makes those tests harder for Go maintainers to review and maintain, since many of us are not very familiar with the Perl language.

I don't see a compelling reason why the test needs to use Perl for this, given that it could just as easily `go build` a handler written in Go.

See previously:
- #20032
- #25586
- #25669
- #27779

**Comment by raghvenders** [comment]
@bcmills - Working on this. Is this only for test.cgi? I have seen at the high level it looks like returning html and handling query params. May be some more while implementing.

At high level all the tests should pass with go cgi handler?

**Comment by bcmills** [comment]
@raghvenders, I would expect that the test handler can be rewritten using `cgi.Request` to parse the input, and write the output in roughly the same manner as the existing Perl script.

To avoid the need to explicitly `go build` a CGI binary, the test binary itself can also function as the CGI handler, using an environment variable to tell the child process's `TestMain` to handle the CGI request instead of running the test.  (For an example of that approach, see `func TestMain` in `src/cmd/vet/vet_test.go`.)

The calls to `check(t)` should be replaced with calls to [`testenv.MustHaveExec(t)`](https://pkg.go.dev/internal/testenv#MustHaveExec), and with that approach all of the tests should either pass (on most platforms) or skip (on `js`, `wasip1`, and perhaps `ios`, which do not support executing a subprocess).

**Comment by raghvenders** [comment]
@bcmills - Shall the cgi handler be like another child test process ?

1. 
```
h := &Handler{
		Path: os.Args[0], // cgi.test.exe
		Root: "/test.go",
		Args: []string{"-test.run=^GoCGIChildProcess$"},
	}

```

Let GoCGIChildProcess- handle and do output what test.cgi does currently.

the above handler will be available for all the test.cgi based tests like TestCGIBasicGet, TestDirWindows, etc. 

2.
Please do correct me on the understanding part of TestMain :

```
// TestMain executes the test binary as the go test command if
// GO_CGI_TEST is set, and runs the tests otherwise.
func TestMain(m *testing.M) {
	if os.Getenv("GO_CGI_TEST") != "" {
		main()
		os.Exit(0)
	}



	os.Setenv("GO_CGI_TEST", "1") // Set for subprocesses to inherit.
	os.Exit(m.Run())
}

```
we have to have above TestMain like this, so all the testcgi will inherit the above env - GO_CGI_TEST in their subprocess ?

 3. Instead of test sub-process  -test.run=^GoCGIChildProcess$, are you expecting GoCGIChildProcess as a GoCGIChildProcess.go file to have go run GoCGIChildProcess.go ?

**Comment by aimuz** [comment]
@bcmills Do you have time to review the code please, I've submitted a patch

https://github.com/golang/go/pull/63869
