### ISSUE TITLE
x/sys/unix/linux: update Linux to v6.6

### ISSUE THREAD

**Issue by mauri870** [golang/go#63833]
The Linux kernel v6.6 released today, 30 October 2023.

https://www.kernel.org

We should be able to update the sources in x/sys by changing the unix/linux/Dockerfile and running GOOS=linux ./mkall.sh. This should be done for all architectures.

**Comment by mauri870** [comment]
Well there is no way I can generate the files for all the architectures, so I'll leave this open until someone decides to contribute all the files in a single CL.

**Comment by tklauser** [comment]
We usually don't require issues for these types of updates in x/sys. It's fine to just open a CL.
