### ISSUE TITLE
 Feedback/Issue with pkg.go.dev:

### ISSUE THREAD

**Issue by mrCleverIdiot** [golang/go#63839]
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/otpless-tech/otpless-auth-sdk.git

### What is your user agent?
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Safari/605.1.15

### Screenshot

<img width="1461" alt="Screenshot 2023-10-31 at 12 31 28 PM" src="https://github.com/golang/go/assets/37953417/dbdd140f-bc38-4f93-a6ea-c78f1bc3473a">

### What did you do?

I want to publish my module into pkg.go.dev 
in my pkg I have one auth sdk

**Comment by Jorropo** [comment]
You can view https://github.com/golang/go/wiki/Questions to see where to ask questions :)

---

You need to use the import path not the repository URL.
So https://pkg.go.dev/github.com/otpless-tech/otpless-auth-sdk
