### ISSUE TITLE
affected/package: time

### ISSUE THREAD

**Issue by shaoqingyang** [golang/go#63843]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.18.10 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Indeed, it is.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/shaoqingyang/Library/Caches/go-build"
GOENV="/Users/shaoqingyang/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/shaoqingyang/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/shaoqingyang/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.18.10"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/l3/w03l6vys18x_nkn5nsmgpzn00000gn/T/go-build1210182971=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I need to calculate the date one month ago. If today is October 31st, the time calculated using the AddDate() method is October 1st, and the underlying code does not take into account the different days of each month.
I provide some code and hope to receive your modifications.
<pre>
func GetMonthToday(t time.Time, month int) time.Time {
	if t.Day() <= 28 {
		return t.AddDate(0, -month, 0)
	}
	monthDay := [13]int{0, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31}
	target := t.AddDate(0, 0, 1-t.Day()).AddDate(0, -month, 0)
	targetDay := monthDay[target.Month()]
	if target.Month() == time.February && (target.Year()%400 == 0 || (target.Year()%100 != 0 && target.Year()%4 == 0)) {
		targetDay++
	}
	if t.Day() > targetDay {
		return target.AddDate(0, 0, targetDay-1)
	}
	return target.AddDate(0, 0, t.Day()-1)
}
</pre>

### What did you expect to see?
I hope that future versions can consider my proposed issue.

### What did you see instead?
The mistake of AddDate()

**Comment by mauri870** [comment]
I'm not sure if I follow along with the problem you are reporting, it seems that AddDate is working as intended. Can you clarify what you think the bug is and a clear way to reproduce it? Thanks

**Comment by doggedOwl** [comment]
@shaoqingyang maybe what is confusing you is the normalization of the date. 
addDate(0, -1 , 0) upplied for exampe to today (31/10/2023) will correctly produce 01/10/2023 because the calculated date of 1 month ago is 31/09/2023. Since september can not have 31 days the date gets normalised to 01 of October.

**Comment by mauri870** [comment]
Normalization is explicitly stated in the docs for [AddDate](https://pkg.go.dev/time#Time.AddDate).

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to [https://github.com/golang/go/wiki/Questions](https://github.com/golang/go/wiki/Questions)
