### ISSUE TITLE
gerrit: mail CL hangs

### ISSUE THREAD

**Issue by felixge** [golang/go#63841]
### What did you do?

```
git codereview mail
```

### What did you expect to see?

A response from the Gerrit server.

### What did you see instead?

The process is hanging at `git push -q origin HEAD:refs/for/master`. When I run this command and replace the `-q` flag with `-v`, I get the following output before is starts hanging:

```
$ git push -v origin HEAD:refs/for/master
Pushing to https://go.googlesource.com/go
Enumerating objects: 210, done.
Counting objects: 100% (210/210), done.
Delta compression using up to 10 threads
Compressing objects: 100% (134/134), done.
Writing objects: 100% (171/171), 147.38 KiB | 10.53 MiB/s, done.
Total 171 (delta 81), reused 73 (delta 29), pack-reused 0
POST git-receive-pack (151068 bytes)
```

This seems similar to https://github.com/golang/go/issues/30905. Is Gerrit having problems right now? I saw the issue intermittently yesterday already, but it went away after a few retries. Now it seems to be persistent.

**Comment by felixge** [comment]
Hm, the problem went away after updating the CL I was trying to mail. It was already modified before I tried mailing it, so I don't thing the hanging was caused by trying to push the same patchset twice.

Closing this for now. Will reopen if I see it again.

**Comment by felixge** [comment]
Seeing the issue again after trying to push another update to [my CL](https://go-review.googlesource.com/c/go/+/538515). Reopening.

**Comment by cherrymui** [comment]
@felixge does it still hang? I just tried to mail a CL and it works fine.

It seems you can reproduce by using `git` directly, so this is not specific to the `codereview` tool, right?

**Comment by felixge** [comment]
Yeah, it's still hanging. It's not specific to the `codereview` tool. I updated the issue description to show the output of using `-v` mode on `git push`, which might provide some more clues. I've also realized that if I kill the hanging push and retry the same command a few times in a row, I'm usually able to get it to succeed.

**Comment by felixge** [comment]
> Meanwhile, there are a lot of CLs mailed in the past a few days, and it seems to work okay for most people.

I mostly opened this issue to check if I'm the only one having problems. Since that seems to be the case, I'll close this issue under the assumption that it's a problem on my end.

I've tried a different network already without success. I'll post an update when I get a chance to try another machine or find other clues.
