### ISSUE TITLE
encoding/json: encode precise floating point integers using %.0f, not %g

### ISSUE THREAD

**Issue by joeshaw** [golang/go#6384]
<pre>Go 1.1.2 on OS X 10.8.4, and on play.golang.org.

If you unmarshal a JSON numeric value into interface{}, it is encoded as a float64.  If
it is sufficiently large (&gt;= 1e6, I believe) when you marshal it, it is encoded as a
string using exponent notation.  If the original value was an integer and you later try
to decode into an int64 value, an error is returned.

Example code is available here: <a href="http://play.golang.org/p/fYuB4tT7Ul">http://play.golang.org/p/fYuB4tT7Ul</a>

Using 'f' for the fmt byte to AppendFloat() instead of 'g' in
<a href="http://golang.org/src/pkg/encoding/json/encode.go#L334">http://golang.org/src/pkg/encoding/json/encode.go#L334</a> would solve this problem, as
values which can be represented as integers will be encoded in a way that can be read
back in as integers.

(There are other issues as you get to very large values, since float64 can't encode a
whole int64... not sure what or if anything can be done about that.)</pre>

**Comment by parkr** [comment]
I'm using protobufs and in order to maintain compatibility with Node land, we can't use int64 in our messages. This breaks the deserialization of json ~> protobuf when a valid int32 is serialized into json, then deserialized into a protobuf.

**Comment by integrii** [comment]
Jesus thank you @rsc - This has been a thorn for anyone encoding lat/lon with six points of precision (common for mobile app use).  Though I would argue that we should go even further and use a decimal for even much larger numbers... perhaps even 1e-10.

Please someone merge this to a release branch!

**Comment by ianlancetaylor** [comment]
This is not the kind of change we put on a release branch.  It will be in the Go 1.8 release.

**Comment by integrii** [comment]
In the mean time between now and release, is there a recommended way to force our json.Marshal output with six points of precision to come out as a decimal and not scientific notation?

**Comment by ianlancetaylor** [comment]
@integrii That is a great question for a forum rather than the issue tracker.  See https://golang.org/wiki/Questions .  Thanks.
