### ISSUE TITLE
x/pkgsite: Link to "change log" leads to https://go.googlesource.com/go

### ISSUE THREAD

**Issue by tschaub** [golang/go#63853]
### What is the URL of the page with the issue?

https://go.dev/doc/devel/release

### What is your user agent?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36

### Screenshot

<img width="1102" alt="image" src="https://github.com/golang/go/assets/41094/dc191456-0551-4e12-9857-bc92be4015e7">

### What did you do?

I clicked the "change log" link (https://go.dev/change).

### What did you expect to see?

I expected to see a change log with details about the most recent release (1.21.3 on https://go.dev/dl/ currently).  Or maybe I expected to see a list of links to change logs for each release.

### What did you see instead?

I got redirected to https://go.googlesource.com/go.  I couldn't find any reference to "change log" on that site.

**Comment by rittneje** [comment]
Contrary to what "change log" means in other projects (basically a collection of release notes), here it is simply referring to the commit history. See #44068.
