### ISSUE TITLE
ERROR - factory instantiation: you passed an empty SDK key, SDK key must be a non-empty string

### ISSUE THREAD

**Issue by NehamaS** [golang/go#63856]
I have installed go 1.21.3 version on mac os

I have some issue with github.com/splitio/go-client/v6/splitio/client module

when I build the project I get this Error: GOROOT=/opt/homebrew/Cellar/go/1.21.3/libexec #gosetup GOPATH=/Users/nehamastefanski/go #gosetup /opt/homebrew/Cellar/go/1.21.3/libexec/bin/go build -o /private/var/folders/nm/z_4x4k1162n_f1tbpkfhxvvm0000gq/T/GoLand/___go_build_gitlab_com_ct_dev_cq_iam_cmd gitlab.com/ct-dev/cq-iam/cmd #gosetup /private/var/folders/nm/z_4x4k1162n_f1tbpkfhxvvm0000gq/T/GoLand/___go_build_gitlab_com_ct_dev_cq_iam_cmd ERROR - 2023/10/31 23:43:23 factory instantiation: you passed an empty SDK key, SDK key must be a non-empty string SDK init error: factory instantiation: you passed an empty SDK key, SDK key must be a non-empty string

Process finished with the exit code 0

what can be the issue?

**Comment by mauri870** [comment]
That sounds like an error with the library you are using and not related to Go itself.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to [https://github.com/golang/go/wiki/Questions](https://github.com/golang/go/wiki/Questions)
