### ISSUE TITLE
affected/package: 

### ISSUE THREAD

**Issue by 3481554467** [golang/go#63868]
### What version of Go are you using (`go version`)?

go1.21.3

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

ubuntu 22.04lts amd64

### What did you do?

how to match the goproxy int goland and root with user?now i must use go env -w GOPROXY=.. everytime in root terminal,which doc should i wtite ?

### What did you expect to see?

which doc should i wtite ?so that i will not use go env -w GOPROXY=.. everytime

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
