### ISSUE TITLE
cmd/vet: do not report variable capture for loop variables with the new lifetime rules

### ISSUE THREAD

**Issue by timothy-king** [golang/go#63888]
This issue tracks support in x/tools/go/analysis/passes/loopclosure for the new loop variable lifetime rules of https://go.dev/issue/60078, available now behind GOEXPERIMENT=loopvar and likely on for language versions >= 1.22.

Marking as a release blocker as this will make cmd/vet would report a large number of false positives due to the new language feature.

**Comment by timothy-king** [comment]
Example of a false positive https://go.dev/play/p/WsTuyNr6YnK
```
package main

import (
	"fmt"
	"sync"
)

func main() {
	const N = 4
	var wg sync.WaitGroup
	for i := 0; i < N; i++ {
		wg.Add(1)
		go func() { defer wg.Done(); fmt.Println(i) }()
	}
	wg.Wait()
}
```
Playground output for Go 1.21:
```
./prog.go:13:44: loop variable i captured by func literal

Go vet failed.

4
4
4
4

Program exited.
```

Playground output for Go dev branch:
```
# [play]
./prog.go:13:44: loop variable i captured by func literal

Go vet failed.

3
2
0
1

Program exited.
```
The dev currently branch implements the https://go.dev/issue/60078 loop lifetimes. So go vet should not continue to report on this example after 1.22.

**Comment by timothy-king** [comment]
Note this will need to support packages with a mixture of lifetimes in different files or files without `//go:` version declared in the files (like the playground example). See #62605 for a potential solution via go/types.

**Comment by timothy-king** [comment]
Fixed by https://go.dev/cl/c/go/+/543975

**Comment by alexaandru** [comment]
I still see this issue with 1.22.0:

```
$ go version    
go version go1.22.0 linux/amd64

$ grep go go.mod              
go 1.22.0

$ cat main.go
package main

func main() {
	for i := range 10 {
		go func() { println(i) }()
	}
}

$ go vet main.go
./main.go:5:23: loop variable i captured by func literal
```

**Comment by timothy-king** [comment]
@alexaandru Thank you for the report. I opened #65612. Looks like a plumbing issue when running vet on files listed on the command line. You can either invoke vet differently, suppress the finding (add `_ = i` at the end of the loop) or follow along on the new bug for a fix. If you have any more questions please ask them on #65612.
