### ISSUE TITLE
access: "go-editors" for rhysh

### ISSUE THREAD

**Issue by rhysh** [golang/go#63887]
Per https://go.dev/wiki/GithubAccess , I'm requesting membership to the https://github.com/orgs/golang/teams/go-editors group for myself, @rhysh.

My main goal is to be able to close, reopen, retitle etc issues near the areas where I work. Thanks!

CC @golang/release

**Comment by heschi** [comment]
Approved! As mentioned in the wiki, please do not edit any field you're not confident about. Feel free to ask for second opinions.
