### ISSUE TITLE
affected/package: Compiling type switch on sealed interfaces without final return statement.

### ISSUE THREAD

**Issue by jeschkies** [golang/go#63898]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.21
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What did you do?

It's debatable whether this is a bug or an improvement. See https://go.dev/play/p/ccGEo7BOewU.

### What did you expect to see?

When a type switch on a sealed interface is exhaustive and each case includes a return statement the compile should not failed because of a missing return at the end.

### What did you see instead?

The compiler fails with `missing return`.

**Comment by seankhliao** [comment]
This is working as intended according to spec, see point 6 of https://go.dev/ref/spec#Terminating_statements

**Comment by jeschkies** [comment]
@seankhliao but can't the spec be changed? I mean this would be an improvement IMHO.

**Comment by randall77** [comment]
There's a strong bias to keep the terminating statement rule simple. There's lots of cases we could handle if we wanted to, like
```
func f(b bool) int {
    switch b {
    case true: return 0
    case false: return 1
    }
```
But each case adds complexity to the spec, and we decided there just wasn't a lot of benefit to justify that complexity.

**Comment by jeschkies** [comment]
Thanks for the feedback. That makes sense to me.
