### ISSUE TITLE
cmd/vet: don't report "loop variable captured" error for versions >= go1.22

### ISSUE THREAD

**Issue by griesemer** [golang/go#63891]
The new loop variable semantics (#60078) is enabled for go1.22 so `go vet` shouldn't report an error for captured loop variables anymore.

The [playground at tip](https://go.dev/play/p/EPKynQJqoPU?v=gotip) shows the new loop variable semantics but still reports a vet error.

Related to #57063.

**Comment by griesemer** [comment]
Tentatively marking this as a release blocker.

**Comment by griesemer** [comment]
cc @timothy-king

**Comment by timothy-king** [comment]
Duplicate of #63888 ?

**Comment by griesemer** [comment]
Indeed! (I'm 6h behind despite being in the same time zone... :-)
Thanks for opening that other issue.
Closed as duplicate of #63888.
