### ISSUE TITLE
"golang.org/x/sys" no longer includes the required "golang.org/x/sys/windows" on the windows operating system

### ISSUE THREAD

**Issue by StephanVerbeeck** [golang/go#63902]
### What version of Go are you using (`go version`)?

<pre>
go version go1.21.3 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
<pre>
yes
</pre>

### What operating system and processor architecture are you using (`go env`)?
<pre>
windows 11
</pre>

### What did you do?

use windows API functions
compilation error occurs in source "advapi32.go" of module "github.com/lxn/win".

### What did you expect to see?
compiles OK

### What did you see instead?
compiler automatically adds an import for the package "golang.org/x/sys/windows" but DOES NOT INSTALL this package.
In earlier versions of GO this did work and packages that were specific for the windows operating system were installed correctly.
Motivation = this did work before and now doesn't work anymore (existing code that has compiled for 3 years now is not compiling anymore).

**Comment by seankhliao** [comment]
please fill out the report form properly and provide a reproducer

**Comment by raghvenders** [comment]
go build works

**Comment by raghvenders** [comment]
@StephanVerbeeck as @seankhliao mentioned Please fill out form. But when I tried high level both below commands worked.

- go install github.com/lxn/win
- go build or go mod tidy is good too.

**Comment by StephanVerbeeck** [comment]
Wait a bit, why would you "go install" a module, install is for executables, "go get" is for modules.
I see, you did not try this at all (because what you say doesn't work and isn't true).
Please don't ask for more information as what I have provided is sufficient to reproduce the problem and there is not added value in describing a more complex setup (my project) than is needed to reproduce the problem.

What you told generates this error "go: 'go install' requires a version when current directory is not in a module
        Try 'go install github.com/lxn/win@latest' to install the latest version"

**Comment by seankhliao** [comment]
Without more information, we don't think this is an error in `go`, rather how you're using it.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
