### ISSUE TITLE
access: approvers for drakkan

### ISSUE THREAD

**Issue by rolandshoemaker** [golang/go#63907]
@drakkan (gerrit user nicola.murino@gmail.com) has been consistently working on x/crypto/ssh changes and has proven themselves to be an active and valuable contributor. I believe they should be added to the approvers group, especially since they are a de facto owner of the x/crypto/ssh package at this point.

cc @golang/release

**Comment by heschi** [comment]
Hi Nicola,

Thanks for your contributions to the ssh package! I've discussed this request with the team, and we agreed to grant you access. I've added you to the approvers group.

Please be familiar with the rules for voting and submitting changes as described at https://golang.org/wiki/GerritAccess#approver-access-approvers. If you're unsure or have any questions, please don't hesitate to ask us.

Additionally, as described at https://golang.org/wiki/GerritAccess#trybot-access-may-start-trybots, please be sure to at least skim CLs before starting a trybot run.

Thank you again for contributing, your help is greatly appreciated!

**Comment by drakkan** [comment]
Thank you!
