### ISSUE TITLE
slices: Insert function does not panic if i is out of range and there are no values to insert

### ISSUE THREAD

**Issue by gazerro** [golang/go#63913]
The `slices.Insert` function should panic if `i` is out of range, but it does not panic if there are no values to insert:

```go
s := []string{"a", "b", "c"}
s = slices.Insert(s, -1) // does not panic
s = slices.Insert(s, 5) // does not panic
fmt.Println(s)
```

**Comment by bcmills** [comment]
The [documentation](https://pkg.go.dev/slices#Insert) does indeed claim that it will panic:
“Insert panics if i is out of range.”

**Comment by eliben** [comment]
Interesting edge case. I looked back at the original implementation of `slices.Insert` when it was just moved into the stdlib, and that one panics for the test cases specified here. However, following the optimizations in https://go-review.googlesource.com/c/go/+/494817 it no longer panics for these cases. @randall77 @cuonglm WDYT?

**Comment by randall77** [comment]
Making it panic in these cases is fine.
