### ISSUE TITLE
access: go-assignees and go-editors

### ISSUE THREAD

**Issue by mateusz834** [golang/go#63916]
Hi,
I would like to request the go-assignees and go-editors access for me (@mateusz834) as per https://github.com/golang/go/wiki/GithubAccess 

https://github.com/orgs/golang/teams/go-assignees
https://github.com/orgs/golang/teams/go-editors

I would like to help you all with simple gardening tasks. I am often aware of issue duplicates and i am just missing the power to close some issues or retitle them.

gerrit: [mpoliwczak34@gmail.com](https://go-review.googlesource.com/q/author:mpoliwczak34@gmail.com)
github: @mateusz834

Thanks

**Comment by seankhliao** [comment]
cc @golang/release

**Comment by heschi** [comment]
Approved! As mentioned in the wiki, please do not edit any field you're not confident about. Feel free to ask for second opinions.
