### ISSUE TITLE
net/http/cgi: PATH_INFO should be empty or start with a slash

### ISSUE THREAD

**Issue by aimuz** [golang/go#63925]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What did you do?

As described at https://datatracker.ietf.org/doc/html/rfc3875#section-3.3 and https://datatracker.ietf.org/doc/html/rfc3875#section-4.1.5, 

seems to require that PATH_INFO either is empty or begins with a slash, which would imply that the SCRIPT_NAME variable for this case must not end with a slash.

https://go-review.googlesource.com/c/go/+/538861/comment/d24b7001_5770e9f5/

**Comment by bcmills** [comment]
(CC @neild @bradfitz)
