### ISSUE TITLE
x/tools/gopls: panic in FillStruct with invalid fields

### ISSUE THREAD

**Issue by findleyr** [golang/go#63921]
Filling `S{}` panics here:

```
type S struct {
  F int
  E
}

func_() {
  S{}
}
```

...due to `S` having invalid fields. Add tests and fix.

**Comment by Oguidan** [comment]
The problem is with "E" bro

**Comment by findleyr** [comment]
@Oguidan yes, `E` is not defined. The problem is that gopls panics. `gopls` should not panic, even when the code being edited is invalid.

**Comment by Oguidan** [comment]
@findleyr, a malicious file can be a file trying to gain unauthorized access to your computer system. This means a harmless file can be considered a malicious file by an antivirus. Or similarities in code or behavior between legitimate and malicious software. Also, don't forget that we are dealing with blockchain here. Programs can try to gain unauthorized access to your computer system.

**Comment by Oguidan** [comment]
Surely, there is an update that caused this.

**Comment by findleyr** [comment]
@Oguidan I'm really not following. This is a bug in gopls, an LSP server for Go, causing it to panic when the "fill struct" code action is invoked on a particular kind of invalid struct. The bug is that certain operations do not handle `types.Typ[types.Invalid]`, and the fix should be straightforward. This bug has existed forever. I filed this issue to make sure we fix this in the next release.

**Comment by Oguidan** [comment]
But @findleyr , you know that Golang is garbage collector!
