### ISSUE TITLE
x/tools/gopls: Unable to configure Local golang development - go1.22 because go.work is configured as go1.22 but global go is go1.21.3

### ISSUE THREAD

**Issue by raghvenders** [golang/go#63922]
### gopls version

gopls@v0.13.2

### go env

Failed to run 'C:\Users\R\golang\go\bin\go.exe env' (cwd: C:\Users\R\golang): Error: Command failed: C:\Users\R\golang\go\bin\go.exe env -json GOPATH GOROOT GOPROXY GOBIN GOMODCACHE
go: downloading go1.22 (windows/amd64)
go: download go1.22 for windows/amd64: toolchain not available

go: downloading go1.22 (windows/amd64)
go: download go1.22 for windows/amd64: toolchain not available

### What did you do?

- I have set up local go lang/go development go1.22 with go.work as go1.22
- I have not set PATH for bin/go1.22 
- When I open the editor, it is not giving option to configure local go development(go1.22) - Choose go environment is not available.
- And none of the go commands are working, go version or go env  until I get out of the go.work folder, which is configured as 1.22

### What did you expect to see?

- Atleast an option for development editor with the help of gopls to configure local ./bin/go1.22

- Instead of below error, which is correct 
> go: download go1.22 for windows/amd64: toolchain not available

but can be more actionable like

 > go: download go1.22 for windows/amd64: toolchain not available as configured in module or workspace. However you have go1.21.3, make that as your toolchain (lower version) or set PATH for go1.22

_However I cannot set lower version as my development of 1.22_

### What did you see instead?

- go: download go1.22 for windows/amd64: toolchain not available
- Failed to run 'C:\Users\R\golang\go\bin\go.exe env' (cwd: C:\Users\R\golang): Error: Command failed: C:\Users\R\golang\go\bin\go.exe env -json GOPATH GOROOT GOPROXY GOBIN GOMODCACHE

**Comment by hyangah** [comment]
@raghvenders There are many different ways, but I think the easiest is to configure your `PATH` to include the directory where the `go1.22` binary exists. Then, when gopls invokes `go` for the project that specifies `go 1.22`, the `go` command will search the PATH and switch to `go1.22` binary underneath.

```
~/godemo$ cat go.mod
module example.com/m

go 1.99999
~/godemo$ ls ./bin
go1.99999
~/godemo$ PATH=$(pwd)/bin:$PATH go version
go1.99999
~/godemo$ cat ./bin/go1.99999
#!/bin/bash

echo "go1.99999"
```

**Comment by findleyr** [comment]
I don't think this is actionable from gopls perspective.

The toolchain must be set to 1.22.0, or the global go must be >= 1.22.
