### ISSUE TITLE
cmd/go: provide an option to print toolchain switch

### ISSUE THREAD

**Issue by hyangah** [golang/go#63939]
Sometimes we want to trace how and where `go` picks up the target toolchain.
(is it from module cache? or is it from one of my PATH that may have a symlink?)
Either a debug environment variable or a flag (`-x` or `-v`) to enable tool switch activity logging can be helpful.

**Comment by heschi** [comment]
cc @bcmills @matloob

**Comment by bcmills** [comment]
I think the existing `-x` flag is the right fit — it should emit a comment when we switch toolchains.

**Comment by raghvenders** [comment]
@bcmills , @hyangah  - I would like to work on this feature change.

Currently I did a small local setup on this go.mod file. Which are those go commands we can show the information about switch.

```

module change-tc

go 1.21.1

toolchain go1.21.4

```
 by local go env modifies as below

```

set GOROOT=C:\Users\R\go\pkg\mod\golang.org\toolchain@v0.0.1-go1.21.4.windows-amd64
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Users\R\go\pkg\mod\golang.org\toolchain@v0.0.1-go1.21.4.windows-amd64\pkg\tool\windows_amd64

```

Note :  Current relevant go [...] -x shows the updated toolchain location.

**Comment by raghvenders** [comment]
Are we refering situations mentioned - https://go.dev/doc/toolchain - Go toolchain switches, especially after it has been been switched , not during second and subsequent.

**Comment by raghvenders** [comment]
Can we fix this issue - cmd/go: go env GOMOD tries to download newer toolchain #61455 along with this. It has to make an appropriate switch here?

**Comment by raghvenders** [comment]
I did try to address for "toolchain not available" issue and switching to go version executing this command or local available go in PATH.
Please let me know if I can raise a CL for this. 

```

C:\Users\R\golang\analyse-bugs>cat go.mod
module example.com/analyze-bugs

go 1.23

C:\Users\R\golang\analyse-bugs>"C:\Program Files\Go\bin\go" run .
go: downloading go1.23 (windows/amd64)
go: download go1.23 for windows/amd64: toolchain not available

C:\Users\R\golang\analyse-bugs>go run .
go: downloading go1.23 (windows/amd64)
go: download go1.23 for windows/amd64: toolchain not available
Switching to your local go version executing this command: devel go1.22-5f08b44799 Mon Nov 13 14:11:13 2023 +0000 windows/amd64
Swithing Go line in go.mod file to : go 1.22 ------ go.mod ------
module example.com/analyze-bugs

go 1.22
====================
Go.mod file is switched to go 1.22 . Kindly re-execute the relevant commands
C:\Users\R\golang\analyse-bugs>go run .
Hello World

```

**Comment by raghvenders** [comment]
sure I will send a separate CL for this one.

**Comment by raghvenders** [comment]
@bcmills @hyangah - here is the CL for this - https://go-review.googlesource.com/c/go/+/548437

I have few questions currently toolchain switch is called at the very base of pretty every go command.

> It must be called early in startup - See https://go.dev/doc/toolchain#select - 

1. If we use x where it is not a valid flag, it shows x is not valid flag but will show the toolchain switch message , for example : go help mod -x. Technically toolchain switch currently happens for all commands if needed and then execute the command as subprocess or syscall.exec.

Kindly suggest.

**Comment by samthanawalla** [comment]
@matloob @rsc and I discussed this today.

Requires more thought about the right way to implement this. It's a non-trivial change.
Pushed the milestone to 1.24 because we want to get it right.

Abandoned my CL since we shouldn't parse the -x flag before toolchain switching.

**Comment by rsc** [comment]
Probably GODEBUG=toolchaintrace=1 to get toolchain switch tracing.
