### ISSUE TITLE
x/pkgsite: package removal request for github.com/tiagomelo/clipboard

### ISSUE THREAD

**Issue by tiagomelo** [golang/go#63946]
### What is the path of the package that you would like to have removed?
github.com/tiagomelo/clipboard

### Are you the owner of this package?

Yes.

### What is the reason that you could not retract this package instead?

Tried to retract; didn't work. I'll revamp the whole project structure, delete the original repo and start from scratch again with a clean state.

**Comment by suzmue** [comment]
Package has been removed!
