### ISSUE TITLE
x/tools/godoc: Second level package documentation broken

### ISSUE THREAD

**Issue by achenet** [golang/go#63950]
### What version of Go are you using (`go version`)?

<pre>
go version go1.21.1 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
Unsure

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/utilisateur/.cache/go-build'
GOENV='/home/utilisateur/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/utilisateur/go/bin/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/utilisateur/go/bin'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.1'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build448943707=/tmp/go-build -gno-record-gcc-switches'

</pre></details>

### What did you do?

I fired up godoc with `godoc -http=":6060" &`, and tried to access the page for `net/http`. I also tried `net`, `os` and `encoding/json`.

### What did you expect to see?
I expected the pages for `net/http` and `encoding/json` to function normally.

### What did you see instead?
` /src/encoding/json/encode.go:963:18: expected '(', found '[' `
` found packages http (alpn_test.go) and main (triv.go) in /src/net/http `
`os`,`net` and `encoding` all worked normally.

**Comment by seankhliao** [comment]
see also #59056

**Comment by heschi** [comment]
cc @alandonovan @findleyr, I guess?

**Comment by findleyr** [comment]
@achenet per https://github.com/golang/go/issues/59056, we're working on getting [x/pkgsite/cmd/pkgsite](https://pkg.go.dev/golang.org/x/pkgsite/cmd/pkgsite) up to the point where we can delete godoc.

Is there a reason you can use cmd/pkgsite?

**Comment by achenet** [comment]
hi, thanks for the replies.
I didn't know about pkgsite, thanks for letting me know, I'll give it a go
:)

-Ariel

**Comment by go101** [comment]
Another alternative is [Golds](https://go101.org/apps-and-libs/golds.html).
