### ISSUE TITLE
x/sys: v0.14.0 removes definition of BPF_F_KPROBE_MULTI_RETURN in unix/zerrors_linux.go

### ISSUE THREAD

**Issue by brycekahle** [golang/go#63969]
### What version of Go are you using (`go version`)?

`go version go1.20.10 linux/arm64`

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="arm64"
GOBIN=""
GOCACHE="/home/vagrant/.cache/go-build"
GOENV="/home/vagrant/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/vagrant/go/pkg/mod"
GONOPROXY="github.com/DataDog"
GONOSUMDB="github.com/DataDog"
GOOS="linux"
GOPATH="/home/vagrant/go"
GOPRIVATE="github.com/DataDog"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/vagrant/.gimme/versions/go1.20.10.linux.arm64"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/vagrant/.gimme/versions/go1.20.10.linux.arm64/pkg/tool/linux_arm64"
GOVCS=""
GOVERSION="go1.20.10"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
GOWORK=""
CGO_CFLAGS="-I/git/datadog-agent/dev/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-L/git/datadog-agent/dev/lib"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1187157903=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Updated `golang.org/x/sys` dependency to `v0.14.0`

### What did you expect to see?

Continued definition of `BPF_F_KPROBE_MULTI_RETURN`

### What did you see instead?

`Error: /home/runner/go/pkg/mod/github.com/cilium/ebpf@v0.12.2/internal/unix/types_linux.go:41:36: undefined: linux.BPF_F_KPROBE_MULTI_RETURN`

This [commit](https://github.com/golang/sys/commit/1168e2596da3c107050a45359d2a33b6ff4b5bc6#diff-c5a31fa49f385decaee6af20c180aa8ba237891920254e621e69e5e78655b1f1L486) removed the definition. This is likely because it was changed from a `#define` to an `enum` in https://github.com/torvalds/linux/commit/c5487f8d91868eeab17a59cf4d164ea113f90252

**Comment by bcmills** [comment]
(attn @tklauser)
