### ISSUE TITLE
x/crypto/ssh: should ParseAuthorizedKey return PublicKey?

### ISSUE THREAD

**Issue by fsouza** [golang/go#6396]
<pre>Today, ParseAuthorizedKey returns an interface{}, but in order to use the returned key
in MarshalAuthorizedKey, one needs to convert it to a PublicKey:

key, comment, _, _, ok := ssh.ParseAuthorizedKey([]byte(content))
if !ok {
    panic(&quot;Invalid key&quot;)
}
marshaled := ssh.MarshalAuthorizedKey(key.(ssh.PublicKey))

Is there a case where ParseAuthorizedKey returns a value that doesn't implement
PublicKey?</pre>

**Comment by hanwen** [comment]
@rsc , @bradfitz - this has been fixed eons ago. How to close this issue?
