### ISSUE TITLE
cmd/compile:  variables that only survive within the function escape to the heap

### ISSUE THREAD

**Issue by qiulaidongfeng** [golang/go#63964]
### What version of Go are you using (`go version`)?

<pre>
$ go version
tip
</pre>

### Does this issue reproduce with the latest release?
yes.

### What operating system and processor architecture are you using (`go env`)?

Can be reproduced in https://go.dev/play

### What did you do?
This is the minimum copy code I have written.

https://go.dev/play/p/CMcVGAsizeN?v=gotip

### What did you expect to see?

I want to see variables that only survive in function memory being allocated to the stack.

### What did you see instead?
I see variables that only survive in function memory being allocated to the heap.

**Comment by mateusz834** [comment]
This might be related to #16241.

**Comment by mauri870** [comment]
By removing the mutex it still escapes `once` to the heap. I believe it is the internal call to (sync.Once).Do that makes it escape, because of the atomic ops

Shorter example: https://go.dev/play/p/RFXBKkEFrfO

```bash
go build -gcflags=-m=2 main.go
# command-line-arguments
./main.go:12:6: cannot inline escapes: function too complex: cost 87 exceeds budget 80
./main.go:13:12: can inline escapes.func1 with cost 4 as: func() { p.b = true }
./main.go:13:11: inlining call to sync.(*Once).Do
./main.go:13:11: inlining call to atomic.(*Uint32).Load
./main.go:18:6: can inline doesntescape with cost 4 as: func(*V) { p.b = true }
./main.go:22:6: can inline main with cost 73 as: func() { vv = <nil>; escapes(&vv); doesntescape(&vv) }
./main.go:25:14: inlining call to doesntescape
./main.go:12:14: escapes capturing by value: p (addr=false assign=false width=8)
./main.go:12:14: parameter p leaks to {heap} with derefs=0:
./main.go:12:14:   flow: sync.o = p:
./main.go:12:14:     from p.once (dot of pointer) at ./main.go:13:3
./main.go:12:14:     from p.once (address-of) at ./main.go:13:8
./main.go:12:14:     from sync.o, sync.f := p.once, func literal (assign-pair) at ./main.go:13:11
./main.go:12:14:   flow: {heap} = sync.o:
./main.go:12:14:     from (*sync.Once).doSlow(sync.o, sync.f) (call parameter) at ./main.go:13:11
./main.go:12:14: leaking param: p
./main.go:13:12: func literal does not escape
./main.go:18:19: p does not escape
./main.go:23:6: vv escapes to heap:
./main.go:23:6:   flow: {heap} = &vv:
./main.go:23:6:     from &vv (address-of) at ./main.go:24:10
./main.go:23:6:     from escapes(&vv) (call parameter) at ./main.go:24:9
./main.go:23:6: moved to heap: vv
```

**Comment by heschi** [comment]
cc @golang/compiler

**Comment by mauri870** [comment]
This seems to be the same as https://github.com/golang/go/issues/57910, I just tested the fix proposed at [CL462299](https://go-review.googlesource.com/c/go/+/462299) and it seems to prevents it from escaping.

**Comment by mdempsky** [comment]
> This seems to be the same as https://github.com/golang/go/issues/57910

Thanks for finding that! I agree, it looks like the same issue. Closing this one as a duplicate.
