### ISSUE TITLE
x/pkgsite: Request to provide offline html version of the documentation for downloading

### ISSUE THREAD

**Issue by viocha** [golang/go#63975]
### What did you expect to see?

I would like to save the documentation as html files for offline browsing like what I can do in Java and Python website.

**Comment by mauri870** [comment]
Could you link to the Java/Python docs that allow downloading? Thanks

Additionally, using the browser option to save as pdf wouldn't suffice?

**Comment by mauri870** [comment]
Just to be clear, it is possible to use godoc to view documentation without internet and that is something that pkgsite does not support, see https://github.com/golang/go/issues/59056

**Comment by viocha** [comment]
> Could you link to the Java/Python docs that allow downloading? Thanks
> 
> Additionally, using the browser option to save as pdf wouldn't suffice?

The relevant links are as follows.
https://www.oracle.com/java/technologies/javase-jdk17-doc-downloads.html
https://docs.python.org/3/download.html

These are very convenient for referring to the documents offline.
![Snipaste_2023-11-08_10-08-38](https://github.com/golang/go/assets/66580331/89c6de73-7812-4307-b6cb-a5bd5f552c29)
![Snipaste_2023-11-08_10-07-19](https://github.com/golang/go/assets/66580331/0bd5e408-a5da-43df-a55e-69c076126592)

**Comment by viocha** [comment]
And Dart, another language of Google, supports downloading of documentation. This is the related link:
https://dart.dev/get-dart/archive
![dart-docs-download](https://github.com/golang/go/assets/66580331/1056d7f8-e48b-4cdf-a040-9de41983aac9)

**Comment by ianthehat** [comment]
As mentioned in the bug linked to above, there is a version of pkgsite for local viewing
`go install golang.org/x/pkgsite/cmd/pkgsite@latest`
Can you say why that is not sufficent?

**Comment by viocha** [comment]
> As mentioned in the bug linked to above, there is a version of pkgsite for local viewing Can you say why that is not sufficent?`go install golang.org/x/pkgsite/cmd/pkgsite@latest`

Its disadvantage is that you have to manually start a service every time you open the reference documentation. If it's a static HTML file, there's no need for deployment, and you can browse it directly by clicking to open it. You can download the html files from the link above and try it, if you cannot understand.

**Comment by 3052** [comment]
> As mentioned in the bug linked to above, there is a version of pkgsite for local viewing `go install golang.org/x/pkgsite/cmd/pkgsite@latest` Can you say why that is not sufficent?

because that makes it extremely difficult if you want to actually host your own docs. if the tool is able to just dump a folder of HTML files, then you can simply upload that folder to some web storage, such as GitHub Pages. but with the current solution, you would be required to purchase a VPS or similar in order to run the server in  the cloud. its just a pointlessly complex solution to what is a simple problem.

**Comment by 3052** [comment]
you can generate with Doc2Go:

https://github.com/abhinav/doc2go

it also supports generating different versions of a module

**Comment by 3052** [comment]
https://github.com/golang/go/issues/2381

**Comment by viocha** [comment]
> you can generate with Doc2Go:
> 
> [abhinav/doc2go](https://github.com/abhinav/doc2go)
> 
> it also supports generating different versions of a module

Thank you. It's the best solution.

**Comment by 3052** [comment]
https://github.com/golang/go/issues/65194
