### ISSUE TITLE
github: use forms for issue templates

### ISSUE THREAD

**Issue by Nasfame** [golang/go#63970]
-  [ ] Migrate from markdown templates to more user friendly .yml templates.

Relates #63655 
Demo: https://github.com/golangFame/go/issues/new/choose

**Comment by heschi** [comment]
This looks great, or at least it did yesterday -- it seems like the changes may have been lost from the demo. Please feel free to send a CL.

One detail -- sometimes we need to file an issue that doesn't fit well into any of the templates. Today, we can just clear out the template. Is there an escape hatch if everything's a template? Perhaps we should have an "Other" option?

**Comment by Nasfame** [comment]
@heschi since its a fork, i have a cron job to sync it up. I will lock the demo.  My bad !!! The cl has been raised a while ago: #63655

**Comment by heschi** [comment]
Thanks! I left some comments on the CL now that I realize it exists, we can continue the discussion there.
