### ISSUE TITLE
cmd/compile: compile error while using generics

### ISSUE THREAD

**Issue by qqxhb** [golang/go#63981]
### What version of Go are you using (`go version`)?

<pre>
$ 1.20.10

</pre>

### Does this issue reproduce with the latest release?
no

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ GO111MODULE="on"
GOARCH="amd64"
GOBIN=""

GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""

GOOS="darwin"

GOSUMDB="sum.golang.google.cn"
GOTMPDIR=""
GOVCS=""
GOVERSION="go1.20.10"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/qg/7jl0rh4502v1w663txn71wnm0000gp/T/go-build2599608933=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
Implement generic interfaces

```go

type DO struct {
}

func (d *DO) Delete(models ...interface{}) (info interface, err error) {
	return nil, nil
}

type IGenericsDo[T IGenericsDo[T, E], E any] interface {
	Delete(...E) (info interface, err error)
}

func NewGenericsDo[T IGenericsDo[T, E], E any](realDo T) IGenericsDo[T, E] {
	return &genericsDo[T, E]{realDo: realDo}
}

type genericsDo[T IGenericsDo[T, E], E any] struct {
	realDo T
	DO
}

func (b *genericsDo[T, E]) Delete(models ...E) (result interface, err error) {
	return b.realDo.Delete(models...)
}

```
compile err: `Cannot use '&genericsDo[T, E]{realDo: realDo}' (type *genericsDo[T, E]) as the type IGenericsDo[T, E] Type does not implement 'IGenericsDo[T, E]' need the method: Delete(...E) (info interface{}, err error) have the method: Delete(models ...interface{}) (info interface{}, err error)`

### What did you see instead?

When I remove the inherited DO, it work.
```go

type IGenericsDo[T IGenericsDo[T, E], E any] interface {
	Delete(...E) (info interface, err error)
}

func NewGenericsDo[T IGenericsDo[T, E], E any](realDo T) IGenericsDo[T, E] {
	return &genericsDo[T, E]{realDo: realDo}
}

type genericsDo[T IGenericsDo[T, E], E any] struct {
	realDo T
	//DO
}

func (b *genericsDo[T, E]) Delete(models ...E) (result interface, err error) {
	return b.realDo.Delete(models...)
}

```

**Comment by Jorropo** [comment]
Are you using gccgo ?
With dc74a3dd4f30c4a3df235aac8a9e84575767ba69 `1.21` and `1.20.10` I get:
```
./prog.go:12:6: invalid recursive type: IGenericsDo refers to itself
./prog.go:26:18: b.realDo.Delete undefined (type T has no field or method Delete)
```
Which looks correct to me.

**Comment by heschi** [comment]
cc @golang/compiler

**Comment by griesemer** [comment]
1) I assume you meant `(info interface{}, err error)` in the signature of `Do.Delete`? As written, `(info interface, err error)` is not valid syntax.

2) After fixing the syntax, I agree with @Jorropo . This program is not correct.

I am going to close this. If you believe this is a mistake and there's a real issue here, please re-open with a small, syntactically correct reproducer. Thanks.

As an aside, gccgo's generics implementation is not sufficiently far along yet I believe to be useable in general (@ianlancetaylor , please correct me if I am mistaken).
