### ISSUE TITLE
golang.org/x/textaffected/package: 

### ISSUE THREAD

**Issue by prr123** [golang/go#63998]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.21.3
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
ubuntu 22.04
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>
can provide, but seems irrelevant

### What did you do?
downloaded golang.org/x/net/http2

### What did you expect to see?
a complete download

### What did you see instead?

go: found golang.org/x/net/http2 in golang.org/x/net v0.17.0
go: downloading golang.org/x/text v0.13.0
go: client/http/http2simple imports
        golang.org/x/net/http2 imports
        golang.org/x/net/idna imports
        golang.org/x/text/secure/bidirule: golang.org/x/text@v0.13.0: read "https:/proxy.golang.org/@v/v0.13.0.zip": stream error: stream ID 19; INTERNAL_ERROR; received from peer
go: client/http/http2simple imports
        golang.org/x/net/http2 imports
        golang.org/x/net/idna imports
        golang.org/x/text/unicode/bidi: golang.org/x/text@v0.13.0: read "https:/proxy.golang.org/@v/v0.13.0.zip": stream error: stream ID 19; INTERNAL_ERROR; received from peer
go: client/http/http2simple imports
        golang.org/x/net/http2 imports
        golang.org/x/net/idna imports
        golang.org/x/text/unicode/norm: golang.org/x/text@v0.13.0: read "https:/proxy.golang.org/@v/v0.13.0.zip": stream error: stream ID 19; INTERNAL_ERROR; received from peer

**Comment by seankhliao** [comment]
this looks more like a problem with your internet connection rather than something with the go project.

**Comment by prr123** [comment]
Here are some more facts and a proposed solution:
1. I can download the module with curl  http1, but downloading with curl does not execute the other steps (calculating the hash) in the golang build system.
2. I was able to download sith go get to one of my servers
It is very convenient to brush the problem aside by blaming the problem on the internet connection. But the issue is that the problem is connected with http2. 
My proposed solution is to offer an option in the go build system to fall back to http1 if a http2 download fails. That would be solution.
