### ISSUE TITLE
"use of internal package not allowed" error

### ISSUE THREAD

**Issue by wulianglongrd** [golang/go#64005]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.3 darwin/amd64
and
built from the source code master branch
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE='auto'
GOARCH='amd64'
GOBIN=''
GOCACHE='/Users/logx/Library/Caches/go-build'
GOENV='/Users/logx/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/logx/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/logx/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/darwin_amd64'
GOVCS=''
GOVERSION='go1.21.3'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD=''
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/mj/fy4gncls07x2y19k7sj9l0tr0000ks/T/go-build4253779863=/tmp/go-build -gno-record-gcc-switches -fno-common'

</pre></details>

### What did you do?

I'm analyzing the source code, and running its test cases, but getting the "use of internal package ... not allowed" error. Here are the steps to reproduce：

step 1: clone the source code
```code
$ cd ~
$ mkdir devgo && cd devgo
$ git clone https://go.googlesource.com/go
```

step 2: make.bash
```code
$ cd go/src
$ ./make.bash
Building Go cmd/dist using /usr/local/go. (go1.21.3 darwin/amd64)
Building Go toolchain1 using /usr/local/go.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for darwin/amd64.
---
Installed Go for darwin/amd64 in /Users/logx/devgo/go
Installed commands in /Users/logx/devgo/go/bin
*** You need to add /Users/logx/devgo/go/bin to your PATH.
```
So far, everything is fine.

step 3: run test case
```code
$ pwd
/Users/logx/devgo/go/src/crypto/sha1
$ /Users/logx/devgo/go/bin/go test .
package std/crypto/sha1
	sha1.go:13:2: use of internal package crypto/internal/boring not allowed
```
I followed [this documentation](https://go.dev/doc/contribute#quick_test), but when running the test case, I got the above error.

### What did you expect to see?
The test case runs successfully without any errors. Because I didn't make any changes.

### What did you see instead?
Got the error mentioned above.

**Comment by thanm** [comment]
From your `go env` digest it looks as though your GOROOT is still set up to point to `/usr/local/go` and not 
/Users/logx/devgo/go.

Try:

```
$ cd /Users/logx/devgo/go/src/crypto/sha1
$ export PATH="/Users/logx/devgo/go/bin:${PATH}"
$ go test .
```

and see if that helps.

**Comment by randall77** [comment]
Strange. I cannot reproduce.

Try unsetting `GO111MODULE` and `GOTOOLCHAIN` environment variables. Those are the only ones in your list that aren't in mine. (I tried setting mine to your values, but that didn't reproduce for me.)

Could there be an old distribution at your checkout location? Add `rm -fr devgo` to your instruction list.

**Comment by wulianglongrd** [comment]
@thanm thanks, The following is the running result

```
$ cd /Users/logx/devgo/go/src/crypto/sha1
$ export PATH="/Users/logx/devgo/go/bin:${PATH}"
$ go test .
package std/crypto/sha1
	sha1.go:13:2: use of internal package crypto/internal/boring not allowed

$ go env | grep GOPATH
GOPATH='/Users/logx/go'

$ GOPATH=/Users/logx/devgo/go
$ go env | grep GOPATH
GOPATH='/Users/logx/devgo/go'

$ go test .
package std/crypto/sha1
	sha1.go:13:2: use of internal package crypto/internal/boring not allowed
```

**Comment by wulianglongrd** [comment]
@randall77 I deleted multiple times today with the same result. At the same time, I deleted the cache via `go clean -cache`, same thing.

**Comment by wulianglongrd** [comment]
Some more information, if I execute `run.bash`, I get `ALL TESTS PASSED`, but if I execute `make.bash` first, and then `run.bash` I get `go: no such tool "dist"`(printed twice).

```
$ ./make.bash
$ ./run.bash
go: no such tool "dist"
go: no such tool "dist"
```

**Comment by seankhliao** [comment]
what's in `/Users/logx/Library/Application Support/go/env`
and what's the output of `go env` using the `go` you've built?

**Comment by wulianglongrd** [comment]
Thank you everyone. Although I'm still not sure what caused the above problem, I solved it through the following solutions:

1. Uninstall the currently installed go
```
$ rm -rf /usr/local/go
$ rm -rf /etc/paths.d/go

# it was cloned so long ago that I almost forgot about it.
$ rm -rf /Users/logx/go/src/google.golang.org
$ rm -rf /Users/logx/go/src/golang.org
```
Delete GOPATH, GOROOT config.

2. Reinstall go

3. Re-test according to the above steps
