### ISSUE TITLE
internal/zstd: the test may be skipped on macos systems with zstd installed.

### ISSUE THREAD

**Issue by aimuz** [golang/go#64000]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.22-c44cd69a0e Wed Nov 1 21:06:08 2023 +0800 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
irrelevant
</pre></details>

### What did you do?

On my current system I installed zstd via `brew install zstd`.

```
go test -v | grep SKIP                                                
--- SKIP: TestLarge (0.01s)
--- SKIP: TestAlloc (0.00s)
--- SKIP: FuzzDecompressor (0.00s)
--- SKIP: FuzzReverse (0.00s)
--- SKIP: FuzzXXHash (0.00s)
```

The reason for this is that the test cases are always looked for in /usr/bin/zstd, 
whereas brew is installed in the /usr/local/bin/zstd

### What did you expect to see?

Tests are not skipped

### What did you see instead?

```
--- SKIP: TestLarge (0.01s)
--- SKIP: TestAlloc (0.00s)
--- SKIP: FuzzDecompressor (0.00s)
--- SKIP: FuzzReverse (0.00s)
--- SKIP: FuzzXXHash (0.00s)
```

**Comment by bcmills** [comment]
(CC @ianlancetaylor @klauspost)

**Comment by callthingsoff** [comment]
Also found "/usr/bin/xxhsum", should it be modified as well?
