### ISSUE TITLE
cmd/go: TestScript/list_pkgconfig_error failures

### ISSUE THREAD

**Issue by bcmills** [golang/go#64017]
```
#!watchflakes
post <- pkg == "cmd/go" && test == "TestScript/list_pkgconfig_error" && date < "2023-10-20"
```

**Comment by bcmills** [comment]
(Fixed by https://go.dev/cl/536195; just filing an issue for filtering purposes.)

**Comment by cherrymui** [comment]
I think `test` doesn't include subtest. On #64021 it has `test == "TestScript"`. We might be able to update the parser to include include subtest. The JSON logs from LUCI might make it easier.
