### ISSUE TITLE
x/tools/internal/diff: suboptimal line edits for a common prefix

### ISSUE THREAD

**Issue by findleyr** [golang/go#64023]
Noticed in https://go.dev/cl/539656. The x/tools/internal/diff package produces suboptimal line diffs, in that it generates edits inside of common prefixes.

Here is a minimal example: https://go.dev/play/p/kS7ykVOJzbm  

```go
diff.Strings("\n\n", "\n\na\n") // [{Start:0,End:0,New:"\n"} {Start:1,End:1,New:"a"}]
```

While the edits are valid, I think it's a bug that an edit is inserted inside a common prefix. Pragmatically, it causes the unified diff to be rather confusing. It may also cause non-nonsensical movement of the cursor in gopls, but I've yet to demonstrate this in practice.

At the very least, I think this warrants investigation.

CC @pjweinb @adonovan

**Comment by adonovan** [comment]
@pjweinb, since the problem is in the core of the diff algorithm, on which you are the expert (and not in the ToUnified  presentation logic), could you take a look at it? Thanks.

**Comment by pjweinb** [comment]
This is a case where a longest common subsequence doesn't include the
common prefix, and unfortunately the algorithm finds it. I think that it's
not hard to fix.

**Comment by findleyr** [comment]
> This is a case where a longest common subsequence doesn't include the
common prefix, and unfortunately the algorithm finds it.

Understood. I think this is why many diff algorithms do a line-based diff first before narrowing to sub-line diffs: when "a\n" is considered as a single unit, the trailing '\n' can't be considered part of a sequence.

Perhaps the simplest fix is to do the same: start by diffing lines, and then do a second sub-line pass on each hunk. This may also lead to better performance.

**Comment by pjweinb** [comment]
This is perhaps unfortunate, but it is not a bug. The same visibly unfortunate thing can happen without a common prefix: diff(xyAA, yyAABA) has the same problem of not returning a minimal diff and being small enough to be dissatisfying to a human observer.
