### ISSUE TITLE
go mod tidy removes the toolchain directive

### ISSUE THREAD

**Issue by prymitive** [golang/go#64039]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

I'm using latest release.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/lukasz/.cache/go-build'
GOENV='/home/lukasz/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/lukasz/go/pkg/mod'
GONOPROXY='xxx'
GONOSUMDB='xxx'
GOOS='linux'
GOPATH='/home/lukasz/go'
GOPRIVATE='xxx'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/home/lukasz/usr/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/home/lukasz/usr/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.4'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/lukasz/work/pint/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2854113973=/tmp/go-build -gno-record-gcc-switches'

</pre></details>

### What did you do?

I can't reproduce it using an empty repo so there must be something in my go.mod that triggers it.
Here's what happens in my repo:

I have a go.mod with both `go` and `toolchain` directives:

```
$ head go.mod 
module github.com/cloudflare/pint

go 1.21.4

toolchain go1.21.0

require (
	github.com/cespare/xxhash/v2 v2.2.0
	github.com/fatih/color v1.16.0
	github.com/gkampitakis/go-snaps v0.4.11
```

I run `$ go mod tidy -v` and it doesn't output anything to stdout/stderr.

But the `toolchain` directive is now gone:

```
$ head go.mod 
module github.com/cloudflare/pint

go 1.21.4

require (
	github.com/cespare/xxhash/v2 v2.2.0
	github.com/fatih/color v1.16.0
	github.com/gkampitakis/go-snaps v0.4.11
	github.com/google/go-cmp v0.6.0
	github.com/google/go-github/v55 v55.0.0
```

```diff
$ git diff
diff --git a/go.mod b/go.mod
index 60df635..0b6953f 100644
--- a/go.mod
+++ b/go.mod
@@ -2,8 +2,6 @@ module github.com/cloudflare/pint
 
 go 1.21.4
 
-toolchain go1.21.0
-
 require (
        github.com/cespare/xxhash/v2 v2.2.0
        github.com/fatih/color v1.16.0
```

### What did you expect to see?

I've put `toolchain` in place so that my code can be compiled using any 1.21.x release.
I expect `toolchain` to be kept in my go.mod file.

### What did you see instead?

`toolchain` is being removed by `go mod tidy` and it's unclear to me why.
I don't see any mention of `go mod tidy` touching `toolchain` on https://go.dev/ref/mod#go-mod-tidy so it's unexpected.

**Comment by seankhliao** [comment]
This is an invalid configuration, the go directive is a minimum version, the toolchain directive can only allow higher versions, not lower versions.
