### ISSUE TITLE
golang.org/x/text

### ISSUE THREAD

**Issue by prr123** [golang/go#64036]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.21.4
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?
ubuntu 22.04
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>
GO111MODULE='on'
GOARCH='amd64'
GOBIN='/home/peter/go/bin'
GOCACHE='/home/peter/.cache/go-build'
GOENV='/home/peter/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/peter/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/peter/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/lang/go/1.21.4'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/lang/go/1.21.4/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.4'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/peter/go/src/client/http/http2simple/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3021424245=/tmp/go-build -gno-record-gcc-switches'
### What did you do?
I submitted the cli command:  **go get golang.org/x/text**

### What did you expect to see?
a successful download

### What did you see instead?
go: downloading golang.org/x/text v0.14.0
golang.org/x/text@v0.14.0: read "https:/proxy.golang.org/@v/v0.14.0.zip": stream error: stream ID 7; INTERNAL_ERROR; received from peer

**Comment by seankhliao** [comment]
This looks like a problem with your internet connection rather than any problem with the go project itself

**Comment by prr123** [comment]
My internet connection has not shown any issues. All other golang modules
download without hesitation. I can download the mirror of x/text from
github.The module in question is the only endpoint that does not download.
I tried over multiple days.
I reopened an issue with more information. I also updated the go version.
Are you able to download this module? If you are able to, that would be
helpful to know.

I tried twice to download the module with curl and the download stopped
working at exactly the same place.
***@***.***:~/zig/projects/zigDemo/overflow$* curl -O
***@***.***/v0.14.0.zip
***@***.***/v0.14.0.zip>*
  % Total    % Received % Xferd  Average Speed   Time    Time     Time
 Current
                                 Dload  Upload   Total   Spent    Left
 Speed
 70 9018k   70 6399k    0     0  16103      0  0:09:33  0:06:46  0:02:47
30741
curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
***@***.***:~/zig/projects/zigDemo/overflow$ *curl -O
***@***.***/v0.14.0.zip
***@***.***/v0.14.0.zip>*
  % Total    % Received % Xferd  Average Speed   Time    Time     Time
 Current
                                 Dload  Upload   Total   Spent    Left
 Speed
 70 9018k   70 6399k    0     0  16010      0  0:09:36  0:06:49  0:02:47
37276
curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
