### ISSUE TITLE
net/http/httputil: ReverseProxy implicitly requires http.Flusher with streaming

### ISSUE THREAD

**Issue by vhakulinen** [golang/go#64045]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/ville/.cache/go-build'
GOENV='/home/ville/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/ville/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/ville/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/home/ville/.local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/home/ville/.local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.4'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/t
mp/go-build3935927459=/tmp/go-build -gno-record-gcc-switches'

</pre></details>

### What did you do?

`httputil.ReverseProxy` requires that the used `http.ResponseWriter` implements `http.Flush` in order to proxy SSE.

I have a situation where the original response writer is wrapped with the following code in order to record the written status code for logging:
```golang
// StatusRecorder wraps http.ResponseWriter and records the status code
// written to the client.
type StatusRecorder struct {
	http.ResponseWriter
	Status int
}

func NewStatusRecorder(w http.ResponseWriter) *StatusRecorder {
	return &StatusRecorder{
		ResponseWriter: w,
		// Default to 200 OK.
		Status: http.StatusOK,
	}
}

func (rr *StatusRecorder) WriteHeader(status int) {
	rr.Status = status
	rr.ResponseWriter.WriteHeader(status)
}
```

### What did you expect to see?

SSE events landing to the client _or_ mention about the `http.Flush` requirement in the reverse proxy's documentation.

### What did you see instead?

SSE events were lost.

Similar issue: #27816

**Comment by seankhliao** [comment]
I think it's just expected that any implementation of wrapping responsewriters will have an `Unwrap() http.ResponseWriter` method.

**Comment by vhakulinen** [comment]
I have completely missed that. I've only been aware of `Unwrap()` when working with errors.

Is it common practice to implement `Unwrap()` when ever wrapping interfaces, or just these two cases?

**Comment by seankhliao** [comment]
afaik these are the only two the standard library supports atm.

**Comment by seankhliao** [comment]
closing as I don't think this is specific to httputil.ReverseProxy, it would have broken with any other non conforming middleware as well.

**Comment by vhakulinen** [comment]
Okay. Thank you for your help.
