### ISSUE TITLE
x/debug/internal/gocore: allocation headers break viewcore tests

### ISSUE THREAD

**Issue by mknyszek** [golang/go#64049]
```
#!watchflakes
post <- pkg == "golang.org/x/debug" && `TestVersions/goroot`
```

The new allocation headers change modifies how the heap metadata is laid out, which unsurprisingly breaks the x/debug viewcore tests that care about that kind of thing.

Example failure: https://build.golang.org/log/921d95ba40810cde564beec65d12b3714c642e57

**Comment by mknyszek** [comment]
Broken as of https://go.dev/cl/538217.

**Comment by dmitshur** [comment]
@mknyszek There's a release-blocker label here, but it's in Unreleased milestone meaning it's not blocking any release. Did you mean for this to be a blocker for Go 1.22 (RC 1), or something else?

**Comment by mknyszek** [comment]
Deduplicating this with #63359.
