### ISSUE TITLE
x/pkgsite: package removal request for github.com/riverqueue/river_licensetest

### ISSUE THREAD

**Issue by bgentry** [golang/go#64053]
### What is the path of the package that you would like to have removed?

github.com/riverqueue/river_licensetest

### Are you the owner of this package?

Yes

### What is the reason that you could not retract this package instead?

I was just testing something for another project and don't want this to stick around in the docs forever. Already retracted it, just want it deleted.

**Comment by suzmue** [comment]
Package has been removed!
