### ISSUE TITLE
x/exp/cmd/gorelease: unexpected go.sum complaint

### ISSUE THREAD

**Issue by PaulForgey-Discovery** [golang/go#64051]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.10 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

unknown (our organization is using go1.20.latest)

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/paul.forgey/Library/Caches/go-build"
GOENV="/Users/paul.forgey/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/paul.forgey/go/pkg/mod"
GONOPROXY="github.com/wbd-streaming/*"
GONOSUMDB="github.com/wbd-streaming/*"
GOOS="darwin"
GOPATH="/Users/paul.forgey/go"
GOPRIVATE="github.com/wbd-streaming/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/paul.forgey/goroot"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/paul.forgey/goroot/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.10"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/paul.forgey/go/src/github.com/wbd-streaming/wbd-go-common/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9h/m7vdp5bn39n3p28g91swgphw0000gq/T/go-build737174559=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

also reproduces in linux

### What did you do?

<pre>
$ gorelease -version=v1.6.0
</pre>

### What did you expect to see?

normal output

### What did you see instead?

<pre>
# diagnostics
go.sum: one or more sums are missing. Run 'go mod tidy' to add missing sums.
</pre>

There is actually nothing wrong with the go.sum file and re-generating it by deleting and re-running`go mod tidy` produces the same contents.

The package builds just fine.

**Comment by seankhliao** [comment]
what version of gorelease is this, and can you provide a reproducer?

**Comment by PaulForgey-Discovery** [comment]
> what version of gorelease is this, and can you provide a reproducer?

unfortunately, I haven't been able to get a sanitized reproduction outside our production code. This is still reproducing @latest (Nov 10, 2023). Has been since the Sep 5, 2023 release but the problem actually started reproducing when we bumped the version of go in this module from 1.18 to 1.20.

**Comment by PaulForgey-Discovery** [comment]
as a test, I tried installing all tagged versions of gorelease to see if it starts reproducing somewhere, and the behavior is present in all but the first release, which panics.

**Comment by PaulForgey-Discovery** [comment]
no longer reproducing in go1.21, but still does reproduce in go1.20 latest

**Comment by kramvan1** [comment]
reproduced with go 1.22.9 with version v0.0.0-20241009180824-f66d83c29e7c
And yes, go mod tidy, makes no difference.
