### ISSUE TITLE
x/tools/gopls/internal/regtest/marker: TestMarkers/diagnostics/usemodule.txt consistently failing locally

### ISSUE THREAD

**Issue by bcmills** [golang/go#64068]
### What version of Go are you using (`go version`)?

<pre>
$ go1.21.4 version
go version go1.21.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go1.21.4 env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/usr/local/google/home/bcmills/.cache/go-build'
GOENV='/usr/local/google/home/bcmills/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/usr/local/google/home/bcmills/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/usr/local/google/home/bcmills'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/google/home/bcmills/sdk/go1.21.4'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='local'
GOTOOLDIR='/usr/local/google/home/bcmills/sdk/go1.21.4/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.4'
GCCGO='/usr/bin/gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='c++'
CGO_ENABLED='1'
GOMOD='/usr/local/google/home/bcmills/x/tools/gopls/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2798536935=/tmp/go-build -gno-record-gcc-switches'

</pre></details>

### What did you do?

```
~/x/tools/gopls$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

~/x/tools/gopls$ git rev-parse HEAD
aafa2e00a0d72fbc8be1200f3bd75e77e1f54a3a

~/x/tools/gopls$ go1.21.4 test ./internal/regtest/marker/ -run=TestMarkers/diagnostics/usemodule.txt
```

### What did you expect to see?

Test passing.

### What did you see instead?

```
--- FAIL: TestMarkers (0.04s)
    --- FAIL: TestMarkers/diagnostics/usemodule.txt (0.43s)
        marker.go:609: b/main.go:3:26 (diagnostics/usemodule.txt:42:26): no diagnostic at b/main.go:3:8-16 (diagnostics/usemodule.txt:42:8-16) matches "not included in a workspace module"
        marker.go:515: b/main.go:3:8 (diagnostics/usemodule.txt:42:8): unexpected diagnostic: "could not import mod.com/b/lib (cannot find package \"mod.com/b/lib\" in GOROOT or GOPATH)"
FAIL
FAIL    golang.org/x/tools/gopls/internal/regtest/marker        0.598s
FAIL
```

**Comment by bcmills** [comment]
(attn @findleyr)

I do not understand why this same test is not currently failing on the Go dashboard builders, but it fails consistently for me. (It looks like this is somehow running `gopls` in `GOPATH` mode instead of module mode? 🤔)

**Comment by bcmills** [comment]
`git bisect` reports:
```
a13793e315cd37beaa5eead1298821a13c9ca41e is the first bad commit
commit a13793e315cd37beaa5eead1298821a13c9ca41e
Author: Rob Findley <rfindley@google.com>
Date:   Fri May 12 14:22:10 2023 -0400

    gopls/internal/lsp: add quick-fixes to manage the go.work file

    Update OrphanedFileDiagnostics to provide suggested fixes for
    diagnostics related to modules that are not activated by a relevant
    go.work file.

    Also remove the Snapshot.openFiles method, which was completely
    redundant with Snapshot.overlays.

    Fixes golang/go#53880

    Change-Id: I7e7aed97fb0b93415fe3dc383b6daea15241f31b
    Reviewed-on: https://go-review.googlesource.com/c/tools/+/494738
    Reviewed-by: Mouffull <dickmouth8340@gmail.com>
    Reviewed-by: Alan Donovan <adonovan@google.com>
    Run-TryBot: Robert Findley <rfindley@google.com>
    gopls-CI: kokoro <noreply+kokoro@google.com>
    TryBot-Result: Gopher Robot <gobot@golang.org>

 gopls/doc/commands.md                              |  15 +
 gopls/internal/lsp/cache/load.go                   |   2 +-
 gopls/internal/lsp/cache/session.go                |  24 +-
 gopls/internal/lsp/cache/snapshot.go               | 160 ++++++++--
 gopls/internal/lsp/cache/view.go                   |  13 +-
 gopls/internal/lsp/code_action.go                  |  12 +
 gopls/internal/lsp/command.go                      | 159 ++++++++--
 gopls/internal/lsp/command/command_gen.go          |  20 ++
 gopls/internal/lsp/command/interface.go            |  10 +
 gopls/internal/lsp/diagnostics.go                  |  10 +-
 gopls/internal/lsp/lsp_test.go                     |   2 +-
 gopls/internal/lsp/regtest/marker.go               |   2 +-
 gopls/internal/lsp/source/api_json.go              |   6 +
 gopls/internal/lsp/source/view.go                  |   4 +-
 gopls/internal/lsp/workspace.go                    |   2 +-
 .../marker/testdata/diagnostics/addgowork.txt      |  45 +++
 .../marker/testdata/diagnostics/usemodule.txt      |  51 +++
 .../regtest/marker/testdata/quickfix/addgowork.txt |  44 ---
 .../regtest/marker/testdata/quickfix/usemodule.txt |  49 ---
 gopls/internal/regtest/workspace/quickfix_test.go  | 344 +++++++++++++++++++++
 20 files changed, 806 insertions(+), 168 deletions(-)
 create mode 100644 gopls/internal/regtest/marker/testdata/diagnostics/addgowork.txt
 create mode 100644 gopls/internal/regtest/marker/testdata/diagnostics/usemodule.txt
 delete mode 100644 gopls/internal/regtest/marker/testdata/quickfix/addgowork.txt
 delete mode 100644 gopls/internal/regtest/marker/testdata/quickfix/usemodule.txt
 create mode 100644 gopls/internal/regtest/workspace/quickfix_test.go
```

**Comment by findleyr** [comment]
Oops, the new marker harness doesn't set GOPACKAGESDRIVER="off". I assume that's the root cause.

Can you confirm that the test succeeds if you set `GOPACKAGESDRIVER=off` first?

**Comment by Oguidan** [comment]
@findleyr, can you explain to me? I am kind of lost.

**Comment by bcmills** [comment]
@findleyr, confirmed: setting `GOPACKAGESDRIVER=off` fixes the test failure.

```
~/x/tools/gopls$ GOPACKAGESDRIVER=off go1.20.11 test ./internal/regtest/marker/ -run=TestMarkers/diagnostics/usemodule.txt
ok      golang.org/x/tools/gopls/internal/regtest/marker        2.262s
```

**Comment by Oguidan** [comment]
@findleyr I see that you have resolved the issue. Could you please explain it to me?

**Comment by findleyr** [comment]
@Oguidan can you please ask a more specific question? What don't you understand?

**Comment by Oguidan** [comment]
@findleyr when you said "the new marker harness doesn't set GOPACKAGESDRIVER="off". I assume that's the root cause.". What's a marker harness.
And please if it doesn't border you I will like to follow you in each of you next contribution.

**Comment by findleyr** [comment]
@Oguidan the new marker harness is a test package we run that invokes data-driven tests, encoded as txtar files. You can see its documentation here:  https://pkg.go.dev/golang.org/x/tools/gopls/internal/test/marker.

Unlike other test runners, it was not setting GOPACKAGESDRIVER=off, which means inside certain organizations the tests may run differently due to a different go/packages driver. We want our tests to be deterministic, so need to explicitly turn off external go/packages drivers.

**Comment by Oguidan** [comment]
Hi @findleyr,

Thank you very much for your guidance; I now have a better understanding.

I am eager to learn and would greatly appreciate your mentorship. There is so much I would like to gain from your expertise.

Looking forward to your positive response.

**Comment by findleyr** [comment]
@Oguidan, sorry I don't have bandwidth for mentorship.

**Comment by Oguidan** [comment]
@findleyr Ok I see, but I will keep to you if doesn't border you.
