### ISSUE TITLE
affected/package:  I installed the opengl library but I get this error:

### ISSUE THREAD

**Issue by MakIcon** [golang/go#64084]
imports github.com/go-gl/gl/v4.1-core/gl: build constraints exclude all Go files in C:\Users\USER\go\pkg\mod\github.com\go-gl\gl@v0.0.0-20231021071112-07e5d0ea2e71\v4.1-core\gl

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
