### ISSUE TITLE
cmd/gofmt: bad indenting of map literals as chained method arguments

### ISSUE THREAD

**Issue by gopherbot** [golang/go#6409]
by **cfbradford**:

<pre>What steps will reproduce the problem?
Format this code: <a href="http://play.golang.org/p/GIcbfEeB5E">http://play.golang.org/p/GIcbfEeB5E</a>

What is the expected output?
lines 22-25 should be indented one more level

This seems to have something to do with the combination of a map literal in the middle
of a set of chained method calls.

(There also seems to be something funky going on with the Playground. If you try to run
this code that does nothing you get an &quot;out of memory&quot; error message.)</pre>

**Comment by agnivade** [comment]
> What steps will reproduce the problem?
Format this code: http://play.golang.org/p/GIcbfEeB5E
What is the expected output?
lines 22-25 should be indented one more level

Seems fixed now. Please reopen if you think otherwise.

**Comment by griesemer** [comment]
@agnivade LGTM. Thanks for checking this!
