### ISSUE TITLE
net/http: problems or undocumented features dealing with handler timeout

### ISSUE THREAD

**Issue by julianmorrison** [golang/go#6410]
<pre>What steps will reproduce the problem?

First problem: a http handler which delays longer than server.WriteTimeout just silently
sends nothing, not even a HTTP error header. This behaviour might be deliberate (on the
basis of &quot;use a timeout handler instead&quot;), but it needs documenting.

Second problem: responseWriter.Write() returns nil for err (a write success) if
WriteTimeout has been exceeded. (Contrast: using a http.TimeoutHandler, it returns
&quot;http: Handler timeout&quot; correctly.)

Third problem: using a TimeoutHandler, with the actual handler having the behaviour or
Write, long delay, Write, and a timeout set to fire during the delay, the first write
sends the headers and the written value, then the timeout fires and appends the timeout
text and fails to set headers (because they were already sent). The result is a jumble
of output. This is not exactly an error, but it's a thing that needs communicating in
the docs: that the TimeoutHandler uses the same ResponseWriter, and if you have written
anything it will be unable to rescind it.

Which compiler are you using (5g, 6g, 8g, gccgo)?

8g

Which operating system are you using?

Ubuntu Linux 12.04 32 bit.

Which version are you using?  (run 'go version')

go version go1.1 linux/386</pre>

**Comment by bradfitz** [comment]
I think most of this has since been fixed or documented, but assigning to myself to double-check.

**Comment by odeke-em** [comment]
In regards to:
1) We've got TestServerTimeouts https://github.com/golang/go/blob/07a22bbc11de6c8cdac599f59ef00f019d22ff67/src/net/http/serve_test.go#L505-L595
2) We've got TestOnlyWriteTimeout https://github.com/golang/go/blob/07a22bbc11de6c8cdac599f59ef00f019d22ff67/src/net/http/serve_test.go#L771-L824
3) am not sure fully yet, I'll defer to Mr. HTTP @bradfitz

**Comment by bradfitz** [comment]
Thanks @odeke-em for investigating and finding the tests.

And #3 has been documented much more in the four years since this bug was filed. It now says:

```go
        // Changing the header map after a call to WriteHeader (or
        // Write) has no effect unless the modified headers are
        // trailers.
```

So I think we're good here. These many-bug-reports-in-one bugs tend to slip through the cracks since they can't be closed piecemeal. In the future, feel free to spam us with a dozen small bugs, cross-referenced as needed.
