### ISSUE TITLE
how:  how to build all src go files into exe,  open exe in ida , i should to see  all asm for  my lib  all go pkgs and  go files and go funcs ?

### ISSUE THREAD

**Issue by zengfr** [golang/go#64109]
how to build all src go files into exe, ? 
open exe in ida , i should to see  all asm code for  my lib  all go pkgs and all  go files and all go funcs ?
but now  exe is to small  to tiny ... only some funcs in exe .....not all funcs in exe

**Comment by mvdan** [comment]
The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.
