### ISSUE TITLE
fmt: `bad pointer in frame fmt.(*pp).printValue`

### ISSUE THREAD

**Issue by gucio321** [golang/go#64111]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.4 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/my-username/.cache/go-build'
GOENV='/home/my-username/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/my-username/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/my-username/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.4'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build497266722=/tmp/go-build -gno-record-gcc-switches'
</pre></details>

### What did you do?

I'm writting a wrapper of C `void*` pointer via CGO. I'm getting the following panic:
```console
runtime: bad pointer in frame fmt.(*pp).printValue at 0xc00022d758: 0x1
fatal error: invalid pointer found on stack
```

Code causing this looks as follows:
```go
        v := texture.ID()
        fmt.Println("%T\n", v)
```

**BUT** when I add this single line:
```go
        fmt.Println(texture)
        v := texture.ID()
        fmt.Println("%T\n", v)
```

This works perfectly.

Full project (as I'm unable to extract a single reproduction code) is here:
https://github.com/gucio321/cimgui-go/tree/callbacks

### What did you expect to see?

No panic should happen

### What did you see instead?

Panic

**Comment by ericlagergren** [comment]
Any sort of repro would be helpful.

Out of curiosity, what happens when you add `runtime.KeepAlive(texture)` after the call to `fmt.Println` in your first code snippet?

Also, fyi: `fmt.Println` doesn't accept format specifiers.

**Comment by gucio321** [comment]
> Also, fyi: fmt.Println doesn't accept format specifiers.

oh, sorry, its a typo ofc. I meant `Printf`, but it doesn't matter in fact. The problem is with the value returned by `texture.ID()` which returns `unsafe.Pointer` representing C `void*` pointer

> Out of curiosity, what happens when you add runtime.KeepAlive(texture) after the call to fmt.Println in your first code snippet?

nothing changes

> Any sort of repro would be helpful.

I know, I tried to write some code but with no result.

Also, I tried to use go-delve to debug this but with no result - when using debugger it worked fine...

**Comment by bcmills** [comment]
0x1 is almost certainly not a valid pointer. Per the C11 spec, “the result [of converting an integer to a pointer type] is implementation-defined, might not be correctly aligned, might not point to an entity of the referenced type, and might be a trap representation.” It just so happens that 0x1 acts as a trap representation for the Go runtime.

If you have a C type that may represent a mix of pointers and integers, you should generally pass it to Go as a `uintptr` rather than a `void*`.

**Comment by mknyszek** [comment]
@gucio321 Is there anything to follow-up with here? Closing optimistically, but please comment if you disagree. Thanks!

**Comment by gucio321** [comment]
@mknyszek After reading @bcmills's statement I still think that fmt shouldn't care what exactly is the pointer as it (in theory) could be whatever the programmer wants - even 0x1 (because why not? - its the idea of the unsafe package). So in my opinion using uintptr is a good workaround here but I think that this panic is a bug in go that _should be fixed_, shouldn't it?

**Comment by gucio321** [comment]
CC @mknyszek

**Comment by gucio321** [comment]
Also, using `uintptr` is in fact not a good solution at all since it violates race detector rules.
