### ISSUE TITLE
affected/package: 

### ISSUE THREAD

**Issue by gongxulei** [golang/go#64143]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.11 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN="/Volumes/work/go/bin"
GOCACHE="/Users/gongxulei/Library/Caches/go-build"
GOENV="/Users/gongxulei/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Volumes/work/go/pkg/mod"
GONOPROXY="gitlab.woqutech.com"
GONOSUMDB="gitlab.woqutech.com"
GOOS="darwin"
GOPATH="/Volumes/work/go"
GOPRIVATE="gitlab.woqutech.com"
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.20.11"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="0"
GOMOD=""
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cf/r0y65jhx4y9fg0m4b968c9pr0000gn/T/go-build2890987543=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I upgrade macos to version14.1.1
use go-Delve debug code 
it‘s not work

### What did you expect to see?
Print stack information

### What did you see instead?

Type 'dlv help' for list of commands.
runtime: g 6: unexpected return pc for runtime.sigpanic called from 0x4522009
stack: frame={sp:0xc0005cbcd0, fp:0xc0005cbd00} stack=[0xc0005c8000,0xc0005cc000)
0x000000c0005cbbd0:  0x000000c000703380  0x0000000000000000 
0x000000c0005cbbe0:  0x000000c0005cbca0  0x000000000103d775 <runtime.gopanic+0x0000000000000115> 
0x000000c0005cbbf0:  0x0000000000000002  0x4ce88ff100000003 
0x000000c0005cbc00:  0x000000c0005cbc20  0x0000000000000000 
0x000000c0005cbc10:  0x0000000000000000  0x0000000000000000 
0x000000c0005cbc20:  0x00000000000065cc  0x00000000031d315f 
0x000000c0005cbc30:  0x0000000000000013  0x00000000031dc748 
0x000000c0005cbc40:  0x0000000000000017  0x0000000000000000 
0x000000c0005cbc50:  0x0000000000000000  0x000000c0007033a0 
0x000000c0005cbc60:  0x000000c000703380  0x0000000000000000 
0x000000c0005cbc70:  0x0000000002fc57e0  0x0000000004011420 
0x000000c0005cbc80:  0x0000000000000000  0x0000000000000000 
0x000000c0005cbc90:  0x0000000000000000  0x0000000000000000 
0x000000c0005cbca0:  0x000000c0005cbcc0  0x000000000103c1a5 <runtime.panicmem+0x0000000000000045> 
0x000000c0005cbcb0:  0x0000000002fc57e0  0x0000000004011420 
0x000000c0005cbcc0:  0x000000c0005cbcf0  0x0000000001055fe5 <runtime.sigpanic+0x0000000000000245> 
0x000000c0005cbcd0: <0x0000000000000000  0x0000000000000000 
0x000000c0005cbce0:  0x0000000000000000  0x000000c000703380 
0x000000c0005cbcf0:  0x000000c0005cbe88 !0x0000000004522009 
0x000000c0005cbd00: >0x000000c00052c680  0x0000000003b6aff8 
0x000000c0005cbd10:  0x00000000034f1a4b  0x000000000000000f 
0x000000c0005cbd20:  0x00000000037adeae  0x0000000000000024 
0x000000c0005cbd30:  0x000000000000059a  0x000000c00052c680

**Comment by adonovan** [comment]
The Delve debugger is not maintained by the Go team. I suggest you look for open issues at https://github.com/go-delve/delve/issues.
