### ISSUE TITLE
x/tools/gopls: need a theory of URls

### ISSUE THREAD

**Issue by adonovan** [golang/go#64147]
Recently we finally got rid of almost everything in the golang.org/x/tools/gopls/internal/span package. Only span.URI remains, and I would like to get rid of it too, either by deleting it, moving it to a sensible location, or fusing it with something else. The question is: what does the span.URI abstraction represent? The disappointing current answer is: "just a URI"; it needn't be a "file:" URI, nor need it be non-empty. Calling URI.Filename on an invalid or non-file-scheme span.URI panics.

The protocol.DocumentURI type represents a URI of an editor document. In practice it is always a "file:" scheme URI (though this isn't required by [the LSP docs](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#documentUri)). However, according to those docs, it may be URL-encoded, so colons in Windows drive letters do not appear literally, and there is evidence in the code that it may contain `"file://"` URIs with only 2 slashes (not 3, and no hostname). So, there is a logical need to convert DocumentURIs as they arrive in requests into some kind of processed internal form, such as span.URI, and this operation is fallible, so its errors must be handled.

This suggests that we should retain the distinction between URI types and audit the codebase (possibly with the help of a static analysis in the style of the safetoken tests) for conversions of DocumentURI to span.URI without validation. Should span.URI, renamed to something suitable like protocol.FileURI, be made stricter about the invariant that it represents a valid "file:" URL? It's a large change, and the status quo doesn't currently cause any obvious problems, but currently there is little rhyme or reason to when we validate DocumentURIs.

@findleyr

**Comment by findleyr** [comment]
> A few little helpers (like filepath.Dir and Base and Join) for URLs would also go a long way to avoiding the need for conversions.

Yes, this has come up in the past (I thought we had an issue for a 'uripath' library). (Aside: I suppose it's not fair to say "this has come up in the past", because it feels like everything has come up in the past!).

It's a good idea. I just never had the patience to convince myself of the algorithmic correctness.

**Comment by adonovan** [comment]
> > A few little helpers (like filepath.Dir and Base and Join) for URLs would also go a long way to avoiding the need for conversions.
> 
> Yes, this has come up in the past (I thought we had an issue for a 'uripath' library). (Aside: I suppose it's not fair to say "this has come up in the past", because it feels like everything has come up in the past!).
> 
> It's a good idea. I just never had the patience to convince myself of the algorithmic correctness.

The implementations can convert to and from strings and call filepath, just like we do today. At least it'll centralize any existing bugs in one place.

**Comment by bcmills** [comment]
See also #32456.
