### ISSUE TITLE
gccgo: missing declared and not used error

### ISSUE THREAD

**Issue by griesemer** [golang/go#6415]
<pre><a href="http://play.golang.org/p/kSqOMI9a_6">http://play.golang.org/p/kSqOMI9a_6</a>

Expected output should be along the lines of:

prog.go:4: s declared and not used

But the compiler is silent.

This is an implementation restriction, and a compiler may be free to restrict or not.
That said, given the specification of the restriction, this is not consistent with the
usage checks that gc already does.

We may not be able to fix this since it may invalidate code that is now compiling.</pre>

**Comment by paranoiacblack** [comment]
What's the status of this issue? It appears cmd/gc also remains silent in this situation. Is this still a problem?

**Comment by ianlancetaylor** [comment]
The same issue for the gc compiler is #6414.

**Comment by griesemer** [comment]
Yes, I'd consider this a bug in gc and gccgo. go/types reports an error.

**Comment by paranoiacblack** [comment]
Fixed in gcc.gnu.org/r219916.
