### ISSUE TITLE
x/net/http2: increased memory use with ForceAttemptHTTP2

### ISSUE THREAD

**Issue by rawat-divyanshu** [golang/go#64164]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
In my golang application we were using the http Client with custom TLS config, and as per the golang's x/net/http package if we provide a custom TLS Config then the support for http/2 will be disabled. So for enabling the http/2 support with custom TLS config I enabled the flag `ForceAttemptHTTP2 `  flag, but with that I'm seeing a 200MB of memory spike in my application.

I'm running this application on a 800 Hosts setup. But as of now none of the Hosts has a http/2 support enabled still I'm seeing this memory spike.

On profiling my application I'm seeing the top contributor for my memory is bytes.growSlice which increased from 8% to whooping 30%. Profile details are as below:
1. Profile with above changes:
<img width="747" alt="Screenshot 2023-11-15 at 2 52 37 PM" src="https://github.com/golang/go/assets/47237721/3f5b39cf-5591-4823-93c2-708d757f455e">
<img width="591" alt="Screenshot 2023-11-15 at 2 53 18 PM" src="https://github.com/golang/go/assets/47237721/adda9b7f-4c08-45d7-b91a-2a58d94f3048">

<img width="780" alt="Screenshot 2023-11-15 at 3 00 53 PM" src="https://github.com/golang/go/assets/47237721/8dca854d-24f4-4af0-a65e-1669371b0917">

2. Profile without changes:
<img width="591" alt="Screenshot 2023-11-15 at 2 56 12 PM" src="https://github.com/golang/go/assets/47237721/99db8ae3-c50b-42fd-a4b9-a9f9ed294c0b">
<img width="591" alt="Screenshot 2023-11-15 at 2 56 27 PM" src="https://github.com/golang/go/assets/47237721/6d0d525e-7d13-4290-95da-d41cb20b58c1">

### What did you expect to see?
Since I enabled the http/2 support, after the protocol negotiation since I didn't had any hosts supporting http/2 the request should fallback to http/1.1 and application should behave normally.

### What did you see instead?
Though requests were falling back to http/1.1 but there was 250MB more memory usage by the application.

**Comment by seankhliao** [comment]
please provide a reproducer demonstrating the issue.
a tls connection includes a list of supported application protocols, if h2 wasn't advertised, it should never be used.

**Comment by mauri870** [comment]
I think this comment explains why:

```go
	// TODO: let getReadBuf be configurable, and use a less memory-pinning
	// allocator in server.go to minimize memory pinned for many idle conns.
	// Will probably also need to make frame invalidation have a hook too.
	getReadBuf func(size uint32) []byte
```

https://github.com/golang/net/blob/547e7edf3873d6f3a9c093d3785f9e2289e00746/http2/frame.go#L282-L285

**Comment by mauri870** [comment]
Maybe we can come up with something similar to [CL 539915](https://go-review.googlesource.com/c/net/+/539915) to optimize the memory usage and allocations.
