### ISSUE TITLE
x/tools/gopls: add some error handle postfix completion (rr, reterr, varCheckError)

### ISSUE THREAD

**Issue by rogeryk** [golang/go#64178]
### Describe the solution you'd like
Go requires that you must explicit error handling, so many times you must write some boring error handling code, and postfix completion can ease the pain.
rr
In most cases, we just need check the error and return it.
![Kapture 2023-11-15 at 22 47 13](https://github.com/golang/go/assets/28089185/d20a7121-ea10-43bf-9999-728e11462441)
This also depends on the return parameters of the current function, for example, when the function has return values other than error, the return values other than error will use default values.
![Kapture 2023-11-15 at 22 49 10](https://github.com/golang/go/assets/28089185/24b26699-b396-4326-8617-b3a14ceb90bc)

reterr
Sometimes when calling a function, you just need to check if there is an error.
![Kapture 2023-11-15 at 22 55 42](https://github.com/golang/go/assets/28089185/59f8a7fd-9528-4dbe-8b1c-607e32d2c270)

varCheckError
Get the return value after calling the function and check for errors. This is a more general version compared to reterr.
![Kapture 2023-11-15 at 22 58 52](https://github.com/golang/go/assets/28089185/dc708823-f300-4ec0-b248-583b4145639c)

**Comment by rogeryk** [comment]
@muirdm Yes, It is  same thing in the first case, but I think the latter two will still provide some convenience.
And i find that the rr and reterrr are the same postfix completion, so we can just focus on the latter two scenarios

**Comment by rogeryk** [comment]
@findleyr What do you think of this proposal? The pattern of error handle will not change anytime soon, so I think it's very valuable.

**Comment by findleyr** [comment]
@rogeryk I think this makes sense. I'll review your CL -- thanks!

**Comment by findleyr** [comment]
(although I'm not sure about `varCheckErr` -- let's discuss on the CL).

**Comment by findleyr** [comment]
In discussion on https://go.dev/cl/550455, we have settled on the more consistent snippet names `iferr` and `variferr`. I believe `iferr` is consistent with the preexisting vscode-go snippet: https://github.com/Microsoft/vscode-go/issues/1549#issuecomment-370312947.

**Comment by rogeryk** [comment]
@findleyr 
Gerrit can't seem to send images, so I'll use a gif here to explain why the specified placeholder tabstop is needed.
Look at the pictures below, when I modify "err", all "err" variables are modified at the same time. This requires us to specify the same tabstops for all "err"
![iShot_2024-01-03_20 37 46](https://github.com/golang/go/assets/28089185/ad6f520d-fae0-4136-95a6-6ebf146e1f50)

There is another confusing point, and I will explain it here.There is a nested tabstop in "variferr"
```
		{{- if eq ($a.TypeName $v.Type) "error" -}}
			{{$errName | $a.SpecifiedPlaceholder (len $a.Tuple) |
				$a.SpecifiedPlaceholder ($a.Inc (len $a.Tuple))}}
		{{- else -}}
```

```
		{{- if eq ($a.TypeName $v.Type) "error" -}}
			{{$errName | $a.SpecifiedPlaceholder 1 | $a.SpecifiedPlaceholder 2}}
		{{- else -}}

```
This is because sometimes we want to return err directly, and sometimes we want to wrap the err. So an additional tabstops is needed to modify the last returned err. Look the below picture.
![iShot_2024-01-03_21 08 31](https://github.com/golang/go/assets/28089185/8a6061a1-5d12-4ad7-a66b-29979e8ed79c)

**Comment by findleyr** [comment]
@rogeryk that's very cool, and I didn't know it worked that way. Thank you for the explanation.
