### ISSUE TITLE
runtime: "malloc/free - deadlock" while trying to print panic message

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#6419]
<pre>From this thread <a href="https://groups.google.com/d/topic/golang-nuts/aX7sJxostWE/discussion">https://groups.google.com/d/topic/golang-nuts/aX7sJxostWE/discussion</a>

Go version: 
go version devel +45343b9c3db4 Mon Sep 16 22:53:12 2013 +1000 windows/386 

Panic message: 
fatal error: malloc/free - deadlock 
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x424bda] 

runtime stack: 
runtime: unexpected return pc for runtime.sigpanic called from 0x77238e19 
runtime.throw(0x63ece0) 
        C:/vcs/go/src/pkg/runtime/panic.c:464 +0x67 
runtime.mallocgc(0x8, 0x0, 0x0) 
        C:/vcs/go/src/pkg/runtime/malloc.goc:51 +0x4f 
runtime.mal(0x8) 
        C:/vcs/go/src/pkg/runtime/malloc.goc:700 +0x3a 
copyin(0x4f5ae0, 0x32cafb98, 0x32cafba4) 
        C:/vcs/go/src/pkg/runtime/iface.c:153 +0x5c 
runtime.convT2E(0x4f5ae0, 0x63dccf, 0x31, 0x4f5ae0, 0x31) 
        C:/vcs/go/src/pkg/runtime/iface.c:221 +0x32 
runtime.newErrorString(0x63dccf, 0x31, 0x32cafbc0) 
        C:/vcs/go/src/pkg/runtime/error.go:74 +0x3a 
runtime.panicstring(0x63dccf) 
        C:/vcs/go/src/pkg/runtime/panic.c:477 +0x82 
runtime.sigpanic() 
        C:/vcs/go/src/pkg/runtime/os_windows.c:337 +0xb4 
runtime.mallocgc(0x8, 0x0, 0x0) 
        C:/vcs/go/src/pkg/runtime/malloc.goc:70 +0xca 
runtime.mal(0x8) 
        C:/vcs/go/src/pkg/runtime/malloc.goc:700 +0x3a 
copyin(0x4f5ae0, 0x32cafc60, 0x32cafc6c) 
        C:/vcs/go/src/pkg/runtime/iface.c:153 +0x5c 
runtime.convT2E(0x4f5ae0, 0x63dccf, 0x31, 0x4f5ae0, 0x31) 
        C:/vcs/go/src/pkg/runtime/iface.c:221 +0x32 
runtime.newErrorString(0x63dccf, 0x31, 0x32cafc88) 
        C:/vcs/go/src/pkg/runtime/error.go:74 +0x3a 
runtime.panicstring(0x63dccf) 
        C:/vcs/go/src/pkg/runtime/panic.c:477 +0x82 
runtime: unexpected return pc for runtime.sigpanic called from 0x77238e19 
runtime.sigpanic() 
        C:/vcs/go/src/pkg/runtime/os_windows.c:337 +0xb4 

Alex</pre>

**Comment by ianlancetaylor** [comment]
I'm fairly sure that this was fixed a while back by https://golang.org/cl/83980043.  Closing.

**Comment by alexbrainman** [comment]
> I'm fairly sure that this was fixed a while back by https://golang.org/cl/83980043. Closing.

There is no way for me to test CL 83980043, but it does look like it might fix this issue.

Thank you.

Alex
