### ISSUE TITLE
x/tools/go/analysis: inconsistency in TextEdit behavior and document

### ISSUE THREAD

**Issue by uffy** [golang/go#64199]
### What version of Go are you using (`go version`)?

<pre>
go version go1.20.6 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

main.go:

```
package main

import (
	"golang.org/x/tools/go/analysis"
	"golang.org/x/tools/go/analysis/singlechecker"
)

func main() {
	singlechecker.Main(&analysis.Analyzer{
		Name: "test",
		Doc:  "test insert code",
		Run: func(pass *analysis.Pass) (any, error) {
			pass.Report(analysis.Diagnostic{
				Message: "test insert code",
				Pos:     1,
				SuggestedFixes: []analysis.SuggestedFix{
					{
						Message: "test insert code",
						TextEdits: []analysis.TextEdit{
							{
								Pos:     1,
								End:     0,
								NewText: []byte("/* insert comment */"),
							},
						},
					},
				},
				Related: nil,
			})

			return nil, nil
		},
	})
}
```

test.go:
```
package main
func main(){}
```

```
$ go run main.go -fix test.go
test: analysis "test" suggests invalid fix: pos (1) > end (0)
exit status 1
```

### What did you expect to see?

https://github.com/golang/tools/blob/v0.15.0/go/analysis/diagnostic.go#L69-L74
```
type TextEdit struct {
	// For a pure insertion, End can either be set to Pos or token.NoPos.
	Pos     token.Pos
	End     token.Pos
	NewText []byte
}
```
Insert "/\*test\*/" into start of test.go or a correct document.

### What did you see instead?

error happened

**Comment by uffy** [comment]
There appear to be two different behaviors when `TextEdit.End` is set to `token.NoPos`.

The checker does not accept `token.NoPos`:
https://github.com/golang/tools/blob/v0.15.0/go/analysis/internal/checker/checker.go#L350

On the other hand, gopls accepts `token.NoPos`:
https://github.com/golang/tools/blob/v0.15.0/gopls/internal/lsp/source/fix.go#L110

So, I'm not sure whether we should make the checker support `token.NoPos` or remove gopls' support for `token.NoPos` and update the documentation.

**Comment by timothy-king** [comment]
> So, I'm not sure whether we should make the checker support token.NoPos or remove gopls' support for token.NoPos and update the documentation.

I would lean towards saying that [go/analysis/internal/checker/checker.go#L350](https://github.com/golang/tools/blob/v0.15.0/go/analysis/internal/checker/checker.go#L350) is not conforming to the documentation in public API and to update that implementation. I can review a CL if someone wants to pick this up.

**Comment by uffy** [comment]
I found that `go/analysis/analysistest` has the same issue, so I have submitted a pull request to fix it.
