### ISSUE TITLE
net/http: bundled http2 uses priority-based scheduler instead of round robin scheduler

### ISSUE THREAD

**Issue by WeidiDeng** [golang/go#64216]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.21.4
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you expect to see?

Bundled http2 uses round robin scheduler.

### What did you see instead?

By default, bundled http2 support should use round robin scheduler according to [this comment](https://github.com/golang/go/issues/58804#issuecomment-1571909056) and [commit](https://go-review.googlesource.com/c/net/+/478735). Howerver, it will still use the old priority scheduler because this [field is set](https://github.com/golang/go/blob/release-branch.go1.21/src/net/http/server.go#L3330), which prevented the default behavior from happening.

**Comment by bcmills** [comment]
(attn @neild)

**Comment by linxiulei** [comment]
Gentle ping @WeidiDeng. Your CL https://go.dev/cl/543178 is ready to submit. Would you like to submit it?

**Comment by bcmills** [comment]
I think at this point in the release cycle, changing the http2 scheduler would need a freeze exception from @golang/release — RC1 is out for testing and does not include the change, which seems like it may be significant for some users.

**Comment by WeidiDeng** [comment]
@linxiulei I was the first to report the problem and I made a pr that addresses this problem, but it never got merged. I would call #67706 a duplicate of this instead of the other way round.

It is fixed, so whatever 🤷 .
