### ISSUE TITLE
cmd/go: "package?go-get=1 404 not found" errors occurs when go get private project in internal private gitlab repository

### ISSUE THREAD

**Issue by learneryork** [golang/go#64223]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go v1.16

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/usr/local/go/bin"
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE="a.b.com"
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY="https://a.b.com"
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE="https://a.b.com"
GOPROXY="https://goproxy.io,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.google.cn"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.12"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/test/workspace/demo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3882968519=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Modify the configuration to be able to download private projects from private gitlab repositories

Approach 1
```bash
$ go env -w GOPRIVATE=a.b.com
$ go env -w GOINSECURE=a.b.com
$ go get a.b.com/testgroup/compkg
```

Approach 2
```bash
$ git config --global url."git@a.b.com:testgroup/compkg.git".insteadOf "https://a.b.com/testgroup/compkg"
$ go get a.b.com/testgroup/compkg
```

Approach 3
```bash
$ vim ~/.netrc
machine a.b.com
              username abcd
              password  private-token
```

> PS: `testgroup` is groupname not username in gitlab

### What did you expect to see?
I can download private project successfullly and use it `import`

### What did you see instead?
`go get` failed, the error is as follows
```
go get: unrecognize import path "a.b.com/test/compkg": reading https://a.b.com/testgroup/compkg?go-get=1: 404 Not Found
```

I used the following curl command to return the following error:
```
$ curl --insecure https://a.b.com/testgroup/compkg?go-get=1
...
404 Not Found
...
```

**Comment by seankhliao** [comment]
we don't support 1.16 anymore.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by shaneHowearth** [comment]
For the record I've been having a very similar problem with go get
(I am considering filing an issue, but I am appending this here in case anyone finds this helpful)

```
go version
go version go1.21.4 linux/arm64
```
The issue was "fixed" by changing the `go.mod` of the project I have hosted privately to be
```
module shanehowearth.com/my/project.git
...
```
No amount of `.gitconfig` fu would get `go get` to fetch the repository that is hosted on my on servers

See: https://stackoverflow.com/questions/60645866/how-can-i-make-go-get-work-with-a-repo-on-a-local-server for more information
