### ISSUE TITLE
affected/package: godoc playground is not showing a Run button for my own examples

### ISSUE THREAD

**Issue by benorgil** [golang/go#64232]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.3 linux/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/home/vscode/.cache/go-build'
GOENV='/home/vscode/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='local'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_arm64'
GOVCS=''
GOVERSION='go1.21.3'
GCCGO='gccgo'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/workspaces/myproject/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build894106699=/tmp/go-build -gno-record-gcc-switches'

</pre></details>

### What did you do?

Created example:
```
func Example_giveMeRunButton() {
	fmt.Println("derp")

	// Output: derp
}
```

Ran `godoc -http=:8080 -play`

Browsed to it locally

### What did you expect to see?
A Run button

### What did you see instead?
![image](https://github.com/golang/go/assets/10213389/9be38ea3-b396-48c6-b562-fd1788c947e9)

I confirmed that if I run `godoc -http=:8080 -play` locally and navigate to http://localhost:8080/pkg/fmt/#example_Errorf I get a Run button as well and it works:
![image](https://github.com/golang/go/assets/10213389/beb84073-781c-4213-834f-ccd172917e94)

So the playground itself _is_ working just not for my own examples for some reason.

**Comment by seankhliao** [comment]
your example file doesn't qualify as a whole file example: https://go.dev/blog/examples#larger-examples

also note that godoc is considered deprecated, please use pkgsite.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
