### ISSUE TITLE
x/tools/gopls: bug in analysis importer reported by telemetry

### ISSUE THREAD

**Issue by adonovan** [golang/go#64236]
```
#!stacks
"bug.Errorf" && "cache.(*analysisNode)._import.func1:+41"
```

This stack `sbGdaw`, `hz09pg`, `zhKNnQ` was [reported by telemetry](https://storage.googleapis.com/prod-telemetry-merged/2023-11-13.json):

[cache.(*analysisNode)._import.func1:41](https://cs.opensource.google/go/x/tools/+/refs/tags/gopls/v0.14.1:gopls/internal/lsp/cache/analysis.go;l=556) is
```
		pkg, err := gcimporter.IImportShallow(an.fset, getPackages, an.summary.Export, string(an.m.PkgPath), bug.Reportf)
		if err != nil {
			an.typesErr = bug.Errorf("%s: invalid export data: %v", an.m, err)
			an.types = nil
		} else if pkg != an.types {
			log.Fatalf("%s: inconsistent packages", an.m)
		}
```

```
gopls/bug
golang.org/x/tools/gopls/internal/bug.report:35
golang.org/x/tools/gopls/internal/bug.Errorf:2
golang.org/x/tools/gopls/internal/lsp/cache.(*analysisNode)._import.func1:41
sync.(*Once).doSlow:5
sync.(*Once).Do:?65
golang.org/x/tools/gopls/internal/lsp/cache.(*analysisNode)._import:1
golang.org/x/tools/gopls/internal/lsp/cache.(*analysisNode).typeCheck.func2:34
golang.org/x/tools/gopls/internal/lsp/cache.importerFunc.Import:0
go/types.(*Checker).importPackage:28
go/types.(*Checker).collectObjects.func1:13
go/types.(*Checker).walkDecl:9
go/types.(*Checker).walkDecls:?391
go/types.(*Checker).collectObjects:42
go/types.(*Checker).checkFiles:32
go/types.(*Checker).Files:?341
golang.org/x/tools/gopls/internal/lsp/cache.(*analysisNode).typeCheck:117
```
```
golang.org/x/tools/gopls@v0.14.1 go1.21.3 linux/amd64 (1)
```

Reported using golang.org/x/tools/gopls/internal/telemetry/cmd/stacks.

Dups: NpfwWw OeW1wA

Duplicates:

This stack `WRBqTw` was [reported by telemetry](https://storage.googleapis.com/prod-telemetry-merged/2024-01-13.json):

```
gopls/bug
golang.org/x/tools/gopls/internal/bug.report:35
golang.org/x/tools/gopls/internal/bug.Errorf:2
golang.org/x/tools/gopls/internal/lsp/cache.(*analysisNode)._import.func1:41
sync.(*Once).doSlow:5
sync.(*Once).Do:?65
golang.org/x/tools/gopls/internal/lsp/cache.(*analysisNode)._import:1
golang.org/x/tools/gopls/internal/lsp/cache.(*analysisNode).typeCheck.func2:34
golang.org/x/tools/gopls/internal/lsp/cache.importerFunc.Import:0
go/types.(*Checker).importPackage:28
go/types.(*Checker).collectObjects.func1:10
go/types.(*Checker).walkDecl:9
go/types.(*Checker).walkDecls:?383
go/types.(*Checker).collectObjects:42
go/types.(*Checker).checkFiles:18
go/types.(*Checker).Files:?307
golang.org/x/tools/gopls/internal/lsp/cache.(*analysisNode).typeCheck:117
```
```
golang.org/x/tools/gopls@v0.14.2 go1.19.13 darwin/arm64 (1)
```

This stack `C7ZvyQ` was [reported by telemetry](https://storage.googleapis.com/prod-telemetry-merged/2024-01-31.json):

```
gopls/bug
golang.org/x/tools/gopls/internal/bug.report:35
golang.org/x/tools/gopls/internal/bug.Errorf:2
golang.org/x/tools/gopls/internal/lsp/cache.(*analysisNode)._import.func1:41
sync.(*Once).doSlow:5
sync.(*Once).Do:?65
golang.org/x/tools/gopls/internal/lsp/cache.(*analysisNode)._import:1
golang.org/x/tools/gopls/internal/lsp/cache.(*analysisNode).typeCheck.func2:34
golang.org/x/tools/gopls/internal/lsp/cache.importerFunc.Import:0
go/types.(*Checker).importPackage:28
go/types.(*Checker).collectObjects.func1:13
go/types.(*Checker).walkDecl:9
go/types.(*Checker).walkDecls:?399
go/types.(*Checker).collectObjects:42
go/types.(*Checker).checkFiles:29
go/types.(*Checker).Files:?372
golang.org/x/tools/gopls/internal/lsp/cache.(*analysisNode).typeCheck:117
```
```
golang.org/x/tools/gopls@v0.14.2 go1.22rc2 darwin/arm64 other,vscode (1)
```

This stack `6jGwIA` was [reported by telemetry](https://storage.googleapis.com/prod-telemetry-merged/2024-02-09.json):

```
gopls/bug
golang.org/x/tools/gopls/internal/util/bug.report:35
golang.org/x/tools/gopls/internal/util/bug.Errorf:2
golang.org/x/tools/gopls/internal/cache.(*analysisNode)._import.func1:41
sync.(*Once).doSlow:5
sync.(*Once).Do:?65
golang.org/x/tools/gopls/internal/cache.(*analysisNode)._import:1
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck.func2:34
golang.org/x/tools/gopls/internal/cache.importerFunc.Import:0
go/types.(*Checker).importPackage:28
go/types.(*Checker).collectObjects.func1:13
go/types.(*Checker).walkDecl:9
go/types.(*Checker).walkDecls:?399
go/types.(*Checker).collectObjects:42
go/types.(*Checker).checkFiles:29
go/types.(*Checker).Files:?372
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck:118
```
```
golang.org/x/tools/gopls@v0.15.0-pre.2 go1.22rc2 linux/amd64 vscode (1)
```

Issue created by golang.org/x/tools/gopls/internal/telemetry/cmd/stacks.

Dups: OeW1wA  NpfwWw sNopDQ YUgxTQ g_3FdA qOlVPg sNopAA NpfwVg rcxYqw qOlVMw rcxYpg MCkoAw snYxVw

**Comment by findleyr** [comment]
We can live with this in v0.15.0. Let's move to v0.16.0

**Comment by adonovan** [comment]
This stack `NpfwWw` was [reported by telemetry](https://storage.googleapis.com/prod-telemetry-merged/2024-02-26.json):

```
gopls/bug
golang.org/x/tools/gopls/internal/util/bug.report:+35
golang.org/x/tools/gopls/internal/util/bug.Errorf:+2
golang.org/x/tools/gopls/internal/cache.(*analysisNode)._import.func1:+41
sync.(*Once).doSlow:+5
sync.(*Once).Do:=65
golang.org/x/tools/gopls/internal/cache.(*analysisNode)._import:+1
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck.func2:+34
golang.org/x/tools/gopls/internal/cache.importerFunc.Import:+0
go/types.(*Checker).importPackage:+28
go/types.(*Checker).collectObjects.func1:+13
go/types.(*Checker).walkDecl:+9
go/types.(*Checker).walkDecls:=399
go/types.(*Checker).collectObjects:+42
go/types.(*Checker).checkFiles:+29
go/types.(*Checker).Files:=372
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck:+118
```
```
golang.org/x/tools/gopls@v0.15.0-pre.3 go1.22.0 darwin/arm64 vscode (2)
```

Issue created by golang.org/x/tools/gopls/internal/telemetry/cmd/stacks.

**Comment by adonovan** [comment]
This stack `OeW1wA` was [reported by telemetry](https://storage.googleapis.com/prod-telemetry-merged/2024-02-20.json):

```
gopls/bug
golang.org/x/tools/gopls/internal/bug.report:35
golang.org/x/tools/gopls/internal/bug.Errorf:2
golang.org/x/tools/gopls/internal/lsp/cache.(*analysisNode)._import.func1:41
sync.(*Once).doSlow:5
sync.(*Once).Do:?65
golang.org/x/tools/gopls/internal/lsp/cache.(*analysisNode)._import:1
golang.org/x/tools/gopls/internal/lsp/cache.(*analysisNode).typeCheck.func2:34
golang.org/x/tools/gopls/internal/lsp/cache.importerFunc.Import:0
go/types.(*Checker).importPackage:28
go/types.(*Checker).collectObjects.func1:13
go/types.(*Checker).walkDecl:9
go/types.(*Checker).walkDecls:?399
go/types.(*Checker).collectObjects:42
go/types.(*Checker).checkFiles:36
go/types.(*Checker).Files:?355
golang.org/x/tools/gopls/internal/lsp/cache.(*analysisNode).typeCheck:117
```
```
golang.org/x/tools/gopls@v0.14.2 devel darwin/arm64 vscode (1)
```

Issue created by golang.org/x/tools/gopls/internal/telemetry/cmd/stacks.

**Comment by adonovan** [comment]
This stack `sNopDQ` was [reported by telemetry](https://storage.googleapis.com/prod-telemetry-merged/2024-03-08.json):

```
gopls/bug
golang.org/x/tools/gopls/internal/util/bug.report:+35
golang.org/x/tools/gopls/internal/util/bug.Errorf:+2
golang.org/x/tools/gopls/internal/cache.(*analysisNode)._import.func1:+41
sync.(*Once).doSlow:+5
sync.(*Once).Do:=65
golang.org/x/tools/gopls/internal/cache.(*analysisNode)._import:+1
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck.func2:+34
golang.org/x/tools/gopls/internal/cache.importerFunc.Import:+0
go/types.(*Checker).importPackage:+28
go/types.(*Checker).collectObjects.func1:+13
go/types.(*Checker).walkDecl:+9
go/types.(*Checker).walkDecls:=391
go/types.(*Checker).collectObjects:+42
go/types.(*Checker).checkFiles:+32
go/types.(*Checker).Files:=341
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck:+118
```
```
golang.org/x/tools/gopls@v0.15.1 go1.21.1 linux/amd64 vscode (1)
```

Issue created by golang.org/x/tools/gopls/internal/telemetry/cmd/stacks.

**Comment by adonovan** [comment]
This stack `YUgxTQ` was [reported by telemetry](https://storage.googleapis.com/prod-telemetry-merged/2024-03-10.json):

```
gopls/bug
golang.org/x/tools/gopls/internal/util/bug.report:+35
golang.org/x/tools/gopls/internal/util/bug.Errorf:+2
golang.org/x/tools/gopls/internal/cache.(*analysisNode)._import.func1:+41
sync.(*Once).doSlow:+5
sync.(*Once).Do:=65
golang.org/x/tools/gopls/internal/cache.(*analysisNode)._import:+1
golang.org/x/tools/gopls/internal/cache.(*analysisNode)._import.func1.1.1:+1
golang.org/x/sync/errgroup.(*Group).Go.func1:+3
runtime.goexit:+0
```
```
golang.org/x/tools/gopls@v0.15.1 go1.22.0 linux/amd64 vscode (1)
```

Issue created by golang.org/x/tools/gopls/internal/telemetry/cmd/stacks.

**Comment by adonovan** [comment]
This stack `g_3FdA` was [reported by telemetry](https://storage.googleapis.com/prod-telemetry-merged/2024-03-17.json):

```
gopls/bug
golang.org/x/tools/gopls/internal/util/bug.report:+35
golang.org/x/tools/gopls/internal/util/bug.Errorf:+2
golang.org/x/tools/gopls/internal/cache.(*analysisNode)._import.func1:+41
sync.(*Once).doSlow:+5
sync.(*Once).Do:=65
golang.org/x/tools/gopls/internal/cache.(*analysisNode)._import:+1
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck.func2:+34
golang.org/x/tools/gopls/internal/cache.importerFunc.Import:+0
go/types.(*Checker).importPackage:+28
go/types.(*Checker).collectObjects.func1:+13
go/types.(*Checker).walkDecl:+9
go/types.(*Checker).walkDecls:=399
go/types.(*Checker).collectObjects:+42
go/types.(*Checker).checkFiles:+29
go/types.(*Checker).Files:=373
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck:+118
```
```
golang.org/x/tools/gopls@v0.15.1 devel darwin/arm64 vscode (1)
```

Issue created by golang.org/x/tools/gopls/internal/telemetry/cmd/stacks.

**Comment by adonovan** [comment]
This stack `qOlVPg` was [reported by telemetry](https://storage.googleapis.com/prod-telemetry-merged/2024-04-03.json):

```
gopls/bug
golang.org/x/tools/gopls/internal/util/bug.report:+35
golang.org/x/tools/gopls/internal/util/bug.Errorf:+2
golang.org/x/tools/gopls/internal/cache.(*analysisNode)._import.func1:+41
sync.(*Once).doSlow:+5
sync.(*Once).Do:=65
golang.org/x/tools/gopls/internal/cache.(*analysisNode)._import:+1
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck.func2:+34
golang.org/x/tools/gopls/internal/cache.importerFunc.Import:+0
go/types.(*Checker).importPackage:+28
go/types.(*Checker).collectObjects.func1:+13
go/types.(*Checker).walkDecl:+9
go/types.(*Checker).walkDecls:=391
go/types.(*Checker).collectObjects:+42
go/types.(*Checker).checkFiles:+18
go/types.(*Checker).Files:=304
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck:+118
```
```
golang.org/x/tools/gopls@v0.15.2 go1.20.6 windows/amd64 vscode (1)
```

Issue created by golang.org/x/tools/gopls/internal/telemetry/cmd/stacks.

**Comment by adonovan** [comment]
This stack `sNopAA` was [reported by telemetry](https://storage.googleapis.com/prod-telemetry-merged/2024-04-21.json):

```
gopls/bug
golang.org/x/tools/gopls/internal/util/bug.report:+35
golang.org/x/tools/gopls/internal/util/bug.Errorf:+2
golang.org/x/tools/gopls/internal/cache.(*analysisNode)._import.func1:+41
sync.(*Once).doSlow:+5
sync.(*Once).Do:=65
golang.org/x/tools/gopls/internal/cache.(*analysisNode)._import:+1
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck.func2:+34
golang.org/x/tools/gopls/internal/cache.importerFunc.Import:+0
go/types.(*Checker).importPackage:+28
go/types.(*Checker).collectObjects.func1:+13
go/types.(*Checker).walkDecl:+9
go/types.(*Checker).walkDecls:=391
go/types.(*Checker).collectObjects:+42
go/types.(*Checker).checkFiles:+32
go/types.(*Checker).Files:=341
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck:+115
```
```
golang.org/x/tools/gopls@v0.15.3 go1.21.2 linux/amd64 vscode (1)
golang.org/x/tools/gopls@v0.15.3-pre.2 go1.21.2 linux/amd64 vscode (3)
```

Issue created by golang.org/x/tools/gopls/internal/telemetry/cmd/stacks.

**Comment by adonovan** [comment]
This stack `NpfwVg` was [reported by telemetry](https://storage.googleapis.com/prod-telemetry-merged/2024-04-21.json):

```
gopls/bug
golang.org/x/tools/gopls/internal/util/bug.report:+35
golang.org/x/tools/gopls/internal/util/bug.Errorf:+2
golang.org/x/tools/gopls/internal/cache.(*analysisNode)._import.func1:+41
sync.(*Once).doSlow:+5
sync.(*Once).Do:=65
golang.org/x/tools/gopls/internal/cache.(*analysisNode)._import:+1
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck.func2:+34
golang.org/x/tools/gopls/internal/cache.importerFunc.Import:+0
go/types.(*Checker).importPackage:+28
go/types.(*Checker).collectObjects.func1:+13
go/types.(*Checker).walkDecl:+9
go/types.(*Checker).walkDecls:=399
go/types.(*Checker).collectObjects:+42
go/types.(*Checker).checkFiles:+29
go/types.(*Checker).Files:=372
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck:+115
```
```
golang.org/x/tools/gopls@v0.15.3 go1.22.1 linux/amd64 vscode (1)
```

Issue created by golang.org/x/tools/gopls/internal/telemetry/cmd/stacks.

**Comment by adonovan** [comment]
This stack `rcxYqw` was [reported by telemetry](https://storage.googleapis.com/prod-telemetry-merged/2024-04-20.json):

```
gopls/bug
golang.org/x/tools/gopls/internal/util/bug.report:+35
golang.org/x/tools/gopls/internal/util/bug.Errorf:+2
golang.org/x/tools/gopls/internal/cache.(*analysisNode)._import.func1:+41
sync.(*Once).doSlow:+5
sync.(*Once).Do:=65
golang.org/x/tools/gopls/internal/cache.(*analysisNode)._import:+1
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck.func2:+34
golang.org/x/tools/gopls/internal/cache.importerFunc.Import:+0
go/types.(*Checker).importPackage:+28
go/types.(*Checker).collectObjects.func1:+10
go/types.(*Checker).walkDecl:+9
go/types.(*Checker).walkDecls:=383
go/types.(*Checker).collectObjects:+42
go/types.(*Checker).checkFiles:+18
go/types.(*Checker).Files:=307
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck:+118
```
```
golang.org/x/tools/gopls@v0.15.2 go1.19.13 darwin/amd64 vscode (1)
```

Issue created by golang.org/x/tools/gopls/internal/telemetry/cmd/stacks.

**Comment by adonovan** [comment]
This stack `qOlVMw` was [reported by telemetry](https://storage.googleapis.com/prod-telemetry-merged/2024-05-07.json):

```
gopls/bug
golang.org/x/tools/gopls/internal/util/bug.report:+35
golang.org/x/tools/gopls/internal/util/bug.Errorf:+2
golang.org/x/tools/gopls/internal/cache.(*analysisNode)._import.func1:+41
sync.(*Once).doSlow:+5
sync.(*Once).Do:=65
golang.org/x/tools/gopls/internal/cache.(*analysisNode)._import:+1
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck.func2:+34
golang.org/x/tools/gopls/internal/cache.importerFunc.Import:+0
go/types.(*Checker).importPackage:+28
go/types.(*Checker).collectObjects.func1:+13
go/types.(*Checker).walkDecl:+9
go/types.(*Checker).walkDecls:=391
go/types.(*Checker).collectObjects:+42
go/types.(*Checker).checkFiles:+18
go/types.(*Checker).Files:=304
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck:+115
```
```
golang.org/x/tools/gopls@v0.15.3 go1.20.13 linux/amd64 vscode (1)
```

Issue created by golang.org/x/tools/gopls/internal/telemetry/cmd/stacks.

**Comment by adonovan** [comment]
This stack `rcxYpg` was [reported by telemetry](https://storage.googleapis.com/prod-telemetry-merged/2024-06-03.json):

```
gopls/bug
golang.org/x/tools/gopls/internal/util/bug.report:+35
golang.org/x/tools/gopls/internal/util/bug.Errorf:+2
golang.org/x/tools/gopls/internal/cache.(*analysisNode)._import.func1:+41
sync.(*Once).doSlow:+5
sync.(*Once).Do:=65
golang.org/x/tools/gopls/internal/cache.(*analysisNode)._import:+1
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck.func2:+34
golang.org/x/tools/gopls/internal/cache.importerFunc.Import:+0
go/types.(*Checker).importPackage:+28
go/types.(*Checker).collectObjects.func1:+10
go/types.(*Checker).walkDecl:+9
go/types.(*Checker).walkDecls:=383
go/types.(*Checker).collectObjects:+42
go/types.(*Checker).checkFiles:+18
go/types.(*Checker).Files:=307
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck:+115
```
```
golang.org/x/tools/gopls@v0.15.3 go1.19.6 linux/amd64 vscode (1)
```

Issue created by golang.org/x/tools/gopls/internal/telemetry/cmd/stacks.

**Comment by adonovan** [comment]
This stack `MCkoAw` was [reported by telemetry](https://storage.googleapis.com/prod-telemetry-merged/2024-08-09.json):

```
gopls/bug
golang.org/x/tools/gopls/internal/util/bug.report:+35
golang.org/x/tools/gopls/internal/util/bug.Errorf:+2
golang.org/x/tools/gopls/internal/cache.(*analysisNode)._import.func1:+41
sync.(*Once).doSlow:+5
sync.(*Once).Do:=67
golang.org/x/tools/gopls/internal/cache.(*analysisNode)._import:+1
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck.func2:+34
golang.org/x/tools/gopls/internal/cache.importerFunc.Import:+0
go/types.(*Checker).importPackage:+31
go/types.(*Checker).collectObjects.func1:+13
go/types.(*Checker).walkDecl:+9
go/types.(*Checker).walkDecls:=391
go/types.(*Checker).collectObjects:+42
go/types.(*Checker).checkFiles:+26
go/types.(*Checker).Files:+13
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck:+115
```
```
golang.org/x/tools/gopls@v0.16.1 go1.23rc2 linux/amd64 vscode-insiders (1)
```

Issue created by golang.org/x/tools/gopls/internal/telemetry/cmd/stacks.

**Comment by adonovan** [comment]
This stack `snYxVw` was [reported by telemetry](https://storage.googleapis.com/prod-telemetry-merged/2024-09-15.json):

- `gopls/bug`
- [`golang.org/x/tools/gopls/internal/util/bug.report:+35`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/util/bug/bug.go;l=109)
- [`golang.org/x/tools/gopls/internal/util/bug.Errorf:+2`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/util/bug/bug.go;l=61)
- [`golang.org/x/tools/gopls/internal/cache.(*analysisNode)._import.func1:+41`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/cache/analysis.go;l=591)
- [`sync.(*Once).doSlow:+5`](https://cs.opensource.google/go/go/+/go1.23.0:src/sync/once.go;l=76)
- [`sync.(*Once).Do:=67`](https://cs.opensource.google/go/go/+/go1.23.0:src/sync/once.go;l=67)
- [`golang.org/x/tools/gopls/internal/cache.(*analysisNode)._import:+1`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/cache/analysis.go;l=550)
- [`golang.org/x/tools/gopls/internal/cache.(*analysisNode)._import.func1.1.1:+1`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/cache/analysis.go;l=579)
- [`golang.org/x/sync/errgroup.(*Group).Go.func1:+3`](https://cs.opensource.google/go/x/sync/+/v0.8.0:errgroup/errgroup.go;l=78)
- `runtime.goexit:+0`
```
golang.org/x/tools/gopls@v0.16.2 go1.23.0 linux/amd64 vscode (2)
```

**Comment by adonovan** [comment]
This stack `4YkxZg` was [reported by telemetry](https://storage.googleapis.com/prod-telemetry-merged/2024-11-06.json):

- `gopls/bug`
- [`golang.org/x/tools/gopls/internal/util/bug.report:+35`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.1:gopls/internal/util/bug/bug.go;l=109)
- [`golang.org/x/tools/gopls/internal/util/bug.Errorf:+2`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.1:gopls/internal/util/bug/bug.go;l=61)
- [`golang.org/x/tools/gopls/internal/cache.(*analysisNode)._import.func1:+41`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.1:gopls/internal/cache/analysis.go;l=591)
- [`sync.(*Once).doSlow:+5`](https://cs.opensource.google/go/go/+/go1.23.0:src/sync/once.go;l=76)
- [`sync.(*Once).Do:+17`](https://cs.opensource.google/go/go/+/go1.23.0:src/sync/once.go;l=67)
- [`golang.org/x/tools/gopls/internal/cache.(*analysisNode)._import:+1`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.1:gopls/internal/cache/analysis.go;l=550)
- [`golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck.func2:+34`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.1:gopls/internal/cache/analysis.go;l=1034)
- [`golang.org/x/tools/gopls/internal/cache.importerFunc.Import:+0`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.1:gopls/internal/cache/check.go;l=2023)
- [`go/types.(*Checker).importPackage:+31`](https://cs.opensource.google/go/go/+/go1.23.0:src/go/types/resolver.go;l=166)
- [`go/types.(*Checker).collectObjects.func1:+13`](https://cs.opensource.google/go/go/+/go1.23.0:src/go/types/resolver.go;l=270)
- [`go/types.(*Checker).walkDecl:+9`](https://cs.opensource.google/go/go/+/go1.23.0:src/go/types/decl.go;l=404)
- `go/types.(*Checker).walkDecls:=391`
- [`go/types.(*Checker).collectObjects:+42`](https://cs.opensource.google/go/go/+/go1.23.0:src/go/types/resolver.go;l=257)
- [`go/types.(*Checker).checkFiles:+26`](https://cs.opensource.google/go/go/+/go1.23.0:src/go/types/check.go;l=464)
- [`go/types.(*Checker).Files:+13`](https://cs.opensource.google/go/go/+/go1.23.0:src/go/types/check.go;l=430)
- [`golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck:+115`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.1:gopls/internal/cache/analysis.go;l=1054)
```
golang.org/x/tools/gopls@v0.16.1 go1.23.0 linux/386 vscode (2)
```

**Comment by adonovan** [comment]
This stack `oKR_eA` was [reported by telemetry](https://telemetry.go.dev/data/2025-08-23):

- `gopls/bug`
- [`golang.org/x/tools/gopls/internal/util/bug.report:+35`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/util/bug/bug.go;l=109)
- [`golang.org/x/tools/gopls/internal/util/bug.Errorf:+2`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/util/bug/bug.go;l=61)
- [`golang.org/x/tools/gopls/internal/cache.(*analysisNode)._import.func1:+41`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/cache/analysis.go;l=591)
- [`sync.(*Once).doSlow:+5`](https://cs.opensource.google/go/go/+/go1.24.4:src/sync/once.go;l=78)
- [`sync.(*Once).Do:=69`](https://cs.opensource.google/go/go/+/go1.24.4:src/sync/once.go;l=69)
- [`golang.org/x/tools/gopls/internal/cache.(*analysisNode)._import:+1`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/cache/analysis.go;l=550)
- [`golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck.func2:+34`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/cache/analysis.go;l=1034)
- [`golang.org/x/tools/gopls/internal/cache.importerFunc.Import:+0`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/cache/check.go;l=2023)
- [`go/types.(*Checker).importPackage:+31`](https://cs.opensource.google/go/go/+/go1.24.4:src/go/types/resolver.go;l=167)
- [`go/types.(*Checker).collectObjects.func1:+13`](https://cs.opensource.google/go/go/+/go1.24.4:src/go/types/resolver.go;l=274)
- [`go/types.(*Checker).walkDecl:+9`](https://cs.opensource.google/go/go/+/go1.24.4:src/go/types/decl.go;l=397)
- `go/types.(*Checker).walkDecls:=384`
- [`go/types.(*Checker).collectObjects:+45`](https://cs.opensource.google/go/go/+/go1.24.4:src/go/types/resolver.go;l=261)
- [`go/types.(*Checker).checkFiles:+26`](https://cs.opensource.google/go/go/+/go1.24.4:src/go/types/check.go;l=486)
- [`go/types.(*Checker).Files:+13`](https://cs.opensource.google/go/go/+/go1.24.4:src/go/types/check.go;l=452)
- [`golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck:+115`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/cache/analysis.go;l=1054)
```
golang.org/x/tools/gopls@v0.16.2 go1.24.4 darwin/arm64 vscode (1)
```

**Comment by adonovan** [comment]
Found new stacks for predicate:
```
#!stacks
"bug.Errorf" &&
  ("cache.(*analysisNode)._import.func1:+41" || "cache.(*analysisNode)._import.func1:41")
```

This stack `cfCMrg` was [reported by telemetry](https://telemetry.go.dev/data/2026-02-09):

- `gopls/bug`
- [`golang.org/x/tools/gopls/internal/util/bug.report:+35`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/util/bug/bug.go;l=109)
- [`golang.org/x/tools/gopls/internal/util/bug.Errorf:+2`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/util/bug/bug.go;l=61)
- [`golang.org/x/tools/gopls/internal/cache.(*analysisNode)._import.func1:+41`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/cache/analysis.go;l=591)
- [`sync.(*Once).doSlow:+5`](https://cs.opensource.google/go/go/+/go1.20:src/sync/once.go;l=74)
- [`sync.(*Once).Do:+17`](https://cs.opensource.google/go/go/+/go1.20:src/sync/once.go;l=65)
- [`golang.org/x/tools/gopls/internal/cache.(*analysisNode)._import:+1`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/cache/analysis.go;l=550)
- [`golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck.func2:+34`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/cache/analysis.go;l=1034)
- [`golang.org/x/tools/gopls/internal/cache.importerFunc.Import:+0`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/cache/check.go;l=2023)
- [`go/types.(*Checker).importPackage:+28`](https://cs.opensource.google/go/go/+/go1.20:src/go/types/resolver.go;l=163)
- [`go/types.(*Checker).collectObjects.func1:+13`](https://cs.opensource.google/go/go/+/go1.20:src/go/types/resolver.go;l=267)
- [`go/types.(*Checker).walkDecl:+9`](https://cs.opensource.google/go/go/+/go1.20:src/go/types/decl.go;l=404)
- `go/types.(*Checker).walkDecls:=391`
- [`go/types.(*Checker).collectObjects:+42`](https://cs.opensource.google/go/go/+/go1.20:src/go/types/resolver.go;l=254)
- [`go/types.(*Checker).checkFiles:+18`](https://cs.opensource.google/go/go/+/go1.20:src/go/types/check.go;l=326)
- [`go/types.(*Checker).Files:=304`](https://cs.opensource.google/go/go/+/go1.20:src/go/types/check.go;l=304)
- [`golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck:+115`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/cache/analysis.go;l=1054)
```
golang.org/x/tools/gopls@v0.16.2 go1.20 windows/386 gopls.client=other (1)
```

Use this command to reproduce the executable:
`(HOME=$(mktemp -d); GOOS=windows GOARCH=386 GOTOOLCHAIN=go1.20 go install golang.org/x/tools/gopls@v0.16.2 && find $HOME/go/bin -type f)`
To disassemble: `go tool objdump exe | less`
