### ISSUE TITLE
x/tools/gopls: SignatureHelp bug reported by telemetry

### ISSUE THREAD

**Issue by adonovan** [golang/go#64245]
This stack `S-zlGg`, `_mSPWg` was [reported by telemetry](https://storage.googleapis.com/prod-telemetry-merged/2023-11-12.json):

[SignatureHelp:72](https://cs.opensource.google/go/x/tools/+/refs/tags/gopls/v0.14.1:gopls/internal/lsp/source/signature_help.go;l=93) is
```
return nil, 0, bug.Errorf("call to unexpected built-in %v (%T)", obj, obj)
```

```
gopls/bug
golang.org/x/tools/gopls/internal/bug.report:35
golang.org/x/tools/gopls/internal/bug.Errorf:2
golang.org/x/tools/gopls/internal/lsp/source.SignatureHelp:72
golang.org/x/tools/gopls/internal/lsp.(*Server).signatureHelp:9
golang.org/x/tools/gopls/internal/lsp.(*Server).SignatureHelp:1
golang.org/x/tools/gopls/internal/lsp/protocol.serverDispatch:490
golang.org/x/tools/gopls/internal/lsp/protocol.ServerHandler.func1:5
golang.org/x/tools/gopls/internal/lsp/lsprpc.handshaker.func1:52
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1:2
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2:3
runtime.goexit:0
```
```
golang.org/x/tools/gopls@v0.14.1 go1.19.1 darwin/amd64 (1)
```

Reported using golang.org/x/tools/gopls/internal/telemetry/cmd/stacks.

**Comment by adonovan** [comment]
Dup of #63804, already fixed.

**Comment by adonovan** [comment]
How can a closed (fixed) issue be closed again as not planned? That's confusing.

**Comment by findleyr** [comment]
Oh, I'm just going through marking dupes as "not planned" instead of "completed", for tracking purposes.

Are you just commenting on how Github reports this state change? I agree it is confusing.
