### ISSUE TITLE
access: approvers 

### ISSUE THREAD

**Issue by qiulaidongfeng** [golang/go#64255]
Hi,

See https://golang.org/wiki/GerritAccess

I'd like to request "approvers" access.

I see many times like https://go-review.googlesource.com/c/go/+/539579 such trivial and obviously right change CL, I used to vote codereview + 1 promote the review process of this kind of CL.
I want to be able to vote codereview+2 to approve this kind of CL.

Gerrit user: https://go-review.googlesource.com/q/author:2645477756@qq.com

**Comment by qiulaidongfeng** [comment]
@gopherbot add NeedsDecision

**Comment by qiulaidongfeng** [comment]
cc @golang/release

**Comment by qiulaidongfeng** [comment]
No updates here?

**Comment by qiulaidongfeng** [comment]
cc @golang/release

**Comment by qiulaidongfeng** [comment]
Maybe I should CC on Monday?
cc @golang/release

**Comment by prattmic** [comment]
Apologies for the delay in reviewing this request, our notifications about this request got missed.

Thanks for your contributions and making this access request. The "approvers" access permits reviewing and submitting CLs across the entire Go project as documented https://go.dev/wiki/GerritAccess#approving-cls-approvers, so it needs a longer history of contributions and demonstrated familiarity with the Go project before granting access can be considered. It looks like you're off to a strong start, but it's still early. I'm going to close this for now, but please keep up the good work and feel free to reapply at a later time.
