### ISSUE TITLE
x/tools/gopls: Complete return as a snippet

### ISSUE THREAD

**Issue by vikblom** [golang/go#64266]
### Feature suggestion
It would be convenient if the return keyword could be completed as a snippet that pre-populates the zero values of return parameters. 

For example
```
func foo() (string, err) {
    ret<TAB>
}
```
would turn into
```
func foo() (string, err) {
    return "", nil
}
```
with the snippet cursor over "" and nil respectively.

Currently the keyword is only completed to a plain `return`. This could be an alternative completion ranked one step lower.

**Comment by muirdm** [comment]
Note there is some logic to write a "return" snippet with zero values [here](https://github.com/golang/tools/blob/98b4b1465a8eaf97f19c711ed90a25473be6d268/gopls/internal/lsp/source/completion/statements.go#L292C18-L292C22). This proposed completion could work in a similar way to that linked completion.

**Comment by findleyr** [comment]
Thanks @vikblom and @muirdm!

I have tentatively put this in the gopls@v0.16.0 milestone, just for our own tracking purposes. You are course free to do as little or as much as you want, whenever you want :)

**Comment by findleyr** [comment]
This was fixed by https://go.dev/cl/546775

(the commit message said "Closes" instead of "Fixes").

**Comment by rogeryk** [comment]
Hi, I'm sorry for commenting so late. If "err" exists, should it be used first to instead "nil"? I think this is more common.

**Comment by vikblom** [comment]
Hi @rogeryk 

That is a valid point. I decided against it, keeping the zero value even for the error, to keep the implementation simple. 

The end user might want err, fmt.Errorf, errors.New, or some local variant thereof (which is what I almost always use). My reasoning was that since the placeholder almost surely needs to be replaced anyway, it doesn't hurt that it is nil.
