### ISSUE TITLE
cmd/compile: missing "imported and not used" error for dot-import

### ISSUE THREAD

**Issue by griesemer** [golang/go#6428]
<pre>cat x.go
package main

import . &quot;testing&quot;  // declares T in file scope

type S struct {
     T int
}

func main() {
     _ = S{T: 0}
}

go tool 6g x.go produces no error. However, it should complain with:

x.go:3: imported and not used: &quot;testing&quot;

Note that changing the assignment in main to:

     _ = S{}

produces the expected error (actually, a slightly confused error message, see issue also
6420).
The &quot;T&quot; in S{T: 0} is not the same T as the one imported.</pre>

**Comment by griesemer** [comment]
Moving to 1.11 to make it visible.

**Comment by griesemer** [comment]
Nor urgent.

**Comment by mdempsky** [comment]
Fixed on dev.regabi.
