### ISSUE TITLE
go/types: Scope.Innermost is incorrect for type parameters

### ISSUE THREAD

**Issue by adonovan** [golang/go#64295]
Scope.Innermost should return the innermost lexical environment block (Scope) for an identifier, but it returns the wrong answer for references to type parameters outside the function body, because the position of the type parameter is not in the pos-end range of the function body scope.

This problem is not a blocker for gopls, only a problem for the test case in  https://go.dev/cl/544035.
The fix for this issue will allow us to remove the  "continue if name is U" statement.

**Comment by griesemer** [comment]
Marking for 1.22 for visibility, in case we get to it. Not a release blocker.
