### ISSUE TITLE
runtime: mysterious bit set of a high order bit causes segfaults and bounds check failures

### ISSUE THREAD

**Issue by findleyr** [golang/go#64290]
```
#!watchflakes
post <- goarch == "ppc64" && ((log ~ `SIGSEGV` && log ~ `0x0x8000`) || (log ~ `runtime error: index out of range`))
```

New segfault found in the gopls tests.

<details><summary>2023-11-20 18:35 linux-ppc64-sid-buildlet tools@8966034e go@ddb38c3f x/tools/gopls/internal/regtest/marker (<a href="https://build.golang.org/log/456ffbdb51dd4743c6bafc3e8ac7587ce459c47b">log</a>)</summary>

    SIGSEGV: segmentation violation
    PC=0x28e6c m=9 sigcode=3 addr=0x800000000b53940
    
    goroutine 0 gp=0xc00070fa00 m=9 mp=0xc000744008 [idle]:
    runtime.(*mspan).typePointersOfUnchecked(0xc00b8b0000?, 0xc00b959d70?)
    	/workdir/go/src/runtime/mbitmap_allocheaders.go:202 +0x4c fp=0xc000fade38 sp=0xc000faddf8 pc=0x28e6c
    runtime.scanobject(0xc00b8b0000, 0xc00004fc48)
    	/workdir/go/src/runtime/mgcmark.go:1446 +0xcc fp=0xc000faded0 sp=0xc000fade38 pc=0x360fc
    runtime.gcDrainN(0xc00004fc48, 0x10000)
    	/workdir/go/src/runtime/mgcmark.go:1331 +0x1f0 fp=0xc000fadf10 sp=0xc000faded0 pc=0x35e30
    ...
    r18  0xc00004ea08	r19  0xc000050a30
    r20  0xa8	r21  0xc000744008
    r22  0xc000faa3a0	r23  0xc000fadeb8
    r24  0x5a	r25  0xf0
    r26  0xc0129eaa1b	r27  0xc0129eaa17
    r28  0x0	r29  0xc000050a28
    r30  0xc00070fa00	r31  0x360fc
    pc   0x28e6c	ctr  0x7fff9bdf04d0
    link 0x360fc	xer  0x20000000
    ccr  0x44428084	trap 0x380
</details>

— [watchflakes](https://go.dev/wiki/Watchflakes)

_Originally posted by @gopherbot in https://github.com/golang/go/issues/63736#issuecomment-1819714566_

**Comment by findleyr** [comment]
CC @mknyszek

**Comment by mknyszek** [comment]
Interesting, it's segfaulting on the type pointer. That pointer also doesn't look like it's nil, either, which makes this very odd.

So far it looks like this has only failed on linux-ppc64? Is that right?

**Comment by findleyr** [comment]
@mknyszek that's the only failure I've observed, but it might be worth checking with greplogs.

**Comment by mknyszek** [comment]
Hey @golang/ppc64, is there something special about where the type metadata (from the binary) is placed in the address space? i.e. does `0x800000000b53940` look like it could plausibly be a type pointer, or does it look completely bogus?

**Comment by mknyszek** [comment]
@findleyr Thanks. `greplogs` shows nothing else as well.

**Comment by pmur** [comment]
I'd err on the side of bogus. I think mapped memory usually falls below `0x8000000000000000` on PPC64 in most cases. ppc64/linux doesn't support PIC, so all static data/text should occupy fairly low addresses starting at `0x10000`.

**Comment by mknyszek** [comment]
There was another failure, this time unrelated to typePointersOfUnchecked, with a similar segfault on a similar address. This makes me think it's more general memory corruption.

https://build.golang.org/log/cbb742b677c36b578951d0a9b5589c1dc223a1c1

**Comment by mknyszek** [comment]
Here's another: https://build.golang.org/log/2e1a99a1002b4c9ff4b2eda9186e89a362194211

**Comment by mknyszek** [comment]
The high bit that seems to be set is the 60th bit? Why does that sound familiar...

**Comment by mknyszek** [comment]
It looks like #64294 is related. There's a weird integer found in a slice that also seems to have *some* high bit set. (134217730 is 0x8000002 in hex.)

After letting this soak for a bit, I'm starting to become convinced this is a ppc64-specific issue with high bits being set. Maybe a subtle miscompilation somewhere?

**Comment by mknyszek** [comment]
All the newly attached failures seem to have a random bit set. Two of them are more obvious than others, but even the one that looks most like "oh maybe that's just garbage" does end up at the upper end of a valid index by flipping the top bit. Perhaps that's just confirmation bias, but it doesn't *not* fit the pattern. :P

**Comment by randall77** [comment]
You are definitely *not* incorrect.

**Comment by mknyszek** [comment]
@pmur Your comment makes me realize this has only appeared on linux-ppc64-buildlet. Perhaps a long-shot, but how hard would it be to determine if the failures were only happening on one particular machine? IIRC there are only 5 such machines. What's the chance of faulty hardware?

(This would be easy to check and rule out on LUCI, but we haven't set up the ppc64 machines there yet, only the ppc64le machines.)

**Comment by pmur** [comment]
That is easy, fortunately. All 5 instances are running on a resource restricted container within the same VM.

**Comment by laboger** [comment]
It's possible this problem could be related to the BE memcombine issue that was fixed here https://go.dev/cl/546355.

**Comment by mknyszek** [comment]
It looks like there haven't been more of these failures since? I think it's reasonable this is related to the big endian memcombine issue. I'm gonna close this optimistically. Please comment if you disagree.

**Comment by laboger** [comment]
I agree this was the likely culprit, since the time frame for when it started seemed consistent with the initial memcombine change, only happened on BE and has not happened since the memcombine fix went int.

**Comment by pmur** [comment]
When I instrumented the memcombine fix, I only observed one code different in some darwin debug code. I did not see any in the failing tests.

**Comment by pmur** [comment]
The recent two failures are not related. The luci container seems to collect zombie processes, I thought I had updated it to start the container with `--init`, but I must have missed the ppc64 builder.

**Comment by mknyszek** [comment]
@pmur Am I understanding right that there's nothing else to do here then? Closing optimistically, thanks.
