### ISSUE TITLE
cmd/go/internal/test: Documentation about "package's source root" is imprecise.

### ISSUE THREAD

**Issue by your-diary** [golang/go#64303]
<pre>
$ go version
1.21.4
</pre>

In [the documentation of `test` package](https://pkg.go.dev/cmd/go/internal/test#pkg-variables), it is said

> Tests that open files within the package's source root (usually `$GOPATH`) or that consult environment variables only match future runs in which the files and environment variables are unchanged.

However, is "the package's source root" really usually `$GOPATH` (e.g. `~/go`)?

**Comment by mknyszek** [comment]
AFAICT this is internal documentation, so it's not really intended to be user-facing. I think this question is more appropriate for the [golang-dev](https://groups.google.com/g/golang-dev) mailing list.

That being said, I'm not sure what the right thing here is. CC @bcmills 

Closing this issue for now. Thanks for flagging this.

**Comment by bcmills** [comment]
I think this issue is about the string displayed by `go help test`, not the package doc comment.

**Comment by bcmills** [comment]
@your-diary, these days the package's source root is usually the module that contains it. (The comment is out of date.)
