### ISSUE TITLE
x/playground: invalid output when using slices of length >  1e6

### ISSUE THREAD

**Issue by Nasfame** [golang/go#64339]
### What version of Go are you using (`go version`)?

<pre>
$ go version
gotip
</pre>

### Does this issue reproduce with the latest release?

yes, go1.20, go1.21, gotip

### What did you do?

https://go.dev/play/p/Rkc3h35UsSm?v=gotip

### What did you expect to see?

```
last slice 9999999
end
```

### What did you see instead?
```
Program exited.
```

**Comment by seankhliao** [comment]
works for me?

**Comment by Nasfame** [comment]
Fine no worries
