### ISSUE TITLE
Not able to install go packages using `go install <package>`

### ISSUE THREAD

**Issue by maths-lover** [golang/go#64348]
### Go version

go version go1.21.4 linux/amd64

### Reproducibility

- [X] Does this issue reproduce with the latest release?

### What operating system and processor architecture are you using (`go env`)?

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN='/mnt/dev/go/bin'
GOCACHE='/home/maths-lover/.cache/go-build'
GOENV='/home/maths-lover/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/mnt/dev/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/mnt/dev/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/lib/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/lib/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.4'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build959285989=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

Trying to install packages using `go install`, for example,

```go install golang.org/x/tools/gopls@latest```

### What did you expect to see?

Install the package as binary without an issue

### What did you see instead?

Unable to fetch the source code itself to build the binary.

```go: golang.org/x/tools/gopls@latest: module golang.org/x/tools/gopls: Get "https://proxy.golang.org/golang.org/x/tools/gopls/@v/list": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:49515->[::1]:53: read: connection refused```

**Comment by seankhliao** [comment]
That's a local DNS issue on your computer, not something for Go.

**Comment by maths-lover** [comment]
But then that should mean it will fail for anything regardless of go version.
When I re-tried with go version 1.20.11 it would install with no issues

Also if I ping to proxy.golang.org in my terminal it'd resolve the IP and will make ping requests successfully

What am I missing here?

**Comment by maths-lover** [comment]
I am extermely sorry about opening this issue in this first place, I should have dug bit more into DNS resolution.
I am on archlinux and using iwd with systemd-resolved, and any software that uses glibc's getaddrinfo will work out of the box and other programs like Go use /etc/resolv.conf to resolve DNS and I didn't have it in place hence this issue

So to fix this issue, all I  had to do was use the stub method to symlink systemd-resolved stub to `/etc/resolv.conf`

More details here: https://wiki.archlinux.org/title/Systemd-resolved#DNS

Thank you @seankhliao for closing it faster as this issue was really unnecessary.
