### ISSUE TITLE
proxy.golang.org: 

### ISSUE THREAD

**Issue by Pro7ech** [golang/go#64362]
The commands `$ go get github.com/tuneinsight/lattigo@latest` and `$ go get github.com/tuneinsight/lattigo`  fetch lattigo `v1.3.1` whereas the latest version is `v5.0.0`.

https://github.com/tuneinsight/lattigo

**Comment by mvdan** [comment]
You're missing the `/v5` suffix.

The Go project doesn't use the issue tracker for questions. See https://golang.org/wiki/Questions.
