### ISSUE TITLE
suggestion: migrate lang change issue template to  golang/proposal

### ISSUE THREAD

**Issue by Nasfame** [golang/go#64367]
## Background

I think its best to restrict this repo to Go 1.x.x proposals. 

## Summary

- [ ] Migrate https://github.com/golang/go/blob/master/.github/ISSUE_TEMPLATE/11-language-change.yml to  https://golang/proposal

- [ ] Update language-change.yml to redirect to  golang/proposal/issues ...

**Comment by seankhliao** [comment]
The go project uses a single issue tracker for all its repos, there's no point in spreading it out elsewhere.
