### ISSUE TITLE
go 1.22 changed escaping of backslash/formfeed characters

### ISSUE THREAD

**Issue by vangent** [golang/go#64369]
### Go version

go version go1.22-20230908-RC04

### Reproducibility

- [X] Does this issue reproduce with the latest release?

### What operating system and processor architecture are you using (`go env`)?

```shell
GO111MODULE='on'
GOARCH='amd64'
GOBIN=''
GOCACHE='/usr/local/google/home/rvangent/.cache/go-build'
GOENV='/usr/local/google/home/rvangent/.config/go/env'
GOEXE=''
GOEXPERIMENT='fieldtrack,boringcrypto'
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/usr/local/google/home/rvangent/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/usr/local/google/home/rvangent/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/lib/google-golang'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/lib/google-golang/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22-20230908-RC04 cl/563875016 +2fe2f08542 X:fieldtrack,boringcrypto'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2560957334=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

I have an external github repository, Go CDK, that uses [github.com/google/go-replayers/](https://www.google.com/url?q=http://github.com/google/go-replayers/&sa=D&source=buganizer&usg=AOvVaw0uNwVOt0zU8ibdowrhzTkP) to  do record/replay tests.

It consistently passes on go 1.21, and consistently fails on go 1.22.

To reproduce, fork [https://github.com/google/go-cloud](https://www.google.com/url?q=https://github.com/google/go-cloud&sa=D&source=buganizer&usg=AOvVaw24q8XnXPj6NKPiaZvNk1zu) and run

```
cd blob/gcsblob
go test -v --run TestConformance/TestKeys/ascii-1
```

The test fails because it tries to match an outgoing HTTP request against what's recorded in the replay file, but can't find a match. I dug under the covers a bit and found that the difference is due to how the backslash character is escaped.

In go 1.22, the HTTP body looks like:

```
{"bucket":"go-cloud-blob-test-bucket","contentType":"text/plain; charset=utf-8","md5Hash":"XUFAKrxLKna5cZ2REBfFkg==","name":"weird-keys\u0000\u00
01\u0002\u0003\u0004\u0005\u0006\u0007\b\t__0xa__\u000b\f__0xd__\u000e\u000f"}
```

while in go 1.21 it looks like

```
{"bucket":"go-cloud-blob-test-bucket","contentType":"text/plain; charset=utf-8","md5Hash":"XUFAKrxLKna5cZ2REBfFkg==","name":"weird-keys\u0000\u00
01\u0002\u0003\u0004\u0005\u0006\u0007\u0008\t__0xa__\u000b\u000c__0xd__\u000e\u000f"}
```

The difference appears to be in the escaping of the backslash character, from "\u0008" to "\b", and the formfeed character, from "\u000c" to "\f".

Is this change intentional?

### What did you expect to see?

I expect the new Go version to not change how these characters are escaped.

### What did you see instead?

See above.

**Comment by seankhliao** [comment]
it is intentional, see [CL 521675](https://go.dev/cl/521675)
