### ISSUE TITLE
godoc: unsupported plugins pkg documented for GOOS=windows 

### ISSUE THREAD

**Issue by Nasfame** [golang/go#64388]
https://pkg.go.dev/plugin?GOOS=windows

Plugins are currently supported only on Linux, FreeBSD, and macOS. Hence the documentation is not necessary for windows & js/wasm.

The documentation can be misleading for developers building apps for windows.

**Comment by seankhliao** [comment]
the docs are generated according to build tags, this is working as expected.

**Comment by Nasfame** [comment]
@seankhliao build tag is missing for **plugin.go**.
