### ISSUE TITLE
Erroneous documentation in the first example of "Using Go Modules"

### ISSUE THREAD

**Issue by michael-esusu** [golang/go#64383]
### What is the URL of the page with the issue?

https://go.dev/blog/using-go-modules

### What is your user agent?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

### Screenshot

![image](https://github.com/golang/go/assets/102369461/4ac57349-be02-45af-b31e-5a01bd63a032)

![image](https://github.com/golang/go/assets/102369461/d67cce8a-067e-411c-b32f-0084723f31e0)

### What did you do?

I followed the instructions to create a new project

### What did you expect to see?

![image](https://github.com/golang/go/assets/102369461/ef027c31-d825-4a3a-9d9a-32784d35ef0e)

### What did you see instead?

![image](https://github.com/golang/go/assets/102369461/e5d60206-f059-42d2-86f9-ba29fa830564)

**Comment by seankhliao** [comment]
it's a blog post from 4 years ago, it was correct at that point in time.
the getting started guides are kept up to date: https://go.dev/doc/

**Comment by michael-esusu** [comment]
Thanks for the rapid response, Sean!
