### ISSUE TITLE
cmd/compile: spurious `not a slice` error when calling `unsafe.SliceData` on a type-parameterized slice

### ISSUE THREAD

**Issue by bcmills** [golang/go#64406]
### Go version

Go 1.21 (playground)

### What operating system and processor architecture are you using (`go env`)?

```shell
playground
```

### What did you do?

https://go.dev/play/p/1onZLUkD_VX

### What did you expect to see?

successful compilation

### What did you see instead?

```
./prog.go:8:26: invalid argument: s (variable of type S constrained by ~[]E) is not a slice
```

But it clearly _is_ a slice, because (according to the same error message) it is constrained by `~[]E`.

(attn @griesemer)

**Comment by mdempsky** [comment]
Confirmed with `-gcflags=-h` this is a types2 error.

**Comment by cuonglm** [comment]
This happens with `unsafe.Slice`, too:

```
package main

import (
	"unsafe"
)

func sliceData[E any, S ~[]E](s S) *E {
	return unsafe.SliceData(s)
}

func slice[E any, S ~*E](s S) []E {
	return unsafe.Slice(s, 0)
}

func main() {
	s := []uint32{0}
	_ = sliceData(s)
	_ = slice(&s)
}
```

**Comment by griesemer** [comment]
I just point out that the spec doesn't allow type parameter arguments for these functions.
It probably should, so this is fine to fix, but we also need to update the spec.
