### ISSUE TITLE
x/sys/unix: Missing Netfilter and NFTables constants

### ISSUE THREAD

**Issue by LionelJouin** [golang/go#64426]
### Go version

go version go1.21.1 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/lionelj/.cache/go-build'
GOENV='/home/lionelj/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/lionelj/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/lionelj/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.1'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1866483795=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

Try to use the NFtables constants (e.g. `unix.NFT_QUEUE_FLAG_BYPASS`) and the Netfilter constants (e.g. `unix.NF_NAT_RANGE_PROTO_RANDOM`).

These constants are used with netfilter:
* https://wiki.nftables.org/wiki-nftables/index.php/Performing_Network_Address_Translation_(NAT) (e.g. See NAT flags section).
* https://wiki.nftables.org/wiki-nftables/index.php/Quick_reference-nftables_in_10_minutes (e.g. See Queue section).

### What did you expect to see?

Being able to use constants from `linux/netfilter/nf_tables.h` and from `linux/netfilter/nf_nat.h`. This would add 54 constants with `NF_NAT_` and `NFT_` excluding `NFT_META_IIFTYPE` since it is already imported from [nf_tables.h#951](https://github.com/torvalds/linux/blob/v6.6/include/uapi/linux/netfilter/nf_tables.h#L951).

### What did you see instead?

Compiler error: `undefined: unix.NFT_QUEUE_FLAG_BYPASS`

**Comment by dmitshur** [comment]
CC @tklauser, @golang/runtime.
