### ISSUE TITLE
log/slog: LevelTrace

### ISSUE THREAD

**Issue by 3052** [golang/go#64439]
### Proposal Details

would look like this, along with the current options:

~~~go
const (
   LevelTrace Level = -8
   LevelDebug Level = -4
   LevelInfo  Level = 0
   LevelWarn  Level = 4
   LevelError Level = 8
)
~~~

its already referenced here:

https://godocs.io/log/slog#example-HandlerOptions-CustomLevels

and I think it would be a helpful addition.

**Comment by seankhliao** [comment]
see https://github.com/golang/go/issues/56345#issuecomment-1322347914
