### ISSUE TITLE
access: request to add myself as a member to port-maintainers/s390x team.

### ISSUE THREAD

**Issue by Vishwanatha-HD** [golang/go#64445]
Hi @bcmills 
Request you to add myself as a member to the port-maintainers/s390x team.
Somehow, my name has been taken out and I am not getting any of the updates and mails.
Request your help and support here.. Thanks.. 

_Originally posted by @Vishwanatha-HD in https://github.com/golang/go/issues/56216#issuecomment-1278921199_

**Comment by dmitshur** [comment]
Thanks, I've sent a pending invitation to rejoin that you'll need to accept.

**Comment by Vishwanatha-HD** [comment]
@dmitshur.. Thanks for your response on this.. 
I was part of the "golang" repo.. But my name is not showing up as part of the go maintainers for s390x..
I am also the maintainer for s390x along with Srinivas.Pokala.. 

So, request you to add to the s390x maintainers list..

i.e. here.. https://github.com/orgs/golang/teams/s390x

**Comment by dmitshur** [comment]
The GitHub team https://github.com/orgs/golang/teams/s390x is where I've sent the invite.
It currently shows "1 pending member", and your GitHub account is listed:

<img width="577" alt="image" src="https://github.com/golang/go/assets/1924134/6d9f4a7a-0b63-42c2-ae9c-d1b95a314c00">

Can you check if you received an invite email, or perhaps it went to a spam folder?
Or maybe your GitHub account email needs to be updated?

**Comment by Vishwanatha-HD** [comment]
I got the invitation, but that was to rejoin for "@golang organization"... 
I didnt get any invitation for rejoining myself for go s390x maintainership..

**Comment by Vishwanatha-HD** [comment]
https://github.com/orgs/golang/teams/s390x

Above link is not accessible to me for now..

**Comment by Vishwanatha-HD** [comment]
Yes.. I requested the golang organization request and I am part of that now.. 

But, I am still not part of the go-s390x maintainers list.. So, any help regarding this would be greatly appreciated. Thanks..

**Comment by dmitshur** [comment]
> Yes.. I requested the golang organization request and I am part of that now..

Can you share a screenshot of what that looks like from your end? Is "Vishwanatha-HD" the right username? I'm not seeing it in the "golang" organization on my side.

**Comment by Vishwanatha-HD** [comment]
Finally I got added to go-s390x maintainers list.. Thanks alot @dmitshur for your help and support... !!

![image](https://github.com/golang/go/assets/110028703/6dbcb83e-643b-483a-97ee-8a8bb65b7874)
