### ISSUE TITLE
x/net/html: removing first child node of pre causes doubling of newline at beginning of following text node

### ISSUE THREAD

**Issue by matloob** [golang/go#64481]
### Go version

go version go1.21.4 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?

```shell
GO111MODULE='on'
GOARCH='amd64'
GOBIN=''
GOCACHE='/Users/matloob/Library/Caches/go-build'
GOENV='/Users/matloob/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/matloob/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/matloob/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/darwin_amd64'
GOVCS=''
GOVERSION='go1.21.4'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/matloob/pkgsite/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/qb/r47yxsb14sx6nz0m6_1pglm8004_sl/T/go-build411072747=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

I ran the following program: https://go.dev/play/p/ywoeY3SDD87 pasted below
```
package main

import (
	"bytes"
	"fmt"
	"log"
	"strings"

	"golang.org/x/net/html"
)

func main() {
	doc, err := html.Parse(strings.NewReader("<pre><img/>\ntext\n</pre>"))
	if err != nil {
		log.Fatal(err)
	}
	pre := doc.FirstChild.LastChild.FirstChild

	fmt.Println("before:")
	var buf bytes.Buffer
	html.Render(&buf, pre)
	fmt.Println(buf.String())

	pre.RemoveChild(pre.FirstChild) // Remove the <img/> tag

	fmt.Println("after:")
	buf.Reset()
	html.Render(&buf, pre)
	fmt.Println(buf.String())
}
```

### What did you expect to see?

```
before:
<pre><img/>
text
</pre>
after:
<pre>
text
</pre>
```

### What did you see instead?

```
before:
<pre><img/>
text
</pre>
after:
<pre>

text
</pre>
```

**Comment by dmitshur** [comment]
CC @neild, @ianlancetaylor.

**Comment by rsc** [comment]
CC @nigeltao if you are interested

**Comment by nigeltao** [comment]
Yeah, in the "after" case, inserting the newline is deliberate (Working As Intended):

https://github.com/golang/net/blob/08a78b1eeae5f15e658ca8972aa74b6857e3b37b/html/render.go#L187-L195

If you delete those lines of code, the tests will fail. For example, this WebKit test case should produce a `"\nfoo"` text node with [exactly one leading `'\n'`](https://github.com/golang/net/blob/08a78b1eeae5f15e658ca8972aa74b6857e3b37b/html/testdata/webkit/tests3.dat#L86-L87), even though [the input](https://github.com/golang/net/blob/08a78b1eeae5f15e658ca8972aa74b6857e3b37b/html/testdata/webkit/tests3.dat#L76-L78) has two.

---

Per the [WHATWG HTML spec](https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-inbody) (see: A start tag whose tag name is one of: "pre", "listing"), a `'\n'` immediately after a `<pre>` would be ignored. In your example code, to keep the Text Node's text being `"\ntext\n"` (with a leading `'\n'`), the renderer inserts an extra one.
