### ISSUE TITLE
x/tools/gopls: rename should also handle references in godoc links

### ISSUE THREAD

**Issue by dolmen** [golang/go#64495]
### Go version

go version go1.21.4 darwin/arm64

### What operating system and processor architecture are you using (`go env`)?

```shell
gopls v0.14.2
```

### What did you do?

Renaming the `FuncA` function should also change the godoc link in `FuncB` documentation.
```go
func FuncA() {
}

// FuncB is same as [FuncB].
func FuncB() {
}
```

### What did you expect to see?

godoc link replaced with the reference to the new name of FuncA.

### What did you see instead?

`FuncA` is still referenced but the symbol doesn't exist anymore. The documentation is now inconsistent (dangling link).

**Comment by findleyr** [comment]
Agreed, gopls should do this, at least within a single package. CC @adonovan 

This is a good medium-difficulty project for someone to work on, but we'll try to get to it in gopls@v0.16.0 if nobody else is interested.

**Comment by rogeryk** [comment]
@findleyr Hi, I want try this.

**Comment by findleyr** [comment]
Great, please go ahead!
Source is in `gopls/internal/lsp/source/rename.go` (see `docComment`).
Tests are in `gopls/internal/test/marker', with documentation in the package documentation: https://pkg.go.dev/golang.org/x/tools/gopls/internal/test/marker
(There are more rename tests in `gopls/internal/test/integration`, but for this work you will probably only need a marker test).
