### ISSUE TITLE
x/tools/gopls: marker tests are broken on small machines

### ISSUE THREAD

**Issue by findleyr** [golang/go#64496]
It looks like https://go.dev/cl/546255 somehow broke the `testenv.ExitIfSmallMachine` skip, and now tests are broken on small builders:

```
skipping test: assuming that android is resource-constrained
--- FAIL: Test (0.00s)
panic: unexpected call to os.Exit(0) during test [recovered]
	panic: unexpected call to os.Exit(0) during test
```

CC @adonovan

**Comment by findleyr** [comment]
Oh, the call to ExitIfSmallMachine was moved from TestMain to Test. I'll fix.

**Comment by adonovan** [comment]
> Oh, the call to ExitIfSmallMachine was moved from TestMain to Test. I'll fix.

Sorry about that; I forgot that it's not a simple skip.
