### ISSUE TITLE
make slice memory leak

### ISSUE THREAD

**Issue by zhaoya881010** [golang/go#64491]
### Go version

go version go1.12 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

```shell
set GOARCH=amd64
set GOBIN=
```

### What did you do?

go tool pprof -- alloc_space 
Why is the memory continuously increasing?
![image](https://github.com/golang/go/assets/4704280/c6243de1-f2ed-4d85-844c-62174d36c3ab)

![image](https://github.com/golang/go/assets/4704280/0f6288ed-0e3b-40c0-a1b5-ca4d1d5aafff)

### What did you expect to see?

memory 

### What did you see instead?

memory

**Comment by merykitty** [comment]
`-alloc_space` measures the total size of objects ever created, of course it keeps growing, for live objects check `-inuse_space` instead.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
