### ISSUE TITLE
compile: error on go version 1.0 in go.mod

### ISSUE THREAD

**Issue by dveeden** [golang/go#64494]
### Go version

go version devel go1.22-446a5dcf Thu Nov 30 20:05:58 2023 +0000 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/dvaneeden/.cache/go-build'
GOENV='/home/dvaneeden/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/dvaneeden/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/dvaneeden/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/home/dvaneeden/sdk/gotip'
GOSUMDB='sum.golang.org'
GOTMPDIR='/home/dvaneeden/go/tmp'
GOTOOLCHAIN='auto'
GOTOOLDIR='/home/dvaneeden/sdk/gotip/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='devel go1.22-446a5dcf Thu Nov 30 20:05:58 2023 +0000'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/dvaneeden/dev/gofslock/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/home/dvaneeden/go/tmp/go-build4148443160=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

I tried to build github.com/danjacques/gofslock with gotip (`go version devel go1.22-446a5dcf Thu Nov 30 20:05:58 2023 +0000 linux/amd64`)

```
$ gotip build ./...
# github.com/danjacques/gofslock/fslock
compile: invalid value "go1" for -lang: should be something like "go1.12"
```

Looks like `go 1.0` isn't seen as a valid version here? It works if I change the version in `go.mod` to `go 1.1`.

https://github.com/danjacques/gofslock/blob/ae8f59f9e88bc8752912b4cfd6de339288b6738d/go.mod#L3

### What did you expect to see?

```
$ gotip build ./...
$
```

### What did you see instead?

```
$ gotip build ./...
# github.com/danjacques/gofslock/fslock
compile: invalid value "go1" for -lang: should be something like "go1.12"
$
```

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by dveeden** [comment]
@seankhliao This is *not* a question. It is a bug. The code works with go 1.21 etc but not with gotip while it should.

**Comment by go101** [comment]
@seankhliao 
What should the correct number here?
And what is the CL which is fixing this?
