### ISSUE TITLE
runtime: internal/trace/v2 tests failing as of CL 546025

### ISSUE THREAD

**Issue by bcmills** [golang/go#64507]
```
#!watchflakes
post <- pkg == "internal/trace/v2" && `writeProcStatusForP`
```

### Go version

N/A

### What operating system and processor architecture are you using (`go env`)?

```shell
build dashboard
```

### What did you do?

Check the dashboard.

### What did you expect to see?

No failures.

### What did you see instead?

Failures in various `internal/trace/v2` tests, confirmed on the LUCI dashboard and legacy builder dashboard as starting at https://go.dev/cl/546025.

**Comment by mknyszek** [comment]
Sorry for the breakage! Makes me wonder if we should have longtest builders on by default during the freeze. That would've caught this problem immediately.

**Comment by prattmic** [comment]
https://github.com/golang/go/issues/64507#issuecomment-1847818848 is a different issue, and probably a better fit for the more general #55317. I've adjusted the watchflakes rule to limit this issue to `writeProcStatusForP` crashes.

**Comment by cuonglm** [comment]
This seems to start failling more frequently, especially on gotip-windows-386: https://ci.chromium.org/ui/p/golang/builders/try/gotip-windows-386/b8752088694372824065/overview

**Comment by mknyszek** [comment]
Filed https://github.com/golang/go/issues/66624.
