### ISSUE TITLE
reflect: pass safe to packEface so we don't need to copy if safe==true is TODO

### ISSUE THREAD

**Issue by qiulaidongfeng** [golang/go#64512]
https://github.com/golang/go/pull/63446 Try to complete the above TODO.
But see https://github.com/golang/go/pull/63446/files#diff-fb7a84f457b2d4466b5d32940ffc6095d12b649f88bd3e5e762a87631e7a917aR1527 ,The first thing  is that safe==true for Value.Interface cannot be passed because it results in an error.
Then, I try to pass safe for deepValueEqual to try to complete TODO, but the benchmark shows that the number of memory allocations is always 0.
I see that this TODO ends with a question mark, maybe this TODO should be deleted directly, create an issue to investigate whether this TODO should be deleted.

**Comment by cagedmantis** [comment]
cc [@golang/runtime](https://github.com/orgs/golang/teams/runtime)

**Comment by mknyszek** [comment]
@qiulaidongfeng In general you don't have to file an issue about resolving a TODO, especially if it's not fixing a known bug. (If it is, then feel free to file an issue for that bug.) AFAICT this isn't the case here, though please correct me if I'm wrong. You can just send a CL and the discussion can happen there. Thanks.
