### ISSUE TITLE
log/slog: invalid LogAttrs examples

### ISSUE THREAD

**Issue by 3052** [golang/go#64519]
### What did you do?

these are both invalid:

https://github.com/golang/go/blob/de5b418bea70aaf27de1f47e9b5813940d1e15a4/src/log/slog/handler.go#L76-L83

### What did you expect to see?

as LogAttrs first takes a context:

https://godocs.io/log/slog#Logger.LogAttrs

**Comment by bcmills** [comment]
attn @jba
