### ISSUE TITLE
pulling go https://dl.google.com/go/go1.21.darwin-arm64.tar.gz returns 404

### ISSUE THREAD

**Issue by noslav** [golang/go#64526]
### Go version

go1.21.darwin-arm64

### What operating system and processor architecture are you using (`go env`)?

```shell
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/noslav/Library/Caches/go-build"
GOENV="/Users/noslav/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/noslav/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/noslav/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/noslav/.asdf/installs/golang/1.20.3/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/noslav/.asdf/installs/golang/1.20.3/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.3"
GCCGO="gccgo"
AR="ar"
CC="/usr/bin/gcc -I/opt/homebrew/Cellar/unixodbc/2.3.11/include"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS=". -fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_k/ddfvbjvn2fq5drm_yv5fprjr0000gn/T/go-build1354756550=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?

Tried to pull and install the new golang tar file from dl.google.com 

### What did you expect to see?

not a 404

### What did you see instead?

a 404
![Screen Shot 2023-12-03 at 13 16 22](https://github.com/golang/go/assets/26611201/9d09f7b3-6dba-4c06-b764-8ac30b0215f9)

**Comment by seankhliao** [comment]
that looks like an asdf problem for using the wrong version number.
we did not have a release called 1.21 without the .0 patch.

**Comment by noslav** [comment]
> that looks like an asdf problem for using the wrong version number.
> we did not have a release called 1.21 without the .0 patch.

apologies on having overlooked this on my end, only the patch version was necessary (I somehow followed previous installed versions from my list currently which have versions without a patch)
<img width="170" alt="Screen Shot 2023-12-04 at 19 43 54" src="https://github.com/golang/go/assets/26611201/c7dbd43b-916d-447d-aedc-259b4000be2f">
