### ISSUE TITLE
access: Need TryBot Access and Access for self-assign github issues

### ISSUE THREAD

**Issue by raghvenders** [golang/go#64523]
See https://go.dev/wiki/GerritAccess

**Comment by cagedmantis** [comment]
@raghvenders Please state the Google account you use to log in to Gerrit.

**Comment by raghvenders** [comment]
raghvenders@gmail.com

**Comment by cagedmantis** [comment]
Thank you for contributing to the Go project. While you've been active, the team usually waits for a longer history of contributions before considering granting the rights to run trybots. We usually wait for about three months of active contributions before considering granting the ability to run trybots. Please resubmit this request after two more months of active contributions.
