### ISSUE TITLE
runtime: Not compatible

### ISSUE THREAD

**Issue by ZeroRaven23** [golang/go#64530]
### Go version

go version go1.21.4 windows/amd64

### What operating system and processor architecture are you using (`go env`)?

```shell
set GO111MODULE=
set GOARCH=arm64
set GOBIN=
set GOCACHE=C:\Users\luizc\AppData\Local\go-build
set GOENV=C:\Users\luizc\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\luizc\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\luizc\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.21.4
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=C:\Users\luizc\ProjectWorks\Back\Go\Start\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\luizc\AppData\Local\Temp\go-build2615450429=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

Run the project

### What did you expect to see?

One calculating

### What did you see instead?

fork/exec C:\Users\luizc\AppData\Local\Temp\go-build1506841787\b001\exe\start.exe: This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

In this case, I've already uninstalled Go, disabled the antivirus, checked the environment variables and haven't been able to find why this is happening.

**Comment by seankhliao** [comment]
so what version of Windows is this?

**Comment by ZeroRaven23** [comment]
I simply can't run my codes in Golang anymore, because of this error

**Comment by ZeroRaven23** [comment]
So my system is 64 bits, that's why I find it strange. How could you test it running at 32?

**Comment by xhit** [comment]
Your GOARCH is arm64, but your GOHOSTARCH is amd64, you need to change GOARCH to amd64.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
