### ISSUE TITLE
math/rand/v2: submit chacha8 and runtime code [freeze exception]

### ISSUE THREAD

**Issue by rsc** [golang/go#64540]
freeze exception request for CL 546020 (fixing a rolled-back CL from before the freeze) and CL 516860 (finishing math/rand/v2, most of which was submitted before the freeze)

cc @golang/release

**Comment by rsc** [comment]
I see thumbs up from bcmills and dmitshur. What do I do next? Is there a state transition I am waiting for?

**Comment by dmitshur** [comment]
We will leave an explicit comment soon. I left a reaction to express my opinion even sooner. Thanks.

**Comment by rsc** [comment]
As far as the risk of the two CLs:

- CL 546020 does not possibly break anything, since math/rand/v2 is new. (It was rolled back due to not being big-endian-safe and due to a bug in the RISCV compiler SSA rules; both are fixed.)
- CL 516860 makes the runtime start using this code, but the CL looks bigger than it is because I rationalized the names and linkname usage, causing a lot of renaming. The CL has two different random generators in it used by the runtime. The ChaCha8 is used directly in all map creation and iteration, so it is heavily exercised. If it were broken, things would blow up quickly. The "cheap" random generator (code unchanged since before, just repackaged a bit) is used during interface checks, allocation, and any kind of blocking due to the randomized balanced tree of waiters. If it were broken, things would similarly blow up quickly. 

So these should both be very low risk. If they were bad, trybots would have failed spectacularly in all kinds of different ways.

**Comment by cagedmantis** [comment]
As discussed in the release meeting, this has been approved. There are additional considerations that we would like to discuss regarding the release timing.

**Comment by prattmic** [comment]
CL 546020 and CL 516860 are submitted. There were a few follow-up issues (filed as separate bugs), all resolved now as far as I know.
