### ISSUE TITLE
runtime, iter: add GOEXPERIMENT=rangefunc package with Seq, Pull [freeze exception]

### ISSUE THREAD

**Issue by rsc** [golang/go#64559]
Freeze exception request for CL 543319, which adds the minimal rangefunc library support for the Go 1.22 GOEXPERIMENT=rangefunc preview. The code is locked behind GOEXPERIMENT=rangefunc and does not affect API for the main release.

**Comment by rsc** [comment]
cc @golang/release

**Comment by dmitshur** [comment]
Is #64277 different from this?

**Comment by rsc** [comment]
It is not. I missed that it had been turned into a freeze exception.
