### ISSUE TITLE
runtime/cgo: fatalf is not declared as "noreturn"

### ISSUE THREAD

**Issue by fukanchik** [golang/go#64553]
### Go version

go version go1.18.1 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

```shell
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/fuxx/.cache/go-build"
GOENV="/home/fuxx/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/fuxx/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/fuxx/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.18"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.18/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2893647507=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

Run go build of a cgo project under clang's scan-build for static analysis.

### What did you expect to see?

No static analizer errors.

### What did you see instead?

In my case /usr/lib/go-1.18/src/runtime/cgo/gcc_linux_amd64.c produces:

    attr = (pthread_attr_t*)malloc(sizeof *attr);
    1	Value assigned to 'attr'
    if (attr == NULL) {
    2 Assuming 'attr' is equal to NULL	
    3 	Taking true branch	
    fatalf("malloc failed: %s", strerror(errno));
    }
    pthread_attr_init(attr);
    4 Null pointer passed to 1st parameter expecting 'nonnull

this is because fatalf is not declared as [[noreturn]]:

    /*
     * Prints error then calls abort. For linux and android.
     */
    void fatalf(const char* format, ...);

**Comment by qiulaidongfeng** [comment]
Which version of clang?
Does the latest version of go have the same problem?

**Comment by cagedmantis** [comment]
cc @golang/runtime

**Comment by cherrymui** [comment]
> clang's scan-build for static analysis

What analysis, specifically, what command did you run and what is the error message? Thanks.

**Comment by fukanchik** [comment]
Error message is in the section "What did you see instead?" of the ticket description.

I run the following command:
```
scan-build go build main.go
```

**Comment by mauri870** [comment]
The issue description shows more errors, but that is with go 1.18, which is EOL.

This only happens for Go <= 1.21, the changes from [CL519457](https://go-review.googlesource.com/c/go/+/519457) made the only warning go away. Since this is just a warning I don't think it is worth backporting.

```bash
$ scan-build go1.21.5 build main.go
scan-build: Using '/usr/lib/llvm-14/bin/clang' for static analysis
# runtime/cgo
gcc_linux_amd64.c:45:2: warning: Null pointer passed to 1st parameter expecting 'nonnull' [core.NonNullParamChecker]
        pthread_attr_init(attr);
        ^~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
scan-build: No bugs found.
```

```bash
$ scan-build gotip build main.go
scan-build: Using '/usr/lib/llvm-14/bin/clang' for static analysis
scan-build: No bugs found.
```

**Comment by cherrymui** [comment]
Thanks @mauri870 . Since there is no more warnings we can close this.

If one wants to add a noreturn attribute or dummy return statements after fatalf, feel free to send a CL. Thanks.

**Comment by fukanchik** [comment]
It's ok to close this, however even though go 1.18 is EOL, it is the actual version for Ubuntu 22.04.3 LTS. That is one of the most used distributions.
