### ISSUE TITLE
Go binary crashed giving "Floating point exception (core dumped)" error message? (No usable until rebuild)

### ISSUE THREAD

**Issue by samueljaydan** [golang/go#64562]
### Go version

go version go1.20.1 openbsd/amd64

### What operating system and processor architecture are you using (`go env`)?

```shell
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="openbsd"
GOINSECURE=""
GOMODCACHE="/var/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="openbsd"
GOPATH="/var/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/openbsd_amd64"
GOVCS=""
GOVERSION="go1.20.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="cc"
CXX="c++"
CGO_ENABLED="1"
GOMOD=""
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build61970428=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

The main program uses the mentioned libraries below. After a while, it encounters a "Floating point exception (core dumped)" error. This error persists and prevents the program from being used again until it is rebuilt.

```
import (
	"crypto/aes"
	"crypto/cipher"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io/ioutil"
	"net"
	"os"
	"os/exec"
	"os/signal"
	"strconv"
	"strings"
	"time"
	"unsafe"
	"golang.org/x/sys/unix"
)
```

```
Core was generated by `main'.
Program terminated with signal 8, Arithmetic exception.
#0  0x0000000296f0ccd5 in ?? ()
(gdb) bt
#0  0x0000000296f0ccd5 in ?? ()
#1  0x0000000000000000 in ?? ()
(gdb) list
No symbol table is loaded.  Use the "file" command.
(gdb) where
#0  0x0000000296f0ccd5 in ?? ()
#1  0x0000000000000000 in ?? ()
(gdb) bt full
#0  0x0000000296f0ccd5 in ?? ()
No symbol table info available.
#1  0x0000000000000000 in ?? ()
No symbol table info available.
(gdb)
```

### What did you expect to see?

I want to learn why that binary crashed. 
Which function or functions caused this error?
It should not give the "Floating point exception (core dumped)" error.  

### What did you see instead?

it encounters a "Floating point exception (core dumped)"

**Comment by randall77** [comment]
> After a while

How long? Does it run properly for a while? Multiple executions of it, or just one?

> This error persists and prevents the program from being used again until it is rebuilt.

So rebuilding causes the program to work again? Very strange. I suspect an antivirus is getting in your way.

Compute the md5 of a working binary and the md5 of a failing binary and see if they match.

**Comment by samueljaydan** [comment]
I'm sure this isn't a virus because I'm using OpenBSD. I also got this error on multiple devices.

This disruption has happened to me multiple times. When I checked their MD5 I noticed it had changed. I got this error mostly after power outages, but interestingly, this binary broke down every time, not the other binaries.

**Comment by randall77** [comment]
> I'm sure this isn't a virus because I'm using OpenBSD.

I don't mean it is a virus. I mean your antivirus has a false positive on your Go binary, thinks it has a virus, and disables it somehow.

> When I checked their MD5 I noticed it had changed.

Figure out where that change is coming from. This is almost certainly not the fault of Go itself.

If it is after power outages, maybe the file system is not getting flushed properly. Maybe a we're missing an fsync somewhere?

**Comment by thediveo** [comment]
are you using OpenZFS?
