### ISSUE TITLE
x/tools/gopls: enhance read/write access distinction in document highlighting for symbols

### ISSUE THREAD

**Issue by xzbdmw** [golang/go#64579]
### gopls version

0.14.2

### go env

```shell
GO111MODULE="auto"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/xzb/Library/Caches/go-build"
GOENV="/Users/xzb/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/xzb/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/xzb/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go@1.18/1.18.10/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go@1.18/1.18.10/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.18.10"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/gv/r110hgbx1gbgzp95kf_q71x40000gn/T/go-build3631566834=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?

<img width="872" alt="image" src="https://github.com/golang/go/assets/97848247/1a94ea63-bb45-4499-98e3-1ea49d103741">
first line is write access and second line is read access

### What did you expect to see?

vscode distinguishs write access and read access, most lsp implementations have it such as clangd and rust-analyzer
an rust example:
<img width="765" alt="image" src="https://github.com/golang/go/assets/97848247/258a4cad-3c3a-40a4-b9db-310c610ca3c5">
see the different color of scoped_interpreter

### What did you see instead?

no color difference

**Comment by hyangah** [comment]
@pjweinb Is the `modification` modifier in the [semantic token](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide)  for this distinction?
On the other hand, I wonder what write-access vs read-access means in Go,  unlike rust.
In `io.Copy(w, r)`, is `w` read access or write access?

**Comment by xzbdmw** [comment]
> @pjweinb Is the `modification` modifier in the [semantic token](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide) for this distinction? On the other hand, I wonder what write-access vs read-access means in Go, unlike rust. In `io.Copy(w, r)`, is `w` read access or write access?

no，only variable reassign is considered write in pylance，clangd and rust-analyzer

**Comment by pjweinb** [comment]
The documentation says nothing about the meaning of the 'modification' modifier, and gopls doesn't use it. I suspect the uses would vary widely by language, but I don't know what would be useful (and practical) in Go.

**Comment by adonovan** [comment]
The easiest definition to implement is the variable/value distinction (which C calls lvalue/rvalue). For example:

```
var v struct { x int }
ptr := &v

ptr.x = ptr.x + 1   // the first x is an lvalue; the second x, and both ptrs, are rvalues
ptr.x++  // x is an lvalue, ptr is an rvalue
v.x = v.x + 1 // the first v and x are lvalues; the second v and x are rvalues
```

But I have no idea  if that's actually what people want. As @hyangah points out with the `io.Copy` example, what we mean by a read and a write is highly context-dependent.

**Comment by xzbdmw** [comment]
I think the easiest way is what most people won't feel uncomfortable, and io.Copy example can wait for future improvement

**Comment by zhzhsx** [comment]
I have a plan to implement this feature, and want to know if it is acceptable.

The definition of 'write access' is same as it in GoLand. Some examples are
access to variables in declaration, assignment(left value), self increasing,
channel sending and composite literal.

The algorithm to find write access is same as it in [jdt (Java LSP)](https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/123be9479530e5d55e0785b630567ab8d1e7f97a/org.eclipse.jdt.core.manipulation/core%20extension/org/eclipse/jdt/internal/core/manipulation/search/OccurrencesFinder.java#L216), by
visiting every write statement in ast traversal and collecting the positions
of access to variables.

A darft version of implementation is [here](https://github.com/zhzhsx/tools/commit/684309a1b472c766bcdc02c98b785418025816cf) and the preview of the feature in VSCode is:
![highlight2](https://github.com/golang/go/assets/1379025/04953d46-fca1-40ca-b7cf-2b9052775f03)

**Comment by hyangah** [comment]
Thanks @zhzhsx! TIL that this read/write distinction can be marked using [`DocumentHighlight`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#documentHighlightClientCapabilities). I think this is a less invasive and more reliable approach than using custom modifier-based syntax highlighting. Please send a cl following the contribution guide 
https://go.dev/doc/contribute
