### ISSUE TITLE
x/pkgsite: type header table of contents links to a different type

### ISSUE THREAD

**Issue by prattmic** [golang/go#64582]
### What is the URL of the page with the issue?

https://pkg.go.dev/google.golang.org/grpc#EmptyDialOption

### What is your user agent?

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

### Screenshot

Original: ![image](https://github.com/golang/go/assets/1293187/24f3e0c4-5497-49ab-92a6-39ee9c81ea24)

After clicking "Experimental": 
![image](https://github.com/golang/go/assets/1293187/2e05712f-3674-4c79-a56a-dd6ced2d00a8)

### What did you do?

Under the "EmptyDialOption" type, I clicked on the "Experimental" link, which is intended to be a table of contents for the headers within the type doc.

### What did you expect to see?

I expected the page to jump to the "Experimental" header just a few lines below (shown in the "Original" screenshot above).

### What did you see instead?

The page jumped to https://pkg.go.dev/google.golang.org/grpc#hdr-Experimental, which is part of "func ClientSupportedCompressors" instead of "type EmptyDialOption".

The problem seems to be that the IDs (`#hdr-Experimental`) aren't unique per type/function, so links go to whichever appears first on the page.

**Comment by hyangah** [comment]
@jba Isn't this an issue in go/doc/comment? (I see the same issue in godoc). Or does pkgsite use a custom header generation logic?
