### ISSUE TITLE
x/build: add LUCI linux-ppc64-power10 builder.

### ISSUE THREAD

**Issue by pmur** [golang/go#64588]
This will be the LUCI `GOPPC64=power10 GOARCH=ppc64 GOOS=linux` builder replacement for `host-linux-ppc64-sid-power10`.

It will share the same VM resources as `host-linux-ppc64-sid-power10`. The hostname should be `linux-ppc64-power10`.

Certificate attached: [linux-ppc64-power10.csr.txt](https://github.com/golang/go/files/13591578/linux-ppc64-power10.csr.txt)

**Comment by dmitshur** [comment]
Thanks. This is similar to #61274, except it's `GOARCH=ppc64` and `GOPPC64=power8`.

CC @golang/release.

**Comment by cagedmantis** [comment]
Here's the resulting certificate: [linux-ppc64-power10-1702068073.cert.txt](https://github.com/golang/go/files/13620762/linux-ppc64-power10-1702068073.cert.txt).

The builder definitions have been added in [CL 548217](https://go.dev/cl/548217) so your bot should be able to connect once you follow the rest of the steps on your end.

**Comment by pmur** [comment]
Thanks! I have one instance started and running.

**Comment by dmitshur** [comment]
That was fast, and we now have its first green build!

https://ci.chromium.org/b/8762240340084651697

Thanks very much. Would you like to keep this issue open (e.g., while you're adding more instances) a bit longer, or okay to close now?

**Comment by pmur** [comment]
Is the GOPPC64=power10 envvar configured for this builder? I didn't see it listed when I clicked through the log above. Should I be configuring that on the builder itself, or is the luci coordinator responsible for setting that?

**Comment by dmitshur** [comment]
Good point, it [ended up](https://logs.chromium.org/logs/golang/buildbucket/cr-buildbucket/8762240340084651697/+/u/step/16/log/2) as its default value of `power8`.

The optimal place to set it might be in our [builder configuration](https://cs.opensource.google/go/x/build/+/luci-config:README), though it's also okay for you to do it in the builder's environment if that doesn't get in the way of something else.

**Comment by dmitshur** [comment]
Checking in on the status of this in progress new-builder issue. Is there more to do here before closing it?

**Comment by dmitshur** [comment]
@pmur Should this issue also be closed, or is there more to do for it?
