### ISSUE TITLE
x/build: add LUCI windows-arm64 builder

### ISSUE THREAD

**Issue by thanm** [golang/go#64587]
Tracking issue for adding new windows-arm64 LUCI builders. Proposed hostname is

  windows-arm64-azure

with the individual builders suffixed with `--00`, `--01` and so on.

CSR is attached.

[windows-arm64-azure.csr.txt](https://github.com/golang/go/files/13591448/windows-arm64-azure.csr.txt)

**Comment by thanm** [comment]
Here is the certificate: 
[windows-arm64-azure-1701977344.cert.txt](https://github.com/golang/go/files/13604352/windows-arm64-azure-1701977344.cert.txt)

**Comment by thanm** [comment]
OK, due to mistakes on my part, I am going to redo the key generation. Here is a new csr:

[windows-arm64-azure.csr.txt](https://github.com/golang/go/files/13651370/windows-arm64-azure.csr.txt)

**Comment by thanm** [comment]
Here is the certificate (round 2):

[windows-arm64-azure-1702406379-cert.txt](https://github.com/golang/go/files/13652126/windows-arm64-azure-1702406379-cert.txt)

**Comment by thanm** [comment]
I have added a new CIPD package containing C/C++ compilers for windows-arm64, for use with LUCI:

```
$ cat cipd.yaml
package: golang/third_party/llvm-mingw-msvcrt/windows-arm64
description: windows-arm64 LLVM-based C/C++ compiler
root: checkout
data:
 - dir: .
$ cipd create -pkg-def=cipd.yaml -tag version:22020323
[P2864632 14:22:11.686 builder.go:141 I] About to zip 4229 files with compression level 5
[P2864632 14:22:11.686 builder.go:155 I] Zipping files: 4229 files left
[P2864632 14:22:12.687 builder.go:155 I] Zipping files: 3684 files left
[P2864632 14:22:13.688 builder.go:155 I] Zipping files: 2851 files left
[P2864632 14:22:15.506 builder.go:155 I] Zipping files: 2604 files left
[P2864632 14:22:16.524 builder.go:155 I] Zipping files: 2595 files left
[P2864632 14:22:17.525 builder.go:155 I] Zipping files: 1906 files left
[P2864632 14:22:18.525 builder.go:155 I] Zipping files: 1158 files left
[P2864632 14:22:19.525 builder.go:155 I] Zipping files: 531 files left
[P2864632 14:22:20.526 builder.go:155 I] Zipping files: 15 files left
Instance: golang/third_party/llvm-mingw-msvcrt/windows-arm64:qns0hQVslwiii8CR-KCXnKmCnVUofE3cRgwfdwFWpVUC
 • Instance golang/third_party/llvm-mingw-msvcrt/windows-arm64:qns0hQVslwiii8CR…
 • Tag "version:22020323" was attached
$
```

Compilers were drawn from the existing bundle at `https://storage.googleapis.com/go-builder-data/llvm-mingw-20220323-ucrt-aarch64.tar.gz`.

**Comment by thanm** [comment]
Update: sent these CLs as part of the work on this issue (forgot to tags the CLs, so mentioning here):

[CL 549118](https://golang.org/cl/549118): env/windows-arm64: add helper program for file writing
[CL 548476](https://golang.org/cl/548476) env/windows-arm64/azure: convert VM bringup script for LUCI use
[CL 549715](https://golang.org/cl/549715) env/windows-arm64/azure: fix buglet in VM setup script

I have one more fix in the works after that related to scheduled tasks.

**Comment by dmitshur** [comment]
@thanm Are there specific tasks left to do here, or is it a good time to mark this as resolved? Thanks.

**Comment by thanm** [comment]
Nothing specific left to do as far as I know. Closing out, thanks.
