### ISSUE TITLE
access: requesting access for running the try bots (Try-bots+1)

### ISSUE THREAD

**Issue by RuinanSun** [golang/go#64594]
See https://go.dev/wiki/GerritAccess

May I request an access to run the Try-bots? If then it will be more convenient for me.

User: `ruinan.sun@arm.com`

Thanks,
Ruinan

**Comment by cagedmantis** [comment]
Hi Ruinan,

Thank you for your contributions and for requesting Trybots access! I've added you to the may-start-trybots group, so you should be able to do so now.

As you've likely read at https://go.dev/wiki/GerritAccess#running-trybots-may-start-trybots, please be sure to at least skim CLs before starting a Trybot run.

Let us know if you have any questions or issues with it, and thanks again!
