### ISSUE TITLE
x/vuln: Ignore found vulnerabilities

### ISSUE THREAD

**Issue by gakesson** [golang/go#64599]
Hello folks,

I have a proposal:

In order to make govulncheck more flexible in CICD automations, what do you think of introducing an `-ignore` flag which can be used to temporarily ignore certain supplied vulnerabilities? Say the database is updated with a new entry and CICD starts to fail, but we want to temporarily ignore that particular new entry without having to disable the entire govulncheck scan.

For example `govulncheck -ignore=GO-2023-2186,GO-2023-2185 ./...` or a file.

Thoughts?
Thank you for a great tool!

**Comment by seankhliao** [comment]
Duplicate of #59507
