### ISSUE TITLE
Flag package: Boolean flags with explicit value following flag and space cause parsing issues

### ISSUE THREAD

**Issue by NeonWizard** [golang/go#64593]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.11 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/.../Library/Caches/go-build"
GOENV="/Users/.../Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS="-tags=dynamic"
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/.../go/pkg/mod"
GOOS="darwin"
GOPATH="/Users/.../go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go@1.20/1.20.11/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go@1.20/1.20.11/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.11"
GCCGO="gccgo"
AR="ar"
CC="cc"
CXX="c++"
CGO_ENABLED="1"
GOMOD="/Users/.../go/src/..."
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/kp/33427_jx5yn03xbwx59xxbsw0000gq/T/go-build585603688=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version go1.20.11 darwin/arm64
GOROOT/bin/go tool compile -V: compile version go1.20.11
uname -v: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
ProductName:		macOS
ProductVersion:		13.3.1
BuildVersion:		22E261
lldb --version: lldb-1403.0.17.67
Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
</pre></details>

### What did you do?

Boolean flags don't allow specifying a value with a space between the flag and value. You either have to drop the value to get an implicit 'true', or use an equal sign (`-AutoStart=true`). If a value is included with a space, it breaks the internal parsing of the string and all following arguments will fall back to default. No error is thrown.

At the bare minimum, an error should be thrown when encountering this case, instead of allowing the program to continue with the remainder arguments being defaulted. Ideally, the package should allow specifying `-AutoStart true` to keep consistency with all other flag types.

Using the `flag` package, define some commandline flags including a boolean flag:

```go
connAddress := flag.String("ConnAddress", "ip", "Connection address")
autoStart := flag.Bool("AutoStart", false, "Automatically start")
execParams := flag.String("ExecParams", "null", "Execution params")
flag.Parse()
```

Run the application with this command:

```bash
./out -ConnAddress 127.0.0.1 -AutoStart true -ExecParams hello,world,stop
```

### What did you expect to see?

```go
connAddress == "127.0.0.1"
autoStart == true
execParams == "hello,world,stop"
```

### What did you see instead?

```go
connAddress == "127.0.0.1"
autoStart == true
execParams == "null"
```

**Comment by seankhliao** [comment]
This is working as intended.
