### ISSUE TITLE
x/pkgsite: package removal request for [https://pkg.go.dev/github.com/srhnevmer/passgen]

### ISSUE THREAD

**Issue by srhnevmer** [golang/go#64601]
### What is the path of the package that you would like to have removed?

https://pkg.go.dev/github.com/srhnevmer/passgen

### Are you the owner of this package?

Yes, I am the owner of the package.

### What is the reason that you could not retract this package instead?

I deleted my old GitHub account with the username (srhnevmer), so the repository with the code for this project was also deleted. Now it is no longer available at the original URL.

**Comment by hyangah** [comment]
This is removed.
