### ISSUE TITLE
runtime/cgo: _cgo_allocate can not work with precise GC

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#6461]
<pre>We currently provide a _cgo_allocate function in the runtime/cgo package.  This function
is mentioned in the cgo documentation, though without documentation.  It is provided to
SWIG code under the name swig_goallocate.

This function can not work with fully precise GC, because there is no type information
for the allocated memory.

We need to figure out a way to address this consonant with the Go 1 guarantee.</pre>

**Comment by rsc** [comment]
cgo_allocate is gone, and the latest SWIG has been updated. Yay!
