### ISSUE TITLE
all: remove unnecessary new line after return statements

### ISSUE THREAD

**Issue by Tv0ridobro** [golang/go#64610]
In some parts of the codebase, there are unnecessary newline characters following return statements. These newline characters create unnecessary separation in the code.

I searched for them with 
`rg -tgo -U 'return.*\n\n}'`
and found 32 files and all new lines looks like a mistype.

I tried to think of a case where new line after return would be useful, but nothing came to mind. Maybe it would be better to remove them? Or even add new check to gofmt.

**Comment by seankhliao** [comment]
i wish the go repos would use gofumpt
