### ISSUE TITLE
x/playground: vet produces incorrect results on programs that set `// GOEXPERIMENT=rangefunc`

### ISSUE THREAD

**Issue by j178** [golang/go#64644]
### Go version

go dev branch

### What operating system and processor architecture are you using (`go env`)?

```shell
n/a
```

### What did you do?

https://go.dev/play/p/vAn7V6xqpWQ?v=gotip

### What did you expect to see?

The program compiles.

### What did you see instead?

```
package play
	imports iter: build constraints exclude all Go files in /usr/local/go-faketime/src/iter
```
<img width="1023" alt="image" src="https://github.com/golang/go/assets/10510431/1aec2c0e-0124-4aa7-b783-8bf5e35c4a43">

**Comment by seankhliao** [comment]
I don't think we've said anywhere that it should work

**Comment by prattmic** [comment]
I'm not sure this is documented anywhere, but it was implemented in https://go.dev/cl/511640. I don't see why this wouldn't be working.

cc @rsc @findleyr

**Comment by dmitshur** [comment]
Note that the program does compile; https://go.dev/play/p/DexLktKrFTb?v=gotip makes that easier to see. The problem appears to be that `vet` isn't being told about the experiment and thus doesn't work.

**Comment by findleyr** [comment]
I suppose https://go.dev/cl/549015 probably fixes this, but need to remember how to test.

**Comment by findleyr** [comment]
This was fixed by https://go.dev/cl/612456.
