### ISSUE TITLE
x/tools/gopls: Highlight the symbols in comments, and support jump to the definition of symbols

### ISSUE THREAD

**Issue by rogeryk** [golang/go#64648]
### gopls version

v14.2

### go env

```shell
unimportant
```

### What did you do?

unimportant

### What did you expect to see?

In Golang, documentation is maintained in code comments. The comment contain a lot of symbols, Highlighting these symbols will make reading clearer. When reading the documentation, you may want to look at the definition of the commit object, so improving the ability to jump would be great.
- highlight symbols in comments
- suport go to definition for symbols in comments

These feature are already implemented in Goland.
Goland
<img width="913" alt="image" src="https://github.com/golang/go/assets/28089185/df026ea3-55f6-4d77-be2d-1f3d67464568">

Vscode
<img width="874" alt="image" src="https://github.com/golang/go/assets/28089185/b0748d91-536a-4349-b3c3-9a417eac8fdd">

### What did you see instead?

unimportant

**Comment by gophun** [comment]
I don't think that GoLand does the right thing either. Only `[Context]` should be rendered as a link, because the author explicitly marked it as one, cf. pkg.go.dev: https://pkg.go.dev/context#Background

**Comment by hyangah** [comment]
I see this feature request is relevant to a couple of different functionalities gopls is offering.

* [textDocument/documentLink](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentLink). Not sure though if editors themselves color differently the parts associated with links. (vscode doesn't seem to color linkified texts).

* Semantic tokens - symbols in comments may be annotated with the [`documentation`](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide) modifier. For example, "Background" and linkified symbols may be differently rendered.

* [textDocument/hover](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_hover). Hover UI can use richer presentation (for symbol documentations), but gopls does not seem to handle `[]` notation yet.

![Screenshot 2023-12-11 at 9 00 04 AM](https://github.com/golang/go/assets/4999471/45d4e9ca-54f2-4f70-8af0-2ec6f0d3fbfb)

**Comment by rogeryk** [comment]
@hyangah 
>  [textDocument/documentLink](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentLink). Not sure though if editors themselves color differently the parts associated with links. (vscode doesn't seem to color linkified texts).

I hope "textDocument/definition" is also supported, because I hope to use a shortcut key to jump to the corresponding definition.

>  Semantic tokens - symbols in comments may be annotated with the [`documentation`](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide) modifier. For example, "Background" and linkified symbols may be differently rendered.

The "doccumentation" modifier is suitable, bu it seems that many themes in vscode do not highlight this.

**Comment by mvdan** [comment]
Just to double check: will this will work with any comment, or just with godoc comments? Even if non-godoc comments don't get rendered as godoc and don't strictly speaking have support for links, I still use this format in them for the sake of consistency and clarity when I refer to a Go identifier, particularly from another package.

**Comment by rogeryk** [comment]
@mvdan This decision is still open to discussion, although I might personally prefer not to work with any comments.
Think about it from a consistency perspective, It would be better to follow the godoc link rules, but I see many packages that don't go out of their way to follow the godoc link rules.

**Comment by rogeryk** [comment]
After some discussion, due to consistency and performance considerations, it only takes effect for doc links. More details can be found in CL  https://go.dev/cl/553836

**Comment by mvdan** [comment]
> After some discussion, due to consistency and performance considerations, it only takes effect for doc links. More details can be found in CL https://go.dev/cl/553836

As long as `[Foo]` works in any comment, godoc or not, that's what I wanted :) I meant that I use this format in non-godoc comments too, such as those inside function bodies, and I'd like gopls to support them too. pkgsite doesn't have to, since it doesn't render those comments in any way.

**Comment by rogeryk** [comment]
@mvdan Ok, now it's exactly what you expected.

**Comment by findleyr** [comment]
Just used this for the first time, and it's so great!
