### ISSUE TITLE
slice.go: why the slice's len() is greater than the cap()

### ISSUE THREAD

**Issue by wobushixiaoj** [golang/go#64642]
### Go version

go version go1.17.2 darwin/arm64

### What operating system and processor architecture are you using (`go env`)?

```shell
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/xxx/Library/Caches/go-build"
GOENV="/Users/xxx/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
```

### What did you do?
I append the slice by multiple goroutines with write lock, and read the slice without lock.
After running  a while, I can view 3 type errors randomly:
* nil pointer error
* len > cap
* unexpected fault address

I suspect that modelList points to the array before the slice "item.ModelList" grew, and this array has been GC.

https://go.dev/play/p/VLOXxf25vOW?v=goprev

<img width="1507" alt="image" src="https://github.com/golang/go/assets/10751551/3300d6ec-24b9-43d9-95d0-452b870e604c">

### What did you expect to see?

we should not react the nil pointer error or len>cap

### What did you see instead?

nil pointer error
len > cap

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
