### ISSUE TITLE
import/path: Golang ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain

### ISSUE THREAD

**Issue by farsheedeveloper** [golang/go#64643]
### Go version

1.19 & 1.21

### What operating system and processor architecture are you using (`go env`)?

```shell
CentOS Linux release 7.9.2009 (Core)
```

### What did you do?

this is my code and i got this error 
**ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain**  

address := con.Address + ":" + con.Port

	config := &ssh.ClientConfig{
		User: con.User,
		Auth: []ssh.AuthMethod{
			ssh.Password(con.Pass),
		},
		HostKeyCallback: ssh.InsecureIgnoreHostKey(),
		//Timeout:         time.Duration(time.Millisecond * 500),
	}

	client, err := ssh.Dial("tcp4", address, config)

	if err != nil {
		//fmt.Println(address, "Failed to connect: ", err)
		sshVal[key].Error = fmt.Sprintf("Failed to connect: %s", err)
		return
	}
	defer client.Close()

	session, err := client.NewSession()

	if err != nil {
		//fmt.Println(address, "Failed to create session: %s", err)
		sshVal[key].Error = fmt.Sprintf("Failed to create session: %s", err)
		return
	}
	defer session.Close()

	output, err := session.CombinedOutput(con.Command)
	if err != nil {

		//fmt.Println(address, "Failed to run command: %s", err)

		sshVal[key].Error = fmt.Sprintf("Failed to run command: %s", err)
		return
	}
	sshVal[key].Output = string(output)

### What did you expect to see?

i wanna to run command and get response but its fail to connect

### What did you see instead?

ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
