### ISSUE TITLE
runtime/pprof: incorrect locations for inlined generic functions

### ISSUE THREAD

**Issue by korniltsev** [golang/go#64641]
### Go version

go version devel go1.22-de5b418bea Sat Dec 2 03:15:03 2023 +0000 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/korniltsev/.cache/go-build'
GOENV='/home/korniltsev/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/korniltsev/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/korniltsev/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/home/korniltsev/github/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/home/korniltsev/github/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='devel go1.22-de5b418bea Sat Dec 2 03:15:03 2023 +0000'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/korniltsev/github/go/src/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3732277415=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

I produced a pprof profile with the following stacktrace

```
foo
generic[a,b]
generic[b,a]
```
And `foo` and `generic[a,b]` functions are inlined by the go compiler

[Reproducer ](https://gist.github.com/korniltsev/f6c639c68c7c40e1ead5db6012abed92)

More info: https://github.com/golang/go/issues/64528#issuecomment-1846804084

### What did you expect to see?

I expected to see a pprof `Location` with 3 `Line` for this case.

### What did you see instead?

Isee a pprof `Location` with 2 `Line` for this case. Only
```
foo
generic[a,b]
```

and then separate location for 

```
generic[b,a]
```

I suspect this is because of this line , which checks for function names without generic shapes (`generic[...]`)

https://github.com/golang/go/blob/de5b418bea70aaf27de1f47e9b5813940d1e15a4/src/runtime/pprof/proto.go#L564

**Comment by prattmic** [comment]
This is https://github.com/golang/go/issues/64528#issuecomment-1846804084, split into another bug. I think this also qualifies for the backport in #64609.

cc @golang/runtime @cherrymui
