### ISSUE TITLE
curly brackets on a new line are not supported

### ISSUE THREAD

**Issue by vault-thirteen** [golang/go#64658]
### Go version

all

### What operating system and processor architecture are you using (`go env`)?

```shell
This does not depend on an operating system
```

### What did you do?

I tried to type the following code.

```go
if (len(stn.SmtpModuleSettings.Host) == 0) ||
		(stn.SmtpModuleSettings.Port == 0) ||
		(len(stn.SmtpModuleSettings.Path) == 0) ||
		(len(stn.SmtpModuleSettings.MessageSubjectTemplate) == 0) ||
		(len(stn.SmtpModuleSettings.MessageBodyTemplateForReg) == 0) ||
		(len(stn.SmtpModuleSettings.MessageBodyTemplateForLogIn) == 0) ||
		(len(stn.SmtpModuleSettings.MessageBodyTemplateForPwdChange) == 0) ||
		(len(stn.SmtpModuleSettings.MessageBodyTemplateForEmailChange) == 0)
	{
		return errors.New(c.MsgSmtpSettingError)
	}
```

### What did you expect to see?

I expected to use curly brackets on a new line as they are used in most of the programming languages, such as C, C++, C#, Java, JavaScript and many other programming languages that exist.

### What did you see instead?

I saw the formatter to change it to the following code.

```
if (len(stn.SmtpModuleSettings.Host) == 0) ||
		(stn.SmtpModuleSettings.Port == 0) ||
		(len(stn.SmtpModuleSettings.Path) == 0) ||
		(len(stn.SmtpModuleSettings.MessageSubjectTemplate) == 0) ||
		(len(stn.SmtpModuleSettings.MessageBodyTemplateForReg) == 0) ||
		(len(stn.SmtpModuleSettings.MessageBodyTemplateForLogIn) == 0) ||
		(len(stn.SmtpModuleSettings.MessageBodyTemplateForPwdChange) == 0) ||
		(len(stn.SmtpModuleSettings.MessageBodyTemplateForEmailChange) == 0) {
		return errors.New(c.MsgSmtpSettingError)
	}
```

**Comment by randall77** [comment]
This is working as intended. See https://go.dev/doc/faq#semicolons

**Comment by vault-thirteen** [comment]
When something is "intended", it does **not** mean that it is correct. And many people have argued about this "feature" when they learned about it. This fact is even saved in the history and stated in that "doc":
> Some have argued that the lexer should do lookahead to permit the brace to live on the next line.

However, the text ignores that the number of those "some" was quite perceptible.
