### ISSUE TITLE
regexp/syntax: (?:A) doesn't compile

### ISSUE THREAD

**Issue by dolmen** [golang/go#64668]
### Go version

go version go1.21.5 darwin/arm64

### What operating system and processor architecture are you using (`go env`)?

```shell
N/A
```

### What did you do?

From [regexp/syntax](https://pkg.go.dev/regexp/syntax):
```
(?:re)         non-capturing group
```

https://go.dev/play/p/YKM2yyDC2Bm
```go
import "regexp/syntax"

fmt.Println(syntax.Parse("(?:A)", 0))
```
Output:
```
<nil> error parsing regexp: missing argument to repetition operator: `?`
```

```console
$ perl -E 'say ("A" =~ /(?:A)/)'
1
$ go run github.com/dolmen-go/goeval@latest -i=regexp/syntax -i=fmt 'fmt.Println(syntax.Parse("(A)", 0))'
(A) <nil>
$ go run github.com/dolmen-go/goeval@latest -i=regexp/syntax -i=fmt 'fmt.Println(syntax.Parse("(?:A)", 0))'  
<nil> error parsing regexp: missing argument to repetition operator: `?`
```

### What did you expect to see?

no error

### What did you see instead?

Output:
```
<nil> error parsing regexp: missing argument to repetition operator: `?`
```

**Comment by Jorropo** [comment]
I think this is a duplicate of #18868, you can find third party packages which implements lookahead.

**Comment by Jorropo** [comment]
Doing this works:
```go
import "regexp/syntax"

fmt.Println(syntax.Parse("(?:A)", syntax.Perl))
```
(this is what `regexp.Compile` uses)

`0` is posix syntax:
https://github.com/golang/go/blob/b18b05881691861c4279a50010829150f1684fa9/src/regexp/syntax/parse.go#L72

Which does not have support for non capturing groups as far as I checked.

There is this text which attempts to explain this.
https://pkg.go.dev/regexp/syntax#hdr-Syntax

I guess each feature could explain under which syntax it is supposed to work. In a table form it might even be digest.

**Comment by dolmen** [comment]
OK, closing. I will see instead about submitting documentation improvements.
