### ISSUE TITLE
iter: `gotip tool compile` failed with ` could not import iter (file not found)`

### ISSUE THREAD

**Issue by j178** [golang/go#64666]
### Go version

go version devel go1.22-b18b058 Mon Dec 11 23:29:45 2023 +0000 X:rangefunc windows/amd64

### What operating system and processor architecture are you using (`go env`)?

```shell
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\nigel\AppData\Local\go-build
set GOENV=C:\Users\nigel\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=rangefunc
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\nigel\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\nigel\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Users\nigel\sdk\gotip
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Users\nigel\sdk\gotip\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=devel go1.22-b18b058 Mon Dec 11 23:29:45 2023 +0000 X:rangefunc
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\Projects\goland\it\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\nigel\AppData\Local\Temp\go-build849119791=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

`GOEXPERIMENT=rangefunc gotip tool compile ./f.go`

`f.go`:

```go
package main

import _ "iter"
```

### What did you expect to see?

It compiles ok.

### What did you see instead?

```
.\f.go:3:10: could not import iter (file not found)
```

**Comment by mauri870** [comment]
We don't make much guarantees regarding `go tool compile`, as it generally changes from one release to the other.

Sometimes you get the same error when importing "fmt" as well.

If you try `GODEBUG=installgoroot=all GOEXPERIMENT=rangefunc go install std` you can probably run compile just fine.

But again, you should be using go build or go run instead.

Similar to https://github.com/golang/go/issues/58629

**Comment by j178** [comment]
I get it. Thank you for the detailed explanation.
