### ISSUE TITLE
x/website: /security is a redirection loop

### ISSUE THREAD

**Issue by yansal** [golang/go#64672]
### Go version

not relevant

### What operating system and processor architecture are you using (`go env`)?

```shell
not relevant
```

### What did you do?

```
➜  ~ curl https://go.dev/security    
<a href="/security/">Moved Permanently</a>.

➜  ~ curl https://go.dev/security/
<a href="/doc/security/">Moved Permanently</a>.

➜  ~ curl https://go.dev/doc/security/
<a href="/security">Moved Permanently</a>.
```

### What did you expect to see?

not a redirection loop

### What did you see instead?

a redirection loop

**Comment by prattmic** [comment]
cc @golang/tools-team
