### ISSUE TITLE
cmd/go/internal/vcweb/vcstest: TestScripts/git/issue47650.txt failing on systems with older git versions

### ISSUE THREAD

**Issue by Ponewor** [golang/go#64670]
### Go version

Latest version on master b18b058

### What operating system and processor architecture are you using (`go env`)?

```shell
GOARCH='amd64'
GOBIN=''
GOCACHE='/root/.cache/go-build'
GOENV='/root/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/root/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/root/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/root/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/root/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.4'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build294179835=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

Just ran the `all.sh` script to build.

### What did you expect to see?

Successful build

### What did you see instead?

--- FAIL: TestScripts (0.40s)
    --- FAIL: TestScripts/git/issue47650.txt (0.89s)
        vcstest_test.go:155: 2023/12/12 02:12:46 issue47650.txt:
            > handle git
            > env GIT_AUTHOR_NAME='Bryan C. Mills'
            > env GIT_AUTHOR_EMAIL='bcmills@google.com'
            > env GIT_COMMITTER_NAME=$GIT_AUTHOR_NAME
            > env GIT_COMMITTER_EMAIL=$GIT_AUTHOR_EMAIL
            > git init
            [stdout]
            Initialized empty Git repository in /tmp/TestScripts1179865923/001/git/issue47650/.git/
            > at 2021-08-11T13:52:00-04:00
            > git add cmd
            > git commit -m 'add cmd/issue47650'
            [stdout]
            [master (root-commit) 4d237df] add cmd/issue47650
             1 file changed, 7 insertions(+)
             create mode 100644 cmd/issue47650/main.go
            > git tag v0.1.0
            > git add go.mod
            > git commit -m 'add go.mod'
            [stdout]
            [master 21535ef] add go.mod
             1 file changed, 3 insertions(+)
             create mode 100644 go.mod
            > git show-ref --tags --heads
            [stdout]
            21535ef346c3e79fd09edd75bd4725f06c828e43 refs/heads/master
            4d237df2dbfc8a443af2f5e84be774f08a2aed0c refs/tags/v0.1.0
            > cmp stdout .git-refs
            diff stdout .git-refs
            --- stdout
            +++ .git-refs
            @@ -1,2 +1,2 @@
            -21535ef346c3e79fd09edd75bd4725f06c828e43 refs/heads/master
            +21535ef346c3e79fd09edd75bd4725f06c828e43 refs/heads/main
             4d237df2dbfc8a443af2f5e84be774f08a2aed0c refs/tags/v0.1.0
            
            
            
        vcstest_test.go:161: issue47650.txt:19: cmp stdout .git-refs: stdout and .git-refs differ
FAIL
FAIL    cmd/go/internal/vcweb/vcstest   7.643s

It seems like it's caused by [this commit](https://cs.opensource.google/go/go/+/a839ec1e73c25d47cc329e93b9508fb53277bdd2) .

**Comment by bcmills** [comment]
Fixed by https://go.dev/cl/549155.
