### ISSUE TITLE
x/tools/gopls: update doc to include Helix editor

### ISSUE THREAD

**Issue by achenet** [golang/go#64685]
### gopls version

0.14.2

### go env

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/utilisateur/.cache/go-build'
GOENV='/home/utilisateur/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/utilisateur/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/utilisateur/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/home/utilisateur/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/home/utilisateur/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.5'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2230977179=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

I'd like to add a some documentation explaining how to setup `gopls` with the `helix` text editor

### What did you expect to see?

This isn't exactly a bug, I'd like to see more docuementation explaining how to setup `gopls` with the `helix` text editor, and given that the [contribution guidelines](https://cs.opensource.google/go/x/tools/+/refs/tags/gopls/v0.14.2:gopls/doc/contributing.md) say to create an issue first, I'm doing that.

### What did you see instead?

I'm seeing a that perhaps this form isn't perfectly suited to every type of issue.

**Comment by findleyr** [comment]
Thanks. Please feel free to send a CL contributing documentation!

**Comment by findleyr** [comment]
@achenet please see https://go.dev/doc/contribute for a guide on how to contribute to Go projects.

**Comment by achenet** [comment]
ok, thanks :)

**Comment by achenet** [comment]
opened CR:
https://go-review.googlesource.com/c/tools/+/553775

**Comment by findleyr** [comment]
Thanks! I added some comments, along with @mvdan.

**Comment by achenet** [comment]
thanks for taking the time to review it ^_^
I'll apply your suggestions and update the CR.
