### ISSUE TITLE
crypto/internal/boring/syso: boringssl builds on musl broken due to `fopen64` calls

### ISSUE THREAD

**Issue by ashishb-solo** [golang/go#64698]
### Go version

1.21.5

### What operating system and processor architecture are you using (`go env`)?

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/root/.cache/go-build'
GOENV='/root/.config/go/env'
GOEXE=''
GOEXPERIMENT='boringcrypto'
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/root/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/root/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/lib/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='local'
GOTOOLDIR='/usr/lib/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.5'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/go/src/example/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3533798560=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

I attempted to build a go program using cgo and boringssl in a Alpine 3.19 dockerfile:

```
FROM alpine:3.19

RUN mkdir -p /go/src/example
WORKDIR /go/src/example
RUN apk add go gcc musl-dev libc6-compat
ENV GOEXPERIMENT=boringcrypto
ENV CGO_ENABLED=1
RUN echo $'package main \n\
 \n\
import ( \n\
	"crypto/boring" \n\
	"fmt" \n\
) \n\
 \n\
func main() { \n\
	fmt.Println(boring.Enabled()) \n\
} \n\
' > main.go
RUN go mod init example && go mod tidy
RUN go env
RUN go build main.go
```

Changing the base image from Alpine 3.19 to 3.18 causes compilation to succeed, so this is due to a recent change in musl where symbols like `fopen64` were removed (see [here](https://gitlab.alpinelinux.org/alpine/aports/-/issues/15573#note_361848)). However, the following libraries still make calls to the removed `fopen64` symbol:

```
ashish@localhost /dev/shm/go $ git grep -w fopen64
Binary file src/crypto/internal/boring/syso/goboringcrypto_linux_amd64.syso matches
Binary file src/crypto/internal/boring/syso/goboringcrypto_linux_arm64.syso matches
```

### What did you expect to see?

Compilation should succeed

### What did you see instead?

The above quoted dockerfile failed with the following error message:

```
# command-line-arguments
/usr/lib/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /tmp/go-link-795436458/000023.o: in function `BIO_new_file':
(.text+0xcb1dc): undefined reference to `fopen64'
/usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /tmp/go-link-795436458/000023.o: in function `BIO_rw_filename':
(.text+0xcb60d): undefined reference to `fopen64'
collect2: error: ld returned 1 exit status
```

**Comment by seankhliao** [comment]
cc @golang/security

**Comment by davidben** [comment]
That #define only does whatever the libc headers decides to do with it. If musl does not provide suffixed symbols, one can assume its headers will not swap over to them.

It sounds like you may have built BoringSSL against one libc's headers and then linked it against a different libc. That cannot work. You need to build against the headers for the library you're linking against.

**Comment by mauri870** [comment]
So the problem, in summary, is:
- musl dropped support for the 64 bit names of system calls, its system calls are 64bit anyway.
- the boring syso file we provide has 64bit variants in it, this causes compilation errors with latest musl

It is not clear to me a path to resolution that does not involve either us recompiling the syso files using only the normal variants or musl providing some kind of solution to this, but since they already removed the 64bit shims I think they expect us to fix it somehow.

**Comment by FiloSottile** [comment]
> It sounds like you may have built BoringSSL against one libc's headers and then linked it against a different libc.

We build the FIPS module against glibc and then check in the object file, so that's effectively what's happening, although it's not clear to me why the BoringCrypto module would call `fopen64`.

**Comment by davidben** [comment]
Ah. I don't think anything in BCM itself calls it, but since BCM is an internal chunk of libcrypto, I assume you're building all of libcrypto and picking it up by way of the file BIO.

I assume musl does not promise to have the same ABI as glibc (given they removed a symbol glibc provides...), even if it probably accidentally matches for simple stuff. So I think that means a musl and glibc build would want to be different, or this mode should just only support glibc.

**Comment by rsc** [comment]
I'm sorry but BoringCrypto is not supported for use outside Google. We share the code with the world in case anyone wants it, but when it breaks in different environments, we don't support it. Musl is a source of many problems generally so it's unsurprising it would be a problem here too, but we're not going to take on the complexity of making musl work and keeping it working.
