### ISSUE TITLE
go build hangs forever in 1.21.x

### ISSUE THREAD

**Issue by chadgrant** [golang/go#64705]
### Go version

go version go1.21.5 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

```shell
/go # go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/root/.cache/go-build'
GOENV='/root/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='local'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.5'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='0'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3119197577=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

Seems to be happening when doing a go build in alpine docker with 1.21.4 and 1.21.5 so far, hangs forever on builds that only thing that changed was go version. When I move back to 1.20.0, my code builds fine

### What did you expect to see?

go build not hang, but compile my code

### What did you see instead?

infinite hang

**Comment by seankhliao** [comment]
please include a reproducer

**Comment by bcmills** [comment]
Or, if you can't include a reproducer, please terminate the `go build` command in a way that will produce a stack trace (by sending it `SIGQUIT` or a similar signal), and post the stack trace here so that we can see where it is getting stuck.

**Comment by chadgrant** [comment]
I will try. I can't sigterm it easily, it's running in alpine docker build stage & the code base is large/proprietary. I'll see if I can get a stack trace

**Comment by chadgrant** [comment]
This is my mistake, it's not go hanging, it's make in alpine. Sorry for the bad report
