### ISSUE TITLE
x/tools/cmd/deadcode: exit with non-zero exit code on findings

### ISSUE THREAD

**Issue by toaster** [golang/go#64713]
Currently, `deadcode` always exits with an exit code of zero, regardless of whether it has found dead code or not.

For integration in automatic linting, it would be nice to return a non-zero exit code on any findings instead.

**Comment by mauri870** [comment]
I think that is a fair point.

cc @adonovan

**Comment by adonovan** [comment]
BTW, if you have a shell, you can simulate the behavior you want with a command like this:
```
$ deadcode | tee out && [ ! -s out ] 
```
(I haven't tested it.)

**Comment by toaster** [comment]
@adonovan What if you decide to print out “No unreachable code found.” to show more explicitly that `deadcode` actually did something. Then my “output empty” check would fail while `deadcode` still behaves correctly according your claim. That’s why I avoid to rely on program output for such things.
Yes, I could use `-json` to enforce a machine readable output but that means I had to actually parse it, because even then there would be multiple possible outcomes for “nothing found”. Currently its `null` but `[]` would be valid too with the current format.
Using the exit code to signal some state is not uncommon.
So, I ask you to think about it one more time and maybe consider a `-batch` flag to enable the requested behaviour.

**Comment by adonovan** [comment]
> @adonovan What if you decide to print out “No unreachable code found.” to show more explicitly that `deadcode` actually did something. Then my “output empty” check would fail while `deadcode` still behaves correctly according your claim. 

That would violate two rules of UNIX command design: 
1. stdout is for structured output, stderr is unstructured (including progress messages and summaries); and
2. be silent when there is nothing to say.

Does the `bash -c 'deadcode | tee out && [ ! -s out ]'` command not address your scripting needs?

**Comment by musiphil** [comment]
While I agree in principle with @adonovan, there's a precedent in a different direction.

https://pubs.opengroup.org/onlinepubs/009696899/utilities/grep.html
> The following exit values shall be returned:
> 
> * 0: One or more lines were selected.
> * 1: No lines were selected.
> * \>1: An error occurred.

**Comment by adonovan** [comment]
I think one can still rationalize the distinction here: grep's job is to select lines of text. If none were selected, it failed. By contrast, deadcode's job is to analyze a Go program, compute a set of results, and print that set. But you're right, there's room for debate.

Nonetheless, your note immediately suggests an improvement over my one-liner: `deadcode | grep .`

**Comment by toaster** [comment]
@adonovan I integrated deadcode in my environment successfully. But I still would prefer exit code evaluation over output evaluation.
However, I understand your position and accept that deadcode won’t implement this behaviour.
Thanks, for discussing the topic.
