### ISSUE TITLE
crypto: upgrade to BoringCrypto fips-20220613 and enable TLS 1.3 [freeze exception]

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#64717]
Per the discussion at https://github.com/golang/go/issues/62372#issuecomment-1827476258, we decided to upgrade to BoringCrypto `fips-20220613` and enable TLS 1.3.

Since the [NIST SP 800-52 Rev. 2](https://csrc.nist.gov/pubs/sp/800/52/r2/final) deadline is January 1st, we need this in Go 1.22.

This only affects `GOEXPERIMENT=boringcrypto`.

**Comment by FiloSottile** [comment]
@gopherbot please open backport issues. All supported Go versions need to be able to comply with [NIST SP 800-52 Rev. 2](https://csrc.nist.gov/pubs/sp/800/52/r2/final) in `GOEXPERIMENT=boringcrypto` mode.

/cc @golang/release @golang/security @rsc

**Comment by dmitshur** [comment]
Thanks for letting us know. The freeze exception bit here is approved.

**Comment by yhlee-tw** [comment]
@FiloSottile and @agl 

when I checked the [CMVP #4735, 2022061300](https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4735) and the corresponding [CAVP A2811, 2022061300](https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?validation=35422), I couldn't find TLS 1.3 KDF listed (comparing with [CAVP A4687, 2023042800](https://csrc.nist.gov/projects/cryptographic-algorithm-validation-program/details?validation=37297) or [CAVP A5370, 20240407](https://csrc.nist.gov/projects/cryptographic-algorithm-validation-program/details?validation=37980)

I am unsure whether the current CMVP #4735 covers the TLS 1.3 usage as I saw it was enabled in d36353499f673c89a267a489beb80133a14a75f9 with 2022061300. (or maybe one of the newer versions is getting a cert soon, guessing from the module-in-progress)

(It's exciting to see #69536 coming)

**Comment by stevesmoot** [comment]
Looks like still lacks support here (https://go.googlesource.com/go/+/dev.boringcrypto/src/crypto/tls/handshake_server_tls13.go#47) any news?:
`
func (hs *serverHandshakeStateTLS13) handshake() error {
--
  | c := hs.c
  |  
  | if needFIPS() {
  | return errors.New("tls: internal error: TLS 1.3 reached in FIPS mode")
  | }
`

**Comment by rolandshoemaker** [comment]
@stevesmoot the dev.boringcrypto branch is deprecated and no longer used. You should be looking at master, where this check isn't present.
