### ISSUE TITLE
io: io.ReadAll(nil) panics

### ISSUE THREAD

**Issue by jim-minter** [golang/go#64714]
### Go version

go version go1.21.4 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/jimminter/.cache/go-build'
GOENV='/home/jimminter/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/jimminter/go/pkg/mod'
GONOPROXY='go.goms.io,goms.io'
GONOSUMDB='go.goms.io,goms.io'
GOOS='linux'
GOPATH='/home/jimminter/go'
GOPRIVATE='go.goms.io,goms.io'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.4'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3119686973=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

`io.ReadAll(nil)` panics.  Please consider whether alternative behavior would be better?

https://go.dev/play/p/TQg_nv6icS0

### What did you expect to see?

I'm not sure whether there's a better behavior than a panic, for example returning `nil, nil`, or `nil, <some error>`.  I don't know what the standard library policy is around this sort of thing.  It maybe that this is sufficiently unimportant and core that it's best not to change the behavior.  Please consider?

### What did you see instead?

`io.ReadAll(nil)` panics.

**Comment by seankhliao** [comment]
it's correct for it to panic on an invalid argument
