### ISSUE TITLE
x/pkgsite: link to gamble website

### ISSUE THREAD

**Issue by huberyhe** [golang/go#64711]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/github.com/astaxie/beego/validation
 
### What is your user agent?
 

 
 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
 
### Screenshot
 

 
 
![Uploading image.png…]()

 
### What did you do?
 

 
 a link in doc redirect to a gamble website, the link is http://beego.me/docs/mvc/controller/validation.md
 
### What did you expect to see?
 
 link to a document website
 
### What did you see instead?

link to a gamble website

**Comment by seankhliao** [comment]
this is documentation from the third party package, the go project has no control over where it links to

**Comment by huberyhe** [comment]
> this is documentation from the third party package, the go project has no control over where it links to

The authors of this package are using your website to spread illegal information, do you knonw?
