### ISSUE TITLE
proposal: Go 2: stub data type that doesn't waste memory and is always nil

### ISSUE THREAD

**Issue by cookiengineer** [golang/go#64737]
### Go Programming Experience

Intermediate

### Other Languages Experience

JS, JVM-based languages, Rust, Python

### Related Idea

- [ ] Has this idea, or one like it, been proposed before?
- [ ] Does this affect error handling?
- [ ] Is this about generics?
- [ ] Is this change backward compatible? Breaking the Go 1 compatibility guarantee is a large cost and requires a large benefit

### Has this idea, or one like it, been proposed before?

I couldn't find another proposal like this.

### Does this affect error handling?

No

### Is this about generics?

Maybe

### Proposal

Maybe it makes sense to explain where I'm coming from, and what I usually find myself refactoring in Go codebase ports and why I am proposing what I am proposing.

In dynamic programming languages you get (maybe incorrectly) taught that Arrays and looping over them don't matter. Specifically in JS, Arrays are not actual Arrays but just Arrays of pointers. As, behind the scenes, the Garbage Collector always has a `map[object_id] = *pointer_to_value_in_memory`, Arrays can be quickly iterated, unboxed, resorted without much performance impact.

Every time I see myself using Arrays in golang, I actually want to use a map whenever the structs that I am mapping to have a unique identifier.

Having said that, I found myself with a data- and memory-affecting challenge. I wanted to have a struct that prevents my code from executing redundant tasks which are currently already in processing (e.g. web requests, parsing, doesn't matter).

My initial implementation was just using a simple `[]string` slice with the task identifier, and then offering a method `Contains(identifier string) bool` which just returned `true` when the task ID is already known. Due to it using a `[]string` slice, I had to have a for loop there which did a `break` on successful comparison.

Finding out that millions of entries don't scale well with this, I rewrote the implementation of that tasks cache with a `map[string]bool` because I didn't know what other data type to use without messing too much with pointers that wouldn't be failsafe. `map[string]nil` doesn't seem to be allowed which I don't understand?

But, as there's a `bool` for each of those millions of entries that I don't care about, it's also wasting a lot of memory. In my case those ~2.5GB memory could've been saved if there was a data type in golang that does the following:

### Language Spec Changes

Two different proposals:

1. Allow `map[string]nil` so the map can be used for lookups and not waste memory
2. Introduce a `stub` data type with the following behaviors:

- a data type that is always `nil`
- a data type that cannot be de-referenced, and isn't copied on access so it doesn't waste memory
- a data type that cannot be set to anything else than `nil`
- a data type that doesn't use additional memory for each map entry

Behind the scenes in dynamic programming languages, this would be e.g. a `Symbol(unique identifier)` data type, and basically just have a fixed address that it would point to in order to find out its hidden class and the unique properties of the data type.

But I am not sure how this would work in golang, that's why I am proposing this discussion about it.

### Informal Change

?

### Is this change backward compatible?

Yes, very likely

**Comment by mauri870** [comment]
There is the  type `struct{}` whose size is zero, it occupies no memory. A map with type struct{} is very common in go to implement a hashset. Closing this as this is already part of the language.
