### ISSUE TITLE
access: gomote

### ISSUE THREAD

**Issue by qiulaidongfeng** [golang/go#64732]
See https://go.dev/wiki/Gomote , I'd like to request access to the gomote service.

I'm interested in investigating alignment optimizations for non-x86 on #63678, but I only have x86 machine,
In my experience with #63661, there are too many problems with using qemu, and it is better to use non-QEMU to study non-x86 optimizations.

cc @golang/release

**Comment by dmitshur** [comment]
CC @mdempsky.

**Comment by cherrymui** [comment]
Apologies for the delay. We don't have a lot of practice with these requests.

Thanks for your contributions and making this access request. Unfortunately gomote access does not give you want you need. It is not a great platform for performance and optimization work. Also, for security reasons the bar for gomote access is very high, so it needs a longer history of contributions and demonstrated familiarity with the Go project before granting access can be considered. I'm going to close this for now. Thanks.
