### ISSUE TITLE
Incorrect generic type inference

### ISSUE THREAD

**Issue by shove70** [golang/go#64734]
### Go version

go1.21.x

### What operating system and processor architecture are you using (`go env`)?

```shell
https://golang.google.cn/play/
```

### What did you do?

```go
package main

package main

import "fmt"

func foo[T any](arr []T) {
	fmt.Println(arr)
}

func main() {
	arr := []int{1, 2, 3}
	foo(arr)
}
```

### What did you expect to see?

```
[[1, 2, 3]]
```
It should be a two-dimensional array

### What did you see instead?

```
[1, 2, 3]
```
-----------

Looking at this again, the inferred behavior is inconsistent:
```go
package main

import "fmt"

func foo[T any](arr T) {
	fmt.Println(arr)
	bar(arr)
}

func bar[T any](arr []T) {
	fmt.Println(arr)
}

func main() {
	arr := []int{1, 2, 3}
	foo(arr)
}
```
outputs:
```
./prog.go:7:6: type T of arr does not match []T (cannot infer T)

Go build failed.
```

**Comment by shove70** [comment]
@chad-bekmezian-snap Are you sure you've read it and thought about it?

**Comment by mateusz834** [comment]
I don't get your point, to get the second example working you have to use a slice, like:
```diff
package main

import "fmt"

func foo[T any](arr T) {
	fmt.Println(arr)
-	bar(arr)
+	bar([]T{arr})
}

func bar[T any](arr []T) {
	fmt.Println(arr)
}

func main() {
	arr := []int{1, 2, 3}
	foo(arr)
}

```

**Comment by shove70** [comment]
Thank you for your response,

First example:
arr ->  []T is inferred as []int
A second example:
arr ->  []T reports an error

The inference results are different for the two examples

**Comment by mateusz834** [comment]
Yes, and that behavior makes sense for me.
The second example reports an error, because in `foo[T any](arr T)` the arr passed (`[]int`) is not treated as an an slice, but as a `T`. You could have passed a `int` instead of a slice. Go is not going to create an implicit slice in this case.

**Comment by mateusz834** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
