### ISSUE TITLE
x/website: displays the content of the index.html file instead of the file list

### ISSUE THREAD

**Issue by LionelMartin** [golang/go#64754]
### What is the URL of the page with the issue?

https://go.dev/src/net/http/testdata/

### What is your user agent?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:120.0) Gecko/20100101 Firefox/120.0

### Screenshot

![image](https://github.com/golang/go/assets/133224/bc639a90-117c-4c41-98ea-de4b45fc79eb)

### What did you do?

Just getting on the page

### What did you expect to see?

a list of files in testdata/

### What did you see instead?

the content of probably an index.html file

**Comment by mauri870** [comment]
Huh,  there is an index.html inside testdata and the webserver is configured to open index.html automatically.

There is not much to browse inside testdata though, so I'm not sure if there is anything to fix really.

/cc @golang/tools-team per https://dev.golang.org/owners

**Comment by suzmue** [comment]
That directory was added to test that the fileserver will serve the index.html file if it exists ([https://golang.org/cl/4798071](https://golang.org/cl/4798071)), so appears to be WAI. As @mauri870 mentioned, there's not much to browse so it probably is not worth trying to do anything special about it.
