### ISSUE TITLE
access: go-assignees and go-editors

### ISSUE THREAD

**Issue by Jorropo** [golang/go#64808]
See https://go.dev/wiki/GithubAccess

https://github.com/orgs/golang/teams/go-assignees
https://github.com/orgs/golang/teams/go-editors

I enjoy reading the issue tracker I would like to be able to retitle issues and triage some bugs as per https://go.dev/wiki/Gardening.

Github: @Jorropo

**Comment by seankhliao** [comment]
cc @golang/release

**Comment by dmitshur** [comment]
CC @thanm.

**Comment by thanm** [comment]
Hi, this may take a few days, please bear with us (lots of folks out on vacation etc at the moment).

**Comment by Jorropo** [comment]
@thanm it sounds like you should be spending time whatever you do around theses times of year than handling this github issue.

Enjoy :heart:

**Comment by Jorropo** [comment]
I received an invitation, thx.

**Comment by dmitshur** [comment]
Great, glad it worked! We have indeed approved this request, just missed leaving a comment here.

As mentioned in the [wiki](https://go.dev/wiki/GithubAccess#editors), please do not edit any field you're not confident about, and feel free to ask for second opinions.

Thanks for your help!
