### ISSUE TITLE
x/mobile: .aar file does not show function parameters

### ISSUE THREAD

**Issue by Thiagohalves85** [golang/go#64816]
Hello.
When I create the .aar file with bind when using the function, its parameters come as var0, var1... instead of the correct name.
Is there any way when generating the .aar file that the function has the correct names?
Thanks.

1- gomobile bind -androidapi 24  -target=android -ldflags="-s -w" -o app/spdnfe_componente.aar ./framework/spdnfe 

2- Created spdnfe_componente.aar

3- Import lib in Android Studio

4- call any function the arguments are like var0, var1

Go Version 1.21.4

Go env

set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\thiago.alves\AppData\Local\go-build
set GOENV=C:\Users\thiago.alves\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\thiago.alves\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\thiago.alves\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.21.4
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\thiago.alves\Documents\Estudo\Go\shared-library\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\THIAGO~1.ALV\AppData\Local\Temp\go-build1670470057=/tmp/go-build -gno-record-gcc-switches

**Comment by hyangah** [comment]
If I remember correctly, `bind` preserves the parameter names in source code generation level. I don't know whether all the info is preserved when building aar out of the generated source code.

(see the test case: https://github.com/golang/mobile/blob/76ac6878050a2eef81867f2c6c21108e59919e8f/bind/testdata/basictypes.objc.h.golden#L30, translating https://github.com/golang/mobile/blob/76ac6878050a2eef81867f2c6c21108e59919e8f/bind/testdata/basictypes.go#L17)

The `-x -v` flags will print what `gomobile bind` is doing underneath. I hope that helps you inspect where the info is dropped. `x/mobile/cmd/gobind` will also help investigate whether the source code generation is working as you expected.

**Comment by Thiagohalves85** [comment]
Thanks for the help @hyangah, but I still haven't been able to find out why the name of the properties doesn't appear in the method, I'll continue searching.
