### ISSUE TITLE
spec: inconsistent map initialization with composite literal

### ISSUE THREAD

**Issue by icza** [golang/go#64817]
### Go version

go version go1.21.5 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/icza/.cache/go-build'
GOENV='/home/icza/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/icza/gows/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/icza/gows'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.5'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1145286549=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

I used a composite literal to initialize a map where one key is a constant string, another is a variable whose value equals to the other constant key.

Example (try it on the [Go Playground](https://go.dev/play/p/QEQ6uSIHrkO)):

	s := "foo"

	m := map[string]int{
		"foo": 1,
		s:     2,
	}
	fmt.Println(m) // Prints map[foo:2]

	m2 := map[string]int{
		s:     2,
		"foo": 1,
	}
	fmt.Println(m2) // Prints map[foo:2]

### What did you expect to see?

I expected different result map (key-value pairs) depending on the order of the listed elements, so I expected the following output:

    map[foo:2]
    map[foo:1]

### What did you see instead?

The result does not depend on listed element order:

    map[foo:2]
    map[foo:2]

[Spec: Composite literals:](https://go.dev/ref/spec#Composite_literals)

> It is an error to specify multiple elements with the same field name or constant key value. For non-constant map keys, see the section on [evaluation order](https://go.dev/ref/spec#Order_of_evaluation).

I believe the above does not imply that pairs with constant keys are added first. If so, the output should depend on the element order. If the above implies that, the wording should be changed to make it clear and obvious.

**Comment by thanm** [comment]
@griesemer for questions relating to the Go spec

**Comment by Jorropo** [comment]
```
m := map[int]int{a: 1, a: 2}  // m may be {2: 1} or {2: 2}: evaluation order between the two map assignments is not specified
```
Looks valid to me. This is one of the rare cases of golang UB.

**Comment by gophun** [comment]
> This is one of the rare cases of golang UB.

Nitpick: implementation defined, not UB: https://groups.google.com/g/golang-nuts/c/MB1QmhDd_Rk

**Comment by randall77** [comment]
Yes, this is odd but it is allowed by the spec. @Jorropo quotes the appropriate part of the spec - each entry, and the order in which they are placed in the map, is not defined by the spec.

@icza The part you are quoting, "It is an error...", applies only to to conflicts between two entries with constant (in the spec sense) keys, which is not the case in your example. It also means that you will get a compiler error in that case, not that the compiler is free to miscompile it.
