### ISSUE TITLE
x/tools/gopls: Extract function not handle anonymous functions correctly

### ISSUE THREAD

**Issue by rogeryk** [golang/go#64821]
### gopls version

v14.2

### go env

```shell
unimportant
```

### What did you do?

In the following example, select all main function body, then toggle "Extract function"
```go
func main() {
	var s []string
	slices.SortFunc(s, func(a, b string) int {
		return cmp.Compare(a, b)
	})
	println(s)
}
```

### What did you expect to see?

```go
func main() {
	newFunction()
}

func newFunction() {
	var s []string
	slices.SortFunc(s, func(a, b string) int {
		return cmp.Compare(a, b)
	})
	println(s)
}
```

### What did you see instead?

```go
func main() {
	shouldReturn := newFunction()
	if shouldReturn {
		return
	}
}

func newFunction() bool {
	var s []string
	slices.SortFunc(s, func(a, b string) int {
		return true, cmp.Compare(a, b)
	})
	println(s)
	return false
}
```

**Comment by adonovan** [comment]
The bad news is that "extract function" has a lot of serious bugs that make it a use-at-your-own peril sort of feature: notably, it discards all comments in the code that migrates. The good news is that it is a priority for our team in 2024 to improve all of our refactoring tools.

**Comment by findleyr** [comment]
Thanks @golopot for this fix.
