### ISSUE TITLE
go mod tidy for large monorepos?

### ISSUE THREAD

**Issue by rc-glean** [golang/go#64827]
### Go version

go version go1.19.13 darwin/arm64

### What operating system and processor architecture are you using (`go env`)?

```shell
GO111MODULE=""
GOARCH="arm64"
GOBIN="/Users/ray/go/bin"
GOCACHE="/Users/ray/Library/Caches/go-build"
GOENV="/Users/ray/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/ray/go/pkg/mod"
GONOPROXY="github.com/REDACTED"
GONOSUMDB="github.com/REDACTED"
GOOS="darwin"
GOPATH="/Users/ray/go"
GOPRIVATE="github.com/REDACTED"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go@1.19/1.19.13/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go@1.19/1.19.13/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.13"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/r4/nj9c_6_x4xj1zsznv8ppgtvm0000gn/T/go-build1209950060=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?

Ran `go mod tidy`

### What did you expect to see?

**Expected**: tidy finishes. Instead it failed due to ~500mb limit below.

### What did you see instead?

```
go: downloading github.com/REDACTED
go: github.com/REDACTED: create zip: module source tree too large (max size is 524288000 bytes)
```

**High level question**: does `go mod tidy` have good mono-repo support?

Our observation is that our golang code is correct from passing our bazel (build|test) ops, but `go mod tidy` attempts to download our entire mono-repo and fail on the ~500mb limit.

Our strategy is to only use a single go.mod for external dependency pinning, and use bazel and gazelle for dependency management. Splitting multiple go.mod's is not palatable to us, as prior issues recommend https://github.com/golang/go/issues/40780#issuecomment-674107553. The splitting also probably doesn't help cases where `go mod tidy` tries to download the whole monorepo

Are there options for bypassing the 500mb limit? It's also not clear to us why `go mod tidy` attempts to download our entire monorepo again, given `go mod tidy` is running locally within the already-checked-out-monorepo.

**Comment by seankhliao** [comment]
there is no bypass for the 500MB limit.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
