### ISSUE TITLE
Go build -buildmode=c-shared . Is regenerating the library everytime (timestamp change is observed) even though there is no change in the source

### ISSUE THREAD

**Issue by chendu471** [golang/go#64832]
Using the go version 1.19.10, is there any extra build flags to use to overcome this ?. We are already using the GOCACHE.

**Comment by thanm** [comment]
Please see https://github.com/golang/go/issues/47788#issuecomment-954890659 , which describes why we are not fixing bugs in shared build mode, with its attendant problems.
