### ISSUE TITLE
proxy.golang.org: 

### ISSUE THREAD

**Issue by davidkhala** [golang/go#64840]
github.com/davidkhala/fabric-common/golang v2.0.1 cannot be found 30 minutes after release

**Comment by davidkhala** [comment]
Meanwhile please help to remove module github.com/davidkhala/fabric-common
It was not desired to be publish.

**Comment by gophun** [comment]
Wouldn't the module name in go.mod need to have "/v2" at the end (github.com/davidkhala/fabric-common/golang/v2)?
https://github.com/davidkhala/fabric-common/blob/master/golang/go.mod#L1

**Comment by seankhliao** [comment]
see above, also please us retract for removal
