### ISSUE TITLE
wiki: RangefuncExperiment link to issue tracker for feedback 

### ISSUE THREAD

**Issue by marwan-at-work** [golang/go#64858]
Hi there 👋🏼 

The following link has no mention of an issue tracker or a feedback form that people in 1.22 turning on the experiment can use to give their feedback: https://go.dev/wiki/RangefuncExperiment

It would be great if one was included since I assume the point of the experiment is for users to experiment and report back :) 

Thanks!

PS. Sorry for not following any of the issue templates, as I'm not sure which one was appropriate.

**Comment by seankhliao** [comment]
i think the expectation is that feedback is filed as bugs or proposals like any other issue with the language.

**Comment by dmitshur** [comment]
Also see https://github.com/golang/go/issues/61405#issuecomment-1876962764.

CC @rsc.

**Comment by ianlancetaylor** [comment]
I don't think anybody ever got around to this, and at this point this is obsolete.
