### ISSUE TITLE
encoding/json: UnmarshalJSON causes panic

### ISSUE THREAD

**Issue by master255** [golang/go#64850]
### Go version

1.21.1

### What operating system and processor architecture are you using (`go env`)?

```shell
Android
```

### What did you do?

err := json.Unmarshal(bootstrap, &peersAddrs)

### What did you expect to see?

Get the error in the err variable

### What did you see instead?

panic in this line https://github.com/golang/go/blob/2184a394777ccc9ce9625932b2ad773e6e626be0/src/encoding/json/decode.go#L360

This method (and maybe other) should not cause a panic, but should return an error.
Otherwise, I hope for quiet operation of the method, but it causes the whole application to crash.

**Comment by odeke-em** [comment]
Thank you for filing this issue @master255! 

Your report currently is not actionable because it provides a single line of code without context of what could be going wrong, nor the stacktrace of the panic. Could you please provide a minimized complete runnable reproducer for the panic as well as the stacktrace? Thank you.

**Comment by master255** [comment]
No. That's impossible. Panic triggers unsteadily and I don't know what it's related to.

**Comment by seankhliao** [comment]
seems like a problem of your code rather than the standard library.

**Comment by master255** [comment]
@seankhliao But here in the code you can see that panic is called, and the method returns an error and should not call panic. Why do you ignore it?

**Comment by seankhliao** [comment]
it violates invariants of the system that make it unsafe to continue, a panic is appropriate.

**Comment by master255** [comment]
@seankhliao No, it's not. It is necessary that json.Unmarshal does not cause panic. How do I do that?

**Comment by master255** [comment]
@seankhliao Are you a programmer without logic?

**Comment by atdiar** [comment]
@master255 Please respect the code of conduct. Thanks.

**Comment by master255** [comment]
@atdiar I want a very simple thing - not to get panic in json.Unmarshal. That my application won't completely terminate because of it. 
All other languages have try catch and that fixes the problem.
Golang has no try catch. So there should be no panic here if an error is supposed to be returned. Under no circumstances!
Even if the data is being edited while json.Unmarshal is happening.
I want to get an error and ignore it or react somehow.
And I'm very surprised that such simple things it is necessary to explain to people here. This is something new.

**Comment by atdiar** [comment]
If the unmarshalling panics, you have a bigger problem than it not returning an error.

That's the point of panicking here.

If your code is correct, it should never even hit that case so this is not something to worry about.
If you have a race in your code, might as well panic too.

**Comment by master255** [comment]
@atdiar try catch catches any problem. What makes you think there are big and small problems at all? All problems are equal. If even a small error occurs, the application stops working. Just like when a big error occurs.
So it is not logical to cause panic for a certain kind of error and not for another kind of error.

**Comment by atdiar** [comment]
Panics are recoverable.
If that's really what you need, I recommend reading:

https://go.dev/blog/defer-panic-and-recover

**Comment by master255** [comment]
@atdiar But it is necessary for me to ignore the error and continue executing the program. Not to catch the error. How do I do that?

**Comment by atdiar** [comment]
Perhaps that you can use a closure to call your json.Unmarshal

**Comment by seankhliao** [comment]
For questions please refer to https://github.com/golang/go/wiki/Questions
