### ISSUE TITLE
stdlib: clear() behavior 

### ISSUE THREAD

**Issue by melekhine** [golang/go#64873]
### Go version

go version go1.21.5 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/Users/igor/Library/Caches/go-build'
GOENV='/Users/igor/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/igor/go/pkg/mod'
GONOPROXY='github.com/takefrom/new'
GONOSUMDB='github.com/takefrom/new'
GOOS='darwin'
GOPATH='/Users/igor/go'
GOPRIVATE='github.com/takefrom/new'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/Cellar/go/1.21.5/libexec'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/Cellar/go/1.21.5/libexec/pkg/tool/darwin_amd64'
GOVCS=''
GOVERSION='go1.21.5'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/37/q5mbdk7545z1v59_qm6zg5340000gn/T/go-build885871997=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

https://go.dev/play/p/oUosdciYDJP

Say we have a `[]T` slice, after `clear([]T)` I expect len of slice will be 0, instead we have all elements inside, just with removed data.

### What did you expect to see?
len=0

As documentation say:
> The clear built-in function clears maps and slices. For maps, clear deletes all entries, resulting in an empty map. For slices, clear sets all elements up to the length of the slice to the zero value of the respective element type. If the argument type is a type parameter, the type parameter's type set must contain only map or slice types, and clear performs the operation implied by the type argument.

But im really don't get it, why it's supposed not to remove all elements, but keep them. Maybe its call something like reset?

### What did you see instead?

len=1

**Comment by gophun** [comment]
This works as intended and documented: https://pkg.go.dev/builtin#clear

> For slices, clear sets all elements up to the length of the slice to the zero value of the respective element type.

If you expect a function to be able change the length of a slice parameter then you need to (re-)learn the basics of slices.
