### ISSUE TITLE
encoding/json: Add Encoder.Indent

### ISSUE THREAD

**Issue by kisielk** [golang/go#6492]
<pre>This is a feature request for encoding/json post-Go 1.2

It would be great if json.Encoder had an Indent method like xml.Encoder does. Currently
the only way to get indented JSON is to use MarshalIndent but that requires an
intermediate []byte.</pre>

**Comment by abourget** [comment]
+1 !

**Comment by robmuh** [comment]
Any word on this? I might take a stab at since I need it at the moment.

**Comment by bradfitz** [comment]
Stab away.

**Comment by NioTeX** [comment]
any news here? I would also need it :+1:

**Comment by rsc** [comment]
No news.

**Comment by cespare** [comment]
I'm going to try to do this for 1.7.
