### ISSUE TITLE
access: members and approvers

### ISSUE THREAD

**Issue by erifan** [golang/go#64924]
Please help to transfer all permissions (including go-member, gerrit-approver) of this Github&Gerrit account (eric.fang@arm.com) to my new Github&Gerrit account (657423312@qq.com). Because I no longer work at Arm, I can no longer use this email account and cannot modify the information, so this account will no longer exist. In the future, I will contribute to this community with my personal account (657423312@qq.com), so please transfer the permissions of my old account to the new account, thank you.
cc @golang/release

**Comment by seankhliao** [comment]
is your GitHub account changing (if yes, what's the new name?) or is it just the Gerrit account?

**Comment by erifan** [comment]
> is your GitHub account changing (if yes, what's the new name?) or is it just the Gerrit account?

It's @fangsm26 Both Github and Gerrit account. Thanks.

**Comment by dmitshur** [comment]
CC @mdempsky.

**Comment by fangsm26** [comment]
Hi, I successfully changed my Github email address, so please leave my Github account as it is. But I cannot modify the information of my Gerrit account, so please help transfer the permissions of my Gerrit account. Thank you.

**Comment by erifan** [comment]
Hi, I successfully changed my Github email address, so please leave my Github account as it is. But I cannot modify the information of my Gerrit account, so please help transfer the permissions of my Gerrit account. Thank you.

**Comment by dmitshur** [comment]
I've transferred the Gerrit [approvers](https://go.dev/wiki/GerritAccess#approving-cls-approvers) access from `eric.fang@arm.com` to `657423312@qq.com`, and mailed [CL 555459](https://go.dev/cl/555459) to update your entry in gophers.go. Please let me know if it's not working as expected. Thank you for contributing to Go.
