### ISSUE TITLE
go/parser : parser go src file then printf to file, format error

### ISSUE THREAD

**Issue by LY1806620741** [golang/go#64927]
### Go version

go version go1.21.5 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

```shell
GO111MODULE='on'
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/dev/.cache/go-build'
GOENV='/home/dev/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/dev/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/dev/go'
GOPRIVATE=''
GOPROXY='https://goproxy.cn,direct'
GOROOT='/usr/local/go'
GOSUMDB='off'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.5'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/dev/Desktop/mkcert-autoconfig/i18ntools/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3963334977=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

main.go
```go
        sourcepath := "../cert.go"
	node, _ := parser.ParseFile(fset, sourcepath, nil, parser.ParseComments|parser.AllErrors)
        file, _ := os.OpenFile("cert_edit.go", os.O_CREATE|os.O_WRONLY, os.ModePerm)
	defer file.Close()
	if err := printer.Fprint(file, fset, node); err != nil {
		log.Fatalln("Error:", err)
	}
```

cert.go from https://github.com/LY1806620741/mkcert-autoconfig/blob/111715b04f1ff91ff297b9652fcc31e5ab3ff4f1/cert.go#L37

### What did you expect to see?

new file cert_edit.go the same as cert.go

### What did you see instead?

go parser rewrite cert.go code but duplicate code inserted. But I didn't operate the ast tree.
![image](https://github.com/golang/go/assets/25952861/fa61f2d8-2d96-4ed4-9e4f-f54be6a2b801)

**Comment by mauri870** [comment]
I just tried this locally and it appears to be working as expected.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to [https://github.com/golang/go/wiki/Questions](https://github.com/golang/go/wiki/Questions)

**Comment by LY1806620741** [comment]
> I just tried this locally and it appears to be working as expected.
> 
> Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.
> 
> For questions please refer to https://github.com/golang/go/wiki/Questions

Thank you for your reply. This issue is caused by not resetting the content of the opened file.
```
file:=os.OpenFile
//resolvent
file.Truncate(0)
file.write
```
