### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by arunsingh28** [golang/go#64932]
### What is the URL of the page with the issue?
[]( https://go.dev/doc/tutorial/create-module)
 
 
### What is your user agent?
`[Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36](https://explore.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)`
   
 
### Screenshot
 
 
<img width="706" alt="Screenshot 2024-01-02 at 4 37 31 PM" src="https://github.com/golang/go/assets/48112517/0d308e05-a61a-43c7-9734-6fb9a52e1b2e">
<img width="654" alt="Screenshot 2024-01-02 at 4 37 51 PM" src="https://github.com/golang/go/assets/48112517/c174f6ff-e028-4a7f-b573-29737f027db0">
 
 
 
### What did you expect to see?

When in dark mode and attempting to change the theme, I observed that although the icon associated with the theme updates immediately, the actual theme itself does not reflect the change until I perform an additional click. This behavior results in a discrepancy between the displayed theme icon and the applied theme.
 
 
### What did you see instead?

it should the change the theme when i click on the change theme icon

**Comment by seankhliao** [comment]
It's a 3 state button: light, dark, system.
I believe this is working as intended.
