### ISSUE TITLE
cmd/cgo: building with clang 13 errors out with `unknown warning group '-Wunaligned-access'`

### ISSUE THREAD

**Issue by bjackman** [golang/go#64943]
### Go version

go version go1.22-20230908-RC04 cl/563875016 +2fe2f08542 X:fieldtrack,boringcrypto linux/amd64

### What operating system and processor architecture are you using (`go env`)?

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/usr/local/google/home/jackmanb/.cache/go-build'
GOENV='/usr/local/google/home/jackmanb/.config/go/env'
GOEXE=''
GOEXPERIMENT='fieldtrack,boringcrypto'
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/usr/local/google/home/jackmanb/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/usr/local/google/home/jackmanb/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/lib/google-golang'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/lib/google-golang/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22-20230908-RC04 cl/563875016 +2fe2f08542 X:fieldtrack,boringcrypto'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2390478846=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

```
mkdir /tmp/go-rand
cd /tmp/go-rand
cat > tst.go << EOF
package main

import (
        "crypto/rand"
)

func main() {
        var r rand.Reader
}
EOF
go build tst.go
```

### What did you expect to see?

Successful build

### What did you see instead?

`_cgo_export.c:9:32: error: unknown warning group '-Wunaligned-access', ignored [-Werror,-Wunknown-warning-option]`

Exit code 1.

In case it's not obvious - I'm a Googler and this is gLinux. I'm reporting via Github per the internal instructions. Apologies if I've misunderstood there!

**Comment by bjackman** [comment]
See also https://github.com/golang/go/issues/62580 which has the same error message. But the CL is way out of that range.

**Comment by bcmills** [comment]
The CL mentioned in #62580 was reapplied in https://go.dev/cl/528935 with an additional `-Wunknown-warning-option` pragma. Perhaps the version of Clang you're using _also_ doesn't support the `-Wunknown-warning-option` pragma?

(What does `clang --version` report for you?)

**Comment by bjackman** [comment]
```
$ clang --version
clang version 13.0.0 (https://github.com/llvm/llvm-project.git 28ab7ff2d732fb0580486baa02b1383a72cec0cb)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
```

Sounds like a good explanation

**Comment by bjackman** [comment]
Not sure if this was already obvious but just to confirm, this is not actually specific to package `crypto/rand` - I get the same thing whenever I `import "C"` myself too.

**Comment by bjackman** [comment]
Workaround: Get a newer Clang and set the `CC` environment variable to the clang binary path. Googlers can try go/crosstool-outside-google3#wrapper-scripts

**Comment by bjackman** [comment]
Was wondering why this isn't affecting more people - suddenly noticed the `InstalledDir: /usr/local/bin` in https://github.com/golang/go/issues/64943#issuecomment-1875554577. Apparently at some point I did a system-wide installation of Clang from source. So my combination of Clang and Go versions is weird and unusual. So probably this can be deprioritised or maybe it's even WAI.

**Comment by mknyszek** [comment]
@bjackman Given that this seems to possibly related to your particular version of Clang, I'm going to optimistically close this for now. If you run into any problems with a more stable (?) version of Clang, feel free to comment. Thanks.

**Comment by bjackman** [comment]
Just to be clear I don't think this is a case of Clang instability, I think this is probably a genuine incompatibility between Go version 1.22 and Clang version 13.0.0.

However I think it's likely nobody else will ever have that combination of versions so optimistically closing still makes sense.
