### ISSUE TITLE
> We could use this e.g. to have different templates for proposals vs regular issues.

### ISSUE THREAD

**Issue by mrsone40** [golang/go#64950]
> We could use this e.g. to have different templates for proposals vs regular issues.

Adding a `.github/ISSUE_TEMPLATE/proposal.md` sounds reasonable to me.

> On the other hand, it adds another click between golang.org/issue/new and actually typing text.

I don't understand why that would be, can you elaborate? As I understand, [golang.org/issue/new](https://golang.org/issue/new) would continue to redirect to https://github.com/golang/go/issues/new, which would continue to use the default `.github/ISSUE_TEMPLATE.md` template (we'd have to give the [existing file](https://github.com/golang/go/blob/8e50e48f4ddd434b848240837a02a487d502b3ee/.github/ISSUE_TEMPLATE) an .md extension to not collide with the new directory). From the GitHub blog post:

> Your default ISSUE_TEMPLATE.md files will continue to work as the default when a template isn’t specified in the new issue URL.

To get to the proposal template, one would have to visit https://github.com/golang/go/issues/new?template=proposal.md. We could consider making a shortlink on golang.org for it, for example golang.org/issue/new?template=proposal.md or golang.org/issue/new/proposal.

The [`go bug` command](https://golang.org/cmd/go/#hdr-Start_a_bug_report) is relevant here, but I don't think it needs to support making proposals.

_Originally posted by @dmitshur in https://github.com/golang/go/issues/29839#issuecomment-456180389_

**Comment by dmitshur** [comment]
@mrsone40 Can you please explain the purpose of taking an individual comment from an old, closed issue and creating a new issue with it? Thanks.

**Comment by seankhliao** [comment]
these are just spam issues we get all the time.
