### ISSUE TITLE
Error: `go install -buildmode=plugin` fails while `go install` works

### ISSUE THREAD

**Issue by thockin** [golang/go#64964]
### Go version

1.22 (gotip)

### What operating system and processor architecture are you using (`go env`)?

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/thockin/.cache/go-build'
GOENV='/home/thockin/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/dev/null/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/dev/null'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/home/thockin/sdk/gotip'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/home/thockin/sdk/gotip/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='devel go1.22-46ea4ab5cb Sat Dec 9 21:48:06 2023 +0000'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/thockin/src/kubernetes/go.mod'
GOWORK='/home/thockin/src/kubernetes/go.work'
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build11502135593448817437=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

This works:
```
$ go install github.com/aojea/sloppy-netparser; echo $?
0
```

This does not:
```
$ go install -buildmode=plugin sigs.k8s.io/logtools/logcheck/plugin; echo $?
go: no install location for directory /tmp/gp/pkg/mod/sigs.k8s.io/logtools@v0.8.0/logcheck/plugin outside GOPATH
For more details see: 'go help gopath'
1
```

Both `github.com/aojea/sloppy-netparser` and `sigs.k8s.io/logtools` are in the go.mod file

### What did you expect to see?

I expected `go install -buildmode=plugin` to work, because `go install` works and `go build -buildmode=plugin` works.

### What did you see instead?

go: no install location for directory /tmp/gp/pkg/mod/sigs.k8s.io/logtools@v0.8.0/logcheck/plugin outside GOPATH

**Comment by seankhliao** [comment]
I believe this is intended, `install` creates an executable and places it in the executable dir `GOBIN`, `build -buildmode=plugin` creates a not directly executable thing, so it shouldn't go there.

It works in GOPATH mode where there's `GOPATH/pkg` for half built things, but this doesn't apply to module mode.
