### ISSUE TITLE
x/tools/cmd/goimports: 

### ISSUE THREAD

**Issue by leathem1** [golang/go#64960]
I am installing:  go install golang.org/x/tools/cmd/goimports@latest

however now when attempting to MAKE BUILD I get errors saying goimports is bad.

sh-5.1$ sudo make build
gofmt -w=true -s $(find . -type f -name '*.go' -not -path "./vendor/*" -not -path "./pb/*")
goimports -w=true -d -local github.com/atlassian/gostatsd $(find . -type f -name '*.go' -not -path "./vendor/*" -not -path "./pb/*")
/bin/sh: line 1: goimports: command not found
make: *** [Makefile:53: fmt] Error 127

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
