### ISSUE TITLE
encoding/json: speed up decoding

### ISSUE THREAD

**Issue by bradfitz** [golang/go#6496]
<pre>JSON decoding could be faster.

Various CLs have been tossed about and/or discussed on the mailing lists.

Here's one, for after Go 1.2 is out: <a href="https://golang.org/cl/13894045/">https://golang.org/cl/13894045/</a></pre>

**Comment by rsc** [comment]
This is too vague to be actionable. It's fine to create new issues with specific cases that should be faster.
