### ISSUE TITLE
x/pkgsite: incorrect latest release for dvyukov/go-fuzz

### ISSUE THREAD

**Issue by cristaloleg** [golang/go#64968]
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/dvyukov/go-fuzz

### What is your user agent?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

### Screenshot

<img width="556" alt="image" src="https://github.com/golang/go/assets/366002/db009840-3df0-43d1-81ef-ad5829762140">

### What did you do?

I decided to fetch the latest commit of github.com/dvyukov/go-fuzz and found that pkg.go.dev shows incorrect latest release.

Currently I see `Published: Oct 19, 2023` as the latest release, however there is a commit dated `Published: Dec 14, 2023` 

On the page with all the latest commits/releases the Dec 14 commit is shows as a recent https://pkg.go.dev/github.com/dvyukov/go-fuzz?tab=versions

### What did you see happen?

<img width="474" alt="image" src="https://github.com/golang/go/assets/366002/6145260f-949d-44f2-ac02-dbdbabb04535">

### What did you expect to see?

<img width="505" alt="image" src="https://github.com/golang/go/assets/366002/bf3eb0f6-a3d2-4cf7-a0f9-fbd985424ea2">

**Comment by bcmills** [comment]
For comparison, https://proxy.golang.org/cached-only/github.com/dvyukov/go-fuzz/@latest lists the correct version:
```json
{"Version":"v0.0.0-20231214143802-7955ebc9f2de","Time":"2023-12-14T14:38:02Z","Origin":{"VCS":"git","URL":"https://github.com/dvyukov/go-fuzz","Hash":"7955ebc9f2de3517b13dcac8425fcbe7da75287a"}}
```

**Comment by cristaloleg** [comment]
Also https://pkg.go.dev/github.com/jackc/pgservicefile@v0.0.0-20221227161230-091c0ba34f0a?tab=versions 

Commit from 2023 isn't show as the latest. Looks like the problem touches repositories without a tag.

**Comment by findleyr** [comment]
Looks like our queue was stuck -- we had related internal alerts fire. This has been addressed, and it looks like both of these instances have caught up.
