### ISSUE TITLE
x/playground: Go 1.20 always times out

### ISSUE THREAD

**Issue by rittneje** [golang/go#64975]
### Go version

n/a

### Output of `go env` in your module/workspace:

```shell
n/a
```

### What did you do?

Tried to run the hello world example in the playground with Go 1.20. https://go.dev/play/?v=goprev

### What did you see happen?

> timeout running program
> Go build failed.

### What did you expect to see?

Hello, 世界

**Comment by seankhliao** [comment]
it seems to work (now)?

**Comment by rittneje** [comment]
@seankhliao Indeed. Maybe someone fixed it?
