### ISSUE TITLE
x/vuln: govulncheck support `-hide-unused` in text mode

### ISSUE THREAD

**Issue by hitzhangjie** [golang/go#64970]
### govulncheck version

Go: go1.21.4
Scanner: govulncheck@v1.0.2-0.20231220041129-7335627909c9
DB: https://vuln.go.dev
DB updated: 2024-01-04 18:39:51 +0000 UTC

No vulnerabilities found.

Share feedback at https://go.dev/s/govulncheck-feedback.

### Does this issue reproduce at the latest version of golang.org/x/vuln?

Yes.

### Output of `go env` in your module/workspace:

```shell
GO111MODULE='on'
GOARCH='amd64'
GOBIN=''
GOCACHE='/root/.cache/go-build'
GOENV='/root/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/root/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/root/go'
GOPRIVATE=''
GOPROXY='direct'
GOROOT='/usr/local/go'
GOSUMDB='off'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.4'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='xxxxx/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4126326493=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

Hi, when I run `govulncheck ./...` to check the vulnerabilities of my project, It outputs the --- informational --- section， which means it is only imported or required rather than have been used.

I want to suppress the output of the --- informational --- part, I think it could be ignored. At least, we could provide an option `-hide-unused` to support this.

And, I read the code to support this:
1. for the TextHandler, it's easy to support this. Just add an flag -hide-unused and make some changes to the `TextHandler.Flush()`. The task will be done.
2. but for the jsonHandler, it's not that easy to support this. Actually jsonHandler will output the CSVs associated with current imported modules in the underlying JSON encoder, and then output the findings. 
3. The documentation doesn't describe the goals of textmode and jsonmode, so I don't know if I should make changes to the jsonHandler.

Now I only fork and make changes to the textmode. 

### What did you see happen?

It outputs the --- informational --- part, which contains the vulnerabilities associated with the only imported or required modules.

### What did you expect to see?

I hope we could support an option -hide-unused.
when -hide-unused specified, don't output the --- informational --- part.

**Comment by zpavlinovic** [comment]
We are in the process of redesigning the textual output. By default, the informational section will be omitted in its current form and only a short single-sentence summary will be provided. More details will be hidden under a flag. I believe that will address your concerns.

**Comment by hitzhangjie** [comment]
Thanks 👍 .
For now, I can use cmd `govulncheck ./... | sed '/------ informational ------/,$d'` to work around this.
---
And, one more suggeston: govulncheck has false positive reports. It may be improved. Before that, developers may want to ignore some false positive reports. For example, to add them into a file .govulncheck in current module.

**Comment by thediveo** [comment]
the vuln documentation says to share feedback here: https://go.dev/s/vuln-feedback ... I would expect this to also include potential false psoitives.

**Comment by zpavlinovic** [comment]
> And, one more suggeston: govulncheck has false positive reports. It may be improved. Before that, developers may want to ignore some false positive reports. For example, to add them into a file .govulncheck in current module.
> 
> Could we take this into consideration?

That would have to be a separate issue with a detailed proposal.

**Comment by zpavlinovic** [comment]
This is now available at master. We will tag the new version soon.
