### ISSUE TITLE
x/build: ppc64le LUCI machines missing for a couple weeks

### ISSUE THREAD

**Issue by mknyszek** [golang/go#64979]
The regular build dashboard seems OK (https://build.golang.org/) but the LUCI machines have been missing for about 2 weeks now (https://chromium-swarm.appspot.com/botlist?f=pool%3Aluci.golang.shared-workers&f=cipd_platform%3Alinux-ppc64le) leading to infra failures.

Can anyone from @golang/ppc64 please take a look? Thanks!

**Comment by pmur** [comment]
Thanks for the heads up. I'll figure it out.

**Comment by pmur** [comment]
Apparently there was a network issue with this VM on 12-23. It has been rebooted and seems to be working again.

Minor aside, docker got stuck trying to clean up the stale containers upon reboot. I had to stop docker and manually remove the stale CI containers.

**Comment by dmitshur** [comment]
Thanks for restoring them. Closing since this seems to be fixed.
