### ISSUE TITLE
proposal: import/path: Basic type interfaces

### ISSUE THREAD

**Issue by darkprof83** [golang/go#64986]
### Proposal Details

I propose to introduce interfaces for basic types. Then when declaring its type, e. g:
`type Email string` 
will give the possibility to create its own functions to check the possibility of converting, modifying. And it will be possible to implement, for example, a function that prohibits setting text other than user@gmail.com or forbid to convert a number to email.

**Comment by seankhliao** [comment]
I believe this is another instance of #29649 where the proposal tries to constrain types by value
