### ISSUE TITLE
mime/multipart: please support adding the standard mime header

### ISSUE THREAD

**Issue by gilbahat** [golang/go#65010]
### Go version

go version go1.21.5 darwin/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/Users/gilbahat/Library/Caches/go-build'
GOENV='/Users/gilbahat/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/gilbahat/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/gilbahat/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/Cellar/go/1.21.5/libexec'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/Cellar/go/1.21.5/libexec/pkg/tool/darwin_amd64'
GOVCS=''
GOVERSION='go1.21.5'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD='/Users/gilbahat/qubex/qubex-core/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/xm/_hmyr0c12tg9lvdm_h4z9tf80000gn/T/go-build3659326257=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

I tried to generate a multipart mime payload for AWS EC2 userdata.

### What did you see happen?

The multipart payload was rejected by cloud-init as it lacked a standard mime header:

MIME-Version: 1.0
Content-Type: multipart/mixed; boundary=<boundary>

### What did you expect to see?

I expected the mime/multipart writer to have a function that writes the standard mime header, e.g. writer.AddHeader . The format of the header is specified here, an example provided above: https://datatracker.ietf.org/doc/html/rfc2045#page-8

**Comment by seankhliao** [comment]
see https://pkg.go.dev/mime/multipart#Writer.FormDataContentType
