### ISSUE TITLE
runtime: remove concatstring{2,3,4,5}

### ISSUE THREAD

**Issue by lasiar** [golang/go#65020]
## Background
Functions `runtime.concatstring{2,3,4,5}` were added by commit: https://github.com/golang/go/commit/24699fb05c897dbaec3fe4f1d565c3c9da5078fc to avoid using C varargs (accordingly written in c).   
After these functions have been replaced to Golang code by commit https://github.com/golang/go/commit/61dca94e107170d2ff3beb13bb9fa5ce49d8d6fd, functions only calls `runtime.concatstrings()` and that is it.

## Proposal
Remove `runtime.concatstring{2,3,4,5}` and use only `runtime.concatstrings(*tmpBuf, []string) string`.

## API changes
Nope

## Benefits
1. The code is clearer.
2. Performance:

<details>
  <summary>Benchmark code</summary>

```go
package main

import "testing"

func concat2(a, b string) string {
	return a + b
}

func concat3(a, b, c string) string {
	return a + b + c
}

func concat4(a, b, c, d string) string {
	return a + b + c + d
}

func concat5(a, b, c, d, e string) string {
	return a + b + c + d + e
}

func concat6(a, b, c, d, e, f string) string {
	return a + b + c + d + e + f
}

var a = "foo"
var _b = "bar"
var c = "baz"
var d = "ipsum"
var e = "lorem"
var f = "dolor"

func BenchmarkConcat2(b *testing.B) {
	for i := 0; i < b.N; i++ {
		_ = concat2(a, _b)
	}
}

func BenchmarkConcat3(b *testing.B) {
	for i := 0; i < b.N; i++ {
		_ = concat3(a, _b, c)
	}
}

func BenchmarkConcat4(b *testing.B) {
	for i := 0; i < b.N; i++ {
		_ = concat4(a, _b, c, e)
	}
}

func BenchmarkConcat5(b *testing.B) {
	for i := 0; i < b.N; i++ {
		_ = concat5(a, _b, c, e, d)
	}
}

func BenchmarkConcat6(b *testing.B) {
	for i := 0; i < b.N; i++ {
		_ = concat6(a, _b, c, e, d, f)
	}
}

```
</details>

<details>
  <summary>Result of benchmark</summary>

```sh
name        old time/op  new time/op  delta
Concat2-10  11.3ns ± 1%  10.6ns ± 0%  -6.37%  (p=0.000 n=18+17)
Concat3-10  14.3ns ± 0%  13.6ns ± 3%  -5.26%  (p=0.000 n=18+20)
Concat4-10  18.3ns ± 5%  17.7ns ± 3%  -3.17%  (p=0.000 n=18+20)
Concat5-10  21.1ns ± 1%  20.6ns ± 0%  -2.26%  (p=0.000 n=18+18)
Concat6-10  23.2ns ± 2%  23.3ns ± 0%    ~     (p=0.084 n=18+19)

```

The Concat6 must show same result, because changes doesn't affect.

</details>

**Comment by randall77** [comment]
Taking out of proposal process, no API changes.

**Comment by CAFxX** [comment]
See https://github.com/golang/go/issues/27801 though
