### ISSUE TITLE
main: chained appends change contents of previous variable

### ISSUE THREAD

**Issue by daHaimi** [golang/go#65034]
### Go version

go version 1.19.1, 1.20, 1.21 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GOCACHE="/home/dahaimi/.cache/go-build"
GOENV="/home/dahaimi/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/dahaimi/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/dahaimi/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.19"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.19/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1433866872=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

I reproduced the issue on https://go.dev/play/p/gRUHj2w1DmJ:

- Create a slice of an initial collection and stored it to variable `a` -> `a` has expected value
- Create a slice `b` using `append` to add an item to `a` -> `b` has expected value
- Create a slice `c` using `append` to add an item to `b` -> `c` has expected value
- Create a slice `d` using `append` to add **an other** item to `b`
  - -> `d` has expected value
  - -> **`c` has the value of `d`**

I tried also with global `var`s and `:=` variable declarations. The result always was the same, so I suggest this is a problem in the behaviour of `append`.

### What did you see happen?

In my example, I added the output of the pointers, which are correct.

So the last call to `append` is changing the contents of `c`, although only `d` is being touched. 

### What did you expect to see?

I expect to see the value of `c` remain untouched when creating `d` by appending an item to `b`, as `c` is not interacting in any way.

**Comment by robpike** [comment]
It's working as expected. Both c and share the same underlying array, so when you declare d by modifying b, you also modify c.

**Comment by daHaimi** [comment]
Okay, I did deeper investigations and what to expect. But although it is not intuitive, it is technically correct behaviour.
The weird thing is, that different pointers to the same slice have the same (`c` and `d`) or different (`b` and `c`/`d`) contents; `b`, `c` and `d` are different pointers, but `c` and `d` point literally to the same content while `b` does not.
