### ISSUE TITLE
x/build/devapp/owners: stale entries at https://dev.golang.org/owners

### ISSUE THREAD

**Issue by mauri870** [golang/go#65049]
I'm not sure if the deployments for the owners page is automated in any way, or deployed periodically, but the data seems to be stale for almost a month.

Last two commits that change the owners file ([5535e355572c2bef34fe373bdf2ab4bc247cd433](https://go.googlesource.com/build/+/5535e355572c2bef34fe373bdf2ab4bc247cd433),  [bad0ec21171944e5e9fc9f5f1cdb927175f99fa5](https://github.com/golang/build/commit/bad0ec21171944e5e9fc9f5f1cdb927175f99fa5)) were not deployed live.

cc @golang/release

**Comment by dmitshur** [comment]
It is indeed manual and needs to be done when there are changes occasionally. Thanks for the ping. Its latest version is now deployed.
