### ISSUE TITLE
Binary package missing "debug_info".

### ISSUE THREAD

**Issue by tttoad** [golang/go#65063]
### Go version

go version go1.21.5 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/toad/Library/Caches/go-build'
GOENV='/Users/toad/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/toad/work/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/toad/work'
GOPRIVATE=''
GOPROXY='https://goproxy.cn,direct'
GOROOT='/Users/toad/go/go1.21.5'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/Users/toad/go/go1.21.5/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.21.5'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/toad/work/***/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/g1/tgmnlrdn3vxgv08kdgh9vpkw0000gn/T/go-build768557887=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

<img width="1575" alt="image" src="https://github.com/golang/go/assets/14021602/33a88de6-cde2-4c82-b0c1-9826137e3843">

go build -o ./main -gcflags all="-N -l" ./cmd/servicemap/main.go 

### What did you see happen?

I need to use dlv for debugging, but I noticed that the built binary is missing "__zdebug_info".

### What did you expect to see?

The binary package should have "__zdebug_info".
I'm not clear on how to troubleshoot this. Only this project is missing, maybe because of the cache ?
I upgraded the SDK. from 1.20.7 to 1.21.5.

**Comment by tttoad** [comment]
I tried using go clean -cache.
The build product is still missing `__zdebug_info`.

**Comment by bcmills** [comment]
Is this a duplicate of #65014?

**Comment by tttoad** [comment]
Yes, it's the same problem.
I don't use `CGO` in my project, it works when I use `CGO_ENABLED=0`.
This seems to be something that only happens on darwin, when I build within linux is works.
