### ISSUE TITLE
go/version: unclear as to what counts as a valid Go version

### ISSUE THREAD

**Issue by MadhavJivrajani** [golang/go#65061]
### Go version

go version devel go1.22-e9b3ff15 Wed Jan 10 17:35:49 2024 +0000 darwin/amd64

### Output of `go env` in your module/workspace:

```shell
❯ gotip env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/Users/mjivrajani/Library/Caches/go-build'
GOENV='/Users/mjivrajani/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/mjivrajani/gocode/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/mjivrajani/gocode'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/Users/mjivrajani/sdk/gotip'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/Users/mjivrajani/sdk/gotip/pkg/tool/darwin_amd64'
GOVCS=''
GOVERSION='devel go1.22-e9b3ff15 Wed Jan 10 17:35:49 2024 +0000'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/mjivrajani/gocode/src/github.com/MadhavJivrajani/go/src/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/r7/f6kyp7vs0sv90105pjh1t8340000gp/T/go-build3111256134=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

I was playing around with the new `go/version` package to see how it works. 

I'm probably missing something, but I'm not entirely sure what a "valid" Go version entails - from the documentation of `Compare`:
> Invalid versions, including the empty string, compare less than valid versions

However, it also says:
> Custom toolchain suffixes are ignored during comparison: "go1.21.0" and "go1.21.0-bigcorp" are equal.

### What did you see happen?

My assumption going into this was that a "valid" version is one that returns a `true` when passed into `IsValid`. However, `IsValid` seems to reject custom toolchain names and names with `+auto` attached, see here: https://go.dev/play/p/OnEbA0bOovs?v=gotip

### What did you expect to see?

Maybe clarifying the docs would help better understand what a valid Go version is for folks other than me who might also make similar assumptions and I'm happy to send in a fix here! And thank you for introducing this package, we are already in the works of getting rid of custom parsing code in the Kubernetes codebase! ❤️

**Comment by mauri870** [comment]
Looks like the description of Compare is not really correct, I don't think we are ignoring the suffixes, if it finds a suffix we just return an empty version:

https://go.googlesource.com/go/+/e9b3ff15f40d6b258217b3467c662f816b078477/src/internal/gover/gover.go#137

**Comment by mauri870** [comment]
We might be able to fix this by returning the proper version if it is a custom toolchain, eg "go1.21.3-corp" returns "1.21.3" instead of an empty version. That would fix Compare but will also affect all other usages of internal/gover.Parse, so I'm not sure if it would break anything.

```diff
diff --git a/src/internal/gover/gover.go b/src/internal/gover/gover.go
index 2ad068464d..151ff674fa 100644
--- a/src/internal/gover/gover.go
+++ b/src/internal/gover/gover.go
@@ -133,7 +133,7 @@ func Parse(x string) Version {
 	// Parse patch if present.
 	if x[0] == '.' {
 		v.Patch, x, ok = cutInt(x[1:])
-		if !ok || x != "" {
+		if !ok || x != "" && x[0] != '-' {
 			// Note that we are disallowing prereleases (alpha, beta, rc) for patch releases here (x != "").
 			// Allowing them would be a bit confusing because we already have:
 			//	1.21 < 1.21rc1
```

**Comment by rsc** [comment]
The mention of toolchains in that comment is just a bug. Custom toolchains are not allowed in this API.
This API is for things like deciding that go1.3 < go1.21.5.

What is the context where you need "go1.21.0-bigcorp" to work?

**Comment by rittneje** [comment]
@rsc Why is it a bug? It was a feature we explicitly discussed in the proposal. https://github.com/golang/go/issues/62039#issuecomment-1726486081

**Comment by rsc** [comment]
@rittneje Thanks for pointing that out. My memory is clearly faulty!

**Comment by rsc** [comment]
Reopen for backport.

**Comment by timothy-king** [comment]
Reopening for x/tools

**Comment by dmitshur** [comment]
This was done for x/tools in [CL 562838](https://go.dev/cl/562838).

This issue is in Go1.22 milestone, so closing again. (It was fixed by [CL 559796](https://go.dev/cl/559796).)
