### ISSUE TITLE
proposal: bytes: implement io.Seeker, io.ReaderAt, io.WriterAt for Buffer

### ISSUE THREAD

**Issue by godcong** [golang/go#65076]
### Proposal Details

I found that `Buffer` doesn't support read/write to a specific location when using `bytes.Buffer`.
This makes it inconvenient when I need to write a []byte in a specified location.
To make it easier to use, I'd like to help implement these basic functions.

```
type Seeker interface {
	Seek(offset int64, whence int) (int64, error)
}
type WriterAt interface {
	WriteAt(p []byte, off int64) (n int, err error)
}
type ReaderAt interface {
	ReadAt(p []byte, off int64) (n int, err error)
}
```

**Comment by mvdan** [comment]
Did you research previous threads like https://github.com/golang/go/issues/21899?
