### ISSUE TITLE
x/tools/gopls: use more specific quick fix description for undefined name

### ISSUE THREAD

**Issue by hyangah** [golang/go#65087]
When the function is not defined, gopls provides a quickfix with the description "undefined"
![Screenshot 2024-01-12 at 5 58 03 PM](https://github.com/golang/go/assets/4999471/872be4e4-56d9-4bf3-9bd2-6ef7191826b3)

It's unclear what it does. Use more specific description e.g. "add missing function" like TS language server
![Screenshot 2024-01-12 at 6 04 14 PM](https://github.com/golang/go/assets/4999471/a928353d-c5e2-4a38-b3e6-896062ff169b)

**Comment by hyangah** [comment]
And, it looks like the quickfix doesn't seem to infer the function signature correctly yet.

**Comment by raghvenders** [comment]
@hyangah -It looks like actionable message. I am making changes for this. Kindly assign this to me. 
Even for undeclared name too, we can change into an actionable message "Add missing declaration ..."

By the way, as this message got changed go-staticcheck uses the same string undefined and those bring out warning. Kindly suggest.

**Comment by adonovan** [comment]
Looking at the logic in gopls that creates this patch--in the `undeclared` analyzer--it seems that it already gives a reasonable name to the fix, but this must be getting lost somewhere along the plumbing between the analyzer and the LSP:

**https://cs.opensource.google/go/x/tools/+/refs/tags/gopls/v0.15.0-pre.1:gopls/internal/analysis/undeclaredname/undeclared.go;l=146-156**
```go
	return fset, &analysis.SuggestedFix{
		Message: fmt.Sprintf("Create function \"%s\"", ident.Name),
		TextEdits: []analysis.TextEdit{{
			Pos:     pos,
			End:     pos,
			NewText: b.Bytes(),
		}},
	}, nil
```

**Comment by raghvenders** [comment]
@alandonovan , Thanks. The place you are referring comes in while apply Fix, correct me if I can understand this better.

I tried applying the fix locally and it goes in runForError() and change error message for functions undeclared

@hyangah  Is this expected ?

```
pass.Report(analysis.Diagnostic{
		Pos:     err.Pos,
		End:     end,
		Message: err.Msg,
	})
```

![Screenshot 2024-01-16 160316](https://github.com/golang/go/assets/9973300/52f66eba-fb02-41b4-8b4f-1df86080f4ef)
![Screenshot 2024-01-16 160303](https://github.com/golang/go/assets/9973300/8ab85e3e-4d96-44a2-8807-2d1c2d7d5906)

**Comment by hyangah** [comment]
Thanks @raghvenders  
`Create function "%s"` as proposed by the analyzer seems more concise.
