### ISSUE TITLE
x/playground: fails to loop for 1e20

### ISSUE THREAD

**Issue by Nasfame** [golang/go#65082]
### Go version

gotip, go1.21, go1.20

### Output of `go env` in your module/workspace:

```shell
https://go.dev/play/?v=gotip
```

### What did you do?

https://go.dev/play/p/CHblz9L4Lq6?v=gotip

### What did you see happen?

```
no Of workers 100000000000000000000
All workers have completed.

Program exited.
```

### What did you expect to see?

```
no Of workers 100000000000000000000
entered loop
Worker 241556 starting
Worker 879206 starting
Worker 878827 starting
Worker 878548 starting
Worker 247627 starting
Worker 879067 starting
Worker 879207 starting
Worker 875930 starting
Worker 879051 starting
Worker 878550 starting
Worker 82724 starting
Worker 878551 starting
Worker 878423 starting
Worker 879211 starting
Worker 878424 starting
Worker 879068 starting
Worker 878555 starting
Worker 878426 starting
Worker 82833 starting
Worker 241283 starting
Worker 879212 starting
.....
```

### Additional Details

works for **1e18** & at times for **1e19**

**Comment by Nasfame** [comment]
Related to #64894

**Comment by zephyrtronium** [comment]
The maximum value of int is less than 1e20. The conversion from float64 to int therefore is implementation-specific. In the playground's case, it ends up with -9223372036854775808, so the loop body never runs. There is nothing surprising here.
