### ISSUE TITLE
x/term: operation not supported by device

### ISSUE THREAD

**Issue by kcmvp** [golang/go#65095]
### Go version

go version go1.21.4 darwin/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/Users/kcmvp/Library/Caches/go-build'
GOENV='/Users/kcmvp/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/kcmvp/go/1.21.4/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/kcmvp/go/1.21.4'
GOPRIVATE=''
GOPROXY='https://goproxy.cn'
GOROOT='/Users/kcmvp/.goenv/versions/1.21.4'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/Users/kcmvp/.goenv/versions/1.21.4/pkg/tool/darwin_amd64'
GOVCS=''
GOVERSION='go1.21.4'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/kcmvp/sandbox/gob/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/0r/y528m9x502d8w4mhps1t6qsr0000gn/T/go-build1470760717=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

run the sample code as from https://pkg.go.dev/golang.org/x/term#section-readme

`oldState, err := term.MakeRaw(int(os.Stdin.Fd()))
if err != nil {
        panic(err)
}
defer term.Restore(int(os.Stdin.Fd()), oldState)`

### What did you see happen?

The code failed with error message 
`operation not supported by device`

### What did you expect to see?

I suppose there should be no error when executing this code. at the same time the error message is so geneirc dont give any information why run into this error

**Comment by creack** [comment]
This error comes from the ioctl syscall when trying to change the setting of the tty device. Are you sure your device supports such operation?

**Comment by kcmvp** [comment]
> This error comes from the ioctl syscall when trying to change the setting of the tty device. Are you sure your device supports such operation?
> To check if a device supports the TTY (teletypewriter) device, you can use the `test` command in a shell script. Here's an example using bash:

```bash
if [[ -t 0 && -t 1 ]]; then
  echo "The device supports TTY."
else
  echo "The device does not support TTY."
fi
```

This script checks if file descriptors 0 (stdin) and 1 (stdout) are associated with a terminal device. If both file descriptors are associated with a terminal, it means the device supports TTY.

You can run this script in your terminal to check if your device supports TTY.

here is the output of above script

<img width="357" alt="image" src="https://github.com/golang/go/assets/7655276/162ccb08-70fb-493d-91ad-55b0c8bcc131">

**Comment by adonovan** [comment]
What is the standard input file of your process? On macOS, usually it is the Terminal application, in which case this program silently succeeds:

```go
$ cat a.go
package main

import (
	"os"
	"golang.org/x/term"
)

func main() {
	oldState, err := term.MakeRaw(int(os.Stdin.Fd()))
	if err != nil {
		panic(err)
	}
	defer term.Restore(int(os.Stdin.Fd()), oldState)
}

$ go run a.go 
```

But If you close stdin:
```
$ go run a.go <&-
fork/exec a: bad file descriptor
```
or read from a regular file:
```
$ go run a.go < a.go 
panic: inappropriate ioctl for device

goroutine 1 [running]:
main.main()
	/Users/adonovan/w/xtools/a.go:14 +0xf4
exit status 2
```
then you can't use terminal ioctls on stdin.
