### ISSUE TITLE
x/pkgsite: package removal request for github.com/Pinggy-io/pinggy-go/pinggy

### ISSUE THREAD

**Issue by abhimp** [golang/go#65100]
Hi,

We mistakenly published `github.com/Pinggy-io/pinggy-go/pinggy` when we wanted to publish `github.com/Pinggy-io/pinggy-go`. `go get` is picking up the older version `github.com/Pinggy-io/pinggy-go/pinggy` when the latest version is available at `github.com/Pinggy-io/pinggy-go`.

Kindly retract all the versions of the `github.com/Pinggy-io/pinggy-go/pinggy` package.

**Comment by seankhliao** [comment]
you have to use `retract` directives for this, we cannot do that for you. a request here will only hide documentation on pkg.go.dev, it doesn't affect the `go` command.
