### ISSUE TITLE
runtime: windows syscall does not use XMM registers to pass float args

### ISSUE THREAD

**Issue by bryanturley** [golang/go#6510]
<pre>Currently in sys_windows_amd64.s line 41-ish

loadregs:
  // Load first 4 args into correspondent registers.                                                                                          
  MOVQ  0(SI), CX
  MOVQ  8(SI), DX
  MOVQ  16(SI), R8
  MOVQ  24(SI), R9

But if an arg is a float32/float64 it should be loaded into an xmm register instead

<a href="http://msdn.microsoft.com/en-us/library/ms235286.aspx">http://msdn.microsoft.com/en-us/library/ms235286.aspx</a>

In the &quot;Calling Convention&quot; section.
&quot;
The arguments are passed in registers RCX, RDX, R8, and R9. If the arguments are
float/double, they are passed in XMM0L, XMM1L, XMM2L, and XMM3L.
&quot;

Perhaps the easy thing is to just load them into both sets of 4?
Then you wouldn't have to type check going out...

Figured I shouldn't try submitting a patch for something so low level without any
previous submissions.

I am no windows pro, so I may just be confused here.

I discovered this trying to call glClearColor (which takes only 4 floats) with
syscall.Syscall6.  I got random colors every run, which was fairly interesting.
Used a fake opengl32.dll (from GLIntercept) and a Printf right before Syscall6 to
discover my values were not being pushed all the way through unless they were integers.

I didn't look into 32bit windows and float args. It may have similar problem.
Hopefully this makes sense my brain hurts. I hate windows.</pre>

**Comment by crawshaw** [comment]
It turns out the calling convention description in Comment 22 by @rsc is not the case. If the second argument is a float32, its value goes into the second XMM register regardless of whether the first argument is an int or a float.

The documentation in https://msdn.microsoft.com/en-us/library/zthk2dkh.aspx has an example:

```
func3(int a, double b, int c, float d);  
// a in RCX, b in XMM1, c in R8, d in XMM3
```

This means its extremely easy to support functions with float parameters in syscall.Syscall. I would like to do this in Go 1.7, so I can remove the fixFloat hack from the GL package I introduced in golang.org/cl/17675.

**Comment by alexbrainman** [comment]
The  https://msdn.microsoft.com/en-us/library/zthk2dkh.aspx is about amd64 parameter passing. What happens with 386?

Alex

**Comment by minux** [comment]
386 always passes argument on stack, so I think it already works correctly
(to pass a double, you have to manually convert it to two uintptrs in the
correct order, but that's doable.)

To fix floating point argument passing on amd64, we just need to copy each
uintptr to corresponding XMM register.

The real problem, however, is handling floating returns. syscall.Syscall has
no way to know whether the result should be in %rax or %xmm0.

**Comment by alexbrainman** [comment]
> 386 always passes argument on stack

Do you have reference for that? I am specifically asking about float args.

Alex

**Comment by minux** [comment]
On Tue, Dec 15, 2015 at 7:35 PM, Alex Brainman <notifications@github.com>
wrote:

> 386 always passes argument on stack
>
> Do you have reference for that? I am specifically asking about float args.
>
No, the MS docs on this matter is very vague:
https://msdn.microsoft.com/en-us/library/984x0h58.aspx
You probably have to find that out with experiments.

But there really is no reason to pass FP arguments in 387 stack whereas all
the integer arguments are passed on stack. (cdecl and stdcall)

**Comment by egonelbre** [comment]
Agner Fog has a pretty extensive overview of calling conventions: http://www.agner.org/optimize/calling_conventions.pdf

> Float and double types are transferred in XMM registers in 64 bit mode, otherwise on the stack.
