### ISSUE TITLE
proxy.golang.org: failed to verify certificate

### ISSUE THREAD

**Issue by ankahla** [golang/go#65118]
When trying to build caddy image (caddy:2.7) the following command failed with error : 

`go: github.com/caddyserver/caddy/v2@v2.7.6: Get "https://proxy.golang.org/github.com/caddyserver/caddy/v2/@v/v2.7.6.info": tls: failed to verify certificate: x509: certificate signed by unknown authority`

The command:
```
RUN xcaddy build \
	--with github.com/dunglas/mercure \
	--with github.com/dunglas/mercure/caddy \
	--with github.com/dunglas/vulcain \
	--with github.com/dunglas/vulcain/caddy
```

**Comment by seankhliao** [comment]
sounds like a problem with your environment.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
