### ISSUE TITLE
x/pkgsite: package removal request for github.com/HixRaid/dummy-image

### ISSUE THREAD

**Issue by HixRaid** [golang/go#65111]
### What is the path of the package that you would like to have removed?

github.com/HixRaid/dummy-image

### Are you the owner of this package?

Yes, I am the owner of the package.

### What is the reason that you could not retract this package instead?

Renamed project
github.com/HixRaid/dummy-image -> github.com/HixRaid/dummy-image-generator

**Comment by seankhliao** [comment]
retract directives work across repo renames, please use those.
