### ISSUE TITLE
runtime: panic in mapaccess2_faststr (suspected data race)

### ISSUE THREAD

**Issue by mikimartin88** [golang/go#65115]
### Go version

1.20

### Output of `go env` in your module/workspace:
`{
      "AR": "ar",
      "CC": "gcc",
      "CGO_CFLAGS": "-O2 -g",
      "CGO_CPPFLAGS": "",
      "CGO_CXXFLAGS": "-O2 -g",
      "CGO_ENABLED": "0",
      "CGO_FFLAGS": "-O2 -g",
      "CGO_LDFLAGS": "-O2 -g",
      "CXX": "g++",
      "GCCGO": "gccgo",
      "GO111MODULE": "",
      "GOAMD64": "v1",
      "GOARCH": "amd64",
      "GOBIN": "",
      "GOCACHE": "/root/.cache/go-build",
      "GOENV": "/root/.config/go/env",
      "GOEXE": "",
      "GOEXPERIMENT": "",
      "GOFLAGS": "",
      "GOGCCFLAGS": "-fPIC -m64 -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build353150670=/tmp/go-build -gno-record-gcc-switches",
      "GOHOSTARCH": "amd64",
      "GOHOSTOS": "linux",
      "GOINSECURE": "",
      "GOMOD": "/go/src/bf/booking/go.mod",
      "GOMODCACHE": "/go/pkg/mod",
      "GONOPROXY": "gitlab.xmltravelgate.com",
      "GONOSUMDB": "gitlab.xmltravelgate.com",
      "GOOS": "linux",
      "GOPATH": "/go",
      "GOPRIVATE": "gitlab.xmltravelgate.com",
      "GOPROXY": "https://proxy.golang.org,direct",
      "GOROOT": "/usr/local/go",
      "GOSUMDB": "sum.golang.org",
      "GOTMPDIR": "",
      "GOTOOLDIR": "/usr/local/go/pkg/tool/linux_amd64",
      "GOVCS": "",
      "GOVERSION": "go1.20.13",
      "GOWORK": "",
      "PKG_CONFIG": "pkg-config"
}`

### What did you do?

Hi :smile:!

I have tried to read a value from nil map

`var orgsToSendToPrometheus map[string]struct{}

func MustRegisterOverheadByOrg(org string) bool {
	if _, ok := orgsToSendToPrometheus[allOrgs]; ok {
		return true
	}
	_, ok := orgsToSendToPrometheus[org]
	return ok
}`

### What did you see happen?

I’m receiving a runtime error: invalid memory address or nil pointer dereference accessing to a nil map:

That panics in line → _, ok := orgsToSendToPrometheus[org]

As I understand, read , delete, length, and range loops, are safe to perform on a nil map since it behaves like an empty map.

All code:
![image](https://github.com/golang/go/assets/18575481/473982ce-0ddb-4ff0-a16b-48bdc84037db)

Error trace:

```gitlab.xmltravelgate.com/hub-aggregator/kit/log.(*Logger).Error
/go/pkg/mod/gitlab.xmltravelgate.com/hub-aggregator/kit@v1.46.22/log/logger.go:68
gitlab.xmltravelgate.com/hub-aggregator/booking/common/kit/audit.Middleware.func1.1.1
/go/src/bf/booking/common/kit/audit/audit.go:119
runtime.gopanic
/usr/local/go/src/runtime/panic.go:884
runtime.panicmem
/usr/local/go/src/runtime/panic.go:260
runtime.sigpanic
/usr/local/go/src/runtime/signal_unix.go:841
memeqbody
/usr/local/go/src/internal/bytealg/equal_amd64.s:151
runtime.mapaccess2_faststr
/usr/local/go/src/runtime/map_faststr.go:133
gitlab.xmltravelgate.com/hub-aggregator/booking/common/connectx/hardCode.MustRegisterOverheadByOrg
/go/src/bf/booking/common/connectx/hardCode/operation_sla.go:30
gitlab.xmltravelgate.com/hub-aggregator/booking/pkg/flow/bfhttp.RegisterSLAStats
/go/src/bf/booking/pkg/flow/bfhttp/metric.go:178
gitlab.xmltravelgate.com/hub-aggregator/kit/http.(*Handler).ServeHTTP
/go/pkg/mod/gitlab.xmltravelgate.com/hub-aggregator/kit@v1.46.22/http/handler.go:90
gitlab.xmltravelgate.com/hub-aggregator/booking/common/connectx.TransactionMiddleware.func1.1
/go/src/bf/booking/common/connectx/transaction.go:124
net/http.HandlerFunc.ServeHTTP
/usr/local/go/src/net/http/server.go:2122
github.com/travelgateX/go-jwt-tools.Middleware.func1.1
/go/pkg/mod/github.com/travelgate!x/go-jwt-tools@v1.5.0/auth.go:42
net/http.HandlerFunc.ServeHTTP
/usr/local/go/src/net/http/server.go:2122
gitlab.xmltravelgate.com/hub-aggregator/tgx-kit/header.Middleware.func1.1
/go/pkg/mod/gitlab.xmltravelgate.com/hub-aggregator/tgx-kit@v1.77.68/header/header.go:235
net/http.HandlerFunc.ServeHTTP
/usr/local/go/src/net/http/server.go:2122```

### What did you expect to see?

No nil pointer reading over a map

**Comment by seankhliao** [comment]
please include a runnable reproducer of the issue

**Comment by rittneje** [comment]
I don't think this is because the map is nil. Based on the stack trace, it seems more like your strings are corrupted. Is your application using cgo, `reflect.StringHeader`, or `unsafe.String`?

**Comment by mikimartin88** [comment]
No, we are not using cgo, reflect.StringHeader neither unsafe.String. How can I know if the strings are corrupted? Is it possible that race conditions could produce that the strings are corrupted?

**Comment by rittneje** [comment]
Have you tried running the race detector on your code?

**Comment by adonovan** [comment]
That map variable is global, and is accessed by global functions, but there is no mutex. Global functions are generally expected to be concurrency safe, so I suspect they were called from two goroutines, causing the the map data structure to become corrupted.

Try running your tests with go test -race.

**Comment by mikimartin88** [comment]
Thank you all, I will try it 👍
