### ISSUE TITLE
x/net/ipv4: ip header is ignored by payloadHandler.ReadFrom 

### ISSUE THREAD

**Issue by amtoor** [golang/go#65126]
### Go version

go version go1.20.7 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/xxx/go"
GOPRIVATE=""
GOROOT="/home/xxx/.bin/go/1.20.7"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOVCS=""
GOVERSION="go1.20.7"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build172644931=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

I want to read tos from response, but I saw payloadHandler.ReadFrom only return icmp packet, there is not ip header.

### What did you see happen?

can not read tos from icmp response.

here read header but not return it.
![image](https://github.com/golang/go/assets/4986063/33f4d092-79d0-44f8-beff-8e3630fb0b22)

### What did you expect to see?

I want to read tos of icmp response.

**Comment by cagedmantis** [comment]
Please provide a snippet of code that reproduces your issue and a description of the problem.
