### ISSUE TITLE
spec: range over integer expressions underspecified

### ISSUE THREAD

**Issue by griesemer** [golang/go#65137]
The following code
```Go
var u uint8
for u = range 258 {
   println(u)
}
```
prints the values 0, 1, 2, ... 255, 0, 1; that is the integer "wraps around". This seems incorrect, but the spec is silent on the subject.

I believe the rules need to be extended such that if:
a) the iteration variable is already declared (`u` in the example above):
- the iteration expressions must be assignable to the iteration variable (if the expression is a constant, it must fit into the iteration variable)

b) the iteration variable is being declared (as in `for u := range x`):
- if the iteration expression is typed, the iteration variable has the same type
- if the iteration expression is an untyped constant, it is given the type `int`, the constant must be representable as an `int`, and the iteration variable will be of type `int`

I believe these rules follow more or less from the existing prose (assignment to the iteration variables happens as in an assignment statement), but the fact that the compiler and type checkers get this wrong is an indication that we need more precise prose or better examples.

We need to pin this down before the 1.22 release otherwise we may not be able to make these changes anymore in a backward-compatible way.

cc: @rsc

**Comment by atdiar** [comment]
Related : https://github.com/golang/go/issues/61405#issuecomment-1875344886

If it is not problematic and not too late, I would remove the assignment form altogether.
The iteration variable is not really needed and may even be confusing for people.

**Comment by cherrymui** [comment]
> the iteration expressions must be assignable to the iteration variable (if the expression is a constant, it must fit into the iteration variable)

This would mean
```
var u uint8
for u = range 256 {
   println(u)
}
```
would not be allowed, as 256 is not assignable to uint8, although the actual values being assigned, 0, 1, ...., 255, are assignable? (Personally I think that is fine, if that is more consistent with other rules. Just a weird corner case.)

**Comment by gazerro** [comment]
> f the iteration expression is typed, the iteration variable has the same type

**Comment by griesemer** [comment]
@cherrymui Correct. I agree it's odd. But it would match the behavior of
```Go
var u uint8
for u := 0; u < 256; u++ {}
```
which is currently also not permitted.

**Comment by zephyrtronium** [comment]
The workaround is straightforward:

```go
var u uint8
for i := range n {
    u = uint8(i)
    println(u)
}
```

**Comment by atdiar** [comment]
Better yet
```go
var u uint8
for range n{
        print(u) 
        u++
} 

```
Now if n is 256, there is still no issue.

**Comment by griesemer** [comment]
@gazerro Note that [your example](https://github.com/golang/go/issues/65137#issuecomment-1896568270) never worked if `n` is a variable.

As @cherrymui has pointed out, these are really esoteric corner cases. Most of the time there's simply no issue here. If it turns out that we're too restrictive for practical purposes, we can relax the rules in the future, based on experience gained. But if we don't lock down things now, we won't be able to make changes later, once enough code is using behavior that we might consider incorrect.

**Comment by gazerro** [comment]
@griesemer my example works if `n` is a variable (https://go.dev/play/p/kUks7Y5sA2E?v=gotip). Is there perhaps something I'm not understanding?

**Comment by timothy-king** [comment]
@gazerro The direct translation of https://github.com/golang/go/issues/65137#issuecomment-1896460243 would be (https://go.dev/play/p/O4ZaNJeuJUG?v=gotip):
```
var n uint8 = 256
var u uint8
for u = range n {
	println(u)
}
```
This fails to compile with:
> ./prog.go:6:16: cannot use 256 (untyped int constant) as uint8 value in variable declaration (overflows)

**Comment by atdiar** [comment]
Another question is, even if we keep the assignment form, why is it even possible for the type of the assignment variable to be `uint8`?
If I range over a slice of uint8, the index is still of type  `int`?

**Comment by rsc** [comment]
New semantics SGTM.

**Comment by mdempsky** [comment]
New semantics SGTM too.

> prints the values 0, 1, 2, ... 255, 0, 1

Oof. I suspect this is another consequence of our fuzzy IR. Ideally the compiler should have ICE'd instead.

**Comment by griesemer** [comment]
@gopherbot please consider this for backport to 1.22. It's missing documentation for 1.22.
