### ISSUE TITLE
x/website: wiki doesn't shrink images to fit on the screen

### ISSUE THREAD

**Issue by prattmic** [golang/go#65139]
https://go.dev/wiki/LUCI contains a high-resolution screenshot, which on my screen overflows off the right side of the screen, like below:

![image](https://github.com/golang/go/assets/1293187/050af92c-e899-4689-98db-58e2ebd88af1)

IMO, this should be automatically shrunk to fit in the same width as the text.

cc @rsc

**Comment by cagedmantis** [comment]
cc [@golang/tools-team](https://github.com/orgs/golang/teams/tools-team)

**Comment by hyangah** [comment]
In https://go-review.git.corp.google.com/c/website/+/556416, proposing 

`max-width: 100%`
