### ISSUE TITLE
x/website: go.dev/wiki page has wrong link to InstallTroubleShooting page

### ISSUE THREAD

**Issue by ALTree** [golang/go#65134]
The https://go.dev/wiki/ page has a line that says

> Having installation problems? [InstallTroubleShooting](https://go.dev/wiki/InstallTroubleShooting)

The InstallTroubleShooting link 404s, the correct link should be https://go.dev/wiki/InstallTroubleshooting (lowercase "s")

**Comment by ALTree** [comment]
This line:

> [Managing your dependencies](https://go.dev/wiki/PackageManagementTools) - An overview of the tools you can use to manage

also has a dead link.

**Comment by yansal** [comment]
These links and others are fixed in this CL which is waiting for review

https://go-review.googlesource.com/c/wiki/+/550195

**Comment by hyangah** [comment]
Thanks @yansal The change was merged.
