### ISSUE TITLE
os: (*File).ReadAt() would probably fail if file is opened with O_DIRECT flag

### ISSUE THREAD

**Issue by hzzb** [golang/go#65135]
### Go version

go version go1.21.6 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/root/.cache/go-build'
GOENV='/root/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/root/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/root/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.6'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='0'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2417799151=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

```golang
package main

import (
	"fmt"
	"os"
	"syscall"
)

func main() {
	filePath := "main.go"
	flags := os.O_RDONLY | syscall.O_DIRECT
	fil, err := os.OpenFile(filePath, flags, 0644)
	if err != nil {
		fmt.Printf("failed to open file: %s\n", err)
		return
	}

	buf := make([]byte, 10)
	_, err = fil.ReadAt(buf, 0)
	if err != nil {
		fmt.Printf("failed to read file: %s\n", err)
		return
	}
	fmt.Printf("succeed to read file\n")
}

```

### What did you see happen?

root@host:/opt# go run main.go 
failed to read file: read main.go: invalid argument

### What did you expect to see?

succeed to read file that is opened using the O_DIRECT flag.

From the [man page](https://man7.org/linux/man-pages/man2/open.2.html#:~:text=O_DIRECT%0A%20%20%20%20%20%20%20The%20O_DIRECT,buffered%20I/O.), it seems required to pass perfect arguments to ReadAt() so that buffer address, length, offset are all aligned.

As go is a easy-to-use language, is it worthy to handle alignment requirements inside the standard pkg, providing a more user-friend api.

**Comment by seankhliao** [comment]
ify you're using OpenFile then it's on you to set the right flags.

**Comment by hzzb** [comment]
It's by intention to open file with the O_DIRCT flag because we want to bypass kernel page cache for performance consideration.  The flags we set is right. It's possible to let user application provide strictly aligned arguments when calling ReadAt(). but that's a bit of trivial. We succeed to read file when pass strict-aligned args.
