### ISSUE TITLE
I Can't import module's function due to the file's name.

### ISSUE THREAD

**Issue by SKYWALKER-STAR** [golang/go#65146]
### Go version

go version go1.20.6 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/usr/local/go/bin"
GOCACHE="/home/ming/.cache/go-build"
GOENV="/home/ming/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
```

### What did you do?

I define a function of one module in seperate files,like this. 
![1](https://github.com/golang/go/assets/60430891/5b536495-ca1a-45e0-b066-92037c091d46)
But when the two file's name are alike(metrics_general.go metrics_test.go),I cant't use function in one of then(metrics_test.go) 
![3](https://github.com/golang/go/assets/60430891/ce711f3e-97d7-43c8-811d-43a473454a27)
When I change metrics_test.go's name,this problem disappeared.
![image](https://github.com/golang/go/assets/60430891/1f9b8548-2762-4a88-a004-e0fd7f9d4464)

### What did you see happen?

I define a function of one module in seperate files,like this. 
![1](https://github.com/golang/go/assets/60430891/5b536495-ca1a-45e0-b066-92037c091d46)
But when the two file's name are alike(metrics_general.go metrics_test.go),I cant't use function in one of then(metrics_test.go) 
![3](https://github.com/golang/go/assets/60430891/ce711f3e-97d7-43c8-811d-43a473454a27)
When I change metrics_test.go's name,this problem disappeared.
![image](https://github.com/golang/go/assets/60430891/1f9b8548-2762-4a88-a004-e0fd7f9d4464)

### What did you expect to see?

I define a function of one module in seperate files,like this. 
![1](https://github.com/golang/go/assets/60430891/5b536495-ca1a-45e0-b066-92037c091d46)
But when the two file's name are alike(metrics_general.go metrics_test.go),I cant't use function in one of then(metrics_test.go) 
![3](https://github.com/golang/go/assets/60430891/ce711f3e-97d7-43c8-811d-43a473454a27)
When I change metrics_test.go's name,this problem disappeared.
![image](https://github.com/golang/go/assets/60430891/1f9b8548-2762-4a88-a004-e0fd7f9d4464)

**Comment by rittneje** [comment]
Files ending in _test.go are unit test files and are ignored during regular builds.

**Comment by SKYWALKER-STAR** [comment]
> Files ending in _test.go are unit test files and are ignored during regular builds.

Thanks,very helpful.
