### ISSUE TITLE
text/template: crash when template.ExecuteTemplate, bug probability is less than 1%

### ISSUE THREAD

**Issue by gopherbot** [golang/go#6516]
by **ssm.fox**:

<pre>What is the expected output?
render site html content

What do you see instead?
crash, I have attache the detail log

Which compiler are you using (5g, 6g, 8g, gccgo)?
6g

Which operating system are you using?
Ubuntu 12.04.1 LTS
uname -a
Linux xx 3.2.0-29-generic #46-Ubuntu SMP Fri Jul 27 17:03:23 UTC 2012 x86_64 x86_64
x86_64 GNU/Linux

Which version are you using?  (run 'go version')
go version go1.1.1 linux/amd64

Please provide any additional information below.</pre>

Attachments:

1. <a href="https://storage.googleapis.com/go-attachment/6516/0/crash_log.txt">crash_log.txt</a> (9613 bytes)

**Comment by rsc** [comment]
Too old, not enough information.
