### ISSUE TITLE
Unexpected behavior of math.RoundToEven(17.1) in Golang 1.21.6 (returns 17 instead of 18)

### ISSUE THREAD

**Issue by Aghiad-Alzein-78** [golang/go#65179]
### Go version

go version go1.21.6 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/aghiad/.cache/go-build'
GOENV='/home/aghiad/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/aghiad/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/aghiad/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.6'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3578265563=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

package main

import (
	"fmt"
	"math"
)

func main(){

	fmt.Println("Value before rounding:", 17.1)
	num:=math.RoundToEven(17.1)
	fmt.Println(num)

}

### What did you see happen?

Value before rounding: 17.1
17

### What did you expect to see?

Value before rounding: 17.1
18

**Comment by seankhliao** [comment]
https://pkg.go.dev/math#RoundToEven

> RoundToEven returns the nearest integer, rounding ties to even.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by Aghiad-Alzein-78** [comment]
But I think this is a bug ,unless u think 17 is the right answer for RoundToEven() function or 17 is an even number!!
