### ISSUE TITLE
x/tools/go/packages: golist driver leaks a go command invocation

### ISSUE THREAD

**Issue by findleyr** [golang/go#65180]
Looking at the following improper shutdown in gopls:

https://build.golang.org/log/bf996ae51d525c51272637629e8dfe6ed4cb79a6

Investigating the goroutine dump there, it looks like the golist driver doesn't handle cancellation properly, and as a result leaks a goroutine that is running the Go command (which, in turn, prevents clean up of the module cache).

Specifically, the driver is here: https://cs.opensource.google/go/x/tools/+/master:go/packages/golist.go;l=154;drc=f60f2e6aa42c945111053771ea53938694791d83

But note that there are early returns that don't await that WaitGroup. My guess is that there's a race when the context is cancelled.

CC @matloob @adonovan

**Comment by matloob** [comment]
Should we defer a function that waits on the sizeswg and sets the error?

**Comment by findleyr** [comment]
Not sure how important this concurrency is, but can we move the sizes query below the `extractQueries` loop and do all out-of-process work in an errgroup? Can `runContainsQueries` execute concurrently to the `createDriverResponse` on line 197? I started looking into this and then realized I should tread carefully and file this issue.

**Comment by matloob** [comment]
Yeah I don't think it should make a big difference to move the sizes query below the extractQueries loop. They both manipulate the same fields on the response so we'd have to be careful with it but I suppose we can lock the response when we access it?
