### ISSUE TITLE
Go fails to compile the trufflehog project on i386 and armv7 without any specific error messages

### ISSUE THREAD

**Issue by yurivict** [golang/go#65187]
### Go version

go1.21 FreeBSD

### Output of `go env` in your module/workspace:

```shell
n/a - I have no access to the system where builds are failing
```

### What did you do?

Build the project github.com/trufflesecurity/trufflehog/v3 version 3.63.8

The FreeBSD package builder actually builds the package from the FreeBSD port security/trufflehog.

### What did you see happen?

The build fails on these architectures:

 *  i386 [log](https://pkg-status.freebsd.org/beefy17/data/main-i386-default/pbc67f159e5b6_sdf8a58b17a/logs/trufflehog-3.63.7.log)
 * armv7 [log](https://pkg-status.freebsd.org/ampere2/data/main-armv7-default/p4a7e52dfb9d4_s4347ef6050/logs/trufflehog-3.63.8.log)

### What did you expect to see?

n/a

**Comment by randall77** [comment]
> vendor/github.com/couchbase/gocb/v2/search/internal.go:31:62: cannot use math.MaxUint32 (untyped int constant 4294967295) as int value in argument to fmt.Errorf (overflows)

That seems like a problem in couchbase/gocb, it does not compile on 32-bit platforms. You should probably open a bug with them.
