### ISSUE TITLE
index.golang.org: incorrect number of optional parameters in the service's description

### ISSUE THREAD

**Issue by jub0bs** [golang/go#65185]
### What did you do?

Visit https://index.golang.org/#services

### What did you see happen?

That section of the page contains the following description of the Go Module Index:

> [index.golang.org](https://index.golang.org/) - [...] There are **two** optional parameters: [...]

(my emphasis)

### What did you expect to see?

Because https://github.com/golang/go/issues/59320 saw the addition of a third optional parameter (`include`), that passage should read as follows:

> [index.golang.org](https://index.golang.org/) - [...] There are **three** optional parameters: [...]

(my emphasis)

**Comment by mauri870** [comment]
cc @hyangah

**Comment by hyangah** [comment]
This is now fixed. Thanks for the report!
