### ISSUE TITLE
runtime: trace2: GoStatus at end of generation uses m.id while other events use m.procid

### ISSUE THREAD

**Issue by dominikh** [golang/go#65196]
When emitting GoStatus events for goroutines that didn't have any activity in a generation, we use `m.id` to set the event's M
https://github.com/golang/go/blob/f19f31f2e7c136a8dae03cbfe4f8ebbb8b54569b/src/runtime/trace2.go#L338

but for all other events with an M we use `m.procid` instead, for example
https://github.com/golang/go/blob/f19f31f2e7c136a8dae03cbfe4f8ebbb8b54569b/src/runtime/trace2buf.go#L113
https://github.com/golang/go/blob/f19f31f2e7c136a8dae03cbfe4f8ebbb8b54569b/src/runtime/trace2event.go#L117

This affects the M reported for goroutines that are already in syscalls when tracing begins.

/cc @mknyszek

**Comment by mknyszek** [comment]
Thanks for reporting this! Yeah, that's definitely wrong. I'll send a CL and get it in for the 1.22 release. I think this is backport-worthy anyway (small safe fix for an issue that can create broken traces).
