### ISSUE TITLE
database/sql: Scan() appends data to RawBytes

### ISSUE THREAD

**Issue by methane** [golang/go#65201]
### Go version

go1.22

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/methane/.cache/go-build'
GOENV='/home/methane/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/methane/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/methane/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/home/methane/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/home/methane/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.3'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/methane/work/go-mysql/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2142438049=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

See https://github.com/go-sql-driver/mysql/issues/1539

This is very complex to reproduce in real code because it is relating mysql protocol and go-mysql double buffering.

So I explain what is happening in this simple code and comments.

```go
var buf sql.RawBytes
rows := tx.Query(tx, "SELECT 'hoge'")
rows.Next()      // driver returns []byte("hoge") that references internal buffer.
rows.Scan(&buf)  // buf now points to driver's internal buffer.
rows.Close()

rows = tx.Query(tx, "SELECT 42")
rows.Next()      // driver returns int64(42).
rows.Scan(&buf)  // sql does `buf = strconv.AppendInt([]byte(buf)[:0], 42)`. That write "42" to the internal buffer.
```

The place database/sql breaks the buffer is here.

https://github.com/golang/go/blob/f19f31f2e7c136a8dae03cbfe4f8ebbb8b54569b/src/database/sql/convert.go#L367-L370

https://github.com/golang/go/blob/f19f31f2e7c136a8dae03cbfe4f8ebbb8b54569b/src/database/sql/convert.go#L512-L515

### What did you see happen?

Reusing RawBytes breaks internal buffer.

### What did you expect to see?

Reusing RawBytes variable should be safe.
This is very hard to debug pitfall.

**Comment by seankhliao** [comment]
I believe this is working as intended:

RawBytes documents: https://pkg.go.dev/database/sql#RawBytes

> After a Scan into a RawBytes, the slice is only valid until the next call to Next, Scan, or Close.

**Comment by methane** [comment]
I don't think this is intended behavior.

The document says "RawBytes is a byte slice that holds a reference to memory owned by the database itself."
`buf = strconv.AppendInt(buf, 42, 10)` is not documented at all.

And users don't know such behavior.
User can not expect passing same RawBytes to Scan() multiple times violates "the slice is only valid until..." limitation.
This is very hard to debug for regular gophers.

Stop appending to RawBytes will save users from this pitfall without any drawback.

**Comment by seankhliao** [comment]
ah, apologies i didn't understand before how the append was observed without api misuse.

**Comment by methane** [comment]
> If the database driver provides some other type, `Scan` reuses any existing byte slice in the `RawBytes`. This allows reusing a single underlying array across multiple calls to `Scan`. For example, if the above loop is reading an `int32` value provided by the database driver, then the loop only needs to allocate a single `[]byte` of length 4 for all iterations.
> 
> The latter case says to me that the above loop is written as intended: We reuse the same `RawBytes` across every `Scan` call to avoid allocations.

In that case, user should just use the type `[]bytes`.
`[]byte` allows memory reuse in the same way as RawBytes, and is safe.

https://github.com/golang/go/blob/f19f31f2e7c136a8dae03cbfe4f8ebbb8b54569b/src/database/sql/convert.go#L361-L366

The intention of RawBytes is using driver's internal buffer directly, instead of allocate&copy.
If RawBytes is passed to driver, it may point to internal buffer from previous Scan(). So driver must never write into it.

**Comment by methane** [comment]
I find that this behavior (using memory allocated by caller) is intended.

https://github.com/golang/go/commit/258ed3f2265a41a46e936e884d8afd6e6f646973

RawBytes has two usage. One of them is undocumented.
And mixing two makes hard to find data corruption bug.

**Comment by methane** [comment]
> Another might be to zero out any `RawBytes` scan parameters on the first `Scan`, to avoid carrying over references to driver-internal memory from a previous query.

But this makes allocation of `[]byte`.

**Comment by methane** [comment]
> However, this optimization has been present since 2014 ([CL 50240044](https://golang.org/cl/50240044)), so I'm not sure reverting it now is the right choice.

I doubt that this optimization is important.

- Almost no one knows it. (I, the driver maintainer didn't know it.)
- Using `int64`, `float64` etc doesn't need allocation&stringification.
- Using `any` need allocation, but no stringification.

How do you think? @bradfitz.

**Comment by dakusan** [comment]
I was the original reporter of this problem, and I agree that this is an unintended and undocumented behavior. The documentation makes it sound like a RawBytes will always receive a buffer pointer. One that either points directly into the raw sql buffer, or a newly allocated buffer with the data.

Overwriting the data that is currently in the buffer does not make sense and can be a security  issue. There are 3 places in sql/convert.go that write into the buffer that RawBytes currently holds. These should instead create a new buffer and set that on the RawBytes.

**Comment by dakusan** [comment]
I was going to ask on the commit but you blocked me from commenting. Just a thought, but on line 240 of `sql/convert.go`, which was modified in this commit, wouldn't it make sense to use an unsafe operation and pass the string bytes directly? Or does that go against go conventions? It would limit the new `rows.raw` member to holding only converted integral and time types, so basically after the first row was scanned in, the `rows.raw` buffer would likely never change sizes.

```
*d = s2b(s)
```

```
func s2b(s string) (b []byte) {
	str := (*reflect.StringHeader)(unsafe.Pointer(&s))
	sh := (*reflect.SliceHeader)(unsafe.Pointer(&b))
	sh.Data = str.Data
	sh.Len = str.Len
	sh.Cap = str.Len
	return b
}
```

**Comment by ianlancetaylor** [comment]
I blocked comments on the commit because we don't use GitHub for code review.  GitHub is a mirror, and almost nobody sees comments on a GitHub commit.  Comments about commits should be on the change review, which in this case is https://go.dev/cl/557917.  Thanks.

**Comment by ianlancetaylor** [comment]
To answer your question, we don't use unsafe unless there is a very significant benefit.  And in this case I don't actually see any benefit at all; `append` supports appending a string directly to a `[]byte`, which is what the code is doing now.

**Comment by dakusan** [comment]
I understand. I was just thinking the RawBytes functionality, meant for speed optimization, in which read-only use-once buffers are returned, kind of matched a use case for returning the direct bytes of a string. Thanks for answering though.

**Comment by d-bytebase** [comment]
I encountered this bug as well by reading bit(1) as sql.RawBytes instead of []byte. Switching to []byte seems to solve the corruption issue. This is very dangerous behavior when we talk about database reads...

**Comment by dakusan** [comment]
@d-bytebase They actually fixed it in go1.23 . This should have been marked as completed.
