### ISSUE TITLE
x/website: The drop down arrow icon is not shown on Firefox

### ISSUE THREAD

**Issue by manbaum** [golang/go#65227]
### What is the URL of the page with the issue?
 
[https://go.dev/](https://go.dev/)
 
### What is your user agent?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:109.0) Gecko/20100101 Firefox/115.0
 
### Screenshot
 
![2024-01-23_10-31-15](https://github.com/golang/go/assets/1811348/4b8e1afe-dba8-4d66-a732-5fbb8c59d375)
  
### What did you do?
 
I just open the home page of go.dev.

### What did you expect to see?
 
If the browser is Chrome, the menu at the top line is ok, see below:

![2024-01-23_10-37-40](https://github.com/golang/go/assets/1811348/2bb6403b-06e8-4bb5-9351-0c6b60e83301)

I expect to see a normal page in Firefox.
 
### What did you see instead?

If the browser is Firefox, the drop down arrow icon is not shown, why?

**Comment by Omkar76** [comment]
I don't see this issue in firefox. Maybe some extension is messing around with it. Turn off all your extensions and then try.

**Comment by cherrymui** [comment]
The text "arrow_drop_down" in the screenshot is interesting. Maybe the icon is missing, or something prevents it from displaying?

@manbaum could you try a newer version of Firefox? And as @Omkar76 mentioned, with extensions disabled? Thanks.

**Comment by manbaum** [comment]
Oh, my fault. When I turn off some add-ons, the problem is gone. Thx @Omkar76 and @cherrymui.
