### ISSUE TITLE
spec: document range-over-func

### ISSUE THREAD

**Issue by rsc** [golang/go#65237]
Tracking bug for adding range-over-func to spec. See #61405.

**Comment by 3052** [comment]
@griesemer this example is not great

~~~go
// print hello world
f := func(yield func(string) bool) {
	if yield("hello") {
		yield("world")
	}
}
for word := range f {
	println(word)
}
~~~

its not clear when `yield` would return `true` or `false`, looking at the example alone

**Comment by griesemer** [comment]
@3052 Agreed. And there's a TODO (html comment) in the spec to fix it. One step at a time.

**Comment by 3052** [comment]
one of the reasons I love Go is that it is very "readable", but the above example is not that at all. I will be patient and wait on updates to the example, but I have strong concerns about the impact of this new change on how easy it is to read Go code.

**Comment by Malix-off** [comment]
@griesemer https://github.com/golang/go/issues/65237#issuecomment-2147899109

> there's a TODO (html comment) in the spec to fix it

Is there an opened issue about it ?

**Comment by griesemer** [comment]
Change is in the works.
