### ISSUE TITLE
x/vuln: How is this tool intended to be used in an air-gapped development environment?

### ISSUE THREAD

**Issue by tpihl** [golang/go#65230]
### govulncheck version

N/A

### Does this issue reproduce at the latest version of golang.org/x/vuln?

N/A

### Output of `go env` in your module/workspace:

```shell
N/A
```

### What did you do?

N/A

### What did you see happen?

N/A

### What did you expect to see?

Documentation on how to bring the db and tooling into a usb-stick and how to set up and run it as similar for the isolated development environment (with no access to internet).

**Comment by zpavlinovic** [comment]
govulncheck [documentation](https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck) states that one can "use the -db flag to specify a different database...." This information is also available through `govulncheck -help` and by following the documentation [links](https://go.dev/doc/security/vuln/database) on the database.

So if you have a local database at `/path/to/db`, you can run `govulncheck -db file:///path/to/db`. 

We'll provide instructions on how to download the Go vulnerability database locally soon.

**Comment by tatianab** [comment]
Hello, we have just released a new feature that allows bulk download of the Go vulnerability database. It is available at https://vuln.go.dev/vulndb.zip.

For example, to download and unzip the database, and run govulncheck with it:
```sh
$ curl https://vuln.go.dev/vulndb.zip -s --output vulndb.zip
$ unzip -qq vulndb.zip -d vulndb
$ govulncheck -db file://$PWD/vulndb -version ./...
```
