### ISSUE TITLE
x/telemetry: implement report upload sampling

### ISSUE THREAD

**Issue by findleyr** [golang/go#65239]
Reminder issue: before rolling out the telemetry prompt to 100%, we need to incorporate sub-sampling via the CounterConfig.Rate.

This mechanism is incomplete and dormant.

**Comment by findleyr** [comment]
CC @pjweinb I think you did this? Is there anything more to do here?

**Comment by pjweinb** [comment]
i think it is done

**Comment by findleyr** [comment]
Thanks.
