### ISSUE TITLE
x/build: netbsd-arm64-bsiegert builder offline

### ISSUE THREAD

**Issue by dmitshur** [golang/go#65242]
https://ci.chromium.org/ui/p/golang/builders/ci/gotip-netbsd-arm64?limit=200 shows the last successful build was 14 days ago, and the builder is currently offline. It seems to need some attention, filing this issue to track that.

CC @bsiegert.

**Comment by bsiegert** [comment]
The machine needed a hard reset. Fixed.

I have one more question: There are two arm64 builder machines. The one that was offline is running a gobuilder *and* a swarming bot. The other one is only running a gobuilder. I noticed there are tasks coming in on *both* of these. Is that intended?

**Comment by dmitshur** [comment]
Thanks for resetting it.

> The one that was offline is running a gobuilder and a swarming bot. The other one is only running a gobuilder.

Is that something you have control over on your side or is a change needed elsewhere? Since the second machine still connects to the old infrastructure, it seems better to update the machine that has both a swarming bot (new, LUCI) and buildlet (old, coordinator) to have just the former. That is, for now you can have:

- 1 machine receiving work from new LUCI
- 1 machine receiving work from old coordinator

When we get to switching to using LUCI as the primary system for post-submit and begin winding down the old system, you can update both machines to connect and receive work from LUCI.

**Comment by bsiegert** [comment]
It's in my control.

This is good guidance, I will have one machine with the gobuilder and one with the swarming bot for now.
