### ISSUE TITLE
proposal: encoding/gob: remove panic on nil pointer values in EncodeValue

### ISSUE THREAD

**Issue by callthingsoff** [golang/go#65268]
## Proposal Details

Remove the intentional panic that was previously encountered when EncodeValue was passed nil values.

Previously, we panicked so as to maintain logical cohesion, like one would encounter when dereferencing a nil pointer in Go code. However, that makes for a not-great developer experience, thus this change instead returns an error that users can inspect.

This is based on #31664, and requested to be revised into a proposal in [CL 554415](https://go-review.googlesource.com/c/go/+/554415).

**Comment by ianlancetaylor** [comment]
CC @robpike
