### ISSUE TITLE
import/path: My development environment is windows, I use "GOOS=aix GOARCH=pcc64 CGO_ENABLED=0 go build" command to compile the aix host file, aix oslevel=7.2.0.0, "Illegal instruction(coredump)" is reported when executing the file on aix host. I have tried to go version 1.13, 1.15, 1.17, 1.19, 1.21, all of them are the same error. The compilation can be successful, but the execution error is reported. How can I solve it?

### ISSUE THREAD

**Issue by Neo4jvv** [golang/go#65272]
### Go version

go version go1.21.6 windows/amd64

### Output of `go env` in your module/workspace:

```shell
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\pytech\AppData\Local\go-build
set GOENV=C:\Users\pytech\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\pytech\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\pytech\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=D:\go1.21.6.windows-amd64\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=D:\go1.21.6.windows-amd64\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.21.6
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\pytech\AppData\Local\Temp\go-build204569819=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

package main

import (
	"fmt"
	"runtime"
)

func main() {
	fmt.Printf("GOOS: %s\n", runtime.GOOS)

	switch runtime.GOOS {
	case "linux":
		fmt.Println("Running on Linux")
	case "aix":
		fmt.Println("Running on AIX")
	case "windows":
		fmt.Println("Running on Windows")
	default:
		fmt.Println("Unknown operating system")
	}
}

### What did you see happen?

![微信图片_20240124142858](https://github.com/golang/go/assets/121590575/1538ba9f-733a-4f60-98bf-d4de7e893b51)

### What did you expect to see?

.

**Comment by Neo4jvv** [comment]
I wrote the code as a simple output of the current system type, as a substitute for "hello world"

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by qiulaidongfeng** [comment]
This could be a bug.
Do a different fmt.Println according to runtime.GOOS, and this should work fine.

**Comment by Neo4jvv** [comment]
@qiulaidongfeng I'm not sure I know what you mean

**Comment by qiulaidongfeng** [comment]
I think the program shown here should run and have no illegal instruction.
https://github.com/golang/go/issues/65272#issue-2099372566

**Comment by Neo4jvv** [comment]
@qiulaidongfeng Normally it should be. Is this problem due to a problem with my compilation method?

**Comment by qiulaidongfeng** [comment]
> @qiulaidongfeng Normally it should be. Is this problem due to a problem with my compilation method?

No. More like go itself has a problem with support for GOOS=aix GOARCH=pcc64.

**Comment by Neo4jvv** [comment]
So I'm looking for a proper way to cross-compile windows>aix

**Comment by Neo4jvv** [comment]
> > 通常应该是。这个问题是由于我的编译方法有问题吗？
> 
> 不。更像是 go 本身在支持 GOOS=aix GOARCH=pcc64 方面存在问题。

When I set set GOOS=aix set GOARCH=ppc64, a new variable "GOPPC64=power8" appears in go env. This variable only supports the values "power8" and "power9", but my aix host's processor is "power7". I'm not sure this question has anything to do with that.

**Comment by qiulaidongfeng** [comment]
That's not go's problem anymore.
See https://go.dev/wiki/MinimumRequirements#ppc64-big-endian  
go support POWER8 at the minimum.

**Comment by Neo4jvv** [comment]
@qiulaidongfeng 破案了，就是版本兼容问题，同样的demo我丢到power8机器上可以正常运行
