### ISSUE TITLE
"x/website:" tour: value/pointer receiver

### ISSUE THREAD

**Issue by SRNissen** [golang/go#65278]
### Go version

Website

### Output of `go env` in your module/workspace:

```shell
Website
```

### What did you do?

Read "A Tour of Go," section "Choosing a value or pointer receiver"

### What did you see happen?

This text:

> ... (We'll see why over the next few pages.)

### What did you expect to see?

**Either**

Not that text.

**Or**

"why," somewhere over the next few pages.

**Comment by cherrymui** [comment]
As mentioned https://pkg.go.dev/golang.org/x/website/tour#readme-report-issues-send-patches , issues with the tour content should be reported to the tour repo's issue tracker. Thanks.

**Comment by SRNissen** [comment]
You've got some cross-org confusion going on I think. golang/tour has this to say on the subject:

> # Go Tour
> 
> The actual web pages for
“A Tour of Go” moved to [golang.org/x/website](https://golang.org/x/website).
> 
> This repo still holds the supporting packages like
[golang.org/x/tour/pic](https://golang.org/x/tour/pic)

Which is why I closed over there and moved it over here.
