### ISSUE TITLE
encoding/json: RawMessage should marshal without pointer receiver

### ISSUE THREAD

**Issue by augustoroman** [golang/go#6528]
<pre>The current json.RawMessage implementation defines MarshalJSON on a pointer receiver. 
This causes unexpected behavior when marshalling with non-pointer-receiver objects.

For example:
<a href="http://play.golang.org/p/Cf_6zpIKC0">http://play.golang.org/p/Cf_6zpIKC0</a>

Instead, MarshalJSON should be defined on a non-pointer receiver for json.RawMessage. 
This will continue to work for existing code that uses pointer-receivers, but will
change behavior to work &quot;correctly&quot; on code that accidentally uses
non-pointer-receivers.</pre>

**Comment by rsc** [comment]
Dup of #14493.
