### ISSUE TITLE
html/template: Some characters cannot be used in the template.

### ISSUE THREAD

**Issue by k-takeuchi220** [golang/go#65289]
### Go version

go version go1.21.1 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/ktake/Library/Caches/go-build'
GOENV='/Users/ktake/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/ktake/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/ktake/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.21.1'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK='/Users/ktake/proj/roguelike/roguelike-fe/go.work'
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/tt/d8rpr28j4_jdcs23zjgg9ksw0000gn/T/go-build1958759893=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

https://go.dev/play/p/W18cUafkh69

### What did you see happen?

`<` is replaced by `&lt;` and other special characters are output as they are.

### What did you expect to see?

I would expect `<` to be output in the same way as other special characters (>"'& etc.).
This may seem like normal behavior. I was unsure whether to report it as an issue, but I would be happy to receive an answer if it is indeed normal.

**Comment by Jorropo** [comment]
This works as intended, it's escaping characters to avoid XSS and other tags injections.

If you don't want this feature `text/template` don't do this: https://go.dev/play/p/p7bt7OM_zwj
