### ISSUE TITLE
runtime/cgo: build fails with GOARCH=arm GOARM=5 CC=clang

### ISSUE THREAD

**Issue by corhere** [golang/go#65290]
### Go version

go version go1.22rc2 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/root/.cache/go-build'
GOENV='/root/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='local'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22rc2'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3163621444=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

[Attempted to (cross-)compile a cgo program for Linux/ARMv5 using clang.](https://github.com/moby/moby/pull/46982#issuecomment-1898673129)

### What did you see happen?

```console
$ docker run --rm -it golang:1.22rc2
root@f78e65b632f2:/go# apt update && apt install -y crossbuild-essential-armhf clang
[...snip...]
root@f78e65b632f2:/go# clang --version
Debian clang version 14.0.6
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
root@f78e65b632f2:/go# CC='clang --target=armv5-none-linux-gnu -mfloat-abi=hard --sysroot=/usr/arm-linux-gnueabihf' GOARCH=arm GOARM=5 CGO_ENABLED=1 go build runtime/cgo
# runtime/cgo
gcc_libinit.c:44:8: error: large atomic operation may incur significant performance penalty; the access size (4 bytes) exceeds the max lock-free size (0  bytes) [-Werror,-Watomic-alignment]
gcc_libinit.c:47:6: error: large atomic operation may incur significant performance penalty; the access size (4 bytes) exceeds the max lock-free size (0  bytes) [-Werror,-Watomic-alignment]
gcc_libinit.c:49:10: error: large atomic operation may incur significant performance penalty; the access size (4 bytes) exceeds the max lock-free size (0  bytes) [-Werror,-Watomic-alignment]
gcc_libinit.c:69:9: error: large atomic operation may incur significant performance penalty; the access size (4 bytes) exceeds the max lock-free size (0  bytes) [-Werror,-Watomic-alignment]
gcc_libinit.c:71:3: error: large atomic operation may incur significant performance penalty; the access size (4 bytes) exceeds the max lock-free size (0  bytes) [-Werror,-Watomic-alignment]
```

### What did you expect to see?

The runtime/cgo package should build without error, like when using gcc.
```console
root@f78e65b632f2:/go# CC=arm-linux-gnueabihf-gcc GOARCH=arm GOARM=5 CGO_ENABLED=1 go build runtime/cgo
root@f78e65b632f2:/go# arm-linux-gnueabihf-gcc --version
arm-linux-gnueabihf-gcc (Debian 12.2.0-14) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by mauri870** [comment]
This seems to have been introduced with [CL505455](https://go-review.googlesource.com/c/go/+/505455) addition of `__atomic_load_n`. 

This bit `exceeds the max lock-free size (0  bytes)` looks weird, a size can never be zero, It is probably some sort of compiler bug.

```txt
clang-14 --target=armv5-none-linux-gnu -mfloat-abi=hard --sysroot=/usr/arm-linux-gnueabihf test.c
test.c:8:15: warning: large atomic operation may incur significant performance penalty; the access size (4 bytes) exceeds the max lock-free size (0  bytes) [-Watomic-alignment]
        int result = __atomic_load_n(&myVar, __ATOMIC_RELAXED);
                     ^
```

**Comment by corhere** [comment]
I think "max size 0" means that the platform does not natively support atomic operations and they have to be emulated. https://bugs.llvm.org/show_bug.cgi?id=38593

**Comment by mauri870** [comment]
Interesting! That seems to be the real reason, it is just poorly worded.

Mauri

**Comment by mauri870** [comment]
I wonder if we can just ignore the warning in runtime/cgo. Since we build with `-Werror` it ends up failing the build. Depending on the C compiler version `-Wno-atomic-alignment` might not even be available. The user can also supply this flag manually when it is needed, but given the misleading error message that might not be initially clear, but that is clang to blame.

```diff
diff --git a/src/runtime/cgo/cgo.go b/src/runtime/cgo/cgo.go
index 1e3a502918..4bd8e6a53a 100644
--- a/src/runtime/cgo/cgo.go
+++ b/src/runtime/cgo/cgo.go
@@ -29,6 +29,8 @@ package cgo
 
 #cgo solaris CPPFLAGS: -D_POSIX_PTHREAD_SEMANTICS
 
+#cgo arm CFLAGS: -Wno-atomic-alignment
+
 */
 import "C"
```

cc @golang/runtime @golang/arm

**Comment by mknyszek** [comment]
In triage, one thing we're wondering is if this error is actually benign and we're OK with unaligned atomics (which IIRC break some atomicity guarantees) or if we need to actually fix this in the code [CL 505455](https://go-review.googlesource.com/c/go/+/505455) modified.

CC @cuonglm @ianlancetaylor

**Comment by prattmic** [comment]
I don't think the issue here is alignment. I think clang is just warning that ARMv5 doesn't really have atomics, as @corhere mentioned.

In our own atomic code, we call into a kernel-provided stub to help with atomics on ARM <7: https://cs.opensource.google/go/go/+/master:src/runtime/internal/atomic/sys_linux_arm.s;l=79-83.

In the kernel, that is https://elixir.bootlin.com/linux/latest/source/arch/arm/kernel/entry-armv.S#L749 -> https://elixir.bootlin.com/linux/latest/source/arch/arm/include/asm/assembler.h#L374. For ARMv5 that is ultimately a nop, because Linux simply doesn't support SMP for ARMv5 at all.

I don't know what the clang-generated code looks like (if someone could provide the disassembly, that would be helpful), but I suspect it is just warning that it has to call into a helper.

If this is accurate, I suspect ignoring the warning is fine.

**Comment by corhere** [comment]
[Compiler Explorer](https://godbolt.org/#g:!((g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:___c,selection:(endColumn:1,endLineNumber:7,positionColumn:1,positionLineNumber:7,selectionStartColumn:1,selectionStartLineNumber:7,startColumn:1,startLineNumber:7),source:'/*+Type+your+code+here,+or+load+an+example.+*/%0Aextern+int+foo%3B%0A%0Aint+a(void)+%7B%0A++++return+__atomic_load_n(%26foo,+__ATOMIC_RELAXED)%3B%0A%7D%0A'),l:'5',n:'0',o:'C+source+%231',t:'0')),k:50.38548735591361,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:armv7-cclang1101,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'1',libraryCode:'1',trim:'0'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:___c,libs:!(),options:'-Wno-atomic-alignment+-Og',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1,wantOptInfo:'1'),l:'5',n:'0',o:'+armv7-a+clang+11.0.1+(Editor+%231)',t:'0')),k:49.6145126440864,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',m:91.76755447941889,n:'0',o:'',t:'0'),(g:!((h:output,i:(compilerName:'armv7-a+clang+10.0.0',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+armv7-a+clang+11.0.1+(Compiler+%231)',t:'0')),header:(),l:'4',m:8.232445520581111,n:'0',o:'',s:0,t:'0')),l:'3',n:'0',o:'',t:'0')),version:4)

```
a:
  push {r11, lr}
  ldr r0, .LCPI0_0
  mov r1, #0
  bl __atomic_load_4
  pop {r11, lr}
  bx lr
```

The `__atomic_load_4` symbol is defined in GCC's libatomic. (When the `-latomic` flag is provided, Compiler Explorer will link the binary but won't render the disassembly for some reason.) [The libatomic function is presumably implemented in terms of the kernel memory-barrier helper.](https://github.com/gcc-mirror/gcc/blob/f1412546ac8999b7f6eeeee8cf967ce3f31794c2/libatomic/config/linux/arm/host-config.h#L37-L39)

**Comment by ianlancetaylor** [comment]
If we only see the warnings for runtime/cgo/gcc_libinit.c, then we can add a `#pragma` line to that file to disable the warning.  Something like

    #pragma GCC diagnostic ignored "-Watomic-alignment"

**Comment by mauri870** [comment]
I just confirmed that this works. It is less intrusive than disabling the warning in a #cgo directive. Thanks, Ian.
