### ISSUE TITLE
x/build: TRY=windows-arm64 doesn't work

### ISSUE THREAD

**Issue by qmuntal** [golang/go#65307]
### Go version

-

### Output of `go env` in your module/workspace:

```shell
-
```

### What did you do?

Run the LUCI builders with `TRY=windows-arm64`. Trying with several CLs. E.g. https://go-review.googlesource.com/c/go/+/558795

### What did you see happen?

`windows-arm64` builders doesn't appear in the Checks tab.

### What did you expect to see?

`windows-arm64` builders do appear in the Checks tab.

**Comment by cherrymui** [comment]
The `TRY=` comment doesn't work for LUCI trybots (CommitQueue+1). It only works for old trybots (TryBots+1). See https://go.dev/wiki/SlowBots .

I kicked a run for windows-arm64 with old trybots on the CL.
