### ISSUE TITLE
reflect: Index(X).Type() returning slice element type instead of actual type

### ISSUE THREAD

**Issue by notyourusualaccountname2** [golang/go#65306]
### Go version

go1.22-20240109-RC01 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/usr/local/google/home/gopher/.cache/go-build'
GOENV='/usr/local/google/home/gopher/.config/go/env'
GOEXE=''
GOEXPERIMENT='fieldtrack,boringcrypto'
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/usr/local/google/home/gopher/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/usr/local/google/home/raffaelemeyer/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/lib/google-golang'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/lib/google-golang/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22-20240109-RC01 cl/597041403 +dcbe772469 X:fieldtrack,boringcrypto'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='0'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1517257978=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

When accessing an element from a slice via reflection (ie. via the `Index` method of `reflect.Value`), the returned `reflect.Value`'s type is the slice's `Elem` type, not the actual type of the value.

ie.
```
var x = []any{string("")}

reflect.ValueOf(x).Index(0).Type() // returns "interface {}" instead of "string"
```

This seems strange behavior, especially since
```
reflect.ValueOf(x[0]).Type() // returns "string"
```

See https://go.dev/play/p/YNfd_PClNWe

### What did you see happen?

```
var x = []any{string("")}

reflect.ValueOf(x).Index(0).Type() // returns "interface {}" instead of "string"
```

### What did you expect to see?

I'd expect the `Index` method to return the actual underlying value of the slice, so its Type method should point to the actual value type.

**Comment by seankhliao** [comment]
This is working as intended. For the second example, passing interface types to ValueOf results in passing the underlying type as interfaces don't nest.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
