### ISSUE TITLE
runtime/trace: flush trace data on non-throw crashes

### ISSUE THREAD

**Issue by mknyszek** [golang/go#65319]
If a Go program has tracing enabled and crashes, chances are that the most recent data (the most useful data) won't be properly flushed, and the trace will be broken. We can discard this broken part of the trace in the tooling (#65316), but it doesn't change the fact that we might loose a lot of information.

The thing is, many crashes that only impact user program state (such as nil dereferences and uncaught-but-recoverable panics) can absolutely still go through with a global buffer flush (`runtime.traceAdvance`) since the runtime state is still OK.

I'd like to suggest explicitly flushing all trace data on an uncaught panic or a crash due to some "easier" case, like nil dereferences, so that as much of the data comes out in-tact as possible.

**Comment by mknyszek** [comment]
Note: this is related to #63185 (flight recording) as well, since this could make recovering trace data from a crash while flight recording was enabled much more successful in the future. We could consider also adding the ability to install an optional handler to the flight recorder for writing out trace data in these cases, though that should probably go in the flight recording proposal.

**Comment by mknyszek** [comment]
This also goes hand-in-hand with #65316, since it's still likely the tail end of the trace data will be broken, since the crash still has to happen.

**Comment by aktau** [comment]
I'm wondering if we could do this in more cases. I think I see three top-level crashing functions (all calling `startpanic_m`):

 - [gopanic()](https://github.com/golang/go/blob/38f85967873b1cd48c20681c5dff0e9f3de18516/src/runtime/panic.go#L737): user panic calls. This one was already handled by https://go.dev/cl/562616
 - [sighandler](https://github.com/golang/go/blob/38f85967873b1cd48c20681c5dff0e9f3de18516/src/runtime/signal_unix.go#L632), which crashes on certain signals (SIGABRT, SIGQUIT, I assume SIGSEGV as well)
 - [throw()](https://github.com/golang/go/blob/38f85967873b1cd48c20681c5dff0e9f3de18516/src/runtime/panic.go#L1065) and [fatal()](https://github.com/golang/go/blob/38f85967873b1cd48c20681c5dff0e9f3de18516/src/runtime/panic.go#L1086)

Which of these paths could we conceivably add a `traceAdvance` to?
