### ISSUE TITLE
maps: Equal should not allocate on the heap

### ISSUE THREAD

**Issue by BrannonKing** [golang/go#65329]
### Go version

go1.21.6 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE='on'
GOARCH='amd64'
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/lib/go'
GOSUMDB='sum.golang.org'
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/lib/go/pkg/tool/linux_amd64'
GOVERSION='go1.21.6'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/brannon/Documents/Research/jobshop_go/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2066541701=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

Ran the memory profiler for my application.

### What did you see happen?

I saw that frequently iterating through a map with type `map[uint16]uint32` was causing memory pressure. `maps.Equal` performs an iteration on one map and indexes into the other.
![image](https://github.com/golang/go/assets/1509322/dbdfc827-b586-4371-8fc1-83fa9fb5560b)

### What did you expect to see?

I expected to be able to iterate over a map without allocating on the heap. Surely we can make `maps.Equal` not allocate on the heap. It seems that stepping through the bucket list shouldn't require a nondeterministic amount of memory.

**Comment by seankhliao** [comment]
can you please provide a minimal reproducer for the issue

**Comment by BrannonKing** [comment]
> provide a minimal reproducer
I just tried to reproduce it. I cannot reproduce it in any simple scenario. The code that fails will be open source in several months. I'll try to follow up on this then.
