### ISSUE TITLE
cmd/compile: avoid allocation when assigning a non-pointer value to an interface that already contains a value of the same type

### ISSUE THREAD

**Issue by nanokatze** [golang/go#65348]
### Go version

go1.22rc1 or older

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/nanokatze/.cache/go-build'
GOENV='/home/nanokatze/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/nanokatze/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/nanokatze/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/home/nanokatze/code/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/home/nanokatze/code/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22rc1'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1416462612=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

```
package main

import "testing"

type Big struct {
        A, B int
}

var p interface{} = Big{}

func BenchmarkInterfaceAssignment(b *testing.B) {
        b.ReportAllocs()

        for i := 0; i < b.N; i++ {
                p = Big{A: i, B: p.(Big).A}
        }
}
```

### What did you see happen?

Storing a value of sufficiently-big type into an interface{}-typed variable unconditionally allocates. 

### What did you expect to see?

Storing even a big-typed value into an interface{}-typed variable should not allocate when the said variable already contains a value of the same big type. The resulting code should check that the type of the value in the interface is the same and overwrite the pointed-at value.

**Comment by mknyszek** [comment]
CC @golang/compiler

**Comment by aclements** [comment]
Unfortunately, this won't work. Consider https://go.dev/play/p/K7qyjdoYQ77, which is similar to your example, except that it makes a copy of `p` before modifying it. After modifying `p`, the value of the copy must not have changed, which means we must have two `Big` objects in memory at that point. Hence, either copying `p` or modifying `p` must allocate for the second `Big` object.

**Comment by mknyszek** [comment]
Based on the comments from @randall77 and @aclements, closing.

**Comment by nanokatze** [comment]
Right, I didn't think of these examples, I now see why it wouldn't work.
