### ISSUE TITLE
proposal: Allow omitting types in callbacks if they can be inferred from the parameters

### ISSUE THREAD

**Issue by wasserholz** [golang/go#65369]
### Go Programming Experience

Intermediate

### Other Languages Experience

JS, Java, Python, Delphi, C

### Related Idea

- [X] Has this idea, or one like it, been proposed before?
- [ ] Does this affect error handling?
- [X] Is this about generics?
- [X] Is this change backward compatible? Breaking the Go 1 compatibility guarantee is a large cost and requires a large benefit

### Has this idea, or one like it, been proposed before?

https://github.com/golang/go/issues/21498
This issue is more general in how anonymous functions should behave, but it is not clearly defined in that proposal what should be done.

### Does this affect error handling?

No

### Is this about generics?

No, this is about inferring types from context in anonymous functions.

### Proposal

It is possible to omit types for parameters in anonymous functions when the types can be inferred from the context.

Return type can be omitted because it can be inferred from the returned value in the anonymous function.
Parameter types are omitted as they can be inferred from the outer function declaration.

### Language Spec Changes

Anonymous functions used as parameters in other functions can be written without re-declaring the parameter and return types, making anonymous functions more concise.

### Informal Change

While using anonymous functions as parameters for other functions, the type definitions for the parameters and return values can be omitted, because the can be inferred from the context.

### Is this change backward compatible?

Yes.

Given these functions:

```
func Map[T, V any](slice []T, accessor func(value T, index int) V) []V {
	output := make([]V, len(slice))
	for i, v := range slice {
		output[i] = accessor(v, i)
	}
	return output
}

func MapIntToString(slice []int, accessor func(value int, index int) string) []string {
	output := make([]string, len(slice))
	for i, v := range slice {
		output[i] = accessor(v, i)
	}
	return output
}
```

Their usage would currently looks like this:
```
func main() {
	nums := []int{1, 2, 3, 4}
	strings1 := Map(nums, func(v int, i int) string { return fmt.Sprintf("number: %v", v) })
	log.Print(strings1)

	strings2 := MapIntToString(nums, func(v int, i int) string { return fmt.Sprintf("number: %v", v) })
	log.Print(strings2)
}
```

Expected usage with this proposal:
```
func main() {
	nums := []int{1, 2, 3, 4}
	strings1 := Map(nums, func(v, i) { return fmt.Sprintf("number: %v", v) })
	log.Print(strings1)

	strings2 := MapIntToString(nums, func(v, i) { return fmt.Sprintf("number: %v", v) })
	log.Print(strings2)
}
```

**Comment by ianlancetaylor** [comment]
Closing as dup of #21498, which covers the same idea.
