### ISSUE TITLE
 x/build: add LUCI linux-loong64 builder

### ISSUE THREAD

**Issue by abner-chenc** [golang/go#65398]
### Proposal Details

 @gopherbot, please add label new-builder

**Comment by abner-chenc** [comment]
[linux-loong64-builder.csr.txt](https://github.com/golang/go/files/14110995/linux-loong64-builder.csr.txt)

**Comment by mknyszek** [comment]
I'm on rotation so I'll try to get to this this week.

**Comment by dr2chase** [comment]
Does anyone know offhand if this is a slower-than-usual builder?  (I'm on rotation this week, in the middle of doing the addition.)

**Comment by dr2chase** [comment]
and it does have network access?

**Comment by mknyszek** [comment]
@dr2chase The `SLOW_HOST` list you're referring to can be updated later if we deem them necessary.

`NO_NETWORK` does not have to do with having network access or not. They're platforms where we set up a special environment to run tests that explicitly need to run in a no-network environment.

**Comment by abner-chenc** [comment]
I haven't fully configured loong64's builder yet, and some additional settings may be needed for the builder to work properly.
But sorry, I'm on vacation recently (about a week), I'll try to finish it in advance if possible.

**Comment by dr2chase** [comment]
The certificate you provided, it is for "linux-loong64-builder", could it instead be for "linux-loong64"? That would match the pattern for all the other builders.  Thanks much, sorry for the hiccup, no rush if you are enjoying your vacation.

**Comment by abner-chenc** [comment]
[linux-loong64.csr.txt](https://github.com/golang/go/files/14321936/linux-loong64.csr.txt)

This is the certificate I regenerated using hostname "linux-loong64". Please replace  **linux-loong64-builder.csr.txt**  with the current **linux-long64.csr.txt.**　

Thanks

**Comment by abner-chenc** [comment]
Gentle ping.
Are the certificates ready?

**Comment by prattmic** [comment]
[linux-loong64-1708541172.cert.txt](https://github.com/golang/go/files/14363773/linux-loong64-1708541172.cert.txt)

**Comment by abner-chenc** [comment]
Thank you for the certificate.

I've tried to launch the swarming bot, but I came across this error:

```
luci_machine_tokend -backend luci-token-server.appspot.com -cert-pem /tmp/linux-loong64-1708541172.cert.txt -pkey-pem /home/golang/linux-loong64.key -token-file=/var/lib/luci_machine_tokend/token.json
[I2024-02-22T15:15:37.646633+08:00 1526740 0 iface.go:167] tsmon is disabled because no endpoint is configured
[I2024-02-22T15:15:37.649157+08:00 1526740 0 main.go:237] The token is valid, skipping the update
```


```
/tmp/bootstrapswarm -hostname linux-loong64 
2024/02/22 15:15:42 Bootstrapping the swarming bot with certificate authentication
2024/02/22 15:15:42 retrieving the luci-machine-token from the token file /var/lib/luci_machine_tokend/token.json (default path for GOOS != windows)
2024/02/22 15:15:42 Downloading the swarming bot
2024/02/22 15:15:44 Starting the swarming bot /root/.swarming/swarming_bot.zip
1526774 2024-02-22 07:22:00.529 E: Unable to open given url, https://chromium-swarm.appspot.com/swarming/api/v1/bot/server_ping, after 30 attempts or 360 timeout.
HTTPSConnectionPool(host='chromium-swarm.appspot.com', port=443): Max retries exceeded with url: /swarming/api/v1/bot/server_ping (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fffe0619050>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
1526774 2024-02-22 07:22:00.530 E: No response from server_ping
1526774 2024-02-22 07:26:05.915 E: Unable to open given url, https://chromium-swarm.appspot.com/swarming/api/v1/bot/handshake, after 30 attempts or 240 timeout.
HTTPSConnectionPool(host='chromium-swarm.appspot.com', port=443): Max retries exceeded with url: /swarming/api/v1/bot/handshake (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fffe0634d90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
1526774 2024-02-22 07:26:05.915 E: Failed to contact for handshake, retrying in 0 sec...
1526774 2024-02-22 07:30:10.905 E: Unable to open given url, https://chromium-swarm.appspot.com/swarming/api/v1/bot/handshake, after 30 attempts or 240 timeout.
HTTPSConnectionPool(host='chromium-swarm.appspot.com', port=443): Max retries exceeded with url: /swarming/api/v1/bot/handshake (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fffe0644ad0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
1526774 2024-02-22 07:30:10.905 E: Failed to contact for handshake, retrying in 1 sec...
1526774 2024-02-22 07:34:19.128 E: Unable to open given url, https://chromium-swarm.appspot.com/swarming/api/v1/bot/handshake, after 30 attempts or 240 timeout.
HTTPSConnectionPool(host='chromium-swarm.appspot.com', port=443): Max retries exceeded with url: /swarming/api/v1/bot/handshake (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fffe05fe490>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
1526774 2024-02-22 07:34:19.128 E: Failed to contact for handshake, retrying in 3 sec...
```

Is there something I'm doing wrong?
Thanks

**Comment by prattmic** [comment]
Can you access https://chromium-swarm.appspot.com/swarming/api/v1/bot/server_ping? That shouldn't require authentication or anything. It seems like there may be an issue with your network connection?

**Comment by abner-chenc** [comment]
＠[prattmic](https://github.com/prattmic)　The problem is that I configured the proxy environment variables https_proxy and http_proxy, but swarming_bot did not use them, which caused the network to be inaccessible.

But I don’t know how to configure it to make these environment variables take effect.

**Comment by prattmic** [comment]
I am not sure what is the correct way to configure a proxy for the swarming bot. The source code for the swarming bot is at https://source.chromium.org/chromium/infra/infra/+/main:luci/appengine/swarming/swarming_bot/bot_code/bot_main.py;l=1785;drc=0d534b7e80a34a79a114fa0a05e5e984190fdbf7 (this line is, I believe, where the `server_ping` call comes from).

I am not very familiar with this code, but digging down several layers to https://source.chromium.org/chromium/infra/infra/+/main:luci/client/utils/net.py;l=810;drc=f9002fe7a0ae6b2837c9c48112b87d820bff9ffa, it looks like this ultimately uses Python `requests`, which looks like it should respect the environment variables: https://requests.readthedocs.io/en/latest/user/advanced/#proxies. Perhaps there is some additional configuration I missed.

**Comment by abner-chenc** [comment]
I have enabled the system proxy environment settings and added Loong64 support to swarming-bot.

CL:
https://chromium-review.googlesource.com/c/infra/luci/luci-py/+/5334944
https://chromium-review.googlesource.com/c/infra/luci/luci-py/+/5334945

**Comment by abner-chenc** [comment]
> I have enabled the system proxy environment settings and added Loong64 support to swarming-bot.
> 
> CL: https://chromium-review.googlesource.com/c/infra/luci/luci-py/+/5334944 https://chromium-review.googlesource.com/c/infra/luci/luci-py/+/5334945

＠[prattmic](https://github.com/prattmic)　
　　These two CLs have been merged.  Can you update swarming_bot.zip?
　　Thanks!

**Comment by abner-chenc** [comment]
This error occurred while running the task： https://7419-34ac013-dot-chromium-swarm.appspot.com/task?id=685629cf2b55df10&w=true

**Comment by prattmic** [comment]
cc @golang/release

**Comment by abner-chenc** [comment]
I found the following error after the service ran for a while：
` HTTPSConnectionPool(host='chromium-swarm.appspot.com', port=443): Max retries exceeded with url: /swarming/api/v1/bot/rbe/session/update (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))`


But I have confirmed that the network is OK，　Here is the detailed log:  [swarming_bot.log](https://github.com/golang/go/files/14614975/swarming_bot.log)

**Comment by abner-chenc** [comment]
> This error occurred while running the task： https://7419-34ac013-dot-chromium-swarm.appspot.com/task?id=685629cf2b55df10&w=true

This problem seems to be happening again

**Comment by abner-chenc** [comment]
I am ready to connect multiple builders, but how can I distinguish the BOT_ID? The environment variable SWARMING_BOT_ID seems to be deprecated.

**Comment by abner-chenc** [comment]
> I am ready to connect multiple builders, but how can I distinguish the BOT_ID? The environment variable SWARMING_BOT_ID seems to be deprecated.

Thanks, I know how to do this.

**Comment by abner-chenc** [comment]
> > This error occurred while running the task： https://7419-34ac013-dot-chromium-swarm.appspot.com/task?id=685629cf2b55df10&w=true
> 
> This problem seems to be happening again

Gentle ping.

**Comment by abner-chenc** [comment]
Can a task be triggered on this [builder](https://7419-34ac013-dot-chromium-swarm.appspot.com/bot?id=linux-loong64)? If everything goes smoothly, I plan to take all the builders connected through the buildlet method offline and then switch them all to the LUCI access method

Thanks.

**Comment by abner-chenc** [comment]
Friendly ping.  @golang/release

Can you solve this error? ( https://7419-34ac013-dot-chromium-swarm.appspot.com/task?id=68c4af6ef5417c10)? 
I want to switch the builder’s access method to LUCI.

**Comment by cagedmantis** [comment]
I'm working on resolving that error message. As soon as it is resolved, I will respond to this issue. Thanks for pushing this along.

**Comment by abner-chenc** [comment]
> I'm working on resolving that error message. As soon as it is resolved, I will respond to this issue. Thanks for pushing this along.

Gentle ping.
Thanks.

**Comment by dmitshur** [comment]
We're still working on this on our side, and will update this after it's resolved or more progress is made. Thanks for your patience and for pushing this forward.

**Comment by abner-chenc** [comment]
Now the LUCI linux-loong64 builder can work happily. Of course, there are occasional network timeouts.
It seems that the LUCI method requires much greater network bandwidth than the previous buildlet method.

Thanks！

**Comment by cagedmantis** [comment]
We are glad to hear that it's working now. Now that the builder is up and running, is there any reason we can't close this issue? Thank you for all of your work.
