### ISSUE TITLE
generics throw "invalid recursive type: X refers to itself" while the same without generics doesn't

### ISSUE THREAD

**Issue by boindil** [golang/go#65402]
### Go version

go version go1.21.6 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/vagrant/gocache'
GOENV='/home/vagrant/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/vagrant/share/go/pkg/mod'
GONOPROXY='X.intern'
GONOSUMDB='X.intern'
GOOS='linux'
GOPATH='/home/vagrant/share/go'
GOPRIVATE='X.intern'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.6'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2182020730=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

I tried to declare a Tree in form of a map, that refers to itself.

Minimal reproduction here: https://go.dev/play/p/eeKhsioARig
```
package main

type Tree[T Tree] map[string]T

func main() {
	t := Tree{}
	_ = t
}
```

What I actually wanted is a typed map, that can on each level either contain a new map or a string: https://go.dev/play/p/yadDpSUaff8
```
package main

type Tree[T Tree | string] map[string]T

func main() {
	t := Tree{}
	_ = t
}
```

This spits out `invalid recursive type: Tree refers to itself`, however the "same" thing without generics works fine: https://go.dev/play/p/19fIOKt7qQQ
```
package main

type Tree map[string]Tree

func main() {
	t := Tree{}
	_ = t
}
```

### What did you see happen?

Its not working even though I think it should be able to, since the variant without generics is recursive, too.

### What did you expect to see?

Compiling code

**Comment by seankhliao** [comment]
This works as intended, interfaces are boxes, while generics aren't, see #65366
