### ISSUE TITLE
container/heap: confusing claim of memory leak when shrinking slices

### ISSUE THREAD

**Issue by codesoap** [golang/go#65403]
### Go version

go version go1.21.1 openbsd/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/richard/.cache/go-build'
GOENV='/home/richard/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='openbsd'
GOINSECURE=''
GOMODCACHE='/home/richard/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='openbsd'
GOPATH='/home/richard/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/openbsd_amd64'
GOVCS=''
GOVERSION='go1.21.1'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build50129197=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

I read the "PriorityQueue" example of the `container/heap` documentation.

### What did you see happen?

I came across [this line](https://github.com/golang/go/blob/master/src/container/heap/example_pq_test.go#L48), claiming to prevent a memory leak. It confused, me since I've never heard of a memory leak caused by Go slices.

Upon some pondering, I figured that the author of this line is talking about the memory, that is retained when shrinking a slice. However, I think the term "memory leak" is not right for this, since the memory will be freed once the slice becomes unused or it will be reused when the slice grows again. At most, I would call this a "[space leak](https://queue.acm.org/detail.cfm?id=2538488)".

### What did you expect to see?

I would prefer this line to be absent. It seems like a premature optimization to me and doesn't help explaining the `container/heap` package.

**Comment by mknyszek** [comment]
This is about a comment internal to the standard library, not any actual user-facing documentation.

You do not need to file an issue for this sort of thing in the future. You can just send a change and it will get reviewed. If you're unsure whether it's worth the effort, start a thread on https://groups.google.com/g/golang-dev first.

Thanks. Closing this issue.

**Comment by codesoap** [comment]
Alright thanks, I'll remember it. However, this is indeed user-facing documentation. It is part of an example, that is visible here: https://pkg.go.dev/container/heap@go1.21.6#example-package-PriorityQueue

**Comment by mknyszek** [comment]
Oh! Thank you. My apologies for not looking closely enough.
