### ISSUE TITLE
x/tools/gopls: code action to "Add switch cases for [enum|type]"

### ISSUE THREAD

**Issue by martskins** [golang/go#65411]
### gopls version

v0.14.2

### go env

```shell
Not relevant
```

### What did you do?

Consider the following snippet:

```go
type AnimalType int

const (
	AnimalTypeUnknown AnimalType = iota
	AnimalTypeDog
	AnimalTypeCat
	AnimalTypeHorse
)

func main() {
	var at AnimalType
	switch at {
	case AnimalTypeDog:
		// do stuff
	}
}
```

(I realise switching on `at` in that example doesn't make sense, just doing that to illustrate the use-case)

### What did you see happen?

N/A

### What did you expect to see?

It would be nice if gopls offered completing the missing switch arms as a code action.

I'm thinking this could be offered only when there's a finite set of cases, so it would work for defined types such as the example above, but not on basic types such as string, int, etc.

Is there an appetite to implement something like this? Or is it intentionally not supported?

**Comment by adonovan** [comment]
Nice idea! It should also support type switches: such a feature would be helpful to me to as I frequently write functions that switch over ast.Node or types.Type or types.Object.

I suggest the precise criteria should be:

- a `switch expr {}` statement should offer a code action at the "switch" keyword to "Add cases for AnimalType", if the type of expr is a named constant declared in a single const declaration. 
- a switch v.(type)` statement should offer a code action at the "switch" keyword to "Add cases for ast.Node", if the type of v is an interface. All accessible types that implement the interface and are declared in the same package as the interface type may be offered.
- If the switch already has some cases, it should fill in the missing ones.
- If all are present (or there is a "default" case), then there should be no code action.
- Only constants or types that are accessible to the switch statement (i.e. exported, or in same package) should be offered.

Do you want to take a crack at it yourself?

**Comment by martskins** [comment]
Agree with all your points! I do I think offering it when there's a default case could potentially be useful as well, but I guess it's probably better to do a first implementation without that and add it later if people think it's useful.

I'm happy to take a stab at this but I'm gonna need some hand-holding. I played around a bit trying to do this but I'm 100% sure it wasn't the right way to do it and also it fell short when the type wasn't declared on the same file that the switch was in.

I suppose this is going to have to be a `fixer` (and not a `singleFileFixer`), but I'm not sure how I'm supposed to use the cache snapshot/package to try and find the relevant types/constants.

**Comment by adonovan** [comment]
>  it fell short when the type wasn't declared on the same file that the switch was in.

Most of the computation will be done in the domain of go/types: you'll need to identify the type of the switch operand (a `types.Type`, found in `types.Info.TypeOf(expr)`), check that it is a named type (`*types.Named`), find its package,  (`Named.Obj().Pkg()`, a `types.Package`), observe that there are various accessible named constants of the same type (types.Identical) in the same package (by iterating over `Package.Scope.{Named,Lookup}`), and subtract the cases that already exist (by again using TypeOf for each case).

Type switches will be similar except that you are iterating over types, not constants, and testing compatibility with the switch operand using types.AssignableTo. You should test whether each `*T` as assignable to the interface if plain old T is not, as the pointer type may have more methods.

Send a CL when you're ready, even if just to ask for clarification.

**Comment by martskins** [comment]
Cool! That was very helpful! I think I got something more or less working, will share a CL soon!
