### ISSUE TITLE
import/path: issue title

### ISSUE THREAD

**Issue by jxwdsb** [golang/go#65424]
### Go version

go version go1.20.4 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=".exe"
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="windows"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/root/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/root/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2789866231=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

go version go1.20.4 linux/amd64
build hello, windows prompts virus file

I used version 1.20.4 to generate hello in May 2023, and Windows did not report a virus. I changed the version to 1.20.4 and regenerated hello. It still reported viruses. However, when I executed the file generated in May 2023, Windows did not report viruses.

### What did you see happen?

go version go1.20.4 linux/amd64
build hello, windows prompts virus file

I used version 1.20.4 to generate hello in May 2023, and Windows did not report a virus. I changed the version to 1.20.4 and regenerated hello. It still reported viruses. However, when I executed the file generated in May 2023, Windows did not report viruses.

### What did you expect to see?

So what is the reason why I am now using the latest version to generate files to report viruses, and replacing the 1.20.4 version to generate kernel files also reports viruses, but when I execute the files generated with version 1.20.4 in May 2023, no viruses are reported. Resolve virus reporting files

**Comment by jxwdsb** [comment]
This is build now
https://www.virustotal.com/gui/file/4737eb6b339e21080fdc4b53ed204e7c10ae2f1a39a469a49011f3fcd060d6ed?nocache=1

This was build in May 2023
https://www.virustotal.com/gui/file/f6158bd924ee47909b3197dc1be366a7c2108d0e0c9dab191f313f6777afaa3f?nocache=1

**Comment by seankhliao** [comment]
that's a problem for your antivirus vendor
https://golang.org/doc/faq#virus
