### ISSUE TITLE
go/types: nil pointer dereference in Alias.Underlying()

### ISSUE THREAD

**Issue by timothy-king** [golang/go#65455]
`Alias.Underlying()` crashes when called on an `Alias` created by `NewAlias(...)`.

1.  `NewAlias` calls `newAlias` with a `(*Checker)(nil)`.
2. `a.actual` by `Alias.cleanup()` is not set when the `(*checker)` is `nil` in `newAlias`.
3. `Alias.Underlying()` calls `a.actual.Underlying()`.

As a mitigation strategy, one can immediately call `Unalias(a)` for its side-effect after `a := NewAlias(...)`, but we should fix this.

cc @griesemer @findleyr

**Comment by adonovan** [comment]
...and while we're there, also avoid the update of the Alias.actual link in the Unalias function, which turns a getter into a setter (=> data race, as @timothy-king pointed out). Using atomic load/store on Alias.actual is one solution.

**Comment by timothy-king** [comment]
I think the following would also handle the datarace:
```
func Unalias(t Type) Type {
    if a0, _ := t.(*Alias); a0 != nil {
      return a0.actual
    }
    return t
}

func unalias(a0 *Alias)  {
	if a0.actual != nil {
		return
	}
	var t Type
	for a := a0; ; {
		t = a.fromRHS
		a, _ = t.(*Alias)
		if a == nil {
			break
		}
	}
	if t == nil {
		panic(fmt.Sprintf("non-terminated alias %s", a0.obj.name))
	}
	a0.actual = t
}

func (check *Checker) newAlias(obj *TypeName, rhs Type) *Alias {
        ...
	if check != nil {
		check.needsCleanup(a)
	} else {
	        a.cleanup()
	}

	return a
}

func (a *Alias) cleanup() {
	unalias(a)
}
```

**Comment by findleyr** [comment]
This is a common pattern: we had symmetrical bugs with instances and interfaces. Generally, the fix is to ensure we never return an incomplete object from the API. I'll send a fix.

**Comment by mknyszek** [comment]
Speaking offline, @findleyr said this can wait for the next minor release. Moving this to the Go 1.23 milestone. After the Go 1.22 release goes out, you should be able to ask gopherbot for a backport issue (unfortunately, that will not work before then). The Go1.22.1 milestone exists if you want to create the backport issue manually. Up to you.

**Comment by findleyr** [comment]
@gopherbot please consider this for backport to 1.22, it's a deterministic panic with a simple fix.
