### ISSUE TITLE
x/build: LUCI builders fail to find C compiler

### ISSUE THREAD

**Issue by cherrymui** [golang/go#65483]
```
#!watchflakes
post <- `cgo: C compiler ".*clang" not found` || `go: -race requires cgo; enable cgo by setting CGO_ENABLED=1` || log ~ `go: -race requires cgo; enable cgo by setting CGO_ENABLED=1`
```

(placeholder for watchflakes)

I assume the race failure is due to the C compiler missing.

**Comment by cherrymui** [comment]
@mknyszek I assume this is related to the clang builder? Feel free to close if this is fixed. Thanks.

**Comment by mknyszek** [comment]
Thanks. I clobbered all of these toolchains. We should hopefully be OK now. (Also, these prebuilt toolchains get completely wiped from CAS every few days.)
