### ISSUE TITLE
x/tools/gopls: missing diagnostics in GOROOT

### ISSUE THREAD

**Issue by findleyr** [golang/go#65481]
It has clearly been a while since I worked in GOROOT... It appears that the zero config changes in #57979 have broken diagnostic reporting in GOROOT. Navigation, completion works, but I'm not getting diagnostics.

This needs fixing (of course) before gopls@v0.15.0.

**Comment by findleyr** [comment]
Oh, it was because I had a go.work file in <repo root> rather than `<repo root>/src`. Moving my go.work file into `src/` works. Ok, marking as WAI.

CC @matloob -- I'm not sure why I had a go.work file in `<repo root>`, but did this ever work?

**Comment by matloob** [comment]
Off the top of my head I can't think of a reason why `<repo root>` would work differently from it being in `<src>`
