### ISSUE TITLE
x/tools/gopls: Labels are treated as parameters when assigning semantic tokens

### ISSUE THREAD

**Issue by anthony-S93** [golang/go#65494]
### gopls version

0.14.2-1

### go env

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/anthony93/.cache/go-build'
GOENV='/home/anthony93/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/anthony93/Devfiles/.go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/anthony93/Devfiles/.go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/lib/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/lib/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.6'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/anthony93/Devfiles/testing/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build410492386=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

Create a label called `mylabel` and then inspect the semantic token assigned to it using an inspection tool.

### What did you see happen?

The language server treats `mylabel` as function parameters rather than a keyword or a variable. 

On Neovim:

![2024-02-03-21-05-49](https://github.com/golang/go/assets/69449791/5d57cfc1-85ad-450a-ae76-6509fd6012da)

On VsCode:

![2024-02-03-20-56-53](https://github.com/golang/go/assets/69449791/016cdf97-19ec-4c59-a188-de43d9c966cc)

### What did you expect to see?

I'm not sure if it's because I'm misinterpreting the language, but I don't think labels and function parameters are semantically equivalent. I would expect a more appropriate semantic token to be assigned to labels. Either that, or don't assign any semantic tokens to labels at all—a syntax highlighter like Treesitter can detect labels just fine since labels require a special syntax.

**Comment by pjweinb** [comment]
The first choice for Go might be to do whatever vscode does for semantic
tokens of labels in Typescript.

**Comment by anthony-S93** [comment]
> The first choice for Go might be to do whatever vscode does for semantic tokens of labels in Typescript.
Is there a workaround for this? I don't want to turn off semantic highlighting entirely because I actually find it useful.

**Comment by pjweinb** [comment]
there is nothing at the moment. (You can turn off semantic tokens for
strings and numbers.)

Is it the color that you don't like?

**Comment by anthony-S93** [comment]
> there is nothing at the moment. (You can turn off semantic tokens for strings and numbers.) Is it the color that you don't like?

I use LSP semantic tokens to visually differentiate between function parameters and normal variables inside function bodies. This is one feature of semantic tokens that I find particularly useful. The problem now is that labels are assigned the same semantic tokens as function parameters, causing the highlighting rules that apply to function parameters to also apply to labels. This kind of defeats my original use case, which is to visually differentiate function parameters.

And then there is also the issue with inconsistency. The current implementation of `gopls` only treats labels as parameters at the places where those labels are _defined_, not at the places where they are _used_ (in a `continue` statement, for example).  
![2024-02-04-09-34-21](https://github.com/golang/go/assets/69449791/1f0e960c-9305-4190-924c-b779e159deec)

In this screenshot, you can see different highlighting rules being applied to `mylabel` depending on where it is used. The two `mylabel`s in this case are semantically the same even though they are not syntactically equivalent. My suggestion is to avoid assigning semantic tokens to labels altogether and just let the syntax highlighter take care of it.
