### ISSUE TITLE
crashes at _cgo_topofstack

### ISSUE THREAD

**Issue by luojc0517** [golang/go#65504]
### Go version

go1.21.1

### Output of `go env` in your module/workspace:

```shell
android
```

### What did you do?

"I'm running a cgo application in an Android environment, and it crashes at _cgo_topofstack. How can I troubleshoot this issue?"

### What did you see happen?

crash report
```
signal 11 (SIGSEGV), code -6 (SI_TKILL), fault addr --------
    r0  00000000  r1  000028f3  r2  0000000b  r3  00000008
    r4  00002829  r5  92589500  r6  92589548  r7  0000010c
    r8  00000007  r9  f2dda124  r10 92589400  r11 bc3218ca
    ip  bf21e9cc  sp  eeb7fc00  lr  bb39d2f8  pc  bb3c07d8

backtrace:
      #00 pc 0049a7d8  /data/app/~~RaMB3k_xm7v41sDHB5G52Q==/com.tencent.supercar-Qe2_Smo7BnMcTvBrMSmgRA==/lib/arm/libtskm.so
```

addr2line result
```
./arm-linux-androideabi-addr2line -e /Users/jackieluo/Downloads/houzhuang/armeabi-v7a-r20b/libtskm.so -f -C 0049aab0
_cgo_topofstack
??:?
```

### What did you expect to see?

no crash

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by vitbulio** [comment]
I have the same problem on iOS

**Comment by adeaddroid** [comment]
@luojc0517 Hi
i have same error 
did u find any solution ?
