### ISSUE TITLE
proposal: net: enable DualStack by default

### ISSUE THREAD

**Issue by mpldr** [golang/go#65502]
### Proposal Details

With FOSDEM being around, one of the libraries we're relying on does not have `DualStack` enabled. Patching this would be very simple, but I don't see a reason to not go the route of `(tls.Dialer).PreferServerCipherSuites` and enable `DualStack` by default.

**Comment by seankhliao** [comment]
as noted in the field docs, the DualStack setting is deprecated, and its replacement of FastFallback already has a reasonable default.
