### ISSUE TITLE
x/tools/gopls: panic in ast.Walk

### ISSUE THREAD

**Issue by danp** [golang/go#65516]
Getting this panic using gopls golang/tools@a1fbc781c2e5ebb63742eb7d6927a638ab448514 and Go tip:

```
runtime.gopanic:59
runtime.panicmem:?261
go/ast.Walk:184
go/ast.Inspect:?397
golang.org/x/tools/gopls/internal/golang.highlightPath:29
golang.org/x/tools/gopls/internal/golang.Highlight:31
golang.org/x/tools/gopls/internal/server.(*server).DocumentHighlight:14
golang.org/x/tools/gopls/internal/protocol.serverDispatch:280
golang.org/x/tools/gopls/internal/lsprpc.(*streamServer).ServeStream.ServerHandler.func3:5
golang.org/x/tools/gopls/internal/lsprpc.(*streamServer).ServeStream.handshaker.func4:52
golang.org/x/tools/gopls/internal/protocol.Handlers.MustReplyHandler.func1:2
golang.org/x/tools/gopls/internal/protocol.Handlers.AsyncHandler.func2.2:3
runtime.goexit:0
```

Noticed since gopls was exiting, sourced this stack from my local telemetry data. I assume it will be uploaded at some point but wanted to bring it up.

Maybe related to golang/tools@85146f5b48ef9cb082397e54dab98b7861424bdc / #60589?

**Comment by findleyr** [comment]
Indeed, this is almost certainly a new crash introduced by my CL. Thanks!

**Comment by adonovan** [comment]
Congratulations: you discovered the the first auto-reported crash to pass through the new machinery that landed on Friday!
