### ISSUE TITLE
x/pkgsite: stale go-source meta tag information means identifiers are not hyperlinked to source

### ISSUE THREAD

**Issue by myitcv** [golang/go#65512]
### What is the URL of the page with the issue?
 
https://pkg.go.dev/cuelabs.dev/go/oci/ociregistry#Descriptor
 
### What is your user agent?
 

 
[Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36](https://explore.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes) 
 
### Screenshot
 

 
n/a
 
### What did you do?
 
Tried to click on the `Descriptor` identifier to jump to the source code.
 
### What did you expect to see?
 
A hyperlinked `Descriptor` attribute taking me to the source code:

https://github.com/cue-labs/oci/blob/HEAD/ociregistry/interface.go#L85
 
### What did you see instead?

No hyperlink.

I think this is an instance of `go-source` changing and pkgsite not detecting that it needs to invalidate caches: https://github.com/golang/go/issues/46203

See previous https://github.com/golang/go/issues/47335

**Comment by mvdan** [comment]
cc @golang/pkgsite who can help us refresh the cache, like Julie did last time in https://github.com/golang/go/issues/47335#issuecomment-884890013? I seem to understand she's no longer part of the team, so I don't want to ping her directly.

**Comment by myitcv** [comment]
This got resolved as a side effect of a new version of `cuelabs.dev/go/oci/ociregistry` being published.
