### ISSUE TITLE
internal compiler error, More should only use concrete types

### ISSUE THREAD

**Issue by wingyiu** [golang/go#65537]
### Go version

go version go1.18.10 darwin/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/xxx/Library/Caches/go-build"
GOENV="/Users/xxx/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/xxx/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/xxx/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/xxx/sdk/go1.18.10"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/xxx/sdk/go1.18.10/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18.10"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/xxx/Git/devops/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/z2/6mn_0xzn37zbv121k0rzj7rm0000gn/T/go-build3144700714=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?

GoLand run debug

### What did you see happen?

# github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/costmanagement/armcostmanagement/v2
<autogenerated>:1: internal compiler error: dictionary for (*Pager[go.shape.struct { "".BenefitRecommendationsListResult }_0]).More should only use concrete types: go.shape.struct { "".BenefitRecommendationsListResult }_0

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new
# github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v5
<autogenerated>:1: internal compiler error: dictionary for (*Pager[go.shape.struct { "".AvailabilitySetListResult }_0]).More should only use concrete types: go.shape.struct { "".AvailabilitySetListResult }_0

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new
# github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork/v4
<autogenerated>:1: internal compiler error: dictionary for (*Pager[go.shape.struct { "".AdminRuleCollectionListResult }_0]).More should only use concrete types: go.shape.struct { "".AdminRuleCollectionListResult }_0

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new

### What did you expect to see?

no errs

**Comment by ALTree** [comment]
Thanks for reporting this. 

This looks like #52181 which has been fixed since 1.19. Please upgrade to a recent Go version. 
Anyway 1.18 is no longer supported so the fix won't be backported, so I'm closing this issue as nothing else is left to fix.
