### ISSUE TITLE
doc: update spec on go.dev

### ISSUE THREAD

**Issue by FedorLap2006** [golang/go#65575]
It seems [the language spec on go.dev](https://go.dev/ref/spec) is out of date (last update was made in Aug 2023).
This is particularly problematic, as the release notes link to it, and new `range <number>` syntax is nowhere to be seen. 

[doc/go_spec.html](https://github.com/golang/go/blob/master/doc/go_spec.html) is up to date on the other hand, so this probably just needs to be refetched.

P.S. I'm not quite sure how it works around here, so please excuse me, if the update on the website just takes a bit of time or if I'm reporting the problem in the wrong place.

**Comment by ianlancetaylor** [comment]
Thanks for reporting this.  The spec at go.dev/ref/spec is the spec for the current released version.  Up until yesterday, it was correctly reporting the language spec for 1.21.  As we just released 1.22, it now reports the language spec for 1.22.

**Comment by FedorLap2006** [comment]
I understand. That's why I created the issue. Thanks!
