### ISSUE TITLE
dl: No longer able to download a new Go toolchain from an old Go version

### ISSUE THREAD

**Issue by punya** [golang/go#65599]
As a result of https://go-review.googlesource.com/c/dl/+/540221, (https://github.com/golang/dl/commit/2a66dfb9a9cf29fab51425f5c052d40437875c70)

`go get golang.org/dl/go1.19.13` run from any Go version <= 1.16 now fails with:
```
# golang.org/dl/internal/version
go/src/golang.org/dl/internal/version/signal_unix.go:14: signalsToIgnore redeclared in this block
	previous declaration at go/src/golang.org/dl/internal/version/signal_notunix.go:13
go/src/golang.org/dl/internal/version/version.go:151: undefined: os.WriteFile
go/src/golang.org/dl/internal/version/version.go:322: undefined: io.ReadAll
```
because `//+build` was removed and `//go:build` is not supported on those versions.

My CI pipeline run from an old Debian that tries to download a newer Go version now fails because of this change.

_Originally posted by @delthas in https://github.com/golang/go/issues/60268#issuecomment-1838391097_

**Comment by seankhliao** [comment]
as noted in the original issue, those versions are outside of our support window (2 most recent major releases)

**Comment by punya** [comment]
You're right that the original issue calls out the support window. However, I think it's worth making a distinction between the `golang.org/dl` package which is often used to install a desired version of Go, and the other packages which are used as libraries.

If this is working as intended, please consider adding a prominent note to [https://go.dev/doc/manage-install](https://go.dev/doc/manage-install) documenting the minimum version.

**Comment by punya** [comment]
Perhaps the team's intent is that dl is really for installing *older* versions of Go, not *newer* ones? It does seem worth clarifying.

**Comment by ianlancetaylor** [comment]
CC @golang/release

**Comment by seankhliao** [comment]
consider https://github.com/golang/go/issues/44329#issuecomment-1612242935 where the use of GOVERSION may obsolete the use golang.org/dl (assuming a new enough starting version)
