### ISSUE TITLE
x/telemetry: go version  should match that of gopls

### ISSUE THREAD

**Issue by pjweinb** [golang/go#65598]
### Go version

go version go1l21l4 darwin/amd

### Output of `go env` in your module/workspace:

```shell
irrelevant
```

### What did you do?

opened the telemetry repository

### What did you see happen?

the go version in go.mod is 1.20, while that in the gopls go.mod is g1.18

### What did you expect to see?

Telemetry has to work with gopls, and gopls by policy works for older versions of Go. Shouldn't the version of go in the telemetry go.mod file match the one in the gopls gol.mod file?

**Comment by hyangah** [comment]
x/telemetry works with go1.18 and go1.19 (just everything is noop and is supposed to be buildtag protected).
go1.20 is the last version where the go version in go.mod does not enforce the importing module to upgrade the go version.

**Comment by hyangah** [comment]
They don't need to match. Independently, gopls will start to use the latest go from v0.17 and I expect x/telemetry will be operating like other x repos.
