### ISSUE TITLE
x/telemetry: counter values in tests should not need mapped file

### ISSUE THREAD

**Issue by pjweinb** [golang/go#65600]
### Go version

go version go1.21.4 darwin/amd64

### Output of `go env` in your module/workspace:

```shell
irrelevant
```

### What did you do?

In a gopls test i was to check that a counter is set.

### What did you see happen?

the telemetry package requires that the counter be associated with a mapped file, which potentially confuses the test setup.

### What did you expect to see?

The code for internal/counter.Read should not require a mapped file.

**Comment by findleyr** [comment]
CC @golang/telemetry

**Comment by hyangah** [comment]
Can you clarify the test set up confusion? The intention was to have more realistic end-to-end test, especially since the file mapping, and mmap brought in uncertainty the most back then.

**Comment by pjweinb** [comment]
I'm adding some counters to measure the effectiveness of completions, and i
would like to have a test that shows that they are being exercised, to show
that the code goes through the expected paths. Writing a counter file
should not be necessary.

**Comment by hyangah** [comment]
https://github.com/golang/tools/blob/master/gopls/internal/telemetry/telemetry_test.go has many tests. Does the completion latency counter test need a different setup?
