### ISSUE TITLE
golang.org: 403 Forbiden when trying to download from rack400.com vm

### ISSUE THREAD

**Issue by Rezaheydariii** [golang/go#65628]
### Go version

go1.21.6 & go1.22.0/linux-amd64

### Output of `go env` in your module/workspace:

```shell
1:
root@id-916752:~# wget https://golang.org/dl/go1.21.6.linux-amd64.tar.gz
--2024-02-08 23:57:07--  https://golang.org/dl/go1.21.6.linux-amd64.tar.gz
Resolving golang.org (golang.org)... 2a00:1450:400e:811::2011, 142.251.39.113
Connecting to golang.org (golang.org)|2a00:1450:400e:811::2011|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-02-08 23:57:07 ERROR 403: Forbidden.
2:
root@id-916752:~# sudo tar -C /usr/local -xvf go1.21.6.linux-amd64.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

### What did you do?

I want to install Go, but I receive an error message(403 Forbidden) and it doesn't work. download website opens fine in my browser and I don't have any internet issues. This is on a Linux server with the specifications for any version of Go.

### What did you see happen?

wget https://golang.org/dl/go1.21.6.linux-amd64.tar.gz
HTTP request sent, awaiting response... 403 Forbidden
2024-02-08 23:57:07 ERROR 403: Forbidden.

### What did you expect to see?

install GO version

**Comment by Jorropo** [comment]
This looks like a virtual machine, could please share it's IP or at least the ASN used, this looks like rate limiting gone wrong.

**Comment by Rezaheydariii** [comment]
> This looks like a virtual machine, could please share it's IP or at least the ASN used, this looks like rate limiting gone wrong.

this ip : 193.163.200.248
There is no problem in the browser
thanks for this

**Comment by seankhliao** [comment]
is that a browser from the same machine?
what if you use something else (e.g. currl)?
the wget output indicates it's using ipv6 but you've given an ipv4 address

**Comment by Rezaheydariii** [comment]
> is that a browser from the same machine?

yes


> what if you use something else (e.g. currl)?

curl :  curl -O -L "https://go.dev/dl/go1.21.6.linux-amd64.tar.gz"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    75  100    75    0     0    436      0 --:--:-- --:--:-- --:--:--   436
100  1449  100  1449    0     0   4911      0 --:--:-- --:--:-- --:--:--  4911



> the wget output indicates it's using ipv6 but you've given an ipv4 address

I would appreciate it if you could provide more explanation about the last solution. I cannot use wget under any circumstances and I still receive the same error.

**Comment by Jorropo** [comment]
Does `wget -4 https://golang.org/dl/go1.21.6.linux-amd64.tar.gz` also fails ?
It would be nice to know the IPv6 address of the machine too.

**Comment by Rezaheydariii** [comment]
> Does `wget -4 https://golang.org/dl/go1.21.6.linux-amd64.tar.gz` also fails ?
> It would be nice to know the IPv6 address of the machine too.

I used this method: this ok. 
wget --inet4-only https://golang.org/dl/go1.21.6.linux-amd64.tar.gz

out:
 wget --inet4-only https://golang.org/dl/go1.21.6.linux-amd64.tar.gz
--2024-02-09 23:48:02--  https://golang.org/dl/go1.21.6.linux-amd64.tar.gz
Resolving golang.org (golang.org)... 142.251.39.113
Connecting to golang.org (golang.org)|142.251.39.113|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://go.dev/dl/go1.21.6.linux-amd64.tar.gz [following]
--2024-02-09 23:48:02--  https://go.dev/dl/go1.21.6.linux-amd64.tar.gz
Resolving go.dev (go.dev)... 216.239.38.21, 216.239.32.21, 216.239.36.21, ...
Connecting to go.dev (go.dev)|216.239.38.21|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://dl.google.com/go/go1.21.6.linux-amd64.tar.gz [following]
--2024-02-09 23:48:02--  https://dl.google.com/go/go1.21.6.linux-amd64.tar.gz
Resolving dl.google.com (dl.google.com)... 142.251.36.14
Connecting to dl.google.com (dl.google.com)|142.251.36.14|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 66704768 (64M) [application/x-gzip]
Saving to: ‘go1.21.6.linux-amd64.tar.gz.3’

go1.21.6.linux-amd64.tar.gz.3       100%[===================================================================>]  63.61M   104MB/s    in 0.6s

2024-02-09 23:48:03 (104 MB/s) - ‘go1.21.6.linux-amd64.tar.gz.3’ saved [66704768/66704768]


but
But I am encountering this error again during extraction: 
:~# tar -xvf go1.21.6.linux-amd64.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by Rezaheydariii** [comment]
> Can you please show `ip addr` for the IPv6 address as IPv4 looks to be working ?

Thank you very much, the extraction was successful. I deleted the previous files and reinstalled it. And as you said @seankhliao
 @Jorropo , the problem was with IPv6 and IPv4.
