### ISSUE TITLE
x/pkgsite: please remove github.com/ldapster/gohelperfilesnewer

### ISSUE THREAD

**Issue by ldapster** [golang/go#65639]
Hi, 

Would someone remove: 

curl https://proxy.golang.org/github.com/ldapster/gohelperfilesnewer/@v/v0.0.0.info
{"Version":"v0.0.0","Time":"2024-02-09T01:36:47Z","Origin":{"VCS":"git","URL":"https://github.com/ldapster/gohelperfilesnewer","Ref":"refs/tags/v0.0.0","Hash":"dfa4d53cb9b80f3fdc1b29e9d82bf476b2b448dd"}}

Also, how long is the cache period? 

-M

**Comment by ianlancetaylor** [comment]
CC @golang/pkgsite

**Comment by seankhliao** [comment]
why do you want it removed?
