### ISSUE TITLE
x/wiki: CommonMistakes mention loopvar change in section using-goroutines-on-loop-iterator-variables

### ISSUE THREAD

**Issue by sdavids** [golang/go#65659]
### What is the URL of the page with the issue?

https://go.dev/wiki/CommonMistakes#using-goroutines-on-loop-iterator-variables

### What is your user agent?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3.1 Safari/605.1.15

### What did you do?

--

### What did you see happen?

--

### What did you expect to see?

Mention Go 1.22 similar to https://go.dev/doc/faq#closures_and_goroutines#closures_and_goroutines

and/or rewrite to Go 1.22

**Comment by sdavids** [comment]
I am unsure of the link deletion policy of _go.dev_ but you might want to keep the https://go.dev/wiki/CommonMistakes#using-goroutines-on-loop-iterator-variables link.

Other Wiki pages (or websites) might reference the link.

Maybe keep the introduction and add a note that as of 1.22 there are no common mistakes?

**Comment by seankhliao** [comment]
nothing else in the wiki references it, and it would be nice not to have so much duplication of information (the wiki link on go.dev is relatively new anyway).

**Comment by sdavids** [comment]
https://github.com/golang/go/wiki/CommonMistakes#using-reference-to-loop-iterator-variable

https://bugzilla.mozilla.org/show_bug.cgi?id=1619047#c1 has a link to the redirect above which redirects to the deleted page.

But not my decision—just mentioning it 🤷‍♂️
