### ISSUE TITLE
cmd/go: go 1.22.0: go test throws errors when processing folders not listed in coverpkg argument

### ISSUE THREAD

**Issue by sonic-martin** [golang/go#65653]
### Go version

go version go1.22.0 linux/amd64, go version go1.22.0 darwin/amd64, go version go1.22.0 windows/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN='/home/martin/bin'
GOCACHE='/home/martin/.cache/go-build'
GOENV='/home/martin/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/mnt/c/dev/git/pkg/mod'
GONOPROXY='*.mycompany.com'
GONOSUMDB='*.mycompany.com'
GOOS='linux'
GOPATH='/mnt/c/dev/git'
GOPRIVATE='*.mycompany.com'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/mnt/c/dev/git/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.0.linux-amd64'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/mnt/c/dev/git/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.0.linux-amd64/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22.0'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/mnt/c/dev/git/golang-test-cover/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2876750124=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

Have a `main.go` and a package `internal` with some functions.

See reproducer: https://github.com/sonic-martin/golang-test-cover

Run `go test`:
```shell
go test -v ./... -coverprofile=coverage.out -coverpkg=./internal/... -covermode count
go tool cover -html=coverage.out -o coverage.html
go tool cover -func=coverage.out
```

### What did you see happen?

```shell
$ go test -v ./... -coverprofile=coverage.out -coverpkg=./internal/... -covermode count
example.com/m: open /tmp/go-build1123786392/b002/covmeta.f6e4431d5ec1fd71f02b3ce4e56eb691a86525173d917007425576a7d9db7c72: no such file or directory
=== RUN   TestHelloer
--- PASS: TestHelloer (0.00s)
PASS
coverage: 100.0% of statements in ./internal/...
ok      example.com/m/internal  0.003s  coverage: 100.0% of statements in ./internal/...
$ echo $?
1
$ go tool cover -html=coverage.out -o coverage.html
$ go tool cover -func=coverage.out
example.com/m/internal/helloer.go:3:    Helloer         100.0%
total:                                  (statements)    100.0%
```

coverage.out:
```
mode: count
example.com/m/internal/helloer.go:3.23,5.2 1 1
```

The both outputs of `go tool cover` are fine.

### What did you expect to see?

Before `go 1.22.0` it worked fine and no `no such file or directory` errors happend.

There are two workarounds:

(1) `go test` with `-coverpkg` equal to the folder/packages processed

```shell
go test -v ./... -coverprofile=coverage.out -coverpkg=./... -covermode count
        example.com/m           coverage: 0.0% of statements
=== RUN   TestHelloer
--- PASS: TestHelloer (0.00s)
PASS
coverage: 50.0% of statements in ./...
ok      example.com/m/internal  0.003s  coverage: 50.0% of statements in ./...
```

But changes semantic of the coverage result.

(2) `go test` with `GOEXPERIMENT=nocoverageredesign`
```shell
$ GOEXPERIMENT=nocoverageredesign go test -v ./... -coverprofile=coverage.out -coverpkg=./internal/... -covermode count
?       example.com/m   [no test files]
=== RUN   TestHelloer
--- PASS: TestHelloer (0.00s)
PASS
coverage: 100.0% of statements in ./internal/...
ok      example.com/m/internal  0.002s  coverage: 100.0% of statements in ./internal/...
```

See the discussion from Brian Candler, Aldemar F, Thomas McNulty and me in the mailing list:
https://groups.google.com/g/golang-nuts/c/PjAWIdSdQHc

**Comment by aldemarf** [comment]
Thanks for opening this issue, Martin.

**Comment by thanm** [comment]
Thanks for the report. I will take a look.

**Comment by shaxbee** [comment]
Got bunch of CI pipelines broken after 1.22 upgrade with same `covmeta.[hash]: no such file or directory` error for packages with no tests.
Only setting `GOEXPERIMENT=nocoverageredesign` or reverting back to 1.21 is fixing it ATM.

**Comment by zegerius** [comment]
Looks like this was introduced in 36e75f67ab380f5414ecbf017e14cc4f54d4ca6d

**Comment by fredbi** [comment]
I am also facing this problem, but the go test program returns an exit status specifically on windows only

**Comment by thanm** [comment]
Thanks for the reports. I have sent a patch https://go.dev/cl/568835 that should fix this issue, if anyone wants to try it out.

**Comment by zegerius** [comment]
@thanm I tested in two projects and experience no more issues after applying your patch. Thanks, looking forward to the release.

**Comment by kavu** [comment]
@thanm Hi! As this fix already flew over the 1.22.1, may we hope that it will be cherry-picked to 1.22.2? I have high hopes for it, we have several dozens of broken pipelines here. Thank you in advance!

**Comment by thanm** [comment]
> cherry-picked to 1.22.2?

I will bring up this possibility with the release team, but given that there is a workaround it seems unlikely that this sort of backport would be approved. Backports are generally reserved for serious problems (compiler or runtime crash, incorrect results, etc) with no workaround. We'll see.

**Comment by kavu** [comment]
Thank you! 

Yeah, we already keep workaround with `GOEXPERIMENT=nocoverageredesign`, but just trying to keep faith that we won't have to wait till `1.23`. Thank you again for your work!

**Comment by muhlemmer** [comment]
For what it's worth, applying the patch on the 1.22 release branch for my local builds works fine.

**Comment by thanm** [comment]
@gopherbot please consider this for backport to 1.22

**Comment by thediveo** [comment]
Has this landed on gotip yet? I run into this issue using gotip just pulled a few moments ago.

**Comment by thanm** [comment]
Yes, this is landed on tip.  If you are still seeing it (or something like it) I would be interested in a reproducer.

**Comment by thediveo** [comment]
Thanks! It seems it was a problem of the shell alias not carrying into a shell script.
