### ISSUE TITLE
proxy.golang.org: failing requests in the European area

### ISSUE THREAD

**Issue by Dlizzz** [golang/go#65662]
go mod tidy reports i/o timeout.

`go: github.com/Dlizzz/catsnn/cmd/controller imports
        go.uber.org/zap: module go.uber.org/zap: Get "https://proxy.golang.org/go.uber.org/zap/@v/list": dial tcp: lookup proxy.golang.org on 172.17.240.1:53: read udp 10.88.0.149:36444->172.17.240.1:53: i/o timeout  

go: github.com/Dlizzz/catsnn/internal/components imports
        golang.org/x/sync/errgroup: module golang.org/x/sync/errgroup: Get "https://proxy.golang.org/golang.org/x/sync/errgroup/@v/list": dial tcp: lookup proxy.golang.org on 172.17.240.1:53: read udp 10.88.0.149:36444->172.17.240.1:53: i/o timeout  

go: github.com/Dlizzz/catsnn/internal/components imports
        google.golang.org/grpc: module google.golang.org/grpc: Get "https://proxy.golang.org/google.golang.org/grpc/@v/list": dial tcp: lookup proxy.golang.org on 172.17.240.1:53: read udp 10.88.0.149:36444->172.17.240.1:53: i/o timeout  

go: github.com/Dlizzz/catsnn/internal/components imports
        google.golang.org/grpc/codes: module google.golang.org/grpc/codes: Get "https://proxy.golang.org/google.golang.org/grpc/codes/@v/list": dial tcp: lookup proxy.golang.org on 172.17.240.1:53: read udp 10.88.0.149:36444->172.17.240.1:53: i/o timeout  

go: github.com/Dlizzz/catsnn/internal/components imports
        google.golang.org/grpc/status: module google.golang.org/grpc/status: Get "https://proxy.golang.org/google.golang.org/grpc/status/@v/list": dial tcp: lookup proxy.golang.org on 172.17.240.1:53: read udp 10.88.0.149:36444->172.17.240.1:53: i/o timeout  

go: github.com/Dlizzz/catsnn/internal/components imports
        google.golang.org/protobuf/reflect/protoreflect: module google.golang.org/protobuf/reflect/protoreflect: Get "https://proxy.golang.org/google.golang.org/protobuf/reflect/protoreflect/@v/list": dial tcp: lookup proxy.golang.org on 172.17.240.1:53: read udp 10.88.0.149:36444->172.17.240.1:53: i/o timeout  

go: github.com/Dlizzz/catsnn/internal/components imports
        google.golang.org/protobuf/runtime/protoimpl: module google.golang.org/protobuf/runtime/protoimpl: Get "https://proxy.golang.org/google.golang.org/protobuf/runtime/protoimpl/@v/list": dial tcp: lookup proxy.golang.org on 172.17.240.1:53: read udp 10.88.0.149:36444->172.17.240.1:53: i/o timeout  

go: github.com/Dlizzz/catsnn/internal/pkg/logger imports
        go.uber.org/zap/zapcore: module go.uber.org/zap/zapcore: Get "https://proxy.golang.org/go.uber.org/zap/zapcore/@v/list": dial tcp: lookup proxy.golang.org on 172.17.240.1:53: read udp 10.88.0.149:36444->172.17.240.1:53: i/o timeout  

go: github.com/Dlizzz/catsnn/internal/pkg/network imports
        google.golang.org/grpc/backoff: module google.golang.org/grpc/backoff: Get "https://proxy.golang.org/google.golang.org/grpc/backoff/@v/list": dial tcp: lookup proxy.golang.org on 172.17.240.1:53: read udp 10.88.0.149:36444->172.17.240.1:53: i/o timeout  

go: github.com/Dlizzz/catsnn/internal/pkg/network imports
        google.golang.org/grpc/credentials/insecure: module google.golang.org/grpc/credentials/insecure: Get "https://proxy.golang.org/google.golang.org/grpc/credentials/insecure/@v/list": dial tcp: lookup proxy.golang.org on 172.17.240.1:53: read udp 10.88.0.149:36444->172.17.240.1:53: i/o timeout  

go: github.com/Dlizzz/catsnn/internal/pkg/network imports
        k8s.io/api/apps/v1: module k8s.io/api/apps: Get "https://proxy.golang.org/k8s.io/api/apps/@v/list": dial tcp: lookup proxy.golang.org on 172.17.240.1:53: read udp 10.88.0.149:36444->172.17.240.1:53: i/o timeout  

go: github.com/Dlizzz/catsnn/internal/pkg/network imports
        k8s.io/api/core/v1: module k8s.io/api/core: Get "https://proxy.golang.org/k8s.io/api/core/@v/list": dial tcp: lookup proxy.golang.org on 172.17.240.1:53: read udp 10.88.0.149:36444->172.17.240.1:53: i/o timeout      

go: github.com/Dlizzz/catsnn/internal/pkg/network imports
        k8s.io/apimachinery/pkg/apis/meta/v1: module k8s.io/apimachinery/pkg/apis/meta: Get "https://proxy.golang.org/k8s.io/apimachinery/pkg/apis/meta/@v/list": dial tcp: lookup proxy.golang.org on 172.17.240.1:53: read udp 10.88.0.149:36444->172.17.240.1:53: i/o timeout

go: github.com/Dlizzz/catsnn/internal/pkg/network imports
        k8s.io/apimachinery/pkg/labels: module k8s.io/apimachinery/pkg/labels: Get "https://proxy.golang.org/k8s.io/apimachinery/pkg/labels/@v/list": dial tcp: lookup proxy.golang.org on 172.17.240.1:53: read udp 10.88.0.149:36444->172.17.240.1:53: i/o timeout

go: github.com/Dlizzz/catsnn/internal/pkg/network imports
        k8s.io/client-go/kubernetes: module k8s.io/client-go/kubernetes: Get "https://proxy.golang.org/k8s.io/client-go/kubernetes/@v/list": dial tcp: lookup proxy.golang.org on 172.17.240.1:53: read udp 10.88.0.149:36444->172.17.240.1:53: i/o timeout  

go: github.com/Dlizzz/catsnn/internal/pkg/network imports
        k8s.io/client-go/rest: module k8s.io/client-go/rest: Get "https://proxy.golang.org/k8s.io/client-go/rest/@v/list": dial tcp: lookup proxy.golang.org on 172.17.240.1:53: read udp 10.88.0.149:36444->172.17.240.1:53: i/o timeout

Error: building at STEP "RUN go mod tidy": while running runtime: exit status 1`

**Comment by seankhliao** [comment]
That's a DNS issue on your setup.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
