### ISSUE TITLE
cmd/compile: unreachable code causes internal compiler error

### ISSUE THREAD

**Issue by jrick** [golang/go#65680]
### Go version

go version go1.22.0 openbsd/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/jrick/.cache/go-build'
GOENV='/home/jrick/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='openbsd'
GOINSECURE=''
GOMODCACHE='/home/jrick/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='openbsd'
GOPATH='/home/jrick/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/home/jrick/src/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='local'
GOTOOLDIR='/home/jrick/src/go/pkg/tool/openbsd_amd64'
GOVCS=''
GOVERSION='go1.22.0'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3442254126=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

https://go.dev/play/p/NHe6QNjlr_i

### What did you see happen?

```
CLOSURE [prog.go:13:9:var n int]
<unknown line number>: internal compiler error: assertion failed

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new
```

### What did you expect to see?

No build error (except for unreachable code warnings from vet).

**Comment by thanm** [comment]
Thanks for the report.

cc @golang/compiler

**Comment by jrick** [comment]
this also affects non-loop labels https://go.dev/play/p/ylEUvtiBb1X

**Comment by jrick** [comment]
the general pattern here seems to be:

1. early unconditional return
2. declare a variable
3. declare a label
4. use the variable after the label.  assignments to `_` will trigger the bug.  For loop labels, the variable usage can occur either inside the loop, or after.

We hit this in our "real code" due to an early unconditional return that was added near the top of a function to stub out something that wasn't ready yet.

**Comment by thanm** [comment]
Duplicate of #65593?

**Comment by jrick** [comment]
Yes, appears to be.
