### ISSUE TITLE
"crawshaw.io/sqlite": Compilation inconsistency

### ISSUE THREAD

**Issue by curiosport** [golang/go#65693]
### Go version

go 1.22.0

### Output of `go env` in your module/workspace:

```shell
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\myuser\AppData\Local\go-build
set GOENV=C:\Users\myuser\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\myuser\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\myuser\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.22.0
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\myuser\AppData\Local\Temp\go-build1645723669=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

I have this simple program:
```
package main

import (
	"crawshaw.io/sqlite"
)

type Buffer struct {
	conn *sqlite.Conn
}

func main() {
	b := &Buffer{}

	_ = b
}
```

When I compile it for Windows I use this command:
`go build -o "sample.exe"`
And the compilation works without any problem, but when I compile it for Linux using this command I get an error:
`set GOOS=linux&&set GOARCH=amd64&&go build -o "sample"`

```
.\main.go:8:15: undefined: sqlite.Conn
```

Reproducible example:
https://go.dev/play/p/puAd3icvors?v=goprev

### What did you see happen?

 Does not compile when the target operating system is Linux in cross-platform code.

### What did you expect to see?

 A binary to be able to use it on Linux.

**Comment by seankhliao** [comment]
cgo is disabled by default for cross compilation.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
