### ISSUE TITLE
html/template: errors returned from MarshalJSON are not correctly escaped

### ISSUE THREAD

**Issue by rolandshoemaker** [golang/go#65697]
If a type passed to the template action has a JSON marshaller, and that MarshalJSON method fails, the returned error is inserted into the template inside of a comment. In order to avoid cases where that error contains user content, which may itself contain a closing comment token (`*/`), we do a find/replace for comment tokens and replace them with `* /`.

This doesn't take into account the confusing handling of closing script, and comment tags (`</script` and `<!--` respectively), which may also be present in user content. We can fix this by treating these tags the same way we do elsewhere in the script context, by taking the [HTML specification recommendation](https://html.spec.whatwg.org/multipage/scripting.html#restrictions-for-contents-of-script-elements) and replacing them with `\x3C/script` and `\x3C!--` in the same way we are currently handling closing comment tokens.

e.g. https://go.dev/play/p/gjCDVopt-zc

Thanks to RyotaK (@ry0tak) for reporting this issue.

**Comment by rolandshoemaker** [comment]
@gopherbot please open backport issues, this is a PUBLIC track security issue.

**Comment by joelsmith** [comment]
This issue is https://pkg.go.dev/vuln/GO-2024-2610

**Comment by raghvendra-dixit** [comment]
IS there a plan to backport this issue to go 1.20?

**Comment by seankhliao** [comment]
No, 1.20 isn't a supported release anymore.
