### ISSUE TITLE
x/pkgsite: module root page not rendered

### ISSUE THREAD

**Issue by hugelgupf** [golang/go#65701]
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/u-root/mkuimage

### What is your user agent?

Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

### Screenshot

![Screenshot 2024-02-13 21 57 20](https://github.com/golang/go/assets/1994130/d7a9439a-9472-40ed-8991-544381cb44d9)

![Screenshot 2024-02-13 21 56 57](https://github.com/golang/go/assets/1994130/27fd40d5-57d3-4662-9da6-c842e653426a)

![Screenshot 2024-02-13 21 56 44](https://github.com/golang/go/assets/1994130/ec17376a-2b35-48ae-84d9-08673c4b3379)

![Screenshot 2024-02-13 21 59 55](https://github.com/golang/go/assets/1994130/0c804000-b54a-4e1c-b92a-12ab5d114cde)

### What did you do?

I'm honestly not sure how to reproduce the issue.

### What did you see happen?

Screenshot shows that "this package is not in the latest version of its module". There is however, a package there: https://github.com/u-root/mkuimage/tree/c899e87a677c2f40f7f8b248f73e3a1b17bae719

It also shows that requesting that version fails.

The sub-packages in the module shown are that of the last version that was able to be indexed, which is not what the packages are called now.

Using one of the sub-packages that still exist, fileflag, the last screenshot shows that the version *was* parsed by pkgsite and updated.

### What did you expect to see?

Documentation for the package & module.

**Comment by seankhliao** [comment]
maybe something to do with this file?
https://github.com/u-root/mkuimage/blob/c899e87a677c2f40f7f8b248f73e3a1b17bae719/dependencies.go

**Comment by findleyr** [comment]
CC @jba

The duplicate escaping is #63968.

**Comment by hyangah** [comment]
The service was updated Thursday last week. @hugelgupf Can you please check if problems still exist?

**Comment by hugelgupf** [comment]
@hyangah looks to be working now.
