### ISSUE TITLE
proposal: go/sql: `sslMode` for database in sql package

### ISSUE THREAD

**Issue by yaron12n** [golang/go#65709]
### Proposal Details

Title: Feature Request: Support for `sslMode` in SQL package

Hello,

I'd like to propose adding support for `sslMode` to the SQL package in Go. This feature would enable more flexible and secure database connections, particularly important for applications that require different levels of SSL encryption and validation based on their security needs.
"Specify how SSL/TLS is enforced in database connections"

Similar field exists in [https://pkg.go.dev/google.golang.org/api@v0.149.0/sqladmin/v1](url)

Thank you for considering this request.

**Comment by seankhliao** [comment]
that's a setting passed to db drivers, not something for the generic sql package.
