### ISSUE TITLE
x/website: https://go.dev/doc/install doesnt contain actual install step for linux

### ISSUE THREAD

**Issue by sunz1e** [golang/go#65710]
### Go version

go1.22.0

### Output of `go env` in your module/workspace:

```shell
Not applicable
```

### What did you do?

I tried to install go on linux

### What did you see happen?

Could not see the actual installation step 

### What did you expect to see?

Actual step to install go in linux

**Comment by seankhliao** [comment]
please show a screenshot of what you're seeing

**Comment by sunz1e** [comment]
I am seeing this 
Step1 says remove the older installation
Step2 says add to the path
Step3 says verify

no steps for actual command which will install the go
![image](https://github.com/golang/go/assets/20132855/eecd5a06-3de3-4fdd-a0da-b30b4467bff3)

**Comment by ianlancetaylor** [comment]
Step 1 shows the command to both remove the older installation and to install the files contained in the download.  "Remove...then extract."
