### ISSUE TITLE
cmd/compile: rangegen.go test killed on ppc64

### ISSUE THREAD

**Issue by prattmic** [golang/go#65725]
```
#!watchflakes
post <- pkg == "cmd/internal/testdir" && test == "Test/rangegen.go" && goarch ~ `ppc64`
```

`Test/rangegen.go` is occasionally getting killed on ppc64 builders.

e.g., https://ci.chromium.org/ui/p/golang/builders/ci/gotip-linux-ppc64le/b8756201558164082785/test-results?sortby=&groupby=

```
=== RUN   Test/rangegen.go
=== PAUSE Test/rangegen.go
=== CONT  Test/rangegen.go
    testdir_test.go:142: exit status 1
        command-line-arguments: /home/swarming/.swarming/w/ir/x/w/goroot/pkg/tool/linux_ppc64le/compile: signal: killed
        
--- FAIL: Test/rangegen.go (33.68s)
```

From the history, this seems to be a recent regression: https://ci.chromium.org/ui/test/golang/cmd%2Finternal%2Ftestdir.Test%2Frangegen.go?q=V%3Ago_branch%3Dmaster+V%3Agoos%3Dlinux+V%3Ahost_goos%3Dlinux+

Note that this test is very large and has caused OOMs before (#64789).

cc @golang/ppc64

**Comment by pmur** [comment]
I changed `/home/swarming` on the LUCI builders to a tmpfs mount on 2/13, that seemed to consistently fail during this test as it went over the 8G RAM limits of the container. The LUCI builders are to using quite a bit more space than the buildbot instances.

I bumped it later that day to 10G, and set up a 5G swap file on the ppc64le builder. Hopefully that is enough to keep things running, hopefully faster.

**Comment by prattmic** [comment]
Thanks for the update. For what it's worth, I got this failure on https://go.dev/cl/564137 at around Feb 14, 6pm EST. It sounds like that may be after your latest change? (This could be a bug in that WIP CL, but it seems unlikely to fail just this one test)

**Comment by pmur** [comment]
Looking at the VM, it did trigger an OOM on a container. The syslog is claiming 7.5G of that is "file" usage.

Is there any way to make LUCI more conservative with it disk usage? This seems like a pretty big jump from the old CI which also ran entirely on a tmpfs.

**Comment by prattmic** [comment]
That's a good question. I wonder how much disk this test used on the old infra. I know this test does generate an absolutely massive source file.

cc @golang/release

**Comment by pmur** [comment]
I didn't realize the ppc64 LUCI builder also needed a bump too. It is bumped to 10g.

If this doesn't crash again in the next week, this issue can be closed.

**Comment by pmur** [comment]
Poking around at the idle ppc64le builders, there is a folder "/home/swarming/.cache/gopls" which is consuming between 2.5G and 3.3G on each instance.

That's a problem. Is it possible to update LUCI to cleanup caches at the end of a test run?

**Comment by dmitshur** [comment]
I recall @adonovan used a GOPLSCACHE mechanism to help with that in the previous infrastructure ([CL 494297](https://go.dev/cl/494297)). I'm not seeing that in the LUCI infrastructure—perhaps it needs to be ported over. There's some relevant discussion in [this thread](https://go-review.googlesource.com/c/build/+/494297/comments/e8b16fff_dac21b90). CC @mknyszek.

**Comment by pmur** [comment]
For reference, this is what has accrued on linux-ppc64le-power8--05 since the last container reboot:

```
832K	.cache/gopls/013c47f3
259M	.cache/gopls/01a3ac08
136M	.cache/gopls/0634c015
88M	.cache/gopls/0d9f1c10
64M	.cache/gopls/1045283d
258M	.cache/gopls/159d94d7
142M	.cache/gopls/17fdaa63
144M	.cache/gopls/18c46665
89M	.cache/gopls/1c4c60e1
64M	.cache/gopls/223a02a4
128K	.cache/gopls/273a5340
6.7M	.cache/gopls/299fee7f
128K	.cache/gopls/29a597a4
26M	.cache/gopls/387f9f03
138M	.cache/gopls/4e2cae36
32M	.cache/gopls/575df253
128K	.cache/gopls/65191266
1.7M	.cache/gopls/694e1ff5
1.4M	.cache/gopls/6fc45050
6.7M	.cache/gopls/70bf6d67
89M	.cache/gopls/78e17b72
61M	.cache/gopls/8a118055
27M	.cache/gopls/8a786b24
6.7M	.cache/gopls/a786fe67
1.4M	.cache/gopls/a806c003
1.4M	.cache/gopls/aa30a907
33M	.cache/gopls/ac020416
832K	.cache/gopls/b0ace309
257M	.cache/gopls/b0bcd7cf
832K	.cache/gopls/b6fa81e7
42M	.cache/gopls/bcc7bedc
27M	.cache/gopls/c8caba22
41M	.cache/gopls/c99017d5
128K	.cache/gopls/cd2810e5
144M	.cache/gopls/d4694109
41M	.cache/gopls/d558ebe0
43M	.cache/gopls/d56f4029
1.9M	.cache/gopls/d67d19d4
33M	.cache/gopls/d93c051c
41M	.cache/gopls/e3926c21
138M	.cache/gopls/eeb12931
41M	.cache/gopls/f224d393
```

**Comment by adonovan** [comment]
That list sums to around 3GB, which is higher than the cache soft limit, but that's to be expected in a test environment as it is constantly generated fresh garbage. It doesn't seem like a large amount of data compared to the capacity of a typical temp volume though.

**Comment by adonovan** [comment]
> I recall @adonovan used a GOPLSCACHE mechanism to help with that in the previous infrastructure ([CL 494297](https://go.dev/cl/494297)). I'm not seeing that in the LUCI infrastructure—perhaps it needs to be ported over.

Yes, that was an effective fix for the problems of this kind we saw in the older builders. It should be as simple as setting GOPLSCACHE to a temp directory for the entire run.

**Comment by pmur** [comment]
I've set `GOPLSCACHE=/home/swarming/.swarming/w` via the container image on all ppc64x luci builders while waiting for a more generic fix.

**Comment by mknyszek** [comment]
> It should be as simple as setting GOPLSCACHE to a temp directory for the entire run.

@adonovan @pmur Can you clarify what you mean by "a temp directory"? Is the `TMPDIR` set in the builds sufficient (https://logs.chromium.org/logs/golang/buildbucket/cr-buildbucket/8755540096649505841/+/u/step/9/log/1)? That gets cleared after every run.

**Comment by adonovan** [comment]
> Is the TMPDIR set in the builds sufficient? That gets cleared after every run.

Yes, a temp directory that lasts for a complete run of tests at a single CL is ideal. Thanks.

**Comment by mknyszek** [comment]
Sent crrev.com/c/5314212. I created an explicit subdirectory in the workdir for it which will have the same effect, and I thought it might be a bit clearer to have it next to the `GOCACHE` directory.

**Comment by mknyszek** [comment]
I confirmed that the environment variable is now set in new builds to a directory that will definitely get wiped on each run. Hopefully this should be resolved.
