### ISSUE TITLE
x/pkgsite: `main` package symbols aren't documented: "There is no documentation for this package"

### ISSUE THREAD

**Issue by tylerbrandt** [golang/go#65731]
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/tylerbrandt/godoc-example@v0.0.0-20240215181740-7b2d44c96bd8/app

### What is your user agent?

Tested on Safari (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3 Safari/605.1.15) and Chrome 

### Screenshot

<img width="1792" alt="Screenshot 2024-02-15 at 11 40 30 AM" src="https://github.com/golang/go/assets/1256483/e9c9573d-a31a-44b5-9fb9-4369c9c14df0">

### What did you do?

See [linked repo](https://github.com/tylerbrandt/godoc-example) which includes:

- an `app/main.go` file (package `main`) including a documented function `SayHello`
- an `app/goodbye.go` file (package `main`) including a documented function `SayGoodbye`
- a `lib/hello/hello.go` file (package `hello`) that includes a documented function `SayHello`

### What did you see happen?

`SayHello` function in package `hello` has generated docs ([link](https://pkg.go.dev/github.com/tylerbrandt/godoc-example/lib/hello)); `SayHello` and `SayGoodbye` functions in package `main` are not ("There is no documentation for this package"; [link](https://pkg.go.dev/github.com/tylerbrandt/godoc-example/app)).

### What did you expect to see?

All 3 documented functions have generated docs. I didn't see any particular behavior of `pkgsite` which is documented as being different for the `main` package.

**Comment by seankhliao** [comment]
main packages aren't importable, so there's nothing exported, so nothing to document.
