### ISSUE TITLE
proposal: Go 2: allow passing statements directly to go and defer

### ISSUE THREAD

**Issue by jordan-bonecutter** [golang/go#65738]
## Proposal

Currently defer and go only work on function calls. I propose to allow defer and go on statements as well. For instance:

```go
func sockToChan() (<-chan []byte) {
  sock := makeSocket()
  ch := make(chan []byte)

  go func() {
    for {
      msg, err := sock.Read()
      ch <- msg
    }
  }()

  return ch
}
```

would be simpler as:

```go
func sockToChan() (<-chan []byte) {
  sock := makeSocket()
  ch := make(chan []byte)

  go for {
    msg, err := sock.Read()
    ch <- msg
  }

  return ch
}
```

Similarly, defer could use statements/blocks as well:

```go
func tryActionAndIncrementCounter(f func() error, errorCount *int) (err error) {
  defer if err != nil {
    *errorCount++
  }

  return f()
}
```

## Discussion

These examples are somewhat contrived (they could be refactored to not need these statements), but hopefully give the gist of the idea. I don't have a deep technical understanding of how defer and go are implemented under the hood, but I would imagine this could just be implemented via syntactic sugar over an anonymous function literal.

**Comment by seankhliao** [comment]
Please fill out https://github.com/golang/proposal/blob/master/go2-language-changes.md when proposing language changes
