### ISSUE TITLE
cmd/vendor: update pprof

### ISSUE THREAD

**Issue by ziler-orca** [golang/go#65741]
### Go version

go version go1.22.0 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/root/.cache/go-build'
GOENV='/root/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/root/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/root/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22.0'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/usr/local/go/src/cmd/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build4066185309=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

The maintainer of `pprof` patched the CVE for [d3-color](https://github.com/google/pprof/issues/830) and it still shows the d3 flamegraph dependency (i.e. `/usr/local/go/src/cmd/vendor/github.com/google/pprof/third_party/d3flamegraph`) in the latest version golang 

### What did you see happen?

The maintainer of `pprof` patched the CVE for [d3-color](https://github.com/google/pprof/issues/830) and it still shows the d3 flamegraph dependency (i.e. `/usr/local/go/src/cmd/vendor/github.com/google/pprof/third_party/d3flamegraph`) in the latest version golang 

### What did you expect to see?

Can you please make the necessary updates to pickup the [patch](https://github.com/google/pprof/issues/830).

**Comment by ianlancetaylor** [comment]
CC @golang/release
