### ISSUE TITLE
net/http: requests with "Transfer-Encoding: chunked" body may buffer small chunks

### ISSUE THREAD

**Issue by benburkert** [golang/go#6574]
<pre>Hello,

I am attempting to implement a client for a http fanout service in go. The utility
establishes an http connection and makes a POST request with a &quot;Transfer-Encoding:
chunked&quot; body, then reads data from stdin and writes them as individual chunks to
the request body.

I have noticed that small chunks are buffered instead of flushed to the wire
immediately. This seems to happen because the io.Reader initialized in the Request.Body
is wrapped in a bufio.Reader when building the persistent connection:
<a href="http://golang.org/src/pkg/net/http/transport.go#L509">http://golang.org/src/pkg/net/http/transport.go#L509</a>

The bufio.Reader is initialized with the default buffer size (defaultBufSize = 4096) so
chunks smaller than this size are buffered internally before sent to the wire. In my
opinion these chunks should be flushed to the wire no matter the size.

What steps will reproduce the problem?
1. run ngrep to sniff the TCP packets sent to port 8080: &quot;ngrep -W byline -d lo0
port 8080&quot;
2. start a basic web server on port 8080: &quot;{ sleep 5 ; echo -ne &quot;HTTP/1.1 200
OK\r\nContent-Length: 0\r\n\r\n&quot; ; } | nc -l 8080&quot;
3. run <a href="http://play.golang.org/p/CZaWdr4oft">http://play.golang.org/p/CZaWdr4oft</a>

What is the expected output?

The expected output from ngrep should have 3 separate TCP packets sent from the go
process to the server:

ngrep -W byline -d lo0 port 8080
interface: lo0 (127.0.0.0/255.0.0.0)
filter: (ip) and ( port 8080 )
#####
T 127.0.0.1:52415 -&gt; 127.0.0.1:8080 [AP]
POST / HTTP/1.1.
Host: 127.0.0.1:8080.
User-Agent: Go 1.1 package http.
Transfer-Encoding: chunked.
Accept-Encoding: gzip.
.
b.
First Chunk
#
T 127.0.0.1:52415 -&gt; 127.0.0.1:8080 [AP]
.
c.
Second Chunk
#
T 127.0.0.1:52415 -&gt; 127.0.0.1:8080 [AP]
.
0.
.

####
T 127.0.0.1:8080 -&gt; 127.0.0.1:52415 [AP]
HTTP/1.1 200 OK.
Content-Length: 0.
.

######

What do you see instead?

The output from ngrep only contains a single TCP packet from the go process to the
server:

ngrep -W byline -d lo0 port 8080
interface: lo0 (127.0.0.0/255.0.0.0)
filter: (ip) and ( port 8080 )
#####
T 127.0.0.1:52641 -&gt; 127.0.0.1:8080 [AP]
POST / HTTP/1.1.
Host: 127.0.0.1:8080.
User-Agent: Go 1.1 package http.
Transfer-Encoding: chunked.
Accept-Encoding: gzip.
.
b.
First Chunk.
c.
Second Chunk.
0.
.

##
T 127.0.0.1:8080 -&gt; 127.0.0.1:52641 [AP]
HTTP/1.1 200 OK.
Content-Length: 0.
.

######

Which operating system are you using?

OSX

Which version are you using?  (run 'go version')

go version go1.1.2 darwin/amd64</pre>

**Comment by cyx** [comment]
Is there a known workaround for this issue?

**Comment by bradfitz** [comment]
No. There are several easy fixes. I'm debating which I like the most. I'll try to get one into 1.5.

**Comment by cyx** [comment]
Ok thanks. So I take it I can't do any workarounds for this that doesn't involve patching the stdlib then?
Currently I've devolved into shelling into curl to make tightly streamed text output work -- but looking forward to the fix.

**Comment by bradfitz** [comment]
There are no workarounds.

**Comment by cyx** [comment]
Awesome! I'll be sure to try HEAD if this gets merged in :)
