### ISSUE TITLE
wasm/js: deadlock when use channel with in `Promise`'s `then` fatal error: all goroutines are asleep - deadlock!

### ISSUE THREAD

**Issue by KevinZonda** [golang/go#65773]
### Go version

go version go1.22.0 windows/amd64

### Output of `go env` in your module/workspace:

```shell
set GO111MODULE=on
set GOARCH=wasm
set GOBIN=
set GOCACHE=C:\Users\KevinZonda\AppData\Local\go-build
set GOENV=C:\Users\KevinZonda\AppData\Roaming\go\env
set GOEXE=
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\KevinZonda\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=js
set GOPATH=C:\Users\KevinZonda\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:/Program Files/Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.22.0
set GCCGO=gccgo
set GOWASM=
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=C:\Users\KevinZonda\GolandProjects\awesomeProject1\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-fPIC -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\KEVINZ~1\AppData\Local\Temp\go-build489661080=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

```
GOOS=js
GOARCH=wasm
```

I tried to use a WaitGroup (& channel) in wasm to handle a `Promise`'s `then`.

```go
// file: main_js.go
package main

import (
	"fmt"
	"sync"
	"syscall/js"
)

func main() {
	c := make(chan struct{}, 0)
	js.Global().Set("foo", js.FuncOf(Foo))
	<-c
}

func Foo(this js.Value, args []js.Value) any {
	var wg sync.WaitGroup
	wg.Add(1)
	js.Global().Get("bar").Invoke().Call("then", js.FuncOf(func(_this js.Value, _args []js.Value) any {
		wg.Done()
		return nil
	}))
	wg.Wait()
	fmt.Println("foo")
	return nil
}
```

```html
<!doctype html>
<html>
    <head>
        <script src="wasm_exec.js"></script>
    </head>

    <body onload="init()">
        <button onclick="foo()">Trigger</button>

        <script>
            const go = new Go();
            function init(){
                WebAssembly.instantiateStreaming(fetch("test.wasm"), go.importObject).then((result) => {
                    go.run(result.instance);
                });
                bar().then(() => {
                    console.log("Hi")
                })
            }
        
            async function bar() {
                await setTimeout(() => {}, 100)
            }

        </script>
    </body>
</html>
```

### What did you see happen?

When trigered the function `foo`, the wasm goes panic with following information (`fatal error: all goroutines are asleep - deadlock!`):

![image](https://github.com/golang/go/assets/33132228/77077479-0c84-4c58-8d06-9bfd8349d79b)

I also tried to rewrite previous code with `sync.Mutex` and channel, both panic with the same msg.

### What did you expect to see?

There is no deadlock.

**Comment by mauri870** [comment]
I think the error is misleading. The runtime shouldn't be reporting `js.handleEvent` in the stack trace, since it is a system goroutine. See https://github.com/golang/go/issues/64620.

Given this, the true error is:

```
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
main.main()
        /tmp/main.go:13 +0x7
exit status 2
```
I believe that is expected, since you are waiting on a channel without a sender, this will block forever.

**Comment by KevinZonda** [comment]
Hi. Thanks so much for getting back to me. I'm trying to understand if it is because the channel `c` in `main` has no sender so that will make this programme exit (cuz `wg` always has `.Done` during calling `then()`). I've made a few adjustments on my end, but it seems the Go program still exits:

```go
package main

import (
	"fmt"
	"sync"
	"syscall/js"
)

var c chan struct{}

func main() {
	c = make(chan struct{}, 1)
	js.Global().Set("foo", js.FuncOf(Foo))
	js.Global().Set("exitX", js.FuncOf(Exit))
	<-c
}

func Exit(this js.Value, args []js.Value) any {
	c <- struct{}{}
	return nil
}

func Foo(this js.Value, args []js.Value) any {
	var wg sync.WaitGroup
	wg.Add(1)
	js.Global().Get("bar").Invoke().Call("then", js.FuncOf(func(_this js.Value, _args []js.Value) any {
		wg.Done()
		return nil
	}))
	wg.Wait()
	fmt.Println("foo")
	return nil
}

```

**Comment by KevinZonda** [comment]
I have a guess: Go mischecks this condition's gorountine operation (waitgroup uses goroutine):

In function `Foo`, the `wg.Done()` is called under the lambda:
```go
func(_this js.Value, _args []js.Value) any {
		wg.Done()
		return nil
	}
```

But the lambda does not call explicitly (although it will be called).

go has no idea will this `Done()` be called Therefore go simply asserts the `Done()` will not be called.

**Comment by seankhliao** [comment]
syscall/js.FuncOf says:

> As a consequence, if one wrapped function blocks, JavaScript's event loop is blocked until that function returns. Hence, calling any async JavaScript API, which requires the event loop, like fetch (http.Client), will cause an immediate deadlock.

The wrapped function `Foo` blocks on `wg.Wait`, blocking the js event loop, so it can't handle the `bar.then` chain async.

I agree that this is working as documented.
