### ISSUE TITLE
cmd/yacc: $$Tokname() does not show correct token name, TOKSTART is wrong

### ISSUE THREAD

**Issue by gopherbot** [golang/go#6577]
by **cornelius.howl**:

<pre>In my case, the generated token ID by goyacc starts from 57346:

    const T_DOT = 57346
    const T_IDENTIFIER = 57347
    const T_FLOATING = 57348
    const T_NUMBER = 57349
    const T_STRING = 57350

And here is the generated table:

    var MyToknames = []string{
    &quot;T_DOT&quot;,
    &quot;T_IDENTIFIER&quot;,
    &quot;T_FLOATING&quot;,
    &quot;T_NUMBER&quot;,
    &quot;T_STRING&quot;,
        ....

But the $$Tokname() function takes the token ID from 4:

     func CoffeeTokname(c int) string {
    // 4 is TOKSTART above
    if c &gt;= 4 &amp;&amp; c-4 &lt; len(CoffeeToknames) {
        if CoffeeToknames[c-4] != &quot;&quot; {
            return CoffeeToknames[c-4]
        }
    }
    return __yyfmt__.Sprintf(&quot;tok-%v&quot;, c)
    }

If I modify the TOKSTART in the yacc.go, my grammar file will be broken.</pre>

**Comment by naegelejd** [comment]
One problem with just adding a new function is that tokens don't have to be named. If you generate the parser for the example `expr` calculator found in `src/cmd/yacc/testdata`, you'll see that there is only one enumerated token:
```go
const NUM = 57346
```
but the slice of names includes all tokens:
```go
var exprToknames = []string{
    "'+'",
    "'-'",
    "'*'",
    "'/'",
    "'('",
    "')'",
    "NUM",
}
```
How would you "look up" token names? In this example, `NUM` has the value `57346`, and the value of each of the symbols is effectively its UTF-8 value (`43`, `45`, `42`, `47`, `40`, `41`, respectively).

**Comment by bradfitz** [comment]
yacc was removed from Go in Go 1.8: https://beta.golang.org/doc/go1.8#tool_yacc
