### ISSUE TITLE
Misleading error message

### ISSUE THREAD

**Issue by fukanchik** [golang/go#65788]
### Go version

go version go1.18.1 linux/amd64

### Output of `go env` in your module/workspace:

```shell
I think go env doesn't matter
```

### What did you do?

Made a typo in a variable definition.

### What did you see happen?

Misleading error message 
```
./main.go:232:38: syntax error: unexpected status, expecting comma or )
```
At first I thought it was unexpected status within the compiler or somewhere else.

### What did you expect to see?

A message similar to what, for example, gcc produces:
```
x.c:3:5: error: ‘status’ undeclared (first use in this function)
```

something like:

```
./main.go:232:38: syntax error: unexpected ‘status‘, expecting comma or )
```

**Comment by seankhliao** [comment]
we no longer support 1.18

**Comment by fukanchik** [comment]
What happened? Why are you so fast in closing the tickets?! go version in the description is there because the field is mandatory.
This issue exists in _ALL_ versions of go.

**Comment by seankhliao** [comment]
in that case please show a reproducer for the issue on one of our supported versions of go.

**Comment by fukanchik** [comment]
Example which produces this in `master` branch:

```
package main

import (
        "fmt"
)

func main() {
        int status
        fmt.Println(status)
}
```

**Comment by seankhliao** [comment]
right, i've filed it as #65790
