### ISSUE TITLE
gofmt: Incorrect format for maps with unicode keys

### ISSUE THREAD

**Issue by CaledoniaProject** [golang/go#65784]
### Go version

go version go1.22.0 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
Not important
```

### What did you do?

I created a map with unicode keys

```
package main

import "fmt"

func main() {
    // Create a map to store the currency names and their corresponding ISO currency codes
    currencyMap := map[string]string{
        "美元":   "USD",
        "人民币":  "CNY",
        "加拿大元": "CAD",
        "巴西雷亚尔": "BRL",
        "欧元":   "EUR",
        "瑞士法郎": "CHF",
        "英镑":   "GBP",
        "澳大利亚元": "AUD",
        "港元":   "HKD",
        "墨西哥比索": "MXN",
        "马来西亚林吉特": "MYR",
        "台币":   "TWD",
        "哥伦比亚比索": "COP",
        "秘鲁新索尔": "PEN",
        "阿根廷比索": "ARS",
        "智利比索":  "CLP",
        "瑞典克朗":  "SEK",
        "以色列新谢克尔": "ILS",
        "新西兰元":  "NZD",
        "南非兰特":  "ZAR",
        "日元":   "JPY",
        "挪威克朗":  "NOK",
        "新加坡元":  "SGD",
        "丹麦克朗":  "DKK",
        "韩国元":   "KRW",
        "印度卢比":  "INR",
        "土耳其里拉": "TRY",
        "哈萨克斯坦坚戈": "KZT",
        "菲律宾比索":  "PHP",
        "印度尼西亚卢比": "IDR",
        "越南盾":   "VND",
    }

    // Print the map
    for currencyName, currencyCode := range currencyMap {
        fmt.Printf("%s: %s\n", currencyName, currencyCode)
    }
}
```

### What did you see happen?

gofmt/vscode is not formatting it correctly, there's extra spaces between the keys and the values. 

The non-unicode map structs has only one space between them, but the unicode ones have multiple spaces and not aligned correctly. It looks like a bug to me.

### What did you expect to see?

Same format as ascii keys

**Comment by CaledoniaProject** [comment]
See this screenshot

![image](https://github.com/golang/go/assets/1357701/7b159fe6-8939-4b90-a57c-fe6ae2f0c505)

**Comment by aimuz** [comment]
Try changing to an equal width font

**Comment by ALTree** [comment]
This is more or less unavoidable, see the discussion in #16170 for an explanation.

Closing here as not actionable.
