### ISSUE TITLE
gomobile can't  gobind on Xcode 15.2

### ISSUE THREAD

**Issue by QiuXiaochun** [golang/go#65807]
### Go version

go version go1.18.3 darwin/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/Users/xxx/go/bin"
GOCACHE="/Users/xxx/Library/Caches/go-build"
GOENV="/Users/xxx/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/yunwu01/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/yunwu01/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/xxx/Documents/Terminal/trunk/xxxx/src/go.mod"
GOWORK="/Users/xxx/Documents/Terminal/trunk/xxx/src/go.work"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xv/_xgjmw6s40sbzv25176gl8rr0000gn/T/go-build3728410003=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?

go get golang.org/x/mobile
GOARCH=arm64 gomobile bind -v -trimpath -ldflags "-s -w" -o build/iOS/xxxxx.xcframework -target=ios -iosversion=11.0 ./codeDir

### What did you see happen?

golang.org/x/mobile/internal/mobileinit
# github.com/mattn/go-sqlite3
sqlite3-binding.c:34903:8: warning: "gethostuuid() is disabled." [-W#warnings]
github.com/mattn/go-sqlite3
# golang.org/x/mobile/internal/mobileinit
cgo: malformed DWARF TagVariable entry
# golang.org/x/mobile/internal/mobileinit
cgo: malformed DWARF TagVariable entry
# golang.org/x/mobile/internal/mobileinit
cgo: malformed DWARF TagVariable entry
gomobile: iossimulator/amd64: go build -v -ldflags -s -w -trimpath -buildmode=c-archive -o /var/folders/xv/_xgjmw6s40sbzv25176gl8rr0000gn/T/gomobile-work-33144207/xxxx-iossimulator-amd64.a ./gobind failed: exit status 2

### What did you expect to see?

I want use gomobile biuld xcframework on Xcode 15.2 successfully

**Comment by seankhliao** [comment]
we don't support 1.18 anymore

**Comment by QiuXiaochun** [comment]
> we don't support 1.18 anymore
But I compile OK on Xcode 14.3, so is this my golang version low? Does it have nothing to do with the Xcode version? If I upgrade the golang version, will everything be fine
