### ISSUE TITLE
net: support TCP_KEEPIDLE, TCP_KEEPINTVL and TCP_KEEPCNT on newer Windows

### ISSUE THREAD

**Issue by panjf2000** [golang/go#65817]
In [CL 542275](https://go-review.googlesource.com/c/go/+/542275), the implementation on `Windows` has a few limitations:

- `TCP_KEEPCNT` is not supported.
- `TCP_KEEPIDLE` and `TCP_KEEPINTVL` cannot be set separately, they must be set together.

https://github.com/golang/go/blob/ff4e45fbc2ab7980087c0ae882a36803f6bc248f/src/net/tcpsock.go#L121-L127

These limitations come from [SIO_KEEPALIVE_VALS](https://learn.microsoft.com/en-us/windows/win32/winsock/sio-keepalive-vals) that is used for TCP keep-alive on `Windows` in `Go` currently. It's a relatively old `Winsock` API for setting up the TCP keep-alive mechanism. I've done some more in-depth research on `Windows` and realized that we can do more things on some relatively newer versions of `Windows` using `setsockopt` and `getsockopt`.

`TCP_KEEPIDLE` and `TCP_KEEPINTVL` are available starting with Windows 10, version 1709. `TCP_KEEPCNT` is available starting with Windows 10, version 1703. Therefore, we can reconcile the implementation on `Windows 10, version 1709` and later versions with the implementations on UNIX's.

Follows up #65809

## References
 
- [IPPROTO_TCP socket options](https://learn.microsoft.com/en-us/windows/win32/winsock/ipproto-tcp-socket-options)
- [TCP_KEEPINVTL and TCP_KEEPIDLE - Socket Keep Alives not working](https://cygwin.com/pipermail/cygwin/2020-June/245436.html)
- [Cygwin: tcp: Support TCP_KEEPIDLE, TCP_KEEPCNT, TCP_KEEPINTVL](https://sourceware.org/pipermail/cygwin-cvs/2020q3/014473.html)
- [Add cross-platform support for keep-alive socket options](https://github.com/dotnet/corefx/pull/29963/files)

**Comment by ianlancetaylor** [comment]
Can we put the new constants in internal/syscall/windows?

**Comment by panjf2000** [comment]
> Can we put the new constants in internal/syscall/windows?

If that is allowed, then it would make our work on this much easier, because we don't have to go through the proposal process.

**Comment by ianlancetaylor** [comment]
We can add anything we like to internal/syscall.

**Comment by qmuntal** [comment]
> Look like we will have to add some [new constants](https://ci.chromium.org/ui/p/golang/builders/try/gotip-linux-amd64/b8755549536945857489/test-results?q=ExactID%3Acmd%2Fapi%3Acheck.TestCheck+VHash%3A59d5ef073852df4a&clean=&sortby=&groupby=), so this issue might need to be bumped up to a proposal.

It seems to me that this issue can be implemented without adding new API surface. The new constants can live in `internal/syscall/windows`. Having them exported in `syscall` is just nice to have.

**Comment by panjf2000** [comment]
We've come to a consensus that this feature can be done without exposing any new constants, so taking this issue out of the `Proposal` process.
