### ISSUE TITLE
cmd/go: go build executes unnecessary mkdir 

### ISSUE THREAD

**Issue by davecheney** [golang/go#6583]
<pre>What steps will reproduce the problem?

% go build -x
WORK=/tmp/go-build249279931
mkdir -p $WORK/crypto/hmac/_obj/
mkdir -p $WORK/crypto/
cd /home/dfc/go/src/pkg/crypto/hmac
/home/dfc/go/pkg/tool/linux_arm/5g -o $WORK/crypto/hmac/_obj/_go_.5 -p crypto/hmac
-complete -D _/home/dfc/go/src/pkg/crypto/hmac -I $WORK ./hmac.go
/home/dfc/go/pkg/tool/linux_arm/pack grcP $WORK $WORK/crypto/hmac.a
$WORK/crypto/hmac/_obj/_go_.5

What is the expected output? What do you see instead?

mkdir -p $WORK/crypto/hmac/_obj/

will create $WORK/crypto/

so

mkdir -p $WORK/crypto/

is unnecessary.

Please use labels and text to provide additional information.</pre>

**Comment by rsc** [comment]
This doesn't matter; fixing it would make the code more fragile.
