### ISSUE TITLE
proposal: reader should able to get content's length

### ISSUE THREAD

**Issue by wondar-chan** [golang/go#65839]
### Go Programming Experience

Experienced

### Related Idea

- [ ] Has this idea, or one like it, been proposed before?
- [ ] Does this affect error handling?
- [ ] Is this about generics?
- [ ] Is this change backward compatible? Breaking the Go 1 compatibility guarantee is a large cost and requires a large benefit

### Has this idea, or one like it, been proposed before?

No

### Does this affect error handling?

No

### Is this about generics?

No

### Proposal

reader should able to get content's length, avoid using io.ReadAll, which read from Reader by range and append. When content is large, io.ReadAll will cost too many memories. 

### Language Spec Changes

Add a new method to io.Reader, like ContentLength, eg. 

### Is this change backward compatible?

No

**Comment by Zxilly** [comment]
Length is not always available.
