### ISSUE TITLE
x/build: timeout_scale parameter not applied on LUCI builders for x/ repos 

### ISSUE THREAD

**Issue by bcmills** [golang/go#65845]
### Go version

86a32d6d9c4b2da88cb97da91a15e1af9efc87f7

### Output of `go env` in your module/workspace:

```shell
N/A
```

### What did you do?

Read https://github.com/golang/go/issues/65820#issuecomment-1954975510.

### What did you see happen?

The logs linked from https://ci.chromium.org/ui/p/golang/builders/ci/x_tools-gotip-darwin-amd64-longtest/b8755859092256698353/overview appear to show `go test` commands run without setting the `-timeout` flag.

It appears that the LUCI configuration only uses the `timeout_scale` parameter to set the `GO_TEST_TIMEOUT_SCALE` environment variable, which is intended to be specific to `cmd/dist` and should have little to no effect on other commands.
(https://cs.opensource.google/go/x/build/+/luci-config:main.star;l=1206-1208;drc=c0163da662349fff6c2f585cebd08bbd836b8470)

### What did you expect to see?

A `-timeout` flag set according to the `timeout_scale` parameter of the builder, analogous to what happens on the legacy builders:
https://cs.opensource.google/go/x/build/+/master:cmd/coordinator/buildstatus.go;l=1187-1190;drc=498808697e0db626ec196a9a5290f5f121fa056a (issue #56968)

**Comment by bcmills** [comment]
It appears that the actual `go test` arguments are set in a separate binary here:
https://source.chromium.org/chromium/infra/infra/+/main:go/src/infra/experimental/golangbuild/buildspec.go;l=257-270;drc=06da4728c54588bb3068716c3f5cd51f04fc2d07

So I guess that's where the `-timeout` argument should be added too?

**Comment by mknyszek** [comment]
I believe this is now resolved. I verified on an x/tools longtest build that the `-timeout` flag is being passed as expected.
