### ISSUE TITLE
cmd/compile: Wrong line number in stack trace in this particular panic (from Go stdlib)

### ISSUE THREAD

**Issue by mitchellh** [golang/go#6586]
<pre>go version:
go version devel +4971493b0e14 Tue Oct 01 23:44:20 2013 -0400 darwin/amd64

the code:
<a href="https://gist.github.com/mitchellh/3883097d9d57fccbfb88">https://gist.github.com/mitchellh/3883097d9d57fccbfb88</a>

(the code actually works fine on play.golang.org, I'm not sure what changed in Go 1.2
but on 1.2 this panics)

The panic looks like this. If you look, the line number of `net.(*TCPConn).Close` is on
line 1 in dial.go. Is this working as intended? It made debugging this trickier.

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x35077]

goroutine 1 [running]:
runtime.panic(0x74e40, 0x114e19)
    /Users/mitchellh/go/src/pkg/runtime/panic.c:266 +0xb6
net.(*TCPConn).Close(0x0, 0x7b6a0, 0x117228)
    /Users/mitchellh/go/src/pkg/net/dial.go:1 +0x17
main.main()
    /tmp/test/test.go:10 +0x41
exit status 2</pre>

**Comment by ALTree** [comment]
> it would be better to say `<unknown>` or `<generated>` than to say dial.go:1.

1.9 compiler does that:

```
goroutine 1 [running]:
net.(*TCPConn).Close(0x0, 0xc42004df70, 0x48a224)
	<autogenerated>:1 +0x5
main.main()
	test.go:10 +0x2a
```

So this issue is fixed. Closing.
