### ISSUE TITLE
Go  C static libraries   .a

### ISSUE THREAD

**Issue by wangqingpen** [golang/go#65865]
### Go version

go version go1.20.4 linux/arm64

### Output of `go env` in your module/workspace:

```shell
go version go1.20.4 linux/arm64
root@linaro-alip:/home/edgex/device-dlt698.45-go1# go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS="-buildvcs=false"
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=".gitlab.com,.gitee.com"
GONOSUMDB=".gitlab.com,.gitee.com"
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=".gitlab.com,.gitee.com"
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm64"
GOVCS=""
GOVERSION="go1.20.4"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
GOMOD="/home/edgex/device-dlt698.45-go1/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3513262744=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

When the go language is compiled, when the .a static library of the C language is linked, it cannot be compiled, and the makefile used for compilation is as follows:

.PHONY: build test clean docker

#export GODEBUG=cgocheck=0

GO=CGO_ENABLED=1 GO111MODULE=on  GOOS=linux GOARCH=arm64 GOPROXY=https://goproxy.io,direct go
#GOCGO=CGO_ENABLED=1 GO111MODULE=on GOPROXY=https://goproxy.cn,direct go

MICROSERVICES=cmd/device-dlt698.45-go
.PHONY: $(MICROSERVICES)

VERSION=$(shell cat ./VERSION 2>/dev/null || echo 0.0.0)
DOCKER_TAG=$(VERSION)-dev

CGO_CFLAGS=-I/home/edgex/device-dlt698.45-go1/lib/ -fpic
#CGO_LDFLAGS=-Llib -l698_45
CGO_LDFLAGS=-L/home/edgex/device-dlt698.45-go1/lib/ -l698_45 -fpic
#GOFLAGS=-ldflags "-s -w -linkmode 'external' -extldflags '-static"
GOFLAGS=-ldflags "-w -s -linkmode 'external' -extldflags '-static -fpic'"

GOTESTFLAGS?=-race

GIT_SHA=$(shell git rev-parse HEAD)
#NO_ZMQ_GO_BUILD_TAG:=no_zmq
build: $(MICROSERVICES) -lm

	$(CC=musl-gcc) $(GO) install -tags=safe
 
cmd/device-dlt698.45-go:
  
	$(CC=musl-gcc) $(GO) build $(GOFLAGS) -o $@ ./cmd/device-dlt698.45-go

### What did you see happen?

err:
/usr/local/go/pkg/tool/linux_arm64/link: running gcc failed: exit status 1
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-ipc_listener.o): in function `zmq::ipc_listener_t::filter(int)':
/home/test/zeromq-4.3.2/src/ipc_listener.cpp:307: 警告：Using 'getgrgid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /home/test/zeromq-4.3.2/src/ipc_listener.cpp:302: 警告：Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-1426863287/000021.o: in function `_cgo_cbcce81e6342_C2func_getaddrinfo':
/tmp/go-build/cgo-gcc-prolog:58: 警告：Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-mailbox_safe.o): in function `zmq::mailbox_safe_t::~mailbox_safe_t()':
/usr/include/c++/8/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-mailbox_safe.o): in function `zmq::mailbox_safe_t::~mailbox_safe_t()':
/usr/include/c++/8/condition_variable:234: undefined reference to `std::condition_variable::~condition_variable()'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-mailbox_safe.o): in function `zmq::mailbox_safe_t::~mailbox_safe_t()':
/home/test/zeromq-4.3.2/src/mailbox_safe.cpp:54: undefined reference to `operator delete(void*, unsigned long)'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-mailbox_safe.o): in function `zmq::mailbox_safe_t::send(zmq::command_t const&)':
/usr/include/c++/8/condition_variable:250: undefined reference to `std::condition_variable::notify_all()'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-mailbox_safe.o): in function `zmq::mailbox_safe_t::send(zmq::command_t const&)':
/usr/include/c++/8/bits/std_mutex.h:107: undefined reference to `std::__throw_system_error(int)'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-mailbox_safe.o): in function `zmq::mailbox_safe_t::recv(zmq::command_t*, int)':
/usr/include/c++/8/condition_variable:305: undefined reference to `std::chrono::_V2::system_clock::now()'
/usr/bin/ld: /usr/include/c++/8/condition_variable:181: undefined reference to `std::chrono::_V2::system_clock::now()'
/usr/bin/ld: /usr/include/c++/8/condition_variable:213: undefined reference to `std::uncaught_exception()'
/usr/bin/ld: /usr/include/c++/8/condition_variable:263: undefined reference to `std::condition_variable::wait(std::unique_lock<std::mutex>&)'
/usr/bin/ld: /usr/include/c++/8/condition_variable:213: undefined reference to `std::uncaught_exception()'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-mailbox_safe.o): in function `zmq::mailbox_safe_t::recv(zmq::command_t*, int)':
/usr/include/c++/8/bits/std_mutex.h:107: undefined reference to `std::__throw_system_error(int)'
/usr/bin/ld: /usr/include/c++/8/bits/std_mutex.h:262: undefined reference to `std::__throw_system_error(int)'
/usr/bin/ld: /usr/include/c++/8/bits/std_mutex.h:107: undefined reference to `std::__throw_system_error(int)'
/usr/bin/ld: /usr/include/c++/8/bits/std_mutex.h:262: undefined reference to `std::__throw_system_error(int)'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-mailbox_safe.o): in function `zmq::mailbox_safe_t::recv(zmq::command_t*, int)':
/usr/include/c++/8/condition_variable:217: undefined reference to `__cxa_begin_catch'
/usr/bin/ld: /usr/include/c++/8/condition_variable:218: undefined reference to `__cxa_rethrow'
/usr/bin/ld: /usr/include/c++/8/condition_variable:219: undefined reference to `__cxa_begin_catch'
/usr/bin/ld: /usr/include/c++/8/condition_variable:219: undefined reference to `__cxa_end_catch'
/usr/bin/ld: /usr/include/c++/8/condition_variable:217: undefined reference to `__cxa_begin_catch'
/usr/bin/ld: /usr/include/c++/8/condition_variable:218: undefined reference to `__cxa_rethrow'
/usr/bin/ld: /usr/include/c++/8/condition_variable:217: undefined reference to `__cxa_end_catch'
/usr/bin/ld: /usr/include/c++/8/condition_variable:219: undefined reference to `__cxa_begin_catch'
/usr/bin/ld: /usr/include/c++/8/condition_variable:219: undefined reference to `__cxa_end_catch'
/usr/bin/ld: /usr/include/c++/8/condition_variable:217: undefined reference to `__cxa_end_catch'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-mailbox_safe.o): in function `zmq::mailbox_safe_t::mailbox_safe_t(zmq::mutex_t*)':
/usr/include/c++/8/condition_variable:233: undefined reference to `std::condition_variable::condition_variable()'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-mailbox_safe.o): in function `zmq::mailbox_safe_t::mailbox_safe_t(zmq::mutex_t*)':
/usr/include/c++/8/ext/new_allocator.h:111: undefined reference to `operator new(unsigned long)'
/usr/bin/ld: /usr/include/c++/8/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-mailbox_safe.o): in function `zmq::mailbox_safe_t::mailbox_safe_t(zmq::mutex_t*)':
/usr/include/c++/8/condition_variable:233: undefined reference to `std::condition_variable::~condition_variable()'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-mailbox_safe.o): in function `std::_Sp_counted_ptr_inplace<std::mutex, std::allocator<std::mutex>, (__gnu_cxx::_Lock_policy)2>::~_Sp_counted_ptr_inplace()':
/usr/include/c++/8/bits/shared_ptr_base.h:549: undefined reference to `operator delete(void*, unsigned long)'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-mailbox_safe.o): in function `std::_Sp_counted_ptr_inplace<std::mutex, std::allocator<std::mutex>, (__gnu_cxx::_Lock_policy)2>::_M_destroy()':
/usr/include/c++/8/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-mailbox_safe.o): in function `std::unique_lock<std::mutex>::unlock() [clone .isra.18]':
/usr/include/c++/8/bits/std_mutex.h:320: undefined reference to `std::__throw_system_error(int)'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-mailbox_safe.o): in function `std::_V2::condition_variable_any::~condition_variable_any()':
/usr/include/c++/8/condition_variable:234: undefined reference to `std::condition_variable::~condition_variable()'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-mailbox_safe.o): in function `std::_V2::condition_variable_any::_Unlock<zmq::mutex_t>::~_Unlock()':
/usr/include/c++/8/condition_variable:213: undefined reference to `std::uncaught_exception()'
/usr/bin/ld: /usr/include/c++/8/condition_variable:217: undefined reference to `__cxa_begin_catch'
/usr/bin/ld: /usr/include/c++/8/condition_variable:218: undefined reference to `__cxa_rethrow'
/usr/bin/ld: /usr/include/c++/8/condition_variable:219: undefined reference to `__cxa_begin_catch'
/usr/bin/ld: /usr/include/c++/8/condition_variable:219: undefined reference to `__cxa_end_catch'
/usr/bin/ld: /usr/include/c++/8/condition_variable:217: undefined reference to `__cxa_end_catch'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-mailbox_safe.o): in function `void std::vector<zmq::signaler_t*, std::allocator<zmq::signaler_t*> >::_M_realloc_insert<zmq::signaler_t* const&>(__gnu_cxx::__normal_iterator<zmq::signaler_t**, std::vector<zmq::signaler_t*, std::allocator<zmq::signaler_t*> > >, zmq::signaler_t* const&)':
/usr/include/c++/8/ext/new_allocator.h:111: undefined reference to `operator new(unsigned long)'
/usr/bin/ld: /usr/include/c++/8/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-mailbox_safe.o):(.data.rel.ro._ZTISt11_Mutex_baseILN9__gnu_cxx12_Lock_policyE2EE[_ZTISt11_Mutex_baseILN9__gnu_cxx12_Lock_policyE2EE]+0x0): undefined reference to `vtable for __cxxabiv1::__class_type_info'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-mailbox_safe.o):(.data.rel.ro._ZTISt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE[_ZTISt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-mailbox_safe.o):(.data.rel.ro._ZTIN3zmq14mailbox_safe_tE[_ZTIN3zmq14mailbox_safe_tE]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-mailbox_safe.o):(.data.rel.ro._ZTISt23_Sp_counted_ptr_inplaceISt5mutexSaIS0_ELN9__gnu_cxx12_Lock_policyE2EE[_ZTISt23_Sp_counted_ptr_inplaceISt5mutexSaIS0_ELN9__gnu_cxx12_Lock_policyE2EE]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-mailbox_safe.o):(.data.rel.local.DW.ref._ZTIN10__cxxabiv115__forced_unwindE[DW.ref._ZTIN10__cxxabiv115__forced_unwindE]+0x0): undefined reference to `typeinfo for __cxxabiv1::__forced_unwind'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-ctx.o): in function `zmq::thread_ctx_t::thread_ctx_t()':
/home/test/zeromq-4.3.2/src/mutex.hpp:120: undefined reference to `pthread_mutexattr_init'
/usr/bin/ld: /home/test/zeromq-4.3.2/src/mutex.hpp:123: undefined reference to `pthread_mutexattr_settype'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-ctx.o): in function `zmq::thread_ctx_t::set(int, int)':
/usr/include/c++/8/bits/basic_ios.h:462: undefined reference to `vtable for std::basic_ios<char, std::char_traits<char> >'
/usr/bin/ld: /usr/include/c++/8/bits/basic_ios.h:462: undefined reference to `std::ios_base::ios_base()'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-ctx.o): in function `zmq::thread_ctx_t::set(int, int)':
/usr/include/c++/8/ostream:385: undefined reference to `VTT for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >'
/usr/bin/ld: /usr/include/c++/8/ostream:385: undefined reference to `VTT for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-ctx.o): in function `zmq::thread_ctx_t::set(int, int)':
/usr/include/c++/8/bits/basic_ios.h:462: undefined reference to `vtable for std::basic_ios<char, std::char_traits<char> >'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-ctx.o): in function `zmq::thread_ctx_t::set(int, int)':
/usr/include/c++/8/ostream:385: undefined reference to `std::basic_ios<char, std::char_traits<char> >::init(std::basic_streambuf<char, std::char_traits<char> >*)'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-ctx.o): in function `zmq::thread_ctx_t::set(int, int)':
/usr/include/c++/8/sstream:562: undefined reference to `vtable for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-ctx.o): in function `zmq::thread_ctx_t::set(int, int)':
/usr/include/c++/8/streambuf:473: undefined reference to `vtable for std::basic_streambuf<char, std::char_traits<char> >'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-ctx.o): in function `zmq::thread_ctx_t::set(int, int)':
/usr/include/c++/8/sstream:562: undefined reference to `vtable for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >'
/usr/bin/ld: /usr/include/c++/8/sstream:101: undefined reference to `vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-ctx.o): in function `zmq::thread_ctx_t::set(int, int)':
/usr/include/c++/8/streambuf:473: undefined reference to `vtable for std::basic_streambuf<char, std::char_traits<char> >'
/usr/bin/ld: /usr/include/c++/8/streambuf:473: undefined reference to `std::locale::locale()'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-ctx.o): in function `zmq::thread_ctx_t::set(int, int)':
/usr/include/c++/8/sstream:101: undefined reference to `vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >'
/usr/bin/ld: /usr/include/c++/8/sstream:563: undefined reference to `std::basic_ios<char, std::char_traits<char> >::init(std::basic_streambuf<char, std::char_traits<char> >*)'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-ctx.o): in function `zmq::thread_ctx_t::set(int, int)':
/home/test/zeromq-4.3.2/src/ctx.cpp:453: undefined reference to `std::ostream::operator<<(int)'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-ctx.o): in function `zmq::thread_ctx_t::set(int, int)':
/usr/include/c++/8/bits/basic_string.h:1932: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-ctx.o): in function `zmq::thread_ctx_t::set(int, int)':
/usr/include/c++/8/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-ctx.o): in function `zmq::thread_ctx_t::set(int, int)':
/usr/include/c++/8/sstream:591: undefined reference to `vtable for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >'
/usr/bin/ld: /usr/include/c++/8/sstream:65: undefined reference to `vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-ctx.o): in function `zmq::thread_ctx_t::set(int, int)':
/usr/include/c++/8/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-ctx.o): in function `zmq::thread_ctx_t::set(int, int)':
/usr/include/c++/8/streambuf:205: undefined reference to `vtable for std::basic_streambuf<char, std::char_traits<char> >'
/usr/bin/ld: /usr/include/c++/8/streambuf:205: undefined reference to `std::locale::~locale()'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-ctx.o): in function `zmq::thread_ctx_t::set(int, int)':
/usr/include/c++/8/bits/basic_ios.h:282: undefined reference to `vtable for std::basic_ios<char, std::char_traits<char> >'
/usr/bin/ld: /usr/include/c++/8/bits/basic_ios.h:282: undefined reference to `std::ios_base::~ios_base()'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-ctx.o): in function `zmq::thread_ctx_t::set(int, int)':
/usr/include/c++/8/bits/basic_string.h:1932: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)'
/usr/bin/ld: /usr/include/c++/8/bits/basic_string.h:1366: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-ctx.o): in function `zmq::thread_ctx_t::set(int, int)':
/home/test/zeromq-4.3.2/src/ctx.cpp:452: undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_ostringstream()'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-ctx.o): in function `zmq::thread_ctx_t::set(int, int)':
/usr/include/c++/8/bits/basic_ios.h:282: undefined reference to `vtable for std::basic_ios<char, std::char_traits<char> >'
/usr/bin/ld: /usr/include/c++/8/bits/basic_ios.h:282: undefined reference to `std::ios_base::~ios_base()'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-ctx.o): in function `zmq::thread_ctx_t::set(int, int)':
/usr/include/c++/8/sstream:65: undefined reference to `vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-ctx.o): in function `zmq::thread_ctx_t::set(int, int)':
/usr/include/c++/8/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-ctx.o): in function `zmq::thread_ctx_t::set(int, int)':
/usr/include/c++/8/streambuf:205: undefined reference to `vtable for std::basic_streambuf<char, std::char_traits<char> >'
/usr/bin/ld: /usr/include/c++/8/streambuf:205: undefined reference to `std::locale::~locale()'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-ctx.o): in function `zmq::thread_ctx_t::set(int, int)':
/usr/include/c++/8/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-ctx.o): in function `zmq::ctx_t::start()':
/home/test/zeromq-4.3.2/src/ctx.cpp:303: undefined reference to `std::nothrow'
/usr/bin/ld: /home/test/zeromq-4.3.2/src/ctx.cpp:303: undefined reference to `std::nothrow'
/usr/bin/ld: /home/test/zeromq-4.3.2/src/ctx.cpp:303: undefined reference to `operator new(unsigned long, std::nothrow_t const&)'
/usr/bin/ld: /home/test/zeromq-4.3.2/src/ctx.cpp:318: undefined reference to `std::nothrow'
/usr/bin/ld: /home/test/zeromq-4.3.2/src/ctx.cpp:318: undefined reference to `operator new(unsigned long, std::nothrow_t const&)'
/usr/bin/ld: /home/test/zeromq-4.3.2/src/ctx.cpp:303: undefined reference to `std::nothrow'
/usr/bin/ld: /home/test/zeromq-4.3.2/src/ctx.cpp:303: undefined reference to `std::nothrow'
/usr/bin/ld: /home/test/zeromq-4.3.2/src/ctx.cpp:303: undefined reference to `operator new(unsigned long, std::nothrow_t const&)'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-ctx.o): in function `zmq::ctx_t::start()':
/usr/include/c++/8/ext/new_allocator.h:111: undefined reference to `operator new(unsigned long)'
/usr/bin/ld: /usr/include/c++/8/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/usr/bin/ld: /usr/include/c++/8/ext/new_allocator.h:111: undefined reference to `operator new(unsigned long)'
/usr/bin/ld: /usr/include/c++/8/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-ctx.o): in function `zmq::ctx_t::start()':
/usr/include/c++/8/bits/vector.tcc:70: undefined reference to `std::__throw_length_error(char const*)'
/usr/bin/ld: /usr/include/c++/8/bits/vector.tcc:70: undefined reference to `std::__throw_length_error(char const*)'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-ctx.o): in function `zmq::ctx_t::start()':
/home/test/zeromq-4.3.2/src/ctx.cpp:303: undefined reference to `std::nothrow'
/usr/bin/ld: /home/test/zeromq-4.3.2/src/ctx.cpp:303: undefined reference to `operator delete(void*, std::nothrow_t const&)'
/usr/bin/ld: /home/test/zeromq-4.3.2/src/ctx.cpp:293: undefined reference to `__cxa_begin_catch'
/usr/bin/ld: /home/test/zeromq-4.3.2/src/ctx.cpp:293: undefined reference to `__cxa_end_catch'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-ctx.o): in function `zmq::ctx_t::unregister_endpoints(zmq::socket_base_t*)':
/home/test/zeromq-4.3.2/src/ctx.cpp:546: undefined reference to `std::_Rb_tree_increment(std::_Rb_tree_node_base*)'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-ctx.o): in function `zmq::ctx_t::connect_pending(char const*, zmq::socket_base_t*)':
/usr/include/c++/8/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/usr/bin/ld: /usr/include/c++/8/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-ctx.o): in function `zmq::ctx_t::connect_pending(char const*, zmq::socket_base_t*)':
/usr/include/c++/8/bits/stl_tree.h:287: undefined reference to `std::_Rb_tree_increment(std::_Rb_tree_node_base*)'
/usr/bin/ld: /usr/include/c++/8/bits/stl_tree.h:374: undefined reference to `std::_Rb_tree_increment(std::_Rb_tree_node_base const*)'
/usr/bin/ld: /usr/include/c++/8/bits/stl_tree.h:2491: undefined reference to `std::_Rb_tree_rebalance_for_erase(std::_Rb_tree_node_base*, std::_Rb_tree_node_base&)'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-ctx.o): in function `zmq::ctx_t::connect_pending(char const*, zmq::socket_base_t*)':
/usr/include/c++/8/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/usr/bin/ld: /usr/include/c++/8/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/usr/bin/ld: /usr/include/c++/8/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/usr/bin/ld: /usr/include/c++/8/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/usr/bin/ld: /usr/include/c++/8/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-ctx.o):/usr/include/c++/8/ext/new_allocator.h:125: more undefined references to `operator delete(void*)' follow
/usr/bin/ld: /usr/local/lib/libzmq.a(libzmq_la-ctx.o): in function `zmq::ctx_t::find_endpoint(char const*)':
/usr/include/c++/8/ext/new_allocator.h:111: undefined reference to `operator new(unsigned long)'

collect2: error: ld returned 1 exit status

### What did you expect to see?

Can you give a workaround

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
