### ISSUE TITLE
提案: 错误处理，避免不必要的 err != nil

### ISSUE THREAD

**Issue by lvan100** [golang/go#65875]
从 rust 取得灵感，引入 err!! 操作，等价于 if err != nil { return } ，这个改进是微小的，向后兼容的。

修改前:

func add(a,b string) (int,error) {
    ia,err :=strconv.atoi(a)
    if err != nil { return }
    ib,err :=strconv.atoi(b)
    if err != nil { return }
    return ia+ib, nil
}

修改后:

func add(a,b string) (int,error) {
    ia,err!! := strconv.atoi(a)
    ib,err!! := strconv.atoi(b)
    return ia+ib,nil
}

得益于 go 的返回值可命名，return 可以不仅仅返回默认值，例子我就不写了。

**Comment by seankhliao** [comment]
see previously rejected proposals such as #63380 #14066 #36390 #60779 #62253
