### ISSUE TITLE
cmd/go: go install does not provide vcs.revision buildinfo

### ISSUE THREAD

**Issue by AlexanderYastrebov** [golang/go#65904]
### Go version

go version go1.22.0 linux/amd64

### Output of `go env` in your module/workspace:

```shell
-
```

### What did you do?

Added a snippet to read vcs.revision setting from `debug.ReadBuildInfo()`
https://github.com/zalando/skipper/pull/2954
and installed the binary:
```
~$ rm $(which skipper)
~$ go install github.com/zalando/skipper/cmd/skipper@latest
```

### What did you see happen?

version output contains proper version (`info.Main.Version`) but empty commit (`vcs.revision`)
```
~$ skipper -version
Skipper version v0.21.3 (commit: , runtime: go1.22.0)
```

### What did you expect to see?

non-empty commit https://github.com/zalando/skipper/commit/8c03dfbd63fe11abee0c41fbc63d4dc248ed7d06
```
~$ skipper -version
Skipper version v0.21.3 (commit: 8c03dfbd, runtime: go1.22.0)
```

**Comment by seankhliao** [comment]
I believe this is working as intended?
when a module is obtained from the module proxy, there's no association with any git commit, only the version it matched, so there's no data to populate it from.

**Comment by AlexanderYastrebov** [comment]
Do I get it right that `Main.Version` and `vcs.revision` are mutually exclusive - build info for `go install` provides `Main.Version` but not `vcs.revision` while `go build` does not provide `Main.Version` (it uses stub `(devel)`, https://github.com/golang/go/issues/50603 seems related) but provides `vcs.revision`:
```
$ go build -o bin/skipper ./cmd/skipper && ./bin/skipper -version
Skipper version (devel) (commit: 8c03dfbd, runtime: go1.22.0)
```

**Comment by AlexanderYastrebov** [comment]
@seankhliao Thank you for the prompt response and clarification.
