### ISSUE TITLE
fmt: refers to the empty interface by the longer, older "interface {}" name instead of the shorter, newer "any"

### ISSUE THREAD

**Issue by dmitshur** [golang/go#65912]
### Go version

go version go1.22.0 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
N/A
```

### What did you do?

I used fmt's `%#v` to print a value whose type involves the empty interface in a module that declares Go version 1.22.0.

```Go
fmt.Printf("value of []any{1, 2} is %#v\n", []any{1, 2})
```

https://go.dev/play/p/pByHBo9Vs03

### What did you see happen?

```
value of []any{1, 2} is []interface {}{1, 2}
```

### What did you expect to see?

Go 1.18 added the predeclared type any as an alias for the empty interface.

It might be an enhancement if `fmt` were to take advantage of it, and print:

```
value of []any{1, 2} is []any{1, 2}
```

CC @robpike, @martisch.

**Comment by cherrymui** [comment]
`any` is defined as an alias to `interface{}`. We print the `byte` type as the unaliased `uint8`, so we probably should print `any` as the unaliased `interface{}` as well.

**Comment by cherrymui** [comment]
Well, for `byte`, when printing the type (`%T`) it prints `uint8`, but when printing value (`%#v`) it prints `byte`. For `rune` we print `int32` for both. https://go.dev/play/p/yttrKyuyZrP . That seems inconsistent.

**Comment by robpike** [comment]
I wouldn't change this.  It's clear and also has the potential to break a lot of golden files.

**Comment by dmitshur** [comment]
It sounds like this is okay to leave as is then. If in the future this change (possibly bundled with others like it) gets a higher benefit-to-cost ratio, a new issue can be filed (referencing this one). Thanks for considering it.
