### ISSUE TITLE
net/http: wasi deadlock

### ISSUE THREAD

**Issue by arejula27** [golang/go#65928]
### Go version

go version go1.21.7 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/arejula27/.cache/go-build'
GOENV='/home/arejula27/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/arejula27/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/arejula27/go'
GOPRIVATE=''
GOPROXY='direct'
GOROOT='/usr/lib/golang'
GOSUMDB='off'
GOTMPDIR=''
GOTOOLCHAIN='local'
GOTOOLDIR='/usr/lib/golang/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.7'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/arejula27/workspaces/go-lab/echo/go.mod'
GOWORK='/home/arejula27/workspaces/go-lab/go.work'
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2105186211=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

I compiled simple web servers using `GOOS=wasip1 GOARCH=wasm` and try to run it.
![image](https://github.com/golang/go/assets/46299278/6027e122-df50-483f-a2df-c8a177a10350)

### What did you see happen?

The program crash because it detects a deadclock

### What did you expect to see?

To run correctly

**Comment by panjf2000** [comment]
Did you run this example in the expected environment: `GOOS=wasip1 GOARCH=wasm`?

**Comment by panjf2000** [comment]
And it reproduces constantly?

**Comment by AndrusGerman** [comment]
Exactly the same problem in Windows.

**Comment by odeke-em** [comment]
Kindly cc-ing @neelance

**Comment by mauri870** [comment]
I believe the wasip1 port does not support creating sockets, so you can't really have http servers with it.

An excerpt from the [WASI blog post](https://go.dev/blog/wasi#limitations):

> A notable missing feature in the wasip1 API is a full implementation of network sockets. wasip1 only defines functions that operate on already opened sockets, making it impossible to support some of the most popular features of the Go standard library, such as HTTP servers. Hosts like Wasmer and WasmEdge implement extensions to the wasip1 API, allowing the opening of network sockets. While these extensions are not implemented by the Go compiler, there exists a third party library, [github.com/stealthrocket/net](https://github.com/stealthrocket/net), which uses go:wasmimport to allow the use of net.Dial and net.Listen on supported Wasm hosts. This enables the creation of net/http servers and other network related functionality when using this package.

**Comment by bcmills** [comment]
In particular, the `wasip1/wasm` port uses a fake network stack that can only accept other connections from the same process. If there are no other goroutines in the same process that can dial a connection, then the program is indeed deadlocked.

**Comment by bcmills** [comment]
@AndrusGerman
> Exactly the same problem in Windows.

Go's Windows networking stack is pretty much completely separate from the fake `wasm` net stack. If you are seeing a problem on Windows, please file a new issue and fill out the issue template.

**Comment by Malix-off** [comment]
See https://github.com/WebAssembly/WASI/tree/main/preview2#wasi-preview-2-contents

And specifically
- https://github.com/WebAssembly/wasi-http
- https://github.com/WebAssembly/wasi-sockets

**Comment by seankhliao** [comment]
Closing this as sockets aren't supported for wasi

**Comment by Malix-off** [comment]
> sockets aren't supported for wasi

[yet*](https://github.com/golang/go/issues/65928#issuecomment-1964491986) indeed;
Better to close as not planned for now
