### ISSUE TITLE
access: Requesting Try-Bots Access and Self-Assign Github Issues

### ISSUE THREAD

**Issue by raghvenders** [golang/go#65936]
Hello,

Per https://github.com/golang/go/wiki/GithubAccess I'd like to request Try-Bots Access and self-Assign Github issues. I have already raised a request on this (https://github.com/golang/go/issues/64523) and have been advised on wait time. I am re-requesting the access.

gerrit account: [raghvenders@gmail.com](https://go-review.googlesource.com/q/author:raghvenders@gmail.com)
github account: [raghvenders](https://github.com/raghvenders)

Thank you!

**Comment by mauri870** [comment]
cc @golang/release

**Comment by dmitshur** [comment]
Hi @raghvenders, thanks for your contributions to Go so far.

We discussed this request. We generally look for contributors to have a more established track record of contributions before considering granting trybot access, and it doesn't seem enough time has passed for that to happen yet. You should feel free to request someone else on the CL to run trybots when needed in the meantime. Thanks again.

I have sent you an invite to the go-assignees group (https://go.dev/wiki/GithubAccess#assignees).
