### ISSUE TITLE
codereview: submitting undo closes original issue again

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#6594]
<pre>Undoing a submit should reopen the issue being fixed, Not close it again. For example,
see <a href="https://golang.org/issue/6417?c=24">https://golang.org/issue/6417?c=24</a>. I do not know, if we can do
something about it, so leaving it for others to decide what to do about it.

Alex</pre>

**Comment by josharian** [comment]
GitHub has no syntax for re-opening issues from commit messages, so I don't think there's anything we can do. Closing.
