### ISSUE TITLE
runtime/cgo: build failing with `error: unknown warning group '-Watomic-alignment'` on `ios-arm64-corellium`

### ISSUE THREAD

**Issue by bcmills** [golang/go#65971]
### Go version

24070cf747d8b3f4487f1ca7247dcdf0ac266e8c

### Output of `go env` in your module/workspace:

```shell
N/A
```

### What did you do?

https://build.golang.org/log/85f674e744e8c08473b66ecef4d68f044f187e50

### What did you see happen?

```
Building Go cmd/dist using /var/root/go-ios-arm64-bootstrap. (go1.20.6 ios/arm64)
Building Go toolchain1 using /var/root/go-ios-arm64-bootstrap.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
warning: unable to find runtime/cgo.a
Building Go toolchain2 using go_bootstrap and Go toolchain1.
# runtime/cgo
gcc_libinit.c:11:32: error: unknown warning group '-Watomic-alignment', ignored [-Werror,-Wunknown-warning-option]
go tool dist: FAILED: /tmp/workdir-host-ios-arm64-corellium-ios/go/pkg/tool/ios_arm64/go_bootstrap install -pgo=off cmd/asm cmd/cgo cmd/compile cmd/link: exit status 1
```

### What did you expect to see?

All build steps succeeded and tests passing.

It appears that this flag was added in https://go.dev/cl/562348, for #65290 (attn @mauri870 @ianlancetaylor).

(attn @golang/ios)

**Comment by bcmills** [comment]
It isn't clear to me whether this problem is actually specific to `ios`, or more generally applicable but depending on a specific range of C compiler versions.

**Comment by mauri870** [comment]
I wonder if this is related to the clang that comes with xcode.

Maybe this approach works:

```c
#if !defined(__has_warning) || __has_warning("-Watomic-alignment")
#pragma GCC diagnostic ignored "-Watomic-alignment"
#endif
```
