### ISSUE TITLE
dist: add binary download for cross compilation

### ISSUE THREAD

**Issue by adg** [golang/go#6597]
<pre>A recent post to the mailing list:
<a href="https://groups.google.com/d/msg/golang-nuts/oFIs6Puj0_Q/0_seVYRtOyYJ">https://groups.google.com/d/msg/golang-nuts/oFIs6Puj0_Q/0_seVYRtOyYJ</a>
suggests we include binary downloads of a cross-compiled toolchain.

It's relatively easy to do, and would benefit people who run build farms. Probably we
should only offer it for the most popular platforms (darwin/linux/windows amd64 only).</pre>

**Comment by dominikh** [comment]
Is this still relevant, now that Go cross compilation works without having to do anything special?

**Comment by bradfitz** [comment]
Probably not relevant. Most of this bug has been discussing `os/user` not working without `cgo`, but that was fixed in #14626 too.

Closing.
