### ISSUE TITLE
fatal error: gcmarknewobject called while doing checkmark

### ISSUE THREAD

**Issue by ytc1012** [golang/go#65988]
### Go version

go version go1.22.0 windows/amd64

### Output of `go env` in your module/workspace:

```shell
set GO111MODULE=auto
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\1\AppData\Local\go-build
set GOENV=C:\Users\1\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\go-path\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\go-path;D:\server-catch-fish;D:\go_work
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:/Program Files/Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\1\AppData\Local\Temp\go-build3204000475
=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

nothing

### What did you see happen?

fatal error: gcmarknewobject called while doing checkmark

goroutine 44247253 gp=0xc000d9bdc0 m=11 mp=0xc0005a5808 [running]:
runtime.throw({0xdb0dd3?, 0xc001f9f8b8?})
	C:/Program Files/Go/src/runtime/panic.go:1023 +0x5c fp=0xc00227b4b8 sp=0xc00227b488 pc=0x439a3c
runtime.gcmarknewobject(0x4120f0?, 0xc001a4e490?)
	C:/Program Files/Go/src/runtime/mgcmark.go:1723 +0xf6 fp=0xc00227b4d8 sp=0xc00227b4b8 pc=0x422436
runtime.mallocgc(0x28, 0xcac5e0, 0x1)
	C:/Program Files/Go/src/runtime/malloc.go:1224 +0x6c5 fp=0xc00227b560 sp=0xc00227b4d8 pc=0x40e7a5
runtime.newobject(0x0?)
	C:/Program Files/Go/src/runtime/malloc.go:1390 +0x25 fp=0xc00227b588 sp=0xc00227b560 pc=0x40eb25

### What did you expect to see?

nothing

**Comment by seankhliao** [comment]
you can't have done nothing, how do we reproduce the issue?

**Comment by ytc1012** [comment]
This is an issue with the game service in our production environment, and I don't know what was done at that time. By checking the logs, I didn't find any abnormal operations. It has occurred twice so far. Since the 1.19 version upgrade, # 65867 has appeared twice. This issue has never occurred before
