### ISSUE TITLE
text/template: template.New(name).ParseFiles(file) not behaving as expected

### ISSUE THREAD

**Issue by udf2457** [golang/go#65996]
### Go version

1.22

### Output of `go env` in your module/workspace:

```shell
Not applicable for this
```

### What did you do?

```go
t, err := template.New(name).ParseFiles(file)
if err != nil {
  log.Error("failed to load template", "err", err.Error())
  os.Exit(1)
}
```

then elsewhere ...

```go
t.Execute(...)
````

### What did you see happen?

On `Execute()` an error was raised:

`name: \"name\" is an incomplete or empty template"`

### What did you expect to see?

`Execute()` should execute as expected.

Instead, I had to change `template.New(name).ParseFiles(file)` to `template.ParseFiles(file)`

I therefore suggest:

1. The preferred option would be chaining `template.New(name).ParseFiles(file)` works, as reasonably expected
2. It errors out if chained

The present situation is unacceptable because you do not discover the problem until `Execute()` time and when you do, the error message is not helpful in diagnosing the cause.

**Comment by AlexanderYastrebov** [comment]
It works when name == file (`, err := template.New("test.tmpl").ParseFiles("test.tmpl")`) and fails when not (`, err := template.New("test").ParseFiles("test.tmpl")`)

**Comment by AlexanderYastrebov** [comment]
See previous https://github.com/golang/go/issues/11247

**Comment by AlexanderYastrebov** [comment]
Since this works (as documented):
```go
func main() {
	t, err := template.New("whatever").ParseFiles("test.tmpl")
	if err != nil {
		log.Fatalf("Failed to load template: %v", err)
	}

	err = t.ExecuteTemplate(os.Stdout, "test.tmpl", nil)
	if err != nil {
		log.Fatalf("Failed to execute template: %v", err)
	}
}
```
it might be impossible to change the behaviour of `template.New("foo").ParseFiles("bar")` to return error earlier due to backwards compatibility.

**Comment by seankhliao** [comment]
given:

> Since the templates created by ParseFiles are named by the base names of the argument files,

I think this is unambiguously working as intended.

it "works" when the name matches simply because it's overwritten.
note that it's also possible to do New().Parse().ParseFiles()
