### ISSUE TITLE
x/build/cmd/gerritbot: creates broken hyperlinks ("publish your drafts!")

### ISSUE THREAD

**Issue by guettli** [golang/go#65998]
### Go version

does not apply

### Output of `go env` in your module/workspace:

```shell
does not apply
```

### What did you do?

I created a tiny PR for Go, and a message created by gopherbot contains a broken hyperlink.

### What did you see happen?

The message: https://github.com/golang/go/pull/65218#issuecomment-1962644297

Link to [publish your drafts](https://github.com/golang/go/wiki/GerritBot#i-left-a-reply-to-a-comment-in-gerrit-but-no-one-but-me-can-see-it) is broken.

### What did you expect to see?

I expect to see a hyperlink to the docs about how to "publish your drafts"

**Comment by dmitshur** [comment]
Thanks for reporting.

Fixing this will involve navigating the constraint that the current message is used for de-duplication, so changes to its exact text without an additional mechanism to detect comments that have been synchronized will lead to duplicates. See [CL 530736](https://go.dev/ci/530736) for details.

It is more important to fix this now as the github.com/golang/go/wiki link is no longer equivalent and simply broken, as you pointed out.

CC @golang/release, @thepudds.
