### ISSUE TITLE
x/tools/internal/versions: fix interpretation of empty language version

### ISSUE THREAD

**Issue by timothy-king** [golang/go#66007]
`x/tools/internal/versions` currently interprets invalid/unknown language versions (`""`) as some unknown earliest version. `go/types` interprets an unknown language version as "an empty string disables Go language version checks" and treats this as if all language features are allowed. This is closer to treating this as if it is some unknown future version. `x/tools` should be consistent with `go/types`.

Users of internal/versions `x/tools/go/analysis/passes/loopclosure` and `x/tools/go/ssa` need to update their interpretation.

Related #65612.

**Comment by timothy-king** [comment]
It probably should be cherry picked as a bug fix.

**Comment by dmitshur** [comment]
Ok, that involves more steps, please see https://go.dev/wiki/MinorReleases.
Since this is the main tracking issue, let's move it to the Go1.23 milestone.
