### ISSUE TITLE
x/mobile: Info.plist not found for  compiled xcframework

### ISSUE THREAD

**Issue by Simon-Zeng** [golang/go#66018]
Starting from XCode 15.3, each framework must have Info.plist located directly under framework root, otherwise app won't be able to run on Simulator (iOS device with iOS 17.4 or later?).
i.e. https://github.com/ProtonMail/gopenpgp/issues/271

![Screen Shot 2024-03-15 at 11 03 15](https://github.com/golang/go/assets/6614318/90e017c4-74d0-4eef-b0a6-bedb80888810)
We don't have `Info.plist` file under gopenpgp.xcframework/ios-arm64_x86_64-simulator/Gopenpgp.framework/.

Could you please update procedure for "gomobile bind" to put an alias of Info.plist to framework root?
Thank you.

**Comment by cagedmantis** [comment]
cc @hyangah

**Comment by scosman** [comment]
Anyone have a workaround for this? I can create the needed `Info.plist` in framework root, but it fails parsing. Not sure which keys are needed.

**Comment by Simon-Zeng** [comment]
> Anyone have a workaround for this? I can create the needed `Info.plist` in framework root, but it fails parsing. Not sure which keys are needed.

Could you please add possibility for users to pass parameter with an URL value of `Info.plist`?

**Comment by scosman** [comment]
@Simon-Zeng I'm not a maintainer. Just trying to fix the same issue in my project, and get the info needed for the maintainers to make a quick fix. An alias won’t work as there are relative paths inside that top plist

**Comment by scosman** [comment]
I've found a working fix manually. I think we need this built into the go mobile framework generator. Slightly confusing since it involves 2 Info.plist files.

First one: the generated framework needs an `Info.plist` in each of the generated `NAME.framework` subfolders. This can just be an empty plist:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
</dict>
</plist>
```

Second one: the existing `Info.plist` that is generated in each nested framework folder, in the subpath `Versions/Current/Resources/Info.plist`

Looks like Xcode 15.3 is expecting 2 properties here: CFBundleExecutable (the name of the static library file), and CFBundleIdentifier (a bundle ID, I use the same string as the CFBundleExecutable).

Example:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>CFBundleExecutable</key>
        <string>Appcore</string>
        <key>CFBundleIdentifier</key>
        <string>Appcore</string>
</dict>
</plist>
```

**Comment by scosman** [comment]
@Simon-Zeng mind testing my PR with a fix? Instructions in the PR.

https://github.com/golang/mobile/pull/96

**Comment by Simon-Zeng** [comment]
> @Simon-Zeng mind testing my PR with a fix? Instructions in the PR.
> 
> [golang/mobile#96](https://github.com/golang/mobile/pull/96)

It works for me. Thanks.

**Comment by Simon-Zeng** [comment]
@scosman We had another issue when using framework built with gomibile on Xcode 15.3, but not sure whether it is related to `Info.plist` too:
1, Archive iOS project with frameworks updated by this fix
2, Export app for debug/ad-hoc distribution
3, Try to install apps on iOS devices, it will fail.

Or 
1, Archive iOS project with frameworks updated by this fix
2, Validate the archive using `Validate app` in `Archives` panel of Xcode
3, Validation will raise error.

**Comment by scosman** [comment]
I'm seeing issues as well.

Deploying to a real device gets and error: `Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.yIsKMw/extracted/voicebox.app/Frameworks/Appcore.framework : 0xe800801c (No code signature found.)`

And on archive validation: `No architectures in the binary. Lipo failed to detect any architectures in the bundle executable.`

Can you add your error messages here @Simon-Zeng

**Comment by Simon-Zeng** [comment]
@scosman Seems like gomobile build frameworks in static mode instead of dyld mode. It may be a reason leading issue on Xcode 15.3.
![Screen Shot 2024-03-21 at 11 41 51](https://github.com/golang/go/assets/6614318/a339c8e6-daa4-4b81-97a1-9271038b1d14)

**Comment by scosman** [comment]
@Simon-Zeng can you provide some more details on what you moved to work with 15.3? I could fix gomobile but need specifics

**Comment by scosman** [comment]
Okay, got it from the docs!

 - Add the keys @Simon-Zeng mentioned to the 2xInfo.plist at NAME.framework/Info.plist
 - Remove the /Resources directories in NAME.framework/ dirs. No need for second Info.plist
 - remove all the symlinks and just move the Headers/ Modules/ and binary to the NAME.framework/ root. The other format is for MacOS as described here: https://developer.apple.com/documentation/bundleresources/placing_content_in_a_bundle?language=objc
 - Update the xcframework Info.plist to point to the new binary paths

This fixes several issues: 
 - Can run on device
 - Can archive+validate

I'll prob open a new issue for this and try a fix next week. The hard part will be keeping macos compatibility. The old system was to use symlinks to make it both work in same format. Now we'll need to maintain conditional targeting based on platform.

@hajimehoshi Any reason to not make this the new structure for iOS target?

**Comment by scosman** [comment]
New issue here for the issue under discussion: https://github.com/golang/go/issues/66500
