### ISSUE TITLE
x/tools/gopls: gopls and other tool installs fail on 2021 M1 Max Mac

### ISSUE THREAD

**Issue by salorsino** [golang/go#66012]
### gopls version

latest

### go env

```shell
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/pseg/Library/Caches/go-build'
GOENV='/Users/pseg/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/pseg/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/pseg/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.22.0'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/pseg/Desktop/Code/learn-go/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-
```

### What did you do?

I enabled the Go VS Code extension and I get errors that I have to install `gopls` and other tools, so when I try to install it, I keep getting an error, and I have no intellisense or any features in my editor.

### What did you see happen?

2024-02-28 16:51:25.923 [info] Tools environment: GOPATH=/Users/pseg/go
2024-02-28 16:51:25.923 [info] Installing 5 tools at /Users/pseg/go/bin
2024-02-28 16:51:25.923 [info]   gopls
2024-02-28 16:51:25.923 [info]   gotests
2024-02-28 16:51:25.923 [info]   goplay
2024-02-28 16:51:25.923 [info]   dlv
2024-02-28 16:51:25.923 [info]   staticcheck
2024-02-28 16:51:25.923 [info] 
2024-02-28 16:51:26.759 [info] Installing golang.org/x/tools/gopls@latest FAILED
2024-02-28 16:51:26.759 [info] {
 "code": 1,
 "killed": false,
 "signal": null,
 "cmd": "/usr/local/go/bin/go install -v golang.org/x/tools/gopls@latest",
 "stdout": "",
 "stderr": "# golang.org/x/tools/gopls\n/usr/local/go/pkg/tool/darwin_arm64/link: running clang failed: exit status 1\nld: Undefined symbols:\n  _darwin_arm_init_mach_exception_handler, referenced from:\n      _x_cgo_init in 000005.o\n  _darwin_arm_init_thread_exception_port, referenced from:\n      _threadentry in 000005.o\n      _x_cgo_init in 000005.o\nclang: error: linker command failed with exit code 1 (use -v to see invocation)\n\n"
}

### What did you expect to see?

Successful install

**Comment by simulationguest** [comment]
See https://github.com/golang/go/issues/62432#issuecomment-1763798412

**Comment by salorsino** [comment]
> See [#62432 (comment)](https://github.com/golang/go/issues/62432#issuecomment-1763798412) for a solution

This didn't work unfortuntately

**Comment by adonovan** [comment]
Hmm, that is surprising. Perhaps you could try the following commands and share their output with me:

```
$ go version
$ go install golang.org/x/tools/gopls@v0.15.1
$ go version $(which gopls)
```
