### ISSUE TITLE
all.bash: problem with spaces in path

### ISSUE THREAD

**Issue by programmingkidx** [golang/go#66061]
### Go version

go version go1.22.0 darwin/amd64

### Output of `go env` in your module/workspace:

```shell
This isn't needed.
```

### What did you do?

I ran this command:
`clear ; time GOOS=darwin GOARCH=amd64 ./all.bash`

### What did you see happen?

I saw this error message at the end of testing the go compiler:
`./all.bash: line 13: /<snip>/Go: No such file or directory`

### What did you expect to see?

I expected to see this:
```
ALL TESTS PASSED
---
Installed Go for darwin/amd64 in /Users/<snip>/Go compiler/goroot
Installed commands in /Users/<snip>/Go compiler/goroot/bin
*** You need to add /Users/<snip>/Go compiler/goroot/bin to your PATH.
```

**Comment by programmingkidx** [comment]
Here is my patch to fix this issue. 

[Fix-banner-issue-with-spaces-in-the-path.patch](https://github.com/golang/go/files/14464201/Fix-banner-issue-with-spaces-in-the-path.patch)

```
---
 src/all.bash | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/all.bash b/src/all.bash
index 5f8e8fec63..1b8ca093e4 100755
--- a/src/all.bash
+++ b/src/all.bash
@@ -10,4 +10,4 @@ if [ ! -f make.bash ]; then
 fi
 . ./make.bash "$@" --no-banner
 bash run.bash --no-rebuild
-$GOTOOLDIR/dist banner  # print build info
+"$GOTOOLDIR/dist" banner  # print build info
-- 
2.14.3 (Apple Git-98)
```

**Comment by seankhliao** [comment]
please see https://go.dev/doc/contribute on how to contribute a fix.
