### ISSUE TITLE
go test -cover [-args -test.gocoverdir] not covering some code that is known to be executed under test

### ISSUE THREAD

**Issue by thediveo** [golang/go#66067]
### Go version

go version go1.22.0 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/x/.cache/go-build'
GOENV='/home/x/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/x/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/x/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/snap/go/10506'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/snap/go/10506/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22.0'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/x/github/notwork/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3694336057=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

Nota bene: I already asked in the golang-nuts group, but got no response whatsoever. If I did a stupid mistake, it was unfortunately not pointed out to me so far.

Unfortunately, I've no minimal example and/or playground, as this happens on a IRL repository only.

```bash
git clone https://github.com/thediveo/notwork
cd notwork
make coverage
```

Then view the resulting `coverage.html` and navigate to `github.com/thediveo/notwork/link/link.go`. Notice how the following [`if`'d block](https://github.com/thediveo/notwork/blob/47c8dbf132b345bf8cf30a9c0e4054af6b24b8a0/link/link.go#L129) (permlink) `peername := ...` has no coverage (red):

```go
if veth, ok := link.(*netlink.Veth); ok {
    peername := base62Nifname(prefix)
    veth.PeerName = peername
}
```

However, the unit tests from `github.com/thediveo/notwork/veth` [execute](https://github.com/thediveo/notwork/blob/47c8dbf132b345bf8cf30a9c0e4054af6b24b8a0/veth/veth_test.go#L48) (permlink) the `if`'d block:

```go
	It("creates a VETH pair in the same network namespace", func() {
		dupond, dupont := NewTransient()
```

```go
func NewTransient(opts ...Opt) (dupond netlink.Link, dupont netlink.Link) {
	veth := &netlink.Veth{
		LinkAttrs: netlink.LinkAttrs{},
	}
	dupond = link.NewTransient(veth, VethPrefix)
```

The coverage is taken as follows:

```bash
GOCOVERTMPDIR="$(mktemp -d)"
trap 'rm -rf -- "$GOCOVERTMPDIR"' EXIT
go test -cover -v -race -exec sudo -tags ${BUILDTAGS} -p=1 -count=1 ./... -args -test.gocoverdir="$GOCOVERTMPDIR"
go tool covdata textfmt -i="$GOCOVERTMPDIR" -o=coverage.out
go tool cover -html=coverage.out -o=coverage.html
```

When inserting a panic in the seemingly uncovered `if`'d block and running the tests as before, this correctly triggers a panic (as expected).

### What did you see happen?

Above referenced `if`'d code block shown in red in the HTML coverage output, as uncovered.

### What did you expect to see?

Above referenced `if`'d code block shown in gray/dark green in the HTML coverage output, thus shown as covered.

**Comment by seankhliao** [comment]
see the -coverpkg flag.

**Comment by thediveo** [comment]
Thank you very much, that was it! I've seen this in the past but was confused by the descriptions.
