### ISSUE TITLE
cmd/go: print file name when showing an import cycle

### ISSUE THREAD

**Issue by purpleidea** [golang/go#66078]
We've all hit the common:

```
package foo
	imports whatever1
	imports whatever2
	imports whatever3
	imports bar: import cycle not allowed
```

It would great if it showed the actual file name of the imports, so that when there are multiple files in a package, it's easier to narrow down which one is the offender.

Eg:

```
package foo: blah.go
	imports whatever1: file1.go
	imports whatever2: something.go
	imports whatever3: thing.go
	imports bar: import cycle not allowed
```

Of course a more symmetrical approach might look like:

```
import cycle not allowed
imports foo: blah.go
imports whatever1: file1.go
imports whatever2: something.go
imports whatever3: thing.go
imports package foo
```

But whatever the formatting the code idea is that we make it easier for the user to know which file was part of the loop.

What about the situation of more than one file offending? Well this is a topological sort, so we already only guarantee that we print a single loop, even when there are more than one paths.

Of note, we _don't_ want a full absolute path printed, we already know where things should be based on package name, we do care about the relative file path in that package.

Thanks!

**Comment by mknyszek** [comment]
CC @bcmills @matloob

**Comment by bcmills** [comment]
As a minor nit, I think it would be slightly clearer like `imports whatever1 (in file1.go)`, rather than just a `:`.

**Comment by purpleidea** [comment]
> As a minor nit, I think it would be slightly clearer like imports whatever1 (in file1.go), rather than just a :.

I don't think it's a nit, any suggestions to improve the formatting are appreciated! I don't have a good recommendation or a strong preference here. I mostly just care that the data is exposed to the user =D

One suggestion: make it easy for terminal users to copy paste out the filename. On the end is easy for most terminal emulators for example. Other ways are possible too.

**Comment by matloob** [comment]
@xin-tsla sent a CL implementing something similar to this. The big difference in their CL is that it used full absolute paths with line numbers. That would make jumping to the import in an editor easier, but I agree with @purpleidea that we shouldn't print the full absolute paths. I don't have a strong opinion on the line numbers, but they're not as useful if we don't have absolute paths. It would make finding the import easier, but it's usually not very hard to find an import in the top of a source file.

**Comment by xin-tsla** [comment]
Hi All, in the PR to have the basename in the stack, the error message looks like following:
```
package cyclic-import-example
        imports cyclic-import-example/packageA from main.go:4:5
        imports cyclic-import-example/packageB from a.go:5:2
        imports cyclic-import-example/packageA from bb.go:5:2: import cycle not allowed
```
<img width="737" alt="image" src="https://github.com/user-attachments/assets/4e78cd14-126b-4d61-8aaa-ea2a5d3e1c63">

In my IDE, it somehow supports to jump to file location even it is a base name.
Just would like to hear everyone's thoughts about the change.
Thank you!

**Comment by purpleidea** [comment]
> In my IDE, it somehow supports to jump to file location even it is a base name.

I don't think including the line numbers is helpful since 99% of the time all the imports are all at the top anyways, and if not they'd be easy to find.

The downside however is that those paths are not directly copy+pasteable into a terminal, so this is less ergonomic. The IDE's can handle not having the line numbers.

If we _really_ want to do this properly, then we should use terminal hyperlinks, like so: https://purpleidea.com/blog/2018/06/29/hyperlinks-in-gnome-terminal/

**Comment by xin-tsla** [comment]
Thanks for the info! @purpleidea 
Will read the link to see if we could apply it to the CL.

**Comment by xin-tsla** [comment]
@purpleidea , it is a good blog to read, thanks for writing and sharing the knowledge! Good to know the hyperlink and escape sequences chars on terminal.
As your point in the comment, it makes sense to have the file name without linenumber.
And I made a change, the new error message is:
<img width="672" alt="image" src="https://github.com/user-attachments/assets/f5953789-5f4e-4249-b984-27ed6af4efc1">
It is close to what you proposed.
Let's list the points in the proposal:
1. Add file name append each imports in the stack
2. If the number of file names is more than one for one import, we append with delimiter `,`, and the limit is 10 (TBD, it could be less), example in the following screenshot:
<img width="689" alt="image" src="https://github.com/user-attachments/assets/ac3fb111-d5f8-46da-8430-54336eeeb131">
<img width="993" alt="image" src="https://github.com/user-attachments/assets/3b3a7148-7a73-4bdd-8672-911b0781da2e">

Wondering are we all in alignment on the proposal?
Please free feel to add comments.
Thanks!

**Comment by matloob** [comment]
I think this looks reasonable but I think it's enough to list just one file per import

**Comment by xin-tsla** [comment]
> I think this looks reasonable but I think it's enough to list just one file per import

@matloob thanks for the comment! 
Addresed and submitted: 
<img width="679" alt="image" src="https://github.com/user-attachments/assets/b5a354f7-38d5-4f0c-8177-857073867407">

**Comment by matloob** [comment]
So I don't think we need the "and more" either. The import cycle error is just showing one path that contains a cycle, but there could be more, so i think that it's implicitly clear that we're just showing one route.

**Comment by xin-tsla** [comment]
> So I don't think we need the "and more" either. The import cycle error is just showing one path that contains a cycle, but there could be more, so i think that it's implicitly clear that we're just showing one route.

@matloob  got it. Addressed the comment and submitted:
<img width="703" alt="image" src="https://github.com/user-attachments/assets/1b9e7acf-30e8-427f-bd03-0762d79ec22a">

**Comment by xin-tsla** [comment]
Hi @matloob , @purpleidea , 
Wondering do you think we could finalize the proposal based on the above discussion?
Thanks!

**Comment by matloob** [comment]
That sounds good to me.

**Comment by xin-tsla** [comment]
@matloob , great! Thanks for the info! 👍 
Wondering how do we change the proposal issue to finalized issue or do we have a label for the finalized issue?

**Comment by matloob** [comment]
I don't think we need a label. Let's proceed with the review

**Comment by dmitshur** [comment]
@matloob https://go.dev/wiki/HandlingIssues suggests issues should have one of the Needs{Investigation,Decision,Fix} labels after they're triaged. Removing NeedsInvestigation without adding something else puts it back in the [untriaged queue](https://go.dev/wiki/Gardening#triage-new-bugs).

NeedsFix seems like the best fit, but feel free to adjust. Thanks.

**Comment by matloob** [comment]
Oh thanks- NeedsFix is correct.

**Comment by xin-tsla** [comment]
Thanks all for helping to finalize the proposal!!
