### ISSUE TITLE
Different instances of MyError1 are treated as the same instance. MyError1 is without fields.

### ISSUE THREAD

**Issue by kdpdev** [golang/go#66079]
### Go version

go version go1.22.0 windows/amd64

### Output of `go env` in your module/workspace:

```shell
doesn't matter
```

### What did you do?

Different instances of MyError1 are treated as the same instance. Looks like it is becouse of optimisation of empty struct{} that has a static address for all instances. Is it a bug or feature for user defined structs? The code is here:
https://go.dev/play/p/YLXRwCEDDfy

```
package main

import (
	"errors"
	"fmt"
)

type MyError1 struct {
}

func (MyError1) Error() string {
	return "my error 1"
}

type MyError2 struct {
	b bool
}

func (MyError2) Error() string {
	return "my error 2"
}

func main() {

	{
		err1 := &MyError1{}
		err2 := &MyError1{}
		fmt.Println(errors.Is(err1, err2)) // true
		fmt.Println(errors.Is(err2, err1)) // true
	}

	{
		err1 := &MyError2{}
		err2 := &MyError2{}
		fmt.Println(errors.Is(err1, err2)) // false
		fmt.Println(errors.Is(err2, err1)) // false
	}
}
```

### What did you see happen?

I see the results of errors.Is are different for types with and without fields.

### What did you expect to see?

I expect the results of errors.Is are the same for types with and without fields.

**Comment by seankhliao** [comment]
see https://go.dev/ref/spec#Comparison_operators

> Pointers to distinct [zero-size](https://go.dev/ref/spec#Size_and_alignment_guarantees) variables may or may not be equal.
