### ISSUE TITLE
x/pkgsite: syscall.Stdin Stdout and Stderr documentation is wrong for Windows

### ISSUE THREAD

**Issue by AidanWelch** [golang/go#66083]
### What is the URL of the page with the issue?

https://pkg.go.dev/syscall#pkg-variables

### What is your user agent?

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0

### What did you do?

Just read it 

### What did you see happen?

```go
var (
	Stdin  = 0
	Stdout = 1
	Stderr = 2
)
```
Is stated to be each value.  [However, in Windows instead each value is a handle(determined at compile time).](https://cs.opensource.google/go/go/+/master:src/cmd/vendor/golang.org/x/sys/windows/syscall_windows.go?q=Stdout&ss=go%2Fgo)

### What did you expect to see?

Further clarification that in Windows it is a Handle and not a file descriptor. For example

```go
var (
	Stdin  = getStdHandle(STD_INPUT_HANDLE)
	Stdout = getStdHandle(STD_OUTPUT_HANDLE)
	Stderr = getStdHandle(STD_ERROR_HANDLE)
)
```

`STD_INPUT_HANDLE`, `STD_OUTPUT_HANDLE`, and `STD_ERROR_HANDLE` correspond to `-10`, `-11`, and `-12` respectively as defined here https://learn.microsoft.com/en-us/windows/console/getstdhandle as is getStdHandle

**Comment by rittneje** [comment]
At the top of the page, you can see a drop-down labeled "Rendered for", which defaults to "linux/amd64". If you change that to "windows/amd64" then you will see the expected documentation. https://pkg.go.dev/syscall?GOOS=windows#pkg-variables

**Comment by AidanWelch** [comment]
Oh thank you!  Sorry!
