### ISSUE TITLE
x/tools/gopls: crash importing test variant of tools file

### ISSUE THREAD

**Issue by painhardcore** [golang/go#66109]
gopls version: v0.15.1/go1.22.0
gopls flags: 
update flags: proxy
extension version: 0.41.1
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Fri, 01 Mar 2024 00:31:32 GMT
restart history:
Fri, 01 Mar 2024 00:30:44 GMT: activation (enabled: true)

Crashing gopls
```
panic: nil metadata for "github.com/mailru/easyjson/easyjson [command-line-arguments.test]"

goroutine 7085 [running]:
golang.org/x/tools/gopls/internal/cache.(*Snapshot).getPackageHandles.func1(0x1400d4f3950, {0x14009c2b040, 0x41})
	/Users/painhardcore/go/pkg/mod/golang.org/x/tools/gopls@v0.15.1/internal/cache/check.go:872 +0x53c
golang.org/x/tools/gopls/internal/cache.(*Snapshot).getPackageHandles.func1(0x0, {0x14009c54500, 0x7a})
	/Users/painhardcore/go/pkg/mod/golang.org/x/tools/gopls@v0.15.1/internal/cache/check.go:889 +0x468
golang.org/x/tools/gopls/internal/cache.(*Snapshot).getPackageHandles(0x140021d59e0, {0x10104c648, 0x14008365590}, {0x1400b2c9b08, 0x1, 0x0?})
	/Users/painhardcore/go/pkg/mod/golang.org/x/tools/gopls@v0.15.1/internal/cache/check.go:899 +0x17c
golang.org/x/tools/gopls/internal/cache.(*Snapshot).forEachPackage(0x140021d59e0, {0x10104c648, 0x14008365320}, {0x1400b2c9b08, 0x1, 0x1}, 0x1400a266c80, 0x1400cb41ca0)
	/Users/painhardcore/go/pkg/mod/golang.org/x/tools/gopls@v0.15.1/internal/cache/check.go:343 +0x134
golang.org/x/tools/gopls/internal/cache.(*Snapshot).PackageDiagnostics(0x140021d59e0, {0x10104c680?, 0x1400582e6e0?}, {0x1400b2c9b08, 0x1, 0x1})
	/Users/painhardcore/go/pkg/mod/golang.org/x/tools/gopls@v0.15.1/internal/cache/snapshot.go:686 +0x19c
golang.org/x/tools/gopls/internal/cache.(*Snapshot).orphanedFileDiagnostics(0x140021d59e0, {0x10104c680, 0x1400582e6e0}, {0x1400a266c00, 0x3, 0x10104aaf8?})
	/Users/painhardcore/go/pkg/mod/golang.org/x/tools/gopls@v0.15.1/internal/cache/snapshot.go:1452 +0x1c8
golang.org/x/tools/gopls/internal/cache.(*Session).OrphanedFileDiagnostics(0x1400048e150, {0x10104c680, 0x1400582e6e0})
	/Users/painhardcore/go/pkg/mod/golang.org/x/tools/gopls@v0.15.1/internal/cache/session.go:1165 +0x474
golang.org/x/tools/gopls/internal/server.(*server).diagnoseChangedViews(0x14000190000, {0x10104c680, 0x1400582e6e0}, 0x3, 0x140086b0b40, 0x0)
	/Users/painhardcore/go/pkg/mod/golang.org/x/tools/gopls@v0.15.1/internal/server/diagnostics.go:157 +0x4f0
golang.org/x/tools/gopls/internal/server.(*server).didModifyFiles.func2()
	/Users/painhardcore/go/pkg/mod/golang.org/x/tools/gopls@v0.15.1/internal/server/text_synchronization.go:269 +0x3c
created by golang.org/x/tools/gopls/internal/server.(*server).didModifyFiles in goroutine 108
	/Users/painhardcore/go/pkg/mod/golang.org/x/tools/gopls@v0.15.1/internal/server/text_synchronization.go:268 +0x468
[Error - 01:31:32] 

```

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 8067,
    "TestdataFiles": 52,
    "GoFiles": 6683,
    "ModFiles": 4,
    "Dirs": 1348
  },
  "GOARCH": "arm64",
  "GOOS": "darwin",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.22.0",
  "GoplsVersion": "v0.15.1",
  "InitialWorkspaceLoadDuration": "1.65849025s",
  "MemStats": {
    "HeapAlloc": 108681552,
    "HeapInUse": 144924672,
    "TotalAlloc": 294147416
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 6971,
      "Largest": 7361676,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.22.0",
        "AllPackages": {
          "Packages": 1426,
          "LargestPackage": 214,
          "CompiledGoFiles": 8363,
          "Modules": 177
        },
        "WorkspacePackages": {
          "Packages": 593,
          "LargestPackage": 214,
          "CompiledGoFiles": 4074,
          "Modules": 1
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

**Comment by painhardcore** [comment]
@findleyr reproducable repo https://github.com/painhardcore/goplscrash . Just go to tools/tools_test.go and gopls will crash.

**Comment by findleyr** [comment]
Indeed it does! Apparently the file must be in a nested directory. Thank you for the reproducer!

**Comment by painhardcore** [comment]
Yep, in our case file tools_test.go was in root folder, so every test file in a big repo was like a trigger 😄

**Comment by findleyr** [comment]
@painhardcore and @amirrmonfared, huge thanks for your conscientious help resolving this bug.  The CL above should fix this crash. However, we have a couple other issues to sort out before we cut gopls@v0.15.2 with this fix.

**Comment by painhardcore** [comment]
> @painhardcore and @amirrmonfared, huge thanks for your conscientious help resolving this bug.  The CL above should fix this crash. However, we have a couple other issues to sort out before we cut gopls@v0.15.2 with this fix.

Thanks.
I fixed the issue in our repo, so we can work on 0.15.1

**Comment by amirrmonfared** [comment]
Thanks a lot @findleyr for your support and thanks to @painhardcore for solving the issue in our repo ❤️

**Comment by findleyr** [comment]
This fix is included in our prerelease:

```
go install golang.org/x/tools/gopls@v0.15.2-pre.1
```
