### ISSUE TITLE
Delve is too old

### ISSUE THREAD

**Issue by abc-tetris** [golang/go#66113]
### Go version

go version is 1.22.0

### Output of `go env` in your module/workspace:

```shell
GO111MODULE='auto'
GOARCH='amd64'
GOBIN=''
GOCACHE='/Users/xxxx/Library/Caches/go-build'
GOENV='/Users/xxxx/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/xxxx/Thumb/work/repos/go/path/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/maru/Thumb/work/repos/go/path'
GOPRIVATE=''
GOPROXY='https://goproxy.io,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/darwin_amd64'
GOVCS=''
GOVERSION='go1.22.0'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/xxxx/Downloads/delve-1.21.0/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3877593811=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

System:   macOS
Version:   13.6.3
just debug, can't set breakpoint
func main() {
	a := new(int)
	*a = 1
}

### What did you see happen?

WARNING: undefined behavior - version of Delve is too old for Go version 1.22.0 (maximum supported version 1.21)
Exiting
Debugger finished with the exit code 0

### What did you expect to see?

how do fixed it?

**Comment by Jorropo** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and [proposals](https://go.dev/s/proposal-process) only.

For asking questions please see https://go.dev/wiki/Questions.
