### ISSUE TITLE
x/text/message: does gotext extract variable that starts with "msg"?

### ISSUE THREAD

**Issue by bigguaxxx** [golang/go#66128]
### Go version

go version go1.18.10 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/xzp/Library/Caches/go-build"
GOENV="/Users/xzp/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/xzp/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/xzp/go"
```

### What did you do?

I defined a global variable that starts with "msg" in main.go, but it is not being called by message.printer. When I execute the gotext extraction, the result unexpectedly extracts this variable into the translation document.
var msgEnv string = "idc"

### What did you see happen?

➜  awesomeProject9 go generate ./translations/translations.go
en: Missing entry for "msgEnv".

### What did you expect to see?

msgEnv not be extracted

**Comment by thepudds** [comment]
Hi @bigguaxxx, can you provide a small sample program (ideally in the playground at https://go.dev/play) along with the exact set of steps to reproduce this?

**Comment by mknyszek** [comment]
CC @mpvl via https://dev.golang.org/owners

**Comment by bigguaxxx** [comment]
> Hi @bigguaxxx, can you provide a small sample program (ideally in the playground at https://go.dev/play) along with the exact set of steps to reproduce this?

I new a test project like this:├── go.mod
├── go.sum
├── main.go
└── translations
    └── translations.go


```golang
// translations.go
package translations

//go:generate gotext -srclang=ch update -out=catalog.go -lang=en,ch ..
```

```golang
// main.go
package main

import (
	"fmt"
	_ "golang.org/x/text/language"
	_ "golang.org/x/text/message"
)

var msgEnv string = "idc"

func main() {
	fmt.Println("hello")
}
```

then
```shell
➜  awesomeProject9 go generate ./translations/translations.go
\en: Missing entry for "msgEnv".
en: Missing entry for "idc".
```

**Comment by seankhliao** [comment]
see [CL 105016](https://go.dev/cl/105016)
