### ISSUE TITLE
x/tools/gopls: import errors with multi-root workspace and gopls@v0.15.0+

### ISSUE THREAD

**Issue by andig** [golang/go#66145]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
`go version go1.22.0 darwin/arm64`
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
```

Build info
----------
golang.org/x/tools/gopls v0.15.1
    golang.org/x/tools/gopls@v0.15.1 h1:WBLlqa3auWKt/jbezarYT204f7IDtCdOn260vY0q4Vk=
    github.com/BurntSushi/toml@v1.2.1 h1:9F2/+DoOYIOksmaJFPw1tGFy1eDnIJXg+UHjuD8lTak=
    github.com/google/go-cmp@v0.6.0 h1:ofyhxvXcZhMsU5ulbFiLKl/XBFqE1GSq7atu8tAmTRI=
    golang.org/x/exp/typeparams@v0.0.0-20221212164502-fae10dda9338 h1:2O2DON6y3XMJiQRAS1UWU+54aec2uopH3x7MAiqGW6Y=
    golang.org/x/mod@v0.15.0 h1:SernR4v+D55NyBH2QiEQrlBAnj1ECL6AGrA5+dPaMY8=
    golang.org/x/sync@v0.6.0 h1:5BMeUDZ7vkXGfEr1x9B4bRcTH4lpkTkpdh0T/J+qjbQ=
    golang.org/x/telemetry@v0.0.0-20240209200032-7b892fcb8a78 h1:vcVnuftN4J4UKLRcgetjzfU9FjjgXUUYUc3JhFplgV4=
    golang.org/x/text@v0.14.0 h1:ScX5w1eTa3QqT8oi6+ziP7dTV1S2+ALU0bI+0zXKWiQ=
    golang.org/x/tools@v0.18.1-0.20240227180630-1c466157abc9 h1:DAFzI/OUTyNjVKs2nsM593aR8oHWjVh3ftZ7XQFEKXw=
    golang.org/x/vuln@v1.0.1 h1:KUas02EjQK5LTuIx1OylBQdKKZ9jeugs+HiqO5HormU=
    honnef.co/go/tools@v0.4.6 h1:oFEHCKeID7to/3autwsWfnuv69j3NsfcXbvJKuIcep8=
    mvdan.cc/gofumpt@v0.6.0 h1:G3QvahNDmpD+Aek/bNOLrFR2XC6ZAdo62dZu65gmwGo=
    mvdan.cc/xurls/v2@v2.5.0 h1:lyBNOm8Wo71UknhUs4QTFUNNMyxy2JEIaKKo0RWOh+8=
go: go1.22.0
```
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.

```
Version: 1.87.0 (Universal)
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Date: 2024-02-27T23:42:56.944Z (1 day ago)
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.2.0
```

* Check your installed extensions to get the version of the VS Code Go extension
	- <Paste Go extension version here>
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- <Paste the output here>
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

```
    "go.gopath": "~/go",
    "go.useLanguageServer": true,
    "gopls": {
        "formatting.gofumpt": true,
    },
    "go.languageServerFlags": [
        "serve",
        "-rpc.trace",
        "--debug=localhost:6060"
    ],
```

### Describe the bug
For some days, gopls has started complaining about missing imports. `go.mod` and `go.sum` are clean and project compiles.

Extension host shows errors:

```
2024-02-29 18:21:56.462 [error] [golang.go] provider FAILED
2024-02-29 18:21:56.462 [error] Error: semantictokens are disabled
    at handleResponse (/Users/andig/.vscode/extensions/golang.go-0.41.1/dist/goMain.js:8606:40)
    at handleMessage (/Users/andig/.vscode/extensions/golang.go-0.41.1/dist/goMain.js:8416:11)
    at processMessageQueue (/Users/andig/.vscode/extensions/golang.go-0.41.1/dist/goMain.js:8431:13)
    at Immediate.<anonymous> (/Users/andig/.vscode/extensions/golang.go-0.41.1/dist/goMain.js:8407:11)
    at processImmediate (node:internal/timers:476:21)
```

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.
<img width="802" alt="Screenshot 2024-02-29 at 18 21 03" src="https://github.com/golang/vscode-go/assets/184815/fbbf0eed-ec4f-42d1-a977-5b10885de011">

**Comment by findleyr** [comment]
Hmm, I think the fix above was actually insufficient. Investigating further...

**Comment by findleyr** [comment]
Hi, this should also be fixed in the next gopls prerelease:

```
go install golang.org/x/tools/gopls@v0.15.2-pre.1
```

@ErwanDL @andig please let me know if this does not fix the bug for you.

**Comment by andig** [comment]
Just did and added the offending root. No more errors- LGTM! Much appreciated!

**Comment by ErwanDL** [comment]
Indeed, looks like it works in `v0.15.2-pre.1`! Thanks a lot for the quick fix.

**Comment by X-lem** [comment]
I still seem to have this error :/ 

```
$ go version
go version go1.22.1 windows/amd64

$ gopls -v version
Build info
----------
golang.org/x/tools/gopls v0.15.3

$ code -v
1.89.1
dc96b837cf6bb4af9cd736aa3af08cf8279f7685
x64
```

My setup looks like this.

```
- Root folder
    - .vscode/
    - client/ (React application)
    - server/ (Go application)
  my-application.code-workspace
  .gitignore
```

If I open my application via the `my-application.code-workspace` file I get the error pictured below. I don't get any errors if I open `/server` file directly. This issue has only started happening the last 2-3 months. I've tried several of the solutions posted in this thread including reverting back to older versions. Also done a `go mod tidy` and "Restart Language Server" in vscode.

![image](https://github.com/golang/go/assets/6555273/bf36775c-15d4-4cd9-a6f9-5e9762716a20)

**Comment by TeddyHarnat** [comment]
I am also still getting this error
