### ISSUE TITLE
x/pkgsite: issue title

### ISSUE THREAD

**Issue by xhyqaq** [golang/go#66163]
### What is the URL of the page with the issue?

https://github.com/golang/pkgsite/blob/master/internal/middleware/requests.go

### What is your user agent?

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0

### Screenshot

![image](https://github.com/golang/go/assets/73917396/6f845c04-ddbf-4175-9fa6-a5d502203f99)

![image](https://github.com/golang/go/assets/73917396/5b56c763-69f4-4de7-a08c-2ab0a99092ca)

### What did you do?

git clone 

### What did you see happen?

context.WithCancelCause not found 

- Troubleshooting: WithCancelCause can only be used with go version 1.2.0+

- I'm a newbie and I don't understand why the go.mod version isn't updated here

### What did you expect to see?

context.WithCancelCause No error

**Comment by Jorropo** [comment]
`WithCancelClause` was added in go 1.20, so go 1.19 does not have this feature.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and [proposals](https://go.dev/s/proposal-process) only.

For asking questions please see: https://go.dev/wiki/Questions
