### ISSUE TITLE
Debug Excessively Slow Stepping Through Code

### ISSUE THREAD

**Issue by teschste-reyrey** [golang/go#66173]
### Go version

1.22.1

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=auto
GOARCH=amd64
GOBIN=
GOCACHE=C:\Users\teschste\AppData\Local\go-build
GOENV=C:\Users\teschste\AppData\Roaming\go\env
GOEXE=.exe
GOEXPERIMENT=
GOFLAGS=
GOHOSTARCH=amd64
GOHOSTOS=windows
GOINSECURE=
GOMODCACHE=C:\Users\teschste\go\pkg\mod
GONOPROXY=tssgit.reyrey.com/*
GONOSUMDB=tssgit.reyrey.com/*
GOOS=windows
GOPATH=C:\Users\teschste\go
GOPRIVATE=tssgit.reyrey.com/*
GOPROXY=https://proxy.golang.org,direct
GOROOT=C:\Program Files\Go
GOSUMDB=sum.golang.org
GOTMPDIR=
GOTOOLCHAIN=auto
GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
GOVCS=
GOVERSION=go1.22.1
GCCGO=gccgo
GOAMD64=v1
AR=ar
CC=gcc
CXX=g++
CGO_ENABLED=1
GOMOD=E:\Dev\Programs\Hardware Manuals DB Sync\go.mod
GOWORK=
CGO_CFLAGS=-O2 -g
CGO_CPPFLAGS=
CGO_CXXFLAGS=-O2 -g
CGO_FFLAGS=-O2 -g
CGO_LDFLAGS=-O2 -g
PKG_CONFIG=pkg-config
GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\teschste\AppData\Local\Temp\go-build3612461297=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

Stepped through Go code in VS Code.

### What did you see happen?

Instead of each step being almost instantaneous as usual, each step takes anywhere from 2-3 seconds for a 2 line application, to 12-13 seconds for a larger application.

I am not certain what triggered it, though it was shortly after upgrading to v1.22.1 that I noticed it.

If I just run the app in VS Code (assuming there are no errors), it runs fast as usual, this only occurs when stepping through the code.

I moved back down to v1.21.8 to see if it was related to my recent upgrade but the issue remained, so I moved back up to 1.22.1.

Since I saw no other issues like this reported, this is likely something unique to me but I even tried completely uninstalling and reinstalling Go with no improvement and nothing else changed in the timeframe this occurred.

### What did you expect to see?

Each step occurring almost instantly as it always has in the past.

**Comment by teschste-reyrey** [comment]
Since I also recently upgraded to VS Code 1.87, I tried going back to version 1.86 but that did not help either.

**Comment by seankhliao** [comment]
sounds like an issue for the debugger (delve?) and not the go project.

**Comment by teschste-reyrey** [comment]
Not sure if this changes your thinking at all but this post was just added to the issue I logged under delve.  Not sure if this puts the ball back in your court, VS Code's court, or somewhere else but an issue that is potentially "fixed" by switching to a preview version of the Go extension seems concerning.  Thoughts?
