### ISSUE TITLE
x/build/cmd/gomote: install builder dependencies by default

### ISSUE THREAD

**Issue by cagedmantis** [golang/go#66170]
The gomote instances should have all the dependencies installed by default upon creation. This will increase the amount of time a gomote creation takes. The resulting machine will match the environment where tests are executed.

@golang/release

**Comment by dmitshur** [comment]
This is resolved as of [CL 569875](https://go.dev/cl/569875). (It didn't get closed automatically because the Fixes line didn't specify the `golang/go` repo quite right.)
