### ISSUE TITLE
x/website: change Handle to HandleFunc in routing-enhancements blog post

### ISSUE THREAD

**Issue by rwxrob** [golang/go#66199]
### What is the URL of the page with the issue?
 
https://go.dev/blog/routing-enhancements
 
### What is your user agent?
 
[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36](https://explore.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)
 
### Screenshot

![handlepost-bug](https://github.com/golang/go/assets/3749067/6c4700cf-b9f9-41d0-9c93-0788bd23d407)
 
### What did you do?
 
Read the docs. The reference to "handlePost" function suggests that the second argument is, in fact, a function and not a struct. Therefore, `HandleFunc` would be called instead.
 
### What did you expect to see?

```golang
HandleFunc
```

### What did you see instead?

```golang
Handle
````

**Comment by mknyszek** [comment]
CC @jba
