### ISSUE TITLE
x/tools/gopls: panic with patch version in go.mod file

### ISSUE THREAD

**Issue by liumingmin** [golang/go#66195]
gopls version: v0.15.1 (go1.20.13)
gopls flags: 
update flags: proxy
extension version: 0.39.1
go version: 1.21.6
environment: Visual Studio Code win32
initialization error: undefined
issue timestamp: Fri, 08 Mar 2024 06:09:49 GMT
restart history:
Fri, 08 Mar 2024 02:16:19 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: invalid Go version "go1.21.6" (should be something like "go1.12")

goroutine 9724 [running]:
go/types.NewChecker(0xc000bb7950%3F, 0xc006eb10c0, 0xc008a6f360, 0x7%3F)
	  check.go:237  0x24e
golang.org/x/tools/gopls/internal/cache.(*typeCheckBatch).checkPackageForImport(0xc0091a0a20, {0x111aa38, 0xc009654180}, 0xc0021f7b00)
	  check.go:702  0x4df
golang.org/x/tools/gopls/internal/cache.(*typeCheckBatch).getImportPackage(0xc0091a0a20, {0x111aa38, 0xc009654180}, {0xc000bb7950, 0x2f})
	  check.go:469  0x767
golang.org/x/tools/gopls/internal/cache.(*Snapshot).forEachPackageInternal.func1()
	  check.go:396  0x2d
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	  errgroup.go:75  0xa5
[Error - 10:16:36] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by adonovan** [comment]
go/types at go1.20 insisted on a version string of the form "go%d.%d", and would otherwise panic. gopls (since my https://go.dev/cl/557215 in January) permits strings of the form "go%d.%d.%d" as well, since later versions of go/types use the go/version.Lang operation to sanitize/normalize.

I'll change gopls to respect the stricter semantics when compiled with go1.20. I will be so happy when we can drop support for these old toolchains.

**Comment by findleyr** [comment]
Indeed, that day can't come soon enough, particularly now that we've agreed on it!

Thanks for investigating.

**Comment by findleyr** [comment]
@liumingmin do you have an idea of why gopls was compiled with go1.20.13, while your ambient go version is 1.21.6? gopls@v0.15.1 came out last week -- have you upgraded Go in the meantime?

**Comment by findleyr** [comment]
Hmm, in general I don't think we can have forward Go command compatibility. We should probably fail loudly in this scenario.

Originally I thought this was gopls compiled with go1.21.6. Given our new understanding of this problem, I think it would be OK not to fix this for gopls@v0.15.2: gopls needs to be recompiled.

**Comment by findleyr** [comment]
This should be fixed by the next gopls prerelease (though reinstalling gopls with a more recent Go would also fix it anyway):

```
go install golang.org/x/tools/gopls@v0.15.2-pre.1
```
