### ISSUE TITLE
go/types: gotypesalias missing calls to IncNonDefault

### ISSUE THREAD

**Issue by rsc** [golang/go#66216]
There is a new gotypesalias godebug but the corresponding monitoring is missing. gotypesalias.IncNonDefault needs to be called when program behavior changes from the default due to an override godebug setting. And not just whenever it is set, but whenever the setting actually changes the output, so only if an alias is observed. See 'go doc internal/godebug' for more details.

**Comment by mknyszek** [comment]
In triage we think this needs the attention of @griesemer and/or @findleyr? Please comment if I should redirect to someone else. Thanks.

**Comment by cagedmantis** [comment]
This issue was reviewed in the release meeting. Is there any status update to report on this issue?
