### ISSUE TITLE
runtime/metrics: inconsistency can be observed in /cpu/classes metrics

### ISSUE THREAD

**Issue by aktau** [golang/go#66212]
### Go version

go version 1.23-dev-c8c46e746b778c39727c588adf79aff34ab6f151

### Output of `go env` in your module/workspace:

```shell
Not relevant.
```

### What did you do?

Run the following program over and over until it fails. It compares the result of fetching `/cpu/classes/gc/total:cpu-seconds` and calculating it from its parts, and also prints how many ULPs apart the numbers are ([good article on this])(https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/). The program makes a little effort to entice a sheared update (successfully on my workstation). This is perhaps the reason the current tests need a [2% fudge factor](https://github.com/golang/go/blob/61d6817c832e318a8a69c4b48e6b823010b9da96/src/runtime/metrics_test.go#L372) to pass. Once fixed, I recommend adjusting the tests to be much stricter, allowing only a couple of ULPs difference.

```go
package main

import (
	"log"
	"math"
	"os"
	"runtime"
	"runtime/metrics"
	"strconv"
	"sync"
	"time"
)

var samples = []metrics.Sample{
	{Name: "/cpu/classes/gc/total:cpu-seconds"},       // 0
	{Name: "/cpu/classes/idle:cpu-seconds"},           // 1
	{Name: "/cpu/classes/scavenge/total:cpu-seconds"}, // 2
	{Name: "/cpu/classes/total:cpu-seconds"},          // 3
	{Name: "/cpu/classes/user:cpu-seconds"},           // 4
}

func main() {
	// Apply some GC load and wait for a bit. Gives a high chance of obtaining the
	// sheared result on my workstation.
	go applyGCLoad()
	time.Sleep(50 * time.Millisecond)

	// Read metrics.
	metrics.Read(samples)
	gc := samples[0].Value.Float64()
	idle := samples[1].Value.Float64()
	scav := samples[2].Value.Float64()
	total := samples[3].Value.Float64()
	user := samples[4].Value.Float64()

	// Calculate the total from the subtotals.
	calcTotal := (((scav + gc) + user) + idle)

	// Compare total read from metrics versus our own calculation.
	log.Printf("Δ = %s = total (%s) - scav+gc+user+idle (%s), there's %d floats between them\n",
		strconv.FormatFloat(total-calcTotal, 'f', -1, 64),
		strconv.FormatFloat(calcTotal, 'f', -1, 64),
		strconv.FormatFloat(total, 'f', -1, 64),
		int64(math.Float64bits(calcTotal)-math.Float64bits(total)),
	)
	if want, got := total, calcTotal; got != want && (got-want > 0.0001 || want-got > 0.0001) {
		os.Exit(1)
	}
}

func applyGCLoad() func() {
	// We’ll apply load to the runtime with maxProcs-1 goroutines
	// and use one more to actually benchmark. It doesn't make sense
	// to try to run this test with only 1 P (that's what
	// BenchmarkReadMemStats is for).
	maxProcs := runtime.GOMAXPROCS(-1)

	// Code to build a big tree with lots of pointers.
	type node struct {
		children [16]*node
	}
	var buildTree func(depth int) *node
	buildTree = func(depth int) *node {
		tree := new(node)
		if depth != 0 {
			for i := range tree.children {
				tree.children[i] = buildTree(depth - 1)
			}
		}
		return tree
	}

	// Keep the GC busy by continuously generating large trees.
	done := make(chan struct{})
	var wg sync.WaitGroup
	for i := 0; i < maxProcs-1; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			var hold *node
		loop:
			for {
				hold = buildTree(5)
				select {
				case <-done:
					break loop
				default:
				}
			}
			runtime.KeepAlive(hold)
		}()
	}
	return func() {
		close(done)
		wg.Wait()
	}
}
```

### What did you see happen?

```
$ GO111MODULE=off go build && ( export GOMAXPROCS=20 ; while ./metricsbug ; do : ; done )
2024/03/08 15:20:59 Δ = -0.004854960000000075 = total (0.50744394) - scav+gc+user+idle (0.50258898), there's 43729592093798 floats between them
```

### What did you expect to see?

I expected the diff to be much smaller, on the order of [`4*ULP(total)`](https://stackoverflow.com/a/51601753/558819). But there's a very large difference (in float space) between these values.  After investigation together with @mknyszek, the issue was found: most of the value that serve as the source for these metrics are updated in `accumulate`: https://github.com/golang/go/blob/61d6817c832e318a8a69c4b48e6b823010b9da96/src/runtime/mstats.go#L953-L976 

under the same (STW) lock. But  `gcPauseTime` and `gcTotalTime` are not updated outside of the lock somewhere else:
https://github.com/golang/go/blob/61d6817c832e318a8a69c4b48e6b823010b9da96/src/runtime/mgc.go#L751-L752

 It is possible that a metric read happens in between these calls, and sheared results are observed. I've verified that this is what happens by manually changing `sweepTermCpu` to a large value and re-running the test. Exactly this change then appears in the diff.

**Comment by mknyszek** [comment]
Already sent a fix. ;) https://go.dev/cl/570257

I'll see if I can incorporate your test program. Thanks for filing an issue!
