### ISSUE TITLE
html/template: jstmpllitinterp godebug documented but a no-op?

### ISSUE THREAD

**Issue by rsc** [golang/go#66217]
There is a new jstmpllitinterp godebug but the corresponding monitoring 
is missing. jstmpllitinterp.IncNonDefault needs to be called when 
program behavior changes from the default due to an override godebug 
setting. And not just whenever it is set, but whenever the setting 
actually changes the program behavior, so only if a template literal
is accepted when it would normally be rejected. 

See 'go doc internal/godebug' for more details.

All that said, it looks like jstmpllitinterp is completely ignored now?
If so, the package docs should be updated, since they say it has an effect.
Also the doc/godebug.md docs should be updated.

/cc @rolandshoemaker

**Comment by cagedmantis** [comment]
This issue was reviewed in the release meeting. Is the documentation change the only remaining item for this issue?

**Comment by rolandshoemaker** [comment]
Yes, the only remaining change is the documentation one, I'll try to get this out this week.

**Comment by cherrymui** [comment]
@rolandshoemaker this is a release blocker. Any update on this? Thanks.

**Comment by cagedmantis** [comment]
@rolandshoemaker Is there is status update on this issue? There is a CL that has been reviewed. This came up in the release meeting.

**Comment by rolandshoemaker** [comment]
@cagedmantis sorry keep completely forgetting about this, submitted.
