### ISSUE TITLE
https://pkg.go.dev/github.com/spotinst/spotinst-sdk-go: 

### ISSUE THREAD

**Issue by anuragsharma-123** [golang/go#66224]
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/spotinst/spotinst-sdk-go

### What is your user agent?

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

### What did you do?

1. Uploaded a new version of spotinst-sdk-go with tag 2.0.0.
2. This version had a retract statement for v1.334.0. This version was wrongly released.

### What did you see happen?

1. New version is not showing in the versions list.
2. v1.334.0 version is not retracted and it is still showing as latest version, which is causing issue for our customer.

### What did you expect to see?

v2.0.0 as the latest version.
v1.334.0 retracted.

**Comment by seankhliao** [comment]
as v2 is considered a different module (different path), the retract won't apply.
you need something tagged higher in v1
