### ISSUE TITLE
x/tools/gopls: [proposal] .reverse postfix completion should use slices package

### ISSUE THREAD

**Issue by ALX99** [golang/go#66222]
### Notes

This is just a proposal to an existing postfix completion entry 
If this change is considered welcomed I would like to have a try at adding it myself!

### gopls version

devel

### What did you do?

From the following code:

```go
func main() {
  example := []string{}
}
```

### What did you see happen?

typing `example.reverse` yields the following:

```go
func main() {
  example := []string{}
  for i, j := 0, len(example)-1; i < j; i, j = i+1, j-1 {
    example[i], example[j] = example[j], example[i]
  }
  
}
```

### What did you expect to see?

I would like it to yield the following instead since it communicates the intent better

```go
func main() {
  example := []string{}
  slices.Reverse(example)
  
}
```

**Comment by adonovan** [comment]
> typing example.reverse yields the following: ...

That's definitely suboptimal; it should indeed suggest `slices.Reverse`. The necessary code change is to the template ingopls/internal/golang/completion/postfix_snippets.go, and we would indeed welcome it! While you're there, see if there are other cases that need updating for the slices package. Thanks.
