### ISSUE TITLE
x/pkgsite: Site doesn't show latest packages

### ISSUE THREAD

**Issue by purpleidea** [golang/go#66236]
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/purpleidea/mgmt/util

### What is your user agent?

Fedora 38

### What did you do?

Go to that URL

### What did you see happen?

See an old version.

### What did you expect to see?

Expect to see latest git master version.

There are old bugs related to this, eg: https://github.com/golang/go/issues/41278 and https://github.com/golang/go/issues/37106 and many more.

Many packages want to be able to see the docs of git master. The special tags like:

https://pkg.go.dev/github.com/purpleidea/mgmt@master or https://pkg.go.dev/github.com/purpleidea/mgmt/@master don't work.

**Comment by seankhliao** [comment]
seems to be working as expected (current master = 6976f5f3f0abaa99cde1b72c15064464d437deeb)

Note that pkgsite is subject to the same caching as proxy.golang.org

**Comment by purpleidea** [comment]
If you look at the other issues, it's clear something is wrong. For example see here:

https://pkg.go.dev/github.com/purpleidea/mgmt/util?tab=versions

All of a sudden there are now two versions:

![image](https://github.com/golang/go/assets/135091/1caf513c-ed17-4ef9-bda8-4afdfc628b9d)

But where are all the earlier ones? There's no way to get an update and it was stale till apparently I opened this issue.

**Comment by seankhliao** [comment]
there are no automatic updates, only when the appropriate version is requested/fetched
