### ISSUE TITLE
x/crypto/sha3: cSHAKE initialization misbehaves for extremely (unrealistically) large `N` or `S`

### ISSUE THREAD

**Issue by Yawning** [golang/go#66232]
### Go version

go version go1.22.1 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='[REDACTED]'
GOENV='[REDACTED]'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='[REDACTED]'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='[REDACTED]'
GOPRIVATE=''
GOPROXY='direct'
GOROOT='/usr/lib/go'
GOSUMDB='off'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/lib/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22.1'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='[REDACTED]'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3832971843=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

Manual code review.

https://github.com/golang/crypto/blob/7067223927c4e3f3bb91a5c6e0d2aae83df74e7a/sha3/shake.go#L83

### What did you see happen?

`newCShake` will silently misbehave if passed an extremely (unrealistically) large `N` or `S`, due to the multiply overflowing.

### What did you expect to see?

There should be overflow checks for the multiplications in the following calls:
`c.initBlock = append(c.initBlock, leftEncode(uint64(len(N)*8))...)`
`c.initBlock = append(c.initBlock, leftEncode(uint64(len(S)*8))...)`

Alternatively `leftEncode` could be modified to support the full range of possible slice lengths.

**Comment by FiloSottile** [comment]
This can only happen if `int` is 32 bits, and can be fixed by switching to `uint64(len(N))*8`, right?

**Comment by MingLLuo** [comment]
following “cSHAKE implementations is based on NIST SP 800-185 [2]” 3.3 Definition, I think we should check the length validity, len(N) and len(S) should less than 2040bit(255 byte). I make a pr for this~

**Comment by Yawning** [comment]
> This can only happen if int is 32 bits, and can be fixed by switching to uint64(len(N))*8, right?

Because the value is "length of N or S" in bits, 64 bit int can also overflow (though not on any current production silicon) with unfathomably large N or S, due to  `(2^63-1) * 8` overflowing.

> following “cSHAKE implementations is based on NIST SP 800-185 [2]” 3.3 Definition, I think we should check the length validity, len(N) and len(S) should less than 2040bit(255 byte). I make a pr for this~

Unfortunately that's not correct.  The upper limit for all N and S is "2^2040-1 bits".

**Comment by MingLLuo** [comment]
> > following “cSHAKE implementations is based on NIST SP 800-185 [2]” 3.3 Definition, I think we should check the length validity, len(N) and len(S) should less than 2040bit(255 byte). I make a pr for this~
> 
> Unfortunately that's not correct. The upper limit for all N and S is "2^2040-1 bits".

I misunderstood. You were right.

**Comment by MingLLuo** [comment]
I think limit the length this function may support directly can prevent errors (like (2^63 - 1) >> 3, since array len is in int, greater then return error).
support for "2^2040-1 bits" data process will be more intricate(unrealistically🥲

**Comment by FiloSottile** [comment]
> > This can only happen if int is 32 bits, and can be fixed by switching to uint64(len(N))*8, right?
> 
> Because the value is "length of N or S" in bits, 64 bit int can also overflow (though not on any current production silicon) with unfathomably large N or S, due to `(2^63-1) * 8` overflowing.

The max length of a Go slice is 2^48, so `len(x) * 8` is at most 51 bits.

https://github.com/golang/go/blob/3a41bfac9bfddc3663d81b8296dbe8904baef44e/src/runtime/malloc.go#L213-L218

Also, I think we can safely assume no machine has more than 2 exabyte of memory.

If we agree it would fix the 32-bit platforms and that 64-bit platforms are unaffected, I would appreciate a CL to switch to `uint64(len(X))*8`.

**Comment by Yawning** [comment]
> The max length of a Go slice is 2^48, so `len(x) * 8` is at most 51 bits.
> 
> https://github.com/golang/go/blob/3a41bfac9bfddc3663d81b8296dbe8904baef44e/src/runtime/malloc.go#L213-L218
> 
> Also, I think we can safely assume no machine has more than 2 exabyte of memory.

Ah ok.  I didn't know about the limit on slice sizes.  TIL.

> If we agree it would fix the 32-bit platforms and that 64-bit platforms are unaffected, I would appreciate a CL to switch to `uint64(len(X))*8`.

The fix sounds good to me.
