### ISSUE TITLE
net/smtp: clearer documentation for SendMail

### ISSUE THREAD

**Issue by gopherbot** [golang/go#6625]
by **faraazs**:

<pre>Hello,

This is my first bug report for golang. I tried searching for this issue, but
could not find any issues relating to this problem. Please excuse me if I missed
one.

The documentation for net/smtp.SendMail can be clearer. Specifically, it is not
clear that the msg parameter is included directly within the header section. I
have attached a patch that includes a bit more documentation on the msg
parameter.</pre>

Attachments:
1. <a href="https://storage.googleapis.com/go-attachment/6625/0/smtp.patch">smtp.patch</a> (734 bytes)

**Comment by agnivade** [comment]
I believe this can be closed. SendMail documentation now clearly specifies that the msg parameter contains the headers.

```
  // The msg parameter should be an RFC 822-style email with headers
  // first, a blank line, and then the message body. The lines of msg
  // should be CRLF terminated. The msg headers should usually include
  // fields such as "From", "To", "Subject", and "Cc".  Sending "Bcc"
  // messages is accomplished by including an email address in the to
  // parameter but not including it in the msg headers.
```

**Comment by bradfitz** [comment]
@agnivade, thanks!

**Comment by agnivade** [comment]
Oops, you seem to have reopened it again. Mistake ?
