### ISSUE TITLE
access: merge Gerrit accounts, or transfer permissions

### ISSUE THREAD

**Issue by rhysh** [golang/go#66283]
I've contributed to the project for several years using the address `rhys@justin.tv` as the author and committer for my changes, and for logging in to Gerrit. That address is a member of the `may-start-trybots` and `approvers` groups.

Moving forward, I'll be using the address `rhys.hiltner@gmail.com` instead for logging in to Gerrit, and I'd like to still be able to start trybots and approve changes.

@golang/release , are you able to please remove those permissions from `rhys@justin.tv` and apply them to `rhys.hiltner@gmail.com`? Or, @prattmic mentioned the possibility of merging the accounts so all of my changes (with either address) would still show up as being written by the same person, with me using `rhys.hiltner@gmail.com` to log in to Gerrit.

Thanks!

**Comment by cherrymui** [comment]
Hi @rhysh , I have merged the two Gerrit accounts. Let me know if there is any issue (we don't do this very often). Thanks for your contribution!
