### ISSUE TITLE
x/pkgsite: package removal request for github.com/Azure/azure-sdk-for-go/sdk/monitor/azingest

### ISSUE THREAD

**Issue by gracewilcox** [golang/go#66302]
### What is the path of the package that you would like to have removed?

github.com/Azure/azure-sdk-for-go/sdk/monitor/azingest

### Are you the owner of this package?

Yes, I am a software engineer on the Azure SDK for Go team acting with the approval of my organization.

### What is the reason that you could not retract this package instead?

Our team is [restructuring our Azure Monitor modules](https://github.com/Azure/azure-sdk-for-go/issues/22377). For our Monitor Ingestion product, we are moving the code from `sdk/monitor/azingest` to `sdk/monitor/ingestion/azlogs`. We have already released the code in its new location and marked the old module as deprecated. We now want the old module removed from pkg.go.dev.

**Comment by findleyr** [comment]
Just an update / note for teammates: we acted on this, but made a typo. We'll fix the exclusion.

**Comment by ansaba** [comment]
Azure/azure-sdk-for-go/sdk/monitor/azingest pkg has been removed from pkg.go.dev
