### ISSUE TITLE
x/pkgsite: Documentation on how to add calls to C functions to the Go compiler 

### ISSUE THREAD

**Issue by programmingkidx** [golang/go#66311]
### What is the URL of the page with the issue?

not applicable 

### What is your user agent?

not applicable

### What did you do?

no error to report

### What did you see happen?

I ask that a documentation page be made detailing how to add C function calls to the Go compiler. Some might think the simple solution is to use cgo. Unfortunately cgo is not available inside the runtime package. I need this information for Mac OS X, but having documentation for all platforms would be great.

### What did you expect to see?

A tutorial on how to add a C function call to the Runtime package or another package. My suggestion would be to use a simple C function like time() or puts().

**Comment by seankhliao** [comment]
I think this is out of scope for user facing documentation
