### ISSUE TITLE
x/text/language: parsing Tagalog tag (tl) returns Filipino (fil)

### ISSUE THREAD

**Issue by jmooring** [golang/go#66335]
### Go version

go version go1.22.1 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/jmooring/.cache/go-build'
GOENV='/home/jmooring/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/jmooring/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/jmooring/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/snap/go/10553'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/snap/go/10553/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22.1'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1138695096=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

https://go.dev/play/p/tw0ydFlH09E

### What did you see happen?

fil

### What did you expect to see?

tl

**Comment by cherrymui** [comment]
cc @mpvl

**Comment by seankhliao** [comment]
there is a test case that tests for this though https://go.googlesource.com/text/+/6c97a165dd661335ff7bce6104a008558123c353/language/language_test.go#492

**Comment by jmooring** [comment]
@seankhliao Thank you for looking into this. The question is, obviously, whether that test case is correct. I am not a linguist, but `tl` is a valid ISO 639-1 language code, so something like `tl-PH` should be valid per BCP 47.

**Comment by jmooring** [comment]
Digging into this, it's a bit messy due to historical usage and linguistic ambiguity. The CLDR [aliases `tl` to `fil`](https://www.unicode.org/cldr/charts/44/supplemental/aliases.html), so we're doing the right thing here despite the fact that `tl-PH` is valid per BCP&nbsp;47.

```
tl-PH --> fil-PH
```
