### ISSUE TITLE
x/tools/cmd/goimports: Provide equivalent of "gofmt -s"

### ISSUE THREAD

**Issue by rata** [golang/go#66342]
`gofmt` provides `-s` to simplify code. It would be great if goimports can provide that too, as some projects like Kubernetes are using `gofmt -s` on CI and catching some things I can't catch locally using goimports.

**Comment by seankhliao** [comment]
This is out of scope for goimports, it's not intended to grow the features of other tools.

**Comment by rata** [comment]
I guess you are aware, but the documentation says:

> In addition to fixing imports, goimports also formats your code in the same style as gofmt so it can be used as a replacement for your editor's gofmt-on-save hook. 

It is hard to replace a tool if not all the functionality is provided. But fair, if the goal it is not to provide that.
