### ISSUE TITLE
x/tools/go/types:  API adjustments, cleanup

### ISSUE THREAD

**Issue by gordonklaus** [golang/go#6634]
<pre>- export fields from the various Type structs instead of providing accessor methods,
e.g., Map.Key, Pointer.Base
- NewMap should validate its key Type
- expose Convertible, ValidMapKey, others?
- consistent naming of predicates IsIdenticalTo, IsAssignable:  trim both &quot;Is&quot;
and &quot;To&quot;</pre>

**Comment by griesemer** [comment]
Several (most?) of the suggestions have been implemented; it's too late for the remaining ones. The API may be extended but otherwise is now frozen.
