### ISSUE TITLE
encoding/json: Unicode \u escape not required for surrogate pairs

### ISSUE THREAD

**Issue by theory** [golang/go#66368]
### Go version

go version go1.22.0 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/david/Library/Caches/go-build'
GOENV='/Users/david/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/david/.gvm/pkgsets/go1.22.0/global/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/david/.gvm/pkgsets/go1.22.0/global'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/Users/david/.gvm/gos/go1.22.0'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/Users/david/.gvm/gos/go1.22.0/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.22.0'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/david/dev/go/try/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/_c/9qfk97x92zq400p82xhtbw240000gn/T/go-build4118721530=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

I noticed this bit of the encoding/json decoder:

https://github.com/golang/go/blob/0a6f05e30f58023bf45f747a79c20751db2bcfe7/src/encoding/json/decode.go#L1253-L1272

Note that at line 1261 it does not check to see whether the next two characters start another unicode escape sequence `\u`, but just merrily skips them (in `getu4`) and extracts the four bytes following.

Reproduction of the issue:

``` go
package main

import (
	"encoding/json"
	"fmt"
)

func main() {
	var list []string
	json.Unmarshal([]byte(`["\uD834..DD1E"]`), &list)
	fmt.Println(list[0])
}
```

### What did you see happen?

This program outputs:

```
𝄞
```

### What did you expect to see?

I'd expect to see an error or perhaps the lone unicode escape replaced with `unicode.ReplacementChar`

**Comment by dr2chase** [comment]
I could not reproduce this in the playground, with 1.22, 1.21, or dev.  I will try again on an arm64 laptop.
Also I am not testing (yet) at exactly 1.22.0.
Playground link: https://go.dev/play/p/PlMjgO4mlM_i

**Comment by theory** [comment]
Yeah I didn't get that result in the playground, either, which is odd. But definitely did on my Mac, and looking at the code it's pretty clear it doesn't check for the presence of `\u`.

**Comment by dr2chase** [comment]
getu4 seems to validate:
```
// getu4 decodes \uXXXX from the beginning of s, returning the hex value,
// or it returns -1.
func getu4(s []byte) rune {
	if len(s) < 6 || s[0] != '\\' || s[1] != 'u' {
		return -1
	}
```

**Comment by dr2chase** [comment]
I'm going to say this is not a bug -- doesn't reproduce for me, and I see the check.

**Comment by theory** [comment]
Holy cow! I've been borrowing code from decode.go for my own project, and see now that I accidentally deleted those lines! I don't need them for my project, so removed them — but from the wrong file 🤦🏻. Apologies for the distraction.
