### ISSUE TITLE
cmd/cgo: TestParallelSleep test is flaky

### ISSUE THREAD

**Issue by lexprfuncall** [golang/go#6636]
<pre>I am getting the occasional test failure

--- FAIL: TestParallelSleep (1.56 seconds)
        issue1560.go:44: difference in start time for two sleep(1) is 562ms
        issue1560.go:48: parallel 1-second sleeps slept for 0.562000 seconds</pre>

**Comment by rsc** [comment]
Last update 2014. Assuming this is no longer an active concern.
