### ISSUE TITLE
x/pkgsite: strings.Trim misleading documentation

### ISSUE THREAD

**Issue by Patrick-ring-motive** [golang/go#66382]
### What is the URL of the page with the issue?

https://pkg.go.dev/strings

### What is your user agent?

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

### What did you do?

I'm working on creating a [package](https://github.com/Patrick-ring-motive/go-String) that extends the strings from the standard library and noticed a possible documentation oversight. The following functions in the strings package all claim to return a slice when they actually return a string. Maybe the author is considering a string as a special type of slice but based on how it reads I would expect the return type to be []string not string.

[func Trim(s, cutset string) string](https://pkg.go.dev/strings#Trim)
[func TrimFunc(s string, f func(rune) bool) string](https://pkg.go.dev/strings#TrimFunc)
[func TrimLeft(s, cutset string) string](https://pkg.go.dev/strings#TrimLeft)
[func TrimLeftFunc(s string, f func(rune) bool) string](https://pkg.go.dev/strings#TrimLeftFunc)
[func TrimPrefix(s, prefix string) string](https://pkg.go.dev/strings#TrimPrefix)
[func TrimRight(s, cutset string) string](https://pkg.go.dev/strings#TrimRight)
[func TrimRightFunc(s string, f func(rune) bool) string](https://pkg.go.dev/strings#TrimRightFunc)
[func TrimSpace(s string) string](https://pkg.go.dev/strings#TrimSpace)
[func TrimSuffix(s, suffix string) string](https://pkg.go.dev/strings#TrimSuffix)

### What did you see happen?

 The Trim* functions in the strings package all claim to return a slice when they actually return a string.

### What did you expect to see?

 Maybe the author is considering a string as a special type of slice but based on how it reads I would expect the return type to be []string not string.

**Comment by seankhliao** [comment]
the docs are correct, a string can be sliced, and it's relevant to whether the original string can be garbage collected.

**Comment by Patrick-ring-motive** [comment]
> the docs are correct, a string can be sliced, and it's relevant to whether the original string can be garbage collected.

You get how this is misleading though right? I mean I can agree with you but in golang slices have a very specific meaning that is different from what is being referenced here.

**Comment by ALTree** [comment]
> You get how this is misleading though right? I mean I can agree with you but in golang slices have a very specific meaning that is different from what is being referenced here.

Not really, this kind of language is used in the Language Specification too, for example:

> Except for untyped strings, **if the sliced operand is a string or slice**, the result of the slice operation is

i.e. strings can be sliced and the result of the operation returns "a slice" of that string.

**Comment by Patrick-ring-motive** [comment]
@seankhliao  @ALTree Your example from the language spec further supports what I am getting at actually. When the spec talks about slicing a string it is using slice as a verb and performing a slice action on a string. When the spec talks about "a slice" using the noun, it is talking about the variable length arrays. See it even goes out of its way to specify the difference. "if the sliced operand is a string **or** slice". If they were considered the same then they could have just said "if the sliced operand is a slice". In the strings package, the Trim functions say specifically "Trim returns a slice" not "a sliced string". You can't tell me that this is unambiguous. Why are you arguing against clarity in the documentation?
