### ISSUE TITLE
x/tools/gopls: creation of missing package doesn't invalidate the "missing import" diagnostic

### ISSUE THREAD

**Issue by adonovan** [golang/go#66384]
https://github.com/joaotavora/eglot/issues/550 describes an eglot bug related to a lack of invalidation. While I don't want to let eglot entirely off the hook (I think there are two bugs), I think there's a gopls invalidation bug in there too.

**Comment by findleyr** [comment]
This reminds me of the logic in `Snapshot.clone` to invalidate packages with cycles whenever an import is deleted.
We should invalidate any package with missing imports when a new package is created (or just reinitialize).
