### ISSUE TITLE
panic: interface conversion: interface {} is ^A, not chan struct {}

### ISSUE THREAD

**Issue by lordcheng10** [golang/go#66400]
### Go version

go 1.19

### Output of `go env` in your module/workspace:

```shell
go 1.19
```

### What did you do?

There seems to be something wrong with the parent context, causing the child context to panic when it times out and cancels.

### What did you see happen?

panic: interface conversion: interface {} is ^A, not chan struct {}

goroutine 248219 [running]:
panic({0x2c7a5c0, 0xce0aa0ed50})
        /usr/local/go/src/runtime/panic.go:987 +0x3ba fp=0xcbbc76bd40 sp=0xcbbc76bc80 pc=0x44ca1a
runtime.panicdottypeE(0x3063da0, 0x2ba00a0, 0x2c1c160)
        /usr/local/go/src/runtime/iface.go:267 +0x6a fp=0xcbbc76bd60 sp=0xcbbc76bd40 pc=0x412b6a
context.(*cancelCtx).Done(0xce098d56e0)
        /usr/local/go/src/context/context.go:361 +0x21c fp=0xcbbc76be30 sp=0xcbbc76bd60 pc=0x508fbc
code.byted.org/storage/tls/shard_server/handler.(*BizContext).Done(0xce09437580)
        <autogenerated>:1 +0x42 fp=0xcbbc76be58 sp=0xcbbc76be30 pc=0x2a4f4e2
context.parentCancelCtx({0x30846f0, 0xce09437580})
        /usr/local/go/src/context/context.go:298 +0x4e fp=0xcbbc76bed8 sp=0xcbbc76be58 pc=0x50894e
context.removeChild({0x30846f0, 0xce09437580}, {0x3079940, 0xce097ad620})
        /usr/local/go/src/context/context.go:315 +0x47 fp=0xcbbc76bf40 sp=0xcbbc76bed8 pc=0x508b67
context.(*timerCtx).cancel(0xce097ad620, 0x1, {0x30765a0, 0x43a4160})
        /usr/local/go/src/context/context.go:486 +0x85 fp=0xcbbc76bfa8 sp=0xcbbc76bf40 pc=0x50a2c5
context.WithDeadline.func2()
        /usr/local/go/src/context/context.go:456 +0x35 fp=0xcbbc76bfe0 sp=0xcbbc76bfa8 pc=0x509e35
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xcbbc76bfe8 sp=0xcbbc76bfe0 pc=0x4848a1
created by time.goFunc
        /usr/local/go/src/time/sleep.go:176 +0x45

### What did you expect to see?

no panic

**Comment by seankhliao** [comment]
that sounds like a problem of custom context implementations. also we don't support 1.19

**Comment by lordcheng10** [comment]
> that sounds like a problem of custom context implementations. also we don't support 1.19

Thank you for your attention and hope to get your help!

My context is very simple, I just added some fields, which did not cause the problem. I just used WithTimeout and WithValue to construct some sub-contexts, and then the above panic occurred after the timeout:
typeBizContext struct {
context.Context
Method string
ClientIP string
ReqID string
}

**Comment by lordcheng10** [comment]
> > that sounds like a problem of custom context implementations. also we don't support 1.19
> 
> Thank you for your attention and hope to get your help! @seankhliao
> 
> My context is very simple, I just added some fields, which did not cause the problem. I just used WithTimeout and WithValue to construct some sub-contexts, and then the above panic occurred after the timeout:
> 
> ```
> typeBizContext struct {
> context.Context
> Method string
> ClientIP string
> ReqID string
> }
> ```

![Uploading image.png…]()

**Comment by lordcheng10** [comment]
In addition, I saw a similar error report: https://github.com/golang/go/issues/51789
