### ISSUE TITLE
x/mobile/cmd/gomobile: unsealed contents present in the root directory of an embedded framework

### ISSUE THREAD

**Issue by ianmcfall** [golang/go#66406]
### Go version

go version go1.21.5 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE='on'
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/ian/Library/Caches/go-build'
GOENV='/Users/ian/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/ian/go/pkg/mod'
GONOPROXY='github.com/onlicorp/*'
GONOSUMDB='github.com/onlicorp/*'
GOOS='darwin'
GOPATH='/Users/ian/go'
GOPRIVATE='github.com/onlicorp/*'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/Users/ian/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.5.darwin-arm64'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/Users/ian/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.5.darwin-arm64/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.21.5'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/ian/Developer/onli-3/vault-mobile/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/d3/dzvp6x6s76v407myqn_wmlmh0000gn/T/go-build521929990=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

1. ```gomobile init```

2. ```go get golang.org/x/mobile```

3. Create XCFramework
```gomobile bind -target=macos .```

4. Attempt codesign .framework
```codesign --force --sign "Developer ID Application: Comp (TeamID)" --timestamp --options runtime /path/Vault_mobile.xcframework/macos-arm64_x86_64/Vault_mobile.framework```

### What did you see happen?

- Result of code signing framework: ```unsealed contents present in the root directory of an embedded framework```
- Context: shipping macos app for direct distribution fails to pass any binary/framework that isn't codesigned. The notarytool cli from xcode produces the following (regardless of if the xcframework is signed or not: 
```###
### Package Issues
###
Status: Invalid
Archive contains critical validation errors
[[ Safe ]]
• MyApp.app/Contents/MacOS/MyApp
• [ERROR] The signature of the binary is invalid.
• [ERROR] The signature of the binary is invalid.
```

### What did you expect to see?

Expected contents to be sealed in the root directory of an embedded framework. 

_I realize this might be just an XCode issue, but considering the posts I've read about info.plists and bundling problems with the lastest XCode I figured I'd give it a shot. Any insights appreciated._

**Comment by dr2chase** [comment]
@hyangah, any clues?

**Comment by hyangah** [comment]
Sorry I have no clue. Does codesign ... --verbose give more hints any chance?
It's possible that the framework bundle doesn't meet recent codesign's expected layout.

**Comment by ianmcfall** [comment]
@hyangah 
> Sorry I have no clue. Does codesign ... --verbose give more hints any chance? It's possible that the framework bundle doesn't meet recent codesign's expected layout.

Not much that tells me anything. But maybe you it'll inform you. I'm using `-vvv` for verbosity:
```
codesign -vvv --deep --strict /MyApp.app
--prepared:/MyApp.app/Contents/Frameworks/Vault_mobile.framework/Versions/Current/.
/Volumes/CLIENT_APPS/client/tokenx/codesign-vault-only TEST/codesign-vault-only 2024-03-19 14-21-12/codesign-vault-only.app: unsealed contents present in the root directory of an embedded framework
In subcomponent: /MyApp.app/Contents/Frameworks/Vault_mobile.framework
```

**Comment by ianmcfall** [comment]
XCFramework file tree, for ref:
```
Vault_mobile.xcframework
├── Info.plist
├── ios-arm64
│   └── Vault_mobile.framework
│       ├── Headers -> Versions/Current/Headers
│       ├── Info.plist
│       ├── Modules -> Versions/Current/Modules
│       ├── Resources -> Versions/Current/Resources
│       ├── Vault_mobile -> Versions/Current/Vault_mobile
│       └── Versions
│           ├── A
│           │   ├── Headers
│           │   │   ├── Universe.objc.h
│           │   │   ├── Vault_mobile.h
│           │   │   ├── Vault_mobile.objc.h
│           │   │   └── ref.h
│           │   ├── Modules
│           │   │   └── module.modulemap
│           │   ├── Resources
│           │   │   └── Info.plist
│           │   └── Vault_mobile
│           └── Current -> A
├── ios-arm64_x86_64-simulator
│   └── Vault_mobile.framework
│       ├── Headers -> Versions/Current/Headers
│       ├── Info.plist
│       ├── Modules -> Versions/Current/Modules
│       ├── Resources -> Versions/Current/Resources
│       ├── Vault_mobile -> Versions/Current/Vault_mobile
│       └── Versions
│           ├── A
│           │   ├── Headers
│           │   │   ├── Universe.objc.h
│           │   │   ├── Vault_mobile.h
│           │   │   ├── Vault_mobile.objc.h
│           │   │   └── ref.h
│           │   ├── Modules
│           │   │   └── module.modulemap
│           │   ├── Resources
│           │   │   └── Info.plist
│           │   └── Vault_mobile
│           └── Current -> A
└── macos-arm64_x86_64
    └── Vault_mobile.framework
        ├── Headers -> Versions/Current/Headers
        ├── Info.plist
        ├── Modules -> Versions/Current/Modules
        ├── Resources -> Versions/Current/Resources
        ├── Vault_mobile -> Versions/Current/Vault_mobile
        └── Versions
            ├── A
            │   ├── Headers
            │   │   ├── Universe.objc.h
            │   │   ├── Vault_mobile.h
            │   │   ├── Vault_mobile.objc.h
            │   │   └── ref.h
            │   ├── Modules
            │   │   └── module.modulemap
            │   ├── Resources
            │   │   └── Info.plist
            │   └── Vault_mobile
            └── Current -> A

34 directories, 28 files
```

**Comment by Simon-Zeng** [comment]
@ianmcfall @hyangah @dr2chase I guess the issue is due to `Info.plist` under `macos-arm64_x86_64/Vault_mobile.framework/`, as Apple has pointed out that `The framework’s root must contain only the Versions directory and symlinks. Don’t place any other content there. Doing so causes code-signing problems. `

Pleases refer: https://developer.apple.com/documentation/bundleresources/placing_content_in_a_bundle

**Comment by Simon-Zeng** [comment]
@ianmcfall iOS requires an `Info.plist` located under framework root when running on Xcode 15.3 and above. So the best solution would be create an alias of `Info.plist` under framework root from `Info.plist` under `{$framework root}/Resources/`, which will work for both iOS and Mac OS.

**Comment by scosman** [comment]
My fix for another issues seems to fix this as well: https://go-review.googlesource.com/c/mobile/+/574055

I can repo a code signing issue before, but not after. Different error message though. 

@ianmcfall want to verify?

**Comment by ianmcfall** [comment]
Thanks for the help, everyone. Closing.

**Comment by ianmcfall** [comment]
> My fix for another issues seems to fix this as well: https://go-review.googlesource.com/c/mobile/+/574055
> 
> I can repo a code signing issue before, but not after. Different error message though.
> 
> @ianmcfall want to verify?
> 
> @Simon-Zeng the suggested symlink will fix this issue, but will cause other issues. Good call on cause!

Apologies @scosman, not sure how I can help to verify that update.

**Comment by scosman** [comment]
@ianmcfall Steps would be:

 - sync git@github.com:scosman/gomobile.git
 - `cd cmd/gomobile`
 - `go build`
 - The run the produced `gomobile` binary in `cmd/gomobile` to bind your library, and check it all works

**Comment by ianmcfall** [comment]
> ...and check it all works

@scosman I just confirmed your `git@github.com:scosman/gomobile.git` passes the `codesign` checks successfully for a macOS app.
