### ISSUE TITLE
net/http: http.Client send reqeust via https cause memory leak

### ISSUE THREAD

**Issue by liumingmin** [golang/go#66401]
### Go version

go verison go1.20.13 windows/amd64

### Output of `go env` in your module/workspace:

```shell
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\admin\AppData\Local\go-build
set GOENV=C:\Users\admin\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\gowork\pkg\mod
set GOOS=windows
set GOPATH=C:\gowork
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.20.13
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=**\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\admin\AppData\Local\Temp\go-build3559619048=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

My project use net/http Client to send request via https to server,
build env is windows10 use `go build -buildmode=c-shared`  to build dll and run on windows7 PC.
when windows7  PC local certificate donot have server certificate's Root CA certificate , then return error is  `tls: failed to verify certificate: x509: certificate signed by unknown author`
At this time many request be sent to server, and the progream memory  increase fast to 1GB.
I think maybe the  http.Client send reqeust via https and No RootCA certificate  cause memory leak.

### What did you see happen?

My project use net/http Client to send request via https to server,
build env is windows10 use `go build -buildmode=c-shared`  to build dll and run on windows7 PC.
when windows7  PC local certificate donot have server certificate's Root CA certificate , then return error is  `tls: failed to verify certificate: x509`
At this time many request be sent to server, and the progream memory  increase fast to 1GB.
I think maybe the  http.Client send reqeust via https and No RootCA certificate  cause memory leak.

### What did you expect to see?

Can this be fixed?

**Comment by panjf2000** [comment]
Could you provide a program that can reproduce this issue?
