### ISSUE TITLE
text/template/parse: Unexpected Behaviour of ActionNode.Position in text/template - Potential Bug?

### ISSUE THREAD

**Issue by shallowclouds** [golang/go#66423]
### Go version

go version go1.21.4 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE='on'
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/xxx/Library/Caches/go-build'
GOENV='/Users/xxx/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/xxx/projects/gopath/pkg/mod'
GOOS='darwin'
GOPATH='/Users/xxx/projects/gopath'
GOROOT='/opt/homebrew/opt/go/libexec'
GOSUMDB='sum.golang.google.cn'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/opt/homebrew/opt/go/libexec/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.21.4'
GCCGO='gccgo'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD='/Users/xxx/projects/xxx/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/mt/w_9vxxsn0ssfxz46n8lbrykh0000gp/T/go-build2022525700=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

https://go.dev/play/p/U8UabjbhJsN

```Go
// You can edit this code!
// Click here and start typing.
package main

import (
	"fmt"
	"reflect"
	"text/template"
)

func main() {
	temp := `{{.locale}}`
	tree, err := template.New("test").Parse(temp)
	if err != nil {
		panic(err)
	}

	node := tree.Root.Nodes[0]
	fmt.Println(reflect.TypeOf(node))
	// expect: {{.locale}} 0
	fmt.Println(node.String(), node.Position())
	// expect: {{.locale}}
	fmt.Println(temp[node.Position():])
}

```

### What did you see happen?

I am currently developing a highlighter for `text/template` scripts. To accomplish this, I require an Abstract Syntax Tree (AST) for the provided template. During this process, I encountered an unexpected behaviour with the `Position` method of the `ActionNode`.

Contrary to my expectations, the `Position` of the `ActionNode` does not include the delimiter ('{{'). However, the `String` method does return the full `{{.locale}}`, inclusive of the delimiter. This discrepancy has prompted me to question whether there is a bug, or if I have misunderstood the purpose of the `Position` function in the `Action` interface.

According to the given documentation comment, `Position() Pos` should represent the 'byte position of the start of node in full original input string'. This, in my understanding, should include the delimiter.

Could you please clarify this discrepancy, or confirm if this is indeed a bug? Thank you for your time and assistance.

### What did you expect to see?

```Go
temp := `{{.locale}}`
tree, err := template.New("test").Parse(temp)
if err != nil {
  panic(err)
}

node := tree.Root.Nodes[0]
fmt.Println(reflect.TypeOf(node))
// expect: {{.locale}} 0
fmt.Println(node.String(), node.Position())
// expect: {{.locale}}
fmt.Println(temp[node.Position():])

```

**Comment by dr2chase** [comment]
@robpike, @mvdan, can you give this a look?

**Comment by robpike** [comment]
The action starts inside the delimiter, so the position field is correct. The String method includes the delimiter for ease of use. So yes, they are inconsistent and perhaps should be consistent, but it's more likely to break things than improve them to try to change this. Plus, you'd need to decide what change to make.

I think it can stay as is.

**Comment by robpike** [comment]
As I said, the action starts inside the delimiter, that's why.

**Comment by shallowclouds** [comment]
> As I said, the action starts inside the delimiter, that's why.

Sorry I may not have made it clear, I mean if there should be a node wraps the action node but contains the delimiter and prefix such as "if" and "range".

**Comment by robpike** [comment]
It's impractical to change the parse tree given the compatibility promise. You'll just have to code around it, which shouldn't be too inconvenient.

**Comment by shallowclouds** [comment]
> It's impractical to change the parse tree given the compatibility promise. You'll just have to code around it, which shouldn't be too inconvenient.

Got it, thanks.
