### ISSUE TITLE
x/website/_content/doc: wrong branch names in install from source docs

### ISSUE THREAD

**Issue by andrewbaptist** [golang/go#66448]
### What is the URL of the page with the issue?

https://go.dev/doc/install/source
 
 
### Screenshot
 
<img width="1522" alt="image" src="https://github.com/golang/go/assets/46975918/ef404376-8cd9-4711-b827-4424910d077e">
 

### What did you do?

It says "check out the latest release tag (go1.12, for example)", it should probably say "check out the latest release tag (release-branch.go1.12, for example)" instead.
 
 
### What did you expect to see?
 
Attempting to follow the docs:
```
% git checkout go1.22
error: pathspec 'go1.22' did not match any file(s) known to git
```

Actual necessary command:
```
% git checkout release-branch.go1.22
branch 'release-branch.go1.22' set up to track 'origin/release-branch.go1.22'.
Switched to a new branch 'release-branch.go1.22'
```

**Comment by go101** [comment]
There is not a `go1.22` tag, try `go1.22.0` or `go1.22.1` please.

**Comment by adonovan** [comment]
As @go101 says, a patch suffix is required. The docs should certainly be updated to state this, or give better alternative instructions.

**Comment by andrewbaptist** [comment]
Thanks!

I had missed the tags, and only looked at branches. It probably is worth clarifying, but I didn't really have a problem solving it, it was more to help anyone else.
