### ISSUE TITLE
x/pkgsite: right aligned ¶

### ISSUE THREAD

**Issue by joeshin** [golang/go#66458]
### What is the URL of the page with the issue?

https://pkg.go.dev/google.golang.org/grpc#hdr-Experimental

### What is your user agent?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

### Screenshot

![Screen Shot 2024-03-21 at 9 32 55 PM](https://github.com/golang/go/assets/485843/69c8c2d0-2b14-41fd-b87c-cdb4c8c473cb)

### What did you do?

Hovered over the Experimental section.

### What did you see happen?

Saw the ¶ link for the heading on the right hand side.

### What did you expect to see?

To see the ¶ link right after the heading text.  The link does appear after the heading text for overview, constants, variables section however functions and types sections show right aligned ¶.

**Comment by adonovan** [comment]
I never understood why the link is a pilcrow, but keeping it close to the symbol name always seemed logical to me. If your screen is wide, the right-hand side is not where your eyes or mouse are likely to be.

**Comment by joeshin** [comment]
@adonovan can I take a crack at it even though it doesn't have a help wanted label just yet?

**Comment by adonovan** [comment]
> can I take a crack at it even though it doesn't have a help wanted label just yet?

Please do!  You should send your CL to @jba for review. Thanks.
