### ISSUE TITLE
cmd/go: go list -m all stuck

### ISSUE THREAD

**Issue by huanghy6268** [golang/go#66463]
### Go version

go version go1.20.7 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GOPROXY="https://proxy.golang.org,direct"
```

### What did you do?

when I run `go list -m all` to detect version of a certain lib, it hangs for more than 5 minutes:
```
root:/work/project# go env | grep GOPROXY
GOPROXY='https://proxy.golang.org,direct'
root:/work/project# time go list -m all
//...
real	5m39.997s
user	1m39.085s
```

and I found this similar issue: https://github.com/golang/go/issues/60395

but I think the default `GOPROXY` already contains `direct`, also found it in the go.env [here](https://cs.opensource.google/go/go/+/refs/tags/go1.21.8:go.env;l=7), not clear about `the  switching to the default GOPROXY (https://proxy.golang.org) means`.

but after I removed the default direct, it indeed takes less time:

```
root:/work/project# go env -w GOPROXY="https://proxy.golang.org"
root:/work/project# go clean -modcache
root:/work/project# time go list -m all
//...
real	0m30.754s
user	0m9.484s
sys	0m7.601s
```

### What did you see happen?

N/A

### What did you expect to see?

return ASAP

**Comment by seankhliao** [comment]
git or other operations are inherently slow.
this is just #60395
