### ISSUE TITLE
x/mobile: `gomobile bind` produces xcframework incompatible with new Xcode 15.3 requirements for iOS builds

### ISSUE THREAD

**Issue by scosman** [golang/go#66500]
### Go version

go1.22.0 darwin/arm64

### What did you do?

`gomobile bind` to produce a xcframework 

### What did you see happen?

The output xcframework isn't compatible with Xcode 15.3 (new Xcode release), when used with iOS devices. 

It works on simulator now because of a fix I made for: https://github.com/golang/go/issues/66018

However the following tasks fail:

 - Debugging on a real device
 - Validating an app archive containing the xcframework
 - Releasing an app using the xcframework

I've determined the fix, described here: https://github.com/golang/go/issues/66018#issuecomment-2016541996

I believe the fix is to follow the Apple ["placing content in a bundle" docs](https://developer.apple.com/documentation/bundleresources/placing_content_in_a_bundle?language=objc) fully. Previously we follow the MacOS docs, then create symlinks from where content is expected on iOS to the MacOS locations. To fix we should follow the right format per platform, without symlinks. We also need to add the new keys.

Open to other suggestions on how to fix. Will try to make a patch next week using approach above if no other suggestions are made.

cc @hajimehoshi @Simon-Zeng

### What did you expect to see?

It should work on Xcode 15.3 😀

**Comment by hajimehoshi** [comment]
CC @hyangah @dmitshur

**Comment by scosman** [comment]
WIP fix: https://github.com/scosman/gomobile/commits/master/

**Comment by Simon-Zeng** [comment]
@scosman This fix should take Mac OS compatibility into consideration too, as reported in #66406 .

**Comment by Simon-Zeng** [comment]
@scosman For symlinks, There seems to be a mistake using `"A": "Versions/Current"`. Shouldn't it be `"/Versions/A": "Versions/Current"`?
![Screen Shot 2024-03-25 at 11 06 26](https://github.com/golang/go/assets/6614318/9897f600-6578-456a-9eb1-33e33f995c36)

**Comment by scosman** [comment]
@Simon-Zeng added a comment explaining that above. dst is relative to src. If both are absolute, when the framework is copied, it keeps original path. This keeps it all relative. Result is correct: `Current -> A`

**Comment by Simon-Zeng** [comment]
@scosman Bundle version and short bundle version in `Info.plist` is necessary for the iOS archive to pass validation.

**Comment by scosman** [comment]
@hajimehoshi easy fix if we're okay with hard coded version. Otherwise we need to add a top level command line parameter for version. Thoughts?

```
  <key>CFBundleShortVersionString</key>
  <string>1.0.0</string>
  <key>CFBundleVersion</key>
  <string>0</string>
```

**Comment by hajimehoshi** [comment]
What about using `0.0.[epoch]` for both?

Adding a global flag to specify the version would be nice but this would be another task.

**Comment by scosman** [comment]
I confirmed it fixes validation.

CFBundleVersion is most commonly a single digit build number. It can be `x.x.x`, but single int is allowed and most common. Spec is "one to three period-separated integers".

How about:

 - CFBundleShortVersionString : `0.0.[epoch]` 
 - CFBundleVersion: epoch

**Comment by hajimehoshi** [comment]
> CFBundleVersion: epoch

My concern is that if a user wants to give a spcific version later, an epoch number seems too big. So, as a tentative version, `0.0.[epoch]` sounds better. Thoughts?

**Comment by scosman** [comment]
The convention I've seen is resetting CFBundleVersion to 0 every time you bump CFBundleShortVersionString, so this wouldn't impact them. But your way will address those concerns so let's do it. I'll patch tomorrow.

**Comment by hajimehoshi** [comment]
> The convention I've seen is resetting CFBundleVersion to 0 every time you bump CFBundleShortVersionString, so this wouldn't impact them.

I thought a new CFBundleVersion must always be bigger than old ones, so resetting 0 didn't work. I might be wrong.

> I'll patch tomorrow.

Thanks!
