### ISSUE TITLE
x/crypto/ssh: ParsePrivateKey gives unintuitive error message for encrypted keys

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#6650]
<pre>key, err := ioutil.ReadFile(&quot;/home/rog/.ssh/id_rsa&quot;)
	if err != nil {
		log.Fatal(err)
	}
	_, err = ssh.ParsePrivateKey(key)
	if err != nil {
		log.Fatalf(&quot;cannot parse ssh private key: %v&quot;, err)
	}

ParsePrivateKey fails with an error like this:

asn1: structure error: tags don't match (16 vs {class:1 tag:28 length:11
isCompound:true}) {optional:false explicit:false application:false
defaultValue:&lt;nil&gt; tag:&lt;nil&gt; stringType:0 set:false omitEmpty:false}
pkcs1PrivateKey @2

I'd expect to see an error that complains about the fact
that the private key is encrypted.</pre>

**Comment by rlynjb** [comment]
go newbie here.. im having the same issue.. looking forward for a solution :-D

**Comment by krlinus** [comment]
Your mentioning the encryption helped me to resolve my asn1 message issue!

**Comment by yougg** [comment]
i'm got same issue too.

- parse the `aa.key` is ok
```bash
openssl genrsa -passout pass:pwdstr -aes256 -out aa.key 2048
```

- but the `bb.key` fails
```bash
openssl req -x509 -days 365 -newkey rsa:2048 -keyout bb.key -passout pass:pwdstr -out bb.crt -subj "/C=CN"
```

> Error message:  
asn1: structure error: tags don't match (2 vs {class:0 tag:16 length:64 isCompound:true}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} int @2

**Comment by odeke-em** [comment]
@yougg I have a feeling that your report might be related to https://github.com/golang/go/issues/13382. Could you re-test it out the latest from Go1.7 or tip?

**Comment by yougg** [comment]
@odeke-em 
my go version is `go version go1.7 windows/amd64`

test with two `openssl` commands from `Git for Windows`  
`C:\Program Files\Git\usr\bin\openssl.exe`  
`C:\Program Files\Git\mingw64\bin\openssl.exe`

**Comment by odeke-em** [comment]
Aye aye @yougg, thank you for helping me confirm.

I am not a crypto expert by any means, but I've mailed https://go-review.googlesource.com/29676 which could use suggestions to make it complete. I've mailed it to get the train started.
