### ISSUE TITLE
Compiler reports an error when trying to assign values from expression that includes function call

### ISSUE THREAD

**Issue by minherz** [golang/go#66529]
### Go version

go version go1.22.0 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/vscode/.cache/go-build'
GOENV='/home/vscode/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='local'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22.0'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/workspaces/go/src/test/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3232209274=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

I wanted to shift the value of the string variable to another variable while setting the original variable with a new value. The new value is calculated by a function that returns the `(string, error)` tuple. The following minimal code example demonstrates what I did

```go
package main

import "fmt"

func main() {
	var s1, s2 string
	var err error

	s1 = "another string"
	// this is the line that generates error
	s2, s1, err = s1, test()
	fmt.Printf("s1 = %s, s2 = %s, error = %v", s1, s2, err)
}

func test() (string, error) {
	s := "some string"
	err := fmt.Errorf("some error")
	return s, err
}
```

### What did you see happen?

When I try to run or build this code example I get the error:

```console
./prog.go:12:16: assignment mismatch: 3 variables but 2 values
```

### What did you expect to see?

I expect the program will build without error and will print out

```console
s1 = some string, s2 = another string, error = some error
```

**Comment by randall77** [comment]
[The spec](https://go.dev/ref/spec#Assignment_statements) does not allow assignment statements like that.
Either there have to be the same number of items on each side of the `=`, or the right-hand side has to be a single multi-valued expression.
Closing, as this is expected. If you want to change something about the language, that would require a language change proposal.

**Comment by minherz** [comment]
Thank you, @randall77 . I found the same place with some delay. My code above is the second form of the assignment that indeed requires matching variables on the left side of the assignment with the single-valued expressions on the right side.
