### ISSUE TITLE
Cgo code is impossible to compile no matter what i've tried 

### ISSUE THREAD

**Issue by AbdeMohlbi** [golang/go#66544]
### Go version

go version go1.22.1 windows/amd64

### Output of `go env` in your module/workspace:

```shell
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\bougara computer\AppData\Local\go-build
set GOENV=C:\Users\bougara computer\AppData\Roaming\go\env  
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\bougara computer\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\bougara computer\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.22.1
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=C:\Users\bougara computer\Desktop\workspace\abde\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\BOUGAR~1\AppData\Local\Temp\go-build3560851944=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

i was trying to create a dll file for calling a function , at first glance i haven't understand why but later i've noticed that each time i add the 'import "C" 'line 
this message appears as a warning over the package main line  even when the go.work file exists and it's there : 
the This file is within module ".", which is not included in your workspace.
To fix this problem, you can add this module to your go.work file
and when trying to do a run or a build it refuses saying : go: no Go source files (and beleive me there is Go files there)

my code :
``
package main
import (
	"C"
	"encoding/json"
	"log"
	"os"
)

type PromptData struct {
	Act    string `json:"act"`
	Prompt string `json:"prompt"`
}
         //export ReadDataFromFile
func ReadDataFromFile(filePathPtr *C.char) *C.char {
	filePath := C.GoString(filePathPtr)
	// Read JSON file
	fileContent, err := os.ReadFile(filePath)
	if err != nil {
		log.Fatalf("Error reading JSON file: %v", err)
		return nil
	}
	// Decode JSON
	var prompts []PromptData
	if err := json.Unmarshal(fileContent, &prompts); err != nil {
		log.Fatalf("Error decoding JSON: %v", err)
		return nil
	}
	// Convert prompts to JSON string
	jsonData, err := json.Marshal(prompts)
	if err != nil {
		log.Fatalf("Error encoding JSON: %v", err)
		return nil
	}
	return C.CString(string(jsonData))
}
func main() {
	// This is needed to compile the program as a shared library
}
``
this code was working normally and compiling to a dll file previously  using this command : 
go build -o example.dll -buildmode=c-shared example.go
note that i was able to compile the code without issues in a previous version of go (i'm not sure wich one but it was the latest at the time in the last 6 months )
so this issue begins after using 1.22.1 this morning 

### What did you see happen?

the code is impossible to compile : go: no Go source files

### What did you expect to see?

i expect the code to compile normally as it was doing previously in the previously go version 

i hope this may get someone attention and guide me to solve it

**Comment by ianlancetaylor** [comment]
Your environment shows that `CGO_ENABLED` is `0`, which means that the go tool ignores all files that use `import "C"`.

**Comment by AbdeMohlbi** [comment]
@ianlancetaylor 
thank you my brother 
it looks like when updating the go version ,all of the previous configuration will be deleted and replaced with default values also i had to change my gcc compiler into a new version .
