### ISSUE TITLE
Increase of memory usage after upgrading from go1.8 to go2.2

### ISSUE THREAD

**Issue by arturg-acoustic** [golang/go#66541]
### Go version

go1.22

### Output of `go env` in your module/workspace:

```shell
GOARCH=amd64 GOOS=linux 
      "GODEBUG" : "disablethp=1, gctrace=1"
```

### What did you do?

I have set       "GODEBUG" : "disablethp=1, gctrace=1" in lambda environment
but it does not seem to have any effect. Unfortunately I can't change the linux provided.al2023 image, as it is not an option using serverless lambda.

### What did you see happen?

My lambda memory consumption increased from 80-90mb to 700mb+

### What did you expect to see?

I expected to see the same level of memory consumption.

**Comment by randall77** [comment]
go2.2 does not exist.
Please include the complete output of `go env`.
I don't know what a "lambda environment" is, so some additional context would help.

**Comment by thediveo** [comment]
AWS environment, so probably an AWS problem.

**Comment by pablodz** [comment]
never seen go2.2

**Comment by arturg-acoustic** [comment]
it's running on AWS lambda (serverless) on provided.al2023 image. 
it's go 1.22

**Comment by randall77** [comment]
> "GODEBUG" : "disablethp=1, gctrace=1"

The space in that string might be preventing gctrace=1 from being recognized.

**Comment by udhos** [comment]
@arturg-acoustic Did you try GOMEMLIMIT ?

I am hitting a somewhat similar issue.
A new proxy application built with Go 1.22.1 increases memory usage at a slow constant rate.
This is my troubleshooting history:

1 - Requests are not served at constant rate but memory increases at slow constant rate.
2 - Profiling did not reveal a culprit for memory leak.
3 - Failed to reproduce it on staging environments.
4 - Attempted "disablethp": It did improve memory usage but did not fix the slow constant growth.
5 - Now I am experimenting with GOMEMLIMIT to restrict memory usage to a reasonable limit.
6 - If GOMEMLIMIT fails, next attempt would be to rebuild the application with 1.19 toolchain.
