### ISSUE TITLE
How often does Go GC after the memory exceeds the GOMEMLIMIT limit?

### ISSUE THREAD

**Issue by 18710309920** [golang/go#66569]
My system triggers OOM when it exceeds 2G. I set the value of GOMEMLIMIT to 1.5G. However, when the memory exceeds 1.5 GB, the GO frequently performs GC, which affects the system performance. I would like to know how the frequency of GC is determined when the memory exceeds the value set by the GOMEMLIMIT

**Comment by Jorropo** [comment]
1hz

---

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and [proposals](https://go.dev/s/proposal-process) only.

Please see: https://go.dev/wiki/Questions
