### ISSUE TITLE
proposal: change base plugin with ebitengine/purego

### ISSUE THREAD

**Issue by MatejMagat305** [golang/go#66577]
### Proposal Details

I know shared-c is not available without C, but there is https://github.com/ebitengine/purego which avoid cgo and provide dlopen ...,  so I  sugest use this for plugin...

**Comment by ianlancetaylor** [comment]
Thanks for the suggestion, but this would need a lot more thought and a lot of work..  Plugins are really different from cgo.  It's not going to be useful to keep this issue open.
