### ISSUE TITLE
x/crypto/ssh whether the idle timeout period of the server can be provided.

### ISSUE THREAD

**Issue by xuwenlong11** [golang/go#66570]
### Proposal Details

Currently, the x/crypto/ssh server does not support the setting of the idle timeout period, and there is no default idle timeout period. As a result, after the client is connected, the session will not exit even if no operation is performed for a long time.

From the perspective of security, I recommend setting the idle timeout period or setting the default idle timeout period.

**Comment by seankhliao** [comment]
Setting any default timeout is an incompatible change that we will not make, given that it is not an unambiguous improvement in security. Given that the creation of a ssh.ServerConn takes a net.Conn, a timeout can be set on the underlying net.Conn. #21420 explains why any finer grained timeouts won't be implemented.
