### ISSUE TITLE
x/pkgsite: package removal request for github.com/jfrech/tbp

### ISSUE THREAD

**Issue by jfrech** [golang/go#66587]

**Comment by jfrech** [comment]
@suzmue Would you please have a look at my removal request?

**Comment by seankhliao** [comment]
there isn't any information in here for us to evaluate this request

**Comment by jfrech** [comment]
What information should I provide? I am writing the request from the only GitHub account which could have owned the now deleted repository with the same name as the package which is known to the pkgsite by only a fully retracted v0 name.

I would like for you to purge the pkgsite cache.

**Comment by jfrech** [comment]
@seankhliao What must I do for the pkgsite team to honour my removal request?

**Comment by jfrech** [comment]
@seankhliao I followed <https://pkg.go.dev/about#removing-a-package>'s link and only added the import path. If there are other pieces of information I must provide before my removal request can be considered, could you please tell me?

**Comment by jfrech** [comment]
@seankhliao Would it be fine if I opened another issue with my removal request? I don't quite understand why this one is being ignored. I also would like to know what information is necessary to provide when filing a package removal request.

**Comment by jfrech** [comment]
Resolved in #66920.

"About pkgsite"'s "file a request" link (cf. https://pkg.go.dev/about#removing-a-package [2024-04-27]) is different to "New Issue"'s (cf. https://github.com/golang/go/issues/new/choose [2024-04-27]).
