### ISSUE TITLE
cmd/compile: package-level variable initialization order looks not correct

### ISSUE THREAD

**Issue by go101** [golang/go#66585]
### Go version

go version go1.22.1 linux/amd64

### Output of `go env` in your module/workspace:

```shell
.
```

### What did you do?

```Go
package main

var x = 0
var a = foo()
var b = x

func foo() int {
	x++
	return x
}

func main() {
	println(a, b) // 1 0
}
```

### What did you see happen?

1 0

### What did you expect to see?

1 1

**Comment by ianlancetaylor** [comment]
CC @griesemer 

gccgo prints `1 1`.

**Comment by griesemer** [comment]
It looks like the type checker is computing the correct order. Here is the initorder trace for the above code:

```
== initOrder ==
Computing initialization order for package p ("p")

Object dependency graph:
        x has no dependencies
        a depends on
                foo
        b depends on
                x
        foo depends on
                x
        main depends on
                a
                b

Transposed object dependency graph (functions eliminated):
        x depends on 0 nodes
                b is dependent
                a is dependent
        a depends on 1 nodes
        b depends on 1 nodes

Processing nodes:
        x (src pos 1) depends on 0 nodes now
        a (src pos 2) depends on 0 nodes now
        b (src pos 3) depends on 0 nodes now

Initialization order:
        x = 0
        a = foo()
        b = x
```

**Comment by randall77** [comment]
Yes, this looks like cmd/compile/internal/initorder not getting it right somehow.
Initorder is generally computed and passed through unified IR export/import correctly. But then we don't use it? Something is odd here.

**Comment by kungfukennyg** [comment]
I'd like to dig further into this issue if no one else is claiming it.

**Comment by mainjzb** [comment]
change to  this
got 1 1  in go v1.22 
got 1 0  in go v1.21 
```go
var x = 0
var a = foo()
var b = x

func foo() int {
	x = x + 1       // diferent
	return x
}

func main() {
	println(a, b)
}
```

**Comment by cuonglm** [comment]
This is a bug in staticinit, where the compiler try optimizing:

```
var x = 0
var a = foo()
var b = x
```
to:

```
var x = 0
var a = ~r0
var b = 0
```

without recognizing that the optimization is unsafe, because foo was inlined.

**Comment by dmitshur** [comment]
Reopening since the fix in [CL 575175](https://go.dev/cl/575175) was rolled back in [CL 575316](https://go.dev/cl/575316).

**Comment by cuonglm** [comment]
@randall77 Should we backport this issue? Though it's not a regression, it causes mis-compilation and make binary behaves wrongly.

**Comment by randall77** [comment]
I don't think we should backport this. It is not a problem that any realistic program runs into, and it is easy to work around if it does.
