### ISSUE TITLE
x/pkgsite:

### ISSUE THREAD

**Issue by petersen65** [golang/go#66591]
### What is the URL of the page with the issue?
 
https://github.com/petersen65/PL0@v2.0.0 
 
### What is your user agent?
 

 
[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0](https://explore.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes) 
 
### Screenshot
 

 
![image](https://github.com/golang/go/assets/6562338/f6644467-c396-4c4e-ab25-ce8969b01dff)
 
 
### What did you do?
 

 
I am requesting the page https://pkg.go.dev/github.com/petersen65/PL0@v2.0.0 to include v2.0.0 of my GitHub repo to the Go package index. For v1.0.0 and v1.1.0, this worked. For the request URL above with version v2.0.0, the package index entry is not generated. From time to time the request button is visible and I hit it.

I assume that I am doing something wrong, and I don't know what. Please help me, thanks in advance.
 
### What did you expect to see?
 
My newly created pages in the Go package index pointing to v2.0.0 
 
### What did you see instead?

Not found
"github.com/petersen65/PL0@v2.0.0" could not be found.

**Comment by seankhliao** [comment]
go modules at v2+ require a /vN suffix in the module path.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
