### ISSUE TITLE
x/build/cmd/gomote:  push failed for gotip-linux-ppc64-power10

### ISSUE THREAD

**Issue by thanm** [golang/go#66619]
### Go version

tip

### Output of `go env` in your module/workspace:

```shell
I'm issuing the commands from linux/amd64. 

The gomote command is built from tip of x/build, e.g. 

$ go version `which gomote`
/w/go1/bin/gomote: devel go1.23-89f7805c2e Fri Mar 29 23:09:29 2024 +0000
$
```

### What did you do?

Created a new ppc64 gomote and tried to push my Go tree to it:

```
$ gomote create gotip-linux-ppc64-power10
...
$ gomote run thanm-gotip-linux-ppc64-power10-0 ls /usr/bin/bash
... works properly
$ gomote push thanm-gotip-linux-ppc64-power10-0
```

### What did you see happen?

Got this error

# Pushing GOROOT "/w/zgo" to "thanm-gotip-linux-ppc64-power10-0"...
2024/03/30 14:25:33 installing go-bootstrap version in the working directory
Error running push: unable to add bootstrap version of Go to instance: rpc error: code = Internal desc = unable to download bootstrap Go

### What did you expect to see?

Successful push

**Comment by cagedmantis** [comment]
I've reproduced this issue. The associated error from the buildlet is:
`024/04/01 14:28:22 writetgz: failed to fetch tgz URL https://storage.googleapis.com/go-builder-data/gobootstrap-linux-ppc64-go1.21.0.tar.gz: status=403 Forbidden`

The bootstrap version was never packaged and uploaded to the bucket. Gomote instances which run on LUCI have the bootstrap go version installed on them during the creation of the gomote instance. The fix here is to remove the installation of the bootstrap version of Go when a `gomote push` is issued.
