### ISSUE TITLE
x/tools/gopls: panic in Analyze with patch version in go.mod file

### ISSUE THREAD

**Issue by irahardianto** [golang/go#66636]
gopls version: v0.15.2/go1.20.4
gopls flags: 
update flags: proxy
extension version: 0.41.2
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Sat, 30 Mar 2024 00:43:17 GMT
restart history:
Fri, 29 Mar 2024 22:57:47 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: invalid Go version "go1.22.1" (should be something like "go1.12")

goroutine 191 [running]:
go/types.NewChecker(0x140002ba5d0%3F, 0x140004b60c0, 0x140001e9310, 0x0%3F)
	  check.go:237  0x1e8
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck(0x140003a8000, {0x14000292410, 0x1, 0x1})
	  analysis.go:1028  0x5fc
golang.org/x/tools/gopls/internal/cache.(*analysisNode).run(0x140003a8000, {0x101c1e998%3F, 0x14000497e30})
	  analysis.go:810  0x1d4
golang.org/x/tools/gopls/internal/cache.(*analysisNode).runCached(0x140003a8000, {0x101c1e998%3F, 0x14000497e30})
	  analysis.go:672  0x104
golang.org/x/tools/gopls/internal/cache.(*Snapshot).Analyze.func6.1()
	  analysis.go:398  0xa4
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x5c
created by golang.org/x/sync/errgroup.(*Group).Go
	  errgroup.go:75  0xa0
</pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 29,
    "TestdataFiles": 0,
    "GoFiles": 1,
    "ModFiles": 1,
    "Dirs": 20
  },
  "GOARCH": "arm64",
  "GOOS": "darwin",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.20.4",
  "GoplsVersion": "v0.15.2",
  "InitialWorkspaceLoadDuration": "55.90625ms",
  "MemStats": {
    "HeapAlloc": 2758320,
    "HeapInUse": 5218304,
    "TotalAlloc": 12841176
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 2,
      "Largest": 57,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.22.1",
        "AllPackages": {
          "Packages": 1,
          "LargestPackage": 1,
          "CompiledGoFiles": 1,
          "Modules": 1
        },
        "WorkspacePackages": {
          "Packages": 1,
          "LargestPackage": 1,
          "CompiledGoFiles": 1,
          "Modules": 1
        },
        "Diagnostics": 1
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
For now, a viable workaround is to install gopls with go1.21+.

However, since this version of gopls nominally supports being build with 1.20, we should fix the crash.

**Comment by irahardianto** [comment]
Thanks for the tip, it rarely crash though, looking forward to the fix
