### ISSUE TITLE
time parse not support "20060102150405000" as format

### ISSUE THREAD

**Issue by ucanme** [golang/go#66632]
### Go version

1.21.6

### Output of `go env` in your module/workspace:

```shell
all version
```

### What did you do?

the time parse package can't use this template "20060102150405000" as format

### What did you see happen?

always happends

### What did you expect to see?

support "20060102150405000" or 20060102150405.000000 as format

**Comment by seankhliao** [comment]
yes it does: https://go.dev/play/p/bgQolPz3Gcc

**Comment by ucanme** [comment]
the milliSecond is always zero
