### ISSUE TITLE
go/build: .syso files can't be specified with .go files

### ISSUE THREAD

**Issue by jaganathanb** [golang/go#66634]
### Go version

go version go1.22.0 windows/amd64

### Output of `go env` in your module/workspace:

```shell
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\XXX\AppData\Local\go-build
set GOENV=C:\Users\XXX\AppData\Roaming\go\env  
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\XXX\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\XXX\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=C:\Projects\tmp
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.22.0
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\XXX\dapps-svc-runr\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=XXX\go-build4047254812=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

Here is the repo to reproduce the bug. - [bug-repo](https://github.com/jaganathanb/go-winres-bug.git)

### What did you see happen?

Follow these command to get the resources embedded into exe.

\go-winres-bug [main ≡ +1 ~0 -0 !]> go-winres init                                  
Created winres/winres.json
\go-winres-bug [main ≡ +3 ~0 -0 !]> git tag -a v1.0.0.0 -m "First version"
\go-winres-bug [main ≡ +3 ~0 -0 !]> go-winres make --product-version=git-tag
\go-winres-bug [main ≡ +5 ~0 -0 !]> go build // This command builds the exe and i could see the exe icon as expected
\go-winres-bug [main ≡ +6 ~0 -0 !]> go build -o custom-name.exe .\main.go // But when i want to build with a file, it is not producing the expected result. Exe work as expected.

### What did you expect to see?

There was a [bug](https://github.com/golang/go/issues/16090) long back but closed as Lack of information. I hope with info given now, we can fix this issue.

**Comment by thanm** [comment]
Hello @jaganathanb , please see this comment: https://github.com/golang/go/issues/16090#issuecomment-258956641

When you say "go build -o something.exe something.go", that tells the Go command to just build an executable based on something.go, not to look at whatever happens to be in the current directory.
