### ISSUE TITLE
golang install for Windows amr64 does not exist ?

### ISSUE THREAD

**Issue by gedw99** [golang/go#66638]
https://go.dev/dl/

can't see windows arm64 at all here ? 

Windows arm64 is a thing that is taking off because of Qualcomm

gobrew actually calls the golang teams released binaries and so I need this to complete this issue: https://github.com/kevincobain2000/gobrew/issues/187

**Comment by ianlancetaylor** [comment]
Closing as dup of #65284.

**Comment by gedw99** [comment]
thanks @ianlancetaylor 

I see now about why it was hidden in the web gui. Because it's not first class yet. 

I installed it anyway using UTM on my M1 Mac to try it out.  Will see how it goes.
