### ISSUE TITLE
text/tabwriter: Misalignment with non-printable characters

### ISSUE THREAD

**Issue by adamroyjones** [golang/go#66661]
### Go version

go version go1.22.1 linux/amd64

### Output of `go env` in your module/workspace:

This shouldn't be relevant, but I've included it below.

<details>
<summary>
go env
</summary>

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN='/home/adamjones/.local/share/go/bin'
GOCACHE='/home/adamjones/.cache/go-build'
GOENV='/home/adamjones/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/adamjones/.local/share/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/adamjones/.local/share/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/home/adamjones/.local/share/mise/installs/go/1.22.1'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/home/adamjones/.local/share/mise/installs/go/1.22.1/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22.1'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/tmp/tabwriter-reprex/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3233429893=/tmp/go-build -gno-record-gcc-switches'
```
</details>

### What did you do?

I noticed that text/tabwriter, which is used for visually aligning text, doesn't seem to account for things being invisible.

There was an abandoned attempt to fix part of this (the ANSI escape codes) [here](https://go-review.googlesource.com/c/go/+/202257), but I can't see an attempt to revisit it.

Here's a small program that illustrates the problem. This seems insensitive to the flags passed to NewWriter. Note that both the line with NUL bytes and the line with ANSI escape codes are misaligned. 

```go
package main

import (
	"fmt"
	"os"
	"strings"
	"text/tabwriter"
)

func main() {
	red := "\033[1m\033[91m"
	reset := "\033[0m"
	nuls := strings.Repeat("\x00", 20)

	w := tabwriter.NewWriter(os.Stdout, 0, 8, 2, '\t', tabwriter.StripEscape)
	fmt.Fprintf(w, "KEY\tVALUE\n")
	fmt.Fprintf(w, "%sfoo\t1%s\n", red, reset)
	fmt.Fprintf(w, "bar\t2\n")
	fmt.Fprintf(w, "baz"+nuls+"\t3\n")
	w.Flush()
}
```

### What did you see happen?

A misaligned table was printed. A screenshot follows.

![maim-2024-04-03T12-07-50](https://github.com/golang/go/assets/10088591/b75f11ae-5b00-4873-a6b5-b84a868e521e)

### What did you expect to see?

I expected an aligned table to be printed.

**Comment by randall77** [comment]
`StripEscape` only strips the tabwriter-defined escape character, `0xff`. It does not strip general unprintable characters.
In any case, `text/tabwriter` is effectively frozen. I'm going to close this, as I don't think we're going to accept improvements at the moment.
