### ISSUE TITLE
atomic.Pointer returned pointer to interface value from Load(), shadowing the value with short decl impossible

### ISSUE THREAD

**Issue by titpetric** [golang/go#66681]
### Go version

go version go1.21.4 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN='/usr/local/bin'
GOCACHE='/root/.cache/go-build'
GOENV='/root/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/root/go/pkg/mod'
GONOPROXY='github.com/TykTechnologies'
GONOSUMDB='github.com/TykTechnologies'
GOOS='linux'
GOPATH='/root/go'
GOPRIVATE='github.com/TykTechnologies'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.4'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/root/tyk/tyk/go.mod'
GOWORK=''
CGO_CFLAGS='-g -O2 -Wno-return-local-addr'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build766378408=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

https://go.dev/play/p/1vJvndqJRvO

### What did you see happen?

./prog.go:25:19: cannot use newVerifier() (value of type Verifier) as *Verifier value in assignment: Verifier does not implement *Verifier (type *Verifier is pointer to interface, not interface)
./prog.go:29:13: cannot use &verifier (value of type **Verifier) as *Verifier value in argument to store.Swap: **Verifier does not implement *Verifier (type *Verifier is pointer to interface, not interface)

### What did you expect to see?

https://go.dev/play/p/e9BwhjoXLZJ

Passing build.

Output: Hello, 世界

**Comment by go101** [comment]
This is totally atomic unrelated. You example code is equivalent to:

```Go
package main

func main() {
	var x any
	var p = &x
	p = x // any does not implement *any
}
```

The error message is indeed imperfect, though.

**Comment by titpetric** [comment]
I think maybe it was my issue in understanding how shadowing works, since I didn't manage to trigger something like this every since go 1.10 days. Closing the issue as I think this works as designed. Thank you @go101
