### ISSUE TITLE
x/tools/gopls/internal/test/marker: 3 test cases failing on linux/arm

### ISSUE THREAD

**Issue by dmitshur** [golang/go#66686]
The definition/embed.txt, definition/misc.txt, and hover/sizeoffset.txt cases of `Test` are failing on linux/arm (32-bit) since they were introduced in [CL 573076](https://go.dev/cl/573076).

For example, see https://ci.chromium.org/b/8752115890806542801/test-results.

CC @adonovan.

**Comment by adonovan** [comment]
Sorry, another semantic merge conflict. Will fix presently.

**Comment by adonovan** [comment]
> Sorry, another semantic merge conflict.

Actually not that: it's just that 32-bit arm is not on our regular CI radar.
