### ISSUE TITLE
x/pkgsite: page jumps back to top after resources finish loading

### ISSUE THREAD

**Issue by mdempsky** [golang/go#66688]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/cmd/compile/internal/ir#NameSet.Sorted
 
### What is your user agent?

 

Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Mobile Safari/537.36
 
 
 
### Screenshot
 

 
 
![Screenshot_20240404-154617](https://github.com/golang/go/assets/38349/75384ad7-c5c8-4ce2-a3d8-8893b9ccf791)

 
### What did you do?
 

 
 I clicked on the link in Google Chat on my phone.
 
### What did you expect to see?

The package ir documentation to open, scroll down to the ir.NameSet.Sorted method, and then stay there.
 
### What did you see instead?

The package ir documentation opened, scrolled down to the ir.NameSet.Sorted method, and then jumped to the very top of the screen again.

**Comment by seankhliao** [comment]
I think this is #60347

**Comment by mdempsky** [comment]
@seankhliao Thank you for finding that for me so quickly! 😊

Yes, it does look like this issue was first reported over a year ago. 😥

**Comment by mdempsky** [comment]
Duplicate of #60347.
