### ISSUE TITLE
x/website: release notes for Go 1.22 mentions inexistent math/rand/v2.Uint()

### ISSUE THREAD

**Issue by rhcarvalho** [golang/go#66693]
### Go version

go version go1.22.2 linux/amd64

### Output of `go env` in your module/workspace:

```shell
N/A
```

### What did you do?

Read release notes at [https://go.dev/doc/go1.22](https://go.dev/doc/go1.22#:~:text=The%20Intn%2C%20Int31%2C%20Int31n%2C%20Int63%2C%20and%20Int64n%20top%2Dlevel%20functions%20and%20methods%20from%20math/rand%20are%20spelled%20more%20idiomatically%20in%20math/rand/v2%3A%20IntN%2C%20Int32%2C%20Int32N%2C%20Int64%2C%20and%20Int64N.%20There%20are%20also%20new%20top%2Dlevel%20functions%20and%20methods%20Uint32%2C%20Uint32N%2C%20Uint64%2C%20Uint64N%2C%20Uint%2C%20and%20UintN), highlights are mine:

> The Intn, Int31, Int31n, Int63, and Int64n top-level functions and methods from math/rand are spelled more idiomatically in math/rand/v2: IntN, Int32, Int32N, Int64, and Int64N. **There are also new top-level functions and methods** Uint32, Uint32N, Uint64, Uint64N, **Uint**, and UintN.

### What did you see happen?

Tried to use `math/rand/v2.Uint`, got a compilation error and realized it doesn't exist, and looking at the CLs that added math/rand/v2 it is possible it never existed, even tough it is mentioned in the original proposal.

### What did you expect to see?

Either the release notes are wrong or the new package is missing intended functionality.

**Comment by jfrech** [comment]
#61716 talks about adding it:

> 9. Add Uint32, Uint32N, Uint64, Uint64N, Uint, UintN, both as top-level functions and methods on Rand. (...)

And the thread ends with the claim all would have been submitted for Go 1.22.

**Comment by jfrech** [comment]
@adonovan Is your resolution motivated by compatibility to the already released Go 1.22 or have there been proposal changes not to include `Uint`?

**Comment by rsc** [comment]
I sent https://go.dev/cl/583455 to add Uint for Go 1.23.
