### ISSUE TITLE
cmd/compile: unnecessary runtime.growslice with provable capacity

### ISSUE THREAD

**Issue by dsnet** [golang/go#66692]
### Go version

go1.22

### Output of `go env` in your module/workspace:

```shell
GOARCH=amd64
GOOS=linux
```

### What did you do?

[Compile the following](https://go.dev/play/p/kkc-3O4mhTT):
```go
package main

import "encoding/binary"

var src uint64
var dst []byte

func main() {
	if cap(dst)-len(dst) < 8 {
		return
	}
	dst = binary.BigEndian.AppendUint64(dst, src)
}
```

### What did you see happen?

I see the following in the assembly:
```
	0x004a 00074 (/usr/local/go1.22.0/src/encoding/binary/binary.go:201)	MOVL	$8, DI
	0x004f 00079 (/usr/local/go1.22.0/src/encoding/binary/binary.go:201)	LEAQ	type:uint8(SB), SI
	0x0056 00086 (/usr/local/go1.22.0/src/encoding/binary/binary.go:201)	PCDATA	$1, $0
	0x0056 00086 (/usr/local/go1.22.0/src/encoding/binary/binary.go:201)	CALL	runtime.growslice(SB)
	0x005b 00091 (/usr/local/go1.22.0/src/encoding/binary/binary.go:201)	MOVQ	encoding/binary.v+64(SP), DX
	0x0060 00096 (/usr/local/go1.22.0/src/encoding/binary/binary.go:201)	BSWAPQ	DX
	0x0063 00099 (/usr/local/go1.22.0/src/encoding/binary/binary.go:201)	MOVQ	DX, -8(BX)(AX*1)
```

### What did you expect to see?

No call to `runtime.growslice`.

This particular example seems silly, but the capacity check already happens elsewhere in code beforehand so there is no possible way that `growslice` would be necessary once we get to `AppendUint64`.

**Comment by dsnet** [comment]
A fix for this should hopefully take #66691 into account such that the following still avoids both `growslice` calls:
```go
if cap(dst)-len(dst) < 1+8 {
	return
}
dst = append(dst, flag)
dst = binary.BigEndian.AppendUint64(dst, src)
```

**Comment by Jorropo** [comment]
With lots of massaging this works:
```go
package main

import "encoding/binary"

var src uint64
var dst []byte

func main() {
	if uint(len(dst)+8) > uint(cap(dst)) {
		return
	}
	dst = binary.BigEndian.AppendUint64(dst, src)
}
```
This works because `uint(len(dst)+8) > uint(cap(dst))` is the exact check generated by the frontend for `append`.

I see at least two things here:
- `SliceLen` and `SliceCap` doesn't seems to be recognized as `uint63` or `uint31` as else `Less64` and `Less64U` should already prove each other https://godbolt.org/z/h9dYfY19M.
- More general equivalence or canonicalization issues.

**Comment by dmitshur** [comment]
CC @golang/compiler.
