### ISSUE TITLE
proposal: x/net/textproto: add generic ServeMux

### ISSUE THREAD

**Issue by sirzooro** [golang/go#66695]
### Proposal Details

Golang provides some support for handling HTTP-like protocols (e.g. SIP, RTSP) in `net/textproto` package. However one important area is not covered there: request multiplexing. Please add new generic multiplexer similar to `http.ServeMux`.

**Comment by seankhliao** [comment]
I believe this is out of scope for textproto, in particular there is no way to route requests generically.
