### ISSUE TITLE
flag: package level nor `CommandLine` var docs mention default behavior of `-h` or `-help` flags

### ISSUE THREAD

**Issue by aaraney** [golang/go#66708]
Out of the box, the default `flag.FlagSet` variable, `flag.CommandLine`, will print usage information and exit `0` if `-h` or `-help` is given and a flag with that name was not already registered. This nicety feature is great, however I discovered by surprise! Looking through the `flag` documentation at `1.22.2`, I found mention of the `-h` and `-help` flags in `ErrHelp`'s documentation, but nothing at the package level or on `CommandLine` specifically about this default behavior.

> ErrHelp is the error returned if the -help or -h flag is invoked but no such flag is defined.

I am happy to open a PR to improve documentation in this area if it would be well receive :).

**Comment by seankhliao** [comment]
it's part of FlagSet.Parse https://pkg.go.dev/flag#FlagSet.Parse

**Comment by aaraney** [comment]
> The return value will be ErrHelp if -help or -h were set but not defined.

@seankhliao, the above snippet from the documentation describe entirely different behavior. `CommandLine.Parse` doesn't return anything and will exit `0` if `-h` or `-help` is provided. This is undocumented.
