### ISSUE TITLE
golang load .dll file, get "failed to load xxx.dll: the specified module could not be found" error

### ISSUE THREAD

**Issue by pengzhihong1637** [golang/go#66710]
I am familiar with C, C++, PYTHON.
I started to learn golang about one month ago.
I also started to learn rust in the same time.
Right now, I am wondering which language should I continue to learn.
So I am trying to rewriting my CAN tool with golang.

Here is the code:

canDll, err := syscall.LoadDLL("./gylinker-x64-dll/VCI_CAN.dll")
	if err != nil {
		log.Fatal("Error during loading .dll file,", err)
	}
	defer canDll.Release()

	proc, err := canDll.FindProc("VCI_InitCAN")
	if err != nil {
		log.Fatal("Error during finding procedure,", err)
	}

	proc.Call() // don't know how to pass parameter yet

I replaced the .dll file with another one from a big company. The error is gone.

canDll, err := syscall.LoadDLL("./zlg-x64-dll/zlgcan.dll")
	if err != nil {
		log.Fatal("Error during loading .dll file,", err)
	}
	defer canDll.Release()

	proc, err := canDll.FindProc("ZCAN_InitCAN")
	if err != nil {
		log.Fatal("Error during finding procedure,", err)
	}

However, the code above seems to work correctly on my laptop (go 1.22), but it crashes when I run it on my PC at office(go 1.19).

So, I have two question:
1. why the code above can load one .dll file correctly, while cannot load the other one?
2. why the code above have different behavior on different computer?

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
