### ISSUE TITLE
proposal: json UnmarshallTo

### ISSUE THREAD

**Issue by maxtreaming** [golang/go#66723]
### Proposal Details

Current implementation of json Unmarshall requires to create a variable that will be used to unmarshall data to.

Since go has generics, we could have that step wrapped into a helper function:
```go
func UnmarshallTo[T any](data []byte) (T, error) {
	var result T
	err := json.Unmarshal(data, &result)
	return result, err
}
```

**Comment by seankhliao** [comment]
I believe this should be part of the #63397 discussion
