### ISSUE TITLE
Compilation Constraint Issue: Mismatch Between Golang Version and go.mod Version

### ISSUE THREAD

**Issue by intmian** [golang/go#66722]
### Go version

go 1.21.1 windows 64bit

### Output of `go env` in your module/workspace:

```shell
go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Administrator\go\pkg\mod
set GONOPROXY=git.idianhun.com
set GOOS=windows
set GOPATH=C:\Users\Administrator\go
set GOPRIVATE=git.idianhun.com
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Users\Administrator\.g\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Users\Administrator\.g\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.21.1
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build3340779885=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

I am using Go version 1.21, and my project’s go.mod specifies Go version 1.14. In my project, I compile the following file:
![d54ef7f7aaeb4cabe746cf76060c2ce0](https://github.com/golang/go/assets/38103855/f2f437a2-d487-4f62-a2d2-e48a8ab68dea)

in go.mod
```
go 1.14
```

### What did you see happen?

During compilation, I encountered the following error:

```
# go.uber.org/zap
embedding non-interface type *T requires go1.18 or later (-lang was set to go1.16; check go.mod)
vendor/go.uber.org/zap/array_go118.go:122:13: cannot use &os[i] (value of type *T) as P value in variable declaration
```

### What did you expect to see?

I would like the compilation to succeed. Interestingly, if I switch my local Go version to 1.15, this error does not occur. After researching, I discovered that the Go version 1.14 in my go.mod file disables generics functionality. However, since my Go version is 1.21, the compilation still attempts to process the array_go118.go file.

My hope is that in future versions, the compilation constraints will take into account the specified Go version in the go.mod file.

My English is not very good, so the translation is ai generated, I'm very sorry, if the reviewer's Chinese level is good you can refer to https://www.intmian.com/archives/yi-zhong-golangbian-yi-yue-shu-yu-ban-ben-hao-chong-tu -de-que-xian

Thank you for your attention to this matter!

**Comment by seankhliao** [comment]
please include a complete reproducer 
and also try 1.22

**Comment by adonovan** [comment]
To elaborate on what @seankhliao said, it would be great help if you could provide a minimal reproduction of the error using only a couple of small files.

Also, go1.14 was released four years ago and is very much unsupported. You should update your go.mod version to something newer (ideally go1.22) if you plan to use newer features such as generics (go1.18).

**Comment by intmian** [comment]
Thank you very much for your response. I am maintaining both my open-source project version 1.21 and our company’s project version 1.14, which is why this situation has occurred. I do not have the permission to update the go.mod version of my company’s project, I am very sorry.

here is my minimal reproduction using go 1.22.

3 files in my test project:`1.18.go`,`sub1.18.go`,`main.go`

`1.18.go`
```
//go:build go1.18
// +build go1.18

package testproj

func test[T any](t T) {
	print(t)
}
```

`sub1.18.go`
```
//go:build !go1.18
// +build !go1.18

package testproj

func test(t int) {
	print(t)
}
```

`main.go`
```
package testproj

func main() {
	test(1)
}
```

`go,mod`
```
module testproj

go 1.14
```

Here's the result of my version checking and compilation:

```
PS E:\my_code_out\testproj> go version       
go version go1.22.2 windows/amd64
PS E:\my_code_out\testproj> go build testproj
# testproj
.\main.go:4:2: implicit function instantiation requires go1.18 or later (-lang was set to go1.14; check go.mod)
```

I am reaching out to express my confusion regarding the compilation constraints not aligning with the version numbers specified in go.mod. It seems contradictory that the version numbers in go.mod can restrict the functionality of golang builder, yet they are not taken as the source of truth for compilation constraints. This creates a significant inconvenience for developers like us who are maintaining multiple legacy and new projects simultaneously, as we are forced to frequently switch between versions.

Could you please clarify if this is an intended behavior or a conflict within the system? Your guidance on this matter would be greatly appreciated as it would greatly assist us in managing our projects more efficiently.
Thank you for your time and consideration

**Comment by seankhliao** [comment]
The constraint works, note that the compilation error is not about the declaration of the function with type parameters, but its call site in main. In other words you're calling `test[int](1)` in `main.go` (with the type parameter being inferred), which isn't allowed in 1.14 code.
