### ISSUE TITLE
net: high cpu usage in extractExtendedRCode

### ISSUE THREAD

**Issue by long-name-let-people-remember-you** [golang/go#66754]
### Go version

go 1.22.2 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN='/usr/local/go/bin'
GOCACHE='/home/xx/.cache/go-build'
GOENV='/home/xx/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/xx/gopath/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/xx/gopath'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22.2'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/xx/gopath/dns/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build185933323=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

concurrent calls to net.LookupAddr

### What did you see happen?

pprof seems that goLookupIp may causes high cpu usage
![image](https://github.com/golang/go/assets/113079915/f53f2e99-7e53-4b43-b58e-e14f93348981)
![image](https://github.com/golang/go/assets/113079915/f32c8299-9853-4c2e-82cd-4f22f29dd888)
![image](https://github.com/golang/go/assets/113079915/234e7e53-0851-4dbe-a689-4b9be30ef524)
[profile.zip](https://github.com/golang/go/files/14926689/profile.zip)

### What did you expect to see?

Occasionally, I don’t know what domain name it was when it happened.

**Comment by ianlancetaylor** [comment]
This code is processing DNS packets.  It would help to know what DNS names are being looked up.

That said, at least part of the problem is that methods like `dnsmessage.Parser.AdditionalHeader` return a value of type `ResourceHeader` which is 268 bytes on amd64.  That's why so much time is being spent in `duffcopy`.

Still, it should only be an issue if the DNS server is returning a lot of additional headers.  It's not clear why that would be happening.

We started looking at the additional headers in https://go.dev/cl/514835.  CC @mateusz834

**Comment by mateusz834** [comment]
Yep, this looks like a DNS response with a bunch of Additional resources, it would be helpful if you could provide us with the raw DNS message reply.

**Comment by long-name-let-people-remember-you** [comment]
thanks for your response. I found that it's an error with my self-build DNS service, my dns service response packet size exceeds 1232.
![image](https://github.com/golang/go/assets/113079915/e4cfeb51-3d20-4226-a64d-90670e8ca60a)
However, the error of not verifying p.SkipAdditional() will lead to an infinite loop:
![image](https://github.com/golang/go/assets/113079915/45a6fad4-9864-4cb6-85d2-f4b86ba4a4c5)
this is my dns response:
[]byte{38, 86, 129, 0, 0, 1, 0, 34, 0, 0, 0, 1, 3, 102, 120, 103, 10, 106, 105, 110, 114, 105, 116, 101, 109, 97, 105, 3, 99, 111, 109, 0, 0, 1, 0, 1, 3, 102, 120, 103, 10, 106, 105, 110, 114, 105, 116, 101, 109, 97, 105, 3, 99, 111, 109, 0, 0, 1, 0, 1, 0, 0, 0, 5, 0, 4, 119, 147, 111, 148, 3, 102, 120, 103, 10, 106, 105, 110, 114, 105, 116, 101, 109, 97, 105, 3, 99, 111, 109, 0, 0, 1, 0, 1, 0, 0, 0, 5, 0, 4, 101, 226, 26, 214, 3, 102, 120, 103, 10, 106, 105, 110, 114, 105, 116, 101, 109, 97, 105, 3, 99, 111, 109, 0, 0, 1, 0, 1, 0, 0, 0, 5, 0, 4, 119, 188, 120, 211, 3, 102, 120, 103, 10, 106, 105, 110, 114, 105, 116, 101, 109, 97, 105, 3, 99, 111, 109, 0, 0, 1, 0, 1, 0, 0, 0, 5, 0, 4, 119, 96, 89, 191, 3, 102, 120, 103, 10, 106, 105, 110, 114, 105, 116, 101, 109, 97, 105, 3, 99, 111, 109, 0, 0, 1, 0, 1, 0, 0, 0, 5, 0, 4, 27, 19, 248, 204, 3, 102, 120, 103, 10, 106, 105, 110, 114, 105, 116, 101, 109, 97, 105, 3, 99, 111, 109, 0, 0, 1, 0, 1, 0, 0, 0, 5, 0, 4, 119, 188, 122, 196, 3, 102, 120, 103, 10, 106, 105, 110, 114, 105, 116, 101, 109, 97, 105, 3, 99, 111, 109, 0, 0, 1, 0, 1, 0, 0, 0, 5, 0, 4, 117, 21, 229, 221, 3, 102, 120, 103, 10, 106, 105, 110, 114, 105, 116, 101, 109, 97, 105, 3, 99, 111, 109, 0, 0, 1, 0, 1, 0, 0, 0, 5, 0, 4, 119, 96, 88, 169, 3, 102, 120, 103, 10, 106, 105, 110, 114, 105, 116, 101, 109, 97, 105, 3, 99, 111, 109, 0, 0, 1, 0, 1, 0, 0, 0, 5, 0, 4, 221, 230, 244, 92, 3, 102, 120, 103, 10, 106, 105, 110, 114, 105, 116, 101, 109, 97, 105, 3, 99, 111, 109, 0, 0, 1, 0, 1, 0, 0, 0, 5, 0, 4, 101, 226, 28, 237, 3, 102, 120, 103, 10, 106, 105, 110, 114, 105, 116, 101, 109, 97, 105, 3, 99, 111, 109, 0, 0, 1, 0, 1, 0, 0, 0, 5, 0, 4, 221, 230, 244, 91, 3, 102, 120, 103, 10, 106, 105, 110, 114, 105, 116, 101, 109, 97, 105, 3, 99, 111, 109, 0, 0, 1, 0, 1, 0, 0, 0, 5, 0, 4, 222, 186, 18, 194, 3, 102, 120, 103, 10, 106, 105, 110, 114, 105, 116, 101, 109, 97, 105, 3, 99, 111, 109, 0, 0, 1, 0, 1, 0, 0, 0, 5, 0, 4, 121, 228, 130, 193, 3, 102, 120, 103, 10, 106, 105, 110, 114, 105, 116, 101, 109, 97, 105, 3, 99, 111, 109, 0, 0, 1, 0, 1, 0, 0, 0, 5, 0, 4, 119, 147, 111, 180, 3, 102, 120, 103, 10, 106, 105, 110, 114, 105, 116, 101, 109, 97, 105, 3, 99, 111, 109, 0, 0, 1, 0, 1, 0, 0, 0, 5, 0, 4, 121, 228, 130, 194, 3, 102, 120, 103, 10, 106, 105, 110, 114, 105, 116, 101, 109, 97, 105, 3, 99, 111, 109, 0, 0, 1, 0, 1, 0, 0, 0, 5, 0, 4, 101, 226, 26, 215, 3, 102, 120, 103, 10, 106, 105, 110, 114, 105, 116, 101, 109, 97, 105, 3, 99, 111, 109, 0, 0, 1, 0, 1, 0, 0, 0, 5, 0, 4, 119, 188, 120, 212, 3, 102, 120, 103, 10, 106, 105, 110, 114, 105, 116, 101, 109, 97, 105, 3, 99, 111, 109, 0, 0, 1, 0, 1, 0, 0, 0, 5, 0, 4, 117, 21, 229, 227, 3, 102, 120, 103, 10, 106, 105, 110, 114, 105, 116, 101, 109, 97, 105, 3, 99, 111, 109, 0, 0, 1, 0, 1, 0, 0, 0, 5, 0, 4, 222, 186, 18, 195, 3, 102, 120, 103, 10, 106, 105, 110, 114, 105, 116, 101, 109, 97, 105, 3, 99, 111, 109, 0, 0, 1, 0, 1, 0, 0, 0, 5, 0, 4, 106, 225, 232, 224, 3, 102, 120, 103, 10, 106, 105, 110, 114, 105, 116, 101, 109, 97, 105, 3, 99, 111, 109, 0, 0, 1, 0, 1, 0, 0, 0, 5, 0, 4, 221, 230, 244, 93, 3, 102, 120, 103, 10, 106, 105, 110, 114, 105, 116, 101, 109, 97, 105, 3, 99, 111, 109, 0, 0, 1, 0, 1, 0, 0, 0, 5, 0, 4, 180, 97, 251, 224, 3, 102, 120, 103, 10, 106, 105, 110, 114, 105, 116, 101, 109, 97, 105, 3, 99, 111, 109, 0, 0, 1, 0, 1, 0, 0, 0, 5, 0, 4, 101, 226, 28, 238, 3, 102, 120, 103, 10, 106, 105, 110, 114, 105, 116, 101, 109, 97, 105, 3, 99, 111, 109, 0, 0, 1, 0, 1, 0, 0, 0, 5, 0, 4, 59, 36, 226, 145, 3, 102, 120, 103, 10, 106, 105, 110, 114, 105, 116, 101, 109, 97, 105, 3, 99, 111, 109, 0, 0, 1, 0, 1, 0, 0, 0, 5, 0, 4, 117, 21, 229, 222, 3, 102, 120, 103, 10, 106, 105, 110, 114, 105, 116, 101, 109, 97, 105, 3, 99, 111, 109, 0, 0, 1, 0, 1, 0, 0, 0, 5, 0, 4, 122, 228, 74, 179, 3, 102, 120, 103, 10, 106, 105, 110, 114, 105, 116, 101, 109, 97, 105, 3, 99, 111, 109, 0, 0, 1, 0, 1, 0, 0, 0, 5, 0, 4, 101, 226, 26, 209, 3, 102, 120, 103, 10, 106, 105, 110, 114, 105, 116, 101, 109, 97, 105, 3, 99, 111, 109, 0, 0, 1, 0, 1, 0, 0, 0, 5, 0, 4, 101, 226, 26, 208, 3, 102, 120, 103, 10, 106, 105, 110, 114, 105, 116, 101, 109, 97, 105, 3, 99, 111, 109, 0, 0, 1, 0, 1, 0, 0, 0, 5, 0, 4, 124, 225, 45, 141, 3, 102, 120, 103, 10, 106, 105, 110, 114, 105, 116, 101, 109, 97, 105, 3, 99, 111, 109, 0, 0, 1, 0, 1, 0, 0, 0, 5, 0, 4, 182, 106, 155, 178, 3, 102, 120, 103, 10, 106, 105, 110, 114, 105, 116, 101, 109, 97, 105, 3, 99, 111, 109, 0, 0, 1, 0, 1, 0, 0, 0, 5, 0, 4, 182, 106, 155, 177, 3, 102, 120, 103, 10, 106, 105, 110, 114, 105, 116, 101, 109, 97, 105, 3, 99, 111, 109, 0, 0, 1, 0, 1, 0, 0, 0, 5, 0, 4, 59, 36, 226, 183, 3, 102, 120, 103, 10, 106, 105, 110, 114, 105, 116, 101, 109, 97, 105, 3, 99, 111, 109, 0, 0, 1, 0, 1, 0, 0, 0, 5, 0, 4, 119, 96, 88, 173, 3, 102, 120, 103, 10, 106, 105, 110, 114, 105, 116, 101, 109, 97, 105, 3, 99, 111, 109, 0, 0, 1, 0, 1, 0, 0, 0, 5, 0, 4, 180, 97, 251, 219, 3, 102, 120, 103, 10, 106, 105, 110, 114, 105, 116, 101, 109, 97, 105, 3, 99, 111, 109, 0, 0, 16, 0, 1, 0, 0, 0, 0, 0, 27, 26, 100, 110, 115, 58, 47, 47, 58, 63, 108}

**Comment by cagedmantis** [comment]
[@neild](https://github.com/neild)

**Comment by rolandshoemaker** [comment]
@gopherbot please open backport issues, this is a PUBLIC track security issue.

**Comment by cherrymui** [comment]
CL submitted. Closing. Thanks.
