### ISSUE TITLE
x/talks: printout of slides does not include code

### ISSUE THREAD

**Issue by rsc** [golang/go#6676]
<pre>Visit <a href="http://talks.golang.org/2013/advconc.slide">http://talks.golang.org/2013/advconc.slide</a> in Chrome
File &gt; Print
Look through preview of printout: the code boxes are empty.
Cancel print.

Arrow-right until you get to a page with code boxes (like page #6).
See that they are filled in.

File &gt; Print
Look through preview of printout: all code boxes, even after that page, now contain code.

It appears that something about flipping through the talk populates the code boxes on
demand? Perhaps this can be done at page load so that printing from slide 1 will work.

Google Chrome    30.0.1599.69 (Official Build 226629) 
OS  Mac OS X 
Blink   537.36 (@158213)
JavaScript  V8 3.20.17.13
Flash    11.9.900.117
User Agent  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML,
like Gecko) Chrome/30.0.1599.69 Safari/537.36
Command Line     /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
-psn_0_20652977 --flag-switches-begin --flag-switches-end
Executable Path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome</pre>

**Comment by ALTree** [comment]
Looks like this is fixed; now (tested with Chromium 55) the code snippets show up in the print preview.
