### ISSUE TITLE
go version response time depends on current directory

### ISSUE THREAD

**Issue by lewijw** [golang/go#66768]
### Go version

go1.22.2 and go1.21.6 - maybe others

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/r/hostname/vol/vol001/u01/userid/.cache/go-build'
GOENV='/r/hostname/vol/vol001/u01/userid/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/r/hostname/vol/vol001/u01/userid/go/pkg/mod'
GONOPROXY=''
GONOSUMDB='*.mycomp.com,mycompsoftware.io'
GOOS='linux'
GOPATH='/r/hostname/vol/vol001/u01/userid/go'
GOPRIVATE=''
GOPROXY='http://goproxy.mycomp.com:3000'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.6'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3402177349=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

\# on a RHEL9 server with a HOME dir that is on an nfs mount
cd /tmp
\# this returns quickly as expected
go version
cd ~
\# this hangs for several minutes
go version

### What did you see happen?

There is a big difference in response times depending on what the current directory is.  Any idea what go version might be doing that would change based on the current directory?

### What did you expect to see?

No difference in response times.

**Comment by seankhliao** [comment]
if the directory is a module then it may involve a version switch.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
