### ISSUE TITLE
crypto/rand: Read argument escapes to heap

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#66779]
Currently, Read is implemented as `io.ReadFull(Reader, b)` which escape analysis can't track, so b escapes to the heap.

This is somewhat annoying, since it causes allocations in paths that could otherwise have none.

It should be possible to rewrite the package so that it doesn't escape on major platforms.

**Comment by mateusz834** [comment]
I' ve been investigating this once, and the remaining problem was that the `rand.Reader` is an interface and cases like:
```
var Reader io.Reader = &someStruct{}
```
will always cause the buffer passed to `rand.Reader.Read` to be escaped.

**Comment by mateusz834** [comment]
But i guess we can make the `rand.Read` function escape-free.
