### ISSUE TITLE
encoding/json: Unmarshaling after marshaling not giving same object 

### ISSUE THREAD

**Issue by DocRitik** [golang/go#66771]
### Go version

1.19.6

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=on
```

### What did you do?

I am converting map[string]interface{} to an user defined object by un-marshaling and marshaling. so for specifically dates format, The value is coming under "data" key but it should be as a value.

### What did you see happen?

So for specifically dates format, The value is coming under "data" key.

### What did you expect to see?

It should be as a value.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
