### ISSUE TITLE
os: document that os.CreateTemp uses permissions 0600

### ISSUE THREAD

**Issue by jech** [golang/go#66784]
### Go version

go version go1.22.1 linux/amd64

### Output of `go env` in your module/workspace:

```shell
Irrelevant, but happy to provide if required.
```

### What did you do?

I checked the documentation for `os.CreateTemp`.  I couldn't find what permissions were used for the file.  I had to check the source in order to find out that it's 0600 (and rightly so).

### What did you see happen?

```
go doc os.CreateTemp | grep -i permission
```

### What did you expect to see?

An indication that the file is not readable by other users, (and that it's guaranteed to remain that way in future Go versions).

**Comment by cagedmantis** [comment]
Tagging owners even though @ianlancetaylor mailed a CL.

[@rsc](https://github.com/rsc) [@robpike](https://github.com/robpike) [@ianlancetaylor](https://github.com/ianlancetaylor) [@bradfitz](https://github.com/bradfitz) [@griesemer](https://github.com/griesemer)
