### ISSUE TITLE
net: compiler warning for _GNU_SOURCE

### ISSUE THREAD

**Issue by rnhaddad** [golang/go#66785]
### Go version

go1.21.5 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE='on'
GOARCH='amd64'
GOBIN=''
GOCACHE='~/go_cache/go-build'
GOENV='~/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='~/gopath/pkg/mod'
GOOS='linux'
GOPATH='~/gopath/'
GOROOT='~/go/1.21.5'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='~/go/1.21.5/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.5'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3819656890=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

Compile CGO with "-D_GNU_SOURCE"

### What did you see happen?

Compiler warning:
<0033706> /sw/packages/xr/go/1.21.5/src/net/cgo_unix_cgo.go:10:9: warning: '_GNU_SOURCE' macro redefined [-Wmacro-redefined]

### What did you expect to see?

The warning is due to:
https://github.com/golang/go/blob/6018ad99a4a951581b2d846a8ccd6f1d4e74fd11/src/net/cgo_unix_cgo.go#L10

The above should have been #ifndef #define, like here:
https://github.com/golang/go/blob/6018ad99a4a951581b2d846a8ccd6f1d4e74fd11/src/runtime/cgo/gcc_stack_unix.c#L7

**Comment by ianlancetaylor** [comment]
Closing as dup of #66325.
