### ISSUE TITLE
log/slog: Source type is public but Record.source() function is private?

### ISSUE THREAD

**Issue by arianvp** [golang/go#66791]
### Go version

go version go1.22.1 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/arian/Library/Caches/go-build'
GOENV='/Users/arian/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/arian/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/arian/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/nix/store/pi4myqk3ssdk2lp6z05h3yywknlr07i5-go-1.22.1/share/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/nix/store/pi4myqk3ssdk2lp6z05h3yywknlr07i5-go-1.22.1/share/go/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.22.1'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/arian/Projects/personal/systemd-project/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/8f/q1dx480905jf7k40b1wbr2_80000gn/T/go-build711937819=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

I am trying to make my own `slog.Handler` for systemd-journald which has support for linking to source code in logs,  so I want to log the [`slog.Source`](https://cs.opensource.google/go/go/+/refs/tags/go1.22.2:src/log/slog/record.go;l=185) for each record. However the `slog.Record` struct does not expose a `Source()` function to create a `slog.Source`.  there is actually _nothing_ in the `slog` package that creates a `slog.Source`

There is a function [`(r *Record) source()`](https://cs.opensource.google/go/go/+/refs/tags/go1.22.2:src/log/slog/record.go;l=218) but it's private. Is this a typo? I'd expect this function to be public. Why else would the type be public?

### What did you see happen?

There is no `r.Source()` method

### What did you expect to see?

there is a `r.Source()` method

**Comment by seankhliao** [comment]
The package example demonstrates where Source is used: https://pkg.go.dev/log/slog#hdr-Writing_a_handler

**Comment by arianvp** [comment]
Ah I guess I can just use `r.PC` which _is_ public in my Handler. Nevermind
