### ISSUE TITLE
x/pkgsite: package removal request for old domains

### ISSUE THREAD

**Issue by mrmelon54** [golang/go#66799]
The following domains currently redirect to some of the new source code and any broken links are deprecated unused projects. I wish to remove these redirects (from my server) and the documentation from the package site.

All packages under the following domains should be removed:
- tea.melonie54.xyz
- codehub.onpointcoding.net
- code.mrmelon54.xyz
- snow.mrmelon54.xyz

I believe there is 35 packages available under those domains as of 2024 / 04 / 09 - [(source)](https://gist.github.com/MarvinJWendt/154c6f56552df30dab7cb9352338879b)

**Comment by adonovan** [comment]
When we're requested to remove packages hosted by GitHub, it's easy to tell that the requestor and the repository owner are the same person. Can you provide us evidence that you are the owner of these domains? Unfortunately the fact that your GitHub ID is a segment of some of the domain names is not sufficient, as the two are independent.

One possibility would for you to alter the contents of each of these domains (e.g. add a file or redirect endpoint) to mention this issue. That would prove that someone with write access to the domain has consented to its removal from our index.

**Comment by mrmelon54** [comment]
Yep I was prepared for this, these URLs all redirect to this issue as proof of ownership:
- https://tea.melonie54.xyz/change
- https://codehub.onpointcoding.net/change
- https://code.mrmelon54.xyz/change
- https://snow.mrmelon54.xyz/change

Please note my new git server is hosted at "code.mrmelon54.com" and all packages listed there should remain in the package database.

**Comment by adonovan** [comment]
Great! (I checked the source of the Markdown to make sure the markup wasn't deceiving me. Why is security so hard?)

Deletion pending.  Please allow a few days.
