### ISSUE TITLE
crypto/internal/mlkem768: TestPQCrystalsAccumulated fails on linux/s390x

### ISSUE THREAD

**Issue by dmitshur** [golang/go#66804]
[CL 550215](https://go.dev/cl/550215) added a new package. One of its tests, `TestPQCrystalsAccumulated`, is failing on the linux/s390x port:

```
--- FAIL: TestPQCrystalsAccumulated (0.07s)
    mlkem768_test.go:341: got a29fd28288bf8b0ec26692d56eab5cb44c57fdc7e378133b81b83c4c33c6bb07, expected 8d0c478ead6037897a0da6be21e5399545babf5fc6dd10c061c99b7dee2bf0dc
FAIL
```

(See https://build.golang.org/log/c33fc12dce181e683b2c21e15d9775633d804637.)

This doesn't seem to happen on other Go ports.

CC @golang/s390x.

**Comment by FiloSottile** [comment]
There is no use of unsafe or assembly in that package, so it doesn't look right away as something wrong in crypto/internal/mlkem768.

**Comment by mundaym** [comment]
I think this issue should now be fixed when golang.org/x/crypto is re-vendored.
