### ISSUE TITLE
Reconsider issue #226 - recurse anonymous function / declare named closure

### ISSUE THREAD

**Issue by qgates** [golang/go#66806]
Request a fix for issue #226. The workaround, though straightforward, is unnecessary code and obtuse for any reader unfamiliar  with this edge case in go's order of evaluation.

In sum, given a situation like: 

```go
var recur func()
recur = func() {
    recur()
}
```
We shouldn't need to declare `var recur func()` for the block to be valid:
```go
recur := func() {
    recur()
}
```
Named nested function declarations might be considered although this may not be idiomatic in go (per [this comment on issue #226](https://github.com/golang/go/issues/226#issuecomment-66048645) from the original issue). For example:
```go
func Outer() {
  func recur() {
    recur()
  }
}
```

**Comment by seankhliao** [comment]
I don't see any new information that would cause us to reconsider this decision.
