### ISSUE TITLE
x/pkgsite: package removal request for some deleted repos

### ISSUE THREAD

**Issue by razor-87** [golang/go#66800]
What is the path of the package that you would like to have removed?
github.com/razor-87/simple-websocket
github.com/razor-87/hh
gitlab.com/razor87/fabrique

Are you the owner of this package?
Yes.

What is the reason that you could not retract this package instead?
The related repository has been deleted.

Thanks in advance.

**Comment by adonovan** [comment]
Done. Please allow a few days for the config changes to take effect.
