### ISSUE TITLE
x/tools/go/analysis/passes/nilness: bogus "impossible condition: non-nil == nil" that is actually possible

### ISSUE THREAD

**Issue by GottfriedHerold** [golang/go#66835]
### Go version

go version go1.21.3 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/gottfried/.cache/go-build'
GOENV='/home/gottfried/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/gottfried/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/gottfried/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/home/gottfried/sdk/go1.21.3'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/home/gottfried/sdk/go1.21.3/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.3'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/gottfried/Bandersnatch/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2158884728=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

The following minimal example function
```
func F[T error](x T) {
	if any(x) == nil {
		panic(0) // or whatever
	}
}
```
triggers a "impossible condition: non-nil == nil (nilness) cond" warning by the nilness analyser.
I'm using vscode with its own gopls integration (which, as opposed to calling go vet (by default, unless opted-in) actually performs nilness analysis, as far as I understand).
Of course, the nilness check is actually not bogus:
Calling `F[error](nil)` will happily run panic(0).
I suspect the analyser somehow thinks T is a non-interface type.

### What did you see happen?

An impossible condition: non-nil == nil nilness (cond) warning flagged by my IDE

### What did you expect to see?

no warning.

**Comment by oakad** [comment]
There's an additional situation when this warning happens:

```
var myPtr *someStruct

// code which may or may not set myPtr

// bogus impossible condition nil != nil
if myPtr != nil {
}
```

**Comment by timothy-king** [comment]
@oakad Can you provide more details than that? A minimized reproducer is usually best.

**Comment by oakad** [comment]
That's what I'm getting in my VSCode window. How do I package it?

**Comment by timothy-king** [comment]
A minimized copy of the function (or the relevant snippet) is usually best. This can be shared on a github issue or go playground. Along with the diagnostic message and version info.
