### ISSUE TITLE
cmd/go/internal/work: -overlay docs incorrectly exclude `go test`

### ISSUE THREAD

**Issue by ramosbugs** [golang/go#66845]
### Go version

1.22.1

### Output of `go env` in your module/workspace:

```shell
N/A
```

### What did you do?

N/A

### What did you see happen?

N/A

### What did you expect to see?

46fa8afca61cf60c64f006685cd6cbb94e080118 introduced support for the `-overlay` flag to `go test` as of Go 1.17 (see #44946).

However, the docs still state that "overlays will not appear when binaries and tests are run through go run and go test respectively.": https://github.com/golang/go/blob/d5138e580c2404f2b8f03d2e1e32b2226cb6bbbc/src/cmd/go/internal/work/build.go#L163-L173

 I believe that's specifically what 46fa8afca61cf60c64f006685cd6cbb94e080118 changed with respect to `go test` (I'm not sure about `go run`).

**Comment by cherrymui** [comment]
> "overlays will not appear when binaries and tests are run through go run and go test respectively."

I think this meant to say that when the test binary _runs_ (not when the test is built), the overlaid file is not present. I.e. if the test binary itself wants to read foo_test.go during the test execution, it sees the original file, not the overlaid file.

I think this works as intended. @matloob can correct me if I'm mistaken.

**Comment by matloob** [comment]
Yes, it's exactly as Cherry wrote.
