### ISSUE TITLE
proposal: inet: implement sctp protocol

### ISSUE THREAD

**Issue by drv1234** [golang/go#66847]
### Proposal Details

hi,
sctp protocol is missing from the core protocols.
There is an project implementing it but it seems will never be fix this critical issue:
https://github.com/ishidawataru/sctp/issues/60

and the implementation does not fit into the golang standard "net" architecture.

Please consider it to implement it as a "supported protocol by default".
Thank you

**Comment by seankhliao** [comment]
Duplicate of #22191
