### ISSUE TITLE
cmd/build: -trimpath not working completely

### ISSUE THREAD

**Issue by hyadav5** [golang/go#66849]
### Go version

go version go1.16.15b7p1 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user/go/pkg/mod"
GONOPROXY="gitlab.eng.company.com,github.com/google/martian"
GONOSUMDB="*.eng.company.com"
GOOS="linux"
GOPATH="/home/user/go"
GOPRIVATE="gitlab.eng.company.com,github.com/google/martian"
GOPROXY="https://build-artifactory.eng.company.com/srp-mds-go-remote"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.15b7p1"
GCCGO="gccgo"
AR="ar"
CC="x86_64-vmk-linux-gnu-gcc"
CXX="/build/mts/release/bora-23244397/compcache/cayman_esx_toolchain/ob-16111630/linux-centos72-gc32/usr/bin/x86_64-vmk-linux-gnu-g++"
CGO_ENABLED="1"
GOMOD="/home/user/dev/dev/go/src/project/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2531685105=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

I have compiled a Go binary using the below flags and it has a runtime exception and dumped the below Stacktrace.
My GOPATH = `/home/hemant/dev/go/src`
My compiler flags while building are: `-gcflags=-trimpath=$GOPATH -trimpath -asmflags=-trimpath=$GOPATH -trimpath`
Stacktrace is below:

```
Apr 15 09:56:59 10-79-108-22 system-health[3923528]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x144efd2]
Apr 15 09:56:59 10-79-108-22 system-health[3923528]: goroutine 1 [running]:`
Apr 15 09:56:59 10-79-108-22 system-health[3923528]: github.com/go-redis/redis.(*cmdable).HGetAll(0xc002cc78b0, 0x0, 0x0, 0x0)
Apr 15 09:56:59 10-79-108-22 system-health[3923528]: github.com/go-redis/redis.(*cmdable).HGetAll(0xc002cc78b0, 0x0, 0x0, 0x0)
Apr 15 09:56:59 10-79-108-22 system-health[3923528]:         github.com/go-redis/redis@v6.13.2+incompatible/commands.go:923 +0xd2
Apr 15 09:56:59 10-79-108-22 system-health[3923528]: controller/systemhealth.someOtherFunc(...)
Apr 15 09:56:59 10-79-108-22 system-health[3923528]:         controller/systemhealth/system_health.go:676
Apr 15 09:56:59 10-79-108-22 system-health[3923528]: controller/systemhealth.someFunction(...)
Apr 15 09:56:59 10-79-108-22 system-health[3923528]:         controller/systemhealth/system_health.go:680
Apr 15 09:56:59 10-79-108-22 system-health[3923528]: controller/systemhealth.ServiceInitialize()
Apr 15 09:56:59 10-79-108-22 system-health[3923528]:         controller/systemhealth/system_health.go:685 +0x6b
Apr 15 09:56:59 10-79-108-22 system-health[3923528]: main.main()
Apr 15 09:56:59 10-79-108-22 system-health[3923528]:         /home/hemant/dev/go/src/controller/go-controller.go:743 +0x231e
```

### What did you see happen?

I have an issue where the -trimpath is not removing the GOPATH `/home/hemant/dev/go/src/` from the last line of the stacktrace.
```
Apr 15 09:56:59 10-79-108-22 system-health[3923528]:         /home/hemant/dev/go/src/controller/go-controller.go:743 +0x231e
```

### What did you expect to see?

GOPATH should have been removed from the last line also.
Also side question: Is it possible to NOT expose directory path also and have mere filename ?

**Comment by Jorropo** [comment]
[This is a very old version of go](https://endoflife.date/go), does that works with one of the maintained release (1.22.2 or 1.21.9) ?

It would also help if you give a complete build command, or repro. I guess you might have pointed `go build` at files instead of a folder ?

**Comment by hyadav5** [comment]
Yes @Jorropo, I have ran the go build on a file, but I think this might be same even for the folder as well.
Unfortunately, I cannot upgrade the go version as its a legacy product.
```
COMMAND cd ${CMAKE_CURRENT_SOURCE_DIR} && env CC=gcc CXX=g++ GOPATH=${CMAKE_SOURCE_DIR}/go go build -mod vendor -ldflags "-X google.golang.org/protobuf/reflect/protoregistry.conflictPolicy=warn" -gcflags=-trimpath=$GOPATH -trimpath -asmflags=-trimpath=$GOPATH -trimpath go-controller.go
```

**Comment by Jorropo** [comment]
Ah, the problem is that you set `-gcflags=-trimpath=$GOPATH` and `GOPATH="/home/user/go"` while your project is stored at `/home/hemant/dev/go` I guess `user` → `hemant` is not real, but `$HOME/go` vs `$HOME/dev/go` is real.

Everything works fine for me when I set `-trimpath` once (afaik you shouldn't need to set `-gcflags` nor `-asmflags` manually, nor you need to set `-trimpath` twice).

**Comment by Jorropo** [comment]
We might be able to error on this (`-trimpath` set too many times) or interpret it set multiple times as each path to be trimmed, but I don't think that worth breaking the cli here.
Can reopen if someone else feels strongly.

**Comment by hyadav5** [comment]
@Jorropo : just plain simple `-trimpath` worked. Thank you very much.
