### ISSUE TITLE
x/website: Add an example for arrays with the `[...]T{a, b, c, d}` syntax

### ISSUE THREAD

**Issue by adriancuadrado** [golang/go#66851]
### What is the URL of the page with the issue?

https://go.dev/tour/moretypes/6

### What is your user agent?

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

### Screenshot

![image](https://github.com/golang/go/assets/29214635/8c6115e9-0123-4b1b-9ffd-748b12e1be59)

### What did you do?

I read [this article](https://go.dev/blog/slices-intro#arrays) and found this code snippet:
```go
b := [...]string{"Penn", "Teller"}
```

### What did you see happen?

It is equivalent to this:
```go
b := [2]string{"Penn", "Teller"}
```
but it's more convenient because you don't have to count the number of elements since that is done automatically for you by the compiler.

### What did you expect to see?

I think it would be awesome to include this feature in [A Tour of Go](https://go.dev/tour/). More specifically [here](https://go.dev/tour/moretypes/6).

**Comment by seankhliao** [comment]
please file this on the your repo https://github.com/golang/tour/issues
