### ISSUE TITLE
x/pkgsite: package removal request for https://github.com/deliveroo/migrate

### ISSUE THREAD

**Issue by michael-huxtable-deliveroo** [golang/go#66854]
### What is the path of the package that you would like to have removed?

https://github.com/deliveroo/migrate

### Are you the owner of this package?

Yes, I am currently a software engineer at Deliveroo acting with the approval of my organization.

### What is the reason that you could not retract this package instead?

Currently there are only old versions of this package listed publicly. This repository has been private for some time and new versions have only been published internally. To avoid confusion we would like to remove all current versions from pkgsite.

**Comment by ansaba** [comment]
Package removed.
