### ISSUE TITLE
cmd/compile: enable type-checking using the new Alias types

### ISSUE THREAD

**Issue by griesemer** [golang/go#66864]
Reminder issue that the compiler currently sets `GODEBUG=gotypesalias=0` to avoid a panic during bootstrap (make.bash).
See `cmd/compile/internal/noder/irgen.go:92`.

**Comment by cherrymui** [comment]
@griesemer this is marked as a release blocker. Any update on this? Thanks.

**Comment by griesemer** [comment]
The compiler's use of Alias types is still disabled due to #66873.
This is a high priority item at this point.

**Comment by griesemer** [comment]
#66873 was fixed with https://go.dev/cl/585399 which also enabled the use of Alias types in the compiler; i.e., this is now fixed.
