### ISSUE TITLE
skip a specific word "image.jpg" in the below regex (.*?)(jpg|gif|doc), as go lang is not supporting negative lookahead, so how can we achieve this in go lang?

### ISSUE THREAD

**Issue by sarathpolisetty** [golang/go#66882]

**Comment by randall77** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
