### ISSUE TITLE
x/mobile: Is gomobile still maintained?

### ISSUE THREAD

**Issue by tri-bao** [golang/go#66919]
Hello,

We plan to use gomobile to build a shared SDK for our mobile app and use it with binding, mainly for networking stack. However, look like there is little to no activities on gomobile repo. I would like to know if gomobile is still maintained and is a viable solution.

Thanks

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
