### ISSUE TITLE
x/pkgsite: package removal request for github.com/jfrech/tbp

### ISSUE THREAD

**Issue by jfrech** [golang/go#66920]
### What is the path of the package that you would like to have removed?

github.com/jfrech/tbp

### Are you the owner of this package?

Yes.

### What is the reason that you could not retract this package instead?

I want this package's cache trace expunged. The repository has been deleted.

**Comment by findleyr** [comment]
Done, and should take effect within the next few hours. Please comment if not.

**Comment by jfrech** [comment]
@findleyr The package entry appears to have vanished. Thank you very much.
