### ISSUE TITLE
x/net/websocket: Document goroutine safety of websocket.Conn

### ISSUE THREAD

**Issue by tuxychandru** [golang/go#6692]
<pre>The documentation of websocket.Conn[1] does not state that it is safe to share it among
multiple goroutines. From the implementation (rio and wio mutexes), it appears that it
is safe.

It'll be convenient if this is explicitly stated like in the case of net.Conn in
stdlib[2].

[1] - <a href="http://godoc.org/code.google.com/p/go.net/websocket#Conn">http://godoc.org/code.google.com/p/go.net/websocket#Conn</a></pre>

**Comment by mikioh** [comment]
Fixed: https://github.com/golang/net/commit/3e5cd1ed149001198e582f9d3f5bfd564cde2896
