### ISSUE TITLE
x/tools/gopls: document how to enable non-default staticcheck checks

### ISSUE THREAD

**Issue by hyangah** [golang/go#66936]
Staticcheck checks can be configured with gopls's `analyses` settings, but this is not obvious from the current analyzer doc (https://github.com/golang/tools/blob/master/gopls/doc/analyzers.md). Settings doc has a link to the Staticcheck's official doc page (https://github.com/golang/tools/blob/master/gopls/doc/settings.md#staticcheck-bool), but how to enable/disable checks is not obvious.

**Comment by adonovan** [comment]
This was fixed by https://go.dev/cl/583316.
