### ISSUE TITLE
x/pkgsite: Add unit test to cover cache bypass by cookie

### ISSUE THREAD

**Issue by behnambm** [golang/go#66947]
### What is the URL of the page with the issue?

https://github.com/golang/pkgsite/blob/ddbbf7b6745ea937506c52fefb4d4688b5f0665e/internal/middleware/caching.go#L148

### What is your user agent?

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

### What did you do?

After running the tests I noticed that the cache middleware tests do not cover bypassing the cache by cookie. 

### What did you see happen?

![image](https://github.com/golang/go/assets/26994700/e8433fdf-5c50-4ac7-b89d-be363ae7a825)

### What did you expect to see?

I propose to contribute a unit test covering the cache middleware bypass functionality with cookie settings in `golang.org/x/pkgsite/internal/middleware/caching.go`. This addition will elevate the test coverage from 73% to 75.7% and address an important yet uncovered part of the codebase. 

Looking forward to collaborating on this enhancement.

**Comment by findleyr** [comment]
My guess is that this behavior is tested by integration tests, though I don't know.
I'm inclined to decline adding additional unit tests at this point, as the project is relatively stable, and unit tests are most useful during periods of active development. At this point, the cognitive overhead to review a unit test may not be worthwhile.

We aren't particularly concerned about unit test coverage percentage at this phase in the project's lifecycle.

So I don't encourage acting on this now. I'll defer to @jba if he would like to review a contribution here.

**Comment by jba** [comment]
I agree with @findleyr. Thanks for your effort, though.
