### ISSUE TITLE
go: errors parsing go.mod

### ISSUE THREAD

**Issue by aliihsankamil** [golang/go#66961]
### Go version

go version go1.22.0 windows/amd64

### Output of `go env` in your module/workspace:

```shell
module blueprint-example

go 1.22.0

replace geometry-lib => D:/DATA ALI/2 DOKUMEN\PELATIHAN/Enigma Camp/Golang/GOLANG DATABASE/geometry-lib
```

### What did you do?

go: errors parsing go.mod:
go.mod:5: usage: replace module/path [v1.2.3] => other/module v1.4
         or replace module/path [v1.2.3] => ../local/directory

### What did you see happen?

Why?

### What did you expect to see?

I want to replace module

**Comment by seankhliao** [comment]
I believe the file separator is `\` on windows.
Is `2 DOKUMEN\PELATIHAN` a literal string with a `\` or 2 directories?

**Comment by aliihsankamil** [comment]
ouh thankyou, but when i change i have error to

**Comment by go101** [comment]
the replace local path should start with `./` or `../`.
