### ISSUE TITLE
gdb: upgrade to be python 3 compatible

### ISSUE THREAD

**Issue by LukeMauldin** [golang/go#6698]
<pre>What steps will reproduce the problem?
If possible, include a link to a program on play.golang.org.
1. Build a Golang program and launch is with GDB.  Using Ubuntu 13.10, GDB 7.6.1. 
Golang version 1.2rc2.  Note, I have go installed in /opt/go and I have a symbolic link
linking /usr/local/go to /opt/go

What is the expected output?
Debugging to work correctly

What do you see instead?
luke@luke-laptop:~/projects/goexternal/src/tf/meetingmessage$ gdb ./meetingmessage 
GNU gdb (GDB) 7.6.1-ubuntu
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later &lt;<a href="http://gnu.org/licenses/gpl.html&gt">http://gnu.org/licenses/gpl.html&gt</a>;
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type &quot;show copying&quot;
and &quot;show warranty&quot; for details.
This GDB was configured as &quot;x86_64-linux-gnu&quot;.
For bug reporting instructions, please see:
&lt;<a href="http://www.gnu.org/software/gdb/bugs/&gt">http://www.gnu.org/software/gdb/bugs/&gt</a>;...
Reading symbols from
/home/luke/projects/goexternal/src/tf/meetingmessage/meetingmessage...done.
  File &quot;/opt/go/src/pkg/runtime/runtime-gdb.py&quot;, line 358
    print s, ptr['goid'], &quot;%8s&quot; % sts[long((ptr['status']))], blk.function
          ^
SyntaxError: invalid syntax
(gdb)</pre>

**Comment by mwhudson** [comment]
To answer minux's question from two years ago, yes, this seems to be fixed.
