### ISSUE TITLE
cmd/link: panic: machorelocsect: size mismatch

### ISSUE THREAD

**Issue by luhring** [golang/go#66993]
### Go version

go version go1.22.2 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='arm64'
GOBIN='/Users/dan/go/bin'
GOCACHE='/Users/dan/Library/Caches/go-build'
GOENV='/Users/dan/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/dan/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/dan/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/Users/dan/homebrew/Cellar/go/1.22.2/libexec'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/Users/dan/homebrew/Cellar/go/1.22.2/libexec/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.22.2'
GCCGO='gccgo'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/pz/h07rtjmd4mv4wpnr5st5q1480000gn/T/go-build3905791175=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

Using GoLand, which I understand to use delve under the hood (see GoLand [ticket](https://intellij-support.jetbrains.com/hc/en-us/community/posts/18472619719826-Compiling-error-on-debug) where someone else is hitting this same issue), I attempted to start a debug session for the Trivy project: https://github.com/aquasecurity/trivy, running the program at `./cmd/trivy`.

I'm able to reproduce this _without GoLand_, too, via:

```
dlv debug ./cmd/trivy/main.go
```

I'm running on macOS 14.4.1, on an M1 processor.

cc: @knqyf263 in case this interests you!

### What did you see happen?

```console
$ dlv debug ./cmd/trivy/main.go
 # command-line-arguments
runtime.textsectionmap: reloc 1 (R_ADDR) to non-macho symbol runtime.text.1 type=1 (STEXT)
runtime.textsectionmap: unsupported obj reloc 1 (R_ADDR)/8 to runtime.text.1
panic: machorelocsect: size mismatch

goroutine 3363 [running]:
cmd/link/internal/ld.machorelocsect(0x14000118000, 0x14000dfee00, 0x1401935b9e0, {0x140227d0000?, 0x14000000002e9bed?, 0x102d54800?})
        cmd/link/internal/ld/macho.go:1256 +0x214
cmd/link/internal/ld.relocSectFn.func1.1()
        cmd/link/internal/ld/asmb.go:203 +0x4c
created by cmd/link/internal/ld.relocSectFn.func1 in goroutine 1
        cmd/link/internal/ld/asmb.go:202 +0x1e4
exit status 1
```

(Note: I also had to temporarily adjust Trivy's `go.mod` to use `toolchain go1.22.2` so it matched my installed toolchain.)

### What did you expect to see?

I expected to be able to start a debugging session successfully, via either dlv or GoLand.

(I can't reproduce this issue using `go1.21.9`, FWIW.)

**Comment by knqyf263** [comment]
@luhring Thanks for raising!

We've also faced the same issue and looked into it. It's even easier to reproduce it.

```
$ go build -gcflags "all=-N -l" github.com/aquasecurity/trivy/cmd/trivy
# github.com/aquasecurity/trivy/cmd/trivy
runtime.textsectionmap: reloc 1 (R_ADDR) to non-macho symbol runtime.text.1 type=1 (STEXT)
runtime.textsectionmap: unsupported obj reloc 1 (R_ADDR)/8 to runtime.text.1
panic: machorelocsect: size mismatch

goroutine 3226 [running]:
cmd/link/internal/ld.machorelocsect(0x14000118000, 0x14001046700, 0x1401700b140, {0x1402a95c000?, 0x0?, 0x1030007a0?})
        /opt/homebrew/Cellar/go/1.22.1/libexec/src/cmd/link/internal/ld/macho.go:1256 +0x20c
cmd/link/internal/ld.relocSectFn.func1.1()
        /opt/homebrew/Cellar/go/1.22.1/libexec/src/cmd/link/internal/ld/asmb.go:203 +0x4c
created by cmd/link/internal/ld.relocSectFn.func1 in goroutine 1
        /opt/homebrew/Cellar/go/1.22.1/libexec/src/cmd/link/internal/ld/asmb.go:202 +0x1e4
```

We tried Go 1.22.0, 1.22.1, and 1.22.2, but the same error occurred with all of them. However, `CGO_ENABLED=0` works around it.

```
CGO_ENABLED=0 go build -gcflags "all=-N -l" github.com/aquasecurity/trivy/cmd/trivy
```

**Comment by luhring** [comment]
Awesome, thanks for the added context! 🙌

**Comment by whhe** [comment]
I met the same error when building [bytebase](https://github.com/bytebase/bytebase) by running `sh scripts/build_bytebase.sh` with `CGO_ENABLED=1`.

```
Step 2 - building Bytebase backend...
# command-line-arguments
runtime.textsectionmap: reloc 1 (R_ADDR) to non-macho symbol runtime.text.1 type=1 (STEXT)
runtime.textsectionmap: unsupported obj reloc 1 (R_ADDR)/8 to runtime.text.1
panic: machorelocsect: size mismatch

goroutine 205 [running]:
cmd/link/internal/ld.machorelocsect(0x14000114000, 0x140063ae7e0, 0x1400006c480, {0x14024dd8000?, 0x110000000058630c?, 0x1045d47a0?})
        /opt/homebrew/Cellar/go/1.22.2/libexec/src/cmd/link/internal/ld/macho.go:1256 +0x214
cmd/link/internal/ld.relocSectFn.func1.1()
        /opt/homebrew/Cellar/go/1.22.2/libexec/src/cmd/link/internal/ld/asmb.go:203 +0x4c
created by cmd/link/internal/ld.relocSectFn.func1 in goroutine 1
        /opt/homebrew/Cellar/go/1.22.2/libexec/src/cmd/link/internal/ld/asmb.go:202 +0x1e4
```

**Comment by FunTimeCoding** [comment]
In one of my projects, I was able to narrow down this error happening as soon as I use https://github.com/aws/aws-sdk-go-v2 in go 1.22+.

My workarounds are to exclude the library and all its usages via build flag, or to run the program in a container, which is obviously in Linux VM.

I also investigated for a while and thought maybe I have some old linked library somewhere.

Thank you for creating this issue.

**Comment by d-bytebase** [comment]
@randall77 would you help take a look? Thanks!

**Comment by randall77** [comment]
@cherrymui This looks like a linker issue. That failing check is off by 8.

**Comment by cherrymui** [comment]
Thanks for reporting. The direct problem is `runtime.textsectionmap: reloc 1 (R_ADDR) to non-macho symbol runtime.text.1 type=1 (STEXT)`, that is, an (8-byte) relocation failed to apply, which causes a size mismatch by 8. The underlying issue is that the text section-split-code path doesn't interact well with the plugin-enabled code path. If the code doesn't (transitively) import the plugin package, it would work fine, but it does. I'll work on a fix.

**Comment by d-bytebase** [comment]
> Thanks for reporting. The direct problem is `runtime.textsectionmap: reloc 1 (R_ADDR) to non-macho symbol runtime.text.1 type=1 (STEXT)`, that is, an (8-byte) relocation failed to apply, which causes a size mismatch by 8. The underlying issue is that the text-section-split code path doesn't interact well with the plugin-enabled code path. If the code doesn't (transitively) import the plugin package, it would work fine, but it does. I'll work on a fix.

Wish I could still send Kudos for your help. Thank you!

**Comment by d-bytebase** [comment]
Also curious why it happens to Darwin/arm64 only?

**Comment by cherrymui** [comment]
> Also curious why it happens to Darwin/arm64 only?

Because on ARM64 the C linker has a section size limit, so we need to split text sections. There is no such limit on AMD64. As for other OSes, the ELF linking is just different from Mach-O linking.

**Comment by thanm** [comment]
@d-bytebase  Based on the error message the problem you're reporting is not related to the one described here. Would you please open another issue? Thanks. Be sure to include details instructions on how to reproduce.

**Comment by d-bytebase** [comment]
> @d-bytebase Based on the error message the problem you're reporting is not related to the one described here. Would you please open another issue? Thanks. Be sure to include details instructions on how to reproduce.

Thanks. I figured it out as it has nothing to do with golang but clang, simply put macos/arm64 is too bad. Golang's linker improvement is exactly solving this kinds of issue, and I found a way out.

**Comment by cherrymui** [comment]
@gopherbot please backport this to Go 1.22. This causes build failures on darwin/arm64.
