### ISSUE TITLE
proposal: sync: On changing the sync.Map implementation to a Ctrie Map (HashTrieMap)

### ISSUE THREAD

**Issue by aimuz** [golang/go#67009]
### Proposal Details

It's not a proposal, it's more of a discussion. I found some interesting changes in the recent commit, I observed the addition of a concurrent/HashTrieMap implementation which is internal.

I think sync.Map should have better performance by way of a HashTrieMap implementation? I didn't do a full test. I just think it has a smaller lock range and doesn't look like the existing sync.Map implementation. Map, which locks the entire map during writes.

The main use case for sync.Map is to solve the problem of concurrent reads and writes. HashTrieMap is designed to be thread-safe and lock-free. So I think using HashTrieMap to implement sync.

As far as I know, there is already a community implementation of sync.Map based on the HashTrieMap implementation

https://github.com/puzpuzpuz/xsync

(Please feel free to correct me if there are any questions, my understanding is not complete)

**Comment by seankhliao** [comment]
closing since we don't use the issue tracker for general discussions.
