### ISSUE TITLE
html/template: truncated output for URL

### ISSUE THREAD

**Issue by robpike** [golang/go#6701]
<pre>Reported at tip with 6g

changeset:   18385:db021a4c7b4a

This program:

======
package main

import (
	&quot;html/template&quot;
	&quot;os&quot;
)

func main() {
	template.Must(template.New(&quot;test&quot;).Parse(text)).Execute(os.Stdout, nil)
}

const text = `&lt;!DOCTYPE html&gt;
&lt;html&gt;
  &lt;body&gt;
    &lt;script id=&quot;test&quot; type=&quot;html/template&quot;&gt;
      &lt;a href=&quot;<a href="https://twitter.com/share&quot">https://twitter.com/share&quot</a>;&gt;&lt;/a&gt;
      &lt;a href=&quot;<a href="https://www.facebook.com/sharer/sharer.php&quot">https://www.facebook.com/sharer/sharer.php&quot</a>;&gt;&lt;/a&gt;
      &lt;a href=&quot;<a href="https://plus.google.com/share&quot">https://plus.google.com/share&quot</a>;&gt;&lt;/a&gt;
    &lt;/script&gt;
  &lt;/body&gt;
&lt;/html&gt;
`
======

Produces this output:

======
&lt;!DOCTYPE html&gt;
&lt;html&gt;
  &lt;body&gt;
    &lt;script id=&quot;test&quot; type=&quot;html/template&quot;&gt;
      &lt;a href=&quot;<a href="https://twitter.com/share&quot">https://twitter.com/share&quot</a>;&gt;&lt;/a&gt;
      &lt;a href=&quot;<a href="https://www.facebook.com/sharer/sharer.php&quot">https://www.facebook.com/sharer/sharer.php&quot</a>;&gt;&lt;/a&gt;
      &lt;a href=&quot;https:
    &lt;/script&gt;
  &lt;/body&gt;
&lt;/html&gt;
======

Notice that the third URL is truncated. Deleting either of the other two from the input
restores the final one.</pre>

**Comment by nodirt** [comment]
[CL 14336](https://go-review.googlesource.com/#/c/14336/) would fix this bug, as a part of fixing its duplicate #12149. It does not treat `script` tag content as JS if the tag has `type` attribute != `"text/javascript"`. I can expand it to `"text/vbscript"`, etc
