### ISSUE TITLE
encoding/binary: fix NativeEndian == BigEndian || NativeEndian == LittleEndian

### ISSUE THREAD

**Issue by dolmen** [golang/go#67026]
This is a follow-up to #57237.

In comment https://github.com/golang/go/issues/57237#issuecomment-1402888111 @robpike implied that the value of `binary.NativeEndian` should be comparable with `==` to the `binary.BigEndian` and `binary.LittleEndian` values.
> 

Unfortunately in the current implementation added in Go 1.21, comparisons with both values fail because the type of `binary.NativeEndian` is different of both values because of the use of an embedded type:
```
type nativeEndian struct {
        bigEndian
}
```

### Proposed fix

Define the type of `binary.NativeEndian` using a type alias instead of type embedding.

```
type nativeEndian = bigEndian

var NativeEndian nativeEndian
```

### Go version

go version go1.22.2 darwin/arm64

### What did you do?

https://go.dev/play/p/niinanpbVuC
```go
func TestEqual(t *testing.T) {
	nbOK := 0
	for _, bo := range []binary.ByteOrder{
		binary.BigEndian,
		binary.LittleEndian,
	} {
		t.Logf("Native == %v: %v", bo, binary.NativeEndian == bo)
		if binary.NativeEndian == bo {
			nbOK++
		}
	}
	if nbOK != 1 {
		t.Error("1 equal expected, got", nbOK)
	}
}
```

### What did you see happen?

```
=== RUN   TestEqual
    prog_test.go:14: NativeEndian == BigEndian: false
    prog_test.go:14: NativeEndian == LittleEndian: false
    prog_test.go:20: 1 equal expected, got 0
--- FAIL: TestEqual (0.00s)
FAIL
```

### What did you expect to see?

```
=== RUN   TestEqual
    compile_test.go:27: NativeEndian == BigEndian: false
    compile_test.go:27: NativeEndian == LittleEndian: true
--- PASS: TestEqual (0.00s)
PASS
```

**Comment by seankhliao** [comment]
As they are different types, equality isn't possible (nor is it generally expected of unexported types).

**Comment by dolmen** [comment]
@seankhliao My point is that they should not be different types, but instead defined using a type alias.

Cc: @tklauser

**Comment by dolmen** [comment]
@seankhliao Please review [CL581655](https://go-review.googlesource.com/c/go/+/581655).

**Comment by dolmen** [comment]
Cc: @randall77 because https://github.com/golang/go/issues/57237#issuecomment-1546764382

**Comment by dolmen** [comment]
I realize that my `TestEqual` in the description is flawed: the `bo` is of type `binary.ByteOrder` (an interface) so the comparaison happens at runtime.

However for `binary.NativeEndian == binary.BigEndian`, the type are resolved at compile time and a mismatch is detected like with `binary.LittleEndian == binary.BigEndian`:
```
invalid operation: binary.LittleEndian == binary.BigEndian (mismatched types binary.littleEndian and binary.bigEndian)
```

So this issue deserved to be closed.
