### ISSUE TITLE
reflect: It does not print correct method set

### ISSUE THREAD

**Issue by leabit** [golang/go#67034]
### Go version

go version go1.22.0 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/leabit/.cache/go-build'
GOENV='/home/leabit/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/leabit/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/leabit/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22.0'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='0'
GOMOD='/home/leabit/goprojects/ceogolang/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1848736934=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

I made a package `mypackage` with the following code:

```
package mypackage

import (
	"fmt"
	"reflect"
)

type Helper struct{}

func (Helper) Method1() {}
func (Helper) method2() { fmt.Println("From method2") }

func (h Helper) Print() {
	h.method2()

	for i := range reflect.TypeOf(h).NumMethod() {
		fmt.Println(reflect.TypeOf(h).Method(i))
	}
}
```

As you can see, the package is very simple. It only has one defined type (`Helper`) with 3 methods, 2 exported and one private (non-exported). The `Print` method is used to print method set of the `Helper`.

`main.go` is as follows:

```
package main

import (
	"ceogolang/mypackage"
	"fmt"
	"reflect"
)

func main() {
	h := mypackage.Helper{}

	for i := range reflect.TypeOf(h).NumMethod() {
		fmt.Println(reflect.TypeOf(h).Method(i))
	}

	h.Print()
}
```

The main function is also very simple, it just initializes the `mypackage.Help` struct variable and prints its method set (one directly in the main and one by invoking `Print` method).

### What did you see happen?

The std output of the program is:

> {Method1  func(mypackage.Helper) <func(mypackage.Helper) Value> 0}
> {Print  func(mypackage.Helper) <func(mypackage.Helper) Value> 1}
> From method2
> {Method1  func(mypackage.Helper) <func(mypackage.Helper) Value> 0}
> {Print  func(mypackage.Helper) <func(mypackage.Helper) Value> 1}

### What did you expect to see?

I expect to see `method2` in the second print as well, since (looking "directly" at the `mypackage`) the helper method set also includes `method2` (I invoked it in the `Print` method).

**Comment by nussjustin** [comment]
This is working as intended.

From the documentation for [Type.Method](https://pkg.go.dev/reflect#Type.Method):

```go
// For a non-interface type T or *T, the returned Method's Type and Func
// fields describe a function whose first argument is the receiver,
// and only exported methods are accessible.
```

Similary for [Type.NumMethod](https://pkg.go.dev/reflect#Type.NumMethod)

```go
// For a non-interface type, it returns the number of exported methods.
```

`method2` is not exported, so it is not returned by `Method` nor counted by `NumMethod`.

**Comment by leabit** [comment]
Thanks!
