### ISSUE TITLE
x/build/cmd/gitmirror: service problem first detected on 2024-04-23

### ISSUE THREAD

**Issue by dmitshur** [golang/go#67070]
Reporting for posterity and in case this comes up again. https://farmer.golang.org/#health was reporting a problem with Git mirroring on 2024-04-23:

![image](https://github.com/golang/go/assets/1924134/6f1a052d-4817-4d79-902f-d618fdd772ac)

It was unhealthy and continuously restarting:

```
$ kubectl get pods
NAME                                              READY   STATUS    RESTARTS          AGE
[...]
gitmirror-mirroring-deployment-6ffdbb4bbb-wtsfs   1/1     Running   170 (4m40s ago)   28d
gitmirror-serving-deployment-76944dc76b-h2qpv     1/1     Running   1 (15h ago)       28d
gitmirror-serving-deployment-76944dc76b-lmk8r     1/1     Running   1 (15h ago)       28d
[...]
```

The specific problem it kept running into was a "invalid index-pack output" error while cloning the go repository:

```
2024/04/23 14:31:55 go: git [clone --mirror https://go.googlesource.com/go /cache/gitmirror/go] failed after 5m33.999593098s: exit status 128
stderr: Cloning into bare repository '/cache/gitmirror/go'...
fatal: fetch-pack: invalid index-pack output

2024/04/23 14:31:55 initializing repos: cloning https://go.googlesource.com/go: exit status 128
```

CC @golang/release, @joedian.

**Comment by dmitshur** [comment]
That error doesn't provide detail but suggests an internal problem in git, possibly related to insufficient resources. We hadn't increased gitmirror's resources in a while.

That said, after redeploying the latest version, the problem hasn't returned, and it's been working okay:

```
2024/04/23 14:53:15 go: ran git [clone --mirror https://go.googlesource.com/go /cache/gitmirror/go] in 7m26.809263865s
```

Closing since this instance is resolved. If it keeps coming up, we may need to do more.

**Comment by cagedmantis** [comment]
This error has happend again. I noticed that the memory limits were being exceeded for individual pods. the CPU limits were also very close to being exceeded. Increasing the allocated resources seems to have fixed it. I will continue to monitor the service until I feel confident that the issue is resolved.

**Comment by cagedmantis** [comment]
CL https://go.dev/cl/586778 seems to have fixed this issue.
