### ISSUE TITLE
"github.com/golang/glog": feature request: support for including stack trace in non-Fatal logs

### ISSUE THREAD

**Issue by ghasemloo** [golang/go#67086]
### Go version

go version go1.22.2 linux/amd64

### Output of `go env` in your module/workspace:

```shell
NA
```

### What did you do?

```golang
glog.ErrorContextDepthf(ctx, 0, "failed: %v", err)
```

### What did you see happen?

it adds a log that shows the call site.

### What did you expect to see?

I want to get the hierachy of the call stack, not just the calls site at depth 0.

this is already implemented in the package internally with `stack` bool type and consts "withStack" and "noStack" but it is not exposed to the users of the package.

What I need is essentially the package exposing some way to pass in "withStack" as an option to the log statements of lower sevirity than "Fatal", like "Error".

Having a "ctx" key:value for it and adding it to the ctx I think can also be fine, and would not need a change in the function signatures or introducing new functions.

something like:

```golang
ctx = glog.ContextWithStack(ctx)
glog.ErrorContextf(ctx, "failed: %v", err)
```

shouldn't have much perofrmance impact either to do a simple key lookup from context.
it can be added to the condition check here:

https://github.com/golang/glog/blob/861d094757551d2f65d1003f0ec93bc92b254a5a/glog.go#L219

```golang
if stack == withStack || ctxHasWithStack(ctx) || backtraceAt(file, line){
```

**Comment by seankhliao** [comment]
from the repo readme:

> The repository contains an open source version of the log package used inside Google. The master copy of the source lives inside Google, not here. The code in this repo is for export only and is not itself under development. Feature requests will be ignored.
