### ISSUE TITLE
net.Conn set 【SO_RCVBUF】, can‘t Close the Conn

### ISSUE THREAD

**Issue by wangyuanwenGit** [golang/go#67094]
goversion:go version go1.19.13 windows/amd64
hostarch:linux

`go
fd, err1 := outConn.(*net.TCPConn).File()
		if err1 == nil {
			syscall.SetsockoptInt(int(fd.Fd()), syscall.SOL_SOCKET, syscall.SO_RCVBUF, 1024*128)
		}
`

Then, call the `outConn.Close()` returned nil error, but I used netstat to check the connection, and it was still in the `ESTABLISH` state. When I deleted the code that set the `SO_RCVBUF` size, everything returned to normal. I'm not sure what the problem is. Is there something wrong with my usage? 

Of course, t can see the  receive buffer has many bytes to read.

![BA55BD91-CE9C-45cb-BBF9-697C53048598](https://github.com/golang/go/assets/32731703/78c3b90a-d018-42ec-a16d-0908d92f749f)

please help me,thank you!!

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
