### ISSUE TITLE
x/spec: the selector rules list states that certain legal expressions are illegal

### ISSUE THREAD

**Issue by leabit** [golang/go#67099]
### What is the URL of the page with the issue?

https://go.dev/ref/spec#Selectors

### What is your user agent?

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

### Screenshot

![image](https://github.com/golang/go/assets/161745257/ee5b08a5-5850-424d-aabd-bdff35de68bc)

### What did you do?

The official [golang specification](https://go.dev/ref/spec#Selectors) (selectors section) states the following two rules:

> ....
> 3. As an exception, if the type of x is a [defined](https://go.dev/ref/spec#Type_definitions) pointer type and (*x).f is a valid selector expression denoting a field (but not a method), x.f is shorthand for (*x).f.
> 4. In all other cases, x.f is illegal.
> ....

So, based on that, only the following should work:

```
package main

import "fmt"

type Human *struct {
	name string
}

func main() {
	var a Human = &struct{ name string }{"leabit1"}

	fmt.Println(a.name)

	a.name = "leabit2"

	fmt.Println(a.name)
}
```

### What did you see happen?

However, the following two cases also work (even though, based on documentation, they are illegal):

1) Pointer to defined non-pointer type

```
package main

import "fmt"

type Human struct {
	name string
}

func main() {
	var a *Human = &Human{"leabit1"}

	fmt.Println(a.name)

	a.name = "leabit2"

	fmt.Println(a.name)
}

```

2. Pointer to non-defined (unnamed) type

```
package main

import "fmt"

func main() {
	var a *struct{ name string } = &struct{ name string }{"leabit1"}

	fmt.Println(a.name)

	a.name = "leabit2"

	fmt.Println(a.name)
}
```

### What did you expect to see?

I expect the documentation to include these two cases and not to consider them illegal.

**Comment by seankhliao** [comment]
Those are just the first case, where
x = a
T = Human or struct{ name string }
f = name
