### ISSUE TITLE
x/mobile: Is it possible to send a function as argument from Java to golang?

### ISSUE THREAD

**Issue by sourish115** [golang/go#67136]
I am using gomobile bind to generate binding for android. I have a use case where I want to write and export a function in golang which takes in a simple function as an argument like so:
`func SetCallback(cb Callback)`
where Callback is a user  defined type:
`type Callback func(string)`
However gomobile bind is not able to generate java bindings for this function. I have tried to do this directly without defining a Callback type, but no success. Is there any other way to do this?
Thank you for your time, looking forward to your response.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
