### ISSUE TITLE
exception 0xc0000005 0x8 0x0 0x0 PC=0x0

### ISSUE THREAD

**Issue by lastSpectator** [golang/go#67139]
### Go version

go 1.22.2

### Output of `go env` in your module/workspace:

```shell
amd64
```

### What did you do?

download 1.22.2
run: go version

### What did you see happen?

0xc0000005 0x8 0x0 0x0 PC=0x0

### What did you expect to see?

1.22.2

**Comment by quochuy284** [comment]
tôi cũng bị như bạn vậy đó
