### ISSUE TITLE
testing: clarify that b.N does not change during execution of the benchmark function

### ISSUE THREAD

**Issue by dolmen** [golang/go#67137]
The [`testing` documentation](https://pkg.go.dev/testing@master#hdr-Benchmarks) clearly mentions that the loop boundary variable might change during execution: 
> During benchmark execution, `b.N` is adjusted until the benchmark function lasts long enough to be timed reliably.

I noticed that [range over integer loop](https://go.dev/ref/spec#For_range) have different behavior than [for with clause](https://go.dev/ref/spec#For_clause) loops when the loop boundary is changed by the loop body:
https://go.dev/play/p/cObUT32FcXc

```go
	n := 4
	for i := 0; i < n; i++ {
		fmt.Println(n)
		n--
	}

	fmt.Println("----")

	n = 4
	for range n {
		fmt.Println(n)
		n--
	}
```

```
4
3
----
4
3
2
1
```

I have not found this difference in behavior explicitely mentioned in [the Go specification](https://go.dev/ref/spec#For_range). The following sentence speaks about the first evaluation of the range expression, but doesn't mention later evaluations.
> The range expression x is evaluated once before beginning the loop, with one exception: if at most one iteration variable is present and len(x) is [constant](https://go.dev/ref/spec#Length_and_capacity), the range expression is not evaluated. 

I wonder how a benchmark would be affected by the use of range-over-integer instead of the documented style.

I have seen no clear mention of forbidding the use of range-over-integer with `b.N` for benchmarks. I have not seen either an explicit mention that range-over-int is compatible with `testing.B` benchmarks which makes me wonder if this has been considered. I also did [a code search on `range b.N` in the Go repository](https://github.com/search?q=repo%3Agolang%2Fgo+%22range+b.N%22&type=code) and the only result is [a test in the `database/sql` package](https://github.com/golang/go/blob/660a071906a3f010a947457521b7671041b5f737/src/database/sql/sql_test.go#L4927) just added less that 2 months ago by @bradfitz in [CL 572119](https://go-review.googlesource.com/c/go/+/572119). No tests in `testing`.

So it would be helpful to have explicit documentation about the use of `b.N` with range-over-integer.

If this is in fact an incompatibility, it would be helpful to have a `go vet` alert about use of range-over-int on `testing.B.N`.

### Go version

go version go1.22.2 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
N/A (reproducible on play.golang.org)
```

### What did you see happen?

```console
$ go doc -all testing | grep -c 'range b.N'
0
```

### What did you expect to see?

```console
$ go doc -all testing | grep -c 'range b.N'
1
```

**Comment by jub0bs** [comment]
Following a discussion on Gophers Slack and a casual inspection of `testing`'s source code, I don't think `b.N` changes during the execution of a benchmark subject. However, I agree with @dolmen that the documentation is ambiguous/misleading in that respect.

**Comment by dolmen** [comment]
I've been a fulltime Go developer for 9 years. I've read the documentation about benchmarks multiple times. I never thought that the whole benchmark function was called multiple times because this is different that Test functions which are called just once. Instead, because of that sentence in the documentation, I thought that `b.N` was changed dynamically (with magic locking that I didn't investigate: after all [code coverage via source instrumentation](https://go.dev/blog/cover#test-coverage-for-go) is already magic of `go test`).

**Comment by jub0bs** [comment]
@Jorropo I don't think @dolmen is suggesting a change to that behaviour; he's only pointing out that, if `b.N` changed during execution of the benchmark function, then

```go
for range b.N { /* ... */ }
```

would not be equivalent to 

```go
for i:=0; i < b.N; i++ { /* ... */ }
```
