### ISSUE TITLE
strings: TrimLeft() returns unexpected value

### ISSUE THREAD

**Issue by keisku** [golang/go#67149]
### What is the URL of the page with the issue?

https://go.dev/play/p/5iv2wx09xc9

### What is your user agent?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

### Screenshot

![2024-05-03_14-51-31](https://github.com/golang/go/assets/41987730/bb998f64-9e64-4276-9886-2a98f0498c66)

### What did you do?

During debugging my program, I've noticed this unexpected behavior.

### What did you see happen?

```go
func main() {
	fmt.Println(strings.TrimLeft(
		"/kubernetes/kubernetes/release-1.30/api/openapi-spec/v3/apis__authentication.k8s.io__v1_openapi.json",
		"/kubernetes/kubernetes/release-1.30/api/openapi-spec/v3/",
	))
	// Expected: "apis__authentication.k8s.io__v1_openapi.json"
	// Actual:   "__authentication.k8s.io__v1_openapi.json"
}
```

### What did you expect to see?

Wrote in the "What did you see happen?" section.

Now I am using `filepath.Base()` instead.
https://go.dev/play/p/sIBOz9OmLuV

**Comment by Jorropo** [comment]
`TrimLeft` takes a list of unicode codepoints to remove, this code is identical to:
```go
func main() {
	fmt.Println(strings.TrimLeft(
		"/kubernetes/kubernetes/release-1.30/api/openapi-spec/v3/apis__authentication.k8s.io__v1_openapi.json",
		"/kuberntsla-1.30piocv",
	))
}
```

You want:
> To remove a prefix, use [TrimPrefix](https://pkg.go.dev/strings#TrimPrefix) instead.
