### ISSUE TITLE
x/sys/unix: mkall.sh fails due to missing files

### ISSUE THREAD

**Issue by programmingkidx** [golang/go#67178]
### Go version

go 1.22.0 darwin amd64

### Output of `go env` in your module/workspace:

```shell
not needed
```

### What did you do?

In the src/cmd/vendor/golang.org/x/sys/unix folder is the mkall.sh script. It is used to generate several files in its folder. First I changed directories to the src/cmd/vendor/golang.org/x/sys/unix folder. Then I ran GOOS=darwin GOARCH=amd64 ./mkall.sh. 

### What did you see happen?

I saw these errors:
<stdin>:25:10: fatal error: 'sys/vsock.h' file not found
#include <sys/vsock.h>
         ^~~~~~~~~~~~~
1 error generated.
/go-1.22.0/src/cmd/vendor/golang.org/x/sys/unix/_const.go:28:10: fatal error: 'sys/vsock.h' file not found
#include <sys/vsock.h>
         ^~~~~~~~~~~~~
1 error generated.
stat mksyscall.go: no such file or directory
stat mkpost.go: no such file or directory
cgo: open /go-1.22.0/src/cmd/vendor/golang.org/x/sys/unix/types_darwin.go: no such file or directory
stat mkasm.go: no such file or directory

### What did you expect to see?

I expected to see these files generated:
- zerrors_darwin_amd64.go
- zsyscall_darwin_amd64.go
- zsysnum_darwin_amd64.go
- ztypes_darwin_amd64.go

I did read the README.md file in the same folder and it states:
"To build the files for your current OS and architecture, make sure GOOS and
GOARCH are set correctly and run `mkall.sh`. This will generate the files for
your specific system. Running `mkall.sh -n` shows the commands that will be run."

The issue is these files are missing from the unix folder:
- mksyscall.go
- mkpost.go
- mkasm.go

**Comment by mauri870** [comment]
These files do exist in the sys repo, e.g https://cs.opensource.google/go/x/sys/+/refs/tags/v0.20.0:unix/mkasm.go. Can you try building from the x/sys source instead?

I believe the vendored copy only includes the autogenerated code to be used, but not the routines to actually generate the code.

**Comment by ianlancetaylor** [comment]
The files under cmd/vendor are incomplete copies of upstream repositories.  Those files are created by modifying the upstream repo and then running `go mod vendor`.  In this case you should be looking at the golang.org/x/sys repo.

**Comment by programmingkidx** [comment]
@mauri870 Why is the mkall.sh file not removed like the other files?

**Comment by ianlancetaylor** [comment]
Go files with `//go:build ignore` lines are not copied into the vendor directory.  There is no special rule for a shell file.

**Comment by ianlancetaylor** [comment]
Unfortunately it's not that simple.  It's possible for a .sh file to be embedded into the package using a `go:embed` directive (see https://pkg.go.dev/embed).  It would be possible to complicate `go mod vendor` by having it compute the total set of embedded files and copy only those over, but simply ignoring shell files isn't safe by itself.

That said, I filed #67233 to propose only copying files that the build system will use.

**Comment by programmingkidx** [comment]
Thank you.
