### ISSUE TITLE
Can't install Gopls in Linux mint

### ISSUE THREAD

**Issue by chirani** [golang/go#67172]
### gopls version

latest

### go env

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN='/home/chirani/go/bin'
GOCACHE='/home/chirani/.cache/go-build'
GOENV='/home/chirani/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/chirani/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/chirani/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/home/chirani/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/home/chirani/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22.1'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/chirani/side/golang/rest_test/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build369982435=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

attempted to install Gopls

### What did you see happen?

```
[info]: gopls: failed to install gopls(golang.org/x/tools/gopls@latest): Error: Command failed: /home/chirani/local/go/bin/go install -v golang.org/x/tools/gopls@latest
runtime/cgo
# runtime/cgo
_cgo_export.c:3:10: fatal error: stdlib.h: No such file or directory
    3 | #include <stdlib.h>
      |          ^~~~~~~~~~
```

### What did you expect to see?

Why wasn't installed

### Editor and settings

Running Linux mint on a VirtualBox
VS code

### Logs

[info]: gopls: failed to install gopls(golang.org/x/tools/gopls@latest): Error: Command failed: /home/chirani/local/go/bin/go install -v golang.org/x/tools/gopls@latest
runtime/cgo
# runtime/cgo
_cgo_export.c:3:10: fatal error: stdlib.h: No such file or directory
    3 | #include <stdlib.h>
      |          ^~~~~~~~~~

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by iqbaltaufiq** [comment]
install g++ from terminal.
```
sudo apt install g++
```
and then try installing gopls again.

source: [another github issue](https://github.com/mattn/go-sqlite3/issues/481#issuecomment-355717133)
