### ISSUE TITLE
Adding support for .heic images

### ISSUE THREAD

**Issue by MaxBoych** [golang/go#67180]
### Proposal Details

Using different formats well:

```
	image.RegisterFormat("jpeg", "jpeg", jpeg.Decode, jpeg.DecodeConfig)
	image.RegisterFormat("jpg", "jpeg", jpeg.Decode, jpeg.DecodeConfig)
	image.RegisterFormat("png", "png", png.Decode, png.DecodeConfig)
	image.RegisterFormat("gif", "gif", gif.Decode, gif.DecodeConfig)
	image.RegisterFormat("bmp", "bmp", bmp.Decode, bmp.DecodeConfig)
	image.RegisterFormat("tiff", "tiff", tiff.Decode, tiff.DecodeConfig)
	image.RegisterFormat("webp", "webp", webp.Decode, webp.DecodeConfig)
```

However the .heic format is sorely missed:

```
        image.RegisterFormat("heic", "heic", heic.Decode, heic.DecodeConfig)
```

I tried to use all sorts of libraries but they were not supported for a long time, caught some C-lang errors

**Comment by seankhliao** [comment]
see https://go.dev/doc/faq#x_in_std
given how it is a patent-encumbered format, and how stretched thin our maintainers are, I don't see this as something that can be maintained by the Go project.
