### ISSUE TITLE
x/sys/unix: update README.md file to include information on original repo

### ISSUE THREAD

**Issue by programmingkidx** [golang/go#67189]
### Go version

go 1.22.0 darwin amd64

### Output of `go env` in your module/workspace:

```shell
Not needed
```

### What did you do?

I read the file README.md in the src/cmd/vendor/golang.org/x/sys/unix folder. 

### What did you see happen?

The program mkall.sh does not work as the README.md file states. There are files missing. See https://github.com/golang/go/issues/67178 for more information.

### What did you expect to see?

I ask that the information on the upstream repo be included in the file README.md. This is where the upstream repo is located: https://cs.opensource.google/go/x/sys/+/refs/tags/v0.20.0:unix/.

**Comment by ianlancetaylor** [comment]
The files do exist.  You are looking at a vendored copy, not the actual repository.
