### ISSUE TITLE
sync/atomic Store() does not leave, CPU at 100%

### ISSUE THREAD

**Issue by flolege** [golang/go#67222]
### Go version

go version go1.19.3 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/goOpera/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3061573790=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

I am running the goOpera node of the Fantom Foundation blockchain project. goOpera uses an older go-ethereum version for certain operations, in this case the interesting part is the types.Sender function which calls the atomic.Value Store() procedure:

```
func Sender(signer Signer, tx *Transaction) (common.Address, error) {
	if sc := tx.from.Load(); sc != nil {
		sigCache := sc.(sigCache)
		// If the signer used to derive from in a previous
		// call is not the same as used current, invalidate
		// the cache.
		if sigCache.signer.Equal(signer) {
			return sigCache.from, nil
		}
	}
	addr, err := signer.Sender(tx)
	if err != nil {
		return common.Address{}, err
	}
	tx.from.Store(sigCache{signer: signer, from: addr})
	return addr, nil
}
```

Transaction struct looks like this:
```
type Transaction struct {
	data txdata
	// caches
	hash atomic.Value
	size atomic.Value
	from atomic.Value
}
```

github link to types.Sender() call [here](https://github.com/Fantom-foundation/go-ethereum/blob/master/core/types/transaction_signing.go#L72)

### What did you see happen?

In my custom code I use types.Sender quite heavily, and usually it works, but sometimes the code does not continue, and the CPU is running at 100%. 

I nailed it down to the sync/atomic.Value Store() procedure which in those cases never seem to return.
Only way to stop this is to panic after a timeout. 

### What did you expect to see?

I expect to see that sync/atomic.Value Store() procedure always returns and never gets stuck.

**Comment by seankhliao** [comment]
note that 1.19 is an unsupported release

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
