### ISSUE TITLE
x/website: dark background of images in chacha8rand blog post

### ISSUE THREAD

**Issue by Deleplace** [golang/go#67224]
### Go version

N/A

### Output of `go env` in your module/workspace:

```shell
N/A
```

### What did you do?

https://go.dev/blog/chacha8rand#performance

### What did you see happen?

<img width="750" alt="image" src="https://github.com/golang/go/assets/13508141/d9dadf40-bafa-4e43-bbf6-0ba743e9e488">

### What did you expect to see?

Better contrast in the 7 SVG images:
- either light color over dark background (best)
- or dark color over light background

**Comment by cherrymui** [comment]
cc @rsc @FiloSottile @golang/tools-team

**Comment by mauri870** [comment]
Looks like it is fixed by [CL 583835](https://go-review.googlesource.com/c/website/+/583835), so closing.

**Comment by Deleplace** [comment]
Yes, I confirm :)

![image](https://github.com/golang/go/assets/13508141/f02f1a5c-e733-45a8-96a9-4233a8562922)
