### ISSUE TITLE
x/tools/gopls/internal/analysis/simplifyrange: adapt for go1.23 range over func

### ISSUE THREAD

**Issue by adonovan** [golang/go#67239]
When it sees `for _ = range x { ... }`, the `simplifyrange` analyzer in gopls offers a suggested fix to remove the `_ = ` part. This is not legal in go1.23 if x is a func.

**Comment by findleyr** [comment]
From dupes:
- Don't forget gofmt -s
- Don't forget the underlying spec proposal.

**Comment by adonovan** [comment]
Reopening since the proposal to make them optional again was accepted:
- https://github.com/golang/go/issues/65236#issuecomment-2187122281
