### ISSUE TITLE
x/build/cmd/watchflakes: shouldn't reopen frozen issues

### ISSUE THREAD

**Issue by dmitshur** [golang/go#67232]
It can be pretty confusing if watchflakes is willing to reopen an issue so old that it is frozen. It should probably opt to file a new issue instead in such cases (and optionally refer to the frozen one).

This happened in #56707, which was a frozen issue in Go1.20 milestone with Soon label that got reopened.

Related issues:

- #57632

**Comment by cherrymui** [comment]
@dmitshur now that we auto-evict old issues from the Test Flakes project, watchflakes shouldn't see frozen issues. Is there anything else needed for this? We could still explicitly not reopen frozen issues, but it doesn't seem very necessary?

**Comment by dmitshur** [comment]
I agree, the auto-archival of closed issues without recent activity likely removes the main source of this happening. Let's not do anything for now unless we find out this is still a problem somehow.
