### ISSUE TITLE
x/tools/gopls: reenable tests suppressed due to lack of build{ssa,ir} support for range-over-func or gotypesalias=1

### ISSUE THREAD

**Issue by adonovan** [golang/go#67262]
A number of gopls tests have been skipped. We shouldn't forget to reenable them when the upstream issues are fixed.

Pending CL adding SSA support for range-over-func:
- https://go.dev/cl/555075

Upstream issues:
- https://github.com/dominikh/go-tools/issues/1494
- https://github.com/dominikh/go-tools/issues/1523

**Comment by adonovan** [comment]
Current status:
- https://go.dev/cl/586076/ updates gopls' staticcheck, but cannot be merged until either staticcheck downgrades its go.mod back to go1.19, or downgrades to go1.21 AND the go1.23 release occurs AND gopls 16 is released (due to #65917).
- https://go-review.git.corp.google.com/c/tools/+/589275 reverts the workaround that disables staticcheck buildir on packages that use `iter`, which is now ~all packages. This cannot be merged until the parent is merged.

**Comment by findleyr** [comment]
@adonovan what's left after the above fixes?

**Comment by adonovan** [comment]
Nothing, I think.
