### ISSUE TITLE
cmd/go: -compiler gccgo should allow specifying the compiler to use

### ISSUE THREAD

**Issue by mwhudson** [golang/go#6727]
<pre>Currently, if you specify -compiler gccgo, go build and friends will just invoke the
'gccgo' binary that's found on $PATH.  This is limiting -- in particular it makes using
a cross-compiling gccgo harder.

(You can always put a symlink to your cross-gccgo called &quot;gccgo&quot; in some
tmpdir and stick it on the front of $PATH... but ick)</pre>

**Comment by rsc** [comment]
Fixed by 8b836fa8; use $GCCGO to control the compiler.
