### ISSUE TITLE
x/pkgsite: "github.com/vortex93/gate-keeper" could not be found.

### ISSUE THREAD

**Issue by Vortex93** [golang/go#67331]
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/vortex93/gate-keeper

### What is your user agent?

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

### Screenshot

![chrome_OoKXTlwR3s](https://github.com/golang/go/assets/10325225/7998289a-9451-49d7-a8c5-1f0ecc17296e)

### What did you do?

Requested to add the package I created

### What did you see happen?

Shows could not be found, meanwhile it's a public repo and I have visited it on multiple PCs and still unable to add to the pkg.go.dev.

### What did you expect to see?

Not sure yet, it's my first time adding a package to pkg.go.dev. But I expected it to not show that it could not be found.

**Comment by seankhliao** [comment]
capitalization matters.
