### ISSUE TITLE
x/pkgsite: render mermaid js

### ISSUE THREAD

**Issue by trajan0x** [golang/go#67339]
### What did you do?

Going to add feature request here.

While not formally included in the [Github-Flavored Markdown Spec](https://github.github.com/gfm/), [Github supports mermaid diagrams](https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/)

Given there's no good way to force these not to render on `pkg.go.dev`, but do render in readme's I think it'd be best if pkg.go.dev supported them.

I'll use one example from my project on how the ux can be sub-optimal otherwise.

We have a [git-change-detector](https://github.com/synapsecns/sanguine/pull/2355) for go workspaces where a lot of the [readme](https://github.com/synapsecns/sanguine/tree/master/contrib/git-changes-action) looks like this:

<img width="1149" alt="image" src="https://github.com/golang/go/assets/83933037/261e8e39-a5d2-4be9-b36b-8faf261b3d74">

But on [pkg.go.dev](https://pkg.go.dev/github.com/synapsecns/sanguine/contrib/git-changes-action#readme-module-level-resolution), it looks like this: 

<img width="1208" alt="image" src="https://github.com/golang/go/assets/83933037/1ade2efd-f849-4eeb-a73a-8a743cf96418">

Anyway, would definitely be a nice to have

### What did you see happen?

N/A

### What did you expect to see?

N/A

**Comment by nnzv** [comment]
Supporting Mermaid.js in pkgsite would likely introduce unnecessary complexity and potential performance issues without significant benefits for Go developers.

**Comment by AlexanderYastrebov** [comment]
Maybe it makes sense to add codeblock language id to `<pre>/<code>` tags to enable userscript-based highlighting/rendering.

**Comment by matloob** [comment]
I don't know if it's worth making the change in https://go.dev/cl/585955 if it's only going to be used by users who enable a custom script locally.

**Comment by AlexanderYastrebov** [comment]
> I don't know if it's worth making the change in https://go.dev/cl/585955 if it's only going to be used by users who enable a custom script locally.

@matloob 
What is the problem or risk to enable already existing codeblock language metadata?
Userscript is the straightforward usecase but there might be others like hints to the crawlers or corporate pkgsite deployments with syntax highlight by default.

**Comment by nnzv** [comment]
> I don't know if it's worth making the change in https://go.dev/cl/585955 if it's only going to be used by users who enable a custom script locally.

Absolutely, that sounds like a more appropriate approach. By utilizing a script to generate necessary files from upstream sources, you can easily place the URL file where pkgsite can display it. This strategy enables flexibility with various tools, eliminating the need to confine yourself to just one option.

**Comment by adonovan** [comment]
We discussed this in our triage meeting and decided that the benefit of the feature is not worth the costs and risks. Go's pkg.go.dev site was never intended to fully simulate GitHub's markdown renderer.

**Comment by AlexanderYastrebov** [comment]
@adonovan @matloob What are the risks of adding a css class to the html element?

**Comment by adonovan** [comment]
> @adonovan @matloob What are the risks of adding a css class to the html element?

The costs and risks of adding a class attribute are very low, though the value seems low also. I would not object to https://go.dev/cl/585955, though I defer to @matloob.

The feature I was referring to as "not worth the costs and risks" is the mermaid rendering that is the subject of this issue.
