### ISSUE TITLE
database/sql: Stmt.Close does not return errors from driver.Stmt.Close

### ISSUE THREAD

**Issue by olt** [golang/go#6734]
<pre>sql.Stmt.Close does not return errors from driver.Stmt.Close

What steps will reproduce the problem?

Call sql.Stmt.Close with a driver that returns an error from driver.Stmt.Close(). See
<a href="http://play.golang.org/p/NxOcz1bT_-">http://play.golang.org/p/NxOcz1bT_-</a>

What is the expected output?
The error from driver.Stmt.Close().

What do you see instead?
No error at all.

Actual use case?

1. I'm working on bulk imports with Postgres COPY FROM statement and I'm reading the
server responses in a separate goroutine (so the stmt.Exec() is asynchonous and will not
return errors immediately).
2. The error handling goroutine is closed when driver.Stmt.Close() is called and the
function returns any pending errors that the server sent back.
3. Calling sql.Stmt.Close() will not return any errors.

Which compiler are you using (5g, 6g, 8g, gccgo)?
6g

Which operating system are you using?
Mac OS X 10.7.5

Which version are you using?  (run 'go version')
go version devel +de159d1f10be Fri Nov 01 12:53:31 2013 +1100 darwin/amd64</pre>

**Comment by kardianos** [comment]
All statements created by the user are now wrapped in a driverStmt that has a sticky error.
As far as I understand the stated issue this is resolved. Please re-open if I'm mistaken.
