### ISSUE TITLE
Documentation/Tutorial: "Random Greeting" tutorial does not reset seed upon subsequent call in playground/vscode. Confusing for new learners.

### ISSUE THREAD

**Issue by KWTechKevin** [golang/go#67344]
Go version: go version go1.18.1 linux/amd64

Followed tutorial instructions to the T, found on https://go.dev/doc/tutorial/random-greeting as of 13 May 2024. 
When running go run . , it does not reset the random seed, resulting in the same results. 

Expected random results.

The solution adopted was to add to the randomFormat() function:

"rand.Seed(time.Now().UnixNano()) // required as go makes randomness deterministic, note that playground makes time deterministic too"

**Comment by seankhliao** [comment]
please use an up to date version of go.

**Comment by KWTechKevin** [comment]
This issue also happens with the latest version of go. 

Shouldn't be too hard to add an extra line to the documentation for people in such a situation.

**Comment by seankhliao** [comment]
we removed the seeding line because go >= 1.20 uses random seeds by default.
