### ISSUE TITLE
os/exec: execution of internal command at Windows gives error

### ISSUE THREAD

**Issue by tredoe** [golang/go#67358]
### Go version

go version go1.22.2 windows/amd64

### Output of `go env` in your module/workspace:

```shell
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\neo\AppData\Local\go-build
set GOENV=C:\Users\neo\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\lib\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\lib\go;C:\Users\neo\Projects\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.22.2
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\neo\Projects\go\osutil\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\neo\AppData\Local\Temp\go-build930553209=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

```
package executil

import (
	"os/exec"
	"testing"
)

func TestEcho(t *testing.T) {
	cmd := exec.Command("echo", "ok")
	if err := cmd.Run(); err != nil {
		t.Fatal(err)
	}
}
```

### What did you see happen?

exec: "echo": executable file not found in %PATH%

### What did you expect to see?

'echo' is an internal command at Windows so it can not found in %PATH%.

**Comment by dmitshur** [comment]
CC @golang/windows.

**Comment by dmitshur** [comment]
This is probably working as intended. If there was a command named `echo` in %PATH%, would it be executed? If so, it might not be a responsibility of os/exec to track which builtins on various platforms.

**Comment by alexbrainman** [comment]
> This is probably working as intended.

I agree.

> If there was a command named `echo` in %PATH%, would it be executed?

If a file named `echo.exe` would be found in the %PATH%, it would be executed. If a file named `echo` would be found in the %PATH%, it would not be executed. 

Alex
