### ISSUE TITLE
cmd/go/internal/script: fix build tags of isETXTBSY

### ISSUE THREAD

**Issue by hnakamur** [golang/go#67356]
### Go version

go version 1.22.2

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/hnakamur/.cache/go-build'
GOENV='/home/hnakamur/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/hnakamur/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/hnakamur/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22.2'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build510329441=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

I looked at the following source files:

* [src/cmd/go/internal/script/cmds_posix.go](https://github.com/golang/go/blob/8623c0ba95f01387c2d705349722b5fcb2b3e77d/src/cmd/go/internal/script/cmds_posix.go)
* [src/cmd/go/internal/script/cmds_other.go](https://github.com/golang/go/blob/8623c0ba95f01387c2d705349722b5fcb2b3e77d/src/cmd/go/internal/script/cmds_other.go)

### What did you see happen?

I saw the build tags:

  * `//go:build unix || windows` in [src/cmd/go/internal/script/cmds_posix.go](https://github.com/golang/go/blob/8623c0ba95f01387c2d705349722b5fcb2b3e77d/src/cmd/go/internal/script/cmds_posix.go)
  * `//go:build !(unix || windows)` in [src/cmd/go/internal/script/cmds_other.go](https://github.com/golang/go/blob/8623c0ba95f01387c2d705349722b5fcb2b3e77d/src/cmd/go/internal/script/cmds_other.go)

### What did you expect to see?

I expect to see the following build tags:

  * `//go:build unix` in [src/cmd/go/internal/script/cmds_posix.go](https://github.com/golang/go/blob/8623c0ba95f01387c2d705349722b5fcb2b3e77d/src/cmd/go/internal/script/cmds_posix.go)
  * `//go:build !unix` in [src/cmd/go/internal/script/cmds_other.go](https://github.com/golang/go/blob/8623c0ba95f01387c2d705349722b5fcb2b3e77d/src/cmd/go/internal/script/cmds_other.go)
  
just like:

* `//go:build unix` in [src/cmd/go/internal/test/test_unix.go](https://github.com/golang/go/blob/8623c0ba95f01387c2d705349722b5fcb2b3e77d/src/cmd/go/internal/test/test_unix.go)
* `//go:build !unix` in [src/cmd/go/internal/test/test_nonunix.go](https://github.com/golang/go/blob/8623c0ba95f01387c2d705349722b5fcb2b3e77d/src/cmd/go/internal/test/test_nonunix.go)

**Comment by ianlancetaylor** [comment]
Want to send a patch?  https://go.dev/doc/contribute.
