### ISSUE TITLE
cmd/compile: go:linkname does not work with dot in importpath

### ISSUE THREAD

**Issue by jiping-s** [golang/go#67361]
### Go version

go1.22.1 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/myname/Library/Caches/go-build'
GOENV='/Users/myname/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/myname/.go/pkg/mod'
GONOPROXY='*'
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/myname/.go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.22.1'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/myname/.go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/n3/rjz31n_50516xs92p6gswgsr0000gp/T/go-build174368253=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

Use go linkname with gopkg.in/yaml.v3 or gopkg.in/yaml.v2 

playground: https://go.dev/play/p/1yYtFVvGnfn

```
package main

import (
	"fmt"
	_ "unsafe"

	_ "gopkg.in/yaml.v2"
)

//go:linkname newEncoder gopkg.in/yaml.v2.newEncoder
func newEncoder() any

func main() {
	newEncoder()
}
```

### What did you see happen?

`relocation target gopkg.in/yaml.v2.newEncoder not defined`

### What did you expect to see?

The symbol is imported and can be called.

**Comment by seankhliao** [comment]
see https://github.com/golang/go/issues/63846#issuecomment-1787303345

**Comment by jiping-s** [comment]
> From what I see in your example you can just import the package as-is, there is no need to use linkname, plus I'm not sure if it even works with external packages, I have mainly seen its use with internal Go libraries.

- linkname is needed to access the internal `decoder`, not the public one which limits functionalities
- It does work with external packages and we use it on production system for other packages.

**Comment by jiping-s** [comment]
Hi! I found the actual symbol name by go tool compile. "." in the last part of package name is encoded:

```go
// gopkg.in/yaml.v2 => gopkg.in/yaml%2ev2

//go:linkname newEncoder2 gopkg.in/yaml%2ev2.newEncoder
func newEncoder2() any
```
