### ISSUE TITLE
x/pkgsite: package removal request for github.com/kickey-net/backend-proto

### ISSUE THREAD

**Issue by duyanh14** [golang/go#67371]
### What is the path of the package that you would like to have removed?

remove all path

### Are you the owner of this package?

![image](https://github.com/golang/go/assets/14250512/ef32182b-ff5d-46e3-bbae-3c4e474288ce)

### What is the reason that you could not retract this package instead?

Please remove https://pkg.go.dev/github.com/kickey-net/backend-proto. I have decided to make this project's GitHub repository private. Thanks!

**Comment by adonovan** [comment]
I confirm through the GitHib user interface that you are the sole person associated with this org.
