### ISSUE TITLE
x/tools/gopls: don't suggest simplification of "for _ = range x" if x is a func

### ISSUE THREAD

**Issue by adonovan** [golang/go#67394]
Currently, the spec requires that a `for _ = range f` statement must have the blank variables (one for Seq, two for Seq2). Gopls currently suggests a simplification to `for range f`. It should not do that.

But first wait for a decision on this proposal:
- https://github.com/golang/go/issues/65236.

**Comment by findleyr** [comment]
Deduping to https://github.com/golang/go/issues/67239, which is more general.
