### ISSUE TITLE
Division-by-zero op not halting execution 

### ISSUE THREAD

**Issue by ybeaudoin** [golang/go#67410]
### Go version

go version go1.22.2 windows/amd64

### Output of `go env` in your module/workspace:

```shell
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\webpraxis\AppData\Local\go-build
set GOENV=C:\Users\webpraxis\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\webpraxis\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\webpraxis\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.22.2
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=F:\Documents and Settings\Yves Beaudoin\My Documents\__Archives_v5\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\WEBPRA~1\AppData\Local\Temp\go-build3425322232=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

package main

import "fmt"
import "math"

func main() {
    x := 1
    fmt.Println( float64( x ) / float64( 0 ) )
    fmt.Println( math.Ceil( float64( x ) / float64( 0 ) ) )
    fmt.Println( int( math.Ceil( float64( x ) / float64( 0 ) ) ) )
    x = 0
    fmt.Println( float64( x ) / float64( 0 ) )
    fmt.Println( math.Ceil( float64( x ) / float64( 0 ) ) )
    fmt.Println( int( math.Ceil( float64( x ) / float64( 0 ) ) ) )
}

### What did you see happen?

go run test.go
Output is:

+Inf
+Inf
-9223372036854775808
NaN
NaN
-9223372036854775808

### What did you expect to see?

Expected execution to be halted with the error message "invalid operation: division by zero"

**Comment by ericlagergren** [comment]
From the spec

> The result of a floating-point or complex division by zero is not specified beyond the IEEE-754 standard; whether a run-time panic occurs is implementation-specific.

https://go.dev/ref/spec#Arithmetic_operators

**Comment by ybeaudoin** [comment]
Thanks for the swift reply. It is unfortunate that this is the case. With a program continuing its execution under such circumstances, some rather bizarre results are generated, leaving the coder totally baffled.

**Comment by randall77** [comment]
This is how floating-point works (in Go, C, Java, ...), sorry.
