### ISSUE TITLE
x/sys/windows: uintptr(unsafe.Pointer) calls outside of syscalls

### ISSUE THREAD

**Issue by abennett** [golang/go#67437]
Documentation states:
> (4) Conversion of a Pointer to a uintptr when calling syscall.Syscall.
The Syscall functions in package syscall pass their uintptr arguments directly to the operating system, which then may, depending on the details of the call, reinterpret some of them as pointers. That is, the system call implementation is implicitly converting certain arguments back from uintptr to pointer.
If a pointer argument must be converted to uintptr for use as an argument, that conversion must appear in the call expression itself

However, there are calls within `/x/sys/windows` that do not follow this requirement. For an example, [this call](https://cs.opensource.google/go/x/sys/+/master:windows/svc/service.go;l=213;drc=1bfbee0e20e3039533666df89a91c1876e67605d) is casting an `unsafe.Pointer` to `uintptr` then is then passed to [here](https://cs.opensource.google/go/x/sys/+/master:windows/zsyscall_windows.go;l=1179;drc=1bfbee0e20e3039533666df89a91c1876e67605d)

The generated calls in [windows/zsyscall_windows.go](https://cs.opensource.google/go/x/sys/+/master:windows/zsyscall_windows.go) should likely accept `unsafe.Pointer` arguments instead of `uintptr.`

### Examples
```golang
// from windows/svc/service.go
handle, err := windows.RegisterServiceCtrlHandlerEx(windows.StringToUTF16Ptr(theService.name), ctlHandlerCallback, uintptr(unsafe.Pointer(&theService)))

// from windows/zsyscall_windows.go
func RegisterServiceCtrlHandlerEx(serviceName *uint16, handlerProc uintptr, context uintptr) (handle Handle, err error) {
	r0, _, e1 := syscall.Syscall(procRegisterServiceCtrlHandlerExW.Addr(), 3, uintptr(unsafe.Pointer(serviceName)), uintptr(handlerProc), uintptr(context))
	handle = Handle(r0)
	if handle == 0 {
		err = errnoErr(e1)
	}
	return
}
```

**Comment by dmitshur** [comment]
CC @golang/runtime, @alexbrainman.

**Comment by ianlancetaylor** [comment]
CC @golang/windows 

I agree that this looks like a bug in x/sys/windows.  I don't know how hard it would be to fix.

**Comment by mguy-huntress** [comment]
@ianlancetaylor 
In this instance, you have the global `theService` for the context that's being passed in and converted. That context ends up [here](https://cs.opensource.google/go/x/sys/+/master:windows/svc/service.go;l=201;drc=1bfbee0e20e3039533666df89a91c1876e67605d).  You could ignore this context (and the [conversion](https://cs.opensource.google/go/x/sys/+/master:windows/svc/service.go;l=202;drc=1bfbee0e20e3039533666df89a91c1876e67605d) that could cause errors) and just use the global `theService` directly in this function.

**Comment by qmuntal** [comment]
This is a duplicated of #59687. IMO @alexbrainman CL supersedes the one submitted in #59687.

**Comment by alexbrainman** [comment]
> @ianlancetaylor
> In this instance, you have the global `theService` for the context that's being passed in and converted. That context ends up [here](https://cs.opensource.google/go/x/sys/+/master:windows/svc/service.go;l=201;drc=1bfbee0e20e3039533666df89a91c1876e67605d). You could ignore this context (and the [conversion](https://cs.opensource.google/go/x/sys/+/master:windows/svc/service.go;l=202;drc=1bfbee0e20e3039533666df89a91c1876e67605d) that could cause errors) and just use the global `theService` directly in this function.

I implemented @mguy-huntress suggestion in

https://go-review.googlesource.com/c/sys/+/591475

Hopefully it is good enough.

Alex
