### ISSUE TITLE
x/tools/gopls: ui.diagnostic.analyses -> shadow should allow exclude-rules, eg for err

### ISSUE THREAD

**Issue by Roemer** [golang/go#67440]
**Is your feature request related to a problem? Please describe.**
Showing shadowed variables can help to prevent some bugs but in most go code, the variable `err` is quite often shadowed which is ok. Therefore we see a lot of shadowed warnings which are not relevant and it is harder to see the relevant ones.

**Describe the solution you'd like**
When `shadow` is enabled, it should also be possible to add some kind of `ignores` like either directly exclude variable names or at least messages like `govet` with `exclude-rules`.

**Describe alternatives you've considered**
I couldn't find an alternative except for keeping `shadow` disabled.

**Comment by adonovan** [comment]
The `shadow` analyzer has never been enabled by default in 'go vet' of gopls because it has always suffered from a high rate of false positives that no-one knows how to fix. We would rather not invest any more effort into it.
