### ISSUE TITLE
strings, bytes, strconv, runtime: use SSE4.2 string instructions on am64

### ISSUE THREAD

**Issue by gopherbot** [golang/go#6749]
by **rayneolivetti**:

<pre>Chapter 10 of Intel Architectures Optimization Reference Manual describes use cases of
several SSE4 instructions that can speed up various routines in strings, bytes, strconv
and runtime packages.

The instructions are missing from 6l/6a by the way.</pre>

**Comment by agnivade** [comment]
@rsc - Is this still valid ? We already have SSE and AVX2 supported instructions in asm_amd64.s.

**Comment by agnivade** [comment]
ping @martisch / @Quasilyte - Does this still need to remain open ?

**Comment by TocarIP** [comment]
We are using sse4.2 for [Index](https://github.com/golang/go/blob/master/src/internal/bytealg/index_amd64.s#L36). I think this should be closed, and if there some other places where sse4.2 makes sense, we should open specific bug for each potential function from runtime/strconv.
