### ISSUE TITLE
cmd/compile: error message for disallowed ... actual parameter is confusing

### ISSUE THREAD

**Issue by tbushnell** [golang/go#6750]
<pre>If I have &quot;func foo(nums ...int)&quot;, and try a call like this: &quot;foo(1,
[]int{2, 3}...)&quot; the error message is confusing. You get something like this:

prog.go:17: too many arguments in call to printmany

See <a href="http://play.golang.org/p/Kmih0YUS0N">http://play.golang.org/p/Kmih0YUS0N</a>.

Of course, since the function *does* accept that many arguments, it's not correct. The
error is really more like a type error, or &quot;incorrect number of arguments before
final slice argument&quot; or something like that.</pre>

**Comment by odeke-em** [comment]
I think when CL https://go-review.googlesource.com/#/c/25156 is merged or if https://github.com/golang/go/issues/4215 is fixed, so will this issue be fixed too /cc @josharian.
The result will be something like
```shell
$ go run Kmih0YUS0N.go 
# command-line-arguments
./Kmih0YUS0N.go:17: too many arguments in call to printmany, got (untyped number, []int) want (...int)
```
