### ISSUE TITLE
access: request gomote access

### ISSUE THREAD

**Issue by rhysh** [golang/go#67518]
I'd like access to gomote, please. (I didn't quite get it set up after the 2022 permissions change, see #49151.) The Google account I use to log in to Gerrit is `rhys.hiltner@gmail.com`.

Thanks!

"See https://go.dev/wiki/Gomote#access."

**Comment by mauri870** [comment]
cc @golang/release

**Comment by rhysh** [comment]
Hi @cagedmantis @golang/release , I know you're on top of this already — thank you.

I've run into a problem with a recently merged change (https://go.dev/cl/585638) on a secondary port that I can't otherwise access. (Trybots would probably work, though slowly.) I'm nervous about lack of gomote making it hard for me to debug that before the team reverts that CL stack and the release freeze sets in.

Hopefully, there's no need to revert, and there's still time for me to submit the necessary fix. But if you'd be able to grant me this access, it would help me to meet the freeze deadline. Thanks.

**Comment by cagedmantis** [comment]
Your account should have access now. Thank you for your contributions to Go!

**Comment by rhysh** [comment]
All set, yes. Thank you!
