### ISSUE TITLE
proposal: Go 2: Let the parallel computing part in Goroutine run on CUDA-like core

### ISSUE THREAD

**Issue by For-ACGN** [golang/go#67511]
### Go Programming Experience

Experienced

### Other Languages Experience

C, x86_64 ASM, C#, Python

### Related Idea

- [ ] Has this idea, or one like it, been proposed before?
- [ ] Does this affect error handling?
- [ ] Is this about generics?
- [X] Is this change backward compatible? Breaking the Go 1 compatibility guarantee is a large cost and requires a large benefit

### Has this idea, or one like it, been proposed before?

No

### Does this affect error handling?

No

### Is this about generics?

No

### Proposal

Let the parallel computing part in Goroutine run on CUDA-like core to achieve parallel computing acceleration.

Today I saw a new programming language on GitHub: 
 [https://github.com/HigherOrderCO/Bend](https://github.com/HigherOrderCO/Bend)
 [https://github.com/HigherOrderCO/hvm](https://github.com/HigherOrderCO/hvm)

Bend is a massively parallel, high-level programming language.

Unlike low-level alternatives like CUDA and Metal, Bend has the feeling and features of expressive languages like Python and Haskell, including fast object allocations, higher-order functions with full closure support, unrestricted recursion, even continuations. Yet, it runs on massively parallel hardware like GPUs, with near-linear speedup based on core count, and zero explicit parallel annotations: no thread spawning, no locks, mutexes, atomics. 

If we can let some pure computing code Goroutine run on CUDA-like core, it will greatly improve the performance of Go.

But there are some difficulties below that I don’t know whether they can be solved.
  1. Context issues when Goroutine switches between CPU and GPU.
  2. When parallel computing can be achieved, Goroutine is moved to CUDA-like core to run, and when instructions similar to syscall are executed, it is moved to the CPU to run. However, synchronization of data in memory and VRAM is a problem.
  3. How do you let the compiler know which code is suitable for computing on the GPU, perhaps through special compiler directives or syntax prefixes?
  4. Users may need to install additional CUDA Toolkit, but similar to cgo, we also need to install additional c compiler.
  
Although the existing Go language can easily run a large number of Goroutines on several CPU cores, it would be very dreamy if we could move some of the Goroutines used for calculations to the GPU for execution.

### Is this change backward compatible?

Yes

**Comment by seankhliao** [comment]
this doesn't look like a concrete proposal we can evaluate, more a starting point for a discussion on how the language might change to enable this. please use the forums for such discussions.
