### ISSUE TITLE
x/pkgsite: package removal request for bitbucket.org/s11006/testmod

### ISSUE THREAD

**Issue by s11006** [golang/go#67524]
Please remove the module bitbucket.org/s11006/testmod and the package test1
Unfortunately, the module and the package were published by mistake.
The code has no special value and there is no need for it to clutter the pkg.go.dev
The module has been marked as retracted.

I am the owner of the account s11006 on bitbucket.org.

Thank you for your help.

**Comment by hyangah** [comment]
The module is still available in public domain. Can you make it private, delete, or use retract (https://go.dev/about#removing-a-package)?

**Comment by s11006** [comment]
The module is already private.

**Comment by suzmue** [comment]
Removed from pkgsite
