### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by inanzhi** [golang/go#67522]
### What is the URL of the page with the issue?
 
 nothing
 
### What is your user agent?
 Goland

 
 
 
### Screenshot
 
![image](https://github.com/golang/go/assets/48210582/c0b64813-c968-4f18-a819-6fcc4098ecfd)

 
 
 
<img width="960" alt="1" src="https://github.com/golang/go/assets/48210582/e8ece265-4cda-496d-8f8e-78827b45d22b">
<img width="774" alt="Snipaste_2024-05-20_14-13-20" src="https://github.com/golang/go/assets/48210582/1f73473f-46e4-4d6d-bce7-e0669e40cefa">

### What did you do?
 

 
 I just want use the fmt.Println() as a newline

 
### What did you expect to see?
 
My data print is well
 
 
### What did you see instead?

My data print is lost a little

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
