### ISSUE TITLE
go/types, types2: audit type assertions for potential Alias bugs

### ISSUE THREAD

**Issue by findleyr** [golang/go#67547]
#67540 fixes a bug where GODEBUG=gotypesalias=1 (the default in go 1.23) results in a type checker bug.

While reviewing the fix (https://go.dev/cl/587075), I noticed that right above that bug, there is [another](https://go-review.git.corp.google.com/c/go/+/587075/1/src/cmd/compile/internal/types2/conversions.go#148), allowing the following program to compile without error (the error comes from vet, not type checking, which may actually indicate another bug: is vet not honoring GODEBUG?):
 
https://go.dev/play/p/cy0Jma_6jAA?v=gotip

It appears that we need to more thoroughly audit type assertions within the type checker.

CC @griesemer @adonovan

**Comment by griesemer** [comment]
There are many assertions with type parameters that seem incorrect. I will take this on.

**Comment by griesemer** [comment]
With these most recent CLs I believe the major issues here are covered.
There are still a few cases (in type inference, in the mono checker) which need attention, but I am not yet sure they are wrong. I will try to create test cases for these as well.

But I think for the freeze we're ok on this front. We may find more regressions but once found, they are easy to address.

**Comment by griesemer** [comment]
All type assertions and type switches in go/types, types2, have been reviewed and updated as needed.
Closing this as completed.
