### ISSUE TITLE
x/pkgsite: package removal request for github.com/flc1125/go-twca/mid

### ISSUE THREAD

**Issue by flc1125** [golang/go#67567]
I accidentally published: `github.com/flc1125/go-twca/mid`, but what I actually want to keep is: `github.com/flc1125/go-twca`. So please help me delete: `github.com/flc1125/go-twca/mid`.

I am the owner of the repository, which can be verified through the address.

Thank you very much.

**Comment by hyangah** [comment]
@jba Is it currently feasible to hide github.com/flc1125/go-twca/mid (module), but leave github.com/flc1125/go-twca/mid (pkg of github.com/flc1125/go-twca@v1.0.5)?

**Comment by ansaba** [comment]
@flc1125 , it will exclude all the child packages of /flc1125/go-twca/mid also from pkgsite. Is it what you intend ?

**Comment by flc1125** [comment]
Yes, or if there is anything I need to do that would be more convenient to operate, you can also tell me.

**Comment by suzmue** [comment]
Hi @flc1125!

So just to clarify, if we remove the documentation for https://pkg.go.dev/github.com/flc1125/go-twca/mid it will also get rid of the documentation for https://pkg.go.dev/github.com/flc1125/go-twca@v1.0.5/mid (and all other versions of this package). If that works for you we can just delete the documentation for both of these, but the go command will still be able to see both packages.

If you do want to have users for https://pkg.go.dev/github.com/flc1125/go-twca@v1.0.5/mid, you probably will want to [retract](https://go.dev/ref/mod#go-mod-file-retract) all versions of https://pkg.go.dev/github.com/flc1125/go-twca/mid. I can see that the module proxy has a copy of v1.0.0 for module github.com/flc1125/go-twca/mid (https://proxy.golang.org/cached-only/github.com/flc1125/go-twca/mid/@v/v1.0.0.info) and your documentation for https://pkg.go.dev/github.com/flc1125/go-twca@v1.0.5/mid links to the "latest" version, which is that module you are trying to delete. The go command prefers github.com/flc1125/go-twca/mid to github.com/flc1125/go-twca when matching on the package.

To retract all versions of github.com/flc1125/go-twca/mid, you will want to:
1. Add back the go.mod file in [github.com/flc1125/go-twca/mid](https://github.com/flc1125/go-twca/tree/master/mid).
2. Add a [retract](https://go.dev/ref/mod#go-mod-file-retract) directive to the go.mod
```
retract [v0.0.0-0, v1.0.1]  // assuming v1.0.1 contains this retraction.
```
3. Tag `mid/v1.0.1`
4. Delete the go.mod in [github.com/flc1125/go-twca/mid](https://github.com/flc1125/go-twca/tree/master/mid)

And that should take care of it! If you have any questions about this process or any of this didn't make sense feel free to ask.

**Comment by flc1125** [comment]
@suzmue Hello, I would like to know about this part `retract [v0.0.0-0, v1.0.1]`, should it be added under `/mid/go.mod` or `/go.mod`? I tried placing it under `/mid/go.mod`, but I noticed that https://pkg.go.dev/github.com/flc1125/go-twca/mid still exists.

Sure, here is your translated text:

Here are my adjustments and the related versions:

- https://github.com/flc1125/go-twca/pull/8
- https://github.com/flc1125/go-twca/tree/mid/v1.0.1

**Comment by flc1125** [comment]
@suzmue However, I tried importing the mid package, and I found that it works correctly.

```
go: finding module for package github.com/flc1125/go-twca/mid
go: downloading github.com/flc1125/go-twca v1.0.6
go: found github.com/flc1125/go-twca/mid in github.com/flc1125/go-twca v1.0.6
```

**Comment by flc1125** [comment]
I think it has resolved my issue. Thank you all very much for your assistance.

@ansaba @hyangah @suzmue @seankhliao @jba
