### ISSUE TITLE
all: binary size regression

### ISSUE THREAD

**Issue by prattmic** [golang/go#67588]
The [performance dashboard](https://perf.golang.org/dashboard/?benchmark=all) shows pretty significant regressions in binary size across most (all?) binary size benchmarks. Look for the "total-bytes" graphs. Regressions vary from around +2% to +30%.

A [specific example](https://perf.golang.org/dashboard/?benchmark=Gonum_community&unit=total-bytes) shows that the regression occurred between [`647870b`](https://go.googlesource.com/go/+show/647870becc230b022b431a4ef8b7c9b31382db6c) and [`814e72f`](https://go.googlesource.com/go/+show/814e72f2ef280da54d1af8088b9a732fda9f217b).

Full log: https://go.googlesource.com/go/+log/647870becc230b022b431a4ef8b7c9b31382db6c..814e72f2ef280da54d1af8088b9a732fda9f217b

[`814e72f`](https://go.googlesource.com/go/+/814e72f2ef280da54d1af8088b9a732fda9f217b) [go/types, types2: don't panic converting a constant to aliased type parameter](https://go.googlesource.com/go/+/814e72f2ef280da54d1af8088b9a732fda9f217b)
[`816b603`](https://go.googlesource.com/go/+/816b6031febc51692eb667df7498f3b2332987fa) [go/types, types2: add missing Unalias calls (clarification)](https://go.googlesource.com/go/+/816b6031febc51692eb667df7498f3b2332987fa)
[`7164fad`](https://go.googlesource.com/go/+/7164fad87a3be06220771f2ae497cb15ef467e31) [net/http: disable flaky 100-continue tests](https://go.googlesource.com/go/+/7164fad87a3be06220771f2ae497cb15ef467e31)
[`5a9dabc`](https://go.googlesource.com/go/+/5a9dabc2ba873f89a5de9ff53c8eab7c96d0c6b5) [cmd/compile: for rangefunc, add checks and tests, fix panic interactions](https://go.googlesource.com/go/+/5a9dabc2ba873f89a5de9ff53c8eab7c96d0c6b5)
[`6438658`](https://go.googlesource.com/go/+/643865856c535a5a644201c602b18bd87b121c93) [cmd/compile: Fix SSA building bug for CAS atomics on ARM64](https://go.googlesource.com/go/+/643865856c535a5a644201c602b18bd87b121c93)
[`1a349fc`](https://go.googlesource.com/go/+/1a349fc92b0d1ea652a164243f850eb542d0924c) [unsafe: document the behavior of Sizeof on an interface](https://go.googlesource.com/go/+/1a349fc92b0d1ea652a164243f850eb542d0924c)
[`180ea45`](https://go.googlesource.com/go/+/180ea45566d19e60aa2d660f6139b7f6e18ff56b) [runtime/coverage: remove uses of //go:linkname](https://go.googlesource.com/go/+/180ea45566d19e60aa2d660f6139b7f6e18ff56b)

cc @golang/compiler

**Comment by prattmic** [comment]
Looks like the cause is [180ea45](https://go.googlesource.com/go/+/180ea45566d19e60aa2d660f6139b7f6e18ff56b) / https://go.dev/cl/585820.

```
$ go test -c gonum.org/v1/gonum/graph/community
```

`community.test` is 4616661 bytes at [647870b](https://go.googlesource.com/go/+show/647870becc230b022b431a4ef8b7c9b31382db6c) and 5377941 bytes at [180ea45](https://go.googlesource.com/go/+/180ea45566d19e60aa2d660f6139b7f6e18ff56b) (+16%).

These binary size benchmarks all happen to be test binaries. I'm guessing the new `internal/coverage/cfile` test dependency is bigger than expected.

Since this is only test binaries, it seems a bit less concerning. Still, it is surprising that what is theoretically "just" a refactor has such a big binary size impact.

cc @rsc @thanm @cherrymui

**Comment by cherrymui** [comment]
My guess is that previously the coverage stuff is only built if coverage is enabled. Now it is always built, just disabled if -cover is not set.

**Comment by thanm** [comment]
I have some ideas on how to fix this, I'll look into it this morning.
