### ISSUE TITLE
go/types, types2: does not see duplicate methods

### ISSUE THREAD

**Issue by AlphaHot** [golang/go#67582]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.22.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/AlphaHot/.cache/go-build'
GOENV='/home/AlphaHot/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/AlphaHot/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/AlphaHot/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22.2'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/AlphaHot/lg/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build149263860=/tmp/go-build -gno-record-gcc-switches'
uname -sr: Linux 4.18.0-26-generic
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic
/lib/x86_64-linux-gnu/libc.so.6: GNU C Library (Ubuntu GLIBC 2.28-0ubuntu1) stable release version 2.28.
gdb --version: GNU gdb (Ubuntu 8.2-0ubuntu1) 8.2
</pre></details>

### What did you do?
https://go.dev/play/p/esbx12UNVzc?v=gotip

### What did you expect to see?
```
./prog.go:14:3: duplicate method `a'
	./prog.go:13:3: other declaration of `a'
```

### What did you see instead?
```
:/
```

**Comment by go101** [comment]
This is allowed, as long as the duplicated methods have the identical signature.
