### ISSUE TITLE
proposal: runtime/dependencies

### ISSUE THREAD

**Issue by xin-tsla** [golang/go#67590]
### Proposal Details

Hi,
It would be great that golang could provide dependencies info like package name and theirs versions to runtime.

**Comment by seankhliao** [comment]
see runtime/debug.BuildInfo

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by xin-tsla** [comment]
Thanks for the info! @seankhliao
