### ISSUE TITLE
x/tools/go/packages: documentation on overlays is incomplete

### ISSUE THREAD

**Issue by dominikh** [golang/go#67601]
The documentation of Config.Overlay says

> Overlays provide incomplete support for when a given file doesn't
> already exist on disk. See the package doc above for more details.

but the package documentation doesn't talk about overlays at all.

**Comment by dominikh** [comment]
Apparently this is part of `doc.go`, but only as an internal comment, not part of the package documentation. I'm not sure it's relevant anymore, either.

**Comment by cagedmantis** [comment]
cc [@matloob](https://github.com/matloob)
