### ISSUE TITLE
cmd/compile: error message refers to aliased type instead of the alias type name

### ISSUE THREAD

**Issue by griesemer** [golang/go#67628]
```Go
package p

func f[P any](x P) P { return x }

func _() {
	type A = int
	var a A
	b := f(a) // type of B is A
	_ = b + "foo"
}
```
produces
```
...: invalid operation: b + "foo" (mismatched types int and untyped string)
```
It should say:
```
mismatched types A and untyped string
```

cc: @findleyr

**Comment by griesemer** [comment]
Related to #67547.

**Comment by findleyr** [comment]
Presumably this is because the inference algorithm strips alias information. I would expect that the type of b is int, not A.
This may be difficult to fix.

**Comment by griesemer** [comment]
> I would expect that the type of b is int, not A.

That's what the error message says. But I think it should say `A`. Not sure why you say it should be `int`.

**Comment by findleyr** [comment]
> > I would expect that the type of b is int, not A.
> 
> That's what the error message says. But I think it should say `A`. Not sure why you say it should be `int`.

I merely meant that the type *is* int, not that it should be int. In other words, the problem is inference, not the error message.
