### ISSUE TITLE
json: Marshaler with promote

### ISSUE THREAD

**Issue by ZenLiuCN** [golang/go#67630]
### Go version

go version go1.21.4 windows/amd64

### Output of `go env` in your module/workspace:

```shell
not important
```

### What did you do?

https://go.dev/play/p/54GOWukObl0

Not really sure it should be a BUG or not.
```go

package main

import (
	"encoding/json"
	"fmt"
)

func main() {
	v, err := json.Marshal(&Some{nil})
	fmt.Printf("%s,%s", string(v), err)
}

type Some struct {
	*SomeMarshal
}
type SomeMarshal struct {
	Name string
}

func (s *SomeMarshal) MarshalJSON() ([]byte, error) {
	return json.Marshal(s.Name)
}
```

### What did you see happen?

panic of `invalid memory address or nil pointer dereference`

### What did you expect to see?

not sure now.

**Comment by seankhliao** [comment]
this is working as intended

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
