### ISSUE TITLE
proposal: strings: add a ReplaceRange function

### ISSUE THREAD

**Issue by Mutoxicated** [golang/go#67643]
### Proposal Details

It's niche but it's nice when it's there.

**Comment by randall77** [comment]
We're going to need more detail than that.
What is the function signature? Argument/results types and names?
What is it supposed to do? A prototype go doc string would help.

**Comment by leb-kuchen** [comment]
This is the rust version: https://doc.rust-lang.org/stable/std/string/struct.String.html#method.replace_range
So I guess, the function signature would be:
```go
// Removes the range [i, j) and replaces it with new. Panics if the range is out of bounds.
func ReplaceRange(s, new string, i,  j int) string
```

**Comment by leb-kuchen** [comment]
So it would be essentially slices.Replace for strings I guess.

**Comment by randall77** [comment]
You can just do `s[:i] + new + s[j:]`, which is shorter and arguably clearer than `strings.ReplaceRange(s, new, i, j)`.

**Comment by go101** [comment]
`s[:i] + new + s[j:]` needs 2 allocations, but `ReplaceRange` only needs one.

From performance views, the `strings`/`bytes` functions which need allocations should have a version with a `writer` parameter.
But Go often favors simplicity over efficiency.

**Comment by go101** [comment]
I think producing `new` needs an extra allocation.

**Comment by leb-kuchen** [comment]
He is referring to a compiler optimization,which may exist.

**Comment by leb-kuchen** [comment]
This pattern is not very common, you need to index the string, so it is also not less error prone. Maybe the slices.Replace version makes more sense, since it less likely to be optimized.

**Comment by earthboundkid** [comment]
```
func sreplace(s, new string, i, j int) string {
	return s[:i] + new + s[j:]
}

var sink string

allocs := testing.AllocsPerRun(10, func() {
	sink = sreplace("Hello, world!", "W", 7, 8)
})
```

This is reporting 1 for me, although it could be an artifact of it s and new being constants.

**Comment by Mutoxicated** [comment]
> We're going to need more detail than that. What is the function signature? Argument/results types and names? What is it supposed to do? A prototype go doc string would help.

```go
func ReplaceRange(s, new string, i, j int) string {
    return s[:i] + new + s[j:]
}
```
My bad I didn't initially provide a prototype.

> You can just do `s[:i] + new + s[j:]`, which is shorter and arguably clearer than `strings.ReplaceRange(s, new, i, j)`.

It might be shorter, however I would argue that ReplaceRange has way clearer intent than `s[:i] + new + s[j:]`.

**Comment by leb-kuchen** [comment]
```
func randString(n int) string {
	s := make([]byte, n)
	for i := range s {
		s[i] = rand.N(byte(127))

	}
	return string(s)
}
s := randString(20)
new := randString(5)

func sreplace(s string, i, j int, new ...string) string {
	r := s[:i]
	for _, n := range new {
		r += n
	}
	r += s[j:]
	return r
}
```
This performs actually 2 allocations, I guess you would have to use a string builder.

**Comment by go101** [comment]
I assumed that `ReplaceRange(s, i, j, new)` means `s[:i] + strings.ReplaceAll(s[i:j], new) + s[j:]`. Not? :D

**Comment by randall77** [comment]
> I assumed that ReplaceRange(s, i, j, new) means s[:i] + strings.ReplaceAll(s[i:j], new) + s[j:]. Not? :D

One of the reasons why `s[:i] + new + s[j:]` is clearer.

**Comment by Mutoxicated** [comment]
> I think there's some confusion here about what the proposal is. I thought it was:
> 
> ```
> func ReplaceRange(s, new string, i,  j int) string
> ```
> 
> but some of the allocation arguments are assuming it is
> 
> ```
> func ReplaceRange(s, news []string, i,  j int) string
> ```
> 
> or perhaps
> 
> ```
> func ReplaceRange(s, i,  j int, new ...string) string
> ```
> 
> Which one are we looking at?
> 
> Keep in mind that allocation is kind of a secondary concern. Primarily we want a clean, easy to understand API.

The first option. This is the prototype we can build off of:

```go
// Removes the range [i, j) and replaces it with new. Panics if the range provided is out of bounds.
func ReplaceRange(s, new string, i, j int) string {
    return s[:i] + new + s[j:]
}
```

As for the clarity between  `s[:i] + new + s[j:]` and the `si[:i] + strings.ReplaceAll(s[i:j], new) + s[j:]`, the description of the function should clarify that it is not the latter.

What do you guys think?

**Comment by go101** [comment]
If it is unrelated to `strings.ReplaceAll`, then `s[:i] + new + s[j:]` is indeed the idiomatic way to do the thing in Go.
In Go, it is seldom to use slice indexes as function parameters (except several ones in the `slices` package).
