### ISSUE TITLE
cmd/cgo/internal/swig,cmd/go,x/build: swig cgo tests incompatible with C++ toolchain on builders

### ISSUE THREAD

**Issue by mknyszek** [golang/go#67698]
After updating the builder images to have a gcc-based C++ toolchain, the clang and 386 builders began failing. This appears to be because the toolchain that's installed is either incompatible with the object files produced by cgo and the Go toolchain (my theory for clang) or the toolchain just can't properly cross-compile (my theory for 386).

Thing is, these tests were already getting skipped 100% of the time, or not running at all, looking at the history. So for now, they're skipped once again. This bug tracks possibly enabling these tests, but I don't think they're a particularly high priority.

Example failures:
- https://ci.chromium.org/ui/p/golang/builders/ci/gotip-linux-386/b8746588762099038993/overview
- https://ci.chromium.org/ui/p/golang/builders/ci/gotip-linux-386-clang15/b8746588763037378577/overview
- https://ci.chromium.org/ui/p/golang/builders/ci/gotip-linux-amd64-clang15/b8746588762291961633/overview

**Comment by mknyszek** [comment]
Erroneously closed, but will be closed soon.

**Comment by dmitshur** [comment]
@gopherbot Please consider this for backport, in particular [CL 589295](https://go.dev/cl/589295) and [CL 589296](https://go.dev/cl/589296). They apply test-only fixes that are needed to fix builder failures in newly running tests after a builder change.
