### ISSUE TITLE
x/tools/go/packages: Load(&cfg...) modifies cfg, contra explicit documentation

### ISSUE THREAD

**Issue by adonovan** [golang/go#67702]
The Load function claims not to mutate the Config, but it does in fact mutate the non-exported fields, and has done for some time. In https://go.dev/cl588936 I proposed to update the docs to match reality:

```go
// Calls to [Load] do not modify the public fields of this struct, but
// may modify hidden fields, so concurrent calls to [Load] must not
// use the same Config.
```

but perhaps we should instead reestablish the invariant rather than give it up.

@findleyr @matloob

**Comment by xieyuschen** [comment]
Hi @adonovan , I have sent you a CL by moving all unexport fields from `Config` to an unexported config struct so `packages.Load` won't modify user provided Config in any case. Let me know whether you like this approach:)
