### ISSUE TITLE
net/http: switch default HTTP/2 write scheduler to round robin [freeze exception]

### ISSUE THREAD

**Issue by neild** [golang/go#67706]
About a year ago, we changed the default HTTP/2 write scheduler in golang.org/x/net/http2. https://go.dev/cl/478735 and https://go.dev/issue/58804 contain context and discussion, but the quick summary is that the previous scheduler is slow, buggy, and implements a deprecated stream prioritization scheme with essentially no adoption in the wild.

Unfortunately, I missed at the time that the net/http package is explicitly enabling the priority scheduler, so changing the x/net/http2 default didn't affect the net/http defaults.

We should change the net/http default as well.

I am requesting a freeze exemption, because I'd hate for us to go another release with a bad default. All users who override the bundled HTTP/2 implementation in net/http with the one from golang.org/x/net/http2 have been getting the new default for the last year, so I believe this is a very low risk change.

CC @golang/release

**Comment by dmitshur** [comment]
We reviewed this in a meeting, and agreed to approve its "freeze exception" bit. Thanks for letting us know.
