### ISSUE TITLE
`go help get` output doesn't document `-d` flag

### ISSUE THREAD

**Issue by UlrichEckhardt** [golang/go#67728]
### Go version

go version go1.20.7 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/uli/.cache/go-build"
GOENV="/home/uli/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/uli/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/uli/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.20"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.20/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.7"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/uli/api-broker-prototype/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2758415129=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

I ran `go help get`.

### What did you see happen?

I got a bunch of help text output, but none explains the `-d` flag. In the output, it says "usage: go get [-t] [-u] [-v] [build flags] [packages]", which kind-of hints at "build flags" being available, but there is no indication which of them are.

### What did you expect to see?

Starting with `go help get`, I should be able to explore (maybe with additional calls to `go help ..`) the valid set of flags.

**Comment by seankhliao** [comment]
The `-d` flag no longer has any effect.

**Comment by UlrichEckhardt** [comment]
Okay, but what is "[build flags]"?

**Comment by ianlancetaylor** [comment]
For build flags, see `go help build`.

I'm not sure why you are asking about the `-d` flag.  I don't see it mentioned in the documentation.

**Comment by UlrichEckhardt** [comment]
Thanks for your response, Ian. I initially stumbled over the `-d` flag in a CI/CD pipeline I was working on and wondered what it does. I couldn't find anything in the `go help get` output, apart from perhaps the `[build flags]` placeholder. However, I couldn't find any hints what that placeholder is for.

So, just to make clear what improvement I'm suggesting here:

- Make it clear what the build flags are from the `go help get` output. You could e.g. include the list of them or refer to `go help build`, but make that explicit about the build flags.
- Make it clear that `-d` is supported in that it is ignored. You could document it in the help output or even output a deprecation warning when it's used. Or, perhaps, reject it altogether.
