### ISSUE TITLE
os/signal: SIGSYS documented as both handled and unhandled

### ISSUE THREAD

**Issue by hdonnay** [golang/go#67729]
### Go version

go 1.22.3

### Output of `go env` in your module/workspace:

```shell
N/A
```

### What did you do?

Visited https://pkg.go.dev/os/signal

### What did you see happen?

The documentation claims both:

> A SIGQUIT, SIGILL, SIGTRAP, SIGABRT, SIGSTKFLT, SIGEMT, or SIGSYS signal causes the program to exit with a stack dump.

and

> It also applies to some signals that otherwise cause no action: SIGUSR1, SIGUSR2, SIGPIPE, SIGALRM, SIGCHLD, SIGCONT, SIGURG, SIGXCPU, SIGXFSZ, SIGVTALRM, SIGWINCH, SIGIO, SIGPWR, SIGSYS, SIGINFO, SIGTHR, SIGWAITING, SIGLWP, SIGFREEZE, SIGTHAW, SIGLOST, SIGXRES, SIGJVM1, SIGJVM2, and any real time signals used on the system.

`SIGSYS` should be removed from whichever list is incorrect.

### What did you expect to see?

`SIGSYS` listed as exactly one of handled or unhandled.

**Comment by mknyszek** [comment]
CC @golang/runtime

**Comment by ianlancetaylor** [comment]
Thanks for noticing.  Sending a fix.
