### ISSUE TITLE
x/website: typo in tutorial "getting started with multi-module workspaces"

### ISSUE THREAD

**Issue by jeffreyhilaire** [golang/go#67740]
### What is the URL of the page with the issue?
 https://go.dev/doc/tutorial/workspaces
 
### What is your user agent?
 [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36](https://explore.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)

### Screenshot
![image](https://github.com/golang/go/assets/15076256/2a30aa67-52c0-45f3-aa0e-502610025272)

### What did you do?
This is a typo, not a behavioral bug so no action needed.
 
### What did you expect to see?
I expected the sentence to read "The **workspace** now includes both the example.com/hello module and the golang.org/x/example/hello module, which provides the golang.org/x/example/hello/reverse package."
 
### What did you see instead?
The sentence reads "The module now includes both the example.com/hello module and the golang.org/x/example/hello module, which provides the golang.org/x/example/hello/reverse package."

**Comment by mknyszek** [comment]
CC @matloob maybe?

@jeffreyhilaire if you're up for it, feel free to send a PR to https://github.com/golang/website.

**Comment by matloob** [comment]
@jeffreyhilaire I have a change that fixes it though I can retract it if you're interested in sending a PR.

https://go-review.git.corp.google.com/c/website/+/590043

**Comment by jeffreyhilaire** [comment]
@matloob thank you for the quick fix.
