### ISSUE TITLE
x/tools/gopls: TestBrokenWorkspace_GOPACKAGESDRIVER is broken on legacy builders

### ISSUE THREAD

**Issue by findleyr** [golang/go#67747]
TestBrokenWorkspace_GOPACKAGESDRIVER is deterministically failing on legacy builders. It looks like this is caused by mismatching file paths due to symlinks.

**Comment by findleyr** [comment]
Reassigning @adonovan as he was able to reproduce locally and root-cause.

**Comment by adonovan** [comment]
Fixed by workaround in  https://go.dev/cl/588767. See https://github.com/golang/go/issues/67757 for a principled solution.
