### ISSUE TITLE
access: Remove me as maintainer

### ISSUE THREAD

**Issue by laboger** [golang/go#67759]
Today is my last day at IBM, so please remove my name from the @golang/ppc64 maintainer list. There are still enough others listed who will continue to do a fine job.

Also my email address laboger@linux.vnet.ibm.com will no longer be active.

Thanks for the adventure of working on Go.

**Comment by ianlancetaylor** [comment]
Sorry to see you go.  Thanks for all the great work over the years.

**Comment by rsc** [comment]
Thanks very much for all your contributions @laboger!

**Comment by dr2chase** [comment]
I just learned of this, I very much enjoyed working with you on all things in the intersection of Go and IBM.
