### ISSUE TITLE
time: Parse formats allow ambiguity

### ISSUE THREAD

**Issue by m-messiah** [golang/go#67750]
### Go version

go version go1.22.3 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE='on'
GOARCH='arm64'
GOOS='darwin'
```

### What did you do?

Time Parse always assumes RFC3339 date and does not allow to change it.

For example https://go.dev/play/p/1gWqncWgd0_h:
```go
a, err := time.Parse("2006-21-01", "2024-23-03")
```

expected to parse the date as 23 March 2024, but fails with error `parsing time "2024-23-03" as "2006-21-01": cannot parse "-03" as "1"`

Moreover, time.DateOnly format (as well as time.DateTime) assume RFC3339 with ambiguity to anyone who does not follow the RFC, as both `01` and `02` could be treated as Month
https://github.com/golang/go/blob/5bf8c0cf09ee5c7e5a37ab90afcce154ab716a97/src/time/format.go#L123-L124

### What did you see happen?

https://go.dev/play/p/qnIFX3Q_zUL

```console
1 January 1 parsing time "2024-23-03" as "2006-21-01": cannot parse "-03" as "1"
2006-01-02
```

### What did you expect to see?

Expect `time.Parse` to follow the format provided without hidden assumptions leading to errors.
Expect time.DateOnly and time.DateTime to provide self-explanatory format without ambiguity.

**Comment by seankhliao** [comment]
That's the wrong layout to use. `time.Parse` correctly treated it as: 
- `2006`: `2004`
- `-`: `-`
- `2`: `23`
- `1`: `-03`, an error

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by m-messiah** [comment]
Ok, I reread the Layout comment and it has some handy things about Day and Month:
https://github.com/golang/go/blob/5bf8c0cf09ee5c7e5a37ab90afcce154ab716a97/src/time/format.go#L60-L62

saying month is always `01` and day is always `02`, meaning my playground could be rewritten as https://go.dev/play/p/CcPYcJ5rRPN

And it works, correctly returning the 23 of March, but `go vet` sends warning about such format after https://github.com/golang/go/issues/48801.

**Comment by rsc** [comment]
Where did you encounter yyyy-dd-mm dates? When we accepted #48801, we believed they were exceedingly rare.
