### ISSUE TITLE
github: issue template should prompt if toolchain is go1.23 and above use go env -changed report bug

### ISSUE THREAD

**Issue by qiulaidongfeng** [golang/go#67767]
See #34208 , it background is that report an bug usually require the user to provide a `go env`, which has a problem the output is getting larger and larger, and most of it is usually useless.
Now that `go env -changed` has been added, issue template should prompt the user to use it when the toolchain is greater than or equal to go1.23.

**Comment by ianlancetaylor** [comment]
`go env -changed` is not enough.  In particular we really need `go env GOOS` and `go env GOARCH` and `go env GOVERSION`.

**Comment by qiulaidongfeng** [comment]
> `go env -changed` is not enough. In particular we really need `go env GOOS` and `go env GOARCH` and `go env GOVERSION`.

issue template need `go version` output , it contain GOOS GOARCH GOVERSION

**Comment by seankhliao** [comment]
I don't think we should do this. the full set of env vars is quite useful in picking out details which the reporter may not have otherwise thought to tell us about.

**Comment by seankhliao** [comment]
I think we can decline this for the same reason as #67769
