### ISSUE TITLE
cmd/go: `go bug` should use `go env -changed`

### ISSUE THREAD

**Issue by qiulaidongfeng** [golang/go#67769]
### Go version

tip

### Output of `go env` in your module/workspace:

```shell
no need.
```

### What did you do?

go bug

### What did you see happen?

use  `go env` report issue.

### What did you expect to see?

use  `go env -changed` report issue.

**Comment by ianlancetaylor** [comment]
We need more than just the changed variables.

**Comment by qiulaidongfeng** [comment]
> We need more than just the changed variables.

If GOOS GOARCH GOVERSION is needed I have run the go bug on my computer, it contain <pre>
$ go version
go version devel go1.23-2f642683 Fri May 17 01:23:00 2024 +0000 windows/amd64
</pre>

**Comment by seankhliao** [comment]
the full set of settings is useful for us to pick out details that the reporter may have omitted themselves. 
`-changed` should only be used when we're unsure where those settings came from.

**Comment by matloob** [comment]
I don't think we should do this.

**Comment by qiulaidongfeng** [comment]
> the full set of settings is useful for us to pick out details that the reporter may have omitted themselves. `-changed` should only be used when we're unsure where those settings came from.

If an environment variable does not print in go env -changed, except implementation bug and having a different $GOROOT/go.env or environment variable non have default value, if the other environment variable is not printed, it means that it is now the default value, and can get the same without setting the environment variable on your computer.

**Comment by seankhliao** [comment]
> except implementation bug and having a different $GOROOT/go.env or environment variable non have default value

I think this is too big of a caveat to ignore.
Also, the default value may not be the same for all environments, e.g.
`GOMOD`, `GOWORK` will print the resolved values.

**Comment by matloob** [comment]
We're not going to do this. Closing.
