### ISSUE TITLE
os/signal: documentation clarification

### ISSUE THREAD

**Issue by withinboredom** [golang/go#67773]
### Go version

1.23

### Output of `go env` in your module/workspace:

```shell
N/A
```

### What did you do?

The current [documentation](https://pkg.go.dev/os/signal#hdr-Go_programs_that_use_cgo_or_SWIG) reads:

> The non-Go code should not change the signal mask on any threads created by the Go runtime. If the non-Go code starts new threads of its own, it may set the signal mask as it pleases.

But it doesn't state the consequences for doing so or in what conditions it is safe to do so. For example:

```go

func callC() {
  runtime.LockOSThread()
  C.methodThatEventuallyCallsBackToGo()
}

// later
go callC()
```

What exactly would happen to signal masks in this case? Further, is the documentation saying that _only_ if non-go code starts threads, it can set the signal mask, or is it saying that only the children may set signal masks?

### What did you see happen?

Confusing or missing documentation in regards to signal masks.

### What did you expect to see?

More detail and clarification in regards to signal masks in non-go code.

**Comment by ianlancetaylor** [comment]
I don't think the docs should lock us into specific consequences.  I'll change them to read

> The non-Go code should not change the signal mask on any threads created by the Go runtime. If the non-Go code starts new threads itself, those threads may set the signal mask as they please.

**Comment by withinboredom** [comment]
Thank you for the clarification @ianlancetaylor! That's really all I needed to know!
