### ISSUE TITLE
wiki:

### ISSUE THREAD

**Issue by wenglaurie30** [golang/go#67789]
https://cs.opensource.google/firebase-sdk/firebase-js-sdk/+/f49c8b5c50919014d852847c755d0eb13a0fc803:tests/

**Comment by wenglaurie30** [comment]
''Please Help''

**Comment by mknyszek** [comment]
Sorry, but there's not enough information in your issue to do anything. I'm not sure what the Firebase JavaScript SDK (which has little to do with the Go project) has to do with the wiki. Closing this issue.
