### ISSUE TITLE
os: follow-up pidfd fixes [freeze exception]

### ISSUE THREAD

**Issue by prattmic** [golang/go#67826]
This is a freeze exception request for feedback for https://go.dev/cl/588675. This CL is fixing #67634, #67640, and #67641, which are issues with the new pidfd support added in https://go.dev/cl/570036 and https://go.dev/cl/570681.

Since these are regressions, I don't think a freeze exception is strictly necessary, however the fix is a fairly invasive overhaul of the internals of os.Process, which I'd say has a medium risk of introducing new problems. The alternative to submitting this fix now would be to revert the pidfd changes and try again when the dev cycles opens again.

cc @golang/release @kolyshkin

**Comment by kolyshkin** [comment]
I'm still wrapping my head around [CL 588675](https://go.dev/cl/588675) but overall it makes sense. At the very least  #67634 is definitely a bad regression that could hit users hard.

**Comment by prattmic** [comment]
> At the very least #67634 is definitely a bad regression that could hit users hard.

Yes, this is the one issue where I am aware of actual failures (some tests inside Google fail). The others are just problems I noticed when fixing the first.

**Comment by dmitshur** [comment]
We reviewed this in a meeting, and agreed to approve its "freeze exception" bit. Thanks for letting us know.
