### ISSUE TITLE
x/pkgsite: package revert request for github.com/wttech/pulumi-aem/sdk pkgsite

### ISSUE THREAD

**Issue by dominik-przybyl-wttech** [golang/go#67847]
Hi, 
previously I asked for https://github.com/golang/go/issues/67209
Is there any way to revert that operation?

**Comment by findleyr** [comment]
Unfortunately this will require a code change. Over to @jba for additional triage.

**Comment by bd-dominik-przybyl** [comment]
What kind of code change will be required?

**Comment by dominik-przybyl-wttech** [comment]
Hi @jba, could you assist with this issue?

**Comment by jba** [comment]
I hope to have time to look into this next week.

**Comment by dominik-przybyl-wttech** [comment]
@jba, do you have any findings in this topic?

**Comment by jba** [comment]
Sorry, I haven't had a chance to look at this yet.

**Comment by dominik-przybyl-wttech** [comment]
@jba, I hope you're doing well. I'm just following up on the issue we have last contacted about a month ago. I understand you may be busy, so I wanted to check if there's someone else who might be able to assist with this?

**Comment by jba** [comment]
Sorry, there isn't. Hopefully this week.

**Comment by dominik-przybyl-wttech** [comment]
@jbe, any new info

**Comment by jba** [comment]
I have some time this week to work on it.

**Comment by jba** [comment]
Fixed in production.

**Comment by dominik-przybyl-wttech** [comment]
@jba, thank you
