### ISSUE TITLE
go/internal/gccgoimporter: go building failing with gcc 14.1.0

### ISSUE THREAD

**Issue by alex14641** [golang/go#67846]
When building go 1.21.x or 1.22.x with gcc 14.1.0, I get the following error:

ok  	go/importer	0.290s
--- FAIL: TestInstallationImporter (0.01s)
panic: runtime error: index out of range [22] with length 22 [recovered]
	panic: runtime error: index out of range [22] with length 22

goroutine 6 [running]:
panic({0x61b280?, 0xc00001a588?})
	/opt/go1.21.11/src/runtime/panic.go:1017 +0x3ac fp=0xc000082060 sp=0xc000081fb0 pc=0x43698c
testing.tRunner.func1.2({0x61b280, 0xc00001a588})
	/opt/go1.21.11/src/testing/testing.go:1545 +0x238 fp=0xc000082110 sp=0xc000082060 pc=0x4d2098
testing.tRunner.func1()
	/opt/go1.21.11/src/testing/testing.go:1548 +0x397 fp=0xc000082278 sp=0xc000082110 pc=0x4d1b57
runtime.deferCallSave(0xc000082330, 0xc000083f90?)
	/opt/go1.21.11/src/runtime/panic.go:798 +0x84 fp=0xc000082288 sp=0xc000082278 pc=0x436564
runtime.runOpenDeferFrame(0xc000015950)
	/opt/go1.21.11/src/runtime/panic.go:771 +0x1b8 fp=0xc0000822c8 sp=0xc000082288 pc=0x436398
panic({0x61b280?, 0xc00001a588?})
	/opt/go1.21.11/src/runtime/panic.go:914 +0x21f fp=0xc000082378 sp=0xc0000822c8 pc=0x4367ff
runtime.goPanicIndex(0x16, 0x16)
	/opt/go1.21.11/src/runtime/panic.go:114 +0x7c fp=0xc0000823b8 sp=0xc000082378 pc=0x4348dc
go/internal/gccgoimporter.lookupBuiltinType(0x16)
	/opt/go1.21.11/src/go/internal/gccgoimporter/parser.go:929 +0x4cb fp=0xc000082568 sp=0xc0000823b8 pc=0x5ccb2b
go/internal/gccgoimporter.(*parser).parseTypeAfterAngle(0xc000095860, 0x0?, {0x0?, 0x0, 0x0})
	/opt/go1.21.11/src/go/internal/gccgoimporter/parser.go:966 +0x8a fp=0xc000082620 sp=0xc000082568 pc=0x5ccd2a
go/internal/gccgoimporter.(*parser).parseResultList(0xc000095860, 0xc000074de0)
	/opt/go1.21.11/src/go/internal/gccgoimporter/parser.go:747 +0x74 fp=0xc000082678 sp=0xc000082620 pc=0x5cb9b4
go/internal/gccgoimporter.(*parser).parseFunctionType(0x0?, 0xc000058400?, {0x0, 0x0, 0x0})
	/opt/go1.21.11/src/go/internal/gccgoimporter/parser.go:765 +0x9d fp=0xc000082708 sp=0xc000082678 pc=0x5cbb9d
go/internal/gccgoimporter.(*parser).parseFunc(0xc000095860, 0xc000074de0)
	/opt/go1.21.11/src/go/internal/gccgoimporter/parser.go:785 +0xaf fp=0xc000082760 sp=0xc000082708 pc=0x5cbd0f
go/internal/gccgoimporter.(*parser).parseInterfaceType(0xc000095860, 0xc000082858?, {0xc00002f850, 0x1, 0x1})
	/opt/go1.21.11/src/go/internal/gccgoimporter/parser.go:815 +0x250 fp=0xc000082810 sp=0xc000082760 pc=0x5cc0b0
go/internal/gccgoimporter.(*parser).parseTypeSpec(0xc000095860, 0x632438?, {0xc00002f850?, 0x685100?, 0x5f2740?})
	/opt/go1.21.11/src/go/internal/gccgoimporter/parser.go:864 +0xd7 fp=0xc000082868 sp=0xc000082810 pc=0x5cc4d7
go/internal/gccgoimporter.(*parser).parseSavedType(0xc000095860, 0x632438?, 0x50, {0x0?, 0x0, 0x0})
	/opt/go1.21.11/src/go/internal/gccgoimporter/parser.go:1091 +0x45e fp=0xc000082968 sp=0xc000082868 pc=0x5cdf7e
go/internal/gccgoimporter.(*parser).parseTypeAfterAngle(0xc000095860, 0x5f5640?, {0x0?, 0x0, 0x0})
	/opt/go1.21.11/src/go/internal/gccgoimporter/parser.go:951 +0x250 fp=0xc000082a20 sp=0xc000082968 pc=0x5ccef0
go/internal/gccgoimporter.(*parser).parseType(0xc000095860?, 0x685aa0?, {0x0, 0x0, 0x0})
	/opt/go1.21.11/src/go/internal/gccgoimporter/parser.go:937 +0x4f fp=0xc000082a68 sp=0xc000082a20 pc=0x5ccc4f
go/internal/gccgoimporter.(*parser).parseNamedType(0xc000095860, {0xc00002f830?, 0x1, 0x1})
	/opt/go1.21.11/src/go/internal/gccgoimporter/parser.go:566 +0x34a fp=0xc000082b88 sp=0xc000082a68 pc=0x5ca5aa
go/internal/gccgoimporter.(*parser).parseTypeSpec(0xc000095860, 0x632438?, {0xc00002f830?, 0x685100?, 0x5f2740?})
	/opt/go1.21.11/src/go/internal/gccgoimporter/parser.go:850 +0xeb fp=0xc000082be0 sp=0xc000082b88 pc=0x5cc4eb
go/internal/gccgoimporter.(*parser).parseSavedType(0xc000095860, 0x632438?, 0x17, {0x0?, 0x0, 0x0})
	/opt/go1.21.11/src/go/internal/gccgoimporter/parser.go:1091 +0x45e fp=0xc000082ce0 sp=0xc000082be0 pc=0x5cdf7e
go/internal/gccgoimporter.(*parser).parseTypeAfterAngle(0xc000095860, 0x0?, {0x0?, 0x0, 0x0})
	/opt/go1.21.11/src/go/internal/gccgoimporter/parser.go:951 +0x250 fp=0xc000082d98 sp=0xc000082ce0 pc=0x5ccef0
go/internal/gccgoimporter.(*parser).parseResultList(0xc000095860, 0xc000074a20)
	/opt/go1.21.11/src/go/internal/gccgoimporter/parser.go:747 +0x74 fp=0xc000082df0 sp=0xc000082d98 pc=0x5cb9b4
go/internal/gccgoimporter.(*parser).parseNamedType(0xc000095860, {0xc00002e620?, 0x1, 0x1})
	/opt/go1.21.11/src/go/internal/gccgoimporter/parser.go:596 +0x93e fp=0xc000082f10 sp=0xc000082df0 pc=0x5cab9e
go/internal/gccgoimporter.(*parser).parseTypeSpec(0xc000095860, 0x632438?, {0xc00002e620?, 0x685100?, 0x5f2740?})
	/opt/go1.21.11/src/go/internal/gccgoimporter/parser.go:850 +0xeb fp=0xc000082f68 sp=0xc000082f10 pc=0x5cc4eb
go/internal/gccgoimporter.(*parser).parseSavedType(0xc000095860, 0xc000000020?, 0x2, {0x0?, 0x0, 0x0})
	/opt/go1.21.11/src/go/internal/gccgoimporter/parser.go:1091 +0x45e fp=0xc000083068 sp=0xc000082f68 pc=0x5cdf7e
go/internal/gccgoimporter.(*parser).parseTypes(0xc000095860, 0xc000012a00?)
	/opt/go1.21.11/src/go/internal/gccgoimporter/parser.go:1067 +0x472 fp=0xc000083190 sp=0xc000083068 pc=0x5cda12
go/internal/gccgoimporter.(*parser).parseDirective(0xc000095860)
	/opt/go1.21.11/src/go/internal/gccgoimporter/parser.go:1229 +0x219 fp=0xc000083200 sp=0xc000083190 pc=0x5cea59
go/internal/gccgoimporter.(*parser).parsePackage(0xc000095860)
	/opt/go1.21.11/src/go/internal/gccgoimporter/parser.go:1267 +0x1e fp=0xc000083270 sp=0xc000083200 pc=0x5cee1e
go/internal/gccgoimporter.(*GccgoInstallation).GetImporter.GetImporter.func1(0xc0000cd4a8?, {0x63408a, 0xb}, {0x0?, 0x0?}, 0x0?)
	/opt/go1.21.11/src/go/internal/gccgoimporter/importer.go:216 +0x612 fp=0xc000083428 sp=0xc000083270 pc=0x5c6332
go/internal/gccgoimporter.TestInstallationImporter(0xc000007a00)
	/opt/go1.21.11/src/go/internal/gccgoimporter/gccgoinstallation_test.go:168 +0x189 fp=0xc000083f70 sp=0xc000083428 pc=0x5cf149
testing.tRunner(0xc000007a00, 0x6461f8)
	/opt/go1.21.11/src/testing/testing.go:1595 +0xff fp=0xc000083fc0 sp=0xc000083f70 pc=0x4d16ff
testing.(*T).Run.func1()
	/opt/go1.21.11/src/testing/testing.go:1648 +0x25 fp=0xc000083fe0 sp=0xc000083fc0 pc=0x4d2685
runtime.goexit()
	/opt/go1.21.11/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000083fe8 sp=0xc000083fe0 pc=0x46a9a1
created by testing.(*T).Run in goroutine 1
	/opt/go1.21.11/src/testing/testing.go:1648 +0x3ad

goroutine 1 [chan receive]:
runtime.gopark(0xc00008c9e8?, 0x40d1e5?, 0x8?, 0x1?, 0x18?)
	/opt/go1.21.11/src/runtime/proc.go:398 +0xce fp=0xc00008c980 sp=0xc00008c960 pc=0x439c0e
runtime.chanrecv(0xc0000181c0, 0xc00008ca67, 0x1)
	/opt/go1.21.11/src/runtime/chan.go:583 +0x3cd fp=0xc00008c9f8 sp=0xc00008c980 pc=0x4068ad
runtime.chanrecv1(0x7bd5c0?, 0x5ea680?)
	/opt/go1.21.11/src/runtime/chan.go:442 +0x12 fp=0xc00008ca20 sp=0xc00008c9f8 pc=0x4064d2
testing.(*T).Run(0xc000007860, {0x638d2c?, 0x4d143c?}, 0x6461f8)
	/opt/go1.21.11/src/testing/testing.go:1649 +0x3c8 fp=0xc00008cae0 sp=0xc00008ca20 pc=0x4d2528
testing.runTests.func1(0x7be1e0?)
	/opt/go1.21.11/src/testing/testing.go:2054 +0x3e fp=0xc00008cb30 sp=0xc00008cae0 pc=0x4d463e
testing.tRunner(0xc000007860, 0xc00008cc48)
	/opt/go1.21.11/src/testing/testing.go:1595 +0xff fp=0xc00008cb80 sp=0xc00008cb30 pc=0x4d16ff
testing.runTests(0xc00007e0a0?, {0x7b6720, 0x4, 0x4}, {0x412e7f?, 0xc00008cd08?, 0x7bd900?})
	/opt/go1.21.11/src/testing/testing.go:2052 +0x445 fp=0xc00008cc78 sp=0xc00008cb80 pc=0x4d4525
testing.(*M).Run(0xc00007e0a0)
	/opt/go1.21.11/src/testing/testing.go:1925 +0x636 fp=0xc00008cec0 sp=0xc00008cc78 pc=0x4d2f16
main.main()
	_testmain.go:53 +0x19c fp=0xc00008cf40 sp=0xc00008cec0 pc=0x5d357c
runtime.main()
	/opt/go1.21.11/src/runtime/proc.go:267 +0x2bb fp=0xc00008cfe0 sp=0xc00008cf40 pc=0x43979b
runtime.goexit()
	/opt/go1.21.11/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00008cfe8 sp=0xc00008cfe0 pc=0x46a9a1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/go1.21.11/src/runtime/proc.go:398 +0xce fp=0xc000052fa8 sp=0xc000052f88 pc=0x439c0e
runtime.goparkunlock(...)
	/opt/go1.21.11/src/runtime/proc.go:404
runtime.forcegchelper()
	/opt/go1.21.11/src/runtime/proc.go:322 +0xb3 fp=0xc000052fe0 sp=0xc000052fa8 pc=0x439a73
runtime.goexit()
	/opt/go1.21.11/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000052fe8 sp=0xc000052fe0 pc=0x46a9a1
created by runtime.init.6 in goroutine 1
	/opt/go1.21.11/src/runtime/proc.go:310 +0x1a

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/go1.21.11/src/runtime/proc.go:398 +0xce fp=0xc000053778 sp=0xc000053758 pc=0x439c0e
runtime.goparkunlock(...)
	/opt/go1.21.11/src/runtime/proc.go:404
runtime.bgsweep(0x0?)
	/opt/go1.21.11/src/runtime/mgcsweep.go:280 +0x94 fp=0xc0000537c8 sp=0xc000053778 pc=0x424614
runtime.gcenable.func1()
	/opt/go1.21.11/src/runtime/mgc.go:200 +0x25 fp=0xc0000537e0 sp=0xc0000537c8 pc=0x4197c5
runtime.goexit()
	/opt/go1.21.11/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000537e8 sp=0xc0000537e0 pc=0x46a9a1
created by runtime.gcenable in goroutine 1
	/opt/go1.21.11/src/runtime/mgc.go:200 +0x66

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc0000180e0?, 0x682ca0?, 0x1?, 0x0?, 0xc000006d00?)
	/opt/go1.21.11/src/runtime/proc.go:398 +0xce fp=0xc000053f70 sp=0xc000053f50 pc=0x439c0e
runtime.goparkunlock(...)
	/opt/go1.21.11/src/runtime/proc.go:404
runtime.(*scavengerState).park(0x7bd980)
	/opt/go1.21.11/src/runtime/mgcscavenge.go:425 +0x49 fp=0xc000053fa0 sp=0xc000053f70 pc=0x421ee9
runtime.bgscavenge(0x0?)
	/opt/go1.21.11/src/runtime/mgcscavenge.go:653 +0x3c fp=0xc000053fc8 sp=0xc000053fa0 pc=0x42247c
runtime.gcenable.func2()
	/opt/go1.21.11/src/runtime/mgc.go:201 +0x25 fp=0xc000053fe0 sp=0xc000053fc8 pc=0x419765
runtime.goexit()
	/opt/go1.21.11/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000053fe8 sp=0xc000053fe0 pc=0x46a9a1
created by runtime.gcenable in goroutine 1
	/opt/go1.21.11/src/runtime/mgc.go:201 +0xa5

goroutine 5 [finalizer wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/go1.21.11/src/runtime/proc.go:398 +0xce fp=0xc000052620 sp=0xc000052600 pc=0x439c0e
runtime.runfinq()
	/opt/go1.21.11/src/runtime/mfinal.go:193 +0x107 fp=0xc0000527e0 sp=0xc000052620 pc=0x4187e7
runtime.goexit()
	/opt/go1.21.11/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000527e8 sp=0xc0000527e0 pc=0x46a9a1
created by runtime.createfing in goroutine 1
	/opt/go1.21.11/src/runtime/mfinal.go:163 +0x3d
FAIL	go/internal/gccgoimporter	0.020s

There's no issue with gcc 13.3

**Comment by ianlancetaylor** [comment]
@gopherbot Please open backport issues.

This is due to some changes in gccgo that appeared in GCC 14.  To fix this we will need to backport https://go.dev/cl/537195.  That change is small and safe.  This is already fixed at HEAD.
