### ISSUE TITLE
proxy.golang.org: please delete stale sub modules for github.com/neurlang/wayland/go-wayland-browser/browser@v0.1.19

### ISSUE THREAD

**Issue by neurlang** [golang/go#67852]
i was doing something and now it's stuck at v0.1.19 any way to upgrade it to v0.1.32

I wish to delete these sub-go-mods and use only the main module github.com/neurlang/wayland@v0.1.32

**Comment by neurlang** [comment]
Related to I think it is potentially related to https://github.com/golang/go/issues/39007

**Comment by seankhliao** [comment]
we can't delete versions, and it doesn't look like an error with the proxy.
