### ISSUE TITLE
net/http: Transport needs a limit on total connections (per host)

### ISSUE THREAD

**Issue by calmh** [golang/go#6785]
<pre>(go1.2rc4)

We're working on a reverse HTTP proxy that does some &quot;stuff&quot; (that's not
relevant) and proxies towards one or more backend HTTP servers. During testing I ran
into connection failures apparently due to running out of file descriptors. In narrowing
this down I reduced the problem to;

The &quot;null&quot; reverse proxy (doing nothing but proxying, using the
httputil.ReverseProxy):

<a href="http://play.golang.org/p/p1g4bpTZ_g">http://play.golang.org/p/p1g4bpTZ_g</a>

A trivial HTTP server acting as the backend behind the above proxy; it simply counts the
number of connections and responds successfully:

<a href="http://play.golang.org/p/F7W-vbXEUt">http://play.golang.org/p/F7W-vbXEUt</a>

Running both of these, I have the proxy on :8080 forwarding to the server at :8090. To
test it, I use wrk (<a href="https://github.com/wg/wrk)">https://github.com/wg/wrk)</a>;

jb@jborg-mbp:~ $ wrk -c 1 -t 1 <a href="http://localhost:8080/">http://localhost:8080/</a>
...

Granted, this isn't a super realistic reproduction of the real world since the latency
on localhost is minimal. I can't prove the same thing _can't_ happen in production
though.

Using one connection (-c 1) up to about three, this works perfectly. The server side
sees a bunch of requests over one to three connections, i.e. the number of backend
connections from the proxy matches the number of incoming connections. At around -c 4
and upwards, it blows up. The proxy doesn't manage to recycle connections quickly enough
and starts doing regular Dial:s at a rate of thousands per second, resulting in

...
2013/11/18 20:18:21 http: proxy error: dial tcp 127.0.0.1:8090: can't assign requested
address
2013/11/18 20:18:21 http: proxy error: dial tcp 127.0.0.1:8090: can't assign requested
address
2013/11/18 20:18:21 http: proxy error: dial tcp 127.0.0.1:8090: can't assign requested
address
2013/11/18 20:18:21 http: proxy error: dial tcp 127.0.0.1:8090: can't assign requested
address
...

from the proxy code and of course HTTP errors as seen by wrk. 

My theory, after going through the http.Transport, is that when the number of requests/s
to the proxy goes up, the small amount of bookkeeping that is required to recycle a
connection (putIdleConn etc) starts taking just long enough that the next request in the
pipeline gets in before a connection is idle. The Transport starts Dial:ing, adding more
connections to take care of, and it explodes chaotically. I would prefer if it blocked
and awaited an idle connection instead of Dial:ing at some point.

Line 92, &quot;// TODO: tunable on global max cached connections&quot; seems relevant,
although in my case the tunable should probably be max connections per host instead of
globally.

I'll probably take a stab at implementing something like that to fix this (i.e.
rewriting Transport to limit connections), since I couldn't figure out a way around it
by just using the available API:s. Unless I seem to have misunderstood something
obvious...

//jb</pre>

**Comment by tj** [comment]
Hit this issue in prod, blocking would definitely be preferable to exhausting sockets

**Comment by cmdrkeene** [comment]
Hitting this issue as well in production. Was there a better solution here than crank up your MaxIdleConns to fit your workload?

**Comment by buth** [comment]
The `persistConn` objects used by the `Transport` object define a `closech` to listen for the closing of the underlying connections.

https://github.com/golang/go/blob/master/src/net/http/transport.go#L821

If this is reliable, it seems like you could use it as the basis for a release on a (per-host) semaphore that `dialConn` would need to aquire in order to create a new connection. As a start on a proposal for limiting total per-host connections, does this sound way off?

**Comment by bradfitz** [comment]
Related CL: https://go-review.googlesource.com/#/c/20485/

**Comment by dkbalachandar** [comment]
I am currently facing an issue similar one in this link https://groups.google.com/forum/#!topic/golang-nuts/LP6n02TFFh8. Using 1.4.3 version. I have increased the max connections per host to some higher value (@marbemac) and  it seems be working fine until now in Non Prod Env. But is this a proper fix? Will using go lang version 1.7 version resolve my issue without increasing the max connctions per host settings

**Comment by dkbalachandar** [comment]
I am using GoLang version 1.4.3 and got this issue. Will this be fixed if i upgrade the version to 1.6

**Comment by bradfitz** [comment]
@dkbalachandar, no.

**Comment by dkbalachandar** [comment]
Thanks @bradfitz. So do we have any workaround for this issue?. I have set the MaxIdleConnsPerHost  as 200 and tested it out. But the error got occurred again.

**Comment by bradfitz** [comment]
Call https://golang.org/pkg/net/http/#Transport.CloseIdleConnections occasionally, or set `Transport. DisableKeepAlives`. The `Transport.MaxIdleConnsPerHost` is not the setting you're looking for. The setting you're looking for doesn't exist (hence this bug).

**Comment by dkbalachandar** [comment]
Thanks @bradfitz, I will look for closing the Idle connections or set DisableKeepAlives. 
Do you mean that MaxIdleConnsPerHost  is not exist? But i still find this setting in transport.go. I have set the http.DefaultTransport.(*http.Transport).MaxIdleConnsPerHost with 200.  I am thinking to increase it to a higher value, if nothing works. Let me know your thoughts

**Comment by bradfitz** [comment]
MaxIdleConnsPerHost exists. It just does something different than what you think it does. It's idle conns **per host**, not total.

**Comment by dkbalachandar** [comment]
Ok @bradfitz. Its a single host reverse proxy. So setting the MaxIdleConnsPerHost  is enough. Please let me know if my assumption is wrong.

**Comment by bradfitz** [comment]
@dkbalachandar, I don't have enough information to understand your problem. It's possible you care about #13957 instead.

**Comment by dkbalachandar** [comment]
@bradfitz, Its a Jersey REST application which is being guarded by a GO application. GO app validates the browser cookie and creates a Proxy and serve the request if its a valid one. The error is happening during the load testing.  Initially we got the error similar like the one described in the issue description(http: proxy error: dial tcp HOSTNAME:PORT can't assign requested address)

Even after upgrading it to 1.6, the same issue is happening but GO App log shows the below error
"http: proxy error: net/http: request canceled"

I've enabled the DisableKeepAlives and performed the load testing and the same issue is happening, Now Go app shows the below errors.

 http: proxy error: dial tcp HOSTNAME:PORT: i/o timeout
 http: proxy error: net/http: request canceled

So we have to either call https://golang.org/pkg/net/http/#Transport.CloseIdleConnections or increase MaxIdleConnsPerHost to some higher value to fix this issue.

Let me know if you have any suggestions.

**Comment by jbardin** [comment]
@dkbalachandar 

(You should probably continue this conversation on the ML if you need more assistance)

Under the artificial environment of a load test, you can have problems recycling connection fast enough. There are a few related issues open, but if you sustain concurrency greater than MaxIdleConnsPerHost you are probably creating new connections too quickly.

**Comment by dkbalachandar** [comment]
@jbardin. Sure. Thanks

**Comment by pyanfield** [comment]
I got the similar error "dial tcp 127.0.0.1:3308: connect: cannot assign requested address" when I use stmt.Exec() method to insert datas to mysql db. And google it to here, after reading the comments, I fixed it by setting `db.SetMaxIdleConns(5)`.

**Comment by dkbalachandar** [comment]
Thanks all for your valuable suggestions. I tried all the solutions but nothing worked out. Then I reviewed the dependent system changes and got to know that their recent changes caused all these issues. So its nothing to do with the Go application.

Apologies for the confusion.

**Comment by bradfitz** [comment]
Sorry, didn't happen for Go 1.8.

**Comment by alexellis** [comment]
I think I'm running into the same issue with a proxy `lsof` is showing hundreds of "ESTABLISHED" connections even when a response has been sent back to the client:

https://github.com/alexellis/faas/blob/master/watchdog/main.go

Can anyone confirm?

**Comment by tleyden** [comment]
@alexellis don't you just need to add an `r.Body.Close()` to close the `io.ReadCloser`?  Sent you a PR: https://github.com/alexellis/faas/pull/13

**Comment by rogchap** [comment]
@tleyden From the Go http docs:

https://golang.org/pkg/net/http/#Request

```go
// The Server will close the request body. The ServeHTTP
// Handler does not need to.
Body io.ReadCloser
```

**Comment by alexellis** [comment]
@tleyden @rogchap I added a Close call to both ends (client and server were both Golang) which fixed the issue.

**Comment by rogchap** [comment]
@alexellis Yup, you have to call Close on the client. Glad you got it working.

**Comment by ldemailly** [comment]
Should I file a separate issue or is this the place to mention: I have code that does:
```
	ht := http.DefaultTransport.(*http.Transport)
	ht.MaxIdleConns = numConnections
	ht.MaxIdleConnsPerHost = numConnections
```
and then establishes `numConnections` simultaneous (go routines) back to back http connections (load testing tool)

if I check the number of sockets, it works as expected where I have numConnections established sockets for numConnections input with smaller numbers (1 and 9 or 10) but for 11 and up I have more sockets than the limit:
```
# with up to 10 it works
$ fortio -qps 0 -c 10 http://localhost:8080
$ netstat -na |awk ' $4 == "::1.8080" { print $0}'|wc -l
10
# with 16 there are more sockets:
$ echo `netstat -na |awk ' $4 == "::1.8080" { print $5}'| sort`
::1.56603 ::1.56604 ::1.56605 ::1.56606 ::1.56607 ::1.56608 ::1.56609 ::1.56610 ::1.56611 ::1.56612 ::1.56613 ::1.56615 ::1.56616 ::1.56617 ::1.56618 ::1.56619 ::1.56621 ::1.56622 ::1.56623 ::1.56624
$ netstat -na |awk ' $4 == "::1.8080" { print $0}'|wc -l
      20
```
this happens both on `go version go1.8.3 darwin/amd64` and `go version go1.8.1 linux/amd64`
the full code to repro is `go get istio.io/istio/devel/fortio/cmd/fortio` (branch ldemailly-bench6 )

beside doing my own connection pooling is there a way to guarantee a maximum/exact number of socket used ? (and why do I get a few more than I ask for)

**Comment by rsc** [comment]
Given that this has been like this since Go 1.2 and still not fixed it seems likely we should just close it. But moving to Go 1.11 at least.

**Comment by bradfitz** [comment]
I don't want to close this. There are a number of related bugs I'd like to all address.

**Comment by luciferous** [comment]
Looks like [Transport.MaxConnsPerHost](https://golang.org/pkg/net/http/#Transport.MaxConnsPerHost) (new in Go1.11) addresses this.

**Comment by rsc** [comment]
Agree that Transport.MaxConnsPerHost fixes this.
