### ISSUE TITLE
access: TryBots to trigger to run tests

### ISSUE THREAD

**Issue by xin-tsla** [golang/go#67851]
Use TryBots to trigger to run tests for the PR: https://github.com/golang/go/pull/66918

**Comment by mknyszek** [comment]
It looks like #66918 is your first contribution to the Go project. Welcome! :)

However, we only grant access if you’ve already been an active member of the community for some time. From the top of  https://go.dev/wiki/GerritAccess#requesting-access: "New contributors should participate in the Gerrit code review process for some time before requesting access."

Closing this issue for now as denying your request. Please feel free to try again in a few months.

(If I'm wrong and you *do* have a history of contributions under some other email address (I searched for xzhang39 -at- tesla.com based on the email you're using in Gerrit), please comment.)

Thanks for understanding.

**Comment by xin-tsla** [comment]
@mknyszek , understood. Thanks for the details!
