### ISSUE TITLE
x/benchmarks/sweet: disable gvisor for arm64 by default

### ISSUE THREAD

**Issue by haoliu-ampere** [golang/go#67869]
### Go version

go version go1.22.3 linux/arm64

### Output of `go env` in your module/workspace:

```shell
GOARCH='arm64'
```

### What did you do?

Currently, `x/benchmarks/sweet` fails to run `gvisor` (which is enabled by default) on linux/arm64: `./sweet run ...`

### What did you see happen?

 `gvisor` only runs on linux/amd64. (see more: https://github.com/golang/benchmarks/commit/34853f5dd1c4ed75883917af5af70be08c051e22).

### What did you expect to see?

I think it's reasonable to only enable `gvisor` for `amd64`. E.g., a simple patch would be:

```diff
 sweet/cmd/sweet/benchmark.go | 5 ++++-
 1 file changed, 4 insertions(+), 1 deletion(-)

diff --git a/sweet/cmd/sweet/benchmark.go b/sweet/cmd/sweet/benchmark.go
index 482d6a7..aaa3457 100644
--- a/sweet/cmd/sweet/benchmark.go
+++ b/sweet/cmd/sweet/benchmark.go
@@ -95,10 +95,13 @@ var benchmarkGroups = func() map[string][]*benchmark {
 		allBenchmarksMap["etcd"],
 		allBenchmarksMap["go-build"],
 		allBenchmarksMap["gopher-lua"],
-		allBenchmarksMap["gvisor"],
 		allBenchmarksMap["markdown"],
 		allBenchmarksMap["tile38"],
 	}
+	if runtime.GOARCH == "amd64" {
+		m["default"] = append(m["default"][:7], m["default"][6:]...)
+		m["default"][6] = allBenchmarksMap["gvisor"]
+	}
 
 	for i := range allBenchmarks {
 		m["all"] = append(m["all"], &allBenchmarks[i])
```

cc @mknyszek

**Comment by mknyszek** [comment]
Seems fine to me, thanks for trying out the benchmarks on arm64. If you're able, please feel free to send a CL (or a PR) to me. See https://go.dev/doc/contribute. Otherwise I'll try to get to it in the near future, but a contribution would be helpful in moving this along faster, if you need it sooner. Thanks.

**Comment by haoliu-ampere** [comment]
Thanks. I'd like to contribute. Let me follow that guide ...

**Comment by mauri870** [comment]
@haoliu-ampere Are you planning on sending a CL?

**Comment by haoliu-ampere** [comment]
> @haoliu-ampere Are you planning on sending a CL?

Yes. I'm still waiting for the CLA (maybe some legal concerns).

**Comment by haoliu-ampere** [comment]
@mknyszek 

For https://go.dev/cl/601075, it should have been reviewed and voted. But it seems I cannot trigger the Trybots and Submit, could you please help to trigger the test suite and submit the change?

> ### Trybots[¶](https://go.dev/doc/contribute#trybots)
> After an initial reading of your change, maintainers will trigger trybots, a cluster of servers that will run the full test suite on several different architectures. Most trybots complete in a few minutes, at which point a link will be posted in Gerrit where you can see the results.

> ### Submitting an approved change[¶](https://go.dev/doc/contribute#submit)
> When a change is ready, a maintainer will submit the change, which adds it as a commit to the Gerrit repository.

**Comment by mknyszek** [comment]
Sorry for the delay, I've set CQ+1 and Auto-Submit.
