### ISSUE TITLE
x/pkgsite: github.com/openstack-k8s-operators/lib-common Doesn't have README displayed due to license

### ISSUE THREAD

**Issue by jpodivin** [golang/go#67877]
### What is the URL of the page with the issue?
[ github.com/openstack-k8s-operators/lib-common](https://pkg.go.dev/github.com/openstack-k8s-operators/lib-common)
 
 
### What is your user agent?
 
[Mozilla/5.0 (X11; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0](https://explore.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)
 
 
 
### Screenshot
 
![image](https://github.com/golang/go/assets/66251151/790c485e-f54e-4ed0-a1c7-dc77435b3531)

 
 
 
### What did you do?

I opened the web page. 
 
### What did you expect to see?

Documentation of the lib-common package
 
 
### What did you see instead?

Disclaimer that it can not be shown due to license issues.

**Comment by seankhliao** [comment]
I believe this is working as intended. The root level of the repo no longer contains a go module, so the page won't be updated with newer licence information. In the current repo, the modules are under `modules/` and the documentation for those are displayed.
