### ISSUE TITLE
x/pkgsite: package removal request for github.com/jwcorle/sqs-extended-client-go

### ISSUE THREAD

**Issue by co-go** [golang/go#67873]
Due to a rename, the path of this package was adjusted when publishing [`v1.3.5`](https://github.com/co-go/sqs-extended-client-go/releases/tag/v1.3.5). This package is still public, just under my new username (`co-go`).

I assumed that `pkg.go.dev` would redirect/rename the package, but it seems that both [`github.com/jwcorle/sqs-extended-client-go`](https://pkg.go.dev/github.com/jwcorle/sqs-extended-client-go) and [`github.com/co-go/sqs-extended-client-go`](https://pkg.go.dev/github.com/co-go/sqs-extended-client-go) are listed as separate packages on pkgsite.

**Comment by suzmue** [comment]
Removed!

**Comment by co-go** [comment]
Thanks @suzmue, any guidance on how I could get previous versions to show under the renamed pkg?

It seems that when trying to reference them directly (https://pkg.go.dev/github.com/co-go/sqs-extended-client-go@v1.0.0), I'm redirected to the old name, which now returns the 404.

**Comment by suzmue** [comment]
The short answer is that its not possible, these are treated as two different modules with two different module paths. Pkgsite organizes the versions by module and we are unlikely to make any changes to that.

Removing the package documentation from pkg.go.dev doesn't however prevent the module from being used, so you should still be able to download/install/depend on the old module versions with the path github.com/jwcorle/sqs-extended-client-go.

**Comment by co-go** [comment]
Understood. Thanks again!
