### ISSUE TITLE
runtime/race: Race detector test fails on grsec kernels

### ISSUE THREAD

**Issue by gopherbot** [golang/go#6787]
by **wizeman@wizy.org**:

<pre>What steps will reproduce the problem?
1. Install Linux kernel patched with security enhancements from grsecurity.net
2. Run the race detector tests

What is the expected output?

Success

What do you see instead?

# Testing race detector.
==9105== ERROR: Failed to allocate 0x400000 (4194304) bytes at address 0x130800000000
(12)
==9105== ERROR: Failed to allocate 0x80000 (524288) bytes at address 0x600000000000 (12)
FATAL: ThreadSanitizer can not mmap thread trace
FAIL    flag    0.010s

Which version are you using?  (run 'go version')

1.1.2

Please provide any additional information below.

It seems to be a similar issue to the one fixed here:

<a href="https://golang.org/cl/5650072/">https://golang.org/cl/5650072/</a></pre>

**Comment by dvyukov** [comment]
Is there any interest in this issues? I am inclined to close as it is not particularly actionable.

**Comment by dvyukov** [comment]
non-actionable

**Comment by dmix** [comment]
Is there a solution/work-around to this bug?

I'm running a grsec kernel and keep running into:

    ==3511==ERROR: ThreadSanitizer failed to allocate 0x80000 (524288) bytes at address 600000000000 (errno: 12)
    FATAL: ThreadSanitizer can not mmap thread trace (0x600000000000/0x000000080000->0xfffffffffffffff4)

This happens for quite a few libraries including go-sqlite3. This makes it nearly impossible to develop Go on a grsec kernel.

**Comment by thestinger** [comment]
This isn't really non-actionable. Go could ask for a RANDMMAP exception by applying the appropriate extended attribute to the executable it builds if it knows it's going to be required (i.e. sanitizers are used). It's as simple as `setfattr -n user.pax.flags -v er whatever-binary` but via the `setxattr` system call.

Ideally, the sanitizers wouldn't make these non-portable assumptions about the address space. There's absolutely no guarantee of it working on all configurations of future upstream Linux kernel versions either. I really wouldn't expect that to be considered an ABI break. Making an assumption that the address space is a precise size is as bad as a program breaking if `mmap`  was switched from the current heuristic to best-fit. It should be dynamically detected with an error only if there truly isn't enough room available. This isn't a Go-specific problem though.

**Comment by dvyukov** [comment]
@dmix does the setfattr command help?
@thestinger thanks for the suggestion

**Comment by dmix** [comment]
@dvyukov I'm not sure which binary to set flags on TBH. Since the error happens while installing go-sqlite3, not running it.

I tried running strace to see which binaries get called during install and tried running setfattr on a few of them but no luck: https://gist.github.com/dmix/5a6e3fb75372876a7c2e Including:

- /usr/bin/go
- /usr/lib/go/src/debug/*
- /usr/lib/go/pkg/tool/linux_amd64/cgo

Any idea which binaries need to be flagged?

**Comment by dvyukov** [comment]
@dmix you need to run strace with -f flag to trace subprocesses
you can try to set flags for all binaries as well, this can be simpler

Also, I don't understand how race detector is involved if you run just 'go install'.  Have you done 'go install -race std'?

**Comment by dmix** [comment]
Here is strace -f output https://gist.github.com/dmix/f47f304c40e1d331ea5d I tried set the flags on all binaries in /usr/lib/go/ subdirectories.

I havent installed race std, I'm pretty much using a clean install of go via archlinux repo: https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/go

**Comment by dvyukov** [comment]
The binary that crashes is cgo:
```
[pid 12320] execve("/usr/lib/go/pkg/tool/linux_amd64/cgo"
...
[pid 12320] write(2, "==12320==ERROR: ThreadSanitizer "..., 110) = 110
```

I don't understand why it is race-enabled.
The script that you pointed to does not build anything with race detector.
Are you sure that /usr/lib/go/pkg/tool/linux_amd64/cgo is built with that script?
What is the output of:
$ nm -A /usr/lib/go/pkg/tool/linux_amd64/cgo | grep __tsan
?

**Comment by dmix** [comment]
@dvyukov output of nm -A https://gist.github.com/dmix/10361e8a3d9acab00927

I ran `rm /usr/lib/go/pkg/tool/linux_amd64/cgo` and reinstalled the arch package, it reinstalled `cgo`. Rerunning `go install github.com/mattn/go-sqlite3` generates the same problem. So `cgo` must be race enabled somehow?

**Comment by dvyukov** [comment]
Yes, it is race-enabled. And it is wrong. There is something wrong with the way you build Go.
I don't see an mentions of race in the script, though. Are you sure than /usr/lib/go/pkg/tool/linux_amd64/cgo is regenerated and has right timestamp? Maybe it is a leftover from something old and is not regenerated by the script?..

**Comment by dmix** [comment]
I manually downloaded Go from Arch repo here: https://www.archlinux.org/packages/community/x86_64/go/ Compared my local `cgo` binaries/timestamps with the Arch one and they are the same.

I downloaded `go1.4.2.linux-amd64.tar.gz` from https://golang.org/dl/ and compared it with the Arch one... and they are different. Running the golang.org `cgo` and I can successfully build go-sqlite3 just fine.

I'll get in touch with the Arch package maintainers to see why they are packaging it with race enabled.

**Comment by minux** [comment]
I'm pretty sure they have made the same mistake that our
makerelease script made (it used to generate Go 1.4 binary
distributions with race-enabled commands.)

It's not trivial to install race packages while not installing race
enabled cmmands in Go 1.4.x.

one workaround is https://golang.org/cl/2995
