### ISSUE TITLE
sync: Package documentation does not link to The Go Memory Model

### ISSUE THREAD

**Issue by orsll** [golang/go#67891]
### Go version

go version go1.22.4 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
Unrelated to the issue
```

### What did you do?

Learn about the `sync` package from somewhere other than the [The Go Memory Model](https://go.dev/ref/mem) post and go to its documentation.

### What did you see happen?

See the Go memory model mentioned several times with no explanation of what it is or links to it.

### What did you expect to see?

A documentation page which properly referenced external sources that could aid in understanding it.

**Comment by mknyszek** [comment]
Thanks for sending a change. In the future, feel free to just send the change if you're up for it anyway. No need for a tracking issue for small things like this. (If you don't intend to send a change, then filing an issue is fine.)
