### ISSUE TITLE
cmd/compile: send statements cannot be parenthesized

### ISSUE THREAD

**Issue by griesemer** [golang/go#6791]
<pre>The following program

<a href="http://play.golang.org/p/JAKJ9WVL00">http://play.golang.org/p/JAKJ9WVL00</a>

is accepted w/o compilation error. However, a send statement is a regular statement and
cannot be parenthesized. This is probably an artifact from the time when sends were
expressions.

gccgo reports an error:

$ cat x.go
package main

func main() {
     var ch chan int
     (ch&lt;-0)
}

$ gccgo x.go
x.go:5:9: error: missing ')'
      (ch&lt;-0)
         ^
x.go:5:12: error: expected ';' or '}' or newline
      (ch&lt;-0)
            ^

And so does gotype:

$ gotype x.go
x.go:5:5: expected ')', found '&lt;-'
x.go:6:2: expected '}', found 'EOF'</pre>

**Comment by odeke-em** [comment]
@griesemer this is no longer the case in Go1.8, we now correctly report that those cases have unexpected tokens and fail to compile.

<img width="832" alt="screen shot 2017-02-22 at 5 41 36 pm" src="https://cloud.githubusercontent.com/assets/4898263/23239752/3fb012e6-f926-11e6-96d1-4ea643471188.png">

<img width="798" alt="screen shot 2017-02-22 at 5 42 32 pm" src="https://cloud.githubusercontent.com/assets/4898263/23239766/5321bc1c-f926-11e6-8cb6-f03461ab9363.png">

**Comment by griesemer** [comment]
Thanks, @odeke-em for digging this one out. Yes, fixed because the 1.8 parser doesn't parse send statements as expressions.
