### ISSUE TITLE
proposal: iter: add New

### ISSUE THREAD

**Issue by anonld** [golang/go#67930]
### Proposal Details

I propose to add the following function to ease the creation of an iterator:

	func New[T any](v T, next func() (T, bool)) iter.Seq[T] {
		return func(yield func(T) bool) bool {
			for ok := true; ok; v, ok = next(v) {
				if !yield(v) {
					return false
				}
			}
			return true
		}
	}

**Update**: Instead of `New`, another name `ToSeq` is suggested.
Note: The example below is erroneous. Iteration should not call `defer`. Moreover, instead of providing an `All` method that returns an `iter.Seq` or an `Iter` method that returns a pulling iterator, the simplest and least error-prone way is to write an `All` method with signature `func (l *List[T]) All(f func(*Element[T]) bool)`.

# Example

	type Element[TElem] struct {
		next *Element[TElem]
		val  TElem
	}
	
	func (e *Element[TElem]) Next() (*Element[TElem], bool) {
		if e.next != nil {
			return e.next, true
		}
		return nil, false
	}
	
	type List[TElem any] struct {
		root *Element[TElem]
	}
	
	func New[TElem any](val TElem) *List[TElem] {
		return &List{&Element{nil, val}}
	}
	
	func All[TElem any](l *List[TElem]) iter.Seq[*Element[TElem]] {
		next := func[TElem any]() func() (*Element[TElem], bool) {
			e := l.root
			ok := e.next != nil
			return func[TElem any]() (*Element[TElem], bool) {
				defer func() { e, ok = e.Next() }
				return e, ok
			}
		}
		return iter.New(l.root, next())
	}

# Expected changes to `stdlib`
1. `runtime`:
Add `runtime.AllCallersFrames(callers []uintptr) iter.Seq[runtime.Frame]`.

Then, one can write the following:

	func main() {
		c := func() {
			pc := make([]uintptr, 10)
			n := runtime.Callers(0, pc)
			if n == 0 {
				return
			}
			pc = pc[:n]
			frames := xiter.Filter(
				runtime.AllCallersFrames(pc),
				func (f runtime.Frame) bool {
					return strings.Contains(f.File, "runtime/")
				})
			for frame := range frames {
				fmt.Println(frame.Function)
			}
		}
		b := func() { c() }
		a := func() { b() }
		a()
	}

2. `database/sql`:
Add `database/sql.db.QueryContextAll`.

With error handling flow from #67913, one can write the following:

	func main() {
		defer handle(func(e error) { log.Fatal(e) })
		age := 27
		rows := try(db.QueryContextAll(ctx, "SELECT name FROM users WHERE age=?", age))
		defer rows.Close()

		names := make([]string, 0)
		for row := range rows {
			var name string
			try(scan(row, &name))
			names = append(names, name)
		}
		log.Printf("%s are %d years old", strings.Join(names, ", "), age)
	}

**Comment by seankhliao** [comment]
See the discussion in https://github.com/golang/go/issues/61897
We expect iterators to primarily be defined as push style iterators.
