### ISSUE TITLE
cmd/link: runtime.mach_vm_region_trampoline: unsupported dynamic relocation for symbol libc_mach_task_self_ (type=29 (R_GOTPCREL) stype=46 (SDYNIMPORT))

### ISSUE THREAD

**Issue by newro** [golang/go#67976]
### Go version

go version go1.22.4 darwin/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN='/Users/newro/go/bin'
GOCACHE='/Users/newro/Library/Caches/go-build'
GOENV='/Users/newro/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/newro/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/newro/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/Cellar/go/1.22.4/libexec'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/Cellar/go/1.22.4/libexec/pkg/tool/darwin_amd64'
GOVCS=''
GOVERSION='go1.22.4'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD=''
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1861243878=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

I'm trying to compile a plugin.
The plugin code shares the model code from the main code, so I'm using the
import "myprog/model"
to get the common code. 
If I leave this import out, the compilation works fine, but when I include it, I get the error shown in the title.
The same code compiles fine on darwin/arm64, linux/arm64, and linux/amd64.

go build -o plugin.so -buildmode=plugin plugin.go

MacBook Pro 2018 Sonoma 14.5

### What did you see happen?

runtime.mach_vm_region_trampoline: unsupported dynamic relocation for symbol libc_mach_task_self_ (type=29 (R_GOTPCREL) stype=46 (SDYNIMPORT))

### What did you expect to see?

compile ok

**Comment by cherrymui** [comment]
@gopherbot please backport this to Go 1.22. This can cause build failure for plugins on darwin/amd64 without workaround. Thanks.
