### ISSUE TITLE
x/pkgsite: package update request for [github.com/grafana/k6build]

### ISSUE THREAD

**Issue by pablochacin** [golang/go#67999]
Hi.

We had a modules named `gitbub.com/grafana/k6build` and another package named `github.com/grafana/k6build-service`

We decided to rename the repositories in git:  `k6build`  --> `k6factory` and `k6build-service` --> `k6build`.
So effectively `k6build` is now in a different repository.

The problem is that now https://pkg.go.dev/github.com/grafana/k6build points to the initial repository for `k6build` (the one before the rename) and not to the new repository. If we publish a new release in the new repository, it is not reflected.

I will appreciate your help.

**Comment by seankhliao** [comment]
Closing as it appears neither repo is available.

**Comment by pablochacin** [comment]
@seankhliao both repos are private. I can make then public if needed.

**Comment by seankhliao** [comment]
pkg.go.dev will only index public repos. if there is any documentation, it will have been from when the repo is public.

**Comment by pablochacin** [comment]
@seankhliao I made both repositories public
