### ISSUE TITLE
x/pkgsite: package removal request for `github.com/kitabisa/teler-waf`

### ISSUE THREAD

**Issue by dwisiswant0** [golang/go#68009]
Actually, I don't want to file a request to delete the package. However, I'm encountering the following issue:

```console
$ go1.19 get -v github.com/teler-sh/teler-waf@latest
go: downloading github.com/teler-sh/teler-waf v1.4.4
go: github.com/teler-sh/teler-waf@v1.2.5: parsing go.mod:
	module declares its path as: github.com/kitabisa/teler-waf
	        but was required as: github.com/teler-sh/teler-waf
```

When I run `go get` with the `latest` tag, it redirects: to the latest (`v1.4.4`) and then to the old version (& old package path) (`v1.2.5`).

Is there a way to resolve this without deleting the package?

**Comment by seankhliao** [comment]
a removal request only hides documentation, it doesn't fix any issues with mismatched paths.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
