### ISSUE TITLE
proposal: import/path: I hope there is an official golang GUI library and control library that is actively maintained and supports a similar set of standard controls as Delphi7's. It should also have the ability to support third-party custom control libraries.

### ISSUE THREAD

**Issue by xiaokentrl** [golang/go#68004]
### Proposal Details

**I hope there is an official golang GUI library and control library that is actively maintained and supports a similar set of standard controls as Delphi7's. It should also have the ability to support third-party custom control libraries.**

Developing GUI programs for Linux is wonderful.

![image](https://github.com/golang/go/assets/97455744/bc9fec2d-8897-402e-898b-713caad9ea37)

**Comment by seankhliao** [comment]
see https://go.dev/doc/faq#x_in_std
