### ISSUE TITLE
strings: Title function incorrectly handles word breaks

### ISSUE THREAD

**Issue by arbrown** [golang/go#6801]
<pre>This is a known bug, but there is no issue (that I could find) for it.

<a href="https://code.google.com/p/go/source/browse/src/pkg/strings/strings.go#485">https://code.google.com/p/go/source/browse/src/pkg/strings/strings.go#485</a>

The Title function should return a new copy of a string with each word capitalized (or,
more accurately, the first rune of each word converted to title case, which can
occasionally differ from Upper Case.)

The following sample program illustrates the incorrect current behavior:
<a href="http://play.golang.org/p/u8AJs-95-g">http://play.golang.org/p/u8AJs-95-g</a>
The Title function simply assumes any separator character (like the apostrophe, in this
case) is a word boundary.  The reality is somewhat more complicated.  For reference, see:

<a href="http://www.unicode.org/reports/tr29/">http://www.unicode.org/reports/tr29/</a>
<a href="http://unicode.org/Public/UNIDATA/auxiliary/WordBreakTest.html">http://unicode.org/Public/UNIDATA/auxiliary/WordBreakTest.html</a></pre>

**Comment by robpike** [comment]
Not going to be fixed in 1.8.

**Comment by robpike** [comment]
This is unplanned and will stay that way indefinitely. There are no plans to fix it. Please do not tag it for each Go release and do not assign it to me.
