### ISSUE TITLE
go/doc: IsPredeclared missing clear, min, max

### ISSUE THREAD

**Issue by jfrech** [golang/go#68028]
### Go version

1.22.4

### Output of `go env` in your module/workspace:

```shell
go.dev/play "Go 1.22"
```

### What did you do?

I browsed https://cs.opensource.google/go/go/+/refs/tags/go1.22.4:src/go/doc/reader.go;l=979 and got curious when not finding "max" in said set.

### What did you see happen?

As https://go.dev/play/p/r88vggchOkT demonstrates, "clear", "max" and "min" aren't regarded as [go/doc.IsPredeclared].

### What did you expect to see?

As per the specification (cf. https://go.dev/ref/spec#Predeclared_identifiers [2024-06-17]), "clear", "max" and "min" are categorized as predeclared which [go/doc.IsPredeclared] should reflect.

**Comment by mauri870** [comment]
Thanks, that seems to have been overlooked.

I wonder if this can be included in the 1.23 freeze?

cc @griesemer @golang/release
