### ISSUE TITLE
x/tools/go/types/objectpath: add support for receiver type parameters

### ISSUE THREAD

**Issue by owen-mc** [golang/go#68055]
Support for type parameters was added [here](https://groups.google.com/g/golang-checkins/c/qTXiYyRyZYk), by calling `.TypeParams().At(i)` on Named types and Signature types. Receiver type parameters are available on Signature types as `.RecvTypeParams().At(i)`. So I think it should be technically quite simple.

**Comment by adonovan** [comment]
> Do you have any idea roughly when this will be in a released version?

We tag a release of x/tools the first week of each month (it's automated), so it shouldn't be more than a couple of weeks. (If you encountered this while using gopls, this CL unfortunately just missed the window of the gopls/v0.16.0 release, so it will be rather longer in that case; but we could create a patch release if this was the cause if a significant user-visible gopls bug.)
