### ISSUE TITLE
cmd/compile: compiler panic for generic alias type

### ISSUE THREAD

**Issue by griesemer** [golang/go#68054]
From https://github.com/golang/go/issues/46477#issuecomment-2175727569:

The following code snippet causes the Go compiler to panic (https://go.dev/play/p/PBvqgMjEs4S?v=gotip)

```Go
package main

type Seq[V any] = func(yield func(V) bool)

func f[E any](seq Seq[E]) {
	return
}

func main() {
	f(Seq[int](nil))
}
```

Marking for 1.23 in case it's a trivial oversight that we can easily address. But not a release blocker.

cc: @mdempsky for visibility. This looks like a noder issue.

**Comment by Carrotman42** [comment]
Possibly related to this minimal repro I was just devising:

```
package main

type OVal[O any] struct {}

type TVal[T any] = OVal[T]

var x TVal[bool]

func main() {}
```

The panic is the same `index out of range [0] with length 0` message.

(sorry for the noise if not - I can file a new issue if desired)
