### ISSUE TITLE
iter: example Pairs in package doc uses wrong (outdated?) signature for iter.Seq2

### ISSUE THREAD

**Issue by powerman** [golang/go#68056]
### Go version

unreleased (current master)

### Output of `go env` in your module/workspace:

```shell
N/A
```

### What did you do?

Read https://cs.opensource.google/go/go/+/master:src/iter/iter.go;l=122

### What did you see happen?

```go
	func Pairs[V any](seq iter.Seq[V]) iter.Seq2[V, V] {
		return func(yield func(V, V) bool) bool {
			// a couple return true/false inside
```

### What did you expect to see?

```go
	func Pairs[V any](seq iter.Seq[V]) iter.Seq2[V, V] {
		return func(yield func(V, V) bool) {
			// no return inside
```

**Comment by jimmyfrasche** [comment]
Also https://cs.opensource.google/go/go/+/master:src/iter/iter.go;l=34 has `_, v := range seq` but `seq` is a `Seq[V]`
