### ISSUE TITLE
x/tools/gopls: gopls api-json references "internal/protocol.CodeLensSource" type

### ISSUE THREAD

**Issue by hyangah** [golang/go#68057]
v0.16.0-pre.1 and pre.2

```
$ gopls api-json

...
   {
     "Name": "codelenses",
     "Type": "map[golang.org/x/tools/gopls/internal/protocol.CodeLensSource]bool",
				 ...
```

Previously, it was `map[string]bool`, but now we need to check the internal package.
It would be nice if we can stick with the basic types like `string` here. 

Assuming that only vscode-go's tool was affected and we can work around it, I don't think it is a release blocker.

**Comment by adonovan** [comment]
The right place to fix this is in loadOptions in gopls/doc/generate/generate.go, which uses a very simple heuristic to turn the go/types representation of each settings.Option field into JSON-like type names.

**Comment by hyangah** [comment]
Thanks. 

Re: `any` as the type. (`linksInHover`).

```
{
                                "Name": "linksInHover",
                                "Type": "any",
                                "Doc": "linksInHover controls the presence of documentation links\nin hover markdown.\n\nIts legal values are:\n- `false`, for no links;\n- `true`, for links to the `linkTarget` domain; or\n- `\"gopls\"`, for links to gopls' internal documentation viewer.\n",
                                "EnumKeys": {
                                        "ValueType": "",
                                        "Keys": null
                                },
                                "EnumValues": null,
                                "Default": "true",
                                "Status": "",
                                "Hierarchy": "ui.documentation"
                        },
```

What vscode setting generator does is to map this api-json settings to the vscode configuration as explained in https://code.visualstudio.com/api/references/contribution-points#Configuration-property-schema.

For `linksInHover` acceptable values can be either boolean or `gopls` (string).
I think mapping this to enum works best for users.

```
"ui.documentation.linksInHover": {
            ...
              "enum": [
                true,
                false,
                "gopls"
              ],
                    ...
 }
```
![Screenshot 2024-06-19 at 4 28 26 PM](https://github.com/golang/go/assets/4999471/5f91d762-7b55-4f05-aebd-77cc45e1e639)
