### ISSUE TITLE
access: request for may-start-trybots

### ISSUE THREAD

**Issue by millerresearch** [golang/go#68074]
See https://go.dev/wiki/GerritAccess

I've been submitting and reviewing CLs since 2016 and I run the `plan9-arm` builders. Currently I'm working on new infrastructure to interface Plan 9 builders with LUCI. Debugging this would be easier to do if I could trigger tasks to be sent to those builders in a controlled way, instead of waiting hours or days for the next trybot to start.

I use millerresearch@gmail.com for Gerrit.

**Comment by mauri870** [comment]
cc @golang/release

**Comment by dr2chase** [comment]
Assuming I pressed the right buttons, you should have may-start-trybots.  Please reopen if it doesn't work, comment if you have questions.
