### ISSUE TITLE
Get error when I use go get command with private package 

### ISSUE THREAD

**Issue by wuye251** [golang/go#68072]
### Go version

go version go1.22.2 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/root/.cache/go-build'
GOENV='/root/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/root/go/pkg/mod'
GONOPROXY='code.xxx.com'
GONOSUMDB='code.xxx.com'
GOOS='linux'
GOPATH='/root/go'
GOPRIVATE='code.xxx.com'
GOPROXY='https://goproxy.cn,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22.2'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/root/code/param_config_service/go.mod'
GOWORK='/root/code/go.work'
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build420680952=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

I done below steps before go get private package:
Step1: set go_private_proxy use code.xxx.com.
Step2: set git insteadOf--- 
```sh
[url "git@172.18.x.x:"]
        insteadOf = https://code.xxx.com/
```
My private repo on gitea like:
<img width="1324" alt="image" src="https://github.com/golang/go/assets/24435699/0498f1e3-a129-4927-8708-5aeeba4a1d5a">

After I done these steps. I'm use `go get ` at another repo import utils repo into my project.
I use `go get -u code.xxx.com/common/ts_utils` command import utils private package into my other repo. But I get err:
<img width="711" alt="image" src="https://github.com/golang/go/assets/24435699/1c05ebd3-c0f2-4f3f-8a2a-5239ae95278f">

Also I'm try to use `go get -v code.teamsun.com/common/ts_utils.git`(extra suffix: `.git`)
![image](https://github.com/golang/go/assets/24435699/77eac610-b91e-4c7c-82f9-e0fc2520a148)

I think i need to add utils project go.mod:
<img width="592" alt="image" src="https://github.com/golang/go/assets/24435699/1763b31f-99ec-45bf-b6db-cc942d1fa603">

### What did you see happen?

I am not sure why such an error occurs  with `go get` to my private package.
<img width="704" alt="image" src="https://github.com/golang/go/assets/24435699/b2009ecd-2d23-4331-866e-6f1ec5edd592">
![image](https://github.com/golang/go/assets/24435699/77eac610-b91e-4c7c-82f9-e0fc2520a148)

### What did you expect to see?

I tried something else：
1. remove utils go.mod. `go get -u xxx/xxx/utils.git`(But I need go.mod file)
2. use replace in import repo go.mod file:
<img width="814" alt="image" src="https://github.com/golang/go/assets/24435699/115001c2-12ff-4d36-b7e9-0fb1bdd4ce49">

But I need manual to upgrade private pkg when utils code update .

These are some intermediate steps that can be ignored because I don't want the real problem to get lost.

Thank you all in advance for your help.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
