### ISSUE TITLE
encoding/binary: missing documentation for BigEndian and LittleEndian functions

### ISSUE THREAD

**Issue by nilskch** [golang/go#68083]
### Go version

go version go1.22.3 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
It is not important here and contains information about my employer that I do not want to share.
```

### What did you do?

I wanted to use the functions of the `littleEndian` and `bigEndian` types and noticed that `gopls` does not provide a function documentation.  I was unsure about the exact behavior and needed to look up the implementation. 

### What did you see happen?

`gopls` just provides the function definition with description (see [here](https://github.com/golang/go/blob/master/src/encoding/binary/binary.go)). 

### What did you expect to see?

I wanted to see a documentation of those functions. Would you accept a PR that adds the documentation?

**Comment by seankhliao** [comment]
Given the function names are quite self-explanatory, what other information would the function docs contain?

**Comment by dr2chase** [comment]
I checked that adding the documentation would work (the bug referenced by gabyhelp made me wonder) so I think a pull request would be fine.  There may be some back-and-forth on the exact wording in review, but if it tripped you up, it is probably a problem for other people, and is worth fixing.

There's [a process](https://go.dev/doc/contribute), if this is too much, say so (that's also useful feedback) and maybe someone else will write the docs and you can comment on whether that meets your needs.

**Comment by rsc** [comment]
They have documentation. https://pkg.go.dev/encoding/binary#pkg-variables
It sounds like you are saying gopls does not show the documentation?

**Comment by nilskch** [comment]
@rsc the variables `LittleEndian`, `BigEndian` and `NativeEndian` have documentation. The interfaces `ByteOrder` and `AppendByteOrder` have documentation as well, but the functions of the structs `littleEndian` and `bigEndian` that implement those interfaces don't ([littleEndian](https://github.com/golang/go/blob/773767def0e0f29584a69bd760430167b7479d7d/src/encoding/binary/binary.go#L66-L139), [bigEndian](https://github.com/golang/go/blob/773767def0e0f29584a69bd760430167b7479d7d/src/encoding/binary/binary.go#L143-L216)). 

When you hover over `binary.LittleEndian.PutUint16` gopls only returns the function definition `func (littleEndian) PutUint16(b []byte, v uint16)` without any further documentation and therefore I needed to lookup the implementation.

**Comment by nilskch** [comment]
> There may be some back-and-forth on the exact wording in review, but if it tripped you up, it is probably a problem for other people, and is worth fixing.

@dr2chase I will look into it this weekend.

**Comment by dmitshur** [comment]
CC @golang/tools-team for awareness of how gopls comes into play here.

**Comment by adonovan** [comment]
I think gopls is working as intended. The `binary` package exposes variables of unexported types, and those methods are undocumented. The solution is to document those methods; https://go.dev/cl/638936 does this.
