### ISSUE TITLE
cmd/go: 'go env' should set GOBIN

### ISSUE THREAD

**Issue by dolmen** [golang/go#68102]
`go env GOBIN` would be helpful to tools beyond the Go toolchain to determine where `go install` will install a binary.

However, up to go 1.22.4, the `go install` directory is not explicitely exposed like `GOPATH` is. Instead `GOBIN` is exposed with an empty value.

### Go version

go version go1.22.4 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
GOBIN=''
GOPATH='/Users/gopher/go'
```

### What did you do?

```console
$ go help environment | sed -n '/GOBIN/{N;p;}'
	GOBIN
		The directory where 'go install' will install a command.
$ env | grep GOBIN
$ cat "$(go env GOENV)"
$ go env GOBIN

$ go env | grep GOBIN
GOBIN=''
```

### What did you see happen?

See above

### What did you expect to see?

```console
$ go env GOPATH
/Users/gopher/go
$ env | grep GOBIN
$ cat "$(go env GOENV)"
$ go env GOBIN
/Users/gopher/go/bin
$ go env | grep GOBIN
GOBIN='/Users/gopher/go/bin'
```

**Comment by dolmen** [comment]
Duplicate of #34522, #28337, #50714.

See @rsc comment: https://github.com/golang/go/issues/23439#issuecomment-433118300

**Comment by dolmen** [comment]
Apparently the blocking issue is #23439, so I'm closing.

**Comment by dolmen** [comment]
Reopening because #23439 seems to be settled if we look at the documentation.
```console
$ go help install | head -9
usage: go install [build flags] [packages]

Install compiles and installs the packages named by the import paths.

Executables are installed in the directory named by the GOBIN environment
variable, which defaults to $GOPATH/bin or $HOME/go/bin if the GOPATH
environment variable is not set. Executables in $GOROOT
are installed in $GOROOT/bin or $GOTOOLDIR instead of $GOBIN.
```

**Comment by seankhliao** [comment]
I don't think we need a separate issue, this can be done as #23439
