### ISSUE TITLE
gccgo: linking against rpm installed lib with separated -debuginfo results in "DWARF underflow" runtime error

### ISSUE THREAD

**Issue by ellson** [golang/go#6810]
<pre>Before filing a bug, please check whether it has been fixed since the
latest release. Search the issue tracker and check that you're running the
latest version of Go:

Run &quot;go version&quot; and compare against
<a href="http://golang.org/doc/devel/release.html">http://golang.org/doc/devel/release.html</a>  If a newer version of Go exists,
install it and retry what you did to reproduce the problem.

Thanks.

What steps will reproduce the problem?
If possible, include a link to a program on play.golang.org.
1.  go build -x -work -gccgoflags '-lgvc' -compiler gccgo test.go
2.  ./test
3.

What is the expected output?
nothing for this stub - an error free exit

What do you see instead?
fatal error: DWARF underflow in .debug_info at 4

Which compiler are you using (5g, 6g, 8g, gccgo)?
gccgo

Which operating system are you using?
Linux: kernel-3.11.8-300.fc20.x86_64

Which version are you using?  (run 'go version')
go version devel +1140207a3395 Wed Nov 20 13:47:37 2013 -0800 linux/amd64

Please provide any additional information below.
<a href="https://groups.google.com/forum/#">https://groups.google.com/forum/#</a>!topic/golang-nuts/QPHRwEa8gkk

  &quot;OK, that is the problem.  The backtrace library that gccgo uses does
not yet understand separate debug info packages.  I didn't realize
that it would actually crash when it sees them; that seems rather
unfortunate.&quot;</pre>

**Comment by ianlancetaylor** [comment]
This has been fixed now by changes to libbacktrace.
