### ISSUE TITLE
x/pkgsite: links in summaries have opacity zero

### ISSUE THREAD

**Issue by favonia** [golang/go#68132]
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/favonia/cloudflare-ddns#readme-migration-guides

### What is your user agent?

Mozilla/5.0 (X11; Linux x86_64; rv:127.0) Gecko/20100101 Firefox/127.0

### Screenshot

![image](https://github.com/golang/go/assets/1471328/d39a78d8-d2a3-4f1c-b835-f8d326638015)

### What did you do?

Navigate down to the section.

### What did you see happen?

Links in `<summary>` are not visible (`opacity: 0` in terms of CSS).

### What did you expect to see?

Links should be visible even within `<summary>`.
![image](https://github.com/golang/go/assets/1471328/e0d6b7bb-9fcb-4e69-aa73-31fbde6a8cf1)

**Comment by jimmyfrasche** [comment]
Bug aside, I would not recommend, in general, putting clickable things in clickable things as it causes accessibility issues. I would recommend removing the links from the summary button, even if this gets fixed.

**Comment by favonia** [comment]
@jimmyfrasche You are right. Working on it.

**Comment by ansaba** [comment]
cc: @jba

**Comment by findleyr** [comment]
Did some digging:

The opacity:0 was added in https://go.dev/cl/304649, presumably to make the anchor links hidden.
I do not now why the summary selector was included in that change.

Then the opacity:0 style for anchor links was rendered obsolete by https://go.dev/cl/520255.

So the fix LGTM.
