### ISSUE TITLE
x/pkgsite: package removal request for github.com/estevesnp/recreate-cli-go and github.com/estevesnp/manage-kpi/cmd/api

### ISSUE THREAD

**Issue by estevesnp** [golang/go#68145]
Hello, I have two pkgs under my username that are available on the pkg.go.dev that I no longer have access to that I would like to retract. Those pkgs are github.com/estevesnp/recreate-cli-go and github.com/estevesnp/manage-kpi/cmd/api . Thank you.

**Comment by findleyr** [comment]
Removed. Please allow a few hours to propagate.
