### ISSUE TITLE
Wish to change pointer detection

### ISSUE THREAD

**Issue by ruyi789** [golang/go#68170]
### Proposal Details

run the code locally：invalid pointer found on stack

https://go.dev/play/p/fpp-0tDjr2W

**Comment by mvdan** [comment]
What are you actually proposing here? You need to provide details: https://github.com/golang/proposal?tab=readme-ov-file#detail

**Comment by ianlancetaylor** [comment]
This kind of code:

```Go
    v = unsafe.Add(nil, c_lock_timeout|c_lock_read)
```

is implicitly converting an integer to an `unsafe.Pointer`, which is not permitted by the `unsafe.Pointer` rules (https://pkg.go.dev/unsafe#Pointer).

We are not going to change that.  That would fundamentally break garbage collection, as we would no longer know what is a valid pointer.  Closing this issue as infeasible.

**Comment by ruyi789** [comment]
> This kind of code:
> 
> ```go
>     v = unsafe.Add(nil, c_lock_timeout|c_lock_read)
> ```
> 
> is implicitly converting an integer to an `unsafe.Pointer`, which is not permitted by the `unsafe.Pointer` rules (https://pkg.go.dev/unsafe#Pointer).
> 
> We are not going to change that. That would fundamentally break garbage collection, as we would no longer know what is a valid pointer. Closing this issue as infeasible.

In two places, I'm going to change the minLegalPointer detection, which has nothing to do with rubbish collection

**Comment by ianlancetaylor** [comment]
But we would not know whether a value was a valid pointer.

What benefit would we get from this change?

**Comment by ruyi789** [comment]
> But we would not know whether a value was a valid pointer.
> 
> What benefit would we get from this change?

A field can be extended for two uses, or more
```
type test1_st struct {
	unk unsafe.Pointer
}

func test1_getUserData(st *test1_st) unsafe.Pointer {
	if v := st.unk; (uintptr)(v)&1 != 0 {
		return unsafe.Add(nil, (uintptr)(v)&^1)
	}
	return nil
}
func test1_getList(st *test1_st) unsafe.Pointer {
	if v := st.unk; (uintptr)(v)&1 == 0 {
		return v
	}
	return nil
}
```

**Comment by ianlancetaylor** [comment]
Sorry, but we are not going to permit user code to change the low bit of pointer values.  That is not the kind of language that Go is.  We already have C and C++, and they are good languages.  Go is a different language.

**Comment by ruyi789** [comment]
I'm not comparing it to other programming languages. It's not up to you to decide the low value, that's a user usage range, for example I wrote it that way. golang reporting an error is just a limitation of knowledge and taste, it's not my business if I can't change it, I just hope it doesn't report an error for no reason, not accessing it as an address why does it report an error? I just hope it doesn't report errors for no reason. If I mark this address 1 as a red marker 0 as a black marker, does that mean it doesn't work?

**Comment by ruyi789** [comment]
@ianlancetaylor If you could define the range of values for pointer types on the golang docs, outside of which I wouldn't use, could you do that?

**Comment by ianlancetaylor** [comment]
Go follows a simple rule: a value with pointer type must be a valid pointer.

**Comment by ruyi789** [comment]
> Go follows a simple rule: a value with pointer type must be a valid pointer.

What do you mean by valid, you define its scope? Is it valid for CPU access, or for golang allocation? Ok even if the allocation is valid, but I modified it and haven't done a read/write operation yet, do I report invalid only when I read/write the operation?

**Comment by ruyi789** [comment]
> Go follows a simple rule: a value with pointer type must be a valid pointer.

Is a nil pointer a valid pointer? If it is valid, why is it invalid when I read or write access it? So, you can only determine validity and invalidity when accessing it by read or write. And Go's detection is a range of 0-1024 detection, 1025 is also sure to report an error ah!

**Comment by ianlancetaylor** [comment]
A valid pointer is, approximately,
* `nil`
* points to a Go variable, including the result of `new` or `&`
* points to memory allocated by non-Go code using `mmap` or related functions

Arbitrary math on a value of pointer type is not supported.  Setting a value of pointer type to an integer is not supported, except for a very limited set of cases in which the integer is derived from an existing pointer in a single expression.

**Comment by ruyi789** [comment]
> A valid pointer is, approximately,
> 
>     * `nil`
> 
>     * points to a Go variable, including the result of `new` or `&`
> 
>     * points to memory allocated by non-Go code using `mmap` or related functions
> 
> 
> Arbitrary math on a value of pointer type is not supported. Setting a value of pointer type to an integer is not supported, except for a very limited set of cases in which the integer is derived from an existing pointer in a single expression.

Why I do this arithmetic with pointers is not nonsensical, it's not just scribbling.

1, a pointer is memory that holds an address meaning it can't be freed by the GC by mistake, I need pointers that protect memory not the other way around.

2, because of the address memory it is aligned and therefore has low value arithmetic capabilities and markers.

3, only I can guarantee that the pointer has no validity, because it's my code, it's guaranteed that it won't execute haphazardly.

4, the code I gave as an example only reports errors with build-debug, so it's the debug option that's causing the problem, and I don't know how to turn that option off yet. The code can be wiped out though, that's the ultimate solution to whether the pointer is valid or not

**Comment by ianlancetaylor** [comment]
> Why I do this arithmetic with pointers is not nonsensical, it's not just scribbling.

I understand that.  I'm telling you that for the code you want to write, Go is the wrong language.  Use C or C++.

**Comment by ruyi789** [comment]
> > Why I do this arithmetic with pointers is not nonsensical, it's not just scribbling.
> 
> I understand that. I'm telling you that for the code you want to write, Go is the wrong language. Use C or C++.

Is my question hard for you, then I'm sorry, maybe some day I'll abandon golang for something else, that's another story too.

**Comment by mvdan** [comment]
This is not productive. If you want to continue, like I said before, start a proposal following the documented process and provide enough detail. I'm locking this issue before it gets worse.
