### ISSUE TITLE
x/sys/unix: TestMremapPtr fails with "MremapPtr: cannot allocate memory" on GOOS=netbsd

### ISSUE THREAD

**Issue by dmitshur** [golang/go#68180]
This functionality and test was recently added in [CL 592415](https://go.dev/cl/592415). It fails on GOOS=netbsd specifically:

```
=== RUN   TestMremapPtr
    mremap_test.go:67: MremapPtr: cannot allocate memory
--- FAIL: TestMremapPtr (0.00s)
```

(From https://ci.chromium.org/b/8744162608784922945.)

CC @golang/netbsd, @ncruces.

**Comment by ncruces** [comment]
Oh. Sorry about that. I had asked to run CI tests because I couldn't test other OSes. I'll try to set up something NetBSD to test this.

**Comment by ncruces** [comment]
I've tried to verify this fix by setting up [NetBSD with GitHub actions](https://github.com/ncruces/go-sys/actions/runs/9671172914), but would appreciate that the CL would go through this testing somehow during review?

**Comment by dmitshur** [comment]
@ncruces See https://go.dev/wiki/SlowBots. In particular, you should be able to include a footer like this:

```
Cq-Include-Trybots: luci.golang.try:x_sys-gotip-netbsd-arm64
```

That'll cause those builders to run when a Commit-Queue+1 vote is left.

**Comment by ncruces** [comment]
Apparently there was a CI availability issue. If anyone can try again. Otherwise I'm reasonably confident due to reproducing and fixing on my end. I'll have a stab at #68181.
