### ISSUE TITLE
proposal: image/jpeg: add progressive encode support

### ISSUE THREAD

**Issue by scchenyong** [golang/go#68208]
RT

**Comment by ianlancetaylor** [comment]
CC @nigeltao

**Comment by nigeltao** [comment]
It's a nice feature but (1) I don't know anyone (whether myself or others on the Go team) who has the free time to work on this and (2) it's not necessary for the feature to live in the standard library. If you (or anyone else) wants to write a `package progjpeg` with an `Encode` function and share it on GitHub (or elsewhere) then you're already free to do so (and your API design won't be constrained by the Go 1.x compatibility promise).

As such, I don't think that Go's formal proposal mechanism is adding much here.

**Comment by ianlancetaylor** [comment]
Agreed.  The proposal process is not a  way of getting other people to do something.
