### ISSUE TITLE
x/telemetry: `gotelemetry view` graphs have data from the future

### ISSUE THREAD

**Issue by prattmic** [golang/go#68206]
On the `gotelemetry view` web server I see graphs like this:

![image](https://github.com/golang/go/assets/1293187/dc8b6d39-1723-4aba-bd89-7860e9f60c8d)

Note "Week 2024-06-30–2024-07-07". Today is 2024-06-26. Showing me what my usage will be in the future is a really cool feature, unfortunately I doubt we have that yet.

From the "Counters" section later down the page, I think this data is coming from this counter file:

```
addr2line@devel-devel-linux-amd64-2024-06-26.v1.count
Program: cmd/addr2line
Version: devel
GOOS: linux
GOARCH: amd64
GoVersion: devel
TimeBegin: 2024-06-26T00:00:00Z
TimeEnd: 2024-07-02T00:00:00Z
addr2line/invocations 8
The program cmd/addr2line is unregistered. No data from this set would be uploaded to the Go team.
```

cc @golang/telemetry

**Comment by findleyr** [comment]
Thanks for investigating. Yes, let's update the definition of Week to match the implementation.
