### ISSUE TITLE
x/pkgsite: <b> tags stripped from markdown 

### ISSUE THREAD

**Issue by lorypelli** [golang/go#68211]
Hello, I'm having an issue on the page:
https://pkg.go.dev/github.com/lorypelli/cpkgs
My user agent is:
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36`
Screenshot:
![image](https://github.com/golang/go/assets/87276663/780ea6cc-a7b7-4797-92ff-412d62bc5b18)
Issue:
The uppercase words are also bolded, but it doesn't show here because bold of the <b> tag was removed

**Comment by seankhliao** [comment]
you could consider using markdown's native `__text__` bolding

**Comment by lorypelli** [comment]
> you could consider using markdown's native `__text__` bolding

You mean `**text**`
You are right, I forgot about this

**Comment by lorypelli** [comment]
> you could consider using markdown's native `__text__` bolding

same issues happens with `em` but I used markdown `*` this time

**Comment by ansaba** [comment]
cc: @jba

**Comment by findleyr** [comment]
Closing as working as intended.
