### ISSUE TITLE
gccgo: Stacktrace and crash in binary compiled with gccgo

### ISSUE THREAD

**Issue by gopherbot** [golang/go#6822]
by **aidanphs**:

<pre>What steps will reproduce the problem?
1. Compile and run binary with &quot;go build -compiler=gccgo
-gccgoflags=&quot;-static-libgo -O3&quot; src/srv/srv.go&quot;
2. Run GOTRACEBACK=2 ./srv
3. Run wrk against that server to cause lots of load.

What is the expected output?
It doesn't crash, as it doesn't when compiled with normal go.

What do you see instead?
It occasionally crashes and terminates.

Which compiler are you using (5g, 6g, 8g, gccgo)?
gccgo 4.8.2 (self compiled)

Which operating system are you using?
Ubuntu 12.04

Which version are you using?  (run 'go version')
go version go1.2rc5 linux/amd64 

Please provide any additional information below.
Stacktrace (the &quot;starting&quot; is my output):

/opt/go $ GOTRACEBACK=2 ./srv                                                           
                              
starting
caught signal while mallocing: 11
fatal error: caught signal while mallocing
[signal 0xb code=0x1 addr=0x0]

goroutine 6 [running]:
runtime_dopanic
        /home/aidanhs/Desktop/apparicon/compiler/gcc-4.8.2/libgo/runtime/panic.c:71
runtime_throw
        /home/aidanhs/Desktop/apparicon/compiler/gcc-4.8.2/libgo/runtime/panic.c:106
sig_panic_leadin
        /home/aidanhs/Desktop/apparicon/compiler/gcc-4.8.2/libgo/runtime/go-signal.c:265
sig_panic_info_handler
        /home/aidanhs/Desktop/apparicon/compiler/gcc-4.8.2/libgo/runtime/go-signal.c:300

        :0
runtime_MCentral_AllocList
        /home/aidanhs/Desktop/apparicon/compiler/gcc-4.8.2/libgo/runtime/mcentral.c:63
runtime_MCache_Alloc
        /home/aidanhs/Desktop/apparicon/compiler/gcc-4.8.2/libgo/runtime/mcache.c:24
runtime_mallocgc
        /home/aidanhs/Desktop/apparicon/compiler/gcc-4.8.2/libgo/runtime/malloc.goc:81
crypto_tls.Handshake.pN15_crypto_tls.Conn
        /home/aidanhs/Desktop/apparicon/compiler/gcc-4.8.2/libgo/go/crypto/tls/conn.go:834
crypto_tls.Write.pN15_crypto_tls.Conn
        /home/aidanhs/Desktop/apparicon/compiler/gcc-4.8.2/libgo/go/crypto/tls/conn.go:750
github.com_lib_pq.send.pN22_github.com_lib_pq.conn
        /opt/go/src/github.com/lib/pq/conn.go:534
github.com_lib_pq.exec.pN22_github.com_lib_pq.stmt
        /opt/go/src/github.com/lib/pq/conn.go:826
github.com_lib_pq.Query.pN22_github.com_lib_pq.stmt
        /opt/go/src/github.com/lib/pq/conn.go:768
sql.rowsiFromStatement
        /home/aidanhs/Desktop/apparicon/compiler/gcc-4.8.2/libgo/go/database/sql/sql.go:1212
database_sql.Query.pN17_database_sql.Stmt
        /home/aidanhs/Desktop/apparicon/compiler/gcc-4.8.2/libgo/go/database/sql/sql.go:1173
database_sql.QueryRow.pN17_database_sql.Stmt
        /home/aidanhs/Desktop/apparicon/compiler/gcc-4.8.2/libgo/go/database/sql/sql.go:1232
main.addBlipHandler
        /opt/go/src/srv/srv.go:102
net_http.ServeHTTP.pN17_net_http.ServeMux
        /home/aidanhs/Desktop/apparicon/compiler/gcc-4.8.2/libgo/go/net/http/server.go:1416
net_http.serve.pN13_net_http.conn
        /home/aidanhs/Desktop/apparicon/compiler/gcc-4.8.2/libgo/go/net/http/server.go:1096
kickoff
        /home/aidanhs/Desktop/apparicon/compiler/gcc-4.8.2/libgo/runtime/proc.c:229

        :0
panic during panic</pre>

**Comment by ianlancetaylor** [comment]
I compiled your program with gccgo on GCC trunk.  I ran your script for a few hours, generating 9237 log files.  I did not see any problems.

I see now that you are using gccgo 4.8.2.  It's likely that the problem, whatever it was, has been fixed.

**Comment by aidanhs** [comment]
Ok, happy to close then (I don't have permission).
