### ISSUE TITLE
encoding/json: documentation show [Unmarshaler.UnmarshalJSON] not show link

### ISSUE THREAD

**Issue by qiulaidongfeng** [golang/go#68257]
### Go version

tip

### Output of `go env` in your module/workspace:

```shell
no have
```

### What did you do?

See https://pkg.go.dev/encoding/json@master#Unmarshal

### What did you see happen?

show [Unmarshaler.UnmarshalJSON] not show link

### What did you expect to see?

not show [Unmarshaler.UnmarshalJSON] show link

**Comment by callthingsoff** [comment]
[Marshaler.MarshalJSON] is not link either.

**Comment by seankhliao** [comment]
Duplicate of #63679
