### ISSUE TITLE
How to close "go version -m" ?

### ISSUE THREAD

**Issue by MmToon** [golang/go#68269]
### Proposal Details

"go version -m" 
It has exposed a lot of information, and I want to close it instead of using third-party software, as there may be a risk of being intercepted by security software.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
