### ISSUE TITLE
regexp: wrong match

### ISSUE THREAD

**Issue by ethanvc** [golang/go#68281]
### Go version

go 1.22.0

### Output of `go env` in your module/workspace:

```shell
$ go env
GO111MODULE='on'
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/Library/Caches/go-build'
GOENV='/Users/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/.gvm/pkgsets/go1.22.4/global/pkg/mod'
GOOS='darwin'
GOPATH='/Users/.gvm/pkgsets/go1.22.4/global'
GOPROXY='https://proxy.golang.org,https://goproxy.io,direct'
GOROOT='/Users/go/go1.22.0'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/Users/go/go1.22.0/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.22.0'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/qz/53hk_dj559zgbmkxl19vmwtm0000gp/T/go-build1960665975=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

```

package main

import (
	"fmt"
	"regexp"
)

func main() {
	x, err := regexp.MatchString(`7|`, "800000")
	fmt.Println(x, err)
}
```

### What did you see happen?

true <nil>

### What did you expect to see?

false, do not match.

**Comment by Shion1305** [comment]
Hello, @ethanvc!

Do you recognize that `regexp.MatchString` takes the first argument as a pattern and the second argument as a target string?
`7|` means `7` or nothing in regex, so this is correct behavior.
You can check from [h
<img width="747" alt="Screenshot 2024-07-03 at 15 59 29" src="https://github.com/golang/go/assets/20254962/ec14b543-636f-4e1f-8990-605665cec027">
ere](https://regex101.com/)

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by ethanvc** [comment]
sorry for the wrong code snip. i correct the example.
```
package main

import (
	"fmt"
	"regexp"
)

func main() {
	x, err := regexp.MatchString(`^7|$`, "800000")
	fmt.Println(x, err)
}
```

**Comment by ethanvc** [comment]
> Hello, @ethanvc!
> 
> Do you recognize that `regexp.MatchString` takes the first argument as a pattern and the second argument as a target string? `7|` means `7` or nothing in regex, so this is correct behavior. You can check from [here](https://regex101.com/) <img alt="Screenshot 2024-07-03 at 15 59 29" width="747" src="https://private-user-images.githubusercontent.com/20254962/345315071-ec14b543-636f-4e1f-8990-605665cec027.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTE2NDgsIm5iZiI6MTcxOTk5MTM0OCwicGF0aCI6Ii8yMDI1NDk2Mi8zNDUzMTUwNzEtZWMxNGI1NDMtNjM2Zi00ZTFmLTg5OTAtNjA1NjY1Y2VjMDI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDA3MjIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhMjM0ZjQ0MjIzNDdjNmEwNjJjYzdlNTJkYWIzOTA5MzYxNDQ0ZmFhNjJiNTI3MjI0NTVlYTFhYTE1MjM2NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n-joN0XS17Rqqz38d08PyT4sovu0DMyeX-5Yyy1mHgg">

thanks, understand.
