### ISSUE TITLE
cmd/compile/internal/types2: inconsistent source paths printed in error message

### ISSUE THREAD

**Issue by jfrech** [golang/go#68292]
### Go version

go version go1.22.3 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/root/.cache/go-build'
GOENV='/root/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/root/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/root/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22.3'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2953486244=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

```
$ cd /tmp
$ cat leaks.go
package main

func f[S any, T any](T) {}

func g() {
        f(0)
}

func main() {}
$ go run leaks.go
# command-line-arguments
./leaks.go:6:3: cannot infer S (/tmp/leaks.go:3:8)
```

### What did you see happen?

In its error message, the compiler leaks the absolute path of "./leaks.go".

### What did you expect to see?

I would have expected the error's source's source path to be presented relative to the current working directory (or relative to the current module's root). Such is the case on the playground: https://go.dev/play/p/890kN4mzITD

**Comment by Zxilly** [comment]
The go playground doesn't really have a file system. See https://go.p2hp.com/blog/playground

**Comment by timothy-king** [comment]
Thank you for the report.

What is happening is that `types` was formatting an error message using [[link](https://source.corp.google.com/h/go/go/+/4b2716348cfcc336469d38ce9a8e23f0b909ab05:src/cmd/compile/internal/types2/infer.go;l=434)]:
```
			err.addf(posn, "cannot infer %s (%v)", obj.name, obj.pos)
```

cmd/go rewrites the output of gc in [Shell.reportCmd](https://source.corp.google.com/h/go/go/+/4b2716348cfcc336469d38ce9a8e23f0b909ab05:src/cmd/go/internal/work/shell.go;l=420). Excerpt from internal documentation:
> // reportCmd formats the output as "# desc" followed by the given output. The
> // output is expected to contain references to 'dir', usually the source
> // directory for the package that has failed to build. reportCmd rewrites
> // mentions of dir with a relative path to dir when the relative path is
> // shorter. This is usually more pleasant.

When this happens is decided by [replacePrefix](https://source.corp.google.com/h/go/go/+/4b2716348cfcc336469d38ce9a8e23f0b909ab05:src/cmd/go/internal/work/shell.go;l=518-519). Docs:
> // replacePrefix is like strings.ReplaceAll, but only replaces instances of old
> // that are preceded by ' ', '\t', or appear at the beginning of a line. 

This manifests as rewriting the output to `/tmp/leaks.go:6:3: cannot infer S (/tmp/leaks.go:3:8)` to `./leaks.go:6:3: cannot infer S (/tmp/leaks.go:3:8)`. The first begins a line and the second is preceded by a `(` so it does not match.

I think we should be consistent with the output here and have a relative path in both locations, e.g. `./leaks.go:6:3: cannot infer S (declared on ./leaks.go:3:8)`. This is being done for convenience, and we should try to get this consistent on a best effort basis. We can fix these as they are reported for now. I don't think there is a need for a more systematic review yet.
