### ISSUE TITLE
x/mobile: Class goSeqDictionary is implemented in both

### ISSUE THREAD

**Issue by banStayUpLate** [golang/go#68304]
### Go version

go 1.22

### Output of `go env` in your module/workspace:

```shell
GO111MODULE='on'
GOARCH='arm64'
GOBIN='/Users/hu/Desktop/program_workspace/bin'
GOCACHE='/Users/hu/Library/Caches/go-build'
GOENV='/Users/hu/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/hu/Desktop/program_workspace/pkg/mod'
```

### What did you do?

Use gomobile to compile two iOS SDKs and use them in iOS projects and get an error

### What did you see happen?

Class RefTracker is implemented in both /private/var/containers/Bundle/Application/647196B8-3B75-4214-A5AF-4ACAB04ACE77/Link.app/Frameworks/LiMaoBase.framework/LiMaoBase (0x106e086b0) and /private/var/containers/Bundle/Application/647196B8-3B75-4214-A5AF-4ACAB04ACE77/Link.app/Link (0x10332c858). One of the two will be used. Which one is undefined.

### What did you expect to see?

How to solve the problem of using multiple SDKs in iOS projects and Class RefTracker is implemented in both

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
