### ISSUE TITLE
unsafe: confusing docs about unsafe.String

### ISSUE THREAD

**Issue by DemiMarie** [golang/go#68300]
### Go version

1.22.5 (this is from `pkg.go.dev`)

### Output of `go env` in your module/workspace:

```shell
N/A as I discovered this problem viewing the online docs.
```

### What did you do?

Looked at the documentation for `unsafe.String`

### What did you see happen?

The documentation for `unsafe.String` states (correctly):

> Since Go strings are immutable, the bytes passed to String must not be modified afterwards.

However, it does not state for how long this holds.  Is it sufficient for the bytes to remain valid until there are no more source-level references to the String, or is the actual requirement stricter?

To use a concrete example: Suppose I get a pointer from C’s `malloc` and use `unsafe.String` to obtain a string pointing to its contents.  Once I am done with the string I free the pointer with C’s `free`.  Is this safe?

### What did you expect to see?

An answer to this question.

**Comment by randall77** [comment]
> Is it sufficient for the bytes to remain valid until there are no more source-level references to the String

Yes, that is enough.

The tricky part documentation-wise is how to write that. "source-level references" isn't defined anywhere. "until the string goes dead"? Also not defined anywhere.
Suggestions welcome, but I don't see an easy way to specify this without going down a rathole.

**Comment by DemiMarie** [comment]
> > Is it sufficient for the bytes to remain valid until there are no more source-level references to the String
> 
> Yes, that is enough.

Good to know.  Is it sufficient for the bytes to remain valid until the string is no longer used, or could a this cause a crash?

> The tricky part documentation-wise is how to write that. "source-level references" isn't defined anywhere. "until the string goes dead"? Also not defined anywhere. Suggestions welcome, but I don't see an easy way to specify this without going down a rathole.

I think some examples would be best.
