### ISSUE TITLE
github.com/EvilBytecode/GolangStyle/pkg

### ISSUE THREAD

**Issue by MeanMachine123** [golang/go#68326]
### What is the URL of the page with the issue?

https://github.com/EvilBytecode/GolangStyle/issues/1

### What is your user agent?

Mozilla

### Screenshot

![Golang](https://github.com/golang/go/assets/23347122/7be27917-a32d-416f-8193-faf8dc7b9b88)

### What did you do?

Payload Crypter is giving issue.......How can I resolve ???

github.com/EvilBytecode/GolangStyle/pkg

../go/pkg/mod/github.com/!evil!bytecode/!golang!style@v1.0.2/pkg/gostyle.go:14:33: undefined: syscall.NewLazyDLL
../go/pkg/mod/github.com/!evil!bytecode/!golang!style@v1.0.2/pkg/gostyle.go:82:20: undefined: syscall.Handle
../go/pkg/mod/github.com/!evil!bytecode/!golang!style@v1.0.2/pkg/gostyle.go:167:22: undefined: syscall.NewLazyDLL

### What did you see happen?

go run main.go
../go/pkg/mod/github.com/!evil!bytecode/!golang!style@v1.0.2/pkg/gostyle.go:14:33: undefined: syscall.NewLazyDLL
../go/pkg/mod/github.com/!evil!bytecode/!golang!style@v1.0.2/pkg/gostyle.go:82:20: undefined: syscall.Handle
../go/pkg/mod/github.com/!evil!bytecode/!golang!style@v1.0.2/pkg/gostyle.go:167:22: undefined: syscall.NewLazyDLL

### What did you expect to see?

Run a Tool

**Comment by ianlancetaylor** [comment]
The package only works on Windows.

In general, we don't use the issue tracker for questions.  Please see https://go.dev/wiki/Questions for better places to ask.  Thanks.
