### ISSUE TITLE
gccgo: runtime.Caller inconsistency

### ISSUE THREAD

**Issue by davecheney** [golang/go#6835]
<pre>What steps will reproduce the problem?

<a href="http://play.golang.org/p/g_s9aMiETt">http://play.golang.org/p/g_s9aMiETt</a>

What is the expected output? What do you see instead?

$ go run -compiler gc main.go
main
$ go run -compiler gccgo main.go
Outer

Looks like gccgo is inserting miranda methods when an inner method is called via
embedding.

Please use labels and text to provide additional information.

% gccgo -v
Using built-in specs.
COLLECT_GCC=gccgo
COLLECT_LTO_WRAPPER=/opt/gccgo/libexec/gcc/x86_64-unknown-linux-gnu/4.9.0/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ../gcc/trunk/configure --prefix=/opt/gccgo --enable-languages=go
--disable-bootstrap : (reconfigured) ../gcc/trunk/configure --prefix=/opt/gccgo
--enable-languages=go --disable-bootstrap
Thread model: posix
gcc version 4.9.0 20131119 (experimental) (GCC)</pre>

**Comment by ianlancetaylor** [comment]
This works now with gccgo, I think because we now skip stub methods in the traceback.
