### ISSUE TITLE
sync.Map report concurrent map read and map write

### ISSUE THREAD

**Issue by IcefireCgrbza** [golang/go#68364]
### Go version

1.20.8

### Output of `go env` in your module/workspace:

```shell
so sorry i cant provide much infomation, maybe sensitive
```

### What did you do?

sorry i can't upload the complete code, my code invoke (sync.Map).Store method and report an error, read and write the sync.map is concurrent
```
 fatal error: concurrent map read and map write

goroutine 2480 [running]:
sync.(*Map).Swap(0xc015bafdd0, {0x984e080, 0xc013614a50}, {0x9ab49e0, 0xc01235ceb8})
 /usr/local/go/src/sync/map.go:353 +0x205
sync.(*Map).Store(...)
 /usr/local/go/src/sync/map.go:155
...
```

### What did you see happen?

 fatal error: concurrent map read and map write

goroutine 2480 [running]:
sync.(*Map).Swap(0xc015bafdd0, {0x984e080, 0xc013614a50}, {0x9ab49e0, 0xc01235ceb8})
 /usr/local/go/src/sync/map.go:353 +0x205
sync.(*Map).Store(...)
 /usr/local/go/src/sync/map.go:155
...

### What did you expect to see?

how to fix it

**Comment by cespare** [comment]
Hi @IcefireCgrbza!

It's possible you've found a bug in Go, but it's more likely that there's a problem with your code. It will be hard to figure it out without some more details, though. For a start, can you include:

1. More of the stack trace (in particular, both of the stack traces that indicate the map read *and* the map write)
2. A bit of code that demonstrates how you're using `sync.Map` in some way

Is it possible that you're copying the `sync.Map` you start using it? That is not okay (see the [Map documentation](https://pkg.go.dev/sync#Map)). That should be caught by `go vet`.

**Comment by IcefireCgrbza** [comment]
thanks, go vet help find the code bug, sync.Map is copy by struct method definication
