### ISSUE TITLE
go 1.22.5 cgo exception on windows 7

### ISSUE THREAD

**Issue by luowencai** [golang/go#68363]
### Go version

since go1.21.5.windows-amd64

### Output of `go env` in your module/workspace:

```shell
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Dell\AppData\Local\go-build
set GOENV=C:\Users\Dell\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Dell\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Dell\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.22.5
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\Dell\AppData\Local\Temp\go-build748694202=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

We use go 1.22.5 with cgo, gcc use tdm64-gcc-10.3.0-2。

### What did you see happen?

It work fine on windows 11/windows 10，But Exception 0xc0000005 on windows 7
![image](https://github.com/golang/go/assets/16441807/325d0b98-f31c-44e1-b223-f43c91abf1d7)
This Exception happens after 1.21.5，It works fine on 1.21.3
gcc with msys2
![image](https://github.com/golang/go/assets/16441807/6f8b04c5-5256-44a4-a7ea-53adfb7d5f68)

### What did you expect to see?

No Exception on Windows 7 with cgo

**Comment by gophun** [comment]
Windows 7 is no longer supported since Go 1.21: https://tip.golang.org/doc/go1.21#windows

> It works fine on 1.21.3

That was pure luck.

**Comment by Lestrad** [comment]
Hello. I would like to request that a warning that the current version of Device Flasher is not compatible with Windows 7 be put on the Web site and if possible that a version of the Device Flasher that is compatible with Windows 7 be made available. Many people who decided to get off the Windows merry-go-round have held on to Windows 7, if only because they need Windows for professional reasons - as is my own case.

Thanks to all

**Comment by ivanshatsky** [comment]
For those interested, the latest version that works with Windows 7 is 1.21.4.
