### ISSUE TITLE
x/pkgsite: package removal request for github.com/marsacotan/go-zabbix7

### ISSUE THREAD

**Issue by marsacotan** [golang/go#68378]
1. v1.0.0 is only a temporary creation and has not been officially released. It is not recommended to use it.
2. Currently, the latest tag is used as the development stage.
3. After most of the functions are developed, v1.0.0 will be officially released as the first stable version.

**Comment by seankhliao** [comment]
we cannot remove specific versions, nor allow you to redefine what a tag points to.
