### ISSUE TITLE
cmd/go, x/telemetry: document GODEBUG=countertrace=1

### ISSUE THREAD

**Issue by findleyr** [golang/go#68376]
Additional debug instrumentation can be enabled for packages using the x/telemetry/counter package by setting GODEBUG=countertrace=1 in the environment. We should document this more prominently, at least at https://pkg.go.dev/golang.org/x/telemetry/counter.

This may also be worth mentioning in the documentation at https://pkg.go.dev/cmd/go.

CC @golang/telemetry

**Comment by hyangah** [comment]
I noticed many GODEBUG settings used in the go command, especially if they are purely for internal debugging purpose) are not documented from the cmd/go documentation. (cmdgonetlimit, fuzzdebug, goindex, ...). If there is no established guideline on what should be documented, I think cl/597617 is good enough.

**Comment by matloob** [comment]
I agree with @hyangah. As I understand it, this isn't meant to be a user facing feature.

**Comment by findleyr** [comment]
Indeed, Russ said the same thing. Then the above CL (for the counter package) is sufficient. Thanks!
