### ISSUE TITLE
wasm: strings.Index/IndexRune can return large negative number on wasm with high mem load

### ISSUE THREAD

**Issue by Zxilly** [golang/go#68395]
### Go version

go version go1.23rc1 windows/amd64

### Output of `go env` in your module/workspace:

```shell
go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\zxilly\AppData\Local\go-build
set GOENV=C:\Users\zxilly\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\zxilly\go\pkg\mod
set GONOPROXY=1
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\zxilly\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:/Users/zxilly/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23rc1.windows-amd64
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Users\zxilly\go\pkg\mod\golang.org\toolchain@v0.0.1-go1.23rc1.windows-amd64\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.23rc1
set GODEBUG=
set GOTELEMETRY=local
set GOTELEMETRYDIR=C:\Users\zxilly\AppData\Roaming\go\telemetry
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=E:\Project\CS_Project\gsv\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\zxilly\AppData\Local\Temp\go-build2193651606=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

Compile a program to wasm and noticed unexpected value was returned by `strings.Index/IndexRune`

### What did you see happen?

`strings.Index/IndexRune` randomly returns large negative number, but not -1, even the substr was found in the given str.

### 1

![image](https://github.com/user-attachments/assets/697cd126-daab-4d3b-90cb-ac23b51f02a2)
![image](https://github.com/user-attachments/assets/0160767f-f396-409e-b215-062c05f13be6)

### 2

![image](https://github.com/user-attachments/assets/d664002f-fd12-43d0-8b07-efcefe9d1579)
![image](https://github.com/user-attachments/assets/191effb5-ff36-4202-89b1-b62da696fc0a)

You can reproduce this on https://gsa.zxilly.dev. 
Or you reproduce it locally with project https://github.com/Zxilly/go-size-analyzer. 

The binary I used as input is https://binaries.cockroachdb.com/cockroach-v24.1.0-beta.2.linux-amd64.tgz

I've tried creating smaller reproducible samples, but they all fail. The error only occurs if a lot of memory is allocated. Smaller inputs will still work fine for this program.

### What did you expect to see?

`Index/IndexRune` should only return negative number -1

**Comment by Zxilly** [comment]
I think https://github.com/golang/go/issues/65571 is the bug I met.

**Comment by ianlancetaylor** [comment]
Thanks.  Closing as a duplicate.
