### ISSUE TITLE
os/exec: Unclear documentation

### ISSUE THREAD

**Issue by bamiaux** [golang/go#6839]
<pre>os/exec documentation does not mention whether one *must* eventually call Cmd.Wait() on
a *exec.Cmd which has been started with Start().
Looking at the code, it seems to be closing descriptors, so system descriptors may not
be released correctly if we never call Cmd.Wait().</pre>

**Comment by ALTree** [comment]
This was fixed by d4b6a198b3b44c8c9617c72ceca9c32ba089b5a8.
