### ISSUE TITLE
cmd/vet: check for misused of append onto new, non-empty slice

### ISSUE THREAD

**Issue by bradfitz** [golang/go#6840]
<pre>Request from coworkers:

Govet or lint could warn about appends to slices which were made with a length (but not
a capacity) and had no intervening mutations:

   s := make([]Foo, len(m))   // accidental length; user meant capacity: make([]Foo, 0, len(m))
   for k, v := range m {
      ....
      s = append(s, foo)
   }</pre>

**Comment by seankhliao** [comment]
Duplicate of #69872
