### ISSUE TITLE
x/build: gotip-freebsd-riscv64 builder is in quarantined state

### ISSUE THREAD

**Issue by dmitshur** [golang/go#68402]
https://ci.chromium.org/ui/p/golang/builders/ci/gotip-freebsd-riscv64

In the Machine Pool section, it's visible that the [freebsd-riscv64-mengzhuo](https://chromium-swarm.appspot.com/bot?id=freebsd-riscv64-mengzhuo) builder is offline. Clicking on more details shows it's actually connected, just in quarantined state ("Had 2 consecutive BOT_DIED tasks"), which requires the swarming bot to be restarted at minimum. @mengzhuo Can you please take a look? Thanks.

CC @golang/release.

**Comment by dmitshur** [comment]
This is [fixed](https://github.com/user-attachments/assets/2e119a47-25f1-4614-b330-22122b485219) now, so closing. Thanks.

**Comment by dmitshur** [comment]
The bot is currently missing, last seen 11h 54m ago. CC @mengzhuo.

**Comment by mengzhuo** [comment]
This Sifive unmatched builder hanged without any log :(
I had rebooted it.

**Comment by dmitshur** [comment]
Thanks!
