### ISSUE TITLE
x/tools/gopls: panic during completion in go template (crash)

### ISSUE THREAD

**Issue by dnywonnt** [golang/go#68416]
gopls version: v0.16.1/go1.22.0
gopls flags: 
update flags: proxy
extension version: 0.41.4
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Sun, 14 Jul 2024 07:29:06 GMT
restart history:
Sun, 14 Jul 2024 05:00:06 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: slice bounds out of range [91:90]

goroutine 118 [running]:
golang.org/x/tools/gopls/internal/template.(*completer).complete(0xc0028b32c0)
	  completion.go:117  0xd25
golang.org/x/tools/gopls/internal/template.Completion({0xc0007e1980%3F, 0x5a%3F}, 0x8%3F, {0x131daa0, 0xc001b380c0}, {0x50d688%3F, 0xc0%3F}, {0x1, {0x0, 0x0}})
	  completion.go:56  0x308
golang.org/x/tools/gopls/internal/server.(*server).Completion(0xc00020c600, {0x131c608, 0xc000451230}, 0xc0002ee5a0)
	  completion.go:54  0x499
golang.org/x/tools/gopls/internal/protocol.serverDispatch({0x131c640, 0xc00054c550}, {0x1337cd0, 0xc00020c600}, 0xc000375cb0, {0x131c800, 0xc00036af00})
	  tsserver.go:361  0x2587
golang.org/x/tools/gopls/internal/lsprpc.(*streamServer).ServeStream.ServerHandler.func3({0x131c640, 0xc00054c550}, 0xc000375cb0, {0x131c800, 0xc00036af00})
	  protocol.go:160  0x85
golang.org/x/tools/gopls/internal/lsprpc.(*streamServer).ServeStream.handshaker.func4({0x131c640, 0xc00054c550}, 0xc000375cb0, {0x131c800, 0xc00036af00})
	  lsprpc.go:509  0x923
golang.org/x/tools/gopls/internal/protocol.Handlers.MustReplyHandler.func1({0x131c640, 0xc00054c550}, 0xc00019d020, {0x131c800, 0xc00036af00})
	  handler.go:35  0xc6
golang.org/x/tools/gopls/internal/protocol.Handlers.AsyncHandler.func2.2()
	  handler.go:103  0x96
created by golang.org/x/tools/gopls/internal/protocol.Handlers.AsyncHandler.func2 in goroutine 96
	  handler.go:100  0x1c5
</pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 134,
    "TestdataFiles": 0,
    "GoFiles": 40,
    "ModFiles": 1,
    "Dirs": 76
  },
  "GOARCH": "amd64",
  "GOOS": "linux",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.22.0",
  "GoplsVersion": "v0.16.1",
  "InitialWorkspaceLoadDuration": "813.282514ms",
  "MemStats": {
    "HeapAlloc": 34401120,
    "HeapInUse": 52289536,
    "TotalAlloc": 579967608
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 2107,
      "Largest": 935931,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.22.0",
        "AllPackages": {
          "Packages": 338,
          "LargestPackage": 161,
          "CompiledGoFiles": 2103,
          "Modules": 53
        },
        "WorkspacePackages": {
          "Packages": 14,
          "LargestPackage": 5,
          "CompiledGoFiles": 40,
          "Modules": 1
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by adonovan** [comment]
Dup of https://github.com/golang/go/issues/57621
