### ISSUE TITLE
x/net/http2: High CPU usage on light traffic

### ISSUE THREAD

**Issue by ttc0419** [golang/go#68414]
### Go version

go version go1.21.6 linux/amd64

### Output of `go env` in your module/workspace:

default

### What did you do?

Stream k8s pod log using we socket using client-go library, which uses http2

### What did you see happen?

High CPU usage in pipe read and mutex time on one CPU core.

[pprof.kube-term.samples.cpu.001.pb.gz](https://github.com/user-attachments/files/16229786/pprof.kube-term.samples.cpu.001.pb.gz)

### What did you expect to see?

Lower CPU usage

**Comment by seankhliao** [comment]
I believe this should first be a kubernetes issue, they have a nonstandard setup with SPDY

**Comment by ttc0419** [comment]
@seankhliao Are you talking about remotecommand.NewSPDYExecutor,  but what I used is the request.Stream.  And the pprof did show ```golang.org/x/net/http2.transportResponseBody.Read``` used most of the CPU time not any of the kubernetes library.
