### ISSUE TITLE
x/image: Link to SVG color spec is outdated

### ISSUE THREAD

**Issue by codesoap** [golang/go#68473]
### Go version

any

### Output of `go env` in your module/workspace:

```shell
doesn't matter
```

### What did you do?

I went to https://pkg.go.dev/golang.org/x/image/colornames and read the documentation of the golang.org/x/image/colornames package.

### What did you see happen?

I found the link http://www.w3.org/TR/SVG/types.html#ColorKeywords, but when following it, I didn't find any information about the colors.

### What did you expect to see?

I expected to see a definition of the colors, that are available in the golang.org/x/image/colornames package.

I suggest to update the link to https://www.w3.org/TR/SVG11/single-page.html#types-ColorKeywords.

**Comment by ianlancetaylor** [comment]
CC @nigeltao

**Comment by codesoap** [comment]
I've just found, that there is also https://www.w3.org/TR/SVG11/types.html#ColorKeywords. This might be preferable to the single-page version of the specification.
