### ISSUE TITLE
Memory leak problem with Opentelemetry Collector Using KafkaReceiver

### ISSUE THREAD

**Issue by Dennis8274** [golang/go#68512]
### Go version

go version go1.20.13 darwin/amd64

### Output of `go env` in your module/workspace:

```shell
go.opentelemetry.io/collector v0.98.0
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkareceiver v0.98.0
```

### What did you do?

 fetching msg and just printing.
pprof result:
<img width="1323" alt="image" src="https://github.com/user-attachments/assets/0348bca2-7f57-46df-b7f4-3daadc7825f8">
<img width="1398" alt="image" src="https://github.com/user-attachments/assets/df6f7780-ee73-42fa-aee4-f524d05e061a">

### What did you see happen?

memory usage is going up over time until oom

### What did you expect to see?

no oom

**Comment by randall77** [comment]
It seems unlikely this is a bug in Go itself. You should open an issue against opentelemetry, probably.
