### ISSUE TITLE
x/pkgsite: `X` is always visible on homepage search

### ISSUE THREAD

**Issue by andybons** [golang/go#68538]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev
 
### What is your user agent?
 

Chrome Mac

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
 
 
### Screenshot
 

 
<img width="759" alt="image" src="https://github.com/user-attachments/assets/57b31abb-f17a-4630-bbad-97c90efe0fe3">

 
 
### What did you do?
 

Visited https://pkg.go.dev
 
 
### What did you expect to see?

No `X` since nothing was in the search input

Additionally:

1. The letter ‘X’ shouldn’t be used as a “clear” icon. Use an actual icon or multiply (‘×’).
2. There’s a bottom border that doesn’t match the rest of the search bar. That should’t be there.
3. Hovering over the close icon causes a white border to appear on the right. That shouldn’t appear either.
 
 
### What did you see instead?

An `X`

**Comment by cespare** [comment]
I remember that this didn't used to be like this. I did a bisect and found that all of the issues mentioned here were introduced in [CL 513037](https://go-review.googlesource.com/c/pkgsite/+/513037).

**Comment by hyangah** [comment]
cc @jba

**Comment by jba** [comment]
Fixed.
