### ISSUE TITLE
x/time/rate: unexpected behaviour with 0 limit

### ISSUE THREAD

**Issue by leesio** [golang/go#68541]
### Go version

$ go version go version go1.22.1 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE='auto'
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/jameslees/Library/Caches/go-build'
GOENV='/Users/jameslees/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/jameslees/pkg/mod'
GONOPROXY='github.com/monzo'
GONOSUMDB='github.com/monzo'
GOOS='darwin'
GOPATH='/Users/jameslees'
GOPRIVATE='github.com/monzo'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/opt/homebrew/Cellar/go/1.22.1/libexec'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/opt/homebrew/Cellar/go/1.22.1/libexec/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.22.1'
GCCGO='gccgo'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD='/Users/jameslees/src/github.com/monzo/wearedev/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/9x/n8nfvk6s4554x9d75k55rl5m0000gn/T/go-build98659086=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

- Created a `rate.Limiter` with `burst: 1` and `limit: 0`
- Called `Allow` on the limiter
- Set the limit to a non-zero value using `SetLimit`
- Called `Wait` on the limiter

```
func main() {
	limiter := rate.NewLimiter(0, 1)

	if !limiter.Allow() {
		// Should be true because the burst is 1
		fmt.Printf("Expected first request to be allowed but wasn't")
	}

	// Set a non-zero limit to start refilling the token bucket
	limiter.SetLimit(100)

	err := limiter.Wait(context.Background())
	if err != nil {
		fmt.Printf("Unexpected error waiting: %v\n", err)
	}
}
```

https://go.dev/play/p/25EIPtjqvDs

### What did you see happen?

`Wait` returns a non-nil `error`: `rate: Wait(n=1) exceeds limiter's burst 0`.

This happens because [the burst is decremented when `reserveN` is called on a `Limiter` with `Limit` of 0](https://github.com/monzo/wearedev/blob/6d94d20d4bf4afbb912a2e0f90bc81d36e303be4/vendor/golang.org/x/time/rate/rate.go#L348-L358) which seems strange/incorrect to me.

The code appeared [here](https://go-review.googlesource.com/c/time/+/323429/2..11/rate/rate.go#b325) but the conversation doesn't really reflect the code: the comment says:

> The opposite in fact needs to happen: lim.tokens must be reduced by the n consumed tokens?

Which makes sense to me, but I'm not sure how we ended up decrementing the burst. To me the solution to the reported problem (limiters not actually being full) would be to set `lim.tokens = burst` on the constructor. I don't think `burst` should be changed by anything except `SetBurst`

### What did you expect to see?

I expected `Wait` to return a `nil` error after an appropriate delay!

**Comment by golanguzb71** [comment]
soo

**Comment by ianlancetaylor** [comment]
CC @Sajmani

**Comment by leesio** [comment]
> To me the solution to the reported problem (limiters not actually being full) would be to set `lim.tokens = burst` in the constructor

Having skimmed the code a bit more, I think this would actually make sense. The overflow [described](https://github.com/golang/go/issues/39984#issuecomment-653179118) in the original issue is specifically [guarded against](https://github.com/golang/time/blob/master/rate/rate.go#L416-L418).

If we remove [this case](https://github.com/golang/time/blob/master/rate/rate.go#L347-L359) entirely, a `NewLimiter(0, 1)` will never allow (instead of always allowing as before). I think changing the constructor to 👇 should resolve that:

```
func NewLimiter(r Limit, b int) *Limiter {
	return &Limiter{
		limit:  r,
		burst:  b,
		tokens: float64(b),
	}
}
```

I can submit a PR with this change

**Comment by Sajmani** [comment]
@leesio initializing tokens to the burst size makes sense to me based on the "initially full" phrase in the Limiter doc comment:
// It implements a "token bucket" of size b, initially full and refilled
// at rate r tokens per second.

I also agree that burst should only be set in the constructor and SetBurst.

Honestly I've lost any familiarity I've had with this code, so I'd feel better with a second set of eyes to review any changes and help us make sure we're not making a backwards-incompatible behavioral change.

**Comment by leesio** [comment]
Cool, glad we're on the same page.

There's no particular rush on my side to get this resolved—we've implemented a workaround on our side. Here's [my suggested patch](https://go-review.googlesource.com/c/time/+/600876). It's very possible I've done something very wrong, it's my first time using the tooling 😅

**Comment by bboreham** [comment]
Is this fixed by https://cs.opensource.google/go/x/time/+/772484ea383fac83b7da05684a96ae628b251bcd ?

**Comment by leesio** [comment]
Yes, it should be.

I was under the impression it would be closed automagically but perhaps I messed some annotation up in my change!
