### ISSUE TITLE
https://github.com/golang/go/issues/68557 was closed by mistake

### ISSUE THREAD

**Issue by NorseGaud** [golang/go#68572]
### Go version

N/A

### Output of `go env` in your module/workspace:

```shell
N/A
```

### What did you do?

Please reopen https://github.com/golang/go/issues/68557

### What did you see happen?

N/A

### What did you expect to see?

N/A

**Comment by ianlancetaylor** [comment]
Reopened though I suspect that it's not a Go bug.
