### ISSUE TITLE
net/textproto: canonicalMIMEHeaderKey returns a  "malformed MIME header line:" for header containing /

### ISSUE THREAD

**Issue by kb4rodrigog** [golang/go#68590]
### Go version

go1.22.5

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/user/Library/Caches/go-build'
GOENV='/Users/user/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/user/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/user/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.22.5'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/user/projects/project/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/g0/r8qb78z13c3_x62jqrr_6xqm0000gp/T/go-build1410450898=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

I tried to get the mime headers passing an email header 

```
	tr := textproto.NewReader(bufio.NewReader(bytes.NewReader(b)))
	headers, err := tr.ReadMIMEHeader()
```

### What did you see happen?

I got this error: 
`malformed MIME header line: X-Hdr-a/b`

### What did you expect to see?

I expect to see this mime header along with the others in the headers object.

The issue happens because the function `validHeaderFieldByte` is missing the `/` character in the list of valid ones

https://datatracker.ietf.org/doc/html/rfc2822#section-3.6.8
```
optional-field  =       field-name ":" unstructured CRLF

field-name      =       1*ftext

ftext           =       %d33-57 /               ; Any character except
                        %d59-126                ;  controls, SP, and
                                                ;  ":".
```

The validation was already missing the character in version 1.19, but the `canonicalMIMEHeaderKey` function was not returning the boolean value to indicate as a !ok to the `readMIMEHeader` function. 
```
// validHeaderFieldByte reports whether b is a valid byte in a header
// field name. RFC 7230 says:
//
//	header-field   = field-name ":" OWS field-value OWS
//	field-name     = token
//	tchar = "!" / "#" / "$" / "%" / "&" / "'" / "*" / "+" / "-" / "." /
//	        "^" / "_" / "`" / "|" / "~" / DIGIT / ALPHA
//	token = 1*tchar
func validHeaderFieldByte(b byte) bool {
	return int(b) < len(isTokenTable) && isTokenTable[b]
}

// canonicalMIMEHeaderKey is like CanonicalMIMEHeaderKey but is
// allowed to mutate the provided byte slice before returning the
// string.
//
// For invalid inputs (if a contains spaces or non-token bytes), a
// is unchanged and a string copy is returned.
func canonicalMIMEHeaderKey(a []byte) string {
	// See if a looks like a header key. If not, return it unchanged.
	for _, c := range a {
		if validHeaderFieldByte(c) {
			continue
		}
		// Don't canonicalize.
		return string(a)
	}
  ...
}
```

**Comment by dcormier** [comment]
Seeing as [the `textproto` package docs](https://pkg.go.dev/net/textproto@go1.22.5) state it should work for the likes of SMTP, it seems like headers from those relevant RFCs should be supported.

> Package textproto implements generic support for text-based request/response protocols in the style of HTTP, NNTP, and SMTP.

**Comment by ianlancetaylor** [comment]
For #53188 we restricted the set of permitted characters in the textproto package to conform to RFC 7230.  We aren't going to go back on that.  For the specific case of mail messages we added CL 504416 to permit more characters for mail messages, as part of #58862 and #60332.

I don't think there is anything to do here.  Sorry.

**Comment by dcormier** [comment]
The docs on textproto state it's intended for use in SMTP. If that's not the case, should those docs be updated to reflect that?
