### ISSUE TITLE
encoding/xml, encoding/json: package docs don't mention encoding.TextMarshaler and encoding.TextUnmarshaler

### ISSUE THREAD

**Issue by songgao** [golang/go#6859]
<pre>version: Go 1.2

What is the expected output?
`encoding/xml` and `encoding/json` should document the behavior that it will check
encoding.TextMarshaler and encoding.TextUnmarshaler.</pre>

**Comment by AlekSi** [comment]
I wanted some text format for for my `struct` so I implemented `TextMarshaler` and `TextUnmarshaler` like this:
```
func (t *T) MarshalText() ([]byte, error) {
	return xml.MarshalIndent(m, "", "  ")
}

func (t *T) UnmarshalText(b []byte) error {
 	return xml.Unmarshal(b, m)
}
```

Then I spent an hour debugging why _simplest_ code like `t.UnmarshalText(bytes)` fails with `io.EOF`.

Please document this behaviour.

**Comment by leighmcculloch** [comment]
[CL 76350](https://golang.org/cl/76350) contains:

- Examples for both `encoding/json` and `encoding/xml` that demonstrate using the `encoding.TextMarshaler` and `encoding.TextUnmarshaler` interfaces.
- An example for `encoding/xml` that demonstrates custom marshaling using `MarshalXML` and `UnmarshalXML`.
- Docs for `encoding/xml` that are mirrored off `encoding/json`.

All new examples are modeled off the existing custom marshal example in `encoding/json`.
