### ISSUE TITLE
x/pkgsite: package removal request for https://pkg.go.dev/github.com/amandlaus/gocrypt

### ISSUE THREAD

**Issue by ghost** [golang/go#68611]
Greetings.
I am writing to request the remove of a package from go.dev. The details are as follows:

- Package URL on go.dev: https://pkg.go.dev/github.com/amandlaus/gocrypt
- Repository URL: https://github.com/amandlaus/gocrypt (I have deleted it.)

Reason for removal:
Gocrypt is the first package that I tried to publish and as a result I messed up in its versioning (tags). Due I was not able to download this package in my other go projects. I tried to clear modcache and even deleted the github repository several times and then recreated it with the hopes of being able to fix this problem.
After a while I realised that the reason why this package was not being overriden even after re-creating new github repositories having the exact same url was that go modules are being picked from a proxy go pkg server. Therefore I'm here to request the removal of this package so that I can push a new initial release of it.

I had read online that I need to "retract" the module by adding this directive in go.mod file. I'm not sure how that works and how to do it. Kindly guide with this too.

Thank you for your assistance. Please let me know if any additional information is required.

Best regards,
Armaan Mandlaus
Email: armaan.mandlaus@gmail.com

**Comment by seankhliao** [comment]
Once picked up by the proxy and sumdb, you cannot reuse/redefine a given module name and version combination.
A removal request only hides the generated documentation, the content hash of the name/version is permanent.

**Comment by armaanmbtech** [comment]
So there's no way to get it fixed?

**Comment by amandlaus** [comment]
I'm not quite sure at the moment if it has been picked up by the proxy or sumdb. How can I check that? Assuming that the package wasn't picked up by either of these, then can it be removed permanently such that I can reuse the given module name?

**Comment by seankhliao** [comment]
If pkg.go.dev has it then it has definitely been picked up (pkg.go.dev reads from the proxy).

**Comment by amandlaus** [comment]
So can you guide me on what else can I do? I heard about retract directive. How can I use that?
