### ISSUE TITLE
go/types: pointer receiver types not recorded in types.Info with Go 1.24

### ISSUE THREAD

**Issue by griesemer** [golang/go#68639]
[CL 594740](https://go.dev/cl/594740) rewrote type checking of method receiver types. Because that CL takes apart the receiver "manually" rather than using the regular code for type checking type expressions, pointer and parenthesized receiver type expressions are not recorded anymore.

The following test shows the discrepancy between [Go 1.22](https://go.dev/play/p/J8_poKKKdlL) (working correctly) and [Go 1.23 (Go at tip)](https://go.dev/play/p/J8_poKKKdlL?v=gotip) (not working correctly anymore).

cc: @adonovan @findleyr @timothy-king for visibility.

**Comment by findleyr** [comment]
This is 1.24, not 1.23, right? The CL above was only merged to the master branch, after the tree was open.
(otherwise, this would be a 1.23 release blocker I think).

**Comment by griesemer** [comment]
@findleyr Yes, of course. I had fixed the milestone but missed the title. Adjusted. CL ready for review.
