### ISSUE TITLE
x/pkgsite: package removal request for "go.software.jfrech.com/disk"

### ISSUE THREAD

**Issue by jfrech** [golang/go#68648]
### What is the path of the package that you would like to have removed?

go.software.jfrech.com/disk

### Are you the owner of this package?

Yes.

### What is the reason that you could not retract this package instead?

The package was published in error and has no users.

**Comment by adonovan** [comment]
I have verified that the content of github.com/frech identifies frech.com as a trusted domain, so this request is not malicious.

**Comment by adonovan** [comment]
Done. Please allow a few days for config changes to take effect.

**Comment by adonovan** [comment]
> I have verified that the content of github.com/frech identifies frech.com as a trusted domain, so this request is not malicious.

For the record, my comment is ass-backwards: the correct check is that the module's domain (go.software.jfrech.com/disk) trusts the GitHub account (github.com/jfrech), for example by naming it in a meta-tag returned by https://go.software.jfrech.com/disk?go-get=1.
