### ISSUE TITLE
access: approver

### ISSUE THREAD

**Issue by archanaravindar** [golang/go#68646]
See https://go.dev/wiki/GerritAccess

Hello Go release team,

I am kindly requesting Approver access as we need more people to approve changes coming in from the ppc64le side 
Group URL: https://go-review.googlesource.com/#/admin/groups/1005,members
Gerrit email address: [aravinda@redhat.com](mailto:aravinda@redhat.com)
The following summarizes my contributions towards golang so far, 
https://go-review.googlesource.com/q/aravind5
https://go-review.googlesource.com/q/aravinda

**Comment by mknyszek** [comment]
Your request has been reviewed and approved. You should now be an approver. Please comment here if you run into any problems. Thanks for your contributions!
