### ISSUE TITLE
x/pkgsite: documentation hidden when LICENSE.md contains text explaining license application to directories

### ISSUE THREAD

**Issue by roman-khimov** [golang/go#68650]
### What is the URL of the page with the issue?
https://pkg.go.dev/github.com/nspcc-dev/neofs-contract@v0.20.0/common 
 
### What is your user agent?
Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0
 
### Screenshot
<img width="347" alt="Screenshot_20240730_164703" src="https://github.com/user-attachments/assets/ccbd223d-d4d6-46fc-b9ab-a009acc70790"> 
 
### What did you do?
Opened the page above.
 
### What did you expect to see?
Package documentation.
 
### What did you see instead?
Licensing error.

### What's up with neofs-contract license?
It's a bit complicated because it has blockchain contracts that are historically GPLv3 and it has some library code for contract integration with is Apache 2.0. Both are OSI-approved and this is explained in https://github.com/nspcc-dev/neofs-contract/blob/2059417af6e3c98dbcb875cead15cd21db8b1751/LICENSE.md, but pkg.go.dev can't figure it out on its own (which is understandable).

Maybe this can still be fixed manually? Maybe we can move/rename/reword license files in some way for this to be auto-detected?

**Comment by hyangah** [comment]
LICENSE.md or LICENSE should have only recognized license text verbatim. The [LICENSE.md](https://github.com/nspcc-dev/neofs-contract/blob/2059417af6e3c98dbcb875cead15cd21db8b1751/LICENSE.md) is not recognized. 
As @jfrech suggested, use a different file to state the restriction (the files checked by the license checker are listed in https://pkg.go.dev/license-policy). Alternatively, I think you can place copies of the license text in the directories where different license applies.
