### ISSUE TITLE
access: request for may-start-trybots

### ISSUE THREAD

**Issue by Garrett-Bodley** [golang/go#68667]
I have a number of CL's, some of which I intend to chain together. This interferes with TryBot as seen in https://github.com/golang/go/issues/65140

Tagging in @FiloSottile on this request

**Comment by FiloSottile** [comment]
Also yes, please. I work with @Garrett-Bodley and they will have a large chain to land soon.

**Comment by mknyszek** [comment]
We've reviewed your request and approved. You should now have may-start-trybots permissions. Please comment if you run into any issues. Thanks for contributing to Go!
