### ISSUE TITLE
cmd/gc: odd imprecision with constant arithmetic

### ISSUE THREAD

**Issue by griesemer** [golang/go#6866]
<pre>The following program:

<a href="http://play.golang.org/p/0yZm6JdjVS">http://play.golang.org/p/0yZm6JdjVS</a>

should produce the identity matrix. However the result is:

+1.000000e+000 +0.000000e+000
-4.508290e-131 +1.000000e+000

The error -4.508290e-131 for element (1, 1) appears to be due to the following two
expressions not being the same:

2 + 1.0/3*-6
2 - 1.0/3*+6

(note that only the signs are swapped for the last operand):

<a href="http://play.golang.org/p/J1KAaUMR1t">http://play.golang.org/p/J1KAaUMR1t</a>

-4.508290e-131
+0.000000e+000</pre>

**Comment by griesemer** [comment]
Running this code after

https://golang.org/cl/7912/

produces PASS.

(The likely culprit was the conversion to two's complement which causes the symmetric expressions (but for the signs) to be asymmetric, with different behavior.)

**Comment by bradfitz** [comment]
@griesemer, nice!
