### ISSUE TITLE
go-gssapi build issue

### ISSUE THREAD

**Issue by huaraz** [golang/go#68680]
### Go version

go version go1.22.5 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE='on'
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/huaraz/.cache/go-build'
GOENV='/home/huaraz/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/huaraz/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/huaraz/go'
GOPRIVATE=''
GOROOT='/usr/lib64/go/1.22'
GOSUMDB='off'
GOTMPDIR=''
GOTOOLCHAIN='local'
GOTOOLDIR='/usr/lib64/go/1.22/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22.5'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/src/huaraz/go-proxy-auth/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2608902204=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

Added import 

package main with go-gssapi

import (
        "encoding/base64"
        "fmt"
        "io/ioutil"
        "log"
        "net/http"
        "net/http/httputil"
        "net/url"
        "github.com/golang-auth/go-gssapi/v2"
        _ "github.com/golang-auth/go-gssapi/v2/krb5"
)

and run go mod tidy and get 

go: finding module for package github.com/golang-auth/go-gssapi/v2/krb5
go: finding module for package github.com/golang-auth/go-gssapi/v2
go: found github.com/golang-auth/go-gssapi/v2 in github.com/golang-auth/go-gssapi/v2 v2.2.2-alpha
go: found github.com/golang-auth/go-gssapi/v2/krb5 in github.com/golang-auth/go-gssapi/v2 v2.2.2-alpha
go: finding module for package github.com/golang-auth/go-gssapi/v2/common
go: negotiate imports
        github.com/golang-auth/go-gssapi/v2 imports
        github.com/golang-auth/go-gssapi/v2/common: module github.com/golang-auth/go-gssapi/v2@latest found (v2.2.2-alpha), **_but does not contain package github.com/golang-auth/go-gssapi/v2/common_**

### What did you see happen?

Can't find the package

### What did you expect to see?

Successful mod tidy / build

**Comment by seankhliao** [comment]
The package indeed does not exist at the given version https://github.com/golang-auth/go-gssapi/tree/v2.2.2-alpha/v2

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by huaraz** [comment]
Thank you and Apologies
