### ISSUE TITLE
x/pkgsite: remove github.com/golang/perf (the correct one is golang.org/x/perf)

### ISSUE THREAD

**Issue by mark-pictor-csec** [golang/go#68703]
### Go version

N/A

### Output of `go env` in your module/workspace:

```shell
N/A
```

### What did you do?

Visit https://pkg.go.dev/github.com/golang/perf/cmd/benchstat

### What did you see happen?

Documentation is for `v0.0.0-20190306144031-151b6387e3f2`, from 2019. Documented flags include `-html`, which does not exist in the latest version.

### What did you expect to see?

Documentation matches the binary installed via `go install golang.org/x/perf/cmd/benchstat@latest`.
The flag was removed in [perf rev 02c5517](https://github.com/golang/perf/commit/02c55175bb825ade4507ee5d459ea6a1ab6e0af5), from January 2023.

**Comment by mknyszek** [comment]
CC @aclements maybe?

**Comment by prattmic** [comment]
https://pkg.go.dev/github.com/golang/perf/cmd/benchstat is the documentation for `github.com/golang/perf`, not `golang.org/x/perf`. Only the latter is the correct module path.

The psuedoversion `v0.0.0-20190306144031-151b6387e3f2` is at https://go.googlesource.com/perf/+/151b6387e3f2aa5908e4a6074f06be9ecc34f004, before there was a `go.mod` file, so I suppose this package was importable via `github.com/golang/perf`.

cc @golang/pkgsite is there anything we can do here to avoid confusion? Perhaps just remove `github.com/golang/perf` entirely?

**Comment by thepudds** [comment]
This is probably similar to #68357 (though I didn’t double check the details, so sorry if not).

**Comment by mark-pictor-csec** [comment]
When I submitted, it hadn't occurred to me that there were two different URLs for benchstat docs.
https://pkg.go.dev/golang.org/x/perf/cmd/benchstat
https://pkg.go.dev/github.com/golang/perf/cmd/benchstat

For `pkg.go.dev/golang.org/x/perf/...`, is the package crawler actually using the golang.org url or does it still go to `github.com/golang/perf/...` like the other?

My thinking is, if the package crawler detects all of the following:
* `$url` and `$url2` are both for code in the same git repo, and
* only one of the two has a module, and
* the one with the module is newer
... then manipulate the page in some way that results in users going to the better version.

This manipulation could take the form of a banner `newer version at new import path [link]` and/or, as mentioned in https://github.com/golang/go/issues/68357#issuecomment-2219463378, via meta tags telling search engines to go away. (IMO adding both would be best, so that if I get to the old version in spite of a search engine, I can still get to the newest/best version).

I think this approach would work on both #68357 and on this issue.

**Comment by prattmic** [comment]
> For `pkg.go.dev/golang.org/x/perf/...`, is the package crawler actually using the golang.org url or does it still go to `github.com/golang/perf/...` like the other?

golang.org/x/... uses the `<meta name="go-import">` [mechanism](https://go.dev/ref/mod#vcs-find) to redirect to the actual git repository. However, the official git repo for golang.org/x/perf is https://go.googlesource.com/perf, not https://github.com/golang/go.

So while I think your proposed approach would work for most vanity import paths, it wouldn't work here.

**Comment by hyangah** [comment]
Let's remove github.com/golang/perf from pkgsite.
