### ISSUE TITLE
x/pkgsite: package removal request for "github.com/belseir/holodex-go"

### ISSUE THREAD

**Issue by Belseir** [golang/go#68707]
# What is the path of the package that you would like to have removed?
"github.com/belseir/holodex-go"

# Are you the owner of this package?
Yes, I am.

# What is the reason that you could not retract this package instead?
I've deleted the repository and I don't have a copy of it. In addition, the package had no users and was published by mistake

**Comment by adonovan** [comment]
[Done](https://team-review.git.corp.google.com/c/golang/discovery-private/+/2303759). Please allow a few days for config changes to take effect.
