### ISSUE TITLE
x/pkgsite: incorrect license parse of github.com/octokit/go-sdk-enterprise-cloud

### ISSUE THREAD

**Issue by icco** [golang/go#68705]
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/github.com/octokit/go-sdk-enterprise-cloud@v0.0.1/pkg/github
 
### What is your user agent?
 

 
 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36

 
### Screenshot
 

 
![Uploading Screenshot 2024-08-01 at 13.36.47.png…]()

 
 
### What did you do?
 

 
visited the page
 
 
### What did you expect to see?
 
no license warning box as this is MIT licensed code
 
 
### What did you see instead?

A warning about the License.

**Comment by seankhliao** [comment]
The version you're looking at does not have a license.
