### ISSUE TITLE
x/mobile: EGLNativeWindowType definition mismatch on Android Termux

### ISSUE THREAD

**Issue by vsm0** [golang/go#68727]
I first encountered this issue when compiling an Ebitengine app in an Android Termux environment.

Full disclosure, there's the open build issue [#47727](https://github.com/golang/go/issues/47727#issue-972144481) also for Termux, but doesn't seem related.

The package uses ebitenmobile, which is an extension of golang.org/x/mobile. From that discussion I was advised to report the issue in the upstream repo if I could reproduce the error there.

I did, so here I am. The following is more or less a replica of [the original issue](https://github.com/hajimehoshi/ebiten/issues/3057#issue-2447187465)

### Operating System

- [X] Android (Termux app)

### Go Version (`go version`)

1.22.5

### Output of Go env (`go env`)

```bash
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/data/data/com.termux/files/home/.cache/go-build'
GOENV='/data/data/com.termux/files/home/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='android'
GOINSECURE=''
GOMODCACHE='/data/data/com.termux/files/home/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='android'
GOPATH='/data/data/com.termux/files/home/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/data/data/com.termux/files/usr/lib/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN=''
GOTOOLDIR='/data/data/com.termux/files/usr/lib/go/pkg/tool/android_arm64'
GOVCS=''
GOVERSION='go1.22.5'
GCCGO='gccgo'
AR='ar'
CC='aarch64-linux-android-clang'
CXX='aarch64-linux-android-clang++'
CGO_ENABLED='1'
GOMOD='/data/data/com.termux/files/home/tmp/mobile/example/basic/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -pthread -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/data/data/com.termux/files/usr/tmp/go-build1234048493=/tmp/go-build -gno-record-gcc-switches'
```

### What steps will reproduce the problem?

Create _main.go_ with the following contents (basic window example):

```go
package main

import (
	"github.com/hajimehoshi/ebiten/v2"
	"github.com/hajimehoshi/ebiten/v2/ebitenutil"
)

const (
	WIDTH = 480
	HEIGHT = 360
)

type Game struct {}

func (g *Game) Layout(widith, height int) (int, int) {
	return WIDTH, HEIGHT
}

func (g *Game) Update() error {
	return nil
}

func (g *Game) Draw(img *ebiten.Image) {
	ebitenutil.DebugPrint(img, "Hello World")
}

func main() {
	ebiten.SetWindowSize(WIDTH * 2, HEIGHT * 2)
	ebiten.SetWindowTitle("Untitled")

	if err := ebiten.RunGame(&Game{}); err != nil {
		panic(err)
	}
}
```

create _go.mod_ and run program:
```bash
go mod init example
go mod tidy
go run .
```

### What is the expected result?

A bare window with some text should appear.

### What happens instead?

The following error appears during compilation:
```bash
android.c:171:52: error: incompatible pointer to integer conversion passing 'ANativeWindow *' (aka 'struct ANativeWindow *') to parameter of type 'EGLNativeWindowType' (aka 'unsigned long') [-Wint-conversion]
../../../../usr/include/EGL/egl.h:136:109: note: passing argument to parameter 'win' here
```

### Anything else you feel useful to add?

The compilation environment is Termux, which is non-standard Android.

After some investigation, the clash between parameter value and signature is possibly due an incorrect/incomplete appraisal of the compilation environment, within the header __eglplatform.h__, as noted by the error.

A standard Android target (as defined in _eglplatform.h_) has the following conditional definition:

```c
#elif defined(__ANDROID__) || defined(ANDROID)
#include <android/native_window.h>
...
typedef struct ANativeWindow* EGLNativeWindowType;
```

However, Termux modifies this slightly:

```c
#elif (defined(__ANDROID__) || defined(ANDROID)) && !defined(__TERMUX__)
...                                                                 
typedef struct ANativeWindow* EGLNativeWindowType;
```

Since this definition doesn't match, I suspect it falls through to the next defined variable '__unix__' (which I confirmed by preprocessing gomobile/app/android.c using _gcc -E -dM android.c_):

```c
#elif defined(__unix__)
...
typedef khronos_uintptr_t EGLNativeWindowType;
```

It's my first time digging so deep into library internals, but unless I'm way off mark, it's possible that gomobile uses the standard eglplatform.h header, which mistakes the Termux environment for a standard Android one.

**Comment by hajimehoshi** [comment]
From the script you executed, gomobile is not related.
