### ISSUE TITLE
How many virtual memory I can use? 

### ISSUE THREAD

**Issue by li9270** [golang/go#68739]
go version 1.14
My go program vss increased, while rss is stable.  I haven seen:
(1) "The runtime now uses a sparse heap layout so there is no longer a limit to the size of the Go heap (previously, the limit was 512GiB)." in https://go.dev/doc/go1.11 
(2) go use midvise to release memory, not umap
My go program work well now. If the program runs for a long time, will it exhaust the virtual address space or influence other app using memory?
I have some question:
(1) virtual adress space which go used is unlimited ?
(2) go reserve a large virtual address space in init stage, how to understand it ?
Is there any revent document or advise? 
Thanks a lot.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
