### ISSUE TITLE
x/pkgsite: package removal request for [https://pkg.go.dev/github.com/erdos99/gverify]

### ISSUE THREAD

**Issue by jishaocong0910** [golang/go#68740]
Hi,

I would like to request the removal of the package https://pkg.go.dev/github.com/erdos99/gverify，I have made the repository private

Thank you very mush.

**Comment by adonovan** [comment]
For us to remove the repository, you would need to demonstrate that you have write access to the repository, as all the commits are by another GitHub user. But the GitHub repo for that Go module appears still to exist. Have you tried following the instructions on "Removing a package at https://pkg.go.dev/about? A simple `retract` declaration in your go.mod file should be all that is needed.

**Comment by jishaocong0910** [comment]
@adonovan I have removed the repository just now, I use other account to publish the repository, so I don't want to keep the old one. I will try to use retract next time

**Comment by hyangah** [comment]
Removed
