### ISSUE TITLE
x/telemetry/config: add collection for gopls/gotoolchain

### ISSUE THREAD

**Issue by findleyr** [golang/go#68771]
### Summary

In #65917, we plan to use forward compatibility to ensure that gopls is installed with the latest Go toolchain.
Before doing so, we want to understand what fraction of users work in an environment where toolchain upgrades are supported. By collecting the gopls/gotoolchain counter, we can help inform this understanding.

### Proposed Config Change

https://go.dev/cl/603857

**Comment by cagedmantis** [comment]
cc [@golang/telemetry](https://github.com/orgs/golang/teams/telemetry)

**Comment by findleyr** [comment]
This was discussed in the telemetry meeting last week, with no objections. Since there have been no external objections, I'll accept and implement.
