### ISSUE TITLE
access: gomote

### ISSUE THREAD

**Issue by kolyshkin** [golang/go#68779]
Per https://go.dev/wiki/Gomote#access I'm requesting gomote access for me (kolyshkin@gmail.com).

I need this as I'm working to reproduce issues #68663 and #68687 and was unable to reproduce this locally.

**Comment by cherrymui** [comment]
Thank you for contributing to Go, and filing this request!

You should have gomote access now. Please be familiar with gomote usage as described at https://go.dev/wiki/Gomote .

Thanks.
