### ISSUE TITLE
x/build: add 1.23 and tip builders with GODEBUG=gotypesalias=1 for at least the x/tools repo

### ISSUE THREAD

**Issue by findleyr** [golang/go#68798]
See #68796 and #68797 for some background on missing test coverage with GODEBUG=gotypesalias=1.

Until x/tools has a go.mod file that says 1.23 (not until at least 1.24 is released), it will lack test coverage of GODEBUG=gotypesalias=1. @timothy-king had added go1.21 and go1.22 builders with GODEBUG=gotypesalias=1; we need them for 1.23 and tip as well.

@timothy-king @dmitshur would you mind adding these as well? CC @adonovan

**Comment by dmitshur** [comment]
These builders were recently updated in [CL 601177](https://go.dev/cl/601177) to stop existing after 1.22 based on the idea that 1.23 and later already default to GODEBUG=gotypesalias=1. I'll refine that to keep them around for 1.23 and 1.24 as well.

**Comment by findleyr** [comment]
Thanks very much @dmitshur! Would it be possible to add the tip builder to the default presubmit tryset as well?

**Comment by DashaBochkar** [comment]
> See #68796 and #68797 for some background on missing test coverage with GODEBUG=gotypesalias=1.
> 
> 
> 
> Until x/tools has a go.mod file that says 1.23 (not until at least 1.24 is released), it will lack test coverage of GODEBUG=gotypesalias=1. @timothy-king had added go1.21 and go1.22 builders with GODEBUG=gotypesalias=1; we need them for 1.23 and tip as well.
> 
> 
> 
> @timothy-king @dmitshur would you mind adding these as well? CC @adonovan
