### ISSUE TITLE
cmd/vet,x/tools/go/analysis/passes/printf: broken with GODEBUG=gotypesalias=1

### ISSUE THREAD

**Issue by findleyr** [golang/go#68796]
Repro, originating from @adonovan's investigation of #68744:

```
> cat bad.go
package main

import "fmt"

func main() {
        fmt.Printf("%s", 123)
        wrapf("%s", 123)
}

func wrapf(format string, args ...any) {
        fmt.Printf(format, args...)
}
> go version
go version go1.23rc2 linux/amd64
> go vet bad.go 
# command-line-arguments
# [command-line-arguments]
./bad.go:6:2: fmt.Printf format %s has arg 123 of wrong type int
./bad.go:7:2: command-line-arguments.wrapf format %s has arg 123 of wrong type int
> GODEBUG=gotypesalias=0 go vet bad.go 
# command-line-arguments
# [command-line-arguments]
./bad.go:6:2: fmt.Printf format %s has arg 123 of wrong type int
./bad.go:7:2: command-line-arguments.wrapf format %s has arg 123 of wrong type int
> GODEBUG=gotypesalias=1 go vet bad.go 
# command-line-arguments
# [command-line-arguments]
./bad.go:6:2: fmt.Printf format %s has arg 123 of wrong type int
```

When GODEBUG=gotypesalias=1 (the default in 1.23), the printf analyzer fails to report a diagnostic for the `wrapf` printf wrapper, due to a missing call to `types.Unalias`.

Separately, it appears the default vet tool distributed with 1.23rc2 (or built on the release branch with `make.bash`) does not have GODEBUG=gotypesalias=1. Otherwise, this should have been caught by the vet integration tests. I will file a separate issue for that.

It may be the case that the two bugs mentioned in the previous two paragraphs effectively cancel themselves out for the Go distribution. However, I think we should at least block the release until we understand both better.

**Comment by findleyr** [comment]
Now that we understand it better, I don't think this needs to block the release. A missing vet diagnostic for printf wrappers (that use any, not interface{}) seems to be benign enough to fix in 1.23.1.

**Comment by dmitshur** [comment]
Thanks. For this to be fixed in go1.23.1, it'll still need to be fixed at tip first and then backported, so moving this to Go1.24 milestone and re-adding release-blocker. Please use the usual process (https://go.dev/wiki/MinorReleases) to create a separate backport tracking issue in the Go1.23.1 milestone.

**Comment by findleyr** [comment]
@gopherbot please backport this issue to 1.23. It is a regression that may affect vet if #68797 is also backported.

**Comment by findleyr** [comment]
To clarify: right now the version of vet distributed with go1.23rc2 DOES work as expected. It is only if we fix the incorrect GODEBUG value to have gotypesalias=1 that we would observe the printf bug, and *even* if that happened I don't think the nature of this bug is severe enough to block this release. I'm not even sure we should backport the fix to 1.23, unless we decide to also backport a fix for #68797.

One of the motivations for marking this as a release blocker was that we weren't sure if GODEBUG was being set correctly during compilation of ALL programs. It turns out that the issue with GODEBUG is restricted to toolchain programs, as a result of the bootstrap process. That is a *much* smaller problem.

**Comment by xiaokentrl** [comment]
I really love the Dynamic-Wallpaper software. If there were a Windows or Linux version, I would be willing to purchase it for a lifetime.

**Comment by dmitshur** [comment]
Checking on this issue as it's a release blocker. Any updates? Thanks.
