### ISSUE TITLE
x/tools/go/callgraph/vta: TestVTACallGraph fails with GODEBUG=gotypesalias=1

### ISSUE THREAD

**Issue by findleyr** [golang/go#68799]
As reported in #68798, we lack test coverage of GODEBUG=gotypesalias=1 in x/tools.

Fortunately, it appears that most tests do pass with this setting (likely since we ran tests during development). However, x/tools/go/callgraph/vta.TestVTACallGraph fails:

```
--- FAIL: TestVTACallGraph (0.06s)                                                                                                                         21:05:12 [126/1617]
    --- FAIL: TestVTACallGraph/testdata/src/callgraph_type_aliases.go (0.01s)          
        vta_test.go:44: computed callgraph [init:  Do: (C).Foo(struct{}{}:Z) -> C.Foo; NewY() -> NewY C.Foo:  Baz: Do(b) -> Do; invoke t0.Foo() -> A.Foo, B.Foo NewY:  B.Foo: 
 B.Foo: (testdata.B).Foo(t1) -> B.Foo A.Foo:  A.Foo: (testdata.A).Foo(t1) -> A.Foo C.Foo: (testdata.C).Foo(t1) -> C.Foo]                                                      
            should contain                                                                                                                                                    
            [Baz: Do(b) -> Do; invoke t0.Foo() -> A.Foo, B.Foo Do: (C).Foo(struct{}{}:C) -> C.Foo; NewY() -> NewY]                                                            
            (diff: [Do: (C).Foo(struct{}{}:C) -> C.Foo; NewY() -> NewY])                                                                                                      
FAIL 
```

Tentatively assigning to zvonimir, though I think @timothy-king also has context on this package and is very familiar with `gotypesalias`.  CC @adonovan

**Comment by dmitshur** [comment]
Thanks for fixing this. I used the fact this was recently broken to confirm the x_tools-gotip-linux-amd64-typesalias builder being added for #68798 is working as expected, and it's indeed passing at the fix commit and failing at its parent:

<img width="1004" alt="image" src="https://github.com/user-attachments/assets/f632d720-6e8c-4a5e-8294-40ccc5573c44">
