### ISSUE TITLE
error obtaining VCS status: exit status 128 / Use -buildvcs=false to disable VCS stamping.

### ISSUE THREAD

**Issue by non7top** [golang/go#68834]
### Go version

go1.20.14

### Output of `go env` in your module/workspace:

```shell
n/a
```

### What did you do?

I'm trying to build latest go using source tarballs
go1.4-bootstrap-20171003 OK
go1.19.5 OK
go1.20.14 FAIL

The commands I run
export GOFLAGS="$GOFLAGS -buildvcs=false"
GOFLAGS="-buildvcs=false" GOROOT_BOOTSTRAP=/home/local/go1.19.5 ./make.bash

I'm using this documentation
https://go.dev/doc/install/source

I'm using this source
https://go.dev/dl/go1.20.14.src.tar.gz

### What did you see happen?

```
+(./make.bash:222): ./cmd/dist/dist bootstrap -a
Building Go toolchain1 using /home/local/go1.19.5.
error obtaining VCS status: exit status 128
        Use -buildvcs=false to disable VCS stamping.
error obtaining VCS status: exit status 128
        Use -buildvcs=false to disable VCS stamping.
error obtaining VCS status: exit status 128
        Use -buildvcs=false to disable VCS stamping.
error obtaining VCS status: exit status 128
        Use -buildvcs=false to disable VCS stamping.
go tool dist: FAILED: /home/local/go1.19.5/bin/go install -tags=math_big_pure_go compiler_bootstrap purego bootstrap/cmd/...: exit status 1
```

### What did you expect to see?

No error
If error, I would expect some helpful error message. `Use -buildvcs=false to disable VCS stamping.` does not help to resolve the issue. I was not able to find docs about how to use buildvcs to build go from source.

**Comment by seankhliao** [comment]
1.20 is outside of our support window ( 2 most recent releases).
