### ISSUE TITLE
syscall: on ARM-based MacOS, read() is unable to read more than 1024 bytes at once

### ISSUE THREAD

**Issue by kmahyyg** [golang/go#68836]
### Go version

go version go1.22.6 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/USERNAME_REDACTED/Library/Caches/go-build'
GOENV='/Users/USERNAME_REDACTED/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/USERNAME_REDACTED/Developer/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/USERNAME_REDACTED/Developer/go'
GOPRIVATE=''
GOPROXY='https://goproxy.cn,direct'
GOROOT='/opt/homebrew/Cellar/go/1.22.6/libexec'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/opt/homebrew/Cellar/go/1.22.6/libexec/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.22.6'
GCCGO='gccgo'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='0'
GOMOD='/Users/USERNAME_REDACTED/Developer/GitBins/PROJECT_REDACTED/src/PROJECT_REDACTED/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/m4/whlp11796rqd17gnlgwz5fpw0000gn/T/go-build594205049=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

```
package utils

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

func ReadUserInputSingleLine(prompt string) (string, error) {
	fmt.Println(prompt)
	reader := bufio.NewReader(os.Stdin)
	text, err := reader.ReadString('\n')
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(text), nil
}
```

My computer is running MacOS 14.5 (23F79) with M1 chip.

I tried to receive user input interactively from stdin using the code above.
`lsof -p PID` returned fd 0 (stdin) is linked to `/dev/ttys001`.

### What did you see happen?

Then when I run the program in iTerm2/Goland terminal:
- Input 1024 bytes repeated `A`, press enter, the program will be no response.
- Don't exit, just remove the last `A`, so the whole input in memory is `1023 bytes A + trailing null byte`, press enter, now it works.

According to your builtin library code, this should be available for receiving max 4096 bytes at once, but now it is only 1024 bytes, totally unexpected. I can't determine whether the bug is on Apple side or Golang side.

I tried to set breakpoint on read syscall, then when it is trying to read input, it goes to `svc #0x80`.

```
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.2
    frame #0: 0x000000018dbd6dac libsystem_kernel.dylib`read
libsystem_kernel.dylib`read:
->  0x18dbd6dac <+0>:  mov    x16, #0x3
    0x18dbd6db0 <+4>:  svc    #0x80
    0x18dbd6db4 <+8>:  b.lo   0x18dbd6dd4               ; <+40>
    0x18dbd6db8 <+12>: pacibsp
Target 0: (go_build_REDACTED_cmd_REDACTED) stopped.
(lldb) c
Process 10306 resuming
```

If I compile the same code and run on go1.22.6/Windows/AMD64, this code is working as expected, can receive more than 1024 bytes.

### What did you expect to see?

when I run the program in iTerm2/Goland terminal:
- Input 1024 bytes repeated `A`, press enter, the program will continue to run.

**Comment by xiaokentrl** [comment]
I really love the Dynamic-Wallpaper software. If there were a Windows or Linux version, I would be willing to purchase it for a lifetime.

**Comment by MasterKenway** [comment]
After I debug, I found first time run into syscall function, and the program did not come out
```

**Comment by ianlancetaylor** [comment]
It helps to show a complete stand-alone program.  Thanks.

The portion you posted looks incorrect.  `bufio.NewReader` buffers input; that's why it exists.  It will read all the available input into its buffer.  In your `ReadUserInputSingleLine` function, you are creating a buffer, reading a single line from the buffer, and then discarding anything else that is in the buffer.

I have no particular reason to think that that is the problem here, but without a complete program it's hard to be sure.

**Comment by kmahyyg** [comment]
> It helps to show a complete stand-alone program. Thanks.
> 
> The portion you posted looks incorrect. `bufio.NewReader` buffers input; that's why it exists. It will read all the available input into its buffer. In your `ReadUserInputSingleLine` function, you are creating a buffer, reading a single line from the buffer, and then discarding anything else that is in the buffer.
> 
> I have no particular reason to think that that is the problem here, but without a complete program it's hard to be sure.

Thanks for response. Just call `ReadUserInputSingleLine` function in `main` should work.

The problem is its behavior is inconsistent in multiple platforms, for ll platforms should be consistently 4096 bytes buffer. Also, buffer is NOT created on bufio package level, it is used in every `read` call. And the problem, from my POV, is the underlying syscall, instead of bufio.

If you think screenshot would be helpful, please let me know.

**Comment by ianlancetaylor** [comment]
The buffer is created by `bufio.NewReader`.  That's what the bufio package does.  Your program will behave incorrectly if multiple lines are available on `os.Stdin` when `ReadUserInputSingleLine` is called.

**Comment by kmahyyg** [comment]
Standalone program:

```
package main

import "REDACTED/utils"
import "fmt"

func main(){
        tokenizer, err := utils.ReadUserInputSingleLine("Tokenizer? ")
	if err != nil {
		panic(err)
	}
        fmt.Println(tokenizer)
}
```

Then I modified this `ReadUserInputSingleLine` to use `reader := bufio.NewReaderSize(os.Stdin, 1020)`, then input `AAAA(single "A" repeated 1024 times)` WITHOUT line break, then press enter, same thing still happened, and still `1023*"A"` will get a response from program.

Or to solve the problem in another way, which way do you think would be perfect for such kind of purpose?

**Comment by kmahyyg** [comment]
Even after I migrate to `io.ReadAll()` , it's still limited to 1024 bytes, is there any workaround (I believe problem might be on MacOS side)?

```
func ReadUserInputSingleLine(prompt string) (string, error) {
	fmt.Println(prompt)
	b, err := io.ReadAll(os.Stdin)
	if err != nil {
		log.Println(err)
	}
	lb_loc := bytes.Index(b, []byte("\n"))
	var text string
	if lb_loc != -1 {
		text = string(b)
	} else {
		text = string(b[:lb_loc])
	}
	return strings.TrimSpace(text), nil
}
```

Test case:

1. A single line with repeated 1024 times "A", no response from program. Delete last "A", press enter, everything works as normal.
2. A single line with repeated 512 times "A", repeated three times, means three lines of 512 repeated "A", program is working as normal.

So the limitation is on MacOS side, is it possible for any workaround?

**Comment by kmahyyg** [comment]
Problem is on tty driver, for MacOS users, try using pipe to solve this problem or add `STTY=-icanon` environment variable before you run your program. 

For more details, check:
- https://stackoverflow.com/questions/36990514/fgets-prompt-limited-to-1024-bytes
- https://unix.stackexchange.com/questions/204815/terminal-does-not-accept-pasted-or-typed-lines-of-more-than-1024-characters
- https://unix.stackexchange.com/questions/131105/how-to-read-over-4k-input-without-new-lines-on-a-terminal
