### ISSUE TITLE
x/pkgsite: golang source src net http should add HttpRequestToHttpsAddress. every version I add this func too tired

### ISSUE THREAD

**Issue by runsys** [golang/go#68833]
### What is the URL of the page with the issue?

none

### What is your user agent?

none

### What did you do?

only add "\r\nLocation: "+HttpRequestToHttpsAddress ++ "\r\n\r\n"
in http request to https server return message.
it is for no http server auto redirect to https.

### What did you see happen?

it can not auto redirect to https.

### What did you expect to see?

add up code

**Comment by runsys** [comment]
yes,it is there. none emoty change change to 302.

**Comment by bddjr** [comment]
https://github.com/bddjr/hlfhr
