### ISSUE TITLE
cmd/compile: differences in assembly between new(T) and &T{}

### ISSUE THREAD

**Issue by mariecurried** [golang/go#68845]
### Go version

go version devel go1.24-d36353499f Sat Aug 10 12:39:48 2024 +0000 linux/amd64

### What did you do?

I compiled the following program to check if there were any differences between `new(T)` and `&T{}`.
```go
package test

type T struct {
    x string
}

func f1() *T {
    return new(T)
}

func f2() *T {
    return &T{}
}
```

### What did you see happen?

In the case of `&T{}`, I noticed an extra instruction `MOVQ    $0, (AX)`.

When the struct is
```go
type T struct {
	x string
	y string
}
```
there is even another instruction `MOVQ	$0, 16(AX)`.

But when the struct is
```go
type T struct {
	x string
	y string
	z string
}
```
the differences go away.

Also, I noticed the two functions have a different cost to inline.
`f1`: `can inline f1 with cost 2 as: func() *T { return new(T) }`
`f2`: `can inline f2 with cost 3 as: func() *T { return &T{} }`

Lastly, both functions have stack handling code and I'm probably missing something, but from the assembly they don't seem to use the stack.

---

As an extra point of reference, the following functions produce different, but equivalent, assembly. The stack usage seems like it could be optimized, but that is another issue:
```go
package test

type T struct {
	x string
	y string
	z string
}

func f1() T {
	return *new(T)
}

func f2() T {
	return T{}
}
```

`f1`
```asm
MOVUPS	X15, command-line-arguments.~r0(SP)
MOVUPS	X15, command-line-arguments.~r0+16(SP)
MOVUPS	X15, command-line-arguments.~r0+32(SP)
MOVQ	command-line-arguments.~r0(SP), AX
MOVQ	command-line-arguments.~r0+16(SP), CX
MOVQ	command-line-arguments.~r0+32(SP), SI
XORL	BX, BX
MOVQ	BX, DI
MOVQ	BX, R8
```

`f2`
```asm
MOVUPS	X15, command-line-arguments.~r0(SP)
MOVUPS	X15, command-line-arguments.~r0+16(SP)
MOVUPS	X15, command-line-arguments.~r0+32(SP)
MOVQ	command-line-arguments.~r0(SP), AX
MOVQ	command-line-arguments.~r0+8(SP), BX
MOVQ	command-line-arguments.~r0+16(SP), CX
MOVQ	command-line-arguments.~r0+24(SP), DI
MOVQ	command-line-arguments.~r0+32(SP), SI
MOVQ	command-line-arguments.~r0+40(SP), R8
```

### What did you expect to see?

I expected both functions to be equivalent.

**Comment by randall77** [comment]
I have a fix for the unnecessary zeroing.

> Also, I noticed the two functions have a different cost to inline.

This is because at inlining time, `f1` has just `NEW` whereas `f2` has `PTRLIT` + `STRUCTLIT`, each of which has a cost of 1. Probably not worth fixing.

> Lastly, both functions have stack handling code and I'm probably missing something, but from the assembly they don't seem to use the stack.

They need stack handling because they call out to `runtime.newobject`, and thus need a full frame.

**Comment by mariecurried** [comment]
Thank you for the quick reply and the explanation on inlining/stack handling.

**Comment by valyala** [comment]
> This is because at inlining time, f1 has just NEW whereas f2 has PTRLIT + STRUCTLIT, each of which has a cost of 1. Probably not worth fixing.

IMHO, this should be fixed for the sake of consistency. People expect that `new(T)` and `&T{}` generate identical assembly code with identical inlining costs. If these statements generate different assembly code and/or have different inlining costs, then people start wasting their time on figuring out the most optimal statement. This isn't very productive task.
