### ISSUE TITLE
runtime/cgo: new pthread crash  _cgo_try_pthread_create

### ISSUE THREAD

**Issue by xuyinghao** [golang/go#68850]
### Go version

go version go1.20.4 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB="*"
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://mirrors.tools.huawei.com/goproxy/"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/mnt/data_disk/code/xyh/smartbench/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3335693688=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

cgo call

glibc version 

![image](https://github.com/user-attachments/assets/06221f24-7189-4d5b-b808-3e5330e45f1b)

### What did you see happen?

process crash

![image](https://github.com/user-attachments/assets/e3f39a18-1f21-4268-b5f7-597e77a26dfc)

### What did you expect to see?

This is a known issue of glibc. I hope go can fix it.
https://sourceware.org/bugzilla/show_bug.cgi?id=19951#c0

Workaround:
1. Because the execution of sub-threads cannot be stopped, the recommended method is to set the thread status to detached (interface function pthread_attr_setdetachstate) when creating sub-threads. Do not use the pthread_detach interface in the main thread.

2. You can call pthread_detach(pthread_self()) at the beginning of a subthread to set the detached state in the subthread.

**Comment by xuyinghao** [comment]
![image](https://github.com/user-attachments/assets/fd8563d9-d2a9-4bf4-8bb5-354af4736061)

**Comment by ianlancetaylor** [comment]
For text, please use plain text, not images.  Plain text is much easier to read.  Thanks.

**Comment by ianlancetaylor** [comment]
If I understand the glibc bug correctly, it only occurs after some thread has exited.  That is unusual in Go programs, in which threads typically never exit after they have been created.  Can you confirm that in your program some threads exit?  Thanks.

**Comment by And-ZJ** [comment]
Hello, excuse me, I'd like to ask, this question seems to exist in the lower version also, do you have a backport plan?

**Comment by ianlancetaylor** [comment]
@And-ZJ Although the change made sense by itself, I haven't seen any confirmation that it actually fixes a problem for anybody.  Do you have a test case where this change makes a difference?

**Comment by xuyinghao** [comment]
When will the release package be released to fix this problem? @ianlancetaylor

**Comment by ianlancetaylor** [comment]
@xuyinghao The change will be in the 1.24 release, which is scheduled for February, 2025.

We can probably backport the change to minor releases of 1.22 or 1.23, but as noted above we haven't seen a test case where it actually makes a difference.
