### ISSUE TITLE
Installation on Windows x64 in C:\Program Files\Go redirects to C:\Program Files (x86)\Go\ 

### ISSUE THREAD

**Issue by Zachdehooge** [golang/go#68876]
### What version of Go are you using (`go version`)?

<pre>
$ go version 
go version go1.23.0 windows/386
</pre>

### Does this issue reproduce with the latest release?
Yes, seems to be similar to #17602
### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=386
set GOBIN=
set GOCACHE=C:\Users\Zacha\AppData\Local\go-build
set GOENV=C:\Users\Zacha\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Zacha\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Zacha\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_386
set GOVCS=
set GOVERSION=go1.23.0
set GODEBUG=
set GOTELEMETRY=local
set GOTELEMETRYDIR=C:\Users\Zacha\AppData\Roaming\go\telemetry
set GCCGO=gccgo
set GO386=sse2
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m32 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\Zacha\AppData\Local\Temp\go-build3846588415=/tmp/go-build -gno-record-gcc-switches
gdb --version: GNU gdb (GDB) 11.2
</pre></details>

### What did you do?
Attempted to update the GO module to the new 1.23 using the Windows MSI updater

### What did you expect to see?
Expected it to overwrite the `Program Files` directory for Go

### What did you see instead?
installed to `Program Files (x86)` 

### Workaround
- After installation I deleted the directory for go in the `Program Files` directory and copied the newly installed module from `Program Files (x86)/GO` to `Program Files/GO` 
- Run `Go version` to validate

**Comment by dmitshur** [comment]
The `go version` output shows `windows/386`, but the issue title mentions "Windows x64". Is the problem that the Windows x86 installer (`go1.23.0.windows-386.msi`) was used instead of the Windows x86-64 installer (`go1.23.0.windows-amd64.msi`)?
