### ISSUE TITLE
x/pkgsite: package removal request for github.com/DataDog/datadog-cdk-constructs/dist/go/ddcdkconstruct

### ISSUE THREAD

**Issue by lym953** [golang/go#68874]
Hi,

I'm writing to request removal of the package [github.com/DataDog/datadog-cdk-constructs](https://github.com/DataDog/datadog-cdk-constructs)/dist/go/ddcdkconstruct from pkg.go.dev.

Reason:
After publishing this package, I figured out that it's better to move it to another GitHub repository, so I moved it to [github.com/DataDog/datadog-cdk-constructs-go](https://github.com/DataDog/datadog-cdk-constructs-go)/ddcdkconstruct. Now if we search for ddcdkconstruct, we see two results: 
<img width="893" alt="image" src="https://github.com/user-attachments/assets/a0ff8474-4c15-40ec-ba6b-6a78db4cdb1f">
and I want the old one to be removed to avoid confusion.

Thank you!

Yiming

**Comment by adonovan** [comment]
I have verified that the requestor (@lym953) is a recent frequent committer to this repo.

Please allow a few days for the configuration changes to take effect.

**Comment by lym953** [comment]
Awesome. Thank you Alan!
