### ISSUE TITLE
x/website: wrong command for installing the go for wsl linux distro

### ISSUE THREAD

**Issue by iamakhildabral** [golang/go#68890]
### What is the URL of the page with the issue?
 https://go.dev/doc/install >> linux
 
 
 
### What is your user agent?
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36

 
 
 
### Screenshot
 

 
![image](https://github.com/user-attachments/assets/bbab3cc1-cd0d-4c66-b7ce-c663290a0f48)

 
 
### What did you do?
 I tried ur command :
  rm -rf /usr/local/go && tar -C /usr/local -xzf go1.23.0.linux-amd64.tar.gz

 
 
 
### What did you expect to see?
 i expect a successful installation
 
 
### What did you see instead?
that my tar zip file not found later i saw a video on youtube 
https://www.youtube.com/watch?v=JgpLNj-Pnng&pp=ygUKZ28gb24gd3NsXA%3D%3D
where he show we need to use a sudo just in between your installation command  before tar :
 sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.23.0.linux-amd64.tar.gz

<img width="767" alt="Screenshot 2024-08-15 162631" src="https://github.com/user-attachments/assets/fbf86a34-7c65-4756-a533-1cf549c32f3f">

**Comment by seankhliao** [comment]
sudo is not a universal requirement
