### ISSUE TITLE
cmd/compile: error in Go 1.23.0 with generics, type aliases and indexing

### ISSUE THREAD

**Issue by phynes-sensiblecode** [golang/go#68903]
### Go version

go1.23.0

### Output of `go env` in your module/workspace:

```shell
Can be seen in Go Playground
```

### What did you do?

```
package main

import "fmt"

type A = map[string]interface{}

func m[T ~A](a interface{}) {
	fmt.Println(a.(T)["key"])
}

func main() {
	b := A{"key": "value"}
	m[A](b)
}
```

See: https://go.dev/play/p/cFkeJ6ppEBk

### What did you see happen?

This compiler error is seen on Go 1.23:
```
./prog.go:8:19: invalid operation: cannot index a.(T) (comma, ok expression of type T constrained by ~A)
```

The program compiles and runs as expected on Go 1.22.

If we move the type definition of `A` to a different package then the code runs fine in Go 1.23:
https://go.dev/play/p/l_x4F190M3y

### What did you expect to see?

There should be no compilation error.

**Comment by ianlancetaylor** [comment]
CC @griesemer @findleyr @timothy-king

**Comment by ianlancetaylor** [comment]
@gopherbot Please open a backport to the 1.23 release.

This appears to be a regression in the compiler.

**Comment by timothy-king** [comment]
Thank you for the report.

This looks like a bug in `(go/types._TypeSet).underIs` (and types2). This internal comment `// x == under(x) for ~x terms` is not true for Aliases. Needs more investigation.

You can get the 1.22 behavior by overriding the 1.23 default `GODEBUG=gotypesalias=0`.  https://go.dev/doc/godebug#default has instructions for different ways to change the default value.
