### ISSUE TITLE
net/http: support HTTP/2

### ISSUE THREAD

**Issue by mikioh** [golang/go#6891]
<pre>Just a thought, because it's a bit big and long-term stuff.

Hypertext Transfer Protocol version 2.0
<a href="http://tools.ietf.org/html/draft-ietf-httpbis-http2">http://tools.ietf.org/html/draft-ietf-httpbis-http2</a>

HPACK - Header Compression for HTTP/2.0
<a href="http://tools.ietf.org/html/draft-ietf-httpbis-header-compression">http://tools.ietf.org/html/draft-ietf-httpbis-header-compression</a>

Also it requires <a href="https://golang.org/issue/6736">issue #6736</a>.

Use cases would be the following:
- Server: 1.x, 2.0 and/or protocol agnostic
- Client: ditto
- Proxy (w/ traffic engineering): basic forward/reverse proxying, also traffic routing
and/or protocol bridging btw 1.x and 2.0
- QoX?: available to inject external queueing disciplines, frame scheduling and queue
management in between HTTP/2.0 framing and TLS layers
- Bearer: WebSocket over HTTP/2.0

Wow, I'm full.</pre>

**Comment by ncdc** [comment]
@bradfitz will there be a public API that will allow us to create streams and send data to/receive data from them?

**Comment by bradfitz** [comment]
Yes.

**Comment by ncdc** [comment]
Awesome, is there anything we can start playing around with yet? Or even a proposed API to review? :-)

**Comment by bradfitz** [comment]
Go look at https://github.com/bradfitz/http2 ... I'm already using it. Also note the open pull request that you'd be interested in.

**Comment by ncdc** [comment]
Are you referring to the Pushhandler PR? If so, I'm not sure that's exactly what I'm looking for. I'm hoping to be able to manage streams myself from the client and/or server side, passing data back and forth over each stream.

**Comment by bradfitz** [comment]
I'm happy with the state of HTTP/2 now. Closing this meta bug.

**Comment by ncdc** [comment]
@bradfitz I glanced quickly at the code but didn't see a way to hijack the connection and create my own streams. Is that possible yet?

**Comment by bradfitz** [comment]
@ncdc, we're not adding new API in Go 1.6. We can consider PUSH_PROMISE APIs in golang.org/x/net/http2 first, and only move things into the standard library when it's baked long enough in x/net. There were old proposals here:

https://github.com/bradfitz/http2/pull/23
https://github.com/bradfitz/http2/pull/34

But we no longer use that repo. Let's move this conversation to #13443
