### ISSUE TITLE
gcc_libinit.c:51: error: implicit declaration of function ‘__atomic_load_n’

### ISSUE THREAD

**Issue by octerye** [golang/go#68910]
### Go version

go1.23.0 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE='auto'
GOARCH='amd64'
GOBIN=''
GOCACHE='/root/.cache/go-build'
GOENV='/root/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/root/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/root/go'
GOPRIVATE=''
GOPROXY='https://goproxy.io,direct'
GOROOT='/usr/local/go1.23.0'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go1.23.0/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.23.0'
GODEBUG=''
GOTELEMETRY='local'
GOTELEMETRYDIR='/root/.config/go/telemetry'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD=''
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2131994557=/tmp/go-build'
```

### What did you do?

Case one:
go 1.23.0 or go 1.22.6
Linux  system kernel is Linux  2.6.32-754.33.1.el6.x86_64 
Release version  is CentOS release 6.5 (Final)
 Compilation  failure and Same error
 
 Case two:
 go 1.19
Linux system kernel is 2.6.32-754.33.1.el6.x86_64
Release version  is CentOS release 6.5 (Final)
 Compile successfully
 
  Case three:
  go 1.23.0 or go 1.22.6 or go1.19
  Linux  system kernel is 3.10.0-1062.el7.x86_64 
  Release version   CentOS Linux release 7.7.1908 (Core)
   Compile successfully
   
   Case four:
   go 1.23.0 or go 1.22.6 or go1.19
   Window 11
   Compile successfully
   
 The kernel version is within the support range of go, is this a compatibility issue?

### What did you see happen?

# runtime/cgo
cc1: warnings being treated as errors
gcc_libinit.c: In function ‘_cgo_wait_runtime_init_done’:
gcc_libinit.c:51: error: implicit declaration of function ‘__atomic_load_n’
gcc_libinit.c:51: error: ‘__ATOMIC_CONSUME’ undeclared (first use in this function)
gcc_libinit.c:51: error: (Each undeclared identifier is reported only once
gcc_libinit.c:51: error: for each function it appears in.)
gcc_libinit.c:78: error: implicit declaration of function ‘__atomic_store_n’
gcc_libinit.c:78: error: ‘__ATOMIC_RELEASE’ undeclared (first use in this function)
gcc_libinit.c: In function ‘x_cgo_notify_runtime_init_done’:
gcc_libinit.c:129: error: ‘__ATOMIC_RELEASE’ undeclared (first use in this function)
gcc_libinit.c: In function ‘x_cgo_set_context_function’:
gcc_libinit.c:137: error: ‘__ATOMIC_RELEASE’ undeclared (first use in this function)
gcc_libinit.c: In function ‘_cgo_get_context_function’:
gcc_libinit.c:142: error: ‘__ATOMIC_CONSUME’ undeclared (first use in this function)

### What did you expect to see?

Hopefully it will be compiled on go1.22 or 1.23 revisions

**Comment by cuonglm** [comment]
What is your gcc version?

**Comment by octerye** [comment]
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18)

**Comment by octerye** [comment]
> What is your gcc version?

gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18)

**Comment by octerye** [comment]
> What is your gcc version?

gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18)

**Comment by octerye** [comment]
1.19 will compile, I haven't tried go1.20 and go1.21 yet，Later I tried to compile go1.20 and go1.21。

**Comment by cuonglm** [comment]
> > What is your gcc version?
> 
> 
> 
> gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18)

Go requires gcc 4.6 or later.

https://go.dev/wiki/MinimumRequirements#cgo

**Comment by octerye** [comment]
go1.19 can compile, go1.20 after the compilation failed，Try upgrading your gcc version first。

**Comment by octerye** [comment]
GCC was upgraded to 5.2.1 by devtoolset, everything is compiling properly, thank you for your answers.
