### ISSUE TITLE
x/website: dark mode at top navbar instead at bottom

### ISSUE THREAD

**Issue by wasup-yash** [golang/go#68911]
### What is the URL of the page with the issue?

https://go.dev/blog/pprof 

### What is your user agent?

applicable to all ig 

### What did you do?

nil

### What did you see happen?

To enable dark mode as soon as I visit the page, reducing hassle.

### What did you expect to see?

Expected to enable dark mode from the top of the page instead of scrolling down to the bottom of the page. this created a hassle for the user to not be able to enable dark mode instantly as soon user visited the website. 
getting this fixed would enhance the UX and make it more user-friendly as the button is available right at the top so easily visible as soon as website is visited.

**Comment by ansaba** [comment]
cc: @jba

**Comment by hyangah** [comment]
I think the dark mode choice is sticky - so once you choose it, the choice is preserved next time you visit the sites.
Is it not the case? Or did you find yourself needing to toggle and choose different dark mode page-by-page due to suboptimal rendering of certain pages in dark/light mode?

**Comment by wasup-yash** [comment]
> I think the dark mode choice is sticky - so once you choose it, the choice is preserved next time you visit the sites, and you don't need to change the mode. Is it not the case? Or did you find yourself needing to toggle and choose different dark mode page-by-page due to suboptimal rendering of certain pages in dark/light mode?

Sorry for the late mention here of the info but regarding this ... I didn't mention anything regarding the preservation of the state i just mentioned that the button is at the bottom and if it is possible to put that at top of the navbar (which most sites do ) for the better UX then it would be good for the usability.
