### ISSUE TITLE
Lines of code should not be there on error page

### ISSUE THREAD

**Issue by pankajdahiya008** [golang/go#68921]
### What is the URL of the page with the issue?
 https://go.dev/doc/install/redirect/bit.ly
 
 
### What is your user agent?
 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15

 
 
 
### Screenshot
 
<img width="1768" alt="Screenshot 2024-08-17 at 11 28 40 AM" src="https://github.com/user-attachments/assets/e9e01611-92b2-41d0-9238-8fbbca08d837">

 
 
 
### What did you do?
 I appended the go install page url with /redirect/bit.ly and got error page but it also showed some code with it.

 
 
 
### What did you expect to see?
 Only error page and not lines of code.
 
 
### What did you see instead?

to, err := human()
open doc/install/redirect/bit.ly: file does not exist

**Comment by gophun** [comment]
It's a play on the proverb '[To err is human](https://en.wikipedia.org/wiki/To_err_is_human).' There are [Go-themed t-shirts](https://pbs.twimg.com/media/BqB3x1aCIAEcjnd?format=jpg) with this line. It's a joke, just some light-hearted fun.

**Comment by pankajdahiya008** [comment]
ok Thanks @gophun . Closing this ticket.
