### ISSUE TITLE
context: WithValue docs shouldn't say "return a copy"

### ISSUE THREAD

**Issue by deansg** [golang/go#68923]
### Go version

1.23.0

### Output of `go env` in your module/workspace:

```shell
N/A
```

### What did you do?

The documentation for context.Context#WithValue (as seen [here](https://pkg.go.dev/context#WithValue)) is misleading. It specifies "WithValue returns a copy of parent in which the value associated with key is val."

### What did you see happen?

In practice, "WithValue" doesn't return a copy of the parent, but rather returns a Context instance pointing to the original parent directly. This isn't mentioned explicitly, in contrast to "WithCancel"/"WithTimeout" where it is written in the intro section.

This means that repeatedly calling `WithValue` on a Context instance can lead to a memory leak even if it's the same single key that is being overriden (in fact, that is a real problem I experienced). Example snippet demonstration the problem:

```go
func doWork(ctx context.Context) {
    for {
        uuid := getSomeID()
        ctx = ctx.WithValue("id", uuid)
        ...
    }
}
```

I'm not sure if there is a reason to truly create a child context instead of a copy as described in the documentation, but either way probably either the documentation or the behavior should be changed.

### What did you expect to see?

Either the documentation clearly mentioning that WithValue also creates a child context (like it mentions for WithCancel), or changing the behavior so it will use a copy of the original context instead of directly pointing to it.

**Comment by cherrymui** [comment]
What memory leak do you see? You expect that after `ctx = ctx.WithValue("id", uuid)`, the original `ctx` can be garbage-collected?

Despite the top-level comment, the doc comment of `WithCancel`, as well as a few other functions, also says "returns a copy of parent". Semantically it is a copy in the sense that modifying the new context does not change the original one. The fact that it points to the old one seems an implementation detail. If we think "derived context" is clearer, maybe we want to change all of them?

**Comment by deansg** [comment]
@cherrymui exactly, the code snippet creates an infinite chain of Context instances, which aren't garbage collected at any point. It might be better to change some documentation of the other methods, even though for methods such as `WithCancel` it is mentioned that it's a child context in other sections of the `context` package documentation.
