### ISSUE TITLE
strings.Split of an empty string returns 1

### ISSUE THREAD

**Issue by lesichkovm** [golang/go#68925]
### Go version

1.23

### Output of `go env` in your module/workspace:

```shell
N/A
```

### What did you do?

Code at: https://go.dev/play/p/ULT5A-GXZmB

Same as in: https://github.com/golang/go/issues/54455

### What did you see happen?

A splitted empty string returns lenght of 1.

Same as: https://github.com/golang/go/issues/54455

### What did you expect to see?

An empty string split should return an empty array. Len should be 0

**Comment by randall77** [comment]
The spec of `strings.Split` says
```
// If s does not contain sep and sep is not empty, Split returns a
// slice of length 1 whose only element is s.
```
which I think covers this case. So this isn't a bug.

**Comment by lesichkovm** [comment]
@randall77 yes realized it has been left like this on purpose. Thanks
