### ISSUE TITLE
proposal: Ability to redirect type defintions (for templating languages)

### ISSUE THREAD

**Issue by harrisbisset** [golang/go#68924]
### Go Programming Experience

Intermediate

### Other Languages Experience

Python

### Related Idea

- [ ] Has this idea, or one like it, been proposed before?
- [ ] Does this affect error handling?
- [ ] Is this about generics?
- [ ] Is this change backward compatible? Breaking the Go 1 compatibility guarantee is a large cost and requires a large benefit

### Has this idea, or one like it, been proposed before?

No, I don't think so.

### Does this affect error handling?

No

### Is this about generics?

No

## Proposal
Ability to comment to redirect symbol defintion.

### Proposed Syntax
//go : indirect : {type} : {name}
This is just a suggestion, types other than **function** probably aren't required if there are complications.

### Example
main.go
```go
func main() {
  template := indexTemplate()
}
```

template.tmpl (templating language)
```go
//go:indirect:func:indexTemplate
func indexTemplate() string {
  <html>
    . . .
  </html>
}
```

template.go (generated go code from template.templ)
```go
func indexTemplate() string {
  return `<html>
                . . .
          </html> `
}
```

I am proposing a functionality to support a more developed templating system. This would satisfy the need and is the solution I thought of that may have the least changes required, as it only need to redirect the lsp (I believe).

### Informal Change

A way for your editor to redirect you to a templating language's defintion of a function.

### Is this change backward compatible?

Yes

### Would this change make Go easier or harder to learn, and why?

Only downside is potentially people being silly with it. E.g.

```go
func main() {
  t := test()
  b := best()
}

func test() {
  . . . 
}

//go:indirect:func:test
func best() {
  . . .
}
```

A solution to this is not allow it reference types in *.go files. Or just ignore it as what on earth is anyone using this for.
Otherwise, it's only implemented in templating languages.

### Cost Description

Makes code navigation more difficult if the end user implements it wrong.
Implementation difficulty (probably low).

### Changes to Go ToolChain

gopls

### Performance Costs

None (maybe makes code navigation very slightly slower if using this feature)

**Comment by seankhliao** [comment]
given that this comment only occurs in a non go templating language, I don't see anything for the go project to do.
