### ISSUE TITLE
cmd/go: "go env -changed" never include GOTELEMETRY

### ISSUE THREAD

**Issue by zigo101** [golang/go#68930]
### Go version

go version go1.23.0 linux/amd64

### Output of `go env` in your module/workspace:

```shell
.
```

### What did you do?

```
$ cat $HOME/.config/go/env
GOSUMDB=off
GOTELEMETRY=off
$ go env GOTELEMETRY
off
```

### What did you see happen?

```
$ go env -changed
GOSUMDB='off'
GCCGO='/usr/bin/gccgo'
```

### What did you expect to see?

```
$ go env -changed
GOSUMDB='off'
GOTELEMETRY=off
GCCGO='/usr/bin/gccgo'
```

**Comment by zigo101** [comment]
Maybe a little related to https://github.com/golang/go/issues/68928

**Comment by seankhliao** [comment]
see https://go.googlesource.com/go/+/d36353499f673c89a267a489beb80133a14a75f9/src/cmd/go/testdata/script/telemetry.txt#48
GOTELEMETRY is not set through an env var or GOENV, so -changed doesn't report it.

**Comment by zigo101** [comment]
But why `gp env" shows it?

**Comment by zigo101** [comment]
Please re-open this issue. If `gotv env GOTELEMETRY` works, then `go env -changed` should include `GOTELEMETRY`.

**Comment by ianlancetaylor** [comment]
At this point this seems the same as #68936.

**Comment by zigo101** [comment]
Continued at https://github.com/golang/go/issues/68960#issuecomment-2301180830
