### ISSUE TITLE
runtime: windows arm32 1.22 broken

### ISSUE THREAD

**Issue by wmjb** [golang/go#68996]
### Go version

1.22

commit https://github.com/golang/go/commit/4beb33018b35d3a68f0ce41bee10f56512d1696e breaks go building on windows arm32

### What did you do?

fixed it by putting back (accidentally?) removed line 238 in  src/runtime/sys_windows_arm.s
`	MOVW	$_INTERRUPT_TIME, R3`

### What did you see happen?

when using this fix https://github.com/golang/go/issues/68552#issuecomment-2302061027 and the fix to sys_windows_arm.s above, go now builds up to 1.23 and functions correctly for windows arm32.

### What did you expect to see?

all is well with go and with these fixes can be unmarked broken for windows arm32

**Comment by ianlancetaylor** [comment]
CC @golang/windows @qmuntal

**Comment by qmuntal** [comment]
Good catch, that line shouldn't have been removed. @wmjb do you want to send a CL with the fix? Else I can do it myself.

**Comment by wmjb** [comment]
> Good catch, that line shouldn't have been removed. @wmjb do you want to send a CL with the fix? Else I can do it myself.

can you take care of that. thank you.
