### ISSUE TITLE
x/vuln/cmd/govulncheck: TestCommand/main fail with Go tip since CL 596035

### ISSUE THREAD

**Issue by cherrymui** [golang/go#68998]
x/vuln's longtest builders started to fail consistently since (main repo's) [CL 596035](https://go.dev/cl/596035)

[https://ci.chromium.org/ui/p/golang/builders/ci/x_vuln-gotip-linux-amd64-longtest/b8738967372571184001/test-results](https://ci.chromium.org/ui/p/golang/builders/ci/x_vuln-gotip-linux-amd64-longtest/b8738967372571184001/test-results)

cc @golang/vulndb

**Comment by cherrymui** [comment]
cc @samthanawalla @matloob

**Comment by zpavlinovic** [comment]
I've created a CL for this: https://go-review.git.corp.google.com/c/vuln/+/605855

Just waiting for a review.

**Comment by cherrymui** [comment]
Thanks!
