### ISSUE TITLE
unique: panic when calling unique.Make with string casted as any

### ISSUE THREAD

**Issue by ALX99** [golang/go#68990]
### Go version

go version go1.23.0 linux/amd64

### Output of `go env` in your module/workspace:

```shell
O111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/dozy/.cache/go-build'
GOENV='/home/dozy/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/dozy/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/dozy/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/lib/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/lib/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.23.0'
GODEBUG=''
GOTELEMETRY='local'
GOTELEMETRYDIR='/home/dozy/.config/go/telemetry'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3823055494=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

Casting a string to `any` and passing it to `unique.Make` seems to cause issues.

```go
package main

import "unique"

func main() {
	unique.Make(any(""))
}
```

Example crash 1 `unexpected fault address 0x912c08`: https://go.dev/play/p/vZWwiXU6YXL
Example crash 2 `panic: interface conversion: interface {} is *unique.uniqueMap[string], not *unique.uniqueMap[interface {}]`: https://go.dev/play/p/U8JvXsqXpJQ

### What did you see happen?

For it not to crash

### What did you expect to see?

I expected to see nothing and the program not to crash

**Comment by ianlancetaylor** [comment]
CC @mknyszek

**Comment by mknyszek** [comment]
Looking into it.

**Comment by mknyszek** [comment]
I see the general problem -- it's a classic reflection mistake when trying to get the type of a value (via `TypeOf`). This package doesn't use reflection directly, but does something reflect-like to extract the type.

Easy fix, apologies for the breakage.

**Comment by mknyszek** [comment]
@gopherbot Please open a backport issue for Go 1.23.

This problem accidentally limits what types the `unique` package can work with, and results in panics. Also, the fix is very simple and low risk.

**Comment by ALX99** [comment]
Appreciate the insanely quick response.
Thank you for your contributions to Go!
