### ISSUE TITLE
proxy.golang.org: wrong version on @latest

### ISSUE THREAD

**Issue by dominik-przybyl-wttech** [golang/go#68991]
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/wttech/pulumi-aem/sdk

### What is your user agent?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36

### What did you do?

Some time age I released new version of https://github.com/wttech/pulumi-aem in version v0.1.2. And also retracted unused versions: from v0.9.0 to v0.9.99 and v0.0.1

### What did you see happen?

In https://pkg.go.dev/github.com/wttech/pulumi-aem/sdk we discover that version v0.9.34 is latest.
But from https://proxy.golang.org/github.com/wttech/pulumi-aem/sdk/@latest we discover that version v0.1.2 is latest, what is correct.

### What did you expect to see?

I exect in https://pkg.go.dev/github.com/wttech/pulumi-aem/sdk to see only version v0.1.1 and v0.1.2 (latest)

**Comment by seankhliao** [comment]
pkgsite is correct, using `go get` will also pull in v0.9.34 correctly.
retractions have to be at the highest versions to take effect.

**Comment by dominik-przybyl-wttech** [comment]
I've added retract when 0.1.2 was released, it was after v0.9.+ were released.
```
retract (
	[v0.9.0, v0.9.99]
	v0.0.1
)
```

so is there any approach to set v0.1.2 as a latest, and "remove" v0.9.+

**Comment by hyangah** [comment]
My understanding is that the retract info should be present in the last version's go.mod (including the retracted versions). (cc correct me if it's incorrect @matloob @samthanawalla ) The last version in the list is currently `v0.9.34`. Have you tried to tag the latest commit with `v0.9.35` (that is in `[v0.9.0, v0.9.99]` retract range) and publish it?

**Comment by dominik-przybyl-wttech** [comment]
I've added commit with `v0.9.35`, now on https://pkg.go.dev/github.com/wttech/pulumi-aem/sdk all entries are labeled as `Retracted`. I do not see `v0.1.1` and `v0.1.2`, which are visible here:
```
go list -m --versions -json github.com/wttech/pulumi-aem/sdk
{
        "Path": "github.com/wttech/pulumi-aem/sdk",
        "Version": "v0.1.2",
        "Versions": [
                "v0.1.1",
                "v0.1.2"
        ],
        "Time": "2024-06-17T15:00:00Z",
        "Dir": "/Users/dominik.przybyl/go/pkg/mod/github.com/wttech/pulumi-aem/sdk@v0.1.2",
        "GoMod": "/Users/dominik.przybyl/go/pkg/mod/cache/download/github.com/wttech/pulumi-aem/sdk/@v/v0.1.2.mod",
        "GoVersion": "1.21"
}
```
What should be done to make them appear in https://pkg.go.dev/github.com/wttech/pulumi-aem/sdk ?

**Comment by hyangah** [comment]
Looks like @dominik-przybyl-wttech published a new version and pkgsite processed the newly published version. However, v0.1.1 and v0.1.2 that were published while the module was excluded from pkgsite per #67209 and before the revert request #67847 was accepted were removed and pkgsite doesn't process them again. 

https://pkg.go.dev/github.com/wttech/pulumi-aem/sdk?tab=versions doesn't show v0.1.1 and v0.1.2.

I think this is a rare case - exclusion request and then revert the request. So, not worth investigating further.
