### ISSUE TITLE
x/website: Incorrect step to modify PATH environment variable

### ISSUE THREAD

**Issue by rootulp** [golang/go#69001]
### What is the URL of the page with the issue?

https://go.dev/doc/install
 
### What is your user agent?
 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36

### Screenshot
 
![Screenshot 2024-08-21 at 4 10 21 PM](https://github.com/user-attachments/assets/649e98cc-c7ae-45c1-ae6a-36bd2de86c89) 
 
### What did you do?
 
I copied this command and ran it on a Scaleway instance 
 
### What did you expect to see?
 
I expected all my Go binaries to be accessible via my PATH
 
 
### What did you see instead?

Instead the Go binaries I installed were not accessible via my PATH. The go binaries that I installed were saved to `/root/go/bin` so I had to modify my path via:

```
export PATH=$PATH:/root/go/bin
```

to access those binaries. Can this step be modified to account for cases where the Go `bin` directory is not at `/usr/local/go/bin`

**Comment by zigo101** [comment]
The Go install paths might differ because of different Linux distributions and user configurations. The doc just shows an example.

**Comment by seankhliao** [comment]
The installation is only about the go toolchain itself, any binaries you install may be in a different location, see #42823
