### ISSUE TITLE
x/exp/typeparams: TestAPIConsistency fail with Go tip since CL 575455

### ISSUE THREAD

**Issue by cherrymui** [golang/go#69000]
The x/exp repo started to fail consistently since [CL 575455](https://go.dev/cl/575455) (on the main repo). E.g.
[https://ci.chromium.org/ui/p/golang/builders/ci/x_exp-gotip-linux-amd64/b8738967462680113393/test-results](https://ci.chromium.org/ui/p/golang/builders/ci/x_exp-gotip-linux-amd64/b8738967462680113393/test-results)

```
=== RUN   TestAPIConsistency
    typeparams_test.go:39: "*TypeList.Types": got func()(Seq[Type]) at 1.18+, but  at 1.17
    typeparams_test.go:39: "*TypeParamList.TypeParams": got func()(Seq[*TypeParam]) at 1.18+, but  at 1.17
    typeparams_test.go:39: "*Union.Terms": got func()(Seq[*Term]) at 1.18+, but  at 1.17
--- FAIL: TestAPIConsistency (0.63s)
```

cc @adonovan @findleyr

**Comment by findleyr** [comment]
Thanks, I'll take a look.
