### ISSUE TITLE
Can not return nil on generic type which is an interface, is that a bug?

### ISSUE THREAD

**Issue by xujianjun2000** [golang/go#69011]
### Go version

go 1.22

### Output of `go env` in your module/workspace:

```shell
no special env, just about go language itself
```

### What did you do?

I have an interface definition, and a function using this interface in generic type as a return type: 
type **IAppender** interface {
    append()
}
func produceAppender\[T **IAppender**\]() T {
    return nil      _// compile err: Cannot use 'nil' as the type T_
}

------- but, below is working, why is that? what is the difference? ----------

func produceAppender\[T **IAppender**\]() **IAppender** {
    return nil      _//ok_
}

### What did you see happen?

return nil is not allowed by error: Cannot use 'nil' as the type T

### What did you expect to see?

can return a nil in the function

**Comment by seankhliao** [comment]
nil may not be a valid value for a type that satisfies the type constraints 

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
