### ISSUE TITLE
net/http/pprof: build tag to disable pprof

### ISSUE THREAD

**Issue by xnox** [golang/go#69030]
### Go version

go1.22

### Output of `go env` in your module/workspace:

```shell
Any
```

### What did you do?

Many projects enabel net/http/pprof, whilst useful in dev and staging/testing, it might be undesirable in production.

See for example https://github.com/search?q=org%3Aprometheus+net%2Fhttp%2Fpprof&type=code

### What did you see happen?

It would be neat to have a build tag, or godebug option to neutralise net/http/pprof such that it does nothing

### What did you expect to see?

Ability to neutralise net/http/pprof without patching code, but affecting toolchain (environment variables, go build tags, godebug setting)

**Comment by seankhliao** [comment]
Prometheus registers pprof on their own, it's up to them to disable it https://github.com/prometheus/prometheus/blob/main/web/web.go#L480

**Comment by xnox** [comment]
> Prometheus registers pprof on their own, it's up to them to disable it https://github.com/prometheus/prometheus/blob/main/web/web.go#L480

in that instance yes, in many other instances they do `_ "net/http/pprof" # comment out to disable` which sounds sub-optimal.
