### ISSUE TITLE
String Slice Doesn't Report the correct Length

### ISSUE THREAD

**Issue by singularian** [golang/go#69037]
### Go version

The application was built with the Go version: go1.23.0
I ran it on 
https://go.dev/tour/moretypes/11

### Output of `go env` in your module/workspace:

```shell
The application was built with the Go version: go1.23.0
```

### What did you do?

I ran the code on [](https://go.dev/tour/moretypes/11)

When I slice the string slice it still shows the same count and adds an empty item at the end if you do a range over the string slice. An int slice doesn't have that issue.

string len=7 cap=7 [1 2 3 4 5 6 ] - Bug
number 1
number 2
number 3
number 4
number 5
number 6
number    - Bug
int len=6 cap=6 [1 7 14 25 42 47]
int len=0 cap=6 []

```
package main

import "fmt"
import "strings"

func main() {
	var bug string = "1,1,2,3,4,5,6,"
	ss := strings.Split(bug, ",")
	ss = ss[1:]
	printSliceString(ss)
	
	for _, number := range ss {
	//  fmt::Println("number ", number)
	fmt.Printf("number %s\n", number)
	}

	s := []int{1, 7, 14, 25, 42, 47}
	printSlice(s)
	// Slice the slice to give it zero length.
	s = s[:0]
	printSlice(s)

	// Extend its length.
	s = s[:4]
	printSlice(s)

	// Drop its first two values.
	s = s[2:]
	printSlice(s)
}

func printSlice(s []int) {
	fmt.Printf("int len=%d cap=%d %v\n", len(s), cap(s), s)
}

func printSliceString(s []string) {
	fmt.Printf("string len=%d cap=%d %v\n", len(s), cap(s), s)
}
```

### What did you see happen?

The String Slice Reports Length 7 even though the length is 6
	var bug string = "1,1,2,3,4,5,6,"
	ss := strings.Split(bug, ",")
	ss = ss[1:]

string **len=7** cap=7 [1 2 3 4 5 6 ]

It's adding an empty item at the end

number 1
number 2
number 3
number 4
number 5
number 6
**number** 

The int slice doesn't have this issue
int len=6 cap=6 [1 7 14 25 42 47]
int len=0 cap=6 []
int len=4 cap=6 [1 7 14 25]
int len=2 cap=4 [14 25]

### What did you expect to see?

The String slice should give a length of 6 after the (ss = ss[1:]) removing of the first item. It shouldn't print an empty value in the range list

string len=6 cap=7 [1 2 3 4 5 6 ]

It's adding an empty item at the end

number 1
number 2
number 3
number 4
number 5
number 6

**Comment by seankhliao** [comment]
This is the expected behavior, please consult the docs for details.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
