### ISSUE TITLE
net/http: ServeMux not backwards compatible (with Go 1.21) when registering double-slash patterns

### ISSUE THREAD

**Issue by rivo** [golang/go#69044]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.23.0 darwin/arm64
</pre>

but the issue appears with go1.22 already, when [enhanced routing patterns](https://tip.golang.org/doc/go1.22#enhanced_routing_patterns) were introduced.

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

This has been confirmed on multiple architectures.

### What did you do?

I'm registering two `http.Handler`'s, one with the pattern `"/"` (one slash) and the other with the pattern `"//"` (two slashes). See the following example code:

https://go.dev/play/p/Gv6F8CMxant

Before go1.22, requesting a URI such as `/abc` would invoke the one-slash handler. Since go1.22, the same URI invokes the two-slash handler. In fact, due to [trailing-slash redirection](https://pkg.go.dev/net/http#hdr-Trailing_slash_redirection), now a request for `/abc` is redirected to `/abc/`, which did not happen in go1.21.

I realize that such a pattern (`"//"`) does not make much sense. And specifying `"GET //"` will lead to a panic. But nonetheless, this compatibility change broke our software when upgrading to go1.22. We'll be fine with a "won't fix" in any case but I thought it is relevant enough to open an issue for it. Maybe it will reveal other issues with the enhanced routing patterns.

(The following playground will follow the redirect and output `two slashes` (go1.22) instead of `one slash` (go1.21): https://go.dev/play/p/mmC95m4W4ko)

### What did you expect to see?

```
Running request...
200 OK
one slash
```

### What did you see instead?

```
Running request...
301 Moved Permanently
<a href="/test/">Moved Permanently</a>.
```

**Comment by cherrymui** [comment]
As you have read, https://go.dev/doc/go1.22#enhanced_routing_patterns mentions

> This change breaks backwards compatibility in small ways... The change is controlled by a [GODEBUG](https://go.dev/doc/godebug) field named httpmuxgo121. Set httpmuxgo121=1 to restore the old behavior.

Have you tried setting `GODEBUG=httpmuxgo121=1`?

cc @neild for whether this incompatibility is intended.

**Comment by rivo** [comment]
> Have you tried setting `GODEBUG=httpmuxgo121=1`?

Just tried that. Yes, it reverts it back to the pre go1.22 result. So I guess maybe this was intended? @cherrymui / @nild feel free to close this one if there's nothing unexpected here.

**Comment by AndrewHarrisSPU** [comment]
> I realize that such a pattern ("//") does not make much sense. And specifying "GET //" will lead to a panic. But nonetheless, this compatibility change broke our software when upgrading to go1.22. We'll be fine with a "won't fix" in any case but I thought it is relevant enough to open an issue for it. Maybe it will reveal other issues with the enhanced routing patterns.

Subtly I wonder if `"//"` does make sense with the `path` package's [cleaning rules](https://pkg.go.dev/path#Clean). There may be a slight inconsistency in how cleaning applies. Whether or not this is actionable for anything, I elect to throw my hands up - no clue!

A function [`parsePattern`](https://cs.opensource.google/go/go/+/master:src/net/http/pattern.go;drc=7b583fd1a1aeda98daa5a9d485b35786c031e941;l=84) is used for parsing, but not cleaning.

Specifically a comment suggests:
```
// An unclean path with a method that is not CONNECT can never match,
// because paths are cleaned before matching.
```

For registration, the serveMux method `Handle` immediately invokes methods `register`, and  [`registerErr`](https://cs.opensource.google/go/go/+/master:src/net/http/server.go;drc=206df8e7ad8a736b0dcbf5d98ab237b6784e5007;l=2801), without path cleaning. It calls `parsePattern` on the uncleaned path. Does this contradict a premise that only cleaned paths are parsed?

In contrast, for matching, the `ServeMux` method [`findHandler`](https://cs.opensource.google/go/go/+/master:src/net/http/server.go;drc=3b36d92c96436b9fcc2ee3b174edc369a598c163;l=2606) does invoke [`cleanPath`](https://cs.opensource.google/go/go/+/master:src/net/http/server.go;drc=3b36d92c96436b9fcc2ee3b174edc369a598c163;l=2524), and mostly follows path cleaning rules.

The [`"//"`](https://cs.opensource.google/go/go/+/master:src/net/http/pattern_test.go;drc=7b583fd1a1aeda98daa5a9d485b35786c031e941;l=86) and [`"GET //"`](https://cs.opensource.google/go/go/+/master:src/net/http/pattern_test.go;drc=7b583fd1a1aeda98daa5a9d485b35786c031e941;l=151) routes are specifically tested in `pattern_test.go`.

**Comment by jba** [comment]
@rivo This particular incompatibility wasn't intended, but is covered by the caveat that [Cherry quoted](https://github.com/golang/go/issues/69044#issuecomment-2307604830), and the GODEBUG setting is the right fix.

Closing as WAI.
