### ISSUE TITLE
cmd/go: document GORACE

### ISSUE THREAD

**Issue by WilliamColton** [golang/go#69090]
### Go version

go version go1.22.3 windows/amd64

### Output of `go env` in your module/workspace:

```shell
go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Administrator\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Administrator\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=E:/Programming/go/sdk/go1.22.3
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=E:\Programming\go\sdk\go1.22.3\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.22.3
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=E:\Programming\go\kite\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build482139038=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

run `go env`

### What did you see happen?

`GORACE` is not listed.

### What did you expect to see?

I expected to see the `GORACE` environment variable listed in the output when running the `go env` command after setting it using `go env -w GORACE="halt_on_error=1"`. This variable should be present along with other environment variables like `GOOS`, `GOARCH`, etc., and should reflect the value that was set.

**Comment by seankhliao** [comment]
GORACE is a runtime config setting for go programs, documented in the runtime package, see https://pkg.go.dev/runtime .

`go help environment` and `go env` are about settings which affect the go toolchain / compilation of go code.

Closing as out of scope.
