### ISSUE TITLE
time.ParseDuration day, week, month, year -> d, w, M, Y; helper code to ParseDuration

### ISSUE THREAD

**Issue by go-shafaq** [golang/go#69114]
I've simplified the code to make it easier to copy and use.
also same issue[/issues/17767#issue-187078548]

```go

// ParseDuration parses a duration string.
// examples: "10d", "-1.5w" or "3Y4M5d".
// Add time units are "d"="D", "w"="W", "M", "y"="Y".
func ParseDuration(s string) (time.Duration, error) {
	neg := false
	if len(s) > 0 && s[0] == '-' {
		neg = true
		s = s[1:]
	}

	re := regexp.MustCompile(`(\d*\.\d+|\d+)[^\d]*`)
	unitMap := map[string]time.Duration{
		"d": 24,
		"D": 24,
		"w": 7 * 24,
		"W": 7 * 24,
		"M": 30 * 24,
		"y": 365 * 24,
		"Y": 365 * 24,
	}

	strs := re.FindAllString(s, -1)
	var sumDur time.Duration
	for _, str := range strs {
		var _hours time.Duration
		for unit, hours := range unitMap {
			if strings.Contains(str, unit) {
				str = strings.ReplaceAll(str, unit, "h")
				_hours = hours
				break
			}
		}

		dur, err := time.ParseDuration(str)
		if err != nil {
			return 0, err
		}

		sumDur += dur * _hours
	}

	if neg {
		sumDur = -sumDur
	}
	return sumDur, nil
}

```

**Comment by ianlancetaylor** [comment]
Thanks, but we intentionally do not use any time unit larger than hour because they are ambiguous.  Days are sometimes 24 hours, sometimes 23 or 25 at daylight savings time transitions.  Similarly for the other larger units.

**Comment by timkuijsten** [comment]
I understand the reasoning, but it does look a bit unpractical when used with flag.Duration, i.e. with a 30 day default:
```sh
  -whiteexp duration
        duration before whitelists expire (default 720h0m0s)
```
From https://github.com/poolpOrg/filter-spfgreylist/pull/5

**Comment by go-shafaq** [comment]
> I understand the reasoning, but it does look a bit unpractical when used with flag.Duration, i.e. with a 30 day default:
> 
> ```shell
>   -whiteexp duration
>         duration before whitelists expire (default 720h0m0s)
> ```
> 
> From [poolpOrg/filter-spfgreylist#5](https://github.com/poolpOrg/filter-spfgreylist/pull/5)
> 
> Maybe we should adapt flag.Duration (not time.Duration) to parse days when used as input from the command line? Previous discussion: #11473

I didnt get you
I made my pkg github.com/go-shafaq/timep
what do you think

**Comment by timkuijsten** [comment]
> I didnt get you

Sorry, I was replying to ianlancetaylor.

> I made my pkg github.com/go-shafaq/timep
> what do you think

It's nice, although I would prefer to copy paste if it's just a little bit of code. For me just adding days and weeks would help with flags to command line tools and it's less ambiguous than the length of a month.

**Comment by go-shafaq** [comment]
> > I didnt get you
> 
> Sorry, I was replying to ianlancetaylor.
> 
> > I made my pkg github.com/go-shafaq/timep
> > what do you think
> 
> It's nice, although I would prefer to copy paste if it's just a little bit of code. For me just adding days and weeks would help with flags to command line tools and it's less ambiguous than the length of a month.

I just copied code from org time pkg and added some flexibility
