### ISSUE TITLE
import/path: go get gitlab private repo subgroup project  failed

### ISSUE THREAD

**Issue by Jerry-yz** [golang/go#69135]
### Go version

go version go1.22.5 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE='on'
GOARCH='amd64'
GOBIN='/home/xx/go/bin'
GOCACHE='/home/xx/.cache/go-build'
GOENV='/home/xx/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE='gitlab.cloud.xxx.cn'
GOMODCACHE='/home/xxx/gowork/pkg/mod'
GONOPROXY='gitlab.cloud.xxx.cn'
GONOSUMDB='gitlab.cloud.xxx.cn'
GOOS='linux'
GOPATH='/home/xx/gowork'
GOPRIVATE='gitlab.cloud.xxx.cn'
GOPROXY='http://goproxy.cn,direct'
GOROOT='/home/xx/go'
GOSUMDB='off'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/home/xx/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22.5'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='0'
GOMOD='/home/xx/work/es-service/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build486725730=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

i create a new project in subgroup, it can work to me; i want get old project, but it failed
go: gitlab.cloud.xxx.cn/server/ims2.0/ims_mirco/ims_system_tool@v1.0.0: invalid version: git ls-remote -q origin in /home/xx/gowork/pkg/mod/cache/vcs/ac45bee48248196e82ab60a65cd296578745f3519110bd77c6934d9c2d9b0c7b: exit status 128:
        remote: The project you were looking for could not be found or you don't have permission to view it.
        fatal: repository 'http://gitlab.cloud.xxxx.cn/server/ims2.0.git/' not found

### What did you see happen?

how to fix it

### What did you expect to see?

it should go get success?

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by Jerry-yz** [comment]
> Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.
> 
> For questions please refer to https://github.com/golang/go/wiki/Questions

ok, thanks
