### ISSUE TITLE
x/tools/gopls: ast.StructType has type other than types.StructType (no type?)

### ISSUE THREAD

**Issue by adonovan** [golang/go#69150]
This stack `iWGuoA` was [reported by telemetry](https://storage.googleapis.com/prod-telemetry-merged/2024-08-26.json):

xtools/gopls/internal/golang/hover.go:
```go
	if v, ok := obj.(*types.Var); ok && v.IsField() {
		// Find enclosing struct type.
		var tStruct *types.Struct
		for _, n := range path {
			if n, ok := n.(*ast.StructType); ok {
				tStruct = pkg.TypesInfo().TypeOf(n).(*types.Struct) // type assertion failed
				break
			}
		}
```
I think this must mean TypeOf returned nil (some other type for ast.StructType seems unlikely). If so, the underlying bug is in the type checker.

```
crash/crash
runtime.gopanic:+69
runtime.panicdottypeE:=275
runtime.panicdottypeI:+5
golang.org/x/tools/gopls/internal/golang.computeSizeOffsetInfo:+40
golang.org/x/tools/gopls/internal/golang.hover:+186
golang.org/x/tools/gopls/internal/golang.Hover:+4
golang.org/x/tools/gopls/internal/server.(*server).Hover:+30
golang.org/x/tools/gopls/internal/protocol.serverDispatch:+335
golang.org/x/tools/gopls/internal/lsprpc.(*streamServer).ServeStream.ServerHandler.func3:+5
golang.org/x/tools/gopls/internal/lsprpc.(*streamServer).ServeStream.handshaker.func4:+52
golang.org/x/tools/gopls/internal/protocol.Handlers.MustReplyHandler.func1:+2
golang.org/x/tools/gopls/internal/protocol.Handlers.AsyncHandler.func2.2:+3
runtime.goexit:+0
```
```
golang.org/x/tools/gopls@v0.16.1 go1.23.0 darwin/arm64 vscode (1)
```

Issue created by golang.org/x/tools/gopls/internal/telemetry/cmd/stacks.

**Comment by adonovan** [comment]
@timothy-king @griesemer

**Comment by adonovan** [comment]
@findleyr points out that this is likely a consequence of https://github.com/golang/go/issues/69092, which doesn't set the types for the inside of a CompositeLit. If the StructType happens to be within it, then we get the above crash.

See https://github.com/golang/go/issues/68918#issuecomment-2313326739, which anticipates the likely need for adding a number of workarounds for the same underlying cause as they show up.

**Comment by findleyr** [comment]
I'm not sure that's the only way to reach this crash, but it does seem like we can the known bug in CompositeLit type checking to write a test, and fix by making gopls more defensive.
