### ISSUE TITLE
iota alone on a single line leads to counter errors.

### ISSUE THREAD

**Issue by jlyzxt** [golang/go#69184]
### Go version

go1.23

### Output of `go env` in your module/workspace:

```shell
null
```

### What did you do?

i write code:
```go
const (
    n1 = 1 //1
    n2     //1
    n3     //1
    iota
    n4 = iota //0
    n5 = iota //1
)
```

### What did you see happen?

n4 = 0 and n5 =1

### What did you expect to see?

n4 should be 3 
n5 should be 4

**Comment by seankhliao** [comment]
your definition of iota shadows the global iota.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by zigo101** [comment]
How is it possible that "n4 = 0 and n5 =1"? It should always be "n4 = 0 and n5 =1".

More ref:

* https://github.com/golang/go/issues/49157
* https://go101.org/blog/2022-08-22-some-undocumented-changes-in-go-1.18-and-1.19.html

**Comment by ianlancetaylor** [comment]
I can't recreate your results.  What version of Go are you using?  Can you show us an example on the Go playground?

For example, this playground program https://go.dev/play/p/o3_SJ8P4Lhh prints `1` for every constant.
