### ISSUE TITLE
runtime: stack traces don't include the parent goroutine

### ISSUE THREAD

**Issue by myaaaaaaaaa** [golang/go#69190]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.23.0 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='~/.cache/go-build'
GOENV='~/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='~/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='~/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/lib/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/lib/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.23.0'
GODEBUG=''
GOTELEMETRY='on'
GOTELEMETRYDIR='~/.config/go/telemetry'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='0'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1345292236=/tmp/go-build -gno-record-gcc-switches'
uname -sr: Linux 6.10.7-arch1-1
/usr/lib/libc.so.6: GNU C Library (GNU libc) stable release version 2.40.
gdb --version: GNU gdb (GDB) 15.1
</pre></details>

### What did you do?

https://go.dev/play/p/gsJN7lxtR4-

### What did you see happen?

![1725135532](https://github.com/user-attachments/assets/e9a10ab8-19b5-4402-96b1-7300af6e05cb)

### What did you expect to see?

The `divideBy(0)` line is part of the stack trace

**Comment by seankhliao** [comment]
This is working as intended, goroutines don't really retain any parent-child relationship once started (`go` statement).

**Comment by ianlancetaylor** [comment]
That said, see `GODEBUG=tracebackancestors` at https://pkg.go.dev/runtime.
