### ISSUE TITLE
go/build: Build API

### ISSUE THREAD

**Issue by jingweno** [golang/go#6920]
<pre>Proposal: Add a build API for building Go program in go/build.

Context: `go build` and `go test` use an internal build API to build a Go program
(<a href="http://golang.org/src/cmd/go/build.go?#L359)">http://golang.org/src/cmd/go/build.go?#L359)</a>. It'd be nice that the API is available to
third party software as well. Google Group discussion is here
(<a href="https://groups.google.com/forum/#">https://groups.google.com/forum/#</a>!topic/golang-nuts/0FBoVbLyfkw).

Use Case: `gotask` (<a href="https://github.com/jingweno/gotask)">https://github.com/jingweno/gotask)</a> adopts similar approach as `go
test` to write and run task functions. Similar to how `go test` compiles and run test
functions, `gotask` compiles task functions on the fly and run them. The difference is
`go test` uses an internal build API (<a href="http://golang.org/src/cmd/go/build.go?#L359)">http://golang.org/src/cmd/go/build.go?#L359)</a> while
`gotask` uses the `go build` command. I'm wondering if it makes sense to add a new build
API for building Go program in go/build so that 3rd party software can make use of. 

Thanks,
Owen</pre>

**Comment by ALTree** [comment]
This is essentially #15108. This issue is older, but the other one has more discussion. Closing here.
