### ISSUE TITLE
x/playground: buttons Format and Share look disabled in dark theme

### ISSUE THREAD

**Issue by Deleplace** [golang/go#69215]
### Go version

1.23

### Output of `go env` in your module/workspace:

```shell
irrelevant in playground
```

### What did you do?

Visit https://go.dev/play/

### What did you see happen?

![image](https://github.com/user-attachments/assets/e892d733-6ca9-49b9-adbc-399b886092db)

### What did you expect to see?

I expected the two buttons Format, Share to have higher contrast colors, to show they are enabled.

The buttons do work properly:
- Format formats the code
- Share generates a permalink

It makes sense to have to button Run stand out as more prominent, as it is the most important button on the page, and the other buttons a bit less prominent. In light theme, there is no problem as all the buttons already look enabled. In dark theme, the colors are confusing and one may not use the buttons, thinking the features are not available.

**Comment by Deleplace** [comment]
Suggested fix for the buttons Format and Share:
- apply the same font color as the Run button

By keeping the same borders (bright border for Run, no border for Format and Share) we'll still have the Run button stand out more prominently.

**Comment by dmitshur** [comment]
CC @toothrot, @golang/tools-team.

**Comment by dmitshur** [comment]
Thanks for reporting this. From a quick look, this might actually be a bug that affects only the "auto" mode. I can reproduce your screenshot when the theme toggle is set to "auto":

<img width="366" alt="image" src="https://github.com/user-attachments/assets/814a5b22-ca9c-4868-a175-ce2aa76d9ef6">

But it looks different, likely as originally intended, when the theme toggle is set to "dark":

<img width="366" alt="image" src="https://github.com/user-attachments/assets/8c98a888-3882-4dcf-a4d2-bd2847917329">

So this probably just needs a fix to make the dark version of "auto" behave like the forced "dark" mode.

**Comment by Deleplace** [comment]
Good catch!

I can confirm "auto (dark)" is affected, while "dark" is not affected.

**Comment by Deleplace** [comment]
`--turq-bright` (`#00769c`) is being used instead of `--turq-med` (`#50b7e0`)

"turq-bright" may be a misnomer as it is rather dark, and has the same value as "turq-dark"

Regardless, we should make sure that rendering "auto (dark)" is always the same as rendering "dark"

**Comment by Deleplace** [comment]
Exact same problem with the "Popular Packages" links on the homepage go.dev : 

![image](https://github.com/user-attachments/assets/6b97b280-7b57-4861-b818-b49031700d1b)

They're too dark in "auto (dark)", while they look good in "dark".

Some styles are shared by the CSS classes `.Playground-button` and `.WhyGo-reasonLink`.
