### ISSUE TITLE
Boringcrypto (20240407) integration to gotool chain

### ISSUE THREAD

**Issue by Nagarjuna-jantali** [golang/go#69226]
### Proposal Details

Hi team,

The boring crypto version 20240407 - which is RSA and ECDSA 186-5 certified .
([Cryptographic Algorithm Validation Program | CSRC](https://csrc.nist.gov/projects/cryptographic-algorithm-validation-program/details?validation=37980))
When and to which release you are planning to integrate it go tool chain ?

Thanks,
Nagarjun

**Comment by seankhliao** [comment]
I believe it exists primarily for fips, see #62372

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
