### ISSUE TITLE
Updates to go.mod needed in a loop, even after go mod tidy is run

### ISSUE THREAD

**Issue by SamWhited** [golang/go#69228]
### Go version

go version go1.23.0 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/sam/.cache/go-build'
GOENV='/home/sam/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/sam/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/sam/go'
GOPRIVATE=''
GOPROXY='off'
GOROOT='/usr/lib/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/lib/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.23.0'
GODEBUG='goindex=0'
GOTELEMETRY='local'
GOTELEMETRYDIR='/home/sam/.config/go/telemetry'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/sam/Projects/mellium/xmpp/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1238908215=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

Tried to run my integration tests:

```
git clone git@codeberg.org:mellium/xmpp.git
cd xmpp
go test -v -tags "integration" -run Integration ...
```

Annoyingly, this only happens when running integration tests. This exact output happens after bumping the version in go.mod to 1.22 or 1.23, but a similar thing happens with the existing Go version (currently 1.18)

### What did you see happen?

$ go test -v -tags "integration" -run Integration ...
go: updates to go.mod needed; to update it:
        go mod tidy
$ go mod tidy
$ go test -v -tags "integration" -run Integration ...
go: updates to go.mod needed; to update it:
        go mod tidy

### What did you expect to see?

Tests run after running go mod tidy.

**EDIT:** everything appears to be working in CI, so maybe it's something to do with my setup or Arch specifically.

**Comment by seankhliao** [comment]
`...` targets every package in the dependency graph which, I assume this should have been `./...`

**Comment by SamWhited** [comment]
I stared at this for *ages* trying to figure out where in the world that dependency came from and what the difference between CI and local was; that's it. Thanks!
