### ISSUE TITLE
runtime: corrupted GoroutineProfile stack traces

### ISSUE THREAD

**Issue by felixge** [golang/go#69243]
A test case + fix for this issue is already submitted here: https://go-review.googlesource.com/c/go/+/609815

I'm opening this issue b/c it's a requirement for getting the fix back ported. cc @prattmic 

### Go version

go1.23.0

### What did you do?

Received a bug report that my fgprof library broke in go1.23: https://github.com/felixge/fgprof/issues/33

### What did you see happen?

Calling `runtime.GoroutineProfile()` repeatedly with the same input slice produced corrupted stack traces showing multiple `runtime.goexit` frames in the same stack trace.

![2024-09-04 CleanShot at 09 29 31](https://github.com/user-attachments/assets/9e11fdb8-393b-4ef3-a75d-6a045c7ef42c)

### What did you expect to see?

`runtime.goexit` should only show up in the root frame of the stack trace.

**Comment by cagedmantis** [comment]
Does the fix for #69335 need to be back-ported as well? It's part of the CL stack.
