### ISSUE TITLE
runtime: SIGSEGV: segmentation violation

### ISSUE THREAD

**Issue by Brhetty** [golang/go#69247]
### Go version

go version go1.22.3 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/root/.cache/go-build'
GOENV='/root/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/root/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/root/go'
GOPRIVATE=''
GOPROXY='https://goproxy.cn,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22.3'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='0'
GOMOD='/root/worker/zeus-detect/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build207762889=/tmp/go-build -gno-record-gcc-switches'
root@brhetty:~/worker/zeus-detect# go version
go version go1.22.3 linux/amd64
root@brhetty:~/worker/zeus-detect# go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/root/.cache/go-build'
GOENV='/root/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/root/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/root/go'
GOPRIVATE=''
GOPROXY='https://goproxy.cn,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22.3'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='0'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2208714169=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

none

### What did you see happen?

SIGSEGV: segmentation violation
PC=0x419877 m=31 sigcode=1 addr=0x20

goroutine 0 gp=0xc000782700 m=31 mp=0xc000801008 [idle]:
runtime.(*mspan).typePointersOfUnchecked(0xc204786000?, 0xc0ffa31140?)
	/usr/local/go/src/runtime/mbitmap_allocheaders.go:202 +0x37 fp=0xc00200be80 sp=0xc00200be60 pc=0x419877
runtime.scanobject(0x0?, 0xc000073268)
	/usr/local/go/src/runtime/mgcmark.go:1446 +0xb5 fp=0xc00200bf10 sp=0xc00200be80 pc=0x425215
runtime.gcDrain(0xc000073268, 0x3)
	/usr/local/go/src/runtime/mgcmark.go:1242 +0x1f4 fp=0xc00200bf78 sp=0xc00200bf10 pc=0x424b74
runtime.gcDrainMarkWorkerDedicated(...)
	/usr/local/go/src/runtime/mgcmark.go:1124
runtime.gcBgMarkWorker.func2()
	/usr/local/go/src/runtime/mgc.go:1387 +0xa5 fp=0xc00200bfc8 sp=0xc00200bf78 pc=0x4211e5
runtime.systemstack(0x25)
	/usr/local/go/src/runtime/asm_amd64.s:509 +0x4a fp=0xc00200bfd8 sp=0xc00200bfc8 pc=0x4762aa

### What did you expect to see?

none

**Comment by seankhliao** [comment]
how do we reproduce this?

**Comment by Brhetty** [comment]
> 我们如何重现这个现象？

I can't reproduce it

**Comment by Brhetty** [comment]
> how do we reproduce this?
SIGSEGV: segmentation violation
PC=0x42e882 m=9 sigcode=1 addr=0x64

goroutine 0 gp=0xc0006821c0 m=9 mp=0xc000680008 [idle]:
runtime.(*mheap).freeManual(0x27727e0, 0x0, 0x2)
	/usr/local/go/src/runtime/mheap.go:1584 +0x22 fp=0xc000693fa0 sp=0xc000693f78 pc=0x42e882
runtime.(*sweepLocked).sweep.func2()
	/usr/local/go/src/runtime/mgcsweep.go:798 +0x70 fp=0xc000693fc8 sp=0xc000693fa0 pc=0x42b790
runtime.systemstack(0x0)
	/usr/local/go/src/runtime/asm_amd64.s:509 +0x4a fp=0xc000693fd8 sp=0xc000693fc8 pc=0x4762aa

**Comment by hitzhangjie** [comment]
```bash
   SIGSEGV: segmentation violation
   PC=0x41b077 m=4 **sigcode=1 addr=0x20**

   goroutine 0 gp=0xc0000076c0 m=4 mp=0xc0000e5808 [idle]:
   runtime.(*mspan).typePointersOfUnchecked(0xc009115c80?, 0xc009115c80?)
                                                                                                                                                                          /data/home/user00/go/src/runtime/mbitmap_allocheaders.go:202 +0x37 fp=0x7faf1340dd48 sp=0x7faf1340dd28 pc=0x41b077                                              runtime.scanobject(0xc000080168?, 0xc000080168)                                                                                                                         /data/home/user00/go/src/runtime/mgcmark.go:1441 +0x1ce fp=0x7faf1340ddd8 sp=0x7faf1340dd48 pc=0x42706e                                                         runtime.gcDrain(0xc000080168, 0x3)                                                                                                                                      /data/home/user00/go/src/runtime/mgcmark.go:1242 +0x1f4 fp=0x7faf1340de40 sp=0x7faf1340ddd8 pc=0x4268b4                                                         runtime.gcDrainMarkWorkerDedicated(...)                                                                                                                                 /data/home/user00/go/src/runtime/mgcmark.go:1124                                                                                                                runtime.gcBgMarkWorker.func2()                                                                                                                                          /data/home/user00/go/src/runtime/mgc.go:1387 +0xa5 fp=0x7faf1340de90 sp=0x7faf1340de40 pc=0x422f25                                                              runtime.systemstack(0x800000)                                                                                                                                           /data/home/user00/go/src/runtime/asm_amd64.s:509 +0x4a fp=0x7faf1340dea0 sp=0x7faf1340de90 pc=0x47880a  
```

**Comment by ikamornikau** [comment]
> > how do we reproduce this?
> > SIGSEGV: segmentation violation
> > PC=0x42e882 m=9 sigcode=1 addr=0x64
> 
> goroutine 0 gp=0xc0006821c0 m=9 mp=0xc000680008 [idle]: runtime.(*mheap).freeManual(0x27727e0, 0x0, 0x2) /usr/local/go/src/runtime/mheap.go:1584 +0x22 fp=0xc000693fa0 sp=0xc000693f78 pc=0x42e882 runtime.(*sweepLocked).sweep.func2() /usr/local/go/src/runtime/mgcsweep.go:798 +0x70 fp=0xc000693fc8 sp=0xc000693fa0 pc=0x42b790 runtime.systemstack(0x0) /usr/local/go/src/runtime/asm_amd64.s:509 +0x4a fp=0xc000693fd8 sp=0xc000693fc8 pc=0x4762aa

@Brhetty did you manage to fix this? I have the same issue running go1.23.2
