### ISSUE TITLE
runtime: multi-arch build via qemu fails to exec go binary [1.23 backport]

### ISSUE THREAD

**Issue by prattmic** [golang/go#69259]
I am requesting issue #68976 to be considered for backport to the next 1.23 minor release.

We already had a backport (#68995) to make failure to start the telemetry subprocess non-fatal. Unfortunately we misunderstood the problem (thinking that telemetry was special), when the real problem here is that any use of `os.StartProcess` / `os/exec` is broken under QEMU user mode >= 7.2, <8.0.

FWIW, QEMU user mode is not a first class supported OS. As I understand it, only real Linux is first class. QEMU user mode is an alternative Linux implementation. There _is_ a workaround: use QEMU older than 7.2 or 8.0 or newer. That said, Debian bookworm has QEMU 7.2 in its apt repository, which I believe is why so many people are using such a narrow window of QEMU releases.

**Comment by aktau** [comment]
We've noticed the new check sometimes hanging in production. On this line:

```go
_, _, errno = Syscall6(SYS_WAITID, _P_PIDFD, uintptr(pidfd), 0, WEXITED, 0, 0)
```

For some reason, sometimes on QEMU the spawned process doesn't actually exit (or wait fails to return from a wait). I wonder if this has also been observed by others.

**Comment by tianon** [comment]
@aktau huh, I wonder if that's the same hang I was seeing in https://github.com/golang/go/issues/68976#issuecomment-2318267106 🤔

**Comment by aktau** [comment]
It's possible. Try sending a `SIGQUIT` if you see it again to see where it's stuck.

**Comment by mknyszek** [comment]
@prattmic just clarifying, should the upstream issue be closed, so the backport can continue? Is there any reason not to backport this? I moved this into "Waiting For Info" so we can figure out how to move forward. Thanks.

**Comment by prattmic** [comment]
Yes, the upstream bug was intended to be closed. This CL should still be backported.

With regards to https://github.com/golang/go/issues/69259#issuecomment-2376755781, that may be a Google-specific issue, but I've proactively sent https://go.dev/cl/617417 since the fix is semantically equivalent anyway. I think we should backport that CL as well.

**Comment by cherrymui** [comment]
Approved for backport.

**Comment by cherrymui** [comment]
CLs are submitted. Closing.
