### ISSUE TITLE
dist: go1.2.src.tar.gz does not contain godoc, or cover and vet go subcommands

### ISSUE THREAD

**Issue by davecheney** [golang/go#6927]
<pre>What steps will reproduce the problem?

Build an operating system distribution of Go 1.2 from the official source,
<a href="https://go.googlecode.com/files/go1.2.src.tar.gz">https://go.googlecode.com/files/go1.2.src.tar.gz</a>

What is the expected output? What do you see instead?

Comparing to the binary versions of Go available on the download website, building Go
from the supplied tarball produces an install which lacks godoc and the vet and cover
subcommands.

This cannot be corrected by the user as the distro packaged locations are owned by root.

Please use labels and text to provide additional information.

This has caused issues for downstream packaging folks as they do not use the misc/dist
tool, but expect the tarball to be complete.

<a href="https://bugs.launchpad.net/ubuntu/+source/golang/+bug/1259414">https://bugs.launchpad.net/ubuntu/+source/golang/+bug/1259414</a>

<a href="https://github.com/mxcl/homebrew/blob/master/Library/Formula/go.rb">https://github.com/mxcl/homebrew/blob/master/Library/Formula/go.rb</a>

^ note, relies on the fact that Go is installed in a user writeable directory

Could the Go 1.2 tarball be amended to include the additional source (misc/dist already
downloads and builds it) or the additional source published alongside the 1.2 tarball.</pre>

**Comment by adg** [comment]
I think we can close this now.
