### ISSUE TITLE
runtime: MutexProfile missing root frames in go1.23

### ISSUE THREAD

**Issue by felixge** [golang/go#69335]
### Go version

go1.23.1

### What did you do?

Print the stack traces of a `runtime.MutexProfile()` using the code below.

```go
package main

import (
	"fmt"
	"runtime"
	"sync"
	"time"
)

func main() {
	produceMutexContention()
	printMutexProfile()
}

func produceMutexContention() {
	runtime.SetMutexProfileFraction(1)
	var mu sync.Mutex
	done := make(chan struct{})
	defer close(done)
	for range runtime.GOMAXPROCS(-1) * 2 {
		go func() {
			for finish := false; !finish; {
				mu.Lock()
				select {
				case <-done:
					finish = true
				default:
					time.Sleep(time.Millisecond)
				}
				mu.Unlock()
			}
		}()
	}
	time.Sleep(time.Second)
}

func printMutexProfile() {
	var records []runtime.BlockProfileRecord
	for {
		n, ok := runtime.MutexProfile(records)
		if ok {
			records = records[:n]
			break
		}
		records = make([]runtime.BlockProfileRecord, n*2)
	}

	for _, r := range records {
		var funcs []string
		frames := runtime.CallersFrames(r.Stack())
		for {
			frame, more := frames.Next()
			funcs = append(funcs, frame.Function)
			if !more {
				break
			}
		}
		fmt.Printf("%#v\n", funcs)
	}
}
```

### What did you see happen?

go1.23.1 produces the following output:

```
[]string{"sync.(*Mutex).Unlock", "main.produceMutexContention.func1"}
[]string{""}
```

### What did you expect to see?

The same output as go1.22.7:

```
[]string{"sync.(*Mutex).Unlock", "main.produceMutexContention.func1", "runtime.goexit"}
[]string{"runtime._LostContendedRuntimeLock"}
```

### Additional Notes

This problem only happens when using the `runtime.MutexProfile` API. `runtime/pprof` output is not impacted.

I have submitted https://go-review.googlesource.com/c/go/+/611615 to fix this problem.

**Comment by timothy-king** [comment]
CC @golang/runtime, @mknyszek, @prattmic.

**Comment by mknyszek** [comment]
Ping @felixge @nsrip-dd re: @cagedmantis's question from [#69243](https://github.com/golang/go/issues/69243#issuecomment-2374741884). Does this need a backport as well? Thanks.

**Comment by nsrip-dd** [comment]
@mknyszek I'd say yes, since this bug causes mutex profiles obtained via `runtime.MutexProfile` to miss information, specifically `runtime._LostContendedRuntimeLock` records will have no stack.

**Comment by felixge** [comment]
@gopherbot Please backport to 1.23. This is a regression in mutex profiles with no workaround.

(not sure if this works, i might not have permissions)
