### ISSUE TITLE
encoding/json: Unmarshal of "null" string into map will panic after assignment (2)

### ISSUE THREAD

**Issue by ior308** [golang/go#69346]
### Go version

go version 1.21.11

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/root/.cache/go-build'
GOENV='/root/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/root/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/root/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/lib/golang'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='local'
GOTOOLDIR='/usr/lib/golang/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.11 (Red Hat 1.21.11-1.module+el8.10.0+90357+32bea22c)'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/usr/src/CARONTE.2.6.4/carontejs/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2364319159=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

I make a map
I unmarshal a string into map. string contains "null".

### What did you see happen?

unmarshal return no error and an empty map
when I use the map I get panic (nil assignement)

### What did you expect to see?

I expect unmarshal return error about malformed json string.  a string is a string. If I use "abc" string unmarshal return an error about JSON.

**Comment by seankhliao** [comment]
please include code to demonstrate the issue

**Comment by ior308** [comment]
package main

  import (
          "encoding/json"
          "fmt"
          "log"
          "time"
  )

>>func main() {

          JSON := "abc" // NO BUG, only JSON format error
          //JSON := "null" // BUG

          // Inizializza la mappa Synclist
          //
          myMap := make(map[string]time.Time)
          myMap["test"] = time.Now()

          fmt.Println("JSON: ", JSON)

          if err := json.Unmarshal([]byte(JSON), &myMap); err != nil {

                  log.Panic(err)

          }

          myMap["test"] = time.Now()

          fmt.Println(myMap["test"])

  }

**Comment by seankhliao** [comment]
`null` is a valid json value that can be represent a nonexistent object, different from invalid json like `abc` or an empty object like `{}`.

**Comment by ior308** [comment]
Yes, but if I pass a defined map, unmarshal shouldn't return a nil map... but rather a defined empty map.

**Comment by ianlancetaylor** [comment]
> Yes, but if I pass a defined map, unmarshal shouldn't return a nil map... but rather a defined empty map.

1. We could have done it that way, but I don't see why it is more correct.  In particular, it would make it impossible to distinguish a JSON `null` from a JSON `{}`.
2. In any case, we certainly can't change the behavior now.

**Comment by ior308** [comment]
Ok, thank you for your reply.
