### ISSUE TITLE
x/pkgsite: package removal request for github.com/ivandomanevsky/bank-app

### ISSUE THREAD

**Issue by fmkoIJoci903m** [golang/go#69347]
Hello, I would like to delete the package that is indexed on the site, but it has not been on github for a long time, thank you!

**Comment by adonovan** [comment]
We will first need to establish that this request comes from the authorized owner of the repository. Unfortunately that GitHub user account appears to have been deleted, which may make it challenging to prove that you had write access to the user account or its associated repos. Can you provide any evidence that you are the project maintainer?
