### ISSUE TITLE
x/pkgsite:

### ISSUE THREAD

**Issue by Amman30** [golang/go#69371]
### What is the URL of the page with the issue?
 https://github.com/Amman30/EnvPilot
 
 
### What is your user agent?
 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36

 
 
 
### Screenshot
 
<img width="1438" alt="Screenshot 2024-09-10 at 4 25 24 PM" src="https://github.com/user-attachments/assets/aee95e84-2892-4aa3-931f-9fc0b374792b">

 
 
<img width="901" alt="Screenshot 2024-09-10 at 4 28 20 PM" src="https://github.com/user-attachments/assets/a4470d7a-8381-4b2c-980f-e8710906a8f8">

 
### What did you do?
 
I uploaded my Go package, which includes the MIT License in the repository. However, the system does not detect the license.
 
 
### What did you expect to see?
 
 I expected the system to detect the MIT License, as it is correctly formatted and included in the repository.
 
### What did you see instead?

The page shows "License: None detected" instead of recognizing the MIT License that has been provided.

**Comment by seankhliao** [comment]
the version of v0.1.0 seen by the proxy did not contain a license file. rewriting the tag does not allow you to change the contents of a version the proxy has seen.

**Comment by Amman30** [comment]
Since rewriting the tag does not change the contents seen by the proxy, can you confirm if the version v0.1.0 is indeed cached by the proxy, or should I take additional steps to ensure the new version is correctly reflected?

**Comment by Amman30** [comment]
Thank you for your response. It appears the issue was related to a cached version of the package. I addressed this by making some changes and creating a new tag for the package. This approach resolved the problem effectively.
