### ISSUE TITLE
x/vuln: vulnerabilities missing (go-reform analysis result)

### ISSUE THREAD

**Issue by realchs** [golang/go#69392]
I have tested govulncheck on the latest version of go-reform (https://github.com/go-reform/reform)
reform uses "github.com/jackc/pgx@v3.6.2+incompatible" as a direct dependency and it has two security vulnerabilities as shown in https://deps.dev/go/gopkg.in%2Fjackc%2Fpgx.v3/v3.6.2. 
However, the vulnerabilities are no found in the report of govulncheck. Would you let me know why it does not report them?

**Comment by timothy-king** [comment]
CC @zpavlinovic, @golang/vulndb .

**Comment by realchs** [comment]
I've tested again and yes it works as expected 👍
