### ISSUE TITLE
x/telemetry/godev: sort go versions in x-axis

### ISSUE THREAD

**Issue by hyangah** [golang/go#69400]
<img width="1024" alt="Screenshot 2024-09-11 at 12 52 06 PM" src="https://github.com/user-attachments/assets/0f949096-b8bf-4eaa-8bc1-7be6d307b376">

See go1.2 is placed after go1.19.

I originally thought we should preserve the order in the graphconfig, but realized that we aggregate by the go major release (patch versions).

**Comment by timothy-king** [comment]
CC @golang/telemetry.

**Comment by findleyr** [comment]
Hmm, after deploying the CL above to dev, it appears not to have fixed the problem. Investigating.

**Comment by findleyr** [comment]
Nevermind: I reran the task before the deployment finished. Rerunning again, the sorting does indeed work (and now in prod as well).
