### ISSUE TITLE
cmd/link: the value stored in pcHeader in `runtime.firstmoduledata` is different from `runtime.pclntab` when using external links on `macOS arm64 cgo`

### ISSUE THREAD

**Issue by Zxilly** [golang/go#69428]
### Go version

go version devel go1.24-2a10a5351b Wed Aug 14 12:32:08 2024 +0800 windows/amd64

### Output of `go env` in your module/workspace:

```shell
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\zxilly\AppData\Local\go-build
set GOENV=C:\Users\zxilly\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\zxilly\go\pkg\mod
set GONOPROXY=1
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\zxilly\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=E:/Temp/go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=E:\Temp\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=devel go1.24-2a10a5351b Wed Aug 14 12:32:08 2024 +0800
set GODEBUG=
set GOTELEMETRY=local
set GOTELEMETRYDIR=C:\Users\zxilly\AppData\Roaming\go\telemetry
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\zxilly\AppData\Local\Temp\go-build119807883=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

I'm trying to extract the `moduledata.pcHeader` value from the binaries, and the integration test shows this error since go1.21 release.

Prior to go 1.21, the runtime.text symbol would still be present in the binary even if the -s flag was passed, masking the problem.

### What did you see happen?

the value stored in pcHeader in `runtime.firstmoduledata` is different from `runtime.pclntab` when using external links on `macOS arm64 cgo`

Can be reproduced with the following code:

```go
package main

import (
	"debug/macho"
	"encoding/binary"
	"fmt"
)

func main() {
	f, err := macho.Open("bin-darwin-1.23-arm64-cgo")
	if err != nil {
		panic(err)
	}

	pclntabAddr := uint64(0)
	moduledataAddr := uint64(0)

	for _, s := range f.Symtab.Syms {
		if s.Name == "runtime.firstmoduledata" {
			moduledataAddr = s.Value
		}
		if s.Name == "runtime.pclntab" {
			pclntabAddr = s.Value
		}
	}

	if moduledataAddr == 0 {
		panic("runtime.firstmoduledata not found")
	}
	if pclntabAddr == 0 {
		panic("runtime.pclntab not found")
	}

	// read first 8 bytes of runtime.moduledata
	data := make([]byte, 8)
	for _, prog := range f.Sections {
		if prog.Addr <= moduledataAddr && moduledataAddr+8-1 <= prog.Addr+prog.Size {
			if _, err := prog.ReadAt(data, int64(moduledataAddr-prog.Addr)); err != nil {
				panic(err)
			}
			break
		}
	}

	// transfer the pclntabAddr to a byte array, little endian
	pclntabAddrBinary := make([]byte, 8)
	binary.LittleEndian.PutUint64(pclntabAddrBinary, pclntabAddr)

	fmt.Println("runtime.firstmoduledata.pcHeader ptr:")
	for _, b := range pclntabAddrBinary {
		fmt.Printf("%02x ", b)
	}
	fmt.Println()
	// print the first 8 bytes of runtime.pclntab as hex
	fmt.Println("runtime.pclntab:")
	for _, b := range data {
		fmt.Printf("%02x ", b)
	}
	fmt.Println()
}
```

Will results to

```bash
runtime.firstmoduledata.pcHeader ptr:
40 26 2a 00 01 00 00 00 
runtime.pclntab:
40 26 2a 00 00 00 10 00 
```

Some scripts indicates similiar problem on most recent major Go releases:

```
// format
// pclntab addr value
// generate search hash
// real value in the binary

19
pclntabAddr 4295817152
c0 f7 0c 00 01 00 00 00 
c0 f7 0c 00 00 00 10 00

20
pclntabAddr 4295805984
20 cc 0c 00 01 00 00 00 
20 cc 0c 00 00 00 10 00

21
pclntabAddr 4298061728
a0 37 2f 00 01 00 00 00 
a0 37 2f 00 00 00 10 00

22
mdAddr 4298416864 mdSect __noptrdata off 6112
pclntabAddr 4297689728
80 8a 29 00 01 00 00 00 
80 8a 29 00 00 00 10 00

23
pclntabAddr 4297729600
40 26 2a 00 01 00 00 00 
40 26 2a 00 00 00 10 00
```

This only happens on `macOS arm64` with external link.

Here's some binary as input:

https://github.com/Zxilly/go-testdata/releases/download/latest/bin-linux-1.22-arm64-strip-cgo
https://github.com/Zxilly/go-testdata/releases/download/latest/bin-linux-1.22-arm64-strip-pie-cgo
https://github.com/Zxilly/go-testdata/releases/download/latest/bin-linux-1.23-arm64-strip-cgo
https://github.com/Zxilly/go-testdata/releases/download/latest/bin-linux-1.23-arm64-strip-pie-cgo

### What did you expect to see?

These value should keep same as other arch.

**Comment by Zxilly** [comment]
This is an advisory issue rather than a bug, as it doesn't seem to affect the operation of the Go binary.

**Comment by ianlancetaylor** [comment]
CC @cherrymui @golang/runtime

**Comment by cherrymui** [comment]
I think the moduledata references pcheader with a dynamic relocation (or the equivalent on Mach-O, a "bind" or "rebase" entry). The data you read directly from moduledata is without the relocation applied. You'll need to decode and apply the relocation.

It is possible that the Go linker and C linker (or even different versions of the C linker) use different relocation mechanism, and the pre-relocated data may or may not be meaningful. They are semantically equivalent so at program run time it always point to the right data.

I'm not sure if there is anything we can do.

**Comment by Zxilly** [comment]
If that's the reason, I'm wondering why buildmode being exe or pie doesn't change this behaviour. I looked up some other issues, is it because Apple doesn't support generating non-pie binaries anymore either?
Similarly, this behaviour is not observed on amd64.

**Comment by cherrymui** [comment]
>  is it because Apple doesn't support generating non-pie binaries anymore either?

That is correct.

Again, the un-relocated data varies depending on architecture, link mode, linker version, etc.. It may happen to be useful, or not.

**Comment by Zxilly** [comment]
I investigated the issue further and it doesn't seem to be a relocation issue, please check the attached image, the corresponding sections for `moduledata` and `pclntab` all have Nreloc of 0

![image](https://github.com/user-attachments/assets/1adc3083-2bfb-4d9f-b9e9-dacc68eedeb5)

![image](https://github.com/user-attachments/assets/d372034e-3108-4072-8af0-b0c2a06adf50)

**Comment by cherrymui** [comment]
Mach-O doesn't use relocations in that sense. They have "rebase" and "bind" tables instead. Try `objdump --macho --bind` and `objdump --macho --rebase` with the macOS system objdump (from Xcode).

**Comment by cherrymui** [comment]
For a binary I built, I have
```
$ nm x | grep firstmoduledata
00000001000f7b00 s _runtime.firstmoduledata
$ nm x | grep runtime.pclntab
000000010009f820 s _runtime.pclntab
$ objdump -m --rebase ./x | grep 0x1000F7B00
...
__DATA   __noptrdata        0x1000F7B00  rebase ptr   0x10009F820
```
The rebase entry does point to the right address.

As you mentioned above, this is not a bug. And I don't think there is much we can do. Thanks.

**Comment by Zxilly** [comment]
Thanks for the suggestion, I tried `llvm-objdump --macho --bind` and `llvm-objdump --macho --rebase` on my samples and it seems that the rebase table does not exist in these files, but the address discrepancy is still there.
Specifically, I am referring to the file 

https://github.com/Zxilly/go-testdata/releases/download/latest/bin-darwin-1.23-arm64-strip-pie-cgo

Can you please suggest me some other directions?

I got

```
PS T:\> llvm-objdump --macho --rebase .\bin-darwin-1.23-arm64-strip-pie-cgo
.\bin-darwin-1.23-arm64-strip-pie-cgo:

Rebase table:
segment  section            address     type
PS T:\> llvm-objdump --macho --bind .\bin-darwin-1.23-arm64-strip-pie-cgo
.\bin-darwin-1.23-arm64-strip-pie-cgo:

Bind table:
segment  section            address    type       addend dylib            symbol
```

on this file.

**Comment by Zxilly** [comment]
I guess it was related to `Chained Fixups`

**Comment by cherrymui** [comment]
You're probably right that chained fixups are related. That is yet another way of expressing dynamic relocations in Mach-O.
