### ISSUE TITLE
x/pkgsite: package removal request for github.com/jeaguil/forgotten-fields and github.com/jeaguil/piefai/cmd

### ISSUE THREAD

**Issue by jeaguil** [golang/go#69450]
### What is the path of the package that you would like to have removed?

github.com/jeaguil/

### Are you the owner of this package?

Yes, to both github.com/jeaguil/forgotten-fields and github.com/jeaguil/piefai/cmd

### What is the reason that you could not retract this package instead?

github.com/jeaguil/piefai/cmd has been deleted and github.com/jeaguil/forgotten-fields was accidentally published as a pkg

**Comment by adonovan** [comment]
I have confirmed that your GitHub ID matches the repo owner and made the change. Please allow a few days for the configuration change to take effect.
