### ISSUE TITLE
wiki: Add Hogosuru to the list of webassembly framework available in GO

### ISSUE THREAD

**Issue by realPy** [golang/go#69471]
Hi all,

I'm the author of hogosuru framework: 

https://github.com/realPy/hogosuru

Would it be possible to add it to the list of frameworks available here:

https://go.dev/wiki/WebAssembly in the "Interacting with the DOM" section.

It would be a shame to miss it.

Just published a new example : an jwt online decoder written with few lines of code:

https://github.com/realPy/hogosuru-jwtdecoder
You can also test it with github pages here :

https://realpy.github.io/hogosuru-jwtdecoder/index.html

Thanks you ! 🙏

**Comment by Zxilly** [comment]
You can send a PR to https://github.com/golang/wiki

**Comment by realPy** [comment]
Hi @Zxilly done here https://github.com/golang/wiki/pull/26

Thank for the suggest.
