### ISSUE TITLE
access: may-start-trybots for @cpu

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#69489]
@cpu is working with me and Roland on the cryptographic packages, it would be useful for him to have `may-start-trybots` on the daniel@binaryparadox.net Gerrit account.

See https://go.dev/wiki/GerritAccess

**Comment by cagedmantis** [comment]
Hi Filippo (on behalf of Daniel @cpu),

Thank you for committing to contribute, and for requesting trybot access! I've added you to the may-start-trybots group, so you should be able to do so now.

As you've probably seen at https://go.dev/wiki/GerritAccess#trybot-access-may-start-trybots, please be sure to skim CLs before starting a trybot run.

Let us know if you have any questions or issues with it, and thanks again!

**Comment by cpu** [comment]
Great, thank you!
