### ISSUE TITLE
log/slog: slog writes nil map as "map[]", not "nil"

### ISSUE THREAD

**Issue by fedulovivan** [golang/go#69496]
### Go version

go version go1.22.5 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
```

### What did you do?

package main
import "log/slog"
func main() {
	var value map[string]string = nil
	slog.Error("message", "value", value)
}

### What did you see happen?

2009/11/10 23:00:00 ERROR message value=map[]

### What did you expect to see?

2009/11/10 23:00:00 ERROR message value=nil

**Comment by seankhliao** [comment]
fmt does the same https://go.dev/play/p/MAaylMZGDeN

**Comment by fedulovivan** [comment]
Сannot understand why fmt is used as reference here. As for me it would be convenient to distinquish between empty and non-initialised maps. Current approach leads to confusion.

**Comment by seankhliao** [comment]
from the docs: 
> Otherwise, the result of fmt.Sprint is written.
