### ISSUE TITLE
x/website: barely visible image in dark theme

### ISSUE THREAD

**Issue by alexandear** [golang/go#69517]
### What did you do?

1. Set the dark appearance in macOS.
2. Open the blog post https://go.dev/blog/llmpowered in the latest Chrome browser.

### What did you see happen?

The RAG diagram is barely visible due to the transparent background:
<img width="855" alt="image" src="https://github.com/user-attachments/assets/b5e7b7ed-d943-4413-932e-a28a776ab574">

### What did you expect to see?

The RAG diagram image has a background. Something like this:
![image](https://github.com/user-attachments/assets/74642302-8f6e-4802-a759-a4bce76934bf)

**Comment by cagedmantis** [comment]
cc [@golang/tools-team](https://github.com/orgs/golang/teams/tools-team)
