### ISSUE TITLE
spec: value in assignability should be replaces with expression

### ISSUE THREAD

**Issue by TutiFrouti** [golang/go#69522]
### What is the URL of the page with the issue?

https://go.dev/ref/spec#Assignability

### What is your user agent?

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36

### What did you do?

Specification for assignability states (I bolded myself):

> A **value x of type V** is assignable to a [variable](https://go.dev/ref/spec#Variables) of type T ("x is assignable to T") if one of the following conditions applies

I think the term "value" used here is wrong and should be replaces with the term "expression".

### What did you see happen?

Each type in golang defines value set, that is, it defines set of values that belongs to that type.

Consider three types:

```
type A []int8
type B []int8
type C = []int8
```

Two named `A` and `B` types and one unnamed `C` type share the exactly same value set. It is the set of all slices of 8-bit integers. Thus, some slice of 8-bit integers at the same time belongs to the value set of all these three types. Value is just value, it doesn't have type. Expressions have a type.

In the following example the problem is not about the type of the value. Value is just value (`[]int8{10, 20}`) and it belongs to the value set of both, `A` and `B` types (and unnamed `[]int8` type). The problem is distinction of the types between variable on the left and expression on the right side of the `=`. So the conversion has to be done not to change anything about the value (it stays as it is; it is the exactly same slice value belonging to the value set of both types), but to align the types of new variable and expression (since expressions have types).

```
package main

type A []int8
type B []int8

func main() {
	var a A = []int8{10, 20}
	var _ B = B(a)
}
```

### What did you expect to see?

I expect the modification of the specification.

That is, to change the following:

> A value x of type V is assignable to a [variable](https://go.dev/ref/spec#Variables) of type T ("x is assignable to T") if one of the following conditions applies

to:

> An expression x of type V is assignable to a [variable](https://go.dev/ref/spec#Variables) of type T ("x is assignable to T") if one of the following conditions applies

**Comment by ianlancetaylor** [comment]
The spec uses the word "value" all over the place.  For example, https://go.dev/ref/spec#Variables says

> A variable is a storage location for holding a value. The set of permissible values is determined by the variable's type.

We aren't going to change all or most of those uses of "value" to say "expression."
