### ISSUE TITLE
access: go-editors for firelizzard18

### ISSUE THREAD

**Issue by hyangah** [golang/go#69541]
Per https://go.dev/wiki/GitHubAccess I am proposing to add @firelizzard18  to https://github.com/orgs/golang/teams/go-editors group.

He is working on the new version of the test explorer UI for the vscode-go project, and needs the permission to triage/organize related issues.

Thanks.

cc @golang/release

**Comment by mknyszek** [comment]
Approved. Sorry for the delay. Thanks @firelizzard18 for your current and future contributions! You should have received an invitation by email to join the group.
