### ISSUE TITLE
gccgo: netpoll_select.c spins on select(2)

### ISSUE THREAD

**Issue by davecheney** [golang/go#6955]
<pre>What steps will reproduce the problem?

During our solaris port we reused the gccgo netpoll_select.c. We've recently discovered
that when the netpoller is running it will loop continually on select(2)

I've reproduced the problem on linux by replacing the epoll system with select (see diff
at the bottom of the issue) and reproduced the problem.

What is the expected output? What do you see instead?

lucky(~/src) % more bug.go 
package main

import &quot;net&quot;
import &quot;time&quot;

func main() {
        net.Dial(&quot;tcp&quot;, &quot;www.google.com:80&quot;) // don't care about result, just start poller
        time.Sleep(time.Minute)
}

lucky(~/src) % gccgo bug.go
lucky(~/src) % time ./a.out

real    1m0.091s
user    0m20.851s
sys     0m39.159s

We traced this to poller continually retrying the operation. 

Please use labels and text to provide additional information.

Index: ../devel/gcc/trunk/libgo/Makefile.am
===================================================================
--- ../devel/gcc/trunk/libgo/Makefile.am        (revision 205993)
+++ ../devel/gcc/trunk/libgo/Makefile.am        (working copy)
@@ -413,7 +413,7 @@
 endif
 
 if LIBGO_IS_LINUX
-runtime_netpoll_files = runtime/netpoll_epoll.c
+runtime_netpoll_files = runtime/netpoll_select.c
 else
 if LIBGO_IS_SOLARIS
 runtime_netpoll_files = runtime/netpoll_select.c
Index: ../devel/gcc/trunk/libgo/Makefile.in
===================================================================
--- ../devel/gcc/trunk/libgo/Makefile.in        (revision 205993)
+++ ../devel/gcc/trunk/libgo/Makefile.in        (working copy)
@@ -181,7 +181,7 @@
 @HAVE_SYS_MMAN_H_TRUE@am__objects_2 = mem.lo
 @LIBGO_IS_LINUX_FALSE@@LIBGO_IS_SOLARIS_FALSE@am__objects_3 = netpoll_kqueue.lo
 @LIBGO_IS_LINUX_FALSE@@LIBGO_IS_SOLARIS_TRUE@am__objects_3 = netpoll_select.lo
-@LIBGO_IS_LINUX_TRUE@am__objects_3 = netpoll_epoll.lo
+@LIBGO_IS_LINUX_TRUE@am__objects_3 = netpoll_select.lo
 @LIBGO_IS_RTEMS_TRUE@am__objects_4 = rtems-task-variable-add.lo
 @LIBGO_IS_DARWIN_FALSE@@LIBGO_IS_FREEBSD_FALSE@@LIBGO_IS_IRIX_FALSE@@LIBGO_IS_LINUX_FALSE@@LIBGO_IS_NETBSD_FALSE@@LIBGO_IS_SOLARIS_FALSE@am__objects_5 = getncpu-none.lo
 @LIBGO_IS_DARWIN_FALSE@@LIBGO_IS_FREEBSD_FALSE@@LIBGO_IS_IRIX_FALSE@@LIBGO_IS_LINUX_FALSE@@LIBGO_IS_NETBSD_TRUE@@LIBGO_IS_SOLARIS_FALSE@am__objects_5 = getncpu-bsd.lo
@@ -752,7 +752,7 @@
 @LIBGO_IS_LINUX_TRUE@runtime_getncpu_file = runtime/getncpu-linux.c
 @LIBGO_IS_LINUX_FALSE@@LIBGO_IS_SOLARIS_FALSE@runtime_netpoll_files = runtime/netpoll_kqueue.c
 @LIBGO_IS_LINUX_FALSE@@LIBGO_IS_SOLARIS_TRUE@runtime_netpoll_files = runtime/netpoll_select.c
-@LIBGO_IS_LINUX_TRUE@runtime_netpoll_files = runtime/netpoll_epoll.c
+@LIBGO_IS_LINUX_TRUE@runtime_netpoll_files = runtime/netpoll_select.c
 runtime_files = \
        runtime/go-append.c \
        runtime/go-assert.c \</pre>

**Comment by ianlancetaylor** [comment]
We no longer use netpoll_select.
