### ISSUE TITLE
Wrong URL in code snippet

### ISSUE THREAD

**Issue by dave1526** [golang/go#69550]
One line of the example code is obsolete here:
https://go.dev/doc/effective_go#web_server
 
This line refers to an API decommissioned long ago:
`<img src="http://chart.apis.google.com/chart?chs=300x300&cht=qr&choe=UTF-8&chl={{.}}" />`
 
The code would work if changed to this e.g.;
`<img src="https://quickchart.io/qr?text={{.}}" />`

**Comment by seankhliao** [comment]
I don't think it's wise to link to another third party website.
