### ISSUE TITLE
crypto/rand: use new Linux vDSO

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#69577]
In Linux 6.11 @zx2c4 introduced a vDSO for the random number generator, which avoids the system call overhead of calling `getrandom`, similarly to how `arc4random()` works on the BSDs. The motivation is explained eloquently in [the lkml patch set](https://lore.kernel.org/lkml/20240712014009.281406-1-Jason@zx2c4.com/), but it boils down to "it would be nice to have the security of a kernel CSPRNG with the speed of a userspace CSPRNG" and indeed it would be nice if crypto/rand was so fast that no one ever reached for something else.

It was [pulled in Linux 6.11](https://lore.kernel.org/lkml/20240719183308.1472668-1-Jason@zx2c4.com/) (released 2024-09-15) and [Linux 6.12 will add arm64, powerpc64, powerpc32, s390x, and loongarch64 support](https://lore.kernel.org/lkml/20240916121358.3666562-1-Jason@zx2c4.com/). It doesn't seem to be documented in the kernel Documentation or in the man pages, but the patch set explains the API (and there's [this LWN article](https://lwn.net/Articles/983186/), too).

I just finished mailing [a chain of crypto/rand changes](https://go.dev/cl/608437) and I wanted to add this on top, but the vDSO mechanism is too deep in the runtime for me to feel confident wiring it in. If someone else (@ianlancetaylor maybe?) wanted to make the runtime changes to expose the vDSO function, happy to then do the crypto/rand ones.

/cc @golang/security

**Comment by zx2c4** [comment]
I'll take a stab at it. I've got a bunch of Go backlog and this sounds like a good project to pull me back to it.

**Comment by zx2c4** [comment]
Ok I did it.

**Comment by zx2c4** [comment]
Sent in a change for x/sys/unix to benefit from the runtime enhancements in the other change.

**Comment by zx2c4** [comment]
Alright, this all is now done, and everything should be wired up. I handled amd64, arm64, ppc64, loong64, and s390x. Please do remember to handle riscv in 3ish months for Linux 6.13 when that starts rolling.
