### ISSUE TITLE
inner function can not reimplement bug

### ISSUE THREAD

**Issue by runsys** [golang/go#69579]
### Go version

all

### Output of `go env` in your module/workspace:

```shell
common
```

### What did you do?

write:

func Len(a any) uint64 {
	return uint64(len(a))
}

### What did you see happen?

compile error

### What did you expect to see?

compile ok:
func Len(a any) uint64 {
	return uint64(len(a))
}

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
