### ISSUE TITLE
cmd/compile: type arguments for generic aliases are not checked against type parameter constraints

### ISSUE THREAD

**Issue by mneverov** [golang/go#69576]
### Go version

go version devel go1.24-c208b91395 Fri Sep 20 13:54:44 2024 +0000 X:aliastypeparams linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/mneverov/.cache/go-build'
GOENV='/home/mneverov/.config/go/env'
GOEXE=''
GOEXPERIMENT='aliastypeparams'
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/mneverov/go/pkg/mod'
GONOPROXY='gitlab.in.strato.de,github.com/ionos-cloud'
GONOSUMDB='gitlab.in.strato.de,github.com/ionos-cloud'
GOOS='linux'
GOPATH='/home/mneverov/go'
GOPRIVATE='gitlab.in.strato.de,github.com/ionos-cloud'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/home/mneverov/go/src/github.com/golang/go'
GOSUMDB='sum.golang.org'
GOTMPDIR='/home/mneverov/tmp'
GOTOOLCHAIN='auto'
GOTOOLDIR='/home/mneverov/go/src/github.com/golang/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='devel go1.24-c208b91395 Fri Sep 20 13:54:44 2024 +0000 X:aliastypeparams'
GODEBUG=''
GOTELEMETRY='on'
GOTELEMETRYDIR='/home/mneverov/.config/go/telemetry'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/mneverov/go/src/github.com/mneverov/usealias/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/home/mneverov/tmp/go-build764456494=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

see in [playground](https://go.dev/play/p/A2eA2_4QCSt?v=gotip)

```go
// GOEXPERIMENT=aliastypeparams

package main

import "fmt"

type T[P int] struct{ f P }
type A[P int] = T[P]

func main() {
	var ta A[string]
	fmt.Printf("%#v\n", ta)
}
```

### What did you see happen?

The output is `main.T[string]{f:""}`

### What did you expect to see?

error `string does not satisfy int (string missing in int)`

**Comment by rittneje** [comment]
As the error indicates, this is because you declared `type A[P int]`, which means the generic type can only be `int`, hence `string` is not allowed.

Changing your variable to be `var ta A[int]`, or change your type declarations to be `type T[P any]` and `type A[P any]` resolves it.

**Comment by seankhliao** [comment]
as mentioned above, type aliases don't allow you to relax type constraints.

**Comment by atdiar** [comment]
Think it should be reopened.
OP seems to wonder why it compiles.
Seems like a bug.

**Comment by mneverov** [comment]
> as mentioned above, type aliases don't allow you to relax type constraints.

I'm not relaxing the constraint with the alias. Declaring an alias with the same constraint as the initial type eliminates the constraint. The code compiles, but should error out FMPV.

**Comment by ianlancetaylor** [comment]
CC @griesemer @findleyr 

This does look like a bug.  The type alias permits type arguments that are not permitted by the constraint.

**Comment by griesemer** [comment]
It appears that we're not checking the constraints for alias type parameters at all. Simpler reproducer:
```Go
package p

type A[P int] = struct{}

var _ A[string] // no error reported here
```
Temp. work-around: write correct code...

**Comment by cuonglm** [comment]
> It appears that we're not checking the constraints for alias type parameters at all. Simpler reproducer:
> 
> ```go
> package p
> 
> type A[P int] = struct{}
> 
> var _ A[string] // no error reported here
> ```
> 
> Temp. work-around: write correct code...

It seems to me that when checking var type, we stop immediately as long sa we see type param.

**Comment by griesemer** [comment]
@cuonglm This is unrelated to var types. It also happens if we declare another type that depends on `A`. The problem is that `Checker.instantiatedType` doesn't verify the instantiation if the instantiated type is an alias.
