### ISSUE TITLE
/src/database/sql/sql.go: Please allow to modify dsn(password) used by the db connection pool

### ISSUE THREAD

**Issue by SaradaSastri** [golang/go#69580]
### Go version

go version go1.22.2 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE='on'
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/ssastri/Library/Caches/go-build'
GOENV='/Users/ssastri/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/ssastri/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/ssastri/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/Users/ssastri/.asdf/installs/golang/1.21.6/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.darwin-arm64'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/Users/ssastri/.asdf/installs/golang/1.21.6/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.darwin-arm64/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.22.2'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/ssastri/repo/liftie-ssastri3/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/4d/f6fbmqk57c16f2m7xvp1zgpc0000gn/T/go-build2232261541=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

https://github.com/golang/go/blob/097b7162adeab8aad0095303aff8a045bbbfa6e0/src/database/sql/sql.go#L801

We are using the db connection pool. The connection pool uses dsn whenever it establishes new connection.
We have the requirement to modify the password in the connection string used by connection pool

UseCase: We are planning to switch to IAM DB Auth instead of basic Auth. The token expires every 15 mins and hence needs to be changed every so often.

### What did you see happen?

There are no modifier methods that allow us to modify the dsn or the password in the dsn connection string.

### What did you expect to see?

Please add modifiers to change the password used by existing connection pool.
You can fix this in the latest version of go, that too will help.

**Comment by seankhliao** [comment]
https://pkg.go.dev/database/sql#OpenDB is more appropriate for this
