### ISSUE TITLE
x/pkgsite: package removal request for "github.com/iambpn/go-schema-validator"

### ISSUE THREAD

**Issue by iambpn** [golang/go#69581]
### What is the path of the package that you would like to have removed?

https://pkg.go.dev/github.com/iambpn/go-schema-validator

### Are you the owner of this package?

Yes, I am the owner of this module. I have only published this module few days back.

### What is the reason that you could not retract this package instead?

I want to remove this package because I didn't like the different path for documentation and package import. Also, importing package required to use deep path like `github.com/iambpn/go-schema-validator/pkg/schema` I would prefer to have a path like `github.com/iambpn/go-schema-validator/schema`. I tried redaction, but redaction didn't solve this problem. So I am requesting to remove this package.

**Comment by seankhliao** [comment]
your repository still exists and is public, what do you wish to achieve through removal?

**Comment by iambpn** [comment]
I want to make my repo public and also index in pkg.go.dev, but I have messed up the package import path and semantic versioning. So deleting it would solve that problem.

**Comment by seankhliao** [comment]
removal only means hiding the generated documentation, it doesn't allow you to restart semver for your module

**Comment by iambpn** [comment]
Oh. I didn't know that.

If that's the case, then I will mark my v1 as depreciated and work on v2.

I am closing this ticket now. Thanks for your clarification.
