### ISSUE TITLE
x/build/cmd/watchflakes: fails to run after a build output property field gitilesCommit → gitiles_commit rename

### ISSUE THREAD

**Issue by dmitshur** [golang/go#69609]
Watchflakes is currently in a continuous crashloop:

```
$ kubectl logs -p watchflakes-deployment-7dd687d899-8rf75
watchflakes: 2024/09/24 12:12:43 ListBuilders  
watchflakes: 2024/09/24 12:12:44 ReadBoard go master
watchflakes: 2024/09/24 12:12:44 ListCommits go master
watchflakes: 2024/09/24 12:12:44 ListBuilders go master
watchflakes: 2024/09/24 12:12:45 GetBuilds gotip-linux-amd64-ssacheck
watchflakes: 2024/09/24 12:12:45 GetBuilds gotip-linux-386-softfloat
[...]
watchflakes: 2024/09/24 12:12:45 GetBuilds gotip-linux-386-longtest
watchflakes: 2024/09/24 12:12:45 GetBuilds gotip-js-wasm
watchflakes: 2024/09/24 12:12:45 GetBuilds gotip-linux-amd64-longtest-race
watchflakes: 2024/09/24 12:12:46 repo mismatch:  go https://ci.chromium.org/b/8735981222897055585
```

It keeps running into the log.Fatalf at [luci.go:366](https://cs.opensource.google/go/x/build/+/master:cmd/watchflakes/luci.go;l=366;drc=1cfd0d1ff7e3c79202c745b11299cf5ace3c34e4).

The problem is likely related to the fact that the output property "sources" now has a field named "gitiles_commit", whereas previously that field was named "gitilesCommit", and watchflakes [looks only for the previous name](https://cs.opensource.google/go/x/build/+/master:cmd/watchflakes/luci.go;l=358;drc=1cfd0d1ff7e3c79202c745b11299cf5ace3c34e4) at this time.

For reference:
- [build 8736245996583568945](https://ci.chromium.org/b/8736245996583568945/infra) from Sep 20 has "gitilesCommit"
- [build 8736029737891541697](https://ci.chromium.org/b/8736029737891541697/infra) from Sep 23 has "gitiles_commit"

[crrev.com/c/5875121](https://crrev.com/c/5875121) might be what caused the field to have a new underscore-separated name.

CC @golang/release, @dr2chase, @cherrymui.

**Comment by dr2chase** [comment]
Not sure how to test it, but https://go.dev/cl/615515 might work.

**Comment by dmitshur** [comment]
One way to test it would be to run it locally; it should no longer run into the "repo mismatch" error.
You'll also know it works when you [deploy watchflakes with it](https://go.googlesource.com/build/+/HEAD/doc/deployment.md), and it resumes working.

Thanks for fixing this.

**Comment by dmitshur** [comment]
The production instance isn't healthy yet:

```
$ kubectl get pods | grep watchflakes
watchflakes-deployment-7dd687d899-8rf75    0/1   CrashLoopBackOff   1876 (3m53s ago)   17d
```

@dr2chase Have you had a chance to [deploy](https://go.googlesource.com/build/+/HEAD/doc/deployment.md) watchflakes with this fix included?

**Comment by dr2chase** [comment]
I had not realized I needed to give it an explicit kick, let me try that.
