### ISSUE TITLE
path/filepath: SplitList return wrong value when the input string started with `;` on Windows

### ISSUE THREAD

**Issue by ray1422** [golang/go#69607]
### Go version

go version go1.20.14 windows/amd64

### Output of `go env` in your module/workspace:

```shell
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Administrator\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Administrator\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.20.14
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\Administrator\AppData\Local\Temp\go-build3983377417=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

```go
fmt.Printf("%+#v\n", filepath.SplitList(`";C:\;c:\Users\"`))
```

### What did you see happen?

filepath.SplitList return wrong value when the input string started with `;`
```go
[]string{";C:\\;c:\\Users\\"}
```

### What did you expect to see?

```go
[]string{"C:\\", "c:\\Users\\"}
```

**Comment by ianlancetaylor** [comment]
CC @golang/windows

**Comment by mattn** [comment]
```
fmt.Printf("%+#v\n", filepath.SplitList(`";C:\;c:\Users\"`))
```

What are the quoting rules for this? Go strings? JSON strings? DOS batch?

**Comment by dagood** [comment]
According to https://github.com/golang/go/commit/b4109f801a2b51978e1ddc1918a4558a8d8ba36c and the linked discussion+CL, this is the correct behavior. In the discussion thread, it mentions that on Windows, `;` is allowed in a directory name, and quoting it lets you include it in PATH and avoid Windows treating the `;` as a separator.

That aside, why do you expect to see `[]string{"C:\\", "c:\\Users\\"}` as the return value? There might be some context missing here.

**Comment by zigo101** [comment]
There is at least an inconsistency problem here between Windows and Linux:

```Go
// on Linux, : can be used in paths.
	fmt.Printf("%+#v\n", filepath.SplitList(`":/tmp/foo:/tmp/bar"`))
	// []string{"\"", "/tmp/foo", "/tmp/bar\""}
```

vs. OP's Windows result:

```Go
// on Windows, ; can be used in paths
	fmt.Printf("%+#v\n", filepath.SplitList(`";C:\;c:\Users\"`))
	// []string{";C:\\;c:\\Users\\"}
```

**Comment by dagood** [comment]
On Linux, I haven't seen a way to put a dir containing `:` onto `PATH`. https://unix.stackexchange.com/a/709937 claims that it's not possible. To me, it seems that `filepath.SplitList` behaves as expected on each platform.

**Comment by ray1422** [comment]
Sorry my mistake in the test case. However I'm encouraged problem of exec.Command reports executable not found when my path starting with semicolon. I'll verify it again. Thanks.
