### ISSUE TITLE
x/website: linux install instruction version number not updated on chromeos

### ISSUE THREAD

**Issue by RyanRosario** [golang/go#69603]
### What is the URL of the page with the issue?

https://go.dev/doc/install

### What is your user agent?

Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36

### Screenshot

![Screenshot 2024-09-23 7 29 09 PM](https://github.com/user-attachments/assets/60129320-b282-422c-be3f-513fb4b03376)

### What did you do?

I tried to blindly run the command in the first box after downloading the 1.23 go distribution.

### What did you see happen?

I got a a no such file or directory error.

Even though the latest version is printed on the blue button, the instructions contained an old version number.

### What did you expect to see?

I expected the command to delete any old Go distributions and extract the latest distribution into /usr/local.

I expected the command to contain a version number matching the latest version in the blue button text.

**Comment by dr2chase** [comment]
@golang/tools-team

**Comment by matloob** [comment]
@RyanRosario do you have javascript disabled on your browser?

The [filename in the instructions served in the original html are 1.14.3](https://cs.opensource.google/go/x/website/+/master:_content/doc/install.html;l=83;drc=15db8a6e56d8c31431c243dea63c3299892d9ba9) but we use javascript to [dynamically update the file name](https://cs.opensource.google/go/x/website/+/master:_content/doc/download.js;l=59;drc=e9ef0abe70ff1b180fda874b423aec83045ab161) in the download instructions.

**Comment by RyanRosario** [comment]
@matloob I do not. JavaScript is enabled. I am using Chrome on a Chromebook+. I just visited the site again and it still shows 1.14.3.

**Comment by seankhliao** [comment]
Maybe ChomeOS / CrOS should be treated as a unix in https://go.dev/doc/download.js

**Comment by matloob** [comment]
I'm wondering why we don't always set the version even if the OS isn't linux? It seems like this problem could occur if the user user agent doesn't match any of the `detectOS` patterns because the linux tab will be selected by default but the file name won't be updated because the OS isn't set to linux.

**Comment by seankhliao** [comment]
I was also wondering why there was a unix OS that wouldn't match any download option. I've updated my CL.
