### ISSUE TITLE
x/pkgsite: kuberc documentation page has a typo in the title

### ISSUE THREAD

**Issue by avanish23** [golang/go#69608]
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/monsterxx03/kuberc#section-readme

### What is your user agent?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36

### Screenshot

![Screenshot 2024-09-24 at 4 48 21 PM](https://github.com/user-attachments/assets/fdfa670e-117b-491e-8bd3-e2dcea3c84e7)

### What did you do?

Open the kuberc documentation [here](https://pkg.go.dev/github.com/monsterxx03/kuberc#section-readme) 

### What did you see happen?

The message we see there is given below(pls check the screenshot)
`kubectl plugin for managing redis cluster & and redis sentinel`
The issue is that "and" gets repeated as "& and" 

### What did you expect to see?

The title should be 
`kubectl plugin for managing redis cluster & redis sentinel` instead of `kubectl plugin for managing redis cluster & and redis sentinel`

Just by removing "and" the issue should be fixed
Should look like this 
![Screenshot 2024-09-24 at 4 55 32 PM](https://github.com/user-attachments/assets/09df665c-28bc-4bfd-b611-dba1d40fe148)

**Comment by zigo101** [comment]
Should it be reported to https://github.com/monsterxx03/kubectl-rc

**Comment by seankhliao** [comment]
please report it to the original repo
