### ISSUE TITLE
x/build: add QEMU builder

### ISSUE THREAD

**Issue by prattmic** [golang/go#69615]
We've had several QEMU-only bugs recently (e.g., #68976, #69255).

QEMU is effectively a secondary implementation of the architecture when performing instruction emulation.

QEMU is also effectively a secondary implementation of Linux when running in "[user mode](https://www.qemu.org/docs/master/user/main.html)" (similar to WSL1).

It would be nice to have an advisory builder to provide some warning of failures. There are a lot of variables: QEMU version, user mode or not, host arch, target arch. #68976 affects only user mode, and only older versions of QEMU, not the latest version.

Covering all of these configurations is too much. We should pick one that we think is one of the most common. Based on #68976 and #69255, that seems to be: QEMU version shipped with Debian, user mode. Targeting arm64 from host amd64 or vice versa both seem common; it's unclear which is more common, though I imagine amd64 host is easier to set up.

**Comment by seankhliao** [comment]
is this #1508 ?

**Comment by prattmic** [comment]
Indeed, thanks @seankhliao, I'm 13 years too late.
