### ISSUE TITLE
x/tools/go/packages: document doesn't show the symbol links

### ISSUE THREAD

**Issue by xieyuschen** [golang/go#69618]
Currently, [pkg.go.dev of go/packages](https://pkg.go.dev/golang.org/x/tools@v0.25.0/go/packages) doesn't show the link of symbols(funciton, struct definition) because the comments haven't used the [links notation mentioned in Go Doc Comments](https://tip.golang.org/doc/comment#links).

 1. some symbols should have links

![image](https://github.com/user-attachments/assets/87a24e36-13b2-41b9-aa3d-a992958b7a8a)

 2. issues listed in the comment should be rendered as a list

![image](https://github.com/user-attachments/assets/29197ab8-ceb1-43ea-947b-eaf634b87cdf)

Besides, the [<StructName>.<FieldName>] hasn't been fixed yet mentioned in https://github.com/golang/go/issues/61394, could I know the progress about it?

**Comment by Tharanishwaran** [comment]
can i work on this issue
