### ISSUE TITLE
unique: document thread safety

### ISSUE THREAD

**Issue by Deleplace** [golang/go#69637]
### Go version

go version go1.23.1 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/deleplace/Library/Caches/go-build'
GOENV='/Users/deleplace/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/deleplace/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/deleplace/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.23.1'
GODEBUG=''
GOTELEMETRY='on'
GOTELEMETRYDIR='/Users/deleplace/Library/Application Support/go/telemetry'
GCCGO='gccgo'
GOARM64='v8.0'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/p4/g7fnpss96g5708_mmv3cxzgh0000gn/T/go-build1180605141=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

Read https://pkg.go.dev/unique

### What did you see happen?

No mention of concurrency or safety

### What did you expect to see?

A sentence "unique.Make is safe for concurrent use by multiple goroutines."

## Discussion

The general rule in Go documentation is that when something is not documented as thread-safe, then it should be regarded as not thread-safe.

However, the [unique](https://pkg.go.dev/unique) package is in fact thread-safe, and this undocumented fact is not obvious to some users.

I suggest to follow the example of:
- [rand](https://pkg.go.dev/math/rand): "Top-level functions, such as [Float64](https://pkg.go.dev/math/rand#Float64) and [Int](https://pkg.go.dev/math/rand#Int), are safe for concurrent use by multiple goroutines."
- [sync.Pool](https://pkg.go.dev/sync#Pool): "A Pool is safe for use by multiple goroutines simultaneously."

**Comment by ianlancetaylor** [comment]
CC @mknyszek

**Comment by mknyszek** [comment]
Thanks. I'll send a CL out today.

**Comment by Deleplace** [comment]
Less importantly, we may also say "unique.Handle.Value is safe for concurrent use by multiple goroutines."
