### ISSUE TITLE
x/pkgsite: Some examples of functions are missing, but there are relevant example codes in the source code

### ISSUE THREAD

**Issue by cuishuang** [golang/go#69654]
### What is the URL of the page with the issue?

https://pkg.go.dev/maps   

### What is your user agent?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36

### Screenshot

![image](https://github.com/user-attachments/assets/c5d48669-2bfe-47a7-8bf9-e3e185abcef9)

### What did you do?

I noticed that the examples for the maps package on [pkg.go.dev](https://pkg.go.dev/maps) are missing. The newly added methods like All, Keys, and others (5 in total) don't have examples, even though they exist in [maps/example_test.go](https://github.com/golang/go/blob/master/src/maps/example_test.go).

After that, I checked the documentation for [slices](https://pkg.go.dev/slices) and found the same issue: the examples for the new methods, such as All, Backward, and 5 others, are missing — but again, they are present in [slices/examples_test.go](https://github.com/golang/go/blob/master/src/slices/example_test.go).

![image](https://github.com/user-attachments/assets/e10b17eb-119b-43cb-9ac9-e020c27c30c2)

The awkward part is that I was the last person to modify both files. After a brief moment of panic, I ran godoc -http=:9092 -goroot="." locally and accessed http://127.0.0.1:9092/pkg/maps/, and everything was as expected, with the examples present.

![image](https://github.com/user-attachments/assets/d39475ea-6464-4ea9-ac02-dd3a2da3f97f)

![image](https://github.com/user-attachments/assets/95b4eb92-7d35-429a-8906-53b39d16c4d3)

### What did you see happen?

I'm not entirely sure about the difference between godoc -http=:9092 -goroot="." and pkg.go.dev, but I suspect that pkg.go.dev might be using a different Go version than the one marked here: Version: go1.23.1 Latest Published: Sep 5, 2024.

### What did you expect to see?

Does this issue need to be fixed? Please give me some advice, I am happy to continue researching and fixing this issue

**Comment by seankhliao** [comment]
you're looking at the docs for 1.23.1, but the added examples are in tip, see https://pkg.go.dev/maps@master
