### ISSUE TITLE
不同项目打包ios的sdk时，在移动端使用出现如下报错：goSeqDictionary、GoSeqRef、RefCounter、RefTracker

### ISSUE THREAD

**Issue by banStayUpLate** [golang/go#69656]
我有项目A，使用gomobile打包ios和android用的sdk，项目b同理使用gomobile库进行编译sdk，移动端同时使用两份sdk出现goSeqDictionary、GoSeqRef、RefCounter、RefTracker符号冲突的问题，请问该如何进行解决

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by zigo101** [comment]
@banStayUpLate 
Do you mean you need two different Go toolchain installations on the same machine? If it is true, you can try GoTV (https://go101.org/apps-and-libs/gotv.html).
