### ISSUE TITLE
x/website: document modules/gomod-ref missing godebug introduced in go 1.23

### ISSUE THREAD

**Issue by haitch** [golang/go#69688]
### Go version

1.23

### Output of `go env` in your module/workspace:

```shell
n/a
```

### What did you do?

research godebug syntax in go.mod reference https://go.dev/doc/modules/gomod-ref 

### What did you see happen?

not seeing this godebug in the doc at all.

### What did you expect to see?

it appears to be introduced in go 1.23: https://go.dev/doc/godebug#default , which are missing in gomod-ref document

**Comment by mknyszek** [comment]
CC @golang/tools-team

**Comment by hyangah** [comment]
cc @matloob @samthanawalla
