### ISSUE TITLE
net: GODEBUG=netdns=cgo does not take priority over netgo build tag

### ISSUE THREAD

**Issue by rittneje** [golang/go#69680]
### Go version

go version go1.22.7 darwin/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE='auto'
GOARCH='amd64'
GOBIN=''
GOCACHE='/tmp/.gocache'
GOENV='/Users/rittneje/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/rittneje/test/pkg/mod'
GONOPROXY='[REDACTED]'
GONOSUMDB='[REDACTED]'
GOOS='darwin'
GOPATH='/Users/rittneje/test'
GOPRIVATE='[REDACTED]'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/Users/rittneje/go1.22.7'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='local'
GOTOOLDIR='/Users/rittneje/go1.22.7/pkg/tool/darwin_amd64'
GOVCS='[REDACTED]'
GOVERSION='go1.22.7'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/rittneje/test/src/dialtest/go.mod'
GOWORK='/Users/rittneje/test/go.work'
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/kf/kr7_s3xx0l12zbj3jrn082hmzy5gvy/T/go-build3261540356=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

I ran a program as follows:
```
GODEBUG=netdns=cgo+1 go run -tags=netgo main.go
```

### What did you see happen?

> go package net: built with netgo build tag; using Go's DNS resolver

### What did you expect to see?

> go package net: GODEBUG setting forcing use of cgo's resolver

---

It should be noted that `GODEBUG` takes priority in the reverse situation.
```
GODEBUG=netdns=go+1 go run -tags=netcgo main.go
```

> go package net: GODEBUG setting forcing use of Go's resolver

**Comment by mateusz834** [comment]
It works as expected `-tags netgo` causes the net package to be build entirely without cgo, whereas `-tags netcgo` sets a preference on the cgo resolver, but the go is still in the binary, so we can run it.

**Comment by rittneje** [comment]
@mateusz834 I don't think the docs currently mention that. https://pkg.go.dev/net#hdr-Name_Resolution

That also seems like something the debug log should directly state, instead of seemingly ignoring the GODEBUG setting entirely.

**Comment by mateusz834** [comment]
@rittneje I agree, will send a CL to mention that in the docs.

**Comment by mateusz834** [comment]
> That also seems like something the debug log should directly state, instead of seemingly ignoring the GODEBUG setting entirely.

@ianlancetaylor any thoughts on this? We can mention that in the `GODEBUG=netdns=1` mode, but not sure whether this is really that useful. Panic would be better, but i am not sure whether we can do this at this point.

**Comment by ianlancetaylor** [comment]
For the case of `GODEBUG=netdns=cgo go run -tags=netgo` I don't think we should panic.  I don't think that serves anybody.  For `GODEBUG=netdns=cgo+1` I think it would be OK to log something like "ignoring GODEBUG=netdns=cgo as -tags=netgo forces netdns=go".

**Comment by mateusz834** [comment]
Also the same issue exists for `CGO_ENABLED=0`.
