### ISSUE TITLE
github: block merge button on github x/ repos

### ISSUE THREAD

**Issue by mateusz834** [golang/go#69718]
I can merge PRs at the https://github.com/golang/sys repo, i think that it should be disabled just as in the golang/go repo.

![obraz](https://github.com/user-attachments/assets/d71b5295-9ec5-40ae-9326-c9e80bd0ab75)

golang/go repo:

![obraz](https://github.com/user-attachments/assets/c5666ef9-7546-4f9c-9354-1d8755c4ac10)

CC @golang/release

**Comment by dmitshur** [comment]
This is issue #59048. Issue #39055 is also related.
