### ISSUE TITLE
String with nil backing array causing panics in 1.23

### ISSUE THREAD

**Issue by watchforstock** [golang/go#69710]
### Go version

go1.23.1 windows/amd64

### Output of `go env` in your module/workspace:

```shell
Note this is from a development machine. Our current deployed system is run on windows (cross compiled on a linux build server)

GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/Username/Library/Caches/go-build'
GOENV='/Users/Username/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/username/go/pkg/mod'
GONOPROXY='*.company.local'
GONOSUMDB='*.company.local'
GOOS='darwin'
GOPATH='/Users/Username/go'
GOPRIVATE='*.company.local'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/opt/homebrew/Cellar/go/1.23.1/libexec'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='local'
GOTOOLDIR='/opt/homebrew/Cellar/go/1.23.1/libexec/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.23.1'
GODEBUG=''
GOTELEMETRY='local'
GOTELEMETRYDIR='/Users/username/Library/Application Support/go/telemetry'
GCCGO='gccgo'
GOARM64='v8.0'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD='/Users/username/project/go.mod'
GOWORK='/Users/username/Development/go.work'
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/_s/568w3p_n6y5f1dlkb7r5_snh0000gn/T/go-build424052742=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

We have a large complex code base and are still tracking down the issue. Code that has been running fine on go1.22 seems to be failing on go1.23. At the moment we haven't been able to recreate the issue except on a customer system.

### What did you see happen?

We noticed that when requesting the length of a string variable, we were getting a size > 1TB. On closer inspection it appears that the data pointer for the string is nil and there is (we assume) invalid data in the length property).

The string in question may be being created programmatically, or may be coming as the result of unmarshalling JSON into an object (we initially suspected the unmarshalling library, but we switched this out for the standard-library version and saw the same results).  We are continuing to try and isolate where the invalid string is being created.

It's worth noting that this appears to have a degree of randomness to it, in that we can sometimes have a run which doesn't exhibit the issue - also the code path where we're having the issue is executed thousands of times during a run and many of those times are successful before we see a failure.

We are getting a strack trace as follows (only partial I'm afraid):
```
.\project-win-snapshot-f18b047.exe : runtime: VirtualAlloc of 1099511701504 bytes failed with errno=1455
At line:1 char:1
+ .\project-win-snapshot-f18b047.exe run -c .\static\deployments...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (runtime: Virtua...with errno=1455:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
fatal error: out of memory
 
runtime stack:
runtime.throw({0x393303b?, 0x1cdd51bc000?})
                /usr/local/go/src/runtime/panic.go:1067 +0x4d fp=0x32a57ffb70 sp=0x32a57ffb40 pc=0xba97ed
runtime.sysUsedOS(0x1c000000000, 0x10000012000)
                /usr/local/go/src/runtime/mem_windows.go:83 +0x1bb fp=0x32a57ffbd0 sp=0x32a57ffb70 pc=0xb4aa3b
runtime.sysUsed(...)
                /usr/local/go/src/runtime/mem.go:77
runtime.(*mheap).allocSpan(0xb8baba0, 0x8000009, 0x0, 0x1)
                /usr/local/go/src/runtime/mheap.go:1345 +0x487 fp=0x32a57ffc78 sp=0x32a57ffbd0 pc=0xb5d9c7
runtime.(*mheap).alloc.func1()
                /usr/local/go/src/runtime/mheap.go:962 +0x5c fp=0x32a57ffcc0 sp=0x32a57ffc78 pc=0xb5d17c
runtime.systemstack(0xc000106000)
                /usr/local/go/src/runtime/asm_amd64.s:514 +0x49 fp=0x32a57ffcd0 sp=0x32a57ffcc0 pc=0xbb0fa9
 
goroutine 165899 gp=0xc019b60e00 m=5 mp=0xc000100008 [running]:
runtime.systemstack_switch()
                /usr/local/go/src/runtime/asm_amd64.s:479 +0x8 fp=0xc009c85fd0 sp=0xc009c85fc0 pc=0xbb0f48
runtime.(*mheap).alloc(0x10000012000?, 0x8000009?, 0x4d?)
                /usr/local/go/src/runtime/mheap.go:956 +0x5b fp=0xc009c86018 sp=0xc009c85fd0 pc=0xb5d0db
runtime.(*mcache).allocLarge(0x1b30?, 0x10000010003, 0x1)
                /usr/local/go/src/runtime/mcache.go:234 +0x87 fp=0xc009c86068 sp=0xc009c86018 pc=0xb497e7
runtime.mallocgc(0x10000010003, 0x3361520, 0x1)
                /usr/local/go/src/runtime/malloc.go:1177 +0x5d0 fp=0xc009c86108 sp=0xc009c86068 pc=0xba3d90
runtime.makeslice(0x60?, 0xb475bd?, 0xc025cb5801?)
                /usr/local/go/src/runtime/slice.go:116 +0x49 fp=0xc009c86130 sp=0xc009c86108 pc=0xbabaa9
scm.company.local/project/project.git/data.Node.MarshalJSON(...)
                /go/pkg/mod/scm.company.local/project/project.git@v0.26.1-0.20240930081403-908ad04ce8ae/data/node.go:46
scm.company.local/project/project.git/data.(*Node).MarshalJSON(0x3801980?)
                <autogenerated>:1 +0x7f fp=0xc009c861e8 sp=0xc009c86130 pc=0x10b591f
github.com/goccy/go-json/internal/encoder.AppendMarshalJSON(0xc023efba00, 0xc003dade90, {0xc02f3f8000, 0x735c, 0x2a000},
{0x3801980?, 0xb8f89c0?})
                /go/pkg/mod/github.com/goccy/go-json@v0.10.2/internal/encoder/encoder.go:430 +0x276 fp=0xc009c86358 sp=0xc009c861e8 pc=0xf8f516
github.com/goccy/go-json/internal/encoder/vm.appendMarshalJSON(0x88b6c80?, 0xc013a17590?, {0xc02f3f8000?, 0xc025281b08?,
0xc0025e3b90?}, {0x3801980?, 0xb8f89c0?})
                /go/pkg/mod/github.com/goccy/go-json@v0.10.2/internal/encoder/vm/util.go:152 +0x25 fp=0xc009c863a0 sp=0xc009c86358 pc=0x10127e5
github.com/goccy/go-json/internal/encoder/vm.Run(0xc023efba00, {0xc02f3f8000?, 0xbac49c?, 0xc009c885a0?}, 0x0?)
                /go/pkg/mod/github.com/goccy/go-json@v0.10.2/internal/encoder/vm/vm.go:271 +0x217e fp=0xc009c886f0 sp=0xc009c863a0 pc=0x1014b3e
github.com/goccy/go-json.encodeRunCode(0xc023efba00?, {0xc02f3f8000?, 0x23?, 0x0?}, 0xbc3c5d?)
                /go/pkg/mod/github.com/goccy/go-json@v0.10.2/encode.go:310 +0x56 fp=0xc009c88728 sp=0xc009c886f0 pc=0x10399d6
github.com/goccy/go-json.encode(0xc023efba00, {0x375d580, 0xc019e719e0})
                /go/pkg/mod/github.com/goccy/go-json@v0.10.2/encode.go:235 +0x205 fp=0xc009c887a8 sp=0xc009c88728 pc=0x1039565
github.com/goccy/go-json.marshal({0x375d580, 0xc019e719e0}, {0x0, 0x0, 0xc0263f4b50?})
                /go/pkg/mod/github.com/goccy/go-json@v0.10.2/encode.go:150 +0xb9 fp=0xc009c88808 sp=0xc009c887a8 pc=0x1039019
github.com/goccy/go-json.MarshalWithOption(...)
                /go/pkg/mod/github.com/goccy/go-json@v0.10.2/json.go:186
github.com/goccy/go-json.Marshal({0x375d580?, 0xc019e719e0?})
                /go/pkg/mod/github.com/goccy/go-json@v0.10.2/json.go:171 +0x25 fp=0xc009c88840 sp=0xc009c88808 pc=0x1039c25
```

The code at /go/pkg/mod/scm.company.local/project/project.git@v0.26.1-0.20240930081403-908ad04ce8ae/data/node.go:46 is as follows:

```
func (n Node) MarshalJSON() ([]byte, error) {
    data := make([]byte, 0, len(n.str)+2)  // line 46
    data = append(data, doubleQuote)
    data = append(data, []byte(n.str)...)
    data = append(data, doubleQuote)
    return data, nil
}
```

### What did you expect to see?

We expected it to run the same on version 1.23 as on version 1.22.

As we are still trying to track this down, if there are additional things we could try (or try to eliminate) that would be helpful.

We are somewhat at a loss as to how the string could get a nil backing array (we're not doing anything with unsafe pointers etc in our code base).

**Comment by Zxilly** [comment]
cc @golang/runtime

**Comment by randall77** [comment]
Have you run your application under the race detector (`-race`)?

The size in question is 0x10000010003. Makes me think of https://github.com/golang/go/issues/68227 which was a missing zero extension on arm64.

**Comment by watchforstock** [comment]
> Have you run your application under the race detector (`-race`)?
> 
> The size in question is 0x10000010003. Makes me think of #68227 which was a missing zero extension on arm64.

We haven't run it under the race detector. At the moment we're only seeing the issue on Windows / amd64 (although we're generally using mac arm64 as a development environment). That said, I noticed that the size looked "structured" rather than random and indeed we have seen the same value multiple times (I can't be definitive that it was always the same)

**Comment by watchforstock** [comment]
I have now realised, partly with the prompt from @randall77 , that if `n.str` was equal to the empty string then it would legitimately have a nil pointer for its underlying storage (we had previously been trying to understand how that might be nil). That would leave the length potentially being corrupted somehow from its zero value. 

Is there anything useful we can look for in the executable to help track down the situation where this issue might be coming from? Unfortunately I can't share the executable itself (and it's about 140MB)

**Comment by randall77** [comment]
Please run with the race detector if you can. Heap corruption like this (if that's what it is) is easily caused by data races.

**Comment by watchforstock** [comment]
> Please run with the race detector if you can. Heap corruption like this (if that's what it is) is easily caused by data races.

Thanks. We will do that (probably tomorrow UK time as we've lost our connection to the customer's environment for the day). Thanks for your help.

**Comment by watchforstock** [comment]
Based on today's investigations it seems most likely that this is a race condition leading to corruption. My team and I very much appreciate the rapid responses and guidance given!
