### ISSUE TITLE
import/path: issue go.dev down

### ISSUE THREAD

**Issue by leenorshn** [golang/go#69726]
### Go version

go.dev down

### Output of `go env` in your module/workspace:

```shell
https://go.dev/doc/install
Ce site est inaccessible
go.dev n'autorise pas la connexion.
Voici quelques conseils :

Vérifier la connexion
Vérifier le proxy et le pare-feu
ERR_CONNECTION_REFUSED
```

### What did you do?

I would like to access the official  site go.dev but the site is not accessible.

### What did you see happen?

I would like to see it again 
Good work!!!

### What did you expect to see?

go.dev alive again

**Comment by seankhliao** [comment]
That seems like an issue with your local network
