### ISSUE TITLE
Make `go install` work consistently for every project

### ISSUE THREAD

**Issue by yonas** [golang/go#69733]
### Go version

go 1.23

### Output of `go env` in your module/workspace:

```shell
N/A
```

### What did you do?

Sometimes it's `go install github.com/hello/world@latest`, or `go install github.com/hello/world/cmd/other@latest` or `go install github.com/hello/world/v3@latest` or it just doesn't work.

### What did you see happen?

Often fails.

### What did you expect to see?

Should install the program(s).

# Proposal

Let's create an official package manifest file format that `go install` can use to find and compile projects.

It would allow putting code in `cmd`, `src`, or any other directory, and will proactively search the root directory and `./cmd/<module name specified at the top of go.mod>`.

**Comment by seankhliao** [comment]
see `go install pkg/...@latest`

**Comment by seankhliao** [comment]
That's intentional, major versions are considered different modules, we would not blur the line between them.

**Comment by yonas** [comment]
@seankhliao But what's the proper `go install` for trufflehog? And why do I need to be ask? It should be as simple as `go install package-name`.

**Comment by seankhliao** [comment]
It is `go install package-name`.
Go is consistent in using fully qualified package names everywhere. Introducing different names for install vs import makes things less consistent.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by yonas** [comment]
> It is `go install package-name.`

@seankhliao That hasn't been my experience.

> [!CAUTION]
> > ...Go is consistent in using fully qualified package names everywhere.
>
> Which is the problem I'm describing.

> [!IMPORTANT]
> > **...fully qualified package names...**
>
> How about simply pointing to the root of a repo.

For example, `golangci-lint` is installed via `go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest`
while another will simply be `go install github.com/some/package@latest`

# Proposal: An Official Go Package Manager

Go needs an official package manager. Rust has `cargo`. Node has `npm`. Just about every cool new language has it's own package manager and package repository.

## Common Features of a Modern Package Manager

### Manifest file
- [ ] describe the project in a single file
  - [ ] manifest file version
  - [ ] project name, description, keywords, categories, version, repo URL, docs URL, homepage URL, license, readme
  - [ ] authors names and email addresses
  - [ ] dependencies with several attributes
    - [ ] version requirements
    - [ ] features
    - [ ] override location (eg. point to a local copy)
  - [ ] features

### Common set of commands
  - [ ] init [ `go mod init` should be `go init` ]
  - [ ] add
  - [ ] remove
  - [ ] build executables / libraries
  - [ ] build documentation
  - [ ] build examples
  - [ ] run
  - [ ] test
  - [ ] bench
  - [ ] update
  - [ ] search
  - [ ] publish
  - [ ] install
  - [ ] uninstall

## Recap

What I'm proposing is that you should only have to type `go install github.com/owner/project` and everything should automatically work.

Specifically, you should not have to:
- add `/cmd/<some command that's not necessarily "project">`
- add `@latest` or `@<some semver>`
