### ISSUE TITLE
x/build: use streaming RPC to list gomote files

### ISSUE THREAD

**Issue by neild** [golang/go#69732]
The number of files on a gomote has passed an RPC size limit event horizon. I can no longer run `gomote push` more than once:

```
$ gomote push
# Using group "debug" from GOMOTE_GROUP
# Pushing GOROOT "/Users/dneil/src/project/openat/go" to "dneil-gotip-windows-amd64-0"...
# Error running push: error listing buildlet's existing files: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4523362 vs. 4194304)
```

Perhaps we can increase that limit, but a more future-proof solution would be to use a streaming RPC to list files.

**Comment by ArjitGopher** [comment]
I am interested in working for this issue.
