### ISSUE TITLE
x/build: add linux-arm64-clang builder

### ISSUE THREAD

**Issue by mknyszek** [golang/go#69763]
Requested by @randall77 for at least debugging clang-on-arm64 issues. Might as well just support it in general, it's about the same amount of work, assuming the tests pass.

**Comment by mknyszek** [comment]
Hrm, some problems:

```
Building Go cmd/dist using /home/swarming/.swarming/w/ir/cache/tools/go_bootstrap. (go1.22.6 linux/arm64)
Building Go toolchain1 using /home/swarming/.swarming/w/ir/cache/tools/go_bootstrap.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for linux/arm64.
# runtime/cgo
clang: /usr/lib/aarch64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by clang)
clang: /usr/lib/aarch64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by clang)
go tool dist: FAILED: /home/swarming/.swarming/w/ir/x/w/goroot/pkg/tool/linux_arm64/go_bootstrap install std: exit status 1
```

Is this just saying that the `libstdc++` that's installed on our builders is too old?

**Comment by ianlancetaylor** [comment]
Yes.  The errors are saying that we can't run the clang binary, because the installed libstdc++.so.6 is too old.

That said, GLIBCXX_3.4.29 and CXXABI_1.3.13 were released in 2021, so we seem to be using some relatively old versions.

**Comment by mknyszek** [comment]
Thanks. I'm not super surprised; our arm64 builder is based on Debian bullseye from 2021. It's a little weird that clang on amd64 works though. It's the same version of clang. Maybe we just haven't updated our arm64 image in a while?

Even weirder, it appears we've got Debian 11.2 for amd64, but Debian 11.7 for arm64...

**Comment by mknyszek** [comment]
I've confirmed that the bookworm image does actually have a new enough `libstdc++`, so hopefully it'll work there.

**Comment by mknyszek** [comment]
Huzzah! `make.bash` works now. https://ci.chromium.org/ui/p/golang/builders/ci-workers.shadow/gotip-linux-arm64-clang15-build_go/b8733166898151394753/infra

**Comment by mknyszek** [comment]
Turns out that was the only issue. Yay! All done. https://ci.chromium.org/ui/p/golang/builders/ci/gotip-linux-arm64-clang15/b8733158741102774385
