### ISSUE TITLE
x/pkgsite: package removal request for github.com/notarock/slopify

### ISSUE THREAD

**Issue by notarock** [golang/go#69770]
I have openly published this module once but have since decided to take it down.

I would really appreciate it if you could remove all versions of https://pkg.go.dev/github.com/notarock/slopify@v1.1.0

Thank you

**Comment by adonovan** [comment]
I confirm that your GitHub userid matches the name of the GitHub repo in question, and have made the necessary changes (internal CL 2347181). Please allow a few days for the configuration change to propagate.
