### ISSUE TITLE
x/mobile: Key codes don't include non-keypad Plus Sign

### ISSUE THREAD

**Issue by justledbetter** [golang/go#69778]
CodeKeypadPlusSign is returned by the library via this line, similar to CodeKeypadHyphenMinus above it:

https://github.com/golang/mobile/blob/c6794c95c70b02ddb1a79d92fec29f8b8ddd8836/event/key/key.go#L179

but there is no corresponding CodePlusSign with CodeHyphenMinus:

https://github.com/golang/mobile/blob/c6794c95c70b02ddb1a79d92fec29f8b8ddd8836/event/key/key.go#L136

**Comment by mknyszek** [comment]
CC @hyangah via https://dev.golang.org/owners

**Comment by justledbetter** [comment]
For reference, Key.Code seems to be set to decimal `46` when the non-keypad `+` is hit, and this works appropriately when combined with Key.Modifiers (`Alt-+`, `Ctrl-+`, etc)

**Comment by justledbetter** [comment]
Looking further at the code, it seems that the _correct_ way to call this is to look for

```
(event.Modifiers&key.ModShift != 0) && (event.KeyCode == key.CodeEqualSign)
```

Tested this on the CrOS system I originally hit the problem on and this seems to be the right fix.  No code change needed to `x/mobile` after all!  😄
