### ISSUE TITLE
all: audit x/ repos for gotypesalias settings

### ISSUE THREAD

**Issue by timothy-king** [golang/go#69772]
This item is to track auditing and then updating all of the x/ repos for correctly setting the `gotypesalias` GODEBUG setting in preparation for 1.24. `main` packages in 1.22 modules (e.g. x/tools/cmd/callgraph) will [default](https://go.dev/doc/godebug#default) to the value of `gotypesalias=0`. If these packages use `go/types` and are built with a 1.24 toolchain, they will have `gotypesalias=0`. Such binaries will not create the `*types.Alias` value that is required to create an alias with type parameters (#46477).  Effectively any such binaries would be unable to properly support 1.24 despite using the 1.24 compiler and standard library.

My proposed plan is to:
1. Find all of the modules in the x/ repos, find all of the main packages within the modules that are <=1.22, and among these main packages determine which transitively import go/types.
1. For all of these packages explicitly label (or comment on) their current status explicitly `//go:debug gotypesalias=0`. (See https://go.dev/cl/617095 for an example.)
1. Audit each `//go:debug gotypesalias=0` for what to do. A good default action is to update these packages to enable `GODEBUG=gotypesalias=1` when built with >=1.23 toolchains (see https://go.dev/cl/617636). 

cc @aclements , @cherrymui , @findleyr, @griesemer , @adonovan , @dmitshur

**Comment by timothy-king** [comment]
x/ repos to audit:

- [ ] arch
- [ ] benchmarks
- [ ] blog
- [ ] build
- [ ] crypto
- [ ] debug
- [ ] dl
- [ ] example
- [ ] exp
- [ ] gddo
- [ ] gofrontend
- [ ] gccgo
- [ ] gollvm
- [ ] govulncheck-action
- [ ] grpc-review
- [ ] image
- [ ] lint
- [ ] mobile
- [ ] mod
- [ ] net
- [ ] oauth2
- [ ] oscar
- [ ] perf
- [ ] pkgsite
- [ ] pkgsite-metrics
- [ ] playground
- [ ] proposal
- [ ] protobuf
- [ ] review
- [ ] scratch
- [ ] sublime-build
- [ ] sublime-config
- [ ] sync
- [ ] sys
- [ ] talks
- [ ] telemetry
- [ ] term
- [ ] text
- [ ] time
- [ ] tools
- [ ] tour
- [ ] vgo
- [ ] vscode-go
- [ ] vuln
- [ ] vulndb
- [ ] website
- [ ] wiki
- [ ] xerrors

**Comment by dmitshur** [comment]
Gaby didn't include it in https://github.com/golang/go/issues/69772#issuecomment-2392352550, but issue #67791 is also related here. If there are tests in x/ repos that would fail when switching to the eventual new default of gotypesalias=1, that builder would report it.

**Comment by timothy-king** [comment]
Excluding gofrontend, there are 60 matches and out of these 25 are in x/tools. x/{tools,vuln,vulndb} are fairly easy to address. The rest give me some pause though. The right thing to do here might just be to update go/types to avoid this.

**Comment by findleyr** [comment]
> The rest give me some pause though. The right thing to do here might just be to update go/types to avoid this.

Can you say more? You mean back porting additional logic to 1.22.x?
IMO it looks pretty straightforward to apply the same mechanical fix in https://go.dev/cl/618676 to each binary target (ideally in a single CL or handful of CLs).

**Comment by timothy-king** [comment]
> Can you say more? 

Sure. 1.24 could materialize *types.Alias values when # type params > 0 and the GOEXPERIMENT is on. Basically ignore the GODEBUG flag for this case. This is backwards compatible with pre 1.24 code. Users of go/types with go.mod files at 1.22 would still need to update their tools to support 1.24 code, but they would not need to apply the a change like https://go.dev/cl/618676. They would not see an error from go/types. A proposal would be needed to change the godebug wording. The advantage is changes like this are unnecessary (in particular for users are not us).

**Comment by timothy-king** [comment]
golang.org/x/playground uses go/types only via golang.org/x/tools/imports. My manual inspection golang.org/x/tools/imports is not sensitive to this setting.

**Comment by timothy-king** [comment]
golang.org/x/website uses go/types only via golang.org/x/tools/imports and runtime.test.

**Comment by timothy-king** [comment]
For golang.org/x/exp/cmd/{apidiff,gorelease} the dependency on go/types is through golang.org/x/exp/apidiff.

golang.org/x/exp/cmd/apidiff tests fail when gotypesalias=1 is enabled.

So it looks like golang.org/x/exp/apidiff needs to be updated for types.Alias.

**Comment by timothy-king** [comment]
golang.org/x/text takes underlying types in message/pipeline/extract.go. So this likely needs to be updated to support 1.24 or an expert on the code needs to do a thorough audit.

**Comment by timothy-king** [comment]
The main packages in golang.org/x/exp/typeparams are examples for illustration purposes only. These do not take input. They are thus not a concern.

**Comment by timothy-king** [comment]
Issues have been filed for the remaining investigations/work. Audit of the packages is done. Nothing remaining seems like a blocker for 1.24.
