### ISSUE TITLE
toolchain: Minimal version selection applies to indirect dependencies even when they are module-local

### ISSUE THREAD

**Issue by pierreprinetti** [golang/go#69798]
### Go version

go version go1.23.2 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN='/var/home/pierre/code/bin'
GOCACHE='/var/home/pierre/.cache/go-build'
GOENV='/var/home/pierre/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/var/home/pierre/code/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/var/home/pierre/code'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/var/home/pierre/sdk/go1.23.2'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/var/home/pierre/sdk/go1.23.2/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.23.2'
GODEBUG=''
GOTELEMETRY='local'
GOTELEMETRYDIR='/var/home/pierre/.config/go/telemetry'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3187542746=/tmp/go-build -gno-record-gcc-switches'
```

#### The background
While preparing a new version of my library, I am testing the interactions between the old version (`v2`) and the new version I am working on (`v3`). I want to import them both, using local rewrites in my local `go.mod`. The caveat: there is no `v3` yet, so internally the imports of both versions are identical.

#### The actual issue

This is the most minimal reproducer I could produce: https://go.dev/play/p/Up68jxuX6_v

This might help understanding the directory structure of the example in the sandbox:

```
$ tree
.
├── go.mod
├── main.go
├── new
│   ├── go.mod
│   ├── speak.go
│   └── sub
│       └── say.go
└── old
    ├── go.mod
    ├── speak.go
    └── sub
        └── say.go

5 directories, 8 files
```

There is a package main that imports both `old` and `new`. Both `old` and `new` contain exactly the same code, and they both import a sub-package `sub`. The content of those two `sub` packages is different: one says `I am old`, the other says `I am new`.

**Both imports are resolved to `old/sub`.**

I find it surprising that imports within a module are not rewritten when a module is imported as a rewrite. I expected `package_new.Speak()` to print `I am new`, because `package_new` imports `sub` from within its own module, and I have rewritten the import of that module.

---

After the initial surprise, I supposed that this was a direct consequence of how minimal version selection works. Both `old` and `new` are importing a package with the same name, so it's natural that only one is retained in the dependency tree.

However, shouldn't packages in the same module be treated differently?

Take this example: https://go.dev/play/p/AxE-iCofpyw

It's the same code as above, except now the `sub` packages are internal.

```
$ tree
.
├── go.mod
├── main.go
├── new
│   ├── go.mod
│   ├── internal
│   │   └── sub
│   │       └── say.go
│   └── speak.go
└── old
    ├── go.mod
    ├── internal
    │   └── sub
    │       └── say.go
    └── speak.go

7 directories, 8 files
```

```
$ go run .
package play.ground
        imports github.com/golang/speak-new
        new/speak.go:6:2: use of internal package github.com/golang/speak/internal/sub not allowed
```

Now compilation fails because both imports of `sub` are resolved to the same package, which happens to be internal to ONE of them.

Is that the intended behaviour?

### What did you see happen?

```
$ go run .
sub says: "I am old"
sub says: "I am old"
```

### What did you expect to see?

```
$ go run .
sub says: "I am old"
sub says: "I am new"
```

**Comment by seankhliao** [comment]
this looks working as intended, MVS applies to modules and not packages. modules need to declare different names in their go.mod

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by pierreprinetti** [comment]
>MVS applies to modules and not packages

hmm right, that's why I am surprised that it applies to packages in this case

**Comment by pierreprinetti** [comment]
A consequence of the issue I am presenting is that you can't import a module twice, if that module has internal packages. Are you sure that this is intended, @seankhliao ?

**Comment by pierreprinetti** [comment]
@seankhliao 

I have slightly changed the example to highlight the suspicious behaviour.

The module is correctly fetched, but subpackages of the modules are fetched by name without namespacing them to the module.

Reproducer: https://go.dev/play/p/1OD7Zm41iMM

```
$ go run .
from OLD, subpackage says: "I am old"
from NEW, subpackage says: "I am old"
```

Whereas it should have been:

```
$ go run .
from OLD, subpackage says: "I am old"
from NEW, subpackage says: "I am new"
```

The modules aliased as "old" and "new" are correctly fetched, but the subpackage of "NEW " should have said "I am new". Instead, the `sub` subpackage of OLD is used.

Are you sure that mixing packages from different modules really is the intended behaviour? That is surprising enough to look like a bug to me.

**Comment by seankhliao** [comment]
They both import the same package `github.com/golang/speak/sub`, only one  package is named that.

**Comment by zigo101** [comment]
> ... modules need to declare different names in their go.mod

If the module name of `new` is changed to a different name, then the code will not compile.

**Comment by zigo101** [comment]
From the perspective of the module in the `new` folder, the `github.com/golang/speak/sub` package path is `./new/sub`. But when it is used as a dependency module, the `github.com/golang/speak/sub` package path is `./old/sub`. This is totally unexpected from the perspective of the module in the `new` folder.

In my honest opinion, the compiler should report a `duplicated packages` alike error. The current behavior (it compiles) is very confusing/surprising. (I totally understand OP's feeling here.)

(This is just one pitfall of the current module system design. There are some others.)

**Comment by zigo101** [comment]
The code (https://go.dev/play/p/VLhjzQtcbD3) works as OP's intention in an unexpected way.

**Comment by zigo101** [comment]
This issue proves that relative import paths are necessary in the module system.

**Comment by zigo101** [comment]
I suggest to re-open this issue, with a different title: a dependency module A should not use the packages in another dependency module B if A's go.mod file doesn't require B.

**Comment by zigo101** [comment]
What you described and I described are two things. In the OP's case, `speak-new` doesn't require `speak` at all, even indirectly.
