### ISSUE TITLE
net/http text/event-stream weird behaviour

### ISSUE THREAD

**Issue by archyd** [golang/go#69794]
### Go version

1.23.1

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/yudis/.cache/go-build'
GOENV='/home/yudis/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
```

### What did you do?

i was trying to implement SSE. So i set header content-type to text/event-stream. the response header are pretty much like this
![image](https://github.com/user-attachments/assets/5555b6e5-b5f1-4510-a7f6-770cb901049c)

but somehow browser detect it as text/plain

### What did you see happen?

on firefox
![image](https://github.com/user-attachments/assets/6ce40a73-5272-4f2b-97dd-03c45b9f3134)
on chrome
![image](https://github.com/user-attachments/assets/1b894943-9e22-4275-b3d3-77c19e69e2c8)

### What did you expect to see?

i does produce the output but it behave like a normal single get response it just print these output and doesnt stream 
![image](https://github.com/user-attachments/assets/6ab47cf5-7440-4a7d-b1ed-110aebfa8fa5)
but somehow it work with curl and it stream as expected.
[Screencast From 2024-10-06 18-26-57.webm](https://github.com/user-attachments/assets/02daaaad-450c-4f19-85e3-0ec3d54a5181)

**Comment by seankhliao** [comment]
headers need to be set before they're written with WriteHeader

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
