### ISSUE TITLE
cmd/compile: allocate some defers in stack frames

### ISSUE THREAD

**Issue by randall77** [golang/go#6980]
<pre>When we can statically determine that a defer is called (at most) once, we should
allocate the Defer structure in the stack frame instead of from the DeferChunk mechanism.

We suspect most defers fit into this category.</pre>

**Comment by aclements** [comment]
Moving to Go 1.9 since we already doubled the performance of defer via other means for Go 1.8.

**Comment by josharian** [comment]
Related: #5712.

**Comment by randall77** [comment]
Punting to unplanned, too late for anything major in 1.12.

**Comment by WGH-** [comment]
Should this be closed? From what I understand, this has been temporarily reverted due to some bugs, and then reverted back: fff4f599 ->  49200e3f -> 8f296f59de

**Comment by randall77** [comment]
Yes, this is done and should be closed.
