### ISSUE TITLE
access: Approving CLs ("approvers")

### ISSUE THREAD

**Issue by limeidan** [golang/go#69807]
Hi,

I am a member of the [golang/loong64](https://github.com/orgs/golang/teams/loong64) . Currently, loong64 has accumulated a lot of unmerged CLs. In order to merge the relevant code of loong64 port faster so that it can keep up with the development progress of other ports, I would like to obtain approval permission. This is my account: limeidan@loongson.cn

See https://go.dev/wiki/GerritAccess#approving-cls-approvers

Looking forward to your reply, thank you.

**Comment by ianlancetaylor** [comment]
CC @golang/release

**Comment by cagedmantis** [comment]
@limeidan please create an issue which requests trybot access.

**Comment by limeidan** [comment]
> @limeidan please create an issue which requests trybot access. As noted at https://go.dev/wiki/GerritAccess#running-trybots-may-start-trybots

https://github.com/golang/go/issues/70120

Done. Thanks.

**Comment by cagedmantis** [comment]
Hi Meidan,

Thank you for contributing to the Go project and helping out so much in the world of modules! I've discussed this request with the team, and we agreed to grant you access. I've added you to the approvers group now.

Please be familiar with the rules for voting and submitting changes as described at https://go.dev/wiki/GerritAccess#approving-cls-approvers. If you're unsure or have any questions, please don't hesitate to ask us.

Thank you again for contributing, your help is greatly appreciated!
