### ISSUE TITLE
encoding/json: Unmarshal to a typed struct uses 50% more bytes in go 1.21 (and current versions) vs go 1.20

### ISSUE THREAD

**Issue by liggitt** [golang/go#69828]
### Go version

go 1.21+ (past https://github.com/golang/go/commit/ac27b4dd1d72bd6467bf7bfa8bc77a1522efd4cc)

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/liggitt/Library/Caches/go-build'
GOENV='/Users/liggitt/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/liggitt/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/liggitt/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/Users/liggitt/.gimme/versions/go1.23.0.darwin.arm64'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/Users/liggitt/.gimme/versions/go1.23.0.darwin.arm64/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.23.0'
GODEBUG=''
GOTELEMETRY='local'
GOTELEMETRYDIR='/Users/liggitt/Library/Application Support/go/telemetry'
GCCGO='gccgo'
GOARM64='v8.0'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/liggitt/go/src/sigs.k8s.io/json/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/37/ns7gt60104scfm9fvg02p1jh00kjgb/T/go-build2228451035=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

Benchmarked json.Unmarshal into a typed go struct using stdlib code from 1.19 / 1.20 / 1.21 / 1.22 / 1.23

Benchmark code and results are at https://gist.github.com/liggitt/bf28159afdaabf52b78ac43d86bc6362

### What did you see happen?

According to benchstat, an unmarshal of https://gist.github.com/liggitt/bf28159afdaabf52b78ac43d86bc6362#file-bench-json into https://gist.github.com/liggitt/bf28159afdaabf52b78ac43d86bc6362#file-regression_test-go-L32 used 50% more memory after https://github.com/golang/go/commit/ac27b4dd1d72bd6467bf7bfa8bc77a1522efd4cc

```
benchstat output1.21-2023-02-27-1156-0d52401e23-good.txt output1.21-2023-02-27-1158-ac27b4dd1d-bad.txt 
goos: darwin
goarch: arm64
pkg: sigs.k8s.io/json
                            │ 1.21-2023-02-27-1156-0d52401e23-good.txt │ 1.21-2023-02-27-1158-ac27b4dd1d-bad.txt │
                            │                  sec/op                  │      sec/op       vs base               │
Unmarshal/typed_stdlib-10                      31.80µ ± 1%                    32.55µ ± 2%  +2.35% (p=0.001 n=10)
Unmarshal/untyped_stdlib-10                    35.80µ ± 2%                    35.40µ ± 2%  -1.10% (p=0.009 n=10)
geomean                                        33.74µ                         33.95µ       +0.61%

                            │ 1.21-2023-02-27-1156-0d52401e23-good.txt │ 1.21-2023-02-27-1158-ac27b4dd1d-bad.txt │
                            │                   B/op                   │      B/op          vs base              │
Unmarshal/typed_stdlib-10                       12.93Ki ± 0%                  19.91Ki ± 0%  +53.96% (p=0.000 n=10)
Unmarshal/untyped_stdlib-10                     27.04Ki ± 0%                  27.04Ki ± 0%        ~ (p=0.491 n=10)
geomean                                         18.70Ki                       23.20Ki       +24.08%

                            │ 1.21-2023-02-27-1156-0d52401e23-good.txt │ 1.21-2023-02-27-1158-ac27b4dd1d-bad.txt │
                            │                allocs/op                 │   allocs/op     vs base                 │
Unmarshal/typed_stdlib-10                    161.0 ± 0%                    162.0 ± 0%    +0.62% (p=0.000 n=10)
Unmarshal/untyped_stdlib-10                  515.0 ± 0%                    515.0 ± 0%         ~ (p=1.000 n=10) ¹
geomean                                      287.9                         288.8         +0.31%
```

### What did you expect to see?

Minimal variance in memory usage minor-over-minor (low single-digit changes)

**Comment by cherrymui** [comment]
cc @dsnet @bradfitz @mvdan

**Comment by ianlancetaylor** [comment]
It's a bit buried, so calling out that the report is saying that the increased memory use is due to https://go.dev/cl/471175 "encoding/json: rely on reflect.Value.Grow".

The 1.20 code always increases the size of a slice by 50% of the previous cap; if that is less than 4 it goes straight to 4.  The 1.21 code grows the slice as though it is appending a single element.  In this case we have small slices, for which it will double the size of a slice.  The effect is to allocate space for 1 element, then 2, then 4.  As the slice elements are fairly large, and the slice winds up with 3 elements, the extra allocation of size 2 likely accounts for the change in memory use.

This seems like a fairly special case.  The new code is normally better.  In this particular case it is worse.  I don't think there is anything to do here.

**Comment by liggitt** [comment]
yeah, I was trying to figure out if the test just happened to hit a ~worst-case scenario... the test data only has a single array (https://gist.github.com/liggitt/bf28159afdaabf52b78ac43d86bc6362#file-bench-json-L12-L46), which has three items

I think the old code grew from 0 → 4 directly

I think the new code grows from 0 → 1, 1 → 2, 2 → 3

I'm still surprised at the size jump for those allocs on that struct, but maybe that fully explains it. If so, I'll probably just adjust the benchmark to exercise arrays of a few different sizes to better represent the general performance

**Comment by liggitt** [comment]
Let me dig another day and I'll self close by EOW if a better distributed benchmark indicates this isn't a general issue

**Comment by liggitt** [comment]
Yeah, with better distributed testdata, the alloc delta ~disappeared
