### ISSUE TITLE
go.tools/imports: update playground with fixed version

### ISSUE THREAD

**Issue by dgryski** [golang/go#6982]
<pre>1. Go to play.golang.org
2. Replace the import line with a comment
3. Click &quot;Format&quot;.  Notice that the comment stays where it is.
4. Check &quot;Imports&quot; and click &quot;Format&quot; again.  The comment is moved
after main().

What is the expected output?
goimports leaves the comment above main().

What do you see instead?
goimports moves the comment after main().

In a real program, the comment rearranging can be much worse:
<a href="http://play.golang.org/p/Wvy-jYoctS">http://play.golang.org/p/Wvy-jYoctS</a>  (taken from <a href="https://github.com/dgryski/dkrcrypt">https://github.com/dgryski/dkrcrypt</a> )

Which version are you using?  (run 'go version')
go version go1.2 linux/amd64.  This happens with goimports pulled from go.tools too, not
only the playground version.</pre>

**Comment by josharian** [comment]
Appears to be done. The issue in comment 6 has been moved to #10337.
