### ISSUE TITLE
x/pkgsite: package removal request for go.astrophena.name/exp

### ISSUE THREAD

**Issue by astrophena** [golang/go#69835]
### What is the path of the package that you would like to have removed?

go.astrophena.name/exp

### Are you the owner of this package?

Yes.

### What is the reason that you could not retract this package instead?

This module was renamed to `tools` and only pollutes pkg.go.dev search results.

**Comment by findleyr** [comment]
Done. Sorry for the delay. Please allow a few hours for this to propagate.

**Comment by astrophena** [comment]
Thanks!
