### ISSUE TITLE
A golang linux program spawned in WSL as a child process of a native Windows application does not exit

### ISSUE THREAD

**Issue by iongion** [golang/go#69845]
### Go version

go version go1.22.2 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/istoica/.cache/go-build'
GOENV='/home/istoica/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/istoica/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/istoica/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/lib/go-1.22'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/lib/go-1.22/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22.2'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2861597373=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

1. I create a windows native program - runs as a server
2. I create a linux native program - runs a server
3. I spawn the linux native program from the windows program, in a certain distribution using `wsl.exe` utility

### What did you see happen?

When I close the native windows process, the child wsl does not exit.

What I notice is that `wsl.exe` launcher does some kind of forking, when it wraps and I see that the processes get detached from the main spawner. When I try to check if `os.Getppid()` process still exists in the linux binary, it is not able to find it.

On windows, the process tree looks like this after spawning, notice the windows process that launched the entire tree

![image](https://github.com/user-attachments/assets/0a992132-5c79-4837-b59f-2251190bd3f6)

Upon closing electron, the windows native process exits properly `container-desktop-ssh-relay.exe`

But what I see happening is that the processes under it, get detached and move to window's root process

![image](https://github.com/user-attachments/assets/d91c5120-8b9d-468c-bda9-73dbf64093be)

The WSL linux golang program, is wrapped by `wsl.exe` at process `31112`

![image](https://github.com/user-attachments/assets/c4c4a2f8-e4bb-4be9-9dbf-7780c30f6258)

### What did you expect to see?

If the spawned program would be for example a native C based binary of `/usr/sbin/sshd` server (from openssh-server), started without running in the background, the exit process is proper and all the process tree gets killed.

I would expect the process tree to die properly.

**Comment by cherrymui** [comment]
Usually when a parent process exits, it doesn't necessarily kill child processes. Some specific programs, like sshd or shell, do this explicitly. Does a Windows process kill child processes by default? Does it reproduce if the child process is a native Windows process, instead of under WSL?

I'm not sure there is anything specific to Go.

cc @golang/windows

**Comment by iongion** [comment]
I have made this simple C program, simulating a long running daemon

```
#include <stdio.h>
#include <unistd.h>

int main() {
    printf("Hello, World!\n");
    while (1) {
        printf("Tack\n");
        sleep(1500);
        printf("Tick\n");
    }
    return 0;
}

```

Same code in golang

```
package main

import (
	"fmt"
	"time"
)

func main() {
	fmt.Println("Hello, World!")
	for {
		fmt.Println("Tack")
		time.Sleep(1500 * time.Millisecond)
		fmt.Println("Tick")
	}
}
```

Spawning in the native windows executable looks like this

```
	args := []string{
		"--distribution",
		"Ubuntu-24.04",
		"--exec",
		"./test-server"
	}
	relay := exec.CommandContext(ctx, "wsl.exe", args...)
	relay.SysProcAttr = &syscall.SysProcAttr{
	}
	relay.Stdout = os.Stdout
	relay.Stderr = os.Stderr
	if err := relay.Start(); err != nil {
		log.Fatalf("Error starting relay program: %v\n", err)
		return err
	}
``

- The C program generated running binary is properly removed / child processes & tree
- The golang program generated running binary is not, as in the screenshots above

**Comment by iongion** [comment]
[container-desktop-relay.zip](https://github.com/user-attachments/files/17346225/container-desktop-relay.zip)

Attached the real world example from https://container-desktop.com

To test, one needs Windows + WSL, golang, nodejs 20, steps

1. Build the relay programs `./relay-build.sh`
2. From a windows cmd / powershell terminal - Start the relay using `relay-test.cmd` - Important to use `node.exe` 

Notice what happens to the child processes after CTRL  + C - it gets detached as in the screenshots

**Comment by cherrymui** [comment]
Is it reproducible if the child program is a native program without WSL?
