### ISSUE TITLE
x/pkgsite: package removal request for github.com/OI4/oi4-oec-service-go

### ISSUE THREAD

**Issue by Weinschenk** [golang/go#69876]
Hi guys,

we changed our project from a workspace "back" to a regular module. We haven't yet published any stable release, but the v0.1.x are still there.

As the go.mod file of the workspace modules do not exist anymore, but only the single "root", I cannot add retract statements.

I kindly ask you, to remove the modules:
https://pkg.go.dev/github.com/OI4/oi4-oec-service-go/api
https://pkg.go.dev/github.com/OI4/oi4-oec-service-go/container
https://pkg.go.dev/github.com/OI4/oi4-oec-service-go/dnp
https://pkg.go.dev/github.com/OI4/oi4-oec-service-go/service

Regards and thanks a lot,
Thomas

**Comment by findleyr** [comment]
Done. Please allow a few hours to propagate.
