### ISSUE TITLE
x/pkgsite: package removal request for github.com/terenceodonoghue/golang

### ISSUE THREAD

**Issue by terenceodonoghue** [golang/go#69883]
### What is the path of the package that you would like to have removed?

github.com/terenceodonoghue/golang

### Are you the owner of this package?

Yes

### What is the reason that you could not retract this package instead?

I have published retractions and made the repo private, would like all packages + docs from `terenceodonoghue/golang` removed (including for latest version) from pkg.go.dev - packages were published accidentally due to my misunderstandings while learning how Go modules work.

Thank you! 🙏

**Comment by findleyr** [comment]
Done. Please allow a few hours to propagate.
