### ISSUE TITLE
golang.org/x/net: XML syntax error

### ISSUE THREAD

**Issue by abcbarryn** [golang/go#69886]
### Go version

go version go1.4.3 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GOARCH="amd64"
GOBIN="/usr/bin"
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/share/go/contrib"
GORACE=""
GOROOT="/usr/lib64/go"
GOTOOLDIR="/usr/lib64/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

### What did you do?

go get -v golang.org/x/net

### What did you see happen?

Fetching https://golang.org/x/net?go-get=1
Parsing meta tags from https://golang.org/x/net?go-get=1 (status code 200)
import "golang.org/x/net": parsing golang.org/x/net: XML syntax error on line 7: unexpected end element </head>
package golang.org/x/net: unrecognized import path "golang.org/x/net"

### What did you expect to see?

success download and install golang.org/x/net

**Comment by seankhliao** [comment]
that's not a version we support.

**Comment by abcbarryn** [comment]
Well gee, thanks for your help, NOT!
I tried to install the newest version of Go and it wouldn't compile and that issue was closed too! I see the kind of help and support I can expect from this project. :(

**Comment by ianlancetaylor** [comment]
@abcbarryn On this issue tracker please follow the [code of conduct](https://go.dev/conduct).  Please be respectful and polite.

To install from source, see https://go.dev/doc/install/source.
