### ISSUE TITLE
access: loong64 team for @sophie-zhao 

### ISSUE THREAD

**Issue by abner-chenc** [golang/go#69891]
Hi, 
   Please add @sophie-zhao  to the @golang/loong64   linux/loong64 team. She has contributed many CLs to linux/loong64.
   These are her commits: https://github.com/golang/go/commits?author=sophie-zhao

  Thanks!

**Comment by dmitshur** [comment]
Thanks. An invite has been sent, it will need to be accepted by @sophie-zhao.

**Comment by sophie-zhao** [comment]
Thanks. I have accepted the invite and joined the loong64 team.
