### ISSUE TITLE
x/tools/gopls:  "inline: corrupted reference %v" bug in golang.RemoveUnusedParameter

### ISSUE THREAD

**Issue by adonovan** [golang/go#69896]
```
#!stacks
"bug.Errorf" && "golang.inlineAllCalls:+98"
```
Issue created by [stacks](https://pkg.go.dev/golang.org/x/tools/gopls/internal/telemetry/cmd/stacks).

```go
		// Sanity check.
		if obj := refpkg.TypesInfo().ObjectOf(name); obj == nil ||
			obj.Name() != origDecl.Name.Name ||
			obj.Pkg() == nil ||
			obj.Pkg().Path() != string(pkg.Metadata().PkgPath) {
			return nil, bug.Errorf("cannot inline: corrupted reference %v", ref)
		}
```
This stack `u1wk7A` was [reported by telemetry](https://storage.googleapis.com/prod-telemetry-merged/2024-10-14.json):

- `gopls/bug`
- [`golang.org/x/tools/gopls/internal/util/bug.report:+35`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/util/bug/bug.go;l=109)
- [`golang.org/x/tools/gopls/internal/util/bug.Errorf:+2`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/util/bug/bug.go;l=61)
- [`golang.org/x/tools/gopls/internal/golang.inlineAllCalls:+98`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/golang/inline_all.go;l=145)
- [`golang.org/x/tools/gopls/internal/golang.rewriteCalls:+114`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/golang/change_signature.go;l=471)
- [`golang.org/x/tools/gopls/internal/golang.RemoveUnusedParameter:+81`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/golang/change_signature.go;l=124)
- [`golang.org/x/tools/gopls/internal/server.(*commandHandler).ChangeSignature.func1:+2`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/server/command.go;l=1338)
- [`golang.org/x/tools/gopls/internal/server.(*commandHandler).run.func2:+3`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/server/command.go;l=174)
- [`golang.org/x/tools/gopls/internal/server.(*commandHandler).run:+73`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/server/command.go;l=201)
- [`golang.org/x/tools/gopls/internal/server.(*commandHandler).ChangeSignature:+2`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/server/command.go;l=1334)
- [`golang.org/x/tools/gopls/internal/protocol/command.Dispatch:+39`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/protocol/command/command_gen.go;l=145)
- [`golang.org/x/tools/gopls/internal/server.(*server).ResolveCodeAction:+21`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/server/code_action.go;l=190)
- [`golang.org/x/tools/gopls/internal/protocol.serverDispatch:+46`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/protocol/tsserver.go;l=214)
- [`golang.org/x/tools/gopls/internal/lsprpc.(*streamServer).ServeStream.ServerHandler.func3:+5`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/protocol/protocol.go;l=160)
- [`golang.org/x/tools/gopls/internal/lsprpc.(*streamServer).ServeStream.handshaker.func4:+52`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/lsprpc/lsprpc.go;l=509)
- [`golang.org/x/tools/gopls/internal/protocol.Handlers.MustReplyHandler.func1:+2`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:internal/jsonrpc2/handler.go;l=35)
- [`golang.org/x/tools/gopls/internal/protocol.Handlers.AsyncHandler.func2.2:+3`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:internal/jsonrpc2/handler.go;l=103)
```
golang.org/x/tools/gopls@v0.16.2 go1.22.2 darwin/arm64 vscode (1)
```

**Comment by adonovan** [comment]
The failing assertion checks that each reference to the function or method of interest is a call to to a symbol with the same name and package as the original function. But the `References` algorithm returns implicit matches by joining with the "implements" relation, and these matches may come from arbitrary packages. So I think the assertion is overly strict.

**Comment by findleyr** [comment]
Thanks, that was indeed it, and I was able to reproduce.

Fix incoming.

**Comment by adonovan** [comment]
This stack `vmzEcA` was [reported by telemetry](https://storage.googleapis.com/prod-telemetry-merged/2025-01-27.json):

- `gopls/bug`
- [`golang.org/x/tools/gopls/internal/util/bug.report:+35`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/util/bug/bug.go;l=109)
- [`golang.org/x/tools/gopls/internal/util/bug.Errorf:+2`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/util/bug/bug.go;l=61)
- [`golang.org/x/tools/gopls/internal/golang.inlineAllCalls:+98`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/golang/inline_all.go;l=145)
- [`golang.org/x/tools/gopls/internal/golang.rewriteCalls:+114`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/golang/change_signature.go;l=471)
- [`golang.org/x/tools/gopls/internal/golang.RemoveUnusedParameter:+81`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/golang/change_signature.go;l=124)
- [`golang.org/x/tools/gopls/internal/server.(*commandHandler).ChangeSignature.func1:+2`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/server/command.go;l=1338)
- [`golang.org/x/tools/gopls/internal/server.(*commandHandler).run.func2:+3`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/server/command.go;l=174)
- [`golang.org/x/tools/gopls/internal/server.(*commandHandler).run:+73`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/server/command.go;l=201)
- [`golang.org/x/tools/gopls/internal/server.(*commandHandler).ChangeSignature:+2`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/server/command.go;l=1334)
- [`golang.org/x/tools/gopls/internal/protocol/command.Dispatch:+39`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/protocol/command/command_gen.go;l=145)
- [`golang.org/x/tools/gopls/internal/server.(*server).ResolveCodeAction:+21`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/server/code_action.go;l=190)
- [`golang.org/x/tools/gopls/internal/protocol.serverDispatch:+46`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/protocol/tsserver.go;l=214)
- [`golang.org/x/tools/gopls/internal/protocol.ServerHandler.func1:+5`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/protocol/protocol.go;l=160)
- [`golang.org/x/tools/gopls/internal/lsprpc.handshaker.func1:+52`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:gopls/internal/lsprpc/lsprpc.go;l=509)
- [`golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1:+2`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:internal/jsonrpc2/handler.go;l=35)
- [`golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2:+3`](https://cs.opensource.google/go/x/tools/+/gopls/v0.16.2:internal/jsonrpc2/handler.go;l=103)
```
golang.org/x/tools/gopls@v0.16.2 go1.20.7 darwin/arm64 vscode (1)
```
