### ISSUE TITLE
strconv: improve readability of `FormatFloat` formatting options in go doc

### ISSUE THREAD

**Issue by gazerro** [golang/go#69890]
In the documentation for the `FormatFloat` function, the list of formatting options (`'b'`, `'e'`, `'f'`, etc.) is clearer and easier to read when displayed on separate lines, as is done in the source documentation. However, go doc compresses them into a single line, making them harder to distinguish.

```
// The format fmt is one of
// 'b' (-ddddp±ddd, a binary exponent),
// 'e' (-d.dddde±dd, a decimal exponent),
// 'E' (-d.ddddE±dd, a decimal exponent),
// 'f' (-ddd.dddd, no exponent),
// 'g' ('e' for large exponents, 'f' otherwise),
// 'G' ('E' for large exponents, 'f' otherwise),
// 'x' (-0xd.ddddp±ddd, a hexadecimal fraction and binary exponent), or
// 'X' (-0Xd.ddddP±ddd, a hexadecimal fraction and binary exponent).
```
become:
> The format fmt is one of 'b' (-ddddp±ddd, a binary exponent), 'e' (-d.dddde±dd, a decimal exponent), 'E' (-d.ddddE±dd, a decimal exponent), 'f' (-ddd.dddd, no exponent), 'g' ('e' for large exponents, 'f' otherwise), 'G' ('E' for large exponents, 'f' otherwise), 'x' (-0xd.ddddp±ddd, a hexadecimal fraction and binary exponent), or 'X' (-0Xd.ddddP±ddd, a hexadecimal fraction and binary exponent).

**Comment by ianlancetaylor** [comment]
Want to send a patch?
