### ISSUE TITLE
x/pkgsite: package removal request for github.com/davidloubere/finance

### ISSUE THREAD

**Issue by davidloubere** [golang/go#69903]
Hello, I removed the Github repository "github.com/davidloubere/finance" (now available on Gitlab).
Can you please remove the related package listed at https://pkg.go.dev/github.com/davidloubere/finance?
Thanks you.

**Comment by adonovan** [comment]
I confirm that your GitHub userid matches the owner of that repo and have made the change. Please allow a few days for the configuration update to propagate.
