### ISSUE TITLE
runtime: os.OpenFile opens files (sometimes) in exclusive mode on windows/amd64 on tip

### ISSUE THREAD

**Issue by aarzilli** [golang/go#69902]
In Go 1.23 (and at least a few versions before it) opening a file twice for writing, was possible (and it continues to be possible on linux):

```
package main

import "os"

func must(err error) {
	if err != nil {
		panic(err)
	}
}

func main() {
	fh, err := os.CreateTemp("", "test-*")
	must(err)
	name := fh.Name()
	must(fh.Close())
	fh, err = os.OpenFile(name, os.O_APPEND|os.O_WRONLY|os.O_CREATE, 0660)
	must(err)
	fh2, err := os.OpenFile(name, os.O_APPEND|os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0660)
	must(err)
	must(fh.Close())
	must(fh2.Close())
}
```

On tip however this results in an Access is denied error:

```
panic: open Z:\buildAgent\temp\buildTmp\test-1396926860: Access is denied.
   
   goroutine 1 [running]:
   main.must(...)
     Z:/buildAgent/work/3aca8f960d346a9c/blah.go:7
   main.main()
     Z:/buildAgent/work/3aca8f960d346a9c/blah.go:19 +0x13d
   exit status 2
```

Furthermore even correcting the order of Open/Close will (sometimes? always?) result in the same Access is denied error, unless a sleep is introduced between the close and the successive open:

```
package main

import "os"

func must(err error) {
	if err != nil {
		panic(err)
	}
}

func main() {
	fh, err := os.CreateTemp("", "test-*")
	must(err)
	name := fh.Name()
	must(fh.Close())
	fh, err = os.OpenFile(name, os.O_APPEND|os.O_WRONLY|os.O_CREATE, 0660)
	must(err)
	must(fh.Close())
	fh2, err := os.OpenFile(name, os.O_APPEND|os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0660)
	must(err)
	must(fh2.Close())
}
```

It might have something to do with the flags being passed to OpenFile since the problem doesn't happen with the first OpenFile (which is also immediately successive to a Close on the same file). I have not bisected this problem but it was introduced between the 5th and the 10th of October.

**Comment by qmuntal** [comment]
Probably related to https://go-review.googlesource.com/c/go/+/619295. Will fix.

**Comment by qmuntal** [comment]
@aarzilli could you check if your issue is fixed on tip?

**Comment by aarzilli** [comment]
It does, thank you.
