### ISSUE TITLE
Command Runner not executing commands on SAVE nor UPLOAD

### ISSUE THREAD

**Issue by dro-ex** [golang/go#69918]
### Go version

Docker version

### Output of `go env` in your module/workspace:

```shell
n/a
```

### What did you do?

Added command to AFTER SAVE  and AFTER UPLOAD triggers. 

### What did you see happen?

Command not executed, but command words fine in shell

### What did you expect to see?

The command execcuted after the creation of a folder/file and after upload of code/file.

**Comment by dro-ex** [comment]
why closed?  AFTER_RENAME works fine - its just the SAVE  and UPLOAD commands that dont work - are these being removed

**Comment by seankhliao** [comment]
This doesn't appear to be an issue about Go. Please file issues with the appropriate project.
