### ISSUE TITLE
misc/wasm: `wasm_exec.js` missing after toolchain update

### ISSUE THREAD

**Issue by ericcornelissen** [golang/go#69989]
### Go version

go version go1.23.0 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/eric/.cache/go-build'
GOENV='/home/eric/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/eric/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/eric/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/home/eric/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.linux-amd64'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/home/eric/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.linux-amd64/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.23.0'
GODEBUG=''
GOTELEMETRY='on'
GOTELEMETRYDIR='/home/eric/.config/go/telemetry'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/eric/workspace/ades/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build283257350=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

I updated my Go toolchain version using the Go command's update functionality (I believe this happens automatically when using the `go` command when the Go version in `go.mod` doesn't match the current version) and then tried to copy the `wasm_exec.js` file - following <https://go.dev/wiki/WebAssembly> - to be able to run WASM compiled Go code in the browser.

### What did you see happen?

An error the `wasm_exec.js` file was not found:

```shell
$ cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" .
cp: cannot stat '/home/eric/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.linux-amd64/misc/wasm/wasm_exec.js': No such file or directory
```

if and only if I use a version of the `go` command from a toolchain update. I verified this error does not occur when Go was installed at `go version go1.23.0 linux/amd64` directly.

### What did you expect to see?

No error and the file is copied:

```shell
$ cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" .
```

(I know [the guide](https://go.dev/wiki/WebAssembly) says `cp "$(go env GOROOT)/lib/wasm/wasm_exec.js" .` - with `lib` instead of `misc` - but, at least on Go `go version go1.22.5 linux/amd64` and `go version go1.23.0 linux/amd64` only `misc` works.)

**Comment by ericcornelissen** [comment]
My bad, this is answered by #68024 

(perhaps the wording here will help other Unix users find the issue too).

**Comment by baldazi** [comment]
Hello!

I am facing the same issue, I don't know where to get the `wasm_exec.js` file.

Here's my go version : `go version go1.23.7 linux/amd64` 

When I try to copy the file is not located 
```bash
$ cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" .
cp: cannot stat '/usr/lib/golang/misc/wasm/wasm_exec.js': No such file or directory
```
```bash
$ ls $(go env GOROOT)
VERSION  api  bin  doc  go.env  lib  pkg  src

ls $(go env GOROOT)/lib
time
```

**Comment by ericcornelissen** [comment]
@baldazi it doesn't work until Go 1.24.0

**Comment by dc0d** [comment]
With `1.24.3` the command `cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" .` still fails (the file is not there).

There is a file `wasm_exec.html` in that location, which contains:

```
<!doctype html>
...
<html>

<head>
	...
</head>

<body>
	...
	<script src="../../lib/wasm/wasm_exec.js"></script>
	<script>
		...
	</script>

	<button onClick="run();" id="runButton" disabled>Run</button>
</body>

</html>
```

And we see these files there:
```
$ ls $(go env GOROOT)/lib/wasm/
go_js_wasm_exec		go_wasip1_wasm_exec	wasm_exec_node.js	wasm_exec.js
```

Will check if that one (`.../wasm_exec.js`) works as well.

**Comment by ericcornelissen** [comment]
> With `1.24.3` the command `cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" .` still fails (the file is not there).

@dc0d the correct location is `$(go env GOROOT)/lib/wasm/wasm_exec.js` (_lib_ instead of _misc_).

**Comment by carbon-starlight** [comment]
> > With `1.24.3` the command `cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" .` still fails (the file is not there).
> 
> [@dc0d](https://github.com/dc0d) the correct location is `$(go env GOROOT)/lib/wasm/wasm_exec.js` (_lib_ instead of _misc_).

Cannot find the file in neither of these locations

```
user@fedora:/usr/lib/golang$ ls $(go env GOROOT)/misc
ls: cannot access '/usr/lib/golang/misc': No such file or directory
```

```
user@fedora:/usr/lib/golang$ tree $(go env GOROOT)/lib
/usr/lib/golang/lib
└── time
    ├── mkzip.go
    ├── README
    ├── update.bash
    └── zoneinfo.zip
```

**Comment by seankhliao** [comment]
That's a packaging issue for whereever you installed Go from, because that's not a tree distributed by the Go project.

**Comment by nonspecialist** [comment]
> > > With `1.24.3` the command `cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" .` still fails (the file is not there).
> > 
> > 
> > [@dc0d](https://github.com/dc0d) the correct location is `$(go env GOROOT)/lib/wasm/wasm_exec.js` (_lib_ instead of _misc_).
> 
> Cannot find the file in neither of these locations
> 
> ```
> user@fedora:/usr/lib/golang$ ls $(go env GOROOT)/misc
> ls: cannot access '/usr/lib/golang/misc': No such file or directory
> ```
> 
> ```
> user@fedora:/usr/lib/golang$ tree $(go env GOROOT)/lib
> /usr/lib/golang/lib
> └── time
>     ├── mkzip.go
>     ├── README
>     ├── update.bash
>     └── zoneinfo.zip
> ```

In Fedora it appears that it's been included in the `golang-tests` package for some strange reason
