### ISSUE TITLE
cmd/link: emit LC_UUID for internal link on Mac

### ISSUE THREAD

**Issue by rsc** [golang/go#69987]
@presotto reports problems with "authorizing" programs to use network on his Mac (meaning the popups about "do you want to trust this program"). Specifically they don't seem to stick unless he uses "-ldflags=-linkmode=external". 

Comparing the `otool -l` outputs from an internal and external link, one difference is that the external link emits an LC_UUID, which could be what the Mac is using to identify the program to cache the saved authorization. It seems like maybe we should emit an LC_UUID in internal linking mode too. We should not generate one at random (that would break reproducible builds) but instead should use a hash of the output sections.

**Comment by cherrymui** [comment]
Dup of #68678?

**Comment by rsc** [comment]
Indeed, duplicate. Thanks. Interesting that gaby didn't think so.
