### ISSUE TITLE
x/tools/gopls: offer undeclared names in lexical completion

### ISSUE THREAD

**Issue by findleyr** [golang/go#69993]
This issue is extracted from #69980, where the request is to include undeclared (but used) names in lexical completion results.
We could do this by extracting such names from type errors (see also `gopls/internal/analysis/undeclaredname`).

I think we're much less likely to implement this feature than we are to offer the fix in #69980. Presumably it's much more important to help users fix their incorrect syntax, than it is to operate as though the syntax were valid. Putting in the unplanned milestone.

```
func _() {
  myvariable = 2
  foo(myv_) <-- offer 'myvariable' in lexical completion results here
}
```

**Comment by xzbdmw** [comment]
What I think is that by accepting illegal syntax for completion, some underline error mark would appear, and code actions can be used after confirming, without moving the cursor to where the error really occurs, is it acceptable? I can take a try then.

**Comment by findleyr** [comment]
@xzbdmw I think the tricky thing is defining the name in the lexical scope. Right now, gopls looks in the surrounding `types.Scope` to find available names. If the name is undefined due to the invalid initializer, it won't be available in the scope. So you'd need to either walk the syntax or look at type errors to guess what other names might be intended. While that's doable (see for example the `undeclaredname` analyzer), it's liable to be tricky, and the value added is not that high. In practice, the user will fix the invalid initializer before moving on to the next line.

So I think this feature is relatively tricky, and not very impactful. Therefore, it is unlikely to be prioritized.
In fact, I think this is so infeasible that we should close this issue: I don't think we'd accept this feature as a contribution.

**Comment by xzbdmw** [comment]
That’s fair, the alternative would be using buffer completion source for this .
