### ISSUE TITLE
The RSS is releasing too slowly, causing the program oom

### ISSUE THREAD

**Issue by lojies** [golang/go#69996]
### Go version

go1.22.5

### Output of `go env` in your module/workspace:

```shell
GOARCH=amd64
```

### What did you do?

In the environment, many Go programs see an increase in RSS memory usage that does not release until there is a significant rise in memory usage, after which it decreases significantly. This means that if calls are made continuously for a period of time, memory will keep growing and eventually trigger OOM (Out of Memory). However, pprof analysis shows that the in-use memory in the heap is actually much smaller than the RSS.

### What did you see happen?

Without any calls, the RSS remains at a high level, and the garbage collector does not seem to reclaim the unused memory.

### What did you expect to see?

rss can be release quickly and no oom

**Comment by lojies** [comment]
If you need any environment-related information, I can provide it. The current environment is stable, and this issue is reproducible.

**Comment by seankhliao** [comment]
https://tip.golang.org/doc/gc-guide

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
