### ISSUE TITLE
net/http: short writes with FileServer on macos

### ISSUE THREAD

**Issue by a-palchikov** [golang/go#70000]
### Go version

go version go1.23.2 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/user/Library/Caches/go-build'
GOENV='/user/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/user/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/user/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/user/dev/go/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/user/dev/go/go/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.23.2'
GODEBUG='httpmuxgo121=0'
GOTELEMETRY='local'
GOTELEMETRYDIR='/user/Library/Application Support/go/telemetry'
GCCGO='gccgo'
GOARM64='v8.0'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK='/user/dev/path/to/go.work'
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/_y/<snip>/T/go-build<id>=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

I have a small webserver that serves static files in a testing setup.

### What did you see happen?

I'm on go 1.23.2 on macos 14.7 and I'm having issues with the stdlib http.FileServer.
After much of poking around, I found that with the BSD sendfile implementation in internal/poll/sendfile_bsd.go having
the `maxSendfileSize` set to 4MiB is causing all large file transfers to fail. For example, the following is the curl failure:

```
...
{ [512 bytes data]
* transfer closed with 361300436 bytes remaining to read
  1  350M    1 5567k    0     0  80.7M      0  0:00:04 --:--:--  0:00:04 81.1M
* Closing connection
curl: (18) transfer closed with 361300436 bytes remaining to read
```
so all requests are failing with short writes.

If I update the `maxSendfileSize` to maximum (adopting the change from this [commit](https://github.com/golang/go/commit/970b1c042cddb5f944d3db1cc2c3d87a3ffabe52#diff-9625cc521fee6a84cb231482728d831c1ea4818dd5247459cf984762e337d4c0L13)) I don't observe any failures.

Just setting the `maxSendfileSize` feels like a hack though (maybe I'm wrong) so I'd appreciate any hints on this behavior.

### What did you expect to see?

The `sendfile` API should be able to send files in their entirety.

**Comment by ianlancetaylor** [comment]
Can you show us code that we can use the replicate the problem?  Thanks.

CC @golang/darwin

**Comment by ianlancetaylor** [comment]
CC @panjf2000

**Comment by a-palchikov** [comment]
There's nothing special to it, really:
```go
m := http.NewServeMux()
m.Handle("/large-payload/", http.StripPrefix("/large-payload/", http.FileServer(http.Dir("path/to/large-payload"))))
```
it looks at a directory with a bunch of numeric files all 350MiB in size:
```sh
$ tree path/to/large-payload | head -n3
src/test/resources/large-payload
├── 1
├── 10
...
```
and I simply hit the server with:
```sh
curl localhost:44444/large-payload/1 -o ./test
```

**Comment by panjf2000** [comment]
Can we get the error returned by your server-side? This 970b1c042cddb5f944d3db1cc2c3d87a3ffabe52 will ship in Go1.24.

**Comment by a-palchikov** [comment]
@panjf2000 I'll gladly comply if you can narrow the context. On high-level it returns the short amount of bytes written here:

https://github.com/golang/go/blob/ed07b321aef7632f956ce991dd10fdd7e1abd827/src/net/http/fs.go#L424

From what I observed, there's no error, e.g.:

https://github.com/golang/go/blob/ed07b321aef7632f956ce991dd10fdd7e1abd827/src/net/sendfile_unix_alt.go#L77

returns with 
```
written=4194304, err=<nil>, handled=true
```
the number of bytes written fluctuates, e.g.:
```
written=12524536, err=<nil>, handled=true
```
the main point is that it's a short write.

Please let me know if you need more details.

**Comment by jiahongli18** [comment]
> Can we get the error returned by your server-side? This [970b1c0](https://github.com/golang/go/commit/970b1c042cddb5f944d3db1cc2c3d87a3ffabe52) will ship in Go1.24.

As @a-palchikov mentioned, we don't see any errors from the server itself. The observation from the client is a partially fetched file.

**Comment by prattmic** [comment]
cc @neild

**Comment by a-palchikov** [comment]
This seems to do the trick:

```
diff --git a/src/internal/poll/sendfile_bsd.go b/src/internal/poll/sendfile_bsd.go
index 669df94cc1..35338730aa 100644
--- a/src/internal/poll/sendfile_bsd.go
+++ b/src/internal/poll/sendfile_bsd.go
@@ -47,7 +47,7 @@ func SendFile(dstFD *FD, src int, pos, remain int64) (written int64, err error,
                // don't implement sendfile), and other errors.
                // We should end the loop when there is no error
                // returned from sendfile(2) or it is not a retryable error.
-               if err != syscall.EAGAIN {
+               if err != nil && err != syscall.EAGAIN {
                        break
                }
                if err = dstFD.pd.waitWrite(dstFD.isFile); err != nil {
```

**Comment by ianlancetaylor** [comment]
@a-palchikov Thanks.  Looks like we need something similar in the other sendfile implementations as well.

**Comment by jonjohnsonjr** [comment]
Just wanted to chime in that this exhibits worse behavior on the client side when uploading large files. I have a client that will hang indefinitely on macOS pretty regularly, which I believe is due to this issue, as it uses an `os.File` as the `Body` of a request.

This was a bit of a [heisenbug](https://en.wikipedia.org/wiki/Heisenbug) for me because when I tried wrapping the `os.File` in another struct to observe what was going on, the problem disappeared. That was enough of a clue to lead me here (and also serve as a workaround until it's fixed).

Thanks for uncovering this!

**Comment by ianlancetaylor** [comment]
@gopherbot Please open backport issues.

This causes inexplicable and difficult to avoid failures on BSD systems.  We should backport the fix.

**Comment by panjf2000** [comment]
> This seems to do the trick:
> 
> ```
> diff --git a/src/internal/poll/sendfile_bsd.go b/src/internal/poll/sendfile_bsd.go
> index 669df94cc1..35338730aa 100644
> --- a/src/internal/poll/sendfile_bsd.go
> +++ b/src/internal/poll/sendfile_bsd.go
> @@ -47,7 +47,7 @@ func SendFile(dstFD *FD, src int, pos, remain int64) (written int64, err error,
>                 // don't implement sendfile), and other errors.
>                 // We should end the loop when there is no error
>                 // returned from sendfile(2) or it is not a retryable error.
> -               if err != syscall.EAGAIN {
> +               if err != nil && err != syscall.EAGAIN {
>                         break
>                 }
>                 if err = dstFD.pd.waitWrite(dstFD.isFile); err != nil {
> ```
> 
> The sequence of events is like following:
> 
> ```
> n= 1408044 , err= resource temporarily unavailable
> n= 434176 , err= resource temporarily unavailable
> n= 4194304
> ```
> 
> given the series of EAGAIN followed by no error, when it reaches the limit (4MiB), it bails out.

Thanks for the details! I think I've found the root cause and you would get rid of this issue after adding the below changes to your source code of go1.23.2:
```diff
diff --git a/src/internal/poll/sendfile_bsd.go b/src/internal/poll/sendfile_bsd.go
index f2d13e1069..1f9c42253a 100644
--- a/src/internal/poll/sendfile_bsd.go
+++ b/src/internal/poll/sendfile_bsd.go
@@ -35,12 +35,16 @@ func SendFile(dstFD *FD, src int, pos, remain int64) (written int64, err error,
 		if int64(n) > remain {
 			n = int(remain)
 		}
+		m := n
 		pos1 := pos
 		n, err = syscall.Sendfile(dst, src, &pos1, n)
 		if n > 0 {
 			pos += int64(n)
 			written += int64(n)
 			remain -= int64(n)
+			if n == m {
+				continue
+			}
 		}
 		if err == syscall.EINTR {
 			continue
```

Please try it out and let me know if it works, thanks! @a-palchikov

**Comment by a-palchikov** [comment]
@panjf2000 Yes, it works as well and is short-circuiting the wait write (which I assume is only necessary when handling the EAGAIN). Thanks!

**Comment by Re2906** [comment]
> ### Go version
> 
> go version go1.23.2 darwin/arm64
> 
> ### Output of `go env` in your module/workspace:
> 
> ```shell
> GO111MODULE=''
> GOARCH='arm64'
> GOBIN=''
> GOCACHE='/user/Library/Caches/go-build'
> GOENV='/user/Library/Application Support/go/env'
> GOEXE=''
> GOEXPERIMENT=''
> GOFLAGS=''
> GOHOSTARCH='arm64'
> GOHOSTOS='darwin'
> GOINSECURE=''
> GOMODCACHE='/user/go/pkg/mod'
> GONOPROXY=''
> GONOSUMDB=''
> GOOS='darwin'
> GOPATH='/user/go'
> GOPRIVATE=''
> GOPROXY='https://proxy.golang.org,direct'
> GOROOT='/user/dev/go/go'
> GOSUMDB='sum.golang.org'
> GOTMPDIR=''
> GOTOOLCHAIN='auto'
> GOTOOLDIR='/user/dev/go/go/pkg/tool/darwin_arm64'
> GOVCS=''
> GOVERSION='go1.23.2'
> GODEBUG='httpmuxgo121=0'
> GOTELEMETRY='local'
> GOTELEMETRYDIR='/user/Library/Application Support/go/telemetry'
> GCCGO='gccgo'
> GOARM64='v8.0'
> AR='ar'
> CC='clang'
> CXX='clang++'
> CGO_ENABLED='1'
> GOMOD='/dev/null'
> GOWORK='/user/dev/path/to/go.work'
> CGO_CFLAGS='-O2 -g'
> CGO_CPPFLAGS=''
> CGO_CXXFLAGS='-O2 -g'
> CGO_FFLAGS='-O2 -g'
> CGO_LDFLAGS='-O2 -g'
> PKG_CONFIG='pkg-config'
> GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/_y/<snip>/T/go-build<id>=/tmp/go-build -gno-record-gcc-switches -fno-common'
> ```
> 
> 
> ### What did you do?
> 
> I have a small webserver that serves static files in a testing setup.
> 
> ### What did you see happen?
> 
> I'm on go 1.23.2 on macos 14.7 and I'm having issues with the stdlib http.FileServer.
> After much of poking around, I found that with the BSD sendfile implementation in internal/poll/sendfile_bsd.go having
> the `maxSendfileSize` set to 4MiB is causing all large file transfers to fail. For example, the following is the curl failure:
> 
> ```
> ...
> { [512 bytes data]
> * transfer closed with 361300436 bytes remaining to read
>   1  350M    1 5567k    0     0  80.7M      0  0:00:04 --:--:--  0:00:04 81.1M
> * Closing connection
> curl: (18) transfer closed with 361300436 bytes remaining to read
> ```
> so all requests are failing with short writes.
> 
> If I update the `maxSendfileSize` to maximum (adopting the change from this [commit](https://github.com/golang/go/commit/970b1c042cddb5f944d3db1cc2c3d87a3ffabe52#diff-9625cc521fee6a84cb231482728d831c1ea4818dd5247459cf984762e337d4c0L13)) I don't observe any failures.
> 
> Just setting the `maxSendfileSize` feels like a hack though (maybe I'm wrong) so I'd appreciate any hints on this behavior.
> 
> 
> ### What did you expect to see?
> 
> The `sendfile` API should be able to send files in their entirety.

**Comment by Re2906** [comment]
> ### Go version
> 
> go version go1.23.2 darwin/arm64
> 
> ### Output of `go env` in your module/workspace:
> 
> ```shell
> GO111MODULE=''
> GOARCH='arm64'
> GOBIN=''
> GOCACHE='/user/Library/Caches/go-build'
> GOENV='/user/Library/Application Support/go/env'
> GOEXE=''
> GOEXPERIMENT=''
> GOFLAGS=''
> GOHOSTARCH='arm64'
> GOHOSTOS='darwin'
> GOINSECURE=''
> GOMODCACHE='/user/go/pkg/mod'
> GONOPROXY=''
> GONOSUMDB=''
> GOOS='darwin'
> GOPATH='/user/go'
> GOPRIVATE=''
> GOPROXY='https://proxy.golang.org,direct'
> GOROOT='/user/dev/go/go'
> GOSUMDB='sum.golang.org'
> GOTMPDIR=''
> GOTOOLCHAIN='auto'
> GOTOOLDIR='/user/dev/go/go/pkg/tool/darwin_arm64'
> GOVCS=''
> GOVERSION='go1.23.2'
> GODEBUG='httpmuxgo121=0'
> GOTELEMETRY='local'
> GOTELEMETRYDIR='/user/Library/Application Support/go/telemetry'
> GCCGO='gccgo'
> GOARM64='v8.0'
> AR='ar'
> CC='clang'
> CXX='clang++'
> CGO_ENABLED='1'
> GOMOD='/dev/null'
> GOWORK='/user/dev/path/to/go.work'
> CGO_CFLAGS='-O2 -g'
> CGO_CPPFLAGS=''
> CGO_CXXFLAGS='-O2 -g'
> CGO_FFLAGS='-O2 -g'
> CGO_LDFLAGS='-O2 -g'
> PKG_CONFIG='pkg-config'
> GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/_y/<snip>/T/go-build<id>=/tmp/go-build -gno-record-gcc-switches -fno-common'
> ```
> 
> 
> ### What did you do?
> 
> I have a small webserver that serves static files in a testing setup.
> 
> ### What did you see happen?
> 
> I'm on go 1.23.2 on macos 14.7 and I'm having issues with the stdlib http.FileServer.
> After much of poking around, I found that with the BSD sendfile implementation in internal/poll/sendfile_bsd.go having
> the `maxSendfileSize` set to 4MiB is causing all large file transfers to fail. For example, the following is the curl failure:
> 
> ```
> ...
> { [512 bytes data]
> * transfer closed with 361300436 bytes remaining to read
>   1  350M    1 5567k    0     0  80.7M      0  0:00:04 --:--:--  0:00:04 81.1M
> * Closing connection
> curl: (18) transfer closed with 361300436 bytes remaining to read
> ```
> so all requests are failing with short writes.
> 
> If I update the `maxSendfileSize` to maximum (adopting the change from this [commit](https://github.com/golang/go/commit/970b1c042cddb5f944d3db1cc2c3d87a3ffabe52#diff-9625cc521fee6a84cb231482728d831c1ea4818dd5247459cf984762e337d4c0L13)) I don't observe any failures.
> 
> Just setting the `maxSendfileSize` feels like a hack though (maybe I'm wrong) so I'd appreciate any hints on this behavior.
> 
> 
> ### What did you expect to see?
> 
> The `sendfile` API should be able to send files in their entirety.

**Comment by ldemailly** [comment]
is this a regression or has been bugged for a long time? ie what is the range of go versions with that issue?

**Comment by a-palchikov** [comment]
I believe it was introduced in [this](https://github.com/golang/go/commit/faf2a8416a1ab933918e3c5091c905194126b60c) commit so affected only the 1.23 release.
