### ISSUE TITLE
x/pkgsite: package removal request for https://github.com/mr-shifu/mpc-lib

### ISSUE THREAD

**Issue by hnamzian** [golang/go#70044]
I'm the author of this repository and this repo is private from now on and I'm kindly ask you to remove all versions of this package

**Comment by seankhliao** [comment]
We need proof of ownership over the repo/account for removal. Can you please demonstrate ownership?

**Comment by hnamzian** [comment]
I can commit to the repository and make the repo public for a short time. is that good or you mind another way?

**Comment by adonovan** [comment]
Yep, that works. Thanks.

**Comment by hnamzian** [comment]
a temporary repo is created with file named proof
https://github.com/mr-shifu/mpc-lib/tree/proof-of-ownership-to-remove-pkg
please take a look

**Comment by adonovan** [comment]
Thanks. Please allow a few days for the configuration change to propagate.

**Comment by hnamzian** [comment]
thank you
can I make the repo private again?
