### ISSUE TITLE
vet: Enable multiple linters with -vettool

### ISSUE THREAD

**Issue by sivchari** [golang/go#70041]
### Proposal Details

Currently, when we want to run multiple original linters, we have to run in each with -vettool. So I want the feature that we can run multiple linters at once like -vettools.
What do you think ? Thanks.

**Comment by seankhliao** [comment]
if you need to invoke multiple analysis passes, you should be using https://pkg.go.dev/golang.org/x/tools@v0.26.0/go/analysis/multichecker
