### ISSUE TITLE
go/printer: formats anonymous interfaces and structs differently.

### ISSUE THREAD

**Issue by remyoudompheng** [golang/go#7004]
<pre>What steps will reproduce the problem?
1. Format:

package main

var S struct{ F string }
var I interface { F() string }

What is the expected output? What do you see instead?

expected:

Either

package main

var S struct{ F string }
var I interface { F() string }

Or:

package main

var S struct{
    F string
}
var I interface {
    F() string
}

but got:

package main

var S struct{ F string }
var I interface {
    F() string
}

Please use labels and text to provide additional information.</pre>

**Comment by jimmyfrasche** [comment]
This was fixed in Go 1.10

**Comment by ianlancetaylor** [comment]
Thanks, closing.
