### ISSUE TITLE
x/telemetry: temporarily downgrade go requirement to go1.21

### ISSUE THREAD

**Issue by hyangah** [golang/go#70056]
Adding golang.org/x/telemetry to Delve's dependency ([https://github.com/go-delve/delve/issues/3815](https://github.com/go-delve/delve/issues/3815))
resulted in Go version requirement change in Delve's go.mod because golang.org/x/telemetry@latest
requires go1.22.0. Delve had been operating with a wider version support policy (3 latest go versions) for a while.
So this needs extra discussion in Delve community.

We need [CL 616396](https://go.dev/cl/616396) but that is past x/telemetry/go.mod go version update.
Can we temporarily revert go.mod version update change so delve can pick up?
([CL 622735](https://go.dev/cl/622735))

Alternatively, can we defer the version bump in x/telemetry until it's really needed?
Looks like x/sys and x/sync are left with older go versions.
We can also consider removing dependency on x/mod.

cc @golang/telemetry

**Comment by adonovan** [comment]
Unfortunately that won't be so simple because the x/tools repo has change a lot recently under the assumption that go1.22 is the minimum version.  It might be easier to prepare a branch of x/telemetry that has whatever delve needs and for delve's go.mod file to use a replace directive that names this branch.

**Comment by hyangah** [comment]
@adonovan x/telemetry does not have dependency on x/tools. I'd say, x/telemetry should have minimal dependencies. Also, if we want to use Go telemetry to monitor the usage of Go versions, I think it makes more sense to avoid requiring latest go versions to avoid selection bias. 

If you are concerned about Delve's existing dependency on x/tools, Delve does not need the latest version of x/tools module. The dependencies are mostly coming from their code generation scripts or tests. Unfortunately, Go supports only one build graph and mixes tools/tests dependencies. Otherwise, there is no reason that delve should require the latest x/tools that moves the go version requirements as well.

**Comment by hyangah** [comment]
@findleyr BTW, I also noticed that not having a tag prevents the Go command from picking the latest version of x/telemetry module that supports Go 1.N correctly. Should we start tagging x/telemetry, too?

**Comment by adonovan** [comment]
> I don't follow. x/telemetry doesn't require x/tools -- only x/sync and x/sys, both of which are on 1.18.

Er, quite right, never mind me.

**Comment by hyangah** [comment]
Change in delve was submitted. 
CL 626357 will change the go version back to 1.22.0.
