### ISSUE TITLE
encoding/json: json.Encoder#Encode and json.Marshal gives different outputs

### ISSUE THREAD

**Issue by otaxhu** [golang/go#70068]
### Go version

go playground 1.23

### Output of `go env` in your module/workspace:

```shell
# go playground environment
```

### What did you do?

https://go.dev/play/p/c9Sgv-KJzku

Encoded the same message using `json.NewEncoder(buffer).Encode(msg)` and `json.Marshal(msg)` and then compared both outputs.

### What did you see happen?

The comparation gave false, `json.Marshal()` doesn't append a newline, `.Encode()` does, I don't know which one should be correct.

### What did you expect to see?

I really don't know what should be the correct output, I expected to see the same output in both functions.

**Comment by seankhliao** [comment]
both are working as intended.
