### ISSUE TITLE
x/pkgsite: package removal request for github.com/iton0/hkup

### ISSUE THREAD

**Issue by iton0** [golang/go#70072]
Made some errors with the semantic versioning and would like to delete package from pkg.go.dev and restart. the github repo has been deleted

**Comment by seankhliao** [comment]
removal only hides the generated documentation. There is no way for you to restart semver or reuse any previously published versions due to the sumdb

**Comment by iton0** [comment]
could i rename from hkup to HkUp and effectively "restart"

**Comment by seankhliao** [comment]
maybe, if sumdb hasn't seen it before. go modules are case sensitive, but GitHub is not so if you query for that now, it'll get tracked.

**Comment by iton0** [comment]
I was able to do it since i deleted the old git repo and created a new one with HkUp as the name. @seankhliao thank you for your quick response and help; I appreciate it!

**Comment by adonovan** [comment]
I confirm that the requester matches the repo, and have remove the module from pkgsite. Please allow a few days for the configuration change to propagate.
