### ISSUE TITLE
how build 16kb sdk for android app?

### ISSUE THREAD

**Issue by shiweigang789** [golang/go#70075]
how build 16kb sdk for android app? 
How to set compilation parameters？

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by 250king** [comment]
Are you sure it isn't project self problem that no support 16kb paging? If not please show the document.
I have the same problem about 16kb paging and googled it but I can't find any answers (

**Comment by 250king** [comment]
https://github.com/ProtonMail/gopenpgp/issues/300
https://github.com/2dust/AndroidLibXrayLite/issues/68

**Comment by 250king** [comment]
https://github.com/ProtonMail/gopenpgp/issues/300#issuecomment-2503591095

**Comment by SuzukiHonoka** [comment]
> [ProtonMail/gopenpgp#300 (comment)](https://github.com/ProtonMail/gopenpgp/issues/300#issuecomment-2503591095)

Great work! Many thanks!
