### ISSUE TITLE
x/sys/windows: get process ids from named pipes

### ISSUE THREAD

**Issue by MOHANKUMAR-IT** [golang/go#70086]
### Proposal Details

 GetNamedPipeClientProcessID and GetNamedPipeServerProcessID functions to get proccess id by providing named pipe handles by using modkernel32 dll.
 new access level PROCESS_ALL_ACCESS for windows.OpenProces function  .

**Comment by ianlancetaylor** [comment]
Thanks.  We don't need a proposal to add simple wrappers of existing Windows functions.  Taking this out of the proposal process.
