### ISSUE TITLE
x/build/cmd/watchflakes: currently in a CrashLoopBackOff state

### ISSUE THREAD

**Issue by cagedmantis** [golang/go#70091]
Watchflakes is continuously crashing. 

`watchflakes-deployment-68796dfdb7-th9zv           0/1     CrashLoopBackOff   986 (3m28s ago)   15d`

The last logged item is:
`watchflakes: 2024/10/29 17:21:46 repo mismatch: tools go https://ci.chromium.org/b/8733044805650708721`

@golang/release

**Comment by dmitshur** [comment]
The input of the LUCI [build 8733044805650708721](https://ci.chromium.org/b/8733044805650708721) is `https://go.googlesource.com/tools/+/889abb17e125bb0f5d8de61bb80ef15fbe2a130d`, which is indeed a revision in x/tools, yet the builder "gotip-..." is for the main Go repo, not x/tools.

It's also the very build of that builder – maybe it was triggered manually and the "tools" part of revision was intended to be "go". After all x/tools doesn't have a commit with that ID, but the main Go repo [does](https://go.googlesource.com/tools/+/889abb17e125bb0f5d8de61bb80ef15fbe2a130d). The second build's revision is in the right repo. CC @mknyszek.

In any case, it seems watchflakes can handle this case of a strange build (mismatch of project between builder definition and revision) by skipping over the build. It's probably not possible to do anything more in the general case.

**Comment by cagedmantis** [comment]
I deployed a version which ignores the mismatch case. I'm only seeing two CLs where this is an issue:
```
watchflakes: 2024/10/29 19:10:22 repo mismatch: tools go https://ci.chromium.org/b/8733044805650708721
watchflakes: 2024/10/29 19:10:22 repo mismatch: tools go https://ci.chromium.org/b/8733044811246345153
```
