### ISSUE TITLE
access: may-start-trybots

### ISSUE THREAD

**Issue by limeidan** [golang/go#70120]
Hi, 

I am a member of the [golang/loong64](https://github.com/orgs/golang/teams/loong64) . Currently, loong64 has accumulated a lot of unmerged CLs. In order to verify CLs of loong64 faster, I would like to request the "may-start-trybots" access for my self. This is my account: [limeidan@loongson.cn](mailto:limeidan@loongson.cn)

See https://go.dev/wiki/GerritAccess#running-trybots-may-start-trybots

Thanks.

**Comment by mauri870** [comment]
cc @golang/release

**Comment by cagedmantis** [comment]
Hi Meidan,

Thank you for your contributions, and for requesting trybot access! I've added you to the may-start-trybots group, so you should be able to do so now.

As you've probably seen at https://go.dev/wiki/GerritAccess#running-trybots-may-start-trybots, please be sure to skim CLs before starting a trybot run.

Let us know if you have any questions or issues with it, and thanks again!

**Comment by To-devgoy** [comment]
https://github.com/golang/go/issues/70176#issuecomment-2453304912
