### ISSUE TITLE
proposal: Shall we set the capacity of a list of byte or rune initialized by a string to the length of the string?

### ISSUE THREAD

**Issue by Fenardle** [golang/go#70158]
### Proposal Details

In the following code:
```
s := "a"
sList := []byte(s)
fmt.Println(cap(sList))
```
the capacity of sList would be 8, which would cause unexpected output for operations such as:
`sList[:5]`

therefore, shall we set the capacity to exactly the length of s?

**Comment by seankhliao** [comment]
see #65708
