### ISSUE TITLE
cmd/compile: internal compiler error with 2 _ labels

### ISSUE THREAD

**Issue by leabit** [golang/go#70175]
### Go version

Go 1.23

### Output of `go env` in your module/workspace:

```shell
/
```

### What did you do?

Playground: https://go.dev/play/p/Qjo8Uh4a4eL

```go
package main

func f() {
_:

_:
}

func main() {
	f()
}

```

### What did you see happen?

./prog.go:10:3: internal compiler error: label ~_·1 missing tag

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new

### What did you expect to see?

To work without errors.

**Comment by leabit** [comment]
Similar, but not the same as the #52278. It now works as expected in that case, but not in the one I provided.

**Comment by zigo101** [comment]
Since v1.18.

**Comment by cuonglm** [comment]
> Similar, but not the same as the #52278. It now works as expected in that case, but not in the one I provided.

The reason is that `_` was mangled during inlining, causing the check for blank node failed.
