### ISSUE TITLE
Proposal: Design and Naming Convention

### ISSUE THREAD

**Issue by henryas** [golang/go#70193]
### Proposal Details

Hi,

I think there is a need for a design and naming convention for Go. Preferably, it needs to be simple and short so that people can easily remember them in their head. Here are some of my suggestions, but feel free to add to it.

**Naming Guide**
1. **Async Suffix**: For a function or a method that is non-blocking, where it spawns one or more goroutines and returns immediately without waiting for the operation to complete, it should have the Async suffix. For instance, in the _os/exec_ package, we have _Cmd.Run_ for blocking and _Cmd.Start_ for non-blocking. Applying this rule, we should have _Cmd.Run_ and _Cmd.RunAsync_.
2. **Safe Prefix**: For a struct that is concurrent safe, it should have a Safe prefix. I initially thought the prefix should be applied to the struct's name. For instance, in _sync_ package we have the concurrent safe _Map_. Applying this rule, it should be _SafeMap_. In this case, all methods in _SafeMap_ are deemed to be concurrent safe without needing the apply the prefix to its methods. 
   However, since Go has dynamic interface and there may be interface whose implementation must be concurrent safe, it is better to apply the prefix to the method's name. For example,
   ````
   type SafeWriter interface {
      SafeWrite(content []byte) (int, error)
   }

   func DoWork(writer SafeWriter, args any) error {
      // use writer in multiple goroutines
   }
   ````
   After throwing interface into the mix, I now think it is better to apply the prefix to the method's name instead of the struct's name. It is simpler and provide better interoperability with interface, in case anyone needs to get an interface out of your existing implementation.

**Design Guide**
1. **Resource Release Pattern**
    For a function or a method that requires a resource to be released, it should follow the following pattern:
    ````
    func GetResource(arg string) (res *Resource, closer func()) {
          // implementation
    } 

    // usage
    res, closer := GetResource("my_resource")
    defer closer()
    ````
    The key idea here is the _closer_ function. The _closer_ function provides a reminder to the caller that there is a resource that needs to be released after the caller is done with all this. The caller can use the _closer_ function when done, or the _Resource.Close_ method. In fact, the _closer_ function may indirectly call the _Resource.Close_. The _Resource.Close_ method should be safe for multiple calls, and it will be invoked only once. It isn't my original idea, but I have found it useful and used it in my work. Read more about it here: https://medium.com/@griffinish/golang-acquire-and-release-pattern-1796f0d2173d

That is all from me, but feel free to add to it. I am sure after using Go for a while you may come across useful things that you wish other people would adhere to it so that there is a certain standardization across libraries.

Thanks

Henry

**Comment by ianlancetaylor** [comment]
Thanks, but this is not the kind of thing we use the proposal process for.  I'm going to close out this issue.

This seems more like a blog post.  It does not seem like something that we are likely to adopt in the Go standard library.
