### ISSUE TITLE
x/pkgsite: package removal request for https://pkg.go.dev/github.com/apleshkov/tmtr/cli

### ISSUE THREAD

**Issue by apleshkov** [golang/go#70216]
hi! published this doc accidentally, remove it please

**Comment by apleshkov** [comment]
and this one too: https://pkg.go.dev/github.com/apleshkov/tmtr/tmtr, if it's ok in the same issue

**Comment by apleshkov** [comment]
the `cli` package is meant to be internal, so the doc is redundant (TBH i don't  understand how it has been published at all, cause there're other internal packages and they're unpublished, MB that's because `cli` is used in the main package)

**Comment by adonovan** [comment]
> the cli package is meant to be internal, so the doc is redundant 

If you publish the code on GitHub, it is likely to end up in the in the module mirror corpus. The doc being redundant is not a compelling reason for us to remove it. I suggest you just ignore it.

> (TBH i don't understand how it has been published at all, cause there're other internal packages and they're unpublished, MB that's because cli is used in the main package)

The pkg.go.dev index is based on the set of modules ever requested (through the `go` command) from the public Go module mirror.

**Comment by apleshkov** [comment]
> If you publish the code on GitHub, it is likely to end up in the in the module mirror corpus. The doc being redundant is not a compelling reason for us to remove it. I suggest you just ignore it.

i see, that's fine :)
> The pkg.go.dev index is based on the set of modules ever requested (through the go command) from the public Go module mirror.

thanks for the clarification! wasn't obvious for me
