### ISSUE TITLE
`go mod tidy` tries to download local package

### ISSUE THREAD

**Issue by lorypelli** [golang/go#70227]
### Go version

1.23.2

### Output of `go env` in your module/workspace:

```shell
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\<username>\AppData\Local\go-build
set GOENV=C:\Users\<username>\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\<username>\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\<username>\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.23.2
set GODEBUG=
set GOTELEMETRY=off
set GOTELEMETRYDIR=C:\Users\<username>\AppData\Roaming\go\telemetry
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\Progetti\server\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\MASSIM~1\AppData\Local\Temp\go-build4023307547=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

I have a go module that is called `github.com/lorypelli/server` but when I do `go mod tidy` it tries to fetch `github.com/lorypelli/server/frontend` even if the `frontend` package of the module is local since the entire module is local

### What did you see happen?

```
go: finding module for package github.com/lorypelli/server/frontend
go: github.com/lorypelli/server/pkg imports
       github.com/lorypelli/server/frontend: no matching versions for query "latest"
```

you can see in https://github.com/lorypelli/server latest actions are failing because of this...

### What did you expect to see?

it shouldn't try to require local modules...

**Comment by lorypelli** [comment]
but it happens only with github actions, on windows it doesn't

**Comment by seankhliao** [comment]
you don't have a go package there https://github.com/lorypelli/server/tree/main/frontend

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
