### ISSUE TITLE
cmd/compile: linux/mips fails to make.bash with "internal compiler error: panic: runtime error: index out of range [0] with length 0"

### ISSUE THREAD

**Issue by dmitshur** [golang/go#70248]
From https://build.golang.org/log/5e58860b238976b022020c1cb9b3537a20adc863:

```
Building Go cmd/dist using /tmp/gobuilder-mips64/go1.4/go. (go1.22.6 linux/mips64)
Building Go toolchain1 using /tmp/gobuilder-mips64/go1.4/go.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
# internal/unsafeheader
<unknown line number>: internal compiler error: panic: runtime error: index out of range [0] with length 0

[...]
```

This isn't happening on other ports, but does happen on GOOS=linux GOARCH=mips. Also note that without a LUCI builder (issue #67303), [watchflakes](https://go.dev/wiki/Watchflakes) doesn't catch and report persistent failures such as this one.

https://build.golang.org/log/e098e9f4dd5cedc9afd00c53a1ead71b3ab66125 was the last passing commit, so this seems to be related to [CL 594597](https://go.dev/cl/594597) for #54766.

CC @golang/mips.

**Comment by prattmic** [comment]
mipsle is OK, so this is probably a big endian problem. I thought I handled this with ppc64, but perhaps this is 32-bit big endian specific.
