### ISSUE TITLE
x/pkgsite: package removal request for github.com/nbgrp/pkg/proto

### ISSUE THREAD

**Issue by a-menshchikov** [golang/go#70279]
Accidentally I made package with wrong module name. An error was fixed immediately, but pkg cached wrong version.

Now github.com/nbgrp/pkg/proto has the only one version with correct module name. Is it possible to reset cache for the package?

**Comment by seankhliao** [comment]
Once seen by the proxy / sumdb, we consider the contents immutable. You cannot redefine what your tag points to. You can publish a new version plus a retraction to discourage selecting the version with the wrong code.
a package removal request here can only hide documentation, it will not affect go command behaviour.
