### ISSUE TITLE
os/user: Fails to return correct user names when users defined outside /etc/passwd

### ISSUE THREAD

**Issue by tzugen** [golang/go#70276]
### Go version

1.23.3

### Output of `go env` in your module/workspace:

```shell
N/A
```

### What did you do?

Use lookupUserId() to retrieve the username for a given id on Fedora Silverblue.

Internally os/user looks hardcoded in /etc/passwd , which does not contain the system users in Fedora Silverblue. Instead the /etc/nsswitch.conf should be queried to retrieve places in which users are defined and then proceeded from there. This call will also not report the correct name for users defined through ldap etc. 

### What did you see happen?

UnknownUserIdError

### What did you expect to see?

A valid username

**Comment by seankhliao** [comment]
Please fill in the issue template properly with a reproducer.
If available, os/user will call C functions, these should invoke the appropriate nss functionality. Pure go will never support nss.

**Comment by tzugen** [comment]
Ah, ok, i only looked at the user.go file.
