### ISSUE TITLE
x/vuln: request govulncheck mark CVE's with severity level

### ISSUE THREAD

**Issue by aep-sunlife** [golang/go#70289]
Hi,

I enjoy using govulncheck to scan for vulnerabilities in Go projects.

I would like govulncheck to denote the severity level of each vulnerability, in order to help users prioritize resolution.

Large, complex projects often have hundreds of CVE's, so from a security perspective it makes sense to patch vulnerabilities in descending order of severity.

For comparison, other common SCA tools note severity levels like Critical, High, Medium, Low, Info for each CVE reported.

**Comment by seankhliao** [comment]
please see the faq
