### ISSUE TITLE
cmd/compile: memcombine does not combine stores separated by OpLocalAddr

### ISSUE THREAD

**Issue by fengyoulin** [golang/go#70300]
### Go version

devel go1.24-c96939fbed

### Output of `go env` in your module/workspace:

```shell
GOARCH='amd64'
```

### What did you do?

Check the assembly code of this function:
```go
func foo(v uint64) (b [8]byte) {
	b[0] = byte(v)
	b[1] = byte(v >> 8)
	b[2] = byte(v >> 16)
	b[3] = byte(v >> 24)
	b[4] = byte(v >> 32)
	b[5] = byte(v >> 40)
	b[6] = byte(v >> 48)
	b[7] = byte(v >> 56)
	return b
}
```

### What did you see happen?

```
88442408                MOVB AL, 0x8(SP)
4889c1                  MOVQ AX, CX
48c1e808                SHRQ $0x8, AX
88442409                MOVB AL, 0x9(SP)
4889c8                  MOVQ CX, AX
48c1e910                SHRQ $0x10, CX
884c240a                MOVB CL, 0xa(SP)
4889c1                  MOVQ AX, CX
48c1e818                SHRQ $0x18, AX
8844240b                MOVB AL, 0xb(SP)
4889c8                  MOVQ CX, AX
48c1e920                SHRQ $0x20, CX
884c240c                MOVB CL, 0xc(SP)
4889c1                  MOVQ AX, CX
48c1e828                SHRQ $0x28, AX
8844240d                MOVB AL, 0xd(SP)
4889c8                  MOVQ CX, AX
48c1e930                SHRQ $0x30, CX
884c240e                MOVB CL, 0xe(SP)
48c1e838                SHRQ $0x38, AX
8844240f                MOVB AL, 0xf(SP)
c3                      RET
```

### What did you expect to see?

```
4889442408              MOVQ AX, 0x8(SP)
c3                      RET
```

**Comment by randall77** [comment]
I feel like the right solution here is to not issue so many OpLocalAddr in the first place.
We're pretty conservative about how we generate them, but especially as the target of the reference has no pointers, we really don't have to be super careful.
I'm thinking that in ssagen we can use a single OpLocalAddr (like we do for PPARAM variables) for any PPARAMOUT variables that don't have pointers in them. Or something like that.
We could so CSE the OpLocalAddr, perhaps? If one dominates the other we can use the first one.

**Comment by fengyoulin** [comment]
I found the explanation in [CL 122483](https://go-review.googlesource.com/c/go/+/122483) which introduced OpLocalAddr. I am studying it.

**Comment by randall77** [comment]
https://go-review.googlesource.com/c/go/+/122484 (which looks abandoned-ish @dr2chase) implements the CSE part I suggested. My other suggestions are in there as comments as well.

**Comment by fengyoulin** [comment]
> Change https://go.dev/cl/628075 mentions this issue: `cmd/compile: modify CSE to remove redundant OpLocalAddrs`

This CL is ready for review. PTAL. @randall77
