### ISSUE TITLE
access: approvers

### ISSUE THREAD

**Issue by Jorropo** [golang/go#70376]
See https://go.dev/wiki/GerritAccess

Account `jorropo.pgm@gmail.com`

Hey I have been having a "fun" time contributing to the compiler, I would enjoy doing a similar thing with reviews and being able to submit my own CLs.

**Comment by mvdan** [comment]
For some context, this is the same person that attended the contributor summit at golab.io a few days ago. cc @alandonovan @neild

**Comment by mknyszek** [comment]
Hi @Jorropo!

Thank you for contributing to the Go project. We've discussed this request on the team, and agreed to grant you this access. I've added your Gerrit account to the approvers group now.

Please be familiar with the rules for voting and submitting changes as described at https://go.dev/wiki/GerritAccess#approving-cls-approvers. If you're unsure or have any questions, please don't hesitate to ask us.

Thank you again for your help.
