### ISSUE TITLE
access: may-start-trybots

### ISSUE THREAD

**Issue by fengyoulin** [golang/go#70372]
Hi,

Can I get Gerrit access to run the TryBots?

I'm trying to fix some bugs such as https://go.dev/cl/628075, having this permission will save Reviewers time.

My Gerrit user ID is 58123, email address is fengyoulin@live.com.

See https://go.dev/wiki/GerritAccess#running-trybots-may-start-trybots

Thanks!

@cagedmantis

**Comment by cagedmantis** [comment]
Hi Youlin,

Thank you for your contributions, and for requesting trybot access! I've added you to the may-start-trybots group, so you should be able to do so now.

As you've probably seen at https://go.dev/wiki/GerritAccess#running-trybots-may-start-trybots, please be sure to skim CLs before starting a trybot run.

Let us know if you have any questions or issues with it, and thanks again!
