### ISSUE TITLE
x/pkgsite: issue title

### ISSUE THREAD

**Issue by codeimmortal** [golang/go#70387]
### What is the URL of the page with the issue?

https://pkg.go.dev/fmt@go1.23.3

### What is your user agent?

Chrome/130.0.0.0

### Screenshot

<img width="978" alt="Screenshot 2024-11-16 at 9 32 04 AM" src="https://github.com/user-attachments/assets/d5cccd1e-8e85-4a04-a8ed-8ae57513853d">
 

### What did you do?

If you see the screenshot, you will find these two line.

%x	hexadecimal notation (with decimal power of two exponent), e.g. -0x1.23abcp+20
%X	upper-case hexadecimal notation, e.g. -0X1.23ABCP+20

if you see e.g -0x1.23abcp+20 , you will find out this is not a proper hexadecimal notation. it should be, d in place of p same for uppercase

%x	hexadecimal notation (with decimal power of two exponent), e.g. -0x1.23abcd+20
%X	upper-case hexadecimal notation, e.g. -0X1.23ABCD+20

### What did you see happen?

If you see the screenshot, you will find these two line.

%x	hexadecimal notation (with decimal power of two exponent), e.g. -0x1.23abcp+20
%X	upper-case hexadecimal notation, e.g. -0X1.23ABCP+20

there is p in hexadecimal notation, which is wrong notation.

### What did you expect to see?

It should be d insted of p, or any other valid hexa character

%x	hexadecimal notation (with decimal power of two exponent), e.g. -0x1.23abcd+20
%X	upper-case hexadecimal notation, e.g. -0X1.23ABCD+20

**Comment by codeimmortal** [comment]
I can raise small PR to correct that.

**Comment by ianlancetaylor** [comment]
The text is correct.

See https://go.dev/play/p/ykxYS9yRyJI
