### ISSUE TITLE
x/pkgsite: package removal request for github.com/mohammedyh/np-run

### ISSUE THREAD

**Issue by mohammedyh** [golang/go#70410]
What is the path of the package that you would like to have removed?
https://pkg.go.dev/github.com/mohammedyh/np-run

Are you the owner of this package?
Yes.

Which version(s) would you like to be removed?
All

What is the reason that you could not retract this package instead?
I've renamed the repo & package to github.com/mohammedyh/npr and didn't want the old-named package floating around.

**Comment by adonovan** [comment]
I confirm that the repo and GitHub username match, and have made the configuration change. Please allow a few days for it to propagate.
