### ISSUE TITLE
x/pkgsite: package removal request for 5 packages

### ISSUE THREAD

**Issue by Highdeger** [golang/go#70413]
These modules weren't meant to be public at their current state, I was just testing and now all are published with wrong state and tags.
Could you please remove them.
- github.com/highdeger/jason
- github.com/highdeger/eris
- github.com/highdeger/logwarts
- github.com/highdeger/vexillum
- github.com/highdeger/acri-collision-detector

**Comment by seankhliao** [comment]
since you mention tags, note that removal only means hiding the generated documentation, you will not be able to reuse any tags you have already published

**Comment by Highdeger** [comment]
that's totally fine, I won't reuse any of published tags.

**Comment by Highdeger** [comment]
I'd still want to get these package removed. These were not meant to be public.

**Comment by adonovan** [comment]
I confirm that the repo owner matches the GitHub username and have made the configuration change. Please allow a few days for it to propagate.
