### ISSUE TITLE
x/pkgsite: package removal request for [https://pkg.go.dev/gitee.com/gkdgo/kk_go_kit]

### ISSUE THREAD

**Issue by cruvie** [golang/go#70444]
### What is the path of the package that you would like to have removed?

gitee.com/gkdgo/kk_go_kit

### Are you the owner of this package?

yes
https://gitee.com/gkdgo/kk_go_kit will redirect to https://gitee.com/cruvie/kk_go_kit
and I created a same issue to proof that I own the repo
https://gitee.com/cruvie/kk_go_kit/issues/IB5KL1

### What is the reason that you could not retract this package instead?

the domain has changed from gkdgo to cruvie, so gitee.com/gkdgo/kk_go_kit changed to gitee.com/cruvie/kk_go_kit

**Comment by adonovan** [comment]
I confirm that the owner of the repo has added a link to this issue as evidence of ownership. I have made the necessary configuration change; please allow a few days for it to propagate.
