### ISSUE TITLE
Unknown error in grpc response

### ISSUE THREAD

**Issue by OriKanfi** [golang/go#70458]
### Go version

go 1.21.3

### Output of `go env` in your module/workspace:

```shell
//
```

### What did you do?

I return an error in this format :
func toProtoIssueClassification(issueClassification issues_types.Classification) (pb.IssueClassification, error) {
	switch issueClassification {
	case issues_types.VIOLATION:
		return pb.IssueClassification_VIOLATION, nil
	case issues_types.INCIDENT:
		return pb.IssueClassification_INCIDENT, nil
	default:
		err := fmt.Errorf("issue classification not valid: %s", issueClassification)
		logger.Error(err)
		return pb.IssueClassification_UNSPECIFIED_CATEGORY, err
	}
}

the grpc response is : Unknown error

when i write the function this way:
func toProtoIssueClassification(issueClassification issues_types.Classification) (pb.IssueClassification, error) {
	err := fmt.Errorf("issue classification not valid: %v", issueClassification)
	logger.Error(err)
	return pb.IssueClassification_UNSPECIFIED_CATEGORY, fmt.Errorf("issue classification not valid: %s", issueClassification)
}

it works fine and print the error log as i expected

### What did you see happen?

grpc response did not return what i expect.
It returns - unknown

### What did you expect to see?

i expected to see the actual error string

**Comment by seankhliao** [comment]
that doesn't look like a go error.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
