### ISSUE TITLE
cmd/cgo/internal/testsanitizers: failures with `setarch: failed to set personality to x86_64: Operation not permitted`

### ISSUE THREAD

**Issue by qmuntal** [golang/go#70463]
### Proposal Details

I'm seeing the following error when running `gotip tool dist test` in a Ubuntu 22.04 container image:

```
--- FAIL: TestShared (0.00s)
    --- FAIL: TestShared/tsan_shared (8.58s)
        cshared_test.go:105: /usr/bin/setarch x86_64 -R /tmp/TestShared2916998830/tsan_shared exited with exit status 1
            setarch: failed to set personality to x86_64: Operation not permitted
--- FAIL: TestTSAN (51.46s)
    --- FAIL: TestTSAN/tsan (1.95s)
        tsan_test.go:88: /usr/bin/setarch x86_64 -R /tmp/TestTSAN2318749046/tsan exited with exit status 1
            setarch: failed to set personality to x86_64: Operation not permitted
```

The `setarch` normally needs the `--privileged` flag to be passed to `docker run`, but I would rather try to avoid that. In fact, `setarch` was introduced in [CL 623956](https://go-review.googlesource.com/c/go/+/623956) to fix the following test issue: https://github.com/golang/go/issues/59418, which it did, but also introduced the issue reported in here.

**Comment by ianlancetaylor** [comment]
CC @mknyszek
