### ISSUE TITLE
x/tools/gopls: jump to definition on 'return' should go to the result parameter list

### ISSUE THREAD

**Issue by findleyr** [golang/go#70462]
Frequently, when I'm looking at a return statement, I want to jump to the function signature.

In the category of "more LSP operations should work, more of the time", we could make jump to definition on a return statement go to the result parameter list.

**Comment by mateusz834** [comment]
This would be also nice for `break` and `continue`, maybe `goto`, but not realy needed, because we can always go to definition of the label (it is required).

**Comment by findleyr** [comment]
@mateusz834 we can do that too. I think whenever there is an obvious possible result for an LSP operation at a position, we should return it. It is a good UX when more operations work, more of the time.

**Comment by xzbdmw** [comment]
How about make hover works for return to show function signature.

**Comment by findleyr** [comment]
> How about make hover works for return to show function signature.

That's a great idea, too. Hover is probably more useful than definition, actually, but we can do both.

**Comment by findleyr** [comment]
Hmm, although I do find that hover to be distracting in some editors. In my editor, I make it a manual operation, bound to a keystroke. I wonder if we should be cautious about popping up hover dialogs over everything.

**Comment by xzbdmw** [comment]
In fact, gopls is already conservative in hover -- rust-analyzer shows definition for every keyword.
Users are able to configure a debounce for hover request, so this should not be a  big problem.

**Comment by madelinekalil** [comment]
Finished "jump to definition" for return statements, will work on break/goto/continue next
