### ISSUE TITLE
x/tools/go/packages: undeprecate Load* mode flags (or fix Need* flags)

### ISSUE THREAD

**Issue by findleyr** [golang/go#70470]
Especially with the 'deprecated' gopls analyzer, I keep bumping up against the fact that go/packages.LoadAllSyntax is deprecated, yet we continue to use it, and keep adding more uses. The stated reason for continuing to use it are usually (1) it is convenient, and (2) the Need* flags interact surprisingly in complicated ways. (To be honest, I can't recall exactly how NeedFlags don't behave as expected -- perhaps @adonovan remembers).

Assertions:

- We should definitely fix bugs related to the Need* mode flags, if there are any. I couldn't find any filed.
- If we prefer to use Load* mode flags, we shouldn't advertise them as deprecated.

Since we're unlikely to have time to prioritize digging deeply into this problem, I think we should just remove the deprecation notices from these mode flags. Given that the original addition did not have a proposal (https://go.dev/cl/173959), I don't think we need a proposal here. (deprecation is a reversible decision).

CC @adonovan @matloob

**Comment by adonovan** [comment]
I agree that we should undeprecate them, recommend their use, and improve their documentation.

The Load flags are not only simpler, but they have fewer combinations, which means fewer "colors" (really: subtle Pantone shades) of Packages data structures that algorithms need to deal with.

> (To be honest, I can't recall exactly how NeedFlags don't behave as expected -- perhaps @adonovan remembers).

See this list of need-related issues for starters:

- https://github.com/golang/go/issues/56633
- https://github.com/golang/go/issues/56677
- https://github.com/golang/go/issues/58726
- https://github.com/golang/go/issues/63517

**Comment by findleyr** [comment]
Thank you. Somehow this github search fails to return any of those...
https://github.com/golang/go/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+go%2Fpackages+need

**Comment by xieyuschen** [comment]
@findleyr I think the issues are listed in the comments of `LoadMode` and here is an add-on. I have sent you a CL for the doc change and hope you like it:)

- https://github.com/golang/go/issues/69931
