### ISSUE TITLE
os: TestRootConsistency* and TestRootRaceRenameDir fail on Plan 9 after CL 627475

### ISSUE THREAD

**Issue by millerresearch** [golang/go#70484]
### Go version

gotip

### Output of `go env` in your module/workspace:

```shell
n/a
```

### What did you do?

LUCI tests running on Plan 9 builders.

### What did you see happen?

Examples from  [log](https://ci.chromium.org/b/8730688067820761969) on plan9-arm builder:

```
--- FAIL: TestRootConsistencyCreate/dir_slash (0.05s)
    root_test.go:814: with root:    err='.../TestRootConsistencyCreatedir_slash2266991326/001/ROOT/target/' create without DMDIR
    root_test.go:815: without root: err='.../TestRootConsistencyCreatedir_slash2266991326/002/ROOT/target/' create without DMDIR
    root_test.go:816: want consistent results, got mismatch
--- FAIL: TestRootConsistencyCreate/dir_slash_dot (0.05s)
    root_test.go:814: with root:    err='.../001/ROOT/target/.' create without DMDIR
    root_test.go:815: without root: err='.../002/ROOT/target/.' create without DMDIR
    root_test.go:816: want consistent results, got mismatch
--- FAIL: TestRootConsistencyCreate/directory_in_path_missing (0.04s)
    root_test.go:814: with root:    err='.../001/ROOT/dir' does not exist
    root_test.go:815: without root: err='.../002/ROOT/dir' does not exist
    root_test.go:816: want consistent results, got mismatch
```

Also:

```
--- FAIL: TestRootRaceRenameDir (0.09s)
    root_test.go:1149: rename /tmp/TestRootRaceRenameDir1031700980/001/base/a /tmp/TestRootRaceRenameDir1031700980/001/b: invalid argument

```

### What did you expect to see?

The consistency tests are failing because Plan 9 includes a path name in its error strings, so the error returned from invalid operations using different path names will not be the same.

The rename test is failing because Plan 9 only supports renaming files when old and new names are in the same directory.

Note that os tests are also failing in NetBSD after [CL 627475](https://go.dev/cl/627475), for different reasons.

**Comment by ianlancetaylor** [comment]
CC @neild
