### ISSUE TITLE
cmd/compile/internal/importer: flip enable alias to true [1.23 backport]

### ISSUE THREAD

**Issue by xieyuschen** [golang/go#70517]
This issue is created to request a backport at go1.23 to fix #70394. The issue _doesn't_ exist in go1.24(master) as the code has refactored a bit before and fixed this issue.

https://github.com/golang/go/blob/b0bbfb1e0f8f3ea55e1e286d32b57daf96495878/src/cmd/compile/internal/importer/ureader.go#L34

The backport fix allows ureader to read exportdata with alias correctly and it doesn't affect the correctness of `compile` to construct exportdata for the following packages.

@timothy-king

**Comment by timothy-king** [comment]
Thoughts for cherrypicking: Setting `enableAlias: true,` seems plausible. I would like to do more tests first though before weighing in on whether it is worth the risk.

**Comment by timothy-king** [comment]
My investigation makes me believe that this should be safe enough for 1.23. The CL to cherry pick would be https://go.dev/cl/631855.

**Comment by mvdan** [comment]
When could I expect a 1.23.x release with this fix? I was hoping that would be the case with 1.23.4, given that the patch was approved last week, but unfortunately I see it's not the case.

**Comment by timothy-king** [comment]
@mvdan The patch have been approved on gerrit, but the status on the issue is CherryPickCandidate. For it to go forward, its must be CherryPickApproved. See https://go.dev/wiki/MinorReleases. (Yes this can be confusing.)

**Comment by mvdan** [comment]
I see. Hopefully this can move along relatively quickly at this point, as I am unable to use alias tracking still.

**Comment by cagedmantis** [comment]
This change has been approved as it is a problem without a viable workaround.

**Comment by mvdan** [comment]
Hi again - is there perhaps a chance that 1.23.5 with this backport will happen before the holidays?

**Comment by mvdan** [comment]
Hello again - is 1.23.5 with this backport happening soon? At this point 1.24.0 is just five weeks away, so with any further delay I'll just reset my expectations and abandon alias support for 1.23.x.

**Comment by ianlancetaylor** [comment]
The next 1.23 minor release is supposed to happen real soon now.
