### ISSUE TITLE
x/pkgsite: package removal request for eight packages

### ISSUE THREAD

**Issue by jfrech** [golang/go#70534]
### What is the path of the package that you would like to have removed?

((See below.))

### Are you the owner of this package?

Yes. I am the owner of all eight modules. See also https://github.com/golang/go/issues/68648#issuecomment-2269470720 where this claim has in the past already been verified.

The eight packages I would like to have removed are:

  - pkg.jfrech.com/go/flaggers
  - pkg.jfrech.com/go/fleetingly
  - pkg.jfrech.com/go/legacy-tbp
  - pkg.jfrech.com/go/sshutil
  - pkg.jfrech.com/go/utils
  - pkg.jfrech.com/go/utils/integrity
  - pkg.jfrech.com/go/webutils
  - pkg.jfrech.com/micronet

I am including eight requests in one GitHub issue on the assumption that such is easier for the pkgsite maintainers. Should this assumption be ill-advised, I am open to have this issue closed and me opening eight separate issues.

### What is the reason that you could not retract this package instead?

I published these modules in error and did retract all of them but would be very grateful if their names would no longer show up on the pkgsite.

**Comment by adonovan** [comment]
Batching the requests is indeed easier; thanks. Sorry to be a pain, but could you prove that jfrech.com trusts you, for example by adding a link to this issue somewhere on jfrech.com? (The previous verification looks backwards to me--my mistake.) Thanks.
