### ISSUE TITLE
cmd/go: errors about netrc need go prefix

### ISSUE THREAD

**Issue by rsc** [golang/go#70537]
I ran 'go test' in a subprocess with no environment at all (accidentally), and it failed with

	could not parse netrc (GOAUTH=netrc): $HOME is not defined

The usual convention is that calls to base.Fatalf need to provide a 'go: ' prefix in the error.
The ones in auth should be fixed.

/cc @matloob @samthanawalla

**Comment by cuishuang** [comment]
The error message here comes from 
https://github.com/golang/go/blob/b68f8ca89a2fb6b33d1e78fadc33d1c35693f6b8/src/cmd/go/internal/auth/netrc.go#L77

If no environment variables are set, `os.UserHomeDir()` will return an error. I wonder if we need to add a logic here to get the result of `cd ~ && pwd` and try to find the .netrc file in that path.

**Comment by cuishuang** [comment]
This issue can be closed now because #CL631535 has been merged.

**Comment by ianlancetaylor** [comment]
Thanks.
