### ISSUE TITLE
gorm: gorm db does not call callback.Trace() for 'sqlite3 DB' when  'sqlite3 DB' is opened with '_txlock=immediate' in the dsn

### ISSUE THREAD

**Issue by satsrini** [golang/go#70552]
### Go version

go version go1.23.1 windows/amd64

### Output of `go env` in your module/workspace:

```shell
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\abc\AppData\Local\go-build
set GOENV=C:\Users\abc\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\abc\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\abc\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.23.1
set GODEBUG=
set GOTELEMETRY=local
set GOTELEMETRYDIR=C:\Users\abc\AppData\Roaming\go\telemetry
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\351\ciam-service\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\SATISH~1\AppData\Local\Temp\go-build253837795=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

Tried to simulate a DB lock after attaching a callback function using gormlogger.
Opened the Sqlite3 database connection as sqlite.Open(“dbname.sqlite3?_txlock=immediate”)

### What did you see happen?

gormlogger's callback method Trace() was not invoked after hitting a 'database is locked' error
https://github.com/go-gorm/gorm/blob/master/logger/logger.go#L68

### What did you expect to see?

gormlogger's callback method Trace() to be invoked after hitting a 'database is locked' error.

**In further debugging found the following:**

When “_txlock=immediate”, in the sqlite3 DB,  the ‘database is locked’ error is thrown when the DB transaction is opened(ie at the very beginning of the operation – first step itself)
 a. Primary Begin Transaction Error:  https://github.com/go-gorm/gorm/blob/6bfccf8afa84fd55e1fae471edf3d45a4b764d3e/callbacks/transaction.go#L9
b. So the func call is returned at this point itself https://github.com/go-gorm/gorm/blob/6bfccf8afa84fd55e1fae471edf3d45a4b764d3e/callbacks/create.go#L41
           b.1  So it misses to populate db.Statement.SQL https://github.com/go-gorm/gorm/blob/6bfccf8afa84fd55e1fae471edf3d45a4b764d3e/callbacks/create.go#L68
           b.2 So , since since db.Statement.Len() = 0  , gormlogger’s callback Trace() cannot be called as per the below code.
                                                                     https://github.com/go-gorm/gorm/blob/6bfccf8afa84fd55e1fae471edf3d45a4b764d3e/callbacks.go#L134

**Comment by seankhliao** [comment]
please report it to Gorm, not the go repo.
