### ISSUE TITLE
x/tools/gopls: refactor.extract.variable inserts new statement before the scope of its free symbols

### ISSUE THREAD

**Issue by adonovan** [golang/go#70563]
Before:
```go
	if x := 1; true {

	} else if y := x; true {  // apply refactor.extract.variable to x

	}
```
After:
```go
	x1 := x // error: undefined x
	if x := 1; true {

	} else if y := x1; true {

	}
```

**Comment by xzbdmw** [comment]
Should [StmtToInsertVarBefore](https://github.com/golang/tools/blob/07a58bce0abb3e4d1256be4e3512fd55d01daa60/internal/analysisinternal/analysis.go#L83) be factored to indicate errors?

**Comment by adonovan** [comment]
> Should [StmtToInsertVarBefore](https://github.com/golang/tools/blob/07a58bce0abb3e4d1256be4e3512fd55d01daa60/internal/analysisinternal/analysis.go#L83) be factored to indicate errors (or observe this earlier with freeVars)?

Probably. And it should be moved into the golang package.
