### ISSUE TITLE
x/pkgsite: var tag uint32 ='name' should compile pass through

### ISSUE THREAD

**Issue by epowsal** [golang/go#70566]
### What is the URL of the page with the issue?

none

### What is your user agent?

no

### Screenshot

no

### What did you do?

code:
var tag uint32 ='name' 

### What did you see happen?

more than one character in rune literal

### What did you expect to see?

compile pass through

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions,
