### ISSUE TITLE
proposal: spec: keys/vals function for map types

### ISSUE THREAD

**Issue by eaigner** [golang/go#7057]
<pre>It's quite a common case to use maps to ensure values are unique.

I wondered if the hashmap implementation could expose it's keys and values directly via
a `keys` and `vals` builtin, instead of creating a slices, iterating over the map and
filling the slice. It would also help to avoid creating unnecessary gargabe when only a
reference is obtained.</pre>

**Comment by nathany** [comment]
This is similar to other requests for builtin generic functionality, such as map/reduce #14173. Otherwise keys/values could be implemented or generated for each map type desired.

**Comment by ianlancetaylor** [comment]
Any implementation of these functions has to make a copy, so there is no way to generate less garbage than the hand written implementation.  We aren't going to do this special case.  Closing.
