### ISSUE TITLE
cmd/trace: show end stack traces

### ISSUE THREAD

**Issue by felixge** [golang/go#70570]
### Go version

go version devel go1.24-733df2bc0a 2024-11-25 02:23:41 +0000 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
n/a
```

### What did you do?

I generated an execution trace for a [simple Go program](https://gist.github.com/felixge/e329d091290662a136611b9fffbdd67f) that has a single goroutine that runs for 10ms on CPU followed by 10ms of sleep in a loop.

### What did you see happen?

Clicking on the first three goroutine spans, I see:

<table>
<tr>
	<td><img src="https://github.com/user-attachments/assets/6cd2ab10-cecc-4976-99bc-05ca53d3b564"/></td>
	<td><img src="https://github.com/user-attachments/assets/aec463d8-d8e7-49ab-86c8-96c9415830fa"/></td>
	<td><img src="https://github.com/user-attachments/assets/c96e0e3f-44b7-4fd2-9936-f96f5f828f8b"/></td>
</tr>
</table>

Showing only the start stack traces also makes it impossible to see the last stack trace produced by a goroutine.

### What did you expect to see?

Showing both start and end stack traces would make it much easier to understand the trace:

**update:** I realized this is not just a "nice to have" but actually a regression compared to go1.22, see comment below.

<table>
<tr>
	<td><img src="https://github.com/user-attachments/assets/46067d0c-d92c-4a38-9d8d-0c19667dbc5f"/></td>
	<td><img src="https://github.com/user-attachments/assets/7f0d8a90-372c-4ae2-8611-7c5b61de412e"/></td>
	<td><img src="https://github.com/user-attachments/assets/b2d1e869-d9df-4457-ad09-a50ff403e6a8"/></td>
</tr>
</table>

cc @mknyszek @prattmic @nsrip-dd - CL for this is submitted below

**Comment by prattmic** [comment]
Since this is a regression and very simple, I personally think it would be OK to backport.

**Comment by felixge** [comment]
@gopherbot please consider this for backport to 1.23, it’s a regression.
