### ISSUE TITLE
import/path: go routine parent go routine did not showed in debug output

### ISSUE THREAD

**Issue by epowsal** [golang/go#70589]
### Go version

go 1.23 windows amd64

### Output of `go env` in your module/workspace:

```shell
set GO111MODULE=off
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\iwlb\AppData\Local\go-build
set GOENV=C:\Users\iwlb\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=true
set GOMODCACHE=M:\work\code\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=M:\work\code\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn
set GOROOT=M:\work\tool\go1.23.1.windows-amd64
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=M:\work\tool\go1.23.1.windows-amd64\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.23.1
set GODEBUG=
set GOTELEMETRY=local
set GOTELEMETRYDIR=C:\Users\iwlb\AppData\Roaming\go\telemetry
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-
```

### What did you do?

debug use liteide

### What did you see happen?

go routine parent go routine did not showed in debug output.it make me can not found out error source.

### What did you expect to see?

fix

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by seankhliao** [comment]
looking at the past issues you've filed, please take a moment to reflect on if they're on topic for the go issue tracker before creating any more issues
