### ISSUE TITLE
x/pkgsite/cmd/pkgsite: invalid env set

### ISSUE THREAD

**Issue by vkml** [golang/go#70581]
### What is the URL of the page with the issue?

any module URL

### What is your user agent?

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36

### What did you do?

Ran the `pkgsite` command to run the server.  Exact used command syntax: `pkgsite -http=":7000"`

### What did you see happen?

On Windows, running the command for the local repository starts the server but fails and hands indefinitely when attempting to follow the module tree. During server init the following error is displayed:
```Error: loading packages from stdlib: err: fork/exec E:\LANG\Go\bin\go.exe: The parameter is incorrect.: stderr:``` 

The `godoc` command works fine on the same local project.

### What did you expect to see?

Local project documentation.

**Comment by vkml** [comment]
Found the possible reason for the following error:

`Error: loading packages from stdlib: err: fork/exec E:\LANG\Go\bin\go.exe: The parameter is incorrect.: stderr:`

Internal `go list ...` command call fails due to function [`NewGoPackagesStdlibModuleGetter(...)`](https://github.com/golang/pkgsite/blob/a9be46500444d46cc1dfe06a2021962103632db3/internal/fetch/getters.go#L290) sets a malformed env variable. It tries to append `env` strings slice with `"GOROOT="` and `abs`, which results in 2 separate slice elements, but the intended behavior would be `"GOROOT=" + abs` to set GOROOT.

**Comment by matloob** [comment]
This was fixed by https://go.dev/cl/635675.
