### ISSUE TITLE
reflect: UnsafePointer() map Values cannot be converted back to a map

### ISSUE THREAD

**Issue by mhr3** [golang/go#70595]
### Go version

go version go1.22.4 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
...
```

### What did you do?

Obtained an unsafe.Pointer to a map like this:
```
m := map[string]any{"foo": "bar"}
uPtr := reflect.ValueOf(m).UnsafePointer()
...

// later I want to convert that unsafe.Pointer back into a map, but this isn't possible
rv := reflect.NewAt(reflect.TypeFor[map[string]any](), uPtr)
return rv.Interface().(*map[string]any)
```

### What did you see happen?

The above snippet crashes the app, because uPtr is the actual map, not a pointer to it, and there's no other working API that can initialize/associate the Value with the uPtr. (or just cast the unsafe.Pointer into a map)

### What did you expect to see?

There should be an operation analogous to Value.UnsafePointer() that can take the pointer and re-create a map out of it. Perhaps unsafe pkg itself should have Map methods similar to unsafe.Slice() + unsafe.SliceData()?

**Comment by seankhliao** [comment]
reflect.ValueOf(&m).UnsafePointer()

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by mhr3** [comment]
I'm aware there's other ways to do this, I'm opening an issue because doing things this way exposes an edge case that produces unusable pointers.

**Comment by randall77** [comment]
You can do:
```
	var m map[string]any
	*(*unsafe.Pointer)(unsafe.Pointer(&m)) = uPtr
```
I agree that the interaction of `unsafe` and `reflect` isn't great. But then again, if you're using `unsafe` you don't normally need reflect.

**Comment by mhr3** [comment]
> if you're using unsafe you don't normally need reflect.

Glad you bring that up - the pointer returned by `reflect.ValueOf(m).UnsafePointer()` is the actual map reference, which would be equivalent to `unsafe.Pointer(m)`, but that's not valid, only `unsafe.Pointer(&m)` is. That's why I mentioned that perhaps the unsafe pkg should have special methods for maps.
