### ISSUE TITLE
Incorrect float expression processing in compile time

### ISSUE THREAD

**Issue by adic3x** [golang/go#70596]
### Go version

1.23

### What did you do?

	a := 0.1
	b := 0.2
	c := a+b == 0.1+0.2 // false

### What did you see happen?

False

### What did you expect to see?

True.

Ok. all other languages (C, C++, C#, Rust, Java, JavaScript, PHP, Python) return `true` for this expression.

https://go.dev/play/p/JvAnVKVSsuk (same code but with reflection)

```Go
	a := 0.1 // type float64
	b := 0.2 // type float64
	c := a+b == 0.1+0.2 // false
	fmt.Println(c)

	var d float32
	var e float32
	d = 0.1
	e = 0.2
	f := d+e == 0.1+0.2 // true
	fmt.Println(f)

	var g float64
	var h float64
	g = 0.1
	h = 0.2
	i := g+h == 0.1+0.2 // false
	fmt.Println(i)
```

As I understand operator `:=` must set type of declared variable equal right part of expression. So what type of literal `0.1` and `0.2`?
If it float32 - `a` and `b` must be float32. Otherwise if its type float64 then expression `0.1+0.2` must be computed as float64+float64->float64 (with specific rounding).

But now literals `0.1` and `0.2` are interpreted as float64 in `:=` operator but expression `0.1+0.2` result - as float32.

**Comment by adic3x** [comment]
> `0.1+0.2` it's an untyped constant that gets computed at arbitrary precision

Is "arbitrary precision" marketing term for "undefined behaviour"? :)

I can't understand why float64+float64 must be "untyped constant". Any reason?

If I want to get some adventures - I will use JavaScript without type hints to get implicit conversions.

In a strongly typed language must be expected behavior for expressions.

**Comment by ALTree** [comment]
`0.1` gets converted to a 53-bits of precision float64 only during the assignment. So in
```
a := 0.1
```
`a` is a float64 variable holding the IEEE-754 representation of the decimal integer 0.1.

On the other hand, in:
```
a := 0.1+0.2
```
the `0.1+0.2` expression is evaluated by the compiler in arbitrary precision, and only later the result (the decimal 0.3) is cast to the closest IEEE-754 float64 to be assigned to `a`. You can force IEEE-754 evaluation using e.g. `a := float64(0.1) + float64(0.2)`.

> Is "arbitrary precision" marketing term for "undefined behaviour"? :)

No: it's used in the mathematical sense.

**Comment by adic3x** [comment]
So you say that the literal 0.1 type is float64.

Then:
```Go
	a := 0.1                                      // 0.1 is float64 and a is float64
	b := 0.2                                      // 0.2 is float64 and b is float64
	fmt.Println(a+b == 0.1+0.2)                   // prints false
	fmt.Println(a+b == float64(0.1)+float64(0.2)) // prints true
```
So to get correct calculation I need to convert float64 type to float64 type? Who in their right mind would even think of something like this? Sorry for toxic, but I really can't understand why all other languages ​​haven't this bug.

```C
#include <stdio.h>

int main() {
    double a = 0.1;
    double b = 0.2;
    int c = (a + b) == (0.1 + 0.2); // true
    printf("%d\n", c);
    return 0;
}
```

```Java
public class Main {
    public static void main(String[] args) {
        double a = 0.1;
        double b = 0.2;
        boolean c = (a + b) == (0.1 + 0.2); // true
        System.out.println(c);
    }
}
```

```Python
a = 0.1
b = 0.2
c = (a + b) == (0.1 + 0.2)  # true
print(c)
```

```C#
using System;

class Program
{
    static void Main()
    {
        double a = 0.1;
        double b = 0.2;
        bool c = (a + b) == (0.1 + 0.2); // true
        Console.WriteLine(c);
    }
}
```

```C++
#include <iostream>

int main() {
    double a = 0.1;
    double b = 0.2;
    bool c = (a + b) == (0.1 + 0.2); // true
    std::cout << std::boolalpha << c << std::endl;
    return 0;
}
```

```Rust
fn main() {
    let a = 0.1;
    let b = 0.2;
    println!("{}", (a + b) == (0.1 + 0.2)); // true
}
```

```JavaScript
let a = 0.1;
let b = 0.2;
console.log(a + b === 0.1 + 0.2); // true
```

```PHP
$a = 0.1;
$b = 0.2;
var_dump($a + $b === 0.1 + 0.2); // true
```

**Comment by adic3x** [comment]
Also:

```Go
	k := 0.1 + 0.2
	fmt.Println("Type of e:", reflect.TypeOf(k)) // float64
```

So, literal float64 + float64 converted to float32, calculated and then again converted to float64? Do you really think it good idea?

**Comment by seankhliao** [comment]
At no point is float32 involved.
What you're doing is:
```
	fmt.Println(float64(0.1)+float64(0.2) == float64(0.3))
```

See: https://0.30000000000000004.com/

**Comment by adic3x** [comment]
For example:

```Go
	a := 0x00000000ffffffff + 0x0000000000000001 // 0x00000000_ffffffff
	fmt.Println(fmt.Sprintf("%x", a)) // 0x00000001_00000000
```

In this case it works correctly. However, consider that the compiler converts the int64 result to int32 (and maybe then to 64 again) - we get 0.

**Comment by adic3x** [comment]
> At no point is float32 involved. What you're doing is:
> 
> ```
> 	fmt.Println(float64(0.1)+float64(0.2) == float64(0.3))
> ```
> 
> See: https://0.30000000000000004.com/

No. it's not about floats at all; it's about implicit convertation between float32 and float64.

**Comment by adic3x** [comment]
```Go
0.1 == float64(0.1) // true
0.2 == float64(0.2) // true
0.1+0.2 == float64(0.1)+float64(0.2) // false
```

Literals 0.1 and 0.2 types are float64 (see above link to documentation).

Type of 0.1 and type of float64(0.1) are same. Why result of calculation float64+float64 is different?

Are you on the Go team? Why should I have to prove an obvious bug? I feel like I'm in the "Dead Parrot" sketch. It is outrageous.

**Comment by seankhliao** [comment]
please read the linked website. it explains why this isn't a bug.

**Comment by seankhliao** [comment]
since it's not a bug, for questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by ianlancetaylor** [comment]
See also https://go.dev/blog/constants.
