### ISSUE TITLE
x/tools/gopls: high cpu when call go mod tidy

### ISSUE THREAD

**Issue by WAY29** [golang/go#70608]
### Go version

go version go1.22.8 windows/amd64

### Output of `go env` in your module/workspace:

```shell
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\user\AppData\Local\go-build
set GOENV=C:\Users\user\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\user\coding\golang\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\user\coding\golang
set GOPRIVATE=
set GOPROXY=https://goproxy.cn
set GOROOT=C:\Users\user\.version-fox\cache\golang\current
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Users\user\.version-fox\cache\golang\current\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.22.8
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\user\coding\golang\src\yaklang\go.mod
set GOWORK=C:\Users\user\coding\golang\src\yaklang\go.work
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\user\AppData\Local\Temp\go-build78613495=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

When I plan to write code normally and use some libraries from the current file, gopls will automatically import the library for me, which will cause the CPU to soar, causing the entire gopls to be temporarily paralyzed (highlighting, completion, prompts)

### What did you see happen?

Sudden CPU surge
go mod tidy -modfile=C:\Users\lang\AppData\Local\Temp\gopls-tempmod246022334\go.mod
![image](https://github.com/user-attachments/assets/5197c57d-c3e7-4565-b625-607fdec2b523)

### What did you expect to see?

gopls running normally

**Comment by WAY29** [comment]
extra info:
Extra information, a new computer purchased a day ago
CPU: AMD Ryzen Al 9 HX 370

**Comment by WAY29** [comment]
I found that go list also cause the CPU to soar..

**Comment by findleyr** [comment]
Thank you. This is almost certainly related to go list: when you add an import we run `go list` to list package information.

Does this occur for even a small module? If so, then it may indicate some real bug in go list (for example, mismatching paths that cause spurious cache misses).

**Comment by WAY29** [comment]
> Thank you. This is almost certainly related to go list: when you add an import we run `go list` to list package information.
> 
> Does this occur for even a small module? If so, then it may indicate some real bug in go list (for example, mismatching paths that cause spurious cache misses).

Without further testing, I have moved to WSL to work on it, and while there is no evidence, I suspect Windows Defender is involved

**Comment by joshghent** [comment]
Sorry for commenting on a closed issue, but I have this exact problem.

`go env`
```
AR='ar'
CC='clang'
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_ENABLED='1'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
CXX='clang++'
GCCGO='gccgo'
GO111MODULE=''
GOARCH='arm64'
GOARM64='v8.0'
GOAUTH='netrc'
GOBIN='/Users/joshghent/.local/share/mise/installs/go/1.24.2/bin'
GOCACHE='/Users/joshghent/Library/Caches/go-build'
GOCACHEPROG=''
GODEBUG=''
GOENV='/Users/joshghent/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFIPS140='off'
GOFLAGS=''
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/cd/l61r4q756_j0vsb10sn7mzkr0000gn/T/go-build542331661=/tmp/go-build -gno-record-gcc-switches -fno-common'
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMOD='/Users/joshghent/Projects/go.mod'
GOMODCACHE='/Users/joshghent/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/joshghent/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/Users/joshghent/.local/share/mise/installs/go/1.24.2'
GOSUMDB='sum.golang.org'
GOTELEMETRY='local'
GOTELEMETRYDIR='/Users/joshghent/Library/Application Support/go/telemetry'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/Users/joshghent/.local/share/mise/installs/go/1.24.2/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.24.2'
GOWORK=''
PKG_CONFIG='pkg-config'
```

This is the command that my editor was running that had extremely high cpu `go mod tidy -modfile=/var/folders/cd/l61r4q756_j0vsb10sn7mzkr0000gn/T/gopls-tempmod3871126848/go.mod`

Computer info
```
Macbook pro m1 - 16gb
Sonoma 14.4.1 (23E224)
```
