### ISSUE TITLE
x/pkgsite: package removal request for github.com/hoony9x-furiosa-ai/68b4a517-730a-4911-b068-18f7cbcd58a7

### ISSUE THREAD

**Issue by hoony9x-furiosa-ai** [golang/go#70606]
### What is the path of the package that you would like to have removed?

github.com/hoony9x-furiosa-ai/68b4a517-730a-4911-b068-18f7cbcd58a7

### Are you the owner of this package?

Yes.
- I already deleted the target repository.

### What is the reason that you could not retract this package instead?

Above pkg was created for test purpose from my working place, and right now it is no longer needed.

Therefore, I need to remove it from `pkg.go.dev`.

**Comment by findleyr** [comment]
Looks like this was completed.
