### ISSUE TITLE
x/pkgsite: package removal request for https://pkg.go.dev/github.com/Ayanrajpoot10/bughunter-go

### ISSUE THREAD

**Issue by ayanrajpoot10** [golang/go#70624]
Please remove the package https://pkg.go.dev/github.com/Ayanrajpoot10/bughunter-go from pkg.go.dev.

The package is no longer maintained, and I would like to request its removal from the Go module registry to prevent further usage or confusion among developers. Let me know if any additional steps or information are required to process this request.

Thank you for your assistance!

**Comment by Ayanrajpoot10** [comment]
explain me what i need to do

**Comment by seankhliao** [comment]
See https://go.dev/ref/mod#go-mod-file-retract:~:text=Wiping%20out%20a%20module%20including%20all%20pseudo%2Dversions%20and%20tagged%20versions%3A

**Comment by Ayanrajpoot10** [comment]
I appreciate that the module has been marked as retracted. However, I would like to request the complete removal of the module github.com/Ayanrajpoot10/bughunter-go from proxy.golang.org and pkg.go.dev.

The reason for this request is that even though the module is retracted, users can still manually install specific versions, which I want to prevent entirely. I no longer maintain this module, and its continued availability may cause confusion or issues for users.

Please assist in permanently removing this module. Let me know if any further steps are required from my end.

![image](https://github.com/user-attachments/assets/958199cd-8961-419b-be25-33da13272f5f)

**Comment by seankhliao** [comment]
requesting a removal only hides the documentation, it will not prevent users from using the module.

**Comment by Ayanrajpoot10** [comment]
I understand that removal will only hide the documentation. However, my goal is to completely prevent the public use of this tool. I had already deleted the repository earlier but had to recreate it temporarily just to retract the versions.

Now that the module is retracted, I kindly request the complete removal of this package so that users cannot install it using go install. Allowing continued installation, even with retraction warnings, defeats the purpose of my deprecation.

I hope this explanation clarifies my intent. Please assist in fully removing the module from proxy.golang.org, pkg.go.dev and preventing further installations.

Thank you for your understanding and support.

**Comment by ansaba** [comment]
As the owner wants to hide documentation for all current and future versions, accepting the pkg removal request.

**Comment by adonovan** [comment]
To be clear, removing the documentation from pkgsite will not affect the behavior of the go command.

**Comment by Ayanrajpoot10** [comment]
> To be clear, removing the documentation from pkgsite will not affect the behavior of the go command.


Understood, but could you clarify how I can stop the installation of my package if needed?

**Comment by findleyr** [comment]
@Ayanrajpoot10 the package has now been excluded from pkg.go.dev, and your module retraction means it will not be listed by the Go command, and users will get a warning when fetching the module with `go get`.

If the module was published with a redistributable license, there is no easy way to just remove it from the proxy. Part of the purpose of the proxy is to prevent builds breaking when a module version disappears. Is the current state sufficient for your concerns? (No documentation on pkg.go.dev, no listing of module versions, and warning for any explicit usage)

**Comment by Ayanrajpoot10** [comment]
Is it possible to ensure that my package cannot be installed via the `go install` command at all?

**Comment by findleyr** [comment]
Thanks all, closing this as complete.
