### ISSUE TITLE
x/tools/gopls: OOB index crash in completion.expectedReturnStmtType

### ISSUE THREAD

**Issue by adonovan** [golang/go#70636]
```
#!stacks
"runtime.goPanicIndex" && "go/types.(*Tuple).At" && "completion.expectedReturnStmtType"
```
Issue created by [stacks](https://pkg.go.dev/golang.org/x/tools/gopls/internal/telemetry/cmd/stacks).

```go
// expectedReturnStmtType returns the expected type of a return statement.
// Returns nil if enclosingSig is nil.
func expectedReturnStmtType(enclosingSig *types.Signature, node *ast.ReturnStmt, pos token.Pos) types.Type {
	if enclosingSig != nil {
		if resultIdx := exprAtPos(pos, node.Results); resultIdx < len(node.Results) {
			return enclosingSig.Results().At(resultIdx).Type() // <--- At panics
		}
	}
	return nil
}
```

This stack `69yMYw` was [reported by telemetry](https://storage.googleapis.com/prod-telemetry-merged/2024-11-28.json):

- `crash/crash`
- [`runtime.gopanic:+69`](https://cs.opensource.google/go/go/+/go1.23.2:src/runtime/panic.go;l=804)
- [`runtime.goPanicIndex:+2`](https://cs.opensource.google/go/go/+/go1.23.2:src/runtime/panic.go;l=115)
- [`go/types.(*Tuple).At:=34`](https://cs.opensource.google/go/go/+/go1.23.2:src/go/types/tuple.go;l=34)
- [`golang.org/x/tools/gopls/internal/golang/completion.expectedReturnStmtType:+3`](https://cs.opensource.google/go/x/tools/+/gopls/v0.17.0-pre.3:gopls/internal/golang/completion/completion.go;l=2628)
- [`golang.org/x/tools/gopls/internal/golang/completion.expectedCandidate:+37`](https://cs.opensource.google/go/x/tools/+/gopls/v0.17.0-pre.3:gopls/internal/golang/completion/completion.go;l=2316)
- [`golang.org/x/tools/gopls/internal/golang/completion.Completion:+150`](https://cs.opensource.google/go/x/tools/+/gopls/v0.17.0-pre.3:gopls/internal/golang/completion/completion.go;l=651)
- [`golang.org/x/tools/gopls/internal/server.(*server).Completion:+19`](https://cs.opensource.google/go/x/tools/+/gopls/v0.17.0-pre.3:gopls/internal/server/completion.go;l=43)
- [`golang.org/x/tools/gopls/internal/protocol.serverDispatch:+193`](https://cs.opensource.google/go/x/tools/+/gopls/v0.17.0-pre.3:gopls/internal/protocol/tsserver.go;l=363)
- [`golang.org/x/tools/gopls/internal/lsprpc.(*streamServer).ServeStream.ServerHandler.func3:+5`](https://cs.opensource.google/go/x/tools/+/gopls/v0.17.0-pre.3:gopls/internal/protocol/protocol.go;l=160)
- [`golang.org/x/tools/gopls/internal/lsprpc.(*streamServer).ServeStream.handshaker.func4:+52`](https://cs.opensource.google/go/x/tools/+/gopls/v0.17.0-pre.3:gopls/internal/lsprpc/lsprpc.go;l=509)
- [`golang.org/x/tools/gopls/internal/protocol.Handlers.MustReplyHandler.func1:+2`](https://cs.opensource.google/go/x/tools/+/gopls/v0.17.0-pre.3:internal/jsonrpc2/handler.go;l=35)
- [`golang.org/x/tools/gopls/internal/protocol.Handlers.AsyncHandler.func2.2:+3`](https://cs.opensource.google/go/x/tools/+/gopls/v0.17.0-pre.3:internal/jsonrpc2/handler.go;l=104)
- `runtime.goexit:+0`
```
golang.org/x/tools/gopls@v0.17.0-pre.3 go1.23.2 linux/amd64 other,vscode (5)
```

**Comment by adonovan** [comment]
Closely related to https://github.com/golang/go/issues/70634.

**Comment by findleyr** [comment]
This is indeed a logic bug, as described in https://github.com/golang/go/issues/70634#issuecomment-2511833703.
