### ISSUE TITLE
gccgo/arm64: inaccuracies in complex division

### ISSUE THREAD

**Issue by mwhudson** [golang/go#7066]
<pre>What steps will reproduce the problem?
If possible, include a link to a program on play.golang.org.
1. Set up the preview go environment described here:
<a href="https://groups.google.com/d/msg/golang-dev/zHkWq3D92-4/5CI0bzTGO1sJ">https://groups.google.com/d/msg/golang-dev/zHkWq3D92-4/5CI0bzTGO1sJ</a>
2. Put this in a file:

package main

func main() {
    c5 := 1 + 3i
    cd := c5 / c5
    println(cd)
    if cd != 1+0i {
        println(&quot;fail&quot;)
    }
}

3. Run it with go run.

What is the expected output?

(+1.000000e+000+0.000000e+000i)

What do you see instead?

(+1.000000e+000-1.665335e-017i)
fail

Which compiler are you using (5g, 6g, 8g, gccgo)?

gccgo from both the 4.8 branch and mainline (as of a couple of weeks ago).

Which operating system are you using?

Ubuntu Trusty.

Please provide any additional information below.

This could perhaps be a result of FPU modes being set incorrectly, maybe to
round-to-negative-infinity?  It's pretty odd.</pre>

**Comment by ianlancetaylor** [comment]
This seems to work today, though I'm not sure what fixed it.  I see the same results from gc and gccgo.
