### ISSUE TITLE
testing/synctest: defer on systemstack failures on android builders

### ISSUE THREAD

**Issue by mknyszek** [golang/go#70661]
Examples:
- https://build.golang.org/log/6058ba22c5ca038c3faf70d4afd8cf2b85236828
- https://build.golang.org/log/69f5b8aca8dcd47bbe5ec18ac3434e3376d44d07

CC @neild @prattmic

**Comment by neild** [comment]
https://build.golang.org/log/69f5b8aca8dcd47bbe5ec18ac3434e3376d44d07 seems to be something else:

```
##### external linking, -buildmode=exe
"/data/local/tmp/go_android_exec/fips140test.test-198516/fips140test.test": error: Android 5.0 and later only support position-independent executables (-fPIE).
FAIL	crypto/internal/fips140test	0.064s
FAIL
```
