### ISSUE TITLE
x/pkgsite: package removal request for https://pkg.go.dev/github.com/uisdevsquad/go-test/debugmate

### ISSUE THREAD

**Issue by uisdevsquad** [golang/go#70674]
### What is the path of the package that you would like to have removed?

https://pkg.go.dev/github.com/uisdevsquad/go-test/debugmate

### Are you the owner of this package?

Yes, I am the owner of this package.

### What is the reason that you could not retract this package instead?

I would like to delete this package because I published it solely for testing purposes. At the time, I wanted to understand how publishing a Go package worked. This package is not used by anyone and was created purely for testing purposes.

**Comment by anevski-stefan** [comment]
test

**Comment by findleyr** [comment]
Looks like this was completed.
