### ISSUE TITLE
breaking out of a loop using a label: stops the loop prematurely using larger dataset

### ISSUE THREAD

**Issue by lfaoro** [golang/go#70729]
### Go version

go version go1.23.3 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GOARCH='amd64'
GOCACHE='/home/user/.cache/go-build'
GOENV='/home/user/.config/go/env'
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOMODCACHE='/home/user/go/pkg/mod'
GOOS='linux'
GOPATH='/home/user/go'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/nix/store/zhq8dnjbhwspzdglyq28j74axvqyk86q-go-1.23.3/share/go'
GOSUMDB='sum.golang.org'
GOTOOLCHAIN='auto'
GOTOOLDIR='/nix/store/zhq8dnjbhwspzdglyq28j74axvqyk86q-go-1.23.3/share/go/pkg/tool/linux_amd64'
GOVERSION='go1.23.3'
GOTELEMETRY='off'
GOTELEMETRYDIR='/home/user/.config/go/telemetry'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
CGO_CFLAGS='-O2 -g'
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1389248914=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

I was writing some quick and inefficient code to get a problem answer fast for advent of code day5 and noticed that the program exits prematurely when breaking from an inner loop to an outer loop using a label -- though it does so only when using a larger input.

I'm not sure if this is an issue with the runtime or I'm not using the language correctly -- if the latter is true; I'm sorry for wasting your time, otherwise happy to help.

### What did you see happen?

Program exits prematurely without errors when using a larger dataset, with a smaller input the program runs as expected.

### What did you expect to see?

How to reproduce

- not working example: https://go.dev/play/p/uuWKb5CDsxd
- working example (replaced break OUTER with a func): https://go.dev/play/p/x8ikpK-VD99

**Comment by randall77** [comment]
I'm pretty sure this is working as expected. The only line of code that should execute after your `break OUTER` is the `fmt.Printf` at line 66.
Perhaps you meant `continue OUTER`? Or put the `OUTER` label one loop in?

**Comment by lfaoro** [comment]
thank you @randall77
