### ISSUE TITLE
x/website/_content/doc/modules: invalid require directive example 

### ISSUE THREAD

**Issue by Eynorey** [golang/go#70747]
### What is the URL of the page with the issue?
 
https://go.dev/doc/modules/managing-source#multiple-module-source
 
### What is your user agent?

n/a
 
### Screenshot
 
![image](https://github.com/user-attachments/assets/f00c5c23-6174-4e75-9b67-01666c0999ce) 
 
### What did you do?
 
n/a
 
### What did you expect to see?
 
The doc describes the setup of a mono-repository with multiple modules that each have their own version.

In the example it says that module `module1` can be versioned by pushing the version tag `module1/v1.2.3`, but then incorrectly states the the require directive for that module and that version needs to be `example.com/mymodules/module1 module1/v1.2.3`, whereas instead it needs to be `example.com/mymodules/module1 v1.2.3`.

```diff
+ Module path as given in a user’s require directive: example.com/mymodules/module1 v1.2.3
```
 
### What did you see instead?

```diff
- Module path as given in a user’s require directive: example.com/mymodules/module1 module1/v1.2.3
```

**Comment by findleyr** [comment]
Thanks for reporting.
