### ISSUE TITLE
os: io.Copy(net.Conn, os.Stdin) on MacOS terminate immediately without waiting for input

### ISSUE THREAD

**Issue by tiendo1011** [golang/go#70763]
### Go version

go version go1.23.3 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/tien/Library/Caches/go-build'
GOENV='/Users/tien/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/tien/.asdf/installs/golang/1.23.3/packages/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/tien/.asdf/installs/golang/1.23.3/packages'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/Users/tien/.asdf/installs/golang/1.23.3/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/Users/tien/.asdf/installs/golang/1.23.3/go/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.23.3'
GODEBUG=''
GOTELEMETRY='local'
GOTELEMETRYDIR='/Users/tien/Library/Application Support/go/telemetry'
GCCGO='gccgo'
GOARM64='v8.0'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/tien/code/learning/the-go-programming-language/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/fw/flzm6v7d6dn9n3255s6c69v00000gn/T/go-build4294646491=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

Running a server: https://go.dev/play/p/5I1sJlo64VB
And a client: https://go.dev/play/p/fOMykC2RbYs

### What did you see happen?

The client exits immediately without waiting for the input

### What did you expect to see?

The client wait for the input

**Comment by seankhliao** [comment]
consider checking the error on the copy operation

**Comment by tiendo1011** [comment]
@seankhliao there is no error, io.Copy returns `0, nil`

**Comment by seankhliao** [comment]
and how are you running this?

**Comment by tiendo1011** [comment]
@seankhliao I'm using `go run` to run the server & the client files separately

**Comment by ianlancetaylor** [comment]
I tried it on a Darwin system using Go tip and `io.Copy` returned an error:

    readfrom tcp [::1]:51606->[::1]:8000: sendfile: operation not supported

**Comment by ianlancetaylor** [comment]
CC @panjf2000

**Comment by ianlancetaylor** [comment]
Marking as release blocker since we shouldn't get a sendfile error from an `io.Copy` call.

I haven't tested earlier Go releases.

**Comment by ianlancetaylor** [comment]
With Go 1.22 the program works as expected.

With Go 1.23 the program exits immediately with no error, as reported by this bug report.

**Comment by ianlancetaylor** [comment]
In Go 1.23 the program fails because it uses `Stat` to get the size of standard input, comes up with 0, and proceeds to copy 0 bytes.

In Go 1.24 it makes it into calling `sendfile`, which fails with the error `ESOCKTNOSUPPORT`, which is not handled by internal/poll.sendFile.

**Comment by ianlancetaylor** [comment]
@gopherbot Please open backport to 1.23

This is a simple program that broke with some `sendfile` work in the Go 1.23 release.  Earlier releases are OK.

**Comment by ianlancetaylor** [comment]
CC @neild

**Comment by ianlancetaylor** [comment]
Sorry, it's not `ESOCKTNOSUPPORT`, it's `ENOTSUP`.
