### ISSUE TITLE
x/pkgsite: package removal request for github.com/Dkamps18/aes256gcm

### ISSUE THREAD

**Issue by Dkamps18** [golang/go#70762]
What is the path of the package that you would like to have removed?
https://pkg.go.dev/github.com/Dkamps18/aes256gcm

Are you the owner of this package?
Yes

What is the reason that you could not retract this package instead?
Repo was published on accident, and I have since made the repo private and would like to stop public access to the package

**Comment by findleyr** [comment]
This is done. Please allow a few hours for the change to propagate.
