### ISSUE TITLE
reflect: document missing panic behavior for non-assignable values in `reflect.Grow`

### ISSUE THREAD

**Issue by gazerro** [golang/go#70760]
Currently, the documentation for `reflect.Grow` does not mention that the method panics if the value passed is not assignable:

> It panics if v's Kind is not a Slice or if n is negative or too large to allocate the memory.

However, if `v` is not assignable (either because it was obtained using an unexported field or it is not addressable), `Grow` will also panic. For [example](https://go.dev/play/p/3uFHojlDy8K):

```
package main

import (
	"reflect"
)

func main() {
	reflect.ValueOf([]int{1, 2, 3}).Grow(5)
}
```

**Comment by randall77** [comment]
Same is true for the `Set*` methods, or `Copy` when the destination is an array.
We mention in some cases that they panic if `CanSet` is false, but fairly inconsistently.

**Comment by gazerro** [comment]
It’s not immediately obvious that `Grow` can panic for certain slices, such as in the following example, which correctly panics:

```
s := []int{1, 2, 3}
reflect.ValueOf(s).Grow(5)
```

I believe this behavior should be documented, along with the other cases mentioned by @randall77.
