### ISSUE TITLE
crypto: align FIPS mode GenerateKey behavior with non-FIPS mode

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#70772]
I initially made the GenerateKey functions ignore the rand parameter, because using anything but the FIPS DRBG makes the key non-compliant. However, this is the only subtle behavior difference between FIPS and non-FIPS mode (the others are the explicit change in crypto/tls behavior, and stuff getting slower).

We discussed this with @rsc and @rolandshoemaker and agreed to change it to work like Go+BoringCrypto for now, and then maybe consider ignoring the rand parameter entirely in Go 1.25 (regardless of FIPS mode).

Tracking issue for making the change in Go 1.24. See #69536.

**Comment by aclements** [comment]
Does this need to block rc1 or can it be post-rc1?

**Comment by FiloSottile** [comment]
It only affects FIPS mode, so I think it's ok post-rc1.
