### ISSUE TITLE
x/pkgsite: package removal request for github.com/kkrypt0nn/centauri

### ISSUE THREAD

**Issue by kkrypt0nn** [golang/go#70788]
### What is the path of the package that you would like to have removed?

https://pkg.go.dev/github.com/kkrypt0nn/centauri

### Are you the owner of this package?

Yes - see the repository with retraction rules -> https://github.com/kkrypt0nn/centauri

### What is the reason that you could not retract this package instead?

The project has been put aside for some time already and the repository has now been deleted. I've created the same repository again just to publish the retractions as I forgot about them. I'd like the documentations of every version to be removed from the website as well.

Many thanks in advance

**Comment by findleyr** [comment]
This is done. Please allow a few hours for the change to propagate.
