### ISSUE TITLE
net/http: Connection reset on file upload

### ISSUE THREAD

**Issue by 0tanay** [golang/go#70798]
### Go version

go version go1.23.4 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/tanay/.cache/go-build'
GOENV='/home/tanay/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/tanay/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/tanay/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/lib/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/lib/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.23.4'
GODEBUG=''
GOTELEMETRY='local'
GOTELEMETRYDIR='/home/tanay/.config/go/telemetry'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2736456403=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

https://go.dev/play/p/Td2zJWsHagm

Uploaded a file of size > 10MiB through the web form on:
- `localhost:8080/case/1/`
- `localhost:8080/case/2/`

### What did you see happen?

The handler Case1 closes the connection without sending any response - either through `http.Error()` or `w.WriteHeader()`.

When the same file is uploaded, the Case2 handler returns the correct error response. It looks like the only difference is the call to `ParseMultipartForm()` before sending a reply.

### What did you expect to see?

The Case1 handler should return an HTTP response with status code 200 or 500.

**Comment by seankhliao** [comment]
see the above links, the connection is broken on a lower level because of full buffers.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
