### ISSUE TITLE
x/website/_content/doc: document steps for vendored standard library dependencies

### ISSUE THREAD

**Issue by Agent-Hellboy** [golang/go#70799]
### What is the URL of the page with the issue?

https://go.dev/doc/contribute

### What is your user agent?

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0

### Screenshot

![Screenshot from 2024-12-12 12-40-22](https://github.com/user-attachments/assets/9a383d25-fb4f-4148-8eb2-7396420e95f0)

### What did you do?

The other day, I was working on a Go module issue and couldn't build the Go binary with my local x/mod repository. A Go developer then shared some steps to follow: [comment](https://github.com/golang/go/issues/70632#issuecomment-2529251392).

### What did you see happen?

I was not able to build go binary with my local `x/mod` 

### What did you expect to see?

Documenting these steps somewhere near the section I pointed out in my screenshot? I couldn’t find it here: [Go mod doc](https://github.com/golang/website/blob/master/_content/ref/mod.md). If it’s documented elsewhere, how about adding a reference to it on the contribution page?

I’d be happy to send a patch—I may learn a few things about website architecture here.

**Comment by seankhliao** [comment]
The instructions are pretty standard for any module where the change is in a dependency, it's not specific to std or cmd.

I think this is out of scope for the referenced pages.
