### ISSUE TITLE
x/pkgsite: package removal request for https://pkg.go.dev/code.weizhuang.net/go/ght & https://pkg.go.dev/code.weizhuang.net/go/ght

### ISSUE THREAD

**Issue by hebuqi** [golang/go#70805]
Request for package removal from pkg.go.dev: Due to changes in the repository domain and the deletion of content from the previous domain, the following packages should be removed from pkg.go.dev:

https://pkg.go.dev/code.weizhuang.net/go/ght
https://pkg.go.dev/sea.weizhuang.net/go/ght
These packages are no longer maintained or updated.

**Comment by seankhliao** [comment]
Duplicate of #70806
