### ISSUE TITLE
x/pkgsite: package removal request for code.weizhuang.net/go/ght sea.weizhuang.net/go/ght

### ISSUE THREAD

**Issue by hebuqi** [golang/go#70806]
**What is the path of the package that you would like to have removed?**
Help to remove the following two packages from pkg.go.dev as they are discarded due to domain changes and content deletion:

https://pkg.go.dev/code.weizhuang.net/go/ght
https://pkg.go.dev/sea.weizhuang.net/go/ght
These packages are no longer maintained or updated.

**Are you the owner of this package?**
Yes, I am the owner of the packages.

**What is the reason that you could not retract this package instead?**
Because the packages are no longer maintained, and the repositories have been deleted and are no longer updated.

**Comment by seankhliao** [comment]
we'll need you to somehow prove you are the owner of the modules. right now I don't see any link between the module and you.

**Comment by hebuqi** [comment]
The new repository address is now hosted under a different domain, wfjr.weizhuang.net
![image](https://github.com/user-attachments/assets/23275a79-3d3a-4339-abf4-0c9eabb28996)

**Comment by hebuqi** [comment]
The previous domain was used for other purposes, so I will no longer be using it for repository access.
