### ISSUE TITLE
perf record output is not correct in arm64.

### ISSUE THREAD

**Issue by zdyj3170101136** [golang/go#70804]
### Go version

go version go1.22.7 (Red Hat 1.22.7-1.0.2.al8) linux/arm64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/root/.cache/go-build'
GOENV='/root/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/root/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/root/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/lib/golang'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='local'
GOTOOLDIR='/usr/lib/golang/pkg/tool/linux_arm64'
GOVCS=''
GOVERSION='go1.22.7 (Red Hat 1.22.7-1.0.2.al8)'
GCCGO='gccgo'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1690956932=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

run benchmark:
```
package main

import (
        "encoding/json"
        "net/http"
        _ "net/http/pprof"
)

func main() {
        go func() {
                http.ListenAndServe(":7079", nil )
        }()
        for {
                json.Marshal([]byte("sss"))
        }
}
```

use perf:
```
perf record -a -g sleep 30s
perf report
```

### What did you see happen?

perf report is very strange:

<img width="1068" alt="截屏2024-12-12 下午7 41 46" src="https://github.com/user-attachments/assets/944c50c1-a4b0-4cc5-9a6d-059929161a99" />

### What did you expect to see?

the perf report should match the go pprof:
<img width="1656" alt="截屏2024-12-12 下午7 41 03" src="https://github.com/user-attachments/assets/f199f95c-e7e4-44a8-aff4-31a678bfb4bd" />

**Comment by seankhliao** [comment]
I think this is #58835

**Comment by zdyj3170101136** [comment]
<img width="1641" alt="截屏2024-12-20 下午5 09 30" src="https://github.com/user-attachments/assets/843ebed3-b8d7-4a03-a298-b632d160c220" />

@seankhliao  

it is the flamegraph generated by perf.

very different with go pprof.

not same problem.
