### ISSUE TITLE
proposal: crypto/x509: Export CertPool Length

### ISSUE THREAD

**Issue by zapisanchez** [golang/go#70819]
### Proposal Details

Actually the only way to know if you have some into a certpool is 
```
if (cp.Equal(&x509.CertPool{})) {
fmt.Printf("CertPool is empty")
}
```

This way, we only can now if empty or not, but we don't now any about the number of certificates added.

I propose to export the len method 

```
func (s *CertPool) Len() int {
	if s == nil {
		return 0
	}
return len(s.lazyCerts)
}
```

**Comment by seankhliao** [comment]
this would be at best misleading. if using the system verifier, the size works be zero but there are roots that can be used.
