### ISSUE TITLE
x/pkgsite: etc/passwd for remote server 

### ISSUE THREAD

**Issue by Ammar-UT** [golang/go#70822]
### What is the URL of the page with the issue?

https://pkg.go.dev/os#OpenFile

### What is your user agent?

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0

### Screenshot

![image](https://github.com/user-attachments/assets/54a4cfd1-51aa-4be7-a540-6e6c11fe05f3)

### What did you do?

just open etc/passwd file and print it's value 

### What did you see happen?

etc/passwd 

### What did you expect to see?

nothing

**Comment by seankhliao** [comment]
the playground is a self contained sandbox, I believe this isn't a concern.
