### ISSUE TITLE
net/http: infinite redirect loop with use of path variables

### ISSUE THREAD

**Issue by WestleyK** [golang/go#70832]
### Go version

go version go1.22.10 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/westley/.cache/go-build'
GOENV='/home/westley/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/westley/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/westley/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/home/westley/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.10.linux-amd64'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/home/westley/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.10.linux-amd64/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22.10'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/westley/codes/go-http-slash-redirect/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2802018030=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

While using go 1.22.10, use of multiple path variables with wildcards could result in a infinite http redirect loop

```go
package main

import (
	"fmt"
	"log"
	"net/http"
)

func main() {
	mux := http.NewServeMux()

	// Input path: /api/foo/ will redirect to: /api/foo/
	mux.Handle("GET /api/{resource_name}/{sub_resource}/{resource_id...}", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintf(w, "Resource: %s/%s -> %s", r.PathValue("resource_name"), r.PathValue("sub_resource"), r.PathValue("resource_id"))
	}))

	s := http.Server{Handler: mux, Addr: ":8000"}
	log.Fatalln(s.ListenAndServe())
}
```

```console
$ curl localhost:8000/api/foo/
<a href="/api/foo/">Moved Permanently</a>.
```

This seemed to be fixed in go 1.23.0 (returning 404), I found no details on this in release changelogs about this. I dont know if 1.22 is still supported. If 1.22 is not supported anymore, then this can be discarded. But it would be nice to see this fix listed in the changelogs, to provide additional documented reasons for upgrading. (maybe I missed it?)

### What did you see happen?

Using a path definition of `GET /api/{resource_name}/{sub_resource}/{resource_id...}`, and an input path of `/api/foo/` will result in a redirect to `/api/foo/`, which is the same as the input path, so its a redirect loop.

### What did you expect to see?

A 404 response.

**Comment by seankhliao** [comment]
upgrade to 1.23 https://go.dev/play/p/738_WErhkKv

**Comment by zigo101** [comment]
Why close it. Go 1.22 is still in maintaining.

**Comment by ianlancetaylor** [comment]
This kind of bug doesn't meed our criteria for backporting, because the user can avoid it by using different handler patterns.  See https://go.dev/wiki/MinorReleases.

**Comment by zigo101** [comment]
The reason is much better than the one to close it. :D
