### ISSUE TITLE
range generics list type error

### ISSUE THREAD

**Issue by epowsal** [golang/go#70842]
### Go version

go 1.23.1 windows amd64

### Output of `go env` in your module/workspace:

```shell
not need
```

### What did you do?

define type:
type QuickSets[T any] []*QuickSet[T]

add func:
func (qs *QuickSets[T]) Clac(cmpf func(a, b T) int) (c []T) {
	as1 := [][]T{}
	for qi, a := range qs {
            as1 = append(as1, qs[qi])
        }
        return c
}

### What did you see happen?

cannot range over qs (variable of type *QuickSets[T])

### What did you expect to see?

make it can range

**Comment by Jorropo** [comment]
Try `*qs`, you can't range nor index pointer to slices to begin with:
```
a := []int{42}
b := &a
for range b // does not work
b[0] = 1337 // does not work
```
