### ISSUE TITLE
x/pkgsite: package removal request for github.com/bernardbaker

### ISSUE THREAD

**Issue by bernardbaker** [golang/go#70858]
### What is the path of the package that you would like to have removed?

github.com/bernardbaker/qiba.core

### Are you the owner of this package?

I am the owner.

### What is the reason that you could not retract this package instead?

Accidental published all the files and a plain text password is listed.

**Comment by findleyr** [comment]
This is done. Please allow a few hours to propagate.

**Comment by bernardbaker** [comment]
Thank you @findleyr ⭐
