### ISSUE TITLE
import/fmt: package iter is not in std (/opt/homebrew/Cellar/go/1.23.4/libexec/src/iter)

### ISSUE THREAD

**Issue by kundkingan** [golang/go#70867]
### Go version

go version go1.23.4 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/davidandersson/Library/Caches/go-build'
GOENV='/Users/davidandersson/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/davidandersson/go/pkg/mod'
GONOPROXY='github.com/getaccept/*'
GONOSUMDB='github.com/getaccept/*'
GOOS='darwin'
GOPATH='/Users/davidandersson/go'
GOPRIVATE='github.com/getaccept/*'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/opt/homebrew/Cellar/go/1.23.4/libexec'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='local'
GOTOOLDIR='/opt/homebrew/Cellar/go/1.23.4/libexec/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.23.4'
GODEBUG=''
GOTELEMETRY='local'
GOTELEMETRYDIR='/Users/davidandersson/Library/Application Support/go/telemetry'
GCCGO='gccgo'
GOARM64='v8.0'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD='/Users/davidandersson/go/src/internal-services/go.mod'
GOWORK='/Users/davidandersson/go/src/internal-services/go.work'
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/rx/px_hdft96ks5npgwy19phydw0000gn/T/go-build2739982723=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

Installed go 1.23.4 with brew, trying to run any go code but keep getting `package iter is not in std`  from basically any import.

### What did you see happen?

/opt/homebrew/bin/go test -timeout 10s -run ^Test_approvalTimeout$ github.com/getaccept/operations/pkg/cmd/approval-timeout -v -race

/opt/homebrew/Cellar/go/1.23.4/libexec/src/reflect/iter.go:7:8: package iter is not in std (/opt/homebrew/Cellar/go/1.23.4/libexec/src/iter)

### What did you expect to see?

A test log

**Comment by seankhliao** [comment]
that seems most likely to be a corrupt installation (a brew problem).

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by orkoden** [comment]
@kundkingan 

Setting these two environment variables solved it for me.

```
export GOPROXY=https://proxy.golang.org,direct
export GOSUMDB="sum.golang.org"

```
