### ISSUE TITLE
x/arch: TestObjdumpRISCV64TestDecodeGNUSyntaxdata failed with objdump

### ISSUE THREAD

**Issue by mengzhuo** [golang/go#70864]
### Go version

go version go1.23.2 linux/riscv64

### Output of `go env` in your module/workspace:

```shell
go builder farm
```

### What did you do?

Failure with Luci:
https://luci-milo.appspot.com/ui/p/golang/builders/ci/x_arch-go1.24-linux-riscv64/b8728442533559969217/overview

```
--- FAIL: TestObjdumpRISCV64TestDecodeGNUSyntaxdata (0.16s)
totalTest: 390 total skip: 21 total error: 79
    ext_test.go:172: decode(bb003108) = "add.uw x1,x2,x3", 4, want ".insn 4, 0x083100bb", 4
```

### What did you see happen?

[Luci logs](https://luci-milo.appspot.com/ui/p/golang/builders/ci/x_arch-go1.24-linux-riscv64/b8728442533559969217/overview)

### What did you expect to see?

Test pass.

**Comment by mengzhuo** [comment]
cc @lrzlin

**Comment by lrzlin** [comment]
FIx: https://go-review.googlesource.com/c/arch/+/636735
