### ISSUE TITLE
x/pkgsite: module not found but is available in proxy

### ISSUE THREAD

**Issue by cuteLittleDevil** [golang/go#70865]
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/cuteLittleDevil/go-jt808@v1.1.0

### What is your user agent?

proxy.golang.org

### Screenshot

<img width="997" alt="image" src="https://github.com/user-attachments/assets/7fa5a47e-70fb-4c42-bb42-36ae8688e56c" />

### What did you do?

1. Tag exists
https://proxy.golang.org/github.com/cute%21little%21devil/go-jt808/@v/v1.1.0.info

``` json
{"Version":"v1.1.0","Time":"2024-12-14T04:11:12Z","Origin":{"VCS":"git","URL":"https://github.com/cuteLittleDevil/go-jt808","Hash":"32c8c3fa672be175f648310f42b5abbd902c3fa2","Ref":"refs/tags/v1.1.0"}}
```

2. Failed to create a web page
https://pkg.go.dev/github.com/cuteLittleDevil/go-jt808@v1.1.0

3. Forced update does not take effect
``` 
go get -u github.com/cuteLittleDevil/go-jt808@v1.1.0         
go: added github.com/cuteLittleDevil/go-jt808 v1.1.0
```

### What did you see happen?

doc  not updated

### What did you expect to see?

doc updated within hours

**Comment by hyangah** [comment]
Does this module have any go package? The repo has multiple go modules but the github.com/cuteLittleDevil/go-jt808 module (root of the repository) contains no go package. I guess pkg.go.dev skips a module that has no go packages.

On the other hand, I see modules in the subfolders can be found correctly from pkg.go.dev.
E.g. https://pkg.go.dev/github.com/cuteLittleDevil/go-jt808/terminal@v1.1.0
     
pkg.go.dev is the site for package documentation, so this is WAI.

**Comment by cuteLittleDevil** [comment]
> Does this module have any go package? The repo has multiple go modules but the github.com/cuteLittleDevil/go-jt808 module (root of the repository) contains no go package. I guess pkg.go.dev skips a module that has no go packages.这个模块有 go 包吗？存储库具有多个 go 模块，但 github.com/cuteLittleDevil/go-jt808 模块（存储库的根目录）不包含 go 包。我猜 pkg.go.dev 跳过了一个没有 go 包的模块。
> 
> On the other hand, I see modules in the subfolders can be found correctly from pkg.go.dev.另一方面，我看到可以从 pkg.go.dev 正确地找到子文件夹中的模块。 E.g. https://pkg.go.dev/github.com/cuteLittleDevil/go-jt808/terminal@v1.1.0例如 https://pkg.go.dev/github.com/cuteLittleDevil/go-jt808/terminal@v1.1.0
> 
> pkg.go.dev is the site for package documentation, so this is WAI.pkg.go.dev 是包文档的站点，因此这是 WAI。

but you can see
```
https://pkg.go.dev/github.com/cuteLittleDevil/go-jt808
```
I want to update markdown.

**Comment by seankhliao** [comment]
you need a go module with go files for pkgsite to serve it

**Comment by cuteLittleDevil** [comment]
> you need a go module with go files for pkgsite to serve it您需要一个带有 Go 文件的 go 模块，以便 pkgsite 为其提供服务

I added the go file.
<img width="914" alt="image" src="https://github.com/user-attachments/assets/d5ca17df-789a-49a9-b90d-65b056a2c4f0" />

```
go get -u github.com/cuteLittleDevil/go-jt808@v1.2.0  

go: downloading github.com/cuteLittleDevil/go-jt808 v1.2.0
go: upgraded github.com/cuteLittleDevil/go-jt808 v1.1.0 => v1.2.0

```
<img width="587" alt="image" src="https://github.com/user-attachments/assets/e86e3068-031f-4236-bd34-7b4ea6399408" />

**Comment by cuteLittleDevil** [comment]
> Does this module have any go package? The repo has multiple go modules but the github.com/cuteLittleDevil/go-jt808 module (root of the repository) contains no go package. I guess pkg.go.dev skips a module that has no go packages.这个模块有 go 包吗？存储库具有多个 go 模块，但 github.com/cuteLittleDevil/go-jt808 模块（存储库的根目录）不包含 go 包。我猜 pkg.go.dev 跳过了一个没有 go 包的模块。
> 
> On the other hand, I see modules in the subfolders can be found correctly from pkg.go.dev.另一方面，我看到可以从 pkg.go.dev 正确地找到子文件夹中的模块。 E.g. https://pkg.go.dev/github.com/cuteLittleDevil/go-jt808/terminal@v1.1.0例如 https://pkg.go.dev/github.com/cuteLittleDevil/go-jt808/terminal@v1.1.0
> 
> pkg.go.dev is the site for package documentation, so this is WAI.pkg.go.dev 是包文档的站点，因此这是 WAI。

You are right. I ignored it.
