### ISSUE TITLE
net/http: NewRequestWithContext links to wrong NewRequest

### ISSUE THREAD

**Issue by bradfitz** [golang/go#70875]
https://pkg.go.dev/net/http#NewRequestWithContext links to the wrong `NewRequest` func:

> either use the [NewRequest](https://pkg.go.dev/net/http#NewRequest) function in the net/http/httptest package

It should link to `httptest.NewRequest` instead.

/cc @neild

**Comment by seankhliao** [comment]
Duplicate of #70874
