### ISSUE TITLE
x/tools/gopls: completion: failed type assertion in inferExpectedTypeArg

### ISSUE THREAD

**Issue by adonovan** [golang/go#70889]
```
#!stacks
"panicdottypeI" && "inferExpectedTypeArg:+11"
```
Issue created by [stacks](https://pkg.go.dev/golang.org/x/tools/gopls/internal/telemetry/cmd/stacks).

```go
	// Infer the type parameters in a function call based on it's context
	sig := c.pkg.TypesInfo().Types[callNode.Fun].Type.(*types.Signature) // <--- panic here
	expectedResults := inferExpectedResultTypes(c, callNodeIdx)
	if typeParamIdx < 0 || typeParamIdx >= sig.TypeParams().Len() {
		return nil
	}
```

This stack `w_8rjA` was [reported by telemetry](https://storage.googleapis.com/prod-telemetry-merged/2024-12-16.json):

- `crash/crash`
- [`runtime.gopanic:+69`](https://cs.opensource.google/go/go/+/go1.23.4:src/runtime/panic.go;l=804)
- [`runtime.panicdottypeE:=275`](https://cs.opensource.google/go/go/+/go1.23.4:src/runtime/iface.go;l=275)
- [`runtime.panicdottypeI:+5`](https://cs.opensource.google/go/go/+/go1.23.4:src/runtime/iface.go;l=285)
- [`golang.org/x/tools/gopls/internal/golang/completion.(*completer).inferExpectedTypeArg:+11`](https://cs.opensource.google/go/x/tools/+/gopls/v0.17.0:gopls/internal/golang/completion/completion.go;l=2709)
- [`golang.org/x/tools/gopls/internal/golang/completion.expectedCandidate:+148`](https://cs.opensource.google/go/x/tools/+/gopls/v0.17.0:gopls/internal/golang/completion/completion.go;l=2427)
- [`golang.org/x/tools/gopls/internal/golang/completion.Completion:+150`](https://cs.opensource.google/go/x/tools/+/gopls/v0.17.0:gopls/internal/golang/completion/completion.go;l=651)
- [`golang.org/x/tools/gopls/internal/server.(*server).Completion:+19`](https://cs.opensource.google/go/x/tools/+/gopls/v0.17.0:gopls/internal/server/completion.go;l=43)
- [`golang.org/x/tools/gopls/internal/protocol.serverDispatch:+193`](https://cs.opensource.google/go/x/tools/+/gopls/v0.17.0:gopls/internal/protocol/tsserver.go;l=363)
- [`golang.org/x/tools/gopls/internal/lsprpc.(*streamServer).ServeStream.ServerHandler.func3:+5`](https://cs.opensource.google/go/x/tools/+/gopls/v0.17.0:gopls/internal/protocol/protocol.go;l=160)
- [`golang.org/x/tools/gopls/internal/lsprpc.(*streamServer).ServeStream.handshaker.func4:+52`](https://cs.opensource.google/go/x/tools/+/gopls/v0.17.0:gopls/internal/lsprpc/lsprpc.go;l=509)
- [`golang.org/x/tools/gopls/internal/protocol.Handlers.MustReplyHandler.func1:+2`](https://cs.opensource.google/go/x/tools/+/gopls/v0.17.0:internal/jsonrpc2/handler.go;l=35)
- [`golang.org/x/tools/gopls/internal/protocol.Handlers.AsyncHandler.func2.2:+3`](https://cs.opensource.google/go/x/tools/+/gopls/v0.17.0:internal/jsonrpc2/handler.go;l=104)
- `runtime.goexit:+0`
```
golang.org/x/tools/gopls@v0.17.0 go1.23.4 darwin/amd64 vscode (1)
```
Dups: brclNw

**Comment by findleyr** [comment]
Hmm, we may want to consider this for a v0.17.1.

**Comment by adonovan** [comment]
This stack `brclNw` was [reported by telemetry](https://storage.googleapis.com/prod-telemetry-merged/2024-12-16.json):

- `crash/crash`
- [`runtime.gopanic:+69`](https://cs.opensource.google/go/go/+/go1.23.4:src/runtime/panic.go;l=804)
- [`runtime.panicdottypeE:=275`](https://cs.opensource.google/go/go/+/go1.23.4:src/runtime/iface.go;l=275)
- [`runtime.panicdottypeI:+5`](https://cs.opensource.google/go/go/+/go1.23.4:src/runtime/iface.go;l=285)
- [`golang.org/x/tools/gopls/internal/golang/completion.(*completer).inferExpectedTypeArg:+11`](https://cs.opensource.google/go/x/tools/+/gopls/v0.17.0:gopls/internal/golang/completion/completion.go;l=2709)
- [`golang.org/x/tools/gopls/internal/golang/completion.expectedCandidate:+163`](https://cs.opensource.google/go/x/tools/+/gopls/v0.17.0:gopls/internal/golang/completion/completion.go;l=2442)
- [`golang.org/x/tools/gopls/internal/golang/completion.Completion:+150`](https://cs.opensource.google/go/x/tools/+/gopls/v0.17.0:gopls/internal/golang/completion/completion.go;l=651)
- [`golang.org/x/tools/gopls/internal/server.(*server).Completion:+19`](https://cs.opensource.google/go/x/tools/+/gopls/v0.17.0:gopls/internal/server/completion.go;l=43)
- [`golang.org/x/tools/gopls/internal/protocol.serverDispatch:+193`](https://cs.opensource.google/go/x/tools/+/gopls/v0.17.0:gopls/internal/protocol/tsserver.go;l=363)
- [`golang.org/x/tools/gopls/internal/lsprpc.(*streamServer).ServeStream.ServerHandler.func3:+5`](https://cs.opensource.google/go/x/tools/+/gopls/v0.17.0:gopls/internal/protocol/protocol.go;l=160)
- [`golang.org/x/tools/gopls/internal/lsprpc.(*streamServer).ServeStream.handshaker.func4:+52`](https://cs.opensource.google/go/x/tools/+/gopls/v0.17.0:gopls/internal/lsprpc/lsprpc.go;l=509)
- [`golang.org/x/tools/gopls/internal/protocol.Handlers.MustReplyHandler.func1:+2`](https://cs.opensource.google/go/x/tools/+/gopls/v0.17.0:internal/jsonrpc2/handler.go;l=35)
- [`golang.org/x/tools/gopls/internal/protocol.Handlers.AsyncHandler.func2.2:+3`](https://cs.opensource.google/go/x/tools/+/gopls/v0.17.0:internal/jsonrpc2/handler.go;l=104)
- `runtime.goexit:+0`
```
golang.org/x/tools/gopls@v0.17.0 go1.23.4 linux/amd64 vscode (1)
```
