### ISSUE TITLE
cgo: CGO callback bug under Windows

### ISSUE THREAD

**Issue by wnxd** [golang/go#70896]
### Go version

go version go1.23.4 windows/amd64

### Output of `go env` in your module/workspace:

```shell
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\htlm0\AppData\Local\go-build
set GOENV=C:\Users\htlm0\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\htlm0\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\htlm0\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Users\htlm0\scoop\apps\go\current
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Users\htlm0\scoop\apps\go\current\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.23.4
set GODEBUG=
set GOTELEMETRY=local
set GOTELEMETRYDIR=C:\Users\htlm0\AppData\Roaming\go\telemetry
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\htlm0\AppData\Local\Temp\go-build1380692712=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

The callback function wrapped by CGO is passed to Unicron. After the callback is completed, the pointer data of EBP is abnormal and is filled with EE FE EE FE EE FE EE FE

### What did you see happen?

![1](https://github.com/user-attachments/assets/2ef625dd-5ff1-4b02-90b3-24ec0ddc6321)
![2](https://github.com/user-attachments/assets/503f2200-065c-4358-ae05-97e79861b398)
![3](https://github.com/user-attachments/assets/51e0dcd1-96ee-4dc3-b0d2-b8f764f12aab)
![4](https://github.com/user-attachments/assets/47463dff-9ae6-4824-8e3e-42d5ea2a0206)
![5](https://github.com/user-attachments/assets/d65eb757-a113-4eaf-a73e-6672f8fd366f)
![6](https://github.com/user-attachments/assets/b9655462-f4b1-4299-b71c-e117447e91a7)

### What did you expect to see?

Because of the above situation, the program runs with the exception of EXCEPTION_ACCESS_VIOLATION

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
