### ISSUE TITLE
crypto/ecdsa: fips140=only does not allow any ecdsa key generation

### ISSUE THREAD

**Issue by kruskall** [golang/go#70894]
### Go version

go1.24-95b433e

### Output of `go env` in your module/workspace:

```shell
GOFIPS140='latest'
```

### What did you do?

```go
package main

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"fmt"
)

func main() {
	_, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	fmt.Println(err)
}
```

- `gotip build -o bug main.go && GODEBUG=fips140=only ./bug`
- `./bug`

### What did you see happen?

program exited with the following error:

```
crypto/ecdsa: only crypto/rand.Reader is allowed in FIPS 140-only mode
```

### What did you expect to see?

no error

**Comment by mauri870** [comment]
Thanks, looks like this was a mistake.

cc @FiloSottile

**Comment by mauri870** [comment]
cc @golang/release since this should be fixed in the next RC.

**Comment by FiloSottile** [comment]
Ooops, sorry! I need to put together a proper test for fips140=only.
