### ISSUE TITLE
x/pkgsite: package removal request for github.com/hugo-cachon/vitals

### ISSUE THREAD

**Issue by xororist** [golang/go#70903]
### What is the path of the package that you would like to have removed?

github.com/hugo-cachon/vitals

### Are you the owner of this package?

Yes.

The previous url of the project was 'github.com/hugo-cachon/vitals' before my username change. It is now 'github.com/xororist/vitals'.

![image](https://github.com/user-attachments/assets/dbc8c600-4464-474a-9629-0a5957349d19)

### What is the reason that you could not retract this package instead?

This package has only been made for testing purposes and I don't want it to be published publicly.

**Comment by adonovan** [comment]
I confirm that github.com/hugo-cachon/vitals redirects to github.com/xororist/vitals and have made the necessary change. Please allow a few days for configuration to propagate.
