### ISSUE TITLE
generics func as parameter no type list will compile OK error 

### ISSUE THREAD

**Issue by epowsal** [golang/go#70922]
### Go version

go 1.23.1 windows amd64

### Output of `go env` in your module/workspace:

```shell
need not
```

### What did you do?

```go
func NewN[T any](cmpf func(a T, b T) int, values ...T) *QuickSet[T] {
	qs := &QuickSet[T]{}
	qs.Insert(cmpf, values...)
	return qs
}
func cmp[K comparable, V any](a, b *Item[K, V]) int {
	if a.ek[0] < b.ek[0] {
		return -1
	} else if a.ek[0] > b.ek[0] {
		return 1
	} else {
		return 0
	}
}

func (w *Wmap[K, V]) Put(key K, val V) error {
  cur.It[i].i = quickset.NewIt(cmp, &Item[K, V]{ek: ke, v: val, bv: true, i: nil})
  cur.It[i].i = quickset.NewIt(cmp[K, V], on)
   return nil
}
```

### What did you see happen?

func Put compiled OK without error.

### What did you expect to see?

it should compile error.

**Comment by seankhliao** [comment]
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
