### ISSUE TITLE
cmd/go/internal/work/security.go: invalid flag in `#cgo darwin LDFLAGS: -Wl,-rpath -Wl,@loader_path`

### ISSUE THREAD

**Issue by t0rr3sp3dr0** [golang/go#70923]
### Go version

go version go1.23.3 darwin/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/Users/pedro/Library/Caches/go-build'
GOENV='/Users/pedro/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/pedro/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/pedro/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/Users/pedro/sdk/go1.23.3'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/Users/pedro/sdk/go1.23.3/pkg/tool/darwin_amd64'
GOVCS=''
GOVERSION='go1.23.3'
GODEBUG=''
GOTELEMETRY='local'
GOTELEMETRYDIR='/Users/pedro/Library/Application Support/go/telemetry'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/pedro/Documents/git/sapsigner/impl/emu/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/_3/sh8y1_5d07q_5xhk9k8mncs80000gn/T/go-build4238436678=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

Run `go build main.go` in macOS with the following program.

<br />

- `main.go`

```go
package main

// #cgo darwin LDFLAGS: -Wl,-rpath,@loader_path
import "C"

func main() {}
```

### What did you see happen?

```console
% go build -v main.go
command-line-arguments
command-line-arguments: invalid flag in #cgo LDFLAGS: -Wl,-rpath,@loader_path
```

### What did you expect to see?

```console
% go build -v main.go
command-line-arguments
```

**Comment by t0rr3sp3dr0** [comment]
Following the guidance on https://golang.org/s/invalidflag, I request that `-Wl,-rpath,@ executable_path` and `-Wl,-rpath,@loader_path`, possibly suffixed with some path, be whitelisted.

These are directives used on macOS to allow a dynamic library search path that is relative to the executable or library. See https://forums.developer.apple.com/forums/thread/736728.

**Comment by t0rr3sp3dr0** [comment]
I see that there is already a rule for `rpath` defined here: https://github.com/golang/go/blob/4f0561f9d354233787de7aa9eff8119a2d4cd5c6/src/cmd/go/internal/work/security.go#L212C6-L212C42. But it explicitly excludes values for `rpath` that start with `@`.

I guess that's because on Linux `@` can be used to read from files. The solution for this is simple enough: if and only if we are on Darwin, allow values for `rpath` starting with `@`.

**Comment by seankhliao** [comment]
Duplicate of #40559
