### ISSUE TITLE
package type function can not reimplement for low memory using purpose

### ISSUE THREAD

**Issue by epowsal** [golang/go#70926]
### Go version

go 1.23.1 windows amd64

### Output of `go env` in your module/workspace:

```shell
not need
```

### What did you do?

```
func Test8(t *testing.T) {
	wm := New[[]byte, int]()
	wm.KeyFromBytes = func(b []byte) (k []byte) {
		return nil
	}
	wm.Put([]byte("ab"), 33)
	wm.Put([]byte("zb"), 34)
	wm.Put([]byte("cb"), 35)
	fmt.Println("Put end")
	fmt.Println(wm.Get([]byte("ab")))
	fmt.Println("Get end")
	fmt.Println(wm.Del([]byte("zb")))
	fmt.Println("Del end")
	fmt.Println(wm.Get([]byte("cb")))
	fmt.Println("Get 2 end")
}
```

### What did you see happen?

# wmap [wmap.test]
.\wmap_test.go:415:2: cannot assign to wm.KeyFromBytes (neither addressable nor a map index expression)
FAIL	wmap [build failed]

### What did you expect to see?

make golang suport reimplement for large items purpose.

**Comment by ianlancetaylor** [comment]
This looks like a misunderstanding of the language.  Show us a complete standalone test case.

Note that we do not use the issue tracker for questions.  You will get better and faster answers on a forum.  See https://go.dev/wiki/Questions.  Thanks.
