### ISSUE TITLE
slices: Concat allocates more than requested

### ISSUE THREAD

**Issue by adonovan** [golang/go#70935]
slices.Concat calls Grow(nil, size), which rounds up the capacity allocation using append's heuristic. For example, the slice returned by Concat may have len=1000 but cap=1023. Is this intentional? I would have thought that slices.Concat is often called when the exact final size is known and no further appends are intended, making this extra allocation wasteful.

Is the idea that rounding up to the size class is essentially free, and avoids reallocation in the not uncommon case that a single element or small handful of elements are added to the end of a large slice.Concat?  If so, a comment would be appreciated.

**Comment by ianlancetaylor** [comment]
Yes, the idea is to raise to the next size class.  See the comment in https://go.dev/cl/504882.

**Comment by zigo101** [comment]
The only inconsistency in the "slices" package is the "Repeat" function.
