### ISSUE TITLE
index.golang.org: missing /cached-only endpoint?

### ISSUE THREAD

**Issue by Thiht** [golang/go#70953]
Hello,

Following the documentation available at https://proxy.golang.org, it seems like a `/cached-only` endpoint should exist for `index.golang.org` but that doesn't seem to be the case.

> If you use the index to download many modules from the module mirror, you will want to use the /cached-only endpoint, described above.

```
# This works as expected
$ curl index.golang.org/index
{"Path":"golang.org/x/text","Version":"v0.3.0","Timestamp":"2019-04-10T19:08:52.997264Z"}
...
```

```
$ curl index.golang.org/cached-only/index   
not found
```

```
$ curl index.golang.org/cached-only      
not found
```

```
$ curl index.golang.org/index/cached-only
not found
```

Am I missing something something? Should this endpoint exist, or am I misunderstanding the documentation?

**Comment by seankhliao** [comment]
it's for modules, ex  https://proxy.golang.org/cached-only/golang.org/x/text/@v/v0.21.0.mod
