### ISSUE TITLE
weak: typo in comment on Pointer about batched allocations

### ISSUE THREAD

**Issue by rittneje** [golang/go#70972]
### Go version

n/a

### Output of `go env` in your module/workspace:

```shell
n/a
```

### What did you do?

I read the documentation for the upcoming [weak.Pointer](https://pkg.go.dev/weak#Pointer) type.

### What did you see happen?

The last paragraph says:

> The weak pointer for an unreferenced object in such an allocation may never be called if it always exists in the same batch as a referenced object.

I think there is a typo in this sentence, since as written it does not make sense to me. I believe it meant "nullified" or similar, not "called."

**Comment by ianlancetaylor** [comment]
CC @mknyszek

**Comment by mknyszek** [comment]
'Doh, yes. This was copied from the cleanup and finalizer documentation.
