### ISSUE TITLE
x/tools/go/pointer: explain deprecation

### ISSUE THREAD

**Issue by dannyc-grafana** [golang/go#70984]
### What is the URL of the page with the issue?

golang.org/x/tools/go/pointer

### What is your user agent?

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0

### What did you do?

I browsed to the page in quesiton

### What did you see happen?

Docs are returned, including a version string that clearly indicates the package is deprecated. However, the body of the documentation contains no reference to the reason for deprecation or warning about the same.

### What did you expect to see?

I think a warning at the top of the package docs stating that:
1. The package is deprecated and unmaintained.
2. **There are known correctness bugs**
3. More can be read at https://github.com/golang/go/issues/59676 

would be quite useful-- I eventually landed on the issue after digging around, but it took considerably more effort than I'd like to admit.

**Comment by adonovan** [comment]
I'm sorry the documentation was inadequate. Unfortunately this issue cannot practically be fixed because the module has already been deleted, and to change it we would need to revive it, modify it, and re-delete it.

I'm glad you at least found your own way to the explanation.

**Comment by dannyc-grafana** [comment]
Hopefully at a minimum now this thread will show up in issue and google
searches on the topic, thank you :).

It looks like the type aliasing stuff in newer go versions breaks something
in Pointer so we might see a few more folks in the coming months.
