### ISSUE TITLE
access: github tells me I can merge on golang/tools bypassing gerrit

### ISSUE THREAD

**Issue by Jorropo** [golang/go#70988]
Here is my view of https://github.com/golang/tools/pull/551
![image](https://github.com/user-attachments/assets/3290ec43-535c-43b5-8216-f4af228b60c9)
Here is how I think it should look taken from https://github.com/golang/go/pull/70983
![image](https://github.com/user-attachments/assets/451b0cb0-112c-40fa-abef-793128975a7c)

I guess if I pressed the button it would only corrupt the mirror and gopherbot would :crossed_fingers: force push over me or loudly error somewhere.

**Comment by Jorropo** [comment]
cc @dmitshur

**Comment by Jorropo** [comment]
I've checked all the repos under the `golang` github org that are marked with `[mirror]` description prefix.
Here is all the incorrectly configured ones I could find:
- https://github.com/golang/tools
- https://github.com/golang/sys
- https://github.com/golang/crypto

I'm sorry I had to find this a Dec 25th.

**Comment by mateusz834** [comment]
See #59048
