### ISSUE TITLE
spec: type switch evaluation order?

### ISSUE THREAD

**Issue by prattmic** [golang/go#70994]
If a type switch contains cases that are interfaces, then it is possible for multiple cases to match. For example, in https://go.dev/play/p/hiq-bYXX-MM the type is both `S` and `fmt.Stringer`.

As far as I can tell, the [spec](https://go.dev/ref/spec#Type_switches) doesn't define which of these cases should match.

For _expression switches_, the spec says "the case expressions, which need not be constants, are evaluated left-to-right and top-to-bottom; the first one that equals the switch expression triggers execution of the statements of the associated case; the other cases are skipped."

As far as I know, type switches behave the same way. It seems that the type switch section needs similar wording.

cc @griesemer

**Comment by zigo101** [comment]
The spec says:

> A type switch compares types rather than values. It is otherwise similar to an expression switch.

**Comment by prattmic** [comment]
Thanks, I suppose that covers it.
