### ISSUE TITLE
import/path:   Unable to run go program prompt invalid UTF-8 encoding

### ISSUE THREAD

**Issue by zhuzi0125** [golang/go#71047]
### Go version

go version go1.23.4 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/zhengzhoutan/Library/Caches/go-build'
GOENV='/Users/zhengzhoutan/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/zhengzhoutan/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/zhengzhoutan/go'
GOPRIVATE=''
GOPROXY='https://goproxy.cn,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.23.4'
GODEBUG=''
GOTELEMETRY='local'
GOTELEMETRYDIR='/Users/zhengzhoutan/Library/Application Support/go/telemetry'
GCCGO='gccgo'
GOARM64='v8.0'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='0'
GOMOD='/Users/zhengzhoutan/Documents/wechat-bot/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/tq/0z89psw52v1_fpjshlgk89qr0000gn/T/go-build571077288=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

zhengzhoutan@ZhengzhuiMac wechat-bot % go run main.go
# internal/bytealg
go_asm.h:1:1: invalid UTF-8 encoding
go_asm.h:1: expected identifier, found "\u0a11"
asm: assembly of /usr/local/go/src/internal/bytealg/compare_arm64.s failed
# internal/runtime/atomic
go_asm.h:1:1: invalid UTF-8 encoding
go_asm.h:1: expected identifier, found "\u0a11"
asm: assembly of /usr/local/go/src/internal/runtime/atomic/atomic_arm64.s failed

### What did you see happen?

When running the Go program, the following error was encountered:
# internal/bytealg
go_asm.h:1:1: invalid UTF-8 encoding
go_asm.h:1: expected identifier, found "\u0a11"
asm: assembly of /usr/local/go/src/internal/bytealg/compare_arm64.s failed
# internal/runtime/atomic
go_asm.h:1:1: invalid UTF-8 encoding
go_asm.h:1: expected identifier, found "\u0a11"
asm: assembly of /usr/local/go/src/internal/runtime/atomic/atomic_arm64.s failed

I have verified that atomic_arm64.s   is an etf-8 file, but I don't know how to solve it now

### What did you expect to see?

Successfully run the go program

**Comment by seankhliao** [comment]
sounds like you have a corrupted installation of go. 

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by zhuzi0125** [comment]
> 听起来你已经安装损坏了。
> 
> 与许多项目不同，Go 项目不使用 GitHub Issues 进行一般讨论或提问。GitHub Issues 仅用于跟踪错误和建议。
> 
> 如有疑问，请参阅https://github.com/golang/go/wiki/Questions


I have tried many installation methods but nothing works

> sounds like you have a corrupted installation of go.
> 
> Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.
> 
> For questions please refer to https://github.com/golang/go/wiki/Questions


I have tried many installation methods but nothing works

**Comment by zhuzi0125** [comment]
> sounds like you have a corrupted installation of go.
> 
> Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.
> 
> For questions please refer to https://github.com/golang/go/wiki/Questions


I have tried many installation methods but nothing works

**Comment by ianlancetaylor** [comment]
@zhuzi0125 Please use a forum.  See https://go.dev/wiki/Questions.
