### ISSUE TITLE
cmd/compile: incorrect location of panic during 2-phase execution of assignment statement

### ISSUE THREAD

**Issue by yaxum62** [golang/go#71054]
### Go version

go version go1.23.2 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/yaxum62/.cache/go-build'
GOENV='/home/yaxum62/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/yaxum62/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/yaxum62/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/lib/go-1.23'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/lib/go-1.23/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.23.2'
GODEBUG=''
GOTELEMETRY='local'
GOTELEMETRYDIR='/home/yaxum62/.config/go/telemetry'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/yaxum62/src/test/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build812913915=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

Original post: https://groups.google.com/g/golang-nuts/c/anNFVPtCGyQ/
Example code: https://go.dev/play/p/6RulNQwIk4n

The example code contains an assignment statement:

```
phase_2, foo.bar.value = "??????", compute_value()
```

The assignment statement will trigger nil pointer panic and contains visible side effects in both phases as described in [golang spec](https://go.dev/ref/spec#Assignment_statements):
 
> The assignment proceeds in two phases. First, the operands of [index expressions](https://go.dev/ref/spec#Index_expressions) and [pointer indirections](https://go.dev/ref/spec#Address_operators) (including implicit pointer indirections in [selectors](https://go.dev/ref/spec#Selectors)) on the left and the expressions on the right are all [evaluated in the usual order](https://go.dev/ref/spec#Order_of_evaluation). Second, the assignments are carried out in left-to-right order.

### What did you see happen?

The nil pointer panic happened after `compute_value()` expression is evaluated in phase 1 but before `phase_2` variable is updated in phase 2.

### What did you expect to see?

The nil pointer panic happened before `compute_value()` expression is evaluated in phase 1, as mentioned in [original post](https://groups.google.com/g/golang-nuts/c/anNFVPtCGyQ/m/em3Cd1RZBAAJ).

**Comment by randall77** [comment]
This looks like it is working correctly to me.

In phase 1, we need to evaluate 3 things:
```
foo.bar
"??????"
compute_value()
```
The order of evaluation between those 3 things is not specified. The first one nil-pointer panics, but that may happen before or after the call to `compute_value`.

Because phase 1 panics, phase 2 does not happen.

**Comment by yaxum62** [comment]
The spec mentioned the phase 1 is evaluated in "[usual order](https://go.dev/ref/spec#Order_of_evaluation)", which is very strict:
> when evaluating the [operands](https://go.dev/ref/spec#Operands) of an expression, **assignment**, or [return statement](https://go.dev/ref/spec#Return_statements), all function calls, method calls, [receive operations](https://go.dev/ref/spec#Receive%20operator), and [binary logical operations](https://go.dev/ref/spec#Logical_operators) are evaluated in **lexical left-to-right order**.

**Comment by randall77** [comment]
It is, but that statement relates only the ordering between those events listed (function call, method call, receive operator, or binary logic operator). There is only one such event here, a function call.
It goes on to say:

> However, the order of those events compared to the evaluation and indexing of x and the evaluation of y and z is not specified, except as required lexically.

More generally, the ordering of those events with respect to all other operations (of import here, a pointer dereference) is not guaranteed.

**Comment by yaxum62** [comment]
I see, thanks for the explanation! That makes more sense. I'll close this bug.

**Comment by robaho** [comment]
Isn’t this a problem though with it not being specified as the function could make the nil pointer dereference not or happen. (Ie what if foo is passed to the function call)

Why not specify this? This is the same sort of undefined behavior that makes C++ such a pain.

**Comment by randall77** [comment]
@robaho 
I think there is an argument to be made that Go is too lax in how it defines evaluation order. But we have the semantics we have; it would require a proposal to change the meaning of the language. And that proposal would require evidence that this is a real problem people run into. All I've seen in this area are toy programs that have confusing evaluation order that I personally would never give a +2 to in code review.

**Comment by robaho** [comment]
> @robaho I think there is an argument to be made that Go is too lax in how it defines evaluation order. But we have the semantics we have; it would require a proposal to change the meaning of the language. And that proposal would require evidence that this is a real problem people run into. All I've seen in this area are toy programs that have confusing evaluation order that I personally would never give a +2 to in code review.

Fair enough. Probably just triggered by being bitten by similar stuff in C++.

**Comment by zigo101** [comment]
see https://github.com/golang/go/issues/27804
