### ISSUE TITLE
x/pkgsite: searching for "new" symbols causes page to hang and eventually return 500 internal server error

### ISSUE THREAD

**Issue by jcbhmr** [golang/go#71052]
### What is the URL of the page with the issue?

https://pkg.go.dev/search?q=new&m=symbol

### What is your user agent?

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36

### Screenshot

![image](https://github.com/user-attachments/assets/efa5ee46-595d-425b-83bb-2b1845c7053b)
![image](https://github.com/user-attachments/assets/90a6f92a-4a07-4e76-a8eb-c4c396efbe81)

### What did you do?

1. Go to https://pkg.go.dev/
2. Search for "new" in the search box
3. Click the "Symbols" tab

### What did you see happen?

The page hangs for about 30 seconds and then the first time I did it showed the branded 500 error. The second time I tried it it showed the plaintext error.

### What did you expect to see?

The first 25 items that were called "new" only. The reason I was searching for "new" in the first place was to get an idea of how many stdlib types were using plain "packagename.New()" instead of "packagename.NewOtherType()". I expected to see stdlib packages (since they are usually ranked above all third-party packages) like log.New()

**Comment by seankhliao** [comment]
seems to work for me?

**Comment by seankhliao** [comment]
I think this is the same as #64422
