### ISSUE TITLE
append func append result error

### ISSUE THREAD

**Issue by epowsal** [golang/go#71057]
### Go version

go 1.23.1 windows amd64

### Output of `go env` in your module/workspace:

```shell
normal
```

### What did you do?

func TestIndex1(t *testing.T) {
	kb := []byte("ab")
	ke := append(kb, 0)
	ke = append(kb, ValPackf64(45)...)
	Pa(ke, ValPackf64(45))
}

### What did you see happen?

M:/work/tool/liteidex38.3-win64-qt5.15.2/bin/gotools.exe gotest -f index_test.go -v [M:/work/code/go/src/imap]
=== RUN   TestIndex1
--- FAIL: TestIndex1 (0.00s)
panic: []byte{0x61, 0x62, 0x40, 0x46, 0x80, 0x0, 0x0, 0x0, 0x0, 0x0}^[]byte{0x40, 0x46, 0x80, 0x0, 0x0, 0x0, 0x0, 0x0}	[13 imap.TestIndex1]imap/index_test.go<< [recovered]
	panic: []byte{0x61, 0x62, 0x40, 0x46, 0x80, 0x0, 0x0, 0x0, 0x0, 0x0}^[]byte{0x40, 0x46, 0x80, 0x0, 0x0, 0x0, 0x0, 0x0}	[13 imap.TestIndex1]imap/index_test.go<<

output have error.
output should:
0x61, 0x62, 0x00, 0x40, 0x46, 0x80, 0x0, 0x0, 0x0, 0x0, 0x0

### What did you expect to see?

right output.

**Comment by Jorropo** [comment]
This is not enough information to reproduce the bug.
Can you please post a https://go.dev/play/ link demonstrating the panic ?
