### ISSUE TITLE
x/tools/cmd/godoc: inconsistent reporting of synopsis vs command documentation

### ISSUE THREAD

**Issue by griesemer** [golang/go#7119]
<pre>1) In a $GOROOT/cmd/foo directory, create two files doc.go, main.go:

$ cat doc.go
// +build ignore

// Package foo is a foo bar.
package main

$ cat main.go
package main

2) godoc cmd/foo won't show any documentation, only the title:
COMMAND DOCUMENTATION

3) run godoc -http=:9000

4) Navigate to: <a href="http://localhost:9000/cmd/">http://localhost:9000/cmd/</a>
The synopsis for command foo is there:
foo         Package foo is a foo bar.

5) Click on command foo: The documentation only shows the title (not even the synopsis
anymore):
Command foo

Problem (suspicion, haven't analyzed in detail): The reason is that the synopsis is
collected in a separate pass, by traversing all directories and extracting documentation
from any .go file available. But when the documentation for the package is shown, the
go/build package is used to determine which files to include, and in this case the
documentation file is ignored from the build.

The solution is to remove the build tag and it will work consistently.  However, it is
confusing that a) the synopsis shows up anyway, and b) that for C commands documentation
is shown even though the build tag is (must be!) present. If one simply copies a C
command doc.go file and adjusts it for a command written in Go one is somewhat surprised
that it doesn't work.

Not sure what the proper solution is - perhaps godoc should say that files were excluded
via build tags? Then the (user) error would be at least not silent.</pre>

**Comment by seankhliao** [comment]
godoc is deprecated #49212
