### ISSUE TITLE
net/http: Request.Body locking should be interruptable on Close

### ISSUE THREAD

**Issue by bradfitz** [golang/go#7121]
<pre>The fix to <a href="https://golang.org/issue/6995">issue #6995</a> made me realize that the new locking introduced in revision
00cce3a34d7eSimilar is too coarse.

It's now possible for a goroutine outside of the main server handler goroutine to be
blocked in a Request.Body.Read (a transfer.go *body.Read) indefinitely, holding the
*body mutex.

That mutex then prevents the server code from closing that body when the handler
completes.

Similar to how an io.Pipe's PipeReader.Read will be interrupted when the pipe is closed,
I think the http server's Request.Body.Read needs to be interruptable.  Perhaps it
should just use io.Pipe somewhere.

Example test showing the problem:

// Test that a hanging Request.Body.Read from another goroutine can't
// cause the Handler goroutine's Request.Body.Close to block.
// See golang.org/issue/7121
func TestRequestBodyCloseDoesntBlock(t *testing.T) {
        if testing.Short() {
                t.Skip(&quot;skipping in -short mode&quot;)
        }
        defer afterTest(t)

        readErrCh := make(chan error, 1)
        errCh := make(chan error, 2)

        server := httptest.NewServer(HandlerFunc(func(rw ResponseWriter, req *Request) {
                go func(body io.Reader) {
            _, err := body.Read(make([]byte, 100))
                        readErrCh &lt;- err
            }(req.Body)
        time.Sleep(500 * time.Millisecond)
        }))
        defer server.Close()

    closeConn := make(chan bool)
        defer close(closeConn)
        go func() {
                conn, err := net.Dial(&quot;tcp&quot;, server.Listener.Addr().String())
                if err != nil {
            errCh &lt;- err
                        return
            }
                defer conn.Close()
        _, err = conn.Write([]byte(&quot;POST / HTTP/1.1\r\nConnection: close\r\nHost: foo\r\nContent-Length: 100000\r\n\r\n&quot;))
                if err != nil {
                        errCh &lt;- err
                        return
        }
                // And now just block, making the server block on our
                // 100000 bytes of body that will never arrive.
                &lt;-closeConn
        }()
        select {
    case err := &lt;-readErrCh:
                t.Logf(&quot;Read error = %v&quot;, err)
        case err := &lt;-errCh:
                t.Error(err)
    case &lt;-time.After(5 * time.Second):
                t.Error(&quot;timeout&quot;)
        }
}</pre>

**Comment by PSG-Luna** [comment]
Are there any plans to fix this ?

When streaming data from the client, this makes it impossible to stop the streaming from the server side.

**Comment by bradfitz** [comment]
I had forgotten about this. I put it on my list to investigate for Go 1.8.

**Comment by odeke-em** [comment]
@bradfitz seems like it passes now, unless am missing something. Running on tip
```shell
$ go version
go version devel +b53f0f8 Sat Feb 4 16:46:11 2017 +0000 darwin/amd64
```

with the code you provided in the bug report ie also at https://github.com/odeke-em/bugs/blob/master/golang/7121/issue_test.go with just ```defer afterTest``` commented
the test passes but prints out
```shell
$ go test -v
=== RUN   TestRequestBodyCloseDoesntBlock
--- PASS: TestRequestBodyCloseDoesntBlock (0.50s)
	issue_test.go:54: Read error = read tcp 127.0.0.1:60113->127.0.0.1:60114: i/o timeout
PASS
ok  	_/Users/emmanuelodeke/Desktop/openSrc/bugs/golang/7121	0.513s
```

**Comment by odeke-em** [comment]
I have traced back the fixer to be commit 736443c13a718f0a9c30327ebbf09f58ccbe6d49 or CL https://go-review.googlesource.com/c/31148/.

Am finna enable the previously skipped test with a CL in a few.

**Comment by odeke-em** [comment]
I have traced back the fixer to be commit faf882d1d427e8c8a9a1be00d8ddcab81d1e848e or CL https://go-review.googlesource.com/c/31173/.

Am finna enable the previously skipped test with a CL in a few.
