### ISSUE TITLE
net: reject Lookup("www.google.com..") on all systems

### ISSUE THREAD

**Issue by vdobler** [golang/go#7122]
<pre>On Linux domain look-up is too liberal and accepts domain
names with two trailing dots like &quot;www.google.com..&quot;.
Most probably this is an issue on the OS level as
gethostbyname(3) shows this behavior also.

Allowing two trailing dots instead of none or
one (for a FQDN) seems harmless but it messes with the
domain name canonicalization done in net/http/cookiejar
and the determination of the public suffix of a domain.

I'd like to argue that malformed domains should be
rejected on look-up on any OS; at least no request
should be made to such malformed domain names.

This issue is not present on Windows and OSX.
Domains with three trailing dots are properly rejected
on Linux, Windows and OSX.
Other OS are untested.

The following program demonstrates the issue:
On Linux neither net.LookupHost nor http.Get fail.

--------------
package main

import (
    &quot;io&quot;
    &quot;log&quot;
    &quot;net&quot;
    &quot;net/http&quot;
    &quot;os&quot;
)

func main() {
    addrs, err := net.LookupHost(&quot;www.google.com..&quot;)
    if err != nil {
        log.Fatal(err)
    }
    for _, a := range addrs {
        log.Println(a)
    }
    res, err := http.Get(&quot;<a href="http://www.google.com">http://www.google.com</a>../foo&quot;)
    if err != nil {
        log.Fatal(err)
    }
    defer res.Body.Close()
    io.Copy(os.Stdout, res.Body)
}</pre>

**Comment by odeke-em** [comment]
Thank you for filing this bug @vdobler! This issue seems to have been filed when we were on code.google.com so I shall raise some attention to it. Kindly paging @iangudger, you might be interested in this bug, if you are free and bored.

**Comment by r5d** [comment]
@odeke-em, `net.LookupHost("www.google.com..")` is currently failing on Linux:

```bash
$ uname -a
Linux cygnus 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux
$ go version
go version go1.17.1 linux/amd64
$ ./7122
2021/09/11 18:04:13 lookup www.google.com..: no such host
````

Perhaps, this can be closed now?

**Comment by ianlancetaylor** [comment]
Sounds like it.  Thanks.
