### ISSUE TITLE
misc/gdb: arrays are too large

### ISSUE THREAD

**Issue by dlsniper** [golang/go#7141]
<pre>What steps will reproduce the problem?
If possible, include a link to a program on play.golang.org.
1. <a href="http://play.golang.org/p/dGBT7xECRs">http://play.golang.org/p/dGBT7xECRs</a>
2. go build -gcflags &quot;-N -l&quot; -o demo demo.go
3. gdb demo
4. &gt; break demo.go:6
5. &gt; break demo.go:13
6. &gt; run

What is the expected output?
For &gt; info locals command on demo.go:13 breakpoint I see the &quot;d&quot; array to
be:
d = {0, 0, 0}

What do you see instead?
d = {0, 0, 0, 4316562, 16, 4816288, 0, 4461078, 4816288, 833492132160, 0, 100,
833492132160, 4409578, 4979216, 29, 140737353932416, 833492132160, 65, 4286192, 4198466,
4272079, 5651336, 0, 0, 4271792, 4294967296, -1, 0, 5651296, 0, 0, 4281584, 0
&lt;repeats 96 times&gt;}

Which compiler are you using (5g, 6g, 8g, gccgo)?
6g

Which operating system are you using?
Ubuntu 13.10 with kernel 3.12.7, GNU gdb (GDB) 7.6.1-ubuntu.
Since I'm running on this version of OS I've had to run 2to3 to convert the
runtime-gdb.py script to python3.

Which version are you using?  (run 'go version')
go version go1.2 linux/amd64

Please provide any additional information below.
I would expect that the array size is the one that I've specified but I have no idea on
how to better check it. It also seems strange that the size is the same on the first
breakpoint (demo.go:6) and the second one (demo.go:13).

I've did a couple of tests on this one, it seems that as long as the value is smaller
than 129 the length of that array will be variable, depending on the number, so far I've
got 97 and another value plus 129 (which seems to be more frequent as long as the size
is above 10).

It also seems that if I change the type of the elements from int to string the cap is
65, float32 the cap is 65, float64 cap is 225, a struct with one public int field and
one public string field 65 and so on.

In all of the above cases, the size of the array returned by GDB is constant across
reruns.

Go is installed from the download distribution from golang.org.

go env output:
GOARCH=&quot;amd64&quot;
GOBIN=&quot;&quot;
GOCHAR=&quot;6&quot;
GOEXE=&quot;&quot;
GOHOSTARCH=&quot;amd64&quot;
GOHOSTOS=&quot;linux&quot;
GOOS=&quot;linux&quot;
GOPATH=&quot;/home/florin/golang:/var/www/personal/heimdall:/var/www/personal/untitled4:/var/www/personal/demo&quot;
GORACE=&quot;&quot;
GOROOT=&quot;/usr/lib/go&quot;
GOTOOLDIR=&quot;/usr/lib/go/pkg/tool/linux_amd64&quot;
TERM=&quot;dumb&quot;
CC=&quot;gcc&quot;
GOGCCFLAGS=&quot;-g -O2 -fPIC -m64 -pthread&quot;
CXX=&quot;g++&quot;
CGO_ENABLED=&quot;1&quot;

Let me know if you need additional details.

Thanks.</pre>

**Comment by ALTree** [comment]
This appears to be fixed in `go1.7` (with `gdb 7.11`):


```
$ go build -gcflags "-N -l" test.go
$ gdb ./test
GNU gdb (Debian 7.11.1-2) 7.11.1
(gdb) b test.go:13
Breakpoint 1 at 0x4010c0: file test.go, line 13.
(gdb) r
Thread 1 "test" hit Breakpoint 1, main.main () at test.go:13
13		if c {
(gdb) info locals
c = false
f = 3.3300000000000001
e = 2.21
b = 1.1200000000000001
d = {0, 0, 0}
a = "Hello world!"
```
n.b:
```
d = {0, 0, 0}
```

**Comment by bradfitz** [comment]
@ALTree, thanks. Closing.
