### ISSUE TITLE
log/syslog: flakey TestConcurrentReconnect test

### ISSUE THREAD

**Issue by mikioh** [golang/go#7146]
<pre>What steps will reproduce the problem?
1. go test -v -run=TestConcurrentReconnect -cpu=2,2,2,2
2.
3.

What is the expected output? What do you see instead?
PASS: TestConcurrentReconnect-2 (0.07 seconds)

Please use labels and text to provide additional information.
<a href="http://build.golang.org/log/d8b466031c5eabeaf15e7d63dca7554c99504920">http://build.golang.org/log/d8b466031c5eabeaf15e7d63dca7554c99504920</a>
<a href="http://build.golang.org/log/016f140e757cfe8cf2516d74cb898351fec8df24">http://build.golang.org/log/016f140e757cfe8cf2516d74cb898351fec8df24</a>
<a href="http://build.golang.org/log/abd6c0a78f68780e03f55c656bd291aa22891661">http://build.golang.org/log/abd6c0a78f68780e03f55c656bd291aa22891661</a></pre>

**Comment by ysmolsky** [comment]
This seems to be working as intended: https://build.golang.org/log/9df324d9c92c9545c7a82c4838c2405505711aa0

Also on my machine (macos):
```
..src/log/syslog (master $%=) % go test -v -run=TestConcurrentReconnect -cpu=2,2,2,2
=== RUN   TestConcurrentReconnect
--- PASS: TestConcurrentReconnect (0.01s)
=== RUN   TestConcurrentReconnect
--- PASS: TestConcurrentReconnect (0.00s)
=== RUN   TestConcurrentReconnect
--- PASS: TestConcurrentReconnect (0.00s)
=== RUN   TestConcurrentReconnect
--- PASS: TestConcurrentReconnect (0.00s)
PASS
ok  	log/syslog	0.025s
```
