### ISSUE TITLE
go.tools/go/types:  types.Eval should also return Object

### ISSUE THREAD

**Issue by gordonklaus** [golang/go#7151]
<pre>If the expression passed to Eval identifies an Object, it should be returned in addition
to the Type.

A glance at the code indicates that this will require adding a new field to operand.</pre>

**Comment by griesemer** [comment]
I'm going to close this one for now. In the meantime, types.Eval returns more than just the type.

CheckExpr might still be useful perhaps, but it's not clear it should be part of go/types.

If you feel strongly about this, you can move https://golang.org/cl/60110044 over to gerrit and send a review request.
