### ISSUE TITLE
cmd/go: introduce build tags for different GOARM settings?

### ISSUE THREAD

**Issue by minux** [golang/go#7211]
<pre>now that the GOARM setting affects the code generated by the compiler,
which means we will need to have separate set of *.a files for each GOARM
anyway, why not introducing armv5, armv6 and armv7 build tags so that
we can statically select the best code based on target platform?

we probably should embed GOARM into cmd/go also, but that is also not
a problem, a lot of settings are embedded in cmd/go nowadays.</pre>

**Comment by maruel** [comment]
I found a use case for adding build tag based on the specific ARM targeted version which helps answering the "why":

In the case of linking with a static library, I'd like to be able to select the optimal version of the static library, which is available in versions ARMv5 soft float, ARMv6 hard float, ARMv7 hf and ARMv8 hf.

I would use conditional compilation based on build tags to select the most optimal version. To be able to do that, I need a build tag for the ARM subarch.

For now I'll settle with ARMv6 hf which is the baseline I'm targeting for, but that's not optimal.

**Comment by clausecker** [comment]
In writing some assembly-optimised libraries for Go, I found this issue.  It would be really great to have a way to conditionally compile code based on `GOARM` and the upcoming `GOAMD64` so I don't have to do a dynamic dispatch at runtime.

**Comment by tv42** [comment]
Related: https://github.com/golang/go/issues/22106

**Comment by seankhliao** [comment]
I believe this was implemented in #45454
