### ISSUE TITLE
net/http: failing tests on Plan 9

### ISSUE THREAD

**Issue by 0intro** [golang/go#7237]
<pre>What steps will reproduce the problem?

cd pkg/net/http; go test -short

What is the expected output? What do you see instead?

The following tests are failing:

serve_test.go

    TestServerTimeouts
    TestOnlyWriteTimeout
    TestTLSHandshakeTimeout
    TestClientWriteShutdown

transport_test.go

    TestTransportPersistConnLeak
    TestTransportPersistConnLeakShortBody
    TestIssue4191_InfiniteGetTimeout
    TestIssue4191_InfiniteGetToPutTimeout

The timeout tests are failing because of the lack of deadline support. The other issues
are:

--- FAIL: TestClientWriteShutdown (0.01 seconds)
        serve_test.go:1430: Dial: not supported by plan 9

--- FAIL: TestTransportPersistConnLeak (0.82 seconds)
        transport_test.go:803: goroutine growth: 93 -&gt; 193 -&gt; 99 (delta: 6)
        transport_test.go:804: too many new goroutines

--- FAIL: TestTransportPersistConnLeakShortBody (1.10 seconds)
        transport_test.go:843: goroutine growth: 93 -&gt; 153 -&gt; 153 (delta: 60)
        transport_test.go:845: too many new goroutines</pre>

**Comment by bradfitz** [comment]
I think this is basically done. I'll create a new bug for the one test I still see mentioning plan9.

**Comment by bradfitz** [comment]
Actually, #17906 is already open. We can close this bug.
