### ISSUE TITLE
io: Add MultiReadSeeker 

### ISSUE THREAD

**Issue by techee** [golang/go#7263]
<pre>The io package provides MultiReader which is useful e.g. when static file size is
limited like on AppEngine but there's no ReadSeeker equivalent when random access is
needed.

I have created this simple implementation:

<a href="http://play.golang.org/p/BNL9QCnUHB">http://play.golang.org/p/BNL9QCnUHB</a>

which I use for MaxMind binary database (which is bigger than 32MB and whose reading
requires random access) on the AppEngine. Before proceeding further, my question is - is
there an interest for having something like this in go standard library? If so, I can
modify the code as a patch against go and add some unit tests.

About the implementation: the core of it is a doubleReadSeeker which is ReadSeeker
composed of two ReadSeekers and based on the offset reads from the first or the second
file. For MultiReadSeeker a tree is made out of these doubleReadSeekers which allows
arbitrary number of ReadSeekers (which are the leaves of the tree). This means log(N)
(where N is the number of ReadSeekers in MultiReadSeeker) steps are needed to access the
ReadSeeker at the bottom of the tree

I've tried to make the implementation as efficient as possible and avoid any extra Reads
or Seeks of the &quot;real&quot; ReadSeekers which may require IO operations and can be
slow:

MultiReadSeeker performs N+1 &quot;real&quot; Seek operations

Read performs 1 &quot;real&quot; Read operation, unless it reads from the border of two
ReadSeekers in which case it's 2 Reads and 1 Seek (can be actually more if this happens
at multiple levels of the tree)

Seek performs 1 &quot;real&quot; Seek operation

What's your opinion on having something like this in go standard library?</pre>

**Comment by rsc** [comment]
I'm not sure I've read this issue before. MultiReadSeeker seems too specialized. In any event, punting to Go 1.11 but maybe we should just close it.

**Comment by brenol** [comment]
@rsc I believe it would be useful in the cases that you need to read from the same underlying Readers in the MultiReader. Right know you need to work with each *os.File (if thats your Seeker) individually.

I see some implementations in the wild: https://github.com/search?q=MultiReadSeeker&type=Code&utf8=%E2%9C%93 (or rather: a lot of copy-paste implementations of MultiReadSeeker)

Not sure if it warrants a implementation in stdlib though.

**Comment by bradfitz** [comment]
I think it's better to have a way to logically concatenate ReaderAt values (using e.g. my https://godoc.org/go4.org/readerutil#NewMultiReaderAt) and then if you want Seek and Read, you wrap it in an SectionReader (https://golang.org/pkg/io/#NewSectionReader).

I'm going to close this for now. All these interfaces deserve some thought for Go 2, so I'll flag this issue as Go 2 to make sure it's even easier to find back.
