### ISSUE TITLE
x/tools/go/gcimporter: RFE: record file/offset/line/col info for all objects in export data format

### ISSUE THREAD

**Issue by adonovan** [golang/go#7311]
<pre>Since we're redesigning export data formats, can we record file/offset/line/col info for
all objects?  Using the interning mechanism it should be fairly cheap and allows us to
improve the user interface of tools that use object code.

For example:

% cat a.go
package main
import . &quot;fmt&quot;
var Println int

% ./ssadump -build=PG a.go
a.go:3:5: Println already declared in this file through import of package fmt
a.go:2:8: &quot;fmt&quot; imported but not used

This error message could additionally say:
src/pkg/fmt/print.go:263:   (previously defined here)</pre>

**Comment by griesemer** [comment]
We're doing this now. Verify current status and close if this is done.

**Comment by griesemer** [comment]
The exporter already writes all the position information. A pending CL ( https://go-review.googlesource.com/#/c/37239 ) contains much of the code needed for this to complete.

**Comment by griesemer** [comment]
The new src importer already will produce packages with precise position information.

**Comment by griesemer** [comment]
The single-biggest issue here (besides verifying that the recorded position information is correct) is that we cannot get the information out unless we have access to the respective token.FileSet (which currently is created inaccessibly in the importers).

I see two possible ways forward:
1) We define (yet another API) for go/importer that's more configurable.
2) We get the file set out of the types.Package object.

We may have to do 1) sooner or later, so perhaps that's the right path. On the other hand, it could make sense to store the file set with a types.Package object as the package scope's objects positions only make sense with the matching file set. We cannot change the NewPackage factory method, but we could add another one that takes a file set; or we could just provide two new accessors `FileSet() *token.FileSet` and `SetFileSet(fset *token.FileSet)`.

@adonovan Thoughts?

**Comment by alandonovan** [comment]
> we cannot get the information out unless we have access to the respective token.FileSet (which currently is created inaccessibly in the importers).

If you load export data using the API in golang.org/x/tools/go/gcexportdata, position information is available.  (It's been working nicely for the Google-internal version of guru for some months.)

> 1. We define (yet another API) for go/importer that's more configurable.
> 2. We get the file set out of the types.Package object.

I don't see any need to store a FileSet in the types.Package.  I agree the API of go/importer is too narrow (it's basically impossible to correctly use the gccgo importer through it, for example) but the API of the new srcimporter package seems fine to me, even though it's currently marked internal.  A visible copy of it in golang.org/x/tools might make sense, alongside the other importers.
