### ISSUE TITLE
syscall: unnamed unix sockets on Linux report Name "@" in their address

### ISSUE THREAD

**Issue by remyoudompheng** [golang/go#7354]
<pre>What steps will reproduce the problem?
1. Run the code 
<a href="http://play.golang.org/p/GSJZRDJWpS">http://play.golang.org/p/GSJZRDJWpS</a>

What is the expected output? What do you see instead?

The UnixAddr is &quot;@&quot; but one would expect an empty string.

Expected:
&amp;net.UnixAddr{Name:&quot;&quot;, Net:&quot;unix&quot;}

Got:
&amp;net.UnixAddr{Name:&quot;@&quot;, Net:&quot;unix&quot;}

Please use labels and text to provide additional information.</pre>

**Comment by ysmolsky** [comment]
According to the last comment from @rsc here https://codereview.appspot.com/69910043 and lack of attention I'm closing this bug.
