### ISSUE TITLE
reflect: CanSet returns true for unexported embedded struct fields.

### ISSUE THREAD

**Issue by paranoiacblack** [golang/go#7363]
<pre>What steps will reproduce the problem?
1. <a href="http://play.golang.org/p/P5IJiLANVg">http://play.golang.org/p/P5IJiLANVg</a>

What is the expected output?
No output.

What do you see instead?
panic: B.a is an unexported embedded struct field

Which compiler are you using (5g, 6g, 8g, gccgo)?
6g

Which operating system are you using?
Ubuntu 12.04 LTS

Which version are you using?  (run 'go version')
go version go1.2 linux/amd64

Please provide any additional information below.
According to <a href="http://golang.org/pkg/reflect/#Value.CanSet">http://golang.org/pkg/reflect/#Value.CanSet</a>, &quot;A Value can be changed
only if it is addressable and was not obtained by the use of unexported struct
fields.&quot; The first clause holds in the example, but the current behavior violates
the second clause.</pre>

**Comment by rsc** [comment]
@mpvl has a plan!
