### ISSUE TITLE
flag: include source of original definition in redefinition error

### ISSUE THREAD

**Issue by robpike** [golang/go#7368]
<pre>If a flag is redefined, it may be due to a transitively imported package you're not
aware of holding the original definition. To help diagnose this, it might be worth
remembering where a flag was defined, although doing so will  require the flag package
to import runtime and other such complexities. I'm not sure it's worthwhile, but I
wanted to record the idea here.</pre>

**Comment by robpike** [comment]
Decided not to do this. A corner case not worth the added complexity and dependencies.

**Comment by WIZARD-CXY** [comment]
Just met this problem in my own project. A glog `log_dir` flag is redefined.....
