### ISSUE TITLE
net: test fails when there's no network

### ISSUE THREAD

**Issue by randall77** [golang/go#7431]
<pre>Turn off your network (ifconfig eth0 down, whatever else makes sense).

Run all.bash.

--- FAIL: TestIPv4MulticastListener (0.01 seconds)
	multicast_test.go:55: First ListenMulticastUDP on &lt;nil&gt; failed: listen udp 224.0.0.254: setsockopt: no such device
FAIL
FAIL	net	2.376s

TestIPv6 also fails.

all.bash should work even without the presence of the network, even if it just skips
these tests.</pre>

**Comment by mikioh** [comment]
I think go1.6 and above can handle this case. Closing.
