### ISSUE TITLE
net: TestIPv6LinkLocalUnicastUDP fails under DragonFly BSD

### ISSUE THREAD

**Issue by 4a6f656c** [golang/go#7473]
<pre>The &quot;udp&quot; to IPv6 unicast address on the loopback interface test currently
fails under DragonFly BSD, since it returns a local address of 0.0.0.1, rather than an
IPv6 address with zone identifier:

--- FAIL: TestIPv6LinkLocalUnicastUDP (0.00 seconds)
udp_test.go:235: got 0.0.0.1:1221; expected a proper address with
        zone identifier

This requires further investigation, however is likely a DragonFly bug/behaviour.</pre>

**Comment by mikioh** [comment]
Merged into #10764.
