### ISSUE TITLE
proposal: spec: disallow unused assignment to return variable

### ISSUE THREAD

**Issue by robpike** [golang/go#7485]
<pre>From @taradinoc on twitter: 

// <a href="http://play.golang.org/p/TsxFgLP1l2">http://play.golang.org/p/TsxFgLP1l2</a>

package main

import &quot;fmt&quot;

func main() {
    i := foo()
    fmt.Printf(&quot;Hello, %d\n&quot;, i)
}

func foo() (x int) {
    x = 7
    return 5
}

This compiles and runs fine, but if x were a local instead of a return variable, gc
would complain that it was unused. is this an inconsistency that should be fixed?</pre>

**Comment by ianlancetaylor** [comment]
Implementing this in the language could be done, but we would have to pay attention to any use of a `return` with no values.  This would make the language rules more complicated for a very minor gain.  Therefore, this is a **likely decline**.  Leaving open for four weeks for final comments.

**Comment by ianlancetaylor** [comment]
No further comments.
