### ISSUE TITLE
cmd/compile: method definitions based on later-defined methods don't compile (pathological)

### ISSUE THREAD

**Issue by griesemer** [golang/go#7495]
<pre><a href="http://play.golang.org/p/WMpE0q2wK8">http://play.golang.org/p/WMpE0q2wK8</a>

produces:

prog.go:7: T.m2 undefined (type T has no method m2)
prog.go:7: invalid expression unsafe.Sizeof(T.m2)
 [process exited with non-zero status]

But switching m1 and m2 works:

<a href="http://play.golang.org/p/uR3wFJcAHq">http://play.golang.org/p/uR3wFJcAHq</a>

In general, ordering declarations differently won't work:

<a href="http://play.golang.org/p/iAV8x86giC">http://play.golang.org/p/iAV8x86giC</a>

These are clearly pathological cases but point out some limitations of gc's type checker.

gccgo handles these cases w/o problem.
go/types has the same problem.</pre>

**Comment by ericlagergren** [comment]
As of Go 1.21, the first example currently compiles. The third exits with 

```
./prog.go:8:28: illegal cycle in method declaration
```

**Comment by griesemer** [comment]
Thanks for reviving this.

The 3rd example is expected to fail as the type checker is (currently) not intended to work with cycles where partial information (such as function size independent of the actual function signature).

So this is not all working as intended.
Closing.
