### ISSUE TITLE
test: make it easy to test machine code generation

### ISSUE THREAD

**Issue by josharian** [golang/go#7515]
<pre>Make it easy to write a test for machine code generation.

One way this might work: Write a test containing an assembly language function and the
desired compiled code (per compiler+arch+goarm?). The run.go test hook compiles,
extracts the relevant symbol, disassembles with objdump, and compares to the desired
output.

Use fixedbugs/issue7044.go as a motivating use case (and replace it with a new and
improved version).

See <a href="https://golang.org/cl/73730043/">https://golang.org/cl/73730043/</a> for the original discussion.</pre>

**Comment by rsc** [comment]
Too late for Go 1.5.

**Comment by ALTree** [comment]
This was implemented last year by the new codegen test harness. Closing.
