### ISSUE TITLE
runtime: TestFinalizerX fails on *bsd/amd64

### ISSUE THREAD

**Issue by mikioh** [golang/go#7529]
<pre>Not sure this is a freebsd-specific issue. We see this rarely on the buildbots, fwiw
I've never seen this on my virtual machines.

Revision: 17d15bc23bce, Mar 12, 2014:
<a href="http://build.golang.org/log/92a502eabafeaaf3d8b3368137eb6a5c6a51ca3c">http://build.golang.org/log/92a502eabafeaaf3d8b3368137eb6a5c6a51ca3c</a>

Revision: 3d37606fb793,     Feb 28, 2014:
<a href="http://build.golang.org/log/49be94df0755ea128d580cc07ac8fea6f3975625">http://build.golang.org/log/49be94df0755ea128d580cc07ac8fea6f3975625</a></pre>

**Comment by tklauser** [comment]
This no longer seems to be failing according to the build status on https://build.golang.org for *bsd/amd64, closing.

Feel free to reopen if you disagree.
