### ISSUE TITLE
cmd/cgo: duplicate symbol "stat"

### ISSUE THREAD

**Issue by mitchellh** [golang/go#7542]
<pre>With a minimal project, I get this cgo error on Windows with msys:

main.go:

    package main

    import &quot;C&quot;

test.c:

    #include &lt;sys/stat.h&gt;

    void check() {
      struct stat st;
      stat(&quot;/tmp/foo&quot;, &amp;st);
    }

Runing &quot;go build&quot;:

C:\Users\Mitchell\AppData\Local\Temp\go-build746675543\_\C_\Users\Mitchell\AppData\Local\Temp\gotest.a(_all.o):
duplicate symbol reference: stat in both main(.text) and main(.data)

Go version: 

go version devel +4df290191840 Wed Jan 15 09:50:55 2014 -0800 windows/amd64</pre>

**Comment by alexbrainman** [comment]
I believe this is fixed now by latest @minux cmd/ld pe changes.

**Comment by mattn** [comment]
i just made sure the code above is compilable in tip.

**Comment by minux** [comment]
Yes, it is fixed by #4069 fix.
(Please reference issue 4069 when closing issues fixed by external linking.)
