### ISSUE TITLE
gccgo: initialization loops are not described

### ISSUE THREAD

**Issue by dsymonds** [golang/go#7558]
<pre>Take a program with an import loop such as <a href="http://play.golang.org/p/29okKQEmlZ">http://play.golang.org/p/29okKQEmlZ</a>.

gc reports the cycle itself. gccgo merely reports that there is a cycle. That makes it a
lot harder to diagnose.

In particular, I found a situation in some code where gc happily compiles it but gccgo
claims &quot;error: variable initializer refers to itself&quot;. I can't find the
initialization loop, but I'm not sure whether gc, gccgo or the program is at fault. In
particular, one of the two compilers must be at fault.</pre>

**Comment by paranoiacblack** [comment]
Initialization loops are better described in gccgo currently; the example now claims "error: initialization expressions for ‘someMap’ and ‘someVal’ depend upon each other" which is surely better but does not spell out the initialization loop as well as cmd/gc.

Also, this example currently causes an infinite loop of describing the initialization loop, so I'll close this after I fix that.

**Comment by paranoiacblack** [comment]
Sorry, missed some error output, let me just post the exact message

    initloop.go:9:5: error: initialization expressions for ‘someMap’ and ‘someVal’ depend upon each other
     var someMap = map[string]func() int{
         ^
    initloop.go:13:5: note: ‘someVal’ defined here
     var someVal = someMap["web"]()
         ^
    initloop.go:13:5: error: initialization expressions for ‘someVal’ and ‘someMap’ depend upon each other
    initloop.go:9:5: note: ‘someMap’ defined here
     var someMap = map[string]func() int{
         ^
    initloop.go:9:5: error: initialization expression for ‘someMap’ depends upon itself
    initloop.go:13:5: error: initialization expression for ‘someVal’ depends upon itself
     var someVal = someMap["web"]()
         ^

**Comment by paranoiacblack** [comment]
Fixed in gcc.gnu.org/r220009.

**Comment by prdoyle** [comment]
The error message for these type inference cycles don't mention that they are looking at types:

   initialization expression for 'x' depends upon itself

Could this add the word "type", as in "initialization expression type for 'state' depends upon itself"?  The error here, really, is that the expression's type depends on itself.
