### ISSUE TITLE
sync: document RWMutex.RLock shouldn't be used recursively

### ISSUE THREAD

**Issue by dvyukov** [golang/go#7576]
<pre>Detected by experimental deadlock detector in cl/77450043.

==================
WARNING: DEADLOCK
Goroutine 999 lock mutex 35 while holding mutex 35:
  sync.(*RWMutex).RLock()
      src/pkg/sync/rwmutex.go:42 +0xa2
  sync.(*rlocker).Lock()
      src/pkg/sync/rwmutex.go:133 +0x34
  sync_test.func·027()
      src/pkg/sync/rwmutex_test.go:132 +0xb6

Mutex 35 was previously locked here:
  sync.(*RWMutex).RLock()
      src/pkg/sync/rwmutex.go:42 +0xa2
  sync.(*rlocker).Lock()
      src/pkg/sync/rwmutex.go:133 +0x34
  sync_test.func·027()
      src/pkg/sync/rwmutex_test.go:133 +0xda
==================

==================
WARNING: DEADLOCK
Goroutine 999 lock mutex 16 while holding mutex 16:
  sync.(*RWMutex).RLock()
      src/pkg/sync/rwmutex.go:42 +0xa2
  sync_test.func·028()
      src/pkg/sync/rwmutex_test.go:166 +0x88
  testing.func·002()
      src/pkg/testing/benchmark.go:416 +0x17d

Mutex 16 was previously locked here:
  sync.(*RWMutex).RLock()
      src/pkg/sync/rwmutex.go:42 +0xa2
  sync_test.func·028()
      src/pkg/sync/rwmutex_test.go:167 +0x96
  testing.func·002()
      src/pkg/testing/benchmark.go:416 +0x17d
==================

Tests lock RWMutex recursively. RWMutex is not recursive.</pre>

**Comment by bradfitz** [comment]
@dvyukov, should we repurpose this into a bug to clarify some documentation on https://golang.org/pkg/sync/#RWMutex.RLock to say that it must not be used recursively by the same caller?

**Comment by dvyukov** [comment]
The documentation already says this:

```
If a goroutine holds a RWMutex for reading, it must not expect this or any other goroutine to be able to also take the read lock until the first read lock is released. In particular, this prohibits recursive read locking. This is to ensure that the lock eventually becomes available; a blocked Lock call excludes new readers from acquiring the lock.
```
