### ISSUE TITLE
x/playground: add vet

### ISSUE THREAD

**Issue by josharian** [golang/go#7597]
<pre>On potential pain of button overload, it might be useful to add a Vet button to the
playground. It would run go vet over the program and display the output. This would
increase vet visibility and help make self-service debugging easier. (E.g. It would have
helped with <a href="https://groups.google.com/forum/m/#">https://groups.google.com/forum/m/#</a>!topic/golang-nuts/IneZcyGGJYM )</pre>

**Comment by josharian** [comment]
The front-end work I did for this (now perhaps a bit dated) can be found at https://codereview.appspot.com/103750044/ and https://codereview.appspot.com/104770043/. The hard part--splitting vet into a package and a command--is still outstanding.

**Comment by adg** [comment]
Now that the new sandbox server is running on a VM, we can think about just
calling the vet command directly.

**Comment by dericofilho** [comment]
Running playground on a sandbox makes easier to execute `cmd/vet` on a piece of code. 

These two CLs addresses this issue, by updating both sandbox, playground frontend application and a static file shared with godoc. 

Currently, it is implemented following this way:
1 - Added one entry point (`/vet`) to sandbox, which calls `cmd/vet` and parses the result as if it were a compilation process.
2 - Updated `playground.js`, so it calls `/vet` at backend. 
3 - Updated Dockerfile with `go get` to install `cmd/vet`

I considered the alternative of overloading `/compile` endpoint with a parameter, thus switching back and forth between compilation and vetting. The reason I did not do it was that it seemed a cleaner design to keep separated different resources with different goals. 

Of course, I am ready to change the implementation after debate. 

Anyway, I should like to open as soon as possible another CL updating docs to mention the existence of a proxy at `golang.org/compile` - so other contributos do not get lost on why query-string calls are made where the sandbox expects for JSON.

https://go-review.googlesource.com/#/c/11632/
https://go-review.googlesource.com/#/c/11633/

**Comment by dericofilho** [comment]
@adg ping

**Comment by dericofilho** [comment]
@josharian ping.

**Comment by adg** [comment]
Sorry, I'm busy preparing for GopherCon. I will review this after next week.

**Comment by dericofilho** [comment]
@adg Sorry to bother you, could you please take a look at these CLs? 

https://golang.org/cl/11633
https://golang.org/cl/11632

**Comment by adg** [comment]
After Go 1.5 is out, yes.

**Comment by ysmolsky** [comment]
I am working on it. Please give me early feedback if you have it.

![screen shot 2018-03-14 at 11 21 42](https://user-images.githubusercontent.com/140245/37393524-feb73cc8-2779-11e8-9bf1-ed1a0e8c1de0.png)

![screen shot 2018-03-14 at 11 23 54](https://user-images.githubusercontent.com/140245/37393621-393d70f6-277a-11e8-9e60-307637e477a0.png)

/CC @andybons @bradfitz

**Comment by andybons** [comment]
UI lgtm!

**Comment by ysmolsky** [comment]
Reviewers are welcome here: https://golang.org/cl/100776
