### ISSUE TITLE
x/tools/dashboard: add axes on performance graphs

### ISSUE THREAD

**Issue by dvyukov** [golang/go#7688]
<pre>---------- Forwarded message ----------
From: Rob 'Commander' Pike

One feature request that would help significantly: please put (even very simple) axes on
the graphs.  If I look at a chart like this:

<a href="http://goperfd.appspot.com/perfgraph?builder=linux-amd64&amp">http://goperfd.appspot.com/perfgraph?builder=linux-amd64&amp</a>;benchmark=json&amp;procs=1&amp;metric=time&amp;startcommit=2256&amp;commitnum=200&amp;zoomout=Zoom+out

it's unclear what is going on.  I can hover over kinks in the line but it would help a
lot to have even, say, the minimum and maximum values on the x and y axes labeled, in
this case the relative percentage change (what do the horizontal lines mean?) and
something like the date or CL# or rev# for the first and last changes on the x axis.

Russ also suggests looking at how the graphs at go/gousage work to see if we can make
that nice navigation UI work, but that is a bigger job.

For now, I'd be happy just to have the three corners (UL, LL, LR) labeled.

Thanks.

-rob</pre>

**Comment by ALTree** [comment]
The old dashboard has been dismissed years ago so we can close this.
