### ISSUE TITLE
proposal: runtime: remove SetFinalizer

### ISSUE THREAD

**Issue by dvyukov** [golang/go#7697]
<pre>Consider removing SetFinalizer in Go2.

Here is the discussion on golang-dev:
<a href="https://groups.google.com/forum/#">https://groups.google.com/forum/#</a>!topic/golang-dev/DMiUkpS1uyQ</pre>

**Comment by ianlancetaylor** [comment]
At the bottom of the cited e-mail thread, @dvyukov withdrew this proposal (https://groups.google.com/d/msg/golang-dev/DMiUkpS1uyQ/bRl5TsMTo6AJ).  Closing.
