### ISSUE TITLE
cmd/gc: pessimistic escape analysis

### ISSUE THREAD

**Issue by dvyukov** [golang/go#7710]
<pre>go version devel +2e0890c1d9d6 Fri Apr 04 08:15:27 2014 -0700 linux/amd64

Build the following program with:
$ go tool 6g -m /tmp/escape.go

package main
import &quot;fmt&quot;
type T struct {
	x int
}
func noescape(p **T) {
	t := *p
	fmt.Println(t)
}
func main() {
	t := &amp;T{42}
	noescape(&amp;t)
}

<a href="http://play.golang.org/p/-6e2VTI_nU">http://play.golang.org/p/-6e2VTI_nU</a>

/tmp/escape.go:9: leaking param: p
/tmp/escape.go:11: noescape ... argument does not escape
/tmp/escape.go:15: moved to heap: t
/tmp/escape.go:16: &amp;t escapes to heap
/tmp/escape.go:15: &amp;T literal escapes to heap

Param p is not leaking here.</pre>

**Comment by dr2chase** [comment]
I think this is closed by recent improvements to escape analysis, commit 7fbb1b36c37ac49db78042adc7533fb4ab83a4bc
The code for netpoll is now escape/leak-free:
```
runtime/netpoll_kqueue.go:101: inlining call to guintptr.ptr
runtime/netpoll_kqueue.go:53: can inline netpollclose
runtime/netpoll_kqueue.go:16: kevent ch does not escape
runtime/netpoll_kqueue.go:16: kevent ev does not escape
runtime/netpoll_kqueue.go:16: kevent ts does not escape
runtime/netpoll_kqueue.go:72: netpoll &ts does not escape
runtime/netpoll_kqueue.go:76: netpoll &events[0] does not escape
runtime/netpoll_kqueue.go:86: netpoll &events[i] does not escape
runtime/netpoll_kqueue.go:95: netpoll &gp does not escape
runtime/netpoll_kqueue.go:33: netpollopen pd does not escape
runtime/netpoll_kqueue.go:38: netpollopen &ev[0].ident does not escape
runtime/netpoll_kqueue.go:46: netpollopen &ev[0] does not escape
runtime/netpoll_kqueue.go:59: netpollarm pd does not escape
```

and the little test case:

```
package main
import "fmt"
type T struct {
    x int
}
func noescape(p **T) {
    t := *p
    fmt.Println(t)
}
func main() {
    t := &T{42}
    noescape(&t)
}
```
produces
```
drchase$ go tool 6g -m esc_dv.go
esc_dv.go:8: t escapes to heap
esc_dv.go:6: leaking param content: p
esc_dv.go:8: noescape ... argument does not escape
esc_dv.go:11: &T literal escapes to heap
esc_dv.go:12: main &t does not escape
```
