### ISSUE TITLE
cmd/gc: loss of precision in very low constant bits?

### ISSUE THREAD

**Issue by rsc** [golang/go#7740]
<pre>I expect this program to print the precision of the internal multiprecision floats used
for storing floating-point constants in the compiler. cmd/gc uses an Mpint with 16
29-bit values, which should be 463 bits plus a sign bit. The program prints 434 on the
playground, which is 15*29-1, not 16*29-1. 

It is possible that my logic here is wrong and that the program does not in fact compute
the precision of the internal floating point representation used for constants. However,
being off by 29 in a compiler with 29-bit mp limbs cannot be a coincidence.

I wonder if the final word in the compiler representation is being maintained or used
incorrectly. It wouldn't be the first time.

package main

import (
	&quot;fmt&quot;
	&quot;math&quot;
)

const ulp = (1.0+(2.0/3.0)) - (5.0/3.0)

func main() {
	fmt.Println(math.Log(1/math.Abs(ulp))/math.Log(2))
}

<a href="http://play.golang.org/p/_3XxPwYeVx">http://play.golang.org/p/_3XxPwYeVx</a></pre>

**Comment by griesemer** [comment]
Running this code after

https://golang.org/cl/7912/

produces 463.00000000000006; that is 463 as one would expect.

**Comment by josharian** [comment]
Using `const ulp = (1. + (2. / 3.)) - (.5 / .3)` also generates 463, but `const ulp = (1. + (.2 / .3)) - (5. / 3.)` generates positive infinity. I don't know whether it is a problem that they should diverge so radically.

**Comment by josharian** [comment]
Never mind. That was a stupid comment. Retracted. :)
