### ISSUE TITLE
cmd/compile: crash due to running out of memory (likely)

### ISSUE THREAD

**Issue by griesemer** [golang/go#7755]
<pre>Test case: <a href="http://play.golang.org/p/xoT0jSBOci">http://play.golang.org/p/xoT0jSBOci</a>

Perhaps it's possible to give a nicer error message on the command line:

$ go tool 6g overflow.go 
overflow.go:35: internal compiler error: fault

(The out of memory message in the playground is presumably from the underlying app
engine implementation).

(see also <a href="https://golang.org/issue/7754">issue #7754</a>).</pre>

**Comment by mdempsky** [comment]
Same as #4415: should be fixed now that the Go compiler is written in Go rather than C.
