### ISSUE TITLE
runtime: use SYSCALL on FreeBSD

### ISSUE THREAD

**Issue by bradfitz** [golang/go#7813]
<pre>Go 1.2 and Go 1.3 require FreeBSD kernels be built with COMPAT_FREEBSD32 due to a
FreeBSD kernel bug with SYSCALL.  Go is currently using INT $0x80 as a workaround.

This bug is about switching back to SYSCALL, once modern FreeBSD kernels with the fix
are prevalent.

See <a href="https://golang.org/issue/7056">issue #7056</a> for background.</pre>

**Comment by sean-** [comment]
Is this a bug with the entire branch or is this specific to a particular release?

**Comment by minux** [comment]
This is fixed. See #9627.
