### ISSUE TITLE
runtime: use user-mode scheduling on Windows

### ISSUE THREAD

**Issue by dvyukov** [golang/go#7876]
<pre>Runtime could benefit from OS support for user-mode scheduling.
Namely, UMS on windows:
<a href="http://msdn.microsoft.com/en-us/library/windows/desktop/dd627187(v=vs.85).aspx">http://msdn.microsoft.com/en-us/library/windows/desktop/dd627187(v=vs.85).aspx</a>
and switchto domains on linux:
<a href="http://www.youtube.com/watch?v=KXuZi9aeGTw">http://www.youtube.com/watch?v=KXuZi9aeGTw</a>

This would allow to determine when a thread in syscall/cgocall actually block. Which
would allow to reduce non-blocking syscall/cgocall overhead by delaying most of the work
till the actual blocking; and to prevent CPU oversubscription by maintaing total of
GOMAXPROCS threads running both Go and C/syscall code.

The obvious downside is increased complexity and lots of OS-specific code.</pre>

**Comment by zx2c4** [comment]
I'm wondering if there's still interest in doing this, given the evolution of the runtime in the last 6 years. At cursory glance, it looks appealing.

**Comment by networkimprov** [comment]
cc @aclements @prattmic @alexbrainman @mattn

**Comment by ianlancetaylor** [comment]
According to https://github.com/golang/go/issues/8687#issuecomment-656259353 User Mode Scheduling is considered to be deprecated, and will not be supported on ARM platforms.

So I suspect we should just close this issue.

**Comment by qiulaidongfeng** [comment]
cc @golang/runtime 
windows 11 not support UMS , this issue should be close.

**Comment by prattmic** [comment]
Thanks. This is clearly documented are unsupported on https://learn.microsoft.com/en-us/windows/win32/procthread/user-mode-scheduling?redirectedfrom=MSDN.
