### ISSUE TITLE
x/playground/website: missing css style on playground errors

### ISSUE THREAD

**Issue by mjibson** [golang/go#7900]
<pre>A program with an error on the playground has its line number highlighted in red, but
only the background changes. The light gray text color remains, and the red error text
does not appear. This is due to CSS precedence rules. The attached patch shows the
intended red text.</pre>

Attachments:
1. <a href="https://storage.googleapis.com/go-attachment/7900/0/style.patch">style.patch</a> (241 bytes)

**Comment by ALTree** [comment]
@mjibson still interested in this? Want to send a gerrit patch? Otherwise I'd close the issue.

**Comment by mjibson** [comment]
Not enough to figure out how to send a gerrit patch.
