### ISSUE TITLE
cmd/compile: tune value of BITS

### ISSUE THREAD

**Issue by josharian** [golang/go#7908]
<pre>Large data structures (I'm looking at you, unicode tables) exceed the current register
optimizer's capacity, so some code gets left unoptimized. To see this, run 'go build -a
-gcflags=&quot;-w -w&quot; unicode'.

This is controlled by BITS in go.h. Looking just at binary size of hello world as a
proxy for optimization, I see:

BITS=5: 1834544
BITS=6: 1830448
BITS=8: 1830448
BITS=12: 1826352

The impact is small, and increasing BITS increases the memory usage and runtime of the
compiler. However, I was unable to detect that difference on my laptop. I've not tried
on (say) a Raspberry Pi.

Once the compiler is in Go, and we have good tools for measuring the impact on build
performance, let's tune BITS based on real world programs -- or perhaps better, have
BITS dynamically adjust as needed.</pre>

**Comment by josharian** [comment]
Once the compiler is in Go, we might want to use something like http://research.swtch.com/sparse for these data structures during registerization and liveness analysis.

**Comment by josharian** [comment]
Surprisingly, this also happens in the 90 line `Write` function in `encoding/binary`:

`encoding/binary/binary.go:335: internal compiler error: variable not optimized: @"".v·47`

**Comment by rsc** [comment]
Too late for Go 1.5.
