### ISSUE TITLE
cmd/gc, runtime: slow swapping of slice values

### ISSUE THREAD

**Issue by egonelbre** [golang/go#7927]
<pre>Idiomatic swapping  e[i], e[j] = e[j], e[i] in a slice of structs is slower than
swapping each field in the structs separately.

What does 'go version' print?
go version devel +c19d7fd53785 Wed Apr 30 13:03:38 2014 -0400 windows/amd64

What steps reproduce the problem?

<a href="http://play.golang.org/p/M5aR22tZSQ">http://play.golang.org/p/M5aR22tZSQ</a>

type Elem [16]uint64
type Elems []Elem

func (e Elems) SwapIdiom(i, j int) {
	e[i], e[j] = e[j], e[i]
}

func (e Elems) SwapUnrolled(i, j int) {
	a, b := &amp;e[i], &amp;e[j]
	a[0], b[0] = b[0], a[0]
	a[1], b[1] = b[1], a[1]
	a[2], b[2] = b[2], a[2]
	...
}

My measurements got:

SwapIdiom: 46.0ns/op
SwapUnrolled: 36.2ns/op

What should have happened instead?

I would expect the idiomatic to be as fast or faster than the manually unrolled version.</pre>

**Comment by ferluht** [comment]
Doesn't reproduce with the latest Go release

**Comment by bradfitz** [comment]
Thanks. Yeah, I suspect SSA helped with this.

I'll close this, but @randall77 @brtzsnr @josharian @dr2chase et al can reopen if they don't like the generated code.
