### ISSUE TITLE
crypto/rand: Read fails for non-interactive processes on Windows

### ISSUE THREAD

**Issue by alotabits** [golang/go#7940]
<pre>What does 'go version' print?

go version go1.2 windows/amd64

What steps reproduce the problem?

1. Create a simple cgi executable containing the code at
<a href="http://play.golang.org/p/DP7rJzhmUB">http://play.golang.org/p/DP7rJzhmUB</a>
2. Create an application in IIS 7.5 to run this as a cgi handler under DefaultAppPool,
with CGI/Impersonate User=False, and the web.config included at the link above (or
similar)
3. Visit URL of cgi handler

What happened?

Received &quot;CryptAcquireContext: Access is denied.&quot;

What should have happened instead?

Receive random gibberish

Please provide any additional information below.

Based on a limited understanding of the Windows cryto APIs from this reference page:

<a href="http://msdn.microsoft.com/en-us/library/windows/desktop/aa379886%28v=vs.85%29.aspx">http://msdn.microsoft.com/en-us/library/windows/desktop/aa379886%28v=vs.85%29.aspx</a>

I think adding the CRYPT_MACHINE_KEYSET flag to src/pkg/crypto/rand/rand_windows.go:30
might resolve the issue. I do not know what side-effects this might have.</pre>

**Comment by mattn** [comment]
I tried this but can't reproduce.

**Comment by FiloSottile** [comment]
The Windows crypto/rand backend has changed since. Please open a new issue if this re-occurs.
