### ISSUE TITLE
net/rpc: add client support for RPC over HTTPS

### ISSUE THREAD

**Issue by athomason** [golang/go#7946]
<pre>While net/rpc supports HTTPS trivially in the server, there's no built-in way for a
client to connect to one since rpc.DialHTTPPath calls net.Dial itself. With some
duplicated code from client.go it's possible to create a working DialHTTPSPath in user
code, though this is suboptimal since DialHTTPPath references an unexported package
variable which must be duplicated.

<a href="https://golang.org/cl/100140043">https://golang.org/cl/100140043</a> implements rpc.DialHTTPS and rpc.DialHTTPSPath
which are exact analogues to DialHTTP and DialHTTPPath apart from also accepting a
tls.Config. This issue is mainly to track that CL during the 1.3 code freeze.

I originally proposed this at
<a href="https://groups.google.com/forum/#">https://groups.google.com/forum/#</a>!topic/golang-nuts/M0LwsijM9bo; no objections were
offered.</pre>

**Comment by robpike** [comment]
The net/rpc package is frozen, so closing this.
