### ISSUE TITLE
doc: define how sync interacts with memory model

### ISSUE THREAD

**Issue by dvyukov** [golang/go#7948]
<pre>This is related to <a href="https://golang.org/issue/5045">issue #5045</a>.

We also need to define how primitives in sync package interact with memory model. E.g.
wg.Add happens-before wg.Done, once.Do function execution happens-before any of once.Do
returns, etc.</pre>

**Comment by glasser** [comment]
Note that Once is currently documented. WaitGroup still isn't.

**Comment by changkun** [comment]
I think this is done via https://go.dev/cl/381316. Close and feel free to reopen if anything else is still left to do
