### ISSUE TITLE
cmd/compile: independent variables should be initialized in declaration order

### ISSUE THREAD

**Issue by griesemer** [golang/go#7962]
<pre><a href="http://play.golang.org/p/icbjgkx71B">http://play.golang.org/p/icbjgkx71B</a>

got:
gc produces the initialization order: c b a .

want:
The variables b and c are independent of each other, and b is declared before c, so the
order should be: b c a .

gccgo reports the order: b c a .

Based on spec clarification <a href="https://golang.org/cl/99020043">https://golang.org/cl/99020043</a> (<a href="https://golang.org/issue/6703">issue #6703</a>).</pre>

**Comment by odeke-em** [comment]
Thank you for the filing @griesemer and @rsc!

Just like duplicate bugs #7320, #22326, it was fixed for Go1.13 by @mdempsky's CL [170062](https://go-review.googlesource.com/c/go/+/170062).

I shall thus close it.
