### ISSUE TITLE
sync/atomic: CAS on ARM does not provide memory fence

### ISSUE THREAD

**Issue by rui314** [golang/go#7977]
<pre>What does 'go version' print?
go version devel +2e591e82a8c8 Fri May 02 13:17:55 2014 -0700 + linux/amd64

What happened?
It's pointed out in <a href="https://golang.org/cl/91230048">https://golang.org/cl/91230048</a> that Go's CompareAndSwap
functions for ARM don't provide memory fence. As a result, on non-Linux OSes,
synchronization mechanisms including Mutex don't guarantee the Go memory model.

We need to add memory fence operations to CAS functions.</pre>

**Comment by crawshaw** [comment]
A consistent failure I am seeing on darwin/arm:

$ go test -cpu=2 -run=TestLFStackStress runtime
--- FAIL: TestLFStackStress-2 (0.58s)
        lfstack_test.go:128: Wrong number of nodes 3/100
FAIL

I'm not sure yet if this is the cas64 in the lfstack implementation or bug in the channel implementation. (I saw a chan_test.go failure fly by, but lost the text.) Still learning the runtime's atomic code and the ARM spec.

**Comment by crawshaw** [comment]
In attempting to swap out the darwin/arm builder for a 4th generation iPad (Apple A6X chip) I ran across this possibly-related error message:

```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x0 pc=0x4035e9c]

runtime stack:
runtime.throw(0x417cb70, 0x2a)
        /private/var/folders/q8/bf_4b1ts2zj0l7b0p1dv36lr0000gp/T/gobuilder/darwin-arm-crawshaw-dfc9e264d18a/go/src/runtime/panic.go:543 +0x7c
runtime.sigpanic()
        /private/var/folders/q8/bf_4b1ts2zj0l7b0p1dv36lr0000gp/T/gobuilder/darwin-arm-crawshaw-dfc9e264d18a/go/src/runtime/sigpanic_unix.go:12 +0x50
runtime.acquirep(0x0)
        /private/var/folders/q8/bf_4b1ts2zj0l7b0p1dv36lr0000gp/T/gobuilder/darwin-arm-crawshaw-dfc9e264d18a/go/src/runtime/proc1.go:2603 +0x54
runtime.stopm()
        /private/var/folders/q8/bf_4b1ts2zj0l7b0p1dv36lr0000gp/T/gobuilder/darwin-arm-crawshaw-dfc9e264d18a/go/src/runtime/proc1.go:1028 +0x17c
runtime.findrunnable(0x50120a00)
        /private/var/folders/q8/bf_4b1ts2zj0l7b0p1dv36lr0000gp/T/gobuilder/darwin-arm-crawshaw-dfc9e264d18a/go/src/runtime/proc1.go:1360 +0x57c
runtime.schedule()
        /private/var/folders/q8/bf_4b1ts2zj0l7b0p1dv36lr0000gp/T/gobuilder/darwin-arm-crawshaw-dfc9e264d18a/go/src/runtime/proc1.go:1459 +0x1d8
runtime.goschedImpl(0x501a8460)
        /private/var/folders/q8/bf_4b1ts2zj0l7b0p1dv36lr0000gp/T/gobuilder/darwin-arm-crawshaw-dfc9e264d18a/go/src/runtime/proc1.go:1533 +0xfc
runtime.gosched_m(0x501a8460)
        /private/var/folders/q8/bf_4b1ts2zj0l7b0p1dv36lr0000gp/T/gobuilder/darwin-arm-crawshaw-dfc9e264d18a/go/src/runtime/proc1.go:1541 +0x38
runtime.mcall(0x5018c000)
        /private/var/folders/q8/bf_4b1ts2zj0l7b0p1dv36lr0000gp/T/gobuilder/darwin-arm-crawshaw-dfc9e264d18a/go/src/runtime/asm_arm.s:178 +0x5c


goroutine 1 [chan receive]:
testing.RunTests(0x4195374,(lldb)  0x4204ca8, 0x2a, 0x2a, 0x1)
        /private/var/folders/q8/bf_4b1ts2zj0l7b0p1dv36lr0000gp/T/gobuilder/darwin-arm-crawshaw-dfc9e264d18a/go/src/testing/testing.go:561 +0x780

testing.(*M).Run(0x50116120, 0x4218328)
        /private/var/folders/q8/bf_4b1ts2zj0l7b0p1dv36lr0000gp/T/gobuilder/darwin-arm-crawshaw-dfc9e264d18a/go/src/testing/testing.go:490 +0x74
main.main()
        /var/folders/q8/bf_4b1ts2zj0l7b0p1dv36lr0000gp/T/go-build399665451/sync/atomic/_test/_testmain.go:142 +0x1b4


goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /private/var/folders/q8/bf_4b1ts2zj0l7b0p1dv36lr0000gp/T/gobuilder/darwin-arm-crawshaw-dfc9e264d18a/go/src/runtime/asm_arm.s:982 +0x4


goroutine 165 [chan receive]:
sync/atomic_test.TestStoreLoadRelAcq32(0x5011ce40)
        /private/var/folders/q8/bf_4b1ts2zj0l7b0p1dv36lr0000gp/T/gobuilder/darwin-arm-crawshaw-dfc9e264d18a/go/src/sync/atomic/atomic_test.go:1327 +0x218
testing.tRunner(0x5011ce40, 0x4204e40)
        /private/var/folders/q8/bf_4b1ts2zj0l7b0p1dv36lr0000gp/T/gobuilder/darwin-arm-crawshaw-dfc9e264d18a/go/src/testing/testing.go:452 +0xc8
created by testing.RunTests
        /private/var/folders/q8/bf_4b1ts2zj0l7b0p1dv36lr0000gp/T/gobuilder/darwin-arm-crawshaw-dfc9e264d18a/go/src/testing/testing.go:560 +0x754


goroutine 167 [runnable]:
runtime.Gosched()
        /private/var/folders/q8/bf_4b1ts2zj0l7b0p1dv36lr0000gp/T/gobuilder/darwin-arm-crawshaw-dfc9e264d18a/go/src/runtime/proc.go:157 +0x10
sync/atomic_test.TestStoreLoadRelAcq32.func1(0x1, 0x50118a20, 0x50224000, 0x5011ce40, 0x5011eec0)
        /private/var/folders/q8/bf_4b1ts2zj0l7b0p1dv36lr0000gp/T/gobuilder/darwin-arm-crawshaw-dfc9e264d18a/go/src/sync/atomic/atomic_test.go:1314 +0xec
created by sync/atomic_test.TestStoreLoadRelAcq32
        /private/var/folders/q8/bf_4b1ts2zj0l7b0p1dv36lr0000gp/T/gobuilder/darwin-arm-crawshaw-dfc9e264d18a/go/src/sync/atomic/atomic_test.go:1325 +0x1ec
Process 559 exited with status = 2 (0x00000002)
go_darwin_arm_exec: exit status 253
FAIL sync/atomic_test 21.858s
```

**Comment by crawshaw** [comment]
I'm a little worried about not fixing this for Go 1.5, because it may affect iOS.

This can be fixed for iOS in a similar way to the linux fix. Because iOS always implies cgo, we can pass the darwin OSAtomicCompareAndSwap64Barrier symbol into the runtime and use it the way we do the linux-provided CAS.

Does that seem reasonable?

**Comment by minux** [comment]
Here is the disassembly for armv7s version of
OSAtomicCompareAndSwap64Barrier:
_OSAtomicCompareAndSwap64Barrier:
2f9d4198            b580        push    {r7, lr}
2f9d419a            466f        mov     r7, sp
2f9d419c        f8d79008        ldr.w   r9, [r7, #8]
2f9d41a0        e8d9ce7f        ldrexd  r12, lr, [r9]
2f9d41a4        ea8e0e01        eor.w   lr, lr, r1
2f9d41a8        ea8c0c00        eor.w   r12, r12, r0
2f9d41ac        ea5c0c0e        orrs.w  r12, r12, lr
2f9d41b0            d10f        bne     0x2f9d41d2
2f9d41b2        f3bf8f5a        dmb     ishst
2f9d41b6        e8c9237c        strexd  r12, r2, r3, [r9]
2f9d41ba        f1bc0f00        cmp.w   r12, #0x0
2f9d41be            d00a        beq     0x2f9d41d6
2f9d41c0        e8d9ce7f        ldrexd  r12, lr, [r9]
2f9d41c4        ea8e0e01        eor.w   lr, lr, r1
2f9d41c8        ea8c0c00        eor.w   r12, r12, r0
2f9d41cc        ea5c0c0e        orrs.w  r12, r12, lr
2f9d41d0            d0f1        beq     0x2f9d41b6
2f9d41d2            2000        movs    r0, #0x0
2f9d41d4            bd80        pop     {r7, pc}
2f9d41d6            2001        movs    r0, #0x1
2f9d41d8        f3bf8f5b        dmb     ish
2f9d41dc            bd80        pop     {r7, pc}
2f9d41de            bf00        nop

I've verified that the arm64 version doesn't have barrier.

We can just DMB instruction to our CAS implementation.
