### ISSUE TITLE
x/tools: random program generator for testing

### ISSUE THREAD

**Issue by dvyukov** [golang/go#7985]
<pre>There is CSmith (<a href="http://embed.cs.utah.edu/csmith/)">http://embed.cs.utah.edu/csmith/)</a> that generates random correct C
programs, and it's proved to be extremely useful in testing C compilers.

We could do something similar for Go.
The tool can use existing ast/types/ssa packages for program generation and
serialization. The tool can start very small, e.g generate only simple assignment
statement. And then gradually grow.

The tool could be used for testing of a range of programs and packages besides gc/gccgo
compilation:
- gofmt idempotentness (gofmt several times and compare results)
- ast/types/ssa robustness and idempotentness (generate, serialize, parse, serialize,
parse, compare).
- govet robustness
- compilation in race mode which had lots of bugs in past
- compare gc, gccgo, ssa/interp output

I foresee piles of bugs there.</pre>

**Comment by ALTree** [comment]
Implemented: [dvyukov/go-fuzz](https://github.com/dvyukov/go-fuzz), so closing this.
