### ISSUE TITLE
cmd/compile: unnecessary nil checks on address of return values

### ISSUE THREAD

**Issue by randall77** [golang/go#7994]
<pre>package main
func foo(x int) (y int) {
     p := &amp;x
     q := &amp;y
     *q = *p
     return
}

compile with &quot;go tool 6g -S foo.go&quot;

The assembly is 

0005  MOVQ    $0,y+8(FP)
0006  LEAQ    x+0(FP),BX
0007  MOVQ    BX,CX
0008  LEAQ    y+8(FP),BX
0009  CMPQ    BX,$0
0010  JNE     $1,12
0011  MOVL    AX,(BX)
0012  NOP     ,
0013  MOVQ    (CX),R8
0014  MOVQ    R8,(BX)
0015  RET     ,

There is a nil check (CMPQ/JNE/MOVL/NOP) on the address of the return value, a value
that certainly non-nil.

Note that there is no nil check on the address of the argument.</pre>

**Comment by rsc** [comment]
Too late for Go 1.5. SSA may replace this code.

**Comment by tzneal** [comment]
dev.ssa currently generates: 

    00000  MOVQ    $0, AX
    00002  MOVQ    AX, 16(SP) 
    00007  MOVQ    8(SP), AX
    00012  MOVQ    AX, 16(SP)
    00017  RET

deadstore elimination doesn't work across blocks, or it would be even better.

**Comment by randall77** [comment]
Fixed with SSA backend.
