### ISSUE TITLE
cmd/compile: internal compiler error: out of fixed registers

### ISSUE THREAD

**Issue by dvyukov** [golang/go#8012]
<pre>go version devel +c9bcacf2ba33 Wed May 14 19:24:00 2014 +0400 + linux/amd64

Program:
<a href="http://play.golang.org/p/s5dPvO0hf7">http://play.golang.org/p/s5dPvO0hf7</a>

$ go build test.go
0 0
1 0
2 0
3 519444
4 0
5 519444
6 0
7 0
8 519444
9 519444
10 519832
11 519444
12 519444
13 519444
14 519444
15 519444
test.go:21: internal compiler error: out of fixed registers

arm and 386 compile successfully.</pre>

**Comment by randall77** [comment]
Fixed with SSA backend.
