### ISSUE TITLE
cmd/gc: spurious "fallthrough statement out of place"

### ISSUE THREAD

**Issue by dvyukov** [golang/go#8041]
<pre>go version devel +4a839bf01b58 Tue May 20 15:52:08 2014 +1000 + linux/amd64

<a href="http://play.golang.org/p/iVY1-AI1B2">http://play.golang.org/p/iVY1-AI1B2</a>

$ go build src.go 
src.go:11: fallthrough statement out of place

Works on playground, so probably with Go1.2 as well.

After s/foo(0)/0/ it compiles successfully.</pre>

**Comment by DanielMorsing** [comment]
The test program works on current tip (c0fa9e3f6ff0c63d063d81c859a7f87a519a4182).
