### ISSUE TITLE
cmd/compile: spurious "goto label jumps over declaration"

### ISSUE THREAD

**Issue by dvyukov** [golang/go#8042]
<pre>go version devel +4a839bf01b58 Tue May 20 15:52:08 2014 +1000 + linux/amd64

The program is:
package main
func main() {
    goto label
    type X int
    label:
}

$ go build goto.go
goto.go:3: goto label jumps over declaration of X at goto.go:4

The spec only requires new variables to not come into scope:
&quot;Executing the &quot;goto&quot; statement must not cause any variables to come into
scope that were not already in scope at the point of the goto&quot;.</pre>

**Comment by DanielMorsing** [comment]
Fix at https://go-review.googlesource.com/#/c/9442/

**Comment by bradfitz** [comment]
I reverted the fix, since it broke all the builds.

**Comment by rsc** [comment]
Too late for Go 1.5.

**Comment by IronGopher** [comment]
At the risk of sounding like a fool: suppose that the next line in `main` in dvyukov's example is

    var v X = 0

What then? I think this is a problem with the spec, and not the toolchain.

**Comment by griesemer** [comment]
@IronGopher If the declaration were about a variable X rather than a type, then it would be a correct error. The issue is that it's only an error if variables are coming into scope, not types or constants. The spec is clear. This is a compiler bug.

**Comment by djadala** [comment]
CC  @griesemer @dvyukov 
If i modify original program as:
```
package main
func main() {
    goto label
    X := 0
    label:
}
```
output is still:
```
go build t.go
# command-line-arguments
./t.go:3:10: goto label jumps over declaration of X at ./t.go:4:7

go version
go version go1.9 linux/amd64
```
Should  new bug be opened ?

**Comment by dvyukov** [comment]
@djadala 
> Should new bug be opened ?
yes

**Comment by odeke-em** [comment]
@djadala I can't reproduce https://github.com/golang/go/issues/8042#issuecomment-333481153 on tip though
```shell
$ cat main.go && go version && go build main.go  && echo "Success" || echo "Fail"
package main
func main() {
    goto label
    type X int
    label:
}
go version devel +a82ee9c Sat Sep 30 17:01:26 2017 +0000 darwin/amd64
Success
```

**Comment by djadala** [comment]
s/ type X int/ X := 0/

**Comment by odeke-em** [comment]
Never mind my last comment, your bug still stands even on the latest code @djadala :)

**Comment by djadala** [comment]
ok, new issue is #22101

**Comment by odeke-em** [comment]
Okay hold up though, your program isn't correct and you have made a declaration with
```go
goto L
X := 0
```
A goto shouldn't allow a variable that wasn't already in scope to come into scope. I don't see the bug here.

**Comment by odeke-em** [comment]
@djadala I've commented on the other issue that this isn't a bug, and coincidentally the spec provides a similar example to what you posted
https://golang.org/ref/spec#GotoStmt

Initially I had copied and pasted the original code without checking it, but on a closer look I deduced that this isn't a bug.

**Comment by djadala** [comment]
Sorry for noise,
 i thought if variable is not used after label, this must compile, but i'm  wrong.

**Comment by odeke-em** [comment]
Not a problem at all @djadala, thank you for checking up on the bug.
