### ISSUE TITLE
gccgo: double close of channel is unrecoverable

### ISSUE THREAD

**Issue by axw** [golang/go#8070]
<pre>What does 'go version' print?

$ gccgo -v
Using built-in specs.
COLLECT_GCC=gccgo
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.9/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.9-20140406-0ubuntu1'
--with-bugurl=file:///usr/share/doc/gccgo-4.9/README.Bugs --enable-languages=c,c++,go
--prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id
--libexecdir=/usr/lib --without-included-gettext --enable-threads=posix
--with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls
--with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-time=yes
--enable-gnu-unique-object --disable-libmudflap --disable-libquadmath --enable-plugin
--with-system-zlib --enable-multiarch --disable-werror --with-arch-32=i686
--with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic
--enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu
--target=x86_64-linux-gnu
Thread model: posix
gcc version 4.9.0 20140405 (experimental) [trunk revision 209157] (Ubuntu
4.9-20140406-0ubuntu1)

What steps reproduce the problem?
If possible, include a link to a program on play.golang.org.

1. Close a channel twice, with a recover.
2. Recover triggers, but afterwards unwinding aborts the process.

Repro: <a href="http://play.golang.org/p/eUJw-e1GRJ">http://play.golang.org/p/eUJw-e1GRJ</a>

What happened?

Process aborts.

What should have happened instead?

Clean exit.</pre>

**Comment by paranoiacblack** [comment]
I'm unable to reproduce this on tip, but I'm not sure what fixed it.
