### ISSUE TITLE
x/tools/cmd/godoc: provide command-line equivalent to ?m=all

### ISSUE THREAD

**Issue by dominikh** [golang/go#8093]
Commit a64b269 added an option to display documentation for unexported
identifiers. For the web version, this can be achieved via `?m=all`. On the command
line, the only way to trigger displaying of all documentation is when using the `-src`
flag, in combination with specifying a filter. 

There should be a way to display documentation for unexported identifiers without also
showing the source, and without having to specify a filter (even though specifying a
filter should still be possible.) Maybe an `-all` flag?

**Comment by LouAdrien** [comment]
Hello, any update on this?

**Comment by andybons** [comment]
@LouAdrien it’s a reasonable request. Someone just needs to do the work. Patches welcome!
