### ISSUE TITLE
cmd/gc: spurious "mixture of field:value and value initializers" error

### ISSUE THREAD

**Issue by dvyukov** [golang/go#8099]
<pre>go version go1.3beta2 +708e129e91a9 Wed May 21 16:01:54 2014 -0700 linux/amd64

The program is:

package main
func main() {
	x := []int{}
	_ = [2][]func(){
		{
			func() {
				_ = x[0]
			},
		},
	}
}

$ go build src.go
src.go:7: mixture of field:value and value initializers
src.go:7: tempname called with nil type</pre>

**Comment by rsc** [comment]
Empirically, fixed in Go 1.4.
