### ISSUE TITLE
cmd/5g: ICE regfree: reg R0 not allocated

### ISSUE THREAD

**Issue by dvyukov** [golang/go#8101]
<pre>go version go1.3beta2 +708e129e91a9 Wed May 21 16:01:54 2014 -0700 linux/amd64

The program is:

package p
var c0 []chan int
var s0 []int
var s1 []**int
var i = 0
var boom = cap(c0[s0[len(c0[**(s1)[s0[s0[**s1[s0[s0[s0[i]]+1]-1]]]]])]+1])

$ GOARCH=arm go build src.go 
registers allocated at
0 409644
1 409bcf
2 409473
3 40a11c
4 40a11c
5 409bcf
6 409bcf
7 40a42d
8 40a7b4
9 0
10 0
src.go:6: out of fixed registers
src.go:6: internal compiler error: regfree: reg R0 not allocated

6g and 8g compile successfully.</pre>

**Comment by rsc** [comment]
Looks fixed.

g% cat /tmp/x.go
	package p
	var c0 []chan int
	var s0 []int
	var s1 []**int
	var i = 0
	var boom = 
	cap(c0[s0[len(c0[**(s1)[s0[s0[**s1[s0[s0[s0[i]]+1]-1]]]]])]+1])
g% GOARCH=arm GOOS=linux go tool compile /tmp/x.go
g%

**Comment by davecheney** [comment]
Attempting to land https://go-review.googlesource.com/10832 showed that this issue remains present on 386
```
##### ../test
# go run run.go -- fixedbugs/issue8101.go
exit status 1
run compiler with -v for register allocation sites
/tmp/workdir/go/test/fixedbugs/issue8101.go:15: internal compiler error: out of fixed registers
```
https://storage.googleapis.com/go-build-log/2b8cc5d9/linux-386_c549e65d.log

**Comment by rsc** [comment]
Too late for Go 1.5. Also SSA will eliminate this entire class of bugs, so probably not worth fixing anyway.

**Comment by randall77** [comment]
Fixed with SSA backend.
