### ISSUE TITLE
runtime/race: documentation file doesn't exist

### ISSUE THREAD

**Issue by randall77** [golang/go#8141]
<pre>The page <a href="http://golang.org/pkg/runtime/race/">http://golang.org/pkg/runtime/race/</a>
 references the page <a href="http://golang.org/doc/articles/race_detector.html">http://golang.org/doc/articles/race_detector.html</a> for documentation.  That page doesn't exist.</pre>

**Comment by dvyukov** [comment]
Both
http://golang.org/doc/articles/race_detector.html
and
http://tip.golang.org/doc/articles/race_detector.html
are present
