### ISSUE TITLE
cmd/go: building cross compilers sets the default CC/CXX to whatever was built last

### ISSUE THREAD

**Issue by OneOfOne** [golang/go#8161]
<pre>What does 'go version' print?
go version go1.3rc1 linux/amd64
(built from tip on 2014-06-07 5:50pm CST)

What steps reproduce the problem?

1. cd $GOROOT/src
2. CC=gcc ./make.bash
3. GOOS=windows GOARCH=386 CC_FOR_TARGET=i686-w64-mingw32-gcc CGO_ENABLED=1 ./make.bash
4. go env | grep CC=

What happened?
It prints CC=&quot;i686-w64-mingw32-gcc&quot;, trying to compile a native (linux/amd64)
executable that uses cgo fails with cc1: sorry, unimplemented: 64-bit mode not compiled
in.

What should have happened instead?
It should've print CC=&quot;gcc&quot; and GOOS=windows GOARCH=386 go env | grep CC=
should print CC=&quot;i686-w64-mingw32-gcc&quot;.

Please provide any additional information below.
Minimal example : <a href="http://play.golang.org/p/FYOPuqiZey">http://play.golang.org/p/FYOPuqiZey</a></pre>

**Comment by jsarenik** [comment]
Any ideas about how to fix this? What about starting to use prefixes like gcc?

**Comment by jsarenik** [comment]
I mean something like `$(config.guess)-go`...
where `config.guess` can stand for
  - x86_64-pc-linux-gnu
  - armv7l-unknown-linux-gnueabihf
  - ...

**Comment by jsarenik** [comment]
But this might just be an issue of the sources I am trying to compile... investigating.

**Comment by ianlancetaylor** [comment]
We aren't going to use prefixes for the go tool.

It's not obvious to me that anything needs to change besides documentation.  It's only necessary to build the go tools once.  It's true that when you do that the compiler being used will be recorded.  Once they are built, you can just set GOOS and GOARCH to cross-compile Go code; you don't need to run make.bash again.  You do need to set CC to cross-compile C code, CXX to cross-compile C++ code, etc.

We could add a way for the go tool to map from GOOS/GOARCH to the non-Go compilers to use.  But you could also write that map as a shell script that sets environment variables before invoking the go tool.  And there is no obvious way to automatically populate that map.

**Comment by jsarenik** [comment]
Thanks for reply. Slowly I'm getting into it and it starts to make sense.

**Comment by mwhudson** [comment]
> We could add a way for the go tool to map from GOOS/GOARCH to the non-Go compilers to use. But you could also write that map as a shell script that sets environment variables before invoking the go tool. And there is no obvious way to automatically populate that map.

If the Go tool supported a mechanism like this, then maybe distro/OS packaging could populate this in a way that's appropriate for a given environment? Just a thought.

**Comment by anguslees** [comment]
@ianlancetaylor: I read you last comment as saying "you just need to build the go tools once, then that toolchain will automatically support all the available golang targets, just by setting GOOS/GOARCH"  (but CC has to be managed yourself).  Is that correct?  If so, then that's great, and the ability for a single go build to support multiple targets wasn't at all clear from the "install from source" docs, nor the current structure of make.bash, which makes some attempts to set GOOS/GOARCH specifically for the intended target (not host) platform.

If my interpretation was not correct, and we do indeed need a new build of the toolchain for each host-target GOOS/GOARCH combination, then I'm still confused how that should be managed without some sort of per-target executable prefix or install location.

I'm currently in the middle of trying to build an amd64->arm go1.6 cross toolchain within an openembedded recipe and finding it much harder than I expected, not being familiar with the internals of the go toolchain.  More sagely advice sought.

**Comment by ianlancetaylor** [comment]
In general, discussion should probably move off this issue and into a forum.  See https://golang.org/wiki/Questions.  Thanks.

It is true today, but was not always true, that once you have built the Go tools for one system, you only need to set GOOS/GOARCH to build Go programs for a different system.  I agree that the documentation has not entirely caught up with the source code.

**Comment by OneOfOne** [comment]
Sorry for the extra comment but this might help people looking at this issue:

To compile for a supported os/arch all you need to do is just to run:

```
env GOOS=os GOARCH=arch go build
#eg
env GOOS=linux GOARCH=arm64 go build
# or to support cgo:
# install gcc for your target, depends on the distro then for example for arm:
env CGO_ENABLED=1 GOOS=linux GOARCH=arm64 CC=arm-eabi-gcc go build
```

That's all you have to do, nothing else.
