### ISSUE TITLE
x/tools/cmd/benchcmp: warn about outliers for -best mode.

### ISSUE THREAD

**Issue by minux** [golang/go#8182]
<pre>for example, given these data (those are real data):
// new.txt
BenchmarkGoroutineForRange       500       3915445 ns/op
BenchmarkGoroutineForRange       500       3873353 ns/op
BenchmarkGoroutineForRange       500       3850778 ns/op
BenchmarkGoroutineForRange       500       3903556 ns/op
BenchmarkGoroutineForRange       500       3768451 ns/op

// old.txt
BenchmarkGoroutineForRange       500       3922159 ns/op
BenchmarkGoroutineForRange      1000       1766253 ns/op
BenchmarkGoroutineForRange       500       3916289 ns/op
BenchmarkGoroutineForRange       500       3903132 ns/op
BenchmarkGoroutineForRange       500       3890627 ns/op

benchcmp -best reports this:
BenchmarkGoroutineForRange                1766253       3768451       +113.36%

However, the 2nd run of old.txt is obviously an outliner.
benchcmp should track and warn about this kind of strange data points.

I propose this criteria: if the max. difference between different runs in the same
file is on the same order of difference than that of best of old and new runs,
benchcmp should warn.</pre>

**Comment by ALTree** [comment]
This is a benchcmp issues that is solved by using benchstat, which is what we recommend now anyway. Closing here.
