### ISSUE TITLE
godoc: maybe make the .md file visible

### ISSUE THREAD

**Issue by robpike** [golang/go#8198]
<pre>It's a shame that godoc (and godoc.org) do such a nice job showing package information
but don't present the .md file that is the github-traditional source of most
documentation. We should perhaps (I stress perhaps) do something about that.

Several possibilities arise:

1) Just publish the .md file in the output. Probably a bad choice since it would require
godoc to understand the format and figure out where to present it in the output. Godoc
already has enough to do.

2) Provide a separate tool that does understand .md file and writes a doc.go for you, so
it's easy to provide the information to godoc.

3) Provide a separate tool that takes godoc output and writes a .md file for you, so
it's easy to provide the information to github.

Probably more.

For discussion.</pre>

**Comment by rsc** [comment]
I'd like to see a godoc html output -> md file generator in some form.
(Probably directly, not by parsing the html.)

**Comment by arvenil** [comment]
Still missing this. This or at least properly working https://github.com/golang/go/issues/2381
Right now it's really difficult to produce nice documents for internal/private tools.

**Comment by Kegsay** [comment]
I might take a stab at this (option 3) - are there any available docs on the structure of the plaintext output of `godoc` so I don't need to do this by trial and error as I encounter new sections? Also, as per https://github.com/golang/go/issues/2381#issuecomment-257830187, how should dependencies be linked together?

**Comment by dsnet** [comment]
Is this issue still relevant given that https://pkg.go.dev shows the readme.md file for modules?

**Comment by arvenil** [comment]
Is there a pkg.go.dev tool similar to https://pkg.go.dev/golang.org/x/tools/cmd/godoc ?

**Comment by seankhliao** [comment]
pkgsiste does this.
