### ISSUE TITLE
testing: support pausing cpu profiling in benchmarks

### ISSUE THREAD

**Issue by masiulaniec** [golang/go#8213]
<pre>The benchmarking part of the &quot;testing&quot; package supports stopping timers while
performing complex initialisation. Perhaps something analogous could be added for cpu
profiling, so that -cpuprofile can produce a data file that excludes samples for the
complex initialisation.

The current workaround is to avoid -cpuprofile in favour of calling
runtime.StartCPUProfile from within the benchmark.</pre>

**Comment by rsc** [comment]
This is infeasible.
