### ISSUE TITLE
x/tools/cmd/godoc: referred packages don't have link in documentation

### ISSUE THREAD

**Issue by chai2010** [golang/go#8223]
<pre>For example, the `image.Image` has no link:
<a href="http://godoc.org/github.com/chai2010/gopkg.image/bmp">http://godoc.org/github.com/chai2010/gopkg.image/bmp</a>

The &quot;github.com/chai2010/gopkg.image&quot; package name is `image`.

I think we need a `ImportSpec.PkgName` for the original package name.</pre>

**Comment by garyburd** [comment]
Godoc.org guesses the package name from the path.  The guess does not work in this case.

The issue should be filed on the godoc.org issue tracker at https://github.com/golang/gddo/issues

**Comment by rakyll** [comment]
The same behavior would also good to have in the scope of x/tools/cmd/godoc, but also filed an issue for godoc.org at https://github.com/golang/gddo/issues/433.

**Comment by agnivade** [comment]
@chai2010 - I am having a bit of trouble reproducing the issue because the repo "github.com/chai2010/gopkg.image" doesn't exist now.

Do you have a sample repo or example to demonstrate the issue ?

AFAI see, the scenario `myImage "github.com/chai2010/gopkg.image"` gets properly linked.
