### ISSUE TITLE
regexp: individual regexp scales poorly under highly concurrent use

### ISSUE THREAD

**Issue by jrockway** [golang/go#8232]
<pre>version: go1.3rc2

When matching against a regexp that's shared between goroutines, the program spends most
of its time waiting for the locks here:

68 @ 0x413579 0x4135fb 0x424eae 0x425080 0x496096 0x449dd7 0x4474fe 0x44df9e 0x400c6c
0x413810
#	0x425080	sync.runtime_Semacquire+0x30			/go/gc/src/pkg/runtime/sema.goc:199
#	0x496096	sync.(*Mutex).Lock+0xd6				/go/gc/src/pkg/sync/mutex.go:66
#	0x449dd7	regexp.(*Regexp).get+0x37			/go/gc/src/pkg/regexp/regexp.go:192
#	0x4474fe	regexp.(*Regexp).doExecute+0x5e			/go/gc/src/pkg/regexp/exec.go:423
#	0x44df9e	regexp.(*Regexp).FindStringSubmatch+0x9e	/go/gc/src/pkg/regexp/regexp.go:883
#	0x400c6c	main.match+0x6c					experimental/users/jrockway/regex.go:24

56 @ 0x413579 0x4135fb 0x424eae 0x425080 0x496096 0x449f2a 0x4477a4 0x44df9e 0x400c6c
0x413810
#	0x425080	sync.runtime_Semacquire+0x30			/go/gc/src/pkg/runtime/sema.goc:199
#	0x496096	sync.(*Mutex).Lock+0xd6				/go/gc/src/pkg/sync/mutex.go:66
#	0x449f2a	regexp.(*Regexp).put+0x3a			/go/gc/src/pkg/regexp/regexp.go:210
#	0x4477a4	regexp.(*Regexp).doExecute+0x304		/go/gc/src/pkg/regexp/exec.go:450
#	0x44df9e	regexp.(*Regexp).FindStringSubmatch+0x9e	/go/gc/src/pkg/regexp/regexp.go:883
#	0x400c6c	main.match+0x6c					experimental/users/jrockway/regex.go:24

With GOMAXPROCS=32 on a 32 core machine, we end up only using about 700% CPU according
to /usr/bin/time.

If we give each goroutine its own copy of the regexp (created in the goroutine with
regexp.MustCompile), then we use 2500% CPU.  This is much more reasonable.

While my actual problem occurs in a process that is reading data from the network, the
attached test case reproduces the issue rather well.

(Note: time CPU timing is done with the profile printer code commented out.  The test
case is compiled with optimization on.)</pre>

Attachments:

1. <a href="https://storage.googleapis.com/go-attachment/8232/0/regex.go">regex.go</a> (878 bytes)

**Comment by rsc** [comment]
Too late for Go 1.5.

**Comment by maxbaldin** [comment]
@rsc why possibility to use regexp in high-concurrent application was removed from 1.5 release? :(

**Comment by cespare** [comment]
@maxbaldin If this is a bottleneck in your code, you can work around it today by using a different `regexp.Regexp` in each goroutine. Based on what @rsc mentioned above, it may be that in future Go versions that becomes slightly easier via a Copy method or something.

**Comment by cespare** [comment]
I gave the Copy approach a shot in https://golang.org/cl/16110. I also compared benchmarks against @rsc's RegexpForSingleGoroutine; that gave a 7% improvement over the no-contention Copy version using the regex @bradfitz and @dvyukov were using above. (See CL for details.)

**Comment by rsc** [comment]
Fixed (at least worked around) in CL 16110.
