### ISSUE TITLE
net: ipv6 entries with many aliases in /etc/hosts confuse both cgo and netgo lookup functions

### ISSUE THREAD

**Issue by tamasd** [golang/go#8235]
<pre>go version go1.3 darwin/amd64

I cloned the hg repository, and ran ./all.bash. Some network tests have failed. I tried
turning off my firewall. I also removed the repository and recloned the contents. I am
running Mac OS X 10.9.3 on a Late 2013 MacBook Pro.

--- FAIL: TestDialDualStackLocalhost (0.00 seconds)
	dial_test.go:493: Dial failed: dial tcp 127.0.0.1:64057: connection refused
--- FAIL: TestResolveIPAddr (0.00 seconds)
	ipraw_test.go:76: got &amp;net.IPAddr{IP:net.IP{0xfe, 0x80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1}, Zone:&quot;&quot;}; expected &amp;net.IPAddr{IP:net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1}, Zone:&quot;&quot;}
--- FAIL: TestResolveTCPAddr (0.00 seconds)
	tcp_test.go:335: ResolveTCPAddr(&quot;tcp6&quot;, &quot;localhost:7&quot;) = &amp;net.TCPAddr{IP:net.IP{0xfe, 0x80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1}, Port:7, Zone:&quot;&quot;}, want &amp;net.TCPAddr{IP:net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1}, Port:7, Zone:&quot;&quot;}
--- FAIL: TestResolveUDPAddr (0.00 seconds)
	udp_test.go:22: ResolveUDPAddr(&quot;udp6&quot;, &quot;localhost:7&quot;) = &amp;net.UDPAddr{IP:net.IP{0xfe, 0x80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1}, Port:7, Zone:&quot;&quot;}, want &amp;net.TCPAddr{IP:net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1}, Port:7, Zone:&quot;&quot;}
FAIL
FAIL	net	2.087s</pre>

**Comment by mikioh** [comment]
Closing. There's no easy way to solve this sort of issue except keeping files or databases clean.
