### ISSUE TITLE
encoding/json: UnmarshalTypeError should tell you what key you were unmarshaling

### ISSUE THREAD

**Issue by kbloom** [golang/go#8254]
<pre>As seen at
<a href="http://stackoverflow.com/questions/24325210/get-field-name-that-errs-in-go-json-unmarshal">http://stackoverflow.com/questions/24325210/get-field-name-that-errs-in-go-json-unmarshal</a>,
it would make it easier to debug JSON decoding errors, if UnmarshalTypeError would tell
you which key you were unmarshaling when you encountered the type error.</pre>

**Comment by petemoore** [comment]
I think it would be helpful here for json.UnmarshalTypeError to have a reference to the full set of bytes that were being unmarshalled, and the character location where the decoding failed. It could even print context lines with an extra line with a ^ character pointing to the problem character:

```
json: cannot unmarshal #/Person/properties/job/description into Go value of type string.
Failed on line 42 at character 33:
  40     "properties": {
  41         "job": {
  42             "description": 7,
                                ^
  43             "salary": 100000
  45         },
```
```

**Comment by rjeczalik** [comment]
@petemoore it's already in master by #9693. Using offset you can then write your own tool for visualization.
