### ISSUE TITLE
proposal: spec: create builtin interfaces, let builtin types fulfill them

### ISSUE THREAD

**Issue by metakeule** [golang/go#8303]
<pre>1. Provide a package builtin/interf with interfaces of the kind of

     type Stringer interface {
        String() string
     }

     type Booler interface {
        Bool() bool
     }

for the following builtin types:

bool, byte, complex128, complex64, float32, float64, int, int16, int32, int64, int8,
rune,
string, uint, uint16, uint32, uint64, uint8

2. Have the compiler use the builtin when it is assigned to &quot;its&quot; interface,
as if
each builtin would fulfill its corresponding interface from builtin/interf.

So code like this

     import &quot;builtin/interf&quot;
     
     func a(b interf.Booler) {
       // do something with b.Bool()
     }
     
     func main() {
       a(true)
     }

would compile and optimized, so that the performance and allocation characteristics for
the call
 a(true) would be the same as if a had the signature to receive a bool.
That means assignment of a builtin to &quot;its&quot; interface and call of
&quot;its&quot; interface's method should cost nothing.

WHY and WHAT IS IT FOR?

There are times more often than not, where we want the meantioned builtins to be
optional.
An example would be the use of the json package with structs where there is no easy way
to have optional builtins, like shown in this blog post:

<a href="https://willnorris.com/2014/05/go-rest-apis-and-pointers?utm_content=bufferb70ff&amp">https://willnorris.com/2014/05/go-rest-apis-and-pointers?utm_content=bufferb70ff&amp</a>;utm_medium=social&amp;utm_source=twitter.com&amp;utm_campaign=buffer

As it turns out, the best solution is to define optional values as interfaces, as shown
here:
<a href="http://play.golang.org/p/cIO2yQ4676">http://play.golang.org/p/cIO2yQ4676</a>

The optional aspect is expression via the fact that any interface may be nil.

There are other places where optional builtins make programming with go awkward, e.g. the
Null* types in the database/sql package.

The problem is that every package wanting to have optional builtins will resort to its
own solution. Some of them are type wrappers leading incompatible types and solutions
between packages and a lot of mental and coding boilerplate.

The proposed solution would not only provide a idiomatic and performant solution, but
also allows
some function signatures to relax and accept the new builtin interfaces instead of  the
builtin and
by that be compatible with the builtins without performance digression but also flexible
enough to
be used with custom implementations.

builtin/interf being a package that has to be included in order to be used, means we are
staying compatible and optional.</pre>

**Comment by ianlancetaylor** [comment]
This proposal is a way of adding optional types to Go: a type that can hold either a value or an indication that there is no value.  I'm going to close this as a dup of #19412, where there is a lot of discussion about optional types as a particular kind of sum type.
