### ISSUE TITLE
math/rand: add io.Reader interface to type Rand

### ISSUE THREAD

**Issue by wathiede** [golang/go#8330]
<pre>This is a feature request I would be willing to implement if it is deemed appropriate.

I often find myself wanting to generate large pseudo-randomly filled files for testing
and benchmarks.  The io.Reader interface in crypto/rand is nice, but it is
non-deterministic by design.  Having an io.Reader interface on math/rand.Rand, paired
with a consistent seed, would allow consistent random number generation from run-to-run
of tests and benchmarks.

Would this be an appropriate addition to the standard library?</pre>

**Comment by jpillora** [comment]
:+1: (Is +1ing issues the right way to show interest?)

**Comment by adg** [comment]
@jpillora unfortunately @github provides no way to show support for an interest besides commenting, but that just creates comment spam. Better to provide more information about your particular use case explaining what might make this a compelling feature.

**Comment by jpillora** [comment]
@adg Will do that in the future. Basically, a deterministic `crypto.Reader` for reproducibility. In the mean time, I guess I could achieve this by repeatedly hashing some seed data and return the output stream.

**Comment by spenczar** [comment]
This issue is old and low priority, but simple to implement. I'd like to try contributing to Go - is there sufficient interest for me to submit a CR? I don't know whether APIs like `math/rand.Rand` are considered frozen.

**Comment by ianlancetaylor** [comment]
I think it would be fine to add something to math/rand that implements io.Reader.  Probably Rand should get a Read method.  I'm not sure how to best implement it--pull seven bytes out of every call to Int63?

**Comment by spenczar** [comment]
Yep, that's the plan.

I'll send a CR, thanks for the speedy reply!
