### ISSUE TITLE
cmd/compile: out of fixed registers (nested array/slice indexing) on amd64

### ISSUE THREAD

**Issue by remyoudompheng** [golang/go#8355]
<pre>1. What is a short input program that triggers the error?

<a href="http://play.golang.org/p/m59dvc6cXo">http://play.golang.org/p/m59dvc6cXo</a>

Also a reduced example:

package main

type T struct {
	F int
}

func f() {
	var (
		A = [][1]int{}
		B = []int{3: 1, 4: 1}
		X [2]byte
		Y [2]int
		Z []float64
		n int

		S     []T
		Funcs = [0]func() uintptr{}
	)

	var Var813 = Funcs[int(B[Y[S[A[X[int(Z[n])]-1][n]+1].F+1]])]()

        _ = Var813
}

2. What is the full compiler output?

0 0
1 0
2 0
3 40cee6
4 0
5 40a25c
6 0
7 0
8 40a25c
9 412470
10 40a25c
11 40a25c
12 40a25c
13 40999d
14 40ab97
15 40a2f5
bug1.go:20: internal compiler error: out of fixed registers

3. What version of the compiler are you using?  (Run it with the -V flag.)

go version devel +0a0e0c40901d Tue Jul 08 14:47:52 2014 -0400 linux/amd64</pre>

**Comment by griesemer** [comment]
From #10088: Make sure this code works as well:
```
package main
func main() {
    type X struct {
        f int
    }
    var x X
    var xx []X
    var s0 []int
    var s1 []func()
    var s2 [][][]int
    var s3 [][]int
    var s4 [][]int16
    s1[xx[int(s4[0][s0[s3[s0[s2[s3[s0[s0[s0[x.f]]-1]+1][0]-1][0][0]]-1][0]]+1])].f-1]() 
}
```

**Comment by randall77** [comment]
Fixed with new SSA backend.
