### ISSUE TITLE
x/tour: no way to terminate a snippet that has continued running

### ISSUE THREAD

**Issue by kortschak** [golang/go#8395]
<pre>The Go tour does not provide the same process kill function provided by e.g. present
although the underlying runner can handle these messaged. For the majority of cases this
is not an issue - it is when people are working on the http lessons where the socket
being held by an incorrect but runnable snippet will block later attempts.

The http lesson stubs should probably handle the returned errors (or otherwise prompt
the user that errors are good to check) from ListenAndServe to help users diagnose why a
edited change is not seen when the snippet is re-run.

gotour version: 91f9594fc692+</pre>

**Comment by kytrinyx** [comment]
It looks like there are two things in place to protect against this issue:

1. The "run" button now turns into a "kill" button
2. If something takes a long time the program exits with "process took too long"

I think this can be closed.

**Comment by adg** [comment]
Yep, @campoy added a Kill button a while ago.
