### ISSUE TITLE
reflect: PtrTo of struct with embedded field does not implement interfaces correctly

### ISSUE THREAD

**Issue by bryanturley** [golang/go#8427]
<pre>This one is hard to explain, luckily it is very simply reproduced.
Keep your attention on output regarding the anonymous struct F {} inside of struct Z {}

If you uncomment the /* */ area at the end.  The reflection answers before it change.
I would say they are only correct when that section is uncommented.
This program should never print &quot;... == false&quot;.

<a href="http://play.golang.org/p/GDUfhs8g2H">http://play.golang.org/p/GDUfhs8g2H</a>

Discovered originally using go1.3 linux amd64.</pre>

**Comment by rsc** [comment]
This is trivial, will fix for Go 1.5.
