### ISSUE TITLE
net: Happ{y,yish,ier} Eyeballs should give the preferred family a head start

### ISSUE THREAD

**Issue by pmarks-net** [golang/go#8455]
<pre>Forked from <a href="https://golang.org/issue/8453">issue #8453</a>.

The Happy Eyeballs implementation used by net.Dialer{DualStack: true} sends IPv4 and
IPv6 SYNs simultaneously, and the resulting address family is unpredictable.

This is harmful for two reasons:
- It increases server load in the common case, by always sending two SYNs.
- Dual-stack clients cannot reliably use IPv6 to route around NATs.  The primary
incentive for a network operator to deploy IPv6 is to reduce NAT load (and therefore
save money), but this sort of client behavior invalidates that incentive.

<a href="http://tools.ietf.org/html/rfc6555#section-4.1">http://tools.ietf.org/html/rfc6555#section-4.1</a> says:

&quot;&quot;&quot;
   Thus, to avoid harming IPv4-only hosts, implementations MUST prefer
   the first IP address family returned by the host's address preference
   policy, unless implementing a stateful algorithm described in
   Section 4.2.  This usually means giving preference to IPv6 over IPv4,
   although that preference can be overridden by user configuration or
   by network configuration [ADDR-SELECT].  If the host's policy is
   unknown or not attainable, implementations MUST prefer IPv6 over
   IPv4.
&quot;&quot;&quot;

When the DualStack flag is true, clients should follow this algorithm:

  Call getaddrinfo()
  Note the family of address[0], and start a routine which connects to each address of that family, in order.
  After ~300ms, start a second routine which connects to addresses *not* of that family, in order.
  Meanwhile:
  - If the first routine terminates before 300ms, start the second routine immediately.
  - When one routine succeeds, cancel the other.

There's room for flexibility in the details, but the important point is that under
normal network conditions, a client should send exactly one SYN to the first address
reported by getaddrinfo().</pre>

**Comment by mikioh** [comment]
@pmarks-net is working on this issue.
