### ISSUE TITLE
encoding/json: UnmarshalText confuses json.Unmarshal

### ISSUE THREAD

**Issue by kortschak** [golang/go#8462]
<pre>What does 'go version' print?
go version go1.3 linux/amd64
go version devel +f7e7857afd88 Fri Aug 01 16:45:33 2014 -0700 linux/amd64

What steps reproduce the problem?
If possible, include a link to a program on play.golang.org.

1. Run the program at <a href="http://play.golang.org/p/izafDRNZFW">http://play.golang.org/p/izafDRNZFW</a>
2. Run the program at <a href="http://play.golang.org/p/Un74tdY10R">http://play.golang.org/p/Un74tdY10R</a>

What happened?
The first program prints a reasonably unhelpful error &quot;error: JSON decoder out of
sync - data changing underfoot?&quot; and the second program prints the expected result.

What should have happened instead?
Both programs should behave as the second, a more informative error should be printed,
or the json documentation should warn about use of encoding.TextUnmarshaler.</pre>

**Comment by rsc** [comment]
Dup of #9650.
