### ISSUE TITLE
misc/makerelease: move to sub-repository

### ISSUE THREAD

**Issue by adg** [golang/go#8472]
<pre>This issue is a proposal that we create a new &quot;go.release&quot; sub-repo and put
makerelease and associated files there.

Rationale:

The makerelease tool reads in various files from misc/makerelease during execution.
Because the makerelease tool is inside the Go repository it is entwined with our release
process. Changes are usually made to makerelease around release time, and it's not
always clear whether the changes should be made to the main or release branches. This
ambiguity would be resolved entirely by keeping the makerelease tool entirely separate
to the go repository.

Any objections?</pre>

**Comment by rsc** [comment]
Sure, sounds like the build subrepo would work.

**Comment by bradfitz** [comment]
We should just delete it, since we're moving to using x/build/cmd/release anyway.

**Comment by adg** [comment]
It will be deleted when the `tools/cmd/release` tool is done.
