### ISSUE TITLE
cmd/dist: does not say there are flags you can pass to bootstrap command

### ISSUE THREAD

**Issue by tfarina** [golang/go#8506]
<pre>I was trying to reach the breakpoint in bgrunv without success, until I passed -a to
dist bootstrap.

Then I hit the breakpoint.

Breakpoint 1, install (dir=&lt;optimized out&gt;) at cmd/dist/build.c:1062
1062            bgrunv(bstr(&amp;path), CheckExit, &amp;compile);

Looking at cmd/dist/build.c:cmdbootstrap I see you can pass either -a, -s or -v.</pre>

**Comment by ALTree** [comment]
This looks fixed, the two (currently valid) flags are documented:

```
$ go tool dist bootstrap -h
usage: go tool dist bootstrap [options]
  -a	rebuild all
  -v	verbosity
```

Closing.
