### ISSUE TITLE
net: document and check LookupCNAME on non-CNAME hosts

### ISSUE THREAD

**Issue by egonelbre** [golang/go#8516]
<pre>LookupCNAME does not have clear behavior what it does when the DNS query succeeds and
there isn't a CNAME record.

Comment says that:

// LookupCNAME returns the canonical DNS host for the given name.
// Callers that do not care about the canonical name can call
// LookupHost or LookupIP directly; both take care of resolving
// the canonical name as part of the lookup.

So, just to clarify does it need to do:

1. return &quot;&quot;, nil
2. return &quot;&quot;, errors.New(&quot;CNAME not found&quot;)
3. return fqdn(name), nil

Given the comment, the approach 3. seems to be the correct one, because CNAME declares
alias names, and the canonical name for X, if there are no CNAME records, is X itself.
Of course some code could rely on returning &quot;&quot; and error.

Of course the code doesn't seem to be doing that - In Windows it's doing 2. in Linux 3.

Also, when researching this I noticed in dnsclient_unix.go at line 432, 

&gt; func goLookupCNAME(name string) (cname string, err error) {
&gt;    _, rr, err := lookup(name, dnsTypeCNAME)
&gt;    if err != nil {
&gt;        return
&gt;    }
&gt;    cname = rr[0].(*dnsRR_CNAME).Cname
&gt;    return
&gt; }

It looks like it might blow up when len(rr) == 0.</pre>

**Comment by rsc** [comment]
Updating the docs seems fine.

**Comment by rsc** [comment]
I am not sure what to say here. In general we can't mandate the behavior for CNAME pointing to CNAME. That will depend on the host resolver, as many things do. We may be better off not saying anything.

The question of what LookupCNAME does for a host without a CNAME is more interesting. It should be defined (I suspect it should return the original name, but I am not sure that's tenable) and be made consistent across systems.

**Comment by rhansen** [comment]
For POSIX-ish systems (Linux, BSD, OS X), what about using the value returned by `getaddrinfo()` with the `AI_CANONNAME` flag set?

**Comment by bradfitz** [comment]
@rhansen, the default resolver in Go is pure Go, and not using heavyweight libc (which requires threads, wasting valuable RAM seconds waiting for responses).

Also, there's Windows and Plan 9 and Solaris, etc. The net package is supposed to be a portable interface. We should define the semantics in terms of something we can reasonably implement on all OSes.

**Comment by rhansen** [comment]
I don't know about Plan 9, but Windows and Solaris both have `getaddrinfo()`.  I suspect all major operating systems updated after [RFC 3493](https://tools.ietf.org/html/rfc3493) have `getaddrinfo()`.

Unless the semantics of net.LookupCNAME is limited to "resolve a CNAME DNS resource record", a pure Go implementation seems a bit unwise because hostname resolution involves OS-specific implementation details like `/etc/resolv.conf`, `/etc/hosts`, NSS, etc.

**Comment by bradfitz** [comment]
We've had a pure Go implementation for the common case (parsing nsswitch.conf, resolv.conf, hosts, etc) for a number of releases now.

The point remains: we don't define Go interfaces in terms of C interfaces. We document what they should do in English, and implement them. Sometimes that implementation might involve using existing system libraries, or not. But that's a detail.

**Comment by ianlancetaylor** [comment]
I think this was fixed by https://golang.org/cl/34650, written to address #18172.

@mdempsky Do you agree?

**Comment by ianlancetaylor** [comment]
Closing because I think this is fixed.  Please comment if you disagree.
