### ISSUE TITLE
websites: downloads have annoying redirect

### ISSUE THREAD

**Issue by bradfitz** [golang/go#8519]
<pre>The Go downloads have an annoying redirect which bites me whenever I try to download a
file remotely:

mac:go bradfitz$ time curl -s -O <a href="https://golang.org/dl/go1.3.darwin-386-osx10.8.tar.gz">https://golang.org/dl/go1.3.darwin-386-osx10.8.tar.gz</a>

real	0m0.333s
user	0m0.049s
sys	0m0.010s

mac:go bradfitz$ ls -l go1.3.darwin-386-osx10.8.tar.gz
-rw-r--r--  1 bradfitz  5000  92 Aug 12 10:30 go1.3.darwin-386-osx10.8.tar.gz

mac:go bradfitz$ cat go1.3.darwin-386-osx10.8.tar.gz
&lt;a
href=&quot;<a href="https://storage.googleapis.com/golang/go1.3.darwin-386-osx10.8.tar.gz&quot">https://storage.googleapis.com/golang/go1.3.darwin-386-osx10.8.tar.gz&quot</a>;&gt;Found&lt;/a&gt;.

Can we not do that? Or use a different redirect status code perhaps?</pre>

**Comment by andrewaustin** [comment]
All the links on https://golang.org/dl/ directly link to storage.googlkeapis.com, so I believe this can be closed. (It looks like the 302 still exists for compatibility reasons, although it doesn't seem to be used?)

**Comment by adg** [comment]
@andrewaustin thanks for going through all of these!
