### ISSUE TITLE
cmd/compile: failure to optimize away temporary variable

### ISSUE THREAD

**Issue by josharian** [golang/go#8525]
<pre>I'd expect these functions to compile identically:

func f() int {
	a := 2
	return a
}

func g() int {
	return 2
}

They do not (6g):

&quot;&quot;.f t=1 size=32 value=0 args=0x8 locals=0x8
  0x0000 00000 (d.go:3) TEXT &quot;&quot;.f+0(SB),4,$8-8
  0x0000 00000 (d.go:3) SUBQ $8,SP
  0x0004 00004 (d.go:3) FUNCDATA $2,gclocals·a7a3692b8e27e823add69ec4239ba55f+0(SB)
  0x0004 00004 (d.go:3) FUNCDATA $3,gclocals·3280bececceccd33cb74587feedb1f9f+0(SB)
  0x0004 00004 (d.go:4) MOVQ $2,AX
  0x000b 00011 (d.go:5) MOVQ AX,&quot;&quot;.~r0+16(FP)
  0x0010 00016 (d.go:5) ADDQ $8,SP
  0x0014 00020 (d.go:5) RET ,

&quot;&quot;.g t=1 size=16 value=0 args=0x8 locals=0x0
  0x0000 00000 (d.go:8) TEXT &quot;&quot;.g+0(SB),4,$0-8
  0x0000 00000 (d.go:8) NOP ,
  0x0000 00000 (d.go:8) NOP ,
  0x0000 00000 (d.go:8) FUNCDATA $2,gclocals·a7a3692b8e27e823add69ec4239ba55f+0(SB)
  0x0000 00000 (d.go:8) FUNCDATA $3,gclocals·3280bececceccd33cb74587feedb1f9f+0(SB)
  0x0000 00000 (d.go:9) MOVQ $2,&quot;&quot;.~r0+8(FP)
  0x0009 00009 (d.go:9) RET ,

There are two inefficiencies in f: A useless stack variable and two MOVQs where one
suffices.

CL 126160043 will address the useless stack variable. The MOVQs should presumably be
handled with a peephole optimization that copies the constant when it has only one
subsequent use.</pre>

**Comment by ferluht** [comment]
Doesn't reproduce with revision b9feb91

**Comment by randall77** [comment]
Yes, SSA fixes this.  Closing.
