### ISSUE TITLE
encoding/xml: failure to handle conflicting tags in different namespaces

### ISSUE THREAD

**Issue by jbardin** [golang/go#8535]
<pre>What does 'go version' print?

go1.3.1

What steps reproduce the problem?

Try to decode document with the same tag in multiple namespaces
&lt;example&gt;
    &lt;title&gt;Example&lt;/title&gt;
    &lt;link&gt;<a href="http://example.com/default&lt">http://example.com/default&lt</a>;/link&gt;
    &lt;ns:link xmlns:ns=&quot;<a href="http://www.w3.org/2005/Atom&quot">http://www.w3.org/2005/Atom&quot</a>;&gt;<a href="http://example.com/ns&lt">http://example.com/ns&lt</a>;/ns:link&gt;
&lt;/example&gt;`

<a href="http://play.golang.org/p/FT56UXolGO">http://play.golang.org/p/FT56UXolGO</a>

What happened?
main.Example field &quot;Link&quot; with tag &quot;link&quot; conflicts with field
&quot;AtomLink&quot; with tag &quot;<a href="http://www.w3.org/2005/Atom">http://www.w3.org/2005/Atom</a> link&quot;

What should have happened instead?

It should be possible to decode both tags in this document.

Also, if the name-spaced tag isn't provided, the second &quot;link&quot; element shadows
the first though it's in another namespace.</pre>

**Comment by klauern** [comment]
I just ran into this issue working with a legacy SOAP API that had a lot of namespaces in the fields.

**Comment by Matt3o12** [comment]
I am also having this issue (funnily enough with RSS readers as well). Is there a workaround, yet or do we have to wait for Go 10 (ie. #14407)

**Comment by Matt3o12** [comment]
I found a workaround by creating a custom string-type with a custom unmarshal function. If anyone is interested, here it is:


```
type NonNamespaceString string

func (s *NonNamespaceString) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	if start.Name.Space != "" {
		// We do not want a namespace, so we need to consume it
		d.Skip()
		return nil
	} else {
		str := ""
		d.DecodeElement(&str, &start)
		*s = NonNamespaceString(str)
	}

	return nil
}
```

I also create a [gist](https://gist.github.com/Matt3o12/add719e5c4a057d6aec176ef90595e96) with a unit test, if you are interested.

It seems to work and can almost be used as a drop-in replacement for any string. You just need to cast it back to a string if you want to use it.

**Comment by iWdGo** [comment]
Comparing namespaces of fields was missing and detecting false conflicts. A fix is submitted.
