### ISSUE TITLE
cmd/compile: typecheck.c illegal member access to n->type member when n->type is nil

### ISSUE THREAD

**Issue by davecheney** [golang/go#8538]
<pre>What steps will reproduce the problem?

-fsanitize=undefined reports

/home/dfc/go/src/cmd/gc/typecheck.c:3326:15: runtime error: member access within null
pointer of type 'Type' (aka 'struct Type')
/home/dfc/go/src/cmd/gc/typecheck.c:3326:15: runtime error: load of null pointer of type
'uchar' (aka 'unsigned char')

typecheckdeftype will set n-&gt;type = T if an error occurs, but line 3326 tries to
access members of n-&gt;type unconditionally.

This only happens when compilation is a failure, but should probably be fixed.

What is the expected output? What do you see instead?

Please use labels and text to provide additional information.</pre>

**Comment by ALTree** [comment]
That C code in the compiler was deleted a long time ago, so I'm closing this.
