### ISSUE TITLE
cmd/6a: setcc encoded incorrectly when rex prefix required

### ISSUE THREAD

**Issue by josharian** [golang/go#8545]
<pre>$ cat x.s
TEXT ·TestSetCC(SB),$0
	SETEQ ,BP
	SETEQ ,CH

$ go tool 6a -S x.s
&quot;&quot;.TestSetCC t=1 size=16 value=0 args=0xffffffff80000000 locals=0
	000000 00000 (x.s:1)	TEXT	&quot;&quot;.TestSetCC+0(SB),4,$0--2147483648
	000000 00000 (x.s:2)	SETEQ	,BP
	0x0003 00003 (x.s:3)	SETEQ	,CH
	000000 0f 94 c5 0f 94 c5                                ......

Both instructions are encoded as 0f 94 c5. SETEQ ,BP requires a REX prefix; the correct
encoding is 40 0f 94 c5.

I have not checked whether 8a has a similar problem.

This arose while working on <a href="https://golang.org/issue/5729">issue #5729</a>.</pre>

**Comment by minux** [comment]
Interestingly, cmd/8a encode SETE BP as:
87 dd 0f 94 c3 87 dd

i.e. it synthesize sete bp as:
	xchgl	%ebx, %ebp
	sete	%bl
	xchgl	%ebx, %ebp

so it seems cmd/8a is not affected by this (and it's pretty
clever in encoding the invalid instruction.)
