### ISSUE TITLE
cmd/compile: gc inconsistent about reporting "unused variable" errors

### ISSUE THREAD

**Issue by adonovan** [golang/go#8560]
<pre>For this program:
  <a href="http://play.golang.org/p/BzMO7Vt3uy">http://play.golang.org/p/BzMO7Vt3uy</a>
  switch x := interface{}(nil).(type) {}
go/types reports an error but gc does not.

I realize the spec does not say what should happen here, but the fact of this
implementation-specific behaviour is that we have two dialects of Go whose tools reject
each others' programs.

We should probably make the tools consistent one way or another.
I would also argue in favour of removing this hole in the spec.</pre>

**Comment by rsc** [comment]
This is in milestone Unplanned. By my assignment should I infer you are requesting we reprioritize it? Normally Unplanned things have no assignee.

**Comment by alandonovan** [comment]
Yes, that's what I meant.  (Sorry if that was unclear or seemed passive-aggressive.)

**Comment by rsc** [comment]
OK, reprioritized to Go 1.7, but that's still no guarantee.

**Comment by odeke-em** [comment]
@adg your report in https://github.com/golang/go/issues/8560#issuecomment-66097949 was a bug that was already reported at https://github.com/golang/go/issues/3059, in case you are interested in tracking that case.

**Comment by jim-minter** [comment]
Out of interest, are there any known workarounds for the gorename issue #14596 (short of not using closures in this way across a codebase) that can be used to enable use of gorename in codebases such as that before this issue is resolved?

**Comment by griesemer** [comment]
The Go 1.18 compiler correctly reports errors in these cases.
Per #49214 we will accept the correct behavior for 1.18 and document it in the release notes.
