### ISSUE TITLE
proposal: spec: disallow `type P *T` if T has methods

### ISSUE THREAD

**Issue by griesemer** [golang/go#8590]
<pre>We already disallow named pointer types as types of receivers or anonymous fields. We
may want to consider outlawing them more generally since they have some strange
properties because methods do not automatically indirect pointers, while fields do.

Here's an example: <a href="http://play.golang.org/p/BsThM7_Jcd">http://play.golang.org/p/BsThM7_Jcd</a>

When we see p.m we don't know if p should be automatically indirected unless we know
that m is a field. Since we (a compiler/typechecker) cannot know this w/o looking it up
first, for fields it is necessary to do a 2nd lookup if the first one (w/o indirection)
finds nothing. If the 2nd lookup results in finding a method (rather than a field), it
must be discarded.</pre>

**Comment by extemporalgenome** [comment]
Are there legitimate use cases for named pointer types? I have not seen them in the wild. Alternatively, perhaps we could disallow automatic dereference of fields "through" a named type like the above `P` -- this would make them unwieldy enough that people will avoid wanting to use them, for the same reason that `defer recover()` does not work (as it'd make panics too convenient).

**Comment by griesemer** [comment]
There's of course `type P *P` which we perhaps don't want to lose...

**Comment by griesemer** [comment]
I'm going to withdraw this proposal for now. There's a lot of subtle interplay between method sets, pointer types, receiver base types, and field and method lookups. This will need a more thorough proposal if any.
