### ISSUE TITLE
proposal: spec: require explicit labels for break, continue

### ISSUE THREAD

**Issue by griesemer** [golang/go#8591]
<pre>It's a not uncommon mistake to use a unlabeled break statement inside a switch statement
with the intention to break a surrounding for loop:

for some_condition {
   switch tag {
   case foo:
      ...
      break  // intent is to break out of for loop
   ...
}

The compiler won't complain but the bug is non-obvious and often not easy to spot.

Break (and also continue) should require use of explicit labels. This will make the code
more readable and remove a not uncommon source of bugs. The benefit outweighs the minor
inconvenience; also this cases don't occur too often.

A slightly more complicated (but more convenient) approach would be to require the label
only if the target statement is ambiguous (i.e., a switch/for statement containing a
break is not nested within another statement that could be targeted by the break; and
analogous for continue).</pre>

**Comment by pciet** [comment]
This happened to me recently but I don't like writing OUTER: everywhere. Maybe a breakall would be better? I use break enough to not want to have to use a label, although the for + switch/select break is definitely a source of mistakes for me.

**Comment by griesemer** [comment]
I'm going to close this one. It's unlikely to find enough support and it's tedious and verbose in most programs.

**Comment by griesemer** [comment]
Just for the record, if this issue were to find interest after all, instead of labels one could follow the `break` keyword with the keyword of the statement to be broken; e.g. `break` `for` to break the innermost enclosing `for` statement, etc. The 2nd keyword could be optional.
