### ISSUE TITLE
internal/race: add the package

### ISSUE THREAD

**Issue by dvyukov** [golang/go#8593]
<pre>We have a bunch of race-related copy-paste in sync, sync/atomic, net, syscall, runtime.
Moreover, any race-related functionality requires 2 files -- race.go and norace.go -- as
race functions are not provided by runtime in non-race build.

We can create internal/race package and move things like IsEnabled, Acquire, Release to
it. It will remove the copy-paste and all the additional files from other packages.

Additionally then we will be able to easily exclude or tune tests in race mode using
race.IsEnabled. E.g. now we have the cpuprof test that constantly flakes on
freebsd-amd64-race.</pre>

**Comment by rsc** [comment]
Too late for Go 1.5.
