### ISSUE TITLE
website: godoc page broken at tip

### ISSUE THREAD

**Issue by bcmills** [golang/go#8595]
<pre>Loading <a href="http://tip.golang.org/pkg/os/exec/">http://tip.golang.org/pkg/os/exec/</a> gives a failure message instead of displaying
the package contents:

/src/pkg/os/exec/exec.go:361:6: expected operand, found 'range' (and 3 more errors)

I'm not sure whether this is a bug in exec at tip or a symptom of a godoc server in need
of update, but it's been broken for at least a couple of days.</pre>

**Comment by andrewaustin** [comment]
This issue has been fixed and can be closed.

http://tip.golang.org/pkg/os/exec/
