### ISSUE TITLE
cmd/vet: reject x < 0 if x is unsigned

### ISSUE THREAD

**Issue by davecheney** [golang/go#8601]
<pre>What steps will reproduce the problem?

In the following code fragment

func f(x uint) int {
    if x &lt; 0 {
        return 9000
    }
    return -9000
}

func main() {
    fmt.Println(f(10))
}

The x &lt; 0 branch is unreachable because x is unsigned. 

What is the expected output? What do you see instead?

Expected, the compiler should refuse to compile this statement.

Actual, the compiler happily accepts it and probably eliminates the branch as
unreachable.

Please use labels and text to provide additional information.

See discussion: <a href="https://groups.google.com/d/topic/golang-dev/k3TQaEeGwyY/discussion">https://groups.google.com/d/topic/golang-dev/k3TQaEeGwyY/discussion</a></pre>

**Comment by rsc** [comment]
I have seen errors like this from vet in the past. It seems OK to add something like this to vet assuming it passes the 3 rules in vet/README. It's not a backwards compatible language change though.

**Comment by dhananjay92** [comment]
[golang.org/cl/34715](http://golang.org/cl/34715) adds this to vet.

**Comment by robpike** [comment]
You need to establish the three rules in the README, of which two seem clear (correctness and precision). Only frequency remains to be demonstrated.

**Comment by dhananjay92** [comment]
> I can see cases where due to a constant value being different on different architectures that this would be fine.

Does this mean that the `x < 0` branch (where x is unsigned), may not be dead/unreachable depending on a constant's representation in some architecture?

**Comment by robpike** [comment]
Yes. For example, consider the case where 0 is not a numeral but an architecture-dependent constant.
