### ISSUE TITLE
cmd/compile: confusing and inconsistent error messages for syntactically incorrect method expressions

### ISSUE THREAD

**Issue by griesemer** [golang/go#8605]
<pre>The following program:

<a href="http://play.golang.org/p/2qX3CIh_Cx">http://play.golang.org/p/2qX3CIh_Cx</a>

compiles with a confusing error:

main.main: call to external function go.(*struct { main.T }).main.m
main.main: undefined: go.(*struct { main.T }).main.m

Per the spec ( <a href="http://tip.golang.org/ref/spec#Method_expressions">http://tip.golang.org/ref/spec#Method_expressions</a> ), method expressions
must have a (possibly parenthesized) named (or pointer to named) type. The error message
is (at the very least) confusing.

For reference, gccgo produces for this case:

x.go:8:14: error: method expression requires named type or pointer to named type
  (*struct{T}).m(nil)

That said, the following (equally syntactically incorrect) program compiles and runs w/o
problems using gc:

<a href="http://play.golang.org/p/qpAtL6sEVW">http://play.golang.org/p/qpAtL6sEVW</a>

For reference, gccgo produces for this case:

x.go:8:15: error: method expression requires named type or pointer to named type
  (struct{ T }).m(struct{ T }{42})

go/types (arguably incorrectly) accepts both programs w/o complaints.

I see 2 possible solutions:

1) Let's fix gc and go/types to make it spec compliant.

2) Relax the spec and adjust gccgo and the one case in cmd/gc.

I am in favor of 2) for the following reasons:

- A method expression T.m is essentially a syntactic construct: It can always be
rewritten to m' where m is roughly defined as:

func m'(x T, args m_params) {
   x.m(args)
}

If m exists for T, m' can always be written independent of the syntactic form of T, for
instance:

<a href="http://play.golang.org/p/kflAOxp2Gr">http://play.golang.org/p/kflAOxp2Gr</a>

for our first example.

- It already appears to work in 1/2 of the cases for cmd/gc.
- It's more general and simplifies the spec.
- It's backward compatible.
- It doesn't require a 2nd syntax check (of technically a selector expression) after the
type checker has determined that x in x.m is a type (rather than a value). This ought to
simplify the implementation slightly.</pre>

**Comment by griesemer** [comment]
See also #9060 .

**Comment by odeke-em** [comment]
As of Go1.15, the program that @griesemer posted up in https://github.com/golang/go/issues/8605#issue-51288436 compiles but fails at runtime with 
![0B698FEE-4459-4DED-944F-F55E038A8DFD](https://user-images.githubusercontent.com/4898263/83967823-cc47fb00-a879-11ea-9994-1c06acac9148.png)
which seems like updated spec compliance, and https://play.golang.org/p/ER4VVfzCbaZ passes.

I can only build as far as Go1.7 on my MacBook Pro but it seems that the form was already accepted before even Go1.7 as acknowledged at https://github.com/golang/go/issues/9060#issuecomment-220165301 for the original bug no longer produces the confusing error. @griesemer shall we perhaps close this issue, or how do you suggest moving forward? Thank you.

**Comment by mdempsky** [comment]
I think this is fixed. The spec has been relaxed to allow arbitrary types in method expressions; and on dev.regabi, the Go compiler correctly prints method expressions in error messages. For example, `struct{ T }.m(nil)` is reported as `invalid method expression struct { T }.m (needs pointer receiver: (*struct { T }).m)`.
