### ISSUE TITLE
x/sys/unix: Mkfifo is missing on Solaris

### ISSUE THREAD

**Issue by tgulacsi** [golang/go#8609]
<pre>What does 'go version' print?
go version go1.3.1 solaris/amd64

What steps reproduce the problem?

1. call syscall.Mkfifo(&quot;/tmp/a&quot;, 0640)

What happened?
undefined: syscall.Mkfifo

What should have happened instead?
syscall should provide the same Mkfifo implementation, as on Linux:
syscall.Mknod(path, mode|syscall.S_IFIFO, 0)

Please provide any additional information below.
On Solaris, mkfifo just calls mknod: <a href="http://www.unix.com/man-page/opensolaris/3c/mkfifo/">http://www.unix.com/man-page/opensolaris/3c/mkfifo/</a></pre>

**Comment by binarycrusader** [comment]
Actually, Solaris is missing a number of functions offered on Linux and others:

 * Mount
 * Getwd
 * Futimes
 * Acct
 * Creat
 * Dup2
 * Mkfifo
 * Pause
 * Times
 * Ustat
 * Utime

I'll submit a CL to add the missing functions where appropriate.

**Comment by binarycrusader** [comment]
Fixed in this CL:

https://golang.org/cl/14643
