### ISSUE TITLE
cmd/compile: _ = 1/x optimized away even though 1/x may panic

### ISSUE THREAD

**Issue by bradfitz** [golang/go#8613]
<pre>Does the spec specify whether an expression assigned to _ needs to be evaluated and thus
might panic?

See: <a href="http://play.golang.org/p/azEfUMu2Vg">http://play.golang.org/p/azEfUMu2Vg</a>

This doesn't panic, even though I would expect it to:

package main

var x int

func main() {
	defer func() {
		if e := recover(); e != nil {
			println(&quot;Panic&quot;)
		}
	}()
	v := 1
	_ = 5 / (1 - v)
	// x = 5 / (1 - v)   // This actually panics.
	println(&quot;No panic&quot;)
}</pre>

**Comment by bradfitz** [comment]
Does anybody know whether this has been fixed?

/cc @josharian @randall77 @mdempsky

**Comment by randall77** [comment]
This is fixed in the SSA branch.  It is not fixed for the legacy compiler (aka all the other architectures besides amd64).

**Comment by griesemer** [comment]
Doesn't look like it's fixed:
```
package main

func main() {
	f(0)
}

func f(x int) {
	_ = 1 / x
}
```
runs w/o complaints.

**Comment by bradfitz** [comment]
Cool. You know where the tests for it are?

**Comment by randall77** [comment]
I don't think there are any. It was fixed by happenstance, not deliberately.  We could add a +build amd64 test.

**Comment by cespare** [comment]
@griesemer that program does panic for me at tip.

**Comment by bradfitz** [comment]
@griesmer, yeah... I see it correctly failing at tip:

```
bradfitz@laptop ~$ GOROOT=$HOME/go1.6 go run div.go
bradfitz@laptop ~$ GOROOT=$HOME/go go run div.go
panic: runtime error: integer divide by zero

goroutine 1 [running]:
panic(0x4b660, 0xc82000a0c0)
        /Users/bradfitz/go/src/runtime/panic.go:500 +0x18e
main.main()
        /Users/bradfitz/div.go:4 +0x14
exit status 2
```

**Comment by bradfitz** [comment]
I sent https://go-review.googlesource.com/21325

**Comment by griesemer** [comment]
My apologies. I thought I had an updated build but obviously I didn't (at home).
