### ISSUE TITLE
compress/bzip2: add support for concatenated bzip2 files

### ISSUE THREAD

**Issue by krasin** [golang/go#8629]
<pre>This is not a bug, it's a feature request.

Consider you have concatenated two valid bzip2 files. The resulted file (like the
attached one) will be correctly decompressed by the /bin/bunzip2, but compress/bzip2
will only decompress the first half.</pre>

Attachments:

1. <a href="https://storage.googleapis.com/go-attachment/8629/0/repro-concatenated.bz2">repro-concatenated.bz2</a> (201690 bytes)

**Comment by dsnet** [comment]
Using ```go1.5.1```

This is supported and can be closed. This was added in https://github.com/golang/go/commit/8a0779f9b91e3392d90dab9217be7fdbee08f523.

I verified that Go's version and the C bzip2 program output the same thing.
