### ISSUE TITLE
runtime/cgo: scheduler blocked with goroutines

### ISSUE THREAD

**Issue by DAddYE** [golang/go#8636]
<pre>Hi there,

I have a quite big app, while my code works and is very fast in production, when I ran
my benchmark suite results 1000x worse. So I'm not sure if I'm doing something wrong or
is a know problem.

There is a thread on google groups:
<a href="https://groups.google.com/forum/#">https://groups.google.com/forum/#</a>!topic/golang-nuts/9RqGvk-b3Ow

Tested on:

go version go1.3.1 darwin/amd64
go version go1.3.1 linux/amd64

Here a simplified version of the code:

func main() {
        runtime.GOMAXPROCS(0)

        // prepare communication protocol
        urls := make(chan string)
        wg := new(sync.WaitGroup)

        // fire a bunch of workers
        for i := 0; i &lt; env.MaxProcs; i++ {
                wg.Add(1)
                go func(i int) {
                        fmt.Printf(&quot;starting worker %d...\n&quot;, i)
                        defer wg.Done()
                        for url := range urls {
                                C.resize_image(url) // takes around 30ms
                        }
                }(i)
        }

        // db connection (native go)....

        var url string
        for i := 0; iter.Scan(&amp;url) &amp;&amp; i &lt; 1e4; i++ { // Scan takes around 8ms
                // with a time.Sleep(10 * time.Millisecond) results are 1000x better!
                urls &lt;- url
        }
        err = iter.Close()

        // wait
        close(urls)
        wg.Wait()
}

When I run pprof (darwin):

3512  76.4%  76.4%     3512  76.4% runtime.mach_semaphore_wait
     968  21.1%  97.5%      968  21.1% runtime.cgocall
     107   2.3%  99.8%      107   2.3% runtime.kevent
       3   0.1%  99.9%        3   0.1% runtime.usleep
       2   0.0%  99.9%        2   0.0% syscall.Syscall
       1   0.0%  99.9%        1   0.0% math/rand.Float64
       1   0.0% 100.0%        1   0.0% runtime.MHeap_LookupMaybe
       1   0.0% 100.0%        1   0.0% runtime.MSpan_Sweep
       1   0.0% 100.0%        1   0.0% runtime.memclr
       0   0.0% 100.0%        6   0.1% GC
       0   0.0% 100.0%     3618  78.7% System
       0   0.0% 100.0%      968  21.1% github.com/daddye/vips.Resize
       0   0.0% 100.0%       28   0.6% github.com/daddye/vips._Cfunc_im_close
       0   0.0% 100.0%      278   6.0% github.com/daddye/vips._Cfunc_vips_affine_interpolator
       0   0.0% 100.0%       18   0.4% github.com/daddye/vips._Cfunc_vips_colourspace_0
       0   0.0% 100.0%       43   0.9% github.com/daddye/vips._Cfunc_vips_copy_0
       0   0.0% 100.0%      258   5.6% github.com/daddye/vips._Cfunc_vips_embed_extend
       0   0.0% 100.0%       35   0.8% github.com/daddye/vips._Cfunc_vips_image_new
       0   0.0% 100.0%       16   0.3% github.com/daddye/vips._Cfunc_vips_jpegload_buffer_seq
       0   0.0% 100.0%       15   0.3% github.com/daddye/vips._Cfunc_vips_jpegload_buffer_shrink

When I run pprof (linux):

Total: 6250 samples
    6188  99.0%  99.0%     6191  99.1% runtime.cgocall
      21   0.3%  99.3%       21   0.3% runtime.usleep
       7   0.1%  99.5%        7   0.1% retake
       7   0.1%  99.6%        7   0.1% runtime.rtsigprocmask
       4   0.1%  99.6%        4   0.1% syscall.Syscall
       3   0.0%  99.7%        3   0.0% runtime.epollwait
       3   0.0%  99.7%        3   0.0% runtime.futex
       2   0.0%  99.8%        2   0.0% ExternalCode
       2   0.0%  99.8%        2   0.0% runtime.memclr
       1   0.0%  99.8%        2   0.0% exitsyscallfast
       1   0.0%  99.8%     6192  99.1% github.com/daddye/vips.Resize
       1   0.0%  99.8%        1   0.0% github.com/gocql/gocql.(*frame).readBytes
       1   0.0%  99.9%        1   0.0% runqgrab
       1   0.0%  99.9%        1   0.0% runtime.atomicload64
       1   0.0%  99.9%        1   0.0% runtime.cas
       1   0.0%  99.9%        1   0.0% runtime.entersyscall
       1   0.0%  99.9%        1   0.0% runtime.fastrand1
       1   0.0%  99.9%        1   0.0% runtime.noteclear
       1   0.0% 100.0%        1   0.0% runtime.purgecachedstats
       1   0.0% 100.0%        1   0.0% runtime.unlock

Things I tried:

1. Use another CGO binding: image magick - Same results - Both libraries are thread safe.
2. Use runtime.Gosched() (tried to put it in different places) - Same
3. Use runtime.LockOSThread() (tried to put it in different places) - Same
4. Add a time.Sleep(10*time.Milliseconds) - the commented line
&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt; I get back good results!
5. Test on linux (ubuntu lts 12) - Same and pretty much same pprof
6. Remove CGO and use a native call - Very fast. 
7. Avoid channels just `go func()` - Very fast!
8. Set GOMAXPROCS 1 - Very fast!
9. Remove the db connection just use a slice - Same
10. Use buffered channels - Worse

To explain more about point 4. it seems that if we add few milliseconds between each
request

        for i := 0; iter.Scan(&amp;url) &amp;&amp; i &lt; 1e4; i++ { // Scan takes around 8ms
                time.Sleep(10 * time.Millisecond)
                urls &lt;- url
        }

 the scheduler can handle everything better, that's why in production I wasn't able to see the issue, so here a benchmark with timings:

Without Sleep:

resize speed mean: 327.630885ms, min: 100.150452ms, max: 462.495835ms, 99%: 429.954171ms
Total: 6250 samples
    6188  99.0%  99.0%     6191  99.1% runtime.cgocall
      21   0.3%  99.3%       21   0.3% runtime.usleep
       7   0.1%  99.5%        7   0.1% retake
       7   0.1%  99.6%        7   0.1% runtime.rtsigprocmask
       4   0.1%  99.6%        4   0.1% syscall.Syscall
       3   0.0%  99.7%        3   0.0% runtime.epollwait
       3   0.0%  99.7%        3   0.0% runtime.futex
       2   0.0%  99.8%        2   0.0% ExternalCode
       2   0.0%  99.8%        2   0.0% runtime.memclr
       1   0.0%  99.8%        2   0.0% exitsyscallfast
       1   0.0%  99.8%     6192  99.1% github.com/daddye/vips.Resize
       1   0.0%  99.8%        1   0.0% github.com/gocql/gocql.(*frame).readBytes
       1   0.0%  99.9%        1   0.0% runqgrab
       1   0.0%  99.9%        1   0.0% runtime.atomicload64
       1   0.0%  99.9%        1   0.0% runtime.cas
       1   0.0%  99.9%        1   0.0% runtime.entersyscall
       1   0.0%  99.9%        1   0.0% runtime.fastrand1
       1   0.0%  99.9%        1   0.0% runtime.noteclear
       1   0.0% 100.0%        1   0.0% runtime.purgecachedstats
       1   0.0% 100.0%        1   0.0% runtime.unlock

With a Sleep of 10ms:

resize speed mean: 28.551381ms, min: 4.666236ms, max: 61.589934ms, 99%: 52.274779ms
Total: 1265 samples
    1101  87.0%  87.0%     1105  87.4% runtime.cgocall
      40   3.2%  90.2%       40   3.2% runtime.usleep
      40   3.2%  93.4%       41   3.2% syscall.Syscall
      23   1.8%  95.2%       23   1.8% runtime.futex
       7   0.6%  95.7%        7   0.6% runtime.epollwait
       4   0.3%  96.0%        4   0.3% runtime.MSpan_Sweep
       3   0.2%  96.3%        3   0.2% ExternalCode
       3   0.2%  96.5%        3   0.2% findrunnable
       3   0.2%  96.8%        3   0.2% runtime.markscan
       3   0.2%  97.0%        3   0.2% runtime.rtsigprocmask
       2   0.2%  97.2%        2   0.2% pidleget
       2   0.2%  97.3%        2   0.2% runtime.atomicload
       2   0.2%  97.5%        3   0.2% runtime.entersyscall
       2   0.2%  97.6%        2   0.2% runtime.fastrand1
       2   0.2%  97.8%        2   0.2% runtime.gogo
       2   0.2%  97.9%        2   0.2% runtime.memmove
       2   0.2%  98.1%        2   0.2% sysmon
       1   0.1%  98.2%        1   0.1% MHeap_AllocLocked
       1   0.1%  98.3%        1   0.1% addstackroots
       1   0.1%  98.3%       16   1.3% bufio.(*Reader).Read

Adding a cumulative with the sleep version:

Total: 1279 samples
       0   0.0%   0.0%     1190  93.0% runtime.gosched0
       1   0.1%   0.1%     1149  89.8% main.func·003
       0   0.0%   0.1%     1116  87.3% github.com/triggit/feeds/processor.ResizeVips
       1   0.1%   0.2%     1114  87.1% github.com/daddye/vips.Resize
    1111  86.9%  87.0%     1111  86.9% runtime.cgocall
       0   0.0%  87.0%      488  38.2% github.com/daddye/vips._Cfunc_vips_jpegsave_custom
       0   0.0%  87.0%      267  20.9% github.com/daddye/vips._Cfunc_vips_affine_interpolator
       0   0.0%  87.0%      233  18.2% github.com/daddye/vips._Cfunc_vips_embed_extend
       0   0.0%  87.0%       82   6.4% System
      38   3.0%  90.0%       40   3.1% syscall.Syscall
      34   2.7%  92.7%       34   2.7% runtime.usleep
      27   2.1%  94.8%       27   2.1% runtime.futex
       0   0.0%  94.8%       26   2.0% io/ioutil.WriteFile
       0   0.0%  94.8%       25   2.0% github.com/daddye/vips._Cfunc_im_close
       0   0.0%  94.8%       25   2.0% github.com/daddye/vips._Cfunc_vips_image_new
       0   0.0%  94.8%       21   1.6% github.com/daddye/vips._Cfunc_vips_jpegload_buffer_seq
       0   0.0%  94.8%       21   1.6% github.com/gocql/gocql.(*Conn).recv
       0   0.0%  94.8%       21   1.6% github.com/gocql/gocql.(*Conn).serve
       1   0.1%  94.8%       19   1.5% bufio.(*Reader).Read
       0   0.0%  94.8%       19   1.5% github.com/daddye/vips._Cfunc_vips_copy_0

We can see that:

With a sleep:

1   0.1%   0.2%     1114  87.1% github.com/daddye/vips.Resize

Without a sleep:

1   0.0%  99.8%     6192  99.1% github.com/daddye/vips.Resize

So finally:

The version without sleep took (just for the C function call): 327.630885ms
With a sleep: 28.551381ms

Thanks so much
Davide</pre>

**Comment by rsc** [comment]
Assigning to Dmitriy to see if there's anything to do here or else close.

**Comment by dvyukov** [comment]
I don't see anything actionable here.
Using buffered channel and setting GOMAXPROCS to a higher value should solve the performance issue.
