### ISSUE TITLE
x/build/builders: move FreeBSD builders to GCE

### ISSUE THREAD

**Issue by bradfitz** [golang/go#8639]
<pre>This bug is about moving the FreeBSD builders to GCE per the document
<a href="http://golang.org/s/builderplan">http://golang.org/s/builderplan</a>

For FreeBSD it looks like we can use <a href="http://mfsbsd.vx.sk/">http://mfsbsd.vx.sk/</a> to prepare a FreeBSD image
that boots, does a single build (in memory), and then shuts down.

See:
<a href="https://groups.google.com/forum/#">https://groups.google.com/forum/#</a>!msg/gce-discussion/YWoa3Aa_49U/1MfTsmgoaNkJ</pre>

**Comment by wathiede** [comment]
Is the goal to have all the FreeBSD versions Go supports running as builders?  I know GCE had (has?) some problems with versions prior to 10, largely disk related.  Building from RAM might make pre-10 FreeBSD usable, but there could still be challenges getting it to booted far enough to build.

**Comment by adg** [comment]
I'm happy to just build against FreeBSD 10+, although the current builders
are running 9.1.

For the older versions, maybe we could run them (really slowly) inside qemu
on gce?

**Comment by bradfitz** [comment]
Let's start with FreeBSD 10 on GCE running the buildlet. We can run older versions elsewhere (RootBSD, AWS) too, but they won't be available via `gomote` and such.

**Comment by bradfitz** [comment]
@wathiede sent https://go-review.googlesource.com/#/c/3053/
