### ISSUE TITLE
cmd/compile: code motion doesn't recognize some loads

### ISSUE THREAD

**Issue by randall77** [golang/go#8641]
<pre>Around newproc/deferproc we decrement/increment the stack pointer by 12 bytes.  We then
do some code motion which moves instructions from outside this region to inside this
region (and vice versa?).  Instructions that are moved inside which refer to SP must
have their offsets adjusted by 12 bytes.  This is not done for some instructions.  See
<a href="https://golang.org/cl/139160043">https://golang.org/cl/139160043</a> for an example.</pre>

**Comment by rsc** [comment]
This is fixed by khr's change not to do funny stack adjustments around newproc and deferproc.
