### ISSUE TITLE
builders: move OpenBSD builder to GCE

### ISSUE THREAD

**Issue by bradfitz** [golang/go#8642]
<pre>This bug is about moving the OpenBSD builders to GCE per the document
<a href="http://golang.org/s/builderplan">http://golang.org/s/builderplan</a>

The OpenBSD buildbot will be similar to Windows (<a href="https://golang.org/issue/8640">issue #8640</a>) and FreeBBSD (<a href="https://golang.org/issue/8639">issue #8639</a>)

In summary, we want a script (that we can run on Linux, in Docker) that can generate a
GCE-bootable OpenBSD image.

That OpenBSD image must then, upon boot, fetch its GCE instance-level metadata value for
&quot;buildmaster-binary-url&quot; and exec it.

Basically, on boot (/etc/rc.local? is that a thing?), I want it to run:

curl -o /buildmaster $(curl -H &quot;Metadata-Flavor: Google&quot;
<a href="http://metadata.google.internal/computeMetadata/v1/instance/attributes/buildmaster-binary-url)">http://metadata.google.internal/computeMetadata/v1/instance/attributes/buildmaster-binary-url)</a>
chmod +x /buildmaster
exec /buildmaster
halt (if the exec failed)

And then we will occasionally update the buildmaster-binary-url property to a new
cross-compiled-to-OpenBSD (/Windows/FreeBSD) Go binary that implements the builder RPC
server, as described in <a href="https://golang.org/issue/8640">issue #8640</a>.

The OpenBSD kernel should be able to run both 32-bit or 64-bit binaries. Alternatively,
if easier or desired, prepare me two images.

Can some OpenBSD person own making the tool to prepare this image?</pre>

**Comment by bradfitz** [comment]
This is now running and working at https://build.golang.org/ ... note the new `openbsd-amd64-gce56` builder. I've updated the wiki DashboardBuilders page.

**Comment by bradfitz** [comment]
We still need 32-bit.

**Comment by mdempsky** [comment]
32-bit should be roughly just s/(amd64|x86_64)/i386/g, but maybe some of the installer questions differ slightly too.

One other comment: it's probably worth double-checking that non-Gophers can't SSH to the host (e.g., by using GCE firewall rules?), since the make.bash script includes username/password credentials for root and the gopher user.

**Comment by bradfitz** [comment]
@mdempsky, yes, these VMs are firewalled, including ssh.
