### ISSUE TITLE
x/build/builders: move NetBSD builders to GCE

### ISSUE THREAD

**Issue by bradfitz** [golang/go#8643]
<pre>This bug is about moving the NetBSD builders to GCE per the document
<a href="http://golang.org/s/builderplan">http://golang.org/s/builderplan</a>

See <a href="https://golang.org/issue/8642">issue #8642</a> about OpenBSD for details. Same thing.

This bug is specifically about details of whatever's involved for NetBSD and somebody
claiming ownership.</pre>

**Comment by bsiegert** [comment]
I started working on this. There is a package called anita which does the scripted install automatically so it should be a little easier than OpenBSD.

**Comment by bsiegert** [comment]
https://go-review.googlesource.com/2612

**Comment by bradfitz** [comment]
Excellent!

Benny, before I spend any time on this (Plan 9 sucked all my time dry, and then some), could you verify this boots and runs on GCE?

I've put up a buildlet for netbsd here:

https://storage.googleapis.com/go-builder-data/buildlet.netbsd-amd64

... so if you start a GCE VM with a metadata key "buildlet-binary-url" set to that value, the instance should see it on boot.

With the .tar.gz file that this script generates, to create an "Image" on GCE, do this:

```
$ gsutil cp -a public-read netbsd-amd64.tar.gz gs://YOUR-BUCKET-NAME/netbsd-amd64.tar.gz
$ gcloud compute --project YOUR-PROJECT-NAME images create netbsd-amd64 --source-uri gs://YOUR-BUCKET-NAME/netbsd-amd64.tar.gz
```

And then it'll show up in the web UI as an image when you create a new instance.
Once it boots, see if you can go to port 80 on it.  It should say "I'm a buildlet on netbsd/amd64".

**Comment by bsiegert** [comment]
OK, I'll try this and report back.

**Comment by bradfitz** [comment]
/cc @minux who runs the current 386 builder. I guess we have no amd64 builder.

@bsiegert, any update on this?

**Comment by bradfitz** [comment]
Ping @bsiegert  :)

**Comment by bsiegert** [comment]
Sorry for dropping this on the floor for so long. 

In http://gnats.netbsd.org/50636, there have been fixes to NetBSD-current to make it work on GCE. I'll try my script again in the next couple of days and update this bug.

**Comment by bradfitz** [comment]
Yay!

**Comment by minux** [comment]
@bsiegert, is it also possible to move the netbsd/386
builder to GCE?

**Comment by bsiegert** [comment]
In principle yes. Let's do amd64 first, 386 should be simple after that.

**Comment by bsiegert** [comment]
FWIW, https://storage.googleapis.com/bsiegert/netbsd-amd64-gce.tar.gz contains a working image for a NetBSD builder. https://storage.googleapis.com/bsiegert/netbsd-amd64-gce.tar.gz is the buildlet.

```
+ exec /buildlet
2016/02/21 14:57:45 buildlet starting.
2016/02/21 14:57:45 Will listen on :80
2016/02/21 14:57:45 Listening on :80 ...
```

\o/

**Comment by bradfitz** [comment]
Alternatively, @mdempsky, do you have time to look into finishing up https://go-review.googlesource.com/#/c/19350/?

**Comment by bsiegert** [comment]
Sorry for the long turnaround times for this CL. @minux, once CL 19350 is in and the builder works, adding i386 is trivial (I hope).

**Comment by bradfitz** [comment]
Any progress here?

**Comment by mdempsky** [comment]
I added some review comments to CL 19350 a few days back, but I haven't looked into it since then. Unfortunately, OpenBSD and NetBSD are sufficiently divergent that my OpenBSD knowledge isn't especially applicable here.  But if this is still open once we hit 1.7 freeze, I'll take ownership.

**Comment by bradfitz** [comment]
This is deployed. Thanks, @bsiegert!

**Comment by bradfitz** [comment]
Sorry, spoke too soon. These never boot on GCE. I don't even see serial console output. GCE always just says "Failed to load" when I ask for serial.

**Comment by bsiegert** [comment]
:(

The serial output is discarded as soon as the VM supervisor exits. So you have to catch it at the right moment to see something. If you have the interactive serial console thing enabled, then that's extremely helpful.

**Comment by bradfitz** [comment]
Did you test this on GCE?

**Comment by bsiegert** [comment]
Yes, I did. I had a version that was successfully launching the buildlet.

**Comment by bradfitz** [comment]
So what's different?

**Comment by bradfitz** [comment]
We're running in us-central1-f on n1-highcpu-2

**Comment by bsiegert** [comment]
OK, let me try.

**Comment by bradfitz** [comment]
Buildlet is http://storage.googleapis.com/go-builder-data/buildlet.netbsd-amd64

**Comment by bradfitz** [comment]
Get a chance to try this again? Is it possible my nightly build of NetBSD where I grabbed the snapshot was buggy?

**Comment by bradfitz** [comment]
@bsiegert, @mdempsky, can one of you spend some time on this and get this done?

We have no netbsd-amd64 builder at the moment (and even netbsd-386 seems dead for the past day?), so I'm getting increasingly tempted to propose deleting our netbsd support if we can't get some builder love.

**Comment by minux** [comment]
The netbsd/386 builder got stuck testing the term subrepo. I have restarted
it.

**Comment by bsiegert** [comment]
Sorry for dragging this out for so long. (In the meantime, btw, we got
NetBSD 7.0.1, which runs on GCE.)

I am currently in Finland with no laptop, but I'll try to get this done
after my vacation.
Minux Ma <notifications@github.com> schrieb am ven. 22 juil. 2016 um 02:48:

**Comment by bradfitz** [comment]
Ping. Benny?

**Comment by bradfitz** [comment]
I built the image and deployed it to the staging cluster. I verified the buildlet binary was at the right spot and the metadata key pointed to it.

But it didn't work. It timed out after the buildlet didn't come up in 3 minutes.

Serial console says:

```
SeaBIOS (version 1.8.2-20160920_150358-google)
Total RAM Size = 0x00000000e6600000 = 3686 MiB
CPU Mhz=6135
CPUs found: 4     Max CPUs supported: 4
found virtio-scsi at 0:3
virtio-scsi vendor='Google' product='PersistentDisk' rev='1' type=0 removable=0
virtio-scsi blksize=512 sectors=8388608 = 4096 MiB
drive 0x000f46c0: PCHS=0/0/0 translation=lba LCHS=522/255/63 s=8388608
Booting from Hard Disk 0...

>> NetBSD/x86 BIOS Boot, Revision 5.10 (from NetBSD 7.0.1)
>> Memory: 639/3144640 k

     1. Boot normally
     2. Boot single user
     3. Disable ACPI
     4. Disable ACPI and SMP
     5. Drop to boot prompt

Choose an option; RETURN for default; SPACE to stop countdown.
Option 1 will be chosen in 5 seconds. 4 seconds. 3 seconds. 2 seconds. 1 seconds. 0 seconds. 0 seconds.     
|/-\|/-\14187064|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\+654328|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\+594952|/-\ [1025016|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|+717527/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|]=0x11630a0
/-\|/-\|/-\|/-\|/-\|/-\|/-\|WARNING: couldn't open /var/db/entropy-file
WARNING: 1 module failed to load
Copyright (c) 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005,
    2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015
    The NetBSD Foundation, Inc.  All rights reserved.
Copyright (c) 1982, 1986, 1989, 1991, 1993
    The Regents of the University of California.  All rights reserved.

NetBSD 7.0.1 (GENERIC.201605221355Z)
total memory = 3685 MB
avail memory = 3560 MB
kern.module.path=/stand/amd64/7.0/modules
mainbus0 (root)
ACPI: RSDP 0xf4700 000014 (v00 Google)
ACPI: RSDT 0xbfffde30 000034 (v01 Google GOOGRSDT 00000001 GOOG 00000001)
ACPI: FACP 0xbfffff00 0000F4 (v02 Google GOOGFACP 00000001 GOOG 00000001)
ACPI: DSDT 0xbfffde70 0015A3 (v01 Google GOOGDSDT 00000001 GOOG 00000001)
ACPI: FACS 0xbffffec0 000040
ACPI: SSDT 0xbffff550 000966 (v01 Google GOOGSSDT 00000001 GOOG 00000001)
ACPI: APIC 0xbffff450 000086 (v01 Google GOOGAPIC 00000001 GOOG 00000001)
ACPI: WAET 0xbffff420 000028 (v01 Google GOOGWAET 00000001 GOOG 00000001)
ACPI: All ACPI Tables successfully acquired
ioapic0 at mainbus0 apid 0
cpu0 at mainbus0 apid 0: Intel(R) Xeon(R) CPU @ 2.50GHz, id 0x306e4
cpu1 at mainbus0 apid 1: Intel(R) Xeon(R) CPU @ 2.50GHz, id 0x306e4
cpu2 at mainbus0 apid 2: Intel(R) Xeon(R) CPU @ 2.50GHz, id 0x306e4
cpu3 at mainbus0 apid 3: Intel(R) Xeon(R) CPU @ 2.50GHz, id 0x306e4
acpi0 at mainbus0: Intel ACPICA 20131218
pckbc1 at acpi0 (KBD, PNP0303) (kbd port): io 0x60,0x64 irq 1
pckbc2 at acpi0 (MOU, PNP0F13) (aux port): irq 12
COM1 (PNP0501) at acpi0 not configured
COM2 (PNP0501) at acpi0 not configured
COM3 (PNP0501) at acpi0 not configured
COM4 (PNP0501) at acpi0 not configured
PEVT (QEMU0001) at acpi0 not configured
ACPI: Enabled 16 GPEs in block 00 to 0F
ACPI Exception: AE_NOT_FOUND, While evaluating Sleep State [\_S0_] (20131218/hwxface-646)
ACPI Exception: AE_NOT_FOUND, While evaluating Sleep State [\_S1_] (20131218/hwxface-646)
ACPI Exception: AE_NOT_FOUND, While evaluating Sleep State [\_S2_] (20131218/hwxface-646)
pckbd0 at pckbc1 (kbd slot)
pckbc1: using irq 1 for kbd slot
wskbd0 at pckbd0 mux 1
pms0 at pckbc1 (aux slot)
pckbc1: using irq 12 for aux slot
wsmouse0 at pms0 mux 0
pci0 at mainbus0 bus 0: configuration mode 1
pchb0 at pci0 dev 0 function 0: vendor 0x8086 product 0x1237 (rev. 0x02)
pcib0 at pci0 dev 1 function 0: vendor 0x8086 product 0x7110 (rev. 0x03)
piixpm0 at pci0 dev 1 function 3: vendor 0x8086 product 0x7113 (rev. 0x03)
piixpm0: SMBus disabled
virtio0 at pci0 dev 3 function 0
virtio0: Virtio Unknown (8) Device (rev. 0x00)
virtio0: no matching child driver; not configured
virtio1 at pci0 dev 4 function 0
virtio1: Virtio Network Device (rev. 0x00)
vioif0 at virtio1: Ethernet address 42:01:0a:f0:00:07
virtio1: interrupting at ioapic0 pin 11
isa0 at pcib0
com0 at isa0 port 0x3f8-0x3ff irq 4: ns16550a, working fifo
com0: console
com1 at isa0 port 0x2f8-0x2ff irq 3: ns16550a, working fifo
attimer0 at isa0 port 0x40-0x43
pcppi0 at isa0 port 0x61
midi0 at pcppi0: PC speaker
sysbeep0 at pcppi0
attimer0: attached to pcppi0
acpicpu0 at cpu0: ACPI CPU
acpicpu1 at cpu1: ACPI CPU
acpicpu2 at cpu2: ACPI CPU
acpicpu3 at cpu3: ACPI CPU
ERROR: 280 cycle TSC drift observed
pad0: outputs: 44100Hz, 16-bit, stereo
audio0 at pad0: half duplex, playback, capture
boot device: <unknown>
root device: acpi0: power button pressed, shutting down!
syncing disks... done
sysbeep0: detached
```

That 5 second pause seems unnecessary.

But also, can we get the `rc.local` output attached to the serial console for debugging?

I have no clue why it didn't work.

@bsiegert?

**Comment by bsiegert** [comment]
@bradfitz I'll be in Seattle next week. Could we sit down together and take a look why this fails?

**Comment by bradfitz** [comment]
I'll also be in Seattle, surprisingly! I arrive tonight. Let's do it.

**Comment by minux** [comment]
I think the reason is that the kernel couldn't find a driver for the
virtio-scsi disk.

relevant log entries:
found virtio-scsi at 0:3   // <--- virtio-scsi is at pci0 dev 3
virtio-scsi vendor='Google' product='PersistentDisk' rev='1' type=0
removable=0
virtio-scsi blksize=512 sectors=8388608 = 4096 MiB
...
virtio0 at pci0 dev 3 function 0
virtio0: Virtio Unknown (8) Device (rev. 0x00)
virtio0: no matching child driver; not configured // <--- it's not
recognized
...

**Comment by bsiegert** [comment]
I got the vioscsi driver (which was indeed missing) pulled up into `netbsd-7` (as well as some virtio fixes), so it will be part of the NetBSD 7.1 release. I also finally got the incantations in the right order to get network into a working state.

I'll update the pending CL.

**Comment by bsiegert** [comment]
For the record (and so I don't forget), this is the magic incantation for the network:

On netbsd-7, you need to install the `dhcpcd` package (the one included is too old). Then, the following goes into `/etc/ifconfig.vioif0`:

```
!/usr/pkg/sbin/dhcpcd vioif0
!route add default 10.240.0.1 -ifp vioif0
```

(Unfortunately, each project uses a different second byte.) The bit with the default route is an issue with dhcpcd, which I have reported upstream.

**Comment by bradfitz** [comment]
@bsiegert, with your latest NetBSD 7.1_RC1 image, I now see it boot and get this serial console output before it shuts down:

```
+ set -e
+ curl -H 'Metadata-Flavor: Google' 'http://metadata.google.internal/computeMetadata/v1/instance/attributes/buildlet-binary-url'
Shared object "libssl.so.10" not found
+ curl -o /buildlet
Shared object "libssl.so.10" not found
+ echo 'giving up'
+ command echo 'giving up'
giving up
+ sleep 10
```

The `/etc/rc.local/` start-up script is:

```sh
(                                                                                                                                                                                    
  export PATH=/usr/pkg/bin:/usr/pkg/sbin:${PATH}                                                                                                                                     
  export GOROOT_BOOTSTRAP=/usr/pkg/go14                                                                                                                                              
  set -x                                                                                                                                                                             
  echo 'starting buildlet script'                                                                                                                                                    
  netstat -rn                                                                                                                                                                        
  cat /etc/resolv.conf                                                                                                                                                               
  dig metadata.google.internal                                                                                                                                                       
  (                                                                                                                                                                                  
    set -e                                                                                                                                                                           
    curl -o /buildlet \$(curl -H 'Metadata-Flavor: Google' http://metadata.google.internal/computeMetadata/v1/instance/attributes/buildlet-binary-url)                               
    chmod +x /buildlet                                                                                                                                                               
    exec /buildlet                                                                                                                                                                   
  )                                                                                                                                                                                  
  echo 'giving up'                                                                                                                                                                   
  sleep 10                                                                                                                                                                           
  halt -p                                                                                                                                                                            
)                                                                                                                                                                                    
```

If the `curl -H` is failing due to libssl not being found, I'm not sure why the `set -e` isn't catching it and failing the whole block. Is `set -e` a bash thing and this isn't bash?

Why isn't `libssl` available?

How did you get a buildlet?

**Comment by bradfitz** [comment]
(And I confirm that the VM is created with `buildlet-binary-url` set to:

```
http://storage.googleapis.com/go-builder-data/buildlet.netbsd-amd64
```

... which notably isn't even https, so I don't know why it needs `libssl`.

**Comment by bradfitz** [comment]
@bsiegert, status?

**Comment by bsiegert** [comment]
No updates for now. I think I understand why your image is different from mine: you built from the US, so the CDN sent you to a different mirror with different package versions. Sigh. Maybe back to hard-coding ftp.netbsd.org again.

**Comment by bradfitz** [comment]
Gross. Can we hard-code versions or ideally a hash of a merkle tree root of versions and make sure we always get the same bits?

**Comment by bradfitz** [comment]
Ping @bsiegert  :)

**Comment by bsiegert** [comment]
I forgot to tag this issue in https://go-review.googlesource.com/#/c/37190/. Could you give it another try, @bradfitz? I got a working buildlet machine in my testing.
