### ISSUE TITLE
x/build/builders: subrepos shouldn't cause full rebuild of Go

### ISSUE THREAD

**Issue by bradfitz** [golang/go#8646]
<pre>Currently if I submit to go.tools or some subrepo, all builders need to rebuild the tip
Go commit just to rebuild the subrepo.

We should save the result of the build (tar it up to GCS or something) after hg tip is
build, to avoid that extra work.

This is related to sharding: we only need to &quot;make.bash&quot; in order to run the
subrepo builds &amp; tests.</pre>

**Comment by bradfitz** [comment]
@adg, I can't figure out the interface to the dashboard here.

The openbsd-amd64-gce56 builder is only building Go commits and not packages (you can see the blank cells at the bottom of https://build.golang.org), but these URLs don't give me any info:

http://build.golang.org/todo?builder=openbsd-amd64-gce56&kind=build-go-commit
http://build.golang.org/todo?builder=openbsd-amd64-gce56&kind=build-package

What is the URL to ask the daskboard what subrepo packages need to be built?

**Comment by bradfitz** [comment]
And now those URLs are returning data! I'm even more confused. You didn't push a new version, did you?

**Comment by adg** [comment]
I didn't change anything.

**Comment by bradfitz** [comment]
Per discussion with @adg we're going to not modify the /todo handler, so we don't break the old-style builders.

The coordinator instead will learn which subrepos it needs to build based on the data from http://build.golang.org/?mode=json (which is to be done in #9493)

**Comment by bradfitz** [comment]
This is now fixed with the recent builder work.
