### ISSUE TITLE
net: flaky TestReloadResolvConfFail

### ISSUE THREAD

**Issue by mikioh** [golang/go#8652]
<pre>it sometimes fails on darwin:

-- FAIL: TestReloadResolvConfFail (1.21s)
	dnsclient_unix_test.go:182: goLookupIP(missing; good) failed: stat /var/folders/7d/d3y9vsls2yd880k121jmzcyr0000gn/T/resolvConfTest018927742/resolv.conf: no such file or directory
FAIL</pre>

**Comment by zachgersh** [comment]
I could totally grab this as well.

**Comment by 4ad** [comment]
Happens on Solaris reliably.

**Comment by 4ad** [comment]
This fixes it, although I don't quite know why:

	diff --git a/src/net/dnsclient_unix_test.go b/src/net/dnsclient_unix_test.go
	index 40b78bd..bfae88c 100644
	--- a/src/net/dnsclient_unix_test.go
	+++ b/src/net/dnsclient_unix_test.go
	@@ -143,6 +143,7 @@ func (r *resolvConfTest) SetConf(s string) {
	 		cfg.ch <- struct{}{} // fill buffer
	 		cfg.ch <- struct{}{} // wait for reload to begin
	 		cfg.ch <- struct{}{} // wait for reload to complete
	+		cfg.ch <- struct{}{}
	 	}
	 }
