### ISSUE TITLE
html: EscapeString could be made faster using a strings.Replacer  

### ISSUE THREAD

**Issue by kbloom** [golang/go#8697]
<pre>Consider the following benchmark:

package escaping

import (
        &quot;html&quot;
        &quot;strings&quot;
        &quot;testing&quot;
)

const noHTMLString = `Can you hear the people sing, singing the song of
angry men. It is the music of a people who will not be slaves again.`
const withHTMLString = `We're going to demand &lt;strong&gt;one million
dollars&lt;/strong&gt; or we're going to threaten Earth with a &quot;Laser&quot;.`

var escaper = strings.NewReplacer(
        `&amp;`, &quot;&amp;amp;&quot;,
        `'`, &quot;&amp;#39;&quot;,
        `&lt;`, &quot;&amp;lt;&quot;,
        `&gt;`, &quot;&amp;gt;&quot;,
        `&quot;`, &quot;&amp;#34;&quot;,
)

func BenchmarkHtml_EscapeString_nochanges(b *testing.B) {
        for i := 0; i &lt; b.N; i++ {
                html.EscapeString(noHTMLString)
        }
}

func BenchmarkStrings_Replacer_nochanges(b *testing.B) {
        for i := 0; i &lt; b.N; i++ {
                escaper.Replace(noHTMLString)
        }
}

func BenchmarkHtml_EscapeString_changes(b *testing.B) {
        for i := 0; i &lt; b.N; i++ {
                html.EscapeString(withHTMLString)
        }
}

func BenchmarkStrings_Replacer_changes(b *testing.B) {
        for i := 0; i &lt; b.N; i++ {
                escaper.Replace(withHTMLString)
        }
}

The performance is as follows:

BenchmarkHtml_EscapeString_nochanges      500000              3912 ns/op
BenchmarkStrings_Replacer_nochanges      5000000               368 ns/op
BenchmarkHtml_EscapeString_changes        500000              4597 ns/op
BenchmarkStrings_Replacer_changes        1000000              1360 ns/op

I've written <a href="https://golang.org/cl/141930043/">https://golang.org/cl/141930043/</a> to change html.EscapeString so
that it uses a replacer internally, but it needs to wait until Go 1.5 development opens.</pre>

**Comment by josharian** [comment]
@kbloom do you plan to migrate your CL to Gerrit (the new codereview system)? If not, would you like one of us to do so for you? Thanks!

**Comment by dspezia** [comment]
I'm not sure the OP is still following this thread. I prepare a similar CL (crediting him, of course).

**Comment by kbloom** [comment]
Thanks. I had lost track of your ping because it was in my personal email
rather than my corp email. (Plus the friction of getting set up on a new
review environment.) I can't even figure out how to LGTM your CL, but it
looks good to me.
