### ISSUE TITLE
cmd/asm: error on overlap

### ISSUE THREAD

**Issue by randall77** [golang/go#8700]
<pre>It would be nice if the assemblers generated an error for data statements that
overlapped:

DATA foo+0x00(SB)/4, $7
DATA foo+0x04(SB)/4, $8
DATA foo+0x04(SB)/4, $9

The last two statements are in conflict - the user probably wanted to have 0x08 in the
last line.</pre>

**Comment by agnivade** [comment]
@randall77 - This fails now with the error - 

```
math/exp_amd64.s:31: overlapping DATA entry for exprodata
asm: assembly of math/exp_amd64.s failed
```

I did - `go tool asm -I runtime/ math/exp_amd64.s`

Kindly check and close if this looks fixed to you.

**Comment by randall77** [comment]
Yes, looks fixed.
