### ISSUE TITLE
sync: intermittent crash locking Mutex -- unexpected fault address

### ISSUE THREAD

**Issue by bmatsuo** [golang/go#8703]
<pre>What does 'go version' print?

go version go1.3.1 linux/amd64

What steps reproduce the problem?

We cannot yet reliably reproduce this problem. It happens in large clusters very
intermittently. The context of the crash is launching goroutines while iterating a slice
in a for-select loop.

func (tab *ProcessTable) loop() {
    for {
        select {
        // ...
        case set := &lt;-tab.persist:
            for _, p := range tab.ps {
                p := p
                go p.DatasetPersisted(set)
            }
        }
        // ...
    }
}

The method called is attempting to lock a mutex.

func (p *Process) DatasetPersisted(outset vaultdata.Dataset) {
    if p == nil {
        return
    }  
    p.chwrmut.Lock()
    defer p.chwrmut.Unlock()
    if !p.closed {
        p.setPersistStatus &lt;- setPersistStatus{outset, nil}
    }  
}

What happened?

The system crashes with the following error. I've only included the top stack as there
are several hundred active goroutines at the time this occurs. There is a
runtime.goexit() call near the bottom that is confusing.

unexpected fault address 0x0
fatal error: fault
[signal 0x7 code=0x80 addr=0x0 pc=0x60f9dd]

goroutine 10270 [running]:
runtime.throw(0xae7a56)
        /usr/local/go/src/pkg/runtime/panic.c:520 +0x69 fp=0x7ff97dcc5ee8 sp=0x7ff97dcc5ed0
runtime.sigpanic()
        /usr/local/go/src/pkg/runtime/os_linux.c:232 +0x25b fp=0x7ff97dcc5f00 sp=0x7ff97dcc5ee8
sync/atomic.CompareAndSwapUint32(0x7561772f746e6d9f, 0x100000000)
        /usr/local/go/src/pkg/sync/atomic/asm_amd64.s:42 +0xd fp=0x7ff97dcc5f08 sp=0x7ff97dcc5f00
sync.(*Mutex).Lock(0x7561772f746e6d9f)
        /usr/local/go/src/pkg/sync/mutex.go:43 +0x42 fp=0x7ff97dcc5f30 sp=0x7ff97dcc5f08
vault/vaultproc.(*Process).DatasetPersisted(0x7561772f746e6d2f, 0x6f2f646f72702e73,
0x393034312f736a62, 0x2d343034302d3131, 0x39382f61382f3435)
        /tmp/wault-build-356012266/git/src/vault/vaultproc/proc.go:233 +0x4a fp=0x7ff97dcc5f80 sp=0x7ff97dcc5f30
runtime.goexit()
        /usr/local/go/src/pkg/runtime/proc.c:1445 fp=0x7ff97dcc5f88 sp=0x7ff97dcc5f80
created by vault/vaultproc.(*ProcessTable).loop
        /tmp/wault-build-356012266/git/src/vault/vaultproc/table.go:255 +0x3c3

What should have happened instead?

No fatal error should occur there.

Please provide any additional information below.

The rate we have seen this occur has been approximately once every several weeks (this
is the first occurrence on go1.3.1).

We saw this error in go1.3 as well. The codebase is young and was running on go1.2.1 for
only a very short time. So while we didn't see the problem present then, given how
intermittent the crash is in nature, I can't say with certainty that it wouldn't have
happened.

Also, we have run into an occasional problem where the go process reaches the limit on
open file descriptors. I have no idea if could be related. And as I said previously
there's no indication from our logs that was the case when the faults have occurred.</pre>

**Comment by rsc** [comment]
In the absence of more information, I don't believe we can fix this.
