### ISSUE TITLE
x/tools/cmd/godoc: start very slowly in china

### ISSUE THREAD

**Issue by chai2010** [golang/go#8710]
<pre>Thanks to GFW, we can't visit youtube.com.
Hope disable load youtube.com in godoc.</pre>

Attachments:
1. <a href="https://storage.googleapis.com/go-attachment/8710/0/godoc.png">godoc.png</a> (60557 bytes)

**Comment by bradfitz** [comment]
I'd rather not add flags for everybody's oppressive regime. I have my own to worry about.
