### ISSUE TITLE
crypto/tls: Failed handshake should not send any data to client

### ISSUE THREAD

**Issue by AudriusButkevicius** [golang/go#8720]
<pre>What does 'go version' print?

go version go1.3 windows/amd64

What steps reproduce the problem?

Snippet: <a href="http://play.golang.org/p/eu_6CStY3k">http://play.golang.org/p/eu_6CStY3k</a>

1. Run the snippet above
2. Browse to <a href="http://localhost:8181">http://localhost:8181</a>

What happened?

Depending on platform or browser different things might happen.
If the browser thinks the data looks binary, it usually starts a download.
If the data looks plain-text'ish, it outputs bytes to the browser.

What should have happened instead?

The connection should have been closed without any data sent, since it doesn't get past
the TLS handshake due to protocol mismatch.

Or alternatively, a feature specific to net/http using TLS could downgrade the protocol
to HTTP and deal with it in some way.

Please provide any additional information below.

The culprit is the following line:
<a href="https://code.google.com/p/go/source/browse/src/crypto/tls/conn.go#582">https://code.google.com/p/go/source/browse/src/crypto/tls/conn.go#582</a>

If commented out, it produces the expected &quot;No data received&quot; error on Chrome.</pre>

**Comment by FiloSottile** [comment]
Fixed by 2a8c81f amongst others.
