### ISSUE TITLE
x/tools/cmd/vet: not always warning about capturing range variable in function literal

### ISSUE THREAD

**Issue by reusee** [golang/go#8732]
<pre>What does 'go version' print?
go version devel +d0331dfbc053 Fri Sep 12 16:35:40 2014 -0700 linux/amd64

What steps reproduce the problem?
go tool vet [program]

What happened?
<a href="http://play.golang.org/p/tB3tpqV1yT">http://play.golang.org/p/tB3tpqV1yT</a> this warns,
<a href="http://play.golang.org/p/6HYeRqt_pw">http://play.golang.org/p/6HYeRqt_pw</a> this doesn't,
<a href="http://play.golang.org/p/ULAplewjBO">http://play.golang.org/p/ULAplewjBO</a> and this warns.</pre>

**Comment by adg** [comment]
This is by design.
