### ISSUE TITLE
cmd/compile: spurious type mismatch error when assigning float64 to indexed string byte

### ISSUE THREAD

**Issue by btracey** [golang/go#8744]
<pre>In the following program:

package main

func main() {
	var a float64
	var s string
	s[0] = a
}

The program reports:
prog.go:6: cannot assign to s[0]
prog.go:6: cannot use a (type float64) as type uint8 in assignment

There are two issues here. First, there are two errors when there could be one. This is
related to <a href="https://golang.org/issue/6406">issue #6406</a>. Second, the type mismatch is stated as float64 vs uint8, but it
should be float64 vs. byte. I'm not sure if these two issues are related, so I'm filing
them as one issue, but I can file a second issue if they are distinct.</pre>

**Comment by rsc** [comment]
The extra error does not bother me. There are two things wrong with the statement. Reporting both is okay.
