### ISSUE TITLE
cmd/go: make path pattern matching functions available to go programmers

### ISSUE THREAD

**Issue by zimmski** [golang/go#8768]
<pre>The go command uses the function &quot;importPaths&quot; from
<a href="https://code.google.com/p/go/source/browse/src/cmd/go/main.go">https://code.google.com/p/go/source/browse/src/cmd/go/main.go</a> to resolve path patterns
like &quot;net/...&quot;. Since this code is not exported other Go tools like
&quot;golint&quot; would have to reimplement or copy it. I propose that this should be
put into a public API so that third party Go projects can use the exact same behavior.

I am willing to do the coding part but I need some guidance on where I should move the
functions and how to properly name them.</pre>

**Comment by ianlancetaylor** [comment]
I think the current plan would be to use go/packages.

**Comment by bcmills** [comment]
Agreed; go/packages should address exactly this use-case.
