### ISSUE TITLE
x/playground: indentation impossible after depth 3

### ISSUE THREAD

**Issue by griesemer** [golang/go#8770]
<pre><a href="http://play.golang.org/p/YfHY5z2wVF">http://play.golang.org/p/YfHY5z2wVF</a>

Pressing tab on line 7 doesn't indent anymore. Nor is it possible to copy and paste a
tab on that line to get more indentation. Format also doesn't show an additional
indentation level.

This looks like some UI quirk.

It also affects some of the golang.org example programs that have more than 3 levels of
identation.</pre>

**Comment by dericofilho** [comment]
@adg this can be closed. I tested on Chrome on X and it worked fine.
