### ISSUE TITLE
x/sys/unix: add support for *xattr functions on FreeBSD

### ISSUE THREAD

**Issue by worr** [golang/go#8785]
<pre>What does 'go version' print?
go version go1.3.1 freebsd/amd64

What steps reproduce the problem?
If possible, include a link to a program on play.golang.org.

1. On FreeBSD, try and call any functions that handle extended attributes

What happened?
Compilation failure

What should have happened instead?
Ideally, these functions would have been implemented

Please provide any additional information below.
I've attached a CL that fixes this: <a href="https://golang.org/cl/147850043/">https://golang.org/cl/147850043/</a></pre>

**Comment by AlekSi** [comment]
I think that one can be closed? https://codereview.appspot.com/147850043 was merged.
