### ISSUE TITLE
x/tools/dashboard/app: incorrect build failure emails

### ISSUE THREAD

**Issue by dvyukov** [golang/go#8831]
<pre>For tests the app sends failure emails only on ok-&gt;fail transition. But for perf
benchmarks it sends emails for all failures. I've tried to fix it, but obviously failed.
The logic is not trivial as there can be partial results and/or partial failures.
For benchmarks the app needs to send emails only on ok-&gt;fail transitions as well.</pre>

**Comment by ALTree** [comment]
The old dashboard has been dismissed years ago so we can close this.
