### ISSUE TITLE
net/http: get for literal ipv6 address url doesn't follow redirection on ipv6-only transport environment

### ISSUE THREAD

**Issue by mikioh** [golang/go#8847]
<pre>theoretically the root cause must be golang.org/issue/8453, but file a separate issue
for safety. for now workaround would be having a custom transport like the following:

tr := &amp;http.Transport{
        Dial: (&amp;net.Dialer{DualStack: true}).Dial,
}
client := http.Client{Transport: tr}
resp, err := client.Get(fmt.Sprintf(&quot;http://[2404:6800:4004:802::1011]:80/&quot;)</pre>

**Comment by rsc** [comment]
Not sure what the status is here, but Brad, Mikio replied to your questions.

**Comment by mikioh** [comment]
#8453 will fix this together, but please keep this open for now. Perhaps we need a test case that runs http.Get/http.Client.Get for www.google.com over only IPv6 transport.
