### ISSUE TITLE
lib/codereview: cannot find CL in local repository

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#8852]
<pre>Cannot undo existing CL, but should be able to:

# hg id
87dcbcc9371b tip
# hg st
# hg log -r 4eda5e4001fd -v
changeset:   21122:4eda5e4001fd
user:        Brad Fitzpatrick &lt;bradfitz@golang.org&gt;
date:        Mon Sep 08 17:47:12 2014 -0700
files:       src/syscall/mksyscall_windows.go src/syscall/zsyscall_windows.go
description:
syscall: keep Windows syscall pointers live too

Like <a href="https://golang.org/cl/139360044">https://golang.org/cl/139360044</a>

LGTM=rsc, alex.brainman
R=alex.brainman, rsc
CC=golang-codereviews
<a href="https://golang.org/cl/138250043">https://golang.org/cl/138250043</a>

# hg undo 138250043
abort: cannot find CL 138250043 in local repository
#

I can see where the problem is, but not confident enough to change codereview.

Alex</pre>

**Comment by rsc** [comment]
No more codereview.py!
