### ISSUE TITLE
x/playground: child processes of the "present" tool not killed on terminate

### ISSUE THREAD

**Issue by karalabe** [golang/go#8854]
<pre>In the online presentations (through the &quot;present&quot; tool), if the executing
code snippet starts up a child process (see end of report for a trivial example), the
child process will remain running in the background even if the parent (original
process) is killed or terminates gracefully.

This is especially an issue if a user kills a running snippet, which will leave
stale/dangling processes running on the host machine.

---
E.g.

package main

import &quot;os/exec&quot;

func main() {
    cmd := exec.Command(&quot;sleep&quot;, &quot;100&quot;)
    cmd.Start()
}

If you run this inside present, and kill the process, the sleep will happily run in the
background until it finishes.</pre>

**Comment by ysmolsky** [comment]
I am confused about this bug. This does not have to be solved in playground code because playground already kills processes that timed out. Anyway, I'm closing it unless somebody can show me the problem to solve.
