### ISSUE TITLE
net/http/httptest: ResponseRecorder does not mimic real behavior of WriteHeader()

### ISSUE THREAD

**Issue by scottferg** [golang/go#8857]
<pre>httptest.ResponseRecorder does not mimic the behavior of the net/http package when
headers are written after a call to WriteHeader().

Per the documentation for http.ResponseWriter:

    Header returns the header map that will be sent by WriteHeader.
    Changing the header after a call to WriteHeader (or Write) has
    no effect.

However, if you change the header after a call to WriteHeader while using
httptest.ResponseRecorder the result will appear as though the header was set (and sent)
correctly. 

This appears to be caused by the fact that in this function:

// Header returns the response headers.
func (rw *ResponseRecorder) Header() http.Header {
        m := rw.HeaderMap
        if m == nil {
                m = make(http.Header)
                rw.HeaderMap = m
        }
        return m
}

there is no check to see if rw.wroteHeader is true. Anything set before or after
`rw.wroteHeader = true` will still show up in this map.

What steps reproduce the problem?
If possible, include a link to a program on play.golang.org.

1. In an http.HandlerFunc, call rw.Header().Set(&quot;Some-Header&quot;,
&quot;Some-Value&quot;) after a call to rw.WriteHeader(statuscode)
2. Call this handler by passing in an httptest.ResponseRecorder

What happened?

recorder.HeaderMap[&quot;Some-Header&quot;][0] will be set to &quot;Some-Value&quot;

What should have happened instead?

&quot;Some-Header&quot; should not have been set</pre>

**Comment by bradfitz** [comment]
It's been requested that we fix this for the next release.

Unfortunately the CL above was never updated so didn't make it into Go 1.6.
