### ISSUE TITLE
net: TestTCPReadWriteAllocs flakiness

### ISSUE THREAD

**Issue by mikioh** [golang/go#8859]
<pre>i now see the following on darwin w/ tip:

go test -run=TestTCPReadWriteMallocs -cpu=1,2,4,8,16,32
--- FAIL: TestTCPReadWriteMallocs (0.02s)
	tcp_test.go:531: Got 1 allocs, want 0
--- FAIL: TestTCPReadWriteMallocs-2 (0.02s)
	tcp_test.go:531: Got 1 allocs, want 0
--- FAIL: TestTCPReadWriteMallocs-4 (0.02s)
	tcp_test.go:531: Got 1 allocs, want 0
--- FAIL: TestTCPReadWriteMallocs-8 (0.02s)
	tcp_test.go:531: Got 1 allocs, want 0
--- FAIL: TestTCPReadWriteMallocs-16 (0.02s)
	tcp_test.go:531: Got 1 allocs, want 0
--- FAIL: TestTCPReadWriteMallocs-32 (0.02s)
	tcp_test.go:531: Got 1 allocs, want 0
FAIL

not tested on all platforms yet, but freebsd and linux work fine.

% hg id
920cde0a8b2d+ tip

% uname -a
Darwin airborne.local 13.4.0 Darwin Kernel Version 13.4.0: Sun Aug 17 19:50:11 PDT 2014;
root:xnu-2422.115.4~1/RELEASE_X86_64 x86_64</pre>

**Comment by mikioh** [comment]
Closed by https://github.com/golang/go/commit/77a2113925b516c0ead2ae258c4d41ac3fdc0836.

**Comment by josharian** [comment]
This still breaks on my OS X machine.

It is an intermittent failure, but it happens enough to be frustrating. Anecdotally, it happens more when running all.bash or the full net tests than just the lone test. I am in Portugal at the moment with flaky internet connections; it is possible that the failures are correlated to internet problems, although I have been unable to pin it down. I have also been unable to reproduce this with the test converted to a benchmark (I was hoping to use -memprofile to point to the source of the allocations).

I'm running 10.10.2 (14C109) with the pprof-enabling kernel patch.

If you have suggestions for other things to try to diagnose this, I'm happy to help.

**Comment by mikioh** [comment]
> with the pprof-enabling kernel patch.

ugh...

**Comment by josharian** [comment]
Yes, that one. Can't live without it, I'm afraid.

**Comment by josharian** [comment]
This is driving me crazy. Sending a CL to disable for now.

**Comment by bradfitz** [comment]
I'm also going to disable Dragonfly. Probably related.

**Comment by josharian** [comment]
I managed to get a stack trace, and I think I have a diagnosis.

Under some network conditions (I don't understand which), the `SYS_READ` syscall in [`syscall.read`](https://github.com/golang/go/blob/master/src/syscall/zsyscall_darwin_amd64.go#L970) fills the buffer and sets `e1` to `35` (`EAGAIN`). `35` is converted to an `error` [a few lines down](https://github.com/golang/go/blob/master/src/syscall/zsyscall_darwin_amd64.go#L973), which allocates. The error is passed up to `io.ReadFull` via `io.ReadAtLeast`. Both calls explicitly document that they return a `nil` error iff the buffer is not full. In this case, the buffer gets filled on the first request, so the error from `syscall.read` gets swallowed. As a result, the `t.Fatal` is not triggered, so we never actually *saw* the `EAGAIN` in the test results.

It's not obvious to me what the right fix is. Perhaps we should ignore `EAGAIN` in `syscall.read` if we have a full buffer? I also don't know whether this a complete diagnosis.

Incidentally, this has nothing to do with the kernel patch. The patch is extremely narrow in scope and concerned with the handling of profiling signals, which are not even in use when this test fails.

**Comment by bradfitz** [comment]
https://go-review.googlesource.com/6701

**Comment by mikioh** [comment]
@josharian,

Thanks for the investigation. I now understand that some additional stuff (e.g., pprof_mac_fix) or environment condition to the kernel can easily shake scheduling for uio_vectors and make EAGAIN notifications. That means that assuming netpoll hotpaths sail on calm sea during test is pretty naive. Perhaps permitting netpoll hotpaths allocate a few stuff in TestReadWriteAllocs might make sense.

**Comment by mikioh** [comment]
> permitting...

either applying change 6701 or permitting...
