### ISSUE TITLE
runtime: runtime.h suggests .goc files and goc2c, they no longer exist.

### ISSUE THREAD

**Issue by wathiede** [golang/go#8866]
<pre>runtime.h on tip @ 21314:8f36a32a9d03 has a large comment block for the FLUSH macro that
says the following.  It should be updated or removed as appropriate.

/*                                                                  
 * This macro is used when writing C functions                      
 * called as if they were Go functions.                             
 * Passed the address of a result before a return statement,        
 * it makes sure the result has been flushed to memory              
 * before the return.                                               
 *                                                                  
 * It is difficult to write such functions portably, because        
 * of the varying requirements on the alignment of the              
 * first output value. Almost all code should write such            
 * functions in .goc files, where goc2c (part of cmd/dist)          
 * can arrange the correct alignment for the target system.         
 * Goc2c also takes care of conveying to the garbage collector      
 * which parts of the argument list are inputs vs outputs.          
 *                                                                  
 * Therefore, do NOT use this macro if at all possible.             
 */                                                                 
#define FLUSH(x)    USED(x)</pre>

**Comment by minux** [comment]
runtime.h doesn't exist anymore.
