### ISSUE TITLE
runtime: split data/bss into 4K chunks for scanning

### ISSUE THREAD

**Issue by dvyukov** [golang/go#8888]
<pre>If we split data/bss into 4K chunks, then it will improve parallelization of scanning
and make it more incremental (something we need for concurrent GC with GOMAXPROCS=1).
I've done it once, but it was reverted during precision changes.
When we have 1-bit/word pointer info, it will be trivial to restore:
1. Calculate number of 4K chunks.
2. Adjust scanning parfor boundary accordingly.
3. If a thread's parfor iteration index is data/bss scanning, it finds the relevant
piece of data/bass and relevant piece of data/bss pointer info and scans only that piece.</pre>

**Comment by dvyukov** [comment]
This was fixed by d3df04cd8cf96db47d986cf3dcf3c7b2ba8238ea right? @aclements

**Comment by aclements** [comment]
Yep! Thanks for scrubbing these old issues.
