### ISSUE TITLE
runtime: replace span freelist with free bitmap

### ISSUE THREAD

**Issue by dvyukov** [golang/go#8894]
<pre>The slowest parts of mallocgc and sweeping are freelist manipulation.
The idea is to replace the freelist with bitmap of free blocks. For spans with objects
&gt;= 128 bytes, we allocate an additional word in MSpan for this; for spans &lt; 128
bytes, we reserve the necessary amount of words at the end of the span.

Here is a prototype CL:
<a href="https://golang.org/cl/113640043/">https://golang.org/cl/113640043/</a>

This has several advantages:
1. We always allocate in memory order.
2. We don't touch MSpan nor memory blocks themselves in mallocgc (freemap is cached in
MCache).
3. We don't touch blocks at all in MSpan_Sweep (only mark bits and free bitmap).
4. We don't work with linked lists in MSpan_Sweep.
5. We don't walk freelist in MSpan_Sweep to mark already free objects (bitmap set is
idempotent).</pre>

**Comment by randall77** [comment]
We now use bitmaps for allocation.
