### ISSUE TITLE
doc: ban data races from spec

### ISSUE THREAD

**Issue by dvyukov** [golang/go#8897]
<pre>We need to remove all guarantees with respect to data races from the language
specification, effectively leaving them as undefined behavior or at least
implementation-defined behavior (as there can potentially be a more secure
implementation that provides basic safety guarantees in presence of data races). Pretend
that it's bug fix wrt Go1 guarantee.
Two reasons:
1. Current implementations don't implement what's specified about data races in the
spec. Gcc and llvm middle-ends assume race-free programs.
2. Sapphire concurrent GC algorithm assumes race-free programs as well.
Fixing the implementations will incur extremely high cost.

Here is proposed wording:
<a href="https://golang.org/cl/101330056/diff/40001/doc/go_mem.html">https://golang.org/cl/101330056/diff/40001/doc/go_mem.html</a></pre>

**Comment by seankhliao** [comment]
I believe the go spec https://go.dev/ref/spec no longer mentions data races while the memory model documents the expectations of racy(?) programs https://go.dev/ref/mem
