### ISSUE TITLE
sort: sort package should provide implementations for all basic types

### ISSUE THREAD

**Issue by balshetzer** [golang/go#8905]
<pre>the sort package provides sorting for int, string and float64. It should also provide
the same boilerplate for int32, int64, uint32, uint64, etc. Otherwise, every project
ends up with the same repeated boilerplate.</pre>

**Comment by cristaloleg** [comment]
Probably case for generics #15292

**Comment by seankhliao** [comment]
see slices.sort https://pkg.go.dev/slices#Sort
