### ISSUE TITLE
net: TestReadFromTimeout is broken on plan9

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#8916]
<pre>new TestReadFromUDP is broken on nacl and plan9

<a href="http://build.golang.org/log/aac4062c5e6af228741d2ba7514c6fed329c2219">http://build.golang.org/log/aac4062c5e6af228741d2ba7514c6fed329c2219</a>

<a href="http://build.golang.org/log/26e95ec7041eca12a30036316d3a765ac8465c90">http://build.golang.org/log/26e95ec7041eca12a30036316d3a765ac8465c90</a>

Alex</pre>

**Comment by bcmills** [comment]
> BTW, Alex fixed this issue in CL [157820043](https://golang.org/cl/157820043).

Sounds like this issue should be closed, then?

**Comment by bcmills** [comment]
https://go.dev/cl/157820043 didn't affect `TestReadFromTimeout` at all as far as I can see, but I also don't see a `plan9` skip in `TestReadFromTimeout`. Closing as obsolete.
