### ISSUE TITLE
x/build/dashboard: repair perf builders

### ISSUE THREAD

**Issue by dvyukov** [golang/go#8930]
<pre>The perf builders don't benchmark older commits:
<a href="http://build.golang.org/perf?page=100">http://build.golang.org/perf?page=100</a>
and perf-todo requests from builders fail:
2014/10/14 12:54:05 datastore: query has no more results
2014/10/14 12:55:04 datastore: query has no more results
2014/10/14 12:55:34 datastore: query has no more results
2014/10/14 12:56:04 datastore: query has no more results
2014/10/14 12:56:35 datastore: query has no more results

Looking at the symptoms it seems that Commit.Num's were manually updated, so that now
(1) PerfTodo entities contain invalid nums and (2) association between Commits and
CommitRun's is broken and (3) Commit nums jumped to 100'000, which created a huge hole
in CommitRun's which negatively affects the graphs UI (one could argue that benchmark
commits contain holes due to branches anyway, but small holes are OK and 100'000 is like
25 years of team's activity).

All these 3 points need to be repaired.</pre>

**Comment by bradfitz** [comment]
I created #19871 to track the build coordinator changes.

**Comment by bradfitz** [comment]
The performance dashboard was rewritten and deployed, but then had problems and was ownerless and so was disabled and abandoned for the second time. Re-enabling it is now #20552.

Closing this one.
