### ISSUE TITLE
x/tools/cmd/vet: mark interfaces to have the correct type for verb %p

### ISSUE THREAD

**Issue by zimmski** [golang/go#8939]
<pre>Analyzing this program <a href="http://play.golang.org/p/aWILUB_GHi">http://play.golang.org/p/aWILUB_GHi</a> with vet, produces the
following problem

&gt; arg i for printf verb %p of wrong type: main.Foo

This occurs because the variable i is an interface and the function matchArgTypeInternal
in go.tools/cmd/vet/types.go does not mark interfaces as OK for the verb %p. I would
like to propose that this usage is not marked as a problem, since the program executes
without errors and prints the address to the interface.
(Which is also the same address printed by the verbs %#v and %+v using the example
code.) I can send a CL if you like but I wanted to confirm first that this is not
intentional since I could not find any documentation about it.

$ go version
&gt; go version go1.3.2 linux/amd64</pre>

**Comment by bradfitz** [comment]
@robpike, opinions on this?

I just got a CL to "fix" my formats from %p to %T to workaround this, but I had %p intentionally so I could line up interface values in my logs with leaked goroutine stack traces.

But I realize https://golang.org/pkg/fmt/ doesn't really define what %p means for an interface. Is it the second word of the interface value, assuming there's a pointer in there?

**Comment by bradfitz** [comment]
(the CL to fix my formats was https://go-review.googlesource.com/#/c/20002/)

**Comment by robpike** [comment]
This has been fixed by a flurry of recent changes. The playground example above now is silent when passed to vet.
