### ISSUE TITLE
cmd/cgo: crash when calling strtod on windows/amd64

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#8941]
<pre>Running this <a href="http://play.golang.org/p/wm5ADXs9KV">http://play.golang.org/p/wm5ADXs9KV</a> on windows/amd64 produces: 

C:\go\path\src\t&gt;go run foo.go
sizeof double is: 8
Exception 0xc0000005 0x1 0x0 0x7feff038ee7
PC=0x7feff038ee7
signal arrived during cgo execution

main._Cfunc_foo(0x0)
        command-line-arguments/_obj/_cgo_gotypes.go:24 +0x5e
main.main()
        C:/go/path/src/t/foo.go:36 +0x31

goroutine 2 [runnable]:
runtime.forcegchelper()
        c:/go/root/src/runtime/proc.go:90
runtime.goexit()
        c:/go/root/src/runtime/proc.c:1651

goroutine 3 [runnable]:
runtime.bgsweep()
        c:/go/root/src/runtime/mgc0.go:66
runtime.goexit()
        c:/go/root/src/runtime/proc.c:1651

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        c:/go/root/src/runtime/proc.c:1651

goroutine 4 [runnable]:
runtime.runfinq()
        c:/go/root/src/runtime/malloc.go:705
runtime.goexit()
        c:/go/root/src/runtime/proc.c:1651
rax     0x0
rbx     0x22fb98
rcx     0x7feea97e5720000
rdx     0x0
rdi     0x22fc38
rsi     0xffffffffffffffff
rbp     0x404147ae147ae148
rsp     0x22fb40
r8      0x22ef28
r9      0x0
r10     0x0
r11     0x22f550
r12     0x22fb90
r13     0x4a4e30
r14     0x51d596
r15     0x0
rip     0x7feff038ee7
rflags  0x7fe00010286
cs      0x33
fs      0x53
gs      0x2b
exit status 2

C:\go\path\src\t&gt;hg id -R %GOROOT%
284a98e61e32 tip

C:\go\path\src\t&gt;gcc --version
gcc (GCC) 4.9.1
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

The program runs fine on windows/386.

Alex</pre>

**Comment by alexbrainman** [comment]
I believe this is fixed now by latest @minux cmd/ld pe changes.

@minux I can make new test out of this for misc/cgo/test. Do we want that?

Alex

**Comment by minux** [comment]
I'm still surprised to see calling strtod requires atexit.
Yes, this should be fixed by external linking (#4069).

@alex.brainman, yes, adding a test would be good, but
note that every test in misc/cgo/test needs to pass
with both internal and external linking.

**Comment by alexbrainman** [comment]
I didn't know that. So were should I add this test? runtime?

Alex
