### ISSUE TITLE
reflect: Convert to unsafe.Pointer doesn't work

### ISSUE THREAD

**Issue by davidthomas426** [golang/go#8964]
<pre>If you have a reflect.Value that's a pointer, and you try to call its
&quot;Convert&quot; method with the reflect.Type representation of the unsafe.Pointer
type, you get the error &quot;panic: reflect.Value.Convert: value of type *int cannot be
converted to type unsafe.Pointer&quot;. That's wrong.

<a href="http://play.golang.org/p/ONG4bE_8iW">http://play.golang.org/p/ONG4bE_8iW</a></pre>

**Comment by randall77** [comment]
Implementing this is a security hole.  I don't think we can allow it.
With this feature, I can convert between pointer types without importing unsafe.

Example: http://play.golang.org/p/4Nz3ZoMWQ_

**Comment by randall77** [comment]
Note that you can always use

    unsafe.Pointer(rx.Pointer())

**Comment by rsc** [comment]
+1 to everything Keith said.
