### ISSUE TITLE
fmt: support printing reflect.Value directly

### ISSUE THREAD

**Issue by rsc** [golang/go#8965]
<pre>A reflect.Value obtained from an unexported field does not support .Interface().
If you hold such a value there is no way to pass it to fmt.Print to get the underlying
value printed.
(The usual way is fmt.Print(v.Interface()).)

Rog asks for a way to print such a reflect.Value. He has cited two unsafe packages that
do this by modifying the Value to remove the 'obtained from unexported field' bit.

Two possibilities.

1) Add a new type, in either reflect or fmt, that fmt recognizes and prints. 
For example, type RawValue struct { V reflect.Value }.

2) Make fmt recognize reflect.Value and print the underlying value instead
of printing the reflect.Value struct as it does today.</pre>

**Comment by robpike** [comment]
I don't understand the issue. This program prints 3.

package main

import (
	"fmt"
	"reflect"
)

type t struct { a int }

func main() {
	var x = t{3}
	fmt.Println(reflect.ValueOf(x.a).Interface())
}

**Comment by robpike** [comment]
This shows the problem:

package main

import (
	"fmt"
	"reflect"
)

type t struct{ a int }

func main() {
	var x = t{3}
	fmt.Println(reflect.ValueOf(x).Field(0).Interface())
}
