### ISSUE TITLE
x/tools/cmd/godoc: analysis mode is too hard/slow/fragile

### ISSUE THREAD

**Issue by bradfitz** [golang/go#8968]
<pre>I'm watching a friend trying to use godoc -analysis mode and it's apparent that there
are a few areas for improvement:

-- when a package has a parse error, just skip that package. Blake has $GOPATH=$HOME and
$HOME/src/** also has non-Go stuff, like Postgres. And Postgres has its own *.s files,
which aren't Go-style assembly. So godoc barfs.

-- analysis mode is too slow with a large GOPATH, and he has a large GOPATH. Our next
attempt was to make a new GOPATH just for godoc -analysis with symlinks to the subset of
packages we care about. But godoc and/or -analysis don't get along well with symlinks. 
So:

-- perhaps godoc needs its own -analysis-filter=[pattern] flag for a regexp or
comma-separated list of packages / globs (implicitly including all dependent packages
thereof).  e.g. --analysis-filter=foo.com/...,bar.com/baz,github.com/bradfitz/bar/...

-- log progress output in verbose mode? sometimes we think it's hung. Some reassuring
progress would be nice.

Thanks!</pre>

**Comment by adonovan** [comment]
Analysis support was dropped in CL 358954.
