### ISSUE TITLE
cmd/ld: no dwarf when using -linkmode=external on OS X

### ISSUE THREAD

**Issue by rsc** [golang/go#8973]
<pre>CL <a href="https://golang.org/cl/9025047">https://golang.org/cl/9025047</a> disabled dwarf generation when using
-linkmode=external on OS X:

changeset:   16733:3ac710a2ebf3
user:        Rob Pike &lt;r@golang.org&gt;
date:        Tue Apr 30 14:22:28 2013 -0700
files:       src/cmd/ld/dwarf.c
description:
cmd/ld: when linking externally, only generate dwarf info for ELF

R=golang-dev, iant
CC=golang-dev
<a href="https://golang.org/cl/9025047">https://golang.org/cl/9025047</a>

This makes lldb/gdb useless on Mac when using cgo outside the Go standard library.

Anyone remember why we did this?

Should look into undoing it for Go 1.4.</pre>

**Comment by josharian** [comment]
Possibly related: #5221.

**Comment by josharian** [comment]
CL 8661 was rolled back due to build breakage.
