### ISSUE TITLE
cmd/cgo: panic in main.(*Package).rewriteRef(0x1043c4d0, 0x1040a080)

### ISSUE THREAD

**Issue by davecheney** [golang/go#8980]
<pre>What steps will reproduce the problem?

On a linux/arm host

env CC=clang ./all.bash

What is the expected output? What do you see instead?

# os/user
os/user/lookup_unix.go:49:10: type C.struct_passwd: undefined C type 'struct passwd'
os/user/lookup_unix.go:50:14: type C.struct_passwd: undefined C type 'struct passwd'
os/user/lookup_unix.go:52:14: type C.long: undefined C type 'long'
os/user/lookup_unix.go:59:13: call of non-function C.sysconf
os/user/lookup_unix.go:59:23: unable to find value of constant C._SC_GETPW_R_SIZE_MAX
os/user/lookup_unix.go:64:9: call of non-function C.malloc
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x1d9ec]

goroutine 1 [running]:
main.(*Package).rewriteRef(0x1043c4d0, 0x1040a080)
        /home/dfc/go/src/cmd/cgo/gcc.go:610 +0xee4
main.(*Package).Translate(0x1043c4d0, 0x1040a080)
        /home/dfc/go/src/cmd/cgo/gcc.go:184 +0x188
main.main()
        /home/dfc/go/src/cmd/cgo/main.go:231 +0xf54

Please use labels and text to provide additional information.

dfc@qnap:~/go/src$ uname -a
Linux qnap 3.14-2-kirkwood #1 Debian 3.14.15-2 (2014-08-09) armv5tel GNU/Linux
dfc@qnap:~/go/src$ clang -v
Debian clang version 3.5.0-6 (tags/RELEASE_350/final) (based on LLVM 3.5.0)
Target: arm-unknown-linux-gnueabi
Thread model: posix
Found candidate GCC installation: /usr/bin/../lib/gcc/arm-linux-gnueabi/4.9
Found candidate GCC installation: /usr/bin/../lib/gcc/arm-linux-gnueabi/4.9.1
Found candidate GCC installation: /usr/lib/gcc/arm-linux-gnueabi/4.9
Found candidate GCC installation: /usr/lib/gcc/arm-linux-gnueabi/4.9.1
Selected GCC installation: /usr/bin/../lib/gcc/arm-linux-gnueabi/4.9
Candidate multilib: .;@m32
Selected multilib: .;@m32

dfc@qnap:~/go/src$ hg parents
changeset:   21552:66a91d217fcb
tag:         tip
user:        Dave Cheney &lt;dave@cheney.net&gt;
date:        Wed Oct 22 12:30:15 2014 +1100
summary:     runtime/cgo: encode BLX directly, fixes one clang build error on arm</pre>

**Comment by ianlancetaylor** [comment]
@davecheney Can you see if http://golang.org/11222 fixes the problem?  It looks right to me but I have no way to test it.

**Comment by davecheney** [comment]
@ianlancetaylor i'll take a look, it might take some time, that machine has been turned off and packed away.

**Comment by ianlancetaylor** [comment]
I guess anybody with an ARM GNU/Linux system could try it.

**Comment by davecheney** [comment]
I'll try tonight, but I ended up uninstalling clang from all my hosts a
while back, so I need to fix that.

**Comment by davecheney** [comment]
@ianlancetaylor 

sorry, doesn't look like it's fixed

```
# net
net/cgo_linux.go:20:26: unable to find value of constant C.AI_CANONNAME
net/cgo_linux.go:20:43: unable to find value of constant C.AI_V4MAPPED
net/cgo_linux.go:20:59: unable to find value of constant C.AI_ALL
net/internal/socktest
os/signal
os/user
# os/user
os/user/lookup_unix.go:55:10: type C.struct_passwd: undefined C type 'struct passwd'
os/user/lookup_unix.go:56:14: type C.struct_passwd: undefined C type 'struct passwd'
os/user/lookup_unix.go:58:14: type C.long: undefined C type 'long'
os/user/lookup_unix.go:65:13: call of non-function C.sysconf
os/user/lookup_unix.go:65:23: unable to find value of constant C._SC_GETPW_R_SIZE_MAX
os/user/lookup_unix.go:70:9: call of non-function C.malloc
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x1cd8c]

goroutine 1 [running]:
main.(*Package).rewriteRef(0x10566000, 0x10548100)
        /root/go/src/cmd/cgo/gcc.go:600 +0x102c
main.(*Package).Translate(0x10566000, 0x10548100)
        /root/go/src/cmd/cgo/gcc.go:170 +0x174
main.main()
        /root/go/src/cmd/cgo/main.go:241 +0xe98
```

**Comment by ianlancetaylor** [comment]
@davecheney Thanks for testing.  That is bizarre.  With the CL applied I could certainly expect other problems, but I can't understand how you are seeing the same problems.

I don't suppose the system is available for ssh?

**Comment by ianlancetaylor** [comment]
@davecheney I bet you just tried to rebuild os/user rather than running all.bash.  I see that too.  The patch is to cmd/cgo, though, so you need to "go install cmd/go" before trying to rebuild os/user.

**Comment by davecheney** [comment]
This was running

env CC=clang ./all.bash

I'll try to get you SSH to this host. Pls email me a key

**Comment by ianlancetaylor** [comment]
Hmmm.  bradfitz got me onto an ARM GNU/Linux machine, all.bash failed without CL 11222, passed with it.  I only tested the most recent version of the CL, using clang-3.5.

I will send you an SSH key.

**Comment by davecheney** [comment]
Confirmed. Thanks Ian.
