### ISSUE TITLE
cmd/cgo: leading whitespace in generated files is noncanonical

### ISSUE THREAD

**Issue by adonovan** [golang/go#9019]
<pre>The output of cgo is not canonical according to gofmt, as it has an excessive number of
tabs preceding many source lines, notably the import paths (e.g. &quot;fmt&quot;) inside
the import block, as the example below shows.  I suspect this is related to
printer.SourcePos mode and //line directives.

For what it's worth, I believe this behaviour is at least somewhat nondeterministic (it
caused my mapreduce consistency checks to fail), although I haven't succeeded in
reproducing that locally.

Deleting the blank line between the two imports hides the bug.

% go version
go version devel +6d6fbf7dee5b Mon Oct 20 11:10:03 2014 -0700 linux/amd64
% cat blurgh.go 
package blurgh

import (
        &quot;blah&quot;

        &quot;foo&quot;
)

import &quot;C&quot;

var _ foo.Foo
var _ blah.Blah
% go tool cgo blurgh.go 
% cat -t _obj/blurgh.cgo1.go 
// Created by cgo - DO NOT EDIT

//line /home/adonovan/test/blurgh.go:1
package blurgh
//line /home/adonovan/test/blurgh.go:4

//line /home/adonovan/test/blurgh.go:3
import (
^I^I^I^I^I&quot;blah&quot;
//line /home/adonovan/test/blurgh.go:7

//line /home/adonovan/test/blurgh.go:6
^I&quot;foo&quot;
)
//line /home/adonovan/test/blurgh.go:12

//line /home/adonovan/test/blurgh.go:11
var _ foo.Foo
var _ blah.Blah</pre>

**Comment by rsc** [comment]
Nondeterministic output is bad and should be fixed.

But non-gofmt'ed output is not a problem. People who care can run gofmt. (The build system doesn't care and doesn't expose these outputs.)
