### ISSUE TITLE
net: compilation failure using clang on armv5

### ISSUE THREAD

**Issue by davecheney** [golang/go#9023]
<pre>What steps will reproduce the problem?

What is the expected output? What do you see instead?

% env CC=clang ./make.bash

runtime/cgo
net
# net
net/cgo_linux.go:14:25: type C.int: undefined C type 'int'
net/cgo_linux.go:21:9: unable to find value of constant C.AI_CANONNAME
net/cgo_linux.go:21:26: unable to find value of constant C.AI_V4MAPPED
net/cgo_linux.go:21:42: unable to find value of constant C.AI_ALL

Please use labels and text to provide additional information.

dfc@qnap:~/go/src$ uname -a
Linux qnap 3.14-2-kirkwood #1 Debian 3.14.15-2 (2014-08-09) armv5tel GNU/Linux
dfc@qnap:~/go/src$ clang -v
Debian clang version 3.5.0-6 (tags/RELEASE_350/final) (based on LLVM 3.5.0)
Target: arm-unknown-linux-gnueabi
Thread model: posix
Found candidate GCC installation: /usr/bin/../lib/gcc/arm-linux-gnueabi/4.9
Found candidate GCC installation: /usr/bin/../lib/gcc/arm-linux-gnueabi/4.9.1
Found candidate GCC installation: /usr/lib/gcc/arm-linux-gnueabi/4.9
Found candidate GCC installation: /usr/lib/gcc/arm-linux-gnueabi/4.9.1
Selected GCC installation: /usr/bin/../lib/gcc/arm-linux-gnueabi/4.9
Candidate multilib: .;@m32
Selected multilib: .;@m32</pre>

**Comment by bradfitz** [comment]
@davecheney, I assume this is still happening? I guess this is yet another builder configuration we're lacking. (but this feels like it's in the long tail of configs... no?)

**Comment by davecheney** [comment]
@bradfitz, i've dug out my arm5 builder. I'm going to test this now.

**Comment by davecheney** [comment]
My arm5 builder is in such a poor shape it cannot run programs reliably any more. I've removed the 1.5 milestone as there is no way to confirm this issue any more.

**Comment by ianlancetaylor** [comment]
I bet this is the same as #8980 .  Closing, but reopen if it can be reproduced.
