### ISSUE TITLE
cmd/gc: compiler must not accept p-notation floats in regular Go code

### ISSUE THREAD

**Issue by griesemer** [golang/go#9036]
<pre>gc accepts the p-notation for floating point numbers:

mantissa &quot;p&quot; exponent

such as 12p-2, etc.

<a href="http://play.golang.org/p/xOixorUxUD">http://play.golang.org/p/xOixorUxUD</a>

The spec doesn't mention them. gccgo and go/types don't support them.

a) we should either disallow them, or
b) we should support them with consistent syntax and document them.</pre>

**Comment by griesemer** [comment]
There are several related errors:

http://play.golang.org/p/VVK5tF24e2

- p exponent
- hex mantissa and p exponent
- hex mantissa and e exponent interpreted as int

**Comment by dr2chase** [comment]
What is this "export data"?  I've been trying to figure out the conditions under which 'p' and 'P' etc should not be rejected?

**Comment by minux** [comment]
The export data is what compiler read from already compiled Go packages.

They are mostly regular Go declarations with some extensions (hex float,
argument escape tagging, etc)

Open a Go .a file under pkg directory with a text editor and you will see.

**Comment by griesemer** [comment]
"Export data" is the textual (go-syntax like) representation of the package "objects" that are exported from the package. The export data of a package A is parsed when another package B imports A. The export data can be found in the object/archive file.

The p-format is used to read and write floating-point numbers quickly and accurately without the need to convert to a decimal exponent.

**Comment by josharian** [comment]
@dr2chase see also the go/internal/gcimporter package and cmd/compile/internal/gc/export.go
