### ISSUE TITLE
cmd/objdump: no support for ppc64{,le}

### ISSUE THREAD

**Issue by davecheney** [golang/go#9039]
<pre>What steps will reproduce the problem?

--- FAIL: TestObjDump (0.90s)
        objdump_test.go:56: go tool objdump /tmp/go-build428711172/cmd/objdump/_test/objdump.test: exit status 1
                objdump: reading /tmp/go-build428711172/cmd/objdump/_test/objdump.test: unknown architecture
--- FAIL: TestDisasm (0.94s)
        objdump_test.go:185: objdump fmthello.exe: exit status 1
                objdump: reading /tmp/TestObjDump069071063/hello.exe: unknown architecture
FAIL
exit status 1
FAIL    cmd/objdump     1.852s

What is the expected output? What do you see instead?

Please use labels and text to provide additional information.</pre>

**Comment by laboger** [comment]
I see this is marked Unplanned but has been marked and unmarked as being included in releases since Go1.5.  I agree it is not a high priority but Minux has already done most of the work so it would be nice to make it available for others to use.

**Comment by laboger** [comment]
Let me add that I've been using the code that Minux pointed me to (a long time ago) with some minor modifications and it is working for me.  If his code was put into golang.org/x/arch/ppc64 after changing the strings from power64 to ppc64, then there are just a few other minor changes to get objump and the testcase to work on ppc64x and I can finish those if necessary.  For now if it could be put into golang.org/x/arch (not sure if that is frozen too?) that would make it easier to use and the rest could be done later for Go 1.8.

**Comment by laboger** [comment]
What's the outlook for getting this into Go 1.8?

**Comment by dr2chase** [comment]
At least for the timing, the outlook for 1.8 is fine.

**Comment by minux** [comment]
I will get this done in the 1.8 cycle.

**Comment by laboger** [comment]
Is this still going to make Go 1.8?
