### ISSUE TITLE
cmd/go: -x flag does not produce executable output

### ISSUE THREAD

**Issue by davecheney** [golang/go#9052]
<pre>dfc@qnap:~$ go build -x os/user
WORK=/tmp/go-build337667835
mkdir -p $WORK/os/user/_obj/
mkdir -p $WORK/os/
cd /home/dfc/go/src/os/user
CGO_LDFLAGS=&quot;-g&quot; &quot;-O2&quot; /home/dfc/go/pkg/tool/linux_arm/cgo -objdir
$WORK/os/user/_obj/ -- -I $WORK/os/user/_obj/ lookup_unix.go
** SNIP *

The key is the assignment to CGO_LDFLAGS should be =&quot;-g -O2&quot;, but is
incorrectly '-g&quot;, &quot;-O2&quot; which will cause the shell to look for a command,
&quot;-O2&quot;

$ CGO_LDFLAGS=&quot;-g&quot; &quot;-O2&quot; /home/dfc/go/pkg/tool/linux_arm/cgo -objdir
$WORK/os/user/_obj/ -- -I $WORK/os/user/_obj/ lookup_unix.go
-bash: -O2: command not found</pre>

**Comment by rsc** [comment]
go build -x is not about producing an exact shell script. This kind of bug has been filed before (maybe about dist?), but of course it depends on the quoting rules of the shell and more. I'm not terribly inclined to try to shove those rules into cmd/go. If you want to use %q that's fine, but it still won't be shell input.

**Comment by bcmills** [comment]
[`TestExecBuildX`](https://github.com/golang/go/blob/cd06b2d00de0e62b26811b38530ffa29a0df4b1e/src/cmd/go/go_test.go#L5040-L5092) seems to verify that the output is, in fact, executable.

Was this issue fixed as part of #21427? If it is still reproducible, is there a small change we can make to `TestExecBuildX` to detect it?

(CC @hirochachacha)
