### ISSUE TITLE
spec: remove unnecessary syntax restrictions for method expressions to match compiler

### ISSUE THREAD

**Issue by griesemer** [golang/go#9060]
<pre>At the moment, method expressions must be of the form T.m or (*T).m . There's no good reason not to generalize the notation to T.m where T is any kind of type that has a method m. The
only options are the ones we already have, as well as unnamed interface types and struct
type embedding fields with methods.

These extra cases are largely academic but there's no real reason for the restriction;
it only adds complexity to the spec and requires extra checks in the compiler.

This would be a backward-compatible language change w/o impact to users. It would
simplify the spec. It simplifies the type-checker. It may simplify the rest of the
implementation.

See also <a href="https://golang.org/issue/8605">issue #8605</a>.</pre>

**Comment by griesemer** [comment]
It appears that both cmd/compile and go/types already accept code like this:
```
package main

func main() {
	(*struct{ error }).Error(nil)
}
```
Perhaps we just need to relax the spec.

**Comment by griesemer** [comment]
This requires more subtle changes in the spec than anticipated - simply removing the grammar in https://golang.org/ref/spec#Method_expressions and replacing MethodExpression with Type in Operand may do it, but then warrant more simplifications (regarding composite literals). Too subtle to squeeze in before 1.7. Still, would be nice to fix since cmd/compile and go/types seem to accept it effortlessly, and it's a clean generalization.

But esoteric and of no real use for now, so no urgency. Postponing again.

**Comment by mdempsky** [comment]
It's worth noting that because of type aliases, the formerly syntactically invalid code

    interface{f()}.f(nil)

can now equivalently be written

    type u = interface{f()}
    u.f(nil)

gccgo rejects the former, but accepts the latter. cmd/compile and go/types accept both.

Notably though, when `interface{f()}.f` is replaced with `(*struct{error}).Error`, gccgo still rejects both forms.

**Comment by griesemer** [comment]
Removing Go2 label. go/types and cmd/compile accept these forms (and have been accepting them for some time), so at this point this is really just about updating the spec to match the compilers. For the same reasons it's also not a language change.

**Comment by cznic** [comment]
@griesemer I don't know if/how it's related, but when I try the code from https://github.com/golang/go/issues/9060#issuecomment-220165301, having the note

> It appears that both cmd/compile and go/types already accept code like this:

in the [playground](https://play.golang.org/p/e1smaFBkvp) I get

```
go.(*struct { error }).Error: call to external function
main.main: relocation target go.(*struct { error }).Error not defined
main.main: undefined: "go.(*struct { error }).Error"
```

Tried also locally with `go version go1.9.1 linux/amd64` and the result is the same.

**Comment by cznic** [comment]
@griesemer Update: Nevermind, I found you've already reported this in #22444.
