### ISSUE TITLE
cmd/gc: reported expr in type error message is wrong

### ISSUE THREAD

**Issue by rsc** [golang/go#9076]
<pre><a href="http://play.golang.org/p/5yQsI8H97Q">http://play.golang.org/p/5yQsI8H97Q</a>

package main
import &quot;unsafe&quot;
const Hundred = 100
var _ int32 = 100/unsafe.Sizeof(int(0)) + 1
var _ int32 = Hundred/unsafe.Sizeof(int(0)) + 1

prog.go:4: cannot use 25 + 1 (type uintptr) as type int32 in assignment
prog.go:5: cannot use Hundred + 1 (type uintptr) as type int32 in assignment

The first error is correct insofar as it prints the right value. It would still be nicer
to print 100/unsafe.Sizeof(int(0)) but 25 isn't terrible.

The second error is incorrect. It should be Hundred/unsafe.Sizeof(int(0)) (or 25).</pre>

**Comment by paranoiacblack** [comment]
I migrated it as https://go-review.googlesource.com/#/c/1250/.
