### ISSUE TITLE
x/build/dashboard: make builders aware of golang.org/x/... sub-repo paths

### ISSUE THREAD

**Issue by adg** [golang/go#9079]
<pre>The build infrastructure uses old code.google.com paths everywhere in the infrastructure.
This needs to be fixed, but there are a few different strategies:

a) Do the full rename everywhere. This includes a potentially risky mass update of the
build dashboard datastore. The watcher tool will need to updated to use &quot;go
get&quot; to initially fetch repositories instead of &quot;hg clone&quot;. The builder
daemons would not need to be updated.

b) Leave the paths as-is in the dashboard datastore, but update the builder daemons to
rewrite the paths before checking out the code. This requires updating all the running
builders, but is the lowest risk approach.

c) Have the dashboard app use the new paths in all its communications with the builders
and watcher, but keep using the old paths in the datastore. This also requires updating
the watcher code. The risk here is that we don't catch all the cases and corrupt the
datastore by accidentally putting in references to the new paths. 

Approach &quot;a' is the hardest but least gross approach. &quot;c&quot; is also
difficult and also the most gross. &quot;b' is kinda gross but also low risk.

I might go ahead with plan B just to get 1.4 out the door, with a view to implementing
plan A further down the track.</pre>

**Comment by crawshaw** [comment]
I believe @adg fixed this by implementing sub-repo builds in the new buildlet infrastructure (see golang/build@234725beb).
