### ISSUE TITLE
x/tools/cmd/vet: vet gets confused between functions that take formatted input, and ones the look like the take formatted input.

### ISSUE THREAD

**Issue by davecheney** [golang/go#9080]
<pre>What steps will reproduce the problem?
1. <a href="http://play.golang.org/p/J3w7d-h4aJ">http://play.golang.org/p/J3w7d-h4aJ</a>
2. go tool vet $FILE

What is the expected output? What do you see instead?

expected: no warning

got:
lucky(~/src) % go tool vet main.go
main.go:20: constant 0 not a string in call to Logf

Please use labels and text to provide additional information.

Vet should probably ignore things that look like functions that take a format string if
the format string argument isn't a string.</pre>

**Comment by ALTree** [comment]
There's no warning in go1.8 for the linked program; also there's a test about this in vet:

https://github.com/golang/go/blob/master/src/cmd/vet/testdata/print.go#L240

So assuming this is fixed.

**Comment by shurcooL** [comment]
For posterity, it appears this was resolved as part of [CL 21023](https://golang.org/cl/21023).
