### ISSUE TITLE
cmd/compile: incorrect initialization order

### ISSUE THREAD

**Issue by paranoiacblack** [golang/go#9094]
<pre>$ cat incorrect_init.go
package main

var (
	a = p(&quot;a&quot;) + c + b
	b = p(&quot;b&quot;) + f()
	c = p(&quot;c&quot;) + f()
	d = p(&quot;d&quot;) + 3
)

func f() int {
     d++
     return d
}

func p(s string) int {
     println(s)
     return 0
}

func main() {
	println(a, b, c, d)
}

compiling and executing produces:

$ go run incorrect_init.go
d
c
b
a
9 5 4 5

But the correct order per the spec should be: d, b, c, a, with values 9, 4, 5, 5.

See: <a href="http://tip.golang.org/ref/spec#Package_initialization">http://tip.golang.org/ref/spec#Package_initialization</a></pre>

**Comment by rsc** [comment]
Is this different from #7692?

**Comment by paranoiacblack** [comment]
I don't really see how they are related. This issue is about the initialization order of global variables, which, given two variables with the same number of dependencies, should initialize them in source declaration order.

**Comment by griesemer** [comment]
@rsc @paranoiacblack They are not related. This is an actual bug. #7692 is about a feature request (Assignable is not implemented for go/types' Tuple types).

**Comment by rsc** [comment]
OK, so it is different from #7692. Is it different from #7962?

**Comment by paranoiacblack** [comment]
This appears to be a duplicate of #7962.

**Comment by griesemer** [comment]
@paranoiacblack agreed.
