### ISSUE TITLE
x/tools/go/loader: handle relative imports

### ISSUE THREAD

**Issue by adonovan** [golang/go#9117]
<pre>Currently go/loader looks for packages relative to $GOPATH and $GOROOT but it should
also allow paths relative to the current directory such as ./foo, and do so in a manner
consistent with the 'go' tool.

This is a subtle change because the name supplied by the user (./foo) may not match the
canonical import path (&quot;bar/foo&quot;) that is widely used as a map key, so we'll
need to audit and test the code thoroughly.

Do this after the 1.4 tree thaw.</pre>

**Comment by alandonovan** [comment]
Fixed along with vendoring changes.
