### ISSUE TITLE
x/benchmarks: no documentation

### ISSUE THREAD

**Issue by rsc** [golang/go#9131]
<pre>There is absolutely no documentation about how to run the benchmarks.
If you check out the golang.org/x/benchmarks repo, the README says basically
&quot;This is an empty repo. When you clone it to make a new repo, be sure to edit this
file to describe the new repo&quot;.

If you poke around and find out that the bench program is the one package main
and then build and run it, you get cryptic output and no idea how to move forward:

% ./bench
build,garbage,json,http
%

godoc bench
or
<a href="http://godoc.org/golang.org/x/benchmarks/bench">http://godoc.org/golang.org/x/benchmarks/bench</a>
have NOTHING.

This needs to be documented well. It is not documented at all right now.</pre>

**Comment by andrewaustin** [comment]
This seems like it should be closed. See: 
https://github.com/golang/benchmarks
https://godoc.org/golang.org/x/benchmarks/bench
https://github.com/golang/go/wiki/PerfDashboard

(Although, maybe the metric descriptions should be moved from the wiki into godoc or at least the readme?)

**Comment by ianlancetaylor** [comment]
I'm inclined to agree, but leaving for @rsc since he opened it.
