### ISSUE TITLE
net/http: docs show insufficient way to cleanup Response Body

### ISSUE THREAD

**Issue by bgentry** [golang/go#9134]
<pre>What does 'go version' print?

go version go1.4rc1 darwin/amd64

What steps reproduce the problem?
If possible, include a link to a program on play.golang.org.

1. View the docs at <a href="http://tip.golang.org/pkg/net/http/">http://tip.golang.org/pkg/net/http/</a>

What happened?

Docs show the following method for cleaning up response bodies:

resp, err := http.Get(&quot;<a href="http://example.com/&quot">http://example.com/&quot</a>;)
if err != nil {
	// handle error
}
defer resp.Body.Close()

What should have happened instead?

The method shown above does not handle the case where both resp and err are non-nil,
which was preserved for compatibility reasons in #3795. If the response was a redirect
and the CheckRedirect func returned an error, the http.Client will return both the
Response and an error. That response's Body would never be closed under the example
shown above, and its connection would leak.

Unfortunately, I suspect this compatibility fix has probably led to lots of potential
leaks in Go code in the wild. Since breaking Go 1 compatibility is not an option, the
docs for Go 1 should show people how to correctly clean up after responses without
leaking conns &amp; file descriptors.

Instead, the following should work and would not leak:

resp, err := http.Get(&quot;<a href="http://example.com/&quot">http://example.com/&quot</a>;)
if resp != nil {
	defer resp.Body.Close()
}
if err != nil {
	// handle error
}

Please provide any additional information below.</pre>

**Comment by odeke-em** [comment]
Dup of https://github.com/golang/go/issues/8633?

**Comment by bradfitz** [comment]
Yes, dup.
