### ISSUE TITLE
cmd/compile: race detector mishandles OBLOCK nodes

### ISSUE THREAD

**Issue by dvyukov** [golang/go#9137]
<pre>Factored from <a href="https://golang.org/issue/9136">https://golang.org/issue/9136</a>

I also have a simple program that fails with -race:

$ cat x.go
package main

import &quot;fmt&quot;

func main() {
	a := []string{&quot;a&quot;}
	i := 0
	a[i], a[len(a)-1], a = a[len(a)-1], &quot;&quot;, a[:len(a)-1]
	fmt.Println(a)
}

$ go run x.go
panic: runtime error: index out of range
...</pre>

**Comment by DanielMorsing** [comment]
The racewalk gets this as its input

BLOCK
. CALLFUNC writebarrierstring
. a[len(a)-1] = ""
. a = a[:len(a)-1]

Because the first op in the block is a CALLFUNC, the racewalk code assumes that it's a multi-valued return and puts the instrumentation after the block in order to not clobber the stack.

**Comment by dvyukov** [comment]
What if we explicitly mark OBLOCKs that copy out return values of a call with a special flag. And then specially handle only these blocks in racewalk rather than try to guess OBLOCK type by looking at the first node.
The offending blocks seem to be created only by ascompatte during walk. Maybe there are few other functions, but they must be findable by calls to arch.nodarg.

**Comment by DanielMorsing** [comment]
How about using rlist on the CALL* nodes? It's not used and it would remove the semantic conflation that the BLOCK node has right now.

**Comment by dvyukov** [comment]
This sounds equally good to me. The root cause of the issue is that OBLOCK guessing in racewalk. And your proposal also removes it.

**Comment by rsc** [comment]
See issue #8102. The handling of OBLOCK is just wrong in general. This is the second time. This needs to be fixed correctly. Again, see my comments on issue #8102.

**Comment by dvyukov** [comment]
Rewriting racewalk as SSA pass should fix this.

**Comment by rsc** [comment]
That's not a fix for Go 1.5. It needs to be fixed for Go 1.5.
