### ISSUE TITLE
cmd/gc: ./size_256.go:2618: internal compiler error: regfree: reg not allocated

### ISSUE THREAD

**Issue by xoba** [golang/go#9153]
<pre>1. What is a short input program that triggers the error?

this issue is for a large program, above a threshold size: see attached size_255.go for
a program right below the threshold that compiles and runs ok, see attached size_256.go
for a program right above the threshold that doesn't. 

2. What is the full compiler output?

mra@dxfce:~/ad$ go run size_256.go 
# command-line-arguments
./size_256.go:2618: internal compiler error: regfree: reg not allocated

3. What version of the compiler are you using?  (Run it with the -V flag.)

go version devel +d7d71f7d6f53 Thu Nov 20 09:35:22 2014 -0800 linux/amd64</pre>

Attachments:

1. <a href="https://storage.googleapis.com/go-attachment/9153/0/size_255.go">size_255.go</a> (147379 bytes)
1. <a href="https://storage.googleapis.com/go-attachment/9153/0/size_256.go">size_256.go</a> (147950 bytes)

**Comment by ALTree** [comment]
This seems to be no longer reproducible on tip. The following:

http://play.golang.org/p/ohMYT9nS4j

Prints ```1.157920892373162e+77```

```
go version devel +d9f6919 Sat May 9 04:23:47 2015 +0000 linux/amd64
```
