### ISSUE TITLE
database/sql: document allowed Scan conversions

### ISSUE THREAD

**Issue by dadkins** [golang/go#9157]
<pre>What does 'go version' print?

go version go1.3.3 darwin/amd64

What steps reproduce the problem?
If possible, include a link to a program on play.golang.org.

<a href="http://play.golang.org/p/mk7wJKtz4H">http://play.golang.org/p/mk7wJKtz4H</a>

What happened?

NullString.Scan didn't accept a time.Time value:

error: unsupported driver -&gt; Scan pair: time.Time -&gt; *string

What should have happened instead?

It should have converted the time.Time value into a string, just it does with any other
type that Scan accepts.

Please provide any additional information below.

The contract for Scanner says:

        // Scan assigns a value from a database driver.
        //
        // The src value will be of one of the following restricted
        // set of types:
        //
        //    int64
        //    float64
        //    bool
        //    []byte
        //    string
        //    time.Time
        //    nil - for NULL values
        //
        // An error should be returned if the value can not be stored
        // without loss of information.
        Scan(src interface{}) error

All of the other types work by formatting the values as strings. Given that time.Time
has a String() function, I would assume it would be handled as well.</pre>

**Comment by syst3mw0rm** [comment]
As mentioned by @johto, there will be `loss of information` while transforming `time.Time` to `string`. I think it is best to remove `time.Time` from the restricted set of src types `Scan(src interface{})` operates on.

Thoughts?

**Comment by rsc** [comment]
database/sql is really very light on docs.
It should be clearer about what works and what does not.
There should be a section about Scan conversions,
and that section can explain what the rules are.

That said, I don't think we should change NullString.
It is what it is, for better or worse.
Note that it is fairly straightforward to implement
a custom NullStringOrTime that picks off the 
"value has type time.Time" case and handles it as
desired and then delegates to NullString for the rest.

**Comment by dadkins** [comment]
It is easy to work around the problem, but it is also surprising (to me). The reason is that error says
error: unsupported driver -> Scan pair: time.Time -> *string
instead of something like
error: sql/driver: couldn't convert 5 into type bool
which is what you get run into a truly lossy conversion.

At the very least, the current behavior should be documented. But I don't think this behavior is correct and think we should fix.

It seems like a cop-out to use the loss of information rule as an excuse for not converting time.Time to a string. You can certainly encode a time, including its time zone, as a string without losing any information.

I would make the argument that time.Time should be converted to string because all of the other types mentioned in the Scanner interface are successfully converted into string. It is surprising that time.Time is not. It feels like an oversight, not an intentional decision.

In fact, are there are any Scanners in the standard library which handle time.Time?

The reason I bring this up is in the first place is that the only way to read a timestamp from a database using Scan is to know a columns contains a timestamp and provide a time.Time (or NullTime in libpq). Otherwise, it's straightforward to dump a table's contents into strings if you don't care. Instead, that's an error and you have to workaround the problem for times only. It's not like timestamps are a corner case of database either. They're very prevalent.
