### ISSUE TITLE
cmd/pprof: unexpectedly creates c:\pprof directory

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#9180]
<pre>C:\go\root\src\archive\zip&gt;hg id
ffe33f1f1f17

C:\go\root\src\archive\zip&gt;dir c:\pprof
 Volume in drive C has no label.
 Volume Serial Number is F483-CD2E

 Directory of c:\

File Not Found

C:\go\root\src\archive\zip&gt;go test -c &amp;&amp; zip.test.exe -test.v -test.run=none
-test.bench=.*  -test.cpuprofile test.prof &amp;&amp; go tool pprof zip.test.exe
test.prof
PASS
BenchmarkCompressedZipGarbage         20          53905905 ns/op          107272 B/op   
    153 allocs/op
BenchmarkZip64Test             3         401039100 ns/op
Entering interactive mode (type &quot;help&quot; for commands)
(pprof) quit

C:\go\root\src\archive\zip&gt;dir c:\pprof
 Volume in drive C has no label.
 Volume Serial Number is F483-CD2E

 Directory of c:\pprof

28/11/2014  09:41 AM    &lt;DIR&gt;          .
28/11/2014  09:41 AM    &lt;DIR&gt;          ..
               0 File(s)              0 bytes
               2 Dir(s)  113,372,999,680 bytes free

C:\go\root\src\archive\zip&gt;</pre>

**Comment by osocurioso** [comment]
Not entirely clear to me whether the orphan pprof directory is a feature or a bug, but here's a suggested fix in case it's supposed to be removed: https://go-review.googlesource.com/2972
