### ISSUE TITLE
cmd/gotype: cgo invalid composite literal 

### ISSUE THREAD

**Issue by nathany** [golang/go#9182]
<pre>What does 'go version' print?

go version devel +ffe33f1f1f17 Tue Nov 25 15:41:33 2014 +1100 darwin/amd64

~/src/golang.org/x/tools/cmd/gotype  
❯ hg log -l 1
changeset:   1265:1d18a854b8e1

What steps reproduce the problem?

Minimal test case (cgo.go):
<a href="http://play.golang.org/p/8rRtv04TN7">http://play.golang.org/p/8rRtv04TN7</a>

1. go run cgo.go (this works)
2. gotype cgo.go

What happened?

cgo.go:13:11: invalid composite literal type invalid type

What should have happened instead?

Ignore the error because gotypes doesn't know about C types.

Please provide any additional information below.

This error also pops up in other tools that use the tools/go/types package, such as
stringer:

❯ stringer -type point cgo.go
stringer: checking package: cgo.go:13:11: invalid composite literal type invalid type

This particular case wouldn't work anyway, but the error occurs even when running
stringer on other Go constants that happen to be in the same file.

<a href="http://play.golang.org/p/UlQDKWpuJE">http://play.golang.org/p/UlQDKWpuJE</a>

❯ stringer -type Color cgo.go</pre>

**Comment by griesemer** [comment]
Fixed with https://github.com/golang/tools/commit/4ad370efaa163bc6919068dba73f7f7344e03bc7 .
