### ISSUE TITLE
x/net/websocket: support DialTimeout

### ISSUE THREAD

**Issue by CSEMike** [golang/go#9198]
<pre>As with net.Dial, websocket should support a timeout during Dial.

Given the existing DialConfig, perhaps the timeout should be expressed there and used if
present, replacing Dial with DialTimeout:

  <a href="https://code.google.com/p/go/source/browse/websocket/client.go?repo=net#77">https://code.google.com/p/go/source/browse/websocket/client.go?repo=net#77</a></pre>

**Comment by CSEMike** [comment]
A Dialer seems preferable. As it is, there's no way to Dial a domain socket, which is another limitation I've hit.

Is there anyone who can approve a patch to add a Dialer to the Config?

**Comment by CSEMike** [comment]
Although, one can dial manually and pass the conn to NewClient, which seems a fine workaround. Perhaps a Dialer is not needed whatsoever.

**Comment by nightlyone** [comment]
I would prefer passing a net.Conn over using a Dialer too. Otherwise those clients are hard to use in tests.
