### ISSUE TITLE
cmd/go: inconsistency between 'go help test' and 'go test -h'

### ISSUE THREAD

**Issue by hyangah** [golang/go#9209]
<pre>'go help test' and 'go test -h' present different docs. 
Other go commands don't seem to exhibit such difference.
Is it intentional? If so, we need to make them mention each other. 

The output of 'go test -h' is what 'go help testflag' outputs btw.</pre>

**Comment by rsc** [comment]
I think the fix for #6576 in CL 14502065 was a mistake. The output for go test -h before that CL was incomplete in one way before the CL and now it is incomplete in a different way.

Probably the right thing to do for go test -h is to print *both* the help for test and for testflag.
