### ISSUE TITLE
crypto/rand: mutex around /dev/urandom is unnecessarily broad

### ISSUE THREAD

**Issue by eapache** [golang/go#9221]
(Possibly related to #7000)

We were trying to read concurrently (on Linux, go 1.3) from the Reader provided by crypto/rand, but were seeing a lot of unexpected contention. Taking a look at the implementation, it appears to take a mutex around the entire call just in order to protect the initialization step: https://github.com/golang/go/blob/master/src/crypto/rand/rand_unix.go#L51

This seems unnecessarily broad, since the underlying `Read` call itself should be safe to do concurrently. It would seem better to replace the mutex with a `sync.Once` which would allow concurrent reads, and also provide a fast path with an atomic op once the initialization is complete.

Thoughts?

**Comment by FiloSottile** [comment]
Fixed by https://go.dev/cl/390038.
