### ISSUE TITLE
test/chan/doubleselect.go: checkmark found unmarked object

### ISSUE THREAD

**Issue by minux** [golang/go#9225]
I happened on the new linux-amd64-temp2 builder:
http://build.golang.org/log/355e8149f2d9825f1f3125013516594ab48b1896

And then the same test failed again in the same way on the same builder:
http://build.golang.org/log/96f65e29bade691078d896dfa4661b3230f73ce6
```
# go run run.go -- chan/doubleselect.go
exit status 1
runtime:greyobject: checkmarks finds unexpected unmarked object obj=0xc208034280, mbits->bits=0x1 *mbits->bitp=0x89
runtime:greyobject Span: obj=0xc208034280 k=0x610401a s.start=0xc208034000 s.limit=0xc208036000 s.sizeclass=5 s.elemsize=64
 *(obj+0) = 0xc208000a20
 *(obj+8) = 0xc20801dcc4
 *(obj+16) = 0x0
 *(obj+24) = 0x0
 *(obj+32) = 0xc20801de70
fatal error: checkmark found unmarked object
```

However, I've run the same program for 300 times on linux/amd64 machine, and none of them is failing.

**Comment by rakyll** [comment]
Happened for `CC_FOR_TARGET=$NDK_ROOT/bin/arm-linux-androideabi-gcc GOOS=android GOARCH=arm GOARM=7 ./make.bash`

See https://registry.hub.docker.com/u/golang/mobile/build_id/32290/code/b6bkeghtevzgoeae8v9vhpp/

**Comment by RLH** [comment]
We are working on these bugs. Since they are non-deterministic concurrency
bugs we are building tools to help us. In fact it was one of these tools
that reported this error. This note is to just assure you that we are aware
of the issue and working hard on it.
