### ISSUE TITLE
doc: $GOPATH is opaque even if you find the doc

### ISSUE THREAD

**Issue by rsc** [golang/go#9228]
Rick and Austin both ran into problems with trying to set up $GOPATH. They both found https://golang.org/doc/code.html but it didn't help either of them. Perhaps the doc should start out more prescriptive and only _then_ move into the description of what a workspace is.

Also, the recipe given uses $HOME/go as $GOPATH, which is just about the worst possible suggestion, because it's where we tell people to check out Go trees in http://golang.org/doc/install/source. This doc should probably use $HOME/work. People will be able to figure out how to generalize to other values of 'work'.

It looks like all the necessary information _is_ in the doc, it's just too hard to find if you're skimming trying to solve a problem. Maybe there should be a short intro that hits the highlights:

(1) mkdir $HOME/work; export GOPATH=$HOME/work; export PATH=$GOPATH/bin:$PATH
(2) Your own work goes in $GOPATH/src/github.com/you/project. Your version control applies to that subdirectory tree, not to all of $GOPATH.

and then the rest of the doc can elaborate.

@adg @aclements @rlh

**Comment by adg** [comment]
I sent [a change](https://go-review.googlesource.com/5561) to add a Quick Start section to code.html.

**Comment by rsc** [comment]
Pending CL just needs to be finished.

**Comment by rsc** [comment]
ping @adg. can we get this in?
