### ISSUE TITLE
doc: The Go Memory Model : a channel example has a bug

### ISSUE THREAD

**Issue by hoonmin** [golang/go#9235]
Hi. Following the go_mem documentation I found  a bug in a channel example.

```go
var limit = make(chan int, 3)

func main() {
	for _, w := range work {
		go func() {
			limit <- 1
			w() // not guaranteed to run their own function.
			<-limit
		}()
	}
	select{}
}
```

I know this is just a realistic pseudo-code, but it would be better to fix this for the beginners like me :-)
So I suggest:

```go
var limit = make(chan int, 3)

func main() {
	for _, w := range work {
		go func(worker func()) {
			limit <- 1
			worker()
			<-limit
		}(w)
	}
	select{}
}
```

**Comment by minux** [comment]
It has been a long time since the issue opened, I will go ahead
and send a CL. https://golang.org/cl/7602.
