### ISSUE TITLE
syscall: cannot call Win32 API functions that spawn new threads

### ISSUE THREAD

**Issue by dgolub** [golang/go#9240]
It is not possible to call Win32 API functions that spawn new threads because the callback wrapper generated by `syscall.NewCallback` does not perform the needed steps to set up the call stack as needed by the Go runtime for a new thread.  Attempting to call such functions will cause the new thread to hang forever.  This can be easily reproduced with the following simple test program:

```
package main

import (
	"fmt"
	"syscall"
)

func ThreadProc(p uintptr) uintptr {
	fmt.Println("FOO")
	return 0
}

func main() {
	modkernel32 := syscall.MustLoadDLL("kernel32.dll")
	procCreateThread := modkernel32.MustFindProc("CreateThread")
	r1, _, _ := procCreateThread.Call(0, 0, syscall.NewCallback(ThreadProc), 0, 0, 0)
	h := syscall.Handle(r1)
	syscall.WaitForSingleObject(h, syscall.INFINITE)
	syscall.CloseHandle(h)
}
```

This will hang forever in Go.  Translating this program into C/C++ and compiling it with an adequate compiler such as Microsoft Visual C++ will give the expected output of printing `FOO` and terminating.

**Comment by rsc** [comment]
We actually do allow calls from non-Go-created threads, provided cgo is in use. We should probably assume cgo is in use all the time on Windows, since it effectively is.

**Comment by alexbrainman** [comment]
Dup of #6751.

Alex
