### ISSUE TITLE
git-codereview: doesn't work correctly on windows

### ISSUE THREAD

**Issue by mattn** [golang/go#9257]
Any files has not been uploaded.

https://go-review.googlesource.com/#/c/1352/

This should have three files in the commit.

https://go-review.googlesource.com/#/c/1354/

**Comment by alexbrainman** [comment]
@mattn what is the problem here? Is it still broken?

Alex

**Comment by mattn** [comment]
Seems to be solved (as far as you can see I send some windows patches)

**Comment by mattn** [comment]
In the time I filed this issue, I could push commit just like below.

* modify files.
* git change
* git push
