### ISSUE TITLE
x/mobile/cmd/gobind: go generate rules

### ISSUE THREAD

**Issue by crawshaw** [golang/go#9267]
Given gobind is run on a Go package, it seems sensible to invoke it now with go generate:

//go:generate gobind -lang=java -odir testpkg
//go:generate gobind -lang=go -odir testpkg

**Comment by hyangah** [comment]
I've added -output flag and converted the bind testpkg to use the go generate. However, as thinking about objective-c gobind, I think -odir is a better option - allow to output multiple files (e.g., .h and .m files). What do you think, David? If you don't mind I will implement -odir and discourage (or remove) the use of -output flag.

**Comment by crawshaw** [comment]
I think multiple output files per package are unavoidable for objective-c. What about Swift?

**Comment by hyangah** [comment]
There is -outdir.
For swift, there is no concept of header file.
