### ISSUE TITLE
testing: allow creation of subtests

### ISSUE THREAD

**Issue by cflewis** [golang/go#9268]
**Problem**: When writing tests that take >3 minutes each, the tests should be parallelized. If your tests are also amenable to being written in a table-driven format, you have to resort to goroutines to make things parallel (rather than `t.Parallel()`). If you do that, then your logs get interleaved, and `go test run .*` can't help you out to isolate particular failures, and you lose the benefits of `t.Parallel()`, like setting number of parallel lines at CLI, ensuring non-parallel ones don't run with it...

**Solution**: A proposed solution discussed involves the ability for tests to create their own subtests.

**Comment by adg** [comment]
Closing in favor of #12166
