### ISSUE TITLE
review: add commit hook that transforms issue reference `#XXX` into `golang/go#XXX` in subrepos

### ISSUE THREAD

**Issue by minux** [golang/go#9273]
Migrated from #9254.

**Comment by adg** [comment]
I don't have a strong opinion.

**Comment by minux** [comment]
I really miss this feature.

Even though I'm perfect aware that I should use golang/go#XXXX
when sending changes for sub-repos, I still recognize the problem
only after I've pushed the CL. It's just to easy to write Fixes #XXXX
always.

And I also propose that we put it into the commit-msg hook so that
people using git directly will also benefit.
