### ISSUE TITLE
net/http: No easy way to get a server-side Request for testing.

### ISSUE THREAD

**Issue by bcmills** [golang/go#9276]
(net/http).Request is populated vastly differently on the client and server sides.
That's probably not fixable, given Go1 compatibility.

But it causes problems when testing http handlers - httptest.ResponseRecorder needs a Request to go with it, and the obvious candidate (http.NewRequest) generates the client-side version, not the server-side version.

You can get the server-side version by setting up an httptest.Server and making a request to it, but that involves a lot of boilerplate and some syscalls.

It would be nice if there were a way (in the http or httptest package) to get a Request in the server-side format without having to go through the whole HTTP stack with a real server.

**Comment by bradfitz** [comment]
Wait, isn't this just http://golang.org/pkg/net/http/#ReadRequest ?

**Comment by bcmills** [comment]
Maybe?  For some reason I thought that ReadRequest generated a client-side request rather than a server-side one.  Perhaps this is just a documentation issue.

**Comment by bradfitz** [comment]
Yeah, I'll clarify the docs.
