### ISSUE TITLE
x/review/git-codereview: support older version of git

### ISSUE THREAD

**Issue by minux** [golang/go#9283]
According to thishttp://opensource.apple.com/source/Git/Git-17/Git.plist,  the git on OS X might be as old as 1.7.4.4.

I know on OS X 10.8.5, git version shows:
```
git version 1.7.12.4 (Apple Git-37)
```

For exmaple, git-branch -q is introduced in https://github.com/git/git/commit/f9a482e62b079cdf9e80889011b6f41f3c17f0c2, which first appreas in 1.7.11. There might be OS X user with older version of git.

Because we still support OS X 10.6, ideally we should support the version of Git on 10.6.

The relevant golang-nuts question: https://groups.google.com/d/msg/golang-nuts/vKwVKAXdrWg/UzKRkQFwPycJ

**Comment by bradfitz** [comment]
I also hit this bug on the default Debian version on GCE (Wheezy), which includes git version 1.7.10.4. 

For others in that situation:

I added:
```
deb http://ftp.de.debian.org/debian wheezy-backports main
```
to /etc/apt/sources.list

And then ran:
```
sudo apt-get install git/wheezy-backports
```

**Comment by rsc** [comment]
There has not been much outcry for this in the past year. Let's just wait this one out.
