### ISSUE TITLE
x/review/git-codereview: detect when there is more than one pending change

### ISSUE THREAD

**Issue by rsc** [golang/go#9291]
Rick got burned by running 'git commit' instead of 'git change' and ending up in a branch with two commits. Then git mail helpfully pushed them both to Gerrit, which helpfully created two changes.

Something in the review tool should detect multiple commits and print an error and die.
Maybe git mail, or maybe something earlier.

Note that I am NOT saying people can't use the multiple commit mode of Gerrit, I'm just saying that the review tool isn't going to help them do that, at least not by default.

@adg

**Comment by cmarcelo** [comment]
After c3e5818734a979dd8168d10f722bfcdafe875ebb "git mail" complains if there are multiple pending CLs, and the user needs to explicitly pass the change to mail. It seems to cover the original issue (mail would ask which change, and the user could notice there are two), and permits pushing multiple commits (just pass the tip of the branch).

Should we close this?

**Comment by cmarcelo** [comment]
@rsc @adg ^
