### ISSUE TITLE
os/exec: data race between StdinPipe and Wait

### ISSUE THREAD

**Issue by CSEMike** [golang/go#9307]
I believe there is an unintentional race in os/exec between Command.Wait and file operations. I am using go version go1.3 linux/amd64, but the race also reproduces with 1.4

A test case follows.

    package main

    import (
      "fmt"
      "log"
      "os/exec"
    )

    func main() {
      cmd := exec.Command("/bin/echo")
      stdin, err := cmd.StdinPipe()
      if err != nil {
        log.Fatalf("StdinPipe: %v", err)
      }
      if err := cmd.Start(); err != nil {
        log.Fatalf("Start: %v", err)
      }
      wrote := make(chan bool)
      go func() {
        defer close(wrote)
        fmt.Fprint(stdin, "echo\n")
      }()
      if err := cmd.Wait(); err != nil {
        log.Fatalf("Wait: %v", err)
      }
      <-wrote
    }

To observe the race, save this program to racedemo.go, and run:

    go run -race racedemo.go

The result:

    WARNING: DATA RACE
    Read by goroutine 5:
      os.(*File).write()
          /usr/lib/google-golang/src/pkg/os/file_unix.go:211 +0xc5
      os.(*File).Write()
          /usr/lib/google-golang/src/pkg/os/file.go:139 +0xcb
      os/exec.(*closeOnce).Write()
          <autogenerated>:42 +0x81
      fmt.Fprint()
          /usr/lib/google-golang/src/pkg/fmt/print.go:223 +0xc3
      main.func·001()
          /usr/local/google/home/piatek/racedemo.go:21 +0x159

    Previous write by main goroutine:
      os.(*file).close()
          /usr/lib/google-golang/src/pkg/os/file_unix.go:108 +0x19b
      os.(*File).Close()
          /usr/lib/google-golang/src/pkg/os/file_unix.go:97 +0x94
      os/exec.(*closeOnce).close()
          /usr/lib/google-golang/src/pkg/os/exec/exec.go:442 +0x45
      os/exec.*closeOnce.(os/exec.close)·fm()
          /usr/lib/google-golang/src/pkg/os/exec/exec.go:437 +0x33
      sync.(*Once).Do()
          /usr/lib/google-golang/src/pkg/sync/once.go:40 +0xb1
      os/exec.(*closeOnce).Close()
          /usr/lib/google-golang/src/pkg/os/exec/exec.go:437 +0x8e
      os/exec.(*Cmd).closeDescriptors()
          /usr/lib/google-golang/src/pkg/os/exec/exec.go:222 +0xa2
      os/exec.(*Cmd).Wait()
          /usr/lib/google-golang/src/pkg/os/exec/exec.go:367 +0x45c
      main.main()
          /usr/local/google/home/piatek/racedemo.go:23 +0x316

    Goroutine 5 (running) created at:
      main.main()
          /usr/local/google/home/piatek/racedemo.go:22 +0x307

The race is on a reference to the file descriptor, which is assigned -1 upon close and read when writing. The documentation is not precise, but I suspect this race is unintentional.

The implementation of StdinPipe uses the internal closeOnce type to prevent concurrent calls to Close; see: http://golang.org/src/os/exec/exec.go#L436

Once wrapped, the file descriptor is added to the closeAfterWait slice, suggesting that concurrent calls to Close and Wait are to be expected. Yet, a concurrent Write will race as shown above. The partially concurrent API is odd.

I believe it is common for code to block on Wait in one goroutine while writing to StdinPipe from other goroutines. (Indeed, I found such a race in a library at Google, prompting my investigation.)

If this race is expected behavior, I suggest updating the package docs to mirror the warning for use of StdoutPipe, e.g., "It is incorrect to call Wait before all writes to the pipe have completed."

**Comment by rsc** [comment]
I think I'd argue this is a dup of #7970, although it's more troubling, because you can actually demonstrate it in a simple program.

**Comment by rsc** [comment]
Too late to fix for Go 1.6.

**Comment by mrkane27** [comment]
At present, is there any race-free way in Go to *execute a process, collect its error and output streams (I assume in goroutines to avoid filling pipe buffers), and finally wait for the process to terminate*?

**Comment by odeke-em** [comment]
For what it is worth, if this bug is blocking you, for a hot fix you can get around it by setting your own stdin before cmd.Start(). I ran into this bug two days back and it got me for about 18 hours until I realized that the race condition was caused because in `cmd.Wait()`, `cmd.closeDescriptors()` is invoked for the registered(internal) io.Pipe()s whenever you invoke cmd.StdinPipe(). The work around this is to assign a readCloser that you control and then close it on your own whenever you are done reading. Please see the patch below

```diff
--- orig.go	2016-02-11 03:44:56.000000000 -0800
+++ main.go	2016-02-11 03:44:57.000000000 -0800
@@ -2,23 +2,24 @@
 
 import (
 	"fmt"
+	"io"
 	"log"
 	"os/exec"
 )
 
 func main() {
 	cmd := exec.Command("/bin/echo")
-	stdin, err := cmd.StdinPipe()
-	if err != nil {
-		log.Fatalf("StdinPipe: %v", err)
-	}
+	pr, pw := io.Pipe()
+
+	cmd.Stdin = pr
 	if err := cmd.Start(); err != nil {
 		log.Fatalf("Start: %v", err)
 	}
 	wrote := make(chan bool)
 	go func() {
 		defer close(wrote)
-		fmt.Fprint(stdin, "echo\n")
+		fmt.Fprint(pw, "echo\n")
+		_ = pw.Close()
 	}()
 	if err := cmd.Wait(); err != nil {
 		log.Fatalf("Wait: %v", err)
```

**Comment by odeke-em** [comment]
Screencast here https://asciinema.org/a/f13lrd8pep3ohr9ha0exe0rwh

**Comment by adg** [comment]
Missed again.

**Comment by rsc** [comment]
We need to decide what to do here.

**Comment by rsc** [comment]
os/exec already guards against "implicit Close during cmd.Wait racing against user calling w.Close". The CL I just sent expands that to guard against "implicit Close during cmd.Wait racing against user calling w.Write".

There is still a race between w.Close and w.Write, like there is on any os.File. I'm not solving #7970, just the os/exec case.
