### ISSUE TITLE
runtime: shortage of contiguous virtual memory on Android L 

### ISSUE THREAD

**Issue by crawshaw** [golang/go#9311]
On 32-bit ARM, Go initially reserves a single block of 768 MB of virtual memory ([runtime/malloc1.go:146](https://github.com/golang/go/blob/master/src/runtime/malloc1.go#L146)). According to several reports, this fails in some L apps. It appears that the ART runtime in the same process reserves more than twice the -Xmx heap size in virtual memory.

A user inside Google with a working reproduction was about to modify the runtime to allocate an initial 512 MB block. This means we could switch to the alternate reservation scheme described in the malloc1.go comments and safely use smaller arena sizes.

The minimal change is to shrink the initial arena size to 256 MB. This seems reasonable for the Android apps I know of, but I am not sure how it would affect other 32-bit users.

**Comment by crawshaw** [comment]
This change (https://github.com/golang/go/commit/324f38a222cc48439a11a5545c85cb8614385987) is small (the diff is mostly indenting) and important to starting Go apps on android. Could this be considered for backporting to 1.4.1?

Right now people are working off tip, which isn't a good idea given the state of the GC. And I suspect it will become even less of an option during the compiler transition.

**Comment by ianlancetaylor** [comment]
You don't need to reopen the issue.  Simply adding the 1.4.1 milestone is enough for it to be considered for 1.4.1.  Most of the 1.4.1 issues are closed.

**Comment by rsc** [comment]
@crawshaw I will grudgingly take this for 1.4.1 but in the future please do not mix code cleanup like variable renamings into subtle semantic changes.

**Comment by rsc** [comment]
Doesn't apply cleanly (the Go source file edited in the commit was a C file in the release branch). Based on that and problems with the logging CL, I suggest posting github.com/crawshaw/go-android for people who want to follow along (or let them keep using 1.4).

**Comment by crawshaw** [comment]
Acknowledged. Apologies for the variable rename, it slipped in when I copied a file in the middle of the code review.
