### ISSUE TITLE
runtime: do not rely on a single bitmap for all Go heap?

### ISSUE THREAD

**Issue by minux** [golang/go#9313]
See also #9311 for Android L and #7284 for windows/386. This might also affect
the darwin/arm port, but so far my testing hasn't revealed anything (I think darwin/arm
kernel disallows memory overcommit, so it might poses problems for devices with
less than 1GB of physical memory)

For 32-bit ports, we probably want to support a scheme where there could be separate
bitmap for each large chunk of VM reservation.

Thoughts?

**Comment by rsc** [comment]
Let's just muddle along until we can stop worrying about 32-bit Android, iOS, or Windows.

**Comment by bradfitz** [comment]
iOS stopped allowing new 32-bit apps shortly after @rsc's last comment.

And as of ~yesterday, the new iOS beta says 32-bit apps won't even run on iOS anymore.

So, Android and Windows.

@eliasnaur, is this a problem in practice for you?

@aclements, you want to keep this open?

**Comment by aclements** [comment]
Since Go 1.7 we've been able to accept allocations anywhere in the 32-bit address space without the need for multiple bitmaps (actually, it was @eliasnaur who did that work), so think we can just close this.

Let me know if I've misunderstood the issue and we can reopen.
