### ISSUE TITLE
x/crypto/ssh/terminal: redundant line break when reaching end of line

### ISSUE THREAD

**Issue by songgao** [golang/go#9319]
I'm seeing a weird behavior when using `crypto/ssh/terminal`: when entering in a terminal connected to a `Terminal` in `crypto/ssh/terminal`, hitting the end of a line (last column of a row), an additional line break is automatically inserted, even when the client terminal already does wrapping.

The behavior does not exist in the `code.google.com/p/go/...` import, but is in `golang.org/x/crypto/ssh/terminal`. It seems that it's due to the `advanceCursor` function defined here: https://github.com/golang/crypto/blob/5ff91abc762244e802d98aa34c6c0d78f70791f3/ssh/terminal/terminal.go#L317, which seems to be a "feature" but unfortunately becomes a problem in some terminals (iTerm 2 on Mac, term.js in my case). A hacky workaround is to set the width to a ridiculously large integer, but that's barely an answer.

What terminal was that inserted line break addressing? Would it be possible to selectively turn off that feature, or auto detect client terminal type?

**Comment by shazow** [comment]
I'm not sure when this was fixed, but I can no longer reproduce this bug. 🎆

Perhaps https://github.com/golang/crypto/commit/95cb608f365d51e0e69abc646ec90c0e26fb427f#diff-a3a6cfbd4e71112ed97a68a606535a23 did the trick?

I suggest closing this issue unless someone can still reproduce it.
