### ISSUE TITLE
x/mobile/sensor: implement sensor library

### ISSUE THREAD

**Issue by crawshaw** [golang/go#9330]
Mobile devices have a range of common sensors:

- accelerometer
- gyroscope
- magnetometer
- barometer
- GPS / wifi location

We need a package golang.org/x/mobile/sensor to give us access to this data.

The challenging part here is, as always, designing an API that will work on both Android and iOS. This will require mapping the differences between sensor APIs on both platforms. There may be more than one Go package under the heading sensor.

As an added challenge, some of these sensors (in particular location) require app permissions to use. The permission models are different on android/iOS. I suspect we can design an API that does both: if a binary imports a particular sensor package, it will ask for the permission at installation time (that is, it will be baked into a generated AndroidManifest.xml file). When the package is used at run time, we ask iOS for permission.

**Comment by rakyll** [comment]
>  if a binary imports a particular sensor package, it will ask for the permission at installation time

We still need to handle the cases where user goes to the Settings and enables a service on iOS. Another idea is to have a high-level permissions handler which is basically a no-op on Android and logs a warning message.

**Comment by rakyll** [comment]
The major challenge in a common API is that iOS has async, Android has sync APIs.

iOS provides notifiers for location and network reachability and notifies the main thread (or another delegate) about the changes. Notifiers should be on iff the application requires the be updated with the current state of the things. Otherwise, it's a battery-life problem.

Even though permission models are different for the location APIs, we can always provide a noop implementation of the permissions dialog on Android and document that AndroidManifest needs to be updated. Additionally, iOS requires the app to provide a description text in info.plist to justify why it needs the user's location. There is much fragmentation when it comes to location :-/

I want to work on trivial cases such as accelerometer and gyroscope first.

**Comment by hyangah** [comment]
Doesn't Android also offer async api through listener? 
Anyhow, if possible, I'd like to have sync API which is more Go like.

Re: permission in AndroidManifest, is possible that the gomobile tool checks 
whether a certain censor package is imported (like openAL packaging) and 
generate/check AndroidManifest while building.

**Comment by rakyll** [comment]
LocationListener provides an async API, but I'd prefer we go for an synchronous API. 

We still can design location and networking info sources as notifiers that can be started and stopped and provide an API to read the latest known value.

``` go
n := location.Notifier{/* criteria */}
n.Start()
n.Value() // blocks until first value is retrieved
// or alternatively, you can use a handler
n.HandleFunc(func (v location.Value) {
   // ...
})
n.Stop()
```

**Comment by minux** [comment]
For locations, probably we do want an async API through channels though
because location result is not instantaneous, so even if we provide a sync
API, I guess most client programs will convert it to an async using
goroutine
anyway (because they might not want to block on a single type of events)

**Comment by rakyll** [comment]
> because location result is not instantaneous

Both platforms can report the last know location and the latency is low. We can always return nil if there is no known last known location. But the users will likely to be polling the notifier anyways in a separate goroutine not to block the main. That's why I agree that we should go async.

On the other hand, I'm not really sure about a channel based API. Because you want to consume the last known location again and again.

**Comment by rakyll** [comment]
@minux, if your suggestion is to have a sync last known location and additionally a channel of events, it SGTM.

**Comment by minux** [comment]
Yeah. I think that's the best of both worlds.

**Comment by rakyll** [comment]
Given this a second thought, having a mechanism that queues the events could be troubling. Users need to consume the channel to avoid the ever growing channel. A handler function is less "stressful", we're making sure that the event has been momentarily notified whether it's used or thrown away.

**Comment by minux** [comment]
we can use a leaking channel though.

loop: for {
  select {
  case ch <- value: break loop
  case _ = <- ch: continue loop
  }
}

This way, if the channel is buffered channel with cap=1, we can be
sure that no matter when does the client read, it will read the last
update or block waiting for an update.

However, I agree that we need to think about the big picture about
sensors and decide whether we want a callback based design (like
we did for touch events) or a channel based design. It's better to be
uniform. Besides location, is there any other sensor that doesn't
provide instantaneous update? heart rate?

**Comment by rakyll** [comment]
> It's better to be uniform.

Yes, totally agreed.

> Besides location, is there any other sensor that doesn't provide instantaneous update? heart rate?

All sensors both on Android and iOS have higher level async APIs. Sensor data is provided by an internal events queue on both platforms (you can directly consume it on Android). Higher level listener/notifier structs are fed by these queues. I was thinking of adopting async APIs for all our sensor data notifiers and directly depend on the higher level layer rather than consuming/filtering "raw" data.

**Comment by rakyll** [comment]
I've been experimenting with a naive accelerometer implementation last week.

```
func StartAccelerometer(fn func(deltaX, deltaY, deltaZ float64)) error
func StopAccelerometer()
```

The average number of samples I can get via calling ALooper_pollOnce on Android is 1-2 -- Go to C is also pretty expensive in this case :-/ We should target 10-20 samples per sec. As I was working on optimizations, I was able to talk to some game developers for feedback. They suggested me to the switch to a sync API and let most of the optimization to be done by the users in their frame loop.

A typical game looks like:
```
main() {
  for {
     // retrieve state
     // draw stuff
     // update other stuff
     // flush
  }
}
```
Giving them sync APIs allows them to sync the update rate of the accelerometer data with their frame rate, e.g. they can ask for new data at every n number of frames.

**Comment by minux** [comment]
On Mon, Mar 16, 2015 at 5:57 PM, Burcu Dogan <notifications@github.com>
wrote:

> They suggested me to the switch to a sync API and let most of the
> optimization to be done by the users in their frame loop.
>
> A typical game looks like:
>
> main() {
>   for {
>      // retrieve state
>      // draw stuff
>      // update other stuff
>      // flush
>   }
> }
>
> Giving them sync APIs allows them to sync the update rate of the
> accelerometer data with their frame rate, e.g. they can ask for new data at
> every n number of frames.
>
I think they've made an assumption that a sync API will return the result
instantaneously?

**Comment by rakyll** [comment]
> will return the result instantaneously?

for accelerometers and alike, it almost returns instantaneously if the sensor doesn't need to be waken up. We can always return nil, if there is no instantaneous data. The polling API shouldn't have to be blocking. The point is to allow the developers to sync their poll rate with their frame rate.

**Comment by crawshaw** [comment]
There's a non-typical use of terminology on golang.org/cl/7699 so just to make sure we are on the same page: interfaces can be broadly broken down into synchronous and asynchronous.

A synchronous interface can block and is safe to call repeatedly in a tight loop without wasting CPU.

An asynchronous interface will never block, and will waste CPU if called unchecked in a tight loop.

The difference does not need to appear in the method signatures. For example, the classic synchronous UNIX open/read/write/close system calls become asynchronous when you pass the O_NONBLOCK to open.

Asynchronous interfaces are much more work to use well, lead to much harder-to-read code, and leave the system in a state that is hard to debug from a stack trace when an error occurs. The only reason to use them is that threads are expensive in the C family of languages. When handling a large number of concurrent data streams, programs cannot afford a million system threads, with the associated stack space and kernel bookkeeping.

That's not a problem in Go. We have goroutines which map N:M onto system threads, and are cheap (and getting cheaper, we are down to 2kb initial stacks).

With this one limit removed, converting between the various flavors of interfaces: channels, iterator objects, etc, becomes cheap. Unless the resolution on the device sensors is higher than 10kHz I doubt performance is a concern in the interface design. Right now Apple devices have a maximum sensor resolution of 100Hz.

CL 7699 presents an argument for a non-blocking interface: to ease the development of a traditional game loop. I'm not convinced by this argument. What's proposed must be an asynchronous interface to be useful in such a game loop. That is, it returns what information is available and will not block. (It has a secondary problem: it forces allocations for reading from a data stream. Alternative designs can avoid that.)

I would like to see a blocking interface, and have designers of game loops who need an asynchronous view of events build it themselves in a separate goroutine and deliver it to their main loop. A blocking interface for events could take many forms:

    Get() Motion

or

    Read([]Motion) (n int, err error)

Independent of interface synchrony, there is a question of sampling. The only way to design an interface that both does not sample and does not have an infinite buffer is to register a callback. This would be equivalent to the Push model described in https://developer.apple.com/library/ios/documentation/EventHandling/Conceptual/EventHandlingiPhoneOS/motion_event_basics/motion_event_basics.html. I'd like to avoid callbacks if possible. As events are processed on an entirely separate ARM Cortex-M4 in modern phones, I don't believe perfect sensor reads under heavy loads is possible. With the potential to drop events, it simplifies the implementation of this and, at least on iOS, let's us make use of the system's underlying ring buffer. Programmers can dedicate a goroutine to reading events and have a high likelihood of reading them all.

Given that events may be dropped I would shy away from using a channel. Firstly, channels are usually lossless streams, so it is a confusing interface. Secondly, the interface would be trickier and more expensive, an extra goroutine would be needed inside the sensor package. I believe a Read function can avoid that.

**Comment by rakyll** [comment]
> I would like to see a blocking interface, and have designers of game loops who need an asynchronous view of events build it themselves in a separate goroutine and deliver it to their main loop.

On CL 7699, what I propose is a blocking interface at the cost of additional buffering on iOS. I am not suggesting the users to call `Read([]Motion) (n int, err error)` in their main loop. The necessity of blocking interfaces occurred to me when I wanted to fine-tune the reading rate according to my game loop's update rate. It shouldn't hint you that I want to read the events in the same goroutine. We had a sea of ideas above including returning nil if timeout occurs, but none of them are making it into the sensors package. Read the godoc, it says it will block.

As I mention above, the main concern is to give the developer a chance to optimize how much they want to block on the event queue. I want to give them blocking interfaces.

(Sorry for the terminology confusion, you should be able to s/sync/blocking throughout this thread.)

**Comment by rakyll** [comment]
There is a comprehensive document that summarizes some of the design goals and our approach for movement sensors on https://docs.google.com/document/d/1uZLObF0Ce7NZ6QAqE-jp9dai-rbs8Om4CUw-TmqyLJo/view.

https://github.com/golang/mobile/commit/4d47512510671417cc71fe6e5dfcf28c602a6748 and https://github.com/golang/mobile/commit/f48e3e4998da8edf5686c404b06a572e88990702 were related changes.

**Comment by rakyll** [comment]
The package lives under https://godoc.org/golang.org/x/mobile/exp/sensor.
