### ISSUE TITLE
runtime: -race allocates 2.8x VM in Go 1.4 vs Go 1.3.3

### ISSUE THREAD

**Issue by vito** [golang/go#9332]
We upgraded to 1.4 recently and noticed dramatically higher memory usage when using the -race flag.

The following table is the memory usage expressed in virtual and resident (as seen in htop), with and without -race:

go    | race        | no-race
-------|----|-----------------------
1.4 | `2236M` / `36352` | `418M` / `8576`
1.3.3 | `782M` / `24884` | `427M` / `8884`

Is this a side-effect of converting them automatically from C to Go? (as seen in 59e3e5354d7fbb896022eb5bf57e8ad850c42dd1).

We noticed this because tests started running out of memory and failing. Looks like the overall footprint is just much higher with `-race` than in 1.3.3 (which was also higher, but not as bad).

/cc @onsi @krishicks

**Comment by rsc** [comment]
@dvyukov, any ideas what might have changed wrt VM usage?

**Comment by dvyukov** [comment]
Tested locally.
With go1.4 the program fails the same way:
fork/exec /bin/ps: cannot allocate memory
With tip it prints:
dvyukov   5133 94.0  1.0 2951416 706384 pts/32 Sl+  10:32

I don't have 1.3, so taking the reported report:
root       550  0.1 20.5 5500216 1256116 pts/1 S<l  01:14

So, on tip memory consumption _dropped_ 2x as compared to 1.3.
We are not going to update race runtime in 1.4, so I am closing this.
