### ISSUE TITLE
cmd/go: invoke git without terminal, so it cannot ask for password

### ISSUE THREAD

**Issue by kokizzu** [golang/go#9341]
When doing `go get ...` if the repository has been renamed/deleted by the owner, the go get progress will stuck and asking for Username and Password (especially on `github`). It would be nice if `404` errors from repository would make `go get` skip current repository instead of asking username and password.

**Comment by rsc** [comment]
The options seem to be:

1) Don't fix this.

2) Take away git's connection to the terminal and tell people who want to use private GitHub accounts to put their GitHub credentials somewhere Git can get them non-interactively.

I'm okay with 2. What do other people think?

**Comment by kokizzu** [comment]
I'm ok with 2, as long it doesn't make the `go get ...` progress stuck XD

**Comment by josharian** [comment]
2 seems fine. I know we support older versions of git, but [git 2.3.0 introduced the `GIT_TERMINAL_PROMPT` environment variable to disable prompting for passwords](https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/2.3.0.txt). That'd make this a one-line fix.

**Comment by Thomasdezeeuw** [comment]
@josharian git on Windows is stil on version 1.9.5 so please support lower git versions in the fix :)

**Comment by rsc** [comment]
Thanks Josh. I will use that suggestion.

@Thomasdezeeuw, I'm sorry, but I have no idea how to fix
the go command's invocation of git for earlier versions.
Git is opening "CONIN$" and "CONOUT$" itself.
It is probably easiest just to suggest that people who
do run into this problem should update to a newer Git.

**Comment by nightlyone** [comment]
Wild guess: setting http://godoc.org/syscall#SysProcAttr.Noctty to true, doesn't help?

**Comment by Thomasdezeeuw** [comment]
Maybe add info to the docs and a link to this issue, since Git for Windows is still at 1.9.5 (https://git-scm.com/download/win, it autostarts a download)?

**Comment by RalphCorderoy** [comment]
This might be helpful. Code that's started using GIT_TERMINAL_PROMPT had other workarounds before, e.g. vim-plug took `https://github.com/junegunn/seoul256.vim.git` and inserted `git::@` to give `https://git::@github.com/junegunn/seoul256.vim.git`. See https://github.com/junegunn/vim-plug/wiki/faq#whats-the-deal-with-git-in-the-url
