### ISSUE TITLE
cmd/go: With Go 1.4, cannot statically link a program which imports net

### ISSUE THREAD

**Issue by glyn** [golang/go#9344]
In Go 1.3.x, it was possible to statically link a program which imports the net package. This is important when building programs for cut-down environments, for example busybox.

The problem can be reproduced on Ubuntu as [reported](https://groups.google.com/forum/#!msg/golang-nuts/S2WDcm47bhA/W243-l49WDsJ) by Vasiliy Tolstov:
```
package main 
import "net" 
func main() { 
        _, _ = net.ResolveIPAddr("ip", "google.com") 
} 
```
It is possible to statically link this program in Go 1.3.x by issuing:
```
CGO_ENABLED=0 go build -a -x
```
but with Go 1.4, the same technique creates the following runtime dependencies: 
```
linux-vdso.so.1 (0x00007fff603fe000) 
libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f3bd0608000) 
libc.so.6 => /lib64/libc.so.6 (0x00007f3bd0260000) 
/lib64/ld-linux-x86-64.so.2 (0x00007f3bd0825000) 
```

**Comment by glyn** [comment]
Fair enough.

**Comment by ianlancetaylor** [comment]
https://groups.google.com/d/msg/golang-dev/ajODMUyOhPI/l3Kh-hW3x5AJ

**Comment by ianlancetaylor** [comment]
Work around: use -installsuffix.

CGO_ENABLED=0 go build -a -installsuffix cgo

**Comment by ianlancetaylor** [comment]
I don't think we are going to do anything--using -installsuffix fixes the problem.

**Comment by DamnWidget** [comment]
Hi.

It should be well documented, thanks for the effort.

**Comment by dukedougal** [comment]
I'm really puzzled about this.  The primary reason I built my app was for static linking which I thought was the default behaviour and now I find that forever more I'll need to use what seems like a kludge to compile:

CGO_ENABLED=0 go build -a -installsuffix cgo -ldflags '-s' src/myapp/myapp.go

I'm using Go 1.5.1

**Comment by davecheney** [comment]
If you want static compilation always then I recommend installing Go from
source

env CGO_ENABLED=0 ./all.bash

That will disable cgo permanently.

**Comment by hongweiyi** [comment]
`CGO_ENABLED=0 go build -a -installsuffix cgo -ldflags '-s' src/myapp/myapp.go`

Go 1.5.1

LGTM
