### ISSUE TITLE
database/sql: permit tagged struct in Scanner

### ISSUE THREAD

**Issue by matejkramny** [golang/go#9347]
Hi all,

First of all, thank you for Go. Its Awesome!

I like the idea how `encoding/json` Marshals and Unmarshals json objects into structs..

One could define the database model like so:

```
type UserModel struct {
    Id int `db:"id"`
    Name string `db:"user_name"`
}
```

And when scanning rows from the database:

```
for rows.Next() {
    user := UserModel{}
    if err := rows.Scan(&user); err != nil {
        panic(err)
    }
}
```

What are your thoughts?

**Comment by rsc** [comment]
3rd-party packages to make nicer scanners seem like the best route here. I don't see a compelling reason to try to standardize this in database/sql itself, and worse I don't see one obvious design. There are many possibilities. Let people use what works for them instead of forcing one.

**Comment by mattn** [comment]
I'm thinking, time.Time should have simple scanner. Because when driver can't recognize type of the field value, driver must return string or []byte.
