### ISSUE TITLE
net: inconsistent documentation for Listen addrs.

### ISSUE THREAD

**Issue by bcmills** [golang/go#9351]
See http://golang.org/pkg/net/.

The example in the Overview section says:

    The Listen function creates servers:
    ln, err := net.Listen("tcp", ":8080")

The comment for `Listen` says:

    See Dial for the syntax of laddr.

The comment for `Dial` says:

    For TCP and UDP networks, addresses have the form host:port.

This contradicts the example in the Overview section, which elides the host.  Assuming the Overview example is correct, the comment for `Dial` comment should be updated to describe what happens if the host and/or port is omitted.

**Comment by mikioh** [comment]
Will fix this issue for Go 1.6, after deduplication of API surface code.

**Comment by rsc** [comment]
Fixed by ebf1f0f but I forgot to put the magic words in the CL description.
