### ISSUE TITLE
x/review/git-codereview: TestCurrentBranch fails

### ISSUE THREAD

**Issue by josharian** [golang/go#9379]
```
--- FAIL: TestCurrentBranch (0.17s)
	branch_test.go:13: on master
	branch_test.go:16: on newbranch
	branch_test.go:45: b.OriginBranch() = "master", want "origin/master"
	branch_test.go:20: making change
	branch_test.go:45: b.OriginBranch() = "master", want "origin/master"
	branch_test.go:25: on dev.branch
	branch_test.go:29: on newdev
	branch_test.go:33: making change
```

Reproduced with both git 1.8.5.3 and 2.2.0 on OS X. But build.golang.org says the review subrepo is passing, and no one else seems to have noticed.

I think that the failure is legit. I'll send a fix in a bit.

**Comment by rsc** [comment]
Can't reproduce this.

**Comment by josharian** [comment]
This still reproduces for me, now at `git version 2.8.3`. I'm going to send a CL commenting out the tests until we can figure out what the right fix is, because it's frustrating working on code with failing tests.
