### ISSUE TITLE
x/sys/unix: sendmsg does not permit sending multiple buffers

### ISSUE THREAD

**Issue by eapache** [golang/go#9402]
(I realize syscall has moved to its own repo as of 1.4, but that repo doesn't have a bug tracker so I assume this is still the right place to file such things, please correct me if I'm wrong.)

The unix `Sendmsg` and `SendmsgN` system calls permit passing in multiple buffers through the use of an io-vector structure, however the Go wrappers for these functions take only a single `[]byte` and hard-code the length of the io-vector to 1. It would be very useful for performance in some cases (such as https://github.com/Shopify/sarama/issues/238) if `Sendmsg` could be made to take a `[][]byte` and construct the equivalent io-vector.

**Comment by hgfischer** [comment]
👍

**Comment by minux** [comment]
We can't change the existing functions, but how about introducing this?
```
func SendmsgMultiple(fd int, p [][]byte, oob []byte, to Sockaddr, flags int) (n int, err error)
```

Any suggestions for a better name?

**Comment by ianlancetaylor** [comment]
GIven the existence of `net.Buffers`, perhaps we can do something along the lines of `SendmsgBuffers`.  Not that we should import "net", but we could add a `Buffers` type to x/sys/unix.  I'm not quite sure that makes sense, though.

**Comment by dpifke** [comment]
Superseded by https://github.com/golang/go/issues/52885?

**Comment by ianlancetaylor** [comment]
Yes, thanks.
