### ISSUE TITLE
gccgo: compiler crash building map of empty struct type

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#9406]
This file fails to compile with gccgo.  Looks like another zero-sized type problem.  This was actually reduced from a real program, though I have no idea why the program was written that way.

package p

type empty struct{}

func f() {
	em := empty{}
	v := map[struct{}]int{em: 0}
	_ = v
}

go1: internal compiler error: in fold_convert_loc, at fold-const.c:2337
0x82feda fold_convert_loc(unsigned int, tree_node*, tree_node*)
	../../trunk/gcc/fold-const.c:2337
0x63e346 Gcc_backend::constructor_expression(Btype*, std::vector<Bexpression*, std::allocator<Bexpression*> > const&, Location)
	../../trunk/gcc/go/go-gcc.cc:1675
0x62e011 Struct_construction_expression::do_get_backend(Translate_context*)
	../../trunk/gcc/go/gofrontend/expressions.cc:11902
0x62e933 Array_construction_expression::get_constructor(Translate_context*, Btype*)
	../../trunk/gcc/go/gofrontend/expressions.cc:12190
0x67be52 Temporary_statement::do_get_backend(Translate_context*)
	../../trunk/gcc/go/gofrontend/statements.cc:462
0x6503c5 Block::get_backend(Translate_context*)
	../../trunk/gcc/go/gofrontend/gogo.cc:5623
0x651bda Function::build(Gogo*, Named_object*)
	../../trunk/gcc/go/gofrontend/gogo.cc:5229
0x65303f Named_object::get_backend(Gogo*, std::vector<Bexpression*, std::allocator<Bexpression*> >&, std::vector<Btype*, std::allocator<Btype*> >&, std::vector<Bfunction*, std::allocator<Bfunction*> >&)
	../../trunk/gcc/go/gofrontend/gogo.cc:6941
0x659b53 Gogo::write_globals()
	../../trunk/gcc/go/gofrontend/gogo.cc:1281

**Comment by paranoiacblack** [comment]
Fixed by gcc.gnu.org/r219262.
