### ISSUE TITLE
tour: add a link to issue tracker

### ISSUE THREAD

**Issue by minux** [golang/go#9414]
I propose that we add a link to golang.org/issue somewhere on the
Go tour,  so that each translated version can customize that link and
make the issue reports go to the correct place.

**Comment by campoy** [comment]
Created change https://go-review.googlesource.com/8312, please review

**Comment by kytrinyx** [comment]
If I'm reading this right, then https://go-review.googlesource.com/#/c/8312/ was replaced with https://go-review.googlesource.com/#/c/8904/ -- which was merged... if that's correct, then this can be closed.

**Comment by adg** [comment]
Correct, thanks.
