### ISSUE TITLE
reflect: raise TestSelect timeout

### ISSUE THREAD

**Issue by randall77** [golang/go#9427]
Looks like TestSelect occasionally fails with an error, saying the select was taking forever.

TestSelect:

select {
0: nil Chan recv
1: zero Chan recv
2: nil Chan send
3: blocking send canselect
} blocked indefinitely
panic: select stuck

goroutine 38 [running]:
reflect_test.selectWatcher()
	/tmp/gobuilder/netbsd-386-minux-d11f41118116/go/src/reflect/all_test.go:1386 +0x19f
created by reflect_test.func·003
	/tmp/gobuilder/netbsd-386-minux-d11f41118116/go/src/reflect/all_test.go:1112 +0x2a

goroutine 1 [chan receive]:
testing.RunTests(0x824ffa0, 0x82cb940, 0x63, 0x63, 0x1)
	/usr/local/go/src/testing/testing.go:556 +0x8a0
testing.(*M).Run(0x18534330, 0x82c9ce0)
	/usr/local/go/src/testing/testing.go:485 +0x58
main.main()
	reflect/_test/_testmain.go:264 +0x171

goroutine 37 [runnable]:
reflect.rselect(0x18560d80, 0x4, 0x4, 0x1851a6b0, 0x58)
	/usr/local/go/src/runtime/select.go:623 +0xcc
reflect.Select(0x185687e0, 0x4, 0x4, 0x4, 0x0, 0x0, 0x0, 0x638b5653)
	/tmp/gobuilder/netbsd-386-minux-d11f41118116/go/src/reflect/value.go:1965 +0x1d1
reflect_test.runSelect(0x185687e0, 0x4, 0x4, 0x18542b40, 0x4, 0x4, 0x0, 0x0, 0x0, 0x0, ...)
	/tmp/gobuilder/netbsd-386-minux-d11f41118116/go/src/reflect/all_test.go:1409 +0x16b
reflect_test.TestSelect(0x1854cba0)
	/tmp/gobuilder/netbsd-386-minux-d11f41118116/go/src/reflect/all_test.go:1324 +0x2347
testing.tRunner(0x1854cba0, 0x82cbab4)
	/usr/local/go/src/testing/testing.go:447 +0xb1
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:555 +0x866
FAIL	reflect	6.208s

Recent occurrence Dec 22, 2014: http://build.golang.org/log/6607c61f735563b9c4f2aac3e098e1261d9289a6
Older occurrence Oct 23, 2014: http://webcache.googleusercontent.com/search?q=cache:GssgZyg7DF8J:build.golang.org/log/b0722fe3828188c8708c717ff3d7c826042f29f5+&cd=2&hl=en&ct=clnk&gl=us

Could it be that the timeout needs to be raised?  It is currently set to 1 second.

**Comment by rsc** [comment]
1 second is not enough.
It should back off or something.
