### ISSUE TITLE
net/http/httptest: "socket is not connected" error after starting httptest.NewServer

### ISSUE THREAD

**Issue by hannesroth** [golang/go#9430]
https://gist.github.com/hannesroth/dd9871ca6275fcb435aa

`ok  proof	0.241s`
`DONE`
`ok  proof	0.312s`
`DONE`
`ok  proof	0.419s`
`DONE`
`--- FAIL: Test559-8 (0.00s)`
`	proof_test.go:4037: write tcp 127.0.0.1:63671: socket is not connected`

`go version go1.4 darwin/amd64`
`Darwin ... 14.0.0 Darwin Kernel Version 14.0.0`

We found this when running lots of tests in parallel against our server implementation on our Mac machines. We are unable to reproduce it on a Linux (3.2.51, x86_64) machine.

**Comment by bradfitz** [comment]
Timeout. And I don't think there's anything actionable here.

We can reopen if anybody disagrees.
