### ISSUE TITLE
cmd/gc: more than one recursive type references causes segmentation fault

### ISSUE THREAD

**Issue by boynton** [golang/go#9432]
go version go1.4 darwin/amd64

This:

    type foo struct {
        bar foo
    }

produces the expected error message:

    invalid recursive type foo

But if more than one recursive reference is present:

    type foo struct {
        bar foo
        blah foo
    }

then it crashes, rather than reporting the error as expected:

   /usr/local/go/pkg/tool/darwin_amd64/6g: signal: segmentation fault

**Comment by minux** [comment]
This issue seems pretty popular, and as it's a compiler crash,
it doesn't have a meaningful workaround, and the fix is small
too, let's consider it for 1.4.2.

**Comment by ianlancetaylor** [comment]
Hmmm.  This is invalid code.  We don't usually put a fix for invalid code into a point release.  It doesn't fix the basic criteria of not having a workaround; the workaround is to fix the code.
