### ISSUE TITLE
encoding/csv: can not Analysis word[space],word

### ISSUE THREAD

**Issue by seefan** [golang/go#9440]
like this "RSCP[-75dbm,-70dbm)" ,"RSCP[-80dbm,-75dbm)"
There is a space in a comma before.
like this will be ok

file:encoding/csv/reader.go
line:289

r1, err = r.readRune()
//+++ 
for err==nil && unicode.IsSpace(r1) {
	r1, err = r.readRune()
}
//===
if err != nil || r1 == r.Comma {
	break Quoted
}

**Comment by rsc** [comment]
I believe this is working as intended. If a field is quoted it must be quoted in its entirety. Putting spaces around the comma puts spaces into the field, and it means the quote no longer appears at the end, so the field is not quoted.

See RFC 4180, bottom of page 2, for a grammar. It makes this very precise.
