### ISSUE TITLE
crypto/tls: remote error: handshake failure

### ISSUE THREAD

**Issue by webluoye** [golang/go#9446]
go version:1.4
connect to server with ssl  get error msg "remote error: handshake failure"

code:
ipConn, err := net.DialTCP("tcp", ladd, radd)
conn := tls.Client(ipConn, tlsconfig)
hsErr := conn.Handshake()

use openssl is ok
openssl s_client -connect ote1.dotasia.net:700 -cert certs/crt -key certs/key -showcerts -state

    Key-Arg   : None
    Krb5 Principal: None
    Start Time: 1419581515
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)

**Comment by quipo** [comment]
Reproducing script:

```go
package main

import (
	"crypto/tls"
	"fmt"
	"net"
)

func resolve(u string) {
	dialer := new(net.Dialer)
	rawConn, err := dialer.Dial("tcp", u)
	if err != nil {
		fmt.Println("failed to dial: ", err.Error())
		return
	}
	config := &tls.Config{InsecureSkipVerify: true}
	conn := tls.Client(rawConn, config)
	fmt.Println(u, conn.Handshake())
	conn.Close()
}

func main() {
	failingUrls := []string{
		"www.vineclient.com:443",
		"www.freespeech.org:443",
		"www.visa.go.kr:443",
		"pressroom.turner.com:443",
		"robertsspaceindustries.com:443",
	}
	for _, u := range failingUrls {
		resolve(u)
	}
}
```

**Comment by quipo** [comment]
Reproducing script using an http client directly:

```go
package main

import (
	"crypto/tls"
	"fmt"
	"net/http"
	"time"
)

func resolve(u string) {
	transport := &http.Transport{
		MaxIdleConnsPerHost: 250,
		TLSClientConfig: &tls.Config{
			InsecureSkipVerify: true,
		},
	}
	client := http.Client{
		Transport: transport,
		Timeout:   15 * time.Second,
	}

	fmt.Println(client.Get(u))
}

func main() {
	failingUrls := []string{
		"https://www.vineclient.com",
		"https://www.freespeech.org",
		"https://www.visa.go.kr",
		"https://pressroom.turner.com",
		"https://robertsspaceindustries.com",
	}
	for _, u := range failingUrls {
		resolve(u)
	}
}

```

**Comment by ebfe** [comment]
www.vineclient.com:443 seems to only accept TLS_DHE_* ciphersuites
pressroom.turner.com:443 seems to only accept TLS_RSA_WITH_RC4_128_MD5

These ciphersuites are not available in crypto/tls.

**Comment by bradfitz** [comment]
@agl, should crypto/tls return more details than just "remote error: handshake failure" ?

**Comment by agl** [comment]
"remote error: handshake failure" means that the peer sent us a numeric error code that means "handshake error". In this case we don't have any additional information to return even if we wanted to.

**Comment by rsc** [comment]
It doesn't sound like there's much we can do about this.
These servers don't like our client and they don't tell us why.
It's unfortunate.

**Comment by quipo** [comment]
well, the problem seems to be a difference in supported ciphersuites between the client and the server   (see [@ebfe's comment](https://github.com/golang/go/issues/9446#issuecomment-69060768) above).

It might get solved once the missing ciphersuites are available in crypto/tls.

**Comment by webluoye** [comment]
go 1.5 test ok
