### ISSUE TITLE
x/tools/cmd/stringer: does not honor build tags

### ISSUE THREAD

**Issue by ceralena** [golang/go#9449]
**What does 'go version' print?**

```
go version go1.4 linux/amd64
```

Additionally, `stringer` source is at this commit:

79d60d6e2ca483f3b11bf0022d3968a0a342a390

**What steps reproduce the problem?**

Create file A with `// +build foo` and file B with `// +build bar` which both declare a string like `const BANG = "hello"`.

Build the package.

**What happened?**

`go generate` failed like this:

```
stringer: checking package: sql_sqlite.go:39:2: INSERT redeclared in this block
src/$package/main.go:35: running "stringer": exit status 1 
```

**What should have happened instead?**

The files using build tags have nothing to do with the code using `//go:generate`, so I expect stringer to work as designed.

**Comment by robpike** [comment]
Not obvious it should or should not honor tags, but it needs to be thought about. There are arguments both ways.
