### ISSUE TITLE
fmt: inconsistent handling of \r in Scanf

### ISSUE THREAD

**Issue by astropanic** [golang/go#9459]
I got different ```fmt.Scanf``` behavior depending on the line endings style.

My go version is go1.3.3 darwin/amd64 on a Mac with OSX 10.10

To reproduce the problem, here is a short go program:

```
package main

import "fmt"

func main() {
	var steps, i int
	fmt.Scanf("%d", &steps)

	var a, b int
	for i = 0; i < steps; i++ {
		fmt.Scanf("%d", &a)
		fmt.Scanf("%d", &b)
		fmt.Println(a + b)
	}
}
```

And an input file

```
2
2 5
4           8
```

```go run test.go < input```

I expect to see regardless of the line endings been ```\r\n``` or ```\n```:

```
7
12
```

But I see

```
2
7
```

when in the input file the line endings are ```\r\n``` .

If the line endings are ```\n``` it works fine.

**Comment by robpike** [comment]
Working as intended, but the documentation needs to be improved.

**Comment by robpike** [comment]
There have been several fixes to fmt.Scanf in the recent flurry. Your example behaves consistently for me now if I rewrite it as follows, making sure the newlines appear in the format to match the input.

package main

import (
	"fmt"
	"strings"
)

func main() {
	do("2\r\n2 5\r\n4           8\r\n")
	do("2\n2 5\n4           8\n")
}

func do(s string) {
	file := strings.NewReader(s)
	var steps int
	fmt.Fscanf(file, "%d\n", &steps)
	fmt.Println("steps:", steps)

	var a, b int
	for i := 0; i < steps; i++ {
		a = -1
		b = -1
		n, err := fmt.Fscanf(file, "%d", &a)
		fmt.Println("first", n, err)
		n, err = fmt.Fscanf(file, "%d\n", &b)
		fmt.Println("second", n, err)
		fmt.Println(a, b, a+b)
	}
}
