### ISSUE TITLE
go/ssa/interp: breaks on reflect implementation of Go tip

### ISSUE THREAD

**Issue by rocky** [golang/go#9462]
Running ssadump on [this go program](http://play.golang.org/p/JHUgaI-2sq) produces a panic: 

    panic: interface conversion: interface is reflect.rtype, not *reflect.rtype

With go gc 1.4 on GNU/Linux there is none. 

The full invocation, output produced, and golang version is given in [this gist](https://gist.github.com/rocky/6f4f1955cdf8addaeb92). 

Looking at the Go code:

    u8 reflect.Type = reflect.TypeOf(uint8(0))
    byteSlice reflect.Type = reflect.SliceOf(u8)

I am just as confused as ssadump. Here is *reflect.SliceOf* in *reflect/type.go*:

    func SliceOf(t Type) Type {
    typ := t.(*rtype)
    ...

The ssadump error message makes sense to me in that the passed-in type is a `reflect.rtype`, not and `*reflect.rtype` which is what  appears to be the use in *reflect.SliceOf*. 

So what is it in Go that makes it okay to have these things not give a type error?

**Comment by rocky** [comment]
I'd like to implement next *func (v reflect.Value) Interface() (i interface{})*, but I don't see where in the SSA interpreter this would be done. Pointers?

**Comment by rocky** [comment]
Never mind. I see how to do this in externals.go. For example: "(*sync.Pool).Get".

**Comment by ceh** [comment]
Fixed by https://golang.org/cl/2145
