### ISSUE TITLE
blog: add post about example tests

### ISSUE THREAD

**Issue by speter** [golang/go#9471]
Godoc's support for displaying [example tests](http://golang.org/pkg/testing/#hdr-Examples) should be mentioned in either or both of:
http://godoc.org/golang.org/x/tools/cmd/godoc
http://blog.golang.org/godoc-documenting-go-code

**Comment by vdobler** [comment]
A link to http://golang.org/pkg/testing/#hdr-Examples in the last paragraph of cmd/godc should be sufficient.
Maybe a own blog post explaining examples in detail would be a good idea. The description in package testing is very terse some meta-examples would be helpful.

**Comment by speter** [comment]
Sent https://golang.org/cl/2490 for adding a link. Given that this is a distinguishing feature of Go, I agree that it would deserve a blog post, but I probably can't volunteer for writing that.

**Comment by rsc** [comment]
Seems worth a blog post?

**Comment by adg** [comment]
https://go-review.googlesource.com/9666

**Comment by adg** [comment]
http://blog.golang.org/examples
