### ISSUE TITLE
go/types: fails to report type error for ill-formed call 

### ISSUE THREAD

**Issue by alandonovan** [golang/go#9473]
package main
func f() (x, y []int)
var _ = append(f()...) // compile error: multiple-value f() in single-value context

In the program above, gc correctly reports a type error for the ill-formed call to append.
go/types does not.

**Comment by robpike** [comment]
I came here to say what I saw Ian has already said. The issue is the ..., and it should not apply to the second result like this. Gc is correct to reject this program.

**Comment by griesemer** [comment]
Fixed by https://github.com/golang/tools/commit/44ee65f5451d813b9795358b974e5798777f9e21 .
