### ISSUE TITLE
log: time zone in log prefix

### ISSUE THREAD

**Issue by rhysh** [golang/go#9483]
Package `log` can print out timestamps with the `Ldate`/`Ltime`/`Lmicroseconds` flags, but the time displayed is in local time without a time zone (http://play.golang.org/p/848Wa50X0d). The machines on which I run software don't always agree on the timezone (PST/PDT for laptop, UTC for server), which makes this output sometimes confusing.

Is there a way for the log lines to be unambiguous? Maybe
- Set the "Local" timezone of the entire process to "UTC"
- Add a flag to package `log` to force its timezone to "UTC"
- Add a flag to package `log` to print the timezone as part of the prefix

I'd like to see the third option, but I'm open to solutions that don't require changes to the stdlib. Thanks!

**Comment by timesking** [comment]
+1, It would be helpful
```
2015-03-17 17:58:57 +0800 [info]: adding source type="monitor_agent"
```

**Comment by nightlyone** [comment]
I would add two flags: One adding the numeric timezone AND one to log time in UTC.

UTC logging is very useful on its own to easily consolidate server logs across continents.

**Comment by tmtk75** [comment]
+1
