### ISSUE TITLE
cmd/api: run.go leaks temporary golang.org/x/tools checkout

### ISSUE THREAD

**Issue by davecheney** [golang/go#9490]
The api check in run.bash leaks one copy of golang,org/x/tools in /tmp for every run.

**Comment by bradfitz** [comment]
Are you sure?  It tries to keep exactly 1 and re-use it over itme.

Do you have more than 1?  (you might have the pre-git one as well, so maybe you have two).

**Comment by davecheney** [comment]
This blew up the -cheney-panda builder and was eating up /tmp on the -imx6
linux and nacl builder.

I didn't have time to fully investigate, just cleated the directories and
restarted the builders.

Consider this issue a note to myself to investigate further.

**Comment by minux** [comment]
Perhaps related leaking file issue: #9513

**Comment by rsc** [comment]
This will be fixed by not checking out x/tools anymore.

**Comment by rsc** [comment]
Dup of #10404.
