### ISSUE TITLE
builders: run builds in VMs in addition to containers

### ISSUE THREAD

**Issue by bradfitz** [golang/go#9492]
This bug is about the non-Linux (but still x86) part of http://golang.org/s/builderplan

The current build coordinator (x/tools/dashboard/coordinator) only runs builds in Docker containers. These are what https://github.com/golang/go/wiki/DashboardBuilders calls the "New-style" builders.

They're only Linux configs, though.

To run non-Linux OSes, we want to run VMs as well. This bug is about adding support to run builds in VMs on GCE (so x86 only)

The first part was recently done in https://go-review.googlesource.com/#/c/2180/ which added the buildlet. The buildlet runs on each VM (Windows, Plan 9, Open BSD, etc) and provides remote command execution and file extraction over HTTP.  This is the interface that the coordinator will then use instead of docker for VM-based builds.

Specific bugs have been filed for each operating system moving to this new scheme:

FreeBSD is #8639
OpenBSD is #8642 (furthest along)
Windows is #8640
Plan 9 is #9491

**Comment by minux** [comment]
What about NetBSD?

For ARM builders, I suggest we still use real hardware, because qemu system
can't
do perfect emulation yet. And if we care that much about speed, we can have
multiple
arm builder, each running parts of the tests. And we can even cross compile
the
toolchain for ARM on a beefy x86 host.
(The go code are building pretty fast even on ARM, but the C part are not.)

**Comment by bradfitz** [comment]
Yes, NetBSD, Solaris, etc. I just didn't list them all.

For ARM, let's move discussion to #8647

**Comment by bradfitz** [comment]
It's starting to work ...

Coordinator showing it's watching a buildlet on a VM it started:
![coord](https://cloud.githubusercontent.com/assets/2621/5601515/b66172a8-92b8-11e4-8803-58b4f8f23dc2.png)

And the VM for just that one build:
![alive](https://cloud.githubusercontent.com/assets/2621/5601514/96f94832-92b8-11e4-8643-9e32fa29a7ef.png)

**Comment by bradfitz** [comment]
The `openbsd-amd64-gce56` builder is now running.

It doesn't do subrepos yet, though. I will do that as part of fixing #8646 with @adg

**Comment by bradfitz** [comment]
NetBSD CL at https://go-review.googlesource.com/2612
