### ISSUE TITLE
command-line: Run go code directly from command line.

### ISSUE THREAD

**Issue by kalopsia** [golang/go#9497]
Hello to all. Thanks for this great project, I'm very pleased to say it, because this language like gulp of fresh air! So I want to ask, will go support executing code directly from command line/terminal (I think it is called REPL).

Something like this:

```
go run "package main; func main() { println('hello') }"
hello
```
or
```
go run --directly "println('hello')"
hello
```

or
```
go exec --interactive
> for {
> println("hello")
> }

hello
hello
...
```

**Comment by bradfitz** [comment]
@pcc and @alandonovan have worked or are working on Go REPLs and it would be nice, but it's never been a goal for the Go project.
