### ISSUE TITLE
condition cannot contain temporary struct construct

### ISSUE THREAD

**Issue by maruel** [golang/go#9502]
http://play.golang.org/p/EI4jfb093Z fails to compile:

--- CUT HERE ---
  package main
  import "fmt"
  type A struct {
  	b string
  }
  func main() {
  	a1 := A{"a1"}
  	a2 := A{"a2"}	
  	// Valid.
  	if a1 == a2 {
  		fmt.Println("Hello, playground 1")
  	}
  	// Invalid.
  	if a1 == A{"a2"} {
  		fmt.Println("Hello, playground 2")
  	}
  }
--- CUT HERE ---

In the context of trivial struct comparison, this forces the programmer to create a temporary named variable as done in the first condition above.

Error is:
prog.go:19: syntax error: unexpected { at end of statement
prog.go:22: syntax error: unexpected }

**Comment by bradfitz** [comment]
Long-time known and accepted issue. Use parenthesis in this case.

**Comment by minux** [comment]
FYI, http://golang.org/ref/spec#Composite_literals

A parsing ambiguity arises when a composite literal using the TypeName form
of the LiteralType appears as an operand between the keyword and the
opening brace of the block of an "if", "for", or "switch" statement, and
the composite literal is not enclosed in parentheses, square brackets, or
curly braces. In this rare case, the opening brace of the literal is
erroneously parsed as the one introducing the block of statements. To
resolve the ambiguity, the composite literal must appear within parentheses.
