### ISSUE TITLE
reflect: Value's == behavior changed between 1.3 and 1.4

### ISSUE THREAD

**Issue by hsinhoyeh** [golang/go#9504]
the following code snippet has different behavior when I run it on 1.3 and 1.4 respectively.
code are in https://play.golang.org/p/yfy7ZKqU1Y

when I run on 1.3, we have the following response:
```
false
0
0x0
true
```

while, It report false in the last println in golang 1.4
```
false
0
0x0
false
```

not sure whether it is a bug or something

**Comment by bradfitz** [comment]
I don't think you should use == on a reflect.Value.  Perhaps that just needs to be documented.

/cc @robpike, @randall77

**Comment by hsinhoyeh** [comment]
ok, then how to test the equality of reflect.Value instead of using "=="?
any suggestion?

**Comment by minux** [comment]
It's not a bug.

You shouldn't use == to compare two reflect.Value for equality.

The reason it's different is that starting from Go 1.4, interface values
will always
store a pointer, so is reflect.Value. Thus, although the two
reflect.Value's are
indeed storing the same integer, the struct itself are not equal (the ptr
field
are different)

**Comment by adg** [comment]
I think `v1.Interface() == v2.Interface()` will probably do what you want.

**Comment by minux** [comment]
And even on Go 1.3, types that can't be stored into interfaces inline will
exhibit the similar behavior (two reflect.Value's representing two equal
values are not equal).

https://play.golang.org/p/Dhe5Qm_vtH

**Comment by hsinhoyeh** [comment]
@minux you are right.
golang 1.4 always stores interface values into a pointer
https://github.com/golang/go/blob/release-branch.go1.4/src/reflect/value.go#L138
, whereas golang 1.3 does the separated things.

@adg thanks, Interface() can test this.
