### ISSUE TITLE
x/build/builders: coordinator and buildlet need to build subrepos

### ISSUE THREAD

**Issue by bradfitz** [golang/go#9506]
buildlet probably needs environment variable support in HTTP headers.  and returning a tarball of a directory. and extracting a tarball from a URL, rather than being fed it in a PUT.

coordinator needs to then get the subrepo lists from http://build.golang.org/?mode=json

**Comment by adg** [comment]
You can get the sub-repo list from
http://build.golang.org/packages?kind=subrepo

**Comment by bradfitz** [comment]
@adg, did you want to work on this?

We'll need to snapshot the "go" directory after make.{bash,bat,rc} and put it on GCS.  Probably in a new bucket.

And then when we need to build a subrepo, we instead untar the pre-built make output from GCS onto the buildlet, and then run just the subrepo tests.

Doing the snapshot after `make.bash` means we need to actually run make.bash separately, and not all.bash.  This ties in with the main repo test sharding later, wherein we'll snapshot after make.bash and then start N VMs over which to run all the tests. But for now you'll need to modify the coordinator to run `make.bash`, snapshot, and then `run.bash`

**Comment by adg** [comment]
Plans:

* Store builds in a GCS bucket called `go-build-tarballs`
* Name the tarballs `$HASH.$BUILDER.tar.gz`
* Overwrite existing tarballs; shouldn't happen except in weird circumstances where we re-trigger builds
* In `buildInVM` run `make.bash`, then simultaneously push the tarball to GCS and run `run.bash`.
* *checkpoint*
* Add subrepo revision discovery to the findWork loop (requires changes on the dashboard side)
* Add new `subrepo` and `subrepoRev` fields to `builderRev`  
* Pass a builderRev value through from the main loop to `startBuilding`, `startBuildingInVM`
* Add logic to `buildInVM` to do subrepo builds (fetch go tree tarball from gcs, fetch sub-repo tarball from gerrit, resolve any dependencies at master (the dashboard doesn't track transitive dependencies between subrepos unfortunately), run `go test`)

Issues to resolve:

* Garbage collection of old tarballs? Do we care? At, say, 50mb * 20 builders * 50 commits = 50gb/day. That's quite a lot.
  * How to manage gc? Hard to think of a means that doesn't track state somehow.

**Comment by nightlyone** [comment]
Garbage collection of tarballs could be done evaluating access logs. If not accessed for a long time, it is probably not interesting anymore (s. https://cloud.google.com/storage/docs/access-logs).

**Comment by adg** [comment]
Nice idea, but we aren't allowed to collect logs because "reasons" (am not
able to elaborate).

**Comment by minux** [comment]
The Go 1.5 code freeze is about to come, we should prioritize fixing this
as the more new builders we have, the less tested the sub-repos become.

**Comment by adg** [comment]
Working on it now.

**Comment by crawshaw** [comment]
@adg are you working on this? I'm interested in getting the mobile subrepository building. It needs a couple of custom hacks over the other subrepos to deal with cross-compilation, but they should be minimal on top of normal building, so I guess that should come first. If you don't have any code outstanding, I'm happy to take a crack at it.

**Comment by adg** [comment]
Yes I'm working on this with @bradfitz. We're close to getting the test
sharding code in; once that's in, I'll be in a good spot to tackle the
subrepo thing (and know pretty much how to do it).

What kind of hacks do you mean? You mean adding stuff to the buildlet base
images?

**Comment by crawshaw** [comment]
The hacks for mobile will be minimal environmental changes. It will probably be easier to understand on a CL. I'll wait for you get basic subrepos working and then send you something.

(Basically the go test golang.org/x/mobile/... needs to run on the host with the android/iOS device attached.)
