### ISSUE TITLE
x/mobile: loading webviewchromium after Go.init crashes on 5.0.1

### ISSUE THREAD

**Issue by dskinner** [golang/go#9507]
After `Go.init(this)`, attempting to call `PublisherAdView.loadAd` from `com.google.android.gms:play-services:6.5.87` causes crash on 5.0.1 but *not* previous 4.x versions of android. `PublisherAdView` uses a `WebView` to load ads.

Very little information is provided in logcat on crash

```
7911-7911/com.app I/WebViewFactory﹕ Loading com.google.android.webview version 37 (1602158-arm) (code 111201)
7911-7911/com.app I/LibraryLoader﹕ Loading: webviewchromium
7911-7911/com.app E/libsigchain﹕ Warning: Unexpected sigaction action found 0xaff5decc
7911-7911/com.app I/LibraryLoader﹕ Time to load native libraries: 4 ms (timestamps 3728-3732)
7911-7911/com.app I/LibraryLoader﹕ Expected native library version number "",actual native library version number ""
7911-7911/com.app V/WebViewChromiumFactoryProvider﹕ Binding Chromium to main looper Looper (main, tid 1) {2bc39a28}
7911-7911/com.app I/LibraryLoader﹕ Expected native library version number "",actual native library version number ""
7911-7911/com.app I/chromium﹕ [INFO:library_loader_hooks.cc(106)] Chromium logging enabled: level = 0, default verbosity = 0
7911-7911/com.app I/BrowserStartupController﹕ Initializing chromium process, renderers=0
7911-7911/com.app W/art﹕ Attempt to remove local handle scope entry from IRT, ignoring
7911-7911/com.app W/chromium﹕ [WARNING:resource_bundle.cc(315)] locale_file_path.empty()
7911-7911/com.app I/chromium﹕ [INFO:aw_browser_main_parts.cc(63)] Load from apk succesful, fd=54 off=46780 len=2953
7911-7911/com.app I/chromium﹕ [INFO:aw_browser_main_parts.cc(78)] Loading webviewchromium.pak from, fd:55 off:229484 len:643667
7911-8173/com.app W/AudioManagerAndroid﹕ Requires BLUETOOTH permission
7911-7911/com.app I/Ads﹕ Starting ad request.
8185-8185/? I/dex2oat﹕ /system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --instruction-set=arm --instruction-set-features=div --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --dex-file=/data/data/com.app/cache/ads1534321150.jar --oat-fd=86 --oat-location=/data/data/com.app/cache/ads1534321150.dex --runtime-arg -Xms64m --runtime-arg -Xmx512m
8185-8185/? I/dex2oat﹕ dex2oat took 82.342ms (threads: 2)
400-915/? I/WindowState﹕ WIN DEATH: Window{3d2a37ef u0 com.app/com.app.GridActivity}
130-130/? I/Zygote﹕ Process 7911 exited due to signal (11)
400-414/? I/ActivityManager﹕ Process com.app (pid 7911) has died
```

Notable is `E/libsigchain﹕ Warning: Unexpected sigaction action found 0xaff5decc` after webviewchromium loads native code, which is an error from the ART runtime: https://android.googlesource.com/platform/art/+/master/sigchainlib/sigchain.cc#161

I believe that's why 4.x is not affected.  I was *not* able to reproduce this issue with the sole use of a simple `WebView` loading a website.

I have found that allowing a single `PublisherAdView.load` call to complete successfully (to allow webviewchromium native code to load first) followed by `Go.init` does work successfully, including afterwards creating new ad views and more calls to `PublisherAdView.load`.

I'll put together a minimal sample soon.

**Comment by minux** [comment]
the ownership of signal handlers is going to be an issue when
mixing two runtimes (ART and Go).

**Comment by crawshaw** [comment]
I believe the basic signal forwarding added in https://golang.org/cl/8712 (5c8fbc6f1e4ba78133c53ce73f82ad10e81b42f8) takes care of this.

**Comment by dskinner** [comment]
I don't think this is resolve unless my issue is related to something separate. I'm still experiencing a crash that's the same as the original reported.

If a sample app would be helpful, I'd be happy to produce this based on the latest gomobile bits. I tested this against

golang: 32ad533813ffd084
gomobile:32ad533813ffd084a

producing an aar from such for inclusion in a project

**Comment by dskinner** [comment]
sorry, updating the original but go hash is: a81c6563525521a1165

**Comment by crawshaw** [comment]
If you can provide a failing program I'll take a look next week.

**Comment by dskinner** [comment]
ok, will do, as a heads up, the program will use RecyclerView to interlace PublisherAdView's in a stream of stories (such as slashdot) which should reproduce the issue.

**Comment by hyangah** [comment]
Looking into #12725, I guess this is related to misuse of the context. 
We no longer require the go.Go class. I am closing this issue. (obsolete)
