### ISSUE TITLE
math/big: ProbablyPrime accepts nonpositive integers as rounds count

### ISSUE THREAD

**Issue by ALTree** [golang/go#9509]
Even though only positive integers make sense, ProbablyPrime accepts null and negative integers for the "number of Miller-Rabin rounds" parameter, and happily output `true` (i.e prime) when given `n < 1`. 

```
package main

import "math/big"

func main() {
	n := new(big.Int)
	n.SetString("5041", 10) // 71 * 71
	println(n.ProbablyPrime(0)) // true
}
```
http://play.golang.org/p/vLwhlt3xsC

**Comment by griesemer** [comment]
Easy to add an extra test if that's desired and documentation is not good enough.

**Comment by ALTree** [comment]
Easy to patch but I'm not sure whether
- Leave the code, change documentation ("will [sometimes] return true with n < 1")
- Panic on n < 1
- Ignore the given n and set a custom nice value (i.e. 25) on n < 1

**Comment by griesemer** [comment]
I'd document that n _must_ be > 0 and panic with an appropriate message if it's not. That makes it clear and prevents surprises.

**Comment by minux** [comment]
Sent https://golang.org/cl/2313
