### ISSUE TITLE
build: drop support for OS X 10.6

### ISSUE THREAD

**Issue by adg** [golang/go#9511]
As discussed in #9495, it might be time to end our support for OS X 10.6.

I'm trying to find Apple's policy on supporting older versions of OS X, but it appears they haven't published anything publicly. (Which seems outrageous to me, but whatever.)

The major concern, I believe, is that OS X 10.6 is the newest version of OS X that runs on pre-EFI macs (or something?). I think @robpike actually has one of these old machines.

**Comment by josharian** [comment]
FWIW, I also have a very old 10.6 machine around that I still use. However, I would be happy to just use 1.4 in perpetuity on that machine.

**Comment by minux** [comment]
Having thought about this more, I think we probably should
announce the intention to remove support for 10.6 in Go 1.6
now, and make 1.5 the last version to support 10.6.

This will give 10.6 user enough time to migrate and also 1.5
is such a major leap. As 10.6 is supported now, supporting
it in 1.5 probably won't incur a lot of work for us.

**Comment by bradfitz** [comment]
This isn't like we're dropping some old Linux version that people might still have in production. This is dropping support for an ancient desktop Mac, where Go 1.4 would continue to work.

**Comment by minux** [comment]
I've sent an email to golang-nuts, let's see.

**Comment by landonbjones** [comment]
This list of security updates, http://support.apple.com/en-us/HT1222, shows that last one for OS X 10.6 was 12 Sept 2013.  It would be nice for Apple to say publicly that they are dropping support, but when there hasn't been a security update for over a year and known issues are out there I would consider support dropped.

**Comment by sdouche** [comment]
> I'm trying to find Apple's policy on supporting older versions of OS X, but it appears they haven't published anything publicly. (Which seems outrageous to me, but whatever.)

From [this link](https://security.berkeley.edu/content/my-mac-os-x-operating-system-supported):

```
Is my Mac OS X operating system supported?
Q. Where can I find information about operating systems supported by Apple?

A. Generally Apple does not officially acknowledge the end of support for Mac OS X
operating systems. Historically, Apple’s support has been limited to 2-3 recent
operating system releases. When Apple releases security updates for Mac OS,
operating systems with vulnerabilities that are no patched by Apple should be
considered unsupported and out of compliance with the Mininum Security
Standards for Network Devices (MSSND).

The current list of supported Mac OS X operating systems (as of 2014-10-30):

OS X 10.8 "Mountain Lion"
OS X 10.9 "Mavericks"
OS X 10.10 "Yosemite"
```

I'd say it's realistic to drop the N-5 version.

**Comment by bradfitz** [comment]
Speaking of which, can we drop support for 32-bit OS X builds too?  When was the last time Apple sold a 32-bit Mac?

Camlistore had to add a warning for Mac users because enough of them were finding themselves with a 32-bit Go installed on accident and then having problems, e.g. linking against a 64-bit sqlite.

**Comment by josharian** [comment]
It's really useful to be able to my 386 testing on my 64 bit OS X machine.

**Comment by bradfitz** [comment]
That's valid.

But we can at least stop distributing builds from http://golang.org/dl/ if they're useless and misleading for almost everybody.

I'm fine with continuing to run a darwin-386 builder to keep it working for Go developer use cases.

**Comment by bradfitz** [comment]
According to Twitter, it's been 7-8 years since Apple sold a 32-bit Mac: https://twitter.com/bradfitz/status/553298936832589825

**Comment by bradfitz** [comment]
... which includes this wonderful table: http://www.everymac.com/mac-answers/snow-leopard-mac-os-x-faq/mac-os-x-snow-leopard-64-bit-macs-64-bit-efi-boot-in-64-bit-mode.html

**Comment by griesemer** [comment]
+1 for being able to run 32bit binaries on the mac. I just used this this morning.

**Comment by minux** [comment]
Not distributing 32-bit packages for Mac SGTM.
But please don't drop support for darwin/386.
(we need to consider 386 developers that use OS X)

IMHO, as long as Darwin still supports running 32-bit
programs, we should continue to support it.

**Comment by bradfitz** [comment]
I only want to remove them from the downloads page.

**Comment by adg** [comment]
On 9 January 2015 at 08:52, Brad Fitzpatrick <notifications@github.com>
wrote:

> I only want to remove them from the downloads page.


SGTM

**Comment by rsc** [comment]
@robpike @rsc @griesemer

**Comment by minux** [comment]
given that 10.6 builder still shows ok now, I propose that
we keep it for Go 1.5 and announce that 1.6 will drop its
support.

**Comment by robpike** [comment]
I propose we don't explicitly unsupport it but don't worry about maintaining it. This is essentially the whole world's policy.

**Comment by minux** [comment]
So the question is when do we stop the OS X 10.6 builders?

Given that they are still passing for Go tip, I think we can keep them
until 1.5 is released.

**Comment by bradfitz** [comment]
They may be "passing", but in several cases that's just because they're skipping tests. It's the same reason that plan9 is "ok" on the dashboard.

**Comment by minux** [comment]
I agree that OS X is skipping some tests (notably the close on
exec and external linking issues) to pass all.bash, but as Go 1.5
is about to enter feature freeze, I think it's still feasible to maintain
the 10.6 builder passing until 1.5 is released. And then we can
stop the builder at the beginning of the 1.6 cycle.

The only thing that could affect 10.6 builders now is dynamic
library support. But it seems nobody is working on adding that
to Darwin in the 1.5 cycle. (I'm happy to be proved wrong on this
though.)

**Comment by rsc** [comment]
Rob and I discussed this, and we propose that for Go 1.5, we will say something along the lines of "The port to OS X 10.6 (Snow Leopard) is no longer actively maintained." That is, we won't go out of our way to delete it or break it, but we're also not going to make any attempt to keep it working or to fix issues specific to that version of OS X.
