### ISSUE TITLE
mobile: gobind tests leaking temporary files on the builder

### ISSUE THREAD

**Issue by minux** [golang/go#9513]
I found a lot of files in the builder's /tmp directory of this form:
goXXXXX and javaXXXXX.

The content of these files showed that they are temporary files for the gobind tests:
```
// Package go_basictypes is an autogenerated binder stub for package basictypes.
//   gobind -lang=go basictypes
//
// File is generated by gobind. Do not edit.
package go_basictypes

import (
        "basictypes"
        "golang.org/x/mobile/bind/seq"
)

func proxy_ByteArrays(out, in *seq.Buffer) {
        param_x := in.ReadByteArray()
        res := basictypes.ByteArrays(param_x)
        out.WriteByteArray(res)
}
// snip
```
And
```
// Java Package interfaces is a proxy for talking to a Go program.
//   gobind -lang=java interfaces
//
// File is generated by gobind. Do not edit.
package go.interfaces;

import go.Seq;

public abstract class Interfaces {
    private Interfaces() {} // uninstantiable
// snip
```

Perhaps this the reason why some builders' file system has been filled.

PS: I just cleaned up the /tmp yesterday, and now it has accumulated about 200 of these
files, so I'm certain this bug is still there.

**Comment by alexbrainman** [comment]
review tests were leaving behind garbage in %TEMP% directory on windows too. I have fixed that in https://go-review.googlesource.com/#/c/2089/

@bradfitz, perhaps you can remove these on our windows builder too. Thank you.

Alex

**Comment by minux** [comment]
Turns out to be easy to fix, sent golang.org/cl/2343
