### ISSUE TITLE
net/http: Client get,post,postform ect funcs do not expose redirect urls

### ISSUE THREAD

**Issue by epelc** [golang/go#9517]
Currently `net/http`'s client `Get` `Post` `PostForm` and other functions do not expose any redirect urls they followed. This forces you to craft your own request and use `Do` even if you just need to follow a single url and know what it is you followed.

**Comment by bradfitz** [comment]
If you need such information, you can use the CheckRedirect hook of http://golang.org/pkg/net/http/#Client

We try to keep the simple things simple.

And obviously we can't change the signature of existing APIs due to the Go 1 API compatibility promise.

**Comment by epelc** [comment]
@bradfitz Thanks I also just found that and was about to comment
