### ISSUE TITLE
build-id=none parameter passed to ld prevents building go from source on Centos 4 and 5

### ISSUE THREAD

**Issue by alyandon** [golang/go#9520]
The version of ld that ships with Centos 4/5 does not accept the build-id parameter which causes the build process to abort with the following error:

```
# runtime/cgo
/usr/bin/ld: unrecognized option '--build-id=none'
/usr/bin/ld: use the --help option for usage information
collect2: ld returned 1 exit status
```

It appears this was added by default in the following commit:

commit 7fdb0292a5e322c302b5ab685d8ee2623a69608a
Author: Ian Lance Taylor <iant@golang.org>
Date:   Thu Aug 7 12:38:39 2014 -0700

    cmd/go: pass --build-id=none when generating a cgo .o

    Some systems, like Ubuntu, pass --build-id when linking.  The
    effect is to put a note in the output file.  This is not
    useful when generating an object file with the -r option, as
    it eventually causes multiple build ID notes in the final
    executable, all but one of which are for tiny portions of the
    file and are therefore useless.

    Disable that by passing an explicit --build-id=none when
    linking with -r on systems that might do this.

    LGTM=bradfitz
    R=golang-codereviews, bradfitz
    CC=golang-codereviews
    https://golang.org/cl/119460043

**Comment by davecheney** [comment]
I'm sorry but centos/rhel versions less than 6 are not supported by Go

**Comment by ianlancetaylor** [comment]
Sadly this will not be the only problem you run into.

**Comment by jeffallen** [comment]
Here is a workaround for this problem:

http://blog.nella.org/building-go-1-4-when-the-linker-doesnt-know-about-build-id/

While RHEL 5.5 is not supported by Go, with this workaround, the Go toolchain build does complete, and you can use Go 1.4 to build Go tip, and you can use Go tip's compiler. Perhaps the binaries fail in funny ways at runtime due to RHEL 5.5?

**Comment by ianlancetaylor** [comment]
The Go runtime requires Linux kernel version 2.6.23--which version of the kernel does RHEL 5.5 have?

**Comment by alyandon** [comment]
RHEL 5.x is supposedly 2.6.18 - but the real answer is not as simple as comparing version numbers as RedHat actively backports features from later kernels.

http://dave.cheney.net/2013/06/18/how-to-install-go-1-1-on-centos-5

I've compiled Go 1.4 on Cenos 5.x and the test suite appears to complete with no errors except for the file descriptor leak and all the code I've personally tested appears to work.  However, I think realistically most simple programs would run fine but you are walking into a potential minefield if you plan on using Go in a non-trivial way on Centos/RHEL 5.

**Comment by davecheney** [comment]
@alyandon @jeffallen this issue is _closed_. Please take the discussion elsewhere, probably golang-nuts.
