### ISSUE TITLE
git-codereview: git change should barf if there is no newline between subject and description

### ISSUE THREAD

**Issue by davecheney** [golang/go#9522]
Gerrit makes a complete hash of the CL if there is no blank line between the 1st and subsequent lines on the change description. Maybe git-codereview should detect this and barf accordingly.

**Comment by RLH** [comment]
When I did this I got a warning about the subject being too long. The next
change has a fixed subject line.

git mail -r rsc@golang.org,austin@google.com
remote: Resolving deltas: 100% (8/8)
remote: Processing changes: new: 1, done
remote: (W) aa88053: commit subject >65 characters; use shorter first
paragraph
remote: (W) aa88053: too many commit message lines longer than 70
characters; manually wrap lines
remote:
remote: New Changes:
remote:   https://go-review.googlesource.com/2349 Runtime: Increase GC
concurrency. Run GC in its own
background goroutine ...
remote:

**Comment by davecheney** [comment]
I think that warning comes from the gerrit end which doesn't like any lines
> 70 chars.

I think the git-codereview tool could do more before involving gerrit.

**Comment by minux** [comment]
That's just a warning, I think we have lot of commits with longer lines.

**Comment by josharian** [comment]
Mailed https://go-review.googlesource.com/#/c/4130/
