### ISSUE TITLE
cmd/go: discard stderr when querying vcs tools

### ISSUE THREAD

**Issue by josharian** [golang/go#9523]
My copy of `rsc.io/x86` contained an `hgrc` that pointed to a copy of `codereview.py` that has moved. `hg` commands on `rsc.io/x86` thus yielded warnings. The `go` command interpreted the warning as part of the output, leading to a spurious import path violation:

```bash
$ go get -u rsc.io/pprof_mac_fix
package rsc.io/pprof_mac_fix
	imports rsc.io/x86/x86asm: /Users/jbleechersnyder/go/src/rsc.io/x86 is from *** failed to import extension codereview from /Users/jbleechersnyder/src/go/tip/lib/codereview/codereview.py: [Errno 2] No such file or directory: '/Users/jbleechersnyder/src/go/tip/lib/codereview/codereview.py'
https://code.google.com/p/rsc.x86, should be from https://code.google.com/p/rsc.x86
```

The fix is probably to only use stdout, not stdout+stderr. I have confirmed that the warning came on stderr and the useful output on stdout.

**Comment by speter** [comment]
An even safer option might be to bail when stderr from the vcs command is non-empty.

**Comment by bradfitz** [comment]
The problem is in:

```
// run1 is the generalized implementation of run and runOutput.                                                           
func (v *vcsCmd) run1(dir string, cmdline string, keyval []string, verbose bool) ([]byte, error) {
```

... which merges stderr and stdout.

**Comment by rsc** [comment]
I'd like to fix this, but it's too late to be making fundamental changes like
separating stderr from stdout in these command invocations.
I just don't know what will break.

Possibly Brad's fix for #11381 will make this easier.

**Comment by rsc** [comment]
Missed this again.

**Comment by rsc** [comment]
I think unless there are more instances of this problem, we can just leave this alone. Git seems not to have this particular problem, and I can only assume that the hg codereview extension is dying out. 

Reopen if you have a case that you believe is still compelling.

Thanks.
