### ISSUE TITLE
doc: /usr/local/go/bin not added to PATH with Mac package

### ISSUE THREAD

**Issue by arun-gupta** [golang/go#9526]
- Downloaded Go 1.4 .pkg from https://golang.org/dl/ for Mac OS X 10.10.1
- Clicked on the package to go through installation process
- Restarted all the Terminal sessions

Go was installed successfully in /usr/local/go, but /usr/local/go/bin was not added to PATH. This should have happened as mentioned at https://golang.org/doc/install#osx.

**Comment by minux** [comment]
After installation, is there a file /etc/paths.d/go in your file system?
The content should be "/usr/local/go/bin\n"

**Comment by arun-gupta** [comment]
Yes, the file exist and has the expected content.

**Comment by minux** [comment]
And if there exists a /etc/paths.d/go, then what's the output of
/usr/libexec/path_helper -s
?

**Comment by arun-gupta** [comment]
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/usr/local/go/bin:/usr/local/MacGPG2/bin:/Users/arungupta/.rvm/gems/ruby-2.1.0/bin:/Users/arungupta/.rvm/gems/ruby-2.1.0@global/bin:/Users/arungupta/.rvm/rubies/ruby-2.1.0/bin:/Users/arungupta/tools/apache-maven-3.2.3/bin:/Users/arungupta/.rvm/bin"; export PATH;

**Comment by minux** [comment]
There is /usr/local/go/bin in the PATH shown, could you check your actual
$PATH
against the output from path_helper -s?

Try source /etc/profile and then check $PATH again, /etc/profile should
contain
the following lines:
if [ -x /usr/libexec/path_helper ]; then
        eval `/usr/libexec/path_helper -s`
fi

I suspect somehow your local setting doesn't source /etc/profile.

**Comment by arun-gupta** [comment]
$PATH is exactly same as shown above.

/etc/profile has:

if [ -x /usr/libexec/path_helper ]; then
        eval `/usr/libexec/path_helper -s`
fi

if [ "${BASH-no}" != "no" ]; then
        [ -r /etc/bashrc ] && . /etc/bashrc
fi

source /etc/profile does not seem to update PATH. It shows:

echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/usr/local/go/bin:/usr/local/MacGPG2/bin:/Users/arungupta/.rvm/gems/ruby-2.1.0/bin:/Users/arungupta/.rvm/gems/ruby-2.1.0@global/bin:/Users/arungupta/.rvm/rubies/ruby-2.1.0/bin:/Users/arungupta/tools/apache-maven-3.2.3/bin:/Users/arungupta/.rvm/bin

**Comment by minux** [comment]
but then /usr/local/go/bin is right there in the $PATH.

so you still can't execute the go command?

**Comment by arun-gupta** [comment]
I manually edited .bash_profile to include it in there. Will try it on a clean machine and report back.

**Comment by rsc** [comment]
Timed out.
