### ISSUE TITLE
encoding/xml: does not process multiple namespace definitions correctly

### ISSUE THREAD

**Issue by jordan2175** [golang/go#9527]
The unmarshal / marshal functions do not handle multiple xmlns definitions.  See:
 
https://play.golang.org/p/KTemXABrFb

If you remove all but one of the namespace definitions, it will sort of work.

**Comment by mikioh** [comment]
Dup of #7113

@jordan2175, feel free to send a CL; http://golang.org/doc/contribute.html

FWIW, there were CL 93320043, but not completed due to more important tasks. I think you can ask him to take over https://codereview.appspot.com/93320043.

**Comment by rogpeppe** [comment]
The example is wrong. If you replace the namespace prefixes in the struct
tags with full URLs, then it seems to work OK.

https://play.golang.org/p/MYDT8H_s6Z
