### ISSUE TITLE
doc/install/source broken.

### ISSUE THREAD

**Issue by plan9** [golang/go#9529]
as of december 10 "This release also coincides with the project's move from Mercurial to Git"
documentation still referring to mercurial.

**Comment by rakyll** [comment]
The doc is not broken.

The latest stable (go1.4) has been released from the Mercurial repo, therefore it's still recommended to install go1.4 from the legacy repo.

**Comment by ianlancetaylor** [comment]
I agree: I think this is correct.  The project moved to git after the 1.4 release, and the 1.4 release is still delivered from Mercurial.

**Comment by davecheney** [comment]
@ianlancetaylor I believe there is still an issue. Following the install from source instructions gets you Go 1.3, not 1.4

```
lucky(~) % hg clone -u release https://code.google.com/p/go go1.4                                                                                                                                             
requesting all changes
adding changesets
adding manifests
adding file changes
added 21924 changesets with 76805 changes to 11602 files (+9 heads)
updating to branch release-branch.go1.3
4167 files updated, 0 files merged, 0 files removed, 0 files unresolved
```

**Comment by adg** [comment]
This will be fixed in 1.4.1. I don't have the patience to figure out why Mercurial is so broken. I'm glad it will all be behind us shortly.

**Comment by minux** [comment]
Very interesting hg behavior.

I double checked the tags (go1.4 and release) are correct on the
default branch, but

hg clone -u release ...
will get me to release-branch.go1.3 branch, but if I go the
directory, and hg up release again, it will switch to release-branch.go1.4
branch correctly.

**Comment by adg** [comment]
@minux very puzzling indeed. I'm curious as to whether it'll work correctly if you `clone -u release` from the local repository.

**Comment by plan9** [comment]
thanks @davecheney
since -u release doesn't default to release-branch.go1.4, perhaps this document can at least be updated to clone with update to release-branch.go1.4 directly. i would imagine there is no harm in making it explicit in a legacy repo.

**Comment by adg** [comment]
OK https://codereview.appspot.com/194050043

**Comment by plan9** [comment]
@adg sure that works, avoids mentioning lengthy release names.

**Comment by adg** [comment]
The updated instructions are now rolled out to golang.org.
