### ISSUE TITLE
sepc: a case clause of swtich does not flow to the next clause

### ISSUE THREAD

**Issue by dorajistyle** [golang/go#9533]
https://golang.org/test/switch.go

The official test works great.
However "switch case" shows strange result in the test below:
https://play.golang.org/p/mkDtpfYqhr

**Comment by dominikh** [comment]
case statements in Go have an implicit break, they don't fall through automatically. Use the `fallthrough` keyword for that, or specify all valid values in a single case, separated by commas.

**Comment by mikioh** [comment]
See http://golang.org/ref/spec#Switch_statements

**Comment by dorajistyle** [comment]
Thanks a lot.
