### ISSUE TITLE
runtime: auxv parsing should be unified

### ISSUE THREAD

**Issue by davecheney** [golang/go#9538]
Currently there are two runtime locations where auxv data is parsed, `vsdo_linux_amd64.go`, and `os_linux_arm.go`. Adding arm64 will add a third location. This logic should be unified into a single file to be reused by all linux implementations.

**Comment by davecheney** [comment]
I just found a third location, `os_linux_386.go`

**Comment by tklauser** [comment]
This was fixed by https://golang.org/cl/22061 (for #9993).
