### ISSUE TITLE
cmd/gc: unaligned stack size on amd64p32

### ISSUE THREAD

**Issue by josharian** [golang/go#9539]
Running `nacltest.bash` at tip (f21ee1e1d8a70abd130d0435eb1a1d2e95c88129), I see a bunch of:

`unaligned stack size 20`

Should we make this an error so that it gets caught in the builders in the future?

**Comment by randall77** [comment]
Yes, that should probably be an error.  It's going to misalign 64-bit loads
and stores.  That's not horrible, but should be avoided.  (Does MOVSD need
to be aligned?  Apparently not, or much worse things should have
happened...)

**Comment by minux** [comment]
I think it's already an error in liblink, the problem is that
our cmd/6a failed to check nerrors before executing
exits(0).

I will fix it.
