### ISSUE TITLE
runtime: linux/arm should source startupRandomData from auxv

### ISSUE THREAD

**Issue by davecheney** [golang/go#9541]
For linux the kernel provides 16 bytes of random data via auvx, we pick this up in linux/arm to use for seeding `cputicks`, but we only use 4 bytes of that data and discard the rest.

Other runtime parts check `startupRandomData` and find it empty and go out to `/dev/{u,}random` to get more entropy. I think we can unify these two efforts and reuse the auxv random data that the os gives us.

**Comment by davecheney** [comment]
@minux what do you think ?

**Comment by davecheney** [comment]
See also, https://go-review.googlesource.com/#/c/2582/2

**Comment by minux** [comment]
I agree, sent CL 2584.

**Comment by minux** [comment]
Dave, send your CL instead.
