### ISSUE TITLE
time: want more control over time.Format

### ISSUE THREAD

**Issue by ddietterich** [golang/go#9547]
Using go version go1.3.3 linux/amd64
```
func main() {
        t := time.Now()
        fmt.Printf("time: %v; format: %s\n", t, t.Format("20080101 10:00:00.000"))
}
```
Prints:
```
time: 2015-01-09 17:06:02.033307544 +0000 UTC; format: 90080101 10:00:00.033
```
I want YYYYMMDD, but time.Format is only layout by example, so it cannot know what digits mean year, month, day. I have to do it by hand.

**Comment by bradfitz** [comment]
Use the reference time. This is explained in the docs: http://golang.org/pkg/time/#pkg-constants

**Comment by cespare** [comment]
@ddietterich http://play.golang.org/p/REvcaiEavz

**Comment by ddietterich** [comment]
I read that documentation. I find nothing there that lets me distinguish years, months and days in a concatenated string. It just will not do what I want it to do.

**Comment by ddietterich** [comment]
@cespare Maybe there is a fix between 1.3.3 and 1.4? You can see that I did not get the correct year in my example.

**Comment by cespare** [comment]
@ddietterich as @bradfitz said, you need to use the reference time, not some other time of your choosing. (Examine carefully the difference between your code and mine.)

**Comment by ddietterich** [comment]
OK, I get it.
I find it entirely obscure and won't use it, but I cannot complain that it won't do what I want it to do.
Thanks!
