### ISSUE TITLE
runtime: fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by opennota** [golang/go#9549]
[This app](https://github.com/opennota/watchreddit/tree/v1), after running for some time on my machine under linux kernel 3.17.7, crashes with `fatal error: unexpected signal during runtime execution`. I didn't observe any crashes under kernels 3.12.x. The app is built using Go 1.4.

```
$ uname -a                           
Linux localhost 3.17.7-gentoo #2 SMP PREEMPT Fri Jan 2 09:09:26 KRAT 2015 x86_64 Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz GenuineIntel GNU/Linux
```

Here's the stack trace with GOTRACEBACK=2:

    fatal error: unexpected signal during runtime execution
    [signal 0xb code=0x80 addr=0x0 pc=0x40fea7]
    
    runtime stack:
    runtime.gothrow(0x7f1d90, 0x2a)
    	/usr/lib/go/src/runtime/panic.go:503 +0x8e fp=0x7f05ba913b10 sp=0x7f05ba913af8
    runtime.sigpanic()
    	/usr/lib/go/src/runtime/sigpanic_unix.go:14 +0x5e fp=0x7f05ba913b60 sp=0x7f05ba913b10
    
    goroutine 1 [syscall, locked to thread]:
    runtime.cgocall_errno(0x40735f, 0xc2080b3c18, 0x0)
    	/usr/lib/go/src/runtime/cgocall.go:130 +0xf5 fp=0xc2080b3bf8 sp=0xc2080b3bd0
    github.com/mxk/go-sqlite/sqlite3._Cfunc_sqlite3_prepare_v2(0xb5a1a8, 0xc2080bf260, 0xffffffff, 0xc2080b3c50, 0xc2080b3c48, 0x0)
    	/home/xxx/gocode/src/github.com/mxk/go-sqlite/sqlite3/:539 +0x43 fp=0xc2080b3c18 sp=0xc2080b3bf8
    github.com/mxk/go-sqlite/sqlite3.newStmt(0xc20803cc00, 0xc2080bf230, 0x2f, 0xc2080b3d38, 0x0, 0x0)
    	/home/xxx/gocode/src/github.com/mxk/go-sqlite/sqlite3/sqlite3.go:586 +0xe4 fp=0xc2080b3cd0 sp=0xc2080b3c18
    github.com/mxk/go-sqlite/sqlite3.(*Conn).Query(0xc20803cc00, 0xc2080bf230, 0x2f, 0xc2080b3da8, 0x1, 0x1, 0x2f, 0x0, 0x0)
    	/home/xxx/gocode/src/github.com/mxk/go-sqlite/sqlite3/sqlite3.go:279 +0xc3 fp=0xc2080b3d20 sp=0xc2080b3cd0
    main.IsPostExists(0xc20803cc00, 0xc208036400, 0xc208034101)
    	/home/xxx/gocode/src/github.com/opennota/watchreddit/main.go:192 +0x210 fp=0xc2080b3dd8 sp=0xc2080b3d20
    main.main()
    	/home/xxx/gocode/src/github.com/opennota/watchreddit/main.go:323 +0xc6a fp=0xc2080b3f98 sp=0xc2080b3dd8
    runtime.main()
    	/usr/lib/go/src/runtime/proc.go:63 +0xf3 fp=0xc2080b3fe0 sp=0xc2080b3f98
    runtime.goexit()
    	/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080b3fe8 sp=0xc2080b3fe0
    
    goroutine 2 [force gc (idle), 635 minutes]:
    runtime.gopark(0x4a5700, 0xb2f6c0, 0x7a4210, 0xf)
    	/usr/lib/go/src/runtime/proc.go:130 +0x105 fp=0xc20801a798 sp=0xc20801a768
    runtime.goparkunlock(0xb2f6c0, 0x7a4210, 0xf)
    	/usr/lib/go/src/runtime/proc.go:136 +0x48 fp=0xc20801a7c0 sp=0xc20801a798
    runtime.forcegchelper()
    	/usr/lib/go/src/runtime/proc.go:99 +0xce fp=0xc20801a7e0 sp=0xc20801a7c0
    runtime.goexit()
    	/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801a7e8 sp=0xc20801a7e0
    created by runtime.init·4
    	/usr/lib/go/src/runtime/proc.go:87 +0x25
    
    goroutine 3 [GC sweep wait]:
    runtime.gopark(0x4a5700, 0xb382a8, 0x79b590, 0xd)
    	/usr/lib/go/src/runtime/proc.go:130 +0x105 fp=0xc20801df98 sp=0xc20801df68
    runtime.goparkunlock(0xb382a8, 0x79b590, 0xd)
    	/usr/lib/go/src/runtime/proc.go:136 +0x48 fp=0xc20801dfc0 sp=0xc20801df98
    runtime.bgsweep()
    	/usr/lib/go/src/runtime/mgc0.go:98 +0xbc fp=0xc20801dfe0 sp=0xc20801dfc0
    runtime.goexit()
    	/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801dfe8 sp=0xc20801dfe0
    created by gc
    	/usr/lib/go/src/runtime/mgc0.c:1383
    
    goroutine 4 [finalizer wait]:
    runtime.gopark(0x4a5700, 0xb382a0, 0x7a3af0, 0xe)
    	/usr/lib/go/src/runtime/proc.go:130 +0x105 fp=0xc208019730 sp=0xc208019700
    runtime.goparkunlock(0xb382a0, 0x7a3af0, 0xe)
    	/usr/lib/go/src/runtime/proc.go:136 +0x48 fp=0xc208019758 sp=0xc208019730
    runtime.runfinq()
    	/usr/lib/go/src/runtime/malloc.go:727 +0xba fp=0xc2080197e0 sp=0xc208019758
    runtime.goexit()
    	/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080197e8 sp=0xc2080197e0
    created by runtime.createfing
    	/usr/lib/go/src/runtime/malloc.go:707 +0x5e
    
    goroutine 17 [syscall, 635 minutes, locked to thread]:
    runtime.goexit()
    	/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208056fe8 sp=0xc208056fe0
    
    goroutine 5 [syscall, 635 minutes]:
    runtime.notetsleepg(0xb38e00, 0xffffffffffffffff, 0x1)
    	/usr/lib/go/src/runtime/lock_futex.go:201 +0x52 fp=0xc208018768 sp=0xc208018740
    runtime.signal_recv(0x0)
    	/usr/lib/go/src/runtime/sigqueue.go:109 +0x135 fp=0xc2080187a0 sp=0xc208018768
    os/signal.loop()
    	/usr/lib/go/src/os/signal/signal_unix.go:21 +0x1f fp=0xc2080187e0 sp=0xc2080187a0
    runtime.goexit()
    	/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080187e8 sp=0xc2080187e0
    created by os/signal.init·1
    	/usr/lib/go/src/os/signal/signal_unix.go:27 +0x35
    
    goroutine 6 [chan receive, 635 minutes]:
    runtime.gopark(0x4a5700, 0xc208062118, 0x7a1e70, 0xc)
    	/usr/lib/go/src/runtime/proc.go:130 +0x105 fp=0xc20801d6c0 sp=0xc20801d690
    runtime.goparkunlock(0xc208062118, 0x7a1e70, 0xc)
    	/usr/lib/go/src/runtime/proc.go:136 +0x48 fp=0xc20801d6e8 sp=0xc20801d6c0
    runtime.chanrecv(0x6a8d20, 0xc2080620c0, 0x0, 0x1, 0x0)
    	/usr/lib/go/src/runtime/chan.go:410 +0x452 fp=0xc20801d788 sp=0xc20801d6e8
    runtime.chanrecv1(0x6a8d20, 0xc2080620c0, 0x0)
    	/usr/lib/go/src/runtime/chan.go:311 +0x2b fp=0xc20801d7b8 sp=0xc20801d788
    main.func·001()
    	/home/xxx/gocode/src/github.com/opennota/watchreddit/main.go:306 +0x48 fp=0xc20801d7e0 sp=0xc20801d7b8
    runtime.goexit()
    	/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801d7e8 sp=0xc20801d7e0
    created by main.main
    	/home/xxx/gocode/src/github.com/opennota/watchreddit/main.go:309 +0xa9f
    
    goroutine 8 [timer goroutine (idle)]:
    runtime.gopark(0x4a5700, 0xb2f8c0, 0x7c69d0, 0x16)
    	/usr/lib/go/src/runtime/proc.go:130 +0x105 fp=0xc208018f40 sp=0xc208018f10
    runtime.goparkunlock(0xb2f8c0, 0x7c69d0, 0x16)
    	/usr/lib/go/src/runtime/proc.go:136 +0x48 fp=0xc208018f68 sp=0xc208018f40
    runtime.timerproc()
    	/usr/lib/go/src/runtime/time.go:200 +0x130 fp=0xc208018fe0 sp=0xc208018f68
    runtime.goexit()
    	/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208018fe8 sp=0xc208018fe0
    created by runtime.addtimerLocked
    	/usr/lib/go/src/runtime/time.go:113 +0x1ba
    
    goroutine 67 [IO wait]:
    runtime.gopark(0x483660, 0x7f05bc0a4160, 0x78a570, 0x7)
    	/usr/lib/go/src/runtime/proc.go:130 +0x105 fp=0xc208055ae8 sp=0xc208055ab8
    runtime.netpollblock(0x7f05bc0a4138, 0x72, 0xc2080df000)
    	/usr/lib/go/src/runtime/netpoll.go:347 +0x170 fp=0xc208055b28 sp=0xc208055ae8
    runtime.netpollWait(0x7f05bc0a4138, 0x72, 0x8)
    	/usr/lib/go/src/runtime/netpoll.go:150 +0x68 fp=0xc208055b48 sp=0xc208055b28
    net.(*pollDesc).Wait(0xc208010680, 0x72, 0x0, 0x0)
    	/usr/lib/go/src/net/fd_poll_runtime.go:84 +0x47 fp=0xc208055b68 sp=0xc208055b48
    net.(*pollDesc).WaitRead(0xc208010680, 0x0, 0x0)
    	/usr/lib/go/src/net/fd_poll_runtime.go:89 +0x43 fp=0xc208055b90 sp=0xc208055b68
    net.(*netFD).Read(0xc208010620, 0xc2080ae000, 0x1000, 0x1000, 0x0, 0x7f05bc0a2bd8, 0xc2080defc8)
    	/usr/lib/go/src/net/fd_unix.go:242 +0x40f fp=0xc208055c30 sp=0xc208055b90
    net.(*conn).Read(0xc20803a088, 0xc2080ae000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    	/usr/lib/go/src/net/net.go:121 +0xdc fp=0xc208055c78 sp=0xc208055c30
    net/http.noteEOFReader.Read(0x7f05bc0a41f8, 0xc20803a088, 0xc2080bdb28, 0xc2080ae000, 0x1000, 0x1000, 0x6f7a00, 0x0, 0x0)
    	/usr/lib/go/src/net/http/transport.go:1270 +0x6e fp=0xc208055cc8 sp=0xc208055c78
    net/http.(*noteEOFReader).Read(0xc2081089c0, 0xc2080ae000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
    	<autogenerated>:125 +0xd4 fp=0xc208055d18 sp=0xc208055cc8
    bufio.(*Reader).fill(0xc208062a20)
    	/usr/lib/go/src/bufio/bufio.go:97 +0x1ce fp=0xc208055dc0 sp=0xc208055d18
    bufio.(*Reader).Peek(0xc208062a20, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
    	/usr/lib/go/src/bufio/bufio.go:132 +0xf0 fp=0xc208055dd0 sp=0xc208055dc0
    net/http.(*persistConn).readLoop(0xc2080bdad0)
    	/usr/lib/go/src/net/http/transport.go:842 +0xa4 fp=0xc208055fd8 sp=0xc208055dd0
    runtime.goexit()
    	/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208055fe0 sp=0xc208055fd8
    created by net/http.(*Transport).dialConn
    	/usr/lib/go/src/net/http/transport.go:660 +0xc9f
    
    goroutine 68 [select]:
    runtime.gopark(0x4881e0, 0xc208019f40, 0x7949d0, 0x6)
    	/usr/lib/go/src/runtime/proc.go:130 +0x105 fp=0xc208019cb8 sp=0xc208019c88
    runtime.selectgoImpl(0xc208019f40, 0x0, 0x18)
    	/usr/lib/go/src/runtime/select.go:366 +0xb2c fp=0xc208019e50 sp=0xc208019cb8
    runtime.selectgo(0xc208019f40)
    	/usr/lib/go/src/runtime/select.go:183 +0x12 fp=0xc208019e70 sp=0xc208019e50
    net/http.(*persistConn).writeLoop(0xc2080bdad0)
    	/usr/lib/go/src/net/http/transport.go:945 +0x41d fp=0xc208019fd8 sp=0xc208019e70
    runtime.goexit()
    	/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208019fe0 sp=0xc208019fd8
    created by net/http.(*Transport).dialConn
    	/usr/lib/go/src/net/http/transport.go:661 +0xcbc
    exit status 2

**Comment by ianlancetaylor** [comment]
This means that your program got a SIGSEGV signal while running C code.  The stack trace of goroutine 1 shows you the Go code that called into C.  The Go runtime can't dump the stack of the C code.

This may be a problem with your C code, or with how your C code is called, rather than anything that Go can fix.

**Comment by opennota** [comment]
That's possible.

**Comment by opennota** [comment]
Any way to get a useful core dump? Special compiling options?

**Comment by ianlancetaylor** [comment]
Set the environment variable GOTRACEBACK to crash.
GOTRACEBACK=crash prog
