### ISSUE TITLE
runtime: send stderr to logcat for GOOS=android

### ISSUE THREAD

**Issue by crawshaw** [golang/go#9550]
This change, https://go-review.googlesource.com/#/c/1285/, failed to make it into Go 1.4 because of bad organization on my part. It is in tip right now, and is particularly useful to developers as it lets them see the output of a panic.

Is a backport for Go 1.4.1 out of the question? It would require a C transliteration, but only affects GOOS=android.

/cc @hyangah

**Comment by ianlancetaylor** [comment]
Can developers for Android use 1.4 in a serious manner, or is it better for them to work on tip?  Or should we just supply a set of patches, or a branch, on top of 1.4?  My understanding was that the Android 1.4 support was quite experimental.  It doesn't seem like a good idea if we're going to have a set of Android patches for 1.4.2 also.

**Comment by crawshaw** [comment]
I suspect the compiler transition will make it hard to use tip for quite a while.

I would be happy with an android-1.4 branch. As is, 1.4 is reasonably stable for GOOS=android, it is the mobile repository (and build system) that is in flux.

**Comment by rsc** [comment]
I'll put this in 1.4.1, because it seems less terrible than having a separate android-1.4 branch. I hope this will be the end though. (And I'll get the Copyright fix.)

**Comment by rsc** [comment]
The code review for this cherry-pick suggested that /dev/log/main doesn't exist on Android L devices. https://go-review.googlesource.com/2803

Based on that and the fact that the malloc change doesn't apply cleanly at all (the change is in a Go file that is still written in C in the release branch), I suggest that you either have people live with the 1.4 limitations or publish a github.com/crawshaw/go-android for people to use. It's too much work (and too uncertain to be useful) to get these into the release branch, and I don't want to create yet another official branch in the main repo that will be maintained.

**Comment by crawshaw** [comment]
I don't consider the Android L logging problem to be important. L devices remain extremely rare and so app writers are not writing apps against it. But I will go with your suggestion of creating a copy elsewhere.
