### ISSUE TITLE
spec: clarify that iteration variables are "evaluated" in each iteration in for-range loops

### ISSUE THREAD

**Issue by griesemer** [golang/go#9552]
http://play.golang.org/p/CqCtJDGoB2

Both gc and gccgo invoke f() in each iteration; that is the "iteration variable" is evaluated each time. This can be concluded from the spec since values are assigned to iteration variables like in an assignment, but perhaps it should be mentioned explicitly or have an example.

**Comment by josharian** [comment]
The spec does say: "Function calls on the left are evaluated once per iteration." The phrasing could definitely be clearer, but I think that it is at least well-specified and explicit.

**Comment by griesemer** [comment]
Very explicit indeed - I completely missed that phrase. Thanks for pointing it out.
