### ISSUE TITLE
tools/go/vcs: Bug fix for remote package discovery was applied to cmd/go but not tools/go/vcs.

### ISSUE THREAD

**Issue by shurcooL** [golang/go#9556]
Both `cmd/go/discovery.go` and `tools/go/vcs/discovery.go` contain what used to be an identical copy of `parseMetaGoImports`.

[CL 68520044](https://codereview.appspot.com/68520044) has applied a bug fix to the `parseMetaGoImports` copy in `cmd/go`, but not in `tools/go/vcs`. Because of that, there is now a difference between the two copies:

![image](https://cloud.githubusercontent.com/assets/1924134/5690473/43f86072-9840-11e4-872b-65d7bbd3d788.png)

Therefore, the bug is still present in `tools/go/vcs` package but not `cmd/go`. It manifests itself in that you can do `go get -d -u robpike.io/filter` and it will succeed, but doing `vcs.RepoRootForImportPath("robpike.io/filter", false)` results in an error `unrecognized import path "robpike.io/filter"`. It was originally discovered in https://github.com/shurcooL/gtdo/issues/26.

The fix is really simple - just apply the same change as in [CL 68520044](https://codereview.appspot.com/68520044) to `tools/go/vcs`.

**Comment by minux** [comment]
Sure, send a CL.

**Comment by shurcooL** [comment]
I haven't figured out how to use Gerrit yet. I've been waiting for tip.golang.org/doc/contribute.html to be updated, and it seems to be the case now, so I can go ahead and do that.

Expect a CL over this weekend.

**Comment by minux** [comment]
FTR, the contribution guideline on golang.org is also up-to-date.
http://golang.org/doc/contribute.html

**Comment by shurcooL** [comment]
Fixed in https://github.com/golang/tools/commit/c10e262955e9f7bf20aaa801af6ff2dd14674159, closing. Thanks minux!

(Is there some bot that would close the issue automatically?)

**Comment by minux** [comment]
I forgot to mention that to close an issue from a sub-repo CL, you need to
write "Fixes golang/go#9556".

My bad.

**Comment by shurcooL** [comment]
Yeah, I'm well aware of that, I just... forgot in this case.
