### ISSUE TITLE
crypto/aes: NewCipher only accept 16 bytes aes key?

### ISSUE THREAD

**Issue by coderhaoxin** [golang/go#9559]
use go version - 1.4

According to the doc

* NewCipher creates and returns a new cipher.Block. The key argument should be the AES key, `either 16, 24, or 32` bytes ...

but in the `NewCFBEncrypter` and `NewCBCEncrypter`, just compare the length of iv with block.BlockSize(), the return is a const `16`.

Because of `the iv must be the same length as the Block's block size`, the AES key must be 16 bytes?

**Comment by minux** [comment]
You've confused key and IV, they are not the same thing.
key can be 16/24/32 bytes for AES, but IV must be 16-byte to match the
block size.

http://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Cipher-block_chaining_.28CBC.29

Working as intended.
