### ISSUE TITLE
net/http: cannot register ServeMux handler for all CONNECT requests regardless of host or path

### ISSUE THREAD

**Issue by kr** [golang/go#9561]
Go version 1.4 and head (4e03bbb1ada77fd9e8ba95d82dec6bfb3862db0d), all platforms.

It doesn't appear to be possible to register a ServeMux handler that works for all CONNECT requests, regardless of hostname or path.

##### Steps to reproduce

1. Register a ServeMux handler for `"/"`. http://play.golang.org/p/iIU0eJ3Idn

2. Send a proxy request:

   ```
CONNECT example.com:443 HTTP/1.1
```

##### Expected behavior

The program prints something like

```
handle CONNECT "example.com:443" ""
```

and returns a 200 response.

##### Observed behavior

The program prints nothing and returns 404.

##### Notes

As http.ServeMux.handler notes, its path parameter is in canonical form, except for CONNECT requests. In this case the path is the empty string, so it never matches against a ServeMux entry that has a non-empty path.

It is possible to register a ServeMux handler for a particular host, as in

```
http.Handle("example.com:443", foo)
```

and this receives CONNECT requests as expected. But it doesn't appear to be possible to register a handler as a generic fallback for CONNECT requests, as one might hope to do with `"/"`. (And ServeMux explicitly rejects the empty string as an invalid pattern.)

A possible workaround is "don't use ServeMux for this", but perhaps there is a fix.

ServeMux.Handler might fix this by explicitly using "/" as the path argument to ServeMux.handler for a CONNECT request with an empty path. E.g.:

```
func (mux *ServeMux) Handler(r *Request) (h Handler, pattern string) {
	path := r.URL.Path
	if r.Method != "CONNECT" {
		if p := cleanPath(r.URL.Path); p != r.URL.Path {
			_, pattern = mux.handler(r.Host, p)
			url := *r.URL
			url.Path = p
			return RedirectHandler(url.String(), StatusMovedPermanently), pattern
		}
	} else if path == "" {
		path = "/"
	}

	return mux.handler(r.Host, path)
}
```

I'm not sure if that's a reasonable approach.

**Comment by rsc** [comment]
This has come up before. We would need to figure out the syntax for this.

**Comment by rsc** [comment]
We didn't manage to get to this for Go 1.5. I apologize for that, but it does seem that there is an easy workaround: register a handler in front of the servemux that picks off CONNECT requests.

**Comment by bradfitz** [comment]
I don't think ServeMux needs to do everything. It's very easy to write your own mux, and CONNECT is a pretty advanced case. Anybody needing CONNECT (like @kr) knows how to write their own.

In the interest of minimizing changes in the standard library, I'm going to close this. Feel free to argue if you feel strongly.

**Comment by kr** [comment]
Sounds good to me. I don't feel strongly about it, just wanted to bring it up.

**Comment by fanyang01** [comment]
There is no way to register a proxy handler in App Engine due to this issue. In a normal environment, it can be avoided by using `http.ListenAndServe`. However for App Engine environment, only `http.Handle` is available.

**Comment by davecheney** [comment]
@fanyang01 please don't discussions on closed issues. Please see https://golang.org/wiki/Questions for good places to ask. Thanks.

**Comment by fanyang01** [comment]
Sorry. I will open a new issue for this.
