### ISSUE TITLE
random hickups

### ISSUE THREAD

**Issue by quinte17** [golang/go#9562]
this is hard to reproduce.
sometimes the following error occurs:
##### GOMAXPROCS=2 runtime -cpu=1,2,4
--- FAIL: TestCgoSignalDeadlock (0.10s)
	crash_test.go:76: building source: exit status 2
		runtime:greyobject: checkmarks finds unexpected unmarked object obj=0xc20801e288, mbits->bits=0x1 *mbits->bitp=0x9b
		runtime: found obj at *(0xc208047a00+0x8)
		runtime:greyobject Span: obj=0xc20801e288 k=0x610400f s.start=0xc20801e000 s.limit=0xc208020000 s.sizeclass=1 s.elemsize=8
		 *(obj+0) = 0xc208047040
		fatal error: checkmark found unmarked object
		
		runtime stack:
		runtime.throw(0x8eb8d0, 0x1f)
			/home/stephan/go/src/runtime/panic.go:508 +0x98 fp=0x7fa9ef4837a0 sp=0x7fa9ef483788
		runtime.greyobject(0xc20801e288, 0xc208047a00, 0x8, 0x7fa9ef483890, 0x7fa9f1438240, 0x7fa9f1438240)
			/home/stephan/go/src/runtime/mgc.go:440 +0x2c9 fp=0x7fa9ef483800 sp=0x7fa9ef4837a0
		runtime.scanobject(0xc208047a00, 0x1b8600, 0x0, 0x7fa9f1438240, 0x7fa9f1438240)
			/home/stephan/go/src/runtime/mgc.go:573 +0x3f0 fp=0x7fa9ef4838b0 sp=0x7fa9ef483800
		runtime.drainworkbuf(0x7fa9f1438240, 0x0)
			/home/stephan/go/src/runtime/mgc.go:650 +0x184 fp=0x7fa9ef4838e0 sp=0x7fa9ef4838b0
		runtime.scanblock(0xc2080cda88, 0x28, 0x950118)
			/home/stephan/go/src/runtime/mgc.go:610 +0xe5 fp=0x7fa9ef483928 sp=0x7fa9ef4838e0
		runtime.scanframe(0x7fa9ef483a78, 0x0, 0xc200000101)
			/home/stephan/go/src/runtime/mgc.go:998 +0x1d0 fp=0x7fa9ef4839c0 sp=0x7fa9ef483928
		runtime.gentraceback(0x4a0bb0, 0xc2080cc3e0, 0x0, 0xc208000120, 0x0, 0x0, 0x7fffffff, 0x970048, 0x0, 0x0, ...)
			/home/stephan/go/src/runtime/traceback.go:282 +0x7cd fp=0x7fa9ef483ad0 sp=0x7fa9ef4839c0
		runtime.scanstack(0xc208000120)
			/home/stephan/go/src/runtime/mgc.go:1032 +0x214 fp=0x7fa9ef483b48 sp=0x7fa9ef483ad0
		runtime.gcphasework(0xc208000120)
			/home/stephan/go/src/runtime/mgc.go:1178 +0x9c fp=0x7fa9ef483b60 sp=0x7fa9ef483b48
		runtime.stopg(0xc208000120, 0x1)
			/home/stephan/go/src/runtime/proc1.go:447 +0x91 fp=0x7fa9ef483b80 sp=0x7fa9ef483b60
		runtime.markroot(0xc208010000, 0x5)
			/home/stephan/go/src/runtime/mgc.go:747 +0x161 fp=0x7fa9ef483bf0 sp=0x7fa9ef483b80
		runtime.parfordo(0xc208010000)
			/home/stephan/go/src/runtime/parfor.go:84 +0x1af fp=0x7fa9ef483c60 sp=0x7fa9ef483bf0
		runtime.gchelper()
			/home/stephan/go/src/runtime/mgc.go:1560 +0x4b fp=0x7fa9ef483c90 sp=0x7fa9ef483c60
		runtime.stopm()
			/home/stephan/go/src/runtime/proc1.go:1052 +0x164 fp=0x7fa9ef483cb8 sp=0x7fa9ef483c90
		runtime.gcstopm()
			/home/stephan/go/src/runtime/proc1.go:1215 +0xff fp=0x7fa9ef483ce8 sp=0x7fa9ef483cb8
		runtime.schedule()
			/home/stephan/go/src/runtime/proc1.go:1424 +0xa4 fp=0x7fa9ef483d18 sp=0x7fa9ef483ce8
		runtime.gosched_m(0xc208000120)
			/home/stephan/go/src/runtime/proc1.go:1535 +0x119 fp=0x7fa9ef483d38 sp=0x7fa9ef483d18
		runtime.newstack()
			/home/stephan/go/src/runtime/stack1.go:712 +0xa3a fp=0x7fa9ef483e90 sp=0x7fa9ef483d38
		runtime.morestack()
			/home/stephan/go/src/runtime/asm_amd64.s:311 +0x7e fp=0x7fa9ef483e98 sp=0x7fa9ef483e90
		
		goroutine 1 [runnable]:
		runtime.growslice(0x74f6c0, 0xc208029c70, 0x2, 0x2, 0x1, 0xc208029c70, 0x1, 0x2)
			/home/stephan/go/src/runtime/slice.go:37 fp=0xc2080cc3e8 sp=0xc2080cc3e0
		go/parser.(*parser).consumeCommentGroup(0xc2080f2c00, 0x1, 0x0, 0x3)
			/home/stephan/go/src/go/parser/parser.go:284 +0x13f fp=0xc2080cc4a0 sp=0xc2080cc3e8
		go/parser.(*parser).next(0xc2080f2c00)
			/home/stephan/go/src/go/parser/parser.go:333 +0x168 fp=0xc2080cc4e8 sp=0xc2080cc4a0
		go/parser.(*parser).init(0xc2080f2c00, 0xc208103680, 0xc2080dc360, 0x27, 0xc208107000, 0x131, 0x200, 0x6)
			/home/stephan/go/src/go/parser/parser.go:78 +0x1b3 fp=0xc2080cc540 sp=0xc2080cc4e8
		go/parser.ParseFile(0xc208103680, 0xc2080dc360, 0x27, 0x7548e0, 0xc20811bae0, 0x6, 0x0, 0x0, 0x0)
			/home/stephan/go/src/go/parser/interface.go:113 +0x20c fp=0xc2080cc5d8 sp=0xc2080cc540
		go/build.(*Context).Import(0xac1720, 0xc2080b6d51, 0xb, 0xc2080df0a0, 0x1c, 0x4, 0xc20809e000, 0x0, 0x0)
			/home/stephan/go/src/go/build/build.go:670 +0x25fd fp=0xc2080ccf00 sp=0xc2080cc5d8
		main.loadImport(0xc2080b6d51, 0xb, 0xc2080df0a0, 0x1c, 0xc2080defe0, 0xc20811e9f0, 0x1, 0x1, 0x0)
			/home/stephan/go/src/cmd/go/pkg.go:267 +0x4e1 fp=0xc2080cd0b8 sp=0xc2080ccf00
		main.(*Package).load(0xc2080ee400, 0xc2080defe0, 0xc208101500, 0x0, 0x0, 0x0)
			/home/stephan/go/src/cmd/go/pkg.go:584 +0x3e0c fp=0xc2080cd678 sp=0xc2080cd0b8
		main.loadPackage(0x892ed0, 0x7, 0xc2080defe0, 0x0)
			/home/stephan/go/src/cmd/go/pkg.go:843 +0x881 fp=0xc2080cd8d0 sp=0xc2080cd678
		main.(*builder).action(0xc20806e000, 0x0, 0x0, 0xc2080ff800, 0x1)
			/home/stephan/go/src/cmd/go/build.go:576 +0x52f fp=0xc2080cda88 sp=0xc2080cd8d0
		main.(*builder).action(0xc20806e000, 0x1, 0x0, 0xc20800dc00, 0x1)
			/home/stephan/go/src/cmd/go/build.go:565 +0x273 fp=0xc2080cdc40 sp=0xc2080cda88
		main.runBuild(0xabbe20, 0xc20800a030, 0x0, 0x0)
			/home/stephan/go/src/cmd/go/build.go:301 +0x470 fp=0xc2080cdd98 sp=0xc2080cdc40
		main.main()
			/home/stephan/go/src/cmd/go/main.go:164 +0x608 fp=0xc2080cdf98 sp=0xc2080cdd98
		runtime.main()
			/home/stephan/go/src/runtime/proc.go:86 +0x1d3 fp=0xc2080cdfe0 sp=0xc2080cdf98
		runtime.goexit()
			/home/stephan/go/src/runtime/asm_amd64.s:2430 +0x1 fp=0xc2080cdfe8 sp=0xc2080cdfe0
		
		goroutine 2 [force gc (idle)]:
		runtime.gopark(0x970020, 0xac0f70, 0x8b4790, 0xf)
			/home/stephan/go/src/runtime/proc.go:151 +0x108 fp=0xc20801a798 sp=0xc20801a768
		runtime.goparkunlock(0xac0f70, 0x8b4790, 0xf)
			/home/stephan/go/src/runtime/proc.go:157 +0x48 fp=0xc20801a7c0 sp=0xc20801a798
		runtime.forcegchelper()
			/home/stephan/go/src/runtime/proc.go:120 +0xce fp=0xc20801a7e0 sp=0xc20801a7c0
		runtime.goexit()
			/home/stephan/go/src/runtime/asm_amd64.s:2430 +0x1 fp=0xc20801a7e8 sp=0xc20801a7e0
		created by runtime.init·4
			/home/stephan/go/src/runtime/proc.go:108 +0x33
		
		goroutine 3 [garbage collection]:
		runtime.systemstack_switch()
			/home/stephan/go/src/runtime/asm_amd64.s:199 fp=0xc20801af48 sp=0xc20801af40
		runtime.gcwork(0x0)
			/home/stephan/go/src/runtime/malloc.go:583 +0x2b9 fp=0xc20801afc0 sp=0xc20801af48
		runtime.backgroundgc()
			/home/stephan/go/src/runtime/mgc0.go:87 +0x62 fp=0xc20801afe0 sp=0xc20801afc0
		runtime.goexit()
			/home/stephan/go/src/runtime/asm_amd64.s:2430 +0x1 fp=0xc20801afe8 sp=0xc20801afe0
		created by runtime.gogc
			/home/stephan/go/src/runtime/malloc.go:501 +0xe2
		
		goroutine 4 [finalizer wait]:
		runtime.gopark(0x970020, 0xad5a08, 0x8b3ef0, 0xe)
			/home/stephan/go/src/runtime/proc.go:151 +0x108 fp=0xc20801b748 sp=0xc20801b718
		runtime.goparkunlock(0xad5a08, 0x8b3ef0, 0xe)
			/home/stephan/go/src/runtime/proc.go:157 +0x48 fp=0xc20801b770 sp=0xc20801b748
		runtime.runfinq()
			/home/stephan/go/src/runtime/malloc.go:959 +0xb7 fp=0xc20801b7e0 sp=0xc20801b770
		runtime.goexit()
			/home/stephan/go/src/runtime/asm_amd64.s:2430 +0x1 fp=0xc20801b7e8 sp=0xc20801b7e0
		created by runtime.createfing
			/home/stephan/go/src/runtime/malloc.go:939 +0x68
		
		goroutine 17 [GC sweep wait]:
		runtime.gopark(0x970020, 0xad5a10, 0x8a8130, 0xd)
			/home/stephan/go/src/runtime/proc.go:151 +0x108 fp=0xc20801df98 sp=0xc20801df68
		runtime.goparkunlock(0xad5a10, 0x8a8130, 0xd)
			/home/stephan/go/src/runtime/proc.go:157 +0x48 fp=0xc20801dfc0 sp=0xc20801df98
		runtime.bgsweep()
			/home/stephan/go/src/runtime/mgc0.go:111 +0xdd fp=0xc20801dfe0 sp=0xc20801dfc0
		runtime.goexit()
			/home/stephan/go/src/runtime/asm_amd64.s:2430 +0x1 fp=0xc20801dfe8 sp=0xc20801dfe0
		created by runtime.gc
			/home/stephan/go/src/runtime/mgc.go:2131 +0xe6b
		
		goroutine 5 [syscall]:
		runtime.notetsleepg(0xad6840, 0xffffffffffffffff, 0x1)
			/home/stephan/go/src/runtime/lock_futex.go:198 +0x59 fp=0xc208018768 sp=0xc208018740
		runtime.signal_recv(0x0)
			/home/stephan/go/src/runtime/sigqueue.go:109 +0x135 fp=0xc2080187a0 sp=0xc208018768
		os/signal.loop()
			/home/stephan/go/src/os/signal/signal_unix.go:21 +0x1f fp=0xc2080187e0 sp=0xc2080187a0
		runtime.goexit()
			/home/stephan/go/src/runtime/asm_amd64.s:2430 +0x1 fp=0xc2080187e8 sp=0xc2080187e0
		created by os/signal.init·1
			/home/stephan/go/src/os/signal/signal_unix.go:27 +0x3f
--- FAIL: TestCgoTraceback-4 (0.04s)
	crash_test.go:76: building source: exit status 2
		runtime:greyobject: checkmarks finds unexpected unmarked object obj=0xc20801e030, mbits->bits=0x1 *mbits->bitp=0xf9
		runtime: found obj at *(0xc2080344b0+0x38)
		runtime:greyobject Span: obj=0xc20801e030 k=0x610400f s.start=0xc20801e000 s.limit=0xc208020000 s.sizeclass=1 s.elemsize=8
		 *(obj+0) = 0xc208043530
		fatal error: checkmark found unmarked object
		
		runtime stack:
		runtime.throw(0x8eb8d0, 0x1f)
			/home/stephan/go/src/runtime/panic.go:508 +0x98 fp=0x7fff97c627d0 sp=0x7fff97c627b8
		runtime.greyobject(0xc20801e030, 0xc2080344b0, 0x38, 0x7fff97c628c0, 0x7fd696b37340, 0x7fd696b37340)
			/home/stephan/go/src/runtime/mgc.go:440 +0x2c9 fp=0x7fff97c62830 sp=0x7fff97c627d0
		runtime.scanobject(0xc2080344b0, 0x1cbb50, 0x0, 0x7fd696b37340, 0x7fd696b37340)
			/home/stephan/go/src/runtime/mgc.go:573 +0x3f0 fp=0x7fff97c628e0 sp=0x7fff97c62830
		runtime.drainworkbuf(0x7fd696b37340, 0x300000001)
			/home/stephan/go/src/runtime/mgc.go:650 +0x184 fp=0x7fff97c62910 sp=0x7fff97c628e0
		runtime.scanblock(0x0, 0x0, 0x0)
			/home/stephan/go/src/runtime/mgc.go:610 +0xe5 fp=0x7fff97c62958 sp=0x7fff97c62910
		runtime.gchelper()
			/home/stephan/go/src/runtime/mgc.go:1562 +0x75 fp=0x7fff97c62988 sp=0x7fff97c62958
		runtime.stopm()
			/home/stephan/go/src/runtime/proc1.go:1052 +0x164 fp=0x7fff97c629b0 sp=0x7fff97c62988
		runtime.gcstopm()
			/home/stephan/go/src/runtime/proc1.go:1215 +0xff fp=0x7fff97c629e0 sp=0x7fff97c629b0
		runtime.schedule()
			/home/stephan/go/src/runtime/proc1.go:1424 +0xa4 fp=0x7fff97c62a10 sp=0x7fff97c629e0
		runtime.gosched_m(0xc208000120)
			/home/stephan/go/src/runtime/proc1.go:1535 +0x119 fp=0x7fff97c62a30 sp=0x7fff97c62a10
		runtime.newstack()
			/home/stephan/go/src/runtime/stack1.go:712 +0xa3a fp=0x7fff97c62b88 sp=0x7fff97c62a30
		runtime.morestack()
			/home/stephan/go/src/runtime/asm_amd64.s:311 +0x7e fp=0x7fff97c62b90 sp=0x7fff97c62b88
		
		goroutine 1 [runnable]:
		path/filepath.(*lazybuf).append(0xc2080dd420, 0xc2080fbe66)
			/home/stephan/go/src/path/filepath/path.go:35 fp=0xc2080dd368 sp=0xc2080dd360
		path/filepath.Clean(0xc2080fbf20, 0x30, 0x0, 0x0)
			/home/stephan/go/src/path/filepath/path.go:142 +0x511 fp=0xc2080dd470 sp=0xc2080dd368
		path/filepath.Join(0xc2080c96e0, 0x2, 0x2, 0x0, 0x0)
			/home/stephan/go/src/path/filepath/path.go:202 +0x12f fp=0xc2080dd500 sp=0xc2080dd470
		go/build.(*Context).joinPath(0xac1720, 0xc2080c96e0, 0x2, 0x2, 0x0, 0x0)
			/home/stephan/go/src/go/build/build.go:102 +0x90 fp=0xc2080dd530 sp=0xc2080dd500
		go/build.(*Context).matchFile(0xac1720, 0xc208045f00, 0x1c, 0xc2080b661d, 0x13, 0x1, 0xc2080fa4e0, 0x0, 0x0, 0x0, ...)
			/home/stephan/go/src/go/build/build.go:956 +0x440 fp=0xc2080dd678 sp=0xc2080dd530
		go/build.(*Context).Import(0xac1720, 0x89ad70, 0x7, 0xc2080c9720, 0x1b, 0x4, 0x7fd696b24400, 0x0, 0x0)
			/home/stephan/go/src/go/build/build.go:625 +0x1dcb fp=0xc2080ddfa0 sp=0xc2080dd678
		main.loadImport(0x89ad70, 0x7, 0xc2080c9720, 0x1b, 0xc208045a80, 0x0, 0x0, 0x0, 0x0)
			/home/stephan/go/src/cmd/go/pkg.go:267 +0x4e1 fp=0xc2080de158 sp=0xc2080ddfa0
		main.(*Package).load(0xc20802a400, 0xc208045a80, 0xc2080f6600, 0x0, 0x0, 0x4)
			/home/stephan/go/src/cmd/go/pkg.go:584 +0x3e0c fp=0xc2080de718 sp=0xc2080de158
		main.loadImport(0xc2080c64f1, 0x6, 0xc2080c89e0, 0x18, 0xc208045a80, 0xc208034c30, 0x2, 0x2, 0x0)
			/home/stephan/go/src/cmd/go/pkg.go:275 +0x63d fp=0xc2080de8d0 sp=0xc2080de718
		main.(*Package).load(0xc20802a000, 0xc208045a80, 0xc2080f6000, 0x0, 0x0, 0x4)
			/home/stephan/go/src/cmd/go/pkg.go:584 +0x3e0c fp=0xc2080dee90 sp=0xc2080de8d0
		main.loadImport(0xc2080c64e1, 0x3, 0xc2080c8040, 0x16, 0xc208045a80, 0xc2080b4900, 0x1, 0x1, 0x0)
			/home/stephan/go/src/cmd/go/pkg.go:275 +0x63d fp=0xc2080df048 sp=0xc2080dee90
		main.(*Package).load(0xc20802bc00, 0xc208045a80, 0xc2080f6300, 0x0, 0x0, 0x4)
			/home/stephan/go/src/cmd/go/pkg.go:584 +0x3e0c fp=0xc2080df608 sp=0xc2080df048
		main.loadImport(0x887d10, 0x1, 0xc208044720, 0x16, 0xc208045a80, 0x0, 0x0, 0x0, 0x0)
			/home/stephan/go/src/cmd/go/pkg.go:275 +0x63d fp=0xc2080df7c0 sp=0xc2080df608
		main.loadPackage(0x887d10, 0x1, 0xc208045a80, 0x0)
			/home/stephan/go/src/cmd/go/pkg.go:866 +0xfd6 fp=0xc2080dfa18 sp=0xc2080df7c0
		main.packagesAndErrors(0xc2080c7820, 0x1, 0x1, 0x0, 0x0, 0x0)
			/home/stephan/go/src/cmd/go/pkg.go:905 +0x366 fp=0xc2080dfb30 sp=0xc2080dfa18
		main.packagesForBuild(0xc20800a030, 0x0, 0x0, 0x0, 0x0, 0x0)
			/home/stephan/go/src/cmd/go/pkg.go:918 +0x74 fp=0xc2080dfc40 sp=0xc2080dfb30
		main.runBuild(0xabbe20, 0xc20800a030, 0x0, 0x0)
			/home/stephan/go/src/cmd/go/build.go:266 +0x78 fp=0xc2080dfd98 sp=0xc2080dfc40
		main.main()
			/home/stephan/go/src/cmd/go/main.go:164 +0x608 fp=0xc2080dff98 sp=0xc2080dfd98
		runtime.main()
			/home/stephan/go/src/runtime/proc.go:86 +0x1d3 fp=0xc2080dffe0 sp=0xc2080dff98
		runtime.goexit()
			/home/stephan/go/src/runtime/asm_amd64.s:2430 +0x1 fp=0xc2080dffe8 sp=0xc2080dffe0
		
		goroutine 2 [force gc (idle)]:
		runtime.gopark(0x970020, 0xac0f70, 0x8b4790, 0xf)
			/home/stephan/go/src/runtime/proc.go:151 +0x108 fp=0xc20801a798 sp=0xc20801a768
		runtime.goparkunlock(0xac0f70, 0x8b4790, 0xf)
			/home/stephan/go/src/runtime/proc.go:157 +0x48 fp=0xc20801a7c0 sp=0xc20801a798
		runtime.forcegchelper()
			/home/stephan/go/src/runtime/proc.go:120 +0xce fp=0xc20801a7e0 sp=0xc20801a7c0
		runtime.goexit()
			/home/stephan/go/src/runtime/asm_amd64.s:2430 +0x1 fp=0xc20801a7e8 sp=0xc20801a7e0
		created by runtime.init·4
			/home/stephan/go/src/runtime/proc.go:108 +0x33
		
		goroutine 3 [garbage collection]:
		runtime.systemstack_switch()
			/home/stephan/go/src/runtime/asm_amd64.s:199 fp=0xc20801af48 sp=0xc20801af40
		runtime.gcwork(0x0)
			/home/stephan/go/src/runtime/malloc.go:583 +0x2b9 fp=0xc20801afc0 sp=0xc20801af48
		runtime.backgroundgc()
			/home/stephan/go/src/runtime/mgc0.go:87 +0x62 fp=0xc20801afe0 sp=0xc20801afc0
		runtime.goexit()
			/home/stephan/go/src/runtime/asm_amd64.s:2430 +0x1 fp=0xc20801afe8 sp=0xc20801afe0
		created by runtime.gogc
			/home/stephan/go/src/runtime/malloc.go:501 +0xe2
		
		goroutine 17 [GC sweep wait]:
		runtime.gopark(0x970020, 0xad5a10, 0x8a8130, 0xd)
			/home/stephan/go/src/runtime/proc.go:151 +0x108 fp=0xc20801d798 sp=0xc20801d768
		runtime.goparkunlock(0xad5a10, 0x8a8130, 0xd)
			/home/stephan/go/src/runtime/proc.go:157 +0x48 fp=0xc20801d7c0 sp=0xc20801d798
		runtime.bgsweep()
			/home/stephan/go/src/runtime/mgc0.go:111 +0xdd fp=0xc20801d7e0 sp=0xc20801d7c0
		runtime.goexit()
			/home/stephan/go/src/runtime/asm_amd64.s:2430 +0x1 fp=0xc20801d7e8 sp=0xc20801d7e0
		created by runtime.gc
			/home/stephan/go/src/runtime/mgc.go:2131 +0xe6b
		
		goroutine 4 [finalizer wait]:
		runtime.gopark(0x970020, 0xad5a08, 0x8b3ef0, 0xe)
			/home/stephan/go/src/runtime/proc.go:151 +0x108 fp=0xc20801df48 sp=0xc20801df18
		runtime.goparkunlock(0xad5a08, 0x8b3ef0, 0xe)
			/home/stephan/go/src/runtime/proc.go:157 +0x48 fp=0xc20801df70 sp=0xc20801df48
		runtime.runfinq()
			/home/stephan/go/src/runtime/malloc.go:959 +0xb7 fp=0xc20801dfe0 sp=0xc20801df70
		runtime.goexit()
			/home/stephan/go/src/runtime/asm_amd64.s:2430 +0x1 fp=0xc20801dfe8 sp=0xc20801dfe0
		created by runtime.createfing
			/home/stephan/go/src/runtime/malloc.go:939 +0x68
		
		goroutine 18 [syscall]:
		runtime.notetsleepg(0xad6840, 0xffffffffffffffff, 0x1)
			/home/stephan/go/src/runtime/lock_futex.go:198 +0x59 fp=0xc208018768 sp=0xc208018740
		runtime.signal_recv(0x0)
			/home/stephan/go/src/runtime/sigqueue.go:109 +0x135 fp=0xc2080187a0 sp=0xc208018768
		os/signal.loop()
			/home/stephan/go/src/os/signal/signal_unix.go:21 +0x1f fp=0xc2080187e0 sp=0xc2080187a0
		runtime.goexit()
			/home/stephan/go/src/runtime/asm_amd64.s:2430 +0x1 fp=0xc2080187e8 sp=0xc2080187e0
		created by os/signal.init·1
			/home/stephan/go/src/os/signal/signal_unix.go:27 +0x3f
FAIL
FAIL	runtime	31.182s

**Comment by minux** [comment]
Dup of #9309
