### ISSUE TITLE
Test Suite Crashes on OS X 10.9 at TestGCFairness-2

### ISSUE THREAD

**Issue by BlackGriffen** [golang/go#9564]
Hello all:

I’m running the master branch build script on Mac OS X 10.9.5. The build fails a crash when running the test suite. For what it’s worth, the exact same build and test suite works fine on my OS X 10.10.1 machine that has an identical gcc version.

gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix

The steps I am performing are:
cd /usr/local/go/src #in here is a clone of master
git fetch
git pull
./all.bash

The failure/error text is:
##### GOMAXPROCS=2 runtime -cpu=1,2,4
--- FAIL: TestGCFairness-2 (0.04s)
	crash_test.go:76: building source: exit status 2
		runtime:greyobject: checkmarks finds unexpected unmarked object obj=0xc2080a2080, mbits->bits=0x1 *mbits->bitp=0xb9
		runtime: found obj at *(0xc20805c5f0+0x38)
		runtime:greyobject Span: obj=0xc2080a2080 k=0x6104051 s.start=0xc2080a2000 s.limit=0xc2080a4000 s.sizeclass=1 s.elemsize=8
		 *(obj+0) = 0xc208053410
		fatal error: checkmark found unmarked object
		
		runtime stack:
		runtime.throw(0x4ea0b0, 0x1f)
			/usr/local/go/src/runtime/panic.go:508 +0x98 fp=0x7fff5fbff240 sp=0x7fff5fbff228
		runtime.greyobject(0xc2080a2080, 0xc20805c5f0, 0x38, 0x7fff5fbff330, 0x78d840, 0x78d840)
			/usr/local/go/src/runtime/mgc.go:440 +0x2c9 fp=0x7fff5fbff2a0 sp=0x7fff5fbff240
		runtime.scanobject(0xc20805c5f0, 0x1a3a10, 0x0, 0x78d840, 0x78d840)
			/usr/local/go/src/runtime/mgc.go:573 +0x3f0 fp=0x7fff5fbff350 sp=0x7fff5fbff2a0
		runtime.drainworkbuf(0x78d840, 0x300000001)
			/usr/local/go/src/runtime/mgc.go:650 +0x184 fp=0x7fff5fbff380 sp=0x7fff5fbff350
		runtime.scanblock(0x0, 0x0, 0x0)
			/usr/local/go/src/runtime/mgc.go:610 +0xe5 fp=0x7fff5fbff3c8 sp=0x7fff5fbff380
		runtime.gchelper()
			/usr/local/go/src/runtime/mgc.go:1562 +0x75 fp=0x7fff5fbff3f8 sp=0x7fff5fbff3c8
		runtime.stopm()
			/usr/local/go/src/runtime/proc1.go:1052 +0x164 fp=0x7fff5fbff420 sp=0x7fff5fbff3f8
		runtime.gcstopm()
			/usr/local/go/src/runtime/proc1.go:1215 +0xff fp=0x7fff5fbff450 sp=0x7fff5fbff420
		runtime.schedule()
			/usr/local/go/src/runtime/proc1.go:1424 +0xa4 fp=0x7fff5fbff480 sp=0x7fff5fbff450
		runtime.gosched_m(0xc208000120)
			/usr/local/go/src/runtime/proc1.go:1535 +0x119 fp=0x7fff5fbff4a0 sp=0x7fff5fbff480
		runtime.newstack()
			/usr/local/go/src/runtime/stack1.go:712 +0xa3a fp=0x7fff5fbff5f8 sp=0x7fff5fbff4a0
		runtime.morestack()
			/usr/local/go/src/runtime/asm_amd64.s:311 +0x7e fp=0x7fff5fbff600 sp=0x7fff5fbff5f8
		
		goroutine 1 [runnable]:
		go/build.(*importReader).readByte(0xc2080ed040, 0x87620)
			/usr/local/go/src/go/build/read.go:40 fp=0xc2080d1498 sp=0xc2080d1490
		go/build.(*importReader).peekByte(0xc2080ed040, 0x495401, 0x22)
			/usr/local/go/src/go/build/read.go:89 +0x164 fp=0xc2080d14d8 sp=0xc2080d1498
		go/build.readImports(0x78ddc0, 0xc2080a2100, 0xc2080a2100, 0x0, 0x0, 0x0, 0x0, 0x0)
			/usr/local/go/src/go/build/read.go:209 +0x108 fp=0xc2080d1530 sp=0xc2080d14d8
		go/build.(*Context).matchFile(0x6bcfe0, 0xc208064ba0, 0x19, 0xc2080b590a, 0x9, 0xc208076001, 0xc2080e9740, 0x0, 0x0, 0x0, ...)
			/usr/local/go/src/go/build/build.go:963 +0x5be fp=0xc2080d1678 sp=0xc2080d1530
		go/build.(*Context).Import(0x6bcfe0, 0x499f10, 0x7, 0xc20805f7a0, 0x18, 0x4, 0x77b000, 0x0, 0x0)
			/usr/local/go/src/go/build/build.go:625 +0x1dcb fp=0xc2080d1fa0 sp=0xc2080d1678
		main.loadImport(0x499f10, 0x7, 0xc20805f7a0, 0x18, 0xc20805ea20, 0x0, 0x0, 0x0, 0x0)
			/usr/local/go/src/cmd/go/pkg.go:267 +0x4e1 fp=0xc2080d2158 sp=0xc2080d1fa0
		main.(*Package).load(0xc208021800, 0xc20805ea20, 0xc20800c900, 0x0, 0x0, 0x4)
			/usr/local/go/src/cmd/go/pkg.go:584 +0x3e0c fp=0xc2080d2718 sp=0xc2080d2158
		main.loadImport(0xc2080a08f1, 0x6, 0xc20805e960, 0x15, 0xc20805ea20, 0xc20805cb40, 0x2, 0x2, 0x0)
			/usr/local/go/src/cmd/go/pkg.go:275 +0x63d fp=0xc2080d28d0 sp=0xc2080d2718
		main.(*Package).load(0xc208021400, 0xc20805ea20, 0xc20800c300, 0x0, 0x0, 0x4)
			/usr/local/go/src/cmd/go/pkg.go:584 +0x3e0c fp=0xc2080d2e90 sp=0xc2080d28d0
		main.loadImport(0xc2080a00eb, 0x3, 0xc20805d6d0, 0x4a, 0xc20805ea20, 0xc208053860, 0x1, 0x1, 0x0)
			/usr/local/go/src/cmd/go/pkg.go:275 +0x63d fp=0xc2080d3048 sp=0xc2080d2e90
		main.(*Package).load(0xc2080de000, 0xc20805ea20, 0xc20800c600, 0x0, 0x0, 0x4)
			/usr/local/go/src/cmd/go/pkg.go:584 +0x3e0c fp=0xc2080d3608 sp=0xc2080d3048
		main.loadImport(0x486df0, 0x1, 0xc2080464b0, 0x4a, 0xc20805ea20, 0x0, 0x0, 0x0, 0x0)
			/usr/local/go/src/cmd/go/pkg.go:275 +0x63d fp=0xc2080d37c0 sp=0xc2080d3608
		main.loadPackage(0x486df0, 0x1, 0xc20805ea20, 0x0)
			/usr/local/go/src/cmd/go/pkg.go:866 +0xfd6 fp=0xc2080d3a18 sp=0xc2080d37c0
		main.packagesAndErrors(0xc2080a13f0, 0x1, 0x1, 0x0, 0x0, 0x0)
			/usr/local/go/src/cmd/go/pkg.go:905 +0x366 fp=0xc2080d3b30 sp=0xc2080d3a18
		main.packagesForBuild(0xc20800a030, 0x0, 0x0, 0x0, 0x0, 0x0)
			/usr/local/go/src/cmd/go/pkg.go:918 +0x74 fp=0xc2080d3c40 sp=0xc2080d3b30
		main.runBuild(0x6b7c20, 0xc20800a030, 0x0, 0x0)
			/usr/local/go/src/cmd/go/build.go:266 +0x78 fp=0xc2080d3d98 sp=0xc2080d3c40
		main.main()
			/usr/local/go/src/cmd/go/main.go:164 +0x608 fp=0xc2080d3f98 sp=0xc2080d3d98
		runtime.main()
			/usr/local/go/src/runtime/proc.go:86 +0x1d3 fp=0xc2080d3fe0 sp=0xc2080d3f98
		runtime.goexit()
			/usr/local/go/src/runtime/asm_amd64.s:2430 +0x1 fp=0xc2080d3fe8 sp=0xc2080d3fe0
		
		goroutine 2 [force gc (idle)]:
		runtime.gopark(0x56e330, 0x6bc8b0, 0x4b3850, 0xf)
			/usr/local/go/src/runtime/proc.go:151 +0x108 fp=0xc20801a798 sp=0xc20801a768
		runtime.goparkunlock(0x6bc8b0, 0x4b3850, 0xf)
			/usr/local/go/src/runtime/proc.go:157 +0x48 fp=0xc20801a7c0 sp=0xc20801a798
		runtime.forcegchelper()
			/usr/local/go/src/runtime/proc.go:120 +0xce fp=0xc20801a7e0 sp=0xc20801a7c0
		runtime.goexit()
			/usr/local/go/src/runtime/asm_amd64.s:2430 +0x1 fp=0xc20801a7e8 sp=0xc20801a7e0
		created by runtime.init·4
			/usr/local/go/src/runtime/proc.go:108 +0x33
		
		goroutine 3 [garbage collection]:
		runtime.systemstack_switch()
			/usr/local/go/src/runtime/asm_amd64.s:199 fp=0xc20801af48 sp=0xc20801af40
		runtime.gcwork(0x0)
			/usr/local/go/src/runtime/malloc.go:583 +0x2b9 fp=0xc20801afc0 sp=0xc20801af48
		runtime.backgroundgc()
			/usr/local/go/src/runtime/mgc0.go:87 +0x62 fp=0xc20801afe0 sp=0xc20801afc0
		runtime.goexit()
			/usr/local/go/src/runtime/asm_amd64.s:2430 +0x1 fp=0xc20801afe8 sp=0xc20801afe0
		created by runtime.gogc
			/usr/local/go/src/runtime/malloc.go:501 +0xe2
		
		goroutine 17 [GC sweep wait]:
		runtime.gopark(0x56e330, 0x6d12d8, 0x4a71b0, 0xd)
			/usr/local/go/src/runtime/proc.go:151 +0x108 fp=0xc20801d798 sp=0xc20801d768
		runtime.goparkunlock(0x6d12d8, 0x4a71b0, 0xd)
			/usr/local/go/src/runtime/proc.go:157 +0x48 fp=0xc20801d7c0 sp=0xc20801d798
		runtime.bgsweep()
			/usr/local/go/src/runtime/mgc0.go:111 +0xdd fp=0xc20801d7e0 sp=0xc20801d7c0
		runtime.goexit()
			/usr/local/go/src/runtime/asm_amd64.s:2430 +0x1 fp=0xc20801d7e8 sp=0xc20801d7e0
		created by runtime.gc
			/usr/local/go/src/runtime/mgc.go:2131 +0xe6b
		
		goroutine 4 [finalizer wait]:
		runtime.gopark(0x56e330, 0x6d12d0, 0x4b2f90, 0xe)
			/usr/local/go/src/runtime/proc.go:151 +0x108 fp=0xc208018748 sp=0xc208018718
		runtime.goparkunlock(0x6d12d0, 0x4b2f90, 0xe)
			/usr/local/go/src/runtime/proc.go:157 +0x48 fp=0xc208018770 sp=0xc208018748
		runtime.runfinq()
			/usr/local/go/src/runtime/malloc.go:959 +0xb7 fp=0xc2080187e0 sp=0xc208018770
		runtime.goexit()
			/usr/local/go/src/runtime/asm_amd64.s:2430 +0x1 fp=0xc2080187e8 sp=0xc2080187e0
		created by runtime.createfing
			/usr/local/go/src/runtime/malloc.go:939 +0x68
		
		goroutine 18 [syscall]:
		runtime.notetsleepg(0x6d1ca0, 0xffffffffffffffff, 0x1)
			/usr/local/go/src/runtime/lock_sema.go:262 +0x93 fp=0xc208018f68 sp=0xc208018f28
		runtime.signal_recv(0x0)
			/usr/local/go/src/runtime/sigqueue.go:109 +0x135 fp=0xc208018fa0 sp=0xc208018f68
		os/signal.loop()
			/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f fp=0xc208018fe0 sp=0xc208018fa0
		runtime.goexit()
			/usr/local/go/src/runtime/asm_amd64.s:2430 +0x1 fp=0xc208018fe8 sp=0xc208018fe0
		created by os/signal.init·1
			/usr/local/go/src/os/signal/signal_unix.go:27 +0x3f
FAIL
FAIL	runtime	22.548s

**Comment by minux** [comment]
Dup of #9309.

**Comment by BlackGriffen** [comment]
Since #9309 is also closed, I’ll leave this comment here. On a machine that runs on a Core2 Duo, and is under extremely heavy io contention, the crash does not occur. So, yeah, it’s likely a race condition.
