### ISSUE TITLE
build: nacl build broken on dev.cc branch

### ISSUE THREAD

**Issue by bradfitz** [golang/go#9574]
The new Go-based dist and nacl don't work together yet.

```
bradfitz@laptop src$ GOROOT_BOOTSTRAP=/Users/bradfitz/prevgo/go1.4 GOOS=nacl GOARCH=amd64p32 ./make.bash 
##### Building Go bootstrap tool.
cmd/dist
./make.bash: line 127: ./cmd/dist/dist: cannot execute binary file

bradfitz@laptop src$ file cmd/dist/dist 
cmd/dist/dist: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped

bradfitz@laptop src$ uname -a
Darwin bradfitz-macbookpro.roam.corp.google.com 13.4.0 Darwin Kernel Version 13.4.0: Sun Aug 17 19:50:11 PDT 2014; root:xnu-2422.115.4~1/RELEASE_X86_64 x86_64
```

/cc @minux

**Comment by davecheney** [comment]
@bradfitz IMO you should use `nacltest.bash` not `make. bash`, although that doesn't completely fix the problem

```
lucky(~/go.devcc/src) % ./nacltest.bash 2>&1 | tail -n 4
Installed commands in /home/dfc/go.devcc/bin
##### Building Go bootstrap tool.
cmd/dist
go build runtime: nacl/amd64p32 must be bootstrapped using make.bash
```

**Comment by minux** [comment]
The general problem is that cross compiling on dev.cc branch is completely
broken.

$ GOARCH=arm ./make.bash
##### Building Go bootstrap tool.
cmd/dist
go build runtime: linux/arm must be bootstrapped using make.bash

**Comment by bradfitz** [comment]
@davecheney, I know about nacltest.sh. That's like all.bash. I was reporting about make.bash, which happens earlier (and is called by nacltest.sh).

You can get past the "must be bootstrapped" issue by running make.bash in the $GOROOT_BOOTSTRAP/src directory, but that doesn't feel like what we want to be doing.

I agree with Minux that there's some missing part of the cross-compilation story.

**Comment by davecheney** [comment]
@bradfitz yup, sorry, my suggestion was not helpful. The error comes from `cmd/go/build.go:818`. I agree that the new cmd/dist probably isn't producing the cross compilation parts.
