### ISSUE TITLE
net/http: TestResponseWriterWriteStringAllocs fails on windows-amd64

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#9575]
windows-amd64 build http://build.golang.org/log/f117061c3ee9fa9bb29820834431b964d9137d71 fails with 

--- FAIL: TestResponseWriterWriteStringAllocs (0.01s)
	serve_test.go:2398: WriteString allocs of 21 >= Write allocs of 21
FAIL
FAIL	net/http	8.384s

**Comment by minux** [comment]
Not a windows specific problem.

On linux/amd64:
$ go test net/http -v -run=TestResponseWriterWriteStringAllocs
=== RUN TestResponseWriterWriteStringAllocs
--- FAIL: TestResponseWriterWriteStringAllocs (0.07s)
serve_test.go:2398: WriteString allocs of 39 >= Write allocs of 22
FAIL
exit status 1
FAIL net/http 0.070s


I think a lot of allocation tests are broken after the interface pointer
change.
(Esp. those not run during -short)

**Comment by alexbrainman** [comment]
It seems this happened before and has been corrected by increasing number of testing.AllocsPerRun:

commit 542415c9df03e40a99ef9eb1005e43ba2cadc46a
Author: Brad Fitzpatrick <bradfitz@golang.org>
Date:   Tue Mar 4 09:59:07 2014 -0800

net/http: deflake another alloc test

I have one machine where this 25 test run is flaky
and fails ("21 >= 21"), but 50 works everywhere.

LGTM=josharian
R=josharian
CC=golang-codereviews
https://golang.org/cl/67870053

It appears my problem goes away if I increase that number again to 100. Should I send a CL?

Alex

**Comment by minux** [comment]
we need to ask @bradfitz to decide.

**Comment by bradfitz** [comment]
Sent https://go-review.googlesource.com/2720
