### ISSUE TITLE
x/build: tracking bug for Android armv7 builders

### ISSUE THREAD

**Issue by rakyll** [golang/go#9579]
I'm working on the android-armv7 builder according to the plan explained on https://golang.org/s/builderplan.

The plan is to depend on one of the official armv7 Android emulator images -- Android emulator is based on qemu-kvm and does arm emulation.

I've drafted the initial work on https://go-review.googlesource.com/#/c/2730/.

**Comment by bradfitz** [comment]
Unfortunately we can't run KVM on GCE. They've disabled nested KVM it seems.

**Comment by rakyll** [comment]
I know the team that's working on nested-KVM on GCE, and in contact. It's likely that I can share more details soon.

**Comment by rakyll** [comment]
Btw, this is already rolled out to the GCE, not an upcoming project or anything. I was able to run the Android emulator on a bare ubuntu instance earlier today and the tests are passing. They are 30x slower as usual.

**Comment by bradfitz** [comment]
I doubt it's using KVM, then. I tried to use qemu with KVM the other day for Plan 9 and it didn't work. I had to use my home Linux server instead.

**Comment by eliasnaur** [comment]
With android/amd64 and android/386 running I don't think we need this. There are device builders that test on real devices for arm and arm64.
