### ISSUE TITLE
cmd/oracle: cannot handle import while go tool can

### ISSUE THREAD

**Issue by anacrolix** [golang/go#9581]
I have an import of the form:

    utp "."

Using it I refer to public names in the current module with the prefix "utp". The go tool "oracle" doesn't like it, but the go tool is fine with it. This makes oracle unusable for this code.

**Comment by ianlancetaylor** [comment]
What you describe seems like a strange thing to do and I doubt it would work as you expect.  That said, I tried writing an example, but I failed.  I consistently get

local import "." in non-local package

What version of Go are you using?  Can you provide a complete example?

**Comment by anacrolix** [comment]
The import is in a _test file. go version devel +1de9c40 Fri Jan 9 00:09:42 2015 +0000 darwin/amd64

**Comment by griesemer** [comment]
Here's a complete example. In a directory "bug", with two files x.go and x_test.go:

$ cat x.go
package main
var X = 7
func main() {}

$ cat x_test.go 
package main
import a "."
import "testing"
func Test(t *testing.T) {
	println(a.X)
	println(X)
}

It is possible to run go test:

$ go test
7
7
PASS
ok  	bug	0.011s

However, (x/tools/cmd/) gotype doesn't like the import of "." (gotype is doing the equivalent of what the oracle would be doing, more or less):

$ gotype -v -a .
x.go
x_test.go
x_test.go:3:10: could not import . (can't find import: /Users/gri/go/src/bug)
x_test.go:7:10: undeclared name: a

**Comment by ianlancetaylor** [comment]
Thanks for the example.

Note that any global variables will be different.  The instance of the variable in the package itself will not be the same as the instance in the imported package.

Consider

package p

import (
	"testing"

	a "."
)

func Test(t *testing.T) {
	X = 2
	a.X = 3
	println(X)
	println(a.X)
}

You will see that the two variables are different, although they seem to have the same name.

It's hard to see any good reason to support this.

**Comment by griesemer** [comment]
As iant pointed out, there's no good reason for making this work - the behavior of

import "."

is obscure at best and (w/o some manual bootstrapping) won't work reliably outside test packages. I briefly investigated the cause for the error message in the responsible package (x/tools/go/gcimporter package). There's simply no provision for the case of "." imports, and it's not trivially clear what would have to be done if one wanted to make it work.

Will not fix.
