### ISSUE TITLE
quoted-printable

### ISSUE THREAD

**Issue by mattn** [golang/go#9583]
Currently, AFAIK, There is no public APIs to make quoted-printable string. In japanese, subject header on e-mails are encoded like below.

  Subject: ?ISO-2022-JP?Q?=1B=24B=243=24s=24K=24A=24o=40=243=26=1B=28B?=

Below is a decoded string from ISO-2022-JP/quoted printable text in above:

  Subject: こんにちわ世界

And body is also encoded as iso-2022-jp encoding. I know that it's possible to transfer bytes into ISO-2022-JP by golang.org/x/text/encoding/japanese, but we can't make quoted printable string by go package. (I know it's not difficult to make quoted-printable string, but i want official package)
Do you have a plan to make public APIs for quoted-printable?

**Comment by bradfitz** [comment]
Dup of #4943

**Comment by mattn** [comment]
You are right. Currently work in progress for making Writer?
