### ISSUE TITLE
json marshal does not obey omitempty for empty structures

### ISSUE THREAD

**Issue by jordan2175** [golang/go#9585]
Given this code 

https://play.golang.org/p/9Y92Vqf8Bb

you will see that I have not specified in the raw JSON data any data for the validTimePosition, however, when you run the marshal process it shows up, as illustrated below.  I would expect that it would not show up at all, if it is empty. 

{
    "stixPackage": {
        "version": "1.1.1",
        "validTimePosition": {}
    }
}

**Comment by adg** [comment]
A struct value cannot be 'empty', so it cannot be omitted. You need to use a pointer to a struct:

https://play.golang.org/p/w4s_S-nUKw

**Comment by jordan2175** [comment]
Thanks....
