### ISSUE TITLE
x/blog: protocol relative urls in atom feed breaks links in rss readers

### ISSUE THREAD

**Issue by jbub** [golang/go#9587]
The links in the http://blog.golang.org/feed.atom feed contains protocol relative urls and those are not very well understood in many RSS readers.

For example in NetNewsWrite this link:
//blog.golang.org/errors-are-values

Becomes this in Chrome:
file://blog.golang.org/errors-are-values

I think we should include protocols in the links until RSS readers become smarter.

**Comment by mattn** [comment]
FYI, FeedValidator returns VALID

http://feedvalidator.org/check.cgi?url=http%3A%2F%2Fblog.golang.org%2Ffeed.atom
