### ISSUE TITLE
net/http/httputil: the default Director created by NewSingleHostReverseProxy can't pass through %2F 

### ISSUE THREAD

**Issue by minux** [golang/go#9589]
I know why this is the case and I know the (current) correct solution.

However, I think the default Director should use req.RequestURI and
URL.Opaque as much as possible so that trivial use of NewSingleHostReverseProxy
don't need to write ones' own Director implementation.

Thoughts?

PS: I was hit this problem because I wrote a reverse proxy for my
Gerrit instance, and Gerrit uses %2F a lot.

**Comment by minux** [comment]
@bradfitz what do you think?

**Comment by bradfitz** [comment]
I would accept a patch but I'm not entirely motivated to do this myself.

But keep in mind that I like keeping ReverseProxy and NewSingleHostReverseProxy readable (as much as possible) for pedagogical purposes. So if you fix this, I'd prefer if you went out of your way to special case the `%2F` path with extra comments and keep the old path (even if it's redundant) just so people can read and see what the obvious way is, and why the `%2F` way is the more ugly & hard-to-read case.

You want to do this, @minux?

**Comment by rsc** [comment]
I think my changes to url.URL to preserve %2F probably fixed this. There's no test case, so can't be sure. But pretty sure.
