### ISSUE TITLE
runtime: implement raiseproc everywhere

### ISSUE THREAD

**Issue by bradfitz** [golang/go#9591]
Commit 5bfed7c6 ("runtime: log all thread stack traces during GODEBUG=crash on Linux and OS X") broke OpenBSD, etc.

http://build.golang.org/log/3c1aaccdeee7951ff4f5a670c98abe1967c127f9
```
...
go/build
cmd/go
runtime.sighandler: runtime.raiseproc: not defined
runtime.sighandler: undefined: runtime.raiseproc
go tool dist: FAILED: /tmp/buildlet-scatch781630640/pkg/tool/openbsd_amd64/6l -o /tmp/buildlet-scatch781630640/pkg/tool/openbsd_amd64/go_bootstrap $WORK/_go_.a
``

**Comment by rsc** [comment]
https://go-review.googlesource.com/#/c/2830/ fixes the build, but it still needs to be written everywhere. Perhaps not yet.

**Comment by mdempsky** [comment]
For what it's worth, runtime.raiseproc on OpenBSD would be identical to runtime.raise, except it should invoke sys_getpid ($20) instead of sys_getthrid ($299).
