### ISSUE TITLE
doc: problematic example for composite literals

### ISSUE THREAD

**Issue by CatTail** [golang/go#9595]
In [effective go](https://go.googlesource.com/go/+/release-branch.go1.4/doc/effective_go.html) L1245, there are example of describe how to use composite literals to initialize `array` and `map`, 

```go
a := [...]string   {Enone: "no error", Eio: "Eio", Einval: "invalid argument"}
s := []string      {Enone: "no error", Eio: "Eio", Einval: "invalid argument"}
m := map[int]string{Enone: "no error", Eio: "Eio", Einval: "invalid argument"}
```

But these example are incorrect.

**Comment by cespare** [comment]
They seem fine to me.

**Comment by cespare** [comment]
http://play.golang.org/p/hcKalEJzTE

**Comment by CatTail** [comment]
Sorry, I'm an newbie in golang, it seemed wire for me that in

```go
&File{fd: fd, name: name}
```

`fd` literal means field while in

```go
a := [...]string   {Enone: "no error", Eio: "Eio", Einval: "invalid argument"}
```

`Enone` will first being evaluated before decide which field it belongs to.

**Comment by minux** [comment]
Please ask the question on the golang-nuts mailing list.
The issue track is not for explanation of basic language
features. Thanks.
