### ISSUE TITLE
cmd/vet: Bad syntax for struct tag value only on go1.4 linux/amd64

### ISSUE THREAD

**Issue by kargakis** [golang/go#9597]
https://travis-ci.org/kargakis/cryptowallet/builds/47078554

Travis complains when vetting on the linux/amd64 tip branch. It's strange because when running locally ```go vet``` (go1.4 windows/amd64) I don't get any error back.

**Comment by minux** [comment]
Are you sure you've installed the latest go vet command?
the stricter struct tag check is just introduced.

go get -u golang.org/x/tools/cmd/vet

**Comment by kargakis** [comment]
Yup, you were right, I had to update go vet. 

Thanks
