### ISSUE TITLE
runtime/pprof: build occasionally fails at TestCPUProfileMultithreaded

### ISSUE THREAD

**Issue by rakyll** [golang/go#9605]
TestCPUProfileMultithreaded occasionally fails for GOOS=android and GOARCH=arm.

834 KB/s (2368016 bytes in 2.770s)
go_android_exec: adb shell cp '/data/local/tmp/goroot/pprof.test-3947-tmp' '/data/local/tmp/goroot/pprof.test-3947'
go_android_exec: adb shell rm '/data/local/tmp/goroot/pprof.test-3947-tmp'
go_android_exec: adb shell export TMPDIR="/data/local/tmp"; export GOROOT="/data/local/tmp/goroot"; cd "$GOROOT/src/runtime/pprof"; '/data/local/tmp/goroot/pprof.test-3947' -test.short=true -test.timeout=360s; echo -n exitcode=$?
--- FAIL: TestCPUProfileMultithreaded (3.60s)
	pprof_test.go:165: runtime/pprof_test.cpuHog1: 0
	pprof_test.go:165: runtime/pprof_test.cpuHog2: 61
	pprof_test.go:179: runtime/pprof_test.cpuHog1 has 0 samples out of 61, want at least 1, ideally 30
FAIL

**Comment by bradfitz** [comment]
qemu, right?

**Comment by rakyll** [comment]
Android emulator ARM v7a. It's not exactly what the mainline qemu is.

**Comment by bradfitz** [comment]
These tests have never run well under qemu. I'd just skip them when under this environment.

Maybe set an IN_QEMU=1 environment variable, and t.Skip based on that.

**Comment by rakyll** [comment]
Mailed https://go-review.googlesource.com/#/c/3000/.

**Comment by 4ad** [comment]
This test is extremely flaky even on real arm64 hardware.
