### ISSUE TITLE
cmd/gc: dead-code elimination for switch statements with constant expressions

### ISSUE THREAD

**Issue by mdempsky** [golang/go#9608]
Commit 5bfed7c ("runtime: log all thread stack traces during GODEBUG=crash on Linux and OS X") broke several architectures because it expected that

    const GOOS = "openbsd"
    switch GOOS {
    case "linux", "darwin":
        raiseproc(_SIGQUIT)
    }

would optimize away the call to raiseproc(), so it wouldn't matter that it wasn't implemented on other architectures.  However, cmd/gc optimizes "if" statements with constant conditions, but it doesn't optimize "switch" statements with constant expressions.  E.g.

    $ cat foo.go
    package foo
    
    func f() bool {
    	const x = 0
    	switch x {
    	case 0:
    		return true
    	}
    	return false
    }
    
    func g() bool {
    	const x = 0
    	if x == 0 {
    		return true
    	}
    	return false
    }

    $ go tool 6g -S foo.go
    "".f t=1 size=32 value=0 args=0x8 locals=0x0
    	0x0000 00000 (foo.go:3)	TEXT	"".f+0(SB),4,$0-8
    	0x0000 00000 (foo.go:3)	NOP	,
    	0x0000 00000 (foo.go:3)	NOP	,
    	0x0000 00000 (foo.go:3)	FUNCDATA	$0,gclocals·a7a3692b8e27e823add69ec4239ba55f+0(SB)
    	0x0000 00000 (foo.go:3)	FUNCDATA	$1,gclocals·3280bececceccd33cb74587feedb1f9f+0(SB)
    	0x0000 00000 (foo.go:5)	MOVQ	$0,AX
    	0x0002 00002 (foo.go:6)	CMPQ	AX,$0
    	0x0006 00006 (foo.go:6)	JNE	,14
    	0x0008 00008 (foo.go:7)	MOVB	$1,"".~r0+8(FP)
    	0x000d 00013 (foo.go:7)	RET	,
    	0x000e 00014 (foo.go:9)	MOVB	$0,"".~r0+8(FP)
    	0x0013 00019 (foo.go:9)	RET	,
    	0x0000 31 c0 48 83 f8 00 75 06 c6 44 24 08 01 c3 c6 44  1.H...u..D$....D
    	0x0010 24 08 00 c3                                      $...
    "".g t=1 size=16 value=0 args=0x8 locals=0x0
    	0x0000 00000 (foo.go:12)	TEXT	"".g+0(SB),4,$0-8
    	0x0000 00000 (foo.go:12)	NOP	,
    	0x0000 00000 (foo.go:12)	NOP	,
    	0x0000 00000 (foo.go:12)	FUNCDATA	$0,gclocals·a7a3692b8e27e823add69ec4239ba55f+0(SB)
    	0x0000 00000 (foo.go:12)	FUNCDATA	$1,gclocals·3280bececceccd33cb74587feedb1f9f+0(SB)
    	0x0000 00000 (foo.go:15)	MOVB	$1,"".~r0+8(FP)
    	0x0005 00005 (foo.go:15)	RET	,
    	0x0000 c6 44 24 08 01 c3                                .D$...

**Comment by bradfitz** [comment]
Josh sent https://go-review.googlesource.com/3980
