### ISSUE TITLE
math/big: AndNot(x,y) doesn't work when x is positive and y is negative

### ISSUE THREAD

**Issue by randall77** [golang/go#9609]
package main

import (
	"fmt"
	"math/big"
)

func main() {
	fmt.Println(new(big.Int).AndNot(big.NewInt(0xff), big.NewInt(-1)))
}

This should print 0.  It does print 2.
The bug is in math/big/int.go:893, it should use sub, not add, as the comment in the previous line specifies.

**Comment by rsc** [comment]
Not obvious why this was 1.4.2 worthy.
