### ISSUE TITLE
runtime: leftover defers

### ISSUE THREAD

**Issue by bradfitz** [golang/go#9610]
The linux-amd64-clang builder has been complaining about leftover defers.

I have no clue why it's only the clang builder, but there are three of them recently.

```
runtime: g1832: leftover defer sp=0xdeaddeaddeaddead pc=0x405a9c
	defer 0xc2086a45f0 sp=0xdeaddeaddeaddead pc=0x405a9c
	defer 0xc2086c2060 sp=0xdeaddeaddeaddead pc=0x40500e
fatal error: traceback has leftover defers
```

In:

http://build.golang.org/log/ca786e4aaa24e7be4e66e1a0e5f81a8572dbf8fc
http://build.golang.org/log/39ff914cd33ad824bb874853592ea3a2f3fd7221
http://build.golang.org/log/aad8bdc0026b36def50c43a426212ed546d80b70

**Comment by bradfitz** [comment]
I also see these on the Windows builders.

/cc @rsc @minux

**Comment by egonelbre** [comment]
Got one recently as well https://gist.github.com/egonelbre/e6d0d22e73953300c9a8

go version devel +4e03bbb Sat Jan 10 00:23:04 2015 +0000 windows/amd64

**Comment by alexbrainman** [comment]
I cannot reproduce it here. But I didn't tried hard enough.

Alex

**Comment by mattyw** [comment]
I just had this error as well: https://gist.github.com/mattyw/31e701977f213ac07279
I've taken off parts of the traceback to hide some proprietary stuff - if you need more let me know and I'll see what I can do.

go version devel +1757b5c Thu Dec 11 07:31:32 2014 +0000 linux/amd64

The process had been running for >3 days when this occurred

**Comment by randall77** [comment]
I haven't seen one of these in a while.  Please reopen if you're still seeing it.
