### ISSUE TITLE
os: FileInfo.Sys should return underlying data source on Windows

### ISSUE THREAD

**Issue by perillo** [golang/go#9611]
The documentation of the Sys method for the FileInfo interface says:
"underlying data source (can return nil)"

However the Windows implementation does not do this.

The underlying data source for the FileInfo implementation in the Stat function is
syscall.ByHandleFileInformation, however the Sys method returns syscall.Win32FileAttributeData.

The underlying data source for the FileInfo implementation in the Readdir method is syscall.Win32finddata, however the Sys method returns syscall.Win32FleAttributeData.

The advantage of the current implementation is that Sys returns the same dynamic type, as it is done on Unix systems.  However the disadvantage is that some valuable information (VolumeInformation and FineIndex from the Stat call) is thrown away.  The current implementation also has to allocate additional space.

Since the interface documentation seems to allow it, I propose that the Sys method returns the actual underlying data used by the implementation, ad discussed above.

The change does not break the go 1 compatibility promise.

**Comment by alexbrainman** [comment]
@ianlancetaylor please assign it to me, if you want me to try and implement it. Tank you.

Alex

**Comment by ianlancetaylor** [comment]
I don't have an opinion on whether we should do this or not.  I'll assign it to you so that you can decide.

**Comment by minux** [comment]
I still think this is a API change, although a less obvious one.

**Comment by alexbrainman** [comment]
I don't think we should be making this change. We don't want to break people's code. Closing this as "unfortunate".

https://groups.google.com/forum/#!topic/golang-dev/Kky-9-TrcWY for full discussion.

Alex

**Comment by perillo** [comment]
On Sun, Jan 18, 2015 at 6:43 AM, alexbrainman <notifications@github.com>
wrote:

> I don't think we should be making this change. We don't want to break
> people's code. Closing this as "unfortunate".
>

It's unfortunate, since this is a private API and the go fix tool should be
able to upgrade the old code.
