### ISSUE TITLE
Go 1.1 Release Notes on Method Values

### ISSUE THREAD

**Issue by nautigar** [golang/go#9612]
In the release notes for Go 1.1 at 

https://golang.org/doc/go1.1#method_values,

the section on method values states:

"For instance, given a Writer value w, the expression w.Write, a method value, is a function that will always write to w; it is equivalent to a function literal closing over w".

However, a method value will capture the current value of w at the time w.Write is evaluated, while a function literal closing over w will capture the variable itself. If w is changed before the function is actually called, the closure will use the changed value, while the method value will remember the original value. Therefore, I think the statement cited above is not correct.

If I am missing something, please enlighten me :-)

**Comment by ianlancetaylor** [comment]
I think you're right.  That said, I don't think we're going to change the 1.1 release notes now.  What matters is the current documentation.

Please do not ask questions by opening issues.  Please use the golang-nuts@googlegroups.com mailing list to ask questions.  Thanks.
