### ISSUE TITLE
x/tools/cmd/godoc: Malformed links in variable definition

### ISSUE THREAD

**Issue by titanous** [golang/go#9613]
The documentation for [`http.DefaultTransport`](https://golang.org/pkg/net/http/#RoundTripper) currently looks like this:

![screen shot 2015-01-16 at 1 21 10 pm](https://cloud.githubusercontent.com/assets/13026/5781662/9706c7d0-9d82-11e4-8485-bc112cfbbebf.png)

There are a bunch of things linked that should not be, including all of the field names and the `Dial` method.

**Comment by vbmade2000** [comment]
@alandonovan Can I take a look on this issue and create PR ? If you don't mind.

**Comment by griesemer** [comment]
@vbmade2000 You're welcome to have a look and send a PR/review request, but you may want to keep an eye out for the pending fix for (related) issue #22803 which is in progress, which may change how this looks.

**Comment by vbmade2000** [comment]
@griesemer Sure. May be I should create PR after #22803 gets merged.

**Comment by agnivade** [comment]
> May be I should create PR after #22803 gets merged.

Yes, thanks. This most probably needs work in godoc/linkify.go. Feel free to cc me when you send the CL.

**Comment by vbmade2000** [comment]
@agnivade Sure. Thanks :)

**Comment by vbmade2000** [comment]
@titanous Can you please give more exaplanation ? I checked doc but still not clear what is the issue.

**Comment by agnivade** [comment]
Everything appears fixed except the Dial method. A better issue was filed [here](https://github.com/golang/go/issues/34583) which clearly outlines what shows and what is expected. I am going to close this in favor of that.
