### ISSUE TITLE
website: links to issue tracker point to old tracker

### ISSUE THREAD

**Issue by osocurioso** [golang/go#9616]
The links from http://golang.org/project all go to http://golang.org/issue -> https://code.google.com/p/go/issues/list. The links should instead point to http://golang.org/issues or https://golang.org/issue, both of which redirect to https://github.com/golang/go/issues.

**Comment by ianlancetaylor** [comment]
When I look at http://golang.org/issue I get forwarded to https://github.com/golang/go/issues .  Either this just changed or we are looking at something different.

> curl http://golang.org/issue
<a href="https://github.com/golang/go/issues">Moved Permanently</a>.

**Comment by osocurioso** [comment]
My (or Firefox 33.0's) fault. Apparently the old forwarding rule was cached. Problem disappeared when cache was emptied.

**Comment by osocurioso** [comment]
I suppose this is what happened: http://stackoverflow.com/a/21396547
