### ISSUE TITLE
build: official binary distribution ships a race-enabled go command

### ISSUE THREAD

**Issue by bictorman** [golang/go#9619]
As previously discussed in https://github.com/golang/go/issues/9358#issuecomment-67257858, this still an issue with 1.4.1. I can confirm it for [linux/amd64](https://storage.googleapis.com/golang/go1.4.1.linux-amd64.tar.gz).

```
$ go version
==16523==ERROR: ThreadSanitizer failed to allocate 0x80000 (524288) bytes at address 600000000000 (errno: 12)
FATAL: ThreadSanitizer can not mmap thread trace (0x600000000000/0x000000080000->0xfffffffffffffff4)
```

**Comment by minux** [comment]
OK, I found the culprit.

when -race is enabled, makerelease.go will do the following after building
Go with make.bash:
go install -race std
go install -a std

However, the 2nd command is a nop on release branches.
Also note that some of the tools are installed into pkg/tool/$GOOS_$GOARCH,
we also need
to recompile them.

I've tried several ways, but the only way that works is this:
rm -rf $GOROOT/pkg/$GOOS_$GOARCH
go tool dist install runtime
go install -race std
go install std

**Comment by adg** [comment]
I've re-built the Go 1.4.1 binaries and re-uploaded them. The downloads at https://golang.org/dl/ are the right thing.

**Comment by minux** [comment]
Thanks!

**Comment by bictorman** [comment]
```
$ go version
go version go1.4.1 linux/amd64
```

Perfect, thanks.

**Comment by netroby** [comment]
The Release notes need up to date.

**Comment by adg** [comment]
@netroby I don't think it's necessary.

**Comment by netroby** [comment]
You rebuilt the binary release, and you should tell public what you have done . DO NOT TRY TO FIX SOMETHING SILENTLY.

**Comment by netroby** [comment]
Like the issue #9646 , You let us comfused, why the sha1 not match with your binary . are you hacked by some one?

**Comment by adg** [comment]
@netroby don't shout please. The sha1 on the page always matched the binary that was made available there. You're making a big deal out of something that is not very important. Homebrew have solved their problem. Let's move on.
