### ISSUE TITLE
website: link to release history from the download page

### ISSUE THREAD

**Issue by netroby** [golang/go#9620]
https://golang.org/dl/ this page should have a link to release history page

https://golang.org/doc/devel/release.html

**Comment by netroby** [comment]
Is the too hard to implements? several days gone, not any more updates?

**Comment by bradfitz** [comment]
This is nobody's highest priority.

**Comment by netroby** [comment]
Can i make a pull request? 
Just put one more line in the footer of the dl page. is that ok?
Please guide me, i would like to do this.

**Comment by netroby** [comment]
I am sorry, i can not find the source code of that page.

**Comment by bradfitz** [comment]
Reading the contributing documentation. We don't use Github Pull Requests, but we do take contributions happily. Unfortunately I think only @adg can fix this one. In the golang/tools repo, cmd/godoc/dl.go is a stub.

**Comment by netroby** [comment]
Thanks. I know it. I will keeping my eyes on go project. nice open source project.

**Comment by netroby** [comment]
How about things going on? any update ?

**Comment by parkr** [comment]
Just spent 20 or so minutes looking through the various repositories for this file. It looks like it's not public. @adg, all yours.

**Comment by adg** [comment]
This is done and will be live soon.

**Comment by netroby** [comment]
God, not more wait for two month, you guys awesome.
