### ISSUE TITLE
cmd/pack: tests fails on ppc64le, but only when run under the dashboard builder

### ISSUE THREAD

**Issue by davecheney** [golang/go#9622]
The newly christened linux-pcc64le-canonical builder is failing to pass the `cmd/pack` tests
```
--- FAIL: TestLargeDefs (2.36s)
	pack_test.go:313: [go tool 9g large.go]: exit status 1
		go tool 9g: signal: segmentation fault (core dumped)
FAIL
FAIL	cmd/pack	2.896s
```
However this test does pass if `./all.bash` is invoked directly from the CLI. It only fails when the build is invoked from the dashboard builder.

/cc @aclements

**Comment by minux** [comment]
check ulimits for daemons.

**Comment by davecheney** [comment]
Indeed it was ulimits.
