### ISSUE TITLE
gerrit: no syntax highlighting of go files

### ISSUE THREAD

**Issue by zimmski** [golang/go#9626]
I cannot select "Go" as language in the diff preferences hence there is no syntax highlighting of Go files on https://go-review.googlesource.com/

**Comment by mikioh** [comment]
I think you need to file an issue at https://code.google.com/p/gerrit/ instead.

**Comment by zimmski** [comment]
When I open the create issue mask there i get the following notice:
```
***** !!!! THIS BUG TRACKER IS FOR GERRIT CODE REVIEW !!!!  *****
*****                                                       *****
***** DO NOT SUBMIT BUGS FOR CHROME, ANDROID, CYANOGENMOD,  *****
***** INTERNAL ISSUES WITH YOUR COMPANY'S GERRIT SETUP, ETC.*****
*****                                                       *****
*****   THOSE ISSUES BELONG IN DIFFERENT ISSUE TRACKERS     *****
```

Who is the master Go's gerrit instance?

**Comment by minux** [comment]
You should still file the bug report with gerrit, as they have intentionally
disabled Go syntax highlighting in 3 months agao:
https://gerrit-review.googlesource.com/#/c/60690/

**Comment by zimmski** [comment]
I filled an issue here https://code.google.com/p/gerrit/issues/detail?id=3106 and keep you up to date with this issue.
