### ISSUE TITLE
build: unknown datastore entity for old build failures

### ISSUE THREAD

**Issue by bradfitz** [golang/go#9628]
Andrew,

I was reading https://github.com/golang/go/issues/6372#issuecomment-66085362 and clicked the link:

But http://build.golang.org/log/a09e574dfbb72c98721571ed8e87e634faeb7863 says:

"Error: datastore: no such entity"

Does the /log/ handler need to try the old hg namespace or something if the Git namespace doesn't have it?

**Comment by adg** [comment]
Your analysis is correct.​

**Comment by adg** [comment]
Sent: https://go-review.googlesource.com/3505

If you try http://build.golang.org/log/a09e574dfbb72c98721571ed8e87e634faeb7863 now, it works.
