### ISSUE TITLE
Go 1.4.1: GOXC Cross-Compiler does not work

### ISSUE THREAD

**Issue by SommerEngineering** [golang/go#9630]
With Go 1.4 I am able to build the GOXC cross-compiler (https://github.com/laher/goxc) and its tool chain (``goxc -t``). After installing Go 1.4.1, it no longer possible to build the tool chain.

For Go 1.4.1, within Go's ``pkg`` directory, there are just a few header files (*.h) for most CPUs and GOXC was not able to copy the final Go tools to ``bin`` and therefore, afterwards it is not able to cross-compile with 1.4.1.

Because the GOXC code does not changed within the last time, i create the issue directly here.

**Comment by rjeczalik** [comment]
```
~ $ go version
go version go1.4.1 darwin/amd64
~ $ go get github.com/laher/goxc
~ $ goxc -t
(...)
[goxc:toolchain] 2015/01/18 17:03:37 Task toolchain succeeded
~ $ GOOS=windows GOARCH=386 go build cmd/gofmt
~ $ file gofmt.exe
gofmt.exe: PE32 executable for MS Windows (console) Intel 80386 32-bit
```

Works here.

**Comment by SommerEngineering** [comment]
Sorry, I used Microsoft Windows 8.1, 64 bit. Maybe it is an issue for Go's Windows build?

**Comment by bradfitz** [comment]
This doesn't sound like a Go bug. Also, nothing notable changed here that I believe could've affected goxc.

I suggest you file a bug against https://github.com/laher/goxc and if/when @laher et al determine it's a Go problem, you can reopen this one.
