### ISSUE TITLE
nil != nil when returning a *struct that is assigned to a variable typed as an interface

### ISSUE THREAD

**Issue by Satook** [golang/go#9631]
Hi. I seem to have a nonsensical case of a function returning nil, and when the calling function imediately checks if nil, the value isn't seen as nil.

This happens on my local install of Go 1.4 (amd64/linux) and on the official Go playground.

Small example here:
http://play.golang.org/p/kjusRx4MqQ

I can get rid of the error by setting the variables type to *Structy, but this still seems like a bug.

Cheers,
Andy

**Comment by cespare** [comment]
http://golang.org/doc/faq#nil_error

**Comment by bradfitz** [comment]
Please use golang-nuts@ when you're learning the language. We don't use the issue tracker as a discussion forum.

**Comment by Satook** [comment]
I should have known.
Thanks for the info.
My apologies for the wasted time.
