### ISSUE TITLE
os: File.Truncate reports unhelpful error in Linux.

### ISSUE THREAD

**Issue by Zilog8** [golang/go#9640]
# What version of Go are you using (go version)?
go version go1.4 linux/386
go version go1.4 windows/amd64
# What operating system and processor architecture are you using?
Debian Wheezy, x86
Windows 7, x64
# What did you do?
```go
    filepath := "/play/p2/test2.txt"
	file, err := os.Open(filepath)
	if err != nil {
		fmt.Println("Error 1", err)
	}
	err = file.Truncate(0)
	if err != nil {
		fmt.Println("Error 2", err)
	}
	err = file.Close()
	if err != nil {
		fmt.Println("Error 3", err)
	}
```
# What did you expect to see?
`Error 2 truncate /play/p2/test2.txt: Access is denied`
# What did you see instead?
`Error 2 truncate /play/p2/test2.txt: invalid argument`

Executing Truncate(int) rightfully results in an error because os.Open() yields a read-only file handle.
However, in windows this error is helpful (the "expect to see" above), while in linux it is not helpful (the "see instead" above)

**Comment by bradfitz** [comment]
Assigning to @ianlancetaylor to decide if this is something we should care about. Where does this end? There are surely tons of different error messages between operating systems.

**Comment by Zilog8** [comment]
I agree it's not exactly a critical issue :-). However, precise and accurate error messages are very useful. I just spent a few hours trying to figure out why my code wasn't working (my project involves a filesystem abstraction layer, so it could've been a couple of different things going wrong) on linux, until I decided to try it on a windows machine and in a few moments knew what was wrong and why.

**Comment by minux** [comment]
That's how Linux reports error when you've provided a read only file
descriptor to an operation that requires writing permission. (See man 2
ftruncate)

Actually, if you look at the man page, EBADF / EINVAL is only used for the
"fd is not open for writing error", so the error is not ambiguous.

It's not feasible for the os package to try to provide better error message
than what the underlying syscall provides in every case.

PS: when debugging this kind of issue, I suggest using strace.

**Comment by Zilog8** [comment]
Hmm.. the documentation that I read showed:
    EINVAL
    The argument length is negative or larger than the maximum file size.

However, further down on the page it does say, which I hadn't noticed earlier:
    EBADF or EINVAL
    fd is not open for writing.
    EINVAL
    fd does not reference a regular file.

Well, if Linux itself doesn't provide a more specific error message, I guess there's not much to be done.

**Comment by minux** [comment]
The first part of the man page is for truncate(2), and the 2nd part is
for ftruncate(2).

Close as nothing to do.
