### ISSUE TITLE
spec: append allocates a new underlying array if needed but the size is not the same across platforms

### ISSUE THREAD

**Issue by nbari** [golang/go#9642]
Following the tour [Adding elements to a slice](https://tour.golang.org/moretypes/11) I notice that if I run the code on my system, I got this output:

     a len=0 cap=0 []
     a len=1 cap=1 [0]
     a len=2 cap=2 [0 1]
     a len=5 cap=6 [0 1 2 3 4]

But running the code on the browser the last line prints a diferente capacity **cap=8**

     a len=0 cap=0 []
     a len=1 cap=2 [0]  
     a len=2 cap=2 [0 1]
     a len=5 cap=8 [0 1 2 3 4]

Any idea of why this happens ?

    > go version 
    go version go1.4.1 darwin/amd64

I tested on google chrome version 39.0.2171.99 (64-bit) and Safari Version 8.0.2 (10600.2.5) but in both browser cap is always 8 while in the terminal running and building always gives 5

This is the code in question:

    package main

    import "fmt"

    func main() {
        var a []int
        printSlice("a", a)

        // append works on nil slices.
        a = append(a, 0)
        printSlice("a", a)

        // the slice grows as needed.
        a = append(a, 1)
        printSlice("a", a)

        // we can add more than one element at a time.
        a = append(a, 2, 3, 4)
        printSlice("a", a)
    }

    func printSlice(s string, x []int) {
        fmt.Printf("%s len=%d cap=%d %v\n",
            s, len(x), cap(x), x)
    }

**Comment by ALTree** [comment]
How much a slice grows after an `append( )` depends on the size of the elements of the underling array. [Relevant](https://github.com/golang/go/blob/master/src/runtime/slice.go#L37). 

What's happening is that the playground `ints` have a different size than the `ints` on your system. Change `var a []int` to `var a []int64` in the tour code and you can see the difference: 

https://play.golang.org/p/788ngmEBp0

**Comment by nbari** [comment]
This happens only on the playground or affect other systems as well also any idea of what practice should I follow to create cross-platform code ?

**Comment by ALTree** [comment]
There's no guarantee about  `int` size, and I don't think this is playground-specific. It's more like 32-bit architecture specific. But again, don't make assumptions about `ints` size.

- Never make assumptions about the size of the backing array after a call to `append`, because the spec makes no guarantees about that
- Use `int32` and `int64` when the size of the integer matters

**Comment by mikioh** [comment]
The language specification says nothing about the new capacity size. It's working as intended.
http://golang.org/ref/spec#Appending_and_copying_slices
