### ISSUE TITLE
cmd/gc: compiler does not complain about unhandled error if short if-err-condition/assignment is used

### ISSUE THREAD

**Issue by simonkern** [golang/go#9643]
Hi there,

I am not entirely sure if this is a feature or a bug. Under some conditions, it's possible that the Go compiler does not complain about unhandled errors.

An example can be found here:
http://play.golang.org/p/lTO9l-Ivb_

<pre>
	content, err := ioutil.ReadAll(resp.Body)
	//No warning although err is not handled
	if err := json.Unmarshal(content, foo); err != nil {
		...
	}
</pre>

It seems to be caused by the short version of the if-err-condition/assignment. The question is, whether this is a bug, or a feature. In case it is a bug, how hard is it to fix it?

Cheers,
Simon

**Comment by rjeczalik** [comment]
Compiler has no concept of error handling, it can only complain when a variable is declared but not used. Your err is reassigned that's why no error.

https://golang.org/doc/effective_go.html#redeclaration

**Comment by simonkern** [comment]
You're right, that's what i meant - sorry for my unclear description.

It appears I assumed Go treats errors differently and explicitly checks that they are used after each (re)assignment. I was mistaken, my bad.

**Comment by adg** [comment]
@rjeczalik is right that errors are not special, but is not accurate in his explanation.

In the example you provided, the compiler *would* complain that the first `err` is not used, as the `err` declared inside the if statement *shadows* the other `err`, and is only visible to the if statement and any of its else cases.

This example shows the compiler complaining in such a case: http://play.golang.org/p/vDtBFZDrwd
