### ISSUE TITLE
go/printer: rewrite import `foo` to import "foo"

### ISSUE THREAD

**Issue by rsc** [golang/go#9644]
It might be that go/printer should rewrite

    import `foo`

to

    import "foo"

so that all import statements use double-quoted strings. This is unlikely in practice, but I found myself making this assumption in a textual rewriter (and we've made this assumption in commands that update old code.google.com subrepo imports) and I was surprised that the backquoted form gets through gofmt.

http://play.golang.org/p/XS-iKGjQWe

We should think about this for Go 1.5.

@griesemer

**Comment by griesemer** [comment]
The spec simply wants a string literal there, so both string forms are permitted.

It's fine to have gofmt produce only double-quoted strings.

**Comment by bradfitz** [comment]
Maybe keep raw strings if the import has double quotes in it already. (which will be approximately 0% of programs in the wild)

**Comment by minux** [comment]
According to http://golang.org/ref/spec#Import_declarations,
It's ok to reject " or ` in import paths, so I think we'd just reject
those paths and always use import "foo".

**Comment by griesemer** [comment]
@minux The implementation restriction in http://golang.org/ref/spec#Import_declarations is already implemented (in gc I think, and in go/types for sure) and is applied to the runes of the string, but not the string's quotes. That is, both `math` and "math" are permitted.

It's trivial to do this in gofmt and there's no need to be overly restrictive in the compiler.

**Comment by minux** [comment]
Right, so there is really no reason not to always rewrite import `foo` into
import "foo".

btw, my point about import path restrictions was replying to Brad's comment
about
import path containing double-quotes.
