### ISSUE TITLE
Repack of 1.4.1?

### ISSUE THREAD

**Issue by DomT4** [golang/go#9646]
Can someone upstream here confirm 1.4.1 was intentionally repacked? The SHA1 on the download page changed, and there wasn't much in the way of explanation.

Caused a bit of a nightmare for [Homebrew](https://github.com/Homebrew/homebrew/pull/36054) and possibly other package managers this morning :crying_cat_face:.

**Comment by adg** [comment]
Yes we re-packed the binaries, with a fix for #9619.
My apologies, I should have announced it.
The reason I didn't is because the issue only affected a small minority.
I'll definitely keep packagers in mind next time.

**Comment by DomT4** [comment]
Thanks for the clarification! Just caught us a little off-guard downstream :).

**Comment by netroby** [comment]
We really need to push a minor version bump.

such as 1.4.1.2 or what ever

**Comment by adg** [comment]
@netroby that's not necessary.
