### ISSUE TITLE
html/template `HTML` type example is confusing

### ISSUE THREAD

**Issue by ssilva** [golang/go#9651]
The [`html/template` documentation](http://golang.org/pkg/html/template/#hdr-Typed_Strings) has a snippet of code showing the usage of the `HTML` type. It does not use the "template" package name to scope it:

    tmpl.Execute(out, HTML(`<b>World</b>`))

This code will throw an "undefined: HTML" error.

Instead, it should be like so:

    tmpl.Execute(out, template.HTML(`<b>World</b>`))

**Comment by adg** [comment]
https://go-review.googlesource.com/3073
