### ISSUE TITLE
cmd/6l: -shared generated invalid relocations

### ISSUE THREAD

**Issue by mwhudson** [golang/go#9652]
I guess this falls into the category of things not really guaranteed to work, but:

```shellsession
mwhudson@narsil:shared-lib-stuff$ cat trivialmain.go 
package main

func main () {}
mwhudson@narsil:shared-lib-stuff$ go build -ldflags -shared trivialmain.go
# command-line-arguments
/usr/bin/ld: /var/tmp/go-link-teMwJN/go.o: relocation R_X86_64_TPOFF32 against `runtime.tlsg' can not be used when making a shared object; recompile with -fPIC
/var/tmp/go-link-teMwJN/go.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
/opt/opensource/go/pkg/tool/linux_amd64/6l: running gcc failed: unsuccessful exit status 0x100
```

I think this was broken by 90093f0634d0143c6294e827e5c83fc0818ff8aa.  For ARM the roughly analogous change (b377c9c6a9b720d0897d298652bebd3887ceeb46) was fixed by  9ed5995cfe4c217c1291ced9c4a70334383df226.

**Comment by minux** [comment]
I don't think -shared is supported except for linux/arm....

**Comment by mwhudson** [comment]
Well yes, but I'm working on shared libraries for go and so I need this sort of thing to work :)  I don't expect anyone else to fix it.

**Comment by mwhudson** [comment]
https://github.com/mwhudson/go/compare/master...5391ba7e0d32f0953992be72c05058255a54aae7 sort of fixes this, as well as being terrible in a variety of ways.

**Comment by spetrovic77** [comment]
Is the command in the issue description supposed to work as is?  I'm still getting the same error as in the description on amd64 linux.

**Comment by mwhudson** [comment]
Unfortunately I bungled a rebase and dropped part of the change; see https://go-review.googlesource.com/#/c/6802/

Even then you need to pass -shared to the compiler and assembler as well as the linker.

**Comment by spetrovic77** [comment]
Okay, I'm indeed able to build with -shared passed to all the commands, with your new patch.

Btw., how are you passing -shared to the assembler?  I've had to add -asmflags to the go/build command and pass that along.

**Comment by mwhudson** [comment]
Same! https://go-review.googlesource.com/#/c/4280/

Eventually I'll add the flags from the "Execution Modes" doc by @ianlancetaylor I hope.

**Comment by pjbgtnj** [comment]
I'm trying to make a static library in go (devel +97f854c) that exports a function that gets called by an apache mod (apxs) and get the following error.  I compile my go program with "go build -buildmode c-archive libxxx.go".  When try to comple and link with my apache mod using "apxs -c mod_authnz_xxx.c libxxx.a" I get:

*** Warning: Linking the shared library mod_authnz_xxx.la against the
*** static library libxxx.a is not portable!
/usr/bin/ld: libxxx.a(go.o): relocation R_X86_64_TPOFF32 against `runtime.tlsg' can not be used when making a shared object; recompile with -fPIC
libxxx.a: could not read symbols: Bad value
collect2: error: ld returned 1 exit status
apxs:Error: Command failed with rc=65536
.
make: *** [mod_authnz_xxx.la] Error 1

I added the "-x" option shows that my go code is compiled with -fPIC but this appears to be a problem related to the fact it's a static library (using a c-shared library works).

**Comment by mwhudson** [comment]
1) replying on a tangentially related closed bug is not really useful
2) this seems entirely to be working as designed, you cannot make c-archive
into a shared object, but c-shared you can
