### ISSUE TITLE
html/charset: can't decode charset to UTF-8

### ISSUE THREAD

**Issue by seago** [golang/go#9653]
For this example:
`<!--`
`.......`
`-->`
`<html>`
`.....`
`</html>`

This comments in html length is large than 1024.

**Comment by mattn** [comment]
@seago is the comment part larger than 1024 bytes?

**Comment by seago** [comment]
This comment part larger than 1024 bytes

**Comment by nigeltao** [comment]
This is working as intended. http://godoc.org/golang.org/x/net/html/charset#DetermineEncoding says that DetermineEncoding determines the encoding of an HTML document by examining up to the first 1024 bytes of content and the declared Content-Type.
See http://www.whatwg.org/specs/web-apps/current-work/multipage/parsing.html#determining-the-character-encoding and that spec says "The authoring conformance requirements for character encoding declarations limit them to only appearing in the first 1024 bytes."
