### ISSUE TITLE
bytes: bytes.Count(buf, []byte {}) return number of runes in buf + 1

### ISSUE THREAD

**Issue by kostya-sh** [golang/go#9659]
I believe `bytes.Count(buf, []byte {})` should return `len(buf) + 1`. Currently it returns `utf8.RuneCount(s) + 1`

Demo to show the problem: http://play.golang.org/p/xjQJGlmuOJ

**Comment by bradfitz** [comment]
Either way, the docs don't say. And I agree the name of the package alone would suggest it operates on bytes and not runes. Over to @robpike.

**Comment by minux** [comment]
The reason is that bytes.Count is direct analogous to the strings.Count
function.

However, I do agree that although this behavior is natural for
strings.Count,
it is not apparent for bytes.Count.

Needs doc fix.

**Comment by cespare** [comment]
We had the same discussion on #8143 (about Replace). bytes is intended to be the same as strings, but just take `[]byte` arguments.
