### ISSUE TITLE
fmt: "default format" doesn't honor Stringer element of struct

### ISSUE THREAD

**Issue by BupjaeLee** [golang/go#9663]
I run following program in playground ( http://play.golang.org/p/BLgzIQpj1g ):

```golang
package main

import "fmt"

type testEnum int

const (
	test0 testEnum = iota
	test1
	test2
	test3
)

func (t testEnum) String() string {
	switch t {
	case test0:
		return "test0"
	case test1:
		return "test1"
	case test2:
		return "test2"
	case test3:
		return "test3"
	default:
		return fmt.Sprintf("testEnum(%d)", int(t))
	}
}

func main() {
	fmt.Println(struct{ a testEnum }{a: test1})
}
```

Expect: `{test1}`
Actual: `{1}`

This behavior is inconsistant with other "compound" objects (array, slice, or map).

**Comment by rjeczalik** [comment]
Your struct literal uses unexported member, that's  why it's not inspected for `fmt.Stringer`. Export the member or embed `testEnum` instead and it'll work.
