### ISSUE TITLE
{bytes,strings}: add Size() int method to Reader

### ISSUE THREAD

**Issue by kortschak** [golang/go#9667]
The API for ReadAt does not allow end of reader offset, presumably because of its relationship to pread(2). This makes ReadAt for reading an end-defined file segment require additional support to determine the total size of the data held by the reader. In the case of an *os.File, this can be done via Stat. In the case a bytes or strings Reader there is no equivalent (though see workaround at [1]).

I would like to see a Size method on these two types. In both cases this is merely requires returning the len of the stored string or []byte.

If this is acceptable I am happy to send a CL.

[1]https://groups.google.com/d/topic/golang-nuts/nskyzVABsX8/discussion

**Comment by bradfitz** [comment]
We sent this out at the same time.

I mailed https://go-review.googlesource.com/3199

Note it should return `int64` and not `int.

**Comment by kortschak** [comment]
True. Thanks.

**Comment by minux** [comment]
Should we also introduce io.Sizer and probably io.SizedReader(At)?
So that we have a standard on this method.

**Comment by kortschak** [comment]
I would like that.

**Comment by bradfitz** [comment]
Not yet. Those are trivial to add in your own code. Until we have something useful which takes one of those, I'd prefer not to add the interfaces.
