### ISSUE TITLE
x/playground: `type *rsa.PrivateKey has no field or method Public`

### ISSUE THREAD

**Issue by adams-sarah** [golang/go#9678]
1. What version of Go are you using (go version)?
    - Playground Go version: `fmt.Println(runtime.Version())` => go1.3.2
    - Docs Go version (found in footer): go1.4.1

2. What operating system and processor architecture are you using?
    - Go playground

3. What did you do?

   ```go
   private, err := rsa.GenerateKey(rand.Reader, 256)
   if err != nil {
      panic(err.Error())
   }
   public := private.Public() // this line
   ```

4. What did you expect to see?
    - **What**: I expected the code to compile.
    - **Why**: Go crypto/rsa docs specify a method `Public` for `*rsa.PrivateKey` 
    - **Reference**: http://golang.org/pkg/crypto/rsa/#PrivateKey.Public

5. What did you see instead?
It does not compile. Exits with: `private.Public undefined (type *rsa.PrivateKey has no field or method Public)`

**Comment by adams-sarah** [comment]
playground: http://play.golang.org/p/sxxL-6F9ed

**Comment by cespare** [comment]
As you noted, the playground is running Go 1.3.2 while the docs are for 1.4.1.

In Go 1.4, `rsa.PrivateKey` had the `Public` method added so that it could satisfy the `crypto.Signer` interface. (See [the release notes](https://golang.org/doc/go1.4#minor_library_changes).) But you can just access `key.PublicKey` directly prior to 1.4 if you need that.

**Comment by adams-sarah** [comment]
Awesome! Thanks for the quick response.

Just so I know, how soon after a go release is the playground go usually updated?

**Comment by adg** [comment]
We're in the process of replacing the old playground infrastructure with
new stuff, which is almost ready. Once it is finally done we'll update the
playground.

**Comment by dericofilho** [comment]
This can be closed. it works now. 

Check it at http://play.golang.org/p/fMfYsY_JJw
