### ISSUE TITLE
invalid operation: str1[0] (type *[]rune does not support indexing

### ISSUE THREAD

**Issue by sprlnxhua** [golang/go#9680]
my Code:

package main

import(
	"fmt"
)
func main(){
	str1 := []rune("google")
	fmt.Print(temp(&str1))
	
}
func temp(str1 *[]rune) (sum int){
	fmt.Print(str1[0]);
	
	return 
}

error:  temp.go:12: invalid operation: str1[0] (type *[]rune does not support indexing

This is what problem?

**Comment by minux** [comment]
Use (*str1)[0].

Please use the golang-nuts mailing list to ask questions like this. The issue tracker is only for reporting bugs.

**Comment by adg** [comment]
The [golang-nuts mailing list](https://groups.google.com/group/golang-nuts) is the place to ask such questions.
