### ISSUE TITLE
Complex number types should support " >  < <= >=" operators (greater than, less than)

### ISSUE THREAD

**Issue by Splizard** [golang/go#9681]
Implementation in Go.

Currently one has to do this to compare complex numbers:
```
real(a)*real(a) + imag(a)*imag(a) > real(b)*real(b) + imag(b)*imag(b)
```
This is comparing what is called the magnitude of a complex number and is essentially comparing the distance from zero because in a complex number plane, 0 is the smallest magnitude.
To draw the similarity between normal greater than and complex, instead of comparing numbers by cutting a line in the number line and checking either direction for smaller or greater than eg. 1234 < 5678.
It doesn't make sense to check greater than and less than in a 1 dimensional sense as there is no 1 dimensional order to complex numbers.
With complex numbers you cut a circle on the complex plane and check either direction of the circle (inside and outside) if a complex number is greater than or less than the circle.
![complex](https://cloud.githubusercontent.com/assets/2015791/5889565/f12e8ca4-a492-11e4-8de7-c9379487b5a9.jpg)
In the above diagram the following would evaluate to true
```
B > A && A > C && B > C 
```
If another point (P) was on the unit circle this would evaluate true
```
P >= A && P <= A
! P > A && ! P < A
```
This would be nice to be builtin to the language as it would bring a better consistency with the number types supporting the " >  < <= >=" operators.

**Comment by minux** [comment]
http://en.wikipedia.org/wiki/Complex_number#Ordering

We shouldn't enforce any particular linear ordering of complex numbers.
Working as intended.
