### ISSUE TITLE
regexp: CompilePOSIX does not appear to match leftmost-longest

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#9684]
Run the following program:

	package main
	
	import (
		"regexp"
		"fmt"
	)
	
	func main() {
		pat := regexp.MustCompilePOSIX(`^([^:=]*)(:|:=)(.*)$`)
		m := pat.FindStringSubmatch("x:=y")
		fmt.Printf("%q\n", m)
	}

It prints:

    ["x:=y" "x" ":" "=y"]

I would expect it to print

    ["x:=y" "x" ":=" "y"]

choosing the longer of the two alternatives, as for example
acme's regexp engine does.

**Comment by cznic** [comment]
FWIW, the "normalized", though equal form
```
package main

import (
	"fmt"
	"regexp"
)

func main() {
	pat := regexp.MustCompilePOSIX(`^([^:=]*)(:?=)(.*)$`)
	m := pat.FindStringSubmatch("x:=y")
	fmt.Printf("%q\n", m)
}
```
prints

`["x:=y" "x" ":=" "y"]`

(http://play.golang.org/p/2ogIBqdnpd)

**Comment by mattn** [comment]
AFAIK, match-group should work with specified order. not longest. At least, perl seems to work specified order. `^([^:=]*)(:|:=)(.*)$`

**Comment by rogpeppe** [comment]
My understanding of POSIX leftmost-longest is that it should pick the longest possible alternative. Switching the alternatives in the example from this issue does make it pick a different alternative, which doesn't seem right.

**Comment by mattn** [comment]
regexp engine of vim works as ordered.

**Comment by rsc** [comment]
Yes, the leftmost-longest only applies to the overall match. Within the match, it is the "first match" semantics of Perl. When POSIX mandated the submatch leftmost-longest rule they had no idea how to implement it without exponential time. It's not trivial and not worth it.

(It's possible but no one does except maybe Haskell.)
