### ISSUE TITLE
text/template: Funcs accepts names with '-' but won't allow calling them

### ISSUE THREAD

**Issue by anacrolix** [golang/go#9685]
I've given a valid function but with a name containing '-'. Attempting to call it from a template:

    panic: template: index.html:64: unexpected bad character U+002D '-' in command

**Comment by minux** [comment]
I agree that we should reject uncallable Funcs.

**Comment by robpike** [comment]
I am confused now. How did you get a panic? The parser correctly returns an error for a template that attempts to invoke such a function.

I'm starting to wonder if the original CL (tweaked) is all that's required.
