### ISSUE TITLE
syscall: Pdeathsig ignored when using setuid/setgid (Linux)

### ISSUE THREAD

**Issue by TheDude05** [golang/go#9686]
When attempting to use the `Pdeathsig` functionality on Linux, along with using setuid/setgid, the death signal appears to be ignored. However when setuid/setgid is not used, the death signal works as expected. This behavior was observed on Go version 1.4.1 with the following test code:

```
package main

import (
	"log"
	"os"
	"os/exec"
	"strconv"
	"syscall"
	"time"
)

func main() {
	attrs := syscall.SysProcAttr{
		Pdeathsig: syscall.SIGTERM,
	}

	if len(os.Args) > 1 {
		id, _ := strconv.ParseUint(os.Args[1], 0, 32)
		attrs.Credential = &syscall.Credential{Uid: uint32(id), Gid: uint32(id)}
	}

	cmd := exec.Command("/bin/sleep", "300")
	cmd.SysProcAttr = &attrs

	err := cmd.Start()
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("Started child %d\n", cmd.Process.Pid)

	// Wait a bit and then die
	time.Sleep(2 * time.Second)
	log.Printf("Dying... Check child status with `ps -p %d -f`\n", cmd.Process.Pid)
}
```

#### Steps to reproduce

Without setting a uid/gid to switch to, the death signal works as expected
```
[andrew@localhost ~]$ sudo ./deathsig_example 
2015/01/25 14:56:15 Started child 2022
2015/01/25 14:56:17 Dying... Check child status with `ps -p 2022 -f`
[andrew@localhost ~]$ ps -p 2022 -f
UID        PID  PPID  C STIME TTY          TIME CMD
```

When switching to another uid/gid (user and group "nobody" in this case) we see that the child is not sent a sigterm.
```
[andrew@localhost ~]$ sudo ./deathsig_example 99
2015/01/25 14:56:26 Started child 2029
2015/01/25 14:56:28 Dying... Check child status with `ps -p 2029 -f`
[andrew@localhost ~]$ ps -p 2029 -f
UID        PID  PPID  C STIME TTY          TIME CMD
nobody    2029     1  0 14:56 pts/2    00:00:00 /bin/sleep 300
```

I reproduced this bug on Fedora 20 (kernel version: 3.16.4-200.fc20.x86_64) as well as on Centos 6.6 (kernel version: 2.6.32-431.11.2.el6.x86_64).

#### The fix

From what I can tell by looking at the kernel source, it appears Linux resets the death signal attribute on a task when the effective uid/gid changes.

https://github.com/torvalds/linux/blob/d82012695ef29e4e1c8153ccf43098ec8e50369e/kernel/sys.c#L561
https://github.com/torvalds/linux/blob/9a3c4145af32125c5ee39c0272662b47307a8323/kernel/cred.c#L441

In `src/syscall/exec_linux.go` we set the death signal *before* we make any setuid/setgid system calls which means it will always be cleared in those cases. Moving the `Pdeathsig` code farther down in the function seems to fix the problem.

I'll be submitting a CL shortly.

**Comment by bradfitz** [comment]
Pending CL is https://go-review.googlesource.com/#/c/3290/1
