### ISSUE TITLE
mobile/motion: add orientation, gyroscope and accelerometer APIs

### ISSUE THREAD

**Issue by rakyll** [golang/go#9687]
Given the fact device motion and rotation are two of the main user inputs in games, we should consider adding related APIs.

http://developer.android.com/guide/topics/sensors/sensors_overview.html
https://developer.apple.com/library/prerelease/ios/documentation/CoreMotion/Reference/CoreMotion_Reference/index.html

**Comment by crawshaw** [comment]
Duplicate of #9330. (I actually meant to be working on it this weekend, but have been distracted by build system brokenness.)
