### ISSUE TITLE
suggest add default ReadTimeout and WriteTimeout to net/http/#Server

### ISSUE THREAD

**Issue by haosdent** [golang/go#9688]
I think default ReadTimeout and WriteTimeout are necessary. Because when server without timeout, a lot of idle connection form client are use up the memory and sockets of memory. It is easy to use by cracker.

**Comment by minux** [comment]
Are you suggesting that when Server.{Read,Write}Timeout is zero,
we apply some default settings?

What if the user really don't want Read/WriteTimeout? I think this will
be an API change and against the Go 1 API stability guarantee.
