### ISSUE TITLE
time: documentation for layout strings is lacking

### ISSUE THREAD

**Issue by TomOnTime** [golang/go#9689]
As documented in this hacker news thread:
https://news.ycombinator.com/item?id=8944578

"The Go date format is one my huge annoyances about the language (not generics, interface{} magic, or the lack of immutable types). My biggest issue is that despite the fact the designers call Strftime bad because no one remembers the letters, and has to have documentation handy - the Go docs don't even document the magic numbers you have to use.
Why 2006? How do I represent a day? When do I use _2 vs 2? Its very poorly documented and thankfully all I use is RFC3339 and Unix timestamps."

**Comment by adg** [comment]
I just sent

https://go-review.googlesource.com/3302

**Comment by robpike** [comment]
Fixed. At tip there are now very nice examples and the docs refer to them.

http://tip.golang.org/pkg/time/#Time.Format now refers to  http://tip.golang.org/pkg/time/#example_Time_Format which is all new
