### ISSUE TITLE
cmd/go: `go test -cover` hangs with import cycles

### ISSUE THREAD

**Issue by aybabtme** [golang/go#9690]
Hello Gophers!

1. `go version go1.4.1 darwin/amd64`
2. OS X Yosemite, amd64.
3. Ran `go test -cover .` in a package with import cycle in the tests.
4. It should fail to compile the tests.
5. It didn't fail and hang instead.

## to reproduce

Fetch repository `github.com/aybabtme/hangcover` and run `./reproduce.sh`.

```bash
$ ./reproduce.sh
GOROOT=$(go env GOROOT)
go env GOROOT
GIT_DIR="$GOROOT/.git" git rev-parse --verify HEAD
886b02d705ffb1be8b4974ac4c355d480a24e3ec

go version
go version go1.4.1 darwin/amd64
go test -cover github.com/aybabtme/hangcover
^C⏎
```

## description

If a test file has the same package name as the package it tests, 
and if that test file imports the package it tests:

```go
// hangcover.go
package hangcover
```

```go
// hangcover_test.go
package hangcover

import "github.com/aybabtme/hangcover"
```

Then running `go test github.com/aybabtme/hangcover` will fail with an import cycle error:

```bash
# github.com/aybabtme/hangcover
./hang_test.go:4: import "github.com/aybabtme/hangcover" while compiling that package (import cycle)
FAIL	github.com/aybabtme/hangcover [build failed]
```

But running `go test -cover github.com/aybabtme/hangcover` will hang:

```bash
go test -cover github.com/aybabtme/hangcover
^C⏎
```

**Comment by ianlancetaylor** [comment]
Problems with invalid code need not be fixed in minor releases.
