### ISSUE TITLE
[question] net/http: why drop the leading dot of cookie.Domain?

### ISSUE THREAD

**Issue by coderhaoxin** [golang/go#9692]
https://github.com/golang/go/blob/master/src/net/http/cookie.go#L144-L151

```go
			// A c.Domain containing illegal characters is not
			// sanitized but simply dropped which turns the cookie
			// into a host-only cookie. A leading dot is okay
			// but won't be sent.
			d := c.Domain
			if d[0] == '.' {
				d = d[1:]
			}
			fmt.Fprintf(&b, "; Domain=%s", d)
```

**Comment by adg** [comment]
This isn't the place for questions. That place is https://groups.google.com/group/golang-nuts

**Comment by minux** [comment]
The issue tracker is not for asking questions. Please ask on golang-nuts mailing list
instead. Thanks.
