### ISSUE TITLE
Add golang yasm support

### ISSUE THREAD

**Issue by harshavardhana** [golang/go#9699]
http://yasm.tortall.net/
~~~
Yasm is a complete rewrite of the NASM assembler under the “new” BSD License (some portions are
under other licenses, see COPYING for details).

Yasm currently supports the x86 and AMD64 instruction sets, accepts NASM and GAS assembler
syntaxes, outputs binary, ELF32, ELF64, 32 and 64-bit Mach-O, RDOFF2, COFF, Win32, and Win64
object formats, and generates source debugging information in STABS, DWARF 2, and CodeView 8 formats.

Yasm can be easily integrated into Visual Studio 2005/2008 and 2010 for assembly of NASM or GAS
syntax code into Win32 or Win64 object files.
~~~

This support is necessary for yasm based assembly files to be integrated along with regular cgo files. 

Currently a working code is available https://github.com/minio-io/go/tree/yasm-support , we will be sending a new patch soon to codereview

Our use case comes from integrating Intel Storage Acceleration library - https://github.com/Minio-io/erasure/tree/golang_restructure

**Comment by minux** [comment]
The problem is that there are multiple popular assembler available (fasm,
JWasm, etc.), why only support yasm, but not the others? And yasm doesn't
support all Go's supported architectures.

I think a better way is to use //go:generate to compile the yasm source to
.syso file and include them into the repository.

**Comment by harshavardhana** [comment]
> I think a better way is to use //go:generate to compile the yasm source to
> .syso file and include them into the repository.

This sounds like the right idea, you are indeed correct why only use yasm - perhaps that is lack of our understanding of Go build system as we hacked our way through go builder
