### ISSUE TITLE
x/tour: moretypes: confusion between XOR and math.Pow

### ISSUE THREAD

**Issue by fhs** [golang/go#9700]
At the [moretypes/14](https://tour.golang.org/moretypes/14) page, `x^y` is used to mean exponentiation but the math package uses `x**y`. Also, the [XOR version](http://play.golang.org/p/BTsw_ZSeRF) is prettier than the [math.Pow version](http://play.golang.org/p/3bXV6D1rrR).

**Comment by ALTree** [comment]
Dup of #11310

**Comment by kytrinyx** [comment]
I believe this is fixed in https://go-review.googlesource.com/#/c/11134/3/content/moretypes.article by removing the reference `math.Pow()` (so the reader is no longer directed to documentation that uses the `x**y` syntax).
