### ISSUE TITLE
unix: GOOS=freebsd Getxattr etc fails to build, missing EXTATTR_NAMESPACE_USER etc

### ISSUE THREAD

**Issue by tv42** [golang/go#9705]
I don't see how ac22431096cc4c3bb3587a28de4edcd6075746b0 could ever have worked. Is the commit perhaps missing a file?

```console
[0 tv@brute ~/go/src/golang.org/x/sys/unix]$ go get -u
[0 tv@brute ~/go/src/golang.org/x/sys/unix]$ GOOS=freebsd go build -v
golang.org/x/sys/unix
# golang.org/x/sys/unix
./syscall_freebsd.go:159: undefined: EXTATTR_NAMESPACE_USER
./syscall_freebsd.go:161: undefined: EXTATTR_NAMESPACE_SYSTEM
./syscall_freebsd.go:291: undefined: EXTATTR_NAMESPACE_USER
./syscall_freebsd.go:291: undefined: EXTATTR_NAMESPACE_SYSTEM
./syscall_freebsd.go:301: undefined: EXTATTR_NAMESPACE_USER
./syscall_freebsd.go:325: undefined: EXTATTR_NAMESPACE_USER
./syscall_freebsd.go:325: undefined: EXTATTR_NAMESPACE_SYSTEM
./syscall_freebsd.go:327: undefined: EXTATTR_NAMESPACE_USER
./syscall_freebsd.go:351: undefined: EXTATTR_NAMESPACE_USER
./syscall_freebsd.go:351: undefined: EXTATTR_NAMESPACE_SYSTEM
./syscall_freebsd.go:351: too many errors
[2 tv@brute ~/go/src/golang.org/x/sys/unix]$ git rev-parse HEAD
853bdd547ae1da82e976a3cb09e1f5dc6b70ef27
[0 tv@brute ~/go/src/golang.org/x/sys/unix]$ 
```

**Comment by minux** [comment]
You're right.

@worr, it seems you modified mkerrors.sh but forgot to include updated
zerrors files.

**Comment by stevenh** [comment]
There's quite a few generated files out of date, when I built on FreeBSD 10.1-RELEASE amd64

**Comment by worr** [comment]
I'll get a fix tonight when I get home from work

**Comment by worr** [comment]
I generated a file for amd64, since I have that on hand. I can't seem to generate working files for arm or 386 though.

**Comment by minux** [comment]
@davecheney runs the freebsd-arm builder, so he might be able to help you
with
generating the zerrors file for freebsd/arm.

**Comment by davecheney** [comment]
I won't be able to do this til the end of February. Given we don't have a FreeBSD/arm builder running at the moment, this will probably remain silently broken til then.

**Comment by worr** [comment]
I've backed out the breaking changes locally, and `mkerrors.sh` is broken on FreeBSD-10.1 386 at least. I'm trying to figure out exactly what's broken before putting in a CL.

**Comment by minux** [comment]
In the x/sys repo, it's probably better in the long run to switch to a Go
based generation infrastructure so that we can have tests that make sure
the generation program works on the builder (and ideally also check that
the z*.go files match the result generated on the builder.) Perhaps we can
reuse cmd/cgo for this.

But before we can do that, we need to figure out how to handle changes in
different versions of the same OS.

**Comment by worr** [comment]
After far too long, I have a CL for the sys changes: https://go-review.googlesource.com/#/c/6370/
