### ISSUE TITLE
encoding/json: Can improve json.Decoder while io.reader is bytes.Bufffer.

### ISSUE THREAD

**Issue by runner-mei** [golang/go#9706]
Can improve json.Decoder while reader is bytes.Bufffer， use it like this:
````go
    buffer := bytes.NewBuffer(make([]byte, 0, 1024))
    for {
      ....   // read bytes to buffer from network
      dec := json.NewDecoder(buffer)   // buffer is *bytes.Buffer
      dec.Decode(&m)     // it should copy all bytes to internal buf.
      ....  // do some things.
      buffer.Reset()
   }
````
json.Decoder.Decode() should copy all bytes to internal buf  in the readValue(), it is what I want to avoid。I want to reuse buffer and zero copy, Reducing the number of GC.    #7709

**Comment by adg** [comment]
What's the context? I'm all for reducing allocations, but I want to make sure that this is worthwhile before we investigate adding special cases for this.

**Comment by bradfitz** [comment]
Reducing copies and making json.Decoder re-usable are separate issues. I don't think the copies (which don't contribute to GCs, only CPU) will matter as much as a Reset(io.Reader) method on json.Decoder, which is probably worth doing.

**Comment by runner-mei** [comment]
I have a bad example, my idea is simply to reduce the memory copy and memory  allocation . When the data is too large (size is 1m), will has too many copies and memory allocation in the readValue(), and I hope that we can avoid it.

````go
      buffer := bytes.NewBuffer(make([]byte, 0, 1024))
      ....   // read bytes to buffer from network
      dec := json.NewDecoder(buffer)   // buffer is *bytes.Buffer
      dec.Decode(&m)     // it should copy all bytes to internal buf.
      ....  // do some things.
````

**Comment by runner-mei** [comment]
I hope that we can avoid it while reader is bytes.Buffer or bytes.Reader or strings.Reader.

**Comment by adg** [comment]
I understand the desire to improve things, but we're not going to add special cases if they don't address a real issue.
