### ISSUE TITLE
syscall: routing message parser seems to be wrong on freebsd-386-gce101

### ISSUE THREAD

**Issue by mikioh** [golang/go#9707]
See http://build.golang.org/log/c66156b3f8d5fdd6f2480c180ed627a58007c9f0

	interface_test.go:76: "lo0": flags "up|loopback|multicast", ifindex 2, mtu 16384
	interface_test.go:77: hardware address ""
	interface_test.go:161: unexpected value: &net.IPNet{IP:net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, Mask:net.IPMask{0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff}}
	interface_test.go:178: interface address "0:0:fe80::/64"
	interface_test.go:178: interface address "127.0.0.1/8"

The output on loopback interface must be

	interface_test.go:178: interface address "::1/128"
	interface_test.go:178: interface address "fe80::1/64"
	interface_test.go:178: interface address "127.0.0.1/8"

**Comment by mikioh** [comment]
Hm,  #8203, looks like I was wrong, it hurts the net package.

**Comment by bradfitz** [comment]
@rakyll, this is a perfect example of when we'd want to be able to say "just run `gomote create freebsd-amd64-gce101` and have your own dev environment of this builder type".

@mikioh, we're almost there, but the `cmd/gomote` tool doesn't yet auto-create images in your GCE project from the public images URLs (which aren't associated with the builder types).

Mikio, are you able to debug this on your own? Or do you want instructions on how to use gomote for now?

**Comment by mikioh** [comment]
@bradfitz I think I can manage this issue; what I need is a time for reading kernel code.

Perhaps I had to ask again at that time even though Mr. Pike rejected a CL for #8203. I think I stashed that patch but it disappears now.

**Comment by bradfitz** [comment]
Oh, I notice this fails only on `freebsd-386-gce101` and not amd64.

Note that the FreeBSD-386 builder is a 64-bit kernel (same VM as the amd64 builder) but just runs with GOARCH=386.

**Comment by mikioh** [comment]
> Note that the FreeBSD-386 builder is a 64-bit kernel (same VM as the amd64 builder) but just runs with GOARCH=386.

Cool, I've never imagined a use case like that. Certainly that's one of the root causes.

**Comment by bradfitz** [comment]
@mikioh, can we get this fixed? This builder has been broken for too long.

**Comment by mikioh** [comment]
@bradfitz, sure, the root causes are a) broken platform recognition stuff, and b) lazy parsers that try to ignore uninteresting messages so hard. but not write a patch yet. if you hurry, will work on this before fixing other issues.

**Comment by bradfitz** [comment]
Yes, I'd always prioritize getting the builders "ok" before new features. A red builder hides other problems. Thanks.

**Comment by mikioh** [comment]
Here you go: https://go-review.googlesource.com/4330
