### ISSUE TITLE
net/http: ServeContent to return bytes copied end error

### ISSUE THREAD

**Issue by funny-falcon** [golang/go#9709]
It will be good if http.ServeContent will return number of bytes copied and error.
It should not break API compatibility, cause it doesn't return anything at the moment.

**Comment by adg** [comment]
But it would break compatibility for anyone that's using `http.ServeContent` as a function value.

To do what you want, you could wrap the `ResponseWriter` with one that records errors etc. I know this isn't ideal.

**Comment by funny-falcon** [comment]
No, I can't wrap cause I still could not access bytes copied (and it is primary reason for issue).

At the moment, I see that it looks like I ought to copy whole ServeContent implementation to achieve goal.

**Comment by funny-falcon** [comment]
may be there is possibility to make `checkETag` and `checkLastModified` public?
or make `serveContent` to be a public function with different name, like `DoServeContent(...)(int64, error)`?

**Comment by adg** [comment]
You can wrap both the `io.ReadSeeker` and the `http.ResponseWriter` with something that counts the bytes copied:

```
package main

import (
        "io"
        "log"
        "net/http"
        "strings"
        "time"
)

func main() {
        http.HandleFunc("/", handler)
        log.Fatal(http.ListenAndServe("localhost:8080", nil))
}

func handler(rw http.ResponseWriter, r *http.Request) {
        rs := strings.NewReader("content")
        crs := &countingReadSeeker{ReadSeeker: rs}
        crw := &countingResponseWriter{ResponseWriter: rw}
        http.ServeContent(crw, r, "file.txt", time.Now(), crs)
        log.Printf("read %v bytes, wrote %v bytes", crs.count, crw.count)
}

type countingReadSeeker struct {
        io.ReadSeeker
        count int64
}

func (r *countingReadSeeker) Read(b []byte) (n int, err error) {
        n, err = r.ReadSeeker.Read(b)
        r.count += int64(n)
        return
}

type countingResponseWriter struct {
        http.ResponseWriter
        count int64
}
```

**Comment by bradfitz** [comment]
Yes, we can't change the signature of things due to the Go 1 API compatibility promise.

**Comment by funny-falcon** [comment]
But you can expose new function: just make private function 'serveContent' to be a public one with non colliding name, and make it return bytes and error.
For example, it could be named as "ServeContentImpl",  "ServeContentInternal" or other.

**Comment by adg** [comment]
ServeContent hasn't changed in years. If you want to access its internals, just make a copy.

**Comment by funny-falcon** [comment]
And now I do not offer to change `ServeContent`, i offer to make `serveContent` public with changed name and return type.

**Comment by bradfitz** [comment]
Your minor convenience isn't worth the cost of all other Go programmer's increased cognitive load required by having more stuff in the `net/http` package to read and understand the difference between.

Sorry, we're not adding this. There are ways to do this already. Unless a large number/percentage of people needed this, it's not worth the cost of adding it.
