### ISSUE TITLE
database/sql: NullString, NullInt64, NullFloat64, NullBool is not exported as real value

### ISSUE THREAD

**Issue by mattn** [golang/go#9719]
```go
package main

import (
	"database/sql"
	"encoding/json"
	"fmt"
	"os"
)

type Foo struct {
	Id    int64          `json:"id"`
	Title sql.NullString `json:"title"`
}

func main() {
	db, _ := sql.Open("blah-driver", "blah-dsn")
	rows, _ := db.Query("select id, title from foo")
	for rows.Next() {
		var foo Foo
		rows.Scan(&foo.Id, &foo.Title)
		json.NewEncoder(os.Stdout).Encode(foo)
		fmt.Println()
	}
}
```

Expected:

```
{"id": 1, "title": "Go Book"}
{"id": 2, "title": null}
...
```

**Comment by mattn** [comment]
If getting agreements, I'll send https://gist.github.com/mattn/a42f0d5c0e135d4d03ee

**Comment by johto** [comment]
Judging from the gist you want the sql.Null* types to implement json.Marshaler?  Is that it?

FWIW that idea has been [rejected in the past](https://groups.google.com/forum/#!topic/golang-dev/SiRHeFQgoLE).

**Comment by mattn** [comment]
Hmm, it seems redundancy to me.

```go
type MyNullString sql.NullString

func (ns NullString) MarshalJSON() ([]byte, error) {
	if ns.Valid {
		return json.Marshal(ns.String)
	}
	return jsonNull, nil
}

type Foo struct {
    Id    int64         `json:"id"`
    Title MyNullString `json:"title"`
}
```

**Comment by mattn** [comment]
I don't have strong objection but when user want to use Null* on their codes, it will be more redundancy .

```go
type MyNullString sql.NullString
type MyNullInt64 sql.NullInt64

func (ns NullString) MarshalJSON() ([]byte, error) {
    if ns.Valid {
        return json.Marshal(ns.String)
    }
    return jsonNull, nil
}

func (n NullInt64) MarshalJSON() ([]byte, error) {
	if n.Valid {
		return json.Marshal(n.Int64)
	}
	return jsonNull, nil
}

type Foo struct {
    Id    int64         `json:"id"`
    Title MyNullString `json:"title"`
    Count MyNullInt64 `json:"count"`
}
```
If applies this patch, it will be simply like below.

```go
type Foo struct {
    Id    int64         `json:"id"`
    Title NullString `json:"title"`
    Count NullInt64 `json:"count"`
}
```

**Comment by bradfitz** [comment]
Let's leave it alone. I think it would be confusing to have json references in the sql package, like Russ said before.

This isn't preventing you from doing anything. You just want to move your complexity into the standard library so it becomes everybody's complexity. If everybody wanted this, sure. But I'm not convinced this need is universal. Those types are just examples anyway.

**Comment by mattn** [comment]
Ah, just now, I got nice idea for new product. Probably, I can provide few types which can be put in user's struct  as field. And that can be converted as JSON but can be used for sql.Scan also. :)

**Comment by mattn** [comment]
BTW, Why database/sql doesn't provide NullTime?
