### ISSUE TITLE
runtime/race: update race runtime before Go 1.5 release

### ISSUE THREAD

**Issue by minux** [golang/go#9720]
@dvyukov might also want to discuss how best to align the update
of the race runtime with our release cycle.

Personally I don't mind updating the race runtime more often, once
some user visible bugs are fixed. Now that we have gomote, building
the race runtime on all supported platforms shouldn't be a problem.
(Ask bradfitz about gomote. I think at least Linux and FreeBSD are
covered.)

**Comment by dvyukov** [comment]
#8653 is related to more frequent updates
