### ISSUE TITLE
objwriter: no error?

### ISSUE THREAD

**Issue by bradfitz** [golang/go#9722]
Seen on Windows once:

http://build.golang.org/log/1d0a8cc93ec09ff54fe30599647b593568f8a614
```
encoding/gob
# encoding/csv
c:\gobuilder\windows-amd64-29428e322d6f\go\pkg\tool\windows_amd64\6g.exe: running c:\gobuilder\windows-amd64-29428e322d6f\go/pkg/tool/windows_amd64/objwriter: No error
image/gif
net/mail
image/png
```

What is the no error error?

/cc @alexbrainman

**Comment by alexbrainman** [comment]
Strange one. It only fails sometimes. And I cannot reproduce it here.

It fails in liblink/writeobjgo2. I will add more error output https://go-review.googlesource.com/3568 - it might give us some clues.

Alex

**Comment by alexbrainman** [comment]
This cannot be happening now that C code is gone.

Alex
