### ISSUE TITLE
doc: impossible to figure out how to checkout sources

### ISSUE THREAD

**Issue by dvyukov** [golang/go#9724]
http://golang.org/project page has "Check out the Go source code" link which leads to incomprehensible page  with no obvious way to checkout code (I still did not found it there).

http://golang.org/doc/contribute.html assumes that you already has code and starts with discussing testing.

"Check out the Go source code" must contain instructions on how to actually checkout code.

"Contribution Guidelines" needs to include commands to checkout code as well.

@adg

**Comment by adg** [comment]
On 29 January 2015 at 22:37, Dmitry Vyukov <notifications@github.com> wrote:

> http://golang.org/project page has "Check out the Go source code" link
> which leads to incomprehensible page with no obvious way to checkout code
> (I still did not found it there).


The third line on that page says

> git clone https://go.googlesource.com/go

**Comment by adg** [comment]
On 29 January 2015 at 22:37, Dmitry Vyukov <notifications@github.com> wrote:

> http://golang.org/doc/contribute.html assumes that you already has code
> and starts with discussing testing.
>
>
The first link on that page is to the source installation instructions.

**Comment by dvyukov** [comment]
I seriously was not able to figure out how to do it. I am not going to read it all, I am just looking for a bold "git something" command line near top of a page.

**Comment by adg** [comment]
I'm not suggesting you have to read all of each page, but the very first things on each of those links explains how to check out the code.

You say

> http://golang.org/doc/contribute.html assumes that you already has code and starts with discussing testing.

But the very first sentence on that page is:

> This document explains how to contribute changes to the Go project. It assumes you have followed the [installation instructions](https://golang.org/doc/install/source)

I don't want to repeat the checkout instructions everywhere, because if/when they change we need to update them everywhere.

**Comment by dvyukov** [comment]
ok, the issue is resolved at least for me :)
