### ISSUE TITLE
runtime: cputicks has low precision on arm

### ISSUE THREAD

**Issue by dvyukov** [golang/go#9725]
runtime/os_linux_arm.go:

func cputicks() int64 {
	// Currently cputicks() is used in blocking profiler and to seed fastrand1().
	// nanotime() is a poor approximation of CPU ticks that is enough for the profiler.
	// randomNumber provides better seeding of fastrand1.
	return nanotime() + int64(randomNumber)
}

This causes runtime/pprof trace tests failures:

--- FAIL: TestTrace (0.00s)
	trace_test.go:56: failed to parse trace: g 3 is not runnable before traceEvGoWaiting (offset 48, time 30528)
--- FAIL: TestTraceStress (1.32s)
	trace_test.go:151: failed to parse trace: g 3 is not runnable before traceEvGoWaiting (offset 75185, time 30528)
--- FAIL: TestTraceSymbolize (0.04s)
	trace_test.go:199: failed to parse trace: g 3 is not runnable before traceEvGoWaiting (offset 48, time 30481)

http://build.golang.org/log/413c7741597ae53221e88070d1b5a70c3a365b03
http://build.golang.org/log/46208c3a96add5a5e5b15ed36ca1d5aa09f7173b

Tracer expects that cputicks are globally monotonic and has cycle precision (subsequent events has different timestamps). The former is probably true for this impl, but the latter is not true.

**Comment by crawshaw** [comment]
ARMv6 and ARMv7 has a cycle counter, but it is privileged

http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0211i/Bihcgfcf.html

What about using the perf_event_open syscall on linux?

http://man7.org/linux/man-pages/man2/perf_event_open.2.html

**Comment by dvyukov** [comment]
As far as I see, it requires using read syscall to access cpu cycle counter. This may be too expensive for tracer. However, we don't have better solutions for now.
I was thinking about converting a low-frequency monotonic timer into monotonically increasing:

var prevTicks int64

func cputicks() int64 {
  for {
    x := nanotime()
    p := prevTicks
    if x <= p {
      x = p + 1
    }
    if cas(&prevTicks, p, x) {
      return x
    }
  }
}

This also can be slow and obviously will give locally skewed traces.

**Comment by crawshaw** [comment]
Right now nanotime is a syscall on linux/arm, so a read from perf_event_open shouldn't be any more expensive. Your way might be better if we switch to VSDO for time on linux/arm, but I cannot work out when it was introduced into linux for arm.

**Comment by mwhudson** [comment]
I don't think linux/arm has a VDSO function for time.  There are some kernel patches floating around but nothing in Linus' tree that I can see. (I've had the reasons this is hard on ARM explained to me a few times but never really understood it...)

**Comment by davecheney** [comment]
Dmitry, you mentioned that your trace infrastructure is based on chrome. If
this is correct, how does chromeos on arm handle this requirement?

**Comment by davecheney** [comment]
Another weird thing is the test reliably fails on my dual core Pandaboard,
but passes on the quad core imx6 machine I have. This might just be dumb
luck.

**Comment by dvyukov** [comment]
@davecheney Here is how chromium does that:
#9892

**Comment by dvyukov** [comment]
@mwhudson clock_gettime on arm/arm64 is even already documented in man pages:
http://man7.org/linux/man-pages/man7/vdso.7.html
@crawshaw Can you check what kind of precision __kernel_clock_gettime(CLOCK_MONOTONIC) gives on arm/arm64?

**Comment by matt2909** [comment]
did anyone follow up on this?

**Comment by minux** [comment]
even if the clock_gettime exported in vDSO is faster,
we can't always use it as it's only exported for ARM
since v4.1 of the kernel.

**Comment by davecheney** [comment]
> even if the clock_gettime exported in vDSO is faster,
we can't always use it as it's only exported for ARM
since v4.1 of the kernel.

Wow, that's fresh. Most SoC's are lucky if they can do better than some moldy version of 3.0 that seems to ship with all iMX6 platforms.

**Comment by matt2909** [comment]
Wait v4.1? my take is v3.10
http://lxr.free-electrons.com/source/arch/arm64/kernel/vdso/gettimeofday.S?v=3.10

**Comment by minux** [comment]
It's the 32-bit arm kernel that only exposes the clock_gettime starting
from 4.1, and your link clearly states it's about arm64.

**Comment by matt2909** [comment]
Yes my bad, I read arm, as arm in general. 32bit arm is 4.1, arm64 is much earlier

**Comment by rsc** [comment]
It sounds like this is not easy to fix (because of hardware privilege issues). Also the new trace sequence numbers may mean we don't need to fix it, since these things don't all compare equal anymore. I'm going to mark this as closed unless there's some reason to keep it open.
