### ISSUE TITLE
runtime: presumably heap corruption 

### ISSUE THREAD

**Issue by dvyukov** [golang/go#9727]
$ GOGC=1 go test -short -cpu=16,16,16,16,16,16,16,16 crypto/rsa
Fails with:
--- FAIL: TestPSSGolden-16 (0.06s)
	pss_test.go:160: crypto/rsa: verification error

git bisect points to:
commit 13aff7831d32c80b98ede611f1ffb0476f16ec51
Author: Rick Hudson
Date:   Mon Jan 26 13:51:39 2015 -0500
    runtime: avoid redundant scans

Race builders also detected fatal errors on this commit:
http://build.golang.org/log/bfca7707a0ccb2dd15e8228eb5b97434c33d1143
http://build.golang.org/log/c0e4c3f3407b621265b706c67b780d32d4c7564e

**Comment by RLH** [comment]
I understand the crypto/rsa bug, not sure about the Race builders.
