### ISSUE TITLE
cmd/go: go generate line ending problem

### ISSUE THREAD

**Issue by propag** [golang/go#9730]
on windows line ending (\r\n)
`main.go:3: running "go\r": exec: "go\r": executable file not found in %PATH%`

on unix line ending (\n), problem not happened

it seems that go generate do not handle line ending appropriately.

**Comment by adg** [comment]
Can you please provide `main.go`?

**Comment by propag** [comment]
Here full main.go

```go
package main

//go:generate go

import "fmt"

func main() {
	fmt.Println("Hello Go World")
}
```

**Comment by adg** [comment]
I sent this: https://go-review.googlesource.com/3604

@propag do you want to try [building Go from source](https://golang.org/doc/install/source) using revision  378716f886cad106c8b15a55ea9dbc92f57df4a5?

Run:
```
git clone https://go.googlesource.com/go
git pull origin 378716f886cad106c8b15a55ea9dbc92f57df4a5
cd go/src
./make.bash
```

And then try running go generate against that file.

**Comment by propag** [comment]
Good! work nice!

**Comment by minux** [comment]
This has already been fixed on tip.
This issue is a dup of #9264.
