### ISSUE TITLE
cmd/gc: internal compiler error: typecheckclosure: var x does not have decldepth assigned

### ISSUE THREAD

**Issue by griesemer** [golang/go#9731]
The following program doesn't compile:

package p

func f(x interface{}) {
	switch x := x.(type) {
	case map[int]int:
		func() {
			for range x {
			}
		}
	}
}

x.go:6: internal compiler error: typecheckclosure: var x does not have decldepth assigned

$ go version
go version devel +0a24b8c Wed Jan 28 23:22:16 2015 +0000 darwin/amd64

I suspect this was recently introduced since it doesn't seem to be present on the playground, for instance.

This looks like the culprit:

https://go.googlesource.com/go/+/0e80b2e082db784c55ec26ed997226e11c4f5f46

**Comment by griesemer** [comment]
PS: This is currently breaking the tools build; e.g.:

http://build.golang.org/log/724f5e516fb381e62bd53a778876ac0ce060900f

**Comment by dvyukov** [comment]
Thanks for minimizing test case!

There is a general typechecking bug: compiler does not check left expr of type switches. That leads to another disastrous consequence. Namely, if you write:

switch unsafe.Sizeof := x.(type) {

The compiler does not say "unsafe.Sizeof is not an expression, must be called", as it usually does. How have nobody ever noticed this?!

**Comment by griesemer** [comment]
I suspect most people try to write correct code and with respect to type switches that seems to be not too hard...
