### ISSUE TITLE
x/sys/unix: ptrace API assumes GOARCH(target) == GOARCH(host)

### ISSUE THREAD

**Issue by 4ad** [golang/go#9739]
syscall.PtraceGetRegs uses syscall.PtraceRegs. syscall.PtraceRegs depends on the host, e.g. if your binary is linux/386 syscall.PtraceRegs has 16 registers. But it's possible to run that linux/386 on an amd64 kernel, and attach to an amd64 process. In that case, syscall.PtraceRegs is not good anymore because the amd64 variant has 26 registers.

I have found this while trying to debug an arm64 Go process using an arm Go debugger.

**Comment by 4ad** [comment]
Well, obviously there is nothing we can do about this particular API, because of Go 1 contract, but presumably we can add Ptrace(Get|Set)Regs(386|Amd64) on both 386 and amd64. Thoughts?

**Comment by tv42** [comment]
Even with Go1 api freeze, golang.org/x/sys/unix can be fixed.

**Comment by rsc** [comment]
Is it really unfixable without an API change?

**Comment by 4ad** [comment]
Well we can add more precise APIs, leaving the current one (assuming ARCH(target) == ARHC(host)) as is, but that's just adding stuff rather than fixing existing stuff, so I don't consider that as "fixing" anything.

And as for adding stuff, we can add it in some other repository, it doesn't have to be inside syscall.

**Comment by bradfitz** [comment]
Repurposed this to be about x/sys/unix.
