### ISSUE TITLE
playground: does not produce the same results as installed go.

### ISSUE THREAD

**Issue by robertfmurdock** [golang/go#9740]
See this playground:

https://play.golang.org/p/OtcBZ-HN8l

This text is correctly escaped when run from the playground. When running this code from within a standard test (using the testing package), only the last line within the string is returned.  This behavior has been observed on both Ubuntu 14.4 and Mac OS X when using Go 1.4.1.

**Comment by mikioh** [comment]
I'm not sure what are you asking for. I think you can use the verb %q instead of %v if you want to make the unescaped output visible/printable using the fmt package. 
```
fmt.Printf("Hello, playground\n%q", translated)
```

**Comment by robertfmurdock** [comment]
Oh, maybe I didn't make it clear: the current playground runtime does not produce the same results as installed Go.  The playground outputs the entire string. In contrast, when run as a program from an installed and built package it only outputs ~70 characters; the last section of the string. Is that expected behavior?

**Comment by minux** [comment]
In the example, the output contains a lot of \r, which, depending on the
terminal, used might mean go to the start of the line, or change to the
next line.

Apparently, on unix, \r means has the former meaning, so every line
except the first will be overwritten again and again. As there is a final
\r in the output, the final result will be an empty 2nd line (without \n,
and then the shell prompt will appear on that line as usual). This
makes it appear that the program only outputs one line of message,
but it's not. You can verify that it does print out the other lines using
hexdump(1) or redirect the stdout to a file.

On the playground, \r is treated the same as \n. This is not unreasonable
given that the playground is not emulating any particular terminal.
(And it does handle \r\n correctly as one line.)

This is a simplified example: https://play.golang.org/p/Hk3jiGbIii

I don't think it's a bug of playground: it's not a terminal emulator.

**Comment by robertfmurdock** [comment]
That totally makes sense. Thanks! :-)
