### ISSUE TITLE
Compiler crashing with multiple invalid recursive types

### ISSUE THREAD

**Issue by fogleman** [golang/go#9746]
*What version of Go are you using (go version)?*

go version go1.4.1 darwin/amd64

*What did you do?*

	type Test struct {
		a, b Test
	}

*What did you expect to see?*

Expect the compiler to complain about a recursive type.

*What did you see instead?*

The compiler crashed:

go build github.com/fogleman/pt: /usr/local/Cellar/go/1.4.1/libexec/pkg/tool/darwin_amd64/6g: signal: segmentation fault

*This sample works as expected:*

	type Test struct {
		a Test
	}

**Comment by ALTree** [comment]
This is #9432

**Comment by minux** [comment]
Right, this has been fixed on tip.
