### ISSUE TITLE
ssh: documentation examples omit package name, causing non-runnable code

### ISSUE THREAD

**Issue by einthusan** [golang/go#9747]
`Dial` instead of `ssh.Dial` is just one instance of many.

**Comment by davecheney** [comment]
I agree the examples could be more useful if the example was converted to
an external test, ie, package ssh_test.

Its a pretty straight forward operation, do you feel like taking a crack?

**Comment by einthusan** [comment]
sure :)

**Comment by einthusan** [comment]
I have the fix, but the damn pull-request method being outside of Github is confusing! can I just send you the code change and you can do the request lol :P .. being lazy

**Comment by davecheney** [comment]
Please don't send me code, I cannot submit it on your behalf.

I'll take care of this soon.

**Comment by davecheney** [comment]
https://go-review.googlesource.com/#/c/3710/

**Comment by einthusan** [comment]
@davecheney yep, looks good. thanks for doing this.

**Comment by davecheney** [comment]
Not a problem.
