### ISSUE TITLE
cmd/gc: allocate slice for []byte -> string conversion on heap.

### ISSUE THREAD

**Issue by DanielMorsing** [golang/go#9748]
A pattern that I've been finding myself writing a lot recently is

    func somefunc() string {
        b := make([]byte, 0, somecap)
        // build a string component by component
        return string(b)
    }

In the case where we don't touch the byte slice after the string conversion and the byte slice otherwise doesn't escape, we can allocate the slice on the heap and use the non-copying slicetostringtmp function to create the string, eliminating copying and an allocation.

**Comment by dvyukov** [comment]
Dup of #6714
