### ISSUE TITLE
cmd/compile: don't emit writebarrier for stores to newly allocated objects

### ISSUE THREAD

**Issue by dvyukov** [golang/go#9755]
Consider the following code:

x := &X{&obj, make([]int, n)}
...

Compiler transforms it to roughly the following code:

tmp0 := runtime.makeslice(int, n)
tmp1 := runtime.newobject(X)
runtime.writebarrierptr(&tmp1.f0, &obj)
runtime.writebarrierslice(&tmp1.f2, tmp0)

I suspect that barriers are unnecessary in this case because tmp1 is accessible only through the stack of the current goroutine. So &obj and tmp0 will be found and marked during stack scanning.

It seems that a simple approximation of the "is accessible only through the stack of the current goroutine" condition is "we have not yet encountered any calls since allocation of the object". That is:

tmp1 := runtime.newobject(X)
tmp1.f0 = ...  // no write barrier
tmp1.f1 = ...  // no write barrier
any function call 
tmp1.f0 = ...  // write barrier
tmp1.f2 = ...  // write barrier

**Comment by dvyukov** [comment]
@rsc @RLH @randall77

**Comment by dvyukov** [comment]
I've calculated an optimistic approximation of the potential win by counting runtime.writebarrier calls right after runtime.newobject calls w/o any intervening calls in godoc binary.
Total number of writebarrier calls = 9732
writebarrier calls right after newobject = 2495
= ~25%

**Comment by RLH** [comment]
I'm not sure the gain is as large as you imply with your 25% number. If the
write barrier is off then the compiler will eventually emit a normal path
of a load of gcphase, a compare, and a branch.  Since the branch is
predictable any reasonable OOO machine will do a pretty good job hiding the
sequence. It will be great when we get to a point where these types of
performance optimizations are at the top of our list for increasing
performance.

**Comment by rsc** [comment]
The compiler now emits the needWriteBarrier check. I think that's enough for Go 1.5. We can revisit this if and when profiles show that we're spending too much time on things like this.

**Comment by randall77** [comment]
This is fixed now; the following code has no write barriers:
```
package main

type X struct {
	p *int
	q []int
}

var obj int

func f(n int) {
	x := &X{&obj, make([]int, n)}
	g(x)
}

//go:noescape
func g(x *X)
```
