### ISSUE TITLE
cmd/ld: Build (go build) does not produce identical binaries

### ISSUE THREAD

**Issue by davecgh** [golang/go#9756]
As the title indicates, running go build on the same machine with no changes does not produce identical binaries on Windows even though it does on Linux/BSD.

To see this in action, run the following one-line command on Windows and Linux/BSD:

```bash
$ mkdir $GOPATH/src/unstable; cd $GOPATH/src/unstable; echo "package main; func main() {}" > main.go; go build -o a; go build -o b; openssl sha a b
```
Output on Windows:
> SHA(a)= 5d5a08499e18e2475fb51d72eee2100afb8ec277
> SHA(b)= 49a016bf798c8a3c0fa88f06372303dd4b3f224f

Output on Linux:
> SHA(a)= 28f40782581aece883589efaa5dc5e269a46b71d
> SHA(b)= 28f40782581aece883589efaa5dc5e269a46b71d

Output on OpenBSD:
> SHA(a)= 962127cf3e97dd22aa8a879c9be58a9643ede0ae
> SHA(a)= 962127cf3e97dd22aa8a879c9be58a9643ede0ae

Further, I've compared the output of strings between the two binaries and there is no difference, but by doing `$ cmp --verbose --print-chars a b`, it appears to be a time stamp that is the cause.

-----
Issue submission questions:

> What version of Go are you using (go version)?
> What operating system and processor architecture are you using?

```bash
$ go version
go version go1.4.1 windows/amd64
```

> What did you do?

I ran the commands provided above.

> What did you expect to see?

The generated binary should be identical and therefore have the same hash on Windows like it does on Linux and BSD.

> What did you see instead?

The generated binaries are not identical on Windows although they are on Linux/BSD.

**Comment by ianlancetaylor** [comment]
It's this line in cmd/ld/pe.c:
	fh.TimeDateStamp = time(0);

I will let the Windows folks decide, but I think we should simply remove that line.  It was a mistake for COFF to put a timestamp into the object file format, and it was a mistake for PE to copy it.  The corresponding code in the GNU linker says the following (apologies for language):

  /* We will NOT put a fucking timestamp in the header here. Every time you
     put it back, I will come in and take it out again.  I'm sorry.  This
     field does not belong here.  We fill it with a 0 so it compares the
     same but is not a reasonable time. -- gnu@cygnus.com  */
  internal_f.f_timdat = 0;

**Comment by minux** [comment]
I've been planing to do get rid of the timestamp for a long time.

https://go-review.googlesource.com/3740
