### ISSUE TITLE
playground: numeric iteration via range can be compiled, but not formatted

### ISSUE THREAD

**Issue by nightlyone** [golang/go#9765]
This formats correctly locally using up2date Go 1.4.1 tooling, but fails to format in the playground
```go
package main

import "fmt"

func main() {
        for range make([]struct{}, 5) {
		fmt.Println("Hello, playground")
	}
}
```
s. for reference http://play.golang.org/p/k9Z2WhCWVl

**Comment by minux** [comment]
@adg it seems the playground service itself is still using old pre-1.4
runtime?

**Comment by adg** [comment]
Fixed now.
