### ISSUE TITLE
cmd/go: first go get with local path downloads but does not build

### ISSUE THREAD

**Issue by robpike** [golang/go#9767]
% echo $GOROOT
/Users/r/go
% pwd
/Users/r/src/rsc.io
% go get ./toolstash
package rsc.io/toolstash: cannot find package "rsc.io/toolstash" in any of:
	/Users/r/go/src/rsc.io/toolstash (from $GOROOT)
	/Users/r/src/rsc.io/toolstash (from $GOPATH)
% go get ./toolstash
% 

If the first download uses a full path (rsc.io/toolstash), there is no problem.

**Comment by sbinet** [comment]
tentatively: https://golang.org/cl/6266
