### ISSUE TITLE
liblink, cmd/9g: [dev.cc] -S output messed up

### ISSUE THREAD

**Issue by mwhudson** [golang/go#9768]
Compiling even the most trivial file such as:

```go
package main

func main() {

}
```

with 9g -S from the dev.cc branch produces insane output (https://gist.github.com/mwhudson/747ac3935cb84080a409, scroll to the right).  What seems to be happening is that each time an instruction is printed it reprints all instructions from that function already, like some buffer isn't being reset or something.  It doesn't happen on master.

**Comment by minux** [comment]
It has been fixed by CL 3511, but dev.cc doesn't contain the fix yet.

Will close as this will eventually be fixed when it's time to merge master.
