### ISSUE TITLE
runtime: TestRuntimeGogoBytes fails on windows-amd64

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#9770]
From our windows-amd64 builder http://build.golang.org/log/103c8ab8ef59e275c5c419a876ade9f4073a6dc5

--- FAIL: TestRuntimeGogoBytes (0.22s)
	runtime_test.go:124: RuntimeGogoBytes = 96, should be 80
FAIL
FAIL	runtime	23.900s

windows-386 is good. It seems to be broken starting from:

commit	3c0fee10dbe82771dcaa956a95bdfabdced5fff7
author	Austin Clements <austin@google.com>	Wed Jan 14 11:09:50 2015 -0500
cmd/6g, liblink, runtime: support saving base pointers

Alex

**Comment by aclements** [comment]
I suspect the same problem will affect Solaris and Plan 9, but those builders are blocked by bigger test failures, so I can't confirm.
