### ISSUE TITLE
smtp mail configuration

### ISSUE THREAD

**Issue by Melkor930425** [golang/go#9772]
Hi, this is not an issue, is more like a doubt, how can i configure the PlainAuth in the smtp lib to ignore the x509 certificates, the only thing that I found´ til know is to change it in the source of the lib, later i will make a pull request, thanks...

**Comment by ianlancetaylor** [comment]
Please ask questions on the mailing list golang-nuts@googlegroups.com.  Thanks.

Also, note that we don't use pull requests.  Please see http://golang.org/doc/contribute.html.  Thanks.
