### ISSUE TITLE
net/smtp: package document does not explain how to add subject and body in msg parameter

### ISSUE THREAD

**Issue by JiranD** [golang/go#9776]
The net/smtp package document does not mention how to add subject and body for emails sent. http://golang.org/pkg/net/smtp/#SendMail

Here is an example of one way to have both subject and body text -

auth := smtp.PlainAuth(
    "",
    "email@example.com",
    "password",
    "smtp.example.com",
)

// Connect to the server, authenticate, set the sender and recipient,
// and send the email all in one step
// The Byte array provides both Subject and body
err := smtp.SendMail(
   "smtp.example.com:587",
   auth,
   "me@example.com",
   []string{recipient@example.com},
   []byte("Subject: Test Subject Text \r\n\r\n Test Email Body Text"),
)

if err != nil {
   fmt.Println("Email Error: ", err)
}

**Comment by minux** [comment]
This is standard SMTP behavior.

Do you want to add an example to the net/smtp package? Please feel free.
See https://golang.org/doc/contribute.HTML for the procedure.

**Comment by bradfitz** [comment]
Sent https://go-review.googlesource.com/4162
