### ISSUE TITLE
Contribution guidelines don't specify code review process for non-main repos

### ISSUE THREAD

**Issue by jacobsa** [golang/go#9778]
The [Contribution Guidelines][doc] doc says that `git mail` will automatically cc golang-codereviews on all code reviews. However I mailed the following two reviews today, and it doesn't appear as if that happened for either one:

1. https://go-review.googlesource.com/#/c/3902/
2. https://go-review.googlesource.com/#/c/3950/

I assume that's because these aren't in the core repository. Can you confirm? And should the documentation be updated to be clearer about what to do for other repos?

[doc]: https://golang.org/doc/contribute.html

**Comment by minux** [comment]
No. They didn't appear instantly is because golang-dev is moderated.

**Comment by minux** [comment]
The cc is really handled by Gerrit, but that's implementation detail.

**Comment by jacobsa** [comment]
Silly me, I didn't realize there was a moderation delay. Thanks.
