### ISSUE TITLE
cmd/6g: Unhelpful error message (doesn't detect recursive type)

### ISSUE THREAD

**Issue by Grovespaz** [golang/go#9780]
The following file: http://play.golang.org/p/Gb4JFw89eF
Causes 6g to run out of stack (I think) and die with a strange error message.

Of course the issue in the example code could be worked around, but it is hard to find in a bigger project.
It would be nice if go could detect this kind of mistake and not burn when it happens.

Go version 1.4 windows/amd64, also reproducable in the playground.
Windows gives: D:\GoRoot\pkg\tool\windows_amd64\6g.exe: exit status 3221225725
Linux (playground) gives: go build command-line-arguments: /usr/src/go/pkg/tool/linux_amd64/6g: signal: segmentation fault

**Comment by minux** [comment]
Dup of #9432, and already fixed on tip.
