### ISSUE TITLE
net/textproto: DotReader can't determine end of data after empty line

### ISSUE THREAD

**Issue by yosida95** [golang/go#9781]
DotReader handles lines only ends with CRLF in document, but source code seems to handle ends with only LF too and I expected that behavior.  

This issue is one that DotReader can't determine end of data after empty line ends with LF not CRLF.  I confirmed that this issue still exists in current master ( 08ca401444cd3e08a98d7fd3f57e44b95243b4fb ).

I am ready to send the patch to fix this issue.

**Comment by bradfitz** [comment]
Before you send a patch, can you post here a play.golang.org snippet showing the problem?

**Comment by yosida95** [comment]
here http://play.golang.org/p/5K_Qu2zhJ-

**Comment by mattn** [comment]
AFAICS, DotReader allow only `\r\n`.

http://golang.org/pkg/net/textproto/#Reader.DotReader

**Comment by yosida95** [comment]
I see that, but source code of net/textproto seems to treat LF too. For instance https://github.com/golang/go/blob/08ca401444cd3e08a98d7fd3f57e44b95243b4fb/src/net/textproto/reader.go#L369-L371, this block should not be needed to support only CRLF.

**Comment by yosida95** [comment]
Oh, I maybe found the reason of this behavior in RFC5321 SMTP.
```
The custom of accepting lines ending only in <LF>, as a concession to
non-conforming behavior on the part of some UNIX systems, has proven
to cause more interoperability problems than it solves, and SMTP
server systems MUST NOT do this, even in the name of improved
robustness.  In particular, the sequence "<LF>.<LF>" (bare line
feeds, without carriage returns) MUST NOT be treated as equivalent to
<CRLF>.<CRLF> as the end of mail data indication.
```
(From Section 4.1.1.4 DATA)

I think that net/textproto follows this spec, isn't it?

**Comment by rsc** [comment]
Brad, he posted a program.

**Comment by bradfitz** [comment]
What is this affecting? Are you having interop problems with a certain client or server? And which protocol?

**Comment by yosida95** [comment]
Thank you for taking your time.

When I create this issue, I wrote a SMTP (RFC5321) server implementation and try to use DotReader to handle DATA command defined in the RFC.

Please take this new snippet http://play.golang.org/p/fYqeKwUwkT , I indicated about how DotReader doesn't follow [its document](http://golang.org/pkg/net/textproto/#Reader.DotReader).

In additional, RFC5321 warns about customizing to  accept lines ending only in <LF> in [§4.1.1.4](https://tools.ietf.org/html/rfc5321#section-4.1.4).
>  The custom of accepting lines ending only in <LF>, as a concession to
>   non-conforming behavior on the part of some UNIX systems, has proven
>   to cause more interoperability problems than it solves, and SMTP
>   server systems MUST NOT do this, even in the name of improved
>   robustness.

**Comment by bradfitz** [comment]
Sorry for the delay here. Yes, it looks like we're following the strict rules from RFC 5321.

I'm going to close this without making any changes. The documentation seems accurate too.
