### ISSUE TITLE
fsnotify: EINTR from Error channel (linux/x64)

### ISSUE THREAD

**Issue by PieterD** [golang/go#9782]
Platform:
linux/x64, 1.4.1 (binary download).

Problem:
fsnotify's Error chan leaked an EINTR. I don't think this is meant to happen.
I may have time to investigate further this weekend.

I can reproduce the problem with this:
```
package main

import (
  "time"
  "fmt"
  "golang.org/x/exp/fsnotify"
  "os"
  "syscall"
)

func Panic(err error) {
  if err != nil {
    panic(err)
  }
}

func main() {
  go sig()
  go notify()
  <-time.After(5 * time.Second)
}

func notify() *fsnotify.Watcher {
  w, err := fsnotify.NewWatcher()
  Panic(err)
  defer w.Close()
  err = w.Watch(".")
  Panic(err)
  defer w.RemoveWatch(".")
  for {
    select {
    case err := <-w.Error:
      Panic(fmt.Errorf("fsnotify error from Error channel: %#v", err))
    case <-w.Event:
    }
  }
}

func sig() {
  p, err := os.FindProcess(os.Getpid())
  Panic(err)
  for {
    p.Signal(syscall.SIGUSR1)
  }
}
```

**Comment by PieterD** [comment]
github.com/go-fsnotify/fsnotify has the same problem, see issue: https://github.com/go-fsnotify/fsnotify/issues/61

It looks like the syscall.Read used to read events blocks, so shouldn't that goroutine get at least a runtime.LockOSThread? I feel this may be true, because the runtime doesn't know about the blocking call- but I don't know quite enough about the internals.

Anyway, whatever the case, the Read can be interrupted by signals, and that error should probably be ignored instead of sending it over Error.

Please confirm.

**Comment by ianlancetaylor** [comment]
It's fine to make a blocking call to syscall.Read without calling runtime.LockOSThread.  Blocking syscalls are fine in general.

**Comment by PieterD** [comment]
Understood, thanks. It just didn't feel right, thanks for clearing it up.

I'll send a CL for EINTR in the near future.

**Comment by minux** [comment]
How could the Read syscall return EINTR given that all signals have
SA_RESTART bit set?

**Comment by PieterD** [comment]
@minux I don't know, but it's apparently a thing. Other than my own experience, I found this: https://github.com/gittup/tup/blob/master/src/tup/monitor/inotify.c
line 540: /* SA_RESTART doesn't work for inotify fds */

**Comment by davecheney** [comment]
I wonder if this explains why I had to deal with EINTER from epoll_wait(2)

On Fri, Feb 6, 2015 at 7:50 AM, Pieter Droogendijk <notifications@github.com

**Comment by PieterD** [comment]
@davecheney : http://man7.org/linux/man-pages/man7/signal.7.html

```
Before Linux 3.8, reads from an inotify(7) file descriptor were not restartable;
when interrupted by a signal handler, read(2) always failed with the error EINTR.

...

The following interfaces are never restarted after being interrupted by a signal handler,
regardless of the use of SA_RESTART;
they always fail with the error EINTR when interrupted by a signal handler:

File descriptor multiplexing interfaces:
epoll_wait(2), epoll_pwait(2), poll(2), ppoll(2), select(2), and pselect(2).
```

I guess that's that. Unsettling.

**Comment by davecheney** [comment]
"

The following interfaces are never restarted after being interrupted
by a signal handler,
regardless of the use of SA_RESTART;
they always fail with the error EINTR when interrupted by a signal handler:

File descriptor multiplexing interfaces:
epoll_wait(2), epoll_pwait(2), poll(2), ppoll(2), select(2), and pselect(2).

I guess that's that. Unsettling.

"

Could you please log a bug on golang/go and i'll make sure this is fixed
once and for all in the std lib.

On Fri, Feb 6, 2015 at 8:00 AM, Pieter Droogendijk <notifications@github.com

**Comment by PieterD** [comment]
@davecheney : No problem. I hope this will do: https://github.com/golang/go/issues/9785

**Comment by rsc** [comment]
fsnotify has been removed from exp
