### ISSUE TITLE
Printf %#v doesn't consider String() methods of types

### ISSUE THREAD

**Issue by Eloff** [golang/go#9783]
I ran into this with an enum type: http://play.golang.org/p/rK_gIV72ea

But itemType defines a String() method which, were it used, would make the Printf a lot more readable. Wasn't String() designed for Printf?

Is there a reason this can't or shouldn't be done? If not I would like to create and contribute a patch.

**Comment by adg** [comment]
`%#v` formats the argument as "a Go-syntax representation of the value". A stringer does not produce such a representation. Use `%v` if you want to invoke a stringer.

**Comment by ianlancetaylor** [comment]
Note that you can customize %#v output by defining a GoString method.

**Comment by Eloff** [comment]
Forgot about GoString(), that's what I was looking for. testify uses %#v to produce messages for assert.Equal, which is lousy for enums. But now I have an easy way to fix it. Thanks.
