### ISSUE TITLE
runtime, syscall: SA_RESTART does not affect all system calls

### ISSUE THREAD

**Issue by PieterD** [golang/go#9785]
http://man7.org/linux/man-pages/man7/signal.7.html

`The following interfaces are never restarted after being interrupted by a signal handler, regardless of the use of SA_RESTART; they always fail with the error EINTR when interrupted by a signal handler:`

What follows is a list of system calls including "File descriptor multiplexing interfaces" and "System V IPC interfaces" (and inotify before Linux 3.8, which is how I found out in the first place: see https://github.com/golang/go/issues/9782).

The standard library should be checked for use of these system calls and, where required, keep EINTR in mind.

**Comment by davecheney** [comment]
This is why we can't have nice things.

**Comment by ianlancetaylor** [comment]
My only thought is that the last time I looked at this they were all handled correctly.  I have no objection to somebody else checking.

**Comment by rsc** [comment]
Unless you know of a specific problem, I don't see any work here.
