### ISSUE TITLE
webdav: TestDir fails on windows

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#9786]
C:\>go test golang.org/x/net/webdav
--- FAIL: TestDir (0.00s)
        file_test.go:506: test case #65 "rename /c /d/n/q want ok": got "errExist" (rename C:\DOCUME~1\brainman\LOCALS~1\Temp\webdav-test593615143\c C:\DOCUME~1\brainman\LOCALS~1\Temp\webdav-test593615143\d\n\q: Cannot create a file when that file already exists.), want "ok"
FAIL
FAIL    golang.org/x/net/webdav 0.547s

This is broken on windows builders too.

Alex

**Comment by alexbrainman** [comment]
Proposed fix is here https://go-review.googlesource.com/4020

Alex

**Comment by nigeltao** [comment]
Counter-proposal: https://go-review.googlesource.com/4341
