### ISSUE TITLE
go-1.4, go-1.4.1: Segfault on structure containing itself

### ISSUE THREAD

**Issue by jeeger** [golang/go#9788]
Defining a structure that contains itself multiple times makes the compiler segfault in go 1.4 and go 1.4.1. If the structure contains itself only once, a correct warning is triggered.

The segfault can be triggered like this (playground link: http://play.golang.org/p/OcRr3GyH5o):

```
package main

struct recursive {
    rec1 recursive
    rec2 recursive
}
```

**Comment by ALTree** [comment]
This is #9432 and it's fixed on tip.

**Comment by jeeger** [comment]
Whoops, sorry.

**Comment by ALTree** [comment]
( This gets reported a lot. Maybe should be cherry-picked for 1.4.2? )

**Comment by minux** [comment]
Changed milestone for issue 9432 to Go 1.4.2.
(That doesn't guarantee its inclusion into Go 1.4.2 though.)
