### ISSUE TITLE
Proposal: Rename project to "errlang"

### ISSUE THREAD

**Issue by thieman** [golang/go#9790]
Go was clearly named with a few simple goals in mind, namely:

1. The language should have a short name and a longer name formed by appending "lang" to the short name.
1. The language's name should reflect one of the most common words in programs written in the language.
1. It should be nigh impossible to search the web for anything related to the language.

The current name made a good effort at meeting all of those goals, but I believe I have found something even better.

It is therefore proposed that this project be renamed to **errlang**.

**Comment by inlinestyle** [comment]
+1

**Comment by ianlancetaylor** [comment]
I like amusing commentary as much as the next person, but that is what the mailing list is for.  Keep the issue tracker for issues.  Thanks.
