### ISSUE TITLE
net/http: default User-Agent is invalid

### ISSUE THREAD

**Issue by everett-toews** [golang/go#9792]
The [default User-Agent](http://golang.org/src/net/http/request.go#L336)

    Go 1.1 package http

in the http package doesn't appear to be valid according to the [User-Agent section of RFC 7231](http://tools.ietf.org/html/rfc7231#section-5.5.3).

Go should have a properly formatted User-Agent. e.g.

    Go-http/1.1

**Comment by sigmavirus24** [comment]
Also, since it seems like "1.1" might be the version of Go not the package, it might make sense to do something like

    Go-1.1-http-package/{package-version}

But I'm not sure if there is a version for standard packages.

**Comment by bradfitz** [comment]
I've never had opinions on this. I believe @rsc picked this string on purpose.

**Comment by rsc** [comment]
I have never seen anything about user-agent syntax before. Sorry.

**Comment by syst3mw0rm** [comment]
Here's the proposed fix - https://go-review.googlesource.com/#/c/9385/

**Comment by bradfitz** [comment]
I would like to put the Go version number in the User-Agent.  Perhaps we only include it if it's not a dev release?  So `go-package-http/1.5` or `go-package-http/dev` but never `go-package-http/GITCOMMITHASH`. @rsc, thoughts?

**Comment by syst3mw0rm** [comment]
I agree with @bradfitz to not include the `GITCOMMITHASH`.
