### ISSUE TITLE
x/build/buildlet: trim go1.4 tarballs

### ISSUE THREAD

**Issue by bradfitz** [golang/go#9797]
Not high priority, but there's a lot of stuff in our go1.4 tarballs that are untarred on builds which can be removed to reduce network & disk I/O and thus improve build latency:

```
api
misc
test
doc
**/testdata
**/*_test.go
bin/gofmt*  (exe or not)
```

Biggest things:

```
1388    ./pkg/tool/windows_amd64/6l.exe
1548    ./pkg/windows_amd64/net.a
1548    ./pkg/windows_amd64/runtime.a
1560    ./pkg/windows_amd64/cmd/internal/rsc.io
1604    ./pkg/tool/windows_amd64/6c.exe
1652    ./pkg/windows_amd64/net/http.a
1668    ./pkg/windows_amd64/text
1816    ./pkg/windows_amd64/debug
1924    ./pkg/obj/windows_amd64/libgc.a
1996    ./pkg/windows_amd64/cmd/internal
2016    ./pkg/windows_amd64/cmd/pprof/internal
2020    ./pkg/windows_amd64/cmd/pprof
2344    ./pkg/tool/windows_amd64/pack.exe
2712    ./pkg/windows_amd64/crypto
2784    ./pkg/windows_amd64/go
2808    ./pkg/tool/windows_amd64/6g.exe
2956    ./pkg/windows_amd64/encoding
3048    ./src/syscall
3436    ./pkg/tool/windows_amd64/yacc.exe
3528    ./pkg/tool/windows_amd64/fix.exe
3672    ./bin/gofmt.exe
3716    ./src/runtime
3788    ./pkg/obj/windows_amd64
3792    ./pkg/obj
3972    ./pkg/windows_amd64/net
4020    ./pkg/windows_amd64/cmd
4220    ./pkg/tool/windows_amd64/addr2line.exe
4236    ./pkg/tool/windows_amd64/nm.exe
4420    ./pkg/tool/windows_amd64/objdump.exe
4584    ./pkg/tool/windows_amd64/cgo.exe
5820    ./src/cmd
9396    ./bin/go.exe
9828    ./pkg/tool/windows_amd64/pprof.exe
13072   ./bin
21036   ./src
36408   ./pkg/windows_amd64
43444   ./pkg/tool/windows_amd64
43448   ./pkg/tool
83652   ./pkg
118472  .
```

Probably don't need pprof, objdump, nm, yacc, etc to bootstrap Go 1.5.

Do we even need the source? I forget when/why the go tool consults it. Did we ever add a mode to have it not look for source?

/cc @adg

**Comment by minux** [comment]
We need to provide at least a file containing the package statement for
each package to satisfy the go tool (also need to make sure the dummy
source file should have earlier timestamp than its pkg.a file.

However, I think just removing unused Go based programs (I think only
bin/go, tool/6g, tool/6l are needed) will recover more space than removing
all the source code.

**Comment by bradfitz** [comment]
There's a cost to just opening, writing, and closing a file, however small, since it needs to do discontiguous reads/writes for the inode metadata, etc. Eliminating a few thousand of them seems worthwhile.

**Comment by minux** [comment]
sure, I thought you only concerned about the total size of the tarball.

But given we always require Go 1.4 to bootstrap, can we just add Go 1.4 to
the base image. (We can always use 1.4.0, because we can't assume what
version the final user is using, so we should only the least version.)

The go15bootstrap document said we want to keep the compiler bootstrapable
with 1.4 for as long as possible, now this is one more reason to keep that
promise.

When building the base image we can use adg's gostrip tool to build a
minimal Go 1.4 installation.

**Comment by bradfitz** [comment]
I did end up baking Go 1.4 into the Linux images, since they were easy to generate (with Docker).

But the VM images are slow enough to generate, I'd rather not bake in Go 1.4 in general, since it gives us more flexibility to not touch the VM image (the buildlet library supports either way, though).

I suppose to eliminate disk I/O (if we don't care about the network transfer speed, which I don't really), we could teach the buildlet to just skip over certain file entries when writing Go 1.4 to disk.  That's probably easiest, and fixes the problem for all builders retroactively without regenerating their go1.4.*.tar.gz files on GCS.

**Comment by bradfitz** [comment]
Notes on how I trimmed a bunch of stuff from the bootstrap.bash result:

```
rm -rf $(find . -name testdata)
rm -rf test
rm -rf api
rm bin/gen
rm bin/gofmt
cd pkg/tool/darwin_amd64 && rm addr2line api cgo cover doc fix nm objdump pack  pprof trace vet yacc 
rm -rf ./darwin_amd64/image
rm -rf ./darwin_amd64/database
```
