### ISSUE TITLE
build: gomote rmall os.RemoveAll latency?!

### ISSUE THREAD

**Issue by bradfitz** [golang/go#9798]
I don't understand what happened here with the buildlet and os.RemoveAll. These commands were all executed within seconds of each other, with no interaction of mine on the builder:

```
ante:build $ gomote rmall windows-amd64-gce
Error running rmall: 500 Internal Server Error; body: remove C:\workdir\pkg\tool: The directory is not empty.

ante:build $ gomote rmall windows-amd64-gce
Error running rmall: 500 Internal Server Error; body: remove C:\workdir\pkg: The directory is not empty.

ante:build $ gomote rmall windows-amd64-gce
Error running rmall: 500 Internal Server Error; body: remove C:\workdir: The directory is not empty.

ante:build $ gomote rmall windows-amd64-gce
ante:build $ gomote rmall windows-amd64-gce
ante:build $ 
```

All that handler was doing was running `os.RemoveAll`. Why doesn't it work on Windows?

/cc @adg @alexbrainman

**Comment by gmlewis** [comment]
I've been having problems with `os.RemoveAll` on Windows as well with Go 1.4.1.

**Comment by bradfitz** [comment]
Well, the buildlet was built with Go tip. But likely nothing's changed there.

What problems are you seeing?

**Comment by minux** [comment]
Is it possible that some tool is still running when you issued the first
rmall command?

On windows you cannot delete a program when it's currently running unless
using some tricks.

**Comment by gmlewis** [comment]
Here is the error I'm seeing on Windows:
`os.RemoveAll: remove D:\tmp\appengine\go_appengine\goroot\.git\objects\pack\pack-5d646641b961ee46717c7e6d2ae239a057f33ab0.idx: Access is denied.`
I tried running the cmd shell in Administrator mode, but get the same result.

**Comment by minux** [comment]
that's the readonly file problem, see #9606.

**Comment by bradfitz** [comment]
This bug is not the read-only file problem, because no git is involved at all. Let's move that discuss elsewhere.

> Is it possible that some tool is still running when you issued the first rmall command?

None that I can imagine.

**Comment by alexbrainman** [comment]
os.RemoveAll will refuse to delete if some process (including yours) has opened files inside directory you want to delete. Same for "current directory" for any process. I don't know the way to solve this, but to catch these processes in action. There are some system tools to monitor these events, but. Can I reproduce this somehow to debug it?

Alex

**Comment by bradfitz** [comment]
I can't reproduce. Maybe there was some process running in the background still.

Closing for now.
