### ISSUE TITLE
bootstrap: segmentation fault during build

### ISSUE THREAD

**Issue by Stefan-Code** [golang/go#9800]
I'm trying to build from source on this system:
<code>Linux Synology 3.2.40 #5022 SMP PREEMPT Wed Jan 7 14:19:42 CST 2015 i686 GNU /Linux synology_evansport_214play</code>
And for building I'm running:
<pre><code>
    ~/temp/go-go1.4/src # sh all.bash
    # Building C bootstrap tool.
    cmd/dist
    Segmentation fault (core dumped)
    ~/temp/go-go1.4/src #
</pre></code>
The same thing happens for make.bash. Any ideas what's happening?

**Comment by davecheney** [comment]
What processor does your synology use, you may need to export GOSSE=387 to
disable the use of sse2 instruction.

Dave

**Comment by minux** [comment]
I'd first run make.bash with bash -x and see which program is segfaulting
and then run the program under gdb if it's cmd/dist/dist.

**Comment by Stefan-Code** [comment]
The box is a DS214play so it's using an Intel Atom CE5335 i686. I tried exporting GOSSE=387 with no luck. The output of bash -x is:
<pre><code>
    root@Synology:/root/temp/go-go1.4/src# export GOSSE=387
    root@Synology:/root/temp/go-go1.4/src# bash -x all.bash
    + set -e
    + '[' '!' -f make.bash ']'
    + OLDPATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/opt/bin:/usr/syno/bin:/usr/local/sbin:/opt/share/go/bin:/root/go/bin:/usr/local/bin
    + . ./make.bash --no-banner
    ++ set -e
    ++ '[' '!' -f run.bash ']'
    ++ case "$(uname)" in
    +++ uname
    ++ ld --version
    ++ grep 'gold.* 2\.20'
    ++ for se_mount in /selinux /sys/fs/selinux
    ++ '[' -d /selinux -a -f /selinux/booleans/allow_execstack -a -x /usr/sbin/selinuxenabled ']'
    ++ for se_mount in /selinux /sys/fs/selinux
    ++ '[' -d /sys/fs/selinux -a -f /sys/fs/selinux/booleans/allow_execstack -a -x /usr/sbin/selinuxenabled ']'
    +++ uname -s
    ++ '[' Linux == GNU/kFreeBSD ']'
    ++ rm -f ./runtime/runtime_defs.go
    ++ echo '# Building C bootstrap tool.'
    # Building C bootstrap tool.
    ++ echo cmd/dist
    cmd/dist
    +++ cd ..
    +++ pwd
    ++ export GOROOT=/root/temp/go-go1.4
    ++ GOROOT=/root/temp/go-go1.4
    ++ GOROOT_FINAL=/root/temp/go-go1.4
    ++ DEFGOROOT='-DGOROOT_FINAL="/root/temp/go-go1.4"'
    ++ mflag=
    ++ case "$GOHOSTARCH" in
    +++ uname
    ++ '[' Linux == Darwin ']'
    +++ type -t gcc
    +++ type -t clang
    ++ '[' -z '' -a -z file -a -n '' ']'
    ++ gcc -O2 -Wall -Werror -o cmd/dist/dist -Icmd/dist '-DGOROOT_FINAL="/root/temp/go-go1.4"' cmd/dist/arm.c cmd/dist/buf.c cmd/dist/build.c cmd/dist/buildgc.c cmd/dist/buildgo.c cmd/dist/buildruntime.c cmd/dist/main.c cmd/dist/plan9.c cmd/dist/unix.c cmd/dist/windows.c
    +++ ./cmd/dist/dist env -p
    +++ echo FAIL=true
    ++ eval FAIL=true
    +++ FAIL=true
    ++ '[' true = true ']'
    ++ exit 1
    root@Synology:/root/temp/go-go1.4/src# 
</code></pre>

**Comment by minux** [comment]
Try running ./cmd/dist/dist env -p under gdb. e.g.

gdb --args ./cmd/dist/dist env -p

and then type run, and see which line segfaulted.

you might need to compile cmd/dist again manually to enable debugging
information.
gcc -O2 -Wall -Werror -ggdb -o cmd/dist/dist -Icmd/dist
'-DGOROOT_FINAL="/root/temp/go-go1.4"' cmd/dist/*.c

**Comment by minux** [comment]
That's weird. cmd/dist/dist in Go 1.4 shouldn't link to libpthread
at all.

what's the output of ```ldd cmd/dist/dist```?

**Comment by Stefan-Code** [comment]
So, running it under gdb like you suggested outputs:
<pre><code>
        root@Synology:/root/temp/go-go1.4/src# gdb --args ./cmd/dist/dist env -p
    dlopen failed on 'libthread_db.so.1' - libthread_db.so.1: cannot open shared object file: No such file or directory
    GDB will not be able to debug pthreads.

    GNU gdb 6.8
    Copyright (C) 2008 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
    and "show warranty" for details.
    This GDB was configured as "i686-linux-gnu"...
    (gdb) run
    Starting program: /root/temp/go-go1.4/src/cmd/dist/dist env -p

    Program received signal SIGSEGV, Segmentation fault.
    0x080e1643 in ?? ()
    (gdb)
</code></pre>
Unfortunately I don't have access to ldd because it's not installed on the Synology boxes and not in any package i can easily install so I'd have to build that one from source too...
Thanks for your help.

**Comment by minux** [comment]
Try compile the dist program with debugging symbols:
```gcc -O0 -Wall -Werror -ggdb -o cmd/dist/dist -Icmd/dist '-DGOROOT_FINAL="/root/temp/go-go1.4"' cmd/dist/*.c```

and then run gdb again.

Use bt to get the full stack trace.

**Comment by Stefan-Code** [comment]
Ok, now it says:
<pre><code>

    Starting program: /root/temp/go-go1.4/src/cmd/dist/dist env -p

    Program received signal SIGSEGV, Segmentation fault.
    0x080e0dd3 in ?? ()
    (gdb) bt
    #0  0x080e0dd3 in ?? ()
    #1  0x08053ce0 in strstr@@GLIBC_2.0 ()
    #2  0xb77c46b0 in ?? ()
    #3  0x00000001 in ?? ()
    #4  0x00000001 in ?? ()
    #5  0x00000000 in ?? ()
    (gdb)

</code></pre>

**Comment by rsc** [comment]
I'm sorry, but you must have a bad gcc installed. 

All this script does is (effectively) gcc *.c and run the resulting binary. In your case the resulting binary doesn't work. You should look into trying to reduce the test case and report it to your Linux distribution, or (less work) make sure all your compiler and library packages are up to date.
