### ISSUE TITLE
race: Windows findfunc: bad findfunctab entry

### ISSUE THREAD

**Issue by bradfitz** [golang/go#9804]
The `windows-amd64-race` builder is failing with:

http://build.golang.org/log/fe4b2df348305ca5e59e2ebba9294c8d5746dcf0
```
....
ok  	regexp	1.080s
ok  	regexp/syntax	7.827s
ok  	runtime	72.692s
?   	runtime/cgo	[no test files]
ok  	runtime/debug	0.329s
fatal error: findfunc: bad findfunctab entry

goroutine 29 [running]:
runtime.throw(0x70dd90, 0x1f)
	C:/workdir/go/src/runtime/panic.go:511 +0x98 fp=0xc0824d1a38 sp=0xc0824d1a20
runtime.findfunc(0x603f77, 0x4573d8)
	C:/workdir/go/src/runtime/symtab.go:162 +0xeb fp=0xc0824d1a58 sp=0xc0824d1a38
runtime.FuncForPC(0x603f77, 0x788068)
	C:/workdir/go/src/runtime/symtab.go:125 +0x2f fp=0xc0824d1a70 sp=0xc0824d1a58
runtime/pprof_test.func·005(0x1, 0xc08215e0b8, 0x2, 0xbed1)
	C:/workdir/go/src/runtime/pprof/pprof_test.go:147 +0xb4 fp=0xc0824d1b60 sp=0xc0824d1a70
runtime/pprof_test.parseProfile(0xc082049200, 0xc08215e000, 0x5f80, 0xbee8, 0xc0824d1ea0)
	C:/workdir/go/src/runtime/pprof/pprof_test.go:117 +0x928 fp=0xc0824d1cc0 sp=0xc0824d1b60
runtime/pprof_test.testCPUProfile(0xc082049200, 0x0, 0x0, 0x0, 0xc0824d1f58)
	C:/workdir/go/src/runtime/pprof/pprof_test.go:157 +0x3e5 fp=0xc0824d1f30 sp=0xc0824d1cc0
runtime/pprof_test.TestMathBigDivide(0xc082049200)
	C:/workdir/go/src/runtime/pprof/pprof_test.go:303 +0x80 fp=0xc0824d1f70 sp=0xc0824d1f30
testing.tRunner(0xc082049200, 0x11d6138)
	C:/workdir/go/src/testing/testing.go:448 +0x142 fp=0xc0824d1fd0 sp=0xc0824d1f70
runtime.goexit()
	C:/workdir/go/src/runtime/asm_amd64.s:2446 +0x1 fp=0xc0824d1fd8 sp=0xc0824d1fd0
created by testing.RunTests
	C:/workdir/go/src/testing/testing.go:556 +0xc85

goroutine 1 [chan receive]:
testing.RunTests(0x758678, 0x11d60c0, 0xc, 0xc, 0x1)
	C:/workdir/go/src/testing/testing.go:557 +0xce1
testing.(*M).Run(0xc08200c280, 0x11fb7a0)
	C:/workdir/go/src/testing/testing.go:486 +0xe8
main.main()
	runtime/pprof/_test/_testmain.go:76 +0x294

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	C:/workdir/go/src/runtime/asm_amd64.s:2446 +0x1
FAIL	runtime/pprof	14.726s
ok  	runtime/race	14.317s
ok  	sort	1.285s
ok  	strconv	4.350s
ok  	strings	2.263s
...
```

/cc @dvyukov @minux @randall77 @alexbrainman

**Comment by alexbrainman** [comment]
I did "git bisect". That is what I find:

63116de558b472c437df186d6bf87e163f674ea2 is the first bad commit
commit 63116de558b472c437df186d6bf87e163f674ea2
Author: Keith Randall <khr@golang.org>
Date:   Sat Dec 27 19:26:40 2014 -0800

    runtime: faster version of findfunc

    Use a lookup table to find the function which contains a pc.  It is
    faster than the old binary search.  findfunc is used primarily for
    stack copying and garbage collection.

    benchmark              old ns/op     new ns/op     delta
    BenchmarkStackCopy     294746596     255400980     -13.35%

    (findfunc is one of several tasks done by stack copy, the findfunc
    time itself is about 2.5x faster.)

    The lookup table is built at link time.  The table grows the binary
    size by about 0.5% of the text segment.

    We impose a lower limit of 16 bytes on any function, which should not
    have much of an impact.  (The real constraint required is <=256
    functions in every 4096 bytes, but 16 bytes/function is easier to
    implement.)

    Change-Id: Ic315b7a2c83e1f7203cd2a50e5d21a822e18fdca
    Reviewed-on: https://go-review.googlesource.com/2097
    Reviewed-by: Russ Cox <rsc@golang.org>

:040000 040000 6833a2db04abf92d8ec1f29ae075c465223ee2a8 05bb58122975d3bc2d941bc7a0f0d7dadd971920 M      src

**Comment by bradfitz** [comment]
Assigned to Keith, then.

Keith, you can now use gomote to have a remote ephemeral Windows instances available for interactive development. The gomote tool is still new and not fully polished, but it's getting there. Let me know if you'd like to use it to debug/test this, without having to use an actual Windows VM or machine.

**Comment by randall77** [comment]
Yes, please, can you hook me up?  Getting an AWS Windows instance to the
point where I can do work is really painful.

**Comment by bradfitz** [comment]
I emailed your google address with instructions. Consider yourself a gomote beta tester. Please complain to me and @adg with any feedback.
