### ISSUE TITLE
encoding/json string option: decoding struct slices: if field is null in JSON, value gets set to previous struct's field value

### ISSUE THREAD

**Issue by tp** [golang/go#9810]
I have seen this with Go 1.2.1 (bundled with App Engine), and could not find a bug report or fix.

This is not an issue with 1.4.1, so I think it has been silently/inadvertently fixed.

```
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
)

type Container struct {
	Xs []X `json:"xs"`
}

type X struct {
	V int64 `json:"value,string"`
}

func main() {

	content := []byte(`{"xs":[{"value":"5838406743490560"},{"value":null}]}`)
	r := bytes.NewReader(content)

	c := &Container{}
	err := json.NewDecoder(r).Decode(c)
	if err != nil {
		fmt.Println(err.Error())
		return
	}

	fmt.Printf("%d %d", c.Xs[0].V, c.Xs[1].V)
}
```

http://play.golang.org/p/jE3tFV8dZN

Go 1.2.1 output: "5838406743490560 5838406743490560"
Go 1.4.1 output: "5838406743490560 0"

**Comment by minux** [comment]
Verified fixed on tip. We don't maintain releases other than
the latest one.
