### ISSUE TITLE
prevent variable aliasing in *any* way

### ISSUE THREAD

**Issue by kodabb** [golang/go#9818]
the following code

```go
func OpenLogFile(lo LogOptions) (io.WriteCloser, error) {
    var logw io.WriteCloser
    switch lo.LogPath {
    case "stderr":
        logw = os.Stderr
    default:
        logw, err := openLogFileInternal(lo)
        if err != nil {
            return logw, err
        }
    }
    log.SetOutput(logw)
    return logw, nil
}
```
will alias the `logw` variable: since `logw` is declared outside, and in the `default` switch case another `logw` is created with `:=`, every default case will return a `nil`. Fun ensues.

Go should either prevent this behaviour with a panic/error/warning or should note that the variable is initialized in an external block and properly initialize it rather than creating a new one.

**Comment by adg** [comment]
Can't change this now. https://golang.org/doc/go1compat

We will certainly revisit variable declarations and scoping rules in Go 2.

**Comment by minux** [comment]
Declare err at the outer scope and use `=` instead of `:=`.

This proposal is an incompatible language change, so
it's not going to happen, at least not for Go 1.

**Comment by dwbuiten** [comment]
> Declare err at the outer scope and use = instead of :=.

The problem is that it's very easy to typo `=` and `:=`.

> This proposal is an incompatible language change, so it's not going to happen, at least not for Go 1.

Yep!

**Comment by kodabb** [comment]
It's fine if this waits until Go 2, just don't forget about it when it is time :)

**Comment by minux** [comment]
Even for Go 2, I think a better way is to have golint or govet detect such
cases rather than make a language change.

**Comment by kodabb** [comment]
sure, as long as it automated and the developer is notified of this in some way
