### ISSUE TITLE
cmd/go: implement go generate -run

### ISSUE THREAD

**Issue by robpike** [golang/go#9821]
The flag is documented and even declared in the code, but is unimplemented. For 1.5 we should decide what it should do and implement that. For 1.4.2 we should include https://go-review.googlesource.com/4291 which at least documents that it doesn't work.

**Comment by robpike** [comment]
When this lands in 1.4.2, update the milestone to 1.5 but do not close the issue.

**Comment by rsc** [comment]
Fixed by 2807572
