### ISSUE TITLE
android/arm: build broken

### ISSUE THREAD

**Issue by hyangah** [golang/go#9829]
it's broken after d738c6b0cad4, and tests fail with segfault.

E/Go      (30115): fatal error: recursive call during initialization - linker skew
E/Go      (30115): goroutine 1 [running, locked to thread]:
E/Go      (30115): runtime.throw(0x190178, 0x32)
E/Go      (30115):      /usr/local/go/src/runtime/panic.go:511 +0x8c fp=0x10433f40 sp=0x10433f34
E/Go      (30115): runtime.throwinit()
E/Go      (30115):      /usr/local/go/src/runtime/panic.go:50 +0x34 fp=0x10433f4c sp=0x10433f40
E/Go      (30115): bufio.init()
E/Go      (30115):      /usr/local/go/src/bufio/scan.go:359 +0x48 fp=0x10433f68 sp=0x10433f4c
E/Go      (30115): runtime/pprof.init()
E/Go      (30115):      /usr/local/go/src/runtime/pprof/pprof.go:700 +0x78 fp=0x10433f74 sp=0x10433f68
E/Go      (30115): testing.init()
E/Go      (30115):      /usr/local/go/src/testing/testing.go:726 +0x60 fp=0x10433f94 sp=0x10433f74
E/Go      (30115): crypto/dsa.init()
E/Go      (30115):      /tmp/gobuilder/android-arm-crawshaw-263405ea4ac2/go/src/crypto/dsa/dsa_test.go:85 +0x5c fp=0x10433fb0 sp=0x10433f94
E/Go      (30115): main.init()
E/Go      (30115):      crypto/dsa/_test/_testmain.go:56 +0x5c fp=0x10433fbc sp=0x10433fb0
E/Go      (30115): runtime.main()
E/Go      (30115):      /usr/local/go/src/runtime/proc.go:81 +0x1dc fp=0x10433fe4 sp=0x10433fbc
E/Go      (30115): runtime.goexit()
E/Go      (30115):      /usr/local/go/src/runtime/asm_arm.s:1347 +0x4 fp=0x10433fe4 sp=0x10433fe4
E/Go      (30115): goroutine 2 [runnable]:
E/Go      (30115): runtime.forcegchelper()
E/Go      (30115):      /usr/local/go/src/runtime/proc.go:111
E/Go      (30115): runtime.goexit()
E/Go      (30115):      /usr/local/go/src/runtime/asm_arm.s:1347 +0x4
E/Go      (30115): goroutine 3 [runnable]:
E/Go      (30115): runtime.runfinq()
E/Go      (30115):      /usr/local/go/src/runtime/mfinal.go:115
E/Go      (30115): runtime.goexit()
E/Go      (30115):      /usr/local/go/src/runtime/asm_arm.s:1347 +0x4

@minux @crawshaw

**Comment by minux** [comment]
It's my fault, and I will fix it ASAP. Thanks for the stack trace!
