### ISSUE TITLE
runtime: add timestamp to gctrace=1 output

### ISSUE THREAD

**Issue by schmichael** [golang/go#9830]
A timestamp for gctrace=1's output would be very useful for external tooling wishing to visualize or aggregate gc logs.

Relevant log line: https://github.com/golang/go/blob/master/src/runtime/mgc.go#L1668-L1676

Seems like using either [t0](https://github.com/golang/go/blob/master/src/runtime/mgc.go#L1542) or [t4](https://github.com/golang/go/blob/master/src/runtime/mgc.go#L1644) would be the most useful. This way all of the phase timings could be easily translated to absolute times by an external tool.

Original post:  https://groups.google.com/forum/#!topic/golang-nuts/CG4BrJ0ZD6Q

**Comment by rsc** [comment]
@aclements did this as part of redoing the entire line.
