### ISSUE TITLE
system TZ is UTC, but time.Local != time.UTC

### ISSUE THREAD

**Issue by pbnjay** [golang/go#9832]
This was a very unexpected bug, considering all output and other logging statements matched up.

$ cat tt.go
                   
    package main
    
    import (
        "fmt"
        "time"
    )
    
    func main() {
        t1 := time.Now()
        t2 := t1.UTC()
        fmt.Println(t1, " == ", t2, " => ", t1==t2)
    }
    
$ go run tt.go

    2015-02-10 19:51:15.366942319 +0000 UTC  ==  2015-02-10 19:51:15.366942319 +0000 UTC  =>  false

go version devel +2d02ff2 Sat Dec 13 10:18:27 2014 +0000 linux/amd64

**Comment by DisposaBlackSwan** [comment]
It wasn't clear whether or not you're aware of http://golang.org/pkg/time/#Time.Equal. I'm not sure `t == t` is ever what one wants.

**Comment by ianlancetaylor** [comment]
See the note about == at http://golang.org/pkg/time/#Time .

**Comment by pbnjay** [comment]
TBH I was using time.Time as map keys when I stumbled on this, so I couldn't use Time.Equal anyways.

The code above was just a minimal test case, since even when trying to debug this the output matched exactly. I had to dig all the way into zoneinfo_unix.go to see that they weren't the same value.

**Comment by pbnjay** [comment]
@ianlancetaylor I've seen the note, but it's not clear that Local = "UTC" and UTC = "UTC" are different things. Obviously bugs/docs are up to y'all, at least now if someone else has the issue they'll be able to google this particular edge case. Cheers

**Comment by nightlyone** [comment]
@pbnjay please note, that you actually CAN use times as map keys, if you call .UTC() before storing them, since t1.UTC() == t2.UTC() => true, iff t1.Equal(t2) => true

**Comment by pbnjay** [comment]
yeah that's what I'm doing now.... but again, docs make it unclear that I
have to force .UTC() even when it's already in UTC.

Jeremy
