### ISSUE TITLE
x/build/dashboard: don't show commit hash in the first column

### ISSUE THREAD

**Issue by dvyukov** [golang/go#9839]
@adg @bradfitz 

For discussion, because this is based only my usage patterns.

Hash is useful to go to commit page. However, I first need to look at the very right to find the commit, and then visually move to the very left to click on the commit. With the current number of builders this movement is very painful.

Also, the exact characters of the commit hash does not seem to be super important to occupy the first column.

So I propose to linkify commit message to link to the commit page.

If one needs to copy commit hash, then it is possible to do on the commit page. If one strongly wants to be able to copy commit hash right on the dashboard, then I still propose to move it to right, e.g.:
runtime: cache workbufs on Ms and add consistency checks (a15818fed303)
Because one needs to see commit description to pick the right hash.

**Comment by bradfitz** [comment]
SGTM

Or linkify the date instead, so it has bounded width and isn't a sea of blue underlines on the right side.

**Comment by dvyukov** [comment]
@bradfitz works for me

**Comment by adg** [comment]
Either approach is fine IMO.

**Comment by bradfitz** [comment]
This isn't urgent and nobody feels strongly, so closing this for now. If somebody wants to hack up something prettier and mail it out we'll take a look.
