### ISSUE TITLE
database/sql: Register is not thread safe

### ISSUE THREAD

**Issue by fabiokung** [golang/go#9847]
`sql.Register` can't currently be called from multiple goroutines:

https://github.com/golang/go/blob/f58a5cb9e2/src/database/sql/sql.go#L28-L39

It should do something along the lines of `gob.RegisterName` and synchronize access on the global `drivers` registry:

https://github.com/golang/go/blob/f58a5cb9e2d03ff1baa37cce63766cdb8cba7221/src/encoding/gob/type.go#L823-L824

**Comment by bradfitz** [comment]
Or we just document it.

**Comment by fabiokung** [comment]
> Or we just document it.

sgtm

**Comment by bradfitz** [comment]
Actually it was easier to just add a mutex than document it.
