### ISSUE TITLE
testing: display ops/s

### ISSUE THREAD

**Issue by tj** [golang/go#9850]
Most people obviously feel differently :D but I think it would be nice, even if it's a flag. Almost everything we evaluate is tied back to metrics that are already reported as ops/s in various tools.

**Comment by adg** [comment]
Are you referring to the benchmarks in $GOROOT/test/bench, the testing package's benchmarking feature, or something else?

**Comment by minux** [comment]
I think the OP means benchmarks using the testing package.

**Comment by tj** [comment]
derp, there we go haha. Yeah just the test -bench output

**Comment by nightlyone** [comment]
@tj What about writing a simple wrapper for that and share it in some repository? 

See https://github.com/golang/tools/blob/master/benchmark/parse/parse.go on how to parse benchmark output. I guess this parser will be maintained for quite some time, since https://github.com/golang/tools/blob/master/cmd/benchcmp relies on it.

**Comment by tj** [comment]
@nightlyone hmm I'm not opposed to it, but with the general out-of-the-box experience Go provides it seems a little odd to me. 

If we went that route maybe a json output flag makes more sense, so it's not such an ad-hoc format to parse? That would be handy for CI too

**Comment by dominikh** [comment]
JSON output might be useful, but in the meantime one can use `golang.org/x/tools/benchmark/parse` to parse the output and transform it in whatever ways one desires.

**Comment by adg** [comment]
I wouldn't be opposed to a flag to switch the output. cc @robpike

**Comment by minux** [comment]
Adding -json for go test and the testing package is #2981.

**Comment by tj** [comment]
Nice, interfaces would definitely be better in this case, wrapping the exec is pretty extreme for one metric. I'll close this and see if I can get time to get a patch for that other issue
