### ISSUE TITLE
x/mobile: gomobile shouldn't suggest sudoing

### ISSUE THREAD

**Issue by rakyll** [golang/go#9854]
If the GOROOT directory is not writable, a sudo won't help because the user's GOPATH/bin and Go tool won't be in the root's PATH. We may suggest changing ownership/permissions temporarily.

**Comment by hyangah** [comment]
-E doesn't seem to preserve PATH env. 

sudo -E PATH=$PATH gomobile init

But more generally, if users has no permission for sudo, should the tool suggest manage their own goroot?

**Comment by rakyll** [comment]
General rule is not to require sudo if sudo can be omitted. I don't see a reason we should run gomobile init as the root user.

**Comment by crawshaw** [comment]
If you install go with apt-get, your GOROOT is only writable to root. I don't want users to install another copy of Go, as it will lead to confusion.

**Comment by adg** [comment]
We should probably check that bootstrapping works with the go packages
provided by popular distros before going down this road.
The distros like to strip stuff out and break things. :-(

**Comment by hyangah** [comment]
what popular distros should we check?

btw I checked the instruction ins https://wiki.ubuntu.com/Go
and it gave me go1.2.1.

2015-02-12 18:44 GMT-05:00 Andrew Gerrand <notifications@github.com>:

> We should probably check that bootstrapping works with the go packages
> provided by popular distros before going down this road.
> The distros like to strip stuff out and break things. :-(
>
> On 13 February 2015 at 08:16, David Crawshaw <notifications@github.com>
> wrote:
>
> > If you install go with apt-get, your GOROOT is only writable to root. I
> > don't want users to install another copy of Go, as it will lead to
> > confusion.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/golang/go/issues/9854#issuecomment-74154204>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/golang/go/issues/9854#issuecomment-74178016>.
>



-- 
__

**Comment by rakyll** [comment]
> We should probably check that bootstrapping works with the go packages

Or we should motivate them to fix their distributions.

**Comment by nightlyone** [comment]
I think it would be great to avoid having add-on repositories write to GOROOT on Linux. Just `vet` needs to be there for historic reasons, others could have been in the GOPATH instead.
Godoc could be in GOPATH, too.

If there is an actual requirement to add more things to GOROOT/pkg/tool, then perhaps adding the convention of GOPATH/pkg/tool (for each GOPATH element of course) starts looking attractive...

**Comment by adg** [comment]
I would suggest Ubuntu, Debian, and possibly CentOS/Redhat as candidates.
The latter will probably be a real PITA.

**Comment by rakyll** [comment]
@nightlyone,

We write to the GOROOT to bootstrap and make go tools targeting arm7 Android. Additional stuff (Android NDK tooling) is being written to GOPATH.

**Comment by crawshaw** [comment]
I think we are in better shape now. The gomobile tool only suggests running an mv command as the super user if it is necessary. There is still the question of do distributions ship with functional GOROOTs or not, but the tool now requires Go 1.5, so it will not be relevant for a while.

**Comment by EtienneBruines** [comment]
Using `version devel +aff7a57 Tue Jun 9 08:21:21 2015` it does indeed suggest a mv command, but that doesn't help:

* the init process is stopped and does not resume;
    * it's not finished either - running `gomobile install` still says `android toolchain partially installed`
* the same message/suggestion is given when the init is restarted manually - thus not advancing.

**Comment by tonyconstantinides** [comment]
I still getting gomobile: toolchain partially installed , run gomobile init
even after I have run gomobile. It thinks it needs to build for ios even though I only interested in Android while building on El Capitan on my Macbook pro. The Android setup occurred but it now thinks it needs to setup IOS as well for some reason.
This is happening on Go Beta 1.5 so looks like it was never fixed

**Comment by crawshaw** [comment]
The gomobile tool no longer suggests sudoing as of https://golang.org/cl/11711. The simplified logic pushed all decisions about how to handle an unwritable GOROOT onto the go tool.

@tonyconstantinides I believe your issue is unrelated to this one. Please try using go get -u to make sure you have the latest gomobile tool, rm -rf on $GOPATH/pkg/gomobile, and then another gomobile init. If you see the same error message, please file a new issue along with the revision of the x/mobile repository you are using.
