### ISSUE TITLE
image/gif: Can’t decode gifs that the browser handles

### ISSUE THREAD

**Issue by tessr** [golang/go#9856]
There are images which browsers can render but which image/gif chokes on. 

The following runs successfully for most gifs: 

```go
import (
	"fmt"
	"image/gif"
	"os"
)

const example = "sample.gif"

func main() {
	fmt.Println("attempting to read gif")

	file, err := os.Open(example)
	if err != nil {
		fmt.Println("Can't open this file:", err)
		return
	}

	img, err := gif.Decode(file)
	if err != nil {
		fmt.Println("Can't decode this as a gif:", err)
		return
	}

	_ = img.Bounds()

	fmt.Println("gif decoded")
}

```

But when trying to run it on a particular gif (below), this happens: 

```
$ go run main.go
attempting to read gif
Can't decode this as a gif: gif: not enough image data
```

Here’s the offending gif: 
![sample](https://cloud.githubusercontent.com/assets/773524/6175591/fcfc2320-b2ac-11e4-8e59-a959092ec361.gif)

Meanwhile, when I run this on another (similar) gif, I get the following: 

```
$ go run main.go
attempting to read gif
Can't decode this as a gif: gif: too much image data
```
![test](https://cloud.githubusercontent.com/assets/773524/6175595/02420458-b2ad-11e4-9a5c-aedcf04b0d7d.gif)

It seems like something might be wrong with these gifs, but browsers are still able to read them, so it seems that image/gif should be able to as well.

Tested with both 1.3 and 1.4.

**Comment by bradfitz** [comment]
@nigeltao, all yours. As a bonus, you get to learn about the nuclear force interaction while you fix it.

**Comment by sbinet** [comment]
also known as the `strong` force. (padawan-puns in the CL allowed?)
