### ISSUE TITLE
net/http/cgi: should not put port into REMOTE_ADDR and REMOTE_HOST

### ISSUE THREAD

**Issue by asergeyev** [golang/go#9861]
In all recent versions (1.4.x) cgi library puts http.Request RemoteAddr into both REMOTE_ADDR and REMOTE_HOST env vars. That is a string that has "IP:port" combination.

CGI 1.1 standard asks to put only IP address to REMOTE_ADDR and omit port...  I suggest to make things work this way too. 

Apache puts port into REMOTE_PORT variable (which is not in spec and not that important to have). I'd vote for ignoring port alltogether.

**Comment by mattn** [comment]
Related issue https://github.com/golang/go/issues/8351 (Closed)

**Comment by asergeyev** [comment]
That ticket discusses CGI child behavior and re-creation of the http.Request.RemoteAddr out of ENV variables that Apache or other server has set. Sure, when it was set by Go cgi-enabled server, things would go even worse, since REMOTE_ADDR already has "IP:port" it would become "IP:port:0" due to missing REMOTE_PORT var.

Here is where error goes in testing of CGI module:

    func newRequest(httpreq string) *http.Request {
    	buf := bufio.NewReader(strings.NewReader(httpreq))
    	req, err := http.ReadRequest(buf)
    	if err != nil {
    		panic("cgi: bogus http request in test: " + httpreq)
    	}
    	req.RemoteAddr = "1.2.3.4"
    	return req
    }

Test sets RemoteAddr to static 1.2.3.4 value while http.Request documentation mentions that it's IP:port string... 

If anyone would comment why that is string and not carried out net.Conn (*net.TCPConn I believe), I would gladly hear it and educate myself :) Fixing this IMO is out of scope of the problem, REMOTE_ADDR might be corrected in CGI and testing mishap that I described above is a small correction too.

**Comment by asergeyev** [comment]
Proposed change:
https://go-review.googlesource.com/4892

**Comment by mattn** [comment]
seems not pushed your changes. Could you please try following.

```
$ git add /path/to/your/changed/file.go
$ git change
$ git mail
```

**Comment by asergeyev** [comment]
Thanks, @mattn, I think I did some odd things in that one and now finally understood that changes must be staged and not committed. Submitted all in clean new codereview, and also fixed IPv6 error I had in original one there.

https://go-review.googlesource.com/#/c/4933/1

**Comment by asergeyev** [comment]
@bradfitz any chance you can take a look?
