### ISSUE TITLE
net/http/httputil: ReverseProxy should use StatusBadGateway if backend can't be connected

### ISSUE THREAD

**Issue by porjo** [golang/go#9864]
When using `net/http/httputil` ReverseProxy where the upstream server is, for example, refusing connections the HTTP status code returned is `StatusInternalServerError`. It would be more appropriate (and helpful to the client) to return `StatusBadGateway`.

Looking at the underlying code for http.Transport, it looks like there is no way to differentiate between the two classes of error at the moment.

**Comment by bradfitz** [comment]
Sent https://go-review.googlesource.com/21363
