### ISSUE TITLE
cgo is unable to link object files that do not have a symbol section

### ISSUE THREAD

**Issue by mildred** [golang/go#9867]
Generally cgo is used to build C code that links to external libraries. It may happen that some C code do not link to external libraries. In which case, the right think is to specify `-nostdlib` in the LDFLAGS.

This implies that the _cgo_.o ELF object file generated by gcc for cgo will not contain a symbol section because there is no unresolved external symbols. This is great because it means we can still generate a go executable that is statically linked and easily deployable.

Unfortunately, cgo will mistakenly treat the absence of a symbol section in the ELF object file as a read error, and will abort the build. I discovered that trying to build such a library with no external dependencies, [see my e-mail on golang-nuts](https://groups.google.com/forum/#!topic/golang-nuts/_qQH9rnM_zQ).

The call stack that lead to this error looks like:

- [cgo/out.go:204](https://github.com/golang/go/blob/3819907a5565c53457b826912a10b18eda708f38/src/cmd/cgo/out.go#L204)
- [debug/elf/file.go:669](https://github.com/golang/debug/blob/512354eaded67146a256474f5f486c37fd6e5263/elf/file.go#L669)
- [debug/elf/file.go:397](https://github.com/golang/debug/blob/512354eaded67146a256474f5f486c37fd6e5263/elf/file.go#L397)
- [debug/elf/file.go:455](https://github.com/golang/debug/blob/512354eaded67146a256474f5f486c37fd6e5263/elf/file.go#L455)

the `debug/elf` package treats the absence of a `.dynsym` section as an error in the function `ImportedSymbols()`, and cgo forwards the error.

Fixing this issue would be relatively simple. And it is also relatively important to have this because Go 1.4 removes the ability to include .c files in modules directly without going through cgo. That was how we could include standalone code that didn't require any external library before.

**Comment by minux** [comment]
-nostdlib doesn't make sense for cgo because cgo definitely needs libgcc,
libc and libpthread, even though your code might not use them directly.

**Comment by minux** [comment]
As explained on golang-nuts, linking external C code without also
linking in libc/libpthread is not going to work. Cgo requires them to
work.
