### ISSUE TITLE
net/http: undocumented ServeFile index.html redirect behavior

### ISSUE THREAD

**Issue by laszlothewiz** [golang/go#9876]
After an hour of head scratching and cursing and found that there's a strange way how ServeFile handles any path's that end with `index.html`:
- Instead of serving the file directly it generates a 301 redirect response to the nearest folder

Example:

http.ServeFile(w,r,"/public/blog/index.html") 
this redirects to `/public/blog/` 

This is not mentioned in the documentation and could cause undesirable behavior.

I tried to add the note about it to the documentation but got rejected because apparently Go doesn't use Github's pull request system. So I don't know how to get this into the documentation so that others won't get tripped over it.

I would actually propose that "feature" to be removed because it's based on an arbitrary of considering the trailing slash ("/") to be the equivalent of a reference to "index.html".

**Comment by bradfitz** [comment]
Docs to contribute a patch for review are at: https://golang.org/doc/contribute.html

We should just document it so we're not changing behavior. IIRC, @rsc likes (and implemented) the current behavior. I don't have much preference either way, except for I prefer things not to change. Documenting it is fine.

**Comment by laszlothewiz** [comment]
Thank you! 

I would like to update the docs but the contribution process is *very* complex! I'm totally confused after looking at it.

Is there a simple way to submit a change for review?

**Comment by adg** [comment]
That's the process. The document looks a lot more complicated than it is, because we made the instructions very thorough. Try following it through. It should take you around 10 minutes, or less.
