### ISSUE TITLE
runtime: Reenable "pointer-to-heap-doesn't-point-to-object" check.

### ISSUE THREAD

**Issue by randall77** [golang/go#9880]
We used to have a check for pointers that point into the heap but don't point to an object.  This check is useful for debugging live variable info, global ptr maps, etc.  It is currently turned off.  We should re-enable it for 1.5.  It is currently broken at least because of holes in 32-bit heaps #9872 .  There are probably other reasons as well.

The check is currently disabled in runtime/mbitmap.go:heapBitsForObject, line 181.

**Comment by aclements** [comment]
Note that this test is currently broken on both 32- and 64-bit because of issue #11267.

/cc @rsc @RLH
