### ISSUE TITLE
x/tools/imports: packages with non-standard names deleted unless imported with explicit name

### ISSUE THREAD

**Issue by taruti** [golang/go#9882]
Go imports deletes the termbox import in the following code:

```
package main

import "fmt"
import "github.com/nsf/termbox-go"

func main() {
    fmt.Println(termbox.Size())
}
```

A named import however works:

```
import termbox "github.com/nsf/termbox-go"
```

works fine.

If such package naming should be banned (could be a good idea) go vet could warn about them.

**Comment by minux** [comment]
If you have installed termbox-go package in your GOPATH, then goimports
should
be able to handle this correctly.

If that package is not installed, how could goimports know its real package
name?

**Comment by taruti** [comment]
Thus a workflow like:
1) git checkout a repo
2) use editor uses goimports to edit a source file (e.g. go-mode + hook)
3) save a source file
4) the imported package with non-standard name is not in $GOPATH and thus imports deletes the reference to it
5) the source code is broken

Should go-imports delete imports for which the corresponding package is not fetched and thus the package name is not known?

**Comment by minux** [comment]
I think that workflow is not right. Are you sure you want to edit a source
file
without also running its tests?

And if you use go get to fetch a package, even if you don't go install
anything,
goimports will do the right thing.

**Comment by ALTree** [comment]
This is a dup of #21143 and the reason `goimports` deletes the import is that `goimports` does not work well with imports containing `-` in a repository. The usecase is not supported and the fix is to use a named import.
