### ISSUE TITLE
runtime: an application using DLL crashes on windows

### ISSUE THREAD

**Issue by trygo** [golang/go#9885]
windows platform ,syscall dll, After a period of time,  the following error occurred:

Go version of this problem: 1.3.3, 1.4.1,   
Go version does not have this problem:1.1, 1.2.2 

-------------------------------------------------------------------------------------------------------
1.
unexpected fault address 0x12000000
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0x12000000 pc=0x4519ea]

goroutine 1 [running, locked to thread]:
runtime.gothrow(0x636f78, 0x5)
	c:/go/src/runtime/panic.go:503 +0x67 fp=0x124c7728 sp=0x124c771c
runtime.sigpanic()
	c:/go/src/runtime/os_windows.go:45 +0xdc fp=0x124c7738 sp=0x124c7728
runtime.mallocgc(0x10, 0x60ea40, 0x1, 0x0)
	c:/go/src/runtime/malloc.go:183 +0x6da fp=0x124c7790 sp=0x124c7738
runtime.newobject(0x60ea40, 0x5652ac)
	c:/go/src/runtime/malloc.go:353 +0x48 fp=0x124c77a4 sp=0x124c7790

OR: 2.  
fatal error: unexpected signal during runtime execution
[signal 0xc0000005 code=0x1 addr=0x92b99fff pc=0x461957]

runtime stack:
runtime.MSpan_Sweep(0x1752c0, 0x0, 0x3d)
	c:/go/src/runtime/mgc0.c:960 +0x107

goroutine 3 [running]:
runtime.switchtoM()
	c:/go/src/runtime/asm_386.s:208 fp=0x12a6cfd4 sp=0x12a6cfd0
runtime.gosweepone(0x0)
	c:/go/src/runtime/mgc0.c:1165 +0x18 fp=0x12a6cfe0 sp=0x12a6cfd4
runtime.bgsweep()
	c:/go/src/runtime/mgc0.go:85 +0x2d fp=0x12a6cff0 sp=0x12a6cfe0
runtime.goexit()
	c:/go/src/runtime/asm_386.s:2287 +0x1 fp=0x12a6cff4 sp=0x12a6cff0
created by gc
	c:/go/src/runtime/mgc0.c:1383

**Comment by minux** [comment]
Could you please show a minimal standalone test case for this issue?

**Comment by jfrazelle** [comment]
we might also be hitting this on the docker windows client we will try to find a minimal reproducing case

**Comment by rsc** [comment]
If you can send a reproduction case then we can try to fix for Go 1.5.

**Comment by jfrazelle** [comment]
Hi,

Sorry for the noise, we ended up hopefully fixing with some buffer
changes. What we were seeing was very hard to reproduce
programatically. Thanks.

On Thu, Apr 9, 2015 at 9:59 PM, Russ Cox <notifications@github.com> wrote:
> If you can send a reproduction case then we can try to fix for Go 1.5.
>
> —
> Reply to this email directly or view it on GitHub.



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu

**Comment by jfrazelle** [comment]
I don't know if this should be closed necessarily, but as a person who also
closes issues on an open sources project and has seen people freak out, I
will just say we will let you know _if_ we reproduce again in an easy way
to debug. Otherwise, seems fine to close it as it's hard to reproduce and
therefore hard to fix :)

On Friday, April 10, 2015, Ian Lance Taylor <notifications@github.com>
wrote:

> Closed #9885 <https://github.com/golang/go/issues/9885>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/golang/go/issues/9885#event-278580068>.
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>
