### ISSUE TITLE
website: add /s/build-coordinator link for the Go build coordinator? 

### ISSUE THREAD

**Issue by minux** [golang/go#9886]
I want to add a link to the build coordinator to the Hacking Gopher Chrome extension.
But I don't know if the current IP address is stable or not.

Is there any other way to discover the IP address for the build coordinator?

/cc @bradfitz

**Comment by minux** [comment]
according to https://go-review.googlesource.com/#/c/5240/1/cmd/coordinator/buildongce/create.go,
it seems that IP is fixed. I will go ahead to use that in the extension.

**Comment by bradfitz** [comment]
I'm creating a DNS name for it now.

**Comment by nightlyone** [comment]
Just for the record: Is it farmer.golang.org ?

**Comment by minux** [comment]
Yes.
