### ISSUE TITLE
image: Rectangle.Union() doesn't handle empty rectangles correctly

### ISSUE THREAD

**Issue by robzan8** [golang/go#9895]
The function for calculating the union of two rectangles returns wrong values when one or both input rectangles are empty. The code in image/geom.go is currently:
```go
func (r Rectangle) Union(s Rectangle) Rectangle {
	if r.Min.X > s.Min.X {
		r.Min.X = s.Min.X
	}
	if r.Min.Y > s.Min.Y {
		r.Min.Y = s.Min.Y
	}
	if r.Max.X < s.Max.X {
		r.Max.X = s.Max.X
	}
	if r.Max.Y < s.Max.Y {
		r.Max.Y = s.Max.Y
	}
	return r
}
```
To be correct a couple of lines should be added at the beginning of the function:
```go
	if r.Empty() {
		return s
	}
	if s.Empty() {
		return r
	}
```
Is this a bug, or is the case ignored for performance reasons? If it's the latter, I think a warning should be added in the function documentation.

**Comment by jnjackins** [comment]
I think it's correct as is. An empty rectangle is still a rectangle, and the function documentation says the resulting rectangle will contain both. With your addition, that's not necessarily true.

**Comment by robzan8** [comment]
Yeah, I was thinking about it, I'm not sure either. But, for an empty rectangle the position does not matter, it contains no pixels ( as explained here http://blog.golang.org/go-image-package ). If we define the union of two rectangles as the minimum rectangle that contains all the pixels of both, then the union of two empty rectangles should be empty, mathematically speaking it makes more sense. Also practically speaking maybe, if you imagine that you want to calculate the union of a slice of rectangles, you should be able to initialize an empty rectangle as accumulator and then simply iterate over the slice.

**Comment by nigeltao** [comment]
I think it is indeed a bug. Please see https://go-review.googlesource.com/#/c/4990/ for a fix (and test).

**Comment by robzan8** [comment]
Looks good to me.

**Comment by robzan8** [comment]
Do you think that Rectangle.Eq() should be true for two empty but "different" rectangles or am I pushing it too far? :)

**Comment by nigeltao** [comment]
Changing Rectangle.Eq is https://go-review.googlesource.com/5006

**Comment by robzan8** [comment]
Great.
