### ISSUE TITLE
cmd/gc: errors are swallowed if liblink calls sysfatal

### ISSUE THREAD

**Issue by minux** [golang/go#9898]
cmd/gc buffers errors so that it can sort on the line number, however,
if liblink calls sysfatal to abort the whole process, those buffered errors
won't be shown.

**Comment by alexbrainman** [comment]
@minux you provide very few details. But perhaps what you see is similar to what we've seen in issue #9722.

Alex

**Comment by minux** [comment]
I encountered this bug while working on the arm64 port, so I don't have
a simple way to reproduce using existing toolchain yet (it requires a
buggy liblink or a buggy cmd/gc)

But yes, it does seem like #9722 is related to this one.

Basically, cmd/gc detects some errors, but before it can print them out,
liblink detects some more errors, and calls sysfatal to terminate the
whole process.

**Comment by rsc** [comment]
Please reopen if you can reproduce.
