### ISSUE TITLE
net/smtp: add support for AUTH LOGIN

### ISSUE THREAD

**Issue by homme** [golang/go#9899]
The Microsoft Exchange SMTP server I connect to at work supports `AUTH LOGIN`.  It would be nice to have support for this in `net/smtp`.  

After hunting around I [found and adapted](https://gist.github.com/homme/22b457eb054a07e7b2fb) some MIT licensed code which implements this.  This works for me and I have checked it against Python's [`smtplib`](https://hg.python.org/cpython/file/2.7/Lib/smtplib.py#l611) implementation.  It may, however, benefit from the same TLS checks that are in place in `PlainAuth.Start` as the credentials are similarly sent over the wire in plain text.

I am using go version go1.4.1 linux/amd64.

**Comment by chengweiv5** [comment]
+1 for this feature request.

**Comment by dominikh** [comment]
net/smtp is frozen, this issue can probably be closed.

**Comment by bradfitz** [comment]
Yeah, probably. This could move to a package on github it looks like.
