### ISSUE TITLE
All github repos need CONTRIBUTING.md

### ISSUE THREAD

**Issue by bradfitz** [golang/go#9908]
All the github.com/golang/ repos need the CONTRIBUTING.md file to tell people how we do code review (Gerrit instead of Pull Requests).

And for the subrepos, they should probably mention where the issue tracker is.

And the subrepo descriptions should probably start with or contain "(mirror)" or something to tell people that they're not for PRs or bugs.

**Comment by adg** [comment]
Done!

**Comment by mikioh** [comment]
Just FYI: text, sys, image, exp, sys, example and debug still remain unchanged

**Comment by adg** [comment]
Oops.

Sent:
https://go-review.googlesource.com/5411
https://go-review.googlesource.com/5412
https://go-review.googlesource.com/5413
https://go-review.googlesource.com/5414
https://go-review.googlesource.com/5415

**Comment by adg** [comment]
The example repo is exempt, but the others are done.
