### ISSUE TITLE
reflect: MethodByName(...).Interface().(func()) is extremely slow.

### ISSUE THREAD

**Issue by OneOfOne** [golang/go#9909]
I always assumed `reflect.ValueOf(x).MethodByName("y").Interface().(func()) == x.y`, however running a simple benchmark shows it's almost ~64 slower on Go 1.5 (+0477433) and ~78x slower on 1.4.1.

Is this working as expected or did I miss something?

```shell
➜ go1.5 run /tmp/blah.go -v
 direct 1000000000               2.16 ns/op
reflect 10000000                  136 ns/op
➜ go1.4 run /tmp/blah.go -v
 direct 2000000000               1.66 ns/op
reflect 10000000                  132 ns/op
```

[playground](http://play.golang.org/p/hxTUeBnRqC)

**Comment by bradfitz** [comment]
>  == x.y

Well, to be pedantic, == isn't defined for function values. Only against nil.

But yes, reflect is pretty slow. It's not as slow as it used to be, but it's slow.

**Comment by OneOfOne** [comment]
I just thought calling `.Interface()` on the returned value would return the actual function pointer (vs. calling Value.Call(...)).

**Comment by ianlancetaylor** [comment]
Calling .Interface().(func()) will indeed a return a copy of the actual function value.  But naturally calling through the reflect functions is going to be slower than just referring to x.y directly.  If nothing else it means memory allocations.

I don't see an actual bug here.

**Comment by OneOfOne** [comment]
Here's my reasoning, and excuse me if I'm way off here (I blame the lack of sleep on my cats):
`.Interface().(*X) == x`,  is there a specific reason `.MethodByName("Y").Interface().(func()) != x.Y`?

I realize you can't check for equality on functions, but what I mean is it returns a completely different function (I'm guessing it wraps the `Value` somehow) and that's why it's slow.

Keep in mind I'm not trying to call `Value.Call()`.

http://play.golang.org/p/hSEB6LlaOq

**Comment by ianlancetaylor** [comment]
Function values in Go are not the same as function pointers in C.  See http://golang.org/s/go11func .  You should not expect the values to be the same.

This has absolutely nothing to do with why calling reflect is slower than referring directly to a method.

**Comment by OneOfOne** [comment]
@ianlancetaylor I completely missed that document, closing now.
