### ISSUE TITLE
go/format: align top-of-case comments with case statement

### ISSUE THREAD

**Issue by josharian** [golang/go#9910]
Consider [this code](http://play.golang.org/p/Q_vmjIpRvz)

```go
func sign(i int) int {
	switch i {
	default:
		return 0

	// negative
	case i < 0:
		return -1

		// positive
	case i > 0:
		return 1
	}
}
```

`go/format` leaves the "negative" and the "positive" comments untouched. This is presumably because it is ambiguous whether the comment is associated with the code above or the case statement below.

I'd suggest as a heuristic that if there is a blank line before the comment (or a run of comments with no blank lines) and no blank line afterwards, then it should be aligned with the case statement.

This would fix many misaligned comments in CL 4851.

**Comment by rsc** [comment]
Sometimes you want one or the other. Gofmt preserves what you've done.
The bad comments in the compiler are my fault and should be fixed separately.
