### ISSUE TITLE
misc/makerelease: Incorrect Environment variable GOROOT path

### ISSUE THREAD

**Issue by hc000** [golang/go#9911]
I am using windows 7 64 bit and downloaded the .msi for go.

The MSI sets the GOROOT at c:\go but the GOPATH is not set (contradicts the install docs)

**Comment by minux** [comment]
Which docs state that GOROOT should point to the bin directory? c:\go is
the correct value for GOROOT.

**Comment by mattn** [comment]
@hc000 GOROOT should point to "c:/go" for specifying the version of go which you use(if you have few versions). The MSI sets automatically this. And GOPATH should point path you favorited for specifying the path that you will install third-party libraries or codes.

See http://golang.org/doc/code.html#GOPATH

**Comment by minux** [comment]
Unless our docs are saying GOROOT should point to the bin directory,
this issue is working as intended.
