### ISSUE TITLE
unix: Unlinkat lacks the flag parameter

### ISSUE THREAD

**Issue by minux** [golang/go#9923]
(Linux-only.)

which means for example, one can't use Unlinkat to remove a directory,
which needs AT_REMOVEDIR.

Unfortunately, our syscall package also has this problem.

There are two ways to fix this:
1. add one flags parameter, breaks the API
2. always pass AT_REMOVEDIR as flags to the syscall.

Opinions?

Discovered while working on the ARM64 port, where unlink syscall
is unavailable.

**Comment by bradfitz** [comment]
3. add a new wrapper. can use the correct case: UnlinkAt

**Comment by nightlyone** [comment]
I would vote for always passing `AT_REMOVEDIR`.

Most people simply ignore errors at unlink or look for very specific ones and ignore the rest. The only new error they get is `ENOTEMPTY` from an `syscall.Unlinkat`, which they should actually expect when they look at the man page.

The os-Package, which provides the abstractions to be used, handles this all correctly by looking for specific errors at `os.Remove` and implementing all other functionality using that abstraction.

**Comment by minux** [comment]
After posting the issue, I realized that if I always add AT_REMOVEDIR, then
that will turn it into RmdirAt. i.e. it can no longer remove regular files....

so we will have to introduce a new function unix.UnlinkAt that contains the new
flags argument.

**Comment by dirk** [comment]
Can this be closed now that `Unlinkat` has been given a third flags argument in golang/sys@bfff0ae28b4728bd08d00d0fee164ff85a8c3275?

**Comment by justincormack** [comment]
This was broken again by

https://github.com/golang/sys/commit/b10968a4460ed90e1d0dcd386a49ba964cd21f23

Which reintroduced the two argument Unlinkat call, so there is no way to provide the flags (Rmdir only works with AT_FDCWD).
