### ISSUE TITLE
runtime: TestGdbPython fails on OS X

### ISSUE THREAD

**Issue by josharian** [golang/go#9927]
The support script is not being loaded.

```bash
$ go test -run=Gdb -v runtime
=== RUN TestGdbPython
--- FAIL: TestGdbPython (0.29s)
	runtime-gdb_test.go:68: failed to load Go runtime support: Breakpoint 1 at 0x2000: file /private/var/folders/jw/xrvq7wz95p5bwvjyx9yc2npm390cfb/T/go-build145181164/main.go, line 4.
FAIL
exit status 1
FAIL	runtime	0.296s
```

This is not #8973 or #5221; the symbol is present.

This is not #9820; `otool -s __DWARF __debug_gdb_scri a.exe` yields the correct language identifier and script path.

Suggestions for what to try next? Objections to simply disabling the test on OS X, as most OS X users use lldb anyway?

**Comment by minux** [comment]
it's a known bug of gdb on os x.

i think it looks for __debug_gdb_script section although that section name
is impossible for Mach-O.

**Comment by josharian** [comment]
Thanks, Minux. I was somehow convinced that it worked in Go 1.3...and I was wrong.
