### ISSUE TITLE
cmd/dist fails w/o .git or VERSION with no actionable error message

### ISSUE THREAD

**Issue by proppy** [golang/go#9932]
Building a [tarball snapshot](https://github.com/golang/go/archive/master.tar.gz) fails with the following error, because the source tree is not a git repo:
```
...
##### Building compilers and Go bootstrap tool for host, darwin/amd64.
++ buildall=-a
++ '[' --no-banner = --no-clean ']'
++ ./cmd/dist/dist bootstrap -a -v
fatal: Not a git repository (or any of the parent directories): .git

go tool dist: FAILED: git rev-parse --abbrev-ref HEAD
```

An "easy" [workaround](https://github.com/golang/go/blob/5f1efe738be296cdbc586348af92eab621d068f5/src/cmd/dist/build.go#L278) is to create a `VERSION `file, it would be nice if the error message was pointing that out.

**Comment by bradfitz** [comment]
Yeah, a nicer error message would be good there.

/cc @adg
