### ISSUE TITLE
x/website: a modern or better design for golang.org / godoc.org / Go's official websites

### ISSUE THREAD

**Issue by redstrike** [golang/go#9936]
Hello,

Go is very awesome, but I think Go's official websites should have a better design. It's really not eyes-friendly / eyes-catching for looking up tutorials, docs, API references. They should have a better syntax highlight themes. For someone who is not a hardcore programmer or native English speaker like me, it's really terrible to scan/skim/read the contents on Go's websites. The poor design of official websites makes Golang looks like an old programming language (this is the feeling not logic).

Below is random websites which are eyes-friendly / eyes-catching than Go's:
http://developer.android.com/
https://developer.apple.com/swift/
https://www.python.org/
http://symfony.com/
https://www.djangoproject.com/
http://laravel.com/
http://fatfreeframework.com/home
http://hacklang.org/
http://hhvm.com/
http://php.net/

Forgive me if your eyes have no problems while looking up for docs, API refs on Golang's websites :)

**Comment by parkr** [comment]
I actually really prefer the aesthetic of Golang.org and Godoc.org. Due to the lack of noise and fluff, it is really easy to read and make contributions to. I think it's great as-is.

**Comment by adg** [comment]
It is very subjective, but the web site needs work and I hope to have it
improved over the next few months.

**Comment by harshavardhana** [comment]
:+1:

**Comment by bcmills** [comment]
CC @spf13

**Comment by spf13** [comment]
@andybons and I have been working on this for the past while. We should have something up in the next few weeks.

**Comment by seankhliao** [comment]
I believe this is mostly covered by the consolidation onto go.dev as announced by the [blog post](https://go.dev/blog/tidy-web)
