### ISSUE TITLE
tools/imports: import misplaced when multiple groups present

### ISSUE THREAD

**Issue by josharian** [golang/go#9940]
Run goimports to pick up the missing `image` import:

```go
package main

import (
	"io"
	"math"

	"code.google.com/p/graphics-go/graphics"

	_ "image/png"
)

func main() {
	var r io.Reader
	img, _, _ := image.Decode(r)
	graphics.Rotate(img, img, graphics.RotateOptions{Angle: math.Pi})
}
```

Got:

```go
import (
	"io"
	"math"

	"code.google.com/p/graphics-go/graphics"

	"image"
	_ "image/png"
)
```

Want:

```go
import (
	"image"
	"io"
	"math"

	"code.google.com/p/graphics-go/graphics"

	_ "image/png"
)
```

/cc @bradfitz for opinions

**Comment by bradfitz** [comment]
No opinions.

**Comment by minux** [comment]
I like the current grouping, related packages are together. I don't
separate out blank imports as a another group of their own. It doesn't look
good if, say, we import image/jpeg and then a database/sql driver in a
single group.

**Comment by josharian** [comment]
@minux that's fair. To be clear, I wasn't suggesting that goimports pull blanks out separately; the issue was about where goimports placed the new `image` import, once the three sections were already present.

**Comment by josharian** [comment]
Fixed by CL 8090.
