### ISSUE TITLE
archive/zip: no such file/directory Java-generated zip (apk) files

### ISSUE THREAD

**Issue by ykamat** [golang/go#9943]
Error while unzipping a apk and jar files. Normal zip files are getting unzipped perfect.
:no such file or directory error

package main

import (
	"archive/zip"
	"flag"
	"fmt"
	"os"
	"io"
	"path/filepath"
	//"strings"
	//"log"
)

func main() {
	flag.Parse() //parse command line arguments
	zipfile := flag.Arg(0)
	//check zip file name is passed as argument
	if zipfile == "" {
		fmt.Println("Usage: godex pathofapk")
		os.Exit(1)
	}
	//open reader to read zip file
	reader, err := zip.OpenReader(zipfile)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	} // check for valid zip file
	defer reader.Close()

	for _, f := range reader.Reader.File {
		zipped, err := f.Open()
		//fmt.Println(f)
		if err != nil {
			fmt.Println(err)
			os.Exit(1)
		}
		defer zipped.Close()
		path := filepath.Join("", f.Name)
		if f.FileInfo().IsDir() {
			os.MkdirAll(path, f.Mode())
			fmt.Println("Creating Directory", path)
		} else {
			writer, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE, f.Mode())
			if err != nil {

					fmt.Println(err)
					os.Exit(1)

			}
			defer writer.Close()
			if _, err = io.Copy(writer, zipped); err != nil {
				fmt.Println(err)
				os.Exit(1)
			}
			fmt.Println("Decompressing: ", path)
		}
	}
	//os.Rename("goSwiff_v3.1.1_UAT.apk","goSwiff_v3.1.1_UAT.zip")
}

**Comment by ykamat** [comment]
go version go1.4.1 darwin/amd64

**Comment by crawshaw** [comment]
Can you share an example file that's failing to open?

**Comment by ykamat** [comment]
https://www.dropbox.com/sh/qwkkzdyn3g7alef/AABGTMQOsVfOLgm1ct-S7tXfa?dl=0

Two apk files and the code file godex.go are both available.

**Comment by ebfe** [comment]
$ go run godex.go Contacts.apk
    open META-INF/MANIFEST.MF: no such file or directory

I don't think thats a problem with the zip package. The error comes from the os.OpenFile("META-INF/MANIFEST.MF",...) call. Note that the META-INF directory does not exist.

**Comment by crawshaw** [comment]
I tried your program on one of the files provided, and there appears to be no problem opening the file with the zip package. You need to create the directories as @ebfe said, and close file descriptors sooner.

**Comment by ykamat** [comment]
apologies but i tried this with 2 zip files which are getting unzipped fine with relevant folders getting created.

also in goswiff apk file  dex and xml files are getting uncompressed if i do a continue instead of printing the error.
