### ISSUE TITLE
cmd/present: navigational help text is distracting when writing slides

### ISSUE THREAD

**Issue by josharian** [golang/go#9950]
I'm writing some slides right now and the help text is driving me bonkers. It is a distraction every time I switch from editor to browser and reload, particularly when it covers text and/or the Run button.

Can we do one of these:

* Disable it when on localhost/127.0.0.1
* Use local storage and/or cookies to only display it once per browser
* Accept a flag to present to disable it (which would have to be passed on to the javascript somehow)

// cc @adg

**Comment by davecheney** [comment]
We can't win.

Newcomers want the help text. Old hands don't care for it at all.

**Comment by josharian** [comment]
My suggestions were intended to try to preserve the helpful behavior for newcomers without being in the way for folks like me. (And I wouldn't mind it if I was just browsing through talks. It's when I'm hitting refresh every other minute that it is bothersome.) I'm open to other suggestions. I'm pretty sure there's a way.

**Comment by adg** [comment]
On 21 February 2015 at 11:48, Josh Bleecher Snyder <notifications@github.com
> wrote:

> Disable it when on localhost/127.0.0.1


Works for me.

**Comment by davecheney** [comment]
Other google properties have standardised on ? to display the help text.
That would be my suggestion.

**Comment by adg** [comment]
On 23 February 2015 at 21:55, Dave Cheney <notifications@github.com> wrote:

> Other google properties have standardised on ? to display the help text.
> That would be my suggestion.
>

Having a magic key to press to get the help text defeats the whole purpose
of the help text.
