### ISSUE TITLE
strings.ToTitle works as ToUpper instead of capitalizing

### ISSUE THREAD

**Issue by sanatgersappa** [golang/go#9956]
Looks like a regression of #933.

See http://play.golang.org/p/27QjEvE6nC

Tested on Go 1.4.2 (windows/amd64)

**Comment by minux** [comment]
http://golang.org/pkg/strings/#ToTitle

ToTitle returns a copy of the string s with all Unicode letters mapped to their title case.

**Comment by sanatgersappa** [comment]
Sorry, my bad. Found that Title() does what I need.
