### ISSUE TITLE
cmd/gc: Wrong error message: "internal compiler error: dowidth: unknown type:"

### ISSUE THREAD

**Issue by rivo** [golang/go#9957]
go version go1.4 darwin/amd64

	package main

	type A struct {
		S []string
	}

	func f(a A, s []string) []string {
		return append(a, s...)
	}

will result in the following error message:

	line 4: internal compiler error: dowidth: unknown type: S []string

The actual error is in line 8 where `a` (the struct) is used instead of `a.S` (a field of the struct). I would expect an error message along the lines of

	line 8: first argument to append must be slice; have struct

In my case, the buggy `append()` code was in a different file so it was very hard to track down because the error fired in the wrong place.

**Comment by ianlancetaylor** [comment]
Dup of #9634, which is fixed on tip.

**Comment by minux** [comment]
Have you tried 1.4.2? I think the error has been fixed.

**Comment by rivo** [comment]
Indeed. It's fixed in 1.4.2. I had reproduced it on http://play.golang.org/ but now it turns out that the site is still on 1.4.1. Thanks for the reply.
