### ISSUE TITLE
x/review/git-codereview: reject commit messages with non-standard form

### ISSUE THREAD

**Issue by josharian** [golang/go#9958]
In particular, they should be of the form `<some components]: <message>`.

This came up in CL 5542.

**Comment by cmarcelo** [comment]
Duplicate of #9254?

For the reference: it was fixed by golang/review@07daa7f8ec4a577c30537f7e8796159b0e0515a7 that performs the check, asking "y/n" if the commit message doesn't follow the convention.

**Comment by josharian** [comment]
I guess so. The problem occurred after the fix mentioned, but I'll close this for now, since it appears to be a duplicate and it has sat dormant for a long time.
