### ISSUE TITLE
cmd/go: pass line number of generate directive in environment

### ISSUE THREAD

**Issue by prencher** [golang/go#9960]
It would be very useful if the go:generate command gained the ability to pass along file and line to the invoked tool, to avoid redundant definitions.

For example:

```go
//go:generate -l stringer
type Pill int

const (
    Placebo Pill = iota
    Aspirin
)
```

Could pass along something like "Pill.go:42" to stringer.

Alternately, or in addition to, one could imagine //go:generate supporting a mode where it must be defined right before a type, variable or function, such that it could pass along that information to the tool.

**Comment by rsc** [comment]
The file name is already there, in $GOFILE.
Perhaps $GOLINE should say 'foo.go:23'.
Plain GOLINE=23 seems too opaque.

@robpike

**Comment by prencher** [comment]
@rsc Ah, I had missed the $GOFILE environment variable. That's obviously cleaner than having command line arguments to go generate. Adding a $GOLINE to pair with it would be perfect.
