### ISSUE TITLE
x/tools/cmd/goimports: spurious blank line in import block

### ISSUE THREAD

**Issue by rsc** [golang/go#9961]
g% cat /tmp/x.go
	package p
	
	import (
		"testing"
	
		"rsc.io/p"
	)
	
	var (
		_ = flag.String
		_ testing.T
		_ p.P
		_ = regexp.Compile
	)
	g% goimports /tmp/x.go
	package p
	
	import (
		"flag"
		"testing"
	
		"regexp"
	
		"rsc.io/p"
	)
	
	var (
		_ = flag.String
		_ testing.T
		_ p.P
		_ = regexp.Compile
	)
	g% 

The blank line between "testing" and "regexp" shouldn't be there (and then regexp should be sorted above testing). This appears to be a minimal example.

**Comment by bradfitz** [comment]
/cc @josharian @griesemer @crawshaw and anybody who likes using the go/ast package.

I'm going to unassign myself so it doesn't look like I'm working on this.

**Comment by josharian** [comment]
Started.
