### ISSUE TITLE
crypto/x509: parseCertificate fails if Cert Policy extension is critical

### ISSUE THREAD

**Issue by mvanotti** [golang/go#9964]
Minimal Test Case: http://play.golang.org/p/ihE8Lkqw66
At the end there's a certificate with a Cert Policy  extension marked as critical.

parseCertificate fails because it is missing a continue at the end of case 32.
https://github.com/golang/go/blob/fe40cdd75676398/src/crypto/x509/x509.go#L1051-L1061

Refer to RFC 5280 Section 4.2.1.4

Adding a simple continue at the end will fix the issue.

**Comment by agl** [comment]
https://go-review.googlesource.com/#/c/5670/
