### ISSUE TITLE
x/tools/cmd/vet: should warn for single-case select statement without a default case

### ISSUE THREAD

**Issue by jonhoo** [golang/go#9966]
After about a day of debugging a problem in which a part of my application suddenly stalled, I came across this piece of code:

``` go
select {
    case ch <- true:
}
```

where ch happened to be an unbuffered channel without a reader.
This was as expected, but the author had meant the select to make the send non-blocking. Unfortunately, without an empty default, this is a _blocking_ channel send. The code should instead have looked like this:

``` go
select {
    case ch <- true:
    default:
}
```

After encountering this, I tried to come up with a use-case for a single-case select statement _without_ a default case, but could not come up with one. Any such code fragment would just be a blocking send on a channel followed by other code; there is no need for the select, and it should be removed to avoid confusion. In the common case, the author probably made the same mistake in the above code and simply forgot the default case necessary to make the code non-blocking.

I initially proposed that go should give a build error when encountering a single-case select without a default on [go-nuts](https://groups.google.com/forum/#!topic/golang-nuts/cHE5m_p9fS8), but valid concerns were quickly raised that this would complicate debugging where you occasionally want to leave the select in place while figuring out which cases to have. Making it a build error would also invalidate `select { }` for infinite blocking which is apparently used occasionally.

However, I still believe this is a confusing, and potentially harmful, pattern, and it seems sensible that `go vet` would warn that this particular construct is unnecessary, and will not be non-blocking.

**Comment by lloydde** [comment]
May I suggest updating this github issue's Title to something specific like "vet should warn if single-case select statement without a default case"

**Comment by josharian** [comment]
/cc @robpike @dsymonds for initial reactions about adding this check.

@jonhoo I think that the actual implementation should be pretty straightforward, so if you have any interest in hacking on vet, this is a good starter project.

**Comment by jonhoo** [comment]
@josharian I'll have a look.
@lloydde Seems I forgot to finish the title.. Thanks!

**Comment by dsymonds** [comment]
I don't see this flying. It's legitimate, albeit odd code. Where does it end? Are you going to suggest flagging `for {}` next?

**Comment by jonhoo** [comment]
No, I think this is different. A select with a single case is rarely ever used without a default, simply because it is not necessary or useful. A `for {}` on the other hand is useful to emulate infinite loops and loops with complex termination conditions. When people write a single case select, I suspect they generally do it because they want a non-blocking channel operation.

Missing the `default:` case for a non-blocking op is also a tricky error to detect, because it might only block in corner cases or due to a race.

**Comment by andrewchambers** [comment]
Perhaps someone could do a code search on github/stdlibrary.
If the cases that are found are bugs, it's probably worth it.

Silent and unintentional deadlock could be quite serious. This code pattern should probably always be replaced by a normal channel operation anyway.

**Comment by jonhoo** [comment]
@andrewchambers: That seems like a good idea. Getting some quantitative measurement of whether this is a sensible change would be useful. What is the best way of performing such a search though?

I've also implemented the proposed change here: https://github.com/jonhoo/tools/compare/singleselect. Any comments are welcome. Unfortunately, the change does require modifying the dead code test data as it uses single-case selects in multiple places.

**Comment by adg** [comment]
> I don't see this flying. It's legitimate, albeit odd code. Where does it end? Are you going to suggest flagging for {} next?

@dsymonds there is absolutely no reason why you would write `select { case c <- true: }` instead of `c <- true`. Now that you mention it, flagging `for {}` seems like a reasonable idea too.

**Comment by jonhoo** [comment]
@adg: I thought the argument made by Dmitri for why `select { case c <- true: }` might be legitimate [on go-nuts](https://groups.google.com/d/msg/golang-nuts/cHE5m_p9fS8/_HWEuqACBmUJ) was quite good. It certainly convinced me that making this a **build** error would be a bad idea. I do think it's sensible for `go vet` to complain about it though.

For `for {}`, the case doesn't seem as clear-cut, as this is a sensible construct for application with an actually infinite main event/dispatch loop, loops with multiple exit conditions where exit condition enumeration might make it clearer what's going on, and for loops with dynamic exit conditions.

**Comment by cespare** [comment]
@jonhoo @adg is referring to literally `for {}`, not `for { /* stuff inside */ }`. `for {}` doesn't have any legitimate use I'm aware of; if you want to block forever `select {}` is what you want (although even that is usually an indication you're doing something wrong).

**Comment by jonhoo** [comment]
@cespare: ah, got it. Thanks for clarifying.

**Comment by ianlancetaylor** [comment]
There is a difference between "for {}" and "select { case <-c: }": the latter can be replaced by "<-c" with no change in functionality.  A single case select can always be replaced by a simpler construct.

**Comment by minux** [comment]
I'm wonder if gofmt -s should simply single case selects?
If go vet flags it as an error, perhaps gofmt should help in this case?

**Comment by griesemer** [comment]
Generally, gofmt -s only simplifies if there's near universal agreement that the simpler form is "better". This is pretty clear for say for "a, _ = range x" which becomes "a = range x", etc.

Also, if code is under development, simplifying the select may not be desirable.

I have long advocated a -ss mode ("strong simplify") which could do things like this (and more); and which wouldn't be restricted as much as "-s".

**Comment by jonhoo** [comment]
Yeah, I'm with @griesemer; this doesn't seem like something you would want `gofmt -s` to do. `gofmt -ss` seems like a great idea, though it's probably a discussion for a different thread.

**Comment by FrankReh** [comment]
Here's a single case select I just ran into that looks like a reasonable
use (has nothing to do with reading from a channel however):

                switch cursor.Kind() {

                case clang.CK_ClassDecl, clang.CK_EnumDecl,

                        clang.CK_StructDecl, clang.CK_Namespace:

                        return clang.CVR_Recurse

                }

                return clang.CVR_Continue

**Comment by jonhoo** [comment]
That's a `switch`, not a `select`. Single-case `switch` statements make perfect sense (especially when they have multiple switch values).

**Comment by FrankReh** [comment]
Whoops - sorry.  (insert red face)

**Comment by gordonklaus** [comment]
For whoever implements this, I guess you might as well also deal with the case of a select with only a default case:

```go
select {
default:
    // ...
}
```

A similarly useless construct comes to mind, in which the programmer probably forgot to write `go` before a function literal call expression:

```go
func() {
    // ...
}()
```

**Comment by cznic** [comment]
> A similarly useless construct comes to mind, in which the programmer probably forgot to write go before a function literal call expression:

This construct has a legitimate use case:

```go
for _, file := range veryLongFileList {
        f, err := os.Open(file)
        if err != nil {
                return nil, err
        }

        func() {
                defer f.Close()

                if err = foo(f); err != nil {
                        return
                }

                if err = bar(f); err != nil {
                        return
                }

                ...
        }()

        if err != nil {
                return nil, err
        }

        return thing, nil
}

**Comment by jonhoo** [comment]
@gordonklaus: Good idea. Added the test for that in jonhoo/tools@b235d59f5dff4374956184847f6c18c8801d3744.

**Comment by gordonklaus** [comment]
@cznic I forgot about this use of a func literal call.  Is it common?  It may still be worth flagging it in go vet.  And it's simple enough to check for `defer` statements before simplifying such a construct via go vet -s (or -ss).

**Comment by gordonklaus** [comment]
... go vet would also have to check for `return` statements before simplifying a func literal call, just as it would have to check for `break` statements before simplifying a single-case select statement.

**Comment by josharian** [comment]
I ran the modified vet from @jonhoo over a very recent corpus of Go code. It found 1339 cases. The full results are here: https://gist.github.com/josharian/9895ee2c66147a6aa70d. I looked at a couple of them and didn't find anything that looked like a bug, just needless verbosity. (Please feel free to look through the list and demonstrate otherwise.) Given that, I'm inclined to say that this is a better fit for gofmt -ss than for vet. I opened #9983 for gofmt -ss.

**Comment by dominikh** [comment]
Wouldn't `golint` also be a plausible place for putting this check? Using `select{}` with a single case could qualify as a style issue.

**Comment by jonhoo** [comment]
@josharian: Interesting. In fact, a number of these should probably be modified to be `for c := range ch {...}` instead of `for { select { case c <- ch: ... } }` to correctly handle closed channels.

**Comment by jonhoo** [comment]
@josharian: The argument for keeping this in `vet` is that this *could* cause unexpected deadlocks, and it is a completely unnecessary construct if it doesn't.

**Comment by andrewchambers** [comment]
Guys, stop discussing fmt issues unrelated to single case select. Create other issues/forum posts if you want to discuss them further.

@josharian Thanks for running that analysis, Based on that, I think the odds that at least a few of them aren't bugs is probably pretty small. 

I think this is a great addition in that it can find bugs and style issues and needs no complicated context to do so.

**Comment by jonhoo** [comment]
The changes to `testdata/deadcode.go` are unfortunate though, as they effectively reduce deadcode test coverage. The "right" way to solve this is to only run a particular test on its own test data, or to add ERROR expectations to `testdata/deadcode.go`. The former seems like a better solution, though I'm not sure it's a change that would be sensible to make to merge this feature.

**Comment by rsc** [comment]
Vet is about clear correctness problems. This code does not seem clearly wrong to me. Especially since we want to move toward vet being nearly-mandatory for running tests, this report does not seem precise enough.
