### ISSUE TITLE
cmd/gc: reenable custom syntax error messages

### ISSUE THREAD

**Issue by rsc** [golang/go#9968]
The C cmd/gc had nice errors via the bisonerrors script.
Need to make that work in the Go version too.
For now the tests will be disabled.

**Comment by rsc** [comment]
These are the affected files:

	Author:     Russ Cox <rsc@golang.org>
	CommitDate: Mon Feb 23 14:00:51 2015 -0500
	
	    [dev.cc] test: disable syntax error tests
	    
	    These don't work with the new compiler, because the
	    new compiler doesn't have the custom syntax errors
	    that I built for the old compiler. It will, just not yet.
	    (Issue #9968.)
	    
	    Change-Id: I658f7dab2c7f855340a501f9ae4479c097b28cd3
	
	 test/fixedbugs/bug121.go    | 3 +++
	 test/fixedbugs/bug349.go    | 3 +++
	 test/fixedbugs/bug388.go    | 3 +++
	 test/fixedbugs/bug435.go    | 3 +++
	 test/fixedbugs/issue4468.go | 3 +++
	 test/run.go                 | 3 ++-

**Comment by mdempsky** [comment]
I took a first stab at this in https://go-review.googlesource.com/#/c/7270/.  It at least restores fixedbugs/bug121.go and fixedbugs/issue4468.go.  It's kind of hacky though, so I'd appreciate feedback on whether this is worth pursuing before I invest more time into it.

**Comment by minux** [comment]
for our yacc, i think we can do better.

for example, could we integrate the custom error message into the .y file
itself?

**Comment by mdempsky** [comment]
I think that's doable.  We could have yacc process the go.errors file (or add it to go.y somehow), and it can just pass the new error string to yyLexer.Error instead of "syntax error".

Maybe lines like

    "%error" string_lit { identifier }

E.g.,

        % loadsys package imports LCHAN ')'
                "unexpected ) in channel type"},

could become

    %error "unexpected ) in channel type" loadsys package imports LCHAN ')'

in go.y?

**Comment by rsc** [comment]
I'd still like the error text to come after the description of what provokes it. But otherwise it seems fine. Maybe use a colon to separate them:

%error loadsys package imports LCHAN ')':
    "unexpected ) in channel type"

**Comment by andrewchambers** [comment]
This is really nice, some additions into doc.go might be appreciated because the plan9 yacc docs don't cover this feature.

**Comment by minux** [comment]
I filed #10888 for the docs issue.
