### ISSUE TITLE
builder: darwin/arm broken

### ISSUE THREAD

**Issue by crawshaw** [golang/go#9971]
(I have been working on this for a few days now, creating a bug for the curious.) There are several problems with darwin/arm builder.

Fixed:

- go_darwin_arm_exec: needs to serialize access to ios-deploy
- go_darwin_arm_exec: not passing test arguments (in particular, -test.short=true)
- cmd/go: tests need to be compiled with cgo
- iOS 8.1.3: required a different Entitlements.plist format (discovered via trial and error)
- crypto/x509: no access to certs

Still to do:

- go_darwin_arm_exec: get it reviewed and submit
- go_darwin_arm_exec: check that testdata is being copied into the app properly
- on an iPhone 4S builder, sometimes: fatal error: runtime: cannot reserve arena virtual address space
  considering falling back to a 128mb heap, trying to determine the consequences

**Comment by crawshaw** [comment]
virtual memory allocation: https://github.com/golang/go/commit/85d09574fd2ed789eb5550a04eae1d261aaf4d17

**Comment by minux** [comment]
We also need to make lldb don't stop on most signals
(e.g. lldb stopping on SIGPIPE is causing the net tests
to timeout.)

On gdb, we can do that with "handle SIGPIPE nostop noprint pass",
I assume lldb also has an equivalent way of specifying that.

**Comment by crawshaw** [comment]
The darwin/arm builder has now done 20 ok runs with no flakes.
