### ISSUE TITLE
oracle: Support finding all implementations of an interface method

### ISSUE THREAD

**Issue by ghodss** [golang/go#9972]
If I give the position of a method of an interface, I should be able to find every method within scope that implements that specific method.

**Comment by alandonovan** [comment]
That's a good idea---generalize the "implements" command so that you don't have to be on a type name, a method name will do.

**Comment by alandonovan** [comment]
I sketched it out here:
https://go-review.googlesource.com/#/c/5860/
Care to try it out and see if it works as expected?

**Comment by ghodss** [comment]
This is awesome, and works perfectly! Thank you!
