### ISSUE TITLE
syscall: support linux variants that don't support deprecated syscalls

### ISSUE THREAD

**Issue by davecheney** [golang/go#9974]
Whew, that issue title is a mouthful.

The issue in question is newer linux ports, amr64 being the one in question, have dropped support for a number of "legacy" syscalls, ie `open(2)` was replaced by `openat(2)`, and so on.

The ppc64 port also faced similar issues (`select(2)` has been replaced by `pselect6(2)` for example), but not as severe.

**Comment by rsc** [comment]
Looks like this was done by making, say, Open call Openat.
Sounds good to me.
