### ISSUE TITLE
all: std package is always compiled

### ISSUE THREAD

**Issue by mattn** [golang/go#9975]
After upgrade go to HEAD, os/signal, runtime, mime/multipart, etc.... that is always compiled with compiling external package.
If do `go install` in the pacakge directory, the std package is not compiled.

**Comment by adg** [comment]
This is expected. If you don't use "go install" then any dependencies that were updated since the last install will be recompiled.

**Comment by mattn** [comment]
As far as I remember, std package is done already to `go install` after `make.bash`.

**Comment by adg** [comment]
Please provide steps to reproduce the issue.

**Comment by mattn** [comment]
Ooops, sorry. I couldn't reproduce this. Maybe, it may cause that I built go with go1.4 before go1.4.2 .
