### ISSUE TITLE
x/review/git-codereview: weird error when trying to commit a merge

### ISSUE THREAD

**Issue by 4ad** [golang/go#9981]
I have no idea what this means.

	: xgene:go; git commit
	git log --topo-order --format=format:%H%x00%h%x00%P%x00%B%x00%s%x00 origin/master..refs/heads/new2.arm64 --
	fatal: bad revision 'origin/master..refs/heads/new2.arm64'
	
	git-codereview: exit status 128

**Comment by josharian** [comment]
What do `git rev-parse origin/master` and `git rev-parse refs/heads/new2.arm64` show? In theory, that command should display all commits in the range between those two commits.

**Comment by 4ad** [comment]
Sorry, no idea, I deleted the hook and did what I had to do.

But if it happens again (it happened a few times already) I will try those commands.
