### ISSUE TITLE
cmd/gofmt: add strongly simplify flag

### ISSUE THREAD

**Issue by josharian** [golang/go#9983]
@griesemer wrote in #9966:

> I have long advocated a -ss mode ("strong simplify") which could do things like this (and more); and which wouldn't be restricted as much as "-s".

One thing -ss could do is remove the select from selects with only a single case (or default). Again, see #9966.

This issue is for discussion about whether gofmt should have a -ss flag and possibly also to collect ideas for what -ss might do over and above -s.

**Comment by griesemer** [comment]
To be clear: gofmt itself should not contain the actual -ss code - that code should be in an independent package that can be invoked from elsewhere and that's simply hooked up to gofmt.

**Comment by rsc** [comment]
Make a separate tool. Let's not keep piling things into gofmt just because it happens to read and write Go files.

I'd be happy if you want to put this in grind.

**Comment by griesemer** [comment]
Separate tool is fine. I'd still suggest to have the actual machinery factored out into a library so that it can be used easily elsewhere.
