### ISSUE TITLE
cmd/gc: lost many comments during c2go translation

### ISSUE THREAD

**Issue by josharian** [golang/go#9989]
Many comments have been lost. For example, compare the Node type just prior to merge:

https://github.com/golang/go/blob/bceb18e4989aee4971fa1de6bb9f5ba7410d5219/src/cmd/gc/go.h#L247

After merge:

https://github.com/golang/go/blob/master/src/cmd/internal/gc/go.go#L148

It's not just types. For example, there are missing const/enum comments in swt.go:

Before: https://github.com/golang/go/blob/bceb18e4989aee4971fa1de6bb9f5ba7410d5219/src/cmd/gc/swt.c#L16

After: https://github.com/golang/go/blob/master/src/cmd/internal/gc/swt.go#L17

@rsc

**Comment by magical** [comment]
Another example, which I tried to point out in the review.

Before: https://github.com/golang/go/blob/8c195bdf120ea86ddda42df89df7bfba80afdf10/src/cmd/gc/typecheck.c#L496
After: https://github.com/golang/go/blob/b59dd94f331677d28250b51729d5bc888fe4cef0/src/cmd/internal/gc/typecheck.go#L496

**Comment by bradfitz** [comment]
Fixed by https://go-review.googlesource.com/#/c/6899/
