### ISSUE TITLE
crypto/tls: Support for session ticket key rotation

### ISSUE THREAD

**Issue by titanous** [golang/go#9994]
In order to rotate session ticket keys effectively, it is useful for the TLS server implementation to support accepting connections with tickets encrypted with previous key(s). Currently the server supports a single session ticket key, and it is not easy to rotate the key. Also, the server cannot be configured to accept tickets encrypted with old keys.

One solution to this is to add two optional fields to `*tls.Config`:

```go
// GetSessionTicketKey returns the current session ticket key.
GetSessionTicketKey func(*ClientHelloInfo) ([32]byte, error)

// AllowPreviousSessionTicketKeys specifies the number of previous
// unique session ticket keys retrieved from GetSessionTicketKey that
// will be used to accept session tickets.
AllowPreviousSessionTicketKeys int
```

This way the server could cache n previous keys and when a session ticket using an old key is encountered it would send a new session ticket encrypted with the current key.

This is certainly not the only approach that could be taken, just a strawman proposal to start discussion.

/cc @agl

**Comment by rsc** [comment]
Adam, thoughts?

**Comment by agl** [comment]
This is a reasonable request for larger sites. However, I don't expect that it'll make 1.5.

Since this will require a lock in the Config structure, I initially think that it might be best supported by a function: tls.Config.SetSessionTicketKeys([][32]byte) where the first element in the slice is the 'current' key and all the others are candidates.

**Comment by titanous** [comment]
https://go-review.googlesource.com/9072

**Comment by aubble** [comment]
does this mean its coming in 1.5 :D
