### ISSUE TITLE
x/tools/cmd/tipgodoc: indexing is not enabled

### ISSUE THREAD

**Issue by speter** [golang/go#9996]
Indexing (search) is available on https://golang.org/ but not on https://tip.golang.org/ . Is there any particular reason for this? (A quick search of issues and the groups didn't seem to bring up anything relevant.)

Unless it has been disabled on purpose, I think it would be preferable if search for tip worked just like on https://golang.org/ , especially considering that tip pages are excluded from search engines.

**Comment by adg** [comment]
It wasn't disabled on purpose, it just wasn't explicitly enabled.
To change this, we'll need to modify the tipgodoc server's "health check"
to wait for the index to be ready.

**Comment by speter** [comment]
Am I right to assume that by health check you are referring to this loop?
https://github.com/golang/tools/blob/264bffc00c400ce4401cc2be15ed56e18a12e889/cmd/tipgodoc/tip.go#L183
Would issuing a search query request and checking that the response doesn't contain "Indexing in progress: result may be inaccurate" suffice? (That message is defined here: https://github.com/golang/tools/blob/264bffc00c400ce4401cc2be15ed56e18a12e889/godoc/search.go#L69)

In addition the timeout probably needs to be increased from 15s; I'm not quite sure what a suitable value would be, but for reference it takes 72s with an empty GOPATH on my machine (Intel(R) Core(TM) i5-4200U CPU).

**Comment by speter** [comment]
I also found that godoc reindexes every 5 minutes, displaying "Indexing in progress: result may be inaccurate" again. It seems that setting Corpus.IndexInterval to -1 would stop the reindexing (with tipgodoc a new instance is started on a change anyway), but there doesn't seem to be a way to control that value from outside. 

Coincidentally I've never encountered this message on golang.org; is it running a modified version? In that case it would seem to be the easiest to do whatever golang.org does. Otherwise, would adding an environment variable make sense? (I imagine adding a command line flag would complicate the user interface for little benefit, and according to the comment at https://github.com/golang/tools/blob/264bffc00c400ce4401cc2be15ed56e18a12e889/godoc/index.go#L1544 this may become unnecessary in case it is changed to use fsnotify in the future.)

Although even with reindexing running every now and then, I'd consider it to be an improvement over the current situation of no search.

**Comment by adg** [comment]
golang.org is running a different version; the app engine version see cmd/godoc/appmain.go. 

But don't worry about that.
Much easier is just to plumb through a flag to configure the indexing interval.

**Comment by speter** [comment]
closing this as the changes have been deployed and indexing (search) working fine on tip.golang.org for a long time.
