### ISSUE TITLE
refactor/rename: "continue" position error

### ISSUE THREAD

**Issue by AngangGuo** [golang/go#9999]
In "https://go.googlesource.com/tools/+/master/refactor/rename/rename.go#194", the code like this:

		if r.hadConflicts {
			continue // ignore errors; leave the existing name
			unchangedFiles = append(unchangedFiles, f.Name.Name)
		}

the line below the "continue" will never be executed. The order of these two lines should be exchanged like this:

		if r.hadConflicts {
			unchangedFiles = append(unchangedFiles, f.Name.Name)
			continue // ignore errors; leave the existing name
		}

**Comment by andrewaustin** [comment]
This was fixed in https://github.com/golang/tools/commit/e591801c2d4e9296e6c1912b807665f160c01345 

For some reason "Fixes #9999" did not close this issue?
